### PR TITLE
Use relative path for JDK 17-based AppCDS dump

### LINKED ISSUE #33069: AppCDS build step with JDK 17 source/target uses absolute classpath
### Describe the bug

When creating an AppCDS jsa archive Quarkus' `AppCDSBuildStep` class uses absolute paths for the class path when the dynamic archive is being dumped with `-XX:ArchiveClassesAtExit=<jsa-file>`. This makes the feature less usable, since on systems where the exact same classpath would be available, yet the **absolute** path to the jar file is different mapping the CDS archive fails.

The JDK is smart enough to handle the relative class path use-case, thus, using relative paths would be the preferred option. Using the older `-Xshare:dump` with classlist file doesn't seem to have that problem.

### Expected behavior

AppCDS archive usable if JDK matches, classpath matches, yet the absolute path to the jar(s) is different.

### Actual behavior

JVM fails to map the CDS archive. Example with `-Xshare:on` so as to provoke a JVM start error when mapping fails:

```
$ java -Xlog:cds,class+path -Xshare:on -XX:SharedArchiveFile=app-cds.jsa -jar getting-started-1.0.0-SNAPSHOT-runner.jar 
[0.001s][info][class,path] bootstrap loader class path=/usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/modules
[0.005s][info][cds       ] trying to map /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/server/classes.jsa
[0.005s][info][cds       ] Opened archive /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/server/classes.jsa.
[0.005s][info][cds       ] Archive was created with UseCompressedOops = 1, UseCompressedClassPointers = 1
[0.005s][info][cds       ] Core region alignment: 4096
[0.005s][info][cds       ] trying to map app-cds.jsa
[0.005s][info][cds       ] Opened archive app-cds.jsa.
[0.005s][info][cds       ] Archive was created with UseCompressedOops = 1, UseCompressedClassPointers = 1
[0.005s][info][cds       ] Reserved archive_space_rs [0x0000000800000000 - 0x0000000801c00000] (29360128) bytes
[0.005s][info][cds       ] Reserved class_space_rs   [0x0000000801c00000 - 0x0000000841c00000] (1073741824) bytes
[0.005s][info][cds       ] Mapped static  region #0 at base 0x0000000800000000 top 0x0000000800458000 (ReadWrite)
[0.005s][info][cds       ] Mapped static  region #1 at base 0x0000000800458000 top 0x0000000800be1000 (ReadOnly)
[0.005s][info][class,path] Expecting BOOT path=/usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/modules
[0.005s][info][class,path] Expecting -Djava.class.path=
[0.005s][info][class,path] checking shared classpath entry: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/modules
[0.005s][info][class,path] ok
[0.005s][info][cds       ] Mapped dynamic region #0 at base 0x0000000800be1000 top 0x0000000801180000 (ReadWrite)
[0.005s][info][cds       ] Mapped dynamic region #1 at base 0x0000000801180000 top 0x0000000801941000 (ReadOnly)
[0.005s][info][class,path] Expecting BOOT path=/usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/modules
[0.005s][info][class,path] Expecting -Djava.class.path=/home/sgehwolf/Documents/openjdk/quarkus/quarkus-quickstarts/getting-started/target/getting-started-1.0.0-SNAPSHOT-runner.jar
[0.005s][info][class,path] checking shared classpath entry: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/modules
[0.005s][info][class,path] ok
[0.005s][info][class,path] checking shared classpath entry: /home/sgehwolf/Documents/openjdk/quarkus/quarkus-quickstarts/getting-started/target/getting-started-1.0.0-SNAPSHOT-runner.jar
[0.005s][info][class,path] ok
[0.005s][info][class,path] [APP classpath mismatch, actual: -Djava.class.path=getting-started-1.0.0-SNAPSHOT-runner.jar
An error has occurred while processing the shared archive file.
shared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure)
Error occurred during initialization of VM
Unable to use shared archive.
```

### How to Reproduce?

Reproducer

1. Build with `-Dmaven.compiler.source=17 -Dmaven.compiler.target=17 -Dquarkus.package.create-appcds=true -Dquarkus.package.type=uber-jar` (e.g. `getting-started` from quarkus-quickstarts)
2. `cd target`
3. `mkdir test && cp app-cds.jsa getting-started*.jar test && cd test`
4. `java -Xshare:on -XX:SharedArchiveFile=app-cds.jsa -jar getting-started-1.0.0-SNAPSHOT-runner.jar`

Note that if run from the `target` folder, not the subfolder `test` (i.e. build time identical), using the CDS archive works.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17.0.7

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

6c7268b90a6f0d76cea39c3ad4520526e66275d9

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jerboaa**
This makes the AppCDS feature more portable where the build and deployment paths differ, but are otherwise identical (for example s2i use-case).

Closes: #33069

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Assuming this has been tested on the environments you have in mind (and passes our CI),  LGTM

**Comment by gsmet** [comment]
@Sanne looks like the Oracle image doesn't start anymore.

The container log files has this at the very end:
```
2023-05-02T23:28:36.4500082Z CONTAINER: DONE: Creating pluggable database, duration: 14 seconds.
2023-05-02T23:28:36.4500640Z CONTAINER: application database not ready for service, aborting!
2023-05-02T23:28:36.4502096Z Please report a bug at https://github.com/gvenzl/oci-oracle-free/issues with your environment details.
```

I don't see people complaining there so not sure why it's always failing for us.

**Comment by Sanne** [comment]
@gsmet thanks for the ping, I can reproduce locally..  opened #33081 , I'll see what we can do quickly.

**Comment by jerboaa** [comment]
> Assuming this has been tested on the environments you have in mind (and passes our CI), LGTM

Thanks for the review!

I have tested this in a container env (similar to what s2i does). Fails prior and passes after the fix.

`fast-jar` packaging type (before):
```
$ podman run --rm -ti quarkus-app-fastjar:1.1 
An error has occurred while processing the shared archive file.
Required classpath entry does not exist: /home/jboss/app/target/quarkus-app/quarkus-run.jar
Error occurred during initialization of VM
Unable to use shared archive.
```

`fast-jar` packaging type (after):
```
$ podman run --rm -ti quarkus-app-fastjar:1.2
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-05-03 12:47:38,669 INFO  [io.quarkus] (main) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.555s. Listening on: http://0.0.0.0:8080
2023-05-03 12:47:38,691 INFO  [io.quarkus] (main) Profile prod activated. 
2023-05-03 12:47:38,691 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, smallrye-context-propagation, vertx]
^C2023-05-03 12:47:46,315 INFO  [io.quarkus] (Shutdown thread) getting-started stopped in 0.029s
```

`uber-jar` packaging type (before):
```
$ podman run --rm -ti quarkus-app-uberjar:1.1
An error has occurred while processing the shared archive file.
Required classpath entry does not exist: /home/jboss/app/target/getting-started-1.0.0-SNAPSHOT-runner.jar
Error occurred during initialization of VM
Unable to use shared archive.

```

`uber-jar` packaging type (after):
```
$ podman run --rm -ti quarkus-app-uberjar:1.2
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-05-03 12:45:07,978 INFO  [io.quarkus] (main) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.379s. Listening on: http://0.0.0.0:8080
2023-05-03 12:45:08,001 INFO  [io.quarkus] (main) Profile prod activated. 
2023-05-03 12:45:08,001 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, smallrye-context-propagation, vertx]
^C2023-05-03 12:45:20,117 INFO  [io.quarkus] (Shutdown thread) getting-started stopped in 0.023s
```

**Comment by geoand** [comment]
👌

**Comment by geoand** [comment]
Can you please rebase this onto `main` so we can pick up some CI fixes?

**Comment by jerboaa** [comment]
> Can you please rebase this onto `main` so we can pick up some CI fixes?

Done.

**Comment by geoand** [comment]
🙏🏼

**Pull request merged**
