### PR TITLE
Use the Quarkus configured ObjectMapper in Redis client

### LINKED ISSUE #44934: Redis JsonCodec use ObjectMapper without jsr310
### Describe the bug

JsonCodec use ObjectMapper from DatabindCodec.mapper(). Received mapper contains only io.vertx.core.json.jackson.VertxModule.
https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/codecs/Codecs.java#L64

As a result, if a list of objects is cached that contains a date/time, when trying to deserialize it, an exception is thrown that there is no jsr310 module.

ObjectMapper in Arc contains next modules by default
- VertxTypes
- jackson-datatype-jsr310
- com.fasterxml.jackson.datatype.jdk8.Jdk8Module
- jackson-module-parameter-names

How it can be fixed:
1. Call findAndRegisterModules
`this.mapper = DatabindCodec.mapper().findAndRegisterModules()`
In this case, `findAndRegisterModules` will be called every time. The `VertxTypes` module will be missing.

2. Get ObjectMapper from Arc
`this.mapper = Arc.container().instance(ObjectMapper.class).orElse(DatabindCodec.mapper())`
In this case, the `io.vertx.core.json.jackson.VertxModule` module will be missing.

I think the first option is more correct, since there may be places where the ObjectMapper from `DatabindCodec` is used. And enriching it with the jsr310 module will not be superfluous. And put it in a static field so as not to call `findAndRegisterModules` every time.
But here you know better.

### Expected behavior

Can cached list of objects this date/time

### Actual behavior

Thrown exception
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 19] (through reference chain: java.util.ArrayList[0]->org.example.Item["localDateTime"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1888)
	at com.fasterxml.jackson.databind.deser.impl.UnsupportedTypeDeserializer.deserialize(UnsupportedTypeDeserializer.java:48)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4917)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3938)
	at io.quarkus.redis.datasource.codecs.Codecs$JsonCodec.decode(Codecs.java:83)
	... 25 more
```

### How to Reproduce?

[redis-demo.zip](https://github.com/user-attachments/files/18021561/redis-demo.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.17.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #44934

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Good catch!

**Review by gsmet — COMMENTED** [review]
I'm a bit torn on this. I think we are again amplifying the issue we have having a single user-configured `ObjectMapper`.

Because the config you have for REST, might not be what you want for Hibernate ORM (we have an issue for that somewhere) and might not be in line with what you want for Redis.

Now the current situation of using the Vert.x one is probably not satisfying either so I'm not saying this patch is not a good thing.

But... we need to be extremely careful when doing this sort of changes because changing the `ObjectMapper` might mean that you might have problems deserializing the content stored with the old `ObjectMapper` (or even worse lose data when getting the data and saving it again).

I will take an example: you adjust the global `ObjectMapper` config for your REST server needs and you end up affecting your storage in Redis.

Also, I think we need to add the JSR 310 module to the Vert.x  `ObjectMapper` as it's standard Java nowadays. Even if it overrides the `Instant` serialization.

Finally, from what I can see, the `ObjectMapper` we are using here doesn't store `Instant` as we would expect from a standard `ObjectMapper`... but that's probably better to keep it that way given the content in Redis is also stored with this mapping.

All in all, I think we will need to be careful about all this when we take a step back and try to not provide a single customized `ObjectMapper` for everything.

**Comment by geoand** [comment]
I do share the concern, however, in this case the Redis extension is very likely used to serialize user provide classes which means custom modules could be needed. With the current situation in the Redis client, users have no way of implementing that scenario. 

I totally agree we need a comprehensive solution for the configuring `ObjectMapper` for each extension, but IMO this is not the place to start. 
The extension previously just choose an `ObjectMapper` that it knew existsed, it didn't make any special provisions about configuring it.

**Comment by gsmet** [comment]
> The extension previously just choose an ObjectMapper that it knew existsed, it didn't make any special provisions about configuring it.

Yes but... by doing that, you will substitute the Vert.x relatively basic `ObjectMapper` by an `ObjectMapper` that is potentially configured in a way that could be problematic because it was used for other purposes.

What I'm saying is that this change could break an app, and more importantly potentially cause some dataloss if unlucky enough.

For instance, let's say you have configured your global `ObjectMapper` to store things with fields like `myField` and the one from Vert.x stored fields as `my_field`, you could end up with a rather catastrophic situation especially with a full roundtrip get/update/save.

Note that I don't have a magic solution, just pointing out what could become a serious issue.

**Comment by geoand** [comment]
I would agree with you generally, but in this case it's weirder because the way things were **before** this change had a mix of two  ObjectMappers  - the one from Vert.x (which actually was only used in the case the test shows - List<T>) and the one from Quarkus. In this situation, the Vert.x `ObjectMapper` was only used for deserialization as serialization is hidden behind the Vertx JSON SPI which Quarkus intercepts and interjects its own `ObjectMapper`.

With this change, we always use the Quarkus one.

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
