### PR TITLE
Dev services check property value existence with expression expansion

### LINKED ISSUE #41128: Add option to start Redis Dev Services on Null Host Value
### Description

Some of my build processes occur inside containers in a staging Kubernetes environment. Dev services containers cannot be started in this environment. 

On my normal development laptop however, dev services can be used to provide a Redis instance, a SQL Server, etc, nice!

One thing that I like about how certain extensions have implemented dev services, is the option to have them start if the provided hostname or host is null or empty. 

This makes dev services a little more flexible on a per profile basis, which has allowed me to run my local tests using the same testing profile (%test) as my tests on my build containers in my staging environment.

Would it be possible to also add an option in the Redis extension to start dev services for Redis under a given set of conditions in a given profile?

In my case, I would want dev services to start in the dev profile always but in the test profile, if and only if the Redis hosts property is null/empty according to the smallrye config.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
Fixes #41128 replaces #41143 

Thanks to @The-Funk !

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Makes sense.

**Review by geoand — APPROVED** [review]
👌

**Comment by The-Funk** [comment]
@ozangunalp @gsmet @geoand  can this be backported to 3.8 for those of us on the LTS?

**Comment by ozangunalp** [comment]
I don't see any conflicts for 3.8 so it should be fine.

**Comment by gsmet** [comment]
I added the label but we discuss backports for 3.8 in a committee so we will see how it goes when we discuss the next round of backports.

**Comment by gsmet** [comment]
@ozangunalp the `extensions/oidc-token-propagation-reactive/deployment` errors look suspicious. I wouldn't be surprised if there was an issue with the Keycloak Dev Services new behavior?

**Comment by ozangunalp** [comment]
@gsmet I am checking this right now.

**Comment by ozangunalp** [comment]
Found the problems: 
- The oidc extension IT application.properties was self referencing the auth-server config
- The oidc extension tests did use wiremock to simulate the keycloak, so auth-server config needed to be present but replaced by the tests.

**Comment by ozangunalp** [comment]
Impacted tests are now green. There is however a behavior change that I've noticed fixing OIDC tests:

Before when a config property was supplied with an expression that is not resolved, the dev service looking at that property would not kick in, because the property value is still non-null.
Now with this change, when the expression is not resolved the dev service property check resolves to null, enabling the dev service. 

In most cases this is not an issue, you either have a value for that property or not, but for OIDC tests in the quarkus core, there was an interesting case : 

Some tests use the `OidcWiremockTestResource` provided by the test library `quarkus-test-oidc-server`, which mocks the OIDC flow and provides only the `keycloak.url` property, not `quarkus.oidc.auth-server-url`. The OIDC extension was configured in properties with 
`quarkus.oidc.auth-server-url=${keycloak.url}/realms/quarkus`. So when the dev service processor looks at the property, the expression is not resolved thus the property `null` and starts the dev service. But the test expects the mocked OIDC provider not the dev service.

The workaround I applied is to change the expression to `quarkus.oidc.auth-server-url=${keycloak.url:replaced-by-tests}/realms/quarkus`.

I am not sure if this would qualify as a breaking change and block the backport. But worth discussing.

@The-Funk @gsmet @geoand

**Comment by geoand** [comment]
Thanks for raising that. 

To be honest, I have been +0 on the backport thing, so this probably tips me to -0.5 :)

**Comment by ozangunalp** [comment]
Same for me. It is a very minor breaking change, but we should refrain from backporting.

**Comment by gsmet** [comment]
I actually missed the ping and I think it's a bit problematic. I don't see a way to fix this given how things are ordered (and the order makes sense) but we already have one complaint here: https://github.com/quarkusio/quarkus/issues/42273 .

And I suspect we will have more.

I added a note in the migration guide as it's the least we have to do.

**Comment by sberyozkin** [comment]
Hi @ozangunalp, @gsmet  I've missed this whole conversation, but I'm seeing a 2nd issue related to this change,

Can you clarify please, given `quarkus.oidc.auth-server-url=${keycloak.url}/realms/quarkus`, what exactly has changed that made `keycloak.url`  unresolvable, given that the OIDC test library sets `keycloak.url` ? 

I see #42392, but `keycloak.url` is [defined](https://github.com/quarkusio/quarkus/blob/main/test-framework/oidc-server/src/main/java/io/quarkus/test/oidc/server/OidcWiremockTestResource.java#L220). What am I missing ?

**Comment by sberyozkin** [comment]
OK, thanks for the summary @ozangunalp

**Pull request merged**
