### PR TITLE
Manage Instant as MongoDB ISODate

### LINKED ISSUE #6566: PanacheMongoRepository does not deal well with instants
When using the PanacheMongoRepository to query the database using Instants the Inventory does not find any results unless the query is written in mongo syntax.

`fun getByCreationInstantBefore(time: Instant) = list("endAt < ?1", time)`
 
Should return the Commands present in the database with endAt < time but returns an empty list.

1.  Create a Database populated with entries with time
2. Try to query by time like above

`fun getByCreationInstantBefore(time: Instant) = list("{endAt : { \$lte : ISODate(?1) }}", time)` works well

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #6566

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Comment by geoand** [comment]
Can you please rebase onto master to pick up a CI fix?

**Comment by gsmet** [comment]
I ust force pushed a rebase, let's see if CI likes it better.

**Comment by machi1990** [comment]
CI is happy, merging! Thanks @loicmathieu @gsmet

**Pull request merged**
