### PR TITLE
Bump Micrometer to 1.13

### LINKED ISSUE #42578: OTEL + `quarkus.http.test-timeout` -> NullPointerException: Cannot invoke "io.vertx.core.spi.observability.HttpResponse.headers()" because "httpResponse" is null
### Describe the bug

Setting `quarkus.http.test-timeout` to a low value so that a rest assured request times out results in a NPE in OTEL code.

### Expected behavior

No NPE, just a timeout.

### Actual behavior

```
WARN  [io.net.cha.AbstractChannelHandlerContext] (vert.x-eventloop-thread-1) An exception 'java.lang.NullPointerException: Cannot invoke "io.vertx.core.spi.observability.HttpResponse.headers()" because "httpResponse" is null' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:: java.lang.NullPointerException: Cannot invoke "io.vertx.core.spi.observability.HttpResponse.headers()" because "httpResponse" is null
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.HttpInstrumenterVertxTracer$AdditionalServerAttributesExtractor.onEnd(HttpInstrumenterVertxTracer.java:301)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.HttpInstrumenterVertxTracer$AdditionalServerAttributesExtractor.onEnd(HttpInstrumenterVertxTracer.java:278)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.doEnd(Instrumenter.java:227)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.end(Instrumenter.java:144)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.InstrumenterVertxTracer.sendResponse(InstrumenterVertxTracer.java:72)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:105)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:50)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:47)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:16)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxTracingFactory$VertxDelegator.sendResponse(OpenTelemetryVertxTracingFactory.java:78)
	at io.vertx.core.http.impl.Http1xServerRequest.reportRequestReset(Http1xServerRequest.java:700)
	at io.vertx.core.http.impl.Http1xServerRequest.handleException(Http1xServerRequest.java:678)
	at io.vertx.core.http.impl.Http1xServerConnection.lambda$handleClosed$7(Http1xServerConnection.java:501)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:313)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:159)
	at io.vertx.core.impl.ContextInternal.execute(ContextInternal.java:216)
	at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:500)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1402)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:900)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:811)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

[q_otel-assured.zip](https://github.com/user-attachments/files/16630224/q_otel-assured.zip)

- `./mvnw clean install -Dquarkus.http.test-timeout=2s`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.13.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.8

### Additional information

There is another exception that looks like "noise" too:
```
2024-08-15 22:44:18,764 ERROR [io.ver.ext.web.RoutingContext] (executor-thread-1) Unhandled exception in router [Error Occurred After Shutdown]: java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:931)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:343)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:833)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:824)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:814)
	at io.vertx.core.net.impl.ConnectionBase.queueForWrite(ConnectionBase.java:238)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:228)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:218)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:214)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:437)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:411)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:390)
	at io.quarkus.vertx.http.runtime.QuarkusErrorHandler.writeResponse(QuarkusErrorHandler.java:206)
	at io.quarkus.vertx.http.runtime.QuarkusErrorHandler.jsonResponse(QuarkusErrorHandler.java:192)
	at io.quarkus.vertx.http.runtime.QuarkusErrorHandler.handle(QuarkusErrorHandler.java:166)
	at io.quarkus.vertx.http.runtime.QuarkusErrorHandler.handle(QuarkusErrorHandler.java:31)
	at io.vertx.ext.web.impl.RouteState.handleFailure(RouteState.java:1291)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:174)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$7.handle(ResteasyReactiveRecorder.java:237)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$7.handle(ResteasyReactiveRecorder.java:196)
	at io.vertx.ext.web.impl.RouteState.handleFailure(RouteState.java:1291)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:174)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.resteasy.reactive.server.runtime.observability.ObservabilityIntegrationRecorder$1.handle(ObservabilityIntegrationRecorder.java:39)
	at io.quarkus.resteasy.reactive.server.runtime.observability.ObservabilityIntegrationRecorder$1.handle(ObservabilityIntegrationRecorder.java:29)
	at io.vertx.ext.web.impl.RouteState.handleFailure(RouteState.java:1291)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:174)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:557)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:196)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:185)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.handleUnrecoverableError(QuarkusResteasyReactiveRequestContext.java:65)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:329)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:175)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### PR DESCRIPTION
**Pull request by brunobat**
This will use the deprecated simple prometheus client for v0.x, not the new prometheus client 1.x.
Beware of the dependency change. Instead of `micrometer-registry-prometheus`, now use:
```xml
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-registry-prometheus-simpleclient</artifactId>
</dependency>
```

This means this bum is backwards compatible with the previous code.

Tests  should always use the SimpleMeterRegistry:
```java
    final static SimpleMeterRegistry registry = new SimpleMeterRegistry();

    @BeforeAll
    static void setRegistry() {
        Metrics.addRegistry(registry);
    }

    @AfterAll()
    static void removeRegistry() {
        Metrics.removeRegistry(registry);
    }
```
Will also fix https://github.com/quarkusio/quarkus/issues/42578

We will suppress these log warnings:
[io.mic.cor.ins.com.CompositeMeterRegistry] (main) A MeterFilter is being configured after a Meter has been
registered to this registry...
It's unavoidable because of how Quarkus startup works and users cannot do anything about it.
see: https://github.com/micrometer-metrics/micrometer/issues/4920#issuecomment-2298348202

### CODE REVIEW

**Comment by gastaldi** [comment]
Can we provide an abstract test class initializing it instead of copy/pasting this snippet everywhere?

**Comment by brunobat** [comment]
> Can we provide an abstract test class initializing it instead of copy/pasting this snippet everywhere?

I'm not a fan of abstract classes, but we could use something from the JUnit lifecycle, however, I would prefer to do it later, in a different PR. I don't want to change too much code. This change would affect pretty much all the tests in deployment.

**Comment by brunobat** [comment]
CC @cescoffier, @aureamunoz please beware of the recommended way to setup the registry on tests.
In relation to the stork tests, it seems to me that they have issues that need fixing... I left FIXME comments in there.

**Comment by cescoffier** [comment]
@brunobat in which class did you see a Stork related FIXME?

**Comment by brunobat** [comment]
> @brunobat in which class did you see a Stork related FIXME?

There are 3:
````
extensions/micrometer/deployment/src/test/java/io/quarkus/micrometer/deployment/binder/StorkMetricsTest.java
extensions/micrometer/deployment/src/test/java/io/quarkus/micrometer/deployment/binder/StorkMetricsServiceDiscoveryFailTest.java
extensions/micrometer/deployment/src/test/java/io/quarkus/micrometer/deployment/binder/StorkMetricsLoadBalancerFailTest.java
````

**Comment by cescoffier** [comment]
@brunobat Hum, the stork issue seems to be a change of behavior in micrometer, this is a bit annoying.

**Comment by cescoffier** [comment]
So, this is a Stork bug (in Quarkus) and a change of behavior in Micrometer.
The later is the non-initialization of the metric if it has not being set (like calling `increment` on a counter). Before it was retruning a counter (keeping this example) with the value 0. Now it returns `null`. 

The interesting aspect is that I would consider this an issue on our side as, our prometheus reporting would have been missing these metrics (which would make the metric interpretation ambiguous). So, I think this change of behavior caught another bug.

**Comment by cescoffier** [comment]
@brunobat I just pushed the fixes.

**Review by cescoffier — APPROVED** [review]

**Review by aureamunoz — APPROVED** [review]

**Comment by rsvoboda** [comment]
@brunobat Is there a plan to bump to new prometheus client 1.x? 

Motivation: To see if the users should be notified about the upcoming change.

**Comment by brunobat** [comment]
> So, this is a Stork bug (in Quarkus) and a change of behavior in Micrometer. The later is the non-initialization of the metric if it has not being set (like calling `increment` on a counter). Before it was retruning a counter (keeping this example) with the value 0. Now it returns `null`.
> 
> The interesting aspect is that I would consider this an issue on our side as, our prometheus reporting would have been missing these metrics (which would make the metric interpretation ambiguous). So, I think this change of behavior caught another bug.

Thanks @cescoffier. There was also a previous problem where in the tests, instead of finding the metric existing, the metric was being created (in the hopes of doing a find) and the value retrieved, it would never be null.

**Comment by brunobat** [comment]
> @brunobat Is there a plan to bump to new prometheus client 1.x?
> 
> Motivation: To see if the users should be notified about the upcoming change.

No, according to the plan explained here: https://groups.google.com/g/quarkus-dev/c/y5-ojIVsa_M/m/4wquJi4bBQAJ

There is no plans to support the Prometheus 1.x client in Quarkus core. The idea is that telemetry output, even for Micrometer metrics, will be done through OpenTelemetry.
We plan to develop a Micrometer to OpenTelemetry bridge and also implement the Prometheus 1.x client registry on Quarkiverse.
The idea is that, as soon as the MM->Otel bridge is available and proved efficient, we will mark the current core extension as deprecated.
CC @tqvarnst

**Comment by brunobat** [comment]
Did a squash

**Review by ebullient — APPROVED** [review]

**Pull request merged**
