### PR TITLE
Update p12 files and provide instructions to regenerate them

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Maybe it would be nice to have that script available in a separate `.sh` file?

**Comment by cescoffier** [comment]
Because it may require some user validation (basically saying yes - but didn't really get why it requires it sometimes), it's simpler like this. Once we reach more stability, we can use a .sh script or even run it every time (quid of windows machines)

**Comment by gastaldi** [comment]
My question was because someone would need to copy/paste your snippet to a .sh file to execute it when needed, so that step could be skipped :)

**Review by gsmet — APPROVED** [review]
I can confirm it fixes the issue. Let's not wait for CI.

**Pull request merged**
