### PR TITLE
Remove JDK collection reflection registration

### PR DESCRIPTION
**Pull request by galderz**
As discussed in [Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Digging.20Into.20Points-To.20Analysis/near/289432755). Let's see if anything breaks.

### CODE REVIEW

**Comment by galderz** [comment]
I've noticed some failures. I'll evaluate them and report.

**Comment by geoand** [comment]
Yeah, we should try that

**Comment by geoand** [comment]
And duplicate it for json-b too

**Comment by gsmet** [comment]
Could we clarify which issues it's supposed to solve? It's not clear from the discussion if it really brings something noticeable.
Because if it doesn't, I really don't see why we would take the risk to break existing applications.

**Pull request closed without merging**
