### PR TITLE
Remove uberJar Maven/Gradle param & quarkus.package.uber-jar property

### LINKED ISSUE #14878: Remove uberJar parameter from Maven mojos/goals in 1.13
**Description**
[As agreed on the mailing list](https://groups.google.com/g/quarkus-dev/c/CM7_La611Bw), the `uberJar` parameter in `QuarkusBootstrapMojo` (`BuildMojo` and `GenerateCodeMojo` respectively) should not be used anymore.
Instead, `quarkus.package.type=uber-jar` shall be used, as already documented: https://quarkus.io/guides/maven-tooling#uber-jar-maven

**Implementation ideas**

- [x] log a warning in the mojos (#14886)
- [x] remove remaining usages (#14886)
- [x] remove usages in quickstarts, if any (none)
- [x] @glefloch: deprecate and log a warning in the gradle plugins (#14899)
- [ ] remove the parameter in 1.13 (#14987)

### PR DESCRIPTION
**Pull request by famod**
Resolves #14878

/cc @glefloch

@aloubyansky Not sure what to do with `QuarkusBootstrapMojo.ignoredEntries`. It says:
> When using the uberJar option, this array specifies entries that should be excluded from the final jar.

but looking at the usage, it seems it's always evaluated, not only for uber-jar?

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
We should probably keep handling `QuarkusBootstrapMojo.ignoredEntries` as we do currently.

**Review by glefloch — APPROVED** [review]

**Comment by famod** [comment]
@aloubyansky Alright, I'll revise the JavaDoc a bit then.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks for the cleanup!

**Comment by famod** [comment]
@gsmet I'll add something to the Migration Guide for this as well.

**Pull request merged**
