### PR TITLE
Some fixes to allow JBang to work

### PR DESCRIPTION
**Pull request by stuartwdouglas**
- Remove ASM dep from provided dep list (JBang will resolve an old
  version)
- Default to using the quarkus bom if no managing project is supplied

### CODE REVIEW

**Comment by maxandersen** [comment]
Awesome. Weird why that didn't caught us before. 

But okey - now really need to get bom support added.

**Comment by aloubyansky** [comment]
The "managing project" should be null for the typical case, i.e. any Quarkus application. If it's not, this is not good. The managing project was introduced primarily to support the platform TS when the Quarkus version/platform of the imported test should be overridden with the current platform. From this perspective this change is really wrong.

Doesn't JBang generate the POM? Wouldn't it be easier to add the BOM on that side?

**Comment by maxandersen** [comment]
jbang only generates a bare bones pom to work around code that assumes there are a physical pom present. we need to find a way to get away from that. 

what does "platform TS" refer to ? testsuite ?

**Comment by aloubyansky** [comment]
As I mentioned on the issue, at least quarkus-bom must be imported by any Quarkus app. Even if it's not about adding the platform properties. A BOM is required to guarantee the dependency versions are properly aligned.

Yes, the platform testsuite.

**Comment by aloubyansky** [comment]
I haven't yet looked into how JBang [integration] sets this all up, but if for some reason it can be fixed there, I would look into hacking the place where the platform properties are resolved in Quarkus instead (i.e. where the exception is thrown in case they are missing).

**Comment by aloubyansky** [comment]
> I haven't yet looked into how JBang [integration] sets this all up, but if for some reason it can be fixed there, I would look into 

I meant: **can't** be fixed there

**Comment by stuartwdouglas** [comment]
The platform properties is not the main issue, there is only one that causes failures so that can be hacked around. The main issue is that the dependencies end up being resolved incorrectly, so we end up with an old ASM which fails.

**Comment by aloubyansky** [comment]
Right, so that's the issue.

**Comment by stuartwdouglas** [comment]
I have changed this so we just set the managing project to the bom when using the Quarkus integration.

I think this is all we can do for now, as real bom support would need to come from the JBang side.

**Review by aloubyansky — APPROVED** [review]
Yes, that's fine, thanks @stuartwdouglas

**Review by maxandersen — APPROVED** [review]
LGTM

**Comment by maxandersen** [comment]
the relevant bom issue is https://github.com/jbangdev/jbang/issues/63 - only reason not done yet is that shrinkwrap blocks pom downloads - i'll see if I can "fix"/hack that :)

**Pull request merged**
