### PR TITLE
Document how to configure well-known OIDC providers

### LINKED ISSUE #21521: Improve OIDC web-app guide with an example singing in to Google
### Description

It would help if we could show, with another quickstart, how Quarkus can directly integrate with Google Sign In process

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #21521.

This PR copies some great content from Renarde Security docs and adapts them to Quarkus. Note I'm not showing a mullti-tenant configuration and instead refer users to Renarde itself to show a concrete example where nearly all of these providers (except for George's Spotify config) are combined.

### CODE REVIEW

**Comment by sberyozkin** [comment]
New document itself is [here](https://github.com/quarkusio/quarkus/pull/25197/files#diff-494301d8276ccc2457e63c39d1b4a80230ec3a2197304249b557870eee6cbcdb).

**Review by FroMage — DISMISSED** [review]
LGTM except the leaked credentials in the spotify screenshots that you should clear out ;)

**Comment by sberyozkin** [comment]
@FroMage Indeed, @gastaldi said that was a temp client already deleted. I think we can only show the first image there and drop the 2nd one containing id and secret

**Comment by sberyozkin** [comment]
Not sure how to get that red line over client id and secret in the image...

**Comment by gastaldi** [comment]
oidc-spotify-2

**Comment by sberyozkin** [comment]
Thanks @gastaldi let me update the PR with this one

**Review by FroMage — APPROVED** [review]

**Pull request merged**
