### PR TITLE
Bump OTel to 1.29.0

### PR DESCRIPTION
**Pull request by brunobat**

### CODE REVIEW

**Review by radcortez — APPROVED** [review]

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@yrodiere this is another case of OOM due to metaspace. It might be a coincidence but it's often failing in this particular test.

**Comment by brunobat** [comment]
I see gradle cache in the stack traces and jobs running for almost 6h with logs ending abruptly.

**Comment by gsmet** [comment]
@brunobat the native failures in the new report look related.

**Comment by brunobat** [comment]
These `com.gradle.maven.cache.extension.*` stacktrace errors in the build log are confusing.
It should be good now, @gsmet

**Comment by brunobat** [comment]
@geoand Do you mind if I merge this? I need to work in the next upgrade...

**Comment by geoand** [comment]
Go for it once CI is done :)

**Comment by gsmet** [comment]
> These com.gradle.maven.cache.extension.* stacktrace errors in the build log are confusing.

@brunobat could you be more specific?

**Comment by brunobat** [comment]
> > These com.gradle.maven.cache.extension.* stacktrace errors in the build log are confusing.
> 
> @brunobat could you be more specific?

Yes @gsmet . Please check the exceptions on the end of this old log file:
https://pipelines.actions.githubusercontent.com/serviceHosts/db7e007d-ef45-446a-a481-86fd29e0a95c/_apis/pipelines/1/runs/210149/signedlogcontent/41?urlExpires=2023-09-19T08%3A42%3A00.8962280Z&urlSigningMethod=HMACV1&urlSignature=F0PVCJQklcNuIqZPj3uT%2F1Z%2FiVEPQLR1vFfQovUzu4M%3D

**Comment by gsmet** [comment]
OK. So the build cache adds a layer and that's what you see in the stacktraces. There's nothing we can do about it really but I don't think this is as confusing as it seems. I'll send an email to the list.

**Pull request merged**
