### PR TITLE
Add capability for reactive routes

### PR DESCRIPTION
**Pull request by HerrDerb**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Makes sense, thanks.

CI is a bit saturated right now, I will approve CI a bit later.

**Comment by gsmet** [comment]
Thanks!

Do you need this in 3.3?

**Comment by HerrDerb** [comment]
Would be great, yes. Thank you !

**Comment by gsmet** [comment]
I marked it for backport, it will be end up in 3.3.1.

**Pull request merged**
