### PR TITLE
Move narayana-lra extension to the new separated LRA project

### PR DESCRIPTION
**Pull request by xstefank**
Narayana LRA moved to a separate repository with a separate lifecycle - https://github.com/jbosstm/lra.

### CODE REVIEW

**Comment by gsmet** [comment]
@radcortez I think we have a problem with the new config stuff.

We have another failure here with:

```
2024-11-14T18:36:49.8668243Z Nov 14, 2024 6:36:49 PM io.quarkus.runtime.ApplicationLifecycleManager run
2024-11-14T18:36:49.8669181Z ERROR: Failed to start application
2024-11-14T18:36:49.8669886Z java.lang.RuntimeException: Failed to start quarkus
2024-11-14T18:36:49.8671108Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2024-11-14T18:36:49.8672143Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2024-11-14T18:36:49.8673466Z 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:121)
2024-11-14T18:36:49.8674711Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
2024-11-14T18:36:49.8675535Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
2024-11-14T18:36:49.8676374Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
2024-11-14T18:36:49.8677225Z 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2024-11-14T18:36:49.8678573Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-11-14T18:36:49.8679985Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-11-14T18:36:49.8681645Z 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
2024-11-14T18:36:49.8683007Z 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
2024-11-14T18:36:49.8684630Z Caused by: java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for io.quarkus.runtime.ConfigConfig
2024-11-14T18:36:49.8686239Z 	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:631)
2024-11-14T18:36:49.8687591Z 	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:621)
2024-11-14T18:36:49.8689087Z 	at io.quarkus.runtime.configuration.ConfigRecorder.handleConfigChange(ConfigRecorder.java:63)
2024-11-14T18:36:49.8690986Z 	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy_8(Unknown Source)
2024-11-14T18:36:49.8693205Z 	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy(Unknown Source)
```

**Comment by radcortez** [comment]
I was looking into it, but I really can't explain the cause yet. To make things worse, it is an intermittent error :(

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks! I suggested some changes, nothing big.

**Comment by xstefank** [comment]
@gsmet sorry for the late update, busy with the book.

**Review by gsmet — APPROVED** [review]
Rebased and ready for inclusion once CI is green.

**Pull request merged**
