### PR TITLE
use (Guava's) Splitter instead of String.split in core/deployment ApplicationArchiveBuildStep

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by gsmet** [comment]
I'm not sure at all we want Guava in our dependencies. This needs to be discussed.

**Comment by vorburger** [comment]
I think of Guava as java.lang.util++ ... IMHO Guava is the new Apache Commons.

Having said that, we could also just `@SuppressWarnings("StringSplitter")` in this specific case.

**Comment by dmlloyd** [comment]
@vorburger your PRs all seem to contain the commits from the previous PRs.  This is making them difficult to review; please ensure that any given commit does not belong to more than one PR.  A PR may contain more than one commit of course.

**Comment by gsmet** [comment]
So, as mentioned, adding Guava as a core dependency should not be done lightly.

Let's discuss that on the mailing list and reopen if we decide it's the way to go.

**Comment by vorburger** [comment]
> @vorburger your PRs all seem to contain the commits from the previous PRs. This is making them difficult to review; please ensure that any given commit does not belong to more than one PR. A PR may contain more than one commit of course.

For testing Error Prone (#1335) I needed them together - my expectation was that they would reviewed by looking at the last commit, not the total changes. But I realize I'm using a Gerrit workflow on GitHub... I'll fix up the open changes (#1327 #1328 #1329) accordingly right now!

**Pull request closed without merging**
