### PR TITLE
Local cache upgrade

### PR DESCRIPTION
**Pull request by Sanne**
A quick draft for #32317 - needs performance assessment

Also requires https://github.com/hibernate/quarkus-local-cache/pull/6

### CODE REVIEW

**Comment by Sanne** [comment]
Simplified this a lot, and released v `0.2.1` of https://github.com/hibernate/quarkus-local-cache which simply makes all Caffeine backgraound work in foreground; it also allows overriding now, should we want to experiment further.

**Comment by Sanne** [comment]
Release notes:
https://github.com/hibernate/quarkus-local-cache/releases/tag/0.2.1

**Review by yrodiere — APPROVED** [review]
> needs performance assessment

Can't give you that, sorry. I'm hardly the right person to ask anyway.

But FWIW, feel free to merge.

**Comment by Sanne** [comment]
> > needs performance assessment

sorry, forgot to mention the comment is out of date - we did it and it's looking great

> Can't give you that, sorry. I'm hardly the right person to ask anyway.
> 
> But FWIW, feel free to merge.

thanks

**Pull request merged**
