### PR TITLE
SmallRye GraphQL Client extension + 1.2.1 upgrade

### LINKED ISSUE #16792: SmallRye GraphQL Client extension
We don't yet have first-class support for GraphQL clients with SmallRye GraphQL in Quarkus. A separate extension would probably be a good way to introduce it, with all the features like a proper Quarkus-like configuration model, and support for client injection.

This will probably be added along with upgrading to SmallRye GraphQL 1.2, which will contain both the dynamic and typesafe clients.

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #16792 

Subscription support and a user guide coming up next

### CODE REVIEW

**Comment by gsmet** [comment]
That's very nice. I would be curious if we could get rid of all the custom stuff we have in https://github.com/quarkusio/status.quarkus.io/.

One of my questions is if it's possible to express queries as strings. We are using Qute templates in status.quarkus.io (see https://github.com/quarkusio/status.quarkus.io/blob/main/src/main/resources/templates/GitHubService/findIssuesByIds.graphql) and that's definitely easier to express/test than writing some DSL calls.

**Comment by jmartisk** [comment]
Using string queries isn't supported by the dynamic client right now, but it won't be a problem to add that. (for the typesafe client, this obviously doesn't make sense)

**Comment by gsmet** [comment]
@jmartisk I think it would be a useful experiment to try to convert status.quarkus.io to use this. And supporting String queries could be a very useful addition for that.

**Comment by jmartisk** [comment]
@gsmet Definitely. I filed https://github.com/smallrye/smallrye-graphql/issues/806

**Review by phillip-kruger — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@jmartisk in the doc, it would be useful to explain how to push an authorization header: https://github.com/quarkusio/status.quarkus.io/blob/main/src/main/java/io/quarkus/status/graphql/GraphQLClient.java#L14

**Comment by jmartisk** [comment]
Sure. I'm planning to start writing the user guide today and see if I can get it done before going on PTO

**Comment by jmartisk** [comment]
Oh, and a quickstart probably.
Anyway that will come in separate PRs. 
I guess this is ready to merge, if no one has concerns. There's one CI failure that looks unrelated

**Comment by phillip-kruger** [comment]
@gsmet - It would be good to get this in before the next Alpha (or Beta) so we can start playing :)

**Comment by t1** [comment]
Great to see this coming! Any chance that it will be backported to pre-2.0?

And I had assumed I could just `@Inject` an instance of a `@TypesafeGrapQLClientApi`, but it throws a `java.lang.NoSuchFieldError: io/quarkus/deployment/Feature.SMALLRYE_GRAPHQL_CLIENT`. I didn't see any tests for this either. Should I open an issue for this?

**Comment by t1** [comment]
sorry, my bad: I mixed versions, which is obviously a bad idea. Still there is no test for injecting typesafe client apis, only programmatic lookups.

**Comment by jmartisk** [comment]
@t1 I'll add such test

**Comment by jmartisk** [comment]
I don't think backporting is being planned, there's also the problem that Quarkus 1 contains SR GraphQL 1.0.x, which only contains the typesafe client, so it would have to be only a partial backport.  And SR GraphQL 1.2.x depends on Vert.x 4 so it can't go into Quarkus 1.x. It would be quite complicated.

**Comment by jmartisk** [comment]
@t1 btw here's the promised test https://github.com/quarkusio/quarkus/pull/17401

**Comment by t1** [comment]
That was fast! Thanks. Also for the explanation about not backporting. I'll have to do my demo talk with the Alpha-Releases then, I guess.

**Comment by phillip-kruger** [comment]
@t1 when is your demo ?

**Comment by t1** [comment]
> @t1 when is your demo ?

On June 9th.. maybe I'll manage to get my GraphQL Federation Quarkus Extension running by then (this is all very new to me). That would be uber cool. Otherwise I'll have to switch back to WildFly.

**Comment by phillip-kruger** [comment]
@t1 - By then Quarkus 2 should be released (see https://github.com/quarkusio/quarkus/wiki/Release-Planning), also, subscription is also in, have a look :)

**Comment by t1** [comment]
Cool... it says 'Full Platform release (and official announcement) on June 9th' ... that would be exactly the day... coincidence or destiny? ;-)

**Pull request merged**
