### PR TITLE
Upgrade to ASM 7.3.1

### PR DESCRIPTION
**Pull request by gunnarmorling**
Note this solves the problem I had with JDK 14, not the other one reported on #6786 which seems related to Gradle/Groovy and likely needs another fix.

CC @gsmet

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks but please let's avoid the emojis in issue title and commit message. I'm also wondering if we should change the versions used when generating the classes (the ASM constants with the version).

We probably should upgrade Gizmo to use that version too.

**Comment by gunnarmorling** [comment]
> let's avoid the emojis in issue title and commit message.

Why?

> change the ASM constants with the version
> We probably should upgrade Gizmo to use that version too.

Do you have any pointers where to look into for these things?

**Comment by geoand** [comment]
> change the ASM constants with the version We probably should upgrade Gizmo to use that version too.
> Do you have any pointers where to look into for these things?

This should be it: https://github.com/quarkusio/gizmo/blob/master/pom.xml#L38

**Comment by geoand** [comment]
> let's avoid the emojis in issue title and commit message.
> Why?
My guess is that it doesn't look in the generated changelog. @gsmet can of course confirm or deny

**Comment by gastaldi** [comment]
How about adding it to the dependabot descriptor?

**Comment by gastaldi** [comment]
I created https://github.com/quarkusio/gizmo/pull/24 bumping ASM and Jandex to their latest versions

**Comment by gsmet** [comment]
> Why?

Because I don't want the changelog to look like a Christmas tree. And if we start accepting them, where do we set the limit? Typically in this case, it's totally useless, it's just visual noise. So let's drop it please.

AFAICS the latest version of ASM is 7.3.1 so we should upgrade to this one instead. I upgraded Gizmo to use it and set up some additional CI.

The version of the API is still 7 so we can just upgrade in place without further changes.

**Comment by gunnarmorling** [comment]
Ok, will send an update for this PR later today, updating to ASM 7.3.1 and
replacing the emoji with a Christm..., eh, removing the emoji ;)

>

**Comment by gunnarmorling** [comment]
Reworked the commit and updated this PR 🤟.

**Comment by gsmet** [comment]
Merged, thanks.

**Pull request merged**
