### PR TITLE
(3.2) Parsson 1.1.5

### PR DESCRIPTION
**Pull request by jmartisk**
https://issues.redhat.com/browse/QUARKUS-3842

https://github.com/eclipse-ee4j/parsson/compare/1.1.2...1.1.5

Quarkus main PR: https://github.com/quarkusio/quarkus/pull/37015

### CODE REVIEW

**Comment by rsvoboda** [comment]
Windows 17 fails on extensions/vertx-http/deployment module and thus there are many other modules skipped

`2024-01-04T08:28:05.2884931Z [ERROR] io.quarkus.vertx.http.http2.Http2RSTFloodProtectionTest.testRstFloodProtectionWithTlsEnabled  Time elapsed: 10.009 s  <<< FAILURE!`

There are also some strange failures of `io.quarkus.vertx.http.testrunner` tests, e.g. `io.quarkus.vertx.http.testrunner.SimpleET`. But they are not reported in the final summary.

**Comment by gsmet** [comment]
Yeah these tests have been unstable on Windows and have been disabled on Windows in main. We should probably do the same for 3.2.

**Review by aloubyansky — APPROVED** [review]

**Comment by rsvoboda** [comment]
@jmartisk there is also https://github.com/quarkusio/quarkus/blob/3.2/independent-projects/resteasy-reactive/pom.xml#L44 where Parsson version is used and defined

**Comment by jmartisk** [comment]
Good catch @rsvoboda , thanks. I've changed that one now too.

**Pull request merged**
