### PR TITLE
Bootstrap: option to build workspaces from the effective project models instead of the raw ones

### LINKED ISSUE #9727: Quarkus dev mode failes, if maven packaging is defined by a variable (property)
If maven packaging is defined by a property, dev mode hangs on startup.

The bug is described in https://github.com/GEDOPLAN/quarkus-devmode-fails-for-variable-packaging.

&lt;tl;dr&gt;
&lt;packaging&gt;${packaging.type}&lt;/packaging&gt;

  &lt;properties&gt;
    &lt;packaging.type&gt;jar&lt;/packaging.type&gt;
  &lt;/properties&gt;

  mvn quarkus:dev hangs in application int.

### LINKED ISSUE #12715: "mvn quarkus:dev" workspace discovery should respect default maven profiles
See second part of discussion here:
  https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/ClassLoading.20error.20in.20hot.20deploy

In optaplanner 7.x, the quarkus-school-timetabling-quickstart's "mvn quarkus:dev" was failling because the optaplanner-parent has a maven module that includes the optaplanner-quarkus-integration - and that maven profile is on by default - but Quarkus ignores maven profiles.

@aloubyansky

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #12715
Fixes #9727
and the setup in Quarkiverse projects excluding the IT module when performing the release.

This PR adds an option to enable building project workspaces using the effective POMs (properly interpolated, including profiles, etc) instead of the raw ones.
However, resolving effective POMs is a lot more expensive than reading the raw ones. E.g. if building a workspace from raw POMs takes around ~200ms for a project, it'll take ~1300ms to build the same workspace using effective POMs. Which will have an effect of the tests and dev mode.
Once enabled, the Quarkus CI, e.g., takes around one hour longer to complete.
That's why this option is off by default, currently. There could be projects though that may require workspaces initialized with the effective POMs. In which case, they can add `quarkus.bootstrap.effective-model-builder` system property set to `true` to their configs (e.g. the `surefire-maven-plugin`).

### CODE REVIEW

**Comment by aloubyansky** [comment]
@vsevel fyi, this will fix the freemaker extension release issue you struggled with.

**Comment by aloubyansky** [comment]
Rebased to fix conflicts.

**Comment by aloubyansky** [comment]
@famod do you mind reviewing this one? I am not sure anybody will like it :)

**Comment by famod** [comment]
@aloubyansky I can try but it'll take me some time because I'm busy with other stuff.

Btw, there seems to be a problem with `IDELauncherTestCase`, three of the four JVM Tests jobs fail with:
```
2021-03-06T17:13:11.8585437Z [INFO] -------------------------------------------------------
2021-03-06T17:13:11.8586994Z [INFO]  T E S T S
2021-03-06T17:13:11.8592142Z [INFO] -------------------------------------------------------
2021-03-06T17:13:12.6530870Z [INFO] Running io.quarkus.it.launcher.IDELauncherTestCase
2021-03-06T17:44:47.3014801Z ##[error]The operation was canceled.
```

**Comment by aloubyansky** [comment]
I've fixed the IDELauncherTestCase. I also compared the time it takes to load the (Quarkus repo) workspace based on the raw project Models and the effective ones. The difference is huge: 200ms vs 1780ms. I'll need to look into whether I can optimize it but naturally the effective model is a lot more expensive to resolve, especially for a repo like Quarkus.

**Comment by aloubyansky** [comment]
There a couple failures that might not be related. However, I am going to introduce some code collecting the overall workspace loading time for a given job to see the impact of the change on the CI.

**Comment by aloubyansky** [comment]
@gsmet just in case, it's ready to be merged.

**Comment by famod** [comment]
@aloubyansky
> I also compared the time it takes to load the (Quarkus repo) workspace based on the raw project Models and the effective ones. The difference is huge: 200ms vs 1780ms. I'll need to look into whether I can optimize it but naturally the effective model is a lot more expensive to resolve, especially for a repo like Quarkus.

How did that turn out in the end?

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by aloubyansky** [comment]
> @aloubyansky
> 
> > I also compared the time it takes to load the (Quarkus repo) workspace based on the raw project Models and the effective ones. The difference is huge: 200ms vs 1780ms. I'll need to look into whether I can optimize it but naturally the effective model is a lot more expensive to resolve, especially for a repo like Quarkus.
> 
> How did that turn out in the end?

At the end I decided not to make it the default, as I hoped to at the beginning. But I think we must have this option available to make sure projects that require it can be built. I'll research a different approach. Perhaps we could avoid the need to re-init the maven context for the tests and dev mode.

**Pull request merged**
