### PR TITLE
QuarkusComponentTest: support Gradle

### LINKED ISSUE #35098: QuarkusComponentTest in Gradle
### Describe the bug

When creating an @QuarkusComponentTest within a Quarkus project that you build with Gradle you get an `IllegalStateException: Invalid test path`. 

```
java.lang.IllegalStateException: Invalid test path: /Users/peter/Development/heating-service/valve/build/classes/java/test/com/peterfortuin/heating/valveservice/pipelines/valveupdates/TemperatureRequestSenderTest.class
	at io.quarkus.test.component.QuarkusComponentTestExtension.initArcContainer(QuarkusComponentTestExtension.java:554)
	at io.quarkus.test.component.QuarkusComponentTestExtension.beforeAll(QuarkusComponentTestExtension.java:292)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because "generatedResources" is null
		at io.quarkus.test.component.QuarkusComponentTestExtension.afterAll(QuarkusComponentTestExtension.java:340)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$18(ClassBasedTestDescriptor.java:461)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$19(ClassBasedTestDescriptor.java:461)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllCallbacks(ClassBasedTestDescriptor.java:461)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:235)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:84)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:161)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:161)
		... 49 more
```

The problem is in QuarkusComponentTestExtension.java. The problem is with this part of the code:

```java
int targetClassesIndex = testPath.indexOf(TARGET_TEST_CLASSES);
// NOTE: continuous testing is not supported at the moment
if (targetClassesIndex == -1) {
    throw new IllegalStateException("Invalid test path: " + testPath);
}
```

Together with

```java
private static final String TARGET_TEST_CLASSES = "target/test-classes";
```

The code is looking if the path to the class with the testcode contains `target/test-classes`. This is true for Maven builds but not for Gradle builds. 

### Expected behavior

I expect to be able to use @QuarkusComponentTest to write component tests with Gradle als build tool and able to run them without the `IllegalStateException: Invalid test path`.

### Actual behavior

At the moment every test class that is annotated with @QuarkusComponentTest in a project that you build with Gradle will fail with `IllegalStateException: Invalid test path`.

### How to Reproduce?

Steps to reproduce:

1. Create a Quarkus project with Gradle as build tool.
2. Create a component test with @QuarkusComponentTest annotation.
3. Run the tests with ./gradlew test or run them from IntelliJ.

### Output of `uname -a` or `ver`

Darwin Peters-MBP-2.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

java version "17.0.2" 2022-01-18 LTS Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86) Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.1.1 ------------------------------------------------------------  Build time:   2023-04-21 12:31:26 UTC Revision:     1cf537a851c635c364a4214885f8b9798051175b  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.2 (Oracle Corporation 17.0.2+8-LTS-86) OS:           Mac OS X 13.4.1 aarch64

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #35098

### CODE REVIEW

**Comment by mkouba** [comment]
@peterfortuin It would be great if you could test your setup with this PR. Of course, you would need to [build the quarkus](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#build) first.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
We probably want to backport this

**Comment by mkouba** [comment]
> We probably want to backport this

Hm, I'm afraid that there will be conflicts because we did not backport https://github.com/quarkusio/quarkus/pull/34239 because it depends on https://github.com/quarkusio/quarkus/pull/34138... Let me try to cherry-pick this commit.

**Comment by mkouba** [comment]
There's only a single conflict that can be easily resolved. @gsmet do you want me to send a separate PR for the 3.2 branch?

**Comment by gsmet** [comment]
@mkouba except if the changes only affect the Gradle plugin, I think this ship has sailed and we shouldn't backport it.

**Comment by mkouba** [comment]
> @mkouba except if the changes only affect the Gradle plugin, I think this ship has sailed and we shouldn't backport it.

@gsmet It does not affect the Gradle plugin. It merely allows users to run a `@QuarkusComponentTest` in a Gradle project.

**Comment by mkouba** [comment]
> > @peterfortuin It would be great if you could test your setup with this PR. Of course, you would need to [build the quarkus](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#build) first.
> 
> I have never build Quarkus for myself, so I need some time to figure that out. I will let you know about the result.

I'm going to merge this pr. If you encounter a problem we'll try to fix it in a follow-up.

**Comment by peterfortuin** [comment]
I have tested your code and I can confirm that the problem I reported in #35098 is fixed. Nice work!

**Comment by mkouba** [comment]
> I have tested your code and I can confirm that the problem I reported in #35098 is fixed. Nice work!

Thanks for verification!

**Pull request merged**
