### PR TITLE
Component upgrades for JBoss Threads

### PR DESCRIPTION
**Pull request by dmlloyd**
These component upgrades fix some potential thread pool scalability issues that show up on some CPU architectures.

### CODE REVIEW

**Comment by dmlloyd** [comment]
See https://issues.jboss.org/browse/JBTHR-71 for more information about the change.

**Comment by gsmet** [comment]
Triggered a rerun as the artifacts have been deployed on Central.

**Comment by dmlloyd** [comment]
Did it fail when I didn't notice?  I waited until both artifacts were on central before submitting the PR.

**Comment by gsmet** [comment]
It failed in the Maven cache job, I haven't looked for the details. Let's see what happens with this one.

**Comment by dmlloyd** [comment]
I couldn't find the historical build on Azure.  I guess we'll see how this one goes.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
At least the Maven cache job went well. Sometimes, there's a slight delay before all the Maven repo are synced so we might have had an issue with that.

**Pull request merged**
