### PR TITLE
Convert Lambda REST and HTTP to @ConfigMapping

### PR DESCRIPTION
**Pull request by mcruzdev**
This pull request aims to apply important Quarkus changes, you can see in more details [here](https://github.com/orgs/quarkiverse/discussions/228#discussioncomment-10451967) and [here](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#getting-your-application-to-compile).

Changes:

- Remove the need to use annotation processor compile args  `-AlegacyConfigRoot=true`
- Use `@ConfigMapping` and `@WithDefault` annotations.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Awesome, thanks!

**Comment by mcruzdev** [comment]
is related, taking a look

**Comment by gsmet** [comment]
Thanks a lot!

**Comment by mcruzdev** [comment]
Seeing here all extensions that need migration, I forgot the `lambda/common-*` modules.

**Pull request merged**
