### PR TITLE
OIDC providers fixes

### PR DESCRIPTION
**Pull request by FroMage**
Updates the facebook provider now that it supports an id token. Also for free, a missing exception cause.

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @FroMage, you probably need t remove [this](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/test/java/io/quarkus/oidc/runtime/OidcUtilsTest.java#L130..L134) check and [this](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/test/java/io/quarkus/oidc/runtime/OidcUtilsTest.java#L97..L101) check :-).
I see I missed testing the apple properties which are removed in this PR, so it should be fine with `apple`

**Comment by sberyozkin** [comment]
@FroMage By the way, let me remove `Fixes` - I'll work on making sure setting `idTokenRequired=false` does not cause a failure if `IdToken` is actually returned

**Comment by gsmet** [comment]
CI is unhappy. See @sberyozkin comment above.

Please let's try to get this merged by Tuesday evening to get this into 2.7.

**Comment by FroMage** [comment]
Updated with suggestions including from https://github.com/quarkusio/quarkus/pull/22572#issuecomment-1017352982

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks

**Pull request merged**
