### PR TITLE
Use Dev Services for Infinispan Client IT and enforce Hibernate Search constraint in BOM

### PR DESCRIPTION
**Pull request by gsmet**
Dragging the server via a test resource was problematic as the server requires a specific version of Hibernate Search.
Now that we have Dev Services for Infinispan, we can use them in the Infinispan IT module.

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Review by yrodiere — APPROVED** [review]

**Review by karesti — APPROVED** [review]
Changes look good to me! thanks @gsmet

**Review by karesti — CHANGES_REQUESTED** [review]
Sorry I just saw this error on the HealthCheck

java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.infinispan.client.deployment.devservices.InfinispanDevServiceProcessor#startInfinispanContainers threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerFetchException: Can't get Docker image

is

**Review by karesti — COMMENTED** [review]
@gsmet the code is ok but I'm just wondering what happened with the healthcheck test that failed and if is just normal

**Comment by aloubyansky** [comment]
@karesti if you are curious about the original issue, it was found that (a part of) Infinispan was incompatible with Hibernate Search included in Quarkus https://github.com/quarkusio/quarkus/pull/26565#issuecomment-1176584494
This PR is a workaround to avoid using the Infinispan server and Hibernate Search in the same runtime for the test.

**Comment by gsmet** [comment]
Issue fixed, let's wait for CI.

**Pull request merged**
