### PR TITLE
Generics in GraphQL app startup fail patched #12230

### PR DESCRIPTION
**Pull request by velias**
Tests added to cover use of Generics in GraphQL also, so similar problems should be catched automatically next time.

### CODE REVIEW

**Comment by velias** [comment]
@phillip-kruger  this is patch for #12230

**Comment by velias** [comment]
DO NOT MERGE yet please, I found some other cases where problem still persists

**Comment by velias** [comment]
OK, I improved cleanup to cover really all locations, so PR CAN BE MERGED once all checks pass

**Comment by phillip-kruger** [comment]
@velias - looking at it now...

**Comment by phillip-kruger** [comment]
@velias - Thanks for this. Can I ask a favour please, the PR contains a lot of formatting changes that makes it difficult to do a review and can create unnecessary conflicts. Please revert the formatting changes. Thanks :)

**Comment by phillip-kruger** [comment]
@velias - don't worry about the above comment. I am going to close this PR. The fix is actually in SmallRye. I have already done it there. Very simple fix, I should have picked it up earlier. There is no setMethod for ParametrizedTypeArguments, so the object can not be recreated. I have created a fix and will release and do a PR with your test cases and with the new version. Thanks for your help on this.

**Comment by velias** [comment]
Thanks. Thing is that ParametrizedTypeArguments are not necessary for static init phase (they are used during Scheme object creation only), so I believe it is not necessary to record them for STATIC_INIT to keep generated code smaller and app init faster. It is probably only small difference, so not so important, but this cleanup I implemented can be kept if you think this optimization is worth it.

**Comment by phillip-kruger** [comment]
The Schema model is used to build the GraphQL Execution on startup. So I think for now we keep it there (not going to make a visible difference, as we already create all the other objects).

**Pull request closed without merging**
