### PR TITLE
Add DevUI entry for RESTEasy Reactive Exception mappers

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
The UI for now is completely horrendous... @phillip-kruger any super quick tips for fixing it?

All I want to do is display something like a table with 3 rows (the values of which however could be long)

**Comment by phillip-kruger** [comment]
I'll have a look

**Comment by geoand** [comment]
Thanks a lot!

**Comment by phillip-kruger** [comment]
after

**Comment by phillip-kruger** [comment]
@geoand - what would be cool, is if the built-in exception mappers contain the `@ApiResponse` annotation from open api. Then not only would the openapi doc be more complete, we can possibly grap the HTTP response code from there and show that in this screen. It would however create a dependency on mp openapi. Or we can introduce a new annotation in rest easy reactive that give some basic info like maybe the HTTP code and description, and we add support for that in OpenAPI.

w.d.y.t ?

**Comment by phillip-kruger** [comment]
Another option for this screen (because the text is so long, on small screens it will wrap), is to do what we do in the log, so something like 
`io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.ForbiddenExceptionMapper`
becomes
`io.qu.re.re.se.ru.ex.ForbiddenExceptionMapper`

and then in the tooltip we add the full package name ? Let me know

**Comment by geoand** [comment]
> @geoand - what would be cool, is if the built-in exception mappers contain the `@ApiResponse` annotation from open api. Then not only would the openapi doc be more complete (if used), we can possibly grap the HTTP response code from there and show that in this screen. It would however create a dependency on mp openapi. Or we can introduce a new annotation in rest easy reactive that give some basic info like maybe the HTTP code and description, and we add support for that in OpenAPI.
> 
> w.d.y.t ?

We can certainly add it to the ones we control the source. Is there anything else to be done other than adding the annotation?
Is there another way to register such metadata for other that we don't control the source but we do register with RESTEesy Reactive?

**Comment by geoand** [comment]
> and then in the tooltip we add the full package name ? Let me know

I think we can keep your current version for now, it looks great, thanks!!!!
We can certainly improve later if needed.

**Comment by phillip-kruger** [comment]
> Is there another way to register such metadata for other that we don't control the source but we do register with RESTEesy Reactive?

The other option is to use a filter, but that will be a bit more complex, as you need to know for what methods this needs to be added (So what methods will throw this) and I do not think this is possible.

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Yea we would need access to the mapper code then...

**Comment by geoand** [comment]
Let me know what you need from the RESTEasy Reactive side and we can make it happen 😉

**Pull request merged**
