### PR TITLE
Support data.sql in Spring Data JPA module

### LINKED ISSUE #40037: Import DB data from data.sql when using quarkus-spring-data-jpa extension
### Description

In Quarkus we have support for loading data from `import.sql` in dev and test mode. SB uses `data.sql`. When people are moving to Quarkus they need to be aware of different file name and rename their `data.sql`.

Quarkus should be able to to work with `data.sql` when `quarkus-spring-data-jpa` extension is added to the project to make the transition slightly easier.

Another approach could be a global change to make `data.sql` fallback if `import.sql` is unavailable.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #40037

### CODE REVIEW

**Comment by geoand** [comment]
Good point. 

I think the Quarkus way is fine and no one has really complained AFAIR so for now I would leave Hibernate as it is

**Review by rsvoboda — APPROVED** [review]
Checked with `spring-data-jpa-quickstart`, scenario when there was 
 - import.sql
 - data.sql
 - both import.sql and data.sql, import.sql was the one that got picked

**Comment by geoand** [comment]
Let's go ahead and merge this and if we really decide that `data.sql` should be added to Hibernate as well, then we can easily do that too

**Comment by rsvoboda** [comment]
@geoand https://quarkus.io/guides/spring-data-jpa#prepare-the-data should be updated to mention support for `data.sql`

**Comment by rsvoboda** [comment]
gosh, you were quick @geoand :)

**Comment by geoand** [comment]
Ah docs...

**Comment by geoand** [comment]
#40046

**Pull request merged**
