### PR TITLE
Extracted Maven test framework from quarkus-maven-plugin

### LINKED ISSUE #3588: devtools/maven to provide a test framework for extensions
ATM, devtools/maven aggregates tests for various extensions (such as kotlin, kogito, etc) that are added as test dependencies. It would help a lot productization to avoid building dependencies that shouldn't be productized. Instead of adding tests to directly to devtools/maven, devtools/maven could provide a test framework that extensions could import into their testsuites and keep their tests in their own modules.

### PR DESCRIPTION
**Pull request by aloubyansky**
...and moved the Maven integration tests to the IT module keeping kotlin, kogito and scala separate from the rest.

Fixes #3588 

This serves a few purposes:
* helps productization to exclude extensions they are not interested in;
* establish proper parent-child project relationships in our repo w/o introducing cyclic deps (and allow me continue working on the build-parent pom split);
* allow external extensions build their maven integration tests in the same manner.

### CODE REVIEW

**Comment by aloubyansky** [comment]
FYI @michalszynkiewicz

**Comment by geoand** [comment]
@aloubyansky I am seeing this in the tests:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.937 s
[INFO] Finished at: 2019-08-22T23:20:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project acme: Could not resolve dependencies for project org.acme:acme:jar:1.0-SNAPSHOT: Could not find artifact io.quarkus:quarkus-kotlin-deployment:jar:999-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
">
to contain:
 <"ready">
 (ignoring case)
[ERROR] Errors: 
[ERROR]   KotlinDevModeIT.testThatTheApplicationIsReloadedOnKotlinChange:22->RunAndCheckMojoTestBase.runAndCheck:46->MojoTestBase.getHttpResponse:191 » ConditionTimeout
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.0:verify (default) @ quarkus-kotlin-deployment ---
[INFO] ------------------------------------------------------------------------
```

**Comment by michalszynkiewicz** [comment]
thanks @aloubyansky !

**Comment by aloubyansky** [comment]
Yes, I rebased before pushing. Perhaps some change got in the way.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
