### PR TITLE
Micro versions bumps

### PR DESCRIPTION
**Pull request by rsvoboda**
Micro versions bumps

 - ~~elasticsearch-rest-client~~
 - rxjava
 - mysql-jdbc
 - artemis
 - freemaker

### CODE REVIEW

**Comment by gsmet** [comment]
Please do not upgrade `elasticsearch-rest-client`, we upgrade it when we upgrade Hibernate Search as it needs to be properly tested.

**Comment by gsmet** [comment]
@gastaldi I'm thinking we should add the JDBC drivers to dependabot? WDYT?

**Comment by gastaldi** [comment]
@gsmet :+1: that's the main reason why I wanted to introduce dependabot.

**Comment by rsvoboda** [comment]
@gsmet PR updated

**Comment by gastaldi** [comment]
@rsvoboda if you believe these libraries should be monitored by dependabot, send a PR including them in the `.dependabot/config.yml`.  I have created for the JDBC drivers here: https://github.com/quarkusio/quarkus/pull/5836

**Comment by gsmet** [comment]
I think adding freemarker and the Artemis artifacts would make sense.

**Comment by rsvoboda** [comment]
Artemis has to be updated on 2 places, is dependabot ok to handle it?

**Comment by gastaldi** [comment]
@rsvoboda yes

**Comment by rsvoboda** [comment]
ok, I will prepare PR for them

**Comment by rsvoboda** [comment]
hm, should I add both artemis artifacts or just one (core-client)?
`org.apache.activemq:artemis-core-client`
`org.apache.activemq:artemis-jms-client`

```xml
            <dependency>
                <groupId>org.apache.activemq</groupId>
                <artifactId>artemis-core-client</artifactId>
                <version>${artemis.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.activemq</groupId>
                <artifactId>artemis-jms-client</artifactId>
                <version>${artemis.version}</version>
            </dependency>
```

https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L39 defines just property for artemis

**Comment by gsmet** [comment]
I would add both.

**Comment by rsvoboda** [comment]
PR: https://github.com/quarkusio/quarkus/pull/5842

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
