### PR TITLE
Use proper syntax to open file at line for Visual Studio Code, Intellij and Eclipse

### LINKED ISSUE #22574: x - open last stacktrace not working with vscode/codium
### Describe the bug

have exception occur and try use `x` to open it and you get code to open "main.java:18" which is not a syntax code supports.

example app:

```
//usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus.platform:quarkus-bom:2.6.1.Final@pom
//DEPS io.quarkus:quarkus-resteasy

//JAVAC_OPTIONS -parameters

import io.quarkus.runtime.Quarkus;
import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/hello-resteasy")
@ApplicationScoped
public class main {

    @GET
    public String sayHello() {
        throw new IllegalStateException("What up");
        
    }

    public static void main(String[] args) {
        Quarkus.run(args);
    }
}
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #22574

@maxandersen can you try with this patch?

### CODE REVIEW

**Comment by gsmet** [comment]
@maxandersen I don't really know how to reproduce this in VSCode as I never used this feature so I let you check it's working.

**Comment by maxandersen** [comment]
vscode works now.
intellij does not. It launches but opens up "main.java:18" so its not the right syntax somehow.
eclipse does not seem work - nothing happens. no error/warn etc. shown even with trace enabled so not sure what happens.


Also once got this weird (probably unrelated to this PR) error if eclipse is running while I start (just setting `quarkus.ide.target=eclipse` don't trigger it):
```
java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.ide.EffectiveIdeBuildItem.getIde()" because "this.val$ideSupport" is null
	at io.quarkus.deployment.console.ConsoleProcessor$4.run(ConsoleProcessor.java:137)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:73)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:46)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$1(AeshConsole.java:247)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:118)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)
	at org.aesh.terminal.io.Decoder.write(Decoder.java:133)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

will do same with 2.6.2 to see if these are regressions or old issues.

**Comment by maxandersen** [comment]
2.6.2 have the same issue with respect to having eclipse running - opened #23002

in 2.6.2 intellij does not even open so albeit this PR is "better" as vscode at least works but something still quirky.

**Comment by gsmet** [comment]
OK, looks like this thing was never tested.

The syntax for Intellij is also completely different: https://www.jetbrains.com/help/idea/opening-files-from-command-line.html. I will fix that.

**Comment by gsmet** [comment]
I added fixes for Eclipse and Intellij. It doesn't fix any infra issue you might have had but at least the options should be OK now.

I couldn't figure out how to make things work with Netbeans though.

**Comment by geoand** [comment]
> OK, looks like this thing was never tested.

it definitely was when I developed it as I use IntelliJ exclusively :)

**Comment by maxandersen** [comment]
Yeah it was tested back then - looking a bit deeper what I'm finding is that I believe idea changed their command line so `idea --help` does not work anymore so detection fails/gets weird.

For eclipse its an OSX thing that fails because the command line to open eclipse on OSX is different ...for stupid eclipse reasons. 

so i'll say its better with this PR in; but still some ghosts left to fix.

**Comment by gsmet** [comment]
Well, the go to line feature was never tested. Because the `file:line number` syntax is working for Vim but that's pretty much it :).

**Comment by geoand** [comment]
> Well, the go to line feature was never tested. Because the file:line number syntax is working for Vim but that's pretty much it :).

What makes you think that?
As I said, when I first developed this stuff, it was tested multiple times on IntelliJ and it always moved to proper line.

The fact that it does go to the proper line for the current version of IntelliJ (which I can confirm), does not mean the feature was not tested when it was developed...

**Comment by gsmet** [comment]
I added a commit to just open the file and not use the `file:line` syntax if no proper options have been provided for the IDE.

AFAICS, the `file:line` number doesn't work for any of them so the changes it will work magically for other IDEs are very thin.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
Merging this one. Even if it doesn't fix everything, it's a step in the right direction.

**Comment by geoand** [comment]
Absolutely

**Pull request merged**
