### PR TITLE
Multiple persistence units support Phase 2

### PR DESCRIPTION
**Pull request by gsmet**
This is a draft PR, mostly to have @machi1990 take a look.

The interesting commit is the last one. All the other commits will be merged as part of https://github.com/quarkusio/quarkus/pull/11519 .

### CODE REVIEW

**Comment by machi1990** [comment]
Thanks @gsmet

**Comment by gsmet** [comment]
@machi1990 I merged the other PR and rebased this one.

**Comment by machi1990** [comment]
Just noticed the merge. Let me get the changes in my branch now.

**Comment by gsmet** [comment]
@gavinking @Sanne I added the support for package level annotations in this PR.

I didn't implement class level annotations as I don't think it's worth implementing it until we get a proper way to get all the dependent classes of a given entity to also add them to the persistence unit. I have no plans to work on that for now.

One thing that is important and I'm a bit torn about is that I used the same annotation as the CDI qualifier. For me there are two options: use the same name and thus the same annotations or find a different name. Having a different name is probably safer but couldn't find a good one. Any name proposal?

**Comment by gavinking** [comment]
> I added the support for package level annotations in this PR.

Excellent!

> I didn't implement class level annotations

That's totally fine, IMO.

> One thing that is important and I'm a bit torn about is that I used the same annotation as the CDI qualifier.

I wonder if it would make sense to somehow use a type safe CDI qualifier annotation at the package level to refer to the PU.

I mean, we must have some way to disambiguate the persistence unit of an injected `EntityManager` using a CDI `@Qualifier` annotation (though at this moment I forget exactly how that works). I feel like we could use the same annotation to disambiguate the the PU to which the entities belong.

**Comment by gavinking** [comment]
> I mean, we must have some way to disambiguate the persistence unit of an injected `EntityManager` using a CDI `@Qualifier` annotation (though at this moment I forget exactly how that works).

Right, so you can just use a `@Producer`, I forget my own APIs. (Though I'm not sure if this is still how it works in Quarkus.)

So you can write:

```java
@Produces @PersistenceContext(unitName = "customerData")
@Customers EntityManager entityManager;
```

Now the CDI spec doesn't say that your qualifier annotation *can't* be `@Target(PACKAGE)`, so I think in principle you could make the `@Customers` qualifier be `@Target(PACKAGE)` and use it to declare the persistence context to which the `@Entity`s belong.

WDYT?

**Comment by gsmet** [comment]
Right now we do the following for the injection:

```java
@PersistenceUnit("users")
EntityManager entityManager;
```

and at the package level (where you can have several annotations):
```java
@PersistenceUnit("users")
@PersistenceUnit("inventory")
package io.quarkus.hibernate.orm.multiplepersistenceunits.model.annotation.shared;

import io.quarkus.hibernate.orm.PersistenceUnit;
```

I think it's in line with what you had in mind.

**Comment by gavinking** [comment]
Yes I understand that but what I'm saying is that I would like to have the option of mapping the untypesafe `@PersistenceUnit(name="stringiness")` to the typesafe `@Customers` and use the typesafe one.

**Comment by gavinking** [comment]
(It's just what you're supposed to do for EM injection in CD anyway.)

**Comment by gsmet** [comment]
Yeah the thing is that we produce the entityManagers ourselves. And also I would like to keep this as consistent as possible with the approach we used for datasources.

That doesn't prevent us to go your way in the future anyway - having a qualifier I also use on packages is already what I do - but I think the default approach should be consistent with what we already have.

A lot of people are not that accustomed with CDI and JPA, we have a lot of Spring users coming so having a consistent experience across Quarkus is important.

**Comment by gsmet** [comment]
That could be a nice pet project for a new contributor btw.

**Comment by gsmet** [comment]
@machi1990 any chance you could do a proper review of the code? Thanks!

**Review by machi1990 — APPROVED** [review]
Code looks good. Reviewed it and verified it when I was updating https://github.com/quarkusio/quarkus/pull/8695.

**Comment by gsmet** [comment]
Thanks @machi1990 , merging this one so that we can make progress and have other people test it (and adjust if necessary).

**Pull request merged**
