### PR TITLE
refactor: Remove obsolete decorators

### PR DESCRIPTION
**Pull request by iocanel**
The pull request removes two decorator implementations that are no longer needed, as ApplicationContainerDecorators can be now used directly even on Objects that have no metadta.

### CODE REVIEW

**Comment by iocanel** [comment]
cc' @metacosm: We recently discussed about this issue, so I thought that you should know.

**Review by geoand — APPROVED** [review]
I trust you with this :)

**Comment by metacosm** [comment]
Doesn't this change require a new dekorate version or was that already handled in a previous change?

**Comment by iocanel** [comment]
We have already upgraded dekorate.

**Pull request merged**
