### PR TITLE
Fix misleading Javadoc on NativeConfig

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by dmlloyd — APPROVED** [review]
Seems OK.  But we really ought to be using `MemorySize` for this!

**Comment by geoand** [comment]
`MemorySize`?

**Comment by dmlloyd** [comment]
`io.quarkus.runtime.configuration.MemorySize`.  It's designed to hold values representing memory sizes... well "designed" might be an overstatement.  I've got a newer variant in the pipeline though which can input and output memory size strings in a sane format.

Anyway it's just a mental note for the future.

**Comment by geoand** [comment]
That's nice to know, thanks!

**Comment by gsmet** [comment]
Merged and cancelled the workflow.

**Pull request merged**
