### PR TITLE
Fix native compilation for Netty and Mutiny

### LINKED ISSUE #39819: Netty update caused failure when building image
### Describe the bug

When building image containing `quarkus-jdbc-postgresql` the build failing on ` Performing analysis...` step with error:
```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
org.jctools.util.UnsafeRefArrayAccess the class was requested to be initialized at run time (from feature io.quarkus.runner.Feature.beforeAnalysis with ''). To see why org.jctools.util.UnsafeRefArrayAccess got initialized use --trace-class-initialization=org.jctools.util.UnsafeRefArrayAccess
io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
io.netty.buffer.UnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///home/jjedlick/work/quarkus-reproducers/target/quarkus-reproducers-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.108.Final.jar' with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///home/jjedlick/work/quarkus-reproducers/target/quarkus-reproducers-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.108.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///home/jjedlick/work/quarkus-reproducers/target/quarkus-reproducers-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.108.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
To see how the classes got initialized, use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledDirectByteBuf,org.jctools.util.UnsafeRefArrayAccess,io.netty.buffer.UnpooledUnsafeDirectByteBuf,io.netty.buffer.UnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledHeapByteBuf,io.netty.buffer.ByteBufUtil,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.AbstractReferenceCountedByteBuf,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
org.jctools.util.UnsafeRefArrayAccess the class was requested to be initialized at run time (from feature io.quarkus.runner.Feature.beforeAnalysis with ''). To see why org.jctools.util.UnsafeRefArrayAccess got initialized use --trace-class-initialization=org.jctools.util.UnsafeRefArrayAccess
io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
io.netty.buffer.UnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///home/jjedlick/work/quarkus-reproducers/target/quarkus-reproducers-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.108.Final.jar' with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///home/jjedlick/work/quarkus-reproducers/target/quarkus-reproducers-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.108.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///home/jjedlick/work/quarkus-reproducers/target/quarkus-reproducers-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.108.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
To see how the classes got initialized, use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledDirectByteBuf,org.jctools.util.UnsafeRefArrayAccess,io.netty.buffer.UnpooledUnsafeDirectByteBuf,io.netty.buffer.UnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledHeapByteBuf,io.netty.buffer.ByteBufUtil,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.AbstractReferenceCountedByteBuf,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.checkDelayedInitialization(ProvenSafeClassInitializationSupport.java:273)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:164)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```
It was caused probably by https://github.com/quarkusio/quarkus/pull/39764 (not tested it without this commit) and it's probably same or simillar problem as in https://github.com/quarkusio/quarkus/pull/39788 PR.

This seems only affecting jdk 17 not jdk 21.

Looking at GeaalVM info for jdk 17:
```
Version info: 'GraalVM 22.3.2 Java 17 CE'
 Java version info: '17.0.7+7-jvmci-22.3-b18'
 C compiler: gcc (redhat, x86_64, 13.2.1)
```
for jdk 21:
```
Java version: 21.0.2+13-LTS, vendor version: Mandrel-23.1.2.0-Final
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (redhat, x86_64, 8.5.0)
```
Both GraalVM version is pulled automatically as I'm using openjdk

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

1. Build of Quarkus main branch
1. `git clone -b netty-native git@github.com:jedla97/quarkus-reproducers.git`
2. `cd quarkus-reproducers`
3. `./mvnw package -Dnative `

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

main/999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jponge**
See #39819 and #39788

### CODE REVIEW

**Comment by jponge** [comment]
Note: updated with a substitution for `UnsafeRefArrayAccess` / ignoring it could yield to segfaults as the field offset couldn't  be computed (it uses a non-classic `Unsafe` access pattern).

**Comment by zakkak** [comment]
> Note: updated with a substitution for `UnsafeRefArrayAccess` / ignoring it could yield to segfaults as the field offset couldn't be computed (it uses a non-classic `Unsafe` access pattern).

@jponge I had a look at `org.graalvm.nativeimage.hosted.Feature.BeforeAnalysisAccess#registerAsUnsafeAccessed` and it looks like it's mostly being used by Truffle.

Unsafe accesses seem to be automatically detected and registered by GraalVM, e.g. https://github.com/oracle/graal/blob/c95781d03099ebd1dad495ac1fefca863178b358/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/flow/MethodTypeFlowBuilder.java#L304

Does this mean we can follow this pattern and completely remove `UnsafeAccessedFieldBuildItem`s in favor of `RecomputeFieldValue`?

**Comment by zakkak** [comment]
@jponge please have a look at https://github.com/quarkusio/quarkus/pull/39831 as well before merging this. It makes the mutiny changes redundant.

**Comment by jponge** [comment]
> Does this mean we can follow this pattern and completely remove `UnsafeAccessedFieldBuildItem`s in favor of `RecomputeFieldValue`?

AFAIK most `Unsafe` patterns indeed get detected now, but one such as `UnsafeRefArrayAccess.REF_ELEMENT_SHIFT` is not, hence the need for either a substitution or a `UnsafeAccessedFieldBuildItem` that does not involved build-time init

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
> Does this mean we can follow this pattern and completely remove UnsafeAccessedFieldBuildItems in favor of RecomputeFieldValue?

I would be in favor of this. The `UnsafeAccessedFieldBuildItems` leads to loading the class at build time (and so run the initialization of the class) which can lead to issues if this class must be runtime only. I wonder if we can workaround this using "re-initialize at runtime".

**Comment by zakkak** [comment]
> The `UnsafeAccessedFieldBuildItems` leads to loading the class at build time (and so run the initialization of the class) which can lead to issues if this class must be runtime only. I wonder if we can workaround this using "re-initialize at runtime".

FYI I have a fix for this behavior in https://github.com/quarkusio/quarkus/pull/39831, but it's still WIP since it triggers other issues.

**Review by zakkak — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
🎉

**Comment by luneo7** [comment]
should this be backported to 3.8.4 as well? since vertx and netty was also upgraded there

**Comment by geoand** [comment]
Makes sense

**Comment by jponge** [comment]
Yes please!

**Comment by gsmet** [comment]
@jponge I don't think this can be backported as is to 3.9 and 3.8.

At least the commit with JCTools is causing issues as I think you are only using this with latest Mutiny?

```
Error: Substitution target for io.quarkus.mutiny.runtime.Target_org_jctools_util_UnsafeRefArrayAccess is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for io.quarkus.mutiny.runtime.Target_org_jctools_util_UnsafeRefArrayAccess is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1074)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:373)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:351)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1029)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:907)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:590)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
```

**Comment by jponge** [comment]
(discussed offline - yes 👍 )

**Comment by gsmet** [comment]
For 3.9 and 3.8, only the Netty changes should be backported.

See this commit: d2673c825ade4aac385586ceb337d56f0a084e46

**Pull request merged**
