### PR TITLE
Shade transitive dependencies in the IDE launcher

### LINKED ISSUE #9068: Uberjar does not include add dependencies
**Describe the bug**
[This](https://github.com/oscarfh/code-with-quarkus) is a project created from code.quarkus.io and configured to generate a uber jar and to use `com.google.common.base.Strings` class.
It will work if ran from maven (`./mvn quarkus:dev`), but not from the uber jar (`java -jar ...`) due to a missing dependency (the above mentioned class)

**Expected behavior**
Both should run.

**Actual behavior**
Only the maven version runs, because the development version seems to get this class from the dependency `quarkus-ide-launcher-1.4.1.Final.jar`. 
It can be even worse, is case the version executed in dev is different than the one executed on the environment.

**To Reproduce**
1. Checkout the project
2. Run with maven -> calling `http://localhost:8080/hello` works
3. Generate the uber jar (or use the one I added to the projecT)
4. See that you cannot call

### LINKED ISSUE #9506: quarkus-ide-launcher breaks mvn dependency:analyze
**Describe the bug**

When using https://maven.apache.org/plugins/maven-dependency-plugin/analyze-only-mojo.html there are some issues due to the new quarkus-ide-launcher introduced in 1.4 that is shading a lot of classes from other dependencies:

```
[INFO] --- maven-dependency-plugin:3.1.2:analyze-only (default)
[WARNING] Used undeclared dependencies found:
[WARNING]    io.quarkus:quarkus-ide-launcher:jar:1.4.1.Final:runtime
[WARNING] Unused declared dependencies found:
[WARNING]    org.slf4j:slf4j-api:jar:1.7.30:compile
```

It's possible to exclude the dependencies shaded by quarkus-ide-launcher from the analysis but the more you exclude the less interesting the plugin...

A workaround with Quarkus 1.4 was to exclude quarkus-core --> quarkus-ide-launcher transitive dependency, thinking IDE-related stuff shouldn't matter too much:

```
<dependencyManagement>
  <dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-core</artifactId>
    <exclusions>
      <exclusion>
        <artifactId>quarkus-ide-launcher</artifactId>
        <groupId>io.quarkus</groupId>
      </exclusion>
    </exclusions>
  </dependency>
<dependencyManagement>
```

But with Quarkus 1.5.0.CR1 this is no longer possible, as it now causes a NoClassDefFoundError during `@QuarkusTest` bootstrap (including via Maven CLI outside IDE):

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/eclipse/sisu/inject/Weak

	at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:273)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/sisu/inject/Weak
	at org.codehaus.plexus.component.configurator.converters.lookup.DefaultConverterLookup.<init>(DefaultConverterLookup.java:77)
	at io.quarkus.bootstrap.resolver.maven.BootstrapWagonConfigurator.<init>(BootstrapWagonConfigurator.java:18)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.newRepositorySystem(BootstrapMavenContext.java:567)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRepositorySystem(BootstrapMavenContext.java:192)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:123)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.getAppModelResolver(BootstrapAppModelFactory.java:180)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:286)
	at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:137)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:131)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:287)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:310)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	... 29 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.sisu.inject.Weak
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 46 more
```

**Expected behavior**

I'm not sure what quarkus-ide-launcher is actually doing ^_^, but based on its name it should not be required outside the IDE ? 

**To Reproduce**
1. mvn maven-dependency-plugin:3.1.2:analyze-only -DfailOnWarning=true

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: MINGW64_NT-10.0 x86_64 Msys
 - Output of `java -version`: java version "11.0.5" 2019-10-15 LTS
 - Quarkus version or git rev: 1.5.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Apache Maven 3.6.3

### LINKED ISSUE #9826: quarkus-ide-launcher duplicates classes from commons-lang etc without shading
See discussion here:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/quarkus-ide-launcher.20vs.20enforcer

In our project we have the enforcer rule org.apache.maven.plugins.enforcer.BanDuplicateClasses.
Because `quarkus-ide-launcher` is a fat jar that includes `jboss-logging` and `commons-lang3`, our build fails:

Duplicate classes found:

```
  Found in:
    org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
    io.quarkus:quarkus-ide-launcher:jar:1.4.2.Final:compile
...
  Found in:
    org.apache.commons:commons-lang3:jar:3.9:compile
    io.quarkus:quarkus-ide-launcher:jar:1.4.2.Final:compile
```

Our dependency tree:

```
[INFO] org.optaplanner:optaplanner-quarkus:jar:7.39.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-core:jar:1.4.2.Final:compile
[INFO] |  +- io.quarkus:quarkus-ide-launcher:jar:1.4.2.Final:compile
...
[INFO] +- org.optaplanner:optaplanner-core:jar:7.36.1.Final:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.9:compile
...
```
**Those classes should be shaded.**

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #9826 
Fixes #9068 
Fixes #9506

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Comment by famod** [comment]
@aloubyansky This "only" shades those dependencies but the `ide-launcher` will still end up on the compile classpath in the IDE (e.g. Eclipse), right?
The problem is that it is easy to import the wrong things...

**Comment by aloubyansky** [comment]
Right. At least the package will hint about the wrong origin. Not ideal, agreed, but still an improvement. Feel free to create an issue about completely hiding them.

**Comment by famod** [comment]
> At least the package will hint about the wrong origin. 

I guess this is why some projects use really ugly looking (even randomized?) packages like `org/jacoco/agent/rt/internal_43f5073/Offline`.

> but still an improvement.

Agreed.

**Comment by aloubyansky** [comment]
> > At least the package will hint about the wrong origin.
> 
> I guess this is why some projects use really ugly looking (even randomized?) packages like `org/jacoco/agent/rt/internal_43f5073/Offline`.

Oh, sure, we could make it uglier!

**Comment by famod** [comment]
> @aloubyansky This "only" shades those dependencies but the `ide-launcher` will still end up on the compile classpath in the IDE (e.g. Eclipse), right?
> The problem is that it is easy to import the wrong things...

FTR, #10067 seems to solve this issue.

**Pull request merged**
