### PR TITLE
Document Resteasy Reactive Links

### PR DESCRIPTION
**Pull request by Sgitario**
Added documentation for resteasy reactive links.

Note that I haven't added any feature on top of the existing resteasy reactive links, only documentation, javadocs, and cosmetic changes in code.

### CODE REVIEW

**Comment by Sgitario** [comment]
Possible next actions:
1.- Add support for HAL types: this is already supported by Reactive REST data panache and we could bring this functionality into the resteasy reactive links with little effort (but I'm not sure if we can avoid some duplication... )
2.- Improve the `rel` values in `RestLink`. At the moment, if not set, it will use the method name. However, I think we could be smarter here to use the same convention than in [resteasy classic](https://docs.jboss.org/resteasy/docs/2.0.0.GA/userguide/html/LinkHeader.html) (see table in section 8.2.4).
3.- It was hard for me to understand the concepts of TYPE and INSTANCE in RestLinkType. And after seeing the comments from the original pull request, I read that it was also confused. From my point of view, we should get rid of it and just infer the usage of TYPE and INSTANCE by the response type. 

cc @geoand

**Comment by geoand** [comment]
They all sound very reasonable to me.

**Review by gsmet — APPROVED** [review]
This looks good to me. Is it ready to get merged?

**Comment by geoand** [comment]
I'll check soon

**Review by geoand — APPROVED** [review]
Great stuff, thanks a lot @Sgitario!

**Pull request merged**
