### PR TITLE
Fix bug with non application endpoint redirect for root-path

### LINKED ISSUE #14109: smallrye-health extension doesn't work when a root path is set in 1.11.0.BetaX versions
**Describe the bug**
Using quarkus 1.11.0.Beta2 version, smallrye health endpoint is not found when a root path is set
(Behaviour is the same for 1.11.0.Beta1)

**Expected behavior**
When calling http://localhost:8080/myrootpath/health should return a 200 with some health informations

**Actual behavior**
When calling http://localhost:8080/myrootpath/health a 404 Resource Not Found is returned. Moreover, I'm redirected to http://localhost:8080/q/myrootpath/health which also returns a 404

**To Reproduce**
https://github.com/jessydeclerck/microprofile-health-issue

1. mvn compile quarkus:dev
2. Check http://localhost:8080/myrootpath/health => Resource Not Found
3. Shutdown app, set quarkus-plugin.version and quarkus.platform.version to 1.10.5.Final
4. mvn compile quarkus:dev
5. Check http://localhost:8080/myrootpath/health => Works perfectly

### PR DESCRIPTION
**Pull request by kenfinnigan**
When `root-path` is not `/`

Fixes #14109

### CODE REVIEW

**Comment by kenfinnigan** [comment]
This *should* fix the issue, but this new test and existing tests started acting really weird locally.

I'm hoping CI fairs better, otherwise, I will look further

**Comment by gsmet** [comment]
@kenfinnigan CI doesn’t look happy.

**Comment by kenfinnigan** [comment]
Will try again in the morning

**Comment by gsmet** [comment]
OK, it missed the CR1 train then. But we can merge it for the Final given it's a bugfix.

**Comment by kenfinnigan** [comment]
@gsmet Should be good now.

Would this require a backport label to be applied to 1.11?

**Comment by gsmet** [comment]
Yes, added!

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
