### PR TITLE
Avoid creating potential build cycles between OTel and logging

### LINKED ISSUE #44181: Quarkus does not start in dev mode with Otel logs enabled and OIDC enabled
### Describe the bug

I have an application that uses `quarkus-oidc` and `quarkus-opentelemetry` extensions with `quarkus.otel.logs.enabled=true` property.

Start the application using `./gradlew quarkusDev`

### Expected behavior

Application starts in dev mode with keycloak devservice running.

### Actual behavior

Application does not start because of ChainBuildException

```
ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Cycle detected:
                   io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.ResourcesGeneratedPhaseBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#initializeContainer produced class io.quarkus.arc.deployment.ArcContainerBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#notifyBeanContainerListeners produced class io.quarkus.arc.deployment.PreBeanContainerBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady produced class io.quarkus.arc.deployment.BeanContainerBuildItem
                to io.quarkus.opentelemetry.deployment.logging.LogHandlerProcessor#build produced class io.quarkus.deployment.builditem.LogHandlerBuildItem
                to io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit produced class io.quarkus.deployment.logging.LoggingSetupBuildItem
                to io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer produced class io.quarkus.devservices.keycloak.KeycloakDevServicesConfigBuildItem
                to io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevUIProcessor#produceProviderComponent produced class io.quarkus.arc.deployment.SyntheticBeanBuildItem
                to io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem$BeanConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#registerSyntheticObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem
                to io.quarkus.arc.deployment.StartupBuildSteps#registerStartupObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem$ObserverConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#validate
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:354)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:89)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:428)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.ChainBuildException: Cycle detected:
                   io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.ResourcesGeneratedPhaseBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#initializeContainer produced class io.quarkus.arc.deployment.ArcContainerBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#notifyBeanContainerListeners produced class io.quarkus.arc.deployment.PreBeanContainerBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady produced class io.quarkus.arc.deployment.BeanContainerBuildItem
                to io.quarkus.opentelemetry.deployment.logging.LogHandlerProcessor#build produced class io.quarkus.deployment.builditem.LogHandlerBuildItem
                to io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit produced class io.quarkus.deployment.logging.LoggingSetupBuildItem
                to io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer produced class io.quarkus.devservices.keycloak.KeycloakDevServicesConfigBuildItem
                to io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevUIProcessor#produceProviderComponent produced class io.quarkus.arc.deployment.SyntheticBeanBuildItem
                to io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem$BeanConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#registerSyntheticObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem
                to io.quarkus.arc.deployment.StartupBuildSteps#registerStartupObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem$ObserverConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#validate
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:327)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:291)
        at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:284)
        at io.quarkus.builder.BuildChainBuilder.build(BuildChainBuilder.java:157)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:143)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
        ... 9 more
```

### How to Reproduce?

Reproducer repository: https://github.com/BogdanAlexa1234/quarkus-repro-otel-log-keycloak

### Output of `uname -a` or `ver`

Linux bogdan 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.8 2023-07-18 OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7) OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

### Quarkus version or git rev

3.16.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.10

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #44181

@mkouba I marked you as co-author, let's see how CI goes.

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Comment by gsmet** [comment]
I tested the reproducer and it worked well but some tests are failing with:

```
2024-11-18T09:50:31.9138227Z [ERROR] io.quarkus.opentelemetry.deployment.logs.OtelLoggingFileTest -- Time elapsed: 2.038 s <<< ERROR!
2024-11-18T09:50:31.9140057Z java.lang.RuntimeException: Failed to start quarkus
2024-11-18T09:50:31.9141282Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2024-11-18T09:50:31.9142634Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2024-11-18T09:50:31.9143854Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-11-18T09:50:31.9145220Z 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
2024-11-18T09:50:31.9146678Z 	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:689)
2024-11-18T09:50:31.9148202Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-11-18T09:50:31.9151690Z Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [Le6zQbzkojAYO_OiKIQWJf4lGa4]: jakarta.enterprise.inject.CreationException: Synthetic bean instance for io.opentelemetry.api.OpenTelemetry not initialized yet: io_opentelemetry_api_OpenTelemetry_4087e2c748253198bc7b05f31387f3f4492f0131
2024-11-18T09:50:31.9155583Z 	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
2024-11-18T09:50:31.9157605Z 	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
2024-11-18T09:50:31.9159556Z 	at io.opentelemetry.api.OpenTelemetry_Le6zQbzkojAYO_OiKIQWJf4lGa4_Synthetic_Bean.doCreate(Unknown Source)
2024-11-18T09:50:31.9161139Z 	at io.opentelemetry.api.OpenTelemetry_Le6zQbzkojAYO_OiKIQWJf4lGa4_Synthetic_Bean.create(Unknown Source)
2024-11-18T09:50:31.9162726Z 	at io.opentelemetry.api.OpenTelemetry_Le6zQbzkojAYO_OiKIQWJf4lGa4_Synthetic_Bean.create(Unknown Source)
2024-11-18T09:50:31.9164623Z 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
2024-11-18T09:50:31.9166077Z 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
2024-11-18T09:50:31.9167357Z 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
2024-11-18T09:50:31.9168393Z 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
2024-11-18T09:50:31.9169405Z 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
2024-11-18T09:50:31.9170920Z 	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
2024-11-18T09:50:31.9172437Z 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
2024-11-18T09:50:31.9173815Z 	at io.opentelemetry.api.OpenTelemetry_Le6zQbzkojAYO_OiKIQWJf4lGa4_Synthetic_Bean.get(Unknown Source)
2024-11-18T09:50:31.9175371Z 	at io.opentelemetry.api.OpenTelemetry_Le6zQbzkojAYO_OiKIQWJf4lGa4_Synthetic_Bean.get(Unknown Source)
2024-11-18T09:50:31.9176995Z 	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:559)
2024-11-18T09:50:31.9178381Z 	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:539)
2024-11-18T09:50:31.9179760Z 	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:572)
2024-11-18T09:50:31.9181064Z 	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:534)
2024-11-18T09:50:31.9182291Z 	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:294)
2024-11-18T09:50:31.9183936Z 	at io.quarkus.opentelemetry.runtime.logs.OpenTelemetryLogRecorder.initializeHandler(OpenTelemetryLogRecorder.java:18)
2024-11-18T09:50:31.9185660Z 	at io.quarkus.deployment.steps.LogHandlerProcessor$build905456565.deploy_0(Unknown Source)
2024-11-18T09:50:31.9187054Z 	at io.quarkus.deployment.steps.LogHandlerProcessor$build905456565.deploy(Unknown Source)
2024-11-18T09:50:31.9193122Z 	... 6 more
2024-11-18T09:50:31.9194873Z Caused by: jakarta.enterprise.inject.CreationException: Synthetic bean instance for io.opentelemetry.api.OpenTelemetry not initialized yet: io_opentelemetry_api_OpenTelemetry_4087e2c748253198bc7b05f31387f3f4492f0131
2024-11-18T09:50:31.9197326Z 	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
2024-11-18T09:50:31.9199293Z 	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
2024-11-18T09:50:31.9201263Z 	at io.opentelemetry.api.OpenTelemetry_Le6zQbzkojAYO_OiKIQWJf4lGa4_Synthetic_Bean.createSynthetic(Unknown Source)
2024-11-18T09:50:31.9202364Z 	... 26 more
```

**Comment by mkouba** [comment]
@gsmet Have you tried to annotate the `LogHandlerProcessor#build()` method with `@Consume(SyntheticBeansRuntimeInitBuildItem.class)` as suggested by the error message?

**Comment by gsmet** [comment]
Yeah, that's what I was trying to do and we're back to square one:

```
Caused by: io.quarkus.builder.ChainBuildException: Cycle detected:
                   io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevUIProcessor#produceProviderComponent produced class io.quarkus.arc.deployment.SyntheticBeanBuildItem
                to io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime produced class io.quarkus.arc.deployment.SyntheticBeansRuntimeInitBuildItem
                to io.quarkus.opentelemetry.deployment.logging.LogHandlerProcessor#build produced class io.quarkus.deployment.builditem.LogHandlerBuildItem
                to io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit produced class io.quarkus.deployment.logging.LoggingSetupBuildItem
                to io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer produced class io.quarkus.devservices.keycloak.KeycloakDevServicesConfigBuildItem
                to io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevUIProcessor#produceProviderComponent
```

**Comment by mkouba** [comment]
> Yeah, that's what I was trying to do and we're back to square one:

:facepalm: Ok, that makes sense. I'm running out of ideas.

**Pull request closed without merging**
