### PR TITLE
Reduce ambiguity around RegisterForReflection's defaults

### PR DESCRIPTION
**Pull request by zakkak**
Motivated by https://github.com/quarkusio/quarkus/pull/24474#issuecomment-1916343312

### CODE REVIEW

**Comment by zakkak** [comment]
Changing `ignoreNested`'s default could indeed be an acceptable trade-off. I don't expect classes to have a large number of nested classes (as a result the impact is expected to be insignificant), and for those that do there is always the option to change the default.

cc @geoand

**Review by geoand — APPROVED** [review]

**Comment by zakkak** [comment]
@geoand thanks for the review. Do you have any comments regarding changing the default for `ignoreNested` https://github.com/quarkusio/quarkus/pull/38496#issuecomment-1918814617?

**Comment by zakkak** [comment]
@humcqc would you like to create a PR changing the default and the corresponding documentation?

**Comment by humcqc** [comment]
> @humcqc would you like to create a PR changing the default and the corresponding documentation?

will do after this one: https://github.com/quarkusio/quarkus/pull/36594

**Pull request merged**
