### PR TITLE
Vert.x Event Bus Codec Management

### LINKED ISSUE #265: using-vertx QS throws error in native mode
using-vertx QS throws error in native mode, app boots, tests are passing ...
run command: `mvn clean verify -Dnative` 

Main message:
Cannot instantiate the MessageCodec class io.quarkus.vertx.runtime.GenericMessageCodec: java.lang.InstantiationException: Type `io.quarkus.vertx.runtime.GenericMessageCodec` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
 
Stacktrace:
```
Executing [/Users/rsvoboda/git/quarkus-quickstarts/using-vertx/target/using-vertx-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2019-08-29 13:10:52,269 ERROR [io.qua.ver.run.VertxRecorder] (main) Cannot instantiate the MessageCodec class io.quarkus.vertx.runtime.GenericMessageCodec: java.lang.InstantiationException: Type `io.quarkus.vertx.runtime.GenericMessageCodec` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
    at java.lang.Class.newInstance(DynamicHub.java:770)
    at io.quarkus.vertx.runtime.VertxRecorder.registerCodec(VertxRecorder.java:342)
    at io.quarkus.vertx.runtime.VertxRecorder.registerCodecs(VertxRecorder.java:335)
    at io.quarkus.vertx.runtime.VertxRecorder.configureVertx(VertxRecorder.java:52)
    at io.quarkus.deployment.steps.VertxProcessor$build15.deploy_0(VertxProcessor$build15.zig:196)
    at io.quarkus.deployment.steps.VertxProcessor$build15.deploy(VertxProcessor$build15.zig:36)
    at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:165)
    at io.quarkus.runtime.Application.start(Application.java:91)
    at io.quarkus.runtime.Application.run(Application.java:204)
    at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)

2019-08-29 13:10:52,272 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.015s. Listening on: http://0.0.0.0:8081
2019-08-29 13:10:52,272 INFO  [io.quarkus] (main) Installed features: [cdi, reactive-pg-client, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-reactive-streams-operators, vertx, vertx-web]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.882 s - in org.acme.vertx.JsonEndpointIT
[INFO] Running org.acme.vertx.NativeFruitsEndpointIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.acme.vertx.NativeFruitsEndpointIT
[INFO] Running org.acme.vertx.GreetingResourceIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.acme.vertx.GreetingResourceIT
[INFO] Running org.acme.vertx.ResourceUsingWebClientIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.acme.vertx.ResourceUsingWebClientIT
[INFO] Running org.acme.vertx.EventResourceIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.352 s - in org.acme.vertx.EventResourceIT
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
```

### PR DESCRIPTION
**Pull request by cescoffier**
Fix https://github.com/quarkusio/quarkus-quickstarts/issues/265

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Review by rsvoboda — APPROVED** [review]
```
$ target/using-vertx-1.0-SNAPSHOT-runner
2019-08-29 15:51:14,257 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.009s. Listening on: http://0.0.0.0:8080
2019-08-29 15:51:14,258 INFO  [io.quarkus] (main) Installed features: [cdi, reactive-pg-client, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-reactive-streams-operators, vertx, vertx-web]
^C2019-08-29 15:51:29,184 INFO  [io.quarkus] (main) Quarkus stopped in 0.002s
```

**Comment by gsmet** [comment]
There was a failure in something that looks totally unrelated. Trying again.

**Comment by FroMage** [comment]
Some tests failed again, rerunning.

**Comment by geoand** [comment]
And again

**Comment by FroMage** [comment]
CI is really touchy, these days. The failure does seem unrelated, but can you please rebase @cescoffier  to make sure?

**Comment by cescoffier** [comment]
I'm redevelopping completely the codec management. The current content is not correct.

**Comment by cescoffier** [comment]
@FroMage the CI is what picked my curiosity and start looking into it... the generic codec uses Serialization...

**Comment by FroMage** [comment]
Well, CI passes and 2 reviews, merging.

**Pull request merged**
