### PR TITLE
Remove devconsole-spi from core

### PR DESCRIPTION
**Pull request by phillip-kruger**
@gsmet the classes in the spi module is already deprecated. This PR remove all usage from core.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Seems like we still need to ignore the test. I assume it used to pull in the dev-console-spi as transitive dependency. Or I can add those to the quickstart

**Comment by phillip-kruger** [comment]
Waiting on https://github.com/quarkusio/quarkus-quickstarts/pull/1320

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
@phillip-kruger I might be missing something, but should be something added to the migration guide?
Thing is: I tried Quarkus 3.4.0.CR1 and I got `ClassNotFoundException: io.quarkus.devconsole.spi.DevConsoleTemplateInfoBuildItem`.
Turns out quarkus-cxf needs to add `quarkus-vertx-http-dev-console-spi` to fix this.

**Comment by gsmet** [comment]
@famod we will reintroduce the dependency in 3.4. We didn't think it would break so many extensions. @phillip-kruger will create a PR soon.

**Comment by famod** [comment]
@gsmet ah, good to know. Is this just a short-term remedy? Meaning: Does it make sense to add it explicitly in quarkus-cxf regardless?

**Comment by gsmet** [comment]
No, it doesn't make sense: Quarkus CXF should get rid of using these classes as it's the old Dev Console and it's gone.

It's not the only extension affected.
The plan is to drop this in 3.5 and communicate in advance so that extensions can adapt to this change.

So we want this change to be done but we didn't communicate well enough about it, that's why we are reverting it temporarily.

**Pull request merged**
