### PR TITLE
Fixed testRegistryClientJsonConfig by comparing maps

### PR DESCRIPTION
**Pull request by RugvedB**
Created this PR to fix 1 flaky test - [testRegistryClientJsonConfig](https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/registry-client/src/test/java/io/quarkus/registry/config/DevToolsConfigSerializationTest.java#L324)
--------------
1. **How were these test identified as flaky?**
This test was identified as flaky by using an open-source research tool named [NonDex](https://github.com/TestingResearchIllinois/NonDex) which is responsible for finding and diagnosing non-deterministic runtime exceptions in Java programs.

2. **What was the error?**
The test reads from files and stores it in String format in `expectedContents` and `actualContents` variables. By the time, the value is stored in these string variables, the order of keys may get shuffled i.e the order of keys is non-deterministic. Thus, when we compare this String variables expectedContents and actualContents, it may fail sometimes because the order of keys could be different in the string representation. One of the error logs has been pasted below where you can see that the keys "disabled" and "artifact" have got shuffled. 
```
[ERROR] Failures: 
[ERROR]   DevToolsConfigSerializationTest.testRegistryClientJsonConfig:349 
expected: 
  "{
    "descriptor" : {
      "artifact" : "registry.quarkus.test:quarkus-registry-descriptor::json:1.0-SNAPSHOT"
    },
    "platforms" : {
      "artifact" : "registry.quarkus.test:quarkus-platforms::json:1.0-SNAPSHOT",
      "extension-catalogs-included" : true
    },
    "non-platform-extensions" : {
      "disabled" : true,
      "artifact" : "registry.quarkus.test:quarkus-non-platform-extensions::json:1.0-SNAPSHOT"
    }
  }"
 but was: 
  "{
    "descriptor" : {
      "artifact" : "registry.quarkus.test:quarkus-registry-descriptor::json:1.0-SNAPSHOT"
    },
    "platforms" : {
      "artifact" : "registry.quarkus.test:quarkus-platforms::json:1.0-SNAPSHOT",
      "extension-catalogs-included" : true
    },
    "non-platform-extensions" : {
      "artifact" : "registry.quarkus.test:quarkus-non-platform-extensions::json:1.0-SNAPSHOT",
      "disabled" : true
    }
  }"

```
3. **What is the fix?**
Instead of comparing json strings, we can convert json strings to Map and then compare the maps. This PR proposes to compare Maps instead of json strings in the test. 

--------------
You can run the following commands to run the test using NonDex tool:
```
mvn -pl independent-projects/tools/registry-client edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=io.quarkus.registry.config.DevToolsConfigSerializationTest#testRegistryClientJsonConfig
```

Test Environment:
```
java version 11.0.19
Apache Maven 3.9.5
```
Kindly let me know if this fix is acceptable.
Thank you

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks. That's a good catch.

Another option could be to write the JSON in a fully deterministic way when serialized. If we are using Jackson, there are options for that IIRC. I think that would have my preference.

**Comment by RugvedB** [comment]
> Thanks. That's a good catch.
> 
> Another option could be to write the JSON in a fully deterministic way when serialized. If we are using Jackson, there are options for that IIRC. I think that would have my preference.

Thank you for your reply. I want to make sure I modify the solution correctly and such that it satisfies all the requirements. Can you please elaborate further? Should I change at the root cause (which may be in actual codebase) or should the change remain in the test only? Thanks for your time.

**Comment by gsmet** [comment]
@RugvedB I was thinking of making sure the data is always serialized in the same order at the source. I think it would be more beneficial.

Not very familiar with this area but @gastaldi can probably point you where we write this thing.

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gastaldi** [comment]
I created https://github.com/quarkusio/quarkus/pull/37541 which should give a deterministic order when serializing Map entries

**Pull request closed without merging**
