### PR TITLE
Compress JSON and XHTML media types by default

### LINKED ISSUE #41094: Vert.x Http: application/json MIME not compressed by default
### Describe the bug

As discovered in #40750

`application/json` and `application/xhtml+xml` MIMEs are not compressed by default.

See [HttpBuildTimeConfig.java](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpBuildTimeConfig.java#L97).

@mkouba, was there a specific reason for not including it? It seems in the log that you originated it in https://github.com/quarkusio/quarkus/commit/670a205d3870a517001a53006d46ac08c5cb5437

I left the default intact in #40750, merely documenting it.

### Expected behavior

Major MIME like `application/json` gets compressed.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.8.4, main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jponge**
Fixes #41094

### CODE REVIEW

**Comment by geoand** [comment]
I'm +0 on the original request, so I'll leave it up to @mkouba :)

**Comment by jponge** [comment]
I'm also on the fence TBH 😉 

Seems like there's no good reason to compress GraphQL JSON and not plain JSON by default, but there might be a reason why we aren't doing that.

**Comment by geoand** [comment]
👍🏽

**Comment by jponge** [comment]
Asking @gsmet, he might know

**Review by mkouba — APPROVED** [review]
Don't forget to add a note in the migration guide.

**Comment by gsmet** [comment]
I think it was just that we were conservative at first and that the GraphQL JSON one was added when GraphQL was implemented.

TBH, I have no idea what is the best practice in the field and if CPU costs more than bandwidth these days or the opposite. Because that's really what will make the decision in one way or the other.

Maybe something for which we could start a discussion on quarkus-dev.

**Comment by mkouba** [comment]
> TBH, I have no idea what is the best practice in the field and if CPU costs more than bandwidth these days or the opposite. Because that's really what will make the decision in one way or the other.

1. Keep in mind that this config property is only used if compression is enabled (and it's disabled by default).
2. I don't think there's a best/bad practice in this field. It's very individual. So I think if it's configurable then we're fine...

**Comment by melloware** [comment]
I think I was +1 because XHTML is what JSF/Faces uses for Quarkus Faces 👍🏻

**Comment by mschorsch** [comment]
+1

**Comment by gsmet** [comment]
> Keep in mind that this config property is only used if compression is enabled (and it's disabled by default).
> I don't think there's a best/bad practice in this field. It's very individual. So I think if it's configurable then we're fine...

Sure it still makes sense to try to have the best defaults possible though.
And I think it's probably best to compress JSON by default if compression is enabled, we will see how the community reacts to it.

**Comment by gsmet** [comment]
I let you folks make sure we have an entry here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.16 .

**Comment by mkouba** [comment]
FTR https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.16#http-compression

**Comment by jponge** [comment]
Thanks Martin!

**Pull request merged**
