### PR TITLE
Execute tests for neo4j by default

### PR DESCRIPTION
**Pull request by rsvoboda**
Execute tests for neo4j by default

Currently neo4j tests are not executed, including CI runs

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Hmmm, no, we don't want that. Our default build should not require Docker.

That's why it's done this way.

**Comment by rsvoboda** [comment]
I played with native run locally and it failed :(

Let's see what CI says about this

**Comment by gsmet** [comment]
Well, we need to run it on CI for sure.

**Comment by rsvoboda** [comment]
And neo4j in native mode fails on CI too, @michael-simons  fyi

```
2019-12-10T17:22:12.8145240Z 2019-12-10 17:22:12,810 INFO  [io.quarkus] (main) Installed features: [cdi, neo4j, resteasy, resteasy-jsonb, smallrye-health]
2019-12-10T17:22:13.9081262Z 2019-12-10 17:22:13,905 WARN  [ChannelErrorHandler] (Neo4jDriverIO-3-2) [0xf593c5b0][localhost:60513][] Fatal error occurred in the pipeline: org.neo4j.driver.internal.shaded.io.netty.handler.codec.DecoderException: Failed to read inbound message:
2019-12-10T17:22:13.9088669Z 70a2867365727665728b4e656f346a2f332e352e368d636f6e6e656374696f6e5f696486626f6c742d31
2019-12-10T17:22:13.9089433Z 
2019-12-10T17:22:13.9103746Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:87)
2019-12-10T17:22:13.9104472Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
2019-12-10T17:22:13.9111392Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2019-12-10T17:22:13.9111960Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9119813Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9120438Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:13.9128790Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:13.9129424Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:13.9140355Z 	at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
2019-12-10T17:22:13.9140947Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9157190Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9157750Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:13.9158378Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:13.9173772Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:13.9186792Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9187349Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9204041Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:13.9208743Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
2019-12-10T17:22:13.9218554Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9233431Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9234237Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
2019-12-10T17:22:13.9234799Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2019-12-10T17:22:13.9269801Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
2019-12-10T17:22:13.9270658Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
2019-12-10T17:22:13.9279508Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
2019-12-10T17:22:13.9280089Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
2019-12-10T17:22:13.9280494Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
2019-12-10T17:22:13.9293756Z 	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2019-12-10T17:22:13.9298865Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2019-12-10T17:22:13.9323346Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-10T17:22:13.9324027Z 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
2019-12-10T17:22:13.9324520Z 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
2019-12-10T17:22:13.9341405Z Caused by: org.neo4j.driver.internal.packstream.PackStream$Unexpected: Expected a struct, but got: ffffffb1
2019-12-10T17:22:13.9342101Z 	at org.neo4j.driver.internal.packstream.PackStream$Unpacker.unpackStructHeader(PackStream.java:421)
2019-12-10T17:22:13.9343188Z 	at org.neo4j.driver.internal.messaging.v1.ValueUnpackerV1.unpackStructHeader(ValueUnpackerV1.java:62)
2019-12-10T17:22:13.9355222Z 	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:51)
2019-12-10T17:22:13.9361078Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
2019-12-10T17:22:13.9361607Z 	... 31 more
2019-12-10T17:22:13.9362006Z 
2019-12-10T17:22:14.1436845Z 2019-12-10 17:22:14,141 WARN  [ChannelErrorHandler] (Neo4jDriverIO-3-1) [0x212a77c8][localhost:60513][] Fatal error occurred in the pipeline: org.neo4j.driver.internal.shaded.io.netty.handler.codec.DecoderException: Failed to read inbound message:
2019-12-10T17:22:14.1444730Z 70a2867365727665728b4e656f346a2f332e352e368d636f6e6e656374696f6e5f696486626f6c742d32
2019-12-10T17:22:14.1445390Z 
2019-12-10T17:22:14.1445910Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:87)
2019-12-10T17:22:14.1446538Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
2019-12-10T17:22:14.1447087Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2019-12-10T17:22:14.1449022Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1449524Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1455020Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:14.1455692Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:14.1470379Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:14.1477951Z 	at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
2019-12-10T17:22:14.1481279Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1485567Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1486256Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:14.1488240Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:14.1489965Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:14.1504501Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1513378Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1515236Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:14.1517998Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
2019-12-10T17:22:14.1520715Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1529101Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1532042Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
2019-12-10T17:22:14.1533846Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2019-12-10T17:22:14.1572936Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
2019-12-10T17:22:14.1573654Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
2019-12-10T17:22:14.1574185Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
2019-12-10T17:22:14.1574888Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
2019-12-10T17:22:14.1575450Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
2019-12-10T17:22:14.1576085Z 	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2019-12-10T17:22:14.1583176Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2019-12-10T17:22:14.1583874Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-10T17:22:14.1584352Z 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
2019-12-10T17:22:14.1620425Z 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
2019-12-10T17:22:14.1621016Z Caused by: org.neo4j.driver.internal.packstream.PackStream$Unexpected: Expected a struct, but got: ffffffb1
2019-12-10T17:22:14.1631143Z 	at org.neo4j.driver.internal.packstream.PackStream$Unpacker.unpackStructHeader(PackStream.java:421)
2019-12-10T17:22:14.1660811Z 	at org.neo4j.driver.internal.messaging.v1.ValueUnpackerV1.unpackStructHeader(ValueUnpackerV1.java:62)
2019-12-10T17:22:14.1661615Z 	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:51)
2019-12-10T17:22:14.1662851Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
2019-12-10T17:22:14.1667963Z 	... 31 more

```

**Comment by michael-simons** [comment]
I’ll check this days. Our final reactive driver has been out today. Is on my list. Thanks for the hint!

**Comment by rsvoboda** [comment]
https://github.com/neo4j/neo4j-java-driver/releases 4.0.0 is out, nice

I looked a bit into bump to 4.0.0-rc2 and there were some class name changes
```diff
+import org.neo4j.driver.Result;
-import org.neo4j.driver.StatementResult;

+import org.neo4j.driver.async.ResultCursor;
-import org.neo4j.driver.async.StatementResultCursor;

+import org.neo4j.driver.reactive.RxResult;
-import org.neo4j.driver.reactive.RxStatementResult;
```

This affects 
 - docs/src/main/asciidoc/neo4j.adoc
 - integration-tests/neo4j/src/main/java/io/quarkus/it/neo4j/Neo4jResource.java

**Comment by michael-simons** [comment]
@rsvoboda Yep, I'm fixing that atm. Also in the guide. We decided the new names are better, because they use the same wording like JDBC etc.

The output you have there, how did you end up with it?

**Comment by michael-simons** [comment]
Btw, are you on Gitter or something for a chat in any case?

**Comment by rsvoboda** [comment]
> The output you have there, how did you end up with it?

I copied it from CI run for this PR

Standard way would be `mvn clean install -Dtest-neo4j -Ddocker -Dnative` in integration-tests/neo4j (after building the master)
https://github.com/quarkusio/quarkus/blob/master/integration-tests/neo4j/README.md

**Comment by michael-simons** [comment]
Thanks. I have it failing locally as well. It worked on Quarkus 1.0. Meeeeh :/

**Comment by michael-simons** [comment]
I'm a bit out of knowledge here atm. 

When the beta03 driver went into Quarkus here: https://github.com/quarkusio/quarkus/commit/56f1ef65f9d9dd198d4ad992586445c948cf43d0

Everything worked, of course I did test native compilation.

**Comment by michael-simons** [comment]
Quarkus 1.0.1 works fine.

**Comment by gsmet** [comment]
So the real fix for the CI issue should be there: https://github.com/quarkusio/quarkus/blob/master/ci-templates/native-build-steps.yaml#L32 .

We need to start a Neo4j docker container and pass `-Dtest-neo4j` to the build.

**Comment by gsmet** [comment]
I'm closing this PR as it's not the right fix. I will open a new PR fixing CI.

I opened an issue for the Neo4j regression: https://github.com/quarkusio/quarkus/issues/6115 .

**Comment by gsmet** [comment]
Superseded by #6117 .

**Pull request closed without merging**
