### PR TITLE
Bump kubernetes-client-bom from 6.11.0 to 6.12.1

### PR DESCRIPTION
**Pull request by manusa**
Kubernetes Client 6.12.0 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.12.0
Kubernetes Client 6.12.1 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.12.1

/cc @metacosm

### CODE REVIEW

**Comment by gsmet** [comment]
Ping @metacosm :)

**Comment by metacosm** [comment]
Looks OK for us. Thank you!

**Comment by gastaldi** [comment]
Should it be backported to 3.8?

**Comment by manusa** [comment]
> Should it be backported to 3.10/3.8?

There shouldn't be any breaking changes in this new release. I guess backporting is safe, but @metacosm should be the one providing advice here.

**Comment by manusa** [comment]
The most important fix has to do with OpenID Connect and access to EKS clusters. Other than that, there isn't much more (for runtime mode).

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
