### PR TITLE
Bump kotlin version to 1.4.31

### LINKED ISSUE #11428: Setting the kotlin.version property to 1.4 doesn't update the Kotlin dependencies version
**Describe the bug**

Setting the kotlin.version property to 1.4 doesn't update the Kotlin dependencies version

**Expected behavior**

I expect that the Kotlin plugin's version, as well as the Kotlin dependencies' version, would be upgraded. 

**Actual behavior**

Only the plugin's version is upgraded. Compilation reports the following warning:

```
[WARNING] Runtime JAR files in the classpath have the version 1.3, which is older than the API version 1.4. Consider using the runtime of version 1.4, or pass '-api-version 1.3' explicitly to restrict the available APIs to the runtime of version 1.3. You can also pass '-language-version 1.3' instead, which will restrict not only the APIs to the specified version, but also the language features
```

**To Reproduce**

1.  `git clone https://github.com/hazelcast-demos/url-shortener`
2. Change the `<kotlin.version>` property from `1.3.72` to `1.4`
3. `mvn compile`

**Configuration**

N/A

**Screenshots**

N/A

**Environment (please complete the following information):**

N/A but filled in for the sake of completeness

 - Output of `uname -a` or `ver`:

    ````
    Darwin Nico 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
    ````

 - Output of `java -version`:

    ````
    openjdk version "1.8.0_252"
    OpenJDK Runtime Environment (build 1.8.0_252-b09)
    OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 25.252-b09-jvmci-20.1-b02, mixed mode)
    ````

 - GraalVM version (if different from Java): same
 - Quarkus version or git rev: `1.6.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

    ````
    Maven home: /Users/nico/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
    Java version: 14.0.2, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home
    Default locale: en_GB, platform encoding: UTF-8
    OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
    ````

### PR DESCRIPTION
**Pull request by evanchooly**
fixes #11428

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by aloubyansky — APPROVED** [review]
I didn't know it was duplicated. It should be set in one place. Can be done in a separate PR though.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Something is wrong with the Kubernetes tests... I need to check it out

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15426 fixes the CI issue

**Comment by geoand** [comment]
Can you rebase onto master please?

**Pull request merged**
