### PR TITLE
Work around oracle/graal#1971

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
This is a possible workaround for oracle/graal#1971 but it needs to be tested with the actual target test case, which I can't easily do today.  The issue is worked around by not caching methods during build in this first effort.

If my assumptions are incorrect and this causes a need for classes to register for reflection, then a different approach will be necessary.

/cc @gsmet @mkouba @lburgazzoli @olpaw

**Comment by olpaw** [comment]
IMO, that change just muddies the water. It does not change the fact that if `org.apache.camel.component.bean.BeanInfo.isValidMethod` is called anywhere it will cause `java.lang.reflect.Proxy` to become reflectively accessible. To fix the problem make `org.apache.camel.component.bean.BeanInfo` initialized at image runtime:
https://github.com/oracle/graal/blob/0dcde6c1b513a72ae30dbe2d6d00e237fde9542c/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeClassInitialization.java#L135

**Comment by dmlloyd** [comment]
I think it's OK for `Proxy` to be reflectively accessible.  And this solution is easier than making `BeanInfo` be runtime initialized only for JDK 8 IMO.  If this fixes the problem, we should move forward with it and we can explore more thorough solutions at another time.

**Comment by gsmet** [comment]
AFAICS, it doesn't fix the issue.

I still have:
```
Trace: 
	at parsing java.lang.reflect.Proxy.access$300(Proxy.java:228)
Call path from entry point to java.lang.reflect.Proxy.access$300(ClassLoader, String, byte[], int, int): 
	at java.lang.reflect.Proxy.access$300(Proxy.java:228)
	at com.oracle.svm.reflect.Proxy_access$300_c7f2160d72324f8fd5d02e2aa54a3c3562bea247_32.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.enterprise.util.AnnotationLiteral.invoke(AnnotationLiteral.java:288)
	at javax.enterprise.util.AnnotationLiteral.getMemberValue(AnnotationLiteral.java:276)
	at javax.enterprise.util.AnnotationLiteral.equals(AnnotationLiteral.java:198)
	at java.util.Hashtable.get(Hashtable.java:367)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:342)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
	... 7 more
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.reflect.Proxy.defineClass0(ClassLoader, String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:183)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:397)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:116)
	at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4168)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1548)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5170)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3286)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3093)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:977)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:871)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
```

with GraalVM 19.3.1-dev from this branch https://github.com/oracle/graal/tree/release/graal-vm/19.3 + JDK 8 + this PR.

**Comment by olpaw** [comment]
> I think it's OK for Proxy to be reflectively accessible.

It's not. Having `java.lang.reflect.Proxy` reflectively accessible makes `java.lang.reflect.Proxy.access$300` reachable from all `MethodAccessor.invoke` calls in your application. This unnecessarily increases your image size. In addition on Java 8 this causes unsupported native method `java.lang.reflect.Proxy.defineClass0` to become reachable (which is a deleted method) as well.

**Comment by mkouba** [comment]
I don't understand how this could fix the problem with static init of [`org.apache.camel.component.bean.BeanInfo.EXCLUDED_METHODS`](https://github.com/apache/camel/blob/afc6ed9c647e1920506065e26498932a4fb697cd/components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanInfo.java#L65)?

I believe that we should add the `@RecomputeFieldValue` to `org.apache.camel.component.bean.BeanInfo.EXCLUDED_METHODS` like  @christianwimmer described in https://github.com/oracle/graal/issues/1971#issuecomment-572724759.

**Comment by gsmet** [comment]
If you need patches to be tested, I have the full infrastructure set up so just ping me in the PR and I can run the tests.

**Comment by gsmet** [comment]
@mkouba would you be interested in working on that? We need a fix for that one for early next week.

**Comment by christianwimmer** [comment]
> I don't understand how this could fix the problem with static init of org.apache.camel.component.bean.BeanInfo.EXCLUDED_METHODS

When the class initializer of `BeanInfo` is executed at run time, then `EXCLUDED_METHODS` will only contain methods that are registered for reflection for any other reason. That is exactly what you want: if a method (like `Proxy.access$300`) is not registered for reflection, then the `Proxy.class.getDeclaredMethods()` in https://github.com/apache/camel/blob/afc6ed9c647e1920506065e26498932a4fb697cd/components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanInfo.java#L85 is not going to return that method. Having fewer (or even no) entries in `EXCLUDED_METHODS` is not a problem because it is used as a blacklist, i.e., if a method does not exist at all there is no need to filter that method.

**Comment by mkouba** [comment]
@christianwimmer yes, I understand. My question was related to this PR ;-).

In any case, this workaround seems to work: https://github.com/mkouba/camel-quarkus/commit/68c3c19306cabd434b55278b4ce4b55472567522. We'll need to modify the original `BeanInfo` though. I believe that if we skip synthetic methods we should be good...

**Comment by gsmet** [comment]
I incorporated a fix by @mkouba here: https://github.com/apache/camel-quarkus/pull/603

**Pull request closed without merging**
