### PR TITLE
Also add implemented interfaces in JAX-RS resources' @Typed

### PR DESCRIPTION
**Pull request by gsmet**
@mkouba we got a report of someone using interfaces to inject the JAX-RS resources elsewhere.

I don't have any details about the use case yet but I was wondering why we didn't add the implemented interfaces to the `@Typed` annotations? That would have looked natural to me.

Creating this PR so that we discuss it when you're back from PTO.

### CODE REVIEW

**Comment by gsmet** [comment]
Also @geoand I have no idea what RESTEasy Reactive does for this?

**Comment by geoand** [comment]
In RESTEasy Reactive, the resources are regular CDI beans, so anything that works for CDI, works for RR.

**Comment by mkouba** [comment]
@gsmet I don't remember TBH but it was something related to inheritance... if there are multiple resources implementing the same interface the build will fail with ambiguous dependency exception. Injecting JAX-RS resources is probably not a good idea anyway...

**Comment by gsmet** [comment]
OK, I provided a work around so let's leave it at that for now until we have more info about the use case.

Thanks!

**Pull request closed without merging**
