### PR TITLE
Document the Mutiny Vert.x context-aware scheduler helpers

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
The CI failure is most probably related.

**Comment by cescoffier** [comment]
Actually, it does not seem to be related:
```
2023-09-07T20:31:52.9728343Z ERROR: Unable to read generated file ../target/asciidoc/generated/config/quarkus-log-logging-log-config.adoc
2023-09-07T20:31:53.0219128Z ##[error]Exception in thread "main" java.io.UncheckedIOException: An error occurred while generating the downstream tree
2023-09-07T20:31:53.0341247Z 	at io.quarkus.docs.generation.AssembleDownstreamDocumentation.main(AssembleDownstreamDocumentation.java:189)
2023-09-07T20:31:53.0342385Z Caused by: java.nio.file.NoSuchFileException: ../target/asciidoc/generated/config/quarkus-log-logging-log-config.adoc
2023-09-07T20:31:53.0343001Z 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
2023-09-07T20:31:53.0344072Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2023-09-07T20:31:53.0344610Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
2023-09-07T20:31:53.0345199Z 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
2023-09-07T20:31:53.0345717Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
2023-09-07T20:31:53.0346157Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
2023-09-07T20:31:53.0346692Z 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
2023-09-07T20:31:53.0347210Z 	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
2023-09-07T20:31:53.0347661Z 	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2839)
2023-09-07T20:31:53.0348091Z 	at java.base/java.nio.file.Files.readAllLines(Files.java:3330)
2023-09-07T20:31:53.0348503Z 	at java.base/java.nio.file.Files.readAllLines(Files.java:3370)
2023-09-07T20:31:53.0349151Z 	at io.quarkus.docs.generation.AssembleDownstreamDocumentation.copyAsciidoc(AssembleDownstreamDocumentation.java:266)
2023-09-07T20:31:53.0349972Z 	at io.quarkus.docs.generation.AssembleDownstreamDocumentation.main(AssembleDownstreamDocumentation.java:167)
2023-09-07T20:31:53.0350503Z [ERROR] Command execution failed.
2023-09-07T20:31:53.0350914Z org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
2023-09-07T20:31:53.0351597Z     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
2023-09-07T20:31:53.0352265Z     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
2023-09-07T20:31:53.0352810Z     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
2023-09-07T20:31:53.0353349Z     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
2023-09-07T20:31:53.0353842Z     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
2023-09-07T20:31:53.0354277Z     at com.gradle.maven.cache.extension.d.c.a (SourceFile:27)
2023-09-07T20:31:53.0354711Z     at com.gradle.maven.cache.extension.d.n.a (SourceFile:23)
2023-09-07T20:31:53.0355130Z     at com.gradle.maven.cache.extension.d.h.a (SourceFile:28)
2023-09-07T20:31:53.0355548Z     at com.gradle.maven.cache.extension.d.m.a (SourceFile:27)
2023-09-07T20:31:53.0355972Z     at com.gradle.maven.cache.extension.d.a.c (SourceFile:115)
2023-09-07T20:31:53.0356401Z     at com.gradle.maven.cache.extension.d.a.a (SourceFile:61)
2023-09-07T20:31:53.0356807Z     at com.gradle.maven.cache.extension.d.e.a (SourceFile:27)
2023-09-07T20:31:53.0357233Z     at com.gradle.maven.cache.extension.d.l.a (SourceFile:17)
2023-09-07T20:31:53.0357647Z     at com.gradle.maven.cache.extension.d.d.a (SourceFile:42)
2023-09-07T20:31:53.0358061Z     at com.gradle.maven.cache.extension.d.b.a (SourceFile:26)
2023-09-07T20:31:53.0358485Z     at com.gradle.maven.cache.extension.d.f$1.run (SourceFile:35)
2023-09-07T20:31:53.0359019Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:29)
2023-09-07T20:31:53.0359631Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:26)
2023-09-07T20:31:53.0360251Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:66)
2023-09-07T20:31:53.0360871Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:59)
2023-09-07T20:31:53.0361517Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:157)
2023-09-07T20:31:53.0362340Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:59)
2023-09-07T20:31:53.0362993Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.run (SourceFile:47)
2023-09-07T20:31:53.0363529Z     at com.gradle.maven.cache.extension.d.f.a (SourceFile:31)
2023-09-07T20:31:53.0363937Z     at com.gradle.maven.cache.extension.d.k.a (SourceFile:67)
2023-09-07T20:31:53.0364553Z     at com.gradle.maven.cache.extension.h.b.lambda$createProxy$0 (SourceFile:79)
2023-09-07T20:31:53.0364989Z     at com.sun.proxy.$Proxy140.execute (Unknown Source)
2023-09-07T20:31:53.0365457Z     at com.gradle.maven.scan.extension.internal.d.a.executeMojo (SourceFile:114)
2023-09-07T20:31:53.0366065Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
2023-09-07T20:31:53.0366707Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
2023-09-07T20:31:53.0367305Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2023-09-07T20:31:53.0367909Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
2023-09-07T20:31:53.0368505Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
2023-09-07T20:31:53.0369218Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2023-09-07T20:31:53.0370028Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2023-09-07T20:31:53.0370905Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2023-09-07T20:31:53.0371718Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2023-09-07T20:31:53.0372336Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
2023-09-07T20:31:53.0372816Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:193)
2023-09-07T20:31:53.0373359Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:106)
2023-09-07T20:31:53.0373811Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:963)
2023-09-07T20:31:53.0374242Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:296)
2023-09-07T20:31:53.0374664Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:199)
2023-09-07T20:31:53.0375142Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2023-09-07T20:31:53.0375744Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2023-09-07T20:31:53.0376419Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2023-09-07T20:31:53.0376964Z     at java.lang.reflect.Method.invoke (Method.java:566)
2023-09-07T20:31:53.0377501Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2023-09-07T20:31:53.0378127Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2023-09-07T20:31:53.0378761Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2023-09-07T20:31:53.0379366Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2023-09-07T20:31:53.0379922Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2023-09-07T20:31:53.0380532Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2023-09-07T20:31:53.0381209Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2023-09-07T20:31:53.0381759Z     at java.lang.reflect.Method.invoke (Method.java:566)
2023-09-07T20:31:53.0382259Z     at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:52)
2023-09-07T20:31:53.0382837Z     at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:161)
2023-09-07T20:31:53.0383404Z     at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:73)
```

@geoand @gsmet any idea?

**Comment by geoand** [comment]
I think I saw it in the snapshot build failure, but I have no idea how it can be fixes - it may have to do with Gradle cache

**Comment by geoand** [comment]
I rebased the PR onto `main`, let's see what happens

**Comment by jponge** [comment]
Looks unrelated to that particular PR:

```
Sep 11, 2023 6:56:48 AM io.quarkus.docs.generation.AssembleDownstreamDocumentation main
ERROR: Unable to read generated file ../target/asciidoc/generated/config/quarkus-log-logging-log-config.adoc
Error: Exception in thread "main" java.io.UncheckedIOException: An error occurred while generating the downstream tree
	at io.quarkus.docs.generation.AssembleDownstreamDocumentation.main(AssembleDownstreamDocumentation.java:189)
Caused by: java.nio.file.NoSuchFileException: ../target/asciidoc/generated/config/quarkus-log-logging-log-config.adoc
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
```

**Comment by geoand** [comment]
@gsmet made some doc relates fixes lately, can you rebase to pick them up?

**Comment by jponge** [comment]
Done!

**Pull request merged**
