### PR TITLE
Upgrade Hibernate ORM to 5.6.14.Final and ByteBuddy to 1.12.18, add test for HHH-15634

### PR DESCRIPTION
**Pull request by yrodiere**
cc @gsmet

Creating as draft because the tests will fail until [HHH-15634](https://hibernate.atlassian.net/browse/HHH-15634) gets fixed and we upgrade our Hibernate ORM dependency.

This will be useful to test the patch that @dreab8 is currently working on for Hibernate ORM.

To launch the test, build Quarkus, then run:

```
mvn clean test -pl extensions/hibernate-orm/deployment -Dtest='LazyBasic*'
```

### CODE REVIEW

**Comment by Sanne** [comment]
Updated

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
Incorporated the ORM release; for detailed changes see https://in.relation.to/2022/11/03/hibernate-orm-5613/

**Review by Sanne — DISMISSED** [review]
Need to respin :(
 https://hibernate.atlassian.net/browse/HHH-15662

**Comment by Sanne** [comment]
Upgraded now to `5.6.14.Final` to fix the Envers releated failures.

**Review by gsmet — APPROVED** [review]

**Comment by Sanne** [comment]
That's looking much better. Thanks all!

**Pull request merged**
