### PR TITLE
Regenerate truststore for self-signed certificate case

### PR DESCRIPTION
**Pull request by geoand**
Fixes the broken snapshots seen at:
https://github.com/quarkusio/quarkus/issues/12111#issuecomment-940649990

### CODE REVIEW

**Comment by geoand** [comment]
@michalszynkiewicz can you take a look please? A lot of PRs are failing because of this

**Review by mkouba — APPROVED** [review]

**Comment by Ladicek** [comment]
In my opinion, it's best to let the build generate testing keystores/truststores, instead of committing them. There's a Maven plugin for keytool that can do that.

**Comment by gsmet** [comment]
@michalszynkiewicz could you have a look at what @Ladicek mentioned ^. Looks like something we need to fix.

**Comment by michalszynkiewicz** [comment]
I made myself a note to do this but don't know when I get to it...

**Comment by zakkak** [comment]
Hi, can we please get this backported on branch `2.2` as well?

We are seeing false negatives in the Mandrel CI without it:
* https://github.com/graalvm/mandrel/actions/runs/1437649796
* https://github.com/graalvm/mandrel/actions/runs/1437651596

Since we are testing the `2.2` branch and not the 2.2.x releases there is no need for a release to make the CI green, just getting the fix on `2.2` should be enough.

Thank you

**Comment by geoand** [comment]
Feel free to open a PR against `2.2` and I'll approve it

**Comment by rsvoboda** [comment]
@michalszynkiewicz did you look into automated keystores/truststores creation?

**Comment by michalszynkiewicz** [comment]
nope, I didn't have time for it yet

**Pull request merged**
