### PR TITLE
WebSocket Next: endpoint callback arguments injection

### LINKED ISSUE #39224: WebSockets Next: support method parameter injection
### Description

Once really handy feature of JAX-RS / Jakarta REST is that resource methods can have a set of well define parameters. 

We should introduce something similar to WebSockets next

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- supported arguments include `WebSocketConnection`, `HandshakeRequest` and
  path parameters - `String` annotated with `@io.quarkus.websockets.next.PathParam`
- resolves #39224

### CODE REVIEW

**Comment by Ladicek** [comment]
Looks reasonable, but I wonder if we aren't perhaps making this needlessly restrictive and complicated at the same time? I would expect that you could inject arbitrary CDI beans, and a `@PathParam` would be the only special case that would have to be handled extra. All the other supported parameters are CDI beans already, are they not?

(Also, it's sad that we don't have CDI 4.1 yet. I believe method invokers would make the implementation here quite a lot easier, and would considerably reduce the amount of bytecode generation we have to do here.)

**Comment by mkouba** [comment]
> Looks reasonable, but I wonder if we aren't perhaps making this needlessly restrictive and complicated at the same time? I would expect that you could inject arbitrary CDI beans, and a `@PathParam` would be the only special case that would have to be handled extra. All the other supported parameters are CDI beans already, are they not?

They are not. And some of them will never be (for example the decoded message).

I'm still not sure it's a good idea to make all other params CDI injection points. I mean it's possible but what's the benefit? In my opinion, the less method parameters the better. Not the other way around.

> (Also, it's sad that we don't have CDI 4.1 yet. I believe method invokers would make the implementation here quite a lot easier, and would considerably reduce the amount of bytecode generation we have to do here.)

I don't think that method invokers would considerably reduce the amount of bytecode generation here. The invocation itself is just a tiny part of the logic.

**Review by gastaldi — APPROVED** [review]

**Comment by Ladicek** [comment]
Ah, of course, I forgot about the message parameter. Yes, that of course is not a bean. The `@PathParam` is not a bean either. But the `WebSocketConnection` is, and the `HandshakeRequest` ... I'm not actually sure if that is a bean, but it could be IMHO.

**Comment by mkouba** [comment]
> and the `HandshakeRequest` ... I'm not actually sure if that is a bean, but it could be IMHO.

It isn't. It could be but I don't see a point. In fact, you can just `@Inject WebSocketConnection` and then use `WebSocketConnection#handshakeRequest()`... which is the same as we do for `@PathParam` with `WebSocketConnection#pathParam(String)`.

**Comment by mkouba** [comment]
In any case, we would still need some API for the special cases. So I believe that it's better to define a proper API that is flexible enough to handle all special cases (including CDI injection).

**Comment by geoand** [comment]
At the risk sounding like a broken record, I will emphasize my point of view again - trying to do what we've done in RESTEasy Reactive / Quarkus REST makes the API easier to learn.

Taking that into account, from my point of view we should support as many method parameters as possible as that is by far the easiest way for a user to get the objects needed for implementing their business functionality. 

> In any case, we would still need some API for the special cases. So I believe that it's better to define a proper API that is flexible enough to handle all special cases (including CDI injection).

I totally agree with this. Furthermore, it's something that can be iterated on

**Comment by mkouba** [comment]
> Furthermore, it's something that can be iterated on

:+1:

**Pull request merged**
