### PR TITLE
Support codestarts of extensions outside catalog

### LINKED ISSUE #21165: Support reading version metadata/codestart when adding extension with specific version
### Description

We should support reading metadata for the specified version when adding extension with specific version. 

It would also open the way to generate codestarts for local extension in devolopment.

ex (should use the extension metadata from  io.foo:quarkus-foo-bar:999-SNAPHOT) :
```
q ext add io.foo:quarkus-foo-bar:999-SNAPHOT
```

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fix #21165

This change adds support for codestarts referenced from extensions that are not included in the registry catalogs.

### CODE REVIEW

**Comment by geoand** [comment]
Can the second commit be renamed to have a better description?

Thanks

**Comment by aloubyansky** [comment]
Sure, I am testing the change. I think I'll need to adjust something more for the tests.

**Comment by aloubyansky** [comment]
@ia3andy it's good now

**Review by ia3andy — COMMENTED** [review]
It's pretty cool, I was able to create a project with a standalone extension which has a codestart (without any trick).

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -Dextensions=org.acme:aloha-code:1.0.0-SNAPSHOT
```

We can potentially use old incompatible codestarts. At some point it might be good to introduce some kind of devtools/codestarts compatibility rules.

**Review by ia3andy — APPROVED** [review]

**Pull request merged**
