### PR TITLE
Add the ability to auto generate Flyway migration

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This will be generated from the Hibernate schema with the press of a
button

Draft for now as it needs docs and tests

### CODE REVIEW

**Comment by geoand** [comment]
Very interesting idea!

**Comment by maxandersen** [comment]
I like it - one thing I would add is some text help on what the "create initial migration" actually does and whats the outcome. Maybe have modal dialog to accept creation:

"Creating initial migration setup basic files for Flyway migrations to work. If you say yes a initial file in db/migrations will be created and you can then add additional migration files as documented at ??" Yes/No

or maybe add a ## comment into the sql giving some hint on where users can get more info ?

**Comment by stuartwdouglas** [comment]
Adding a button is about the limit of my frontend skills. Let's look at improving this once it is in.

**Comment by stuartwdouglas** [comment]
@Sanne I have added some docs, but I am not really sure how to write a test without adding a test dependency on the hibernate module, which I know you have issues with.

**Comment by Sanne** [comment]
> @Sanne I have added some docs, but I am not really sure how to write a test without adding a test dependency on the hibernate module, which I know you have issues with.

Sorry allow me to clarify: in such cases it's perfectly reasonable and I have no problem with it. I was only asking to refrain from adding the dependency when not necessary (as I've seen that happening) but in this case there's clear good reasons to have such tests so no problem at all :)

**Comment by stuartwdouglas** [comment]
Test has been added, should be good to go now.

**Review by gsmet — APPROVED** [review]
I rebased and added a commit with some small doc adjustments. Let's get this in, maybe @phillip-kruger can have a look at the UI improvements that were suggested when he has time.

**Comment by phillip-kruger** [comment]
@gsmet Great ! I'll have a look as soon as possible.

**Pull request merged**
