### PR TITLE
Generate the command for default base image that requires it

### LINKED ISSUE #29451: OpenShift deployment don't generate command when arguments are provided
### Describe the bug

When `quarkus.openshift.arguments` are provided, first one is used as command is not generated. I think the behavior was introduced by https://github.com/quarkusio/quarkus/pull/27733, but the PR description says _The command may still be generated if the user provides arguments without command._

### Expected behavior

One of:
- Behavior is same as in 2.12 - command is generated.
- Documentation correct my expectation; https://quarkus.io/guides/deploying-to-openshift#generating-job-resources does not explain behavior.
- Build fails as no command has been specified.

### Actual behavior

Container fails to start as first argument is used to start the app.

_Error: container create failed: time="2022-11-23T15:50:25Z" level=error msg="runc create failed: unable to start container process: exec: \"ARG1\": executable file not found in $PATH"_

### How to Reproduce?

Reproducer:

0. OC - logged in
1. `quarkus create app org.acme:openshift-quickstart \
    --extension='resteasy-reactive,openshift'`
2. `cd openshift-quickstart`
3. `quarkus build -Dquarkus.kubernetes.deploy=true -Dquarkus.kubernetes-client.trust-certs=true -Dquarkus.openshift.arguments="ARG1,ARG2" -Dquarkus.platform.version=2.13.0.Final -DskipTests -DskipITs` (NOTE: same happens when you use `-Dnative`)
5. `oc get pod`

Alternatively:
1. `git clone https://github.com/quarkus-qe/quarkus-test-suite.git`
2. `cd quarkus-test-suite/lifecycle-application`
3. `mvn clean verify -Dopenshift -Dit.test=OpenShiftLifecycleApplicationIT` (NOTE: same happens when you use `-Dnative`)
4. `oc get pod`

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### GraalVM version (if different from Java)

GraalVM CE 22.3.0

### Quarkus version or git rev

2.13.0 +, 2.14, 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

_No response_

### LINKED ISSUE #29642: I am not able to set `QUARKUS_OPTS` on my Openshift dpeloyment
### Describe the bug

I am experimenting an `java.lang.OutOfMemoryError: Array allocation too large` on a native application on OpenShift and could be related to the default Quarkus application memory settings

On Applicaiton Starts
```
17:03:02,390 INFO  [app] [app-1-zp2cj-app] QUARKUS_OPTS environment variable was not set, using default values of -Xmx24M -Xms16M -Xmn24M
17:03:02,391 INFO  [app] __  ____  __  _____   ___  __ ____  ______ 
17:03:02,391 INFO  [app]  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
17:03:02,391 INFO  [app]  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
17:03:02,391 INFO  [app] --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
17:03:02,391 INFO  [app] 16:03:00,751 jaxrs-reactive 1.0.0-SNAPSHOT native (powered by Quarkus 999-SNAPSHOT) started in 0.019s. Listening on: http://0.0.0.0:8080
17:03:02,391 INFO  [app] 16:03:00,755 Profile prod activated. 
17:03:02,392 INFO  [app] 16:03:00,755 Installed features: [cdi, rest-client-reactive, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
17:03:08,283 INFO  [app] Service started (Quarkus NATIVE mode)

``` 
More in detail:
`QUARKUS_OPTS environment variable was not set, using default values of -Xmx24M -Xms16M -Xmn24M`

When I try to set my own values through this documented property `quarkus.openshift.env.vars`, seems that doesn't have any impact (any effect):

Example:
Application.properties
```
quarkus.openshift.env.vars.QUARKUS_OPTS="-Xmx2024M -Xms80M -Xmn120M"
```

OpenShift.yaml
```
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: "QUARKUS_HOME"
            value: "/home/quarkus/"
          - name: "QUARKUS_OPTS"
            value: ""
          - name: "JAVA_APP_JAR"
            value: "/deployments/jaxrs-reactive-1.0.0-SNAPSHOT-runner"
```

So the issue is, that I am not able to set my own "QUARKUS_OPTS". 

### Expected behavior

An Openshift.yaml with the user QUARKUS_OPTS. 

### Actual behavior

Empty QUARKUS_OPTS.

### How to Reproduce?

`git clone --branch feat/compresion_biffiles git@github.com:pjgg/quarkus-test-suite.git`
`cd quarkus-test-suite/http/jaxrs-reactive`
`mvn clean verify -Dnative -Dopenshift -Dit.test=OpenShiftExecutionModelIT#bigCompression`

and in the middle time an Openshift.yaml will be generated on `/quarkus-test-suite/http/jaxrs-reactive/target/OpenShiftExecutionModelIT/app/openshift.yml`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
The default base image for OpenShift s2i builds: ubi8/openjdk-11 or ubi8/openjdk-17 needs the Java command when there are arguments. Therefore, let's generate always the command when using these images (the old ubi8 and ubi9 images) and also in Native mode. 

Fix https://github.com/quarkusio/quarkus/issues/29451

These changes are also related to https://github.com/quarkusio/quarkus/issues/29642, so for known base images, we won't be providing the JAVA_OPTS property when there are no jvm arguments. 
 
Fix https://github.com/quarkusio/quarkus/issues/29642

### CODE REVIEW

**Comment by Sgitario** [comment]
> We've decided against this approach as part of #24885.
> 
> The main reason was that the resuling behavior was too complex to explain and in addtion it created false expectations.
> 
> See #24885: at some point the enum went out of sync for native images resulting in situation that was pretty complex to understand.
> 
> If we are to tumble back to the old behavior, I would like additional input (@geoand @maxandersen wdyt?) and also clear documentation explaining what we do for each image and full test coverage.

We're not always generated the command, but only when we know that the base image needs it (and the default base image needs it when arguments are set). The root cause is that [the default base image](https://github.com/jboss-container-images/openjdk) is using the first java argument as the java command which as far I see, it's wrong (but according to some tests, they do it on purpose). 

Therefore, without these changes, we force users to set the command ("java -jar ...") when they want to simply provide the java arguments. For me, this is an issue that we should have detected before doing https://github.com/quarkusio/quarkus/issues/24885.

However, if the default base image is addressed to not use the first argument as Java command, we could get rid of these changes.

**Review by michalvavrik — COMMENTED** [review]
For what is it worth, I like this solution. Thank you for fixing my issue. IMO you should document the behavior, because 

- now there will be different behavior for known images like `ubi9/openjdk-17`, `ubi9/openjdk-11` and unknown ones
- if I define args and unknown image, I'll get still get first argument used as command, right? That's something that could be detected as argument shouldn't be used as command, you could throw configuration exception

**Comment by Sgitario** [comment]
Let me reply inline:

> For what is it worth, I like this solution. Thank you for fixing my issue. IMO you should document the behavior, because
> 
> * now there will be different behavior for known images like `ubi9/openjdk-17`, `ubi9/openjdk-11` and unknown ones

There is a different behavior for all known images. That's the purpose of the enum where I added these new images. The idea is to offer the same user experience regardless the image the user uses (if we know something about the image, of course).

> * if I define args and unknown image, I'll get still get first argument used as command, right? That's something that could be detected as argument shouldn't be used as command, you could throw configuration exception

This is not correct. The first argument is an issue of only the ubi8 and ubi9 images. And also, this is not something we can prevent because, in terms of manifest generation, the result is correct.

**Comment by Sgitario** [comment]
@iocanel could you take a look into this issue, please? At the moment, without these changes, when one user provides at least one argument, the deployment will fail.

**Comment by maxandersen** [comment]
Maybe I'm missing something but this feels Like we will keep digging and making it harder and harder for users to manage their configuration and just as hard to document what will be the actual behavior. 

The underlying issue is that images has these varied ways to run but I feel it's not helping we are trying to shoehorn every image into being the same. 

I don't have a solution as is but think we should really consider our options before we keep adding special image treatments. 

I *think* I might like it if there was a "strategy" setting users could choose but which was set based on image. Then users can chose if they want the magic or not and also wouldn't need to wait on core adding treatment for specific base image ?

Thoughts?

**Comment by Sgitario** [comment]
> Maybe I'm missing something but this feels Like we will keep digging and making it harder and harder for users to manage their configuration and just as hard to document what will be the actual behavior.
> 
> The underlying issue is that images has these varied ways to run but I feel it's not helping we are trying to shoehorn every image into being the same.
> 
> I don't have a solution as is but think we should really consider our options before we keep adding special image treatments.
> 
> I _think_ I might like it if there was a "strategy" setting users could choose but which was set based on image. Then users can chose if they want the magic or not and also wouldn't need to wait on core adding treatment for specific base image ?
> 
> Thoughts?

I don't think this is getting more and more complicated:
- If a user provides the command and/or the arguments, this will be respected. 
- If a user provides the arguments only, this is also respected. (With this PR, we ensure that Quarkus will work as expected using the default base image - the UBI one)

Note that the image treatment is not something new that has been shipped as part of this pull request, but a mechanism that was already in place and used for other images to ensure common behavior regardless of the base image the user sets). So, this pull request basically fixes the following issue:

> when one user provides at least one argument, the deployment will fail.

About looking at strategies to prevent image treatments at all, I think we should use our own images as default. Images we know and we maintain. However, I think this is out of scope for this issue.

**Comment by michalvavrik** [comment]
> Maybe I'm missing something but this feels Like we will keep digging and making it harder and harder for users to manage their configuration and just as hard to document what will be the actual behavior.

Actual behavior is not documented anyway (not after this PR, not before this PR). If you looked at the steps to reproduce of the issue I opened https://github.com/quarkusio/quarkus/issues/29451, I believe you would not find these steps groundless unless docs correct my expectation.

**Comment by iocanel** [comment]
> Actual behavior is not documented anyway (not after this PR, not before this PR). If you looked at the steps to reproduce of the issue I opened #29451, I believe you would not find these steps groundless unless docs correct my expectation.

The current behavior is straight forward and consistent all across the board that does not need a special reference to the documentation (apart from migration related details).

**Comment by Sgitario** [comment]
> > Actual behavior is not documented anyway (not after this PR, not before this PR). If you looked at the steps to reproduce of the issue I opened #29451, I believe you would not find these steps groundless unless docs correct my expectation.
> 
> The current behavior is straight forward and consistent all across the board that does not need a special reference to the documentation (apart from migration related details).

The current behavior is buggy because when providing the Java arguments, the application will not work.

**Comment by gsmet** [comment]
IIUC the issue, I'm weighing with @Sgitario here. My only concern is: do we have a way to actually detect if this behavior is changed in a new version of the image? Because I suspect, we will just copy/paste things when adding a new version and I wonder if we would easily catch a change in behavior?

Also, won't it break existing setups (I mean setups where users hacked their way to make it work)?

**Comment by Sgitario** [comment]
> IIUC the issue, I'm weighing with @Sgitario here. My only concern is: do we have a way to actually detect if this behavior is changed in a new version of the image? Because I suspect, we will just copy/paste things when adding a new version and I wonder if we would easily catch a change in behavior?
> 
> Also, won't it break existing setups (I mean setups where users hacked their way to make it work)?

When using the default image and users set only the arguments, if we also include the command, we're safe here. But I agree with you that we should include this use case in our K8s tests so that we can detect issues beforehand. 

Moreover, I think it would make sense to open an issue in the OpenJDK image repository and watch this issue to revert these changes if they decide to fix/change this odd behavior (I mean that OpenJDK image should never use the first argument as command when the command is not set).

**Comment by iocanel** [comment]
> IIUC the issue, I'm weighing with @Sgitario here. My only concern is: do we have a way to actually detect if this behavior is changed in a new version of the image? Because I suspect, we will just copy/paste things when adding a new version and I wonder if we would easily catch a change in behavior?

Not sure if the image has changed behavior from version to version, but I do know that we have changed image completely and he gone out of sync. If we are to maintain such feature we need to somehow ensure that things won't get out of sync.

> Also, won't it break existing setups (I mean setups where users hacked their way to make it work)?

The breaking change has already happened. Restoring the `magic` most probably wont break anyone, but I strongly advocate against it.

Why?

It sounds simple when you think about `default images` but when you break down `default images` into the corresponding 
modes: `jvm` / `native`,  builders (e.g. `docker`, `openshift`, `jib` and `buildpack`) and deployment targets, things get **TOO** complicated.
So, yeah we could get smarter when using the default `s2i` images to deploy to Openshift, but what about images built using `docker`? Or external images?

**Comment by michalvavrik** [comment]
I tried to set `quarkus.openshift.command` to `java -jar /deployments/quarkus-run.jar` but that don't help. What am I supposed to use if this PR doesn't get in, please?

**Comment by rsvoboda** [comment]
@iocanel are there any plans with this PR / to fix https://github.com/quarkusio/quarkus/issues/29451 and https://github.com/quarkusio/quarkus/issues/29642?

**Comment by rsvoboda** [comment]
@maxandersen / @iocanel / @cescoffier / @geoand 

Are there any plans with this PR?  To fix https://github.com/quarkusio/quarkus/issues/29451 and https://github.com/quarkusio/quarkus/issues/29642?

**Comment by cescoffier** [comment]
@rsvoboda i'm discovering this issue. I agree that the current approach is not great. However, I'm wondering if we should not just use run-java in JVM mode. 

Doing the java -jar your self is rarely great.

**Comment by rsvoboda** [comment]
IMHO OpenShift/Kubernetes extensions should have more eyes attached to them. I think these extensions need to be polished and some design decisions need to be taken or revisited to have several questions and issues concluded. Also I think that more things should be documented in docs and not just in the code.

About the issues I mentioned in my comment:

**Issue https://github.com/quarkusio/quarkus/issues/29451** 
This issue is more about definition of expected behavior when `quarkus.openshift.arguments` are provided.
It's going to be one year old soon.
>  These images seem to use the first argument when provided on purpose. Though I think this is wrong, let's workaround it by providing the command.

I think I don't have the full insights to say if it's a good step or not. Or to say if the path proposed in Clement's comment should be followed.


**Issue https://github.com/quarkusio/quarkus/issues/29642** 
This issue is interesting one, focuses on QUARKUS_OPTS but triggers other concerns for native image - see https://github.com/quarkusio/quarkus/issues/29642#issuecomment-1341169893 by Ioannis, about `nativeArguments` vs. `QUARKUS_OPTS`.

https://github.com/quarkusio/quarkus/issues/29642#issuecomment-1341644852 shows that `quarkus.openshift.env.vars.quarkus-opts=-Xmx2024M -Xms80M -Xmn120M` does the job for the primary concern of the issue.
But there is **no example of `quarkus.openshift.env.vars.quarkus-opts` usage in Quarkus docs.**
How can possible users find out about it? (Guillaume also complained hard time setting `QUARKUS_OPTS`)


**kubernetes vs. openshift configuration note**
When playing with `quarkus.openshift.env.vars.quarkus-opts=-Xmx2024M -Xms80M -Xmn120M` I checked also generated `kubernetes.yml` and it had no jvm setup.
I had to add `quarkus.kubernetes.env.vars.quarkus-opts=-Xmx2024M -Xms80M -Xmn120M` to have the same content in related sections.

My concerns:
 - I was using `quarkus-openshift` extension, so why is kubernetes.(yml|json) generated if I should care just about openshift ones?
 - If kubernetes.(yml|json) are intended to be generate, shouldn't be `quarkus.openshift.*` configuration reflected in them too? OpenShift is built on top of Kubernetes and it would be good if `quarkus.openshift.*` configuration gets applied in kube descriptors (with some exceptions for known differences) 
   - Motivation: I want to support both OCP and Kube with my app, why do I need to duplicate the config for `quarkus.openshift.*` and `quarkus.kubernetes.*` ?

**Comment by fedinskiy** [comment]
@cescoffier are there any news regarding this fix?

**Comment by cescoffier** [comment]
No, I was not even aware of this.

**Comment by gsmet** [comment]
Closing for lack of activity.

**Pull request closed without merging**
