### PR TITLE
Disable Vert.x file caching when building the k8s client HttpClient.Factory

### PR DESCRIPTION
**Pull request by geoand**
Relates to: https://github.com/quarkusio/quarkus/issues/32499#issuecomment-1500829471

### CODE REVIEW

**Comment by geoand** [comment]
cc @manusa @vietj

**Comment by gsmet** [comment]
Not sure about the implications here but isn't the root cause the fact that the temporary files are created in `c:/windows/`? That looks extremely wrong.

**Comment by geoand** [comment]
It is (and I don't know why), but why deal with it when we don't need handle anything file system related in this case?

**Review by Sgitario — APPROVED** [review]
Agreed!

**Pull request merged**
