### PR TITLE
Bump artemis-jms to 2.10.0

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
Seem like the change isn't enough:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ quarkus-integration-test-artemis-jms ---
[WARNING] 
Dependency convergence error for org.apache.activemq:artemis-commons:2.9.0 paths to dependency are:
+-io.quarkus:quarkus-integration-test-artemis-jms:999-SNAPSHOT
  +-io.quarkus:quarkus-artemis-jms:999-SNAPSHOT
    +-io.quarkus:quarkus-artemis-core:999-SNAPSHOT
      +-org.apache.activemq:artemis-core-client:2.10.0
        +-org.apache.activemq:artemis-commons:2.9.0
and
+-io.quarkus:quarkus-integration-test-artemis-jms:999-SNAPSHOT
  +-io.quarkus:quarkus-artemis-jms:999-SNAPSHOT
    +-org.apache.activemq:artemis-jms-client:2.10.0
      +-org.apache.activemq:artemis-selector:2.9.0
        +-org.apache.activemq:artemis-commons:2.10.0
and
+-io.quarkus:quarkus-integration-test-artemis-jms:999-SNAPSHOT
  +-org.apache.activemq:artemis-server:2.9.0
    +-org.apache.activemq:artemis-commons:2.9.0
and
+-io.quarkus:quarkus-integration-test-artemis-jms:999-SNAPSHOT
  +-org.apache.activemq:artemis-server:2.9.0
    +-org.apache.activemq:artemis-journal:2.9.0
      +-org.apache.activemq:artemis-commons:2.9.0
and
+-io.quarkus:quarkus-integration-test-artemis-jms:999-SNAPSHOT
  +-org.apache.activemq:artemis-server:2.9.0
    +-org.apache.activemq:artemis-jdbc-store:2.9.0
      +-org.apache.activemq:artemis-commons:2.9.0

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

**Comment by gastaldi** [comment]
@geoand oops, forgot to change in `build-parent`. Done

**Comment by geoand** [comment]
@gsmet is there any specific reason we have the artemis version in both places?

**Comment by gastaldi** [comment]
The artemis-server used in the integration-tests isn't declared in the runtime BOM (not sure why), perhaps @middagj may explain?

**Comment by middagj** [comment]
The server is only used in the integration tests to test the client. I took Kafka as an example, there this is also the case.

**Pull request merged**
