### PR TITLE
Added filter and other updates to config screen in Dev UI

### LINKED ISSUE #15196: Dev UI config editor with filtering capabilities
**Description**
The Config Editor in the Dev UI has no built-in possibility to filter for entries.

**Implementation ideas**
Could be similar to the one in the [All-Config Guide](https://quarkus.io/guides/all-config).

It would be helpful that after a value is updated and the page reloaded, the filter is still active.

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR updates the config properties screen in Dev UI.

Fix #15196

Here the changes:

- Changed the sub header (of all screens) to be in the nav bar header (space saving)
- Added a way for extension pages to add javascript
- Added a search/filter bar for the config properties
- Changed the order of the config properties to first show properties from `application.properties` and then other Quarkus properties and moved `System` and `Environment` to the bottom, the logic here is that the developer would probably change properties in `application.properties` and other Quarkus properties (rather than a system property like `awt.toolkit` that is currently showing at the top)
- Changed the default value to be a tool-tip to the input-box, rather than a column (space saving)
- Changed the information about what config source this comes from to a tool-tip next to the config key (because does that really matter ?) (space saving)
- Changed the Update button, that is currently a separate button in a table col to be next to the input-box (space saving)
- Added a Key listener to the inputbox to allow using Enter as a submit
- Made sure the columns wrap as to not make the table bigger than the view-port (horizontal scroll)
- Changed the form submit, that currently reloads the page to a Javascript POST. Better user experience to not reload the page and loose the state. This is also nice if you have the log open for instance.

Screen before:
old_config

Screen after:
new_config

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by gsmet** [comment]
There is a conflict now.

Small gripe: I think I would rather have a small space between the search engine and the table rather than having the two attached.

Other than that, it looks very promising!

**Comment by geoand** [comment]
Simply judging by the screenshot, it looks great!

But I'll take a closer look tomorrow

**Comment by phillip-kruger** [comment]
@gsmet - cool, I can add a space there. Let me look at that and this conflict.
Thanks :)

**Comment by radcortez** [comment]
That looks great :)

**Review by geoand — APPROVED** [review]
This is a great improvement!

My one suggestion is to document how extension pages can add javascript

**Comment by phillip-kruger** [comment]
@geoand - Thanks, yes I am happy to update the documentation, it's really 'inline' so similar to style. I'll look into that.

**Comment by geoand** [comment]
Not really sure what happened, but it looks like something went wrong during the rebase

**Comment by phillip-kruger** [comment]
Yup. I screwed up the squash :(
Busy fixing. Sorry

**Comment by geoand** [comment]
No worries and no rush to fix :)

**Comment by phillip-kruger** [comment]
Ok reverted the squash. 

- I resolved the conflict
- I added a space between the filter bar and the table (see screenshot below)
- I added some documentation

I'll try the squash again if everyone is happy.

Let me know.

config_space_added

**Comment by phillip-kruger** [comment]
Ok, I am giving up on squashing this mess. Closing here. I'll open a new PR.

**Pull request closed without merging**
