### PR TITLE
Ensure the Quarkus HTTP Client Factory is always used by Kubernetes Client

### LINKED ISSUE #32937: Warning: Multiple httpclient implementation in the classpath
### Describe the bug

I wanted to upgrade one of our applications from Quarkus 2.16.6.Final to Quarkus 3.0.1.Final. The application starts but as soon as I use the Kubernetes client I get the following warning and exception in the console:

> 2023-04-27 07:48:35,213 WARN  [io.fab.kub.cli.uti.HttpClientUtils] (vert.x-eventloop-thread-2) There are multiple httpclient implementation in the classpath, choosing the first non-default implementation. You should exclude dependencies that aren't needed or use an explicit association of the HttpClient.Factory.

```bash
2023-04-27 07:48:35,213 WARN  [io.fab.kub.cli.uti.HttpClientUtils] (vert.x-eventloop-thread-2) There are multiple httpclient implementation in the classpath, choosing the first non-default implementation. You should exclude dependencies that aren't needed or use an explicit association of the HttpClient.Factory.
2023-04-27 07:48:50,331 ERROR [de.bvu.tra.tim.htt.ExceptionMappers] (vert.x-eventloop-thread-2) An error has occurred.: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:551)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:424)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:392)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:93)
        at com.example.services.InstanceService.findDeployments(InstanceService.kt:105)
        at com.example.services.InstanceService.findApps(InstanceService.kt:86)
        at com.example.services.InstanceService_ClientProxy.findApps(Unknown Source)
        at com.example.http.MainResource.getIndexPage(MainResource.kt:87)
        at com.example.http.MainResource_Subclass.getIndexPage$$superforward(Unknown Source)
        at com.example.http.MainResource_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:74)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:100)
        at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:27)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:71)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:63)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_RolesAllowedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:38)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:26)
        at com.example.http.MainResource_Subclass.getIndexPage(Unknown Source)
        at com.example.http.MainResource_ClientProxy.getIndexPage(Unknown Source)
        at com.example.http.MainResource$quarkusrestinvoker$getIndexPage_2ced74d2fee37c4b83002c0f48a53b817892c857.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:290)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:528)
        ... 50 more
```

I guess the exception is due to the warning that there are multiple HTTP clients on the classpath?

Maven dependencies:
```xml
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-qute</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-config-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>kotlin-extensions</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.cronutils</groupId>
            <artifactId>cron-utils</artifactId>
        </dependency>
    </dependencies>
```

I don't currently have a reproducer, but maybe someone has an idea?

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/32937

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by Sgitario** [comment]
@geoand if the Quarkus HTTP Client Factory is the one that our Kubernetes Client instance must use, why not force the httpClientFactory to always use it? 

Note that this will disable the ServiceLoader logic to find any other.

**Comment by geoand** [comment]
That's up for debate actually - cc @metacosm.

**Comment by geoand** [comment]
So let's wait and see what other think

**Comment by Sgitario** [comment]
> Which issue is this suppose to address? Regarding whether or not the factory should be used all the time, I don't know for sure. We still want people to be able to use a different http client implementation if they need to. That said, they could just provide their own Kubernetes client provider, configuring the client as they want so maybe that's fine.

https://github.com/quarkusio/quarkus/issues/32937 is the issue we're trying to fix.
Basically, https://github.com/Sgitario/quarkus/blob/34264c28e3ac64dadd67cb5fbe3cb37feafe8d97/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java#L94 seems to not be working for DEV mode.

**Comment by geoand** [comment]
> Basically, https://github.com/Sgitario/quarkus/blob/34264c28e3ac64dadd67cb5fbe3cb37feafe8d97/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java#L94 seems to not be working for DEV mode.

This is what we need to figure out before anything else

**Comment by geoand** [comment]
Actually, it probably does work as expected, but my guess is that the client that is created at build time is causing the issue.

In that case, we migjht want to limit disabling Service Discovery **only** to that client

**Comment by Sgitario** [comment]
> Actually, it probably does work as expected, but my guess is that the client that is created at build time is causing the issue.
> 

Do you mean the one we created to deploy into OpenShift [[1](https://github.com/quarkusio/quarkus/blob/2c6c42bba6d19a8d65f7a7b3a627b23d3d1e7270/extensions/kubernetes-client/deployment-internal/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientBuildStep.java#L20)]? If so, I don't think you're right. We have disabled the Service Discovery for this client already.

**Comment by geoand** [comment]
Yeah I never tried it, just wondering.

**Comment by Sgitario** [comment]
> > Basically, https://github.com/Sgitario/quarkus/blob/34264c28e3ac64dadd67cb5fbe3cb37feafe8d97/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java#L94 seems to not be working for DEV mode.
> 
> This is what we need to figure out before anything else

I would like to help with this. Though, if the Quarkus HTTP Client Factory is meant to always be used here, the simplest solution is this one. 

Yet if you want me to investigate why RemovedResourceBuildItem does not work in DEV mode, I would need some pointers to know where to start looking into as I have no idea.

**Comment by geoand** [comment]
> Yet if you want me to investigate why RemovedResourceBuildItem does not work in DEV mode, I would need some pointers to know where to start looking into as I have no idea.

I won't have time for this for the next 10 days or so (same goes for others who are familiar with this part of the code).
If you want to start looking, you should look into `ClassTransformingBuildStep` which uses the build item in question in order to build the transformed classes.

For a starting point for dev-mode, look into `IsolatedDevModeMain#firstStart`

**Comment by Sgitario** [comment]
> 

I've just confirmed that DEV mode is not consuming the `RemovedResourceBuildItem` build items at all. 

Honestly, I don't see how DEV mode is meant to consume these build items, so I won't be helpful here. Anyway, I'm closing this pull request as the suggested solution seems not to be valid.

**Comment by metacosm** [comment]
The warning will be improved in the next version of the fabric8 client and yes, it shows up because the Kubernetes client extension adds an additional factory, we should indeed try to mute the warning in the case where there's only the original vert.x factory and the one that the extension creates. I'll take a look.

**Pull request closed without merging**
