### PR TITLE
WIP: Make Filters Clickable, open Filters in the IDE

### PR DESCRIPTION
**Pull request by saumya1singh**
@FroMage @geoand

### CODE REVIEW

**Comment by geoand** [comment]
Hm.... Have you tried it?

Asking because the filters that are a result of using `@ServerRequestFilter` and `@ServerResponseFilter` definitely won't be working properly.

**Comment by SaumyaSingh1** [comment]
Ah, I forgot to mention, for the `open in IDE` features because of the `permission denied` problem I am not able to test the code.

**Comment by geoand** [comment]
I do have in mind to be able to support this properly in the future - but for now it would introduce too many false positives

**Comment by geoand** [comment]
I'm going to close this because this needs a lot more support on the RESTEasy Reactive side of things

**Pull request closed without merging**
