### PR TITLE
Docs: generate index.yaml with title + preamble

### PR DESCRIPTION
**Pull request by ebullient**
I would like to remove/reduce the amount of manual maintenance for the quarkus website (jekyll based). We can use this generated data alongside other hand-tended information, but I'll toss this out as a preliminary.

This utility generates an `index.yaml` file that contains the file url, title, and preamble (first paragraph) for all of the source asciidoc files in the docs directory. Output looks like this (based on current asciidoc content, which does not have the best preambles):

```yaml
groups:
  reference:
    name: Reference
    id: reference
    docs:
    - title: Reactive Messaging AMQP 1.0 Connector Reference Documentation
      filename: amqp-reference.adoc
      description: This guide is the companion from the Getting Started with AMQP
        1.0. It explains in more details the configuration and usage of the AMQP connector
        for reactive messaging.
    - title: Contexts and Dependency Injection
      filename: cdi-reference.adoc
      description: "Quarkus DI solution (also called ArC) is based on the Contexts\
        \ and Dependency Injection for Java 2.0 specification. However, it is not\
        \ a full CDI implementation verified by the TCK. Only a subset of the CDI\
        \ features is implemented - see also the list of supported features and the\
        \ list of limitations."
    - title: Class Loading Reference
      filename: class-loading-reference.adoc
      description: This document explains the Quarkus class loading architecture.
        It is intended for extension authors and advanced users who want to understand
        exactly how Quarkus works.
```

It also produces an `errors.yaml` file: 

```yaml
empty-preamble:
- faq.adoc
- maven-tooling.adoc
- lra.adoc
- resteasy.adoc
- reaugmentation.adoc
- gradle-tooling.adoc
- redis-reference.adoc
- security-customization.adoc
- security-openid-connect-providers.adoc
- config-extending-support.adoc
```

This checks for missing/empty preambles, missing section ids (that don't match expectations) and missing keywords (unless we decide to remove this).

## Questions: 

- Should we use a single-sentence document attribute (summary or something) instead of the preamble? I'd rather see this as encouragement to keep the preambles short and to the point.
- Keywords in the docs or not? (should categories shift with new design to orient around keywords as tags?)

### CODE REVIEW

**Comment by ebullient** [comment]
@maxandersen

**Comment by maxandersen** [comment]
like the idea of the "errrors.yaml" to incrementally migrate to new structure without having to boil the ocean.

On the questions:

```Should we use a single-sentence document attribute (summary or something) instead of the preamble? I'd rather see this as an encouragement to keep the preambles short and to the point.```

I initially thought it would be awesome just picking up preamble but then i realized the description is mainly(?) used on https://quarkus.io/guides/ where I think the preambles will be too long. Even if they are short and to the point.
How about look for summary attribute and use it if present and otherwise get preamble so don't force adding two "summaries" if one is enough ?

    ```Keywords in the docs or not? (should categories shift with new design to orient around keywords as tags?)```

That i'm not sure about - in beginning it was nice just be able to add keywords to the central file to get it show up the right places but I' struggling to see why not just have it in the docs file?

**Comment by ebullient** [comment]
I updated the tool to check for summary (and then fall back to preamble), but test for / require the preamble anyway (as we do want it to be present consistently).

I think we should defer the keyword question to a subsequent item, once we think about update to the website a bit more.

**Review by FroMage — APPROVED** [review]
Looks like a great idea!

**Pull request merged**
