### PR TITLE
Upgrade to maven-compiler-plugin 3.11.0

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky interested in your opinion on this: we were still using Maven Compiler Plugin 3.8.1 to compile Quarkus.

**Comment by aloubyansky** [comment]
Sounds like a good idea

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand did you end up moving to Windows in the end? From what I could understand, I think the error is due to some invalid character in the report but the error message is very cryptic and I have no idea where it could come from.

It might be a regression in a Maven plugin but it's hard to know.

```
2023-03-07T22:57:03.5409484Z     at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)
2023-03-07T22:57:03.5409759Z Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
2023-03-07T22:57:03.5410025Z     at java.nio.charset.CoderResult.throwException (CoderResult.java:275)
2023-03-07T22:57:03.5410259Z     at sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:307)
2023-03-07T22:57:03.5411185Z     at sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:282)
2023-03-07T22:57:03.5411499Z     at sun.nio.cs.StreamEncoder.write (StreamEncoder.java:132)
2023-03-07T22:57:03.5411736Z     at java.io.OutputStreamWriter.write (OutputStreamWriter.java:205)
2023-03-07T22:57:03.5411966Z     at java.io.BufferedWriter.flushBuffer (BufferedWriter.java:120)
2023-03-07T22:57:03.5412177Z     at java.io.BufferedWriter.write (BufferedWriter.java:233)
2023-03-07T22:57:03.5412345Z     at java.io.Writer.write (Writer.java:249)
2023-03-07T22:57:03.5412633Z     at org.apache.maven.shared.utils.io.FileUtils.fileWriteArray (FileUtils.java:460)
2023-03-07T22:57:03.5412918Z     at org.apache.maven.shared.utils.io.FileUtils.fileWriteArray (FileUtils.java:437)
2023-03-07T22:57:03.5413322Z     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.computeInputFileTreeChanges (AbstractCompilerMojo.java:1704)
2023-03-07T22:57:03.5414023Z     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:858)
2023-03-07T22:57:03.5414359Z     at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:199)
```

From what I can see, the failure is here: https://github.com/apache/maven-compiler-plugin/blob/master/src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java#L1704 .

Do we have a file in the tree with a special character?

**Comment by geoand** [comment]
> @geoand did you end up moving to Windows in the end

Nope, not yet

**Comment by geoand** [comment]
Maybe @Karm who recently built on a new Windows installation can help

**Comment by gsmet** [comment]
@jorsol oh, good catch! Will fix that and see how it goes!

**Comment by gsmet** [comment]
@jorsol yeah, I actually did the mistake but fixed it right away. Things should be all good now.

**Pull request merged**
