### PR TITLE
Dev mode test fixes

### PR DESCRIPTION
**Pull request by stuartwdouglas**
The test was including the wrong classes, so no file modification actually happened.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
This seems to be occurring consistently:

```
2020-04-17T06:22:15.6627309Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.689 s <<< FAILURE! - in io.quarkus.smallrye.reactivemessaging.amqp.devmode.AmqpDevModeTest
2020-04-17T06:22:15.6632065Z [ERROR] testCodeUpdate  Time elapsed: 1.221 s  <<< ERROR!
```

**Comment by gsmet** [comment]
This is the error:
```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.smallrye.reactivemessaging.amqp.ConsumingBean and qualifiers [@Default]
	- java member: io.quarkus.smallrye.reactivemessaging.amqp.TestResource#bean
	- declared on CLASS bean [types=[io.quarkus.smallrye.reactivemessaging.amqp.TestResource, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.smallrye.reactivemessaging.amqp.TestResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:973)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:240)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:135)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:358)
```

**Comment by cescoffier** [comment]
Yes, the beans have been removed (should use different class names...)

**Comment by gsmet** [comment]
@cescoffier could you adjust the PR and make things less confusing?

**Comment by cescoffier** [comment]
@gsmet I will rebase first as the switch to durable messages is changing the test already.

**Comment by cescoffier** [comment]
Let's see what the CI says!

@stuartwdouglas I force-pushed, so...

**Comment by cescoffier** [comment]
Can't work, hitting the missing ALPN provider on Java 8

**Comment by geoand** [comment]
Please rebase PR onto the latest master in order to pick up a CI fix

**Comment by cescoffier** [comment]
Rebase done.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
