### PR TITLE
Fix #9309: Quarkus/Undertow does not parse request parameters correctly from multipart post

### LINKED ISSUE #9309: Quarkus/Undertow does not parse request parameters correctly from multipart post
**Describe the bug**
We tried to setup a PrimeFaces FileUpload with the new MyFaces Quarkus Extension but the post is not correctly considered as postback in JSF as the underlying HttpServletRequest doesnt have any post params.
I tested it and it works fine on jetty.

**Expected behavior**
HttpSevletRequest also parses post params from the multipart request

**Actual behavior**
empty request params

**To Reproduce**
1. Build MyFaces (git clone https://github.com/apache/myfaces/  and  mvn clean install -DskipTests)
2. Run the Showcase (https://github.com/apache/myfaces/tree/master/extensions/quarkus/showcase): mvn compile quarkus:dev -Ddebug
3. Open localhost:8080/file.xhtml
4. Select a file in the second / simple exmaple and use the styled or not styled button to submit it
5. if you check the post in the browser tools, it's a multipart and correclty contains the javax.faces.ViewState param
6. Now debug HtmlResponseStateManager#isPostback and you will see that the underlying HttpServletRequest doesnt have ANY request params

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by mgorniew**
Fixes #9309

### CODE REVIEW

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
I don't really like this approach. ServletBuildItem is eventually a programatic way to register servlets, so it should also support setting the Multipart config directly. 

In general servlets added in this manner will not be in the Jandex index, so the annotation information will not be present anyway (if they are in the index then you can just use @WebServlet, making this build item unnecessary).

Can you modify this PR to add Mutlipart config to ServletBuildItem so it can be configured programatically?

**Comment by mgorniew** [comment]
@stuartwdouglas Sure. I can add multipart config to ServletBuildItem. But should we also keep annotation processing for this build item? 

In #9309 I see that Apache MyFaces does create Jandex, but they don't annotate FacesServlet with @WebServlet. Maybe they don't want to create explicit dependency on Quarkus in core. 

User can also extensions may use IndexDependencyBuildItem for dependencies. Should we ignore `@MultipartConfig` in such case?

**Comment by stuartwdouglas** [comment]
I think just programatic is fine for now, I don't really like the mixed approach, as it is unclear what to do if the build item has different values to the annotations.

**Comment by gsmet** [comment]
@stuartwdouglas can you rereview?

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
