### PR TITLE
Upgrade Infinispan to 12.1.4.Final

### PR DESCRIPTION
**Pull request by karesti**
upgrade latest stable

### CODE REVIEW

**Comment by gsmet** [comment]
Please make the title clear when you create a PR. The fact that it is an upgrade for Infinispan is important. I fixed it.

**Comment by gsmet** [comment]
@karesti looks like the test failure is related to the upgrade ^

**Comment by karesti** [comment]
@gsmet weird ...

**Comment by karesti** [comment]
@gsmet I passed both jvm and native tests locally before submitting the PR, i'm surprised. I upgraded protostream as well for the final version. I'll check it all

**Comment by karesti** [comment]
@gsmet ok for some reason I did not see this failing locally but now I am. Keep you posted about the native failure and thanks for the heads up

**Comment by karesti** [comment]
@gsmet all tests are ok

**Comment by gastaldi** [comment]
Looks good, but it needs to be rebased before we merge this 😉

**Review by gsmet — APPROVED** [review]
Rebased, let's wait for CI again.

**Comment by gsmet** [comment]
@mkouba @radcortez the test above is failing quite regularly ^

**Comment by karesti** [comment]
@gsmet thanks for the rebase

**Comment by radcortez** [comment]
Hum... seems very similar to the failure in https://github.com/quarkusio/quarkus/pull/17991. I don't believe in coincidences, so something is definitely suspicious here. Did you notice if this only happens on Windows?

**Comment by gsmet** [comment]
@radcortez I have no idea. What I know is that the Windows CI machines are usually a bit slower than the others.

**Pull request merged**
