### PR TITLE
Replaced deprecated Config phase BOOTSTRAP in Kubernetes

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by geoand** [comment]
@radcortez any chance you break up the change to the kubernete-client and kubernetes-config modules into separate commits?

**Comment by radcortez** [comment]
Separate commits in the same PR you mean? Or do you prefer to have separate PRs?

**Comment by geoand** [comment]
Same PR is fine

**Comment by radcortez** [comment]
Ok, let me see what I can do.

**Comment by geoand** [comment]
Sorry for nitpicking, but could you fix the description of the commit for the kubernetes-client, as the commit just changes to ConfigMapping (the is no Bootstrap phase for the kubernetes-client) extension.

**Comment by geoand** [comment]
Also cc, @metacosm as this might break the JOSDK

**Comment by radcortez** [comment]
> Sorry for nitpicking, but could you fix the description of the commit for the kubernetes-client, as the commit just changes to ConfigMapping (the is no Bootstrap phase for the kubernetes-client) extension.

Sure. No worries.

**Review by geoand — APPROVED** [review]

**Comment by metacosm** [comment]
Can I get a TL,DR; description of what this does and what purpose this serves, as well to how things are potentially affected downstream, please?

**Comment by geoand** [comment]
What you care about is that `KubernetesClientBuildConfig` and `KubernetesDevServicesBuildTimeConfig` are now interfaces

**Comment by metacosm** [comment]
Ok, where could I learn more about why this change was made? In particular, is it something that people are now expected to do in their own extensions (as opposed to having public fields on config classes)?

**Comment by geoand** [comment]
> Ok, where could I learn more about why this change was made?

@radcortez ^

> In particular, is it something that people are now expected to do in their own extensions (as opposed to having public fields on config classes)?

Yes, but there is no rush.

**Comment by radcortez** [comment]
> Ok, where could I learn more about why this change was made?

Certainly. Here is something that I wrote about the Class vs Interface approach:
https://github.com/jakartaee/config/discussions/122

Also, there are some additional reasons for Quarkus:
- The old class / ConfigRoot approach works exclusively for Quarkus extensions, meaning that application developers had to use a different mechanism. The new interface approach works for both extensions and applications
- The old mechanism was built around the Config system, which complicated a few things (for instance, the config classes would only be available at a certain point in the runtime). The new system is built inside the Config system, so they are immediately available once Config is up.

**Comment by metacosm** [comment]
Thanks for the info, @radcortez!

**Pull request merged**
