### PR TITLE
[Docs] security-oidc-auth0-tutorial.adoc improvements

### PR DESCRIPTION
**Pull request by rolfedh**
…tutorial.adoc

Purpose: [Docs] Final edits, QE and publishing prep work: security-oidc-auth0-tutorial.adoc as described in [QDOCS-534](https://issues.redhat.com/browse/QDOCS-534)

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi Rolfe, just to make sure there is no confusion, this is not about the OIDC authentication in general, it is there to help an Auth0 https://auth0.com/ users, while RHBQ customers will be getting Keycloak, this tutorial has my name all over it :-), I'm not sure it is ready for the downstream inclusion yet...

**Comment by sberyozkin** [comment]
Thanks @rolfedh for these edits, I'll have a look tomorrow, this PR will be good to go in, but I'm not sure yet about #36905

**Comment by sberyozkin** [comment]
I apologize in advance if these edits won't have effect on the product docs :-), we'll discuss #36905

**Comment by rolfedh** [comment]
@sberyozkin I hear you are might be working on this file now. I made some preliminary edits here, but expect that the underlying content might change significantly. Let's connect later today.

**Comment by rolfedh** [comment]
No worries, @sberyozkin. Thanks.

**Comment by sberyozkin** [comment]
Hey @rolfedh, I'd not like to lose the fixes you have made to this file, I'll have a look soon, at the very least they will make it upstream :-), this is what I meant, they will be applied, but may not end up in the product if the doc itself is not pushed down to the product, thanks

**Review by sberyozkin — APPROVED** [review]
Thanks for the fixes, Rolfe

**Pull request merged**
