### PR TITLE
Revert test serializer changes to avoid regressing existing use cases

### LINKED ISSUE #94: [CI] - Pact + Quarkus main
This issue will be opened and closed depending on the state of https://github.com/quarkiverse/quarkus-pact build against Quarkus main SNAPSHOT.

If you are interested in being notified, please subscribe to this issue.

### LINKED ISSUE #40770: JUnit TestTemplate tests are not re-run on code change in dev mode
### Describe the bug

I spotted two issues with `@TestTemplate` and dev mode, while adding tests to improve our coverage in this area. 

*Problem 1:* Changing a file covered by a templated test does not trigger a re-run of the templated test. 

*Problem 2:* Failures in templated tests seem to be under-counted; in my test, when things pass, there are two passes, but when things fail, there's only one failure. (I'll confirm the behaviour in normal mode.)

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

The disabled `testThatChangesTriggerRerunsOfJUnitTestTemplates` test in `DevMojoIT` reproduces the problem. (PR incoming.)

It's also possible to reproduce manually. 

1. Run the maven tests (this just does the substitutions in the test projects): `mvn -f integration-tests/maven -Dtest=DevMojoIT clean verify`
2. In one terminal, run the test application `cd integration-tests/maven/target/test-classes/projects/test-template-processed && quarkus dev`. It should report two tests passing. 
3. In a separate window, edit the java file for the generated test project: `vi integration-tests/maven/target/test-classes/projects/test-template-processed/src/main/java/org/acme/HelloResource.java`. Change "hello" to something else. 
4. Notice that the tests do not re-run. This is bad. 
5. If you quit quarkus and then re-run `quarkus dev`, you'll get failure (which is good), but only one (which is unexpected). 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by holly-cummins**
This reverts #40601, to fix https://github.com/quarkiverse/quarkiverse/issues/94. 
As part of the same changeset, I’ve also disabled a test that #40601 caused to pass (https://github.com/quarkusio/quarkus/pull/40749), and enabled a test that #40601 makes fail (https://github.com/quarkusio/quarkus/pull/40773). 

Why is this a change we'd want, if it makes stuff fail? IMO, the stuff it makes pass is more important than the stuff it makes fail. The test which this PR now causes to fail has never passed, but the test which it gets to pass is reasonably widely used in the field. We don't want to regress it. How bad is the regression? Anything involving a Pact provider won’t work without this change. We should, IMO, favour ‘avoiding regressions’ over ‘enabling new functionality’. If 3.12 ships with a regression, that’s embarrassing, and if it has a regression that we actually knew about and decided we didn't care about, that’s something that will affect user trust in us.

Does this mean that #40601 isn’t a good change? No! It's an *awesome* change. This is a *temporary* reversion, just until https://github.com/junit-team/junit5/pull/3820 makes it into a JUnit release. Think of it as a delay to function we definitely want, not a reversion. :) 

This PR should be reverted as soon as we have a release of JUnit with https://github.com/junit-team/junit5/pull/3820 in it. I’ve split the PR into two parts; we only want to revert 8e7f808de43a47b30969e6d7e1440d0840222130, because hopefully the test enabled by other commit will continue passing. Once/if this merges, I'll open another PR with the reversion of the reversion (!), to make sure we don't forget. 

There’s a fuller discussion of the arguments for and against this change on https://github.com/quarkusio/quarkus/pull/40751 (which is an alternate solution to get these use cases passing). 

cc @dmlloyd @geoand @gsmet @edeandrea

### CODE REVIEW

**Review by dmlloyd — APPROVED** [review]
🥲

**Comment by geoand** [comment]
😭

**Comment by holly-cummins** [comment]
I got confused by my towering stack of disabled tests and test-related issues, and enabled the wrong test. Hopefully fixed now. :)

**Review by gsmet — APPROVED** [review]
I agree.

Let's monitor JUnit releases so that we can push it back as soon as we have a fix for the issue in JUnit.

**Comment by holly-cummins** [comment]
I've raised https://github.com/quarkusio/quarkus/pull/40906 so we don't lose track of getting #40601 back in. We obviously can't merge it yet for all sorts of reasons, but it's there, with the right code changes for serialization. 

@edeandrea, you can re-enable the superheroes tests now.  🥳

**Comment by edeandrea** [comment]
Done!

https://github.com/quarkusio/quarkus-super-heroes/commit/d12cf5eaa88b876812f05dfdae893fbd53f0788b

**Comment by geoand** [comment]
We now have JUnit `5.10.3` in `main` which includes David's fix, so I pressume we can bring #40601 back

**Comment by holly-cummins** [comment]
> We now have JUnit `5.10.3` in `main` which includes David's fix, so I pressume we can bring #40601 back

That's https://github.com/quarkusio/quarkus/pull/40906, although we have a failure in the 'fails with #40601' test that needs investigation.

**Pull request merged**
