### PR TITLE
Delete elasticsearch-high-level-rest-client extension and upgrade dev-services and tests to Elasticsearch 8

### LINKED ISSUE #29523: ElasticsearchDevServicesBuildTimeConfig uses elasticsearch:7.17.0, newer versions are available
### Describe the bug

ElasticsearchDevServicesBuildTimeConfig uses elasticsearch:7.17.0, newer versions are available

https://github.com/quarkusio/quarkus/blame/main/extensions/elasticsearch-rest-client-common/deployment/src/main/java/io/quarkus/elasticsearch/restclient/common/deployment/ElasticsearchDevServicesBuildTimeConfig.java#L32

https://hub.docker.com/_/elasticsearch - `8.5.1` and `7.17.7` are available

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #31960: Elasticsearch Dev Services gives `Operation not permitted` on startup when using Podman
### Describe the bug

When starting up a app that uses elasticsearch dev services I get:

`chroot: cannot change root directory to '/': Operation not permitted`

I am using podman, not sure if that is the issue. 

### Expected behavior

Elasticsearch should start

### Actual behavior

It does not

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux pkruger-laptop 6.1.18-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Mar 11 16:09:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/Maven/apache-maven-3.8.5
Java version: 17.0.6, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "6.1.18-200.fc37.x86_64", arch: "amd64", family: "unix"

### Additional information

Output of `docker -v` is:
`podman version 4.4.2`

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #29523
Fixes #31960

Co-authored by @phillip-kruger 

Creating as draft since we need an upgrade to Hibernate Search 6.2 (not yet released) in order to get official compatibility with ES 8.

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]

**Comment by yrodiere** [comment]
We've upgraded to Hibernate Search 6.2, so we can upgrade to ES 8.8 safely now (there won't be any warnings in the logs about HSearch not supporting ES 8)

**Comment by yrodiere** [comment]
Alright, the (deprecated) Elasticsearch high-level client doesn't work with Elasticsearch 8. I'll remove it, because it's been deprecated since Quarkus 3.0 IIRC.

**Comment by gsmet** [comment]
> Alright, the (deprecated) Elasticsearch high-level client doesn't work with Elasticsearch 8. I'll remove it, because it's been deprecated since Quarkus 3.0 IIRC.

Fine by me but let's do it in a separate PR as we need to mark it as noteworthy.

**Comment by gsmet** [comment]
OK, well, I see the title is clear enough, I will make this PR noteworthy.

**Review by gsmet — APPROVED** [review]

**Comment by loicmathieu** [comment]
The high level rest client is Still used by the réactive extension.
I'm not against removing it but can we wait a little more so I have time to support the Java client on the réactive extension? 
Also maybe worth it to check the download numbers to be sure it's not still used à lot

**Comment by yrodiere** [comment]
We're stuck on Elasticsearch 7 as long as we keep the high level client, so
it's not really something we can do forever... Elasticsearch will no longer
be supported starting August 1st.

Le ven. 7 juil. 2023, 18:57, Loïc Mathieu ***@***.***> a
écrit :

**Comment by yrodiere** [comment]
Elasticsearch 7* will no longer be supported starting August 1st.

**Comment by gsmet** [comment]
I think we can get rid of this extension. If people need time to upgrade, they can use 3.2 for a while since it will be an LTS.

**Comment by loicmathieu** [comment]
@gsmet true, I forgot that this move is after 3.2 that is an LTS.
Good for me to delete it, I will launch the discussion about a reactive Java Client on Zulip (I'll need someone from Vert.x side) and add a note on the existing reactive client to mark it as deprecated for removal, it's an experimental extension anyway.

**Review by loicmathieu — APPROVED** [review]

**Comment by geoand** [comment]
What's the status of this?

**Comment by gsmet** [comment]
I had a look earlier today and I think `io.quarkus.logging.gelf.it.GelfLogHandlerTest.test` failure could be related to the Elasticsearch upgrade.

**Comment by gsmet** [comment]
I force pushed a rebase to fix a conflict.

**Comment by loicmathieu** [comment]
@gsmet the library may not be compatible with 8.8, as Elasticsearch is only used for integration test (the library send UDP packet to logstash in a traditional ELK setup) so we can safely test with a lower version.

I notice that the library is no more maintained since a few days, so it's really new and it's a really stable library so not urgent but yes, we should do something. OpenTelemetry logs specification is now stable, I think the best for Quarkus would be to support this new standard for log centralization and deprecate the logging-gelf extension. But as you said, this is another discussion.

I'll have a look tomorrow but the error `object mapping for [host] tried to parse field [host] as object, but found a concrete value` may indicate a discrepancy of the mapping.

**Comment by loicmathieu** [comment]
@gsmet @yrodiere the Logstash mapping for the host field is now an object but the GELF Logstash plugin emits a String. As it's for testing only I fixes it by removing the field from the pipeline. See https://github.com/loicmathieu/quarkus/commit/5ac78a63fb50b63859959ce4bd9f2b97556eb1f8

Please include this commit (or do the same on your branch).

**Comment by gsmet** [comment]
@loicmathieu but is the underlying library still compatible with recent Logstash versions or do we have a problem?

**Comment by loicmathieu** [comment]
@gsmet the underlying library is still compatible with Logstash, but with recent versions the pipeline must be updated to handle the fact that Logstash changes it's default mapping for host from string to object. That's what I do with the very basic pipeline we use in our test. I assume most people that uses it with Logstash are aware of this kind of changes.

Anyway, this library allows to send logs to multiple bakends, Logstash being one of them, so it' still accurate until we have something else to send logs to a central backend.

**Comment by yrodiere** [comment]
Having a look at the test failures.

**Comment by gsmet** [comment]
`integration-tests/grpc-hibernate` was a flaky test

**Comment by yrodiere** [comment]
I pushed an update that might 

> Having a look at the test failures.

I wasn't able to reproduce locally, so I added a bit more configuration to get rid of environment-specific problems (such as a disk too full leading to Elasticsearch misbehaving). Let's see how it goes.

**Comment by yrodiere** [comment]
I think the failing tests are just flaky.

**Comment by yrodiere** [comment]
Merging as the build failures seem unrelated and already present on `main`: https://github.com/quarkusio/quarkus/actions/runs/5771471073

Seems like even before my changes, we're reaching the 6h timeout on some jobs... We'll have to work on that.

**Comment by yrodiere** [comment]
I updated the migration guide to mention these changes: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3

**Pull request merged**
