### PR TITLE
Introduce app.kubernetes.io/managed-by label to k8s manifest generation

### LINKED ISSUE #30572: should set `app.kubernetes.io/managed-by=quarkus` when we generate deploy schemas
### Description

in https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ is documented that `app.kubernetes.io/managed-by` should be set to the app that setup the deployment, i.e. `helm`

we should set it to `quarkus` to separate it from hand edited deployments.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #30572

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by iocanel — CHANGES_REQUESTED** [review]
I see support for kubernetes, openshift, kind but not knative and minikube.

I would expect setting the label in the `KubenretesCommonHelper.createDecorator` instead. Do I miss something?

**Comment by geoand** [comment]
> I would expect setting the label in the KubenretesCommonHelper.createDecorator instead. Do I miss something?

We could certainly hard code it there. Do we really want to do that?

**Comment by geoand** [comment]
Also FWIW, `Kind` does include this. Minikube doesn't

**Review by iocanel — APPROVED** [review]
It seems weird to me that we are setting labels in so many differnet places.
However, this is how it is and no directly related to the PR, so I'll approve and create a differnet issue about it.

**Comment by geoand** [comment]
The way I see it, this allows us to customize labels per type, but we can
certainly centralize things more if you think it's best

**Pull request merged**
