### PR TITLE
Upgrade to Hibernate ORM 6.2.1.Final

### LINKED ISSUE #32464: Spring Data API Extension not updating generic mapping
### Describe the bug

I have a generic baseclass (annotated with `@MappedSuperclass`) with a one to one (unidirectional) mapping. Then i save the entity which extends the base class. The property child (which is the mapped entity) is null. Now when i create a child i also update the parent so that the parent is connected to child. But only the child is stored to the database but the parent column won't get updated with the id of the child. 
If the mapping is not done with a generic it works as expected. In Spring Boot it also works with a generic.

### Expected behavior

The parent should be correctly updated.

### Actual behavior

_No response_

### How to Reproduce?

1. Go to the swagger: [http://localhost:42000/test/q/swagger/]
2. Call POST /test/rest/parents with the following data
```
{
  "child": null,
  "id": null,
  "name": "string"
}
```
3. Call POST /test/rest/parents/{parentId}/children with the following data
`parentId = 1`
```
{
  "id": null,
  "childName": "string"
}
```
4. Call GET /test/rest/parents/{parentId} with the following data
`parentId = 1`
Now the response should be:
```
{
  "child": null,
  "id": 1,
  "name": "string"
}
```
If it worked correctly the child shouldn't be null
The reproducer is with version 3.0.0.CR2 it also does not work with 2.16.5
[reproducerGenericMapping.zip](https://github.com/quarkusio/quarkus/files/11169477/reproducerGenericMapping.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]
Placeholder to make sure we wait for Yoann.

**Comment by geoand** [comment]
CI seems to be encountering some OOMs in the ORM tests.. Not a good sign :(

**Comment by Sanne** [comment]
I missed that there's a new service required by ORM, it needs to be registered in our custom bootstrap.

**Comment by Sanne** [comment]
Should be fixed now

**Review by yrodiere — APPROVED** [review]
LGTM, thanks

**Comment by geoand** [comment]
@michalvavrik @brunobat we have `OracleOpenTelemetryJdbcInstrumentationTest` failing again

**Comment by yrodiere** [comment]
> @michalvavrik @brunobat we have `OracleOpenTelemetryJdbcInstrumentationTest` failing again

Seems unrelated though, it's a flaky test. Merging.

**Comment by Sanne** [comment]
> > @michalvavrik @brunobat we have `OracleOpenTelemetryJdbcInstrumentationTest` failing again
> 
> Seems unrelated though, it's a flaky test. Merging.

yes that failed previously as well and @michalvavrik had an idea about it - waiting for his PR :)

**Comment by Sanne** [comment]
@yrodiere FWIW, the reason we waited for you to review is that I lost track of any "fixes" tag you might want to link - I assume nothing in particular unless you add them.

**Comment by michalvavrik** [comment]
@geoand  @Sanne 

>2023-04-18T18:43:02.5999050Z [INFO] Running io.quarkus.it.opentelemetry.PostgresOpenTelemetryJdbcInstrumentationTest
2023-04-18T18:43:02.6168589Z [WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.021 s - in io.quarkus.it.opentelemetry.PostgresOpenTelemetryJdbcInstrumentationTest
> OracleOpenTelemetryJdbcInstrumentationTest.testOracleQueryTraced  Time elapsed: 3.889 s

Did you check git log @geoand ? I think this wasn't rebased on the fix, that's all. The test is enabled now.

**Comment by michalvavrik** [comment]
> > > @michalvavrik @brunobat we have `OracleOpenTelemetryJdbcInstrumentationTest` failing again
> > 
> > 
> > Seems unrelated though, it's a flaky test. Merging.
> 
> yes that failed previously as well and @michalvavrik had an idea about it - waiting for his PR :)

https://github.com/quarkusio/quarkus/pull/32697

**Comment by geoand** [comment]
> Did you check git log @geoand ? I think this wasn't rebased on the fix, that's all. The test is enabled now.

Ah, I didn't realise the PR was "old" (in Quarkus terms)

**Pull request merged**
