### PR TITLE
Quartz - replace Arc.container() with Instance<UserTransaction>

### LINKED ISSUE #12896: CDI: programmatic lookup problem detected - Nayarana - 1.9.0.Final
**Describe the bug**
A warning message is printed when using `@Transactional` in 1.9.0.Final

**Expected behavior**
No warning message should show up.

**Actual behavior**
This message on startup is shown:

``` 
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build
Removed beans:
	- PRODUCER_METHOD bean io.quarkus.narayana.jta.runtime.NarayanaJtaProducers#userTransaction() [types=[interface javax.transaction.UserTransaction], qualifiers=[@javax.enterprise.inject.Default(), @javax.enterprise.inject.Any()]]
Required type: interface javax.transaction.UserTransaction
Required qualifiers: [@javax.enterprise.inject.Default()]
```

**To Reproduce**

Create any project using `@Transactional` annotation in some bean. Then just package and startup application.

**Configuration**

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: JDK 11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.9.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
Related to https://github.com/quarkusio/quarkus/issues/12420

### PR DESCRIPTION
**Pull request by mkouba**
- so that the UserTransaction is not removed if no other injection point
exists

Fixes #12896

### CODE REVIEW

**Comment by mkouba** [comment]
@ochaloup This should eliminate the warning...

**Comment by manovotn** [comment]
Fixes #12896

**Review by manovotn — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]

**Comment by mkouba** [comment]
Thanks for review @machi1990.

**Comment by gsmet** [comment]
Don't worry about the bot message. I had to redeliver the message to test a node.js update.

**Pull request merged**
