### PR TITLE
Fix broken Feature#runtimeInitializedPackages method

### PR DESCRIPTION
**Pull request by geoand**
Relates to: https://github.com/quarkiverse/quarkus-neo4j/pull/115

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM @geoand, thanks !

Good catch by the way, this should have been caught by the CI though. Do you think you could add a test for it as well?

**Comment by geoand** [comment]
> Do you think you could add a test for it as well?

The only way I can think of to do this would be to have some custom extension that generates the build item. I think it's a worthy addition :)

**Review by mkouba — APPROVED** [review]

**Comment by zakkak** [comment]
> > Do you think you could add a test for it as well?
> 
> The only way I can think of to do this would be to have some custom extension that generates the build item. I think it's a worthy addition :)

Perhaps you can reuse/extend this https://github.com/quarkusio/quarkus/blob/f096001b848bc3fa208c48c1fba5007ef89df4fe/integration-tests/test-extension/extension/deployment/src/main/java/io/quarkus/extest/deployment/TestProcessor.java#L465-L468 ?

**Comment by geoand** [comment]
That integration test should actually be run when in the `Misc2` category. There is some problem in the `filter-native-tests-json.sh` script

**Comment by geoand** [comment]
@famod any chance you can take a look at `filter-native-tests-json.sh`? 
What seems to happen here is that because `integration-tests/test-extension` is a multi-module directory, the script gets mixed up and does not include it in the output.

**Comment by zakkak** [comment]
There seems to be another issue with the test. In the [mandrel nightly CI runs](https://github.com/graalvm/mandrel/actions/workflows/nightly.yml) (that are not "incremental") the test is included in `Misc2`, yet [it looks like there are no native tests in there](https://github.com/graalvm/mandrel/actions/runs/3754247648/jobs/6378567415#step:11:675).

**Comment by geoand** [comment]
That's weird because when I ran the test manually `mvn verify -Dnative` in `integration-tests/test-extension` the native tests ran

**Comment by zakkak** [comment]
> That's weird because when I ran the test manually `mvn verify -Dnative` in `integration-tests/test-extension` the native tests ran

Are these native tests though, do you see a native-image being generated? Can you try with `mvn verify -Dnative.surefire.skip`?

**Comment by geoand** [comment]
Yes, I saw the native binary being built with my fix while seeing the error mentioned in https://github.com/quarkiverse/quarkus-neo4j/pull/115 without it

**Comment by zakkak** [comment]
I tried locally on 4397da64f763294425aceb33655d12978c9f5a99 with `./mvnw -Dnative -pl integration-tests/test-extension/ clean verify` and can't get it to build and run :/

**Comment by geoand** [comment]
`mvn verify -Dnative -f integration-tests/test-extension/` does the trick for me

**Comment by zakkak** [comment]
OK, that seems to be an issue in the CI as well (both in the mandrel workdlows and the quarkus), which run the tests using:

```
./mvnw -Dnative -f integration-tests -pl test-extension ...
```

https://github.com/quarkusio/quarkus/blob/b32cf7edd17fedaab270d86149971662c1938c87/.github/workflows/ci-actions-incremental.yml#L740

**Comment by geoand** [comment]
Yeah, that's certainly part of the problem. The other part is that `$TEST_MODULES` is not populated correctly :)

**Comment by zakkak** [comment]
> Yeah, that's certainly part of the problem. 

I opened https://github.com/quarkusio/quarkus/pull/30035 and https://github.com/graalvm/mandrel/pull/462

> The other part is that $TEST_MODULES is not populated correctly :)

For this part I can't help much but it looks like the test is correctly added when running on the `main` branch:

https://github.com/quarkusio/quarkus/actions/runs/3755597705/jobs/6381059498#step:12:15

**Comment by geoand** [comment]
Ah, that's nice!

**Pull request merged**
