### PR TITLE
RestClient Reactive: Default conversion for basic types

### LINKED ISSUE #27430: Default parameter conversion for REST Client Reactive
### Description

At the moment, REST Client Reactive, supports only String parameters or parameters that have registered custom parameter converters.
Anything else results in
```
Form element 'io.quarkus.it.rest.client.multipart.MultipartClient$WithBufferAsTextFile.number' could not be converted to 'String' for REST Client interface 'io.quarkus.it.rest.client.multipart.MultipartClient'. A proper implementation of 'javax.ws.rs.ext.ParamConverter' needs to be returned by a 'javax.ws.rs.ext.ParamConverterProvider' that is registered with the client via the @RegisterProvider annotation on the REST Client interface.
```

On the server side, we convert parameters according to the JAXRS spec:
```
Valid parameter types for each of the above annotations are listed in the corresponding Javadoc, however in general (excluding @Context) the following types are supported:

Types for which a ParamConverter is available via a registered ParamConverterProvider. See Javadoc for these classes for more information.

Primitive types.

Types that have a constructor that accepts a single String argument.

Types that have a static method named valueOf or fromString with a single String argument that return an instance of the type. If both methods are present then valueOf MUST be used unless the type is an enum in which case fromString MUST be used[1].

List<T>, Set<T>, or SortedSet<T>, where T satisfies 1,3 or 4 above.
```

We should support similar conversions on the client side (but the client side needs to convert from some type, e.g. primitive, to string).

CC @FroMage @Sgitario @geoand 

Origin: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/RESTEasy.20Reactive.20client.20ParamConverter

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Default support for primitive and enum types. For the rest, a custom converter is necessary. 

Fix https://github.com/quarkusio/quarkus/issues/27430

### CODE REVIEW

**Comment by Sgitario** [comment]
@michalszynkiewicz I'm not 100% sure that this was the goal of https://github.com/quarkusio/quarkus/issues/27430 or if there is something more to cover, but unless we can have these changes to make some progress.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
Something is wrong, the test failure is:
```java
org.keycloak.admin.client.resource.RealmResource$$QuarkusRestClientInterface.testSMTPConnection(java.lang.String) 
2022-08-24T20:16:07.9059051Z Parsing context:
2022-08-24T20:16:07.9059562Z    at org.keycloak.admin.client.resource.RealmResource$$QuarkusRestClientInterface.testSMTPConnection(Unknown Source)
2022-08-24T20:16:07.9060272Z    at org.keycloak.admin.client.resource.RealmResource.testSMTPConnection(RealmResource.java)
2022-08-24T20:16:07.9066246Z 
2022-08-24T20:16:07.9074394Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
2022-08-24T20:16:07.9081827Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
2022-08-24T20:16:07.9088942Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
2022-08-24T20:16:07.9096037Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
2022-08-24T20:16:07.9103563Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
2022-08-24T20:16:07.9110307Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:558)
2022-08-24T20:16:07.9117291Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:635)
2022-08-24T20:16:07.9129605Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
2022-08-24T20:16:07.9131000Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
2022-08-24T20:16:07.9131639Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
2022-08-24T20:16:07.9132129Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
2022-08-24T20:16:07.9176437Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
2022-08-24T20:16:07.9177384Z ------------------------------------------------------------------------------------------------------------------------
2022-08-24T20:16:07.9216054Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
2022-08-24T20:16:07.9216626Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
2022-08-24T20:16:07.9217161Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-08-24T20:16:07.9218630Z Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.lang.String.name(). This error is reported at image build time because class org.keycloak.admin.client.resource.RealmResource$$QuarkusRestClientInterface is registered for linking at image build time by command line
2022-08-24T20:16:07.9219744Z 	at parsing org.keycloak.admin.client.resource.RealmResource$$QuarkusRestClientInterface.testSMTPConnection(Unknown Source)
2022-08-24T20:16:07.9220415Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2506)
2022-08-24T20:16:07.9221418Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:105)
2022-08-24T20:16:07.9222247Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3367)
2022-08-24T20:16:07.9222982Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3319)
2022-08-24T20:16:07.9223662Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3164)
2022-08-24T20:16:07.9224273Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
2022-08-24T20:16:07.9224913Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
2022-08-24T20:16:07.9225569Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2022-08-24T20:16:07.9226266Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
2022-08-24T20:16:07.9227003Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2022-08-24T20:16:07.9227635Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:261)
2022-08-24T20:16:07.9228142Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2022-08-24T20:16:07.9228623Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2022-08-24T20:16:07.9229233Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
2022-08-24T20:16:07.9229970Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
2022-08-24T20:16:07.9230684Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:168)
2022-08-24T20:16:07.9231392Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:343)
2022-08-24T20:16:07.9232087Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
2022-08-24T20:16:07.9232527Z 	... 13 more
2022-08-24T20:16:07.9233573Z Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.lang.String.name(). This error is reported at image build time because class org.keycloak.admin.client.resource.RealmResource$$QuarkusRestClientInterface is registered for linking at image build time by command line
2022-08-24T20:16:07.9234830Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:298)
2022-08-24T20:16:07.9235778Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:288)
2022-08-24T20:16:07.9236968Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:244)
2022-08-24T20:16:07.9237916Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1709)
2022-08-24T20:16:07.9238599Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5222)
2022-08-24T20:16:07.9239306Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3359)
```

**Comment by geoand** [comment]
@Sgitario this is now causing multiple PRs to fail on the JAX-RS TCK `JAXRSClient0133`. If we don't have a quick fix, we'll have to revert it

**Comment by Sgitario** [comment]
Let's revert it and will investigate it later.

**Comment by geoand** [comment]
@Sgitario ignore my previous comment - I made it on the wrong issue :)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/26495 is the actual problem

**Pull request merged**
