### PR TITLE
Easy Config-related cleanups #5388

### PR DESCRIPTION
**Pull request by ShubhamRwt**
Fixes correspondoing to first problem listed in #5388

### CODE REVIEW

**Comment by geoand** [comment]
Hi,

Thanks a lot for the PR! 
Can you please squash the commits into a single one?

**Comment by ShubhamRwt** [comment]
Yes sure @geoand ,On it.

**Comment by ShubhamRwt** [comment]
@geoand I have squashed the commits. There were 4 problems listed in issue #5388 . I will be sending  separate PRs for each problem as suggested by @dmlloyd

**Comment by geoand** [comment]
Good idea, thanks!

**Review by geoand — APPROVED** [review]
LGTM, @gsmet want to take a quick look as well?

**Review by machi1990 — APPROVED** [review]
LGTM, thanks @ShubhamRwt

**Comment by gsmet** [comment]
I rebased and force pushed.

**Comment by machi1990** [comment]
Merged. Thanks @ShubhamRwt

**Comment by machi1990** [comment]
> Fixes correspondoing to first problem listed in #5388

@ShubhamRwt do you want to take a look at the remaining parts listed in the issue
#5388?

**Comment by ShubhamRwt** [comment]
@machi1990 Yes. I will send it by tomorrow.

**Comment by machi1990** [comment]
Great, thanks!

**Pull request merged**
