### PR TITLE
Bump infinispan from 13.0.8.Final to 13.0.10.Final

### PR DESCRIPTION
**Pull request by vardhmanJain**
upgrade to infinispan 13.0.10.Final

### CODE REVIEW

**Comment by gsmet** [comment]
@karesti could you have a look at this one? Looks like something we want for 2.10.0.Final.

**Comment by gastaldi** [comment]
@gsmet FTR this PR is targeting 2.7, Infinispan 13.0.10.Final is already in 2.10.0.CR1 (it was added in https://github.com/quarkusio/quarkus/pull/25405)

**Comment by gsmet** [comment]
@gastaldi ah thanks, I missed that.

@vardhmanJain why do you want it in 2.7?

**Comment by vardhmanJain** [comment]
Hi @gsmet 
13.0.8.Final is not productized by the RHDG team while 13.0.10.Final is productized and supported.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks for the explanation.

**Comment by gsmet** [comment]
Next time, let's just add `triage/backport-2.7?` labels to the relevant PRs. Because we are missing the Protostream upgrade: https://github.com/quarkusio/quarkus/pull/25306/files .

I will fix it.

**Comment by gsmet** [comment]
Fixed here: https://github.com/quarkusio/quarkus/pull/26095 .

**Comment by karesti** [comment]
@gsmet nice catch, thank you very much

**Pull request merged**
