### PR TITLE
Eliminating the white space from the xref macro

### PR DESCRIPTION
**Pull request by MichalMaler**
The correct way of using xref macro is documented in https://quarkus.io/guides/doc-reference#anchors-reference
This PR just cleans it up so that contributors can not get a bad example directly from the source code.

Kudos to @jmartisk for creation of the regex to catch them all.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Good catch!

**Review by cescoffier — APPROVED** [review]
Question: Should we have a linter with such kind of rules?

**Review by Ladicek — APPROVED** [review]

**Comment by michelle-purcell** [comment]
> Question: Should we have a linter with such kind of rules?

Great idea @cescoffier . We could investigate adding this to the Vale ruleset for Quarkus. 
@MichalMaler - WDYT?  let's try this out... :test_tube: 
BTW... a PR is on the way to fix most of the false-positives too.

**Review by jmartisk — APPROVED** [review]

**Review by michelle-purcell — APPROVED** [review]

**Comment by gsmet** [comment]
Does it hurt to have a whitespace? Just wondering how much we should invest in it.

**Comment by MichalMaler** [comment]
> Does it hurt to have a whitespace? Just wondering how much we should invest in it.

I guess it doesn't hurt, but I like to keep things unified if possible.
The recommendation to not to use the space after comma come directly from you; you told me this while i was drafting the cross-ref guide (March 22)

**Comment by gsmet** [comment]
Well, I don't recall saying that tbh. I said it was working with or without equally but the doc is without and that our example should be consistent with the AsciiDoctor doc.

I'm not saying we shouldn't merge this, it's good. I wouldn't make it a priority to have a tooling to check that though, if it doesn't cause any problems, given all the other issues we have that actually cause problems.

**Comment by MichalMaler** [comment]
> Well, I don't recall saying that tbh. I said it was working with or without equally but the doc is without and that our example should be consistent with the AsciiDoctor doc.
> 
> I'm not saying we shouldn't merge this, it's good. I wouldn't make it a priority to have a tooling to check that though, if it doesn't cause any problems, given all the other issues we have that actually cause problems.

image

But you are saying in next sentence that you dont think it matters.
So, as I said, this is just a cosmetic tweak, clean-up, unification, to reach some consistency. :)

No hard feelings if this will not got merged.

**Comment by gsmet** [comment]
Looks like I had a good recollection of what I said :)

I'm not sure it's coming from these changes but the doc build is failing with:
```
[INFO] asciidoctor: INFO: possible invalid reference: duplicated-context
[INFO] asciidoctor: INFO: possible invalid reference: duplicated-context
```

**Comment by gsmet** [comment]
We need to understand what's going on with ^ but we can merge once it's fixed.

**Comment by MichalMaler** [comment]
> Looks like I had a good recollection of what I said :)

You are my greatest Quarkus hero, would never said something you didn't :))

All I did was use this to search for the space after a comma inside <<>> with:
`(<<[A-Za-z-]+,) `
And replace it with:
`$1`

The truth is, this operation had two iterations (but it was maybe caused by the fact that my IDEA didn't find all occurrences when I hit the FindNReplace button for the first time.

I double-checked all stuff I touched and they are all in the <<>>, thus should not touched the context or and ID.

**Review by gsmet — APPROVED** [review]
Merging as the failure is not related. I will fix it in an upcoming PR.

**Comment by michalvavrik** [comment]
> This PR just cleans it up so that contributors can not get a bad example directly from the source code.

Yeah, that's exactly how I work :-) Thanks!

**Pull request merged**
