### PR TITLE
Introduce a way to customize OTel TextMapPropagator

### LINKED ISSUE #31656: Allow restricting propagation of OpenTelemetry trace headers
### Description

As described in the w3c [trace-context](https://www.w3.org/TR/trace-context/#information-exposure) and [baggage](https://www.w3.org/TR/baggage/#information-exposure) specifications tracing headers might carry sensitive information. Currently once a [propagator is configured](https://quarkus.io/guides/opentelemetry#propagators) it unconditionally propagates regardless of who the service is talking to. If a service calls out to an untrusted system/third party this would expose the information.

As the headers being propagated might come from another applications call, it is very hard to ensure no sensitive data is present in the application actually making the request. The only safe solution is to prevent the information from being propagated to untrusted systems in the first place.

Currently there does not seem to be any way to restrict or customize this propagation behavior while using the quarkus-opentelemetry extension ([zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Controlling.20trace.20context.20propagation.20to.20third.20parties/near/338885117)).

As a developer it would be great to be able to whitelist URL patterns (and/or IP ranges) for propagation in the quarkus-opentelemetry configuration. This would allow safe configuration of who the information is transmitted to without much effort. The default would whitelist everything to retain compatibility.

Another, less safe, option would be some option to explicitly block propagation for certain URLs or rest clients through configuration/annotation.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #31656

### CODE REVIEW

**Comment by hacst** [comment]
If I understand correctly I would use this to create a wrapper around the propagator. On inject I would then introspect the carrier to see if it is a known type and whether it is OK to propagate according to my configuration and only then do the actual inject?

If that is possible then it should allow the kind of filtering I was trying to do. It is a bit unfortunate that this will have to rely on knowledge of the type and internals of the carriers, but as long as it allows handling normal framework http requests that will cover a lot already.

**Comment by geoand** [comment]
I added a test to the PR

**Comment by geoand** [comment]
This will conflict with #34946, but it's very easy to rebase this one on that one.

**Review by brunobat — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
