### PR TITLE
Upgrade Kotlin to v1.7.0

### PR DESCRIPTION
**Pull request by GavinRay97**
This should be one of the most impactful updates for Quarkus Kotlin users

The speedups to compile times range from 50-200% and include better incremental compilation support.

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
I think you missed some here: https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L147-L149 .

Also, we need to make sure things are compatible (especially Dokka, the coroutine stuff and serialization).

**Comment by GavinRay97** [comment]
Ah whoops!

I checked the`kotlin-coroutines`, `kotlin-serialization`, and `dokka` versions, and they don't have changes (they don't track with the Kotlin core version always)

**Comment by gsmet** [comment]
Can you squash the commits, please?

**Comment by GavinRay97** [comment]
Sure =)

**Comment by GavinRay97** [comment]
I'm not sure what eldritch horror I summoned with the wrong Git command but my history is all kinds of screwed up now.
Going to try to see if I can just delete the entire history and redo the initial commit.

image

**Comment by gsmet** [comment]
@GavinRay97 any chance you could revisit this PR with the latest changes you made? I don't think we have upgraded to 1.7.0 yet.

**Comment by gsmet** [comment]
If the history is all messed up, I would just start another clean branch and cherry-pick the commit.

**Pull request closed without merging**
