### PR TITLE
Add Optional converter

### LINKED ISSUE #25413: Quarkus testing with @ParameterizedTest using Optional broken with Java 17 + 18 (xstream)
### Describe the bug

This is the same issue as https://github.com/quarkusio/quarkus/issues/24492 but for `Optional`. The error is:
```
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Optional
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static final java.util.Optional java.util.Optional.EMPTY accessible: module java.base does not "opens java.util" to unnamed module @44f75083
-------------------------------
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

```java
@QuarkusTest
class OptionalTest {

    static Stream<Arguments> arguments() {
        return Stream.of(
                Arguments.of(Optional.empty()),
                Arguments.of(Optional.of("")),
                Arguments.of(Map.of("optional", Optional.empty())),
                Arguments.of(Map.of("optional", Optional.of(""))));
    }

    @ParameterizedTest
    @MethodSource("arguments")
    void map(Object o) {

    }

}
```

### Output of `uname -a` or `ver`

21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 17.0.3 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.5

### Additional information

Might not be very common to use optionals in this way but I'm testing JSON/Jackson conversion/mappings and I'm testing all the cases.

### PR DESCRIPTION
**Pull request by ejba**
Fixes #25413

### CODE REVIEW

**Comment by ejba** [comment]
I can't reproduce the test failure in my env. Should I re-trigger the CI pipeline?

**Comment by gsmet** [comment]
No it's just a flaky test.

**Comment by gsmet** [comment]
Argh, too late.

**Comment by ejba** [comment]
Ups, sorry @gsmet. I rebased the MR.

**Review by geoand — APPROVED** [review]

**Pull request merged**
