### PR TITLE
Fail by default when encountering interceptor annotations on private methods

### PR DESCRIPTION
**Pull request by yrodiere**
Cf. https://groups.google.com/g/quarkus-dev/c/ukQEujtlRbs

I didn't run the full test suite locally though, let's see how it goes...

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Comment by maxandersen** [comment]
If we change this default please be sure the exception throw provides info on how to revert it.

**Comment by gsmet** [comment]
Also make sure you add a note here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.17 .

**Comment by yrodiere** [comment]
> If we change this default please be sure the exception throw provides info on how to revert it.

Right, will do. The current message does not refer to the configuration property at all.

**Comment by yrodiere** [comment]
> If we change this default please be sure the exception throw provides info on how to revert it.

Done.

> Also make sure you add a note here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.17 .

Done.

**Comment by maxandersen** [comment]
Given this is a build breaking change would it not be a better option to wait until 3 to apply this ?

**Comment by yrodiere** [comment]
> Given this is a build breaking change would it not be a better option to wait until 3 to apply this ?

Please note this breaks the build only for applications that are already broken (in a way) because they have methods whose interceptor is being ignored.

As to waiting for 3... I personally don't mind, I guess that's soon-ish anyway?

I'll look into the test failure.

**Review by gwenneg — APPROVED** [review]
LGTM for the quarkus-cache changes.

**Comment by geoand** [comment]
Were are we with this one?

**Comment by yrodiere** [comment]
@geoand I'm done, and it works. @maxandersen wants to wait for Quarkus 3. I don't mind either way, so we're currently waiting.

**Comment by geoand** [comment]
Thanks for the update

**Pull request merged**
