### PR TITLE
Health-UI calls the wrong URL for health in dev mode

### LINKED ISSUE #21517: Health-UI call the wrong URL for health
### Describe the bug

I have this dependency in my pom.xml (Quarkus 2.4.2.Final)
````
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
````

if I enter this url : http://localhost:8080/q/health

I'll obtain this
````
{
    "status": "UP",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - liveness check",
            "status": "UP",
            "data": {
                "cleanupjob": "[OK]",
                "cleanupjob-completed": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "UP",
            "data": {
                "cleanupjob": "[OK]",
                "cleanupjob-completed": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - startup check",
            "status": "UP",
            "data": {
                "cleanupjob": "[OK]",
                "cleanupjob-completed": "[OK]"
            }
        }
    ]
}
````
but if I enter this : http://localhost:8080/q/health-ui/

I'll obtain this error

Why the url in the UI is trying to retreive this http://localhost:8080/health instead of http://localhost:8080/q/health

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

````
mvn io.quarkus.platform:quarkus-maven-plugin:2.4.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=microprofile-health-quickstart \
    -Dextensions="smallrye-health"
cd microprofile-health-quickstart
mvn clean quarkus:dev

http://localhost:8080/q/health/ -> works
http://localhost:8080/q/health-ui/ -> fails
````

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xstefank**
Fixes #21517

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
My silly mistake from the previous PR.... Sorry :)

**Comment by xstefank** [comment]
@phillip-kruger come on, no need to be sorry, this happens to all of us from time to time ;)

**Comment by gsmet** [comment]
@xstefank there's a formatting issue. Could you run `mvn process-sources` and amend your commit? Thanks!

**Comment by gastaldi** [comment]
The failing tests are unrelated and fixed in https://github.com/quarkusio/quarkus/pull/21544

**Pull request merged**
