### PR TITLE
Gradle: clear reloadable flag for extension dependencies

### PR DESCRIPTION
**Pull request by aloubyansky**
This has been missing in the Gradle plugin compared to the Maven one. Projects that include extensions could be failing w/o this fix due to project local dependencies ending up in different classloaders.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by aloubyansky** [comment]
BTW, @glefloch working on this PR I noticed quite a few Gradle tests while passing are terminating with a time out. E.g.
````
[INFO] Running io.quarkus.gradle.devmode.AnnotationProcessorSimpleModuleDevModeTest
$ /home/aloubyansky/git/quarkus/integration-tests/gradle/./gradlew -D=maven.repo.local=/home/aloubyansky/.m2/repository --stacktrace clean quarkusDev -s
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.719 s - in io.quarkus.gradle.devmode.AnnotationProcessorSimpleModuleDevModeTest
[ERROR] System Exit has timed out in the forked process 1
````
With or without this specific PR. Have you noticed that?

**Review by glefloch — COMMENTED** [review]
Yes, I haven't been able to reproduce it locally but sometimes, the `Process` started by java never ends, and we need to kill it.

**Review by glefloch — APPROVED** [review]
I closed it by mistake. This looks good to me.

**Comment by Foobartender** [comment]
This causes #23569 and probably #23591.

**Pull request merged**
