### PR TITLE
Make sure `GraphQLApi` are marked as CDI Bean

### LINKED ISSUE #18516: quarkus-smallrye-graphql and quarkus-neo4j don't work together in Quarkus 2.0.
Given a GraphQL API like this:

```
import javax.inject.Inject;

import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Name;
import org.eclipse.microprofile.graphql.Query;
import org.neo4j.driver.Driver;

@GraphQLApi
public class People {

	@Inject Driver driver;

	@Query("people")
	public CompletableFuture<List<Person>> getPeople(@Name("nameFilter") String nameFilter) {
		System.out.println(driver == null);
		return CompletableFuture.completedFuture(List.of());
	}
}
```

the injected driver will always be literal `null`. Used to work in 1.13.x, but not in 2.0.
I wonder if this is due to the `Neo4jDriverProducer` producing the driver as `Singleton` and the GraphQL things bootstrapping rather early.

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #18516

@michael-simons - would be great if you can confirm. I tested against your example and this fix it.

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by jmartisk** [comment]
Here you're just specifying the application scope on the bean, I wonder why that's needed, why leaving it to the default scope (which one is that? dependent?) isn't enough. Do you have an explanation why it worked in 1.13? 

AFAIK `@Injecting` into a `@GraphQLApi` has always worked (without adding any explicit CDI scope), for example see this test which does it: https://github.com/quarkusio/quarkus/blob/2.0.1.Final/extensions/smallrye-graphql-client/deployment/src/test/java/io/quarkus/smallrye/graphql/client/deployment/model/TestingGraphQLApi.java 

How this fix works is a bit of a mystery to me

**Comment by phillip-kruger** [comment]
Not sure. Maybe something changed in Arc ? @mkouba ?

**Comment by mkouba** [comment]
There are no changes in this area I'm aware of. I can take a look at the reproducer. I think that we should not merge this workaround until we find the real cause.

**Comment by phillip-kruger** [comment]
Thanks @mkouba !

**Pull request closed without merging**
