### PR TITLE
Add m2e lifecycle mapping to bootstrap maven plugin

### PR DESCRIPTION
**Pull request by aloubyansky**
Fix for #1769

### CODE REVIEW

**Comment by FroMage** [comment]
Well, on the surface it looks better, except this seems to cause an infinite loop of invoking "Maven Project Builder" on every project forever and ever.

**Comment by gsmet** [comment]
@FroMage what's the status of this? I think I have seen a few discussions on Zulip regarding issues with Eclipse but I'm not sure if you sorted this one out?

**Comment by aloubyansky** [comment]
If Maven update doesn't work after applying this change then re-import the project (basically re-create the workspace).

**Review by gsmet — APPROVED** [review]
I could get my Eclipse workspace to work so it looks good to me.

**Pull request merged**
