### PR TITLE
Upgrade to RESTEasy 4.7.2.Final

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by sberyozkin** [comment]
@gsmet James Perkins released 4.7.3 yesterday, so I was planning to update it, would you like to change it to 4.7.3 or I can follow up

**Comment by sberyozkin** [comment]
I was thinking of writing a test to verify 4.7.3 provides a hardening fix, so may be it would be better to follow up with another PR

**Comment by gsmet** [comment]
@sberyozkin I merged it. No problem to upgrade to 4.7.3.Final in the next few days.

**Comment by sberyozkin** [comment]
@gsmet `dependabot` has already started the process :-)

**Pull request merged**
