### PR TITLE
Handle symlink dirs

### LINKED ISSUE #37223: Quarkus cannot find gRPC input files through symlinks
### Describe the bug

When one makes the /src/main/proto directory a symlink to another directory, Quarkus cannot find the `.proto` files within that symlinked directory.

### Expected behavior

Quarkus compiles the .proto files within the symlink target to java classes within `/build/classes/java/quarkus-generated-sources`

### Actual behavior

`/build/classes/java/quarkus-generated-sources` is empty.

### How to Reproduce?

1. Set up a Quarkus project with the gRPC extension installed.
2. Create a directory with `.proto` files that Quarkus can compile
3. Create a symlink in /src/main/proto that links to the directory in step 2.
4. Run `quarkusBuild`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22635.2771]

### Output of `java -version`

java version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.5.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alesj**
Fix #37223, resolve all context dirs.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
I think the name is fine.

**Comment by alesj** [comment]
@cescoffier let's wait a bit with the merge, as @dmlloyd has some valid points via comments in #37223

**Comment by cescoffier** [comment]
After discussion we should only handle symlink for the input directory not the other ones.

**Comment by alesj** [comment]
> After discussion we should only handle symlink for the input directory not the other ones.

OK, I just reverted to just the input dir.

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
