### PR TITLE
Dev console - make it possible to output config properties

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
There are CI failures though ?

**Comment by phillip-kruger** [comment]
Thanks @mkouba !!

**Comment by mkouba** [comment]
> There are CI failures though ?

It's a formatting issue again... :-(

**Comment by phillip-kruger** [comment]
I hate those !! (I am wondering, can the CI not just fix that ?)

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Hmmm. Let me merge all this Dev Console PR into one or it will be a nightmare to rebase.

**Pull request closed without merging**
