### PR TITLE
Configurable Telemetry for static resources

### LINKED ISSUE #19907: Static resources as operations in Jaeger
### Describe the bug

After enabling tracing with OLTP for a frontend application, I realised that even static resources are being shown as operations in the Jaeger UI (see attached picture). 
Screenshot 2021-09-03 at 16 15 42

### Expected behavior

Only REST operations are listed 

### Actual behavior

Static resources are shown as operations

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Darwin DWI-MBP15-1.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.6" 2020-01-14 LTS

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #19907

~~Had to move `StaticResourcesBuildItem` to `vertx-http-deployment-spi`. If this is not acceptable, we need to duplicate this (or deprecate the old one and add a new one).~~

Also, the PR changes the telemetry behavior for static resources. Before, all static resources are captured by OpenTelemetry. After the PR, static resources are dropped from OpenTelemetry. I believe it should be better like this as default behavior since I see no reason why would someone prefer to record telemetry data on static resources. It is possible to revert to the old behavior with the configuration `quarkus.opentelemetry.tracer.include-static-resources=true`. Once this is merged, it requires a note in the migration guide.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by radcortez** [comment]
@geoand are you ok with the `StaticResourcesBuildItem` move?

**Comment by geoand** [comment]
You also changed the package, no?

**Comment by radcortez** [comment]
> You also changed the package, no?

Yes. We could keep the same package in the SPI module, but that would look weird.

> If so, then we can't do it, because Kogito depends on it. We probably need to have 2 versions for now and deprecate the old one (for removal)

Ok, let me do this.

**Comment by geoand** [comment]
@evacchi Kogito should be aware of this PR. Essentially once it's in, you should change to use the new `StaticResourcesBuildItem` (although the existing one will be around for a while but will be deprecated).

**Comment by evacchi** [comment]
@tkobayas implemented the change

**Comment by radcortez** [comment]
Moved `StaticResourcesBuildItem` to `spi` and marked the old `StaticResourcesBuildItem` as deprecated.

**Comment by gsmet** [comment]
@radcortez just a suggestion but I wonder if `quarkus.opentelemetry.tracer.include-static-resources=true` would be better?

**Comment by tkobayas** [comment]
@evacchi  @geoand  The introduced change in Kogito was `AdditionalStaticResourceBuildItem`, not `StaticResourcesBuildItem`. Is it still affected?

https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java#L149

**Comment by geoand** [comment]
Ah, you are right.

That one is not affected

**Comment by radcortez** [comment]
> @radcortez just a suggestion but I wonder if `quarkus.opentelemetry.tracer.include-static-resources=true` would be better?

It is. I had the current name to be consistent with `quarkus.opentelemetry.tracer.include-static-resources-suppress-non-application-uris`, but it is not a big deal. Let me change it.

**Review by geoand — APPROVED** [review]

**Pull request merged**
