### PR TITLE
Remove not used extension registry plugins

### PR DESCRIPTION
**Pull request by maxandersen**
Why:

 * want to improve Extension metadata and old registry plugins
   makes that harder.

This change addreses the need by:

 * remove the extension plugin.
 * next step after is to remove the old registry platform but that is
   currently being used.

### CODE REVIEW

**Comment by maxandersen** [comment]
checked i can build (without tests) so lets see what the PR completes if we want to be sure it doesn't break any other IT tests.

**Comment by maxandersen** [comment]
or @aloubyansky if you can verify you agree i'm fine applying this immediately ;)

**Review by aloubyansky — APPROVED** [review]

**Comment by geoand** [comment]
CI isn't liking this :(

**Comment by maxandersen** [comment]
> CI isn't liking this :(

my bad - removed a module but didn't remove the previous built one in .m2 cache thus my local build was running fine. pushed update that should hopefully get us further!

**Pull request merged**
