### PR TITLE
[fixes #5397] - Updating guide to include path permissions

### LINKED ISSUE #5397: security-openid-connect-web-authentication.adoc is out of sync with current code base and related quickstart
security-openid-connect-web-authentication.adoc is out of sync with current code base and related quickstart

There were several adjustments to the codebase and security-openid-connect-web-authentication-quickstart was updated too
https://github.com/quarkusio/quarkus-quickstarts/commits/development/security-openid-connect-web-authentication-quickstart

security-openid-connect-web-authentication.adoc needs to catch up with those changes

### PR DESCRIPTION
**Pull request by pedroigor**
@sberyozkin I did not comment about why you need permissions because I think this is covered by the security guide. If you think otherwise, please let me know.

### CODE REVIEW

**Comment by gsmet** [comment]
@pedroigor should it be included in 1.0 Final? Or is it about a newly added feature?

**Comment by pedroigor** [comment]
> @pedroigor should it be included in 1.0 Final? Or is it about a newly added feature?

I think it should be included in 1.0.Final. As well as https://github.com/quarkusio/quarkus-quickstarts/commit/e18a67758dde3a4876b83313da6ed59cc6b601e0#diff-f85db8aa6e5aec0b2d2c933f127763fb, which is only in the development branch.

**Comment by gsmet** [comment]
@cescoffier are you aware of this quickstart commit ^

**Comment by pedroigor** [comment]
@gsmet Actually, I'm not sure ... I would say it has to be in 1.0 if the change (upstream) that made that configuration necessary was backported or is in the backport queue.

**Comment by pedroigor** [comment]
@gsmet See https://github.com/quarkusio/quarkus/commit/7457063fe14d7269e8c58f6a8a6d151ab59c23cc. It was included in 1.0.

**Comment by sberyozkin** [comment]
@pedroigor to be honest I was not sure why they had to be added :-), I guess that after Stuart fixed it for the "/health" path not to be secured (unrelated issue) some paths on the test flow became unsecure which caused the test failure.

**Review by sberyozkin — APPROVED** [review]
LGTM - since the #5397 task is about synchronizing the quick start source with the guide text

**Comment by sberyozkin** [comment]
@pedroigor Can you please check and indeed comment about those 2 lines ? Adding something like "This policy configuration requires that a user has to be authenticated to access all the endpoiint resources, please check the http permissions guiide[link] for more information" or something similar should be enough...

**Comment by sberyozkin** [comment]
@pedroigor thanks

**Pull request merged**
