### PR TITLE
Introducing Kafka Streams DevUI

### PR DESCRIPTION
**Pull request by danielpetisme**
This PR aims at providing a Dev UI for Kafka Streams.
The first element is a topology visualizer similar to https://zz85.github.io/kafka-streams-viz/.
I choose to use [mermaid.js](https://mermaid-js.github.io/mermaid/#/) rather than a graphviz JS implementation.

The topology is fetched from the Arc container to supply a TopologyDescription object.
Then it's up to the frontend part to parse it, build a mermaid description and render the final graph.
Here you have an example
Screenshot 2021-10-11 at 11 40 40

UI remarks
* The textarea is reaonly, the topology visualizer aimed at rendering the current application topology not to be a general purpose Kafka Streams topology visualizer tool.
* I used Mermaid default styling. Is there a Quarkus color palette? Is it worth it?
* The textarea font could be reduce a bit... What do you think?

The main concern I have is regarding mermaid.js files, I had to update the vertx-http extension to bundle the JS files.
I didn't found a way to package static assets as part of the extension itself. I think for isolation/decoupling purposes it would be better to not have to update the vertx-http extension...
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/DevUI.20custom.20static.20resources/near/256872499

I may add a "statics row on top of the current content displaying the numbers of sub-topologies, input/output topics as well as state stores.

This is the first draft so, feedbacks are more than welcome!

### CODE REVIEW

**Comment by gsmet** [comment]
Woot, this is very nice!

How complex can a topology be? I wonder if it's going to work well to have both on the same line? But maybe you can tweak things depending on the number of columns?

As for pushing the JS dependency to vertx-http, I think it has also some advantages as it would be good to reuse the same JS libraries across all Dev UI components. So I would lean towards keeping it that way.

**Review by phillip-kruger — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a few comments.

**Comment by phillip-kruger** [comment]
@danielpetisme - I like what you have now, I don't think that is an error message, but rather an info message. Nice and clear.

**Review by gsmet — DISMISSED** [review]
I spotted a small remaining issue. Once fixed, I think we should merge it.

**Comment by geoand** [comment]
👍🏼

**Pull request merged**
