### PR TITLE
Rewrite the Vert.x MDC tests to be more robust

### PR DESCRIPTION
**Pull request by cescoffier**
@gsmet as requested, let's see how it goes....

My rewrite does not call a remove service (which can be very slow and stop responding).

### CODE REVIEW

**Comment by cescoffier** [comment]
I don't believe the CI ran successfully... @gsmet @geoand any idea?

**Comment by cescoffier** [comment]
Quarkus CI / JVM Tests - JDK 17 (pull_request) Successful in 3m ..... yeah sure....

**Comment by cescoffier** [comment]
ah no, it only ran the updated modules... nice!

**Comment by geoand** [comment]
Yeah, that's the GIB Maven extension (from @famod) at work :)

**Review by gsmet — APPROVED** [review]
I will rerun them once to have another run.

**Comment by cescoffier** [comment]
Yeah... I will have another look tomorrow. I was hoping it was the remote service, but it's not.

I need to look under the hood, it might be a real bug, not just a test issue.

**Comment by cescoffier** [comment]
We had a green build.
I ran the windows tests again to ensure it was not just chance. 

I just started the whole pipeline again to see.


----

The PR:

- removes the external service. It can be slow or even block our requests (rate limiting / blacklisting)
- makes sure we wait for the log handler to be in the delayed handler list before starting to execute the tests

**Comment by cescoffier** [comment]
Another green run, let's merge and see if I need to revisit them again later.

**Pull request merged**
