### PR TITLE
Upgrade to kubernetes-client 4.10.2

### LINKED ISSUE #1313: [Quarkus 1.6] Unresolved method AutoscalingAPIGroupDSL.v1() error in Kubernetes native image generation
* Quarkus master.
* Camel Quarkus master.
* Graal 20.1.x.
* OpenJDK 11 (not labs).

```
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.fabric8.kubernetes.client.dsl.AutoscalingAPIGroupDSL.v1(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
        at parsing org.apache.camel.component.kubernetes.hpa.KubernetesHPAConsumer$HpaConsumerTask.run(KubernetesHPAConsumer.java:94)
Call path from entry point to org.apache.camel.component.kubernetes.hpa.KubernetesHPAConsumer$HpaConsumerTask.run():
        at org.apache.camel.component.kubernetes.hpa.KubernetesHPAConsumer$HpaConsumerTask.run(KubernetesHPAConsumer.java:93)
        at app//com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at app//com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:141)
        at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

### PR DESCRIPTION
**Pull request by ppalaga**
This helps to resolve https://github.com/apache/camel-quarkus/issues/1313

### CODE REVIEW

**Comment by geoand** [comment]
@ppalaga why was the substitution removed? Is the relevant code no longer in the client?

**Comment by ppalaga** [comment]
> @ppalaga why was the substitution removed? Is the relevant code no longer in the client?

Yes, the method was removed between 4.10.1 and 4.10.2

**Review by geoand — APPROVED** [review]

**Comment by jorsol** [comment]
> > @ppalaga why was the substitution removed? Is the relevant code no longer in the client?
> 
> Yes, the method was removed between 4.10.1 and 4.10.2

It was not removed, it was moved to a inner class.

Anyway it looks like `getClassLoader().loadClass` now works with GraalVM so the substitution is no longer required.

**Comment by ppalaga** [comment]
> It was not removed, it was moved to a inner class.

Good to know, thanks for the info!

**Pull request merged**
