### PR TITLE
Resolve config and env folders with user.dir

### LINKED ISSUE #16429: gradle quarkusBuild  has error : SRCFG00035: Failed to load resource
Since upgrading from to 1.13.x, run below command
```
./gradlew  quarkusBuild -Dquarkus.package.type=uber-jar  -Dorg.gradle.jvmargs=-Xmx256m
```
Gradle made a error: SRCFG00035: Failed to load resource, full stacktrace is:
```
> Task :processResources

> Task :classes
start copy some files...

> Task :inspectClassesForKotlinIC
> Task :jar

> Task :quarkusBuild
building quarkus jar

> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> java.lang.IllegalStateException: SRCFG00035: Failed to load resource

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
My system jdk version :
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
```
when I use `adoptjdk15-openj9` or downgrade quarkus version to `1.12.2.Final`, it' all fine.

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #16429

### CODE REVIEW

**Comment by gsmet** [comment]
Rebased on latest 1.13, let's see how CI goes.

**Comment by gsmet** [comment]
@radcortez is this PR for 1.13 only? The issue is not in `main`?

**Comment by radcortez** [comment]
> @radcortez is this PR for 1.13 only? The issue is not in `main`?

It yes, but I plan to solve it directly in SR Config, so I don't have to override stuff. I'm been working in the new config version and I'll submit a PR to `main` in the next couple of days.

**Review by gsmet — APPROVED** [review]
OK thanks for the explanation!

**Pull request merged**
