### PR TITLE
Add more netty tweaks to make reactor-netty work on top of quarkus-netty

### PR DESCRIPTION
**Pull request by ppalaga**
In the end I was able to make reactor-netty work with these tweaks. I hope they are acceptable. Could you please review, @cescoffier?

### CODE REVIEW

**Comment by cescoffier** [comment]
@ppalaga  The failure may be related. Can you check?

Also, were you able to use the event loops produced by Quarkus? 

I'm also concerned by the netty version alignment. We are strictly using the Netty version that Vert.x uses and adapt the configuration/substitution for this version. If at some point it becomes incompatible, we may break your extension.

**Comment by ppalaga** [comment]
> @ppalaga The failure may be related. Can you check?

The failures in `JVM Tests - JDK 11` and in `JVM Tests - JDK 11 Windows` jobs cannot be related because those jobs are JVM-only and the changes impact only native mode

> Also, were you able to use the event loops produced by Quarkus?

No I have not tried. At this stage, we concentrate on quickly porting as many Camel components as possible and we hope for being able to polish them later. BTW, is it technically possible to wrap vert.x HTTP client into Reactor interfaces - i.e. to make it implement Azure [HttpClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpClient.java)? It would perhaps be the most elegant option to support Azure,

> I'm also concerned by the netty version alignment. We are strictly using the Netty version that Vert.x uses and adapt the configuration/substitution for this version. If at some point it becomes incompatible, we may break your extension.

We test against Quarkus master and thus we have a chance learn about any damage quite early.

**Comment by cescoffier** [comment]
> No I have not tried. At this stage, we concentrate on quickly porting as many Camel components as possible and we hope for being able to polish them later. BTW, is it technically possible to wrap vert.x HTTP client into Reactor interfaces - i.e. to make it implement Azure HttpClient? It would perhaps be the most elegant option to support Azure,

Yes, especially if you use the Mutiny variant of the Vert.x Web Client (Mutiny has adapters for Reactor).

**Comment by gsmet** [comment]
@cescoffier I let you approve this PR or not, I'm not familiar enough with Netty to judge if it's a good thing or not.

**Comment by cescoffier** [comment]
I will have another look tomorrow. Today was too bumpy to look to anything that require a brain (so I did some Kafka stuff :-))

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
I don't know what's going on but I had to revert this due to issues like this in master:
```
11:33:24,397 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
To see how the classes got initialized, use --trace-class-initialization=io.netty.util.NetUtil
[quarkus-integration-test-reactive-mysql-client-999-SNAPSHOT-runner:27]     analysis:  46,047.62 ms,  2.35 GB
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.NetUtil the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.util.NetUtil got initialized use --trace-class-initialization=io.netty.util.NetUtil

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.NetUtil the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.util.NetUtil got initialized use --trace-class-initialization=io.netty.util.NetUtil

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/pull/14894/checks?check_run_id=1854174628

for this PR: https://github.com/quarkusio/quarkus/pull/14894

**Pull request merged**
