### PR TITLE
Arc - remove wildcard types from bean types of class-based beans

### PR DESCRIPTION
**Pull request by manovotn**
A complementary fix to #30412 and https://github.com/quarkusio/quarkus/pull/30415

I originally forgot to address a scenario where a class based bean was able to retain wildcard type as its bean type.
This is against CDI specification and should not occur (the TCK covers that as well).

### CODE REVIEW

**Comment by manovotn** [comment]
The failures looks related. In fact, it seem that HV is maybe using bean types as a basic for validation.
Though I am a HV rookie so maybe @yrodiere might know more? Any pointers are appreciated.

**Comment by yrodiere** [comment]
Hey @manovotn.

Hibernate Validator uses annotations on type parameters to configure value extractors (which can be CDI beans):

https://github.com/quarkusio/quarkus/blob/0c3c7e1fb5af229476ceb31346a4cd9c008ca8d8/extensions/hibernate-validator/deployment/src/test/java/io/quarkus/hibernate/validator/test/valueextractor

It would seem that your change is somehow removing the wildcard and corresponding annotation in the code above, leading HV to not detect the value extractor, leading (later) to a failure because HV cannot extract values from a `Container`.

Does that help?

**Comment by yrodiere** [comment]
Oops, the link to the code was truncated. I edited my comment.

**Comment by yrodiere** [comment]
Ah but wait, I found that in the HV code:

https://github.com/quarkusio/quarkus/blob/0c3c7e1fb5af229476ceb31346a4cd9c008ca8d8/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java#L39-L40

https://github.com/quarkusio/quarkus/blob/0c3c7e1fb5af229476ceb31346a4cd9c008ca8d8/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java#L146-L152

Maybe that hack is no longer necessary, and doing a simple request with `ValueExtractor.class` would work after your patch?

**Comment by yrodiere** [comment]
@manovotn Changing `.select(TYPE_LITERAL_VALUE_EXTRACTOR_WITH_WILDCARD))` to `.select(ValueExtractor.class)` doesn't seem to fix the problem. From what I can see, this bean:

```java
 @Singleton 
 public static class SingletonContainerValueExtractor 
         implements ValueExtractor<Container<@ExtractedValue ?>> { 
  
     @Override 
     public void extractValues(Container<?> originalValue, ValueReceiver receiver) { 
         receiver.value("someName", originalValue.value); 
     } 
 } 
```

Is simply ignored and not added to the CDI context... At least I don't see it in `Arc.container().beans`. I suspect the type `ValueExtractor` was ignored for that bean, and thus it was removed?

Maybe you should adjust your code to not *ignore* bean supertypes that contain wildcards, but just erase them (i.e. register the raw supertype `ValueExtractor` for `SingletonContainerValueExtractor` above)?

**Comment by manovotn** [comment]
@yrodiere according to [CDI spec](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#legal_bean_types):

> A parameterized type that contains a wildcard type parameter is not a legal bean type.

Remaining types should be preserved. There is a [TCK test](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/definition/bean/types/illegal/BeanTypesWithIllegalTypeTest.java) (and the test I added here with the `Eagle` type is the same) asserting a very similar scenario that you're showing where `ValueExtractor` would not be a valid bean type.

**Comment by yrodiere** [comment]
@manovotn Does that TCK test expect the 3 types to be `Eagle`, `Bird` and `AnimalHolder` (raw, not parameterized), or `Eagle`, `Bird` and `Object`?

If it's the former, that's exactly what I was asking for and it would work with HV.

---

If it's the latter, I don't really see the point of that limitation, since it would only remove a feature that users possibly rely on currently (and thus break backwards compatibility, by the way). Not sure we want to be that strict, at least not by default? Configuration flags to enable strict spec compliance comes to mind.

Alternatively, I suppose we could enable type matching (`.select()`) to take into account more types than what `Bean#getTypes` returns. I.e. `Bean#getTypes()` would only return a subset (`Eagle`, `Bird` and `Object`) of all the bean types that we consider when doing matches (`Eagle`, `Bird`, `AnimalHolder` and `Object`). That particular TCK test would then pass, as far as I can see, and we would preserve backwards compatibility at least to some extent.

If we want to break compatibility instead, in suppose that in the specific case of Hibernate Validator, we could use jandex to list all types extending `ValueExtractor` and retrieve those types explicitly. Which seems a shame to me considering that's usually CDI's job, but I guess if we don't have a choice...

**Comment by manovotn** [comment]
@yrodiere the TCK test explicitly checks that `AnimalHolder` is *not* a bean type. See [this line](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/definition/bean/types/illegal/BeanTypesWithIllegalTypeTest.java#L71).

I also brought this up with @mkouba and @Ladicek to get some more CDI expertise on this but the conclusion is what I am telling you.

> If it's the latter, I don't really see the point of that limitation...

That decision predates my engagement with the spec so I can only assume it's because of some typesafe resolution cases which would otherwise not work correctly.

Note that there has to be similar limitation in WFLY integration. Weld is for sure passing CDI TCKs so it will have the same "problem". I'd assume HV had to deal with it there as well?

> Not sure we want to be that strict, at least not by default? 

This was basically an oversight. We already did similar bean type removal for producer method/field we just forgot to apply this to class beans. With that in mind it's not as much of a breaking change as it is fixing an inconsistency of our behavior.

**Comment by yrodiere** [comment]
> @yrodiere the TCK test explicitly checks that AnimalHolder is not a bean type. See [this line](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/definition/bean/types/illegal/BeanTypesWithIllegalTypeTest.java#L71).

It does not. It checks that `AnymalHolder<?>` is not a bean type. It says nothing about the raw type. Only the assertion that checks the number of bean types gives us a clue about that. Hence my question.

> Note that there has to be similar limitation in WFLY integration. Weld is for sure passing CDI TCKs so it will have the same "problem". I'd assume HV had to deal with it there as well?

WildFly doesn't allow declaring `ValueExtractor`s as CDI beans. That's a Quarkus-specific feature.

> With that in mind it's not as much of a breaking change as it is fixing an inconsistency of our behavior.

It can be both.

On that note, I'll summon @gsmet to give his opinion: should I change HV to use Jandex to workaround this limitation we're introducing in Arc, or should we do something else?

**Comment by gsmet** [comment]
Well, I can't say I'm excited about this...

But if you all are saying what we do is against spec, I suppose we need to go the Jandex way.

**Comment by manovotn** [comment]
Note that this is related to https://github.com/quarkusio/quarkus/issues/28558 which is a tracker issue for (eventual) CDI Lite compliance in Quarkus 3.
I expect we'll find a lot more cases of missing validation compared to CDI TCKs as we haven't really executed them up until this point and they cover fair amount of rare cases such as this one here.

> It does not. It checks that AnymalHolder<?> is not a bean type. It says nothing about the raw type. Only the assertion that checks the number of bean types gives us a clue about that. Hence my question.

But that's how it works in CDI. If given type isn't a legal bean type, then you cannot use the raw type either.
See [Typesafe resolution](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#performing_typesafe_resolution) and [Assignability of parameterized and raw types](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#assignable_parameters).

> It can be both.

True, just pointing that out :)

**Comment by manovotn** [comment]
> Well, I can't say I'm excited about this...
> 
> But if you all are saying what we do is against spec, I suppose we need to go the Jandex way.

I don't mean to be the bad guy pushing this, I just saw and inconsistency and wanted to fix it, sorry @gsmet :-D

**Comment by Ladicek** [comment]
Just want to point out one thing: we do consider a "strict compliance" switch, which would be off by default (and we'd turn it on to pass the TCK). As we go through the TCK tests, I'm sure we'll stumble upon cases like this and we'll need to add the switch. The problem is that such switch is global. If we relied on our default relaxed behavior in our extensions, the extensions would start to fail once the user turns the switch on (which they may do for various reasons). So I believe we'll need our extensions to work correctly in the strictly compliant mode as well.

**Comment by yrodiere** [comment]
The initial policy of not adhering strictly to specs was not only about user experience, it was also about freeing up some time on our end, because those spec-mandated behaviors that we find uninteresting or even detrimental would not have to be implemented/dealt with. If extensions need to be compatible with both compliant and non-compliant mode, we do have to deal with those behaviors, and that means spending time that we won't spend innovating.

Worse, having to be compatible with both compliant and non-compliant mode is actually *more* effort than having to just be compatible with spec-compliant mode.

I understand where y'all are coming from, and I know complaining won't change anything. That won't stop me from being unhappy about it, though :)

Anyway, I just pushed a commit that sidesteps the problem.

**Comment by Ladicek** [comment]
Good point there. I was mainly thinking that the strictly compliant mode would disallow shortcuts such as omitting `@Inject` when a qualifier is present, or omitting `@Produces` when a qualifier is present. In such cases, achieving compatibility with both modes is pretty straightforward. I certainly would not want the two modes to have differences in how resolution or lookup behaves, that's a recipe for disaster.

**Comment by manovotn** [comment]
> I understand where y'all are coming from, and I know complaining won't change anything. That won't stop me from being unhappy about it, though :)

Understood. I appreciate the workaround you implemented :)
And thanks @Ladicek for chiming in as well.

**Comment by yrodiere** [comment]
The test failures are unrelated, see https://github.com/quarkusio/quarkus/pull/30501

**Comment by manovotn** [comment]
Good to know, I only re-ran it since I was surprised it didn't show up earlier.

We still need some review on this to get it on - @mkouba @Ladicek ? :)

**Review by Ladicek — APPROVED** [review]

**Review by mkouba — APPROVED** [review]

**Pull request merged**
