### PR TITLE
Make sure dev mode uses correct TCCL

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by cescoffier** [comment]
I'm not sure it would work for blocking routes.
Also, shouldn't we restore the TCCL once the response has been written?

**Comment by stuartwdouglas** [comment]
yea, I need something for the blocking pool as well.

We don't want to restore it because the original TCCL is wrong, vert.x survives dev mode restart, but the TCCL of the thread stays as the original. The threads should have this TCCL as the correct one, the original one basically represents a ClassLoader leak.

**Comment by stuartwdouglas** [comment]
I have updated this approach to instead do a best effort TCCL clean on restart.

**Comment by cescoffier** [comment]
It does not seem to work well (see CI log).

We may have to wait for the completion of all the tasks you enqueue in the pools (both worker and event loops).

**Review by gsmet — APPROVED** [review]
Merging after discussion with Stuart.

**Pull request merged**
