### PR TITLE
Reintroduce `CardPageBuildItem` constructor

### PR DESCRIPTION
**Pull request by gastaldi**
- This avoids breaking existing code

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Review by phillip-kruger — COMMENTED** [review]
We want to break all existing PR so that they use the new way. All current cards is fixed, so we only break PRs

**Comment by phillip-kruger** [comment]
@melloware just rebase and you should be ok

**Comment by gastaldi** [comment]
I opened this PR because of https://github.com/quarkiverse/quarkus-poi/actions/runs/4528900550/jobs/7976108596, but I think it can wait for the next 3.x release

**Comment by melloware** [comment]
Yep I plan on fixing all the cards one BETA2 is released.  Should be easy fixes.

**Comment by phillip-kruger** [comment]
@melloware You don't have to wait for beta2, the quarkiverse extension runs against 999-SNAPSHOT so you can fix main in poi right now. In fact I can do a PR later if you want ?

**Comment by gastaldi** [comment]
Actually `main` runs in the latest 3.x. The Ecosystem CI builds against 999-SNAPSHOT, which is what this PR was intended to fix :)

I'd prefer to keep `main` building against 3.0.0.Beta1. 

@melloware How about removing the DevUI integration from POI until the next 3.x is out?

**Comment by gastaldi** [comment]
I think it's okay to remove it temporarily, at least until the next 3.x release is out

**Pull request closed without merging**
