### PR TITLE
Bump RESTEasy to 4.5.8.Final 

### LINKED ISSUE #10133: Spring MVC @RequestParam encoding problem on UTF-8
I develop a rest API that serves city information for users. But I'm having problems with @RequestParam charset.  I sent some params to the controller which includes Turkish characters. And it didn't work as expected.

Some of the characters that I have Turkish character problem:
- ı
- ö
- ş
- ç

If you want to check that source code of this project: https://github.com/enesusta/tzone/tree/develop

Here is my request
```http
http://localhost:8080/district?name=diyarbakı
```

Here is our controller

```java
import com.github.enesusta.tzone.district.service.DistrictsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.io.UnsupportedEncodingException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.Executor;

@RestController
public class DistrictsController {

    @Autowired
    DistrictsService districtsService;

    @Autowired
    Executor executor;

    @GetMapping("/districts")
    public CompletionStage<List<Districts>> getDistricts() {
        return CompletableFuture.supplyAsync(districtsService.getDistricts(), executor);
    }

    @GetMapping(value = "/district", produces = "application/json;charset=utf-8")
    public CompletionStage<List<Districts>> getDistrictsByName(@RequestParam(name = "name") String districtName) throws UnsupportedEncodingException {
        return CompletableFuture.supplyAsync(districtsService.findDistrictsByCityName(districtName), executor);
    }
}
```

Here is our service:

```java
import com.github.enesusta.tzone.district.Districts;
import com.github.enesusta.tzone.district.repository.DistrictsRepository;
import org.jboss.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Locale;
import java.util.function.Supplier;

@Service
public class DefaultDistrictsService implements DistrictsService {

    private final static Logger logger = Logger.getLogger(DefaultDistrictsService.class);

    @Autowired
    DistrictsRepository districtsRepository;

    @Autowired
    Locale locale;

    @Override
    public Supplier<List<Districts>> getDistricts() {
        return () -> districtsRepository.getDistricts();
    }

    @Override
    public Supplier<List<Districts>> findDistrictsByCityName(String cityName) throws UnsupportedEncodingException {
        final String encodedParam = URLEncoder.encode(cityName, StandardCharsets.UTF_8);
        logger.info("encodedParam =" + encodedParam);
        final String upperCasedFirstCharacter = encodedParam.substring(0, 1).toUpperCase(locale);
        final String query = String.format("%s%s", upperCasedFirstCharacter, encodedParam.substring(1));
        logger.info("query = " + query);
        return () -> districtsRepository.findDistrictsByCityName(query);
    }
}
```

**Expected behavior**

```properties
name=diyarbakı
encodedParam = diyarbakı
query = Diyarbakı
```

**Actual behavior**

```properties
name = diyarbak%25C4%25B1
encodedParam  = diyarbak%25C4%25B1
query = Diyarbak%25C4%25B1
```

**Environment**

- uname -a

```
Linux DESKTOP-B3CNSC5 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- java -version

```bash
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
```

- mvn -version

```bash
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /mnt/c/Java/apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /home/phield/java/graalvm-ce-java11-20.0.0
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-18362-microsoft", arch: "amd64", family: "unix"
```

- quarkus-ver

```xml
<properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.5.2.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.5.2.Final</quarkus.platform.version>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
    <jacoco.version>0.8.4</jacoco.version>
  </properties>
```

### PR DESCRIPTION
**Pull request by ronsigal**
This is https://github.com/quarkusio/quarkus/pull/12232 but with RESTEasy version 4.5.8.Final. I don't have permission to edit https://github.com/quarkusio/quarkus/pull/12232 directly.

Fixes: #10133

### CODE REVIEW

**Comment by ronsigal** [comment]
"Initial JDK 11 Build' failed because RESTEasy 4.5.8.Final hasn't made it to https://repo.maven.apache.org/maven2.

**Comment by ronsigal** [comment]
RESTEasy 4.5.8.Final is now on https://repo.maven.apache.org/maven2. Could someone restart the tests?

**Comment by kenfinnigan** [comment]
done

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
That's awesome, but can you squash all these commits and add a `Co-authored-by` in the single commit? It seems to me that the upgrade only works when all these commits are applied, hence the request :wink:

**Comment by ronsigal** [comment]
Hi @gastaldi,

re: "squash all these commits and add a Co-authored-by in the single commit?"

Done.

**Comment by gastaldi** [comment]
@ronsigal excellent, but I thought the `Co-Authored-By` would mention @asoldano instead ?

**Comment by ronsigal** [comment]
re: "would mention @asoldano instead"

Ah, I thought maybe there was some standard requiring a Co-authored-by in any case. I doubt that @asoldano would be offended, but, sure, I can update it. ;-)

**Comment by ronsigal** [comment]
Done.

**Comment by gastaldi** [comment]
@ronsigal thank you, yeah, it's just to give him credit for his commits ;)

**Comment by ronsigal** [comment]
re: "it's just to give him credit for his commits"

Cool. Maybe I can leverage this into a larger bonus. ;-)

**Comment by kenfinnigan** [comment]
Is it also worth replacing https://github.com/quarkusio/quarkus/blob/master/extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java#L64-L69 with the static call to `ResteasyClientBuilderImpl` that was added to RESTEasy?

**Comment by ronsigal** [comment]
Hi @kenfinnigan,

re: "Is it also worth replacing"

Sorry, I'm not following ... . https://github.com/quarkusio/quarkus/blob/master/extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java#L64-L69 doesn't reference ResteasyClientBuilderImpl. What am I missing?

**Comment by kenfinnigan** [comment]
Sorry @ronsigal 

Those lines were added because we didn't have the ability to set the static, so I *think* they can be removed and replaced with a call to the static, similar to calling the `RestClientBuilderImpl` static to set the provider factory

**Comment by ronsigal** [comment]
Oh, man, I'm still not getting it. I blame 2020 because nothing else makes sense either. :(

**Comment by kenfinnigan** [comment]
No worries.

Instead of the lines I highlighted that peek into the RESTEasy provider factory and set it, just call `ResteasyClientBuilderImpl.setProviderFactory(clientProviderFactory);`

**Comment by ronsigal** [comment]
Mmmm, but ResteasyProviderFactory.instance and RestClientBuilderImpl.PROVIDER_FACTORY are two different things ... . I guess I still don't know the resteasy-client-microprofile code as well as I should.

**Comment by kenfinnigan** [comment]
They most definitely are different, but hijacking the RESTEasy provider factory for everything was the only way we could *hack it* so that the `ResteasyClientBuilderImpl` ended up with the provider factory we wanted it to.

With the static, we don't need those shenanigans and we can just set the static.

Sound ok?

**Comment by ronsigal** [comment]
Ahhhhhh. Yes, ok. ;-)

Would you like me to add that change to this PR?

**Review by asoldano — APPROVED** [review]
Given this is passing CI, I would deal with what @kenfinnigan is asking for (enhancements relying on the additions in 4.5.8.Final) in another PR.

**Comment by ronsigal** [comment]
@kenfinnigan , I've created issue #12325 "Remove unnecesary code from RestClientRecorder" and pull request https://github.com/quarkusio/quarkus/pull/12326 to remove that bit of code.

**Comment by gsmet** [comment]
@kenfinnigan any chance you could address the static thing? You're probably the one with the best understanding of this.

**Comment by kenfinnigan** [comment]
@ronsigal has provided a PR in #12326

**Pull request merged**
