### PR TITLE
Use the same default for accept backlog as Vert.x uses

### PR DESCRIPTION
**Pull request by geoand**
See https://github.com/eclipse-vertx/vert.x/blob/4.2.7/src/main/java/io/vertx/core/net/NetServerOptions.java#L46

### CODE REVIEW

**Comment by geoand** [comment]
cc @franz1981 @Sanne

**Review by cescoffier — APPROVED** [review]
ah ah... yes.... 0 was not right :-D

**Comment by geoand** [comment]
Damn defaults :)

**Comment by franz1981** [comment]
No idea, but I would add a test to don't get bitten in the future and always been in sync with the vert-x version

**Comment by geoand** [comment]
Right, we should indeed do that!

**Comment by Sanne** [comment]
I don't understand what the doc is saying, nor what zero would have
implied. Could we clarify this?

**Comment by franz1981** [comment]
Just a note for myself of the future (+ who is interested on this).
To understand how bad this can affect user experience, let's see what happen..
- 128 is the default value set for Unix OSs by Netty 4.1 if BACKLOG isn't set ie if it's != -1 (our Vert-x default)
- if set on 0 on NIO, Netty will pass it straight to the JDK impl and accordly to https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/sun/nio/ch/ServerSocketChannelImpl.java#L228 it will change it into 50 (meaning that EPOLL netty vs NIO behave differently, if configured by default)
- if set to 0 on EPOLL, instead it's used for real , see below more details

Assuming an existing http 1.1 hello world app, with this bug, effectively EPOLL native is using 0:
```bash
$ strace -e trace=listen -f java -Dquarkus.vertx.prefer-native-transport=true -jar ./target/quarkus-app/quarkus-run.jar
# ...noise...
[pid 1138300] listen(146, 0)            = 0
```
On recent kernels (past 2.2, see http://veithen.io/2014/01/01/how-tcp-backlog-works-in-linux.html and 
More details here: https://blog.cloudflare.com/syn-packet-handling-in-the-wild/ for more info) it means that pending accepts (fully established) during an overflow (that happen immediately with backlog of 0!!) cause clients to retries (`/proc/sys/net/ipv4/tcp_synack_retries times`) using an exponential backoff, that explain why incoming connections were getting slower and slower.

**Comment by geoand** [comment]
Thanks for.the analysis @franz1981 !

**Pull request merged**
