### PR TITLE
ArC - do not activate request context for Inialized/Destroyed events

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by manovotn — APPROVED** [review]

**Review by Ladicek — APPROVED** [review]
LGTM, just wondering -- how do we call the `@Initialized`/`@BeforeDestroyed`/`@Destroyed` observers for `@SessionScoped` or `@TransactionScoped` contexts?

**Comment by mkouba** [comment]
> LGTM, just wondering -- how do we call the `@Initialized`/`@BeforeDestroyed`/`@Destroyed` observers for `@SessionScoped` or `@TransactionScoped` contexts?

I don't think we fire those events for `@SessionScoped` which is only implemented in the undertow extension. I'm not sure about `@TransactionScoped` but keep in mind that it's not a built-in context so it's not mandatory ;-).

**Comment by manovotn** [comment]
> > LGTM, just wondering -- how do we call the `@Initialized`/`@BeforeDestroyed`/`@Destroyed` observers for `@SessionScoped` or `@TransactionScoped` contexts?
> 
> I don't think we fire those events for `@SessionScoped` which is only implemented in the undertow extension. I'm not sure about `@TransactionScoped` but keep in mind that it's not a built-in context so it's not mandatory ;-).

Don't know about session scoped, but transactional should perform this.
See for instance this - https://github.com/quarkusio/quarkus/blob/e1d474725b5f0f81c483c160f4cf8c1086b4aedd/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/CDIDelegatingTransactionManager.java#L76

**Comment by Ladicek** [comment]
Looks like we would still activate the request context for the transaction scope events, then?

**Comment by mkouba** [comment]
> Looks like we would still activate the request context for the transaction scope events, then?

Yes and I don't think it's a problem. In fact, the only problem is `@Initialized(ApplicationScoped.class)` which is fired during STATIC_INIT...

**Comment by Ladicek** [comment]
I think it's weird and shouldn't happen, but it doesn't bother me _that_ much :-)

**Comment by radcortez** [comment]
> > Looks like we would still activate the request context for the transaction scope events, then?
> 
> Yes and I don't think it's a problem. In fact, the only "problem" is `@Initialized(ApplicationScoped.class)` which is fired during STATIC_INIT...

Do we want to keep it at STATIC_INIT? My question here is about Config injection. Since we have different instances of Config for STATIC and RUNTIME, the visibility and configuration values are totally different and most likely result in unexpected behaviour.

**Comment by mkouba** [comment]
> > > Looks like we would still activate the request context for the transaction scope events, then?
> > 
> > 
> > Yes and I don't think it's a problem. In fact, the only "problem" is `@Initialized(ApplicationScoped.class)` which is fired during STATIC_INIT...
> 
> Do we want to keep it at STATIC_INIT? My question here is about Config injection. Since we have different instances of Config for STATIC and RUNTIME, the visibility and configuration values are totally different and most likely result in unexpected behaviour.

We need to keep it in STATIC_INIT because the CDI container is started in this phase and many extension rely on this behavior, i.e. they use the beans during this phase.

**Pull request merged**
