### PR TITLE
Auto-detect codestarts implemented languages

### PR DESCRIPTION
**Pull request by ia3andy**
it also:
- fixes the test that wasn't activating the examples to run them..
- fail if a pom.xml is present in a codestart for a non maven project

### CODE REVIEW

**Comment by ia3andy** [comment]
@maxandersen this PR is breaking the model compat. I've discussed with @gsmet and it's too late to have it in 1.7.0.Final. Can we assume for now that codestart model can be broken between minors for now?

**Comment by maxandersen** [comment]
It's still experimental and not default so we should be good for now.

**Comment by ia3andy** [comment]
@patriot1burke when this gets merged `missing-languages` will NOT be necessary anymore.

**Comment by ia3andy** [comment]
@aloubyansky if you lgtm it and CI passes, could you merge it, I'll be afk most of the afternoon.

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
