### PR TITLE
Remove jdk18-workarounds profile in TCKs of Rest Client

### LINKED ISSUE #21248: Clean up JDK 18 workarounds
### Description

Some workarounds were/are needed to get the EA job passing, which should be removed again if/when possible:
- https://github.com/quarkusio/quarkus/pull/21244
- ~~more to come~~ _edit: the above is the only real workaround_

Related: #20392

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by alexey-anufriev**
fixes #21248

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

Let's see what CI says

**Review by gsmet — CHANGES_REQUESTED** [review]
Problem is that CI doesn't actually test JDK 18+ right now given our Gradle issues.

I think this will have to be put on freeze until we get the early access build back on track.

**Comment by famod** [comment]
This won't work (Gradle issues aside) because resteasy classic still hasn't upgraded to httpclient 5, see also: https://github.com/quarkusio/quarkus/issues/21248#issuecomment-1083048549

**Comment by famod** [comment]
Closing as per https://github.com/quarkusio/quarkus/issues/21248#issuecomment-1480337310

Thanks anyway @alexey-anufriev!

**Pull request closed without merging**
