### PR TITLE
Upgrade to Hibernate Search 6.0.0.Final

### PR DESCRIPTION
**Pull request by yrodiere**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Should we also change the status of the extension here: https://github.com/quarkusio/quarkus/blame/master/docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc#L7 ?

It has been there for a while now or do you want it to bake for a bit longer?

**Comment by gsmet** [comment]
(Closed by mistake and reopened)

**Comment by yrodiere** [comment]
@gsmet I pushed a commit to at least stop referring to Search as "work in progress".

Regarding the extension itself, the only change I still had in mind was the handling of properties that accept a bean reference. Currently we only accept a FQCN, and we don't support referencing beans by name at all.

I believe some more advanced syntax such as `bean:beanName`/`class:com.mycompany.MyClass`, similar to [what we do in Hibernate Search](https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#configuration-bean-reference-parsing), might be better? But that would require some more work, and possibly would require that we break compatibility. So... in another PR?

**Comment by gsmet** [comment]
Sure, just wanted to be sure it wasn't an oversight!

**Pull request merged**
