### PR TITLE
Minor fixes for the create-extension mojo

### LINKED ISSUE #7180: create-extension mojo should accept absolute paths for the templatesUriBase option
ATM, setting `-DtemplatesUriBase=file:///some/absolute/path` or `<templatesUriBase>file:///${project.basedir}/my/path</templatesUriBase>` results an exception similar to the following:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.3.0.Alpha1:create-extension (default-cli) on project camel-quarkus-extensions: Could not read /home/james/Projects/camel-quarkus/extensions/pom.xml: /home/james/Projects/camel-quarkus/extensions/./home/james/Projects/camel-quarkus/extensions/../tooling/create-extension-templates does not exist. -> [Help 1]
```

Original report: https://github.com/apache/camel-quarkus/issues/688

A PR follows.

### LINKED ISSUE #7181: create-extension should generate application.properties for the integration test
create-extension should generate application.properties for the integration test.

Original report: https://github.com/apache/camel-quarkus/issues/694

A PR follows

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #7180 
Fix #7181

### CODE REVIEW

**Comment by ppalaga** [comment]
3b65464 fixed the failing test

**Comment by gsmet** [comment]
@aloubyansky can you have a look at that one? You recently made changes to this part of the code IIRC.

**Review by aloubyansky — APPROVED** [review]
Looks good, thanks!

**Comment by aloubyansky** [comment]
@ppalaga do you mind re-basing your PR? The failures don't seem to be related but still. Thanks!

**Comment by ppalaga** [comment]
61d5eb8 rebased

**Pull request merged**
