### PR TITLE
Docs: Move docs/README.adoc to docs reference

### PR DESCRIPTION
**Pull request by ebullient**

### CODE REVIEW

**Comment by maxandersen** [comment]
the content updates are good, but why split the easier to spot/more recognizable README.adoc over 2 separate docs and require newcomers to jump twice?

What am I missing?

**Comment by ebullient** [comment]
> the content updates are good, but why split the easier to spot/more recognizable README.adoc over 2 separate docs and require newcomers to jump twice?
> 
> What am I missing?

README.adoc is not used on the website. The other docs are. This avoids having to duplicate information in the README that is otherwise present in published docs.

**Comment by maxandersen** [comment]
+1 on this when conflicts resolved.

The linking works nicely on github so easy to find/navigate and the variables info is "advanced" info so not a loss for newcomers.

Actually just realized the readme.adoc is "hidden" inside `docs/src/main/asciidoc` rather than at docs level - thats for another PR :)

**Review by maxandersen — APPROVED** [review]
approve when rebased.

**Pull request merged**
