### PR TITLE
Use a safe version of maven-shared-utils

### LINKED ISSUE #18050: maven-shared-utils@3.2.1 Security Vulnerability: Command Injection
## Describe the bug
My company nexus blocked quarkus-ide-launcher due to the following Vulnerability.
https://snyk.io/vuln/maven:org.apache.maven.shared:maven-shared-utils@3.2.1

### Expected behavior
Should not have dependencies issues with quarkus latest version. 

### Actual behavior
(Describe the actual behavior clearly and concisely.)
please lock `org.apache.maven.shared:maven-shared-utils`  version to 3.3.3 or above.

Fixed in maven-shared-utils@3.3.3 
https://github.com/apache/maven-shared-utils/pull/40
https://issues.apache.org/jira/browse/MSHARED-297

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/schintha/.sdkman/candidates/maven/current
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/<userid>/.sdkman/candidates/java/11.0.11.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

```
gradle --version
------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.4 x86_64
```
## Additional context
 Repo: https://github.com/xmlking/micro-apps

image

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #18050

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
FWIW, this should be part of the next Maven 3.8.x version (WIP).

**Comment by aloubyansky** [comment]
@famod do you know version are they going to include? Is it 3.3.3, 3.3.4 or later?

**Comment by famod** [comment]
@aloubyansky the latest one, I hope. But it's still WIP, see latest messages here: https://lists.apache.org/thread.html/r72100477e39a12d2a66239d4c625d91cb9bcc8add72d2f910ce5ec26%40%3Cdev.maven.apache.org%3E

**Comment by aloubyansky** [comment]
Thanks. Reading https://issues.apache.org/jira/browse/MNG-7177, it seems like it's not entirely safe at least for the full blown Maven to use 3.3.4. I'll keep 3.3.3 for now. Once we upgrade to a Maven version that contains the fix, we can remove this constraint from our BOM.

**Comment by famod** [comment]
Makes sense, given that Jansi 2 seems to cause backporting issues and given that this was bumped in 3.3.4 (but not yet in 3.3.3).

**Pull request merged**
