### PR TITLE
Fix expired certificates

### PR DESCRIPTION
**Pull request by geoand**
This was done by running: `integration-tests/rest-client/generate-trust-store-for-bad-ssl.sh`

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier @sberyozkin didn't you guys have something to generate a certificate at build time somewhere?

**Comment by cescoffier** [comment]
During Quarkus build time? That would be very weird. 

During a maven phase, I don't have anything but that could be useful.

**Comment by gsmet** [comment]
Yeah I was thinking of Maven. I thought we had something.

**Comment by gsmet** [comment]
@geoand do you mind just disabling the tests and we will let @michalszynkiewicz deal with it?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/24692

**Comment by michalszynkiewicz** [comment]
hmm... at least some of these tests use badssl.com which seems to be down

**Comment by michalszynkiewicz** [comment]
I'm not the author of the tests but will try to replace badssl.com with something that is set up during the tests

**Comment by michalszynkiewicz** [comment]
Actually it is not resolvable, not down.

**Comment by michalszynkiewicz** [comment]
https://github.com/chromium/badssl.com/issues/500 - someone is apparently working on it

**Comment by michalszynkiewicz** [comment]
@geoand maybe we could reopen this PR retry it when the DNS for badssl is resolved?

**Comment by geoand** [comment]
Sure ywah

**Comment by gsmet** [comment]
Our tests shouldn't depend on an external service that we don't manage.

**Comment by geoand** [comment]
Oh, those are still disabled? Then yes, I'll do that

**Comment by geoand** [comment]
CI is passing, should we get this in?

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged. If the new certificates can expire again, we should probably document how to generate them.

**Comment by geoand** [comment]
Yes, indeed

**Comment by gsmet** [comment]
Adding the instructions in the description of the PR is enough IMHO. We will find them easily.

**Comment by geoand** [comment]
Done :)

**Pull request merged**
