### PR TITLE
Introduce an attribute for the platform groupId

### PR DESCRIPTION
**Pull request by gsmet**
/cc @inoxx03 here you go for what you requested.

@ebullient I'm a bit concerned by the first commit: your metadata checking tool reported some errors but apparently only because I modified the file. I think we should at least run it on all the files that are around once to fix the failures. And maybe we should also trigger a full run when it is modified.

@inoxx03 the second commit concerns me a bit. It's not the first time that I fix a formatting error that goes unnoticed for a long while. At least from time to time, the doc team should have a look at the output of the Maven doc build as some errors are unfortunately logged at debug level and are not triggering a build failure.

### CODE REVIEW

**Comment by ebullient** [comment]
> /cc @inoxx03 here you go for what you requested.
> 
> @ebullient I'm a bit concerned by the first commit: your metadata checking tool reported some errors but apparently only because I modified the file. I think we should at least run it on all the files that are around once to fix the failures. And maybe we should also trigger a full run when it is modified.
> 

Yes. I am trying to facilitate incremental improvement by not spamming the universe with all of the errors. We can trigger analysis of everything (it's a change in parameter when you invoke the test), but I think that's an activity for a different PR.

**Comment by gsmet** [comment]
@inoxx03 @michelle-purcell I let you check it's all good for you on the doc side and that it does what you wanted?

**Review by rolfedh — APPROVED** [review]
LGTM

**Comment by inoxx03** [comment]
Many thanks for implementing this change @gsmet
I think this is exactly what we need.
I'd like to give our writers a chance test this against the downstream publishing tools, but I am fairly sure that this change will allow us to reuse the automated upgrade guide (and potentially other pieces of content) downstream without the need to change the groupId manually.

**Review by inoxx03 — APPROVED** [review]

**Review by michelle-purcell — APPROVED** [review]
@gsmet - Thanks. LGTM too, providing @rolfedh confirms it's usable downstream too, which it hopefully should be. :+1:

**Review by ebullient — APPROVED** [review]

**Comment by rolfedh** [comment]
> @gsmet - Thanks. LGTM too, providing @rolfedh confirms it's usable downstream too, which it hopefully should be. +1

Yes, it's usable downstream, too. Please go ahead.

**Pull request merged**
