### PR TITLE
Fix gradle test assertion

### PR DESCRIPTION
**Pull request by glefloch**
The test assertion was wrong but the ci was OK. 
I fixed the test.

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]
Wondering how this did pass the CI.

**Comment by gsmet** [comment]
Hum. Yeah, I think we need to understand how it passed CI.

**Comment by glefloch** [comment]
It looks like tests overlap themselves. Running test with `maxParallelForks = 1` shows the error. I set the flag in the test task.

**Comment by gsmet** [comment]
I'm torn about this one. We have CI green and we're changing a test and CI is still green.

We need to get to the bottom of this.

**Comment by glefloch** [comment]
I reverted the test fix and even with the `maxParallelForks = 1`, CI is green..
Should I open an issue ?

**Comment by glefloch** [comment]
I pushed the commit that only fixed the test.

I tested multiple things but I was never able to make the test fail in CI. 
On my local machine, the test with the wrong assertion always fail.
First, I thought there was some kind of race condition as tests may run in parallel, I tried running them sequentially but the test was still ok, I even tried to only run this test, and it's still ok. 
I tried to migrate it in java but always ok. 

The only difference between the main ci job and the snapshot job (that fails) is the cache but I don't know how it could be related. 

have you any idea @gsmet @aloubyansky ?

**Comment by aloubyansky** [comment]
I'll try to reproduce it one of these days.

**Comment by gsmet** [comment]
Let's see if it improves the snapshot deployment situation.

**Pull request merged**
