### PR TITLE
Upgrade to Hibernate ORM 6.2.7.Final and Hibernate Reactive 2.0.4.Final

### LINKED ISSUE #34986: Quarkus is affected by criteria query issue in Hibernate
### Describe the bug

Quarkus 3.2.2 is affected by [HHH-16905](https://hibernate.atlassian.net/browse/HHH-16905). This is fixed in Hibernate 6.2.7, Quarkus needs to adopt this version.

This issue is affecting Keycloak that consumes Hibernate through Quarkus.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #34986

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
Nice, this will also fix https://hibernate.atlassian.net/browse/HHH-16845! (verified via dep-mgmt override on top of Quarkus 3.2.2)

**Comment by Sanne** [comment]
@famod thanks for verifying! Let me know if there's more "fixes" I should add to the description, I might lose track of them.

**Comment by geoand** [comment]
Although `VertxBlockingMutinyTest` is very flaky lately, I'll the job again just in case

**Comment by famod** [comment]
> @famod thanks for verifying! Let me know if there's more "fixes" I should add to the description, I might lose track of them.

I'm not aware of other quarkus issues (filed by other users) that are caused upstream in Hibernate, but we didn't open a quarkus issue for HHH-16845, so I have nothing to add at this point.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
