### PR TITLE
Switch Vert.x HTTP to @ConfigMapping

### LINKED ISSUE #34292: null keys in YAML config break JSON compatibility
### Description

I'm not sure how common this is in general, though I doubt I'm the only platform engineer on Earth who does this: when deploying applications which accept YAML configuration, I quite often feed in the configuration as JSON -- which is also always valid YAML (with yes, pedantically, a few minor exceptions that don't normally matter in real life as long as you use UTF-8).

(Why? In short, generally it's less ambiguous and is compatible with more tools. More convenient to canonicalize ([RFC 8785](https://www.rfc-editor.org/rfc/rfc8785)), and therefore to validate. Particularly in a microservices environment, using a tool to manage and generate config files is fairly standard, and I just tend to find that JSON makes that easier.)

This normally works very well with most applications, but unfortunately in Quarkus there is a design element that makes this difficult. Let's take this example from the guide: https://quarkus.io/guides/config-yaml#configuration-key-conflicts

In the underlying properties representation we have `quarkus.http.cors=true` and `quarkus.http.cors.methods="GET,PUT,POST"`.

When we attempt to represent these as YAML this is of course impossible, as the config value at `['quarkus']['http']['cors']` can't simultaneously be `true` and `{"methods": "GET,PUT,POST"}`.

There is a hack in the YAML representation to work around this, where instead the `true` value is placed under `['quarkus']['http']['cors'][null]`. Unfortunately, while all JSON is valid YAML, the reverse is not true. This YAML is unrepresentable in JSON -- all keys must be strings, so `null` is impossible to express.

Even with natively YAML-based tooling, if any kind of schema or type system is used, the use of `null` as a key always stands out as an awkward exception.

In an application which parsed YAML natively as its config format, this would likely never have become a problem in the first place -- the design would simply use non-overlapping keys and call the first property `quarkus.http.cors.enabled` instead of the unrepresentable `quarkus.http.cors`.

(I'm not trying here to get into whether the `methods` property in the same example should really be an array. Clearly people find the Java properties representation valuable, and clearly some compromises have to be made to be compatible with both formats.)

### Implementation ideas

What I would like to suggest, though, is that a change could be considered to allow the more compatible key `quarkus.http.cors.enabled` either as a replacement or an alias for the unrepresentable `quarkus.http.cors` key (along with similar aliases for any other keys with the same "overlapping" problem), so that the YAML config representation remains compatible with JSON.

As this is not really a "bug", though I do think it's a surprising and counterintuitive design, I've raised this as an improvement.

To be fair I should say we do have a workaround in place already, which is to put the `quarkus.http.cors=true` in the built-in `application.yaml`, separately from the other runtime config which is injected by the config system. This does seem to work -- the two files do seem to merge correctly, at least in the current version -- so this is hardly a critical issue for us. It would definitely be much nicer not to have to do this, though.

Thanks for reading :bow:

### PR DESCRIPTION
**Pull request by radcortez**
- Part of #32209
- Fixes #34292

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@radcortez I'm pretty sure the fact that you fixed `https://github.com/quarkusio/quarkus/issues/34292` will require a note in the migration guide?

**Comment by radcortez** [comment]
Right now both properties `quarkus.http.cors` and `quarkus.http.cors.enabled` are valid, but only`quarkus.http.cors.enabled` shows up in the documentation. The old `quarkus.http.cors` is not deprecated yet, so whoever uses it shouldn't notice any difference.

The plan is to support https://github.com/quarkusio/quarkus/issues/33877, so we can deprecate this (and other properties) and provide more direct feedback to the user.

Regardless, I'll add a note.

**Comment by mkouba** [comment]
@gsmet @radcortez Shouldn't we label this PR as a breaking change?

**Comment by gsmet** [comment]
Yeah, I noticed this problem in my Quarkus GitHub App extension but with the runtime config.

I never actually considered the config an API (especially given it's in the `runtime` module) but unfortunately it was the most convenient way to get the values.

I'm not sure if we should ask people to move to the method or if we should advertise a better way of getting this config (maybe by getting the Vert.x instance and get the value from there if possible).

@radcortez @cescoffier thoughts?

**Comment by mkouba** [comment]
> I never actually considered the config an API (especially given it's in the `runtime` module) but unfortunately it was the most convenient way to get the values.

Well, I'd say that it's the only type-safe way... The truth is that the content of the `io.quarkus.vertx.http.runtime` package should not be considered part of the public API but since the class was `public` and there's usually no other "official" way...

> I'm not sure if we should ask people to move to the method or if we should advertise a better way of getting this config (maybe by getting the Vert.x instance and get the value from there if possible).

But that would only solve the runtime part, what about the build steps?

**Comment by cescoffier** [comment]
In my opinion, it’s a breaking change. 

Unfortunately, there is no way to get the values from the vertx instance. Keeping a VertxOption instance around sounds a bit overkill (and it’s not a one-to-one mapping).

**Comment by radcortez** [comment]
Hum... good point.

In reality, because these classes are public, we have no idea if they are being used outside our own internal code. Probably we need to consider that any Config root / mapping classes are public APIs.

**Comment by mkouba** [comment]
> In reality, because these classes are public, we have no idea if they are being used outside our own internal code. Probably we need to consider that any Config root / mapping classes are public APIs.

It's like public build items. You can consume it in your build steps. Moreover, `BUILD_AND_RUN_TIME_FIXED` configs can be injected in beans, etc.

**Comment by radcortez** [comment]
> It's like public build items. You can consume it in your build steps. Moreover, `BUILD_AND_RUN_TIME_FIXED` configs can be injected in beans, etc.

Exactly. But we usually always treat this as internal APIs. Build items are bit more obscure for the regular users, so I guess that is not a big deal. I agree that we may see more users relying on the Config objects.

**Comment by michalvavrik** [comment]
This feels like a stalemate. Quarkus knows whether someone injects config classes. Can't Quarkus generate config classes for few releases only if necessary and log warning that these classes should be migrated to the `@ConfigMapping`? It should be easy to keep consistency for few releases because you only need to maintain existing properties, new properties can only be added to the `@ConfigMapping`. Would it be possible for `@ConfigMapping` and config classes to live together and provide same information?

Is there a Quarkus issue where this migration is tracked, or a plan for the `@ConfigMapping` migration, please?

I'm mostly interested because QE test framework needs to detect all used build time properties before Quarkus build and I don't want to do it in 2 ways. But after reading https://github.com/quarkusio/quarkus/issues/32209 it seems there also are performance objectives.

**Comment by radcortez** [comment]
> This feels like a stalemate. Quarkus knows whether someone injects config classes. Can't Quarkus generate config classes for few releases only if necessary and log warning that these classes should be migrated to the `@ConfigMapping`? 

Eventually, we will have to figure something out here. I didn't want to put a warning message that would reach the user and create unnecessary noise. An option could be to do it at compilation time of Quarkus, or of an Extension, but not a Quarkus App.

> It should be easy to keep consistency for few releases because you only need to maintain existing properties, new properties can only be added to the `@ConfigMapping`. Would it be possible for `@ConfigMapping` and config classes to live together and provide same information?

Yes they can, but the extension would need to pick which one to use, because it codes directly against the specific type.

> Is there a Quarkus issue where this migration is tracked, or a plan for the `@ConfigMapping` migration, please?

Not at the moment. We talked about this a few times, but we also had a few issues, like this one, that had to be reverted. I believe things should be better now after some improvements we did with performance.

> I'm mostly interested because QE test framework needs to detect all used build time properties before Quarkus build and I don't want to do it in 2 ways. But after reading #32209 it seems there also are performance objectives.

What are you doing exactly? Maybe I can help.

**Comment by michalvavrik** [comment]
> What are you doing exactly? Maybe I can help.

We run many tests with different configuration combinations (and test methods) in order to tests many features and scenarios on same application classes and with same dependencies. When they are native tests, we need to know whether we can reuse native executable (which can spare significant test execution time). So far we use hardcoded list, but it is absolutely incomplete and sometimes properties are moved ... I watched this issue as my plan was to build `SmallRyeConfig`, get all config mappings and check build time / runtime. It can be done for config classes, but don't want to invest time into deprecated solution. I don't want spam this PR, so I can ping you at some other time directly.

**Pull request merged**
