### PR TITLE
Don't require a global body handler for vertx-graphql

### LINKED ISSUE #18598: Extension quarkus-vertx-graphql interferes with extension quarkus-resteasy-multipart
## Describe the bug
After upgrading to Quarks 2.0 I discovered an issue with my application that uses the extensions quarkus-vertx-graphql and quarkus-resteasy-multipart. While running my application in devmode if I perform a multipart form data post to a JAX-RS endpoint none of the parts are received by the JAX-RS endpoint. If i remove the quarkus-vertx-graphql dependency from my application it works fine. The application also works fine in production mode when I directly run the quarkus-run.jar.

### Expected behavior
The multipart form parameter parts are available regardless of what mode the Quarkus application is run in or if the quarkus-vertx-graphql extensions is included in the application. 

### Actual behavior
The request reaches the endpoint but no parts are available.

## To Reproduce

Reproducer: https://github.com/aaronanderson/quarkus-multipart

I experimented with the 2.0.1.Final version of the VertxGraphqlProcessor class and if I comment out this line and build the extension it fixes the issue:

https://github.com/quarkusio/quarkus/blob/9e0736c5091bc34791ceffe6b760f111af0b63bf/extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java#L84

I am not sure what the RequireBodyHandlerBuildItem does or why it would affect the multipart extension. I did confirm it is required for the vertx-graphql extension to work.

1. Check out the reproducer build and run it. 
2. Remove the quarkus-vertx-graphql or modify the VertxGraphqlProcessor class as mentioned above to successfully run the test.

### Output of `java -version`
```
java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Corretto-16.0.1.9.1 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Corretto-16.0.1.9.1 (build 16.0.1+9, mixed mode, sharing)
```

### Quarkus version or git rev
2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn -version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/xxxx/apache-maven-3.8.1
Java version: 16.0.1, vendor: Amazon.com Inc., runtime: /home/xxxx/jdk-16
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-051300-generic", arch: "amd64", family: "unix"

## Additional context
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #18598

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by geoand** [comment]
How about adding a test so we ensure this doesn't happen again?

**Comment by jmartisk** [comment]
@geoand  That will be a bit tricky, the problem basically is that `resteasy-multipart` breaks when the body handler is installed, so the test would have to include both `resteasy-multipart` and `quarkus-vertx-graphql` extensions, I'm not sure if there is an existing test module where this could be added without being "polluting", as in introducing unnecessary dependencies between extensions. Do you have an idea? :)

**Comment by geoand** [comment]
Hm, it seems like `QuarkusDevModeTest` does not have the `setForcedDependencies` option that `QuarkusUnitTest` does (although it should likely be easy to add it). 
That mode allows a test to add stuff on the classpath only for that specific test

**Comment by jmartisk** [comment]
To be able to verify that resteasy-multipart doesn't break, we would need a test-compile-time dependency on it, not one added dynamically. The test would need to contain a REST endpoint or something.

**Review by gsmet — APPROVED** [review]
Not saying we shouldn't add a test but let's merge this now to get it in for 2.1. We can add a test later if we have the proper infrastructure.

**Pull request merged**
