### PR TITLE
Fixes #2537 Add Extension for Camel-AWS-SQS

### LINKED ISSUE #2537: Add Extension for Camel-AWS-SQS
**Description**
To support AWS SQS component from Camel.

### PR DESCRIPTION
**Pull request by oscerd**
@gnodet @lburgazzoli @gsmet

### CODE REVIEW

**Comment by lburgazzoli** [comment]
LGTM

Maybe we should evaluate a camel-aws-common in case we add support for more services and all requires common classes to be made accessible through reflection and so on.

**Comment by oscerd** [comment]
Yes, sure. I'm planning to add more extension I can from the camel-aws-* family and then extract the common part

**Comment by kenfinnigan** [comment]
@lburgazzoli how does this play into the idea of having Camel extensions for Quarkus in Camel itself? Is adding here a temporary solution?

**Comment by lburgazzoli** [comment]
@kenfinnigan yes it is a temporary solution until we sort out the "Quarkus Ecosystem Model"

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
