### PR TITLE
Provide a way to set the TCCL in @BuildStep

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This allows for the TCCL to automatically set the TCCL
in a build step. We can't do it for everyone as the metadata
needed to build this CL is created by @BuildStep methods.

Any build step that needs to load application classes should
use this flag to get a transformation safe ClassLoader.

### CODE REVIEW

**Comment by gsmet** [comment]
There are test failures that look related.

**Comment by stuartwdouglas** [comment]
The other way to do this would be via an 'opt out' based approach, so all the pre-classloading build steps would not have their TCCL set.

**Comment by jaikiran** [comment]
Hello @stuartwdouglas 

> Any build step that needs to load application classes

Have things changed when it comes to build steps (as part of build processors) loading application classes? I'm still not fully caught up with Quarkus augmentation and other details, but the documentation that I had read previously (and even the live one) states (https://quarkus.io/guides/writing-extensions#bootstrap-three-phases):

> Augmentation
>     This is the first phase, and is done by the Build Step Processors. 
> **These processors** have access to Jandex annotation information and can parse any descriptors 
> and read annotations, but **should not attempt to load any application classes**.

**Comment by stuartwdouglas** [comment]
That has changed, unfortunately it turns out that there are cases where do no need to load application classes. This approach allows us to load them in a temp class loader, so they won't affect transformation, in much the same way that the JPA spec does.

**Comment by jaikiran** [comment]
Understood. Thank you.

**Review by dmlloyd — APPROVED** [review]

**Pull request merged**
