### PR TITLE
Test Quarkus with OpenJDK 14 instead of 13

### PR DESCRIPTION
**Pull request by gsmet**
Waiting for CI running in my fork.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
And don't forget to reply to https://twitter.com/mreinhold/status/1243214596854276097 if everything is green :wink:

**Comment by geoand** [comment]
Seems like your local GH Actions hasn't run the tests yet...

**Comment by geoand** [comment]
One of the Kafka tests is failing, but I'm not it's a transient failure or if it's actually due to JDK 14. @gsmet mind restarting the tests when you have a chance?

**Comment by gsmet** [comment]
Yeah, guys, no need to check my fork's GH actions, I'm handling it :).

**Comment by geoand** [comment]
But we want to know :P

**Comment by gastaldi** [comment]
Don't tell me what to do :stuck_out_tongue_closed_eyes: 

_refreshes build page_

**Comment by gsmet** [comment]
This one is now ready for review.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Did we ever respond to the tweet that Quarkus CI passes with JDK 14 now?

**Comment by gastaldi** [comment]
No, but I think that will be true in the next release only?

**Comment by geoand** [comment]
Well, the tweet says all tests green, so it's just about CI I would say :). 
Plus I am pretty sure Quarkus `1.3.1.Final` will work with Java 14, I don't recall us fixing any compatibility issues.

**Comment by gsmet** [comment]
I think 1.3.1 works with JDK 14 but all our tests weren't green.

1.4 will be the first version with all tests green.

**Pull request merged**
