### PR TITLE
KOGITO-5560 remove 'preview'label from community website

### PR DESCRIPTION
**Pull request by tarilabs**
Draft as pending Kogito upstream PR first: kiegroup/kogito-runtimes#1462

https://issues.redhat.com/browse/KOGITO-5560

### CODE REVIEW

**Comment by gsmet** [comment]
@tarilabs maybe one PR is enough?

**Comment by tarilabs** [comment]
how do I "backport" @gsmet to previous branches, please?

**Comment by gsmet** [comment]
You don't. I do it and we don't maintain all branches anyway. I will add the backport label for the branches we still maintain.

**Comment by tarilabs** [comment]
Sorry @gsmet I didn't realize https://github.com/quarkusio/quarkus/pull/18905#issuecomment-884308733 that.
OK, thank you, and sorry again for unintended noise.

**Pull request closed without merging**
