### PR TITLE
Subscription Handler - Allow multiple connections

### LINKED ISSUE #17422: SmallRye GraphQL Subscription Concurrent Connections
## Describe the bug
Concurrent connections in the Quarkus-Smallrye-GraphQL library do not work. Once a single client is connected and subscribed, no other clients are able to receive data from the socket. The socket allows the connection but no data is sent. Also, should one client send a malformed payload that causes an exception, all clients fail and disconnect.

### Expected behavior
Multiple clients should be able to connect at the same time

### Actual behavior
Once a client connects, any other clients are blocked and do not receive any data. Though the WebSocket does open and function, just no data.

## To Reproduce

https://github.com/Volxz/quarkus-smallrye-graphql-test

1. Run the  quarkus app
2. Open two browser tabs and navigate to the graphql-ui
3. Start two subscribers that are running concurrently

```graphql
subscription {
    pong(p: {startingNumber: 5}) {
    pongNumber
  }
}
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
```Linux NotAComputer 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
### Output of `java -version`
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
### Quarkus version or git rev
``` 
2.0.0.Alpha3 
```
## Additional context
I believe this may be a problem with the AtomicReference specified in [SmallRyeGraphQLSubscriptionHandler](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLSubscriptionHandler.java) as there is only one instance allowed of a subscription. I could be completely wrong and am currently hacking on master. I am also looking into the Smallrye library.

### PR DESCRIPTION
**Pull request by ethan-gallant**
This PR allows multiple connections to be concurrently handled by the Application Scoped GraphQL Subscription Handler.

For more details see #17422

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]
This PR will require a squash if accepted. Thanks.

**Comment by phillip-kruger** [comment]
Hi @ethan-gallant - thanks for this. I am not sure it's working yet. Maybe you can try this in your environment (basically the gif from https://github.com/quarkusio/quarkus/pull/17191)

 - clone https://github.com/phillip-kruger/graphql-experimental
 - change the version in pom.xml to 999-SNAPSHOT (to run against your local fix)
 - cd subscription-example
 - mvn clean install quarkus:dev

This will start a example application.

Now open 3 windows with localhost:8080/q/graphql-ui

- First window is to add a new person:

```
mutation addPerson {
  addPerson(p:{id:2 names:"Koos" surname:"van der Merwe"}){
    id
  }
}
```
- Second and third to listen for new people, one listen for the name and the other for the surname

```
subscription listenForNewPeople {
  personAdded{
    id
    surname
  }
}
```

and 

```
subscription listenForNewPeople {
  personAdded{
    id
    name
  }
}
```

Then start the subscription and add a person. For me I still only get one notification. 

I'll also look into this a.s.a.p, but if you are keep to look at it in the mean time. Like I said, this used to work, so something between Alpha2 and 3 and/or smallrye graphql 1.2.0 and 1.2.1

**Comment by ethan-gallant** [comment]
Hi @phillip-kruger it works as expected for me and I get the following after doing the mutation
image

How it worked before puzzles me quite a bit as the SmallryeGraphQLSubscriptionHandler is initialized at startup by the processor/recorder yet there is only one instance of the 
`private final AtomicReference<Subscription> subscriptionRef = new AtomicReference<>();`

My guess is something to do with how runtime recorder beans are initialized changed meaning that instead of multiple classes being created, only one instance is created. To be honest though, I have no idea how it worked before and I'm completely puzzled.

**Comment by phillip-kruger** [comment]
Awesome ! Then it must be my testing that is wrong. I'll double-check. Can you squash your commits ?

**Review by phillip-kruger — APPROVED** [review]
Thanks @ethan-gallant . I confirmed that this is working. Thanks :)

**Pull request merged**
