### PR TITLE
Introducing Quarkus Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by Gurubaseio**
Hello Team,

This PR is a friendly notification that the [Quarkus Guru](https://gurubase.io/g/quarkus) has been added to Gurubase. The Quarkus Guru uses data from this repository and the [documentation](https://quarkus.io) to answer questions by leveraging the LLM.

Gurubase is a centralized, RAG-based learning and troubleshooting assistant platform. Each "Guru" is equipped with custom knowledge to answer user questions based on data collected for that tool. More information can be found in [this repo](https://github.com/getanteon/gurubase).

This PR updates the README to indicate that Quarkus users can now ask questions to Quarkus Guru. As shown in the [Used By](https://github.com/getanteon/gurubase?tab=readme-ov-file#used-by) section, over 100 open-source repositories currently showcase their Guru in their README.md.

By default, there are three possible actions:
1. If you dislike it, we can immediately disable Quarkus Guru in Gurubase and remove this PR.
2. If you like it but don’t want to add it to the README, we can remove this PR or include it in another place you prefer.
3. If you’re happy with it, we can keep it as is and merge the PR.

Although this PR is created by the Gurubase Notifier account, the team monitors it and will answer any questions you may have.

**Note:** If you consider this PR a time-waster, apologize for the inconvenience. Developers often request us to create a Guru for the tools they use. Once we create it, we notify the maintainers to inform them and seek their approval.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
This is pretty cool.

**Comment by gastaldi** [comment]
That's awesome! Can it be enhanced with data from https://docs.quarkiverse.io too?

**Comment by geoand** [comment]
Great stuff!

**Comment by maxandersen** [comment]
Really like the idea but yeah would love to hear if it could include quarkiverse repos and docs then it would be a truly big value add. if you need a list of URLs / repos we can definitely provide something based on metadata we have available.

**Comment by kursataktas** [comment]
Hello Everyone,

Yes, I can add https://docs.quarkiverse.io/ as well. I crawled the site and found [567 pages](https://docs.google.com/document/d/1Wyo5lFlOhG2voTTWd94Ch2Sr4NSkDYcSnRcsGRDEnEk/edit?usp=sharing). Since some of them are the same page for different versions, I haven't filtered them yet. Maybe you can help me with that.

You can also manage Quarkus Guru and its data sources. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). I highly recommend this option as it allows you to make future changes as much as you want.

**Comment by phillip-kruger** [comment]
We can probably also add smallrye documentation? I created an issue to add me to the quarkus guru maintenance. https://github.com/getanteon/gurubase/issues/16

**Comment by phillip-kruger** [comment]
@Gurubaseio please squash your commits

**Comment by gsmet** [comment]
@kursataktas when I ask `Can I use Bean Validation with Quarkus?`, sources are a bit odd (look for `chevronDown`):

Screenshot from 2024-12-13 11-48-21

**Comment by Gurubaseio** [comment]
> @Gurubaseio please squash your commits

I accidentally corrupted the Git history, so I opened a new [PR](https://github.com/quarkusio/quarkus/pull/45113) and am closing this one.

**Comment by kursataktas** [comment]
> @kursataktas when I ask `Can I use Bean Validation with Quarkus?`, sources are a bit odd (look for `chevronDown`):
> 
> Screenshot from 2024-12-13 11-48-21

We’ve been experiencing this issue with the meta titles of the sources for a while and are working to resolve it. However, it shouldn’t affect the quality of the generated answers. Can you confirm that?

**Comment by gsmet** [comment]
@kursataktas yes, it's purely esthetic, the answer was all good.

**Pull request closed without merging**
