### PR TITLE
Execute QuarkusTest**Callback when running QuarkusIntegrationTest

### LINKED ISSUE #28402: QuarkusTest**Callback not executed when running QuarkusIntegrationTest
### Describe the bug

When running a `@QuarkusIntegrationTest` the registered QuarkusTest**Callback are not executed. 

Setup:

```
integrationTest
|-src
|   |-MyIntegrationTest.java  (extends MyQuarkusTest)
|-resources
    |-META_INF
        |-services
            |- io.quarkus.test.junit.callback.QuarkusTestBeforeEachCallback  (same as in test)

test
|-src
|   |-MyQuarkusTest.java
|-resources
    |-META_INF
        |-services
            |- io.quarkus.test.junit.callback.QuarkusTestBeforeEachCallback

```

### Expected behavior

The test callback should also be executed when running integration tests.

### Actual behavior

When running a `@QuarkusIntegrationTest` the registered QuarkusTest**Callback are not executed. 

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/28402

Note that I had to add two "expensive" tests to verify that this works fine for nested tests and the callback integration. 

At the moment, I only add support for `@QuarkusIntegrationTest`, but in the future, we could add support also for `@QuarkusMainIntegrationTest`.

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @HerrDerb

**Review by HerrDerb — APPROVED** [review]
Looking good,  as far as I can tell

**Review by geoand — APPROVED** [review]
Nice!

**Comment by geoand** [comment]
Hm... the test failures do seem related

**Comment by Sgitario** [comment]
> Hm... the test failures do seem related

It seems that we can't add the new property `quarkus.test.enable-callbacks-for-integration-tests` as part of the `TestConfig` class because is a build time fixed config group and it fails only when running in Native.

To fix the test failures, I've removed the new property from the `TestConfig` and added a note in the documentation. The PR is already updated.

**Comment by geoand** [comment]
> It seems that we can't add the new property quarkus.test.enable-callbacks-for-integration-tests as part of the TestConfig class because is a build time fixed config group and it fails only when running in Native.

Are you sure about this? We have other similar properties in `TestConfig`.

**Comment by Sgitario** [comment]
> > It seems that we can't add the new property quarkus.test.enable-callbacks-for-integration-tests as part of the TestConfig class because is a build time fixed config group and it fails only when running in Native.
> 
> Are you sure about this? We have other similar properties in `TestConfig`.

Yes. The problem is that this property was `false` at build time (when maven built the Native binary) and `true` when running the test (because it's added using the `@TestProfile` annotation) and this causes an IllegalStateException when running the application.

**Comment by geoand** [comment]
Right, so the property should not be set with a test profile - that does not mean the property should not be part of `TestConfig` - it should be in order for us to get all the benefits of declaring each such properties

**Comment by Sgitario** [comment]
> Right, so the property should not be set with a test profile - that does not mean the property should not be part of `TestConfig` - it should be in order for us to get all the benefits of declaring each such properties.

But this would extremely limit users that want to activate callbacks only for some integration tests, but not all. 
I would say that the right solution is to create an additional TestConfig for runtime properties like this and probably also others. 
Moreover, the current `TestConfig` is part of the `dev` package (dev mode) which is confusing.

**Comment by geoand** [comment]
> But this would extremely limit users that want to activate callbacks only for some integration tests, but not all.

Well, this has never been a problem so far - I mean I think we have only got one request of someone asking for having the callbacks not being enabled for all tests.
I personally would not worry about it at this stage.

> Moreover, the current TestConfig is part of the dev package (dev mode) which is confusing

The source of the class is not meant to be seen by users - we only use this class in order to take advantage of the declarative configuration.

**Comment by Sgitario** [comment]
> > But this would extremely limit users that want to activate callbacks only for some integration tests, but not all.
> 
> Well, this has never been a problem so far - I mean I think we have only got one request of someone asking for having the callbacks not being enabled for all tests. I personally would not worry about it at this stage.

But it will be a problem in the future if we want that a runtime configuration like this to be changed at runtime. 

> 
> > Moreover, the current TestConfig is part of the dev package (dev mode) which is confusing
> 
> The source of the class is not meant to be seen by users - we only use this class in order to take advantage of the declarative configuration.

Yet this does not explain that we have the test purpose config under the `dev` package and that all the properties are build-time configuration. 

Alternatively, we could add a new property within the `@QuarkusIntegrationTest` to activate the callbacks for only the current test and also keep the property in the `TestConfig` which I'm a bit against it because it's not a build config, but a runtime one (even though this isn't to be likely used).

**Comment by geoand** [comment]
> But it will be a problem in the future if we want that a runtime configuration like this to be changed at runtime.

Which we can deal with at that time :). 

> Yet this does not explain that we have the test purpose config under the dev package and that all the properties are build-time configuration.

Sure, the package might be odd, but it's not a problem really.

**Comment by Sgitario** [comment]
PR updated based on the GH discussion: keep the property in the build-time configuration `TestConfig` (hence, added `quarkus.test.enable-callbacks-for-integration-tests=true` in the `application.properties`). 

Taking into account that the property `enable-callbacks-for-integration-tests` is not a build-time property, to fix this in the future, we should remove it from the TestConfig class and remove this line: https://github.com/quarkusio/quarkus/pull/28445/files#diff-1ad75d06709a5c1e9337738768129e24759211c76895b3bda011ecfc8e66e2bfR348

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
