### PR TITLE
Make generate no-args constructor package private

### PR DESCRIPTION
**Pull request by geoand**
The idea here is that hopefully it convince code coverage tools to ignore it

Relates to: #32254

### CODE REVIEW

**Review by manovotn — COMMENTED** [review]
Marked @vsevel for review to make sure this actually addresses the problem.

From CDI perspective this is fine.
From Arc PoV I am thinking whether this can sometimes require reflection access - WDYT @mkouba? I don't think it should (since we are not adding these recursively) but maybe I am missing something?

**Comment by geoand** [comment]
> Marked @vsevel for review to make sure this actually addresses the problem.

+1

Just as an FYI, people should be using the `quarkus-jacoco` instead of the Maven plugin

**Comment by mkouba** [comment]
> Marked @vsevel for review to make sure this actually addresses the problem.
> 
> From CDI perspective this is fine. From Arc PoV I am thinking whether this can sometimes require reflection access - WDYT @mkouba? I don't think it should (since we are not adding these recursively) but maybe I am missing something?

It should be fine.

However, I would add my :+1: to this PR only if we're 100% sure it fixes the problem.

**Comment by manovotn** [comment]
> However, I would add my +1 to this PR only if we're 100% sure it fixes the problem.

My thoughts exactly :)

**Comment by vsevel** [comment]
> Marked @vsevel for review to make sure this actually addresses the problem.

I will give it a try next week. thanks for looking into it.

**Comment by vsevel** [comment]
hmm. could not get it to work.
I took your branch @geoand and rebuilt it locally.
then executed `mvn clean verify -Pcodecoverage` on this [repo](https://github.com/vsevel/reproducer_jacoco)
I am getting
```
[INFO] --- jacoco-maven-plugin:0.8.8:report (report) @ getting-started ---
[INFO] Loading execution data file /Users/vsevel/dev/tmp/jacoco/target/jacoco.exec
[INFO] Analyzed bundle 'getting-started' with 3 classes
[WARNING] Classes in bundle 'getting-started' do not match with execution data. For report generation the same class files must be used as at runtime.
[WARNING] Execution data for class org/acme/MyBean does not match.
```

how do I know your change is doing something?
here is the [faulty bean](https://github.com/vsevel/reproducer_jacoco/blob/main/src/main/java/org/acme/MyBean.java)

**Comment by geoand** [comment]
Hey @vsevel.

I am not sure that jacoco works when used as a Maven plugin. Can you try using the [Quarkus extension](https://quarkus.io/guides/tests-with-coverage)  please?

**Comment by vsevel** [comment]
> I am not sure that jacoco works when used as a Maven plugin.

well, it does for us (assuming we add the default constructor).
I do not know if we could use the extension instead (for use some special config).
but I can do the test for you

**Comment by geoand** [comment]
Okay thanks. 

The reason we have the extension is to (hopefully) overcome issues like these where the source and output do not match.

**Comment by geoand** [comment]
Thanks for checking @vsevel. I'll close this PR as per your findings. 

> I am wondering if the extension has a way to make sure the classes that are tested are the same than the ones used for reporting

What exactly do you mean by this?

**Comment by vsevel** [comment]
> What exactly do you mean by this?

_this happens if classes at runtime are different from the class files at report generation time._

see [this thread](https://groups.google.com/g/jacoco/c/FJ5VAOi2h0s/m/9-I-QzreAgAJ)

this makes me wonder why this would work with the extension and not the maven plugin. one possible explanation is that the extension works differently in the build/test lifecycle, resulting in jacoco report seeing the same classes that were used at runtime.

**Comment by geoand** [comment]
When using the extension, we augment the Jacoco setup to use the transformed classes and run it during the Quarkus build phase.

When it runs as maven plugin, it has no idea where those transformed classes are (because we don't override the original class output on the file system)

**Pull request closed without merging**
