### PR TITLE
Kogito quickstart Person example fails with list of objects

### PR DESCRIPTION
**Pull request by spolti**
…jects

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@mswiderski f.y.i.

**Review by mswiderski — APPROVED** [review]

**Comment by mswiderski** [comment]
@spolti thanks for the fix!

Just a comment, this change itself does not need new kogito version as it fixes the immediate bug in handling list of simple types

**Comment by mswiderski** [comment]
What I meant is that it can be safely merged and no need to wait for 0.6.0 of kogito

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@mswiderski I'm merging it then.

**Pull request merged**
