### PR TITLE
Remove spurious test

### PR DESCRIPTION
**Pull request by evanchooly**
fixes intermittent native test failures

### CODE REVIEW

**Comment by evanchooly** [comment]
A little "princess and the pea" vibe here...

**Comment by FroMage** [comment]
I'm not sure how to review that, I don't know what the test is testing and why it fails but only sometimes.

**Comment by evanchooly** [comment]
It's not really testing anything.  It was a shortcut check I'd put in on early to get a better stack trace out of the tests than what we get via the REST route.  As for why it fails intermittently on CI, I'm not sure.  I was getting pretty regular failures locally until I removed that line.

**Comment by evanchooly** [comment]
ok to merge?

**Review by FroMage — APPROVED** [review]

**Pull request merged**
