### PR TITLE
Narayana upgrade (to 6.0.1.Final)

### PR DESCRIPTION
**Pull request by mmusgrov**
narayana  component upgrade  to 6.0.1.Final

The release notes are https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12310200&version=12402559 and it includes some bug fixes to facilitate issue #31066  (Allow configuring the Narayana transaction log to be stored in a Datasource).

### CODE REVIEW

**Comment by mmusgrov** [comment]
The failure is because the PR is using an old version of the LRA coordinator pulled from quay.io.https://issues.redhat.com/browse/JBTM-3767
I'll need to check to see how the MicroProfile LRA TCK is being configured when running a quarkus PR.
That version of the coordinator contains the bug https://issues.redhat.com/browse/JBTM-3767 so the image needs upgrading.

**Comment by mmusgrov** [comment]
I think we can avoid this issue in the future if, after releasing a version of Narayana that makes changes to the Narayana implementation of the LRA coordinator, we first raise a PR against https://github.com/jbosstm/lra-coordinator-quarkus in order to push a new version of the coordinator image to quay.io, only then will the Quarkus PR be able to run its tests.

But perhaps the sane alternative is to push the coordinator image as part of the Narayana release process like we used to do instead of pushing of the image from a different project. But I think that approach had problems because the Quarkus release cycle is much faster than the Narayana one and we couldn't keep pace with their release cycles so we dropped any dependency on quarkus which was a shame.

I personally don't like either of these proposals but @xstefank do you have a view on which of the two proposals would be best or if there is a third alternative that doesn't have these problems?

**Comment by xstefank** [comment]
@mmusgrov quay.io/jbosstm/lra-coordinator:6.0.1.Final-3.0.0.Final pushed. The PR CI can be retriggered.

**Comment by mmusgrov** [comment]
According to the open issue https://github.com/quarkusio/quarkus-github-bot/issues/71 there is no way to trigger a retest of a PR, @gastaldi do we need to ask one of the quarkus team to trigger a retest of a PR? This PR has failed because the test pulled download an out of date image from quay.io (as I explained in comment https://github.com/quarkusio/quarkus/pull/32922#issuecomment-1525596000) and Martin has since updated that image so we'd like to retest using the new image.

**Comment by mmusgrov** [comment]
Thanks very much @gastaldi . The only failure is in the JDK 19 job which failed running the module `Elytron Security JDBC - Deployment` and is unrelated - see log file 11_Build.txt which reports:

```
RealmUnavailableException: ELY01050: Could not execute query "SELECT u.password, roles FROM test_user u WHERE u.username=?"
...
Caused by: org.h2.jdbc.JdbcSQLDataException: Invalid value "3" for parameter "columnIndex" [90008-214]
etc
```

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
