### PR TITLE
KOGITO-6258: Quarkus: DevServices: Built-in Kafka hot-reload blocks process

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/KOGITO-6258

Discussion here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/DevServices.20Kafka.20usage

Please advise your admin process if you need a GitHub issue or QUARKUS JIRA etc and I will oblige.

### CODE REVIEW

**Comment by manstis** [comment]
@Ladicek FYI. I removed the call to `join()` on the other methods too as it seemed appropriate.

Please close, reject this PR as you see fit.. it's just trying to save you some work.

**Review by Ladicek — APPROVED** [review]
This looks good to me, but I don't have the time to thoroughly test.

**Comment by gsmet** [comment]
@Ladicek is it something I should merge and backport to 2.5? Or should we wait?

**Comment by Ladicek** [comment]
I guess I wouldn't mind myself, but it seems important for Kogito, so perhaps backporting to 2.5 is a good idea.

(@cescoffier any other opinion?)

**Comment by manstis** [comment]
Hi @Ladicek @gsmet @cescoffier it doesn't _block_ me.. I can build locally and use a `SNAPSHOT` for now.

@evacchi I get the feeling Kogito follows Quarkus releases pretty closely so this can probably wait for 2.6.

If anyone has a strong preference either way don't let my opinion take precedence.

**Comment by cescoffier** [comment]
No problem backporting it.

**Review by cescoffier — APPROVED** [review]

**Comment by manstis** [comment]
Hi @cescoffier do I need to submit a PR to backport it?

The `kogito` team developers backport fixes themselves. IDK your development process.

**Comment by cescoffier** [comment]
No need for an additional PR. There is the backport label (already set)

**Pull request merged**
