### PR TITLE
DevMojo: introduce enforceBuildGoal param to opt out of build goal check

### LINKED ISSUE #9094: Dev-Mode: Remove check for build goal (or provide opt-out)
**Description**
In my current multi-module project we have one main `server` module where everything comes together and where the `quarkus:build` is configured.

To be able to just start only a part of the application, we introduced a Maven profile that allows to start Dev-Mode in certain other modules which do not (and must not) have `quarkus:build` configured.

Due to a check in https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L259 we have to "fake" the build goal:
```xml
        <profile>
            <id>qdev</id>
            <build>
                <defaultGoal>quarkus:dev</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>io.quarkus</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                        <executions>
                            <!-- presence of build-goal is enforced by dev-goal, but is not required to actually run (sic!) -->
                            <execution>
                                <id>default</id>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

It would be nice to get rid of this fake build goal workaround.

**Implementation ideas**
In case you want to prevent Quarkus-newbies from making mistakes, there could be a mojo parameter for opting out of the check that the experienced users could use.

cc @harthorst

### PR DESCRIPTION
**Pull request by famod**
Resolves #9094

cc @geoand

### CODE REVIEW

**Comment by famod** [comment]
Btw, it seems there is _no_ full mojo documentation (with all the params) online?

**Comment by geoand** [comment]
`DevMojoIT` seems to be failing in CI

**Comment by famod** [comment]
> `DevMojoIT` seems to be failing in CI

I'll check. It didn't do so locally.

PS: I must say that as cool as the GH actions are, it is pretty cumbersome to extract the failing tests.

**Comment by geoand** [comment]
> PS: I must say that as cool as the GH actions are, it is pretty cumbersome to extract the failing tests.

Yes... it's a pain in that respect

**Comment by famod** [comment]
Is that "normal"?
```
$ mvn clean verify -f integration-tests/maven/
[...]
[INFO] --- quarkus-platform-descriptor-json-plugin:999-SNAPSHOT:validate-extensions-json (default) @ quarkus-integration-test-maven ---
[WARNING] Failed to resolve io.smallrye:smallrye-config:jar:1.5.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.smallrye:smallrye-config-common:jar:1.5.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-lang-js-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-lang-groovy-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-lang-ruby-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-lang-kotlin-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-junit5-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-consul:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-mongo:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-maven-service-factory-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-jca:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-mail:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-jgroups:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-sql-client-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-mysql-postgresql-client-parent:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[WARNING] Failed to resolve io.vertx:vertx-client-services:jar:3.9.0 from managed dependencies of BOM io.quarkus:quarkus-bom:pom:999-SNAPSHOT
[ERROR] Extensions from io.quarkus:quarkus-bom:pom:999-SNAPSHOT not present in io.quarkus:quarkus-bom-descriptor-json:999-SNAPSHOT
[ERROR] - io.quarkus:quarkus-spring-cache:jar:999-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by geoand** [comment]
It doesn't look normal, but I don't see any other PRs affected by it

**Comment by famod** [comment]
This happens locally on my private PC (Win10) and on my company laptop (Win10, corporate security, proxy, yadda yadda...).
I built everything before that via `mvn clean install -DskipTests -DskipITs -DskipDocs -T3`.

**Comment by geoand** [comment]
I dunno TBH, it works for me locally.

**Comment by famod** [comment]
I might create another issue for that, then.

**Comment by famod** [comment]
Back to the main issue:

The only failure I see locally `quarkus-integration-test-maven` is:
```
[ERROR] Failures:
[ERROR]   DevMojoIT.testThatTheApplicationIsReloadedOnDotEnvConfigChange:601
Expecting:
 <"other">
to contain:
 <"Hola">
 (ignoring case)
[INFO]
[ERROR] Tests run: 60, Failures: 1, Errors: 0, Skipped: 1
```
and I suppose this is due to:
```
020-05-12 13:30:20,152 WARN  [io.qua.dep.dev.DevModeMain] (main) Unable to copy .env file: java.nio.file.FileSystemException: C:\_dev\git\quarkus\integration-tests\maven\target\test-classes\projects\project-classic-run-java-change-remote\target\.env: Dem Client fehlt ein erforderliches Recht.

        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
        at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1058)
        at io.quarkus.deployment.dev.DevModeMain.copyDotEnvFile(DevModeMain.java:145)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:109)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:55)
```
This is on Win10 Home which does not allow settings symlinks, AFAIK.

Long story short: I cannot repoduce the failures from your CI and since the output ist extremely sparse, I don't know how to continue.

**Comment by geoand** [comment]
Based on:

```
2020-05-12T00:42:16.4144262Z [ERROR] Errors: 
2020-05-12T00:42:16.4161333Z [ERROR]   DevMojoIT.testThatTheApplicationIsNotStartedWithoutBuildGoal:638->MojoTestBase.initProject:62 Â» Runtime
2020-05-12T00:42:16.4162072Z [ERROR]   DevMojoIT.testThatTheApplicationIsStartedWithoutBuildGoalWhenNotEnforced:649->MojoTestBase.initProject:81 Â» Runtime
```

I checked out your PR, rebased it onto the latest master and ran:

```
mvn clean verify -Dit.test=DevMojoIT#testThatTheApplicationIsNotStartedWithoutBuildGoal -f integration-tests/maven/
```

What I got was:

```
-------------------------------------------------------------------------------
Test set: io.quarkus.maven.it.DevMojoIT
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.158 s <<< FAILURE! - in io.quarkus.maven.it.DevMojoIT
io.quarkus.maven.it.DevMojoIT.testThatTheApplicationIsNotStartedWithoutBuildGoal  Time elapsed: 0.145 s  <<< ERROR!
java.lang.RuntimeException: Cannot find directory: /home/gandrian/projects/redhat/quarkus/integration-tests/maven/target/test-classes/projects/classic-no-build
	at io.quarkus.maven.it.DevMojoIT.testThatTheApplicationIsNotStartedWithoutBuildGoal(DevMojoIT.java:638)
```

**Comment by famod** [comment]
Thanks! I must have missed that `Cannot find directory` bit; my commit was incomplete.

**Comment by geoand** [comment]
Seems reasonable to me. @aloubyanksy can you think of any way this could backfire?

**Comment by famod** [comment]
@aloubyansky WDYT?

**Review by aloubyansky — APPROVED** [review]
Thanks @famod

**Pull request merged**
