### PR TITLE
Update to SmallRye JWT 3.0.0

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@radcortez Hey Roberto - fault-tolerance tck has failed so MP JWT tck did not run. There was no luck in my fork due to some unrelated build failures as well: https://github.com/sberyozkin/quarkus/actions/runs/561117570.

**Comment by sberyozkin** [comment]
@gsmet I'm going to restart soon - any concerns let me know please

**Comment by radcortez** [comment]
> @radcortez Hey Roberto - fault-tolerance tck has failed so MP JWT tck did not run. There was no luck in my fork due to some unrelated build failures as well: https://github.com/sberyozkin/quarkus/actions/runs/561117570.

I think there is a TCK test that fails sometime due to sync issues.

**Comment by sberyozkin** [comment]
@radcortez JDK8 (vault), Native tests - messaging, and Misc4 failed, not related to the PR. We can restart or merge :-)

**Review by radcortez — APPROVED** [review]

**Pull request merged**
