### PR TITLE
Kafka Streams: restore the feature name at Quarkus startup

### LINKED ISSUE #34171: QuarkusApplication with Argument class/interface as a parameter
### Description

Quarkus supports implementation of QuarkusApplication which has a run(String... args) method to access command line arguments, I'm thinking if the args has a interface that supports basic command line features immediately for example:

- getOptions
- getArgs

### Implementation ideas

This is an additional interface/s. Add another interface named QuarkusArgument as an example to make it as a parameter for an overloaded ' run()` method in QuarkusApplication.
Example interface

```
interface QuarkusArgument {

String[] getOptions();

String[] getArguments();

// and so on.....
}
```

So that other developers doesn't need to create their own custom methods just to manipulate the whole `String... args` argument when we can create immediately the obvious ones.

### LINKED ISSUE #35171: kafka-streams: feature not listed on startup
### Describe the bug

Develop a microservice based on the quarkus kafka-streams extension.
Run quarkus:dev and look at the start logs of Quarkus.
kafka-streams does not appear in the list.

### Expected behavior

kafka-streams should be listed in the activated extensions

### Actual behavior

kafka-streams does not appear, probably since this commit https://github.com/quarkusio/quarkus/commit/4bd0553402aa0b6009d7b36e84fc70df385db572, i.e. whenever the microservice is launched in JVM mode

### How to Reproduce?

[reproducer-kafka-streams-not-listed.zip](https://github.com/quarkusio/quarkus/files/12242048/reproducer-kafka-streams-not-listed.zip)

1. unzip above code.quarkus.io generated project
2. run mvn quarkus:dev
3. the following log line: `Installed features: [cdi, kafka-client]` does not contain kafka-streams

### Output of `uname -a` or `ver`

Linux 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15)

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mederel**
Fixes #35171

The FeatureBuildItem was returned in a BuildStep now annotated to only run when native compilation is used.
The consequence is that in JVM mode, the FeatureBuildItem is not created, and the feature name not appearing in the start logs of Quarkus.

Solution: extract the FeatureBuildItem creation in a dedicated BuildStep.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Good catch!

**Comment by gsmet** [comment]
Force pushed to fix the formatting issue.

**Comment by mederel** [comment]
> Force pushed to fix the formatting issue.

Thanks, sorry for the stupid import.

**Comment by gsmet** [comment]
No worries, that's why we have checks :).

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
