### PR TITLE
Do not use deprecated `DockerStatusBuildItem#isDockerRunning` in core

### PR DESCRIPTION
**Pull request by gastaldi**
/cc @edeandrea

### CODE REVIEW

**Comment by geoand** [comment]
How long ago was this deprecated, do we know?

**Comment by gastaldi** [comment]
It was deprecated here: https://github.com/quarkusio/quarkus/pull/40729

**Comment by gastaldi** [comment]
Hm, since this is recent, I think I'll keep the deprecated method for now, but keep the changes to use the new method,

**Comment by edeandrea** [comment]
I did not remove it in #40729 because I didn't want to break anything in Quarkiverse/Camel that may be using it.

**Comment by geoand** [comment]
Yeah, I completely agree

**Review by geoand — APPROVED** [review]

**Comment by gastaldi** [comment]
Done, changed the PR title too

**Comment by gsmet** [comment]
Mmmmh, looks like we got issues with Docker pulling the images:

```
2024-07-19T15:28:17.1976345Z 2024-07-19 15:28:17,130 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--1881956780) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}
2024-07-19T15:28:17.1978719Z 
2024-07-19T15:28:17.1979517Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
2024-07-19T15:28:17.1981331Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
```

Doesn't look related to this patch though.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Good cleanup, thanks. Note that the backport label is `triage/backport`, I fixed it.

**Pull request merged**
