### PR TITLE
Bump Microsoft SQL Server JDBC driver to 12.6.3

### LINKED ISSUE #41255: Bump Microsoft SQL Server JDBC driver to 12.6.3
### Description

MS has created a new release of the MS SQL JDBC driver: https://github.com/microsoft/mssql-jdbc/releases/tag/v12.6.3
We should pick this up for Quarkus.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by sschu**
Closes #41255

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Thanks! Let's see what CI has to say.

**Comment by sschu** [comment]
I have to admin, I am pretty lost. I can reproduce the error locally but the code the parser complains about basically hasn't been touched for years. I don't really see a difference between 12.6.1 and 12.6.2 that sounds like the error message.

**Comment by zakkak** [comment]
Indeed, the error message indicates that `com.microsoft.sqlserver.jdbc.SQLServerSecurityUtility.decryptSymmetricKey(com.microsoft.sqlserver.jdbc.CryptoMetadata, com.microsoft.sqlserver.jdbc.SQLServerConnection, com.microsoft.sqlserver.jdbc.SQLServerStatement)` can't be resolved. 

Looking at https://github.com/microsoft/mssql-jdbc/blob/17caf22234e632407499ad4e5a234c9da2de5aef/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java#L228 the method is present in the source code and I also see it in the decompiled class file from the maven artifact.

I tried attaching the debugger to see the root cause (and why it's not printed) but haven't succeeded yet, I will give it a try tomorrow again or next week.

**Comment by zakkak** [comment]
For future reference to debug this I set a breakpoint at https://github.com/graalvm/mandrel/blob/08389e1be8f9588c03ffa34a7820fab22fb3dcf1/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/SharedGraphBuilderPhase.java#L248 and run:

```
./mvnw -Dnative -pl integration-tests/jpa-mssql/ -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package -Dquarkus.native.container-runtime=podman -Dquarkus.native.debug-build-process
```

Then I attach my IDE/Debugger to port 5005, when the breakpoint is hit all we need is to inspect cause of the exception.

**Comment by gsmet** [comment]
@zakkak thanks! And thanks for creating an issue on the GraalVM side to improve the error message.

**Comment by sschu** [comment]
@zakkak The reference to `TokenCredential` was a good hint, I was able to find the code referencing the optional dependency and substituting it out and it worked. In the meantime, the same issue was reported at the mssql-jdbc driver (see https://github.com/microsoft/mssql-jdbc/pull/2453) and released (see https://github.com/microsoft/mssql-jdbc/releases/tag/v12.6.3). So this should work without any modifications now with 12.6.3. I hope the CI agrees.
@gsmet FYI.

**Pull request merged**
