### PR TITLE
Use run-java script when possible

### PR DESCRIPTION
**Pull request by geoand**
When creating a container image using Jib,
try to use the run-java script when
it exists and when AppCDS are not being
used

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@geoand will this affect who already using jib to build container images?

**Comment by geoand** [comment]
Yes

**Comment by shivam-sharma7** [comment]
> Yes

then it is comming in next quarkus 3.6.2 right?

**Comment by cescoffier** [comment]
I would say 3.7.

**Comment by cescoffier** [comment]
(@geoand we should document it as a breaking change and how to configure the entry point)

**Review by cescoffier — APPROVED** [review]

**Comment by shivam-sharma7** [comment]
Thanks @cescoffier

**Comment by geoand** [comment]
> (@geoand we should document it as a breaking change and how to configure the entry point)

Definitely.

**Pull request merged**
