### PR TITLE
Update Vert.x version to 4.4.6

### LINKED ISSUE #36119: quarkus-redis need newer vertx-redis-client to fix connection pool issue
### Describe the bug

Just to remind Quarkus 3.2.x/3.3.x/3.4.x should pick newer vertx-redis-client when it's released:

https://github.com/vert-x3/vertx-redis-client/pull/406
https://github.com/vert-x3/vertx-redis-client/pull/407

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #36144: PG Reactive Client: Cannot create Money value in Range (-1.00, 0.00)
### Describe the bug

I cannot create a `Money` value of -0.XX, i.e.,  a Money value greater than -1.00, and less than 0.00. Range  (-1.00 < value < 0.00)

If the integer value of the Number argument is non-zero, e.g., using `Money` constructor argument `new BigDecimal("-1.11")`  works.

If the integer value of the Number argument is zero, e.g., using a `Money` constructor `new BigDecimal("-0.11")` does not work (as expected).

I am not certain this is a bug, due to my expectation that the integerPart of a Money(-0.11) could be represented as -0.

Reproducing tests and debugger screenshots are below.

### Expected behavior

Calling `new Money(new BigDecimal("-0.11"))` results in a negative `Money(-0,11)`

The Money value represents  minus 11 cents, as expected.

### Actual behavior

Calling `new Money(new BigDecimal("-0.11"))` results in a _positive_ `Money(0,11)`

The Money value represents plus 11cents, not minus 11cents.

### How to Reproduce?

> Reproduce Expected Behaviour
1. Use a `BigDecimal` as a `Money` constructor argument.  
   `Money money = new Money(new BigDecimal("-1.11"));`

2. Examine resulting Money in debugger:
right-money

3. Print resulting Money value:  `Money(-1.11)`.          As expected I see `Money(-1.11)`.

> Reproduce Unexpected Behaviour

1. Use a `BigDecimal` as a `Money` constructor argument.  
   `Money money = new Money(new BigDecimal("-0.11"));`

2. Examine resulting Money in debugger:
wrong-money

3. Print resulting Money value:  `Money(0.11)`.          I expect to see `Money(-0.11)`.

Below are some test cases.

```
 @Test
    public void testRightMoney() {
        Money money = new Money(new BigDecimal("-1.11"));
        System.out.println(money);
        assertEquals(-1, money.getIntegerPart());
        assertEquals(11, money.getDecimalPart());
    }
```

Above, as expected `assertEquals(-1, money.getIntegerPart())` passes.

```
@Test
    public void testWrongMoney() {
        Money money = new Money(new BigDecimal("-0.11"));
        System.out.println(money);
        assertEquals(0, money.getIntegerPart());
        assertEquals(11, money.getDecimalPart());
    }

```

Above, as expected `assertEquals(0, money.getIntegerPart())` passes, but I need to be able to create a Money(-0.11).

Any advice?
Thanks.

### Output of `uname -a` or `ver`

Ubuntu 22.04.3  Linux 6.2.0-33-generic x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

### Additional information

_No response_

### LINKED ISSUE #36234: NullPointerException for request with empty Host header in j3.4.1
### Describe the bug

The request without the `Host` header does work in Quarkus 3.3.1 but not in 3.4.1
```
curl -iv -H "User-Agent:" -H "Accept:" -H "Host:" http://localhost:8080/foo
```
Fails with 500 and NullPointerException in log (enabled level ALL)

Vert.x io.vertx.core.net.impl.HostAndPortImpl does not allow an empty Host header anymore and throws `NullPointerException`
Would it be possible to intercept the request and set a dummy host header to make vert.x happy?
Currently, `ContainerRequestFilter` is not invoked on that failure

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #36382: redis-cache blocks the eventloop
### Describe the bug

The Redis cache implementation seems to block the eventloop. It causes the HTTP throughput to be very poor, we see that the `worker_pool_queue_delay_seconds_max` metric keeps getting higher and higher, it was at 60s before we turned off the load test. It also seems to cause a very high number of open files on the Linux system.

We verified this by switching to caffeine cache, the throughput increased by a factor 3. The number of open files dropped and `worker_pool_queue_delay_seconds_max` stays low.

MicrosoftTeams-image

Screenshot Grafana

### Expected behavior

The Redis cache implementation does not block the eventloop.

### Actual behavior

The Redis cache implementation blocks the eventloop.

### How to Reproduce?

1.  Create a sample application with Resteasy Reactive and Redis cache
2. Create a simple endpoint and a method annotated with `@CacheResult`
3. Run a load test with > 100req/s
4. The console should now log `thread blocked` errors

### Output of `uname -a` or `ver`

Linux 4.18.0-477.27.1.el8_8.x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 LTS OpenJDK Runtime Environment (Red_Hat-17.0.5.0.8-2.el8_6) (build 17.0.5+8-LTS) OpenJDK 64-Bit Server VM (Red_Hat-17.0.5.0.8-2.el8_6) (build 17.0.5+8-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
* Fix #36144 
* Fix #36382
* Fix #36119 
* Fix #36234 
* Allows configuring the RST Flood protection

### CODE REVIEW

**Comment by cescoffier** [comment]
@maxandersen FYI.

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@cescoffier is it something that needs to be considered for 3.2 at some point or not?

**Comment by Dieken** [comment]
3.5.0 is about to be released, could this be ported to 3.4.x and 3.5.x?

**Comment by gsmet** [comment]
It will be part of 3.5.1.

**Comment by cescoffier** [comment]
@gsmet yes, it needs to be backported. I tried to make it as simple as possible. If needed I will redo the commit for 3.2.

**Pull request merged**
