### PR TITLE
ArC - injection point validation

### PR DESCRIPTION
**Pull request by mkouba**
- type variable is not a legal injection point type
- also validate type params of types related to programmatic lookup,
i.e. Instance<> and List<> with All qualifier

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]
LGTM, though I have reservations about the error messages. Wildcards and type variables _are_ legal type arguments. IMHO, the errors should read more like "Injection point may not contain a wildcard type argument" or so.

Note I'm specifically using the term "type argument" instead of "type parameter". I'd encourage to follow this convention. In a function declaration, we define _parameters_. In a function call, we pass _arguments_. The same applies to generics. In a generic class/method declaration, we define _type parameters_ (e.g. in `class List<T> { ... }`, `T` is a type parameter). In a generic instantiation of a class/method, we pass _type arguments_ (e.g. in `List<String>`, `String` is a type argument).

**Comment by mkouba** [comment]
> LGTM, though I have reservations about the error messages. Wildcards and type variables _are_ legal type arguments. IMHO, the errors should read more like "Injection point may not contain a wildcard type argument" or so.

Actually, the error message for `@Inject T` is "Type variable is not a legal **_injection point type_**" which is IMO correct. "Injection point may not contain a wildcard type argument" is not exact because `@Inject List<T>` is OK.

> Note I'm specifically using the term "type argument" instead of "type parameter".

Ok, I'll update the error message for `Instance` to use the "type argument".

**Review by Ladicek — APPROVED** [review]

**Review by manovotn — APPROVED** [review]
Looks good and consistent with what we do in Weld.

**Comment by mkouba** [comment]
I need to fix the `io.quarkus.qute.deployment.inject.InjectionFailedTest`...

**Pull request merged**
