### PR TITLE
Update SmallRye Config to 2.12.1

### PR DESCRIPTION
**Pull request by radcortez**
https://github.com/smallrye/smallrye-config/releases/tag/2.12.1

### CODE REVIEW

**Comment by gsmet** [comment]
Do we need a Jakarta version or can we live without it?

**Comment by radcortez** [comment]
I think we can live without it. This is just a release with a few fixes. No API changes.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
And second question: do we need that for 2.13? Or is it 2.14 material?

**Comment by radcortez** [comment]
Not urgent; we can do it for 2.14.

**Pull request merged**
