### PR TITLE
Add quarkus-test-oidc-server test support module and update the docs

### PR DESCRIPTION
**Pull request by sberyozkin**
@cemnura has done a great job with completing the code flow wire mock test support - this PR completes this iteration with moving the Wiremock code into a test support module (with a few minor updates) and updating the docs

### CODE REVIEW

**Comment by sberyozkin** [comment]
Sorry, I'll need to do a few doc tweaks

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by sberyozkin** [comment]
Hi George @gastaldi thanks, I did not have a good sleep today and as it happens I thought of this PR :-) and realized I should also update `smallrye-jwt` guide to show how to use this mock and may be do a few minor code enhancements, sorry about it, I'll do some more work here and will ping you and @stuartwdouglas again

**Comment by sberyozkin** [comment]
@gastaldi I'll go ahead with the merge now so as not to miss `.Final`, I'll follow up with another PR, @stuartwdouglas will CC you as well in case you'd like to review as well

**Pull request merged**
