### PR TITLE
Set up JAXP factories

### LINKED ISSUE #1762: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl
Hello!

I am having a few issues while trying to use SAXParserFactoryImpl and have tried a few things:
- Creating a SAXParserProcessor and registering it with a @BuildStep, however, I'm not sure on how to configure a new extension (is this necessary?);
- Registering it with System.property;
- Tried using the underlying graalVM Class.forName as mentioned in Graal's reflection docs, but no luck;

Even tried a few other things and I'm a little out of ideas now. Can someone help me, please?
I even tried downloading quarkus-jaxb but no luck.

Thanks!

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #1762

### CODE REVIEW

**Comment by dmlloyd** [comment]
@brenol, @danilocgomes - this change should fix the problem, with one catch: you'll have to bundle a JAXP implementation (like Xerces) because this approach cannot use the JDK one.  Because of this I want to have some discussion before I officially propose this fix - and also I'm hoping that you can verify that this actually fixes the issue as well!

**Comment by dmlloyd** [comment]
Also you'll have to install a snapshot of Gizmo - I forgot about that.

**Comment by gsmet** [comment]
> you'll have to bundle a JAXP implementation (like Xerces) because this approach cannot use the JDK one

Can't say I'm excited about this.

**Comment by dmlloyd** [comment]
> > you'll have to bundle a JAXP implementation (like Xerces) because this approach cannot use the JDK one
> 
> Can't say I'm excited about this.

Me either.  I actually did an implementation where the JDK class is detected and used - but it will almost certainly fail unless native-image is run against the same JDK instance that augmentation was run on, which is a restriction that we have not had to date.

Once we move to Java 9+, the JAXP factories include methods like `javax.xml.parsers.SAXParserFactory#newDefaultInstance` and so forth, which work as a valid fallback.  But until then, I don't see a better option.

**Comment by dmlloyd** [comment]
FYI this is essentially part of what I hope will become a new overall strategy: replacing runtime discovery which relies on service loader or reflection with a static direct constructor invocation.  This way if the service is not used, it is DCE'd, yet all such services are otherwise available without any special configuration.

The first step is this one: replacing specific factory methods with discovered implementation.  JAXP is a special case though, because of its myriad fallback strategies which make things difficult as I pointed out in my previous comment.  Most discovery-based services do not operate in this way and can be solved much more simply.

**Comment by cescoffier** [comment]
any update on this PR?

**Comment by dmlloyd** [comment]
Nope, I still don't have any ideas.  My current plan is to wait it out until we start requiring 11, and then fall back to the new methods that show up in 9.

**Comment by cescoffier** [comment]
Thanks for the heads up. I'm going to add the on-ice label.

**Comment by stuartwdouglas** [comment]
@dmlloyd is there any point in keeping this one open if the current plan is to wait for JDK11 support?

**Comment by dmlloyd** [comment]
At this point it's more of a reminder to me.  We can close it though, it's on my board in any case.

**Pull request closed without merging**
