### PR TITLE
Upgrade to jboss-threads 3.5.0.Final

### PR DESCRIPTION
**Pull request by dmlloyd**
This includes `ScheduledExecutorService` support.

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
I don’t recall having seen these Vert.x tests failing before, could the failures be related?

**Comment by geoand** [comment]
That's why I reran the tests

**Comment by dmlloyd** [comment]
The pool implementation didn't change, but it could be related if there is code which detects that the pool is a scheduled pool *and* there is some bug there that I don't know about/didn't come up in testing.

**Comment by dmlloyd** [comment]
I see: `Quarkus CI / JVM Tests - JDK 17 (pull_request) Successful in 265m`

Is that normal? Or is that much too long as I suspect?

**Comment by geoand** [comment]
It does seem rather long but I did see that https://github.com/quarkusio/quarkus/actions/runs/4353713879/jobs/7610030824 took about the same time

**Comment by gsmet** [comment]
I have been concerned a bit by that but it's really hard to figure out what's going on or if there is actually a problem.

**Comment by dmlloyd** [comment]
I looked at some other CI runs where it took ~10 minutes or so for that step. Maybe I can find something in the logs that will give a clue as to whether it's a real problem.

**Comment by geoand** [comment]
@dmlloyd you can't really compare any PR because CI only builds affected modules.

So to compare you need to look at PRs that make changes to core

**Comment by gsmet** [comment]
The best PRs to compare things are PRs updating the BOM (typically most Dependabot PRs). The runs will be consistent there.

**Comment by dmlloyd** [comment]
Well I read through the entire log for `JVM Tests - JDK 17` and didn't see any time gaps that would make me think that something is wrong with the thread pool; it looks like it's just building a lot of modules (even just printing the final reactor summary took something like a quarter of a second). Next I'll look at the Windows one to see if I can get a clue as to what might be happening there.

**Comment by dmlloyd** [comment]
OK for the Windows build I think the test which is failing might have a race condition. Here's the body of the request handler used in the test:

```java
    @Path("per-request")
    @RequestScoped
    public static class PerRequestResource implements Closeable {
        private final Closer closer;
        private final Counter counter;

        public PerRequestResource(Closer closer, Counter counter) {
            this.closer = closer;
            this.counter = counter;
        }

        @GET
        public int get() {
            closer.add(this);
            return counter.perRequest.get();
        }

        public void close() throws IOException {
            counter.perRequest.incrementAndGet();
        }
    }
```

and it's expected to work like this:

```java
        get("/per-request")
                .then()
                .statusCode(200)
                .body(equalTo("0"));
        get("/per-request")
                .then()
                .statusCode(200)
                .body(equalTo("1"));
```

The basic idea seems to be that we are checking to see that the closer does in fact get called, by observing the effect in the second request. However, I think it is possible for the second request to complete before the closer is called on the first one, and this might be happening more consistently on Windows for some reason (e.g. different number of cores, different thread scheduling policy compared to Linux, etc.).

There probably needs to be a latch or barrier or something on the second request which blocks until the closer is called, with a short timeout (e.g. 5 seconds).

I don't think think this is a problem related to the threads upgrade (but @geoand should confirm that).

**Comment by geoand** [comment]
@dmlloyd yes, I have observed that test being unstable and plan to loom at it again next week

**Comment by geoand** [comment]
I think what I'll do is limit the thread pool to one thread for that test

**Pull request merged**
