### PR TITLE
Fix OIDC scope to permission mapping when scope is empty

### LINKED ISSUE #36911: OIDC "Permission must not be empty" with imported test realm since 3.5.0
### Describe the bug

In certain projects, we use a realm.json to initialize the keycloak dev instance for our tests.
This did work fine prior 3.5.0

Since 3.5.0 we do get an exception as soon as we try to send an authorized request to a REST api during a test:
```
Caused by: java.lang.IllegalArgumentException: Permission name must not be empty
                at io.quarkus.security.StringPermission.validateAndTrim(StringPermission.java:48)
                at io.quarkus.security.StringPermission.<init>(StringPermission.java:26)
                at io.quarkus.oidc.runtime.OidcUtils.transformScopesToPermissions(OidcUtils.java:314)
                at io.quarkus.oidc.runtime.OidcUtils$1.<init>(OidcUtils.java:288)
                at io.quarkus.oidc.runtime.OidcUtils.addTokenScopesAsPermissions(OidcUtils.java:286)
                at io.quarkus.oidc.runtime.OidcUtils.setSecurityIdentityPermissions(OidcUtils.java:281)
                at io.quarkus.oidc.runtime.OidcUtils.validateAndCreateIdentity(OidcUtils.java:270)
                at io.quarkus.oidc.runtime.OidcIdentityProvider.createSecurityIdentityWithOidcServer(OidcIdentityProvider.java:284)
```

As nothing is noted as a breaking change concerning oidc in 3.5.0 and the imported realm.json seems valid, I must assume that this is bug?

PS: Mabey our keycloak "test tool" to add users, roles etc. could be distilled and integrated in quarkus?

### How to Reproduce?

Run tests:
https://github.com/HerrDerb/quarkus-issue/tree/oidc-3-5-0-issue

Switch to Quarkus version 3.4.3 and the test will succeed.

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #36911

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Thanks @michalvavrik for a quick fix

**Comment by michalvavrik** [comment]
> Thanks @michalvavrik for a quick fix

Np, I was thinking about something even more robust for all sorts of scenarios like scope ` separator ` (white separator white space) that would also result into illegal arg exception, but this seems most performant fix. However while I found plenty of scenarios where users had empty scope, I think we can stick with this and made adjustments if someone complains. The reported issue resulted in 401, so it's safe (though it was a bug).

**Comment by michalvavrik** [comment]
@sberyozkin I've made one simple change `isEmpty` => `isBlank` that should handle everything; please have a look again

**Review by sberyozkin — APPROVED** [review]
LGTM

**Pull request merged**
