### PR TITLE
Add Vodafone Greece to ADOPTERS.md

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Review by geoand — APPROVED** [review]
It's only fitting that a Greek approves this PR :)

**Comment by Sanne** [comment]
Just wondering, anyone knows why CI is building this PR? This specific file is listed in the exclusions.

**Comment by geoand** [comment]
Yeah, we wondering the same in chat. Something is off

**Review by maxandersen — APPROVED** [review]
a-ok!

**Pull request merged**
