### PR TITLE
Support `@EmbeddedId` in spring-data-jpa repositories & allow ids to be returned from `@Query` methods

### LINKED ISSUE #10870: Provide support for composite primary key in Spring Data JPA
**Describe the bug**
Composite primary key with @Id and @EmbeddedId annotation are not allowed because there is an error about the mandatory use of an @Id annotation.

```
@Entity
public class Profile {
	
	@EmbeddedId
	private ProfileId profileId;
	
	@Column(name = "name")
	String name;
}
```
And:

```
@Embeddable
public class ProfileId  implements Serializable{	
	private static final long serialVersionUID = 1L;
	@Column(name = "id")
	private String id;

	@Column(name = "number")
	private Long number;
	
	@Column(name = "code")
	private String code;
}
```
```
public interface IProfileRepository extends JpaRepository<Profile, ProfileId> {
	
}

```
**Expected behavior**
The use of composite primary key through annotation @EmbeddedId. 
**Actual behavior**
This is the console error:
Caused by: java.lang.IllegalArgumentException: Currently only Entities with the @Id annotation are supported. 

**To Reproduce**
1. Create new Quarkus app with: Hibernate ORM and Quarkus Extension for Spring Data JPA API dependencies. For DB I used Oracle (but the behaviour is the same at PostgreSQL)
2. Add these classes
3. run mvn quarkus:dev

**Configuration**
```properties
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL10Dialect
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.username=user
quarkus.datasource.password=pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/demo
quarkus.hibernate-orm.database.generation=drop-and-create

```

**Screenshots**
None

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Microsoft Windows [Version 10.0.17763.1282]
 - Output of `java -version`:  openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
Libraries:
quarkus-hibernate-orm
quarkus-jdbc-postgresql / ojdbc8
quarkus-spring-data-jpa

### PR DESCRIPTION
**Pull request by famod**
Resolves #10870

The second commit prevents exceptions like:
```
Caused by: java.lang.IllegalArgumentException: Query annotations may only use interfaces to map results to non-entity types. Offending query string is "select p.id from PhoneCall p" on method findAllIds of Repository io.quarkus.it.spring.data.jpa.PhoneCallRepository
        at io.quarkus.spring.data.deployment.generate.CustomQueryMethodsAdder.add(CustomQueryMethodsAdder.java:300)
```
The second commit could also be a separate PR, but the change is tiny and is also about ids (in general, not only embedded ones), so ...

Please let me know if you prefer a separation.

It would be great if that could end up in 2.5!

### CODE REVIEW

**Comment by famod** [comment]
Btw, in the long run, that return type check in `CustomQueryMethodsAdder` should be deferred to runtime as suggested here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/getting.20all.20hibernate.20supported.20types/near/258183181
But I'm lacking the time to take a closer look at that so I decided to take a small improvement step first.

**Comment by geoand** [comment]
I'm off for a week or two, so I won't be able to review this any time soon

**Comment by famod** [comment]
@geoand ok, have a nice time! Can anyone else review this?

**Comment by geoand** [comment]
It's more of a necessity than a leisure 😝.

@gsmet or @gastaldi mind taking a look?

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
Thanks everyone!

**Pull request merged**
