### PR TITLE
Introduce quarkusGoOffline task to download app dependencies for off-line use

### PR DESCRIPTION
**Pull request by glefloch**
This introduce the `quarkusPrepareOffline` task that resolves all application dependencies.

### CODE REVIEW

**Comment by aloubyansky** [comment]
@glefloch thanks for this PR. Do you mind changing the task name to `quarkusGoOffline` to keep it kind of consistent with the Maven equivalent or you really don't like it?

**Comment by glefloch** [comment]
Sure, I will update it. I have no problem with `quarkusGoOffline` :)

**Comment by gsmet** [comment]
@glefloch can you adjust the commit message too?

**Comment by glefloch** [comment]
right, sure. Done!

**Review by gastaldi — APPROVED** [review]
LGTM

**Pull request merged**
