### PR TITLE
read timeout for blocking http

### LINKED ISSUE #4455: Read timeout for Servlet
Undertow should have a read timeout for blocking IO. This should be inherited from the vert.x config.

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
fixes #4455

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
requires: https://github.com/quarkusio/quarkus-http/pull/9

**Comment by michalszynkiewicz** [comment]
resurected the PR, needs a release of quarkus-http with https://github.com/quarkusio/quarkus-http/pull/13

**Comment by michalszynkiewicz** [comment]
The quarkus-http PR has been merged: https://github.com/quarkusio/quarkus-http/pull/13
This PR waits only for quarkus-http release now.

**Comment by michalszynkiewicz** [comment]
@gsmet @stuartwdouglas this one should be ready now

**Comment by gsmet** [comment]
I'm not totally sure about the default value. I will let @stuartwdouglas decide.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I think 1m is pretty good as a default value. There is no perfect default, but having no default can also cause problems, as clients that have silently gone away can block threads for a long time.

**Pull request merged**
