### PR TITLE
Fix RESTEasy Reactive race

### LINKED ISSUE #19471: SimpleQuarkusRestTestCase#testFormMap sometimes fails with NPE
See the run for this PR: https://github.com/quarkusio/quarkus/pull/19463

```
2021-08-17T19:37:29.9850663Z 2021-08-17 19:37:29,957 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /simple/form-map failed, error id: e3672c38-a3f4-4013-876e-bdeec84f42f8-2: java.lang.NullPointerException
2021-08-17T19:37:29.9853878Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers.getTarget(ContextProducers.java:108)
2021-08-17T19:37:29.9857459Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers.resourceInfo(ContextProducers.java:90)
2021-08-17T19:37:29.9861602Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.create(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.zig:163)
2021-08-17T19:37:29.9866116Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.create(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.zig:194)
2021-08-17T19:37:29.9869160Z 	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:68)
2021-08-17T19:37:29.9870910Z 	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:33)
2021-08-17T19:37:29.9874045Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.arc$delegate(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.zig:60)
2021-08-17T19:37:29.9879272Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.getResourceMethod(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.zig:135)
2021-08-17T19:37:29.9884187Z 	at io.quarkus.resteasy.reactive.server.test.simple.ResourceInfoInjectingFilter.filter(ResourceInfoInjectingFilter.java:19)
2021-08-17T19:37:29.9888838Z 	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:40)
2021-08-17T19:37:29.9893747Z 	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:8)
2021-08-17T19:37:29.9898151Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:133)
2021-08-17T19:37:29.9971999Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:538)
2021-08-17T19:37:29.9974080Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2021-08-17T19:37:29.9976066Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2021-08-17T19:37:29.9977965Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2021-08-17T19:37:29.9980149Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2021-08-17T19:37:29.9982705Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-08-17T19:37:29.9984394Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
These executor dispatch has to be the last thing in the method, to
prevent a possible race

Fixes #19471

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
I'm afraid this broke `AsyncRequestFilterTest` in my fork's CI and I was also able to reproduce it locally:
```
org.opentest4j.AssertionFailedError: expected: <200> but was: <500>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
        at io.quarkus.resteasy.reactive.server.test.resteasy.async.filters.AsyncRequestFilterTest.testRequestFilters(AsyncRequestFilterTest.java:94)
```
I bisected it via:
```
mvn -Dquickly -T6 -pl extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment -am && mvn clean verify -Dtest=AsyncRequestFilterTest -f extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment
```

I have absolutely *no* idea how this passed CI (the test _was_ run).

But it showed at least once in another PR: https://github.com/quarkusio/quarkus/pull/19532#issuecomment-902681416

**Comment by geoand** [comment]
Hm, then I guess we should revert

**Comment by famod** [comment]
It was already backported to 2.1.3. But maybe it's just the test?
On the other hand, the reason it doesn't pop up all the time in CI might be the low concurrency potential given there are only 2 cores...

**Comment by geoand** [comment]
I wouldn't be surprised.

We sometimes get the opposite problem, but I wouldn't be surprised if low concurrency masked the problem this time

**Comment by famod** [comment]
I might have a hint what's going on: The test spits out so many errors that it's hard to see where difference is, but I don't see this before this change:
```
2021-08-20 20:56:53,259 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[executor-thread-1,5,main] threw an uncaught exception: java.lang.RuntimeException: Callback called twice
        at io.quarkus.resteasy.reactive.server.test.resteasy.async.filters.AsyncRequestFilter.lambda$filter$2(AsyncRequestFilter.java:61)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.onComplete(AbstractResteasyReactiveContext.java:354)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.close(AbstractResteasyReactiveContext.java:104)
        at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.close(ResteasyReactiveRequestContext.java:366)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:178)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by famod** [comment]
I actually see the above multiple times, plus there is another new error (also multiple times):
```
2021-08-20 20:56:53,258 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-1) Request failed: java.lang.IllegalStateException: Response has already been written
        at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:394)
        at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:382)
        at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:451)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.end(VertxResteasyReactiveRequestContext.java:311)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:37)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:15)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:135)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by stuartwdouglas** [comment]
The tests pass for me locally but I do see a lot of errors in the logs. 

We probably should fail all our tests if there are errors in the logs (unless explicitly configured otherwise).

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/19568 should sort it out.

**Pull request merged**
