### PR TITLE
Update to Keycloak 10.0.0

### PR DESCRIPTION
**Pull request by sberyozkin**
Original PR is #8965

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hmm. `CodeFlowTest.testIdTokenInjectionJwtMethod` has failed in the Java8 JVM mode, `Security2` is good

**Comment by sberyozkin** [comment]
I've rerun all the tests locally too, all seems good

**Comment by sberyozkin** [comment]
@gsmet Hi, is it looking OK to you ?

**Review by pedroigor — APPROVED** [review]

**Comment by gsmet** [comment]
@sberyozkin I think we need an update on the quickstarts side too!

**Pull request merged**
