### PR TITLE
JUnit5 extension: project vs application root

### PR DESCRIPTION
**Pull request by aloubyansky**
Set project root for tests from the current workspace and application root for tests from external JARs

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
@aloubyansky told me he wanted to add more commits so let's not merge it too soon.

**Comment by gastaldi** [comment]
One way to prevent this is to mark the PR as a draft :wink:

**Comment by aloubyansky** [comment]
Should be ok to merge.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
