### PR TITLE
Update to kafka 2.5.0

### PR DESCRIPTION
**Pull request by schulzp**
I fixed to kafka-streams health check to be compatible with kafka 2.5.0.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Cool, thanks! Let's see what CI has to say.

**Comment by schulzp** [comment]
@gsmet, looks good to me. ;-)

**Comment by gsmet** [comment]
Ah, woot. I didn't think the native tests would pass :).

**Comment by gsmet** [comment]
@cescoffier do you have any specific concern about this upgrade or we can merge now that CI is green?

**Comment by schulzp** [comment]
@gsmet, let me check with a real world project and if that (still) works.

**Comment by schulzp** [comment]
@gsmet , all integration tests pass in our app (with the native build), so I have no concerns. Go for it! :-)

**Comment by cescoffier** [comment]
Yes, it can be merged

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
@schulzp thanks! Keep up the good work :).

**Comment by gsmet** [comment]
@schulzp 

Our Kafka quickstart (https://github.com/quarkusio/quarkus-quickstarts/tree/master/kafka-quickstart) fails in native with the following error:
```Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/692518721.invokeExact_MT(Object, Object, Object)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed.
Detailed message:
Trace: 
	at parsing org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(ByteBufferUnmapper.java:81)
Call path from entry point to org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(String, ByteBuffer): 
	at org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(ByteBufferUnmapper.java:75)
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:206)
	at java.io.FileDescriptor.closeAll(FileDescriptor.java:202)
	at java.io.FileInputStream.close(FileInputStream.java:334)
	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:139)
	at java.nio.channels.spi.AbstractInterruptibleChannel$1.interrupt(AbstractInterruptibleChannel.java:165)
	at java.lang.Thread.interrupt(Thread.java:922)
	at java.io.PrintStream.newLine(PrintStream.java:552)
	at java.io.PrintStream.println(PrintStream.java:807)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:750)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/692518721.invokeExact_MT(Object, Object, Object)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed.
Detailed message:
Trace: 
	at parsing org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(ByteBufferUnmapper.java:81)
Call path from entry point to org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(String, ByteBuffer): 
	at org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(ByteBufferUnmapper.java:75)
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:206)
	at java.io.FileDescriptor.closeAll(FileDescriptor.java:202)
	at java.io.FileInputStream.close(FileInputStream.java:334)
	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:139)
	at java.nio.channels.spi.AbstractInterruptibleChannel$1.interrupt(AbstractInterruptibleChannel.java:165)
	at java.lang.Thread.interrupt(Thread.java:922)
	at java.io.PrintStream.newLine(PrintStream.java:552)
	at java.io.PrintStream.println(PrintStream.java:807)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:750)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/692518721.invokeExact_MT(Object, Object, Object)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed.
Detailed message:
Trace: 
	at parsing org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(ByteBufferUnmapper.java:81)
Call path from entry point to org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(String, ByteBuffer): 
	at org.apache.kafka.common.utils.ByteBufferUnmapper.unmap(ByteBufferUnmapper.java:75)
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:206)
	at java.io.FileDescriptor.closeAll(FileDescriptor.java:202)
	at java.io.FileInputStream.close(FileInputStream.java:334)
	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:139)
	at java.nio.channels.spi.AbstractInterruptibleChannel$1.interrupt(AbstractInterruptibleChannel.java:165)
	at java.lang.Thread.interrupt(Thread.java:922)
	at java.io.PrintStream.newLine(PrintStream.java:552)
	at java.io.PrintStream.println(PrintStream.java:807)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:750)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
	... 7 more
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/692518721.invokeExact_MT(Object, Object, Object)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed.
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.reportUnsupportedFeature(IntrinsifyMethodHandlesInvocationPlugin.java:602)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.processInvokeWithMethodHandle(IntrinsifyMethodHandlesInvocationPlugin.java:500)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.handleInvoke(IntrinsifyMethodHandlesInvocationPlugin.java:220)
	at org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2110)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1793)
	at org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1682)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1630)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1615)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5168)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3286)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3093)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:977)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:871)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
```

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/8762 should take care of it

**Pull request merged**
