### PR TITLE
Allow multiple source directories for Gradle.

### LINKED ISSUE #5539: Multiple sourceDirs for Gradle are not supported.
**Describe the bug**
Multiple `sourceDir`s for Gradle are not supported.

**Actual behavior**
```console
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':time-service.app:quarkusDev' (type 'QuarkusDev').
> Directory '/Users/Projects/marvel/time-service/app/src/main/java:/Users/Projects/marvel-github/time-service/app/src/main/kotlin' specified for property 'sourceDir' does not exist.
...
* Exception is:
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':time-service.app:quarkusDev' (type 'QuarkusDev').
...
Caused by: org.gradle.api.InvalidUserDataException: Directory '/Users/Projects/marvel/time-service/app/src/main/java:/Users/Projects/marvel/time-service/app/src/main/kotlin' specified for property 'sourceDir' does not exist.
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:500)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	... 43 more
```
if specify
```groovy
quarkus {
    setSourceDir("$projectDir/src/main/kotlin")
}
```

a non-sence forlder structure created
```console
./build/classes
├── java
│   ├── main
│   │   └── com
│   │       └── example
│   │           └── marvel ...
│   └── main:
│       └── Users
│           └── Projects
│               └── marvel
│                   └── time-service
│                       └── app
│                           └── build
│                               └── classes
│                                   └── kotlin
│                                       └── main:
│                                           └── Users
│                                               └── Projects
│                                                   └── marvel
│                                                       └── time-service
│                                                           └── app
│                                                               └── build
│                                                                   └── tmp
│                                                                       └── kapt3
│                                                                           └── classes
│                                                                               └── main
│                                                                                   ├── META-INF
│                                                                                   │   └── resources
│                                                                                   │       └── swagger-ui
│                                                                                   └── com
│                                                                                       └── example
│                                                                                           └── marvel ...
└── kotlin
    └── main
        ├── META-INF
        └── com
            └── example
                └── marvel ...

```

**To Reproduce**
```sh
git clone -b quarkus-template git@github.com:soberich/marvel.git marvel && cd $_ && ./gradlew quarkusDev
```

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Environment (please complete the following information):**
```console
------------------------------------------------------------
Gradle 6.0
------------------------------------------------------------

Build time:   2019-11-08 18:12:12 UTC
Revision:     0a5b531749138f2f983f7c888fa7790bfc52d88a

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_232 (AdoptOpenJDK 25.232-b09)
OS:           Mac OS X 10.14.6 x86_64
```

**Additional context**
Quarkus `1.0.0.CR1`

### PR DESCRIPTION
**Pull request by soberich**
Kotlin, annotation processors and/or multi-module projects required multiple directories as sourceDir.

Fixes https://github.com/quarkusio/quarkus/issues/5539

### CODE REVIEW

**Comment by geoand** [comment]
Hi,

Can you please rebase onto master to pick up a fix for CI?

Thank

**Comment by soberich** [comment]
@geoand done. Let's see the CI.

**Comment by soberich** [comment]
@geoand Looks like some ordering problem in Microprofile TCK tests. Not from Quarkus side.

**Comment by soberich** [comment]
@geoand Looks like some ordering problem in Microprofile TCK tests. Not from Quarkus side.
These lines does respect the order, while they should probably not:

https://github.com/eclipse/microprofile-opentracing/blob/0d66079f00f15f6c3be8b5c33b5a0dd60a2baa07/tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpanTree.java#L206-L212

**Comment by geoand** [comment]
For future reference, we are seeing:

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.963 s <<< FAILURE! - in org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests
[ERROR] testMethodNotTraced(org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests)  Time elapsed: 0.058 s  <<< FAILURE!
java.lang.AssertionError: 
expected [[
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.application.TestServerWebServices.simpleTest, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/testServices/simpleTest, span.kind=server], logEntries: []}"
  },
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.rest.client.RestClientServices.restClientMethodTracingDisabled, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/mpRestClient/restClientMethodTracingDisabled, span.kind=server], logEntries: []}"
  }
]
] but found [[
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.rest.client.RestClientServices.restClientMethodTracingDisabled, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/mpRestClient/restClientMethodTracingDisabled, span.kind=server], logEntries: []}"
  },
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.application.TestServerWebServices.simpleTest, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/testServices/simpleTest, span.kind=server], logEntries: []}"
  }
]
]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:442)
	at org.eclipse.microprofile.opentracing.tck.OpenTracingBaseTests.assertEqualTrees(OpenTracingBaseTests.java:227)
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testNotTraced(OpenTracingMpRestClientTests.java:166)
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testMethodNotTraced(OpenTracingMpRestClientTests.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.jboss.arquillian.testng.Arquillian$2.invoke(Arquillian.java:145)
	at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:139)
	at org.jboss.arquillian.testng.Arquillian.run(Arquillian.java:138)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:576)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OpenTracingMpRestClientTests>Arquillian.run:138->testMethodNotTraced:116->testNotTraced:166->OpenTracingBaseTests.assertEqualTrees:227 expected [[
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.application.TestServerWebServices.simpleTest, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/testServices/simpleTest, span.kind=server], logEntries: []}"
  },
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.rest.client.RestClientServices.restClientMethodTracingDisabled, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/mpRestClient/restClientMethodTracingDisabled, span.kind=server], logEntries: []}"
  }
]
] but found [[
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.rest.client.RestClientServices.restClientMethodTracingDisabled, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/mpRestClient/restClientMethodTracingDisabled, span.kind=server], logEntries: []}"
  },
  {
    span: "{ operationName: GET:org.eclipse.microprofile.opentracing.tck.application.TestServerWebServices.simpleTest, tags: [component=jaxrs, http.method=GET, http.status_code=200, http.url=http://localhost:8081/rest/testServices/simpleTest, span.kind=server], logEntries: []}"
  }
]
]
[INFO] 
```

@kenfinnigan @objectiser any idea?

**Comment by kenfinnigan** [comment]
I think the order is important, as it implies the spans were collected in a different sequence

**Comment by geoand** [comment]
I restarted the failing test, let's see what happens

**Comment by geoand** [comment]
Test failure seems to be unrelated (#https://github.com/quarkusio/quarkus/issues/5569)

**Comment by soberich** [comment]
@geoand I reran. It's fine now.

**Comment by geoand** [comment]
@aloubyansky @gastaldi mind taking a look please?

**Comment by soberich** [comment]
@geoand BTW. After say it is merged, is this going to be in snapshot repo as `999-SNAPSHOT`?

**Review by aloubyansky — APPROVED** [review]
Looks good to me, I haven't tried it though. It'd be good to have a test for this. Thanks a lot @soberich 
I'll let @gastaldi to comment before merging this.

**Comment by geoand** [comment]
@soberich everything build locally uses `999-SNAPSHOT`. Is that what you mean?

**Review by gastaldi — APPROVED** [review]
LGTM, as @aloubyansky mentioned, it would be nice to have some tests too

**Comment by gsmet** [comment]
@gastaldi I thought we didn't have any Gradle ITs anyway? Or did the situation change?

**Comment by gastaldi** [comment]
@gsmet you're right, we need to add some and change the pom.xml to build using Gradle instead

**Comment by gsmet** [comment]
So, given we don't have any tests, did someone try this manually and confirm it's working as advertised.

If so let's merge. The bad Gradle testing situation shouldn't block this PR.

**Comment by geoand** [comment]
I'll hopefully try this over the weekend

**Comment by cescoffier** [comment]
@geoand I let you merge once you checked it.

**Comment by soberich** [comment]
It doesn't work. The approach taken by Quarkus plugin hardly fits in Gradle integration. In many cases Gradle will have multiple dirs in sources, classes, resources, etc in project layout.
Quarkus plugin is too opinionated on in this sence. It expects something like absolute path for a single file or `java.nio.file.Path` in many places which is not the case.
For example `io.quarkus.dev.DevModeContext.ModuleInfo#ModuleInfo` ctor expects `String classesPath,...` while in reality it will be 
```
build
    classes
        java
        kotlin
        scala
    ...
```
also `java.lang.ProcessBuilder#directory(java.io.File)` calls should simply get `/build`, because now it gets `path:path:path` from Gradle.
so without re-write of `quarkus-development-mode` it will be a crutch.
Ideally all api for development mode should assume Collection of Files.

**Comment by geoand** [comment]
I tested it and it works great. Thanks a lot @soberich !

**Comment by soberich** [comment]
@geoand It does cover a bunch of cases but definitely not all of them. I want to open another PR because locally I already started something. I am not sure how fast would it go. Is this ok?

**Comment by soberich** [comment]
Actually, I am not sure we should've merge it.
@geoand I thought after my comment you won't. Because there is something quite important.
For example, I got NPE here
https://github.com/quarkusio/quarkus/blob/2ea45abd1fb087700e681f12998207f8a0f30f46/devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java#L82
`uberJar` is null and unboxing throws.

**Comment by geoand** [comment]
@soberich OK, I opened a PR to revert this one: #5727.
I'll merge it and then you can work on a new one as you see fit. Does that sound good?

**Pull request merged**
