### PR TITLE
Make sure correct runtime configuration is resolved before running quarkusGenerateCode

### LINKED ISSUE #24260: Gradle quarkusGenerateCode task with composite build dependency causes jar does not exist
### Describe the bug

Our gradle composite build intermittently fails with dependent jars not existing (see below sample output). It always fails on the quarkusGenerateCode task of a module that depends on a jar produced by the included build. We don't usually run this task directly, but running it directly reproduces the issue much more consistently.

```
> Task :service-mocks:aws-orchestration-mock:quarkusGenerateCode FAILED
preparing quarkus application

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':service-mocks:aws-orchestration-mock:quarkusGenerateCode'.
> [...]/quarkus-composite-build-issue/common/common-util/build/libs/common-util-1.0.jar does not exist
```

### Expected behavior

I should be able to run the gradle quarkusGenerateCode task and dependencies should correctly be resolved prior to execution.

### Actual behavior

quarkusGenerateCode task fails with an error indicating the composite build dependency jar does not exist

### How to Reproduce?

From the root of the attached project if you run the gradle command:

`./gradlew :common:common-util:clean :services:acme-service:clean :services:acme-service:quarkusGenerateCode`

It should reproduce the issue. There is a commented out line in `services/acme-service/build.gradle` that adds an explicit dependency on the included composite build's jar task that can be used as a workaround.

[quarkus-composite-build-issue.zip](https://github.com/quarkusio/quarkus/files/8227922/quarkus-composite-build-issue.zip)

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.3.0

### Output of `java -version`

openjdk version "11.0.11"

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glefloch**
This makes sure the correct runtime configuration is resolved before the task is run. 

close #24260

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]
Thanks @glefloch !

**Comment by gsmet** [comment]
@glefloch I tried to backport that one and I end up with compilation issues. I'm not sure if it's easily fixable without backporting significant changes that we wouldn't want in 2.7. Any chance you could have a look and tell me if things are easy to sort out or not?

**Comment by glefloch** [comment]
Yes sure, looking at it.

**Comment by glefloch** [comment]
It should be that hard, I will push a backport

**Pull request merged**
