### PR TITLE
Support for multi tenancy root mode

### LINKED ISSUE #35424: How support multiple tenant root with hibernate6 ?
## In Springboot
application.yml
```yml
spring:
  jpa:
    properties:
      hibernate:
        multiTenancy: true
        tenant_identifier_resolver: com.example.config.TenantResolver
```
TenantResolver.java
```java
public interface CurrentTenantIdentifierResolver {
        // set tenant value
	String resolveCurrentTenantIdentifier();
   
        // true will query all tenant data
	default boolean isRoot(String tenantId) {
		return false;
	}
}
```

## But in Quarkus 3.x

I can not find how to query ignore tenant like `CurrentTenantIdentifierResolver .isRoot`

application.properties
```properties
quarkus.hibernate-orm.multitenant=DISCRIMINATOR
```

CustomTenantResolver.java
```java
@PersistenceUnitExtension
@RequestScoped
public class CustomTenantResolver implements TenantResolver {

  // what is this ?
  @Override
  public String getDefaultTenantId() {
    return "0";
  }

  @Override
  public String resolveTenantId() {
    return Optional.ofNullable(TenantUtil.getTenantId()).map(Serializable::toString).orElse(null);
  }
}
```

### Implementation ideas

like this

```java
        // true will query all tenant data
	default boolean isRoot(String tenantId) {
		return false;
	}
```

### PR DESCRIPTION
**Pull request by seepine**
Fixes #35424

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]
LGTM, thanks a lot!

Let's merge if CI passes.

**Comment by yrodiere** [comment]
Looks like some imports are not sorted automatically.

I'll fix it and force-push to your branch for this PR.

You might want to look into [this](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style) for your next PR :)

**Comment by yrodiere** [comment]
> > Looks like some imports are not sorted automatically.
> > I'll fix it and force-push to your branch for this PR.
> > You might want to look into [this](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style) for your next PR :)
> 
> Sorry i overlooked [this](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style)
> 
> Perhaps I still need to remove imports* ?
> 
> ```java
> import static org.hamcrest.Matchers.*;
> ```
> 
> ```
> Next, disable wildcard imports: navigate to Editor -> Code Style -> Java -> Imports and set Class count to use import with '*' to 999. Do the same with Names count to use static import with '*'.
> ```

If this was in your PR, yes that was probably the problem. I didn't look, I just executed `./mvnw process-sources` and let it automatically fix all problems :sweat_smile:

**Review by yrodiere — APPROVED** [review]

**Comment by yrodiere** [comment]
Merged, will be available in Quarkus 3.4. Thanks again!

**Comment by gsmet** [comment]
If you need it sooner and given I think it doesn't break anything (@yrodiere do you confirm?), I could be convinced to backport it to the next 3.3 micro.

**Comment by yrodiere** [comment]
> given I think it doesn't break anything (@yrodiere do you confirm?)

Yes it does seem safe.

**Pull request merged**
