### PR TITLE
Make mutable-jar work with jib in all cases

### LINKED ISSUE #15477: Add support for mutable-jar package format for container image extensions
**Description**
Currently there is no way to use container image extensions (jib or docker)  to build a valid image for remote dev mode. When following the guide on build maven based quarkus app it does not mention this limitation and building the image results in exception at runtime

````
Exception in thread "main" java.nio.file.NoSuchFileException: /work/lib/deployment/deployment-class-path.dat
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:39)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:35)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
````

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #15477

### CODE REVIEW

**Comment by geoand** [comment]
@mswiderski mind giving it a try please?

It worked fine for me

**Comment by mswiderski** [comment]
Sure thing @geoand will take it first thing in the morning and let you know

**Comment by geoand** [comment]
Thanks

**Comment by mswiderski** [comment]
@geoand I tried it and now container is build with the required files but it does not seem to start. Kubernetes is reporting it as running but there are no logs written by the container. When logging into the container itself it shows java process running but none of the app endpoints are accessible.

No idea how to trace what is going wrong there....

**Comment by geoand** [comment]
What happens when you run the container locally?
Do you have any logs in that case?

**Comment by mswiderski** [comment]
same thing, no logs ... just hangs

as soon as I set `-e QUARKUS_LAUNCH_DEVMODE=true` then it results in such a hang. Without that it starts without issues

**Comment by geoand** [comment]
I'll have a look later on today.

Thanks for checking

**Comment by mswiderski** [comment]
it's reproducible as well without docker/kube just do following

````
export QUARKUS_LAUNCH_DEVMODE=true
java -jar target/quarkus-app/quarkus-run.jar
````

and it hangs without any log message

And here is a threads that are active in the app via jconsole
image
looks bit short list ...

**Comment by geoand** [comment]
I can't reproduce the problem in either regular `java -jar` or `docker run`.

Do you have a reproducer you could share?

**Comment by mswiderski** [comment]
interesting ....

about reproducer it won't be easy as it relies on quite few unreleased yet version of different libraries... working on operator. Don't want you to build up everything from sources etc so maybe you could give me a hint where to start debugging (the bootstrap code) so maybe I could gather more info?

**Comment by geoand** [comment]
I would start debugging in `QuarkusEntryPoint`, move on to `DevModeTask` to see if the augmentation was performed properly and then see what `IsolatedDevModeMain` is doing

**Comment by mswiderski** [comment]
Alright, debugging showed this exception when starting 

````
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor#config threw an exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.config(ConfigEditorProcessor.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

````

it is thrown from `io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart` when calling `StartupAction start = augmentAction.createInitialRuntimeApplication();`

here is the list of extensions in use

````
cdi, kubernetes, kubernetes-client, operator-sdk, resteasy, resteasy-jackson, security, smallrye-health, smallrye-openapi, swagger-ui
````

**Comment by geoand** [comment]
I was still not able to reproduce the problem with the extensions you mentioned.

Also `ConfigEditorProcessor.java:37` is rather odd as I don't see how it can cause a NPE

**Comment by mswiderski** [comment]
ok, correction when it comes to line number as I am running on top of 1.12.0.CR1 - https://github.com/quarkusio/quarkus/blob/1.12.0.CR1/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/ConfigEditorProcessor.java#L37

and the failure is because of `DevConsoleManager.getHotReplacementContext()` return null

**Comment by geoand** [comment]
OK, that part has changed significatly. Would it possible for you to try `master`?

**Comment by mswiderski** [comment]
most likely won't be that simple but will do so as it seems it has changed quite a bit. Will report back when done the testing on top of master

**Comment by mswiderski** [comment]
@geoand anyway I think we can proceed with this PR to be merged as it does fix the container image build with jib for mutable-jar

the other issue I ran into is independent of this change. I can either post back the results here or on the mailing list thread.

**Comment by geoand** [comment]
I was going to propose the same :).

Feel free to post the results back here and then we can discuss how to proceed

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by mswiderski** [comment]
@geoand running on top of master I get this

````
2021-03-05 13:47:05,497 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to create compiler, runtime compilation will be unavailable: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at io.quarkus.deployment.dev.ClassLoaderCompiler.lambda$new$0(ClassLoaderCompiler.java:149)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at io.quarkus.deployment.dev.ClassLoaderCompiler.<init>(ClassLoaderCompiler.java:144)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.setupRuntimeCompilation(IsolatedDevModeMain.java:222)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:372)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:127)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
	at io.quarkus.deployment.mutability.DevModeTask.main(DevModeTask.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:50)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:35)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
````

**Comment by geoand** [comment]
Can you open a new issue with that information?

**Comment by mswiderski** [comment]
@geoand here it is https://github.com/quarkusio/quarkus/issues/15494

**Comment by famod** [comment]
**Offtopic**: Can we leave this open for a little while? By chance I picked this PR to check how the incremental build is doing in and in this case here it is builidng too much and I'm trying to understand why.
GIB is actually detecting a BOM change, which this PR doesn't have. 
`PULL_REQUEST_BASE` yields https://github.com/quarkusio/quarkus/commit/d7a96af1288f68fc0734d921c00b36729736abfd and I suppose this is where you started your this change @geoand?

/cc @gsmet

**Comment by geoand** [comment]
Sure, I'll leave it open, no problem. 

I don't remember exactly where I started from since I may have rebased but that commit does sound about right

**Comment by famod** [comment]
@geoand I've already found the problem. Feel free to do whatever you like with this PR (e.g. merging). 😜

**Comment by geoand** [comment]
Neat! What was the problem?

**Comment by famod** [comment]
@geoand 
Well, it still _is_ a problem but it might be as easy as swapping a `.sha` to `.ref` in the workflow file. 🤓 
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Incremental.20build/near/228975996

**Pull request merged**
