### PR TITLE
Replace hardcoded ASM version with Gizmo.ASM_API_VERSION

### PR DESCRIPTION
**Pull request by gwenneg**
Integration of https://github.com/quarkusio/gizmo/commit/0b7911390fef81f706af36a94efe7a81eb4095be into Quarkus.

### CODE REVIEW

**Comment by gwenneg** [comment]
`Opcodes.ASM7` is also present in `ReflectionAgent` from `quarkus-devtools-reflection-agent` but this module depends directly on `org.ow2.asm:asm` instead of `io.quarkus.gizmo:gizmo`.

**Comment by geoand** [comment]
Seems reasonable, but there is a compilation failure:

```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/vsts/work/1/s/extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessEnhancer.java:[27,19] cannot find symbol
  symbol:   variable Gizmo
  location: class io.quarkus.panache.common.deployment.PanacheFieldAccessEnhancer.FieldAccessClassVisi
```

**Comment by gwenneg** [comment]
Sorry, it was late when I submitted this PR and I didn't have the courage to wait for the end of my local build :)

**Comment by geoand** [comment]
No worries 👍

**Comment by gsmet** [comment]
I haven't look into the details but just one note:
- we need to use this constant when using Gizmo;
- in a ByteBuddy context (this might be relevant for some parts of ORM), we would need to use `OpenedClassReader.ASM_API` which will be used by ORM soon.

Could you check?

**Comment by gwenneg** [comment]
Ok @gsmet I will check.

**Comment by gwenneg** [comment]
I replaced `Gizmo.ASM_API_VERSION` with `OpenedClassReader.ASM_API` in `HibernateEntityEnhancer` as we're clearly in a ByteBuddy context there.

I'm really not sure about the 5 `Panache*` classes and `ProjectionForEnhancer`. These classes are all belong to Panache extensions but it doesn't look like they're used in a ByteBuddy context. This will need to be double-checked.

For all other classes, ByteBuddy doesn't seem involved at all.

**Comment by gsmet** [comment]
This PR needs a rebase, unfortunately.

**Comment by gwenneg** [comment]
Rebase done.

**Review by cescoffier — APPROVED** [review]
LGTM.

**Review by gsmet — APPROVED** [review]
Thanks for having a look at that one.

**Pull request merged**
