### PR TITLE
Properly apply MongoClientConfig.socketTimeout

### LINKED ISSUE #8026: MongoClientConfig socketTimeout don't actually set a socket timeout
**Describe the bug**

Setting the property `quarkus.mongodb.socket-timeout` that translates to `MongoClientConfig` field `Optional<Duration> socketTimeout` have no effect whatsoever.

The socket configuration sets only the connection timeout but not the read timeout (this may hangs thread indefinitely).

See:

https://github.com/quarkusio/quarkus/blob/1.3.0.Final/extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/AbstractMongoClientProducer.java#L198

https://mongodb.github.io/mongo-java-driver/3.12/javadoc/com/mongodb/connection/SocketSettings.Builder.html#readTimeout(int,java.util.concurrent.TimeUnit)

**Expected behavior**

Being able to set both connection and read timeout and use the configured values to actually configure the Mongo client socket settings.

**Actual behavior**

Socket timeout value not used, socket configuration partial:

https://github.com/quarkusio/quarkus/blob/1.3.0.Final/extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/AbstractMongoClientProducer.java#L198

**To Reproduce**
- Configure the client and lock the socket after connection
- Simply search the codebase for `socketTimeout`

**Configuration**
```properties
quarkus.mongodb.socket-timeout
quarkus.mongodb.connect-timeout
```

**Screenshots**
Not related

**Environment (please complete the following information):**
Not related, every platform

**Additional context**
Tried to lock the socket after connection using a firewall and connection hangs in read wait indefinitely.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #8026

The property should probably be renamed to `readTimeout` in a later version

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand considering it didn't work before, maybe it's the best time to rename it?

**Comment by geoand** [comment]
I am fine with that, but are we ok doing it in a patch release?

**Comment by geoand** [comment]
I pushed a 2nd commit that renames the property in case we decide we want the change in the 1.3.x line

**Comment by gsmet** [comment]
Yeah, I'll think about it.

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
I backported both, I'll add a note in the release notes.

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
