### PR TITLE
Fix race condition on reactive client with streaming and SSE responses

### LINKED ISSUE #16227: Investigate io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase#testClientStreaming
`io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase#testClientStreaming` has been disabled in the Vert.x 4 branches due to some random failure on CI. 

Also:
`io.quarkus.resteasy.reactive.jsonb.deployment.test.sse.SseTestCase#testMultiFromMulti`

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #16227

### CODE REVIEW

**Comment by geoand** [comment]
I used JUnit's `@RepeatedTest(1000)`  (and even then did multiple runs) locally to ensure that these tests are not flaky any more with this fix

**Review by FroMage — COMMENTED** [review]
So hold on, the fix is which part? Is it a double call to `complete()` or a double call to `close(true)`? Both?

IIRC `closeHandler` was called when the server dropped the connection without ending/responding it. I'm not sure we have tests in place for this case (not sure how we could).

**Comment by FroMage** [comment]
Oh, close _before_ handler for items. Damn. Huh. Oh well, I guess we can fix this and wait until any bug related to connection dying appear later. But, then please add a comment in both cases to explain why there's no `closeHandler` pointing to this issue because we'll never remember to not add it ;)

**Comment by geoand** [comment]
Will do

**Comment by geoand** [comment]
PR updated

**Review by FroMage — APPROVED** [review]
Great, thanks!

**Review by cescoffier — APPROVED** [review]
But worried about closing.

**Comment by geoand** [comment]
Yeah, we'll have to see...

**Comment by gsmet** [comment]
Rebased to get the latest CI fixes.

**Pull request merged**
