### PR TITLE
Document package name values usage in quarkus.jaxb.exclude-classes property

### PR DESCRIPTION
**Pull request by gnieser**
Hello,

This PR suggests an update to documentation next to https://github.com/quarkusio/quarkus/pull/31940

Have a nice day

### CODE REVIEW

**Comment by gnieser** [comment]
Hi, is there anything I shall do to fix this?

**Review by gsmet — APPROVED** [review]
Sorry for the delay and thanks for this change, I will merge it!

**Comment by gsmet** [comment]
Ah wait, there is a conflict now, I will have a look.

**Comment by gsmet** [comment]
Actually, this has been addressed by some other PRs.

Thanks for taking the time to create the PR and sorry for the delay, it fell through the cracks.

**Pull request closed without merging**
