### PR TITLE
Add dependencies with provided scope in test mode

### LINKED ISSUE #22552: Continuous testing doesn't support `provided` dependencies
### Describe the bug

Using a class from a `provided` scoped dependency in a test (in whichever way) results in a `ClassNotFoundException` when the test is run in continuous testing mode.

### Expected behavior

Class is found, just like when surefire is running the test.

### Actual behavior

`ClassNotFoundException`

### How to Reproduce?

[q_ct-provided.zip](https://github.com/quarkusio/quarkus/files/7790968/q_ct-provided.zip)

- `mvn clean verify` does not fail (`ProvidedTest` passes)
- `mvn quarkus:dev`
- resume tests
- fails with: 
  ```
  ERROR [io.qua.test] (Test runner thread) Test ProvidedTest#load() failed: java.lang.NoClassDefFoundError: lombok/experimental/SuperBuilder
          at org.acme.ProvidedTest.load(ProvidedTest.java:11)
  Caused by: java.lang.ClassNotFoundException: lombok.experimental.SuperBuilder
          at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
          at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
          at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
          ... 1 more
  ```

lombok might be a strange example, but in my real project I have a test based on `javaparser` that verifies the expected usage of lombok annotations (which have source retention, so ArchUnit is not usable here).

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

Probably related: https://github.com/quarkusio/quarkus/blob/723663953f2c54fed473021a04d169047c693572/core/deployment/src/main/java/io/quarkus/deployment/dev/testing/TestSupport.java#L196-L201

### LINKED ISSUE #23078: Continuous testing can fail after `mvn test` when run without `clean`
### Describe the bug

I added a workaround to my project for #22552 which is setting the scope of lombok to `test` instead of `provided` via a specific `qtest` maven profile (that has `<defaultGoal>quarkus:test</defaultGoal>`).
This works if cont' testing is started on a "clean" state, but if regular testing was run before via `mvn test`, this workaround does not have any effect anymore.
In other words, I have to run `mvn clean quarkus:test` (clean!) if `mvn test` was run before, which is cumbersome and wastes time if you have many classes to generate/compile. It's also easy to forget.

### Expected behavior

Cont' testing should re-setup dependencies (if needed) and should not rely on what `mvn test` has left behind.

### Actual behavior

Doesn't re-setup dependencies and reuses what `mvn test` has left behind, which in this case means failing bedcause of the `provided` issue.

### How to Reproduce?

[q_ct-provided-2.zip](https://github.com/quarkusio/quarkus/files/7909031/q_ct-provided-2.zip) (note: uses 999-SNAPSHOT)

- `mvn quarkus:test -Dlombok.scope=test` (ok)
- `mvn clean test` (ok)
- `mvn quarkus:test -Dlombok.scope=test` (fails with `ClassNotFoundException`)
- `mvn clean quarkus:test -Dlombok.scope=test` (ok)

PS: This reproducer simply toggles the scope via a property instead of via a profile, but that's not relevant.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.3.Final and current 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

FWIW, `-Dquarkus.bootstrap.effective-model-builder=true` doesn't make a difference.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes https://github.com/quarkusio/quarkus/issues/23078, https://github.com/quarkusio/quarkus/issues/22552

### CODE REVIEW

**Comment by famod** [comment]
Looking good in my "real" project (w.r.t. that JavaSourceTest loading lombok classes)! Thanks!

I'm a bit puzzled though how this fixes #23078?
I mean, ok, I don't need to bump the scope via a profile or property anymore (because the `provided` problem is fixed) but for other classpath-relevant use cases there is still the need to `clean`, no?
I do understand if you say this is a won't fix. But what about a clear-cache goal or similar? So that you don't have to go through everything again (compile etc.)? Not sure I'm making sense here. 😄

**Comment by aloubyansky** [comment]
You mean you want to be modifying scopes or classpath in general with a system property on the command line? 
We actually used to have a system property that was disabling classpath caching. Perhaps, it's time to re-evaluate the gains of this cache at all.

**Comment by famod** [comment]
> You mean you want to be modifying scopes or classpath in general with a system property on the command line?

Well, my thought was was simple (and maybe stupid): If I changed/set/configured something I know has incluence on classpath, I'd rather just remove that cache instead of the entire `target` directory.
For that I thought a separate mojo (or flag for the existing mojos) could come in handy.
But then again this is probably too specific to be of real use for the majority of users.

> We actually used to have a system property that was disabling classpath caching.

This is more or less the flag solution I mentioned above.

> Perhaps, it's time to re-evaluate the gains of this cache at all.

Good idea!

**Comment by aloubyansky** [comment]
It depends how you apply the change currently. We check whether the workspace (all the poms) have changed since the last cache update. If it has changed, we re-resolve the app model. However, if you do it using command line arguments, you have to use clean currently.

**Comment by famod** [comment]
> However, if you do it using command line arguments, you have to use clean currently.

Which includes profile activation (manual or automatic), right?

**Review by famod — APPROVED** [review]
I scanned the code and it LGTM (and fixes the `provided` issue).

**Comment by aloubyansky** [comment]
> > However, if you do it using command line arguments, you have to use clean currently.
> 
> Which includes profile activation (manual or automatic), right?

Right.

**Comment by aloubyansky** [comment]
If you activate a profile though, it depends, but chances are you may want to recompile anyway if the profile modifies the dependency graph.

**Comment by famod** [comment]
It's very unlikely that (all) those failures are related. I'll restart CI regardless...

**Comment by famod** [comment]
This one test failure looks related:
```
java.nio.file.NoSuchFileException: src/main/resources/overrides
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472)
        at io.quarkus.tck.graphql.TestInterceptor.loadSchemaOverride(TestInterceptor.java:66)
```

**Comment by famod** [comment]
The above message does not seem to be the actual problem. Instead I see:
```
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 6 deployment problems:
[1] Ambiguous dependencies for type org.eclipse.microprofile.graphql.tck.apps.superhero.db.HeroDatabase and qualifiers [@Default]
        - java member: org.eclipse.microprofile.graphql.tck.apps.superhero.api.HeroFinder#heroDB
        - declared on CLASS bean [types=[org.eclipse.microprofile.graphql.tck.apps.superhero.api.HeroFinder, java.lang.Object], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.graphql.tck.apps.superhero.api.HeroFinder]
        - available beans:
                - CLASS bean [types=[org.eclipse.microprofile.graphql.tck.apps.superhero.db.HeroDatabase, java.lang.Object], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.graphql.tck.apps.superhero.db.HeroDatabase]
                - CLASS bean [types=[org.eclipse.microprofile.graphql.tck.apps.superhero.db.HeroDatabase, java.lang.Object], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.graphql.tck.apps.superhero.db.HeroDatabase]
```
(many more)

**Comment by aloubyansky** [comment]
In the test setup these classes are added to the WebArchive
````
public class DeployableUnit {
    
    private DeployableUnit(){}
    
    public static Archive<?> getDeployment(String unitName) throws Exception {
        return ShrinkWrap.create(WebArchive.class, unitName + ".war")
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml")
                .addAsManifestResource(
                        new StringAsset(getPropertyAsString()),
                        "microprofile-config.properties")
                .addPackage(HeroFinder.class.getPackage())
                .addPackage(HeroDatabase.class.getPackage())
                .addPackage(SuperHero.class.getPackage())
                .addPackage(ScalarTestApi.class.getPackage());
    }
````
And the test also depends on the JAR providing these classes.

**Comment by aloubyansky** [comment]
A workaround could be
````
diff --git a/tcks/microprofile-graphql/pom.xml b/tcks/microprofile-graphql/pom.xml
index 8fc6136fe5..fb51de26b8 100644
--- a/tcks/microprofile-graphql/pom.xml
+++ b/tcks/microprofile-graphql/pom.xml
@@ -29,6 +29,10 @@
                     <suiteXmlFiles>
                         <suiteXmlFile>testng.xml</suiteXmlFile>
                     </suiteXmlFiles>
+                    <systemPropertyVariables>
+                        <quarkus.arc.exclude-dependency.graphql-tck.group-id>org.eclipse.microprofile.graphql</quarkus.arc.exclude-dependency.graphql-tck.group-id>
+                        <quarkus.arc.exclude-dependency.graphql-tck.artifact-id>microprofile-graphql-tck</quarkus.arc.exclude-dependency.graphql-tck.artifact-id>
+                    </systemPropertyVariables>
                 </configuration>
````

**Comment by aloubyansky** [comment]
I pushed a workaround as a separate commit. Perhaps @phillip-kruger or @mkouba could comment on whether this change is acceptable.
I see in other TCK tests the MP TCK dependencies are compile dependencies. In the GraphQL module it's `provided` exactly to exclude it from indexing.
Alternatively, we could still add provided dependencies to the Quarkus classpath but by default exclude them from indexing, which would be worth, IMO.

**Comment by mkouba** [comment]
> I pushed a workaround as a separate commit. Perhaps @phillip-kruger or @mkouba could comment on whether this change is acceptable.

Whatever makes the TCK tests pass is acceptable ;-). No seriously, I think it's fine. @phillip-kruger any objections?

**Comment by aloubyansky** [comment]
If we are to merge it before 2.7.0.Final, it's better to do it ASAP. So we can check its effects on status.quarkus.io

**Comment by famod** [comment]
I suggest do merge now. We can improve on the TCK aspects later, if required.

**Comment by glefloch** [comment]
@aloubyansky, should we do the same thing in the gradle plugin with `runtimeOnly` dependencies?

**Comment by aloubyansky** [comment]
Aren't they already? @glefloch

**Comment by glefloch** [comment]
I don't think so, I can't find any reference to `RUNTIME_ONLY` configuration

**Comment by aloubyansky** [comment]
They should be included @glefloch

**Comment by glefloch** [comment]
They are indeed !

**Pull request merged**
