### PR TITLE
Provide unique information in secret/configmap ConfigSource

### LINKED ISSUE #15247: A way to determine exactly what secret/configmap was used by quarkus-kubernetes-config
**Description**
We would like our application to restart it's own container when it detects that relevant configuration has changed.  Currently all we can determine from the config names created by quarkus-kubernetes-config is the secret/configmap name.

**Implementation ideas**
This could be as simple as just providing a full name: https://github.com/quarkusio/quarkus/compare/master...shawkins:master which adds the namespace, uid, and resourceVersion.  Or it could create a new interface for the returned configs that a similar set of information.

### PR DESCRIPTION
**Pull request by shawkins**
Resolves: #15247

### CODE REVIEW

**Review by geoand — APPROVED** [review]
I like it, thanks!

**Comment by shawkins** [comment]
Corrected the formatting and a misspelling.

**Comment by geoand** [comment]
Can you please squash the commits?

Thanks

**Comment by shawkins** [comment]
No problem, it's squashed now.

**Comment by geoand** [comment]
👍🏼

**Pull request merged**
