### PR TITLE
Watch for index.html creation

### LINKED ISSUE #40829: dynamic default page can't handle I add a index.html file
### Describe the bug

I add `META-INF/resources/index.html` and refresh index page I still get http://localhost:8080/q/dev-ui/welcome but this is visible in logs:

```
2024-05-24 10:10:44,589 ERROR [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-4) Failed to copy resources: java.nio.file.NoSuchFileException: /Users/manderse/code/jconqbot/target/classes/index.html
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:291)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForFileChange(RuntimeUpdatesProcessor.java:970)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:464)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:442)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:161)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:148)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #40829

In this PR:

- Added a watch for index.html
- Make sure to always watch META-INF for changes
- Clean up some stacktraces that print in the log
- Make the logo in the welcome page clickable, so when you created your own index.html, you can click the logo to re-try

index

### CODE REVIEW

**Comment by geoand** [comment]
Nice!

@phillip-kruger I think these changes warrant separate commits, WDYT?

**Comment by phillip-kruger** [comment]
So this problem was always there. In a Quarkus 3.8 if you remove the generated index.html. Then Build and start in dev mode, then add a index.html, you will get the same error. The only difference is in 3.8 you get the 404 page and currently you get the welcome page

**Comment by phillip-kruger** [comment]
@geoand I don't really have an opinion on the separate commits. We usually squash all commits. They are all related to the fix, but I am happy to redo with more commits.

**Comment by geoand** [comment]
Yeah, I think that since you are fixing multiple partially unrelated things, it makes sense to split into separate commits.

**Comment by phillip-kruger** [comment]
@geoand - ok split into 3 commits.

**Review by geoand — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
