### PR TITLE
Remove Kotlin from dependabot config

### PR DESCRIPTION
**Pull request by gastaldi**
Closes #6051

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
I'm not entirely sure I agree tbh. It's a nice reminder and we could have changed the other version manually.

Not sure it's better to ship with an outdated Kotlin, given how Kotlin people are bleeding edge.

**Comment by gastaldi** [comment]
In this case, we should dedicate some time to see if we can reduce everything to just use one version (as suggested by @geoand). I can provide a PR reverting this commit if you like

**Comment by geoand** [comment]
Well I think it's better to ship an outdated but consistent experience.
Of course ideally we would have the Kotlin version in a single place and then be able to use the bot. I think we should look into doing this.

**Comment by gsmet** [comment]
Well, it would be consistent if we add a commit when the bot creates a PR. I'm not saying it shouldn't be.

I can see how people might be tempted to just merge things when CI is green though.

And yes, I agree we should try to fix this issue somehow.

**Comment by geoand** [comment]
Exactly, it would be too easy to just merge when everything is green and forgetting about the other properties.
I can absolutely see that happening to me 😁.

I'll try and take a look over the weekend and see if we can unify the Kotlin version properties in an easy way.

**Pull request merged**
