### PR TITLE
Add resteasy-reactive jaxb support

### LINKED ISSUE #20298: resteasy-reactive jaxb support
### Description

I am needing jaxb support in resteasy-reactive (server), since some of my resources return xml.
Currently, I use the whole resteasy-classic stack, combined with resteasy-jaxb for my application.

Jaxb support in the server part of resteasy-reactive is (afaik) the last missing piece for my migration away from resteasy-classic.

### Implementation ideas

Support jaxb in a similar fashion like it was done for jackson, i.e. add a specific servermessagebody reader and writer.

See also the resteasy jaxb provider:
https://github.com/resteasy/resteasy/tree/main/providers/jaxb

### PR DESCRIPTION
**Pull request by Sgitario**
Add extension to have XML support for Resteasy Reactive. Example:

Add dependency into Maven:

```xml
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jaxb</artifactId>
</dependency>
```

Create pojo:

```java
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Person {

    private String first;

    @NotBlank(message = "Title cannot be blank")
    private String last;

    public String getFirst() {
        return first;
    }

    public void setFirst(String first) {
        this.first = first;
    }

    public String getLast() {
        return last;
    }

    public void setLast(String last) {
        this.last = last;
    }
}
```

And the resource:

```java
@GET
    @Path("/person")
    public Person getPerson() {
        Person person = new Person();
        person.setFirst("Bob");
        person.setLast("Builder");
        return person;
    }
```

It works fine with blocking and non blocking.

Resolves https://github.com/quarkusio/quarkus/issues/20298

### CODE REVIEW

**Review by Postremus — CHANGES_REQUESTED** [review]
I have 2 points which should be adressed.
Please see the comments I left, they apply to multiple similar places in the changes.

* `JAXB.marshal` / `JAXB.unmarshal` creates internally a `JAXBContext`. The context however can be perfectly cached.
* We can only read / write `@XMLRootElement` anyway. We should therefore check for this annotation in isWritable / isReadable

**Comment by Sgitario** [comment]
@geoand @Postremus I've already addressed all your comments. Feel free to take another look. Thanks!

**Comment by geoand** [comment]
LGTM, but I'll leave the final approval to @Postremus because he knows way more about JAXB than I do.

**Review by gsmet — DISMISSED** [review]
Could you please clarify the codestart part before we merge? Thanks!

**Review by Postremus — CHANGES_REQUESTED** [review]
Only one minor thing regarding the status of this extension.
Other than this, LGTM.

Everything else can be handled in another PR.

**Review by geoand — APPROVED** [review]
LGTM

**Review by Postremus — APPROVED** [review]

**Comment by geoand** [comment]
The failures in `quarkus-integration-test-vault-agroal` have nothing to do with this PR

**Comment by Sgitario** [comment]
The CI is green now, can this PR be merged already or do you want me to rebase it to get the latest changes from main?

**Pull request merged**
