### PR TITLE
Take into account that configuration properties can contain a dot in RunTimeConfigurationGenerator

### PR DESCRIPTION
**Pull request by yrodiere**
Otherwise we sometimes get a bug where Quarkus would get to the wrong index
when parsing a configuration property, and would end up mistakenly
reporting missing configuration properties (in a really puzzling error
message...).

You can witness this bug in the test introduced in #26961 in particular. Essentially, any runtime property that contains a dot and has a `Map` parent will trigger the bug; in my case the property was `quarkus.hibernate-search-orm."namedpu".elasticsearch.version-check.enabled` (`version-check.enabled` is a single property, not two, see `io.quarkus.hibernate.search.orm.elasticsearch.runtime.HibernateSearchElasticsearchRuntimeConfigPersistenceUnit.ElasticsearchBackendRuntimeConfig#versionCheck`).

I initially thought "well, maybe I shouldn't be using dots in my property names", but then I checked, and we already do that all over the place (e.g. `metrics.enabled`, `serializer-autodetection.enabled`, `handler.console`, `config.locations`, ...).

I suspect this bug may have caused some configuration being ignored, but I'm not entirely sure.

### CODE REVIEW

**Comment by radcortez** [comment]
It seems that these keys:

```properties
quarkus.log.console.json.additional-field.foo.value=42
quarkus.log.console.json.additional-field.foo.type=int
quarkus.log.console.json.additional-field.bar.value=baz
quarkus.log.console.json.additional-field.bar.type=string
```

Are not being picked up correctly now. They are missing their map key:

```console
  - SRCFG00014: The config property quarkus.log.console.json.additional-field.value is required but it could not be found in any config source
  - SRCFG00014: The config property quarkus.log.console.json.additional-field.type is required but it could not be found in any config source
  - SRCFG00014: The config property quarkus.log.console.json.additional-field.value is required but it could not be found in any config source
  - SRCFG00014: The config property quarkus.log.console.json.additional-field.type is required but it could not be found in any config source
```

**Comment by yrodiere** [comment]
Having a look...

**Comment by yrodiere** [comment]
There was a symmetric operation restoring the initial state of the `NameIterator`, which I hadn't noticed and thus had not updated.

It should be fixed now.

**Comment by yrodiere** [comment]
Note the failure is unrelated to this PR: it also happens (randomly) on the main branch: https://github.com/quarkusio/quarkus/actions/runs/2751756082

**Review by radcortez — APPROVED** [review]

**Pull request merged**
