### PR TITLE
Generate dependency list for Develocity consumption

### LINKED ISSUE #39256: Improve track-config-changes performance by delegating dependencies fingerprinting to the Develocity extension
### Description

This [PR](https://github.com/quarkusio/quarkus/pull/37622) introduced the `target/quarkus-<profile-name>-dependency-checksums.txt` file which contains the list of Quarkus extra dependencies brought during a Quarkus `build`.
This file is used in the context of caching.
For `SNAPSHOT` versions, a fingerprint is computed to be able to track differences among builds.

This fingerprinting would actually be more naturally handled by the [Develocity Maven extension](https://docs.gradle.com/enterprise/maven-extension/).
In details, the Quarkus build caching capability is brought by the [Quarkus Maven build caching extension](https://github.com/gradle/develocity-build-config-samples/tree/main/quarkus-build-caching-extension).

This extension is already ready to integrate the fingerprinting currently handled by the Quarkus Maven plugin since [this PR](https://github.com/gradle/develocity-build-config-samples/pull/1078).

The required changes are:
- list dependencies with absolute path
- create a file named `target/quarkus-<profile-name>-dependencies.txt`

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
We used to build the hashes ourselves but it's best to use the Develocity infrastructure for that.

Fixes #39256

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by aloubyansky** [comment]
I thought you would add an option to record just the paths. I don't mind though. There is a mention in the doc that still needs an adjustment https://quarkus.io/guides/config-reference#dump-quarkus-application-dependencies

**Review by jprinet — APPROVED** [review]
LGTM

**Comment by jprinet** [comment]
This change definitely helps troubleshoot a cache miss due to volatility of the Quarkus runtime dependencies, we now understand which dependencies are changing between builds. 

See the screenshot (with a contrived test):
Screenshot 2024-06-27 at 10 22 36 AM

**Comment by gsmet** [comment]
Hmmm. Why are we using a SNAPSHOT of Spotless?

**Comment by gsmet** [comment]
@aloubyansky if we end up needing that back, I'll restore it and add an option but I think going the Develocity way is better.

I updated the doc.

**Comment by jprinet** [comment]
> Hmmm. Why are we using a SNAPSHOT of Spotless?

As mentioned in my initial comment @gsmet , this is an unreal scenario where I programmatically add a random dependency between two Quarkus builds.
I was working on Spotless recently and collected the absolute path from my command history 😅

**Comment by gsmet** [comment]
Or you also made some changes to Quarkus?

**Comment by jprinet** [comment]
Including a real change in my [automated tests](https://github.com/gradle/develocity-build-config-samples/blob/main/quarkus-build-caching-extension/src/it/invoker.properties) is not easily feasible.
I hooked some add/remove random libs behavior in the extension to verify the fingerprinting mechanims

**Comment by gsmet** [comment]
We need to wait for the update of the Quarkus Develocity extension to 1.1.2 before merging this PR.

**Review by aloubyansky — APPROVED** [review]
Thanks @gsmet

**Comment by gsmet** [comment]
I pushed an additional commit to update the extension.

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
