### PR TITLE
Quarkus Apache XML Security

### PR DESCRIPTION
**Pull request by martinffx**
Add support for Apache XML Security

Based off of the version done for Apache Camel

https://github.com/apache/camel-quarkus/tree/main/extensions/xmlsecurity

### CODE REVIEW

**Comment by martinffx** [comment]
https://github.com/quarkiverse/quarkiverse/issues/47

I opened a issue there a while back and got no response, how do I contribute there?

**Comment by sberyozkin** [comment]
@gastaldi may be it should be independent if non-SOAP use cases are possible, XML Sec itself is not tied to SOAP

**Comment by famod** [comment]
I think it makes more sense as a separate quarkiverse extension that something in `quarkus-cxf`.

In my current project we do use Apache Santuario (jvm only, not native), also in combination with SOAP (sadly), but you could be passing around encrypted xml data without SOAP, so ...

/cc @shumonsharif, as @dufoli wasn't active on GH for while now.

**Comment by gastaldi** [comment]
I created https://github.com/quarkiverse/quarkus-xmlsec and gave @martinffx the appropriate permissions to maintain it. Let me know if that works for you.

**Comment by geoand** [comment]
Closing this

**Comment by gastaldi** [comment]
@shumonsharif shouldn' t `quarkus-cxf` start depending on the `quarkus-xmlsec` extension then? Trying to minimize the effort in maintaining the integration with Santuario

**Comment by shumonsharif** [comment]
Hi @gastaldi I don't believe `quarkus-cxf` should depend on `quarkus-xmlsec` as Santuario appears to provide a smaller subset of what WS-Security / WSS4J covers, and CXF is already well integrated with WSS4J to provide full WS-Security support.  

I'm sure there is a bit of overlap with the standards at play, but as you all have already discussed - WSS4J covers SOAP security, while Santuario covers just XML security, so the two use cases are different.

**Pull request closed without merging**
