### PR TITLE
Update to GraalVM 21.3

### PR DESCRIPTION
**Pull request by zakkak**
Creating as draft PR till Mandrel 21.3 gets released as well.

~Blocked by: https://github.com/quarkusio/quarkus-images/pull/175~

### CODE REVIEW

**Comment by zakkak** [comment]
Looking into the issue... :eyes:

**Review by gastaldi — APPROVED** [review]

**Review by geoand — APPROVED** [review]

**Comment by vsevel** [comment]
@geoand I have tried executing a single vault test (including full vault init) 50 times in a row on my local host. I was able to reproduce one timeout, similar to the issue in this build. I will try making this part more resilient.

**Comment by geoand** [comment]
Great, thanks 👍

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
