### PR TITLE
Replace hot AtomicBoolean usage in Arc with AtomicIntegerFieldUpdater

### PR DESCRIPTION
**Pull request by geoand**
This is done because InstanceHandleImpl is really hot, so avoiding
the additional allocations is beneficial.

See:

Screenshot from 2021-10-15 17-06-26

Similar optimizations have been performed in Mutiny
and most recently Vert.x Web.

Unfortunately there is no AtomicBooleanFieldUpdater, so this is slightly dirtier than necessary

### CODE REVIEW

**Review by mkouba — COMMENTED** [review]
So if I understand it correctly this will save one allocation of `AtomicBoolean` per `InstanceHandle`. TBH I'm not a big fan of similar optimizations. It's hard to read and the gain is disputable. Do you have some numbers of how big the impact of this change is?

Also the `InstanceHandle` implementation was refactored in another PR: https://github.com/quarkusio/quarkus/pull/20796

**Comment by geoand** [comment]
> Also the `InstanceHandle` implementation was refactored in another PR: #20796

We can do both 😉

**Comment by geoand** [comment]
I don't think we can do that, it's a pretty fundamental way of accessing the Vertx request from CDI

**Comment by mkouba** [comment]
> I don't think we can do that, it's a pretty fundamental way of accessing the Vertx request from CDI

The question is how often is it used? Also note that we have currently have 3 beans: `CurrentVertxRequest` (aka the request holder), the `CurrentVertxRequest.getCurrent()` and the `CurrentRequestProducer.getCurrentRequest()` producers. And `CurrentVertxRequest` is always created (and one of the setter called), no matter whether the `RoutingContext` or `HttpServerRequest` is injected somewhere.

**Comment by geoand** [comment]
I think this change is pretty small and that it would make sense to include it before exploring more radical solutions. 

But I'm biased :)

**Review by Sanne — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Review by mkouba — APPROVED** [review]

**Pull request merged**
