### PR TITLE
Support mocking PanacheEntityBase.persist static methods

### LINKED ISSUE #16182: Mocking Panache active record pattern not working
## Describe the bug
I've built a JAX-RS endpoint & a test using Panache & the active record pattern. I'm trying to mock Panache so I can test the resource class in isolation. It doesn't seem to be working. I've successfully been able to do this using the repository pattern and am trying to achieve the same thing with the active record pattern. I've attached a reproducing project, but here are the details.

I also thought that `void` methods on mocks do nothing by default (https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#doNothing--), so I tried eliminating the `PanacheMock.doNothing().when(Fruit.class).persist();` but that ended up with the same result.

Changing to use RESTEasy classic results in the same error.

I've also posted this on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Need.20help.20mocking.20with.20Panache.20using.20active.20record.20pattern

JAX-RS class:

```java
@Path("/fruits")
public class FruitResource {
	@POST
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	@Blocking
	@Transactional
	public Fruit addFruit(@Valid Fruit fruit) {
		fruit.persist();
		return fruit;
	}
}
```

Test class

```java
@QuarkusTest
public class FruitResourceTests {
	@Test
	public void addFruit() {
		PanacheMock.mock(Fruit.class);
		PanacheMock.doNothing()
			.when(Fruit.class).persist();

		given()
			.when()
				.contentType(ContentType.JSON)
				.body("{\"id\":1,\"name\":\"Grapefruit\",\"description\":\"Summer fruit\"}")
				.post("/fruits")
			.then()
				.statusCode(200)
				.contentType(ContentType.JSON)
				.body(
					"id", is(1),
					"name", is("Grapefruit"),
					"description", is("Summer fruit")
				);

		PanacheMock.verify(Fruit.class).persist();
		PanacheMock.verifyNoMoreInteractions(Fruit.class);
	}
}
```

When running `./mvnw verify` on the attached reproducer I'm getting

```shell
2021-04-01 09:04:05,510 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-1) Request failed: javax.persistence.PersistenceException: org.hibernate.PersistentObjectException: detached entity passed to persist: org.acme.domain.Fruit
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:726)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:706)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:139)
        at io.quarkus.hibernate.orm.runtime.session.ForwardingSession.persist(ForwardingSession.java:53)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:99)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:94)
        at io.quarkus.hibernate.orm.panache.PanacheEntityBase.persist(PanacheEntityBase.java:56)
        at org.acme.rest.FruitResource.addFruit(FruitResource.java:23)
        at org.acme.rest.FruitResource_Subclass.addFruit$$superaccessor1(FruitResource_Subclass.zig:265)
        at org.acme.rest.FruitResource_Subclass$$function$$1.apply(FruitResource_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:68)
        at io.quarkus.hibernate.validator.runtime.jaxrs.QuarkusRestEndPointValidationInterceptor.validateMethodInvocation(QuarkusRestEndPointValidationInterceptor.java:19)
        at io.quarkus.hibernate.validator.runtime.jaxrs.QuarkusRestEndPointValidationInterceptor_Bean.intercept(QuarkusRestEndPointValidationInterceptor_Bean.zig:341)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.rest.FruitResource_Subclass.addFruit(FruitResource_Subclass.zig:222)
        at org.acme.rest.FruitResource$quarkusrestinvoker$addFruit_e4ceee061fa3e84c0954c49287079e5dcbfcc5b0.invoke(FruitResource$quarkusrestinvoker$addFruit_e4ceee061fa3e84c0954c49287079e5dcbfcc5b0.zig:39)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:122)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: org.acme.domain.Fruit
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:120)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:93)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:720)
        ... 35 more

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.704 s <<< FAILURE! - in org.acme.rest.FruitResourceTests

```

I also tried `PanacheMock.doNothing().when(Fruit.class).persist(Mockito.any(Fruit.class));` while changing the JAX-RS method to do `Fruit.persist(fruit);` instead of `fruit.persist();`, but that resulted in a much different error:

```shell
[ERROR] org.acme.rest.FruitResourceTests.addFruit  Time elapsed: 0.28 s  <<< ERROR!
java.lang.NullPointerException
        at org.acme.rest.FruitResourceTests.addFruit(FruitResourceTests.java:83)

[ERROR] org.acme.rest.FruitResourceTests.getAll  Time elapsed: 0.009 s  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException:

Unfinished stubbing detected here:
-> at io.quarkus.panache.mock.PanacheMock.doNothing(PanacheMock.java:120)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

        at org.acme.rest.FruitResourceTests.getAll(FruitResourceTests.java:23)

2021-03-30 16:15:57,464 INFO  [io.quarkus] (main) Quarkus stopped in 0.631s
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   FruitResourceTests.addFruit:83 » NullPointer
[ERROR]   FruitResourceTests.getAll:23 » UnfinishedStubbing
Unfinished stubbing detecte...
```

## To Reproduce
Reproducer project attached

1. Run `./mvnw verify`

### Configuration
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fruits
quarkus.datasource.password=fruits
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fruits
quarkus.datasource.devservices.image-name=quay.io/edeandrea/postgres-13-fruits:latest

quarkus.hibernate-orm.database.generation=validate

# Set testcontainers info for testing
%test.quarkus.datasource.jdbc.url=jdbc:tc:postgresql:13:///test?TC_INITSCRIPT=db/schema.sql
%test.quarkus.datasource.jdbc.driver=org.testcontainers.jdbc.ContainerDatabaseDriver
```

### Output of `uname -a` or `ver`
`Darwin edeandre-mac 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

### Output of `java -version`
```shell
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### Quarkus version or git rev
`1.13.0.Final` (I also tried with 1.12.x and same thing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```shell
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/edeandre/.sdkman/candidates/java/11.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/6243706/code-with-quarkus.zip)

### PR DESCRIPTION
**Pull request by FroMage**
Fixes #16182

@evanchooly @loicmathieu do you know if I need to do anything for Mongo and Kotlin too? Do they support mocking static methods too?

### CODE REVIEW

**Comment by loicmathieu** [comment]
If I understand it correctly, you generate a bridge method for the method that don't need one (because they are directly implemented inside the base class) only to be able to mock them from Panache Mock ?

I don't very like it but I don't see any other way to do this.

If so, yes, this needs to be done for Mongo and the Kotlin variant that should suffer for the same issue.

**Comment by FroMage** [comment]
> I don't very like it but I don't see any other way to do this.

Yeah, me neither, but otherwise if I implement it directly in the Java code I need to depend on the mocking extension, which isn't better.

**Comment by FroMage** [comment]
I've added support for Mongodb. I don't thing the Kotlin versions have static methods, am I wrong @evanchooly ?

**Comment by loicmathieu** [comment]
Kotlin static methods are in the companion object.

Instance methods are in the base object, like https://github.com/quarkusio/quarkus/blob/main/extensions/panache/mongodb-panache-kotlin/runtime/src/main/kotlin/io/quarkus/mongodb/panache/kotlin/PanacheMongoEntityBase.kt, I think they too need the new annotation to be mockable.

**Comment by FroMage** [comment]
Well this is not for instance methods, but for the static methods, so it would be in https://github.com/quarkusio/quarkus/blob/main/extensions/panache/mongodb-panache-kotlin/runtime/src/main/kotlin/io/quarkus/mongodb/panache/kotlin/PanacheMongoCompanion.kt

@evanchooly do you think you could do this part please?

**Comment by evanchooly** [comment]
I can.  I'm trying to wrap up the native coroutine support and can take a look when that's done.

**Comment by edeandrea** [comment]
Does this PR cover panache reactive as well? The same issue described on #16182 exists in Panache Reactive as well.

**Comment by FroMage** [comment]
Added support for HR/Panache (thanks for spotting this, I had forgotten about it…) and rebased on `main`. @evanchooly if you don't have time for this quickly, we can open an issue for the kotlin bits and merge this, as I've been made aware it's become urgent.

**Comment by FroMage** [comment]
OK, moving out of draft to get merged quickly and hopefully backported. Kotlin will wait, I'll file another issue.

@loicmathieu would you mind reviewing please?

**Review by loicmathieu — APPROVED** [review]
LGTM

Thanks for updating all possible combination of hibernate/mongo/imperative/reactive ;)
Kotlin will be handled in a separate PR so it's OK to merge this one as soon as CI is green.

**Comment by FroMage** [comment]
> 2021-04-12T15:48:55.9744656Z Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Authorization failed for https://dl.bintray.com/davided/artifacts/org/hibernate/reactive/hibernate-reactive-core/1.0.0.CR1.Vertx4/hibernate-reactive-core-1.0.0.CR1.Vertx4.pom 403 Forbidden

Now.

**Comment by gsmet** [comment]
Rebased to get the latest CI fixes.

**Comment by FroMage** [comment]
Thanks!

**Comment by gsmet** [comment]
I tried to backport it (and also backported a MongoReplicaSetTestResource to make it work) but in the end, I have some instabilities on Windows so removed it from the backports for now.

**Comment by edeandrea** [comment]
@gsmet what does that mean from a Quarkus versioning perspective? Does that mean it will not make a Quarkus 1.13.x release?

**Comment by edeandrea** [comment]
Any update on my question re: 1.13.x @gsmet ?

I'm a red hatter and am writing a book. The text will be frozen before quarkus 2.0 comes out. If this won't make it into a 1.13.x release then I will not be able to discuss the panache active record pattern in the book. I cant discuss and show code examples that don't work. I'm working with Charles Mouillard on this project.

Please advise if we can get this into a 1.13.x release.

**Comment by FroMage** [comment]
@gsmet I can help with the backport if you want.

**Comment by edeandrea** [comment]
@FroMage @gsmet any idea on getting this into a 1.13.x release? My book's chapter text is going to freeze shortly and without this in there I need to remove discussion of the active record pattern from it. I can't include text and code samples that do not work.

@cmoulliard any chance you can weigh in here?

**Comment by geoand** [comment]
I'd say let's backport this. @FroMage care opening a PR against the `1.13` branch?

**Comment by FroMage** [comment]
OK.

**Comment by FroMage** [comment]
It's at https://github.com/quarkusio/quarkus/pull/16866

**Comment by edeandrea** [comment]
Hey @FroMage / @geoand should this fix be available in the latest Quarkus 2.0.0.Alpha3 release? If so, it does not work.

### FruitResource.java
```java
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Transactional
public Fruit addFruit(@Valid Fruit fruit) {
	Fruit.persist(fruit);
	return fruit;
}
```

## FruitResourceTests.java
```java
@Test
public void addFruit() {
	PanacheMock.mock(Fruit.class);
	PanacheMock.doNothing()
		.when(Fruit.class).persist(Mockito.any(Fruit.class));

	given()
		.when()
			.contentType(ContentType.JSON)
			.body("{\"id\":1,\"name\":\"Grapefruit\",\"description\":\"Summer fruit\"}")
			.post("/fruits")
		.then()
			.statusCode(200)
			.contentType(ContentType.JSON)
			.body(
				"id", is(1),
				"name", is("Grapefruit"),
				"description", is("Summer fruit")
			);

	PanacheMock.verify(Fruit.class).persist(Mockito.any(Fruit.class));
	PanacheMock.verifyNoMoreInteractions(Fruit.class);
}
```

### Output of `./mvnw clean verify`
```shell
2021-05-21 13:36:02,718 INFO  [io.quarkus] (main) Quarkus 2.0.0.Alpha3 on JVM started in 15.015s. Listening on: http://localhost:8081
2021-05-21 13:36:02,719 INFO  [io.quarkus] (main) Profile test activated. 
2021-05-21 13:36:02,719 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-postgresql, narayana-jta, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.244 s - in org.acme.domain.FruitTests
[INFO] Running org.acme.rest.FruitResourceTests
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.883 s <<< FAILURE! - in org.acme.rest.FruitResourceTests
[ERROR] org.acme.rest.FruitResourceTests.addFruit  Time elapsed: 0.207 s  <<< ERROR!
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 

Invalid use of argument matchers!
2 matchers expected, 1 recorded:
-> at org.acme.rest.FruitResourceTests.addFruit(FruitResourceTests.java:83)

This exception may occur if matchers are combined with raw values:
    //incorrect:
    someMethod(anyObject(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
    //correct:
    someMethod(anyObject(), eq("String by matcher"));

For more info see javadoc for Matchers class.

	at org.acme.rest.FruitResourceTests.addFruit(FruitResourceTests.java:83)

2021-05-21 13:36:06,523 INFO  [io.quarkus] (main) Quarkus stopped in 0.533s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FruitResourceTests.addFruit:83 » InvalidUseOfMatchers 
Invalid use of argument...
[INFO] 
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0
```

I also tried changing

```java
PanacheMock.doNothing()
		.when(Fruit.class).persist(Mockito.any(Fruit.class));
```

to

```java
PanacheMock.doNothing()
		.when(Fruit.class).persist(Mockito.any(Fruit.class), Mockito.any());
```

**Comment by edeandrea** [comment]
Actually nevermind - false alarm. I had to change my verification as well.

**Comment by nikolasFreitas** [comment]
> 
> 
> Actually nevermind - false alarm. I had to change my verification as well.

Which technique did you use to work the `panacheEntity` mock?

**Comment by edeandrea** [comment]
@nikolasFreitas This is what I did and it works. Note I use the `PanacheEntity.persist(entity)` static method, not the `persist()` instance method.

## FruitResource.java
```java
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Transactional
public Fruit addFruit(@Valid Fruit fruit) {
	Fruit.persist(fruit);
	return fruit;
}
```

## FruitResourceTests.java
```java
@Test
public void addFruit() {
	PanacheMock.mock(Fruit.class);
	PanacheMock.doNothing()
		.when(Fruit.class).persist(Mockito.any(Fruit.class), Mockito.any());

	given()
		.when()
			.contentType(ContentType.JSON)
			.body("{\"id\":1,\"name\":\"Grapefruit\",\"description\":\"Summer fruit\"}")
			.post("/fruits")
		.then()
			.statusCode(200)
			.contentType(ContentType.JSON)
			.body(
				"id", is(1),
				"name", is("Grapefruit"),
				"description", is("Summer fruit")
			);

	PanacheMock.verify(Fruit.class).persist(Mockito.any(Fruit.class), Mockito.any());
	PanacheMock.verifyNoMoreInteractions(Fruit.class);
}
```

**Comment by abritov** [comment]
Is this still actual? Still can't test instance methods on 2.14.1.Final

**Comment by edeandrea** [comment]
As far as I know you can't mock instance methods, unless your application has complete control over when instances are created. For example, if a jaxrs endpoint creates the instance by unmarshaling from json then you have no control over an instance's creation.

That's why in my examples above I use the static methods instead of the instance methods.

**Comment by geoand** [comment]
`quarkus-panache-mock` does allow for mocking the static methods of a `PanacheEntity`. See [this](https://quarkus.io/guides/hibernate-orm-panache#using-the-active-record-pattern) part of the documentation.

**Comment by geoand** [comment]
Using Hibernate Reactive Panache inside tests won't work really well. Can you update your code and try using the API shown [here](https://github.com/quarkusio/quarkus-super-heroes/blob/85385441cae896a9bc7527fb79351f5c9c9cc2fb/rest-heroes/src/test/java/io/quarkus/sample/superheroes/hero/repository/HeroRepositoryTests.java#L30)?

**Comment by nikolasFreitas** [comment]
Thanks for sharing @edeandrea. Now in the [documentation](https://quarkus.io/guides/hibernate-orm-panache#mocking-entitymanager-session-and-entity-instance-methods) is suggested to mock the EntityManager, preventing every database operation.

If you're using the mockito annotations you can do like I did [https://github.com/nikolasFreitas/activity/blob/dev/src/test/java/dev/orion/workflowExecutor/SendEmailStepStepExecutorTest.java#L40](https://github.com/nikolasFreitas/activity/blob/dev/src/test/java/dev/orion/workflowExecutor/SendEmailStepStepExecutorTest.java#L40)

**Pull request merged**
