### PR TITLE
Document bug in Reactive Extensions of the Oracle JDBC driver

### PR DESCRIPTION
**Pull request by tsegismont**
See https://github.com/quarkusio/quarkus/issues/35477

### CODE REVIEW

**Review by Sanne — APPROVED** [review]
Looks great! Many thanks and sorry for the delay - unfortunately there's a conflict to resolve now.

**Comment by tsegismont** [comment]
@Sanne PR rebased

**Review by Sanne — APPROVED** [review]

**Comment by tsegismont** [comment]
Can someone granted to merge PRs please merge this one?

**Review by gsmet — APPROVED** [review]

**Comment by Sanne** [comment]
This is superseded by the actual fix now: #36453

**Pull request merged**
