### PR TITLE
Remove support for list of objects in YAML configuration

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
@radcortez LGTM, thanks, please update the migration guide just to let the users know that this feature is removed due to a better and also safer alternative avalable from `smallrye-config`

**Comment by radcortez** [comment]
> @radcortez LGTM, thanks, please update the migration guide just to let the users know that this feature is removed due to a better and also safer alternative avalable from `smallrye-config`

Sure.

**Comment by machi1990** [comment]
Maybe this can be labelled as a breaking change?

**Comment by radcortez** [comment]
> Maybe this can be labelled as a breaking change?

Done!

**Comment by sberyozkin** [comment]
Might make sense to update the migration guide and/or the docs to show how the same can be achieved using the new capability

**Comment by radcortez** [comment]
> Might make sense to update the migration guide and/or the docs to show how the same can be achieved using the new capability

I added it to the migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0

We also rewrote the config documentation and the new APIs are already included.

**Pull request merged**
