### PR TITLE
Upgrade to Jandex 2.3.0

### LINKED ISSUE #17491: Quarkus project using hibernate validator on classes from separate jars does not compile with 1.13.5.Final
## Describe the bug
(Describe the problem clearly and concisely.)
I have a couple of projects that use DTO classes from another jar that are annotated with hibernate validator classes. This includes validations on type declarations for container classes. When I moved from 1.13.4.Final to 1.13.5.final, my project failed to compile.

### Expected behavior
(Describe the expected behavior clearly and concisely.)
I expected everything to compile as with past Quarkus version upgrades.

### Actual behavior
(Describe the actual behavior clearly and concisely.)
The compile for both project failed with stack trace:
F
[demo1.zip](https://github.com/quarkusio/quarkus/files/6550261/demo1.zip)
ailed to execute goal io.quarkus:quarkus-maven-plugin:1.13.5.Final:build (default) on project scoreapi: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] [error]: Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.ClassCastException: class org.jboss.jandex.ClassInfo cannot be cast to class org.jboss.jandex.MethodInfo (org.jboss.jandex.ClassInfo and org.jboss.jandex.MethodInfo are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @5411fed2)
[ERROR] at org.jboss.jandex.MethodParameterTypeTarget.enclosingTarget(MethodParameterTypeTarget.java:56)
[ERROR] at org.jboss.jandex.MethodParameterTypeTarget.enclosingTarget(MethodParameterTypeTarget.java:39)
[ERROR] at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.build(HibernateValidatorProcessor.java:281)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] at org.jboss.threads.JBossThread.run(JBossThread.java:501)

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. reproducer attached.
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin BillMacBookPro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
### GraalVM version (if different from Java)
CE 21.1.0
### Quarkus version or git rev
1.13.4.Final and 1.13.5.Final(attempted)
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.11, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
## Additional context
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #17491 by upgrading to Jandex 2.3.0, which includes https://github.com/wildfly/jandex/pull/121 

Draft because we're waiting for:

* ~The Gradle plugin: https://github.com/kordamp/jandex-gradle-plugin/pull/13 + wait for release~ => Done
* ~The Maven plugin: https://github.com/wildfly/jandex-maven-plugin/pull/28 + wait for release~ => Done

### CODE REVIEW

**Comment by glefloch** [comment]
The gradle plugin has been released in 0.11.0.

**Comment by Sanne** [comment]
@yrodiere should this be promoted from draft ?

**Comment by yrodiere** [comment]
Not until the maven plugin get released, which should hopefully happen soon.

Le mar. 1 juin 2021 à 19:41, Sanne Grinovero ***@***.***> a
écrit :

**Comment by yrodiere** [comment]
`jandex-maven-plugin` version 1.1.0 has been released last night (https://repo1.maven.org/maven2/org/jboss/jandex/jandex-maven-plugin/1.1.0/), so this PR is ready for review!

I also just pushed an additional commit to disable the workaround on Hibernate Validator.

I tested locally with the reproducer that Xavier Sanchez Taixe provided [on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Bean.20validation.20bug) (thanks for that!), upgrading to this patched version of Quarkus and `jandex-maven-plugin` 1.1.0: it works!

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
It seems like GraphQL doesn't like it. @phillip-kruger can you please take a look?

**Comment by yrodiere** [comment]
> It seems like GraphQL doesn't like it. @phillip-kruger can you please take a look?

Note that the main change in this new version of Jandex is that type-use annotations are now returned by `MethodInfo#annotation`/`FieldInfo#annotation` (in compliance with the javadoc), whereas previously they were omitted. I can see how this could make some annotation processors fail...

**Comment by phillip-kruger** [comment]
I'll have a look. Thanks :)

**Comment by gsmet** [comment]
Quite an adventure but here we are. Thanks everyone!

**Comment by geoand** [comment]
Great job folks 👌

**Comment by Sanne** [comment]
Nice!

**Comment by xtaixe** [comment]
👏🏻

**Pull request merged**
