### PR TITLE
Introduce build item that gives access to generated k8s resources

### PR DESCRIPTION
**Pull request by geoand**
This is useful for extensions that depend on the k8s extension
in order to have a predicable way to use the output of the
kubernetes extension

### CODE REVIEW

**Comment by geoand** [comment]
cc @metacosm

**Comment by gastaldi** [comment]
Isn't `GeneratedFileSystemResourceBuildItem` already doing this?

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by iocanel** [comment]
> GeneratedFileSystemResourceBuildItem

I think not, cause it's more generic than we need.

**Comment by geoand** [comment]
@iocanel is exactly right.

The existing build item contains all generated resources.

**Review by metacosm — APPROVED** [review]
LGTM

**Comment by metacosm** [comment]
Any chance that could be backported to 2.2?

**Comment by geoand** [comment]
You should know by know, look at the labels 😉

**Comment by metacosm** [comment]
Ah yes, that wasn't obvious on the GitHub app, sorry.

**Comment by geoand** [comment]
NP!

**Comment by paulrobinson** [comment]
Sorry for the noise @gsmet. I added the backport label by accident.

**Pull request merged**
