### PR TITLE
Revert "Allow multiple source directories for Gradle."

### PR DESCRIPTION
**Pull request by geoand**
Reverts quarkusio/quarkus#5540

Based on [this](https://github.com/quarkusio/quarkus/pull/5540#issuecomment-557878416) comment.

### CODE REVIEW

**Comment by geoand** [comment]
@gsmet @aloubyansky @maxandersen  could one you approve so we can get this revert in quickly?

Thanks!

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I approved it. Maybe we should try to fix it though as it's an important one.

**Comment by maxandersen** [comment]
I really would like us to stop try keep merge all these "random" small fixes into the gradle support it needs to be redone anyway. 

lets rather get them linked to https://github.com/quarkusio/quarkus/issues/5101 and we can get it reset and clean up from there.

**Comment by maxandersen** [comment]
and to be clear +1 on the revert commits.

**Comment by geoand** [comment]
I agree that the Gradle stuff needs to be collected and dealt with strategically.

But we also want to leverage community knowledge on Gradle I think

**Comment by geoand** [comment]
I added the original issue to the general Gradle tracking issue

**Pull request merged**
