### PR TITLE
Bump SmallRye Reactive Messaging to 3.19.1

### PR DESCRIPTION
**Pull request by ozangunalp**
- Update Kafka documentation
- Update HR RM test with activate request context
- Added HR ORM RM IT

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
I think it's a flaky test. I got it failing a few times. We should disable it and investigate.

**Comment by ozangunalp** [comment]
That test is still green for me. Maybe it is a windows issue?

**Comment by ozangunalp** [comment]
@cescoffier Actually maybe we need to mark the outgoing channel durable, instead of the incoming one.

**Comment by cescoffier** [comment]
Can you squash @ozangunalp ? It will make the backport easier.

**Review by cescoffier — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Let's keep the commits as is. They are semantic, it's better.

**Pull request merged**
