### PR TITLE
In CI swap Java 16 with 17 and in EA job swap 17-ea with 18-ea

### LINKED ISSUE #20215: Java 17: In CI swap 16 with 17 and in EA job swap 17-ea with 18-ea
### Description

Java 17 reached GA, so regular CI should make the move and EA job accordingly.

We need to wait for the Eclipse Temurin binaries:
- https://github.com/adoptium/adoptium/issues/74
- https://github.com/adoptium/adoptium/issues/73

Ironically, the EA job has more >11 coverage than regular CI so it might be worthwhile to have a nightly "EA" run, but with 17 (additionally to the normal EA run with 18-ea).

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by famod**
Resolves #20215

Unfortunately, I don't have time ATM for:
> Ironically, the EA job has more >11 coverage than regular CI so it might be worthwhile to have a nightly "EA" run, but with 17 (additionally to the normal EA run with 18-ea).

I'll put that higher on my list (and create yet another housekeeping issue for that).

### CODE REVIEW

**Comment by famod** [comment]
Hm, bummer - there is no Temurin 18-ea. I'll have a look which other candidates there are.

**Comment by geoand** [comment]
I restarted CI because the Java 17 job timed out

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by famod** [comment]
> Hm, bummer - there is no Temurin 18-ea: https://github.com/famod/quarkus/runs/3679956449?check_suite_focus=true
> I'll have a look which other candidates there are.

zulu works, so we'll have to live with that for now. I'll wait for the current run to finish and if that is more or less ok, I'll push the zulu change for the EA job (and we then don't need to wait for yet another CI run).

**Comment by famod** [comment]
I merely switched EA job to zulu 18-ea for now, so no use waiting for CI again.

**Pull request merged**
