### PR TITLE
Rename RESTEasy Classic client extensions to resteasy-client

### PR DESCRIPTION
**Pull request by gsmet**
This is part of a more massive operation that will be followed up in 3.9.

Starting CI with the code changes, will take care of the documentation now.

/cc @maxandersen @geoand @cescoffier 

- Relates to #38188

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
🎯

**Comment by gsmet** [comment]
CI looks happyish on my side, let's try the main CI.

@geoand @cescoffier @maxandersen fancy a sanity check? Once this is in, I will merge the quickstart PR I prepared.

**Review by geoand — APPROVED** [review]
LGTM!

**Comment by maxandersen** [comment]
related to #38188

**Pull request merged**
