### PR TITLE
Fix the OIDC token verification failure with the inlined cert chain

### LINKED ISSUE #38989: cert chain public key resolver thumbprints
### Describe the bug

I have a truststore configured to validate the oidc token, a self contained token with full chain certs, but fails to validate the thumbprints [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CertChainPublicKeyResolver.java#L40). However, I can debug and verified that one if the thumbprints is valid, happens not to be the **first one** on index 0. 

So, I'm thinking if instead of picking one (index 0), we should instead call calculate all the thumbprints of the chain and check if any of the set are part of the trust store certificate thumprints.

### Expected behavior

Except one the thumbprints to be valid and proceed.

### Actual behavior

Throws an exception `UnresolvableKeyException("Certificate chain thumprint is invalid")`

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #38989.

As explained in #38989, when the token with the inlined certificate chain arrives, in order to use the leaf certificate of this chain to verify the token signature, Quarkus OIDC wants to establish trust in the leaf certificate, in addition to using the Vert.x Cert chain verification to assert the general validity of the chain (which is also tested). Quarkus OIDC does it by checking a leaf certificate thumbprint against one of the certificates in the truststore.

However, in prod, truststores may have the root certificates only. The intermediate and leaf certificates will be in the token chain. 

So, this PR makes it possible to support such truststores while still insisting that the leaf certificate is known to Quarkus OIDC - this is because it is this certificate that will be used to check the token signature, so we'd like to avoid the situation where someone pays to a well known authority to sign their certificate and then sends a signed token to Quarkus OIDC which will be able to verify the chain itself but won't have proof that the token is signed by the expected leaf certificate.

Therefore, if the truststore contains a root certificate only, users must specify a leaf certificate common name. If it is set then the common name check is done, plus the thumbrint of the root certificate will be checked as well as the Vert.x chain validation.

Test has been added.
 
CC @calvernaz - FYI

### CODE REVIEW

**Comment by sberyozkin** [comment]
@pedroigor @calvernaz, FYI, I have tightened the original solution as well, now the root cert must always be in the truststore, initially, the thumbprint of the leaf certificate only was checked which is not enough to establish the full trust.
Going forward we can also optionally enforce the presence of all the intermediate certs for very strict trust decisions (in case where it is possible in prod), but for now the root certificate requirement plus the rest of the verification should be sufficient.

**Comment by sberyozkin** [comment]
Oh, sorry, other tests now need tweaking

**Comment by sberyozkin** [comment]
A few tests were pointing to a leaf certificate for the thumbprint calculation, so I fixed that

**Comment by sberyozkin** [comment]
Just tuned the docs a bit to make it clearer

**Review by pedroigor — APPROVED** [review]
LGTM. It should help to avoid having lot of certificates that potentially expire for every single client..

**Pull request merged**
