### PR TITLE
Updated docs for Panache marker removal

### PR DESCRIPTION
**Pull request by FroMage**
Docs for https://github.com/quarkusio/quarkus/pull/38242

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by FroMage** [comment]
Migration part is here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#ormhrmongo-panache-annotation-processor-removed

@geoand or @yrodiere do you happen to know where I can add a quarkus-update rule to make sure any usage of the annotation processor gets removed on update?

**Comment by geoand** [comment]
I do not

**Comment by yrodiere** [comment]
> Migration part is here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#ormhrmongo-panache-annotation-processor-removed
> 
> @geoand or @yrodiere do you happen to know where I can add a quarkus-update rule to make sure any usage of the annotation processor gets removed on update?

Not exactly, but you can probably take inspiration from this: https://github.com/quarkusio/quarkus-updates/pull/106

**Comment by FroMage** [comment]
Thanks @yrodiere this is exactly what I was looking for :)

**Pull request merged**
