### PR TITLE
Disable INFO logging during the analysis phase in native build

### LINKED ISSUE #23748: Remove JBoss Threads version printing when building native
JBoss Thread printing version information when building native images getting in the way of the new GraalVM 22.x output:

```
[1/7] Initializing...                                                                                    (2.3s @ 0.14GB)
 Version info: 'GraalVM 22.1-dev Java 17 CE'
 C compiler: gcc (redhat, x86_64, 11.2.1)
 Garbage collector: Serial GC
 3 user-provided feature(s)
  - io.quarkus.caffeine.runtime.graal.CacheConstructorsAutofeature
  - io.quarkus.runner.AutoFeature
  - io.quarkus.runtime.graal.ResourcesFeature
[2/7] Performing analysis...  [*10:01:48,494 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
*******]                                                                 (9.1s @ 1.70GB)
  14,475 (95.76%) of 15,116 classes reachable
```

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #23748

### CODE REVIEW

**Comment by gsmet** [comment]
Making it draft so that we can discuss this without pushing to CI.

**Comment by gastaldi** [comment]
Sample output:

```bash
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Users/ggastald/.sdkman/candidates/java/22.0.0.2.r17-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=BR -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-registry-app-999-SNAPSHOT-runner -jar quarkus-registry-app-999-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-registry-app-999-SNAPSHOT-runner'...
========================================================================================================================
[1/7] Initializing...                                                                                   (16.4s @ 0.31GB)
 Version info: 'GraalVM 22.0.0.2 Java 17 CE'
 10 user-provided feature(s)
  - com.oracle.svm.thirdparty.gson.GsonFeature
  - io.quarkus.caffeine.runtime.graal.CacheConstructorsAutofeature
  - io.quarkus.hibernate.orm.runtime.graal.DisableLoggingAutoFeature
  - io.quarkus.hibernate.validator.runtime.DisableLoggingAutoFeature
  - io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature
  - io.quarkus.runner.AutoFeature
  - io.quarkus.runtime.graal.DisableLoggingAutoFeature
  - io.quarkus.runtime.graal.ResourcesFeature
  - org.hibernate.graalvm.internal.GraalVMStaticAutofeature
  - org.hibernate.graalvm.internal.QueryParsingSupport
[2/7] Performing analysis...  [**********]                                                              (66.0s @ 4.27GB)
  20,279 (96.53%) of 21,009 classes reachable
  29,770 (67.26%) of 44,263 fields reachable
 101,092 (81.70%) of 123,732 methods reachable
     861 classes,   685 fields, and 3,956 methods registered for reflection
      64 classes,    76 fields, and    55 methods registered for JNI access
[3/7] Building universe...                                                                               (4.0s @ 5.02GB)
[4/7] Parsing methods...      [***]                                                                      (9.7s @ 4.06GB)
[5/7] Inlining methods...     [***********]                                                              (9.8s @ 3.67GB)
[6/7] Compiling methods...    [******]                                                                  (41.3s @ 2.68GB)
[7/7] Creating image...                                                                                  (8.6s @ 5.17GB)
  37.99MB (40.17%) for code area:   68,305 compilation units
  48.82MB (51.63%) for image heap:  13,973 classes and 657,513 objects
   7.75MB ( 8.20%) for other data
  94.56MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.73MB sun.security.ssl                                    15.91MB byte[] for general heap data
   1.34MB com.oracle.svm.core.reflect                          4.86MB java.lang.Class
   1.15MB java.util                                            4.31MB java.lang.String
 730.27KB com.sun.crypto.provider                              3.68MB byte[] for java.lang.String
 565.00KB org.hibernate.hql.internal.antlr                     2.16MB java.util.LinkedHashMap
 540.55KB io.quarkus.runtime.generated                         1.39MB java.lang.reflect.Method
 504.10KB java.util.concurrent                                 1.22MB s.r.a.AnnotatedTypeFactory$AnnotatedTypeBaseImpl
 475.35KB sun.security.x509                                  802.99KB java.lang.String[]
 472.07KB org.postgresql.jdbc                                791.30KB java.util.HashMap$Node
 428.78KB java.lang                                          766.72KB com.oracle.svm.core.util.LazyFinalReference
      ... 1012 additional packages                                ... 4901 additional object types
                                           (use GraalVM Dashboard to see all)
------------------------------------------------------------------------------------------------------------------------
                        7.7s (4.7% of total time) in 52 GCs | Peak RSS: 8.54GB | CPU load: 3.93
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /Users/ggastald/workspace/registry.quarkus.io/target/quarkus-registry-app-999-SNAPSHOT-native-image-source-jar/quarkus-registry-app-999-SNAPSHOT-runner (executable)
 /Users/ggastald/workspace/registry.quarkus.io/target/quarkus-registry-app-999-SNAPSHOT-native-image-source-jar/quarkus-registry-app-999-SNAPSHOT-runner.build_artifacts.txt
========================================================================================================================
Finished generating 'quarkus-registry-app-999-SNAPSHOT-runner' in 2m 42s.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 174339ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:16 min
[INFO] Finished at: 2022-03-08T21:21:37-03:00
[INFO] ------------------------------------------------------------------------
```

**Comment by geoand** [comment]
Seems reasonable to me

**Review by galderz — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Clever trick.

I added a commit for Hibernate Search too.

**Comment by geoand** [comment]
This make me think of what else we might be able to do using this trick :)

**Comment by gastaldi** [comment]
> This make me think of what else we might be able to do using this trick :)

The sky is the limit 😉

**Comment by gastaldi** [comment]
I squashed all commits, let me know when this is ready for review

**Review by dmlloyd — APPROVED** [review]
Nice idea.

**Comment by gsmet** [comment]
Making it `WARN` would work and is probably better. I would refrain from disabling everything for the time being. We can revisit later if we end up having a ton of other things that require this treatment.

**Pull request merged**
