### PR TITLE
Add support for generating an example configuration file

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Example config file is at https://gist.github.com/stuartwdouglas/8e85bb438d5d9d4cd90027ce2955fe26

For details on how it works see the docs changes

@emmanuelbernard @FroMage if this looks ok to you guys I will add gradle support and some tests and change it from a draft PR.

### CODE REVIEW

**Comment by cescoffier** [comment]
Nice feature, however, don't you fear listing hundreds of properties and most of them are quite advanced? Should we filter out advanced properties (or generate them using a flag)?

**Comment by stuartwdouglas** [comment]
I was planning on adding an 'advanced' flag to the annotation. You would then be able to specify if you want everything or just the non-advanced stuff

**Comment by FroMage** [comment]
OK this is super cool :)

We will have to do something about `@see UnremovableBeanBuildItem` once we publish javadoc online (do we already?), but it can wait.

**Comment by stuartwdouglas** [comment]
I missed that one, I already handle {@code } and {@link }

**Review by FroMage — APPROVED** [review]

**Comment by emmanuelbernard** [comment]
I agree an advanced flag would be nice.

**Pull request merged**
