### PR TITLE
Kubernetes Config: Expand properties by using the resource type and name

### PR DESCRIPTION
**Pull request by Sgitario**
This pull request partially resolves the issue https://github.com/quarkusio/quarkus/issues/27434.

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @iocanel @geoand @lordofthejars

**Comment by geoand** [comment]
Hm... I am kinda skeptical of this TBH. The whole idea of having the Kubernetes Config extension is to make reading configuration from `ConfigMap` and `Secret` transparent to the application... 
With this, the environment where the application will be deployed in "leaks" into the application as you need to know the name of the Kubernetes objects in the code. 
Moreover, I think it will be ackward for users working in dev-mode. How would they configure these values?

**Comment by Sgitario** [comment]
> Hm... I am kinda skeptical of this TBH. The whole idea of having the Kubernetes Config extension is to make reading configuration from `ConfigMap` and `Secret` transparent to the application... With this, the environment where the application will be deployed in "leaks" into the application as you need to know the name of the Kubernetes objects in the code. Moreover, I think it will be ackward for users working in dev-mode. How would they configure these values?

The idea is to not change how users work. I mean that this change does not introduce any breaking change, but in case of conflicts (same keys used in different resources), it offers a solution to inject one value or another.

**Comment by geoand** [comment]
Yeah I understand that, but having explicit support for things like:

```
@ConfigProperty(name = "configMaps/appConfig.hello.message")
```

is not something I much like

**Comment by Sgitario** [comment]
> Yeah I understand that, but having explicit support for things like:
> 
> ```
> @ConfigProperty(name = "configMaps/appConfig.hello.message")
> ```
> 
> is not something I much like

And do you have any other ideas for users with conflicts for the same key in different resources?

**Comment by geoand** [comment]
> And do you have any other ideas for users with conflicts for the same key in different resources?

Unfortunately no...

**Comment by gsmet** [comment]
OK, closing this as apparently it's not an approach we want to pursue.
Thanks anyway!

**Pull request closed without merging**
