### PR TITLE
Make sure the ordering of Maven repos in tests matches the ordering of the repos in Mojos

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Comment by aloubyansky** [comment]
I've noticed these tests failing on MacOS in other PRs too.

**Comment by geoand** [comment]
> I've noticed these tests failing on MacOS in other PRs too.

Yup, maybe we need to restart the runners @holly-cummins?

**Comment by geoand** [comment]
Does this fix a known issue?

**Review by geoand — APPROVED** [review]

**Comment by holly-cummins** [comment]
> > I've noticed these tests failing on MacOS in other PRs too.
> 
> Yup, maybe we need to restart the runners @holly-cummins?

We've got a zulip thread for this issue, but I'll convert it to an issue since I think this is going to be a slow burner: #28779. 

I've restarted the runners, but sadly it didn't help. I also can't reproduce locally. My "best" analysis, from looking at the line of code which is failing, is that build pixies come in, remove the docker binary from the machine while the mongo tests run, and then sneak back and reinstate the docker binary. (Somewhere, Occam's razor has its razor-head in its razor-hands.)

**Pull request merged**
