### PR TITLE
Improve support for infinispan marshaller

### PR DESCRIPTION
**Pull request by famarting**
From #2227 Allows to use `EnumMarshaller` and other basic Marshallers from infinispan
Thanks @karesti for your help

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
CC @karesti

**Review by karesti — CHANGES_REQUESTED** [review]
Just fix the formatting, amend the changes to the commit and check CI 🙏 
If everything is green, should be mergeable!

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
LGTM 😃

**Comment by famartinrh** [comment]
@emmanuelbernard we are missing one approval to merge this changes

**Review by gsmet — APPROVED** [review]

**Pull request merged**
