### PR TITLE
Hibernate Reactive Panache: fix WithSessionOnDemand implementation

### LINKED ISSUE #35568: Hibernate Reactive Panache MySQL
### Describe the bug

After Calling find() and count() on a table few times with ~10rows I am getting timeout:
I believe the connections are not being closed after the calls.

2023-08-25 11:28:34,464 ERROR [com.tha.ota.exc.ThrowableMapper] (vert.x-eventloop-thread-3) Timeout: io.vertx.core.impl.NoStackTraceThrowable: Timeout

```java
public static Uni<PageResult<Table>> findPage(Set<String> param1,
                                                       Param2 param2,
                                                       ...,
                                                       Page page,
                                                       Sort sort) {

        Set<String> whereClauses = new HashSet<>();
        Map<String, Object> params = new HashMap<>();
        
        ... I Build the where clause here

        Uni<Long> count = countBy(whereClause, params);

        Uni<List<Table>> content = findAllBy(whereClause, params, page, sort);

        return Uni.combine().all().unis(count, content)
                .asTuple()
                .map(tuple -> new PageResult<>(page.index, page.size, tuple.getItem1(), tuple.getItem2()));
    }

    private static Uni<Long> countBy(String whereClause, Map<String, Object> params) {
        return Table.count(
                "from Table t join t.table2 t2 join t2.table3 t3" + whereClause,
                params);
    }

    public static Uni<List<Table>> findAllBy(String whereClause, Map<String, Object> params, Page page, Sort sort) {
        String query = "from Table t join fetch t.table2 t2 join fetch t2.table3 t3" + whereClause;
        return Table.<Table>find(
                        query,
                        sort,
                        params
                )
                .page(page)
                .list();
    }
```

### Expected behavior

Not getting I timeout exception

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #35568

### CODE REVIEW

**Review by DavideD — APPROVED** [review]
Thanks!

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Should this be backported and if so, to which versions?

**Comment by mkouba** [comment]
> Does this affect 3.2 as well or only 3.3?

I believe that it affects all 3+ versions...

**Comment by aloubyansky** [comment]
Backport is problematic due to `io.quarkus.test.vertx` missing from 3.2

**Comment by mkouba** [comment]
> Backport is problematic due to `io.quarkus.test.vertx` missing from 3.2

Shall I send a separate PR without the test?

**Comment by aloubyansky** [comment]
Actually, I was wrong about `io.quarkus.test.vertx` missing from 3.2, mistake in an expression I used to search for it. There was still a conflict though with the test dependency.

**Comment by mkouba** [comment]
> Actually, I was wrong about `io.quarkus.test.vertx` missing from 3.2, mistake in an expression I used to search for it. There was still a conflict though with the test dependency.

Which dependency? Are we ok then?

**Comment by aloubyansky** [comment]
It depends on https://github.com/quarkusio/quarkus/pull/34334/files I'm checking whether what it takes to backport it too, it results in some conflicts as well.

**Comment by mkouba** [comment]
> It depends on https://github.com/quarkusio/quarkus/pull/34334/files I'm checking whether what it takes to backport it too, it results in some conflicts as well.

Hmm, but it seems that the `quarkus-test-hibernate-reactive-panache` module is not used in the test at all. Maybe we could just replace it with `quarkus-test-vertx`?

**Comment by aloubyansky** [comment]
If I backport https://github.com/quarkusio/quarkus/pull/34245 too, it applies w/o conflicts

**Comment by aloubyansky** [comment]
Changing to `quarkus-test-vertx` also works and is simpler, thanks @mkouba

**Pull request merged**
