### PR TITLE
Upgrade mariadb-java-client from 2.7.5 to 3.0.4

### PR DESCRIPTION
**Pull request by famod**
https://mariadb.com/docs/release-notes/mariadb-connector-j-3-0/3-0-4/

Another try, after #23249 and #23530. The issues that popped up back then have been addressed, AFAICS.
A quick test run in my project didn't reveal any issues (just more WARN-chattiness by `org.mariadb.jdbc.message.server.ErrorPacket`).

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by famod** [comment]
Btw, no changes compared to #23249 except for the version property.

**Comment by gsmet** [comment]
> just more WARN-chattiness by `org.mariadb.jdbc.message.server.ErrorPacket`

@famod but does that mean you end up with WARN messages in your logs for normal operations?

**Comment by famod** [comment]
@gsmet not in general, but I saw two warnings on a clean DB when liquibase runs for the first time. It was warning that DATABASECHANGELOG doesn't exist (and the lock table).
Other than that I saw (additional) warnings when a constraint was violated and stuff like that.

**Review by gsmet — APPROVED** [review]
Nice work, thanks!

**Comment by gsmet** [comment]
I see you asked for a backport. Is there anything pressing in the upgrade?

**Comment by famod** [comment]
Well, not really. Fits a .0 rather well?
Would have been ideal/better for CR but they don't seem to obey the Quarkus release schedule. 😉 

I'm not sure there will be any changes to the 2.x driver.
Are we back to more or less monthly Quarkus releases? If yes 2.9.0 won't be that far away, so ok for me.

**Comment by gsmet** [comment]
Yeah we are back to regular cycles. I'm on the verge for this one, I'll decide when doing the backport round :).

**Comment by famod** [comment]
Thanks for backporting, @gsmet!

**Pull request merged**
