### PR TITLE
Add openj9 images to the S2iBaseJavaImage

### LINKED ISSUE #10056: OpenJ9 images not recognized as using run-java.sh
**Description**
Quarkus has a hard-coded list of base S2I images known to use the `run-java.sh` mechanism: https://github.com/quarkusio/quarkus/blob/1.5.1.Final/extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iBaseJavaImage.java#L11-L19

This list doesn't include the Red Hat OpenJ9 images, which makes for a sub-par experience.

**Implementation ideas**
Just add the known OpenJ9 images to the `S2iBaseJavaImage` enum:

- https://catalog.redhat.com/software/containers/openj9/openj9-8-rhel7/5ddfdbf75a13461646f8171a
- https://catalog.redhat.com/software/containers/openj9/openj9-11-rhel7/5ddfdb26dd19c71643b652d5
- https://catalog.redhat.com/software/containers/openj9/openj9-8-rhel8/5ddfdbb8bed8bd164a0b1fa1
- https://catalog.redhat.com/software/containers/openj9/openj9-11-rhel8/5ddfdb765a13461646f816f0

### PR DESCRIPTION
**Pull request by ejba**
Fixes: #10056

/cc @geoand @iocanel

### CODE REVIEW

**Comment by geoand** [comment]
Great thanks!

I'll take a look tomorrow.

cc @Ladicek

**Comment by ejba** [comment]
yw :)

**Comment by ejba** [comment]
I am wondering if there is any question that I could do in this task.

**Review by geoand — APPROVED** [review]
LGTM, but I can't really tell for the env vars. @Ladicek do we have any way to verify the env vars are the same for these images?

**Comment by Ladicek** [comment]
Well, if you have access to an s390x machine, you can pull the images :grin:

But the OpenJ9 images are built from the same source as the OpenJDK ones: https://github.com/jboss-container-images/openjdk, and I've verified yesterday that the RHEL 8-based OpenJ9 11 image has the same scripts with the same env vars, so I think it's fine.

**Review by Ladicek — APPROVED** [review]

**Comment by geoand** [comment]
Great, thanks

**Pull request merged**
