### PR TITLE
Support MDC when using OTEL

### LINKED ISSUE #18228: Support for MDC log metadata when using Opentelemetry
## Description

When using the [smallrye opentracing extension](https://quarkus.io/guides/opentracing) in Quarkus applications, the [quarkus-logging-gelf](https://quarkus.io/guides/centralized-log-management) extension allows you to include the MDC (mapped diagnostic context) as metadata in each log record. This is essential when using a centralised logging system such as logstash as it allows logs to be filtered (via e.g. kibana) via trace/span/parentspan ids to trace interactions between multiple microservices communicating over synchronous (e.g. REST) or asynchronous (e.g. AMQP, Kafka) channels.

Currently the quarkus opentelemetry extension does not support this feature, which makes it unsuitable for use in a distributed logging system.

## Implementation ideas

None proposed, only that whatever implementation is chosen should meet the following requirements:

- The configuration (via those properties exposed by the gelf logging extension) should be identical to that used in the context of opentracing.
- The resultant log metadata fields should match (in type and name) those produced when used in the context of opentracing.

### PR DESCRIPTION
**Pull request by luneo7**
Add MDC information when using OTEL (traceId, spanId, parentId, sampled).
Fixes https://github.com/quarkusio/quarkus/issues/18228

### CODE REVIEW

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
Thanks for the PR @luneo7 :)

**Comment by VantronBluesphere** [comment]
@radcortez Hi, when will 2.10 release? I need this feature: [Support MDC when using OTEL](https://github.com/quarkusio/quarkus/pull/25671#)

**Comment by radcortez** [comment]
We have already released 2.10.0.CR1. The Final should be out in a few days.

**Comment by luneo7** [comment]
2.10.0.Final release is supposed to be tomorrow, but the artifacts are already published

**Pull request merged**
