### PR TITLE
Support for project modules that produce multiple JARs (with classifiers)

### PR DESCRIPTION
**Pull request by aloubyansky**
This is https://github.com/quarkusio/quarkus/pull/22336 plus the fix for `ApplicationArchiveImpl` exposing paths from open JARs that are now switched to PathTree-based API as well.

### CODE REVIEW

**Comment by famod** [comment]
So the main thing to look at is `ApplicationArchiveImpl` and the rest is more or less the same as in the first PR?

**Comment by aloubyansky** [comment]
The Qute failure is clear how to fix but the webjars issue isn't. I am still investigating it.

**Comment by gsmet** [comment]
@aloubyansky I don't think the webjar locator issue is related to your PR. Rostislav added the native testing recently and it has been unstable since then. We will remove the native testing for now.

**Comment by aloubyansky** [comment]
The failure isn't even related to native apparently. We are using `org.webjars.WebJarsAssetLocator` to locate the resources. While the resources are clearly visible on the classpath, it fails to locate them with my PR applied. So even `quarkus:build` won't see them. I really want to know what the cause is.

**Comment by aloubyansky** [comment]
I am not sure we want to rely on that logic. Basically, the resources the webjars scanner is looking for are on the classpath but it is trying to use all sorts of tricks to not load them through the ClassLoader API and this PR breaks it. I'll probably try to find a workaround.

**Comment by aloubyansky** [comment]
I ended up removing the dependency on the webjars-locator-core replacing it with our own webjars discovery on the classpath.

**Comment by aloubyansky** [comment]
The LiquibaseFunctionalityNativeIT is reproducible locally. My change passed the CI in my working branch before I updated the PR though. I am wondering whether I rebased before updating pulled in some other change.

**Comment by aloubyansky** [comment]
It's also reproducible on the main branch
````
[ERROR] Failures: 
[ERROR]   LiquibaseFunctionalityNativeIT>LiquibaseFunctionalityTest.testLiquibaseQuarkusFunctionality:21 1 expectation failed.
Response body doesn't match expectation.
Expected: is "create-tables-1,test-1,create-view-inline,create-view-file-abs,create-view-file-rel,json-create-tables-1,json-test-1,sql-create-tables-1,sql-test-1,yaml-create-tables-1,yaml-test-1,00000000000000,00000000000001,00000000000002,1613578374533-1,1613578374533-2,1613578374533-3"
  Actual: 

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
````

**Comment by aloubyansky** [comment]
Rebased just to get another CI run.

**Comment by aloubyansky** [comment]
I added a couple more fixes:
1. occasional failure originally reported in https://github.com/quarkusio/quarkus/pull/22639#issuecomment-1005495363. The issue is that I changed the bootstrap Maven resolver prefer locally built JARs if they exist over the `classes` dirs. It looks like this could be an issue in parallel builds when a JAR is created so `Files.exists(jar)` return true but it hasn't been written completely resulting in "end of ZIP missing" error trying to read it. Given that we know the workspace in `extension-descriptor`, I am checking whether it's a parallel build and if it is I am switching to the `classes` dir to read extension descriptors.
2. There is a trick in the current impl to allow re-reading JAR content if the thread was interrupted. I originally copied its impl but it's JarFile-based while this PR NIO-based. The thrown exceptions changed from `InterruptedIOException` to `ClosedByInterruptionException` and `ClosedChannelException`. I adjusted the code to handle those and I don't see misleading stacktraces logged for info purposes anymore.

I've been running CI multiple times with these changes in my working branches w/o getting any failure. So, this should be good to merge.

**Comment by famod** [comment]
@aloubyansky Sounds good! Shall I give it another try with my project?

**Comment by aloubyansky** [comment]
I won't say no to that :)

**Comment by famod** [comment]
Looking good!

**Review by gsmet — APPROVED** [review]
So this is a large patch but it fixes quite a lot of complex issues and after discussion with @geoand @aloubyansky @famod , we want to get it in for 2.7.

It has already been through a first round of reviews in the first PR and got through some important testing.

**Pull request merged**
