### PR TITLE
Qute user tags - use defaulted keys if appropriate

### LINKED ISSUE #21855: Qute: shorter tag invocation
### Description

I found myself having lots of calls to tags that boiled down to:

```html
 {#likeAlbum album=album user=user/}
 {#voteAlbum album=album user=user/}
```

And I wonder if we couldn't simplify those calls to:

```html
 {#likeAlbum album user/}
 {#voteAlbum album user/}
```

That is: if we're passing a template parameter with no value (or no name, depending on how you look at it), we expand `<ident>` to `<ident>=<ident>`.

If I'm not mistaken, we can already currently pass a single parameter with no name, which ends up named as `it`, so we could expand the rules by saying that if the first parameter with no name is a single identifier (no dots, no complex expression) we make it available to the tag as both `it` and `<ident>`?

So, in our case, for a call of `{#likeAlbum album user/}` the `album` value would be bound to both `it` and `album` in the tag. I think that would make sense, no?

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- i.e. for params that define no key and contain only single part
- also use Mapper instead of Map for the data passed to a template
- Mapper value resolver has priority 15, i.e. is called before a
generated value resolver
- resolves #21855
- related to #21861

### CODE REVIEW

**Comment by mkouba** [comment]
@FroMage This is the initial attempt to solve #21861. It should solve the problem with `class` and `size`. Furthermore, it's possible to configure that a user tag should not delegate to the parent context, e.g. `{#test class="myclass" _isolated=true /}`. I'm still not convinced it should be the default behavior but if we decide to do so it will be a one-liner. I'm also not sure about the name of the config property - `_isolated` should be quite unambiguous one-word but it's not very intuitive.

**Comment by FroMage** [comment]
OK thanks. This is missing docs though. And I really think tags should be isolated by default, as every programming language function.

Naturally, for tags that accept a body, the body should be resolved in the context of the parent, and not the tag. But again, exactly the same scoping rules as Java and most modern programming languages.

**Comment by mkouba** [comment]
> This is missing docs though.

Yes, it's not documented because I'm still not convinced of the param name... Maybe something like  `_skipParent`  or `_noParent` would be more understandable?

> Naturally, for tags that accept a body, the body should be resolved in the context of the parent, and not the tag. But again, exactly the same scoping rules as Java and most modern programming languages.

Well, I'll be repeating myself but tags are IMO not functions but more like a specialized include directives. I get your point but I'm hesitating to change the default behavior and introduce another breaking change. Moreover, we would have to follow the same rules for `{#include}` sections...

**Comment by FroMage** [comment]
I don't know what external scope is visible from includes, that's not obvious from https://quarkus.io/guides/qute-reference#include_helper

In general, I really think we should stick to programming language semantics, especially Java, because that's what make the most sense for Quarkus devs.

**Comment by mkouba** [comment]
> I don't know what external scope is visible from includes, that's not obvious from https://quarkus.io/guides/qute-reference#include_helper

It's simply the parent scope. The docs mention _"The included template can reference data from the current context."_.

> In general, I really think we should stick to programming language semantics, especially Java, because that's what make the most sense for Quarkus devs.

+1 but it's a pity we did not catch this a few dozen versions back  :-(

**Comment by mkouba** [comment]
I've updated the docs. Let's merge this now and we can decide to change the default behavior later... @FroMage WDYT?

**Comment by FroMage** [comment]
Well, now you've pretty much set it in stone in the docs that the current behaviour is dynamic scoping, so people may start using it. If you agree that this is the direction we should go do, we should make the change now that people are most likely not relying on dynamic scoping for user tags, and perhaps include a configuration setting to enable the old behaviour in case people depend on it?

**Comment by mkouba** [comment]
> Well, now you've pretty much set it in stone in the docs that the current behaviour is dynamic scoping, so people may start using it.

The current behaviour is "dynamic scoping" and it was like that since the beginning.

> If you agree that this is the direction we should go do, we should make the change now that people are most likely not relying on dynamic scoping for user tags, and perhaps include a configuration setting to enable the old behaviour in case people depend on it?

This PR merely clarifies the current behavior and I am still not sure which direction to go. But I agree that we should decide in the scope of 2.7. I can create a [new discussion topic](https://github.com/quarkusio/quarkus/discussions) and we can create a follow-up PR if we decide to do a breaking change.

**Comment by mkouba** [comment]
I've created https://github.com/quarkusio/quarkus/discussions/22285

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by mkouba** [comment]
I'm going to merge this one, let's continue the discussion in https://github.com/quarkusio/quarkus/discussions/22285.

**Pull request merged**
