### PR TITLE
Upgrade to Infinispan 12.0.0.Final

### PR DESCRIPTION
**Pull request by karesti**
https://infinispan.org/blog/2021/01/15/infinispan-12-final

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand there was a RESTEasy Reactive failure on Windows:
```
Error:  Failures: 
Error:    StreamTestCase.testSse:147 expected: <[a, b, c]> but was: <[]>
```
I wonder why we can't get this SSE tests to be stable enough?

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
I don't know, I haven't dealt with SSE much.

@FroMage does this ring a bell?

**Comment by gsmet** [comment]
Thanks!

**Comment by FroMage** [comment]
It does not ring a bell, is this the first time it happens?

**Comment by geoand** [comment]
I personally don't recall seeing that one faile before

**Pull request merged**
