### PR TITLE
Add user-agent to resteasy reactive client

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by geoand** [comment]
Hm... I did something more general in https://github.com/quarkusio/quarkus/pull/22236

**Comment by FroMage** [comment]
Well, you did something more general, and that's great, but it also doesn't set a `User-Agent` by default ;) So it doesn't fix my issue. I'm fairly sure that having a default one is the right thing to do.
Being able to override it with config is great too, but ideally we'd still have a default one, so probably we need both PRs :)

**Comment by geoand** [comment]
Sure, we can do both 😉

**Comment by stuartwdouglas** [comment]
I think we probably want both.

**Review by geoand — APPROVED** [review]

**Pull request merged**
