### PR TITLE
Improve Qute + Cache integration

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Looks good.

**Comment by stefanorg** [comment]
The issue has not been solved in LTS release?
I'm using 3.2.6.Final

```
[INFO] Quarkus platform BOMs:
[INFO]         io.quarkus:quarkus-bom:pom:3.2.6.Final ✔
[INFO] 
[INFO] Extensions from io.quarkus:quarkus-bom:
[INFO]         io.quarkus:quarkus-hibernate-validator ✔
[INFO]         io.quarkus:quarkus-logging-json ✔
[INFO]         io.quarkus:quarkus-mongodb-panache ✔
[INFO]         io.quarkus:quarkus-smallrye-graphql ✔
[INFO]         io.quarkus:quarkus-arc ✔
[INFO]         io.quarkus:quarkus-jdbc-mysql ✔
[INFO]         io.quarkus:quarkus-agroal ✔
[INFO]         io.quarkus:quarkus-resteasy-reactive ✔
[INFO]         io.quarkus:quarkus-rest-client-reactive-jackson ✔
[INFO]         io.quarkus:quarkus-jackson ✔
[INFO]         io.quarkus:quarkus-rest-client-reactive ✔
[INFO]         io.quarkus:quarkus-elytron-security-oauth2 ✔
[INFO]         io.quarkus:quarkus-opentelemetry ✔
[INFO]         io.quarkus:quarkus-vertx ✔
[INFO]         io.quarkus:quarkus-config-yaml ✔
[INFO]         io.quarkus:quarkus-smallrye-metrics ✔
[INFO]         io.quarkus:quarkus-smallrye-health ✔
[INFO]         io.quarkus:quarkus-container-image-docker ✔
[INFO]         io.quarkus:quarkus-elasticsearch-rest-client ✔
[INFO]         io.quarkus:quarkus-hibernate-orm-panache-common ✔
[INFO]         io.quarkus:quarkus-hibernate-orm ✔
[INFO]         io.quarkus:quarkus-redis-cache ✔
[INFO]         io.quarkus:quarkus-smallrye-fault-tolerance ✔
[INFO]         io.quarkus:quarkus-resteasy-reactive-jackson ✔
[INFO]         io.quarkus:quarkus-hibernate-orm-panache ✔
[INFO]         io.quarkus:quarkus-cache ✔
[INFO]         io.quarkus:quarkus-smallrye-openapi ✔
[INFO]         io.quarkus:quarkus-oidc-client-reactive-filter ✔
[INFO]         io.quarkus:quarkus-redis-client ✔
[INFO]         io.quarkus:quarkus-resteasy-reactive-qute ✔
[INFO] 
[INFO] Extensions from io.quarkus.platform:quarkus-amazon-services-bom:
[INFO]         io.quarkiverse.amazonservices:quarkus-amazon-common:2.3.2 ⚠
[INFO]         io.quarkiverse.amazonservices:quarkus-amazon-sns:2.3.2 ⚠
[INFO]         io.quarkiverse.amazonservices:quarkus-amazon-ssm:2.3.2 ⚠
[INFO] 

```

**Comment by geoand** [comment]
Not yet. The fix will be backported at some point

**Comment by stefanorg** [comment]
ok thank you :+1:

**Pull request merged**
