### PR TITLE
Unclutter dev mode logging

### LINKED ISSUE #1393: dev mode logging is not configurable
Logging for quarkus:dev mode is not configurable. Users should be able to define logging configuration via application.properties files

### LINKED ISSUE #1764: Logging filters not applied in dev mode
Current output when starting a simple project in dev mode is:
```
15:21:15,610 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
15:21:15,761 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Alpha4
15:21:15,864 WARN  [io.qua.config] Unrecognized configuration key "quarkus.undertow.resources" provided
15:21:16,209 INFO  [io.qua.dep.QuarkusAugmentor] Quarkus augmentation completed in 599ms
15:21:16,228 INFO  [io.sma.ope.api.OpenApiDocument] OpenAPI document initialized: io.smallrye.openapi.api.models.OpenAPIImpl@6b09fb41
15:21:16,356 INFO  [org.xnio] XNIO version 3.7.0.Final
15:21:16,363 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.0.Final
15:21:16,445 INFO  [io.quarkus] Quarkus 999-SNAPSHOT started in 0.938s. Listening on: http://[::]:8080
15:21:16,445 INFO  [io.quarkus] Installed features: [cdi, resteasy, resteasy-jsonb, smallrye-openapi]
```

The log filters are not applied.

### LINKED ISSUE #1803: Warn in dev mode: Unrecognized configuration key "quarkus.undertow.resources" provided
When creating a simple project with:
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create  -DprojectGroupId=org.acme     -DprojectArtifactId=using-openapi-swaggerui -DclassName="org.acme.openapi.swaggerui.FruitResource" -Dpath="/fruits" -Dextensions="resteasy-jsonb"
```
and running:
```
mvn compile quarkus:dev
```
we end up with the following warning:
```
17:14:30,561 WARN  [io.qua.config] Unrecognized configuration key "quarkus.undertow.resources" provided
```

### PR DESCRIPTION
**Pull request by gsmet**
- Change `quarkus.undertow.resources` to `quarkus-internal.undertow.resources` to avoid an unrecognized config log message
- Remove some newly added log messages (some debug messages were moved to info by mistake AFAICS)
- Restore log cleanup filters and colors by reverting https://github.com/quarkusio/quarkus/pull/1375 and fixing it in a different way

Fixes #1764 
Fixes #1803 
Also fixes https://github.com/quarkusio/quarkus/issues/1393 as it was introduced by https://github.com/quarkusio/quarkus/pull/1375

### CODE REVIEW

**Comment by gsmet** [comment]
@johnaohara I think I addressed the initial issue you had in #1375 in a more conservative way. Could you check it's OK for you?

**Comment by johnaohara** [comment]
@gsmet this approach is the approach suggested by @stuartwdouglas. I will confirm that #1363 is resolved by this change

**Comment by gsmet** [comment]
@johnaohara yes, so it's not exactly the approach you discussed in the issue as it's not a shutdown hook. I just flush the messages if we have an error.

**Review by dmlloyd — APPROVED** [review]

**Comment by johnaohara** [comment]
@gsmet this pr resolves #1363 and the exception messages are printed to console if there is an error in dev mode

**Review by johnaohara — APPROVED** [review]

**Comment by gsmet** [comment]
Everyone is happy, merging then :)

**Pull request merged**
