### PR TITLE
Remove ProfileManager

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by geoand** [comment]
I am wondering if there are any extensions in the Platform or the Quarkiverse that use it... Do you have any idea?

**Comment by radcortez** [comment]
Unsure, but the main method has been deprecated for a while with a pointer to use the new one, especially because the old one doesn't support multiple profiles.

**Comment by radcortez** [comment]
2.16 :D

https://github.com/quarkusio/quarkus/pull/28091

**Review by geoand — COMMENTED** [review]
In that case, kill it!

**Review by geoand — APPROVED** [review]

**Comment by rsvoboda** [comment]
@radcortez / @geoand is this something to highlight in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.11?

https://github.com/search?q=io.quarkus.runtime.configuration.ProfileManager&type=code shows some hits, e.g. Keycloak and apicurio-registry

**Comment by Pepo48** [comment]
+1 for this to be mentioned in the migration guide. 

Jfyi, I can confirm that this is something that will need to be addressed in Keycloak. It already broke our last night's CI run with quarkus-nightly (that's actually the reason I found this PR at the first place) 😊.

**Comment by radcortez** [comment]
Ok, added the following text:

Removed deprecated ProfileManager#getActiveProfile and ProfilaManger. The ProfileManager could not handle multiple profiles, added in Quarkus 2.16. To retrieve the active profile, please use io.quarkus.runtime.configuration.ConfigUtils#getProfiles. The configuration name used to retrieve the Quarkus profile cannot be appropriately determined by a simple constant definition (as it was in ProfileManager); if you need it, please use LaunchMode.current().getProfileKey().

**Comment by Pepo48** [comment]
>  if you need it, please use LaunchMode.current().getProfileKey()

@radcortez I assume that `ProfileManager.getLaunchMode().getProfileKey(), profile)` is just another way of achieving the suggested, right?

**Comment by radcortez** [comment]
Yes, but that one will also get removed, so please use `LaunchMode.current().getProfileKey()`.

**Comment by Pepo48** [comment]
@radcortez got it, thanks!

**Pull request merged**
