### PR TITLE
Switch to `jboss-logmanager`

### LINKED ISSUE #2152: Anything which starts logging too early will disable Quarkus logging
The upstream LogManager has some stuff in it to prevent this from happening.  We should use that stuff.

### LINKED ISSUE #7640: Wrong logging format when using -javaagent or -agentpath
**Describe the bug**
When a Java-Agent is attached to quarkus running in jvm-Mode, the Log-Format specified by default from quarkus or the one specified in the application.properties is not used to format Log-Messages anymore. This only happens, when the Java-Agent is producing Log-Messages as well.

**Expected behavior**
Logs should look like this:
```console
2020-03-06 12:33:28,145 INFO  [io.quarkus] (main) agent-test 1.0-SNAPSHOT (running on Quarkus 1.2.1.Final) started in 0.913s. Listening on: http://0.0.0.0:8080
```

**Actual behavior**
Logs do look like this:
```console
Mõr 06, 2020 12:34:40 PM io.quarkus.runtime.Timing printStartupTime
INFO: agent-test 1.0-SNAPSHOT (running on Quarkus 1.2.1.Final) started in 0.854s. Listening on: http://0.0.0.0:8080
```

**To Reproduce**
1. I used the quarkus-create command to create a default project called "agent-test" with the following "HelloResource":
```java
package de.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("/hello")
public class HelloResource {

    private static final Logger LOG = LoggerFactory.getLogger(HelloResource.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response hello() {
        LOG.info("Entered hello");
        Response response = Response.ok("hello").build();
        LOG.info("Hello responeded with {}", response.getStatus());
        return response;
    }
}
```
You can also find the project here:
[agent-test.zip](https://github.com/quarkusio/quarkus/files/4298148/agent-test.zip)

2. I created a simple Java-Agent which is only producing a LOG-Message to avoid any issues with other thrid party agents. It has only one class called "SimpleAgent":
```java
package de.example;

import java.lang.instrument.Instrumentation;
import java.util.logging.Logger;

public class SimpleAgent {

    public static void premain(String agentArgs, Instrumentation inst) {
        Logger LOG = Logger.getLogger(SimpleAgent.class.getName());
        LOG.info("This message was created by SimpleAgent");
        System.out.println("-------------------------------------------------------------");
    }

}
``` 
and the MANIFEST.MF file:
```
Manifest-Version: 1.0
Premain-Class: de.example.SimpleAgent
```
You can also find the code for the agent here:
[SimpleJavaAgent.zip](https://github.com/quarkusio/quarkus/files/4298182/SimpleJavaAgent.zip)

3. I created a jar-artifact called "SimpleAgent.jar" for the described agent.

4. I built the quarkus-runner.jar using
```
mvn clean package
```
and started it using
```
java -javaagent:path/to/agent/SimpleAgent.jar -jar path/to/quarkus/agent-test-1.0-SNAPSHOT-runner.jar
```

**Configuration**
I used the default quarkus configuration, so there are no properties specified in application.properties

**Environment:**
 - java`: java version 1.8.0_201. also tested using OpenJDK 11.0.3
 - GraalVM version (if different from Java): not used
 - Quarkus version or git rev: 1.2.1.Final, also tested using 1.0.0.Final and 1.1.0.Final
 - Build tool:  Apache Maven 3.6.0
Different environments (java-version, quarkus-version and operating systems) did not change the described behavior.

### LINKED ISSUE #9679: Logging: support microseconds in %d log pattern
**Description**

The current implementation is based on SimpleDateFormat and is limited to milliseconds (i.e. %d{SSSSSS} does not work and prefixes with 000).
https://github.com/jboss-logging/jboss-logmanager/blob/master/core/src/main/java/org/jboss/logmanager/formatters/Formatters.java#L443-L458

With Java 9+, OpenJDK added support for better precision than milliseconds/nano-of-second (https://bugs.openjdk.java.net/browse/JDK-8068730).

Quarkus being supersonic, its logging should support this ! :p

**Implementation ideas**

Since [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html ) was added in Java 8, maybe there's a fallback and it doesn't have to wait for Quarkus to drop Java 8 support ?

### LINKED ISSUE #33109: java.lang.System logging is not routed to Quarkus logging
### Describe the bug

When JDK logs using `System.Logger`:
```
    public static final System.Logger logger = System.getLogger("foo.bar");
    public static void debug(String fmt, Object... params) {
        logger.log(System.Logger.Level.DEBUG, fmt, params);
    }
```
even though Quarkus is built with `-Dquarkus.log.min-level=TRACE` and ran with `-Dquarkus.log.level=TRACE -Dquarkus.log.console.level=TRACE` these message are not printed out.

### Expected behavior

Quarkus logs this at DEBUG level.

### Actual behavior

Logs from within Quarkus systems are correctly printed but System logging is not printed anywhere.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

OpenJDK CRaC build

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dmlloyd**
Drop the old `jboss-logmanager-embedded` in favor of `jboss-logmanager`.

* Update all relevant POMs to reference `jboss-logmanager` instead of `jboss-logmanager-embedded`
* Remove `jboss-logmanager` from the banned dependencies list (without replacement)
* Update `jboss-logmanager-embedded` to `1.2.0.Final`, which is a relocation that points to `jboss-logmanager` `3.0.0.Final`; this artifact will never be changed again
    * n.b. users who have an explicit dependency on this older artifact will automatically be forwarded to the version of `jboss-logmanager` found in our BOM
* Update logging extension for API differences
* Use the upstream banner formatter for the startup banner

(Possibly) Fixes #2152
(Possibly) Fixes #7640
Fixes #9679
Fixes #33109

### CODE REVIEW

**Comment by dmlloyd** [comment]
Looks like the artifact hasn't propagated yet. Will retry CI in 24 hours.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
@dmlloyd should this be taken out of draft?

**Comment by dmlloyd** [comment]
Probably not until `3.0.0.Final` is tagged, which depends on testing in WildFly as well.

**Comment by gsmet** [comment]
@dmlloyd what's the status of this one?

**Comment by dmlloyd** [comment]
We're still waiting for the WildFly integration and testing to be complete before 3.0.0.Final can be released. I understand that @jamezp is making steady progress on that.

**Comment by gsmet** [comment]
Perfect, thanks for the update.

**Comment by geoand** [comment]
Does it make sense to use `3.0.0.Beta1` for now?

**Comment by gsmet** [comment]
I don't think we are in a hurry on this. So let's wait for the Final.

**Comment by geoand** [comment]
Cool

**Review by geoand — APPROVED** [review]

**Comment by dmlloyd** [comment]
Failure is related, will check it out in the morning.

**Comment by dmlloyd** [comment]
Wow. I'll have to check into this next week.

**Comment by geoand** [comment]
My guess is that it's not a parent first dependency?

**Comment by dmlloyd** [comment]
Hmm, well I added it as a parent-first dependency and it still isn't working in the Gradle ITs (reproduced the problem locally). Still trying to figure out what the problem is.

**Comment by geoand** [comment]
The native tests seem to be failing with:

```
2023-07-24T23:17:31.3563756Z Error: could not find target field: java.util.logging.Handler[] io.quarkus.runtime.graal.Target_org_jboss_logmanager_LoggerNode.handlersRef
2023-07-24T23:17:31.3567927Z com.oracle.svm.core.util.UserError$UserException: could not find target field: java.util.logging.Handler[] io.quarkus.runtime.graal.Target_org_jboss_logmanager_LoggerNode.handlersRef
```

**Comment by dmlloyd** [comment]
I had updated the field type but didn't notice that the field name had also changed...

**Comment by geoand** [comment]
👌🏼

**Comment by geoand** [comment]
Understood. Let me know if we want me to take a look

**Comment by dmlloyd** [comment]
Looks like more mismatches in classes between the old and new impl. We'll see how this goes...

**Comment by dmlloyd** [comment]
Phew, okay. Here's one new failure:

```
Error:  Failures: 
Error:    JarRunnerIT.testThatFastJarCustomOutputDirFormatWorks:182->assertThatFastJarFormatWorks:839->assertResourceReadingFromClassPathWorksCorrectly:709 
expected: "success"
 but was: "assert-multi-release-jar / Incorrect ClassLoader for class io.smallrye.common.cpu.ProcessorInfo"
```

Clearly this is a result of putting the SmallRye Common dependencies of JBoss LogManager onto the parent-first class loader. But I'm not completely sure what the fix is; maybe this test is no longer needed because we know which class loader it will be on?

**Comment by dmlloyd** [comment]
Additionally, we have:

```
Caused by: java.lang.NullPointerException: receiver is null
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotConstantReflectionProvider.readFieldValue(HotSpotConstantReflectionProvider.java:175)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.ReadableJavaField.readFieldValue(ReadableJavaField.java:77)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:285)
...
```

Which is likely another mistake in the substitution changes and/or a generated substitution which is incorrect now, that I missed.

**Comment by geoand** [comment]
I think that we should just change the assertion on JarRunnerIT.testThatFastJarCustomOutputDirFormatWorks since we are including more jars as parent first

**Comment by dmlloyd** [comment]
Change it to check some other class? Which though... presumably it has to be class in a non-parent-first JAR, one which is reliably always included, but we don't have a list of those.

**Comment by geoand** [comment]
How about adding `smallrye-common-vertx-context` [here](https://github.com/quarkusio/quarkus/blob/8776b7896b2e02291cb3f6252e12e1c586fd2594/integration-tests/maven/src/test/resources-filtered/projects/rr-with-json-logging/pom.xml) and using clases of that dependency (that has not been made parent first)?

**Comment by dmlloyd** [comment]
Part of *a* problem is here: https://github.com/jboss-logging/jboss-logmanager/pull/420

**Comment by geoand** [comment]
👌

**Comment by cescoffier** [comment]
Any update on this PR? 
I know @dmlloyd is in PTO, so I believe it will have to wait.

The problem is that we need this update for Java 21. The current version is pinning when using a virtual thread (so basically, you cannot log from a virtual thread, which is.... annoying). 
The fix is already in 3.0.0.Final.

**Comment by geoand** [comment]
I don't think we have version `3.0.1.Final` that according to @dmlloyd is needed to fix the native issues

**Comment by dmlloyd** [comment]
At least one native issue anyway :-) James mentioned he may have time for this this week.

**Comment by jamezp** [comment]
I can do a release tomorrow. Sorry for the delay on this.

**Comment by jamezp** [comment]
3.0.1.Final has been released to JBoss Nexus. It will take a bit for it to be available in Maven Central https://github.com/jboss-logging/jboss-logmanager/releases/tag/3.0.1.Final.

**Comment by geoand** [comment]
Thanks @jamezp! 

I force pushed an update to the PR using the new version. Let's see what CI says.

**Comment by geoand** [comment]
It doesn't, but GraalVM doesn't know that.
I'm going on PTO, so this will have to wait a few days (unless someone else wants to pick it up)

**Comment by geoand** [comment]
@jamezp I tested one of the failures with a combination of a [fix](https://github.com/jboss-logging/jboss-logmanager/pull/426) in jboss-logmanager and the following patch to this PR:

```diff
Index: core/runtime/src/main/java/io/quarkus/runtime/graal/LoggingSubstitutions.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/runtime/src/main/java/io/quarkus/runtime/graal/LoggingSubstitutions.java b/core/runtime/src/main/java/io/quarkus/runtime/graal/LoggingSubstitutions.java
--- a/core/runtime/src/main/java/io/quarkus/runtime/graal/LoggingSubstitutions.java	(revision 00e0c93b4fec362eaaa6dede1bcad208488b5031)
+++ b/core/runtime/src/main/java/io/quarkus/runtime/graal/LoggingSubstitutions.java	(revision e932ffe949f5312912cbfae235e06fee8ceaa28f)
@@ -24,6 +24,15 @@
     Handler[] handlers;
 }
 
+@TargetClass(className = "org.jboss.logmanager.configuration.ObjectBuilder$ModuleFinder")
+final class Target_org_jboss_logmanager_configuration_ObjectBuilder$ModuleFinder {
+
+    @Substitute
+    static ClassLoader getClassLoader(final String moduleName) throws Exception {
+        return Thread.currentThread().getContextClassLoader();
+    }
+}
+
 @TargetClass(className = "org.slf4j.LoggerFactory")
 final class Target_org_slf4j_LoggerFactory {
```

and it passed

**Comment by geoand** [comment]
Thanks!

**Comment by cescoffier** [comment]
Any update?

**Comment by geoand** [comment]
I force pushed a wip commit - let's see

**Comment by geoand** [comment]
The errors do seem related, we have for example:

```posh
2023-08-19T06:34:12.0102681Z Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=io.smallrye.common.ref.References$ReaperThread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
2023-08-19T06:34:12.0103513Z Trace: Object was reached by
2023-08-19T06:34:12.0103876Z   reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.waiter of constant 
2023-08-19T06:34:12.0104476Z     java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode@38a3057a: java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode@38a3057a
2023-08-19T06:34:12.0105098Z   reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.lastWaiter of constant 
2023-08-19T06:34:12.0105723Z     java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3b3319b9: java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3b3319b9
2023-08-19T06:34:12.0106246Z   reading field java.lang.ref.ReferenceQueue.notEmpty of constant 
2023-08-19T06:34:12.0106619Z     java.lang.ref.ReferenceQueue@7fb7f0f9: java.lang.ref.ReferenceQueue@7fb7f0f9
2023-08-19T06:34:12.0107035Z   scanning root java.lang.ref.ReferenceQueue@7fb7f0f9: java.lang.ref.ReferenceQueue@7fb7f0f9 embedded in 
2023-08-19T06:34:12.0107462Z     io.smallrye.common.ref.PhantomReference.<init>(PhantomReference.java:39)
2023-08-19T06:34:12.0107931Z   parsing method io.smallrye.common.ref.PhantomReference.<init>(PhantomReference.java:39) reachable via the parsing context
2023-08-19T06:34:12.0108396Z     at org.jboss.logmanager.LoggerNode.createLogger(LoggerNode.java:308)
2023-08-19T06:34:12.0108883Z     at org.jboss.logmanager.LogContext.getLogger(LogContext.java:312)
2023-08-19T06:34:12.0109260Z     at org.jboss.logmanager.LogManager.getLogger(LogManager.java:237)
2023-08-19T06:34:12.0109615Z     at org.jboss.logmanager.LogManager.getLogger(LogManager.java:44)
2023-08-19T06:34:12.0110093Z     at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:137)
2023-08-19T06:34:12.0110677Z     at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit1899082837.deploy_0(Unknown Source)
2023-08-19T06:34:12.0111245Z     at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit1899082837.deploy(Unknown Source)
2023-08-19T06:34:12.0111691Z     at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-08-19T06:34:12.0112053Z     at io.quarkus.runtime.Application.start(Application.java:101)
2023-08-19T06:34:12.0112498Z     at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
2023-08-19T06:34:12.0112906Z     at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
2023-08-19T06:34:12.0113232Z     at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2023-08-19T06:34:12.0113515Z     at static root method.(Unknown Source)
```

**Comment by dmlloyd** [comment]
I think this is going to be a question of patching the `io.smallrye.common.ref.References$ReaperThread` class so that it starts its thread at run time.

**Comment by dmlloyd** [comment]
Relates to smallrye/smallrye-common#238.

**Comment by dmlloyd** [comment]
Updated and turned to draft until after SmallRye Common is tagged & updated.

**Comment by dmlloyd** [comment]
Now that native was getting farther, its reachability algorithm was encountering the property configurator code which had been deleted from the embedded version. I've added substitutions to ensure that this code is not reached by GraalVM.

**Comment by geoand** [comment]
👌

**Review by geoand — APPROVED** [review]

**Comment by cescoffier** [comment]
Awesome! Keeping my fingers crossed.

**Comment by geoand** [comment]
@dmlloyd should we mark this as ready?

**Comment by dmlloyd** [comment]
Not yet, I still need to release SmallRye Common and update its version here.

**Comment by cescoffier** [comment]
@dmlloyd I've seen the release of smallrye-commons. So we should be good to go, no?

**Comment by dmlloyd** [comment]
Yeah it didn't propagate during my workday yesterday but it has now. I'll get the PR updated as soon as I get started today.

**Comment by dmlloyd** [comment]
This failure is due to another difference from the embedded logmanager. If it detected that handlers are null, it would assume that the handlers array needs to be reconfigured. The new logmanager assumes that the handlers field is never null, so the substitutions are creating an invalid state at native image run time.

**Comment by geoand** [comment]
Not sure if the test is flaky because the failure does not seem to indicate that this PR is responsible

**Comment by dmlloyd** [comment]
The failure is caused by a bug in a substitution found in `smallrye-common-net`. Tracked in smallrye/smallrye-common#241.

**Comment by cescoffier** [comment]
ah ah ah, I merged first :-) Rebase time @dmlloyd!

**Pull request merged**
