### PR TITLE
opentracing, jaeger, xnio, debezium, log4j2, assertj, junit-jupiter minor version updates

### PR DESCRIPTION
**Pull request by rsvoboda**
opentracing, jaeger, xnio, debezium, log4j2, assertj, junit-jupiter minor version updates

I tried locally both `mvn clean install` and `mvn clean install -Dnative`, no issues hit.

### CODE REVIEW

**Comment by rsvoboda** [comment]
Weird, I haven't seen any failure locally.
Running io.quarkus.example.test.RestClientITCase again to be sure: `mvn -pl integration-tests/main clean integration-test -Dnative  -Dit.test=RestClientITCase -Dtest=NONE -DfailIfNoTests=false`

**Comment by dmlloyd** [comment]
Don't bother updating `jboss-modules`, it's only a compilation stub at this point.  In fact, let's see if we can remove it completely now that JBoss LogManager is out of tree.

**Comment by rsvoboda** [comment]
I will update the PR tmr, still struggling to reproduce failures from CI.

Installed F29 into VirtualBox, running main module of integration TS with -Dnative and have pass.

Any tips are welcome.

**Comment by rsvoboda** [comment]
So the tests which are failing were merged 5 hours ago - https://github.com/quarkusio/quarkus/commit/0311eb8170711ee31b2a575c6b641488e53dc5cc
So that's why I didn't see the failures

**Comment by rsvoboda** [comment]
I see the failures on master too :(

**Comment by rsvoboda** [comment]
Test issue was fixed, reverting the reverts and dropping jboss-modules update

**Comment by Sanne** [comment]
great, thanks! Testing one last time locally ...

**Review by Sanne — APPROVED** [review]

**Pull request merged**
