### PR TITLE
 Fix #3321 create-extension Maven mojo should allow creating from scratch

### LINKED ISSUE #3321: create-extension Maven mojo should allow creating from scratch
A followup of #2113 .

create-extension Maven mojo added via #3191 allows creating new extension modules inside an existing source tree. It should be enhanced to be able to create new extension projects from scratch.

cc @aloubyansky @Dufgui

### PR DESCRIPTION
**Pull request by ppalaga**
The first two commits are covered by https://github.com/quarkusio/quarkus/pull/3407 so they do not need to get reviewed here.

### CODE REVIEW

**Comment by aloubyansky** [comment]
This is basically the same approach I was investigating. I was just thinking it could be organized slightly differently, e.g.
````
build-parent/
|- application/
|  `- pom.xml (parent for apps built on Quarkus core, flattened)
|- extension/
|  `- pom.xml (parent for extensions built on Quarkus core, probably has application/pom.xml as its parent, flattened)
`- internal/
   `- pom.xml (Quarkus core build parent pom, has extension/pom.xml as its parent).
````
However, before actually applying this kind of change, it'd be a good idea to announce/discuss it on the dev list.

**Comment by ppalaga** [comment]
Yes, I think your proposal could work for me too.

+1 for opening the topic on quarkus-dev. Could you please do that because I think I am not acquainted with all problems your tri-section tries to solve?

**Comment by aloubyansky** [comment]
Here it is https://groups.google.com/forum/#!topic/quarkus-dev/UoDBpG4PCJQ

**Comment by ppalaga** [comment]
Blocked by https://github.com/quarkusio/quarkus/issues/1594 

@aloubyansky may I expect that you are going to fix https://github.com/quarkusio/quarkus/issues/1594 ?

**Comment by aloubyansky** [comment]
Yes, I can look into this next week.

**Comment by gsmet** [comment]
@aloubyansky do you still plan to work on this one?

**Comment by aloubyansky** [comment]
Yes, I am working on the split. Not a trivial task. In addition, getting destructed by other issues. We'll most probably need to discuss the details when I am more or less satisfied with my prototype.

**Comment by gsmet** [comment]
@aloubyansky OK, thanks for the feedback!

**Comment by cescoffier** [comment]
Any update on this one? Would be great to have it!

**Comment by ppalaga** [comment]
@cescoffier fully forgot it, sorry. I hope I can get back to it when I have a couple of free cycles.

**Comment by gsmet** [comment]
@aloubyansky I think we should define a proper plan to have things in line with your other parent pom PR. Otherwise it will conflict.

I'm putting this one on ice until we have a clear plan.

**Comment by ppalaga** [comment]
Too old to be useful for anything

**Pull request closed without merging**
