### PR TITLE
Revert the WebAuthn extension due to a Vert.x issue

### PR DESCRIPTION
**Pull request by cescoffier**
Due to an integration issue between Vert.x 4.2.6 and Hibernate Reactive (especially when using Oracle), reverts quarkusio/quarkus#24316. 

We hope to be able to get a Vert.x 4.2.7 soon so we can move forward.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by FroMage** [comment]
From my own testing, the 4.2.5.1 oracle driver that we're currently shipping with also fails the Hibernate Reactive tests as much as the 4.2.5 and 4.2.6, so this revert isn't necessary.

**Comment by FroMage** [comment]
Perhaps @DavideD can confirm from his end.

**Comment by DavideD** [comment]
> Perhaps @DavideD can confirm from his end.

Yes.

When I've tried to upgrade to 4.2.5, Hibernate Reactive wasn't even able to connect to Oracle but I've been told that it was a known issue and should have been fixed via 4.2.5.1

With 4.5.1, 4.6 and the snapshot on the repository, Hibernate Reactive connects to Oracle but many tests fail because of something related to the transaction demarcation. It seems to happen when we don't create transaction explicitly.

**Comment by FroMage** [comment]
> should have been fixed via 4.2.5.1

But you didn't test it, or did you? My test says it didn't work:

```diff
diff --git a/hibernate-reactive-core/build.gradle b/hibernate-reactive-core/build.gradle
index 54ce8958..e460519c 100644
--- a/hibernate-reactive-core/build.gradle
+++ b/hibernate-reactive-core/build.gradle
@@ -36,7 +36,7 @@ dependencies {
     testImplementation "io.vertx:vertx-mysql-client:${vertxVersion}"
     testImplementation "io.vertx:vertx-db2-client:${vertxVersion}"
     testImplementation "io.vertx:vertx-mssql-client:${vertxVersion}"
-    testImplementation "io.vertx:vertx-oracle-client:${vertxVersion}"
+    testImplementation "io.vertx:vertx-oracle-client:4.2.5.1"
 
     // Optional dependency of vertx-pg-client, essential when connecting via SASL SCRAM
     testImplementation 'com.ongres.scram:client:2.1'
```

With: `./gradlew clean test -Pdocker -Pdb=oracle -PvertxVersion=4.2.5`

**Comment by DavideD** [comment]
I've tested it and it didn't work (sorry, I wrote the wrong versions in my previous message, now it's fixed).

**Comment by FroMage** [comment]
So this got reverted in 2.8.0.Final, then?

**Comment by cescoffier** [comment]
Not yet... need to see if we can get a fix from vertx soon.

**Comment by FroMage** [comment]
Are you sure? I don't see it in https://repo1.maven.org/maven2/io/quarkus/ but it could be due to the sync issue.

**Comment by cescoffier** [comment]
Yes that's the sync issue...

**Comment by gsmet** [comment]
If it wasn't clear, I haven't backported the Webauthn support to 2.8.0.Final so that's normal the extension is not on Sonatype, that's not a sync issue.

Given the information we have, we should probably close this PR because AFAIK 4.2.6 is not worse than the one before that.

**Comment by cescoffier** [comment]
I still didn't added hibernate reactive to constructor (it's using gradle, so I need to implement something).

**Comment by FroMage** [comment]
Ah

**Comment by FroMage** [comment]
OK, so any chance webauthn will be backported to 2.8 then?

**Comment by cescoffier** [comment]
Closing, we will have a Vert.x 4.2.7 next week.

**Pull request closed without merging**
