### PR TITLE
End Vert.x response before propagating mapped exception in VertxBlockingoutput

### PR DESCRIPTION
**Pull request by pedroigor**
Relates to: https://github.com/quarkusio/quarkus/issues/21841

### CODE REVIEW

**Comment by pedroigor** [comment]
@geoand Took more time than expected because I was trying to figure out how to force the error using tests. I failed, if you think a test is a must, do you have an idea how to force the behavior using a test?

**Review by sberyozkin — APPROVED** [review]
I believe we've had a few of similar fixes which can be hard to reproduce with tests

**Comment by gsmet** [comment]
Let's wait for @stuartwdouglas 's blessing before merging this, please.

**Comment by pedroigor** [comment]
@sberyozkin @geoand To reproduce this one we need to somehow force an error on the write stream so that the exception is set here https://github.com/quarkusio/quarkus/blob/8bea56c861c2cd32554047bcf9078b7f87242a19/extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/VertxBlockingOutput.java#L34.

Then, the `write` method should be called.

We should be able to check whether the Vert.x response by looking if header were written, or if handler registered via `RoutingContext` (e.g.: body, headers end handler, etc) are invoked.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I am ok with skipping a test for this one. We do have a couple of similar tests for the read side such as https://github.com/stuartwdouglas/quarkus/blob/04aa95308cc3296ec89871932cfae101daf9d46a/extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/IncompletePostTestCase.java#L38

Basically if you want to test this you need to manually send a HTTP request over a socket, then close the socket after a delay without reading, and also write a large amount of data in the test. Even then I think it will be hard to get a test that passes reliably though.

**Comment by pedroigor** [comment]
@stuartwdouglas Yeah .. I noticed there are some tests there doing something similar you are suggesting, but I failed to adapt it to my use case :(. But I was not sure what I was doing was the right path, now that you suggested I'll try more.

**Pull request merged**
