### PR TITLE
Avoid Maven imports in core/deployment

### PR DESCRIPTION
**Pull request by gsmet**
The Maven classes won't be available in a Gradle environment. Also install forbiddenapis to make sure they don't come back.

Relates to #28301

### CODE REVIEW

**Comment by Sanne** [comment]
LGTM, but I'll let @aloubyansky review properly.

**Comment by gsmet** [comment]
@Sanne Yeah the bot pinged you because I removed the version in the ORM pom :). Sorry for the noise.

**Comment by Sanne** [comment]
np :) was still interesting to see

**Review by aloubyansky — APPROVED** [review]
Thanks @gsmet

**Pull request merged**
