### PR TITLE
Bump kubernetes-client to 4.5.1

### LINKED ISSUE #3593: hibernate-validator + kubernetes-client native-image is slow and resource intensive
**Describe the bug**
Including the quarkus-hibernate-validator on a fairly dummy project makes the compilation time to last the double or triple, and increase the CPU and Memory usage.

On an idle and relatively powerful workstation (AMD Ryzen 7 2700X, 64GB RAM), the compilation time without quarkus-hibernate-validator in three runs:
01:20 min
01:23 min
01:21 min

Creating a final file size of 39 MB.

After adding the quarkus-hibernate-validator the times go up to:
03:48 min
03:38 min
03:38 min

Creating a final file size of 73 MB. * Just by adding hibernate-validator

**To Reproduce**
1. `./mvnw clean package -Pnative` without quarkus-hibernate-validator
2. ./mvnw quarkus:add-extension -Dextensions="quarkus-hibernate-validator"
3. `./mvnw clean package -Pnative`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux ibz 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK 64-Bit GraalVM CE 19.1.1
 - Quarkus version or git rev: 0.21.1

**Additional context**
The list of extensions (features) used are: cdi, _hibernate-validator_, kubernetes-client, resteasy, resteasy-jackson, smallrye-health

I could provide additional logs if requested.

### PR DESCRIPTION
**Pull request by gastaldi**
Release notes: https://github.com/fabric8io/kubernetes-client/releases/tag/v4.5.0

Fixes: #3593

### CODE REVIEW

**Comment by gastaldi** [comment]
@gsmet @geoand please review

**Comment by geoand** [comment]
I think the same issue with the excessive reflection remains, but I only tested really quickly so I might have got it wrong. I'll need to check again later

**Comment by geoand** [comment]
@gastaldi @iocanel @gsmet there is still an issue with excessive reflection registration. It looks like a lot (almost all maybe?) of the classes of the model have:

```
    @CheckObjectMeta
    private ObjectMeta metadata;
```

which is causing problems. Can this be removed from the model safely?

**Comment by gastaldi** [comment]
I'll have a look. Can you provide a PR in the kubernetes-client if you are faster than me? I'll be happy to merge and cut another release

**Comment by geoand** [comment]
I potentially could, but I am not sure what the implications are of removing this check. @iocanel any ideas would be welcome :)

**Comment by gastaldi** [comment]
It seems to be a Bean Validation 2.0 (JSR 380) annotation, I think it's safe to remove that considering that the Validator is never called (I think, but @iocanel may confirm)

**Comment by geoand** [comment]
Yeah I would hope that is the case

**Comment by gastaldi** [comment]
I created https://github.com/fabric8io/kubernetes-client/pull/1752 removing BV completely from the kubernetes-client project. @geoand could you give it a try and let me know how it behaves?

**Comment by geoand** [comment]
@gastaldi I tested with the kubernetes-client PR and everything looks good. So I am +1 for merging that one and providing a new release.

**Comment by gastaldi** [comment]
Right, while @iocanel works on the BV replacement, I think it would be nice to merge this PR just to incorporate the bug fixes and new features in this version

**Comment by geoand** [comment]
That's fine with me, @gsmet ?

**Comment by gastaldi** [comment]
@geoand updated to 4.5.1

**Comment by geoand** [comment]
Awesome!

**Review by geoand — APPROVED** [review]

**Comment by gastaldi** [comment]
Weird, the CI failed but it is totally unrelated to my commit :thinking:

**Comment by geoand** [comment]
Probably a flake, I restarted it

**Comment by gastaldi** [comment]
Finally, CI is green :fireworks:

**Comment by geoand** [comment]
Thanks for this!

**Pull request merged**
