### PR TITLE
Construct URITemplate with prefixMatch when used for sub-resource locators

### LINKED ISSUE #26028: JAX-RS sub-resource locators with parameter don't always match
### Describe the bug

When using JAX-RS resource locators and sub-resources I don't always get the expected behavior. The paths don't match as expected. If you have a resource locator annotated with `@Path("{id}SomethingElse")` and a nested path in the sub-resource, quarkus will not match the path but rather output a `404`.

I think this is related to [this](https://github.com/quarkusio/quarkus/blob/d5de3c342ddb3b622ec7c63fd1e42fdc985c108f/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java#L172) line in the `URITemplate` class. Or more specifically that the `URITemplate` is mistakenly constructed with `prefixMatch` set to `false`. It should be set to `true` as the path only refers to a resource locator and not an actual method. Sadly I could not inspect further from where the constructor is called.

### Expected behavior

_Referring to code posted below_

If I request `GET /b/TomOther/greet` I expect to get returned `Hello Tom` (same as when calling `GET /a/Tom/greet`)

### Actual behavior

I get `404 - Resource Not Found` status code.

### How to Reproduce?

[Repository](https://github.com/Emmeral/quarkus-subresource-reproducer) or see code below

```java
import javax.ws.rs.Path;
import javax.ws.rs.container.ResourceContext;
import javax.ws.rs.core.Context;

@Path("/")
public class RootResource {

    @Context
    ResourceContext resourceContext;

    @Path("a/{id}")
    public SubResource sub() {
        return resourceContext.getResource(SubResource.class);
    }

    @Path("b/{id}Other")
    public SubResource sub2() {
        return resourceContext.getResource(SubResource.class);
    }
}

```

```java
import io.quarkus.arc.Unremovable;
import javax.enterprise.context.RequestScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;


@Unremovable
@RequestScoped
@Produces("text/plain")
public class SubResource {



    @Path("/greet")
    @GET
    public String greet(@PathParam("id") String id){
        return "Hello " + id;
    }


}

```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Emmeral**
Fixes #26028

### CODE REVIEW

**Comment by geoand** [comment]
Mind adding a test for this?

**Comment by Emmeral** [comment]
> Mind adding a test for this?

I saw that the test package of the project is empty. Is there some other place where the stuff is tested, or are there not that many tests currently?

**Comment by gastaldi** [comment]
Why is this PR targeting the  `2.9` branch and not `main`?

**Comment by geoand** [comment]
Good catch!

**Comment by gsmet** [comment]
I'm closing this one for now: PRs have to target `main` except for very specific cases.
We clearly want this fix in but we need a PR against `main` and ideally a test.
Please open a new PR if you can get to it.

**Comment by Emmeral** [comment]
I just created a new PR to main. See #26224 and added some tests.
I think I branched from 2.9 in the first place, because I used it to test my application which uses 2.9.

**Pull request closed without merging**
