### PR TITLE
Add `format` command to CLI for source formatting

### LINKED ISSUE #30337: Introduce `quarkus format` (or `quarkus fmt`)
### Description

Analogous to `go fmt`, it would be nice if the CLI had a command to automatically format the project sources by running `quarkus fmt`

### Implementation ideas

The command may invoke the [`mvn formatter:format`](https://code.revelc.net/formatter-maven-plugin/format-mojo.html) goal (if configured in the project) otherwise prompt to include it in the project and use the Quarkus IDE Config (`io.quarkus:quarkus-ide-config`) by default

### PR DESCRIPTION
**Pull request by gastaldi**
- Add formatting feature to the Quarkus CLI for sources using the same formatting rules used in the Quarkus Core project
- Fixes #30337

### CODE REVIEW

**Comment by maxandersen** [comment]
This seems like a prime candidate to have as a quarkus-fmt@ plugin similar to quarkus-kill@ ?

**Comment by gastaldi** [comment]
@maxandersen Oh you mean after https://github.com/quarkusio/quarkus/pull/31198 is merged?

**Comment by maxandersen** [comment]
Well you can make it now. Until quarkus has plug-in you run it using jbang fmt@quarkusio

**Comment by gastaldi** [comment]
Added to jbang catalog. Closing this for now

**Comment by geoand** [comment]
Quarkus CLI does have pluggins now, does it not? Should we revive this?

**Comment by gastaldi** [comment]
That would be nice

**Comment by geoand** [comment]
Actually, jbang alias from the Quarkus catalog are already supported as CLI plugins, so there is nothing to be done here.

**Pull request closed without merging**
