### PR TITLE
Detect @Tenant interceptors are required when only JAX-RS classes are annotated, but no resource methods

### PR DESCRIPTION
**Pull request by michalvavrik**
complements: #40843

The `@Tenant` can link resource **classes** or methods with specific tenant: https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/main/java/io/quarkus/it/keycloak/TenantEchoResource.java#L16

### CODE REVIEW

**Comment by sberyozkin** [comment]
@michalvavrik Michal, why don't we want to use these interceptors on methods ? Like
```
class Login {
    @Tenant("google") 
    @GET
    public Response loginWithGoogle() {}

    @Tenant("gitgub") 
    @GET
    public Response loginWithGitgub() {}
}
```

Or did you mean something else ?

**Comment by sberyozkin** [comment]
Is it about `@Inject @Tenant("google") TenanIdentityProvider provider;`  ?

**Comment by michalvavrik** [comment]
Sorry @sberyozkin I wasn't clear. Your example will work as well, we have tests.

I made a mistake in #40843 that I only realized when re-reading it today. On JAX-RS resources, you can place `@Tenant("hr")` like this:


```
@Tenant("github") 
class Login {

    @GET
    public Response loginWithGoogle() {}

    @GET
    public Response loginWithGithub() {}
}
```

that is working, we have tests which https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/main/java/io/quarkus/it/keycloak/TenantEchoResource.java#L16 part of. However when we try to determine whether tenant interceptors should be produced, I tried to exclude `TenantIdentityProvider` and I forgot to check for the Tenant annotation instances on classes. 

Only reason why CI is not failing is that there are other tests using `@Tenant` on methods here: https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/main/java/io/quarkus/it/keycloak/TenantEcho2Resource.java#L26

So this PR is about detecting that `@Tenant` interceptors are required when `@Tenant("github")` is not used on a method level.

I can create a test if you like, but as said, it is not about actual functionality, just about knowing whether functionality is needed. I'll respect your choice.

**Comment by sberyozkin** [comment]
@michalvavrik Got it, thanks

**Review by sberyozkin — APPROVED** [review]

**Pull request merged**
