### PR TITLE
Fix REST Client Reactive path handling for sub-resources

### LINKED ISSUE #25028: Reactive REST client duplicates paths, described by subresources
### Describe the bug

When reactive REST client is used to access sub-resources of some HTTP resource, it duplicates paths which describe these sub-resources. For example, if there is such method in rest client:
```
@Path("/resource")
public interface Client {
 @Path("/sub")
    SubClient getSubResource()
 }
}
```
then call  `client.getSubResource().getSomething()` will lead to HTTP request to `resource/sub/sub/something`.

### Expected behavior

Sub-resources should not lead to duplicated paths.

### Actual behavior

Paths are duplicated

### How to Reproduce?

1. `git clone -b reproducer/duplicate-paths git@github.com:fedinskiy/quarkus-test-suite.git`
2. `cd  http/rest-client-reactive`
3. `mvn clean verify -Dit.test=ReactiveRestClientIT#deepLevel` ( or `ReactiveRestClientIT#subResource`)
4. There is a log which shows, that requests are send to URLs like `http://localhost:1101/books/author/profession/profession/wage/wage/currency/currency/name`

### Output of `uname -a` or `ver`

5.16.13-200.fc35.x86_64

### Output of `java -version`

11.0.12, vendor: GraalVM Community

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
fixes #25028

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
cc @Sgitario

**Comment by michalszynkiewicz** [comment]
This change:
- cleans up the way the targets for subresources are created, 
- fixes generating the `close()` method, 
- fixed selecting converters for parameters, 
- gets rid of unnecessarily generated code in methods that return subresources

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand @michalszynkiewicz it looks like a big change to backport to 2.8 but... given this thing is very broken and I suppose the standard cases are well covered by tests, maybe we should do it?

**Comment by michalszynkiewicz** [comment]
> @geoand @michalszynkiewicz it looks like a big change to backport to 2.8 but... given this thing is very broken and I suppose the standard cases are well covered by tests, maybe we should do it?

Especially that the problem also impacts the keycloak admin client https://github.com/quarkusio/quarkus/issues/24991

**Pull request merged**
