### PR TITLE
RegisterForReflection#classNames does not register full hierarchy of the class

### LINKED ISSUE #21985: RegisterForReflection#classNames does not register full hierarchy of the class
### Description

If we use `io.quarkus.runtime.annotations.RegisterForReflection#classNames` to register classes for reflection it does not register classes up in the hierarchy.

On the other hand, if we use `-H:ReflectionConfigurationFiles`, it does register the full class hierarchy.

### Implementation ideas

I think we should look for the full hierarchy here: https://github.com/quarkusio/quarkus/blob/c82f416fd1ad3ddf8ee40cd40c839e9c884757b3/core/deployment/src/main/java/io/quarkus/deployment/steps/RegisterForReflectionBuildStep.java#L66

And also register super classes.

Are we ok to implement this? I can do it.

### PR DESCRIPTION
**Pull request by igorregis**
fix [#21985](https://github.com/quarkusio/quarkus/issues/21985)
PR originally being discussed [here (RegisterForReflection#classNames does not register full hierarchy of the class)](https://github.com/quarkusio/quarkus/pull/24474), original was mistakenly closed by me.

### CODE REVIEW

**Comment by igorregis** [comment]
Thanks for the orientation @zakkak, the rebase indeed did the trick.

**Comment by geoand** [comment]
Can you please rebase onto `main`?

**Review by zakkak — APPROVED** [review]

**Comment by geoand** [comment]
We'll need another rebase-squash please

**Comment by zakkak** [comment]
@radcortez could you please have a look at this. It looks good to me but I would like a second pair of eyes on it :)

**Comment by radcortez** [comment]
Sure!

**Review by radcortez — APPROVED** [review]

**Pull request merged**
