### PR TITLE
Allow vertx-http to customize body of security errors

### PR DESCRIPTION
**Pull request by looorent**
As explained in #5751 , `io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder` ends the response as soon as a authentication is detected. This prevents us to customize the response's body elsewhere.

The idea of this pull request is to manage this body with a dedicated bean.

### CODE REVIEW

**Comment by gsmet** [comment]
There is a formatting issue. Could you run `mvn process-sources` and amend your commit?

**Comment by looorent** [comment]
I have defined a `DefaultBean` to declare a default implementation (that could be overriden by any project). However, I've never worked on a Quarkus extension so I have no idea whether it is the best way to do it or not. Any clue on this?

```
@Dependent
class AuthenticationErrorResponseConfiguration {

    @Produces
    @DefaultBean
    public AuthenticationErrorResponseHandler createHandler() {
        return new DefaultHandler();
    }
}
```

**Comment by gsmet** [comment]
I rebased this one.

It looks interesting but I think we need proper tests, otherwise we don't know if it works at all.

@stuartwdouglas could you have a look at the general idea?

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
I don't think this is sufficient. It does not address the io.quarkus.vertx.http.runtime.security.HttpAuthenticator#getChallenge use case.

I think that this body data needs to be added to ChallengeData, and then AuthenticationErrorResponseHandler be modified to take the existing challenge data and return a new modified one. I am not sure if this needs the actual exception, as in some cases there isn't one (e.g. io.quarkus.vertx.http.runtime.security.HttpAuthorizer#doDeny).

**Pull request closed without merging**
