### PR TITLE
Set quarkus.datasource.db-kind property in PostgreSql Service Binding

### LINKED ISSUE #14327: quarkus.datasource.db-kind is not set when using PostgreSql ServiceBinding
**Description**
quarkus.datasource.db-kind is not set when using PostgreSql ServiceBinding and so no default DataSource is created,

**Implementation ideas**
Set quarkus.datasource.db-kind

Thanks !

### PR DESCRIPTION
**Pull request by johnpoth**
…rviceBindingConverter

Fixes #14327 

Thanks !

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Good catch!

**Comment by geoand** [comment]
Actually, I remember why this was not done in the first place and why it's wrong.

`quarkus.datasource.db-kind` is a build-time property. So you need to have it set during build, it doesn't have any effect when setting at runtime.

**Comment by gsmet** [comment]
I think the only thing you can do is check the build time value and throw an error if it's not consistent.

**Comment by geoand** [comment]
I don't think that provides much value TBH

**Comment by johnpoth** [comment]
@geoand, thanks!

@gsmet when creating a default datasource, do all database properties need to be set at build-time (password, username, url, db-kind...) or just the db-kind? While testing it seems it's the former

**Comment by geoand** [comment]
I am pretty sure you don't need the runtime properties (like the URL, the username etc.) set, but I could be mistaken

**Comment by johnpoth** [comment]
@geoand gotcha. I see two ways of solving this:

1] Take `quarkus.datasource.db-kind` into account at runtime

2] Read the Service Bindings at build time as well as at runtime 

If you'd like I can do an initial implementation

**Comment by geoand** [comment]
> @geoand gotcha. I see two ways of solving this:
> 
> 1] Take `quarkus.datasource.db-kind` into account at runtime
> 

Unfortunately this is not an option: Quarkus needs to know a lot of stuff at buid time

> 2] Read the Service Bindings at build time as well as at runtime
> 
> If you'd like I can do an initial implementation

But if you do this, properties won't be available at runtime, no?


I might have missed this, but what is the original problem you are trying to solve?

**Comment by johnpoth** [comment]
@geoand I was thinking of [adding](https://github.com/johnpoth/quarkus/commit/c41df8690912e2bbad6647800cba88152fdfe6a9) the kubernetes service binding as a config source at build time too. That way the user only has to use the service binding for a default datasource to be created and doesn't have to add something else to his config or command line. In our case, the user has to set quarkus.datasource.db-kind correctly. I think this would make the user experience better.  Hope this makes sense, let me know what you think thanks !

**Comment by geoand** [comment]
Ah, now I think I understand.

So you basically want the following:

When a user has the `quarkus-kubernetes-service-binding` extension and `quarkus-jdbc-postgresql`, then have `quarkus.datasource.db-kind` set to `postgresql` automatically?

I think that it's a good idea. @gsmet how does that sounds to you?

**Comment by geoand** [comment]
I opened a draft PR showing the approach I mentioned above https://github.com/quarkusio/quarkus/pull/14393.

@gsmet care to comment on that since you are the SME on all things datasource?

**Comment by johnpoth** [comment]
@geoand exactly! Maybe if there are several datasources configured by service bindings then set the datasource name to the servicebinding name or something (but keeping a default datasource in simple use is nice to have IMO). Thanks !

**Comment by geoand** [comment]
Currently we are not implementing multiple database resources - that is a next thing we need to look into

**Pull request closed without merging**
