### PR TITLE
ServerSerialisers static init should change Serialisers primitive lookup strategy

### LINKED ISSUE #37776: Rest client does not support other primitive response types when filter like OIDC client filter is used after optimization of primitive checks
### Describe the bug

https://github.com/quarkusio/quarkus/pull/37655 causes problems when our reactive REST client is also `@OidcClientFilter`  as return type `boolean` is not supported for `text/plain` anymore.

### Expected behavior

`boolean` is valid `text/plain` response type as is when `@OidcClientFilter` is not used

### Actual behavior

An exception is thrown `jakarta.ws.rs.ProcessingException: Response could not be mapped to type boolean for response with media type text/plain;charset=UTF-8`

### How to Reproduce?

1. `git@github.com:quarkus-qe/quarkus-test-suite.git`
2. `cd quarkus-test-suite`
3. `mvn clean verify -f security/keycloak-oidc-client-reactive-extended/ -Dit.test=OidcRestClientIT#testAutoAcquireToken`

### Output of `uname -a` or `ver`

Fedora 38

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by franz1981**
Fixes #37776

### CODE REVIEW

**Comment by franz1981** [comment]
@geoand this is weird: this is really the expected behaviour?

eg 
1. `ClientSerialisers` is used and no primitive wrappers lookup happen
2. `ServerSerialisers` is now used as well 
3. both `ServerSerialisers` and `ClientSerialisers` start to lookup primitive types

Maybe this is just a non possible situation, and everything always happen in a single thread, and in a given order.
In  that case I can remove the `volatile` keyword or we can move this "setup" in who will make these classes to be loaded
and can "configure" them in order that when `ServerSerialisers` is configured, all the serializers behave the same.

**Comment by geoand** [comment]
I haven't debugged yet, but my guess is that ClientSerializers are now wrong, as opposed to the case before the change

**Comment by franz1981** [comment]
@geoand 

> as opposed to the case before the change

I've restored the "original" behaviour (before https://github.com/quarkusio/quarkus/pull/37655) with this one 
ie  static init of `SerialSerialisers` influence the behaviour of all `Serialisers`'s son.

If the original behaviour need to be changed for the case of https://github.com/quarkusio/quarkus/pull/37778#issuecomment-1858058743 let me know and i'll put it in draft, awaiting a different fix on monday - I don't think we're in hurry (it's nearly weekend :P)

**Comment by geoand** [comment]
To be honest, we always need the primitive lookup

**Comment by geoand** [comment]
@franz1981 thanks for this, but I actually prefer #37788 since its is more correct and also contains a test.

**Pull request closed without merging**
