### PR TITLE
Build PDF when running the documentation job for PRs

### LINKED ISSUE #10702: Improve the doc-related PR builds
I've broken a `documentation` build with this PR, https://github.com/quarkusio/quarkus/pull/10653#issuecomment-657671432, but the PR build did not detect it, both the PR build and myself were doing only `doc` builds :-).

Proposal: have both `doc` and `documentation` built

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #10702

### CODE REVIEW

**Comment by loicmathieu** [comment]
@gastaldi @sberyozkin I don't think this will be enought.

I think about it this night and if I undertand it correctly the issue is with a duplicated title: one inside the guide and the other inside the configuration reference fragment.

@gastaldi you successfuly trigger the issue because you tested your PR with a non clean master where the configuration fragment was built right ? I'm pretty sure if you retry with a clean master (mvn clean on the Quarkus top folder) the issue will not be triggered.

The doc CI build only build the doc, to covers this kind of issue we will need to build the config reference fragements this means building all extensions + quarkus-core. This will make the CI build a lot longuer so better check with @gsmet first about this ...

**Comment by gsmet** [comment]
If we can get a minimal build that also builds the config doc, that would be nice. I'm just not sure if it will fit the definition of `minimal` though.

**Comment by loicmathieu** [comment]
@gsmet the minimal build would be `mvn clean compile` on both `quarkus-core` and the `quarkus-extension-parent` as the configuration reference fragments are built via an annotation processor so a compile goal should be enought.

But this would lead to an increase of the build form 30s to a few minutes (5 or more, test should be done).

**Comment by sberyozkin** [comment]
Hi George, @gastaldi, thanks for picking it up, i did not mean to avoid fixing the issue :-) was just focusing on the smallrye-jwt quickstart yesterday. But my PR would've been the same :-), given Loic's hint earlier. 
I'm not sure it is a big problem if the build time increases, a single job should do, and it is better to prevent the doc build failures, even though they are admittedly quite rare...

**Review by sberyozkin — APPROVED** [review]
Let me approve.

**Comment by gastaldi** [comment]
> @gastaldi you successfuly trigger the issue because you tested your PR with a non clean master where the configuration fragment was built right ? I'm pretty sure if you retry with a clean master (mvn clean on the Quarkus top folder) the issue will not be triggered.

Yes, you're right. Perhaps we could build it with `-Dquickly` first and then run the doc generation mojo?

**Comment by gastaldi** [comment]
> Hi George, @gastaldi, thanks for picking it up, i did not mean to avoid fixing the issue :-) was just focusing on the smallrye-jwt quickstart yesterday. But my PR would've been the same :-), given Loic's hint earlier.

@sberyozkin no worries, I just wanted to work on something quick and saw that low hanging fruit :)

**Comment by loicmathieu** [comment]
> Yes, you're right. Perhaps we could build it with -Dquickly first and then run the doc generation mojo?

With `-Dquickly` you will still build a lot of not needed projects.

I will manually build core and extensions with the `compile` target prior to builds the doc. This should be the minimal steps needed to have the configuration reference generated.

**Comment by sberyozkin** [comment]
@gastaldi hey, 
> I just wanted to work on something quick and saw that low hanging fruit

ROFL, this issue may end up to be the hardest issue we've had to deal with recently :-)

**Comment by gastaldi** [comment]
@loicmathieu simply building `core` and `extensions` isn't enough, since they depend on other projects, like the BOM, build-parent and independent-projects for example. I still think it's safe to go with `-Dquickly` for now since it seems to build all the necessary projects and skips the docs on purpose.

**Comment by loicmathieu** [comment]
@gastaldi OK, in this case you will need to install everything ... At least you can excluse the integration test from the list of projects. I think that `-Dquickly` still build them.

**Comment by gastaldi** [comment]
Yeah, but I think that runs so fast that it wouldn't hurt in this case and it would make the cmd more complicated :slightly_smiling_face:

**Comment by gastaldi** [comment]
I created https://github.com/quarkusio/quarkus/pull/10752 that would skip the integration tests too with `-Dquickly`

**Review by loicmathieu — APPROVED** [review]
LGTM please provides timing to know how much CI minutes it will use.

Previously, it runs in less than 30s, I expect it to run between 5 to 10mn now ...

**Comment by gastaldi** [comment]
In my laptop `mvn -Dquickly` runs in 4:07. With https://github.com/quarkusio/quarkus/pull/10752 it boils down to 02:56

**Comment by loicmathieu** [comment]
Maybe you can just avoid to build the integration test inside the doc PR for now waiting for feedback to inlcude it or not for `-Dquickly`.

Using `-pl !integration-tests` or someting like this should do the trick and we can merged this PR and revisit it later if needed.

**Comment by gastaldi** [comment]
I can't get it to work with `mvn -Dquickly -pl "!integration-tests"`. My bash insists on replacing it with `integration-tests/jpa-mariadbtests`

**Comment by loicmathieu** [comment]
@gastaldi you can use single quote instead of double quotes

**Comment by gastaldi** [comment]
`mvn -Dquickly -pl '!integration-tests'` still builds the integration-tests module. Maybe the `-pl` argument does not support that?

**Comment by loicmathieu** [comment]
@gastaldi ah yes, it didn't work for parent modules, all modules needs to be listed one by one so it's not really usable here ...

**Comment by rquinio** [comment]
@gastaldi To exclude sub-modules recursively, you'd have to use a profile: `mvn -Dquickly -P '!integration-tests'`

```xml
<profile>
  <id>integration-tests</id>
  <activation>
    <activeByDefault>true</activeByDefault>
  </activation>
  <modules>
    <module>integration-tests</module>
  </modules>
</profile>
```

Since integration-tests were already executing last, it shouldn't have any side effect on build reactor order.

**Comment by famod** [comment]
Btw, `-f` is faster than `-pl` because the latter will parse all submodules while `-f` won't.

**Pull request merged**
