### PR TITLE
Introduce retry into Mongo DNS resolution

### PR DESCRIPTION
**Pull request by geoand**
- Relates to: https://github.com/quarkusio/quarkus/discussions/31971
- Relates to: https://github.com/quarkusio/quarkus/issues/37618

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
It looks good, we may want to make the timeout uses the existing property and the number of retry configurable.

**Comment by geoand** [comment]
> It looks good, we may want to make the timeout uses the existing property and the number of retry configurable.

Right, this could be a good next step

**Comment by csotiriou** [comment]
This seems promising, @geoand any chance this can be backported into 3.8.x current LTS?

**Comment by geoand** [comment]
Yeah, if there is a new 3.8 LTS release, we can backport

**Pull request merged**
