### PR TITLE
Improve continuous testing status message

### PR DESCRIPTION
**Pull request by stuartwdouglas**
The message is now the same for passed/failed (but
a different color). It show total passed/failed, and
the results of the last run.

### CODE REVIEW

**Comment by ia3andy** [comment]
@stuartwdouglas could you have a look at my latest proposition in https://github.com/quarkusio/quarkus/issues/17161

What I do like about that approach is that we have a consistent text between the different modes ("normal" and "broken only"). In "0/4 passed" the "4" stays the same across runs and modes since it is the quantity of tests which should pass (now or already). I also like that you can easily find what is what by summing it making it intuitive.

**Comment by ia3andy** [comment]
I added a commit with:
- Failed status message: `9 tests failed (56 passing, 2 skipped), 14 tests were run in 400ms`
- Passed status message: `all 14 tests passed (2 skipped), 14 tests were run in 400ms`
- Also add a report result when it passed
- Add run # number to the report separator
- Use ">>>>> ... <<<<<" as report conclusion/end
- Use green/red for status

this is what it looks like:

Starting with 5 tests failing:
image

Then fixing a few tests:
image


Then activate broken only mode (we can see that the passing count is not going down):
image

Greennnn Yeaahh they all are passing :)
image


I find it really cool now!

The only thing I am not sure is when the `skipped > 0` should we say "passed" or "failed", also why don't we call it "aborted" which may be more intuitive?

**Comment by ia3andy** [comment]
I fixed a few spaces problems in another commit and improved the passed report:
image

**Comment by ia3andy** [comment]
I would be nice to have this in the next Alpha

**Review by ebullient — APPROVED** [review]

**Comment by ia3andy** [comment]
@stuartwdouglas After looking at the junit spec, I don't understand why we use `skipped` instead if `aborted`? https://junit.org/junit5/docs/5.0.1/api/org/junit/platform/engine/TestExecutionResult.Status.html
```java
else if (i.getTestExecutionResult().getStatus() == TestExecutionResult.Status.ABORTED) {
                    skipped.add(i);
```

For the general status, it seems to be:
- no aborted/failed = passed
- at least one aborted = aborted
- at least one failed and no aborted = failed

It could be done in another PR..

**Pull request merged**
