### PR TITLE
Update gradle wrapper version used in codestart

### PR DESCRIPTION
**Pull request by glefloch**
This update the version of gradle wrapper used in generated gradle projects.

### CODE REVIEW

**Review by ia3andy — COMMENTED** [review]
LGTM

**Review by ia3andy — APPROVED** [review]

**Comment by ia3andy** [comment]
@glefloch  is the maven wrapper version ok? https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/maven-wrapper/codestart.yml#L10-L11

**Comment by glefloch** [comment]
hmm it looks like ` 0.5.6` is not the latest version but I don't know how safely we can update. Maybe @famod knows more ?

**Comment by famod** [comment]
@glefloch AFAICS, 0.5.6 **is** the latest mvn wrapper version.
Where have you seen a newer one?

**Comment by glefloch** [comment]
@famod you are right, my bad, I was not looking at the right place...

**Comment by famod** [comment]
@glefloch hakuna matata! 😁

**Pull request merged**
