### PR TITLE
Upgrade Jakarta EL impl to 3.0.4

### LINKED ISSUE #20274: Bump `org.glassfish:jakarta.el` due to vulnerability
### Description

https://app.snyk.io/vuln/SNYK-JAVA-ORGGLASSFISH-1297098

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #20274

It fixes a CVE so probably something to consider for 2.2.

### CODE REVIEW

**Comment by famod** [comment]
Should we add it to dependabot?

**Review by sberyozkin — APPROVED** [review]

**Comment by gsmet** [comment]
We could but we will need to ignore all the new major versions.

**Comment by sberyozkin** [comment]
@gsmet OK, let me update the dependabot rule

**Comment by sberyozkin** [comment]
Hmm, is it `dependency-name: org.glassfish:jakarta-el:3.*.*` or 
```
ignore:
      - dependency-name: "jakarta-el"
        update-types: ["version-update:semver-major"]
```
?

**Comment by sberyozkin** [comment]
Hey @geoand can you check my last comment please ?

**Comment by geoand** [comment]
Oh sorry, I missed that!

**Comment by sberyozkin** [comment]
@geoand np :-), I'll add the ignore section, 1 sec

**Comment by sberyozkin** [comment]
@geoand done :-), if that does not work then we'll make sure the major version is not merged in any case, Guillaume, we won't let 4.x.x in :-)

**Comment by gsmet** [comment]
When Dependabot pushes the update, you can add a comment with something like "ignore this major version" (not exactly sure it's the right wording but the help is available in the Dependabot PR).

**Comment by sberyozkin** [comment]
Sound good

**Comment by sberyozkin** [comment]
There was a single JVM JDK 11 failure,

```
2021-09-28T19:45:27.0795401Z [INFO] Running io.quarkus.it.amqp.AmqpConnectorTest
2021-09-28T19:45:32.2405183Z ##[error]The operation was canceled.
2021-09-28T19:45:32.2991572Z ##[group]Run actions/upload-artifact@v2....
```

Which is not related, I could not see anything else, so let me merge

**Pull request merged**
