### PR TITLE
Implement new-connection-sql configuration for Agroal

### PR DESCRIPTION
**Pull request by Sanne**
Rebased version of #4117 - credit to @chaminnk

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
CI failure is unrelated.

**Comment by gsmet** [comment]
Merged, thanks @chaminnk and @Sanne !

**Comment by chaminnk** [comment]
You are welcome @gsmet . Thanks for merging the feature :)

**Comment by chaminnk** [comment]
Thanks for the rebase @Sanne :)

**Pull request merged**
