### PR TITLE
Improve context propagation performance for JTA

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@loicmathieu can you test this out and see if it makes a difference for your use case? It should remove a lot of the CDI overhead.

**Comment by loicmathieu** [comment]
@stuartwdouglas this improves performance a little.
CPU profile: 6.8% => 5.2% of frames

For allocation profiling, I see an improvements but the numbers are not concistent from run to run so it's difficult to provides a comparison.

So, it improve a bit, but the cost (and specially allocation cost due to captured context state object creation) is still high.

**Comment by FroMage** [comment]
I can't review this unless I understand what it does differently :-/

Also, if this is just about perf, why not take this change upstream?

**Comment by stuartwdouglas** [comment]
I have created an upstream version, although it is a bit more complex: https://github.com/smallrye/smallrye-context-propagation/pull/165

**Comment by stuartwdouglas** [comment]
Basically the main change is that we don't look up the TM bean on every invocation.

**Comment by FroMage** [comment]
OK, merged. Do you want this PR to go through or shall I do a release and we upgrade our dep to SR-CP?

**Comment by stuartwdouglas** [comment]
I will close this one, and wait for a release.

**Comment by FroMage** [comment]
OK, deploying now.

**Comment by FroMage** [comment]
Released at https://repo1.maven.org/maven2/io/smallrye/smallrye-context-propagation/1.0.13/

**Pull request closed without merging**
