### PR TITLE
Add logging-manager extension

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR adds a new logging-manager extension (from Quarkiverse) that allows a full screen (and if configured available in non-dev mode, and native)

This reuse the code and static content from the Dev UI. If the developer adds this extension, there will be a new icon in Dev UI that takes you to the extension endpoint.

logger-manager

This is the first of 2 PR's to pull the quarkiverse logger-manager in, the second PR will contain the remaining features (OpenAPI etc)

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by FroMage** [comment]
Sorry I don't have time to review, but I'm +1 on this extension :)

I could rubber-stamp this if no-one else can review.

**Comment by phillip-kruger** [comment]
Thanks @FroMage :)

**Comment by gsmet** [comment]
I don't know.

For me, the bar to accept a new extension in core is now very high. What is the reason why it can't live in the Quarkiverse?

**Comment by phillip-kruger** [comment]
I guess it can, it was initially discussed when part of this was brought over to Dev UI, so this was always part of the work I was doing on that, I just broke it up into multiple PRs.

**Comment by gsmet** [comment]
Frankly, I don't really know. If there's no strong reason to have it in Core, I'm not sure we should include it.

But probably better discuss it on the quarkus-dev list.

**Comment by phillip-kruger** [comment]
If we do decide to keep it in quarkiverse, I would still need some changes to the Dev UI (the ones in this PR) to allow for the reuse of static resources. 
Another option would to built everything into Vertx http (where Dev UI is at the moment) but I am not sure about that...

**Comment by phillip-kruger** [comment]
Closing this in favor of a smaller (upcoming)  PR that only contains changes to allow the current Quarkiverse to reuse the static content.

**Pull request closed without merging**
