### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by rsvoboda**
We have Quarkus 0.15.0 out so we can have some dependency updates ;)

### CODE REVIEW

**Comment by gsmet** [comment]
The build fails with:
```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-infinispan-client ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v /home/vsts/work/1/s/integration-tests/infinispan-client/target:/project:z --rm --user 1001:117 quay.io/quarkus/centos-quarkus-native-image:graalvm-1.0.0-rc16 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.noUnsafe=true -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-infinispan-client-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -J-Xmx6g -H:-AddAllCharsets -H:EnableURLProtocols=http --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[quarkus-integration-test-infinispan-client-999-SNAPSHOT-runner:6]    classlist:  14,310.44 ms
[quarkus-integration-test-infinispan-client-999-SNAPSHOT-runner:6]        setup:     460.51 ms
Error: Already registered: io.netty.util.internal.CleanerJava6.CLEANER_FIELD_OFFSET
com.oracle.svm.core.util.UserError$UserException: Already registered: io.netty.util.internal.CleanerJava6.CLEANER_FIELD_OFFSET
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:86)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:710)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:405)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:304)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:865)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:820)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:522)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:442)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by rsvoboda** [comment]
Ah, did just full jvm run locally :)

We will probably need to drop netty related substitutions as they are in component now.
Commit https://github.com/netty/netty/commit/f1495e19459eb4e961b1c078e7692680f88a0803

**Comment by gsmet** [comment]
IIRC Netty updates need to be coordinated as it’s a very sensitive component. /cc @cescoffier

**Comment by rsvoboda** [comment]
Oki, I will revert netty update.

**Comment by rsvoboda** [comment]
@gsmet checks are green now.

Should I create issue for netty upgrade and assign it to Clement ?

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@rsvoboda I don't know about Netty. I think it's really something that should be managed upstream.

**Pull request merged**
