### PR TITLE
Vertx - make it possible to set cache dir for native image

### LINKED ISSUE #2898: Setting of system property  java.io.tmpdir having no effect on VertxTemplate in native mode
**Describe the bug**
Setting of system property `java.io.tmpdir` in native mode has no effect for vert.x quickstart. This is part of the discussion [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Native.20builds.3A.20JVM.20options.20at.20runtime/near/168516155). 

**Expected behavior**
Setting the `java.io.tmpdir` system property should work correctly since the `VertxTemplate` is a RuntTime init template

**Actual behavior**
The system property is ignored

**To Reproduce**
1. Use the vertx quickstart :https://github.com/quarkusio/quarkus-quickstarts/tree/master/using-vertx
2. Create a native binary
3. Attempt to set the system property by doing something like: `target/using-vertx-1.0-SNAPSHOT-runner -Djava.io.tmpdir=/dummy`. This should fail normally since the directory does not exist (and it of course does fail when running `java -Djava.io.tmpdir=/dummy -jar target/using-vertx-1.0-SNAPSHOT-runner.jar`).

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #2898

### CODE REVIEW

**Comment by geoand** [comment]
I don't know enough about Vert.x to actually review the change, but I did test the PR and I can verify that it fixes the issue

**Comment by mkouba** [comment]
@geoand thanks for verification! ;-)

**Comment by geoand** [comment]
Thanks for fixing the issue :)

**Comment by mkouba** [comment]
@cescoffier Pls review.

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
