### PR TITLE
build(BOM): Upgrade Swagger UI to  3.24.3

### PR DESCRIPTION
**Pull request by aoudiamoncef**

### CODE REVIEW

**Comment by machi1990** [comment]
Hi @aoudiamoncef thanks for the PR. CI failure looks related. Can you check?

**Comment by aoudiamoncef** [comment]
Hi @machi1990,
There is an issue with the latest version, it wasn't pushed to Maven central, i don't why !
[swagger-ui maven](https://mvnrepository.com/artifact/org.webjars/swagger-ui)

I'll be safer to upgrade to Swagger UI 3.23.11.

**Comment by gsmet** [comment]
Could you please test it and check it works OK? Because I don't see how you could have tested it without it being available on Central.

We need to be thorough when upgrading a HTML/JS thing.

Thanks!

**Comment by aoudiamoncef** [comment]
Hi @gsmet ,
For 3.24.2, i hadn't got an error, because in y local repository, i don't know why, i still got 3.20.9.

For 3.23.11, i delete all swagger dependencies in my local repository, i launched a hole project rebuild and i launched tests on Swagger UI extension: 
```
99-SNAPSHOT/quarkus-swagger-ui-deployment-999-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus - Swagger UI 999-SNAPSHOT:
[INFO] 
[INFO] Quarkus - Swagger UI ............................... SUCCESS [  1.016 s]
[INFO] Quarkus - Swagger UI - Runtime ..................... SUCCESS [  2.060 s]
[INFO] Quarkus - Swagger UI - Deployment .................. SUCCESS [  5.020 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.395 s
[INFO] Finished at: 2019-11-16T10:32:56+01:00
[INFO] ------------------------------------------------------------------------
```

If you have another check that i could make in my dev environment. Don't hesitate.

Thanks

**Comment by gsmet** [comment]
I think it's worth really testing it works on a simple project with openapi. It should just be a matter of creating a new project with the openapi extension included.

**Comment by aoudiamoncef** [comment]
They seems to have some [issues](https://github.com/swagger-api/swagger-ui/releases) with **Swagger UI 3.24.0** which are fixed in next releases that aren't available on Maven central.

**Comment by aoudiamoncef** [comment]
I tested with [openapi-swaggerui-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/openapi-swaggerui-quickstart) and all seems to be ok.

swagger-ui

**Review by gsmet — CHANGES_REQUESTED** [review]
@aoudiamoncef I just pinged James, the maintainer, and he told me he just released 3.24.3 to Maven Central: https://repo1.maven.org/maven2/org/webjars/swagger-ui/3.24.3/ ?

Would you be up for adjusting your PR with this one and test it? Thanks!

**Comment by gsmet** [comment]
Upstream repository is here: https://github.com/webjars/swagger-ui .

**Comment by aoudiamoncef** [comment]
@gsmet, i did all the requested checks, all is green with the latest version.

**Comment by gsmet** [comment]
Perfect, thanks!

**Review by gsmet — APPROVED** [review]

**Comment by machi1990** [comment]
CI green. Merging, thanks @gsmet @aoudiamoncef

**Pull request merged**
