### PR TITLE
removing reference to the authorization part

### PR DESCRIPTION
**Pull request by sebastienblanc**

### CODE REVIEW

**Comment by sebastienblanc** [comment]
@pedroigor make sense to remove it from here, doesn't it ?

**Comment by pedroigor** [comment]
@sebastienblanc yes, it does. This part is now covered in `quarkus-keycloak-authorization` extension.

**Comment by sberyozkin** [comment]
I see, thanks

**Review by sberyozkin — APPROVED** [review]

**Comment by gsmet** [comment]
I suppose this needs to be merged. I'll do it.

**Pull request merged**
