### PR TITLE
Upgrade Hibernate ORM to 6.2.5.Final and Reactive to 2.0.1.Final

### LINKED ISSUE #33779: Quarkus 3/Hibernate 6 - Exception when access ElementCollection from an Entity with an embedded composite Key with associated Object
### Describe the bug

I have an Entity with an EmbeddedId and an ElementCollection: 
```
@Entity()
public class MyEntity {
    @EmbeddedId
    EmbeddableId id;

    public String name;

    @ElementCollection
    public Set<EmbeddableElement> elementCollection = new HashSet<>();
}
```
```
@Embeddable
public class EmbeddableElement {
    public String name;
}
```

The embedded id has an composite key
```
@Embeddable
public class EmbeddableId  {
    public String id1;
    @ManyToOne
    public PartOfIdEntity id2;
}
```
```
@Entity()
public class PartOfIdEntity  {
    @Id
    public Long id;
}
```

### Expected behavior

No Exception when accessing the ElementCollection like in Quarkus 2.*

### Actual behavior

I get an Exception

Now if i access the elementCollection of MyEntity i get following exception: 
```
java.lang.NullPointerException: Cannot invoke "org.hibernate.sql.results.graph.entity.EntityInitializer.getNavigablePath()" because "firstEntityInitializer" is null
        at org.hibernate.sql.results.graph.entity.internal.BatchEntityInsideEmbeddableSelectFetchInitializer.getRootEmbeddablePropertyName(BatchEntityInsideEmbeddableSelectFetchInitializer.java:190)
        at org.hibernate.sql.results.graph.entity.internal.BatchEntityInsideEmbeddableSelectFetchInitializer.<init>(BatchEntityInsideEmbeddableSelectFetchInitializer.java:57)
        at org.hibernate.sql.results.graph.entity.internal.EntitySelectFetchInitializerBuilder.createInitializer(EntitySelectFetchInitializerBuilder.java:58)
        at org.hibernate.sql.results.graph.entity.internal.EntityFetchSelectImpl.buildEntitySelectFetchInitializer(EntityFetchSelectImpl.java:92)
        at org.hibernate.sql.results.graph.entity.internal.EntityFetchSelectImpl.lambda$createAssembler$0(EntityFetchSelectImpl.java:70)
        at org.hibernate.sql.results.internal.ResultsHelper$1.resolveInitializer(ResultsHelper.java:108)
        at org.hibernate.sql.results.graph.entity.internal.EntityFetchSelectImpl.createAssembler(EntityFetchSelectImpl.java:67)
        at org.hibernate.sql.results.graph.embeddable.AbstractEmbeddableInitializer.initializeAssemblers(AbstractEmbeddableInitializer.java:121)
        at org.hibernate.sql.results.graph.embeddable.AbstractEmbeddableInitializer.<init>(AbstractEmbeddableInitializer.java:107)
        at org.hibernate.sql.results.graph.embeddable.internal.EmbeddableResultInitializer.<init>(EmbeddableResultInitializer.java:22)
        at org.hibernate.sql.results.graph.embeddable.internal.EmbeddableForeignKeyResultImpl.lambda$createResultAssembler$0(EmbeddableForeignKeyResultImpl.java:101)
        at org.hibernate.sql.results.internal.ResultsHelper$1.resolveInitializer(ResultsHelper.java:108)
        at org.hibernate.sql.results.graph.embeddable.internal.EmbeddableForeignKeyResultImpl.createResultAssembler(EmbeddableForeignKeyResultImpl.java:98)
        at org.hibernate.sql.results.graph.collection.internal.CollectionDomainResult.lambda$createResultAssembler$0(CollectionDomainResult.java:98)
        at org.hibernate.sql.results.internal.ResultsHelper$1.resolveInitializer(ResultsHelper.java:108)
        at org.hibernate.sql.results.graph.collection.internal.CollectionDomainResult.createResultAssembler(CollectionDomainResult.java:94)
        at org.hibernate.sql.results.jdbc.internal.StandardJdbcValuesMapping.resolveAssemblers(StandardJdbcValuesMapping.java:53)
        at org.hibernate.sql.results.internal.ResultsHelper.createRowReader(ResultsHelper.java:78)
        at org.hibernate.sql.results.internal.ResultsHelper.createRowReader(ResultsHelper.java:64)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:341)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
        at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:144)
        at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:104)
        at org.hibernate.loader.ast.internal.CollectionLoaderBatchKey.load(CollectionLoaderBatchKey.java:116)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:668)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1697)
        at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$initialize$3(AbstractPersistentCollection.java:617)
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
        at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615)
        at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136)
        at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$readSize$0(AbstractPersistentCollection.java:163)
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
        at org.hibernate.collection.spi.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:148)
        at org.hibernate.collection.spi.PersistentSet.size(PersistentSet.java:151)
        at example.MyEntityTest.test(MyEntityTest.java:47)

```

### How to Reproduce?

1. Persist some data 
```
PartOfIdEntity partOfIdEntity = new PartOfIdEntity();
            partOfIdEntity.id = 1L;
            entityManager.persist(partOfIdEntity);

            MyEntity myEntity = new MyEntity();
            myEntity.id = new EmbeddableId();
            myEntity.id.id1 = "123";
            myEntity.id.id2 = partOfIdEntity;

            EmbeddableElement el = new EmbeddableElement();
            el.name = "abc";
            myEntity.elementCollection.add(el);
            entityManager.persist(myEntity);
```
2. Close the transaction
3. Access the data:
```
 MyEntity entityFromSelect = em.createQuery("SELECT e FROM MyEntity e", MyEntity.class).getSingleResult();
        entityFromSelect.elementCollection.size();

        // Cannot invoke "org.hibernate.sql.results.graph.entity.EntityInitializer.getNavigablePath()" because "firstEntityInitializer" is null:
        assertEquals(1, entityFromSelect.elementCollection.size());
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

First i assumed it was a hibernate issue, but i can´t reproduce it with pure hibernate:
[hibernate-orm-6.zip](https://github.com/quarkusio/quarkus/files/11632131/hibernate-orm-6.zip)

Only with Quarkus 3.*
[quarkus-hibernate-issue.zip](https://github.com/quarkusio/quarkus/files/11632133/quarkus-hibernate-issue.zip)

### PR DESCRIPTION
**Pull request by DavideD**
* Hibernate ORM to 6.2.5.Final
* Hibernate Reactive to 2.0.1.Final

### CODE REVIEW

**Comment by gsmet** [comment]
Unfortunately, this doesn't look good. My testing didn't go this far unfortunately. We really need to figure out a way to test these snapshots fully on CI.

/cc @dreab8 @Sanne

**Comment by gsmet** [comment]
Kafka error:

```
Caused by: java.lang.ClassCastException: Object of type 'class io.quarkus.smallrye.reactivemessaging.kafka.CheckpointEntityId' can't be cast to CompositeTracker
	at org.hibernate.engine.internal.ManagedTypeHelper.asCompositeTracker(ManagedTypeHelper.java:337)
	at io.quarkus.it.kafka.people.PeopleState.$$_hibernate_write_id(PeopleState.java)
	at io.quarkus.smallrye.reactivemessaging.kafka.CheckpointEntity.setId(CheckpointEntity.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
	... 25 more
```

Spring Data JPA error:

```
	Caused by: java.lang.NoSuchMethodError: 'io.quarkus.it.spring.data.jpa.PhoneCallId io.quarkus.it.spring.data.jpa.AbstractPhoneEntity.$$_hibernate_read_id()'
		at io.quarkus.it.spring.data.jpa.PhoneCall.$$_hibernate_write_id(PhoneCall.java)
		at io.quarkus.it.spring.data.jpa.AbstractTypedIdEntity.<init>(AbstractTypedIdEntity.java:16)
		at io.quarkus.it.spring.data.jpa.AbstractPhoneEntity.<init>(AbstractPhoneEntity.java:10)
		at io.quarkus.it.spring.data.jpa.PhoneCall.<init>(PhoneCall.java:17)
		... 83 more
	Suppressed: org.jboss.resteasy.spi.UnhandledException: org.hibernate.InstantiationException: Could not instantiate entity : io.quarkus.it.spring.data.jpa.PhoneCall
		at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:107)
		at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:344)
		at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:205)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
		at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
		at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
		at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
		at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
		at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
		at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
		at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
```

/cc @yrodiere too

**Comment by Sanne** [comment]
Thanks for highlighting the errors!

Both errors look like related to a failure of entity enhancement.

**Comment by yrodiere** [comment]
> Both errors look like related to a failure of entity enhancement.

Agreed. The first one looks like a regression in ORM, the second one might be a combination of a change in ORM and a bug introduced by [my earlier PR](https://github.com/quarkusio/quarkus/pull/32876).

I can't look into this right now, but I'll try to investigate next week.

**Comment by DavideD** [comment]
Oops.... I've deleted this branch by mistake.

Here's a new PR rebased to the latest changes: https://github.com/quarkusio/quarkus/pull/34124

**Pull request closed without merging**
