### PR TITLE
Funqy knative events update

### PR DESCRIPTION
**Pull request by sshaaf**
Guide update for  #14454 - Quarkus Funqy Knative Events guide
PR quarkus-quickstarts is also made for this: [PR](https://github.com/quarkusio/quarkus-quickstarts/pull/758)

### CODE REVIEW

**Comment by matejvasek** [comment]
@sshaaf question not related directly to content of this PR:
Is `http://default-broker.knativetutorial.svc.cluster.local` still valid broker address in knative-eveting?
Seems to me that with newer knative-eventing it should be `http://broker-ingress.knative-eventing.svc.cluster.local/knativetutorial/default`

**Comment by cardil** [comment]
You should always use `status.address.url`. From Knative Eventing 0.15+ the default implementation is [MT broker](https://github.com/knative/docs/tree/release-0.20/docs/eventing/broker#configuring-broker-classes), that lives in single pod. Previously there were brokers pods for each broker.

Using `io.fabric8:knative-client:5.0.1` API:

```java
KnativeClient kn = new DefaultKnativeClient();
kn.brokers()
  .inNamespace("namespace")
  .withName("brokername")
  .get()
  .getStatus()
  .getAddress()
  .getUrl();
```

**Comment by sshaaf** [comment]
> @sshaaf question not related directly to content of this PR:
> Is `http://default-broker.knativetutorial.svc.cluster.local` still valid broker address in knative-eveting?
> Seems to me that with newer knative-eventing it should be `http://broker-ingress.knative-eventing.svc.cluster.local/knativetutorial/default`

Yes, it seems its different, we use the following command you mentioned to get the address. Not sure if we need to mention the change? 

> 
> Not much important since `kubectl get broker default -o jsonpath='{.status.address.url}'` will get them correct url anyway.

**Comment by matejvasek** [comment]
I would just chage
```
This will provide you a url like this (exactly like this if you followed the knative tutorial): http://default-broker.knativetutorial.svc.cluster.local Remember this URL.
```
to
```
This will provide you a URL similar to this: http://broker-ingress.knative-eventing.svc.cluster.local/knativetutorial/default. Remember this URL.
```
Because `exactly like this if you followed the knative tutorial` this is no longer true and it might be confusing.

**Comment by sshaaf** [comment]
> Because `exactly like this if you followed the knative tutorial` this is no longer true and it might be confusing.

Agreed. changed it to 
```
This will provide you a URL similar to e.g.: `http://broker-ingress.knative-eventing.svc.cluster.local/knativetutorial/default`. Remember this URL.
```

**Comment by sshaaf** [comment]
@matejvasek 
The quickstarts PR is already reviewed(but not merged). I also need the review on this one i.e. guide. 
Thanks.

**Review by matejvasek — APPROVED** [review]

**Comment by matejvasek** [comment]
@patriot1burke PTAL

**Review by gsmet — APPROVED** [review]
I made a couple of additional changes. Let's get this merged once it's green.

**Comment by gsmet** [comment]
Thanks @sshaaf

**Comment by sshaaf** [comment]
> Thanks @sshaaf

Thanks @gsmet , FYI this PR on quickstarts is related: https://github.com/quarkusio/quarkus-quickstarts/pull/758
otherwise the guide wont match.

**Pull request merged**
