### PR TITLE
gRPC - gather call statistics

### LINKED ISSUE #24: Load Balancing for gRPC
## Built-in gRPC load balancing
In gRPC, load balancing is a bit different than elsewhere. 

### grpclb
With external load balancer, `grpclb`, the load balancer provides a **list** of server addresses and a connection is established with each of the addresses in the list.
Then, e.g. round-robin is used to distribute calls among the connections.

### round-robin, pick-first
A list of servers (either from Service Discovery or staticly provided?), connections with all of them are established upfront, then the selected strategy is used to "load-balance" the traffic.

## SmallRye Stork vs gRPC
The current model of Stork is to provide either a list of server addresses or a single address, selected by the load balancing strategy.

There are a few ways we could adapt it to gRPC:
- (1) set up connections for all the addresses in the list, use the one selected by the load balancer
   - this seems to be the closest to what is done in gRPC
   - it might need a hook for server addresses refresh. Or the gRPC internals could invoke the Stork `ServiceDiscovery` periodically
- (2) enhance `LoadBalancer` to add an option to select a few best server addresses

ATM, I think (1) is the best option, and seems to be the closest to what we have.
Specifically, we should provide a `NameResolverProvider` backed by Stork `ServiceDiscovery` and `LoadBalancer` with `Picker` based on the Stork `LoadBalancer`

### LINKED ISSUE #23578: Quarkus doesn't create a dedicated StorkInfrastructure
### Describe the bug

Quarkus doesn't create a dedicated StorkInfrastructure

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
This change also introduces a dedicated StorkInfrastructure, to reuse the Vertx instance from Quarkus

fixes #23578
fixes https://github.com/smallrye/smallrye-stork/issues/24

### CODE REVIEW

**Review by mkouba — COMMENTED** [review]
Looks good but I have a minimal knowledge of stork sooo ;-)

**Comment by michalszynkiewicz** [comment]
> Looks good but I have a minimal knowledge of stork sooo ;-)

but you have knowledge of grpc :) thanks for reviewing!

**Comment by michalszynkiewicz** [comment]
the test failure doesn't seem related

**Review by cescoffier — APPROVED** [review]
Do not forget to add a section in the migration guide.

**Comment by michalszynkiewicz** [comment]
> Do not forget to add a section in the migration guide.
hmm... the changes should be transparent for the users, no?

**Comment by cescoffier** [comment]
Yes, in theory. At some point we will need to describe the behavior changes: concurrent calls of the load balancer, how stats are collected...

**Pull request merged**
