### PR TITLE
Upgrade to Maven Compiler Plugin 3.12.1

### PR DESCRIPTION
**Pull request by gsmet**
Unfortunately, we can't integrate it for now as we are hit by https://issues.apache.org/jira/browse/MCOMPILER-567.

### CODE REVIEW

**Comment by jorsol** [comment]
A patch release (3.12.1) might be available in the coming weeks.

**Comment by gsmet** [comment]
@jorsol yeah, I saw you were working hard on that, thanks!

**Comment by jorsol** [comment]
@gsmet m-compiler-p 3.12.1 is now available!

**Comment by gsmet** [comment]
Adjusted to target `3.12.1`.

**Comment by gsmet** [comment]
@jorsol thanks! I just got back from PTO and updated the PR.

**Comment by famod** [comment]
FYI, this depMgmt version lookup does not seem to support relocations: https://github.com/apache/maven-compiler-plugin/pull/180#issuecomment-1876921475

**Review by geoand — APPROVED** [review]

**Pull request merged**
