### PR TITLE
-H:+AddAllCharsets passed to native-image even though no extension requested it

### LINKED ISSUE #6683: -H:+AddAllCharsets passed to native-image even though no extension requested it
-H:+AddAllCharsets passed to native-image even though neither any extension nor user config requests it.

Thanks @lburgazzoli for spotting the symptoms. 

Steps to reproduce: run any itest where `-H:+AddAllCharsets` is not expected in the native mode. quarkus-integration-test-jackson is a good example.

Expected: Either `AddAllCharsets` does not occur at all or `-H:-AddAllCharsets` occurs in the output.

Actual: `-H:+AddAllCharsets` occurs in the output

## Explanation

The implementation of `DeprecatedBuildItemProcessor.enableAllCharsets(List<NativeEnableAllCharsetsBuildItem>)` is broken:

```
    @BuildStep
    NativeImageEnableAllCharsetsBuildItem enableAllCharsets(List<NativeEnableAllCharsetsBuildItem> oldProps) {
        return new NativeImageEnableAllCharsetsBuildItem();
    }
```

It returns a NativeImageEnableAllCharsetsBuildItem regardless if there are any oldProps.

A PR follows

### PR DESCRIPTION
**Pull request by ppalaga**
…tension requested it

### CODE REVIEW

**Comment by geoand** [comment]
@machi1990 was this just an oversight when the implementation was done?

**Review by gsmet — APPROVED** [review]
Good catch.

**Comment by gsmet** [comment]
@geoand it's when the "deprecation handling" layer was added that we got it wrong.

**Comment by geoand** [comment]
@gsmet Sure, I'm just trying to establish if it was just a simple oversight or if there was perhaps some reason behind this.
I am pretty sure it's the former, I just wanted to be on the safe side

**Comment by gsmet** [comment]
Yeah, it's an oversight, there's no good reason to do it that way. But bonus point for checking :).

**Comment by machi1990** [comment]
> @machi1990 was this just an oversight when the implementation was done?

Yeap, an oversight from me! Good catch @ppalaga thanks!

**Pull request merged**
