### PR TITLE
Fix issue with config beans in dev mode

### PR DESCRIPTION
**Pull request by stuartwdouglas**
The config beans are generated into a different CL
to RuntimeConfig, and so did not have access to it.

This also provides a nice bump to dev mode hot reload speed, around 50ms on my machine.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@dmlloyd is there any need to regenerate RuntimeConfig in dev mode? If there is I can fix this a different way but we would loose the performance improvement

**Comment by dmlloyd** [comment]
I wouldn't think so, unless you've added dependencies (if that's allowed in dev mode).

**Comment by gsmet** [comment]
@dmlloyd I let you review that one.

**Comment by stuartwdouglas** [comment]
This still has a problem, I need to investigate further

**Comment by stuartwdouglas** [comment]
Should be good to go now assuming CI passes.

Extensions that inject config are now completly broken in dev mode, so it would be good to get this in ASAP

**Comment by gsmet** [comment]
@loicmathieu could you test your project with this PR?

**Comment by loicmathieu** [comment]
@gsmet this will fix #8908

**Review by gsmet — APPROVED** [review]

**Pull request merged**
