### PR TITLE
Add guidance for creating a Quarkus doc abstract

### PR DESCRIPTION
**Pull request by michelle-purcell**
As a contributor to the Quarkus community project, I'd like to know how to write a good extract that helps Quarkus readers to find, skim and understand our content and uses best practices for search engine optimization.

### CODE REVIEW

**Comment by michelle-purcell** [comment]
@MichalMaler - I started the guideance for 'Abstracts' that clarifies the importance of the first sentence and how it gets used to dynamically populate the summary blurb on the Quarkusio home page.
Please can you review and add more guidance about abstracts if you think it's needed? Thanks :-)

**Review by ebullient — APPROVED** [review]

**Comment by ebullient** [comment]
I'm ok to merge this..

**Comment by MichalMaler** [comment]
> As a contributor to the Quarkus community project, I'd like to know how to write a good extract that helps Quarkus readers to find, skim and understand our content and uses best practices for search engine optimization.

Hello @michelle-purcell , adding my feedback here :)
https://github.com/quarkusio/quarkus/pull/27302

**Comment by michelle-purcell** [comment]
@inoxx03 FYI

**Pull request merged**
