### PR TITLE
Fix rest client invalid config message

### LINKED ISSUE #21708: quarkus.rest-config instead of quarkus.rest-client
### Describe the bug

When using REST Client, when you forget to configure the uri of an external microservice, Quarkus displays an error message as follow:

```
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. 
Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding

'quarkus.rest-config."org.agoncal.fascicle.quarkus.book.client.NumberProxy".url' or 
'quarkus.rest-config."org.agoncal.fascicle.quarkus.book.client.NumberProxy".uri' to your Quarkus configuration
```

There is no such `quarkus.rest-config` property, but instead, `quarkus.rest-client`

### Expected behavior

The message should display the right properties

```
...
'quarkus.rest-client."org.agoncal.fascicle.quarkus.book.client.NumberProxy".url' or 
'quarkus.rest-client."org.agoncal.fascicle.quarkus.book.client.NumberProxy".uri' to your Quarkus configuration
```

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #21708

### CODE REVIEW

**Comment by gsmet** [comment]
Is it really the right fix? What is `rest-config`?

**Comment by geoand** [comment]
> Is it really the right fix? What is `rest-config`?

`rest-config` was a mistake

**Comment by geoand** [comment]
Ah sorry, I just saw that I got it reversed... Let me close

**Comment by geoand** [comment]
Superceded by https://github.com/quarkusio/quarkus/pull/21728

**Pull request closed without merging**
