### PR TITLE
Add support for HTTP/2

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by gastaldi** [comment]
LGTM but CI is reporting an error: 

```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.505 s <<< FAILURE! - in io.quarkus.vertx.http.http2.Http2Test
[ERROR] testHttp2EnabledSsl  Time elapsed: 0.223 s  <<< ERROR!
org.opentest4j.TestAbortedException: Assumption failed: assumption is not true
	at org.junit.jupiter.api.Assumptions.throwTestAbortedException(Assumptions.java:256)
	at org.junit.jupiter.api.Assumptions.assumeTrue(Assumptions.java:115)
	at org.junit.jupiter.api.Assumptions.assumeTrue(Assumptions.java:66)
	at io.quarkus.vertx.http.http2.Http2Test.testHttp2EnabledSsl(Http2Test.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.test.QuarkusUnitTest.runExtensionMethod(QuarkusUnitTest.java:285)
	at io.quarkus.test.QuarkusUnitTest.interceptTestMethod(QuarkusUnitTest.java:253)
```

**Comment by gastaldi** [comment]
AFAIK Assumptions should not be considered errors right? They should just prevent the test from being executed in the environment?

**Comment by stuartwdouglas** [comment]
I fixed the assumptions issue, I also opened a seperate PR for the fix as it will likely want to be backported.

**Review by gastaldi — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/7796 should probably be merged first to make backporting easier.

**Comment by gastaldi** [comment]
Since it's the same commit SHA, Github will automatically close #7796 when this PR is merged.

**Comment by machi1990** [comment]
This is really good!

**Pull request merged**
