### PR TITLE
update postgres to newer version to fix fail to start on M2 laptops

### LINKED ISSUE #44150: postgres:14 as quarkus devservice fails to run on M2 macbook
### Describe the bug

not sure when it started but recently postgres:14 stopped working for me.

error showing it is not multiarch:
`The architecture 'amd64' for image 'docker.io/postgres:14' (ID sha256:d4a3e64ed8edfd59f3b853e3fe43e3d549b69f3a08e78841b268cdcf4998313d) does not match the Docker server architecture 'arm64'. This will cause the container to execute much more slowly due to emulation and may lead to timeout failures.`

and then the logs showing it simply fails to start:

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/14/bin/pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2024-10-29 05:36:05.193 UTC [118] LOG:  starting PostgreSQL 14.13 (Debian 14.13-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-10-29 05:36:05.195 UTC [118] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-10-29 05:36:05.214 UTC [122] LOG:  database system was shut down at 2024-10-29 05:36:04 UTC
 stopped waiting
pg_ctl: could not start server
Examine the log output.
```

using `postgres` only works - which (I assume) means `postgres:17` would be a better choice.

Not sure if there is a reason we are on a old version (postgres:14 is from 2021).

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by maxandersen**
fixes #44150

anyone know if reason to stay on older postgres or this should be fine?

### CODE REVIEW

**Comment by gastaldi** [comment]
@melloware This also partially fixes https://github.com/quarkusio/quarkus/issues/42149

**Comment by yrodiere** [comment]
> @melloware This also partially fixes #42149

Yeah, pretty sure the upgrade was blocked because Flyway didn't work after the upgrade.

**Comment by maxandersen** [comment]
And flyway failing was more than need to use flyway-database-postgresql when using Postgres ?

**Comment by melloware** [comment]
Yes it looks like an issue where Flyway needed to change some code to be PG 16 compliant.

**Comment by maxandersen** [comment]
but thats what i'm saying - you need to add a specific postgress flyway dependency to make it work. 

@FroMage mentioned he had some fun with flyway on getting it to use right postgres combination. @FroMage can you remember?

**Comment by gastaldi** [comment]
I've run `mvn -Dquarkus.datasource.devservices.image-name=postgres quarkus:dev` with https://github.com/quarkusio/registry.quarkus.io

And got the following warning, but the app started ok:

```
2024-10-29 09:26:33,119 WARN  [org.fly.cor.int.dat.bas.Database] (Quarkus Main Thread) Flyway upgrade recommended: PostgreSQL 17.0 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
```

**Comment by yrodiere** [comment]
> but thats what i'm saying - you need to add a specific postgress flyway dependency to make it work.

That additional dependency is already added automatically: https://github.com/quarkusio/quarkus/pull/41862

We might need to update it, though, if the compatibility problem with Postgres 16 was fixed upstream.

Anyway, tests are already failing in this PR, maybe let's wait for the report and the exact failure before we discuss solutions?

**Comment by yrodiere** [comment]
The failure looks related to usage of public schema in tests (see below). Since it's mentioned in https://github.com/quarkusio/quarkus/pull/41862, I assume the public schema can no longer be used by default in Postgres 16.

```
2024-10-29T09:32:39.1749951Z [ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 7, Time elapsed: 10.76 s <<< FAILURE! -- in io.quarkus.it.flyway.FlywayFunctionalityTest
2024-10-29T09:32:39.1754211Z [ERROR] io.quarkus.it.flyway.FlywayFunctionalityTest.testPlaceholders -- Time elapsed: 0.007 s <<< ERROR!
2024-10-29T09:32:39.1756068Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2024-10-29T09:32:39.1757884Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:632)
2024-10-29T09:32:39.1759922Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:716)
2024-10-29T09:32:39.1761612Z 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2024-10-29T09:32:39.1762918Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-10-29T09:32:39.1764131Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-10-29T09:32:39.1765336Z Caused by: java.lang.RuntimeException: Failed to start quarkus
2024-10-29T09:32:39.1766773Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2024-10-29T09:32:39.1767936Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2024-10-29T09:32:39.1769104Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-10-29T09:32:39.1770518Z 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
2024-10-29T09:32:39.1772149Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:245)
2024-10-29T09:32:39.1773986Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:599)
2024-10-29T09:32:39.1775967Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:649)
2024-10-29T09:32:39.1777382Z 	... 1 more
2024-10-29T09:32:39.1778518Z Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Script  failed
2024-10-29T09:32:39.1779737Z --------------
2024-10-29T09:32:39.1780116Z SQL State  : 42501
2024-10-29T09:32:39.1781268Z Error Code : 0
2024-10-29T09:32:39.1781851Z Message    : ERROR: permission denied for schema public
2024-10-29T09:32:39.1782507Z Location   :  ()
2024-10-29T09:32:39.1782888Z Line       : 1
2024-10-29T09:32:39.1783877Z Statement  : CREATE OR REPLACE FUNCTION f_my_constant() RETURNS integer LANGUAGE plpgsql as $func$ BEGIN return 100; END $func$
2024-10-29T09:32:39.1784815Z 
2024-10-29T09:32:39.1785645Z 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:256)
2024-10-29T09:32:39.1787638Z 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:217)
2024-10-29T09:32:39.1789401Z 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:137)
2024-10-29T09:32:39.1790768Z 	at org.flywaydb.core.FlywayExecutor.lambda$execute$1(FlywayExecutor.java:159)
2024-10-29T09:32:39.1792114Z 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.openConnection(JdbcConnectionFactory.java:106)
2024-10-29T09:32:39.1793478Z 	at org.flywaydb.core.internal.database.base.Database.<init>(Database.java:89)
2024-10-29T09:32:39.1794691Z 	at org.flywaydb.database.postgresql.PostgreSQLDatabase.<init>(PostgreSQLDatabase.java:38)
2024-10-29T09:32:39.1796173Z 	at org.flywaydb.database.postgresql.PostgreSQLDatabaseType.createDatabase(PostgreSQLDatabaseType.java:96)
2024-10-29T09:32:39.1797478Z 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:164)
2024-10-29T09:32:39.1798337Z 	at org.flywaydb.core.Flyway.migrate(Flyway.java:176)
2024-10-29T09:32:39.1799309Z 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:142)
2024-10-29T09:32:39.1800591Z 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
2024-10-29T09:32:39.1802045Z 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
2024-10-29T09:32:39.1802945Z 	... 8 more
2024-10-29T09:32:39.1803657Z Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for schema public
2024-10-29T09:32:39.1804985Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
2024-10-29T09:32:39.1806347Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
2024-10-29T09:32:39.1807585Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
2024-10-29T09:32:39.1808705Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
2024-10-29T09:32:39.1809717Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434)
2024-10-29T09:32:39.1810712Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:356)
2024-10-29T09:32:39.1811797Z 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:341)
2024-10-29T09:32:39.1812870Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:317)
2024-10-29T09:32:39.1813869Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:312)
2024-10-29T09:32:39.1815141Z 	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:210)
2024-10-29T09:32:39.1816956Z 	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:88)
2024-10-29T09:32:39.1818801Z 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:212)
2024-10-29T09:32:39.1820020Z 	... 19 more
2024-10-29T09:32:39.1820234Z 
```

**Comment by FroMage** [comment]
> mentioned he had some fun with flyway on getting it to use right postgres combination

It was a red herring. Flyway was reporting something like "Version X of Postgres not supported" when the version was irrelevant: it was the general postgres support module that was missing, but I'm pretty sure some brave colleague fixed that.

**Comment by gsmet** [comment]
I will close this one and create a more comprehensive PR with some Flyway tests adjustments and maybe also some other image updates.

**Comment by gsmet** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/44191 .

**Pull request closed without merging**
