### PR TITLE
ProtoStream update, solves #5554

### PR DESCRIPTION
**Pull request by rsvoboda**
ProtoStream update, solves #5554

### CODE REVIEW

**Comment by rsvoboda** [comment]
fyi JDK 14-ea / 15-ea still need to be tackled - https://issues.redhat.com/browse/IPROTO-126

**Review by gastaldi — APPROVED** [review]
LGTM, want to also add it to the dependabot descriptor?

**Comment by rsvoboda** [comment]
@wburns how do you feel about adding ProtoStream to dependabot ?

**Comment by wburns** [comment]
> @wburns how do you feel about adding ProtoStream to dependabot ?

Well normally we just keep it in sync with Infinispan. Unfortunately I have been a bit busy to update Infinispan in Quarkus, I hope to be able to get back sometime soon though :)

**Pull request merged**
