### PR TITLE
Improve OpenApi CORS message

### LINKED ISSUE #28377: Log on startup with "Default CORS properties will be used, please use 'quarkus.http.cors' properties instead" without more information
### Describe the bug

If I start a Quarkus application in production mode, with the smallrye-openapi extension enabled, I get this message on startup:

```
2022-10-04 13:50:54,394 INFO  [io.qua.sma.ope.run.OpenApiRecorder] (main) Default CORS properties will be used, please use 'quarkus.http.cors' properties instead
```

I find this confusing, as the message is not telling me what I did wrong (maybe forgot to set some properties, which ones?) nor exactly what is needed to solve it (which properties should I set, simply `quarkus.http.cors=true`? something more complex?). For the record, my `application.properties` is completely empty.

### Expected behavior

Maybe the message should expand a bit on what's wrong and what should be done to solve the problem?

If there *is* no problem (as the "INFO" level seems to suggest), maybe it should be rephrased from "please use [...]" to "if you want X, do Y"?

### Actual behavior

```
2022-10-04 13:50:54,394 INFO  [io.qua.sma.ope.run.OpenApiRecorder] (main) Default CORS properties will be used, please use 'quarkus.http.cors' properties instead
```

### How to Reproduce?

```
quarkus create --extension resteasy,hibernate-orm-panache,jdbc-postgresql,smallrye-openapi
cd code-with-quarkus
./mvnw clean package
java -jar ./target/quarkus-app/quarkus-run.jar
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The log was apparently introduced in this commit by @sberyozkin: https://github.com/quarkusio/quarkus/commit/597440d6edbeee8850de0d6f34477dd606724287

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #28377.

Improving the message as proposed by Yoann but without a specific doc link.

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]
LGTM if we do need this log.

Still wondering if this shouldn't be moved to the vertx extension, though, since this is really not specific to openapi. But that's probably a separate issue.

Let's wait for @gsmet 's opinion though, as I'm sure he has one :)

**Comment by sberyozkin** [comment]
@yrodiere 

>Still wondering if this shouldn't be moved to the vertx extension, though, since this is really not specific to openapi.

This is specific to `smallrye-open-api` since it is only `smallrye-open-api` which enables wildcard CORS properties by default

**Comment by yrodiere** [comment]
> This is specific to `smallrye-open-api` since it is only `smallrye-open-api` which enables wildcard CORS properties by default

Ok, I thought those wildcard CORS properties were equivalent to simply no CORS properties, but apparently that's not true. So I assume those wildcard CORS properties are useful somehow.

I assume those wildcard properties are also useful in development mode, probably because development setups would fail without those.

In production though... I'm sorry if I'm being thickheaded, but I keep thinking there's something strange here... To sum up, we have a default that is insecure in some cases (which we cannot detect), and presumably useful in others (which we cannot detect either). And, whatever the case, we would rather have users pick their configuration explicitly.

If we have an insecure default that we don't want people to rely on anyway, maybe we should reconsider that default, at least in the next minor or major, to be secure by default?

The only "secure" option I'm seeing is simply not setting any CORS headers at all when they are not enabled explicitly (**in production**). From what I understand that will cause [errors in the browser](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin), but at least those errors mention the need to enable CORS in the REST API, and from there users can go configure their application correctly.

Maybe that's already planned? I couldn't find a GitHub issue about that, though.

**Comment by sberyozkin** [comment]
Hey @yrodiere 

Np, thanks for trying to make sure all is clear. So this log message will only be shown in the production mode. Wildcard CORS properties are really never useful in the production mode - but we just all tend do it to get past the annoying CORS errors which might show up, it is just convenient, but Quarkus can't offer this convenience by default without saying anything as eventually someone will report CVE. 
IMHO the best thing should've been to remove these wildcard properties set by default, but I can imagine then we will annoy many users again. So this log message is some kind of compromise, we don't break the backward compatibility, but also make an effort to warn gently via the INFO that it is not a good idea, and to address a specific Snyk report problem along the way.
I don't mind though removing the default OpenApi properties altogether - if it is not in the product then I guess we can do it now

**Comment by sberyozkin** [comment]
>I don't mind though removing the default OpenApi properties altogether - if it is not in the product then I guess we can do it now

It is in the product as this is why I've found about it via a product Snyk scan so we can't really remove these default properties easily. But deprecating them in a message would be even more annoying to the users who just would like to try it locally. So not sure what else we can do but make this message more informative as you have proposed

**Comment by yrodiere** [comment]
> Wildcard CORS properties are really never useful in the production mode - but we just all tend do it to get past the annoying CORS errors which might show up, it is just convenient

Thanks for clarifying, I was suspecting as much but wasn't sure, given that's not really my area of expertise :)

> but Quarkus can't offer this convenience by default without saying anything

Sure, it's still a good idea to keep and improve the message in the meantime.

> we can't really remove these default properties easily

Right, if it's really too disruptive, regardless of products, maybe that's not something we want to do in a minor. Perhaps we could plan this change for the next major of Quarkus? No idea when/if that will happen of course, but in a major version it's more reasonable to introduce disruptive changes, especially if they make Quarkus more secure by default.

I created #28397, let's continue the discussion there :)

@gsmet Summary of the discussion so you don't have to read it all:

* There's an INFO log on startup when using smallrye-openapi and that's annoying.
* We cannot remove that log because of security scanners (we've used this log to justify an exception).
* This PR at least makes the log extra-clear.
* We opened #28397 to suggest another solution, but that'll have to wait until we can break backwards compatibility.

**Comment by sberyozkin** [comment]
@yrodiere Sure, but re #28397, we have this extension in the product, that is the problem...

**Comment by sberyozkin** [comment]
@gsmet I'm going to merge shortly as @yrodiere has approved, to get it to 2.13.x if possible, and for 2.14.0.CR I'll try resolve #28397

**Comment by yrodiere** [comment]
@sberyozkin Fine by me, thanks!

**Pull request merged**
