### PR TITLE
Only enable Hibernate Validator built-in constraints that are used

### PR DESCRIPTION
**Pull request by gsmet**
@loicmathieu can you try this PR in conjunction with this HV PR: https://github.com/hibernate/hibernate-validator/pull/1080 ?

Just deploy HV with a `mvn clean install -DskipTests -DskipITs` then build Quarkus with `mvn clean install -DskipTests -DskipITs` and bump your project to `999-SNAPSHOT`.

It should hopefully improve the situation for #8586 .

### CODE REVIEW

**Comment by loicmathieu** [comment]
@gsmet I check and it clearly shows a performance improvement and less allocation in dev mode (I would said from 50ms to 10ms in average for the `build()` method, more if we take into account the startup improvement of the validator factory).
Advantage in production mode is less visible.

While you're at performance improvements, the `isResteasyInClasspath()` method could be improve to not initialize the class ... or to use the `Capabilities.RESTEASY`  instead of loading a random resteasy class ...

**Review by loicmathieu — APPROVED** [review]
LGTM, performance test shows a nice startup improvements for Hibernate Validator

**Comment by loicmathieu** [comment]
Fixes #8586

**Comment by gsmet** [comment]
@loicmathieu I pushed another round of small improvements. Could you have a look? Both in the Hibernate Validator PR and the Quarkus PR so both need to be rebuilt.

Thanks!

**Comment by gsmet** [comment]
I'm done with this btw, except if you have other complaints coming :).

**Review by yrodiere — APPROVED** [review]
@gsmet Looks good to me.

**Comment by loicmathieu** [comment]
@gsmet it's difficult to give numbers for the new improvements but checking the memory and CPU profiles I can see a clear improvements for Hibernate validator bootstrap in both dev and production mode.
So it's a nice performance improvement! Great job!

**Comment by geoand** [comment]
Since everyone in the know seems to agree this is great, should we get it in?

**Comment by yrodiere** [comment]
> Since everyone in the know seems to agree this is great, should we get it in?

@geoand This PR relies on a SNAPSHOT version of Validator. We have to wait for Validator to be released.

**Comment by geoand** [comment]
Yes yes, I am aware of that. My message was meant to get that ball rolling as well :)

**Comment by gsmet** [comment]
I'm working on it. Have a few other small things to fix before releasing a new version.

**Comment by gsmet** [comment]
6.1.4.Final is released but I need to wait for the sync from JBoss Nexus to Maven Central so I will finalize this during the week-end.

**Comment by gsmet** [comment]
This is now ready to go.

**Review by machi1990 — APPROVED** [review]

**Pull request merged**
