### PR TITLE
Configuration classes are application classes.

### LINKED ISSUE #2138: Build time config options are not reloaded in dev mode
If you have a build time config option (e.g. quarkus.datasource.driver) and you update it in dev mode you will see the updated value in the processor but the value in the template is the old value.

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #2138, #2117

### CODE REVIEW

**Comment by dmlloyd** [comment]
@stuartwdouglas and @gsmet, if you have an easy way to check if this resolves #2138 and/or #2117, that would be really helpful.

**Comment by gsmet** [comment]
@dmlloyd I confirm it fixes #2117 .

**Comment by LightGuard** [comment]
Confirmed to fix #2117 as well.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
This looks good but I need to check it fixes #2138 too. I'll merge as soon as I'm able to verify it.

**Comment by gsmet** [comment]
I confirm it fixes both issues, merging, thanks!

**Pull request merged**
