### PR TITLE
Fix OpenTelemetry substitution

### LINKED ISSUE #25143: App with quarkus-opentelemetry-exporter-jaeger fails to compile into native
### Describe the bug

App with quarkus-opentelemetry-exporter-jaeger fails to compile into native

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 22.0.0.2 Java 17 CE (Java Version 17.0.2+8-jvmci-22.0-b05)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Users/rsvoboda/.sdkman/candidates/java/22.0.0.2.r17-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Duser.country=GB -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-UseServiceLoaderFeature -H:+StackTrace code-with-quarkus-1.0.0-SNAPSHOT-runner -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner'...
========================================================================================================================
[1/7] Initializing...
                                                                                    (3.2s @ 0.21GB)
Error: Could not find target method: public static void io.quarkus.opentelemetry.exporter.jaeger.runtime.JaegerSubstitutions$Target_ManagedChannelUtil.setTrustedCertificatesPem(io.grpc.ManagedChannelBuilder,byte[]) throws javax.net.ssl.SSLException
com.oracle.svm.core.util.UserError$UserException: Could not find target method: public static void io.quarkus.opentelemetry.exporter.jaeger.runtime.JaegerSubstitutions$Target_ManagedChannelUtil.setTrustedCertificatesPem(io.grpc.ManagedChannelBuilder,byte[]) throws javax.net.ssl.SSLException
	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:751)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:368)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:340)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:889)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:816)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:534)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:494)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:426)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
------------------------------------------------------------------------------------------------------------------------
                         0.1s (5.4% of total time) in 8 GCs | Peak RSS: 0.67GB | CPU load: 6.74
------------------------------------------------------------------------------------------------------------------------
```

https://github.com/quarkusio/quarkus/blob/main/extensions/opentelemetry/opentelemetry-exporter-jaeger/runtime/src/main/java/io/quarkus/opentelemetry/exporter/jaeger/runtime/JaegerSubstitutions.java

CC @radcortez 

### Expected behavior

Application compiles

### Actual behavior

Application does not compile

### How to Reproduce?

 - Generate app https://code.quarkus.io/
 - add `io.quarkus:quarkus-opentelemetry-exporter-jaeger`
 - run `mvn clean verify -Dnative`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

GraalVM 22.0 Java17

### Quarkus version or git rev

Quarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #25143

### CODE REVIEW

**Comment by gsmet** [comment]
Any chance we could test this somehow? Not necessarily the whole thing but at least that this thing compiles?

**Comment by geoand** [comment]
We could add the extension to one of the integration tests. @radcortez anything more we can do?

**Comment by radcortez** [comment]
> We could add the extension to one of the integration tests. @radcortez anything more we can do?

We can also add some integrations tests, set up Jaeger, and check if the Telemetry data is getting correctly populated. It is going to require some effort. Not sure if it will be worth it since the plan is to move the Jaeger extension to Quarkiverse and deprecate it at some point. The recommended way to push Telemetry data is to use the OTel Exporter (which can push data to Jaeger on its own, so we don't need a dedicated extension for Jaeger).

**Comment by geoand** [comment]
So do you propose we just leave it as is for now?

**Comment by radcortez** [comment]
> So do you propose we just leave it as is for now?

Yes. We can just add an integration-test to make sure that the compile works.

**Comment by geoand** [comment]
Done

**Review by rsvoboda — APPROVED** [review]
App with quarkus-opentelemetry-exporter-jaeger builds now

**Comment by geoand** [comment]
Thanks for checking!

**Pull request merged**
