### PR TITLE
Dev UI: Auto naming for JsonRPC and build time data

### LINKED ISSUE #31786: Dev UI: `doNotEmbed` is opening a blank page instead of new window tab
### Describe the bug

When using `doNotEmbed()` option on the page builder it should open the URL in a new browser tab.

```java
  PageBuilder versionPage = Page.externalPageBuilder("Version")
                .url("https://poi.apache.org/")
                .doNotEmbed();
```

### Expected behavior

Open in new browser tab.

### Actual behavior

Opening a blank page in the DEV UI.

### How to Reproduce?

Just add a simple card like above and click the link.

cc @phillip-kruger

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR is a "breaking  change" for the new Dev UI. 
Names used to import build time data and identify JsonRPC messages that had to be passed in by the extension, both on the server side and when using it in the client. This name used was the Extension name as defined in the extension yaml.

This PR changes:

- The name used is now a combination of the groupId and artifactId.
- We detect this name automatically on the client and server.
- This means that the url for extension pages also changes
- The folder where static content live in an extension now needs to be the root of `dev-ui` (not `dev-ui/extensionName`)
- When importing build time data, you now `import {mydata} from 'build-time-data'` (not `from 'extensionName-data'`) 

This PR also
- Fix #31786
- Reload on hot reload (i.e when the server does not restart but a hot reload happened)
- Cosmetic changes to the Config screen

I will update the videos with the changes and new feature after this is merged.
There will also be follow up PR for some extensions to fix what this PR breaks.

The updated config screen with hotreload working in the log and name (see name in the title)
Peek 2023-03-24 19-02

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Awesome changes!

**Review by cescoffier — COMMENTED** [review]
Can we do something to avoid the js files being in a super complex subdirectory?

**Comment by phillip-kruger** [comment]
> Can we do something to avoid the js files being in a super complex subdirectory?

Yes this is on my todo list. but, the same reasoning for uniqueness applies to both the directory and the build-time data import. ... so it might have to stay like this

**Comment by phillip-kruger** [comment]
@cescoffier I managed to get around the ugly folder name in dev-ui.  Looking at the data import now.

**Comment by phillip-kruger** [comment]
@cescoffier - now folder is removed and build time data is not using name or namespace, but `build-time-data`. Much better.

**Comment by melloware** [comment]
It looks like there are two copies of the caffeine-card one that was moved and one that was left in place?

**Review by melloware — CHANGES_REQUESTED** [review]
See comment

**Comment by phillip-kruger** [comment]
@melloware Thanks ! Good catch. Fixed. Please check

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Looks good!

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
