### PR TITLE
Upgrade Oracle JDBC driver to 23.2.0.0

### PR DESCRIPTION
**Pull request by Sanne**
Targeting Quarkus 3.1

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]

**Comment by gsmet** [comment]
There is a problem in native AFAICS.

**Comment by Sanne** [comment]
that's unfortunate, this test is working fine for me locally - and I have no idea what it does. I'll see if I can figure it out but it seems unreliable

**Comment by Sanne** [comment]
Ok great it's failing now locally too - gives me a chance to dig

**Comment by gsmet** [comment]
I pushed a commit to your branch. Probably a good idea to keep it anyway for future failures.

**Comment by Sanne** [comment]
Thanks! +1 these "legacy" designed integration tests are a pain

**Comment by Sanne** [comment]
@gsmet should work now - although now I'm puzzled about why it didn't fail consistently.

Essentially it was failing to fail correctly - the JNDI initialization expects specific error codes to happen, but it was throwing a different error because the resource bundle which includes the error codes wasn't included in native image.

I had compared the native-image metadata from the previous versions and had been reassured to see only one difference, which is the one change that we had suggested. Unfortunately they seem to have made some code changes without updating the metadata... added additional corrections in our override layer.

**Comment by Sanne** [comment]
I can't reproduce this either, and it should be easier since it failed in JVM mode :-/

Launched it a dozen times locally, it never failed.  @michalvavrik , would you have any suggestions?

I'll try to have it repeated on CI.

**Comment by michalvavrik** [comment]
looks like you fixed it :-)

**Comment by Sanne** [comment]
hi @michalvavrik , no I didn't - I only had CI try once again as I was wondering if it was consistently reproducible on CI, and it seems it isn't. I can't reproduce it locally either.

It doesn't make me comfortable to push this, knowing that this test might be flaky, would be nice if you could check if it works for you locally?

**Comment by michalvavrik** [comment]
@Sanne 
ad - `io.quarkus.it.opentelemetry.OracleOpenTelemetryJdbcInstrumentationTest.testOracleQueryTraced` I think I made essential mistake when designing this condition . Sometimes it takes longer for spans to arrive (that's expected, we have timeouts in all OT tests), but I just checks for "any traces to arrive" https://github.com/quarkusio/quarkus/blob/b687fbb7ba8678d99433be71aca5dd1f358fb6e6/integration-tests/opentelemetry-jdbc-instrumentation/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryJdbcInstrumentationTest.java#L50, while I should give time for "INSERT" traces to arrive. That makes it flaky (you can see test ended after 3 s, so timeout is never exhausted). My bad, it's unrelated, I'll open PR when I find little time.

**Comment by Sanne** [comment]
awesome, many thanks for the help :)

**Review by gsmet — APPROVED** [review]

**Pull request merged**
