### PR TITLE
Webauthn improvements : docs, customisable cookies, virtual thread support

### PR DESCRIPTION
**Pull request by FroMage**
This is mostly docs improvements, but also #38352 and #38351

### CODE REVIEW

**Comment by FroMage** [comment]
For @cescoffier 's review, it's mostly about the logic in https://github.com/quarkusio/quarkus/pull/38373/files#diff-493a6f5a982ad741f9a8c8b0a8485833005410f7e2fb3062f4c53290a7238dfeR44 that I'm not entirely convinced about.

There are tests, though, but a logic/sanity check would not hurt.

**Review by cescoffier — APPROVED** [review]
The virtual thread part looks good to me!

**Comment by FroMage** [comment]
First failure is my fault, but the second one about import sorting is annoying, locally it's not run:

```
[INFO] --- impsort-maven-plugin:1.9.0:sort (sort-imports) @ quarkus-integration-test-virtual-threads-security-webauthn ---
[INFO] Skipping execution of impsort-maven-plugin
```

**Comment by FroMage** [comment]
Oh great, so I have to run the build on java < 20, then java 20.

**Comment by FroMage** [comment]
Yeah, the quickstarts have their own PR at https://github.com/quarkusio/quarkus-quickstarts/pull/1377 how do we get out of this kind of chicken/egg issue @gsmet ?

**Comment by sberyozkin** [comment]
Hi Steph, @FroMage, thanks for the PR. This is for `main` , so I've been thinking, I'll need to work through the tutorial and catch up a bit on some WebAuthn mechanics, spec details, as it is getting a bit vague for me, and then I'll be happy to review. Hope you are OK with it, we have a lot of time before 3.9 is released, I'll try to finish it within up to 2 weeks.
Clement's review is enough to merge, so if you'd like, go ahead, only keep it open if you'd like to wait for one more approval.

Cheers

**Comment by FroMage** [comment]
This PR doesn't change any mechanics of webauthn beyond giving the ability to configure the cookie names in use, and allowing virtual threads where blocking calls were also allowed.

As such, it can be reviewed without any webauthn knowledge.

**Review by sberyozkin — APPROVED** [review]
@FroMage Apologies for a delay, while I definitely want to start helping with more concrete reviews, I'm falling behind right now and don't want to hold this important PR with various fixes, it should be part of 3.9 for sure. @cescoffier has already approved, so please go ahead with the merge when you are ready, thanks

**Comment by FroMage** [comment]
Not sure what that failure was about, rebased and retrying.

**Comment by FroMage** [comment]
I don't understand why the `enforcer` plugin runs locally:

```
[INFO] --- enforcer:3.2.1:enforce (enforce) @ quarkus-integration-test-virtual-threads-security-webauthn ---
Downloading from apache.snapshots: https://repository.apache.org/snapshots/io/quarkus/quarkus-parent/999-SNAPSHOT/maven-metadata.xml
[INFO] Rule Config Provider org.apache.maven.enforcer.rules.ExternalRules executed
[INFO] Rule Config Provider org.apache.maven.enforcer.rules.ExternalRules executed
[INFO] Rule 0: org.apache.maven.enforcer.rules.dependency.DependencyConvergence passed
[INFO] Rule 1: io.quarkus.enforcer.RequiresMinimalDeploymentDependency passed
[INFO] Rule 2: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] Rule 3: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
```

**Comment by FroMage** [comment]
Quickstart failure is normal, as there's a separate PR for it.

**Comment by FroMage** [comment]
No answer about quickstart, let's just merge this and get this done.

**Pull request merged**
