### PR TITLE
Use LinkedHashMap for parts map to ensure user input order

### LINKED ISSUE #37214: MultipartFormDataOutput should use an ordered map instead of a HashMap
### Describe the bug

See [RESTEASY-3217](https://issues.redhat.com/browse/RESTEASY-3217): `MultipartFormDataOutput` uses a `HashMap` for the `parts` map, this should use a `LinkedHashMap` to honor the users' input order.

With 2.16.x we extended `MultipartFormDataOutput` to use a `LinkedHashMap`, which was possible because the class was not `final` yet. This has in the meantime been changed with #30307, and hence I'd like to ask if it would be possible to use `LinkedHashMap` in the `final` class now, just like Resteasy does it too.

I haven't found whether the standard requires preserving the order, but it seems there are consumers out there which do (at least that's the case for us).

Changing the map implementation from `HashMap` to `LinkedHashMap` should have no implications to existing code.

### Expected behavior

The parts in a `multi-part/form-data` response should appear in the response body in the same order as they've been added with `addFormData()` programmatically.

### Actual behavior

The actual order of the parts in a `multi-part/form-data` response appear in an unpredictable order in which `HashMap` decides to order them.

### How to Reproduce?

-

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.5.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Added #37215.

### PR DESCRIPTION
**Pull request by bschuhmann**
Fixes #37214.

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks! It probably doesn't hurt and can be useful but I will let @geoand have the final say on this.

**Review by geoand — APPROVED** [review]
Thanks

**Comment by sberyozkin** [comment]
Welcome @bschuhmann :+1:

**Comment by bschuhmann** [comment]
@gsmet, is there any chance this can go to 3.5.x as well?

Also, I was just about to add a unit test to `MultipartOutputUsingBlockingEndpointsTest` before I noticed my PR was already merged - would that make sense and would you still be interested?

**Comment by geoand** [comment]
I don't think we need a test for such a change.

Also, sure , it's safe so as can backport to 3.5 if there is another such release

**Comment by gsmet** [comment]
It was already marked for backports. I plan to release 3.5.3 tomorrow.

**Pull request merged**
