### PR TITLE
Release configuration when launch mode changes between tests

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Creating as a draft PR, because this needs to be discussed a little (I believe).

Hi @stuartwdouglas @geoand @radcortez, could you please take a look at this? There are 2 things I'd like to discuss.

1. In case Surefire wants to runs multiple tests, and there's at least one dev mode test and at least one other test, the current launch mode will change in between individual tests (that is in the Surefire JVM, not in a Quarkus app JVM). During a very interesting debugging session last week (see #24356 if interested), I came to believe that when the launch mode changes between tests, the current configuration (as returned by `ConfigProvider.getConfig()`) must be dropped (because it contains stale data -- at the very least the `test.url` URL will change, which affects `@TestHTTPResource` injection) and later rebuilt (that would happen on demand). Does that make sense to you?

2. To be able to drop the current configuration, I'm poking into SmallRye Config via reflection. `SmallRyeConfigProviderResolver` doesn't allow dropping configs by classloader, and when I ask it for a config object for given classloader, it will unconditionally create one if missing. That might be harmless, but since we're doing crazy things to speed up configuration building elsewhere (see `BasicLoggingEnabler`), I figured I'd rather err on the side of caution. WDYT?

**Comment by geoand** [comment]
> I came to believe that when the launch mode changes between tests, the current configuration (as returned by ConfigProvider.getConfig()) must be dropped (because it contains stale data -- at the very least the test.url URL will change, which affects @TestHTTPResource injection) and later rebuilt (that would happen on demand). Does that make sense to you?

Yeah, that seems reasonable to me

**Comment by Ladicek** [comment]
One more thing re item 2, @ozangunalp correctly pointed out [here](https://github.com/quarkusio/quarkus/pull/24356#issuecomment-1072613988) that `TestResourceManager` does something similar in the `close` method and just calls `configProviderResolver.releaseConfig(configProviderResolver.getConfig())`, so maybe it's not that big of a deal. I'm no expert, so I wanted to ask what experts think :-)

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
This should already be cleaned up as part of shutdown, if the config is not being released then this is a bug.

**Comment by Ladicek** [comment]
Then there's a bug. If you can point me to the code that should handle config release (in the Surefire JVM!) after each test, I'll take a look.

**Comment by stuartwdouglas** [comment]
Just have a look for usages of `releaseConfig` in the source. There are a couple of different config instances created, so it depends which one you are talking about.

Application.close() should be the place where the main runtime one is released, but there is also deployment time config that is released after augmentation.

My guess would be that something is creating a new implicit config by attempting to access it after it has been released.

**Comment by Ladicek** [comment]
OK, I'll check it once again. I don't recall configuration being recreated for each test, it seemed as if the `Config` instance lived across all the tests.

**Comment by stuartwdouglas** [comment]
It definitly doesn't, Quarkus Dev mode and Unit tests can all have different config (e.g. they can all have different application.properties).

**Comment by Ladicek** [comment]
Right, but that's in the JVM where the Quarkus application is running. What concerns me here is the Surefire JVM.

Oh I just realized, I'm actually formulating it in a completely misleading way, because there's always just a single JVM. The Quarkus app runs in a separate _classloader_, not a separate JVM. Ugh.

OK let me look at it once again, though if I remember correctly, the `@TestHTTPResource` is being injected based on the `Config` object associated with the system classloader.

**Comment by Ladicek** [comment]
OK so I can indeed see many `Config` objects associated with a Quarkus CL come and go, but there's always also a `Config` associated with the system CL (which is the TCCL when `@TestHTTPResource` is being injected), and that lives forever. It is only torn down by `TestResourceManager.close` when JUnit shuts down.

I'm not sure if _that_ is by design or not. I assumed it is.

**Comment by stuartwdouglas** [comment]
I would say this is likely an accident, the config associated with the external CL is not really defined.

**Comment by Ladicek** [comment]
OK now I remember that we used to intercept `@Test` methods and forward their invocation to an instance in the Quarkus CL. Maybe that only happens for the "normal" tests and not for dev mode tests? (Didn't look, just guessing. I don't know anything about dev mode tests.)

**Comment by Ladicek** [comment]
I'm closing this. Based on the discussion above, I realized that there's probably an expectation that no `Config` object remains associated with the system classloader between tests. Indeed, that's what one problematic test does. Fixing that test is fortunately straightforward.

**Pull request closed without merging**
