### PR TITLE
Packs libraries alongside executable in function.zip

### LINKED ISSUE #35713: AWS Lambda extension does not pack necessary .so files when AWT is used
### Describe the bug

See https://github.com/quarkusio/quarkus/issues/35256#issuecomment-1705087637

The AWS Lambda extension must pack all necessary files into the function.zip.

### Expected behavior

AWS Lambda function.zip contains needed shared object (.so) dependencies. 

### Actual behavior

AWS Lambda function.zip contains just the runner executable.

### How to Reproduce?

See https://github.com/quarkusio/quarkus/issues/35256#issuecomment-1705087637

### Output of `uname -a` or `ver`

Linux 4.18.0-500.el8.x86_64

### Output of `java -version`

openjdk 17.0.8 2023-07-18

### GraalVM version (if different from Java)

OpenJDK Runtime Environment Mandrel-23.0.1.2-Final (build 17.0.8+7)

### Quarkus version or git rev

3.1, 3.2, main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Karm**
Fixes #35713

Using the reproducer from https://github.com/quarkusio/quarkus/issues/35256#issuecomment-1705087637

I tested that it indeed packs the libraries now:

```
$ unzip -l  target/function.zip
Archive:  target/function.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 76905784  09-04-2023 15:00   bootstrap
   871000  09-04-2023 15:00   libawt.so
    46504  09-04-2023 15:00   libawt_headless.so
   486832  09-04-2023 15:00   libawt_xawt.so
  2495760  09-04-2023 15:00   libfontmanager.so
   239768  09-04-2023 15:00   libjavajpeg.so
   606272  09-04-2023 15:00   liblcms.so
   606952  09-04-2023 15:00   libmlib_image.so
     7888  09-04-2023 15:00   libjava.so
     7888  09-04-2023 15:00   libjvm.so
---------                     -------
 82274648                     10 files
```

And that it also works on AWS:

setup-1

Upload function.zip and run it:

setup-2

The output is sane:
```
$ echo 'JVBERi0xLjQKJfbk/N8KMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovVmVyc2lvbiAvMS43Ci9QYWdlcyAyIDAgUgo+PgplbmRvYmoKMyAwIG9iago8PAovQ3JlYXRpb25EYXRlIChEOjIwMjMwOTA0MTMwNTEyKzAwJzAwJykKL1Byb2R1Y2VyIChvcGVuaHRtbHRvcGRmLmNvbSkKPj4KZW5kb2JqCjIgMCBvYmoKPDwKL1R5cGUgL1BhZ2VzCi9LaWRzIFs0IDAgUl0KL0NvdW50IDEKPj4KZW5kb2JqCjQgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL01lZGlhQm94IFswLjAgMC4wIDU5NS4yNzUgODQxLjg3NV0KL1BhcmVudCAyIDAgUgovQ29udGVudHMgNSAwIFIKL1Jlc291cmNlcyA2IDAgUgo+PgplbmRvYmoKNSAwIG9iago8PAovTGVuZ3RoIDEyOAovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0NCnicVcw7CwJBDATgfn7FlNqsSW6X22sFLQQLIWAhdr44PMEH+PfdtfBBIIRvhkiQpk18wriAsIcKl9hsKdzhWiRHDbk0BqQuBWuT2MfOPyb1UczF5O/+dk9Y41LTMrcjpo7JXKlGP0DfWnduNKha7OgDRr6/P8b0HjPHCi+awCLiDQplbmRzdHJlYW0KZW5kb2JqCjYgMCBvYmoKPDwKL0ZvbnQgNyAwIFIKPj4KZW5kb2JqCjcgMCBvYmoKPDwKL0YxIDggMCBSCj4+CmVuZG9iago4IDAgb2JqCjw8Ci9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9UeXBlMQovQmFzZUZvbnQgL1RpbWVzLVJvbWFuCi9FbmNvZGluZyAvV2luQW5zaUVuY29kaW5nCj4+CmVuZG9iagp4cmVmCjAgOQowMDAwMDAwMDAwIDY1NTM1IGYNCjAwMDAwMDAwMTUgMDAwMDAgbg0KMDAwMDAwMDE2OSAwMDAwMCBuDQowMDAwMDAwMDc4IDAwMDAwIG4NCjAwMDAwMDAyMjYgMDAwMDAgbg0KMDAwMDAwMDM0MiAwMDAwMCBuDQowMDAwMDAwNTQ0IDAwMDAwIG4NCjAwMDAwMDA1NzcgMDAwMDAgbg0KMDAwMDAwMDYwOCAwMDAwMCBuDQp0cmFpbGVyCjw8Ci9Sb290IDEgMCBSCi9JbmZvIDMgMCBSCi9JRCBbPEJENkI3NzQ2MEY1QTBEREFCREIyMjE2MEM2MUQ2RUQ3PiA8QkQ2Qjc3NDYwRjVBMEREQUJEQjIyMTYwQzYxRDZFRDc+XQovU2l6ZSA5Cj4+CnN0YXJ0eHJlZgo3MDcKJSVFT0YK' 
| base64 -di > test.pdf; evince ./test.pdf
```
setup-3

### CODE REVIEW

**Review by geoand — APPROVED** [review]
LGTM

**Comment by Karm** [comment]
This seems to be scattered all over the place all over various contemporary GHA runs...

```
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_7e0594f6-953a-474e-9322-46efe690c48d/e8bff115-11ab-4cc4-9c98-b357cc8c880e.tar.gz. return code: 2.
```

Definitely unrelated. Re-running didn't help though.

**Comment by patriot1burke** [comment]
@geoand Isn't this a general problem with the way we build native?  SSL is also a .so that should be included.

@Karm My biggest concern is the inclusion of AWT and fontmanager.  They are big and not used?  AWT is the old Java GUI stuff from 90s, is it not?

**Comment by Karm** [comment]
@patriot1burke 

> @geoand Isn't this a general problem with the way we build native? SSL is also a .so that should be included.

That is a slightly separate topic of using/not using the one coming from the OS. I would like to deal with is separately. 
 
> @Karm My biggest concern is the inclusion of AWT and fontmanager. They are big and not used? AWT is the old Java GUI stuff from 90s, is it not?

The files are included only if they exist. They exist only if they are needed. That happens when your app depends on our somewhat poorly named "AWT Extension".
You want to depend on that extension if you do any kind of server side image processing, e.g. resizing images, rendering fonts, dealing with ccompressions, encodings, color spaces etc.

AWT libs are there because it historically implements a lot of stuff we need. We only support headless use though, i.e. no GUI.

....and with that said, compared to Swing and JavaFX, AWT was the best :-P  */me dodges flying stones*

**Comment by Karm** [comment]
@geoand Ready to be merged IMHO.

**Comment by geoand** [comment]
@patriot1burke any objections?

**Pull request merged**
