### PR TITLE
Fix DevServices for Keycloak loading the realm file from the file system

### LINKED ISSUE #21975: Regression: DevServices for Keycloak fails to load a realm file from the file system
### Describe the bug

We have 3 quickstart tests where `Dev Services for Keycloak` loads the file from the classpath.
The user reported on Zulip loading the file system does not work.

As it happens, it used to work but myself has managed to lose the line which did make it work during some of the refactoring.
It has to be restored, and I'll update one of the quickstarts to test it

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #21975 

(and also removes an unused `shared` property in `StartResult`)

See also https://github.com/quarkusio/quarkus-quickstarts/pull/1001

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Can you add a test for this?

**Comment by sberyozkin** [comment]
Hi @stuartwdouglas It is in the linked quickstart PR, I did not want to copy the large realm file here; in `oidc_token_propagation` which uses Dev Services it is tested that Dev Services does not create a realm.  Would that quickstart test do ? I don't mind, I can rework some of the existing tests here around the realm file...

**Comment by sberyozkin** [comment]
@stuartwdouglas I can update @geoand 's test once #21999 get merged to use a file system path to the realm file, 3 quickstarts  currently use the class based resource for testing. Though having only one of the quickstarts checking the file system path should also be OK IMHO, it will fail if the regression is introduced here before the release...

**Comment by sberyozkin** [comment]
Hi Stuart, @stuartwdouglas It took me awhile to find where I can add the realm file, with a few tries, but finally, `interation-tests/oidc-client-reactive-filter` has come to the rescue :-). It should do it, thanks

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks for this @sberyozkin!

**Comment by sberyozkin** [comment]
Hi @geoand Can you have a look please since you also worked recently on updating Keycloak Dev Services (and I recall it was a more difficult update than adding a file system bind :-) ) - this PR does that and updates the test

**Comment by geoand** [comment]
Should this be backported to `2.6` and `2.5`?

**Comment by sberyozkin** [comment]
Thanks for a super fast review @geoand :-)

**Comment by sberyozkin** [comment]
Yeah, if it can make it to 2.5.x it would be fine, let me add the labels

**Comment by geoand** [comment]
Great, thanks!

**Pull request merged**
