### PR TITLE
Propagate completion and error events in Redis pub/sub

### LINKED ISSUE #33418: Quarkus redis reactive pubsub disconnecting handler
### Describe the bug

I have the following code:
```
ReactiveRedisDataSource redis; -> Injected
ReactivePubSubCommands<String> pubsub = redis.pubsub(String.class);
pubsub.subscribe('my-channel')
                .onItem().call(this::consume)
                .subscribe().with(
                        notificationId -> log.debug("New notification has been processed {}", notificationId),
                        err -> log.error("Error while listening for new notifications ", err));
```

Everything is working fine, I receive data via the subscription, but for some reason, after a while (days, weeks), my subscription is gone. It can be checked by running in redis the folowing command:
```
PUBSUB NUMSUB my-channel
```
Initially returns 1, but when my issues occurs, it is going to 0. No other failures can be seen in the application. 

It is very easy to reproduce the issue:
1. Connect via the code above to a redis docker instance.
2. Check `PUBSUB NUMSUB my-channel -> 1`
3. Stop redis container
4. Start redis container
5. Now `PUBSUB NUMSUB my-channel -> 0` and no errors thrown in code.

**How can I watch the disconnected state to be able to manually reconnect?** I tried to add handlers like `onTermination`, `onCanncelation`, `onFailure`, `onCompletion` but they are never triggered. 

An undesired solution is to use 
```
pubsub.Uni<ReactiveRedisSubscriber> subscribe(String channel, Consumer<V> onMessage, Runnable onEnd,
            Consumer<Throwable> onException);
```

I noticed that when my redis connection is going down, it triggers `onEnd` handler.

But this cuts my reactivity in the process for consuming the event. I want to use `pubsub.Multi<V> subscribe(String... channels)`

### Quarkus version or git rev

2.14.3.Final

### PR DESCRIPTION
**Pull request by cescoffier**
When subscribing to a channel, the subscriber gets the completion and exception events using the `pubSub.subscribe(channel)` method.

Note that if the Redis server is shut down, it receives the completion signal.

Fix https://github.com/quarkusio/quarkus/issues/33418.

### CODE REVIEW

**Review by machi1990 — CHANGES_REQUESTED** [review]
Thanks for the improvement @cescoffier  Should we do the same here https://github.com/quarkusio/quarkus/blob/dbeb3aa1701cea6ffb5429acf44d4fb49fe2e01c/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactivePubSubCommandsImpl.java#L161 ?

**Comment by cescoffier** [comment]
@machi1990 Absolutely! 

I fixed it!

**Review by machi1990 — APPROVED** [review]
lgtm

Thanks @cescoffier

**Comment by machi1990** [comment]
Failing test is unrelated. I'll merge this PR.

**Comment by silviu-negoita** [comment]
@cescoffier  thank you for fixing this :)

**Pull request merged**
