### PR TITLE
Add a GCF Cloud Event function example in the codestart

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by gsmet** [comment]
@loicmathieu looks like CI isn't happy about it.

**Comment by loicmathieu** [comment]
@gsmet yes, I know, and I have no idea why ...

@ia3andy do you have an idea of what I'm missing ?

**Comment by ia3andy** [comment]
@loicmathieu 

When running locally I get this on `testExampleCodestartsJava`:
```java
-build-test/project-maven-java-google-cloud-functions-example/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/ia3andy/workspace/redhat/quarkus/quarkus/integration-tests/devtools/target/quarkus-codestart-build-test/project-maven-java-google-cloud-functions-example/src/main/java/org/acme/googlecloudfunctions/HelloWorldCloudEventsFunction.java:[10,8] class HelloWorldBackgroundFunction is public, should be declared in a file named HelloWorldBackgroundFunction.java
[ERROR] /Users/ia3andy/workspace/redhat/quarkus/quarkus/integration-tests/devtools/target/quarkus-codestart-build-test/project-maven-java-google-cloud-functions-example/src/main/java/org/acme/googlecloudfunctions/HelloWorldBackgroundFunction.java:[9,8] duplicate class: org.acme.googlecloudfunctions.HelloWorldBackgroundFunction

**Comment by ia3andy** [comment]
The class name in that file is wrong:
https://github.com/quarkusio/quarkus/blob/30de971cca3dcab445ce6f3a46e34f1adaffd60e/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/examples/google-cloud-functions-example/java/src/main/java/org/acme/googlecloudfunctions/HelloWorldCloudEventsFunction.java#L10

**Comment by loicmathieu** [comment]
Thanks @ia3andy bad copy/paste, I don't understand why I didn't saw the error, all test was green locally (or I was tired and miss something obvious ...). I'll update tomorrow my PR.

**Review by ia3andy — APPROVED** [review]
It looks good codestart wise, I didn't check the business part.

**Pull request merged**
