### PR TITLE
[WIP] Support both GraalVM 19.2.1 and 19.3.1 - Duplicate targeting GraalVM 19.3.1-java8

### PR DESCRIPTION
**Pull request by gwenneg**
Duplicate of #6574 with a different GraalVM target: `19.3.1-java8`.

This is a control PR that is not meant to be merged and will be closed as soon as #6574 is merged.

### CODE REVIEW

**Review by geoand — CHANGES_REQUESTED** [review]
Just making sure it won't be merged by accident :)

**Comment by geoand** [comment]
The failure should be fixed by https://github.com/quarkusio/quarkus/pull/6597

**Comment by geoand** [comment]
I pushed the Netty substitution commit, let's see if CI passes

**Comment by gwenneg** [comment]
All natives tests are green :tada:

**Comment by geoand** [comment]
AWESOME job @gwenneg !

**Comment by geoand** [comment]
This PR did what it was meat to do which was to test GraalVM 19.3.1. It can now rest in piece :)

**Pull request closed without merging**
