### PR TITLE
Upgrade checkout and java-setup actions to version v4

### LINKED ISSUE #38549: Upgrade actions/setup-java to v4
### Description

Hi @gastaldi how are you? I saw your effort to upgrade the actions from `actions/setup-java@v3`  to `actions/setup-java@v4` version. 

I created a new version with `io.quarkiverse` template, and was possible to see that the scaffold generated is using the version v3, makes sense to update this one? If yes, I created a draft pull request for this.

__

### Implementation ideas

Upgrade version for those files:

https://github.com/quarkusio/quarkus/blob/dfe434e774206720c8f30825747b8b9fb33205fe/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/.github/workflows/build.tpl.qute.yml#L49

https://github.com/quarkusio/quarkus/blob/dfe434e774206720c8f30825747b8b9fb33205fe/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/.github/workflows/quarkus-snapshot.tpl.qute.yaml#L41

https://github.com/quarkusio/quarkus/blob/dfe434e774206720c8f30825747b8b9fb33205fe/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/github-action/base/.github/workflows/ci.tpl.qute.yml#L17

### PR DESCRIPTION
**Pull request by mcruzdev**
Fixes #38549

### CODE REVIEW

**Comment by gastaldi** [comment]
Nice! Can you also bump actions/checkout to v4? Thanks

**Comment by gastaldi** [comment]
BTW some tests are going to fail because of this change, you need to run `mvn clean verify -Dsnap` in the `integration-tests/maven` directory

**Comment by mcruzdev** [comment]
Hi @gastaldi I executed the command into the specified module and works well. I upgraded the checkout action too.

**Comment by gastaldi** [comment]
Ah sorry, I think the correct command is something like:
`mvn clean install -Dsnap -Dit.test=CreateExtensionMojoIT -Dtest=CreateExtensionMojoIT`

**Comment by gastaldi** [comment]
Can you squash those commits before we merge this?

**Comment by mcruzdev** [comment]
noooo ;/

**Review by gastaldi — APPROVED** [review]

**Comment by mcruzdev** [comment]
I am fixing the broken tests

**Comment by mcruzdev** [comment]
@gastaldi this issue is related to the pull request or is just a flaky test as quarkus said?

**Comment by gastaldi** [comment]
The ones in `independent-projects/tools/devtools-testing` seem related to this change 🤔

**Comment by gastaldi** [comment]
Please squash all commits before we merge this

**Comment by mcruzdev** [comment]
Hi @gastaldi, done! Thank you for the support!

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
