### PR TITLE
Google Cloud Functions test framework

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by loicmathieu** [comment]
@patriot1burke would you have some time to review this PR ?

**Comment by patriot1burke** [comment]
LGTM, but, have you considered creating a DevService instead like I do for Lambda and the MockEventServer?  This way, the user doesn't have to add the test framework as a dependency.  One less thing they have to worry about.

**Comment by loicmathieu** [comment]
@patriot1burke 
> have you considered creating a DevService instead like I do for Lambda and the MockEventServer? This way, the user doesn't have to add the test framework as a dependency. One less thing they have to worry about.

Yes, I look at it but it was more work to do and the design of the invoker plays nicely with a test framework but less with an integration with Vert.x. Maybe I'll have time for a second look some day and provide a DevService.

**Comment by patriot1burke** [comment]
> @patriot1burke
> 
> > have you considered creating a DevService instead like I do for Lambda and the MockEventServer? This way, the user doesn't have to add the test framework as a dependency. One less thing they have to worry about.
> 
> Yes, I look at it but it was more work to do and the design of the invoker plays nicely with a test framework but less with an integration with Vert.x. Maybe I'll have time for a second look some day and provide a DevService.

I really do wish you'd look into a DevService as Lambda started out this way and we had to add hacks for backward compatibility, but I understand you are an external contributor and have RL to worry about and would approve without that chane.

You'll need a rebase for this branch and documentation before I can approve, though.

TY!!!

**Comment by loicmathieu** [comment]
@patriot1burke I added some documentations, can you approve this PR ?

**Comment by patriot1burke** [comment]
> @patriot1burke I added some documentations, can you approve this PR ?

You need to rebase with main before I can approve.

**Comment by loicmathieu** [comment]
@patriot1burke I rebase onto main, can you approve it ?

**Review by patriot1burke — APPROVED** [review]

**Pull request merged**
