### PR TITLE
MP Config integration - support injection of arrays and custom types

### LINKED ISSUE #2379: MP Config integration - support injection of arrays and custom types
See SR config extension: https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/inject/ConfigExtension.java#L65-L125

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #2379

### CODE REVIEW

**Comment by geoand** [comment]
I probably won't be able to review this until the weekend :(

**Comment by mkouba** [comment]
@geoand No problem. Thanks for letting me know.

**Review by dmlloyd — APPROVED** [review]
For a future enhancement you might want to look into `io.quarkus.runtime.configuration.ConverterFactory#getImplicitConverter` which returns the `Converter` directly.  You can use this in a static init and avoid having to register whole classes for reflection.

**Comment by dmlloyd** [comment]
Waiting for CI.

**Comment by mkouba** [comment]
@dmlloyd Hm, the `ConverterFactory` is marked as deprecated and there is a comment _"For removal once https://github.com/smallrye/smallrye-config/issues/80 is resolved"_. And this issue is closed ;-).

Anyway, I'm not sure I fully understand your proposal. But if you feel it would be worth exploring pls create a new issue.

**Comment by dmlloyd** [comment]
Yeah that class is going to be replaced with a SmallRye implementation class that I just implemented yesterday. :)

**Pull request merged**
