### PR TITLE
Separate Hibernate Reactive tests against MariaDB / MySQL

### PR DESCRIPTION
**Pull request by yrodiere**
~~Based on #33790 which should be merged first.~~ => Done

This creates a module `integration-tests/hibernate-reactive-mariadb` next to `integration-tests/hibernate-reactive-mysql`, and updates `integration-tests/hibernate-reactive-mysql*` to actually use a MySQL instance (and not MariaDB like it used to).

This is important because Hibernate Reactive has a different dialect for MariaDB and MySQL, so tests passing with one may not pass with the other.

### CODE REVIEW

**Review by DavideD — APPROVED** [review]

**Review by Sanne — APPROVED** [review]

**Comment by gsmet** [comment]
@yrodiere CI is unhappy and there is a conflict now.

**Comment by yrodiere** [comment]
Yes, I'm on it.

**Comment by yrodiere** [comment]
Should be better now. I ran tests locally for the three relevant modules and they passed.

**Comment by yrodiere** [comment]
Test failures look unrelated. Merging.

**Pull request merged**
