### PR TITLE
Add topics and extensions metadata to guides

### PR DESCRIPTION
**Pull request by gsmet**
We will be able to use this in the new search and also to provide additional suggestions/links to other guides ("More like this" feature) and to create links to the extension website and others.

Sorry there is some noise due to vscode cleaning up spaces, but as I updated all the guides, it's probably the last time we see that.
Also a Kotlin file got reformatted with import order.

### CODE REVIEW

**Comment by gsmet** [comment]
My guess is that we will also need a way to link guides that are different types of the exact same subject to offer a very easy navigation between them.
The security guides are a good example of that: they have been split with a very small granularity and it's very hard to actually find the entry point for them.

**Comment by gsmet** [comment]
@yrodiere ideally, I would like them indexed as facets so that we could for instance list the topics and the extensions in the index page (or a specific search page).
I have a vague recollection that Elasticsearch could suggest similar documents based on specific fields, is it the case?

**Comment by yrodiere** [comment]
> @yrodiere ideally, I would like them indexed as facets so that we could for instance list the topics and the extensions in the index page (or a specific search page).

My main concern if we do that is that we wouldn't be able to degrade gracefully to javascript search in case the search service isn't available for some reason or is too slow to answer.

Anyway... Please create an issue :) https://github.com/yrodiere/search.quarkus.io/issues

> I have a vague recollection that Elasticsearch could suggest similar documents based on specific fields, is it the case?

There's a more like this query, but it's not supported by Hibernate Search, we'd have write native JSON queries.

**Comment by gsmet** [comment]
> My main concern if we do that is that we wouldn't be able to degrade gracefully to javascript search in case the search service isn't available for some reason or is too slow to answer.

I think we could still find ways to degrade the behavior if the service is not available. When we get the facets, we know if the service is available or not and we can go from there.
If the service degrades while we are doing queries, we could reload the page with something in the query string and display a message saying the service is degraded.

My guess is that something like that could work and wouldn't be too hard to code?

> There's a more like this query, but it's not supported by Hibernate Search, we'd have write native JSON queries.

OK. I don't expect them to be very complex to write as we would target just a few fields.

**Review by gastaldi — APPROVED** [review]
LGTM

**Pull request merged**
