### PR TITLE
Usage section added to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mklueh**
I´ve added a short usage section to make it a bit clearer how to use artifacts in your project after you´ve build it locally.
As I´m using Gradle myself I´ve only added the Gradle subsection, so if Maven is relevant too it should be added as well

### CODE REVIEW

**Review by machi1990 — CHANGES_REQUESTED** [review]
Thanks @mklueh I like it and this is very useful. Can we add a maven section too taking inspiration from https://github.com/quarkusio/quarkus-quickstarts/blob/development/getting-started/pom.xml#L9-L32?

**Comment by mklueh** [comment]
@machi1990 glad to hear. I can add that as well, but two questions:

1. Do we have to explicitly define the local repository in the pom.xml like we have to in the build.gradle/settings.gradle or is it used automatically?

2. As I have not worked with pull requests before I have no idea how to add another commit to this existing request. I´d assume to convert it to a draft pull request first, then do the commit on my forked repository and see if it asks me somewhere to refresh my request. Am I on the right track?

**Comment by geoand** [comment]
> @machi1990 glad to hear. I can add that as well, but two questions:
> 
>     1. Do we have to explicitly define the local repository in the pom.xml like we have to in the build.gradle/settings.gradle or is it used automatically?

It's used automatically in Maven
> 
>     2. As I have not worked with pull requests before I have no idea how to add another commit to this existing request. I´d assume to convert it to a draft pull request first, then do the commit on my forked repository and see if it asks me somewhere to refresh my request. Am I on the right track?
> 

You can just push a new commit to your pull request, although it would be best if you just amend your commit and force push the change

**Comment by mklueh** [comment]
@geoand Hi Geoand, I tried to do a rebase squash but it did not work as expected, so I did a revert and then amended the changes to the first commit and force pushed. Thank you

**Comment by geoand** [comment]
Cool, thanks!

**Review by machi1990 — APPROVED** [review]
Much better, thanks for the update @mklueh

**Review by geoand — APPROVED** [review]
Thanks a lot!

**Pull request merged**
