### PR TITLE
Bootstrap - include reloadable artifacts to deployment classloader

### LINKED ISSUE #16681: Property "quarkus.class-loading.reloadable-artifacts" creates "ClassNotFoundException" in Arc
Update:
This property creates a ClassNotFoundException in arc when we wants to inject instances of CDI beans of this library.

Example: I want to inject all classes that implements a "NewServiceInterface" defined in the "libx" in my REST class of the app:

@Path("/hello")
public class GreetingResource {

    @Inject
    Instance<NewServiceInterface> services;
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        SingletonObject.getInstance().doSomething();
        SingletonObject2.getInstance().doSomething();
        System.out.println("services size: " +  services.stream().count());
        return "Hello RESTEasy again or nothing..";
    }

in the depedency "libx", I have this class NewServiceImpl, and the interface NewServiceInterface. 

@ApplicationScoped
public class NewServiceImpl implements NewServiceInterface {
}

Without quarkus.class-loading.reloadable-artifacts=org.acme.test:libx
=> No issue: I see "services size: 1"

With quarkus.class-loading.reloadable-artifacts=org.acme.test:libx
=> Class not found exception at first call of http://localhost:8080/hello (no reload at all)

2021-04-20 11:52:44,277 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 69d2e706-5b85-49e5-b5c4-84c611c0f658-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: org/acme/test/libx/NewServiceImpl
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
...
Caused by: java.lang.NoClassDefFoundError: org/acme/test/libx/NewServiceImpl
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:411)
...
Caused by: java.lang.ClassNotFoundException: org.acme.test.libx.NewServiceImpl                              
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)          
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)       
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                  
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:421)      
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)     

I tried adding
quarkus.class-loading.parent-first-artifacts=org.acme.test:libx
quarkus.arc.unremovable-types=org.acme.test.libx.**
Not working neither.

_Originally posted by @iriikoad in https://github.com/quarkusio/quarkus/issues/16633#issuecomment-823221087_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #16681

### CODE REVIEW

**Comment by mkouba** [comment]
I verified this fix manually but I have no idea how to write an automated test for this...

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
This should also be removed from augment class loader. It's not 100% necessary but it keeps things consistent with the way the runtime and base runtime CL is setup.

**Comment by mkouba** [comment]
> This should also be removed from augment class loader. It's not 100% necessary but it keeps things consistent with the way the runtime and base runtime CL is setup.

Removed? I'm not following... Do you mean that we should filter out reloadable arfitacts from the `AppModel.getFullDeploymentDeps()` [here](https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java#L180-L182)?

**Comment by stuartwdouglas** [comment]
Yea, like we do here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java#L235

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
