### PR TITLE
Cache generated applications for different test profiles

### PR DESCRIPTION
**Pull request by stuartwdouglas**
If a profile is restarted the augment phase does
not need to run again.

### CODE REVIEW

**Comment by geoand** [comment]
Looks good! 

I think however that we should have some more tests (that don't run alphabetically) to make sure we don't break anything in the future.

**Comment by stuartwdouglas** [comment]
The existing profile test runs in the middle, so the default profile is stopped, the custom profile is run, then the default is restarted.

**Comment by geoand** [comment]
Right, I just looked at the tests name, so that's cool.

**Review by geoand — APPROVED** [review]
:+1:

**Comment by geoand** [comment]
Test failure seems related:

```
2020-06-16T07:11:28.3149677Z [ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 4.683 s <<< FAILURE! - in io.quarkus.grpc.server.GrpcHealthTest
2020-06-16T07:11:28.3150010Z [ERROR] shouldGetHealthInfoFromMultipleStreams  Time elapsed: 0.258 s  <<< ERROR!
2020-06-16T07:11:28.3151162Z java.lang.LinkageError: loader constraint violation: when resolving method "io.quarkus.grpc.runtime.health.GrpcHealthStorage.setStatus(Ljava/lang/String;Lgrpc/health/v1/HealthOuterClass$HealthCheckResponse$ServingStatus;)V" the class loader (instance of io/quarkus/bootstrap/classloading/QuarkusClassLoader) of the current class, io/quarkus/grpc/server/GrpcHealthTest, and the class loader (instance of io/quarkus/bootstrap/classloading/QuarkusClassLoader) for the method's defining class, io/quarkus/grpc/runtime/health/GrpcHealthStorage, have different Class objects for the type grpc/health/v1/HealthOuterClass$HealthCheckResponse$ServingStatus used in the signature
2020-06-16T07:11:28.3151815Z 	at io.quarkus.grpc.server.GrpcHealthTest.shouldGetHealthInfoFromMultipleStreams(GrpcHealthTest.java:85)
```

**Comment by stuartwdouglas** [comment]
This changed the tests to use the same class loading scheme as dev mode, it is likely related.

**Comment by geoand** [comment]
> This changed the tests to use the same class loading scheme as dev mode, it is likely related.

Yup, that's why I mentioned it :)

**Comment by stuartwdouglas** [comment]
Looks like gRPC has some dev mode issues. I will look at fixing them tomorrow.

**Comment by geoand** [comment]
Ack

**Comment by geoand** [comment]
@stuartwdouglas are you looking into the test failures or are you on something else and would like me to look into it?

**Comment by stuartwdouglas** [comment]
I got caught up with other stuff today, so if you want feel free. I think the issue is with how the gRPC tests are setup, I tried adding a gRPC dev mode test and it failed, but real dev mode seems to work fine when testing the quickstarts.

**Comment by geoand** [comment]
OK, I'll have a look

**Comment by geoand** [comment]
The problem comes down to the use of `EmptyProtos.Empty.newBuilder().build()` inside the test classes.

When that is done, the (generated) `com.google.protobuf.EmptyProtos.Empty` is loaded from the `Quarkus Runtime ClassLoader`, but inside its code it refers to `com.google.protobuf.GeneratedMessageV3` which is loaded from `Quarkus Base Runtime ClassLoader`.

Without this PR, `com.google.protobuf.EmptyProtos.Empty`  gets loaded from `Quarkus Base Runtime ClassLoader` (since there is no `Quarkus Runtime Classloader`) so tests pass without issue. 

This is a very obscure corner case and I wonder if we should just have a flag to fallback to the previous behavior that would only be used for `@QuarkusUnitTest`. WDYT?

**Comment by geoand** [comment]
I think I have a sort of lame solution to this. Will update soon

**Comment by geoand** [comment]
I have a fix, @stuartwdouglas would you like me to push into your branch?

**Comment by geoand** [comment]
I pushed the commit, feel free to make changes if you deem necessary

**Comment by geoand** [comment]
I pushed another update but there is still one test failure: `GrpcHealthTest`. The problem with this one seems to be pretty much the same, but because for that case the CL issue is for generated application classes (not test) classes, I am not sure what the proper way to deal with it is.

**Comment by geoand** [comment]
I pushed a hacky fix, that I don't really like, but I don't know if there are any better options at this point...

This PR now needs a rebase, @stuartwdouglas do you want to perform it or do you want me to?

**Comment by stuartwdouglas** [comment]
I wonder if this is worth doing? The potential benefits are likely minimal, and it feels wrong to change the ClassLoading model based on this.

**Comment by geoand** [comment]
Yeah I understand the point. How about we leave it as is and take another look at it if users start reporting slow test execution?

**Comment by stuartwdouglas** [comment]
Sounds good to me.

**Pull request closed without merging**
