### PR TITLE
Make SecurityCheckStorage bean unremoveable

### LINKED ISSUE #28732: Weird problem when using interface + class for JAX-RS Resources + Auth
### Describe the bug

When using interfaces with JAX-RS annotations plus classes without those annotations + `@RolesRequired`, there seems to be a weird problem.

Logs:
```
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: io.quarkus.resteasy.reactive.server.runtime.security.EagerSecurityHandler.handle(EagerSecurityHandler.java:62)
Required type: interface io.quarkus.security.spi.runtime.SecurityCheckStorage
Required qualifiers: [@javax.enterprise.inject.Default()]
Removed beans:
	- SYNTHETIC bean  [types=[interface io.quarkus.security.spi.runtime.SecurityCheckStorage], qualifiers=null]
Solutions:
	- Application developers can eliminate false positives via the @Unremovable annotation
	- Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
	- See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
	- Enable the DEBUG log level to see the full stack trace
================================================================================

2022-10-21 00:55:21,948 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /hello failed, error id: 04032c56-8cb1-4a3b-a007-a0cd2c01db5c-1: java.lang.NullPointerException: Cannot invoke "io.quarkus.security.spi.runtime.SecurityCheckStorage.getSecurityCheck(io.quarkus.security.spi.runtime.MethodDescription)" because the return value of "io.quarkus.arc.InstanceHandle.get()" is null
	at io.quarkus.resteasy.reactive.server.runtime.security.EagerSecurityHandler.handle(EagerSecurityHandler.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:124)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:142)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:51)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:18)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:8)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:117)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:100)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:233)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:225)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2$1.onItem(HttpSecurityRecorder.java:137)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2$1.onItem(HttpSecurityRecorder.java:127)
```
This problem can be kinda solved by adding this bean to the unremovable beans list by config. 
But, by doing so, any JAX-RS custom exception mappers for Forbidden and Unauthorized seem to stop working.

### Expected behavior

Requests with correct Auth return 200.
Requests with invalid Auth return 401, using custom JAX-RS exception mapper.
Requests without necessary roles return 403, using custom JAX-RS exception mapper.

### Actual behavior

All requests return 500.

After adding the bean to the unremovable list,

Requests with correct Auth return 200.
Requests with invalid Auth return 401, using default response.
Requests without necessary roles return 403, using default response.

### How to Reproduce?

https://github.com/davidfrickert/quarkus-resteasy-reactive-resource-interfaces-auth
Run `GreetingResourceImplTest` (only contains the http status 500 case described)

### Output of `uname -a` or `ver`

Linux dfrickert 6.0.2-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Oct 15 18:49:52 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment (build 17.0.5+1) OpenJDK 64-Bit Server VM (build 17.0.5+1, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /opt/maven Java version: 17.0.5, vendor: N/A, runtime: /usr/lib/jvm/java-17-openjdk Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.0.2-3-manjaro", arch: "amd64", family: "unix"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #28732

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi @geoand, #28732 mentions that making the bean unremovable causes JAX-RS custom exception mappers for Forbidden and Unauthorized being ignored, I know @michalvavrik has added a few tests for the custom mappers, yeah, actually, I think Michal added the one for `AuthenticationFailedException`, but may be worth double checking

**Comment by michalvavrik** [comment]
There is already `io.quarkus.resteasy.reactive.server.test.security.CustomExceptionMapperTest` added by Georgios for Unauthorized that should do.

**Comment by geoand** [comment]
Now you folks confused me :).

Do we or do we not need to do anything else for this?

**Comment by michalvavrik** [comment]
The issue with reproducer is that RBAC annotations aren't inherited from interface, actual `hello` endpoint is on implementation `GreetingResourceImpl` and there they are not applied. I tried to add `ServerExceptionMapper` for `UnauthorizedException` and when you annotate implementation, it works. So, it's possible @davidfrickert misunderstood the situation (I am just guessing of course :-)).

**Comment by geoand** [comment]
That might be the case, but why is this bean not unremovable?

It seems very fishy to me that the proper functionality depends on the bean not being present...

**Comment by geoand** [comment]
An just to add to the previous comment, if what has been done here is problematic, why do no tests fail?

**Comment by davidfrickert** [comment]
> The issue with reproducer is that RBAC annotations aren't inherited from interface, actual `hello` endpoint is on implementation `GreetingResourceImpl` and there they are not applied. I tried to add `ServerExceptionMapper` for `UnauthorizedException` and when you annotate implementation, it works. So, it's possible @davidfrickert misunderstood the situation (I am just guessing of course :-)).

I suspected this was the case and in practice to solve my problem I just eliminated the interface.

I opened this issue to understand why they aren't inherited. This error is also a bit obscure.

**Comment by michalvavrik** [comment]
@davidfrickert agree. @geoand IMHO bean should be unremovable.

**Comment by sberyozkin** [comment]
Cool, so all is good

**Review by sberyozkin — APPROVED** [review]

**Comment by geoand** [comment]
So yeah, I agree the usage was not correct to begin with, and this fix only oncovers the real issue

**Comment by davidfrickert** [comment]
Thanks for the fix @geoand.

@michalvavrik @sberyozkin - about the RBAC annotations, why are they not inherited to the class, is that a limitation or on purpose? In any case, should it not be documented in the Quarkus Security guides? Like this one - https://quarkus.io/guides/security-openid-connect - for example.

About my problem with the exception mappers, it seems to actually be related to `quarkus.http.auth.policy` + `quarkus.http.auth.permission`. It seems that when using these configs, custom exception mappers are not executed. Is this expected?

**Comment by geoand** [comment]
> Thanks for the fix @geoand.

🙏🏼

**Comment by michalvavrik** [comment]
> @michalvavrik @sberyozkin - about the RBAC annotations, why are they not inherited to the class, is that a limitation or on purpose? In any case, should it not be documented in the Quarkus Security guides? Like this one - https://quarkus.io/guides/security-openid-connect - for example.

@davidfrickert 
It's Java EE annotation _Specifying it on a method means that it is applicable to that method only._  https://javaee.github.io/javaee-spec/javadocs/javax/annotation/security/RolesAllowed.html So to me it's clear, however I understand we can read it differently. I'd suggest you can create issue (or PR :-)) that request change of behavior or better docs. Could you kindly do that (you can mention me there)?

**Comment by michalvavrik** [comment]
ah @davidfrickert there is already one https://github.com/quarkusio/quarkus/pull/22540

**Comment by michalvavrik** [comment]
https://github.com/quarkusio/quarkus/issues/22530

**Comment by davidfrickert** [comment]
@michalvavrik Didn't check the annotation so that was my bad. But it's nice that there is already an issue and PR for it, thanks!

**Pull request merged**
