### PR TITLE
Allow Jackson configuration through properties

### LINKED ISSUE #18572: Allow Jackson configuration through properties
## Description

It would be nice to be able to configure the Jackson `ObjectMapper` through properties rather than having to create a class extending `ObjectMapperCustomizer`.

Rather than having to constantly map Quarkus-specific properties to Jackson properties, just allow free-form mapping within the properties that would "flow-through" to the underlying Jackson enum properties. Something like this:

| **Enum** | **Property** | **Values** |
| :----- | :-------- | :------ |
| `com.fasterxml.jackson.databind.DeserializationFeature` | `quarkus.jackson.deserialization.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.databind.SerializationFeature` | `quarkus.jackson.serialization.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.databind.MapperFeature` | `quarkus.jackson.mapper.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.core.JsonGenerator.Feature` | `quarkus.jackson.generator.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.core.JsonParser.Feature` | `quarkus.jackson.parser.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.annotation.JsonInclude.Include` | `quarkus.jackson.default-property-inclusion` | `always`, `non_null`, `non_absent`, `non_default`, `non_empty` |

This way, if/as new "things" are added to the enums, there isn't any work that needs to be done in the extension. As long as `<feature_name>` aligns with the enum constant, it would just map. 

I would envision these properties would be fixed at build time and not overridable at runtime. We'd have to decide what to do in the case that an application provides an `ObjectMapperCustomizer` and there are properties set. I would think that we would union the properties and what is defined in the `ObjectMapperCustomizer`. We'd have to figure out "who wins" in the situation where a property is set to one value and the customizer sets a different value for the same enum property. Don't property values specified in `application.properties`/`application.yml` always "win" over whats in the code?

   > Just a side note, I did get this idea from Spring and the [Spring documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.spring-mvc.customize-jackson-objectmapper) which allows for this. Its a very convenient feature to have that eliminates the need to write code.

### PR DESCRIPTION
**Pull request by edeandrea**
Allow Jackson configuration through properties.

**NOTE:** This does not require #24214. That could make this simpler. 

Closes #18572

### CODE REVIEW

**Comment by edeandrea** [comment]
@geoand Here's my attempt at #18572. I'm open to feedback.

**Comment by geoand** [comment]
I'm +0 about this really.

**Comment by edeandrea** [comment]
Why? It allows easier config of some build time properties without having to drop into custom code?

Is it the idea of it that you are +0 or the way I implemented it?

**Comment by geoand** [comment]
The idea

**Comment by geoand** [comment]
So your stalking me now 😂?

The reason I am not sure it's particularly useful is basically what Guillaume said. There is no easy way as a user to know what I can put in the map

**Comment by edeandrea** [comment]
> So your stalking me now 😂?

You can't hide from me (you should know that by now...) :D

> The reason I am not sure it's particularly useful is basically what Guillaume said. There is no easy way as a user to know what I can put in the map

I'm fine to go look things up in the documentation. The Javadoc comment right on the attribute mentions the enum class name containing the applicable keys. I could also update the applicable guide with this information as well and link to the Jackson Javadocs.

Plus. auto-completion in the IDE doesn't work for lots of other things. Think about reactive messaging - `mp.messaging.outgoing.<channel-nane>.*` properties. I find that many properties the auto-completion simply doesn't work.

See all these properties with squiggles? The IDE doesn't recognize them.

Screen Shot 2022-03-10 at 7 55 47 AM

**Comment by geoand** [comment]
In the case of reactive messaging, there really wasn't a choice... Here there is...
Also, that situation is going to be rectified.

Like I said above, although I understand where this is coming from, I don't think whataboutism is a wining argument.

I won't block this, but will abstain from approving

**Comment by edeandrea** [comment]
Wouldn't it be a similar argument for any config which is a `Map`? I would argue that because the key is an `enum` type that you'd have stronger type safety (if you want to call it that) vs a random `String`. (Yes I'm fully aware in this case that the actual `enum` type isn't the key - but it could be if #24214 was implemented).

Just trying to make an argument for less code is all. Isn't that one of the underpinnings of Quarkus in the first place? Less code? Is that a better argument than whataboutism :D ?

**Comment by geoand** [comment]
> Wouldn't it be a similar argument for any config which is a Map?

Yes and no. In all cases I am aware of, we use the map for configuration where the key a user provided name, that distinguishes something, like say a named datasource, or a reactive messaging channel.

In this work, this is not the case. What you use as the key really really matters.

**Comment by geoand** [comment]
> Is that a better argument than whataboutism :D ? 

It is :). But of course it does not aleviate the concerns already expressed.

I am definitely not against this, I just don't think it provides enough value. But if someone else thinks it does, I don't mind having this merged.

**Comment by edeandrea** [comment]
> But if someone else thinks it does, I don't mind having this merged.

How do we get any eyes on it to see if there's any interest (short of me tagging a handful of people directly - not sure that's the right thing to do).

**Comment by gsmet** [comment]
Frankly it would be far better to integrate useful configuration knobs in the Quarkus config rather than arguing endlessly about this. 

If you can think of useful knobs that makes sense in common cases (and please I’m not talking about all of them), add them to the Quarkus config. 

Otherwise you basically have the two maintainers of this extension saying that they are not really excited about this so maybe you can accept this is not the way we want to go.

**Comment by geoand** [comment]
Closing as per comments

**Pull request closed without merging**
