### PR TITLE
Drop the compatibility layer for the Big Reactive Rename

### PR DESCRIPTION
**Pull request by gsmet**
The change has been done in 3.9 and the deprecation will be in 3.15 LTS so we can now consider removing all this.

While our tendency would be to keep them forever, they come with a cost both in terms of size of BOM (which reflects in the build memory usage for all Quarkus projects), and in terms of config cost - we will reduce the number of interceptors quite a lot.

### CODE REVIEW

**Comment by gsmet** [comment]
Let's start with a draft as I might have left some tests around so let's catch them :).

**Comment by geoand** [comment]
+100 for this

**Comment by geoand** [comment]
The TCK failure of `JAXRSClient0012` is weird...

**Comment by gsmet** [comment]
@geoand I was having a look this morning. It was due to: https://github.com/gsmet/resteasy-reactive-testsuite/commit/762d369b9d9c85f7df3c8a0d6f308e59890c577a .

I chased all the test failures, it's now ready to go!

**Comment by geoand** [comment]
Awesome, thanks!

**Review by geoand — APPROVED** [review]
I obviously didn't review this, but I trust you and CI fully :)

**Pull request merged**
