### PR TITLE
Clarify type of container

### PR DESCRIPTION
**Pull request by nmcl**
Container in the Java world still has a close association with Java EE containers. So tried to make it clearer.

### CODE REVIEW

**Comment by gsmet** [comment]
I don't find it confusing with `Cloud native` just before `Container`.

@emmanuelbernard WDYT as you wrote this part?

**Comment by emmanuelbernard** [comment]
I think we should just align the messaging with what we have on quarkus.io, including the benefits.

**Comment by nmcl** [comment]
I disagree. Container still means Application Container to many people even in a cloud native world. Remember we have been talking about cloud native in the context of EAP and WildFly for years as have many other vendors, even before there were Linux Containers.

**Comment by nmcl** [comment]
One other thing: whilst today we're focussing on Linux Containers, there's a good chance we will need to consider heterogeneous operating systems eventually.

**Comment by nmcl** [comment]
@emmanuelbernard I agree we need to be consistent with whatever we have on quarkus.io. However, if that talks about Containers without at least giving an initial clarification of the type of container, i.e., NOT Application Container, I think we need to address there too.

**Comment by nmcl** [comment]
Note, for example: https://developer.ibm.com/articles/java-ee-jakarta-ee-microprofile-or-maybe-all-of-them/

Do a search for container ;)

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Got the same comment last week in Barcelona, worth indicating it's about Linux container.

**Pull request merged**
