### PR TITLE
Backport Ensure that ConfigBuilder classes work in native mode to 2.13

### LINKED ISSUE #32152: Quarkus 2.13 test extension tests fail with the 22.3 mandrel builder image and
### Describe the bug

The integration tests fail with the 22.3 mandrel builder image. Filing this for tracking purposes:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.extension.ClasspathInGraalITCase
Executing "/home/runner/work/mandrel/mandrel/quarkus/integration-tests/test-extension/tests/target/quarkus-integration-test-test-extension-tests-999-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/runner/work/mandrel/mandrel/quarkus/integration-tests/test-extension/tests/target/quarkus.log -Dquarkus.log.file.enable=true"
Mar 25, 2023 2:19:24 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
java.lang.ClassNotFoundException: io.quarkus.extest.runtime.config.RunTimeConfigBuilder
	at java.base@17.0.6/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
	at java.base@17.0.6/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base@17.0.6/java.lang.ClassLoader.loadClass(ClassLoader.java:132)
	at io.quarkus.runtime.configuration.ConfigUtils.configBuilder(ConfigUtils.java:189)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:123)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Expected behavior

Test extension tests pass with the builder image.

### Actual behavior

Test throws `ClassNotFoundException` at boot.

### How to Reproduce?

Run integration tests extension tests with the 22.3 builder image.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

See https://github.com/graalvm/mandrel/actions/runs/4516801805/jobs/7955690955#step:11:1120

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #32152

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
I need to fix 2.13 CI. I will have a look at this this week-end.

**Comment by radcortez** [comment]
The failures in `ProviderConfigInjectionWarningsTest` are picking up an additional warning:

```console
WARN  [org.jbo.res.cli.jax.i18n] (Finalizer) RESTEASY004687: Closing a class org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine instance for you. Please close clients yourself.
```

I guess we also need https://github.com/quarkusio/quarkus/pull/31496.

**Comment by gsmet** [comment]
@radcortez yeah I have to backport a few CI fixes to older branches.

**Review by gsmet — APPROVED** [review]
CI is green enough.

**Pull request merged**
