### PR TITLE
Fix kafka-oauth-keycloak test on GraalVM 22.1

### PR DESCRIPTION
**Pull request by ozangunalp**
- Stop applying substitution for javax.security.auth.Subject after GraalVM 22.1
- Bump Keycloak container version to 16.1.1, remove certificate/keystore as they weren't used

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Review by sberyozkin — APPROVED** [review]
Nice cleanup with the certs/keystores :-), thanks for updating to 16.1.1

**Comment by geoand** [comment]
The CI failure is suspicious... Is the failing test known to be flaky?

**Comment by ozangunalp** [comment]
@geoand I am looking into it. If it wasn't flaky before it is now..

**Review by galderz — APPROVED** [review]

**Comment by ozangunalp** [comment]
The test is failing because of a redpanda container failing to start. I don't think it is related. 
For future reference the failure message is `sh: 1: /var/lib/redpanda/redpanda.sh: Text file busy`

**Comment by geoand** [comment]
Thanks @ozangunalp.

I'll restart CI just to be sure

**Pull request merged**
