### PR TITLE
Add first version of Keycloak admin client based on Reactive REST Client

### PR DESCRIPTION
**Pull request by geoand**
Alternative to https://github.com/quarkusio/quarkus/pull/24294 that requires a new Keycloak release

### CODE REVIEW

**Comment by cescoffier** [comment]
Wasn't the last release of keycloak enough?

**Comment by geoand** [comment]
It introduced the changes we needed. This is the new extension that uses the changes and leverages the Reactive REST Client under the hood

**Comment by cescoffier** [comment]
Ah ok, I misundertood.

**Review by cescoffier — DISMISSED** [review]
We would need to document that somewhere.
We also do not have any tests for the non-reactive version (I think @sberyozkin was working on that), but we would need some tests for this version. 

The rest looks great!

**Comment by geoand** [comment]
I added a couple mentions in the security docs.
Furthermore, it has already been mentioned in https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/resteasy-reactive-migration.adoc#keycloak-admin-client

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks @geoand

**Comment by geoand** [comment]
YW!

**Comment by sberyozkin** [comment]
Hi @geoand @cescoffier `integration-tests/keycloak-authorization` was the only one was using the non-reactive admin client - a few of OIDC integration tests were doing it it was slowing down the native builds as the admin client was bringing a lot of extra dependencies so in the end it was only `integration-tests/keycloak-authorization`  which was using it. This PR has changed it and now the reactive admin client is used - it is fine; 
I'll update one of other OIDC tests to use the non-reactive admin client for completeness with one of the next Keycloak related updates

**Comment by Foobartender** [comment]
Quick feedback: I tried it and got a 404 error. It tries to access the URL below, where the last path element ("roles") is duplicated:
http://localhost:9080/auth/admin/realms/myrealm/roles/roles?search=myrole&briefRepresentation=true

I'll look at it closer and create an issue as soon as I find the time.

**Comment by rvansa** [comment]
I wonder, can we expect a client that uses Mutiny in the API?

**Comment by geoand** [comment]
That's one for @sberyozkin and @pedroigor

**Pull request merged**
