### PR TITLE
JUnit support - disable observers declared on mocked beans

### LINKED ISSUE #11079: InjectMock does not work on observer method
**Describe the bug**
Mocking a bean with `@io.quarkus.test.junit.mockito.InjectMock` does not work for methods that use `@Observes`.
Example:
`public void onExampleEvent(@Observes ExampleEvent event) {...}`
This method is called when `ExampleEvent` is fired, even if the bean containing this method is mocked by using `@InjectMock`.
Hint: any other method of the same bean is mocked successfully.

**Expected behavior**
- observer methods of a mocked bean should not be called when event is fired

**Actual behavior**
- observer methods of a mocked bean are called when event is fired

**To Reproduce**
1. `git clone -b quarkus-observer-mock https://github.com/mickroll/demonstrator.git`
2. run `mvn clean install`

**Configuration**
none

**Screenshots**
none

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.959]
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
 - GraalVM version (if different from Java): /
 - Quarkus version or git rev: 1.6.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
the demonstrator was built similar to https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started-testing

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #11079

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Really nice!

**Comment by famod** [comment]
Awesome! Will take me some time to review/test this, so don't wait for me in case the others approve before me.

/cc @mickroll in case you want to try this out: clone this branch & run `mvn -Dquickly` & use 999-SNAPSHOT in our project

**Review by stuartwdouglas — APPROVED** [review]

**Comment by mkouba** [comment]
> /cc @mickroll in case you want to try this out: clone this branch & run mvn -Dquickly & use 999-SNAPSHOT in our project

I'd recommend to build quarkus with ` mvn clean install -T 1C -DskipTests -DskipITs -Dquickly`...

**Comment by famod** [comment]
> I'd recommend to build quarkus with ` mvn clean install -T 1C -DskipTests -DskipITs -Dquickly`...

Parallel build is flaky, especially for first time builds (see #10859) and `quickly` should also skip all tests, but yeah eveyone has his/her way. 😉

**Comment by mkouba** [comment]
Yep, this time we don't want to run the tests but build the quarkus as quick as possible ;-).

**Comment by mkouba** [comment]
The windows job got cancelled in 3h 1m 9s...  Is it expected to take so long?

**Comment by geoand** [comment]
Nope, it should finish in 2 (or close to that)

**Comment by mkouba** [comment]
Ok, so this time **JDK Java 14 JVM Gradle Tests**:
```
2020-08-03T15:11:24.3416664Z GrpcDevModeTest > main() FAILED
2020-08-03T15:11:24.3417128Z     org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.test.devmode.util.DevModeTestUtils that uses java.util.function.Supplier, java.util.function.Supplierjava.util.concurrent.atomic.AtomicReference, java.util.concurrent.atomic.AtomicReferencejava.lang.String, java.lang.Stringboolean was not fulfilled within 1 minutes.
2020-08-03T15:11:24.3417586Z         at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
2020-08-03T15:11:24.3418042Z         at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
2020-08-03T15:11:24.3418422Z         at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
2020-08-03T15:11:24.3418817Z         at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
2020-08-03T15:11:24.3419195Z         at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
2020-08-03T15:11:24.3419581Z         at io.quarkus.test.devmode.util.DevModeTestUtils.getHttpResponse(DevModeTestUtils.java:126)
2020-08-03T15:11:24.3419979Z         at io.quarkus.test.devmode.util.DevModeTestUtils.getHttpResponse(DevModeTestUtils.java:115)
2020-08-03T15:11:24.3420407Z         at io.quarkus.gradle.devmode.QuarkusDevGradleTestBase.getHttpResponse(QuarkusDevGradleTestBase.java:108)
2020-08-03T15:11:24.3421080Z         at io.quarkus.gradle.devmode.GrpcDevModeTest.testDevMode(GrpcDevModeTest.java:15)
```

I don't think it's related. Can anyone confirm my assumption?

**Comment by geoand** [comment]
Yes, that is totally unrelated.

@michalszynkiewicz seems like `io.quarkus.gradle.devmode.GrpcDevModeTest` is flaky.

**Comment by michalszynkiewicz** [comment]
@geoand thanks for letting me know. The weird thing is that it failed before any modifications have been made... 
Is it possible that gradle is not able to start dev mode in a minute?

**Comment by michalszynkiewicz** [comment]
also, have you seen this failure on any other PR?

**Comment by geoand** [comment]
I have seen gradle failures from time to time, but TBH I don't remember which class was causing them

**Comment by gsmet** [comment]
@michalszynkiewicz I confirm I have seen it in other pull requests.

**Comment by michalszynkiewicz** [comment]
@gsmet always for grpc?

**Comment by michalszynkiewicz** [comment]
@glefloch do you have some suspicions what may be the cause?

**Comment by mkouba** [comment]
@gsmet Are we safe to merge this PR?

Pls move the gradle CI discussion to a separate issue.

**Review by manovotn — APPROVED** [review]
Apologies for late review (PTO).
PR looks good.

**Comment by gsmet** [comment]
Yeah, failure looks unrelated.

Should this be backported to 1.7.0.Final or it's not worth it?

**Comment by glefloch** [comment]
Gradle tests are slow but I don't think they are as slow as taking a minute to start the devmode. There used to be issues on windows with some locks inside Gradle cache but not on Unix.

**Pull request merged**
