### PR TITLE
org.jboss.builder package rename to io.quarkus.builder

### PR DESCRIPTION
**Pull request by rsvoboda**
org.jboss.builder package rename to io.quarkus.builder

https://quarkusio.zulipchat.com/#narrow/stream/191168-core-team/topic/core.2Fbuilder.20and.20org.2Fjboss.2Fbuilder.20package/near/163182641

Sort of breaking change as this is fixing package name for stuff like `BuildStep` etc.

### CODE REVIEW

**Comment by rsvoboda** [comment]
hm, I have [INFO] Quarkus - Gradle Plugin IT ......................... FAILURE [  5.802 s] locally with weird message - Caused by: org.gradle.api.GradleException: Failed to build a runnable JAR

Caused by: java.io.FileNotFoundException: JAR entry META-INF/quarkus-config-roots.list not found in /Users/rsvoboda/git/quarkus/devtools/gradle-it/target/dependencies/io/quarkus/quarkus-undertow/999-SNAPSHOT/quarkus-undertow-999-SNAPSHOT.jar

let's see what happens on CI

**Comment by rsvoboda** [comment]
unzip -l /Users/rsvoboda/git/quarkus/devtools/gradle-it/target/dependencies/io/quarkus/quarkus-undertow/999-SNAPSHOT/quarkus-undertow-999-SNAPSHOT.jar | grep "META-INF/quarkus-config-roots.list" shows
```
       39  04-12-2019 14:49   META-INF/quarkus-config-roots.list
```

**Comment by rsvoboda** [comment]
CI passed, so I must have local env issue

**Review by gsmet — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
