### PR TITLE
Do not include the Kafka Dev UI beans during the native build

### LINKED ISSUE #33623: Regression - Unable to build native binary when using quarkus-kafka-client extension
### Describe the bug

See https://github.com/quarkusio/quarkus/issues/32968.
Steps to reproduce are the same.

Root cause differs for  released Quarkus versions and snapshot:
- `3.0.2.Final` / `3.0.3.Final` / `3.0.4.Final` / `3.1.0.CR1`
```
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.kafka.client.runtime.ui.KafkaUiUtils.<init>(io.quarkus.kafka.client.runtime.KafkaAdminClient, io.quarkus.kafka.client.runtime.ui.KafkaTopicClient, java.util.Map). This error is reported at image build time because class io.quarkus.kafka.client.runtime.ui.KafkaUiUtils_Bean is registered for linking at image build time by command line
```
- `999-SNAPSHOT` (2023-05-25)
```
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.netty.util.internal.logging.Log4J2Logger. This error is reported at image build time because class io.netty.util.internal.logging.Log4J2LoggerFactory is registered for linking at image build time by command line
```

See attached logs:
[kafka-client-3-0-2-final.log](https://github.com/quarkusio/quarkus/files/11572911/kafka-client-3-0-2-final.log)
[kafka-client-3-0-3-final.log](https://github.com/quarkusio/quarkus/files/11572912/kafka-client-3-0-3-final.log)
[kafka-client-3-0-4-final.log](https://github.com/quarkusio/quarkus/files/11572913/kafka-client-3-0-4-final.log)
[kafka-client-3-1-0-cr1.log](https://github.com/quarkusio/quarkus/files/11572914/kafka-client-3-1-0-cr1.log)
[kafka-client-999-snapshot.log](https://github.com/quarkusio/quarkus/files/11572915/kafka-client-999-snapshot.log)

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux 6.2.15-200.fc37.x86_64

### Output of `java -version`

openjdk 17.0.7 2023-04-18

### GraalVM version (if different from Java)

GraalVM 22.3.2.1-Final Java 17 Mandrel Distribution

### Quarkus version or git rev

3.0.2.Final, 3.0.3.Final, 3.0.4.Final, 3.1.0.CR1, 999-SNAPSHOT (2023-05-25)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #33623.

The funny thing is that it didn't happen when using reactive messaging...

### CODE REVIEW

**Comment by geoand** [comment]
Seems like the method needs to be broken up :)

**Comment by cescoffier** [comment]
Ok... something super weird.... looking...

**Comment by cescoffier** [comment]
I love when tests use features that should not be there...

**Review by geoand — COMMENTED** [review]
The change makes sense, but can we avoid the star imports?

**Comment by cescoffier** [comment]
@geoand  Missed it/them, fixed!

**Review by geoand — APPROVED** [review]

**Pull request merged**
