### PR TITLE
Bump Yasson from 1.0.9 to 1.0.10

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Should we include it in Dependabot?

**Comment by geoand** [comment]
Can we tell dependabot to only propose 1.x version updates?

**Comment by gsmet** [comment]
I think that's what https://github.com/quarkusio/quarkus/blob/main/.github/dependabot.yml#L135-L137 does.

**Comment by geoand** [comment]
Thanks! I'll take care of it

**Pull request merged**
