### PR TITLE
More specific error log for http/https port BindException

### PR DESCRIPTION
**Pull request by mattiaforc**
This PR makes the error log shown when a BindException is thrown be more specific and clear to the user. Previously, the logs suggested to check only the http port (i.e. the http port defined in the application.properties or a default of 8080) and showed commands to check which process was running on that port. This was confusing if the port that was already bound was the https one. 
I implemented a clearer way to handle this exception: 

- If the http traffic is disabled, the error log shows the https port
- If the http traffic is not disabled, but at least one of the `quarkus.http.ssl*` properties is defined, then the error logs shows both ports and prints commands to check them both
- If the http traffic is not disabled, and there is no `quarkus.http.ssl*`property defined, the error log shows the http port

### CODE REVIEW

**Comment by geoand** [comment]
Can you please rebase this onto `main` to pick up CI fixes?

@gastaldi mind reviewing this?

Thanks!

**Comment by mattiaforc** [comment]
Hi @geoand, yes, of course!
I just did that, let me know if there is anything else to do!

**Review by gastaldi — APPROVED** [review]
LGTM but I think these messages should be warnings instead of info. And also use `warnf` instead of concatenating Strings

**Comment by mattiaforc** [comment]
Hi @gastaldi, I followed your suggestions and updated the code. I squashed the previous commit and rebased onto main just to keep it updated. 
Thanks!

**Comment by gastaldi** [comment]
@mattiaforc thanks. You need to run `mvn process-sources` to format the code appropriately and make CI happy :)

**Comment by geoand** [comment]
> @mattiaforc thanks. You need to run `mvn process-sources` to format the code appropriately and make CI happy :)

And make sure to amend the changes to the commit 😉

**Comment by mattiaforc** [comment]
@gastaldi @geoand Done :)

**Review by gsmet — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
