### PR TITLE
update to MicroProfile Fault Tolerance 2.1 and SmallRye Fault Tolerance 4.1.0

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by gastaldi** [comment]
Looks like there is a failing test:
```

	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	... 60 more

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.049 s <<< FAILURE! - in io.quarkus.it.main.FaultToleranceITCase
[ERROR] testRetry  Time elapsed: 0.048 s  <<< ERROR!
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8081/ft

```

**Comment by gsmet** [comment]
Needs a rebase.

**Comment by Ladicek** [comment]
OK, got it failing locally, it seems it's only the native test that's failing, it seems to work just fine in JVM mode. I'll look into it.

**Comment by Ladicek** [comment]
Should be fixed now.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
