### PR TITLE
Small Kotlin fixes

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by gsmet** [comment]
Ah ah ah, I was writing a comment saying we should consider doing https://github.com/quarkusio/quarkus/issues/8713 :).

**Comment by geoand** [comment]
Haha, I'm already ahead of you :P

**Comment by geoand** [comment]
Taking out of draft since CI passed on my fork.

**Comment by gsmet** [comment]
@geoand I reckon the original issue is not fixed though?

**Comment by geoand** [comment]
Which is the original issue?

**Comment by gsmet** [comment]
This one: https://github.com/quarkusio/quarkus/issues/8708

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
Yeah, that one hasn't been fixed, there is an issue with kotlinc containing non compatible version of classes

**Pull request merged**
