### PR TITLE
Add quarkus-caffeine as a dependency of quarkus-camel-core

### LINKED ISSUE #1670: quarkus-caffeine should be part of the camel-core dependencies
Otherwise, you end up with the following error when executing a native image:
```
2019-03-25 12:31:29,479 INFO  [io.qua.cam.cor.run.CamelRuntime] (main) Apache Camel  (CamelContext: camel-1) is starting
java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SILMS
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3043)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3039)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:926)
	at org.apache.camel.support.LRUCache.<init>(LRUCache.java:145)
	at org.apache.camel.support.LRUCache.<init>(LRUCache.java:113)
	at org.apache.camel.support.LRUSoftCache.<init>(LRUSoftCache.java:67)
	at org.apache.camel.support.LRUSoftCache.<init>(LRUSoftCache.java:63)
	at org.apache.camel.support.LRUSoftCache.<init>(LRUSoftCache.java:59)
	at org.apache.camel.support.LRUCacheFactory.newLRUSoftCache(LRUCacheFactory.java:156)
	at org.apache.camel.component.properties.PropertiesComponent.<init>(PropertiesComponent.java:69)
	at io.quarkus.camel.core.runtime.CamelRuntime.createPropertiesComponent(CamelRuntime.java:154)
	at io.quarkus.camel.core.runtime.CamelRuntime.doStart(CamelRuntime.java:90)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at io.quarkus.camel.core.runtime.CamelTemplate.start(CamelTemplate.java:35)
	at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask6.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:93)
	at io.quarkus.runtime.Application.run(Application.java:198)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SILMS
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at java.lang.ClassLoader.loadClass(Target_java_lang_ClassLoader.java:127)
```

### PR DESCRIPTION
**Pull request by gsmet**
This issue is hidden by the fact that the main Camel test is in the main IT. It was reported by a user trying to play with camel-core.

I had to reformat one of the pom but I did it in a separate commit.

Fixes #1670.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
This needs a rebase

**Comment by davsclaus** [comment]
Just a heads-up that we are working on making caffeine optional in future Camel releases
https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13363

**Comment by gsmet** [comment]
@davsclaus OK, cool, please ping us when done so that we can remove the dependency (or configure Camel to use it if it's deemed more optimized).

**Review by oscerd — APPROVED** [review]
LGTM, just need to be rebased.

**Comment by oscerd** [comment]
Once this is merged we may need to remove quarkus-caffeine from camel integration tests, like here:

https://github.com/quarkusio/quarkus/blob/master/integration-tests/camel-aws-s3/pom.xml#L40

**Comment by gsmet** [comment]
@oscerd rebased and removed the dependency from the tests (I looked into the other Camel modules but missed the ITs).

**Review by Sanne — APPROVED** [review]

**Pull request merged**
