### PR TITLE
Update SmallRye Config to 3.5.1

### LINKED ISSUE #37461: Service binding doesn't work as SERVICE_BINDING_ROOT expression is not expanded
### Describe the bug

Service binding doesn't work as mounted secret is never found as file because config expression is not expanded.
Problem was brought in when trying to fix other problem by this PR: https://github.com/quarkusio/quarkus/pull/34792

### Expected behavior

Service binding works.

### Actual behavior

Service binding in OCP 4.14 and 4.11 binds secret in following fashion:

```
...
Environment:
  SERVICE_BINDING_ROOT:        /bindings
Mounts:
  /bindings/app-postgresql from app-postgresql (rw)
...
```

and application never starts with:

```
15:13:04,436 Service Binding root '/deployments/${SERVICE_BINDING_ROOT:}' does not exist
```

I put some logging to `io.quarkus.kubernetes.service.binding.runtime.KubernetesServiceBindingConfigSourceFactory#getConfigSources(io.smallrye.config.ConfigSourceContext)` and got:

```
...
17:29:36,283 INFO  [app] source io.smallrye.config.ConfigSourceContext$ConfigSourceContextConfigSource key SERVICE_BINDING_ROOT val /bindings
...
```

### How to Reproduce?

Steps to reproduce:

0. be logged in OpenShift, have installed Service Binding and Crunchy PG operator and your user must have rights to list csv etc. (in short, for reproducer only you can use cluster admin)
1. `git clone git@github.com:michalvavrik/quarkus-test-suite.git`
2. `cd quarkus-test-suite/service-binding/postgresql-crunchy-classic`
3. `git checkout feature/fix-and-enable-crunchy-sb-tests`
4. `mvn clean verify -Dopenshift`

### Output of `uname -a` or `ver`

Fedora 38

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+9

### Quarkus version or git rev

999-SNAPSHOT,

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

I have a fix.

### LINKED ISSUE #37577: @ConfigMapping with Optional values does not load values when inheriting interface
### Describe the bug

1. Consider a configuration interface annotated with @ConfigMapping that inherits from another interface, such as https://github.com/fire2/quarkus-bug-configmapping/blob/main/src/main/java/org/config/Configuration.java. Define the config properties as `Optional`: https://github.com/fire2/quarkus-bug-configmapping/blob/main/src/main/java/org/config/MarketConfig.java 
2. Provide proper values for the config in `application.yaml`: https://github.com/fire2/quarkus-bug-configmapping/blob/main/src/main/resources/application.yaml 

The config values do not load, all the Optionals are empty, although there are valid values in `application.yaml`. 

### Expected behavior

The config values are loaded correctly and the optionals are not empty. This works fine when they are defined directly in the annotated interface. It also worked fine in Quarkus 2.15.3.Final. 

### Actual behavior

Optionals are empty. 

### How to Reproduce?

1. Clone https://github.com/fire2/quarkus-bug-configmapping/tree/main
2. Run https://github.com/fire2/quarkus-bug-configmapping/blob/main/src/test/java/org/config/ConfigurationTest.java 

### Output of `uname -a` or `ver`

Darwin LMUCM902989 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64 i386 Darwin

### Output of `java -version`

openjdk 17.0.7 2023-04-18 LTS OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.6.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

### Additional information

_No response_

### LINKED ISSUE #37641: Maps in ConfigMappings, that reference other ConfigMappings
### Describe the bug

When I define two ConfigMappings, where one references the other, maps are only parsed into one of the two config objects. 

The same works for primitives, lists and nested config interfaces.

### Expected behavior

Both config objects injected in the application contain equal value in their maps. 

### Actual behavior

One of the two configs only contains an empty map. It is not consistent which one. At least I could not find a pattern. 

### How to Reproduce?

I created a small [reproducer](https://github.com/nicolaideffremo/QuarkusConfigMappingReproducer) 

There are a few tests comparing the configuration values between the plain config and and another one referencing the plain config.   

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 LTS

### Quarkus version or git rev

3.6.1, but also tested with 3.2.9.Final, 2.16.9.Final and 2.13.9.Finall

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

_No response_

### LINKED ISSUE #37747: Native Build vs. Runtime Profiles Mismatch and Doubled-Up Using Parent Profile
### Describe the bug

Performing a native build using `mvn package -Pnative -Dquarkus.profile=prod,kubernetes` seems to add the parent profile and doubles it when running.

It seems to be related to profiles that have a `parent` profile because running single profiles does not produce the warning.

As far as I can recall this only started recently because we have not seen the warning before in the logs.

```
2023-12-14 09:50:53,973 WARN  [io.qua.run.con.ConfigRecorder] (main) The profile '[kubernetes, cluster, prod]' used to build the native image is different from the runtime profile '[kubernetes, cluster, prod, cluster]'. This may lead to unexpected results.
```

### Expected behavior

That the runtime would use the same profiles as build time and produce a message more like:
`2023-12-14 10:04:17,979 INFO  [io.quarkus] (main) Profile prod activated.`)`

### Actual behavior

A warning on startup appears when a profile seems to use a parent profile.

```
2023-12-14 09:50:53,973 WARN  [io.qua.run.con.ConfigRecorder] (main) The profile '[kubernetes, cluster, prod]' used to build the native image is different from the runtime profile '[kubernetes, cluster, prod, cluster]'. This may lead to unexpected results.
```

### How to Reproduce?

**To get the warning:**
1. `mvn package -Pnative -Dquarkus.profile=prod,kubernetes`
2. Run the generated native executable in the target folder.
3. Has the warning

**Not getting the warning:**
1. `mvn package -Pnative -Dquarkus.profile=prod`
2. Run the generated native executable in the target folder.
3. No warning (`2023-12-14 10:04:17,979 INFO  [io.quarkus] (main) Profile prod activated.`)

[code-with-quarkus2.zip](https://github.com/quarkusio/quarkus/files/13674965/code-with-quarkus2.zip)

### Output of `uname -a` or `ver`

ubuntu

### Output of `java -version`

17

### Quarkus version or git rev

3.6.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9

### Additional information

It is not harming anything just appears in our logs

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes https://github.com/quarkusio/quarkus/issues/37747
- Fixes https://github.com/quarkusio/quarkus/issues/37641
- Fixes https://github.com/quarkusio/quarkus/issues/37577
- Fixes https://github.com/quarkusio/quarkus/issues/37461

These are significant changes in the SR Config implementation, including a complete rewrite of the `@ConfigMapping` implementation to be fully build-time aware.

Used `config-quickstart` to measure improvements with Java 17 Temurin and Graal 22.3 - Java 17:

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

  | JVM RSS | Native RSS | JVM Start | Native Start
-- | -- | -- | -- | --
3.6.3 | 148621 | 23782 | 0.641 | 0.019
#37794 | 144970 | 22915 | 0.601 | 0.016
Diff to 3.6.3 | -2.52% | -3.78% | -6.59% | -20.25%

</google-sheets-html-origin>

Some corner case mappings may not work, due to the major implementation changes. This is not intended, and I'll fix those if they show up. The changes were made to retain 100% compatibility with the old implementation. There are likely cases we are not covering in our tests, hence the warning.

Due to a change triggered by https://github.com/quarkusio/quarkus/issues/35410, the config file loader now looks for any associated extension in the loader (if multiple available) https://github.com/smallrye/smallrye-config/pull/1026. This was causing issues with the Gradle plugin, which provided a custom loader implementation plus used the same ordinal for both `properties` and `yaml` files, which is not how Quarkus, and Maven order these sources. The Gradle plugin was adjusted to be consistent with ordering sources in other systems. Some Gradle users can notice configuration differences if they are mixing `properties` and `yaml` files.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Mind rebasing to get one more run on the latest main?

**Comment by radcortez** [comment]
> Mind rebasing to get one more run on the latest main?

Sure

**Comment by gsmet** [comment]
Amazing work @radcortez and thanks for the very detailed description.

**Comment by radcortez** [comment]
Thanks :)

Let's hope it doesn't cause too many regressions.

**Comment by vsevel** [comment]
> Due to a change triggered by https://github.com/quarkusio/quarkus/issues/35410,

what change exactly @radcortez ?

**Comment by radcortez** [comment]
This one: https://github.com/quarkusio/quarkus/issues/35410

**Pull request merged**
