### PR TITLE
Update building-native-image.adoc: Replace -Dnative with -Pnative

### PR DESCRIPTION
**Pull request by HannahArndt**
I struggled with this tutorial yesterday (it continued to produces .jars) until I had a look at this other guide (https://access.redhat.com/documentation/en-us/red_hat_build_of_quarkus/2.2/guide/819fc552-29b3-4659-b0d3-4c96418be718) where it says `-Pnative` instead of `-Dnative` which then worked for me.

In my understanding the native **profile** needs to be activated, so `-P` actually makes more sense.
I have only tested the multistage Dockerfile, but I assume it should say `-P` in all cases.

Let me know, if I misunderstood something.

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
No, it should actually be `-Dnative`.

You don't have an `<activation>` block in the profile? If not how did you generate your project?

**Comment by HannahArndt** [comment]
No, I added the following profile verbatim from the tutorial to my pom.xml in the `<profiles>` section:
```xml
<profiles>
    <profile>
        <id>native</id>
        <properties>
            <quarkus.package.type>native</quarkus.package.type>
        </properties>
    </profile>
</profiles>
```
I don't know how the project was generated, it was an existing project.
Is there another change I should have done to the project in order to build a native executable?

**Comment by geoand** [comment]
The `profiles` section that is added for projects created by our tooling is:

```xml
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <properties>
        <skipITs>false</skipITs>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
```

So `-Dnative` as the docs suggest is correct

**Comment by geoand** [comment]
I see that you are viewing the documentation a very old version of Quarkus.

**Comment by HannahArndt** [comment]
ok,
- good news: it did work with the new <profile> and `-Dnative`
- bad news: I'm pretty shure I got the outdated <profile> from the current guide at https://quarkus.io/guides/building-native-image
 
grafik
grafik

So I think this needs updating.
Would you rather have me editing this pull request (revert the previous commit, add a new commit with the updated profile-section) or close this PR and open a new PR with the updated profile?

**Comment by gsmet** [comment]
I will have a look.

**Comment by gsmet** [comment]
Thanks for raising this problem.

I instead fixed the `<profile>` section in the doc to make it consistent with the projects we generate: https://github.com/quarkusio/quarkus/pull/39530 .

In general, we recommend to generate your projects using our tooling.

**Pull request closed without merging**
