### PR TITLE
Add neo4j testcontainers entry to the BOM

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by gsmet** [comment]
So this is related to a discussion we had with @aloubyansky recently. If this is required, maybe we shouldn't add test containers to the bom to begin with and let people select their own version.

We could move it to the build parent. Except if we plan to have an artifact publicly exposing it?

**Comment by geoand** [comment]
Well, I added this because we wanted to use neo4j from testcontainers in the quickstarts

**Comment by aloubyansky** [comment]
I'd say unless there is a reason (e.g. compatibility related) to use a specific version of a dependency for Quarkus apps, we shouldn't be adding such dependencies to our BOMs.

**Comment by geoand** [comment]
So should we completely remove testcontainers from the runtime bom and only add it to the build-parent?

That way the quickstarts will have to pick their own version as well, which I am perfectly fine with.

**Comment by gsmet** [comment]
I think that would be the safe thing to do. We included too many test dependencies in the bom IMHO.

But we need to check testcontainers is not exposed as a public dependency first. Because if so, it has to be in the bom.

We will also need a breaking change label and a note in the migration guide.

**Comment by geoand** [comment]
Sounds good to me. I'll close this PR and open a new one.

**Pull request closed without merging**
