### PR TITLE
Do not generate Kubernetes resources in dev mode

### PR DESCRIPTION
**Pull request by gsmet**
Creating as draft for now to get proper CI coverage.

/cc @Sgitario

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by Sgitario** [comment]
Do you mean to configure the Vanilla, OpenShift, Kind, Knative... processors with the `@BuildStep(onlyIfNot = { IsTest.class, IsDevelopment.class })` annotation at class level? 

If so, I think it makes sense to me.

**Comment by gsmet** [comment]
Yes, exactly.

**Comment by gsmet** [comment]
@Sgitario I took a step back this morning and I think this won't fly: don't we have the ability to deploy to a Kubernetes cluster in the Dev UI? If so, I suspect we need the resources to be generated, right?

**Comment by Sgitario** [comment]
> @Sgitario I took a step back this morning and I think this won't fly: don't we have the ability to deploy to a Kubernetes cluster in the Dev UI? If so, I suspect we need the resources to be generated, right?

To be honest, I don't have idea and also I could not find anything relevant in any guides.

**Comment by iocanel** [comment]
@gsmet: besides the deployment from DevUI I think that we also regenerated the manifests each time we updated application.properties. BTW, I can't get it to work right now, so its either broken or my memory deceives me. 

@geoand didn't you implemented that yourself ?

**Comment by geoand** [comment]
I don't remember at all unfortunately

**Comment by gsmet** [comment]
Closing as it's either a dead end or requiring a lot more work.

**Pull request closed without merging**
