### PR TITLE
portable banner

### PR DESCRIPTION
**Pull request by maxandersen**
after lots of back and forth I'm saying we go for banner that only uses ascii chars as otherwise non-US windows users using gradle will get blank or weird characters.

included banner here is more portable and smaller than the competition :)

### CODE REVIEW

**Comment by maxandersen** [comment]
Screenshots from both osx and windows.

**Comment by maxandersen** [comment]
ignore the WAZZUP in the screenshot :)

**Comment by geoand** [comment]
Looks good to me.

So should we merge and be done with it?

**Comment by maxandersen** [comment]
@geoand sounds good to me, will you +1 review it ? :)

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Done :)

**Pull request merged**
