### PR TITLE
Bump GraalVM and Mandrel version to 22.1

### LINKED ISSUE #25199: Upgrade to GraalVM 22.1
### Description

> It brings developer experience improvements, Apple Silicon builds, a brand new `TruffleStrings` implementation, and more.

More details [here](https://medium.com/graalvm/graalvm-22-1-developer-experience-improvements-apple-silicon-builds-and-more-b7ac9a0f6066)

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
Closes #25199

Openning as Draft till CI runs on my fork

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
The svm thing is a bit concerning but let's get this in.

Does it make sense to push the envelope a bit and backport it to 2.9?

**Comment by jorsol** [comment]
> The svm thing is a bit concerning but let's get this in.
> 
> Does it make sense to push the envelope a bit and backport it to 2.9?

Yes, it make sense to backport it to 2.9, GraalVM 22.0.0.2  might affected by the [Java ECDSA Signature Vulnerability](https://github.com/quarkusio/quarkus/discussions/25252) so if CI pass with all the battery of tests that Quarkus has, then it's a sane choice.

We are already using GraalVM 22.1 with Quarkus 2.8.2 and it compiles fine for our use case (through we haven't extensively tested it yet) and having an official support by Quarkus it will give us more confidence to use it.

Also, the `svm` thing is annoying but there are two dependencies used, the `org.graalvm.nativeimage:svm` which Oracle don't want to release the artifact for newer versions, and `org.graalvm.sdk:graal-sdk` which is still being updated, so here I would say that at least the `graal-sdk` must be updated since it's also affected by a security issue: https://security.snyk.io/vuln/SNYK-JAVA-ORGGRAALVMSDK-2767964

**Comment by gsmet** [comment]
That makes sense: @zakkak we should probably have a specific version for `svm` and keep updating the SDK. Providing it works, which might become a problem at some point unfortunately.

**Comment by zakkak** [comment]
> That makes sense: @zakkak we should probably have a specific version for `svm` and keep updating the SDK. Providing it works, which might become a problem at some point unfortunately.

ACK, that makes sense.

For some context though let me clarify that the only reason Quarkus depends on `org.graalvm.nativeimage:svm` and `org.graalvm.sdk:graal-sdk` is for `javac` to not complain when compiling code referencing the corresponding APIs, the actual implementations of the APIs are only accessed during native image build in which case it uses the implementations provided by the corresponding GraalVM or Mandrel. As a result no matter the version we define in the pom.xml files the implementation that will be used depends on the GraalVM or Mandrel version actually being used when building the native image, which also allows us to be able to build Quarkus applications with different GraalVM/Mandrel applications without needing to change the `graal-sdk.version` property

**Pull request merged**
