### PR TITLE
Upgrade to Infinispan 10.1.2.Final

### PR DESCRIPTION
**Pull request by karesti**
Upgrade to latest Infinispan release 10.1.2.Final

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
```
[INFO] Running io.quarkus.it.infinispan.client.InfinispanClientFunctionalityTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.904 s <<< FAILURE! - in io.quarkus.it.infinispan.client.InfinispanClientFunctionalityTest
[ERROR] io.quarkus.it.infinispan.client.InfinispanClientFunctionalityTest  Time elapsed: 0.904 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/infinispan/factories/scopes/Scopes
	at org.infinispan.commands.module.TestModuleLifecycle$GlobalFactoryComponentAccessor.<init>(TestModuleLifecycle.java:126)
	at org.infinispan.commands.module.TestModuleLifecycle.registerDynamicMetadata(TestModuleLifecycle.java:46)
	at org.infinispan.manager.ModuleRepository$Builder.build(ModuleRepository.java:95)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:265)
	at org.infinispan.test.fwk.TestCacheManagerFactory.newDefaultCacheManager(TestCacheManagerFactory.java:70)
	at org.infinispan.test.fwk.TestCacheManagerFactory.createCacheManager(TestCacheManagerFactory.java:315)
	at io.quarkus.it.infinispan.client.InfinispanServerTestResource.start(InfinispanServerTestResource.java:22)
	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:45)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:178)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:207)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ClassNotFoundException: org.infinispan.factories.scopes.Scopes
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 47 more
```

**Comment by karesti** [comment]
@gsmet there is a job failing and I can't relaunch

**Comment by gsmet** [comment]
I hit the button but it wasn't working so I rebased and force pushed. CI is running now.

**Comment by geoand** [comment]
I tried to restart the tests again because CI seems to be misbehaving...

**Comment by karesti** [comment]
@wburns @gsmet green!!

**Comment by karesti** [comment]
Updated to 10.1.2.Final

**Review by gsmet — APPROVED** [review]

**Comment by gwenneg** [comment]
There's an exception during the `infinispan-client` native tests:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.417 s <<< FAILURE! - in io.quarkus.it.infinispan.client.InfinispanClientFunctionalityInGraalITCase
[ERROR] io.quarkus.it.infinispan.client.InfinispanClientFunctionalityInGraalITCase  Time elapsed: 2.411 s  <<< ERROR!
org.junit.platform.commons.JUnitException: Quarkus native image start failed, original cause: java.lang.IllegalStateException: Configuration already registered for the given class loader
```

Considering this seems related to the class loader, maybe a rebase on master would help since your branch is one week old and several class loading issues were fixed on master recently.

**Comment by gastaldi** [comment]
@karesti can you squash your commits into a single one? Thanks!

**Comment by gastaldi** [comment]
Also it seems there are formatting issues with the infinispan tests. Run `mvn process-sources` to fix that

**Comment by karesti** [comment]
@gastaldi I squashed the commits. However I have run `mvn process-sources` in all the project but I did not get any file change.

**Comment by gastaldi** [comment]
Weird, well let's see how CI behaves now, thanks!

**Comment by gastaldi** [comment]
There is an error while running the Infinispan tests:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.infinispan.client.InfinispanClientFunctionalityInGraalITCase
Feb 16, 2020 2:17:30 AM org.infinispan.registry.impl.InternalCacheRegistryImpl registerInternalCache
WARN: ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
Feb 16, 2020 2:17:30 AM org.infinispan.factories.GlobalComponentRegistry preStart
INFO: ISPN000128: Infinispan version: Infinispan 'Turia' 10.1.2.Final
Feb 16, 2020 2:17:31 AM org.infinispan.lock.impl.ClusteredLockModuleLifecycle cacheManagerStarted
INFO: ISPN029009: Configuration is not clustered, clustered locks are disabled
Feb 16, 2020 2:17:31 AM org.infinispan.transaction.lookup.GenericTransactionManagerLookup useDummyTM
INFO: ISPN000104: Using EmbeddedTransactionManager
Feb 16, 2020 2:17:31 AM org.infinispan.server.hotrod.test.HotRodTestingUtil startHotRodServer
INFO: Start server in port 11232
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.062 s <<< FAILURE! - in io.quarkus.it.infinispan.client.InfinispanClientFunctionalityInGraalITCase
[ERROR] io.quarkus.it.infinispan.client.InfinispanClientFunctionalityInGraalITCase  Time elapsed: 2.061 s  <<< ERROR!
org.junit.platform.commons.JUnitException: Quarkus native image start failed, original cause: java.lang.IllegalStateException: Configuration already registered for the given class loader

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   InfinispanClientFunctionalityInGraalITCase » JUnit Quarkus native image start ...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by karesti** [comment]
@gastaldi yes, at a point I was rebasing because of the class loading changes expecting to get fixed alone haha I will have a closer look with @wburns today

**Comment by dmlloyd** [comment]
#7335 may help.

**Comment by karesti** [comment]
Greeeeen!!! 👏🏻👏🏻👏🏻👏🏻 @gsmet @gastaldi :)))))

**Comment by gsmet** [comment]
OK, let's merge it before it gets red again :).

**Comment by geoand** [comment]
🎉

**Pull request merged**
