### PR TITLE
More diagnostic output when checking for proper docker setup

### PR DESCRIPTION
**Pull request by famod**
Should aid with cases like #14892.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by famod** [comment]
@gsmet I suppose you cancelled the workflow to free up resources for the backport stuff? I yes I'll re-trigger tomorrow.

**Comment by geoand** [comment]
Yeah, that's exactly what Guillaume had to do in order to ensure that the release will go smoothly.

We can re-start the jobs tomorrow as per his email

**Comment by famod** [comment]
Must.check.mailing.list.more.often!

**Pull request merged**
