### PR TITLE
Fix typos in extensions/qute

### PR DESCRIPTION
**Pull request by marcwrobel**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
@marcwrobel if you plan to continue on this, maybe create a pull request with several commits in it instead? I'm talking for the next ones if more are coming, I'll merge the ones you already created.

**Comment by marcwrobel** [comment]
@gsmet ok. And sorry for the inconvenience, I was testing gitpod and got caught with the simplicity of this tool to create PR ;).

**Comment by gsmet** [comment]
@jeanphibaconnais see, people are liking your Gitpod work :)

**Comment by jeanphibaconnais** [comment]
@gsmet oh Great !!! 😃 Thanks for the ping

**Pull request merged**
