### PR TITLE
Fix Gradle test-fixtures class loading issues

### LINKED ISSUE #11318: Gradle Test fixtures do not work when Running Unit tests with IntelliJ
**Describe the bug**
This issue is related to #11144. So in #11144 test-fixtures started working when running tests with Gradle from command line, thank you for fixing that.

When running Unit tests from IDE with IntelliJ runner the problem still exists. It looks like test fixtures are really annoying little feature. :)

```
java.lang.RuntimeException: java.io.UncheckedIOException: Error while reading file as JAR: /Users/anzes/prototype-dev/quarkus-test-fixtures-reproducible/build/libs/quarkus-test-fixtures-reproducible-my-version.jar
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:508)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:358)
...
Caused by: java.io.FileNotFoundException: /Users/anzes/prototype-dev/quarkus-test-fixtures-reproducible/build/libs/quarkus-test-fixtures-reproducible-my-version.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
```

I updated my reproducer to 1.7.0.Final: https://github.com/asodja/quarkus-test-fixtures-reproducer

**Expected behavior**
Test passes.

**Actual behavior**
Test fails, exception is thrown.

**To Reproduce**
1. git clone git@github.com:asodja/quarkus-test-fixtures-reproducer.git
2. Open in IntellIj and set Gradle: Build and run using: IntelliJ IDEA and Run tests using: IntelliJ IDEA
3. Run MyResourceTest, it fails with exception

**Environment (please complete the following information):**
- Output of uname -a or ver: MacBook Pro, Darwin Kernel Version 19.5.0
- Output of java -version: openjdk version "1.8.0_242"
- Quarkus version: 1.7.0.Final
- Build tool: Gradle 6.5.1
- IntelliJ: Build #IC-202.6397.94 (Community Edition)

### PR DESCRIPTION
**Pull request by asodja**
Fixes Classloader issues from #11318 for test fixtures.

It looks like dependencies are not correctly collected when test-fixtures are used, since they have same coordinates as main artifact and app dependencies are collected as a map of `Map<ArtifactCoords, Dependency> appDependencies`. 

So this fix also takes into account classifier when it's generating `ArtifactCoords`.

Alternative is, to use `Map<ArtifactCoords, List<Dependency>> appDependencies` and not classifier, but I think classifier solution is better.

### CODE REVIEW

**Comment by aloubyansky** [comment]
The classifier surely makes sense. As well as the type. The formatting check failed though. @asodja make sure you run `mvn clean package` before committing. It will autoformat the sources.

**Review by glefloch — COMMENTED** [review]
Yes I agree with @aloubyansky, adding the classifier make sense and looks better than having a `Map<ArtifactCoords, List<Dependency>> `

**Review by glefloch — APPROVED** [review]
LGTM

**Comment by asodja** [comment]
Latest commit also fixes jar issue when running from IDE. When running tests from IDE jvm arg "-Dorg.gradle.java.compile-classpath-packaging=true" is passed that forces that test-fixtures are packaged as jars. 

Docs:
https://docs.gradle.org/current/userguide/java_library_plugin.html#sub:java_library_known_issues_windows_performance

Unit tests in Gradle repo that makes sure that that works: https://github.com/gradle/gradle/blob/f8ea607a7dfe0f8715e3bf656df7414a415449b5/subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy#L57.

**Review by aloubyansky — APPROVED** [review]
Thanks a lot @asodja!

**Comment by asodja** [comment]
Thank you both.

**Pull request merged**
