### PR TITLE
Group resteasy classic extensions

### PR DESCRIPTION
**Pull request by ebullient**
It can be confusing to understand/remember (at a glance) that rest extensions in the tree belong to resteasy "classic" (only). Since resteasy-reactive and resteasy-classic cannot co-exist (and that extends down into the entire related extension set), this PR makes a directory for resteasy-classic extension and moves that related set into it... which IMO makes the either/or behavior more obvious.

### CODE REVIEW

**Comment by gsmet** [comment]
Hmmmm. Not sure it solves any problem at all tbh. I can see how things could be confusing in code.quarkus.io but I don't think this PR will change anything there?

But is it really confusing for people working in the code base?

I'm not -1 on this, just trying to understand what the real problem is. Because I would find it more important to properly group the extensions on code.quarkus.io and have extra clear extension names.

**Comment by geoand** [comment]
> But is it really confusing for people working in the code base?

I am pretty sure this is reason the PR was opened

**Comment by ebullient** [comment]
I'm trying to work on rest things in core right now.. and sifting through the pile of rest directories is.. annoying. And having to pause/remember that "no, this rest-client extension only apples to resteasy classic, I have to go into the resteasy-reactive directory to work on the rest client extension that works w/ resteasy-reactive" is an annoyance. 

@geoand is on board w/ this. It just applies to code, doesn't impact published artifacts. How we solve extension grouping is, indeed, a deeper problem.

**Comment by geoand** [comment]
Yeah, I think that it really makes sense to group things the way that is already done for RESTEasy Reactive. 
It makes it easier for people that casually have to work on this part of the codebase

**Comment by famod** [comment]
I'm +1 for more structure/cohesion, given those many extensions. Also makes it easier to work with `mvn -f/-pl` (alternatively, just let GIB do the work 😉).

But shouldn't the integration test modules mirror this structure?

**Comment by geoand** [comment]
> But shouldn't the integration test modules mirror this structure?

It could in a later phase. We haven't really done a lot

**Comment by ebullient** [comment]
The integration tests are generally pretty easy to sort out (and are usually scenario named) such that the flat lookup works ok (TBH, I prefer it). if anything, I could rename some of those: resteasy-classic-whatever, rather than tucking them all in a folder. 

The difference w/ extensions really is that there is a whole collection of extensions that are either/or in terms of usage/applicability.. and having one that was flat and the other grouped was making my brain hurt, especially as they are otherwise similarly named (and include things like -common).

**Comment by kenfinnigan** [comment]
+1 to this change, it will clean up the `/extensions` directory a lot, and also make it easier to ignore/activate entire swathes of extensions on the same topic.

I'd be in favor of doing similar things for the Amazon and Elytron extensions, possible others as well

**Comment by kenfinnigan** [comment]
Not a huge thing, but I just had a thought of whether the "resteasy-classic" directory actually needs a pom, or whether it can just be a directory and the extensions pom includes that directory in the path?

Prevents another module being created.

**Comment by famod** [comment]
With this aggregator/parent you can easily say `mvn -f extensions/resteasy-classic` to build everything related to RC. IDK if there is a need for this.
(And with Maven 4 you'll be able to use `-pl ...` because will be recursive then).

**Comment by gsmet** [comment]
Yeah I'm in favor of having a parent pom exactly for this reason.

**Comment by ebullient** [comment]
ok. is this a yes? or a no? or a sit here until it expires? or ..

**Review by gsmet — APPROVED** [review]
Let's merge it before we have too many conflicts.

**Pull request merged**
