### PR TITLE
Dev UI 2 - merge build steps and build items pages (not visible yet)

### PR DESCRIPTION
**Pull request by mkouba**
...into the build metrics page with tabs

### CODE REVIEW

**Comment by gsmet** [comment]
Aren't they already rendered as tabs?

I think @phillip-kruger had some work planned in this area.

**Comment by mkouba** [comment]
> Aren't they already rendered as tabs?
> 
> I think @phillip-kruger had some work planned in this area.

Build items was not visible at all. A link for build steps is in the menu on the left. This PR however turns the link on the left into Build metrics page which has two tabs - steps and links. The build steps tab is still missing the chart and dependency graph though (I believe that Phillip was working on this).

**Comment by phillip-kruger** [comment]
I have a PR in progress for this

**Comment by phillip-kruger** [comment]
I refactored the menu a bit, to also fix the url. My PR contains the fix for this and Continuous Testing.

**Comment by phillip-kruger** [comment]
I'll close here . Thanks though :)

**Pull request closed without merging**
