### PR TITLE
Replace oidc auth apple screenshots with generic ones

### LINKED ISSUE #42549: Remove references to Renarde in https://quarkus.io/guides/security-openid-connect-providers
### Description

The https://quarkus.io/guides/security-openid-connect-providers doc is about showing with some sample images, the typical process for registering an application with a given provider.

Originally, I copied a few of those images from Renarde docs. It can be causing the confusion that this is indeed how Renarde applications must be registered.

So this issue is about replacing images referencing Renarde with more neutral images

CC @Sanne 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by rghara**
Replace oidc auth apple screenshots with generic ones

 Related to #42549

### CODE REVIEW

**Comment by rghara** [comment]
Hi @sberyozkin,
Please do check the screenshots as I have only modified the existing ones to remove all trace from Renarde. Otherwise, I would have needed a developer subscription.

**Comment by sberyozkin** [comment]
Thanks @rghara , it is fine, but 2 commits with the same message are shown,  please have a single commit only. 
I believe that following with the X provider updates will resolve the issue 

Thanks

**Comment by rghara** [comment]
> Thanks @rghara , it is fine, but 2 commits with the same message are shown, please have a single commit only. I believe that following with the X provider updates will resolve the issue
> 
> Thanks

@sberyozkin Sure thing.

**Comment by rghara** [comment]
Closing this PR to create one with one commit based on reviewer's suggestion.

**Pull request closed without merging**
