### PR TITLE
Qute - ExtensionMethodGenerator now handles ClassCastException correctly

### LINKED ISSUE #7144: Qute Template Extension with multiple parameters: Resulting in endless wait without error
**Describe the bug**
I'm trying to create a Qute template extension with multiple parameters as described here: https://quarkus.io/guides/qute-reference#method-parameters

When using a method with a single parameter all is working well, when I add a second parameter in the template extension method, it results in an endless loop in the browser.

I tried setting the default logger to DEBUG, but nothing gets logged (see log under "actual behavior"). I also tried to set a breakpoint in the method that gets called, but the error seems to be happening before the breakpoint is reached.

**Expected behavior**
The template extension method is called, the result computed and displayed in my HTML template.

**Actual behavior**
Website loads endlesly in browser. Logfile shows this:

```
2020-02-11 17:00:18,069 INFO  [io.quarkus] (main) Quarkus 1.2.0.Final started in 2.818s. Listening on: http://0.0.0.0:8080
2020-02-11 17:00:18,070 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-02-11 17:00:18,070 INFO  [io.quarkus] (main) Installed features: [cdi, qute, resteasy, resteasy-jackson, resteasy-qute, spring-di, spring-web]
2020-02-11 17:00:30,242 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.maxCapacityPerThread: {}
2020-02-11 17:00:30,243 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.maxSharedCapacityFactor: {}
2020-02-11 17:00:30,243 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.linkCapacity: {}
2020-02-11 17:00:30,243 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.ratio: {}
2020-02-11 17:00:30,334 DEBUG [io.net.han.cod.com.ZlibCodecFactory] (vert.x-eventloop-thread-1) -Dio.netty.noJdkZlibDecoder: {}
2020-02-11 17:00:30,334 DEBUG [io.net.han.cod.com.ZlibCodecFactory] (vert.x-eventloop-thread-1) -Dio.netty.noJdkZlibEncoder: {}
2020-02-11 17:00:30,459 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002315: PathInfo: /
2020-02-11 17:00:31,172 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed
2020-02-11 17:00:31,175 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.html
2020-02-11 17:00:31,176 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.txt

<HERE WE HAVE AN ENDLESS WAIT, THEN IT SEEMS TO RESTART THE TASK?>

> Task :quarkusDev

<THEN RELOADING WEBSITE IN BROWSER>

2020-02-11 17:04:48,855 DEBUG [io.qua.resteasy] (vert.x-eventloop-thread-10) IO Exception : io.vertx.core.VertxException: Connection was closed

2020-02-11 17:04:48,892 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002315: PathInfo: /
2020-02-11 17:04:49,219 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed
2020-02-11 17:04:49,222 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.html
2020-02-11 17:04:49,224 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.txt

<AND ENDLESS WAIT AGAIN>
```

**Not working code example**

```
    // My @RestController method, where "downloadFolder" would be a simple String, and "feed" would be a @Component with several methods
    @GetMapping(value = "/", produces = MediaType.TEXT_HTML)
    public TemplateInstance showFeed() {
        return feed.data("feed", feedReader.readFeed())
                .data("downloadFolder", downloadFolder);
    }
```

```
@TemplateExtension
public class DownloadExistsUtil {
    public static boolean isAlreadyDownloaded(FeedItem feedItem, String downloadUrl, String downloadFolder) {
        return false;
    }
}
```

```
<table class="datagrid">
    {#for item in feed}
    <tr>
        <td>
            {#for url in item.urls}
                {#if item.isAlreadyDownloaded(url,downloadFolder) == false}
                    <p>
                        Bla
                    </p>
                {#else}
                    <p>
                        Blub
                    </p>
                {/if}
            {/for}
        </td>
    </tr>
    {/for}
</table>
```

**Working example with just 1 parameter**

```
    // No change from "not working example"
    // My @RestController method, where "downloadFolder" would be a simple String, and "feed" would be a @Component with several methods
    @GetMapping(value = "/", produces = MediaType.TEXT_HTML)
    public TemplateInstance showFeed() {
        return feed.data("feed", feedReader.readFeed())
                .data("downloadFolder", downloadFolder);
    }
```

```
@TemplateExtension
public class DownloadExistsUtil {
    public static boolean isAlreadyDownloaded(FeedItem feedItem, String downloadUrl) {
        return false;
    }
}
```

```
<table class="datagrid">
    {#for item in feed}
    <tr>
        <td>
            {#for url in item.urls}
                {#if item.isAlreadyDownloaded(url) == false}
                    <p>
                        Bla
                    </p>
                {#else}
                    <p>
                        Blub
                    </p>
                {/if}
            {/for}
        </td>
    </tr>
    {/for}
</table>
```

**Configuration**
- Nothing

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Microsoft Windows [Version 10.0.18363.592]
 - Output of `java -version`:

```
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```

 - GraalVM version (if different from Java): same as java
 - Quarkus version or git rev: 1.2.0.Final

### PR DESCRIPTION
**Pull request by mkouba**
- also fix parent context resolution for multiple nested levels
- resolves #7144

### CODE REVIEW

**Comment by gsmet** [comment]
@mithandir can you check it solves your problem?

**Comment by mithandir** [comment]
@gsmet  Thank you, currently checking out your branch and building it.

**Comment by mithandir** [comment]
@gsmet At least I get an error message inside the browser. I did miss implementing the template extension methods with 1 parameter in my example. But still get an error.

I did update the example: https://github.com/mithandir/quarkus-quote-template-bug/commit/130938b833ef0b2986f7ffdf44fb8d8f7b0fc5d8

```
2020-02-20 06:32:14,657 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-62) HTTP Request to /error failed, error id: f32c18a6-9cad-4d83-a675-487f94c68b6d-3: org.jboss.resteasy.spi.UnhandledException: java.util.concurrent.CompletionException: java.lang.ClassCastException: class io.quarkus.qute.Results$Result cannot be cast to class java.lang.String (io.quarkus.qute.Results$Result is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2aa3cd93; java.lang.String is in module java.base of loader 'bootstrap')
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:587)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:508)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.util.concurrent.CompletionException: java.lang.ClassCastException: class io.quarkus.qute.Results$Result cannot be cast to class java.lang.String (io.quarkus.qute.Results$Result is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2aa3cd93; java.lang.String is in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1099)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:93)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:102)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:102)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:102)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:102)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:69)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolveReference$1(EvaluatorImpl.java:72)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:70)
	at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:48)
	at io.quarkus.qute.ResolutionContextImpl.evaluate(ResolutionContextImpl.java:31)
	at io.quarkus.qute.IfSectionHelper$OperandCondition.evaluate(IfSectionHelper.java:175)
	at io.quarkus.qute.IfSectionHelper$CompositeCondition.evaluateNext(IfSectionHelper.java:215)
	at io.quarkus.qute.IfSectionHelper$CompositeCondition.evaluate(IfSectionHelper.java:197)
	at io.quarkus.qute.IfSectionHelper.resolveCondition(IfSectionHelper.java:53)
	at io.quarkus.qute.IfSectionHelper.resolve(IfSectionHelper.java:43)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:34)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:126)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:41)
	at io.quarkus.qute.LoopSectionHelper.nextElement(LoopSectionHelper.java:83)
	at io.quarkus.qute.LoopSectionHelper.lambda$resolve$1(LoopSectionHelper.java:54)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at io.quarkus.qute.LoopSectionHelper.resolve(LoopSectionHelper.java:37)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:34)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:126)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:41)
	at io.quarkus.qute.LoopSectionHelper.nextElement(LoopSectionHelper.java:83)
	at io.quarkus.qute.LoopSectionHelper.lambda$resolve$1(LoopSectionHelper.java:54)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at io.quarkus.qute.LoopSectionHelper.resolve(LoopSectionHelper.java:37)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:34)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:126)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:31)
	at io.quarkus.qute.Parser$1$1.resolve(Parser.java:74)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:34)
	at io.quarkus.qute.TemplateImpl.renderData(TemplateImpl.java:92)
	at io.quarkus.qute.TemplateImpl.access$200(TemplateImpl.java:14)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:73)
	at io.quarkus.resteasy.qute.runtime.TemplateResponseFilter.filter(TemplateResponseFilter.java:58)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:361)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:232)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:97)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:70)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:578)
	... 21 more
Caused by: java.lang.ClassCastException: class io.quarkus.qute.Results$Result cannot be cast to class java.lang.String (io.quarkus.qute.Results$Result is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2aa3cd93; java.lang.String is in module java.base of loader 'bootstrap')
	at org.download.client.utils.DownloadExistsUtil_Extension_ValueResolver_isAlreadyDownloaded_2f56c2965c4b44769ce830a300cec81859a1cb8b$$function$$16.accept(DownloadExistsUtil_Extension_ValueResolver_isAlreadyDownloaded_2f56c2965c4b44769ce830a300cec81859a1cb8b$$function$$16.zig:69)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at org.download.client.utils.DownloadExistsUtil_Extension_ValueResolver_isAlreadyDownloaded_2f56c2965c4b44769ce830a300cec81859a1cb8b.resolve(DownloadExistsUtil_Extension_ValueResolver_isAlreadyDownloaded_2f56c2965c4b44769ce830a300cec81859a1cb8b.zig:112)
	... 71 more


```

**Comment by mkouba** [comment]
I don't think that changing only the version of `io.quarkus:quarkus-resteasy-qute` would work. Anyway, I'll take a look at the updated app.

**Comment by mithandir** [comment]
Sorry, my mistake. Updating everything to 999-SNAPSHOT did work. The "error" endpoint now displays everything correctly.

So from my side it seems to be fixed.

**Comment by mkouba** [comment]
@gsmet The failure on the windows machine seems to be unrelated.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
