### PR TITLE
Use mvnw in CI to make sure we have a stable Maven version

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by geoand** [comment]
CI failure seems related:

```
 ../tcks/mvnw: 219: cannot open /home/runner/work/quarkus/quarkus/resteasy-reactive-testsuite/.mvn/wrapper/maven-wrapper.properties: No such file
/home/runner/work/quarkus/quarkus/resteasy-reactive-testsuite/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
Error: Process completed with exit code 1.
```

**Comment by famod** [comment]
The easiest fix for this might be to introduce `mvnw` in the `1.11` of the testsuite...

Alternatively, switching the working-directory to `tcks` and using `-f ../resteasy-reactive-testsuite` _could_ work but you might run into #16906.

**Comment by gsmet** [comment]
Yeah I was expected something like that. I think I haven't totally grokked the structure. What I don't understand is how you can find ../tcks/.github/mvn-settings.xml and not the Maven wrapper.

**Comment by famod** [comment]
Probably a bug in the wrapper. I suppose it didn't even come as far to check the settings file.

**Pull request merged**
