### PR TITLE
Big Quarkus REST rename

### PR DESCRIPTION
**Pull request by gsmet**
This PR contains the work to rename the RESTEasy Reactive (and some RESTEasy Classic) extensions to be more consistent with the idea of having a Quarkus REST branding.

Relocations have been put in place for everything.
Fallbacks have been put in place for the config too.

An overview of the changes can be found in the migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-extensions-renamed-to-quarkus-rest .

Note that there are still a few remaining issues/tasks:

- There are a ton of warnings due to the fallback layer. @radcortez is working on it and hopefully we will have something for the CR1.
- I want to rename a few config properties in the OTel config (to remove mentions of RESTEasy Reactive) but I prefer to do it once this is in as it's already a gigantic PR.
- The REST Client Config extension needs to be moved out of the `resteasy-classic` as it's common to both but again, another PR and not actually pressing.
- I need to work on the OpenRewrite recipes

I don't expect people to actually review the full content of this PR given it affects (cough cough) 1700+ files.

I have renamed some of the directories on disk but not all of them as typically for the OIDC extensions, I prefer to let @sberyozkin and @michalvavrik decide if they prefer to keep them where they are. The on-disk structure is not consumed by users so we don't really care about it.

Let's do that in a second time once the dust has settled.

Ideally I would like this to get merged quickly as it's a nightmare to keep updated with all you folks being busy bees.

/cc @geoand @cescoffier @maxandersen

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks for this massive effort @gsmet, can you clarify what did you mean with `I have renamed some of the directories on disk but not all of them as typically for the OIDC extensions` ?

Do you mean something like removing `.reactive.` from the package names of the renamed extensions and updating the directories accordingly ?

I believe OIDC related commits look fine

**Comment by gsmet** [comment]
@sberyozkin no, we decided to avoid changing the package names as it would quickly become a backport nightmare.

What I'm saying is while I renamed `quarkus-oidc-token-propagation` to `quarkus-resteasy-client-oidc-token-propagation`, the on-disk directory is still `extensions/oidc-token-propagation`.

**Comment by gsmet** [comment]
And believe it or not, CI is green \o/

**Review by geoand — APPROVED** [review]
Let's get in ASAP!

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
Raaaaaaaah, conflict...

**Comment by radcortez** [comment]
Sorry :(

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
It should be fairly easy to resolve... I added a few additional tests / assertions in RestClientFallbackConfigSourceInterceptorTest. We only to rename the properties.

**Comment by gsmet** [comment]
Yes, already solved, I'll go add the relocate though as we will get another CI run anyway :).

**Comment by gsmet** [comment]
The test `RestClientFallbackConfigSourceInterceptorTest.testGetValue` was actually dropped by @radcortez in the SmallRye Config 3.6.1 and it was reintroduced when it was rebased and conflicts were solved.

I dropped this test again, force pushed and did a local check that everything is OK.

I will merge so that we can make progress.

**Pull request merged**
