### PR TITLE
Qute Character Escapes for Json Content

### PR DESCRIPTION
**Pull request by ogomezdi**
Changes for covering JSON Escapes in templates mentioned in issue #43369

### CODE REVIEW

**Comment by gsmet** [comment]
@mkouba not sure you are aware of this effort?

**Comment by mkouba** [comment]
> @mkouba not sure you are aware of this effort?

@gsmet I think I was but I forgot ;-).

@ogomezdi Could you squash the commits please?

**Comment by ogomezdi** [comment]
> > @mkouba not sure you are aware of this effort?
> 
> @gsmet I think I was but I forgot ;-).
> 
> @ogomezdi Could you squash the commits please?
Sorry for the inconvenience, it was my first time and I make foolish typo errors in testing class.
The functionality was the one we spoke and agreed long ago @mkouba.
What exactly do you want me to do?

**Comment by mkouba** [comment]
> What exactly do you want me to do?

To squash the commits in one. See for example https://www.git-tower.com/learn/git/faq/git-squash or https://www.geeksforgeeks.org/git-squash/.

**Comment by ogomezdi** [comment]
> > What exactly do you want me to do?
> 
> To squash the commits in one. See for example https://www.git-tower.com/learn/git/faq/git-squash or https://www.geeksforgeeks.org/git-squash/.

I'm not able to do this :( , my git skills are minimal, and executing commands in examples provided get me to nowhere.

**Comment by mkouba** [comment]
> > > What exactly do you want me to do?
> > 
> > 
> > To squash the commits in one. See for example https://www.git-tower.com/learn/git/faq/git-squash or https://www.geeksforgeeks.org/git-squash/.
> 
> I'm not able to do this :( , my git skills are minimal, and executing commands in examples provided get me to nowhere.

No worries, I can do that.

**Comment by mkouba** [comment]
This pull request is superseded by #44706.

@ogomezdi I wasn't able to merge the commits on your branch either. So I've created a new branch, cherry-picked your commits, rebased and introduced some changes:
1. Added a test to `EscapingTest` to verify the Quarkus integration
2. Introduced `CharReplacementResultMapper` that holds the common logic for `JsonEscaper` and `HtmlEscaper`.
3. Modified the logic in `JsonEscaper` to improve the performance (quick benchmark showed the diff ~ 10%).
4. Removed the duplicate parts from the docs.

Let me know what you think.

**Comment by ogomezdi** [comment]
> This pull request is superseded by #44706.
> 
> @ogomezdi I wasn't able to merge the commits on your branch either. So I've created a new branch, cherry-picked your commits, rebased and introduced some changes:
> 
> 1. Added a test to `EscapingTest` to verify the Quarkus integration
> 2. Introduced `CharReplacementResultMapper` that holds the common logic for `JsonEscaper` and `HtmlEscaper`.
> 3. Modified the logic in `JsonEscaper` to improve the performance (quick benchmark showed the diff ~ 10%).
> 4. Removed the duplicate parts from the docs.
> 
> Let me know what you think.

Great solution!!!
I didn't notice the need of "EscapingTest", simply perfect.
Creating an abstract class, makes easier to understand the logic, despite the performance improvement you've mentioned, and it's convenient for future escape needs in other target formats (YAML, ...)

Thanks a lot!!!
I promise I'll improve my git skills for future pull request.

**Pull request closed without merging**
