### PR TITLE
Update Keycloak docker image to 9.0.0

### LINKED ISSUE #7314: Update Keycloak docker image to 9.0.0
**Description**
Keycloak 9.0.0 has been released so we need to test against it

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #7314

### CODE REVIEW

**Review by machi1990 — DISMISSED** [review]
I think we should update this line https://github.com/quarkusio/quarkus/blob/master/ci-templates/jvm-build-steps.yaml#L33 too.

**Comment by sberyozkin** [comment]
@machi1990 Thanks for spotting it :-), also updated the comment in the `build-parent/pom.xml`

**Comment by machi1990** [comment]
> @machi1990 Thanks for spotting it :-), also updated the comment in the `build-parent/pom.xml`

Thanks @sberyozkin I also wonder if we should updates the keycloak instances in  https://github.com/quarkusio/quarkus/blob/master/.github/workflows/ci-actions.yml ?

@gsmet @sberyozkin WDYT?

**Comment by gsmet** [comment]
Yes, it's what we use now for CI so we need to.

**Review by gsmet — CHANGES_REQUESTED** [review]
Shouldn't `keycloak.version` be updated in the bom?

**Comment by sberyozkin** [comment]
Hi @machi1990 @gsmet Oh, another resource is there :-), let me update it too.

@gsmet So far the update was about testing against Keycloak, so haven't thought about the bom update, makes sense though to sync, will do as well

**Comment by gsmet** [comment]
I rebased to get the latest CI fixes. Please pull before pushing other changes.

**Comment by sberyozkin** [comment]
@gsmet Thanks, does it look OK now ?

**Review by machi1990 — APPROVED** [review]
LGTM.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
