### PR TITLE
Register profile specific configuration files for hot-reload

### LINKED ISSUE #18731: Add profile specific config files to watched resources in dev mode
### Description

A file like `application-dev.yaml` (or .properties) is not automatically watched for changes, but the regular `application.yaml` is.

There seems to be no good reason for this difference.

Workaround; DIY:
```yaml
quarkus:
  live-reload:
    watched-resources:
      - application-dev.yaml
```

See also: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Profile.20aware.20config.20files/near/246092779

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by glefloch**
This branch registers `application-<profile>.properties` and yaml variant too for hot reload. 

close #18731

### CODE REVIEW

**Review by famod — APPROVED** [review]
LGTM! But let's wait for @radcortez before merging.

**Review by geoand — APPROVED** [review]

**Comment by radcortez** [comment]
Can we also add the profiles for `.env`, `config` folder and `quarkus.config.locations`? See https://github.com/quarkusio/quarkus/blob/d3d70ac5b97932bf2a2811ef796219d590ff2811/core/deployment/src/main/java/io/quarkus/deployment/steps/DevModeBuildStep.java

**Review by radcortez — CHANGES_REQUESTED** [review]
Can we also add the profiles for `.env`, `config` folder and `quarkus.config.locations`? See https://github.com/quarkusio/quarkus/blob/d3d70ac5b97932bf2a2811ef796219d590ff2811/core/deployment/src/main/java/io/quarkus/deployment/steps/DevModeBuildStep.java

**Comment by glefloch** [comment]
Sure, just to make sure, that would means to register: 
- .env-<profile>
- config-<profile>/*
- all `quarkus.config.location`-<profile>/*

**Comment by radcortez** [comment]
> Sure, just to make sure, that would means to register for example for the dev profile:
> 
> * .env-dev

Yes.

> * config-dev/*

No. Files can also be read from the `/config` directory. So if you have `config/application.properties`, you can also have `config/application-dev.properties`. See https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/configuration/ApplicationPropertiesConfigSourceLoader.java. Same for YAML.

> * all `quarkus.config.location`-dev/*

No. You can add additional locations (or files) with the configuration. For instance, `quarkus.config.locations=my-config.properties`. In this case for a profile, `my-config-dev.properties` is also valid and should be monitored.

**Comment by glefloch** [comment]
@radcortez I pushed an update that adds all paths.

**Comment by gsmet** [comment]
@radcortez I let you drive this puppy home!

**Comment by radcortez** [comment]
> @radcortez I let you drive this puppy home!

Sure :)

**Review by radcortez — APPROVED** [review]

**Pull request merged**
