### PR TITLE
AppCDS: Make container-based generation opt-out

### PR DESCRIPTION
**Pull request by benkard**
This change adds a new configuration key, `quarkus.package.appcds-use-container`, which defaults to true and can be set to false to avoid the use of a container when building an AppCDS archive.

This is useful in cases where the build happens in an environment without full control of a container system, such as hosted CI solutions.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this.

Can elaborate a little more on the reasoning? Why would one need `quarkus.package.create-appcds=true` and `quarkus.package.appcds-use-container=false`?

**Comment by benkard** [comment]
My personal use case is a CI pipeline that runs in Bitbucket Pipelines.  Bitbucket Pipelines gives me access to a restricted Docker daemon with some peculiarities about it.  One such peculiarity is that the user ID that you pass to the container using `docker run --user` maps to something other than the same UID in the container running the build, which makes the attempt by the AppCDS container to write its output file fail.  Even if I work around this by creating all directories beforehand and applying `chmod 0777` to everything I can find creation of the AppCDS archive still fails for other reasons related to the managed Docker daemon.  In this environment I also cannot run my own Docker daemon because my pipeline runs in a restricted container itself.

On the other hand I can select the container that the build pipeline itself runs in, so I can easily make it use the same exact container image that I use as my target Jib base image (or one derived from it). I checked—creating the AppCDS archive in the build container itself works fine.  It is only when I add Jib to the mix that it fails because the Jib target image is detected as an image to run the AppCDS build in (which is usually what you want, just not in my particular case) and so it attempts to use Docker to do the AppCDS, which fails due to the above-mentioned reasons.

**Review by geoand — APPROVED** [review]
Thanks

**Comment by geoand** [comment]
@benkard mind rebasing this onto `main`? 

Thanks

**Pull request merged**
