### PR TITLE
Improve config documentation generation for mappings

### PR DESCRIPTION
**Pull request by radcortez**
This improves 3 things:
- Do not require the @ConfigGroup annotation in non-inner classes of mappings to generate the docs
- Ignore the `toString` method
- Properly generate documentation for `Duration` and other java types

### CODE REVIEW

**Comment by gsmet** [comment]
Could you describe the purpose of this change? Thanks.

**Comment by radcortez** [comment]
Sure, updated the description.

**Comment by radcortez** [comment]
@gsmet do you think we can merge this? Thanks!

**Review by gsmet — APPROVED** [review]

**Comment by radcortez** [comment]
Thanks :)

**Pull request merged**
