### PR TITLE
Scheduler - fix tests for pause/resume of scheduled methods

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by mkouba** [comment]
CC @adrianfiedler

**Review by machi1990 — APPROVED** [review]

**Comment by gsmet** [comment]
@famod there's something weird with the status of this CI run: https://github.com/quarkusio/quarkus/actions/runs/813295602

The status at the top is `Failure` while everything looks green or skipped... except for the `Matrix - native tests` at the bottom which is in the `Waiting for pending jobs`.

I suspect it could be related to your latest CI changes.

**Comment by famod** [comment]
@gsmet 
image

Hm. I thought I tested an empty matrix. Will have a look.

**Comment by famod** [comment]
@gsmet A fix is on the way (was a bit tricky).

What disturbes me a bit is that GH is all green here with `All checks have passed` although the workflow itself has bug.

**Comment by famod** [comment]
I think this PR can be merged safely. If you want to be extra sure, you can wait for #17022 (and rebase after that).

**Comment by famod** [comment]
I went ahead and merged this. Will do a final test of the CI fix in #16997 (which has no approval yet).

**Pull request merged**
