### PR TITLE
Add high level logging for RESTEasy Reactive exceptions

### PR DESCRIPTION
**Pull request by geoand**
Closes: #27585

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by famod** [comment]
Could this be worth mentioning in the docs?

E.g. OIDC has such hints in its docs.

**Comment by geoand** [comment]
Why not 😉

**Comment by geoand** [comment]
I'll follow that up tomorrow

**Comment by FroMage** [comment]
Yes, if the docs don't mention how to enable this, it doesn't exist ;) Bonus points if it tells me how to enable _just_ this and not all the debug logs that I don't care about ;)

**Comment by geoand** [comment]
I have a new PR for that 😉

**Pull request merged**
