### PR TITLE
Bump RESTEasy version to 4.5.5.Final, added test for #8795

### LINKED ISSUE #10096: Not expected behaviour when using http.* or https.* proxy system properties
**Describe the bug**

At the moment in order to set an http/https proxy one uses system properties like:
```-Dhttp.proxyHost=localhost -Dhttp.proxyPort=9090 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=9090 -Dhttp.nonProxyHosts=dummy.example.com```

However, the behaviour is not as expected. For instance:

- If you specify just https.* properties, they are not picked up.

- If you specify both http and https properties and a http.nonProxyHosts, the latter is not picked up, forcing everything through the proxy.

**Expected behavior**
What I would expect:

- If you specify https.* proxy properties, they should be picked up for https calls.

- If you use both http and https properties with http.nonProxyHosts, the latter should be picked up to avoid going through the proxy.

**To Reproduce**
1. Clone and compile the test repo: https://github.com/paolocarta/microprofile-rest-clients-http-proxy
2. Start the app with: ```java -Dhttps.proxyHost=localhost -Dhttps.proxyPort=9090 -jar target/rest-client-quickstart-1.0-SNAPSHOT-runner.jar``` , the https proxy is not picked up.
3. Start the app with: ```java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=9090 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=9090 -Dhttp.nonProxyHosts=dummy.restapiexample.com -jar target/rest-client-quickstart-1.0-SNAPSHOT-runner.jar``` , the nonProxyHosts property is ignored.

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin MacBook-Pro 19.5.0 Darwin Kernel Version 19.5.0
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14, OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
 - Quarkus version or git rev: for sure starting with 1.3.2 and above.
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Apache Maven 3.6.3

### PR DESCRIPTION
**Pull request by FroMage**
Had to bump to 4.5.5.Final because 4.5.4.Final did not have the fixes that were supposed to be in there, due to some release mishap.

### CODE REVIEW

**Review by asoldano — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by FroMage** [comment]
Damnit, test failures:

```
2020-06-17T09:19:12.5708095Z [ERROR] Failures: 
2020-06-17T09:19:12.5725946Z [ERROR]   JaxRSTestCase.testSSE:272 1 expectation failed.
2020-06-17T09:19:12.5726587Z Expected content-type "text/event-stream" doesn't match actual content-type "".
2020-06-17T09:19:12.5726674Z 
2020-06-17T09:19:12.5727946Z [ERROR]   JaxRsConstructorPropertiesTestCase.testWrappedInServerSentEventMessage:38 1 expectation failed.
2020-06-17T09:19:12.5729351Z Response body doesn't match expectation.
2020-06-17T09:19:12.5733111Z Expected: a string containing "ssevalue"
2020-06-17T09:19:12.5735532Z   Actual: 
2020-06-17T09:19:12.5735651Z 
2020-06-17T09:19:12.5735724Z [INFO] 
```

**Comment by FroMage** [comment]
Fixed those two tests. Apparently the syntax changed and using `@Produces("text/event-stream;element-type=text/xml")` will throw in some places, thus requiring:

```java
    @SseElementType(MediaType.TEXT_XML)
    @Produces(MediaType.SERVER_SENT_EVENTS)
```

Is that expected @asoldano ?

**Comment by gsmet** [comment]
I'll refrain from backporting as it might break some applications.

**Comment by asoldano** [comment]
> Fixed those two tests. Apparently the syntax changed and using `@Produces("text/event-stream;element-type=text/xml")` will throw in some places, thus requiring:
> 
> ```java
>     @SseElementType(MediaType.TEXT_XML)
>     @Produces(MediaType.SERVER_SENT_EVENTS)
> ```
> 
> Is that expected @asoldano ?

I don't think so, but might be forgetting something. @ronsigal, any clue?

**Comment by jaikiran** [comment]
> > Fixed those two tests. Apparently the syntax changed and using `@Produces("text/event-stream;element-type=text/xml")` will throw in some places, thus requiring:
> > ```java
> >     @SseElementType(MediaType.TEXT_XML)
> >     @Produces(MediaType.SERVER_SENT_EVENTS)
> > ```
> > 
> > 
> > Is that expected @asoldano ?
> 
> I don't think so, but might be forgetting something. @ronsigal, any clue?

@asoldano, my guess is that this is an unintentional side-effect of this change https://github.com/resteasy/Resteasy/pull/2361/files#diff-198cf22a0e7c855a4a4b3cf2430f873cL171. 
My guess (based on a quick check of the resteasy code) is that this new code:
```
Arrays.asList(mediaTypes).contains(MediaType.SERVER_SENT_EVENTS_TYPE)
```
is no longer satisfied, due to the fact that the `MediaType.equals` implementation also takes into account the `parameters` map for equality check. So the constant `MediaType.SERVER_SENT_EVENTS_TYPE` which doesn't have any `parameters` isn't considered `equal` to a `MediaType.SERVER_SENT_EVENTS_TYPE` which is parsed out of the `text/event-stream;element-type=text/xml` which will have a `parameters` map populated with the `element-type` key/value pair.

For a similar use case for equality check, I had to write something like this in Quarkus a while back https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L541. I guess, at a minimum, something like that probably needs to be done in RestEasy too, since this change looks like an regression (not just in Quarkus but in RestEasy core itself).

**Comment by asoldano** [comment]
Thanks for the investigation @jaikiran ! @ronsigal and @jimma will be looking into and fixing this soon.

**Comment by asoldano** [comment]
https://issues.redhat.com/browse/RESTEASY-2625

**Comment by FroMage** [comment]
FTR I think those tests had two failures at different places, so it's possible there are two distinct fixes to make in RESTEasy

**Comment by asoldano** [comment]
Jim has just provided https://github.com/resteasy/Resteasy/pull/2450 , you might want to try building it and seeing if it fully address the regression in Quarkus maybe?

**Comment by ronsigal** [comment]
@jaikiran, you're still here!! Cool. ;-)

**Comment by jaikiran** [comment]
> @jaikiran, you're still here!! Cool. ;-)

Hey Ron, good to see to you around too :) Been a while!

**Comment by geoand** [comment]
I am wondering if it makes sense to setup some CI that will test some branch of RESTEasy with the latest Quarkus

**Comment by FroMage** [comment]
@asoldano yup, the PR fixes those two tests.

**Comment by FroMage** [comment]
@geoand that would be really sweet.

**Comment by FroMage** [comment]
Restarted CI. We could merge this PR regardless, because we have workarounded the tests, and it fixes a few RE bugs we know of, even though this might break a few user's code if they used the same annotations and idioms.

**Pull request merged**
