### PR TITLE
Restrict deployment classpath to first level extensions

### LINKED ISSUE #20767: Gradle reactive project errors when the maven one doesn't.
### Describe the bug

If I generate a reactive project the maven version works and the gradle one doesn't.
I made projects with the dependencies described here: https://quarkus.io/guides/getting-started-reactive
[code-with-quarkus (5).zip](https://github.com/quarkusio/quarkus/files/7345800/code-with-quarkus.5.zip)
[code-with-quarkus (4).zip](https://github.com/quarkusio/quarkus/files/7345801/code-with-quarkus.4.zip)

### Expected behavior

App starts

### Actual behavior

Gradle project gives me this:
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgresql' for the default datasource. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.

### How to Reproduce?

Run
./gradlew quarkusDev
and
./mvnw quarkus:dev

### Output of `uname -a` or `ver`

ver : The term 'ver' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is  correct and try again.

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7) OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.2 ------------------------------------------------------------  Build time:   2021-08-17 09:59:03 UTC Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad  Kotlin:       1.5.21 Groovy:       3.0.8 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.12 (Eclipse Foundation 11.0.12+7) OS:           Windows 10 10.0 amd64

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glefloch**
This branch rework the way the deployment classpath is built. 
This now goes down the dependency graph and stop on first level extension. 
conditional dependencies are added afterward. 

close #20767

### CODE REVIEW

**Comment by gsmet** [comment]
I'm really not sure we should go down this road. The real problem is that there should be a common Hibernate ORM module that doesn't depend on Agroal and Narayana and that is shared between Hibernate ORM extension and Hibernate Reactive extension.

**Comment by glefloch** [comment]
I'm reworking the way we build the deployment classpath, this exclude should not be necessary anymore. But I agree on the common module that does not depend on `agroal` and `narayana`.

**Comment by aloubyansky** [comment]
@glefloch looks like it needs a rebase.

**Comment by glefloch** [comment]
right!, I also removes the exclude as it does not seems to be necessary anymore.

**Comment by aloubyansky** [comment]
@glefloch could you please adjust the title and the description of the PR so they correspond to the actual changes? Thanks!

**Comment by glefloch** [comment]
Sure done :)

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
