### PR TITLE
Fix Panache / Reactive integration tests in native mode

### LINKED ISSUE #13668: Panache / Hibernate Reactive integration tests are not run on CI
**Description**
The module for `:quarkus-integration-test-hibernate-reactive-panache` is apparently not being run on CI - I found two probems when testing it locally in **native mode**. Maybe it's not being run in native?

**Implementation ideas**
I propose we fix it :-) 

I'll follow up with links to the existing failures: no point in enabling CI on this module until it actually works.

Pre-requisites:

1. #13672
2. #13670

### LINKED ISSUE #13672: Reactive Panache: Entity bytecode replacements seem ignored by native-image
**Describe the bug**
It seems like the entities compiled into native are missing the replacement implementations for the template methods.

Running

I get:
```
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?

    at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.implementationInjectionMissing(AbstractJpaOperations.java:321)
    at io.quarkus.hibernate.reactive.panache.PanacheEntityBase.deleteAll(PanacheEntityBase.java:626)
    at io.quarkus.it.panache.reactive.PanacheFunctionalityTest.before(PanacheFunctionalityTest.java:48)
```

As @FroMage pointed out, the stack should point to the `deleteAll` method in `Dog` entity, not to the one in `PanacheEntityBase`. Did the enhancer run successfully? Are we compiling the right code?

**To Reproduce**

Run 

 1. `podman run --rm --name HibernateTestingPGSQL -e POSTGRES_USER=hibernate_orm_test -e POSTGRES_PASSWORD=hibernate_orm_test -e POSTGRES_DB=hibernate_orm_test -p 5432:5432 postgres:13.1`
 2. `mvn clean install -pl :quarkus-integration-test-hibernate-reactive-panache -amd -Dtest-containers -Dnative`

Might be bast to fix #13670 first, as it prevents seeing the present issue.

### PR DESCRIPTION
**Pull request by FroMage**
all calls must go via REST
and it was just not needed

Fixes #13672
Fixes #13668

### CODE REVIEW

**Comment by Sanne** [comment]
Looks good. I'll amend the description

**Review by Sanne — APPROVED** [review]
Looks good, but let's wait for the CI logs to see that it actually did run the expected tests.

**Comment by gsmet** [comment]
I checked the tests have been run.

**Comment by Sanne** [comment]
And they passed?

**Pull request merged**
