### PR TITLE
Update Netty to 4.1.42.Final

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by Sanne** [comment]
This looks sane, but I'm wondering: during last meeting @emmanuelbernard mentioned you badly needed to disable some native-image directives being picked up from the Manifest in the Netty jar; is that no longer the case?

asking so to affect priority for #4919

**Comment by gsmet** [comment]
Does it bring something to the plate? If we don't strictly need it, I would just postpone that for now.

**Comment by stuartwdouglas** [comment]
@gsmet I assume that comment about postponing was in relation to Sanne, not to this PR in general?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by emmanuelbernard** [comment]
The new release does bring CVE fixes.

**Comment by stuartwdouglas** [comment]
Then let's update

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
