### PR TITLE
Update smallrye openapi to 2.0.20

### LINKED ISSUE #13845: Add oauth2 configuration to swagger-ui
**Description**
Already many configurations for the openapi / swagger-ui can be set in the application.properties. It would be nice to be able to set the oauth 2 configuration properties (https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md) 

This would allow to set preconfigure the oauth login dialog with all the necessary options.

**Implementation ideas**
As example, with spring-doc the properties can be set as follow:
`springdoc.swagger-ui.oauth.client-id=theclient`
so for quarkus it could be 

```
quarkus.swagger-ui.oauth.client-id=theclient
```

### LINKED ISSUE #14670: OpenAPI invalid document - missing schema element
**Describe the bug**
The generated openapi document is missing the schema element "MessageDataItemsAnimal".

Bug is in Quarkus version: **1.11.1.FINAL** and not in **1.11.0.FINAL**

**Expected behavior**
The generated openapi document is consistent.

**Actual behavior**
The generated openapi document refereces the schema "MessageDataItemsAnimal" but not creating it.

**To Reproduce**

1. Clone and start the reproducer: https://github.com/haraldatbmw/openapi-reproducer
2. Look at the openapi document at http://localhost:8080/q/openapi
3. Or open the swagger-ui at http://localhost:8080/q/swagger-ui and try to expand the schema AnimalListEnvelope --> error occurs

**Environment (please complete the following information):**
 - Quarkus version: 1.11.1.FINAL

### LINKED ISSUE #14712: OpenAPI:  1.11.x picks up annotated interfaces from dependency JARs
**Describe the bug**
1.11.x is including annotated API interfaces from dependent JAR's that have no implementations provided.  These are API's that I am consuming, not ones that I am providing.  Since they come from a 3rd party, I can't annotate them with @RegisterRestClient.

**Expected behavior**
Only include REST API's that have implementations provided.  Ignore interfaces with no implementations, not just ones annotated with @RegisterRestClient.  If an annotated API does not have an implementation, than the application is not actually exposing it.

**Actual behavior**
Includes annotated interfaces from dependency JAR's with no implementations.

**To Reproduce**
git clone https://bitbucket.org/alexlitovsky1/quarkus-openapi-bug.git

1. mvn quarkus:dev
2. http://localhost:8080/swagger-ui
3. Notice that /facts/random shows up (it shouldn't).
4. Change the POM to use Quarkus 1.10.5
5. mvn quarkus:dev
6. http://localhost:8080/swagger-ui
7. Notice that the /facts/random API does NOT show up (this is correct).

**Configuration**
```
quarkus.smallrye-openapi.path=/openapi.yml
quarkus.swagger-ui.always-include=true
quarkus.log.level=INFO
quarkus.log.console.enable=true

catfact.url=https://cat-fact.herokuapp.com
```

**Screenshots**
**Quarkus 1.10.5 (correct behavior)**
image

**Quarkus 1.11.1 (incorrect behavior)**
image

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.19041.746]
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**

### LINKED ISSUE #14865: @DefaultValue for enums ignored in openapi.yaml / swagger-ui
**Describe the bug**

Specifying a default value for an enum parameter on a REST API has no effect on the generated openapi.yaml or a pre-selection of the respective value in the swagger-ui.

```java
@Path("/hello-resteasy")
public class GreetingResource {

   public enum MyEnum {
      CAT,
      DOG,
      BAR,
      FOO
   }

   @GET
   @Produces(MediaType.TEXT_PLAIN)
   public String hello(
      @Parameter(required = true) 
      @QueryParam(value = "myEnum") 
      @DefaultValue("DOG") // -> I want MyEnum.DOG to be the default value
      final MyEnum myEnum
   ) {
      return "myEnum = " + myEnum;
   }
}
```

**Expected behavior**

Openapi.yaml should specify "DOG" as parameter default and the "DOG" entry should also be pre-selected in swagger-ui.

**Actual behavior**

The first entry of the enum values sorted alphabetically is pre-selected.

**To Reproduce**

1. Extract [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5935125/code-with-quarkus.zip) and run
2. Go to http://localhost:8080/q/swagger-ui/#/default/get_hello_resteasy

**Screenshots**

Current Swagger-UI:
image

Here is a comparison of how the Openapi.yaml is currently generated (left) and how it could be generated to solve this issue (right).

image

After this change, swagger-ui would render:

image

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.1198]
 - Output of `java -version`: openjdk version "11.0.9.1" 2020-11-04 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### PR DESCRIPTION
**Pull request by phillip-kruger**
Update smallrye openapi to 2.0.20.

see https://github.com/smallrye/smallrye-open-api/releases/tag/2.0.20

Fix #14865
Fix #14712
Fix #14670

(^^^ thanks @MikeEdgar !)

Also added new configuration options for `initOAuth` method in Swagger UI

Fix #13845

Updated Swagger UI to 3.42.0

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Cancelled CI for now as I need the resources for the 1.11.2.Final release finalization.

**Comment by gsmet** [comment]
It broke something:
```
Error:  io.quarkus.it.amazon.lambda.AmazonLambdaSimpleIT.testSwaggerUi  Time elapsed: 0.021 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:162)
	at io.quarkus.it.amazon.lambda.AmazonLambdaSimpleTestCase.testSwaggerUi(AmazonLambdaSimpleTestCase.java:46)
```

Killing the rest of the CI run.

**Comment by phillip-kruger** [comment]
@gsmet - looking at it...

**Comment by phillip-kruger** [comment]
@gsmet - The html title changed, and the Amazon Lambda IT is testing that to see if the html is available. I changed the test to look at the new title.

**Comment by gsmet** [comment]
Force pushed a rebase to solve a conflict in the BOM.

**Pull request merged**
