### PR TITLE
Error when running HQL queries spanning multiple tables in Hibernate Reactive

### LINKED ISSUE #15834: Error when running HQL queries spanning multiple tables in Hibernate Reactive
## Describe the bug
It happens, for example, when using `IngheritanceType.JOINED` and an update/delete HQL query is executed on the parent entity.

At the moment, this exceptions is thrown:
```
java.lang.ClassCastException: class org.hibernate.hql.spi.id.local.LocalTemporaryTableBulkIdStrategy$3 cannot be cast to class org.hibernate.reactive.bulk.StatementsWithParameters
```

It happens because we don't set `optionsBuilder.applyMultiTableBulkIdStrategy( new ReactiveBulkIdStrategy( metadata ) )`
when we create the session factory.

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #15834 

Hibernate Reactive needs  a different `MultiTableBulkIdStrategy` than ORM.

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Review by Sanne — CHANGES_REQUESTED** [review]
Something is wrong with native compilation. I guess a missing reflective rule for the new strategy? I'll have a look

**Comment by DavideD** [comment]
There is failure when on CI with native: https://github.com/quarkusio/quarkus/pull/15835/checks?check_run_id=2138462807#step:9:364

Any idea?

**Comment by DavideD** [comment]
> Something is wrong with native compilation. I guess a missing reflective rule for the new strategy? I'll have a look

Thanks

**Review by Sanne — APPROVED** [review]
It should work now.

**Comment by Sanne** [comment]
Merged! thanks @DavideD

**Pull request merged**
