### PR TITLE
Fix gRPC DevUI testing console

### LINKED ISSUE #43305: gRPC bidi streaming testing in DevUI is broken
### Describe the bug

Bidirectional streaming in the DevUI test console is broken: 

```
2024-09-16 07:59:51,785 ERROR [io.qua.dev.run.com.JsonRpcRouter] (vert.x-eventloop-thread-2) Unable to invoke method io.quarkus.quarkus-grpc.streamService using JSON-RPC, request was: {
  "jsonrpc" : "2.0",
  "method" : "io.quarkus.quarkus-grpc.streamService",
  "params" : {
    "serviceName" : "test.Streaming",
    "methodName" : "pipe",
    "methodType" : "BIDI_STREAMING",
    "content" : "{\n  \"value\": \"dsaf\"\n}"
  },
  "id" : 11
}: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.routeToRuntimeSubscription(JsonRpcRouter.java:176)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.routeToRuntime(JsonRpcRouter.java:163)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.route(JsonRpcRouter.java:139)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.lambda$addSocket$0(JsonRpcRouter.java:105)
	at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handleTextFrame(WebSocketImplBase.java:634)
	at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:600)
	at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:589)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.http.impl.WebSocketImplBase.receiveFrame(WebSocketImplBase.java:534)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:279)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:157)
	at io.vertx.core.http.impl.WebSocketImplBase.handleFrame(WebSocketImplBase.java:475)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:313)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:159)
	at io.vertx.core.http.impl.Http1xConnectionBase.handleWsFrame(Http1xConnectionBase.java:66)
	at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:191)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:176)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: wrong number of arguments: 2 expected: 1
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkArgumentCount(DirectMethodHandleAccessor.java:329)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.grpc.runtime.devui.GrpcJsonRPCService.streamService(GrpcJsonRPCService.java:148)
	at io.quarkus.grpc.runtime.devui.GrpcJsonRPCService_ClientProxy.streamService(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 45 more
```

### Expected behavior

It works.

### Actual behavior

Fails with the exception.

### How to Reproduce?

Reproducer - https://github.com/xstefank/quarkus-reproducers/tree/main/grpc-bidi-streaming

Start dev mode.
Access the gRPC card in DevUI.
Try to pass some value into the bidi_streaming pipe method of test.Streaming.
It fails with the above exception.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xstefank**
- Fixes: #43305

### CODE REVIEW

**Comment by xstefank** [comment]
And this is how it works now with this PR:


https://github.com/user-attachments/assets/c58284c8-d83c-445a-b858-16b966ccf211

**Comment by xstefank** [comment]
@gsmet I would really need this release asap for the book if possible :)

**Comment by geoand** [comment]
> @gsmet I would really need this releases asap for the book if possible :)

Guillame is on PTO (and @aloubyansky is handling releases), but even he was not, the release schedule is pretty strict and emergency releases (like `3.14.4`) are only warranted when a fix for a critical bug (affecting lots of users and effectively preventing them from using Quarkus) need addressing.

**Comment by aloubyansky** [comment]
@xstefank @phillip-kruger @alesj when you review, please set the corresponding backport labels if necessary. Thanks!

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by xstefank** [comment]
@geoand @aloubyansky I don't really care in which release it will be since I need to rebase the whole code in the book. But I just want it sooner than later because of rebases. 

Thanks @phillip-kruger for the review and merge :). If it's going to be in 3.15 that's also OK. Will be better for the book to be on LTS version.

**Comment by geoand** [comment]
Right, the plan is to have it in the LTS

**Pull request merged**
