### PR TITLE
build-parent split into a parent for apps, extensions and internal build

### LINKED ISSUE #1594: Propose a parent pom for external extensions
Currently, the extensions are embedded into the main Quarkus repository thus use the internal `build-parent` pom.xml.
To permits 3rd parties to develop their own extensions, it would be great to propose a public `quarkus-extension-parent` pom.

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Extensions/near/161188290

### PR DESCRIPTION
**Pull request by aloubyansky**
The objective of this effort is to provide a parent pom.xml for external extension developers and a parent pom.xml for application developers.
At this point, there is `build-parent/pom.xml` that combines configuration and deps for everything including the Quarkus-specific internal build deps and configs and properties, which makes it unusable outside of Quarkus repo.

With this change, app developers will have a choice of:
* keeping their poms in the style we've been promoting so far, i.e. `quarkus-bom` and the plugin config (and let them use their own parent poms);
* or using `quarkus-application-parent` as a parent pom from which the apps would inherit `quarkus-bom`, the plugin configs and the native profile.

Changes:
* Introduced `quarkus-application-parent` (flattened);
* Introduced `quarkus-extension-parent` (flattened);
* Integration tests are now using `quarkus-application-parent` as their parent;
* Extensions are now using `quarkus-extension-parent` as their parent;
* The content of the `integration-tests` directory now is:
  * `class-transformer` (uses `quarkus-extension-parent` as the base parent);
  * `common-jpa-entities` (base parent `quarkus-build-parent`);
  * `shared-library` (base parent `quarkus-build-parent`);
  * `extensions` (extension integration tests, base parent `quarkus-application-parent`);
  * `maven` (maven integration testsuite, base parent `quarkus-build-parent`):
    * includes `core`, `kogito`, `kotlin` and `scala` submodules;
* Common properties were consolidated in the root pom.xml.

Pom flattening is done by applying `org.codehaus.mojo:flatten-maven-plugin:flatten` and `io.quarkus:quarkus-maven-plugin:post-process-flattened-pom` (which makes sure that the flattened pom contains all the necessary properties and removes both of the flattening-related plugins from it).

Fixes #1594

### CODE REVIEW

**Comment by FroMage** [comment]
This seems like a move in the right direction.

**Review by rsvoboda — COMMENTED** [review]
@ aloubyansky In general I'm happy about this PR and refactoring you are doing, have some comments from my quick look:

> With this change, app developers will have a choice of quarkus-bom and quarkus-application-parent

Supporting 2 ways brings burden to the team, I had impression that BOM way ++ io.quarkus:quarkus-maven-plugin:0.22.0:create is pretty nice. Didn't notice people wanting Quarkus based parent.
Project can have one parent, but several BOMs can be imported, personally I'm in favor of BOM-only way

> Integration tests are now using quarkus-application-parent as their parent;
> extensions (extension integration tests, base parent quarkus-application-parent);

Isn't `quarkus-application-parent` in reality `quarkus-extensions-parent`-ish? At least that's how I feel it from the description.
Note: not meaning `quarkus-extensions-parent` from https://github.com/quarkusio/quarkus/blob/7108785f462da778f075585ac591dd3274168020/extensions/pom.xml, just same names

I think we should have one way for application developers (BOM if you ask me) and one way for extensions developers (parent could work here). Having multiple ways is harder to maintain and to keep consistent.

> **Docs**

This PR needs some documentation about BOMs and parent POMs, their structure and their primary use. People can easily pick the wrong one for their use-case now.

**Comment by aloubyansky** [comment]
> > With this change, app developers will have a choice of quarkus-bom and quarkus-application-parent
> 
> Supporting 2 ways brings burden to the team, I had impression that BOM way ++ io.quarkus:quarkus-maven-plugin:0.22.0:create is pretty nice. Didn't notice people wanting Quarkus based parent.
> Project can have one parent, but several BOMs can be imported, personally I'm in favor of BOM-only way

The only advantage of a parent POM in our case is pre-configured plugins that will be inherited from the parent POM. This makes the application POM cleaner in a sense that it contains mostly the app deps.

> > Integration tests are now using quarkus-application-parent as their parent;
> > extensions (extension integration tests, base parent quarkus-application-parent);
> 
> Isn't `quarkus-application-parent` in reality `quarkus-extensions-parent`-ish? At least that's how I feel it from the description.
> Note: not meaning `quarkus-extensions-parent` from https://github.com/quarkusio/quarkus/blob/7108785f462da778f075585ac591dd3274168020/extensions/pom.xml, just same names

Sorry, not sure what you mean. Application and extension parents have different plugin configs.

> I think we should have one way for application developers (BOM if you ask me) and one way for extensions developers (parent could work here). Having multiple ways is harder to maintain and to keep consistent.

The parent POM can be recommended (as a convenience) but can't be the only way. First, simply because it isn't one in its nature. Second, users may have requirements to use a different parent, in which case they would have to add the necessary BOMs and plugins to their POMs "manually".

**Comment by rsvoboda** [comment]
> Sorry, not sure what you mean. Application and extension parents have different plugin configs.

Sure. Just wanted to say that from the description where the parent is used it feels more like parent for extensions.

**Review by dmlloyd — DISMISSED** [review]
As far as I can tell, the execution of the change seems correct and the tests do pass.  The vast majority of this change are renames, so the risk I see is going to be in merge conflicts, but that's how these things go.

As for whether the change itself is correct, I think it is, but I think at least one other person should give an OK as well.

**Comment by dmlloyd** [comment]
And already there are conflicts. :slightly_smiling_face:

**Comment by aloubyansky** [comment]
@gsmet I think it can't get in w/o your review :)

**Comment by cescoffier** [comment]
What do we do about this one?

**Comment by aloubyansky** [comment]
First of all, do we want this change in principle? If yes, it has to be merged as soon as it's ready, because given its scope it's not practical to maintain a branch with it.

**Comment by gsmet** [comment]
@aloubyansky should we revisit this effort now or should we wait?

**Comment by kunal-kushwaha** [comment]
@aloubyansky : Can I rebase it and bring it up to date and submit a new PR if it's not a WIP?

**Comment by aloubyansky** [comment]
We haven't reached a consensus whether we want to provide a parent for apps. So, I'm not sure there is interest in this effort. If you feel like doing it anyway, go ahead. If it looks clean and useful, we'll merge it but no promises.

**Comment by aloubyansky** [comment]
Too old.

**Pull request closed without merging**
