### PR TITLE
Make s2i use Java 11 as the default

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
Pending a test by @maxandersen

**Comment by maxandersen** [comment]
@tqvarnst registry.access.redhat.com/ubi8/openjdk-11 works - but its rhel8, okey to make that default or should we use fabric8/s2i-java:3.1-java11

**Comment by maxandersen** [comment]
fyi, fabric8/s2i-java:3.1-java11 works as well as registry.access.redhat.com/ubi8/openjdk-11

**Comment by geoand** [comment]
Thanks @maxandersen !

I updated the PR to use UBI Java

**Review by maxandersen — APPROVED** [review]
+1 on getting this in as the current on is broken (fails on deploy as base image is java 8 but build is java 11)

And using the ubi8/ubi-java is thus a working default. 

Might be a update for final/.1 but in any case users would already post 1.7 have to override the image thus +1 on this.

**Pull request merged**
