### PR TITLE
Bump commons-codec to version 1.14

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
@gsmet

**Review by gastaldi — APPROVED** [review]
LGTM, want to add it to dependabot?

**Comment by oscerd** [comment]
Yeah, I noticed this because I was upgrading on Apache Camel too.

**Comment by gsmet** [comment]
@gastaldi please don't add the 1.5.0.Final version and add the backport tag. Otherwise this won't be backported to 1.5 and we will miss it.

Thanks.

**Comment by gastaldi** [comment]
Ah, so PRs that should be backported don't get a version now? That's news to me.

Thanks for the heads up.

**Comment by gsmet** [comment]
That's not new. You can set a version but it should be the one of master so currently 1.6.0 (see my email on quarkus-dev).

But it should never be the branched release as, once merged, the PR is not magically there, I need to backport it thus the label.

So feel free to add 1.6.0, I change the milestone when backporting and so when the commits are really in the branch.

**Comment by gastaldi** [comment]
For some reason I assumed 1.5.0 to be master. Can we have some kind of marker in the milestone version to indicate that it it's master?

**Pull request merged**
