### PR TITLE
Remove usage of java.util.logging.Logger

### LINKED ISSUE #699: Replace usage of java.util.logging by JBoss logging
We have parts of the code using `java.util.logging` such as `ShamrockTracingDynamicFeature`, `UndertowDeploymentTemplate`, `DataSourceProducer`.

They should use JBoss Logging.

We should also probably set up forbiddenapis to prevent this type of issue.

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #699

### CODE REVIEW

**Review by Sanne — DISMISSED** [review]
Thanks.  We might want to try to introduce "forbiddenapis" or something like that as it's a frequent mistake :)

**Comment by Sanne** [comment]
ah, it was actually incomplete. Please take https://github.com/gsmet/quarkus/pull/3 first ..

**Comment by gsmet** [comment]
Rebased, squashed and force-pushed. Thanks @Sanne !

**Review by Sanne — APPROVED** [review]
:+1:

**Pull request merged**
