### PR TITLE
fix: clarify kubernetes documentation and fix various typos / formatting issues

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand probably something we would want included in 1.4.1.Final if you have the time to review it.

**Comment by geoand** [comment]
I'll check it out immediately

**Review by geoand — APPROVED** [review]
Thanks a lot of this! It's certainly nice to have a fresh pair of eyes on this dense piece of documentation

**Comment by metacosm** [comment]
Thanks!

**Pull request merged**
