### PR TITLE
Add suffix to errors on shutdown

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This makes it clear that the error is not a runtime problem, but mostly
likely a result of the system shutting down with active requests.

Draft for now until we decide if we actually want this

### CODE REVIEW

**Comment by geoand** [comment]
I personally think it makes sense

**Comment by gsmet** [comment]
I think it makes sense.

**Review by geoand — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Note that there is no easy way to add a test, as QuarkusUnitTest stops checking the logs before shutdown. I could change this behavior but I am not sure if it would have wider ramifications.

**Comment by geoand** [comment]
I don't think it's terribly important to have that test.

**Pull request merged**
