### PR TITLE
Change default priority for jaxb customizers

### LINKED ISSUE #29803: Avoid errors on `JaxbContextCustomizer` priority order.
### Describe the bug

Quarkus 2.13.4 +

Interface `io.quarkus.jaxb.runtime.JaxbContextCustomizer` allows you to customize the JAXBContext. Is possible to have more than one JaxbContext in the same application. The CDI resolution that will prioritizes one bean on the other is based on the method "priority()"

```
int DEFAULT_PRIORITY = 0;
/**
     * Defines the priority that the customizers are applied.
     * A lower integer value means that the customizer will be applied after a customizer with a higher priority
     */
    default int priority() {
        return DEFAULT_PRIORITY;
    }
```

By default if the end user doesn't override the `priority()`, then the priority is going to be set to `0`, so an other bean on this project or in a dependency with a lower priority could override the intended behavior (I am thinking about hacking or a possible vulnerability). 

For example: 

End user app

```
@Singleton
public class CustomJaxbContextCustomizer implements JaxbContextCustomizer {

    @Override
    public void customizeMarshaller(Marshaller marshaller) throws PropertyException {
        marshaller.setProperty("jaxb.formatted.output", Boolean.TRUE);
    }
}

```

Dependency
```
@Singleton
public class CustomJaxbContextCustomizer implements JaxbContextCustomizer {

    @Override
    public void customizeMarshaller(Marshaller marshaller) throws PropertyException {
        marshaller.setProperty("jaxb.formatted.output", false);
    }

    @Override
    public int priority() {
        return -1;
    }
}
```

Suggested change:
```
int DEFAULT_PRIORITY = Integer.MIN_VALUE;

Also in the compare method check "if the incoming priority is the same as the current one" and in this case be sure to give priority to the current one(I think that the current implementation is fine on this topic, but just double check). 
```

If the enduser wants to leave open the `CustomJaxbContextCustomizer`, she/he could always `Override` his priority and set it to 0.

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/29803

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
I'm really not sure about that at all.

The reason mentioned was:

> I am thinking about hacking or a possible vulnerability

Which sounds a bit weak given as long as someone can push code that you execute, you're dead and believe me they won't use a customizer, they will just delete all your data or encrypt it :).

I think the current default priority makes sense. And we should at least consider this change extremely carefully because that could break existing applications relying on the current behavior.

Marking as `Request changes` so we don't merge this too quickly.

/cc @geoand @pjgg

**Comment by Sgitario** [comment]
> I'm really not sure about that at all.
> 
> The reason mentioned was:
> 
> > I am thinking about hacking or a possible vulnerability
> 
> Which sounds a bit weak given as long as someone can push code that you execute, you're dead and believe me they won't use a customizer, they will just delete all your data or encrypt it :).
> 
> I think the current default priority makes sense. And we should at least consider this change extremely carefully because that could break existing applications relying on the current behavior.
> 
> Marking as `Request changes` so we don't merge this too quickly.
> 
> /cc @geoand @pjgg

I also agree with your comment as stated in https://github.com/quarkusio/quarkus/issues/29803#issuecomment-1347798764. The only advantage I see is in terms of usability.

As an additional note, other customizers like object mapper use 0 as the default priority, so this is another point against merging this pull request.

**Comment by geoand** [comment]
I agree with @gsmet. This is really weird and it's not something we do in the other customizers that follow the same pattern...

**Comment by Sgitario** [comment]
> I agree with @gsmet. This is really weird and it's not something we do in the other customizers that follow the same pattern...

Based on your comments, I think we all agree against merging this pull request, so I'm closing it. cc @pjgg

**Comment by geoand** [comment]
Thanks @Sgitario

**Comment by pjgg** [comment]
Ok, thank you for the feedback!

**Pull request closed without merging**
