### PR TITLE
Introduce coroutine support in Reactive Messaging

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by evanchooly** [comment]
a lot of this looks *very* similar to the RR-kotlin code.  Which isn't surprising.  But should we consider making a common, say, `quarkus-kotlin-coroutines` module to share these bits?  I don't want to over engineer things but maybe it makes sense.

**Comment by geoand** [comment]
Indeed, the infrastructure classes are very similar.

We can certainly consider moving them into some common module.

But first I want to know if want I have done makes much in a reactive messaging context

**Comment by geoand** [comment]
For the producing methods, I am thinking that the request must already be executed as part of coroutine, like in a RESTEasy Reactive suspend function.

For processor methods, I can't think of what the proper way to support suspend functions should be...

**Review by cescoffier — APPROVED** [review]
It looks good to me.
It's a great first step.

Adding the support for processing methods would be nice (@Incoming and @Outgoing). We can maybe map them to methods returning a CompletionStage.

**Comment by geoand** [comment]
Cool, I'll drive this one home tomorrow and then look to expanding the support after that

**Comment by geoand** [comment]
This should be good to go now

**Comment by geoand** [comment]
@cescoffier I updated the PR with support for processing methods as well

**Comment by geoand** [comment]
@cescoffier do I need to be mindful of  SmallRye Reactive Messaging 3.3?

**Comment by geoand** [comment]
OK, so I'll merge this once CI completes unless you think I should wait for any reason

**Comment by cescoffier** [comment]
Go ahead!

**Comment by geoand** [comment]
I added one more commit that allows using `Emitter#send` as a suspending function as well

**Pull request merged**
