### PR TITLE
Ensure logs are displayed when application fails due to bootstrap config error

### LINKED ISSUE #8624: Exceptions thrown in bootstrap recorders prevent logging

### PR DESCRIPTION
**Pull request by geoand**
…fig error

Fixes: #8624

### CODE REVIEW

**Comment by geoand** [comment]
@stuartwdouglas after discussing with @dmlloyd [here](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/logging.20not.20displayed.20when.20bootstrap.20config.20providers.20errors), he mentioned that you might have written something similar somewhere?

**Comment by geoand** [comment]
Never mind, found it

**Comment by geoand** [comment]
I added a second commit explaining why I didn't go with `LoggingSetupRecorder#handleFailedStart` after all

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
@geoand can you squash the commits?

**Comment by geoand** [comment]
Commits squashed

**Pull request merged**
