### PR TITLE
Improve JavaDoc -> AsciiDoc transformation for lists, paragraphs and code blocks

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by gsmet** [comment]
@ppalaga the build is unhappy. Your changes seem to cause some issues in the AsciiDoc output.

**Comment by ppalaga** [comment]
Thanks for the reminder, @gsmet! Unfortunately I did not have any time to figure out what's wrong. Keeping it on my TODO.

**Comment by ppalaga** [comment]
5bc21a5: Fixed the failures in asciidoctor-maven-plugin

**Comment by ppalaga** [comment]
a768bb1: rebased. I cannot reproduce the failure in JavaDocConfigDescriptionParserTest.parseJavaDocWithCodeBlock locally.

**Comment by ppalaga** [comment]
15d56ac: rebased. I still cannot reproduce the issue locally. Are there perhaps some outdated files cached on the CI? Could please somebody try this locally?

**Comment by ppalaga** [comment]
`java.net.BindException: Address already in use` in the Amazon job cannot be caused by this change.

I hope this good merge now?

**Comment by ppalaga** [comment]
1616f28: rebased it would be nice if this could get merged before there are conflicts again

**Comment by ppalaga** [comment]
@gsmet is this good to merge?

**Review by gsmet — APPROVED** [review]
I confirm it significantly improves the output (tested with the `NativeConfig`).

**Comment by gsmet** [comment]
Thanks @ppalaga , sorry it slipped through the cracks until now!

**Pull request merged**
