### PR TITLE
Gradle: resources dir related fixes

### LINKED ISSUE #9299: Dev mode test gets stuck if there are no classes/resources in src/main
I am trying to add a dev mode test to the platform https://github.com/quarkusio/quarkus-platform/pull/64 but the test gets stuck during the test app boot.

## Steps to reproduce

The easiest way to reproduce is to take some existing dev mode test from Quarkus and move it to a new Maven module. I have done it for DevModeConstraintValidationTest:

1. Checkout this branch https://github.com/ppalaga/quarkus/commits/i9299
2. Make sure you have installed what's necessary in the local maven repo
3. 

```
cd extensions/hibernate-validator/devmode-test
mvn clean test
```

Expected: DevModeConstraintValidationTest should pass
Actual: DevModeConstraintValidationTest is stuck

Some observations: 

* There is an exception thrown from `io.quarkus.deployment.dev.DevModeMain.start()` which can be seen only after adding `t.printStackTrace()` by the end of `DevModeMain.start()`:

```
io.quarkus.bootstrap.BootstrapException: Failed to create the application model for io.quarkus:quarkus-hibernate-validator-devmode-test::jar:999-SNAPSHOT
        at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:301)
        at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:140)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:114)
        at io.quarkus.test.QuarkusDevModeTest.beforeEach(QuarkusDevModeTest.java:155)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:127)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to resolve artifact io.quarkus:quarkus-hibernate-validator-devmode-test:jar:999-SNAPSHOT
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveInternal(MavenArtifactResolver.java:166)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolve(MavenArtifactResolver.java:155)
        at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel(BootstrapAppModelResolver.java:171)
        at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel(BootstrapAppModelResolver.java:144)
        at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:287)
        ... 52 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.quarkus:quarkus-hibernate-validator-devmode-test:jar:999-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:262)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveInternal(MavenArtifactResolver.java:161)
        ... 56 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.quarkus:quarkus-hibernate-validator-devmode-test:jar:999-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:414)
        ... 60 more
```

* With the stock Quarkus maven the above stack trace is not shown in the console, the test is just stuck and nothing happens. This is caused by an attempt to close the app via `DevModeMain.stop()` that in turn calls `ApplicationStateNotification.waitForApplicationStop()`

I think the above demonstrates at lest two separate issues: 

1. The test app boot failure visible in the stack trace
2. The infinite loop in `ApplicationStateNotification.waitForApplicationStop()` after the start failure.

### LINKED ISSUE #9543: (1.5.0.CR1) Qute Template not found
**Describe the bug**
I get a template not found error in Quote when updating to 1.5.0.CR1

**Expected behavior**
Qute works just like it does in 1.4.2.Final

**Actual behavior**
I'm getting [this](https://gist.github.com/SR-Lut3t1um/b634649af59be67ef2d765ba4a8d6717) stacktrace

**To Reproduce**
 1. Download [this](https://gitlab.informatik.uni-bremen.de/tobias5/aut0m4t0n) repo
 2. Start the docker-compose to start a postgress database.
 3. Run quakus:dev when changing to 1.4.2.Final the templating-system will work.

**Configuration**
```properties
#Gradle properties
#Tue Feb 11 17:11:23 UTC 2020
quarkusPluginVersion=1.5.0.CR1
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=1.5.0.CR1
quarkusPlatformGroupId=io.quarkus

```

**Environment (please complete the following information):**
Java 11; 
Windows 10;
Gradle 6.4.1

### PR DESCRIPTION
**Pull request by aloubyansky**
* Add main resources dir to the application root paths for tests
* Support projects containing only resources without classes in dev mode.

Fixes #9543
Fixes #9299

### CODE REVIEW

**Comment by geoand** [comment]
>     * Support projects containing only resources without classes in dev mode.

Are you referring to #9299?

**Comment by geoand** [comment]
Seems like great work, :+1: :+1: :+1:

**Comment by aloubyansky** [comment]
> > ```
> > * Support projects containing only resources without classes in dev mode.
> > ```
> 
> Are you referring to #9299?

Perhaps :) I remember there was an issue about it but I didn't actually verify whether it fixes the one you referenced. I just could get my Gradle tests pass w/o those fixes.

**Comment by geoand** [comment]
> > > ```
> > > * Support projects containing only resources without classes in dev mode.
> > > ```
> > 
> > 
> > Are you referring to #9299?
> 
> Perhaps :) I remember there was an issue about it but I didn't actually verify whether it fixes the one you referenced. I just could get my Gradle tests pass w/o those fixes.

cc @ppalaga

**Comment by aloubyansky** [comment]
Ok, I've got
````
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ quarkus-hibernate-validator-devmode-test ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.hibernate.validator.test.devmode.DevModeConstraintValidationTest
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
            Powered by Quarkus 999-SNAPSHOT
2020-05-25 16:37:13,419 INFO  [io.quarkus] (Quarkus Main Thread) Quarkus 999-SNAPSHOT on JVM started in 1.811s. Listening on: http://0.0.0.0:8080
2020-05-25 16:37:13,421 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-05-25 16:37:13,421 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, hibernate-validator, resteasy, resteasy-jsonb]
2020-05-25 16:37:15,140 INFO  [io.qua.dep.dev] (vert.x-worker-thread-2) Changed source files detected, recompiling [/home/aloubyansky/git/quarkus/extensions/hibernate-validator/devmode-test/target/quarkus-dev-mode-test14997365065217792025/src/main/java/io/quarkus/hibernate/validator/test/devmode/TestBean.java]
2020-05-25 16:37:15,761 INFO  [io.quarkus] (Quarkus Main Thread) Quarkus stopped in 0.023s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
            Powered by Quarkus 999-SNAPSHOT
2020-05-25 16:37:16,116 INFO  [io.quarkus] (Quarkus Main Thread) Quarkus 999-SNAPSHOT on JVM started in 0.350s. Listening on: http://0.0.0.0:8080
2020-05-25 16:37:16,117 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-05-25 16:37:16,117 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, hibernate-validator, resteasy, resteasy-jsonb]
2020-05-25 16:37:16,117 INFO  [io.qua.dep.dev] (vert.x-worker-thread-2) Hot replace total time: 0.978s 
2020-05-25 16:37:16,145 INFO  [io.quarkus] (Quarkus Main Thread) Quarkus stopped in 0.000s
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.629 s - in io.quarkus.hibernate.validator.test.devmode.DevModeConstraintValidationTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
````
I guess this PR fixes that too.

**Comment by geoand** [comment]
Two birds - one stone :)

**Comment by ppalaga** [comment]
@aloubyansky I have sent a PR with tests for #9299 against the branch in your fork https://github.com/aloubyansky/quarkus/pull/2 . Could please check that they pass and add them to your PR if possible?

**Comment by aloubyansky** [comment]
@ppalaga those are failing actually. @jaikiran's commit helps it to fail fast.

**Comment by aloubyansky** [comment]
BTW, I'd probably prefer those tests to be in integration-tests.

**Comment by aloubyansky** [comment]
Ah, they did pass after a re-build.

**Comment by ppalaga** [comment]
Thanks for taking care, @aloubyansky !

> I'd probably prefer those tests to be in integration-tests.

Feel free to move them whereever you like.

**Comment by stuartwdouglas** [comment]
The windows failure looks related.

**Comment by aloubyansky** [comment]
Yes, I'll have a look. I did try it yesterday on a windows laptop and it
passed.

**Comment by aloubyansky** [comment]
Thanks to @gsmet I figured out the cause. This should be good now.

**Comment by aloubyansky** [comment]
All green

**Review by gsmet — APPROVED** [review]
Let's merge this. And it's nice to have tests for all this now :).

**Comment by geoand** [comment]
@aloubyansky is our hero!!!

**Pull request merged**
