### PR TITLE
Make order of QuarkusTestResourceLifecycleManager predictable

### PR DESCRIPTION
**Pull request by geoand**
This applies for implementations that don't specify the order

Relates to: #22025

### CODE REVIEW

**Comment by gsmet** [comment]
I'm on the verge about backporting it. I'll let you decide.

**Comment by geoand** [comment]
I think it's perfectly safe to backport

**Comment by famod** [comment]
So the bigger part of this change is "just" for more readable code, while the actual ordering adjustments are those `LinkedHashSet`s, right?

**Comment by geoand** [comment]
Right, there are 2 commits.

The first one makes the code more readable, the second one addresses the order issue

**Review by famod — APPROVED** [review]
👍

**Pull request merged**
