### PR TITLE
Only register providers if RESTEasy is not doing it.

### LINKED ISSUE #11810: Warnings when running the OpenAPI tests
When running the OpenAPI tests, we end up with these warnings which don't look like normal:

```
[INFO] Running io.quarkus.smallrye.openapi.test.jaxrs.OpenApiWithResteasyPathHttpRootDefaultPathTestCase
2020-09-02 11:42:22,076 WARN  [io.qua.dep.QuarkusAugmentor] (main) Using Java versions older than 11 to build Quarkus applications is deprecated and will be disallowed in a future release!
2020-09-02 11:42:22,492 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FileProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,492 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.sse.SseEventOutputProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,545 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class io.quarkus.resteasy.runtime.vertx.JsonObjectWriter is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,545 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ByteArrayProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,545 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class io.quarkus.resteasy.runtime.vertx.JsonArrayWriter is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,545 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.StringTextStar is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,545 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.StreamingOutputProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,545 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ReaderProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,545 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,547 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DataSourceProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,547 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.AsyncStreamingOutputProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,547 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FileRangeWriter is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,547 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.InputStreamProvider is already registered.  2nd registration is being ignored.
2020-09-02 11:42:22,788 INFO  [io.quarkus] (main) Quarkus 1.8.0.CR1 on JVM started in 0.450s. Listening on: http://0.0.0.0:8081
2020-09-02 11:42:22,788 INFO  [io.quarkus] (main) Profile test activated. 
2020-09-02 11:42:22,789 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-openapi, spring-di, spring-web, swagger-ui, vertx, vertx-web]
```

/cc @phillip-kruger @kenfinnigan

### PR DESCRIPTION
**Pull request by phillip-kruger**
This fix #11810.
I am not 100% sure if this is the correct fix. It ended up having nothing to do with OpenAPI, but rather with Spring-Web and JAX-RS. Since OpenAPI use both it hightlight the issue.

I tried all sort of things, but this seems to be the simplest. But I do not know enough about the Spring Web extension to know if this is ok. Maybe @geoand can have a look ?

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Native tests fail, so this is not the right fix. @geoand - any suggestions ?

**Comment by geoand** [comment]
I'll have to take a look - hopefully later on today :)

**Comment by geoand** [comment]
Weird that this doesn't show up in the Spring Web integration test

**Comment by phillip-kruger** [comment]
Yea I can not pin point the issue...

**Comment by geoand** [comment]
I'll start looking into it now

**Comment by geoand** [comment]
I'll close this in favor of https://github.com/quarkusio/quarkus/pull/11898

**Pull request closed without merging**
