### PR TITLE
Add ability to specify default JAX-RS roles allowed

### LINKED ISSUE #10362: @PermitAll is misleading
The @PermitAll annotation is misleading and has cost me some effort to figure out its meaning -
perimit all implies that this opens up an endpoint for all requests - but what is actually meant is
@PermitAllRoles or @PermitAllExistingRoles or something like that.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Also improve docs around this

Fixes #10362

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi Stuart @stuartwdouglas This looks fine.
How does it work when the proactive authentication is disabled when the authentication is effectively run at the JAX-RS level ?

**Comment by stuartwdouglas** [comment]
It works the same way it would if you had put @RolesAllowed on all JAX-RS classes.

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@stuartwdouglas 

> It works the same way it would if you had put @RolesAllowed on all JAX-RS classes.

What is not clear to me is whether it will be useful to specify these properties when the proactive-authentication is disabled since in that case the security checks are done at the JAX-RS level (given [your comment](https://github.com/quarkusio/quarkus/issues/10362#issuecomment-885981943) that the JAX-RS level constraints can't be pushed up).

**Comment by sberyozkin** [comment]
I think even if the proactive authentication is disabled the general concept works the same way (without these props, i.e, HTTP config is checked first etc), so the new properties should not be redundant in case of the security checks shifted to the JAX-RS layer when the proactive auth is disabled - I believe it is clear now to me. Please merge

**Comment by sberyozkin** [comment]
Hmm... that said, the reason the security checks are done at the JAX-RS layer when the proactive authentication is disabled is because one can check if the resource is secured or not at the JAX-RS layer (even if no HTTP path configuration is set).
May be I'm confused but if I wonder if it makes sense to clarify in the docs the properties may be needed only when the proactive auth is enabled (which is a default)

**Comment by stuartwdouglas** [comment]
It can be used either way. It provides a way of allowing you to override your default rules via annotations.

If you look at the original issue the if you use path based auth to require /api to be authenticated, you can't then use @PermitAll to override that.

**Pull request merged**
