### PR TITLE
DRYness: consolidate duplicated code in extension build plugins

### PR DESCRIPTION
**Pull request by holly-cummins**
I've added a dependency on devtools-common from all of the extension build plugins, so that I can eliminate duplicated code I introduced in the last changeset.

The implementation and the test method are just copied across from the duplicated versions.

### CODE REVIEW

**Comment by holly-cummins** [comment]
Scratch that about just copying and pasting. I've copy and pasted the implementation, but I made an error in the common-tools test setup that only showed in the github actions, so I've switched to System Stubs for controlling the environment variables in tests.

**Comment by holly-cummins** [comment]
Scratch that about just copying and pasting. I've copy and pasted the implementation, but I made an error in the common-tools test setup that only showed in the github actions, so I've switched to System Stubs for controlling the environment variables in tests.

**Comment by holly-cummins** [comment]
@aloubyansky, do you mind looking at this?

**Comment by aloubyansky** [comment]
Let's abandon the `quarkus-bootstrap-maven-plugin`. If we didn't have an aggregating root `pom.xml`, it would fail the build due to a circular dependency between the `bootstrap` project and the `tools`, those are supposed to independent projects.

**Comment by holly-cummins** [comment]
> Let's abandon the `quarkus-bootstrap-maven-plugin`. If we didn't have an aggregating root `pom.xml`, it would fail the build due to a circular dependency between the `bootstrap` project and the `tools`, those are supposed to independent projects.

@aloubyansky do you mean "remove it from the product" or "go back to the WET implementation without the circular dependency on that module" or "not add the scm information in that module?" 

When I was looking I noticed that there's definitely some extensions in the quarkiverse using that one.... but it is adding a maintenance overhead now.

**Comment by aloubyansky** [comment]
I meant to not keep enhancing it. Projects that are still using it should have warnings in their build logs. We could probably open PRs for those that we know about.
I probably wouldn't remove it yet.

**Comment by holly-cummins** [comment]
> I meant to not keep enhancing it. Projects that are still using it should have warnings in their build logs. We could probably open PRs for those that we know about. I probably wouldn't remove it yet.

I did think removing it sounded drastic, but some teams move fast. :) 

After this PR, I *think* all scm-related future enhancements in it will be passive, because the brains will be in the common code. Or do you think I should take it out of this PR?

**Comment by aloubyansky** [comment]
We don't want to introduce a circular dependency between the tools and bootstrap. I meant to leave the bootstrap plugin out of this change.

**Comment by holly-cummins** [comment]
Got it, thanks! In my first version of the changes I did introduce a new module, `devtools-extensions` to avoid the circular dependency and other dependency badness, but then I decided it was too much clutter. I've removed bootstrap from the changes, so it will have the original support and not get any 'reading the pom' or 'adding the tag' enhancements. I think that's fine, given it's deprecated.

**Review by aloubyansky — APPROVED** [review]

**Comment by geoand** [comment]
Is this one good to go? If so, please merge

**Comment by holly-cummins** [comment]
This is good to go - the test failures are #28779.

**Comment by geoand** [comment]
Thanks.

I'll let @aloubyansky push the button

**Pull request merged**
