### PR TITLE
Add system properties source to CodeGenerator config sources

### LINKED ISSUE #27431: Add default config sources to codegen config
### Description

Seems that the `Config` instance passed to the `CodeGenProvider` implementation does not have the default config sources configured. Therefore, if you need to resolve system properties, you're forced to look them up manually via `System.getProperty`.

It'd be nicer if you could resolve them automatically via the `Config` instance. It'd make overriding of config values via the command line a bit simpler to handle.

### Implementation ideas

Add `setAddDefaultSources(true)` to the config builder in `CodeGenerator.trigger()`.

### PR DESCRIPTION
**Pull request by geoand**
Resolves: #27431

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@geoand It looks good, did you have a way to check if it works? ;)

**Comment by geoand** [comment]
I do not, I am hoping @jamesnetherton does :)

**Comment by jamesnetherton** [comment]
I did a quick local test and I could resolve system properties via the provided `Config` object  in my `CodeGenProvider`.

**Comment by geoand** [comment]
Great, thanks for checking!

**Review by michalszynkiewicz — APPROVED** [review]

**Pull request merged**
