### PR TITLE
QUARKUS-1501: DevServicesKafkaProcessor: Always expose to Docker host network

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/QUARKUS-1501

### CODE REVIEW

**Comment by manstis** [comment]
@geoand FYI.

**Review by geoand — APPROVED** [review]
Thanks, let's do this

**Comment by geoand** [comment]
FWIW, there is no need to open a JIRA ticket for these kinds of issues

**Comment by manstis** [comment]
> FWIW, there is no need to open a JIRA ticket for these kinds of issues

OK.. in "my world" I need a JIRA even to breath :smirk:

**Pull request merged**
