### PR TITLE
Optimize RequestContext for the single entry use case

### PR DESCRIPTION
**Pull request by franz1981**
This is using some lock-free tecnique to NOT use a full-fat ConcurrentHashMap to hold `RequestContextState`'s entries, if not necessary i.e. single entry and empty.
Moreover, inspecting the assembly produced, it seems that initializing volatile fields in the constructor with something different from a default value (e.g. `null` or `0`)  makes the JIT to emit a full StoreLoad barrier (that on x86 translates into a costy atomic operation) although not required for safe-publication: I've used `VarHandle` in order to save such cost (that looks like a perf bug on JIT to me TBH).
Additionally I've checked using Java Object Layout, that the `RequestContextState` is exactly the same in most scenarios because of 4 bytes padding due to 8 bytes alignments.

The single entry use case seems very frequent on benchmarks, but I don't know if is that usual in the real world @mkouba @Sanne are more aware of it.

I'll soon publish some end 2 end benchmarking result (for the record, in case) while microbenchmarks on https://github.com/mkouba/arc-benchmarks are already very promising, obviously (because they are indeed using empty and single entry cases)

For `RequestContextActivationBenchmark`:

RequestContextActivationBenchmark

For `RequestScopedProxyInvocationBenchmark`:
RequestScopedProxyInvocationBenchmark

### CODE REVIEW

**Comment by mkouba** [comment]
> The single entry use case seems very frequent on benchmarks, but I don't know if is that usual in the real world

It's very common in the http benchmarks because the `io.quarkus.vertx.http.runtime.CurrentVertxRequest` is always created and initialized with the current `RoutingContext`. And in the real world? Well it depends. If a user has no `@RequestScoped` bean (note that JAX-RS resources are `@Singleton` by default) then yes, there will be a lot of single entry use cases.

**Comment by Ladicek** [comment]
I'd venture to say that in the real world apps, there's typically a non-trivial number of request-scoped beans. From top of my head, RESTEasy Reactive produces some, Hibernate ORM and/or transactions, security.

**Comment by mkouba** [comment]
> I'd venture to say that in the real world apps, there's typically a non-trivial number of request-scoped beans. From top of my head, RESTEasy Reactive produces some, Hibernate ORM and/or transactions, security.

Note that those beans must be actually used (and initialized; i.e. not only injected) in order to be stored in the context. Having said that, I also think that this optimization would not pay off in real apps.

**Comment by geoand** [comment]
> RESTEasy Reactive produces some

It produces plenty actually :)

**Comment by geoand** [comment]
Thought: can we use the number of request scoped beans which we know at build time to do some kind of optimization?

**Comment by mkouba** [comment]
> Question/thought: can we use the number of request scoped beans which we know at build time to do some kind of optimization?

This number could be used to set the max size of the underlying map. Which is probably not very useful, or?

**Comment by franz1981** [comment]
> This number could be used to set the max size of the underlying map. Which is probably not very useful, or?

it can be useful if all of these will be always used, but probably it's not like that

**Comment by geoand** [comment]
> Which is probably not very useful, or?

I haven't looked at the code, so I was just wondering and hoping you and @franz1981 would have a definitive answer :)

**Comment by franz1981** [comment]
@geoand 

Given that the single value use case seems relevant just for benchs, bud, I suggest you to not go into the rabbit hole of the current impl (that is'a lock-free algo, actually): i'm going to add a commit that simplify it just by sizing differently the CHM

**Comment by mkouba** [comment]
> > Which is probably not very useful, or?
> 
> I haven't looked at the code, so I was just wondering and hoping you and @franz1981 would have a definitive answer :)

I think that we would have to use/create an optimized structure for this, and not CHM. Maybe @franz1981 has something prepared already ;-)

**Comment by geoand** [comment]
Okay, thanks folks

**Comment by franz1981** [comment]
@mkouba 
> I think that we would have to use/create an optimized structure for this

We have the NonBlocking hash maps on https://github.com/JCTools/JCTools but TBH here the costy ops are:
1. hashcode computation
2. pointer chasing 
3.  allocation rate in "common" scenario (TBD)

The current implementation makes the 1->2 entries transition a bit more costy, but already allocate CHM with 2 elements on demand. 
it's complicated but already makes benchmarks better and if we choose something more approriate then just 2 elements, it can save some memory for existing uses cases

**Comment by franz1981** [comment]
@mkouba @geoand  @Sanne I've just added a commit to simplify this in a different CHM lazy presizing and looking what numbers I got on micro and end 2 end (but still) benchmarks. And we can decide if there's any number that worth configuring it (other then 16).

Ideally we would like to be able how many beans will be added and just use a simple array, precomputing the indexes, but I have to learn more how this work to understand if is feasable

**Comment by Sanne** [comment]
> Question/thought: can we use the number of request scoped beans which we know at build time to do some kind of optimization?

If we can enumerate them all at build time, then it would be super cool to assign a unique id to each of them to use as an index of an array. Same could be done for other scopes, so to not use maps? Might need some consideration for sparse arrays if the range gets large though.

**Comment by Sanne** [comment]
Just wondering, why was this closed in the end? Was there some follow up?

**Comment by mkouba** [comment]
> Just wondering, why was this closed in the end? Was there some follow up?

I don't remember but I guess that we took a different path. @franz1981 closed this pull request :shrug:.

**Comment by franz1981** [comment]
The reason for this @mkouba was in the comments in this issue where it seems that assuming a small amount of beans to not be a safe bet. TBH it just means that:
1. we should try hard to know it upfront
2. we should use a better structure which grow in a more gentle way than CHM

If you feel the changes here to be safe I can reopen it in no time

**Comment by mkouba** [comment]
> If you feel the changes here to be safe I can reopen it in no time

I don't think it's necessary...

**Pull request closed without merging**
