### PR TITLE
Fix #9780 Manage debezium in quarkus-bom-test instead of quarkus-bom

### LINKED ISSUE #9780: Manage debezium in quarkus-bom-test instead of quarkus-bom
Followup https://github.com/quarkusio/quarkus/issues/8593#issuecomment-638775288

Quarkus BOM should not manage Debezium because it is only used as a test scoped dep in itests, so it should be managed in quarkus-bom-test.

A PR follows.

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #9780

### CODE REVIEW

**Comment by ppalaga** [comment]
The failure in hibernate-orm-panache-kotlin does not seem to be related.

**Comment by geoand** [comment]
Yeah, it's not related to this PR

**Review by geoand — APPROVED** [review]
LGTM, but I'll let @gsmet have the final say

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Makes perfect sense.

**Pull request merged**
