### PR TITLE
Close the TestResourceManager in afterAll

### PR DESCRIPTION
**Pull request by jaikiran**
@geoand, @stuartwdouglas, in context of https://github.com/quarkusio/quarkus/pull/11785, what's happening there (even after the `@BeforeEach` fix) is that the `KubernetesClientTest` in its `before` uses a new (and correct) `MockServer` instance and adds "endpoints" to it. However, the kubenetes client APIs (in the application code) end up invoking on a different instance of `MockServer` one which was started by a different test, specifically a `QuarkusProdModeTest` (`AbsentConfigMapPropertiesTest` in this case). This is because the client APIs (in the application code) check for a system property to decide the "master url" of Kubernetes. Ir so happens that the `AbsentConfigMapPropertiesTest` sets it to one. 

The `QuarkusProdModeTest` has logic to clear these system properties when the `TestResourceManager` instance is closed. But my debugging shows that this `TestResourceManager#close` which we link to the JUnit `ExtensionContextStore` gets called way too late, IMO. I'm seeing it being called after the complete testsuite has finished (i.e. all tests in kubenetes-client instead of after just `AbsentConfigMapPropertiesTest` gets completed). This means that the system properties never get cleared before subsequent tests run. It's not just system properties by the way, all kinds of resources which were started and were meant to be closed (like the webserver) are all closed after the complete testsuite is done.

Perhaps this too is playing a role in the CI resource usage issues? Are we holding on to these for a bit too long?

Is it intentional that we create (once and) attach this `TestResourceManager` to the `ExtensionContext.Store` instead of dealing with it in the `beforeAll`/`afterAll` of each test, just like we do it for other things in that extension, like the `process`, the `application` itself?

Just to see what impact/regression any change in this area might have, I have done the initial changes in this PR to give it a try.

### CODE REVIEW

**Comment by geoand** [comment]
Excellent analysis @jaikiran! 

Yeah, the TestResourceManager should be unique for `QuarkusProdModeTest` and should definitely not leak out when those tests are done

**Review by geoand — APPROVED** [review]

**Comment by jaikiran** [comment]
If this CI run completes successfully, we will have to review the similar pattern in our other test extensions `QuarkusDevModeTest` and `QuarkusUnitTest`

**Comment by geoand** [comment]
You are absolutely right

**Review by gsmet — CHANGES_REQUESTED** [review]
Except if I didn't understand what's happening there, I'm -1.

The fact that `TestResourceManager` is closed after the end of the test suite is by design.

It's used to start databases, Docker containers and so on. We don't want to restart them after each test class.

If the mock server needs to be cleared for each test then we shouldn't use a test resource.

**Comment by gsmet** [comment]
Or we could have a method we call on the resource after each test that could be used to clear the state.

**Comment by geoand** [comment]
@gsmet this is only for `QuarkusProdModeTest`

**Comment by geoand** [comment]
If we really want to keep things as they are, then the Kubernetes tests that use `QuarkusTestResource` should be moved into a different surefire run

**Comment by gsmet** [comment]
So you would stop/start any resource for each test? What if they are mixed with other tests also starting the resources? It cannot happen?

**Comment by geoand** [comment]
That is exactly what happened in this situation... We have `@QuarkusTest` and `QuarkusProdModTest` in the same surefire run and they both use test resources.

It does make sense that `QuarkusProdModTest` be isolated, but I do understand the point you are making. And TBH, the change made here might not work for QuarkusDevTest - because we might already be assuming the behavior you mention.

So I guess you are probably right and we should not do this, but instead just break the tests in question into a different surefire run. @jaikiran do yo want to do that or should I?

**Comment by jaikiran** [comment]
> So I guess you are probably right and we should not do this, but instead just break the tests in question into a different surefire run. @jaikiran do yo want to do that or should I?

Hello @geoand, please go ahead. I'm in the middle of a few other things at work.

**Comment by geoand** [comment]
Will do. 

Thank you very much for your detective work on this @jaikiran, it's extremely valuable!

**Comment by geoand** [comment]
I'll open another PR, so we don't cross wires with this one

**Comment by geoand** [comment]
#11809 supersedes this

**Pull request closed without merging**
