### PR TITLE
Allow CORS same origin requests

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Thanks @stuartwdouglas, it does look like it will offer a more optimal way of comparing Origin and the request URI, and if necessary, we can follow up with adding a flag making the same origin check optional

**Review by maxandersen — CHANGES_REQUESTED** [review]
-1 on blindly allowing same origin hosts by default. You are basically trusting the client to speak the truth allowing to trick Quarkus into accept from any host name (not just localhost) which is problematic.

we should check what other fwks do here - the only reason it worked before was due to another CORS filter bug.

**Comment by stuartwdouglas** [comment]
> -1 on blindly allowing same origin hosts by default. You are basically trusting the client to speak the truth allowing to trick Quarkus into accept from any host name (not just localhost) which is problematic.
> 
> we should check what other fwks do here - the only reason it worked before was due to another CORS filter bug.

That is the point. 

CORS is intended to prevent trusted clients (i.e. browsers implementing the web security model) from being tricked by a malicious site into sending requests to other sites.

If the client is compromised then CORS is useless, the client can send any origin it wants so no matter what is configured the client can send something that would be expected. This type of issue is prevented by requiring authentication.

**Comment by sberyozkin** [comment]
Re-opening for another round of reviews

**Review by maxandersen — APPROVED** [review]
+1 after reviewing and discussion on enabling same origin even when additional hosts specified for cors.

**Comment by sberyozkin** [comment]
Thanks @stuartwdouglas @maxandersen

**Pull request merged**
