### PR TITLE
dependabot.yml_cleanup

### PR DESCRIPTION
**Pull request by Pankraz76**
no extra explanation needed if sorted properly then its easy to spot mistakes that are out of order

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks but I don't know really. Even if not perfect, we categoried them a bit and sorting them alphabetically might not be an improvement.

I'm -0 on this.

**Comment by punkratz312** [comment]
thanks for the fast response. yes i get your point.  in my point of view the comments are redundant information and the eye can spot obvious mistakes very easy if its well sorted. i would recommend to give it a try its easy reverted. plus now if its sorted there is one rule just he alphabet in the case before its not that easy to spot where to add a new entity. 
the same in .propertie files once applies the pattern is pretty usefull for tidy looking code.

**Comment by gastaldi** [comment]
I prefer having them sorted in categories instead of alphabetically, so I agree with @gsmet here.

**Comment by punkratz312** [comment]
all right, both opinions got their benefit so thanks for the valuable exchange. its my pleasure

**Pull request closed without merging**
