### PR TITLE
Allow finer tuning of shared network usage by DevServices

### LINKED ISSUE #39156: Add the ability to ask for devservices to use the shared network
### Description

As of now, the only way to ask for dev services to be run in the shared network is to produce a `DevServicesSharedNetworkBuildItem`, which I think is only done here : https://github.com/quarkusio/quarkus/blob/607ece496231d6278471e76c337d8637bc67c640/test-framework/junit5/src/main/java/io/quarkus/test/junit/IntegrationTestUtil.java#L292.

It would be great to be able to ask for it through configuration. I first thought that was what quarkus.<extension>.devservice.shared was for, it turned out it was not ;).

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by lbroudoux**
This PR follows up on this discussion: https://github.com/quarkusio/quarkus/discussions/38398
and embeds enhancement for this issue: https://github.com/quarkusio/quarkus/issues/39156

It allows finer tuning of shared network usage by DevServices.

By default, database-related DevServices make their container join the shared network as soon as it exists. At first, it was
only when running integration tests using a containerized application. However, there exist situations where the user wants to force the usage of a shared network, or other DevServices may require a shared network in dev or test mode (see the discussion and issue).

The proposed change allows us to clearly determine if joining a shared network is required (by the user, by integration test) so that DevServices can only join on purpose.

I'll prepare another PR for documentation update as explained in contribution guide.

Signed-off-by: Laurent Broudoux <laurent.broudoux@gmail.com>

- Closes: #39156

### CODE REVIEW

**Comment by jtama** [comment]
@lbroudoux there a network labeling point (https://github.com/quarkusio/quarkus/pull/39177/files#diff-eadbd09b0263a696107aca146819cd82f60481ca5879c0b1160c2f1f8fc02dbb)

**Review by geoand — APPROVED** [review]
I think this makes perfect sense, thanks a lot!

**Comment by lbroudoux** [comment]
> @lbroudoux there a network labeling point (https://github.com/quarkusio/quarkus/pull/39177/files#diff-eadbd09b0263a696107aca146819cd82f60481ca5879c0b1160c2f1f8fc02dbb)

Oh yes... I wasn't sure of the status of this part, and it wasn't on the critical path for my issue, so I chose the easy path. Let me know (@jtama and @geoand) if it's closely related and validated and I'll take some time to update the PR.

**Comment by jtama** [comment]
It's really helpfull when you're outside of an extension, if you're developing an Test resource.

**Comment by geoand** [comment]
@jtama can you provide @lbroudoux a suggestion on how to update the PR?

**Comment by geoand** [comment]
@lbroudoux is there anything you need from us to address the final concern?

Thanks

**Comment by lbroudoux** [comment]
Hello! Sorry for late reply... I was travelling these last days. I think I'll be able to have a look at it this afternoon or tomorrow. Will keep you posted.

**Comment by geoand** [comment]
🙏🏼

**Comment by lbroudoux** [comment]
Hey @geoand and @jtama!
I just added a commit to report the network labeling point. Sorry for delay.

**Pull request merged**
