### PR TITLE
Integrate AzureMonitorRegistry into Micrometer Extension

### PR DESCRIPTION
**Pull request by mqs24d**
Integration of the existing micrometer implementation for Azure Insights Monitor into the quarkus-micrometer extension.

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]
Looks reasonable to me. Will let @ebullient take a look to make sure I didn't miss anything

**Comment by kenfinnigan** [comment]
Just realized, I think we need the commits squashed? Can't recall the exact policy on that. @gsmet?

**Review by ebullient — APPROVED** [review]

**Comment by ebullient** [comment]
Please squash the commits, but this is great! Thank you. =)

**Comment by mqs24d** [comment]
> Please squash the commits, but this is great! Thank you. =)

squashing the commits and force push?

**Comment by mqs24d** [comment]
Please help me! How could the "Quarkus CI / Native Tests - Misc4 (pull_request) fail" it has nothing to do with the changes i made. So i have no clue what to do.

**Comment by ebullient** [comment]
We're working on that one.. something odd is happening w/ the native build. You're correct it has nothing to do with your changes. See #12478

**Pull request merged**
