### PR TITLE
Don't convert WebApplicationException in REST Client when produced by a custom mapper

### LINKED ISSUE #42275: REST Client Replaces WebApplicationException Instances Returned By ExceptionMapper
### Describe the bug

REST Client's that use an exception mapper to return custom exception types may have those instances unexpected replaced by the `RestClientRequestContext`.

When the exception returned by an exception mapper is itself a subclass of `WebApplicationException`, then [logic in RestClientRequestContext replaces that instance with a new instance of `ClientWebApplicationException`](https://github.com/quarkusio/quarkus/blob/5f35abd3d9ed04aed28a97803970604611806018/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java#L182-L195).

### Expected behavior

The exception instance returned by the exception mapper is thrown.

### Actual behavior

A new exception of type `ClientWebApplicationException` is thrown.

### How to Reproduce?

The failing Quarkus test in the attached reproducer demonstrates the actual vs expected behavior of this exception mapper.

```java
@RegisterRestClient(configKey = "greeting-service")
public interface GreetingService {

  /**
   * Retrieves a greeting for the given individual.
   *
   * @param name name of the individual
   * @return a greeting
   */
  @GET
  @Path("/greeting")
  String greet(@QueryParam("name") String name);

  /**
   * Because {@link GreetingException} extends {@link jakarta.ws.rs.WebApplicationException},
   * Quarkus will replace the instance returned by this method with a new {@link
   * ClientWebApplicationException}.
   */
  @ClientExceptionMapper
  static RuntimeException toException(Response response) {
    if (response.getStatus() == 400) {
      final var error = response.readEntity(GreetingError.class);
      return new GreetingException(Response.Status.BAD_REQUEST, error);
    }
    return null;
  }
}
```

[quarkus-rest-client-exception-mapper-changes-type.zip](https://github.com/user-attachments/files/16460877/quarkus-rest-client-exception-mapper-changes-type.zip)

### Output of `uname -a` or `ver`

Darwin pixee-mbp-gilday.localdomain 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode)

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7 (8b094c9513efc1b9ce2d952b3b9c8eaedaf8cbf0) Maven home: /Users/jgilday/.m2/wrapper/dists/apache-maven-3.9.7-bin/33482774/apache-maven-3.9.7 Java version: 21.0.3, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "14.5", arch: "aarch64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
The idea is that if a user has opted to create an exception, we should always honor it - even if it's a WebApplicationException

- Fixes: #42275

### CODE REVIEW

**Comment by geoand** [comment]
@FroMage WDYT?

**Comment by FroMage** [comment]
My only objection would be the original security mistake of JAX-RS which is that client and server share the same exception type, and so it's too easy for client calls to leak client call details to server users. Things like status code, reason, headers, bodies.

That's why our clients don't throw `WebApplicationException` instances. Now, in the case of custom mappers… Given that they're separate exception mappers to the server mappers, perhaps that's alright. But given that the original issue was avoiding security leaks, make sure you keep this in mind while reviewing the feature?

I can't think a security reason to refuse this PR, myself.

**Comment by geoand** [comment]
> But given that the original issue was avoiding security leaks, make sure you keep this in mind while reviewing the feature?

Yeah, the use in the reported issue is legit and does things properly

**Comment by geoand** [comment]
@FroMage mind reviewing this?

Thanks

**Review by FroMage — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
🙏🏼

**Pull request merged**
