### PR TITLE
Fix handling of `@WithTestResource` and Global resources

### LINKED ISSUE #43034: Injection of BrowserContext stopped working on main/999-SNAPSHOT
### Describe the bug

Injection of `BrowserContext` stopped working on main/999-SNAPSHOT branch but it works on 3.14.2 version

```java

@QuarkusTest
@WithPlaywright
public class EmailTagTest {

    @InjectPlaywright
    BrowserContext context;

    @Test
    void test(){
        assertNotNull(context);
    }

}
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #43034

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
I don't the the DevTools failures are related, but I have no idea what those tests do

**Comment by holly-cummins** [comment]
> I don't believe the the DevTools failures are related, but I have no idea what those tests do

I haven't looked at the failures all, just basing my comments off this comment. It's possible they are related, because the devtools tests exercise the quickstarts, and the quickstarts end up exercising a good portion of the codebase, including resource-related tests.

**Comment by geoand** [comment]
Interesting, thanks for the info!

I'll have to look into it more

**Comment by holly-cummins** [comment]
I just had a quick peek and it's the gradle devtools test cases that are failing, and the gradle tests are also failing. So the devtools test was a canary for the gradle problem. If you fix the gradle project tests, devtools should also start working. 

(And I'll be interested to see your fix, since I have also broken gradle on my branch. :) )

**Comment by geoand** [comment]
Sounds like way more than I was hoping I would have to do 😿

**Comment by geoand** [comment]
I actually see:

```
2024-09-05T07:07:29.3234814Z Caused by: io.quarkus.bootstrap.prebuild.CodeGenException: Failed to find com.google.protobuf:protoc:linux-x86_64:exe among dependencies
2024-09-05T07:07:29.3236628Z 	at io.quarkus.grpc.deployment.GrpcCodeGen.makeExecutableFromPath(GrpcCodeGen.java:447)
2024-09-05T07:07:29.3237932Z 	at io.quarkus.grpc.deployment.GrpcCodeGen.initExecutables(GrpcCodeGen.java:419)
2024-09-05T07:07:29.3239216Z 	at io.quarkus.grpc.deployment.GrpcCodeGen.trigger(GrpcCodeGen.java:144)
2024-09-05T07:07:29.3240252Z 	at io.quarkus.deployment.CodeGenerator.lambda$trigger$4(CodeGenerator.java:206)
2024-09-05T07:07:29.3241545Z 	at io.quarkus.deployment.CodeGenerator.callWithClassloader(CodeGenerator.java:181)
2024-09-05T07:07:29.3242792Z 	at io.quarkus.deployment.CodeGenerator.trigger(CodeGenerator.java:203)
2024-09-05T07:07:29.3243890Z 	at io.quarkus.deployment.CodeGenerator.initAndRun(CodeGenerator.java:80)
```

so I am still thinking this could be something else entirely...

**Comment by holly-cummins** [comment]
I agree that it's hard to see how that stack trace could be related.

**Comment by geoand** [comment]
Seems like I have my work cut out for me :(

**Comment by geoand** [comment]
@cescoffier the failures I see boil down to something like:

```
2024-09-05T07:24:52.8251081Z Caused by: io.quarkus.bootstrap.prebuild.CodeGenException: Failed to find com.google.protobuf:protoc:linux-x86_64:exe among dependencies
2024-09-05T07:24:52.8253025Z 	at io.quarkus.grpc.deployment.GrpcCodeGen.makeExecutableFromPath(GrpcCodeGen.java:447)
2024-09-05T07:24:52.8254528Z 	at io.quarkus.grpc.deployment.GrpcCodeGen.initExecutables(GrpcCodeGen.java:419)
2024-09-05T07:24:52.8255856Z 	at io.quarkus.grpc.deployment.GrpcCodeGen.trigger(GrpcCodeGen.java:144)
2024-09-05T07:24:52.8257166Z 	at io.quarkus.deployment.CodeGenerator.lambda$trigger$4(CodeGenerator.java:206)
2024-09-05T07:24:52.8258587Z 	at io.quarkus.deployment.CodeGenerator.callWithClassloader(CodeGenerator.java:181)
2024-09-05T07:24:52.8259929Z 	at io.quarkus.deployment.CodeGenerator.trigger(CodeGenerator.java:203)
2024-09-05T07:24:52.8261215Z 	at io.quarkus.deployment.CodeGenerator.initAndRun(CodeGenerator.java:80)
```

has something changed recently?

**Comment by cescoffier** [comment]
Oh, this is why @gsmet reopened the issue.

Yes, a profile based approach got merged recently, do only select the protoc of the matching OS/arch

**Comment by geoand** [comment]
I can reproduce the problem locally on this PR **and** on `main`.

**Comment by geoand** [comment]
> Yes, a profile based approach got merged recently, do only select the protoc of the matching OS/arch

So it seems this broke the Gradle and DevTools tests. Any idea what needs to be done to fix them?

**Comment by geoand** [comment]
@gsmet @cescoffier @alesj any idea about the grpc failures?

**Comment by cescoffier** [comment]
The PR causing them has been reverted. So rebasing should fix your CI.

**Comment by geoand** [comment]
Thanks, let's see

**Pull request merged**
