### PR TITLE
Add a vertx-web integration test with minimal dependencies

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by gsmet** [comment]
What's the rationale of this? I know @cescoffier had plans to add more Vert.x tests so we should coordinate with him.

**Comment by ppalaga** [comment]
My motivation is to make sure that issues like https://github.com/quarkusio/quarkus/issues/4047 won't happen.

**Comment by gsmet** [comment]
And the issue you have is solved in master? Because the test passes and I don't see any fix.

**Comment by ppalaga** [comment]
Yes, #4047 does not occur in master.

**Comment by stuartwdouglas** [comment]
Vert.x is now used for all HTTP, so every integration test makes sure it works correctly.

This is a -1 from me, native image tests are very resource intensive and I don't really know if this one adds much.

**Comment by ppalaga** [comment]
The minimal dependency set was supposed to be the main added value of this test. But I can understand your concerns. Feel free to close. In the worst case we'll catch any issues in Camel Quarkus.

**Comment by gsmet** [comment]
OK, let's close it then.

**Pull request closed without merging**
