### PR TITLE
Ensure the Kind manifests are generated

### LINKED ISSUE #28078: quarkus-kind extension does not create manifests (kind.yml/.json)
### Describe the bug

When using the `quarkus-kind` extension, no manifests are created and the deployment subsequently fails.

I'm using the following command to build the project: 
`gradle build -Dquarkus.container-image.build=true -Dquarkus.kubernetes.deploy=true`

### Expected behavior

I expect the `quarkus-kind` extension to create a `kind.yml` and `kind.json` file.

### Actual behavior

No files are created. The deployment fails.

### How to Reproduce?

[crickets.zip](https://github.com/quarkusio/quarkus/files/9605066/crickets.zip)

Use the following command: `gradle build -Dquarkus.container-image.build=true -Dquarkus.kubernetes.deploy=true`

### Output of `uname -a` or `ver`

Darwin V6624MV3PM 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 17.0.4 2022-07-19

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.4.2 ------------------------------------------------------------  Build time:   2022-03-31 15:25:29 UTC Revision:     540473b8118064efcc264694cbcaa4b677f61041  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.4 (Eclipse Adoptium 17.0.4+8) OS:           Mac OS X 12.6 aarch64

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/28078

Some context: the Kind manifests are only generated when adding the `quarkus-kind-deployment` dependency, and it should be generated when using `quarkus-kind` too. This is also the reason why this issue has not been spotted in the tests.

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @linvsendian

**Comment by iocanel** [comment]
@Sgitario: It's not clear what changed with this rename.
Maybe it's just how github presents the change:

```
...ices/io.dekorate.ManifestGeneratorFactory
vs
...ices/io.dekorate.ManifestGeneratorFactory
```

**Comment by Sgitario** [comment]
> @Sgitario: It's not clear what changed with this rename. Maybe it's just how github presents the change:
> 
> ```
> ...ices/io.dekorate.ManifestGeneratorFactory
> vs
> ...ices/io.dekorate.ManifestGeneratorFactory
> ```

The file's view does not help. I simply moved the file `io.dekorate.ManifestGeneratorFactory` from `quarkus-kind-deployment` to `quarkus-kind` module.

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
