### PR TITLE
[WIP] Deprecate enableJni option and always consider it true

### LINKED ISSUE #6101: Deprecate enableJni option as GraalVM 19.3 requires JNI support
With GraalVM 19.3.0, JNI always needs to be enabled.

We should:
- deprecate enableJni (and any other option allowing to set it)
- always consider it true
- warn if it has been set to false

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #6101 

This PR is ready for a review, but it shouldn't be merged into `master` before we're sure that the following Quarkus release depends on GraalVM `19.3.0` or greater.

### CODE REVIEW

**Comment by gwenneg** [comment]
I'm putting a WIP label to make sure it isn't merged too soon.

**Review by gsmet — APPROVED** [review]
Looks good to me but I agree we need to merge it very last minute.

I'm still unsure we will be able to have the RSS regression fixed in 19.3.1.

**Comment by gwenneg** [comment]
Thanks for the review!

**Comment by gsmet** [comment]
If we get to support both versions, we will have to tune that one a bit.

**Comment by gwenneg** [comment]
Superseded by #6792.

**Pull request closed without merging**
