### PR TITLE
Aws dynamodb sdk2 extension

### PR DESCRIPTION
**Pull request by marcinczeczko**
An extension that provides AWS DynamoDB client based on AWS SDK2 that supports async netty client.
An extension adds support for both Async (Netty) and Blocking (Apache) HTTP clients.

Mentioned in #1716

### CODE REVIEW

**Comment by gsmet** [comment]
@marcinczeczko any reason why you closed this one? Did you have issues you wanted to discuss?

**Comment by marcinczeczko** [comment]
@gsmet There were couple of reasons. I wanted to cleanup commit history, and then started struggling with native compilation (and realised that new native-image option is supported on graalvm rc15 while I was using rc14. I think the biggest issue I was facing was with one build pipeline on quarkus azure dev - for some reason jdk11 pipeline was failing because a local dynamodb started by maven-exec-plugin started after the test, but not before, no matter what maven phase I picked (it works fine on windows & native pipelines).
Anyway, I'm happy to open my PR once again (as new one).

**Comment by gsmet** [comment]
@marcinczeczko I think it's an interesting contribution. A lot of our core people are currently working on demos and talks, that's why we might not be as reactive as we could be.

But if you can create a rebased PR and explain the issues you have in the PR, we will try to help for sure.

**Comment by marcinczeczko** [comment]
Cool, please find PR #2193

**Pull request closed without merging**
