### PR TITLE
Make sure the logged process ID is correct in native mode

### LINKED ISSUE #39854: 'quarkus.log.console.format' '%i' Process ID fixed at build time
### Describe the bug

it looks like 'Process ID' is fixed at build time when running in native mode. In JVM mode works as expected.

### Expected behavior

the process ID is different every run

### Actual behavior

the process ID is always the same

### How to Reproduce?

1. create the app
`quarkus create app org.acme:getting-started --extension='rest' && cd getting-started`
2. edit the application.properties to include the format:
`quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %i%n`
3. build the native executable
`mvn package -Pnative  -Dmaven.test.skip=true`
4. run the app
`./target/getting-started-1.0.0-SNAPSHOT-runner`
5. close and run the app again

> root@- /getting-started # ./target/getting-started-1.0.0-SNAPSHOT-runner
2024-04-03 09:47:28.286 **181019**
2024-04-03 09:47:28.286 **181019**
2024-04-03 09:47:28.286 **181019**
^C2024-04-03 09:47:30.899 **181019**
> root@- /getting-started # ./target/getting-started-1.0.0-SNAPSHOT-runner
2024-04-03 09:47:31.911 **181019**
2024-04-03 09:47:31.911 **181019**
2024-04-03 09:47:31.911 **181019**
^C2024-04-03 09:49:08.309 **181019**

### Output of `uname -a` or `ver`

Linux rubin-ec84.de 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.2" 2024-01-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

java version "21.0.2" 2024-01-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #39854

### CODE REVIEW

**Comment by geoand** [comment]
@zakkak another instance of the image metrics test causing issues:

```
2024-04-03T10:22:46.7791862Z 2024-04-03 10:22:46,761 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-h2, jdbc-postgresql, micrometer, narayana-jta, narayana-lra, resteasy, resteasy-client, resteasy-jackson, resteasy-jaxb, resteasy-jsonb, resteasy-mutiny, scheduler, security, security-properties-file, servlet, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, swagger-ui, vertx, websockets, websockets-client]
2024-04-03T10:22:46.8258981Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.666 s <<< FAILURE! -- in io.quarkus.it.main.ImageMetricsITCase
2024-04-03T10:22:46.8263218Z [ERROR] io.quarkus.it.main.ImageMetricsITCase.verifyImageMetrics -- Time elapsed: 0.002 s <<< FAILURE!
2024-04-03T10:22:46.8265776Z org.opentest4j.AssertionFailedError: Expected analysis_results.classes.jni to be within range [62 +- 1%] but was 63 ==> expected: <true> but was: <false>
2024-04-03T10:22:46.8267631Z 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
2024-04-03T10:22:46.8269173Z 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
```

**Comment by dmlloyd** [comment]
Hmm I think this indicates at least two bugs. In both the SmallRye and LogManager case, we should use the JDK API to get the PID; we must be caching it. I'll have a look today.

**Comment by dmlloyd** [comment]
smallrye/smallrye-common#299

**Comment by geoand** [comment]
💪🏼

**Comment by geoand** [comment]
Closing this

**Comment by dmlloyd** [comment]
jboss-logging/jboss-logmanager#464

**Pull request closed without merging**
