### PR TITLE
Execute test plan with the deployment classloader as the TCCL

### LINKED ISSUE #24229: Continuous testing is not picking up custom JUnit extension from same module
### Describe the bug

A Junit extension, e.g. a `org.junit.jupiter.api.extension.BeforeAllCallback`, that is registered via `src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension` is not picked up when `mvn quarkus:test` (CT) is run in that module.

If CT is run in another module that depends on the module that contains the extension, everything works as expected!

### Expected behavior

"local" extension is run

### Actual behavior

"local" extension is not run/found

### How to Reproduce?

[q_ct-junitext.zip](https://github.com/quarkusio/quarkus/files/8222903/q_ct-junitext.zip)

- `mvn verify` ✔️ 
- run test in Eclipse ✔️ 
- `mvn quarkus:test` ❌ 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17.0.2, vendor: BellSoft

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.3.Final and 2.7.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fix #24229

### CODE REVIEW

**Comment by aloubyansky** [comment]
I should add a test though

**Review by famod — APPROVED** [review]
Yeah, test would be nice.

Apart from that: LGTM; I tested it successfully in my real project and Stuart already said it's the proper way.
I'm only asking myself what's left for which we need the augmentation classloader (set in `ModuleTestRunner`)?

**Comment by famod** [comment]
PS: IMO it makes sense to backport, but I'll leave this to you.

**Comment by aloubyansky** [comment]
Yes, I'll look into adapting the reproducer provided by @famod

**Comment by gsmet** [comment]
@aloubyansky I will merge this tonight latest as I want this in CR1. If you don't have the time to write the test now, no biggie, we can include it later.

**Comment by aloubyansky** [comment]
Unfortunately, I couldn't create a test case that would fail. I tried using `ContinuousTestingTestUtils` as a base utility but my test would still pass for 2.7.5.Final. Looks like we need a "cleaner" test framework for CT. Let's merge this one for now.

**Pull request merged**
