### PR TITLE
fix: #2470 Use mirror to download dependencies if applicable

### PR DESCRIPTION
**Pull request by jycr**

### CODE REVIEW

**Comment by aloubyansky** [comment]
This should move to MavenRepoInitializer as well. Would you mind doing it, @jycr ?

**Comment by jycr** [comment]
> This should move to MavenRepoInitializer as well. Would you mind doing it, @jycr ?

I will check if I can access to MirrorSelector in MavenRepoInitializer (currently, I get it through current RepositorySystemSession)

**Comment by aloubyansky** [comment]
Have a look at newSession method. It creates one from settings.

**Comment by gsmet** [comment]
@jycr FYI, I plan to release 0.16.0 on Wednesday. It would be nice to have this one in if you can find the time to finish it.

**Comment by aloubyansky** [comment]
Thanks @jycr. This PR contains way too many changes that shouldn't be done as part of the issue it addresses though. I hoped to see changes you did for the proxy applied in a similar fashion to the mirrors. Let me know if you want me to take care of this one. Thanks!

**Comment by jycr** [comment]
> Thanks @jycr. This PR contains way too many changes that shouldn't be done as part of the issue it addresses though. I hoped to see changes you did for the proxy applied in a similar fashion to the mirrors. Let me know if you want me to take care of this one. Thanks!

Sure, I will send you a new "quick and dirty" PR (like I done it with proxy issue).
I will try to do that tomorrow.

**Pull request closed without merging**
