### PR TITLE
Do not delete BrotliDecoder and let GraalVM DCE do it for us

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by zakkak** [comment]
Please don't merge this before https://github.com/graalvm/mandrel/actions/runs/897038267 completes (testing it against Mandrel 21.1.0).

**Comment by zakkak** [comment]
CI passed, so that's OK to be merged.

I am not sure I understand why we "We need to delete this class" though. Is this to prevent users from trying to use brotli due to some known issue with `native-image`?

**Comment by gsmet** [comment]
No it's because it doesn't work right now (it uses some native library and work is needed to make it work).

**Comment by cescoffier** [comment]
@zakkak should be fine no?

**Comment by zakkak** [comment]
> No it's because it doesn't work right now (it uses some native library and work is needed to make it work).

In that case it would be nice to have a GH issue and link to it in the comment so that we can better track it.

> @zakkak should be fine no?

Yup it's fine!

**Pull request merged**
