### PR TITLE
Upgrade to Mutiny 0.10.0

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
Do not merge until @Sanne has checked, thanks

**Comment by Sanne** [comment]
Hi @jponge , Hibernate Reactive was updated: no issues! Thanks

I'll approve this but please check the failed CI tests before merging.

**Review by Sanne — APPROVED** [review]

**Comment by jponge** [comment]
Failing / cancelled jobs do not seem to have Mutiny issues as far as I can tell.

**Comment by gsmet** [comment]
It's the first time I see all of them cancelled at the same time so I wouldn't be so sure.

**Review by gsmet — CHANGES_REQUESTED** [review]
All the jobs were cancelled in the same test:
```
Running io.quarkus.mailer.InjectionTest
```
which uses Mutiny.

So I'm pretty sure there's something fishy here and it needs to be checked.

**Comment by jponge** [comment]
I'll have a look later tonight, I have some emergencies to deal with due to the lockdown. 

Perhaps @cescoffier has an idea meanwhile.

**Comment by jponge** [comment]
Before I go off the grid for a few hours, I ran `./mvnw clean install -f extensions/mailer/pom.xml` (Java 11):

```
[INFO] Running io.quarkus.mailer.InjectionTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.584 s <<< FAILURE! - in io.quarkus.mailer.InjectionTest
[ERROR] io.quarkus.mailer.InjectionTest  Time elapsed: 1.584 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Undeclared build item class io.quarkus.deployment.builditem.TransformedClassesBuildItem
	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:487)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.IllegalArgumentException: Undeclared build item class io.quarkus.deployment.builditem.TransformedClassesBuildItem
	at io.quarkus.builder.Messages.undeclaredItem(Messages.java:13)
	at io.quarkus.builder.BuildResult.consume(BuildResult.java:48)
	at io.quarkus.runner.bootstrap.StartupActionImpl.extractTransformers(StartupActionImpl.java:256)
	at io.quarkus.runner.bootstrap.StartupActionImpl.<init>(StartupActionImpl.java:50)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:135)
	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:442)
	... 40 more

[INFO] Running io.quarkus.mailer.MailTemplateValidationTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.174 s <<< FAILURE! - in io.quarkus.mailer.MailTemplateValidationTest
[ERROR] io.quarkus.mailer.MailTemplateValidationTest  Time elapsed: 0.174 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Build failed with wrong exception, expected class javax.enterprise.inject.spi.DeploymentException but got java.lang.IllegalArgumentException: Undeclared build item class io.quarkus.deployment.builditem.TransformedClassesBuildItem ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
	at io.quarkus.test.QuarkusUnitTest.lambda$setExpectedException$1(QuarkusUnitTest.java:126)
	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:477)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by cescoffier** [comment]
Ok, something is off:
```
[DEBUG] at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:60)
[DEBUG] at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
[DEBUG] at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:42)
[DEBUG] at io.quarkus.mailer.runtime.MailTemplateInstanceImpl$3.apply(MailTemplateInstanceImpl.java:132)
[DEBUG] at io.quarkus.mailer.runtime.MailTemplateInstanceImpl$3.apply(MailTemplateInstanceImpl.java:127)
```

and we are stuck here.

**Comment by cescoffier** [comment]
@jponge and there is a:
```
[DEBUG] at io.smallrye.mutiny.operators.UniMemoizeOp.drain(UniMemoizeOp.java:133)
[DEBUG] at io.smallrye.mutiny.operators.UniMemoizeOp.onItem(UniMemoizeOp.java:160)
```

in the stack trace ;-)

**Comment by cescoffier** [comment]
I've pushed a fix. 
It's definitely a bug in the new Memoization operator (@jponge). I've worked around it.

**Comment by gsmet** [comment]
I would prefer we wait for a fix in Mutiny before merging this. It's widely used by our user base and this bugs looks... blocking :).

**Comment by cescoffier** [comment]
The security issues looked related. It seems to be another `cache()` issue.

**Comment by cescoffier** [comment]
Putting this PR on hold. There is something wrong with the memorization operator that needs to be fixed upstream. Who knew that cache was that hard? :-D

**Comment by jponge** [comment]
Totally agree, better merge later a 0.10.1 😉

**Comment by jponge** [comment]
Replaced by https://github.com/quarkusio/quarkus/pull/13034

**Pull request closed without merging**
