### PR TITLE
Fix servlet file listing

### LINKED ISSUE #28028: Undertow: servletContext.getResourcePaths("/") not listed in PROD mode
### Describe the bug

I have a simple ApplicationInitializer to print out all the available servlet resource paths...

```java
public class ApplicationInitializer implements ServletContainerInitializer {

	private static final Logger logger = Logger.getLogger(ApplicationInitializer.class.getName());

	@Override
	public void onStartup(Set<Class<?>> c, ServletContext servletContext) throws ServletException {
		logger.info("Checking servlet resource paths...");

		Set<String> resourcePaths = servletContext.getResourcePaths("/");
		for (String resourcePath : resourcePaths) {
			logger.info("Resource: " + resourcePath);
		}
		
		if (resourcePaths.isEmpty()) {
			logger.warning("NO servlet resource paths found!");
		}
	}
}
```

When running in **DEV** mode `mvn quarkus:dev` the following is printed out it finds the mapped `/index.html`:
```
2022-09-17 07:51:08,575 INFO  [org.acm.ApplicationInitializer] (Quarkus Main Thread) Checking servlet resource paths...
2022-09-17 07:51:08,577 INFO  [org.acm.ApplicationInitializer] (Quarkus Main Thread) Resource: /index.html
```

When running in **PRD** mode `mvn clean package -DskipTests && java -jar target/quarkus-app/quarkus-run.jar` it doesn't find anything:
```
2022-09-17 07:49:05,376 INFO  [org.acm.ApplicationInitializer] (main) Checking servlet resource paths...
2022-09-17 07:49:05,376 WARNING [org.acm.ApplicationInitializer] (main) NO servlet resource paths found!
```

### Expected behavior

All servlet resource paths should be available in both DEV and PRD mode.

### Actual behavior

Resource Paths are only available in DEV mode.

### How to Reproduce?

[quarkus-servlet.zip](https://github.com/quarkusio/quarkus/files/9591559/quarkus-servlet.zip)

1. Unzip the reproducer attached
2. Run `mvn clean quarkus:dev` and see the servlet paths printed out `2022-12-27 13:00:20,489 INFO  [org.acm.ApplicationInitializer] (Quarkus Main Thread) Resource: /index.html`
3. Run `mvn clean package -DskipTests && java -jar target/quarkus-app/quarkus-run.jar` and see the WARNING that no paths found `2022-12-27 13:01:06,297 WARNING [org.acm.ApplicationInitializer] (main) NO servlet resource paths found!`

### Output of `uname -a` or `ver`

OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Output of `java -version`

OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: C:\Tools\apache-maven-3.8.5 Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: C:\Tools\jdk-11.0.10 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #28028

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
The windows failure of the test seems relevant

**Comment by stuartwdouglas** [comment]
Yea, something is going on there. underlying.getResource() must be returning null, although I am not sure why at this point.

**Review by melloware — APPROVED** [review]

**Comment by geoand** [comment]
Gotta love Windows...

```
java.lang.RuntimeException: Unable to get listed resource foo\bar\bar.html from directory  for path  from underlying manager io.undertow.server.handlers.resource.ClassPathResourceManager@8843d9
2023-01-30T05:55:21.6413585Z 	at io.quarkus.undertow.runtime.KnownPathResourceManager$DirectoryResource.list(KnownPathResourceManager.java:137)
2023-01-30T05:55:21.6414290Z 	at io.undertow.servlet.spec.ServletContextImpl.getResourcePaths(ServletContextImpl.java:272)
2023-01-30T05:55:21.6414905Z 	at io.quarkus.undertow.test.ResourceManagerTestCase$ContextPathServlet.doGet(ResourceManagerTestCase.java:53)
2023-01-30T05:55:21.6415429Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
2023-01-30T05:55:21.6415825Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
2023-01-30T05:55:21.6416312Z 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
2023-01-30T05:55:21.6416987Z 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
2023-01-30T05:55:21.6417628Z 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
2023-01-30T05:55:21.6418209Z 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
2023-01-30T05:55:21.6418854Z 	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
2023-01-30T05:55:21.6419600Z 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
2023-01-30T05:55:21.6420479Z 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
2023-01-30T05:55:21.6421186Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2023-01-30T05:55:21.6421862Z 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
2023-01-30T05:55:21.6422747Z 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
2023-01-30T05:55:21.6423643Z 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
2023-01-30T05:55:21.6424465Z 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
2023-01-30T05:55:21.6425269Z 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
2023-01-30T05:55:21.6426109Z 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
2023-01-30T05:55:21.6426859Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2023-01-30T05:55:21.6427402Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2023-01-30T05:55:21.6428081Z 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
2023-01-30T05:55:21.6428723Z 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
2023-01-30T05:55:21.6429291Z 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
2023-01-30T05:55:21.6429817Z 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
2023-01-30T05:55:21.6430464Z 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
2023-01-30T05:55:21.6431151Z 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
2023-01-30T05:55:21.6431755Z 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:595)
2023-01-30T05:55:21.6432385Z 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
2023-01-30T05:55:21.6433037Z 	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
2023-01-30T05:55:21.6433674Z 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:120)
2023-01-30T05:55:21.6434200Z 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
2023-01-30T05:55:21.6434749Z 	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
2023-01-30T05:55:21.6435310Z 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:417)
2023-01-30T05:55:21.6435839Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2023-01-30T05:55:21.6436297Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-01-30T05:55:21.6436769Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2023-01-30T05:55:21.6437273Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2023-01-30T05:55:21.6437759Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2023-01-30T05:55:21.6438248Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2023-01-30T05:55:21.6438764Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2023-01-30T05:55:21.6439329Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-01-30T05:55:21.6439739Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-01-30T05:55:21.6439923Z 
```

**Comment by stuartwdouglas** [comment]
I think https://github.com/quarkusio/quarkus-http/pull/111 should be the fix.

**Comment by melloware** [comment]
Can this be merged before the Quarkus 3 cutover this weekend?

**Comment by melloware** [comment]
Bump?

**Comment by stuartwdouglas** [comment]
Looks like there is still an issue, I will need to have another look when I have time.

**Comment by melloware** [comment]
@stuartwdouglas now that 3.0.0 Final is out maybe one more look at this one?

**Comment by stuartwdouglas** [comment]
I don't have access to windows which makes it hard to debug. It is almost certainly a / vs \ issue somewhere in the resource handling code.

**Comment by melloware** [comment]
OK I run on Windows let me try your code and see if I can figure out the error.

**Comment by melloware** [comment]
OK I don't see how this would work.  

image

Its looking for Windows "foo\bar\bar.html" but the underlying ClassPathResourceManager it has Unix prefix `META-INF/resources/"

If I correct the slashes to be UNix slashes it no longer errors but then returns too many files

**Comment by melloware** [comment]
I submitted my PR based on this one if someone wants to kick off the build so I can see whether it passes on Windows and Linux now.  I did all my testing on Windows and its all working.

https://github.com/quarkusio/quarkus/pull/32656

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/32656

**Pull request closed without merging**
