### PR TITLE
Move Dev UI ClassLoading to Runtime

### LINKED ISSUE #41722: GrpcDevUIProcessor#grpcAction() is problematic from a CL point of view
> [!NOTE]
> This is part of my class loader work and is going to be very problematic soon.

`GrpcDevUIProcessor#grpcAction()` which is a deployment bit is called from the Dev UI at runtime and actually performs some class loading from the deployment class loader, which is closed at that point (so we shouldn't load classes from it anymore).

I think the problem was somehow identified because of this comment:

```java
 /**
  * This gets called during runtime from the Dev UI JsonRPC Service to test a grpc call
  * We go to Flow to stay in the JDK, else we have classpath issues.
  */
```

I'm not entirely sure how we want to fix it but I would really like us to get rid of this pattern (if we can find a better solution).

Also I'm not entirely sure it's the only problematic piece of the Dev UI (I'm pushing something to CI to try to detect these problems but it might break too many things to be meaningful). @phillip-kruger do you recall some other similar hacks?

/cc @cescoffier

### PR DESCRIPTION
**Pull request by phillip-kruger**
@cescoffier - I had to pull in a new dependency in runtime module, that is not great. 

Fix #41722

### CODE REVIEW

**Comment by cescoffier** [comment]
@phillip-kruger which tests are failing?

**Comment by gsmet** [comment]
Maybe some of the work needs to be done at build time? Or some info from the work done at build time passed to a recorder?

**Comment by phillip-kruger** [comment]
@gsmet there are still a lot being done at build time. I have tried another way (creating all the objects and stubs during build time and just use them (via DevConsoleManager). However, to create the stubs you need the host and port, and those are runtime only config. So at this point if seems this PR is the way to go. I am sure the maintainers of this grpc extension might be able to do a better job than me (I don't know enough about grpc)

**Comment by phillip-kruger** [comment]
> @phillip-kruger which tests are failing?

Seems ok now. I had some local failures, but I might have been my environment ?

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
@gsmet do you think you could check if this fix the leak you found around gRPC / Dev UI ?

**Comment by phillip-kruger** [comment]
@cescoffier @gsmet I have check against the draft PR that @gsmet has ready and I can confirm this fix it.

**Pull request merged**
