### PR TITLE
Handle configured parent first resources

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Configured parent first resources need to be placed on the class path to
take effect.

This fixes it for maven, a similar fix will be needed for gradle

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
@glefloch will you have time to do the corresponding change in Gradle?

**Comment by glefloch** [comment]
Sure. I think I can do it today.

**Comment by aloubyansky** [comment]
Thanks @glefloch

**Comment by srigano** [comment]
Hi,
after test, still the same with 2.7.1.Final:

022-02-08 21:47:10,064 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (Hibernate post-boot validation thread for <default>) SQL Error: -4230, SQLState: 42968
2022-02-08 21:47:10,067 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (Hibernate post-boot validation thread for <default>) [jcc][t4][10509][13454][4.31.10] La connexion au serveur de données a échoué. La licence IBM Data Server for JDBC and SQLJ n'était pas valide 
ou n'a pas été activée pour le sous-système DB2 for z/OS. Si vous vous connectez directement au 
serveur de données et que vous utilisez DB2 Connect Unlimited Edition for System z, effectuez
l'étape d'activation en exécutant le programme d'activation du kit d'activation de licence.
Si vous utilisez une autre édition de DB2 Connect, procurez-vous le fichier de licence,
db2jcc_license_cisuz.jar, qui se trouve dans le kit d'activation de licence et suivez les instructions d'installation  
pour inclure ce fichier dans le chemin d'accès aux classes. ERRORCODE=-4230, SQLSTATE=42968

2022-02-08 21:47:10,072 ERROR [io.qua.hib.orm.run.sch.SchemaManagementIntegrator] (Hibernate post-boot validation thread for <default>) Failed to run post-boot validation: org.hibernate.exception.SQLGrammarException: Unable to open JDBC Connection for DDL execution

**Comment by stuartwdouglas** [comment]
What does your parent first config look like?

**Comment by srigano** [comment]
here is my config file: (************************************** for private datas)

#general
application.version=1.0.0
application.name=vega

#db2z
quarkus.datasource.db-kind=db2
quarkus.datasource.jdbc.url=**************************************
quarkus.hibernate-orm.database.default-schema=**************************************
quarkus.datasource.username=**************************************
quarkus.datasource.password=**************************************
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.max-size=10
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.class-loading.parent-first-artifacts=db2jccdriver:db2jcc_license_cisuz-10.5.0.8
quarkus.class-loading.reloadable-artifacts=db2jccdriver:db2jcc_license_cisuz-10.5.0.8

**Comment by stuartwdouglas** [comment]
You can't be both reloadable and parent first, although in this case I am not sure if it would cause this specific problem. 

Are there any other DB2 related artifacts in the dependency tree? I don't really have any experience with DB2, but I am guessing it is looking for a license file using a wrong ClassLoader.

**Comment by srigano** [comment]
Hi,

It works since 2.7.1.Final !
Thank you very much.

**Pull request merged**
