### PR TITLE
ArC: fix the situation when a framework bean uses an application decorator

### PR DESCRIPTION
**Pull request by Ladicek**
ArC-generated classes for framework beans are by default _not_ application classes. This causes problems in hierarchical classloader environments (dev/test mode) when there is an application decorator that applies to the framework bean.

This commit fixes that issue by turning the ArC-generated classes for framework beans into application classes whenever an application decorator applies. This makes package access impossible, which is an unfortunate downside.

The problem doesn't exist in a flat classloading environment, such as prod mode.

### CODE REVIEW

**Comment by Ladicek** [comment]
I couldn't figure out a better solution. I tried turning all `loadClass()` calls in ArC into `loadClassFromTCCL()`, but that didn't help, so this is the only solution I can think of.

**Review by mkouba — APPROVED** [review]
This fix seems to be reasonable.

I wonder if we should mention this in the CDI ref guide :thinking:.

**Review by manovotn — APPROVED** [review]
I agree this is the best we can do to make the behavior consistent.

> This commit fixes that issue by turning the ArC-generated classes for framework beans into application classes whenever an application decorator applies. This makes package access impossible, which is an unfortunate downside.

> I wonder if we should mention this in the CDI ref guide

We could have a configuration knob for the previous behavior which would enable the pack private access and also serve as a documentation. Although I am not sure it's worth it.

**Comment by Ladicek** [comment]
To be honest, I'd rather do a bytecode transformation that turns package-private injection points (and other things, probably?) into `protected` fields/methods :-) That should fix the package access issue.

Documenting the package access restriction in the CDI reference guide just seems like accepting defeat.

**Comment by manovotn** [comment]
> To be honest, I'd rather do a bytecode transformation that turns package-private injection points (and other things, probably?) into `protected` fields/methods :-) That should fix the package access issue.

I don't think we want to do this everywhere and detecting just these cases might be challenging.
It is definitely an option if the problem surfaces again though.

> 
> Documenting the package access restriction in the CDI reference guide just seems like accepting defeat.

Yea, plus the CDI ref. guide is too broad for this peculiar case.

**Comment by mkouba** [comment]
> > Documenting the package access restriction in the CDI reference guide just seems like accepting defeat.
> 
> Yea, plus the CDI ref. guide is too broad for this peculiar case.

A single line in the https://quarkus.io/guides/cdi-reference#supported_features_and_limitations after _"Decoration of built-in beans, such as Event, is not supported"_ would be enough.

**Comment by Ladicek** [comment]
I'm afraid it's not gonna be just a "single line", or it's gonna be a _long_ single line. How about this?

> If a decorator provided by the application applies to beans provided by external libraries, package-private injection points (and other CDI constructs) are not going to work in those beans in dev/test mode.

Sounds fairly crazy to me, but if you agree, I'll add that.

**Comment by gsmet** [comment]
Please make it clear what you should use and actually work in the sentence. It’s not always clear to our users.

**Comment by manovotn** [comment]
> > Please make it clear what you should use and actually work in the sentence. It’s not always clear to our users.
> 
> @gsmet Well, the problem is that users can't do much in this particular case because those problematic injection points are defined in external libraries/extension runtime artifacts...

Yes, in this particular case the user might not even know their decorator applies to a bean provided by some other fwk.
Which is also why I think the documentation doesn't make much of a difference.

**Comment by mkouba** [comment]
> I'm afraid it's not gonna be just a "single line", or it's gonna be a _long_ single line. How about this?
> 
> > If a decorator provided by the application applies to beans provided by external libraries, package-private injection points (and other CDI constructs) are not going to work in those beans in dev/test mode.
> 
> Sounds fairly crazy to me, but if you agree, I'll add that.

@Ladicek You're right, sounds crazy and most readers won't be able to decrypt this message. So we should probably keep it as a secret for now :shrug:.

**Comment by Ladicek** [comment]
Any objection to merging this?

**Comment by rsvoboda** [comment]
For https://issues.redhat.com/browse/QUARKUS-5178

**Pull request merged**
