### PR TITLE
Upgrade LogManager to 1.0.9

### LINKED ISSUE #6954: When overridding logging handlers for a specific category we get NullPointerException in native mode only
**Describe the bug**
Whenever we configure specific handlers that we link to a category we get a NullPointerException.
```
2020-01-30 12:10:53 Mounting /private/var/folders/xk/xtn2b68s2c33qryl26pvzfv40000gn/T/tmpt7c35ugv as /var/task:ro,delegated inside runtime container
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:138)
at io.quarkus.runtime.Application.start(Application.java:87)
at io.quarkus.runtime.Application.run(Application.java:210)
at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.NullPointerException
at org.jboss.logmanager.AtomicArray.add(AtomicArray.java:114)
at org.jboss.logmanager.LoggerNode.addHandler(LoggerNode.java:295)
at org.jboss.logmanager.Logger.addHandler(Logger.java:217)
at io.quarkus.runtime.logging.LoggingSetupRecorder.addNamedHandlersToCategory(LoggingSetupRecorder.java:169)
at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:116)
at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit180.deploy_0(LoggingResourceProcessor$setupLoggingRuntimeInit180.zig:103)
at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit180.deploy(LoggingResourceProcessor$setupLoggingRuntimeInit180.zig:122)
at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:60)
... 3 more
```

**Expected behavior**
The behaviour should be the same as when running in JVM and attach the extra handlers to the Logger that belongs to a category.

**To Reproduce**
1. Configure named handlers and link to category
2. Build native image
3. During initialisation the exception occurs

**Configuration**
```properties
quarkus.log.handler.console."STRUCTURED_LOGGING".format=%m%n

quarkus.log.category."com.xyz.DocumentEventLogger".level=DEBUG
quarkus.log.category."com.xyz.DocumentEventLogger".handlers=STRUCTURED_LOGGING
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin APRXJGH6D5D5F9 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 1.8.0_211
 - GraalVM version (if different from Java): quay.io/quarkus/ubi-quarkus-native-image:19.2.1
 - Quarkus version or git rev: 1.2.0.Final

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes potential NPE in `AtomicArray` updates on native images.

Fixes #6954

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
More importantly, you need to change it here: https://github.com/quarkusio/quarkus/blob/master/bom/application/pom.xml#L159

**Comment by dmlloyd** [comment]
> More importantly, you need to change it here: https://github.com/quarkusio/quarkus/blob/master/bom/application/pom.xml#L159

Ah, I didn't find it because I grepped for `embedded` 🤦🏻‍♂️

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by dmlloyd** [comment]
Looks like the substitutions need to be updated now.  I'll come back to that later today hopefully.

**Comment by gsmet** [comment]
All the JDK tests got cancelled with timeouts which looks a bit suspicious.

**Comment by gsmet** [comment]
Again, all JDK tests got cancelled.

**Comment by dmlloyd** [comment]
I have no idea why.  I'll try to see if I can get it to run locally next week.

**Comment by gastaldi** [comment]
@dependabot rebase

**Comment by gastaldi** [comment]
I wonder why CI refuses to test this PR

**Comment by gsmet** [comment]
I force pushed again and CI started.

**Comment by dmlloyd** [comment]
If it fails again, give me time to copy the build command from the job so that I can try to reproduce the problem locally.

**Comment by gastaldi** [comment]
Weird, some of the jobs were cancelled

**Comment by dmlloyd** [comment]
I've got the JDK test running locally and I'll see what's going on there.

**Comment by dmlloyd** [comment]
Yeah I cancelled them.  They were clearly hung

**Comment by dmlloyd** [comment]
Running the build command locally, I get:

```

**Comment by gastaldi** [comment]
@famod any idea what's going on? ☝🏻

**Comment by dmlloyd** [comment]
I switched the property name to `gib.disableIfBranchRegex` and it worked.  Seems weird though.

**Comment by dmlloyd** [comment]
My local run has already made it farther than the CI job. 😕

**Comment by gsmet** [comment]
@dmlloyd are you sure you have the latest main? Because GIB got upgraded recently and gib.disableIfBranchMatches is one of the change.

**Comment by famod** [comment]
Huh? PR jobs normally build a merge of the PR branch and the target branch. How can this end up with a mismatch of GIB version and GIB property?!

I'll have a look in around two hours.

I must say I have seen some weird things after the `main` switch, not (exclusively) related to GIB.

**Comment by dmlloyd** [comment]
No worries, I have found the problem.  It needs another 24 hours for Maven publication though.

**Comment by gsmet** [comment]
Rebased to fix a conflict.

**Comment by thomas-mc-work** [comment]
This is targeted for `1.14`. It would be lovely to have it backported to `1.13`, as it's fixing an annoying bug.

Thank you anyways for taking care of this!

**Comment by geoand** [comment]
The `backport` label has been added, so it will become part of `1.13.0.Final`

**Pull request merged**
