### PR TITLE
Use latest Stork fixing an issue about k8s SD refreshing cache

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier we are still using Stork 2.2 in 3.2, should we upgrade?

**Comment by cescoffier** [comment]
Yes, this is a bug fix release.

**Comment by cescoffier** [comment]
Let me check, I think it's fine. 2.3 fixed the missing service registar - was also a kind of bugfix release.

WDYT @aureamunoz ?

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Otherwise, we can cut a 2.2.x release with that bug fix.

**Comment by gsmet** [comment]
I’m not really comfortable backporting this one tbh: https://github.com/quarkusio/quarkus/pull/34372/files

When fixing bugs, we should be more careful.

**Comment by cescoffier** [comment]
I would have agreed, but that's more (quite large) refactoring than anything else.
But, ok, I will cut a bug-fix release without this one.

**Comment by cescoffier** [comment]
@aureamunoz is getting a 2.2.1 release today for 3.2.

This one should not be backported (see previous comments)

**Pull request merged**
