### PR TITLE
Break build cycle between OTel, logging and Flyway

### LINKED ISSUE #45130: Conflicting open telemetry and flyway dependencies
### Describe the bug

Hi, I found that if I have open telemetry and flyway dependencies in one project and set `quarkus.otel.logs.enabled=true` during build I got:  

```Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.ChainBuildException: Cycle detected:
                           io.quarkus.flyway.deployment.FlywayProcessor#createBeans produced class io.quarkus.arc.deployment.AdditionalBeanBuildItem
                        to io.quarkus.arc.deployment.ArcProcessor#initialize produced class io.quarkus.arc.deployment.ContextRegistrationPhaseBuildItem
                        to io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#transactionContext produced class io.quarkus.arc.deployment.ContextRegistrationPhaseBuildItem$ContextConfiguratorBuildItem
                        to io.quarkus.arc.deployment.ArcProcessor#registerBeans produced class io.quarkus.arc.deployment.BeanDiscoveryFinishedBuildItem
                        to io.quarkus.arc.deployment.ReflectiveBeanClassesProcessor#implicitReflectiveBeanClasses produced class io.quarkus.arc.deployment.ReflectiveBeanClassBuildItem
                        to io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.ResourcesGeneratedPhaseBuildItem
                        to io.quarkus.arc.deployment.ArcProcessor#initializeContainer produced class io.quarkus.arc.deployment.ArcContainerBuildItem
                        to io.quarkus.arc.deployment.ArcProcessor#notifyBeanContainerListeners produced class io.quarkus.arc.deployment.PreBeanContainerBuildItem
                        to io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady produced class io.quarkus.arc.deployment.BeanContainerBuildItem
                        to io.quarkus.opentelemetry.deployment.logging.LogHandlerProcessor#build produced class io.quarkus.deployment.builditem.LogHandlerBuildItem
                        to io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit produced class io.quarkus.deployment.logging.LoggingSetupBuildItem
                        to io.quarkus.flyway.deployment.FlywayProcessor#createBeans

```

If I remove `implementation("io.quarkus:quarkus-flyway")` or  `implementation("io.quarkus:quarkus-opentelemetry")`  everything works fine 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

https://github.com/DawidStuzynski/open-telemetry-flyway-problem
clone this repo, run in terminal  `./gradlew assemble`, if `quarkus.otel.logs.enabled=true` or `quarkus.otel.metrics.enabled=true` is removed everything works fine

### Output of `uname -a` or `ver`

Darwin Dawids-MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0:

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 OpenJDK Runtime Environment GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19) OpenJDK 64-Bit Server VM GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

### Quarkus version or git rev

3.17.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #45130

### CODE REVIEW

**Comment by geoand** [comment]
The issue with this one is that I have no idea what problem `@Consume(LoggingSetupBuildItem.class)` solved.
It was introduced in 72a983fd14e298c513dd9755b4f9fa690fd59c09 but I don't see an example of what prompted its inclusion.

**Comment by geoand** [comment]
An alternative fix would be to check if the bean has been initialized and if not queue the records and it does become available to emit them all.
This solution however would require an API for checking whether a synthetic bean has been initialized. See [this](https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/Synthetic.20Beans/near/489159972) for more details.

**Comment by gsmet** [comment]
Yeah I also had a quick look yesterday and this is similar to another issue we had a few weeks back.

I'm a bit worried about just dropping @stuartwdouglas 's fix. Also a bit worried in general as this cycle is something that could happen quite a lot.

**Comment by geoand** [comment]
> I'm a bit worried about just dropping @stuartwdouglas 's fix

Me too, but I don't have a way of knowing what problem it was meant to fix

> Also a bit worried in general as this cycle is something that could happen quite a lot.

I think this specific instance is pretty unique as creating `LogHandlerBuildItem` is not terribly common among extensions

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
OK, I suppose we will have reports soon enough if it's still needed.

**Pull request merged**
