### PR TITLE
Take conditional annotation into account for @ServerExceptionMapper

### LINKED ISSUE #29043: Parent first dependencies method in Class Loading Reference guide not working for applications
### Describe the bug

A Quarkus application that wants to use byteman to intercept and startup and shutdown events will suffer issues like this with default fast-jar.

On startup, byteman is loaded with the system classloader and it successfully injects the rule:

```
[1830908236 null] Rule.execute called for restore_1:0
HelperManager.install for helper class org.acme.JigawattsService
calling activated() for helper class org.jboss.byteman.rule.helper.Helper
Default helper activated
calling installed(restore) for helper classorg.jboss.byteman.rule.helper.Helper
Installed rule using default helper : restore
calling activated() for helper class org.acme.JigawattsService
Default helper activated
calling installed(restore) for helper classorg.acme.JigawattsService
Installed rule using default helper : restore
restore execute()
Restore::entry
Restore::exit
```

Then on shutdown, the rule won't trigger and you will see these messages appearing on byteman:

```
^C[33293669 io.quarkus.bootstrap.runner.RunnerClassLoader@3d24753a] Rule.execute called for checkpoint_0:0
Rule.execute for decommissioned key checkpoint_0:0
```

What is happening is that on shutdown, byteman classes are being loaded with a different classloader (the `RunnerClassLoader`). This is problematic because Byteman's rule has a static cache of rules, and when the class is loaded with another classloader different to the system one, the cache is empty and it won't trigger the rule. The above (tweaked) byteman log messages show that.

The classloading guide indicates how to avoid this issue in the [parent first dependencies section](https://quarkus.io/guides/class-loading-reference#parent-first-dependencies). The guide suggests to do add this to the pom.xml but for Quarkus applications (not extensions) it has no effect:

```
<plugin>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-extension-maven-plugin</artifactId>
    <configuration>
        <parentFirstArtifacts>
            <parentFirstArtifact>org.jboss.byteman:byteman</parentFirstArtifact>
        </parentFirstArtifacts>
    </configuration>
</plugin>
```

However, if you instead modify the app's `application.properties` file and add this:

```
quarkus.class-loading.parent-first-artifacts=org.jboss.byteman:byteman
```

Then things will work:

```
^C[1288354730 null] Rule.execute called for checkpoint_0:0
HelperManager.install for helper class org.jboss.byteman.rule.helper.Helper
calling installed(checkpoint) for helper classorg.jboss.byteman.rule.helper.Helper
Installed rule using default helper : checkpoint
checkpoint execute
Checkpoint::entry
```

What you're seeing above is the rule being loaded with the system classloader once again and things working as expected.

Documentation should make this clear.

Moreover, the following statement in the classloader guide is outdated:

> When running a production application everything is loaded in the system ClassLoader, so it is a completely flat class path.

There should be an explanation about fast-jar (vs legacy-jar)...etc.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #29043

### CODE REVIEW

**Review by Sgitario — COMMENTED** [review]
The changes look good to me, though the CI is broken due to https://github.com/quarkusio/quarkus/issues/29403. 

Moreover, I would consider adding a section to note/describe that we can use these annotations in the exception mappers.

**Comment by geoand** [comment]
> Moreover, I would consider adding a section to note/describe that we can use these annotations in the exception mappers.

I have actually found that users intuitively think that all annotations work together, unless otherwise stated, so I don't think we need to explicitly mention anything.

I rebased the PR onto main to get another CI run

**Comment by geoand** [comment]
@Sgitario can I get a review please?

Thanks

**Review by Sgitario — APPROVED** [review]
lgtm!

**Pull request merged**
