### PR TITLE
Fix banner in native when building with docker

### PR DESCRIPTION
**Pull request by geoand**
This came out of the extensive collaboration of David Lloyd,
Max Andersen and myself (chat can be seen [here](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/banner.20.3F/near/189939308))

Co-Authored-By: David M. Lloyd <david.lloyd@redhat.com>
Co-authored-by: Max Rydahl Andersen <manderse@redhat.com>

### CODE REVIEW

**Comment by geoand** [comment]
Supercedes: #7610

**Review by dmlloyd — APPROVED** [review]

**Comment by geoand** [comment]
@dmlloyd also mentioned he is going to look into what to do when the banner can't be printed

**Comment by gsmet** [comment]
Please be careful about adding the `backport` label when merging.

**Comment by geoand** [comment]
Ah yes! I missed this one, sorry

**Pull request merged**
