### PR TITLE
Change GraphQL endpoints to be Singleton by default

### LINKED ISSUE #26103: Change GraphQL endpoints to be @Singleton by default
### Description

Follow the same strategy that we have with JAX-RS endpoints

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #26103

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
Could you add an entry to the migration guide for 2.11: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.11 ?

Thanks!

**Comment by phillip-kruger** [comment]
@jmartisk ^^^

**Comment by jmartisk** [comment]
Done.

**Pull request merged**
