### PR TITLE
Properly cache ContextResolver usage for ObjectMapper

### LINKED ISSUE #36067: @ClientObjectMapper should run only once
### Description

When using context resolver. I can use a pattern like this. Which will make the ObjectMapper copied a single time;
```java
public class MyWriter implements ContextResolver<ObjectMapper> {

    private final ObjectMapper myMapper;

    MyWriter(ObjectMapper mapper) {
        this.myMapper = mapper.copy();
        myMapper.setConfig(myMapper.getSerializationConfig().withView(getClass()));
    }

    @Override
    public ObjectMapper getContext(Class<?> type) {
        return myMapper;
    }

}
```

When using 
```java
    @ClientObjectMapper
    static ObjectMapper objectMapper(ObjectMapper defaultObjectMapper) {
        ObjectMapper myMapper = defaultObjectMapper.copy();
        return myMapper.setConfig(myMapper.getSerializationConfig().withView(MyApi.class));
    }
```

This have the effect that if I have 100 concurrent requests to the api, I can see 100 objectMappers getting created. Since the static method does not have any context of what is being called, it could only be ran once so save the overhead of creating /copying and storing an extra object mapper.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #36067

### CODE REVIEW

**Comment by geoand** [comment]
We might also want to backport the first commit to 3.2 - remains to be seen.

**Review by gastaldi — APPROVED** [review]

**Comment by geoand** [comment]
I don't see how my change could be impacting this:

```
2023-09-25T13:08:14.8854475Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.21 s -- in io.quarkus.it.opentelemetry.MariaDbOpenTelemetryJdbcInstrumentationTest
2023-09-25T13:08:14.8888690Z [INFO] Running io.quarkus.it.opentelemetry.Db2OpenTelemetryJdbcInstrumentationTest
2023-09-25T13:08:14.9019947Z [WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s -- in io.quarkus.it.opentelemetry.Db2OpenTelemetryJdbcInstrumentationTest
2023-09-25T13:08:14.9020997Z [INFO] Running io.quarkus.it.opentelemetry.OracleOpenTelemetryJdbcInstrumentationTest
2023-09-25T13:08:15.0667092Z 2023-09-25 13:08:14,908 INFO  [io.quarkus] (main) opentelemetry-jdbc-instrumentation-it stopped in 0.028s
2023-09-25T13:08:17.8923746Z 2023-09-25 13:08:17,800 WARN  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-21) Could not find a suitable persistence unit for model classes:
2023-09-25T13:08:17.8924595Z 	- io.quarkus.hibernate.orm.panache.PanacheEntity
2023-09-25T13:08:17.8925149Z 	- io.quarkus.it.opentelemetry.model.Hit
2023-09-25T13:08:18.5934819Z 2023-09-25 13:08:18,559 INFO  [JakartaTransformer] (build-15) Jakarta EE compatibility enhancer for Quarkus: transforming com.ibm.db2.jcc.t2zos.ab
2023-09-25T13:08:18.5936175Z 2023-09-25 13:08:18,564 INFO  [JakartaTransformer] (build-32) Jakarta EE compatibility enhancer for Quarkus: transforming com.ibm.db2.jcc.t2zos.T2zosConfiguration
2023-09-25T13:08:18.5937233Z 2023-09-25 13:08:18,566 INFO  [JakartaTransformer] (build-18) Jakarta EE compatibility enhancer for Quarkus: transforming com.ibm.db2.jcc.t2zos.T2zosConnection
2023-09-25T13:08:20.1184222Z 2023-09-25 13:08:20,116 INFO  [io.qua.hib.orm.run.JPAConfig] (main) Hibernate ORM persistence unit 'db2' was deactivated through configuration properties
2023-09-25T13:08:20.1185269Z 2023-09-25 13:08:20,117 INFO  [io.qua.hib.orm.run.JPAConfig] (main) Hibernate ORM persistence unit 'mariadb' was deactivated through configuration properties
2023-09-25T13:08:20.2185558Z 2023-09-25 13:08:20,119 INFO  [io.qua.hib.orm.run.JPAConfig] (main) Hibernate ORM persistence unit 'postgresql' was deactivated through configuration properties
2023-09-25T13:08:20.7253570Z 2023-09-25 13:08:20,686 WARN  [io.agr.pool] (agroal-11) Datasource 'oracle': ORA-00604: Error occurred at recursive SQL level 1. Check subsequent errors.
2023-09-25T13:08:20.7254642Z ORA-01804: failure to initialize timezone information
2023-09-25T13:08:20.7255575Z 
2023-09-25T13:08:20.7257628Z 2023-09-25 13:08:20,688 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: ORA-00604: Error occurred at recursive SQL level 1. Check subsequent errors.
2023-09-25T13:08:20.7258735Z ORA-01804: failure to initialize timezone information
2023-09-25T13:08:20.7259207Z 
2023-09-25T13:08:20.7260904Z 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
2023-09-25T13:08:20.7318137Z 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:603)
2023-09-25T13:08:20.7318633Z 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:598)
2023-09-25T13:08:20.7319129Z 	at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1710)
2023-09-25T13:08:20.7319677Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:819)
2023-09-25T13:08:20.7320199Z 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1041)
2023-09-25T13:08:20.7320638Z 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:443)
2023-09-25T13:08:20.7321130Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:462)
2023-09-25T13:08:20.7321723Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTHWithO5Logon(T4CTTIoauthenticate.java:1628)
2023-09-25T13:08:20.7322331Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1375)
2023-09-25T13:08:20.7322888Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1322)
2023-09-25T13:08:20.7323479Z 	at oracle.jdbc.driver.T4CConnection.authenticateWithPassword(T4CConnection.java:1516)
2023-09-25T13:08:20.7324095Z 	at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1459)
2023-09-25T13:08:20.7324642Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:828)
2023-09-25T13:08:20.7325146Z 	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1132)
2023-09-25T13:08:20.7325725Z 	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104)
2023-09-25T13:08:20.7326262Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:837)
2023-09-25T13:08:20.7326729Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:664)
2023-09-25T13:08:20.7327252Z 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
2023-09-25T13:08:20.7327809Z 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
2023-09-25T13:08:20.7328343Z 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
2023-09-25T13:08:20.7328829Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
2023-09-25T13:08:20.7329669Z 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
2023-09-25T13:08:20.7330348Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2023-09-25T13:08:20.7330944Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2023-09-25T13:08:20.7331415Z 	at java.base/java.lang.Thread.run(Thread.java:1623)
2023-09-25T13:08:20.7331627Z 
2023-09-25T13:08:20.9079985Z 13:08:20.906 Oracle Database:2023-09-25T13:08:20.669466+00:00
2023-09-25T13:08:20.9081509Z 13:08:20.907 Oracle Database:FREEPDB1(3):TABLE AUDSYS.AUD$UNIFIED: ADDED INTERVAL PARTITION SYS_P351 (3374) VALUES LESS THAN (TIMESTAMP' 2023-09-26 00:00:00')
2023-09-25T13:08:21.0906032Z 2023-09-25 13:08:21,051 WARN  [io.agr.pool] (agroal-11) Datasource 'oracle': ORA-00604: Error occurred at recursive SQL level 1. Check subsequent errors.
2023-09-25T13:08:21.0906992Z ORA-01804: failure to initialize timezone information
2023-09-25T13:08:21.0907423Z 
2023-09-25T13:08:21.0908895Z 2023-09-25 13:08:21,052 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread) SQL Error: 604, SQLState: 60000
2023-09-25T13:08:21.0909913Z 2023-09-25 13:08:21,052 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread) ORA-00604: Error occurred at recursive SQL level 1. Check subsequent errors.
2023-09-25T13:08:21.0922780Z ORA-01804: failure to initialize timezone information
2023-09-25T13:08:21.0922989Z 
2023-09-25T13:08:21.1802718Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.223 s <<< FAILURE! -- in io.quarkus.it.opentelemetry.OracleOpenTelemetryJdbcInstrumentationTest
2023-09-25T13:08:21.1803975Z [ERROR] io.quarkus.it.opentelemetry.OracleOpenTelemetryJdbcInstrumentationTest.testOracleQueryTraced -- Time elapsed: 0.004 s <<< ERROR!
2023-09-25T13:08:21.1804744Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2023-09-25T13:08:21.1805370Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:639)
2023-09-25T13:08:21.1806171Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:723)
2023-09-25T13:08:21.1806774Z 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2023-09-25T13:08:21.1807199Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2023-09-25T13:08:21.1807607Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2023-09-25T13:08:21.1808009Z Caused by: java.lang.RuntimeException: Failed to start quarkus
2023-09-25T13:08:21.1808428Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-09-25T13:08:21.1808874Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2023-09-25T13:08:21.1809296Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
2023-09-25T13:08:21.1809880Z 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:282)
2023-09-25T13:08:21.1810482Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:251)
2023-09-25T13:08:21.1811123Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:606)
2023-09-25T13:08:21.1811736Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:656)
2023-09-25T13:08:21.1812140Z 	... 1 more
2023-09-25T13:08:21.1823763Z Caused by: java.lang.RuntimeException: jakarta.persistence.PersistenceException: [PersistenceUnit: oracle] Unable to build Hibernate SessionFactory
2023-09-25T13:08:21.1824450Z 	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:78)
2023-09-25T13:08:21.1825168Z 	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:101)
2023-09-25T13:08:21.1825950Z 	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy_0(Unknown Source)
2023-09-25T13:08:21.1826641Z 	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy(Unknown Source)
2023-09-25T13:08:21.1827067Z 	... 8 more
2023-09-25T13:08:21.1827832Z Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: oracle] Unable to build Hibernate SessionFactory
2023-09-25T13:08:21.1828759Z 	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:126)
2023-09-25T13:08:21.1829827Z 	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:86)
2023-09-25T13:08:21.1830913Z 	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
2023-09-25T13:08:21.1831819Z 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
2023-09-25T13:08:21.1832454Z 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
2023-09-25T13:08:21.1833043Z 	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
2023-09-25T13:08:21.1833582Z 	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
2023-09-25T13:08:21.1834004Z 	at java.base/java.lang.Thread.run(Thread.java:1623)
2023-09-25T13:08:21.1834901Z Caused by: org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution [ORA-00604: Error occurred at recursive SQL level 1. Check subsequent errors.
2023-09-25T13:08:21.1835774Z ORA-01804: failure to initialize timezone information
2023-09-25T13:08:21.1836050Z ] [n/a]
2023-09-25T13:08:21.1836588Z 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:61)
2023-09-25T13:08:21.1837317Z 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
2023-09-25T13:08:21.1837953Z 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
2023-09-25T13:08:21.1838919Z 	at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.getIsolatedConnection(DdlTransactionIsolatorJtaImpl.java:77)
2023-09-25T13:08:21.1840076Z 	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.getIsolatedConnection(GenerationTargetToDatabase.java:60)
2023-09-25T13:08:21.1841044Z 	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.jdbcStatement(GenerationTargetToDatabase.java:110)
2023-09-25T13:08:21.1841933Z 	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:77)
2023-09-25T13:08:21.1842637Z 	at org.hibernate.tool.schema.internal.Helper.applySqlString(Helper.java:235)
2023-09-25T13:08:21.1843224Z 	at org.hibernate.tool.schema.internal.Helper.applySqlStrings(Helper.java:219)
2023-09-25T13:08:21.1843869Z 	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropTables(SchemaDropperImpl.java:362)
2023-09-25T13:08:21.1844679Z 	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropConstraintsTablesSequences(SchemaDropperImpl.java:253)
2023-09-25T13:08:21.1845524Z 	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:215)
2023-09-25T13:08:21.1846260Z 	at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:185)
2023-09-25T13:08:21.1846946Z 	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:155)
2023-09-25T13:08:21.1847608Z 	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:115)
2023-09-25T13:08:21.1848427Z 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:242)
2023-09-25T13:08:21.1849355Z 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
2023-09-25T13:08:21.1849974Z 	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
2023-09-25T13:08:21.1850597Z 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
2023-09-25T13:08:21.1851766Z 	at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
2023-09-25T13:08:21.1852979Z 	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
2023-09-25T13:08:21.1853679Z 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:293)
2023-09-25T13:08:21.1854433Z 	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
2023-09-25T13:08:21.1855010Z 	... 6 more
2023-09-25T13:08:21.1855526Z Caused by: java.sql.SQLException: ORA-00604: Error occurred at recursive SQL level 1. Check subsequent errors.
2023-09-25T13:08:21.1856693Z ORA-01804: failure to initialize timezone information
2023-09-25T13:08:21.1856905Z 
2023-09-25T13:08:21.1857134Z 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
2023-09-25T13:08:21.1857620Z 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:603)
2023-09-25T13:08:21.1858107Z 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:598)
2023-09-25T13:08:21.1858561Z 	at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1710)
2023-09-25T13:08:21.1859101Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:819)
2023-09-25T13:08:21.1859774Z 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1041)
2023-09-25T13:08:21.1860194Z 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:443)
2023-09-25T13:08:21.1860686Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:462)
2023-09-25T13:08:21.1861286Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTHWithO5Logon(T4CTTIoauthenticate.java:1628)
2023-09-25T13:08:21.1861875Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1375)
2023-09-25T13:08:21.1862826Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1322)
2023-09-25T13:08:21.1863423Z 	at oracle.jdbc.driver.T4CConnection.authenticateWithPassword(T4CConnection.java:1516)
2023-09-25T13:08:21.1864040Z 	at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1459)
2023-09-25T13:08:21.1864573Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:828)
2023-09-25T13:08:21.1865091Z 	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1132)
2023-09-25T13:08:21.1865656Z 	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104)
2023-09-25T13:08:21.1866179Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:837)
2023-09-25T13:08:21.1866642Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:664)
2023-09-25T13:08:21.1867160Z 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
2023-09-25T13:08:21.1867713Z 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
2023-09-25T13:08:21.1868237Z 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
2023-09-25T13:08:21.1868733Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
2023-09-25T13:08:21.1869304Z 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
2023-09-25T13:08:21.1869960Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2023-09-25T13:08:21.1870559Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2023-09-25T13:08:21.1870941Z 	... 1 more
2023-09-25T13:08:21.1871075Z 
2023-09-25T13:08:21.3391464Z [INFO] 
2023-09-25T13:08:21.3394346Z [INFO] Results:
2023-09-25T13:08:21.3394917Z [INFO] 
2023-09-25T13:08:21.3395292Z [ERROR] Errors: 
2023-09-25T13:08:21.3396411Z [ERROR]   OracleOpenTelemetryJdbcInstrumentationTest.testOracleQueryTraced » Runtime java.lang.RuntimeException: Failed to start quarkus
2023-09-25T13:08:21.3397189Z [INFO] 
2023-09-25T13:08:21.3397613Z [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 1
```

cc @yrodiere

**Comment by yrodiere** [comment]
@geoand No idea either, but this is an error on the Oracle side.

A web search turned out [this](https://stackoverflow.com/questions/12837811/error-while-trying-to-retrieve-text-for-error-ora-01804), which seems to say "you can get this error for a thousand different reasons".

Let's... run CI again and hope it never happens again?

**Comment by yrodiere** [comment]
Oh my, it happens consistently on all builds. Well... that's worrying.

**Comment by yrodiere** [comment]
> > it can be an image problem...
> 
> Just checked, and the Oracle image was last updated on April 7th: [07f30aa#diff-150bdf617c2dc80dc5a9d5f1313f44a73950a96ca7b166b79a35b15f4c84f193L97-R97](https://github.com/quarkusio/quarkus/commit/07f30aadb6727eb8476fd0aac051f4a6a19322a9#diff-150bdf617c2dc80dc5a9d5f1313f44a73950a96ca7b166b79a35b15f4c84f193L97-R97)

Ah, but it's a floating tag and it's been updated 20 hours ago: https://hub.docker.com/layers/gvenzl/oracle-free/23-slim-faststart/images/sha256-44416f0de8bb6ce3ec82fb8b1ad766c4667073b723d1f02451e0f0375c0ed064?context=explore

**Comment by brunobat** [comment]
I'll disable the test until they fix that image... I cannot find any older version we can use.

**Comment by yrodiere** [comment]
There's been this report, though it doesn't really look related: https://github.com/gvenzl/oci-oracle-free/issues/22

@geoand you can try changing `<oracle.image>` to [`docker.io/gvenzl/oracle-free:23.2-slim-faststart`](https://hub.docker.com/layers/gvenzl/oracle-free/23.2-slim-faststart/images/sha256-fe679c7dd98ca56f802d416a9b0fc3a9cd8c6f3e71f9afc3049b4f78801ad177?context=explore), in quarkus-build-parent, though I'm not sure it will fix the problem.

**Comment by brunobat** [comment]
Testing now

**Comment by yrodiere** [comment]
Related: https://github.com/apache/camel-quarkus/issues/5353

**Comment by gsmet** [comment]
@geoand should this be backported to 3.4? I'm on the verge...

**Comment by geoand** [comment]
Yeah, I think it makes sense

**Pull request merged**
