### PR TITLE
Run resources:resource if needed maven goal when starting dev-mode

### LINKED ISSUE #9721: Quarkus:dev does not filter resources
Quarkus:dev does not filter resources

add filter a maven
```
        <resources>
          <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
          </resource>
        </resources>
```
add a maven property in application.yaml or application.properties
```
my.version=$ {project.version}
```
run mvn clean package quarkus: dev
resources are filtered and the application starts with the property
my.version = 1.0.0-SNAPSHOT

run mvn clean quarkus: dev
resources are not filtered and the application starts with the property
my.version = $ {project.version}
**Describe the bug**

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #9721

### CODE REVIEW

**Comment by geoand** [comment]
Note that this does **not** fix dev-mode to handle resource filtering when the properties file is updated. That is a different issue - this issue just makes sure that the initial resource filtering is applied when a user doesn't specify the `compile` or `package` goals when running dev-mode.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Yeah so if you update the file afterwards, you get back to no filtering?

I wonder if it's better to have a consistent (broken) behavior.

**Comment by geoand** [comment]
> Yeah so if you update the file afterwards, you get back to no filtering?
> 

Exactly, filtering doesn't work.

> I wonder if it's better to have a consistent (broken) behavior.

The way I see it, it's more consistent with this PR because `mvn quarkus:dev` and `mvn compile quarkus:dev` behave in the same way on first deploy and on changes.

**Comment by geoand** [comment]
I'll leave it to you @gsmet to decide if we want this or not :)

**Comment by famod** [comment]
Have you guys seen my comment/question regarding the empty `configuration`?

**Comment by famod** [comment]
A review comment:
https://github.com/quarkusio/quarkus/pull/9724#pullrequestreview-422718958

**Comment by famod** [comment]
Well, it seems I _have_ posted it. Strange.
It is related to line 419 of the DevMojo:
> Is this creating an empty configuration? What if I have set (e.g.) https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#nonFilteredFileExtensions ?

**Comment by geoand** [comment]
> Well, it seems I _have_ posted it. Strange.
> It is related to line 419 of the DevMojo:
> 
> > Is this creating an empty configuration? What if I have set (e.g.) https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#nonFilteredFileExtensions ?

Yeah, that indeed won't work. Would you like to follow up this PR with one of your own that adds support for the configuration of the resources plugin?

**Comment by famod** [comment]
I cannot promise anything since I've just returned to my day job after more than one week off, so I'm pretty busy...

**Comment by geoand** [comment]
No worries, we have plenty of time until we freeze for 1.6.
I propose we merge this now since it's clearly better than what we had and you can work on it when you have time (or let us know if you can't get to it and we'll drive it home)

**Comment by geoand** [comment]
@gsmet what do you want to do with this one?

**Pull request merged**
