### PR TITLE
Replace oidc auth facebook screenshots with generic ones

### PR DESCRIPTION
**Pull request by rghara**
Replace oidc auth facebook screenshots with generic ones

Related to #42549

### CODE REVIEW

**Comment by rghara** [comment]
Hi @sberyozkin,
Here is a PR for changes in Facebook.
Note: There has been some significant changes to the app creation in Facebook.

**Comment by sberyozkin** [comment]
Thanks @rghara, I noticed your PR earlier, but was waiting for #44114 to complete which also updates the same guide.

Thanks for refreshing the Facebook instructions, @FroMage FYI.

@rghara, FYI, we've added some instructions on how to rebase at #44226, please try to follow them in your next PRs, which should save you some time.

Thanks

**Review by sberyozkin — APPROVED** [review]

**Comment by rghara** [comment]
> Thanks @rghara, I noticed your PR earlier, but was waiting for #44114 to complete which also updates the same guide.
> 
> Thanks for refreshing the Facebook instructions, @FroMage FYI.
> 
> @rghara, FYI, we've added some instructions on how to rebase at #44226, please try to follow them in your next PRs, which should save you some time.
> 
> Thanks

I appreciate your support!

**Comment by sberyozkin** [comment]
@rghara Np at all, thanks for keeping going through all those outdated OIDC/OAuth2 provider setup images, `Apple` and possible another one or 2 still refer to Renarde, so a few more images to update :-)... Note, AFAIK, `Apple` requires a paid subscription (CC @FroMage ) - but registering the OIDC application alone should be free, if not - let us know please, thanks

**Comment by rghara** [comment]
> @rghara Np at all, thanks for keeping going through all those outdated OIDC/OAuth2 provider setup images, `Apple` and possibly another one or two images still refer to Renarde, so a few more images to update :-)... Note, AFAIK, `Apple` requires a paid subscription (CC @FroMage ) - but registering the OIDC application alone should be free, if not - let us know please, thanks

Hi @sberyozkin - I did check out Apple and it does need a paid subscription. I thought in Apple case I could retouch the screenshots only. I wouldn't be able to test it with the code though. If there has been changes to Apple process as well then I will need to redo it from scratch. I will keep you posted.

**Review by FroMage — COMMENTED** [review]
Great!

**Pull request merged**
