### PR TITLE
Allow adding extra OIDC provider scopes without having to list all scopes

### LINKED ISSUE #34646: Introduce `quarkus.oidc.authentication.add-scopes` property
### Description

We already have  `quarkus.oidc.authentication.scopes` property, whenever OIDC authorization code flow is used, and more scopes should be requested, this property can be used.

For example, with Google, one can have

```
quarkus.oidc.google.authentication.scopes=email,profile
```

The above scopes are setup with `quarkus.oidc.provider=google`, as in:

```
quarkus.oidc.provider=google
quarkus.oidc.client-id=${google-client-id}
quarkus.oidc.credentials.secret=${google-client-secret}
```

This is all good, and any property set up indirectly with `quarkus.oidc.provider=google` can be `overridden` - I'm highlighting it because it is getting inconvenient if one more scope, in addition to `email,profile` (already setup in case of Google) had to be `added`, and not replace/override the existing scopes value.

For example, if I need to support Google Calendar, in addition to `email, profile`, then the only way to do it is:

```
quarkus.oidc.provider=google
quarkus.oidc.client-id=${google-client-id}
quarkus.oidc.credentials.secret=${google-client-secret}
quarkus.oidc.authentication.scopes=email,profile,https://www.googleapis.com/auth/calendar
```

which is not great - since I have to list `email,profile` again, to avoid them be overridden with the new `quarkus.oidc.authentication.scopes` value.

I'd like to be able to type only:
```
quarkus.oidc.provider=google
quarkus.oidc.client-id=${google-client-id}
quarkus.oidc.credentials.secret=${google-client-secret}
quarkus.oidc.authentication.scopes=https://www.googleapis.com/auth/calendar
```
but we can't distinguish here if the user means to add this scope to whatever scopes are already supported, not to replace them, thus a new property can help:

```
quarkus.oidc.provider=google
quarkus.oidc.client-id=${google-client-id}
quarkus.oidc.credentials.secret=${google-client-secret}
quarkus.oidc.authentication.add-scopes=https://www.googleapis.com/auth/calendar
```

### Implementation ideas

Add a new property to let users add scopes to the already configured scopes as opposed to replace them

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #34646

Simple PR which allows to add an extra scope as a `quarkus.oidc.authentication.extra-params` Map `scope` property, which will make it simpler adding extra scopes for `quarkus.oidc.provider` declarations - at the moment one has to use `quarkus.oidc.authentication.scopes` to add some extra scope - but also list all the other scopes this provider supports by default in order not to lose them during the override.

Updated the test - moved one of the scopes to the Map property, it is asserted it still makes it to the redirect URL here: https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-code-flow/src/test/java/io/quarkus/it/keycloak/CodeFlowTest.java#L425, in fact I broke a few tests before I realized that after adding the this extra scope to the `scope` query parameter, it should not be duplicated when `extra-params` are processed.

Also updated the well-known providers doc with the explanation how to override provider specific scopes or just add an extra scope

### CODE REVIEW

**Comment by sberyozkin** [comment]
Sorry about it

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by sberyozkin** [comment]
Thanks @gastaldi, let me wait till tomorrow morning just in case, cheers

**Comment by sberyozkin** [comment]
@gastaldi Ignore that one please :-), total mix up, sorry

**Pull request merged**
