### PR TITLE
Reproducer for Issue #24492

### PR DESCRIPTION
**Pull request by snazy**
See #24492

### CODE REVIEW

**Comment by famod** [comment]
Thanks, this made if very easy to confirm that this is (still) an upstream issue in x-stream: https://github.com/quarkusio/quarkus/issues/24492#issuecomment-1079507594

**Comment by famod** [comment]
@geoand I might have closed this prematurely as we _could_ integrate it in some form, but for folks building Quarkus with Java 17 we'd need to set add-opens to make the test pass (or exclude it for Java 17).
WDYT?

**Comment by geoand** [comment]
You mean add the necessary configuration to surefire for the generated projects?

**Comment by snazy** [comment]
Is it worth to add some docs regarding this issue? Like „add these —add-opens, if you hit this“

**Comment by famod** [comment]
@geoand I meant adding this `ParamsTest` to integration-tests/test-extension.

@snazy well, maybe we could extend the exception message. 🤔

**Comment by famod** [comment]
PS: Adding documentation is always a good and idea and PRs are more than welcome!

**Comment by geoand** [comment]
@famod both sound good :)

**Comment by geoand** [comment]
Hey,

Github does not allow us to reopen a closed PR when the target branch has been updated. 
Can you open a new one please?

Thanks

**Pull request closed without merging**
