### PR TITLE
Provide a way to push env variables to dev services containers

### LINKED ISSUE #33864: Support passing environment variables to devservices containers
### Description

testcontainers has API to pass environment variables to the container:

https://www.javadoc.io/doc/org.testcontainers/testcontainers/latest/org/testcontainers/containers/GenericContainer.html#addEnv-java.lang.String-java.lang.String-

One possible usage, setting collation of `MSSQLServerContainer`:

    mssqlServerContainer.addEnv("MSSQL_COLLATION", "Arabic_100_CS_AS_KS_WS_SC_UTF8");

### Implementation ideas

Obtain environment variables from `application.properties` and pass them to devservices container:

> quarkus.datasource.devservices.container-enironment-variables.MSSQL_COLLATION=Arabic_100_CS_AS_KS_WS_SC_UTF8

similar to the [existing property](https://quarkus.io/guides/all-config#quarkus-datasource_quarkus.datasource.devservices.container-properties-container-properties):

> quarkus.datasource.devservices.container-properties.TC_MY_CNF

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #33864

@Eng-Fouad could you give it a try? Thanks!

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]

**Comment by Eng-Fouad** [comment]
Tried this configuration:

    quarkus.datasource.devservices.container-env.MSSQL_COLLATION=Arabic_100_CS_AS_KS_WS_SC_UTF8

and it worked perfectly. Thanks.

**Comment by Eng-Fouad** [comment]
I got this error, whenever I use container-env:

> Login failed for user 'SA'. Reason: Could not find a login matching the name provided

May be the default environment variables are overridden.

**Comment by yrodiere** [comment]
@gsmet We probably need to merge user-provided environment variables with the ones we set ourselves (e.g. username)?

**Comment by Eng-Fouad** [comment]
> @gsmet We probably need to merge user-provided environment variables with the ones we set ourselves (e.g. username)?

I think there is no need to do that, as we are already using `withEnv` which appends to the existing environment variables:

    public SELF withEnv(Map<String, String> env) {
        env.forEach(this::addEnv);
        return self();
    }
    
    public void addEnv(String key, String value) {
        env.put(key, value);
    }

**Review by Eng-Fouad — APPROVED** [review]

**Comment by gsmet** [comment]
@Eng-Fouad I wonder if the collation is not causing issues with matching the user name. Could you try to connect from the command line with `SA` and then with `sa` and see if it makes a difference?

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad I wonder if the collation is not causing issues with matching the user name. Could you try to connect from the command line with `SA` and then with `sa` and see if it makes a difference?

Indeed, that was the problem.

I had this config:

> %dev.quarkus.datasource.username=SA

changing it to `sa` resolved the issue.

**Comment by gsmet** [comment]
I think the default from Testcontainers is also `SA` so we probably want to lowercase it.

**Comment by Eng-Fouad** [comment]
Submitted a bug report to `testcontainers-java`: testcontainers/testcontainers-java#7237

**Comment by gsmet** [comment]
@Eng-Fouad could you retest with my latest changes and removing `%dev.quarkus.datasource.username` entirely? I think it should work out of the box now.

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad could you retest with my latest changes and removing `%dev.quarkus.datasource.username` entirely? I think it should work out of the box now.

Yes. It works.

**Pull request merged**
