### PR TITLE
Enable elementary quarkus-jaxb functionality even when no annotations and jaxb.index files are provided

### PR DESCRIPTION
**Pull request by pivovarit**
Not sure if this is desired or not, but if you don't provide locations of `jaxb.index` files and no annotated classes are present, most reflectively-created classes won't get registered because of this line:

https://github.com/quarkusio/quarkus/blob/e5029247cfb136d2d7bdec0d4d78d26d9b9407cf/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L150-L152

And, for example, parsing a standalone file should be a valid use case which is not possible at the moment unless I'm missing something:
```
protected Document parse(InputStream inputStream) {
    // ...
    DocumentBuilder builder = DocumentBuilderFactory
      .newInstance()
      .newDocumentBuilder();
    // ...
    return builder.parse(inputStream);
}
```

I pulled out registration of necessary classes to a separate build step and left only extras inside the conditional branch.

### CODE REVIEW

**Comment by geoand** [comment]
When the review is completed (I assume @gsmet will now most about JAXB), could you also please squash the commits?

Thanks

**Comment by pivovarit** [comment]
@geoand sure, however keep in mind that you can simply do the squash on merge via GitHub

**Comment by gsmet** [comment]
@pivovarit no you can't if you're using merge commits (and unfortunately we do).

**Comment by geoand** [comment]
@pivovarit unfortunately the Github UI does not provide the option to squash and create a merge commit (the merge commit is something that we have decided - at least for the time being - is a requirement), which is why we kindly ask contributors to squash themselves. I know it's not ideal :)

**Comment by gsmet** [comment]
There are a lot of unrelated formatting changes and even formatting issues with indentation. That makes the patch pretty unreadable as there are a lot of unwanted changes (and we won't merge it like that).

Could you have a look at: https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#ide-config-and-code-style ?

**Review by gsmet — APPROVED** [review]
Far better, thanks!

**Comment by pivovarit** [comment]
You're welcome :)

**Pull request merged**
