### PR TITLE
Inject JWT Parser

### LINKED ISSUE #9012: Support the injection of smallrye-jwt DefaultJwtParser
**Description**
If the token is coming in the payload as opposed to a header or if the token is obtained from the OIDC server access token endpoint from the service code, then the usual `JsonWebToken` injection does not work. But having something like
```
@Inject JWTParser parser;

String rawToken = ...;
JsonWebToken jwt = parser.parse(rawToken);
```
will help.
**Implementation ideas**
It should be an easy fix, `SmallryeJwtProcessor` needs to add [DefaultJwtParser](https://github.com/smallrye/smallrye-jwt/blob/master/implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java) producer

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #9012

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi Martin, I'd like to ask about removable vs unremovable beans. If I add `DefautJWTParser` as unremovable bean then it is correctly injected into `MpJwtValidator`, but not in the custom endpoint.
But if I mark it as removable then the injection works correctly for both `MpJwtValidator` and the custom endpoint. Why 'removable' does better ? Thanks

**Comment by sberyozkin** [comment]
@stuartwdouglas I've removed the existing `quarkus-smallrye-jwt` extension of the `DefaultJWTCallerPrincipal` as it was not adding anything new, it had a constructor property to accept a custom principal name, which was never used apart from the test, but it was in itself of no use, as the name must be deduced from the token.

**Comment by sberyozkin** [comment]
```
ERROR] Errors: 
[ERROR]   JPAFunctionalityTest.testJPAFunctionalityFromServlet » Runtime java.lang.RuntimException
```

**Review by stuartwdouglas — APPROVED** [review]

**Comment by mkouba** [comment]
> If I add DefautJWTParser as unremovable bean then it is correctly injected into MpJwtValidator, but not in the custom endpoint.

@sberyozkin it should not make any difference. What was the error message?

**Comment by sberyozkin** [comment]
Hi @mkouba I'll post at the dev channel, as I'm merging this one, cheers

**Comment by mkouba** [comment]
The problem with unremovable is explained here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Unremovable.20bean.20problem

**Pull request merged**
