### PR TITLE
Add quarkus-bot notifications for Kogito and OptaPlanner

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
main vs master is causing issues for me, so I didn't use the latest master apparantly

**Comment by gsmet** [comment]
Ah I was rebasing it :).

**Comment by ge0ffrey** [comment]
Closed in favor of https://github.com/quarkusio/quarkus/pull/15786

**Comment by ge0ffrey** [comment]
Sorry @gsmet for the confusion, I hadn't seen it was using the stale master branch until the PR showed it had conflicts. Anyway, https://github.com/quarkusio/quarkus/pull/15786 is the correct one :)

**Pull request closed without merging**
