### PR TITLE
Bump to Scala 2.13 (including Kafka dependency)

### LINKED ISSUE #10025: Can't compile with Scala 2.13
**Describe the bug**
Quarkus doesn't work when Scala version is changed from 2.12 to 2.13.

**Expected behavior**
Successfully compiled.

**To Reproduce**
1. Open https://code.quarkus.io
2. Select Scala (I also selected Gradle, resteasy-jackson, jackson, jdbc-postgresql and mailer)
3. Download and extract the skeleton project
4. In the project's working directory, `./gradlew quarkusDev`
5. Notice the errors. You will get something like:

        Scala signature package has wrong version
         expected: 5.0
         found: 5.2 in package.class

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux Ryzen5 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

 - GraalVM version (if different from Java): 
N/A

 - Quarkus version or git rev: 
1.5.1.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Gradle 6.3
Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60
Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.3 (AdoptOpenJDK 11.0.3+7)
OS:           Linux 4.4.0-18362-Microsoft amd64

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #10025

### CODE REVIEW

**Comment by gsmet** [comment]
I tried that a while ago and wasn't able to make it work with Debezium.

**Comment by gsmet** [comment]
```
2020-06-16T18:00:07.4027409Z Caused by: java.lang.InstantiationError: scala.collection.mutable.ArraySeq
2020-06-16T18:00:07.4028364Z 	at io.debezium.kafka.KafkaServer.startup(KafkaServer.java:218)
2020-06-16T18:00:07.4030095Z 	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
2020-06-16T18:00:07.4031034Z 	at io.debezium.kafka.KafkaCluster.startup(KafkaCluster.java:250)
2020-06-16T18:00:07.4032295Z 	at io.quarkus.it.kafka.KafkaSASLTestResource.start(KafkaSASLTestResource.java:44)
2020-06-16T18:00:07.4035990Z 	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:46)
2020-06-16T18:00:07.4036413Z 	... 44 more
```

@gunnarmorling any chance we could have a Debezium version supporting Scala 2.13?

**Comment by gunnarmorling** [comment]
I suppose we could do that, but I'm not 100% sure about the consequences. Potentially, it might break other users of `KafkaCluster` who are bound to 2.12. Note that the Kafka website recommends to use 2.12, if in doubt. Btw. it seems the OP said the problem is resolved on their end?

**Comment by gsmet** [comment]
Closing this one. We can revisit later once Debezium is ready for Scala 2.13.

**Comment by wiradikusuma** [comment]
From https://www.confluent.io/blog/apache-kafka-2-6-updates/

    the community has switched to using Scala 2.13 by default and now recommends using Scala 2.13 for production

Can we please upgrade to Scala 2.13 as well?

**Pull request closed without merging**
