### PR TITLE
enable hot reload on application.yaml

### PR DESCRIPTION
**Pull request by devauxbr**
Hi Quarkus Team and happy new year ! 🎉 

I've been playing with the latest release 1.1.0.Final and I find the new YAML configuration support awesome. Unfortunately I have realised that the hot deployment upon change on `application.yaml` is not supported (unlike with the regular `application.properties` file) :( From what I can tell, the feature was included in the [first draft PR](https://github.com/quarkusio/quarkus/pull/4525/files#diff-870ef4539cfeec6ab40ffb88ab640e26R22), but not the [final one](https://github.com/quarkusio/quarkus/pull/5973/files)

This PR fixes the issue. I am not sure if there is any easy way to add an automated test for this ? I have created a [small reproducer](https://github.com/devauxbr/quarkus-config-yaml-live-reload) to easily test this manually

Any feedback appreciated! :) 

Cheers

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Nice catch! 
About the tests you can use the QuarkusDevModeTest as in https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/hotreload/HotReloadWithFilterTest.java

**Comment by geoand** [comment]
Thanks for this!

It would be nice to have a test like @gastaldi described

**Review by gsmet — APPROVED** [review]
That's unfortunate, thanks for that.

As the others mentioned, having a test would help.

Thanks!

**Comment by devauxbr** [comment]
Thanks for the guidance, I have added an automated test 👍

**Review by gsmet — APPROVED** [review]
Perfect, thanks, let's wait for CI!

**Comment by machi1990** [comment]
Merged thanks @devauxbr @gsmet @gastaldi

**Pull request merged**
