### PR TITLE
Update Smallrye Reactive Messaging to 2.6.1

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by gsmet** [comment]
Wouldn't the build be broken with just the first commit?

**Comment by cescoffier** [comment]
@gsmet Yes, I will rebase.
I was more looking at the build result to see where it breaks, because at the moment even with the second commit, it breaks the HTTP connector.

@michalszynkiewicz FYI.

**Comment by cescoffier** [comment]
and hop 2.6.1...

**Review by kenfinnigan — APPROVED** [review]
Looks good, but it does fail CI

**Comment by cescoffier** [comment]
Failure looks unrelated. (MP TCK but on something not related to messaging)

**Comment by cescoffier** [comment]
Confirmed the TCK issue is about Quarkus Rest (we should update the name)

**Comment by kenfinnigan** [comment]
@FroMage @geoand Is that an expected TCK failure for Reactive REST?

**Comment by geoand** [comment]
It's one of the flaky SSE tests. You can ignore the failure, however if you need to a proper run of the MP TCK, you should probably restart CI

**Comment by gsmet** [comment]
@geoand if it's flaky, can we disable it? AFAIK, it failed twice in a row here and it's an issue.

**Comment by geoand** [comment]
It's flaky and we've tried to fix it without success, so I guess I'll disable it

**Comment by geoand** [comment]
The test has now been disabled

**Comment by cescoffier** [comment]
rebased and pushed... let's see.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
This time the MP TCKs failed on Reactive Messaging

**Pull request merged**
