### PR TITLE
Introduce `quarkus.datasource.devservices.init-script-path`

### PR DESCRIPTION
**Pull request by gastaldi**
- This enables specifying a SQL initialization script for Dev Services Databases

Added tests

### CODE REVIEW

**Comment by gastaldi** [comment]
This may be interesting for #29756

**Comment by Sanne** [comment]
nice!

**Comment by Sanne** [comment]
My only concern would be that this adds yet-another-way to do such things; we already have the Hibernate import scripts and also the liquibase/flyway migration tools.
I suppose that's overkill for most such uses cases? Also they don't play well with the reactive extensions.

It would be really nice if someone could dedicate some time to unify the experience; e.g. having the power of the migration tools but presented in a super-simple and light way.  Until that day comes, I'm ok to have this.

**Review by Sanne — APPROVED** [review]

**Comment by gastaldi** [comment]
@Sanne those are valid concerns, but this use case is specifically to allow creating additional users in the DB that would then be consumed by Flyway, which should happen before the app initializes

**Comment by Sanne** [comment]
@gastaldi right, not meaning to block this - not at all. Just thinking out loud :)

**Comment by Serkan80** [comment]
Cool ! I was looking for something like this.

And does it also work for multi datasources ?

```
quarkus.datasource.datasource1.devservices.init-script-path=script1.sql
quarkus.datasource.datasource2.devservices.init-script-path=script2.sql
```

**Comment by gastaldi** [comment]
@Serkan80 yes, it should work for that scenario too

**Comment by viniciusvasti** [comment]
It is not working for me.
I'm getting `org.postgresql.util.PSQLException: ERROR: relation "<table>" does not exist`
Does the defined script run before Flyway migrations?
I'd like to have my migrations ran then populate the database for dev and test profiles only.
Shouldn't this property allow that?

**Comment by gastaldi** [comment]
No, the `init-script-path` script is executed before Flyway executes

**Pull request merged**
