### PR TITLE
Fix fault-tolerance quickstart guide formatting

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by geoand** [comment]
👍

**Review by machi1990 — COMMENTED** [review]
👍

**Comment by gsmet** [comment]
@geoand a real approval would be nice so that I can merge it :)

I think you have write access, now, no?

**Comment by geoand** [comment]
@gsmet I do, but no one has told me explicitly to do make changes, which I was I have been holding off :P 

But I will start now :)

**Review by geoand — APPROVED** [review]
LGTM

**Pull request merged**
