### PR TITLE
DO NOT MERGE: Use our own repo manager

### PR DESCRIPTION
**Pull request by stuartwdouglas**
I have set up a quick and dirty Azure VM to test if this helps the CI timeouts, and to see what effect this has on the overall build speed

### CODE REVIEW

**Comment by gastaldi** [comment]
Another option is to use https://jitpack.io/

**Comment by gastaldi** [comment]
Ignore my last comment, that changes the GAV

**Comment by stuartwdouglas** [comment]
This seems to also speed up the build by around 6-10 minutes.

**Review by gsmet — APPROVED** [review]
Looks like a good solution to me.

**Comment by mkouba** [comment]
Hm, it would be good if the mirror was not publicly available (wrt maintenance, security, etc.).

**Comment by gsmet** [comment]
@stuartwdouglas I let you polish this and merge it when you see fit. We have merged the Google Mirror thing so that we have a sustainable solution for the time being.

**Pull request closed without merging**
