### PR TITLE
Fix swallowed failures in Reactive SQL Client tests

### PR DESCRIPTION
**Pull request by yrodiere**
I have no idea why these tests swallow failures, but it doesn't seem necessary to test the CDI bean producer... 
I mean we're not even checking that failures occur, so I really don't know why we would trigger those failures.

I'd like to fix this in order to reuse `application-default-datasource.properties` in other tests for another PR. Currently it's not possible, since that file is incomplete: depending on the client, sometimes it's completely empty, sometimes it's lacking credentials, ...

Hey @tsegismont can you confirm I didn't overlook some important reason to have connections fail and ignore the failures here?

### CODE REVIEW

**Comment by yrodiere** [comment]
Well the tests pass once we fix the configuration and stop ignoring failures, so I guess this is good to merge?

**Comment by gsmet** [comment]
I might be mistaken but I wonder if it was to have the tests working even when you don't have a Docker environment.

**Review by tsegismont — APPROVED** [review]
LGTM, thank you @yrodiere

**Comment by yrodiere** [comment]
Np, thanks for confirming @tsegismont !

@gsmet would you mind approving? Apparently @tsegismont's approval is not enough :)

**Comment by yrodiere** [comment]
> @gsmet would you mind approving? Apparently @tsegismont's approval is not enough :)

Bump :)

**Review by gastaldi — APPROVED** [review]

**Comment by yrodiere** [comment]
Thanks @gastaldi!

**Pull request merged**
