### PR TITLE
Allow certain @ConfigProperties fields to be ignored

### LINKED ISSUE #9762: Add @ConfigIgnore annotation for ignorable @ConfigProperties
I believe a `@ConfigIgnore` annotation should be added for fields that you don't want to be configured via `@ConfigProperties`

Currently if a class has an `@ConfigProperties` annotation it attempts to configure every variable in that class.  This lead to an issue where I was trying to use `@Inject` to set a variable. 
I was just using my configuration class as a single point of reference for that variable instead of having to inject it everywhere else.

### PR DESCRIPTION
**Pull request by geoand**
Resolves: #9762

### CODE REVIEW

**Comment by geoand** [comment]
CI Failure is completely unrelated:

```

2020-06-04T06:34:31.3546209Z [INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-hibernate-orm-panache-kotlin ---
2020-06-04T06:34:32.5673551Z [INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.4.17.Final
2020-06-04T06:34:33.7702241Z [INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/runner/work/quarkus/quarkus/integration-tests/hibernate-orm-panache-kotlin/target/quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner.jar
2020-06-04T06:34:33.9033717Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/runner/work/quarkus/quarkus/integration-tests/hibernate-orm-panache-kotlin/target/quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner.jar
2020-06-04T06:34:33.9131181Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Pulling image quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
2020-06-04T06:34:34.4183157Z 20.1.0-java11: Pulling from quarkus/ubi-quarkus-native-image
2020-06-04T06:34:34.4189246Z Digest: sha256:8ed2ee503623a35129da3eced5ce629a6dcb5cc42204af69ac39d6ca641ebf56
2020-06-04T06:34:34.4201389Z Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
2020-06-04T06:34:34.4210451Z quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
2020-06-04T06:34:36.8597583Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.1.0 (Java Version 11.0.7)
2020-06-04T06:34:37.7091760Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/runner/work/quarkus/quarkus/integration-tests/hibernate-orm-panache-kotlin/target/quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -J-Xmx5g -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner
2020-06-04T06:34:54.2944575Z -H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
2020-06-04T06:34:54.3159096Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]    classlist:  15,078.34 ms,  1.69 GB
2020-06-04T06:34:56.3096771Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]        (cap):   1,123.59 ms,  1.69 GB
2020-06-04T06:34:57.7103825Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]        setup:   3,381.40 ms,  1.69 GB
2020-06-04T06:34:58.9087648Z 06:34:58,906 INFO  [org.hib.Version] HHH000412: Hibernate ORM core version 5.4.17.Final
2020-06-04T06:34:58.9194290Z 06:34:58,918 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-06-04T06:34:58.9950241Z 06:34:58,994 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2020-06-04T06:35:34.7856360Z 06:35:34,784 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
2020-06-04T06:36:45.9472360Z WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!
2020-06-04T06:37:37.1797178Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]     (clinit):   1,693.08 ms,  3.18 GB
2020-06-04T06:37:39.1430700Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]   (typeflow):  92,074.33 ms,  3.18 GB
2020-06-04T06:37:39.1431318Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]    (objects):  61,645.14 ms,  3.18 GB
2020-06-04T06:37:39.1431755Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]   (features):   1,705.88 ms,  3.18 GB
2020-06-04T06:37:39.1758708Z [quarkus-integration-test-hibernate-orm-panache-kotlin-999-SNAPSHOT-runner:24]     analysis: 161,090.79 ms,  3.18 GB
2020-06-04T06:37:39.1795121Z Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.it.panache.kotlin.Address.getId(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
2020-06-04T06:37:39.1795557Z Detailed message:
2020-06-04T06:37:39.1795715Z Trace: 
2020-06-04T06:37:39.1801611Z 	at parsing io.quarkus.it.panache.kotlin.Address.toString(Address.kt:30)
2020-06-04T06:37:39.1801973Z Call path from entry point to io.quarkus.it.panache.kotlin.Address.toString(): 
2020-06-04T06:37:39.1802151Z 	at io.quarkus.it.panache.kotlin.Address.toString(Address.kt:30)
2020-06-04T06:37:39.1802318Z 	at java.lang.String.valueOf(String.java:2951)
2020-06-04T06:37:39.1802469Z 	at java.io.PrintStream.print(PrintStream.java:745)
2020-06-04T06:37:39.1808042Z 	at java.io.PrintStream.println(PrintStream.java:882)
2020-06-04T06:37:39.1808238Z 	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
2020-06-04T06:37:39.1808424Z 	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
2020-06-04T06:37:39.1808618Z 
2020-06-04T06:37:39.1809429Z com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.it.panache.kotlin.Address.getId(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
2020-06-04T06:37:39.1809657Z Detailed message:
2020-06-04T06:37:39.1813400Z Trace: 
2020-06-04T06:37:39.1813549Z 	at parsing io.quarkus.it.panache.kotlin.Address.toString(Address.kt:30)
2020-06-04T06:37:39.1813707Z Call path from entry point to io.quarkus.it.panache.kotlin.Address.toString(): 
2020-06-04T06:37:39.1813863Z 	at io.quarkus.it.panache.kotlin.Address.toString(Address.kt:30)
2020-06-04T06:37:39.1813965Z 	at java.lang.String.valueOf(String.java:2951)
2020-06-04T06:37:39.1817314Z 	at java.io.PrintStream.print(PrintStream.java:745)
2020-06-04T06:37:39.1817618Z 	at java.io.PrintStream.println(PrintStream.java:882)
2020-06-04T06:37:39.1817928Z 	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
2020-06-04T06:37:39.1818127Z 	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
2020-06-04T06:37:39.1818260Z 
2020-06-04T06:37:39.1821017Z 	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
2020-06-04T06:37:39.1826001Z 	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
2020-06-04T06:37:39.1830939Z 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
2020-06-04T06:37:39.1840711Z 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
2020-06-04T06:37:39.1840942Z 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
2020-06-04T06:37:39.1845592Z 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
2020-06-04T06:37:39.1850392Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2020-06-04T06:37:39.1855214Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2020-06-04T06:37:39.1864117Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2020-06-04T06:37:39.1864378Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2020-06-04T06:37:39.1869484Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by mkouba** [comment]
The impl looks good but I don't undestand the use case. Why would you add such a field to a `@ConfigProperties` file? I mean, it's just a config properties holder, it should not be used for anything else, or?

**Comment by geoand** [comment]
The use case I can think of is to do allow a startup event to set some of the fields.

The OP mentioned being able to use `@Inject@` on fields - but that is something I don't like and don't intend to do anything more to support

**Comment by mkouba** [comment]
> The use case I can think of is to do allow a startup event to set some of the fields.

Well, that somehow defeats the purpose of config properties, or?

> The OP mentioned being able to use @Inject@ on fields - but that is something I don't like and don't intend to do anything more to support

+1

@geoand I'm +0 for this PR. I'll approve it and let you decide (you're the author of the concept of `@ConfigProperties` anyway ;-).

**Review by mkouba — APPROVED** [review]

**Comment by geoand** [comment]
I think it's marginally useful but it's surface is very small, so I think it's fine to have it.

**Pull request merged**
