### PR TITLE
ci: remove services block from tck test runs

### PR DESCRIPTION
**Pull request by machi1990**

### CODE REVIEW

**Comment by geoand** [comment]
Makes sense to me, but can you please rebase onto master to pick up a CI fix?

Thanks

**Comment by geoand** [comment]
Tacks failed, is it related?

**Comment by machi1990** [comment]
> Tacks failed, is it related?

```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.641 s <<< FAILURE! - in org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedClassBeanTest
[ERROR] countedMethodsNotCalledYet(org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedClassBeanTest)  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: Max value of metric MetricID{name='org.eclipse.microprofile.metrics.tck.metrics.cGaugedClass.ConcurrentGaugedClassBean', tags=[tier="integration"]} should be 0 expected:<0> but was:<1>
```

I do not think it is related.

**Comment by geoand** [comment]
Yeah, most likely a flake. Can you nonetheless restart CI?

**Review by geoand — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks for this cleanup!

**Pull request merged**
