### PR TITLE
Split OIDC session cookie

### LINKED ISSUE #12254: [OIDC] Too large JWT cookie cause infinite redirect loop
**Too large JWT cause infinite redirect loop**
A cookie may not exceed 4096 bytes, so a very large JWT may cause the cookie not to be set at all. This results in the user being redirect back to the OIDC server. This is notably an issue with Keycloak instances with configuration that predates version 3.2 (roles were then included in the JWT).
This can probably be solved by splitting the JWT up into multiple cookies, although that's likely not the prettiest solution. Another approach could be to log more and prevent the redirection loop, letting the user know what the issue is.

**Edit: See https://github.com/quarkusio/quarkus/issues/12297 for a solution to the feature described below.**
~~**Support for application-type=service+web-app?**~~
~~I'm piggybacking with another OIDC-issue:~~
~~We have REST APIs that are used by both web apps and by other services. For the web app we'd like to use cookies, services supplies an "Authorization" header with the bearer token.~~
~~Setting `application-type=web-app` cause services to be redirected to OIDC server for authentication, setting `application-type=service` forbids web app from using the API.~~
~~I was unsuccessful finding a solution for this that didn't involve either duplicating the REST API or making the web app send bearer token with every request. Unless a solution for this already exists (or there are security concerns combining the two application types), it would be nice with a mode where header is checked for an Authorization entry before redirecting user to authenticate.~~

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #12254

Hi Pedro @pedroigor, Stuart @stuartwdouglas, this PR fixes the issue with a session cookie exceeding `4096` and while the user has fixed by disabling including the roles in the ID token, it is a matter of time before we'll get the issue reported again; if we start dealing with the encrypted tokens then the session cookie size will be massive anyway.
The solution so far is to split the session cookie into 3 cookies, one - ID token only (same old cookie name), plus one for AT and one for RT. This should work in most/all cases (the fact that the session value won't have to be split now will compensate a bit for having 3 cookies instead of one) but I'm also going to open a separate enhancement request to support a DB-based session manager

### CODE REVIEW

**Comment by pedroigor** [comment]
@sberyozkin We could still end-up reaching the limit depending on the size of those tokens (mainly if using JWTs and no interaction with userinfo endpoint).

I think there are two main use cases to consider here:

* Single Sign-On, and authentication-only, self-contained applications.
* Single Sign-On and frontend applications backed by some backend

In theory, the first should not require storing anything else but a simple session cookie, which we could build based on the subject, role, and expiration (we could maybe allow people to customize what is persisted into the cookie). That should help to keep the token small.

The second use case does require storing the access token (and RT) so that the frontend application can have access to the backend. An interesting point here, I think, is that use cases like that may be an indication that your frontend application should probably be designed so that you don't use cookies at all, but store tokens using the browser session storage. In other words, `quarkus-oidc` would just bridge the code flow with the OP and forward the code to the frontend (.e.g: HTML5) so that the frontend app itself can exchange the code with tokens (using some library such as `keycloak.js`).

Wdyt ?

**Comment by sberyozkin** [comment]
Hey @pedroigor 

For the 1st case, we generally need AT & RT - the latter is not only for the user info but also if it is injected into the service endpoint for it to propagate it and the latter to refresh when needed, I agree there could be cases where only ID token may suffice but in general we need all 3 of them.

But yeah, producing 3 cookies instead of obe feels like a hack as opposed to a proper solution as I can certainly imagine a massive encrypted ID token alone taking 6K in size or whatever  :-)

I feel a DB based solution will be all right, we won't be using HTTP sessions, but a DB connection. It will be up to a user how to ensure this DB session info is available across the nods, which is a general Quarkus DB concern anyway, the cookie then will be just a DB  key.

I was thinking of some extension like `quarkus-oidc-session-manager`, the current session code would be a default `SessionManager` implementation which just have them concatenated. `quarkus-oidc-session-manager` would depend on the Hibernate extension and have SessionManager which will store all 3 tokens in DB.

Does it sound a bit crazy or not too bad :-) ? CC @stuartwdouglas

**Comment by stuartwdouglas** [comment]
How do other systems deal with this issue?

**Comment by sberyozkin** [comment]
Hi Stuart @stuartwdouglas the same options have to be considered in all the systems RP (OIDC adapter) systems.
For some cases, where we can detect that no access or refresh tokens are injected (and no properties are set which may require them - this is easy) we can have a single ID token as a cookie and in the vast majority of cases it will never go beyond the limit. So this is one approach to investigate - but even if it works - there will always be cases where all 3 tokens are needed :-)
So a DB based solution can compensate in those cases where 3 tokens are needed and the cookie is too large. As I said, I'd not consider us doing anything about the DB replication, but only letting the users add an extra extension, and set the DB properties if they really need it - some users may like the idea anyway, since, unless the tokens are encrypted, their content can be introspected if the cookies are leaked somehow...

**Comment by sberyozkin** [comment]
Hi @pedroigor @stuartwdouglas I'm going to close this PR, it is linked from #12254 so we can check the discussion here will remain accessible. I'll try to open another draft PR to show you how it might look like, it will take some time though...

**Pull request closed without merging**
