### PR TITLE
Add support for Kubernetes Client retry properties

### LINKED ISSUE #29467: Add support for HTTP operation retries (with exponential backoff) in Kubernetes Client
### Description

Fabric8's Kubernetes client has exposed HTTP operation retry configuration options with exponential backoff since version 5.5.0 [0]:
* `kubernetes.request.retry.backoffLimit`
* `kubernetes.request.retry.backoffInterval`

Request Quarkus to add similar configurations in [KubernetesClientBuildConfig](https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-client/runtime-internal/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesClientBuildConfig.java) to support retries when the HTTP status code is 500 (Status Internal Server Error), 503 (Status Service Unavailable), or 504 (Status Server Timeout).

[0] https://developers.redhat.com/articles/2021/07/16/whats-new-fabric8-kubernetes-client-version-550

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #29467

### CODE REVIEW

**Comment by geoand** [comment]
cc @manusa

**Review by manusa — APPROVED** [review]
:raised_hands:

**Review by gsmet — APPROVED** [review]
Looks simple enough for me to approve.

**Comment by geoand** [comment]
🙏

**Pull request merged**
