### PR TITLE
Fix some gradle-extension-plugin apply bugs

### PR DESCRIPTION
**Pull request by djnalluri**
This PR fixes a few bugs with the gradle-extension-plugin as follows:
- ~~JavaPluginConvention is deprecated so I replaced it with it's successor JavaPluginExtension~~
- The deployment module configuration is read before configuration is applied making the module fixed to the default name. I changed it to trigger on `afterEvaluate`.
- The annotation processor can't be resolved without providing an explicit version. I've changed it to detect the current version of the plugin and set the annotation processor to the same one.

These changes are based on issues I ran into during usage in my own environment using Gradle 7.2. I'm not a Gradle expert. @glefloch If there is anything that doesn't fit well with your plans, let me know and I can make changes or close this PR.

### CODE REVIEW

**Review by glefloch — CHANGES_REQUESTED** [review]
Thanks for this @djnalluri I left a few comments but the overall looks good

**Comment by djnalluri** [comment]
I ran into a few caveats while implementing the suggestion for determining the annotation processor version. The `compileClasspath` configuration needs to be resolved before the `eachDependency` action will trigger. This required me to run the `build` task in tests before running `dependencies`. Additionally, if there are no sources, resolution isn't attempted so I added empty classes to the test environments.

**Comment by glefloch** [comment]
ok, that should be good, could you format your code using `mvn -Dquickly` ? the CI failed because of that.

**Comment by djnalluri** [comment]
Oops, missed the part about squashing commits. _Now_ it should be all set.

**Review by glefloch — APPROVED** [review]

**Comment by glefloch** [comment]
Thanks for this work @djnalluri !

**Pull request merged**
