### PR TITLE
Adds processor to annotation JsonAutoDetect

### PR DESCRIPTION
**Pull request by netodevel**
This pr adds the processor to Jackson `JsonAutoDetect` annotation (currently needed for records usage);

Bug:
This error happens in the endpoint's response serialization (mode native):
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed to access RecordComponents of type `com.netodevel.money_transfer.dto.MoneyTransferResponse`
```

How to Reproduce?

**clone repository**
git clone https://github.com/netodevel/money-transfer-service

**build native image**
mvn clean install -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.2.0-java16 -DskipTests

**run postgresql local**
docker-compose up -d 

**execute binary**
./target/money-transfer-service-1.0.0-SNAPSHOT-runner 

** execute request **
[POST]  url: http://localhost:8080/api/money-transfer

```json
{
  "fromAccount": "999",
  "toAccount": "777",
  "amount": 50
}
```

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks

**Review by geoand — CHANGES_REQUESTED** [review]
One small change and this should be good

**Comment by geoand** [comment]
You need to format the code

**Comment by geoand** [comment]
When you are done, please squash the commits

**Comment by netodevel** [comment]
@geoand, sorry about format :/ 

I've fixed the formatting and squash, Thanks

**Review by geoand — APPROVED** [review]

**Pull request merged**
