### PR TITLE
Fix Cookie handling in reactive rest client

### PR DESCRIPTION
**Pull request by geoand**
Original discussion in https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Reactive.20Client.20Cookies

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
nice!

If that's not a big problem, could you also tests for sub-resources?

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by geoand** [comment]
Let me check that out

**Comment by geoand** [comment]
There seem to be issues with subresources for both cookies and headers... I'm looking into it

**Comment by michalszynkiewicz** [comment]
> There seem to be issues with subresources for both cookies and headers... I'm looking into it

hmm... I was quite sure we had tests for headers

**Comment by geoand** [comment]
PR updated with the fix to both headers and cookie handlinh

**Review by michalszynkiewicz — APPROVED** [review]

**Pull request merged**
