### PR TITLE
Rethink closing strategy of the ThreadLocalPool optimised pgpool

### PR DESCRIPTION
**Pull request by Sanne**
Have been tinkering with the new pool a bit.

The main improvement is that the thredlocals and their matching List of opened pools is being treated as a single element of state, so stored together and closed as one. Before you could have some odd situations with the list being attempted to be modified during a close, or viceversa.

Should still be very efficient, however I didn't test that.

### CODE REVIEW

**Comment by FroMage** [comment]
Sorry I can't review this besides rubber-stamping it. This concurrency stuff is not something I'm familiar with.

**Comment by FroMage** [comment]
I mean, I can definitely rubber-stamp this if that's what you're after, but I suspect you want someone to actually understand what you changed, right? If yes, I'm not qualified.

**Comment by Sanne** [comment]
Ok I'll take the rubber-stamp then :) If there's issues, I'll fix them

Re-pushed as there was a formatting issue.

**Comment by Sanne** [comment]
Since @geoand had to revert the original patch in #10240 , I've re-included it here but deleting the problematic test: it's late now and I can't check what's wrong with the test, but the failure isn't related with the pool optimisation.

**Comment by geoand** [comment]
CI is passing

**Comment by Sanne** [comment]
great. Could you merge it @geoand ?  I think Stephane mentioned going on PTO and we need the feature - this code is all disabled by default so should be low risk.

**Review by geoand — APPROVED** [review]
I trust you :)

**Pull request merged**
