### PR TITLE
Fix on RestPathAnnotationProcessor to ensure that the correct url template is computed for metrics

### PR DESCRIPTION
**Pull request by souchel**
This is a proposition to fix a bug on the metric system. When using quarkus-micrometer, the metrics contain information on the time taken by a request. One of the tag is the uri and currently the uri is incorrect.
For example we get:
```text
# HELP http_server_requests_seconds  
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/{firstname}/{firstname}",} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/{firstname}/{firstname}",} 0.1192732
```
instead of:
```# HELP http_server_requests_seconds  
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/hello/{firstname}",} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/hello/{firstname}",} 0.1192732
```

Here is a reproducer: https://github.com/souchel/quarkus-metrics-reproducer

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]
Thanks. Let's see what @ebullient thinks but PRs should target the `main` branch and are backported to older branches when it makes sense.

**Comment by gsmet** [comment]
@ebullient any chance you could have a look? You're our path expert (how lucky!) and this one might be a pain if you're affected.

**Comment by geoand** [comment]
Also cc @brunobat @radcortez

**Comment by brunobat** [comment]
Will take a look

**Comment by souchel** [comment]
> @souchel can you please update your PR by moving from the legacy `javax` to the new `jakarta` packages on the test? Quarkus 3.x now uses jakarta.
> 
> The reproducer worked for me and I think the fix is good. Nice one!

Will do, thanks :)

**Comment by brunobat** [comment]
Approved the CI run to see how it looks.

**Review by brunobat — APPROVED** [review]
The CI errors seem unrelated. 
They work on my machine but are quite slow. That's probably why they are failing.

**Comment by souchel** [comment]
@brunobat I also think the failures are unrelated, what's the next step ?

**Comment by brunobat** [comment]
@gsmet will merge when the right time comes.

**Pull request merged**
