### PR TITLE
Change repository order in gradle test

### PR DESCRIPTION
**Pull request by glefloch**
This branch change repository order in test. 
This fix failed CI jobs.

### CODE REVIEW

**Comment by geoand** [comment]
CI seems to be reporting Gradle errors on one of the jobs. Are they related?

**Comment by glefloch** [comment]
@geoand, yes, I think this is related. I'm having a look at the failure.

**Comment by geoand** [comment]
Great, thanks

**Comment by glefloch** [comment]
That's weird, looking at logs, everything looks fine. I restarted the CI, the windows-gradle CI is ok, but now the jdk11-windows action is failing  on `resteasy-reactive`.

**Comment by geoand** [comment]
That seems like a flaky test - I'll keep an eye out for it

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks @glefloch!

**Comment by glefloch** [comment]
I'm the one who broke CI, that's the least I can do :) thanks for the review and merge!

**Pull request merged**
