### PR TITLE
Ensure various non-bean JAX-RS components work in native

### LINKED ISSUE #16211: Reactive resteasy native exception
## Describe the bug
When running reactive resteasy in native mode and accessing an endpoint with insufficient right a forbidden exception is thrown and is catched by `io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.ForbiddenExceptionMapper`that throws an exception

### Expected behavior
This should work flowlessly 

### Actual behavior
An exception is thrown with following : 

`
Caused by: java.lang.InstantiationException: Type io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.ForbiddenExceptionMapper` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
`

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #16211

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
It makes sense and it can't hurt so I'm merging this to get it into 2.1.1.Final.

**Comment by geoand** [comment]
Thanks 👍

**Review by FroMage — COMMENTED** [review]
This would probably have benefited from a native test…

**Comment by geoand** [comment]
Indeed, I'll keep it in mind

**Comment by geoand** [comment]
@FroMage here you go: https://github.com/quarkusio/quarkus/pull/19227. It also uncovered an unrelated RR bug

**Comment by FroMage** [comment]
Wow :)

**Pull request merged**
