### PR TITLE
Adjust LCMS substitutions for GraalVM JDK 17

### LINKED ISSUE #19356: sun.java2d.cmm.lcms.LCMS#setTagDataNative substitution is broken on JDK17
### Describe the bug

On JDK17 [`sun.java2d.cmm.lcms.LCMS#setTagDataNative` is declared as `static`](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/sun/java2d/cmm/lcms/LCMS.java#L73). Prior to JDK17 this method was not `static` so now the [Quarkus substitution](https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/graal/LCMSSubstitutions.java#L32) leads to a build time error:
```
Error: Static modifier mismatch: private void io.quarkus.runtime.graal.Target_sun_java2d_cmm_lcms_LCMS.setTagDataNative(long,int,byte[]), static native void sun.java2d.cmm.lcms.LCMS.setTagDataNative(long,int,byte[])
com.oracle.svm.core.util.UserError$UserException: Static modifier mismatch: private void io.quarkus.runtime.graal.Target_sun_java2d_cmm_lcms_LCMS.setTagDataNative(long,int,byte[]), static native void sun.java2d.cmm.lcms.LCMS.setTagDataNative(long,int,byte[])
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:725)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:368)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:340)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:941)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:873)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:531)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:492)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:400)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:566)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:596)
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

This is currently reproducible only with JDK17 GraalVM builds.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The substitution should be version specific with an alternative declaration for JDK17 using `onlyWith = JDK17OrLater.class`.

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #19356

@zakkak would you have any way to test that? I did that completely in the dark...

### CODE REVIEW

**Comment by zakkak** [comment]
> @zakkak would you have any way to test that? I did that completely in the dark...

We currently don't have any JDK 17 builds in our pipelines, but @Karm is working on it. Maybe he can help testing it.

**Comment by jaikiran** [comment]
The JVMCI JDK17 releases/builds are made available at https://github.com/graalvm/labs-openjdk-17. I used the `labsjdk-ce-17-jvmci-21.3-b01` to build the latest GraalVM community edition from the GraalVM repo. I then used it to test the `getting-started` quickstart of quarkus to build and use the native image for it.

An additional change was needed in this PR because it was failing during native image build with:

```
Error: Could not find target method: static void io.quarkus.runtime.graal.Target_sun_java2d_cmm_lcms_LCMS_JDK17.getProfileDataNative(long,byte[])
com.oracle.svm.core.util.UserError$UserException: Could not find target method: static void io.quarkus.runtime.graal.Target_sun_java2d_cmm_lcms_LCMS_JDK17.getProfileDataNative(long,byte[])
```
In the latest JDK17 version, this method now takes just one parameter. I've fixed that part and updated this PR. With this change, the basic test and building of the `getting-started` quickstart against a JDK17 built GraalVM and GraalVM 21.1.0 (Java 11) release both went fine.

Once the CI jobs of this PR come out fine, I think it probably is safe to merge this.

**Comment by gsmet** [comment]
Pushed a rebase as there were too many CI failures.

**Comment by gsmet** [comment]
@jaikiran can I have your approval? :)

**Review by jaikiran — APPROVED** [review]
This looks good and more importantly doesn't regress against existing Java/Native image versions. Approved :)

**Comment by Karm** [comment]
@gsmet @zakkak  I can confirm it's fixed :heavy_check_mark: 

Running with [JDK 17 based Mandrel 21.3-SNAPSHOT](https://ci.modcluster.io/view/Mandrel/job/mandrel-master-jdk17-linux-build/2/artifact/mandrel-java17-linux-amd64-21.3.0-deve98ae39603.tar.gz):

## Quarkus 2.2.0.CR1

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 21.3.0-deve98ae39603 Mandrel Distribution (Java Version 17-internal+0-adhoc.tester.jdk17)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /home/karm/workspaceRH/mandrel-release/mandrel-java17-21.3.0-deve98ae39603/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -H:-ParseOnce code-with-quarkus-1.0.0-SNAPSHOT-runner
[code-with-quarkus-1.0.0-SNAPSHOT-runner:211626]    classlist:   1,187.86 ms,  0.93 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:211626]        setup:     471.32 ms,  0.93 GB
Error: Static modifier mismatch: private long io.quarkus.runtime.graal.Target_sun_java2d_cmm_lcms_LCMS.loadProfileNative(byte[],java.lang.Object), private static native long sun.java2d.cmm.lcms.LCMS.loadProfileNative(byte[],java.lang.Object)
com.oracle.svm.core.util.UserError$UserException: Static modifier mismatch: private long io.quarkus.runtime.graal.Target_sun_java2d_cmm_lcms_LCMS.loadProfileNative(byte[],java.lang.Object), private static native long sun.java2d.cmm.lcms.LCMS.loadProfileNative(byte[],java.lang.Object)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:725)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:368)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:340)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:944)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:873)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:531)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:492)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:400)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:566)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:596)
[code-with-quarkus-1.0.0-SNAPSHOT-runner:211626]      [total]:   1,695.69 ms,  0.93 GB
# Printing build artifacts to: /tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.build_artifacts.txt
Error: Image build request failed with exit status 1
```

## Quarkus 999-SNAPSHOT 01103295

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 21.3.0-deve98ae39603 Mandrel Distribution (Java Version 17-internal+0-adhoc.tester.jdk17)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /home/karm/workspaceRH/mandrel-release/mandrel-java17-21.3.0-deve98ae39603/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -H:-ParseOnce code-with-quarkus-1.0.0-SNAPSHOT-runner
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]    classlist:   1,121.82 ms,  0.96 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]        (cap):     466.06 ms,  0.94 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]        setup:   1,790.03 ms,  0.94 GB
The bundle named: messages, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
01:32:42,101 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]     (clinit):     480.00 ms,  4.27 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]   (typeflow):   2,433.94 ms,  4.27 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]    (objects):  15,841.08 ms,  4.27 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]   (features):     788.91 ms,  4.27 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]     analysis:  20,550.71 ms,  4.27 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]     universe:   1,647.85 ms,  4.27 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]      (parse):   3,751.59 ms,  4.79 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]     (inline):   4,122.05 ms,  6.11 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]    (compile):  19,457.91 ms,  6.14 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]      compile:  29,120.34 ms,  6.14 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]        image:   2,718.64 ms,  6.14 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]        write:     427.25 ms,  6.14 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:210174]      [total]:  57,626.01 ms,  6.14 GB
# Printing build artifacts to: /tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.build_artifacts.txt
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] objcopy --strip-debug code-with-quarkus-1.0.0-SNAPSHOT-runner
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 60038ms

```


Although if you go beyond Hello World, there will be more substitutions adjustments needed:  #19633

**Pull request merged**
