### PR TITLE
Infinispan extension hard-coding location of hotrod-client.properties

### LINKED ISSUE #14368: quarkus-infinispan extension hard-coding location of hotrod-client.properties
I posted this on zulip chat last week but haven't been able to get a response (https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20infinispan.20extension.20hotrod-client.2Eproperties/near/222425566)

Using the Infinispan component with camel-k. The issue is that the quarkus-infinispan extension hard-codes the location of `hotrod-client.properties` as `META-INF/hotrod-client.properties` (https://github.com/quarkusio/quarkus/blob/master/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java#L62).

In camel-k, the build is performed by the operator, so the user has no way to put `hotrod-client.properties` within a `META-INF` directory. The user just submits an `Integration` custom resource (https://gist.github.com/edeandrea/770c84be9da204ff0b13f2340975904e#file-camelk-client-yml-L56-L57) referencing a `ConfigMap`, and that `ConfigMap` is mounted in a directory in the running pod and is added to the root of the classpath. Because of this, as a camel-k user using the camel-infinispan component (which the underlying runtime is quarkus, handing off to the quarkus-infinispan extension), the integration just doesn't work.

This has been cross-posted on the camel-k issue tracker as well (apache/camel-k#1898)

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #14368

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@wburns @karesti  basic implementation for option 1 describe in #14368

**Comment by lburgazzoli** [comment]
@wburns @karesti I think this pr can be closed right ?

**Comment by karesti** [comment]
@lburgazzoli @wburns

**Comment by geoand** [comment]
Should this be closed?

**Comment by lburgazzoli** [comment]
@geoand @karesti I don't know if it can be closed as I'm not aware of a solution for the issue

**Comment by lburgazzoli** [comment]
I think I'm going to close this and defer the fix to the infinispan team 

@geoand would that be ok ?

**Comment by geoand** [comment]
@lburgazzoli makes sense

**Pull request closed without merging**
