### PR TITLE
hot reload OpenAPI static files

### LINKED ISSUE #2907: OpenAPI with static files instead of annotation scanning
**Describe the bug**
It seems that all the `microprofile-open-api` features are not supported yet by quarkus.

One setup example:
Add the config property `mp.openapi.scan.disable=true` and a static OpenAPI file in `src/main/resources/META-INF/openapi.yaml`.

In that case, the `microprofile-open-api` annotation scanning should be disabled and the openapi spec should be served from the static file.

See https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#static-openapi-files

**Expected behavior**
You see the static file served at http://localhost:8080/openapi

**Actual behavior**
I did not manage to see my local file, the server is always serving the generated one

**To Reproduce**
1. Create a project with Quarkus RESTEasy
2. Add the openapi extension and configure as described

**Configuration**
```properties
mp.openapi.scan.disable=true
```

Static OpenAPI file (that would be different from the generated one):
```yaml
---
openapi: 3.0.1
info:
  title: My HelloWorld API
  version: "1.0"
  license:
    name: Eclipse Public License 2.0
    url: 'https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html'
paths:
  /hello:
    get:
      description: hello world method
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Darwin  18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```
 - GraalVM version (if different from Java): [not used]
 - Quarkus version or git rev: 0.16.1

---

We had a quick look at the code with @emmanuelbernard at Voxxed Days Luxembourg 2019.

There is one integration test for the default setup (generated spec based on the annotation)
https://github.com/quarkusio/quarkus/blob/master/integration-tests/main/src/test/java/io/quarkus/it/main/OpenApiTestCase.java

But other scenario should be tested as test of the "deployment" module of "smallrye-openapi"
https://github.com/quarkusio/quarkus/tree/master/extensions/smallrye-openapi/deployment/

cc: @kenfinnigan

### PR DESCRIPTION
**Pull request by machi1990**
Fixes https://github.com/quarkusio/quarkus/issues/2907#issuecomment-504117198

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Good catch!

**Comment by gsmet** [comment]
@machi1990 just to understand, does it fix the whole issue?

**Comment by machi1990** [comment]
> @machi1990 just to understand, does it fix the whole issue?

I'd say no, the overall issue was about supporting "all" microprofile-open-api features: it is broad. So this only fixes hot reloading openapi static files.

**Comment by jmini** [comment]
Thank you a lot for this PR!

**Pull request merged**
