### PR TITLE
Upgrade to Mutiny 2.6.2 and the Vert.x Mutiny bindings 3.13.2

### PR DESCRIPTION
**Pull request by jponge**
Upgrade to:

- Mutiny 2.6.2, and
- Vert.x Mutiny bindings 3.13.2.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Comment by jponge** [comment]
(rebased due to a an application BOM conflict)

**Comment by gsmet** [comment]
I'm not sure what's going on with these builds being stuck. It's a bit concerning...

**Comment by gsmet** [comment]
I saw several of them blocking in `quarkus-rest-links-deployment` testing.

Thread dump is:

```
2024-07-13T09:59:13.2030569Z Test has been running for more than 5 minutes, thread dump is:
2024-07-13T09:59:13.2031194Z 
2024-07-13T09:59:13.2031203Z 
2024-07-13T09:59:13.2032897Z Thread[#27,gradle-enterprise-test-client-gradle-enterprise-test-listener,5,gradle-enterprise-test-client]=[Ljava.lang.StackTraceElement;@4be97cd5
2024-07-13T09:59:13.2034388Z 
2024-07-13T09:59:13.2034397Z 
2024-07-13T09:59:13.2035009Z java.base@21.0.3/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1124)
2024-07-13T09:59:13.2036406Z java.base@21.0.3/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
2024-07-13T09:59:13.2037830Z app//com.gradle.maven.scan.extension.test.listener.obfuscated.k.a.a(SourceFile:141)
2024-07-13T09:59:13.2039305Z app//com.gradle.maven.scan.extension.test.listener.obfuscated.k.a.b(SourceFile:93)
2024-07-13T09:59:13.2041033Z app//com.gradle.maven.scan.extension.test.listener.obfuscated.k.a$$Lambda/0x00007f8cc80b1800.run(Unknown Source)
2024-07-13T09:59:13.2043310Z java.base@21.0.3/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
2024-07-13T09:59:13.2044638Z java.base@21.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:317)
2024-07-13T09:59:13.2046220Z java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-07-13T09:59:13.2047852Z java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-07-13T09:59:13.2049092Z java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
2024-07-13T09:59:13.2049952Z java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
2024-07-13T09:59:13.2050489Z 
2024-07-13T09:59:13.2050498Z 
2024-07-13T09:59:13.2050988Z Thread[#10,Finalizer,8,system]=[Ljava.lang.StackTraceElement;@6847e836
2024-07-13T09:59:13.2051628Z 
2024-07-13T09:59:13.2051636Z 
2024-07-13T09:59:13.2052105Z java.base@21.0.3/java.lang.Object.wait0(Native Method)
2024-07-13T09:59:13.2053102Z java.base@21.0.3/java.lang.Object.wait(Object.java:366)
2024-07-13T09:59:13.2053908Z java.base@21.0.3/java.lang.Object.wait(Object.java:339)
2024-07-13T09:59:13.2055013Z java.base@21.0.3/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
2024-07-13T09:59:13.2056331Z java.base@21.0.3/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
2024-07-13T09:59:13.2057696Z java.base@21.0.3/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
2024-07-13T09:59:13.2059065Z java.base@21.0.3/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2024-07-13T09:59:13.2059830Z 
2024-07-13T09:59:13.2059839Z 
2024-07-13T09:59:13.2060343Z Thread[#178,Test thread dump timer,5,main]=[Ljava.lang.StackTraceElement;@5fab0e10
2024-07-13T09:59:13.2061073Z 
2024-07-13T09:59:13.2061081Z 
2024-07-13T09:59:13.2061436Z java.base@21.0.3/java.lang.Thread.dumpThreads(Native Method)
2024-07-13T09:59:13.2062426Z java.base@21.0.3/java.lang.Thread.getAllStackTraces(Thread.java:2521)
2024-07-13T09:59:13.2063796Z app//io.quarkus.test.QuarkusProdModeTest$PrintStackTraceTimerTask.run(QuarkusProdModeTest.java:826)
2024-07-13T09:59:13.2065115Z java.base@21.0.3/java.util.TimerThread.mainLoop(Timer.java:566)
2024-07-13T09:59:13.2066041Z java.base@21.0.3/java.util.TimerThread.run(Timer.java:516)
2024-07-13T09:59:13.2066611Z 
2024-07-13T09:59:13.2066623Z 
2024-07-13T09:59:13.2067104Z Thread[#11,Signal Dispatcher,9,system]=[Ljava.lang.StackTraceElement;@3031246e
2024-07-13T09:59:13.2067828Z 
2024-07-13T09:59:13.2067836Z 
2024-07-13T09:59:13.2067844Z 
2024-07-13T09:59:13.2067851Z 
2024-07-13T09:59:13.2068627Z Thread[#17,Common-Cleaner,8,InnocuousThreadGroup]=[Ljava.lang.StackTraceElement;@30bee969
2024-07-13T09:59:13.2069464Z 
2024-07-13T09:59:13.2069472Z 
2024-07-13T09:59:13.2069843Z java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method)
2024-07-13T09:59:13.2071217Z java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
2024-07-13T09:59:13.2073038Z java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
2024-07-13T09:59:13.2074691Z java.base@21.0.3/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71)
2024-07-13T09:59:13.2075882Z java.base@21.0.3/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143)
2024-07-13T09:59:13.2077123Z java.base@21.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218)
2024-07-13T09:59:13.2078293Z java.base@21.0.3/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
2024-07-13T09:59:13.2079276Z java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
2024-07-13T09:59:13.2080107Z java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
2024-07-13T09:59:13.2081137Z java.base@21.0.3/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
2024-07-13T09:59:13.2082103Z 
2024-07-13T09:59:13.2082112Z 
2024-07-13T09:59:13.2082593Z Thread[#26,Reference Reaper #1,5,main]=[Ljava.lang.StackTraceElement;@676fb110
2024-07-13T09:59:13.2083449Z 
2024-07-13T09:59:13.2083457Z 
2024-07-13T09:59:13.2083851Z java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method)
2024-07-13T09:59:13.2084524Z java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
2024-07-13T09:59:13.2085607Z java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
2024-07-13T09:59:13.2086597Z java.base@21.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
2024-07-13T09:59:13.2087392Z java.base@21.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
2024-07-13T09:59:13.2088400Z java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
2024-07-13T09:59:13.2089375Z java.base@21.0.3/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:67)
2024-07-13T09:59:13.2090125Z java.base@21.0.3/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
2024-07-13T09:59:13.2090879Z java.base@21.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:234)
2024-07-13T09:59:13.2091554Z app//io.smallrye.common.ref.References$ReaperThread.run(References.java:58)
2024-07-13T09:59:13.2091954Z 
2024-07-13T09:59:13.2091959Z 
2024-07-13T09:59:13.2092157Z Thread[#1,main,5,main]=[Ljava.lang.StackTraceElement;@60b3f863
2024-07-13T09:59:13.2092493Z 
2024-07-13T09:59:13.2092497Z 
2024-07-13T09:59:13.2092704Z java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method)
2024-07-13T09:59:13.2093350Z java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
2024-07-13T09:59:13.2094314Z java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
2024-07-13T09:59:13.2095294Z java.base@21.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
2024-07-13T09:59:13.2096104Z java.base@21.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
2024-07-13T09:59:13.2097126Z java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
2024-07-13T09:59:13.2098030Z java.base@21.0.3/java.lang.ProcessImpl.waitFor(ProcessImpl.java:425)
2024-07-13T09:59:13.2098674Z app//io.quarkus.test.QuarkusProdModeTest.stop(QuarkusProdModeTest.java:647)
2024-07-13T09:59:13.2099388Z app//io.quarkus.test.QuarkusProdModeTest.afterAll(QuarkusProdModeTest.java:743)
2024-07-13T09:59:13.2100419Z app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$18(ClassBasedTestDescriptor.java:462)
2024-07-13T09:59:13.2101584Z app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda/0x00007f8cc88d6d30.execute(Unknown Source)
2024-07-13T09:59:13.2102640Z app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-07-13T09:59:13.2103797Z app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$19(ClassBasedTestDescriptor.java:462)
2024-07-13T09:59:13.2104970Z app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda/0x00007f8cc88d6b00.accept(Unknown Source)
2024-07-13T09:59:13.2105995Z app//org.junit.platform.commons.util.CollectionUtils.forEachInReverseOrder(CollectionUtils.java:217)
2024-07-13T09:59:13.2107108Z app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllCallbacks(ClassBasedTestDescriptor.java:461)
2024-07-13T09:59:13.2108259Z app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:236)
2024-07-13T09:59:13.2109280Z app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:85)
2024-07-13T09:59:13.2110344Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:161)
2024-07-13T09:59:13.2111420Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f8cc88cd0d0.execute(Unknown Source)
2024-07-13T09:59:13.2112545Z app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-07-13T09:59:13.2113601Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:161)
2024-07-13T09:59:13.2114718Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f8cc8110eb0.invoke(Unknown Source)
2024-07-13T09:59:13.2115603Z app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2024-07-13T09:59:13.2116521Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2024-07-13T09:59:13.2117577Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f8cc8110a98.execute(Unknown Source)
2024-07-13T09:59:13.2118615Z app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-07-13T09:59:13.2119781Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2024-07-13T09:59:13.2120769Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2024-07-13T09:59:13.2122173Z app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda/0x00007f8cc8112040.accept(Unknown Source)
2024-07-13T09:59:13.2123161Z java.base@21.0.3/java.util.ArrayList.forEach(ArrayList.java:1596)
2024-07-13T09:59:13.2124248Z app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2024-07-13T09:59:13.2125589Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2024-07-13T09:59:13.2126642Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f8cc81110d0.execute(Unknown Source)
2024-07-13T09:59:13.2127689Z app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-07-13T09:59:13.2128746Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2024-07-13T09:59:13.2129809Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f8cc8110eb0.invoke(Unknown Source)
2024-07-13T09:59:13.2130698Z app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2024-07-13T09:59:13.2131615Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2024-07-13T09:59:13.2132671Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f8cc8110a98.execute(Unknown Source)
2024-07-13T09:59:13.2133828Z app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-07-13T09:59:13.2134884Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2024-07-13T09:59:13.2135879Z app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2024-07-13T09:59:13.2137118Z app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
2024-07-13T09:59:13.2138484Z app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2024-07-13T09:59:13.2139631Z app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
2024-07-13T09:59:13.2140732Z app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
2024-07-13T09:59:13.2141803Z app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
2024-07-13T09:59:13.2142881Z app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
2024-07-13T09:59:13.2144080Z app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
2024-07-13T09:59:13.2145169Z app//org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda/0x00007f8cc80ab778.accept(Unknown Source)
2024-07-13T09:59:13.2146400Z app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
2024-07-13T09:59:13.2147575Z app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
2024-07-13T09:59:13.2148511Z app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
2024-07-13T09:59:13.2149320Z app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
2024-07-13T09:59:13.2150159Z app//org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
2024-07-13T09:59:13.2151101Z app//org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
2024-07-13T09:59:13.2152103Z app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
2024-07-13T09:59:13.2153188Z app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
2024-07-13T09:59:13.2154279Z app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
2024-07-13T09:59:13.2155241Z app//org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2024-07-13T09:59:13.2156063Z app//org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2024-07-13T09:59:13.2156797Z app//org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2024-07-13T09:59:13.2157517Z app//org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2024-07-13T09:59:13.2157944Z 
2024-07-13T09:59:13.2157949Z 
2024-07-13T09:59:13.2158421Z Thread[#19,surefire-forkedjvm-stream-flusher,5,main]=[Ljava.lang.StackTraceElement;@5998a24f
2024-07-13T09:59:13.2158902Z 
2024-07-13T09:59:13.2158906Z 
2024-07-13T09:59:13.2159119Z java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method)
2024-07-13T09:59:13.2159776Z java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
2024-07-13T09:59:13.2160797Z java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
2024-07-13T09:59:13.2162208Z java.base@21.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
2024-07-13T09:59:13.2163358Z java.base@21.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
2024-07-13T09:59:13.2164355Z java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
2024-07-13T09:59:13.2165228Z java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2024-07-13T09:59:13.2166089Z java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-07-13T09:59:13.2166764Z java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
2024-07-13T09:59:13.2167245Z java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
2024-07-13T09:59:13.2167543Z 
2024-07-13T09:59:13.2167550Z 
2024-07-13T09:59:13.2167974Z Thread[#21,surefire-forkedjvm-command-thread,5,main]=[Ljava.lang.StackTraceElement;@1eaaedb4
2024-07-13T09:59:13.2168457Z 
2024-07-13T09:59:13.2168461Z 
2024-07-13T09:59:13.2168686Z java.base@21.0.3/java.io.FileInputStream.readBytes(Native Method)
2024-07-13T09:59:13.2169282Z java.base@21.0.3/java.io.FileInputStream.read(FileInputStream.java:287)
2024-07-13T09:59:13.2169947Z java.base@21.0.3/java.io.BufferedInputStream.read1(BufferedInputStream.java:345)
2024-07-13T09:59:13.2170670Z java.base@21.0.3/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
2024-07-13T09:59:13.2171479Z java.base@21.0.3/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
2024-07-13T09:59:13.2172164Z java.base@21.0.3/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
2024-07-13T09:59:13.2172857Z java.base@21.0.3/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
2024-07-13T09:59:13.2173640Z java.base@21.0.3/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
2024-07-13T09:59:13.2174365Z java.base@21.0.3/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
2024-07-13T09:59:13.2175111Z app//org.apache.maven.surefire.api.util.internal.Channels$3.readImpl(Channels.java:169)
2024-07-13T09:59:13.2176243Z app//org.apache.maven.surefire.api.util.internal.AbstractNoninterruptibleReadableChannel.read(AbstractNoninterruptibleReadableChannel.java:50)
2024-07-13T09:59:13.2177456Z app//org.apache.maven.surefire.api.stream.AbstractStreamDecoder.read(AbstractStreamDecoder.java:430)
2024-07-13T09:59:13.2178493Z app//org.apache.maven.surefire.api.stream.AbstractStreamDecoder.read(AbstractStreamDecoder.java:419)
2024-07-13T09:59:13.2179595Z app//org.apache.maven.surefire.api.stream.AbstractStreamDecoder.readMessageType(AbstractStreamDecoder.java:116)
2024-07-13T09:59:13.2180565Z app//org.apache.maven.surefire.booter.stream.CommandDecoder.decode(CommandDecoder.java:77)
2024-07-13T09:59:13.2181488Z app//org.apache.maven.surefire.booter.spi.CommandChannelDecoder.decode(CommandChannelDecoder.java:60)
2024-07-13T09:59:13.2182414Z app//org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:290)
2024-07-13T09:59:13.2183097Z java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
2024-07-13T09:59:13.2183583Z java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
2024-07-13T09:59:13.2183879Z 
2024-07-13T09:59:13.2183884Z 
2024-07-13T09:59:13.2184251Z Thread[#217,process reaper (pid 118722),10,InnocuousThreadGroup]=[Ljava.lang.StackTraceElement;@4d73840
2024-07-13T09:59:13.2184746Z 
2024-07-13T09:59:13.2184751Z 
2024-07-13T09:59:13.2185054Z java.base@21.0.3/java.lang.ProcessHandleImpl.waitForProcessExit0(Native Method)
2024-07-13T09:59:13.2185752Z java.base@21.0.3/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:163)
2024-07-13T09:59:13.2186535Z java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-07-13T09:59:13.2187393Z java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-07-13T09:59:13.2188063Z java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
2024-07-13T09:59:13.2188539Z java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
2024-07-13T09:59:13.2189153Z java.base@21.0.3/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
2024-07-13T09:59:13.2189570Z 
2024-07-13T09:59:13.2189580Z 
2024-07-13T09:59:13.2189845Z Thread[#9,Reference Handler,10,system]=[Ljava.lang.StackTraceElement;@7bd8b859
2024-07-13T09:59:13.2190232Z 
2024-07-13T09:59:13.2190236Z 
2024-07-13T09:59:13.2190559Z java.base@21.0.3/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
2024-07-13T09:59:13.2191323Z java.base@21.0.3/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
2024-07-13T09:59:13.2192055Z java.base@21.0.3/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
2024-07-13T09:59:13.2192461Z 
2024-07-13T09:59:13.2192465Z 
2024-07-13T09:59:13.2192736Z Thread[#18,Notification Thread,9,system]=[Ljava.lang.StackTraceElement;@674ef7b7
```

**Comment by gsmet** [comment]
Issue seems to be in this test:

```
2024-07-13T09:54:16.1006253Z 2024-07-13 09:54:16,085 INFO  [io.quarkus] (main) quarkus-rest-links-deployment 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.751s. Listening on: http://0.0.0.0:8081
2024-07-13T09:54:16.1010179Z 2024-07-13 09:54:16,091 INFO  [io.quarkus] (main) Profile prod activated. 
2024-07-13T09:54:16.1012119Z 2024-07-13 09:54:16,091 INFO  [io.quarkus] (main) Installed features: [cdi, rest, rest-jsonb, rest-links, smallrye-context-propagation, vertx]
```
that is a `QuarkusProdModeTest`.

**Review by gsmet — APPROVED** [review]
I don't think the problem has anything to do with this particular PR so let's merge.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/issues/41878 .

**Pull request merged**
