### PR TITLE
Validator for Config only

### LINKED ISSUE #24540: NullPointerException on custom consraint validator when injecting a config mapping at startup
### Describe the bug

I am unable to start quarkus when i try to inject a ConfigMapping into a Hibernate validator constraint.

getting a quite big exception;
```
2022-03-24 13:04:14,650 WARN  [io.qua.arc.impl] (Quarkus Main Thread) An error occurred during delivery of the @BeforeDestroyed(ApplicationScoped.class) event: javax.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.scheduler.runtime.SchedulerContext not initialized yet: io_quarkus_scheduler_runtime_SchedulerContext_97d170e1550eee4afc0af065b78cda302a97674c

...

Caused by: java.lang.NullPointerException: Cannot invoke "javax.validation.Validator.forExecutables()" because the return value of "io.smallrye.config.validator.BeanValidationConfigValidator.getValidator()" is null

```

### Expected behavior

I should be able to inject a config in a constraint validator

### Actual behavior

App crashes on start

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-validator-reproducer

Step to reproduce;
1- Start the app

### Output of `uname -a` or `ver`

Darwin Kernel Version 20.6.0

### Output of `java -version`

openjdk version "17.0.2"

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.5

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #24540

Ideally, we would want to at least configure the validator locale, but I don't have a way to retrieve the current Config in the Validator. I need to add that in SmallRye Config.

### CODE REVIEW

**Comment by gsmet** [comment]
@radcortez I think this approach has a lot of value and we should pursue it. I don't think we should customize the Validator as much as the application one. We can live with the defaults and see how it goes.

**Comment by gsmet** [comment]
@radcortez the CI failure must be related as it's the first time we see this one.

**Comment by radcortez** [comment]
Done.

**Review by gsmet — APPROVED** [review]
I will mark it for backport as I think it's an important fix even if the change is large.

**Pull request merged**
