### PR TITLE
HealthBuildItem - remove the useless configRootName property

### PR DESCRIPTION
**Pull request by mkouba**
- the property is not used by SmallRyeHealthProcessor
- keep the old version of constructor for backwards compatibility

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]

**Comment by jmartisk** [comment]
Good idea, I will do the same thing for metrics :D

**Comment by loicmathieu** [comment]
Just discover this one, this was asked by @emmanuelbernard to be able, some day, to provides easy configuration for extension health check via extension filtering.

Instead of doing:
```
quarkus.datasource.health.enabled=true
quarkus.kafka.health.enabled=true
quarkus.mongodb.health.enabled=true
```
You would be able to do
```
quarkus.health.extensions=datasource,kafka,mongodb
```

See this comment in the origintated PR: https://github.com/quarkusio/quarkus/pull/3671#discussion_r321347454

See also some comment on the issue for extension health checks: https://github.com/quarkusio/quarkus/issues/3107

**Comment by mkouba** [comment]
So -1 for _"add the configRootName for future usage"_. If it's not used it shouldn't be there. The current status was that most extensions passed some hard-coded values or feature names. Also the property had no javadoc to clarify what the value actually represents.

**Comment by loicmathieu** [comment]
@mkouba the intent was to represent the name of the extension, we named it configRoot as the name of the extension is sometimes linked to it's implementation like `quarkus-argoal` and not what it provides like `datasource` and the root of the configuration is usually the later: `quarkus.datasource`.

Now, this was a special request of @emmanuelbernard to add it now, unused, to be able to use it later. So better check with him that you can remove it. At the time I added it, I too say that if it's not used, better not included it, and he insist mainly because it's easiest to add it now that to refactor everything later ...

**Comment by emmanuelbernard** [comment]
The point was that extensions *had to* document this name so we could implement the property filtering in a second stage. So -1 x your -1. But we should improve the JavaDoc and intend indeed

**Comment by mkouba** [comment]
I'm sorry but I don't get this. If it's not used, then it should not be there. This way you force the extensions to provide meaningless string values. If you plan to add such feature there should be an issue describing the "second stage". And once it is in the extensions should follow the contract (that is missing ATM ;-).

**Comment by emmanuelbernard** [comment]
It's described in the clsoed issue Loic mentioned (at least explains the reasoning). Also closely related to https://github.com/quarkusio/quarkus/issues/5572 as a feature request

**Comment by mkouba** [comment]
Ok, so once we're going to implement #5572 we should add the property back with a solid contract defined ;-).

**Comment by jmartisk** [comment]
So now I'm a little confused whether we should go ahead with removing the same for metrics or not ;) (I have an unmerged PR for that). But since Health now did this, perhaps yes? Or are we going to back it out?

**Pull request merged**
