### PR TITLE
Update JBoss Threads to 3.0.0.Beta4

### LINKED ISSUE #2218: Native mode - ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread
java.lang.ClassCastException on app shutdown with websocket

Quarkus: 0.14.0
GraalVM: 1.0.0-rc-15
Application: https://github.com/burrsutter/quarkusfingerpaint ++ Quarkus version update

Error is not thrown each time, best way for me was to open 2 tabs with http://127.0.0.1:8080/ URL, do some drawing and shutdown the app. 

```
target/quarkusfingerpaint-1.0.0-runner
2019-04-25 13:49:37,655 INFO  [io.quarkus] (main) Quarkus 0.14.0 started in 0.007s. Listening on: http://[::]:8080
2019-04-25 13:49:37,658 INFO  [io.quarkus] (main) Installed features: [cdi, smallrye-health, undertow-websockets]
2019-04-25 13:49:41,349 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:42,220 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:43,652 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:45,539 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:47,636 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:50,749 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:52,635 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:53,196 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:56,252 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
^C2019-04-25 13:49:59,359 INFO  [org.acm.web.WebSocket] (main) onClose: 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:59,359 INFO  [org.acm.web.WebSocket] (main) onClose: 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:59,360 INFO  [io.quarkus] (main) Quarkus stopped in 0.001s
2019-04-25 13:49:59,360 ERROR [org.jbo.exe.uncaught] (executor-thread-1) Thread Thread[executor-thread-1,5,executor] threw an uncaught exception: java.lang.ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread
	at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:47)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #2218

### CODE REVIEW

**Comment by dmlloyd** [comment]
https://github.com/jbossas/jboss-threads/compare/3.0.0.Beta3..3.0.0.Beta4

**Comment by rsvoboda** [comment]
So the removal of substitutions is all we need atm ?

I expect it's sort of workaround for now.

**Comment by dmlloyd** [comment]
Yeah it should work with just the substitutions removed and falling back to `Unsafe`.

**Comment by dmlloyd** [comment]
I'm not sure where CI has gone.

**Comment by rsvoboda** [comment]
2 hours ago CI worked, I updated https://github.com/quarkusio/quarkus/pull/2449

**Comment by aloubyansky** [comment]
How can a CI be triggered for this one? Does it require David to push an update?

**Comment by gsmet** [comment]
@dmlloyd could you force push somehow? I didn't find any way to trigger a CI build.

**Comment by dmlloyd** [comment]
Force pushed, but I still see no CI...

**Comment by dmlloyd** [comment]
Oh there it is!

**Review by gsmet — APPROVED** [review]

**Pull request merged**
