### PR TITLE
Use Java 15 in CI instead of Java 14

### PR DESCRIPTION
**Pull request by geoand**
Let's see if out GH Action supports Java 15 now

### CODE REVIEW

**Comment by gsmet** [comment]
I checked yesterday and AdoptOpenJDK didn't have JDK 15 available but it looks like it is today!

**Comment by geoand** [comment]
> I checked yesterday and AdoptOpenJDK didn't have JDK 15 available but it looks like it is today!

Yup, same here :)

**Comment by geoand** [comment]
Taking out of draft as JDK 15 was downloaded on my fork

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
Should we change the badge as well, or should that be left to when 1.9 goes out?

**Comment by gsmet** [comment]
No, let's change the badge if CI is green without any changes.

**Comment by geoand** [comment]
Badge updated as well

**Comment by geoand** [comment]
JDK 15 build passed, so merging

**Pull request merged**
