### PR TITLE
Safer Annotations

### PR DESCRIPTION
**Pull request by FroMage**
This PR introduces the io.quarkus.safer:safer-annotations module which allows for fine-grained annotation constraints, as an independent-project. And starts making RESTEasy Reactive use it.

Don't hesitate to provide feedback on module/package names, or anything else.

### CODE REVIEW

**Comment by geoand** [comment]
🎉 

I was wondering what happened to this a few days ago :)

**Comment by FroMage** [comment]
Time. That's what happened to this. And dust a bit too…

**Comment by Ladicek** [comment]
Looks great! Just wondering if the API design doesn't prevent adding more features. For example, I'm not sure how I'd fit a constraint of "at most one parameter from given set of types" into this. (Hmm, perhaps `mutuallyExclusiveParameterTypes`, but that's a bit limited...)

Anyway. There's only one thing I don't like: the Quarkus namespace. Pretty sure noone outside of the Quarkus ecosystem will ever use this. Not sure if SmallRye would be much better, and it must start somewhere, so definitely not a blocking concern.

**Comment by geoand** [comment]
Good idea to use the Smallrye package name. 

That would of course mean it would need to live in Smallrye and be released there as opposed to being releasable with Quarkus

**Comment by FroMage** [comment]
@Ladicek Let's add constraints when we need them, instead of trying to invent them :)

As for the SR package, it'd need to be in smallrye, then, no? I figured adding it here would be easier and allow us to use it here once it's released, given it has zero dependency.

I think it might be possible to decouple the annotation and constraint with something like:

```java
@TargetAccessor
@AnnotationConstraintFor(MicroProfileAnnotationICannotTouch.class)
public @interface Placeholder {}
```

Or:

```java
@TargetAccessor
public class PlaceholderClass implements AnnotationConstraintFor<MicroProfileAnnotationICannotTouch> {}
```

This way we can tie annotations and their constraints from anywhere. But then we have to make the APT processor see them, and I don't know how.

**Comment by Ladicek** [comment]
The constraint for "only one parameter from given set of types" is something I would want in my current proposal for CDI Build Compatible Extension API. But who knows how that will look in the end, so no pressure :-)

**Comment by mkouba** [comment]
> I think it might be possible to decouple the annotation and constraint with something like:

I think that it's probably a must-have for any spec-driven technology we use, including CDI ;-).
> 
> ```java
> @TargetAccessor
> @AnnotationConstraintFor(MicroProfileAnnotationICannotTouch.class)
> public @interface Placeholder {}
> ```
> 
> Or:
> 
> ```java
> @TargetAccessor
> public class PlaceholderClass implements AnnotationConstraintFor<MicroProfileAnnotationICannotTouch> {}
> ```
> 
> This way we can tie annotations and their constraints from anywhere. But then we have to make the APT processor see them, and I don't know how.

We could also add a target member to each constraint annotation ane make them repeatable, something like `Class<?> target() default TargetAccessor.class;` so that one could define all constraints on a single class:

```java
@TargetMethod(
  target = AroundInvoke.class
  returnTypes = { void.class, Object.class }, 
  parameterTypes = { InvocationContext.class }
)
@TargetMethod(
  target = AroundConstruct.class
  returnTypes = { void.class, Object.class }, 
  parameterTypes = { InvocationContext.class }
)
class CdiConstraints {
}
```

**Comment by mkouba** [comment]
> The constraint for "only one parameter from given set of types" is something I would want in my current proposal for CDI Build Compatible Extension API. But who knows how that will look in the end, so no pressure :-)

@Ladicek @FroMage Maybe we could add an API for this later, e.g. something like `enum ReturnTypesCheck { ANY, ONE }` `ReturnTypesCheck returnTypesCheck() default ReturnTypesCheck.ANY`, and something similar for param type. Actually, it might make sense to specify the set of allowed exceptions as well...

**Comment by FroMage** [comment]
@mkouba be my guest and try to make it work. I ran into issues related to visibility when I tried anything fancy, because when using the recommended way to use APT for checks (see README):

```xml
<build>
    <plugins>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>${compiler-plugin.version}</version>
            <configuration>
                <annotationProcessorPaths>
                    <annotationProcessorPath>
                        <groupId>io.quarkus.safer</groupId>
                        <artifactId>safer-annotations</artifactId>
                        <version>${quarkus-plugin.version}</version>
                    </annotationProcessorPath>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
```

APT could not see a lot of things.

**Comment by mkouba** [comment]
> @mkouba be my guest and try to make it work. I ran into issues related to visibility when I tried anything fancy, because when using the recommended way to use APT for checks (see README):
> 
> APT could not see a lot of things.

Oh, that was just an idea ;-). I totally forgot about the visibility problems you mentioned earlier. And TBH my exp with APT is... frustrating.

**Comment by FroMage** [comment]
Well, IMO we have to find a way to make this use-case work, because we can't modify every annotation we care about, so it's definitely worth experimenting.

**Comment by FroMage** [comment]
No review?

**Comment by geoand** [comment]
I think the main point that needs to be clarified is whether or not this should live in Quarkus or separately in Smallrye

**Comment by FroMage** [comment]
My opinion is that it should start here because it's easiest, and we can release it and people can experiment and move it forward, and we can always move it to another location later, no?

**Comment by geoand** [comment]
That's fine with me

**Comment by Ladicek** [comment]
My opinion is that I don't care [much], and I don't really have a say in this, so please do whatever you wish :-) I remember I went through the code and wrote everything I had already, so it's kinda LGTM from me :-)

At the same time, I also don't like using `independent-projects` for possibly universally useful things, because they will forever be tied to Quarkus. Maybe that's not a big deal and I'm just overthinking it.

**Comment by FroMage** [comment]
OK, well, in that case we can also ask @kenfinnigan and @radcortez if they feel like it's worth adding it as a smallrye project? I really don't care either, as long as it's easy to do and doesn't require me begging for nexus authorisation and finding a new domain name.

**Review by Ladicek — APPROVED** [review]

**Comment by kenfinnigan** [comment]
I have no opinion

**Comment by radcortez** [comment]
I see us using this in our SR projects as well. If we find a way to add the constraints to MP annotations, then the SR implementations are the right place to add them. If we do that, then we probably want to have this as a independent project outside Quarkus.

@FroMage I'm fine if you want to move this to SR. No fancy setup is required. Just create a new repo, push the code, copy and modify as appropriate the `.githut` scripts and it should be fine. If you move forward, let me know and I'll help.

**Comment by FroMage** [comment]
OK fine, let's move it there.

**Comment by FroMage** [comment]
OK, @kenfinnigan @radcortez can you check that the GAV are fine before I make a release? https://github.com/smallrye/smallrye-safer-annotations

In theory it's `io.smallrye:smallrye-safer-annotations`

**Comment by radcortez** [comment]
In our recent projects we started to use an. additional name in the groupId. Not really required, but it may help to avoid collisions. What do you think?

**Comment by FroMage** [comment]
So, `io.smallrye.safer.annotations:smallrye-safer-annotations`? That seems overly long, no?

**Comment by radcortez** [comment]
Yes. Just leave it with.`io.smallrye` or `io.smallrye.annotations`?

**Comment by FroMage** [comment]
OK, this is almost ready for a release at https://github.com/smallrye/smallrye-safer-annotations/pull/2

**Comment by FroMage** [comment]
Rebased, using the latest release from `io.smallrye`, and checked the parameter/return types to adhere to the javadoc, and enabled in the `quarkus-resteasy-reactive-server-deployment` tests so we will know to update the annotation if we add support for a new parameter type.

**Comment by FroMage** [comment]
Ah wait, I will add a mention in the docs.

**Review by geoand — APPROVED** [review]

**Comment by FroMage** [comment]
Should compile now, let's see what CI has to say.

**Comment by FroMage** [comment]
OK it's in!

**Pull request merged**
