### PR TITLE
Do not create new instances in nested tests

### LINKED ISSUE #20114: @Nested JUnit test doesn't inherit lifecycle of @QuarkusTest
### Describe the bug

`@Nested` test of a test annotated with `@QuarkusTest` and `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` is run with a new instance of its outer test.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

1. Run the test below. It passes.
2. Annotate it with @QuarkusTest and run it again. The outer test passes, but the nested test fails.

```kotlin
// @QuarkusTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation::class)
class TestLifecycle {
 var s: String? = null

 @Test
 @Order(1)
 fun setString() {
  s = "foo"
 }

 @Test
 @Order(2)
 fun testString() {
  assertEquals("foo", s)
 }


 @Nested
 inner class NestedTest {
  @Test
  fun testString() {
   assertEquals("foo", s)
  }
 }
}
```

Edit: same test in Java, makes no difference.

```java
// @QuarkusTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class TestLifecycleJ {
 private String s;


 @Test
 @Order(1)
 public void setString() {
  s="foo";
 }


 @Test
 @Order(2)
 public void testString() {
  assertEquals("foo", s);
 }


 @Nested
 public class NestedTest {
  @Test
  public void testString() {
   assertEquals("foo", s);
  }
 }
}
```

### Output of `uname -a` or `ver`

Linux ***** 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08) OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

21.2.0

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

### Additional information

_No response_

### LINKED ISSUE #23947: QuarkusTest does not run @BeforeEach method of outer class when using @Nested test classes
### Describe the bug

Given the following test class:
```
import static org.junit.jupiter.api.Assertions.assertEquals;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

@QuarkusTest
public class DemonstratorTest {

    String outerValue;

    @BeforeEach
    void setUp() {
        outerValue = "outer";
    }

    @Nested
    public class NestedClass{

        String innerValue;

        @BeforeEach
        void setUp() {
            innerValue = "inner";
        }

        @Test
        void test() {
            assertEquals("inner", innerValue);
            assertEquals("outer", outerValue);
        }
    }
}
```

### Expected behavior

Both the outer and the inner `@BeforeEach` method are called before the test. Therefore the test succeeds.

### Actual behavior

The test fails because `outerValue` is actual `null`. If the `@QuarkusTest` annotation is removed from the outer class, the test succeeds as expected.

### How to Reproduce?

Run the test above.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8) OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

If the public modifier of the outer class is removed, the test does not run at all and the following stacktrace is produced:
```
java.lang.NoSuchMethodException: my.package.DemonstratorTest.<init>()

	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:987)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeEachMethod(QuarkusTestExtension.java:796)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	...
```

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/23947
Fix https://github.com/quarkusio/quarkus/issues/20114

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand I'll let you decide if this needs to be backported.

**Comment by geoand** [comment]
I'll need to look at this closer, because I think there is more to it than this...

**Comment by geoand** [comment]
@Sgitario can you explain this change please?

**Comment by Sgitario** [comment]
> @Sgitario can you explain this change please?

In [this line](https://github.com/quarkusio/quarkus/pull/24172/files#diff-462fa0cb443c21c9406c8b4daeb31500f20a4c9b46a0b039adcc93dee6a3bea4L995), a new instance of the outer class was being created to invoke the "before" methods (`beforeEach` for example). The right instance of the outer class was the one created at https://github.com/quarkusio/quarkus/blob/b08a00e636521f2bdb9f400431c618d5c6f216e2/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L766. 

Therefore, after using the right outer instance, when running the test, the instance will contain the data set at the `beforeEach` method.

**Comment by geoand** [comment]
Okay, thanks

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Actually, the title is not correct. We don't prefix the titles with the area the fix affects

**Comment by famod** [comment]
CI results looked very weird, so I rebased this to get a fresh run.

**Pull request merged**
