### PR TITLE
Bump Microsoft SQL Server JDBC driver to 11.2.3

### LINKED ISSUE #30584: Update MS SQL JDBC driver to version 11.2.3
### Description

MS has released a bugfix release for the MS SQL JDBC driver:https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.3

This should be included in Quarkus.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by sschu**
Fixes #30584

### CODE REVIEW

**Comment by sschu** [comment]
@Sanne Hmm, the native tests were aborted. The Java 11 tests reported:

Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
2023-01-25T11:42:26.6467198Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:119)
2023-01-25T11:42:26.6467867Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:28)
2023-01-25T11:42:26.6468561Z 	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17)
2023-01-25T11:42:26.6469163Z 	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39)
2023-01-25T11:42:26.6472569Z 	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1369)
2023-01-25T11:42:26.6473227Z 	... 18 more
2023-01-25T11:42:26.6474047Z Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://docker.elastic.co/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

Which is the only error I could find so I guess it is not related to my change.

**Comment by sschu** [comment]
Now I don't even find an error in the logs.

**Comment by gsmet** [comment]
Don't worry about the CI results. It looks good enough from what I can see. I will have a better look tomorrow.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Comment by sschu** [comment]
@gsmet Thank you! In the future I plan to watch to MS SQL driver closely and provide PRs once new versions are released. I can also provide backport PRs for patch releases if you think that makes sense.
Btw. 12.2.0 should be coming soon.

**Comment by gsmet** [comment]
@sschu we don't need backport PRs as long as there's no conflict with backporting (which I check when backporting in batch). I add the backport label and I backport by cherry-picking the commits.

In short: don't worry about backports :).

**Pull request merged**
