### PR TITLE
Do not auto-@Inject producer fields

### LINKED ISSUE #4002: Auto-@Inject fields break producer fields
Also if a producer field is annotated with `@Inject`, the container should detect the problem.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #4002
- also if a producer field is annotated with @Inject, the container
detects the problem

### CODE REVIEW

**Comment by mkouba** [comment]
@gsmet I believe that this one should be backported to 0.22.0.

**Comment by manovotn** [comment]
> @gsmet I believe that this one should be backported to 0.22.0.

+1 to that

**Review by manovotn — APPROVED** [review]
Good job nailing this SO exception down!

**Comment by geoand** [comment]
Arc tests seem to be failing

**Comment by manovotn** [comment]
It's import formatting error

**Pull request merged**
