### PR TITLE
Remove redpanda image name check

### LINKED ISSUE #23978: Kafka dev services can not be used with redpanda images from outside of DockerHub
### Describe the bug

Devmode for Kafka explicitly requires, that images should be from vectorized/redpanda dockerhub repository. Because of that, even if the very same is copied to other docker repository, it can be used.

The reproducer uses image `quay.io/quarkusqeteam/redpanda` which was copied with docker pull/push from DockerHub to quay.io

### Expected behavior

Kafka dev services should work with redpanda images from any repository

### Actual behavior

Error: `IllegalArgumentException: Only vectorized/redpanda images are supported`

### How to Reproduce?

1. `git clone -b reproducer/redpanda git@github.com:fedinskiy/quarkus-test-suite.git`
2. `cd super-size/many-extensions`
3. `mvn clean validate compile test package verify -Dall-modules -DexcludedGroups=fips-incompatible -Dit.test=DevModeManyExtensionsIT`

### Output of `uname -a` or `ver`

5.16.7-200.fc35.x86_64

### Output of `java -version`

 11.0.12, vendor: GraalVM Community

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.2.Final, 2.2.5.Final, 3bda8b29565261d2dc188f8feda6d027eb085d6f

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
Fixes #23978

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
The documentation might need to be updated.

**Comment by gsmet** [comment]
Is it backportable or not?

**Comment by cescoffier** [comment]
Technically it is, but reason we have lifted this is because we have now the support of 'bare' kafka. Is it in 2.7 already? @ozangunalp ?

**Comment by gastaldi** [comment]
Ah just saw @cescoffier's comment about the need to update the documentation. Mind providing a separate PR with that @ozangunalp ?

**Comment by ozangunalp** [comment]
@gsmet No need to backport, it is not in 2.7. @gastaldi my bad, I was late to respond, I'll make the doc changes in another PR.

**Pull request merged**
