### PR TITLE
Infinispan Client doesn't pick up the hotrod-client.properties file

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/QUARKUS-442

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks for this @wburns.

Is this one meant to be backported?

**Comment by rsvoboda** [comment]
There is https://issues.redhat.com/browse/QUARKUS-442, so I think it's intended for backport

**Comment by geoand** [comment]
So I assume we will need a new community 1.7.x release?

**Comment by rsvoboda** [comment]
Probably yes, I will send an email.

**Comment by rsvoboda** [comment]
Email sent, there were more items to dig into.

**Comment by wburns** [comment]
@geoand Yes, it would be great to backport this. Unfortunately, without this change we lose quite a bit of functionality and the change is as you can see very trivial.

**Comment by geoand** [comment]
Gotcha, thanks

**Pull request merged**
