### PR TITLE
Dev UI - ArC interceptors fails if AroundConstruct interceptor exists

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by gsmet** [comment]
@mkouba is it normal you added *and* removed the backport label? Just to be sure.

**Review by Ladicek — APPROVED** [review]
Nice typo :-)

**Comment by mkouba** [comment]
> @mkouba is it normal you added _and_ removed the backport label? Just to be sure.

@gsmet I realized that this feature (Dev UI interceptors) got added only in 2.2 ;-). I'm sorry for confusion...

**Comment by gsmet** [comment]
No problem, better safe than sorry :).

**Pull request merged**
