### PR TITLE
Do better cleanup of tests if the JVM is killed

### PR DESCRIPTION
**Pull request by stuartwdouglas**
We write out all the created files to a file, and if this
file is still present we know that the JVM was killed and
we clean up all listed entries. Note that this can still
give problems for classes that use QuarkusTestExtension,
as JUnit 5 does not let us hook in before classloading.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@FroMage I think you have been complaining at various times about test cleanup in Eclipse? I think this might help.

**Comment by FroMage** [comment]
OK lemme try

**Comment by gsmet** [comment]
@FroMage can you check if it's OK for you? If so let's merge it and be done with it.

**Comment by FroMage** [comment]
Finally ready to test.

**Comment by FroMage** [comment]
I confirm it fixes my issue, thanks a lot!

**Review by FroMage — APPROVED** [review]

**Pull request merged**
