### PR TITLE
Add Arango extension.

### PR DESCRIPTION
**Pull request by previousdeveloper**
This adds a new extension for the Arango Java Driver (see https://github.com/arangodb/arangodb-java-driver) .

The integration tests will run on the JVM with `mvn clean install -Dtest-arango -Ddocker` and natively with `mvn clean install -Dtest-arango -Ddocker -Dnative`, in both cases an installed and working Docker environment are required.

### CODE REVIEW

**Comment by previousdeveloper** [comment]
Can you check it? @gsmet

**Comment by gastaldi** [comment]
Hi @previousdeveloper thank you for your contribution! 

We are encouraging extension authors to create their own repositories for their extensions instead of creating a new sub-module in the Quarkus repo tree and then integrate the release into the ecosystem catalog which for now is https://github.com/quarkusio/quarkus-platform.

This is already done by some other extensions, like [Kogito](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-quarkus-extension) and [Camel](https://github.com/apache/camel-quarkus). 

We are still in the process of fully documenting that process, so keep an eye in https://github.com/quarkusio/quarkus/issues/8094. 

Feel free to ping us in our [ZulipChat](https://quarkusio.zulipchat.com/) if you have any questions, we'll be more than happy to assist you! :wink:

**Comment by previousdeveloper** [comment]
Hi @gastaldi thank you for answer. I will move to my repo.

**Comment by dcdh** [comment]
Hello,

I've created an arangodb extension. Here is the extension-proposal regarding it https://github.com/quarkusio/quarkus/issues/37406

**Pull request closed without merging**
