### PR TITLE
Introduce Reactive Routes Codestart (in java and kotlin)

### PR DESCRIPTION
**Pull request by enwooz**
Add a new code start for reactive route in java and kotlin 

Fix #20871 

We follow the quarkus guide and add routes like described in guide https://quarkus.io/guides/reactive-routes

### CODE REVIEW

**Review by loicmathieu — CHANGES_REQUESTED** [review]
When you first launch the test, you launched it with `-Dsnap` and it generates test snapshots.
Those snapshots must be committed for regression testing

**Review by ia3andy — CHANGES_REQUESTED** [review]

**Review by loicmathieu — COMMENTED** [review]
LGTM, can you squash your commit so you'll have only one ?

**Comment by enwooz** [comment]
> LGTM, can you squash your commit so you'll have only one ?
Done, I have squash and force pushed . Thx @loicmathieu @ia3andy @gsmet

**Review by loicmathieu — APPROVED** [review]
LGTM

**Review by ia3andy — CHANGES_REQUESTED** [review]
You need to update the test snapshots

**Pull request closed without merging**
