### PR TITLE
Upgrade to Mutiny 0.11.0

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
Do not merge until we hear back from @Sanne _et al._ regarding the Hibernete Reactive compatibility 😃

**Review by Sanne — APPROVED** [review]
Nice, and seems straight forward compatible for Hibernate Reactive.

**Comment by Sanne** [comment]
Looks like two Gradle integration tests failed. I'm not familiar about those - if someone could tell they are safe to ignore, we could merge this.

**Comment by jponge** [comment]
Similar Gradle issues have been reported /cc @ia3andy

**Comment by Sanne** [comment]
Right, just noticed https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/CI.20Gradle.20issue . Let's merge this one :)

**Comment by Sanne** [comment]
@jponge I'm not sure if you'd want this applied to backported to the about-to-be-released 1.10 ..  Up to you if you'd like it to be taken in consideration, add the "backport?" label ?  If it's a low risk, bugfix thing..

**Comment by jponge** [comment]
@Sanne That'd be good to backport indeed. Note that I don't have  permissions to add a label.

**Comment by Sanne** [comment]
> @Sanne That'd be good to backport indeed. Note that I don't have permissions to add a label.

ah, we should fix that!

**Comment by jponge** [comment]
Invite me to the team folks 😉

**Pull request merged**
