### PR TITLE
Fix dependency issues causing build problems

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by FroMage — APPROVED** [review]

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
I will merge it as soon as one of the JVM build is green.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
LGTM, waiting for ci

**Comment by jaikiran** [comment]
I am not too familiar with the Maven side of things, but does this also indicate that there might be some other issue in this area which made this issue show up itermittently? I remember seeing this issue (just once) in https://github.com/quarkusio/quarkus/pull/10769, but when that PR was merged all jobs had passed.

**Comment by gsmet** [comment]
I have no idea how the build passed because it's consistently failing since it has been merged and it's expected to fail given the dependency we had.

**Pull request merged**
