### PR TITLE
specify value for PathParam

### PR DESCRIPTION
**Pull request by darinpope**
when I was going through the getting-started (again), I wasn’t able to compile with Java 11 until I added a value to @PathParam. This PR covers all the occurences found where @PathParam did not have a value specified.

Signed-off-by: Darin Pope <darin@planetpope.com>

### CODE REVIEW

**Comment by gastaldi** [comment]
I guess the `maven.compiler.parameters` property in the pom.xml isn't being set to `true`?

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by darinpope** [comment]
> I guess the `maven.compiler.parameters` property in the pom.xml isn't being set to `true`?

I followed step 4 on https://quarkus.io/guides/getting-started#bootstrapping-the-project. I confirmed in the `pom.xml` that `maven.compiler.parameters` is set to true.

If you would prefer to not merge, I'll dig more and figure out if it's environmental.

**Comment by gastaldi** [comment]
Weird, it should have worked then. Maybe I am missing something, but your PR looks fine to me, let's see what the team thinks about merging it 👍

**Review by gsmet — CHANGES_REQUESTED** [review]
I don't think we want that.

It should work if you compile with `-parameters` which is enabled if you generated a project and if you import the RESTEasy version of `@PathParam`. We usually put the imports in the source code.

**Comment by darinpope** [comment]
🤦  I had the wrong import. When I changed to the RESTEasy version, it worked as expected. I didn't fully copy/paste the example and I had missed that. I'll retract.

**Pull request closed without merging**
