### PR TITLE
Allow injection of BeanManager into tests

### LINKED ISSUE #2368: @Inject BeanManager in @QuarkusTest annotated class does not work
Hi @mkouba,

This is in regards to the issue we discussed on Zulip.

I cannot `@Inject` `BeanManager` into a `@QuarkusTest` annotated class. When I have a test class like this one:

```java
@QuarkusTest
public class EventsBypassTest {

    @Inject
    BeanManager bm;

    // ...
}
```

It fails with the following error:

```plain
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 s <<< FAILURE! - in com.github.sarxos.abberwoult.EventsBypassTest
[ERROR] test_startupEventReceived  Time elapsed: 0.007 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [com.github.sarxos.abberwoult.EventsBypassTest]: Failed to inject field javax.enterprise.inject.spi.BeanManager com.github.sarxos.abberwoult.EventsBypassTest.bm
Caused by: java.lang.RuntimeException: Failed to inject field javax.enterprise.inject.spi.BeanManager com.github.sarxos.abberwoult.EventsBypassTest.bm
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException
```

In the same time I can get BeanManager from CDI (and this is what I did as a workaround to the problem):

```java
@Test
public void test_eventsReceived() throws InterruptedException {
    final BeanManager bm = CDI.current().getBeanManager();
    // ... use bean manager here
}
```

This happens on Quarkus `0.14.0`.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #2368

@mkouba I just stumbled upon the issue and thought that this quick fix would take care of it, but perhaps I am missing something.

### CODE REVIEW

**Comment by mkouba** [comment]
Well, your solution would surely work but I was thinking of a more general solution so that it would be possible to inject `Instance`, `Event` and other built-in beans.

**Comment by geoand** [comment]
Then that is the piece I was missing :). I will leave it up to you if you want to merge this now and deal with the other later if needed.

**Comment by geoand** [comment]
@mkouba should we merge this or should I close the PR do you think?

**Review by mkouba — APPROVED** [review]
Let's merge this for now. I've created a follow-up issue: https://github.com/quarkusio/quarkus/issues/2459.

**Pull request merged**
