### PR TITLE
Fix MySQL high availability not working in native mode

### LINKED ISSUE #7936: [jdbc-mysql extension] MySQL high availability datasource health check not supported in native Quarkus
I am using the jdbc-mysql Quarkus extension for connecting my Quarkus application to a MySQL cluster. My datatsource URL is like:

    jdbc:mysql:replication://host/db

As you can see, I am using the _Connector/J_ feature ```replication``` as described on https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-master-slave-replication-connection.html

While this works fine running Quarkus running in JVM, a Quarkus native fails to do the datasource health check.

When running my Quarkus application as a native, the health endpoint returns:

```bash
$ curl localhost:8080/health
{   
    "status": "DOWN",
    "checks": [
        {   
            "name": "Database connections health check",
            "status": "DOWN",
            "data": {
                "default": "Unable to execute the validation check for the default DataSource: !InvalidLoadBalanceExceptionChecker!"
            }
        }
    ]
}
```

The corresponding exception is
```bash
2020-03-18 13:31:17,255 WARN  [io.agr.pool] {} Datasource '<default>': !InvalidLoadBalanceExceptionChecker!
2020-03-18 13:31:17,255 DEBUG [io.agr.pool] {} Cause: : java.sql.SQLException: !InvalidLoadBalanceExceptionChecker!
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
        at com.mysql.cj.jdbc.ha.LoadBalancedConnectionProxy.<init>(LoadBalancedConnectionProxy.java:244)
        at com.mysql.cj.jdbc.ha.LoadBalancedConnectionProxy.createProxyInstance(LoadBalancedConnectionProxy.java:120)
        at com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.initializeSlavesConnection(ReplicationConnectionProxy.java:448)
        at com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.<init>(ReplicationConnectionProxy.java:168)
        at com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.createProxyInstance(ReplicationConnectionProxy.java:88)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:209)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:390)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:372)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.mysql.cj.exceptions.WrongArgumentException: !InvalidLoadBalanceExceptionChecker!
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at com.mysql.cj.util.Util.getInstance(Util.java:169)
        at com.mysql.cj.jdbc.ha.LoadBalancedConnectionProxy.<init>(LoadBalancedConnectionProxy.java:239)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.ha.StandardLoadBalanceExceptionChecker
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1211)
        at com.mysql.cj.util.Util.getInstance(Util.java:167)
        ... 16 more
```

Adding ```com.mysql.cj.jdbc.ha.StandardLoadBalanceExceptionChecker``` to the [reflection-config.json](https://quarkus.io/guides/writing-native-applications-tips#using-a-configuration-file) seems to be only the tip of the iceberg, doing so results in exceptions of kind
```
2020-03-18 13:18:02,839 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] {} HTTP Request to /health failed, error id: 8865e180-03db-4b52-b335-efa4e0f8223b-1: com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface com.mysql.cj.jdbc.ha.LoadBalancedConnection, interface com.mysql.cj.jdbc.JdbcConnection] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
        at com.oracle.svm.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:113)
        at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:66)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
        at com.mysql.cj.jdbc.ha.LoadBalancedConnectionProxy.createProxyInstance(LoadBalancedConnectionProxy.java:121)
        at com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.initializeSlavesConnection(ReplicationConnectionProxy.java:448)
        at com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.<init>(ReplicationConnectionProxy.java:168)
        at com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.createProxyInstance(ReplicationConnectionProxy.java:88)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:209)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:390)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:372)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
```

**Workaround**
Removing ```replication``` from the datasource URL "solves" the issue.

**Environment**
- Java: v11
- Quarkus: 1.3.0.Final
- Build tool: Gradle

### PR DESCRIPTION
**Pull request by machi1990**
Fixes https://github.com/quarkusio/quarkus/issues/7936

I was able to reproduce the error and adding the missing proxy registration fixed it.

To test the fix, using the below mysql replication setup:

```
docker run \
--name mysql_primary \
 -p 3306:3306 \
 -e MYSQL_ROOT_PASSWORD=hibernate_orm_test \
 -e MYSQL_USER=hibernate_orm_test \
 -e MYSQL_PASSWORD=hibernate_orm_test \
 -e MYSQL_DATABASE=hibernate_orm_test \
 -e REPLICATION_USER=hibernate_orm_test \
 -e REPLICATION_PASSWORD=hibernate_orm_test \
 actency/docker-mysql-replication:5.7
```

And on another terminal tab, run the following command:

```
 docker run \
 --name mysql_secondary \
  -p 3307:3306 \
 -e MYSQL_ROOT_PASSWORD=hibernate_orm_test \
 -e MYSQL_USER=hibernate_orm_test \
 -e MYSQL_PASSWORD=hibernate_orm_test \
 -e MYSQL_DATABASE=hibernate_orm_test \
 -e REPLICATION_USER=hibernate_orm_test \
 -e REPLICATION_PASSWORD=hibernate_orm_test \
 --link mysql_primary:master \
 actency/docker-mysql-replication:5.7
```

Open another terminal tab and launch jdbc-mysql integration tests with the following command
`cd integration-tests/jpa-mysql` and then open the configuration file and edit the jdbc url so that it points to: 
```
jdbc:mysql:replication://localhost:3306,localhost:3307/hibernate_orm_test?connectTimeout=5000&socketTimeout=5000&retriesAllDown=3&allowMasterDownConnections=true&allowSlaveDownConnections=true&loadBalanceBlacklistTimeout=10000&readFromMasterWhenNoSlaves=true`
```

Then running
```
mvn clean install -Dnative -Dtest-mysql
```

Should pass successfully which was not the case previously as it was throwing missing proxy registration errors.

@SchulteMarkus can you check if this fixes the error for you? 

PS: The first commit adds connection clean up in native mode. Let me know what you think about it?

/cc @Sanne @geoand @gsmet

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
Not my wheelhouse, so I'll leave the review to others who know much about the topic

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks. Nice work!

**Comment by machi1990** [comment]
Great thanks.

**Comment by gsmet** [comment]
I backported the second commit.

**Comment by machi1990** [comment]
Thanks @gsmet

**Comment by SchulteMarkus** [comment]
Solves my problem.

**Comment by gsmet** [comment]
Thanks for confirming!

**Comment by machi1990** [comment]
> Solves my problem.

@SchulteMarkus , thanks for testing and confirming.

**Comment by shahmalhar** [comment]
I can't find this fix in 1.5.0.Final, can someone help?

**Pull request merged**
