### PR TITLE
Log the time each BeanContainerListener takes

### PR DESCRIPTION
**Pull request by mkouba**
- to debug perf problems during startup

### CODE REVIEW

**Review by geoand — APPROVED** [review]
I assume you tested it and logging is available at that point in time :)

**Comment by mkouba** [comment]
> I assume you tested it and logging is available at that point in time :)

Hm, I did test it with a quickstart app and it seems to work just fine but I'm hopefully it does not break anything...

@dmlloyd Is it OK to use a `Logger` in a STATIC_INIT recorder? I went through our docs and found no mention of any similar restriction.

**Comment by dmlloyd** [comment]
As long as you're not using the logger directly from the recorder, it should be OK.  Unrelatedly, you should also get in the habit of always using `System.nanoTime` when measuring durations, just as a matter of best practice.

**Comment by mkouba** [comment]
> As long as you're not using the logger directly from the recorder build step method, it should be OK. 

I suppose you mean directly from a `@BuildStep` method?

> Unrelatedly, you should also get in the habit of always using `System.nanoTime` when measuring durations, just as a matter of best practice.

That's a good point. Although in this particular case we aim to detect problematic listeners with times around hundreds of millis.

**Pull request merged**
