### PR TITLE
Change version to 2.16.999-SNAPSHOT in 2.16 branch

### PR DESCRIPTION
**Pull request by gsmet**
I will do the same for 2.7 and 2.13, once I'm sure it passes.

### CODE REVIEW

**Comment by radtriste** [comment]
@gsmet Is that a new standard for setting the version on branches ?

**Comment by gsmet** [comment]
@radtriste tbh I'm not sure yet. It causes issues with the RESTEasy Reactive test suite which will require a branch per Quarkus branch and I'm not sure we want this overhead.

**Comment by gsmet** [comment]
Feedback is welcome if you have some.

**Comment by radtriste** [comment]
well it does not change much on our side. We set the needed version directly in our jobs.
Just need to know the convention :)

**Pull request merged**
