### PR TITLE
[3.15] 3.15.2 backports 1

### PR DESCRIPTION
**Pull request by gsmet**
Please don't merge, I will merge it myself.

@gastaldi @rsvoboda @aloubyansky here is the first round following the meeting we had next week.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gtroitsk** [comment]
@gsmet can you please backport https://github.com/quarkusio/quarkus/pull/43884 also?

**Review by aloubyansky — APPROVED** [review]

**Comment by rsvoboda** [comment]
> @gsmet can you please backport https://github.com/quarkusio/quarkus/pull/43884 also?

There will be another round of backports @gtroitsk. I expect that backport can wait for round 2. Please let us know if there is something pressing.

**Review by rsvoboda — APPROVED** [review]

**Comment by gtroitsk** [comment]
> > @gsmet can you please backport #43884 also?
> 
> There will be another round of backports @gtroitsk. I expect that backport can wait for round 2. Please let us know if there is something pressing.

Sure, this way no pressing atm

**Comment by rsvoboda** [comment]
CI is green 🎉

**Comment by rsvoboda** [comment]
@gsmet I think this could be merged, it has some docs fixes that could be used downstream.

**Comment by MichalMaler** [comment]
> @gsmet I think this could be merged, it has some docs fixes that could be used downstream.

@rsvoboda 
The fixes we need are 
- https://github.com/quarkusio/quarkus/pull/43884 [Tweaking the Datasource guide content conditionals]
- https://github.com/quarkusio/quarkus/pull/44070 [Unwrap tooltips in the downstream configuration reference docs - by @jmartisk ] - Will be merged to main tomorrow, Oct 30.

**Pull request merged**
