### PR TITLE
Upgrade to GraalVM 20.3.1

### PR DESCRIPTION
**Pull request by gsmet**
Want to upgrade to 20.3.1 first as we will probably backport it to 1.11.

Creating as draft for now to see how it goes in my fork.

### CODE REVIEW

**Comment by zakkak** [comment]
Hi @gsmet I have prepared a similar branch (https://github.com/zakkak/quarkus/tree/graal-20.3.1-update)

In which in addition to what you reverted, I also revert https://github.com/quarkusio/quarkus/commit/9e0a94ebf07021a1d95050a369c8af340d153dcf and https://github.com/quarkusio/quarkus/commit/af31023b4a76ce6e5b14e3db97b6b679febf0ac8.

Note: I would prefer the changes that revert commits to be explicit reverts (see https://github.com/zakkak/quarkus/commits/graal-20.3.1-update) since that makes it easier to track and understand the changes in the future.

**Comment by gsmet** [comment]
I don't mind if you prefer your branch but you need to put the commits the other way around: first the upgrade, then revert the unnecessary things we added for 20.3.0.

I can close this one if we go with your PR.

**Comment by zakkak** [comment]
OK let me do the change and open another draft PR then.

**Pull request closed without merging**
