### PR TITLE
Bump 2.16 branch to OTel 1.23 and SR reactive messaging 3.24

### PR DESCRIPTION
**Pull request by brunobat**

### CODE REVIEW

**Comment by gsmet** [comment]
What's the rationale for backporting this bump?

**Comment by brunobat** [comment]
It was asked by a user, but @ozangunalp has more details.

**Comment by ozangunalp** [comment]
I can't find the discussion right now. The reactive messaging 3.24.0 also includes the fix for https://github.com/quarkusio/quarkus/issues/31003.

**Comment by gsmet** [comment]
OK, makes sense then if not too risky. Thanks for the clarification.

**Comment by ozangunalp** [comment]
Test failures seem to be related. I am looking at it.

**Comment by ozangunalp** [comment]
The Kafka record offset Otel attribute changed in the previous Reactive Messaging release. 
I also backported that commit.

**Review by ozangunalp — APPROVED** [review]

**Comment by gsmet** [comment]
I had a look at all the tests you had to adjust and this PR actually worries me a lot. Is it really safe to backport that to 2.16?

**Comment by radcortez** [comment]
Yes, I agree that these changes should not be expected in a patch release.

Even with the span name change, it would look weird to start seeing different span names in your tools. We could override their span name creator to keep the old behavior for this version. On the other hand, it would also look weird because this OTel version changes the name, and we are changing it again :)

Can we clarify what the user needs to ask for the backport?

**Comment by brunobat** [comment]
This started on a SM Reactive messaging backport request. Because OTel 1.23 is a dependency, it requires Otel backport due the mentioned changes, this was created. 
If @ozangunalp is happy not to backport we can scrap this.

**Comment by ozangunalp** [comment]
I agree with the stability argument. No problem for me to scrap this PR. 
In any case, I can't find the original user request.

**Comment by brunobat** [comment]
Dropping it.

**Pull request closed without merging**
