### PR TITLE
Fix `@EngineConfiguration` sample in Qute Reference documentation

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Comment by gastaldi** [comment]
The example also fails with: 
```
java.lang.NullPointerException: Cannot invoke "io.quarkus.qute.ExpressionNode.hasEngineResultMappers()" because "expressionNode" is null
	at io.quarkus.qute.SingleResultNode.<init>(SingleResultNode.java:16)
```

**Comment by mkouba** [comment]
> The example also fails with:
> 
> ```
> java.lang.NullPointerException: Cannot invoke "io.quarkus.qute.ExpressionNode.hasEngineResultMappers()" because "expressionNode" is null
> 	at io.quarkus.qute.SingleResultNode.<init>(SingleResultNode.java:16)
> ```

That should not happen - there is the [CustomSectionHelperTest](https://github.com/quarkusio/quarkus/blob/main/extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/engineconfigurations/section/CustomSectionHelperTest.java). Could you verify the test pls?

**Comment by gastaldi** [comment]
I am testing with 2.16.0.Final and 2.16.1.Final. It looks like it was fixed in https://github.com/quarkusio/quarkus/commit/cedab81491bec24f37601eab52df44066d8798ff#diff-50cb6077e5b913bf85917e76b89290d8e0efe53e505f8d12308ca654b771b418R16 but it's planned for 2.17

**Comment by mkouba** [comment]
> I am testing with 2.16.0.Final and 2.16.1.Final. It looks like it was fixed in [cedab81#diff-50cb6077e5b913bf85917e76b89290d8e0efe53e505f8d12308ca654b771b418R16](https://github.com/quarkusio/quarkus/commit/cedab81491bec24f37601eab52df44066d8798ff#diff-50cb6077e5b913bf85917e76b89290d8e0efe53e505f8d12308ca654b771b418R16) but it's planned for 2.17

Yep, it won't work in 2.16...

**Comment by gastaldi** [comment]
Actually since `io.quarkus.qute.ExpressionNode` is a protected class, maybe that constructor should be package-protected as well?

**Comment by gastaldi** [comment]
@mkouba I also added support for `OptionalInt`,`OptionalDouble` and `OptionalLong`

**Review by mkouba — APPROVED** [review]

**Pull request merged**
