### PR TITLE
Document corellation between provided and generated k8s resources

### LINKED ISSUE #22975: Document the customization  of the minikube.yml and openshift.yaml
### Describe the bug

With the target=kubernetes, if we put a kubernetes.yml inside src/main/kubernetes , in the generation process this contents will be added to the kubernetes.yml inside target/kubernetes along with the auto generated resources.

In the documentation is not said that the file to customize this for minikube needs to be minikube.yml, and the same for openshift that needs to be openshift.yml
https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources

### Expected behavior

Documentation says that for each extension the configuration file is the name of the extension

### Actual behavior

It only mentions the kubernetes extension case

### How to Reproduce?

Add a src/main/kubernetes/kubernetes.yml and set quarkus.kubernetes.target=minikube and check that the content of that src file is not in the target/kubernetes/minikube.yml

### Output of `uname -a` or `ver`

Linux localhost-live.home 5.15.14-200.fc35.x86_64 #1 SMP Tue Jan 11 16:49:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #22975

### CODE REVIEW

**Comment by iocanel** [comment]
cc @jonathanvila

**Comment by geoand** [comment]
What is `byon`?

**Comment by jonathanvila** [comment]
Thank you @iocanel :+1:

**Comment by gsmet** [comment]
@iocanel can you take into account the bot's feedback for your PR titles? It's important for our release notes. Thanks.

**Comment by iocanel** [comment]
> @iocanel can you take into account the bot's feedback for your PR titles? It's important for our release notes. Thanks.

Sorry about that. I keep on forgetting it.

**Comment by iocanel** [comment]
> What is `byon`?

B.Y.O is an acronym for `bring your own`. In our case it should be `byor` for bring your own resources.

**Comment by geoand** [comment]
2005 is calling! 

https://www.youtube.com/watch?v=zUzd9KyIDrM

**Review by geoand — APPROVED** [review]

**Pull request merged**
