### PR TITLE
DO NOT MERGE: Attempt to use Google's mirror of central for CI

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Both JBoss Nexus and the main Central repo's seem to have
intermittent problems. This attempts to use Google's mirror
to see if it improves things at all.

This is just an experiment, do not merge for now.

### CODE REVIEW

**Comment by Sanne** [comment]
Good idea, but wondering: doesn't Azure have its own mirror?

I've used AWS myself before; AWS has their own mirrors of Maven central, which are highly recommended as not only they are faster but internal transfers are cheaper. (I don't know about Azure though)

**Comment by stuartwdouglas** [comment]
Not that I can see. They have a thing called Azure Artifacts but it appears to mostly be about publishing your own artifacts.

**Comment by gsmet** [comment]
I don't know if it's just a temporary artifact but the first 2 builds (JDK 11 and Windows) were really slower than usual. From what I can see, we are usually more in the ~20-25 minutes ballpark. Here it took 35-38 minutes.

**Comment by stuartwdouglas** [comment]
It's probably related

**Pull request closed without merging**
