### PR TITLE
Update Using JWT RBAC to use RequestScoped endpoints and add default scoped test

### PR DESCRIPTION
**Pull request by starksm64**
Related to #1710 I have updated the Using JWT RBAC guide to explicitly declare @RequestScope scoping on the endpoints and add a statement about this as necessary for the expected behavior of JWT injected values.

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]
Could you please squash the reformatting commits? We should really try to have atomic commits.

**Comment by gsmet** [comment]
@mkouba @stuartwdouglas I think this raises an important issue: people migrating apps could end up with a massive security issue. Wondering if we should reconsider the default choice.

If possible, I think we should at least raise a warning or an error if methods are secured on a singleton scoped bean. @starksm64 is the set of annotations we should consider finite?

**Comment by starksm64** [comment]
Yes, the annotations in use are:

```java
import javax.annotation.security.DenyAll;
import javax.annotation.security.PermitAll;
import javax.annotation.security.RolesAllowed;
import org.eclipse.microprofile.jwt.Claim;
```

**Comment by mkouba** [comment]
@starksm64 @gsmet So if I understand it correctly the problem is that JWT produces some `@Dependent` beans that are injected into `@Singleton` resources. If those JWT beans were `@RequestScoped` everything should work fine because the injected client proxies would delegate to the correct instances. But I understand that sometimes it's not always possible to fulfill all CDI proxyability requirements.

**Comment by starksm64** [comment]
@mkouba yes, that is correct.

**Comment by mkouba** [comment]
Hm, in that case it would a problem for any non-default JAX-RS resource lifecycle strategy. Would it make sense to change JWT to produce `@RequestScoped` beans instead?

**Comment by starksm64** [comment]
There was some usecase we were wanting to support in the MP-JWT spec that required dependent scoping, so I have to revisit that to remember exactly why this was chosen. We did discuss looking into adding an option to configure the smallrye-jwt extension to produce request scoped beans. Would that require having two sets of producers and only register the ones with the requested scoping in the extension processor?

**Comment by mkouba** [comment]
> Would that require having two sets of producers and only register the ones with the requested scoping in the extension processor?

It seems like we have our own producers in quarkus: https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-jwt/runtime/src/main/java/io/quarkus/smallrye/jwt/runtime/JsonValueProducer.java#L28

Anyway, we could also register a custom annotation transformer to replace/add the scope annotation to a producer method.

**Comment by starksm64** [comment]
> Anyway, we could also register a custom annotation transformer to replace/add the scope annotation to a producer method.

The producers were replicated because the smallrye versions required some portable extension magic to work. Is there an example of that type of annotation processor already in the codebase?

**Comment by mkouba** [comment]
> The producers were replicated...

In that case we don't need a transformer at all? Just add `@RequestScoped` to the producet methods?

> Is there an example of that type of annotation processor already in the codebase?

Yes, for example: https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java#L201-L223

spring-di, vertx-web and scheduler extensions are also using this API.

**Comment by gsmet** [comment]
I'm not sure what to do about this one. @starksm64 could you take a look at what @mkouba suggested?

If we can't do better by tomorrow, I'll merge this one anyway as it's still better than the current situation. We would then iterate on it for the next release.

**Comment by starksm64** [comment]
We won't be able to do anything in terms of implementing alternative producer request scoped values so let's just document the issue an change the defaults on the quickstart endpoints for this release. For the next release I will come up with a solution.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
OK, let's merge then. Thanks.

**Pull request merged**
