### PR TITLE
Update tools provided Dockerfiles to use RHEL 8.5

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Comment by paulrobinson** [comment]
This looks right to me, but I don't know how to test it, or if there's anything else that needs changing to support this.

**Comment by aloubyansky** [comment]
To test it, a branch including the change would have to be built locally and a sample project would have to be generated, e.g., with a quarkus-maven-plugin. For example:
````
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DquarkusRegistryClient=false
````
The generated docker files will be located under `src/main/docker`. Then a docker image would have to be built for the application.

**Comment by paulrobinson** [comment]
I'm having trouble building Quarkus locally, which is making this hard to try. This is the problem I have: https://github.com/quarkusio/quarkus/discussions/22802

**Comment by paulrobinson** [comment]
I've got the sample project building now, and "ubi-minimal:8.5" is being stated in the various Dockerfiles.

I'll build the sample application next and run it from the containers.

**Comment by aloubyansky** [comment]
@paulrobinson I pushed more changes to fix the CI, could you please review those too? Thanks.

**Review by gsmet — APPROVED** [review]

**Comment by paulrobinson** [comment]
I've now tested the produced Dockerfile.jvm, Dockerfile.legacy-jar & Dockerfile.native. They all seem to work for me.

**Comment by paulrobinson** [comment]
@gsmet I notice that this PR is missing a milestone. Is that because it was raised directly on the https://github.com/quarkusio/quarkus/tree/2.2 branch?

I can see from it being merged to the 2.2 branch, that it should be in the 2.2.5.Final release. However, it's confusing my reporting script that looks for issues that might have missed the required release.

**Comment by paulrobinson** [comment]
Aha, I get it now. It's merged to the 2.2 branch, but after 2.2.5.Final was released. So, it's yet to be in a release, and thus has no milestone set. Is that right?

**Pull request merged**
