### PR TITLE
Support config reactive datasource with list of database urls for fault tolerance and load balance

### LINKED ISSUE #31492: Loadbalance for reactive mysql client
### Description

There is built-in loadbalance support from MySQL Connector/J driver, so we can write `quarkus.datasource.jdbc.url=jdbc:mysql:loadbalance://192.168.32.101,192.168.32.102/dbname` in application.properties to take the advantage of load balance.

For reactive mysql client similar config not work because vert.x mysql client not support the `loadbalance` keyword within url. But vert.x do support server load balance. https://vertx.io/docs/vertx-mysql-client/java/#_advanced_pool_configuration

Do we have any plan to support config like this? `quarkus.datasource.reactive.url=mysql:loadbalance://192.168.32.101,192.168.32.102/dbname`

### Implementation ideas

update io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder, change `MySQLPool.pool(Vertx vertx, MySQLConnectOptions database, PoolOptions options)` to `MySQLPool.pool(Vertx vertx, List<MySQLConnectOptions> databases, PoolOptions options)` if keyword `loadbalance` present in the url

### PR DESCRIPTION
**Pull request by benstonezhang**
Add support to config load balance urls for reactive datasources in application.properties, for example:
```
quarkus.datasource.reactive.url=mysql://host1:3306/dbname,mysql://host2:3306/dbname,mysql://host3:3306/dbname
```
or
```
quarkus.datasource.reactive.url[0]=mysql://host1:3306/dbname
quarkus.datasource.reactive.url[1]=mysql://host2:3306/dbname
quarkus.datasource.reactive.url[2]=mysql://host3:3306/dbname
```
The original PR is https://github.com/quarkusio/quarkus/pull/31852, which only update reactive mysql client. As @tsegismont suggested, I replaced public Optional<String> url with public Optional<List<String>> urls in DataSourceReactiveRuntimeConfig, and all of reactive database client were updated accordingly.

There is one exception: Vert.x oracle client already have build-in load balance support, and there is no such function like OraclePool.pool(Vertx vertx, List<OracleConnectOptions> databases, PoolOptions options). So only the first url is valid and others is discarded even if you config more urls.

The original PR title maybe improperly and misleading, so I create this one.

### CODE REVIEW

**Review by tsegismont — APPROVED** [review]
LGTM, thank you @benstonezhang

**Review by tsegismont — APPROVED** [review]

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Can you please squash the commits into a single one before we merge this? Thanks!

**Comment by benstonezhang** [comment]
@gastaldi Could you tell me how to do this? Thanks.

**Comment by gastaldi** [comment]
1) Run `git rebase -i HEAD~2` your branch and add a `F` to the `update reactive-sql-clients.adoc` line. Save the file
2) `git rebase main`
3) `git log` and check that everything is okay (just one commit after the last one in your main)
3) `git push -f` to your remote branch

**Comment by tsegismont** [comment]
> @tsegismont updated `reactive-sql-clients.adoc` with a new revision.

Thank you. Just a title change suggestion. Otherwise, LGTM

**Comment by benstonezhang** [comment]
@tsegismont updated.
@gastaldi PR commits updated.

**Pull request merged**
