### PR TITLE
Bump dekorate version to 0.11.4

### LINKED ISSUE #8091: quarkus.kubernetes.image-pull-policy ignored
I put this in `application.properties`

`quarkus.kubernetes.image-pull-policy=Always`

After performing:

```
mvn clean package
```

and in `target/kubernetes/kubernetes.yaml`

I have this : 

```
image: "docker.example.com:5000/iep/quarkus-k8s-hello:latest"
imagePullPolicy: "IfNotPresent"
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: "/health/live"
    port: 8080
    scheme: "HTTP"
  initialDelaySeconds: 0
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
name: "quarkus-k8s-hello"
```

### LINKED ISSUE #8093: Generating a fieldRef env var with the Kubernetes Extension is not working
**Describe the bug**
In my properties I put : 
```
kubernetes.env-vars[0].name=GREETING_MYADRESS
kubernetes.env-vars[0].field=metadata.name
```

This should generate : 

```
- name: "GREETING_MYADRESS"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
```

But nothing is generated in `target/kubernetes/kubernetes.yaml`
**Expected behavior**
in  `target/kubernetes/kubernetes.yaml`
```
- name: "GREETING_MYADRESS"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
```

**Actual behavior**
It's not generated in the yaml file

**To Reproduce**
1. add properties as mentioned in the beginning of the report 
2. `mvn clean package`
3. inspect the content of  `target/kubernetes/kubernetes.yaml`

**Environment (please complete the following information):**
Quarkus 1.3.0.Final

@iocanel @geoand

### PR DESCRIPTION
**Pull request by iocanel**
Fixes: #8093 
Fixes: #8091 

and removes obsolete decorator classes that have been fixed upstream.

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel can we enhance the tests to cover the linked issues please?
We can do with all the test coverage we can get 😆

**Comment by iocanel** [comment]
> @iocanel can we enhance the tests to cover the linked issues please?
> We can do with all the test coverage we can get

Since, the fix is actually on the dekorate side, I added the tests there.

**Comment by geoand** [comment]
Yeah I know, but due to the deep integration with dekorate we have and to
avoid things breaking in the future, I would prefer we also enhance some of
our existing tests to test for the linked issues.

**Comment by geoand** [comment]
@iocanel one of the existing tests is failing: `OpenshiftWithHealthTest.assertGeneratedResources`

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by iocanel** [comment]
This pull request introduces a new bug. I'll fix it ASAP.

**Comment by iocanel** [comment]
> This pull request introduces a new bug. I'll fix it ASAP.

Done!

**Comment by geoand** [comment]
> > This pull request introduces a new bug. I'll fix it ASAP.
> 
> Done!

Thanks!

**Pull request merged**
