### PR TITLE
Update kindcontainer to 1.4.4

### PR DESCRIPTION
**Pull request by bulldog98**

### CODE REVIEW

**Comment by geoand** [comment]
cc @metacosm

**Comment by metacosm** [comment]
Minimal testing hasn't shown any issue.

**Comment by geoand** [comment]
Thanks!

**Review by geoand — APPROVED** [review]

**Comment by bulldog98** [comment]
The test failure seems to be that, an image (quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21) cannot be pulled in the test. Not sure why this happen, but that seems fishy

**Pull request merged**
