### PR TITLE
Raise kotlin-maven-plugin jvmTarget from 1.8 to 11

### PR DESCRIPTION
**Pull request by famod**

### CODE REVIEW

**Comment by famod** [comment]
I decided it's time to manage this plugin in build-parent...

**Review by gsmet — APPROVED** [review]
Makes perfect sense, thanks!

**Comment by gsmet** [comment]
@evanchooly I let you merge this one.

**Comment by famod** [comment]
Is this `ConfiguredBeanTest` a new flake?

**Review by evanchooly — APPROVED** [review]

**Comment by evanchooly** [comment]
@gsmet I think it's fine to merge because we know the cause of those config tests is elsewhere, yeah?

**Comment by gsmet** [comment]
@famod yes, it should be already fixed

**Pull request merged**
