### PR TITLE
Fix a race condition in ReactiveDatasourceHealthCheck data field population

### LINKED ISSUE #42133: Incorrect data in the ReactiveDatasourceHealthCheck being set when the connection is down
### Describe the bug

In https://github.com/quarkusio/quarkus/blob/72297fbee8c6633281a6a7900d6c2ac84506ea11/extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/ReactiveDatasourceHealthCheck.java#L79
the data field for a datasource is set UP, however as this is reactive code theres a race condition existing where the checkFailures method in the same class can set the data field to DOWN before this UP data is set. This can result in the health check being DOWN but the datasource being UP.

The fix for this is actually extremely easy

Change the execute section to set the UP data if the result is not a failure, and remove the setting of this data on line 79
```
pgPool.query(healthCheckSQL)
            .execute { ar: AsyncResult<RowSet<Row>> ->
                if (ar.failed()) {
                    operationsError(dataSourceName, ar.cause())
                    builder.down()
                    builder.withData(dataSourceName, "DOWN - connection failed: ${ar.cause().javaClass.name} : ${ar.cause().message}")
                } else {
                    builder.withData(dataSourceName, "UP")
                }
                databaseConnectionAttempt.complete(null)
            }
```

### Expected behavior

If the connection is down and the query can't be executed then the health check should be
```
{
            "name": "Reactive MySQL connections health check",
            "status": "DOWN",
            "data": {
                "<default>": "DOWN - connection failed: io.netty.channel.AbstractChannel$AnnotatedSocketException : Network is unreachable: HOST_DETAILS"
            }
        } 
```

### Actual behavior

If the connection is down and the query can't be executed then the health check is 
```
{
            "name": "Reactive MySQL connections health check",
            "status": "DOWN",
            "data": {
                "<default>": "UP"
            }
        } 
```

### How to Reproduce?

1. Create any Database server and make sure its running
2. Start any Quarkus App with a Reactive Client e.g. `implementation("io.quarkus:quarkus-reactive-mysql-client")` connecting the DB from "1"
3. Shut down the Database
4. Query `/q/health/ready` endpoint

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xstefank**
I don't think we need a test for this but I can add it if someone thinks it's worth it.

- Fixes: #42133

### CODE REVIEW

**Comment by geoand** [comment]
> I don't think we need a test for this but I can add it if someone thinks it's worth it.

I actually believe it would be nice to have as we clearly aren't testing the scenario that the user described

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
The failures definitelt seem related

**Comment by gsmet** [comment]
We need to check if it applies to 3.8.

**Comment by xstefank** [comment]
@gsmet yes, this applies to 3.8.

**Pull request merged**
