### PR TITLE
Jakarta TCKs

### LINKED ISSUE #28558: CDI Lite compliance (CDI 4.0)
### Description

I intend to eventually make ArC fully compliant with the CDI Lite part of CDI 4.0. This entails:

- implementing Build Compatible Extensions in ArC
- implementing an Arquillian adapter for ArC
- adding a CDI TCK runner module to ArC
- most likely adding a special mode (off by default) that enables strict spec compliance
- fixing the issues found by the TCK

This issue is a tracker for all that. Work will start on this when Quarkus mainline switches to Jakarta EE 10 dependencies and ArC specifically switches to CDI 4.0.

### Implementation ideas

I actually have quite a lot of that already implemented on a non-public branch (that I've been rebasing for more than 2 years actually). Specifically:

- Arquillian adapter is implemented (could be submitted now, but would cause too much churn), together with a simple CDI Lite TCK runner module
- Build Compatible Extensions are implemented and pass all the relevant CDI TCK tests

What I didn't focus on yet is passing the full CDI Lite TCK. As is, ArC passes roughly 1/2 of the CDI Lite TCK, so there's quite some work to do. I expect that some tests in the CDI Lite TCK are always going to fail due to some improvements we made in ArC and are not willing to give up -- for that reason, I expect we'll have to add a switch for enabling strict spec compliance at the cost of foregoing the improvements. That switch will be off by default, but we'll turn it on to pass the TCK. Users will also be able to turn it on if they so desire.

### List of related PRs

- #30447
- #30452
- #30509
- #30544
- #30666
- #30917
- #30924
- #30950
- #31062
- #31085
- #31248
- #31348
- #31444
- #31589
- #31702
- #31814
- #32407
- #32730
- #32885
- #32945
- #32984
- #33051
- #33447
- #33523
- #33638

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #28558

- fix type discovery for classes added by Build Compatible Extensions
- fix bean archive discovery in strict mode
- fix discovering bean archives that only contain scopes
- remove useless Arquillian extension from MP Context Propagation TCK
- add workaround for Arquillian memory leak
- improve instantiating test classes through CDI
- update to CDI TCK 4.0.10
- add Jakarta TCKs

### CODE REVIEW

**Comment by Ladicek** [comment]
#33523 was merged and CDI TCK 4.0.10 was released, so this PR is now rebased and ready.

**Comment by manovotn** [comment]
> #33523 was merged and CDI TCK 4.0.10 was released, so this PR is now rebased and ready.

Awesome, almost there now! :)

**Review by geoand — COMMENTED** [review]
I don't know anything about Arquillian unfortunately to be able to provide any meaningful reviewe

**Comment by Ladicek** [comment]
@geoand I was thinking more about this commit: https://github.com/quarkusio/quarkus/pull/33638/commits/bc3802e70a03b5aef3fe66225b71e5e74c7c2d9b It's a tiny thing, but could still use a second pair of eyes :-)

**Comment by geoand** [comment]
> This class is loaded from the Quarkus CL and so the code can be written directly instead of reflectively

I always love this kind of cleanup! Moving reflection as high up as possible is such an enabler :)

**Comment by Ladicek** [comment]
Issues should be gone now. The MP Context Propagation TCK used to fail because when refactoring the Arquillian adapter, I forgot to update possible consumers -- fortunately, the consumer in MP ConProp TCK was redundant, so I just deleted it. The MP LRA TCK used to fail because when refactoring the Arquillian adapter, I failed to transform all `null` checks properly, which I fixed.

**Review by mkouba — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

**Pull request merged**
