### PR TITLE
Use maven.compiler.release

### LINKED ISSUE #14487: Consider using maven.compiler.release instead of maven.compiler.source/.target when creating projects
**Description**
With Java9+, the `relase` flag should be preferred over `source`/`target` because it will also check whether you are accidentally using an API that does not exist in a lower version.
One such problem is described here: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

So, instead of:
```xml
<maven.compiler.source>11</maven.compiler.source>
<maven.compiler.target>11</maven.compiler.target>
```
this should be used:
```xml
<maven.compiler.release>11</maven.compiler.release>
```

However:
- `release` doesn't work on JDK 8 (compiler-plugin will fail)
- `maven.compiler.parameters` does not work when just `release` is specified:
   https://issues.apache.org/jira/browse/MCOMPILER-413
   As a workaround (until that bug is fixed), `target` must be set as well (or set parameters directly in the compiler args)
- system module exports do not work, e.g. https://github.com/mvndaemon/mvnd/issues/320#issuecomment-761868291

PS: At least once there was a user running into the parameters problem because he had set just `release`: #14331

### LINKED ISSUE #19866: Quickstarts: use maven.compiler.release instead of maven.compiler.source and maven.compiler.target
### Description

In
https://raw.githubusercontent.com/quarkusio/quarkus-quickstarts/main/getting-started/pom.xml

it says

```
    <properties>
        ...
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
```

### Implementation ideas

Use instead

```
    <properties>
        ...
        <maven.compiler.release>11</maven.compiler.source>
    </properties>
```

The release tag (new in JDK 11 (or was it 9?)), replaces source AND target and gives additional guarantees (for example release=11 will fail when using a JDK API new in 17 (so not available in 11), EVEN when build with JDK 17.

### PR DESCRIPTION
**Pull request by ggrebert**
replace `maven.compiler.source` and `maven.compiler.target` by `maven.compiler.release`.

Fixes #19866

### CODE REVIEW

**Review by famod — COMMENTED** [review]
Thanks for your contribution!

#19866 is pretty much a duplicate of #14487 and that ticket contains some info why simply dropping `target` will produce a problem with `maven.compiler.parameters`:

> - `maven.compiler.parameters` does not work when just `release` is specified:
   https://issues.apache.org/jira/browse/MCOMPILER-413
   As a workaround (until that bug is fixed), `target` must be set as well (or set parameters directly in the compiler args)

@ia3andy @aloubyansky WDYT? Shall we keep the `target` property or shall we set directy the compiler arg?

PS: The other two points in #14487 are note relevant (anymore), AFAICS.

**Comment by famod** [comment]
@ggrebert btw, your commit author doesn't seem to match you GH account mail address.

**Comment by ggrebert** [comment]
@famod mail address fixed.

**Comment by aloubyansky** [comment]
Sounds like setting the compiler arg is the better option.

**Comment by ggrebert** [comment]
Do you want to replace the following lines

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>     
  <artifactId>maven-compiler-plugin</artifactId>
  <version>$\{compiler-plugin.version}</version>
  <!-- Workaround to support maven.compiler.parameters property (see https://youtrack.jetbrains.com/issue/IDEA-201496) -->
  <configuration>
    <parameters>$\{maven.compiler.parameters}</parameters>
  </configuration>
</plugin>
```

by

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>     
  <artifactId>maven-compiler-plugin</artifactId>
  <version>$\{compiler-plugin.version}</version>
  <!-- Workaround to support maven.compiler.parameters property (see https://youtrack.jetbrains.com/issue/IDEA-201496) -->
  <configuration>
    <compilerArgs>
      <arg>-parameters</arg>
    </compilerArgs>
  </configuration>
</plugin>
```

like: https://github.com/albertominetti/jackson-parameters/pull/1/commits/ad0fa7605fe378a4b900b7c911f4e7019533092f ?

**Comment by famod** [comment]
I would go with:
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>     
  <artifactId>maven-compiler-plugin</artifactId>
  <version>$\{compiler-plugin.version}</version>
  <!-- Workaround to support maven.compiler.parameters property (see https://youtrack.jetbrains.com/issue/IDEA-201496) -->
  <configuration>
    <compilerArgs>
      <!-- Workaround for https://issues.apache.org/jira/browse/MCOMPILER-413 and https://youtrack.jetbrains.com/issue/IDEA-201496-->
      <arg>-parameters</arg>
    </compilerArgs>
  </configuration>
</plugin>
```
Someone using IntelliJ should test that part. But then again it was fixed in 2021.2. 🤷‍♂️

**Comment by famod** [comment]
If the IntelliJ part is fixed, we could also drop that link to `https://youtrack.jetbrains.com/issue/IDEA-201496`. /cc @ia3andy

**Comment by famod** [comment]
We have many more pom.xml files still using `maven.compiler.source/target`.

@gsmet WDYT about adjusting them _all_ here? Any objections w.r.t. making backports harder with such a big change?

**Comment by gsmet** [comment]
@famod I think it should be OK, backport-wise. We don't really change that very often.

**Comment by famod** [comment]
Draft status for now because I need to go through all remaining occurences to decide whether they need to be added to this PR or whether I can address those in a subsequent PR.

**Comment by famod** [comment]
Ok, so this is where I'd like to stop for this PR and do the rest in a subsequent PR (some archetypes and switching the actual build process in this repo to `release`).

@aloubyansky @ia3andy @gsmet please (re-)review.

**Review by famod — APPROVED** [review]

**Review by aloubyansky — APPROVED** [review]

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
