### PR TITLE
Add a note about quarkus-security dependency

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gastaldi** [comment]
BTW if the dependency is required for all items, shouldn't it be the first item?

**Comment by sberyozkin** [comment]
@gastaldi Hi George - all the existing mechanism will have it hence I added it only in this sub-section - because here the users may want to go without smallrye-jwt and other sec extensions. I was thinking for a moment to put it somewhere in the main `security.adoc` page but then thought the users would copy it even if it is already fetched with `smallrye-jwt` or any other sec extension...
Are you OK with this clarification ?

**Comment by sberyozkin** [comment]
@gastaldi May be it is worth to create a small subsection instead titled `Custom Security` and note that if you go totally own way then add this dependency and proceed from there...

**Comment by sberyozkin** [comment]
Ignore me please - it is also needed for bouncy castle, etc, so I'll put something on top of that doc with the note

**Comment by sberyozkin** [comment]
Hey @gastaldi I've moved it to the top and have verified the links work - does it look all right ? if some text needs to be tweaked then please let me know

**Review by gastaldi — APPROVED** [review]
Looks great!

**Pull request merged**
