### PR TITLE
JPA test cleanup

### PR DESCRIPTION
**Pull request by yrodiere**
Opening this draft so I don't forget about it.

Based on #36978 , which must be merged first.

For now this includes only this:

* Migrate all JPA tests to RestEasy Reactive (instead of using Servlets)

I had to do it anyway because I couldn't for the life of me debug test failures with this servlet stuff.

I wonder if I should also do the following:

- [x] Use the recommended approach to access the entity manager: inject it, instead of using `createEntityManager`
   That will probably require adding a dedicated test using JPA's createEntityManager directly, so that we have at least some coverage for that?
- [x] Use the recommended approach to start/end transactions: `@Transactional` or `QuarkusTransaction`, instead of `entityManager.getTransaction()`
   That will probably require adding a dedicated test using `entityManager.getTransaction()`, so that we have at least some coverage for that?
- [ ] Move all JPA integration tests under a common directory?
- [ ] Move all JPA + Hibernate ORM integration tests under a common directory?

WDYT @gsmet / @Sanne?

### CODE REVIEW

**Comment by gsmet** [comment]
All of this makes sense. Just remember you also need to adjust the JSON file with native tests if you move the IT modules around.

**Comment by yrodiere** [comment]
@gsmet Thanks. I did not move the modules in the end, because I need to move to some other task. But I think this is a good first step and ready to merge :)

About the review... Hum... good luck? More seriously, I'd recommend reviewing commit by commit, that way you can skip the larger diffs more easily.

**Review by gsmet — APPROVED** [review]
LGTM!

**Comment by gsmet** [comment]
There are a bunch of tests failing (at least on Windows):

```

Error:  io.quarkus.it.jpa.proxy.ProxyTest.testEnhancedProxies -- Time elapsed: 0.029 s <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "OK"
  Actual: <html><body><h1>Resource not found</h1></body></html>
```

**Comment by yrodiere** [comment]
Right, I forgot to run this particular module locally... Note I did run all the others, downloading all the DB container images just for this :sunglasses: 

Anyway, I fixed the problems: should be good now.

**Pull request merged**
