### PR TITLE
Don't register Kafka LoginModule interface for reflection

### PR DESCRIPTION
**Pull request by gsmet**
I think this code is misinterpreting what ReflectiveHierarchyBuildItem
is about. It is registering the *parents* and method return types and
parameters.
I think the initial idea was to register the implementors for reflection
but this was never in effect: the current code only registers the
interface (and the referenced types) for reflection.
Given that, I think it's safe to simply remove this code.

I tested both kafka-sasl IT modules in native and they did work.

Let's see what CI and @cescoffier have to say.

BTW, the main problem this patch is trying to solve is this warning when building any Kafka application:
```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- javax.net.ssl.SSLSocketFactory (source: KafkaProcessor > javax.security.auth.spi.LoginModule)
	- org.jose4j.jwk.HttpsJwks (source: KafkaProcessor > javax.security.auth.spi.LoginModule)
	- org.jose4j.jwk.JsonWebKey (source: KafkaProcessor > javax.security.auth.spi.LoginModule)
	- org.jose4j.jwk.VerificationJwkSelector (source: KafkaProcessor > javax.security.auth.spi.LoginModule)
	- org.jose4j.jwt.consumer.JwtConsumer (source: KafkaProcessor > javax.security.auth.spi.LoginModule)
	- org.jose4j.keys.resolvers.VerificationKeyResolver (source: KafkaProcessor > javax.security.auth.spi.LoginModule)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

### CODE REVIEW

**Comment by cescoffier** [comment]
Since when do we have these warnings?

**Comment by cescoffier** [comment]
Also, I don't believe that we have test testing that part. While we have SASL tests, they are quite small. We would need to run manual test against the 2 auth mechanisms proposed by Managed Kafka to verify.

**Comment by gsmet** [comment]
Well, I had another patch actually registering the `LoginModule` implementors for reflection. But... if I fail to see how registering the `LoginModule` interface could make things work.

**Comment by gsmet** [comment]
I think it's probably worth checking as the warnings are annoying.

**Comment by cescoffier** [comment]
Well, it seems that our ITs cover that case

**Comment by ozangunalp** [comment]
I confirmed the breaking ITs on CI: passing on JVM broken on native.
- kafka-oauth-keycloak uses SASL_PLAINTEXT with OAUTHBEARER and complains about org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslClientCallbackHandler
- kafka-sasl uses SASL_PLAINTEXT with PLAIN and complains about org.apache.kafka.common.security.plain.PlainLoginModule

So other ITs with SASL_PLAINTEXT with kerberos and SSL pass both on JVM and native.

I'll try some fixes later on.

**Comment by cescoffier** [comment]
We may need to explicitly register these. Note that the kafka client jar is not jandexed. Maybe adding it to the index would fix the issue.

**Comment by gsmet** [comment]
I'll have another look. I know I made the tests pass at some point because I explicitly built these two. Maybe I forgot to recompile the extension for my next try, removing the new explicit registration I added.

**Comment by ozangunalp** [comment]
I've been looking at this since this morning. It seems we have a couple of options:
- Keep the ReflectiveHierarchyBuildItem and add missing classes to the index, as was done before for `LoginModule`, `Subject` etc.
- Keep the ReflectiveHierarchyBuildItem and produce `ReflectiveHierarchyIgnoreWarningBuildItem` for the missing classes in the index.
- Remove the ReflectiveHierarchyBuildItem and add a complete list of classes as reflective, if possible.

For the last option I can identify several classes:
- `LoginModule` implementations such as `PlainLoginModule`, `OAuthBearerLoginModule` and `ScramLoginModule` : any custom class would be included, in theory, in kafka config `sasl.login.class` or first token in the `sasl.jaas.config`
- `AuthenticateCallbackHandler` implementations such as `OAuthBearerSaslClientCallbackHandler`, `ScramSaslClientFactory` and `KerberosClientCallbackHandler` : custom class would be in kafka config `sasl.login.callback.handler.class` or ​`sasl.client.callback.handler.class`
- While we are at it we can add classes from config such as `ssl.engine.factory.class` `partition.assignment.strategy` and `partitioner.class`.

**Comment by gsmet** [comment]
Let me have a look at this as I'm puzzled it worked locally.I probably did something wrong.

**Comment by gsmet** [comment]
OK, it's definitely better when you actually run the tests :). Forgot the `-Dstart-containers -Dtest-containers` :).

**Comment by gsmet** [comment]
I pushed some adjustments. They fix the second failure for sure but I wasn't able to check the `integration-tests/kafka-oauth-keycloak` failure has been fixed because I don't know why but the Keycloak container doesn't want to start.

Let's see what CI has to say.

**Review by cescoffier — APPROVED** [review]
Ah, that version makes sense! This, combined with the possibility to add jar to the index, will work nicely.

**Comment by gsmet** [comment]
That was my original version before I started removing things :).

**Review by ozangunalp — APPROVED** [review]
Yes this makes sense!

**Pull request merged**
