### PR TITLE
Preserve debug symbols when classes are recompiled in dev mode

### PR DESCRIPTION
**Pull request by geoand**
Original issue reported at: https://stackoverflow.com/q/55142212/2504224

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Nice one. Let's wait for CI then merge.

**Comment by geoand** [comment]
Thanks :)

**Comment by geoand** [comment]
All green :tada:

**Comment by dmlloyd** [comment]
Don't we want `-parameters` as well?

**Comment by geoand** [comment]
@dmlloyd makes sense, I will follow up with a new PR

**Pull request merged**
