### PR TITLE
Registers RestClientListener for reflection and adds service file as a native resource

### LINKED ISSUE #11349: Multiple traces in Native mode instead of one trace with multiple spans like in JVM mode
We see multiple traces in Native mode instead of one trace with multiple spans like in JVM mode. Using Quarkus 1.7.0.Final, GraalVM 20.1 JDK11 based.
This issue was Identified using https://github.com/quarkus-qe/quarkus-openshift-test-suite, I created a standalone application which doesn't need OpenShift cluster - https://github.com/rsvoboda/tracing-sample

The expected behavior for Native mode is to see the same behavior as in JVM mode, just one trace with multiple spans.
@Ladicek indicated that it sounds like context propagation not working

### Steps to reproduce:
Terminal 1
```
docker run -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 jaegertracing/all-in-one:latest
```

Terminal 2
```
git clone https://github.com/rsvoboda/tracing-sample.git
cd tracing-sample

sdk use java 20.1.0.r11-grl && export GRAALVM_HOME=$JAVA_HOME
mvn verify -Dnative
```

### View the traces
Open http://localhost:16686/ and Find traces for `test-traced-service` service

### Screenshots
Search for Traces:
Screenshot 2020-08-12 at 15 34 14

JVM mode result
Screenshot 2020-08-12 at 15 34 30

Native mode result
Screenshot 2020-08-12 at 15 34 37
Screenshot 2020-08-12 at 15 34 43

### PR DESCRIPTION
**Pull request by kenfinnigan**
- Registers RestClientListener for reflection and adds service file as a native resource

Fixes #11349

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Did this fail because of hitting a time limit?

**Comment by Ladicek** [comment]
FYI, GitHub doesn't notice the issue number when it's not in the 1st comment of the PR. (And it probably has to be there during PR creation, because when I added it retroactively in some of my PRs elsewhere, it didn't work.)

**Comment by kenfinnigan** [comment]
@gsmet do you happen to know why the CI build just stopped? Nothing obvious to me in the CI details

**Review by rsvoboda — APPROVED** [review]
3 spans in case of native mode, 3 spans in case of jvm mode
Checked with `tracing-sample` reproducer

**Comment by jaikiran** [comment]
Hello @kenfinnigan, both the failed jobs are failing due to unrelated reasons of the form:
```
2020-08-19T16:04:38.4842075Z ##[section]Starting: Request a runner to run this job
2020-08-19T16:04:39.7916975Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2020-08-19T16:04:39.7917120Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-08-19T16:04:39.7917372Z Found online and idle hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-08-19T16:04:40.1329972Z ##[section]Finishing: Request a runner to run this job

```

**Review by gsmet — APPROVED** [review]

**Comment by kenfinnigan** [comment]
Thanks @jaikiran, couldn't easily see that from where I was looking

**Pull request merged**
