### PR TITLE
Make KubernetesClientErrorHandler always throw a RuntimeException

### LINKED ISSUE #19870: Potential NPE when deploying on Kubernetes / Openshift
### Describe the bug

The method below may return null, when `adapt` fails.

```
    private static OpenShiftClient toOpenshiftClient(KubernetesClient client) {
        try {
            return client.adapt(OpenShiftClient.class);
        } catch (KubernetesClientException e) {
            KubernetesClientErrorHandler.handle(e);
            return null; // will never happen
        }
    }
```
So, what is supposed to never happen actually does.

### Expected behavior

`handle()` should always throw an Exception

### Actual behavior

`handle()` only throws SSL related exception Exception 

### How to Reproduce?

Just create an app add the `quarkus-openshift` extension and run `mvn -Dquarkus.kubernetes.deploy=true` against an unreachable cluster.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #19870

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
That makes sense. I'm curious about @geoand's question too

**Comment by iocanel** [comment]
> Are there any potential side effects to always throwing the exception?

Yes, the build breaks and the users get's the stack trace of the exception.
With the current behavior the error becomes an NPE (unless its an `SSLSomethingException`) without any indication of what might be wrong.

I feel that when a user requests an operation (in this case `container image build`) and this cannot be done for any reason, the build should immediately fail. If not random things might happen later on, that are hard for users to decipher.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand @iocanel should we backport this one for 2.2.2.Final?

**Comment by geoand** [comment]
That sounds like a good idea to me

**Pull request merged**
