### PR TITLE
Revert "Optimise the strategy we use to reset the classloader in the …

### LINKED ISSUE #19136: Classloader changed in quarkus 2.1.0 (regression from 2.0.1) for optaplanner/drools with smallrye (but not resteasy)
### Describe the bug

The drools ANC compiler fails in 2.1.0 (not in 2.0.1) on optaplanner's activemq-quarkus quickstart
because the classloader changed.

Before (2.0.1):
image

After (2.1.0):
image

The strange thing is, that it doesn't fail for any of the other quickstarts (those use resteasy and sometimes hibernate, this one uses smallrye).
Comparing the dependency tree between 2.0.1 and 2.1.0 shows nothing besides the quarkus version change that could explain this.

### Expected behavior

A successful test with the reproducer below.

### Actual behavior

```
2021-07-30 16:29:06,337 WARN  [org.acm.sch.mes.TimeTableMessagingHandler] (ForkJoinPool.commonPool-worker-3) Error during processing a solver request (1).: org.drools.ancompiler.CouldNotCreateAlphaNetworkCompilerException: Cannot create Compiled Alpha Network
        at org.drools.ancompiler.CompiledNetworkSource.newCompiledNetworkInstance(CompiledNetworkSource.java:80)
        at org.drools.ancompiler.CompiledNetworkSource.createInstanceAndSet(CompiledNetworkSource.java:66)
        at org.drools.ancompiler.KieBaseUpdaterANC.lambda$inMemoryUpdate$0(KieBaseUpdaterANC.java:72)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
        at org.drools.ancompiler.KieBaseUpdaterANC.inMemoryUpdate(KieBaseUpdaterANC.java:70)
        at org.drools.ancompiler.KieBaseUpdaterANC.run(KieBaseUpdaterANC.java:52)
        at org.drools.ancompiler.KieBaseUpdaterANC.generateAndSetInMemoryANC(KieBaseUpdaterANC.java:99)
        at org.optaplanner.core.impl.score.stream.drools.DroolsConstraintSessionFactory.buildKieBaseFromModel(DroolsConstraintSessionFactory.java:85)
        at org.optaplanner.core.impl.score.stream.drools.DroolsConstraintSessionFactory.buildSession(DroolsConstraintSessionFactory.java:126)
        at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirectorFactory.newConstraintStreamingSession(DroolsConstraintStreamScoreDirectorFactory.java:50)
        at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirector.resetConstraintStreamingSession(DroolsConstraintStreamScoreDirector.java:75)
        at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirector.setWorkingSolution(DroolsConstraintStreamScoreDirector.java:67)
        at org.optaplanner.core.impl.solver.scope.SolverScope.setWorkingSolutionFromBestSolution(SolverScope.java:215)
        at org.optaplanner.core.impl.solver.AbstractSolver.solvingStarted(AbstractSolver.java:80)
        at org.optaplanner.core.impl.solver.DefaultSolver.solvingStarted(DefaultSolver.java:200)
        at org.optaplanner.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:174)
        at org.acme.schooltimetabling.messaging.TimeTableMessagingHandler.lambda$solve$0(TimeTableMessagingHandler.java:79)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoSuchMethodException: org.drools.ancompiler.Compiledorg_acme_schooltimetabling_domain_LessonNetwork31008790748.<init>(org.drools.core.spi.InternalReadAccessor, java.util.Map)
        at java.base/java.lang.Class.getConstructor0(Class.java:3349)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
        at org.drools.ancompiler.CompiledNetworkSource.newCompiledNetworkInstance(CompiledNetworkSource.java:77)
        ... 23 more

```

### How to Reproduce?

```
git clone https://github.com/kiegroup/optaplanner-quickstarts.git
cd optaplanner-quickstarts
git checkout development
cd technology/java-activemq-quarkus
gedit pom.xml // Switch it to 2.1.0.Final
mvn clean install -DskipTests
cd solver
mvn test -Dtest=TimeTableMessagingHandlerTest#solve
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Reproduced on multiple machines (Radovan, Geoffrey, Luca).

### PR DESCRIPTION
**Pull request by stuartwdouglas**
…Common ForkJoin ThreadPool"

This reverts commit ae9a6345c229356d1ea8b536bab4535ca8e8ead7.

Fixes #19136

This code not only stops class loader leaks but also makes sure the correct TCCL is set.

### CODE REVIEW

**Review by Sanne — APPROVED** [review]
OK but could you elaborate on why?

Does it mean we actually have to max out the threadpool and start all threads making our machines beg for mercy?

It seems to imply we don't actually reset the context so that newly started threads will use this - I assumed that was dealt with by some other area of the code.
BTW you'd agree this is brittle right? There is no guarantee that these threads won't die for wathever reason, or just scale back, and then you'll have the wrong context again. Unless I'm not understaning this at all :)

**Comment by ge0ffrey** [comment]
Thanks Stuart for this fix.
Please backport for a 2.1.x release if possible.

**Comment by Sanne** [comment]
@ge0ffrey agreed :) And many thanks for your report!

I guess let's merge the revert first, then I'll see if we can have our cake and eat it too with a follow up. Simplest seems to be to just execute on the TODO I already had in the code :)  We also seem to need more ITs though.

Opened #19161

**Comment by stuartwdouglas** [comment]
I think that is JDK16+ only, I don't see it in JDK14.

**Pull request merged**
