### PR TITLE
Allow the use of @DisableIfBuiltWithGraalVMOlderThan on test methods

### PR DESCRIPTION
**Pull request by geoand**
Relates to https://github.com/quarkusio/quarkus/pull/16216#issuecomment-814093389

### CODE REVIEW

**Comment by geoand** [comment]
@zakkak want to give it a shot?

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by zakkak — APPROVED** [review]
Tested with #16216

Thanks @geoand

**Comment by geoand** [comment]
Great, thanks for checking!

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/16304 should have fixed the CI issue.

I rebased and force-pushed

**Pull request merged**
