### PR TITLE
Upgrade to Narayana 5.12.5.Final

### PR DESCRIPTION
**Pull request by Sanne**
This fixes a performance regression with the artemis journal
 - https://issues.redhat.com/browse/JBTM-3572

### CODE REVIEW

**Comment by mmusgrov** [comment]
@Sanne The compilation fails because `LRAParticipant.java:[20,19] package javax.ws.rs does not exist`. Have you already moved to jakarta?

**Comment by Sanne** [comment]
> @Sanne The compilation fails because `LRAParticipant.java:[20,19] package javax.ws.rs does not exist`. Have you already moved to jakarta?

We have not - I'll need to have a look.

**Comment by Sanne** [comment]
I'll close this @mmusgrov , since it seems this version is not an option, unless I experiment with dependency overrides which make me uncomfortable. Feel free to send a different PR

**Comment by mmusgrov** [comment]
Oh dear, I guess we will need another release of narayana

**Pull request closed without merging**
