### PR TITLE
Migrate Security WebAuth guide to Hibernate ORM

### LINKED ISSUE #36438: Should security-web-authn guide and quickstart use Hibernate Reactive by default?
The `security-web-authn` guide and quickstart are using Hibernate Reactive and I don't think it's something mandatory when using security-web-authn?

If not, I think we would rather have a security-web-authn quickstart that is not using HR and maybe rename the existing one to security-web-authn-reactive.

And the guide should be based on the non-reactive one.

As now mentioned in the Hibernate Reactive guide, we are recommending using Hibernate ORM for most workloads, except when you need high concurrency so Hibernate ORM should be the default for our guides when HR is not mandatory.
Especially since it makes things a tad more complex and might have bring more complexity than needed to explain the concepts of this particular feature.

/cc @sberyozkin I'm not sure who worked on that, could you coordinate this (if it makes sense and I'm not mistaken that HR is not mandatory)?

(This issue is part of various things noted when I added the `:topics:` to the guides)

### PR DESCRIPTION
**Pull request by michalvavrik**
closes: #36438

related to https://github.com/quarkusio/quarkus-quickstarts/pull/1375

### CODE REVIEW

**Review by FroMage — APPROVED** [review]
Same as for the other PR, this is fine, but I wonder if we should not keep the reactive style for people who want to do reactive, as it's not trivial to turn the blocking one into the reactive one. People might not figure it out and give up 🤷

**Comment by sberyozkin** [comment]
@michalvavrik Thanks, it probably closes a few other issues, give me 1 sec to check

**Comment by sberyozkin** [comment]
@michalvavrik See #32376, looks like that issue is invalid ?

**Comment by michalvavrik** [comment]
> @michalvavrik See #32376, looks like that issue is invalid ?

IIRC codestarts work differently, I think the issue author confused terms. I can look into that issue, I'll put it on my list.

**Comment by michalvavrik** [comment]
@FroMage I think it is not necessary to keep _reactive_ guide as long as there is reactive quickstart, because they would be mostly duplicate. We can keep reactive quickstart and link it with this quickstart as well for those who use Hiberante Reactive.

I'll add the reactive quickstart as well and after that, I'll ask @sberyozkin to review changes (text that link Hibernate Reactive version). Thanks

**Comment by sberyozkin** [comment]
Thanks @michalvavrik, let me merge given @FroMage's approval

**Pull request merged**
