### PR TITLE
Refactor & Remove legacy codegen

### PR DESCRIPTION
**Pull request by ia3andy**
This has been in my TODO forever :)

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]
Good to see!

**Comment by aloubyansky** [comment]
Although
````
Error:  io.quarkus.devtools.commands.CreateProjectHelperTest.givenKotlinProjectWithVersion18ShouldReturn17  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <17> but was: <11>
````

**Comment by ia3andy** [comment]
> Although
> 
> ```
> Error:  io.quarkus.devtools.commands.CreateProjectHelperTest.givenKotlinProjectWithVersion18ShouldReturn17  Time elapsed: 0.002 s  <<< FAILURE!
> org.opentest4j.AssertionFailedError: expected: <17> but was: <11>
> ```

Will have a look :)

**Comment by ia3andy** [comment]
@aloubyansky error seems unrelated right?

**Pull request merged**
