### PR TITLE
Consider GZip max input in REST Client

### LINKED ISSUE #12941: quarkus.resteasy.gzip.max-input does not apply for REST client
**Describe the bug**
Given a REST client configuration as in the official guide,
with `quarkus.resteasy.gzip.enabled=true` and `quarkus.resteasy.gzip.max-input=100M`
when trying to fetch >10M  < 100M (unpacked) gzipped content from an endpoint,
then an exception 'quarkus RESTEASY003357: GZIP input exceeds max size: 10000000' is thrown

**Expected behavior**
The GZIP input is unpacked successfully

**Actual behavior**
Exception 'quarkus RESTEASY003357: GZIP input exceeds max size: 10000000' is thrown

**To Reproduce**
...

**Configuration**
...

**Screenshots**
...

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.8.3
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.7, vendor: Azul Systems, Inc.
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Additional context**
Apparently, in `GZIPDecodingInterceptor#getMaxSize()`, `ResteasyConfiguration context = ResteasyContext.getContextData(ResteasyConfiguration.class);` returns a `null` `ResteasyConfiguration`, causing `DEFAULT_MAX_SIZE` to apply.
Also `JaxRSTestCase#testGzipConfig` seems to be testing the configuration  `quarkus.resteasy.gzip.max-input=10` from the server-side perspective.

### PR DESCRIPTION
**Pull request by gsmet**
Tentatively fixes https://github.com/quarkusio/quarkus/issues/12941 .

Let's wait for the OP's confirmation.

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by machi1990** [comment]
@gsmet should we have a test for this?

**Comment by gsmet** [comment]
Maybe. I won't write one though :).

**Comment by gsmet** [comment]
Apparently it doesn't work so let's not merge it.

**Comment by gsmet** [comment]
@kenfinnigan I digged a bit more and AFAICS, the maxSize is extracted from the `ResteasyContext`:
```
      ResteasyConfiguration context = ResteasyContext.getContextData(ResteasyConfiguration.class);
      if (context != null)
      {
         String s = context.getParameter(ResteasyContextParameters.RESTEASY_GZIP_MAX_INPUT);
```

I haven't found it defined in the client case but I can't say it's easy to analyze this code.

/cc @asoldano do you have any idea how we could push this config to the REST client?

**Comment by kenfinnigan** [comment]
I *think* there's a `ResteasyContext` present on the client-side, but it's been a long time since I've dug through the RESTEasy code

**Comment by gsmet** [comment]
Yeah it's probably there. What we miss (I think) is a way to pass configuration to the providers when using only the RESTEasy client.

**Comment by gastaldi** [comment]
Marked as a draft to prevent merging based on https://github.com/quarkusio/quarkus/pull/12975#issuecomment-717407714

**Comment by asoldano** [comment]
Something you might want to do is proposing changes to get that property in the RESTEasy interceptors using MicroProfile Config instead of accessing the ResteasyContext directly. That way you could any mechanism you have in place to setup MicroProfile configs.

**Comment by gsmet** [comment]
@asoldano  Ok, I won't have time to dig into RESTEasy to fix this so either someone from the RESTEasy team takes it or it will have to stay that way for now.

Closing this PR as it's useless :).

**Pull request closed without merging**
