### PR TITLE
Change Vault default KV secret engine from v1 to v2

### LINKED ISSUE #6739: Fetching credentials from Vault KV v2 fails
**Describe the bug**

I am trying to fetch credentials for DB from Vault KV v2 instead of v1.

I am executing the next Vault commands:

```
vault kv put secret/myapps/vault-service/db password=alex

cat <<EOF | vault policy write vault-service-policy -
path "secret/data/myapps/vault-service/*" {
  capabilities = ["read"]
}
EOF

vault auth enable userpass
vault write auth/userpass/users/alex password=alex policies=vault-service-policy
```

Then if I do  a `vault login ....` I can retrieve correctly the `secret/myapps/vault-service/db` but when I configure Quarkus to fetch the credentials to configure the datasource then I got:

```
Caused by: io.quarkus.vault.runtime.client.VaultClientException code=403 body={"errors":["1 error occurred:\n\t* permission denied\n\n"]}

	at io.quarkus.vault.runtime.client.OkHttpVaultClient.throwVaultException(OkHttpVaultClient.java:146)
	at io.quarkus.vault.runtime.client.OkHttpVaultClient.exec(OkHttpVaultClient.java:130)
	at io.quarkus.vault.runtime.client.OkHttpVaultClient.get(OkHttpVaultClient.java:124)
	at io.quarkus.vault.runtime.client.OkHttpVaultClient.getSecretV1(OkHttpVaultClient.java:74)
	at io.quarkus.vault.runtime.VaultKvManager.readSecret(VaultKvManager.java:28)
	at io.quarkus.vault.runtime.VaultCredentialsProvider.getCredentials(VaultCredentialsProvider.java:37)
	at io.quarkus.vault.runtime.VaultServiceProducer_ProducerMethod_createCredentialsProvider_760efe06b6852169ee62572bb780e1c741813f4b_ClientProxy.getCredentials(VaultServiceProducer_ProducerMethod_createCredentialsProvider_760efe06b6852169ee62572bb780e1c741813f4b_ClientProxy.zig:43)
```

If I run the same example but using the KV v1 then it works correctly.

Also if I change the `kv-path` to `secret/myapps/vault-service/db` I got: 

```
Caused by: io.quarkus.vault.VaultException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (String)"{"request_id":"c4dda670-6886-15af-3867-fe70ae5fa676","lease_id":"","renewable":false,"lease_duration":0,"data":{"data":{"password":"alex"},"metadata":{"created_time":"2020-01-23T09:00:02.438243752Z","deletion_time":"","destroyed":false,"version":1}},"wrap_info":null,"warnings":null,"auth":null}
"; line: 1, column: 120] (through reference chain: io.quarkus.vault.runtime.client.dto.VaultKvSecretV1["data"]->java.util.LinkedHashMap["data"])
```

**Expected behavior**

KV v2 should work as v1

**Actual behavior**

Exception is thrown.

**Configuration**
```properties

quarkus.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=alex
# <1>
quarkus.vault.credentials-provider.mydatabase.kv-path=myapps/vault-service/db
# <2>
quarkus.datasource.credentials-provider=mydatabase
# <3>
quarkus.vault.url=http://localhost:8200
quarkus.vault.authentication.userpass.username=alex
quarkus.vault.authentication.userpass.password=alex
```

To reproduce just follow the instructions of the guide but using KV v2 instead of KV v1.

cc// @vsevel

### PR DESCRIPTION
**Pull request by vsevel**
Fixes Fetching credentials from Vault KV v2 fails https://github.com/quarkusio/quarkus/issues/6739
The change involves moving the kv secret engine default version to be v2 instead of v1, as discussed in https://github.com/quarkusio/quarkus/issues/6739#issuecomment-577778616 and https://github.com/quarkusio/quarkus/issues/6739#issuecomment-577869497

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Comment by vsevel** [comment]
hello @gsmet this should be ready for merge

**Comment by sberyozkin** [comment]
Hi @vsevel @gsmet We've discussed this issue awhile back and this PR is a simple one which just does what was agreed upon at #6739 so I may as well go ahead and merge. But I think the health vault option should go first

**Comment by gsmet** [comment]
@vsevel looks in line with what we discussed. I was just wondering if we should add a comment saying we use version 2 or if it's natural and doesn't require one. I let you judge of that!

**Comment by vsevel** [comment]
> But I think the health vault option should go first

let's do that. we will have to adapt the policy for the health feature test

> I was just wondering if we should add a comment saying we use version 2 

done

now waiting for https://github.com/quarkusio/quarkus/pull/8014

**Comment by sberyozkin** [comment]
@vsevel Thanks, I'll merge asap

**Comment by sberyozkin** [comment]
OK, all is good now with the heath addition, so merging this one now, thanks @vsevel

**Comment by vsevel** [comment]
@gsmet just a note that this is a breaking change, since the default is now v2 (instead of v1).
so people that did not set `quarkus.vault.kv-secret-engine-version` explicitly, will have to set this property to `1` when they upgrade.

**Pull request merged**
