### PR TITLE
Fix reflections registration of constructors used in serialization

### LINKED ISSUE #19711: GraalVM issue with ArrayList serialization
### Describe the bug

When trying to serialize an `ArrayList` in native, we get the following error:

```
2021-08-27 07:00:01,618 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello/serlist failed, error id: 4735770b-c272-499f-ad87-5b70a6a2ca6c-1: org.jboss.resteasy.spi.UnhandledException: java.io.InvalidClassException: java.util.ArrayList; no valid constructor
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.io.InvalidClassException: java.util.ArrayList; no valid constructor
        at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:159)
        at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:875)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2170)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at org.acme.GreetingResource.serlist(GreetingResource.java:69)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 17 more

```

Looks similar to https://github.com/micronaut-projects/micronaut-redis/issues/194

### Expected behavior

The list should be able to be serialized and un-serialized.

### Actual behavior

It fails with the above exception.

### How to Reproduce?

Reproducer:

- Create a sample JAXRS application
- Add the following code:

```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/serstring")
    public String serstring() throws IOException, ClassNotFoundException {

        byte[] bytes = null;

        try (
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ObjectOutputStream oos = new ObjectOutputStream(baos)) {

            oos.writeObject("Hello RESTEasy");
            oos.flush();
            bytes = baos.toByteArray();
        }

        try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
                ObjectInputStream ois = new ObjectInputStream(bais)) {
            return (String) ois.readObject();
        }
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/serlist")
    public String serlist() throws IOException, ClassNotFoundException {

        byte[] bytes = null;

        try (
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ObjectOutputStream oos = new ObjectOutputStream(baos)) {

            List<String> list = new ArrayList<>();
            list.add("Hello RESTEasy");

            oos.writeObject(list);
            oos.flush();
            bytes = baos.toByteArray();
        }

        try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
                ObjectInputStream ois = new ObjectInputStream(bais)) {
            
            return ois.readObject().toString();
        }
    }
```

- do a native build
- start the server
- execute `curl http://localhost:8080/hello/serstring` => `Hello RESTEasy`
- execute `curl http://localhost:8080/hello/serlist` => exception

### Output of `uname -a` or `ver`

windows

### Output of `java -version`

openjdk 11.0.1-redhat 2018-10-16 LTS

### GraalVM version (if different from Java)

Running Quarkus native-image plugin on GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)

### Quarkus version or git rev

2.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### Additional information

`<quarkus.native.container-build>true</quarkus.native.container-build>`

### PR DESCRIPTION
**Pull request by zakkak**
Supersedes #19942

Closes: #19711

### CODE REVIEW

**Comment by vsevel** [comment]
LGTM
should we have also the following code in `RegisterForReflectionBuildStep`, as suggested in this [comment](https://github.com/quarkusio/quarkus/issues/19711#issuecomment-913601763):

```
reflectiveClass.produce(serialization ? ReflectiveClassBuildItem.serializationClass(methods, fields, className) : new ReflectiveClassBuildItem(methods, fields, className));
```

**Comment by zakkak** [comment]
> should we have also the following code in `RegisterForReflectionBuildStep`, as suggested in this [comment](https://github.com/quarkusio/quarkus/issues/19711#issuecomment-913601763):
> 
> ```
> reflectiveClass.produce(serialization ? ReflectiveClassBuildItem.serializationClass(methods, fields, className) : new ReflectiveClassBuildItem(methods, fields, className));
> ```

That's a good question! I think that really depends on whether `serialization = true` in `@RegisterForReflection` implies that the corresponding class should be registered solely for serialization or both for serialization and reflection. Unfortunately the option [appears to be undocumented](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/writing-native-applications-tips.adoc#using-the-registerforreflection-annotation) leaving this open to interpretation.

As far as this PR is concerned I believe this question is orthogonal, however, and should be tackled in a separate issue/PR.

For the record, I would personally prefer to be able to register a class either for:

1. reflection,
2. serialization, or
3. both reflection and serialization.

instead of either "1 or 2" or "1 or 3".

"1 or 2" implies that there is no way for me to register a class for both reflection and serialization with a single annotation. I wonder if
```
@RegisterForReflection(targets = String.class)
public class ReflectionConfig {

}

@RegisterForReflection(targets = String.class, serialization = true)
public class SerializationConfig {

}
```
would do the trick in such cases.

On the other hand "1 or 3" implies that there is no way to avoid registering for reflection a class that I want to be able to serialization, making registrations for serialization more expensive than necessary.

**Comment by vsevel** [comment]
I was actually surprised that `RegisterForReflection` was used for reflection _and_ serialization, when graalvm clearly separates both use cases using the new `serialization-config.json` config file.
Overloading `RegisterForReflection` is misleading. it almost looks liked we piggybacked on an existing mechanism.
my first choice would have been to make 2 annotations with an additional `RegisterForSerialization`. especially if the serialization use case is self sufficient (meaning that if serialization needs some reflection, quarkus will do it for you - e.g. through [addReflections](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java#L262))

```
@RegisterForReflection
@RegisterForSerialization
public class MyClass {
}
```

I understand the argument for 1 annotation. but then I would honor the different attributes `methods` and `fields` that are `true` by default. I am surprised also that `constructors` does not appear on the annotation. 
but I am not a huge fan. At the minimum the doc should be improved to express what it will and won't do when we use `serialization = true`.

as you said this may be a different issue covered by a different PR. 
your PR fixes an immediate problem, so I would go ahead with it.

**Comment by vsevel** [comment]
could you provide some guidance here @stuartwdouglas and/or @gsmet?

**Comment by geoand** [comment]
Yeah, it's a little weird to mix the two concerns, but it should probably be addressed in another PR.

**Review by geoand — APPROVED** [review]

**Pull request merged**
