### PR TITLE
Findability enhancement for landing page issue: Reactive doc search yields zero results

### PR DESCRIPTION
**Pull request by michelle-purcell**
**Fixes:**

When you select the `Reactive` category on the doc landing page, you get zero results.
image

**How?**
In this PR I added the `reactive`  keyword to the doc header `:categories:`where the keyword was mentioned >10 times OR featured in the main title or summary. Plus some other obviously missing categories. There might be others that slipped though the net.

### CODE REVIEW

**Comment by gsmet** [comment]
@michelle-purcell looks like you discovered my evil plan!

**Review by gsmet — COMMENTED** [review]
I think we need to discuss this with @cescoffier .

What I'm wondering is: should we mark everything that is reactive with this category, meaning most of our extensions or should we focus on guides that actually talks about the reactive bits. I will let @cescoffier decide on that one.

**Comment by cescoffier** [comment]
We should remove the reactive category

**Comment by michelle-purcell** [comment]
This changes in this PR are now reverted and I updated the list of doc categories to remove the `reactive` label as per this new PR : https://github.com/quarkusio/quarkus/pull/33992
@gsmet & @cescoffier  - Thanks for your help getting this to resolution :green_heart:

**Pull request closed without merging**
