### PR TITLE
Allow passing unsupported properties to Hibernate ORM

### LINKED ISSUE #12724: `hibernate.*` properties in Hibernate-ORM extension
**Description**
I am missing a way to configure `hibernate.event.merge.entity_copy_observer` ([see](https://docs.jboss.org/hibernate/stable/orm/userguide/html_single/Hibernate_User_Guide.html#pc-merge-gotchas)) from `application.properties`.
Using a `persistence.xml` I can set all kinds of properties but as I read, in terms of Quarkus it's "the old way" of doing things and not encouraged.

**Implementation ideas**
If I understand correctly, `quarkus.hibernate-orm.*` properties are global. So where I could set `hibernate.show_sql` per persistence unit before, I can now only set `quarkus.hibernate-orm.log.sql` for all datasources using Hibernate? It might be useful to set these properties per datasource. Also I think it'd be better to implement such properties in a pass-through way, so it's no question anymore whether Hibernate property X can be specified via `application.properties`.

### LINKED ISSUE #19129: hibernate-orm is missing some important Hibernate batch configuration options
### Description

See https://quarkus.io/guides/hibernate-orm for current list and https://vladmihalcea.com/how-to-batch-insert-and-update-statements-with-hibernate/ for additional needed options, e.g.
* `hibernate.order_inserts`
* `hibernate.order_updates`
* `hibernate.jdbc.batch_versioned_data`

Is it planned to add them?

### Workaround
Using `persistence.xml`

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #19129.

~~Creating as draft because this PR is based on #26126, which needs to be merged first.~~ => Done

In short, this adds a configuration property which can be used like this:

```
quarkus.hibernate-orm.unsupported-properties."hibernate.order_inserts" = true
```

IMO, the name makes it clear that such properties will not necessarily work, but the documentation makes it extra-clear:

```
     * Properties that should be passed on directly to Hibernate ORM.
     * Use the full configuration property key here,
     * for instance `quarkus.hibernate-orm.unsupported-properties."hibernate.order_inserts" = true`.
     *
     * [WARNING]
     * ====
     * Properties set here are completely unsupported:
     * as Quarkus doesn't generally know about these properties and their purpose,
     * there is absolutely no guarantee that they will work correctly,
     * and even if they do, that may change when upgrading to a newer version of Quarkus
     * (even just a micro/patch version).
     * ====
     *
     * Consider using a supported configuration property before falling back to unsupported ones.
     * If none exists, make sure to file a feature request so that a supported configuration property can be added to Quarkus,
     * and more importantly so that the configuration property is tested regularly.
```

To be even safer, setting such a property triggers a warning on startup:

> Persistence-unit [`<default>`] sets unsupported properties. These properties may not work correctly, and even if they do, that may change when upgrading to a newer version of Quarkus (even just a micro/patch version). Consider using a supported configuration property before falling back to unsupported ones. If there is no supported equivalent, make sure to file a feature request so that a supported configuration property can be added to Quarkus, and more importantly so that the configuration property is tested regularly. Unsupported properties being set: [hibernate.order_inserts]

Also, such properties have the lowest precedence. If Quarkus needs to set the same property as the user for whatever reason, Quarkus will win, and another warning will be displayed on startup:

> Persistence-unit [`<default>`] sets property 'hibernate.order_inserts' to a custom value through 'quarkus.hibernate-orm.unsupported-properties."hibernate.order_inserts"', but Quarkus already set that property independently. The custom value will be ignored.

I think that should address all of @Sanne's [concerns](https://github.com/quarkusio/quarkus/issues/19129#issuecomment-1141054626)?

### CODE REVIEW

**Comment by yrodiere** [comment]
Thanks.

> Perhaps document that such "unsupported properties" are not guaranteed to being applied - people should test their effect is working as intended.

Right. I think this should cover it?

```
     * [WARNING]
     * ====
     * Properties set here are completely unsupported:
     * as Quarkus doesn't generally know about these properties and their purpose,
     * there is absolutely no guarantee that they will work correctly,
     * and even if they do, that may change when upgrading to a newer version of Quarkus
     * (even just a micro/patch version).
     * ====
```

I didn't add a dedicated section to the documentation because I didn't want to encourage people to use this. If they really need it, it's in the configuration reference, and we can always point them to it.

**Comment by yrodiere** [comment]
I'll have a closer look at test failures on Monday; I suspect some tests are having side-effects on others...

**Comment by yrodiere** [comment]
The failing tests are unrelated, see #26251

**Review by gsmet — APPROVED** [review]

**Comment by Sanne** [comment]
Nice, thanks!

**Comment by kay-horst** [comment]
Hello! This is a very useful addition, thanks a lot!

**Pull request merged**
