### PR TITLE
Fix HttpHeaders.getAcceptableLanguages() on empty headers

### LINKED ISSUE #44253: Missing Accept-Language header results in an empty list with `getAcceptableLanguages()`
### Describe the bug

The Reactive Resteasy implementation of `jakarta.ws.rs.core.HttpHeaders` differs from the documentation. If a request contains no `Accept-Language` header and `HttpHeaders.getAcceptableLangauges()` is called, it will return an empty list.

The documentation specifies that a wildcard locale is returned, if no acceptable languages are specified: https://jakarta.ee/specifications/platform/10/apidocs/jakarta/ws/rs/core/httpheaders#getAcceptableLanguages().

### Expected behavior

Calling  `HttpHeaders.getAcceptableLangauges()` returns a list with a single wildcard locale, if no acceptable language header is given.

### Actual behavior

Calling  `HttpHeaders.getAcceptableLangauges()` returns an empty list, if no acceptable language header is given.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The reason for this issue is here: https://github.com/quarkusio/quarkus/blob/e158abcf0256ddfc8d6dd1eb9adf790f6e3235e8/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/headers/HeaderUtil.java#L296
Instead of returning an empty list, it should return a wildcard locale, like it is done here: https://github.com/resteasy/resteasy/blob/91f23fff5eca4b45fba4f45b938dca2fe5c0d16d/resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java#L232

### PR DESCRIPTION
**Pull request by koplas**
`jakarta.ws.rs.core.HttpHeaders.getAcceptableLanguages` requires that a wildcard locale is returned, if no acceptable language is specified. The previous behavior returned an empty list.

- Closes: #44253

### CODE REVIEW

**Review by FroMage — CHANGES_REQUESTED** [review]
Thanks for the contribution.

I don't think `Locale.ROOT` is a wildcard. Its javadoc says its language is set to the empty string, while a wildcard should have its language set to `*`.

Also, could you add a test for this? It will probably highlight this issue.

And I suspect the test failure may be related, somehow, it should be investigated.

Thanks a lot :)

**Comment by koplas** [comment]
> I don't think `Locale.ROOT` is a wildcard. Its javadoc says its language is set to the empty string, while a wildcard should have its language set to `*`.

Maybe the docs are a bit confusing, `Locale.ROOT` is a constant, as is `Locale.ENGLISH`.
The relevant code is [here](https://github.com/openjdk/jdk/blob/23fa1a33274d279a53fa6dde683900450561957b/src/java.base/share/classes/sun/util/locale/BaseLocale.java#L45) and [here](https://github.com/openjdk/jdk/blob/7f8450cc511e22e3183092edfa3a37b39f133cff/src/java.base/share/classes/java/util/Locale.java#L656). I did not find another wildcard locale other than `Locale.ROOT`.
> Also, could you add a test for this? It will probably highlight this issue.

This is a good idea; I will try to add a test.

> And I suspect the test failure may be related, somehow, it should be investigated.

Some failing tests seem to be I/O related. For example, one error looks like this:
```
Caused by: io.fabric8.maven.docker.access.hc.http.HttpRequestException: {"message":"Head \"https://registry-1.docker.io/v2/elastic/elasticsearch/manifests/8.15.0\": Get \"https://auth.docker.io/token?account=githubactions&scope=repository%3Aelastic%2Felasticsearch%3Apull&service=registry.docker.io\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"} (Internal Server Error: 500)
```
Maybe these tests can refactored to be more robust, but this should be handled in another pull request.

**Comment by geoand** [comment]
The test failure was transient, nothing to do with this PR

**Review by FroMage — APPROVED** [review]
LGTM. I do wonder why this is not tested in the TCK, but 🤷

**Review by geoand — APPROVED** [review]

**Pull request merged**
