### PR TITLE
Fix Redis dev mode

### LINKED ISSUE #18669: Redis breaks on live reload
### Describe the bug

**Using Quarkus 1.13.4.Final**
1. App uses a Redis connection (ReactiveRedisClient)
2. Perform a postman call to an endpoint that calls Redis in some way
3. Successful response
4. Make any change such that performing another call triggers live reload
5. Successful response

**Using Quarkus 2.0.1.Final or 2.0.2.Final**
1. App uses a Redis connection (ReactiveRedisClient)
2. Perform a postman call to an endpoint that calls Redis in some way
3. Successful response
4. Make any change such that performing another call triggers live reload
5. Request failed : java.lang.IllegalStateException: Client is closed

Somewhere between 1.13.4.Final and 2.0.1.Final, live reload breaks Redis. I've confirmed this by switching the versions in the pom.xml several times and 1.13.4.Final works great, but 2.0.1.Final+ breaks with absolutely no other changes (same local computer, same remote redis host, same application.properties, etc.)

### Expected behavior

Would expect live reload to not cause a fatal error in Redis.

### Actual behavior

```
ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-21) Request failed: java.lang.IllegalStateException: Client is closed
	at io.vertx.core.net.impl.NetClientImpl.checkClosed(NetClientImpl.java:175)
	at io.vertx.core.net.impl.NetClientImpl.connectInternal(NetClientImpl.java:218)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:206)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:185)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:191)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider.connect(RedisConnectionManager.java:136)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.connect(SimpleConnectionPool.java:240)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool$Acquire.lambda$execute$2(SimpleConnectionPool.java:526)
	at io.vertx.core.net.impl.pool.CombinerExecutor.pollAndExecute(CombinerExecutor.java:55)
	at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:43)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:231)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.acquire(SimpleConnectionPool.java:555)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.acquire(SimpleConnectionPool.java:559)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisEndpoint.requestConnection(RedisConnectionManager.java:331)
	at io.vertx.core.net.impl.pool.Endpoint.getConnection(Endpoint.java:41)
	at io.vertx.core.net.impl.pool.ConnectionManager.getConnection(ConnectionManager.java:54)
	at io.vertx.core.net.impl.pool.ConnectionManager.getConnection(ConnectionManager.java:44)
	at io.vertx.redis.client.impl.RedisConnectionManager.getConnection(RedisConnectionManager.java:301)
	at io.vertx.redis.client.impl.RedisClient.connect(RedisClient.java:32)
	at io.vertx.redis.client.impl.BaseRedisClient.send(BaseRedisClient.java:46)
	at io.vertx.redis.client.Redis.send(Redis.java:105)
	at io.vertx.redis.client.impl.RedisAPIImpl.send(RedisAPIImpl.java:54)
	at io.vertx.redis.client.RedisAPI.hgetall(RedisAPI.java:939)
	at io.vertx.mutiny.redis.client.RedisAPI.lambda$hgetall$53(RedisAPI.java:2601)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.vertx.AsyncResultUni.subscribe(AsyncResultUni.java:31)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:90)
	at io.quarkus.resteasy.reactive.server.runtime.filters.FilterUtil.handleUniResponse(FilterUtil.java:62)
	at security.SecurityFilter$GeneratedServerRequestFilter$securityFilter.filter(SecurityFilter$GeneratedServerRequestFilter$securityFilter.zig:67)
	at security.SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.filter$$superforward1(SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.zig:139)
	at security.SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass$$function$$4.apply(SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass$$function$$4.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at security.SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.filter(SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.zig:304)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveContainerRequestFilter.filter(ResteasyReactiveContainerRequestFilter.java:10)
	at security.SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.filter$$superforward1(SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.zig:124)
	at security.SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass$$function$$3.apply(SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass$$function$$3.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at security.SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.filter(SecurityFilter$GeneratedServerRequestFilter$securityFilter_Subclass.zig:204)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:40)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:8)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:132)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:47)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$4.handle(VertxHttpRecorder.java:336)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$4.handle(VertxHttpRecorder.java:314)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:116)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:99)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer_Subclass.checkPermission$$superforward1(HttpAuthorizer_Subclass.zig:175)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer_Subclass$$function$$1.apply(HttpAuthorizer_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer_Subclass.checkPermission(HttpAuthorizer_Subclass.zig:279)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:218)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:210)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2$1.onItem(HttpSecurityRecorder.java:128)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2$1.onItem(HttpSecurityRecorder.java:118)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:118)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:104)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.drain(UniMemoizeOp.java:152)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.onItem(UniMemoizeOp.java:172)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:29)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:76)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:104)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:51)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:49)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:350)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:346)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:55)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:428)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:425)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:150)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:132)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$3.handle(VertxHttpHotReplacementSetup.java:86)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$3.handle(VertxHttpHotReplacementSetup.java:77)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #18669

### CODE REVIEW

**Comment by gsmet** [comment]
@stuartwdouglas I'm not sure I understand why it didn't work before? I also wouldn't be surprised we use the exact same pattern elsewhere.

**Review by gsmet — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
There was an @PreDestroy on something that was not a CDI bean

**Comment by gsmet** [comment]
Ah yeah OK, I missed that. I think it used to be a CDI bean but got changed at some point. I wonder if we could detect than somehow and throw at least a warning if not an error. @mkouba WDYT?

**Comment by mkouba** [comment]
> I wonder if we could detect than somehow and throw at least a warning if not an error.

Detect what exactly? That there's a `@PreDestroy` declared on a class which is not a bean? We could definitely do that. But I'm not quite sure we should throw an error because it comes from `javax.annotation` and thus can be used by other frameworks and libraries, i.e. it's not CDI-only.

**Comment by stuartwdouglas** [comment]
Yea, it's not really practical. It's possible to have classes in extensions that are only sometimes registered as beans.

**Pull request merged**
