### PR TITLE
Remove or replace Pinning cases?

### PR DESCRIPTION
**Pull request by rolfedh**
It's unclear from this issue, Thread pinning with PostgreSQL JDBC driver #33337 , whether to simply remove the section or replace it with new information.

### CODE REVIEW

**Comment by cescoffier** [comment]
The text says 'old' version of the driver.

**Comment by rolfedh** [comment]
Thanks, @cescoffier. At this stage, the intention of the PR is to have a conversation about this specific content. Please suggest specific edits to resolve the issue, if needed. I have restored the content and used comments so that it is visible here. I'll remove the comments when we're done with revisions.

**Comment by cescoffier** [comment]
The content is accurate. The only thing I would add is a link to the blog post: https://quarkus.io/blog/virtual-thread-1/

**Review by cescoffier — CHANGES_REQUESTED** [review]
The content is accurate, do not remove it.

**Comment by rolfedh** [comment]
@cescoffier please review and approve so we can merge this PR. Thank you.

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
