### PR TITLE
Update SmallRye Config to 3.3.3

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by gsmet** [comment]
@ozangunalp `io.quarkus.it.vthreads.kafka.VirtualThreadTest.testAlertMessage` is a problem, it has been pretty unstable. I will disable it for now as it needs fixing.

**Comment by ozangunalp** [comment]
Thanks! I'll take a look

**Comment by gsmet** [comment]
@radcortez do we want a backport of this one?

**Review by gsmet — APPROVED** [review]

**Comment by radcortez** [comment]
> @radcortez do we want a backport of this one?

Not really required, but we could.

**Pull request merged**
