### PR TITLE
Downgrade commons-lang3 to 3.14.0 to avoid entropy issues

### PR DESCRIPTION
**Pull request by famod**
Details: https://github.com/quarkusio/quarkus/pull/41962#issuecomment-2293614340

Draft until it's clear whether or not this is the right way to go for now.
If not, then there should at least be a hint in the migration guide (I think).

### CODE REVIEW

**Comment by gsmet** [comment]
Hum. Awesome…

We are affected only starting 3.13?

Should we report the issue to Liquibase?

**Comment by famod** [comment]
> We are affected only starting 3.13?

It seems so.

> Should we report the issue to Liquibase?

There are two issues already (on which I left comments):
- https://github.com/liquibase/liquibase/issues/6156
- https://github.com/liquibase/liquibase/issues/6178

and there's an open PR: https://github.com/liquibase/liquibase/pull/6179

So there should be a "fixed" version of Liquibase sooner or later.

Question is: What else is (potentially) affected? E.g. https://github.com/search?q=repo%3Aquarkusio%2Fquarkus%20RandomStringUtils&type=code
Finding affected libs is much harder.

**Comment by gsmet** [comment]
I think it makes sense to merge this for now until the ecosystem has adapted.

Please mark it ready for review when if all is good on your side and I'll include it in the next 3.13 and 3.14.0.

**Review by gsmet — APPROVED** [review]

**Comment by mikethecalamity** [comment]
I see this is tagged as a backport to 3.13, any idea when that patch will be released?

**Comment by gsmet** [comment]
If all goes well, it will be released today.

**Pull request merged**
