### PR TITLE
Propagate Vert.x context on all ExecutorService methods for VirtualThreadExecutor

### LINKED ISSUE #38815: Support security identity propagation in VT
### Description

Here is a use case we expect to be supported:
```
@Inject
    MyComponent myComponent;

    @Inject
    @VirtualThreads
    ExecutorService vThreads;

    @Inject
    SecurityIdentity securityIdentity;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @RunOnVirtualThread
    @Path("/vt")
    @RolesAllowed("admin")
    public String getId() throws InterruptedException, ExecutionException {
        String name = securityIdentity.getPrincipal().getName();
        log.info("name = " + name);
        String nameV = vThreads.submit(() -> myComponent.getId()).get();
        log.info("nameV = " + nameVT);
        return name + "/" + nameV;
    }

...

@ApplicationScoped
public class MyComponent {

    private static final Logger log = Logger.getLogger(MyComponent.class);

    @Inject
    SecurityIdentity securityIdentity;

    // @ActivateRequestContext
    public String getId() {
        String nameVT = securityIdentity.getPrincipal().getName();
        log.info("nameVT = " + nameVT);
        return name;
    }
}
```

today, without the `ActivateRequestContext`, it fails because there is no request context when accessing the security identity.
and if we force the activation of the request context, there is no identity propagated from the calling thread : `getId()` returns an empty string.

the expectation is that there would be identity propagation.
an alternative (non ideal)  idea would be to re-authenticate inside `getId()`.
we intend to use this pattern on facades that receive an invocation, and need to call multiple downstream services in parallel, then aggregate all the information and return the result to the caller.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
Previous propagation only decorated execute method.

- Fixes #38815

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Looks good!

**Review by manovotn — APPROVED** [review]

**Comment by manovotn** [comment]
@vsevel Would you mind giving this branch/PR a spin with your use case?

**Review by cescoffier — APPROVED** [review]

**Comment by vsevel** [comment]
> @vsevel Would you mind giving this branch/PR a spin with your use case?

sure. it may take a little while though.

**Comment by vsevel** [comment]
I can confirm this works. I can now do:
```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @RunOnVirtualThread
    @Path("/vt")
    @RolesAllowed("myrole")
    public String getId() throws InterruptedException, ExecutionException {

        String name = securityIdentity.getPrincipal().getName();
        log.info("name = " + name);

        String name2 = vThreads.submit(() -> myComponent.getId()).get();

        log.info("name2 = " + name2);
        return "CALLER:" + name + "  /  CALLED:" + name2;
    }

...

@ApplicationScoped
public class MyComponent {

    private static final Logger log = Logger.getLogger(MyComponent.class);

    @Inject
    SecurityIdentity securityIdentity;

    public String getId() {
        String name = securityIdentity.getPrincipal().getName();
        log.info("name inside CALLED = " + name);
        return name;
    }
}

```

getting the principal name as expected. no need to activate a request context.
I am impressed @ozangunalp

**Comment by ozangunalp** [comment]
@vsevel thank you for testing it out. It was supposed to work this way from the beginning.

**Comment by cescoffier** [comment]
@ozangunalp I would propose to backport it, as for me it was a bug. WDYT?

**Comment by ozangunalp** [comment]
Yes, I think I need to revert the pattern variable change for the backporting.

**Pull request merged**
