### PR TITLE
Disable Vert.x TCCL management

### LINKED ISSUE #18299: Live-Reload not working with Hibernate Reactive
## Describe the bug

Live-reload doesn't work when using Hibernate Reactive.

## To Reproduce

Using the `hibernate-reactive-quickstart`, start it in dev-mode
 
1. hit endpoint `localhost:8080/fruits`
2. change the named query declared on `Fruit` from "SELECT f FROM Fruit f ORDER BY f.name" to "SELECT f FROM Fruit f ORDER BY f.id"
3. hit endpoint `localhost:8080/fruits`

This throws an exception, apparently we're not dropping the original classloader fully, and the entity class doesn't match the expected type.

### Quarkus version or git rev

2.0.0.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This breaks dev mode, and in general is not needed as Quarkus can
perform it's own TCCL management when required. It also provides a
slight performance boost.

Fixes #18299

### CODE REVIEW

**Comment by gsmet** [comment]
CI is very unhappy :).

**Comment by Sanne** [comment]
triggered a new CI run.

**Comment by stuartwdouglas** [comment]
There is definitely something wrong here. I will investigate today.

**Comment by Sanne** [comment]
There seems to be a pattern: all failed tests relate to Gradle. Even the CLI tests failing (at the end of the list) are the ones using gradle.

**Comment by stuartwdouglas** [comment]
@Sanne assuming CI passes this should be ready to go. 

Removing the TCCL management exposed some different CL leaks (e.g. around continuous testing), which ended up causing other tests to fail, which is why I have had to add CL leak fixes into the PR.

**Comment by Sanne** [comment]
sounds great @stuartwdouglas :)

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
FYI @vietj also has a PR improving the Vert.x SPI : 
 - https://github.com/eclipse-vertx/vert.x/pull/4037

I've tested it on top of your PR and it seems to work nicely; looking forward to the Vert.x 4.2 release so we can apply a little cleanups:
 - https://github.com/Sanne/quarkus/pull/77

**Comment by markusdlugi** [comment]
Great stuff, thanks a lot for the efforts guys!

**Pull request merged**
