### PR TITLE
Added "User-Agent" header to requests made to the Lambda Runtime API

### PR DESCRIPTION
**Pull request by msailes**
The value of the header will be in the format "quarkus/%s-%s" where the first position will be a description of the Java version and the second being the version of Quarkus.

There were no existing tests for the class I changed, I'd be happy to write some tests if given guidance.

Thanks,

### CODE REVIEW

**Comment by maxandersen** [comment]
this feels like something we should have config for that the various http clients will be able to use?

**Comment by msailes** [comment]
Hi @maxandersen,

Maybe, I couldn't see any http client in this module, so I followed the style which was existing.

**Comment by geoand** [comment]
> this feels like something we should have config for that the various http clients will be able to use?

I definitely agree

**Comment by gsmet** [comment]
I think having a configurable user agent for lambda would be a good first step. If we generalize it at some point we could use the more general one if not set.

@msailes I'm not sure we have some config root for lambda yet though. My guess would be to add something to `LambdaConfig`.
If you're still interested in finalizing this, I suppose you could ask for @matejvasek 's help if you have questions.

**Comment by matejvasek** [comment]
@gsmet @msailes  I didn't work much on aws lambda directly, I only did some work  wrt `Funqy` binding, AFAIK we don't configure user-agent there.

cc @patriot1burke

**Comment by patriot1burke** [comment]
Just curious, why the user agent?  Does the lambda event server want that information?

**Comment by msailes** [comment]
Yes, it helps us understand which frameworks are used.

**Comment by patriot1burke** [comment]
rebase, squash and i'll spin off CI.  Sorry this fell through the cracks.

**Comment by msailes** [comment]
No problem

**Comment by geoand** [comment]
Can you please rebase the PR onto `main` (instead of merging `main` into this PR)?

Thanks

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
