### PR TITLE
fix: non-heap memory pool metrics

### LINKED ISSUE #3710: [Smallrye Metrics] Some memory pool metrics are missing
**Describe the bug**
When using quarkus-smallrye-metric extension, some memory pool metrics are missing. Looking at the code in `SmallRyeMetricsRecorder.memoryPoolMetrics` it registers metrics for all pools. 

Running Java 11 I have the following pools
```
CodeHeap 'non-nmethods'
Metaspace
Compressed Class Space
G1 Eden Space
G1 Old Gen
G1 Survivor Space
CodeHeap 'non-profiled nmethods'
```

But only metrics for three pools are displayed:

```
    "memoryPool.usage.max;name=G1 Old Gen": 9825056,
    "memoryPool.usage.max;name=G1 Survivor Space": 16777216,
    "memoryPool.usage.max;name=G1 Eden Space": 157286400,
    "memoryPool.usage;name=G1 Eden Space": 0,
    "memoryPool.usage;name=G1 Survivor Space": 14680064,
    "memoryPool.usage;name=G1 Old Gen": 0,
```
All non-heap memory pools are missing.

**Expected behavior**
Metrics for all memory pools should be displayed when going to the /metrics endpoint.

**Actual behavior**
Some memory pool metrics are missing.

**To Reproduce**
1. Add quarkus-smallrye-metric extension to your project.
2. Go to /metrics endpoint.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.4" 2019-07-16
 - Quarkus version or git rev: master

### PR DESCRIPTION
**Pull request by loicmathieu**
This fixes #3710

### CODE REVIEW

**Comment by cescoffier** [comment]
@michalszynkiewicz can you have a look as it touches SmallRye Metrics.

**Comment by michalszynkiewicz** [comment]
looks good to me. 
@jmartisk would you also like to take a look?

**Review by jmartisk — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]
Approving based on the SME reviews

**Pull request merged**
