### PR TITLE
Vert.x extension - remove quarkus-jackson, add optional jackson-databind

### LINKED ISSUE #21139: JAX-RS minimal application (just quarkus-resteasy) is getting heavy, 120 jars vs 105 jars in 2.2.3.Final
### Describe the bug

JAX-RS minimal application (just `quarkus-resteasy`) is getting heavy, 120 jars in 2.4.0.Final vs 105 jars in 2.2.3.Final, 11% increase in disk usage of quarkus-app

As quarkus-resteasy is matured extension and one of the most used one the impact of this regression can be quite wide.

This increase in disk footprint has implications for runtime
 - more classes need to be loaded
 - => it takes longer to boot the application
 - => more Metaspace gets used to keep class metadata => RSS gets bigger

```
2.3.1.Final / 2.4.0.Final / 999-SNAPSHOT
 30M	app-jax-rs-minimal/target/quarkus-app
 120 JAR files

2.2.3.Final
 27M	app-jax-rs-minimal/target/quarkus-app
 105  JAR files
```

Attaching list of jar files from the app
 - [app-jax-rs-minimal-2.4.0.txt](https://github.com/quarkusio/quarkus/files/7458553/app-jax-rs-minimal-2.4.0.txt)
 - [app-jax-rs-minimal-2.2.3.txt](https://github.com/quarkusio/quarkus/files/7458555/app-jax-rs-minimal-2.2.3.txt)

Can be compared for example with `code --diff ~/Downloads/app-jax-rs-minimal-2.2.3.txt ~/Downloads/app-jax-rs-minimal-2.4.0.txt`
Generated using `find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | xargs basename | sort`

In the diff I see more `com.fasterxml.jackson.*` and `io.smallrye.reactive.*` artifacts in 2.4.0.Final.

### Expected behavior

Same / similar number of jar files and similar disk usage between Quarkus versions.

### Actual behavior

Increase in number of jar files and disk usage between Quarkus versions.
 - 120 jars in 2.4.0.Final vs. 105 jars in 2.2.3.Final
 - 11% increase in disk usage of quarkus-app

### How to Reproduce?

Get https://github.com/quarkus-qe/quarkus-startstop
```
mvn clean package -f app-jax-rs-minimal -Dquarkus.version=2.4.0.Final
du -cskh app-jax-rs-minimal/target/quarkus-app
find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | wc -l
```
```
mvn clean package -f app-jax-rs-minimal -Dquarkus.version=2.2.3.Final
du -cskh app-jax-rs-minimal/target/quarkus-app
find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | wc -l
```

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.0.Final and Quarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #21139

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
This requires a note in the migration guide as people using `quarkus-vertx` will have to add the Jackson extension manually now if I'm not mistaken (the core of the problem is that our extensions were depending on the internal quarkus-vertx-core before, that was not depending on Jackson).

**Comment by mkouba** [comment]
> This requires a note in the migration guide as people using `quarkus-vertx` will have to add the Jackson extension manually now if I'm not mistaken (the core of the problem is that our extensions were depending on the internal quarkus-vertx-core before, that was not depending on Jackson).

Yes, but only if they use the `com.fasterxml.jackson.databind` classes directly or rely on a JsonObject/JsonArray feature that requires `com.fasterxml.jackson.databind.ObjectMapper`.

Anyway, I have to investigate the CI failures first.

**Comment by mkouba** [comment]
The  JVM Tests - JDK 11 Windows failure is not related:
```
Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.2:jar (default-jar) on project quarkus-documentation: Error assembling JAR: Problem creating jar: Execution exception (and the archive is probably corrupt but I could not delete it): Java heap space 
```

**Review by geoand — APPROVED** [review]
Great!

**Pull request merged**
