### PR TITLE
Enhancements of mailer test coverage

### PR DESCRIPTION
**Pull request by rsvoboda**
Enhancements of mailer test coverage

  * Send a simple text email with non-ascii characters
  * Send a simple text email with human friendly address prefix
  * Send a simple HTML email with inline attachment

### CODE REVIEW

**Comment by rsvoboda** [comment]
M1 fail is env / machine issue

Native fail is connected to:
```java
        // present in core/deployment/src/main/resources/META-INF/branding/logo.png
        InputStream in = this.getClass().getClassLoader().getResourceAsStream("META-INF/branding/logo.png");
```

I'm trying `quarkus.native.resources.includes=META-INF/branding/logo.png` but no luck, probably because the resource is in dependency jar and not in the project?!
Any tips on how to include resource that is in dependency jar into the native image?

**Comment by rsvoboda** [comment]
@Karm / @galderz / @zakkak any tips for ^^^

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Hum, the CI is failing.

**Comment by gsmet** [comment]
The resource is in a deployment package so not available at runtime. So I wouldn’t expect things to work when trying to include in the native image.

**Comment by rsvoboda** [comment]
PR updated, cc @cescoffier

**Comment by rsvoboda** [comment]
M1 - Failing after 7s  :/

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
