### PR TITLE
TemporalParamConverter returns null if it has to convert empty string

### LINKED ISSUE #40833: Quarkus REST: setting a `LocalDate` parameter to an empty value results in a 400 instead of a `null` parameter
Given this endpoint:

```
@POST
public void foo(@RestForm LocalDate date){}
```

And this payload:
```
date=
```

I get a 400 from Quarkus REST. Probably because `TemporalParamConverter` doesn't handle empty strings? I think it should be set to a `null` value. I also assume other temporal types have the same issue.

### PR DESCRIPTION
**Pull request by blazmrak**
Closes #40833

### CODE REVIEW

**Comment by blazmrak** [comment]
I'm having problem getting the `extensions/resteasy-reactive/rest/deployment/` test suite to run to add the tests for temporal types. It fails with `No config found for interface io.quarkus.resteasy.reactive.common.runtime.ResteasyReactiveConfig` for each test. I run the suite with `./mvnw test -f extensions/resteasy-reactive/rest/deployment/`. Am I missing something obvious?

**Comment by gsmet** [comment]
Have you installed the artifacts locally with `./mvnw -Dquickly`?

**Comment by blazmrak** [comment]
> Have you installed the artifacts locally with `./mvnw -Dquickly`?

Ah... It was in my face... It failed the first time for Gradle Model. I was going to deal with it after I got everything working for the PR :D I ran it again now and it seems like I need JDK 17 installed for it to run. I'll fix this tomorrow and try again. Thanks!

**Comment by blazmrak** [comment]
@FroMage @geoand I was updating the tests, when I realized that just adding `String.isEmpty()` check to the converter and returning null would just make it a footgun. I have added a try/catch around the `delegate.convert()` in `OptionalConverter` and return empty if it conversion throws when converting an empty String.

This breaks custom converters that throw on empty string and where users also use Optional as a parameter and expect to throw and not handle Optional on empty string. My guess would be that this is very uncommon.

The upside is, that this applies to all types, not just temporal - e.g. `@RestForm Optional<Integer>` would now work as well.

**Review by FroMage — CHANGES_REQUESTED** [review]
This feels wrong to me. It special-cases `Optional`, and does not solve the issue for any type that is not optional. Indeed the tests you added expect a `400` for a `null` `Date`.

In my opinion there are two alternatives possible:

- Either we decide that `foo=` is equivalent to `foo` not being set, and any value extracted for it should be `null`, and we cannot make the difference between passing an empty string and not passing any value, in which case it's `ResteasyReactiveRequestContext.get*Param()` should not return empty strings, but `null` values, and then every further `ParamConverter` will work properly, or
- We declare that `foo=` should set it to an empty string (as is the case now, as opposed to a `null` value) and so every `ParamConverter` that exists has to handle empty strings specially, such as temporal values.

I'm not entirely sure what to do, TBH. Perhaps @geoand has an opinion?

**Comment by blazmrak** [comment]
> This feels wrong to me. It special-cases `Optional`, and does not solve the issue for any type that is not optional. Indeed the tests you added expect a `400` for a `null` `Date`.

I was about to disagree, because I thought I was being smart with null safety, but I completely forgot, that if no parameter is set, it will be null anyways.

The problem of making `foo=` null is that you might have a required field that can be an empty string, that would break. This feels like bad implementation, but someone might rely on this?

The problem with `foo=` being an empty string is that we likely don't control every param converter. I don't think that e.g. `Integer` has a param converter as it relies on Jakarta standard to use `valueOf` I'm guessing although I'm not familiar with the codebase and could be completely wrong :sweat_smile:

**Comment by FroMage** [comment]
Yeah, for strings, we might be able to use an empty string to disinguish:

- `<nothing>` →`@RestQuery String foo` will be `null` because it not set in the request
- `foo=` →  `@RestQuery String foo` will be `""` (empty string) because it is set to empty

So, really, IMO the interesting difference is between:

- Was set to _nothing_ (either `null` or `""` (empty string)
- Was not set

Note that this problem only happens for strings, because we have confusion between `null` (not set) and `""` (empty string) (set to empty value).

This does not apply to integers, booleans or any other type where the empty value is distinct from the "not set" value.

For example, given an unboxed integer:

- `<nothing>` →`@RestQuery int foo` will be `0` because it not set in the request
- `foo=` →  `@RestQuery int foo` will be `0` because it is set to empty

And given a boxed integer:

- `<nothing>` →`@RestQuery Integer foo` will be `null` because it not set in the request
- `foo=` →  `@RestQuery Integer foo` will be `null` because it is set to empty

So I think that `String` is a very special case, and every other type will not be able to make the difference between "not set" and "set to empty value", because in both cases they should get a `null` or zero value (for primitives).

Therefore, I suggest we turn both `<nothing>` and `foo=` into `null` for `String`, `LocalTime` and in fact every non-primitive, and the zero-value for primitives.

This is what makes the most sense. And if people want to differenciate between `<nothing>` and `foo=` we will need a different API.

**Comment by blazmrak** [comment]
> So I think that String is a very special case

Yep, completely agree. There are custom converters as well, but I would be surprised if anyone is relying on this behavior.

 > Therefore, I suggest we turn both <nothing> and foo= into null for String, LocalTime and in fact every non-primitive, and the zero-value for primitives.

This makes the most sense to me as well. I'll make the changes shortly.

**Comment by blazmrak** [comment]
I have done the changes. I have two more questions:

1. Do we leave the array parameters (single = false) as is, or do we make them null as well? Leaving them as is would make `List<String>` params be null instead of empty, however it would make e.g. `List<Integer>` not throw. I'm leaning towards not returning null for !single. 
2. I don't like where the tests for this change are, but I have no idea where else to put them. Do I make another test class or did I miss some place where RequestContext is tested or are you fine with where they are? I don't know the codebase, but to me it looks like the tests are meant to be testing the converter :smile:

**Comment by FroMage** [comment]
> 1. Do we leave the array parameters (single = false) as is, or do we make them null as well? Leaving them as is would make `List<String>` params be null instead of empty, however it would make e.g. `List<Integer>` not throw. I'm leaning towards not returning null for !single.

I think we should make the array parameters empty collections, if it's not already the case. I'm not sure how it makes sense to turn `foo=&foo=` into collections of two empty elements, especially given it can't work for primitives, and the previous reasoning that we applied to `String`.

> 2. I don't like where the tests for this change are, but I have no idea where else to put them. Do I make another test class or did I miss some place where RequestContext is tested or are you fine with where they are? I don't know the codebase, but to me it looks like the tests are meant to be testing the converter 😄

That's fine IMO.

**Comment by blazmrak** [comment]
> I think we should make the array parameters empty collections, if it's not already the case. I'm not sure how it makes sense to turn foo=&foo= into collections of two empty elements, especially given it can't work for primitives, and the previous reasoning that we applied to String.

What do we do with `foo=&foo=1`? If I understood you correctly, you would expect it to be become `[1]` and not `[null, 1]`.

**Comment by FroMage** [comment]
> What do we do with `foo=&foo=1`? If I understood you correctly, you would expect it to be become `[1]` and not `[null, 1]`

Yeah, this is the only thing that makes sense for arrays of primitives anyways.

**Comment by blazmrak** [comment]
It took me more than I'm willing to admit, but I have confirmed this... As soon as I return null for `val.isEmpty()` in `getQueryParameter`, the tests for cookies fail. TCK tests send empty `todo=` somewhere and expect to get back `other stuff` :smile: https://github.com/quarkusio/resteasy-reactive-testsuite/blob/c8b7402a9fdd6aa4e267a6e9e12d936b246e2a75/tests/src/test/java/com/sun/ts/tests/jaxrs/ee/rs/cookieparam/JAXRSClient0143.java#L368

Do I make a PR to TCK as well? This needs to be changed to include the same response as the else block https://github.com/quarkusio/resteasy-reactive-testsuite/blob/c8b7402a9fdd6aa4e267a6e9e12d936b246e2a75/tests/src/test/java/com/sun/ts/tests/jaxrs/ee/rs/cookieparam/CookieParamTest.java#L89

**Comment by blazmrak** [comment]
> yeah, it's not right that a query param change would break cookie tests. Thta's just bad testing.

Well, it was just a defensive branch that was never hit. I opened the pull request there: https://github.com/quarkusio/resteasy-reactive-testsuite/pull/8

Once that is merged, the test should go through.

**Comment by cescoffier** [comment]
@blazmrak Can you rebase, the other PR has been merged.

**Comment by blazmrak** [comment]
@cescoffier I have rebased the changes. Sorry, I forgot about this PR. It was a while ago, but I think I still have to implement the handling of the arrays. I'll take a look over this PR again today and make the changes if necessary.

**Comment by cescoffier** [comment]
@FroMage any idea about the TCK?

**Comment by FroMage** [comment]
> Do I submit another PR to TCK suite? 

Sure.

**Comment by blazmrak** [comment]
@FroMage I have submitted a PR

**Comment by FroMage** [comment]
I've restarted the tests

**Comment by blazmrak** [comment]
@FroMage Same failure... The commit hash has to be updated to `2b263617d93e3f161bf092bb6425405e9d3c01d0` probably, unless the pipeline does it automatically somehow?

**Review by FroMage — APPROVED** [review]

**Comment by geoand** [comment]
I think there was an update to the TCK in the meantime, that would be nice to include

**Comment by blazmrak** [comment]
> I think there was an update to the TCK in the meantime, that would be nice to include.

@geoand This PR should be on the latest commit https://github.com/quarkusio/resteasy-reactive-testsuite/commit/2b263617d93e3f161bf092bb6425405e9d3c01d0

```
<resteasy-reactive-testsuite.repo.ref>2b263617d93e3f161bf092bb6425405e9d3c01d0</resteasy-reactive-testsuite.repo.ref>
```

**Comment by geoand** [comment]
The latest commit on the testsuite is 0231b4a4c070d4899216bd6aa77c9a30f2129dd3 from a few days ago

**Comment by blazmrak** [comment]
@geoand that is my commit, `2b26361` is your merge commit to main. Without that patch, TCK was failing the CI. This PR only passed CI after I updated the TCK commit hash here: https://github.com/quarkusio/quarkus/pull/42468/commits/f11984874e410ab9666b895895d1e0057d423d13

**Comment by geoand** [comment]
Ah, good point!

**Pull request merged**
