### PR TITLE
Remove unnecessary reactive routes dependency in JWT extension

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
cc @franz1981

**Comment by sberyozkin** [comment]
Hey @geoand, this is fine with me, but since this is a supported extension, I can expect the guys asking me to explain :-).
Do we lose anything at all with losing this reactive routes extension ? If both JAX-RS endpoints and Vert.x routes can be supported then it is not really a breaking change

**Comment by geoand** [comment]
Hey @sberyozkin 

The reason for this change is to cut down on the number of classes needed when JWT is around, as Reactive Routes is not really necessary - simply Vert.x HTTP does the trick.
The reason I added the breaking change label is because there might be a few application that don't include Reactive Routes explicitly, but nevertheless use it in user code.

**Comment by sberyozkin** [comment]
Thanks @geoand I think it is very reasonable to expect users not to depend on `smallrye-jwt` for the reactive routes capability, let me approve, and thanks for analyzing, but I'd like to ask @maxandersen to confirm we can do it

**Review by sberyozkin — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
> Thanks @geoand I think it is very reasonable to expect users not to depend on `smallrye-jwt` for the reactive routes capability, let me approve, and thanks for analyzing, but I'd like to ask @maxandersen to confirm we can do it

Thanks!

**Review by gsmet — APPROVED** [review]
This makes perfect sense but let's add a small note in the migration guide please.

**Comment by geoand** [comment]
YW!

**Pull request merged**
