### PR TITLE
Introducing Quarkus Guru

### PR DESCRIPTION
**Pull request by Gurubaseio**
The Git history of the previous [PR](https://github.com/quarkusio/quarkus/pull/45099) was mistakenly corrupted, so I created a new one.

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
@maxandersen @gsmet @cescoffier - happy to merge ?

**Review by gsmet — COMMENTED** [review]
I must admit I wasn't exactly excited about this (mostly because why this one and not something else?) but given the quality of the answers , I think we should give it a try nut we need @cescoffier and @maxandersen approval.

Could we use the `blue` color instead of a specific one though? I would like to avoid this the badges looking like a Christmas tree.

I need to fix the Develocity one also.

Just replacing the color code with `blue` will do it and make things consistent.

Thanks!

**Comment by Gurubaseio** [comment]
> I must admit I wasn't exactly excited about this (mostly because why this one and not something else?) but given the quality of the answers , I think we should give it a try nut we need @cescoffier and @maxandersen approval.
> 
> Could we use the `blue` color instead of a specific one though? I would like to avoid the badges looking like a Christmas tree.
> 
> I need to fix the Develocity one also.
> 
> Just replacing the color code with `blue` will do it and make things consistent.
> 
> Thanks!

Happy to hear that you like it. I also fixed the colors, including Develocity.

**Comment by maxandersen** [comment]
continuing from the previous pr - would quarkiverse be able to be there?

and right now when i ask a question I end up with 404 page not found (https://gurubase.io/not-found) ?

**Comment by maxandersen** [comment]
about merging it - then i see this as our use of javadoc.io - makes it easier to share docs and if gurubase will do this for quarkus and quarkiverse then no harm in linking to it - but lets have it not give 404 first :)

**Comment by maxandersen** [comment]
fyi, I openend claim request as suggested at https://github.com/getanteon/gurubase/issues/17

**Comment by kursataktas** [comment]
There was a temporary issue, but it has been resolved now.

I believe @phillip-kruger added quarkiverse as a datasource since I assigned him as a maintainer of Quarkus Guru.
image

I also assigned quarkusio@gmail.com as a maintainer.

**Comment by maxandersen** [comment]
sounds good @kursataktas  - I can see the results and the index now includes quarkiverse stuff which is amazing.

I'll go ahead an merge this as its working now.

I asked on discord on how to get the quarkus guru landing page to include mention of it is also indexing youtube and quarkiverse but we can fix that as it goes.

**Pull request merged**
