### PR TITLE
fix injection of @ConfigProperty OptionalInt

### LINKED ISSUE #11362: ambiguous resolution for @Inject @ConfigProperty OptionalInt
**Describe the bug**
When use MP Config injection with an `OptionalInt` type, like this:

```java
@Inject
@ConfigProperty(name = "my.config.property")
OptionalInt foo;
```

I get an error when I try to run the app (be it `mvn quarkus:dev`, running a test or just `mvn clean package -DskipTests`):

```
javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type java.util.OptionalInt and qualifiers [@ConfigProperty(name = "my.config.property")]
	- java member: org.acme.ExampleResource#foo
	- declared on CLASS bean [types=[org.acme.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	- available beans:
		- PRODUCER METHOD bean [types=[java.lang.Object, java.util.OptionalInt], qualifiers=[@ConfigProperty, @Any], target=java.util.OptionalInt produceOptionalIntConfigProperty(javax.enterprise.inject.spi.InjectionPoint ip), declaringBean=io.smallrye.config.inject.ConfigProducer]
		- SYNTHETIC bean [types=[java.util.OptionalInt], qualifiers=[@org.eclipse.microprofile.config.inject.ConfigProperty, @Any], target=n/a]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:502)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:226)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:120)
	...
```

**Expected behavior**
Injecting `@ConfigProperty OptionalInt` works.

**Actual behavior**
Injecting `@ConfigProperty OptionalInt` doesn't work.

**To Reproduce**
1. Generate a new project using code.quarkus.io.
2. To the generated JAX-RS resource, paste the snippet of code mentioned above.
3. Run `mvn clean package` and observe a test failure.

**Configuration**
none

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
```
Linux argondie 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```
 - GraalVM version (if different from Java):  N/A
 - Quarkus version or git rev: 1.6.1.Final, but same behavior occurs on today's `master` branch
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/lthon/software/apache-maven
Java version: 11.0.8, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-112-generic", arch: "amd64", family: "unix"
```

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #11362.

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft to let CI run in my fork, and also because some of the tests I modified fail now and I need to discuss that with someone :-)

**Comment by Ladicek** [comment]
Removed all the test modifications I did previously, because they were in the `@ConfigProperties` test suite. Instead added a new test just for `@ConfigProperty`.

**Comment by Ladicek** [comment]
CI passed in my fork.

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]
Thanks 👍

**Pull request merged**
