### PR TITLE
Do not include in the list of property names Kubernetes config fallbacks

### LINKED ISSUE #35722: Since quarkus 3.3.0 a WARN message unrecognized configuration key "quarkus.kubernetes.route.expose" is logged
### Describe the bug

WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.kubernetes.route.expose" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Have the following property set:

`quarkus.openshift.route.expose=true`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #35722

### CODE REVIEW

**Comment by gsmet** [comment]
@radcortez you confirm that it wasn't only a warning logged but the config being fully ignored? Asking that because if you only fixed the warnings, I think we have something else lurking around.

**Comment by radcortez** [comment]
> @radcortez you confirm that it wasn't only a warning logged but the config being fully ignored? Asking that because if you only fixed the warnings, I think we have something else lurking around.

I can have another look, but I'm pretty sure it is related to the fallback rules we added in https://github.com/quarkusio/quarkus/issues/35722.

Each fallback rule also rewrites the corresponding property name as a possible property in the list of property names. So for instance when we write a rule to fallback openshift properties to kubernetes as in:

```
if (name.startsWith("quarkus.openshift.")) {
   return "quarkus.kubernetes." + name.substring(18
}
```

It means that the property `quarkus.openshift.route.expose` will be rewritten to `quarkus.kubenetes.route.expose`, and both versions are include in the list of property names. So when we iterate and search for unknowns we find the property `quarkus.kubenetes.route.expose`, which is not mapped in the Kubernetes config.

I think we didn't properly consider all the ramifications of the request in https://github.com/quarkusio/quarkus/issues/34025, (which I am to blame). The true is that we are trying to force a hierarchy (which config supports), but the Kubernetes config is not mapped that way: https://github.com/quarkusio/quarkus/issues/35608#issuecomment-1701212708.

**Comment by radcortez** [comment]
> Asking that because if you only fixed the warnings, I think we have something else lurking around.

So the fix did not fix the warning, is just skipping the implementation provided by `FallbackConfigSourceInterceptor` to iterate names (which adds both the original property and the rewritten fallback property).

Ideally, this should all be integrated and the unknown reporting feature should be aware that this is a fallback and ignore it (which I already wanted to implement).

**Comment by gsmet** [comment]
Hmmm. This is annoying. I will try to deploy my app to OpenShit with this patch and see how it goes. If it doesn’t fix the fact that the deployment doesn’t work, we might have to revert that patch.

**Comment by radcortez** [comment]
Hum, but is the deployment not working just with the warning?

**Comment by radcortez** [comment]
So, I've tried this with a local Quarkus build based on 3.2.x, plus PR https://github.com/quarkusio/quarkus/pull/34487.

With 3.2.5.Final (with Openshift extension and the property `quarkus.openshift.route.expose=true`)

```console
🌀 java -jar target/quarkus-app/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-09-08 12:16:12,435 INFO  [io.quarkus] (main) config-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.5.Final) started in 0.627s. Listening on: http://0.0.0.0:8080
2023-09-08 12:16:12,460 INFO  [io.quarkus] (main) Profile prod activated.
2023-09-08 12:16:12,460 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, resteasy-reactive, smallrye-context-propagation, vertx]
```

With 3.2 branch plus https://github.com/quarkusio/quarkus/pull/34487:

```console
🌀 git log
commit 15ef6359a73955b5aacb00f75d8d01c24b0befab (HEAD -> 3.2)
Author: Roberto Cortez <radcortez@yahoo.com>
Date:   Wed Aug 2 11:47:42 2023 +0100

    Fallback specialized kubernetes config to vanilla kubernetes

commit 925742d8465c02322488f5d1d94630f0ebfedcb8 (origin/3.2)
Merge: d24c8d19c1e 87761c1869c
Author: Guillaume Smet <guillaume.smet@gmail.com>
Date:   Mon Sep 4 11:31:27 2023 +0200

    Merge pull request #35652 from jmartisk/gradle-8.2

    [3.2] Bump to Gradle 8.2.1

🌀 java -jar target/quarkus-app/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-09-08 12:43:42,974 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.kubernetes.route.expose" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2023-09-08 12:43:43,486 INFO  [io.quarkus] (main) config-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.999-SNAPSHOT) started in 0.787s. Listening on: http://0.0.0.0:8080
2023-09-08 12:43:43,487 INFO  [io.quarkus] (main) Profile prod activated.
2023-09-08 12:43:43,488 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, resteasy-reactive, smallrye-context-propagation, vertx]
```

With the fix:

```console
🌀 git log
commit 41a6e556894de174ffb95536bce487a412aee164 (HEAD -> 3.2)
Author: Roberto Cortez <radcortez@yahoo.com>
Date:   Thu Sep 7 00:22:26 2023 +0100

    Do not include in the list of property names Kubernetes config fallbacks

commit 15ef6359a73955b5aacb00f75d8d01c24b0befab
Author: Roberto Cortez <radcortez@yahoo.com>
Date:   Wed Aug 2 11:47:42 2023 +0100

    Fallback specialized kubernetes config to vanilla kubernetes

commit 925742d8465c02322488f5d1d94630f0ebfedcb8 (origin/3.2)
Merge: d24c8d19c1e 87761c1869c
Author: Guillaume Smet <guillaume.smet@gmail.com>
Date:   Mon Sep 4 11:31:27 2023 +0200

    Merge pull request #35652 from jmartisk/gradle-8.2

    [3.2] Bump to Gradle 8.2.1

🌀 java -jar target/quarkus-app/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-09-08 12:40:25,418 INFO  [io.quarkus] (main) config-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.999-SNAPSHOT) started in 0.647s. Listening on: http://0.0.0.0:8080
2023-09-08 12:40:25,445 INFO  [io.quarkus] (main) Profile prod activated.
2023-09-08 12:40:25,445 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, resteasy-reactive, smallrye-context-propagation, vertx]
```

**Comment by gsmet** [comment]
I will try but the deployment was not working at all. It looked as if the configuration was ignored. I will retry with this patch in.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
