### PR TITLE
Add default values for Hibernate ORM properties

### LINKED ISSUE #12654: Document Hibernate config property default values
Some of the Quarkus Hibernate config properties don't have a default value and as a result the corresponding Hibernate property will not be set and retain its own default value. IMHO this makes sense, but I think it would also make sense if the default values were documented on the Quarkus side, so that developers don't need to first find the corresponding Hibernate docs. Two examples:

* [query-plan-cache-max-size](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.query.query-plan-cache-max-size): Here the default value in Hibernate is `2048`
* [default-null-ordering](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.query.default-null-ordering): Here the default value in Hibernate is `none`

Unfortunately I don't think Hibernate has any Java constants declaring the default values of the various properties, otherwise these could be referenced by `@ConfigItem#defaultValue`.

### PR DESCRIPTION
**Pull request by xumk**
Fixes #12654 add default value for queryPlanCacheMaxSize and defaultNullOrdering

### CODE REVIEW

**Comment by xumk** [comment]
@gastaldi Can you please rerun CI. I don't see error in log and don't know why it failed

**Comment by gastaldi** [comment]
This is the error in CI: 
```
Imports are not sorted in /home/runner/work/quarkus/quarkus/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
```

You need to run `mvn process-sources` in your branch

**Comment by xumk** [comment]
@gastaldi oh, thanks

**Comment by xumk** [comment]
@gsmet @Sanne review please

**Review by Sanne — APPROVED** [review]

**Pull request merged**
