### PR TITLE
Update protobuf-java to 3.19.2

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by famod** [comment]
We could add it to dependabot, no?

**Comment by gsmet** [comment]
I refrained from doing it because IIRC, this is a very sensitive dependency. I upgraded it because of a security issue.

**Comment by gsmet** [comment]
@cescoffier WDYT about ^

**Comment by famod** [comment]
We could play it save and only enable patch/micro updates via dependabot.

**Pull request merged**
