### PR TITLE
The SmallRye JWT extension depends on Undertow.

### PR DESCRIPTION
**Pull request by cescoffier**
It fixes the JWT quickstart.

### CODE REVIEW

**Comment by cescoffier** [comment]
The dependency comes from SmallRye JWT.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by sberyozkin** [comment]
@stuartwdouglas @cescoffier this will disconnect smallrye-jwt from the vertx-based OIDC ? Or is it done until smallrye-jwt extension is rebuilt not to use Undertow ?

**Comment by sberyozkin** [comment]
I've referred to it at #4226

**Comment by gsmet** [comment]
Same question as Sergey. Not very excited about this change. 

We can’t make it work with vert.x?

**Comment by cescoffier** [comment]
The new security architecture won't use SmallRye JWT. JWT is going to be handled by the quarkus security components. 

If you want to make SmallRye JWT work with the new architecture (which was not the goal) you would need to rewrite it.

**Comment by stuartwdouglas** [comment]
Note that you can still inject stuff as per the MP JWT spec at the moment when using Vert.x Keycloak, it just does not use Smallrye to verify the token.

**Comment by cescoffier** [comment]
Will try to find another way to make the quickstart pass without these changes. 
Might need a complete rewrite.

**Pull request closed without merging**
