### PR TITLE
Replace oidc auth google screenshots with generic ones

### PR DESCRIPTION
**Pull request by rghara**
Replaces oidc auth google screenshots with generic ones

### CODE REVIEW

**Comment by rghara** [comment]
Hi @sberyozkin,
Next PR replaces google screenshots

**Comment by sberyozkin** [comment]
Hi @rghara Thanks very much for keeping going with these updates, I've updates the subject description only as this PR won't fix the linked issue yet.

It looks good to me, but I'd like to ask you to shrink some images, users don't need the whole page of the current Google OAuth wizard screen, like how to manage billings or where to learn more about Google cloud, please try to cut some space on the right, the images sizes will also be significantly smaller.

Thanks.

**Comment by sberyozkin** [comment]
@rghara Please also experiment with the the screen resolution, as I can see that the identical content from the replaced image is now represented by an image which looks like it is twice as large as the original one. I guess it is not critical and may be easier to read, but indeed, please try to shrink them a bit and also cut the redundant empty or unrelated content on the right,

Thanks

**Comment by rghara** [comment]
@sberyozkin closing this to create a new PR. For some reason the bot fails always to update my branch.

**Pull request closed without merging**
