### PR TITLE
Add xml-apis:xml-apis as parentFirstArtifact to io.quarkus:quarkus-core

### LINKED ISSUE #7359: Build error when using quarkus-tika and quarkus-narayana-jta extensions, provider com.ctc.wstx.stax.WstxInputFactory not found
Build error, provider `com.ctc.wstx.stax.WstxInputFactory` not found when using quarkus-tika and quarkus-narayana-jta extensions.

```
rm -rf fooBar
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=io.quarkus.qe \
    -DprojectArtifactId=fooBar \
    -DprojectVersion=1.0.0-SNAPSHOT \
    -DplatformArtifactId=quarkus-bom \
    -DclassName="io.quarkus.qe.MyResource" \
    -Dextensions="quarkus-tika,quarkus-narayana-jta"
mvn -f fooBar/pom.xml clean verify
```
```
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#build threw an exception: javax.xml.stream.FactoryConfigurationError: Provider com.ctc.wstx.stax.WstxInputFactory not found
	at javax.xml.stream.XMLInputFactory.newInstance(Unknown Source)
	at com.arjuna.common.util.propertyservice.PropertiesFactoryStax.loadFromXML(PropertiesFactoryStax.java:46)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.loadFromFile(AbstractPropertiesFactory.java:149)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getPropertiesFromFile(AbstractPropertiesFactory.java:102)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.initDefaultProperties(AbstractPropertiesFactory.java:195)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getDefaultProperties(AbstractPropertiesFactory.java:62)
	at com.arjuna.common.util.propertyservice.PropertiesFactory.getDefaultProperties(PropertiesFactory.java:48)
	at io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor.build(NarayanaJtaProcessor.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Workaround is to add `com.fasterxml.woodstox:woodstox-core` to the deps of the app.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes the issue reported in https://groups.google.com/g/quarkus-dev/c/_Cs-ga4zsWM/m/ZMZAIhCjBgAJ

Fixes #7359

### CODE REVIEW

**Comment by geoand** [comment]
Do we definitely want this parentFirst artifact in the core or perhaps only in the kubernetes extension where the problem was reported?

**Comment by aloubyansky** [comment]
Right, it could be moved to the kubernetes one instead to fix the reported use-case. I added it to the core to potentially fix similar issues for other extensions.

**Comment by geoand** [comment]
I'm fine with it either way. @stuartwdouglas WDYT?

**Comment by sberyozkin** [comment]
Maybe it can fix this one as well : #7359 ?

**Comment by aloubyansky** [comment]
@sberyozkin I can reproduce the issue you referenced with 1.9.0.FInal but not the current master.

**Comment by sberyozkin** [comment]
@aloubyansky this is a nice surprise :-), let me try too :-)

**Comment by sberyozkin** [comment]
@aloubyansky Thanks Alexey, I wish all more open issues will get self-resolved like this :-)

**Comment by gsmet** [comment]
If it's a global fix, it should be in core.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
