### PR TITLE
Fix configuration processing to also process superclasses

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@dmlloyd Thanks, this fix looks good on my branch

**Comment by radcortez** [comment]
@dmlloyd The code itself seems fine, but it is failing the formatter :)

**Review by radcortez — APPROVED** [review]

**Comment by dmlloyd** [comment]
Interesting, I only made one line of change in the last push.  Somehow that one line was formatted wrong :)

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
+1

**Review by gsmet — APPROVED** [review]

**Pull request merged**
