### PR TITLE
Add DefaultExtensionRegistryTest

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]
Are you testing against the actually released platforms instead of the mocks?

**Comment by aloubyansky** [comment]
I think unless there is a strong reason to pull actually released platforms the tests should be using local mocks.

**Comment by gastaldi** [comment]
> Are you testing against the actually released platforms instead of the mocks?

No, only mocks. I am using `QuarkusTestPlatformDescriptorLoader`

**Comment by aloubyansky** [comment]
Good, thanks, didn't see them among the resources.

**Pull request merged**
