### PR TITLE
Add traceresponse header to HTTP responses

### PR DESCRIPTION
**Pull request by wottop**
https://github.com/quarkusio/quarkus/issues/11931

### CODE REVIEW

**Comment by sberyozkin** [comment]
Should it be done in dev mode only ?

**Review by brunobat — CHANGES_REQUESTED** [review]
Thanks for the PR.
Please check this comment for more details on what to implement in the PR: https://github.com/quarkusio/quarkus/issues/11931#issuecomment-1705254135

**Comment by brunobat** [comment]
@wottop Are you thinking on continuing the work on this issue?
Some considerations:
1. The response header should not be inserted by default. A new property is needed with default value to false.
2. This needs to be developed for quarkus-rest quarkus-resteasy-classic and vertx routes.
3. We need tests.

**Comment by cescoffier** [comment]
@brunobat What should we do here?

**Comment by brunobat** [comment]
Like it is, we cannot accept the PR and because @wottop hasn't addressed the comments I'm closing the PR. 
We can re-open it if we hear any news.

**Comment by dastrobu** [comment]
I tried that code in one of my projects. Unfortunately it also won't address resources retiring `Multi` responses (see also #44898). So I guess there is some alternative implementation needed to fully support setting the `traceresponse`.

**Pull request closed without merging**
