### PR TITLE
Fix gRPC codegen race condition

### PR DESCRIPTION
**Pull request by scrocquesel**
@cescoffier I add a lock to prevent compilation while generating sources. No more error so far. Shall we try it with quarkus CI ?

### CODE REVIEW

**Comment by cescoffier** [comment]
looks good! LEt's see what the CI says.

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
Unfortunately, this PR is in conflict now, could you rebase and fix the conflict?

**Comment by gsmet** [comment]
I rebased the PR, let's see what CI has to say.

**Comment by scrocquesel** [comment]
> I rebased the PR, let's see what CI has to say.

Thanks

**Pull request merged**
