### PR TITLE
Re-enable DevMojoIT.testResourcesFromClasspath()

### PR DESCRIPTION
**Pull request by famod**
See https://github.com/quarkusio/quarkus/pull/10565#issuecomment-656814500

### CODE REVIEW

**Comment by geoand** [comment]
Let's see what CI says

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
@geoand CI is green. Good to merge? Or do we need a rebase?

**Comment by geoand** [comment]
Let's merge it, although I think the test might have to be disabled altogether (as I saw it fail in Linux tests once)

**Comment by famod** [comment]
> I think the test might have to be disabled altogether (as I saw it fail in Linux tests once)

:+1: -> https://github.com/quarkusio/quarkus/pull/10675#issuecomment-657657170

I'll try to add more diagnostic output.

**Comment by geoand** [comment]
Cool!

**Comment by famod** [comment]
Reproducible sooner or later via:
```
while mvn clean test -Dtest=DevMojoIT#testResourcesFromClasspath -f integration-tests/maven/; do :; done
```

**Comment by famod** [comment]
On Windows:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project multimodule-cp-resources-html: Failed to clean project: Failed to delete C:\_dev\git\quarkus\integration-tests\maven\target\test-classes\projects\multimodule-resources-classpath\html\target\classes -> [Help 1]
```
I am not sure that this is the same problem on Linux. I could only tell if I had the logs from CI but it doesn't seem to collect files like `integration-tests/maven/target/test-classes/projects/multimodule-resources-classpath/build-multimodule-resources-classpath.log`

I'll focus on the failure I am seeing on Windows  for now and I'll create an infra-issue to collect all `**/target/**/*.log`.

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
