### PR TITLE
Manage snappy-java so that other Platform participants do not bring their own versions

### PR DESCRIPTION
**Pull request by ppalaga**
…heir own versions 

[QUARKUS-1461](https://issues.redhat.com/browse/QUARKUS-1461)

### CODE REVIEW

**Comment by ppalaga** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
I know where this is coming from but i am not sure the quarkus-bom is the place to manage these kind of cases. They are going to be popping up pretty randomly, I guess. We can automate this kind of alignment in the platform though or adjust it manually there.
This specific dependency seems to be a dependency of `org.apache.kafka:kafka-clients` which is used by multiple extensions and it's already in the quarkus-bom.

**Comment by gsmet** [comment]
AFAICS, it's going to be mandated by https://github.com/quarkusio/quarkus/pull/21847/files#diff-2b7d71809e1063e0d0411cbe30d606e12b984790680195567e7b8bde0d078e3fR139 so maybe we could merge this.

But please make this patch as similar as the one in ^ so that it can be rebased properly.

**Comment by ppalaga** [comment]
> We can automate this kind of alignment in the platform

I'd prefer testing in Camel Quarkus with the same version as we get on the Platform. Camel Quarkus extensions may have different paths how they pull snappy, so managing kafka clients might not be enough.

> AFAICS, it's going to be mandated by https://github.com/quarkusio/quarkus/pull/21847/files#diff-2b7d71809e1063e0d0411cbe30d606e12b984790680195567e7b8bde0d078e3fR139 so maybe we could merge this.

Good news, thanks!

> But please make this patch as similar as the one in ^ so that it can be rebased properly.

OK, let me do it.

**Comment by ppalaga** [comment]
> make this patch as similar as the one in ^ so that it can be rebased properly.

Done in 1ce2210

**Comment by ppalaga** [comment]
Not sure what the CI failure means?

```
2021-12-01T17:18:14.7067697Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-12-01T17:18:14.7950007Z Waiting for a Hosted runner in the 'organization' to pick this job...
2021-12-01T17:18:15.0673017Z Job is waiting for a hosted runner to come online.
2021-12-01T17:19:34.8159512Z Job is about to start running on the hosted runner: GitHub Actions 11 (hosted)
```

**Comment by ppalaga** [comment]
Is this good to merge?

**Comment by gsmet** [comment]
@ppalaga In the end, this was merged as part as the Kafka 3 upgrade that went in early. Question is: is it something you need for a 2.5 backport?

**Comment by ppalaga** [comment]
This is much more product related then anything else. 2.2.4 would be nice to have, otherwise 2.7 will do.

**Comment by gsmet** [comment]
If you create a PR for 2.2, I'll consider it. You'll need to check the version of Snappy that is used there.

2.2.4.Final will be released next Monday morning.

Closing this one.

**Comment by ppalaga** [comment]
> If you create a PR for 2.2, I'll consider it.

There is a workaround in prod Platform 2.2 that works well and can stay till 2.7. Thus I am not going to send a PR to 2.2

**Pull request closed without merging**
