### PR TITLE
ServiceProviderBuildItem improvements

### PR DESCRIPTION
**Pull request by ppalaga**
* Make ServiceProviderBuildItem immutable
* Allow instantiation from a Collection
* factory reading from service descriptor files

### CODE REVIEW

**Comment by FroMage** [comment]
Sorry I don't have the time. Perhaps @geoand can help?

**Comment by geoand** [comment]
Sure, I'll take a look tomorrow hopefully

**Review by geoand — APPROVED** [review]
LGTM

**Comment by ppalaga** [comment]
Thanks, @geoand !

**Comment by geoand** [comment]
yw!

**Pull request merged**
