### PR TITLE
Introduction of the extension (catalog) compatibility info based on capabilities

### PR DESCRIPTION
**Pull request by aloubyansky**
This PR introduces means to collect extension compatibility info and check whether any combination of extensions is compatible based on provided capabilities.

It also adds `extension-dependencies` element to the extension metadata which contains a list of extensions that are dependencies of the current extension.

### CODE REVIEW

**Comment by aloubyansky** [comment]
@ia3andy could you have a look and see what's missing for it to be usable in code.quarkus, etc? Specifically, `ExtensionCompatibility` and `ExtensionCatalogCompatibility` classes.

**Comment by aloubyansky** [comment]
BTW, @gastaldi, I'm replacing `groupId`, `artifactId` and `version` in the `extension.yaml` with `artifact`, so it's consistent with the generated platform descriptor. But if you are using `JsonExtension` to deserialize it, it shouldn't be an issue.

**Comment by ia3andy** [comment]
> @ia3andy could you have a look and see what's missing for it to be usable in code.quarkus, etc? Specifically, `ExtensionCompatibility` and `ExtensionCatalogCompatibility` classes.

@aloubyansky it seems fine, I will probably load it from the catalog using the factory you provided, to add the incompatibility list to all extensions sent to the UI.

**Comment by aloubyansky** [comment]
Ready for review.

**Review by gastaldi — APPROVED** [review]
LGTM

**Pull request merged**
