### PR TITLE
Fix TLS config Javadoc typo

### PR DESCRIPTION
**Pull request by gsmet**
Noticed while working on the management interface.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Review by geoand — APPROVED** [review]

**Comment by michalvavrik** [comment]
> @michalvavrik @sberyozkin could one of you have a look at these failures ^?

Yeah, I'll check what has changed. I just experienced it locally and it will block both of my PRs when I push changes. @sberyozkin please let me know in a channel of your choice if you figure it out (pinging me in any PR should be enough).

**Comment by michalvavrik** [comment]
It seems that we just hit the expiration time:

> Verification of the token issued to client quarkus-app has failed: The JWT is no longer valid - the evaluation time NumericDate{1732638044 -> Nov 26, 2024, 5:20:44 PM CET} is on or after the Expiration Time (exp=NumericDate{-31557014167219200}) claim value..

**Comment by sberyozkin** [comment]
Oops, sorry @gsmet, @michalvavrik, I'll have a look, I think there is one token there, azure one, recorded there as a test resource, provided by a user, to test a strange Azure case.  Not sure what to do right now.  I'll have to sign off and head home shortly, will have a look  into the OIDC wiremock tests tomorrow morning at the latest, sorry about this noise - I'm sure this is not a certificate issue.

Not sure what is happening with the GraphQL tests, may be the certs have to be dynamically generated - @jmartisk, did you work on those tests ?

**Comment by jmartisk** [comment]
> Not sure what is happening with the GraphQL tests, may be the certs have to be dynamically generated - @jmartisk, did you work on those tests ?

The certs are indeed dynamically generated, but from looking at the failure ("address already in use"), it seems the problem there was a leftover HTTP server that some previous test failed to tidy up

**Comment by sberyozkin** [comment]
The most obvious solution is to update the OIDC lifespan grace property to be Long, as opposed to Int and make the Azure token last for another 20 years or whatever, right now it is set in the test to the maximum Int value.

I don't think I can use use Azure in tests, I can generate it myself to make it a bit closer to how Azure creates this token, may be it is another option, I'll have to think....

**Pull request merged**
