### PR TITLE
Update kubernetes-client to support EC keys in native image

### LINKED ISSUE #21848: Make sure kubernetes-client can work with Elliptic Curve keys
### Description

Right now, if the EC keys are required, the client will fail due to the EC key utility code being excluded in the native image.

Reported by Alexander Hachmann.

### Implementation ideas

Consider adding
```
<dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
</dependency>
<dependency>
     <groupId>org.bouncycastle</groupId>
     <artifactId>bcpkix-jdk15on</artifactId>
</dependency>
```

as `quarkus-kubernetes-client` dependencies

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #21848

Keeping this PR as draft for a moment - the BC dependencies are added at the integration test level - but they should be added at the extension level - with the exclusion the EC keys will never work while the native build fails without the BC dependencies even if EC keys are not required.

@geoand I'll move the dependencies to the extension once you approve it

### CODE REVIEW

**Comment by ahachmann** [comment]
@sberyozkin thanks for creating this issue, I was not able to document / create yet.
For what I experienced now, I can say that once tweaking the JAR and removing the `CertUtilsSubstitutions` from the jar to test this solution, everything was working. 👍 

From users's perspective I can say, that having to add bouncy castle dependencies myself would not have been an issue. Especially as the Documentation tells to do so here: https://quarkus.io/guides/security-customization
But that is up to you guys from Quarkus ;-)

Thanks for your support. Will this change only be reflected in upcoming versions of quarkus, or will there also be some backporting to 2.4.2?

Cheers,
Alex

**Comment by geoand** [comment]
> Thanks for your support. Will this change only be reflected in upcoming versions of quarkus, or will there also be some backporting to 2.4.2?

There are no further releases planed for `2.4` as we have moved to `2.5`

**Comment by sberyozkin** [comment]
@geoand the native build fails once the substitution is removed - even if the EC key is not used. `CertUtils` in Fabric8 is coded directly against the BC API (and looks like it is not possible to avoid it when dealing the the certs in the code).

I've moved the dependencies around and tried to build without them again but it fails.

**Comment by sberyozkin** [comment]
@geoand This is why I've moved now directly to the extension - it will just fail without it and the substitution dropped unless we start asking users to support an incomplete path... No sure if it is the best option but not sure what else can be done

**Comment by geoand** [comment]
I'd like to hear from @manusa and @iocanel about this actually.

**Comment by iocanel** [comment]
> I'd like to hear from @manusa and @iocanel about this actually.

I don't recall why this part requires BC. I do recall however, that it was meant to be an optional dependency and the absence of it was meant to be handled gracefully.
So, if the particular operation shouldn't be using BC, but it does we should report it upstream.

**Comment by ahachmann** [comment]
If it was meant to be an optional dependency, it would be nice if there was a way to disable `CertUtilsSubstitutions ` though. I added the needed dependencies ,but the `CertUtilsSubstitutions ` was basically intercepting the code so that it was throwing an exception. So if this a way to avoid that interception, this could help as well. But right now, it will break the thread.

**Comment by geoand** [comment]
In that case, we should try to improve the substitution

**Comment by manusa** [comment]
> I'd like to hear from @manusa and @iocanel about this actually.

> So, if the particular operation shouldn't be using BC, but it does we should report it upstream.


AFAIK, upstream, the Bouncy Castle dependencies should be [optional](https://github.com/fabric8io/kubernetes-client/blob/87352fd7fe15feca1a247a37020dfd569bfbf4d5/kubernetes-client/pom.xml#L167-L178). I think we are only using Bouncy Castle tools for very specific operations (namely [handling EC keys](https://github.com/fabric8io/kubernetes-client/blob/e580fe4dc18828d1995648f390409243353cb1ba/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L138)). I think this is only documented as a NoClassDefFoundError message, maybe we should add this somewhere.

For the Quarkus part, I guess the user should be responsible to add that dependency in case it's necessary for their use case, I don't understand the need to make it mandatory.

Regarding the `CertUtilsSubstitutions` I have no idea why it was added. The `CertUtils#handleECKey` method hasn't changed much since this extension was created. I make heavy use of BC in another Quarkus extension and I don't recall having trouble with similar methods. Maybe it's worth a try removing the substitution and checking if Graal compilation warnings persist.

**Comment by sberyozkin** [comment]
@manusa It will fail to build without it. 
But let me try a conditional exclusion - exclude only if no BC is registered, I recall we did something similar for BC in Quarkus

**Comment by geoand** [comment]
Let me know if you want me to look at something @sberyozkin

**Comment by sberyozkin** [comment]
Hey @geoand Trying to finalize updating this PR :-), should be close enough

**Comment by sberyozkin** [comment]
@geoand, all, does it look better ?

**Review by geoand — APPROVED** [review]
Great!

**Comment by ahachmann** [comment]
Thanks guys for your effort!

**Pull request merged**
