### PR TITLE
Use direct SmallRye Config APIs

### LINKED ISSUE #4166: Use smallrye config's newOptionalConverter when it lands
Currently Smallrye Config doesn't provide a Converter for `Optional` so the `@ConfigProperties` support implements it's [own](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/configproperties/ConfigPropertiesUtil.java#L69).
However native support for `Optional` is coming in the next Smallrye Config release so this should be picked up as soon it lands to simply the Quarkus code.

See [this](https://github.com/quarkusio/quarkus/pull/4075#discussion_r326248009) discussion.

### PR DESCRIPTION
**Pull request by radcortez**
Fix #4166

### CODE REVIEW

**Comment by radcortez** [comment]
@geoand

**Comment by geoand** [comment]
Thanks @radcortez ! I'll have a look tomorrow

**Review by geoand — APPROVED** [review]
Nice simplification!

Once CI is back online, let's restart the tests and make sure everything passes

**Comment by radcortez** [comment]
Sure. Thanks!

**Pull request merged**
