### PR TITLE
Quarkus JBang project type

### PR DESCRIPTION
**Pull request by ia3andy**
command:
```shell
final QuarkusJBangCodestartProjectInput input = QuarkusJBangCodestartProjectInput.builder()
                .putData("quarkus.version", "999-SNAPSHOT")
                .build();
        final Path projectDir = testDirPath.resolve("default");
        getCatalog().createProject(input).generate(projectDir);
```

output:
```shell
 tree                                                                                                                                                                                                                                                                                                               130 jbang-project-type
.
├── src/ExampleResource.java
├── README.md
├── jbang
└── jbang.cmd

```
 running:
```shell
 ./jbang src/ExampleResource.java                                                                                                                                                                                                                                                                                                    master!+?
[jbang] Resolving dependencies...
[jbang]     Resolving io.quarkus:quarkus-resteasy:999-SNAPSHOT...Done
[jbang] Dependencies resolved
[jbang] Building jar...
[jbang] Post build with io.quarkus.launcher.JBangIntegration
oct. 28, 2020 5:05:57 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.1.Final
oct. 28, 2020 5:05:57 PM io.quarkus.deployment.QuarkusAugmentor run
INFO: Quarkus augmentation completed in 787ms
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-10-28 17:05:58,886 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT on JVM started in 0.786s. Listening on: http://0.0.0.0:8080
2020-10-28 17:05:58,905 INFO  [io.quarkus] (main) Profile prod activated. 
2020-10-28 17:05:58,905 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]

```

Todo in next PRs:
- Picocli: #13208
- Plug to Quarkus CLI #13209

### CODE REVIEW

**Comment by maxandersen** [comment]
nice.

1) for a "enterprise" jbang app I would still put the java file in `src/` not toplevel.
2) I gues this does NOT play well together with existing codestarts; like they can do both --maven and --gradle but for --jbang most of them couldn't be shared due to less sharable code ? 
(actually - jbang would be able to build most of our example projects assuming they have //DEPS ..

What is really missing though is jbang doesn't support BOM resolution thus no notion of platform when using jbang. thus not sure if we want to include it in codestarts just yet.

**Comment by ia3andy** [comment]
> nice.
> 
> 1. for a "enterprise" jbang app I would still put the java file in `src/` not toplevel.

@maxandersen  TBH I really like the flat structure that jbang provides, if we start to add `src`.. IMHO you already removed a big part of jbang simplicity, if you want to start a bigger project, you convert it to a maven or gradle project.. 

plus if you put it in `src`, then you might want to put it in `src/main/java` then you already have 3 dirs for nothing.... I like flat :)

> 2. I gues this does NOT play well together with existing codestarts; like they can do both --maven and --gradle but for --jbang most of them couldn't be shared due to less sharable code ?
>    (actually - jbang would be able to build most of our example projects assuming they have //DEPS ..
> 

This is a new codestart project type completely separated from the quarkus project type, thus Maven and Gradle codestarts are not used for this.

> What is really missing though is jbang doesn't support BOM resolution thus no notion of platform when using jbang. thus not sure if we want to include it in codestarts just yet.

I created this PR because it was close to be done in my local branches and we needed an example of new codestart project type for https://github.com/quarkusio/quarkus/issues/12522

For now, I am just adding the plain extension dependency with version, but yeah this would indeed be better with bom. 

I was thinking about creating a different CLI entry point `quarkus create-jbang` or whatever, we could display a big splash warning in the console saying it's "Experimental"

**Comment by maxandersen** [comment]
> @maxandersen TBH I really like the flat structure that jbang provides, if we start to add `src`.. IMHO you already removed a big part of jbang simplicity, if you want to start a bigger project, you convert it to a maven or gradle project..

not sure if you realize it but jbang can use multiple source files now, currently `//SOURCE x.java` but soon `//SOURCE **/*.java` will be allowed too.

that plus jbang eventually will have `jbang edit` support which does not require creating temporary project it will rely on detecting where `src` is.

Having .java side-by-side with jbang/jbang.jar is not great either.

Thus I think it fits perfectly quarkus codestarts will create a slight structure that is as simple as possible, but not simpler than that.

> 
> plus if you put it in `src`, then you might want to put it in `src/main/java` then you already have 3 dirs for nothing.... I like flat :)

No, I just said `src` :) Which is fit.

**Comment by ia3andy** [comment]
@maxandersen I changed the location to `./src` as requested. I have a few change from this PR needed for https://github.com/quarkusio/quarkus/issues/12522, I think we can merge this without plugging it in the tooling yet. I will create issues for the next tasks which would be "good first issues"

**Review by maxandersen — APPROVED** [review]
doesn't hurt ;) LGTM.

how do i actually test/try this from the cli/command line ?

**Comment by ia3andy** [comment]
Created:
- https://github.com/quarkusio/quarkus/issues/13209
- https://github.com/quarkusio/quarkus/issues/13208

**Pull request merged**
