### PR TITLE
Bump to smallrye-config 2.13.1

### LINKED ISSUE #29918: smallrye-config: Converter<Int> throws IllegalStateException
### Describe the bug

Since Quarkus 2.15.0.Final a converter defined as follows leads to a `IllegalStateException`:

```kotlin
import org.eclipse.microprofile.config.spi.Converter

class MyConverter: Converter<Int> {

    override fun convert(value: String): Int {
       return 1
    }
}
```

This is because `Int` is interpreted as an `int` and not an `java.lang.Integer`. The exception is thrown in
 method `validateConverter` (`io/smallrye/config/smallrye-config-core/2.13.0/smallrye-config-core-2.13.0-sources.jar!/io/smallrye/config/ConfigMappingInterface.java:831`).

```bash
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#generateConfigClasses threw an exception: java.lang.IllegalArgumentException
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.validateConverter(ConfigMappingInterface.java:831)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:721)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getProperties(ConfigMappingInterface.java:699)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.createConfigurationInterface(ConfigMappingInterface.java:656)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.access$000(ConfigMappingInterface.java:28)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface$1.computeValue(ConfigMappingInterface.java:33)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface$1.computeValue(ConfigMappingInterface.java:31)
[ERROR] 	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
[ERROR] 	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
[ERROR] 	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getConfigurationInterface(ConfigMappingInterface.java:80)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:764)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getProperties(ConfigMappingInterface.java:699)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getProperties(ConfigMappingInterface.java:700)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getProperties(ConfigMappingInterface.java:700)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.createConfigurationInterface(ConfigMappingInterface.java:656)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.access$000(ConfigMappingInterface.java:28)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface$1.computeValue(ConfigMappingInterface.java:33)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface$1.computeValue(ConfigMappingInterface.java:31)
[ERROR] 	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
[ERROR] 	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
[ERROR] 	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
[ERROR] 	at io.smallrye.config.ConfigMappingInterface.getConfigurationInterface(ConfigMappingInterface.java:80)
[ERROR] 	at io.smallrye.config.ConfigMappingLoader.getConfigMappingsMetadata(ConfigMappingLoader.java:28)
[ERROR] 	at io.quarkus.deployment.configuration.ConfigMappingUtils.processConfigClass(ConfigMappingUtils.java:86)
[ERROR] 	at io.quarkus.deployment.configuration.ConfigMappingUtils.generateConfigClasses(ConfigMappingUtils.java:59)
[ERROR] 	at io.quarkus.arc.deployment.ConfigBuildStep.generateConfigClasses(ConfigBuildStep.java:285)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

In addition: The exception should have more information about this failure.

### How to Reproduce?

`./mvnw clean install`

[reproducer.zip](https://github.com/quarkusio/quarkus/files/10248164/reproducer.zip)

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #29918

### CODE REVIEW

**Comment by geoand** [comment]
@radcortez are there any other issues this release fixes?

**Comment by radcortez** [comment]
> @radcortez are there any other issues this release fixes?

It has other fixes, but no issues opened in Quarkus.

**Review by radcortez — CHANGES_REQUESTED** [review]
I think @gsmet also wants an update to the Jakarta migration script. I've also released the equivalent version for Jakarta: 3.1.1

**Comment by geoand** [comment]
Jakarta rule updated

**Review by radcortez — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
@radcortez Thanks for reading my mind :).

**Comment by gsmet** [comment]
@geoand @radcortez 

This particular commit causes regressions with native executables and 2.15 specifically.

The full report is visible here: https://github.com/quarkusio/quarkus/pull/30148#issuecomment-1370341898 (it's hidden as I pushed another build but you can open it).

For instance, `CharacterSetSupportITCase.testFieldAndGetterReflectionOnEntityFromServlet` from `integration-tests/main` is failing with the following error (the stacktrace is not visible on CI but I reproduced it locally):


```
ERROR: Failed to start application (with profile prod)
java.lang.StackOverflowError
	at com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.newStackOverflowError0(StackOverflowCheckImpl.java:333)
	at com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.newStackOverflowError(StackOverflowCheckImpl.java:329)
	at com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.throwNewStackOverflowError(StackOverflowCheckImpl.java:309)
	at com.oracle.svm.core.graal.jdk.SubstrateArraycopySnippets.boundsCheck(SubstrateArraycopySnippets.java:117)
	at com.oracle.svm.core.graal.jdk.SubstrateArraycopySnippets.doArraycopy(SubstrateArraycopySnippets.java:108)
	at java.util.ArrayList.toArray(ArrayList.java:402)
	at java.lang.Class$2.run(Class.java:1878)
	at java.lang.Class$2.run(Class.java:1866)
	at java.security.AccessController.executePrivileged(AccessController.java:169)
	at java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.lang.Class.getClasses(DynamicHub.java:1865)
	at io.smallrye.config.ConfigMappingInterface.hasDefaultMethodImplementation(ConfigMappingInterface.java:796)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:715)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
	at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:733)
```

There are some other weird errors that are fixed by removing this commit.

For now, I have removed it from the backports for 2.15.2.Final.

**Comment by geoand** [comment]
Interesting

**Comment by radcortez** [comment]
I'll have a look.

**Comment by gsmet** [comment]
To reproduce, use the 2.15 branch and add this commit on top of it. Don't hesitate to ping me if you need more details.

**Comment by radcortez** [comment]
To backport, this also requires https://github.com/quarkusio/quarkus/pull/29609

**Pull request merged**
