### PR TITLE
ldap mock: using random port instead of hardcoded one

### PR DESCRIPTION
**Pull request by hartimcwildfly**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot for the contribution!

Would you like to explain what use case you are trying to solve with this?

**Comment by hartimcwildfly** [comment]
I just think it's cleaner code to use a random port instead of a hardcoded one. And one does not have to manually set the quarkus.security.ldap.dir-context.url when using the LdapTestResource.

**Comment by geoand** [comment]
We don't really do this for other things, so I am kind of against this.

@gastaldi WDYT?

**Comment by gastaldi** [comment]
@geoand I don't have a strong opinion about this but given that this is used in tests and that the necessary parameters to run the tests are set in the LdapTestResource, I think that kinda makes sense. 

Perhaps we should adapt our other tests to run in random ports in order to facilitate parallel testing

**Comment by maxandersen** [comment]
we already do 8081 instead of 8080 for testing to run while products; I agree with @gastaldi it would be interesting to see what we can do to ensure parallel tests and less fricition in test setup is feasible.

**Comment by maxandersen** [comment]
I don't know if random is the right approach - but I assume there gotta be many more examples of things like this ?

**Comment by gastaldi** [comment]
Random enables parallel tests compared to a fixed port, so I think it makes sense

**Comment by gastaldi** [comment]
> we already do 8081 instead of 8080 for testing to run while products

We should look at enabling random ports in our HTTP tests, I think there is an issue asking for that already

**Review by oscerd — APPROVED** [review]

**Comment by hartimcwildfly** [comment]
Go for it!

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
