### PR TITLE
Use ApplicationScoped for Artemis ServerLocator and ConnectionFactory

### PR DESCRIPTION
**Pull request by middagj**
If no scope is used on a Produces method, it defaults to Dependent, which is probably not the best for the ConnectionFactory and ServerLocator.

### CODE REVIEW

**Comment by gastaldi** [comment]
Maybe add a `@DefaultBean` too so users can override it if necessary?

**Comment by middagj** [comment]
Yes, that is a good addition. I have added that.

Also we have in our custom extension to set up some JMS a problem with the ordering so I added a ArtemisConfiguredBuildItem that can be used for ordering. It is a common pattern in other extensions, only there it is done via a SimpleBuildItem with a RuntimeValue of the produced item. Using a SimpleBuildItem is not feasible because we have two methods producing the same item, which is not allowed. I only plan to use it for ordering and get the bean from the BeanContainer.

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Looks good, thanks.

**Comment by gsmet** [comment]
@middagj btw, have you tried your `@Produce` trick? It's the first time I saw this one in action :).

**Comment by middagj** [comment]
No, but I can check of course.

**Comment by gsmet** [comment]
Yes, better check it works OK.

**Comment by geoand** [comment]
So is this good to go?

**Comment by gsmet** [comment]
@geoand not really, I'm waiting for @middagj to test his `@Produce` thing works as he expects.

**Comment by geoand** [comment]
OK thanks! I removed the `waiting-for-ci` label then to avoid having this merged by accident

**Comment by middagj** [comment]
Sorry, it took me sometime to force a wrong initial order as it comes always ordered on my mac (only seems to happen on Linux in the CI/CD pipeline).

It does not work when producing the jar (it does work in testing), I get a:
```
Failed to build a runnable JAR: Failed to augment application classes: Cycle detected:
[ERROR]            io.quarkus.artemis.jms.deployment.ArtemisJmsProcessor#configure produced class io.quarkus.artemis.core.deployment.ArtemisConfiguredBuildItem
[ERROR]         to org.acme.CustomProcessor#defineBeanAnnotation produced class io.quarkus.arc.deployment.BeanDefiningAnnotationBuildItem
[ERROR]         to io.quarkus.arc.deployment.BeanArchiveProcessor#build produced class io.quarkus.arc.deployment.BeanArchiveIndexBuildItem
[ERROR]         to io.quarkus.arc.deployment.AutoInjectFieldProcessor#autoInjectQualifiers produced class io.quarkus.arc.deployment.AutoInjectAnnotationBuildItem
[ERROR]         to io.quarkus.arc.deployment.AutoInjectFieldProcessor#annotationTransformer produced class io.quarkus.arc.deployment.AnnotationsTransformerBuildItem
[ERROR]         to io.quarkus.arc.deployment.ArcProcessor#initialize produced class io.quarkus.arc.deployment.ContextRegistrationPhaseBuildItem
[ERROR]         to io.quarkus.arc.deployment.ArcProcessor#registerBeans produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem
[ERROR]         to io.quarkus.arc.deployment.ConfigBuildStep#analyzeConfigPropertyInjectionPoints produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem$BeanConfiguratorBuildItem
[ERROR]         to io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
[ERROR]         to io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.BeanContainerBuildItem
[ERROR]         to io.quarkus.artemis.jms.deployment.ArtemisJmsProcessor#configure
```
I changed the implementation to use separate SimpleBuildItems.

**Comment by gsmet** [comment]
Thanks for checking.

**Pull request merged**
