### PR TITLE
Introduce a workflow for linting with Vale

### PR DESCRIPTION
**Pull request by gsmet**
Here is the CI setup for Vale.

From what I can see, with `fail_on_error: false`, the build still fails if Vale complains about something. I think it's probably not a big deal as it's probably a good idea to make people aware of it so that we can fine tune the config.

I'm wondering if it could be useful to ping someone from the doc team (Michelle) for failing Vale workflows? At least once we are confident about the setup? Let me know if you think it has value, I can probably do something about it.

Keeping it as a draft for now as I would like to set up the label we talked about with @michelle-purcell today and send an email to the list before actually enabling it.

Fixes #29103

### CODE REVIEW

**Comment by michelle-purcell** [comment]
Thanks @gsmet. I reviewed and replicated the Vale configuration in this PR on my sandbox and see the same behaviour.
`fail_on_error: false` seems to have no impact.

I will keep digging and testing. It might be a reviewdog v3 issue...

I'll ask about this in the vale-at-red-hat community slack channel, in case this is a known issue. 

I really like your label idea. What about the following:

image

Thanks

**Comment by gsmet** [comment]
@michelle-purcell I created the label `triage/needs-vale-rule-tweak`.

**Comment by michelle-purcell** [comment]
Perfect :100: 

I will add information to the quarkus contributor docs to explain what to do when your PR is littered with errors, warnings, or suggestions that are incorrect or misleading.

**Review by ebullient — APPROVED** [review]

**Comment by michelle-purcell** [comment]
@gsmet - According to the Vale docs :arrow_down: and issue [Action fails even if fail_on_error is false #89](https://github.com/errata-ai/vale-action/issues/89),  `fail_on_error: false` is not working as expected. I added our scenario and experience to the issue. 

image

**Comment by gsmet** [comment]
Let's make progress on this even if the situation is not perfect on the Vale side.

**Pull request merged**
