### PR TITLE
Add build tool param to fix gradle adding extension bootstrap

### LINKED ISSUE #8009: Quarkus Kotlin extension not added in Bootstrap Kotlin+Gradle Project
**Describe the bug**
Quarkus Kotlin extension is not added in dependencies Bootstrap Kotlin+Gradle Project

**Expected behavior**
It should be added to to `dependencies` block

**Actual behavior**
It is not added to to `dependencies` block

**To Reproduce**
- Bootstrap kotlin+gradle project
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
	-DprojectGroupId=org.acme \
	-DprojectArtifactId=kotlin-test-gradle \
	-DclassName="org.acme.fruitStore.FruitResource" \
	-Dpath="/fruits" \
	-DplatformArtifactId=quarkus-bom \
	-Dextensions="kotlin,resteasy-jsonb" \
	-DbuildTool=gradle
```

**Environment (please complete the following information):**
 - Build tool : Gradle 6.1.1

### PR DESCRIPTION
**Pull request by RotBolt**
fixes #8009

### CODE REVIEW

**Comment by geoand** [comment]
@gastaldi did we have tests for gradle project generation? If so, then this PR should add one

**Comment by geoand** [comment]
I tested this and it does work as expected.

**Comment by gastaldi** [comment]
> @gastaldi did we have tests for gradle project generation? If so, then this PR should add one

Yes, see https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/functionalTest/java/io/quarkus/gradle/QuarkusPluginFunctionalTest.java#L71

**Comment by KaenDagger** [comment]
@geoand Bootsrap Gradle project test ? I did not find one in gradle module

**Comment by geoand** [comment]
> > @gastaldi did we have tests for gradle project generation? If so, then this PR should add one
> 
> Yes, see https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/functionalTest/java/io/quarkus/gradle/QuarkusPluginFunctionalTest.java#L71

Excellent! @KaenDagger please a test that corresponds to the use case the PR is fixing (adding extensions to a generated Gradle project).

**Comment by KaenDagger** [comment]
@geoand silly issue. Bot did not label it correctly :P

**Comment by gastaldi** [comment]
BTW you can't really create a project using Gradle, there is just the Maven mojo (which is what @KaenDagger changed) that does it. The test is just using the internal API to create it, which I think it's not where the bug lives, considering the proposed fix.

**Comment by gastaldi** [comment]
The integration tests in this case live in https://github.com/quarkusio/quarkus/tree/master/integration-tests/maven

**Comment by geoand** [comment]
@gastaldi yeah, you are correct. 
But we really need an integration test testing gradle project creation...
[This](https://github.com/quarkusio/quarkus/blob/master/integration-tests/maven/src/test/java/io/quarkus/maven/it/CreateProjectMojoIT.java) is where such tests are added. @KaenDagger can you add one please?

**Comment by KaenDagger** [comment]
@gastaldi , Currently maven is used to create a gradle project. Thats why had to fix here
I think there was a proposal to use gradle only to create quarkus-gradle project.

**Comment by geoand** [comment]
@KaenDagger forget about using Gradle to generate a project for now. There is an issue for that IIRC, but that is for latter :)

We just need an integration test for the fix you did so we can merge this.

Thanks

**Comment by KaenDagger** [comment]
ok sure will add the test

**Comment by geoand** [comment]
Thanks

**Comment by geoand** [comment]
@KaenDagger if the test is going to be a problem, we can merge this as is since it would be great to a fix for this for `1.3.1.Final` (all code for which needs to be done by today).

**Comment by KaenDagger** [comment]
@geoand if you could merge this it would be fine. I won't have the time today . I am busy at hospital for my father's treatment.

**Comment by geoand** [comment]
@KaenDagger thanks for the update.
If I have time I will push a commit that adds a test. If not, I will merge as is.

**Review by geoand — APPROVED** [review]

**Comment by KaenDagger** [comment]
@geoand  thanks for adding test

**Pull request merged**
