### PR TITLE
Upgrade microprofile-openapi-tck to 3.1

### PR DESCRIPTION
**Pull request by gsmet**
Related to #31084

@MikeEdgar I tried to upgrade the OpenAPI TCK in main as I thought it would be an easy one but there are 2 test failures.

Could you have a look?

```
[ERROR]   AirlinesAppTest>Arquillian.run:138->testOperationUserResource:285 1 expectation failed.
JSON path paths.'/user/special'.post.requestBody.content.'application/json'.schema doesn't match.
Expected: is null
  Actual: <{$ref=#/components/schemas/User}>

[ERROR]   AirlinesAppTest>Arquillian.run:138->testOperationUserResource:285 1 expectation failed.
JSON path paths.'/user/special'.post.requestBody.content.'application/json'.schema doesn't match.
Expected: is null
  Actual: <{$ref=#/components/schemas/User}>
```

### CODE REVIEW

**Comment by MikeEdgar** [comment]
The defaulting of the REST body type as `application/json` is exposing a bug in the SmallRye implementation that relies solely on the presence of a `@Consumes` annotation when it's running the TCK. I'm looking at how to fix this upstream.

**Comment by MikeEdgar** [comment]
@gsmet , the commit below will resolve this with a bump to SmallRye OpenAPI to release 3.2.0 and fixing 2 open Quarkus issues). If you prefer I can open a separate PR with those changes.

[ MikeEdgar/quarkus/c47c909b618686472c908497ea19db82bbbf864a](https://github.com/MikeEdgar/quarkus/commit/c47c909b618686472c908497ea19db82bbbf864a)

**Comment by gsmet** [comment]
@MikeEdgar yes please open a pull request in your name, including the TCK update. I will close this one.

**Pull request closed without merging**
