### PR TITLE
Support for single same uri redirects for OIDC WebClient

### LINKED ISSUE #43937: Provide limited redirect support for OIDC Web client when auto-redirect is disabled
### Description

Sometimes, when `quarkus-oidc` (or other OIDC extension) calls OIDC provider endpoints like the discovery one, the OIDC provider will send a redirect request to the same discovery endpoint but with some cookies.

Quarkus OIDC uses Vert.x WebClient. As far as managing redirects is concerned,  WebClient follows redirects by default, with some addition work required at the Vert.x level to deal with such redirects.

If the auto-redirect is disabled, then Quarkus OIDC should allow a single, same URI redirect, only if the cookies are available. Essentially it is a single safe retry case in case of the redirect since the request does not follow a new URI.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #43937.

This PR enables a single time redirect support when one of GET OidcProvider endpoints (discovery, JWK, or UserInfo) request a redirect exactly to the same URI, as long as one or more cookies are available during such redirect.

it is impossible to avoid adding a property in this case. Some users may already depending on the auto-redirect feature  without cookies.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
LGTM

Do you think we should document this feature?

**Comment by sberyozkin** [comment]
@cescoffier Thanks, sure, will have a look

**Comment by sberyozkin** [comment]
Hi @cescoffier, I've started documenting it, and thought, may be we should do it when, at some point, the same is supported at the WebClient level, otherwise I'm not sure how to say in the docs: if you'd like to have a same URI redirect supported you must disable auto-following redirects, which does not read very logical :-). I can still do it though if you prefer. 
JavaDocs for the `OidcCommonConfig#follow-redirects` does describe what happens if it is set to `false`, so may be we can keep this option quite low profile for the moment until Vert.x 5 might start supporting it ?

**Comment by sberyozkin** [comment]
@cescoffier Let me actually add a few lines

**Comment by sberyozkin** [comment]
@cescoffier Docs updated, that should be better now

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
