### PR TITLE
ArC: fix KotlinUtils.isKotlinSuspendMethod() in case of zero-parameter Kotlin methods

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
I would have added a test, but `ArcTestContainer` doesn't support unproxyable classes transformations (yet).

**Review by mkouba — APPROVED** [review]

**Comment by Ladicek** [comment]
I'm looking at it as we speak -- it requires adding rudimentary support for bytecode transformations in `ArcTestContainer`, but that would overall be a good thing to have (e.g. we could move `static` methods interception implementation from the Quarkus extension to ArC itself), so I'm doing it :-)

**Review by Sanne — APPROVED** [review]
Thanks!

**Comment by Sanne** [comment]
Regarding tests: don't sweat it, unit tests would be nice(r) but we'll have coverage when the `quarkus-integration-test-hibernate-reactive-panache-kotlin` module gets enabled again; it's temporarily disabled as we work on Hibernate Reactive.

**Comment by Ladicek** [comment]
Failing tests are:

- `GrpcDevModeTest.testEchoStreamReload` -- known flaky test
- `OpenTelemetryDevServicesDatasourcesTest.devDatasource` -- doesn't seem to be known flaky :thinking:

**Comment by Ladicek** [comment]
`OpenTelemetryDevServicesDatasourcesTest.devDatasource` fails in at least one other PR (#31929), which proves that this PR doesn't cause it (I don't really see how that could possibly happen). Gonna merge this.

@brunobat, `OpenTelemetryDevServicesDatasourcesTest.devDatasource` seems to have started failing in CI recently. I didn't really spend much time looking into it, so this is just FYI.

**Comment by brunobat** [comment]
looking into it @Ladicek I also spot it somewhere else.

**Comment by brunobat** [comment]
This should fix it: https://github.com/quarkusio/quarkus/pull/31909

**Pull request merged**
