### PR TITLE
Redis Client: fix JSON.MGET parameters ordering

### LINKED ISSUE #41611: quarks-redis-client : JSON.MGET returning null
### Describe the bug

I am using quarkus-redis-client to interact with redis through the following code:

```
String[] keys = {"key-1", " key-2"}
reactiveJsonCommands.jsonMget("$", keys).await().indefinitely();
```

My interest is to fetch values for multiple keys in one go. The [documentation](https://redis.io/docs/latest/commands/json.mget/) says -> Return the values at path from multiple key arguments, hence I suppose this fits my requirement.

In reality, I am able to successfully execute commands in redis-cli by doing: 
`JSON.MGET key-1 key-2 key-3 $`

But the above code is returning null always. This is what the above code would result in: 
Result from MONITOR command:
`"json.mget" "$" "key-1" “key-2 “key-3”`

But when i execute the command JSON.MGET key-1 key-2 key-3 $ in redis-cli, I am observing the below result in MONITOR output:
`"JSON.MGET" "key-1" "key-2" "key-3" "$"`

When i checked the internals, the path and key formation looks bit confusing, as this would always result in path getting appended at the first and if i do -> `JSON.MGET $ key-1 key-2 key-3` this will return null as my code:

image

Is this causing the values to be returning as null or enlighten me on what I am doing wrong here?

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #41611

### CODE REVIEW

**Comment by Ladicek** [comment]
This is technically a breaking change, but a minor one I believe? And it actually makes the API behave as intended.

**Comment by gsmet** [comment]
I think it's worth fixing it. If it gets in, please add an entry in the migration guide for 3.13.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Definitely a breaking change, but yes, we must fix this. Thanks!

**Comment by Ladicek** [comment]
Added a short notice to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.13, thank you!

**Pull request merged**
