### PR TITLE
Use actual bean type when generating Reactive Messaging Invoker

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by gsmet** [comment]
Out of curiosity, what is it supposed to fix?

**Comment by geoand** [comment]
It doesn't fix anything. It just make the generated bytecode more javac like (and I assume helps the JIT to make the call monomorphic)

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks! LGTM!

**Comment by geoand** [comment]
You are welcome!

**Pull request merged**
