### PR TITLE
Initialize defaultCatalog and defaultSchema in Hibernate ORM config

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]
Sure, go ahead.

However:

1. If this is a problem, I'm surprised we don't have half of our testsuite failing with an NPE?
2. Shouldn't quarkus-config do this for us? It seems like a sane default.

**Comment by gsmet** [comment]
I know it's a problem because I had to do it for the others. Someone reported the NPE to me in private. I have no idea though why the test suite is not reporting the error.
The problem is not our config framework. We sometimes instantiate these objects ourselves when no config is defined (in the case of named persistence units).

**Comment by gsmet** [comment]
My guess is that it's probably because we always have `generation` defined to drop/create the schema.

As long as we have one config in this root, it's not a problem.

**Comment by yrodiere** [comment]
>  The problem is not our config framework. We sometimes instantiate these objects ourselves when no config is defined (in the case of named persistence units).

Maybe we should not call the constructor directly in this case, but ask quarkus-config (whatever it's named, the module that deserializes config) to instantiate an empty config? That way, defaults are set correctly, and we don't have to be so careful about what we do in this file.

I'll look into this when I have some time.

**Pull request merged**
