### PR TITLE
Fix and test netty ssl on graal rc12

### PR DESCRIPTION
**Pull request by FroMage**
For #764

### CODE REVIEW

**Review by cescoffier — CHANGES_REQUESTED** [review]
A few comments.

**Review by cescoffier — APPROVED** [review]

**Comment by Sanne** [comment]
I figured out why GraalVM wasn't allowing more than one path for `java.library.path`.. patch coming soon.

**Comment by cescoffier** [comment]
@Sanne that would help a lot!

**Comment by Sanne** [comment]
FYI the PR is for GraalVM: https://github.com/oracle/graal/pull/1136

**Pull request closed without merging**
