### PR TITLE
[3.2] Upgrade sshd to 2.12.0

### PR DESCRIPTION
**Pull request by jmartisk**
https://issues.redhat.com/browse/QUARKUS-3845

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by sberyozkin** [comment]
Sorry @aloubyansky @gsmet, I merged and just realized  it was for 3.2, hope it won't cause problems in organizing things, please temp revert it if you'd like till all is ready to go, sorry again

**Comment by rsvoboda** [comment]
Just for the record: https://github.com/apache/mina-sshd/compare/sshd-2.10.0...sshd-2.12.0

I'm also ok with merging this, no failure in CI

**Comment by rsvoboda** [comment]
Creation of these direct PRs is getting problematic because it doesn't ensure that the future streams are also fixed

For example 3.7 branch and main still depend on older version 2.10.0
 - https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L224
 - https://github.com/quarkusio/quarkus/blob/3.7/bom/application/pom.xml#L224

Changes should go first into main and other lts/product branches. CC @gsmet @aloubyansky

**Comment by jmartisk** [comment]
I create clones of CVEs for the following RHBQ release too, and make sure we don't forget to fix it. There's https://issues.redhat.com/browse/QUARKUS-3927 for Hyperion. But you're right that in this case the PR probably could've instead gone to main first, and with a backport label.

**Pull request merged**
