### PR TITLE
Workaround https://github.com/quarkusio/quarkus/issues/36952 alias https://github.com/jboss/jboss-parent-pom/issues/236 jboss-parent:40 still manages jdk-misc, but does not define version.jdk-misc anymore

### PR DESCRIPTION
**Pull request by ppalaga**
Workaround for https://github.com/quarkusio/quarkus/issues/36952 alias https://github.com/jboss/jboss-parent-pom/issues/236

### CODE REVIEW

**Comment by gsmet** [comment]
Do we still depend on jboss-parent? IIRC we tried hard to not to recently.

**Comment by ppalaga** [comment]
> Do we still depend on jboss-parent?

Another BOM that we import may depend on it. I have not investigated where it comes from, TBH.

Just try

```
mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:effective-pom -Dverbose=true
```

**Comment by gsmet** [comment]
@aloubyansky I think it makes sense to have this workaround in? At least until `jboss-parent` is fixed?

**Comment by aloubyansky** [comment]
No objections. Perhaps a comment would be useful to remind why it's excluded.

**Comment by ppalaga** [comment]
8c7876b:

* Rebased
* Added a more detailed comment why jdk-misc is excluded

**Review by gsmet — APPROVED** [review]

**Pull request merged**
