### PR TITLE
Fix for #5214

### PR DESCRIPTION
**Pull request by FroMage**
Replace $ with . in loaded class names

### CODE REVIEW

**Comment by gsmet** [comment]
@FroMage could you push the updated adoc to the website? This way, it's mostly fixed already.

Thanks!

**Comment by FroMage** [comment]
Well, it looks like https://github.com/quarkusio/quarkus/commit/0849187379c97db17d6005f709ee6939237eec97 made the table non-searchable, so I want to understand things before rushing this out. ATM my table is not searchable.

**Comment by FroMage** [comment]
Ah, I need to do a full build, probably. But I don't understand why some tables are not searchable anymore. Won't it make them non-searchable on each guide?

**Comment by FroMage** [comment]
OK this is ready to be merged. Result is at https://github.com/quarkusio/quarkusio.github.io/pull/344 for website.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
