### PR TITLE
Revert "Improve loading of classes in RunnerClassLoader"

### PR DESCRIPTION
**Pull request by gsmet**
This reverts commit 27102380b3caa867e195a2ec84c70aeac860d782.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by mariofusco — CHANGES_REQUESTED** [review]
Wait a second, I think we have a much better solution now.

**Comment by mariofusco** [comment]
See https://github.com/quarkusio/quarkus/pull/40942#issuecomment-2160994514

**Comment by geoand** [comment]
I believe we should merge this for now, see https://github.com/quarkusio/quarkus/pull/40942#issuecomment-2161006863

**Comment by mariofusco** [comment]
> I believe we should merge this for now, see [#40942 (comment)](https://github.com/quarkusio/quarkus/pull/40942#issuecomment-2161006863)

Thinking twice wouldn't be better to revert this commit only on the 3.12 immediately after it will be branched and leave the main as it is? This will make easier to merge the other pull request on main when we will be happy with it.

**Comment by geoand** [comment]
We could certainly do that, but it mean extra time for CI to run since it would mean that we would need a CI run after the branch is cut (recall that when the branch is cut from `main`, we know CI has passed). 

@gsmet is the one that handles the releases, so I'll leave to him to decide.

**Comment by gsmet** [comment]
Yeah, that won't fly as I need this to be in for tomorrow morning and I need it when the branch is created.

**Comment by mariofusco** [comment]
That's ok but this will mean that we will have to revert this revert on main before merging [my pull request](https://github.com/quarkusio/quarkus/pull/40942). Please let us know when we can do this.

**Pull request merged**
