### PR TITLE
improve security by adding httponly flag

### PR DESCRIPTION
**Pull request by sschmiedleitner**
for form-based auth. Mitigates XSS.

### CODE REVIEW

**Comment by sberyozkin** [comment]
I think it is reasonable but what I'm not sure about is whether Quarkus users do form based authentication from SPA with Java Script... I don't think this option will do for `quarkus-oidc`. @stuartwdouglas - what do you think ? `secure` attribute is critical but not sure about `http-only`

**Comment by sschmiedleitner** [comment]
Imho as this cookie is encrypted and therefore not intended to be used at the client, therefore the access should be restricted - see also https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies.

Especially for small-sized projects, where you have just a few power users the form-based auth can be an option but still needs to be as secure as possible.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
For form auth this makes sense. For SPA OIDC apps (e.g. using keycloak.js) not so much.

**Comment by sschmiedleitner** [comment]
Btw. when accepting this PR it will not be possible to logout with plain JS as it is not possible to delete the cookie then. For this one may add an endpoint to be able to logout, i.e. a DELETE to /j_security_check? Maybe in FormAuthenticationMechanism.authenticate - correct?

Regarding OIDC. As far as I know the cookie of an OIDC auth server will be a different one issued by the auth server (and most probably for a different domain). This particular cookie is only for form based auth - isn't it?

**Comment by gsmet** [comment]
So what's the status of this? Your two last comments make me wonder if it's an improvement in all cases?

**Comment by sschmiedleitner** [comment]
@gsmet / @stuartwdouglas / @sberyozkin 
I think this PR should only be merged if someone could help and contribute to add the logout endpoint as proposed above. Otherwise no logout would be possible which is really bad in production.

**Comment by gsmet** [comment]
@sschmiedleitner OK that's what I understood. @sberyozkin I'll you decide what to do with this PR and how it can be finalized.

Anyway thanks @sschmiedleitner for starting this discussion with some code!

**Review by mamadaliev — APPROVED** [review]

**Comment by Sanne** [comment]
@sberyozkin up :)

**Comment by gsmet** [comment]
@sberyozkin we need feedback on this.

**Comment by gsmet** [comment]
Closing for lack of activity.

**Pull request closed without merging**
