### PR TITLE
Added logging-json-structured extension

### PR DESCRIPTION
**Pull request by SlyngDK**
I have used some time to add support for logging custom fields in the json output.
This is the first preview, of a possible way to implement it.

This is related to this issue #7451.

Comments and questions are welcome.

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks for this work.

I wonder if it could be a good candidate for the Quarkiverse that we are trying to build. @aloubyansky WDYT?

**Comment by aloubyansky** [comment]
I'd say yes @gsmet 
@SlyngDK the quarkus repo is getting huge and it's obvious it's not going to scale well in perspective if we keep adding more and more extensions. For that and other maintenance and infrastructure related issues we decided to create an separate org for extensions contributed by the community (including the Quarkus team members themselves). It's still a work a progress in terms of integrating quarkiverse extensions into the dev tools such as code.quarkus.io catalog and the command line ones but it's highly prioritized. We already we have a couple extension repos in there. See https://github.com/quarkiverse and the start of the wiki https://github.com/quarkiverse/quarkiverse-wiki/blob/master/Home.md
Are you intending to be maintaining the extension in the future? Would you like me to create a repository for it in quarkiverse instead?
Thanks a lot for your contribution!

**Comment by SlyngDK** [comment]
@aloubyansky Indeed, sounds like good idea to start move non core extensions, to another repo. I am using quarkus at my current workplace, and will be able to maintaining  it.
My thoughts on this extension, is to make it more mature, and maybe later replaces the current `logging-json` extension.
How do I getting started with the quarkiverse??
Is the build pipeline ready, to test and publish packages?
How to create documentation/guide of the usage?

**Comment by aloubyansky** [comment]
Excellent @SlyngDK. The build pipeline and publishing hasn't yet been setup. @gastaldi is working on it. The docs publishing is also an open issue, we are considering `quarkiverse.io/<project-name>/<project-version>/docs` as the location but that's still a subject to discuss. Sorry, we are still figuring this all out. Feel free to contribute your ideas. @maxandersen is about to write a blog about the whole thing today/tomorrow.
However, I can already create a repo for your extension under https://github.com/quarkiverse and let your manage it. If you agree, make sure you follow these naming conventions https://github.com/quarkiverse/quarkiverse-wiki/blob/master/Home.md and let me know. Thanks!

**Comment by SlyngDK** [comment]
@aloubyansky 
If you create the repo, then I will import the project with the correct naming.
And be ready to test the setup, when the things get ready.

**Comment by aloubyansky** [comment]
Sure @SlyngDK pick a name for it and let me know. The wiki has moved here, btw https://github.com/quarkiverse/quarkiverse/wiki

**Comment by SlyngDK** [comment]
@aloubyansky Will `quarkiverse-json-logging` be fine?

**Comment by aloubyansky** [comment]
I'd, personally, pick quarkiverse-logging-json. @gsmet how does that sound to you? The Quarkus repo includes `quarkus-logging-json` which could be confusing a bit. Why not though?

**Comment by aloubyansky** [comment]
@SlyngDK i've created https://github.com/quarkiverse/quarkiverse-logging-json and sent you an invite to become the admin for it.

**Comment by SlyngDK** [comment]
@aloubyansky I have merged the first version to the new repo.
How is the progress on getting the build and publishing to work?
Should we continue this thread on zulip?

**Comment by aloubyansky** [comment]
Excellent @SlyngDK Sure, let's chat on zulip. We already have a Quarkiverse topic in the dev stream. Feel free to post your questions there. The build and publishing is on its way. @gastaldi should be able to provide the current status.

**Pull request closed without merging**
