### PR TITLE
Qute checked fragments - ignore literal expressions during validation

### PR DESCRIPTION
**Pull request by mkouba**
- literals have type info as well

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Looks good. No tests?

**Comment by mkouba** [comment]
> Looks good. No tests?

Good point, I'll update the `CheckedTemplateFragmentTest`...

**Comment by gsmet** [comment]
@mkouba just checking that this doesn't need a backport to 2.13?

**Comment by mkouba** [comment]
> @mkouba just checking that this doesn't need a backport to 2.13?

It's not needed. The fragments are in the main branch only.

**Pull request merged**
