### PR TITLE
Fix HibernateOrmCodestart

### PR DESCRIPTION
**Pull request by ia3andy**
This test in generating code for Java, I removed the line testing a kotlin file (there is a specific test for kotlin).

### CODE REVIEW

**Comment by yrodiere** [comment]
@ia3andy There isn't any test for Kotlin as far as I can see? The only one I can see is `HibernateOrmPanacheKotlinCodestartTest.java` and that's for Hibernate ORM with Panache, not with Hibernate ORM.

**Comment by ia3andy** [comment]
> @ia3andy There isn't any test for Kotlin as far as I can see? The only one I can see is `HibernateOrmPanacheKotlinCodestartTest.java` and that's for Hibernate ORM with Panache, not for Hibernate ORM alone.

good catch!

**Comment by ia3andy** [comment]
Ok things where in a inconsistant state, I guess the test was passing at some point but the codestart was changed and the snapshot was not updated accordingly.

Also there was a file in the kotlin codestart which should not have been there.

As you said @yrodiere there was no hibernate kotlin test so I added one.

**Comment by ia3andy** [comment]
if things keep failing after this patch, @gsmet let me know and I'll dig deeper.

**Review by loicmathieu — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@manovotn could the failures be related to your recent changes to ArC?

**Review by gsmet — APPROVED** [review]
OK, let's get this in!

**Comment by manovotn** [comment]
@gsmet yes the the MP TCK are definitely related.
It's this PR - https://github.com/quarkusio/quarkus/pull/30452 but the CI there passed without these failures?

**Comment by manovotn** [comment]
@gsmet I don't know that much about RR, but I am aware of some such magic being done here - https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java#L750-L751
But that doesn't look like it since that should only limit the bean type to the impl class; the exception complains about types such as `javax.ws.rs.ext.MessageBodyWriter`...

**Comment by manovotn** [comment]
I think I found it, it's actually in `ResteasyReactiveProcessor`, namely [here](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java#L850-L865) we are adding interface types as well with no validation.
This is now causing issue because some of those interface types can have wildcards in them which removed them from bean types but we'll still attempt to restrict the bean type to it.

We'd need to filter out any interface types that have wildcards in them. Though I have no idea how this affects RR functionality.

**Comment by gsmet** [comment]
Probably something to discuss with @geoand next week.

**Comment by geoand** [comment]
> We'd need to filter out any interface types that have wildcards in them. Though I have no idea how this affects RR functionality.

I think we can probably safely do this

**Comment by manovotn** [comment]
I took a closer look and wasted some time trying to implement what I said above while in fact limiting the types by wildcards would be pretty complex and not really needed.
Instead, Arc should compare types declared via `@Typed` with *unrestricted* bean type set (including all types, even those we eventually remove). I'll submit a PR and mark you for review.

**Pull request merged**
