### PR TITLE
Also use args when comparing test resources

### LINKED ISSUE #44129: TestResourceScope.MATCHING_RESOURCES ignores configuration annotations from QuarkusTestResourceConfigurableLifecycleManager
### Describe the bug

From what I can see, only the FQCN of the test resource lifecycle manager and the configured scope are taken into account when grouping together tests with matching resources:

https://github.com/quarkusio/quarkus/blob/2fc4833f3f52e7d7851bbea57653b1bca53af98c/test-framework/common/src/main/java/io/quarkus/test/common/TestResourceManager.java#L321-L332

This seems incomplete, as test resource lifecycle managers can implement `QuarkusTestResourceConfigurableLifecycleManager` to be customized per-test, like this:

https://github.com/quarkusio/search.quarkus.io/blob/41e3b9f2de465ea2dc74efaa46ee44b310d5cc08/src/test/java/io/quarkus/search/app/testsupport/QuarkusIOSample.java#L510-L531

https://github.com/yrodiere/search.quarkus.io/blob/42ebd004b6fa5d92960b0615fb8ead6b1b6cb726/src/test/java/io/quarkus/search/app/SearchServiceTest.java#L42

### Expected behavior

Tests are considered to have matching resources if they have the same resource lifecycle managers _with the same arguments_.

### Actual behavior

Tests are considered to have matching resources if they have the same resource lifecycle managers, _regardless of arguments_.

### How to Reproduce?

Check out https://github.com/quarkusio/search.quarkus.io/pull/345 , revert the last commit, and see how resources are reused despite the 

Or, probably simpler, add a unit test next to the existing ones for `@WithTestResource` within Quarkus itself.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Related conversation: https://github.com/quarkusio/search.quarkus.io/pull/345

PR introducing the feature: #42852

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #44129

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Oh, apparently, the classes changed under your feet.

**Comment by geoand** [comment]
No problem, I'll update

**Comment by geoand** [comment]
Closing this actually because the change was included in https://github.com/quarkusio/quarkus/issues/44129

**Comment by gsmet** [comment]
@geoand you pointed to an issue?

**Comment by geoand** [comment]
My bad, I meant #44279

**Comment by gsmet** [comment]
Thanks, I wanted to check we have the backport label and it's all good.

**Comment by geoand** [comment]
👍🏽

**Pull request closed without merging**
