### PR TITLE
Make sure versions are mocked in snapshots tests

### LINKED ISSUE #15142: Some code start tests test the version which is not compatible with releases
Got these errors while releasing:
```
[ERROR] Failures: 
[ERROR]   QuarkusJBangCodestartGenerationTest.generatePicocliProject:55 [check snapshot for: QuarkusJBangCodestartGenerationTest/generatePicocliProject/src_GreetingCommand.java] 
Path:
  target/jbang-codestart-gen-test/picocli/src/GreetingCommand.java
read with charset UTF-8 does not have the expected content:

Changed content at line 2:
expecting:
  ["//DEPS io.quarkus:quarkus-bom:999-SNAPSHOT@pom"]
but was:
  ["//DEPS io.quarkus:quarkus-bom:1.12.0.Final@pom"]

[ERROR]   QuarkusCodestartGenerationTest.generateDefault:90 [check snapshot for: QuarkusCodestartGenerationTest/generateDefault/pom.xml] 
Path:
  target/quarkus-codestart-gen-test/default/pom.xml
read with charset UTF-8 does not have the expected content:

Changed content at line 15:
expecting:
  ["    <quarkus-plugin.version>999-SNAPSHOT</quarkus-plugin.version>"]
but was:
  ["    <quarkus-plugin.version>1.12.0.Final</quarkus-plugin.version>"]

Changed content at line 18:
expecting:
  ["    <quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>"]
but was:
  ["    <quarkus.platform.version>1.12.0.Final</quarkus.platform.version>"]

[ERROR]   QuarkusCodestartGenerationTest.generateMavenWithCustomDep:200 [check snapshot for: QuarkusCodestartGenerationTest/generateMavenWithCustomDep/pom.xml] 
Path:
  target/quarkus-codestart-gen-test/maven-custom-dep/pom.xml
read with charset UTF-8 does not have the expected content:

Changed content at line 15:
expecting:
  ["    <quarkus-plugin.version>999-SNAPSHOT</quarkus-plugin.version>"]
but was:
  ["    <quarkus-plugin.version>1.12.0.Final</quarkus-plugin.version>"]

Changed content at line 18:
expecting:
  ["    <quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>"]
but was:
  ["    <quarkus.platform.version>1.12.0.Final</quarkus.platform.version>"]

[ERROR]   QuarkusCodestartGenerationTest.generateRESTEasyJavaCustom:152 [check snapshot for: QuarkusCodestartGenerationTest/generateRESTEasyJavaCustom/src_main_resources_META-INF_resources_index.html] 
Path:
  target/quarkus-codestart-gen-test/resteasy-java-custom/src/main/resources/META-INF/resources/index.html
read with charset UTF-8 does not have the expected content:

Changed content at line 149:
expecting:
  ["                <li>Quarkus Version: <code>999-SNAPSHOT</code></li>"]
but was:
  ["                <li>Quarkus Version: <code>1.12.0.Final</code></li>"]

[ERROR]   QuarkusCodestartGenerationTest.generateRESTEasySpringWeb:181 [check snapshot for: QuarkusCodestartGenerationTest/generateRESTEasySpringWeb/src_main_resources_META-INF_resources_index.html] 
Path:
  target/quarkus-codestart-gen-test/resteasy-springweb/src/main/resources/META-INF/resources/index.html
read with charset UTF-8 does not have the expected content:

Changed content at line 155:
expecting:
  ["                <li>Quarkus Version: <code>999-SNAPSHOT</code></li>"]
but was:
  ["                <li>Quarkus Version: <code>1.12.0.Final</code></li>"]

[INFO] 
[ERROR] Tests run: 106, Failures: 5, Errors: 0, Skipped: 0
```

We can't count on the version to always be `999-SNAPSHOT`, we shouldn't test that.

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes https://github.com/quarkusio/quarkus/issues/15142

### CODE REVIEW

**Comment by gsmet** [comment]
@glefloch a test is often failing for Gradle Windows: https://scans.gradle.com/s/uevlpnn7ufycc/tests/:test/io.quarkus.gradle.devmode.MultiModuleIncludedBuildTest/main()#1

I wonder if it could be related to the fast-jar change given we don't really expect a `build/libs/` directory now but I'm not really sure given I only have seen it fail on Windows and not consistently.

**Comment by glefloch** [comment]
Yes I'm having a look, this is weird. The failing module is a dependency and gradle outputs jar to `build/libs` by default, so this shouldn't be related to the fat jar change.

**Review by gsmet — APPROVED** [review]
Thanks! Will try that for the next release.

**Comment by ia3andy** [comment]
@gsmet cool, sorry about this. 

We need to be careful when switching code gen tests to snapshot testing, while it's easy to convert and gives a check of the whole file, most of them are not designed with mocks.

**Pull request merged**
