### PR TITLE
Bump vertx to 4.3.8 to fix CVE from vertx-http (32258)

### PR DESCRIPTION
**Pull request by aleboulanger**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

Updating Vert.x usually entails a chain of checks that need to be performed, but @cescoffier is the best person to comment on it

**Comment by cescoffier** [comment]
As I said in several issue, we cannot update to that version. Next update will target 4.4.1.

**Comment by geoand** [comment]
Thanks @cescoffier.

So I'll close this based on that information.

**Comment by cescoffier** [comment]
Also, we are not affected by the reported cve.

**Comment by aleboulanger** [comment]
> Also, we are not affected by the reported cve.

can you give us more details about this one please ? is it because the dependency is only use at compile time ? thanks

**Comment by cescoffier** [comment]
No, it's because Vert.x did not use the constructor and methods affected by the CVE. So, except if your code is using these, you are safe. If your code is using these methods, it won't compile anyway, as the methods got removed.

**Pull request closed without merging**
