### PR TITLE
Make org.graalvm.regex:regex parent first

### LINKED ISSUE #27085: Regression with upgrade 2.9.2 -> 2.11.1 in app using GraalVM Javascript interpreter
### Describe the bug

My application uses `org.graalvm.js:js` to interpret Javascript. With 2.9.2 this was working fine (I had to make sure I keep my dependencies on the same version with Quarkus), but with upgrade to 2.11.1 the tests are failing with
```
2022-08-02 10:47:53,966 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-12) Uncaught exception received by Vert.x: org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: Duplicate language id regex. First language [Language class com.oracle.truffle.regex.RegexLanguage, Loaded from file:/home/rvansa/.m2/repository/org/graalvm/regex/regex/22.1.0/regex-22.1.0.jar]. Second language [Language class com.oracle.truffle.regex.RegexLanguage, Loaded from file:/home/rvansa/.m2/repository/org/graalvm/regex/regex/22.1.0/regex-22.1.0.jar].
    at com.oracle.truffle.polyglot.LanguageCache.createLanguages(LanguageCache.java:256)
    at com.oracle.truffle.polyglot.LanguageCache.loadLanguages(LanguageCache.java:222)
    at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:212)
    at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:889)
    at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:254)
    at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:286)
    at org.graalvm.polyglot.Engine$Builder.build(Engine.java:620)
    at org.graalvm.polyglot.Context$Builder.build(Context.java:1822)
```
Looks like the `RegexLanguage` class is once loaded through AppClassLoader and another time through QuarkusClassLoader. 

### Expected behavior

There's no regression.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk 11.0.15 2022-04-19

### GraalVM version (if different from Java)

22.1.0

### Quarkus version or git rev

2.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #27085

@rvansa can you try if this PR fixes your issue?
Also, if there are just a couple of artifacts that need syncing with the GraalVM version, maybe we could add them to the BOM if it makes things significantly easier. Let me know if you have a list. (I'm not really inclined to add 20 of them for such a use case but if it's 2 or 3, that could work)

### CODE REVIEW

**Comment by rvansa** [comment]
Building Quarkus... thanks! I guess that the difference in behaviour comes from adding Truffle to those parent-first loaders - I've found that the code checks where is TruffleLanguage loaded from and ignores unsuitable loaders...

**Comment by rvansa** [comment]
For some reason I can't build the branch with `./mvnw install -DskipTests` - it fails with
```
Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-cli: Failed to build quarkus application: java.lang.ClassNotFoundException: io.quarkus.deployment.TestConfig
 ```

**Comment by rvansa** [comment]
@gsmet OK, build with `-Dquickly` worked and now I confirm that this fixes my issue. Thanks!

**Comment by gsmet** [comment]
Thanks for testing, I will backport it to the next micro.

**Review by geoand — APPROVED** [review]

**Pull request merged**
