### PR TITLE
Update dekorate to 2.9.2

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by metacosm** [comment]
This should be back ported to 2.8 so that it gets in 2.8.1 as well, please.

**Comment by gsmet** [comment]
Sure, I already marked it for backport :).

**Comment by metacosm** [comment]
I guess I still don't understand how these labels are supposed to work :)
The `?` at the end is confusing to me as it makes it seem like this is something that might be considered, not something that's decided.

**Comment by gsmet** [comment]
Yeah that means they should be considered. But sometimes when doing the backport, things go south (typically so many conflicts that we have to rewrite the patch and that it might be too risky to backport). So in most cases, things will get backported. In some complex cases, they might not but I always contact the original author to discuss the options. 
In this very case, I don’t expect any issues given it’s just a version bump.

**Pull request merged**
