### PR TITLE
Upgrade JAXB to 4.0.2

### PR DESCRIPTION
**Pull request by gsmet**
Noticed while debugging an issue that we could upgrade to 4.0.2.

### CODE REVIEW

**Comment by famod** [comment]
WDYT about having dependebot do that for us for patch releases?

**Comment by gsmet** [comment]
@famod done!

**Review by famod — APPROVED** [review]
This will now also catch major and minor updates, but why not!

**Comment by gsmet** [comment]
@famod I will ask Dependabot to ignore it when it happens. On one hand, I agree skipping majors would be best, on the other hand, I like to be aware that a new major is out and we are lagging.

**Pull request merged**
