### PR TITLE
Adds environmentVariables and systemProperties options to the DevMojo

### LINKED ISSUE #14401: dev mode: support for setting system properties and env variables
**Description**

Since version 1.3.0, [camel-k](https://github.com/apache/camel-k) has switched to Quarkus as default runtime. For troubleshooting purpose we have some pure java based examples which I'm now migrating to use `quarkus:dev` instead of the `exec-maven-plugin`

Our current setup is like:

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>${exec-maven-plugin.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>exec</goal>
            </goals>
        </execution>
        <configuration>
            <executable>java</executable>
            <workingDirectory>${project.basedir}</workingDirectory>
            <arguments>
                <argument>-jar</argument>
                <argument>${project.build.directory}/${project.artifactId}-runner.jar</argument>
            </arguments>
            <environmentVariables>
                <CAMEL_K_CONF>${project.basedir}/data/application.properties</CAMEL_K_CONF>
                <DATA_DIR>${project.basedir}/data</DATA_DIR>
            </environmentVariables>
        </configuration>
    </executions>
</plugin>
```

The most relevant part here is the `environmentVariables` as camel-k uses some env vars for boot-strapping its configuration.

It would be nice if the `configuration` section of the DevMojo would support setting arguments, env vars and system properties, something like:

```xml
<plugin>
    <groupId>oio.quarkus</groupId>
    <artifactId>quarkus-maven-plugin</artifactId>
    <version>${quarkus-maven-plugin.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>dev</goal>
            </goals>
        </execution>
        <configuration>
            <arguments>
                --max-messages=1
            </arguments>
            <systemProperties>
                <my.property>my.val</my.property>
            </systemProperties>
            <environmentVariables>
                <CAMEL_K_CONF>${project.basedir}/data/application.properties</CAMEL_K_CONF>
                <DATA_DIR>${project.basedir}/data</DATA_DIR>
            </environmentVariables>
        </configuration>
    </executions>
</plugin>
```

I know that it is possible to use the configuration optios `jvmArgs` to set the system properties and `argsString` to set application arguments but having a proper `systemProperties` and `arguments` seems, at least to me, better as user expoerience

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #14401 

This change allows configuring env vars and system properties as
````
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus-plugin.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <systemProperties>
            <p1>v1</p1>
          </systemProperties>
          <environmentVariables>
            <ONE>TWO</ONE>
          </environmentVariables>
        </configuration>
      </plugin>
````

Although, this may look a confusing, given that `dev` isn't really listed as the goal and it may seem like the configuration is relevant for the listed goals, which it isn't. That's, btw, also relevant for the other existing dev mode config options.
Perhaps, these options could be nested under a `dev` element or something or the goal should be configured in the pluginManagement.

### CODE REVIEW

**Comment by geoand** [comment]
cc @lburgazzoli

**Comment by famod** [comment]
Well, that "plugin-wide" config is basically a Maven feature. So I don't really think that we should add a `dev` element.

In my previous Quarkus project I introduced a `qdev` Maven profile in in that profile I set everything dev mode sepcific, e.g. h2 dependency, `skipTests`, `<defaultGoal>quarkus:dev</defaultGoal>` etc.
And then nice an short: `mvn -Pqdev`

**Review by famod — APPROVED** [review]
LGTM!
Maybe just add a little note to `jvmArgs` that system properties should be better set via `systemProperties`?

**Comment by aloubyansky** [comment]
Another option would be to prefix the option names with `dev`.

**Comment by aloubyansky** [comment]
> In my previous Quarkus project I introduced a `qdev` Maven profile and in that profile I set everything dev mode specific, e.g. h2 dependency, `skipTests`, `<defaultGoal>quarkus:dev</defaultGoal>` etc.
> And then nice and short: `mvn -Pqdev`

Nice.

**Comment by lburgazzoli** [comment]
LGTM

**Comment by famod** [comment]
> Maybe just add a little note to `jvmArgs` that system properties should be better set via `systemProperties`?

I take that back since those new Maps cannot be set via `-D` so if a user wants to quickly pass a system property, `-DjvmArgs=...` would be tha way to go.

**Comment by famod** [comment]
> Another option would be to prefix the option names with `dev`.

I think I would like this a bit more than en entire `dev` wrapper element, but YMMV.
Then again, sould all `generate-code` parameters be prefixed with `gen` or so? Where would it stop?

**Comment by aloubyansky** [comment]
> > Another option would be to prefix the option names with `dev`.
> 
> I think I would like this a bit more than an entire `dev` wrapper element, but YMMV.
> Then again, should all `generate-code` parameters be prefixed with `gen` or so? Where would it stop?

If we go that way then it should be applied to all the options that aren't common, I guess.
Dev mode is special though in that it's not listed as a goal, yet its configuration is in.

**Comment by geoand** [comment]
Are we ready to go on this @aloubyansky @famod ?

@Ladicek there seems to be a race condition on one of the FT tests:

```
Error:  Failures: 
Error:    TimeoutUninterruptableTest>Arquillian.run:138->testTimeoutAsyncBulkhead:199 Execution count after completing all tasks expected [1] but found [2]
```

**Comment by aloubyansky** [comment]
I am still tempted to add the `dev` prefix. But I'm not 100% sure. Any opinions?

**Comment by famod** [comment]
I'm +0.5. 😉 
The consequence would be to duplicate all other DevMojo parameters (addind "dev"-prefix), deprecate the old ones and log warnings so that people move to the new ones? And then remove the old ones in an upcoming release (greater 1.12)?

**Comment by Ladicek** [comment]
I made a bunch of improvements in SRye FT 5.0, which is unfortunately not gonna be merged in `master` anytime soon :-/

**Pull request merged**
