### PR TITLE
Remove remaining usages of native-image goal

### PR DESCRIPTION
**Pull request by famod**
Relates to #14645

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks a ton for this cleanup!

**Comment by gsmet** [comment]
BTW, I think we will need to do the same in the quickstarts.

**Comment by famod** [comment]
> BTW, I think we will need to do the same in the quickstarts.

Good point, 70 matches...

**Comment by famod** [comment]
@gsmet https://github.com/quarkusio/quarkus-quickstarts/pull/765

**Pull request merged**
