### PR TITLE
Safe check to not walk on non-existent paths

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by geoand** [comment]
It does make sense, however I wonder if this needs to be dealt with at a higher level

**Comment by geoand** [comment]
If OP confirms that this works for his issue, I'm good with it

**Comment by gsmet** [comment]
I force pushed to get CI to run.

**Review by gsmet — APPROVED** [review]

**Comment by gastaldi** [comment]
Merged in https://github.com/quarkusio/quarkus/commit/7bf1ed1b5a98fa64a974e78d047d8d18dbfc8fc3

**Pull request closed without merging**
