### PR TITLE
Allow the use of @Blocking on @ClientExceptionMapper

### PR DESCRIPTION
**Pull request by geoand**
- Relates to: https://github.com/quarkusio/quarkus/issues/38275#issuecomment-2115117993

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
I believe none of the other extension handling @Blocking handle this case. 

@ozangunalp do you know about reactive messaging?
@alesj do you know about gRPC?
@mkouba do you know about websocket next?

**Comment by geoand** [comment]
That's a very good point, however the REST client **might** be unique in that the various _Providers_ are run on the event loop by default (which was probably a mistake)

**Comment by mkouba** [comment]
> @mkouba do you know about websocket next?

@cescoffier if you ask whether we produce an `ExecutionModelAnnotationsAllowedBuildItem` for endpoint callbacks then yes, we do: https://github.com/quarkusio/quarkus/blob/main/extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketProcessor.java#L135-L145 :D

**Comment by ozangunalp** [comment]
For messaging, we only detect incoming/outgoing annotated methods on beans and not from superclasses.

**Comment by alesj** [comment]
@cescoffier is gRPC exception handler is a plain ServerCall.Listener impl, which I guess could work with blocking, if there is a @Blocking before on the method

**Pull request merged**
