### PR TITLE
Fix OIDC capability string

### PR DESCRIPTION
**Pull request by HerrDerb**
Follow up #30386
Fix prefix typo

### CODE REVIEW

**Review by sberyozkin — COMMENTED** [review]
@HerrDerb Thanks, looks like there are many other capabilities there with a duplicate dot, would you like to add one more commit to this PR fixing the rest of them, PR may be renamed then to `Remove an extra dot in some capability strings` or something like that ?

**Comment by HerrDerb** [comment]
> @HerrDerb Thanks, looks like there are many other capabilities there with a duplicate dot, would like to add one more commit to this PR fixing the rest of them, PR may be renamed then to `Remove an extra dot in some capability strings` or something like that ?

It's a bit confusing, that's why this one slipped throught. Currently the dot is only given when using the constant `QUARKUS_PREFIX`, the other constants do not have a dot in the end.
I could harmoize this.

**Comment by sberyozkin** [comment]
@HerrDerb Oh I see, sure, let me approve this PR now and if you can follow up with another one harmonizing it then it would be nice, cheers

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
Failure is not related

**Pull request merged**
