### PR TITLE
Run infinispan-embedded in native pipelines

### PR DESCRIPTION
**Pull request by rsvoboda**
Run infinispan-embedded in native pipelines

To prevent issues like https://github.com/quarkusio/quarkus/issues/4830

### CODE REVIEW

**Comment by jaikiran** [comment]
This is a genuine issue in the `infinispan-embedded` integration-tests. It has this:

```
<configuration>
      ...
    <!-- We have some example stack files we want to use -->
    <additionalBuildArgs>
        <additionalBuildArg>-H:ResourceConfigurationFiles=${project.basedir}/src/main/resources/resources-config.json</additionalBuildArg>
    </additionalBuildArgs>
```
Given that the CI build runs `native-image` within `docker`, this path (preferably `${project.build.outputDirectory}` first needs to be exposed via `-v` or `--volume` through `containerRuntimeOptions`, before it can be used as `-H:ResourceConfigurationFiles`

**Comment by rsvoboda** [comment]
`infinispan-embedded` is failing on macOS, don't have linux machine around to play with it :(

**Comment by rsvoboda** [comment]
Looking at infinispan-embedded on Linux machine, transparent linking of resources-config.json in maven is problematic. Shouldn't be Quarkus helping with this stuff?

**Comment by rsvoboda** [comment]
Trying `-H:IncludeResources` approach but resources are not included...

**Comment by rsvoboda** [comment]
Closing, don't see elegant solution for this atm.

**Pull request closed without merging**
