### PR TITLE
Move DevUI Config resolution to Runtime

### LINKED ISSUE #33945: Dev-ui config editor not showing config values changed by a ConfigSourceInterceptor
### Describe the bug

This follows up on https://github.com/quarkusio/quarkus/issues/33884

I have added the null check in the ConfigSourceInterceptor. So it proceeds with null. But then the dev-ui does not show the update toe the config value.

### Expected behavior

Dev-ui should show the actual value the application uses at runtime

### Actual behavior

Seems to show the build time value

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-configinterceptor-npe

Steps to reproduce:
1- run the app via mvn quarkus:dev
2- see the console log ` (Quarkus Main Thread) keepalive config set to 60s`
3-check the same config within the dev-ui

Screen Shot 2023-06-09 at 1 15 37 PM

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

3.1.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #33945

The resolution of the ConfigDescription and matched values must happen at Runtime to make sure we get the correct values.

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by phillip-kruger** [comment]
Test failures is related, you also need to update the integration tests. You can now change the BuildTimeData test to a JsonRPC Test

**Comment by radcortez** [comment]
> Test failures is related, you also need to update the integration tests. You can now change the BuildTimeData test to a JsonRPC Test

Which ones are you thinking? I had a look and I don't think they need to be changed.

**Comment by phillip-kruger** [comment]
O yes, you are right, configuration's dev-ui test is in vertx-http (https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/test/java/io/quarkus/devui/ConfigurationTest.java)

And that only test the update, that is still correct. So please ignore my previous comment :)

**Comment by geoand** [comment]
Should this be backported?

**Comment by radcortez** [comment]
> Should this be backported?

It could be.

**Pull request merged**
