### PR TITLE
Maven CLI: use recipes for platform extensions

### LINKED ISSUE #36568: Maven CLI: use recipes for platform extensions
### Describe the bug

With the recent change https://github.com/quarkusio/quarkus/issues/34391, the migration detects extensions of the migrated application. Recipes for the detected extensions are executed during the update.

The list of the extensions is filtered for simple version updates (see [code](https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/ProjectExtensionsUpdateInfo.java#L42) and [code](https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/ExtensionUpdateInfo.java#L93)). This condition filteres out `camel-quarkus-core` extension (which is part of the platform) and therefore does not upgrade the camel-quarkus code.

### Expected behavior

Recipes for camel-quarkus extensions should be applied if `camel-quarkus-core` dependency is present (and part of the platform)

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/quarkusio/quarkus/issues/36568

### CODE REVIEW

**Review by ia3andy — APPROVED** [review]
That's exactly what I meant thanks @JiriOndrusek :)

**Comment by JiriOndrusek** [comment]
> That's exactly what I meant thanks @JiriOndrusek :)

np, thank for the tip! (I've found another issue - will discuss it on the zulip chat , whether my solution (which I've already tested) is acceptable.

**Comment by JiriOndrusek** [comment]
Failures do not seem to be related to the change in this PR

**Comment by aloubyansky** [comment]
@JiriOndrusek could you please rebase this PR? Thanks.

**Comment by JiriOndrusek** [comment]
> @JiriOndrusek could you please rebase this PR? Thanks.

done

**Pull request merged**
