### PR TITLE
Add strimzi kafka-oauth-client to application bom

### LINKED ISSUE #18601: Manage kafka-oauth-client version in quarkus bom
Manage kafka-oauth-client mentionned in [Quarku's Kafka Guide](https://quarkus.io/guides/kafka#authenticating-with-oauth), in the quarkus bom.

### PR DESCRIPTION
**Pull request by ozangunalp**
Fixes #18601

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
I'm not entirely sure we should do that if we are not consuming it at all in Quarkus. Maybe we should just amend the documentation with the version?

Let's discuss it before merging please.

**Comment by ppalaga** [comment]
> I'm not entirely sure we should do that if we are not consuming it at all in Quarkus. Maybe we should just amend the documentation with the version?

I wonder, whether we shouldn't have test for the scenario mentioned in https://quarkus.io/guides/kafka#authenticating-with-oauth ? In that way we would start using the dependency :)

The bottom line is that this dependency would help us in Camel Quarkus to select the "blessed" version of `com.nimbusds:nimbus-jose-jwt`.

**Comment by ozangunalp** [comment]
@ppalaga I recently tested this scenario with the `0.8.1` of strimzi oauth. I'll see how I can get the security setup working in an integration test.

**Comment by ppalaga** [comment]
> @ppalaga I recently tested this scenario with the `0.8.1` of strimzi oauth. I'll see how I can get the security setup working in an integration test.

That would be highly appreciated from my side, but @gsmet may still want to approve the whole idea.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
The PR itself is ok, but yes, like @gsmet, I wonder if we need to do that as we don't consume it directly. It's a "nice to have" when using managed kafka, but if they changed the required version, the users would have to override it.

**Comment by ppalaga** [comment]
The main question for me is whether the scenario mentioned in the docs should be tested. I think it should.

**Comment by gsmet** [comment]
Well, the fact that it is tested doesn't mandate it to be part of the BOM. We really don't want to add the whole world to the BOM. If using a specific version is not required by the Kafka version we are using, I would keep it user-side.

**Comment by ppalaga** [comment]
Fair enough, it is up to you to decide about the content of the BoM. 
Regardless of that, a test with a hardcoded `kafka-oauth-client` in Quarkus source tree would help us to solve our aligment problems in Camel Quarkus too. Is the idea to have such a test approved at least?

**Comment by gsmet** [comment]
@ppalaga yes, a test would be fine. BTW, I'm not entirely against it IF alignment is a problem and we need to fix something by adding it to the BOM. What I don't want is us adding versions that are not really mandated by alignment.

**Pull request closed without merging**
