### PR TITLE
CI incremental: fix insufficent number of native builds due to internal grep error

### PR DESCRIPTION
**Pull request by famod**
Fixes https://github.com/quarkusio/quarkus/pull/17282#issuecomment-842964572

The main change is to produce a much shorter expression that doesn't repeat `(?<=^)|(?<=,)|(?<=, ))` etc. again and again.

The second change makes the script fail in case such an error should ever happen again.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
I can't say I understand it, but since you've tested it, let's add it :)

**Review by gsmet — APPROVED** [review]
@geoand said it all :).

**Comment by famod** [comment]
I'm sorry guys, I have to admit it's not the easiest regex one could imagine.

FTR, before it looked like this for a change that affected all ITs:
```
(((?<=^)|(?<=,)|(?<=, ))avro-reload(,|$)|((?<=^)|(?<=,)|(?<=, ))bouncycastle(,|$)|((?<=^)|(?<=,)|(?<=, ))bouncycastle-fips(,|$)|((?<=^)|(?<=,)|(?<=, ))bouncycastle-fips-jsse(,|$)|((?<=^)|(?<=,)|(?<=, ))bouncycastle-jsse(,|$)|((?<=^)|(?<=,)|(?<=, ))funqy-amazon-lambda(,|$)|((?<=^)|(?<=,)|(?<=, ))funqy-google-cloud-functions(,|$)|((?<=^)|(?<=,)|(?<=, ))class-transformer(,|$)|((?<=^)|(?<=,)|(?<=, ))class-transformer/runtime(,|$)|((?<=^)|(?<=,)|(?<=, ))class-transformer/deployment(,|$)|((?<=^)|(?<=,)|(?<=, ))shared-library(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-validator(,|$)|((?<=^)|(?<=,)|(?<=, ))common-jpa-entities(,|$)|((?<=^)|(?<=,)|(?<=, ))infinispan-client(,|$)|((?<=^)|(?<=,)|(?<=, ))devtools(,|$)|((?<=^)|(?<=,)|(?<=, ))gradle(,|$)|((?<=^)|(?<=,)|(?<=, ))main(,|$)|((?<=^)|(?<=,)|(?<=, ))kafka(,|$)|((?<=^)|(?<=,)|(?<=, ))kafka-ssl(,|$)|((?<=^)|(?<=,)|(?<=, ))kafka-sasl(,|$)|((?<=^)|(?<=,)|(?<=, ))kafka-snappy(,|$)|((?<=^)|(?<=,)|(?<=, ))kafka-avro(,|$)|((?<=^)|(?<=,)|(?<=, ))kafka-avro-apicurio2(,|$)|((?<=^)|(?<=,)|(?<=, ))kafka-streams(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-db2(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-derby(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-postgresql(,|$)|((?<=^)|(?<=,)|(?<=, ))vault(,|$)|((?<=^)|(?<=,)|(?<=, ))vault-agroal(,|$)|((?<=^)|(?<=,)|(?<=, ))vault-app(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-mariadb(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-h2(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-mssql(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-mysql(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-oracle(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-orm-panache(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-orm-rest-data-panache(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-orm-panache-kotlin(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-reactive-db2(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-reactive-mysql(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-reactive-postgresql(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-reactive-panache(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-search-orm-elasticsearch(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-tenancy(,|$)|((?<=^)|(?<=,)|(?<=, ))hibernate-orm-envers(,|$)|((?<=^)|(?<=,)|(?<=, ))legacy-redirect(,|$)|((?<=^)|(?<=,)|(?<=, ))vertx-http(,|$)|((?<=^)|(?<=,)|(?<=, ))vertx-web(,|$)|((?<=^)|(?<=,)|(?<=, ))vertx-web-jackson(,|$)|((?<=^)|(?<=,)|(?<=, ))vertx(,|$)|((?<=^)|(?<=,)|(?<=, ))spring-di(,|$)|((?<=^)|(?<=,)|(?<=, ))spring-web(,|$)|((?<=^)|(?<=,)|(?<=, ))spring-data-jpa(,|$)|((?<=^)|(?<=,)|(?<=, ))spring-boot-properties(,|$)|((?<=^)|(?<=,)|(?<=, ))spring-cloud-config-client(,|$)|((?<=^)|(?<=,)|(?<=, ))spring-data-rest(,|$)|((?<=^)|(?<=,)|(?<=, ))infinispan-cache-jpa(,|$)|((?<=^)|(?<=,)|(?<=, ))elytron-security(,|$)|((?<=^)|(?<=,)|(?<=, ))elytron-security-oauth2(,|$)|((?<=^)|(?<=,)|(?<=, ))elytron-resteasy(,|$)|((?<=^)|(?<=,)|(?<=, ))elytron-undertow(,|$)|((?<=^)|(?<=,)|(?<=, ))flyway(,|$)|((?<=^)|(?<=,)|(?<=, ))liquibase(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc-client(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc-client-reactive(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc-client-wiremock(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc-token-propagation(,|$)|((?<=^)|(?<=,)|(?<=, ))smallrye-jwt-token-propagation(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc-code-flow(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc-tenancy(,|$)|((?<=^)|(?<=,)|(?<=, ))oidc-wiremock(,|$)|((?<=^)|(?<=,)|(?<=, ))keycloak-authorization(,|$)|((?<=^)|(?<=,)|(?<=, ))reactive-db2-client(,|$)|((?<=^)|(?<=,)|(?<=, ))reactive-pg-client(,|$)|((?<=^)|(?<=,)|(?<=, ))reactive-mysql-client(,|$)|((?<=^)|(?<=,)|(?<=, ))amazon-services(,|$)|((?<=^)|(?<=,)|(?<=, ))test-extension(,|$)|((?<=^)|(?<=,)|(?<=, ))amazon-lambda(,|$)|((?<=^)|(?<=,)|(?<=, ))amazon-lambda-s3event(,|$)|((?<=^)|(?<=,)|(?<=, ))amazon-lambda-stream-handler(,|$)|((?<=^)|(?<=,)|(?<=, ))amazon-lambda-http(,|$)|((?<=^)|(?<=,)|(?<=, ))amazon-lambda-rest(,|$)|((?<=^)|(?<=,)|(?<=, ))amazon-lambda-http-resteasy(,|$)|((?<=^)|(?<=,)|(?<=, ))container-image(,|$)|((?<=^)|(?<=,)|(?<=, ))container-image/maven-invoker-way(,|$)|((?<=^)|(?<=,)|(?<=, ))container-image/quarkus-standard-way(,|$)|((?<=^)|(?<=,)|(?<=, ))kubernetes(,|$)|((?<=^)|(?<=,)|(?<=, ))kubernetes/maven-invoker-way(,|$)|((?<=^)|(?<=,)|(?<=, ))kubernetes/quarkus-standard-way(,|$)|((?<=^)|(?<=,)|(?<=, ))kubernetes-client(,|$)|((?<=^)|(?<=,)|(?<=, ))kubernetes-service-binding-jdbc(,|$)|((?<=^)|(?<=,)|(?<=, ))openshift-client(,|$)|((?<=^)|(?<=,)|(?<=, ))tika(,|$)|((?<=^)|(?<=,)|(?<=, ))neo4j(,|$)|((?<=^)|(?<=,)|(?<=, ))mongodb-client(,|$)|((?<=^)|(?<=,)|(?<=, ))jackson(,|$)|((?<=^)|(?<=,)|(?<=, ))jsonb(,|$)|((?<=^)|(?<=,)|(?<=, ))resteasy-jackson(,|$)|((?<=^)|(?<=,)|(?<=, ))resteasy-mutiny(,|$)|((?<=^)|(?<=,)|(?<=, ))jgit(,|$)|((?<=^)|(?<=,)|(?<=, ))jsch(,|$)|((?<=^)|(?<=,)|(?<=, ))virtual-http(,|$)|((?<=^)|(?<=,)|(?<=, ))virtual-http-resteasy(,|$)|((?<=^)|(?<=,)|(?<=, ))artemis-core(,|$)|((?<=^)|(?<=,)|(?<=, ))artemis-jms(,|$)|((?<=^)|(?<=,)|(?<=, ))maven(,|$)|((?<=^)|(?<=,)|(?<=, ))scala(,|$)|((?<=^)|(?<=,)|(?<=, ))kotlin(,|$)|((?<=^)|(?<=,)|(?<=, ))mongodb-panache(,|$)|((?<=^)|(?<=,)|(?<=, ))mongodb-panache-kotlin(,|$)|((?<=^)|(?<=,)|(?<=, ))mongodb-rest-data-panache(,|$)|((?<=^)|(?<=,)|(?<=, ))narayana-stm(,|$)|((?<=^)|(?<=,)|(?<=, ))narayana-jta(,|$)|((?<=^)|(?<=,)|(?<=, ))elytron-security-jdbc(,|$)|((?<=^)|(?<=,)|(?<=, ))elytron-security-ldap(,|$)|((?<=^)|(?<=,)|(?<=, ))vertx-graphql(,|$)|((?<=^)|(?<=,)|(?<=, ))smallrye-config(,|$)|((?<=^)|(?<=,)|(?<=, ))smallrye-context-propagation(,|$)|((?<=^)|(?<=,)|(?<=, ))smallrye-metrics(,|$)|((?<=^)|(?<=,)|(?<=, ))smallrye-graphql(,|$)|((?<=^)|(?<=,)|(?<=, ))jpa-without-entity(,|$)|((?<=^)|(?<=,)|(?<=, ))quartz(,|$)|((?<=^)|(?<=,)|(?<=, ))redis-client(,|$)|((?<=^)|(?<=,)|(?<=, ))logging-gelf(,|$)|((?<=^)|(?<=,)|(?<=, ))cache(,|$)|((?<=^)|(?<=,)|(?<=, ))qute(,|$)|((?<=^)|(?<=,)|(?<=, ))bootstrap-config/extension(,|$)|((?<=^)|(?<=,)|(?<=, ))bootstrap-config/extension/runtime(,|$)|((?<=^)|(?<=,)|(?<=, ))bootstrap-config/extension/deployment(,|$)|((?<=^)|(?<=,)|(?<=, ))bootstrap-config(,|$)|((?<=^)|(?<=,)|(?<=, ))bootstrap-config/application(,|$)|((?<=^)|(?<=,)|(?<=, ))injectmock(,|$)|((?<=^)|(?<=,)|(?<=, ))reactive-messaging-amqp(,|$)|((?<=^)|(?<=,)|(?<=, ))reactive-messaging-kafka(,|$)|((?<=^)|(?<=,)|(?<=, ))reactive-messaging-http(,|$)|((?<=^)|(?<=,)|(?<=, ))rest-client(,|$)|((?<=^)|(?<=,)|(?<=, ))resteasy-reactive-kotlin(,|$)|((?<=^)|(?<=,)|(?<=, ))resteasy-reactive-kotlin/standard(,|$)|((?<=^)|(?<=,)|(?<=, ))resteasy-reactive-kotlin/prod-mode(,|$)|((?<=^)|(?<=,)|(?<=, ))resteasy-reactive-rest-client(,|$)|((?<=^)|(?<=,)|(?<=, ))resteasy-reactive-rest-client-standalone(,|$)|((?<=^)|(?<=,)|(?<=, ))packaging(,|$)|((?<=^)|(?<=,)|(?<=, ))simple with space(,|$)|((?<=^)|(?<=,)|(?<=, ))consul-config(,|$)|((?<=^)|(?<=,)|(?<=, ))picocli(,|$)|((?<=^)|(?<=,)|(?<=, ))picocli-native(,|$)|((?<=^)|(?<=,)|(?<=, ))webjars-locator(,|$)|((?<=^)|(?<=,)|(?<=, ))devmode(,|$)|((?<=^)|(?<=,)|(?<=, ))ide-launcher(,|$)|((?<=^)|(?<=,)|(?<=, ))elasticsearch-rest-client(,|$)|((?<=^)|(?<=,)|(?<=, ))elasticsearch-rest-high-level-client(,|$)|((?<=^)|(?<=,)|(?<=, ))micrometer-mp-metrics(,|$)|((?<=^)|(?<=,)|(?<=, ))micrometer-prometheus(,|$)|((?<=^)|(?<=,)|(?<=, ))opentelemetry(,|$)|((?<=^)|(?<=,)|(?<=, ))logging-json(,|$)|((?<=^)|(?<=,)|(?<=, ))jaxp(,|$)|((?<=^)|(?<=,)|(?<=, ))mailer(,|$)|((?<=^)|(?<=,)|(?<=, ))native-config-profile(,|$)|((?<=^)|(?<=,)|(?<=, ))logging-min-level-unset(,|$)|((?<=^)|(?<=,)|(?<=, ))logging-min-level-set(,|$)|((?<=^)|(?<=,)|(?<=, ))redis-devservices(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-tls(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-plain-text-gzip(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-plain-text-mutiny(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-mutual-auth(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-streaming(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-interceptors(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-proto-v2(,|$)|((?<=^)|(?<=,)|(?<=, ))grpc-health(,|$)|((?<=^)|(?<=,)|(?<=, ))google-cloud-functions-http(,|$)|((?<=^)|(?<=,)|(?<=, ))google-cloud-functions(,|$)|)
```
I suppose this was just too much for grep to take in.

Now it's:
```
((?:(?<=^)|(?<=,)|(?<=, ))(avro-reload|bouncycastle|bouncycastle-fips|bouncycastle-fips-jsse|bouncycastle-jsse|funqy-amazon-lambda|funqy-google-cloud-functions|class-transformer|class-transformer/runtime|class-transformer/deployment|shared-library|hibernate-validator|common-jpa-entities|infinispan-client|devtools|gradle|main|kafka|kafka-ssl|kafka-sasl|kafka-snappy|kafka-avro|kafka-avro-apicurio2|kafka-streams|jpa|jpa-db2|jpa-derby|jpa-postgresql|vault|vault-agroal|vault-app|jpa-mariadb|jpa-h2|jpa-mssql|jpa-mysql|jpa-oracle|hibernate-orm-panache|hibernate-orm-rest-data-panache|hibernate-orm-panache-kotlin|hibernate-reactive-db2|hibernate-reactive-mysql|hibernate-reactive-postgresql|hibernate-reactive-panache|hibernate-search-orm-elasticsearch|hibernate-tenancy|hibernate-orm-envers|legacy-redirect|vertx-http|vertx-web|vertx-web-jackson|vertx|spring-di|spring-web|spring-data-jpa|spring-boot-properties|spring-cloud-config-client|spring-data-rest|infinispan-cache-jpa|elytron-security|elytron-security-oauth2|elytron-resteasy|elytron-undertow|flyway|liquibase|oidc|oidc-client|oidc-client-reactive|oidc-client-wiremock|oidc-token-propagation|smallrye-jwt-token-propagation|oidc-code-flow|oidc-tenancy|oidc-wiremock|keycloak-authorization|reactive-db2-client|reactive-pg-client|reactive-mysql-client|amazon-services|test-extension|amazon-lambda|amazon-lambda-s3event|amazon-lambda-stream-handler|amazon-lambda-http|amazon-lambda-rest|amazon-lambda-http-resteasy|container-image|container-image/maven-invoker-way|container-image/quarkus-standard-way|kubernetes|kubernetes/maven-invoker-way|kubernetes/quarkus-standard-way|kubernetes-client|kubernetes-service-binding-jdbc|openshift-client|tika|neo4j|mongodb-client|jackson|jsonb|resteasy-jackson|resteasy-mutiny|jgit|jsch|virtual-http|virtual-http-resteasy|artemis-core|artemis-jms|maven|scala|kotlin|mongodb-panache|mongodb-panache-kotlin|mongodb-rest-data-panache|narayana-stm|narayana-jta|elytron-security-jdbc|elytron-security-ldap|vertx-graphql|smallrye-config|smallrye-context-propagation|smallrye-metrics|smallrye-graphql|jpa-without-entity|quartz|redis-client|logging-gelf|cache|qute|bootstrap-config/extension|bootstrap-config/extension/runtime|bootstrap-config/extension/deployment|bootstrap-config|bootstrap-config/application|injectmock|reactive-messaging-amqp|reactive-messaging-kafka|reactive-messaging-http|rest-client|resteasy-reactive-kotlin|resteasy-reactive-kotlin/standard|resteasy-reactive-kotlin/prod-mode|resteasy-reactive-rest-client|resteasy-reactive-rest-client-standalone|packaging|simple with space|consul-config|picocli|picocli-native|webjars-locator|devmode|ide-launcher|elasticsearch-rest-client|elasticsearch-rest-high-level-client|micrometer-mp-metrics|micrometer-prometheus|opentelemetry|logging-json|jaxp|mailer|native-config-profile|logging-min-level-unset|logging-min-level-set|redis-devservices|grpc-tls|grpc-plain-text-gzip|grpc-plain-text-mutiny|grpc-mutual-auth|grpc-streaming|grpc-interceptors|grpc-proto-v2|grpc-health|google-cloud-functions-http|google-cloud-functions|)(,|$))+
```

**Comment by famod** [comment]
PS: ...and I cannot tell you anymore why I didn't do it like that right away. Typical "who wrote that stuff?! ...ah, me some time ago" effect.

**Comment by gsmet** [comment]
The step was executed properly so let's merge and see how it goes.

**Pull request merged**
