### PR TITLE
Upgrade to SmallRye Config 1.9.3

### LINKED ISSUE #2292: Pretty print of configuration errors
Users can do (unintended) configuration errors and Quarkus should provide human (not only Java developer) readable message. Currently java stacktrace is provided.

I can imagine several cases
 - decimal instead of integer
 - typo in boolean
 - typo in name for enums/constants - e.g. log level

Quarkus is using MP Config via SmallRye Config code so there could be also an enhancement on that side.

Proposed format:
```
java -Dquarkus.log.console.darken=1.5 -jar target/validation-1.0-SNAPSHOT-runner.jar
Error: Expected an integer value for 'quarkus.log.console.darken' property.
```

Current state:
```
java -Dquarkus.log.console.darken=1.5 -jar target/validation-1.0-SNAPSHOT-runner.jar
java.lang.NumberFormatException: For input string: "1.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.smallrye.config.Converters.lambda$static$18960f11$1(Converters.java:75)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:133)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:76)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console_darken(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.Application.run(Application.java:213)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.Application.run(Application.java:213)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: "1.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.smallrye.config.Converters.lambda$static$18960f11$1(Converters.java:75)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:133)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:76)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console_darken(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(Unknown Source)
	... 4 more
```

### LINKED ISSUE #12960: ASM classes included in native image due to io.smallrye.config.ConfigMappingInterface.appendPropertyName
We shouldn't generate classes post static init so the ASM classes should never be included in the native executable.

I reproduced this by building the `integration-tests/jpa-postgresql` IT but it should be reproducible with any app.

This is a regression between 1.8.3.Final and 1.9.0.Final.

/cc @radcortez

### PR DESCRIPTION
**Pull request by radcortez**
Release Notes:
https://github.com/smallrye/smallrye-config/releases/tag/1.9.3

* Fixes #12960
* Fixed #2292

### CODE REVIEW

**Comment by gastaldi** [comment]
It also fixes #2292

**Comment by gastaldi** [comment]
Funny that I can't reference that issue in the `Linked issues` list

**Comment by radcortez** [comment]
> It also fixes #2292

Ah yes, let me add it as well.

**Comment by gsmet** [comment]
@gastaldi it needs to be in the description of the PR.

**Review by gsmet — APPROVED** [review]

**Comment by gastaldi** [comment]
> @gastaldi it needs to be in the description of the PR.

I know, but it also (sometimes) works if you add to the Linked Issues list

**Comment by rsvoboda** [comment]
Regarding issue #2292, this error gets printed

```
$ java -Dquarkus.log.console.darken=1.5 -jar target/quarkus-app-1.0-SNAPSHOT-runner.jar
Oct 28, 2020 6:13:10 PM io.quarkus.config
ERROR: An invalid value was given for configuration key "quarkus.log.console.darken": SRCFG00029: Expected an integer value, got "1.5"
Oct 28, 2020 6:13:10 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors has prevented the application from starting. The errors are:
An invalid value was given for configuration key "quarkus.log.console.darken": SRCFG00029: Expected an integer value, got "1.5"
```

JDK logging is used, can be "standard" one line logging used? Or these errors appear too early in the init phase?

**Pull request merged**
