### PR TITLE
Showing the profile in the first line of log after start running Quarkus

### PR DESCRIPTION
**Pull request by chu3laman**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for your contribution!

I am not entirely sure we want this however. Can you describe why exactly you would like to have this?

**Comment by geoand** [comment]
I see, thanks. 

I'm +0 on this, so let's see what others think

**Comment by radcortez** [comment]
Isn't this going to show 2 lines with the profile? The one in the PR, plus the one we already have?

**Comment by Chu3laMan** [comment]
@radcortez I don't think so, because I found a opened ticket that wanted to show the profile in the first line in the console similar to spring

**Comment by radcortez** [comment]
We already show the profile in the startup log, but it is not the first line in the log. As an example:

```console
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-12-01 17:17:51,410 INFO  [io.quarkus] (main) config-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.721s. Listening on: http://0.0.0.0:8080
2024-12-01 17:17:51,419 INFO  [io.quarkus] (main) Profile prod activated.
2024-12-01 17:17:51,419 INFO  [io.quarkus] (main) Installed features: [cdi, config-yaml, rest, smallrye-context-propagation, vertex]
```

Notice the line `Profile prod activated.`.

So, if this PR only adds a new log, the old log will still be there, and you will get the profile logged twice. Would you mind doing something similar and showing the log of a Quarkus app with your PR? Thank you.

**Comment by Chu3laMan** [comment]
> We already show the profile in the startup log, but it is not the first line in the log. As an example:
> 
> ```
> __  ____  __  _____   ___  __ ____  ______
>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2024-12-01 17:17:51,410 INFO  [io.quarkus] (main) config-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.721s. Listening on: http://0.0.0.0:8080
> 2024-12-01 17:17:51,419 INFO  [io.quarkus] (main) Profile prod activated.
> 2024-12-01 17:17:51,419 INFO  [io.quarkus] (main) Installed features: [cdi, config-yaml, rest, smallrye-context-propagation, vertex]
> ```
> 
> Notice the line `Profile prod activated.`.
> 
> So, if this PR only adds a new log, the old log will still be there, and you will get the profile logged twice. Would you mind doing something similar and showing the log of a Quarkus app with your PR? Thank you.

Ah I see, because I was found a ticket that said that they want to show profile that being activated in the first line as spring... no issue. if you don't mind I can close this merge request

**Comment by geoand** [comment]
👌🏽

**Comment by gsmet** [comment]
Hey @Chu3laMan 

could you point me to the issue? We probably need to close it. Thanks!

**Comment by geoand** [comment]
I just closed #32231

**Comment by gsmet** [comment]
Thanks!

**Comment by geoand** [comment]
🙏🏽

**Pull request closed without merging**
