### PR TITLE
Move empty byte buffer creation direct buffer to runtime

### PR DESCRIPTION
**Pull request by galderz**
A better fix for https://github.com/quarkusio/quarkus/issues/9750.

The [initial PR](https://github.com/quarkusio/quarkus/pull/9751) would have caused NPEs. This PR improves that by first avoiding the NPE altogether: the static field is recomputed to the default value (`null`) and then we substitute all accesses by runtime allocated direct byte buffer.

Then, to avoid perf/GC penalty of creating an empty direct byte buffer any time, we create a stub that contains a constant direct byte buffer, but crucially this stub is initialised only at runtime.

Also, the empty byte buffer address was being calculated at build time, which would likely have caused issues at runtime if trying to access that address (any guarantees that it'd be the same?). In this initial attempt, the address has just been set to 0, but a similar trick might be possible by making the computation of the address a runtime concern.

### CODE REVIEW

**Comment by galderz** [comment]
Of course, credit to @dmlloyd for the idea of the runtime stub that's accessed from the substitution 👏

**Review by dmlloyd — APPROVED** [review]

**Comment by galderz** [comment]
Oh crap

**Comment by galderz** [comment]
@geoand Should be fixed now :)

**Comment by geoand** [comment]
:+1:

**Comment by Sanne** [comment]
Triggered a new CI build, as it seems to work better now.

**Pull request merged**
