### PR TITLE
Fix RESTEasy Reactive Default Codestart on 1.11

### LINKED ISSUE #16497: `quarkus:create` adds `quarkus-resteasy` to a project even when `quarkus-resteasy-reactive-jackson` is specified
## Describe the bug
When generating a project with `quarkus-resteasy-reactive-jackson`, `quarkus-resteasy` extension is added to the project's pom.

Related to https://github.com/quarkusio/quarkus/issues/15997

### Expected behavior
`quarkus-resteasy-reactive` and `quarkus-resteasy` are mutually exclusive, the latter should not be added when the former is used, and `quarkus-resteasy-reactive-jackson`  brings in the former.

### Actual behavior
The dependency on `quarkus-resteasy` is added. 
It all works okay if a user explicitly adds `quarkus-resteasy-reactive`

## To Reproduce
```
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create -Dextensions=resteasy-reactive-jackson
```

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #16497

### CODE REVIEW

**Comment by ia3andy** [comment]
@gsmet this one is dedicated to 1.11

**Comment by ia3andy** [comment]
@gsmet the error doesn't seem to be related could you have look?

**Comment by gsmet** [comment]
@ia3andy could you rebase? I should have fixed the CI failures in the branch now.

**Comment by ia3andy** [comment]
Done!

**Review by gsmet — APPROVED** [review]

**Pull request merged**
