### PR TITLE
Take into account the RESTEasy path in SmallRye OpenAPI

### PR DESCRIPTION
**Pull request by gsmet**
This is another version of what was proposed here: https://github.com/quarkusio/quarkus/pull/10636 .

It's based on build items which is cleaner and (hopefully) takes all the cases into account.

Also I added some tests.

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]
Looks good from a brief look

**Review by phillip-kruger — APPROVED** [review]
LGTM. Thanks :)

**Comment by phillip-kruger** [comment]
Fixes #10616

**Comment by crissi98** [comment]
LGTM. Thanks for fixing it :)

**Pull request merged**
