### PR TITLE
Upgrade Hibernate ORM to 5.4.28.Final, Hibernate Reactive to 1.0.0.Beta3

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
GH Actions went berserk on this PR :/

**Comment by gsmet** [comment]
@Sanne AFAICS, there is a regression in Hibernate Reactive. The native tests failed with:
```
2021-02-09T16:58:31.8117291Z 2021-02-09 16:58:31,800 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-1) failed to execute statement [select person0_.id as id1_15_, person0_.address_id as address_5_15_, person0_.name as name2_15_, person0_.status as status3_15_, person0_.uniqueName as uniquena4_15_ from Person2 person0_ where person0_.status = 'LIVING' and person0_.name = $1 order by person0_.id]
2021-02-09T16:58:31.8134255Z 2021-02-09 16:58:31,800 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-1) could not execute query: java.util.concurrent.CompletionException: io.vertx.pgclient.PgException: argument of LIMIT must be type bigint, not type text
2021-02-09T16:58:31.8141509Z 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
2021-02-09T16:58:31.8146909Z 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
2021-02-09T16:58:31.8151916Z 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
2021-02-09T16:58:31.8154230Z 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
2021-02-09T16:58:31.8156854Z 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
2021-02-09T16:58:31.8162107Z 	at org.hibernate.reactive.pool.impl.Handlers.lambda$toCompletionStage$0(Handlers.java:29)
2021-02-09T16:58:31.8164240Z 	at io.vertx.sqlclient.impl.SqlResultHandler.fail(SqlResultHandler.java:103)
2021-02-09T16:58:31.8166198Z 	at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:89)
2021-02-09T16:58:31.8171119Z 	at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:33)
2021-02-09T16:58:31.8173105Z 	at io.vertx.sqlclient.impl.TransactionImpl.lambda$null$3(TransactionImpl.java:181)
2021-02-09T16:58:31.8178105Z 	at io.vertx.sqlclient.impl.TransactionImpl.lambda$rollback$2(TransactionImpl.java:140)
2021-02-09T16:58:31.8182364Z 	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:241)
2021-02-09T16:58:31.8194539Z 	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:88)
2021-02-09T16:58:31.8200952Z 	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
2021-02-09T16:58:31.8227356Z 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
2021-02-09T16:58:31.8262963Z 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
2021-02-09T16:58:31.8283053Z 	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
2021-02-09T16:58:31.8289551Z 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
```

**Comment by gsmet** [comment]
(or there's a problem in Hibernate Reactive with Panache)

**Comment by gsmet** [comment]
Killing CI given we won't be able to merge it.

**Comment by Sanne** [comment]
Ok, sorry to hear. Davide is already working on the fix but let's not hold.

If you want, the ORM upgrade should work taken individually, but IMO it's
ok to wait for post CR.

**Comment by Sanne** [comment]
Closing this. To be replaced with an upgrade of one component at a time.

**Pull request closed without merging**
