### PR TITLE
Kogito extension to include DecisionCodegen

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @mswiderski

### CODE REVIEW

**Comment by mswiderski** [comment]
@tarilabs do we already want it to be always generated for DMN? see the [issue](https://github.com/kiegroup/kogito-examples/pull/93) we just found in Kogito-examples and had to disable the code gen in there

**Comment by tarilabs** [comment]
I don't see the connection.

**Comment by mswiderski** [comment]
the connection is that with this change you can't disable it and the DMN endpoints will be generated but won't be domain specific and as such exposing internals of the DMN execution.

**Comment by gsmet** [comment]
I have the following test error on CI:
```
Caused by: java.lang.NoClassDefFoundError: org/kie/kogito/dmn/DMNKogito
	at org.kie.kogito.app.Application$DecisionModels.<clinit>(Application.java:92)
	at org.kie.kogito.app.Application.<init>(Application.java:23)
	at org.kie.kogito.app.Application_Bean.create(Application_Bean.zig:274)
	at org.kie.kogito.app.Application_Bean.create(Application_Bean.zig:468)
	at io.quarkus.arc.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:77)
	at io.quarkus.arc.AbstractSharedContext.lambda$new$0(AbstractSharedContext.java:17)
	at io.quarkus.arc.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.AbstractSharedContext.get(AbstractSharedContext.java:23)
	at org.kie.kogito.app.Application_Bean.get(Application_Bean.zig:440)
	at org.kie.kogito.app.Application_Bean.get(Application_Bean.zig:43)
	at io.quarkus.it.kogito.jbpm.OrderItemsProcess_Bean.create(OrderItemsProcess_Bean.zig:325)
	at io.quarkus.it.kogito.jbpm.OrderItemsProcess_Bean.create(OrderItemsProcess_Bean.zig:392)
	at io.quarkus.arc.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:77)
	at io.quarkus.arc.AbstractSharedContext.lambda$new$0(AbstractSharedContext.java:17)
	at io.quarkus.arc.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.AbstractSharedContext.get(AbstractSharedContext.java:23)
	at io.quarkus.it.kogito.jbpm.OrderItemsProcess_ClientProxy.arc$delegate(OrderItemsProcess_ClientProxy.zig:81)
	at io.quarkus.it.kogito.jbpm.OrderItemsProcess_ClientProxy.arc_contextualInstance(OrderItemsProcess_ClientProxy.zig:354)
	at io.quarkus.it.kogito.jbpm.OrderItemsProcess_Observer_init_c6e577ab5da11c32214e7d0c965f6089ddc75405.notify(OrderItemsProcess_Observer_init_c6e577ab5da11c32214e7d0c965f6089ddc75405.zig:88)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:228)
	at io.quarkus.arc.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:103)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent23.deploy_0(LifecycleEventsBuildStep$startupEvent23.zig:77)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent23.deploy(LifecycleEventsBuildStep$startupEvent23.zig:36)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:145)
	... 52 more
Caused by: java.lang.ClassNotFoundException: org.kie.kogito.dmn.DMNKogito
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 82 more
```

**Comment by tarilabs** [comment]
@gsmet thanks for the feedback

**Comment by tarilabs** [comment]
Even with CI green, Quarkus maintainers might want to **hold merge** until comment https://github.com/quarkusio/quarkus/pull/4296#issuecomment-537095249 is revoked and this functionality deemed acceptable.

**Comment by gsmet** [comment]
@mswiderski let me know if this should go in or not

**Comment by mswiderski** [comment]
I would prefer to not merge it yet as we need to make sure all issues are addressed and then this could go in as part of 0.5.0 upgrade that hopefully will come next wee this is to avoid potential issues with currently used 0.4.0 version of quarkus

**Comment by gsmet** [comment]
@mswiderski OK, thanks, I marked it with `on-ice`. Let's revisit when you're ready.

**Comment by mswiderski** [comment]
@tarilabs @gsmet this can be closed now, I included these changes in the kogito 0.5.0 upgrade PR https://github.com/quarkusio/quarkus/pull/4511

**Comment by gsmet** [comment]
Thanks for the follow-up.

**Pull request closed without merging**
