### PR TITLE
Ensure that quarkus:dev works with yet to be compiled Kotlin project

### LINKED ISSUE #6931: mvn clean quarkus:dev not working in mixed Kotlin project
**Describe the bug**
Project with mixed Java/Kotlin doesn't compile after moving to `quarkus-maven-plugin:1.2.0.Final`.  Either the Kotlin compiler isn't running at all or it it is not running before Java (as required).

Switching the plugin version back to `1.1.1.Final` the project builds/runs correctly again.

**Expected behavior**
Using mixed Java/Kotlin with Quarkus builds correctly.

**Actual behavior**
Java source files cannot find symbols defined in Kotlin source files and produces compilation errors.

**To Reproduce**
1.  Create a mixed Java/Kotlin project built with Maven.
2. Reference a symbol defined in a Kotlin file from a Java file.
3. Build (e.g. using `package`) or run (e.g. using `quarks:dev`).

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
   Darwin ... 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
 - Output of `java -version`:
   java version "11.0.6" 2020-01-14 LTS
   Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
   Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
 - Output of `java -version`: 
N/A
 - GraalVM version (if different from Java): 
N/A
 - Quarkus version or git rev: 
`1.2.0.Final`

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #6931

### CODE REVIEW

**Comment by gsmet** [comment]
There's a good chance this will conflict with: https://github.com/quarkusio/quarkus/pull/6949 .

I'm also not excited at all to have some Kotlin-specific stuff in our core classes.

**Comment by geoand** [comment]
It will absolutely confict. 

Will already have some Kotlin support in DevMojo this just improves it. We could of course move things out to a Service Loader type of mechanism if we think it's important.

**Comment by gsmet** [comment]
Yeah, but it's already hardcoded? I remember having seen some sort of SPI for the compilers?

**Comment by geoand** [comment]
In quarkus:dev the passing of data to DevContext is hardcoded for Kotlin. 
The SPI you are referring to is for the actual compilation process when the application need to perform compilation of the changed code upon restart.

**Comment by geoand** [comment]
@gsmet How about this: We include this fix, but then perhaps @KaenDagger can work on extracting the Kotlin specific stuff from DevMojo into some nice SPI that will be called by the DevMojo at the appropriate times?

**Comment by geoand** [comment]
For the conflict with #6949 I can cherry pick the commit from that one and include it into this PR. OK @gsmet ?

**Comment by gsmet** [comment]
If so, can you please move the line just after the version check as requested in my review?

**Comment by geoand** [comment]
> If so, can you please move the line just after the version check as requested in my review?

Sure thing

**Review by gsmet — APPROVED** [review]

**Pull request merged**
