### PR TITLE
Add initial routines of reactive h2 client

### PR DESCRIPTION
**Pull request by benstonezhang**
This is initial routines of reactive h2 client, devservice not supported.
Vert.x JDBC client is used for database access.

### CODE REVIEW

**Comment by tsegismont** [comment]
Thank you for sharing this @benstonezhang 

The Vert.x community does not develop a reactive driver for H2. Besides, previous conversations we had in the Quarkus community about H2 showed that users who want a client for this database are actually seeking a way to avoid running the target production database in a container, which is not the process a cloud native framework like Quarkus promotes.

For these reasons, I believe this contribution should be proposed to the [Quarkiverse](https://github.com/quarkiverse/quarkiverse/wiki#getting-an-extension-onboarded).

**Comment by gsmet** [comment]
@benstonezhang let us know if you want to create a Quarkiverse extension for this and maintain it in the future. I can help with converting what you did to a Quarkiverse extension if you need help.

/cc @gastaldi 

Closing this as we won't merge it into the core repository.

**Comment by benstonezhang** [comment]
@gsmet I'm ok to convert it to a Quarkiverse extension, please help. I just know the Quarkiverse project now.

**Comment by gastaldi** [comment]
@benstonezhang I provisioned https://github.com/quarkiverse/quarkus-reactive-h2-client which you should have maintainer access. Take a look at https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created on the next steps to make your extension visible to our tooling and integrated with the ecosystem CI

**Comment by gastaldi** [comment]
Not sure you need SMS to enable 2FA: https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication

**Comment by benstonezhang** [comment]
Now I joined. Thanks for advise. It's strange the TOTP options not shown when I tried it at first time.

**Pull request closed without merging**
