### PR TITLE
Remove long deprecated jib property

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM, I wonder if we could add an Openrewrite rule to migrate it

**Comment by geoand** [comment]
Good idea. Do we have any examples of rules that change properties?

**Comment by gastaldi** [comment]
@geoand see https://github.com/quarkusio/quarkus-updates/blob/7bd7875b2f4014b6eb848f14124b7ae3e94c1f5e/recipes/src/main/resources/quarkus-updates/core/3alpha.yaml#L1169-L1231

**Comment by geoand** [comment]
Cool thanks

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus-updates/pull/19 is the PR

**Pull request merged**
