### PR TITLE
jackson-databind library dependency added

### PR DESCRIPTION
**Pull request by jithset**

### CODE REVIEW

**Comment by cescoffier** [comment]
I may miss the context. Can you remind me of the reason for this addition?

**Comment by jitihn** [comment]
adding jackson-databind  library is not mentioned in the guide.

It will be helpful for users to follow the guide step by step.

**Comment by geoand** [comment]
Do the tests of the fail without this dependency?

**Review by gsmet — CHANGES_REQUESTED** [review]
This PR requires a few wording changes and it looks like `nimbus-jose-jwt` is not used anymore and I would prefer getting rid of Jackson Databind.

See https://github.com/quarkusio/quarkus-quickstarts/issues/325

**Comment by sberyozkin** [comment]
Yes, looks like it is not even used now...

**Comment by gsmet** [comment]
This has been fixed another way. Thanks for the report.

**Pull request closed without merging**
