### PR TITLE
Reactive routes security - use shared Event instance

### PR DESCRIPTION
**Pull request by mkouba**
- to save quite a few allocations per each request

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Every day I learn a new thing... LazyValue :-)

**Comment by geoand** [comment]
Can you please rebase onto master to pick up a CI fix?

Thanks

**Review by stuartwdouglas — APPROVED** [review]

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
Actually will this break dev mode? The Event from the original Container will still be present after restart.

**Comment by mkouba** [comment]
@stuartwdouglas Yes, you're right, this would probably break the dev mode. I added a shutdown hook to clear the cache. I wonder if we should mention this in the "Writing Your Own Extension" guide...

**Comment by mkouba** [comment]
@stuartwdouglas This PR should be ready now.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
