### PR TITLE
Properly create REST Client template path when @Url is used

### LINKED ISSUE #44974: Rest Client metrics show real value in uri attribute instead of path parameter placeholders when used with @Url
### Describe the bug

When using Rest Client with the new @Url annotation for dynamic url together with metrics _quarkus-micrometer-registry-prometheus_ I can see that uri attribute of the metric shows values passed as path parameters instead of path parameters placeholders.

This is problematic as it creates one metric per each path parameter permutation.

I checked that Rest Client with base uri defined in configuration or via RestClientBuilder produces correct metrics. So it must be related to implementation of the new @Url annotation.

### Expected behavior

Metrics should show path parameter placeholder `/example/{id}` to reduce cardinality of the metrics
```
   http_client_requests_seconds_count{clientName="localhost",method="GET",outcome="SUCCESS",status="200",uri="/example/{id}",} 32.0
   http_client_requests_seconds_sum{clientName="localhost",method="GET",outcome="SUCCESS",status="200",uri="/example/{id}",} 0.0397333
```

### Actual behavior

Metrics show `/example/1` with real value `1` instead of path parameter placeholder `{id}`

```
http_client_requests_seconds_count{clientName="localhost",method="GET",outcome="SUCCESS",status="200",uri="/example/1",} 6.0
http_client_requests_seconds_sum{clientName="localhost",method="GET",outcome="SUCCESS",status="200",uri="/example/1",} 0.0097736
```

### How to Reproduce?

Project dependencies

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-rest-client-jackson</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-rest-jackson</artifactId>
</dependency>
```

Test code using @Url

```
@Path("/example")
public class ExampleResource {

    @RestClient
    ExampleClient exampleClient;


    @GET
    @Path("/{id}")
    @Produces(MediaType.TEXT_PLAIN)
    public String example() {
        return "Hello from Quarkus REST";
    }

    @GET
    @Path("/call")
    @Produces(MediaType.TEXT_PLAIN)
    public String call() {
        return exampleClient.getById("http://localhost:8080", "1");
    }

    @Path("/example")
    @RegisterRestClient(baseUri = "http://dummy")
    public interface ExampleClient  {

        @GET
        @Path("/{id}")
        String getById(@Url String baseUri, @PathParam("id") String id);
    }

}
```

Metrics endpoint

`http://localhost:8080/q/metrics`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

java 21.0.1 2023-10-17 LTS

### Quarkus version or git rev

3.17.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brunobat**
- Fixes: #44974

### CODE REVIEW

**Comment by brunobat** [comment]
@geoand, got this reproduced but I miss to understand why the `ClientObservabilityHandler` was not set when the `withNewUri` is called on line 1017.

**Comment by geoand** [comment]
PR updated

**Comment by cescoffier** [comment]
Should it be backported to 3.15? When was this introduced?

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
It was actually introduced in `3.16`

**Comment by geoand** [comment]
We are getting a bunch of docker related errors, so I'm going to have try CI again later

**Comment by geoand** [comment]
Not sure what the deal with the Redis test on Windows is

**Comment by brunobat** [comment]
> Not sure what the deal with the Redis test on Windows is

Looks like there it complains it cannot find a Docker environment: 
https://github.com/quarkusio/quarkus/actions/runs/12254593642/job/34198505954#step:17:18862

**Comment by geoand** [comment]
Yeah, the question is why. We shouldn't be running docker related tests on Windows anyway

**Pull request merged**
