### PR TITLE
Allow for usage of @ConfigProperty on fields without @Inject

### PR DESCRIPTION
**Pull request by manovotn**

### CODE REVIEW

**Review by michalszynkiewicz — COMMENTED** [review]
Looks good to me but I'd rather wait for someone experienced with Quarkus to approve

**Review by mkouba — CHANGES_REQUESTED** [review]
Why a new `Processor` class? I would move the method to the `ConfigBuildStep`. Otherwise looks good?

**Comment by manovotn** [comment]
@mkouba good point, I didn't realize I can stuff multiple build steps in there. 
Changed, squashed and pushed.

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
Looks good now. Let's wait for CI checks...

**Pull request merged**
