### PR TITLE
Remove substitution for DefaultMethodFallbackProvider

### LINKED ISSUE #14394: MP Fault Tolerance - default method fallback doesn't work in native mode
**Summary**
I have a microprofile HttpClient on Native mode, and also a fallback action configured, then I got the following exception:

```
2021-01-18 10:36:17,661 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.RuntimeException: Not implemented in native mode
```

**Expected behavior**
Same as JVM mode (if HTTP request fail, then move on to fallback)

**Actual behavior**
```
2021-01-18 10:36:17,661 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.RuntimeException: Not implemented in native mode
```

**To Reproduce**

Setup an HttpClient pointing to a not found URL

```
@RegisterRestClient(baseUri = "http://microprofile-test:8080/")
public interface HelloClient {
    
    @GET
    @Path("/hello/notFound")
    @Produces(MediaType.TEXT_PLAIN)
    @Asynchronous
    @Fallback(fallbackMethod = "fallback")
    CompletionStage<String> getWithFallback();

    default CompletionStage<String> fallback() {
        return completedFuture("Fallback");
    }
}
```

And then make a query: 
```
@Inject
@RestClient
HelloClient hello;

hello.getWithFallback().thenApply(result -> "Client got: " + result);
```

[Jira ref](https://issues.redhat.com/browse/QUARKUS-697)

### PR DESCRIPTION
**Pull request by Ladicek**
This is because with GraalVM 21, the `DefaultMethodFallbackProvider`
class from SmallRye Fault Tolerance works just fine. The substitution
just threw an exception, which is no longer necessary.

Fixes #14394

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft to let CI run in my fork.

**Comment by Ladicek** [comment]
CI passed in my fork, marking as ready for review.

**Review by gsmet — APPROVED** [review]
Nice, thanks!

**Comment by paulrobinson** [comment]
@gsmet am I right in thinking Quarkus 1.11.x works with GraalVM 20.3, not GraalVM 21? In which case the backport of this PR to 1.11 will not be possible?

**Pull request merged**
