### PR TITLE
Don't include startup probe for KNative manifests

### LINKED ISSUE #33944: Kubernetes + Smallrye Health Extensions: Knative deployment fails due to presence of startupProbe
### Describe the bug

The Smallrye health extension adds a startupProbe to the generated target/kubernetes/knative.yml when I set my deployment-target to knative.  The Knative admission controller however does not allow the startupProbe element, resulting in a failed deployment.   

### Expected behavior

I expect the knative.yml to not contain the unsupported startupProbe element.

### Actual behavior

_No response_

### How to Reproduce?

Steps to reproduce:

1. quarkus create app knative-bug -x kubernetes -x smallrye-health
2. mvn package -Dquarkus.kubernetes.deployment-target=knative
3. verify that a startupProbe is present in the generated target/knative.yml
4. deploy to Knative, and observe the following error:

```
[ERROR] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://xyz.openshiftapps.com:6443/apis/serving.knative.dev/v1/namespaces/blabla/services. Message: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.containers[0].startupProbe. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.containers[0].startupProbe, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes #33944

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
We're struggling with the Knative deployments quite often. So, I would prefer to add the test in the maven invoker test suite instead of the quarkus standard way. 

The solution looks good.

**Comment by geoand** [comment]
Okay, no problem

**Comment by geoand** [comment]
I updated on the `maven-invoker-way` tests. Is that what you had in mind?

**Review by Sgitario — APPROVED** [review]
Yes!

**Comment by geoand** [comment]
I have no idea why this does not work as expected on CI. Seems like some Maven artifact issue, but I have no idea what it could be

**Comment by Sgitario** [comment]
> I have no idea why this does not work as expected on CI. Seems like some Maven artifact issue, but I have no idea what it could be

Apart from the test you have changed "KnativeWithHealthUsingManagementInterfaceTest", you also need to update the test "KnativeWithHealthTest".

**Comment by geoand** [comment]
Oh wow, I didn't even realize it was a different test that was failing 🤦🏼

**Pull request merged**
