### PR TITLE
Improve Quarkus CLI tests to check for --native flag output

### PR DESCRIPTION
**Pull request by kdubois**
I added a few additional tests to make sure the --native flag is taking into account and that maven/gradle effectively do a native build.

### CODE REVIEW

**Comment by maxandersen** [comment]
having the test for verifying --native impact is probably worthwhile but I would expect it to be additional tests rather than change existing ones. 

@ebullient wdyt?

**Comment by gsmet** [comment]
Please make sure you rebase instead of introducing merge commits. I will rebase using GitHub UI, it should get rid of the merge commits.

Thanks!

**Review by ebullient — APPROVED** [review]

**Comment by ebullient** [comment]
> 

This is just making sure the required parameters are emitted in the end.

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
