### PR TITLE
Support for existing kubernetes resources

### PR DESCRIPTION
**Pull request by iocanel**
The is a reincarnation #8521, which I had to recreate from scratch, as I abused that branch beyond repair (don't ask).

### CODE REVIEW

**Comment by iocanel** [comment]
@gsmet: Your suggestions on the original pull request have all been manually applied to this one.

**Comment by maxandersen** [comment]
my question from the other PR still valid: what attributes/rules are replaced and what are contained ? is it just the specific known image references or is there additional "magic guessing" in place ?

**Comment by iocanel** [comment]
The way the Kubernetes extension works, is that we start with a minimal resource and for each configuration option or build item provided we apply the change needed to resource. The same principal is followed when the starting point is an existing resource.

In other words there are no rules, we just replace what configuration dictates.
Examples:

The user provides an existing deployment and sets via application properties:

i. The num of replicas. The result will be the provided resource with the configured replicas.

ii. An env variable. The result will be the provided resource with the new env car (retaining old ones if available and replacing any that clashes). Same goes for labels, annotations, ports, volumes etc.

The only case where the changed we apply might not be as fine grained is probes. With probes, we will just replace them (if smallrye health is available).

**Comment by maxandersen** [comment]
Thanks for the explanation!

**Comment by geoand** [comment]
@maxandersen are you OK with this or does it need changes?

**Comment by geoand** [comment]
This needs a rebase now

**Comment by maxandersen** [comment]
LGTM

**Comment by gsmet** [comment]
I rebased, fixed a conflict and squashed things a bit. In general, better have an atomic commit for the whole feature rather than three for feature / doc / test.

It makes backporting more tedious than necessary in case we want to backport some features.

**Comment by gsmet** [comment]
@iocanel wasn't able to push to your branch, could you authorize me to? There should be a checkbox somewhere.

Thanks.

**Comment by iocanel** [comment]
@gsmet: Done.

**Comment by iocanel** [comment]
I think I am doing something wrong. It keeps getting unchecked each time I refresh.

**Comment by iocanel** [comment]
@gsmet, I probably miss something. Let me push the fix myself.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/9341 with what I had. Let's close this one.

**Pull request closed without merging**
