### PR TITLE
Fix mongodb-client health test after client creation was made lazy

### PR DESCRIPTION
**Pull request by famod**
Better alternative to #21539. Relates to #20935.

See also: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/main.20is.20broken/near/261926866

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Just an idea: instead of ordering the tests, isn't easier to just perform another call in the same test method before the /health endpoint is called?

**Comment by famod** [comment]
Sure. This would have the benefit that you can also run the single test method alone.

**Review by gastaldi — APPROVED** [review]

**Comment by famod** [comment]
I added a simple GET instead. I couldn't use `Utils.callTheEndpoint()` because this is doing too much.

**Comment by loicmathieu** [comment]
Late to the party but thanks!

**Pull request merged**
