### PR TITLE
Update keycloak version to 8.0.1

### LINKED ISSUE #5868: quarkus-keycloak-authorization does not work with Keycloak 8
**Describe the bug**
This error is reported:
```
2019-11-28 13:58:50,271 WARN  [org.key.ada.KeycloakDeployment] (executor-thread-1) Failed to load URLs from http://localhost:8180/auth/realms/quarkus/.well-known/openid-configuration: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.keycloak.protocol.oidc.representations.OIDCConfigurationRepresentation` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3071)
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:94)
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:79)
	at org.keycloak.adapters.KeycloakDeployment.getOidcConfiguration(KeycloakDeployment.java:224)
	at org.keycloak.adapters.KeycloakDeployment.resolveUrls(KeycloakDeployment.java:178)
	at org.keycloak.adapters.KeycloakDeployment.getRealmInfoUrl(KeycloakDeployment.java:232)
	at org.keycloak.adapters.rotation.AdapterTokenVerifier.createVerifier(AdapterTokenVerifier.java:107)
	at org.keycloak.adapters.rotation.AdapterTokenVerifier.verifyToken(AdapterTokenVerifier.java:47)
	at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.requestAuthorizationToken(KeycloakAdapterPolicyEnforcer.java:172)
	at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.isAuthorized(KeycloakAdapterPolicyEnforcer.java:65)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:118)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:43)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:28)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1.run(HttpAuthorizer.java:65)

```
Please follow #5822 for more information.

### PR DESCRIPTION
**Pull request by SlyngDK**
Fixes #5868

### CODE REVIEW

**Review by sberyozkin — CHANGES_REQUESTED** [review]
Please also update [this property](https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L82)

**Review by gsmet — CHANGES_REQUESTED** [review]
Also https://github.com/quarkusio/quarkus/blob/master/ci-templates/native-build-steps.yaml#L39 needs a change.

Better grep for 7.0.1 in the source repo and see what needs changing.

**Review by machi1990 — COMMENTED** [review]
Similar changes have to be applied for the quickstarts - https://github.com/quarkusio/quarkus-quickstarts/tree/development/security-keycloak-authorization-quickstart as in https://github.com/quarkusio/quarkus-quickstarts/pull/387 

This could be done in a followup PR there. Just mentioned it so that we do not forget about it.

**Comment by sberyozkin** [comment]
@rsvoboda Ho Rostislav, can you please comment which issues you've seen with 8.0.0 in the native mode ?

**Comment by rsvoboda** [comment]
I had these changes [keycloak-8-diff.txt](https://github.com/quarkusio/quarkus/files/3902244/keycloak-8-diff.txt)

And executed https://github.com/quarkusio/quarkus/tree/master/integration-tests/keycloak-authorization and https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-keycloak-authorization-quickstart in native mode

Saw these errors: [keycloak-8-errors.txt](https://github.com/quarkusio/quarkus/files/3902250/keycloak-8-errors.txt)

**Comment by gsmet** [comment]
Yeah, my recollection was that we had failures with latest Keycloak.

**Comment by sberyozkin** [comment]
@pedroigor Hi Pedro, looks like in Keycloak 8 the authorization client responses have some extra data that can not be mapped by Jackson to some internal beans in one of the KC APIs, perhaps it is a known 8.0 issue ? I've looked through the `quarkus-keycloak-authorization` and I don't anything related there.

**Comment by pedroigor** [comment]
I think the reason is that `OIDCConfigurationRepresentation` is not registered for reflection. I'll check it out.

**Comment by pedroigor** [comment]
@rsvoboda This [change](https://github.com/pedroigor/quarkus/tree/issue-5868) seems to fix the issue. Do you want me to send a separated PR or you would just include it here ?

**Review by pedroigor — COMMENTED** [review]
See https://github.com/pedroigor/quarkus/tree/issue-5868 for a fix.

**Comment by sberyozkin** [comment]
@pedroigor Hi Pedro, thanks
@SlyngDK Can you please update your PR, see https://github.com/pedroigor/quarkus/tree/issue-5868

**Comment by SlyngDK** [comment]
@sberyozkin I have updated the PR with changes from https://github.com/pedroigor/quarkus/tree/issue-5868, and updated to the newest keycloak version 8.0.1.

**Comment by sberyozkin** [comment]
@SlyngDK thanks, hopefully it will all pass now :-)

**Review by gsmet — DISMISSED** [review]
Just a note that this one needs to be squashed before merging. We don't want broken commits in the tree.

Thanks! (and feel free to dismiss this review when done)

**Review by sberyozkin — APPROVED** [review]
@gsmet as agreed, approving now :-). as I've squashed the commits

**Pull request merged**
