### PR TITLE
Fixed the path to the extension catalog json for the all-config gen

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Comment by famod** [comment]
@gsmet I think the bot needs to be adjusted to cope with the now expectedly skipped (not cancelled!) jobs. ⬆️

**Comment by famod** [comment]
Nevermind, it's the same problem as in https://github.com/quarkusio/quarkus/pull/17003#issuecomment-832661939 and we've been discussing those skipped runs already: https://github.com/quarkusio/quarkus-bot/issues/97

**Comment by famod** [comment]
I took the liberty to re-run the workflow, now after #17022 was merged. That CI fix should be picked up automatically here.

**Comment by famod** [comment]
@aloubyansky I hope you don't mind the rebase.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
