### PR TITLE
Metaspace improvements in QuarkusUnitTest - round 1

### PR DESCRIPTION
**Pull request by yrodiere**
@gsmet This is what I have so far. Nothing groundbreaking, and I'm sure it doesn't prevent outrageous metaspace consumptions, but that solves part of the problem, at least.

Best reviewed commit by commit.

I'll try to continue later with more fixes as I identify leaks and solutions.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Interesting and looks good to me.

**Comment by gsmet** [comment]
@aloubyansky I let you have a look at this one.

**Comment by yrodiere** [comment]
Looks like classes of quarkus-bootstrap are not accessible to some tests... they were accessible to quarkus-orm-deployment tests, which is the one I tested locally. I'll see what's up.

**Comment by yrodiere** [comment]
Alright, I moved the JNDI stuff to `quarkus-bootstrap-runner`, which seems accessible from everywhere; it's a (non-optional) dependency of quarkus-core so I'm guessing it's always there, regardless of the packaging type? At least I hope so :/

**Comment by yrodiere** [comment]
The only failure is evidently flaky and caused by `OutOfMemoryError: Metaspace`, which is one of the problems we're in the process of solving, so I think it's just a pre-existing problem.

I think we're good to merge @gsmet ?

**Comment by gsmet** [comment]
A bit late but yes :).

**Pull request merged**
