### PR TITLE
Quarkus Funqy FaaS Framework - initial implementation

### PR DESCRIPTION
**Pull request by patriot1burke**
* Initial implementaiton of Quarkus Funqy FaaS Framework
* Refactored amazon-lambda extension into some reusable common modules
* Added amazon-lambda stream handler test

### CODE REVIEW

**Comment by patriot1burke** [comment]
Want to get this merged even though its a WIP.  Merge conflicts are becoming an issue.

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gastaldi** [comment]
It would be nice to revisit (at some point) moving the Amazon bits to a separate repository and add them to the `quarkus-universe-bom` in a similar way that camel-quarkus does

**Comment by patriot1burke** [comment]
@gastaldi Is everything going in that direction?  Moving to a separate repo?  The Lambda code isn't a lot of code.  Most of these extensiosn aren't.  It just might be a matter of the dependencies?  *shrug*

**Comment by gastaldi** [comment]
@patriot1burke I think so. That would give teams more control over releases

**Comment by patriot1burke** [comment]
@gastaldi I don't really want to move everything out until Quarkus core becomes really stable.  There's still some work in lambda that I want to do that may require core changes.

**Comment by oztimpower** [comment]
I'm seeing this exception when running the Unit tests from the Maven Archetype for a new project, post this commit.

When I roll back to 1.3.0.Final from 999-SNAPSHOT the error disappears. 

Gradle recognises this RuntimeException as a failure in the Unit Test, whereas Maven ignores it, that's how I picked it up (via Gradle).

```
Exception in thread "Quarkus Test Cleanup Shutdown task" java.lang.RuntimeException: Unable to stop Quarkus test resource io.quarkus.amazon.lambda.test.LambdaResourceManager@22f02996
	at io.quarkus.test.common.TestResourceManager.close(TestResourceManager.java:88)
	at io.quarkus.test.junit.QuarkusTestExtension$1.close(QuarkusTestExtension.java:124)
	at io.quarkus.test.junit.QuarkusTestExtension$2.run(QuarkusTestExtension.java:133)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at io.quarkus.amazon.lambda.test.LambdaResourceManager.stop(LambdaResourceManager.java:120)
	at io.quarkus.test.common.TestResourceManager.close(TestResourceManager.java:86)
	... 3 more
```

**Comment by oztimpower** [comment]
BTW I like the way you refactored, the AbstractLambdaPollLoop and other simplifications.

**Pull request merged**
