### PR TITLE
RESTEasy Reactive thread fixes

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Relates to #18977

There are still issues though, as the vert.x pool is not enforcing
affinity.

### CODE REVIEW

**Comment by geoand** [comment]
This doesn't fix the issue though, does it?

**Comment by stuartwdouglas** [comment]
It does not, however it is part of the solution.

**Review by geoand — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
@stuartwdouglas not sure about your third commit? If we want it in, we need a better commit message (or a squash).

**Comment by stuartwdouglas** [comment]
Closing for now.

**Pull request closed without merging**
