### PR TITLE
Introduce handling of more advanced generics cases in JandexUtil

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
CI failed because a PR was merged in the meantime. I'll restart when all other tests finish.

**Comment by geoand** [comment]
I rebased the PR onto master

**Comment by geoand** [comment]
@FroMage can you check at some point if these changes satisfy the requirements you have in the Panache module?

**Review by FroMage — APPROVED** [review]
Frankly I find the implementation complex, but as long as you're maintaining it, that's fine by me :)

**Pull request merged**
