### PR TITLE
upgrade to kogito 0.4.0

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by mswiderski** [comment]
if possible I'd like to include it in the next release which I believe is 0.23.0 and if there is still an option to do so I can prepare another PR for another branch.

**Comment by gsmet** [comment]
@mswiderski looks like there is a conflict in the bom? Can you rebase?

**Comment by mswiderski** [comment]
@gsmet rebase done

**Review by gsmet — APPROVED** [review]
Let’s wait for CI

**Pull request merged**
