### PR TITLE
Make sure that DotEnvConfigSource is used for runtime properties as well

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by dmlloyd — APPROVED** [review]

**Comment by geoand** [comment]
@dmlloyd just as an FYI I had to make the `DotEnvConfigSource` Serializable to get the TCK to pass

**Review by dmlloyd — APPROVED** [review]

**Comment by geoand** [comment]
The test failure is completely unrelated:

```
2020-03-03T14:14:04.6046929Z Caused by: java.io.IOException: error=26, Text file busy
2020-03-03T14:14:04.6048563Z 	at java.lang.UNIXProcess.forkAndExec(Native Method)
2020-03-03T14:14:04.6050232Z 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
2020-03-03T14:14:04.6051870Z 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
2020-03-03T14:14:04.6053558Z 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2020-03-03T14:14:04.6054831Z 	... 63 more
2020-03-03T14:14:04.6054888Z 
2020-03-03T14:14:04.9553850Z [INFO] 
2020-03-03T14:14:04.9559928Z [INFO] Results:
2020-03-03T14:14:04.9581587Z [INFO] 
2020-03-03T14:14:04.9582072Z [ERROR] Errors: 
2020-03-03T14:14:04.9583011Z [ERROR]   CollectionManagementTest>MongoTestBase.startMongoDatabase:63 Â» IO Cannot run p...
```

**Comment by dmlloyd** [comment]
> The test failure is completely unrelated:
> 
> ```
> 2020-03-03T14:14:04.6046929Z Caused by: java.io.IOException: error=26, Text file busy
> 2020-03-03T14:14:04.6048563Z 	at java.lang.UNIXProcess.forkAndExec(Native Method)
> 2020-03-03T14:14:04.6050232Z 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
> 2020-03-03T14:14:04.6051870Z 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
> 2020-03-03T14:14:04.6053558Z 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
> 2020-03-03T14:14:04.6054831Z 	... 63 more
> 2020-03-03T14:14:04.6054888Z 
> 2020-03-03T14:14:04.9553850Z [INFO] 
> 2020-03-03T14:14:04.9559928Z [INFO] Results:
> 2020-03-03T14:14:04.9581587Z [INFO] 
> 2020-03-03T14:14:04.9582072Z [ERROR] Errors: 
> 2020-03-03T14:14:04.9583011Z [ERROR]   CollectionManagementTest>MongoTestBase.startMongoDatabase:63 Â» IO Cannot run p...
> ```

`ETXTBSY`'s definition is `The specified executable was open for writing by one or more processes.`  What's the rest of the stack trace?  It seems like it's launching a program that is still in the process of being installed.

**Comment by geoand** [comment]
```
2020-03-03T14:14:04.3906315Z [INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.459 s - in io.quarkus.mongodb.reactive.legacy.AxleBasicInteractionTest
2020-03-03T14:14:04.3907097Z [INFO] Running io.quarkus.mongodb.reactive.CollectionManagementTest
2020-03-03T14:14:04.5876087Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.193 s <<< FAILURE! - in io.quarkus.mongodb.reactive.CollectionManagementTest
2020-03-03T14:14:04.5879776Z [ERROR] io.quarkus.mongodb.reactive.CollectionManagementTest  Time elapsed: 0.193 s  <<< ERROR!
2020-03-03T14:14:04.5886109Z java.io.IOException: Cannot run program "/home/runner/work/quarkus/quarkus/extensions/mongodb-client/runtime/target/extract-9e349165-981b-4f70-865a-34445099beebextractmongod": error=26, Text file busy
2020-03-03T14:14:04.5889780Z 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
2020-03-03T14:14:04.5892734Z 	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:213)
2020-03-03T14:14:04.5895248Z 	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
2020-03-03T14:14:04.5898086Z 	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
2020-03-03T14:14:04.5900138Z 	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
2020-03-03T14:14:04.5902173Z 	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
2020-03-03T14:14:04.5904779Z 	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
2020-03-03T14:14:04.5906985Z 	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
2020-03-03T14:14:04.5909152Z 	at io.quarkus.mongodb.reactive.MongoTestBase.startMongoDatabase(MongoTestBase.java:63)
2020-03-03T14:14:04.5911000Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-03-03T14:14:04.5913120Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-03-03T14:14:04.5915231Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-03-03T14:14:04.5916861Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-03-03T14:14:04.5919191Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
2020-03-03T14:14:04.5923411Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2020-03-03T14:14:04.5926061Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2020-03-03T14:14:04.5928301Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-03-03T14:14:04.5930771Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
2020-03-03T14:14:04.5933304Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
2020-03-03T14:14:04.5936176Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-03-03T14:14:04.5938655Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-03-03T14:14:04.5941658Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-03-03T14:14:04.5944888Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-03-03T14:14:04.5948782Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-03-03T14:14:04.5951745Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-03-03T14:14:04.5954008Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-03-03T14:14:04.5956237Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-03-03T14:14:04.5958997Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$8(ClassBasedTestDescriptor.java:375)
2020-03-03T14:14:04.5961369Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-03-03T14:14:04.5964127Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:373)
2020-03-03T14:14:04.5966482Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:193)
2020-03-03T14:14:04.5968795Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
2020-03-03T14:14:04.5971269Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
2020-03-03T14:14:04.5973511Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-03-03T14:14:04.5975930Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-03-03T14:14:04.5977903Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-03-03T14:14:04.5980343Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-03-03T14:14:04.5982881Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-03-03T14:14:04.5985378Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-03-03T14:14:04.5987500Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-03-03T14:14:04.5989173Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-03-03T14:14:04.5992165Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-03-03T14:14:04.5994937Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-03-03T14:14:04.5997131Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-03-03T14:14:04.5999806Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-03-03T14:14:04.6001931Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-03-03T14:14:04.6005127Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-03-03T14:14:04.6007538Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-03-03T14:14:04.6009953Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-03-03T14:14:04.6012113Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-03-03T14:14:04.6014999Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-03-03T14:14:04.6017633Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-03-03T14:14:04.6020048Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-03-03T14:14:04.6022378Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
2020-03-03T14:14:04.6024610Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
2020-03-03T14:14:04.6027023Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
2020-03-03T14:14:04.6029078Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
2020-03-03T14:14:04.6031115Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
2020-03-03T14:14:04.6033600Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
2020-03-03T14:14:04.6036113Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
2020-03-03T14:14:04.6038446Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2020-03-03T14:14:04.6041418Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2020-03-03T14:14:04.6043387Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2020-03-03T14:14:04.6045278Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2020-03-03T14:14:04.6046929Z Caused by: java.io.IOException: error=26, Text file busy
2020-03-03T14:14:04.6048563Z 	at java.lang.UNIXProcess.forkAndExec(Native Method)
2020-03-03T14:14:04.6050232Z 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
2020-03-03T14:14:04.6051870Z 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
2020-03-03T14:14:04.6053558Z 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2020-03-03T14:14:04.6054831Z 	... 63 more
```

There seem to be infra issues (other jobs getting cancelled) so I'll need to restart anyway..

**Comment by dmlloyd** [comment]
This looks to me like it could be another flapdoodle bug - perhaps it's writing out the executable but doesn't finish writing it out before it runs it.

**Comment by geoand** [comment]
> This looks to me like it could be another flapdoodle bug - perhaps it's writing out the executable but doesn't finish writing it out before it runs it.

Yeah, we should just get rid of it altogether...

**Pull request merged**
