### PR TITLE
Fix Windows input issue

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
What if `-Djansi.passthrough=true` is set? I'm using this on Windows with Git Bash because that shell doesn't need Jansi for coloring...

**Comment by stuartwdouglas** [comment]
Did that fix this issue? I just saw it starting an input pump thread in the terminal constructor, not guarded by an if block.

**Comment by famod** [comment]
I can check later today. My question was primarily about whether you were aware of that property (and checked whether it does anything here).

**Comment by famod** [comment]
PS: My comment shall not prevent the merge of this PR.
I would have to take a closer look and chances are I won't be able to do so today.

**Pull request merged**
