### PR TITLE
refactor: do not use deprecated DefaultAnnotationScannerExtension class

### PR DESCRIPTION
**Pull request by machi1990**

### CODE REVIEW

**Comment by EricWittmann** [comment]
Seems reasonable to me - what do you think @MikeEdgar ?

**Comment by gsmet** [comment]
Yeah the thing worrying me a bit is the `return null` appearing now.

**Comment by machi1990** [comment]
> Yeah the thing worrying me a bit is the `return null` appearing now.

This seems to be the default value returned by `AnnotationScannerExtension#resolveAsyncType()`.

**Comment by MikeEdgar** [comment]
+1

Returning `null` is valid - it simply means the `Type` could not be resolved. As @machi1990 mentioned, it's the same value being returned by the call of the `super` method today.

**Review by gsmet — APPROVED** [review]
Got the approval from the SmallRye OpenAPI team so let's merge!

**Comment by gsmet** [comment]
Thanks for the reviews!

**Pull request merged**
