### PR TITLE
Allow disabling Jackson ObjectMapper WRITE_DURATIONS_AS_TIMESTAMPS

### LINKED ISSUE #28605: Allow disabling Jackson ObjectMapper WRITE_DURATIONS_AS_TIMESTAMPS
### Description

It would be nice is to disable `WRITE_DURATIONS_AS_TIMESTAMPS` using config.
Currently quarkus supports disabling `WRITE_DATES_AS_TIMESTAMPS` which is very similar.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by davidfrickert**
Fixes #28605

### CODE REVIEW

**Comment by davidfrickert** [comment]
I opted to set the default config the same that is provided by Jackson - which is to serialize Durations as Timestamps - in order to not break existing Quarkus applications that are using the default value.

**Comment by davidfrickert** [comment]
It seems I missed the Intellij IDEA configuration part of the import order file. Going to install it and fix the import order of the tests.

**Comment by gsmet** [comment]
Just run `mvn process-sources`.

**Comment by gsmet** [comment]
Also please squash all the commits when you're done.

**Comment by davidfrickert** [comment]
Thanks for the tip @gsmet. I ended up installing the plugin and fixing the imports with it. Also did a force push with a single commit. Just ran `mvn process-sources` and it didn't perform any changes so it should be good now.

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Pull request merged**
