### PR TITLE
Add GraalVM 21.3 compatibility support for resource registration 

### LINKED ISSUE #20226: Signature of com.oracle.svm.core.configure.ResourcesRegistry.ignoreResources changed in GraalVM/Mandrel 21.3-dev
https://github.com/oracle/graal/pull/3774 changed the signature of `ignoreResources` as follows:
```diff
-                public void ignoreResources(String pattern) {
+                public void ignoreResources(ConfigurationCondition condition, String pattern) {
```

This results in Quarkus throwing a `NoSuchMethodError` exception at the code generated by: https://github.com/quarkusio/quarkus/blob/9b1424df9aee33a2e89058d9d879d58ab8a80e3b/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java#L78-L80

### PR DESCRIPTION
**Pull request by zakkak**
oracle/graal#3774 changed the signature of ignoreResources as follows:

```
- public void ignoreResources(String pattern) {
+ public void ignoreResources(ConfigurationCondition condition, String pattern) {
```

~~This results in Quarkus throwing a `NoSuchMethodError` exception at the
code generated by NativeImageAutoFeatureStep~~
and deprecated the old API (see https://github.com/oracle/graal/pull/3803)

This patch looks for the right method based on the GraalVM/Mandrel version.

Closes: #20226

### CODE REVIEW

**Comment by zakkak** [comment]
Marking as Draft till we confirm that the change is going to land in the upcoming 21.3

**Comment by Sanne** [comment]
oops sorry @zakkak I didn't mean to promote it from "draft" status. Do you know how to undo that?

**Comment by zakkak** [comment]
The test failures seem unrelated to this PR, please let me know if you see something wrong with it that I am missing.

**Comment by zakkak** [comment]
Marking for backport to make sure Q 2.2.x is compatible with the upcoming GraalVM/Mandrel 21.3

**Review by geoand — APPROVED** [review]

**Pull request merged**
