### PR TITLE
Change CaffeineCache eviction and expiration policies programmatically

### LINKED ISSUE #29934: Set quarkus-cache properties at runtime
### Description

The properties for the `quarkus-cache` extension look like they should be settable at runtime. At the very least: `enabled`, `initial-capacity`, `maximum-size`, `expire-after-write`, `expire-after-access`.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by gwenneg**
This PR offers another way to partially fix #29934. The main fix is in #30000.

### CODE REVIEW

**Comment by gwenneg** [comment]
ℹ️ I will update this PR and add the missing doc section tomorrow.

**Comment by geoand** [comment]
> information_source I will update this PR and add the missing doc section tomorrow.

Please ping when this is done :)

**Comment by gwenneg** [comment]
@geoand I've updated the doc.

**Comment by geoand** [comment]
What do you have in mind for this WRT https://github.com/quarkusio/quarkus/pull/30000?

**Comment by gwenneg** [comment]
#30000 allows changing the configuration before the app is started. After the app is started, even though the Quarkus configuration can be updated programmatically, it is impossible to change the configuration of the caches because they are built at startup.

With this PR, some of the config values can be updated on the fly which may be convenient for some Quarkus users. This PR is an additional step towards cache config flexibility.

**Comment by geoand** [comment]
Gotcha, thanks!

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
I'll merge this, feel free to close the initiating issue when you think it's done

**Pull request merged**
