### PR TITLE
Fix flakey test

### LINKED ISSUE #14392: ConnectionPoolsClosedTest is racy
**Description**
The condition on line 35 of ConnectionPoolsClosedTest depends on a background thread to not only have completed its task (which we wait for) but it also requires the Thread to have been flagged as no longer running - which we're not waiting for.

This makes the test occasionally fail on CI.

**Implementation ideas**
Wait for the background thread to having been killed.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This test requires the executor thread to be finished,
but waiting for 1ms does not guarentee this as the thread
may not get scheduled.

Fixes:  #14392

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
See failure on run https://github.com/quarkusio/quarkus/pull/14413/checks?check_run_id=1732679737

**Review by gastaldi — APPROVED** [review]

**Comment by geoand** [comment]
I assume this fixes #14392, right?

**Comment by stuartwdouglas** [comment]
I did not notice there was already an issue for it

**Comment by geoand** [comment]
No worries :). I just wanted to make sure @Sanne was aware of your fix

**Review by Sanne — APPROVED** [review]
perfect, thanks.

**Pull request merged**
