### PR TITLE
Changes to conform to RESTEasy 4.5.7.Final

### PR DESCRIPTION
**Pull request by ronsigal**
Issue https://github.com/quarkusio/quarkus/issues/12210

### CODE REVIEW

**Comment by cescoffier** [comment]
@ronsigal It seems to break `MultiRxInvokerImpl`. Did the API change (it's a compilation issue).

**Comment by asoldano** [comment]
@cescoffier (/cc @ronsigal ), I believe the resteasy version bump was simply forgotten, please check https://github.com/quarkusio/quarkus/pull/12232

**Comment by ronsigal** [comment]
Hi @cescoffier,

Sorry for not being clearer. These changes should allow the Quarkus testsuite to pass **after** upgrading to RESTEasy 4.5.7.Final.

-Ron

**Comment by cescoffier** [comment]
Thanks @ronsigal .

I believe we would need a bit of coordination to get everything in a single PR / commit.

**Comment by ronsigal** [comment]
Hey @cescoffier,

re: "I believe we would need a bit of coordination to get everything in a single PR / commit."

Yes, you're right. @asoldano did that in  https://github.com/quarkusio/quarkus/pull/12232. I'll close this one.

**Comment by cescoffier** [comment]
oh cool! Thanks I missed it!

**Pull request closed without merging**
