### PR TITLE
[3.2] Backports of downstream doc adjustments

### PR DESCRIPTION
**Pull request by gsmet**
/cc @MichalMaler

### CODE REVIEW

**Comment by ppalaga** [comment]
Please hold on. This may cause a lot of work in dependent projects

**Comment by ppalaga** [comment]
This breaks links pointing to specific config properties in maintenance branches of the docs. For upstream for sure, for downstream we'd need to let our docs team ack this because I have no idea how they handle this. Given that Quarkus docs team did not insist on porting this to 3.2 I wonder why would this be necessary at all?

**Comment by MichalMaler** [comment]
> This breaks links pointing to specific config properties in maintenance branches of the docs. For upstream for sure, for downstream we'd need to let our docs team ack this because I have no idea how they handle this. Given that Quarkus docs team did not insist on porting this to 3.2 I wonder why would this be necessary at all?

Hello, @ppalaga . I will explain this shortly. Also, provide an alternative if this will be not possible to merge.
Just need to get out of the meeting when  I will be presenting in a moment. BRB

**Comment by MichalMaler** [comment]
@ppalaga To "Why we (docs) need these changes to be part of main and 3.2.
Let me use the reply I provided Yoann just a few days back.

_Hello Yoann,

You at least deserve to know why this is happening. RHBQ was stuck for a long time on the old and unsupported publishing platform Pantheon II. We implemented a few workarounds to make publishing possible, yet operating on that tool was painful. Also, we were the last team there; the others had already fled to something else.

While the migration to the older but technically savvier brother, Pantheon 1, offers many benefits and solves hundreds of small issues, it causes the one we are resolving right now. I asked the CSS tool team and bccutil gurus, but I was told that a rule that makes reading these IDs problematic cant be bypassed and rule can not be shuted down because of security reasons. I did what I could but needed to turn to upstream masterminds again for help.

I asked Guillaume if the transformation of these links and IDs could be part of our script, but he proposed this approach and unification. I am sorry to hear that it causes some problems, but once this is resolved, we should be in a much better position and operate on a better publishing tool overall.

On behalf of the entire docs team, I want to apologize for any additional workload and problem-solving these changes bring._

The `3.2` is a source for our RHBQ 3.2 release. Since we are migrating from one publication portal to another, we still need to provide our users with the docs that reach at least one release back.

From now on, we will be on a better publishing platform with better tooling, support, and the possibility to add or modify little gambits here and there.

If these changes can not be a part of the 3.2, we need to find a way how to get them solely to the RHBQ repository; only with the fact that it will be against RH police in which we agree that All the content is checked and verified by QE Upstream First.

The whole situation about RHBQ 3.2 was problematic, and it was caused by a huge delay between 3.2 and main.
I was assured that these situations should not be repeated in the future.
  
The ID issue description that @gsmet fixing by these backports can be found here. Problem number [2]
https://docs.google.com/document/d/1GhkifPjVRsDPkxuvSdVeLa5k6rnfRgo5988I9k4mHfc/edit

**Comment by gsmet** [comment]
> Given that Quarkus docs team did not insist on porting this to 3.2 I wonder why would this be necessary at all?

Actually, as said by Michal above, they requested it after in the other PR thus why I did it. I'm not exactly looking for ways to waste my time doing useless backports :).

I understand this breaks things. I know it's not ideal. Didn't find any other practical way though so why I did it this way.

**Review by MichalMaler — APPROVED** [review]

**Review by aloubyansky — APPROVED** [review]

**Review by jmartisk — APPROVED** [review]

**Comment by MichalMaler** [comment]
> We are discussing this within Camel Quarkus team. Let me repeat that I am fine with doing this in 3.7+. Questionable is only the old stuff I'd prefer not to touch. Would it perhaps be feasible to keep the old behavior by default in 3.2 and have an option to enable it only for projects that really want it?

@ppalaga @gsmet 
Hello, if that will help in anyway, here is the list of Guides we are publishing for RHBQ 3.2:
https://docs.google.com/document/d/1PiR-IDgFnJvxyxLip1qZolOe-OFm1BfzmBkyc56tWYc/edit#heading=h.hp243j2rd0ec

The 3.7 releases will additionally content all possible Security guides.
Cheers!

**Comment by gsmet** [comment]
@ppalaga would it be problematic to merge this now to unblock the doc team? I will work on making it conditional next week and it will be fixed before we even think about releasing the next 3.2. You have my word.

**Comment by ppalaga** [comment]
> would it be problematic to merge this now to unblock the doc team? I will work on making it conditional next week and it will be fixed before we even think about releasing the next 3.2. You have my word.

Sounds good, thank you very much!

**Comment by gsmet** [comment]
Merging then. Thanks!

**Pull request merged**
