### PR TITLE
feat: group name version are inherited from container image.

### PR DESCRIPTION
**Pull request by iocanel**
group, name & version are config properties that are present in:

- container-image
- kubernetes
- opesnhift
- knative 

This pull request changes kubernetes, openshift and knative config objects so that they default to container-image for these 3 properties (group, name & version).

### CODE REVIEW

**Comment by iocanel** [comment]
@lordofthejars: We talked about it in twitter and felt that we can do better. So, with this change if the user sets

`quarkus.container-image.group` it will also apply to kubernetes, openshift and knative resource. Still the user is free to override the property, in which case it will only affect labels and resource names (image name is 100% responsibility of container-image).

**Comment by lordofthejars** [comment]
That's awesome thank you very much.

**Comment by geoand** [comment]
CI doesn't seem to like it :)

**Comment by iocanel** [comment]
> CI doesn't seem to like it :)
I know, I am working on it!

**Comment by geoand** [comment]
This has a few issues, I'll take care of them

**Comment by geoand** [comment]
Actually we came to the conclusion that I was wrong, I hadn't properly installed all the dependencies

**Review by geoand — APPROVED** [review]

**Pull request merged**
