### PR TITLE
Beans enabled via build profile/properties should not be alternatives

### LINKED ISSUE #11892: Adding @IfBuildProfile("prod") annotation to one grpc service throws away all other services
**Describe the bug**
I have multiple grpc services defined in my proto file and corresponding implementations in java code. If I mark one implementation with annotation `@IfBuildProfile("prod")` and run application with prod profile, all other services disappear, grpcurl shows only one single service which I marked with annotation.

**Expected behavior**
All defined services should still be available in application including annotated service and all unannotated ones.

**Actual behavior**
Application starts with just one grpc service, the one I marked with `@IfBuildProfile("prod")` annotation

**To Reproduce**
1. Create two services in your proto file. Implement them In application. Run and check that both services are available (by calling them or by listing with `./grpcurl -plaintext localhost:9000 list`
2. Mark one service with `@IfBuildProfile("prod")` annotation
3. Run application with prod profile and try to call unmarked service. It will fail. Or try listing with `./grpcurl -plaintext localhost:9000 list` and you will see only one service (don't forget about `quarkus.grpc.server.enable-reflection-service = true`)

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.grpc.server.port = 9000
quarkus.grpc.server.enable-reflection-service = true
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 
1.7.1.Final

**Additional context**
My digging shows that `io.quarkus.grpc.runtime.GrpcContainer` injects services as `Instance<BindableService> services;` If any of the BindableService beans have some priority set it is prioritized over other BindableServices and all other services are thrown away. IfBuildProfile annotation is counted as "alternative priority" and it survives filtering in `ArcContainerImpl.resolve(Set<Bean<? extends X>> beans)` method

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #11892

### CODE REVIEW

**Comment by mkouba** [comment]
CC @michalszynkiewicz @Shohou

**Review by geoand — COMMENTED** [review]
LGTM

**Review by geoand — APPROVED** [review]

**Comment by mkouba** [comment]
The JDK 11 job fails with:
```
2020-09-07T12:03:00.4141770Z [ERROR] io.quarkus.resteasy.test.IncompletePostTestCase.testIncompleteWrite  Time elapsed: 2.692 s  <<< ERROR!
2020-09-07T12:03:00.4142229Z java.net.SocketTimeoutException: Read timed out
```

**Comment by geoand** [comment]
Seems like a flaky test

**Comment by gsmet** [comment]
@mkouba I think it makes sense to push that one to 1.8, right?

**Comment by mkouba** [comment]
> I think it makes sense to push that one to 1.8, right?

@gsmet Yes, let's hope we will not break anything...

**Review by manovotn — APPROVED** [review]
Looks fine, just one note (unless I am missing something :))
With this solution, if a user has a bean `Foo` and also has `Bar extends Foo` that is only added in certain build profile, this combination will now fail to inject `Foo` for given profile (ambiguous dependency). This was valid previously because `Bar` was actually prioritized alternative and took precedence. Are we OK with that @mkouba @geoand?

**Comment by geoand** [comment]
Oh shoot... 
I don't know to be honest, it looks like something that should work :)

But between the example you mentioned and the one issue that this PR fixes, I don't know which one is more important TBH... I'll trust you CDI experts on this

**Comment by manovotn** [comment]
It's not about expertise but more about what scenarios we choose to support and which are expected not to work.
E.g. we are choosing between:
* Having each implementation of `Foo` tied to some profile so that there is at most one (which is the content of this PR)
* Having some default `Foo` in your app and then having other impls overriding it in some profiles (which was previous state)

**Comment by geoand** [comment]
Put that way, I am a little worried about breaking backward compatibily :(

**Comment by mkouba** [comment]
I believe that `@IfBuildProfile` should not prioritize or override a bean. It's merely an "enablement" feature. In other words, the ambiguous dependency is IMO correct. There are other means to resolve similar ambiguities, such as `@DefaultBean`.

**Comment by geoand** [comment]
@mkouba fair enough. But I think we will at least have to have something in the wiki mentioning this change.

**Comment by manovotn** [comment]
> Put that way, I am a little worried about breaking backward compatibily :(

That's exactly why I put it that way :)

> I believe that @IfBuildProfile should not prioritize or override a bean. It's merely an "enablement" feature. In other words, the ambiguous dependency is IMO correct.

Ok, in that case I think we are good to proceed.

**Comment by mkouba** [comment]
Ok. To sum it up. It's a breaking change in the sense that a bean enabled via `@IfBuildProfile` was previously registered as an alternative with high priority and so it was taken in case of ambiguous dependencies during typesafe resolution. That was IMO a mistake; we don't even mention this behavior in the docs and javadoc. Therefore, I suggest to fix it and add a note to the migration notes.

@gsmet I'd also suggest to include this fix in 1.8.

**Pull request merged**
