### PR TITLE
OpenAPI 1.1.10

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by machi1990** [comment]
Should this fix #4329?

**Comment by gsmet** [comment]
@machi1990 that's the idea :)

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
I assume we won't merge this but instead we're waiting for a new version once it becomes available?

**Comment by kenfinnigan** [comment]
Currently still waiting for a release to successfully push to Sonatype

**Pull request closed without merging**
