### PR TITLE
Deprecate field- and ctor-based BuildProducers

### PR DESCRIPTION
**Pull request by dmlloyd**
Groundwork for #13145

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
I force pushed an update to fix formatting and import issues :).

**Review by gsmet — APPROVED** [review]

**Comment by dmlloyd** [comment]
Are those not picked up when you build with `-Dquickly`?  It built cleanly for me locally with that flag.

**Comment by geoand** [comment]
> Are those not picked up when you build with `-Dquickly`? It built cleanly for me locally with that flag.

Yeah `-Dquickly` implies `format.skip`

**Review by geoand — APPROVED** [review]

**Comment by gastaldi** [comment]
> > Are those not picked up when you build with `-Dquickly`? It built cleanly for me locally with that flag.
> 
> Yeah `-Dquickly` implies `format.skip`

Maybe we should enable that with `-Dquickly`. It's not the first time I see someone doing that and expecting it to work (myself included) :)

**Comment by geoand** [comment]
I guess it depends on how much it slows things down?

**Comment by gastaldi** [comment]
Considering that the majority of classes are already (supposedly) formatted, I don't think it should take that long :)

**Comment by geoand** [comment]
But the plugin itself night be slow... A simple set of runs should give us the answer

**Comment by gsmet** [comment]
I don't use `-Dquickly` for exactly this reason.

I have my own aliases:
```
alias build-fast="mvn -T C1 -DskipDocs -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests clean install"
alias build-docs="mvn -T C1 -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests clean install"
alias format="mvn -T C1 process-sources"
```

**Comment by gastaldi** [comment]
I also recommend using https://github.com/mvndaemon/mvnd for speed

**Comment by machi1990** [comment]
The JDK8 test failed with 
```log
 ReadTimeoutTestCase.shouldNotProcessRequestWrittenTooSlowly:63 Did not expect data to be read, content was: The 
message content ==> expected: <false> but was: <true>
```

Not sure if it is related.

**Comment by dmlloyd** [comment]
I don't think it is. I got that failure on another PR as well.

**Pull request merged**
