### PR TITLE
add http://errorprone.info (optional, non-enforcing - yet)

### PR DESCRIPTION
**Pull request by vorburger**
We will require a series of fixes before being able to enforce.

### CODE REVIEW

**Comment by vorburger** [comment]
see #1335 for more background...

Running a local with this like so:

    mvn install -Perrorprone -Dno-native -DskipTests 

reveals e.g. this (anyone wants to fix this one?):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2:compile (default-compile) on project quarkus-test-extension-runtime: Compilation failure: Compilation failure: 
[ERROR] /home/vorburger/dev/Quarkus/git/quarkus/core/test-extension/runtime/src/main/java/io/quarkus/extest/runtime/ObjectOfValue.java:[35,20] [EqualsHashCode] Classes that override equals should also override hashCode.
[ERROR]     (see https://errorprone.info/bugpattern/EqualsHashCode)
```

**Review by dmlloyd — CHANGES_REQUESTED** [review]
This kind of change needs to be preceded by discussion on the mailing list or in chat.

**Comment by gsmet** [comment]
Mailing list would be better as not everyone can follow the chat closely these days with all the talks, travel and so on.

Closing this one for now, we can reopen once discussed.

**Comment by vorburger** [comment]
Sure, let's first discuss further in #1335; also posted on list in https://groups.google.com/forum/#!topic/quarkus-dev/ZEIYoZRMsk8

**Pull request closed without merging**
