### PR TITLE
Remove long deprecated options from CertificateConfig

### PR DESCRIPTION
**Pull request by geoand**
These options where deprecated more than 2 years ago in 272119dcbec1b7a0fbff96c08729b86223bce258

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Maybe let's try to get https://github.com/quarkusio/quarkus/pull/33228 in before doing that.

I'll rebase and try to get it merged soon.

**Comment by geoand** [comment]
Sure, no problerm

**Review by cescoffier — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
I rebased this PR and fixed the gRPC tests.

**Comment by geoand** [comment]
💪

**Pull request merged**
