### PR TITLE
Qute - unify behavior/logic of include sections and user tags

### LINKED ISSUE #22657: Qute: user-defined tags should allow insert's like include does
### Description

Tags are currently documented as "can be used to include a template and optionally pass some parameters" (https://quarkus.io/guides/qute-reference#user_tags).

But inside a (user-defined) tag, you cannot use `insert` to embed nested sections/tags, to for example allow the following:
```
{#mylist name="My List"}
  {#header}<p>Some more informations</p>{/header}
  {#footer}<button>Add Element</button>{/footer}
{/mylist}
```

```
{! mylist tag !}
<div>
  <h1>{name}</h1>
  {#insert header}
  <ul>...</ul>
  {#insert footer}
</div>
```

I know that there is `{nested-content}`, but this only allows for the complete body to be used, not single tags from it like `insert` does when `include`-ing.

### Implementation ideas

_No response_

### LINKED ISSUE #23292: Qute: Consistent behaviour for tags and include
### Description

We can include another template using ```#include``` syntax.

```
 {#include foo limit=10 /} 
 ```
 
 for tags syntax is quite different
 
 ```
 {foo limit=10}{/foo}
 ```
 
 It would be great if tag ```{xxx limit=10}{/xxx}``` would be only a shorter syntax for ```{#include foo limit=10/}
 
 ```#include``` offers now more features than tags for example "transclusion" with ```#insert``` syntax.
 
 What do you think about unifying tag and include?

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #23292
- fixes #22657

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Nice! 

Every day, we're getting Qute closer to JSF :)

**Comment by mkouba** [comment]
> Every day, we're getting Qute closer to JSF :)

I hope that you mean "closer in terms of productivity" :D

**Comment by gastaldi** [comment]
s/JSF/Facelets 😃

**Comment by gastaldi** [comment]
Should we backport this one to 2.9.x?

**Comment by mkouba** [comment]
> Should we backport this one to 2.9.x?

So in theory it should not break anything... but it's not a bugfix so I'd rather keep this for 2.10.

**Pull request merged**
