### PR TITLE
Upgrade flapdoodle embed mongo to 4.4.0

### PR DESCRIPTION
**Pull request by michaelmosmann**
This is a squash of the pull request #30243, please check #30243 for history.

Supersed #30243

Closes: https://github.com/quarkusio/quarkus/pull/30243

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks for that but please amend your commit so that the message is meaningful.

Same for the pull request title.

History is important.

Thanks!

**Comment by michaelmosmann** [comment]
@gsmet i have changed the commit message.

**Comment by loicmathieu** [comment]
@gsmet I update the title and that comment, and close the previous PR to only keep this one. The code was already reviewed so it's good to go. I'll approve the workflow to run the CI.

**Review by loicmathieu — APPROVED** [review]
Already approved in the original PR

**Comment by michaelmosmann** [comment]
@loicmathieu .. is there anything still left to do for me?

**Comment by loicmathieu** [comment]
@michaelmosmann no, we need to wait for @gsmet to approve this PR as he request changes.

**Comment by michaelmosmann** [comment]
@loicmathieu as there is now some new issue (imports not sorted) .. can i run these checks in my machine to speedup this cycle a little bit?

**Comment by loicmathieu** [comment]
@michaelmosmann CI should run in your own fork, you can check the result there.
Imports will be sorted if you run `mvn clean install`.

**Comment by michaelmosmann** [comment]
@loicmathieu .. ok. this is strange.. a local maven build changed the import order.. the build failed with:

OpenTelemetrySamplerConfigTest.test:33 expected: <TraceIdRatioBased{0,500000}> but was: <TraceIdRatioBased{0.500000}>

(guess some local formating issue in "Quarkus - OpenTelemetry - Deployment")

..then the CI build failed again with " .. MongoWithReplicasTestBase.java' has not been previously formatted .." so that i again used `mvn -f extensions/mongodb-client/deployment net.revelc.code.formatter:formatter-maven-plugin:2.21.0:format` to fix this.. 

i hope for the best.. but will have a look tomorrow..

**Comment by debu999** [comment]
Is this good to merge

**Comment by debu999** [comment]
@michaelmosmann is 4.4.0 version of flapdoodle available in maven central?

**Comment by michaelmosmann** [comment]
Yes . Should be..

**Comment by michaelmosmann** [comment]
@debu999 its there: https://repo1.maven.org/maven2/de/flapdoodle/embed/de.flapdoodle.embed.mongo/4.4.0/

**Comment by michaelmosmann** [comment]
@debu999 the build with my changes failed on unrelated parts: https://github.com/flapdoodle-oss/quarkus-embedmongo-integration/actions/runs/3966644585  so i would guess that a merge would not make it worse:)

**Comment by michaelmosmann** [comment]
Is here something left to todo?

**Comment by loicmathieu** [comment]
@michaelmosmann I launch the CI, is all is green and @gsmet approve it we'll merge it.

**Comment by michaelmosmann** [comment]
@loicmathieu @gsmet .. 4 failing checks don't relate AFAIK to any of my changes..

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Comment by debu999** [comment]
Finally it's in. Thanks @michaelmosmann @loicmathieu @gsmet

**Pull request merged**
