### PR TITLE
Pass checked exceptions unwrapped for Kotlin methods

### LINKED ISSUE #21519: Kotlin: ArcUndeclaredThrowableException since 1.13.x
### Describe the bug

Hello,
since Quarkus 1.13.x an ArcUndeclaredThrowableException is thrown when the method has no annotation @Throws(Exception::class) and an exception is thrown by called method.

My code is written in Kotlin and it works in Quarkus 1.12.x but not in 1.13.x.

Exception thrown :
```
2021-11-19 09:41:38,139 | ERROR | executor-thread-0 | [org.acme.quarkus.arcexception.config.exception.RestThrowableMapper:30] - Throwable unhandled (ArcUndeclaredThrowableException): Error invoking subclass method: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
        at ...
Caused by: org.acme.quarkus.arcexception.partner.exception.PartnerException: Error when retrieving partner status: : RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: Hôte inconnu (unknownhost)
        at org.acme.quarkus.arcexception.partner.PartnerApiService.fetchAppStatus(PartnerApiService.kt:19)
        at ...
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: Hôte inconnu (unknownhost)
        at ...
Caused by: java.net.UnknownHostException: Hôte inconnu (unknownhost)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.in.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at ...
```

Thanks 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

You can find a reproducer at https://github.com/Itoriem/quarkus-kotlin-ArcUndeclaredThrowableException

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

"11.0.8" 2020-07-14 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

1.13

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3

### Additional information

Discussed here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Kotlin.3A.20ArcUndeclaredThrowableException.20since.201.2E13.2Ex

### PR DESCRIPTION
**Pull request by kdubb**
Fixes #21519

### CODE REVIEW

**Comment by kdubb** [comment]
@mkouba Thoughts on best way to write a test for this?

I'm thinking I can just make a Java class with a dummy `@Metadata` annotation. Is adding a kotlin dependency to Arc tests ok?

**Comment by geoand** [comment]
I think it's fine to add this, but it's up to @mkouba

**Comment by mkouba** [comment]
> I'm thinking I can just make a Java class with a dummy @Metadata annotation. Is adding a kotlin dependency to Arc tests ok?

@kdubb sure, that should be ok.

**Comment by kdubb** [comment]
@mkouba Should be ready to go.

**Comment by mkouba** [comment]
FTR the `ArcUndeclaredThrowableException` got added in a PR for https://github.com/quarkusio/quarkus/issues/3949

The original problem was that an interceptor throws a checked exception that is not declared in the the associated target method `throws`. Which is IMO illegal, because the interceptors spec states: _"Interceptor methods are allowed to throw runtime exceptions or any checked exceptions that the associated target method allows within its throws clause."_. Anyway, the solution was to wrap such all uncaught ``Exception``s in a special runtime exception.

IIUIC Kotlin does not have the checked exceptions and so the `ArcUndeclaredThrowableException` is currently used to wrap any exception that extends `java.lang.Exception` thrown from the code. So the solution in this PR seems to be correct.

**Review by mkouba — APPROVED** [review]

**Pull request merged**
