### PR TITLE
Use `--interactive` option when using docker inside Windows' WSL

### LINKED ISSUE #32215: Native build show no output when using docker 20.10 on ubuntu wsl
### Describe the bug

Running
`./mvnw clean package -Pnative -Dmaven.test.skip`
results in 
```
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1000:1000 ....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
```

Checking the command
`docker run --env LANG=C --rm --user 1000:1000 --rm quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.2-java17 --version`
the output is indeed empty on ubuntu wsl with docker 20.10.

Adding the interactive flag `-i` fixes the problem.
Also, using 23.0 on windows and with the original command (no additional -i) does show the version.
The same is true for the actual build command. No difference between graalvmce or mandel images.

### Expected behavior

See the output of native-image command

### Actual behavior

```
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1000:1000 ....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:41 min
[INFO] Finished at: 2023-03-29T12:10:49+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.16.5.Final:build (default) on project cloudportal: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:422)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:263)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux xxx 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 19.0.2 2023-01-17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 

### Additional information

_No response_

### LINKED ISSUE #37272: [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to get GraalVM version
### Describe the bug

I created and downloaded the most simple Quarkus application from https://code.quarkus.io/ using `Gradle with Kotlin DSL` as `Build Tool`.

What works:
```
./gradlew addExtension --extensions=quarkus-container-image-docker
./gradlew imageBuild
```
What doesn't work:
```
./gradlew clean imageBuild -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker
```
It fails with
```
> Task :quarkusAppPartsBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to get GraalVM version
                at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:40)
                at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:223)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
                at java.base/java.lang.Thread.run(Thread.java:840)
                at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Caused by: java.lang.IllegalArgumentException: Cannot parse version from output:

                at io.quarkus.deployment.pkg.steps.GraalVM$Version.of(GraalVM.java:281)
                at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:37)
                ... 12 more
```

### Output of `uname -a` or `ver`
```
Linux SAG-H56RXL3 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
```
### Output of `java -version`
```
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
```
### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev
```
3.5.3
```
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-04 20:52:13 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.9 (Eclipse Adoptium 17.0.9+9)
OS:           Linux 5.10.102.1-microsoft-standard-WSL2 amd64
```
### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
There seems to be an issue with docker printing output when running in Windows' WSL without `--interactive`.

Closes https://github.com/quarkusio/quarkus/issues/37272
Closes https://github.com/quarkusio/quarkus/issues/32215

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by zakkak** [comment]
@tglaeser @gmuellerinform can you please confirm that the `docker info` output contains `WSL` in your environments? 

If you could also give this PR a go it would be great. You can do so by running:

```shell
git clone https://github.com/zakkak/quarkus --branch 2023-11-27-fix-docker-in-wsl-issue
cd quarkus
./mvnw -Dquickly
./mvnw -Dnative -pl integration-tests/jpa -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean verify
```

**Comment by zakkak** [comment]
@karm @geoand please note that I am also moving [ContainerRuntimeUtil to core/deployment](https://github.com/quarkusio/quarkus/pull/37389/commits/0bb807369bbe50a0b3cb14d01b40e429e732d031) since it's only used in the deployment phase. I am not sure why it was added to core/runtime at first. Let me know if there is any issue with the move.

**Comment by tglaeser** [comment]
Executing `docker info` in terminal applications _CMD_, _PowerShell_, _MSYS2_, and the _Kali Linux WSL VE terminal_ all contain output
```
...
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Rancher Desktop WSL Distribution
...
```

**Comment by tglaeser** [comment]
> ```shell
> ./mvnw -Dnative -pl integration-tests/jpa -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean verify
> ```
returns
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.203 s -- in io.quarkus.it.jpa.entitylistener.EntityListenerInGraalITCase
[INFO] Running io.quarkus.it.jpa.generatedvalue.GeneratedValueInGraalITCase
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.010 s -- in io.quarkus.it.jpa.generatedvalue.GeneratedValueInGraalITCase
[INFO] Running io.quarkus.it.jpa.jdbcmetadata.JPAJdbcMetadataRetrievalInGraalITCase
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s -- in io.quarkus.it.jpa.jdbcmetadata.JPAJdbcMetadataRetrievalInGraalITCase
[INFO] H2 database was shut down; server status: Not started
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- failsafe:3.1.2:verify (default) @ quarkus-integration-test-jpa ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:20 min
[INFO] Finished at: 2023-11-29T14:29:37-05:00
[INFO] ------------------------------------------------------------------------
[INFO] 20 goals, 20 executed
```
Probably unrelated, there were many exceptions of type `Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Schema "SCHEMA1" not found` thrown wile executing those test cases.

**Review by tglaeser — APPROVED** [review]

**Comment by gsmet** [comment]
@zakkak the question might be stupid but won't `--interactive` makes things... well... interactive? :)

**Comment by zakkak** [comment]
> @zakkak the question might be stupid but won't `--interactive` makes things... well... interactive? :)

I suppose, but it's not clear what this really means in our case. According to my testing it doesn't seem to affect the build process (at least not when everything works as expected) and AFAIK is the only way to work around the issue. I guess it could become an issue if `native-image` suddenly decides to ask for some input at any stage of the build process :/

**Comment by zakkak** [comment]
@gsmet if there are no objections on your side I think this is ready to be merged.

**Pull request merged**
