### PR TITLE
Check that resources and classes are effectively available at runtime

### PR DESCRIPTION
**Pull request by gsmet**
Until now, we were testing that the class was present in the deployment classpath which could lead to incorrect behavior if the class is available at deployment and not at runtime.
Given that the deployment classpath contains a TON of additional dependencies, this is not only a theoretical issue and we already got hit by that in the past.

For now, creating as a draft to get CI running. We will also need very careful reviews of the changes once CI passes.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
LGTM

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
@yrodiere given I'm not sure all of these combinations are tested, I was wondering if you could scrutinize this commit before I merge it.

**Review by radcortez — APPROVED** [review]

**Review by yrodiere — APPROVED** [review]
@gsmet I don't know if that's what you wanted me to check, but the conditions seem to be equivalent to what you had before (except the part about deployment classpath that you're fixing, of course).

**Comment by gsmet** [comment]
@yrodiere perfect, thanks! Let’s merge then.

**Comment by gsmet** [comment]
@alesj so that’s what you should use now to check if a class is available at runtime. (We discussed that very subject a while ago)

**Comment by alesj** [comment]
@gsmet yup, got it, tnx :-)

**Pull request merged**
