### PR TITLE
CapturingInputStream discards -1 from delegate read

### LINKED ISSUE #23351: Data corruption when mixing `@FormParam` and `MultivaluedMap`
### Describe the bug

A RestEasy Reactive handler method such as the one shown below which consumes `application/x-www-form-urlencoded`, declares at least one `@FormParam` method parameter, and declares a `MultivaluedMap<String, String>` method parameter to receive all the form parameters as a map corrupts the value of the last form parameter in the request body by appending two `-1` bytes to it.

```
@POST
@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
public void demo(@FormParam("bound") String bound, MultivaluedMap<String, String> params) {
    System.out.println("bound=" + bound);
    params.forEach((k, v) -> System.out.println(k + " -> " + v));
}
```

Curl command to submit test values:
```
curl -i -X POST -d 'bound=this+value+is+bound+to+a+method+parameter&unbound=this+one+is+not&corrupt=this+one+has+junk+at+the+end+because+it+is+at+the+end+of+the+request+body' http://localhost:8080/demo
```

Resulting output:
```
bound=this value is bound to a method parameter
unbound -> [this one is not]
corrupt -> [this one has junk at the end because it is at the end of the request body��]
bound -> [this value is bound to a method parameter]
```

The bug is in the `FormBodyHandler.CapturingInputStream` class here.
https://github.com/quarkusio/quarkus/blob/2.7/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/FormBodyHandler.java#L133-L135

It does not check for a `-1` return value from the delegate `read()` call before appending to the `ByteArrayOutputStream`. The following change fixes the bug.

```
@Override
public int read() throws IOException {
    int res = delegate.read();
    if (res != -1) {
        baos.write(res);
    }
    return res;
}
```

### Expected behavior

The value of the last parameter in the request body is not corrupt

### Actual behavior

The value of the last parameter in the request body has two `-1` bytes appended to it

### How to Reproduce?

[demo.zip](https://github.com/quarkusio/quarkus/files/7981672/demo.zip)

### Output of `uname -a` or `ver`

Linux ben-work-laptop 5.13.0-1029-oem #36-Ubuntu SMP Thu Jan 20 05:55:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04) OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bengunter**
Fixes #23351

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by geoand — COMMENTED** [review]
Thanks, but I think we will need an integration test for this

**Review by gastaldi — DISMISSED** [review]
Marking as requesting changes until an integration test is added

**Comment by bengunter** [comment]
I'm going to need some specifics as to what you're looking for. It's a big project, and I'm not familiar with any of it.

**Comment by geoand** [comment]
Something like https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/multipart/InvalidEncodingTest.java

**Comment by gastaldi** [comment]
The snippet you added in https://github.com/quarkusio/quarkus/issues/23351#issue-1121153892 will be useful too

**Comment by bengunter** [comment]
Integration test has been added.

**Review by geoand — APPROVED** [review]

**Comment by gastaldi** [comment]
Error is unrelated. Merging.

Good job @bengunter !

**Pull request merged**
