### PR TITLE
Ignore non-existing class and resource paths during JVM test

### PR DESCRIPTION
**Pull request by AdlerFleurant**
Some resource and class locations may not exist when resolving paths. 
We now ensure that these non-existing paths are not added to the application root.

### CODE REVIEW

**Comment by AdlerFleurant** [comment]
This may also fix #26013

**Comment by AdlerFleurant** [comment]
Do we need to rerun this or should we investigate?

**Comment by gsmet** [comment]
Yeah no need to push again when it's like that. Usually it's just a flaky test. We will deal with it ourselves and ping you if we think it's related to your work.

We are currently working on improving the situation with flaky tests.

**Review by aloubyansky — APPROVED** [review]
Thanks @AdlerFleurant

**Pull request merged**
