### PR TITLE
Fix Java file paths and packages in OptaPlanner quickstart

### PR DESCRIPTION
**Pull request by yurloc**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks! 

Do you also plan to update the corresponding quickstart?

**Comment by geoand** [comment]
Asking because I see that the docs changes are different from what the quickstarts has for tests packages

**Comment by yurloc** [comment]
@geoand Good catch. I think the article should be consistent with the quickstart source code. I'll update the PR.

@ge0ffrey the [quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/optaplanner-quickstart/src/main/java/org/acme/optaplanner) uses `org.acme.optaplanner` as the root package. I'll update the article to the same instead of just `org.acme`, ok?

**Comment by ge0ffrey** [comment]
@yurloc Yes, thanks

**Comment by yurloc** [comment]
@geoand I haven't touched the quickstart code in the other repo. Instead I made sure that this quickstart article is consistent with the solution in the quickstart repo.

**Comment by geoand** [comment]
Cool, thanks!

**Review by geoand — APPROVED** [review]

**Pull request merged**
