### PR TITLE
Remove instantiation of com.sun.jndi.ldap.LdapCtxFactory for JDK16+ compatibility

### LINKED ISSUE #17092: Enable elytron-security-ldap tests on JDK 16+
Analyze problem (illegal access w.r.t. "opens com.sun.jndi.ldap"), probably update some elytron component and revert https://github.com/quarkusio/quarkus/pull/17053/commits/472080225faf60cceb02938aba8984d3e310abb7.

Relates to #16195.

- set JDK 16 (e.g. via `sdk`)
- if Kotlin 1.5 is not yet integrated: add `--add-opens java.base/java.util=ALL-UNNAMED` to `MAVEN_OPTS`
- `mvn -Dquickly -T1C`
- `mvn clean verify -f extensions/elytron-security-ldap/deployment` (should not fail)
- `mvn clean verify -f extensions/elytron-security-ldap/deployment -P'!jdk16-workarounds'` (should fail)
- same with `integration-tests/elytron-security-ldap`

### PR DESCRIPTION
**Pull request by famod**
Resolves #17092

The following change in Spring led me to try out removing it and lo and behold, it worked: https://github.com/spring-projects/spring-ldap/pull/568

See #8651 and #8696 for more context of that instantiation.

Not sure who can review this... @sberyozkin maybe? Or @galderz?

### CODE REVIEW

**Comment by famod** [comment]
Not entirely sure about backporting to 2.0.1 but I'm leaning towards yes.

**Comment by gsmet** [comment]
I think this needs to be carefully verified as the initial issue was a corner case.

**Comment by famod** [comment]
Ah I see! I finally found the right PR that introduced this: #9486 (#8696 was not merged back then)

@gsmet I assume there is no test coverage for that corner case in this repo?

**Comment by gsmet** [comment]
I think it fails with the tests we have... given you have the right tool to build the native images. I wouldn't be surprised if the issue is only with Mandrel.

@zakkak any chance you could help here? Maybe run this PR with Mandrel releases?

**Comment by zakkak** [comment]
> I think it fails with the tests we have... given you have the right tool to build the native images. I wouldn't be surprised if the issue is only with Mandrel.
> 
> @zakkak any chance you could help here? Maybe run this PR with Mandrel releases?

@gsmet I am not sure how I can help. It appears like this patch is to resolve a JDK16+ compatibility issue. I have no way to verify this since we are not yet building/testing Mandrel for JDK 16+. Would a test using Mandrel 21.1 (JDK11 based) suffice?

**Comment by famod** [comment]
@zakkak I think a JDK 11 based Mandrel test would cover Guillaume's concerns.

**Comment by zakkak** [comment]
> @zakkak I think a JDK 11 based Mandrel test would cover Guillaume's concerns.

OK, I started the following two:

* Mandrel 21.1: https://github.com/graalvm/mandrel/actions/runs/1022639598 
* Mandrel 20.3: https://github.com/graalvm/mandrel/actions/runs/1022639971

**Comment by gsmet** [comment]
@zakkak yeah that's exactly what I wanted. This workaround was added for Mandrel so if we want to remove it, we need to make sure it's not an issue anymore.

**Comment by zakkak** [comment]
@gsmet both Mandrel 20.3 and 21.1 runs passed :)

**Review by gsmet — APPROVED** [review]
OK, let's do it then. Thanks @zakkak for checking!

**Pull request merged**
