### PR TITLE
Escape UUID in MongoDB with Panache

### LINKED ISSUE #10941: cannot find by UUID field in PanacheMongoEntity
When using the following PanacheMongoEntity:

```
@MongoEntity()
@Data
public class Event extends PanacheMongoEntity {

    public UUID userId;
    public UUID objectId;
    public LocalDateTime createdAt;
}
```
The following request always return 0, even if some data is present:
```
Event.count("objectId = ?1", someObject.getUuid())
```

My connection String is : 
``` 
quarkus.mongodb.connection-string = mongodb://localhost:27017/?uuidRepresentation=STANDARD
```
In an other entity, I use UUID as primary ID and I can find them with findById(UUID).

Replacing UUID by String make this working.

I'm using Quarkus 1.6.1

### PR DESCRIPTION
**Pull request by rmanibus**
Fix #10941

### CODE REVIEW

**Comment by geoand** [comment]
Hi,

Thanks for the contribution! CI is failing because the code is not properly formatted, so please run `mvn process-sources` before amending your commit.

**Comment by rmanibus** [comment]
Thanks @geoand, will do it. Regarding my comment on the issue, should I upgrade mondb client to 4.1.0-rc in this PR ?

**Comment by geoand** [comment]
I haven't followed that issue closely, so I'll let @loicmathieu decide. But my inclination is that we should not use an `rc` version of a dependency in Quarkus, best wait for a proper final release of it before including it.

**Comment by rmanibus** [comment]
Ok that's what I thought. Anyway I opened an issue to fix this on their 4.0.x branch. But without this it won't be working properly.

**Comment by loicmathieu** [comment]
As I unserstand it this will not work until some changes will be done on Mongo driver side?
If so better put this PR on ice, there is a label for this,  and add a comment with a link to the issue on the Mongo repository.
No CR dependency, our Mongodb support is now is the stable state so we cannot depend on non final artifacts

**Comment by rmanibus** [comment]
Blocked by https://github.com/mongodb/mongo-java-driver/pull/556

**Comment by rmanibus** [comment]
MongoDB driver 4.1.0 has been released with the fix. I included it in this PR, this is now working.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
Can you please adds tests ?
At least a test in the runtime module inside the existing `MongoOperationsTest` inside the runtime module.

**Comment by rmanibus** [comment]
It's done,

should I also add something like:

```
    @Test
    public void testUUIDSubType() {
        BsonDocument doc = BsonDocument.parse("{'field':UUID('7f000101-7370-1f68-8173-70afa71b0000')}");
        assertEquals("{\"field\": {\"$binary\": {\"base64\": \"fwABAXNwH2iBc3CvpxsAAA==\", \"subType\": \"04\"}}}",
                doc.toJson());
    }
```
But this is more like testing the mongo driver itself.

**Review by loicmathieu — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
