### PR TITLE
List of AWT runtime initialized classes not observable for other extensions

### LINKED ISSUE #32065: List of AWT runtime initialized classes not observable for other extensions
### Describe the bug

In Quarkiverse CXF we are performing some special actions at build time based on whether SOAP service interfaces reference build time initiliazed classes. To do that, we observe `RuntimeInitializedClassBuildItem` and `RuntimeInitializedPackageBuildItem`. 

`java.awt.Image` is a prime example for passing binary content to WebServices, however our Processor, it is not able to find out that `quarkus-awt` is actually setting it for runtime init, because it does so via GraalVM Features.

I wonder whether `io.quarkus.awt.runtime.graal.AwtFeature` and `DarwinAwtFeature` could be transformed to a Quarkus BuildStep producing some `RuntimeInitializedPackageBuildItem` s?

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #32065

@Karm transforming DarwinAwtFeature is not that straightforward as I was not able to figure out how to reliably detect the native builder JVM version and platform from a Quarkus BuildStep. Migrating AwtFeature as done in this PR would be enough for my purposes though.

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM

**Comment by ppalaga** [comment]
Is this good to merge?

**Comment by zakkak** [comment]
> Is this good to merge?

It looks pretty safe to me, but let's give @Karm another chance to review it before merging.

**Comment by Karm** [comment]
Well, looking at it now, this will get reshuffled again by #31596 ...

@ppalaga It would help me if I could have a test or repo I can try to see how it goes for your usage in the Quarkiverse.

Apart from our AWT Extension TS, I'll be running AWT QuickStart and then https://github.com/quarkiverse/quarkus-primefaces.

Initially on Linux.

The change opens a Window to native Windows AWT too though and I will port to Windows later.

**Comment by ppalaga** [comment]
> @ppalaga It would help me if I could have a test or repo I can try to see how it goes for your usage in the Quarkiverse.

This particular change is covered by this test: https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/mtom-awt It is no fancy Image processing, only passing an Image instance to a SOAP web service.

There are more interesting tests in Camel Quarkus:

* https://github.com/apache/camel-quarkus/tree/main/integration-tests/fop
* https://github.com/apache/camel-quarkus/tree/main/integration-tests/pdf

**Pull request merged**
