### PR TITLE
Better annotation literals

### LINKED ISSUE #21230: ArC - enhance the generated annotation literal classes
### Description

Currently, all generated annotation literals extend `javax.enterprise.util.AnnotationLiteral`. This is suboptimal as all functionality (including `equals()` and `hashCode()`) is implemented via the reflection API.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #21230

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft because this depends on https://github.com/quarkusio/gizmo/pull/131.

**Comment by mkouba** [comment]
Looks good!

**Comment by Ladicek** [comment]
Thanks! Once Gizmo is released (https://github.com/quarkusio/gizmo/pull/131#issuecomment-1283543490), I'll un-draft this PR.

(Plus I'll fix the `equals` bug for memberless annotations as we discussed offline.)

**Comment by manovotn** [comment]
Fiddled with it locally to see what's the actual difference and it looks good!

Nitpicker's note - there are some code comments in `AnnotationLiteralProcessor` that still refer to how it worked before and might be worth updating:
* [reference to previous class suffix](https://github.com/Ladicek/quarkus/blob/better-annotation-literals/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationLiteralProcessor.java#L356)
* [notion of extending `AnnotationLiteral` class](https://github.com/Ladicek/quarkus/blob/better-annotation-literals/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationLiteralProcessor.java#L400)

**Comment by Ladicek** [comment]
Thanks, will fix those!

**Comment by Ladicek** [comment]
Updated the 1st commit to use Gizmo 1.4 and marked as ready.

**Review by manovotn — APPROVED** [review]

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
@Ladicek aaand a formatting error :-)

**Comment by Ladicek** [comment]
Ugh! :-)

**Comment by Ladicek** [comment]
Should be fixed now.

**Pull request merged**
