### PR TITLE
Update GraalVM parsing to support upcoming 21.1

### LINKED ISSUE #16131: [native] Quarkus not able to parse GraalVM version in upcoming 21.1
## Describe the bug
Quakus fails to parse the GraalVM version from `native-image --version` in upcoming GraalVM 21.1.

This is because in the upcoming GraalVM the version is:
```
GraalVM Version 21.0.0 (Java Version 11.0.10+8-jvmci-21.0-b06)
```
while in previous versions it used to be:
```
GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+5-jvmci-21.1-b02)
```
Note the removal of "Version" and the addition of "Java 11 CE".

### Expected behavior
Quarkus should be able to get the version without any warning or error.

### Actual behavior
Quarkus prints:
```
[io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
```

## To Reproduce

1. Grab GraalVM from https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.1.0-dev-20210330_0726
2. Build a Quarkus app or test with `-Dnative` and `GRAALVM_HOME` pointing to GraalVM 21.1.0-dev

### PR DESCRIPTION
**Pull request by zakkak**
Closes #16131

### CODE REVIEW

**Comment by geoand** [comment]
We'll need one of your colleagues to review this one :)

**Comment by zakkak** [comment]
> We'll need one of your colleagues to review this one :)

@jerboaa can you please review this?

**Comment by jerboaa** [comment]
> > We'll need one of your colleagues to review this one :)
> 
> @jerboaa can you please review this?

@zakkak Sure, I'll take a look.

**Review by jerboaa — APPROVED** [review]
This looks good in terms of the updated versioning scheme for Mandrel and Graal VM (21.1+) and lower. Ship it! I don't know about the devtools test failure.

**Comment by jerboaa** [comment]
@geoand If this looks good to you from a general Quarkus perspective this should be good to go.

**Comment by geoand** [comment]
Thanks, I'll take a close look at it tomorrow

**Review by geoand — APPROVED** [review]
LGTM

**Comment by zakkak** [comment]
@gsmet this need to be backported to 1.13 to avoid getting:
```
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
```
with Mandrel (note that despite the ERROR the build succeeds, so maybe we need to make this a warning or make it fail).

To reproduce:
```
curl -O -J  https://code.quarkus.io/api/download        
unzip code-with-quarkus.zip
cd code-with-quarkus
./mvnw package -Pnative \
    -Dquarkus.native.container-build=true \
    -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.1-java11
```

**Pull request merged**
