### PR TITLE
Fix count / delete operations when using named query

### PR DESCRIPTION
**Pull request by gilvansfilho**
Fix to issue #20758

### CODE REVIEW

**Review by loicmathieu — CHANGES_REQUESTED** [review]
You must add a test inside the integration test.
The guide also should be updated, at least with a note saying that named queries can also be used with the count methods.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
This looks indead way better :)

Thanks for providing so much tests.
The same should also be done for Hibernate Reactive, I can take care of it if you can't.
Can you please mark your PR ready so I can launch the CI on it after taking care of the two minor feedback ?

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks for doing it, nice addition with a neat implementation ;)

@FroMage maybe you want to have a look ?

**Comment by gilvansfilho** [comment]
@loicmathieu  What about failed _build_ step of _Gradle Tests - JDK 11 Windows_ job? I runned this locally `./mvnw install -pl integrations-tests/gradle` and works fine. Could I rerun on CI?

**Comment by loicmathieu** [comment]
The failure is in an un-related CI task and both JDK11 and JDK17 tests passed.
I'm merging it, thanks @gilvansfilho !

**Pull request merged**
