### PR TITLE
Remove unnecessary public visibility modifier on Panache interfaces

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by FroMage** [comment]
What's the need?

**Comment by geoand** [comment]
No need whatsoever, just removal of (unnecessary) boilterplate :)

**Comment by FroMage** [comment]
I'm not too keen on removing `public` modifiers because I hate how they're not required because it harms lisibility: you have to check the outer type to figure out if your method is public or package-private, which is very poor UX. So I'm rather against this, but we can ask @emmanuelbernard or @gsmet for their opinion about this, wrt quarkus overall style.

**Comment by geoand** [comment]
I don't have a strong opinion on this, but according to the [JLS](https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-9.4):

```
A method in the body of an interface may be declared public or private (§6.6). If no access modifier is given, the method is implicitly public. It is permitted, but discouraged as a matter of style, to redundantly specify the public modifier for a method declaration in an interface. 
```

**Comment by gsmet** [comment]
I usually don't add public modifiers on public methods of interfaces.

A habit coming from using SonarQube, which had a rule for that back in the time.

**Comment by emmanuelbernard** [comment]
I won't help much, I lean towards Stef on that one. I personally do add this redundency. But no massively strong feeling

**Comment by geoand** [comment]
So it's a tie, which I guess means that @FroMage  as the "owner" should decide :)

**Comment by FroMage** [comment]
Well in that case I'd say let's leave it as-is until there's a quarkus-wide style decision, ok?

**Comment by geoand** [comment]
Certainly, closing the PR then

**Pull request closed without merging**
