### PR TITLE
Revisit the non-standard behavior of ArcContainer#instanceSupplier()

### LINKED ISSUE #28115: Revisit the non-standard behavior of ArcContainer#instanceSupplier()
### Description

Namely this part: https://github.com/quarkusio/quarkus/blob/2.13/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L266-L276

Note that a change would break the compatibility because some extensions rely on this behavior (e.g. undertow).

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #28115 

This would be a breaking change in `ArcContainer#instanceSupplier()` because there can be other extensions (outside of this repo) that use this method unknowingly via `BeanContainer#instanceFactory` and those might rely on the non-CDI behavior that the underlying resolution performed.

Theoretically, we could instead deprecate `instanceSupplier()` method (as well as the method on `BeanContainer`) and keep their current behavior while introducing new ones with similar names that would behave per spec. That'd give extension creators time to adapt. WDYT @mkouba?

As for our own extensions, I am stuck with RE reactive and its handling of `@Provider`. The second commit shows the issue - the altered test would lead to ambig. exception (expected due to changes in `BeanContainer#instanceFactory`) but I am adding `@Typed` to all providers. Despite the fact that RE will register such provider, but will not use it during test execution. I might need someone with RE internals knowledge to take a look and tell me what I am missing...

### CODE REVIEW

**Comment by manovotn** [comment]
Added commit from @geoand that solves the issue I encountered.
We'll still need to make the RR transformation more refined

**Comment by manovotn** [comment]
I've updated the RR processor to transform annotations using RR build items as per @geoand suggestion.

I also noticed that I can still get intermittent failures of the `ChunkedResponseTest` - running the test repeatedly sometimes yields a failure locally which means that https://github.com/quarkusio/quarkus/pull/28429/commits/fc76c76d954990ffed2a5a7329a97cee0f7c856d didn't fix it completely.

**Comment by geoand** [comment]
Thanks for the update. I'll have a look on Monday.

**Comment by geoand** [comment]
I pushed two commits:

* One that reverts my previous fix (this should be squashed with the commit that introduced the change - I didn't want to do this myself as it's not branch so having to rebase would come as a surprise to you)
* One that introduces a proper fix (or at least what seems to be a proper fix as I ran the tests multiple times and they always passed)

**Comment by manovotn** [comment]
@geoand silly question but did you rebuild all the parts? I am still seeing the failure and it is not even intermittent now - I am getting it on every run.

**Comment by geoand** [comment]
You are right, seems I must have missed something.

**Comment by geoand** [comment]
The reason we don't want my initial commit is that it breaks the TCK, so I need to figure out a different approach

**Comment by geoand** [comment]
Should be fixed now. My comment about squashing the two sorting commits I mentioned above still applies.

**Comment by geoand** [comment]
Great, thanks!

**Comment by manovotn** [comment]
I've added a commit that renames affected methods and re-introduces the original methods as `@Deprecated`. This prevents us from immediately breaking extensions outside of our code base in this repo and gives users a grace period to adjust.

All usages in our codebase haven been changed to use the new variants (hence the label explosion on this PR).

**Comment by geoand** [comment]
The TCK failure also occurred on https://github.com/quarkusio/quarkus/pull/27526 so it's unlikely to be related to this

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28498 fixes the test failure

**Comment by manovotn** [comment]
Alright, I've rebased to include that commit

**Review by mkouba — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
