### PR TITLE
Adds test random port

### LINKED ISSUE #2269: Random port configuration of port in tests
Currently, there is one property called `quarkus.http.test-port` where you can set the port number where to start the Quarkus server, but we should provide a special char for setting a random private port (49152 through 65535)

I purpose something like `quarkus.http.test-port=$`

This is important for allowing the system to execute tests in parallel.

If agrees I can send a PR.

### PR DESCRIPTION
**Pull request by lordofthejars**
Fixes #2269

### CODE REVIEW

**Review by n1hility — CHANGES_REQUESTED** [review]
For this to work correctly I think it will need to verify the port is bindable, otherwise the chances of colliding with another ephemeral port are high.

Implementation wise I would recommend letting the OS do this. The best way to do it would be to pass the port straight through and then query what it ended up being.  Otherwise you could just construct a ServerSocket on 0 with the proper interface (but then you have to figure out which it is), and then call getLocalPort on that and pass it to the server (after closing the socket). There is still a race condition in this scenario though.

**Comment by lordofthejars** [comment]
yes I agree on changing how random port is calculated, what I do not see is a race condition. Because ThreadLocal is for thread hence any parallel thread will have their own instance. Maybe you see the race condition in another place but or possibly also I am missing some important case.

**Comment by lordofthejars** [comment]
@n1hility Ok now I think the race condition and how the random port is found has been fixed.

**Comment by dmlloyd** [comment]
There's definitely still a race - you're binding and closing a port, then binding it again; in the meantime something else could steal it.  But I think this risk is fairly minimal.  @n1hility?

**Comment by lordofthejars** [comment]
@dmlloyd But I am storing in a list inside a sync block.

**Comment by dmlloyd** [comment]
It can be chosen by any other process in the system at any time.  The OS *probably* won't assign it, but any program definitely can bind it.

**Comment by lordofthejars** [comment]
@dmlloyd but notice here https://github.com/quarkusio/quarkus/pull/2324/files#diff-9c615e8c2b594c0d5e168fe03bad4864R52 I am checking that the has never been chosen before.

**Comment by dmlloyd** [comment]
I see, but consider the following sequence of events:

* Process A: enter generate
    * open socket, bind port
    * close socket, return port #
* Process B: bind socket on port #
* Process A: try to bind port #, fail

You're not really allocating a port, you're just finding one that happens to be unused, then closing the socket, and then hoping that when you bind the port, it's still unused.  And it will be most of the time because I think the OS won't reassign ports that are in `TIME_WAIT`, but it is *possible* that some other process might decide to bind that exact port during the window when process A doesn't really "own" it.

**Comment by lordofthejars** [comment]
Yes but notice that all the method is synchronized and it is static, so process A enters into the block, when it left there is a Port let's say 45678 this port is stored in a list. Then Port B tries to enter, if it has not been assigned into this list, the Process B will wait until the port is stored in this list  (Process A), then Process B will enter and if the port (still not binded is returned by OS) this port is in the `usedPorts` list hence the loop happens and the OS will return another one.

**Comment by aloubyansky** [comment]
I think in David's scenario Process B is not using your utility class but binding the port directly?

**Comment by Sanne** [comment]
hi @lordofthejars,

this PR is stalled for two reasons:
 
1. it needs rebasing, as there's a conflict now. That's why @aloubyansky added the "needs rebase" label, that's going to block any further review.
2. you need to address the race condition issue highlighted by @dmlloyd and @n1hility, the current solution isn't safe; let me try to clarify what the others told you:

If you choose a random port which is available during the test fixture, but don't immediately "reserve" the socket, this port could be stolen by another process right after your setup code was run.

(that's not too unlikely: imagine someone running multiple Quarkus builds on the same machine, with each test sequentially choosing a random port and then using it only later, it's pretty much guaranteed to produce random failures)

Ideally we should have the tested server to start first, on port 0, then (and only then) the client gets the port from it and the test is started by connecting on that same port.

If that's not possible (I don't know much about the phases of test bootstrap), I guess we could accept a minimal risk of races, if the whole suite is always using the same port. That might be acceptable, but it's something we need to discuss so we need you to first understand the problem (and in that case I suspect you'd not use a threadlocal, and neither need to hold on a set of intetegers, or need a loop to try multiple numbers).

Thanks

**Comment by lordofthejars** [comment]
But this port problem is not happening as it is protected in the list, so notice that I have a list of already chosen ports, so if tests are run in the same JVM then it cannot happen that two processes with the same port (https://github.com/quarkusio/quarkus/pull/2324/files#diff-9c615e8c2b594c0d5e168fe03bad4864R52) So every quarkus instance will contain a different port.

Said that if the tests are run in different JVMs, then there is a problem hard to resolve as every instance runs in an independent structure, so some kind of file should be used to pass the information (for example working in an offset way).

**Comment by Sanne** [comment]
> But this port problem is not happening as it is protected in the list, so notice that I have a list of already chosen ports, so if tests are run in the same JVM then [...]

Sure, you already said that but we're all talking about other processes, other OS components, and I'm making the very concrete example of a different Quarkus build being run. That's different JVMs.


> Said that if the tests are run in different JVMs, then there is a problem hard to resolve as every instance runs in an independent structure, so some kind of file should be used to pass the information (for example working in an offset way).

There's no need for a file, as mentioned above all it takes is to open the port first. Please see the above suggestions, now that we're on the same page as to what the problem is, it might be worth reading Jason's and David's suggestions again :-)

**Comment by lordofthejars** [comment]
@Sanne yes I am talking about the same different Quarkus being run not different OS processes. Notice the algorithm, 1) make OS to choose a random port 2) check if port has been assigned previously to run with quarkus (list https://github.com/quarkusio/quarkus/pull/2324/files#diff-9c615e8c2b594c0d5e168fe03bad4864R26) if it has been set it iterates and ask the OS to another port. 3) finds a port which can be used it adds to `used` list and it is used to start Quarkus

If there is another Quarkus process starting at the same time it will try to allocate a port, if this port is in the list will be skipped if not it will be chosen. And since everything is synchronized it cannot happen same port to two Quarkus process.

If you want I can do a BJN session as concurrent things are always hard to explain.

**Comment by Sanne** [comment]
@lordofthejars sure I've seen the code and the synchronized block. It's not safe: between the time you added it to the list, and Quarkus is actually started to use it, the situation isn't necessarily the same any longer.

**Comment by lordofthejars** [comment]
I don't see it sorry. Generate is responsible of calculating a port and store it in the list and all method is sync and it is in this phase where the port is chosen and it is known to be free.

**Comment by lordofthejars** [comment]
Ok, now I understand the problem but I do not know exactly how we could fix it as there are really two different processes even for example other Quarkus processes starting in the middle, but I do not see now how to fix this problem globally. If there is any suggestion or idea on how to solve this.

**Comment by Sanne** [comment]
sure, the suggestion is what we wrote earlier: boot the Quarkus server using port 0, then read the port from it - without releasing the port in between.

In other words, rather than have a utility invoke `new ServerSocket(0)` upfront, you start the Quarkus application on port 0 as first step.

**Comment by lordofthejars** [comment]
ok, then random ports are already supported, I just need to use the property and set it to 0, so this PR has no sense.

**Comment by Sanne** [comment]
why "no sense" ? Sorry I don't know the goal of this PR, I was expecting the test helpers to be able to "get" the port which was chosen, which probably still needs something among the lines of your `RestAssuredURLManager` ?

**Comment by lordofthejars** [comment]
Yes exactly, what I mean with no sense is that it is totally a different direction. I'll need to find some time to think about it.

**Comment by Sanne** [comment]
fair enough! Nobody said this would be easy :-)

Thanks a lot

**Comment by FroMage** [comment]
Well, should we not close this PR and #2269 because we already support setting the port to `0` to get a random free port? @emmanuelbernard ?

**Comment by emmanuelbernard** [comment]
My reading is that you need to read that random port and give it to restassured and to the `@TestHTTPResource` facility. At least I don’t then no anyone tried with the port 0 setting.

**Comment by FroMage** [comment]
OK, so this needs to simply look at how setting `0` for a port works, and making sure we can obtain the port and use it from restassured. Sounds good @lordofthejars ?

**Comment by lordofthejars** [comment]
Sounds good my concerns is how I can get this info from Undertow but I'll
explore code later

**Comment by dmlloyd** [comment]
Any updates on this one?

**Pull request closed without merging**
