### PR TITLE
Eliminate Config accessor object usage wherever possible

### PR DESCRIPTION
**Pull request by geoand**
Accessors are only now used when a field or class is non-public (we have such an example in the Quarkus codebase with Neo4j)

### CODE REVIEW

**Comment by geoand** [comment]
PR is in draft state because I didn't run all tests locally and want to see what CI says on my fork

**Comment by geoand** [comment]
Turns out there is an issue with package-private config objects. I'll take a look later on

**Comment by geoand** [comment]
@stuartwdouglas mind also taking a quick look?

Thanks

**Review by stuartwdouglas — APPROVED** [review]

**Comment by geoand** [comment]
Thanks for the review @stuartwdouglas.

@dmlloyd can you think of any reason why this shouldn't go in?

**Comment by dmlloyd** [comment]
It should be OK, as long as the tests pass.

**Comment by geoand** [comment]
:+1: 

I let CI run the whole testsuite twice (and that's after it had picked up the Neo4J issue which I fixed)

**Pull request merged**
