### PR TITLE
Ensure that multipart response has a boundary when RestResponse is used

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #29794
Fixes: #29685

### CODE REVIEW

**Comment by geoand** [comment]
@Sgitario can you have a quick look at this please?

**Review by Sgitario — APPROVED** [review]
I've just confirmed that these changes also fix this issue: https://github.com/quarkusio/quarkus/issues/29685

**Comment by gsmet** [comment]
Good call checking this other issue. Added the other issue to the description so that it gets properly tracked.

**Comment by geoand** [comment]
Oh nice! I had no idea :)

Thanks for being vigilant!

**Pull request merged**
