### PR TITLE
Initialize a properly configured ProviderFactory at static init time

### LINKED ISSUE #2040: JAX-RS exceptions in native mode CNFE javax.ws.rs.ext.Providers
Hi I see a lot of exceptions:
```
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.JaxrsFormProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.JaxrsFormProvider...........
```

when I build https://github.com/quarkusio/quarkus-quickstarts/tree/master/using-opentracing to native executable. Is it problem with the example or bug?

Full log: https://pastebin.com/TN0yfCzN

### PR DESCRIPTION
**Pull request by gsmet**
Currently, the ProviderFactory is not properly configured as it doesn't
respect at all the provided configuration.

Fixes #2040

### CODE REVIEW

**Comment by gsmet** [comment]
@kenfinnigan interested in your feedback on this one.

I will ping the RESTEasy people to see if we can get a clean way to get a client provider factory properly initialized and respecting the configuration.

**Comment by kenfinnigan** [comment]
Clearly I don't understand RESTEasy Client provider registration!

My only question would be whether it's better to have the static init pieces in separate build steps, as the majority of the methods don't require the static init piece. Not sure if that improves build performance or not.

**Comment by gsmet** [comment]
We weren't really careful about that for the other extensions. It makes sense though and is particularly true in this case (and makes sense from a logic point of view). I'll take a look.

**Comment by kenfinnigan** [comment]
Doesn't have to hold up this change, was just curious if that's something we should be looking to do, minimize the work done in a static init build step

**Comment by gsmet** [comment]
I think it's probably better as I suspect the recorder as to inspect the calls. I wouldn't do it if it complicated the logic though or if the template call was the result of some prior code.

**Review by emmanuelbernard — APPROVED** [review]

**Comment by emmanuelbernard** [comment]
@gsmet it cursorily LGTM (so I approved the review) but you might want another 👍 from the RESTEasy team or @kenfinnigan

**Comment by kenfinnigan** [comment]
I'm good with it as is, we can rework later

**Pull request merged**
