### PR TITLE
Upgrade of kogito to 0.7.0 plus required adjustments

### PR DESCRIPTION
**Pull request by mswiderski**
- Updated jandex proto generator to allow exclusion of static and transient, support simple types for collections
- KOGITO-801 - Live/Hot reload does not work when adding a process definition to a skeleton project
- upgrade kogito dependencies after internal refactoring

### CODE REVIEW

**Comment by geoand** [comment]
@mswiderski Thanks for the PR!

CI seems to be complaining:

```
2020-01-18T07:47:26.1838592Z [INFO] Running io.quarkus.it.kogito.drools.DroolsTest
2020-01-18T07:47:35.5672856Z 2020-01-18 07:47:29,446 WARN  [org.kie.kog.cod.GeneratorContext] (build-9) Unable to load 'application.properties'.
2020-01-18T07:47:35.5680213Z 2020-01-18 07:47:31,896 INFO  [org.kie.kog.cod.pro.ProcessCodegen] (build-9) Generating REST Resources.
2020-01-18T07:47:35.5681520Z 2020-01-18 07:47:31,897 INFO  [org.kie.kog.cod.pro.ProcessCodegen] (build-9) Generating REST Resources.
2020-01-18T07:47:35.9055626Z 2020-01-18 07:47:35,904 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.815s. Listening on: http://0.0.0.0:8081
2020-01-18T07:47:35.9062099Z 2020-01-18 07:47:35,904 INFO  [io.quarkus] (main) Profile test activated. 
2020-01-18T07:47:35.9063115Z 2020-01-18 07:47:35,905 INFO  [io.quarkus] (main) Installed features: [cdi, kogito, resteasy, resteasy-jackson]
2020-01-18T07:47:37.4066885Z [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.22 s - in io.quarkus.it.kogito.drools.DroolsTest
2020-01-18T07:47:37.4068143Z [INFO] Running io.quarkus.it.kogito.jbpm.OrdersProcessTest
2020-01-18T07:47:37.4577206Z Order has been created Order[12345] with assigned approver john
2020-01-18T07:47:37.4779079Z 2020-01-18 07:47:37,474 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /runProcess failed, error id: 38879176-4867-4a5a-9060-9d088bacc83a-1: org.jboss.resteasy.spi.UnhandledException: java.lang.AssertionError
2020-01-18T07:47:37.4790114Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
2020-01-18T07:47:37.4790858Z 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
2020-01-18T07:47:37.4791367Z 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
2020-01-18T07:47:37.4798709Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
2020-01-18T07:47:37.4799411Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
2020-01-18T07:47:37.4799879Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
2020-01-18T07:47:37.4807178Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
2020-01-18T07:47:37.4807948Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
2020-01-18T07:47:37.4814732Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
2020-01-18T07:47:37.4815349Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2020-01-18T07:47:37.4815854Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
2020-01-18T07:47:37.4828446Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
2020-01-18T07:47:37.4829120Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
2020-01-18T07:47:37.4835184Z 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-01-18T07:47:37.4835814Z 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
2020-01-18T07:47:37.4872905Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
2020-01-18T07:47:37.4906274Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
2020-01-18T07:47:37.4907336Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2020-01-18T07:47:37.4923129Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2020-01-18T07:47:37.4923796Z 	at java.lang.Thread.run(Thread.java:748)
2020-01-18T07:47:37.4924915Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-01-18T07:47:37.4925403Z Caused by: java.lang.AssertionError
2020-01-18T07:47:37.4925848Z 	at io.quarkus.it.kogito.jbpm.OrdersProcessService.testOrderProcess(OrdersProcessService.java:54)
2020-01-18T07:47:37.4944785Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by mswiderski** [comment]
@geoand thanks for extracting details. I updated test case as it seemed to be not really what it was suppose to be. Let's see if now CI would be happy.

**Comment by mswiderski** [comment]
we are investigating reported failures ... will drop a note as soon as they are resolved.

**Comment by geoand** [comment]
Cool, thanks

**Comment by gsmet** [comment]
@mswiderski just FYI, cut-off for 1.2 is this evening.

**Comment by mswiderski** [comment]
@gsmet yes, I am aware but I am afraid we won’t make it in time :( but let’s keep the pr open for a while more

**Comment by gsmet** [comment]
Force pushed a rebase to trigger CI.

**Comment by gsmet** [comment]
This one needs more work. CI failed in related tests.

**Comment by mswiderski** [comment]
@gsmet this now is ready for merge

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
