### PR TITLE
Update and prune Liquibase xsd files that are included in native image

### PR DESCRIPTION
**Pull request by famod**
We missed to add the newer ones in the last updates.

To reduce native image size, I removed everything before 4.7 (which is the version Quarkus 2.7 uses).

I left the test changelog files at 4.9 for now.

Since 4.12 there is also a "latest" xsd link, but I think we want more stability...?
https://github.com/liquibase/liquibase/releases/tag/v4.12.0
> Introduced "latest" xsd file path. In addition to `http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.12.xsd` type XSDs references, you can now also use `http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd` instead. By using "latest", Liquibase will use the bundled XSD for it's version. The uploaded "latest" XSD will always be the most recent Liquibase release, so note how they can be different and locally cached IDE versions may be different yet.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
@famod should we backport this too?

**Comment by famod** [comment]
@gastaldi I would say yes. There's a slight "breaking" notion though, in that some user might need to update their xml files in case they are still using very old xsds.
Still, I think it makes sense to backport it to 2.10 and 2.11.

**Comment by famod** [comment]
Ok. I'll do that and I'll also create a PR for 2.10 only adding the newer missing xsds.

**Comment by rsvoboda** [comment]
Just for the record: 

QS updated in https://github.com/quarkusio/quarkus-quickstarts/pull/1147

Migration Guide 2.11 contains entry about this change: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.11#old-liquibase-xsd-files-removed-from-native-image

**Pull request merged**
