### PR TITLE
Update SR JWT to 3.0.0-RC4 (MP4)

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@radcortez Hey Roberto, switching to non-SNAPSHOT dependency looks reasonable to me, but please decide yourself if you happy enough with it

**Comment by tobiasstadler** [comment]
@sberyozkin microprofile-4 branch already uses a non snapshot version, currently 3.0.0-RC3.

**Comment by sberyozkin** [comment]
@tobiasstadler Oh I thought it was still on the snapshot :-)

**Review by sberyozkin — APPROVED** [review]
LGTM

**Review by radcortez — APPROVED** [review]

**Comment by tobiasstadler** [comment]
Thank You

**Pull request merged**
