### PR TITLE
MongoDB Panache reactive: database name is not taken from the annotation

### LINKED ISSUE #23813: @MongoEntity with database parameter does not detect database when using mongo panache
### Describe the bug

The following is my code structure:

```
public interface BaseMongoRepository<T extends BaseMongoEntity>
         extends ReactivePanacheMongoRepository<T>  {}

public interface UserRepository 
        extends BaseMongoRepository<UserEntity> {}

public class BaseMongoRepositoryImpl<T extends BaseMongoEntity> 
        implements BaseMongoRepository<T> {}

public class UserRepositoryImpl
        extends BaseMongoRepositoryImpl<UserEntity>
        implements UserRepository

@MongoEntity(database = "userDB", collection= "users")
public class User {}
```

When I'm running this code, mongo panache fails with IllegalArgumentException:

`The database attribute was not set for the @MongoEntity annotation and neither was the database property configured for the default Mongo Client (via 'quarkus.mongodb.database').`

If I pass the default client using `quarkus.mongodb.database`, all my collections are created in the same database. However, the collections args for @MongoEntity works fine. 

### Expected behavior

When passing @MongoEntity(database = "userDB"), the collection should be created in the userDB database.

### Actual behavior

If no default database is passed in application.properties, an error is thrown. Else the collection is created in the default database.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Homebrew (build 17.0.2+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.2+0, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 17.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home Default locale: en_IN, platform encoding: UTF-8 OS name: "mac os x", version: "12.0.1", arch: "aarch64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #23813

### CODE REVIEW

**Review by evanchooly — APPROVED** [review]

**Comment by loicmathieu** [comment]
> though we should have tests for this in both variants...

I was afraid you'll said that, I knew you'll said that ...
But the test would take more time to write than the fix ! But OK, I should have done it anyway ;)

I'll write a small test next week.

**Comment by gsmet** [comment]
@loicmathieu I merged this one as I want to backport it in tomorrow's version. Please add the test in a separate PR. Thanks!

**Comment by loicmathieu** [comment]
@gsmet great, I'll provide a test later this week

**Comment by romilpunetha** [comment]
When is this fix getting released?

**Comment by gsmet** [comment]
@romilpunetha tomorrow in 2.7.3.Final if all goes well.

**Pull request merged**
