### PR TITLE
Introduce new JPMS exports to allow running native-image on module-path

### PR DESCRIPTION
**Pull request by zakkak**
Once https://github.com/oracle/graal/pull/4468 gets merged, native-image will run on module-path requiring some additional exports to be passed to it in order to access internal APIs.

Marking as Draft till I finish testing it with https://github.com/oracle/graal/pull/4468

### CODE REVIEW

**Comment by jerboaa** [comment]
@zakkak Could we move this out of draft now, please? It looks like our nightly mandrel builds are failing miserably because of https://github.com/oracle/graal/pull/4468

See for example:
https://github.com/graalvm/mandrel/runs/6824595648

**Comment by zakkak** [comment]
@jerboaa this is not ready to be merged though.  
We should only export these modules if graalvm is newer than 22.1. Additionally there is still an issue with the awt test which @olpaw is investigating. Hopefully we will have these ready next week. 

In the meantime for Mandrel's CI we can set `USE_NATIVE_IMAGE_JAVA_MODULE_SYSTEM` to `false` for now.

**Comment by jerboaa** [comment]
> In the meantime for Mandrel's CI we can set `USE_NATIVE_IMAGE_JAVA_MODULE_SYSTEM` to `false` for now.

Fair enough. As long as we keep a tracker with remaining issues and flip that once everything is fixed.

**Comment by zakkak** [comment]
> We should only export these modules if graalvm is newer than 22.1. Additionally there is still an issue with the awt test which @olpaw is investigating. Hopefully we will have these ready next week.

Both issues are now tackled and this is ready for review.

**Review by geoand — APPROVED** [review]

**Pull request merged**
