### PR TITLE
Ensure that Google Cloud Functions and Jib extensions work together

### LINKED ISSUE #33011: Building an image with jib fails when adding the quarkus google cloud functions extension
### Describe the bug

After adding the google cloud functions extension to my project, building images with the jib extension failed

### Expected behavior

I should still be able to build an image using jib when adding the google cloud functions dependency

### Actual behavior

The build fails with exception:
```
Base image 'registry.access.redhat.com/ubi8/openjdk-17-runtime:1.15' does not use a specific image digest - build may not be reproducible
> Task :quarkusAppPartsBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
                at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:255)
                at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:181)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
                at java.base/java.lang.reflect.Method.invoke(Method.java:578)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
                at java.base/java.lang.Thread.run(Thread.java:1623)
                at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Caused by: java.util.concurrent.ExecutionException: java.nio.file.NoSuchFileException: /Users/emilesteenkamp/Repository/github.com/emilesteenkamp/quarkus-function-google-function-jib-reproducer/build/lib
                at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
                at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
                at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
                at com.google.cloud.tools.jib.builder.steps.StepsRunner.realizeFutures(StepsRunner.java:112)
                at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$buildImage$9(StepsRunner.java:450)
                at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
                at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
                at java.base/java.lang.Thread.run(Thread.java:1623)
        Caused by: java.nio.file.NoSuchFileException: /Users/emilesteenkamp/Repository/github.com/emilesteenkamp/quarkus-function-google-function-jib-reproducer/build/lib
                at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
                at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
                at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
                at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
                at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
                at java.base/java.nio.file.Files.readAttributes(Files.java:1848)
                at java.base/java.nio.file.Files.getLastModifiedTime(Files.java:2391)
                at com.google.cloud.tools.jib.cache.LayerEntriesSelector$LayerEntryTemplate.<init>(LayerEntriesSelector.java:77)
                at com.google.cloud.tools.jib.cache.LayerEntriesSelector.toSortedJsonTemplates(LayerEntriesSelector.java:153)
                at com.google.cloud.tools.jib.cache.LayerEntriesSelector.generateSelector(LayerEntriesSelector.java:169)
                at com.google.cloud.tools.jib.cache.Cache.retrieve(Cache.java:217)
                at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:102)
                at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:38)
                ... 6 more


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.


```

### How to Reproduce?

I have added a reproducer project here

https://github.com/emilesteenkamp/quarkus-function-google-function-jib-reproducer

to reproduce the issue, you can clone the project and run the build command in the Readme

### Output of `uname -a` or `ver`

Darwin Emiles-MacBook-Pro.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "20" 2023-03-21 OpenJDK Runtime Environment Homebrew (build 20) OpenJDK 64-Bit Server VM Homebrew (build 20, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #33011

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
Makes sense!

This is a bit unfortunate that there is multiple way to check that an uber jar is requested, I hope the same issue didn't exist on other extensions.

**Comment by geoand** [comment]
Yeah...

**Comment by geoand** [comment]
The failure is related, I'll have a look tomorrow.

**Comment by Sgitario** [comment]
> Actually they might not be...
> 
> @iocanel @Sgitario I see:
> 
> ```
> 2023-05-10T12:25:48.4787055Z [INFO] [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project knative-jib-build-and-deploy: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> 2023-05-10T12:25:48.4795697Z [INFO] [ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: java.lang.RuntimeException: Although a Kubernetes deployment was requested, it however cannot take place because there was an error during communication with the API Server at 'https://kubernetes.default.svc/'
> 2023-05-10T12:25:48.4800991Z [INFO] [ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeploy.doCheck(KubernetesDeploy.java:80)
> 2023-05-10T12:25:48.4805877Z [INFO] [ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeploy.check(KubernetesDeploy.java:31)
> 2023-05-10T12:25:48.4810610Z [INFO] [ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:121)
> 2023-05-10T12:25:48.4815726Z [INFO] [ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 2023-05-10T12:25:48.4823268Z [INFO] [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
> 2023-05-10T12:25:48.4827936Z [INFO] [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
> 2023-05-10T12:25:48.4832613Z [INFO] [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
> 2023-05-10T12:25:48.4837056Z [INFO] [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> 2023-05-10T12:25:48.4841465Z [INFO] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> 2023-05-10T12:25:48.4848782Z [INFO] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> 2023-05-10T12:25:48.4855616Z [INFO] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1589)
> 2023-05-10T12:25:48.4860037Z [INFO] [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
> 2023-05-10T12:25:48.4864474Z [INFO] [ERROR] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
> 2023-05-10T12:25:48.4869383Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
> 2023-05-10T12:25:48.4874249Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122)
> 2023-05-10T12:25:48.4924654Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.restCall(OperationSupport.java:755)
> 2023-05-10T12:25:48.4977246Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.impl.BaseClient.getVersionInfo(BaseClient.java:276)
> 2023-05-10T12:25:48.4991316Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.getVersion(KubernetesClientImpl.java:613)
> 2023-05-10T12:25:48.4997691Z [INFO] [ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeploy.doCheck(KubernetesDeploy.java:61)
> 2023-05-10T12:25:48.5003091Z [INFO] [ERROR] 	... 11 more
> 2023-05-10T12:25:48.5007903Z [INFO] [ERROR] Caused by: java.io.IOException: kubernetes.default.svc
> 2023-05-10T12:25:48.5012957Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:522)
> 2023-05-10T12:25:48.5024477Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:545)
> 2023-05-10T12:25:48.5031419Z [INFO] [ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.restCall(OperationSupport.java:748)
> 2023-05-10T12:25:48.5036229Z [INFO] [ERROR] 	... 14 more
> 2023-05-10T12:25:48.5040909Z [INFO] [ERROR] Caused by: java.net.UnknownHostException: kubernetes.default.svc
> 2023-05-10T12:25:48.5046091Z [INFO] [ERROR] 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:952)
> 2023-05-10T12:25:48.5051347Z [INFO] [ERROR] 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1663)
> 2023-05-10T12:25:48.5056112Z [INFO] [ERROR] 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1528)
> 2023-05-10T12:25:48.5060866Z [INFO] [ERROR] 	at java.base/java.net.InetAddress.getByName(InetAddress.java:1413)
> 2023-05-10T12:25:48.5065814Z [INFO] [ERROR] 	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
> 2023-05-10T12:25:48.5070500Z [INFO] [ERROR] 	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
> 2023-05-10T12:25:48.5079507Z [INFO] [ERROR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
> 2023-05-10T12:25:48.5085063Z [INFO] [ERROR] 	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
> 2023-05-10T12:25:48.5089973Z [INFO] [ERROR] 	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
> 2023-05-10T12:25:48.5094805Z [INFO] [ERROR] 	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
> 2023-05-10T12:25:48.5098730Z [INFO] [ERROR] 	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
> 2023-05-10T12:25:48.5105826Z [INFO] [ERROR] 	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
> 2023-05-10T12:25:48.5109948Z [INFO] [ERROR] 	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
> 2023-05-10T12:25:48.5113693Z [INFO] [ERROR] 	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
> 2023-05-10T12:25:48.5117337Z [INFO] [ERROR] 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
> 2023-05-10T12:25:48.5120739Z [INFO] [ERROR] 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
> 2023-05-10T12:25:48.5126803Z [INFO] [ERROR] 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
> 2023-05-10T12:25:48.5133076Z [INFO] [ERROR] 	at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:152)
> 2023-05-10T12:25:48.5136770Z [INFO] [ERROR] 	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:103)
> 2023-05-10T12:25:48.5140099Z [INFO] [ERROR] 	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:89)
> 2023-05-10T12:25:48.5143408Z [INFO] [ERROR] 	at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:296)
> 2023-05-10T12:25:48.5146708Z [INFO] [ERROR] 	at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$2(NetClientImpl.java:262)
> 2023-05-10T12:25:48.5149990Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
> 2023-05-10T12:25:48.5153269Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 2023-05-10T12:25:48.5156561Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
> 2023-05-10T12:25:48.5159998Z [INFO] [ERROR] 	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
> 2023-05-10T12:25:48.5163449Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 2023-05-10T12:25:48.5166908Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
> 2023-05-10T12:25:48.5169643Z [INFO] [ERROR] 	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
> 2023-05-10T12:25:48.5172355Z [INFO] [ERROR] 	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
> 2023-05-10T12:25:48.5175044Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 2023-05-10T12:25:48.5177763Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
> 2023-05-10T12:25:48.5180493Z [INFO] [ERROR] 	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
> 2023-05-10T12:25:48.5186173Z [INFO] [ERROR] 	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
> 2023-05-10T12:25:48.5189330Z [INFO] [ERROR] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
> 2023-05-10T12:25:48.5192752Z [INFO] [ERROR] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
> 2023-05-10T12:25:48.5195774Z [INFO] [ERROR] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
> 2023-05-10T12:25:48.5198444Z [INFO] [ERROR] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
> 2023-05-10T12:25:48.5207256Z [INFO] [ERROR] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 2023-05-10T12:25:48.5210206Z [INFO] [ERROR] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 2023-05-10T12:25:48.5213072Z [INFO] [ERROR] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 2023-05-10T12:25:48.5215961Z [INFO] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1589): Unknown host kubernetes.default.svc
> ```
> 
> Any idea what's going on?

I would need to check whether these changes cause this issue (maybe it's about the addition of `List<UberJarRequiredBuildItem> uberJarRequired`). But at first glance, I could not see anything suspicious.

**Comment by geoand** [comment]
This seems to be an actual issue...

**Pull request merged**
