### PR TITLE
Remove deprecated `AppModel`

### PR DESCRIPTION
**Pull request by gastaldi**
- This removes the long-deprecated `AppModel` from the codebase

### CODE REVIEW

**Comment by aloubyansky** [comment]
I'm totally in favor of this change. It's right before the final release though. We need to make sure we don't break the platform with this change.

**Comment by gsmet** [comment]
Let's not merge it now and make it a 3.1 item.

We won't have time to deal with the consequences.

**Comment by gastaldi** [comment]
@aloubyansky grepping the https://github.com/apache/camel-quarkus/ does not give any reference to this class (only `ApplicationModel`). 

Can you confirm @ppalaga?

**Review by gsmet — CHANGES_REQUESTED** [review]
Let's keep it on ice until 3.1 development starts.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Main is now 3.1 so we can merge.

**Comment by gsmet** [comment]
@aloubyansky I let you approve and merge if you're happy with the change.

**Review by aloubyansky — APPROVED** [review]

**Comment by ppalaga** [comment]
Sorry for the late response, yes, this is fine. Thanks for checking @gastaldi!

**Pull request merged**
