### PR TITLE
Revert "Disable failing CodeStarts test"

### PR DESCRIPTION
**Pull request by ia3andy**
This reverts commit 11f37926

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
Let me validate it's OK on my laptop before merging as it's where the test didn't pass at all.

**Comment by ia3andy** [comment]
@gsmet should we merge this?

**Comment by gsmet** [comment]
Can't you read my message above?

**Comment by ia3andy** [comment]
> Can't you read my message above?

@gsmet of course I read it.. it was two hours ago and the CI passed 100% in between, I thought you would have tried it by now and this was just standing by for CI.. My bad :)

**Review by gsmet — APPROVED** [review]

**Pull request merged**
