### PR TITLE
Remove Reactive Messaging in-memory-connector from bom in 1.3.x

### LINKED ISSUE #9540: quarkus-bom 1.3.3 declares smallrye-reactive-messaging-in-memory
smallrye-reactive-messaging-in-memory 1.1.0 doesn't work with Quarkus yet it is in the BOM for 1.3.3 (info from @cescoffier)

It should be dropped from quarkus-bom in the 1.3 branch.

### PR DESCRIPTION
**Pull request by RotBolt**
fixes #9540

cc @michalszynkiewicz @cescoffier

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@gsmet why wasn't it tested?

**Comment by geoand** [comment]
Why wasn't what tested?

**Comment by michalszynkiewicz** [comment]
Why the CI jobs werent triggered.

**Comment by geoand** [comment]
I am pretty sure that those jobs exist in `master` but not in `1.3`

**Comment by geoand** [comment]
The UI seems to be a little messed up. If you go to https://github.com/quarkusio/quarkus/actions/runs/112625186 you can see the jobs that actually ran

**Comment by RotBolt** [comment]
There are 23 checks ran.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Nothing in the code base depends on it, so the tests are not relevant.

**Comment by geoand** [comment]
Let's let @gsmet merge this one since he is the one handling the `1.3` branch

**Comment by michalszynkiewicz** [comment]
@RotBolt how do you see that 23 checks were executed?

**Pull request merged**
