### PR TITLE
Use a custom InitialContextFactoryBuilder to avoid JDK caching #8651

### LINKED ISSUE #8651: Elytron LDAP native test failure
Got this testing latest Graal/Quarkus with OpenJDK 11 (https://github.com/openjdk/jdk11u-dev/commit/f3b9513155b5e36cfc0e74048eca23b38485e0b1):

```
2020-04-17 15:21:30,378 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /api/requiresStandardRole failed, error id: 
4af2a4af-1daf-448c-8336-69ab4abec3c2-1: 
com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: 
Target_java_lang_ClassLoader.createOrGetClassLoaderValueMap()
```

Longer output [here](https://gist.github.com/galderz/54118a03f60e8c2422dcc994469bfb15).

Not 100% sure, but might be related to using OpenJDK instead of labs JDK, since @zakkak's latest failures with Labs JDK and Graal/Quarkus masters (see [here](https://github.com/zakkak/graal/actions/runs/79288545)) do not show a failure.

### PR DESCRIPTION
**Pull request by galderz**
* Recent JDK changes have added caching of InitialContextFactory
instances which results in creating classloaders on the fly.
See JDK-8223260.
* That's not allowed by Graal, so instead use
a custom InitialContextFactoryBuilder to avoid the issue.

Aside from alternative fixes, wonder if there's better options for the implementation of `InitialContextFactoryBuilder`. For example, since we know that `INITIAL_CONTEXT_FACTORY` is set to `com.sun.jndi.ldap.LdapCtxFactory`, could we instantiate it directly? @hartimcwildfly? @darranl (hi! 👋)?

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
@galderz should we backport this PR?

**Comment by galderz** [comment]
Hmmm, error reported in one of the tests:

```
[ERROR] Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 38.558 s <<< FAILURE! - in io.quarkus.it.keycloak.CodeFlowTest
[ERROR] testIdTokenInjection  Time elapsed: 0.756 s  <<< ERROR!
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 401 Unauthorized for http://localhost:8081/web-app
```

Looking...

**Comment by galderz** [comment]
That keycloak failure seems to be a flaky one (see #7340).

**Comment by galderz** [comment]
And this last CI failure shows the failure in https://github.com/quarkusio/quarkus/issues/8782...

**Comment by galderz** [comment]
This is likely to be fixed at the GraalVM level, so hold off integrating this PR for now...

**Comment by galderz** [comment]
Fixed in GraalVM, PR no longer needed.

**Pull request closed without merging**
