### PR TITLE
Fix matrix computation for Ubuntu 24

### PR DESCRIPTION
**Pull request by gsmet**
@holly-cummins I was able to reproduce your issue and this should fix it.

### CODE REVIEW

**Comment by gsmet** [comment]
Let's merge it and see how it goes as this thing is not really tested by this CI run.

**Comment by gsmet** [comment]
@holly-cummins if you can rebase your PR, I would be interested to know the result.

**Comment by holly-cummins** [comment]
> @holly-cummins if you can rebase your PR, I would be interested to know the result.

Confirmed that it's working, and I have JVM tests: https://github.com/holly-cummins/quarkus/actions/runs/12398637710

(Don't be confused by the confusing name of the last commit. I've also forced some of my native and JVM runners onto ubuntu-22 while waiting for https://github.com/quarkusio/quarkus/pull/45160, hence the commit about forcing ubuntu 22. The main matrix calculation is running on 24.)

**Comment by gsmet** [comment]
Awesome, thanks for confirming!

**Pull request merged**
