### PR TITLE
Qute - prefix iteration metadata in a loop

### LINKED ISSUE #20671: Qute: prefix loop metadata
### Description

https://quarkus.io/guides/qute-reference#loop_section says that we get iterator metadata `index`, `hasNext`, `odd` and `even`, but it does not show any example of how to access it, leading me to believe it would be a property of the iterated variable such as `it.index`. I now realise it showed this example:

```java
{#each items}
  {count}. {it.name} 
{/each}
```

Which introduces the `count` metadata, I guess, but because it's not properly introduced I assumed it was a random toplevel.

The docs should be more clear as to which metadata properties are available, and also this is terrible wrt scoping, because it will automatically override any explicitely declared binding named `count` or `index` by surprise.

I do agree it'd be weird to tack these metadata properties to the iterated variable.

In other templates, I've seen the iterated variable name being used as a prefix, though, such as `it_count` or `myVar_hasNext` which greatly limits binding clashes.

Could we get such prefixed properties instead?

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- the prefix is configurable (globally)
- also added "isFirst" and "isLast" properties for convenience
- resolves #20671

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by mkouba** [comment]
CC @FroMage @gsmet

**Comment by mkouba** [comment]
The Native Tests - Windows - hibernate-validator failure is not related:
```
2021-11-04T11:44:17.3729938Z LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)
2021-11-04T11:44:17.3731966Z 	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:502)
2021-11-04T11:44:17.3738330Z 	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:449)
2021-11-04T11:44:17.3740901Z 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
2021-11-04T11:44:17.3743463Z 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
2021-11-04T11:44:17.3746581Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
2021-11-04T11:44:17.3756229Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
2021-11-04T11:44:17.3759036Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
2021-11-04T11:44:17.3842819Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
```

**Comment by mkouba** [comment]
I'm going to merge this one. We can address potential problems later...

**Pull request merged**
