### PR TITLE
Trim spaces in CORS config

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Adding spaces to the lists causes hard to debug
errors.

### CODE REVIEW

**Comment by knutwannheden** [comment]
Wouldn't it make sense if trimming the the elements in a comma-separated list of values were the default behavior of Quarkus, when mapping to a `List` typed `ConfigItem`? That is what I would have expected in any case.

**Comment by sberyozkin** [comment]
@radcortez Hi Roberto, where such a global feature can be controlled, in Quarkus or directly in `smallrye-jwt`.
@knutwannheden good point, the PR is good as it fixes a concrete problem, but indeed, I've certainly had to deal with trimming other list properties by manual trim() :-). I think we should merge this PR and if it can be done by default in Quarkus without any side-effects then all the `trim()` code dealing with the configs can be gradually removed

**Comment by radcortez** [comment]
> @radcortez Hi Roberto, where such a global feature can be controlled, in Quarkus or directly in `smallrye-config` ?

SR Config :) Strange. I thought that it was already trimming spaces, but I guess not. I'll have to check. We are also going to improve how empty values are handled: https://github.com/eclipse/microprofile-config/issues/446

**Comment by gsmet** [comment]
IIRC it trims spaces for some types (e.g. Integer, boolean) but not for Strings.

Otherwise, it would be impossible to configure something ending with a space, which could happen (think of a prefix in the subject of emails you send).

There's no real perfect solution for this. Or maybe it could be the default and then we would have a specific annotation or parameter to say "don't trim this string".

**Comment by radcortez** [comment]
Ah, yes. Trimming is only applied for non String types.

**Comment by gsmet** [comment]
Got hit by CI master issue, I rebased and force pushed.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
