### PR TITLE
Add defaultGoal clean install to quick-build profile

### PR DESCRIPTION
**Pull request by famod**
As discussed here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/quick.20build.20with.20-Dquickly/near/202108542

Btw, I left out the profile in `devtools/gradle` as it auto-inherits the `defaultGoal` from `quarkus-parent` (via `build-parent`).

### CODE REVIEW

**Comment by famod** [comment]
cc @geoand & @aloubyansky

**Review by aloubyansky — APPROVED** [review]
Thanks!

**Review by geoand — APPROVED** [review]
Very nice 👌

**Comment by famod** [comment]
I don't think this one test failure is related.

**Comment by geoand** [comment]
Yeah, seems like a flake

**Pull request merged**
