### PR TITLE
Stop index warn by excluding resource removed by extension from indexing

### LINKED ISSUE #27907: Failed to index ResteasyJackson2Provider using the keycloak-admin-client-reactive extension
### Describe the bug

The `quarkus-keycloak-admin-client-reactive` extension excludes dependencies from classic RESTEasy including org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.

The keycloak-admin-client dependency has a `JacksonProvider` class that extends `ResteasyJackson2Provider`.

When Quarkus is building the app, it prints a `WARNING` that can't index the `org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider` because it doesn't exist.

### Expected behavior

No warning in the build output.

### Actual behavior

```
[INFO] --- quarkus-maven-plugin:2.12.2.Final:build (default) @ viz-rest-api ---
[WARNING] [io.quarkus.arc.processor.BeanArchives] Failed to index org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@3237522b
[INFO] [io.quarkus.arc.processor.IndexClassLookupUtils] Class for name: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider was not found in Jandex index. Please ensure the class is part of the index.
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 17.0.4.1

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #27907

Excludes resources removed by extension from indexing as according to `io.quarkus.maven.ExtensionDescriptorMojo#removedResources` should be equivalent of `quarkus.class-loading.removed-resources`, however later classes are excluded from indexing while former are not. Fix is used  to exclude `org.keycloak.admin.client.JacksonProvider` that extends `org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider` from indexing. The file is never used as we set `io.quarkus.keycloak.admin.client.reactive.runtime.ResteasyReactiveKeycloakAdminClientRecorder#setClientProvider` and it produces incorrect warning (see linked issue).

### CODE REVIEW

**Comment by michalvavrik** [comment]
cc @geoand I can divide this to 2 PRs if you think it's appropriate. I added this as one PR as changes are tiny.

**Comment by geoand** [comment]
Hi,

Thanks for this!
We definitely want this to be two different commits (it can remain a single PR though).

Furthermore, I'd like @aloubyansky to verify this

**Comment by aloubyansky** [comment]
Looks good, thanks!

**Comment by michalvavrik** [comment]
PR is split into 2 commits. Thank you for reviews.

**Review by geoand — APPROVED** [review]

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
