### PR TITLE
Allow to define parent first artifacts in fast jar mode

### LINKED ISSUE #17391: Cannot load artifacts in parent first manner in fast jar mode
## Describe the bug

The property `quarkus.class-loading.parent-first` is not taken into account in fast jar mode such that we cannot use it to workaround LinkageError like in https://github.com/quarkusio/quarkus/issues/9300 but when the artifact cannot be excluded because it contains classes that are needed by the application.

### Expected behavior

We can force Quarkus to load classes of the artifacts defined with `quarkus.class-loading.parent-first` using the parent ClassLoader first.

### Actual behavior

The property `quarkus.class-loading.parent-first`  is ignored in case of a fast jar such that we can get LinkageError

### PR DESCRIPTION
**Pull request by essobedo**
fixes #17391 

## Motivation

In case a dependency of the application contains classes that are part of the JDK, we can end up with `LinkageError`. This is typically what happens when we have a dependency that contains the class `javax.xml.namespace.QName`, because this class is still part of the JDK.

The official workaround is to define the artifact with `quarkus.class-loading.parent-first-artifacts` but it is ignored in fast jar mode.

## Modifications

* Relies on `ClassLoadingConfig` to extract the parent first artifacts that are defined by the enduser to build a collection of artifact keys to define as  parent first artifacts in the model.
* Adds an integration test to ensure that it works as expected in build mode whatever the target packing type
* Adds an integration test to ensure that it works as expected in dev mode

### CODE REVIEW

**Comment by essobedo** [comment]
@stuartwdouglas it is the PR for the problem that I described [here](https://github.com/quarkusio/quarkus/pull/17248#issuecomment-845182005). WDYT of it?

**Comment by famod** [comment]
@essobedo CI says there is a formatting issue. Please check/fix.

**Comment by essobedo** [comment]
> @essobedo CI says there is a formatting issue. Please check/fix.

@famod Fixed, thx

**Review by stuartwdouglas — APPROVED** [review]
LGTM. With our internal parent first stuff we differentiate between dev/test and prod, but I don't think it really matters here because you can control it via profiles.

**Comment by stuartwdouglas** [comment]
Thanks for the patch

**Comment by essobedo** [comment]
@stuartwdouglas Thx for reviewing and merging it, do you want a backport for the branch 1.13?

**Pull request merged**
