### PR TITLE
Revisit options challenge endpoints

### PR DESCRIPTION
**Pull request by ynojima**
Addresses #45091, Follow-up for #44105

- Changes `/q/webauthn/register-options-challenge` and `/q/webauthn/login-options-challenge` endpoints from `POST` to `GET`
  - They now accepts parameters as query parameters instead of request body JSON
- The username parameters are renamed to `username` from `name` or `userName` for consistency
- Make `user` parameter of `loginCLientSteps` method optional

I couldn't update the webauthn-*.svg files as I don't have the original files.

### CODE REVIEW

**Review by FroMage — CHANGES_REQUESTED** [review]
Besides the JS function, this is great. I can take care of updating the migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.18/#webauthn and the Quickstart (https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-webauthn-quickstart and https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-webauthn-reactive-quickstart if it actually turns out we need to update them) when we merge this.

Although, perhaps this is our last chance to rename `userName` to `username` and make this lowercase, what do you think?

**Comment by ynojima** [comment]
> Although, perhaps this is our last chance to rename `userName` to `username` and make this lowercase, what do you think?

I prefer `username`.

**Comment by FroMage** [comment]
> > Although, perhaps this is our last chance to rename `userName` to `username` and make this lowercase, what do you think?
> 
> I prefer `username`.

Alright, let's change it to username then, fix this now. Do you mind doing it as part of this PR?

**Comment by ynojima** [comment]
@FroMage I've addressed `userName` renaming and webauthn.js issue. could you review again?

**Review by FroMage — CHANGES_REQUESTED** [review]
Looks great. Could you rebase your commits to group them better? In particular the WIP and `userName->username` ones could be merged.

**Comment by FroMage** [comment]
The quickstart failure is expected, since you have a PR pending there.

**Comment by ynojima** [comment]
@FroMage Oh, I recalled why I marked it WIP. 
I couldn't update the webauthn-*.svg files as I don't have the original files. Could you update the webauthn-*.svg files?

**Comment by FroMage** [comment]
> @FroMage Oh, I recalled why I marked it WIP. I couldn't update the webauthn-_.svg files as I don't have the original files. Could you update the webauthn-_.svg files?

Oh, oops. Let me see…

**Comment by ynojima** [comment]
Rebased to main and merged some commits that are close in content

**Comment by FroMage** [comment]
OK, should be good.

**Review by FroMage — APPROVED** [review]

**Pull request merged**
