### PR TITLE
Add the ability to configure the maximum form attribute size

### LINKED ISSUE #16422: Resteasy Reactive - Multipart does not accept text/plain bigger than 2048 bytes
## Describe the bug

I am currently migrating a small app from Resteasy Classic to Resteasy Reactive.

One of my resources uses multipart to accept form input from users.

2048 or less bytes work, the text field contains the input text.
If the users enters more than 2048 bytes, the text field is null.
No exception is thrown.

My resource:
```
@POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@MultipartForm SomeData data)
```

```
import org.jboss.resteasy.reactive.PartType;

import javax.ws.rs.FormParam;

public class SomeData {
    @FormParam("text")
    @PartType("text/plain")
    private String text;
}
```

### Expected behavior
A text/plain field should not be arbitary limited to 2048 bytes. 

It should work like with Resteasy Classic, with the only limit being the configured quarkus.http.limits.max-body-size.

### Actual behavior
`@PartType("text/plain")` is left null if input text is longer than 2048 bytes.

## To Reproduce

1. Download the reproducer: [rr-large-multipart.zip](https://github.com/quarkusio/quarkus/files/6291302/rr-large-multipart.zip)
2. Run the GreetingResourceTest test class. testLargeText will fail.
3. Add another byte to the src/test/resources/2048.rj file.
4. Run the tests again. Now also test2048Bytes will fail.

### Output of `uname -a` or `ver`
Linux martin 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment Zulu15.28+13-CA (build 15.0.1+8)
OpenJDK 64-Bit Server VM Zulu15.28+13-CA (build 15.0.1+8, mixed mode, sharing)

### Quarkus version or git rev
1.13.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/martin/.sdkman/candidates/maven/current
Java version: 15.0.1, vendor: Azul Systems, Inc., runtime: /home/martin/.sdkman/candidates/java/15.0.1-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-48-generic", arch: "amd64", family: "unix"

### PR DESCRIPTION
**Pull request by geoand**
Vert.x defaults to 2K and prior to this PR we didn't have
a way to configure it.

Fixes: #16422

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Probably a good candidate for backport. WDYT @geoand ?

**Comment by geoand** [comment]
Yeah, I think so.

If this doesn't apply cleanly, I can certainly open a PR against the `1.13` branch

**Comment by gsmet** [comment]
@geoand isn't there much to it? Shouldn't we have an exception thrown in the case the form is over the limit? AFAICS from the issue, we just put `null` in the value which sounds a bit weird to me.

**Comment by geoand** [comment]
That sounds reasonable, but I am not sure we can do that - it's something Vert.x handles. @cescoffier do you know how what @gsmet is asking for could be done?

**Comment by cescoffier** [comment]
My understanding is that the request is going to be rejected with a PAYLOAD_TOO_LARGE response. @vietj / @pmlopes can you confirm?

**Comment by geoand** [comment]
> My understanding is that the request is going to be rejected with a PAYLOAD_TOO_LARGE response. @vietj / @pmlopes can you confirm?

That is not what currently happens - currently the form param that exceeds the limit is simply never populated

**Comment by geoand** [comment]
> > My understanding is that the request is going to be rejected with a PAYLOAD_TOO_LARGE response. @vietj / @pmlopes can you confirm?
> 
> That is not what currently happens - currently the form param that exceeds the limit is simply never populated

It seems like Netty does throw an `IOException` which Vert.x handles at: https://github.com/eclipse-vertx/vert.x/blob/4.0.3/src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java#L524.
But that doesn't seem to result in response

**Comment by gsmet** [comment]
Maybe it's just me but I find this code a bit weird. I would at the very least have expected a `return` after the `handleException()`. My very wild guess is that there's something wrong around here.

**Comment by geoand** [comment]
Which code are you talking about?

**Comment by geoand** [comment]
In any case, I don't think there is anything we can in Quarkus, so I'll merge this once CI is done. If there is some way we can integrate with Vert.x to make it fail in the case, in question, we can do it in a follow up

**Comment by gsmet** [comment]
Totally agree it doesn't block this PR but the behavior on the Vert.x side is definitely problematic.

**Comment by pmlopes** [comment]
@geoand @cescoffier @gsmet I don't see how this is related to vert.x, we don't enforce any limit by default, here's a test I've just created to check this issue:

```java
  @Test
  public void testFormMultipartFormDataLarge() throws Exception {
    router.clear();
    router.route().handler(BodyHandler.create());
    router.route().handler(rc -> {
      MultiMap attrs = rc.request().formAttributes();
      assertNotNull(attrs);
      int size = 0;
      assertNotNull(attrs.get("attr1"));
      size += attrs.get("attr1").length();
      assertNotNull(attrs.get("attr2"));
      size += attrs.get("attr2").length();
      assertTrue(size > 2048);
      rc.response().end();
    });
    testRequest(HttpMethod.POST, "/?p1=foo", req -> {
      Buffer buffer = Buffer.buffer();
      String boundary = "dLV9Wyq26L_-JQxk6ferf-RT153LhOO";
      String header =
        "--" + boundary + "\r\n" +
          "Content-Disposition: form-data; name=\"attr1\"\r\n\r\n" + Base64.getUrlEncoder().encodeToString(TestUtils.randomBuffer(1024).getBytes()) + "\r\n" +
          "--" + boundary + "\r\n" +
          "Content-Disposition: form-data; name=\"attr2\"\r\n\r\n" + Base64.getUrlEncoder().encodeToString(TestUtils.randomBuffer(1024).getBytes()) + "\r\n" +
          "--" + boundary + "\r\n" +
          "Content-Disposition: form-data; name=\"" + name + "\"; filename=\"file\"\r\n" +
          "Content-Type: application/octet-stream\r\n" +
          "Content-Transfer-Encoding: binary\r\n" +
          "\r\n";
      buffer.appendString(header);
      buffer.appendBuffer(TestUtils.randomBuffer(50));
      buffer.appendString("\r\n--" + boundary + "--\r\n");
      req.headers().set("content-length", String.valueOf(buffer.length()));
      req.headers().set("content-type", "multipart/form-data; boundary=" + boundary);
      req.write(buffer);
    }, 200, "OK", null);
  }
```

I'm sending a multipart larger than 2kb and there's no problem with that.

**Comment by geoand** [comment]
@pmlopes the problem in your test will likely surface if `attr1` or `attr2` is larger than 2k. 
We would expect Vert.x to return some error, but it seems like the attribute is just silently ignored

**Comment by pmlopes** [comment]
@geoand that doesn't seem to be the vert.x behavior:

```java
  @Test
  public void testFormMultipartFormDataLarge() throws Exception {
    router.clear();
    router.route().handler(BodyHandler.create());
    router.route().handler(rc -> {
      MultiMap attrs = rc.request().formAttributes();
      assertNotNull(attrs);
      int size = 0;
      assertNotNull(attrs.get("attr1"));
      size += attrs.get("attr1").length();
      assertNotNull(attrs.get("attr2"));
      size += attrs.get("attr2").length();
      assertTrue(size > 4096);
      rc.response().end();
    }).failureHandler(ctx -> {
      assertNotNull(ctx.failure());
      assertTrue(ctx.failure() instanceof IOException);
      assertEquals("Size exceed allowed maximum capacity", ctx.failure().getMessage());
      ctx.next();
    });

    testRequest(HttpMethod.POST, "/?p1=foo", req -> {
      Buffer buffer = Buffer.buffer();
      String boundary = "dLV9Wyq26L_-JQxk6ferf-RT153LhOO";
      String header =
        "--" + boundary + "\r\n" +
          "Content-Disposition: form-data; name=\"attr1\"\r\n\r\n" + Base64.getUrlEncoder().encodeToString(TestUtils.randomBuffer(2048).getBytes()) + "\r\n" +
          "--" + boundary + "\r\n" +
          "Content-Disposition: form-data; name=\"attr2\"\r\n\r\n" + Base64.getUrlEncoder().encodeToString(TestUtils.randomBuffer(2048).getBytes()) + "\r\n" +
          "--" + boundary + "\r\n" +
          "Content-Disposition: form-data; name=\"" + name + "\"; filename=\"file\"\r\n" +
          "Content-Type: application/octet-stream\r\n" +
          "Content-Transfer-Encoding: binary\r\n" +
          "\r\n";
      buffer.appendString(header);
      buffer.appendBuffer(TestUtils.randomBuffer(50));
      buffer.appendString("\r\n--" + boundary + "--\r\n");
      req.headers().set("content-length", String.valueOf(buffer.length()));
      req.headers().set("content-type", "multipart/form-data; boundary=" + boundary);
      req.write(buffer);
    }, 400, "Bad Request", null);
  }
```

When the attributes are larger than 2kb then indeed a `DecodeException` is catched in the `BodyHandler` that fails the request with a default `400` failure. The failure is indeed an `IOException` with the message mentioned in the issue.

We could try to make a distinction between 400 and 413 (entity too large) by inspecting the exception type. But this would require a custom exception type in core as `IOException` is too generic.

**Comment by geoand** [comment]
@pmlopes OK, I see. 

We aren't using the body handler in RESTEasy Reactive so I'll need to look into emulating its behavior

**Comment by geoand** [comment]
In light of the previous comments, I **will** actually push changed to this PR

**Comment by gsmet** [comment]
Rebased to get the latest CI fixes.

**Comment by geoand** [comment]
Thanks!

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
This is not easily backportable due to:
```
[ERROR] /data/home/gsmet/git/quarkus/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/MultipartFormHandler.java:[162,32] cannot find symbol
[ERROR]   symbol:   method cancel()
[ERROR]   location: variable fileUpload of type io.vertx.ext.web.FileUpload
```
Should we just avoid calling this method?

**Comment by geoand** [comment]
oh

**Pull request merged**
