### PR TITLE
MongoDB with Panache : avoid to project on the class field

### PR DESCRIPTION
**Pull request by loicmathieu**
Class is always added to the projection fields as all Java classes have a getClass method.
We should avoid this, it is not realy a bug as MongoDB will ignore unknow fields but it's useless.

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]
Makes sense!

**Review by machi1990 — CHANGES_REQUESTED** [review]
Can you fix the formatting issue?

**Comment by loicmathieu** [comment]
@machi1990 sorry, fixed.

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
Thanks! Merged!

**Pull request merged**
