### PR TITLE
Adding LANG env to docker build

### PR DESCRIPTION
**Pull request by gastaldi**
This resolves errors while showing the ASCII art banner

### CODE REVIEW

**Comment by geoand** [comment]
Works for me. But I'll let @dmlloyd have the final say

**Review by gsmet — CHANGES_REQUESTED** [review]
I'm -1 for this change, at least until we discuss it first on the mailing list.

**Comment by maxandersen** [comment]
Can't we just pass in the environment charset rather than hardcore it ?

That mean It runs as if you local native build ?

**Comment by maxandersen** [comment]
This doenst not just fix ASCII art banner. It makes charset predictable. 

@gsmet can you state what your concern is ? In what situation is using whatever default charset in our base builders better Than utf-8 or Users default Charset ?

**Comment by maxandersen** [comment]
If we wait we'll not get feedback if it actually breaks and users can still set it where needed.

**Comment by dmlloyd** [comment]
TBH I with @gsmet on this one.  We don't want to force the charset when the problem we're trying to solve is correct banner rendering, which might better be solved at a different layer.

**Comment by maxandersen** [comment]
the way I see it the banner revealed that our call through docker here are using rather custom/random encoding...

**Comment by geoand** [comment]
Given the fact that this only happens when the native image is built through docker, I agree with @maxandersen (although my knowledge of character encodings is very limited)

**Comment by dmlloyd** [comment]
How do we know that UTF-8 is the right charset?  What are the factors that determine the charset in use with Docker and how does that interplay with the JDK or the host OS?  At a minimum that level of analysis should be on the PR and/or commit.

**Comment by geoand** [comment]
That I can completely agree with - essentially if this PR fixes the issue we need to know why

**Comment by maxandersen** [comment]
The image we are talking about here is "quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java8", right?

when I run that guess what LANG is set to ? "en_US.UTF-8" ...

**Comment by maxandersen** [comment]
I really see this as our docker launch here relying on whatever LANG enabled in the graalvm build and thus explicitly setting it should be better.

**Comment by geoand** [comment]
Yeah, it would be great to know how the value ends up being what it is when we don't set anything.

**Comment by maxandersen** [comment]
so, after some trial and error we now know LANG and other env is not set at all by default and the default charset /lang is `en.US-ASCII`which I think we all can agree is *worse* than UTF-8....

**Comment by geoand** [comment]
Superseded by: #7662

**Pull request closed without merging**
