### PR TITLE
WebJars locator extension Dev UI support

### LINKED ISSUE #21273: Webjars: support DEV UI
### Description

Webjars are nice, but DEV UI support that would list the files would be nice, because it's not obvious what the URIs are, and they're not listed as static resources.

https://quarkus.io/guides/http-reference#webjar-locator-support

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by majlantalik**
Fixes #21273 

I added an interactive resource explorer for any included webjar for the Dev UI. It shows the resources as a tree providing links to any file found in the webjars' content.

image

This is my first contribution to Quarkus (or any OSS for that matter), so any feedback or help is highly appreciated!

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Hi @majlantalik. Thanks for this ! this is great ! I wonder if we should not add this to vertx-http and include mvnpm jars ?

**Comment by cescoffier** [comment]
Defintiely a great addition!

**Comment by phillip-kruger** [comment]
@majlantalik - are you keen to move this to vertx-http extension and add mvnpm jars ?

**Comment by majlantalik** [comment]
Thank you guys!

@phillip-kruger sure, I'd be happy to, although the vertx-http extension looks a lot more complicated.

Can I maybe ask you to do the vertx-http in a separate PR? I'm participating in Hacktoberfetst and I'm almost positive I won't be able to complete my 4 PRs if I get stuck on this one for the time being.

**Comment by phillip-kruger** [comment]
Ok, I'll merge this layer and follow up with a pr in vertx-http

**Comment by FroMage** [comment]
This is great!

@phillip-kruger let's merge this and refactor later for mvnpm, no?

**Review by FroMage — APPROVED** [review]

**Comment by phillip-kruger** [comment]
I'll look at this in the morning

**Comment by phillip-kruger** [comment]
Thanks @majlantalik for your contribution !

**Pull request merged**
