### PR TITLE
Bump quarkiverse-parent to 16 and maven-compiler-plugin to 3.13.0

### PR DESCRIPTION
**Pull request by gastaldi**
- Bumps the `quarkiverse-parent` to `16`
- Bumps the `maven-compiler-plugin` to `3.13.0`

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
I force pushed to fix the snapshot issue.

**Comment by gastaldi** [comment]
Thank you @gsmet

**Comment by gsmet** [comment]
@mkouba these websockets-next tests look unstable.

**Review by gsmet — APPROVED** [review]

**Comment by mkouba** [comment]
> @mkouba these websockets-next tests look unstable.

@gsmet I'll take a look. The `BroadcastOnOpenTest` failures on Windows are not new but I cannot say I know why :shrug:. The `ClientEndpointTest` is got added recently, so that can be a problem in the test.

**Comment by gsmet** [comment]
@mkouba for the first one, if we don't think we can find a solution soon, maybe let's disable it on Windows?

**Pull request merged**
