### PR TITLE
WIP: Cache (Caffeine): Allow setting refreshAfterWrite property

### PR DESCRIPTION
**Pull request by gilvansfilho**
Allow setting refreshAfterWrite property on caffeine - Issue #25921

I am not confident about [CacheLoader](https://github.com/ben-manes/caffeine/wiki/Population#loading) required when using refreshAfterWrite property. Also did not found good information about this.

So If someone could take a look, will be great.

### CODE REVIEW

**Comment by ben-manes** [comment]
The cache loader is required (see [javadoc](https://github.com/ben-manes/caffeine/blob/10b7b9f4c4a517d4e66fe268bbf95d027b1676d3/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java#L767-L787) because on a read, the cache may need to reload the value. The reload method is `(key, oldValue) -> newValue`, which is a different signature than the load's `key -> value` (but delegates by defaults). As not all methods that read specify a loading function, it has to be attached up front. It is also more confusing if the supplied functions vary causing the reload result to be inconsistent (though, likewise, the load would be). 

In your snippet, you return `null` which indicates that the entry should be removed (e.g. was deleted in the system of record). That does not seem to be what you would want.

Since Quarkus' cache read apis always require a loading function, you could stash it into a thread local for use by the loader. Unfortunately that would cause brittleness by disallowing non-loading lookup, e.g. `getIfPresent(key)`.

Generalizing features into a vendor agnostic api is daunting. If you want to do simple things then its fine, but more advanced functionality will likely require using the native api. As refreshing is surprisingly complex, I think using Caffeine's apis directly is likely the best option.

**Comment by gwenneg** [comment]
@ben-manes Could you please elaborate on the `ThreadLocal` idea?

Entries from a single Quarkus cache can be loaded from multiple classes/methods/threads. A single cache entry can even be loaded from one method at first and then replaced from another method that shares the same cache and same key. I don't see how the Caffeine refresh requirement (attaching the loading function up front) could fit into `CaffeineCacheImpl`.

**Comment by gwenneg** [comment]
Also, since this extension always requires a loading function when a cache entry is retrieved, using `expire-after-write` _almost_ produces the same outcome than a `refresh-after-write`. Introducing brittleness for the sake of having a real `refresh-after-write` doesn't sound like the best thing to do to me.

**Comment by ben-manes** [comment]
@gwenneg I think my idea was a hack to coerce something to work but would be brittle. It might work, but also does not work cleanly with `getIfPresent`. More of it could be done if you had no other choice, but not something that you'd want to maintain.

```java
ThreadLocal<Function<K, V>> loader;

Caffeine.newBuilder().build(new CacheLoader<K, V>() {
  public V load(K key) {
    throw new UnsupportedOperationException();
  }
  public CompletableFuture<V> asyncReload(K key, V oldValue, Executor e) {
    var f = loader.get();
    return (f == null) ? oldValue : CompletableFuture.supplyAsync(() -> f.apply(key), e);
});

loader.set(...)
try {
  return cache.get(key, loader);
} finally {
  loader.set(null);
}
```

**Comment by ben-manes** [comment]
Not sure if this helps, but there was a thread on a hack for Spring that got access to the caller's method via the `CacheOperationInvocationContext`. But that API does not expect manual usage, so `getIfPresent` would be broken. That could be hacked around if we supported variable refresh, but I've only drawn an api sketch and backlogged the implementation work.

https://github.com/ben-manes/caffeine/issues/311#issuecomment-478552898

**Comment by gwenneg** [comment]
I'm not in favor of introducing brittleness and decreasing the maintainability of the extension for the sake of supporting cache entries refreshing.

**Pull request closed without merging**
