### PR TITLE
Add Groovy language basic support

### LINKED ISSUE #2720: Groovy language support
It's would be nice to have Groovy supported. It has smooth Java integration, relatively short learning curve and support for unit testing.

Version 3 is being worked on to support the new features that have emerged since Java 9, with support for lambda expressions and JPMS, for instance.

Also, Vert.x has Groovy support and it would be consistent that Quarkus also supports it. Groovy has an average of 12 million downloads per month, so it is considered a popular and growing language.

### PR DESCRIPTION
**Pull request by essobedo**
fixes #2720

## Motivation

The Groovy language is widely used so it would be nice to propose its support in Quarkus out-of-the-box.

## Modifications:

* Add a groovy extension with native and dev mode support
* Add `resteasy-reactive-groovy` to the native tests in HTTP category
* Add groovy to the target language
* Write codestart in Groovy
* Add `codestart` to the metadata of the extension `reactive-routes` to ensure that the sources are added when creating the project
* Update the `codestart` metadata to add Groovy to all extensions for which Groovy version has been proposed

## Result

Even if those changes don't cover hibernate-orm and hibernate-orm-reactive, Groovy can be used to write a Quarkus application

### CODE REVIEW

**Comment by essobedo** [comment]
Follow-up PRs will be proposed to add ORM support and some doc

**Comment by maxandersen** [comment]
super interesting!

I think it would be better having this more like an external extension similar to scala3 support like https://github.com/quarkiverse/quarkus-scala3. We are trying to avoid grow quarkus core repo size and dependency set.

**Comment by maxandersen** [comment]
a quick scan shows that codestarts might be the place we have a limit on language extendability but we should be able to fix or live with that in some way for this. wdyt?

**Comment by gsmet** [comment]
As for Scala, it was incorporated before we decided to not include everything in core (the decision was mostly driven by the size of the build but also to offer the ability to have different release cycles). This is Scala 2 though, Scala 3 is hosted in the Quarkiverse. It was my intention to move Scala 2 out of the tree but it has not been moved outside the tree because of the codestarts limitations.

To be honest, I’m a bit reluctant to incorporate languages in the tree for which we have no experts in the current core maintainers. 

I agree we should work on alleviating the codestarts limitation as we need to be able to develop language support outside of the core tree. 

/cc @ia3andy

**Comment by ia3andy** [comment]
I need to give it a try but now that we have Quarkiverse codestart support, this shouldn't be a limitation anymore!

**Comment by maxandersen** [comment]
@essobedo sorry, if any misunderstanding here. I/we *are* interested in enabling Groovy but we don't want to repeat the mistake of including i.e. Scala directly in core as it actually degraded very quickly - that's why when someone showed up with Scala 3 support we placed it in Quarkiverse.

If we could magically do same for Kotlin I would do that too; but for now we have it in core as it works.

Groovy I would love to see support for and the best way of doing that is by enabling those who are experts and interested in it to release and iterate independently from the core repository.

Being in Quarkiverse is NOT a discouragement; its about enabling faster movement.

**Comment by gsmet** [comment]
IIRC it wasn’t possible to define additional languages. 

But I might have missed something or it might have been fixed already.

**Comment by maxandersen** [comment]
> f so, it is unclear to me why to propose Kotlin and Scala in Quarkus core knowing that they are more or less as popular as Groovy. Do you consider Groovy as less important?

just to answer this specifically - these two are in there as that was contributed in very early days of Quarkus. Now 3+ years later we've grown and learned and trying to setup core to be language agnostic rather than tie core to specific versions of the languages/libraries.

At the moment we don't have contributors doing any Groovy. If we do it in core it will take much longer; hence the  suggestion to move majority of this into quarkiverse extension as it lets those doing Groovy contribute and grow this much faster.

**Comment by aaloise** [comment]
Groovy on Quarkus is very interesting. I hope this union works. I myself opened issue #2720 back in 2019 with the expectation of seeing this integration.

I ask @essobedo not to be discouraged. The considerations made so far are just minor adjustments to be made. Your contribution was very valuable.

I'd rather see Groovy on Quarkus as an extension than not have it at all.

**Comment by essobedo** [comment]
Ok, I can move it to Quarkiverse, let me know when the repository will be ready. I will then rewrite the PR accordingly as soon as possible. And I will do my best in terms of commitments behind a Quarkiverse extension.

**Comment by gastaldi** [comment]
The https://github.com/quarkiverse/quarkus-groovy repository is now created. You should have received an invitation email to join the Quarkiverse organization, @essobedo.

Here are the next steps (eg. how to list your extension in code.quarkus.io, docs, etc): https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created

**Pull request closed without merging**
