### PR TITLE
Update Kotlin to 1.6.20

### PR DESCRIPTION
**Pull request by famod**
~~Draft mode until 1.6.20 is final.~~

I haven't done any specific tests myself, I only ran CI in my fork and locally I ran `integration-tests/gradle` with Java 11 and 18 EA.

/cc @evanchooly

### CODE REVIEW

**Comment by gsmet** [comment]
Rebased to fix a conflict.

**Review by gsmet — APPROVED** [review]

**Comment by MartinX3** [comment]
Could it get backported to 2.8?

**Comment by gsmet** [comment]
@MartinX3 I don't know. Is it a bugfix only release on the Kotlin side or are there any potential breaking change?

**Comment by MartinX3** [comment]
It also adds new language features or puts them out of the experimental state if I read it correctly
https://blog.jetbrains.com/kotlin/2022/04/kotlin-1-6-20-released/

So i think it is not a bugfix only release

**Comment by gsmet** [comment]
I don't use Kotlin so I'm not really the right person to take an educated decision here. @evanchooly @geoand any opinion?

**Comment by geoand** [comment]
It seems to be bigger than usual, so I'd personally be in favor of not backporting

**Pull request merged**
