### PR TITLE
Add support for AppCDS generation in Jib built container images

### LINKED ISSUE #14607: Integrate AppCDS generation into Jib container image generation
**Description**
AppCDS generation currently is not baked into container image generation with Jib.
We should add this feature because creating AppCDS for use in a container image is very tricky due to the need to have the JVM version and classpaths match perfectly.

**Implementation ideas**
We can use the same trick that we use when `quarkus.native.container-build=true` is active - that is run the actual AppCDS generation with the JVM specified in the base image. That will result in an AppCDS file that can be used by the container image.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #14607

### CODE REVIEW

**Comment by geoand** [comment]
CI is failing on the new test I added - which is weird because it passed locally. 
I'll look into it

**Comment by geoand** [comment]
@stuartwdouglas PR should be ready now

**Comment by geoand** [comment]
This will also require some documentation - probably a blog post on `quarkus.io`

**Comment by geoand** [comment]
@stuartwdouglas can you take a look and let me know what you think?

Thanks

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
LGTM

**Pull request merged**
