### PR TITLE
Micrometer: rename vertx options to http-server

### LINKED ISSUE #14745: Micrometer: Rename vertx properties to http server binding.
**Description**
Following this guide: https://quarkus.io/guides/micrometer, there are some vertx related properties like:
- quarkus.micrometer.binder.vertx.enabled
- quarkus.micrometer.binder.vertx.match-patterns
- quarkus.micrometer.binder.vertx.ignore-patterns

After speaking with @ebullient , it seems that this binding matches with the HTTP server metrics rather than vertx. Therefore, we should rename this binding in order to avoid users misunderstandings with https://vertx.io/docs/vertx-micrometer-metrics/java/#_vert_x_pool_metrics.

### LINKED ISSUE #14887: MicroMeter extension: JSONExporter issue with "NaN" values
**Describe the bug**
The JSON-Exporter for the micrometer metrics throws a NumberFormatException when a Gauge that is based on weak reference returns "NaN".
According to https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing a Gauge's value can get garbage-collected if it's not using a strong-reference. This happened to me for the Gauge "system.cpu.usage" which leads the JSON-Exporter to serialize "NaN.
There is a check for NaN-values in `JsonExporter`: 
`https://github.com/quarkusio/quarkus/blob/95602076fa89d89e0db6c00709e07a0b9cc28530/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/registry/json/JsonExporter.java#L91`
Unfortunately that check does not work here as one line lower the Gauges' value is queried again resulting in a different value ('NaN').

**Expected behavior**
The JSON-Exporter should filter out `NaN`-double values.

**Actual behavior**
The JSON-Exporter tries to use a `NaN` value leading to a NumberFormatException.

**To Reproduce**
I did create a small repo with a test that fails: https://github.com/flobjective/Quarkus-Metrics-JSON-Nan

1) Run the test `GreetingResourceTest:prometheus_metrics_in_json_should_be_available` using `./mvnw test`

Alternative:

1) Run `./mvnw quarkus:dev`
2) Run curl from a shell `curl http://localhost:8080/q/metrics -H "Accept:application/json"`
3) Repeat the curl a few times (I only 1-2 runs locally)

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.micrometer.export.json.enabled=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 ```
 Darwin machinename 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
 ```
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
```
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - Quarkus version or git rev: `1.11.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
Maven home:  /Users/florianfritzsche/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #14745 
Resolves #14887

This is a better fit after the addition of similar options for http-client

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by ebullient** [comment]
@vsevel .. is the failing CI a known issue?

**Comment by ebullient** [comment]
hmm. native test showed something not right. Put a pin in this -- @kenfinnigan I'll let you know when to look again

**Comment by rsvoboda** [comment]
CI passed, ready for second review from @kenfinnigan?

**Comment by rsvoboda** [comment]
Added triage label, we would like to get this change into 1.11 branch

**Comment by ebullient** [comment]
Ken will be slow to review. Adding an additional test for match pattern (re #14813). This behavior is tested in unit tests, but a multi-parameter pattern in properties was not explicitly tested.

**Comment by gsmet** [comment]
If we want this in 1.11.2.Final, it needs to be merged today.

**Comment by ebullient** [comment]
> If we want this in 1.11.2.Final, it needs to be merged today.

I may need help w/ a review, in that case. Ken was out last week. I've changed things since the last time he looked, which is why I asked again. So if you care to have a gander, that would help. ;)

**Review by geoand — APPROVED** [review]
Thanks!

**Pull request merged**
