### PR TITLE
Upgrade to Hibernate ORM 5.5.6.Final

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by Sanne** [comment]
Build failed because of

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.hibernate:hibernate-core:jar:5.5.6.Final in google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/)
```

Weird, I could fetch it locally. I'll trigger the build again in a few hours.

**Comment by famod** [comment]
My company's Artifactory doesn't seem to have it yet. Will try again later.

**Comment by famod** [comment]
@Sanne Um...have you changed the versioning scheme? I can see (and download/use) `5.5.6` but not `5.5.6.Final`?

**Comment by famod** [comment]
The modelgen part is fixed for sure, but I cannot test 5.5.6 (without .Final) in my current project because we are using Blaze-Persistence and `com.blazebit.persistence.integration.hibernate.base.function.AbstractHibernateEntityManagerFactoryIntegrator` chokes on the missing version suffix.
/cc @beikov (but I suppose the missing suffix was a mishap during release...?)

**Comment by beikov** [comment]
@Sanne might be worth re-doing the release?

**Comment by Sanne** [comment]
@beikov yes I'll repeat the process. Sorry all :(

**Comment by Sanne** [comment]
The `5.5.6.Final` artifacts have been released correctly now, but it will take a little longer for Maven to synch.

**Comment by Sanne** [comment]
It's available, restarting CI....

**Comment by Sanne** [comment]
FWIW, the error:

```
Error:  Failed to execute goal io.fabric8:docker-maven-plugin:0.31.0:start (docker-start) on project quarkus-integration-test-hibernate-reactive-panache: I/O Error: Unable to pull 'postgres:13.1' : {"message":"Head https://registry-1.docker.io/v2/library/postgres/manifests/13.1: unknown: unable to scan account service account row from query: context deadline exceeded"} (Internal Server Error: 500) -> [Help 1]
```

I'm restarting it.

**Comment by famod** [comment]
Looking good in my project now! Hitting another problem SR Config though, but that's not related.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
