### PR TITLE
Remove the 'no sources dir' warning from DevMojo

### LINKED ISSUE #14402: dev mode: support suppressing warnign about non existing source directory
**Description**

Since version 1.3.0, [camel-k](https://github.com/apache/camel-k) has switched to Quarkus as default runtime. For troubleshooting purpose we have some pure java based examples which I'm now migrating to use `quarkus:dev` instead of the `exec-maven-plugin` and since in camel-k we basically do composition, we don't have any source in project and that leads to the following warning:

```
The project's sources directory does not exist /home/codespace/workspace/camel-k-runtime-example-kamelets/src/main/java
```

As it is perfectly fine for a camel-k project to be "source free", it would be nice to add an option to silence such warning

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #14402

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Cool, thanks!

**Comment by gsmet** [comment]
Ah ah, believe it or not, we had a test for it;
```
2021-01-21 13:56:20,579 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-01-21 13:56:20,579 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, servlet, undertow-websockets]
">
to contain:
 <"The project's sources directory does not exist"> 
```

Our young selves were very thorough :).

**Comment by geoand** [comment]
> Ah ah, believe it or not, we had a test for it;
> 
> ```
> 2021-01-21 13:56:20,579 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
> 2021-01-21 13:56:20,579 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, servlet, undertow-websockets]
> ">
> to contain:
>  <"The project's sources directory does not exist"> 
> ```
> 
> Our young selves were very thorough :).

Hahaha! There is a thing as too much testing :P

**Comment by famod** [comment]
And there goes all the work I've put into the multi module condition. 😜

**Comment by geoand** [comment]
> And there goes all the work I've put into the multi module condition.

May it RIP :)

**Pull request merged**
