### PR TITLE
Upgrade to SmallRye GraphQL 1.7.0 (graphql-java 19.0)

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR upgrades to [SmallRye GraphQL 1.7.0](https://github.com/smallrye/smallrye-graphql/releases/tag/1.7.0) that contains a new version of [graphql-java (v19.0)](https://github.com/graphql-java/graphql-java/releases/tag/v19.0). The validation messages now supports i18n and the default message changed slightly (hence the overrides in the MicroProfile GraphQL TCK)

This PR also adds some new configuration options:

- quarkus.smallrye-graphql.instrumentation-query-complexity
- quarkus.smallrye-graphql.instrumentation-query-depth
- quarkus.smallrye-graphql.parser-capture-ignored-chars
- quarkus.smallrye-graphql.parser-capture-line-comments
- quarkus.smallrye-graphql.parser-capture-source-location
- quarkus.smallrye-graphql.parser-max-tokens
- quarkus.smallrye-graphql.parser-max-whitespace-tokens

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
You know that already but just so that it doesn't get merged too soon: we will need a Jakarta version and an update to the rewrite.yml file.
Thanks.

**Comment by phillip-kruger** [comment]
That is why this is still a draft. Busy with the 2.0.0.RC release

**Review by jmartisk — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Failures look related.

**Comment by phillip-kruger** [comment]
@gsmet Yes native failed due to new i18n resource from graphql-java. Fixed now. Should be ok, lets see what CI does now.

**Comment by phillip-kruger** [comment]
Thanks @gsmet !

**Pull request merged**
