### PR TITLE
Upgrade to Mutiny 1.1.1 and Mutiny Vert.x bindings 2.14.0

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
LGTM

**Review by geoand — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
The failure seems suspicious... 

cc @michalszynkiewicz

**Comment by michalszynkiewicz** [comment]
looking

**Review by michalszynkiewicz — CHANGES_REQUESTED** [review]
The test failures are real, I'm investigating them

**Review by michalszynkiewicz — APPROVED** [review]
the failures are not caused by this PR

**Comment by geoand** [comment]
What's wrong? Is the build currently broken?

**Review by cescoffier — APPROVED** [review]

**Pull request closed without merging**
