### PR TITLE
Add guard task to ensure log messages are dropped when the process isn't a Quarkus application

### LINKED ISSUE #14295: java.lang.OutOfMemoryError: Java heap space - Quarkus 1.10.5.Final
**Describe the bug**
Difference in memory consumption between version 1.8.3 and 1.10.* 
It can result in an OutOfMemoryError on a simple unit test using the ApachDS library.

**Expected behavior**
Use of 300 MB of memory instead of 2 GB +
Build succes with the unit test. 

**Actual behavior**
```java
Running org.nch.GreetingResourceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 42.689 sec <<< FAILURE!
org.nch.GreetingResourceTest  Time elapsed: 42.689 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.apache.directory.api.ldap.model.schema.registries.Registries.dumpUsing(Registries.java:1954)
	at org.apache.directory.api.ldap.model.schema.registries.Registries.addReference(Registries.java:2031)
	at org.apache.directory.api.ldap.model.schema.registries.helper.ObjectClassHelper.addToRegistries(ObjectClassHelper.java:81)
	at org.apache.directory.api.ldap.model.schema.registries.Registries.buildReference(Registries.java:690)
	at org.apache.directory.api.ldap.model.schema.registries.Registries.buildObjectClassReferences(Registries.java:815)
	at org.apache.directory.api.ldap.model.schema.registries.Registries.buildReferences(Registries.java:875)
	at org.apache.directory.api.ldap.model.schema.registries.Registries.clone(Registries.java:2578)
	at org.apache.directory.api.ldap.schemamanager.impl.DefaultSchemaManager.cloneRegistries(DefaultSchemaManager.java:200)
	at org.apache.directory.api.ldap.schemamanager.impl.DefaultSchemaManager.load(DefaultSchemaManager.java:589)
	at org.apache.directory.server.core.api.schema.registries.synchronizers.SchemaSynchronizer.add(SchemaSynchronizer.java:215)
	at org.apache.directory.server.core.api.schema.registries.synchronizers.RegistrySynchronizerAdaptor.add(RegistrySynchronizerAdaptor.java:188)
	at org.apache.directory.server.core.api.schema.SchemaPartition.add(SchemaPartition.java:266)
	at org.apache.directory.server.core.shared.partition.DefaultPartitionNexus.add(DefaultPartitionNexus.java:385)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor$1.add(BaseInterceptor.java:158)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:412)
	at org.apache.directory.server.core.journal.JournalInterceptor.add(JournalInterceptor.java:139)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:412)
	at org.apache.directory.server.core.changelog.ChangeLogInterceptor.add(ChangeLogInterceptor.java:113)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:412)
	at org.apache.directory.server.core.trigger.TriggerInterceptor.add(TriggerInterceptor.java:300)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:412)
	at org.apache.directory.server.core.event.EventInterceptor.add(EventInterceptor.java:220)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:412)
	at org.apache.directory.server.core.subtree.SubentryInterceptor.add(SubentryInterceptor.java:1014)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:412)
	at org.apache.directory.server.core.collective.CollectiveAttributeInterceptor.add(CollectiveAttributeInterceptor.java:134)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:412)

Results :

Tests in error: 
  org.nch.GreetingResourceTest: Java heap space
```

**To Reproduce**

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5813489/code-with-quarkus.zip)

1. mvn clean install 

**Environment (please complete the following information):**
 - #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk version "1.8.0_232"
   OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~19.04.1-b09)
   OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
 - Quarkus version or git rev :  1.10.5.Final
 - Apache Maven 3.6.3 
   Maven home: /opt/apache-maven-3.6.3
   Java version: 1.8.0_232, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
   Default locale: fr_FR, platform encoding: UTF-8
   OS name: "linux", version: "5.4.0-26-generic", arch: "amd64", family: "unix"

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #14295

This solution really sucks but I couldn't come up with anything better that 

1) Had no penalty for a prod run
2) Worked properly for prod, dev and test mode

### CODE REVIEW

**Comment by geoand** [comment]
The JDK 11 test failure is completely unrelated:

```
Error:    ConnectionPoolsClosedTest.connectionsFromOtherThreadsGetClosed:35 COM01003: Internal error: Assertion failure: Expected boolean value to be false
[INFO] 
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
```

It looks like there is some kind of race condition in the test

**Comment by Sanne** [comment]
hum thanks yes I can see a possible race. I'll open a different issue:
 - https://github.com/quarkusio/quarkus/issues/14392

If this happens again while I haven't fixed it, feel free to disable the test.

**Review by dmlloyd — CHANGES_REQUESTED** [review]
Apologies, but: I think using a timer is a monumentally bad idea.  Let's try to find some other approach - even examining the stack trace would be a better idea IMO.

**Review by dmlloyd — CHANGES_REQUESTED** [review]
Apologies, but: I think using a timer is a monumentally bad idea.  Let's try to find some other approach - even examining the stack trace would be a better idea IMO.

**Comment by geoand** [comment]
I absolutely agree it's bad :).

If you think the stacktrace approach is better, then I'm all for it. I thought of it myself, but I didn't go through with it because I thought the performance penalty would be high... 
Are you sure you want me to go ahead with it?

**Comment by dmlloyd** [comment]
> I absolutely agree it's bad :).
> 
> If you think the stacktrace approach is better, then I'm all for it. I thought of it myself, but I didn't go through with it because I thought the performance penalty would be high...
> Are you sure you want me to go ahead with it?

I don't think it would be terrible.  The main challenge is that the stack is not necessarily predictable; you'd have to do some experimentation to see.

**Comment by geoand** [comment]
> > I absolutely agree it's bad :).
> > If you think the stacktrace approach is better, then I'm all for it. I thought of it myself, but I didn't go through with it because I thought the performance penalty would be high...
> > Are you sure you want me to go ahead with it?
> 
> I don't think it would be terrible. The main challenge is that the stack is not necessarily predictable; you'd have to do some experimentation to see.

OK, I'll check

**Comment by geoand** [comment]
Another thing about the stack based approach, is that I am not sure that we'll be able to tell a Quarkus application is being run by examining the stack.

I am thinking about the case of tests where maven surefire launches a test jar and our logging is started very very early. In that case I think even when `getHandlersOf` there is a good chance that Quarkus bootstrapping will not have been started yet.

**Comment by geoand** [comment]
I also wanted to note that generating an `InitialConfigurator` won't work because again that class is engaged before Quarkus is even bootstraped in the case of tests

**Comment by Sanne** [comment]
I've probably missed something, but why do we worry about "non-Quarkus applications" at all?

**Comment by geoand** [comment]
> I've probably missed something, but why do we worry about "non-Quarkus applications" at all?

The problem is that merely the presence of Quarkus on the test classpath, leads to non Quarkus tests causing OOM errors because log messages get queued and never released

**Comment by stuartwdouglas** [comment]
I don't know if there is any good automatic solution to this. Can't we just tell the user to specify -Djava.util.logging.manager=java.util.logging.LogManager and be done with it?

**Comment by geoand** [comment]
Yeah... The complexity of an acceptable solution outweighs the usefulness of addressing the issue.

**Pull request closed without merging**
