### PR TITLE
Draft support for AWT image resizing

### LINKED ISSUE #19789: AWT Graphics does not seem to work in native image
### Describe the bug

So basically I'm trying to resize png picture in quarkus app and I'm aware that there were several problems with AWT library. I tried following [this](https://github.com/graalvm/mandrel/issues/180#issuecomment-734873511) comment but so far I cannot make this thing to work. The main culprit in stack trace seems to be this
```
Caused by: java.lang.UnsupportedOperationException: Not implemented yet for GraalVM native images
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:15)
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
        at com.test.ImageResource.resizeImage(ImageResource.java:63)
        at com.test.ImageResource.save(ImageResource.java:25)
```

I did create config files using agent like mentioned in that thread (you can check them [here](https://github.com/habimt/rest-graphics/tree/master/src/main/resources/META-INF/native-image)) but I'm wondering if perhaps there's something wrong with them.

Config files were crated the following way:
```
$GRAALVM_HOME/bin/java -agentlib:native-image-agent=config-output-dir=native-image-config -Djava.awt.headless=true -jar target/quarkus-app/quarkus-run.jar
```

### How to Reproduce?
clone this https://github.com/habimt/rest-graphics and run `./mvnw verify -Pnative`

### Output of `java -version`

OpenJDK Runtime Environment (build 11.0.12+7)

### GraalVM version (if different from Java)

GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08), also tried on 21.2.0.0-Final Mandrel Distribution (Java Version 11.0.12+7)

### Quarkus version or git rev
2.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1

### PR DESCRIPTION
**Pull request by galderz**
Draft PR to fix #19789.

To enable AWT image resizing, it does a couple of things:

1. It instructs AWT and graphics related `java`, `javax`, and `sun` packages to be runtime initialized. The rest of the code is build time initialized as usual.
2. It registers the necessary reflection and JNI items for things to work. These are derived from running the Java version of [this Quarkus AWT image resize example](https://github.com/galderz/mendrugo/tree/main/quarkus-awt) with `-agentlib:native-image-agent=config-output-dir=META-INF/native-image`. I wonder if, rather than having `Java2DProcessor` in `core/deployment`, it would make more sense to have this as an extension? E.g. an `extension/awt` where we can put all this things and people optionally depend on it.

### CODE REVIEW

**Comment by galderz** [comment]
The configuration files generated by `native-image-agent` can be found [here](https://gist.github.com/galderz/49567f2817a9821745be6140bd050234) for comparison.

**Comment by gastaldi** [comment]
+1, I think it makes total sense to introduce a AWT extension also

**Comment by galderz** [comment]
I'm looking at the test failures.

**Comment by galderz** [comment]
Any ideas on how to deal with situations like this going forward?

```
sun.awt.image.ByteBandedRaster the class was requested to be initialized at run time (from the command line with 'sun.awt'). org.apache.pdfbox.pdmodel.PDDocument caused initialization of this class with the following trace:
	at sun.awt.image.ByteBandedRaster.<clinit>(ByteBandedRaster.java)
	at java.awt.image.Raster.createBandedRaster(Raster.java:730)
	at java.awt.image.Raster.createBandedRaster(Raster.java:417)
	at java.awt.image.Raster.createBandedRaster(Raster.java:324)
	at org.apache.pdfbox.pdmodel.PDDocument.<clinit>(PDDocument.java:107)
```

The issue is that if we push `java.awt` and related to be runtime init, any static initializers that use those need to be as well. So, seems to me there has to be some kind of way for extensions to say: please add this package(s) to be runtime initialized. How would that be achieved? @sanne @geoand? For this experiment, I'm hacking `NativeImageBuildStep` to add a runtime init for `org.apache.pdfbox.pdmodel` package and see how far I get...

**Comment by galderz** [comment]
> Any ideas on how to deal with situations like this going forward?
> 
> ```
> sun.awt.image.ByteBandedRaster the class was requested to be initialized at run time (from the command line with 'sun.awt'). org.apache.pdfbox.pdmodel.PDDocument caused initialization of this class with the following trace:
> 	at sun.awt.image.ByteBandedRaster.<clinit>(ByteBandedRaster.java)
> 	at java.awt.image.Raster.createBandedRaster(Raster.java:730)
> 	at java.awt.image.Raster.createBandedRaster(Raster.java:417)
> 	at java.awt.image.Raster.createBandedRaster(Raster.java:324)
> 	at org.apache.pdfbox.pdmodel.PDDocument.<clinit>(PDDocument.java:107)
> ```
> 
> The issue is that if we push `java.awt` and related to be runtime init, any static initializers that use those need to be as well. So, seems to me there has to be some kind of way for extensions to say: please add this package(s) to be runtime initialized. How would that be achieved? @Sanne @geoand? For this experiment, I'm hacking `NativeImageBuildStep` to add a runtime init for `org.apache.pdfbox.pdmodel` package and see how far I get...

It could be that, rather than using the `----initialize-at-run-time` param, maybe it's easier for extensions to extend this if done via the programmatic API, akin to what @geoand did in https://github.com/quarkusio/quarkus/commit/a85c687d6d6f8bb626444464a0558a2dd151e5f1#diff-bbea232d6b9141ad313658b2587f9ec7e23d90c93cd79994dd14086a769d52d0?

**Comment by Sanne** [comment]
hi @galderz ! That would be `RuntimeInitializedClassBuildItem` 

e.g. see 
https://github.com/quarkusio/quarkus/blob/5fab70f27a5380ec85db3da373930445634d75a4/extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java#L63-L67

**Comment by geoand** [comment]
Unfortunately emitting `RuntimeInitializedClassBuildItem` won't work properly for packages. If we really do want to add that kind of support for packages, we'll need a new build item.

**Comment by galderz** [comment]
@geoand Could you work on that bit in parallel? I've just verified that with this, the Tika tests pass:

```
nativeImageArgs
    .add("--initialize-at-run-time=java.awt,javax.imageio,sun.awt,sun.java2d,sun.font,com.sun.imageio,org.apache.pdfbox,org.apache.poi.hssf.util,org.apache.poi.ss.format");
```

I just added `org.apache.pdfbox,org.apache.poi.hssf.util,org.apache.poi.ss.format` to the Java AWT/Graphics runtime init packages. As mentioned above, the `extensions/awt` would take care of using this new construct too. I'll take care of `extensions/awt` when CI is happy and the runtime init package item is available :)

**Comment by Sanne** [comment]
I don't like the idea of offering an approach based on packages.

Couldn't we list the individual classes?

1. for AWT this ismost likely a too wide net, I hope you can identify which ones really need it.
2. we should encourage other extension writers to also be very selective about this

**Comment by geoand** [comment]
> @geoand Could you work on that bit in parallel? I've just verified that with this, the Tika tests pass:

The current build item for classes results in `org.graalvm.nativeimage.hosted.RuntimeClassInitialization#initializeAtRunTime` being called, with the argument being classes.
The new build item would call the method that expects strings with the expectation that those strings are valid packages.

**Comment by Sanne** [comment]
BTW @galderz : when it's a static well known list such as in this case, rather than relying on the build items which will dynamically generate an AutomaticFeature during the Quarkus build, you might as well just create an AutomaticFeature ... KISS and it would allow you to use packages - if you really must :)

**Comment by Sanne** [comment]
e.g. https://github.com/hibernate/hibernate-orm/blob/7d37e9f8784040fa91330a94628787bc36eb26c1/hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/GraalVMStaticAutofeature.java#L38

**Comment by geoand** [comment]
> I don't like the idea of offering an approach based on packages.
> 
> Couldn't we list the individual classes?

I completelt agree - we should avoid doing the packages thing if so possible.

**Comment by galderz** [comment]
I'm not going to track individual classes. My experiment will focus on packages. Feel free to further tune it for packages.

**Comment by galderz** [comment]
I've pushed a couple of commits to fix the `main` and `tika` tests.

Are the gradle native tests flaky? It seems to complain that `[total]` was not printed in the output... No idea, but I was unable to replicate locally. [Gradle IT dependencies look outdated](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Gradle.20IT.20dependencies.20look.20outdated.3F).

The native failures for hibernate validator on Windows don't know either. Let's see if they're still present after the update.

**Comment by geoand** [comment]
Some of the tests are flaky indeed :(

**Comment by maxandersen** [comment]
this should be in a .awt/.java2d extension rather than in quarkus core should it not? then we can also mark it experimental :)

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/20239

**Pull request closed without merging**
