### PR TITLE
Automatically add @Produces to methods annotated with scope or qualifier

### LINKED ISSUE #4831: HealthChecks and CDI Produces
**Description**

Hi I have developed a Health Check using CDI so the code looks like:

```
@ApplicationScoped
public class HealthChecks {
    @Readiness
    @Produces
    public HealthCheck healthy() {
        return HealthStatus.up("name");
    }
}
```
I have read in this document https://github.com/eclipse/microprofile-health/blob/51c0421ee9ab68742126e98d52ff20542273d2fe/spec/src/main/asciidoc/java-api.adoc that  you can define health checks using CDI producers. 

I don't know exactly if this is mandatory or not regarding the MicroProfile Health Checks spec to have to use @Produces or not in case of Health Checks and CDI, but maybe we could skip this annotation as we are skipping for `@Inject`.

**Implementation ideas**

I think that skipping the `@Produces` annotation should only affect in case of HealthCheck is the return type.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #4831

### CODE REVIEW

**Review by geoand — APPROVED** [review]
I really like anything that reduces boilerplate, so this is +1 from me!

**Review by manovotn — COMMENTED** [review]
@mkouba looks good, I am just thinking - could you use stereotype to define a scope for producer method?

**Comment by mkouba** [comment]
@manovotn Another good point!

**Review by manovotn — APPROVED** [review]

**Comment by geoand** [comment]
@mkouba mind force pushing the PR? I would like to have CI run properly (some infrastructure issue seems to have prevented the JDK tests from running).

**Pull request merged**
