### PR TITLE
Added a method to walk a subtree of a given PathTree

### PR DESCRIPTION
**Pull request by aloubyansky**
This PR also adds a convenient method `PathTree.walkIfContains(relativePath, visitor)` for walking over a subtree of a given `PathTree`. It's also a more efficient alternative to the current approach of using `FilteredPathTree`.

This PR also removes never used `CachedPathTree` which wasn't a complete implementation.

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky I wonder if the failure is related given I think Qute is now using this infra?

**Review by gsmet — CHANGES_REQUESTED** [review]
@aloubyansky I wonder if the failure is related given I think Qute is now using this infra?

**Comment by gsmet** [comment]
@aloubyansky I think we still have a problem on Windows here.

**Review by gsmet — CHANGES_REQUESTED** [review]
There is a log file in the PR: `[extensions/qute/deployment/log](https://github.com/quarkusio/quarkus/pull/40415/files#diff-40a826f6c73b87b94607d079015516f18ae0028a85b93068ff025c1125bea062)`. It needs to removed.

**Comment by aloubyansky** [comment]
@gsmet @mkouba this one's ready for review.

This may raise a question why not always perform case-sensitive path checks. We rely on pretty much `Files.exists(Path.resolve(path))` everywhere else.
What we do in case of Windows here has a certain cost, since we haven't had an issue everywhere else I thought of keeping it the way it is for now but added a method to PathTreeUtils to perform this kind of check where necessary.
If run into these issues in the future in other areas, we could reconsider the default check.

**Review by gsmet — APPROVED** [review]

**Comment by aloubyansky** [comment]
@mkouba does it look ok to you?

**Review by mkouba — APPROVED** [review]
Looks good!

**Pull request merged**
