### PR TITLE
Fast Jar Improvements

### PR DESCRIPTION
**Pull request by stuartwdouglas**
- Fix output dir bug
- Add ability to include user provided code on re-augmentation

### CODE REVIEW

**Comment by geoand** [comment]
`HttpRemoteDevClient` is failing on Windows which looks suspicious

**Comment by stuartwdouglas** [comment]
@pedroigor this looks related to your change so the output dir

**Comment by pedroigor** [comment]
@stuartwdouglas It seems to work fine for me. I'm able to load and process any custom code from the user providers dir when re-augmenting the application. The issue with the ORM extension too, so the classloader is able now to load additional classes.

I've only a few comments:

* Why not accept a dir outside the output directory? Would it be possible to allow setting a value to `user-providers-directory=../providers`? See https://github.com/quarkusio/quarkus/blob/61ab24825a669352f3527a2ad8844aa76eb8f7b0/independent-projects/bootstrap/runner/src/main/java/io/quarkus/bootstrap/runner/SerializedApplication.java#L232. By removing that check I don't see any negative impact.

* I was wondering whether or not it makes sense to build an extension that is capable of loading custom code from other sources than the filesystem. For instance, network, maven repo, etc. That would allow us to dynamically re-augment the application based on updates to custom code. Not sure if that makes sense because when using containers you probably want to go over the entire build process.

**Comment by pedroigor** [comment]
@stuartwdouglas The failing test works for me on Windows, using JDK 11. I did a rebase though.

**Comment by gsmet** [comment]
I rebased that one to fix an import conflict.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
