### PR TITLE
Allow fields with "and" or "or" in Spring Data JPA repositories

### LINKED ISSUE #10100: Spring Data JPA - Method name parsing fails when fields start with "and" or "or"
Repositories method name parsing for does not handle fields starting with "and" or "or" and split by operators blindly.

With this repository: 
```java
public interface ProjectRepository extends Repository<Project, Long> {
    List<Project> findAllByOrganization(String organization);
}
```

Exception is thrown:
```
Caused by: io.quarkus.builder.BuildException:
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.spring.data.deployment.SpringDataJPAProcessor#build threw an exception: io.quarkus.spring.data.deployment.UnableToParseMethodException: Entity org.acme.Project does not contain a field named: ganization. Offending method is findAllByOrganization
	at io.quarkus.spring.data.deployment.MethodNameParser.parse(MethodNameParser.java:210)
```

Simple project to reproduce it: 
```
git clone git@github.com:yall/quarkus-spring-data-parsing-bug.git
cd quarkus-spring-data-parsing-bug && ./mvnw test
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #10100

### CODE REVIEW

**Comment by geoand** [comment]
@gsmet hopefully a really quick and easy one to review before you get some rest :)

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
Thanks @gastaldi

**Comment by yall** [comment]
Thanks @geoand, that was fast. One might run into the same issue with some weird field names like `phoneOrEmail`, but naming things with logic operators and using parsed methods is playing with fire :).
Other thought: What about skipping the parsing if the method is annotated with a `@Query?

**Comment by geoand** [comment]
@yall yeah, it can get tricky :)

As for the use of `@Query`, we already do skip parsing the name if the annotation is present IIRC. If not, then it's a bug and I would definitely be interested in seeing a reproducer :)

**Comment by yall** [comment]
@geoand you're right, `@Query` makes the parsing being skipped. I've had a false memory of an annotated method when i ran into the bug 🤦‍♂️.
Thanks again for the fix!

**Comment by geoand** [comment]
Thank you for reporting!

**Pull request merged**
