### PR TITLE
Add double quotes around java executable

### LINKED ISSUE #11550: quarkus-grpc-protoc-plugin windows script fails with java.exe in Program Files
**Describe the bug**
protoc compilation fails with "'С:\Program' is not recognized as an internal or external command, operable program or batch file."

**Expected behavior**
protoc compilation successfully runs

**Actual behavior**
protoc compilation fails with "'С:\Program' is not recognized as an internal or external command, operable program or batch file."

**To Reproduce**
1. Have java in C:\Program Files\Java
2. Use quarkus gradle plugin with quarkus-grpc dependency to compile some protoc files
3. It will fail with exception from https://github.com/quarkusio/quarkus/blob/1.7/extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java line 86 saying "Failed to generate Java classes from proto files:" which doesn't explain anything.
4. If you try to run generated command yourself you will get a real reason saying C:\Program is not a command.
5. Further investigation will show that GrpcCodeGen.java generates a cmd sript on line 207 which contains a java command -
`C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin\java.EXE -cp "C:\Users\blablabla"`
6. Adding double quotes around java command fixes the issue

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.7.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

Gradle 6.6

Build time:   2020-08-10 22:06:19 UTC
Revision:     d119144684a0c301aea027b79857815659e431b9

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.7 (AdoptOpenJDK 11.0.7+10)
OS:           Windows 10 10.0 amd64

Issue seems to be specific to quarkus 1.7.0.Final. At least changing version to 1.6.1.Final doesn't throw this exception, but it seems like it also doesn't try to compile proto files at all.

### PR DESCRIPTION
**Pull request by Shohou**
Fix #11550 adding double quotes

### CODE REVIEW

**Comment by jaikiran** [comment]
This looks fine to me. Although, I wonder if we should implement this change in `JavaBinFinder.findBin()` itself to quote the return path on Windows. But that's much wider change and I think can be done and tested in a separate PR.

**Review by jaikiran — APPROVED** [review]

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by Shohou** [comment]
All other usages put it as the first argument to arguments list and pass it to java.lang.ProcessBuilder which handles unquoted executable correctly.

**Comment by gsmet** [comment]
Merged, thanks!

**Comment by gsmet** [comment]
Ah ah, just saw you targeted 1.7, next time, please target master and I will backport it. Thanks!

**Comment by gsmet** [comment]
Pushed to master too.

**Pull request merged**
