### PR TITLE
Upgrade to Hibernate Reactive 1.0.0.Beta4

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Cool, thanks!

**Comment by gsmet** [comment]
@mkouba @radcortez the Windows build failed with this error:
```
Caused by: java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for io.quarkus.arc.test.config.ConfigMappingTest$Collections
	at io.smallrye.config.ConfigMappings.getConfigMapping(ConfigMappings.java:57)
	at io.smallrye.config.ConfigMappings.getConfigMapping(ConfigMappings.java:47)
	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:232)
	at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:17)
	at io.quarkus.arc.test.config.ConfigMappingTest_Collections_2bd928ae5c9c1fbdf3ffd5f20e38ca31d78769fe_Synthetic_Bean.create(ConfigMappingTest_Collections_2bd928ae5c9c1fbdf3ffd5f20e38ca31d78769fe_Synthetic_Bean.zig:121)
	at io.quarkus.arc.test.config.ConfigMappingTest_Collections_2bd928ae5c9c1fbdf3ffd5f20e38ca31d78769fe_Synthetic_Bean.get(ConfigMappingTest_Collections_2bd928ae5c9c1fbdf3ffd5f20e38ca31d78769fe_Synthetic_Bean.zig:152)
	at io.quarkus.arc.test.config.ConfigMappingTest_Collections_2bd928ae5c9c1fbdf3ffd5f20e38ca31d78769fe_Synthetic_Bean.get(ConfigMappingTest_Collections_2bd928ae5c9c1fbdf3ffd5f20e38ca31d78769fe_Synthetic_Bean.zig:175)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
	at io.quarkus.arc.test.config.ConfigMappingTest_Bean.create(ConfigMappingTest_Bean.zig:654)
	... 51 more
```
could you have a look?

**Comment by radcortez** [comment]
Sure, I'll have a look.

**Comment by radcortez** [comment]
@gsmet I've tried to reproduce the error in a VM with Windows with no luck.

Also, I don't see how the hibernate update may break this test. It happens way before the hibernate dependencies kick in the reactor.

Regarding the test, it is testing a mapping class that it is pre generated in the arc config step and register in runtime init in the Config. It just seems that the class was not registered at all and it failed the test. Usually when registration fails, an exception is thrown, but I don't see any exception either.

Let me restart the CI and see what happens.

**Comment by Sanne** [comment]
thanks all!

**Pull request merged**
