### PR TITLE
Only keep resteasy-qute example codestart binded to resteasy-qute

### PR DESCRIPTION
**Pull request by ia3andy**
This is a merge to the 1.11 branch

### CODE REVIEW

**Comment by ia3andy** [comment]
This has been made to reproduce the effect of https://github.com/quarkusio/quarkus/pull/15148 without having big changes.

**Comment by ia3andy** [comment]
@gsmet I think we need backported to 1.12 too, should I do something?

**Comment by gsmet** [comment]
Yes, it needs the normal backport label. I just added it. I thought the fix was in 1.12 already given you made a 1.11 PR.

Will backport for 1.12.1.Final.

**Comment by ia3andy** [comment]
> Yes, it needs the normal backport label. I just added it. I thought the fix was in 1.12 already given you made a 1.11 PR.
@gsmet yeah, my bad...

**Pull request merged**
