### PR TITLE
Add the default lifecycle mapping to the quarkus-maven-plugin

### LINKED ISSUE #19838: quickstarts: do not define quarkus plugin goal "build" (less code is more)
### Description

For example in:
https://raw.githubusercontent.com/quarkusio/quarkus-quickstarts/main/getting-started/pom.xml
it says:

```
       <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

But this should just suffice:

```
       <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus-plugin.version}</version>
            </plugin>
```

Less is more. Configuration by exception. Keep it simple.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #19838

This change adds the default lifecycle mapping for the `quarkus-maven-plugin`, so the default application config could be made simpler looking by removing the execution goals. For example instead of 
````
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
````
the following would be enough
````
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
      </plugin>
````

### CODE REVIEW

**Comment by famod** [comment]
So, this would be like e.g. maven-compile-plugin? How can I then get rid of e.g. `generate-code`?

**Comment by aloubyansky** [comment]
There are a few issues with this change that need further evaluation:

1. if a project already contains a traditional `quarkus-maven-plugin` config with the `build`, `generate-code` and `generate-code-tests` listed, the execution IDs of these goals will be different (`default` for the goals configured in the application pom.xml and `default-<goal>` for the goals configured in the lifecycle mapping, which will result in duplicate goal execution. For example
````
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:generate-code (default-generate-code) @ code-with-quarkus ---
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:generate-code (default) @ code-with-quarkus ---
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/aloubyansky/playground/test-devtools/code-with-quarkus/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:generate-code-tests (default-generate-code-tests) @ code-with-quarkus ---
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:generate-code-tests (default) @ code-with-quarkus ---
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /home/aloubyansky/playground/test-devtools/code-with-quarkus/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/aloubyansky/playground/test-devtools/code-with-quarkus/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ code-with-quarkus ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.GreetingResourceTest
2021-09-01 22:53:56,899 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT on JVM started in 1.515s. Listening on: http://localhost:8081
2021-09-01 22:53:56,901 INFO  [io.quarkus] (main) Profile test activated. 
2021-09-01 22:53:56,901 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, smallrye-context-propagation]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.481 s - in org.acme.GreetingResourceTest
2021-09-01 22:53:58,112 INFO  [io.quarkus] (main) Quarkus stopped in 0.034s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ code-with-quarkus ---
[INFO] Building jar: /home/aloubyansky/playground/test-devtools/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default-build) @ code-with-quarkus ---
[INFO] [org.jboss.threads] JBoss Threads version 3.4.2.Final
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1027ms
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ code-with-quarkus ---
[INFO] [org.jboss.threads] JBoss Threads version 3.4.2.Final
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1011ms
````

2. with the lifecycle mapping configured in the plugin, the following plugin configuration
````
 <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
      </plugin>
````
will be interpreted as having the `build` goal explicitly configured. This may break some existing projects that add the `quarkus-maven-plugin` w/o configuring the `build` goal. The issue is that `quarkus:dev` executed from the root of the workspace, will search for a module that includes the `quarkus-maven-plugin` with the `build` goal configured and will launch the first found module as the app.

**Comment by aloubyansky** [comment]
> So, this would be like e.g. maven-compile-plugin? How can I then get rid of e.g. `generate-code`?

Right, it covers all the goals.

**Comment by aloubyansky** [comment]
There is a workaround for 1. We can check which goals are configured in the project. So if there is a matching `quarkus:` goal with the `default` ID, we could skip one of the executions.

I am not yet sure what we could do about 2.

**Comment by aloubyansky** [comment]
> So to get rid of `generate-code`, I would need to do:
> 
> ```
> <execution>
>   <id>default-generate-test</id>
>   <phase>none</phase>
> <execution>
> ```
> 
> (maybe also with `<goal>`)?
> 
> If yes, I'm personally -1 to this.
> 
> The other issues you've listed don't look great either.

We could have a `skipGenerateCode` property and/or mojo parameter that you could enable.

**Comment by gsmet** [comment]
TBH, I'm not sure it's an improvement. The current thing is generated anyway so it's no hassle for the users and it looks harder to grasp.

Only issue might be if we tweak the goals in the future, not sure how common that will be.

**Comment by ge0ffrey** [comment]
Code generation only works the first time, not when the project evolves.

If the generated code is complex, it's makes Quarkus look complex. This is **accidental complexity**.

For spring, this just works:
```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
```

**Comment by maxandersen** [comment]
> The issue is that `quarkus:dev` executed from the root of the workspace, will search for a module that includes the `quarkus-maven-plugin` with the `build` goal configured and will launch the first found module as the app.

why is it that its looking for one with build in it? why would there be a quarkus-maven-plugin and it would not be relevant for quarkus:dev to use it as app ?

**Comment by maxandersen** [comment]
>     1. if a project already contains a traditional `quarkus-maven-plugin` config with the `build`, `generate-code` and `generate-code-tests` listed, the execution IDs of these goals will be different

anyways we can detect that mirrored goal exists and skip the default and print message ? a bit hacky but would make it at least not be incorrect.

...another aspect is how these will work withing IDE's...but I assume it won't be much of an issue as we already had them default generated everytime.

**Comment by ge0ffrey** [comment]
So there are 2 types of quarkus-maven-plugin users:
A) users that want to do the `build` goals etc
B) users that don't want to the `build` goals etc, and have to use `<phase>none</phase>`

If you had to guess, what percentage of users are in group A) and what percentage are in group B)?

**Comment by famod** [comment]
> So there are 2 types of quarkus-maven-plugin users: A) users that want to do the `build` goals etc B) users that don't want to the `build` goals etc, and would have to use `<phase>none</phase>`
> 
> If you had to guess, what percentage of users are in group A) and what percentage are in group B)?

Probably more in group A, but I'd like to point out:
- How many are really annoyed by default maven way of listing goal to execute?
- How do we guide those user that set up their multi module projects? Currently, code.quarkus.io doens't provide a multi-module template (AFAICS) and so user might end up having the plugin defined in the regular `plugins` section and so it will run for every single child module.

**Comment by ge0ffrey** [comment]
> How many are really annoyed by default maven way of listing goals to execute?

I hoping it's not just me who gets annoyed by boilerplate code in a build file :)

My bigger worry is the fact that apparently **just adding the build goal isn't enough** - even though we've been pushing that for over a year in optaplanner-quickstarts and **quarkus-quickstarts still pushes that** - as the other goals (generate-code etc) should be added in all those build files too, with all users, to make it future proof.

**Comment by gsmet** [comment]
Closing due to lack of activity.

Please open a new PR if need be.

**Pull request closed without merging**
