### PR TITLE
Sentry tests - getSentryHandler method to reduce duplicated code

### PR DESCRIPTION
**Pull request by rsvoboda**
Sentry tests - getSentryHandler method to reduce duplicated code

### CODE REVIEW

**Comment by gsmet** [comment]
@ia3andy can you have a look?

**Review by ia3andy — APPROVED** [review]
Looks good, @rsvoboda did you also refactor the other Logger tests which use nearly the same code as well?

**Comment by rsvoboda** [comment]
@ia3andy will double check other logger tests, looked just in sentry ones.

**Comment by ia3andy** [comment]
@rsvoboda have a look in `core/test-extension/deployment/src/test..` and in `extensions/logging-json/deployement/src/test/...`

**Pull request merged**
