### PR TITLE
Update to SmallRye Fault Tolerance 5.2.1

### LINKED ISSUE #18511: FaultToleranceDefinitionException after migrating to Quarkus 2.0
## Describe the bug
After migrating to Quarkus 2.0, @Retry throws the following exception:
```
Caused by: javax.enterprise.inject.spi.DeploymentException: org.eclipse.microprofile.faulttolerance.exceptions.
FaultToleranceDefinitionException: Invalid @Blocking/@NonBlocking on public java.lang.String org.acme.getting.
started.ReactiveGreetingResource.greeting(java.lang.String): must return java.util.concurrent.CompletionStage or io.smallrye.mutiny.Uni
```
Using resteasy-reactive extension, the problem takes place on blocking endpoints with non Uni or CompletionStage return values.
The problem can be mitigated by:
 1. removing @Retry annotation
 2. rolling back to pre Quarkus 2.0 versions
 3. moving from resteasy-reactive to non-reactive resteasy.

### Expected behavior
Not getting FaultToleranceDefinitionException.

### Actual behavior
FaultToleranceDefinitionException thrown.

## To Reproduce
https://github.com/jjolsvai/quarkus-ft-reproducer

1. run the unit test in re-producer

## Additional context
We have a common library with resteasy reactive, but not all the microservices moved to full reactive yet. Hence, there are blocking endpoints.

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #18511

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by kenfinnigan** [comment]
@Ladicek could you rebase? thanks

**Comment by Ladicek** [comment]
Rebased.

@gsmet FYI, this is not suitable for 2.0, because it follows up on #18361.

**Comment by gsmet** [comment]
OK, thanks for the heads up. I usually figure it out when backporting :).

**Comment by jjolsvai** [comment]
Thanks @Ladicek for the fixing the issue so quickly!

**Pull request merged**
