### PR TITLE
Prevent a malformed URI from hanging the Reactive REST Client

### LINKED ISSUE #24042: RestClient reactive hangs forever when url is invalid
### Describe the bug

When using the rest client with an invalid url example `http//localhost:8080` note the missing colon. Something makes the calls never return, and timeout values are also ignored. Using `@URL` from hibernate validator is a good way to catch it, but still I believe it should not hang.

In the reproducer I am using quartz scheduler as well. IN that case the app fully hangs and becomes totally unresponsive, it needs to be killed -9.

### Expected behavior

The invalid url should throw a runtime exception of something instead of making the app hang

### Actual behavior

The full application hangs and is not stoppable without killing it

### How to Reproduce?

Reproduder: https://github.com/manofthepeace/quarkus-reproducer-httpHang

Steps to reproduce:
1. mvn quarkus:dev
2. app will hang you need to kill it.

To make it work;
1. in the application.properties change `http//localhost:8080` to `http://localhost:8080`
2. mvn quarkus:dev

### Output of `uname -a` or `ver`

Darwin Kernel Version 20.6.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #24042

### CODE REVIEW

**Comment by geoand** [comment]
My latest change would prevent this case as well.

**Comment by michalszynkiewicz** [comment]
oh, I thought it's after Stork replaces the URI with the actual one. Stork tests fail now, `URL` doesn't know `stork` scheme and it fails

**Comment by geoand** [comment]
Ah, good point

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by geoand** [comment]
Seems like the second commits needs formatting 😉

**Comment by michalszynkiewicz** [comment]
fixed

**Pull request merged**
