### PR TITLE
Add convenience methods mirroring ReflectiveClassBuildItem factory methods

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by geoand** [comment]
+1 for the new methods. 

My only "worry" here is about backporting. If we do intend to backport this (and I don't see why not), then +1 for all the changes.
If we don't, then I would prefer if we only added the new methods and didn't change the build steps.

**Comment by metacosm** [comment]
I did wonder about this. Let me know and I'll revert the build steps changes.

**Comment by metacosm** [comment]
Another change that could also be made would be to deprecate the constructors, similarly to what was done for ReflectiveClassBuildItem.

**Comment by geoand** [comment]
Let's do the following:

In this PR introduce only the new methods.
A follow up PR can change the call sites and also deprecate the
constructors.
That way we'll have the flexibility to decide later on

**Comment by metacosm** [comment]
Removed the call sites changes, added javadoc.

**Review by geoand — APPROVED** [review]
Thanks!

**Pull request merged**
