### PR TITLE
Update to Vert.x 4.2.1 and related projects

### PR DESCRIPTION
**Pull request by cescoffier**
Dependencies:

- Update to Vert.x 4.2.1
- Update to Stork 1.0.0.Beta1
- Update to Vert.x Mutiny Bindings 2.15.0
- Update to Quarkus HTTP 4.1.4

Core and HTTP:

- New cookie-related methods
- Relocation of the CACHE_DIR_BASE_PROP_NAME constant
- Update native image configuration for Vert.x

Data Source:

- New preparedQuery method in Pool

Redis:

- Signature changes of the lpop, psync and rpop command
- The workaround done in Quarkus does not break compatibility

Amazon Lambda:

- Relocation of the CACHE_DIR_BASE_PROP_NAME constant

### CODE REVIEW

**Comment by geoand** [comment]
Seems like the PR needs a rebase :)

**Comment by cescoffier** [comment]
@geoand yep... Let's see what's the CI is going to say...

**Comment by stuartwdouglas** [comment]
@cescoffier I think I have fixed it, lets see how this commit goes.

**Comment by cescoffier** [comment]
Awesome thanks @stuartwdouglas !

**Review by geoand — APPROVED** [review]
Great!

**Comment by Sanne** [comment]
Nice! HR upgrade coming in a moment

**Comment by tsegismont** [comment]
>Nice! HR upgrade coming in a moment

Same for MSSQL options

**Comment by Sanne** [comment]
Related: - https://github.com/quarkusio/quarkus/pull/21220

**Comment by Sanne** [comment]
@cescoffier N.B. that Vert.x 4.2.1 is using Netty `4.1.69`
 - https://github.com/vert-x3/vertx-dependencies/blob/4.2.1/pom.xml#L51

shouldn't we align? I need a feature in the later Netty :)

**Comment by Sanne** [comment]
nevermind, the Netty version matches already - sorry got confused with branches while testing.

**Comment by cescoffier** [comment]
We are working on integrating 4.1.70, but we need to be sure Vert.x works with it. I will get the response to that question next week.

**Comment by Sanne** [comment]
> We are working on integrating 4.1.70, but we need to be sure Vert.x works with it. I will get the response to that question next week.

sorry I got confused: I was needing 4.1.69 - it's there already so all good :+1:

**Pull request merged**
