### PR TITLE
Using filtering parameters and namedQuery in the count query

### LINKED ISSUE #41500: The total count for page links do not considered the complete query
### Describe the bug

I'm using the quarkus-hibernate-orm-rest-data-panache extension to generate CRUD's, and in the endpoint that lists the records, the pagination links are not correct. This only becomes evident when I use a filter and/or custom query. Reviewing the source code of the rest-data-panache extension I discovered the reason:

```java
ResultHandle pageCount = tryBlock.invokeVirtualMethod(
                    ofMethod(resourceMetadata.getResourceClass(), Constants.PAGE_COUNT_METHOD_PREFIX + RESOURCE_METHOD_NAME,
                            int.class, Page.class),
                    resource, page);
```
Class: io.quarkus.rest.data.panache.deployment.methods.ListMethodImplementor.java
Line: 232
Version: 3.11.2

The reason is that this SQL query to obtain the total number of records must also consider the filters and/or custom queries that I apply as part of my query-params, and in this way both queries (for the total and list) will be affected by the filters and/or queries:

```java
return creator.invokeVirtualMethod(
        ofMethod(resourceMetadata.getResourceClass(), "list", isNotReactivePanache() ? List.class : Uni.class,
                Page.class, Sort.class, String.class, Map.class),
        resource, page == null ? creator.loadNull() : page, sort, query, dataParams);
```
Class: io.quarkus.rest.data.panache.deployment.methods.ListMethodImplementor.java
Line: 361
Version: 3.11.2

In this second source code fragment you can see that the query and dataParams parameters are being injected, both parameters should also be used to obtain the total.

#### Records in my database:

 id | name | createdBy
--- | --- | --- |
 1  | Jimy | Nikola
 2  | Jaime | Steve
 3  | Julio | Nikola

#### Scenery 1:
Endpoint consumption without filtering parameters:
https://api.jimyx,dev/users?size=2

Headers obtained:
Link: <https://api.jimyx,dev/users?page=0&size=2>; rel="first"
Link: <https://api.jimyx,dev/users?page=1&size=2>; rel="last"
Link: <https://api.jimyx,dev/users?page=1&size=2>; rel="next"

#### Scenery 2:
Endpoint consumption with filtering parameters:
https://api.jimyx,dev/users?size=2&createdBy=Nikola

Headers obtained:
Link: <https://api.jimyx,dev/users?page=0&size=2>; rel="first"
Link: <https://api.jimyx,dev/users?page=0&size=2>; rel="last"

#### Records in my database:

 id | name | createdBy
--- | --- | --- |
 1  | Jimy | Nikola
 2  | Jaime | Steve
 3  | Julio | Nikola

#### Scenery 1:
Endpoint consumption without filtering parameters:
https://api.jimyx,dev/users?size=2

Headers obtained:
Link: <https://api.jimyx,dev/users?page=0&size=2>; rel="first"
Link: <https://api.jimyx,dev/users?page=1&size=2>; rel="last"
Link: <https://api.jimyx,dev/users?page=1&size=2>; rel="next"

#### Scenery 2:
Endpoint consumption with filtering parameters:
https://api.jimyx,dev/users?size=2&createdBy=Nikola

Headers obtained:
Link: <https://api.jimyx,dev/users?page=0&size=2>; rel="first"
Link: <https://api.jimyx,dev/users?page=1&size=2>; rel="last"
Link: <https://api.jimyx,dev/users?page=1&size=2>; rel="next"

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by j1myx**
- Fixes: https://github.com/quarkusio/quarkus/issues/41500

@geoand , @Sgitario

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand this looks like a nice contribution, not sure who should review it? Maybe @FroMage ?

**Comment by geoand** [comment]
Very nice indeed!

Perhaps @Sgitario could take a quick look

**Review by Sgitario — APPROVED** [review]
I did take a look in the previous PR: https://github.com/quarkusio/quarkus/pull/42155, where I had some concerns about the tests. I see that it has been sorted it out in these changes, so as long as the CI is green, I'm ok with these changes.
Great contribution!

**Comment by j1myx** [comment]
> Can you please fix the formatting issue (the command is in the bot's message) and force push? Or if you prefer, I can do that for you.
> 
> Thanks

Hi @geoand, Now I upload the correction

**Comment by j1myx** [comment]
Hi @geoand, I just made the correction.

**Comment by geoand** [comment]
Thanks a lot!

**Comment by gsmet** [comment]
Will backport this to 3.13.1, that we will release next week.

**Pull request merged**
