### PR TITLE
Diataxis restructure of security docs

### PR DESCRIPTION
**Pull request by michelle-purcell**
Content updates to restructure the Quarkus Security Basic authentication content into the new Quarkus doc contributor templates based on the Diátaxis framework.

**Includes:**
- [x] Applying the Quarkus docs filename and ID syntax (by renaming existing content files)
- [x] Adding taxonomy tags for security/getting started
- [x] Fixing links in other topics where the source file name has changed
- [x] Creating required redirects to ensure that bookmarks do not break (See quarkus website repo PR [1579](https://github.com/quarkusio/quarkusio.github.io/pull/1579) 

REF: [QDOCS-68](https://issues.redhat.com/browse/QDOCS-68 )

### CODE REVIEW

**Comment by michelle-purcell** [comment]
@gsmet -  As I am changing the file names of existing content in this PR to match the preferred Quarkus templates (`diataxis` content types), I need to understand how to create a redirect. Can you confirm how to do this, as per QDOCS-72?

**Review by sberyozkin — APPROVED** [review]
Hi @michelle-purcell Thanks for this PR, I think it all looks fine, would it make sense to rename the PR title, the basic authentication content issue is fixed, but all security docs have been impacted due to the link updates/etc, so may be it should read `Diataxis restructure of security docs` ?

**Comment by michelle-purcell** [comment]
@sberyozkin  Done :+1:

**Comment by sberyozkin** [comment]
Sorry @michelle-purcell, I've merged #29454 as it was green and I thought this PR was still WIP (redirects still have to be taken care of as per your list of tasks above), but now there is a conflict, hope they could be resolved easily enough, thanks

**Comment by michelle-purcell** [comment]
`> Sorry @michelle-purcell, I've merged #29454 as it was green and I thought this PR was still WIP (redirects still have to be taken care of as per your list of tasks above), but now there is a conflict, hope they could be resolved easily enough, thanks`

No need to apologize @sberyozkin :+1:  Thanks for flagging. 
I have now fixed the conflicts and rebased successfully.
The redirects are also created and merged too.

**After this PR is merged:** There's more to be done with the basic authentication conceptual information in the existing guide format, as per [Basic Auth HowTo and Tutorial content is identical #29472 ](https://github.com/quarkusio/quarkus/issues/29472).

**Comment by sberyozkin** [comment]
@michelle-purcell Sounds good, thanks

**Pull request merged**
