### PR TITLE
Inject KafkaClientSupplier and State(Restore)Listener in KafkaStreams

### LINKED ISSUE #8923: Possibility to set KafkaClientSupplier + State(Restore)Listener in KafkaStreams extension
**Description**
Hello it would be possible to inject/set into the KafkaStream instance other instances of interfaces that are commonly used to customize kafkastream user needs.
- [KafkaClientSupplier](https://kafka.apache.org/20/javadoc/org/apache/kafka/streams/KafkaClientSupplier.html) allow to override Producer/Consumer factories
- [StateListener](https://kafka.apache.org/20/javadoc/org/apache/kafka/streams/KafkaStreams.StateListener.html) is a hook into KafkaStream instance lifecycle.
- [StateRestoreListener](https://kafka.apache.org/10/javadoc/org/apache/kafka/streams/processor/StateRestoreListener.html) that would allow to monitor the restore time of stateful KafkaStream application

**Implementation ideas**
These instances need to be set up during the creation of the KafkaStream instance and should be set before start method has been call.

Since the approach would be the same for both needs (listener + supplier), like discovering instances of these bean using CDI they could be done in the same pull request.

Note that allow the possibility of setting KafkaClientSupplier has been mentioned as a prerequisites of #5471 to implement OpenTracing support in the extension.

Regards

### PR DESCRIPTION
**Pull request by rquinio**
Fixes #8923

Enables user instrumentation (tracing, metrics, ...) of the KafkaStreams instance, by discovering beans of type KafkaClientSupplier, StateListener and StateRestoreListener, similar to discovery of Topology bean.
Some default instrumentation could come later come via the extension (cf #5471).

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Nice, thanks!

**Comment by rquinio** [comment]
@gsmet I've had a more careful look to the CI result, it looks like the 1st failure was random, but 2nd one on GraalVM actually comes from my test :/

```
@Inject is not supported in NativeImageTest tests. Offending field is io.quarkus.it.kafka.streams.KafkaStreamsTest.stateListener
```

I guess there's no easy way to test then ?

**Comment by gsmet** [comment]
You need to do the injection in the REST resource not in the Quarkus test itself and then use REST Assured to check it.

Shouldn't have missed it.

**Comment by rquinio** [comment]
> You need to do the injection in the REST resource not in the Quarkus test itself and then use REST Assured to check it.

Ha ok I see, I'll try to fix it asap.

**Comment by LeonardoBonacci** [comment]
Any update on this issue?

**Pull request merged**
