### PR TITLE
docs: fix description for credentials provider

### PR DESCRIPTION
**Pull request by kdnakt**
Fixed AWS credentials info according to the official document:
https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html

### CODE REVIEW

**Comment by gsmet** [comment]
@marcinczeczko could you have a look at that one?

**Comment by sberyozkin** [comment]
Is there an option (in the future) to have these AWS features exposed to the rest of Quarkus via a new credential provider spi ?

**Comment by marcinczeczko** [comment]
@kdnakt thanks for spotting it up. @gsmet looks good to me

**Comment by kdnakt** [comment]
Thank you for the review!

**Comment by marcinczeczko** [comment]
@sberyozkin - I think it might be a good idea. Are you able to raise an issue and describe come potential scenarios where you'd like to use it ?

**Review by marcinczeczko — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Pull request merged**
