### PR TITLE
Revert "Set Hibernate ORM connection handling strategy to BEFORE_TRANSACTION_COMPLETION"

### PR DESCRIPTION
**Pull request by gsmet**
This reverts commit 7e4b6317083aef900e6229ab0b3e64a7e5547fb0.

See #9578

### CODE REVIEW

**Comment by Sanne** [comment]
I could use a bit more context?

**Comment by gsmet** [comment]
@Sanne this is related to the quarkus-dev discussion with John. Did you see the issue I pointed in the description of the PR?

**Comment by Sanne** [comment]
yes I saw the issue. Sorry, being slow as it's PTO here and yet there's a lot going on..

I wish we could investigate more but I agree we can defer that. +1 to revert first, investigate later ;)

**Review by Sanne — APPROVED** [review]

**Pull request merged**
