### PR TITLE
Use an instance of the proper service initiator for SQL import

### PR DESCRIPTION
**Pull request by gsmet**
Tentative fix for #11566 but doesn't work :/

@Sanne I fixed the most obvious issue but it still doesn't work AFAICS. The jpa tests are failing even with my fix. Looks like the service initiator is not called.

Do you have an idea?

### CODE REVIEW

**Comment by gastaldi** [comment]
You might also know, but an easy way to write singletons and avoid these obvious issues is to do: 

```java
public enum QuarkusImportSqlCommandExtractorInitiator implements StandardServiceInitiator<ImportSqlCommandExtractor> {
    INSTANCE;
    ...
}
```

**Comment by Sanne** [comment]
n.b. there is a related issue which will be resolved as soon as we upgrade ORM, there has been a regression in the upstream parser (but I'm not sure if it's related specifically to what you are looking at)

**Comment by gsmet** [comment]
I don't know. I added a log in the initiator and I didn't see it called. But maybe I missed something obvious.

**Comment by Sanne** [comment]
I'm confused.. did the JPA tests not fail before this? I'll build it all locally..

**Comment by gsmet** [comment]
I don't know if we had a multi-line import SQL file before. I added one in this PR and it fails.

**Comment by Sanne** [comment]
thanks, I see what's going on now. Working on it..

**Comment by gsmet** [comment]
I force pushed an update to fix the comment added to the import file.

**Comment by Sanne** [comment]
For some reason I can't push on your PR.. I'll open a new one including your latest commit.

**Pull request closed without merging**
