### PR TITLE
Add a note about quarkus.http.root-path to security authorization guide

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by gastaldi — DISMISSED** [review]

**Review by ebullient — CHANGES_REQUESTED** [review]
The implementation of this should work with relative paths by default (that's what we tried to fix across the board where paths are specified):

image

image

Note that `quarkus.http.root-path` is / by default, making it effectively invisible. 

All configured paths that users specify should be relative by default/example, so they automatically travel with a configured `quarkus.http.root-path`. 

These behaviors should be accounted for: 
- https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/NonApplicationAndRootPathTest.java
- https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/NonApplicationEscapeTest.java
- https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/NonApplicationRootPathSiblingTest.java

(see the relationship between `quarkus.http.root-path` and `quarkus.http.non-application-root-path` .. the changes for securing endpoints needs to react to when quarkus.http.root-path is not set (default /), and when it is set (to something else).

Was this written with the assumption that endpoints being secured are always absolute (and not relative to http root?)

**Comment by sberyozkin** [comment]
@ebullient This note is meant primarily for 2.8.x, I promised to follow up with this note, which is why it is here,
I opened an issue yesterday at #25154, this is where `http.root-path` for security related relative paths will be dealt with consistently

**Comment by sberyozkin** [comment]
@ebullient 

>Was this written with the assumption that endpoints being secured are always absolute (and not relative to http root?)
That security policy code has been written originally to compare these path values against the request URL's path component, `http.root` part of such paths is not currently taken into account. I'd prefer not to go into absolute vs relative variations in the context of dealing with these security paths

**Comment by sberyozkin** [comment]
Let me just close this one to avoid introducing any confusions to the users

**Pull request closed without merging**
