### PR TITLE
Update vert.x to 4.4.6

### PR DESCRIPTION
**Pull request by bartm-dvb**
- Fixes Redis connection pooling for #36382

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks but Vert.x updates are usually a bit harder than that as it's a core component and we might need to release other components :).

@cescoffier my understanding is that you will need to coordinate this one with other releases?

**Comment by bartm-dvb** [comment]
> Thanks but Vert.x updates are usually a bit harder than that as it's a core component and we might need to release other components :).
> 
> @cescoffier my understanding is that you will need to coordinate this one with other releases?

Alright, I was suspecting that would be the case but I was willing to give it a try anyway. You can close this PR if it will be picked up by the maintainers.

**Comment by cescoffier** [comment]
Yes, it's a lot more compiicated, and our upgrade must be backportable too.

In general, it requires:

- updating the Mutiny bindings and verifying breaking changes
- updating reactive messaging
- updating stork
- updating quarkus HTTP
- finally, updating quarkus
- expose new config in quarkus and extend documentation
- verify the issues that were potentially fixed in vert.x 

I will try to start the process this week. However, it takes several days of work.

**Comment by ahus1** [comment]
Upcoming PR: 

* #36544

**Pull request closed without merging**
