### PR TITLE
Change the dev/test mode defaults to localhost

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This prevents users on the same network from
connecting to your development machine (which could
be a problem on public networks, such as in a coffee
shop).

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@stuartwdouglas thanks Stuart, `integration-tests/main` are failing, likely due to the property update:
```
Caused by: javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: quarkus.http.host
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:39)
```

**Review by geoand — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I have changed this to use a low priority config source.

**Comment by sberyozkin** [comment]
Hi @stuartwdouglas one more test is failing, probably the last one
```
Failures: 
Error:    JaxRSITCase>JaxRSTestCase.testConfigInjectionOfPort:40 1 expectation failed.
Response body doesn't match expectation.
Expected: is "localhost"
  Actual: 0.0.0.0
```

**Comment by sberyozkin** [comment]
Hey Stuart @stuartwdouglas, 
it is MP Config TCK now:
```

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.io.NotSerializableException: io.quarkus.vertx.http.runtime.HttpHostConfigSource
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
``` 
The new [config source](https://github.com/quarkusio/quarkus/pull/13223/files#diff-e99cad820a5d635678fd94a2cc4e4811f6247f3bce237c567052a15b3e516c25) looks fine

CC @radcortez

**Comment by radcortez** [comment]
The TCK checks if the `Config` object is `Serializable`, which is not because the new `ConfigSource` is not Serializable. We already made a change in SR Config to be more flexible to tolerate a non `Serializable` `ConfigSource`, but it is not released yet.

**Comment by gsmet** [comment]
Rebased and fixed an import order issue. We will get this in!

**Comment by stuartwdouglas** [comment]
There are still some failures, I am investigating.

**Comment by stuartwdouglas** [comment]
I have no idea what is happening here. Somehow adding the new config source causes other config sources to fail in native image mode.

**Comment by stuartwdouglas** [comment]
I think I have fixed the remaining issues, hopefully 10th times the charm...

**Comment by sberyozkin** [comment]
@gsmet Hi Guillaume - here is another one where I should've also included `triage/backport-1.7?` as well, adding it now, thanks

**Pull request merged**
