### PR TITLE
Update to Java Parser 3.24.4

### PR DESCRIPTION
**Pull request by cescoffier**
CC @mariofusco

### CODE REVIEW

**Comment by gsmet** [comment]
OK, just so we are clear: we need this to get in a given Quarkus version and in the Kogito version that will end up in the Platform of this given Quarkus version. So let's be careful about when we merge it in both trees.

**Review by mariofusco — APPROVED** [review]

**Comment by gsmet** [comment]
@mariofusco so should we target this for the Kogito version that will go into 2.13 (i.e. our next version coming in about a month)?

/cc @evacchi

**Comment by mariofusco** [comment]
@gsmet Are you still planning to merge this? If there isn't any other blocker please do so, we need it to also upgrade javaparser on Drools/Kogito, thanks.

**Comment by cescoffier** [comment]
@gsmet @mariofusco what's the status of this one?

**Comment by mariofusco** [comment]
@cescoffier I'm ready to merge the upgrade on the drools/kogito side and I was waiting for this PR to be merged before moving forward also there. 
@gsmet how do you want to proceed here?

**Comment by famod** [comment]
Coming from #30162 (dependabot update to 3.24.10), is there any progress on this?

**Pull request closed without merging**
