### PR TITLE
Update Gradle to 6.2.2

### PR DESCRIPTION
**Pull request by SR-Lut3t1um**
There are no other changes in the jarfile and the wrapper files.

### CODE REVIEW

**Comment by gastaldi** [comment]
Good job! You also need to update code.quarkus.io with this change

**Comment by gastaldi** [comment]
No changes in the `gradlew` script?

**Comment by SR-Lut3t1um** [comment]
No, no changes. I will change io asap. Probably in 12 hours.

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Looks like the CI is borked. Can I ask you to rebase to the latest master and force push?

**Comment by gastaldi** [comment]
Thank you!

**Pull request merged**
