### PR TITLE
Re-enable the code flow test

### LINKED ISSUE #7044: OIDC code flow tests failing in native on CI
The OIDC code flow tests are now consistently failing on CI with something like:

```
Caused by: org.opentest4j.AssertionFailedError: expected: </index.html> but was: <null>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at io.quarkus.it.keycloak.CodeFlowTest.testAccessTokenInjection(CodeFlowTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:360)
	... 62 more

2020-02-06 17:27:14,690 INFO  [io.quarkus] (main) Quarkus stopped in 0.069s

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CodeFlowTest.testAccessAndRefreshTokenInjection » Runtime org.opentest4j.Asser...
[ERROR]   CodeFlowTest.testAccessAndRefreshTokenInjectionWithoutIndexHtml » Runtime org....
[ERROR]   CodeFlowTest.testAccessTokenInjection » Runtime org.opentest4j.AssertionFailed...
[ERROR]   CodeFlowTest.testCodeFlowNoConsent » Runtime org.opentest4j.AssertionFailedErr...
[ERROR]   CodeFlowTest.testIdTokenInjection » Runtime org.opentest4j.AssertionFailedErro...
[ERROR]   CodeFlowTest.testIdTokenInjectionWithoutRestoredPath » Runtime org.opentest4j....
[ERROR]   CodeFlowTest.testTokenTimeoutLogout » Runtime org.opentest4j.AssertionFailedEr...
```

/cc @sberyozkin @pedroigor

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #7044.

### CODE REVIEW

**Comment by sberyozkin** [comment]
Previously the tenant resolver was using a cookie to preserve the tenant id across multiple requests, which was causing issues in CI, specifically, I believe the only way one would get the failures like the ones which were happening (the state cookie was available but no saved original path hence a null assertion failure) is when the cookie pointing to a tenant id configuration (which in turns instructs OIDC not to preserve the original path) is interfering (i.e was not cleared despite the test request).
I've simplified the test, if a path contains a `callback-` which is only used by this test then it is a `tenant-1` configuration. `callback-before-redirect` would happen when the test is doing the initial request, `callback-after-redirect` - after the OIDC server redirects the user back, with `callback-after-redirect` picked up from the `tenant-1` configuration.

**Comment by sberyozkin** [comment]
@gsmet @gastaldi @geoand  Hi, this test passed on Windows,
```
2020-02-07T17:36:28.1295838Z [INFO] Quarkus - Integration Tests - OpenID Connect Adapter Code Flow SUCCESS [  2.240 s]
```
May be you can approve ? (Would be good to expand the team of the OIDC reviewers anyway :-) ) I can rebase it, but not sure it is needed. This is only a test update to make it run predictably, please see the comment above...

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by sberyozkin** [comment]
@gastaldi Thanks George.
@gsmet, Guillaume, I'm preparing a PR to improve the multi-tenancy support so I'd be happy to pick up this updated test there. I'll merge later this evening if you will have no objections by then...

Cheers

**Pull request merged**
