### PR TITLE
[3.8] Prevent smallrye-graphql-schema-builder from leaking into runtime deps

### PR DESCRIPTION
**Pull request by jmartisk**
@rsvoboda

### CODE REVIEW

**Comment by jmartisk** [comment]
Very strictly speaking it's a breaking change, but only if somebody uses the configuration object (`SmallRyeGraphQLConfig`) programmatically, which I think is not supported for applications?! But the benefit here is big, we get rid of the `kotlin-stdlib` and `kotlinx-metadata-jvm` dependencies in runtime.

**Comment by rsvoboda** [comment]
Context for backports session: fixes https://github.com/quarkusio/quarkus/pull/40104

**Comment by aloubyansky** [comment]
FYI @gsmet, we'll want it in 3.8.4.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I'm not sure what's going on with this gRPC test failing. It has been failing a few times...

**Pull request merged**
