### PR TITLE
Fix multi-module Hot-Code-Replacement

### LINKED ISSUE #23164: Hot reload does not build multi module project in correct order
### Describe the bug

I have a multi module project, where I get exceptions on hot reload.
If I inly change one module at a time (and hot reload), no exception is thrown.

If i change multiple modules at the same time, I get the exception from below.
In module "service", I add a new method which I use in my rest resources in "web".
This new method is not found on hot reload.

I believe that the web module is compiled before service, otherwise the newly created method would be found.

### Expected behavior

Hot reload works flawlessly even when changing multiple modules at once.

### Actual behavior

Following exception:

```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-01-25 07:09:35,054 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.datasource.db-kind" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

2022-01-25 07:09:35,054 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.hibernate-orm.log.sql" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-01-25 07:09:35,054 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.hibernate-orm.validate-in-dev-mode" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-01-25 07:09:35,054 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.hibernate-orm.database.generation" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-01-25 07:09:35,055 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.datasource.metrics.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-01-25 07:09:35,737 INFO  [io.qua.sch.run.SimpleScheduler] (Quarkus Main Thread) No scheduled business methods found - Simple scheduler will not be started
2022-01-25 07:09:35,874 INFO  [io.quarkus] (Quarkus Main Thread) multi-module-hot-reload-web 1.0-SNAPSHOT on JVM (powered by Quarkus 2.6.1.Final) started in 4.437s. Listening on: http://localhost:8080
2022-01-25 07:09:35,874 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-01-25 07:09:35,874 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, config-yaml, hibernate-validator, jdbc-postgresql, rest-client, rest-client-jackson, resteasy-jackson, scheduler, smallrye-context-propagation, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui, vertx]
2022-01-25 07:09:39,838 INFO  [io.qua.htt.access-log] ([DevConsole]vert.x-eventloop-thread-1) 127.0.0.1 - - 25/Jan/2022:07:09:39 +0000 "GET /q/dev HTTP/1.1" 302 -
2022-01-25 07:09:39,910 INFO  [io.qua.htt.access-log] ([DevConsole]vert.x-eventloop-thread-1) 127.0.0.1 - - 25/Jan/2022:07:09:39 +0000 "GET /q/dev/ HTTP/1.1" 200 51097

--
Compilation Failed:
warning: [options] system modules path not set in conjunction with -source 11
C:\workspaces\aviator\multi-module-hot-reload\multi-module-hot-reload-web\src\main\java\com\acme\rest\Resource.java:18: error: cannot find symbol
        return configuration.someSetting2();
                            ^
  symbol:   method someSetting2()
  location: variable configuration of type com.acme.config.ApplicationConfiguration
Tests paused
Press [r] to resume testing, [o] Toggle test output, [h] for more options>

```

### How to Reproduce?

1. Download the reproducer: 
[multi-module-hot-reload.zip](https://github.com/quarkusio/quarkus/files/7931394/multi-module-hot-reload.zip)

2. mvn clean compile quarkus:dev
3. open dev ui - this works
4. In com.acme.config.ApplicationConfiguration, remove the comments from `someSetting2`
5. In com.acme.rest.Resource, change the resource to `return configuration.someSetting()` instead of an empty string.
6. reload the dev ui
7. compilation error from above happens
8. Stop quarkus
9. mvn clean compile quarkus:dev
10. open dev ui - this works. The source itself is compileable by maven, but not by quarkus.

### Output of `uname -a` or `ver`

MSYS_NT-10.0-19043 NANB7NLNVP2 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment Temurin-17+35 (build 17+35) OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739) Maven home: C:\eclipse\tools\apache-maven Java version: 17, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\17 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Chris311**
* [Here](https://github.com/quarkusio/quarkus/blob/e8b0c1e02b7eab0fda93fe476b15839eb1051c97/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L656) the `applicationRoot` will always be traversed first. Thus, any incompatible change in any other module will always result in a compile error https://github.com/quarkusio/quarkus/blob/e8b0c1e02b7eab0fda93fe476b15839eb1051c97/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L708
* Furthermore this will always result in `restartNeeded = false`
https://github.com/quarkusio/quarkus/blob/e8b0c1e02b7eab0fda93fe476b15839eb1051c97/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L525
* resolves [#23164](https://github.com/quarkusio/quarkus/issues/23164)

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]
Assuming CI passes then this should be fine, but we likely also need to ensure that the 'additionalModules' are ordered in the correct order as well, so this is likely only a partial fix.

**Comment by Postremus** [comment]
@Chris311 
Thank you very much for working on this. This will solve some real productivity issued I was facing.

@stuartwdouglas 
yes, this is only a partial fix, but should at least get simple projects going.
My real world application has no code in the applicationRoot at all. According to the debugger, everything is part of an `additionalModule`.
I can create a more comples reproducer, if that helps?

**Review by Postremus — APPROVED** [review]
I tested the change, and can confirm that this helps with simple multi module projects. Thank you!

**Comment by gsmet** [comment]
I rebased the branch to get rid of the merge commit but CI was green before so let's merge!

**Comment by beatngu13** [comment]
Regarding `additionalModules`: @Chris311 made the observation that, at least in our case, these are already properly sorted. But it could by that this was just by chance.

What one probably wants is to obtain the module build order from the underlying build tool. Looks like there are currently three places, where the modules are set:

* https://github.com/quarkusio/quarkus/blob/d634c336b47452a55a3548361648eebe650ffb62/core/deployment/src/main/java/io/quarkus/deployment/mutability/DevModeTask.java#L92
* https://github.com/quarkusio/quarkus/blob/d634c336b47452a55a3548361648eebe650ffb62/core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusDevModeLauncher.java#L409
* https://github.com/quarkusio/quarkus/blob/d634c336b47452a55a3548361648eebe650ffb62/core/deployment/src/main/java/io/quarkus/deployment/dev/IDEDevModeMain.java#L57

Anyway, I think this PR is already a great improvement and the (possible) problems with `additionalModules` can be addressed via another change.

**Pull request merged**
