### PR TITLE
TenantConfigResolver should be able to work without the default tenant

### LINKED ISSUE #8851: ODIC 'auth-server-url' and 'client-id' or alternatively 'public-key' should not be mandatory for case "Custom TenantConfigResolver"
**Describe the bug**
For security-openid-connect extensions, the properties 'auth-server-url' and 'client-id' or alternatively 'public-key' are always mandatory, even if they are not required in case of using a TenantConfigResolver. 

The following exception is thrown on startup if they are not configured:
```
io.quarkus.runtime.configuration.ConfigurationException: Both 'auth-server-url' and 'client-id' or alterntively 'public-key' must be configured when the quarkus-oidc extension is enabled
	at io.quarkus.oidc.runtime.OidcRecorder.createTenantContext(OidcRecorder.java:96)
	at io.quarkus.oidc.runtime.OidcRecorder.setup(OidcRecorder.java:52)
	at io.quarkus.deployment.steps.OidcBuildStep$setup25.deploy_0(OidcBuildStep$setup25.zig:64)
	at io.quarkus.deployment.steps.OidcBuildStep$setup25.deploy(OidcBuildStep$setup25.zig:89)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:179)
	at io.quarkus.runtime.Application.start(Application.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:177)

```

**Expected behavior**
In case that a [TenantConfigResolver](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/TenantConfigResolver.java) was provided, the properties should **not** be mandatory, because they will most likely not be used. The configuration is returned by the resolver and that means there is no need for a static configuration in the application.properties

**Possible solution**
The [OidcRecorder](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java) class should be enhanced to check wether a custom TenantConfigResolver is available and only throw the exception if this is not the case.

### LINKED ISSUE #8985: mongodb+srv protocol no more working on dev mode since Quarkus 1.3 with Java 11
**Describe the bug**
SInce Quarkus 1.3, using a MongoDB connection String with `mongodb+srv` didn't work anymore on dev mode.
This work fine when launching the JAR file (native mode didn't works for `mongo+srv`).
This work fine with Quarkus 1.2.
This is a Java 11 and later only issue on dev mode.

Adding the right export to the JVM do the trick but we normally didn't need to as using the JAR file works : `--add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming`

**Actual behavior**
It fails with the following stacktrace:
```
Caused by: com.mongodb.MongoClientException: Unable to support mongodb+srv// style connections as the 'com.sun.jndi.dns.DnsContextFactory' class is not available in this JRE. A JNDI context is required for resolving SRV records.
	at com.mongodb.internal.dns.DefaultDnsResolver.createDnsDirContext(DefaultDnsResolver.java:152)
	at com.mongodb.internal.dns.DefaultDnsResolver.resolveAdditionalQueryParametersFromTxtRecords(DefaultDnsResolver.java:112)
	at com.mongodb.ConnectionString.<init>(ConnectionString.java:382)
	at io.quarkus.mongodb.runtime.AbstractMongoClientProducer.createMongoConfiguration(AbstractMongoClientProducer.java:240)
	at io.quarkus.mongodb.runtime.AbstractMongoClientProducer.createMongoClient(AbstractMongoClientProducer.java:87)
	at io.quarkus.mongodb.runtime.MongoClientProducer.createDefaultMongoClient(MongoClientProducer.zig:37)
	at io.quarkus.mongodb.runtime.MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_Bean.create(MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_Bean.zig:138)
	at io.quarkus.mongodb.runtime.MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_Bean.create(MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_Bean.zig:77)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.mongodb.runtime.MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_ClientProxy.arc$delegate(MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_ClientProxy.zig:264)
	at io.quarkus.mongodb.runtime.MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_ClientProxy.getDatabase(MongoClientProducer_ProducerMethod_createDefaultMongoClient_e88f14bf92aae40841e4b513ac764f8acd21873d_ClientProxy.zig:104)
	at org.acme.rest.json.FruitService.getCollection(FruitService.java:44)
	at org.acme.rest.json.FruitService.list(FruitService.java:20)
	at org.acme.rest.json.FruitService_ClientProxy.list(FruitService_ClientProxy.zig:51)
	at org.acme.rest.json.FruitResource.list(FruitResource.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 20 more
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.dns.DnsContextFactory [Root exception is java.lang.IllegalAccessException: class javax.naming.spi.NamingManager (in module java.naming) cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to module java.naming]
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:719)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
	at java.naming/javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at com.mongodb.internal.dns.DefaultDnsResolver.createDnsDirContext(DefaultDnsResolver.java:150)
	... 53 more
Caused by: java.lang.IllegalAccessException: class javax.naming.spi.NamingManager (in module java.naming) cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to module java.naming
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/jdk.internal.reflect.Reflection.ensureMemberAccess(Reflection.java:99)
	at java.base/java.lang.Class.newInstance(Class.java:579)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:716)
	... 58 more
```

**To Reproduce**
The issue can be reproduced easily on the `mongodb-client` integration test:

- Use Java 11
- Update `application.properties` with the following connection String : 
```
quarkus.mongodb.connection-string=mongodb+srv://sarah:connor@toto.tata.titi.com/test?retryWrites=true&w=majority
```
- Launch the application in dev mode: `mvn quarkus:dev`
- Access the endpoint: `curl localhost:8080/books`

Of course, this cluster didn't exist ;) but the test fails before connecting to it.

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #8851

(I've moved the public-key only test to the integration tests to avoid it interfering with the dev mode test) 

CC @michael-schnell, @gsmet

### CODE REVIEW

**Comment by sberyozkin** [comment]
It will require more work...

**Comment by sberyozkin** [comment]
It should be all good now. But the backport will need a minor update, [here](https://github.com/quarkusio/quarkus/pull/9014/files#diff-30d712cc7b9081084c8e883a8d7cd7b5R84), instead of

```
return resolver != null && (resolver.auth == null || resolver.oidcConfig.token.refreshExpired);
```

it should be 

```
return resolver != null && resolver.auth == null;
```

since refreshing will only be supported in 1.5.0.

**Comment by sberyozkin** [comment]
I've added a backport label again. If there are any concerns then lets leave it for 1.5.0

**Comment by gsmet** [comment]
I will let @pedroigor review that one. Will probably be too late for 1.4.2 though.

**Comment by sberyozkin** [comment]
Yes, a bit tight

**Review by pedroigor — APPROVED** [review]

**Comment by sberyozkin** [comment]
@pedroigor Thanks

**Pull request merged**
