### PR TITLE
Allow @ShouldPin/@ShouldNotPin on super class

### PR DESCRIPTION
**Pull request by bdeneuter**
Allow to use @ShouldPin/@ShouldNotPin annotations not only on the class level but also on super classes.
This a PR for the following issue:
https://github.com/quarkusio/quarkus/issues/41782

### CODE REVIEW

**Comment by gastaldi** [comment]
Why not make the annotations `@Inherited`?

**Comment by bdeneuter** [comment]
> Why not make the annotations `@Inherited`?

You are right. With `@Inherited` the tests pass also. I will make the necessary changes and see to cleanup the master branch to not have merge commits and have a single change

**Comment by bdeneuter** [comment]
I'm going to close this PR to cleanup the main branch and have a single commit

**Comment by gastaldi** [comment]
@bdeneuter You can also force push on your branch. Make sure you use `- Fixes #41782` in the PR description too

**Comment by bdeneuter** [comment]
@gastaldi Sorry, it appears I cannot reopen this PR anymore. I have created a new PR for this:
https://github.com/quarkusio/quarkus/pull/41900

**Comment by gastaldi** [comment]
@bdeneuter next time try creating a new branch in your fork and performing the changes in there when creating a new PR. Using the `main` branch doesn't scale very well

**Pull request closed without merging**
