### PR TITLE
Make the directory containing the output fast jar a constant

### PR DESCRIPTION
**Pull request by geoand**
This makes it easy to build a Dockerfile

### CODE REVIEW

**Comment by maxandersen** [comment]
as i understand it the folder is there less for the reason its a fast-jar but its there because we wanted to make the packaged quarkus application be separated from all the other content in the target folder.

wouldn't even uber jar format make sense to put in here?
Thus I suggest we name this `quarkus-app` ?

**Comment by geoand** [comment]
> as i understand it the folder is there less for the reason its a fast-jar but its there because we wanted to make the packaged quarkus application be separated from all the other content in the target folder.
> 

Correct

> wouldn't even uber jar format make sense to put in here?
> Thus I suggest we name this `quarkus-app` ?

Sure, I'll do that

**Comment by geoand** [comment]
@maxandersen done

**Review by stuartwdouglas — APPROVED** [review]
I am ok with the quarkus-app name, but I wonder if we should make it configurable?

**Comment by geoand** [comment]
> I am ok with the quarkus-app name, but I wonder if we should make it configurable?

Good idea! We already have `outputDirectory` in `PackageConfig`, so I reused that

**Pull request merged**
