### PR TITLE
Introduce getSession() to PanacheEntity and PanacheRepository

### PR DESCRIPTION
**Pull request by gastaldi**
This is necessary to perform extra operations

### CODE REVIEW

**Comment by geoand** [comment]
You definitely have my vote, but I'd like someone who contributes to Panache more actively than me to comment

**Comment by gastaldi** [comment]
@geoand thank you, I asked @FroMage too. Feel free to add other reviewers if you feel like 😉

**Review by loicmathieu — APPROVED** [review]
LGTM

Please, avoid too much formatting correction, this make the PR harder to review as more lines are modified that necessary.

**Comment by gastaldi** [comment]
@loicmathieu I know, I blame the formatter plugin for that, since I have only added those methods 😕

**Review by FroMage — CHANGES_REQUESTED** [review]
I feel this is wrong for several reasons:

- It tries to mimick the `PanacheEntityBase.getEntityManager()` call for regular ORM, except that one deals with multiple persistence units, and this one does not. OTOH it looks like the rest of HR with Panache does not support multiple persistence units, and I'm not sure why it wasn't added when it was added to ORM with Panache. Probably that's not this PR's fault.
- It is an instance method, and I can't understand why. The same could be said of `PanacheEntityBase.getEntityManager()` for ORM: why is it an instance method? I can't think of any reason why it would be: it should be a static method. We should fix this.

**Comment by FroMage** [comment]
OH COME ON guys 13h to review a PR that's too fast.

**Comment by loicmathieu** [comment]
> OH COME ON guys 13h to review a PR that's too fast.

Agree, and it's partially my fault as usually I add a comment like "But please wait for FroMage review before merging" :(

**Pull request merged**
