### PR TITLE
Downgrade assertj to 3.21.0 to avoid breaking platform members

### PR DESCRIPTION
**Pull request by aloubyansky**
This should be mostly relevant for 2.7. In 2.8 we should look into removing assertj from the quarkus-bom.

### CODE REVIEW

**Comment by aloubyansky** [comment]
https://github.com/kiegroup/kogito-runtimes/pull/1919#issuecomment-1018433296

**Comment by gsmet** [comment]
But aren't they updating to 3.22?

**Comment by aloubyansky** [comment]
No, they can't do it currently, AFAIU.

**Comment by gsmet** [comment]
OK, noted, but that's Kogito. Are we sure we won't break others by downgrading? :)

I suppose we can try and see.

**Review by gsmet — APPROVED** [review]
I sent an email to the platform coordination list.

**Comment by evacchi** [comment]
thanks folks. We _can_ upgrade when we upgrade to 2.7, but unfortunately we can't right now because of this issue https://github.com/quarkusio/quarkus/pull/23076

**Comment by gsmet** [comment]
@evacchi let's stay on 3.21.0 for 2.7 too.

**Comment by evacchi** [comment]
fyi @radtriste

**Review by gsmet — APPROVED** [review]

**Pull request merged**
