### PR TITLE
REST Client codestart

### LINKED ISSUE #20555: Rest Client codestart (in java and kotlin)
### Description

As Rest Client is one of the most used extension, we should find a good codestart for it (in java and kotlin).

### Implementation ideas

We should first discuss the content of this codestart. The goal is to have code:
- that is re-used 99% of the time to get started with the extension (nearly no deletion)
- that is compatible with all other compatible extensions codestarts

What is the piece of code that you nearly always start with when using the extension.. Make it compile, and it's the perfect codestart!

The guide to create an extension codestart https://quarkus.io/guides/extension-codestart

### PR DESCRIPTION
**Pull request by xstefank**
Resolves #20555

### CODE REVIEW

**Comment by xstefank** [comment]
@ia3andy can you review please?

**Comment by ia3andy** [comment]
Hey @xstefank, it looks nice! 

Could you put the `Extension` as an inner class (we try to have only one file/codestart when possible)?

**Comment by xstefank** [comment]
@ia3andy updated.

**Comment by ia3andy** [comment]
What do you think of naming the class `MyRemoteService` and the method `getExtensionsById(...)` (and add the @Path on the method)?

This is meant to make it easier to find this across different extensions codestarts in the same project..

**Comment by xstefank** [comment]
@ia3andy ok, applied your suggestions.

**Review by ia3andy — APPROVED** [review]
LGTM, let's wait for CI :)

**Pull request merged**
