### PR TITLE
Update to Vert.x 4.3.3 and Mutiny Bindings 2.26.0

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Comment by cescoffier** [comment]
@tsegismont 
I've a vertx-graphql issue:
```
2022-08-17 16:22:23,976 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /graphql failed, error id: 8dbb5ab2-1819-44ee-8838-0f4afb48fdad-1: java.util.MissingResourceException: Can't find bundle for base name i18n.Validation, locale en_US
```

Do you know of any change in vert.x graphql?

**Comment by tsegismont** [comment]
Probably related to this
https://github.com/vert-x3/wiki/wiki/4.3.3-Deprecations-and-breaking-changes

**Comment by cescoffier** [comment]
Thanks @tsegismont, I've tried to register the i18n "bundle" (which is not really a bundle, but well). I got the test passing on my machine, but let's see what the CI says.

**Comment by cescoffier** [comment]
The JPA issue does not seem related. @Sanne  any idea?

**Comment by Sanne** [comment]
@cescoffier It might relate: never seen it before, and it's native-image complaining about a thread being started.

I'm pretty sure Hibernate ORM doesn't start threads during the build so we should investigate.

**Comment by cescoffier** [comment]
The previous run (which ran that part) didn't report the issue.

**Comment by Sanne** [comment]
hum ok, I guess you could ignore then it but I still want to look into it - unstable CI is not something I want to live with :)

I'll see if I can reproduce it locally but don't let that slow you down.

**Comment by cescoffier** [comment]
@Sanne I tried on two machines at home, no problem. As you said... suspicious...

**Comment by gsmet** [comment]
Hmm, the JPA issue is suspicious. I don't think I have seen it fail previously.

**Comment by cescoffier** [comment]
I've retried multiple times without any problem.

**Comment by gsmet** [comment]
Well, the last build also has it. That's what concerns me.

**Comment by cescoffier** [comment]
let's see what the main CI says, we can revert (I'm unable to reproduce it).

**Comment by Sanne** [comment]
FWIW I've run that particular module a dozen times with `-Dnative` and it never failed. Please let me know if you see it fail again.

**Pull request merged**
