### PR TITLE
Fix for 2114 - Missing AWS events classes in jandex when building Lambda

### PR DESCRIPTION
**Pull request by marcinczeczko**
This is a fix for #2114

### CODE REVIEW

**Comment by gsmet** [comment]
@marcinczeczko could you rebase your PR on master and squash it? It contains a lot of commits.

Thanks!

**Comment by marcinczeczko** [comment]
@gsmet - now it's one commit.

**Comment by marcinczeczko** [comment]
When lambda is used with LAMBDA_PROXY mode, the `APIGatewayProxyRequestEvent` can be used. However, the AWS jdk has missing few fields in the inner class causing unmarshalling errors - so I turned off errors on unknowns - see latest commit

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
