### PR TITLE
K8s resource generation

### LINKED ISSUE #29350: Enhancements to the Kubernetes extension
### Description

I recently try the Kubernetes extension to generates Kubernetes ressources and I have some feedback / enhacement proposals : 

- When specifing container ressources, there is a log that seems not necessary
```
Apply requests cpu to:test-kubernetes
```
- The Ingress is using port value instead of port name, the deployment specify a port name of `http`, it would be better to use it instead of the port value.
- When adding Smallrye Health, probes are added to the container spec with the following settings:
```yaml
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
```
As `initialDelaySeconds` is at 0, the first probe will always fails, and as `periodSeconds` is at 30s this means te container will be detected as RUNNING after 30s which is a lot for a typical Quarkus application that can starts in less than 3s even in constrainted environments. I'll suggest configuring  `initialDelaySeconds` to 3s or 5s.
I also wonder why the periodSeconds has been set to 30s when the default is 10s.
- There is no functionality to generates an HorizontalPodAutoscaling, using HPA in deployments is very common, this would be a great addition if Quarkus would be able to generate one.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by loicmathieu**
As discussed in #29350 I update the probe with an initial delay of 5s and a period of 10s which is the default.
The initial delay can be challenged as a Quarkus apps with good limits (like 1CPU and 512MB) would starts in less than 3s.

I wonder if this shouldn't be documented as a breaking change, WDYT ?

Fixes #29350

### CODE REVIEW

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by loicmathieu** [comment]
@iocanel do you think I should add the breaking change label (to write something on the migration guide) or at least the noteworthy one as generated k8s resources will not be the same.

**Comment by iocanel** [comment]
I wouldn't call it a breaking change.
But it might make sense to doc and explain the reasoning anyway.

**Comment by loicmathieu** [comment]
OK, I'll add something inside the migration guide.

**Pull request merged**
