### PR TITLE
Create Redis client beans from buildtime config

### PR DESCRIPTION
**Pull request by ozangunalp**
If a programmatic lookup exists

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by rsvoboda** [comment]
I think this PR should have noteworthy label and entry in migration guide.

Before this change people could have `quarkus.redis.hosts=redis://localhost:6379` in the app `application.properties` but still have the option to define custom `quarkus.redis.hosts` when starting the app.

Now they have `quarkus.redis.hosts=redis://localhost:6379` baked in. To get back to the "dynamic" behaviour they need to drop the entry from `application.properties`.

**Comment by gsmet** [comment]
@rsvoboda so you're saying the connection URL is hardcoded if defined in `application.properties`? If so, we have a problem, I don't think it's acceptable.

**Comment by cescoffier** [comment]
Oh yeah, didn't see the change to BUILD_TIME_AND_RUNTIME_FIXED. 

@ozangunalp we need to go back to runtime.

**Comment by cescoffier** [comment]
Let me revert this PR.

**Comment by ozangunalp** [comment]
Ok, that's not ok. we need to revert it.

I need to come up with a way to get the list of configured Redis data sources without annotations.

**Pull request merged**
