### PR TITLE
Upgrade to SmallRye Fault Tolerance 6.2.6

### PR DESCRIPTION
**Pull request by Ladicek**
- https://smallrye.io/blog/fault-tolerance-6-2-6/

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Would this be considered for backport to 3.2?

The camel-k folks were hitting this issue:

https://github.com/smallrye/smallrye-fault-tolerance/issues/861

**Comment by Ladicek** [comment]
Ah I absolutely intended to add the backport label, but of course forgot! Done.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@Ladicek apparently, you compiled the Kotlin extension of 6.2.6 with Kotlin 1.9.0 and thus it doesn't work anymore with 3.2 projects.

I will be able to make things work in the quickstarts but I don't think this is something you should change in a micro.

**Comment by Ladicek** [comment]
Hmm, that is indeed correct. My assumptions about Kotlin backwards compatibility have been too strong it seems. I can revert to Kotlin 1.8.22 and release 6.2.7.

**Comment by Ladicek** [comment]
I looked into https://github.com/quarkusio/quarkus-quickstarts/commits/main and the only commit that could be relevant seems to be https://github.com/quarkusio/quarkus-quickstarts/commit/df48f5012897c2f1d7ffe6cb79da76d0abe4ec01 -- which doesn't bump to Kotlin 1.9, but to 1.8. Kotlin 1.8 seems to be what we recommend for Quarkus 3.2, so there's no problem in the end?

I generally agree that I shouldn't have done that, and in the future, I'll avoid bumping minor versions of Kotlin in micro versions of SmallRye Fault Tolerance. But I don't need to revert and re-release at the moment, right?

**Pull request merged**
