### PR TITLE
Qute - do not split expr parts before the literal is parsed

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by FroMage — APPROVED** [review]
Well, is this really only in if sections? Do we also have byte/short/... Literals ?

**Comment by FroMage** [comment]
Also, are literals documented ?

**Comment by mkouba** [comment]
> Also, are literals documented ?

https://quarkus.io/guides/qute-reference#literals

**Comment by mkouba** [comment]
> Well, is this really only in if sections?

No. You can use literals anywhere. But you can't use e.g. negative numbers as a standalone expression  `{-1.0f}` because `-` is not a [valid tag start](https://quarkus.io/guides/qute-reference#identifiers ).

> Do we also have byte/short/... Literals ?

No. There was no use case so far.

**Review by gastaldi — APPROVED** [review]

**Comment by FroMage** [comment]
Thanks!

**Pull request merged**
