### PR TITLE
Qute: Support iterating by number

### LINKED ISSUE #6963: Qute iterating by number
**Description**

Iterate by a number instead of by a list of elements.

**Implementation ideas**

```
{#repeat var.total}
   ...
{/repeat}
```

I think we could do things more complex like in FreeMarker but at least having this structure would help a lot in some cases.

### PR DESCRIPTION
**Pull request by gastaldi**
I reused the `for` instruction to iterate by number. Support for descending order is not yet implemented. Let me see how that works for you @lordofthejars 

Fixes #6963

### CODE REVIEW

**Comment by gastaldi** [comment]
Also feel free to reject/close this PR if it doesn't make sense @mkouba :)

**Comment by lordofthejars** [comment]
For me, it works really well as the only thing I want to do is print the number of stars depending on a rating number. So if it is 4 I just want to add 4 stars. The other thing as you said is the descending order but for now, if this is accepted I can work around the problem with not much effort.

Thank you very much.

**Comment by gastaldi** [comment]
> The other thing as you said is the descending order but for now, if this is accepted I can work around the problem with not much effort.

Yeah, you can always do a `total - i` instead of `i` if you want a descending order anyway :)

**Comment by mkouba** [comment]
@gastaldi looks good ;-).

> It seems like math expressions are not supported yet

Yep, complex expressions are not supported in loops.

By the way, you can also use the `{#each}` variant here, e.g. something like:
```
{#each movie.numberOfStars}
  ...print star
{/each}
```

**Comment by gastaldi** [comment]
Can we get this PR approved and merged in time for 1.3.0.Alpha1?

**Review by mkouba — APPROVED** [review]

**Comment by gsmet** [comment]
Just a small comment: let's not put pressure when none is needed. 1.3.0.Alpha1 is released for people to test the new class loading infra. We don't need to hurry to get this sort of fixes in: we can take our time to get a proper design if needed.

**Comment by gastaldi** [comment]
Hm, while reading the docs, I noticed that you could have also used an `IntStream` instead in an extension method: 

Eg.
```java 
public IntStream getMovies() {
   return IntStream.rangeClosed(1, getMoviesCount()); 
}
```

Anyway, I added some docs adding support for plain Integers, let me know what you guys think :)

**Comment by gsmet** [comment]
@mkouba could you review the doc?

**Comment by mkouba** [comment]
@gastaldi Yes, extension methods would work too, ie. something like:
```java
public static IntStream getMovieStars(Movie movie) {
   return IntStream.rangeClosed(1, movie.getStarsCount()); 
}
```
Anyway, I think it's ok to support this directly.

**Comment by DaHoC** [comment]
Proposing to also support iterating Long numbers: https://github.com/quarkusio/quarkus/pull/41679

**Pull request merged**
