### PR TITLE
Use similar options in Linux tests as Windows tests

### PR DESCRIPTION
**Pull request by geoand**
Hopefully this will fix our JDK 11 and JDK 14 CI issues

### CODE REVIEW

**Comment by aloubyansky** [comment]
fyi @glefloch

**Review by aloubyansky — APPROVED** [review]

**Comment by glefloch** [comment]
yes just saw that :)

**Comment by geoand** [comment]
Oh boy... OOM

**Comment by glefloch** [comment]
hmm but this time it's not in gradle tests

**Comment by geoand** [comment]
Yup, seems like we need to give it more memory. I'll update the PR soon

**Pull request merged**
