### PR TITLE
SmallRye GraphQL 1.6

### LINKED ISSUE #25808: Executing single-result GraphQL operations over websocket is broken in latest main branch
### Describe the bug

A single-result GraphQL operation (query, mutation) executed over websocket rather than a pure HTTP request fails:

```
java.lang.NullPointerException
		at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.runBlocking(QuarkusDefaultDataFetcher.java:99)
		at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.invokeAndTransform(QuarkusDefaultDataFetcher.java:33)
		at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:62)
		at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:87)
		at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279)
		at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210)
		at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:182)
		at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43)
		at graphql.execution.Async.eachSequentiallyImpl(Async.java:80)
		at graphql.execution.Async.eachSequentially(Async.java:69)
		at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38)
		at graphql.execution.Execution.executeOperation(Execution.java:160)
		at graphql.execution.Execution.execute(Execution.java:106)
		at graphql.GraphQL.execute(GraphQL.java:641)
		at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:561)
		at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
		at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556)
		at graphql.GraphQL.executeAsync(GraphQL.java:524)
		at io.smallrye.graphql.execution.ExecutionService.lambda$writeAsync$0(ExecutionService.java:176)
		at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
		at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
		at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
		at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:52)
		at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:112)
		at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:89)
		at io.smallrye.graphql.execution.ExecutionService.writeAsync(ExecutionService.java:178)
		at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:158)
		at io.smallrye.graphql.execution.ExecutionService.executeAsync(ExecutionService.java:99)
		at io.smallrye.graphql.execution.ExecutionService.executeAsync(ExecutionService.java:95)
		at io.smallrye.graphql.websocket.AbstractGraphQLWebsocketHandler.sendDataMessage(AbstractGraphQLWebsocketHandler.java:97)
		at io.smallrye.graphql.websocket.graphqltransportws.GraphQLTransportWSSubprotocolHandler.onMessage(GraphQLTransportWSSubprotocolHandler.java:42)
		at io.smallrye.graphql.websocket.AbstractGraphQLWebsocketHandler.onMessage(AbstractGraphQLWebsocketHandler.java:57)
		at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLOverWebSocketHandler.lambda$doHandle$3(SmallRyeGraphQLOverWebSocketHandler.java:53)
		at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handleTextFrame(WebSocketImplBase.java:620)
		at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:586)
		at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:575)
		at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
		at io.vertx.core.http.impl.WebSocketImplBase.receiveFrame(WebSocketImplBase.java:527)
		at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
		at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
		at io.vertx.core.http.impl.WebSocketImplBase.handleFrame(WebSocketImplBase.java:469)
		at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
		at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
		at io.vertx.core.http.impl.Http1xConnectionBase.handleWsFrame(Http1xConnectionBase.java:60)
		at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:163)
		at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:149)
		at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
		at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)

```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

latest main branch

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jmartisk**
fixes https://github.com/quarkusio/quarkus/issues/25808

### CODE REVIEW

**Comment by gsmet** [comment]
@jmartisk if the API is not compatible, I will need a new Jakarta RC too.

**Review by phillip-kruger — APPROVED** [review]
Thanks @jmartisk

**Comment by jmartisk** [comment]
@gsmet Sure, I'll release it right away then

**Comment by jmartisk** [comment]
@gsmet  here it is: https://repo.maven.apache.org/maven2/io/smallrye/smallrye-graphql/2.0.0.RC4/

**Review by gsmet — APPROVED** [review]

**Pull request merged**
