### PR TITLE
Upgrade to Kogito 0.5.1

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by gsmet** [comment]
@mswiderski CI is failing with:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.kogito.jbpm.OrdersProcessTest
08:47:11,765 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
08:47:12,258 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.327 s <<< FAILURE! - in io.quarkus.it.kogito.jbpm.OrdersProcessTest
[ERROR] testRuleEvaluation  Time elapsed: 0.016 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: 
TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [io.quarkus.it.kogito.jbpm.OrdersProcessTest]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
[2] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:858)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more

	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:300)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:275)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:258)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:252)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
[2] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:858)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more

	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:157)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:248)
	at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:390)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:285)
	... 47 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
[2] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:858)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more

	at io.quarkus.builder.Execution.run(Execution.java:108)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:130)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:111)
	... 50 more
Caused by: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
[2] Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:858)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "canDrinkKS")]
	- java member: io.quarkus.it.kogito.drools.CanDrinkResource#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.CanDrinkResource], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.CanDrinkResource]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.rules.impl.SessionUnit and qualifiers [@Named(value = "simpleKS")]
	- java member: io.quarkus.it.kogito.drools.HelloRuleService#ruleUnit
	- declared on CLASS bean [types=[io.quarkus.it.kogito.drools.HelloRuleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.it.kogito.drools.HelloRuleService]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
		... 14 more
```

**Comment by mswiderski** [comment]
yes, looking into it...

**Comment by gsmet** [comment]
Rebased and force-pushed to fix the doc generation issue.

**Comment by gsmet** [comment]
Closing, will be part of a larger PR.

**Comment by gsmet** [comment]
We had a Windows failure:
```
[ERROR] testThatTheKogitoApplicationRuns  Time elapsed: 85.536 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with io.quarkus.kogito.maven.it.KogitoDevModeIT was not fulfilled within 1 minutes.
	at io.quarkus.kogito.maven.it.KogitoDevModeIT.testThatTheKogitoApplicationRuns(KogitoDevModeIT.java:22)
Caused by: java.util.concurrent.TimeoutException
	at io.quarkus.kogito.maven.it.KogitoDevModeIT.testThatTheKogitoApplicationRuns(KogitoDevModeIT.java:22)
```

**Comment by gsmet** [comment]
@mswiderski I wasn't able to get this one in the release as we have a consistent Windows failure (see the message I pasted above).

Any chance you could have a look.

**Comment by mswiderski** [comment]
@gsmet yes, I am trying this to get it running on windows... though my windows machine is not the best so it takes time ... but I am certainly on it and it's prio 1 for me

**Comment by gsmet** [comment]
Ok, thanks!

**Comment by mswiderski** [comment]
@gsmet the windows failure is now fixed, the failed job seems to be not related as it is timeout on Gradle download.

````
[INFO] --- exec-maven-plugin:1.6.0:exec (gradle) @ quarkus-gradle-plugin ---
Downloading https://services.gradle.org/distributions/gradle-5.6.3-bin.zip
Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
````

**Comment by gsmet** [comment]
@mswiderski I just force pushed a change to fix a formatting issue and add the jakarta.annotation dependency. It's not good practice to count on the other part of the framework to provide it.

Let's wait for CI to go green!

**Comment by gsmet** [comment]
Looks green enough to me. I'll merge.

@mswiderski thanks!

**Review by gsmet — APPROVED** [review]

**Pull request merged**
