### PR TITLE
Remove Caffeine's UnsafeRefArrayAccess

### LINKED ISSUE #25125: Explore removing Caffeine's UnsafeRefArrayAccess
### Description

While doing some research, I've discovered that Caffeine is no longer using Unsafe. In https://github.com/ben-manes/caffeine/commit/e4b77d2527e54959050fd0b48b5364714164309a, Caffeine moved its copy of `MpscGrowableArrayQueue` to use either Unsafe, or if not available, VarHandle. Then, with https://github.com/ben-manes/caffeine/commit/4db9e8e360d838d979b9ee10f8a86bcb3b77f045, Unsafe was completely removed and VarHandle is only in use.

This means that [`UnsafeRefArrayAccess`](https://github.com/quarkusio/quarkus/blob/main/extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/UnsafeRefArrayAccess.java) should no longer be needed. I'm not aware of VarHandles requiring extra handling.

### Implementation ideas

Upgrade to a Caffeine version that includes the 2 commits mentioned above. The minimum version that includes both is `3.0.2`. At the time of writing, the latest version is `3.0.6`.

Then, remove `UnsafeRefArrayAccess` and see if Caffeine dependant native CI tests fail.

When `UnsafeRefArrayAccess` was not in place, you'd get a segmentation fault during runtime native execution, as a result of native offset that is runtime dependant being wrongly baked at build time.

### PR DESCRIPTION
**Pull request by ejba**
Fixes #25125

### CODE REVIEW

**Comment by gsmet** [comment]
I converted this PR to draft for now. Please make sure things build locally and also run the tests of this extension (and the IT of the extension in native too). Then you can promote it!

**Comment by ejba** [comment]
Oops sorry @gsmet!

**Comment by galderz** [comment]
Thx @ejba for giving this a go! CI shows a compilation failing:

```
Error:  /home/runner/work/quarkus/quarkus/integration-tests/cache/src/main/java/io/quarkus/it/cache/CaffeineResource.java:[56,9] method does not override or implement a method from a supertype
```

**Comment by gwenneg** [comment]
I checked all caffeine 3.0.x release notes. The bump from `2.9.3` to `3.0.6` looks safe to me from a `quarkus-cache` perspective.

**Comment by galderz** [comment]
Thx @gwenneg. Infinispan is currently the roadblock. See my [comment](https://github.com/quarkusio/quarkus/issues/25125#issuecomment-1109962543).

**Comment by geoand** [comment]
@galderz @gwenneg can you now review this please?

I have rebased it onto `main` and checked that the tests pass.

**Comment by galderz** [comment]
@geoand It appears that the upgrade to Infinispan 14 has not aligned the caffeine version? Quarkus still sets Caffeine 2.9.3 https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L135, which uses unsafe. Infinispan 14.x is on 3.1.1 https://github.com/infinispan/infinispan/blob/14.0.x/build/configuration/pom.xml#L135 - @karesti / @geoand some leftover work to do on that upgrade?

**Comment by geoand** [comment]
Thanks @galderz.

I can certainly bump the caffeine version, but it should probably be left to @karesti and / or @gwenneg who know this area

**Comment by gwenneg** [comment]
> I checked all caffeine 3.0.x release notes. The bump from `2.9.3` to `3.0.6` looks safe to me from a `quarkus-cache` perspective.

My comment still stands for Caffeine 3.1.1 ☝️

**Comment by galderz** [comment]
> > I checked all caffeine 3.0.x release notes. The bump from `2.9.3` to `3.0.6` looks safe to me from a `quarkus-cache` perspective.
> 
> My comment still stands for Caffeine 3.1.1 ☝️

@gwenneg Can you send a separate PR for that upgrade then? Any thoughts @karesti?

**Comment by geoand** [comment]
> Shall I submit a new PR based on this one with an additional commit for the bump?

Sure yeah

**Pull request closed without merging**
