### PR TITLE
Qute: make TemplateNode part of the public API

### PR DESCRIPTION
**Pull request by mkouba**
- so that it's possible to analyze the parsed template tree during build and at runtime

### CODE REVIEW

**Comment by ia3andy** [comment]
> @ia3andy pls let me know if this API is good enough for your use case.

I don't think I'll be able to tackle this anytime soon, it's hard to know without actually starting :-/

**Comment by ia3andy** [comment]
As soon as I can know if a tag is used and the params it is used with (when accessible), that should be fine?

**Comment by mkouba** [comment]
> > @ia3andy pls let me know if this API is good enough for your use case.
> 
> I don't think I'll be able to tackle this anytime soon, it's hard to know without actually starting :-/

I see. In that case, we can merge this pull request (once we have a review from @gastaldi) and improve it later - based on your feedback.

**Comment by mkouba** [comment]
> As soon as I can know during deployment if a tag is used and the params it is used with (when accessible), that should be fine?

Yes, that should be doable. You will need to consume the `TemplatesAnalysisBuildItem` and then for each `TemplateAnalysis` do something like https://github.com/quarkusio/quarkus/pull/41273/files#diff-cefd9e0cd3cd633f1d4b263635312f76c9283f59084a51358687cd2fe6f232b0R50-R58.

**Review by gastaldi — APPROVED** [review]
LGTM

**Pull request merged**
