### PR TITLE
1.11.7 backports infra

### PR DESCRIPTION
**Pull request by gsmet**
This is a test to backport some infrastructure related changes to 1.11 as Kafka tests don't work there anymore either.

Please don't merge, I will merge it myself.

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier so... the build passes. It's a lot more changes than I'm usually comfortable to backport but... I think we don't have better options. Do you agree?

**Comment by rsvoboda** [comment]
@pjgg please check these changes

**Comment by gsmet** [comment]
To give a bit more context: the main part of this PR is to backport the Kafka tests fixes that @cescoffier did. I'm not sure it's really doable for someone outside of the Kafka world to thoroughly review this so it was more for your awareness. Anyway, another pair of eyes can't hurt :).

**Comment by gsmet** [comment]
Alternative is that CI doesn't work anymore in 1.11 as the Kafka tests aren't passing anymore.

**Comment by pjgg** [comment]
I've run Kafka Beefy scenarios against this branch `gsmet:1.11.7-backports-infra` and LGTM.

Scenarios:

[Kafka AVRO](https://github.com/quarkus-qe/beefy-scenarios/tree/main/301-quarkus-vertx-kafka): `mvn -V -B clean compile verify -pl 301-quarkus-vertx-kafka`

[Kafka Streams](https://github.com/quarkus-qe/beefy-scenarios/tree/main/012-quarkus-kafka-streams): ` mvn -V -B clean compile verify -pl 012-quarkus-kafka-streams`

**Comment by gsmet** [comment]
OK, thanks. I will merge it so that we can make progress on 1.11.

**Pull request merged**
