### PR TITLE
Enable buildx support in docker container image extension

### PR DESCRIPTION
**Pull request by edeandrea**
This was spawned from the conversation in #25467 - a way to pass additional arguments to the `container-image-docker` build process.

### CODE REVIEW

**Comment by edeandrea** [comment]
Do you see anything wrong with the way I added this to `DockerConfig`? Basically just allow what the config says to "pass through" to the executable. Or would you see that as a potential security hole (i.e. injection)?

```java
/**
  * Additional command line arguments to be passed to the {@link #executableName}.
 */
@ConfigItem
public Optional<List<String>> additionalCommandArgs;
```

I thought about just adding a `platform` config item specifically, but that option *ONLY* exists if you're using `docker buildx build`.

Happy to have a conversation and/or change things up based on discussion.

**Comment by geoand** [comment]
What is buildx?

If we can avoid having catch-all configuration, I would prefer it.

**Comment by edeandrea** [comment]
> What is buildx?

https://docs.docker.com/buildx/working-with-buildx

Its used to build multi-arch images.

**Comment by geoand** [comment]
I'll have to take a look and get back to you

**Comment by edeandrea** [comment]
See https://github.com/quarkusio/quarkus-super-heroes/blob/main/.github/workflows/build-push-container-images.yml#L81-L89 as well. With this change I wouldn't have to use the buildx github action. I could just use `mvn package` (like I was doing before building multi-arch images).

**Comment by edeandrea** [comment]
> I'll have to take a look and get back to you

Sounds good. Happy to chat about it more and what you think the best approach would be. I agree having a "catch-all" that blindly appends things to the command line isn't the best idea.

We would instead use a `platform` config attribute, which if configured could reconfigure `executableName` to be `docker buildx` instead of just `docker`. That's another idea.

**Comment by geoand** [comment]
> See https://github.com/quarkusio/quarkus-super-heroes/blob/main/.github/workflows/build-push-container-images.yml#L81-L89 as well. With this change I wouldn't have to use the buildx github action. I could just use `mvn package` (like I was doing before building multi-arch images).

How does `buildx` come into play in this case? Is it automatically added because `platform` was specified?

**Comment by geoand** [comment]
> We could instead use a platform config attribute, which if configured could reconfigure executableName to be docker buildx instead of just docker (and of course document it). That's another idea.

I don't think this is correct, because the executable is still `docker` isn't it? IIUC, what needs to be done is to add `buildx` if `platform` is specified, no?

**Comment by edeandrea** [comment]
Buildx is a plugin to the docker command, so you would run the command `docker buildx --platform ...`. There's also a GitHub action which sets it up (see https://github.com/quarkusio/quarkus-super-heroes/blob/ebfcf21d7d880595358d475f4dfc0fad51cfeb31/.github/workflows/build-push-container-images.yml#L76 and https://github.com/docker/setup-buildx-action). The `install` parameter in the action essentially creates a symlink so that `docker` -> `docker buildx`. 

So in that use case where you are using the GitHub action with `install=true`, setting the `executableName` to `docker buildx` would actually not be correct.

Maybe the thing to do is to introduce the new `platform` parameter and if it is set, then check what the `exefutableName` is. If it's anything other than `docker` then fail the build and notify the user that they have conflicting settings that they need to fix. This way we aren't making assumptions on what the user is trying to do.

I'm not sure we could (or should) test that they have `docker` symlinked to `docker buildx`. The only way to really know would be to run the `docker` command and parse the output of it in some way.

**Comment by geoand** [comment]
I think the simplest and most reasonable thing to do is add a `platform` parameter to our Docker configuration and then alter the code that handles it to also add `buildx` when `platform` is present

**Comment by edeandrea** [comment]
> I think the simplest and most reasonable thing to do is add a `platform` parameter to our Docker configuration and then alter the code that handles it to also add `buildx` when platform is present

I agree. If we do this, though, and the user in the workflow sets the action to `install=true` then this will cause the docker command to fail. The user will have to go back and fix their workflow.

I don't think that is the majority use case though. If you simply run `docker build` and pass the `--platform` flag, the build will run and the flag will be ignored, therefore succeffully producing a container image that isn't of the arch you expected. I think thos is the more important use case to guard against.

I also think we should take it 1 step further. If the `--platform` parameter is set, then we should check what the `executableName` is. If it's anything other than `docker` (maybe they're using `podman`) then we should fail the build and notify the user that they have conflicting settings that they need to fix.

And of course, all of this will be documented in the documentation :)

**Comment by edeandrea** [comment]
@geoand are there tests anywhere in the codebase that test all these config options and make sure the correct `docker build` command is run?

**Comment by geoand** [comment]
Nope, but you can certainly add some

**Comment by edeandrea** [comment]
Something I just thought of. There are a bunch of options that buildx supports (https://docs.docker.com/engine/reference/commandline/buildx_build/#options). Some of these are just carry-over from the generic `docker build`, but others (like the output) are specific to buildx.

Instead of a single `platform` property (i.e. `quarkus.docker.platform`, what about a set of nested properties specific for buildx (`quarkus.docker.buildx.*`). I don't think we need to support every option right now. For now, maybe just `platform` and [`output`](https://docs.docker.com/engine/reference/commandline/buildx_build/#output)?

Output is important because docker buildx can only load created images into `docker images` if doing a single-arch build.

WDYT @geoand ?

**Comment by geoand** [comment]
I like the idea

**Comment by geoand** [comment]
Once everything is done, we'll definitely need the commits in better shape :)

**Comment by edeandrea** [comment]
I'm done :) they can be squashed when merged? The file browser at the top combines all the commits so you can just see the changes.

**Comment by edeandrea** [comment]
I'm done :) they can be squashed when merged? The file browser at the top combines all the commits so you can just see the changes.

**Comment by edeandrea** [comment]
I'm done coding. On the PR you can look on the top at the file browser. It combines the commits.

I tried to rebase to a single commit but something got messed up when I merged main back in.

**Comment by geoand** [comment]
We'll need the commits merged, as we require semantic commits in Quarkus and a repository that builds properly at any commit.

My request does not have to do with viewing the changes

**Comment by edeandrea** [comment]
I'll take care of it on Monday.

**Comment by edeandrea** [comment]
@geoand I'm not sure what happened here. I went to try to rebase all the commits into a single commit and also rebase main on top but things got messed up, so instead I opened #25589. I'm closing this one in favor of that one.

**Pull request closed without merging**
