### PR TITLE
Infinispan Extension adds SASL to reflective classes

### LINKED ISSUE #41677: Infinispan extension needs to include Wildly SASL providers in the native executable
In some cases, Infinispan cannot start on FIPS enabled system and with Native mode. We need to include these classes to be loaded in the native executable. 

            "org.wildfly.security.sasl.plain.WildFlyElytronSaslPlainProvider",
            "org.wildfly.security.sasl.digest.WildFlyElytronSaslDigestProvider",
            "org.wildfly.security.sasl.external.WildFlyElytronSaslExternalProvider",
            "org.wildfly.security.sasl.oauth2.WildFlyElytronSaslOAuth2Provider",
            "org.wildfly.security.sasl.scram.WildFlyElytronSaslScramProvider",
            "org.wildfly.security.sasl.gssapi.WildFlyElytronSaslGssapiProvider",
            "org.wildfly.security.sasl.gs2.WildFlyElytronSaslGs2Provider"

### PR DESCRIPTION
**Pull request by karesti**
Closes #41677

### CODE REVIEW

**Comment by karesti** [comment]
@tristantarrant here

**Comment by karesti** [comment]
@ryanemerson

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
I wonder if at some point they shouldn't be moved to an Elytron extension but we can start with that and see how it goes.

**Comment by gsmet** [comment]
Thanks!

**Comment by gastaldi** [comment]
Can this be backported to 3.8? Asking because of QUARKUS-4612

**Comment by karesti** [comment]
@gastaldi I can deal with the backport if this is ok

**Comment by gsmet** [comment]
Let's push it in the next 3.12 first, then we can talk. I added the backport labels.

**Comment by karesti** [comment]
@gsmet thanks Guillaume!

**Pull request merged**
