### PR TITLE
LinksProcessor ID field error for native class HalCollectionWrapper

### LINKED ISSUE #38543: LinksProcessor ID field error for native class HalCollectionWrapper
### Describe the bug

Hello,

When I upgrade quarkus from 3.6.9 to 3.7.1 PR @bpasson https://github.com/quarkusio/quarkus/pull/38265/files is causing the following issue.

My entity is :

    import io.quarkus.resteasy.reactive.links.RestLinkId;
    
    @Getter
    @AllArgsConstructor
    @NoArgsConstructor
    public class Car
    {
    
       @RestLinkId
       private int id;
       private int year;
       private String make;
       private String model;
    }

In my controller I have : 

      Collection<Object> objectCollection = returnCars.stream().map(car -> (Object)car).collect(Collectors.toList());
      HalCollectionWrapper halCollection = resteasyReactiveHalService.toHalCollectionWrapper(objectCollection,"result_page_"+pageRequest.getPage()+"_size_"+pageRequest.getSize(),
               Car.class);

When the app starts I get:

        2024-02-01 16:46:50,992 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	        [error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:268)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateClassHasFieldId(LinksProcessor.java:232)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:151)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:76)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	        at java.base/java.lang.Thread.run(Thread.java:840)
	        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
	        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
	        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
        Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	        [error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:268)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateClassHasFieldId(LinksProcessor.java:232)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:151)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:76)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	        at java.base/java.lang.Thread.run(Thread.java:840)
	        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        
	        at io.quarkus.builder.Execution.run(Execution.java:123)
	        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	        ... 9 more
        Caused by: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:268)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateClassHasFieldId(LinksProcessor.java:232)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:151)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:76)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	        at java.base/java.lang.Thread.run(Thread.java:840)
	        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        
        

### Expected behavior

Since my entity is marked with `RestLinkId` and I am using quarkus's `io.quarkus.hal.HalCollectionWrapper` I should not have received `io.quarkus.resteasy.reactive.links.deployment.LinksProcessor` 's IllegalStateException. HalCollectionWrapper and HalEntityWrapper should be excluded from the Id check.

### Actual behavior

I end up getting 

    java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation

### How to Reproduce?

1. Create an entity with RestLinkId annotation
2. Create a controller method like 

     `@GET`
     `@Produces({ MediaType.APPLICATION_JSON, RestMediaType.APPLICATION_HAL_JSON })`
     `@RestLink(rel = "list")`
     `@InjectRestLinks`
       public HalCollectionWrapper getCars(@BeanParam PageRequest pageRequest, @Context UriInfo uriInfo)
       {
          List<Car> returnCars = Cars.cars();
    

         Collection<Object> objectCollection = returnCars.stream().map(car -> (Object)car).collect(Collectors.toList());
      
        HalCollectionWrapper halCollection = resteasyReactiveHalService.toHalCollectionWrapper(objectCollection,"result_page_"+pageRequest.getPage()+"_size_"+pageRequest.getSize(),
         Car.class);

          halCollection.addLinks(Link.fromPath(uriInfo.getAbsolutePath().toString()+"?page="+(pageRequest.getPage()+1)+"size="+pageRequest.getSize()).rel("next_page_url").build());

          halCollection.addLinks(Link.fromPath(uriInfo.getAbsolutePath().toString()+"?page=1&size=20").rel("first_page_url").build());

         halCollection.addLinks(Link.fromPath(uriInfo.getAbsolutePath().toString()).rel("list").build());

         return halCollection;
       }
4. Run application

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### Quarkus version or git rev

3.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.5

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bpasson**
Fixes #38543 - LinksProcessor ID field error for native class HalCollectionWrapper

### CODE REVIEW

**Comment by bpasson** [comment]
@Sgitario this is a draft PR. Which I would like you to have a look at. There is still one issue to be solved. The Jsonb serializers don't seem to be triggered any more since the HalWrapper types got added a type argument. The Jackson serializer works correctly. I think the typed HalWrappers no longer are matched against the serializer, but why this happens I do not know. Looking at eclipse yasson it should work. Do you have any idea?

**Review by Sgitario — COMMENTED** [review]
I have a doubt about what is the value of changing the HalEntityWrapper and the HalCollectionWrapper classes to include the parametrized type.

If I understood the changes correctly, you're proposing to use the HalService to create the wrappers which is perfectly fine (this is a change of behaviour that would need to be noted in the migration guide though). 

My doubt is why we need to include the parameterized type.

**Comment by bpasson** [comment]
We need the parameterized type to be able to determine the wrapped type which needs to be scanned for `id` field, `@RestLinkId` annotation or `@Id` annotation or the build will fail with an exception stating it can't find any of those. Further more we need to scan the class to be able to implement getters for all path variables used. The id field for instance is used for the 'self' link. If we don't do that those never get rendered.

**Comment by geoand** [comment]
> @geoand any hints about the jsonb failures?

I can't think of anything off hand. I would start by looking backwards to where the working Jackson ones are being called and comparing with that with the Jsonb ones to see what is different

**Comment by bpasson** [comment]
@geoand @Sgitario I did a backtrace and the normaly I would expect `io.quarkus.jsonb.JsonbProducer#jsonbConfig()` to be called which adds the serializer. But it seems this does not happen. Could this be due to the fact I added a test dependency on quarkus-hal-deployment to be able to use the wrapper classes in a testcase?

**Comment by geoand** [comment]
> Could this be due to the fact I added a test dependency on quarkus-hal-deployment to be able to use the wrapper classes in a testcase?

Have you tried without it?

**Comment by bpasson** [comment]
I can check if the producer is called without the dependency but I will have to remove the extra testcases as they use the wrapper classes. Will post the results of my findings here.

**Comment by bpasson** [comment]
@geoand @Sgitario I did some testing and have the idea the problem is a bug in eclipse yasson. I tried the following definitions of the serializer:

1 `HalCollectionWrapperJsonbSerializer implements JsonbSerializer<HalCollectionWrapper<?>>` which fails.
2 `HalCollectionWrapperJsonbSerializer implements JsonbSerializer<HalCollectionWrapper>` which works.

It looks eclipse yasson has an issue with serializers and probably deserializers when the root type is generic. Maybe it is related or the same as https://github.com/eclipse-ee4j/yasson/issues/243 which is fixed, but that seemed to target annotated serializers / deserializers. These are added though configuration.

I've updated the PR to use the raw typed serializers as that works. I'll report an issue with eclipse yasson and update the comment in the serializers to reference that issue.

What do you think?

**Comment by geoand** [comment]
Sounds good to me!

Thanks for looking into it.

**Comment by bpasson** [comment]
@geoand I updated the PR to point to https://github.com/eclipse-ee4j/yasson/issues/639 for as why the use of raw types in the Jsonb serializers. 

@Sgitario How can I add something to the migration guide?

**Comment by Sgitario** [comment]
> @Sgitario How can I add something to the migration guide?

Here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9
If you don't have permission, drop the content here and I can add it for you.

**Comment by Sgitario** [comment]
Many thanks for your changes here @bpasson !

> > @Sgitario How can I add something to the migration guide?
> 
> Here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9 If you don't have permission, drop the content here and I can add it for you.

**Comment by bpasson** [comment]
@Sgitario this probably needs to be backported to 3.7 as it is broken there atm.

**Comment by bpasson** [comment]
@Sgitario a side note here. The type validation expects the find the `id`, `@RestlInkId` or `@Id` on the first level. You could theoretically do `HalCollectionWrapper<Collection<Record>>` but that will fail, as was already failing previously.

**Review by Sgitario — APPROVED** [review]
lgtm!

**Comment by Sgitario** [comment]
> @Sgitario a side note here. The type validation expects to find the `id`, `@RestlInkId` or `@Id` on the first level. You could theoretically do `HalCollectionWrapper<Collection<Record>>` but that will fail, as was already failing previously.
> 
> Can you also remove the label `area/infinispan`? This got added when I let GitHub update the branch. It defaults to merge commit in stead of rebase.

Item added into the migration guide. I've renamed a bit the title to match the section in the guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-adding-web-links-programmatically

I've updated the labels as well.

cc @geoand

**Comment by bpasson** [comment]
@geoand @Sgitario many thanks for the fast support on my questions getting this fixed.

**Comment by geoand** [comment]
Thank you for the contribution n

**Pull request merged**
