### PR TITLE
Gradle: inject test resources before the main resources for testing

### LINKED ISSUE #8845: SmallRyeConfig picks up application.properties from src/main/resources during testing instead of src/test/resources
**Describe the bug**
Quarkus is picking up the `application.properties` file from `src/main/resources` during testing instead of `src/test/resources`.

**Expected behavior**
`./gradlew build --info` passes

**Actual behavior**
`./gradlew build --info` fails with:
```
...
java.util.NoSuchElementException: Property MY_PROD_ENV_VAR not found
  at io.smallrye.config.SmallRyeConfig.propertyNotFound(SmallRyeConfig.java:209)
  at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:96)
  at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:80)
  at io.quarkus.runtime.configuration.ConfigExpander.accept(ConfigExpander.java:55)
  at io.quarkus.runtime.configuration.ConfigExpander.accept(ConfigExpander.java:15)
  at org.wildfly.common.expression.ExpressionNode.emit(ExpressionNode.java:42)
  at org.wildfly.common.expression.Expression.evaluateException(Expression.java:75)
  ...
```

**To Reproduce**
`./gradlew build --info`

[Reproducer available here.](https://github.com/marc-christian-schulze/quarkus-reproducer-8845)

**Additional context**
This is a regression introduced with Quarkus 1.4.0.Final. Testing the very same example with Quarkus 1.4.0.CR1 works.

### LINKED ISSUE #8901: Test DataSource not used in 1.4.1.Final
**Describe the bug**
Tests use only the DataSource configured in main resources instead of the one in test resources.

**Expected behavior**
The in-memory DataSource configured in the test resources is used like in 1.4.0.CR1 and before.

**Actual behavior**
The in-memory test resource H2 database is started but agroal is configured to use main resources PostgreSQL DataSource.

**To Reproduce**
1. Configure a data source in main resources.
2. Configure a data source in test resources.
3. Shutdown main data base.
4. Execute tests accessing the database.

**Configuration**
Main application.properties:
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:2345/test-db
quarkus.datasource.username = postgres
quarkus.datasource.password = secret
```
Test application.properties:
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.url = jdbc:h2:tcp://localhost/mem:test-db;MODE=PostgreSQL
quarkus.datasource.driver = org.h2.Driver
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux voyager 5.6.7-arch1-1 #1 SMP PREEMPT Thu, 23 Apr 2020 09:13:56 +0000 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.3

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #8845 
Fixes #8901

### CODE REVIEW

**Comment by aloubyansky** [comment]
Hm, I noticed a difference in how I implemented this for Gradle vs how it seems to work for Maven currently.
In Maven, `application.properties` from the test resources dir seems to replace the main `application.properties`.
While in Gradle (in this PR) `application.properties` from the test resources is added a dominating config source.
So, we need to decide what's more appropriate. I tend to prefer the way it's implemented in this PR. However, it'll be a breaking change.

**Comment by aloubyansky** [comment]
I should probably re-work it so the main application.properties is completely replaced with the one from the test. Partial overrides are supported using profiles.

**Comment by aloubyansky** [comment]
Ok, I've re-worked it to replace the main application.properties

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by mklueh** [comment]
Does that mean it'll replace the entire file contents so you have to have your whole production application properties duplicated if you just want to change one single property for your tests? I was always under the impression that it is kind of merged and the test properties that are defined will overwrite those that are given in the main application.properties

**Comment by aloubyansky** [comment]
Yes, it is completely replaced. We thought that with profiles you already have a way to override properties selectively. And it is also consistent with how it works in Maven.

**Pull request merged**
