### PR TITLE
Fix broken main

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@aloubyansky @famod we have seen this problem before, no?

How do we overcome it? This PR is actually needed because `main` is currently broken.

**Review by cescoffier — CHANGES_REQUESTED** [review]
Many of these dependencies have been moved to quarkiverse. So, they should not be there anymore.

**Comment by geoand** [comment]
The changes were made by running the `update-extension-dependencies.sh` script, so I don't really know how to proceed

**Comment by geoand** [comment]
Pushed an update... Let's see what happens

**Review by aloubyansky — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Comment by famod** [comment]
Not sure where buildpack is coming from (it's new, right?) but we already had a report a few days ago and #22993 contains a quickfix.

**Comment by geoand** [comment]
> Not sure where buildpack is coming from (it's new, right?)

Yup it is.

The problem I had when I first pushed this fix was that the script resulted in adding a lot of new dependencies, which have been moved to Quarkiverse.
Following @cescoffier's advice, after cleaning `.m2`, the script resulted in the proper entries being added

**Pull request merged**
