### PR TITLE
Use HTTPS for the elytron-undertow tests

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Tests for #11616

### CODE REVIEW

**Comment by gsmet** [comment]
Native image is failing with:
```
2020-08-26T01:35:48.5298363Z 2020-08-26 01:35:48,416 ERROR [io.qua.application] (main) Failed to start application (with profile prod): java.nio.file.NoSuchFileException: server-cert.pem
2020-08-26T01:35:48.5298512Z 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
2020-08-26T01:35:48.5298620Z 	at java.nio.file.Files.newByteChannel(Files.java:370)
2020-08-26T01:35:48.5298745Z 	at java.nio.file.Files.newByteChannel(Files.java:421)
2020-08-26T01:35:48.5298887Z 	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
2020-08-26T01:35:48.5299022Z 	at java.nio.file.Files.newInputStream(Files.java:155)
2020-08-26T01:35:48.5299167Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.getFileContent(VertxHttpRecorder.java:646)
2020-08-26T01:35:48.5299315Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.createPemKeyCertOptions(VertxHttpRecorder.java:655)
2020-08-26T01:35:48.5299465Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.createSslOptions(VertxHttpRecorder.java:564)
2020-08-26T01:35:48.5299606Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:431)
2020-08-26T01:35:48.5299745Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:220)
2020-08-26T01:35:48.5300115Z 	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket-2064782366.deploy_0(VertxHttpProcessor$openSocket-2064782366.zig:136)
2020-08-26T01:35:48.5300458Z 	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket-2064782366.deploy(VertxHttpProcessor$openSocket-2064782366.zig:40)
2020-08-26T01:35:48.5300588Z 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:620)
2020-08-26T01:35:48.5300717Z 	at io.quarkus.runtime.Application.start(Application.java:90)
2020-08-26T01:35:48.5300847Z 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:92)
2020-08-26T01:35:48.5300975Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
2020-08-26T01:35:48.5301095Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
2020-08-26T01:35:48.5301212Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
2020-08-26T01:35:48.5301334Z 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

Do we automatically add the certificate files to the native image?

**Comment by stuartwdouglas** [comment]
Native should be fixed now. Turns out we don't have any native SSL tests so some pieces were missing.

**Comment by gsmet** [comment]
Force pushed a rebase.

**Comment by gsmet** [comment]
JVM tests are now failing with:
```
2020-08-30T17:55:36.4033304Z [INFO] Running io.quarkus.it.undertow.elytron.WebXmlPermissionsTestCase
2020-08-30T17:55:36.4037186Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in io.quarkus.it.undertow.elytron.WebXmlPermissionsTestCase
2020-08-30T17:55:36.4039685Z [ERROR] io.quarkus.it.undertow.elytron.WebXmlPermissionsTestCase  Time elapsed: 0.002 s  <<< ERROR!
2020-08-30T17:55:36.4043586Z java.lang.NullPointerException
2020-08-30T17:55:36.4049767Z 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:721)
2020-08-30T17:55:36.4051653Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptAfterAllMethod(QuarkusTestExtension.java:713)
2020-08-30T17:55:36.4053876Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-08-30T17:55:36.4056153Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-08-30T17:55:36.4059180Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-08-30T17:55:36.4065265Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-08-30T17:55:36.4066634Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
2020-08-30T17:55:36.4069332Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterAllMethod(TimeoutExtension.java:116)
2020-08-30T17:55:36.4072218Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-08-30T17:55:36.4076757Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-08-30T17:55:36.4079239Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-08-30T17:55:36.4082604Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-08-30T17:55:36.4085254Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-08-30T17:55:36.4087163Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-08-30T17:55:36.4089951Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-08-30T17:55:36.4092183Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-08-30T17:55:36.4093305Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllMethods$10(ClassBasedTestDescriptor.java:403)
2020-08-30T17:55:36.4093639Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-30T17:55:36.4094409Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllMethods$11(ClassBasedTestDescriptor.java:401)
2020-08-30T17:55:36.4094715Z 	at java.util.ArrayList.forEach(ArrayList.java:1259)
2020-08-30T17:55:36.4094991Z 	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
2020-08-30T17:55:36.4095289Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllMethods(ClassBasedTestDescriptor.java:401)
2020-08-30T17:55:36.4095593Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:209)
2020-08-30T17:55:36.4095883Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:78)
2020-08-30T17:55:36.4096335Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:145)
2020-08-30T17:55:36.4097978Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-30T17:55:36.4100668Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:145)
2020-08-30T17:55:36.4102029Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-08-30T17:55:36.4103847Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-08-30T17:55:36.4106890Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-30T17:55:36.4111044Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-08-30T17:55:36.4114656Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-08-30T17:55:36.4118877Z 	at java.util.ArrayList.forEach(ArrayList.java:1259)
2020-08-30T17:55:36.4122082Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-08-30T17:55:36.4124995Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-08-30T17:55:36.4125972Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-30T17:55:36.4127096Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-08-30T17:55:36.4128326Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-08-30T17:55:36.4129283Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-08-30T17:55:36.4132244Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-30T17:55:36.4134230Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-08-30T17:55:36.4136611Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-08-30T17:55:36.4138345Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-08-30T17:55:36.4140771Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-08-30T17:55:36.4144284Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-08-30T17:55:36.4154248Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
2020-08-30T17:55:36.4154401Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
2020-08-30T17:55:36.4154529Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
2020-08-30T17:55:36.4154673Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
2020-08-30T17:55:36.4154807Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
2020-08-30T17:55:36.4154949Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2020-08-30T17:55:36.4155110Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2020-08-30T17:55:36.4155312Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2020-08-30T17:55:36.4155460Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2020-08-30T17:55:36.4155600Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2020-08-30T17:55:36.4155736Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2020-08-30T17:55:36.4156216Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2020-08-30T17:55:36.4156350Z 	Suppressed: org.opentest4j.TestAbortedException: Boot failed
2020-08-30T17:55:36.4156634Z 		at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:533)
2020-08-30T17:55:36.4156772Z 		at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:583)
2020-08-30T17:55:36.4156921Z 		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-08-30T17:55:36.4157140Z 		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-08-30T17:55:36.4157291Z 		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-08-30T17:55:36.4157432Z 		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-08-30T17:55:36.4157577Z 		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
2020-08-30T17:55:36.4157878Z 		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
2020-08-30T17:55:36.4158021Z 		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-08-30T17:55:36.4158157Z 		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-08-30T17:55:36.4158297Z 		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-08-30T17:55:36.4158439Z 		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-08-30T17:55:36.4158580Z 		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-08-30T17:55:36.4158708Z 		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-08-30T17:55:36.4158841Z 		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-08-30T17:55:36.4158972Z 		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-08-30T17:55:36.4159115Z 		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$8(ClassBasedTestDescriptor.java:375)
2020-08-30T17:55:36.4159255Z 		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-30T17:55:36.4159395Z 		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:373)
2020-08-30T17:55:36.4159535Z 		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:193)
2020-08-30T17:55:36.4159677Z 		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
2020-08-30T17:55:36.4159815Z 		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
2020-08-30T17:55:36.4159949Z 		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-30T17:55:36.4160084Z 		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-08-30T17:55:36.4160203Z 		... 30 more
2020-08-30T17:55:36.4160303Z 	[CIRCULAR REFERENCE:org.opentest4j.TestAbortedException: Boot failed]
```

**Comment by gsmet** [comment]
Unfortunately, we now have a conflict.

**Review by gsmet — APPROVED** [review]
Failing test is unrelated and already fixed in master.

**Pull request merged**
