### PR TITLE
Remove gradletestkit from native test

### PR DESCRIPTION
**Pull request by glefloch**
Use gradle wrapper for native test instead of the Gradle test kit API. 

@aloubyansky can you have a look ?

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
The failures seem to be related.

**Comment by geoand** [comment]
Output is:

```
2020-06-15T20:58:26.3030471Z Starting a Gradle Daemon (subsequent builds will be faster)
2020-06-15T20:58:34.5085312Z > Task :clean UP-TO-DATE
2020-06-15T20:58:34.5098496Z > Task :compileJava NO-SOURCE
2020-06-15T20:58:34.5098978Z > Task :pluginDescriptors
2020-06-15T20:58:34.5099603Z > Task :processResources NO-SOURCE
2020-06-15T20:58:34.5099895Z > Task :classes UP-TO-DATE
2020-06-15T20:58:44.0029942Z > Task :pluginUnderTestMetadata
2020-06-15T20:59:13.4029517Z > Task :compileTestJava
2020-06-15T20:59:13.6029735Z > Task :processTestResources
2020-06-15T20:59:13.6030205Z > Task :testClasses
2020-06-15T20:59:43.6029870Z > Task :nativeTest
2020-06-15T20:59:45.0043612Z 
2020-06-15T20:59:45.0044508Z BasicJavaNativeBuildTest > shouldBuildNativeImage() FAILED
2020-06-15T20:59:45.0044961Z     java.lang.AssertionError at BasicJavaNativeBuildTest.java:25
```

**Comment by glefloch** [comment]
humm that's weird, it's ok on my machine. I'm investigating.

**Comment by glefloch** [comment]
Still having issues with the windows build..

**Pull request merged**
