### PR TITLE
Upgrading bouncycastle to 1.68

### PR DESCRIPTION
**Pull request by harshmadhani**
The fix is already present in master and backported to 1.11. Adding it to 1.10

### CODE REVIEW

**Comment by sberyozkin** [comment]
@harshmadhani it is `1.68` now

**Comment by gsmet** [comment]
I don't plan on releasing any new 1.10.

**Comment by sberyozkin** [comment]
Just a clarification - BC support is indirect right now - i.e - we don't have the BC-related extensions

**Comment by harshmadhani** [comment]
@sberyozkin Okay, I just upgraded it to 1.68. Thanks! @gsmet no issues

**Comment by gsmet** [comment]
Closing as there won't be any more 1.10.

**Pull request closed without merging**
