### PR TITLE
Upgrade Gradle wrapper version to 5.6.4

### PR DESCRIPTION
**Pull request by gsmet**
@gastaldi could you test this when you get a chance?

### CODE REVIEW

**Review by gastaldi — COMMENTED** [review]
This doesn't change the Gradle wrapper used in new projects. You need to update the `<gradle-wrapper.version>` in `build-parent/pom.xml` too

**Comment by gsmet** [comment]
Oh it's not using the tools to generate the new projects?

**Comment by gsmet** [comment]
why do we have this variable in the tools, then?

**Comment by gastaldi** [comment]
@aloubyansky may confirm but I think that's still a work in progress

**Comment by gsmet** [comment]
@gastaldi thanks for noticing, I force-pushed an update.

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
@gastaldi can you test that creating a new Gradle project with it works and the project works too?

**Comment by gastaldi** [comment]
Yes, I tested that before approving this PR :smile:  I can confirm it works and the project works too

**Comment by gsmet** [comment]
Let's say you are suspiciously fast ;). Thanks then!

**Comment by gwenneg** [comment]
Shouldn't [this file](https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/gradle/wrapper/gradle-wrapper.properties) be updated too?

**Comment by gsmet** [comment]
Yeah, it's the version we need to build. Initially I just wanted to update the version used in the created projects.

But it's nice to have a reference for when to upgrade Gradle. So I included everything in this PR.

Thanks everyone!

**Review by gwenneg — APPROVED** [review]

**Pull request merged**
