### PR TITLE
Include interfaces as bean types of RR resources

### LINKED ISSUE #29128: Mocking Rest client does not work with 2.14.0.CR1
### Describe the bug

Mocking a Client like this worked with 2.13.3

```
@Alternative()
@Priority(1)
@ApplicationScoped
@RestClient
public class ClientMock implements Client {
```
but does not with 2.14

### Expected behavior

Mocking works.

### Actual behavior

The mock is ignored.

### How to Reproduce?

[code-with-quarkus-client-mock.zip](https://github.com/quarkusio/quarkus/files/9962098/code-with-quarkus-client-mock.zip)

There is a simple test included.

If you switch to 2.13.3 the test passes.

### Output of `uname -a` or `ver`

windows/ubuntu

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #29128 

This is a suggestion on how to fix the issue and works with the reproducer provided there. I've also run some basic tests in RR to see if it breaks anything and so far so good.

However, it isn't a silver bullet because there are other scenarios in which this won't suffice. For instance if these resources extend any user defined class and then injection is performed based on that class (which might be uncommon for RR resources anyway?).

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
I think this is a fine solution for now. Let's just add some tests :)

**Comment by manovotn** [comment]
> I think this is a fine solution for now. Let's just add some tests :)

OFC, I wanted to see if there are any objections to it first.
I'll add something similar to the reproducer.

**Comment by mkouba** [comment]
It looks good. Let's see if it breaks anything...

**Comment by manovotn** [comment]
@mkouba @geoand I've added a test very much like the one from provided reproducer.

**Review by geoand — APPROVED** [review]

**Review by mkouba — APPROVED** [review]

**Pull request merged**
