### PR TITLE
Disable snapshot resolution for releases repositories and only add the Gradle repository where needed

### PR DESCRIPTION
**Pull request by gsmet**
Right now, we try to download maven-metadata.xml from all the repositories present whereas it makes no sense to do it for releases repositories.

I think we should probably also fixed that in the JBoss Parent /cc @dmlloyd .

Noticed because right now the Gradle repository is timing out for me making it really cumbersome to build Quarkus.

In passing, I pushed the Gradle repo to where it's strictly needed because we have absolutely no idea what's there and better be conservative rather than enabling it globally.

### CODE REVIEW

**Review by glefloch — APPROVED** [review]
LGTM

**Comment by famod** [comment]
I wonder whether this will also resolve #10955?

**Comment by gsmet** [comment]
@famod it partially fixes the issue. It would need to get fixed in the jboss-parent too.

**Comment by gsmet** [comment]
Hmmm, I just checked the JBoss parent pom and it only declares a plugin repository and snapshots are not enabled.

So we need to find out from where the other `<repository>` comes from.

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
