### PR TITLE
Disable failing Windows test

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@famod or @jaikiran if you could look into this when you have time (since you guys have Windows machines), that would be excellent

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
@geoand I can have a look at it later this week.
If you have a ticket you can assign it to me.

**Comment by geoand** [comment]
Thanks @famod. I don't have a ticket created, consider this the ticket 😎

**Comment by famod** [comment]
Hm, the test passes locally. I'll have a look at the build logs...

**Comment by famod** [comment]
What can I say...no errors in my fork after commenting out `@DisabledOnOs`: https://github.com/famod/quarkus/commit/69ccd996d5a9c9dff5422cdfff4255d489230ecb

**Pull request merged**
