### PR TITLE
Support AsyncFile, Path. Added PathPart and FilePart

### PR DESCRIPTION
**Pull request by FroMage**
This is the 1.13 version of #15891

### CODE REVIEW

**Comment by geoand** [comment]
CI failure seems related

**Comment by FroMage** [comment]
It seems related. But this is for client interceptors, and that damn test runs locally…

**Comment by FroMage** [comment]
Ah, it's using the 1.13 branch of the TCK, I need to port the same fix there. Fine.

**Comment by FroMage** [comment]
Restarting CI, but it should be fine now.

**Comment by geoand** [comment]
👍🏼

**Comment by geoand** [comment]
Still failing:

```
Error:  Failures: 
Error:    JAXRSClient0021.fileWriterClientInterceptorTest:591->JaxrsCommonClient.invoke:212 [WebValidatorBase] Unable to find the following search string in the server's response: 'com.sun.ts.tests.jaxrs.spec.filter.interceptor.EntityWriterInterceptor' at index: 0

```

**Comment by FroMage** [comment]
Well yeah, the stupid thing still checked out the previous version: 0ce5dbc724a688ff94da4b5755c9720c70a2bf0d

**Comment by FroMage** [comment]
So, restarted it again, but if it keeps taking the wrong commit, I don't know what to do.

**Comment by geoand** [comment]
If you pushed the TCK changes to the `1.13` branch, then CI should be fine because of https://github.com/quarkusio/quarkus/blob/1.13/.github/workflows/ci-actions-incremental.yml#L600

**Comment by FroMage** [comment]
I did, and I checked it in github too. So either it's caching something, or I made a mistake I couldn't spot.

**Comment by geoand** [comment]
Let's see what happens :)

**Comment by geoand** [comment]
@gsmet this PR is against `1.13` as it's a feature we wanted to backport but that needed some work to adapt to Vert.x 3.9.x. 
I assume we are OK to merge it?

**Comment by FroMage** [comment]
Yay, it passed!

**Comment by geoand** [comment]
@gsmet I am going to merge this, OK?

**Comment by cescoffier** [comment]
@geoand should this me merged?

**Comment by geoand** [comment]
I forgot about this one. Yes, I'm merging it, thanks!

**Pull request merged**
