### PR TITLE
Ensure that all our handlers extend `ExtHandler`

### LINKED ISSUE #44540: FORMAT_FAILURE when using `Log.error(Object,Throwable)`
### Describe the bug

Hi, I stumbled across this bug, when an exception message contained braces and `Log.error(e.getMessage(), e)` produced unexpected output instead of logging the message and stacktrace.

Downgrading to quarkus 3.14.2 results in the expected behaviour - 3.14.3 fails.

> Edit: upon closer inspection this only happens in dev-mode - the behaviour of the built artifact is fine.

### Expected behavior

Message and Stacktrace should be logged

### Actual behavior

The following stacktrace is printed:

```
LogManager error of type FORMAT_FAILURE: Formatting error
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
        at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:540)
        at java.base/java.text.MessageFormat.<init>(MessageFormat.java:382)
        at java.base/java.text.MessageFormat.format(MessageFormat.java:882)
        at org.jboss.logmanager.ExtFormatter.formatMessageLegacy(ExtFormatter.java:133)
        at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:96)
        at org.jboss.logmanager.formatters.ColorPatternFormatter.formatMessage(ColorPatternFormatter.java:129)
        at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:832)
        at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:227)
        at org.jboss.logmanager.formatters.ColorPatternFormatter$ColorStep.render(ColorPatternFormatter.java:152)
        at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:90)
        at org.jboss.logmanager.ExtFormatter$Delegating.format(ExtFormatter.java:196)
        at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:58)
        at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:52)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:471)
        at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:406)
        at io.quarkus.runtime.logging.LoggingSetupRecorder$7.publish(LoggingSetupRecorder.java:570)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:138)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.activate(QuarkusDelayedHandler.java:292)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.setHandlers(QuarkusDelayedHandler.java:189)
        at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:255)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
```

### How to Reproduce?

This can be reproduced with the following startup bean:

```java
package org.acme;

import io.quarkus.logging.Log;
import io.quarkus.runtime.Startup;
import jakarta.annotation.PostConstruct;

@Startup
public class Start
{
    @PostConstruct
    public void onStart()
    {
        Log.info( "{", new Exception() );
    }
}

```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.14.3 - 3.16.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #44540 (in theory)

### CODE REVIEW

**Comment by gsmet** [comment]
@dmlloyd when you say `in theory` did you test this particular example?

**Comment by dmlloyd** [comment]
I tested it obliquely, but I couldn't test it exactly (yet?) due to local configuration problems.

**Comment by gastaldi** [comment]
@MaxFichtelmann can you build this PR locally and confirm that it fixes your issue before we merge it?

**Review by brunobat — APPROVED** [review]

**Comment by brunobat** [comment]
It makes sense to me even if it doesn't fix the bug.

**Comment by MaxFichtelmann** [comment]
> @MaxFichtelmann can you build this PR locally and confirm that it fixes your issue before we merge it?

Sure, I'll build and Test when I am at the PC again.

**Comment by MaxFichtelmann** [comment]
hm, still seeing that behaviour in `quarkus dev` - actually when running that same project without dev, the issue does not appear, neither with 3.14.3 nor 3.16.3 - so seems to be a devmode-only issue.

**Review by radcortez — APPROVED** [review]

**Review by gastaldi — APPROVED** [review]
I agree with @brunobat. Even if it doesn't fix the issue, I think this is a nice improvement to have

**Comment by dmlloyd** [comment]
I also opened https://github.com/jboss-logging/jboss-logmanager/pull/493 which should address what we're seeing on the stack trace, once that is merged & the component is updated.

**Comment by gastaldi** [comment]
I'd recommend to wait until https://github.com/jboss-logging/jboss-logmanager/pull/493 is merged and released and updated in this PR before merging

**Comment by gsmet** [comment]
@dmlloyd sorry if it's just noise but how will the new patch in JBoss Logmanager interact with this specific piece:

https://github.com/quarkusio/quarkus/commit/7e6c529629ea31e8c193110c8abe31aaa101b597#diff-3027189c5073a902729f033232338719972cd18a3c64018f24b99dd78e1fea6aR441-R447

where we add parameters to something that used to be `NO_FORMAT`.

**Comment by gastaldi** [comment]
@dmlloyd I know, but the second chance will fix the bug, right?

**Comment by dmlloyd** [comment]
It might :-)

**Comment by gastaldi** [comment]
Loving the confidence behind this patch :D

**Comment by dmlloyd** [comment]
> @dmlloyd sorry if it's just noise but how will the new patch in JBoss Logmanager interact with this specific piece:
> 
> [7e6c529#diff-3027189c5073a902729f033232338719972cd18a3c64018f24b99dd78e1fea6aR441-R447](https://github.com/quarkusio/quarkus/commit/7e6c529629ea31e8c193110c8abe31aaa101b597#diff-3027189c5073a902729f033232338719972cd18a3c64018f24b99dd78e1fea6aR441-R447)
> 
> where we add parameters to something that used to be `NO_FORMAT`.

The interaction should be fine. The handler for `NO_FORMAT` here will change it to use message format, with two arguments.

**Comment by gsmet** [comment]
> The interaction should be fine. The handler for NO_FORMAT here will change it to use message format, with two arguments.

And it won't fail if we end up with `My message {` that used to work in `NO_FORMAT` but won't work with message format? Or maybe you don't resolve the parameters recursively?

**Comment by dmlloyd** [comment]
> > The interaction should be fine. The handler for NO_FORMAT here will change it to use message format, with two arguments.
> 
> And it won't fail if we end up with `My message {` that used to work in `NO_FORMAT` but won't work with message format? Or maybe you don't resolve the parameters recursively?

The original message is passed as a parameter to a new message, so no further interpolation can take place.

**Comment by gsmet** [comment]
OK, perfect, thanks for the clarification. I'm still a bit puzzled the OP says it's failing only in dev mode but I wonder if he actually used the newly compiled version in dev mode, I will have to check that.

**Comment by MaxFichtelmann** [comment]
> OK, perfect, thanks for the clarification. I'm still a bit puzzled the OP says it's failing only in dev mode but I wonder if he actually used the newly compiled version in dev mode, I will have to check that.

I am optimistic that I used the updated version, but this is the first time, I built quarkus myself so...

**Review by geoand — APPROVED** [review]

**Pull request merged**
