### PR TITLE
Introduce tika and tika-resteasy extensions

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi @gsmet 
Here are some of the comments related to your earlier review:
- I left `Content` and `Metadata` class names unchanged, because they represent the file text and metadata (Tika itself only adds few properties to Metadata)
- `tika-resteasy` still depends on the `quarkus-resteasy-common` as it is expected to work with the JAX-RS client API / MP rest client as well
- `tika-resteasy` is very light-weight but I hope to grow it further and link closer; users can add such providers themselves, but I hope it would be easier for them not to.
I'm open to further modifications, have a look whenever you get some time, thanks

**Comment by FroMage** [comment]
@sberyozkin can you rebase please? You have conflicts now.

**Comment by gsmet** [comment]
@sberyozkin I thought about this a bit and I think the Apache Tika extension should live in Quarkus itself but the RESTEasy Tika one should be moved out in its own repo.

We will have the extension ecosystem at some point and I think it's a perfect candidate for this.

If you agree, could you create a PR with just the Tika extension aiming at having Tika working on Quarkus?

**Comment by sberyozkin** [comment]
Hi @gsmet  sounds good to me, thanks. On reflection, I think it is reasonable, in fact I can also follow up with a quick start demo where the simple MBRs are part of the demo as well, just to show them in action, and then once the extensions ecosystem is in place, will consider where to put the -resteasy one. Thanks

Hi @FroMage thanks for mentioning it, I'm going to close this one as agreed with @gsmet  and will create another PR

**Pull request closed without merging**
