### PR TITLE
MP FT integration - fix FallbackHandler support

### LINKED ISSUE #2344: FallbackHandler seems to not taken into consideration
I have created an example of fault tolerance using `@Fallback` annotation with the class approach:

```java
public class RecoverFallback implements FallbackHandler<String> {
    @Override
    public String handle(ExecutionContext context) {
        return "It could be worse";
    }
}
```

```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Retry(maxRetries = 1)
    @Fallback(RecoverFallback.class)
    public String faultTolerance() {
        maybeFail();
        return "Hurrah";
    }
```

But the fallback is never executed. Doing the same but with `fallbackMethod` property then it works as expected.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #2344

### CODE REVIEW

**Comment by mkouba** [comment]
@lordofthejars Could you pls verify that this PR fixes your problem?

**Comment by lordofthejars** [comment]
@mkouba sure, I'll build a snapshot version and I'll test today.

**Comment by lordofthejars** [comment]
@mkouba It works perfectly.

Now I am getting these warnings:

```
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.IIOImageProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.sse.SseEventOutputProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyViolationExceptionMapper is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.sse.SseEventProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jsonp.JsonObjectProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DefaultTextPlain is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.client.jaxrs.internal.CompletionStageRxInvokerProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ReactiveStreamProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.CacheControlFeature is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,274 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.ServerContentEncodingAnnotationFeature is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.CompletionStageProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.ClientContentEncodingAnnotationFeature is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DefaultNumberWriter is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.SourceProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FileProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.MessageSanitizerContainerResponseFilter is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.MultiValuedParamConverterProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jsonp.JsonArrayProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DocumentProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DefaultBooleanWriter is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ByteArrayProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,275 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.StringTextStar is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jsonp.JsonStructureProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.StreamingOutputProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ReaderProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.sse.SseEventSinkInterceptor is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DataSourceProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.JaxrsFormProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FileRangeWriter is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.InputStreamProvider is already registered.  2nd registration is being ignored.
2019-05-07 13:31:20,276 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.jsonp.JsonValueProvider is already registered.  2nd registration is being ignored.
```

But probably are not related to this change. Just in case you are interested in knowing how my `pom` looks like:

```xml
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>${quarkus.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jsonb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-validator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kubernetes</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
    </dependency>
  </dependencies>
```

**Comment by mkouba** [comment]
@gsmet ^ Any idea about the warnings?

**Review by dmlloyd — APPROVED** [review]

**Pull request merged**
