### PR TITLE
Allow Environment variables to populate property Maps in build time Config

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Should we backport it?

**Comment by radcortez** [comment]
> Should we backport it?

I believe it should be fine to backport. It depends on the urgency :)

**Comment by geoand** [comment]
Not urgent, but I would say nice to have for 2.16

**Comment by geoand** [comment]
The CI failure seems related

**Comment by radcortez** [comment]
Yes, I'll have a look

**Pull request merged**
