### PR TITLE
Simplify proxy selection for the REST Client

### LINKED ISSUE #18548: Error injecting rest client caused by PatternSyntaxException when http.nonProxyHosts is set
## Describe the bug

when setting `http.nonProxyHosts` containing a pattern starting with `*` Quarkus fails to inject an instance of a rest client.

Despite a pattern like `*.foo.com` is not a valid regexp, it's a valid value for `nonProxyHosts` according to [Oracle Docs](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html).

### Expected behavior

Create and inject an instance of a rest client without error

### Actual behavior
When Quarkus needs to inject some rest client it fails if `http.nonProxyHost` is set with a value like `*.foo.com|localhost`
```
org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.rest.client.FooRestClient org.acme.rest.client.CountriesResource.fooApi
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.rest.client.FooRestClient org.acme.rest.client.CountriesResource.fooApi
        at org.acme.rest.client.CountriesResource_Bean.create(CountriesResource_Bean.zig:189)
        at org.acme.rest.client.CountriesResource_Bean.create(CountriesResource_Bean.zig:212)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.rest.client.CountriesResource_Bean.get(CountriesResource_Bean.zig:244)
        at org.acme.rest.client.CountriesResource_Bean.get(CountriesResource_Bean.zig:260)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:263)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.foo.com
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:265)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:79)
```

## To Reproduce

1.  clone the [rest-client-quickstart](https://github.com/maykoone/rest-client-quickstart)
2. `./mvnw quarkus:dev -Dhttp.proxyHost=foo-proxy.com -Dhttp.nonProxyHosts="*.foo.com|localhost|127.*|[::1]"`
3.  `curl http://localhost:8080/country`

### Configuration
Included in the project

### Output of `uname -a` or `ver`
`Linux desktop 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### Quarkus version or git rev
`2.0.1.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /opt/maven
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.72-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

### LINKED ISSUE #19240: Rest Client java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0 when setting http.nonProxyHosts
### Describe the bug

I have REST Client injected to my resource class. 
```
@Path("/hello")
public class GreetingResource {
	
    @Inject
    @RestClient
    HelloResourceClient helloResourceClient;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello RESTEasy";
    }
}
```

When I run appliaction without proxy settings i works fine but when I set proxy parameters `-Dhttps.proxyHost=proxy.acme.com -Dhttps.proxyPort=3128 -Dhttp.proxyHost=proxy.acme.com -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts="*.acme.com|*.acme.app"` it throws an exception:
```
RoutingContext failure (500): org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:247)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:270)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:302)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:318)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:269)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.acme.com
```

This same appliaction with proxy parameters on quarkus 1.13.7.Final works fine.

### Expected behavior

Tests should pass

### Actual behavior

Exception 

[io.ver.ext.web.RoutingContext] (executor-thread-0) RoutingContext failure (500): org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:247)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:270)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:302)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:318)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:269)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.acme.com
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:276)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:69)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.create(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:189)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:220)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:243)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:230)
        ... 33 more

2021-08-05 07:37:29,577 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: 8bb16a4e-90f9-4381-a186-098a07ae0ba2-1: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:247)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:270)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:302)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:318)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:269)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.acme.com
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:276)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:69)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.create(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:189)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:220)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:243)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:230)
        ... 33 more

### How to Reproduce?

1. Extract sample appliaction 
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/6936189/code-with-quarkus.zip)
2. Run mvnw test -Dhttps.proxyHost=proxy.acme.com -Dhttps.proxyPort=3128 -Dhttp.proxyHost=proxy.acme.com -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts="*.acme.com|*.acme.app"

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1556]

### Output of `java -version`

openjdk version "11.0.9.1" 2020-11-04 LTS OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\Users\aszywala\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.9.1, vendor: Amazon.com Inc., runtime: c:\jdk\jdk11.0.9_12 Default locale: pl_PL, platform encoding: Cp1250 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
- do not use regexp pattern matching for http.nonProxyHosts env variable
  given it is not supposed to be a valid regexp (* is the wildcard)
- give precedence to the builder configuration over the env variables
- delegate the whole proxy resolution via env variables to ProxySelector

Fixes #19240
Fixes #18548

### CODE REVIEW

**Comment by gsmet** [comment]
@andrzejszywala any chance you could test this PR in your environment?

Just get this branch and you can follow the instructions here: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main

**Comment by gsmet** [comment]
@mkouba the failures above looks related to https://github.com/quarkusio/quarkus/pull/19192 ?

**Comment by mkouba** [comment]
> @mkouba the failures above looks related to #19192 ?

@gsmet Yes, it's related. Seems like a flaky test.

@ebullient Do you happen to know what exactly does the `MeterNotFoundException` message mean? I'm a bit confused. It says that there's no meter with name `scheduled.methods` but then it says  _"A meter with name `scheduled.methods` has a tag 'method' with value 'everySecond'."_
```
FAIL: No meter with name 'scheduled.methods' was found.
OK: Meters with type timer were found.
OK: A meter with name 'scheduled.methods' has a tag 'method' with value 'everySecond'.
OK: A meter with name 'scheduled.methods' has a tag 'class' with value 'io.quarkus.scheduler.test.metrics.MicrometerTimedTest$Jobs'.
```

**Comment by ebullient** [comment]
> @ebullient Do you happen to know what exactly does the `MeterNotFoundException` message mean? I'm a bit confused. It says that there's no meter with name `scheduled.methods` but then it says  _"A meter with name `scheduled.methods` has a tag 'method' with value 'everySecond'."_
> 
> ```
> FAIL: No meter with name 'scheduled.methods' was found.
> OK: Meters with type timer were found.
> OK: A meter with name 'scheduled.methods' has a tag 'method' with value 'everySecond'.
> OK: A meter with name 'scheduled.methods' has a tag 'class' with value 'io.quarkus.scheduler.test.metrics.MicrometerTimedTest$Jobs'.
> ```

Meters must have the same labels (class, method, ...). It looks like we somehow have two timers? That is a little odd.

I usually do a bit of waiting for meters to show up for testing..

https://github.com/quarkusio/quarkus/blob/0616e26df8ef702f10b85fd7f655eb16dae5b4e5/extensions/micrometer/deployment/src/test/java/io/quarkus/micrometer/deployment/binder/UriTagWithHttpRootTest.java#L66

**Comment by famod** [comment]
@gsmet did you mean "Fixes #19240"?

Btw, I ran into a problem in the same code a few days ago because I had my nonProxyHosts (in MAVEN_OPTS) wrapped in double quotes. Without those, gradlew fails in the Quarkus build (sic!) due to the pipe separating 127.0.0.1 and localhost.
I'll try to test whether this PR changes anything. I'm less than sure that those quotes are even allowed, but the JDK parsing logic doesn't seem to mind.

**Comment by gsmet** [comment]
@famod yup, fixed.

**Comment by famod** [comment]
Btw, this also seems to fix #18548 (in which @michalszynkiewicz and @radcortez discussed how to move forward).

**Comment by michalszynkiewicz** [comment]
@gsmet with your changes, is it still possible to set nonProxyHosts?

**Comment by gsmet** [comment]
@michalszynkiewicz the JDK proxy selector should take care of everything and consume the proxy system properties to determine what to do. The only thing I was a bit unsure of is that I changed the ordering slightly for something that sounds more logical to me... but I might have missed something.

**Review by michalszynkiewicz — APPROVED** [review]

**Pull request merged**
