### PR TITLE
Add dev mode test for multiple datasources

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by geoand** [comment]
I'll do the same thing with the Flyway once #9436 is in

**Review by geoand — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I was hoping this would show up the config issue. It didn't, but seems worth having anyway.

**Comment by geoand** [comment]
I'll see if the Flyway test I'll add will surface the issue

**Comment by geoand** [comment]
I have the test ready (and it does fail without your Config fixing PR). I'll open a PR once your is merged

**Pull request merged**
