### PR TITLE
Allow overriding trust store properties in the Infinispan client

### PR DESCRIPTION
**Pull request by newportd**
Hello,
This pull request adds support for specifying the infinispan client trust store location (and other associated properties) in the quarkus application.properties file.

Please let me know of any questions or comments.

Thanks!

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks!

Just a note that we need to check it's consistent with the other trust store properties we have in other extensions. Please dismiss when done.

**Comment by geoand** [comment]
Thanks a lot for the contribution!

I looked at what @gsmet said, and in most of the codebase we just use `trustStore` instead of `trustStoreFileName`

**Comment by newportd** [comment]
Thanks, I have renamed the property to be consistent with other extensions based on your recommendation. Let me know of any other comments.

**Comment by karesti** [comment]
@geoand LGTM but I added @wburns to review, he is more accurate

**Comment by geoand** [comment]
Great, thanks @karesti

**Comment by newportd** [comment]
@gsmet Please let me know if renaming the property addresses your concern.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merging this one as it's a step in the right direction. Thanks!

**Pull request merged**
