### PR TITLE
Qute parser fix - tag delimiter is used in a string literal in a tag

### PR DESCRIPTION
**Pull request by mkouba**
- for example 'messages.get("{foo}")'

### CODE REVIEW

**Comment by mkouba** [comment]
CC @SaumyaSingh1

**Comment by SaumyaSingh1** [comment]
This is awesome @mkouba , the other trick you mentioned also worked perfect but yeah this is cool :)
Thanks

**Comment by gsmet** [comment]
@mkouba is it worth being backported to 1.11 too?

**Comment by mkouba** [comment]
> @mkouba is it worth being backported to 1.11 too?

@gsmet I don't think so. It's a corner case...

**Review by gsmet — APPROVED** [review]

**Pull request merged**
