### PR TITLE
Resteasy reactive doesn't encode a space in @Path value

### PR DESCRIPTION
**Pull request by tkobayas**
- Unit test only

See https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Kogito.20and.20RESTEasy.20Reactive

### CODE REVIEW

**Comment by tkobayas** [comment]
Feel free to close this PR and recreate if the unit test is not in an appropriate place.

**Comment by geoand** [comment]
Does RESTEasy Reactive not work properly if you add the `@Encoded` annotation?

**Comment by tkobayas** [comment]
Thank you for the reply, @geoand 

I added `@Encoded` on both class level and method level but didn't help.

Btw, I updated the PR by adding a test for an explicitly encoded space `hello%20test`, which is successful.

According to jax-rs 2.1 spec "3.4 URI Templates"
```
The value of the annotation is automatically encoded, e.g. the following two lines are equivalent:

1  @Path("widget list/{id}")
2  @Path("widget%20list/{id}")
```
So I think both should work. (as Resteasy classic does)

**Comment by geoand** [comment]
@FroMage do you remember anything about this?

**Comment by geoand** [comment]
Thanks for bringing this to our attention. 

I'll close this PR and open a new one with a fix

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/22840 is the follow up

**Pull request closed without merging**
