### PR TITLE
Bump kubernetes-client to 4.6.0

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks @gastaldi!

What new does 4.6.x bring?

**Comment by gastaldi** [comment]
@geoand according to https://github.com/fabric8io/kubernetes-client/releases/tag/v4.6.0, support for ControllerRevision,Template Instance and SharedInformer

**Comment by geoand** [comment]
Thanks @gastaldi.

Seems like it adds things that we all use everyday 😂

**Comment by gastaldi** [comment]
Ah and the Kubernetes Model was updated, I think that's why it's worth upgrading :wink:

**Comment by geoand** [comment]
I just now realized what the SharedInformer is. That is actually super interesting!

**Pull request merged**
