### PR TITLE
Add exclude and additional option to AssembleDownstreamDocumentation

### PR DESCRIPTION
**Pull request by maxandersen**
Why:

 * downstreamdoc.yaml is used to generate the list of docs used by
  downstream doc builds and today its hardcoded thus very limited
  for downstream docs ability to adjust without changing the quarkus
  repo.

This change addreses the need by:

 * adding a DOWNSTREAM_CONFIG_FILE to *optionally* override the
   hardcoded downstreamdoc.yaml
 * adding a DOWNSTREAM_ADDITONALS env var to the downstream doc build
   that can be used to add docs to the list of docs used by
   downstream doc builds
 * adding a DOWNSTREAM_EXCLUDES env var to the downstream doc build
   that can be used to exclude docs from the list of docs used by
   downstream doc builds + additionals

@michelle-purcell @sheilamjones FYI

Idea for this is that on downstreambuilds you can set DOWNSTREAM_EXCLUDES env to exclude files that are in dwonstream.yaml - i.e.

```
export DOWNSTREAM_ADDITIONALS=src/main/asciidoc/cli-tooling.adoc 
export DOWNSTREAM_EXCLUDES=security-jpa,security-cors 
mvn package
````

if do not want to main adds/excludes set speific file instead:

```
export DOWNSTREAM_CONFIG_FILE=redhatprod.yaml
mvn package
```

### CODE REVIEW

**Comment by maxandersen** [comment]
just realized when takling with @gsmet this is NOT actualy used by github bot.

**Comment by maxandersen** [comment]
merging in as it cause no change to existing code only activates different behavior if using env variables.

**Comment by MichalMaler** [comment]
@maxandersen @aloubyansky @sheilamjones I guess this needs to be backported to 3.2, since script will be checking that branch for these changes.

**Comment by gsmet** [comment]
Please don't merge PRs with merge commits, they are annoying to backport. Rebase it before merging. Thanks!

**Comment by MichalMaler** [comment]
@maxandersen @gsmet @aloubyansky Created a bacporting MR here: https://github.com/quarkusio/quarkus/pull/38212

**Pull request merged**
