### PR TITLE
Test improvements in the Gradle plugin

### PR DESCRIPTION
**Pull request by gastaldi**
junit-jupiter resolves transitively to the api, engine and params modules.
Also setup to use testImplementation and testRuntime directives in build.gradle

### CODE REVIEW

**Comment by gastaldi** [comment]
@Sanne @gsmet @geoand can you have a look at it?

**Comment by geoand** [comment]
I like it

**Comment by Sanne** [comment]
nice!

**Comment by stuartwdouglas** [comment]
Does this need any docs changes or changes in the quickstarts projects to go with it?

**Review by gsmet — APPROVED** [review]

**Pull request merged**
