### PR TITLE
Remove the legacy datasource configuration

### PR DESCRIPTION
**Pull request by gsmet**
We moved to the new configuration in 1.3 and had deprecation warnings
since then.
Moreover it's confusing as people do all sort of weird things and they
don't have any proper deprecation warnings for very weird configuration
settings that we don't catch as invalid.
Better get a clean sheet now.

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]
About time! LGTM.

**Comment by Sanne** [comment]
Very nice cleanup!  I'm confused about the min-size being gone, didn't we need that to tune the pool and yet have lazy initialization?

**Comment by machi1990** [comment]
> Very nice cleanup! I'm confused about the min-size being gone, didn't we need that to tune the pool and yet have lazy initialization?

I think it is still there:

https://github.com/quarkusio/quarkus/blob/ac0be13005675d433fc25695e1bf1876e1b4e9af/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcRuntimeConfig.java#L32

But rather removed from various the test resource files.

**Comment by gsmet** [comment]
@Sanne as Manyanda mentioned it, I haven't removed it: I just removed it from all the tests where it was useless and generating a warning because the initial size was under the minimal size. I could have also defined the initial size instead but it had relatively low value.

Thus the cleanup but it's still there, don't worry :). It's not the type of changes I would hide in an unrelated PR :).

**Comment by Sanne** [comment]
Thanks both!  BTW I wasn't thinking that you'd "hide it in an unrelated PR", more like wondering if it was a legacy-only thing.

It still makes me think though, I'm not sure if the warning is appropriate as I had my reasons to tune for smaller test times :) But it's unrelated and far less important, let's discuss it another time.

**Comment by gsmet** [comment]
The warning comes from Agroal complaining about initial size being inferior to minimal size every time you configure the min-size without setting the initial-size to at least the min-size.

**Pull request merged**
