### PR TITLE
Upgrade kotlin version to 1.4

### PR DESCRIPTION
**Pull request by evanchooly**
https://blog.jetbrains.com/kotlin/2020/08/kotlin-1-4-released-with-a-focus-on-quality-and-performance/

### CODE REVIEW

**Comment by gsmet** [comment]
@evanchooly any progress on this one?

**Comment by evanchooly** [comment]
My machine is in the shop so I'm a bit behind.

**Comment by gastaldi** [comment]
This PR needs to be rebased

**Comment by evanchooly** [comment]
yeah, i'm waiting on the panache PR to land so i can test that the new kotlin version doesn't complain about the generated bytecode.

**Comment by oberstrike** [comment]
Does one already know when the PR is finished?

**Comment by evanchooly** [comment]
I'm hoping today. Just waiting on approval but the PR itself is done.

**Comment by evanchooly** [comment]
Every run seems to fail in a different place.  When I run it locally, it works.  @geoand any ideas? @gastaldi @gsmet   (your names were all recommended by github so you win. :D )

**Comment by geoand** [comment]
I'm seeing

```
2020-11-13T06:36:09.4598617Z [ERROR] io.quarkus.it.mongodb.panache.MongodbPanacheResourceTest.testBookEntity  Time elapsed: 0.02 s  <<< FAILURE!
2020-11-13T06:36:09.4600959Z java.lang.AssertionError: Built-in class kotlin.Any is not found
```

in the logs. Did you see something different?

**Comment by gsmet** [comment]
All I can say is that CI is pretty stable lately. So if it's failing more or less consistently, there's something wrong in the PR.

**Comment by evanchooly** [comment]
I tracked it down and finally recreated it.  I've been building with java 8 locally.  switching to 11, i get that locally, too.  so that's something I can work with.  will let you know.

**Comment by evanchooly** [comment]
the test failures here are the same as #11549.  I can remove the dependency on `jackson-module-kotlin` and the tests pass.  It doesn't seem that particular integration test actually need the module.  The question is, then, do we want to merge an update that would break those cases that *do* need it or wait for the jackson team to fix their bug.  I don't think we want to update to 1.4 just yet as jackson is a pretty common dependency.  On the other hand, if these tests can get by without a specific kotlin module from jackson, chances are a lot of others could, too.  

So I'm not sure which path is better.  If we *do* merge this update, we'd probably fine for many cases but in the instances where the jackson module is involved, we could simply refer issues to that project instead.  And once they fix whatever the issue is, we'd already be set up on 1.4.

Thoughts?

**Comment by gsmet** [comment]
My opinion is that, if we can't get Jackson working properly, we shouldn't upgrade.

**Comment by geoand** [comment]
I agree with both of you.

I would much rather hold off the upgrade to Kotlin1.4 until Jackson fully works with it.
The chance of us getting plenty of bug reports that nor we nor the user can do anything about is pretty high given the popularity of Jackson.

**Comment by evanchooly** [comment]
Sounds like we're all on the same page then.  I'll move this to a draft PR so it's findable and add a note about the Jackson issue.  I'll also reach out to the Jackson team and see what's happening there.

**Comment by geoand** [comment]
Great, thanks!

**Comment by gsmet** [comment]
@evanchooly maybe it's worth trying 2.12.0-rc2 ?

**Comment by evanchooly** [comment]
I did actually

**Comment by evanchooly** [comment]
@stuartwdouglas's PR gets us over the hump.

**Pull request closed without merging**
