### PR TITLE
BeanManager.getBeans() - assume the default qualifier if none specified

### PR DESCRIPTION
**Pull request by mkouba**
- this behavior is defined by the spec

### CODE REVIEW

**Comment by mkouba** [comment]
See also https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/.40InjectMock.20incorrect.20resolution

**Review by Ladicek — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

**Comment by mkouba** [comment]
The CI failure seems to be related...

**Comment by gsmet** [comment]
@mkouba could you prepare a note about the potential compatibility issue? I see you had to add some qualifiers to some tests. Just add it as a comment here and I will include it in the 2.12.1 announcement blog post. Thanks!

**Comment by mkouba** [comment]
> @mkouba could you prepare a note about the potential compatibility issue? I see you had to add some qualifiers to some tests. Just add it as a comment here and I will include it in the 2.12.1 announcement blog post. Thanks!

So this change should only affect code that directly/indirectly makes use of the `BeanManager.getBeans(Type, Annotation...)` method and does not pass any required qualifiers, i.e. regular injection, programmatic lookup and code like `beanManager.getBeans(Foo.class, MyQualifier.Literal.INSTANCE)` is not affected. The difference is that previously if no qualifier was specified then the behavior was the same as if the `@Any` qualifier was used, i.e. all beans matching the required type were resolved. In general, a user can get an unsatisfied dependency exception at runtime (e.g. during tests when `@InjectMock` is used). The solution is to use an appropriate qualifier or `@Any`.

**Comment by manovotn** [comment]
Note that this change is also aligning the behavior with CDI specification. Therefore, if users expected/relied on different behavior, it was not warranted by spec.
See https://github.com/jakartaee/cdi/blob/master/api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java#L75

**Pull request merged**
