### PR TITLE
Improve Reflection Performance for Beans with Superclass methods/fields

### PR DESCRIPTION
**Pull request by bcluap**
Avoid NoSuchMethodException being thrown and having resultant fillInStackTrace impact reflection performance. Here is a stacktrace I see a lot when running a load test:

java.base@11.0.5/java.lang.Throwable.fillInStackTrace(Native Method)
java.base@11.0.5/java.lang.Throwable.fillInStackTrace(Throwable.java:787)
   - locked java.lang.NoSuchMethodException@7e48719e
java.base@11.0.5/java.lang.Throwable.<init>(Throwable.java:270)
java.base@11.0.5/java.lang.Exception.<init>(Exception.java:66)
java.base@11.0.5/java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
java.base@11.0.5/java.lang.NoSuchMethodException.<init>(NoSuchMethodException.java:51)
java.base@11.0.5/java.lang.Class.getDeclaredMethod(Class.java:2475)
app//io.quarkus.arc.impl.Reflections.findMethod(Reflections.java:33)
app//guru.jini.services.property.rest.PropertiesResource_Subclass.<init>(PropertiesResource_Subclass.zig:522)
app//guru.jini.services.property.rest.PropertiesResource_Bean.create(PropertiesResource_Bean.zig:80)
app//guru.jini.services.property.rest.PropertiesResource_Bean.create(PropertiesResource_Bean.zig:648)
app//io.quarkus.arc.impl.RequestContext.get(RequestContext.java:67)
...
This PR Introduces a weak set cache to track methods and fields that are found on superclasses so as to avoid always getting NoSuchMethodException.

Load tests against this change show a 36% increase in throughput for a basic rest service where the service extends another class which has about 8 methods on it.

Although this change helps a lot, it would be even better if the generated code for beans that extend other classes don't use reflection on every superclass method/field for every single class instantiation. Perhaps someone who understands that part better could take a look at optimising treatment of beans with superclasses as they perform significantly worse than ones that dont extend anything.

### CODE REVIEW

**Comment by gsmet** [comment]
@bcluap any chance you could properly rebase this PR and have one commit with the changes?

I also have one question: you're talking about throughput improvements, is it at runtime when you access the REST service?

**Comment by mkouba** [comment]
So we only use reflection if an injection point resolves to a dependent bean that injects `InjectionPoint` metadata. A common example is injection of a `@ConfigProperty` that is satisifed by a `io.smallrye.config.inject.ConfigProducer` method. I like the idea of a cache but we could probably cache all lookups (hit, miss, etc.). I'll take a look at this next week...

**Comment by gsmet** [comment]
@bcluap any chance you could provide a simple app where we can see the difference? Might be useful to validate the improvements.

Thanks!

**Comment by bcluap** [comment]
The performance increase was at runtime. I will create a new rebased PR if this discussion requires it.

In creating a test app to show this, I worked out that it has to do with a combination of superclasses and @Transactional annotation. Take a look at this test project:

https://github.com/bcluap/quarkus/tree/master/reflection

Once built, if you decompile ./target/org/acme/quickstart/GreetingResource_Subclass.class you will see this constructor:

`public GreetingResource_Subclass(final CreationalContext creationalContext, final InjectableInterceptor injectableInterceptor) {
        final HashMap<String, Object> hashMap = new HashMap<String, Object>();
        hashMap.put(((InjectableBean)injectableInterceptor).getIdentifier(), ((InjectableReferenceProvider)injectableInterceptor).get((CreationalContext)CreationalContextImpl.child(creationalContext)));
        final HashMap<String, SubclassMethodMetadata> hashMap2 = new HashMap<String, SubclassMethodMetadata>();
        this.metadata = hashMap2;
        final ArrayList<InterceptorInvocation> list = new ArrayList<InterceptorInvocation>();
        list.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method = Reflections.findMethod((Class)GreetingResource.class, "go1", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m1", new SubclassMethodMetadata((List)list, method, (Set)set));
        final ArrayList<InterceptorInvocation> list2 = new ArrayList<InterceptorInvocation>();
        list2.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method2 = Reflections.findMethod((Class)GreetingResource.class, "go3", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set2 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set2.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m2", new SubclassMethodMetadata((List)list2, method2, (Set)set2));
        final ArrayList<InterceptorInvocation> list3 = new ArrayList<InterceptorInvocation>();
        list3.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method3 = Reflections.findMethod((Class)GreetingResource.class, "go2", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set3 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set3.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m3", new SubclassMethodMetadata((List)list3, method3, (Set)set3));
        final ArrayList<InterceptorInvocation> list4 = new ArrayList<InterceptorInvocation>();
        list4.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method4 = Reflections.findMethod((Class)GreetingResource.class, "go10", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set4 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set4.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m4", new SubclassMethodMetadata((List)list4, method4, (Set)set4));
        final ArrayList<InterceptorInvocation> list5 = new ArrayList<InterceptorInvocation>();
        list5.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method5 = Reflections.findMethod((Class)GreetingResource.class, "go9", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set5 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set5.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m5", new SubclassMethodMetadata((List)list5, method5, (Set)set5));
        final ArrayList<InterceptorInvocation> list6 = new ArrayList<InterceptorInvocation>();
        list6.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method6 = Reflections.findMethod((Class)GreetingResource.class, "go8", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set6 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set6.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m6", new SubclassMethodMetadata((List)list6, method6, (Set)set6));
        final ArrayList<InterceptorInvocation> list7 = new ArrayList<InterceptorInvocation>();
        list7.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method7 = Reflections.findMethod((Class)GreetingResource.class, "go7", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set7 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set7.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m7", new SubclassMethodMetadata((List)list7, method7, (Set)set7));
        final ArrayList<InterceptorInvocation> list8 = new ArrayList<InterceptorInvocation>();
        list8.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method8 = Reflections.findMethod((Class)GreetingResource.class, "go6", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set8 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set8.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m8", new SubclassMethodMetadata((List)list8, method8, (Set)set8));
        final ArrayList<InterceptorInvocation> list9 = new ArrayList<InterceptorInvocation>();
        list9.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method9 = Reflections.findMethod((Class)GreetingResource.class, "go4", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set9 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set9.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m9", new SubclassMethodMetadata((List)list9, method9, (Set)set9));
        final ArrayList<InterceptorInvocation> list10 = new ArrayList<InterceptorInvocation>();
        list10.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method10 = Reflections.findMethod((Class)GreetingResource.class, "greeting", new Class[] { String.class });
        final HashSet<Transactional_Shared_AnnotationLiteral> set10 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set10.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m10", new SubclassMethodMetadata((List)list10, method10, (Set)set10));
        final ArrayList<InterceptorInvocation> list11 = new ArrayList<InterceptorInvocation>();
        list11.add(InterceptorInvocation.aroundInvoke(injectableInterceptor, hashMap.get(((InjectableBean)injectableInterceptor).getIdentifier())));
        final Method method11 = Reflections.findMethod((Class)GreetingResource.class, "go5", new Class[0]);
        final HashSet<Transactional_Shared_AnnotationLiteral> set11 = new HashSet<Transactional_Shared_AnnotationLiteral>();
        set11.add(new Transactional_Shared_AnnotationLiteral(new Class[0], new Class[0], Transactional$TxType.REQUIRED));
        hashMap2.put("m11", new SubclassMethodMetadata((List)list11, method11, (Set)set11));
    }
`

So for every method of the bean and any supers it may have, a reflection call is done during construction (which for RequestScoped means every rest call). So if my rest resource has 11 methods, and if 10 of those methods are on the super, then that's 10 MethodNotFoundExceptions per instantiation.

I really think that due to @Transactional being a very common use case, the ultimate solution would be  that the build processor should resolve the concrete method invocations at build time and not rely on reflection at runtime,

In the meantime though, if you run a load test on this test project, then you will see a significant performance improvement with the PR I did.

**Comment by bcluap** [comment]
Test results of the test project (after about 10 runs)

Without the cache:

paul@PCBLaptop:~$ ab -c 10 -n 100000 http://localhost:8080/hellofast
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /hellofast
Document Length:        2 bytes

Concurrency Level:      10
Time taken for tests:   15.189 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      8000000 bytes
HTML transferred:       200000 bytes
Requests per second:    6583.75 [#/sec] (mean)
Time per request:       1.519 [ms] (mean)
Time per request:       0.152 [ms] (mean, across all concurrent requests)
Transfer rate:          514.36 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.4      0      20
Processing:     0    1   1.2      1      50
Waiting:        0    1   1.1      1      50
Total:          0    1   1.3      1      50

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      2
  80%      2
  90%      2
  95%      3
  98%      5
  99%      6
 100%     50 (longest request)


With the PR applied:

paul@PCBLaptop:~$ ab -c 10 -n 100000 http://localhost:8080/hellofast
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /hellofast
Document Length:        2 bytes

Concurrency Level:      10
Time taken for tests:   12.265 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      8000000 bytes
HTML transferred:       200000 bytes
Requests per second:    8153.36 [#/sec] (mean)
Time per request:       1.226 [ms] (mean)
Time per request:       0.123 [ms] (mean, across all concurrent requests)
Transfer rate:          636.98 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       8
Processing:     0    1   0.9      1      37
Waiting:        0    1   0.9      1      37
Total:          0    1   1.0      1      37

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      2
  95%      2
  98%      3
  99%      5
 100%     37 (longest request)

And with @Transactional removed:

paul@PCBLaptop:~$ ab -c 10 -n 100000 http://localhost:8080/hellofast
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /hellofast
Document Length:        2 bytes

Concurrency Level:      10
Time taken for tests:   10.904 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      8000000 bytes
HTML transferred:       200000 bytes
Requests per second:    9171.35 [#/sec] (mean)
Time per request:       1.090 [ms] (mean)
Time per request:       0.109 [ms] (mean, across all concurrent requests)
Transfer rate:          716.51 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0      12
Processing:     0    1   0.8      1      19
Waiting:        0    1   0.7      0      19
Total:          0    1   0.8      1      19
WARNING: The median and mean for the waiting time are not within a normal deviation
        These results are probably not that reliable.

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      2
  95%      2
  98%      3
  99%      4
 100%     19 (longest request)


P.S. Set as @ApplicationScoped or @Singleton with no transaction and results don't change much from those with @RequestScoped which is great.

**Comment by bcluap** [comment]
Just for fun i added another 150 methods onto MySuper and without the PR the tps went down to 1300 and with the PR about 2300 tps so its still no great compared to fewer methods.

If we could make changes to get the test project with 160 methods on the superclass to get up to the same as with 1 method then we rocking.

Alternatively, for best performance, developers would need to ensure that transactional beans don't have many methods in the class hierarchy - which is a bit offputting and not something one should have to worry about.

**Comment by mkouba** [comment]
@bcluap Thanks for the tests and analysis.

1. Yes, intercepted classes also require reflection but we can't get rid of it because of `javax.interceptor.InvocationContext.getMethod()`.
2. We could use caching but we could also switch to `Class.getDeclaredFields()` (iteration would be probably much faster than `NoSuchFieldException`).

I do think that we should optimize this piece of code. But we should probably spend some more time with analyzing the problem and trying to find the best solution.

**Comment by gsmet** [comment]
@mkouba can you create an issue with all the details we have here and a pointer to the test app?

And please mark it for 1.3 as I'm pretty sure we want that one for 1.3.

Thanks!

**Comment by gsmet** [comment]
Closing as superseded by https://github.com/quarkusio/quarkus/pull/6990 .

Let's continue the discussion there.

**Pull request closed without merging**
