### PR TITLE
Extension clarification for Kafka Serializer/deserializer autodetection

### PR DESCRIPTION
**Pull request by rsvoboda**
Extension clarification for Kafka Serializer/deserializer autodetection.

Some people may consider this feature to be available also for `quarkus-kafka-client`, so let's mention the extension explicitly.

### CODE REVIEW

**Comment by Ladicek** [comment]
It does mention the extension explicitly, you're just duplicating the info. If you insist on this, I'd just add the coordinates into `backticks` so that it's highlighted as code.

**Comment by ozangunalp** [comment]
I do agree with @Ladicek on this. At least let's get the backticks so that one can understand that its artifact coordinates.

**Comment by rsvoboda** [comment]
Backticks added

**Review by ozangunalp — APPROVED** [review]

**Comment by ozangunalp** [comment]
Thanks!

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
