### PR TITLE
Fix building Quarkus with JDK 13

### PR DESCRIPTION
**Pull request by gsmet**
Wasn't too hard :).

Note: we can't have CI yet as JDK 13 is not available on Azure yet.

### CODE REVIEW

**Comment by geoand** [comment]
Wow! What's up with need to cast? was a new method added in JDK 13?

**Comment by gsmet** [comment]
Yes, the second parameter can now be a class loader or a Map.

**Comment by geoand** [comment]
Good know, thanks!

**Comment by geoand** [comment]
@gsmet would you like me to approve and merge or should we wait for @Sanne ?

**Comment by Sanne** [comment]
I'm testing it locally, let me finish the build at least :)

**Comment by geoand** [comment]
Cool :)

**Comment by geoand** [comment]
Darn sdkman still doesn't have the final JDK 13 available for installation, only ea

**Comment by Sanne** [comment]
When testing on JDK 13 there's a failure in the Kogito integration tests.

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-kogito: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kogito.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ExceptionInInitializerError
[ERROR] 	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:989)
[ERROR] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:592)
[ERROR] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:514)
[ERROR] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:483)
[ERROR] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:429)
[ERROR] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:396)
[ERROR] 	at org.drools.core.util.XStreamUtils.createTrustingXStream(XStreamUtils.java:43)
[ERROR] 	at org.drools.compiler.kproject.models.KieModuleMarshaller.<init>(KieModuleMarshaller.java:48)
[ERROR] 	at org.drools.compiler.kproject.models.KieModuleMarshaller.<clinit>(KieModuleMarshaller.java:46)
[ERROR] 	at org.drools.compiler.kproject.models.KieModuleModelImpl.fromXML(KieModuleModelImpl.java:143)
[ERROR] 	at io.quarkus.kogito.deployment.KogitoAssetsProcessor.createApplicationGenerator(KogitoAssetsProcessor.java:279)
[ERROR] 	at io.quarkus.kogito.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:147)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:780)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:830)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @6c9cbf2c
[ERROR] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:344)
[ERROR] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:284)
[ERROR] 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
[ERROR] 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
[ERROR] 	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
[ERROR] 	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
[ERROR] 	... 24 more
```
cc/ @evacchi 

That said, there's no harm in merging this - WDYT @gsmet and @geoand ?

I think I'd merge anyway, at least we have the core component working fine - while without this not even that.
I'll approve and let you choose.

**Review by Sanne — APPROVED** [review]
Approved - but not merging as there's options.

**Comment by gsmet** [comment]
It’s weird. I had a warning but no errors and the build succeeded.

**Comment by geoand** [comment]
I agree with @Sanne on merging this now. We can always take care of whatever integration tests fail later since we can't yet run a JDK 13 build on CI

**Comment by gsmet** [comment]
Let me have a look tomorrow.

**Comment by gsmet** [comment]
@Sanne are you sure you run the tests with the default options? Wondering if you have a specific `--illegal-access` configuration.

**Comment by Sanne** [comment]
@gsmet you're right!  sorry I have my environment set at most strict by default.

Running it again...

**Comment by Sanne** [comment]
no more failures, sorry about that. Merged, thanks all!

**Comment by gsmet** [comment]
No worries, I'll ping the Kogito team tomorrow because at some point it will be a real issue.

**Comment by evacchi** [comment]
most probably related to this https://github.com/x-stream/xstream/issues/101 Luckily, we went great length to limit our usage of XStream in Kogito and (AFAIK) it is now limited to that one line inside the extension; and it's mostly for backwards-compatibility. We should be able to fix that either by applying the workaround in the xstream issue above, or by removing that line entirely (but that should be discussed)
/cc @mariofusco

**Comment by Sanne** [comment]
> No worries, I'll ping the Kogito team tomorrow because at some point it will be a real issue.

@gsmet ^ evacchi and mariofusco are from the Kogito team, so they know now ;-)

@evacchi understood, and no rush. I merely use the stricter validation in my projects to avoid regressions but it's of course acceptable with existing code to still have some TODOs - nothing urgent.

In case you want to reproduce my environment had:

    JAVA_OPTS=-Dsun.reflect.debugModuleAccessChecks=true --illegal-access=deny 
    MAVEN_OPTS=-Dsun.reflect.debugModuleAccessChecks=true --illegal-access=deny

**Pull request merged**
