### PR TITLE
Update to Keycloak 11.0.1

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by sberyozkin** [comment]
Hmm the doc step failed, will rerun

**Comment by gastaldi** [comment]
The CI was broken, can you please rebase again?

**Comment by gsmet** [comment]
I did the rebase. Too nervous to have everything green.

**Comment by sberyozkin** [comment]
Sorry @gsmet, I rebased and pushed as well, should've told you, thanks for taking care of it as well

**Pull request merged**
