### PR TITLE
Add log diagnostics

### PR DESCRIPTION
**Pull request by dmlloyd**
To help diagnose #2223.

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
It says draft, does it mean don't push upstream @dmlloyd ?

**Comment by dmlloyd** [comment]
Correct.

**Comment by emmanuelbernard** [comment]
How do you do that (draft mode) btw, could not find it :)

**Comment by dmlloyd** [comment]
Before you create the PR, note the drop-down menu next to the create button.  That's where you choose it.

**Comment by gsmet** [comment]
@dmlloyd should we close this one?

**Comment by dmlloyd** [comment]
Hmm, yeah I guess so, this was useful for solving one problem but it'd be pretty obnoxious to keep it in.

**Pull request closed without merging**
