### PR TITLE
Qute: add logical AND and OR operators

### PR DESCRIPTION
**Pull request by mkouba**
- relates to #6369

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
No XOR? (sad :panda_face:)

LGTM :wink:

**Comment by gastaldi** [comment]
I think you need to rebase to pick up the CI fixes

**Comment by gastaldi** [comment]
Also there is a minor typo in your commit message, so if you are force-pushing it would be nice to have that fixed

**Comment by gsmet** [comment]
I rebased as this one got hit by the CI issue in master.

I fixed the typo in passing.

**Pull request merged**
