### PR TITLE
Dev UI:  Continuous testing

### LINKED ISSUE #31932: Dev UI 2 - generate-code gets maven-metadata.xml for Vaadin components
Very often when I build a Quarkus application with 3.0.0.Alpha6, I end up with the following log. I'm not sure this is a behavior we really want to keep.

```
[INFO] --- quarkus-maven-plugin:3.0.0.Alpha6:generate-code (default) @ quarkus-github-lottery ---
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/lit/reactive-element/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/lit/reactive-element/maven-metadata.xml (339 B at 1.9 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/lit-labs/ssr-dom-shim/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/lit-labs/ssr-dom-shim/maven-metadata.xml (340 B at 16 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/lit-element/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/lit-element/maven-metadata.xml (327 B at 17 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/lit-html/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/lit-html/maven-metadata.xml (324 B at 18 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/types/trusted-types/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/types/trusted-types/maven-metadata.xml (338 B at 23 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/vaadin/vaadin-usage-statistics/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/vaadin/vaadin-usage-statistics/maven-metadata.xml (349 B at 22 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/vaadin/vaadin-development-mode-detector/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/vaadin/vaadin-development-mode-detector/maven-metadata.xml (358 B at 15 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/polymer/polymer/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/mvnpm/at/polymer/polymer/maven-metadata.xml (334 B at 20 kB/s)
```

### LINKED ISSUE #32230: Dev UI 2 - Fonts are blurry (Chrome / Fedora)
Using Chrome on a standard Fedora desktop, the fonts for title are very blurry. It's especially visible in light mode.
Firefox is a bit better but not so much.

I tried to check which fonts were used and apparently it's something called `Red Hat text`. Is it a webfont we load?

I'm not sure if I'm the only one observing this but it doesn't look very good and makes it very hard to read for me.

2023-03-29 16 26 15 localhost 23da7fe75f0a

### LINKED ISSUE #32233: Clicking on Dev UI main logo/title doesn't bring me to the home page
When I click on the Dev UI main logo/title (top left), it doesn't bring me to the home page, which is what I would expect.

Tested with Vivaldi and Firefox. I don't have any errors in the console, it's just doing nothing.

From what I can see, it's implemented in the `_reload` method as:

```
        fetch(devuiState.applicationInfo.contextRoot);
```

From what I can see, the `_reload` method is called but `fetch` does nothing.

### LINKED ISSUE #32443: DevUI: Configuration Changes Not Sticking
### Describe the bug

Configuration changes on the Dev UI not sticking.

### Expected behavior

Change configuration should Live Reload and the value should stick and be respected.

### Actual behavior

Configuration changes seem to not be taking effect.

### How to Reproduce?

1. Go to Dev UI Configuration http://localhost:8080/q/dev-ui/configuration
2. Filter for "health"
3. Uncheck `quarkus.datasource.health.enabled`
4. Now navigate to Extensions and check the Health card and see the Datasource is no longer reporting in Health (good).
5. Navigate back to Configuration page and see that the UI has the `quarkus.datasource.health.enabled` checked again.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR has a few commits with small enhancements, and the main feature is the Continuous testing page:

ContinuousTesting

@melloware you might be interested in the change to server log that allows overriding to add a filtered log (for https://github.com/quarkiverse/quarkus-quinoa/blob/main/deployment/src/main/resources/dev-ui/qwc-quinoa-log.js) - see https://github.com/quarkusio/quarkus/blob/cb52bdea9497bcbcae485cfed80f7625f1a8ad48/extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-test-log.js

@mkouba this also handles the issue with multiple pages per menu item (as with https://github.com/quarkusio/quarkus/pull/32471) - It reuse the submenu in the header we already have for extensions.

This PR also:
fix #32443
fix #32233
fix #32230
fix #31932

### CODE REVIEW

**Comment by melloware** [comment]
Oh yeah gonna make the same fix in Quinoa!  Thanks for the heads up!

**Comment by gsmet** [comment]
> Change connecting color to warning

Ah, nice, I wanted to ask for that :).

**Comment by maxandersen** [comment]
nice!

one concern:
the green/red circle  is nice but feels like a lot of real estate spent to show the progress indicator.

How about mimicking a traditional progress bar on top of the tests which means it wont take up space nor need space to visualize progress?

**Comment by phillip-kruger** [comment]
I did not think we have a space problem (so far at least) on this screen. Can you do a mock up of what you mean ?

**Comment by phillip-kruger** [comment]
@melloware this also now fix #32443

**Comment by melloware** [comment]
Nice!   Thanks for fixing!

**Comment by phillip-kruger** [comment]
@gsmet I added a commit to fix https://github.com/quarkusio/quarkus/issues/32230, can you confirm please (as I can not recreate on my env). I just removed the RH font

**Comment by phillip-kruger** [comment]
@gsmet this should also now fix #31932 - I'll find a better way to do this in mvnpm, but for now we set the version explicitly. I'll add a feature to mvnpm that create locked versions

**Review by gastaldi — APPROVED** [review]
LGTM, let's integrate this in and provide enhancements to the UI in subsequent PRs

**Comment by phillip-kruger** [comment]
I don't think the CI failures are related. Can we merge ?

**Pull request merged**
