### PR TITLE
Bump Keycloak version to 15.0.2

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hmm, I run al the tests but did not try in native, will look into it

**Comment by sberyozkin** [comment]
```
2021-09-07 19:27:19,644 WARN  [org.key.ada.KeycloakDeployment] (executor-thread-0) Failed to load URLs from http://localhost:8180/auth/realms/quarkus/.well-known/openid-configuration: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.keycloak.protocol.oidc.representations.MTLSEndpointAliases` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 1, column: 4769] (through reference chain: org.keycloak.protocol.oidc.representations.OIDCConfigurationRepresentation["mtls_endpoint_aliases"])
```

**Comment by sberyozkin** [comment]
Will be fine now, `org.keycloak.protocol.oidc.representations.MTLSEndpointAliases` is a new class and had to be added for the reflection (`org.keycloak.protocol.oidc.representations.OIDCConfigurationRepresentation` was already added earlier)

**Comment by sberyozkin** [comment]
Hi @gastaldi Would you be OK to check it ? This is just a version update, with one more reflection added due to a new class in 15.0.2

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by sberyozkin** [comment]
Thanks @gastaldi

**Pull request merged**
