### PR TITLE
Fix the config editor to handle wildcards

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This turned out to be very complex, but now:
- Wildcards are not displayed in their (useles) raw form
- Unset config properties that have a set wildcard component in their
  root are now displayed
- It is now possible to add new wildcard entries

This is a draft as it needs extensive unit tests and a lot more comments, as the logic is way more involved than I wanted it to be.

I also think the current editor display really does not make sense. From a users PoV they don't care if a config value comes from the 'default config source' or the 'other config source'. It is really apparent when you use the new UI to add a datasource for instance and some properties end up in 'default value' and some in 'other'.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Also I have removed the restriction that you can't write to an immutable config source, as you can always just write the value to application.properties.

**Comment by phillip-kruger** [comment]
> I also think the current editor display really does not make sense. From a users PoV they don't care if a config value comes from the 'default config source' or the 'other config source'.

Agree, we can just collapse into one table. 

I'll checkout this PR and test locally and get back to you

**Comment by stuartwdouglas** [comment]
This should be ready to go now.

**Comment by stuartwdouglas** [comment]
In terms of the UI I think we should have 2 tables:

- The explicitly set config at the top
- An alphabetically ordered table down the bottom that also include the values from the top table (double ups are find).

The second table should be expandable by level, with an expand all button, so you can expand it out to what we have today, or just click to expand the bits you are interested in. 

If we could make that change combined with the changes in this PR I think the editor will be way way more usable.

**Comment by phillip-kruger** [comment]
Ok, I can do the UI change at some point.

**Review by phillip-kruger — APPROVED** [review]

**Pull request merged**
