### PR TITLE
Generate spring-boot metadata in Quarkus extension processor

### PR DESCRIPTION
**Pull request by rquinio**
This is an attempt at #1655

This is mostly working as far as I could test on the getting-started quickstart (undertow + logging + thread-pool runtime config).
To use:
- with Eclipse, install spring-boot support plugin at https://spring.io/tools3/sts/all
- with IntelliJ, you need the Ultimate edition + explicitly add spring-boot as a provided dependency

But there are quite a few limitations I discovered and which I've listed in the issue.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Not sure we want a dependency on SB for annotation processing.

@aloubyansky @dmlloyd @stuartwdouglas @geoand thoughts?

**Comment by geoand** [comment]
My personal opinion is that this feature doesn't warrant having a dependency on any Spring Boot artifacts

**Comment by aloubyansky** [comment]
Would the file type in the IDE appear as some kind of "Spring Boot config"? Sorry, I haven't actually tried it. If so, I don't think we want it to appear like that. IIUC, support for Spring Boot config is already generic enough and based on metadata. Would be great if IDEs simply provided that in a vendor-neutral way out-of-the-box.

**Comment by dmlloyd** [comment]
I think proposing a vendor-neutral properties file metadata format is a great idea.

**Comment by rquinio** [comment]
@geoand @kenfinnigan Yes, overall there are too many drawbacks with this PR, I opened it to trigger discussion, but it should be declined !

> Would the file type in the IDE appear as some kind of "Spring Boot config"? Sorry, I haven't actually tried it. If so, I don't think we want it to appear like that. IIUC, support for Spring Boot config is already generic enough and based on metadata. Would be great if IDEs simply provided that in a vendor-neutral way out-of-the-box.

There's the spring icon on the files - which makes sense since the editor is contributed by a spring plugin :)

> I think proposing a vendor-neutral properties file metadata format is a great idea.

Btw there may be 2 things that could be improved over the already good spring metadata format:

- Metadata for Collection and Map values that are also ConfigGroups
- Notion of build time vs runtime property, for improved usability

I realize now that a better approach may be to generate the metadata of an extension (runtime + deployment) config via the quarkus-bootstrap-maven-plugin executed on the runtime module (since only runtime jars are in IDE classpath, and thus visible to IDE plugins, the build time configuration metadata needs to be in the runtime jar).
It needs to resolve the List<ConfigDescriptionBuildItem> (same logic as https://github.com/quarkusio/quarkus/blob/master/core/creator/src/main/java/io/quarkus/creator/phase/generateconfig/GenerateConfigPhase.java#L150 ) and simply serialize it to the metadata format.

**Comment by kenfinnigan** [comment]
Closing as it was agreed this approach was not ideal.

**Pull request closed without merging**
