### PR TITLE
Camel-AWS - fix env variable substitution, fixes #2525

### LINKED ISSUE #2525: Camel-AWS S3 integration test: Env variable substitution doesn't work anymore
```
oscerd@ghost:~/quarkus/integration-tests/camel-aws-s3$ export S3_REGION="EU_WEST_1"
org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[From[timer:quarkus?repeatCount=1] -> [SetHeade... because of No enum constant com.amazonaws.regions.Regions.{{env:S3_REGION}}
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:142)
	at org.apache.camel.impl.AbstractCamelContext.doWarmUpRoutes(AbstractCamelContext.java:3846)
	at org.apache.camel.impl.AbstractCamelContext.safelyStartRouteServices(AbstractCamelContext.java:3753)
	at org.apache.camel.impl.AbstractCamelContext.doStartOrResumeRoutes(AbstractCamelContext.java:3539)
	at org.apache.camel.impl.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3391)
	at org.apache.camel.impl.AbstractCamelContext.lambda$doStart$2(AbstractCamelContext.java:3188)
	at org.apache.camel.impl.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:3205)
	at org.apache.camel.impl.AbstractCamelContext.doStart(AbstractCamelContext.java:3186)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.impl.AbstractCamelContext.start(AbstractCamelContext.java:3102)
	at io.quarkus.camel.core.runtime.support.FastCamelRuntime.doStart(FastCamelRuntime.java:110)
	at io.quarkus.camel.core.runtime.support.FastCamelRuntime.start(FastCamelRuntime.java:61)
	at io.quarkus.camel.core.runtime.CamelTemplate.start(CamelTemplate.java:51)
	at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask6.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:100)
	at io.quarkus.runtime.Application.run(Application.java:212)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant com.amazonaws.regions.Regions.{{env:S3_REGION}}
	at java.lang.Enum.valueOf(Enum.java:153)
	at com.amazonaws.regions.Regions.valueOf(Regions.java:25)
	at org.apache.camel.component.aws.s3.client.impl.S3ClientStandardImpl.getS3Client(S3ClientStandardImpl.java:96)
	at org.apache.camel.component.aws.s3.S3Endpoint.doStart(S3Endpoint.java:90)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:207)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:72)
	at org.apache.camel.processor.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1290)
	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:47)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:72)
	at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:153)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:58)
	at org.apache.camel.processor.Pipeline.doStart(Pipeline.java:139)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:76)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.impl.RouteService.startChildService(RouteService.java:365)
	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:191)
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:140)
	... 17 more
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:100)
	at io.quarkus.runtime.Application.run(Application.java:212)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[From[timer:quarkus?repeatCount=1] -> [SetHeade... because of No enum constant com.amazonaws.regions.Regions.{{env:S3_REGION}}
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:142)
	at org.apache.camel.impl.AbstractCamelContext.doWarmUpRoutes(AbstractCamelContext.java:3846)
	at org.apache.camel.impl.AbstractCamelContext.safelyStartRouteServices(AbstractCamelContext.java:3753)
	at org.apache.camel.impl.AbstractCamelContext.doStartOrResumeRoutes(AbstractCamelContext.java:3539)
	at org.apache.camel.impl.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3391)
	at org.apache.camel.impl.AbstractCamelContext.lambda$doStart$2(AbstractCamelContext.java:3188)
	at org.apache.camel.impl.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:3205)
	at org.apache.camel.impl.AbstractCamelContext.doStart(AbstractCamelContext.java:3186)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.impl.AbstractCamelContext.start(AbstractCamelContext.java:3102)
	at io.quarkus.camel.core.runtime.support.FastCamelRuntime.doStart(FastCamelRuntime.java:110)
	at io.quarkus.camel.core.runtime.support.FastCamelRuntime.start(FastCamelRuntime.java:61)
	at io.quarkus.camel.core.runtime.CamelTemplate.start(CamelTemplate.java:51)
	at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask6.deploy(Unknown Source)
	... 4 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.amazonaws.regions.Regions.{{env:S3_REGION}}
	at java.lang.Enum.valueOf(Enum.java:153)
	at com.amazonaws.regions.Regions.valueOf(Regions.java:25)
	at org.apache.camel.component.aws.s3.client.impl.S3ClientStandardImpl.getS3Client(S3ClientStandardImpl.java:96)
	at org.apache.camel.component.aws.s3.S3Endpoint.doStart(S3Endpoint.java:90)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:207)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:72)
	at org.apache.camel.processor.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1290)
	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:47)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:72)
	at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:153)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:58)
	at org.apache.camel.processor.Pipeline.doStart(Pipeline.java:139)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.support.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:76)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:86)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:55)
	at org.apache.camel.impl.RouteService.startChildService(RouteService.java:365)
	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:191)
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:140)
	... 17 more

```

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by gsmet** [comment]
Wasn’t the config based on the global MP config? If so, there’s a good chance it’s a general regression and not something we should fix only here. 

It was my understanding that environment variables in MP config would be resolved?

I don’t have the code handy. Maybe I’m missing something.

**Comment by gnodet** [comment]
I'll do a bisect to check where the problem is.

**Comment by gnodet** [comment]
The culprit is the following commit 
  https://github.com/quarkusio/quarkus/commit/514eeac5143afc2f1cd9b798cf0605a068b634d9

**Review by oscerd — APPROVED** [review]

**Comment by gnodet** [comment]
@gsmet fwiw, it's not a general quarkus problem, as the config is using specific substitutions from camel and it was broken by one of my earlier commit, so this can be mergeg.

**Comment by oscerd** [comment]
Can we get this merged?

**Review by mkouba — APPROVED** [review]

**Pull request merged**
