### PR TITLE
Validation of codestart artifacts configured in extension descriptors

### PR DESCRIPTION
**Pull request by aloubyansky**
* Adds an option to the extension metadata generator to validate the codestart artifact, in case it's configured, by resolving it.
* Completes the coordinates of the codestart, in case the configured coordinates were not complete, i.e. missing the version.
* Changed previously pre-configured `io.quarkus:quarkus-descriptor-json` to `io.quarkus:quarkus-platform-descriptor-json` that actually exists.
* Support loading codestarts referenced from extension metadata.

### CODE REVIEW

**Comment by aloubyansky** [comment]
Unfortunately, I did not isolate the artifact id fix, so this is not good for backport.

**Comment by aloubyansky** [comment]
@famod so, I went ahead and removed all the dependencies from the `quarkus-platform-descriptor-json` (which is not a descriptor json at all and now is renamed to `quarkus-core-codestarts`). Can you think of consequences on the incremental build?

The other issue introduced by this PR is that each extension (in this repo) may reference a codestart artifact, which typically will be `quarkus-core-codestarts`. The extension descriptor generating plugin (configured for every runtime artifact) is by default validating that the referenced codestart artifact is resolvable. But this dependency isn't really a Maven dependency. So we need to somehow make sure the build order is correct. I was thinking about adding a dependecy on `quarkus-core-codestarts:pom` from the `quarkus-extensions-parent`, this doesn't look nice though.
Also maven and gradle plugins appear to directly depend on the codestarts artifact which looks like another clean up candidate.

**Comment by aloubyansky** [comment]
Actually, I guess, the codestart artifact doesn't actually need to be resolvable (i.e. built) before the extension descriptor is generated. I was thinking I could simply check whether either the project producing the codestart artifact is found in the reactor or, if it isn't, it is resolvable. This could avoid the hard build ordering. But it would still have to be present in the reactor.

**Comment by ia3andy** [comment]
@aloubyansky maybe we should make another PR to be backported (for the wrong `artifact`s)?

**Comment by aloubyansky** [comment]
We could extract the fix, yes.

**Comment by ia3andy** [comment]
@aloubyansky will it be enough to have the artifact correct without the new code which add the classifier & version?

**Comment by aloubyansky** [comment]
You can probably just append :${project.version} to make it complete.

**Comment by famod** [comment]
@aloubyansky I'll not be able to look at this in detail today. Sunday or so seems more realistic.

**Comment by ia3andy** [comment]
@aloubyansky I created this issue with the new modules names:
https://github.com/quarkusio/quarkus/issues/15813

**Comment by aloubyansky** [comment]
````
2021-03-19T16:09:10.8743409Z Building dependencies list from gradle build files...
2021-03-19T16:09:10.8744819Z 
2021-03-19T16:09:11.3711259Z 
2021-03-19T16:09:11.3718727Z Updating pom.xml...
2021-03-19T16:09:11.3724487Z 
2021-03-19T16:09:11.3869406Z 
2021-03-19T16:09:11.3870384Z Sanity check...
2021-03-19T16:09:11.3870922Z 
2021-03-19T16:09:27.9822003Z [0;31mError:[0m Dependencies in integration-tests/gradle/pom.xml are outdated!
2021-03-19T16:09:27.9825731Z [0;31mError:[0m Run update-dependencies.sh in integration-tests/gradle and add the modified pom.xml file to your commit.
2021-03-19T16:09:27.9833233Z ##[error]Process completed with exit code 1.
````
@famod I am not sure how to do that. Running the script from the gradle module fails. Simply running the script from the root does not change anything.

**Comment by famod** [comment]
@aloubyansky What error are you getting? Please don't tell me you are using a Mac (#15823)... 😨

**Comment by aloubyansky** [comment]
I pasted the error in my previous comment. I copied it from the CI logs.

**Comment by famod** [comment]
That's the error from CI. But what are you getting locally when running `update-dependencies.sh` in `integration-tests/gradle`?

**Comment by aloubyansky** [comment]
Ah, sorry, I got confused. There is also the version of the script right in that module. If I execute it, it removes the dependency I added in this PR
````
-        <dependency>
-            <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-core-codestarts</artifactId>
-            <type>pom</type>
-            <scope>test</scope>
-            <exclusions>
-                <exclusion>
-                    <groupId>*</groupId>
-                    <artifactId>*</artifactId>
-                </exclusion>
-            </exclusions>
-        </dependency>
````
It's not an extension but given that that jar should have been built I added this pom dependency.

**Comment by famod** [comment]
@aloubyansky 
> @famod so, I went ahead and removed all the dependencies from the `quarkus-platform-descriptor-json` (which is not a descriptor json at all and now is renamed to `quarkus-core-codestarts`). Can you think of consequences on the incremental build?

Well, it seems we now don't need that `incremental` profile anymore in `devtools/bom-descriptor-json`:
```
mvn -pl devtools/bom-descriptor-json -amd validate
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Quarkus - BOM - Descriptor JSON                                    [pom]
[INFO] Quarkus - Integration Tests - Maven tooling                        [jar]
[INFO]
```
So we do _not_ have to "disable" all the dependencies from `bom-descriptor-json` to all the extensions anymore (to stop running all ITs in case just a single extension was changed).
Now, whether or not it is correct that changes to `bom-descriptor-json` itself (or any of it's non-extension upstream modules) do _not_ trigger any ITs anymore (apart from "Maven tooling") is something that I cannot fully answer.

I can move those dependencies out of the profile in a separate PR or you can do it in this PR. If you do, please remove this bit:
https://github.com/quarkusio/quarkus/blob/main/.github/workflows/ci-actions-incremental.yml#L94-L95
and please switch `-Pincremental` to `-Dincremental`.

**Comment by famod** [comment]
@aloubyansky and about this:
```
So we need to somehow make sure the build order is correct. I was thinking about adding a dependecy on `quarkus-core-codestarts:pom` from the `quarkus-extensions-parent`, this doesn't look nice though.
```
This would mean that a change to `quarkus-core-codestarts` would trigger _all_ extensions to be built and in turn all their ITs!
Doesn't seem like a good idea...unless we introduce such an `incremetal` profile workaround as in `bom-descriptor-json`.

**Comment by aloubyansky** [comment]
Right. We just need the devtools IT (maven, gradle, devtools) to depend on the codestarts artifact.

**Comment by aloubyansky** [comment]
Actually, the json descriptor artifact has the same requirement as the codestarts above from testing perspective.

**Comment by aloubyansky** [comment]
@famod I think there is an issue with the `integration-tests/gradle/update-dependencies.sh` I am trying to add a dependency on the pom of `quarkus-project-core-extension-codestarts` (previously `quarkus-core-codestarts`) with 
````
 dependencies {
+    testImplementation "io.quarkus:quarkus-project-core-extension-codestarts:${version}@pom"
````
in the `build.gradle` and 
````
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-project-core-extension-codestarts</artifactId>
+            <version>${project.version}</version>
+            <type>pom</type>
+            <scope>test</scope>
+            <exclusions>
+                <exclusion>
+                    <groupId>*</groupId>
+                    <artifactId>*</artifactId>
+                </exclusion>
+            </exclusions>
+        </dependency>
````
in the `pom.xml`. But if I launch the script it changes the pom to
````
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-project-core-extension-codestarts</artifactId>
+            <version>${project.version}</version>
+        </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-resteasy</artifactId>
@@ -154,6 +159,19 @@
                 </exclusion>
             </exclusions>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-project-core-extension-codestarts-deployment</artifactId>
+            <version>${project.version}</version>
+            <type>pom</type>
+            <scope>test</scope>
+            <exclusions>
+                <exclusion>
+                    <groupId>*</groupId>
+                    <artifactId>*</artifactId>
+                </exclusion>
+            </exclusions>
+        </dependency>
````
and then fails to resolve the deployment, of course. It shouldn't be assuming that this pom dependency pattern is reserved for extension artifacts. Would that be difficult to fix? Thanks.

**Comment by famod** [comment]
@aloubyansky 
Just add something like `-e '/-extension-codestarts/d'` here: https://github.com/quarkusio/quarkus/blob/main/integration-tests/gradle/update-dependencies.sh#L58

But it will still add a non-deployment dependency (without exclusions) and I think this is ok. Those deps won't be really used anyway.

**Comment by aloubyansky** [comment]
I could just add that in place of the pom one, right?

**Comment by famod** [comment]
> I could just add that in place of the pom one, right?

If you want to do it manually you can of course do it. Or you can just watch what happens when you run the script. 😉 

There is also another approach:
By adding the mentioned deletion expression here, the script would ignore that gradle dep entirely:
https://github.com/quarkusio/quarkus/blob/main/integration-tests/gradle/update-dependencies.sh#L38
You would then have to add it manually.

**Comment by aloubyansky** [comment]
If I leave the "runtime" one, it still adds the deployment one apparently.

**Comment by famod** [comment]
Have you added `-e '/-extension-codestarts/d'` to the script?

**Comment by aloubyansky** [comment]
No, i thought it wouldn't be necessary.

**Comment by famod** [comment]
You must tell the script to either ignore it only for the deployment part or entirely (manual addition is then required).

**Comment by famod** [comment]
Rationale: The script is extracting all Quarkus artifact ids from all gradle build files, applies a filter (=line deletions), creates "runtime" dep entries and then applies another filter and adds deployment dep entries.

**Comment by aloubyansky** [comment]
Why is adding the `-deployment` dep for 
````
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-project-core-extension-codestarts</artifactId>
            <version>${project.version}</version>
        </dependency>
````
though?

**Comment by famod** [comment]
Because it is not yet filtered (unless you added the line deletion expression already).
See also:
- https://github.com/quarkusio/quarkus/blob/main/integration-tests/gradle/update-dependencies.sh#L55-L56
- https://github.com/quarkusio/quarkus/blob/main/integration-tests/gradle/update-dependencies.sh#L58

**Comment by aloubyansky** [comment]
Ok, thanks!

**Comment by aloubyansky** [comment]
I should just remove it from build.gradle

**Comment by famod** [comment]
If it's not required, neither for the gradle test execution nor for the maven build order, then it should go.

**Comment by aloubyansky** [comment]
The artifact must be built for the gradle testsuite.

**Comment by aloubyansky** [comment]
Hm, the script simply removes it unless it's in build.gradle.

**Comment by famod** [comment]
> Hm, the script simply removes it unless it's in build.gradle.

I won't if you put it before
```xml
<!-- START update-dependencies.sh -->
```
or after
```xml
<!-- END update-dependencies.sh -->
```

**Review by ia3andy — APPROVED** [review]
Looking great! 

We will still need to move the `codestarts/quarkus/core` and `codestarts/quarkus-jbang` codestarts to `devtools-common` so we only keep the extensions codestarts in `quarkus-project-core-extension-codestarts`. The reason is also that those codestarts are more tied to the api so better bring them alongside it..

**Pull request merged**
