### PR TITLE
Interceptor bindings must not be inherited from interfaces

### LINKED ISSUE #11704: Interceptor bindings must not be inherited from interfaces implemented by a bean
https://github.com/quarkusio/quarkus/commit/d2321964a08e3cfd8583767d590be842e4679b61 introduced a regression where interceptor bindings are inherited from interfaces implemented by a bean.

The spec is very clear that this should not be possible. See https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#inheritance for more info. JSR-250 also mentions in the "General Guidelines for Inheritance of Annotations":
> The interfaces implemented by a class never contribute annotations to the class itself or any of its members.

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #11704

### CODE REVIEW

**Comment by mkouba** [comment]
CC @famod @gsmet

**Comment by famod** [comment]
Did you try it with my reproducer? If not I could do that later today evening (at the earliest).

**Comment by mkouba** [comment]
> Did you try it with my reproducer? If not I could do that later today evening (at the earliest).

Not yet. It would be great if you could try it ;-)

**Review by manovotn — APPROVED** [review]

**Comment by jaikiran** [comment]
Merging this. The JVM tests have all passed except on Windows Java 11. That one is failing with a known issue being tracked in https://github.com/quarkusio/quarkus/issues/11711

**Comment by famod** [comment]
Fix confirmed with my reproducer. Thanks!

**Pull request merged**
