### PR TITLE
Bump to Vert.x 4.3.1 and Netty 4.1.78

### PR DESCRIPTION
**Pull request by cescoffier**
This new combination is tricky. It imposes to have brotli4j available in the classpath as, because of the new HTTP compression feature from vert.x, it does now have a hard dependency on brotli4j. While in JVM mode, everything is fine, native compilation fails if not there. We have tried a few things to avoid the dependency, but we are hitting https://github.com/oracle/graal/issues/4652.

### CODE REVIEW

**Comment by cescoffier** [comment]
@Sanne @DavideD - looks like we will be able to update to Vert.x 4.3.1. Do you have any concerns on your side?

**Comment by DavideD** [comment]
On the current `main` branch of Hibernate Reactive we are already using 4.3.1. It shouldn't be a problem for us.

**Comment by Sanne** [comment]
@cescoffier great to hear :) and no concerns, it all seems under control :100:

**Comment by cescoffier** [comment]
@Sanne yes, that's the only issue. It even gets eliminated during the native compilation.

**Review by Sanne — APPROVED** [review]

**Pull request merged**
