### PR TITLE
[3.8] 3.8.5 backports 4

### PR DESCRIPTION
**Pull request by gsmet**
Please don't merge, I will merge it myself.

We will have to merge https://github.com/quarkusio/quarkus/pull/40776 first and then wait until the beginning of June before merging to make sure we have sufficient bake time.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by yrodiere — APPROVED** [review]
LGTM for the Narayana backport.

**Comment by rsvoboda** [comment]
@gsmet ` Move reinitialization of vertx classes out of NettyProcessor ` commit is in both backport nr. 3 and backport nr. 4

**Comment by gsmet** [comment]
Yes, that's normal. I will rebase this one once the other one is in. I didn't want to have conflicts.

**Comment by gsmet** [comment]
Something odd happened in a Gradle module... I rebased now that the previous one was merged.

**Comment by yrodiere** [comment]
```
2024-05-23T12:27:15.0779376Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project quarkus-hibernate-orm-deployment: 
2024-05-23T12:27:15.0781021Z [ERROR] 
2024-05-23T12:27:15.0783411Z [ERROR] Please refer to /home/runner/work/quarkus/quarkus/extensions/hibernate-orm/deployment/target/surefire-reports for the individual test results.
2024-05-23T12:27:15.0785680Z [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
2024-05-23T12:27:15.0786828Z [ERROR] There was an error in the forked process
2024-05-23T12:27:15.0787471Z [ERROR] Metaspace
2024-05-23T12:27:15.0787958Z [ERROR] java.lang.OutOfMemoryError: Metaspace
2024-05-23T12:27:15.0788851Z [ERROR] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
2024-05-23T12:27:15.0789976Z [ERROR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
2024-05-23T12:27:15.0791428Z [ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:513)
2024-05-23T12:27:15.0793122Z [ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:473)
2024-05-23T12:27:15.0794803Z [ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:523)
2024-05-23T12:27:15.0796479Z [ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:473)
2024-05-23T12:27:15.0797845Z [ERROR] 	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
2024-05-23T12:27:15.0798847Z [ERROR] 	at java.base/java.lang.Class.forName0(Native Method)
2024-05-23T12:27:15.0799730Z [ERROR] 	at java.base/java.lang.Class.forName(Class.java:534)
2024-05-23T12:27:15.0800611Z [ERROR] 	at java.base/java.lang.Class.forName(Class.java:513)
2024-05-23T12:27:15.0801740Z [ERROR] 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:269)
2024-05-23T12:27:15.0803058Z [ERROR] 	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:662)
2024-05-23T12:27:15.0804876Z [ERROR] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:396)
2024-05-23T12:27:15.0807292Z [ERROR] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda/0x00007f6ebc188000.execute(Unknown Source)
2024-05-23T12:27:15.0809220Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-23T12:27:15.0811652Z [ERROR] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:396)
2024-05-23T12:27:15.0813762Z [ERROR] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:212)
2024-05-23T12:27:15.0815634Z [ERROR] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:85)
2024-05-23T12:27:15.0825918Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
2024-05-23T12:27:15.0827852Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f6ebc122220.execute(Unknown Source)
2024-05-23T12:27:15.0829706Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-23T12:27:15.0831767Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2024-05-23T12:27:15.0833811Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f6ebc122000.invoke(Unknown Source)
2024-05-23T12:27:15.0835506Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2024-05-23T12:27:15.0837330Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2024-05-23T12:27:15.0839347Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x00007f6ebc127340.execute(Unknown Source)
2024-05-23T12:27:15.0841157Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-23T12:27:15.0843113Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2024-05-23T12:27:15.0844983Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2024-05-23T12:27:15.0847064Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda/0x00007f6ebc122d10.accept(Unknown Source)
2024-05-23T12:27:15.0848898Z [ERROR] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
2024-05-23T12:27:15.0850942Z [ERROR] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
```

You must be kidding... :nauseated_face:

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
My ack still applies after the recent updates.

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
