### PR TITLE
Pr issue 9846

### PR DESCRIPTION
**Pull request by jglink**
PullRequest to demonstrate https://github.com/quarkusio/quarkus/issues/9846

Calling `mvn quarkus:dev` on the integration-test/liquibase folder will show the issue

### CODE REVIEW

**Comment by machi1990** [comment]
@jglink thanks for the PR. I think it needs a clean rebase.

**Comment by jglink** [comment]
Ah, sorry.
I created the PR for 1.5 branch not for master

**Comment by gsmet** [comment]
I changed the base of the PR to 1.5.

**Comment by geoand** [comment]
Superceded by #9881

**Pull request closed without merging**
