### PR TITLE
Remove dependency on quarkus-oidc from keycloak-admin-client

### PR DESCRIPTION
**Pull request by aloubyansky**
Mentioned in #13056

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Thanks Alexey

**Comment by sberyozkin** [comment]
It is the GRPC dev test failing on Windows

**Comment by gsmet** [comment]
Yeah I pinged Clément and Michal. We can ignore it for now.

**Comment by sberyozkin** [comment]
@gsmet thanks. let me merge it then

**Pull request merged**
