### PR TITLE
Bump to Hibernate 5.6.3.Final

### PR DESCRIPTION
**Pull request by gastaldi**
It finally undeprecates the TypeDef annotations

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
thanks for preparing the PR!

**Comment by gastaldi** [comment]
Any chance to backport this PR to 2.6.1.Final?

**Comment by Sanne** [comment]
> Any chance to backport this PR to 2.6.1.Final? ([#22114 (comment)](https://github.com/quarkusio/quarkus/pull/22114#issuecomment-991246536))

I have no strong objections but there's no strong reason to do it either... just a little risk. IMO it's best to calm down a little with backports, unless there's good reasons, no? People will get it soon, it's not like 2.7 will take ages :)

**Comment by gastaldi** [comment]
@Sanne for me the removal of the deprecation warnings is the main driver to get it asap but I think we can wait for 2.7 next year :)

**Comment by famod** [comment]
Looking at https://github.com/quarkusio/quarkus/pull/22925#issue-1105018754 and given it's marked for imminent 2.6.3, isn't this going to break projects that are using currently latest blaze-persistence 1.6.4?

/cc @beikov @gsmet

**Comment by gsmet** [comment]
Not sure to understand? Current version of BP in Quarkus is not compatible with 5.6.3?

**Comment by famod** [comment]
@gsmet I got that impression from https://github.com/Blazebit/blaze-persistence/issues/1413

**Comment by beikov** [comment]
There is a breaking change in the `org.hibernate.hql.spi.id.MultiTableBulkIdStrategy` SPI in 5.6.3.Final but AFAIU the change is necessary. Not sure if we can somehow make the change in Hibernate in a backwards compatible way, but I'll look into this tomorrow.

**Comment by famod** [comment]
Just checked my project (which is using `blaze-persistence-integration-hibernate-5.4`) with current Quarkus main (which has Hibernate 5.6.3) and I'm no seeing any issues.
So I suppose this error only pops up if using some specific BP feature.

**Comment by beikov** [comment]
Are you overriding the `hibernate.hql.bulk_id_strategy` config property?

**Comment by famod** [comment]
No, we don't.

**Comment by beikov** [comment]
Then the contributor is maybe not applied correctly when using Quarkus for some reason. I'll dig into that.

**Comment by famod** [comment]
Hum, we are generating the ids of our entities on our own (UUIDs), so maybe that's the reason?

**Comment by gsmet** [comment]
@beikov @Sanne we need this sorted out before Wednesday evening. Either by avoiding the SPI breakage or by integrating a new BP version in the Platform for 2.6.3.Final.

**Comment by beikov** [comment]
Ok, so the Quarkus Hibernate bootstrap somehow strips off configuration values contributed in MetadataContributor implementations, which is why https://github.com/Blazebit/blaze-persistence/issues/1413 is not an issue for Quarkus users. 

Working on a fix for that now.

Apart from that, yes, I think that we should try to get a Hibernate 5.6.4.Final out that avoids breaking SPIs. I'll work on that first thing on Monday.

**Comment by beikov** [comment]
FYI I created https://hibernate.atlassian.net/browse/HHH-15032 for the issue.

**Comment by Sanne** [comment]
I was about to tag `5.6.4.Final` but I'll hold off for now

**Pull request merged**
