### PR TITLE
Update versions used in codestarts generation

### LINKED ISSUE #14479: Surefire plugin has version 2.22.1 in bootstrap app for 1.11, 1.7 had 3.0.0-M5
Surefire plugin has version 2.22.1 in bootstrap app for 1.11, 1.7 had 3.0.0-M5.
Qurkus codebase is using 3.0.0-M5 too.

1.11.0.Final:
```xml
  <properties>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>    <==  HERE ...
    <quarkus.platform.version>1.11.0.Final</quarkus.platform.version>
    <maven.compiler.target>8</maven.compiler.target>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <quarkus-plugin.version>1.11.0.Final</quarkus-plugin.version>
    <maven.compiler.source>8</maven.compiler.source>
  </properties>
```

1.7.6.Final
```xml
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.7.6.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.7.6.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>    <==  HERE ...
  </properties>
```

Used commands:
```
mvn io.quarkus:quarkus-maven-plugin:1.11.0.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started \
  -DclassName="org.acme.getting.started.GreetingResource" -Dpath="/hello"
mvn io.quarkus:quarkus-maven-plugin:1.7.6.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started-old \
  -DclassName="org.acme.getting.started.GreetingResource" -Dpath="/hello" -DplatformVersion=1.7.6.Final
```

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #14479

@rsvoboda I think this will fix #14479 but... I also think this file should be generated (via Maven filtering for instance) as otherwise this will be a chronic issue. @ia3andy could you have a look at that part?

### CODE REVIEW

**Comment by famod** [comment]
Maven resource filtering sounds good, but we need to be careful with the compiler-plugin (which is a jboss fork, which is actually not really necessary for Quarkus, as far as I understood the respective discussions on Zulip).

**Comment by gsmet** [comment]
@famod we have the correct version here: https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L23

Before codestarts, it used to come from this property.

**Comment by famod** [comment]
Ok, so we just need to use the correct property then.

**Comment by ia3andy** [comment]
> @famod we have the correct version here: [https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L23](https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml?rgh-link-date=2021-01-21T13%3A27%3A40Z#L23)
> 
> Before codestarts, it used to come from this property.

Then it should be fairly easy to use it again :) I'll have a look!

**Comment by ia3andy** [comment]
Superseded by #14489

**Pull request closed without merging**
