### PR TITLE
Removing jsr305 as dependency to verify if the grpc extension works fine without it

### PR DESCRIPTION
**Pull request by harshmadhani**
Removing jsr305 as dependency to verify if the grpc extension works fine

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@cescoffier it seems it works fine ;)

**Comment by harshmadhani** [comment]
@cescoffier would we still require jsr305 as a dependency in grpc runtime if the checks are passed for them without jsr305?

**Comment by cescoffier** [comment]
@harshmadhani If we can remove it, let's remove it!

**Review by cescoffier — APPROVED** [review]

**Comment by harshmadhani** [comment]
Thanks, @cescoffier !

**Pull request merged**
