### PR TITLE
Avoid resolving plugin command after the first option

### PR DESCRIPTION
**Pull request by gsmet**
Otherwise things like:
quarkus extension -i -s rest
triggers the plugin manager.

### CODE REVIEW

**Comment by gsmet** [comment]
@iocanel can you have a look at this one? I wouldn't want to break a case you want to be working.

**Comment by gsmet** [comment]
@maxandersen can you check I didn't break some of your use cases with this patch?

**Comment by maxandersen** [comment]
i'll try out - my first thought is if it breaks `quarkus deploy xyz` was intended to lookup `quarkus-deploy-xyz` where `quarkus deploy -i -x xyz` should be okey to skip.

**Comment by maxandersen** [comment]
hmm - i dont seem able to build this PR ? 

`Could not find goal 'extension-descriptor' in plugin io.quarkus:quarkus-extension-maven-plugin:999-SNAPSHOT among available goals`
 
 build scan: https://ge.quarkus.io/s/zdneznjlyphpu

**Comment by gsmet** [comment]
I don't see how this change could trigger that.

**Comment by iocanel** [comment]
> my first thought is if it breaks `quarkus deploy xyz` as that is intended to lookup `quarkus-deploy-xyz` where `quarkus deploy -i -x xyz` should be okey to skip.

100% agree. 
A plugin may be added to any of the existing sub commands and we should make sure that this is not broken by this.

**Comment by gsmet** [comment]
`quarkus deploy xyz` should still work, I didn't change that.

What wouldn't be supported is `quarkus deploy -i xyz`. In this case it won't look for `quarkus-deploy-xyz` but that's exactly what I was trying to fix :).

Note that the current behavior is quite annoying for anything that has a default subcommand such as `quarkus extension` so I would really like to get this in.

**Comment by gsmet** [comment]
Ping?

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
