### PR TITLE
Added tests to Config, to ensure backwards compatibility.

### LINKED ISSUE #10570: Devmode, Regression in 1.6.0: Cannot override property from profile via system property
**Describe the bug**
Overriding a property that is defined in the `%dev` profile via system property (`-D...`) does not work anymore.

**Expected behavior**
System property must take precedence (as in 1.5.2 or lower)

**Actual behavior**
Profile in properties/yaml takes precedence.

**To Reproduce**
1. Clone https://github.com/famod/quarkus-quickstarts
2. `git switch devmode-port-override`
3. `cd getting-started`
4. `mvn clean verify`
5. `mvn quarkus:dev` starts on port 2081
6. `mvn quarkus:dev -Dquarkus.http.port=0` (or any other port) still starts on port 2081
7. remove profile prefix from property or remove entire property in `application.properties`
8. `mvn quarkus:dev -Dquarkus.http.port=0` starts with desired port

**Configuration**
```properties
%dev.quarkus.http.port=2081
```

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
    ```
    MINGW64_NT-10.0-18363 BIGBLUE 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys
    ```
 - Output of `java -version`: 
    ```
    openjdk version "11.0.7" 2020-04-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
    ```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

### PR DESCRIPTION
**Pull request by radcortez**
This is the initial PR to fix #10570. It only requires an update to a release of SmallRye Config 1.8.2, but wanted to add the tests to make sure we don't break stuff.

Additional, I've added the same set of tests in a 1.5.0 branch, to make sure we keep the same behaviour: https://github.com/radcortez/quarkus/tree/config-1.5

One test is failing due to the missing update of SmallRye Config that will fix it.

### CODE REVIEW

**Comment by geoand** [comment]
CI seems to be misbehaving, tests didn't even start :confused:

**Comment by radcortez** [comment]
Yes, GH seems to be unstable today. I guess we need to wait until is sorted and then restart.

**Comment by radcortez** [comment]
@geoand seems to be better today :)

Are we still maintaining 1.5x branch somehow? I can push the test code there as well, so we can see it also passes. Or you can just check it out and run it locally :D

https://github.com/radcortez/quarkus/tree/config-1.5

The more comprehensive set of tests should pass both in 1.5 (before the switch to SR Config) and in 1.6 (after the switch). If you look into both classes, the tests are the same, just some slight differences in the tests initialization:

1.5 - https://github.com/radcortez/quarkus/blob/config-1.5/core/runtime/src/test/java/io/quarkus/runtime/configuration/ConfigProfileTestCase.java

1.6  - https://github.com/radcortez/quarkus/blob/config/core/runtime/src/test/java/io/quarkus/runtime/configuration/ConfigProfileTestCase.java

**Comment by geoand** [comment]
@radcortez nope, 1.5 is no longer maintained

**Comment by geoand** [comment]
So if everything works against 1.6 / master, we should merge

**Comment by radcortez** [comment]
> @radcortez nope, 1.5 is no longer maintained

Sure,  this was just if we wanted to have an extra layer of security that we are not breaking more things :(

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand the idea was to backport that one to 1.6.1, right?

**Comment by geoand** [comment]
Yes, exactly

**Pull request merged**
