### PR TITLE
Update to GraalVM 21.1

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by zakkak** [comment]
Marking as draft until the tests complete on my fork.

**Review by gsmet — APPROVED** [review]
Cool, thanks!

**Comment by zakkak** [comment]
Things look good. The only failure I see is related to https://github.com/quarkusio/quarkus/issues/14139

**Comment by gsmet** [comment]
@zakkak so shouldn't we disable the test? I don't see it in your PR?

**Comment by zakkak** [comment]
> @zakkak so shouldn't we disable the test? I don't see it in your PR?

@gsmet can you please advise on how to disable it? Should I just remove the test from `native-tests.json`?

**Comment by gsmet** [comment]
You should be able to use `@DisabledOnNativeImage` and make @sberyozkin aware of it so he doesn't forget to remove it when he fixes the issue.

**Comment by zakkak** [comment]
> Things look good. The only failure I see is related to #14139

It looks like I am wrong about this, there is another failure on bouncycastle-jsse, see https://github.com/quarkusio/quarkus/issues/17046

The test is now disabled.

**Comment by sberyozkin** [comment]
@zakkak Thanks

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
