### PR TITLE
Let Maven start and stop the Docker images and other CI adjustments

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@machi1990 I just stumbled upon the fact that the Redis integration tests do not have a `docker` profile allowing to start Redis from Maven. Any chance you could take care of that?

**Comment by machi1990** [comment]
> @machi1990 I just stumbled upon the fact that the Redis integration tests do not have a `docker` profile allowing to start Redis from Maven. Any chance you could take care of that?

Sure. Okay, do you want me to push a commit in this branch or on a separate PR?

**Comment by gsmet** [comment]
Keep it on your side for now. I want this PR to run fully :). But you can push to it tomorrow, I'm on PTO.

Don't forget the docker prune script. There are a few examples in existing modules.

**Comment by gsmet** [comment]
A good example: https://github.com/quarkusio/quarkus/blob/master/integration-tests/jpa-postgresql/pom.xml#L206

**Comment by machi1990** [comment]
> Keep it on your side for now. I want this PR to run fully :). But you can push to it tomorrow, I'm on PTO.
> 
> Don't forget the docker prune script. There are a few examples in existing modules.

Sure, I had all the resources I needed :-) 

PR opened here https://github.com/quarkusio/quarkus/pull/11686

**Review by geoand — APPROVED** [review]

**Pull request merged**
