### PR TITLE
Support custom MessageBodyWriters and MessageBodyReaders

### PR DESCRIPTION
**Pull request by gastaldi**
eg. YAML is now supported by simply adding a dependency to com.fasterxml.jackson.jaxrs:jackson-jaxrs-yaml-provider

### CODE REVIEW

**Comment by geoand** [comment]
Hm, actually there is probably an easier way to do this.

I am thinking that the resteasy-jackson can just register this provider

**Comment by gastaldi** [comment]
How so? Got an example?

**Comment by geoand** [comment]
I don't since I'm on my phone now, but I think that just looking at the code of that extension should give you a hint.

I may be totally misremembering though, so I'll have to get back to you later for sure

**Comment by geoand** [comment]
So I think of automatically registering all those providers, I think it would be best if in the `RestEasyJacksonProcessor` you register `JacksonJaxbYAMLProvider` if that class is available.

**Comment by geoand** [comment]
@jmartisk seems like one of the TCK tests is flaky:

```
2020-05-21T18:02:00.0574980Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.642 s <<< FAILURE! - in org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedClassBeanTest
2020-05-21T18:02:00.0668086Z [ERROR] countedMethodsNotCalledYet(org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedClassBeanTest)  Time elapsed: 0.015 s  <<< FAILURE!
2020-05-21T18:02:00.0720627Z java.lang.AssertionError: Max value of metric MetricID{name='org.eclipse.microprofile.metrics.tck.metrics.cGaugedClass.ConcurrentGaugedClassBean', tags=[tier="integration"]} should be 0 expected:<0> but was:<1>
```

Can you please take a look when you have some time?

**Comment by jmartisk** [comment]
@geoand https://github.com/quarkusio/quarkus/pull/9528 should fix that

**Comment by gastaldi** [comment]
I'll add a simple test

**Pull request closed without merging**
