### PR TITLE
Move Kubernetes to @ConfigMapping

### LINKED ISSUE #35608: Fallback specialized kubernetes config to vanilla kubernetes not working
Hi @radcortez / @Sgitario / @iocanel should this feature (see #34487 & #34025) have made it into the `3.3.0`release? If so, it does not seem to work fully.

If I specify the following (the `kubernetes`, `openshift`, `knative,` and `minikube` extensions are all present):

```properties
quarkus.kubernetes.part-of=villains-service
quarkus.kubernetes.annotations."app.openshift.io/connects-to"=villains-db,otel-collector
quarkus.kubernetes.env.configmaps=${quarkus.application.name}-config
quarkus.kubernetes.env.secrets=${quarkus.application.name}-config-creds
quarkus.kubernetes.labels.app=${quarkus.application.name}
quarkus.kubernetes.labels.application=${quarkus.kubernetes.part-of}
quarkus.kubernetes.labels.system=quarkus-super-heroes
quarkus.openshift.route.expose=true
```

when the OpenShift & KNative resources are generated, the resources (the OpenShift `DeploymentConfig` and the KNative `Service`) do not have the expected annotations or labels. They do, however, have the expected `ConfigMap`s and `Secret`s.

The minikube `Deployment`, though, does look to be ok. 

I'm not sure if this is because for OpenShift/Knative the resource types are different (kubernetes `Deployment` vs OpenShift `DeploymentConfig`/KNative `Service`)?

In any event, it does not work as expected.

_Originally posted by @edeandrea in https://github.com/quarkusio/quarkus/issues/34487#issuecomment-1692168040_

### PR DESCRIPTION
**Pull request by radcortez**
- Uses a hierarchy to share standard configurations between Kubernetes, OpenShift, and Knative for #35608.
- Separate commits:
  - Tests for the old config to ensure no breakage
  - Move to `@ConfigMapping`
  - Adjusted the fallback mechanism

- Fixes #35608

Only shared configuration between `quarkus.kubernetes`, `quarkus.openshift` and `quarkus. native` can be set in `quarkus.kubernetes`. There is configuration that is only shared between `quarkus.kubernetes` and `quarkus.openshift`, which needs to be set separately (for instance `quarkus.kubernetes.replicas` and `quarkus.openshift.replicas`.

### CODE REVIEW

**Comment by radcortez** [comment]
@edeandrea would you like to try this out?

**Comment by radcortez** [comment]
Great. Thanks!

**Comment by geoand** [comment]
@iocanel are you okay with this?

**Review by iocanel — APPROVED** [review]
Skimmed through the changes. They look reasonable to me.

**Comment by metacosm** [comment]
Will these changes be documented? Also, I noticed that the OpenShift config got renamed but not the processor, might as well do this as well… 😄

**Pull request merged**
