### PR TITLE
Use proper header name

### PR DESCRIPTION
**Pull request by geoand**
Follows up on #26467 which seems to have introduced
flakyness

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by evanchooly** [comment]
> @evanchooly `NamedMongoClientConfigTest` is failing a lot lately. I might have to do with your recent change

I know we ran in to an issue doing the PR builds on windows but I disabled those tests on windows.  Is it still a problem?

**Comment by geoand** [comment]
Yes, a lot of PRs have been failing today with this same exact failure

**Comment by geoand** [comment]
The tests were all green, sure, but the failure happens way to often now 🙂.
I don't think it's a coincidence that a mongo change was made and suddenly we have this consistent failure.

I don't know if it's a flaky test or an actual problem, what I do know is that it needs to be sorted out.

**Comment by gsmet** [comment]
@evanchooly  You cannot use Docker on Windows in GitHub Actions. Why did you change the test infrastructure? Was there a good reason?

**Pull request merged**
