### PR TITLE
Register arrays of Hibernate ORM's JDBC basic types for reflection 

### LINKED ISSUE #34071: 3.1.1 Final - java.lang.IllegalArgumentException: Class java.util.UUID[] is instantiated reflectively but was never registered
### Describe the bug

Upgrading from 3.1.0 Final to 3.1.1 Final leads to this is native mode only

```
2023-06-15 18:20:45.00 UTCgreetings-68cc87fc5-dvgsf[pod-event]Successfully pulled image "registry.cloud.okteto.net/amoscatelli/greetings:1.0.4" in 242.613097ms (242.629307ms including waiting)
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings__ ____ __ _____ ___ __ ____ ______ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings--\___\_\____/_/ |_/_/|_/_/|_|\____/___/ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings18:31:02 WARN traceId=, parentId=, spanId=, sampled= [io.qu.ru.co.ConfigRecorder] (main) Build time property cannot be changed at runtime:
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings - quarkus.http.root-path is set to '/greetings' but it is build time fixed to '/'. Did you change the property quarkus.http.root-path after building the application?
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings18:31:02 WARN traceId=, parentId=, spanId=, sampled= [io.qu.op.ru.ex.ot.LateBoundBatchSpanProcessor] (main) No BatchSpanProcessor delegate specified, no action taken.
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings18:31:04 ERROR traceId=, parentId=, spanId=, sampled= [io.qu.ru.Application] (main) Failed to start application (with profile [prod]): java.lang.IllegalArgumentException: Class java.util.UUID[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.arrayHubErrorStub(SubstrateAllocationSnippets.java:345)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.loader.ast.internal.EntityBatchLoaderArrayParam.prepare(EntityBatchLoaderArrayParam.java:176)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.persister.entity.AbstractEntityPersister.prepareLoader(AbstractEntityPersister.java:3425)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.persister.entity.AbstractEntityPersister.postInstantiate(AbstractEntityPersister.java:3419)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:204)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.internal.SessionFactoryImpl.initializeMappingModel(SessionFactoryImpl.java:320)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:270)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.1.1 Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #34071

Essentially this is a workaround for https://hibernate.atlassian.net/browse/HHH-16809, which from the looks of it is not considered a priority and won't be solved anytime soon.

See also https://github.com/hibernate/hibernate-orm/pull/6815#issuecomment-1662197545

And before anyone (i.e. @Sanne ;) ) tells me "you could have tried to detect which of those types are actually useful for a given application"... yes, I could have, but:

1. I'd need to process `@Id`, `@IdClass`/`@EmbeddedId` with a single column, XML mapping, ...
2. I couldn't do it with perfect accuracy, because it's the JDBC type that matters, and that's not the same as the property type. `AttributeConverter` being one example, but there are probably others.
3. GraalVM's "features" are not a viable option either as JDBC types are all reachable through a map (i.e. GraalVM cannot distinguish being one type being retrieved or another).
4. Frankly we're talking about just a few standard Java types (and not even those types, just *their array types*), so let's not bother.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Looks good as a workaround!

**Comment by Sanne** [comment]
Many thanks, nice to see this resolved.

For the future I'm thinking to propose an explicit SPI in ORM core: a service for ORM code itself to register elements for reflective access? It could be a no-op in regular use, but frameworks like Quarkus (and possibly others) would be able to collect types and register them on GraalVM explicitly.  But I wonder if it's a good ideas, as its usefulness depends on how many of such cases we're having (certainly this case adds to an existing list), and testing for it to be thoroughly applied seems tricky - perhaps it's unnecessarily complex.

Thoughts?

**Comment by yrodiere** [comment]
I'm not sure this SPI really is necessary... Seems to me it would be exactly as effective, and perhaps more generic, to just have Hibernate ORM correctly avoid all dynamic, runtime reflection and instead store `Constructor`/`Method`/`Field`/`MethodHandle` in its `Metadata`? Then IIUC GraalVM is perfectly able to deduce that those constructors/methods/fields will be accessed at runtime (at least in Quarkus, as they will be put on the heap during static init).

> certainly this case adds to an existing list

Not sure about that. In this instance, the problem really is that Hibernate ORM does something like `Arrays.newArray( <some variable containing a Class> )`. So, it does dynamic, runtime reflection. If, instead, Hibernate ORM stored the array constructor somewhere in the metadata (e.g. in the `BasicJavaType`), or used some static constructor call (`new Integer[<size>]`), then we wouldn't have such a problem.

And if you think about it, changing Hibernate ORM to use the new SPI probably has very similar cost than changing Hibernate ORM to just avoid dynamic, runtime reflection.

**Comment by Sanne** [comment]
> I'm not sure this SPI really is necessary... Seems to me it would be exactly as effective, and perhaps more generic, to just have Hibernate ORM correctly avoid all dynamic, runtime reflection and instead store relevant

I agree in theory, but as this case shows sometimes practical needs hit.

We had agreed with the ORM team to stick to pretty much the guidelines you're describing, but things will naturally fall through the cracks. Which is why I'm wondering if we could have integration tests coverage within ORM to flag such needs earlier - and if we had such an SPI it would be their responsibility to fix right away rather than a "problem for downstream consumers", which inevitably gets us into problems either of twisted release dances or such bugs.

**Comment by yrodiere** [comment]
> and if we had such an SPI it would be their responsibility to fix right away rather than a "problem for downstream consumers",

IMO we'd just get in the same situation, just with an additional SPI adding complexity to the mix and (understandable) resentment/reluctance upstream because it creates additional work upstream for our (very) specific downstream needs.

At least resolving the `Constructor`/`Method`/etc. during metadata creation is arguably a good practice that might lead to (small) performance increases in general, even in JVM mode and with other frameworks, so it's not "just for those Quarkus folks".

I'm not saying "no, we should never do that", I just doubt it will solve the root of the problem, which is that Hibernate ORM doesn't get tested with the same constraints as Quarkus. That JVM agent you talked about some time ago to detect reflection that happens too late (after `Metadata` creation) would be a better angle of approach IMO. At least we'd be able to detect future problems (regressions) and have them fixed upstream as they appear, and we could add an allowlist for existing problems to work on them asynchronously, as time allows. That is, assuming the agent doesn't yield too many false-positives/false-negatives.

**Pull request merged**
