### PR TITLE
Update smallrye reactive messaging to version 2.2.1

### PR DESCRIPTION
**Pull request by cescoffier**
This version fixes a bug when writing a failing Kafka record to the dead-queue topic.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gastaldi** [comment]
The build fails with 

```
[WARNING] 
Dependency convergence error for io.smallrye.common:smallrye-common-annotation:1.0.2 paths to dependency are:
+-io.quarkus:quarkus-smallrye-reactive-messaging:999-SNAPSHOT
  +-io.quarkus:quarkus-arc:999-SNAPSHOT
    +-io.quarkus:quarkus-core:999-SNAPSHOT
      +-io.smallrye.config:smallrye-config:1.8.4
        +-io.smallrye.common:smallrye-common-annotation:1.0.2
and
+-io.quarkus:quarkus-smallrye-reactive-messaging:999-SNAPSHOT
  +-io.smallrye.reactive:smallrye-reactive-messaging-provider:2.2.1
    +-io.smallrye.reactive:smallrye-reactive-messaging-api:2.2.1
      +-io.smallrye.common:smallrye-common-annotation:1.1.0
```

**Comment by gastaldi** [comment]
That's the situation where the BOM would avoid, glad the CI catches this

**Comment by cescoffier** [comment]
I've added smallrye-common-annotation to the bom to avoid the dependency divergence.

**Comment by gastaldi** [comment]
I think it would be safer if we updated smallrye-config too. This commit seems to fix that: https://github.com/smallrye/smallrye-config/commit/3622c231095c4c874f32ea82beb0be7c0466a788

WDYT @radcortez ?

**Comment by gastaldi** [comment]
> I've added smallrye-common-annotation to the bom to avoid the dependency divergence.

Please add it to dependabot too, next to https://github.com/quarkusio/quarkus/blob/master/.github/dependabot.yml#L63

**Comment by cescoffier** [comment]
Are you sure we want automatic updates? I would prefer doing manual updates for a bit. We never know...

**Comment by gastaldi** [comment]
Well, for smallrye-common specifically they are supposed to be bug fixes, so in this case I think so :smiley:

**Comment by radcortez** [comment]
Yes, I need to release a SmallRye Config 1.8.5 with some fixes. It already updated the commons dependency. I was just waiting for a bit to see if we find more issues with Config.

**Comment by cescoffier** [comment]
Ok, I will update the magic updater.

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
