### PR TITLE
Move REST Client configuration to use @ConfigMapping

### PR DESCRIPTION
**Pull request by radcortez**
I've tried to be somehow conservative with the changes (if you can call this PR that :))

The old REST Client configuration performed look-ups to all acceptable names and merged the final configuration. The standard Config system does not support this (and other extensions don't either). It was specifically implemented with the old behaviour, which is also supported in the new implementation via fallbacks, except for a minor breaking change: simple names REST Client names quoted cannot be mixed with unquoted and FQN. This can easily be added if required with another fallback.

- For https://github.com/quarkusio/quarkus/issues/41313
- Removes the CDI dependency from the RestClientConfig
- Removes all the custom config populate code and relies only in the standard Config system

### CODE REVIEW

**Comment by geoand** [comment]
This will conflict head on with https://github.com/quarkusio/quarkus/pull/42100 :)

**Comment by radcortez** [comment]
> This will conflict head-on with #42100 :)

Ops... this was because of https://github.com/quarkusio/quarkus/pull/41948#issuecomment-2237102492. This should also help with the config overhead. The mapping will load and cache the config at startup time.

Sorry for the extra work :(

**Comment by gsmet** [comment]
Yeah, so, I won't fight this one as already done but let's not start a massive rewrite of extensions to `@ConfigMapping` because that makes things a moving target for me. Thanks!

**Comment by geoand** [comment]
> Sorry for the extra work :(

No problem. If we can get something better for REST config, I'm all for it because it's a real pain to maintain

**Comment by radcortez** [comment]
> Yeah, so, I won't fight this one as already done but let's not start a massive rewrite of extensions to `@ConfigMapping` because that makes things a moving target for me. Thanks!

The intent was not to start a massive rewrite of extensions but to fix only the REST Client config since it neither uses the old `@ConfigRoot` class implementation nor `@ConfigMapping`, but a custom-based implementation with CDI dependencies.

One annoying issue is this:
- https://github.com/quarkusio/quarkus/issues/41313

And I guess https://github.com/quarkusio/quarkus/issues/42092, which I overlooked but would also help.

**Review by geoand — APPROVED** [review]
Assuming CI passes, this is great!

**Comment by gsmet** [comment]
At least some of the failures look related.

**Comment by geoand** [comment]
The test failure seems related, but it's probably easily fixable

**Comment by radcortez** [comment]
The problem here is how we handle the test url properties. There is some sanitization code to remove the ending slash and rewrite the configuration as a system property.

Some pieces of the code may see different configuration values depending on when they are executed. In this case, the REST Client configuration was only queried when the REST Client was created (after the test URL was sanitized). Now, it is created at startup (before the test URL was sanitized). For the REST Client execution, the sanitization doesn't matter, but the tracing code asserted the client URL without an ending slash, which was removed by the sanitization.

I've added a separate commit to handle the sanitization at the config level, so all executions should see the same values.

As a separate discussion, we must consider if changing the configuration after startup and rewriting the system properties is the proper behaviour. It is convenient for sure, and we haven't had many issues around it, but I think it is a problem. See also https://github.com/quarkusio/quarkus/pull/41957.

**Comment by geoand** [comment]
> As a separate discussion, we must consider if changing the configuration after startup and rewriting the system properties is the proper behaviour.

We are doing this?

**Comment by radcortez** [comment]
> We are doing this?

Yes. Here are a couple of examples:

- https://github.com/quarkusio/quarkus/blob/eef51383160f95338e09ca5f750ace1d5601d67f/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L273-L274
- https://github.com/quarkusio/quarkus/blob/10654d6a220a5cc9905340de4306bc4cc35e2146/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L1282-L1295

I'm unsure if this is only required for testing or if we have cases where we rely on system properties changed in the `prod` profile. I'll have to analyze it.

**Comment by geoand** [comment]
Okay, those are the ones I had in mind

**Review by gsmet — APPROVED** [review]

**Pull request merged**
