### PR TITLE
Rest Client: exclude weld-api

### LINKED ISSUE #19393: Remove dependency to weld
### Description

quarkus-rest-client transitivly pulls in weld.

This causes some annotations to be present multiple times, from different packages (e.g. javax.enterprise.context.control.ActivateRequestContext and org.jboss.weld.context.activator.ActivateRequestContext)

Can the dependency to weld please be removed?
```
[INFO] │  │     └─ io.quarkus:quarkus-rest-client:jar:2.1.2.Final (compile)
[INFO] │  │        ├─ org.jboss.resteasy:resteasy-client-microprofile:jar:4.7.0.Final (compile)
[INFO] │  │        │  └─ org.jboss.resteasy:resteasy-client-microprofile-base:jar:4.7.0.Final (compile)
[INFO] │  │        │     ├─ org.jboss.resteasy:resteasy-client:jar:4.7.0.Final (compile)
[INFO] │  │        │     │  └─ org.jboss.resteasy:resteasy-client-api:jar:4.7.0.Final (compile)
[INFO] │  │        │     ├─ org.jboss.resteasy:resteasy-cdi:jar:4.7.0.Final (compile)
[INFO] │  │        │     │  └─ org.jboss.weld:weld-api:jar:3.1.SP4 (compile)
[INFO] │  │        │     └─ org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:2.0 (compile)
[INFO] │  │        └─ org.apache.httpcomponents:httpasyncclient:jar:4.1.4 (compile)
[INFO] │  │           └─ org.apache.httpcomponents:httpcore-nio:jar:4.4.14 (compile)
```

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
fixes #19393

### CODE REVIEW

**Comment by gsmet** [comment]
@michalszynkiewicz so we use `resteasy-cdi` but not the underlying `weld-api`?

**Comment by michalszynkiewicz** [comment]
> @michalszynkiewicz so we use `resteasy-cdi` but not the underlying `weld-api`?

yes. I have a branch that removes resteasy-cdi altogether too but as I wrote it requires copying a few classes from resteasy so could be a pain to maintain

**Comment by gsmet** [comment]
FWIW, copying a few classes is what I did for the Hibernate Validator - CDI integration in Quarkus.

But yeah we can see how it goes with just excluding the Weld API: we just need to be sure our tests exercise this so that we catch the issue if at some point a class we use starts using the Weld API.

**Review by manovotn — APPROVED** [review]
Thanks for looking into this @michalszynkiewicz!

**Review by gsmet — APPROVED** [review]

**Pull request merged**
