### PR TITLE
Update Vert.x to version 4.1.0.Beta1

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by cescoffier** [comment]
Let's see how far the CI goes.

**Comment by gsmet** [comment]
@cescoffier things are looking relatively good? WDYT?

**Comment by cescoffier** [comment]
It's looking really good!

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
Looks good, and found no need for any changes in Hibernate Reactive either (we don't need to release one).

Merge?

**Comment by Sanne** [comment]
#Fixed 14608

**Pull request merged**
