### PR TITLE
Fix jar file reference release race condition

### PR DESCRIPTION
**Pull request by pcasaes**
Per instance, close should only be performed once.

Possible solution for https://github.com/quarkusio/quarkus/issues/43158

### CODE REVIEW

**Comment by geoand** [comment]
cc @mariofusco

**Review by mariofusco — CHANGES_REQUESTED** [review]
We designed this class to keep the concurrent state in one single variable, the `referenceCounter`. In general adding a second variable makes the concurrent state no longer atomic and much harder to be coordinated and kept consistent, even though I must admit that in this specific case this additional state is only used to ensure that the close is called only once, so probably there's no need for a coordination with the other variable.

However the atomic state implemented by the `referenceCounter` actually works only under the strict assumption that the close method is called only once, while with this proposed change you're trying to cover the possibility of multiple close invocation, which breaks that assumption.

In essence while this pull request could be acceptable and make the whole design safer, I believe that it is fixing a symptom not the root cause. In other words, before dealing with the possibility that the close is called more than once, I would like to investigate why this is happening and possibly prevent it.

@franz1981 any comment on your side?

**Comment by pcasaes** [comment]
> In essence while this pull request could be acceptable and make the whole design safer, I believe that it is fixing a symptom not the root cause.

I agree 100%. Which is why in the issue I comment that I'm not sure this is the solution
https://github.com/quarkusio/quarkus/issues/43158#issuecomment-2344388615


close can be called more than once because an instance of a reference call be added and removed from the runner's cache many times, all while a happy path acquire/release is taking place.

Maybe the proper solution is to no add references back into the cache once close has been called.

**Comment by pcasaes** [comment]
I wonder if this would be a better change

```
    void close(JarResource jarResource) {
        while (true) {
            var jarFileReference = jarResource.jarFileReference.get();
            if (jarFileReference == null) {
                break;
            } else if (jarResource.jarFileReference.compareAndSet(jarFileReference, null)) {
                release(jarResource);
                break;
            }
        }
    }
```

This would prevent a reference that has been marked as closed from being reused even if there's still counters available.

This does prevent the issue from happening but it would allow multiple instances of the same jar file to "live" concurrently.

**Comment by franz1981** [comment]
@pcasaes I have proposed an alternative solution using a negative value scheme which should work, do you need any help to implement it?

**Comment by pcasaes** [comment]
Oh, here? https://github.com/quarkusio/quarkus/pull/43221#issuecomment-2346280812

**Comment by pcasaes** [comment]
Probably best if yuo do the implementation. I can certainly test it.

**Comment by franz1981** [comment]
FYI @pcasaes https://github.com/quarkusio/quarkus/pull/43257

**Comment by pcasaes** [comment]
This field
https://github.com/quarkusio/quarkus/pull/43257/files#diff-f20997e90aae1d2fe046b512defb1a3e14215b7a834177d43369542bae99a7f6R17

Isn't thread safe. Won't that be a problem?

**Comment by pcasaes** [comment]
@franz1981 Seems to have fixed it. But two things:

I do believe this field needs to be set as volatile (or use atomic reference)
https://github.com/quarkusio/quarkus/pull/43257/files#diff-f20997e90aae1d2fe046b512defb1a3e14215b7a834177d43369542bae99a7f6R17

Can we just return here instead of checking on count again?
https://github.com/quarkusio/quarkus/pull/43257/files#diff-f20997e90aae1d2fe046b512defb1a3e14215b7a834177d43369542bae99a7f6R126-R128

**Comment by franz1981** [comment]
Thanks for the check @pcasaes 

For the volatile is not needed thanks to the barriers surrounding it 

1. Completable future's allocation store "release" the field value 
2. Reading the field requires to call Completable future::getNow/join before, which load "acquire" it

The acquire/release semantics implied happens-before, so we should be fine with weaker architectures like ARM, here, been compliant with the Java Memory Model 9.


Re 
> Can we just return here instead of checking on count again?

The existing algorithm doesn't forcibly free immediately the jar file ref, but try to keep it around till none needed it anymore (an acquire can still happen after a mark close, to save creating a useless new jar file ref again); it means that both release/markForClosing are in the position to move the counter to 0, and that means that both need to check if they have won the race to free it.

For release it can happen only -1 -> 0 (in the code comments) whilst for markForClosing, with 1 -> 0, hence both need to check their own expected ones before freeing the resource and attempt to cleanup the shared atomic reference

**Comment by mariofusco** [comment]
I believe this pull request can be closed as the problem has been fixed by https://github.com/quarkusio/quarkus/pull/43257

**Comment by gsmet** [comment]
Thanks a lot for the efforts! This is superseded by https://github.com/quarkusio/quarkus/pull/43257 .

**Pull request closed without merging**
