### PR TITLE
Confirming that combining tika and narayana-jta has no native image build failures

### LINKED ISSUE #7359: Build error when using quarkus-tika and quarkus-narayana-jta extensions, provider com.ctc.wstx.stax.WstxInputFactory not found
Build error, provider `com.ctc.wstx.stax.WstxInputFactory` not found when using quarkus-tika and quarkus-narayana-jta extensions.

```
rm -rf fooBar
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=io.quarkus.qe \
    -DprojectArtifactId=fooBar \
    -DprojectVersion=1.0.0-SNAPSHOT \
    -DplatformArtifactId=quarkus-bom \
    -DclassName="io.quarkus.qe.MyResource" \
    -Dextensions="quarkus-tika,quarkus-narayana-jta"
mvn -f fooBar/pom.xml clean verify
```
```
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#build threw an exception: javax.xml.stream.FactoryConfigurationError: Provider com.ctc.wstx.stax.WstxInputFactory not found
	at javax.xml.stream.XMLInputFactory.newInstance(Unknown Source)
	at com.arjuna.common.util.propertyservice.PropertiesFactoryStax.loadFromXML(PropertiesFactoryStax.java:46)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.loadFromFile(AbstractPropertiesFactory.java:149)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getPropertiesFromFile(AbstractPropertiesFactory.java:102)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.initDefaultProperties(AbstractPropertiesFactory.java:195)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getDefaultProperties(AbstractPropertiesFactory.java:62)
	at com.arjuna.common.util.propertyservice.PropertiesFactory.getDefaultProperties(PropertiesFactory.java:48)
	at io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor.build(NarayanaJtaProcessor.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Workaround is to add `com.fasterxml.woodstox:woodstox-core` to the deps of the app.

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #7359

### CODE REVIEW

**Comment by aloubyansky** [comment]
Is it simply adding a dependency that's not actually used in the test?

**Comment by sberyozkin** [comment]
@aloubyansky In the reported issue simply combining both dependencies was causing the issue, this is my understanding of it.

**Comment by sberyozkin** [comment]
@aloubyansky I can add a tika-dependency to `integration-tests/narayana-jta` as well, at least I can try now

**Comment by sberyozkin** [comment]
@aloubyansky hey, I've confirmed that adding `quarkus-tika` to `integration-tests/narayana-jta` is also good in the native mode, but not sure it should go in this PR as adding tika can increase the build time significantly, I've no problems adding it if you prefer :-), also CC @gsmet

**Comment by aloubyansky** [comment]
While I do understand the purpose of this change is to test compatibility of transitive dependencies and classloading, tbh, adding a dependency that has nothing to do with the actual functionality being tested looks somewhat random to me. At least it may look as such for a person reviewing this in the future. It'd be good to know what change fixed it in the first place and whether that change was covered with a test, in which case we might not need to do anything more about it here.

**Comment by gsmet** [comment]
Yeah, I think we need to live without a test on this one. Otherwise we will end up with all the dependencies in each test module.

**Comment by sberyozkin** [comment]
@aloubyansky @gsmet OK, so will I close this PR ? The related issue was caused by simply combining both deps, and it was traced down to the `xml-apis` Tika dependency. Somehow it was resolved (perhaps via the earlier Tika xerces exclusion or some other dependency update elsewhere). I'm fine with closing it

**Comment by sberyozkin** [comment]
@aloubyansky @gsmet specifically, Tika `xml-apis` dependency uses Woodstock STAX parser by default which is a problem for `narayana-jta`, and it was causing a build step failure.

**Comment by sberyozkin** [comment]
May be it is a positive side-effect of updating to Tika 1.24.1, I don't really know.

**Comment by aloubyansky** [comment]
I'd close it.

**Comment by Sanne** [comment]
on top of what others said, I also believe you shouldn't use the `quarkus-narayana-jta-deployment` dependency but the runtime one. Also, you might need to actually have some code which does trigger the Transaction Manager to be used.

In terms of how to test combinations of extensions, that's what we usually do in the `integrationtests/main` : add Tika there, and introduce some endpoint which verifies Tika is working fine - a smoke test would be enough to trigger problems of co-existence with other extensions.

**Comment by sberyozkin** [comment]
Hi @Sanne, it was the `narayana-jta` extension which was affected but I added a tika dependency to `integration-tests/narayana-jta` and it passed as well.

**Comment by sberyozkin** [comment]
@aloubyansky but then we won't detect if this issue comes back again and the only thing we know is that it has been after each of us has confirmed it locally.

I've seen a number of PRs before where some dependencies were known to cause some side-effects for some other extensions and the fixes were 'verified' by simply adding those dependencies, for example, [this one](https://github.com/quarkusio/quarkus/commit/c5f4c49bbd5d1b0f7ea8fbb13f6f58cd52aa9438#diff-b5dabbff8c28d764fa7098697d14bd6f4aaa09e955f1e6e83360311e02905c21).

I'm not saying it is necessarily the best pattern, but in this particular case it is very clear from the description that an empty generated application fails to build by simply having the 2 dependencies combined: #7359

**Comment by aloubyansky** [comment]
That is pretty much why there is `integration-tests/main`. Could you check if adding tika to it will fail the build for 1.9.0.Final? If it does, that's the place. Otherwise, following this logic we may be adding "random" extension dependencies to various tests which will certainly create a mess and confusion.

**Comment by Sanne** [comment]
> Hi @Sanne, it was the `narayana-jta` extension which was affected but I added a tika dependency to `integration-tests/narayana-jta` (locally only) and it passed as well.

Did you also add some code which uses it? You need to make sure it's "live", as the native-image compiler is very clever about ignoring & removing useless code.

**Comment by sberyozkin** [comment]
Hi @Sanne 
> Did you also add some code which uses it?
I honestly don't know anything about `narayana-jta`, Tika is not affected and the narayana integration test is doing something :-) but as I said,  #7359 is a failure where only `narayana-jta` and `tika` extensions are combined, the failure occurs at the build time of the empty generated application.
I'll give a try a bit later on and update `integration/main` and see how it goes

Thanks all :-)

**Comment by sberyozkin** [comment]
Hi @aloubyansky @Sanne I've confirmed that integration-tests/main fails immediately by just adding a tika dependency to its pom in 1.9.0.Final, hence updated this PR to include the tika dependency in `integration-tests/main`

**Review by aloubyansky — APPROVED** [review]
Great, thanks @sberyozkin

**Comment by sberyozkin** [comment]
@aloubyansky and @Sanne Thanks, I did not even know that `integration-tests/main` existed :-).
I'll rebase this PR and if it goes green I'll merge, unless Guillaume @gsmet can become concerned about the native image build time increase with the tika dependency, let me know please...

**Pull request merged**
