### PR TITLE
Improved the parsing of the host and port in vertx

### LINKED ISSUE #12939: Wrong host forwarded after enabling  proxy address forwarding
**Describe the bug**
quarkus.http.proxy.proxy-address-forwarding=true

When an ip like 2001:db8:85a3:8d3:1319:8a2e:370:ac is used, the parsing in vertx.http  ForwardedParser breaks as it considers ac to be the port

**Expected behavior**
The obtained remote host address should be2001:db8:85a3:8d3:1319:8a2e:370:ac

**Actual behavior**
We get something like  2001:db8:85a3:8d3:1319:8a2e:370:37678

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.proxy.proxy-address-forwarding=true

```

### PR DESCRIPTION
**Pull request by bobbyphilip**
Fixes https://github.com/quarkusio/quarkus/issues/12939

Added new testcases.  (The pull request fixes ForwardedForHeaderTest#testIPV6HexEnding)

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
LGTM. However, this may be considered as a breaking change.

**Comment by gsmet** [comment]
@cescoffier how is it a breaking change?

**Comment by cescoffier** [comment]
Does it still handle the previous properties?

**Comment by bobbyphilip** [comment]
I would think it still handles the current properties. I have only tried to consolidate the parsing to be more consistent

**Review by stuartwdouglas — APPROVED** [review]

**Comment by cescoffier** [comment]
Oh, my bad! I was thinking some properties were removed, it's just the formatting of the code that made them on 1 line instead of 3. So, yes, not a breaking change.

**Comment by gsmet** [comment]
@bobbyphilip thanks!

**Pull request merged**
