### PR TITLE
Don't always trust Maven's '-f' arg value when resolving the current project pom.xml

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Tested against Quarkus platform and it works great

**Comment by famod** [comment]
Is this fixing strange Dev-Mode errors when using `-f ./my-module` instead of `-f my-module`?
I just had this yesterday and it took me a while to figure out what is going on...

**Comment by gsmet** [comment]
@aloubyansky there is a NPE in some of the tests:
```
io.quarkus.deployment.runnerjar.DependencyVersionOverridesManagedVersionTest
[ERROR] test  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
	at java.nio.file.Files.provider(Files.java:97)
	at java.nio.file.Files.exists(Files.java:2385)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getCurrentProjectPomOrNull(BootstrapMavenContext.java:626)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getActiveSettingsProfiles(BootstrapMavenContext.java:462)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.resolveRemoteRepos(BootstrapMavenContext.java:391)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRemoteRepositories(BootstrapMavenContext.java:202)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:118)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:53)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver$Builder.build(MavenArtifactResolver.java:89)
	at io.quarkus.bootstrap.resolver.ResolverSetupCleanup.initResolver(ResolverSetupCleanup.java:65)
	at io.quarkus.bootstrap.resolver.ResolverSetupCleanup.setup(ResolverSetupCleanup.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by aloubyansky** [comment]
@famod will you be able to test whether it fixes your use-case? We may want to release 1.4.1.Final tomorrow including this fix.

**Comment by famod** [comment]
Is this PR actually try to fix a regression in 1.4.0.Final?

I am asking because with 1.3.1.Final everything is ok when running `mvn quarkus:dev -f my-module`.
When I run `mvn quarkus:dev -f ./my-module` I get an `AmbiguousResolutionException` listing a class bean _twice_ that exists in the very same module and is injected into a REST controller that also exists in the same module.
No difference with 1.3.2.Final.

But with 1.4.0.Final I _also_ get this `AmbiguousResolutionException` when calling `mvn quarkus:dev -f my-module`, which works in 1.3.x.
The bean class is even listed _three_ times when calling `mvn quarkus:dev -f ./my-module`.

And now comes the sad part: This PR does not seem to fix it. :-/

PS: Some gradlew download goes wrong in `quarkus-platform-descriptor-json` when building behind a proxy, although I have set all env vars etc.
For my test of this PR I removed the respective plugin from the pom.

**Comment by aloubyansky** [comment]
@famod is your app available somewhere on github to use as a reproducer?

**Comment by aloubyansky** [comment]
I think I know why @famod Will try to fix it today. Thanks for reporting.

**Comment by aloubyansky** [comment]
@famod just to make sure, it'll still be good if you could share a reproducer.

**Comment by aloubyansky** [comment]
@famod I pushed another commit here. Could you please give it a try?

**Comment by famod** [comment]
> Could you please give it a try?

Will do, give me an hour.

> it'll still be good if you could share a reproducer.

I'll try, but this will take me longer since I am not allowed to share the original project.

**Comment by aloubyansky** [comment]
Thanks!

**Comment by famod** [comment]
The new commit does not change anything for my case. :-/

I'll take a stab at a reproducer.

**Comment by aloubyansky** [comment]
Does it change anything if you use an absolute path with -f?

**Comment by famod** [comment]
_Update:_ I am still working on the reproducer but it seems this problem has to do with Maven CI friendly versioning...

**Comment by aloubyansky** [comment]
@famod please open a new issue once you are ready. Thanks a lot!

**Pull request merged**
