### PR TITLE
Check naming strategy in Spring Boot properties

### LINKED ISSUE #12483: Spring @ConfigProperties bindings are not relaxed
**Describe the bug**
When defining properties with kebab case and defining pojos in camel case, the properties are not binded. The preferred behavior would be like described here: [Relaxed Binding](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-relaxed-binding) 

**Expected behavior**
I defined a property named:
`prop.name-with-dash`
and a class:
```java
@Data
@ConfigurationProperties(prefix = "prop")
public class MyProps {
   private String nameWithDash;
}
```
The property gets loaded correctly.

**Actual behavior**
The application fails with:
`javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: prop.nameWithDash`

**To Reproduce**
The issue is pretty straightforward that's why I am not attaching a project, if really needed let me know and I will add one.

**Configuration**
```properties
# Add your application.properties here, if applicable.
prop.name-with-dash=value
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux host 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.8" 2020-07-14
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.8.1.final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)

### PR DESCRIPTION
**Pull request by gytis**
Fixes https://github.com/quarkusio/quarkus/issues/12483

### CODE REVIEW

**Comment by geoand** [comment]
@gytis CI seems to not like it :)

**Comment by geoand** [comment]
Also, this is breaking change so we will need to have something in the wiki

**Comment by gytis** [comment]
@geoand when and where do you want me to write an entry about the breaking change?

**Comment by geoand** [comment]
Just a note here and I'll copy it into the wiki.

**Comment by gytis** [comment]
This change replaces a hardcoded `verbatim` naming strategy of Spring Boot properties extension with the one defined in `quarkus.arc.config-properties-default-naming-strategy` property (kebab by default).

To keep your application operating as before, perform one of the following changes:

- Set `quarkus.arc.config-properties-default-naming-strategy=verbatim` in the `application.(yml|properties)`
- Replace the properties from verbatim style to kebab (default) or the one defined in `quarkus.arc.config-properties-default-naming-strategy` property.

**Comment by geoand** [comment]
The CI failure is completely unrelated (` quarkus-smallrye-graphql-deployment`)

**Review by geoand — APPROVED** [review]

**Pull request merged**
