### PR TITLE
Add .dockerignore creation to generate

### PR DESCRIPTION
**Pull request by anthonydahanne**
replaces https://github.com/quarkusio/quarkus-quickstarts/pull/91

### CODE REVIEW

**Comment by anthonydahanne** [comment]
I have tested it locally running the basic-rest test and checking it was properly generated.
If you want an automated test, let me know

**Review by stuartwdouglas — APPROVED** [review]

**Comment by cescoffier** [comment]
@geoand this may need to be revisited when we apply the 2 docker fles.

**Comment by geoand** [comment]
Thanks for the heads up @cescoffier! I will go ahead and update PR #1312

**Comment by geoand** [comment]
@cescoffier PR #1312 was updated to incorporate the latest changes in .dockerignore

**Pull request merged**
