### PR TITLE
3.2.8 backports 1

### PR DESCRIPTION
**Pull request by aloubyansky**
FYI @rsvoboda @gsmet @gastaldi this is the initial list of simple looking changes I selected so far. Please let me know if something raises a concern and then we'll do another round. Thanks!

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by rsvoboda** [comment]
The set looks reasonable to me, just a few comments which do not block merging.

https://github.com/quarkusio/quarkus/pull/36697/commits/68fb1da5836f388d2ab73d782ab1cf775abd4a90 ... We could have CORS guide tip about method and origin debug logging. WDYT @sberyozkin ?

https://github.com/quarkusio/quarkus/pull/36697/commits/c2b33a4c7b7ead473e14ccf1c86a00615b6195db ... Test could be part of that PR, I will put it on the list for test development on QE side.

Areas for further analysis and possible test development:
 - https://github.com/quarkusio/quarkus/issues/35706
 - https://github.com/quarkusio/quarkus/issues/35730

**Comment by rsvoboda** [comment]
@aloubyansky @gastaldi CI failures do not look great, JDK 11 and JDK 17 fails in both Linux and Windows variants, Windows native fails on 404 with graalvm/setup-graalvm@v1 ...

**Comment by gastaldi** [comment]
@rsvoboda yeah, that's really odd, since I don't see any meaningful changes in the PR that would cause that. 

@aloubyansky does the build pass when you run it locally?

**Comment by gastaldi** [comment]
@rsvoboda yeah, that's really odd, since I don't see any meaningful change in the PR that would cause that. 

@aloubyansky does the build pass when you run it locally?

**Comment by gastaldi** [comment]
@rsvoboda yeah, that's really odd, since I don't see any meaningful change in the PR that would cause that. 

@aloubyansky does the build pass when you run it locally?

**Comment by gastaldi** [comment]
@rsvoboda yeah, that's really odd, since I don't see any meaningful changes in the PR that would cause that. 

@aloubyansky does the build pass when you run it locally?

**Comment by gastaldi** [comment]
@rsvoboda yeah, that's really odd, since I don't see any meaningful changes in the PR that would cause that. 

@aloubyansky does the build pass when you run it locally?

**Comment by rsvoboda** [comment]
`CompatibilityTest.offsetTime` tests differs by 1 hour. As it has issues with time shift from summer time to winter time.
The same tests fails on Quarkus main too.

**Comment by rsvoboda** [comment]
JDK 17 and JDK 11 didn't finish on time (6 hours)

Last one for JDK 11: 2023-10-30T21:51:02.3030129Z [INFO] Building Quarkus - Integration Tests - Scala 3.2.999-SNAPSHOT [989/1088]
Last one for JDK 17: 2023-10-30T21:53:55.4269482Z [INFO] Building Quarkus - Integration Tests - Management Interface with authentication 3.2.999-SNAPSHOT [1088/1089]

Checked the logs and failed ones are `CompatibilityTest.offsetTime` mentioned for JDK 19 above.
Screenshot 2023-10-31 at 9 21 11

**Pull request merged**
