### PR TITLE
Fix build-doc job

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
this is an attempt to fix this error: https://github.com/quarkusio/quarkus/pull/13308/checks?check_run_id=1411376813

I know nothing about github actions but [this](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) seems to say that should work :)

**Comment by gsmet** [comment]
I already created https://github.com/quarkusio/quarkus/pull/13333 yesterday.

It should fix the issue.

**Comment by michalszynkiewicz** [comment]
cool, should I rebase https://github.com/quarkusio/quarkus/pull/13308 ?
All other jobs succeeded, I have no problem waiting for a rebuild, just don't want to cause too much load

**Comment by gsmet** [comment]
@michalszynkiewicz yes, please. My doc PR passed so the problem should be fixed.

**Pull request closed without merging**
