### PR TITLE
Fix broken primitive default values in @ConfigProperties

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@gytis this will likely cause a merge conflict with your PR.

**Comment by geoand** [comment]
PR rebased onto the latest master to pick up the changes from Panache REST

**Review by mkouba — APPROVED** [review]
LGTM.

**Comment by geoand** [comment]
Waiting for CI to complete on my fork before taking out of draft

**Comment by gsmet** [comment]
Rebased.

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
