### PR TITLE
Drop Okhttp/Okio from BOM

### PR DESCRIPTION
**Pull request by gsmet**
This has been a long standing issue as we were forcing on people a very old version of Okhttp due to recent versions being dependent on Kotlin.

We have been making progress for a while on getting rid of Okhttp from our runtime dependencies and this make sure that only some test framework dependencies rely on it.

It also makes sure that the dependency is not in the BOM.

Now, I'm wondering if the `quarkus-test-kubernetes-client` and `quarkus-test-openshift-client` artifacts are productized and if this change could cause issues (from what I can see the dependencies there is even older than the one we had in the BOM so I'm not sure this will help with CVEs...).

From what I can see in the platform, the consequences are:
- the Okhttp dependencies are gone from the Platform BOM
- Okio is downgraded from `1.17.6` to `1.17.5`

/cc @aloubyansky @maxandersen @tqvarnst 

Also /cc @karesti as I'm dropping `quarkus-test-infinispan-client` (it was unused and problematic and I don't think it has value now that we have proper Dev Services support for Infinispan)

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]
When it comes to extension dependencies in Quarkus itself, for 3.6.1 release, okhttp appears only as a transitive dependency of one extension
```
== IO.QUARKUS.PLATFORM:QUARKUS-BOM:3.6.1

= BOM entries

com.squareup.okhttp3:okhttp:3.14.9

= Extension dependencies

io.quarkus:quarkus-infinispan-client-deployment:3.6.1
└─ org.infinispan:infinispan-server-testdriver-core:14.0.21.Final
   └─ org.infinispan:infinispan-client-rest:14.0.21.Final
      └─ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]
```
There is a bunch of Camel extensions that have it too.

**Review by geoand — APPROVED** [review]
🎉

**Comment by geoand** [comment]
Added the `noteworthy-feature` label because of how highly requested this was

**Comment by gsmet** [comment]
@aloubyansky not sure Camel is actually using Okhttp (Okio, yes but  I don't see Okhttp being added in the Camel Quarkus BOM).

This is the diff (and I haven't added exclusions for Okhttp in the BOM generator config):

```diff
diff --git a/generated-platform-project/quarkus-camel/bom/pom.xml b/generated-platform-project/quarkus-camel/bom/pom.xml
index 7de84878b..cac85dcdb 100644
--- a/generated-platform-project/quarkus-camel/bom/pom.xml
+++ b/generated-platform-project/quarkus-camel/bom/pom.xml
@@ -497,7 +497,7 @@
       <dependency>
         <groupId>com.squareup.okio</groupId>
         <artifactId>okio</artifactId>
-        <version>1.17.6</version>
+        <version>1.17.5</version>
       </dependency>
       <dependency>
         <groupId>com.squareup.retrofit2</groupId>
diff --git a/generated-platform-project/quarkus-universe/bom/pom.xml b/generated-platform-project/quarkus-universe/bom/pom.xml
index 50c7688e2..3220189ec 100644
--- a/generated-platform-project/quarkus-universe/bom/pom.xml
+++ b/generated-platform-project/quarkus-universe/bom/pom.xml
@@ -5056,20 +5056,10 @@
         <artifactId>jprotoc</artifactId>
         <version>1.2.1</version>
       </dependency>
-      <dependency>
-        <groupId>com.squareup.okhttp3</groupId>
-        <artifactId>logging-interceptor</artifactId>
-        <version>3.14.9</version>
-      </dependency>
-      <dependency>
-        <groupId>com.squareup.okhttp3</groupId>
-        <artifactId>okhttp</artifactId>
-        <version>3.14.9</version>
-      </dependency>
       <dependency>
         <groupId>com.squareup.okio</groupId>
         <artifactId>okio</artifactId>
-        <version>1.17.6</version>
+        <version>1.17.5</version>
       </dependency>
       <dependency>
         <groupId>com.squareup.retrofit2</groupId>
@@ -12056,11 +12046,6 @@
         <artifactId>quarkus-test-hibernate-reactive-panache</artifactId>
         <version>999-SNAPSHOT</version>
       </dependency>
-      <dependency>
-        <groupId>io.quarkus</groupId>
-        <artifactId>quarkus-test-infinispan-client</artifactId>
-        <version>999-SNAPSHOT</version>
-      </dependency>
       <dependency>
         <groupId>io.quarkus</groupId>
         <artifactId>quarkus-test-kafka-companion</artifactId>
diff --git a/generated-platform-project/quarkus/bom/pom.xml b/generated-platform-project/quarkus/bom/pom.xml
index c7f745e3d..5168bd014 100644
--- a/generated-platform-project/quarkus/bom/pom.xml
+++ b/generated-platform-project/quarkus/bom/pom.xml
@@ -869,21 +869,6 @@
         <artifactId>jprotoc</artifactId>
         <version>1.2.1</version>
       </dependency>
-      <dependency>
-        <groupId>com.squareup.okhttp3</groupId>
-        <artifactId>logging-interceptor</artifactId>
-        <version>3.14.9</version>
-      </dependency>
-      <dependency>
-        <groupId>com.squareup.okhttp3</groupId>
-        <artifactId>okhttp</artifactId>
-        <version>3.14.9</version>
-      </dependency>
-      <dependency>
-        <groupId>com.squareup.okio</groupId>
-        <artifactId>okio</artifactId>
-        <version>1.17.6</version>
-      </dependency>
       <dependency>
         <groupId>com.sun.mail</groupId>
         <artifactId>jakarta.mail</artifactId>
@@ -7041,11 +7026,6 @@
         <artifactId>quarkus-test-hibernate-reactive-panache</artifactId>
         <version>999-SNAPSHOT</version>
       </dependency>
-      <dependency>
-        <groupId>io.quarkus</groupId>
-        <artifactId>quarkus-test-infinispan-client</artifactId>
-        <version>999-SNAPSHOT</version>
-      </dependency>
       <dependency>
         <groupId>io.quarkus</groupId>
         <artifactId>quarkus-test-kafka-companion</artifactId>
```

**Comment by aloubyansky** [comment]
Camel Quarkus BOM doesn't have to duplicate what's in the `quarkus-bom`, here is the report:
```
== IO.QUARKUS.PLATFORM:QUARKUS-CAMEL-BOM:3.6.1

= Extension dependencies

org.apache.camel.quarkus:camel-quarkus-box-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-box:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-consul:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-consul-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-geocoder:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-geocoder-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-huaweicloud-smn:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-huaweicloud-smn-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-influxdb:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-influxdb-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-hdfs:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-hdfs-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-jsonapi-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-jsonapi:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-minio:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-minio-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-nitrite:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-nitrite-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-openstack:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-openstack-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-pubnub-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-pubnub:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-slack:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-slack-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-support-consul-client:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-support-consul-client-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-support-retrofit:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-support-retrofit-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-web3j:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]

org.apache.camel.quarkus:camel-quarkus-web3j-deployment:3.6.0
↳ com.squareup.okhttp3:okhttp:3.14.9 [managed by quarkus-bom]
```

**Comment by gsmet** [comment]
> Camel Quarkus BOM doesn't have to duplicate what's in the quarkus-bom

Agreed... but they are removed from the BOM, thus my surprise.

**Comment by karesti** [comment]
@gsmet yes, thanks no problem for us

**Pull request merged**
