### PR TITLE
Update SR Config to 2.0.2

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks! But I don't know what @radcortez thinks but I'm not sure this helps as the MP 4 effort is coordinated and things will be updated (together with the necessary changes in Quarkus).

@radcortez WDYT?

**Comment by radcortez** [comment]
Yes, this cannot be updated on its own. The MP Config API adds breaking changes, that will cause failures to all dependent projects, so we need to update all of these as well.

This work is happening in the microprofile-4 branch: https://github.com/quarkusio/quarkus/tree/microprofile-4

@tobiasstadler are  you looking for any particular feature that is present in SR Config 2.x, but not currently available in Quarkus? I'm planning to provide a new SR Config 1.x version with some back ports.

**Comment by tobiasstadler** [comment]
@radcortez the pr targets the microprofile branch 😉

**Comment by radcortez** [comment]
> @radcortez the pr targets the microprofile branch 😉

Ops. Sorry, I thought it was for master. I must be sleeping. Then it should be fine.

**Pull request closed without merging**
