### PR TITLE
Port NativeConfig to @ConfigMapping

### PR DESCRIPTION
**Pull request by geoand**
Opening as a draft for now as this is based on #32276

### CODE REVIEW

**Comment by yrodiere** [comment]
@geoand this will very likely conflict with #32236

**Comment by geoand** [comment]
This can wait, no rush

**Comment by geoand** [comment]
PR rebased onto main

**Comment by geoand** [comment]
The maven failures maybe related, I'll have a look tomorrow

**Review by radcortez — APPROVED** [review]

**Pull request merged**
