### PR TITLE
Add caffeine integration tests

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
If you want this to run in native mode on CI it needs to be added to ci-templates/stages.yaml

**Comment by cescoffier** [comment]
As mentioned by @stuartwdouglas you need to add it to the stage list and increase the timeout accordingly. I let you guess the additional time required.

**Comment by lburgazzoli** [comment]
which category fits better ? I would say `infinispan` as `caffeine` is also used by those extensions

**Comment by stuartwdouglas** [comment]
sounds good to me

**Comment by lburgazzoli** [comment]
done, I haven't increased the time-out as now it fails pretty fast :)

**Comment by lburgazzoli** [comment]
I think this can safely be closed as superseded by the cache extension tests

**Pull request closed without merging**
