### PR TITLE
Move dokka execution to a profile

### PR DESCRIPTION
**Pull request by evanchooly**
Move the dokka executions to a profile to isolate the generation to the release execution.  This also converts what little java exists in those repositories to kotlin because apparently dokka chokes on mixed-source modules.

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]
Could you revisit this PR with the addition of https://github.com/quarkusio/quarkus/pull/17009 ?

Also I added a question.

**Comment by gsmet** [comment]
@evanchooly I think we should limit this PR to its original purpose. The other changes look unrelated?

**Comment by evanchooly** [comment]
Well, it gets tricky here.  Dokka apparently doesn't work well with mixed source trees.  So I thought "ill just move it all to kotlin!" Which lead to a while.host of interesting issues like missing tests compared to the Java side, etc.  I van move off resolving this diffs to a different PR but there are still failures in tests to resolve.

It's definitely snowballing so I might just rebranch and apply lessons learned and side step these other elements as much as I can.  But it feels a bit like pulling on that one loose thread and watching the whole sweater unravel.

**Comment by gsmet** [comment]
Well. It won't work any worse than it used to work or will it?

So I would rather:
- update Dokka
- move things into the `release` profile
as a first step as it fixes some problems we have.

And then you can continue on figuring out how things can be fixed?

**Comment by evanchooly** [comment]
I cleaned up my overexuberance.  :)  There is still the one test failing on multiple PUs and I don't know why.  the set up looks the same as the java side.  but i'm going to go through all the dokka bits and circle back to this one.

**Comment by evanchooly** [comment]
OK.  so that last failure is modules related.  I think we can ignore that one for now as there is already another issue filed to make jdk16 work.  Agreed?

**Comment by evanchooly** [comment]
*bump*

**Comment by evanchooly** [comment]
are we trying to deploy java 16 builds anywhere or just build against java 16.  if we're not deploying, we could simply disable the dokka generation altogether on java 16 because we don't need to worry about sonatype validation rules.  would that work?

**Comment by gsmet** [comment]
@famod could you have a look at ^ ?

**Comment by evanchooly** [comment]
Another option i'm exploring is just bumping to kotlin 1.5.0 as part of this.  I know they're separate issues and I was trying to treat them as such but we may not have a lot of choice on that one.

**Comment by evanchooly** [comment]
on second thought, i'll just do the 1.5 bump then rebase this dokka work on that.

**Comment by famod** [comment]
If the dokka issue is one more item on the "upgrade to Kotlin 1.5 will fix it list" than I'm all for doing it that way.

Having said that...
> are we trying to deploy java 16 builds anywhere or just build against java 16. if we're not deploying, we could simply disable the dokka generation altogether on java 16 because we don't need to worry about sonatype validation rules. would that work?

Unless @gsmet has a big secret master plan to jump on Java 17 once it hits GA (😉), I suppose Quarkus will stay on Java 11 for a looong time. So AFAICS dokka can be safely disabled on Java 16+.
But if dokka is still around by the time the switch to 17 comes, it better got fixed (in case Kotlin 1.5 didn't fix it already).

**Comment by gsmet** [comment]
@evanchooly where are we on this now?

**Comment by evanchooly** [comment]
OK.  we absolutely have to remove java 16 passing as a gatekeeping feature here.  Java 16 requires moving to kotlin 1.5.0 full stop.  However, with 1.5.0 there are byte code changes that torpedo panache processing and so that's a larger change.  IMO, the standard CI should not require Java 16 passage until Java 16 is a supported platform.  I can tackle the changes in panache needed to make it all work but that's larger change and longer wait than necessary for this docs change.  Can we move that Java 16 run to a separate job so we're not tied down by it for the 'main' CI runs?

**Comment by famod** [comment]
Self-quote:
> So AFAICS dokka can be safely disabled on Java 16+.

So why do we need to kick out the entire JDK 16 build then? Have you found more issues that you cannot exclude for JDK 16?
Just trying to understand...

**Comment by evanchooly** [comment]
the bytecode generation changed with 1.5.0 so the panache processing needs an update.

**Comment by famod** [comment]
Bytecode only changed with Kotlin 1.5 on Java 16 or also on Java 11?

**Comment by evanchooly** [comment]
It seems to affect only Java 16.  Tests pass on 11 but not 16.  Either way, the changes can be separated in spite of what I was thinking earlier and so should be.  I'm still working the other issue but it shouldn't block the dokka change or the next alpha release.

**Comment by evanchooly** [comment]
where do we stand with this?

**Comment by gsmet** [comment]
I iterated on a branch. Didn't have time to finish yet but should be ready for the CR1.

**Comment by evanchooly** [comment]
but not *this* branch?  so what happens with this PR/branch?  are we done with it?  is your further work available somewhere?  this branch was going to be the basis for trying to get java 16 working.

**Comment by gsmet** [comment]
I will push to this branch when it's ready (today is a holiday in France). I just fixed the conflicts, fixed a few issues and added some Maven opts.

**Comment by gsmet** [comment]
@evanchooly I just pushed my changes to your branch. Even if not ideal, I think the `--add-opens` are specific enough that they won't hide too many other issues.

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
@gsmet It seems the JDK EA jon needs those new `--add-opens` as well:
```
2021-05-25T03:20:29.6025503Z [ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.32:kapt (kapt) on project quarkus-hibernate-orm-panache-kotlin: Compilation failure
2021-05-25T03:20:29.6036133Z [ERROR] java.lang.IllegalAccessError: class org.jetbrains.kotlin.kapt3.base.KaptContext (in unnamed module @0x244d6a9f) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x244d6a9f
```

**Pull request merged**
