### PR TITLE
Moved SmallRyeGraphQLConfigMapping to the runtime dependency

### LINKED ISSUE #20494: Graphql Quarkus properties not working
### Describe the bug

Some Quarkus properties for graphql do not work, their smallrye/graphql version do work.

properties which do not work:
```
quarkus.smallrye-graphql.show-runtime-exception-message=java.lang.RuntimeException
quarkus.smallrye-graphql.error-extension-fields=code,description,queryPath
```
Documentation: https://quarkus.io/version/main/guides/smallrye-graphql#quarkus-smallrye-graphql_quarkus.smallrye-graphql.show-runtime-exception-message

properties which work:

```
mp.graphql.showErrorMessage=org.acme.CustomRuntimeException
smallrye.graphql.errorExtensionFields=code,description,queryPath
```

### Expected behavior

When running the query 

```
query a{
  testCustomRuntimeException
}
```

There should be the message of the exception and the error code.

```
{
  "errors": [
    {
      "message": "Test CustomRuntimeException",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testCustomRuntimeException"
      ],
      "extensions": {
        "code": "CustomRuntimeException"
      }
    }
  ],
  "data": {
    "testCustomRuntimeException": null
  }
}
```

### Actual behavior

There is no error code and only the standard error message.

```
{
  "errors": [
    {
      "message": "System error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testCustomRuntimeException"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "testCustomRuntimeException": null
  }
}
```

### How to Reproduce?

[code-with-quarkus-exceptions.zip](https://github.com/quarkusio/quarkus/files/7265225/code-with-quarkus-exceptions.zip)
Run the query from above and activate/deactivate the properties.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #20494

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
we move it because otherwise the mapping can only be applied in the build time?

**Review by phillip-kruger — APPROVED** [review]
I think we can later separate this into two, because some does work on build time.

**Comment by radcortez** [comment]
I additionally moved `SmallRyeGraphQLConfig` to the runtime dependency and to `BUILD_AND_RUN_TIME_FIXED`. This will be a middle step until we figure out what needs to go to each phase.

This will also allow fixing the issue discovered by https://github.com/quarkusio/quarkus/pull/20590

**Comment by geoand** [comment]
Should this be merged? If so, please do so soon in order to get it into `2.4.0.CR1`.
Furthermore, should it be backported to `2.3`?

**Pull request merged**
