### PR TITLE
Improve documentation of configuration properties with type Map<String, NotAConfigGroup>

### LINKED ISSUE #40332: Improve documentation of configuration properties with type `Map<String, NotAConfigGroup>`
### Description

Configuration properties of type `Map<String, SomeConfigGroup>`, where `SomeConfigGroup` is a type annotated with `@ConfigGroup` are handled nicely, with documentation clearly stating that the map key is included in the configuration property key:

image

The name of the map key in the documentation can even be customized with `@ConfigDocMapKey("someName")`.

On the other hand, configuration properties of type `Map<String, NotAConfigGroup>`, where `NotAConfigGroup` is a type that is **not** annotated with `@ConfigGroup`, are not handled nicely at all:

image

Also, adding `@ConfigDocMapKey("someName")` on such properties has no effect.

We should display Maps the same way in the documentation, regardless of whether the value type is a config group or not.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #40332 

Before the patch:

image

After the patch (without CSS, since I tested locally...):

image

Unfortunately, this PR needs to set the name of the map keys, which will break direct links to the relevant configuration properties in the docs. That's because anchors are generated from the displayed key, including the `"some-name"` parts... which IMO is a dubious choice. We should probably change that to use anchors generated from some display-independent reference to the key. But that will result in breaking even more links, and anyway won't solve our problem here (since existing links will still be using the old anchor that includes the old `"some-name"`), so I won't do it in this PR.

### CODE REVIEW

**Comment by yrodiere** [comment]
Damn, Guillaume went on PTO before he had time to review this. Though he of all people would be interested.

@geoand maybe? :)

**Comment by geoand** [comment]
It LGTM, but I not done any work around this area not have I followed discussions so I am hesitant to approve

**Comment by yrodiere** [comment]
Thanks. Alright, let's wait for @gsmet .
FWIW there's no conversation beside #40332 .

**Comment by yrodiere** [comment]
Bump @gsmet :)

**Review by gsmet — APPROVED** [review]
Looks interesting, let's merge, thanks!

**Pull request merged**
