### PR TITLE
fix how environment variables are created for OpenShift if well-known S2I image is configured

### LINKED ISSUE #8422: environment variables in OpenShift resources are not generated correctly
**Describe the bug**
If I configure a well-known S2I image to be used, some environment variables (`JAVA_APP_JAR`, `JAVA_LIB_DIR`, `JAVA_CLASSPATH` and `JAVA_OPTIONS`) are supposed to be generated into the `target/kubernetes/openshift.yml`. However, that doesn't happen.

This is because some callsites use the `KubernetesEnvBuildItem` constructor incorrectly.

**Expected behavior**
Environment variables created.

**Actual behavior**
Environment variables missing.

**To Reproduce**
1. Add the `quarkus-openshift` extension.
2. Configure the S2I base image (see properties below).
3. Run `mvn clean package`.
4. Observe missing environment variables in `target/kubernetes/openshift.yml`.

**Configuration**
```properties
quarkus.openshift.expose=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7
```

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #8422.

### CODE REVIEW

**Comment by Ladicek** [comment]
Created as a draft, because I need to add a test and it's already too late today :-)

**Comment by gsmet** [comment]
It would be nice if we could have that one ready today.

**Comment by Ladicek** [comment]
I'm working on the test as we speak :-)

**Comment by Ladicek** [comment]
Test added, now waiting for CI to finish in my fork.

**Comment by Ladicek** [comment]
Well, it's got exactly the problem I feared -- on Windows, the S2I stuff generates Windows paths :-/

Sounds like I need to fix that too.

**Comment by Ladicek** [comment]
@iocanel @geoand BTW, what are you doing in Dekorate to not generate Windows paths on Windows? Always use `/`?

**Comment by geoand** [comment]
I'm not aware (haven't done much work on Dekorate), so I'll let @iocanel elaborate.

**Comment by iocanel** [comment]
@Ladicek in most cases, we use `File.separator`.

**Review by iocanel — APPROVED** [review]
Great catch!

**Comment by Ladicek** [comment]
`File.separator` will, on Windows, produce Windows paths. That's bad -- even on Windows, you (most often, I'd say in 99.99999% cases) want the Kubernetes YAML files to still contain Linux paths, as the container is Linux.

We have a couple of tests in Quarkus already that assert Linux paths, e.g. `BasicOpenshiftTest` has

```java
assertThat(h).extracting("spec").extracting("template").extracting("spec").isInstanceOfSatisfying(PodSpec.class,
        podSpec -> {
            assertThat(podSpec.getContainers()).hasOnlyOneElementSatisfying(container -> {
                assertThat(container.getEnv()).extracting("name", "value")
                        .contains(tuple("JAVA_APP_JAR",
                                "/deployments/basic-openshift-runner.jar"));
            });
        });
```

That test passes even on Windows. So there must be something wrong.

**Comment by Ladicek** [comment]
And indeed Dekorate has

```java
.withName(JAVA_APP_JAR)
.withValue("/deployments/" + config.getProject().getBuildInfo().getOutputFile().getFileName().toString())
```

**Comment by iocanel** [comment]
@Ladicek: Hmmm, I misunderstood your question. Yeah, to reference paths inside resources, you better use `/`.

**Comment by Ladicek** [comment]
Fixed now, waiting for CI in my fork.

**Comment by Ladicek** [comment]
CI passed in my fork, ready now! :-)

**Review by geoand — APPROVED** [review]
Thanks @Ladicek!

**Pull request merged**
