### PR TITLE
Bump Keycloak version to 22.0.0

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by sberyozkin** [comment]
Great stuff thanks @pedroigor

**Comment by sberyozkin** [comment]
Checking locally

**Comment by sberyozkin** [comment]
`CodeFlowTest.testAccessAndRefreshTokenInjectionWithoutIndexHtmlAndListenerMultiTab` is failing, I'll have a look

**Review by sberyozkin — APPROVED** [review]
@pedroigor Many thanks for the PR, minor issue in the test related to the multi-tab setup which I fixed, I'll check it outside the test setup - but as far as Quarkus is concerned it can't affect how KC responds in such cases so we can chat about it afterwards and see what/if might need to be tweaked further

**Comment by sberyozkin** [comment]
@pedroigor For Keycloak 20, 21, 22 I get now 401 as well in the browser, with `Cookie not found. Please make sure cookies are enabled in your browser.`, While test gets an expected `You are already logged in`. It feels like it is the browser related configuration which influences it. I'm pretty sure that specifically Keycloak users confirmed multi-tab was working fine for them and I did try it in the quickstart before writing a test - as I needed to know what Keycloak will return in the first tab ot verify it in the test.

But in any case - this is definitely not something Quarkus can influence, it is between the browser and Keycloak, so I'm not worried. If I see users documenting how this should be worked around then I can add some advice to our docs...

Thanks

**Comment by sberyozkin** [comment]
Tests look ok. Keycloak authorization is the only integration point. For dev services changing a KC image name is easy

**Comment by maxandersen** [comment]
So 22.0 is what is supposed tonight be used in 3.2 - but there is an open question about forward and backwards compatibility of the client that the Keycloak team is going to investigate next week.

**Comment by sberyozkin** [comment]
Added a breaking-change label due to #35572 - even though it is not a keycloak-authorization specific breaking change

**Comment by sberyozkin** [comment]
@maxandersen @gsmet See #35572, for it to be backported to 3.2, `keycloak-adapter-core` dependency which is no longer needed after the update to KC 22.0.1, would have to be re-introduced as users may be depending on some code from this dependency

**Pull request merged**
