### PR TITLE
31246 bump agroal to 1.17

### LINKED ISSUE #31246: Agroal does not provide existing connections from the pool when new connections cannot be established and pool<MIN_SIZE
### Describe the bug

- We are running Keycloak using Quarkus on MS Azure with MS Azure SQL as database
- We are regularly experiencing connection problems to the Azure DB where some connections drop and new connections cannot be established but existing connections still work
- With Keycloak based on Wildly/IronJacamar as pooling implementation, there were request processing errors - with Quarkus/Agroal-based Keycloak 20 requests cannot be processed anymore
- note this is a copy of https://issues.redhat.com/browse/AG-201

### Expected behavior

GIVEN there are database connection problems
AND the current number of connections is below MIN_SIZE
AND there are still valid connections in the pool
AND new connections cannot be created
WHEN a connection is requested from the pool
THEN then an existing connection from the pool is returned and the request succeeds

### Actual behavior

GIVEN there are database connection problems
AND the current number of connections is below MIN_SIZE
AND there are still valid connections in the pool
AND new connections cannot be created
WHEN a connection is requested from the pool
THEN no connection can be obtained and the request fails

### How to Reproduce?

We reproduced the behaviour by changing the db password on a running application so the pool cannot create new connections and killing existing db sessions to bring the number of connections below MIN_SIZE.

However, the problem can be seen directly in the code: https://github.com/agroal/agroal/blob/4c4da6419652f772542e648581d0d8939c411b5e/agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java#L270-L323
-  if a new connection cannot be established, a TimeoutException is thrown and the code to take a connection from the pool is never reached
- while it might be a good idea to trigger filling up the pool to MIN_SIZE, the current request should not incur the delay and probably the failure of obtaining a new connection but rather prefer using an existing connection - IMHO filling up should happen only concurrently 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sschu**
Fixes #31246 (backport).

### CODE REVIEW

**Comment by Sanne** [comment]
I guess it's targeting the wrong branch?

**Comment by sschu** [comment]
@Sanne Sorry, my mistake. Thanks for noticing!

**Comment by Sanne** [comment]
@sschu ah now I see what you meant doing - sorry no we should always target `main` for PRs and only after that flag things to be considered for backporting, @gsmet has his own scripts and methods for that.

Although I'm not sure - it could be helpful in this case as there's the Jakarta barrier in between. Let's ask @gsmet 

Either way, please send a PR for `main` first as we'll want to see that tested and integrated first.

**Comment by sschu** [comment]
@Sanne But for master I would update to 2.1? Will the script be able to make it a 1.17 for backport to quarkus 2.13 branch?

**Comment by sschu** [comment]
PR for main: https://github.com/quarkusio/quarkus/pull/31762

**Comment by gsmet** [comment]
I'm closing this one. We will backport the PR from `main` directly. Thanks anyway.

**Comment by gsmet** [comment]
Ah actually, you have a point but we need to create a PR against 2.16 and I will mark it for backport for 2.13. I will take your commit from here and apply it to 2.16.

**Comment by gsmet** [comment]
@sschu see here: https://github.com/quarkusio/quarkus/pull/31763

Sorry it's all internal cooking of our backport process, thanks for raising both PRs!

**Pull request closed without merging**
