### PR TITLE
Fail with 401 if single IdentityProvider produced no SecurityIdentity

### LINKED ISSUE #17591: HTTP request fails with 401 if more than one IdentityProvider produced no SecurityIdentity but is allowed if a single one is used
## Describe the bug
Bill @patriot1burke has spotted that when a matching `HttpAuthenticationMechanism` requests the request credentials be converted to `SecurityIdentity` then if only a single `IdentityProvider` returns `null` then the request is allowed to continue with an anonymous identity, despite the credentials being available - but will fail with `401` if more than one `IdentityProvider` has not provided `SecurityIdentity`

### Expected behavior
It has to be consistent in both cases.

And IMHO it has to be 401 because it should be a responsibility of `HttpAuthenticationMechanism` to decide whether a null `SecurityIdentity` is returned or not: if it does not recognize the credentials - return null, if it does - then it has to be converted.

Allowing the request to proceed where for example the provided Basic Auth credentials, with the proactive autentication enabled, are represented as an anonymous identity and eventually returning `403` at the RBAC level (as opposed to 401 if the name or password are wrong) is not quite correct.

See also #17192

CC @patriot1burke @stuartwdouglas

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #17591

Currently when multiple identity providers are applied on HTTP request and they all return null, an `AuthenticationFailedException` is thrown. When single identity provider is applied on HTTP request, request is allowed to continue with anonymous identity. In practice, it should still respond with 401 as auth/roles allowed policy still requires non-anonymous identity and response correct status, however that depends from which context is `io.quarkus.security.identity.IdentityProviderManager#authenticate` called. We should make behavior uniform. I believe current behavior for single identity provider has been added by accident in https://github.com/quarkusio/quarkus/pull/8903 as previous behavior also thrown exception (see https://github.com/quarkusio/quarkus/pull/8352)

### CODE REVIEW

**Comment by michalvavrik** [comment]
I think `io.quarkus.it.amazon.lambda.AmazonLambdaV1SimpleTestCase` failures are related, I'll investigate tomorrow.

**Comment by sberyozkin** [comment]
@michalvavrik Yes, I recall it was @patriot1burke who pointed to this issue, so I believe the AWS Lambda tests are checking the status codes as per the current expectations only, so should be OK to change I hope

**Comment by michalvavrik** [comment]
> @michalvavrik Yes, I recall it was @patriot1burke who pointed to this issue, so I believe the AWS Lambda tests are checking the status codes as per the current expectations only, so should be OK to change I hope

thanks Sergey (@sberyozkin ), I think I got it right now (at least it seems logical to me, but I think we will need Bill to verify).

In short: 
here https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpAuthenticationMechanism.java#L49 LambdaHttpAuthenticationMechanism tries to identify whether the request is authenticatable, however the condition actually differs to how DefaultLambdaIdentityProvider resolves identity (please have a look here https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/DefaultLambdaIdentityProvider.java#L77). What I did is to make these conditions matching. Before this change, identity provider was called even when request wasn't authenticatable.

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks; Indeed, lets wait for @patriot1burke to review as well

**Comment by michalvavrik** [comment]
FYI: Today I mentioned that if identity provider response with empty optional in form based auth, this leads to NPE, therefore this PR also prevents NPE when single identity provider is used. If more than one provider is used, there is no NPE.

**Comment by sberyozkin** [comment]
Bill, @patriot1burke , let me merge it, I think this is a good fix, we can follow up if necessary with some updates

**Pull request merged**
