### PR TITLE
Take HTTP root path into account when using @TestHTTPResource

### LINKED ISSUE #27416: @TestHTTPResource annotation injects endpoint URL without the quarkus.http.root-path segment
### Describe the bug

When injecting an endpoint URL in test using the `io.quarkus.test.common.http.TestHTTPResource` annotation, the injected path does not contain a segment, specified by the `quarkus.http.root-path` config property.

### Expected behavior

A full enpoint URL with, including the value of `quarkus.http.root-path`, should be injected.

### Actual behavior

The injected URL lacks the `quarkus.http.root-path` segment.

### How to Reproduce?

```
@TestHTTPEndpoint(MyResource.class)
@TestHTTPResource
URL myResourceUrl;
```
The injected URL would lack the path segment set by the `quarkus.http.root-path` property.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.867]

### Output of `java -version`

openjdk version "18.0.2" 2022-07-19

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

It seems that this happens because the [`TestHTTPResourceManager`](https://github.com/quarkusio/quarkus/blob/b0b51fdc80024efea3acf114b13cd7eb688c5247/test-framework/common/src/main/java/io/quarkus/test/common/http/TestHTTPResourceManager.java#L23) class uses the `test.url` config property to determine an endpoint URL, which is, in turn, is provided by the [`TestHTTPConfigSourceProvider`](https://github.com/quarkusio/quarkus/blob/b0b51fdc80024efea3acf114b13cd7eb688c5247/test-framework/common/src/main/java/io/quarkus/test/common/http/TestHTTPConfigSourceProvider.java#L17) using the following expression:
```
"http://${quarkus.http.host:localhost}:${quarkus.http.test-port:8081}${quarkus.servlet.context-path:}"
```
As you can see, instead of the `quarkus.http.root-path`, the `quarkus.servlet.context-path` is used, which is not applicable for a standalone application.

A workaround is to set the `quarkus.servlet.context-path` in like this:
```
quarkus.servlet.context-path=${quarkus.http.root-path}
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #27416

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Nice!

**Comment by gastaldi** [comment]
Worth mentioning this in the migration docs, as it may break users doing https://github.com/quarkusio/quarkus/issues/27416#issuecomment-1222243108

**Comment by geoand** [comment]
Good point

**Comment by geoand** [comment]
@gastaldi you might want to take another quick look since I added 2 more super simple commits

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Looks like this change broke some tests 🤔

**Comment by geoand** [comment]
Test failures were legit but they should be addressed now

**Pull request merged**
