### PR TITLE
put renamed jar extension in a String constant so it could be safely …

### PR DESCRIPTION
**Pull request by mariofusco**
…referred by extensions

As discussed in: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/uberjar.20.2B.20native

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by jaikiran** [comment]
The failure[1] looks unrelated:

```
2020-07-24T09:28:30.1028316Z [ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.15:runforked (start-elasticsearch) on project quarkus-integration-test-hibernate-search-elasticsearch: Error while expanding /home/runner/.m2/repository/com/github/alexcojocaru/elasticsearch-oss/7.7.0/elasticsearch-oss-7.7.0-linux-x86_64.tar.gz: Unexpected end of ZLIB input stream -> [Help 1]
2020-07-24T09:28:30.1029336Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.15:runforked (start-elasticsearch) on project quarkus-integration-test-hibernate-search-elasticsearch: Error while expanding /home/runner/.m2/repository/com/github/alexcojocaru/elasticsearch-oss/7.7.0/elasticsearch-oss-7.7.0-linux-x86_64.tar.gz
2020-07-24T09:28:30.1029543Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2020-07-24T09:28:30.1029688Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2020-07-24T09:28:30.1029832Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2020-07-24T09:28:30.1029991Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2020-07-24T09:28:30.1030156Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2020-07-24T09:28:30.1030318Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2020-07-24T09:28:30.1030472Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2020-07-24T09:28:30.1030609Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2020-07-24T09:28:30.1030741Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2020-07-24T09:28:30.1030871Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2020-07-24T09:28:30.1031002Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
2020-07-24T09:28:30.1031133Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
2020-07-24T09:28:30.1031245Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
2020-07-24T09:28:30.1031375Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2020-07-24T09:28:30.1031631Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2020-07-24T09:28:30.1031791Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2020-07-24T09:28:30.1031932Z     at java.lang.reflect.Method.invoke (Method.java:564)
2020-07-24T09:28:30.1032065Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2020-07-24T09:28:30.1032207Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2020-07-24T09:28:30.1032350Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2020-07-24T09:28:30.1032497Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2020-07-24T09:28:30.1032995Z Caused by: org.apache.maven.plugin.MojoExecutionException: Error while expanding /home/runner/.m2/repository/com/github/alexcojocaru/elasticsearch-oss/7.7.0/elasticsearch-oss-7.7.0-linux-x86_64.tar.gz
2020-07-24T09:28:30.1033166Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.RunForkedMojo.execute (RunForkedMojo.java:52)
2020-07-24T09:28:30.1033321Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2020-07-24T09:28:30.1033465Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
2020-07-24T09:28:30.1033589Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2020-07-24T09:28:30.1033722Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2020-07-24T09:28:30.1033871Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2020-07-24T09:28:30.1038474Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2020-07-24T09:28:30.1049408Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2020-07-24T09:28:30.1058029Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2020-07-24T09:28:30.1064925Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2020-07-24T09:28:30.1070805Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2020-07-24T09:28:30.1075898Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2020-07-24T09:28:30.1082308Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
2020-07-24T09:28:30.1087388Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
2020-07-24T09:28:30.1092511Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
2020-07-24T09:28:30.1098740Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2020-07-24T09:28:30.1105504Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2020-07-24T09:28:30.1114350Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2020-07-24T09:28:30.1121349Z     at java.lang.reflect.Method.invoke (Method.java:564)
2020-07-24T09:28:30.1128846Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2020-07-24T09:28:30.1137664Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2020-07-24T09:28:30.1145026Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2020-07-24T09:28:30.1152208Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2020-07-24T09:28:30.1158090Z Caused by: org.codehaus.plexus.archiver.ArchiverException: Error while expanding /home/runner/.m2/repository/com/github/alexcojocaru/elasticsearch-oss/7.7.0/elasticsearch-oss-7.7.0-linux-x86_64.tar.gz
2020-07-24T09:28:30.1163521Z     at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute (TarUnArchiver.java:124)
2020-07-24T09:28:30.1167297Z     at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute (TarUnArchiver.java:87)
2020-07-24T09:28:30.1171088Z     at org.codehaus.plexus.archiver.AbstractUnArchiver.extract (AbstractUnArchiver.java:133)
2020-07-24T09:28:30.1174965Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ArchiveUtil.extractTarGz (ArchiveUtil.java:43)
2020-07-24T09:28:30.1178928Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ArchiveUtil.autodetectAndExtract (ArchiveUtil.java:27)
2020-07-24T09:28:30.1183425Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.ResolveElasticsearchStep.unpackToElasticsearchDirectory (ResolveElasticsearchStep.java:245)
2020-07-24T09:28:30.1187436Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.ResolveElasticsearchStep.execute (ResolveElasticsearchStep.java:44)
2020-07-24T09:28:30.1191976Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultInstanceStepSequence.lambda$execute$0 (DefaultInstanceStepSequence.java:21)
2020-07-24T09:28:30.1194957Z     at java.lang.Iterable.forEach (Iterable.java:75)
2020-07-24T09:28:30.1198987Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultInstanceStepSequence.execute (DefaultInstanceStepSequence.java:21)
2020-07-24T09:28:30.1202842Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedInstance.configureInstance (ForkedInstance.java:32)
2020-07-24T09:28:30.1208005Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.RunForkedMojo.execute (RunForkedMojo.java:43)
2020-07-24T09:28:30.1211761Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2020-07-24T09:28:30.1221036Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
2020-07-24T09:28:30.1230511Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2020-07-24T09:28:30.1230679Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2020-07-24T09:28:30.1231032Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2020-07-24T09:28:30.1231243Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2020-07-24T09:28:30.1231546Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2020-07-24T09:28:30.1233683Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2020-07-24T09:28:30.1236705Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2020-07-24T09:28:30.1241106Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2020-07-24T09:28:30.1241294Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2020-07-24T09:28:30.1243250Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
2020-07-24T09:28:30.1245954Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
2020-07-24T09:28:30.1248536Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
2020-07-24T09:28:30.1251632Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2020-07-24T09:28:30.1255858Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2020-07-24T09:28:30.1259305Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2020-07-24T09:28:30.1263801Z     at java.lang.reflect.Method.invoke (Method.java:564)
2020-07-24T09:28:30.1268230Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2020-07-24T09:28:30.1271212Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2020-07-24T09:28:30.1276168Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2020-07-24T09:28:30.1279367Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2020-07-24T09:28:30.1282768Z Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
2020-07-24T09:28:30.1286941Z     at java.util.zip.InflaterInputStream.fill (InflaterInputStream.java:244)
2020-07-24T09:28:30.1289949Z     at java.util.zip.InflaterInputStream.read (InflaterInputStream.java:158)
2020-07-24T09:28:30.1292823Z     at java.util.zip.GZIPInputStream.read (GZIPInputStream.java:117)
2020-07-24T09:28:30.1295982Z     at java.io.BufferedInputStream.fill (BufferedInputStream.java:244)
2020-07-24T09:28:30.1298976Z     at java.io.BufferedInputStream.read1 (BufferedInputStream.java:284)
2020-07-24T09:28:30.1301717Z     at java.io.BufferedInputStream.read (BufferedInputStream.java:343)
2020-07-24T09:28:30.1305229Z     at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read (TarArchiveInputStream.java:656)
2020-07-24T09:28:30.1307633Z     at java.io.InputStream.read (InputStream.java:218)
2020-07-24T09:28:30.1310227Z     at org.codehaus.plexus.util.IOUtil.copy (IOUtil.java:189)
2020-07-24T09:28:30.1312577Z     at org.codehaus.plexus.util.IOUtil.copy (IOUtil.java:175)
2020-07-24T09:28:30.1315948Z     at org.codehaus.plexus.archiver.AbstractUnArchiver.extractFile (AbstractUnArchiver.java:340)
2020-07-24T09:28:30.1319169Z     at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute (TarUnArchiver.java:113)
2020-07-24T09:28:30.1322606Z     at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute (TarUnArchiver.java:87)
2020-07-24T09:28:30.1326226Z     at org.codehaus.plexus.archiver.AbstractUnArchiver.extract (AbstractUnArchiver.java:133)
2020-07-24T09:28:30.1329853Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ArchiveUtil.extractTarGz (ArchiveUtil.java:43)
2020-07-24T09:28:30.1333933Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ArchiveUtil.autodetectAndExtract (ArchiveUtil.java:27)
2020-07-24T09:28:30.1338764Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.ResolveElasticsearchStep.unpackToElasticsearchDirectory (ResolveElasticsearchStep.java:245)
2020-07-24T09:28:30.1342647Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.ResolveElasticsearchStep.execute (ResolveElasticsearchStep.java:44)
2020-07-24T09:28:30.1347219Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultInstanceStepSequence.lambda$execute$0 (DefaultInstanceStepSequence.java:21)
2020-07-24T09:28:30.1347521Z     at java.lang.Iterable.forEach (Iterable.java:75)
2020-07-24T09:28:30.1351518Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultInstanceStepSequence.execute (DefaultInstanceStepSequence.java:21)
2020-07-24T09:28:30.1354927Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedInstance.configureInstance (ForkedInstance.java:32)
2020-07-24T09:28:30.1358129Z     at com.github.alexcojocaru.mojo.elasticsearch.v2.RunForkedMojo.execute (RunForkedMojo.java:43)
2020-07-24T09:28:30.1361273Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2020-07-24T09:28:30.1363889Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
2020-07-24T09:28:30.1366874Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2020-07-24T09:28:30.1369469Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2020-07-24T09:28:30.1372538Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2020-07-24T09:28:30.1375896Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2020-07-24T09:28:30.1379299Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2020-07-24T09:28:30.1382447Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2020-07-24T09:28:30.1384870Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2020-07-24T09:28:30.1387296Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2020-07-24T09:28:30.1389931Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2020-07-24T09:28:30.1412251Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
2020-07-24T09:28:30.1419190Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
2020-07-24T09:28:30.1436613Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
2020-07-24T09:28:30.1438089Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2020-07-24T09:28:30.1439187Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2020-07-24T09:28:30.1440265Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2020-07-24T09:28:30.1441338Z     at java.lang.reflect.Method.invoke (Method.java:564)
2020-07-24T09:28:30.1442381Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2020-07-24T09:28:30.1443476Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2020-07-24T09:28:30.1444602Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2020-07-24T09:28:30.1445694Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2020-07-24T09:28:30.1446881Z [ERROR] 
2020-07-24T09:28:30.1448300Z [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2020-07-24T09:28:30.1449559Z [ERROR] 
2020-07-24T09:28:30.1450598Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2020-07-24T09:28:30.1451719Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
2020-07-24T09:28:30.1453212Z [ERROR] 
2020-07-24T09:28:30.1454721Z [ERROR] After correcting the problems, you can resume the build with the command
2020-07-24T09:28:30.1456173Z [ERROR]   mvn <args> -rf :quarkus-integration-test-hibernate-search-elasticsearch
```

[1] https://github.com/quarkusio/quarkus/pull/10952/checks?check_run_id=905929356

**Comment by geoand** [comment]
Yeah, but maybe it's something that @yrodiere has an idea about?

**Comment by yrodiere** [comment]
@geoand Never saw this stack trace, and I use this plugin on a daily basis, including on a Jenkins CI. It looks like the Elasticsearch tar is corrupt. Maybe a cache was reused from a previous build that failed to download Elasticsearch?

**Comment by geoand** [comment]
Thanks @yrodiere for the info. It's probably just a random failure, hopefully we won't be seeing it again :)

**Pull request merged**
