### PR TITLE
SimpleScheduler - fix CronTrigger#evaluate()

### LINKED ISSUE #17724: Scheduler is not triggered or triggered 2 times randomly with native image
## Describe the bug
Randomly, scheduler is not triggered or triggered 2 times with native image
This behavior is not observed in "jvm mode"

### Expected behavior
Scheduler should trigger 1 time and doesn't miss any trigger event with native image

## To Reproduce

https://github.com/jmpdev34/reproducer-scheduler-native

The reproducer should schedule every second based on a cron expression.
When the scheduler method is fired, a log with the datetime is printed
If the scheduler triggers 2 times, a log is printed : 'Already triggered ..."
1. Build a native image of the reproducer project
2. Start runner
3. Wait for a "Already triggered' log and verify if a second hasn't been triggered

Note : if none "Already triggered" log appears, try to shutdown et re-start the runner and/or start another activity on the computer (IT tests on a project for example)

### Configuration
```properties
# Add your application.properties here, if applicable.
reproducer.scheduler.cron=0/1 * * ? * *
```

### Output of `uname -a` or `ver`
Linux 344910zx2006 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

### GraalVM version (if different from Java)
graalvm-ce-java11-20.1.0

### Quarkus version or git rev
1.11.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven version 3.6.3

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #17724

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]
LGTM. CI was not happy with the first run though, I relaunched it.

**Comment by mkouba** [comment]
> LGTM. CI was not happy with the first run though, I relaunched it.

GitHub has problems: https://www.githubstatus.com/ :-(

**Comment by mkouba** [comment]
The change is described in https://github.com/quarkusio/quarkus/issues/17724#issuecomment-856649657

**Comment by gsmet** [comment]
@mkouba VERY bad idea to rename the logger in the same commit. I have conflicts... When you want to backport a fix, please do NOT make cosmetic changes that don't bring anything to the plate.

**Comment by gsmet** [comment]
I fixed the conflicts myself by saying that for next time.

**Comment by mkouba** [comment]
> @mkouba VERY bad idea to rename the logger in the same commit. I have conflicts... When you want to backport a fix, please do NOT make cosmetic changes that don't bring anything to the plate.

@gsmet I'm really sorry about that. I tried to make a diff locally and saw no conflicts. But this change was not only about renaming the logger, I also added/removed some log messages. Was it really the rename itself that caused the conflict?

**Comment by gsmet** [comment]
Yes. Some methods are not in 1.13 and the fact that the logger name had changed made them present in the diff as they are logging something. There's a good chance they would have been ignored otherwise.

It wasn't too hard to fix it but for a more complex patch, that could have been a major pain thus my message.

**Pull request merged**
