### PR TITLE
Improve security-getting-started-tutorial doc

### LINKED ISSUE #37499: Docs: security-getting-started-tutorial guide
### Describe the bug

Found issues in https://quarkus.io/guides/security-getting-started-tutorial

1. In https://quarkus.io/guides/security-getting-started-tutorial#what-you-will-build
There is {ProductName} that should be Quarkus, I suppose

2. In https://quarkus.io/guides/security-getting-started-tutorial#create-the-maven-project
It says “To create a new Maven project with the Jakarta Persistence extension, complete one of the following steps”', but in the first step provided commands will only create a new project with provided groupId and artifactId. 
For example, command creating Maven project with Hibernate ORM must include the next option  
`-Dextensions='security-jpa'`

3. In[ https://quarkus.io/guides/security-getting-started-tutorial#write-the-application](https://quarkus.io/guides/security-getting-started-tutorial#write-the-application)
Before starting writing new classes, we need to add `resteasy-reactive` as project dependency to be able to use JAX-RS features in code. IMHO ideally if we include this dependency during the app creating step.

4. I see the next sentence twice: “Implement the /api/public endpoint to allow all users to access the application”.
In the second case, it refers to admin endpoint creation, so I suggest rewriting this.
“Implement an /api/admin endpoint that can only be accessed by users who have the admin role.”

5. In[ https://quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity](https://quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity)
Please add a note for guide readers: don’t forget to set up the Panache and PostgreSQL JDBC driver, please see https://quarkus.io/guides/hibernate-orm-panache#setting-up-and-configuring-hibernate-orm-with-panache

6. In https://quarkus.io/guides/security-getting-started-tutorial#configure-the-application
In 1. point,  please remove backtick from quarkus.http.auth.basic=true’

7. In https://quarkus.io/guides/security-getting-started-tutorial#test-your-application-by-using-dev-services-for-postgresql
 
 In the code example for `JpaSecurityRealmTest` wrong package name is using, in all    places in this guide I see `org.acme.security.jpa`, here it is `org.acme.elytron.security.jpa`.

 It’s needed to add next dependency to can import `io.restassured.RestAssured` and `org.hamcrest.core` into `JpaSecurityRealmTest`
```
<dependency>
     <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
</dependency> 
```

8. In https://quarkus.io/guides/security-getting-started-tutorial#use-curl-or-a-browser-to-test-your-application
Please add copy button as it is in all other code boxes

9. In https://quarkus.io/guides/security-getting-started-tutorial#compile-and-run-the-application
When running app in Native mode the next target must be used `./target/security-jpa-quickstart-1.0.0-SNAPSHOT-runner`

10. In https://quarkus.io/guides/security-getting-started-tutorial#use-curl-or-a-browser-to-test-your-application
I am suggesting to separate curl commands and its results because basically user want to copy only command, not with result :)

11. In https://quarkus.io/guides/security-getting-started-tutorial#results
	It says “it is not assigned to the "user" role, as shown in the following shell example”. Can we remove the word “shell” from this sentence?

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #37499

CC @gtroitsk

Points 1-3 remain unresolved, so keeping it as Draft for now

### CODE REVIEW

**Comment by sberyozkin** [comment]
@gtroitsk @rsvoboda I believe points 1-3 are now resolved, specifically, as far as the point 1 is concerned I removed a ref to the `ProductName` template var - looks like it was added here to make it available downstream - but no other guides do it

**Comment by gtroitsk** [comment]
@sberyozkin I have only one note. In preview I see that section "Define the user entity" is displayed as title. There may be an extra level 3 section heading (===). It is displayed as `=== Define the user entity`

**Comment by sberyozkin** [comment]
@gtroitsk Thanks for a quality review, I've fixed it by having both `Define User Entity` and `Configure Application` set with a `==` title property, `===` is not quite correct and it is also, as you have spotted, is not rendered correctly, though I'm not sure why, there are some docstyle characters around...
I had to rebase and resolve the conflict - as the Doc team is working on these docs too, please check the preview

CC @rsvoboda

**Comment by gtroitsk** [comment]
@sberyozkin Thank you, preview looks good

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
