### PR TITLE
Add QuarkusPhysicalNamingStrategy.java to support mapUnderscoreToCamelCase

### PR DESCRIPTION
**Pull request by w3n9**
Copied from https://github.com/spring-projects/spring-boot/blob/47516b50c39bd6ea924a1f6720ce6d4a71088651/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/orm/jpa/hibernate/SpringPhysicalNamingStrategy.java

but renamed  and kept the copyright

Relates to: https://github.com/quarkusio/quarkus/issues/18678

### CODE REVIEW

**Comment by FromMeToMyself** [comment]
https://github.com/quarkusio/quarkus/issues/18678

**Comment by maxandersen** [comment]
this does not seem like a Quarkus naming strategy but more one that just adds camel case handling?

@Sanne is this not something that would make more sense to put into hibernate default naming strategy ?
or name it CamelCaseNamingStrategy or similar?

**Comment by maxandersen** [comment]
or if this is truly to mimick/follow spring default naming strategy then call it SpringCompatibleNamingStrategy or similar ?

**Comment by Sanne** [comment]
yea it's just camel-case, so the current name is indeed a bit odd.

I think the name `QuarkusPhysicalNamingStrategy` only if we were to make it the default? But even if that could be nice, it would break backwards compatibility quite significantly for minor reasons, so I don't think we'd be making it default - not right now at least.

Also, thinking out loud.. should it belong in Hibernate ORM instead? That would be more useful for both Quarkus, Spring users, and everyone else since this pattern seems popular. Whad do you think @FromMeToMyself ?

(sorry for not having proposed that earlier, I had not seen the code)

**Comment by FromMeToMyself** [comment]
> yea it's just camel-case, so the current name is indeed a bit odd.
> 
> I think the name `QuarkusPhysicalNamingStrategy` only if we were to make it the default? But even if that could be nice, it would break backwards compatibility quite significantly for minor reasons, so I don't think we'd be making it default - not right now at least.
> 
> Also, thinking out loud.. should it belong in Hibernate ORM instead? That would be more useful for both Quarkus, Spring users, and everyone else since this pattern seems popular. Whad do you think @FromMeToMyself ?
> 
> (sorry for not having proposed that earlier, I had not seen the code)

I agree with you.

**Comment by FromMeToMyself** [comment]
> this does not seem like a Quarkus naming strategy but more one that just adds camel case handling?
> 
> @Sanne is this not something that would make more sense to put into hibernate default naming strategy ?
> or name it CamelCaseNamingStrategy or similar?

Why not UnderscoreNamingStrategy ?

**Comment by Sanne** [comment]
@FromMeToMyself I'll close this in favour of:
 - https://github.com/hibernate/hibernate-orm/pull/4098

**Pull request closed without merging**
