### PR TITLE
ArC intercepted subclasses - fix bridge methods processing

### PR DESCRIPTION
**Pull request by mkouba**
- skip methods overriden by bridge methods
- do not skip a bridge method for which an "impl. method" is not
declared on the class

Co-authored-by: Matej Novotny <manovotn@redhat.com>

### CODE REVIEW

**Comment by mkouba** [comment]
In this PR, we're trying to fix several issues with CDI interceptors and bridge methods. Unfortunately, the fix is not "ultimate".

The problem is that the generic strategy to _skip all bridge methods_ and _methods overriden by bridge methods_ (taken from [Weld](http://weld.cdi-spec.org/)) may not be applied in all cases. The special case (inspired by a [real use case](https://github.com/quarkusio/quarkus/issues/14696)) is tested [here](https://github.com/quarkusio/quarkus/pull/14767/files#diff-62526717a21afc153687990441abcc534dfcc3a2bf712df734292aded443c9aaR65-R66).

`ExampleResource` - the class in test - extends `AbstractResource` which implements `ExampleApi`. The `ExampleResource` does not override the inherited `create(T dto)` but since the `ExampleApi` declares `create(String dto)` a bridge method is generated in the `ExampleResource` class. And this method is used if you [invoke the method via `invokeinterface`](https://github.com/quarkusio/quarkus/pull/14767/files#diff-62526717a21afc153687990441abcc534dfcc3a2bf712df734292aded443c9aaR71). As a result, interceptors are not applied unless we add a generated method to the intercepted subclass for this bridge method. Therefore, we applied an [algorithm to detect similar bridge methods](https://github.com/quarkusio/quarkus/pull/14767/files#diff-f05a30ce973915337c900f71476c739f710d3fcc1ab6d148bbb418755a2bd5a9R450-R488). It's not perfect but best effort and it should work in most cases.

Unfortunately, it seems that compilers are not consistent and the generated bytecode differs in certain scenarios. In particular, the following test fails with Eclipse JDT compiler: https://github.com/quarkusio/quarkus/pull/14767/files#diff-62526717a21afc153687990441abcc534dfcc3a2bf712df734292aded443c9aaR70-R72 because the generated bridge method does not use the `invokespecial` to call the implementation method declared on the superclass but `invokevirtual` which in turn results in "double interception".

We don't know how to solve it better but our knowledge of bridge methods is limited (neither JLS nor JVM spec provide a clear description). So any feedback and tips are welcome! CC @stuartwdouglas @dmlloyd @FroMage @geoand

**Comment by dmlloyd** [comment]
I think the "most correct" check would be to detect methods whose body contains a single invocation which delegates to a more specific method on the same class (possibly through a `checkcast`) using some algorithm to determine specificity.  But, I think your solution is good enough, from a pragmatic perspective.  If it works, it works!

**Comment by stuartwdouglas** [comment]
So as I understand it the issue is that some compilers use invokespecial and some use invokevirtual for their bridge methods? The ones that use invokespecial need to be overriden as the invokespecial would skip the subclass method with the interceptors, while if you apply this same logic to ones that use invokevirtual then double interception applies.

Instead of skipping bridge methods like we currently do would it be possible to always override them but just replace them with an invokevirtual version (assuming we can figure out the correct target for the bridge method)?

**Comment by geoand** [comment]
Question: is EJC the only problematic compiler?

And if so, how widespread is it's use?

**Comment by mkouba** [comment]
> I think the "most correct" check would be to detect methods whose body contains a single invocation which delegates to a more specific method on the same class (possibly through a checkcast) using some algorithm to determine specificity.

@dmlloyd Hm, that would require bytecode inspection/manipulation. So far we only used the Jandex index. The other problem is that there is nowhere specified how a bridge method should look like, i.e. compilers could add stuff that would break our detection.

> Instead of skipping bridge methods like we currently do would it be possible to always override them but just replace them with an invokevirtual version (assuming we can figure out the correct target for the bridge method)?

@stuartwdouglas Hm, that would imply bytecode manipulation for every class that has an associated interceptor. Also I'm not so sure we could easily find the correct target for the bridge method. It's basically the same problem as I described above.

> Question: is EJC the only problematic compiler? And if so, how widespread is it's use?

@geoand I really have no idea! ;-)

Thank you guys for your tips! Based on the feedback I think that the fix is "good enough". It should definitely work better than our current approach. 

@manovotn I think this PR is ready for review.

**Comment by manovotn** [comment]
> If it works, it works!

Love this conclusion! +1

> Question: is EJC the only problematic compiler? And if so, how widespread is it's use?

Personally, never seen it outside of Eclipse IDE but that doesn't say much.

> Instead of skipping bridge methods like we currently do would it be possible to always override them but just replace them with an invokevirtual version (assuming we can figure out the correct target for the bridge method)?

Yeah, we thought about that as well but couldn't come up with reliable way of detection plus to me this seems as way too invasive bytecode manipulation.

> @manovotn I think this PR is ready for review.

I can give you the green stamp but not sure it count for much since we wrote it together :-D

**Review by manovotn — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I am not talking about bytecode manipulation, I am talking about overriding the bridge methods in the subclass, and then creating a new version that uses invokevirtual rather than invokespecial. This will always result in the intercepted method being called once and only once.

**Comment by manovotn** [comment]
> I am not talking about bytecode manipulation, I am talking about overriding the bridge methods in the subclass, and then creating a new version that uses invokevirtual rather than invokespecial. This will always result in the intercepted method being called once and only once.

Oh, now I see what you mean. Thanks for explanation.
That's pretty smart but I would still rather keep what we have as a simpler solution and see if it ever emerges again. If it does, we should probably apply your suggestion.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by famod** [comment]
Although this wasn't broken by 1.11, I wonder whether this is a backport candidate?

**Pull request merged**
