### PR TITLE
Fixing the badly ended conditionals

### PR DESCRIPTION
**Pull request by MichalMaler**
Previously, I created conditionals that were not properly ended.
This fix is maybe a solution for the troubles caused during the downstreaming of this guide.
Ref:
* https://github.com/quarkusio/quarkus/pull/44252
* https://github.com/quarkusio/quarkus/pull/44223

### CODE REVIEW

**Review by jmartisk — APPROVED** [review]

**Review by michalvavrik — APPROVED** [review]

**Review by rsvoboda — APPROVED** [review]
For the future, @MichalMaler is there a way to validate adocs by a tool to prevent issues like this?

**Comment by MichalMaler** [comment]
> For the future, @MichalMaler is there a way to validate adocs by a tool to prevent issues like this?

We don't have such a tool right now, but I agree it would be great to have something that can check if all conditions are properly enclosed.
It was a silly mistake by me, but on the other hand, that's why we have reviews.

**Comment by rsvoboda** [comment]
>  It was a silly mistake by me, but on the other hand, that's why we have reviews.

With a load of pull requests landing to the Quarkus repo, I don't think it's a reasonable expectation. Creator/Owner of the PR is the primary responsible person and that's also why having a tool that would help identify incorrect syntax would help.

**Comment by MichalMaler** [comment]
> > It was a silly mistake by me, but on the other hand, that's why we have reviews.
> 
> With a load of pull requests landing to the Quarkus repo, I don't think it's a reasonable expectation. Creator/Owner of the PR is the primary responsible person and that's also why having a tool that would help identify incorrect syntax would help.

Hey, I don't blame anyone! :) It was all my fault. I will put this on my todo list.
I agree that this should be caught automatically.

**Comment by jmartisk** [comment]
We do have a bazillion documentation-related automated checks in the upstream CI, how come none of them caught this?

**Comment by jmartisk** [comment]
I guess the problem is that an unterminated `ifndef/ifdef` macro is actually legal, and the (asciidoc-maven-plugin) compiler in this case just treats the whole rest of the document (behind this macro) to be part of this macro, and doesn't throw any errors. And only Pantheon seems to handle it by failing (without a reasonable error message). To check for unterminated macros, we would have to write our own custom check, I think.

**Pull request merged**
