### PR TITLE
Look for quarkus.index-dependency.* among the application runtime dependencies

### LINKED ISSUE #9396: Sub-modules in same project not being indexed when using `quarkus.index-dependency.` properties
**Describe the bug**
Projects in a Quarkus mulimodule-setup are not processed when using properties configuration.
```
quarkus.index-dependency.<name>.group-id=
quarkus.index-dependency.<name>.artifact-id=
```
Addind the properties shows this error when running in native mode like
```
Could not resolve artifact org.abelsromero:model:null. Please make sure it is present and contains a META-INF/MANIFEST.MF file. Note that artifacts that are part of the same project may not always be resolvable, in this case you should generate a META-INF/jandex.idx file instead using the Jandex Maven plugin.
```

**Expected behavior**
Modules should be indexed and processed to enable Quarkus features (also CDI, etc.).

**Actual behavior**
As explained  [stackoverflow.com/55513502](https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module) sub-modules can be indexed using three methods:
. Generating jandex index with jandex-maven-plugin -> this works :+1: 
. Adding an empty META-INF/beans.xml -> this works :+1: 
. Indexing with properties -> this does not :-1: 

**To Reproduce**
1. Clone https://github.com/abelsromero/quarkus-multimodule-mongodb
2. Add `quarkus.index-dependency.model.group-id=org.abelsromero` and `quarkus.index-dependency.model.artifact-id=model` to `application.properties.
3. Compile with `mvn clean package -Pnative`

**Configuration**
```properties
quarkus.index-dependency.model.group-id=org.abelsromero
quarkus.index-dependency.model.artifact-id=model
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
_Linux man-pc 5.6.11-1-MANJARO #1 SMP PREEMPT Wed May 6 10:20:32 UTC 2020 x86_64 GNU/Linux_
 - Output of `java -version`: 
_openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)_
 - GraalVM version (if different from Java): 
_ 20.0.0.r11-grl_
 - Quarkus version or git rev: 
_1.4.2.Final_
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
_Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/asalgadr/.sdkman/candidates/maven/current
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /home/asalgadr/.sdkman/candidates/java/20.0.0.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.11-1-manjaro", arch: "amd64", family: "unix"_

**Additional context**
mailing list conversation: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/SN1RdLS2Hu0/y7MUUZfGBAAJ

Looking into the code seems the issue is in https://github.com/quarkusio/quarkus/blob/688ee16b0641ac60239c0c7970ce23b6cbff35ff/core/deployment/src/main/java/io/quarkus/deployment/index/ClassPathArtifactResolver.java#L118-L123
This validated the groupId provided matches the path location of the jar assuming it's located in a local m2 repo, which is not the case for a dependency to a module in the same reactor. To make it work, it should also look for a path like "**/{artifact-id}/target/{jarfile}", which still may cause issues in some odd cases, but covers for 99%. Another options is adding a specific configuration property to tell it's a sub-module, but I woudn't make configuration even more complex. Or even resorting a proper maven resolver, iirc Arquilian had something.

### PR DESCRIPTION
**Pull request by aloubyansky**
Look for quarkus.index-dependency.* among the application runtime dependencies obtained from the AppModel instead of the classloader-based artifact resolver.

I think this is more efficient and also works for modules of a multimodule project that have not been packaged or installed.

Fixes #9396

### CODE REVIEW

**Comment by aloubyansky** [comment]
BTW, I think we should remove `ClassPathArtifactResolver`, I guess it was a workaround at the time but now we have access to the AppModel. This resolver impl is fragile anyway. The only other place I see it being used in is https://github.com/quarkusio/quarkus/blob/master/extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java#L168

**Comment by gsmet** [comment]
Rebased to trigger CI and get the latest CI fixes.

**Comment by stuartwdouglas** [comment]
Failures look related, +1 to removing ClassPathArtifactResolver

**Comment by aloubyansky** [comment]
Yes, I used added module `lib` to a test which is in `.gitignore,` so it wasn't committed.
I've removed ClasspathArtifactResolver and related API. I also noticed there is `io.quarkus.deployment.index.ConstPoolPredicate`, is it used anywhere?

**Comment by aloubyansky** [comment]
@stuartwdouglas this one should be good now. Please check the swagger and graphql processors. Looks like those should also be looking for the artifact among the deployment dependencies, since I found at least the swagger deployment artifact depending on what's being looked up.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
