### PR TITLE
Ability to configure extension Dev mode JVM options

### PR DESCRIPTION
**Pull request by aloubyansky**
This change allows extension authors to configure JVM options in extension metadata that would be added to the command line launching an application in dev mode.

At this point, this is targeting JVM options that start with `--`, such as `--enable-preview`, `--add-opens`, `--add-modules` and boolean or single valued `-XX:` options.

Dev mode JVM options can be configured when building extensions in the following way
```
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-extension-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>extension-descriptor</goal>
                        </goals>
                        <configuration>
                            <deployment>${project.groupId}:${project.artifactId}-deployment:${project.version}</deployment>
                            <devMode>
                                <!-- standard JVM options -->
                                <jvmOptions>
                                    <add-modules>jdk.incubator.vector</add-modules>
                                    <add-opens>java.base/java.util=ALL-UNNAMED</add-opens>
                                    <add-opens>java.base/java.io=ALL-UNNAMED</add-opens>
                                    <add-opens>java.base/java.nio=ALL-UNNAMED</add-opens>
                                    <enable-preview/>
                                </jvmOptions>
                                <!-- -XX: options -->
                                <xxJvmOptions>
                                    <UseThreadPriorities>false</UseThreadPriorities>
                                    <UseLargePages>true</UseLargePages>
                                    <AllocatePrefetchStyle>1</AllocatePrefetchStyle>
                                </xxJvmOptions>
                            </devMode>
...
```

When an `ApplicationModel` is resolved, Dev mode JVM options from all the extensions are merged and when the application is launched in Dev mode, these options are added to the command line.

A user can disable JVM options coming extensions by adding the following `quarkus-maven-plugin` configuration
```
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <configuration>
                    <extensionJvmOptions>
                        <disableAll>true</disableAll>
                    </extensionJvmOptions>
                </configuration>
...
```
or disable JVM arguments from extensions matching an artifact pattern
```
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <configuration>
                    <extensionJvmOptions>
                        <disableFor>
                            <!-- disable JVM options from all the extensions with groupId org.acme -->
                            <extension>org.acme</extension>
                            <!-- disable JVM options configured in io.quarkiverse:quarkus-magic -->
                            <extension>org.quarkiverse:quarkus-magic</extension>
                        </disableFor>
                    </extensionJvmOptions>
                </configuration>
...
```

Here is a playground repository I use to test this https://github.com/aloubyansky/playground/tree/ext-dev-jvm-args

https://github.com/aloubyansky/playground/blob/ext-dev-jvm-args/quarkus-blue/runtime/pom.xml and
https://github.com/aloubyansky/playground/blob/ext-dev-jvm-args/quarkus-red/runtime/pom.xml
configure dev mode JVM options.

Application https://github.com/aloubyansky/playground/blob/ext-dev-jvm-args/app/pom.xml depends on both of the extensions and can filter out some or all the options from the extensions it depends on.

The project can be launched with `mvn clean compile quarkus:dev -X` from the root directory to see the final command line launching the application logged.

It looks like
```
[DEBUG] Launching JVM with command line: /home/aloubyansky/jdk/jdk-17.0.10/bin/java --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -XX:AllocatePrefetchStyle=1 --add-modules=java.management,jdk.incubator.vector -XX:+UseLargePages --enable-preview -XX:-UseThreadPriorities -Dquarkus-internal.serialized-app-model.path=/home/aloubyansky/git/playground/app/target/quarkus/bootstrap/dev-app-model.dat -javaagent:/home/aloubyansky/.m2/repository/io/quarkus/quarkus-class-change-agent/999-SNAPSHOT/quarkus-class-change-agent-999-SNAPSHOT.jar -XX:TieredStopAtLevel=1 -agentlib:jdwp=transport=dt_socket,address=localhost:5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/aloubyansky/git/playground/app/target/acme-app-dev.jar
```

### CODE REVIEW

**Comment by geoand** [comment]
This is awesome!

I assume that to test it, I should update one of the extensions I have in mind with the `<extensionJvmArgs>` section?

**Comment by maxandersen** [comment]
looks good but can you clarify whats the options/semantics if/when user want to configure these?

do they override them all or can they append/prepend? (order matters for some of these afaik and also behavior of runtime will differ greatly between dev and prod - not saying thats bad but should be documented/make users aware)

Also, this is purely for devmode so for prod users are on their own figuring out what to add? anything we could do there to help?

**Comment by geoand** [comment]
> Also, this is purely for devmode so for prod users are on their own figuring out what to add? anything we could do there to help?

My hope is that once we figure this one out, we can do something similar for prod-mode

**Comment by maxandersen** [comment]
just to give a usecase i'm concerned about - two extensions adding conflicting arguments; how can/will user resolve that?

**Comment by geoand** [comment]
@aloubyansky how would the 

```
-enable-native-access=ALL-UNNAMED
```

JVM flag be enabled?

**Comment by aloubyansky** [comment]
> looks good but can you clarify whats the options/semantics if/when user want to configure these?
> 
> do they override them all or can they append/prepend?

For now everything is merged. It's pretty basic at this point. A user can disable arguments from all or specific extensions and configure their own on top of those.
Exposing `jvmArgs` as a string parameter in `DevMojo` now doesn't look like the best idea. We should probably refactor it to have a similar break down as for extensions in this PR.
There is the `modules` parameter though in `DevMojo` which fits well in here.

> (order matters for some of these afaik and also behavior of runtime will differ greatly between dev and prod - not saying thats bad but should be documented/make users aware)

Could you give an example where order matters? For now I actually order everything alphabetically, which may be a bad idea but it results in a stable command line.

> Also, this is purely for devmode so for prod users are on their own figuring out what to add? anything we could do there to help?

This is still being explored even for dev mode.

**Comment by aloubyansky** [comment]
> just to give a usecase i'm concerned about - two extensions adding conflicting arguments; how can/will user resolve that?

I think the validation and conflict resolution will have to be implemented per argument type, they are quite different. We can point out which arguments from which extensions conflict and let the user resolve it. We can't guarantee a conflict free solution, it may happen as well as with dependencies, capabilities, etc.

**Comment by aloubyansky** [comment]
Here is my playground project with a couple of extensions and an app https://github.com/aloubyansky/playground/tree/ext-dev-jvm-args

Here is how one configures its arguments https://github.com/aloubyansky/playground/blob/ext-dev-jvm-args/quarkus-red/runtime/pom.xml#L34-L42
and here is the other one https://github.com/aloubyansky/playground/blob/ext-dev-jvm-args/quarkus-blue/runtime/pom.xml#L34-L39

And here is the app depending on both of them https://github.com/aloubyansky/playground/blob/ext-dev-jvm-args/app/pom.xml#L59-L66 also adding an extra module https://github.com/aloubyansky/playground/blob/ext-dev-jvm-args/app/pom.xml#L57

To test it the project could be launched from the root with `mvn clean compile quarkus:dev`
Adding `-X` to the `mvn` command will log the actual command launching the app.

**Comment by aloubyansky** [comment]
> @aloubyansky how would the
> 
> ```
> -enable-native-access=ALL-UNNAMED
> ```
> 
> JVM flag be enabled?

It should be `--enable-native-access`, right?
```
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-extension-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>extension-descriptor</goal>
                        </goals>
                        <configuration>
                            <deployment>${project.groupId}:${project.artifactId}-deployment:${project.version}</deployment>
                            <devMode>
                                <jvmArgs>
                                    <enable-native-access>ALL-UNNAMED</enable-native-access>
                                </jvmArgs>
                            </devMode>
...
```

**Comment by aloubyansky** [comment]
If I add it that way to `quarkus-blue` in my playground project, the command will look like
```
[DEBUG] Launching JVM with command line: /home/aloubyansky/jdk/jdk-17.0.10/bin/java --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --enable-native-access=ALL-UNNAMED --add-modules=java.management,jdk.incubator.vector --enable-preview -Dquarkus-internal.serialized-app-model.path=/home/aloubyansky/git/playground/app/target/quarkus/bootstrap/dev-app-model.dat -javaagent:/home/aloubyansky/.m2/repository/io/quarkus/quarkus-class-change-agent/999-SNAPSHOT/quarkus-class-change-agent-999-SNAPSHOT.jar -XX:TieredStopAtLevel=1 -agentlib:jdwp=transport=dt_socket,address=localhost:5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/aloubyansky/git/playground/app/target/acme-app-dev.jar
```

**Comment by geoand** [comment]
I'll check it out, thanks

**Comment by maxandersen** [comment]
> A user can disable arguments from all or specific extensions and configure their own on top of those.

how is that done by the user?

**Comment by aloubyansky** [comment]
> > A user can disable arguments from all or specific extensions and configure their own on top of those.
> 
> how is that done by the user?

See the description (the last XML snippet)

**Comment by maxandersen** [comment]
rather than sorting alphabetically why not sort by dependency order? (and if java honors first/last maybe add it in reverse order)

**Comment by maxandersen** [comment]
actually just realizing that if we just expose explict options and from that generates *one* argument, i.e.

<enable-native-access>ALL-UNNAMED</enable-native-access>
<enable-native-access>some-other-module</enable-native-access>

no matter where it comes from results in:

`--enable-native-access=ALL-UNNAMED,some-other-module`

things are less "chaotic" and if put first in command line give user somewhat freedom to at least append.

Would it make sense to have these generated into a common location (i.e. `/target/quarkus/devmodeflags`) and then refer to it using`@target/quarkus/devmodeflags` and also avoid hitting command line limits on windows?

**Comment by maxandersen** [comment]
> I am not covering `-D` here currently.

-D was just example, add-modules is in here.

But basically I think it is last one wins.

**Comment by aloubyansky** [comment]
> Would it make sense to have these generated into a common location (i.e. `/target/quarkus/devmodeflags`) and then refer to it using`@target/quarkus/devmodeflags` and also avoid hitting command line limits on windows?

Sure, could you point me to a doc or some other impl using this approach?

**Comment by aloubyansky** [comment]
> rather than sorting alphabetically why not sort by dependency order? (and if java honors first/last maybe add it in reverse order)

We could, although in the new resolver impl the dependencies (including extension metadata) are processed in parallel.

**Comment by maxandersen** [comment]
> We could, although in the new resolver impl the dependencies (including extension metadata) are processed in parallel.

with the option of disabling and everything gets grouped its probably fine to use alpha ordering of the values.

**Comment by maxandersen** [comment]
> See the description (the last XML snippet)

will this disable it for everything?

```
<disableFor>
             <extension/>
</disableFor>
```

**Comment by aloubyansky** [comment]
I haven't tested that but this (the previous snippet in the description) will
```
                    <extensionJvmArgs>
                        <disableAll>true</disableAll>
                    </extensionJvmArgs>
```

**Comment by geoand** [comment]
@aloubyansky is there a way that the Maven / Gradle option added in https://github.com/quarkusio/quarkus/pull/43988 could be "enabled"?
Essentially what the options is to prevent `-XX:TieredStopAtLevel=1` from being added to the JVM args

**Comment by aloubyansky** [comment]
> @aloubyansky is there a way that the Maven / Gradle option added in #43988 could be "enabled"? Essentially what the options is to prevent `-XX:TieredStopAtLevel=1` from being added to the JVM args

From an extension? That's a tricky one. Either we create an alias for it or add (more or less) proper support for configuring (some of the) `-XX` options. I could look into this.

**Comment by geoand** [comment]
That would be very nice, thanks!

**Comment by aloubyansky** [comment]
I renamed "arguments" to "options" in the config and API to be inline with the official docs and added a way to configure `-XX:` options (boolean and single valued ones for now). I updated the description of the PR as well.

However,  preventing `-XX:TieredStopAtLevel=1` still seems to be a challenge. I guess either an extension set it to some special value such as `-1` or `unset` (that would be interpreted as "do not set any value") or we do use an alias such as `forceC2` on an extension level.

**Comment by geoand** [comment]
I'm fine either way, whatever you think is best

**Comment by geoand** [comment]
`unset` sound better now that I think of it

**Comment by aloubyansky** [comment]
I was thinking of expressing "unset" something like this

```
  <devMode>
    <unsetXxJvmOptions>Option1,Option2</unsetXxJvmOptions>
  </devMode>

```

That way I wouldn't have to come up with a special value that everyone configuring it will have to remember.

Unset, though, is a bit confusing. What if an option is set with a compatible value?

**Comment by geoand** [comment]
> Unset, though, is a bit confusing. What if an option is set with a compatible value?

By two different extensions you mean? In that case we would arrive at the situation Max is worried about, and the way I see it, would should provide an actionable error message allowing the user to resolve the issue by choosing which extension should win

**Comment by aloubyansky** [comment]
I'd like to clarify and define the semantics of "unset".

When an extension sets a value, that's a request to set a specific value, which may result in a conflict with another extension setting a conflicting value or simply triggering an incompatible behavior in the JVM. In this case, the user will have resolve it by forcing a value that will work.

"Unset" seems to be different in that it seems to be about what not to do. If we imagine we didn't have the "forceC2" option in the plugins, if another extension set that option, the jlama extension would fail, which would be the case above: a conflict caused by some other extension.

Afaiu, we need "unset" to not apply a non-default value by default by a quarkus plugin for example.
So if a user explicitly sets `forceC2=false` in the plugin or another extension does it, this value would be forced in and may result in an error at runtime.

But if `forceC2` is not set to `false` explicitly in the plugin then "unset" in the extension metadata would mean "don't alter the JVM defaults with your dev mode specific defaults" but not more than that.

So it'd be more preserve, retain or keep the original defaults.

Do we agree?

**Comment by geoand** [comment]
> Afaiu, we need "unset" to not apply a non-default value by default by a quarkus plugin for example.

Yes, this exactly right.

> But if forceC2 is not set to false explicitly in the plugin then "unset" in the extension metadata would mean "don't alter the JVM defaults with your dev mode specific defaults" but not more than that

Correct

> So it'd be more preserve, retain or keep the original defaults.

> Do we agree?

+1 from me

**Comment by aloubyansky** [comment]
For now I added `lockDefaultXxJvmOptions` as a comma-separated list of option names that shouldn't be overridden by dev mode defaults. Here is an example config of an extension 
```
                            <devMode>
                                <jvmOptions>
                                    <add-modules>jdk.incubator.vector</add-modules>
                                    <enable-preview/>
                                </jvmOptions>
                                <lockDefaultXxJvmOptions>TieredStopAtLevel</lockDefaultXxJvmOptions>
                            </devMode>
```
How does this look?

**Comment by geoand** [comment]
Very nice!

I'll play with the PR on Monday and see it in action

**Comment by geoand** [comment]
I tried the latest version of the PR on an extension with the following config:

```xml
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-extension-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>extension-descriptor</goal>
                        </goals>
                        <configuration>
                            <deployment>${project.groupId}:${project.artifactId}-deployment:${project.version}</deployment>
                            <devMode>
                                <jvmOptions>
                                    <add-modules>jdk.incubator.vector</add-modules>
                                    <enable-preview/>
                                    <enable-native-access>ALL-UNNAMED</enable-native-access>
                                </jvmOptions>
                                <lockDefaultXxJvmOptions>TieredStopAtLevel</lockDefaultXxJvmOptions>
                            </devMode>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

and when I ran an application using that extension I got:

```posh

[INFO] Scanning for projects...
[INFO] 
[INFO] --< io.quarkiverse.langchain4j:quarkus-langchain4j-sample-review-triage >--
[INFO] Building Quarkus LangChain4j - Sample - Review Triage 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus:999-SNAPSHOT:dev (default-cli) @ quarkus-langchain4j-sample-review-triage ---
[INFO] Invoking resources:3.3.1:resources (default-resources) @ quarkus-langchain4j-sample-review-triage
[INFO] Copying 5 resources from src/main/resources to target/classes
[INFO] Invoking compiler:3.13.0:compile (default-compile) @ quarkus-langchain4j-sample-review-triage
[INFO] Nothing to compile - all classes are up to date.
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ quarkus-langchain4j-sample-review-triage
[INFO] skip non existing resourceDirectory /home/gandrian/projects/redhat/quarkus-langchain4j/samples/review-triage/src/test/resources
[INFO] Invoking compiler:3.13.0:testCompile (default-testCompile) @ quarkus-langchain4j-sample-review-triage
[INFO] Nothing to compile - all classes are up to date.
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Live reload was disabled for the following project artifacts:
- io.quarkiverse.langchain4j:quarkus-langchain4j-jlama:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-core:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-core-runtime-spi:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-core-deployment:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-jlama-deployment:999-SNAPSHOT
The artifacts above appear to be either dependencies of non-reloadable application dependencies or Quarkus extensions
[INFO] Invoking resources:3.3.1:resources (default-resources) @ quarkus-langchain4j-sample-review-triage
[INFO] Copying 5 resources from src/main/resources to target/classes
[INFO] Invoking compiler:3.13.0:compile (default-compile) @ quarkus-langchain4j-sample-review-triage
[INFO] Nothing to compile - all classes are up to date.
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ quarkus-langchain4j-sample-review-triage
[INFO] skip non existing resourceDirectory /home/gandrian/projects/redhat/quarkus-langchain4j/samples/review-triage/src/test/resources
[INFO] Invoking compiler:3.13.0:testCompile (default-testCompile) @ quarkus-langchain4j-sample-review-triage
[INFO] Nothing to compile - all classes are up to date.
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Live reload was disabled for the following project artifacts:
- io.quarkiverse.langchain4j:quarkus-langchain4j-jlama:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-core:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-core-runtime-spi:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-core-deployment:999-SNAPSHOT
- io.quarkiverse.langchain4j:quarkus-langchain4j-jlama-deployment:999-SNAPSHOT
The artifacts above appear to be either dependencies of non-reloadable application dependencies or Quarkus extensions
java.lang.UnsupportedOperationException
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.putIfAbsent(ImmutableCollections.java:1081)
        at io.quarkus.bootstrap.model.JvmOptionsBuilder.addAll(JvmOptionsBuilder.java:140)
        at io.quarkus.deployment.dev.QuarkusDevModeLauncher.setExtensionJvmOptions(QuarkusDevModeLauncher.java:614)
        at io.quarkus.deployment.dev.QuarkusDevModeLauncher.setJvmOptions(QuarkusDevModeLauncher.java:559)
        at io.quarkus.deployment.dev.QuarkusDevModeLauncher.prepare(QuarkusDevModeLauncher.java:377)
        at io.quarkus.deployment.dev.QuarkusDevModeLauncher$Builder.build(QuarkusDevModeLauncher.java:328)
        at io.quarkus.maven.DevMojo.newLauncher(DevMojo.java:1478)
        at io.quarkus.maven.DevMojo$DevModeRunner.<init>(DevMojo.java:1218)
        at io.quarkus.maven.DevMojo.execute(DevMojo.java:496)

```

**Comment by aloubyansky** [comment]
Looking

**Comment by aloubyansky** [comment]
Sorry about that. I had various options in various places and it appeared to work. Fixed now.

**Comment by geoand** [comment]
Things are working now, thanks!

**Comment by geoand** [comment]
I have to do some more digging, but I am pretty sure I'm going to have another request that we won't like :)

**Comment by geoand** [comment]
Okay, so here the latest:

In Dev-mode the JVM still does not apply the proper C2 optimizations for my use case and the reason is the prensence of the debugger.
So ideally I would also want an extension to be able to specify `debug=false` as the default. Users of course can override that, but the OOTB experience would be much better with `debug=false`.

**Comment by aloubyansky** [comment]
Would approaching it as "locking" the `-agentlib` option kinda fit?

**Comment by maxandersen** [comment]
> In Dev-mode the JVM still does not apply the proper C2 optimizations for my use case and the reason is the prensence of the debugger.

damn thats not nice if we now end up with default devmode being debugger disabled because one added an extension. But yeah, I could imagine debugging is not possible with optimzations enabled. Yeah we would need some warning printed - will be interesting how well devmode will actually work once jlama extension disables all the "fun" features.

**Comment by geoand** [comment]
I don't think it will cause too much of a disruption, but the experience for sure won't be as good as with REST + DB applications for example :)

**Comment by aloubyansky** [comment]
Once we get the options we need supported, I'll probably review the design of the config and some impl details. And in case you have any suggestions, please let me know too. Thanks.

**Comment by aloubyansky** [comment]
Here is what I see with that config
```
[DEBUG] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] (main) Adding JVM options from org.acme:quarkus-blue::jar
[DEBUG] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] (main)   enable-native-access: [ALL-UNNAMED]
[DEBUG] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] (main)   add-modules: [jdk.incubator.vector]
[DEBUG] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] (main)   enable-preview: []
[DEBUG] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] (main) org.acme:quarkus-blue::jar locks JVM options [agentlib:jdwp]
[DEBUG] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] (main) org.acme:quarkus-blue::jar locks JVM options [TieredStopAtLevel]
[DEBUG] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] (main) Executable jar: /home/aloubyansky/git/playground/app/target/acme-app-dev.jar
[DEBUG] Launching JVM with command line: /home/aloubyansky/jdk/jdk-17.0.12/bin/java -Dquarkus-internal.serialized-app-model.path=/home/aloubyansky/git/playground/app/target/quarkus/bootstrap/dev-app-model.dat -javaagent:/home/aloubyansky/.m2/repository/io/quarkus/quarkus-class-change-agent/999-SNAPSHOT/quarkus-class-change-agent-999-SNAPSHOT.jar --enable-native-access=ALL-UNNAMED --add-modules=jdk.incubator.vector --enable-preview -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/aloubyansky/git/playground/app/target/acme-app-dev.jar
WARNING: Using incubator modules: jdk.incubator.vector
```

**Comment by aloubyansky** [comment]
Ah, it still adds `-javaagent:path`

**Comment by aloubyansky** [comment]
@geoand is adding the instrumentation agent an issue in your case?

**Comment by aloubyansky** [comment]
How about the following?
```
[WARNING] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] Extension org.acme:quarkus-blue enables the C2 compiler which is disabled by default in Dev mode for optimal performance.
[WARNING] [io.quarkus.deployment.dev.DevModeCommandLineBuilder] Extension org.acme:quarkus-blue disables the debug mode for optimal performance. Debugging can still be enabled in the Quarkus plugin configuration or with -Ddebug on the command line.
```
These would be logged only in case an extension's config is effective. Re-running with `-Ddebug`, for example, will remove the warning.

**Comment by geoand** [comment]
I like the messages, but maybe it should be `INFO` instead of `WARNING`?

**Comment by aloubyansky** [comment]
Ok, I don't mind. I'm thinking of changing
```
                                <lockDefaultJvmOptions>agentlib:jdwp</lockDefaultJvmOptions>
                                <lockDefaultXxJvmOptions>TieredStopAtLevel</lockDefaultXxJvmOptions>
```
to simply
```
                                <lockJvmOptions>agentlib:jdwp</lockJvmOptions>
                                <lockXxJvmOptions>TieredStopAtLevel</lockXxJvmOptions>
```
Otherwise, I think it's in a good shape, unless you have further remarks @geoand.

I still need to implement extension option filtering in the Gradle plugin and document it though.

**Comment by geoand** [comment]
Thanks a lot @aloubyansky!

I will try it soon and let you know if all is good on my side.

**Comment by geoand** [comment]
Tried it and it works like a charm! So from my pov, this is ready to go functionally.

**Comment by aloubyansky** [comment]
Gradle support and the basic docs added.

**Review by geoand — APPROVED** [review]
Awesome stuff!

**Comment by aloubyansky** [comment]
Unless there are objections, I'd prefer merging this one, since I have another PR touching some of the same classes, that will result in conflicts.

**Review by maxandersen — APPROVED** [review]
each extension can express things they want to set and if something goes against something we traditionally hardwired in devmode a info message is logged and users can alwas expliclity set it in their configuration. If conflicts there is a hard fail and user will need to adjust.

Generally +1

I'm not fully sure we shouldn't print WARN for things that goes counter to devmode defaults - like Debugging not being enabled but lets see; also annoying having warnings for something that is expected result from something like jlama needs...

**Comment by aloubyansky** [comment]
> I'm not fully sure we shouldn't print WARN for things that goes counter to devmode defaults - like Debugging not being enabled but lets see; also annoying having warnings for something that is expected result from something like jlama needs...

I changed those to `INFO` after @geoand's feedback.

**Comment by geoand** [comment]
I added the `release/noteworthy-feature` because of it's impact on how the user experience for various extensions can be improved in the future

**Comment by aloubyansky** [comment]
I really hope it won't get popular though :D

**Comment by geoand** [comment]
😆

**Pull request merged**
