### PR TITLE
Do not check for multi-release jar when reading files from META-INF

### PR DESCRIPTION
**Pull request by gsmet**
Related to #41395

### CODE REVIEW

**Comment by gsmet** [comment]
@dmlloyd my understanding is it's the classes that can be multi-releases, right?

Here, I'm trying to avoid reading the manifest when we go find the `quarkus-extension` metadata in the jars.

**Comment by dmlloyd** [comment]
Right, this check looks safe to me.

**Review by dmlloyd — APPROVED** [review]

**Comment by aloubyansky** [comment]
Just in case, the multi release concept isn't limited to classes. 
See Class Loader Resources paragraph in https://openjdk.org/jeps/238 for an example.

**Comment by dmlloyd** [comment]
I think in this case (`META-INF`) it's OK. The JEP says this:

> A JAR file has a content root, which contains classes and resources, as well as a `META-INF` directory which contains metadata about the JAR.

And then later:

> JAR metadata, such as that found in the `MANIFEST.MF` file and the `META-INF/services` directory, need not be versioned.

I would generally extrapolate this to include anything in `META-INF` (including the versioned directories themselves, which otherwise would lead to some ugly recursion problems).

**Comment by aloubyansky** [comment]
Agreed

**Pull request merged**
