### PR TITLE
Allow configuration doc generator to recognise config group declared in another module and generation of config items docs for external extensions

### PR DESCRIPTION
**Pull request by machi1990**
@marcinczeczko can you try out this PR

/cc @gsmet also for double checking.

Needed for https://github.com/quarkusio/quarkus/pull/4968

### CODE REVIEW

**Comment by marcinczeczko** [comment]
@machi1990 I did tests with your changes and works perfect. So from my perspective it's ready to go.

**Comment by machi1990** [comment]
@marcinczeczko thanks for checking. Let's wait for @gsmet approval.

**Comment by machi1990** [comment]
Spotted a few issues. Will check later.

**Comment by machi1990** [comment]
@tomekl007 can you try this PR out locally? With this you should be able to automatic generate configuration documentation. 

The command to use is 
```shell
mvn clean install -DskipTests -DskipITs -Dquarkus.docsOutputDir=.
``` 

which you output the generated docs in `target/asciidoc/generated..`  

The output dir will contain a few noises but what you should be looking at is `quarkus-cassandra.adoc` file. 

This is the first step towards a goal of being able to consume this output from somewhere as it will be needed once the external extension guide is hosted under quarkus.io/guides and to be able to consume it when generating this all configuration page - https://quarkus.io/guides/all-config

**Comment by tomekl007** [comment]
> ```shell
> mvn clean install -DskipTests -DskipITs -Dquarkus.docsOutputDir=.
> ```

I've tested your branch with the Cassandra extensions and it did produce `adoc` files for config:
```
find . | grep adoc | grep config                             
./target/asciidoc/generated/config/quarkus-cassandra-com-datastax-oss-quarkus-deployment-cassandra-client-build-time-config.adoc
./target/asciidoc/generated/config/quarkus-cassandra-general-config-items.adoc
./target/asciidoc/generated/config/config-group-com-datastax-oss-quarkus-config-cassandra-client-connection-config.adoc
./target/asciidoc/generated/config/quarkus-cassandra-com-datastax-oss-quarkus-config-cassandra-client-config.adoc
./target/asciidoc/generated/config/quarkus-cassandra.adoc
```
The Cassandra config is generated as the adoc, i.e.:
```
cat ./target/asciidoc/generated/config/quarkus-cassandra-com-datastax-oss-quarkus-deployment-cassandra-client-build-time-config.adoc
[.configuration-legend]
icon:lock[title=Fixed at build time] Configuration property fixed at build time - All other configuration properties are overridable at runtime
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-cassandra-com-datastax-oss-quarkus-deployment-cassandra-client-build-time-config_configuration]]link:#quarkus-cassandra-com-datastax-oss-quarkus-deployment-cassandra-client-build-time-config_configuration[Configuration property]

h|Type
h|Default

a|icon:lock[title=Fixed at build time] [[quarkus-cassandra-com-datastax-oss-quarkus-deployment-cassandra-client-build-time-config_quarkus.cassandra.health.enabled]]`link:#quarkus-cassandra-com-datastax-oss-quarkus-deployment-cassandra-client-build-time-config_quarkus.cassandra.health.enabled[quarkus.cassandra.health.enabled]`
```
so if this will land in the quarkus next release it would solve our problem. Thank You.
When do you think it could be released?

**Comment by tomekl007** [comment]
> This is the first step towards a goal of being able to consume this output from somewhere as it will be needed once the external extension guide is hosted under quarkus.io/guides and to be able to consume it when generating this all configuration page - https://quarkus.io/guides/all-config

One question regarding hosting docs: do you plan to fetch the docs from our repository, and host them on your `quarkus.io` website?

**Comment by gsmet** [comment]
> When do you think it could be released?

It will be part of 1.5 if all goes well so end of month.

> One question regarding hosting docs: do you plan to fetch the docs from our repository, and host them on your quarkus.io website?

We had a discussion with @machi1990 on this very subject yesterday. We need to think a bit more about it.

**Review by gsmet — APPROVED** [review]
I didn't go into the details but things look good on existing docs and people reported it fixed their issues so let's merge it!

**Comment by tomekl007** [comment]
> ```shell
> mvn clean install -DskipTests -DskipITs -Dquarkus.docsOutputDir=.
> ```

Thank You for your work on that issue.
I am trying to incorporate the process of generating the settings in our extension. I am using `1.5.0.Final` quarkus.
The generation process seems working properly, but there is a problem when creating a final `adoc` with include:
`include::{generated-dir}/config/quarkus-cassandra.adoc[opts=optional, leveloffset=+1]`
I am getting the following error:
```

[INFO] asciidoctor: WARN: Could not locate the character `' in the following fonts: Overpass, M+ 1p Fallback
[INFO] Rendered /Users/tomaszlelek/IntelliJ_workspace/cassandra-quarkus/documentation/src/main/asciidoc/cassandraclient.adoc
[ERROR] asciidoctor: WARN: Could not locate the character `' in the following fonts: Overpass, M+ 1p Fallback
```
We are using the same fonts as you do in the quarkus repo `docs/src/main/resources/themes/fonts`.
Is it possible the generated setting is malformed?

**Comment by tomekl007** [comment]
@gsmet @machi1990 any thoughts regarding this issue?

**Comment by machi1990** [comment]
@tomekl007 sorry, I did not had time to look at the issue yet. 

>..... [INFO] asciidoctor: WARN: Could not locate the character `' in the following fonts: Overpass, M+ 1p Fallback
> [INFO] Rendered /Users/tomaszlelek/IntelliJ_workspace/cassandra-quarkus/documentation/src/main/asciidoc/cassandraclient.adoc
> [ERROR] asciidoctor: WARN: Could not locate the character `' in the following fonts: Overpass, M+ 1p Fallback
> ```
> 
> We are using the same fonts as you do in the quarkus repo `docs/src/main/resources/themes/fonts`.
> Is it possible the generated setting is malformed?

Can you share a link to your document and are you able to pinpoint from which line of the generated doc is causing the issue?

**Comment by tomekl007** [comment]
The error doesn't give any more info besides what I've shared.
I am enclosing the generated file.
[quarkus-cassandra.adoc.zip](https://github.com/quarkusio/quarkus/files/4723246/quarkus-cassandra.adoc.zip)

**Comment by machi1990** [comment]
Thanks @tomekl007 I'd have a look.

**Comment by machi1990** [comment]
> The error doesn't give any more info besides what I've shared.
> I am enclosing the generated file.
> [quarkus-cassandra.adoc.zip](https://github.com/quarkusio/quarkus/files/4723246/quarkus-cassandra.adoc.zip)

I did not have any issue when running I generated the docs after copying the shared generated config docs  and using it in the guide https://github.com/datastax/cassandra-quarkus/blob/master/documentation/src/main/asciidoc/cassandraclient.adoc. The process was done locally on my quarkus project. At this point I am not sure where the error could be coming from. Maybe @gsmet might have some ideas.

**Comment by tomekl007** [comment]
> > The error doesn't give any more info besides what I've shared.
> > I am enclosing the generated file.
> > [quarkus-cassandra.adoc.zip](https://github.com/quarkusio/quarkus/files/4723246/quarkus-cassandra.adoc.zip)
> 
> I did not have any issue when running I generated the docs after copying the shared generated config docs and using it in the guide https://github.com/datastax/cassandra-quarkus/blob/master/documentation/src/main/asciidoc/cassandraclient.adoc. The process was done locally on my quarkus project. At this point I am not sure where the error could be coming from. Maybe @gsmet might have some ideas.

Any news regarding this problem?

**Comment by gsmet** [comment]
I totally missed this thread, let me have a look.

**Comment by gsmet** [comment]
@tomekl007 could you point me to a branch where I can reproduce it?

**Comment by tomekl007** [comment]
https://github.com/datastax/cassandra-quarkus/tree/java2762
When you do:
`mvn clean install -DskipTests -DskipITs -Dquarkus.docsOutputDir=.`
and then generate the final doc file:
`mvn clean package -Prelease` 
there will be a failure

**Pull request merged**
