### PR TITLE
Avoid installing multiple extensions with multiple matches

### LINKED ISSUE #11086: In tooling, do not install any extension when there are multiple matches
**Describe the bug**
I think that by default we shouldn't install any extension when there are multiple matches:

We only list then and tell the user that they can use a flag to "accept" installing all

Example of case where you may not want all installed in the end:

```
addExtensions(asList("jdbc"));

✅ Extension io.quarkus:quarkus-agroal has been installed
✅ Extension io.quarkus:quarkus-jdbc-db2 has been installed
✅ Extension io.quarkus:quarkus-jdbc-postgresql has been installed
✅ Extension io.quarkus:quarkus-jdbc-h2 has been installed
✅ Extension io.quarkus:quarkus-jdbc-mariadb has been installed
✅ Extension io.quarkus:quarkus-jdbc-mssql has been installed
✅ Extension io.quarkus:quarkus-jdbc-mysql has been installed
✅ Extension io.quarkus:quarkus-jdbc-derby has been installed
✅ Extension io.quarkus:quarkus-elytron-security-jdbc has been installed
```

**Expected behavior**
Fail and list the matching extensions

**Actual behavior**
They are installed

This new behavior has appeared with the new registry.

### PR DESCRIPTION
**Pull request by gastaldi**
Unless it's a pattern.

Fixes #11086

### CODE REVIEW

**Comment by gsmet** [comment]
I thought we had tests for that? I remember we did tests some of this.

**Comment by gsmet** [comment]
@maxandersen can you check that one tomorrow morning? That's something I could include in the CR1.

**Comment by maxandersen** [comment]
@ia3andy @gastaldi I assume this code only effects if you enable new registry ? 

Since default users are not affected in master where I get:

```
 mvn quarkus:add-extension -Dextension=jdbc
[INFO] --- quarkus-maven-plugin:1.6.1.Final:add-extension (default-cli) @ test2 ---
❌ Multiple extensions matching 'jdbc'
     * io.quarkus:quarkus-jdbc-derby
     * io.quarkus:quarkus-jdbc-mssql
     * io.quarkus:quarkus-elytron-security-jdbc
     * org.apache.camel.quarkus:camel-quarkus-jdbc
     * io.quarkus:quarkus-jdbc-mysql
     * io.quarkus:quarkus-jdbc-postgresql
     * io.quarkus:quarkus-jdbc-h2
     * io.quarkus:quarkus-jdbc-mariadb
     Be more specific e.g using the exact name or the full GAV.
```

**Review by maxandersen — CHANGES_REQUESTED** [review]
This only affects new registry and looks correct thus lgtm.

**Review by maxandersen — APPROVED** [review]

**Comment by gastaldi** [comment]
Thanks, but looking at the output you pasted it seems like you're testing 1.6.1.Final. 

FYI the original extension lookup algorithm was copied to the extension registry and that's what's being used in the list and add-extension commands, regardless if the Registry URL is specified or not (it falls-back to the extensions in the platform if the registry URL is not provided). This was a special case that was not caught in the exiwting tests but hopefully this should be good now

**Pull request merged**
