### PR TITLE
Make @MultipartConfig work in quarkus-undertow extension

### LINKED ISSUE #6944: MultipartConfig annotation is ignored at HttpServlet by quarkus-undertow
**Describe the bug**
Adding @MultipartConfig to a HttpServlet gets ignored by quarkus. While POSTing a file to the Servlet an IllegalStateException "UT010057: multipart config was not present on Servlet" is thrown.

**Expected behavior**
Quarkus or undertow should respect the MultipartConfig annotation and act accordingly.

**Actual behavior**
Despite adding the requested annotation, it is ignored. And then quarkus complains about missing annotation.

**To Reproduce**
1. Use extracted attached minimal project
2. run "gradlew quarkusDev" inside the project folder
3. create a file "somefile.txt" with random content
4. execute "curl -F'file=@somefile.txt' http://localhost:8080/ul"

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 5.3.0-29-generic x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
 - GraalVM version (if different from Java): not installed
 - Quarkus version or git rev: 1.2.0-Final

**Additional context**
When attaching a debugger while starting quarkus on UndertowDeploymentRecorder at method registerServlet() one can see that the attribute multipartConfig of ServletInfo is null.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4144190/code-with-quarkus.zip)

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #6944

### CODE REVIEW

**Comment by gsmet** [comment]
Please don't push failing test cases as a PR: we are scarce on CI resources.

**Comment by ia3andy** [comment]
> Please don't push failing test cases as a PR: we are scarce on CI resources.

@gsmet ok will do ;-) my bad

**Comment by ia3andy** [comment]
I would like to point out that those lines seems unreachable:
https://github.com/quarkusio/quarkus/blob/c0614ca747fbbf11ed9a2bbdfb58517faa613f6a/extensions/undertow/deployment/src/main/java/io/quarkus/undertow/deployment/UndertowBuildStep.java#L348-L352

And that, this `if` seems weirdly placed, to me it looks like it should be placed at line 348, it's not using any of the stuff from the `for` loop:
https://github.com/quarkusio/quarkus/blob/c0614ca747fbbf11ed9a2bbdfb58517faa613f6a/extensions/undertow/deployment/src/main/java/io/quarkus/undertow/deployment/UndertowBuildStep.java#L379-L383

**Comment by stuartwdouglas** [comment]
getSecurityRoleRefs should be outside the loop, servlet.getMultipartConfig() should be reachable if this is set via XML rather than annotation.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by ia3andy** [comment]
> getSecurityRoleRefs should be outside the loop, servlet.getMultipartConfig() should be reachable if this is set via XML rather than annotation.

@stuartwdouglas 
- I've moved the `getSecurityRoleRefs` after the loop.
- I've moved the `servlet.getMultipartConfig()` after the loop too, at least we do it only once..

**Comment by machi1990** [comment]
@ia3andy seems like the formatter is not happy

**Comment by ia3andy** [comment]
@machi1990 oups :) fixed!

**Comment by ia3andy** [comment]
@gsmet I can merge right?

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Better have a second opinion when you have changed all the implementation after an approval ;).

**Pull request merged**
