### PR TITLE
ArC - register client proxies and subclasses for reflection if needed

### LINKED ISSUE #7507: ArC - register client proxies and subclasses for reflection if needed
Currently, client proxies and subclasses are not registered for reflection. However, sometimes it could be useful to be able to pass a client proxy/subclass of a bean into a third-party library that makes use of reflection at runtime, e.g. to serialize a bean instance to XML/JSON/etc.

The simplest possible implementation would be to register the generated classes if the bean class declares `@RegisterForReflection` ...

### PR DESCRIPTION
**Pull request by mkouba**
- introduce ReflectiveBeanClassBuildItem
- produce ReflectiveBeanClassBuildItem automatically for bean class
annotated with RegisterForReflection
- resolves #7507

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]
LGTM

**Review by manovotn — APPROVED** [review]

**Comment by gsmet** [comment]
@manovotn @Ladicek is it something we should backport?

**Comment by Ladicek** [comment]
That's probably a good idea. WDYT @mkouba?

**Comment by manovotn** [comment]
I am kinda neutral on backporting this. I don't think it's vital feature.

**Pull request merged**
