### PR TITLE
Prevent misuse of modify* in dev mode tests

### PR DESCRIPTION
**Pull request by geoand**
I wasted a few minutes the last time I made
this mistake until I found out what
I had done wrong, so best make it clear
immediately

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Good catch!

**Comment by geoand** [comment]
Let's hope none of the existing tests are actually misusing the methods 😎

**Comment by gastaldi** [comment]
After browsing the sources, shouldn't `modifyResourceFile` call this method too?

**Comment by geoand** [comment]
Ah, I didn't see it was a different implementation. I'm about to head out, so I'd you want to push another commit into this, that's perfectly fine with me

**Comment by gastaldi** [comment]
Actually it should already fail if the file does not exists, so we're good ;)

**Pull request merged**
