### PR TITLE
Add @Cache and @NoCache tests

### LINKED ISSUE #5551: Resteasy @NoCache Annotation doesn't work
Hey,
we were using the `@NoCache` Annotation of RESTEasy to disable the caching for some rest interfaces. It is not working with Quarkus 1.0.0.CR1

It is ignored and no cache related headers are set.

### PR DESCRIPTION
**Pull request by gastaldi**
This PR provides tests for #5551 that would ensure that `@NoCache` and `@Cache` work as advertised.

gsmet: But apparently, the OP still has the issue.

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Let's wait for the OP's feedback before merging this PR and (thus) closing the issue.

**Comment by geoand** [comment]
Seems like a resonable change, but @gsmet's suggestion also makes perfect sense

**Comment by geoand** [comment]
I see from #5551 that this doesn't solve your issue @rboei ?

**Review by gsmet — APPROVED** [review]
Doesn't hurt to have a test. Let's merge this even if it doesn't seem to solve the OP's original issue.

**Pull request merged**
