### PR TITLE
￼ Fix #2547 Camel servlet extension

### LINKED ISSUE #2547: Camel servlet extension
Assigning to me ( @ppalaga ).

@lburgazzoli mentioned in the Fuse chat:

> it would be maybe nice to have a camel-servlet extension
> and have an option to customize path, name and so on trough properties
> so no need to edit any xml
> I think in general we should try to move as much as possible at build time

> ~~another interesting thing would also be to configure [via configuation.properties] the default rest configuration from the camel-servlet extension~~ moved to https://github.com/quarkusio/quarkus/issues/2585

Following up https://github.com/quarkusio/quarkus/pull/2542

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@gnodet @lburgazzoli @oscerd could please anybody of you review?

**Comment by kenfinnigan** [comment]
From looking at the changes it seems that this tests a component that isn't even part of Quarkus, ie. `camel-servlet`?

If that's correct, I'm not sure it makes sense to add these tests to Quarkus

**Comment by stuartwdouglas** [comment]
I agree with Ken, and in addition to this we are likely going to want our own HTTP connectors for Camel on Quarkus to allow Camel to share the same HTTP port as other implementations.

**Comment by ppalaga** [comment]
Sorry to cause dissatisfaction with this. As you may know, Camel integration for Quarkus is looking for its (new?) home. We (camel guys) need to work (code, review, test, etc.) somewhere even before the final destination of the Camel Quarkus code is decided and ready to be used.

If you do not want to accept this PR for reasons you named, OK, let's not merge it, but please keep it open so that we can discuss and test at least.

**Comment by ppalaga** [comment]
bd85b19 adds a Camel servlet extension. The servlet mapping is now done in application.properties instead of web.xml as suggested by @lburgazzoli .

**Comment by lburgazzoli** [comment]
> I agree with Ken, and in addition to this we are likely going to want our own HTTP connectors for Camel on Quarkus to allow Camel to share the same HTTP port as other implementations.

yeah, this is a first step as the servlet component relies on a servlet container provided by the runtime in which camel runs.

**Comment by ppalaga** [comment]
> could be nice to make the default servlet name customizable as well

I'd say it is covered well by the current solution. If you do not like the default name, you can go without using the default servlet (that has no name in the config) and simply add a named servlet instead.

Instead of 

```
# implies servlet name CamelServlet
quarkus.camel.servlet.url-patterns=/folder-1/*
```

you can do

```
# explicit servlet name
quarkus.camel.servlet.my-favorite-servlet.url-patterns=/folder-1/*
```

WDYT?

**Comment by lburgazzoli** [comment]
yes but it creates an additional servlet that it is not in use

**Comment by ppalaga** [comment]
Actually you are right, `CamelServletProcessor.newServlet()` would complain if the default servlet does not have any URL patterns defined. Would loosening that check solve the issue?

**Comment by lburgazzoli** [comment]
I'm advocating to just make the default servlet name configurable with a default as it is on camel sime

**Comment by ppalaga** [comment]
a96ed30 rebased on master and added the `servletName` config option for both default and named servlets. If `servletName` is used for a named servlet, the `servletName` gets the precedence before the name infix.

The RestConfiguration is not set by the extension yet. Because it requires Camel 3.0.0-M3, I have created a new issue for that https://github.com/quarkusio/quarkus/issues/2585

**Comment by oscerd** [comment]
@gsmet this one looks good too.

**Review by oscerd — APPROVED** [review]

**Review by lburgazzoli — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
