### PR TITLE
Use QuarkusClassWriter in HibernateEntityEnhancer

### LINKED ISSUE #3462: TypeNotPresentException during entity augmentation
**Describe the bug**
I'm seeing Maven build failures from the package phase (and later phases) due to entity class augmentation failures.

**Expected behavior**
Jar files are created for the project.

**Actual behavior**
No jar files are created.  This is failing on an entity that is catching a `NoResultException` or a `NonUniqueResultException`.  These classes are in the dependency tree of the project, and show up in the class path and constructed class loader during the build.

**To Reproduce**
Run `./mvnw clean package` on the attached example project.

**Screenshots**
```
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2155ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.066 s
[INFO] Finished at: 2019-08-08T10:03:17-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.20.0:build (default) on project getting-started: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: java.lang.TypeNotPresentException: Type javax/persistence/NoResultException not present: javax.persistence.NoResultException -> [Help 1]
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Linux **** 5.0.0-23-generic #24-Ubuntu SMP Mon Jul 29 15:36:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)
```
 - GraalVM version (if different from Java): n/a (not using GraalVM)
 - Quarkus version or git rev: 0.20.0

**Additional context**
It looks like when `HibernateEnhancingClassVisitor` is constructed, it does not pass along the class loader to the new instance of `ClassWriter`.  It somehow gets a different class loader, which knows nothing about the carefully constructed class loader from Quarkus, so it throws a `ClassNotFound` exception when it processes the entity class, trying to find `NoResultException` or `NonUniqueResultException`.

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #3462

### CODE REVIEW

**Comment by gsmet** [comment]
@sirf could you check if this PR fixes the issue you wanted to fix in https://github.com/quarkusio/quarkus/pull/3507 ?

**Comment by sirf** [comment]
@gsmet Certainly. I'll test it right away.

**Review by geoand — APPROVED** [review]

**Comment by sirf** [comment]
@gsmet Yes, this PR does indeed fix the issue I was having.

**Comment by gsmet** [comment]
OK, let's wait for CI and merge then. Thanks for confirming.

**Pull request merged**
