### PR TITLE
Allow accessing the ClientSession programmatively

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by gsmet** [comment]
@loicmathieu what's the status of this?

**Comment by loicmathieu** [comment]
@gsmet I took the time to finish it and think it could be a nice addition for those who need more control over MongoDB transactions

**Comment by loicmathieu** [comment]
@gsmet can you validate this PR? It is pretty straightforward and will give more flexibility over MongoDB transactions.

**Comment by felixng313** [comment]
I'm looking forward to this feature.

**Comment by loicmathieu** [comment]
Let's try to have a review from someone then ;) 
I also rebase the PR as it's pretty old.

**Review by geoand — APPROVED** [review]

**Comment by felixng313** [comment]
Has the merge failed?

**Review by gastaldi — APPROVED** [review]

**Comment by felixng313** [comment]
The `MongoCollection` only accepts `com.mongodb.client.ClientSession`, but the new function `Panache.getSession()` is returning `com.mongodb.session.ClientSession`. Any advice for this case?

**Comment by loicmathieu** [comment]
@felixng313 this is a bug :(  thanks for pointing it out.

`com.mongodb.client.ClientSession` extends `com.mongodb.session.ClientSession` so when I implement it my IDE auto-complete the wrong ClientSession interface. I'll send a bugfix soon and asl for a backport.

**Comment by loicmathieu** [comment]
@felixng313 as a workaround you should be able to cast the session to `com.mongodb.client.ClientSession` safely.

**Pull request merged**
