### PR TITLE
Index Envers base entity classes

### LINKED ISSUE #12471: quarkus-hibernate-envers should add hibernate-envers to Jandex index
**Description**
The current `quarkus-hibernate-envers` extension doesn't do very much yet. In order to be able to use Envers it would make sense if the extension were to add `hibernate-envers` to the Jandex index, so that errors like the following can be avoided, where it can't find `org.hibernate.envers.DefaultRevisionEntity` indexed:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.8.1.Final:build (default) on project gluon-integration-test-persistence: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: io.quarkus.deployment.configuration.ConfigurationError: Unable to properly register the hierarchy of the following JPA classes as they are not in the Jandex index:
[ERROR]         - org.hibernate.envers.DefaultRevisionEntity
[ERROR] Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
[ERROR]         at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.discoverModelAndRegisterForReflection(JpaJandexScavenger.java:116)
[ERROR]         at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.defineJpaEntities(HibernateOrmProcessor.java:338)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Implementation ideas**
Define a build step adding a corresponding `IndexDependencyBuildItem` build item.

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #12471

@knutwannheden  can you check that this fixes your issue?

### CODE REVIEW

**Comment by knutwannheden** [comment]
> @knutwannheden can you check that this fixes your issue?

LGTM.

**Review by geoand — APPROVED** [review]

**Comment by Sanne** [comment]
Looks good, but I'm wondering how come we didn't catch this? No tests running in native?

**Comment by Sanne** [comment]
BTW I wonder if you considered emitting these entity names as `AdditionalJpaModelBuildItem`, that would ensure we apply enhancements as well. But I'm not sure if these need to be enhanced, so maybe that's not important - just mentioning the option.

**Comment by gsmet** [comment]
That's right, it's probably best. I will adjust my PR.

**Comment by gsmet** [comment]
@Sanne I adjusted the PR.

I have no idea if these classes are used in the normal code path or if something specific needs to be done to trigger it.

@knutwannheden are you doing anything specific?

**Comment by knutwannheden** [comment]
> @knutwannheden are you doing anything specific?

Nothing out of the ordinary, I wouldn't say. But I have not debugged it. I have an entity annotated with `@Audited` and a test using `AuditReader` and `AuditReaderFactory` which fetches some `RevisionInfo` entities.

**Comment by gsmet** [comment]
@knutwannheden if you could come up with a small Maven reproducer with just the minimum needed to reproduce the issue, that would be really helpful so that we're sure it's fixed once and for all.

**Comment by knutwannheden** [comment]
OK. I could try to do that. But I won't be able to look into this until the week after next.

**Comment by gsmet** [comment]
OK, maybe I'll get this merged before that then.

But even so, having a test would be great.

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
> OK, maybe I'll get this merged before that then. But even so, having a test would be great.

+1 merge to merge anytime, but let's not forget to eventually make sure the issue was fixed. Also because I'd like to know why this wasn't caught by the existing integration tests. Clearly our Envers coverage is very limited.

**Comment by knutwannheden** [comment]
I will try to supply that test then. Although I haven't looked at the existing tests, I don't quite understand why it would work correctly without this commit.

**Pull request merged**
