### PR TITLE
Replace Dev UI libs with a composite from mvnpm

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR change the dev-ui libraries to use a composite from mvnpm that creates one jar containing all the (current) ui dependencies.

(see https://mvnpm.org/composites)

This fix 2 issues:
1) Users are not tied to the version of a library defined in dev-ui (in the bom)
2) Faster maven download as there is only one jar now.

### CODE REVIEW

**Comment by maxandersen** [comment]
I grok the idea but I'm not liking it because we are doing something noone else can do afaik. 

How/where are composites defined?
If a user wants to do adjustments or have their own composite is that an option?

Ie. it's under mvnnpm namespace. Not in Quarkus

**Comment by phillip-kruger** [comment]
@maxandersen see https://github.com/mvnpm/composites.

**Review by cescoffier — APPROVED** [review]

**Review by maxandersen — CHANGES_REQUESTED** [review]
I get that - but that means anyone needs to be ok to have the code open.

I'm not saying absolutely no to this but I would like us to:

1) explain why this needs to be in org.mvnpm composite. why not in i.e. quarkus.io and mvnpm opens PR's against a artifact?

2) how this works with CVE's / forks of quarkus etc.

3) how is collisions avoided when users add another version of the lib?

4) how can a user update a library? (I 'm assuming he can't as something in #3 ensures things are isolated??)

5) what decides what goes into the composite? will it not just keep growing? how about backward compatibility if core gets split up more?

**Comment by phillip-kruger** [comment]
So I can (maybe in another PR) change mvnpm to have a dynamic list of where remote composites can live. At the moment, all composite definitions are read off mvnpm/composites GH repo. If I change mvnpm to allow this to be a list, and allow adding more, we can add quarkus GH repo and move the definition there ? Will that help ? And do you think I should do this before merging this ?

**Comment by phillip-kruger** [comment]
Closing for now. I'll circle back to this at some point.

**Pull request closed without merging**
