### PR TITLE
Properly handle Flyway locations prefixed with 'filesystem:'

### LINKED ISSUE #13421: Flyway filesystem location not supported
**Describe the bug**
Any filesystem location added to the `quarkus.flyway.locations` property is ignored

**Expected behavior**
Adding a `filesystem:/path` to the property must make flyway aware of the sql migration files located there, like documented:
```
quarkus.flyway.locations

Comma-separated list of locations to scan recursively for migrations.
The location type is determined by its prefix.
Unprefixed locations or locations starting with classpath: point to a package on the classpath and may contain both SQL and Java-based migrations.
Locations starting with filesystem: point to a directory on the filesystem, may only contain SQL migrations and are only scanned recursively down non-hidden directories.
```

**Actual behavior**
The filesystem locations are ignored

**To Reproduce**

1.  Enable the Flyway extension
2. Add the `quarkus.flyway.locations` to the `application.properties` with a value `filesystem:/path` where the path is pointing to a folder with sql files in it
3. Execute Quarkus, the log will report only the classpath locations

**Configuration**
```properties
quarkus.flyway.locations=db/migration,filesystem:/deployments/scripts
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin MaQ.lan 20.2.0 Darwin Kernel Version 20.2.0: Tue Nov 10 21:14:14 PST 2020; root:xnu-7195.60.70.111.1~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Corretto-11.0.9.11.1 (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.11.1 (build 11.0.9+11-LTS, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.9.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
After some debugging I noticed that the method `FlywayProcessor.discoverApplicationMigrations()` in the flyway extension discards any location that is not resolvable with the class loader

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #13421

### CODE REVIEW

**Comment by gsmet** [comment]
@glefloch the Gradle tests failed for this one: https://scans.gradle.com/s/ydwizpwelqt3o/

**Review by gsmet — APPROVED** [review]
Looks good, thanks!

**Comment by geoand** [comment]
I assume we are safe to merge despite the gradle failures?

**Comment by glefloch** [comment]
Yes I think so. This is the tests that failed on multiple PR on Friday. I added some log so now I will be able to investigate the problem.

**Comment by geoand** [comment]
Cool, thanks

**Pull request merged**
