### PR TITLE
Fix typo in podman.adoc

### PR DESCRIPTION
**Pull request by gemmellr**
Fix typo introduced in previous changes from #39692

### CODE REVIEW

**Comment by gemmellr** [comment]
The earlier PR is marked for backport, so perhaps this one should be too?

@maxandersen @gsmet

**Review by gsmet — COMMENTED** [review]
Thanks, I added the backport labels.

Could you have a look at my comment inline?

**Comment by gemmellr** [comment]
Committed suggestion. Would you prefer I squash the commits, or leave?

**Comment by gsmet** [comment]
Ideally I would prefer them squashed! Thanks!

**Comment by gemmellr** [comment]
Squashed!

**Review by gsmet — APPROVED** [review]

**Pull request merged**
