### PR TITLE
Creation extension command needs artifactIdPrefix

### PR DESCRIPTION
**Pull request by aureamunoz**
The parameters that will be constant for all the extensions are configured in extensions/pom.xml. This config introduces a build dependency on the maven plugin  which leads to an ordering that prevents the tooling to include the generated JSON platform descriptor so has been `commented`. 
Thus, the command to add a new extension to the Quarkus source tree needs to pass also the `artifactIdPrefix` otherwise an error is raised.
Here is the stacktrace:
```
mvn io.quarkus:quarkus-maven-plugin:0.27.0:create-extension -N \
                                                            -Dquarkus.artifactIdBase=my-ext \
                                                            -Dquarkus.nameBase="My Extension"
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< io.quarkus:quarkus-parent >----------------------
[INFO] Building Quarkus - Parent pom 999-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:0.27.0:create-extension (default-cli) @ quarkus-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.770 s
[INFO] Finished at: 2019-10-31T09:02:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.27.0:create-extension (default-cli) on project quarkus-parent: Either artifactId or both artifactIdPrefix and artifactIdBase must be specified; found: artifactId=[null], artifactIdPrefix=[null], artifactIdBase[my-ext] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
Could you please take a look @geoand or forward this PR to someone else?

### CODE REVIEW

**Comment by maxandersen** [comment]
not fully following this one - we shouldn't require users to add prefix. We should fix what is breaking it instead.

**Comment by geoand** [comment]
Asking because we haven't followed the evolution of the devtools. I personally didn't even know there was such a command :)

**Comment by aureamunoz** [comment]
Maybe [this](https://github.com/quarkusio/quarkus/blob/b40baaa04a34d2a14266d354d0e0d6b8189b6a6c/extensions/pom.xml#L131) helps to understand --> the config setting the commons parameters has been commented so now the `artifactIdPrefix` is needed.

**Comment by geoand** [comment]
@maxandersen if what @aureamunoz mentions checks out, I think we should at least update the docs for now

**Comment by maxandersen** [comment]
+1

@aloubyansky wdyt ?

**Comment by aloubyansky** [comment]
+1

**Review by geoand — APPROVED** [review]
Let's add this for the time being and revisit post 1.0.

Thanks @aureamunoz for spotting and this and updating the docs!

**Pull request merged**
