### PR TITLE
Introduce YAML configuration extension

### LINKED ISSUE #3904: Add support for YAML configuration files
Some people prefer yaml for the hierarchical configuration structure we have.
It would be useful I think to support it as an extra `configsource` https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc

`application.yaml`

and make sure we enlist that file for hot reload etc (everywhere `application.properties` is used really).

As for priority, we could decide it's the `.properties` priority + 1 (no strong preference).

Anyone against this?
CC @stuartwdouglas @kenfinnigan @dmlloyd 

I don't think it needs to be documented beyond the configuration guide.

I was wondering if it could/should be an optional extension. Not sure how tied to core it is.

### LINKED ISSUE #4568: CORSConfig is not representable as YAML
As seen during #4525 development, `CORSConfig` cannot be represented as YAML because we'd need the `quarkus.http.cors` key to be both the key of a key/value pair and the key of a dictionary, which is not possible.

A properties-based CORS filter configuration currently looks like this:
```
quarkus.http.cors=true
quarkus.http.cors.origins=http://foo.com,http://www.bar.io
quarkus.http.cors.methods=GET,PUT,POST
quarkus.http.cors.headers=X-Custom
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
```

We only need to change the `quarkus.http.cors=true` property to `quarkus.http.cors.enabled=true` to make it convertible to YAML.

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #3904, fixes #4568, fixes #4525.

### CODE REVIEW

**Comment by gastaldi** [comment]
Will this also close https://github.com/quarkusio/quarkus/pull/4525 ?

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by dmlloyd** [comment]
Yes, it will.

**Comment by dmlloyd** [comment]
It looks like there's still some relocation or dependency related issue.  Part of the build is grabbing an old version of `smallrye-config` and dying as a result.  Looking into it.

**Comment by dmlloyd** [comment]
TBH it almost looks like it's using a stale BOM.

**Comment by geoand** [comment]
@gsmet any idea what could be going on with the dependencies?

**Comment by gsmet** [comment]
How did you solve the issue with `quarkus.http.cors` in the end?

**Comment by gsmet** [comment]
I have a fix for the build issue. It is a funny one. I will push additional commits to David's branch as soon as the tests are OK.

**Comment by gsmet** [comment]
@dmlloyd so... Kogito, Scala and Kotlin test projects had issues so I fixed them all.

I also reordered the commits (even if GitHub doesn't say so) so that my fixes comes before your commits.

Let's see what CI has to say.

**Comment by dmlloyd** [comment]
Thanks @gsmet!  I couldn't even reproduce the problem locally for some reason.  It might have had something to do with the reactor order or something?

**Comment by dmlloyd** [comment]
The way the CORS style problem was solved is by using a null key when you want an entry for the parent name, so given properties `foo.bar` and `foo.bar.baz`, you do:

```yaml
foo:
    bar:
        ~: fooBarValue
        baz: fooBarBazValue
```

**Comment by gsmet** [comment]
Mkay. Cannot say I'm excited about this :).

This should probably be documented somewhere.

**Comment by gsmet** [comment]
@dmlloyd we will need some documentation for this one before Final so work can be done next week.

**Pull request merged**
