### PR TITLE
Dev mode: fix HotDeploymentWatchedFileBuildItem predicate

### LINKED ISSUE #36472: HotDeploymentWatchedFileBuildItem predicate not working when auto-build is enabled (vscode)
### Describe the bug

Currently, Quarkus is looking for modification between the target and the source (when using a HotDeploymentWatchedFileBuildItem.locationPredicate):
https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L913-L914

When using a static location, then it compare a timestamp registered locally (which works):
https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L968

When auto-build is enabled (vscode), the target file and the source file are the same after a modification and the change is not detected by Quarkus.

### Expected behavior

Change should be detected with the HotDeploymentWatchedFileBuildItem.locationPredicate

### Actual behavior

Change is not detected

### How to Reproduce?

https://github.com/ia3andy/web-bundler-jquery

Open with vscode (java enabled), start dev mode and change something in `src/main/resources/web/...` (reload)

### PR DESCRIPTION
**Pull request by mkouba**
- also mention the glob pattern in HotDeploymentWatchedFileBuildItem javadoc and optimize glob pattern processing
- fixes https://github.com/quarkusio/quarkus/issues/36472

### CODE REVIEW

**Comment by ia3andy** [comment]
I will have a look early next week thanks @mkouba, don't hesitate to remind me if I don't..

**Review by glefloch — APPROVED** [review]
This looks good to me!

**Comment by mkouba** [comment]
> @cescoffier the VT tests are really getting in the way. Not sure why they are so unstable but it's concerning. Could you have a look or ask someone to have a look?

I can try to take a look. Hopefully, it's not caused by the #36466 :facepalm:.

**Comment by cescoffier** [comment]
@mkouba @gsmet We need to bump everything to Java 21. We have the Mandrel builder image ready. That should improve things.

**Comment by gsmet** [comment]
@cescoffier this is in progress on my side but somehow we have a disk space issue when the runner is using Java 21. I'm slowly diagnosing it but it takes time, given each round takes ~4-6 hours...

**Comment by mkouba** [comment]
This pull request is ready to merge but let's wait for Andy's approval...

**Comment by mkouba** [comment]
Ping @ia3andy ;-)

**Comment by ia3andy** [comment]
Thanks @mkouba :), It's on my today's daily tasks. 

I had a few urgent things to do as I am just back from a conf trip. I am having a look now !

**Comment by ia3andy** [comment]
Ok it's still not working, I am debugging...

**Review by ia3andy — CHANGES_REQUESTED** [review]
That should help:
image

It seems the Map contains a relative path, while the check is on the full path in the contains, is that expected?.

**Comment by ia3andy** [comment]
Also here (I guess this is why it doesn't work):
image

**Comment by ia3andy** [comment]
Hey @mkouba, 

I've tested it in the situation that caused the issue and it now works as expected 🎉

This part of the code seems to have grown a bit too tentaculous, my concern is more on the fact you are not confident with your commit (which is a good improvement already), maybe we should create an issue and expand on those concerns?

**Review by ia3andy — APPROVED** [review]
Thanks @mkouba

**Comment by mkouba** [comment]
> Hey @mkouba,
> 
> I've tested it in the situation that caused the issue and it now works as expected 🎉
> 
> This part of the code seems to have grown a bit too tentaculous, my concern is more on the fact you are not confident with your commit (which is a good improvement already), maybe we should create an issue and expand on those concerns?

Yes, we should definitely create a tracking issue to refactor this area.

**Comment by mkouba** [comment]
The test failures seem to be related. Investigating...

**Comment by mkouba** [comment]
It seems that some of the failures are related. Investigating again...

**Comment by mkouba** [comment]
@ia3andy Could you pls retest your app with this PR? I did some more refactoring and I believe that it's ready to merge.

@gsmet I wonder if it's even possible these days to pass all the CI jobs if you make a change in the `core` modules? I mean there are timeouts, flaky tests, etc.

**Comment by ia3andy** [comment]
testing...

**Comment by ia3andy** [comment]
@mkouba it works... thanks!!

**Comment by mkouba** [comment]
Test failures are unrelated - merging...

**Pull request merged**
