### PR TITLE
Bump io.dekorate to 0.12.11

### PR DESCRIPTION
**Pull request by Vinche59**
Signed-off-by: Vincent Sourtin <sourin-v@bridgestone-bae.com>

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel which dekorate release should we use?

**Comment by Vinche59** [comment]
Actually version 0.12.10 contains also the fix I need.
@iocanel it's up to you. Just tell me if I have to close this pr.

**Comment by iocanel** [comment]
The later the better

**Comment by geoand** [comment]
The PR needs to rebased onto master

**Comment by Vinche59** [comment]
rebase done.

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Maybe add it to dependabot?

**Comment by geoand** [comment]
Nah, I think we want to control this one more closely

**Comment by gastaldi** [comment]
@geoand I agree, looking at https://github.com/dekorateio/dekorate/releases I see a lot of 1.0.x and 2.x releases that might require some changes in Quarkus. 

BTW, just curious, why we are not using 1.0.3?

**Comment by geoand** [comment]
IIRC, the 1.x releases are centered around Spring Boot - @iocanel would know best

**Pull request merged**
