### PR TITLE
Support Surefire 3.0.0-M5

### PR DESCRIPTION
**Pull request by Tibor17**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

Can you please rebase onto the latest `master`? I want to see if CI will pass or not.

**Comment by Tibor17** [comment]
@geoand 
There are test failures. Pls see the stacktraces.
Fasterxml missing subtypes, Could not stop Keycloak server.

**Comment by geoand** [comment]
The reason I am asking is because those tests all pass on `master`. If they fail with this PR, then it would be nice to know why - what changed that cause them to fail so we can update them as part of this PR

**Comment by Tibor17** [comment]
@geoand 
I do not have time to analyse this but i see what everybody can see. See them, open it and see the stacktrace.

**Comment by geoand** [comment]
I understand that, what I'm saying is that it would be nice to know what changed in Surefire that could cause these failures.

**Comment by Tibor17** [comment]
For instance we are able to handle the exceptions thrown in @Before methods.
This was a required fix by JUnit5 users.
Also other errors are handled from JUnit5. I think now this handler is more objective.

For instance we had a discussion at the mailing list during the release and one JUnit5 user was opointing to a difference with errors thrown in Before between 2.22.2 and M5. Finally, we agreed that M5 is objective because the same result is observed by IDEA.

Not sure if these errors with marshaller are JDK related but it would be nice to reproduce it locally with identical platform.

**Comment by Tibor17** [comment]
@geoand 
Is somebody investigating the errors found in the log?

**Comment by geoand** [comment]
Not yet, hopefully we'll look into it come Monday

**Comment by Tibor17** [comment]
@geoand 
Obviously the provider `JUnitPlatformProvider` failed in constructor because the instance fields attempt to instantiate the JUnit5 objects and internal code of JUnit5 `org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.<clinit>` failed as a root cause due to JBoss logger could not find some class.

As I said before, we ignored these errors, and this happens exactly before any tests atart running.

[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[ERROR] 	at java.util.logging.LogManager$1.run(LogManager.java:195)
[ERROR] 	at java.util.logging.LogManager$1.run(LogManager.java:181)
[ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
[ERROR] 	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
[ERROR] 	at java.util.logging.Logger.demandLogger(Logger.java:448)
[ERROR] 	at java.util.logging.Logger.getLogger(Logger.java:502)
[ERROR] 	at org.junit.platform.commons.logging.LoggerFactory$DelegatingLogger.<init>(LoggerFactory.java:80)
[ERROR] 	at org.junit.platform.commons.logging.LoggerFactory.getLogger(LoggerFactory.java:51)
[ERROR] 	at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.<clinit>(ServiceLoaderTestEngineRegistry.java:32)
[ERROR] 	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:87)
[ERROR] 	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:67)
[ERROR] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.<init>(JUnitPlatformProvider.java:90)
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] 	at org.apache.maven.surefire.api.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:123)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.createProviderInCurrentClassloader(ForkedBooter.java:491)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

**Comment by Tibor17** [comment]
@geoand 
You have fixed these uncovered issues in #10146 ?

**Comment by geoand** [comment]
That was definitely one issue. Can you rebase the PR onto master so we can see if CI passes now or if there are more issues?

**Comment by Tibor17** [comment]
@geoand 
done

**Comment by geoand** [comment]
All tests pass, great! 

Could I trouble to  rebase onto master again? The reason I am asking is that we made a change to #10146 and I would like to ensure that nothing broke with regards to this.

Thanks

**Comment by gsmet** [comment]
I just pushed a rebase.

**Comment by geoand** [comment]
Thanks

**Comment by Tibor17** [comment]
@geoand 
Pls have alok at this test in `Quarkus CI / JDK Java 8 - 242 JVM Tests (pull_request)`
It looks like Basic Auth failure
 [ERROR] Failures: 
[ERROR]   FormAuthCookiesTestCase.testCredentialCookieRotation:184->doRegularGet:135 Session cookie WAS NOT eligible for renewal and should have remained the same. ==> expected: <DBCucILj++O9vRjU2h7qq5JbrFrzPUgrm1vYOv2YBh+btNqFJu5oJ4gdk+hjan7Y> but was: <DOh/zejFs/YxwI9Drpw5RbIqYWT4vmRE9MXz+NyN7WAPkF6Bph++h+YBW59uiaBE>
[INFO] 
[ERROR] Tests run: 71, Failures: 1, Errors: 0, Skipped: 1

**Comment by geoand** [comment]
I'll have a look tomorrow or Friday

**Comment by gsmet** [comment]
I force pushed a rebase to fix a few conflicts. Let's wait for CI and merge.

**Comment by geoand** [comment]
Assuming everything works 🤪

**Review by geoand — APPROVED** [review]
All green, nice!

**Comment by geoand** [comment]
Let me just check one last thing before merging

**Comment by geoand** [comment]
Thanks a lot for this!

We'll let you know if we run into any issues

**Comment by famod** [comment]
@geoand I am wondering whether the quickstarts should be adjusted as well?

**Comment by geoand** [comment]
For 1.7 where this change will take effect, it makes sense

**Comment by famod** [comment]
It seems there are still some modules picking up Surefire 2.22.0 from `jboss-parent`, e.g. `quarkus-devtools-common`.
(e.g. https://github.com/quarkusio/quarkus/pull/10311/checks?check_run_id=811868118)

I'll have a look.

**Comment by geoand** [comment]
Thanks @famod!

**Pull request merged**
