### PR TITLE
Fix request hanging condition

### LINKED ISSUE #37807: SSL requests hang when returning a CompletableFuture
### Describe the bug

Requests hang when an endpoint is returning a CompletableFuture and SSL is active. When turning off SSL or the endpoint is changed to not return a CompletableFuture, the requests seem not to hang.
The requests hang for the time specified in `quarkus.http.idle-timeout`.

### Expected behavior

Requests should not hang.

### Actual behavior

Requests hang.

### How to Reproduce?
[hanging-ssl.zip](https://github.com/quarkusio/quarkus/files/13704513/hanging-ssl.zip)

1. Unzip the attached zip-archive
2. Run the project
3. Do a GET request to http://localhost:8080/test/count (here http does not matter)
4. Notice that "Request completed" is never printed (well, after `quarkus.http.idle-timeout` it is, but that defaults to 30m)
5. If changing the code such that the endpoint test/bytes is used internally, "Request Completed" is eventually printed

The example code uses OkHttpClient, but it is possible to reproduce with java.net.HttpClient aswell, but that seems to require  more iterations.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This condition could happen when a TLS secured connection had a lot  of data written to it very fast from an event loop thread.

The problem was that there was a race condition
on the registration of the drain handler,
which then resulted in the pending data never
being written out.
The fix is to always register the drain handler

- Resolves: #37807

### CODE REVIEW

**Comment by geoand** [comment]
@cescoffier would you like to add commit with the unit test you came up with?

@franz1981 this should be safe from a performance standpoint, but I would like to have it tested if possible.

Thanks

**Comment by cescoffier** [comment]
@geoand I just pushed the 4 unit tests. Unfortunately, does not seem to pass yet....

**Comment by geoand** [comment]
Yeah, see https://github.com/quarkusio/quarkus/issues/37807#issuecomment-1914245348

**Comment by cescoffier** [comment]
Ok, got something super simple that seems to fix the problem. Let's see what the CI says.

**Comment by geoand** [comment]
🥳

**Comment by cescoffier** [comment]
@geoand the question is.... who do we ask to approve :-D

**Comment by geoand** [comment]
I don't think there is anyone else 😄

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
