### PR TITLE
RESTEasy Reactive: Move more logic outside Quarkus

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This allows RR to have its own unit tests that do
not require Quarkus to bootstrap, while also making
the code more re-usable.

There is more work to do in this area, but this is bulk of the
changes, and has a high chance of conflicting with other RR
changes.

### CODE REVIEW

**Comment by geoand** [comment]
Seems like the PR is missing formatting

**Comment by geoand** [comment]
CI is saying that `VertxRequestContextFactory.java` is not formatted

**Comment by geoand** [comment]
Looks great!

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
CI is passing 🎉 

@FroMage want to take a look as well?

**Review by FroMage — APPROVED** [review]
:shipit:

**Pull request merged**
