### PR TITLE
Make sure we have Agroal datasources before configuring health checks

### LINKED ISSUE #43990: Healthcheck results in NPE when no JDBC datasources are defined after breaking changes in 3.17
### Describe the bug

Here https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.17#datasources-without-a-url-no-longer-contribute-a-health-check is described that datasources no longer contribute to a health check when they are deactivated. However I am getting NPE for a code that previously worked and I am not sure what to do.

### Expected behavior

Document what to do or fix the NPE.

### Actual behavior

Exception is raised:

```
14:09:17,604 INFO  [app] 14:09:15,903 SRHCK01000: Error processing Health Checks: java.lang.NullPointerException: Cannot read field "entries" because "agroalSupport" is null
14:09:17,605 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck.init(DataSourceHealthCheck.java:47)
14:09:17,605 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_Bean.doCreate(Unknown Source)
14:09:17,605 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_Bean.create(Unknown Source)
14:09:17,606 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_Bean.create(Unknown Source)
14:09:17,606 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
14:09:17,606 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
14:09:17,607 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
14:09:17,607 INFO  [app] 	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c11(Unknown Source)
14:09:17,607 INFO  [app] 	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
14:09:17,608 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
14:09:17,608 INFO  [app] 	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
14:09:17,608 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.arc$delegate(Unknown Source)
14:09:17,608 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(Unknown Source)
14:09:17,609 INFO  [app] 	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
14:09:17,609 INFO  [app] 	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
14:09:17,609 INFO  [app] 	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
14:09:17,609 INFO  [app] 	at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
14:09:17,610 INFO  [app] 	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
14:09:17,610 INFO  [app] 	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
14:09:17,610 INFO  [app] 	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
14:09:17,610 INFO  [app] 	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
14:09:17,611 INFO  [app] 	at io.quarkus.smallrye.health.runtime.QuarkusAsyncHealthCheckFactory$1$1.call(QuarkusAsyncHealthCheckFactory.java:42)
14:09:17,611 INFO  [app] 	at io.quarkus.smallrye.health.runtime.QuarkusAsyncHealthCheckFactory$1$1.call(QuarkusAsyncHealthCheckFactory.java:39)
14:09:17,611 INFO  [app] 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
14:09:17,611 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
14:09:17,611 INFO  [app] 	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
14:09:17,612 INFO  [app] 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
14:09:17,612 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
14:09:17,612 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
14:09:17,612 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1591)
14:09:17,613 INFO  [app] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
14:09:17,613 INFO  [app] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
14:09:17,613 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
14:09:17,613 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:1583)
14:09:17,613 INFO  [app] 14:09:15,912 SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"liveness","status":"UP"},{"name":"readiness","status":"UP"},{"name":"io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy","status":"DOWN","data":{"exceptionClass":"java.lang.NullPointerException","exceptionMessage":"Cannot read field \"entries\" because \"agroalSupport\" is null","rootCause":"Cannot read field \"entries\" because \"agroalSupport\" is null"}},{"name":"greeting","status":"UP"}]}
14:09:17,614 INFO  [app] 14:09:16,596 SRHCK01000: Error processing Health Checks: java.lang.NullPointerException: Cannot read field "entries" because "agroalSupport" is null
14:09:17,614 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck.init(DataSourceHealthCheck.java:47)
14:09:17,614 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_Bean.doCreate(Unknown Source)
14:09:17,614 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_Bean.create(Unknown Source)
14:09:17,614 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_Bean.create(Unknown Source)
14:09:17,615 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
14:09:17,615 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
14:09:17,615 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
14:09:17,615 INFO  [app] 	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c11(Unknown Source)
14:09:17,615 INFO  [app] 	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
14:09:17,616 INFO  [app] 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
14:09:17,616 INFO  [app] 	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
14:09:17,616 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.arc$delegate(Unknown Source)
14:09:17,616 INFO  [app] 	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(Unknown Source)
14:09:17,617 INFO  [app] 	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
14:09:17,617 INFO  [app] 	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
14:09:17,617 INFO  [app] 	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
14:09:17,617 INFO  [app] 	at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
14:09:17,617 INFO  [app] 	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
14:09:17,617 INFO  [app] 	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
14:09:17,618 INFO  [app] 	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
14:09:17,618 INFO  [app] 	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
14:09:17,618 INFO  [app] 	at io.quarkus.smallrye.health.runtime.QuarkusAsyncHealthCheckFactory$1$1.call(QuarkusAsyncHealthCheckFactory.java:42)
14:09:17,618 INFO  [app] 	at io.quarkus.smallrye.health.runtime.QuarkusAsyncHealthCheckFactory$1$1.call(QuarkusAsyncHealthCheckFactory.java:39)
14:09:17,618 INFO  [app] 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
14:09:17,618 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
14:09:17,618 INFO  [app] 	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
14:09:17,619 INFO  [app] 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
14:09:17,619 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
14:09:17,619 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
14:09:17,619 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
14:09:17,619 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
14:09:17,619 INFO  [app] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
14:09:17,619 INFO  [app] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
14:09:17,620 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
14:09:17,620 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:1583)
14:09:17,620 INFO  [app] 14:09:16,597 SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"readiness","status":"UP"},{"name":"io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy","status":"DOWN","data":{"exceptionClass":"java.lang.NullPointerException","exceptionMessage":"Cannot read field \"entries\" because \"agroalSupport\" is null","rootCause":"Cannot read field \"entries\" because \"agroalSupport\" is null"}},{"name":"greeting","status":"UP"}]}
```

### How to Reproduce?

1. `git clone git@github.com:michalvavrik/quarkus-test-suite.git -b feature/health-check-npe-reproducer`
2. `quarkus-test-suite/javaee-like-getting-started`
3. `mvn clean verify -Dit.test=JavaEELikeHealthCheckIT`

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

Temurin 21

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #43990

### CODE REVIEW

**Comment by gsmet** [comment]
@michalvavrik I tried to add a test to the `quarkus-agroal-deployment` module but I couldn't reproduce the issue. I'm not sure what you're doing to trigger it specifically. Do you have an idea of how we could reproduce it in the main repo?

**Review by yrodiere — APPROVED** [review]
LGTM, though I find it odd that the bean would not be resolvable... I suspect the bean having the default scope (dependent), toghether with the use of bytecode recorders, might have something to do with that, so I sent a suggestion to your fork: https://github.com/gsmet/quarkus/pull/193

**Comment by michalvavrik** [comment]
> @michalvavrik I tried to add a test to the `quarkus-agroal-deployment` module but I couldn't reproduce the issue. I'm not sure what you're doing to trigger it specifically. Do you have an idea of how we could reproduce it in the main repo?

I tried, but inside Argoal deployment module you have a JDBC extension (H2) so I think you won't reproduce it there. If you drop it you can reproduce it like this https://github.com/quarkusio/quarkus/commit/84813f9f65380b58a30da48913fa70c89f0bdd88. So unless you have different module I don't think you can reproduce it.

**Comment by gsmet** [comment]
OK, I think we will have to live with it then. @michalvavrik if you can independently verify the last version of this PR fixes it for you, that would be awesome.

**Review by yrodiere — APPROVED** [review]

**Review by michalvavrik — APPROVED** [review]
I tried the latest version and it fixes my issue. Thank you

**Pull request merged**
