### PR TITLE
Agroal is missing essential metadata labels

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Review by machi1990 — COMMENTED** [review]
Maybe we can also add the guide - https://quarkus.io/guides/datasource

```
guide: https://quarkus.io/guides/datasource
```

?

**Comment by gsmet** [comment]
@machi1990 let's add it in another PR.

**Comment by machi1990** [comment]
> @machi1990 let's add it in another PR.

Let me prepare it.

**Comment by geoand** [comment]
The CI failure is most likely due to the PR needing a rebase onto master. I am not sure that it's worth burning CI cycles however, it looks safe to me, but I'll let others decide

**Comment by machi1990** [comment]
I was about to merge this change as CI failure is unrelated.

**Comment by geoand** [comment]
Up to y'all :)

**Pull request merged**
