### PR TITLE
OpenApi does not find generated REST resources due to checking only base index

### PR DESCRIPTION
**Pull request by mswiderski**
…ase index

this fixes missing OpenAPI definition of REST resources that were generated instead of being part of the source tree.

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by gsmet** [comment]
There are test failures that look related:
```
[ERROR] Failures: 
[ERROR]   OpenApiTestCase.testOpenAPIJSON:65 Normal and RX/Single have same schema ==> expected: <{"get":{"responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"$ref":"#/components/schemas/String"}}}}}}}> but was: <{"get":{"responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"type":"string"}}}}}}}>
[INFO] 
```

**Comment by emmanuelbernard** [comment]
@mswiderski the CI raises this error

```
OpenApiTestCase.testOpenAPIJSON:65 Normal and RX/Single have same schema ==> expected: <{"get":{"responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"$ref":"#/components/schemas/String"}}}}}}}> but was: <{"get":{"responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"type":"string"}}}}}}}>
```

**Comment by mswiderski** [comment]
@gsmet @emmanuelbernard looking into it, so far it looks like `BeanArchiveIndexBuildItem .getIndex()` makes the schema of the response to be a reference instead of just the type... haven't figured out yet what it does it ... if you have any hints please let me know

**Comment by mswiderski** [comment]
bit of an update, `BeanArchiveIndexBuildItem .getIndex()` has indexed String as well and that's why it produces a reference instead of type but it has not indexed `Single<String>` and that's they the difference in test.

So questions are:
- why is the String type part of the `BeanArchiveIndexBuildItem .getIndex()`? 
- is this expected?

In the end the openapi definition is still the same, it is only either using reference or type directly. So I could change the test to take that into account. Please let me know your thoughts on this.

**Comment by emmanuelbernard** [comment]
I'm a bit out of my knowledge zone. What is `Single`, the RxJava type?

@n1hility will know more but I suspect Jandex includes or resolves the JDK types  and that's why `java.lang.String` is in the index. If `Single` is in RXJava and we don't index it, then it's unknown.

@EricWittmann @kenfinnigan what would be the expected return type for the failing test here?

**Comment by FroMage** [comment]
Note that `Single<T>` is just like `CompletionStage<T>` and  `T` in that it should generate the exact same OpenAPI response type. The Quarkus-OpenAPI RESTEasy extension makes sure that the RESTEasy async return types are supported, which includes `CompletionStage` and RxJava2's `Single`, so in theory SR-OpenAPI does not neep to know about them because our extension converts them to `T`.

**Comment by FroMage** [comment]
I don't think a reference or a direct type make a difference in the generated openapi document, so that's probably fine, if you can resolve the reference and make sure they are in fact the same type in the test.

I am however curious why `String` is in this specific index because I was under the impression we did not index stuff from the JDK.

**Comment by mswiderski** [comment]
> I don't think a reference or a direct type make a difference in the generated openapi document, so that's probably fine, if you can resolve the reference and make sure they are in fact the same type in the test.

ok, will work on test changes to compare the actual type of the schema

> I am however curious why String is in this specific index because I was under the impression we did not index stuff from the JDK.

same here, though this is only done by BeanArchiveIndex...

**Comment by mswiderski** [comment]
test case updated to take into account the reference when comparing schema types

**Review by FroMage — APPROVED** [review]
LGTM now, thanks!

**Pull request merged**
