### PR TITLE
Adding tests to create and verify an object-store directory

### PR DESCRIPTION
**Pull request by mayankkunwar**
https://issues.redhat.com/browse/QUARKUS-679

### CODE REVIEW

**Review by Sgitario — COMMENTED** [review]
If this property is only effective for XA transactions, this should be noted in the documentation. 
What about using "quarkus.datasource.jdbc.transactions=XA"?

**Comment by mayankkunwar** [comment]
We create object-store when needed, not for every transaction, object-store would be created. I am not sure what to document, whenever there is a need of object-store internal to JTA-transaction we create it, otherwise we don't.

The issue was to just set the path of object-store whenever it is created.

**Comment by mayankkunwar** [comment]
@rsvoboda Thanks for the clarification. I think there is already a issue created https://github.com/quarkusio/quarkus/issues/9623 . Maybe we could add these tests as part of the mentioned issue?

**Comment by rsvoboda** [comment]
+1, I'm going to add approval for this PR

**Review by rsvoboda — APPROVED** [review]

**Review by Sgitario — APPROVED** [review]

**Pull request merged**
