### PR TITLE
Introduce full indexing of specific directories of the classpath

### LINKED ISSUE #13256: Classloader optimisations for resource loading
**Description**
This is about optimising how our (production) classloader `RunnerClassLoader` can efficiently open resources, and release the internal caches so to keep using a minimal footprint.

**Implementation ideas**
Vertx has a caching layer implemented by `io.vertx.core.file.impl.FileResolver`, which will trigger loading the full list of resources of any parent directory as well when a single resource is requested, as it attempts to then create a cache on filesystem.

This is an interestin idea, but it doesn't play along well with the current implementation of the Quarkus `RunnerClassLoader`, as attempting to load e.g. `META-INF/resources/` will trigger the load on all jars which have such a resource path (which means opening many jar files).

Following up on ideas discussed in #13219 , some options IMO worth considering:

 - pre-load all the resources during boot, keep them in memory (and disable the Vertx FS-cache ?)
 - actually leverage the `io.vertx.core.file.impl.FileResolver` explicitly during boot to build up the cache on filesystem, then release all caches
 - extract the "hot resources" during build of the application into the filesystem? (For example static webpages?)
 - we could opt to be more fine-grained indexing in the map _packages/ClassLoadingResource_ in `RunnerClassLoader`, specifically for resources to have more precision - so to hit the right jar files.

## StaticResourcesBuildItem

We could also take this opportunity to actually process the resources which have been explicitly mentioned by `StaticResourcesBuildItem` more optimally, and fallback to a "slow mode" (existing?) for any unlisted resource.

This could be an opportunity to provide a warning about the need of a resource being loaded, as this would fail in native mode.

## ServiceProviderBuildItem

Similarly services from `META-INF/services/` could be specifically optimised, and we can take advantage of having a fallback mode in JVM which would produce a warning for native mode.

## Testing for proper resource configuration

To make it more obvious that there's a missing resource registration, I'd also propose having an environment flag which upgrades the warning into an exception.
This would be useful during testing; although I believe it's probably best left as an opt-in to not nag people too much - especially as they might not be interested in extreme optimisations and/or native images.

### PR DESCRIPTION
**Pull request by geoand**
The PR introduces indexing for `META-INF/services` and the root directory of the jars on the classpath.
I only added those 2 as those are the ones I saw being used by all applications.

Fixes: #13256

### CODE REVIEW

**Comment by geoand** [comment]
@stuartwdouglas @Sanne FYI

**Comment by geoand** [comment]
@stuartwdouglas I assume you prefer this over https://github.com/quarkusio/quarkus/pull/13365. If so, I'll close the latter

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I think this is the better approach.

**Comment by geoand** [comment]
@Sanne do you want to take quick look as well or should I just merge and you can check from `master`?

**Comment by Sanne** [comment]
> @Sanne do you want to take quick look as well or should I just merge and you can check from `master`?

I'm back and want to play with this soon, but I can do that also after it's merged..  Don't wait for me :)

**Comment by geoand** [comment]
OK, I'll merge.

When you get a chance to play with it, let me know how it goes please :)

**Pull request merged**
