### PR TITLE
Don't close the connection when returning Multi

### LINKED ISSUE #18445: Quarkus Resteasy Reactive does not respect keep-alive when using Multi<>s
## Describe the bug

Quarkus Resteasy Reactive kills connections even if Connection: keep-alive is specified and acknowledged by the server.

The problem only occurs when returning Multi<>s, not when returning Uni<>s or synchronous results.

A simple method such as

```
    @GET
    public Multi<String> async(){
        return Multi.createFrom().item("async");
    }

```
and then calling

`curl http://localhost:8080 http://localhost:8080 -v -H "Connection: keep-alive`

reproduces the problem.

### Expected behavior
Quarkus Resteasy Reactive should behave like non-reactive and keep the connection alive.

### Actual behavior
The connection is dead after the first request.

## To Reproduce

Small project based on the Quarkus Reactive quick-start.

https://github.com/rasmusfaber/quarkus-resteasy-reactive-connection-drop

1. Run the included tests and notice that `testHelloEndpointAsyncMulti` fails.
Or
1. Build and start the application
2. Run `curl http://localhost:8081/hello/async http://localhost:8081/hello/async -v -H "Connection: keep-alive"`
3. Notice that the second connection fails and curl needs to create a new connection (compare with `curl http://localhost:8081/hello/sync http://localhost:8081/hello/sync -v -H "Connection: keep-alive"`)

### Output of `uname -a` or `ver`
Linux xxx 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

### Quarkus version or git rev
2.0.0.Final (also 1.13.3.Final)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
apache-maven-3.6.3

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #18445

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@FroMage @geoand any idea why this was here? It should not be necessary.

**Comment by geoand** [comment]
I personally don't

**Review by FroMage — CHANGES_REQUESTED** [review]
Obviously it is necessary, otherwise it woudn't be there with a big fat comment. But I probably didn't know how to write a test for this, and I can't remember now. Let's fix it but please add a test that checks that we didn't close the connection?

And then when someone figures out something didn't work we'l get a reproducer for the original issue for free :)

**Comment by rasmusfaber** [comment]
> Let's fix it but please add a test that checks that we didn't close the connection?

Feel free to use the test in https://github.com/rasmusfaber/quarkus-resteasy-reactive-connection-drop/blob/main/src/test/java/org/acme/getting/started/ReactiveGreetingResourceTest.java

It should be easy to modify it to fit into quarkus-integration-test-resteasy-mutiny (just change the endpoint) or I will be happy to make a pull request if you prefer.

**Comment by stuartwdouglas** [comment]
Damnit, that test works on my machine

**Comment by FroMage** [comment]
> Damnit, that test works on my machine

That's like 95% of my daily routine, man :rofl:

**Review by FroMage — APPROVED** [review]

**Pull request merged**
