### PR TITLE
Limit `MATCHING_RESOURCES` TestResources to the test that declares them

### LINKED ISSUE #44235: 3.16: `@WithTestResource` starts all test resources (regression)
### Describe the bug

Since Quarkus 3.16 (including 3.16.1, 3.15.1 is fine) our integration test classes start literally test-resources from all literally all `@WithTestResource` annotations, even for those that are not (yet) executed.

Before 3.16(.1), only the test-resource for the currently running integration-test-class were started.

The major change in behavior that I could identify so far is in `io.quarkus.test.common.TestResourceManager#restrictToAnnotatedClass`, which now delegates to the `TestResourceClassEntryHandler` implementations (for `@QuarkusTestResource` and `@WithTestResource`). (Admittedly, [`restrictToAnnotatedClass` could never yield `true` before 3.16](https://github.com/quarkusio/quarkus/blob/a98a3f91fc06c959672b67ece75516bb59b994cd/test-framework/common/src/main/java/io/quarkus/test/common/TestResourceManager.java#L481).)

Since [restrictToAnnotatedClass() checks for `== RESTRICTED_TO_CLASS`](https://github.com/quarkusio/quarkus/blob/8a67e7919a7e373bd6edc6036c915aff23f25c1a/test-framework/common/src/main/java/io/quarkus/test/common/TestResourceManager.java#L494) on all annotations "everywhere", it initialized and starts all test resources. This can lead to e.g. 4 Keycloaks, 2 Minios and a bunch of other containers 🤷 

Our integration-tests are annotated using `@WithTestResource(value = xyz.class)`, leaving the default scope `MATCHING_RESOURCES` to leverage the `... Quarkus will not restart when running consecutive tests that use the same set of resources.` behavior.

The current workaround is to set the scope to `RESTRICTED_TO_CLASS`.

/cc @geoand 

### Expected behavior

* Only have the test-resources for the current test class running
* Group tests by test-resources, considering "initArgs"
* Don't start the "whole world" ;)

### Actual behavior

_No response_

### How to Reproduce?

I do have a reproducer, but it's still a (local) WIP to bump Quarkus to 3.16.1 in Nessie, including the workaround mentioned above.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by snazy**
- Closes: #44235

### CODE REVIEW

**Comment by snazy** [comment]
@geoand your change LGTM! I've added some missing scope-checks, which otherwise eventually caused callbacks via `AbstractTestWithCallbacksExtension` not being properly registered, causing class-loader issues with `NoSuchMethodException`s due to "stale" callbacks still being registered.

Applied the change against the `3.16.1` tag and ran our integration tests, manually verifying that only the right test-resources (containers) are running.

**Comment by geoand** [comment]
Thanks a lot!

**Comment by geoand** [comment]
@snazy something seems to have broke with the latest change

**Comment by snazy** [comment]
@geoand yea, just making `MATCHING_RESOURCES` work like `RESTRICTED_TO_CLASS` isn't enough (actually, too much).

**Review by geoand — APPROVED** [review]

**Comment by jedla97** [comment]
@geoand @snazy looking at this at this and think that this bug fix should be documented in release notes as it can possibly break someone tests. 
Our one TS adopted this back in September and I probably use incorectly `MATCHING_RESOURCES` scope (Probably I interpret the java docs incorectly and it was working fine). There can be some early adopter of this which done same error as me (also in guides we still use `@QuarkusTestResource` so there isn't much example or info about this).

If I understand this change correctly. If you want use the `MATCHING_RESOURCES` you need to anotate every test class with it, to all the test classes with same resource are grouped together and use that resource without restart. Before this PR it behave same/similar to `GLOBAL`, that there was no need of anotation of every test classes. So it was enough to have one `testResource` class to start the resource to be used for all the test.

Simply:
* `RESTRICTED_TO_CLASS` start for every test class
* `MATCHING_RESOURCES` start for specific group of test classes
* `GLOBAL` start for every test class

**Comment by geoand** [comment]
> Before this PR it behave same/similar to GLOBAL, that there was no need of anotation of every test classes

Correct, but this was a bug honestly

**Comment by geoand** [comment]
That said, improvements to the docs and / or Javadoc are always welcome :)

**Comment by holly-cummins** [comment]
@snazy, have you got a reproducer I could run for the callbacks issue? I'm doing a rebase as part of https://github.com/orgs/quarkusio/projects/30. After my changes, I think the callback clearing is either going to need to be implemented differently (classloader issues), or may not be needed at all. I'm not entirely sure which it is, and want to make sure I don't mess it up!

**Pull request merged**
