### PR TITLE
RootDefinition - trim RuntimeConfig and RuntimeConfiguration suffixes

### LINKED ISSUE #7257: RootDefinition should also trim RuntimeConfig and RuntimeConfiguration suffixes
If a config root has a `RuntimeConfig` suffix (not `RunTimeConfig`) only the `Config` part of the suffix is removed and so the property must include the `-runtime` part, ie. for `io.quarkus.quartz.runtime.QuartzRuntimeConfig#threadCount` the `quarkus.quartz-runtime.thread-count` property must be used.

This works as designed and documented, but:
(1) The generated configuration references in docs does not reflect this behavior - see for example https://quarkus.io/guides/quartz#quartz-configuration-reference
(2) In most cases the usage of `RuntimeConfig` is very likely NOT intentional but a typo

Proposed solution:
1. Fix the `RootDefinition`, ie. trim the `RuntimeConfig` and `RuntimeConfiguration` suffixes
2. Fix docs generator
3. Update the docs
4. Intruct the clients of the affected configurations to switch to the new values

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #7257

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Seems reasonable to me

**Comment by gsmet** [comment]
Note for myself: breaking change is that everything `quarkus.quartz-runtime.*` should be `quarkus.quartz.*`.

**Review by machi1990 — APPROVED** [review]

**Comment by mkouba** [comment]
The CI failures seem to be unrelated: `io.quarkus.it.kubernetes.KubernetesWithHealthTest` and `##[error]One or more errors occurred. (One or more errors occurred. (An error occurred while sending the request.))` for `jpa-h2, jpa-mariadb, jpa-mssql, jpa-derby, jpa-without-entity`.

**Comment by geoand** [comment]
@mkouba yes, the test seems to be flacky... Of course it never happened when I was developing it...

But I'll look into it now

**Comment by geoand** [comment]
A PR about fixing the flaky tests has been opened, so I am now going to restart the failed tests in this PR

**Pull request merged**
