### PR TITLE
Disable native tests execution for elytron-security-ldap

### LINKED ISSUE #6606: quarkus-elytron-security-ldap-integration-test fails in the native mode
**Describe the bug**
Georgios @geoand has spotted it is not part of [the native CI build](https://github.com/quarkusio/quarkus/blob/master/ci-templates/stages.yml#L262) and fails locally when run in the native mode with:
```
[quarkus-elytron-security-ldap-integration-test-999-SNAPSHOT-runner:26719]     analysis:  27,176.27 ms
Error: Unsupported features in 2 methods
Detailed message:
Error: Class initialization of org.wildfly.security.auth.client.ElytronMessages failed. Use the option --initialize-at-run-time=org.wildfly.security.auth.client.ElytronMessages to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.NoClassDefFoundError: org/wildfly/client/config/ConfigXMLParseException
        at java.lang.Class.forName0(Native Method)
```

### PR DESCRIPTION
**Pull request by gastaldi**
This PR enables native compilation but fails native execution failing with:

`Fatal error: Failed to leave the current IsolateThread context and to detach the current thread. (code 12)` 

Fixes #6606

### CODE REVIEW

**Comment by geoand** [comment]
This effort is great, but given the problems that still exist, I don't really know what we should do with this module.


@sberyozkin I think it should be up to you

**Comment by gastaldi** [comment]
Yeah, definitely it doesn't seem to work in native. The application is killed with that error (may be a bug in GraalVM?)

**Comment by sberyozkin** [comment]
Hi George, Georgios; George, thanks for looking into it, I'm sorry, the code of the extension looked sound to me, so from a non-LDAP expert's point of view it was good to go and it works in the JVM mode. IMHO we should ask the author of the PR to spend some time on this issue too, I'll CC in the issue. Perhaps we should mark this extension as experimental ?

**Comment by sberyozkin** [comment]
FYI `quarkus-smallrye-jwt` did not work for a while in the native mode too :-)

**Review by sberyozkin — APPROVED** [review]

**Pull request merged**
