### PR TITLE
Upgrade Kotlin Maven plugin to 1.6.20

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
Merging as it's needed for tonight's Jakarta rewrite build.

**Comment by MartinX3** [comment]
Could it get backported to 2.8?

**Comment by Sanne** [comment]
@MartinX3 this change only updated what we use in the conversion script - I suppose you need a different change?

Feel free to send a PR with any change you need, if it works we can consider that for backport.

**Comment by MartinX3** [comment]
@Sanne I'm sorry. I think it was an accident to comment it here.
Link to https://github.com/quarkusio/quarkus/pull/24086

**Pull request merged**
