### PR TITLE
CLI - Rework how missing commands are detected

### PR DESCRIPTION
**Pull request by gsmet**
We had a problem here as most options are only valid in the context of the root command (for instance -D) so trying to parse them in the context of a subcommand or on their own will most probably fail.

Also parsing recursively the command is non-efficient as we do a lot of parsing, especially since it was done twice (this was fixed too).

The new approach uses the ParseResult generated once and get the knownledge from there. From my tests, it provides similar results and avoid false positives and running the parsing too many times.

This should fix CliHelpTest#testCommandHelp() being flaky as not being able to interpret the options ended up triggering the missing command branch and then the JBang support.

### CODE REVIEW

**Comment by maxandersen** [comment]
good catch so doing `quarkus -Dblah create app` vs `quarkus create app -Dblah` is what triggered it ?

**Comment by gsmet** [comment]
well, even `quarkus --help --Dsomething` would trigger it. Basically, anything with `-` option could trigger it.

**Comment by gsmet** [comment]
Part of the problem is that we were considering options as potential subcommand in this `checkMissingCommand` thing.

**Comment by gsmet** [comment]
Also my guess is that this will be significantly faster as parsing the command has an important cost.

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
