### PR TITLE
Add mutual SSL properties

### PR DESCRIPTION
**Pull request by CSTDev**
These bits allow us to use mutual SSL authentication, and should enable using certificates for user authn/authz. ([Little discussion here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/mutual.20tls.20client.20auth))

Adds property for enabling ClientAuth for the engine Vertx uses. 
Allows you to set the trust store information for the server to verify incoming request certificates against.

### CODE REVIEW

**Comment by geoand** [comment]
Can you please rebase onto the latest `master`? 

There is a CI fix that should take care of the error reported.

Thanks

**Comment by sberyozkin** [comment]
@CSTDev Will Vertx set the information about the client certificate on the HTTP request context object or some extra step is needed ? In the latter case I'll create another issue, it would not be a blocker for this PR. We'll need this information for some of the OIDC work.  

Thanks

**Comment by sberyozkin** [comment]
@CSTDev Can you please add a test, not sure it will be possible to add a 2-way TLS test to https://github.com/quarkusio/quarkus/tree/master/integration-tests/vertx-http, if not then you can just copy and paste that module into `integration-tests/vertx-http-mtls`. Should not take much time, thanks

**Comment by CSTDev** [comment]
@sberyozkin Yes I believe it does add the information to the request context. And will look at putting a test in now.

**Comment by sberyozkin** [comment]
@CSTDev Thanks for adding a test :-). Can you check if the test resource has to be added, the tests fail with 
```
java.nio.file.NoSuchFileException: server-keystore.jks
```

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@CSTDev It still fails:
```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.345 s <<< FAILURE! - in io.quarkus.it.vertx.VertxProducerResourceTest
[ERROR] testRouteRegistrationMTLS  Time elapsed: 0.274 s  <<< ERROR!
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1322)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
```
I wonder if the tests are interfering with each other...

@gsmet, @stuartwdouglas I don't really want to delay this PR as we need 2-way TLS for sure, may be it is not even possible to test it in the native mode ? What do you think ? I believe the native SSL is enabled with Vertx HTTP...

**Comment by CSTDev** [comment]
@sberyozkin yes, sorry, I thought it might still as I was having some issues with the sunEC library locally and wondered if it was just local which from the errors in the tests here it looks like it was. I can give putting the test in a separate module, as you suggested, a go tomorrow if it might be interfering.

**Comment by CSTDev** [comment]
hmm, makes no difference in a separate module (other than not failing the existing tests). Trying to get it to work in native mode on it's own still...

**Comment by sberyozkin** [comment]
@CSTDev I think it worked:
```
bernate ORM with Panache SUCCESS [ 14.999 s]
[INFO] Quarkus - Integration Tests - Hibernate Search + Elasticsearch SUCCESS [01:09 min]
[INFO] Quarkus - Integration Tests - Vert.x HTTP .......... SUCCESS [  8.047 s]
[INFO] Quarkus - Integration Tests - Vert.x ............... SUCCESS [  9.690 s]
```
[INFO] Quarkus - Documentation ............................ FAILURE [ 23.376 s].
Can you please rebase ?

**Comment by gsmet** [comment]
We had some CI issues, I force pushed a rebase to your branch.

**Comment by gsmet** [comment]
Closing this one, I will merge into a large PR.

**Comment by CSTDev** [comment]
@gsmet Ok, is it possible to trigger the CI so I can see the problem, or do I need to push something to get it to do? Or can you give me a link to where it failed please?

**Comment by CSTDev** [comment]
Working on this, will fix...

**Comment by gsmet** [comment]
I don't know if it was a CI issue to be honest, I had the issue on my Linux laptop when testing the PR.

**Comment by CSTDev** [comment]
> I don't know if it was a CI issue to be honest, I had the issue on my Linux laptop when testing the PR.

Ok that's kinda useful to know, I'm having no issues locally on a Linux machine, running native and jvm tests, which is why I'm having issues resolving it.

**Comment by sberyozkin** [comment]
@CSTDev Can you please run `mvn process-sources` on the test code ?

**Comment by sberyozkin** [comment]
@stuartwdouglas, @cescoffier  Hi Stuart, Clement, can some extra logging added in the quarkus vertx code to help @CSTDev trace the test issue ? I believe the test passes for @CSTDev locally.

@CSTDev how do you run the tests ? Does it pass for you when you run only this test in `integration-tests/vertx-http` ? Does it pass when you run all the tests in `integration-tests/vertx-http` ? What about doing `mvn clean install` from the root of the project ?

**Comment by CSTDev** [comment]
@sberyozkin I've been running the tests with `mvn clean verify` (and with the -Dnative flag for those ones). Both individually, as a module and from the root directory I did  `mvn clean install`.

However, I just realised I'm running Java 8, just got 11 down and getting failures, so can actually try to fix it now, sorry!

**Comment by CSTDev** [comment]
It appears it's something to do with the certificates I've generated, they were using the DSA alg which as of Java 11 doesn't work. Have re-generated ones using RSA which now work on both Java 8 and 11, but back to the tests failing in Native mode. They're PKCS12 keystores, not sure if that's causing my problem

**Comment by CSTDev** [comment]
This warning is what's causing the Native test to fail, anyone have an idea what might cause it? 

```
WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.
```

**Comment by KarlScheibelhofer** [comment]
I just realized this issue exists. When I checked the issues some weeks ago, it wasn't there. Thus I started some own efforts to implement the same feature.

You can find what I have done so far under:
https://github.com/KarlScheibelhofer/quarkus/tree/sslclientauth

It is similar to what CSTDev implemented. 

Here are the differences I saw:
 * In my version, there are some [JUnit-Tests in extensions/vertx-http/deployment](https://github.com/KarlScheibelhofer/quarkus/tree/sslclientauth/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/ssl) with a script for recreating all [keys and certificates](https://github.com/KarlScheibelhofer/quarkus/blob/sslclientauth/extensions/vertx-http/deployment/src/test/resources/conf/create-keys.sh)
 * There ist also an Option for the three different types REQUIRED, REQUEST, NONE in my [client config class](https://github.com/KarlScheibelhofer/quarkus/blob/sslclientauth/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ClientAuthConfig.java)
 * I did not implement any native tests or separate integration tests.

If you want, take from my code pieces whatever you like.

I guess it might be best for me to wait for CSTDev's code to show up in quarkusio:master. An then see if I can contribute some tests or the client auth type (REQUIRED, REQUEST, NONE).

**Comment by CSTDev** [comment]
@KarlScheibelhofer Thanks for that, looks good, especially the other tests and the script for generating the certificates! This PR does have the bits for the three auth types (REQUEST,REQUIRE NONE), but I may move them round to be in a separate class with the trust store like yours. 

I'm still having issues with the native tests. Did you attempt to write any when you did this?

**Comment by sberyozkin** [comment]
@CSTDev Can you check this issue, https://github.com/oracle/graal/issues/951 ? There is a lot of information there. May be also worth asking at Zulip

**Comment by sberyozkin** [comment]
@CSTDev congratulations, thanks for persevering and getting this test green in the native mode.
@gsmet, Hi Guillaume, I'm going to merge shortly as I'm going offline a bit earlier today due to me traveling, unless you have some other comments. I'm marking it for 1.1.0, not 100% sure about a Backport, even though the changes look isolated and seem safe. Thanks

**Comment by sberyozkin** [comment]
@CSTDev In meantime, if you could find some cycles to update the vertx http guide on how to do the mutual TLS  then it would be appreciated

**Pull request merged**
