### PR TITLE
Set current/explicit Keycloak version in docs examples

### PR DESCRIPTION
**Pull request by rsvoboda**
Set current/explicit Keycloak version in docs examples

Similar fix happened in QS - https://github.com/quarkusio/quarkus-quickstarts/pull/387
I was playing with Keycloak 8 and hit issues in native mode.

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
There is a build property in the parent pom, we should inject it in the doc and use it.

See https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L82 .

**Comment by rsvoboda** [comment]
@gsmet can you point me to an example ? Something like `${keycloak.docker.image}` ?

**Comment by rsvoboda** [comment]
Looking at asciidoctor-maven-plugin config and following `graalvm-version` way

**Comment by gsmet** [comment]
Yeah sorry. We already do that for a couple of attributes, you just need to do exactly the same!

You might have to use the following if the variable is used in a source block:
```
[source,subs=attributes+]
```
This enables variable substitution in a source block.

Ping me on Zulip if you have any further issue!

**Comment by rsvoboda** [comment]
@gsmet PR updated, already figured out my way

**Review by gsmet — APPROVED** [review]

**Pull request merged**
