### PR TITLE
Handle all possible dependency scopes in update-dependencies.sh

### PR DESCRIPTION
**Pull request by glefloch**
This branch update the `update-dependencies.sh` script to look for all kind of scope in gradle (adding `api` and `quarkusDev`)

### CODE REVIEW

**Review by galderz — APPROVED** [review]

**Review by famod — APPROVED** [review]
I suppose this also works with BSD grep (I went through a lot of troubleshooting with @kenfinnigan back then).

**Comment by glefloch** [comment]
@famod I think, the `E` flag is used in the expression below.

**Comment by famod** [comment]
Yeah, `-E` should be supported and the extended expression should be ok too. I just cannot test it, I'm on Windows and WSL2 Ubuntu, not macOS.

**Comment by glefloch** [comment]
OSX is ok, I tested it on my machine

**Comment by famod** [comment]
Ha, should have led with that! 😉

**Comment by galderz** [comment]
Thx @glefloch for fixing this! :)

**Pull request merged**
