### PR TITLE
Quartz - remove the deprecated StoreType.DB

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by machi1990 — CHANGES_REQUESTED** [review]
LGTM. 

There are some CI failure because of usage of the removed enum. Can you have a look?

**Comment by mkouba** [comment]
@machi1990 Should be fixed now.

**Review by machi1990 — APPROVED** [review]

**Comment by Sgitario** [comment]
I think this change should be mentioned in the migration guide (to use `jdbc-cmt` instead of `db`).
What do you think @mkouba  ?

**Comment by mkouba** [comment]
> I think this change should be mentioned in the migration guide (to use `jdbc-cmt` instead of `db`).
> What do you think @mkouba ?

It's already there ;-). I added the note when this PR got merged.

**Pull request merged**
