### PR TITLE
Enable tracing in the SmallRye GraphQL extension

### LINKED ISSUE #9322: OpenTracing integration in the SmallRye GraphQL extension
SmallRye GraphQL includes support for OpenTracing, we just need to properly integrate it and add a few tests.

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #9322 
cc @phillip-kruger

### CODE REVIEW

**Comment by jmartisk** [comment]
It seems that `io.quarkus.smallrye.graphql.deployment.ui.DisabledTest` starts failing as soon as I add the `quarkus-smallrye-opentracing` dependency to the test classpath - if I do that, the `graphql-ui` directory with some static resources seems to be picked up and served as a static resource even if `quarkus.smallrye-graphql.enable-ui=false`, therefore a call to `/graphql-ui/index.html` will return 200 (but will return a broken UI because it's not wired correctly). 
Interestingly, it only happens during test, I wasn't able to duplicate this with devmode or prod mode. Anyone has an idea how to prevent this from happening?

**Comment by geoand** [comment]
It seems like we need to have a way for `QuarkusUnitTest` to exclude a dependency when running one of the internal tests.
We don't have that now AFAIK, but it would probably make sense to have it down the line. @aloubyansky  WDYT? If you think it's a good idea, I can look into it.

**Comment by jmartisk** [comment]
That could be useful, but it does not explain or fix the root cause why the `graphql-ui` directory is picked up and served as static resources (in test mode only). I tried debugging into it, but got lost within vert.x code that I don't understand much.

**Comment by aloubyansky** [comment]
Are the dependencies and the configuration the same for devmode, prod and tests in this case? If they are the same, we should observe the same responses in all modes, iiuc.

**Comment by jmartisk** [comment]
The dependencies will never be exactly the same because we're talking about a regular application versus a unit test within the codebase of a Quarkus extension. But generally I'd say they are more or less the same. Also tried reproducing the same with `@QuarkusTest` within an application project, but couldn't. It only happens with a `QuarkusUnitTest`.

**Comment by geoand** [comment]
Hm, can't you do the following:

Instead of adding 

```
quarkus-smallrye-opentracing
```

as a Maven project dependency, can't you just add it via `forcedDependencies` to whatever tests you need it in?

**Comment by jmartisk** [comment]
If I remove it from the pom and add it just to `GraphQLTracingTest` via
```
.setForcedDependencies(
                    Collections.singletonList(
                            new AppArtifact("io.quarkus", "quarkus-smallrye-opentracing", Version.getVersion())));
```
then the test passes only if I run that test separately. If I run any other test along with it in the same Maven execution, it behaves as if the opentracing dependency is not there.
I have absolutely no idea why. There must be something fishy with tests not being properly isolated.

**Comment by geoand** [comment]
> I have absolutely no idea why. There must be something fishy with tests not being properly isolated.

You can probably just add `quarkus-smallrye-opentracing` as a `provided ` dependency to make it come before graphql in the Maven reactor and that should work.
We do use a similar trick elsewhere IIRC

**Comment by jmartisk** [comment]
You mean in `pom.xml`? Making it `provided` won't  make it available during tests.

**Comment by geoand** [comment]
> You mean in `pom.xml`? Making it `provided` won't make it available during tests.

Yeah, that's what I'm saying. But I just now saw that you actually need opentracing in your tests, so forget everything I have said in this issue :)

**Comment by jmartisk** [comment]
I removed the line from `DisabledTest` which asserts a 404 response from the `/graphql-ui/index.html` path. It still asserts a 404 from `/graphql-ui`, that passes without problem, so I suppose the tests should pass now.
It's a bit of a shortcut, but I have no idea how else to fix it, and apparently it only affects tests, so I think it shouldn't really matter. I hope no one will be strongly against this shortcut :D

**Comment by geoand** [comment]
Fine with me

**Comment by gsmet** [comment]
@phillip-kruger can you review that one?

**Review by phillip-kruger — APPROVED** [review]
LGTM! Thanks @jmartisk !

**Review by geoand — APPROVED** [review]

**Pull request merged**
