### PR TITLE
index.html (welcome page) now dynamic

### LINKED ISSUE #1499: Improve index.html welcome page
We include in Quarkus a welcome page when creating a new project.

The current file is here: https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/test/resources/projects/classic/src/main/resources/META-INF/resources/index.html .

It could use some love once we have a logo. @jkbrock could your team take care of it once everything is settled? It's the first thing people will see when creating a new app so I think it deserves to be nice.

### LINKED ISSUE #5236: Move handling of NotFound http code from resteasy to the vertx-http extension
**Description**
Current the `NotFound` error page is handled by `resteasy` via https://github.com/quarkusio/quarkus/blob/44e029ba5f100594f1fe235c63c3aee280f253b9/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/NotFoundExceptionMapper.java. 

This presents two setbacks:

- We are unable to list `vertx-web` rest endpoints and various others endpoints eg swagger, metrics, health. 
- Also, if we change the http root path via quarkus.http.root-path to something else (other than /) and try to load localhost:8080/ we get `Resource not found` generated by `vertx` instead of the error page. 

**Implementation ideas**
- Add a `DisplayableEndpointBuildItem`. 
- add a `404 failure handler` in `vertx-http` to intercept 404 http codes
- make `resteasy`, `undertow`, `vertx-web` and `spring-web` and other extensions  produce the build item so that can be propery consumed and listed from the `vertx-http` in case of a 404 error. 

/cc @gsmet @stuartwdouglas .

### LINKED ISSUE #8392: Hyperlink Rest Resources on 404 page
**Description**
When an application attempts to access an invalid REST endpoint, Quarkus will provide a 404 page with a list of valid endpoints. There are some additional developer joy opportunities here:

1. Make non-parameterized resource access a hyperlink to application endpoint on 404 pages. Seems like low-hanging fruit with a nice upside.
2. Optional: Make resource parameters editable in 404 page. This is a nice-to-have feature and is not intended to be feature rich and replace swagger UI. Alternatively, if swagger extension is loaded, provide hyperlink to swagger endpoint.
Browser_Preview__404_-_Resource_Not_Found__—_mp-spring

### PR DESCRIPTION
**Pull request by phillip-kruger**
### The welcome page
The static index.html page that get generated with a quarkus app, is now replace with a dynamic page from Dev UI. This page will render on the naked domain if the user does not provide their own index.html (and only in Dev mode)

dynamic_welcome

- Fixes #1499

### The not found page
This PR also moves the Not Found page (that renders in Dev Mode) to Vertx-http, removing it from resteasy-reactive, resteasy-classic, spring-web, reactive-routes. Also, undertow should also now display this not found page.

The handler for Not found is last in the queue, so any user, or extension, can override this behavior, by adding their own handler for Not Found.

new_screens

@ia3andy ResumeOn404BuildItem should not be needed anymore. Please can you confirm (I might be wrong) and if so we can remove ResumeOn404BuildItem on another PR

The management interface is now also working. The links (for management interfaces) was omitted in the NotFoundPage (in the current version). I have now added them, and also added a Not Found Page for the management interface. So now if you enable management, and go to 0.0.0.0:9000/non-existing-resource, that will show the Not Found page, with the links correctly added

**Breaking change (with a workaround  if needed)**

In the current version, if you have a JAX-RS Filter, that filter will run, even in the case that the requested resource was not a REST resource (in my opinion, that is wrong). This will not happen anymore. Filters for JAX-RS will now only run on JAX-RS resources. In the case that you want your Filters to also run on non JAX-RS resource, you need to add your own ExceptionMapper:

```java
package io.quarkus.resteasy.reactive.server.test.customproviders;

import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.ext.ExceptionMapper;
import jakarta.ws.rs.ext.Provider;

@Provider
public class NotFoundExeptionMapper implements ExceptionMapper<NotFoundException> {
    @Override
    public Response toResponse(NotFoundException exception) {
        return Response.status(404).build();
    }
}
```

Now, JAX-RS becomes responsible for the Not Found resources, and the Filter will run. In the current version where this always happens, it makes it impossible for other extensions to handle Not Found.

- Fixes #5236

### The routes page
This PR also includes a new tab in the Endpoints menu in Dev UI, that display the routes and their order. It's not perfect, but something we can build on, and it does help with debugging.

image

This also:

- Fixes #8392

### CODE REVIEW

**Comment by maxandersen** [comment]
Wdym about the codestart info?

It's added in readme and index.html - now jt will just be in the readme or is it something different you refer to?

**Comment by cescoffier** [comment]
I like the idea but what happen in test and prod mode?

**Comment by phillip-kruger** [comment]
> Wdym about the codestart info?
> 
> It's added in readme and index.html - now jt will just be in the readme or is it something different you refer to?

@maxandersen  Yes, that is what I mean, it is not in the index.html anymore. I could probably still get it with some effort. (this is where I need @ia3andy to comment)

> I like the idea but what happen in test and prod mode?

@cescoffier in test and prod the route that serve the index.html will not be created. This (I think) is more correct. At the moment the generated index.html will be served (in prod !) and it's highly unlikely that this is what the user want. The use can create their own index.html and then that will be served in dev, test and prod. However, we should probably guide the user to the UI options in Quarkus (Quinoa, Web Bundler, Renade etc) and a plain static file in META-INF resources has it's limits. Maybe we need a guide that starts with plain static resource, then Renade, then Web bundler then Quinoa ?

**Comment by cescoffier** [comment]
@phillip-kruger ok, that's what I got. It is a change in behavior that I would consider to be a breaking change (aka need to be documented).

**Comment by phillip-kruger** [comment]
Why is this build failing :(

**Comment by phillip-kruger** [comment]
@maxandersen @cescoffier I fixed the issues in the CI Build, please can you have a look. If you are happy as is we can maybe merge and then improve going forward ?

**Comment by phillip-kruger** [comment]
We have a chicken egg problem here... I need to spend some more time on this. Please ignore PR for now, I'll ping you when ready

**Comment by ia3andy** [comment]
For the data I get from the codestarts, now that this has moved, we should move this info to the extension descriptors and provide a way for the dev-ui to access it:
Example:
from here: https://github.com/quarkusio/quarkus/blob/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/funqy-http-codestart/codestart.yml#L6-L9
to here: https://github.com/quarkusio/quarkus/blob/main/extensions/funqy/funqy-http/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L12

 @phillip-kruger do you already have access to this descriptor data from the dev ui?

**Comment by phillip-kruger** [comment]
Yes I have, but I don't think all extensions is up to date w.r.t those entries.

**Comment by ia3andy** [comment]
> I don't think it makes sense to have this info in the extension descriptor available at runtime. its a devtime possiblye buildtime only thing.

I am not sure what you mean/imply?

**Comment by maxandersen** [comment]
@ia3andy we shouldn't add wall of text into extensions.yaml that is part of runtime artifact that is only relevent for codestarts/dev page.

**Comment by ia3andy** [comment]
> @ia3andy we shouldn't add wall of text into extensions.yaml that is part of runtime artifact that is only relevent for codestarts/dev page.

Yeah you are right, I think this info which was provided through codestarts (as it was used there) should now be added to the dev-ui setup of the extension (some way)

**Comment by phillip-kruger** [comment]
OK, so here the issue I am having.

I am making the vertx route that server this welcome page (on naked path /) the last in the queue (Integer.Max) so if a user has:

- Their own static `index.html` in META-INF/resources that should be served
- Their own Vertx route on `/`, that should be served
- Their own REST endpoint on `/`, that should be served

However, adding REST (without a `/` path) cause the NotFound to kick in when `/` is requested, and it never goes to the next handler. 

I can:

- Use the `ResumeOn404BuildItem` to let the 404 page not render. However, then there is no more 404 page for real 404s
- Do some checks in the 404 handler to go to the next handler if this is `/`. (I could not get this to work, but it should be possible)
- Change the priority of the welcome page to be before REST and in there somehow check if there is a `/` path, and go to the next handler if there is one.

But then I started thinking about the 404 page. Probably the right solution is that the 404 should also be handled separately in vertx (maybe same as the welcome page) by Dev UI. At the moment it's handled by RESTEasy Reactive or Classic or Reactive Routes. This change will mean that those 3 will let vertx go to the next handler until we end up at the welcome / not found one (except if the user handles it) 

This feels like the right way to go ? Any other suggestions ? This is a bit more work and will delay this PR.

/cc @cescoffier @maxandersen

**Comment by phillip-kruger** [comment]
Cool. i'll start that work next year and update this PR then, for now I am taking a break :)

**Review by maxandersen — COMMENTED** [review]
At first I was a bit puzzled with the amount of files that needed changes to get 404 page to be dynamic but now grokking this PR is unifying a lot of 404 page handling and add devui page which adds up the changed files.

I'm thus far +1 on it but best if @cescoffier or @stuartwdouglas could give it a review for technical routing correctness.

**Comment by phillip-kruger** [comment]
@cescoffier - the management is now also working. The link was omitted in the NotFoundPage (in the current version). I have now added them, and also added a Not Found Page for the management interface. So now if you enable management, and go to 0.0.0.0:9000/asdasdasd that will show the Not Found page, with the links correctly added

**Comment by geoand** [comment]
> In the current version, if you have a JAX-RS Filter, that filter will run, even in the case that the requested resource was not a REST resource (in my opinion, that is wrong). This will not happen anymore

This is indeed the correct behavior!

**Comment by geoand** [comment]
The CI failures seem related to the change

**Comment by phillip-kruger** [comment]
CI failures was related to remote-dev. I have fixed it (I think) . Let see what CI does now :)

**Comment by geoand** [comment]
🤞

**Comment by phillip-kruger** [comment]
We have a green CI !!! @gsmet this will probably conflict with the big rename. Do you want me to wait and I rename once the rename is in ?

**Comment by geoand** [comment]
The Big Rename for REST is already in.

**Comment by phillip-kruger** [comment]
Yes, I rebased this pr on that, had a few conflicts to resolve.

**Review by cescoffier — APPROVED** [review]
Let's get this one in, we can always improve later.

**Comment by maxandersen** [comment]
good stuff @phillip-kruger was about to comment same as clement: get it in an iterate.

what will be important is that we document how this works/breaks(?) when trying to add/update content.

One thing - i didn't check - does codestart generate with or without index.html in place?

**Comment by phillip-kruger** [comment]
It should now generate without the index.html

**Comment by maxandersen** [comment]
cool - and it still puts index.html when generating for 3.8 and older?

**Comment by phillip-kruger** [comment]
Yes

**Pull request merged**
