### PR TITLE
SmallRye GraphQL 1.2.8 and client configuration fixes

### LINKED ISSUE #18457: Multiple issues with SmallRye GraphQL Client
The quickstart for SmallRye GraphQL Client doesn't work anymore.

There are multiple issues.

## Config

The config that was used looks like it's not supported anymore as I get:

```
Caused by: java.util.NoSuchElementException: SRGQLDC035001: URL not configured for client named 'star-wars-dynamic'. Please define the property smallrye.graphql.client.CLIENT_NAME/url
```

I tried to follow this advice but it didn't work so the advice is wrong or something is broken.

I was able to get it to work by using the Quarkus way (following what @jmartisk did in his config overhaul PR). See the PR here: https://github.com/quarkusio/quarkus-quickstarts/pull/897 .

In a perfect world, that would be the syntax recommended by the error message (but given the error is triggered by SmallRye GraphQL Client, it might be a bit tricky).

## Native not working

I then tried to compile to native and got:

```
2021-07-06 17:20:27,924 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NullPointerException
	at io.smallrye.graphql.client.GraphQLClientsConfiguration.initialize(GraphQLClientsConfiguration.java:49)
	at io.smallrye.graphql.client.GraphQLClientsConfiguration_Bean.create(GraphQLClientsConfiguration_Bean.zig:144)
	at io.smallrye.graphql.client.GraphQLClientsConfiguration_Bean.create(GraphQLClientsConfiguration_Bean.zig:160)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
```

Do we really test native properly in the main repo?

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes https://github.com/quarkusio/quarkus/issues/18457

### CODE REVIEW

**Comment by gsmet** [comment]
@jmartisk for my understanding, how does it fix the native issue?

**Comment by jmartisk** [comment]
I'm just finding out I don't know that either. Hold on, might still need some adjustments

**Comment by jmartisk** [comment]
Ok so in the end the previous fix was good, but I've improved the integration tests to be sure.

The first problem was caused by a bad regular expression that did not expect that a configured client name can contain dashes. Now it should accept dashes, numbers and underscores in addition to the English alphabet.

The second problem (with native mode) is because we were depending on TCCL as a key for storing the client configuration map in a static map (this is to be able to support app servers with potentially multiple applications). But in native mode, this becomes a problem because at build-time, the class loader is different than the one at runtime. I changed that so that in Quarkus, we assume there is only one application, so no need to distinguish using the TCCL. The reason why native mode tests in quarkus core didn't catch this is that there was a fallback - if the configuration-storing bean is broken or inaccessible, we just ignored it. And that worked in the integration-tests module, because there was no client configuration in `application.properties` (I now added a test that actually needs some config from there to be able to pass properly).

Generally I had to rework the integration tests quite a bit, because now that the client depends more heavily on CDI (in most cases it's necessary), we hit the problem that CDI does not work in native mode tests on the "client" side (from the `@Test` method). So I changed the tests in the way that the `@Test` method calls a REST endpoint, which then performs all the GraphQL-client-related work - CDI is available then.

I also fixed one minor problem where the client's `url` was considered required by Quarkus, but it should not - it should be possible to define the URL dynamically using the client builder.

**Comment by jmartisk** [comment]
A pair of eyes to try the quickstart with this change would be welcome. I tested it, but, you know...

**Review by phillip-kruger — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
Hmmm, I don't know if it's normal but before if the URL was not configured, I had a nice (but misleading as reported) error message.

Now I get:
```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at org.jboss.resteasy.reactive.client.impl.ClientImpl.target(ClientImpl.java:150)
	at io.smallrye.graphql.client.typesafe.jaxrs.JaxRsTypesafeGraphQLClientBuilder.build(JaxRsTypesafeGraphQLClientBuilder.java:81)
	at io.quarkus.smallrye.graphql.client.runtime.SmallRyeGraphQLClientRecorder.lambda$typesafeClientSupplier$0(SmallRyeGraphQLClientRecorder.java:20)
```

I don't think this is an improvement :).

To reproduce, just comment the first URL in the quickstart `application.properties`.

**Comment by jmartisk** [comment]
Hey, in the first case you were referring to the dynamic client, this example is for a typesafe client. Yeah, they behave a bit differently, which is probably also bad. 
I filed https://github.com/smallrye/smallrye-graphql/issues/903 to unify and improve, but it will need a new SmallRye release.

**Comment by gsmet** [comment]
@jmartisk OK so I also commented the other one and I get:
```
SRGQLDC035001: URL not configured for client named 'star-wars-dynamic'. Please define the property smallrye.graphql.client.CLIENT_NAME/url
```

and if I define:
```
smallrye.graphql.client.star-wars-dynamic/url=https://swapi-graphql.netlify.app/.netlify/functions/index
```
as recommended by the message, I still get the error as I initially reported it.

Did I miss something?

**Comment by jmartisk** [comment]
Oh fuck me, I realize the error message is wrong. It should be `CLIENT_NAME/mp-graphql/url`, not `smallrye.graphql.client.CLIENT_NAME/url` (I changed that at one point in the implementation but forgot to correspondingly update the error message). Thanks for noticing. Will fix that within https://github.com/smallrye/smallrye-graphql/issues/903

**Comment by gsmet** [comment]
@jmartisk and in an ideal world, it would be even cooler if we could recommend the Quarkus version of the property :).

**Review by gsmet — APPROVED** [review]
OK, let's merge this, it fixes the native issue, which is good. I'll let @jmartisk iterate on the rest of the issues.

**Pull request merged**
