### PR TITLE
Bump dekorate version to 2.11

### PR DESCRIPTION
**Pull request by Sgitario**
Updates:
- Changed helm expressions format to avoid using jsonpaths
- New certmanager extension (necessary for a upcoming Quarkus extension: https://github.com/quarkusio/quarkus/issues/25874
- Other inner changes like route/ingress configuration

### CODE REVIEW

**Comment by gsmet** [comment]
@Sgitario please avoid merge commits in PRs, do a proper rebase. Otherwise it's a nightmare when we try to backport things. Thanks!
(I did the rebase)

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by Sgitario** [comment]
I don't think the failures are related to the PR's changes :/

**Comment by iocanel** [comment]
> I don't think the failures are related to the PR's changes :/

Agree! From what I see there are quite a few PRs ATM failing on these particular tests. @geoand @gsmet: How do we handle this? Merge or hold our horses till the issue is fixed on main?

**Comment by geoand** [comment]
Let's rerun the failing job just to be on the safe side

**Comment by geoand** [comment]
Not sure what's going on with that test... It should not fail. Can you rebase on `main` please?

**Comment by Sgitario** [comment]
> Not sure what's going on with that test... It should not fail. Can you rebase on `main` please?

Done

**Comment by Sgitario** [comment]
There are other pull requests with the same failures. Example: https://github.com/quarkusio/quarkus/pull/26414#user-content-test-failures-job-7101599087

I expect having my Windows machine back during the next week, so I could investigate these failures further after then.

**Comment by gsmet** [comment]
@geoand it wasn't until a few days ago. It only fails on Windows AFAICS. And the failure is pretty consistent.

**Comment by geoand** [comment]
Very weird for that particular test to fail...

**Comment by aloubyansky** [comment]
Yes, I noticed that recently too. Was going to look into it.

Is this OK for the operator SDK, btw? @metacosm

**Pull request merged**
