### PR TITLE
Bump to Vert.x 4.3.2 and smallrye mutiny bindings 2.24.0

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by cescoffier** [comment]
Ok, I missed that commit:
https://github.com/vert-x3/vertx-web/commit/ce19bbf4aed78295b7622ad0e2a3f190235bdab6

This is very annoying as it breaks lots of extensions. 

\CC @vietj

**Comment by cescoffier** [comment]
looking at that commit, we would need a new release of vert.x with a rollback, but the blast radius is very large.

**Comment by cescoffier** [comment]
@Sanne any idea about these _classic_ Hibernate tests failing with the Vert.x update?

**Comment by cescoffier** [comment]
hum... actually... I may know...

**Review by gsmet — APPROVED** [review]

**Comment by Sanne** [comment]
Related:
 - https://github.com/hibernate/hibernate-reactive/pull/1357

**Pull request merged**
