### PR TITLE
Replace @michalszynkiewicz in the quarkus-github-bot.yml

### PR DESCRIPTION
**Pull request by cescoffier**
I hope one day we will be able to revert that commit 🤞. Until that 😔.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
Noooooooooooo. If we don't approve the PR, he stays with us?

**Comment by gastaldi** [comment]
Should https://github.com/quarkusio/quarkus/blob/main/MAINTAINERS.adoc be updated too?

**Comment by cescoffier** [comment]
Good point @gastaldi. That doc seems to contain extensions we moved to quarkiverse too. It is expected?

**Comment by gastaldi** [comment]
> Good point @gastaldi. That doc seems to contain extensions we moved to quarkiverse too. It is expected?

I think they are still here because of relocations. But I'm +1 in removing that

**Comment by gsmet** [comment]
We can probably clean them up, yes.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by cescoffier** [comment]
I've removed Michal from the MAINTAINERS.adoc. I didn't do the cleanup. There are many extensions missing (like resteasy reactive).

**Pull request merged**
