### PR TITLE
Prevent transfer-encoding header when using server-sent-eventsCloses …

### LINKED ISSUE #7094: SSE endpoint has incorrect value for Transfer-Encoding header
**Describe the bug**
JAX-RS resource which is producing server-sent-events has a spurious ```Transfer-Encoding ``` response header

**Expected behavior**
No Transfer-Encoding response header or header value of ```identity```

**Actual behavior**
Response header set as ```transfer-encoding: chunked``` even though the response body is not chunked endcoded 

```
curl -v http://localhost:8080/hello/stream
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /hello/stream HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< transfer-encoding: chunked
< Content-Type: text/event-stream
< 


data: hello 0
```

**To Reproduce**
1. ```mvn quarkus:dev``` attached code
2. ```curl -v http://localhost:8080/hello/stream```

**Environment (please complete the following information):**
 - Output of `uname -a`: ```Darwin McBookAir 17.7.0 Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64 x86_64```
 - Output of `java -version`: ```openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)```
 - Quarkus version: ```1.2.0.Final```

**Additional context**
Example code to reproduce:
```java

@Path("/hello")
public class ExampleResource {
  @GET
  @Path("stream")
  @Produces("text/event-stream")
  public void streamHello(@Context SseEventSink sseEventSink, @Context Sse sse) {
    for (int i = 0; i < 100; ++i) {
        sseEventSink.send(sse.newEvent("hello "+i));
    }
  }
}
```

### PR DESCRIPTION
**Pull request by chonton**
Closes #7094

### CODE REVIEW

**Comment by gsmet** [comment]
There are test failures:
```
[ERROR] testJsonAsync  Time elapsed: 0.016 s  <<< ERROR!
35965
java.lang.IllegalStateException: 
35966
Expected response body to be verified as JSON, HTML or XML but no content-type was defined in the response.
35967
Try registering a default parser using:
35968
   RestAssured.defaultParser(<parser type>);
35969
Content was:
35970

35971

35972
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
35973
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
35974
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
35975
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
35976
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
35977
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
35978
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
35979
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
35980
	at io.restassured.assertion.StreamVerifier.newAssertion(StreamVerifier.groovy:43)
35981
	at io.restassured.assertion.StreamVerifier$newAssertion.call(Unknown Source)
35982
	at io.restassured.assertion.BodyMatcher.validate(BodyMatcher.groovy:85)
35983
	at io.restassured.assertion.BodyMatcher$validate$0.call(Unknown Source)
35984
	at io.restassured.assertion.BodyMatcherGroup$_validate_closure2.doCall(BodyMatcherGroup.groovy:47)
```

**Comment by chonton** [comment]
Hmm.  All tests successful on Mac with OpenJDK 11.0.2.  Is it possible to restart the CI tests?

**Comment by stuartwdouglas** [comment]
It seems suspicious that this is not being chunked even though the header is set. I think we need to do some more investigation here.

**Comment by stuartwdouglas** [comment]
The content is being chunked correctly, curl just does not show chunk markers in the -v output.

I think we are better off leaving this as chunked for now.

**Comment by chonton** [comment]
Great! Thanks for investigating. My apologies for the distraction.  Keep up the great work!

**Pull request closed without merging**
