### PR TITLE
Don't warn when QuarkusTestResourceLifecycleManager can't find field

### LINKED ISSUE #21577: Getting lots of "Unable to determine matching fields for injection of test instance" messages
### Describe the bug

This isn't specific to using Wiremock, but more generically if you are building a `QuarkusTestResourceLifecycleManager` while also overriding the `inject` method. In my example I am using wiremock and created a custom `@InjectWireMock` annotation.

```java
@Target({ METHOD, CONSTRUCTOR, FIELD })
@Retention(RUNTIME)
@Documented
public @interface InjectWireMock {
}
```

My `QuarkusTestResourceLifecycleManager` class looks like this:

```java
public class HeroesVillainsWiremockServer implements QuarkusTestResourceLifecycleManager {
	private final WireMockServer wireMockServer = new WireMockServer(wireMockConfig().dynamicPort());

	@Override
	public Map<String, String> start() {
		this.wireMockServer.start();

		return Map.of(
			"quarkus.rest-client.hero-client.url", this.wireMockServer.baseUrl(),
			"fight.villain.client-base-url", this.wireMockServer.baseUrl()
		);
	}

	@Override
	public void stop() {
		this.wireMockServer.stop();
	}

	@Override
	public void inject(TestInjector testInjector) {
		testInjector.injectIntoFields(
			this.wireMockServer,
			new AnnotatedAndMatchesType(InjectWireMock.class, WireMockServer.class)
		);
	}
}
```

I have some tests which do `@QuarkusTestResource(HeroesVillainsWiremockServer.class)`. Those tests also have

```java
@InjectWireMock
WireMockServer server;
```

and then do something with the server during the tests.

There are also other tests which do not interact with the server at all and therefore do not inject the server as a field in the test class. In those cases, the log output from the test contains lots and lots of `Unable to determine matching fields for injection of test instance` messages.

I can add the field to my test class (even though it is never used) and the messages go away.

### Expected behavior

I don't expect to see that log message in tests where I am not using the test resource.

### Actual behavior

Lots & lots of `Unable to determine matching fields for injection of test instance` messages

### How to Reproduce?

Reproducer:
[matching-fields-for-injection.zip](https://github.com/quarkusio/quarkus/files/7571613/matching-fields-for-injection.zip)

When you run `./mvnw clean verify`, you'll see that the message is printed out once for each test method in `ExampleResourceTest`. 

### Output of `uname -a` or `ver`

`Darwin edeandre-mac 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`

### Output of `java -version`

```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### GraalVM version (if different from Java)

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)
```

### Quarkus version or git rev

`2.4.2.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/edeandre/.sdkman/candidates/java/11.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #21577

### CODE REVIEW

**Review by famod — APPROVED** [review]
:+1:

I'm adding the backport label for 2.5.1.Final.

**Comment by geoand** [comment]
Good idea!

**Review by edeandrea — COMMENTED** [review]
Maybe do a `log.debug` or `log.info`? Maybe the user wants to see it, maybe they don't? Leave the choice to the user rather than completely eliminate it?

**Comment by geoand** [comment]
Logging doesn't work in this setting unfortunately

**Pull request merged**
