### PR TITLE
Support for generating ServiceBinding CR

### PR DESCRIPTION
**Pull request by iocanel**
The pull request introduces support for generation `ServiceBinding` CR.

At the moment the generation of the `ServiceBinding` is 100% configuration based, as at the moment there are no identifiable services that support the Service Binding Operator.

### CODE REVIEW

**Comment by geoand** [comment]
Glad to see it!

Can we also have some docs for this?

**Comment by geoand** [comment]
I will take a closer look this weekend or Monday morning

**Comment by iocanel** [comment]
@geoand: Feedback applied, Once the review is done, I'll squash and push.

**Review by geoand — COMMENTED** [review]
LGTM , just added some minor comments!

**Review by geoand — APPROVED** [review]

**Comment by iocanel** [comment]
I didn't

**Comment by geoand** [comment]
Gotta love git black magic :)

**Comment by geoand** [comment]
The `OpenshiftWithServiceBindingTest` failure seems genuine

**Comment by iocanel** [comment]
> The `OpenshiftWithServiceBindingTest` failure seems genuine

It seems that there was a bug only manifesting on jdk17.

**Comment by geoand** [comment]
Now the PR needs a formatting change

**Pull request merged**
