### PR TITLE
Improve Config CLI

### LINKED ISSUE #41131: CLI - Config command - missing help text and unexpedted error stacktraces
### Describe the bug

CLI command for Config has missing help text and help for sub-commands throws stacktrace
CLI command for Config was introduced in 3.9 - https://quarkus.io/blog/quarkus-3-9-1-released/#cli-command-for-config

CC @radcortez as you worked on https://github.com/quarkusio/quarkus/pull/34493

```
quarkus -version
3.11.1
```
`set` has no description:
```
quarkus --help
...
  config                  Manage Quarkus configuration
    set
    encrypt, enc          Encrypt Secrets using AES/GCM/NoPadding algorithm by
                            default
...
```
Help goes directly to `set` sub-command and complains about missing parameter when I just want help text:
```
quarkus config --help
[ERROR] ❗  Missing required option: '--name=<name>'

Usage: quarkus config set [-ek] [--verbose] [-a=<value>] -n=<name>

See 'quarkus config set --help' for more information.
```

Error when wanting help for `enc` sub-command:
```
quarkus config enc --help
2024-06-11 21:45:14,200 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): picocli.CommandLine$MissingParameterException: Missing required option: '--secret=<secret>'
	at picocli.CommandLine$MissingParameterException.create(CommandLine.java:18673)
	at picocli.CommandLine$MissingParameterException.access$21200(CommandLine.java:18661)
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13657)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13620)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13915)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13811)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13597)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13915)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13811)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13597)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13565)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13460)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at io.quarkus.cli.QuarkusCli.checkMissingCommand(QuarkusCli.java:165)
	at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:109)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.cli.Main.main(Main.java:9)
```

Error when wanting help for `set` sub-command:
```
quarkus config set --help
2024-06-11 21:45:27,514 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): picocli.CommandLine$MissingParameterException: Missing required option: '--name=<name>'
	at picocli.CommandLine$MissingParameterException.create(CommandLine.java:18673)
	at picocli.CommandLine$MissingParameterException.access$21200(CommandLine.java:18661)
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13657)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13620)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13915)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13811)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13597)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13915)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13811)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13597)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13565)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13460)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at io.quarkus.cli.QuarkusCli.checkMissingCommand(QuarkusCli.java:165)
	at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:109)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.cli.Main.main(Main.java:9)
```

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

3.11.1

### PR DESCRIPTION
**Pull request by radcortez**
Fixes #41131

- Properly add help flags
- Moved required options to parameters
- Add a `remove` command

### CODE REVIEW

**Comment by gsmet** [comment]
Ah cool, I tried it the other day and it was a bit hard to use. I'll have a look soon.

**Comment by radcortez** [comment]
Should be easier now :)

**Comment by gsmet** [comment]
I'm having a look at it now.

**Review by gsmet — COMMENTED** [review]
I played with it a bit and here is my feedback.
Not saying everything should be fixed before we merged this PR but I'd like to have your feedback on my comments.

1. I think `quarkus config` should display the help rather than defaulting to `set`. For me this is too important to push a random default.
2. I think the feedback should be consistent with the feedback we have when adding an extension for instance.

We have:

Screenshot from 2024-06-27 14-22-24

In general, we should try to be consistent on the feedback side.

3. When typing `quarkus config enc`, I end up with an error instead of the help being displaying (this is the case in `main` but also in this branch). I created https://github.com/quarkusio/quarkus/issues/41513 because even if you can tweak it here, I think it's something that is not ideal in our Picocli extension.

4. I'm not sure of why I have to pass the secret with `--secret` in `quarkus config enc --secret=secret`, for the rest you pass the parameters as is (or at least that's what I did and it worked).
Also I have no idea what to do with the output:
```
Encrypted Secret: DBLLBaf7o_i3u8lmJBb0rKJT13xvBXoQYjVFWFCJACl_tGU
Encryption Key: S6i5aNG6ySALS6021eMKbg
```
We probably need to explain what to do with it?

**Comment by radcortez** [comment]
> 1. I think `quarkus config` should display the help rather than defaulting to `set`. For me this is too important to push a random default.

OK

> 2. I think the feedback should be consistent with the feedback we have when adding an extension for instance.

> In general, we should try to be consistent on the feedback side.

OK

> 3. When typing `quarkus config enc`, I end up with an error instead of the help being displaying (this is the case in `main` but also in this branch). I created [Picocli - Some expected errors lead to a stacktrace and they shouldn't #41513](https://github.com/quarkusio/quarkus/issues/41513) because even if you can tweak it here, I think it's something that is not ideal in our Picocli extension.

Yes, this is an issue with our extension rather than the CLI commands. When I looked into other examples, we also got the same error (for instance, `quarkus extension add` without any parameter also ends up with a stacktrace). I then forgot to open an issue about it. Thanks for opening one. It seems this happens only with subcommands.

> 4. I'm not sure of why I have to pass the secret with `--secret` in `quarkus config enc --secret=secret`, for the rest you pass the parameters as is (or at least that's what I did and it worked).

Strange. It shouldn't be that way anymore. The previous version did have a `--secret` option but I've changed that to be a parameter.

>    Also I have no idea what to do with the output:
> 
> ```
> Encrypted Secret: DBLLBaf7o_i3u8lmJBb0rKJT13xvBXoQYjVFWFCJACl_tGU
> Encryption Key: S6i5aNG6ySALS6021eMKbg
> ```
> 
> We probably need to explain what to do with it?

OK

**Comment by radcortez** [comment]
This is how it is looking now:

Screenshot 2024-06-28 at 12 47 32

**Comment by gsmet** [comment]
Love it!

**Review by gsmet — APPROVED** [review]

**Comment by michalvavrik** [comment]
Some changes here (Moved required options to parameters: SECRET, NAME, VALUE) are not backwards compatible, but I can't find it documented in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.13 and this PR does not have a breaking-change label. Can you improve this, please?

**Comment by radcortez** [comment]
Hey @michalvavrik sorry for the inconvenience. 

We made the changes to fix some of the raised issues, plus make it consistent with other Quarkus CLI commands. I'll add that information now.

**Comment by michalvavrik** [comment]
> Hey @michalvavrik sorry for the inconvenience.
> 
> We made the changes to fix some of the raised issues, plus make it consistent with other Quarkus CLI commands. I'll add that information now.

np, but good to have it documented, thanks

**Comment by radcortez** [comment]
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.13#quarkus-cli

**Pull request merged**
