### PR TITLE
Support OffsetDateTime serialization in REST Client multipart bodies

### LINKED ISSUE #31320: RESTEasy Reactive doesn't support `java.time.OffsetDateTime`
### Describe the bug

This is similar to https://github.com/quarkusio/quarkus/issues/31298, but for `java.time.OffsetDateTime`.
I have a PR ready.

### Expected behavior

`OffsetDateTime` attribute should be serialized to String.

### Actual behavior

A serializer can't be found.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hbelmiro**
Fixes: https://github.com/quarkusio/quarkus/issues/31320

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

I think we would need to support more of the Java time/date types

**Comment by hbelmiro** [comment]
Yes, makes sense. Maybe the reactive extension should support the same types as the classic does. That way users wouldn't face these issues when migrating to reactive.

**Comment by geoand** [comment]
Right. I'll look into it

**Comment by geoand** [comment]
I had a first look at this and in order to do it properly we would need to support `@org.jboss.resteasy.reactive.DateFormat`. 
But that in turns requires some additional changes I do not have time to make now. 
So this will likely have to wait a few weeks.

**Comment by gsmet** [comment]
@geoand what should we do with this one?

**Comment by geoand** [comment]
I think it should be closed

**Pull request closed without merging**
