### PR TITLE
Update codeblock to 1.0.13

### LINKED ISSUE #40123: Quarkus Dev UI - Calling gRPC endpoint is not working
### Describe the bug

I am seeing some JS errors when trying to use the Quarkus Dev UI (on Quarkus 3.9.3) to query a sample gRPC endpoint:

Screenshot 2024-04-17 at 11 49 55 AM

### Expected behavior

- successful gRPC responses are displayed in the UI
- gRPC responses with a non-OK gRPC status code are displayed in the UI

### Actual behavior

Seeing JS exceptions in Chrome

### How to Reproduce?

Reproducer: https://github.com/darrenclark/reproduce-quarkus-grpc-dev-ui-issue

1. Clone the above repo
2. Run `quarkus dev`
3. Open dev UI -> navigate Extensions -> gRPC -> Services
4. Open Chrome console
5. Try to query one of the gRPC APIs, error will popup in Chrome console.

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
fix #40123

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by gastaldi** [comment]
Should this be backported?

**Comment by phillip-kruger** [comment]
Yes, sorry forgot to add the label

**Comment by gastaldi** [comment]
@phillip-kruger how about backporting to 3.8 LTS too? Or is this something post-3.9 only?

**Comment by phillip-kruger** [comment]
I'll have to go check.

**Comment by phillip-kruger** [comment]
It broke with this PR https://github.com/quarkusio/quarkus/pull/38848, that was included in 3.9, so everything pre 3.9 is fine

**Pull request merged**
