### PR TITLE
Introduce BansRuntimeDependency for extensions/*

### LINKED ISSUE #11174: Enforce the rule "don't use runtime dependencies in deployment artifacts"
**Description**
See #11169.

**Implementation ideas**
As mentioned in https://github.com/quarkusio/quarkus/pull/11169#issuecomment-668170987, the idea is to introduce a Maven a custom enforcer rule which enforces that there are no runtime deps of other extensions in deployment artifacts.

### PR DESCRIPTION
**Pull request by famod**
Resolves #11174 (and should prevent such tedious tasks as #12205)

- refactor RequiresMinimalDeploymentDependency for common base class
- extend invoker smoketest (now with 3 executions)
- disable invoker tests for -Dquickly
- activate new rule for all extensions in extensions-parent
- change parent of all extensions from build-parent to extensions-parent
- fix found rule violations

/cc @gsmet @aloubyansky @gastaldi

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM. Let's wait for others to review before we merge this. Great job @famod !

**Comment by geoand** [comment]
Very very cool!

**Comment by geoand** [comment]
One issue I see is that once we merge this, we will need to alert the community as their extensions could potentially break

**Comment by famod** [comment]
@geoand I am missing some details about that.
How are those enforcer rules integrated into community extensions?

**Comment by geoand** [comment]
I guess I am the one that spoke too soon 😂.

I thought that this contained a change in Quarkus bootstrap that would cause a failure is the extension was not properly configured.
However that's obviously not the case, so no issue 😎

**Comment by famod** [comment]
@geoand no problem!
I mean there is a `distributionManagement` in `enforcer-rules`, so usage outside of the main repo *might* come sooner or later.

**Review by aloubyansky — APPROVED** [review]
Great work @famod Thanks!

**Pull request merged**
