### PR TITLE
Don't execute blocking security code serially as it limits concurrent blocking execution to number of the event loops

### LINKED ISSUE #43217: Calling blocking code from SecurityIdentityAugmentor causes concurrent requests to be limited by the number of event loop threads
### Describe the bug

Hi,

we have an application calling some blocking code from a `SecurityIdentityAugmentor` (using `authenticationRequestContext.runBlocking`); under some circumstances, this code may take longer than expected and when this happens we've noticed that requests seemed to be queued. After some investigation we found out that the application can't handle more than N requests where N = number of event loop threads... but, since the blocking tasks run in a worker thread, I was expecting the application to handle up to M requests, where M = number of worker threads. 

For example, say the event loop has 2 threads and the blocking task takes 5s: if three users perform a request at the same time, two requests will take 5s and one will take 10s because it won't be processed until the first two complete. However, if an unauthenticated request (i.e. blocking task is not run) is performed while some blocking tasks are running, it's served immediately which shows that the event loop threads are not busy.

You can find a reproducer here: https://github.com/lorenzobenvenuti/security-augmentor-blocking-issue

Thanks,

lorenzo

### Expected behavior

Number of concurrent requests is limited by the number of worker threads

### Actual behavior

Number of concurrent requests is limited by the number of event loop threads

### How to Reproduce?

https://github.com/lorenzobenvenuti/security-augmentor-blocking-issue

### Output of `uname -a` or `ver`

Linux  6.10.6-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:35:32 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.12" 2024-07-16 OpenJDK Runtime Environment (Red_Hat-17.0.12.0.7-2) (build 17.0.12+7) OpenJDK 64-Bit Server VM (Red_Hat-17.0.12.0.7-2) (build 17.0.12+7, mixed mode, sharing)

### Quarkus version or git rev

3.14.2 (also tested with 3.8 which is the one used by our app)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (Red Hat 3.9.1-3)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- Closes: https://github.com/quarkusio/quarkus/issues/43217

### CODE REVIEW

**Comment by michalvavrik** [comment]
@cescoffier I've added backports label, I take it this was always the case (and we have a test). But if you want to be more conservative, wait or you can see an issue, please drop the labels. Thank you

re backport also cc @sberyozkin @gsmet, please adjust backport labels according to your liking

**Comment by sberyozkin** [comment]
Thanks very much @michalvavrik, not sure how critical it is for 3.8, as it is only suboptimal with the ordered option for the blocking augmentors, I'll let Guillaume decide

**Review by sberyozkin — APPROVED** [review]
LGTM, but indeed, it requires an approval from Clement

**Review by cescoffier — APPROVED** [review]

**Comment by michalvavrik** [comment]
I'll add 3.8 label after all as user that report this would appreciate it: https://github.com/quarkusio/quarkus/issues/43217#issuecomment-2348434087

I think it is right change, though I am very much relying on provided information about Vert.x here. I would be more certain if it was change only regarding Quarkus code.

**Pull request merged**
