### PR TITLE
Revert "Simplify runtime class transformation"

### PR DESCRIPTION
**Pull request by gsmet**
PLEASE DO NOT MERGE YET. I want CI to run on it but @aloubyansky might come with a proper fix before the release.

This is a reminder so that I do not forget to revert it in case we don't have a better option.

This reverts commit 18f1ca2792940386cc50b0efa70c15c25d307505.

/cc @geoand @aloubyansky @Postremus

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by aloubyansky — APPROVED** [review]
I'm approving it. I'll probably take the time to look into another regression instead right now.

**Comment by aloubyansky** [comment]
Maybe we shouldn't revert it in master though? Creating an issue instead?

**Comment by gsmet** [comment]
We already have an issue. I prefer doing it in both branches because if we don't have time to fix it by 1.7, I wouldn't want it to resurface. It's easy enough to re-revert it.

**Review by Postremus — APPROVED** [review]

**Pull request merged**
