### PR TITLE
Use followOutput for lra-coordinator container

### LINKED ISSUE #39390: Log lra-coordinator output during microprofile-lra tck tests
### Description

Logging lra-coordinator container output during microprofile-lra tck tests would help to better understand the behaviour of the coordinator and would help developers to debug tck tests issues when they occur. 

### Implementation ideas

I would propose to log the output using the followOutput method of the org.testcontainers.containers.GenericContainer class. See https://github.com/quarkusio/quarkus/pull/39104.

### PR DESCRIPTION
**Pull request by marcosgopen**
https://github.com/quarkusio/quarkus/issues/39390

Adding lra-coordinator container log in microprofile-lra tck tests logs.

### CODE REVIEW

**Comment by marcosgopen** [comment]
@mmusgrov

**Comment by mmusgrov** [comment]
I approve of the PR but I suspect that there needs to be an associated issue.

**Comment by mmusgrov** [comment]
@gsmet does @marcosgopen need a related issue in order to trigger a review?

**Review by mmusgrov — APPROVED** [review]
Good PR, we need these logs to be able to effectively debug issues with the LRA extension.

**Review by xstefank — COMMENTED** [review]
Is slf4j appropriate for this?

I don't know if we should use the logs here if it's not custom with anything else.

**Comment by mmusgrov** [comment]
> Is slf4j appropriate for this?

testcontainers relies on SLF4J for logging

> I don't know if we should use the logs here if it's not custom with anything else.

What do you mean by "use the logs" and what does "if it's not custom ..." mean?

**Comment by xstefank** [comment]
@mmusgrov @marcosgopen together with Marco we created an integration job in lra-coordinator-quarkus that'll also test the image which is the correct fix for this problem - https://github.com/jbosstm/lra-coordinator-quarkus/blob/main/.github/workflows/build.yml#L62-L99. This PR can be closed.

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
