### PR TITLE
Get correct map key for config maps of maps, with tests

### LINKED ISSUE #5982: Map config item with the map values gets the wrong keys
**Describe the bug**

With this config item:
```
/**
     * Configuration of the individual parsers.
     * For example:
     *
     * <pre>
     * quarkus.tika.parsers = pdf
     * quarkus.tika.parser-options.pdf.sort-by-position = true
     */
    @ConfigItem
    public Map<String, Map<String, String>> parserOptions;
```

the first segment following the name of the config item (`pdf`) is lost. 

Before the major config update I was seeing the map initialized as follows, given the above config fragment:

`pdf` (key):  `sort-by-position` = `true` (single entry map value, `sort-by-position` - key, `true` - value)

Now I'm seeing:

`sort-by-position` (key):  `sort-by-position` = `true` (single entry map value, `sort-by-position` - key, `true` - value)

so the `pdf` bit is lost.

(I think a similar issue may affect [this configuration](https://github.com/quarkusio/quarkus/blob/master/extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java#L164))

CC @dmlloyd

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #5982

### CODE REVIEW

**Comment by dmlloyd** [comment]
This PR includes the commit from #5989 for conflict reasons so it should stay in draft until that PR is merged.

**Comment by gsmet** [comment]
I tried to put this one on top of the PR I'm preparing and I have a test failure:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-keycloak-authorization: Failed to build a runnable JAR: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.keycloak.pep.deployment.KeycloakPolicyEnforcerBuildStep#requireBody threw an exception: java.lang.NullPointerException
[ERROR] 	at io.quarkus.keycloak.pep.deployment.KeycloakPolicyEnforcerBuildStep.isBodyClaimInformationPointDefined(KeycloakPolicyEnforcerBuildStep.java:47)
[ERROR] 	at io.quarkus.keycloak.pep.deployment.KeycloakPolicyEnforcerBuildStep.requireBody(KeycloakPolicyEnforcerBuildStep.java:30)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Comment by sberyozkin** [comment]
@gsmet I'm not sure I undertand what [line 47](https://github.com/quarkusio/quarkus/blob/master/extensions/keycloak-authorization/deployment/src/main/java/io/quarkus/keycloak/pep/deployment/KeycloakPolicyEnforcerBuildStep.java#L47) does, it looks like it expects a `key` be also a `key` in the values map.
Actually, this code was added as part of the [recent fix](https://github.com/quarkusio/quarkus/commit/5cef24b19c82069f2c9896258abf8f24cea2a507#diff-4bd6435c8acf7229ed83e3281739f41a), but it is likely was there just because it was the way the key was prepared as per this bug  #5982 :-)

**Comment by gsmet** [comment]
Yes, I agree this code looks suspicious and is probably buggy.

Could you come up with a fix?

**Comment by sberyozkin** [comment]
@gsmet Guillaume, can you please check what the value of that map is ? I don't know if it is possible to debug, may be add some temp log message...The fix should be trivial. I'll have to pick up the family...

**Comment by sberyozkin** [comment]
`entry.getValue().values().contains("request.body")` should be enough but not 100% sure :-)

**Comment by gsmet** [comment]
@sberyozkin I will have a look later tonight or tomorrow morning.

**Comment by gsmet** [comment]
I rebased on top of https://github.com/quarkusio/quarkus/pull/6005 and pushed a fix for Keycloak Authorization.

Let's see what CI think.

**Comment by sberyozkin** [comment]
@gsmet thanks :-)

**Comment by gsmet** [comment]
@dmlloyd I rebased on top of master but it seems the test you added doesn't pass:
```
Caused by: java.lang.NullPointerException
	at io.quarkus.extest.deployment.TestProcessor.checkMapMap(TestProcessor.java:464)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

Issue reported by CI before my last rebase and reproduced locally with the last rebase.

**Comment by gsmet** [comment]
@dmlloyd I pushed again my Keycloak Authorization fix on top of your commit.

**Comment by dmlloyd** [comment]
Ah, didn't mean to lose it. Pushed from my phone in bed :-)

**Comment by gsmet** [comment]
Looks like we still have the same issue:
```
Caused by: java.lang.NullPointerException
	at io.quarkus.extest.deployment.TestProcessor.checkMapMap(TestProcessor.java:464)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Comment by dmlloyd** [comment]
Looks like everything is OK now.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
