### PR TITLE
Remove deprecated Kubernetes/OpenShift properties

### PR DESCRIPTION
**Pull request by Sgitario**
This pull request removes the deprecated properties:
- `quarkus.kubernetes.expose` -> `quarkus.kubernetes.ingress.expose`
- `quarkus.openshift.expose` -> `quarkus.openshift.route.expose`
- `quarkus.kubernetes.host` -> `quarkus.kubernetes.ingress.host`
- `quarkus.openshift.host` -> `quarkus.openshift.route.host`
- `quarkus.kubernetes.group` -> `quarkus.kubernetes.part-of`
- `quarkus.openshift.group` -> `quarkus.openshift.part-of`

Plus, properties without the `quarkus.` prefix will be ignored. For example, before these changes we could add `kubernetes.name` and this property will be mapped to `quarkus.kubernetes.name`. After these changes, we're not going to do this any longer, to avoid issues like https://github.com/quarkusio/quarkus/issues/30850.

### CODE REVIEW

**Comment by Sgitario** [comment]
@geoand and @iocanel , what do you think if we remove the support of the mentioned deprecated properties in the description? I think that after 2 years when these properties were marked as deprecated, we can do it for 3.0.0.

**Comment by geoand** [comment]
👍🏼

**Review by geoand — APPROVED** [review]

**Review by iocanel — APPROVED** [review]
lgmt

**Comment by Sgitario** [comment]
Added https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#removed-deprecated-properties

**Pull request merged**
