### PR TITLE
Make native tests work with random port

### LINKED ISSUE #11891: Native Tests fail when quarkus.http.test-port is set to 0
**Describe the bug**

When running a native test with `quarkus.http.test-port=0` you get the following :

```
[INFO] Running org.acme.NativeExampleResourceIT
Executing target/code-with-quarkus-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=0, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:0
```

The runner is executed with `localhost:0` (instead of a random port). So it hangs, and then the test fails with:

```
Caused by: java.lang.RuntimeException: Unable to start native image in 60s
```

**Expected behavior**

The test should pass using a random port (like JVM mode tests).

**Actual behavior**

**To Reproduce**
1. Go to code.quarkus.io and generate a new project
2. `mvn verify -Pnative`  works
3. Add the property `quarkus.http.test-port=0`to the `application.properties` file
4. `mvn verify -Pnative`  FAILS

**Configuration**
```properties
quarkus.http.test-port=0
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin iMac-Pro-de-Antonio.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "11.0.6" 2020-01-14 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.7.1-FINAL
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3_1

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #11891

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]
This is definitely an improvement, but I wonder if we should also try and capture the https port if both are configured?

**Comment by geoand** [comment]
That's a good idea, but I think that we might want to do that in a follow up.

The main reason is that with RestAssured we aren't really making https calls anyway (we always use for `useSecureConnection` of `RestAssuredURLManager#setURL`), so it's probably if https is tackled in it's own issue.

**Comment by stuartwdouglas** [comment]
Good point, I fixed this in https://github.com/quarkusio/quarkus/pull/11629 before I went on PTO, but there was an issue so it was not merged.

**Comment by geoand** [comment]
Perhaps you want to "cherry-pick" the native launcher related change from that PR and open a new one?

**Comment by gsmet** [comment]
I'm leading towards not backporting this one for 1.7 except if at some point someone explicitly asks for it.

**Comment by geoand** [comment]
Okay.

This has been an issue for a while and we haven't had any complaints (other that the issue the PR was meant to address), so it's perfectly fine to hold off on this one for now

**Pull request merged**
