### PR TITLE
Upgrade to ANTLR 4.10.1 (for the ANTLR 4.x series)

### PR DESCRIPTION
**Pull request by Sanne**
This is in preparation of Hibernate ORM 6: we'll require this version, so might as well try to prepare for that, in case there's other projects that need to adapt.

N.B. versions v3 and v4 of ANTLR use a different package name, therefore this has no impact on users of ANTLR v3.x and previous.

### CODE REVIEW

**Comment by Sanne** [comment]
@evacchi | @mariofusco | @lucamolteni hi :)

Looks like I'm going to need your help. Apparently `org.kie:kie-dmn-core` is depending on `org.antlr:antlr4-runtime:jar:4.9.2:compile`, but the generated code by ANTLR checks that the runtime actually matches exactly the version used at runtime.

Could you all upgrade to `4.10` ? In my experience it's a drop-in replacement, and that would solve the problem. This would ve very useful to make progress with our experiments to migrate to Jakarta 10.

**Comment by evacchi** [comment]
fyi @tarilabs

**Comment by tarilabs** [comment]
hi @Sanne I might have limited ability to follow this through as I'm on PTO: Antlr4 is a bit delicate for DMN as it has some ties also with some GWT work, so I will be keeping 🤞  but worth giving it a shot, let's see what Jenkins says 🙃 

Tracked with https://issues.redhat.com/browse/DROOLS-7105 and derivatives.

/cc @baldimir @danielezonca

**Comment by Sanne** [comment]
we've merged a temporary workaround for Kogito in the quickstarts:
 - https://github.com/quarkusio/quarkus-quickstarts/commit/06864a195f0b2f5d8101d18d97265306aa3b3809

[Not opening an issue to get it cleaned up later as I'm sure we'll notice when Kogito will update]

With the quickstarts no longer breaking I think we can merge this - doing a last CI run.

**Comment by Sanne** [comment]
damn this one is going to be very annoying:
```
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:56)
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:48)
	at com.microsoft.sqlserver.jdbc.SQLServerLexer.<clinit>(SQLServerLexer.java:424)
```

**Review by gsmet — CHANGES_REQUESTED** [review]
> With the quickstarts no longer breaking I think we can merge this - doing a last CI run.

@Sanne I disagree we can merge it. We need a clear plan for Kogito to upgrade before doing so as the Platform will use only one version and we can't expect Platform consumers to have to override the version locally.

So:
- we need to make sure Kogito can upgrade
- define in which version we upgrade and coordinate the upgrades to make sure the Platform is consistent

You might already have a plan but if so let's make it clear in this PR.

**Comment by Sanne** [comment]
@gsmet sure I understand; my assumption is that the Kogito upgrade will be fairly simple, and it's going to be easier for them to test things if we do the change first - since it's a downstream project.

If it turns out it's a hell of a problem we can revert here; but it would be simpler to try to keep going so to identify other issues with it.

Already found a critical issue with the MSSQL JDBC driver so we might need to hold anyway. Wondering now why we didn't hit it in the ORM testsuite?! Seems related with native image's flow analsys, it seems the check is possibly in a code path not being triggered by the tests in Hibernate ORM.

**Comment by mariofusco** [comment]
@Sanne @gsmet @tarilabs I sent a [PR](https://github.com/kiegroup/drools/pull/4616) to bump Drools (and then also Kogito) to antlr 4.10. Let's see what happens, but i ran all dmn related tests locally and they seemed ok.

**Comment by gsmet** [comment]
> since it's a downstream project

Kogito Quarkus is a downstream project, not Kogito. Kogito is a different upstream. Thus why we need to coordinate and make sure we upgrade together.

Given the SQL Server issue, let's make sure we can upgrade before pulling the trigger for Kogito too.

**Comment by tarilabs** [comment]
FYI for as much as I can verify at present, on Drools DMN engine side we're ready to bump to Antlr 4.10 as you requested, ref this https://github.com/kiegroup/drools/pull/4614#issuecomment-1227070425 for the build errors in case let me know if I missed some CI-related considerations

**Comment by Sanne** [comment]
@tarilabs awesome, thanks!

@gsmet may I consider this un-stuck? I'll rebase...

**Comment by Sanne** [comment]
Rebased, and updated to `4.10.1` which came out in the meantime.

It seems runtime-compatible with `4.10` so I don't expect this would require strict alignment over 4.10 - however people on 4.9 still need to upgrade.

**Comment by Sanne** [comment]
Related:
 - https://github.com/hibernate/hibernate-orm/pull/5265

**Comment by knutwannheden** [comment]
Latest version is not 4.11.1. We are using PACT which in its most recent version [was regenerated with ANTLR 4.11.1](https://github.com/pact-foundation/pact-jvm/issues/1608). We will just stay on an older version for now.

**Comment by Sanne** [comment]
> Latest version is now 4.11.1. We are using PACT which in its most recent version [was regenerated with ANTLR 4.11.1](https://github.com/pact-foundation/pact-jvm/issues/1608). We will just stay on an older version for now.

Ouch, do you know if code built with 4.11 will be compatible at runtime with 4.10?

**Comment by holly-cummins** [comment]
I'm having fun with Pact and the Antlr upgrade too, @knutwannheden  - we raised https://github.com/pact-foundation/pact-jvm/issues/1615. It may be something a Pact Quarkus extension can fix, since Pact-Quarkus-Antlr seems to be a recurring compatibility issue (I spotted you raised https://github.com/pact-foundation/pact-jvm/issues/1380 a while ago). 

I've raised https://github.com/quarkiverse/quarkus-pact/issues/1 to track it for the extension.

**Comment by holly-cummins** [comment]
> > Latest version is now 4.11.1. We are using PACT which in its most recent version [was regenerated with ANTLR 4.11.1](https://github.com/pact-foundation/pact-jvm/issues/1608). We will just stay on an older version for now.
> 
> Ouch, do you know if code built with 4.11 will be compatible at runtime with 4.10?

I *think* it will. The ATN changed from 3 (used by 4.9.2) to 4 (used by 4.11.1) in Antlr 4.10. So as I understand it, that means 4.10 should be compatible with 4.11.

**Comment by knutwannheden** [comment]
@holly-cummins That sounds about right. Thanks for the heads up. I will look into the new extension and may be able to provide some feedback, since we've already used Pact consumer and provider tests in Quarkus projects for quite some time now.

**Comment by Sanne** [comment]
apologies, I don't remember about the plan here. @gsmet is it suitable for merging now ?

Rebased to get a fresh opinion from CI.

**Review by gsmet — APPROVED** [review]

**Comment by rsvoboda** [comment]
QS daily run fails - https://github.com/quarkusio/quarkus-quickstarts/actions/runs/3537201590
https://github.com/quarkusio/quarkus/issues/6588#issuecomment-1326106800

**Comment by Sanne** [comment]
The error mentions KIE:

```
 Error: Class initialization of org.kie.dmn.feel.parser.feel11.FEEL_1_1Lexer failed.
```

We're aware that this will break KIE but agreed with the team to merge this anyway, they'll catch up and updat ANTLR on their side as well soon.
I wasn't aware of this test, sorry - I did prevent a similar problem here: https://github.com/quarkusio/quarkus-quickstarts/pull/1155/files

**Comment by Sanne** [comment]
Actually that's exactly the same module that I had patched months ago to prevent this very issue. I know this worked, now I'm confused about why that would no longer be effective ?

**Comment by Sanne** [comment]
I tried to build it all locally and `kogito-dmn-quickstart` is compiling fine to native; it's working because it's using the version I had enforced in https://github.com/quarkusio/quarkus-quickstarts/pull/1155 .

I could use some suggestion as to why these versions wouldn't get applied on CI ; commenting here as well:
 - https://github.com/quarkusio/quarkus/issues/6588#issuecomment-1326862566

**Comment by tarilabs** [comment]
Could it be that the CI failure pertains to another quickstart? 🤔 Sorry just wild guess based on comments as I can access only on mobile atm

**Comment by Sanne** [comment]
@tarilabs you're right, I was blind yesterday night :) thanks. I'll send a PR shortly.

**Comment by tarilabs** [comment]
thanks to you @Sanne , sorry I couldn't turn around faster here before you. Thanks again for the related PR

**Pull request merged**
