### PR TITLE
Document SyntheticBeanBuildItem

### LINKED ISSUE #10691: Document SyntheticBeanBuildItem
`SyntheticBeanBuildItem` can be used to to register a bean whose instance can be easily produced through a recorder.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #10691

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]
I wonder if this (great) information should also be present in the extension author's guide (as this information is useful primarily - if not exclusively - for extension code)

**Comment by mkouba** [comment]
@geoand Good idea. I'll try to update the "Expose your components via CDI" section...

**Comment by mkouba** [comment]
@geoand @gastaldi updated...

**Review by geoand — APPROVED** [review]
Excellent!

**Review by manovotn — APPROVED** [review]
LGTM

**Pull request merged**
