### PR TITLE
Use InputStream.readAllBytes in FileUtil

### PR DESCRIPTION
**Pull request by gastaldi**
Using the JDK9+ goodies

### CODE REVIEW

**Review by geoand — APPROVED** [review]
I was actually thinking about looking for places we have this kind of pattern!

**Comment by gastaldi** [comment]
@geoand that's the main reason why I put it in a public branch in the quarkus repository 😉

**Comment by geoand** [comment]
Jus remember to remove it :)

**Comment by gsmet** [comment]
@gastaldi please don't push branches to the main repo. It triggers two different builds.

**Pull request merged**
