### PR TITLE
Add some new ignores for ReflectiveHierarchyStep

### LINKED ISSUE #7528: JsonNode missing in Index
**Describe the bug**
I get a log output about missing `com.fasterxml.jackson.databind.JsonNode` in the jandex index.
That class comes from jackson.

**Expected behavior**
No warn log output about missing classes in the index.

**Actual behavior**
I get the following output:
```
03.03.2020 09:02:22 WARN  [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - com.fasterxml.jackson.databind.JsonNode
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```

**To Reproduce**
Have JsonNode as part of a request body.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
MSYS_NT-10.0 SOMEHOST 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
 - Output of `java -version`: 
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
 - Quarkus version or git rev: 
1.3.0.Alpha2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: C:\eclipse\tools\apache-maven-3.5.3\bin\..
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_181\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### PR DESCRIPTION
**Pull request by gsmet**
Per user request.
Fixes #7528

### CODE REVIEW

**Comment by nimo23** [comment]
@gsmet the `ResteasyDotNames` (and maybe other ..DotNames) uses modifiable sets/lists. 

Does it make sense to use Set.of(..) or List.of(..) instead? 

The immutable Set.of(), Map.of(), List.of() has 
- better time and space efficiency 
- does not allow null values
- immutable and hence thread-safe
- ...

than mutable collections.

**Comment by nimo23** [comment]
For example:

Instead of 


```
private static final List<String> PACKAGES_IGNORED_FOR_REFLECTION = Arrays.asList("java.", "io.reactivex.",
            "org.reactivestreams.");
```
better

```
private static final List<String> PACKAGES_IGNORED_FOR_REFLECTION = List.of("java.", "io.reactivex.",
            "org.reactivestreams.");
```

The same for all DotNames with Sets, Lists, Maps..

**Comment by gsmet** [comment]
We still require JDK 8 compatibility so that's a no-no for these fancy things.

**Comment by nimo23** [comment]
oh did forget about that. but keep in mind for future;)

**Review by machi1990 — APPROVED** [review]
LGTM

**Pull request merged**
