### PR TITLE
Disable analytics on CI

### PR DESCRIPTION
**Pull request by gsmet**
There's noone to answer the question and approve.
Thanks to @yrodiere for finding out about this.

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]

**Review by brunobat — APPROVED** [review]

**Comment by gsmet** [comment]
Ah ah ah, obviously the analytics tests will be broken on CI...

**Comment by gsmet** [comment]
It should be fixed now.

**Review by yrodiere — APPROVED** [review]

**Comment by brunobat** [comment]
You could also set the system prop `quarkus.analytics.disabled` to true...
All artifacts were disabled by the group filter... Probably someone created a test outside of the banned group.

**Comment by gsmet** [comment]
I think it makes sense to disable this on common CI infrastructure. Think of someone running their app tests on CI: they don't want the question to be asked.

**Comment by brunobat** [comment]
> GitHub are using `CI=true`

Yeah... I didn't knew that. Thanks!

**Pull request merged**
