### PR TITLE
Bootstrap cache and groupId fixes

### PR DESCRIPTION
**Pull request by aloubyansky**
As discussed on the dev list:
* removed everything related to quarkus-deployment-dependency.graph
* move classpath cache from ~/.quarkus to project.basedir/target
* changed groupId of bootstrap from io.quarkus.bootstrap to io.quarkus

### CODE REVIEW

**Comment by Sanne** [comment]
let's be careful here, we're about to merge several out-of-tree extensions.

They all mention `<groupId>io.quarkus.bootstrap</groupId>`, so depending on order of merges things will need to be adjusted.

**Comment by aloubyansky** [comment]
Just in case, I won't mind rebasing this one.

**Comment by Sanne** [comment]
@aloubyansky thanks :)

> Just in case, I won't mind rebasing this one.

Thanks :) just merged the _flyway_ extension then #1649

**Review by gsmet — APPROVED** [review]
Looks good to me.

**Comment by gsmet** [comment]
@Sanne did you have any other extensions in mind? I think we can merge now?

**Comment by Sanne** [comment]
@gsmet +1 to merge, I'll let the other "out of tree" being written extension authors know.

@aloubyansky could you let the mailing list know?

thanks!

**Pull request merged**
