### PR TITLE
Allow the use of -H:+InlineBeforeAnalysis via a config flag or build item

### LINKED ISSUE #16117: Introduce a buildItem for compiler flag -H:+InlineBeforeAnalysis
## Description
GraalVM introduced in 21.0.0 a new compiler flag `-H:+InlineBeforeAnalysis` (see https://github.com/oracle/graal/issues/2594)

## Implementation ideas

It would be nice to have a buildItem to use this flag in extensions.

### PR DESCRIPTION
**Pull request by geoand**
Resolves: #16117

### CODE REVIEW

**Comment by ppalaga** [comment]
`-H:+InlineBeforeAnalysis` does a generally useful thing. Shouldn't we enable it by default and keep the config option only for disabling it?

**Comment by geoand** [comment]
That's more a question for the Mandrel team

**Comment by ppalaga** [comment]
I mean here in Quarkus, we could change the semantics of the new `quarkus.native.inlineBeforeAnalysis` to be true by default. We would not need the build item then.

**Comment by geoand** [comment]
Sure I get that.

What I am saying is that it's not for me to say if it should be the default or not

**Comment by zakkak** [comment]
This feature seems fairly new and is still [considered experimental](https://github.com/oracle/graal/blob/93ec5943ded2b22baa58529853ffc7cc5069204e/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/ExperimentalNativeImageInlineDuringParsingPlugin.java), as a result I would advise against enabling it by default.

**Review by zakkak — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand could we use the option in one of our native tests?

**Comment by geoand** [comment]
We certainly can - I'll add it to one tomorrow morning

**Review by zakkak — CHANGES_REQUESTED** [review]
After giving this some more thought I have two comments that could improve this PR:

1. The option is not available in 20.3, so we need a check to only add the flag when using 21.0 or greater and to print an error if the config flag is use with 20.3.
2.  `-H:±InlineBeforeAnalysis` is accompanied by `-H:InlineBeforeAnalysisMaxDepth=9` so it might be worth allowing `quarkus.native.inline-before-analysis` to accept either a boolean or an integer. In the integer case both `-H:+InlineBeforeAnalysis` and `-H:InlineBeforeAnalysisMaxDepth=<integer value>` should be appended to the command line.

**Comment by geoand** [comment]
@zakkak I'll merge the PR as is once CI finishes. Feel free to make those improvements once it's in

**Pull request merged**
