### PR TITLE
Remove duplicated HTTP body size limit check

### PR DESCRIPTION
**Pull request by snazy**
Also removes the duplicate addition of the body-size-limit enforcer.

### CODE REVIEW

**Comment by cescoffier** [comment]
(copied from zulip)

That's the opposite. That would be the management one to remove, and only if it's mounted on a router having it already. 
So, keep the one line 425 and remove the one line 553.

**Review by cescoffier — COMMENTED** [review]
I think it should work as expected now.
Does your case pass?

**Comment by snazy** [comment]
@cescoffier it does with the `.order(-3)`

**Comment by snazy** [comment]
-2 is the body-size-check.
Haven't seen any route for -1 though

**Comment by cescoffier** [comment]
I think we should start having constants (and documentation) around these numbers.

**Comment by snazy** [comment]
> I think we should start having constants (and documentation) around these numbers.

Makes sense. Want me to do that in this PR or better have a follow-up?

**Comment by cescoffier** [comment]
Let's do it in another PR. That one is ready from my POV.

**Comment by cescoffier** [comment]
Can you rebase? It should be good to go.

**Comment by snazy** [comment]
> Can you rebase?

Sure, done.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Pull request merged**
