### PR TITLE
Exporting invocation order of Filters

### LINKED ISSUE #14885: Export invocation order
**Description**
I would like see which filters/interceptors in which order are run on a particular JAX-RS resource/CDI bean. Ideally the invocation order can be exported during the (maven) build.

**Implementation ideas**

### PR DESCRIPTION
**Pull request by saumya1singh**
Fixes: #14885

### CODE REVIEW

**Comment by geoand** [comment]
Thanks!

It looks like it already conflicts with what we have on master :)

Moreover, I'll need to take a closer look to let you know what needs to be done to progress to meet the actual needs mentioned in https://github.com/quarkusio/quarkus/issues/14885

**Comment by SaumyaSingh1** [comment]
> Thanks!
> 
> It looks like it already conflicts with what we have on master :)
> 
> Moreover, I'll need to take a closer look to let you know what needs to be done to progress to meet the actual needs mentioned in #14885

Yeah, I see the conflict is because of the previous PR I made.
I was working on `DevConsoleProcessor` before as well. That is my code only, which I wrote for Static Resources Task :)

**Comment by geoand** [comment]
This is a good start, but it's not exactly what we are looking for to solve #14885.
The general idea is for a user to be able to see which filters are associated with which endpoint.

Looking at the existing DevUI, I think we should add that information into the scores page (the UI will need some attention as to not cluter each entry).

To determine the filters for each endpoint you will need to update [EndpointScore](https://github.com/quarkusio/quarkus/blob/master/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/util/ScoreSystem.java#L28) to contain a list of request filter entries. Those entries will a new static class inside the `ScoreSystem` class that looks like so:

```java
    public static class RequestFilterEntry {
        public final String name;
        public final boolean preMatch;

        public RequestFilterEntry(String name, boolean preMatch) {
            this.name = name;
            this.preMatch = preMatch;
        }
    }
```
 
Those filter entries will be determined in [this](https://github.com/quarkusio/quarkus/blob/master/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/util/ScoreSystem.java#L101) method by doing something like:

```java
            ServerRestHandler[] handlerChain = runtimeResource.getHandlerChain();
            List<RequestFilterEntry> requestFilters = new ArrayList<>();
            for (ServerRestHandler serverRestHandler : handlerChain) {
                if (serverRestHandler instanceof ResourceRequestFilterHandler) {
                    ResourceRequestFilterHandler requestFilterHandler = (ResourceRequestFilterHandler) serverRestHandler;
                    requestFilters.add(new RequestFilterEntry(requestFilterHandler.getFilter().getClass().getName(), requestFilterHandler.isPreMatch()));
                }
            }
```

Once you do all that, each `EndpointScore` will contain the list of request filters which you need to display in nice manner in the UI.

Does this all make sense?

**Comment by SaumyaSingh1** [comment]
Yes, this is all very well explained and it is now clear: going to start the work :)

**Comment by geoand** [comment]
Cool :)

**Comment by SaumyaSingh1** [comment]
So now I am trying to expose all the details of `requestFilters` from `DevConsoleProcessor` into my `filters.html`. 
But I don't understand this piece of an error on running `mvn quarkus:dev`. 

image

Perhaps this is related to my code :)?

**Comment by geoand** [comment]
I would suggest doing a clean build of Quarkus and of the project you are using to test it.
Furthermore, for the project you are testing, make sure that you are using the same version of Quarkus for both the quarkus-bom and the quarkus-maven-plugin

**Comment by SaumyaSingh1** [comment]
oh nice, it worked :)
I should have asked early: I wasted time fixing on my own 🤦🏻

**Comment by geoand** [comment]
A rule of thumb is that anytime you see a `NoSuchMethodError`, there is a version mismatch somewhere :)

**Comment by SaumyaSingh1** [comment]
Is it a good way to show Filters like this?
Corresponding to each filter should we show the `diagnostic.score` as well?

image

**Comment by geoand** [comment]
A filter does not have a score.

I was thinking that filters should be in some kind of UI component that allows you to open / close them. The reason is that there could potentially be a lot of filters and in that case that would really mess up the UI.

**Comment by SaumyaSingh1** [comment]
Humm like for one single endpoint, one can have a huge list of Filters. 

yes that definitely makes sense to put it in a UI component that allows to open/close them else the score page will be flooded with list of filters.

**Comment by geoand** [comment]
> Humm like for one single endpoint, one can have a huge list of Filters.
> 

Yeah, there is no telling how many there could be. 
Zero is very likely, but so is something like 5.

**Comment by SaumyaSingh1** [comment]
https://user-images.githubusercontent.com/46818757/108964610-af6e8480-76a1-11eb-8dc3-8eb97ef6a159.mp4

After trying diff styles, ended here: well I am working to improve this too :)
Something like this will perhaps do the work?

**Comment by geoand** [comment]
Yeah, that is a step in the proper direction.

Can you also add a simple screenshot? I would like @phillip-kruger to be able to see it and perhaps provide suggestions for alternatives :)

**Comment by SaumyaSingh1** [comment]
> Can you also add a simple screenshot pointing to the part in question? I would like @phillip-kruger to be able to see it and perhaps provide suggestions for alternatives :)

Sure, I was thinking to put this on zulip too so that can get better feedback and suggestions from everyone :)

**Comment by geoand** [comment]
Sure, although I think that Phillip's advice is all you'll need :)

**Comment by SaumyaSingh1** [comment]
@phillip-kruger 

I added the `Filters` part as pointed in the screenshot. On clicking `Click to view Filters List`, we are able to see the list of Filters :)
image
image

Thinking of using a better UI component 🤔  WDYT

**Comment by phillip-kruger** [comment]
Hi @SaumyaSingh1 - I think what you have is great already.  Here some notes on the screen and what I would possibly change:

As I understand, the main goal of the screen is to show the score the endpoints, first at a global value and expanded in these 3 categories:

- Execution
- Resource
- Writer

Then as a second goal provide some metadata about the endpoints, like
- filters
- content type

I think users might 1) have many endpoints and 2) really mostly care about the endpoints that does not score high, right ?

So how about we order the endpoints from low scoring to high scoring, so that the "bad" ones is at the top. Then maybe use an
Accordion (https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example) that only list the Endpoints and their total score, and if selected open up with a section that contain the 3 detailed scores.

Then, what would be cool is if those 3 scored can be more visible, so I was thinking, maybe a basic Gauge per score ?

Then at the bottom a table with the other meta data on the endpoint, with the filters using a collapse (https://getbootstrap.com/docs/4.6/components/collapse/) like you have now, but maybe just in icon to activate the "show"

So something like this maybe :


idea


On another note: I would rename the page name and remove the "Quarkus REST" part, and just call it Scoring (we know it's Quarkus and we know it's Rest :) )

Let me know if I can help you with this :)

**Comment by phillip-kruger** [comment]
Here a pure CSS Gauge example: https://github.com/JohnrBell/Gauge_CSS

**Comment by geoand** [comment]
WOW, that design is awesome!

**Comment by phillip-kruger** [comment]
Thanks @geoand :) It does not have to be gauges, just somehow make the score more visible, as at the moment , metadata and score blur a bit and it's a bit of an alignment exercise to see what score is where.

**Comment by SaumyaSingh1** [comment]
Awesome, this design idea is soo beautiful and clean 💙 @phillip-kruger 

Definitely, I would love to do the redesigning of the score page :) But I think for that I will need to open a separate PR because this one is mainly focused on the "Filters" Category. WDYT @geoand 

As Phillip suggested for the Filters I will keep the simple `>` kinda icon (simple and nice) and of-course using collapse :)

**Comment by geoand** [comment]
> Definitely, I would love to do the redesigning of the score page :) But I think for that I will need to open a separate PR because this one is mainly focused on the "Filters" Category. WDYT @geoand
> 

Yes, for sure

**Comment by phillip-kruger** [comment]
What about adding the "Meta data" table at the bottom ? The we can later work on the score section ?

**Comment by geoand** [comment]
If @SaumyaSingh1 is up for it or if you want to chip in sure, why not :)

**Comment by SaumyaSingh1** [comment]
sure :)

**Comment by geoand** [comment]
Can you post a screenshot of what the page looks like now?

**Comment by SaumyaSingh1** [comment]
Sure, it is simple right now with the `Filter` functionality added :)

image
image

**Review by geoand — APPROVED** [review]
LGMT

**Comment by geoand** [comment]
I closed and re-opened to get CI working

**Comment by SaumyaSingh1** [comment]
nice, all passed :)

**Comment by geoand** [comment]
Thanks @SaumyaSingh1 !

**Pull request merged**
