### PR TITLE
Bump netty from 4.1.111 to 4.1.115

### PR DESCRIPTION
**Pull request by CodeSimcoe**
Upgrade netty to 4.1.115
fixes cve GHSA-xq3w-v528-46rv

### CODE REVIEW

**Comment by gsmet** [comment]
Upgrading Netty requires coordinated effort across several components of the stack so this PR won't be sufficient.

@cescoffier what's your plan about this update?

**Comment by cescoffier** [comment]
@gsmet the Vert.x release is done.  Bindings are on their way, but the Quarkus integration is not going to happen this week. Hopefully next week.

**Comment by gsmet** [comment]
OK, let's close this one then. Thanks for the effort, though!

@cescoffier I plan to build a last 3.16 next Wednesday if that helps.

**Comment by cescoffier** [comment]
The plan is to land before this, but can't commit. There are a few changes that need adaptation. Unfortunately, my calendar is not giving me a lot of time to work on this.

**Comment by cescoffier** [comment]
@jponge is going to open a PR soon actually.

**Comment by jponge** [comment]
I confirm that the Netty bump broke some substitutions

**Comment by jponge** [comment]
Constructors have changed in `JdkSslClientContext` (and the server counterpart) with the addition of a package-private parameter, so it won't be a 5 minutes fix

**Comment by jponge** [comment]
https://github.com/quarkusio/quarkus/pull/44515

**Pull request closed without merging**
