### PR TITLE
Produce valid JSON for Multi<String> return type in RESTEasy Reactive

### LINKED ISSUE #18043: Resteasy-reactive produces invalid json for Multi
## Describe the bug
While using Multi<String> as a return value for a method annotated with `@Produces(MediaType.APPLICATION_JSON)`, the returned json looks like an array(it uses square brackets around the results), but lacks quotation marks around the strings inside e.g. `[Hello,Hola]` instead of `["Hello","Hola"]`. Adding quarkus-resteasy-reactive-jackson to a classpath does not solve the problem.

### Expected behaviour
Any of the following:
Returning of valid json array (`["Hello","Hola"]`)
Returning values one-by-one
Compilation error

### Actual behavior
Invalid json array(`[Hello,Hola]`)

## To Reproduce

Link to a reproducer:
```
git clone git@github.com:fedinskiy/reproducer.git -b multi-jackson
```
1. `mvn clean quarkus:dev`
2. `curl -w'\n' localhost:8080/hello/multi`
Or:
1. `mvn clean test`

### Output of `uname -a` or `ver`
`Linux localhost.localdomain 5.12.10-300.fc34.x86_64 #1 SMP Thu Jun 10 14:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
### Output of `java -version`
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment GraalVM CE 20.3.2 (build 11.0.11+8-jvmci-20.3-b15)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.2 (build 11.0.11+8-jvmci-20.3-b15, mixed mode, sharing)
```
### Quarkus version or git rev
2.0.0.CR3
OR
1.13.7.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 

May be somehow connected to https://github.com/quarkusio/quarkus/issues/14183

### PR DESCRIPTION
**Pull request by oliver-brm**
This is primarily meant to provide a fix for #18043. However, there were no `integration-tests/resteasy-reactive` yet, so I added them. I have a few questions with you to discuss:

**Regarding my fix for the issue in `StreamingUtil.java`...**
  - is it safe for integration, regarding the UTF-8 charset and regarding the `MediaType` condition?
  - the fix is a bit hack-ish; I think, if possible, it would be better to change those Jackson/JSONB writers, for example `FullyFeaturedServerJacksonMessageBodyWriter`; however, I wasn't sure how to test that for side-effects; probably running the RESTeasy TCK?

**Regarding the integration tests for RESTeasy reactive**
I added the project right under `integration-tests` and copied (YUK!) some classes from the `resteasy-mutiny` and `resteasy-jackson` integration tests. Would be better to share the classes, using a parent or shared project. However, I was not sure how much restructuring I would be allowed to do in this scope. You might like to have this done under a separate GitHub issue?

### CODE REVIEW

**Comment by geoand** [comment]
Thanks!

Ping me when you are ready for a review

**Comment by oliver-brm** [comment]
> Thanks!
> 
> Ping me when you are ready for a review
Ping! :-)

**Comment by geoand** [comment]
Thanks for this!

I would prefer if the PR didn't introduce a whole new project just for testing.
The PR could likely easily just add a new test in one of the json modules (and it doesn't need to be a integration test, it can be one a `@QuarkusUnitTest`)

**Comment by oliver-brm** [comment]
Hmm, I tried to move some of the tests to the `quarkus-resteasy-reactive-jackson`. However, I cannot get the test to run:
```
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for io.quarkus:quarkus-resteasy-reactive-jackson::jar:999-SNAPSHOT
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:325)
	at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:169)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:314)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:635)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:682)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	... 34 more
Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to resolve artifacts
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolve(MavenArtifactResolver.java:172)
	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel(BootstrapAppModelResolver.java:233)
	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel(BootstrapAppModelResolver.java:147)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:311)
	... 44 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifacts(DefaultRepositorySystem.java:270)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolve(MavenArtifactResolver.java:170)
	... 47 more
```

**Comment by geoand** [comment]
I would suggest the following:

`mvn -Dquickly` to build all changes and then `mvn test -f extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/deployment/` to run the tests in the jackson module.

see https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#workflow-tips for more details

**Comment by oliver-brm** [comment]
Sorry, I messed up my fork. Had to re-create one and open a new PR. Please see #18401.

**Pull request closed without merging**
