### PR TITLE
Support SmallRye Config 1.9.2.

### LINKED ISSUE #9895: Allow activation of multiple configuration profiles
**Description**
I understand that currently a Quarkus config profile denotes an "environment".

But sometimes you want to resuse configuration bits but you cannot put them in the "common" block (properties without `%<profileName>` prefix).
E.g. in my current project we would like to toggle dev-mode between h2 (default) and postgres (also used in prod, but with slightly different config). We have some more dev specific settings like logging to a file (which we don't do in prod) etc.
In this scenario we have to duplicate many properties from `dev` to `dev-postgres` which violates the DRY principle and makes the config less readable.
(To make things worse we have multiple "layers" of config files in various submodules which are aggregated via a custom `ConfigSourceProvider`.)

It would come in handy if multiple profiles could be actived.

**Implementation ideas**
Allow profiles to be set in a comma separated way, e.g. `foo,bar` (`bar` would overwrite `foo`, Spring Boot style IIRC).

Fun fact (or better to say bug): As of 1.4.2.Final you _can_ set `-Dquarkus.profile=foo,bar` and Quarkus will happily report that it activated `foo,bar`, but nothing of the two profiles is taken into account.

### LINKED ISSUE #12758: CNFE when using Smallrye @ConfigMapping
**Describe the bug**
I am using configmappings for a Map<String, Configuration>.
https://smallrye.io/docs/smallrye-config/mapping/mapping.html#_collections_config_mapping

When I run in dev mode, I get a CNFE for my `Configuration` class.
When I run as jar (mvn clean install), everything works as expected.

**Expected behavior**
ConfigMapping works in dev mode as it does as jar.

**Actual behavior**
```
2020-10-16 14:03:07,817 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:675)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:93)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: org/acme/amqp/config/ConnectionConfiguration
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.System$2.defineClass(System.java:2128)
        at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
        at io.smallrye.common.classloader.ClassDefiner$1.run(ClassDefiner.java:19)
        at io.smallrye.common.classloader.ClassDefiner$1.run(ClassDefiner.java:14)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.smallrye.common.classloader.ClassDefiner.defineClass(ClassDefiner.java:14)
        at io.smallrye.config.ConfigMappingLoader.loadClass(ConfigMappingLoader.java:76)
        at io.smallrye.config.ConfigMappingLoader.loadClass(ConfigMappingLoader.java:71)
        at io.smallrye.config.ConfigMappingLoader.getImplementationClass(ConfigMappingLoader.java:61)
        at io.smallrye.config.ConfigMappingLoader$1.computeValue(ConfigMappingLoader.java:18)
        at io.smallrye.config.ConfigMappingLoader$1.computeValue(ConfigMappingLoader.java:15)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
        at java.base/java.lang.ClassValue.get(ClassValue.java:114)
        at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:37)
        at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:68)
        at io.smallrye.config.ConfigMappingProvider$GetOrCreateEnclosingGroupInMap.apply(ConfigMappingProvider.java:507)
        at io.smallrye.config.ConfigMappingProvider$GetOrCreateEnclosingGroupInMap.accept(ConfigMappingProvider.java:513)
        at io.smallrye.config.ConfigMappingProvider$GetOrCreateEnclosingGroupInMap.accept(ConfigMappingProvider.java:477)
        at io.smallrye.config.ConfigMappingProvider$ConsumeOneAndThen.accept(ConfigMappingProvider.java:175)
        at io.smallrye.config.ConfigMappingProvider$ConsumeOneAndThen.accept(ConfigMappingProvider.java:166)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:633)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:602)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:44)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:32)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:52)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy_0(ConfigBuildStep$registerConfigMappings510524965.zig:130)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy(ConfigBuildStep$registerConfigMappings510524965.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:532)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.acme.amqp.config.ConnectionConfiguration
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:412)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:365)
        ... 42 more
```

**To Reproduce**

1. Download the reproducer:
[configmapping-cnfe.zip](https://github.com/quarkusio/quarkus/files/5391388/configmapping-cnfe.zip)
2. mvn quarkus:dev
3. CNFE from above happens
4. Now, run as jar (mvn quarkus:dev cd target/ java -jar  configmapping-cnfe-1.0.0-SNAPSHOT-runner.jar)
5. Quarkus starts.
6. Go to http://localhost:8080/hello and you see the configuration value.

**Configuration**
```properties
rabbitmq.wolf.connection-string=https://example.com

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
 - Quarkus version or git rev: 1.9.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\eclipse\tools\apache-maven\bin\..
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\zulu11.39.15-ca-jdk11.0.7-win_x64
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### PR DESCRIPTION
**Pull request by radcortez**
Release Notes:
https://github.com/smallrye/smallrye-config/releases/tag/1.9.2

* Fixes #12758
* Fixes #9895

### CODE REVIEW

**Comment by gsmet** [comment]
Can you adjust the description? GH won't automatically resolves the issues the way you did it. You need:

```
* Fixes #...
* Fixes #...
```

(I could do it but I prefer telling you for next times)

Thanks!

**Comment by radcortez** [comment]
Sure!

**Review by gastaldi — APPROVED** [review]

**Comment by famod** [comment]
I wonder whether multi profile support should be documented somewhere?

**Comment by radcortez** [comment]
> I wonder whether multi profile support should be documented somewhere?

I can add an entry to the config doc, but it will point to the SR Config docs, since this is coming from SR Config.

**Comment by gsmet** [comment]
Could you briefly describe the feature here and what it means in a Quarkus environment? I think it's something I would like to have in the release notes.

**Comment by radcortez** [comment]
Sure.

**Comment by radcortez** [comment]
> Multiple Profiles may be active at the same time. The configuration `quarkus.profile` or `QUARKUS_PROFILE` accepts a
comma-separated list of profile names.
>
> When multiple profiles are active, the rules for profile configuration are exactly the same. If two profiles define the
same configuration, then the last listed profile has priority.

I'm also adding this bit into config.adoc, with some additional enhancements in a separate PR.

**Pull request merged**
