### PR TITLE
Add exposed option to ResourceProperties

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by geoand** [comment]
@gytis does this fix an issue or was this done in a response to a discussion in some other PR? If so, please link it so reviewers can have more context.

**Review by FroMage — APPROVED** [review]
Yeah, some context would have been helpful, but I can deduce it from the PR: this appears to be allow me to define a default for the class as to whether methods default to exposed or not. We have similar settings in JPA and anything JSON/XML, so it makes sense.

**Comment by FroMage** [comment]
`io.quarkus.it.mongodb.rest.data.panache.MongoDbRestDataPanacheTest` failed on Windows, is this related?

**Comment by gytis** [comment]
Sorry for the lack of context. @FroMage is correct. This is a class-level config option to set `expose` property for all resource methods (e.g. to hide all by default).

**Comment by gytis** [comment]
I'm not sure about the Windows job. Hard to see the problem from the log. Maybe we could rerun the failed one just to see if it happen again?

**Comment by geoand** [comment]
> I'm not sure about the Windows job. Hard to see the problem from the log. Maybe we could rerun the failed one just to see if it happen again?

I just restarted CI.

**Pull request merged**
