### PR TITLE
Upgrade SmallRye Metrics to 2.4.3

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello @jmartisk, Given that this PR contains a change that needs to be tested and pass against Java 8, could you rebase this PR against latest master please? The current (unrelated) Java 8 test failure in this PR should be solved by some commits that we have made in master a few minutes back.

**Comment by gsmet** [comment]
I just force-pushed a rebase so that we can get the CI results by tomorrow morning.

**Review by jaikiran — APPROVED** [review]

**Comment by jaikiran** [comment]
> I just force-pushed a rebase 

Hello @gsmet, how did you do that? Doesn't that require write permissions on jmartisk's repo? Asking so that I can follow that process for any such PRs in future.

**Comment by gsmet** [comment]
@jaikiran as long as you have permissions to write to the Quarkus repository, you can push changes to PR branches of personal forks (if the creator hasn't unchecked the checkbox allowing that). This has to be used with caution though as you don't want to overwrite other people's work or be in the way.

**Comment by jaikiran** [comment]
Thanks.

> This has to be used with caution though as you don't want to overwrite other people's work or be in the way.

Understood :) This mostly will be a last resort thing if at all I use it ever.

**Comment by gsmet** [comment]
It can also be used to collaborate on a PR. I usually just ask permission in this case.

**Pull request merged**
