### PR TITLE
Update to RestEasy 4.5.10

### PR DESCRIPTION
**Pull request by sberyozkin**
CC @ronsigal

### CODE REVIEW

**Comment by geoand** [comment]
CI output doesn't look good:

```
com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.servlet.ServletOutputStream. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
```

**Comment by sberyozkin** [comment]
Hmm, I run smallrye-jwt tests with it, was fine, and Ron tested against 1.13.2, let me check

**Comment by sberyozkin** [comment]
This is probably it, https://github.com/resteasy/Resteasy/commit/abfcd15a01387c0c22d8c33f4f2be6034a540112. Was tricky to spot as the native tests are affected, let me ping Ron

**Comment by geoand** [comment]
Sounds reasonable

**Pull request closed without merging**
