### PR TITLE
Limit scope of jsoup to only quarkus-extension-processor

### LINKED ISSUE #26141: bootstrap mentions jsoup as wagon-http dependency, that's no longer true
### Describe the bug

bootstrap mentions jsoup as wagon-http dependency, that's no longer true

This changed in https://github.com/quarkusio/quarkus/commit/a342c5652677a17a1eaaf209628b4364cdb81251 when maven-wagon was updated to 3.5.1 and no longer pulls in jsoup dependency

See https://mvnrepository.com/artifact/org.apache.maven.wagon/wagon-http-shared/3.5.1 and compare with previously used https://mvnrepository.com/artifact/org.apache.maven.wagon/wagon-http-shared/3.4.3

At least the description in `independent-projects/bootstrap/pom.xml` needs to be adjusted
Maybe even revisited, because the exclude in docs module feels a bit fishy.

`git grep jsoup` gives this:
```
core/processor/pom.xml:            <groupId>org.jsoup</groupId>
core/processor/pom.xml:            <artifactId>jsoup</artifactId>
core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/JavaDocParser.java:import org.jsoup.Jsoup;
core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/JavaDocParser.java:import org.jsoup.nodes.Node;
core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/JavaDocParser.java:import org.jsoup.nodes.TextNode;
docs/pom.xml:            <groupId>org.jsoup</groupId>
docs/pom.xml:            <artifactId>jsoup</artifactId>
docs/pom.xml:                    <groupId>org.jsoup</groupId>
docs/pom.xml:                    <artifactId>jsoup</artifactId>
independent-projects/bootstrap/bom/pom.xml:                <groupId>org.jsoup</groupId>
independent-projects/bootstrap/bom/pom.xml:                <artifactId>jsoup</artifactId>
independent-projects/bootstrap/bom/pom.xml:                <version>${jsoup.version}</version>
independent-projects/bootstrap/pom.xml:        <jsoup.version>1.14.2</jsoup.version> <!-- wagon-http dependency -->
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

Quarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by famod**
Fixes #26141

jsoup scope is now limited as much as possible and follows the example of xstream: https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/pom.xml#L54-L55

/cc @rsvoboda @aloubyansky @gsmet

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by famod** [comment]
Those failures don't look related. I also didn't have them in my fork.

**Comment by aloubyansky** [comment]
Thanks @famod I think generally it's OK. Looking at this and the xstream case you referenced, I thought it might be better to still add property versions in the build-parent for these, otherwise when one day we need to add them back to the BOM we might not find them in those modules. WDYT?

**Comment by famod** [comment]
Well, I'm not sure this will ever be the case so it looks like YAGNI to me? But I have no strong opinion.

One nice effect of the current soultion is that incremental build is more efficient if the version is updated as build-parent affects more modules.

**Review by aloubyansky — APPROVED** [review]
Ok, thanks!

**Pull request merged**
