### PR TITLE
Add sslmode/sslrootcert service binding params for postgresql

### LINKED ISSUE #24323: Added sslmode&sslrootcert Service Binding support to postgresql and cockroachdb
### Description

CockroachDB Cloud, by default, uses one-way TLS for client and server authentication. To do so, the client application has to download the server CA Certificate (ie: root.crt), and the path of this file has to be set to sslrootcert and added to the connection string.   
We need a way to let a client application be able to know the path of this root.crt and build up the connection URL 
We should enhance Quarkus kubernetes-service-binding, and jdbc-postgresql modules to read from $SERVICE_BINDING_ROOT, and construct the connection URL after those connection properties and root.crt are bound to this folder.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by myeung18**
- added sslmode/option(cluster) parameters postgresql conn. string
- add support cockroachdb cloud

Closes: https://github.com/quarkusio/quarkus/issues/24323

### CODE REVIEW

**Comment by geoand** [comment]
@maxandersen @cescoffier FYI

**Review by geoand — COMMENTED** [review]
I have no way to verify this, but it does seem reasonable to me.

@gsmet do you have any JDBC related comments?

**Comment by myeung18** [comment]
> I have no way to verify this, but it does seem reasonable to me.
> 
> @gsmet do you have any JDBC related comments?

is there any further comment? Any decision to merge?

**Review by gsmet — APPROVED** [review]
I rebased it and did some minor cleanups: my main issue was the method that was nearly entirely duplicated.

Let's merge it once CI is happy.

**Comment by gsmet** [comment]
Looks like I broke something. I ran these tests locally though so there's something weird.

**Comment by gsmet** [comment]
First, I have force pushed to your branch so make sure to get the latest update from there before working further on this.

I didn't break something, it has always been broken on Windows as the path is using `\` instead of `/`.

But seeing the path, I wonder if this really works? I would have expected a class path resource but a path from the root of the module makes me wonder if it will really work in practice?

Can you make sure of that?

**Comment by myeung18** [comment]
> First, I have force pushed to your branch so make sure to get the latest update from there before working further on this.
> 
> I didn't break something, it has always been broken on Windows as the path is using `\` instead of `/`.
> 
> But seeing the path, I wonder if this really works? I would have expected a class path resource but a path from the root of the module makes me wonder if it will really work in practice?
> 
> Can you make sure of that?

The failure was only on those test cases.  They failed take windows tester into account.  I have fixes for them in the new commit.

That root path in test case is actually SERVICE_BINDING_ROOT. Its default is /bindings, and applications can change to other paths when they use SBO. Test case uses module root is only for testing, as I need some fixed paths for assertion.

The change is tested with SBO in OCP with CockroachDB as well as postgresql:
```
example Connection URLs from debug log:
jdbc:postgresql://free-tier9.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/bindings/crdb-quarkus-app-d-rh-qe-inst-050-1b5a707a63-dbsc/root.crt&options=--cluster%3Drh-qe-inst-050-274

jdbc:postgresql://p.vnxqmt3daxxxxxgj3o4ktbbyyi.db.postgresbridge.com:5432/postgres
```

**Comment by gsmet** [comment]
OK, I went with a simpler version of the Windows fix. Using `Path` should do the work for us automatically without replacing chars.
Also, you don't need to use a regexp to replace a character. You can use `String.replace()`.

Let's see what CI has to say.

**Pull request merged**
