### PR TITLE
Have the Mongo Clients initialized eagerly

### LINKED ISSUE #7895: Mongo clients should be initialized eagerly
**Describe the bug**
Currently the mongo clients are flagged as @ApplicaitonScoped, which means they are wrapped by a proxy making them initialized on first use.

This is annoying as

* we don't respect the configuration of pre-filling the pool on boot
* we can't validate the connection properties, deferring any failure
* it's an overhead

relates to #4507

### PR DESCRIPTION
**Pull request by Postremus**
closes #7895

### CODE REVIEW

**Comment by geoand** [comment]
@Postremus why was this closed?

**Comment by Postremus** [comment]
@geoand I noticed that the github actions failed on my branch, just after opening this PR.
I will reopen once I fix everything.

**Comment by geoand** [comment]
Gotcha, thanks!

**Comment by dufoli** [comment]
@Postremus issue come from fact import is not sorted. I do not know why, in your patch, you move many import whereas mvn clean must sort it automaticly.

**Pull request closed without merging**
