### PR TITLE
Add Prometheus annotations when smallrye metrics in enabled

### LINKED ISSUE #10301: Enhancement : add Prometheus annotation when extension : metrics + kubernetes are used
when we are using metrics + kubernetes extensions, should we add those annotations to the pods into the generated file target\kubernetes\kubernetes.yml 

I found this in prometheus helm chart documentation : https://github.com/helm/charts/tree/master/stable/prometheus

In order to get prometheus to scrape pods, you must add annotations to the the pods as below:
```
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
```

I tested by adding

kubectl annotate pods iep-monitoring-junk-f8fbbdbb9-84jkt prometheus.io/scrape="true"
kubectl annotate pods iep-monitoring-junk-f8fbbdbb9-84jkt prometheus.io/path=/metrics
kubectl annotate pods iep-monitoring-junk-f8fbbdbb9-84jkt prometheus.io/port="8080"

and Prometheus started to scrape metrics from my application.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #10301

### CODE REVIEW

**Comment by geoand** [comment]
@maxandersen I wasn't able to find any additional information for the application annotations on Openshift. Who is the best person to ask for this?

**Comment by gsmet** [comment]
This looks like a new feature, I'm not sure it's a good backport candidate.

**Comment by geoand** [comment]
OK, no problem.

**Review by iocanel — APPROVED** [review]
LGTM, I am wondering if in the future we also need to support the `ServiceMonitor` custom resource which is an operator based alternative to those annotations!

**Comment by geoand** [comment]
@brancz Hey! @maxandersen mentioned that you are the right person to help us figure out what the proper way of monitoring applications (via Prometheus) running on Openshift is.

To give you some context, in Quarkus we generate the Kubernetes / Openshift manifests based on the various capabilities the application has and we are wondering what Kubernetes manifests we should be generating in order to properly monitor a user application on Openshift.

Thanks!

**Comment by brancz** [comment]
Yes as @iocanel mentioned `ServiceMonitor`s are the mechanism to use in OpenShift (and the larger Kubernetes ecosystem for anyone using the prometheus-operator, which is a very popular project and many people use it). In OpenShift everything will work out of the box with the new "user workload monitoring" feature when you create a ServiceMonitor.

**Comment by geoand** [comment]
Thanks @brancz, I'll check it out

**Comment by maxandersen** [comment]
thanks @brancz - just want to grok when the prometheus annotations are relevant and when they aren't - are you saying ServiceMonitor are the key and then prometheus annotations are irrelevant or should both be applied ?

**Comment by geoand** [comment]
Looks like we should start supporting the Prometheus CRD. @iocanel does dekorate have the ability to generate that?

**Pull request merged**
