### PR TITLE
4967 Add pinned info and description for categories

### PR DESCRIPTION
**Pull request by emmanuelbernard**
We don't need to use description in the UI just yet but it's there now.
Also added a reactive driver into the reactive section

### CODE REVIEW

**Review by ia3andy — APPROVED** [review]
Cool !

**Comment by emmanuelbernard** [comment]
Fix for https://github.com/quarkusio/quarkus/issues/4967

**Comment by maxandersen** [comment]
Thanks - pushed after removing the superfluous period at the end of each descripition since other descriptions we have don't have it.

**Comment by emmanuelbernard** [comment]
Ah, well I was following proper English since some had multiple sencences. But better use consistency.

**Pull request closed without merging**
