### PR TITLE
Fix base-codestart 2.x

### LINKED ISSUE #32474: Quarkus 3 kotlin generation missconfigures allopen
**Describe the bug**
Generating an new app with quarkus-kotlin for Quarkus 3 generates an allopen configuration for `javax.` instead of for `jakarta.`

**Expected behavior**
The list of allopen with annotation should be the jakarta imports

**Actual behavior**
The list of allopen with annotation should be the javax imports

**To Reproduce**
1. https://code.quarkus.io/?b=GRADLE_KOTLIN_DSL&e=kotlin&S=io.quarkus.platform%3A3.0&extension-search=kotlin
2. Have a look into the zip
3. Happens in maven and gradle

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #32474

### CODE REVIEW

**Comment by ia3andy** [comment]
Also fix jbang

**Comment by ia3andy** [comment]
Tested:
```
qss create app -S=2.16 gradle-kotlin-app --gradle --kotlin
qss create app -S=3.0 gradle-kotlin-app-3 --gradle --kotlin
qss create app jb3 --jbang -S 3.0
qss create app jb --jbang -S 2.16

**Comment by bulldog98** [comment]
That same problem exists with maven as well

**Comment by ia3andy** [comment]
> That same problem exists with maven as well

Right thanks I missed that one, let me fix it

**Comment by ia3andy** [comment]
ok it's fixed and tested with:
```
qss create app maven-kotlin --kotlin -S=3.0
qss create app maven-kotlin-2.16 --kotlin -S=2.16

**Review by gsmet — APPROVED** [review]

**Pull request merged**
