### PR TITLE
Add support for JUnit @Nested

### LINKED ISSUE #11323: @Nested (Junit5) associated with @QuarkusTest causes an UnsatisfiedResolutionException
**Description**
An `UnsatisfiedResolutionException` will be thrown when a test class is annotated with `@QuarkusTest` and implements inner test classes in connection with `@Nested` (Junit5).

**Actual behavior**
The relevant dump of the stack trace (via `mvn clean verify`):
```
...
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class org.acme.testcoverage.GreetingResourceTest$NestedTestClass] and qualifiers [[]]
...
```

**Steps to reproduce the behavior**
1. Checkout https://github.com/quarkusio/quarkus-quickstarts/tree/master/tests-with-coverage-quickstart 
2. Adjust https://github.com/quarkusio/quarkus-quickstarts/blob/master/tests-with-coverage-quickstart/src/test/java/org/acme/testcoverage/GreetingResourceTest.java

```
package org.acme.testcoverage;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

import java.util.UUID;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
@Tag("integration")
public class GreetingResourceTest {

    @Nested
    class NestedTestClass {
        @Test
        public void testHelloEndpoint() {
            given()
                    .when().get("/hello")
                    .then()
                    .statusCode(200)
                    .body(is("hello"));
        }
    }

    @Test
    public void testGreetingEndpoint() {
        String uuid = UUID.randomUUID().toString();
        given()
                .pathParam("name", uuid)
                .when().get("/hello/greeting/{name}")
                .then()
                .statusCode(200)
                .body(is("hello " + uuid));
    }
}
```

3. Execute `mvn clean verify`

**Environment**
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
 - Output of `mvnw --version`: 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.7, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
...
```
 - Quarkus version: 1.6.1.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**
I don't really understand the use case for @Nestled, but this
should make it work now.

Fixes #11323

### CODE REVIEW

**Comment by gsmet** [comment]
It failed in native in the modified test case. Hard to know exactly what's wrong, the logs are barely usable.

@loicmathieu I think you added some JSON logging test to the main integration tests, we need it to be in its own module as it makes things really difficult. Also, maybe I missed it but I couldn't find anything useful in the log so I wonder if we don't have an issue there.

**Comment by jaikiran** [comment]
The native tests failure appears to be this:
```
2020-08-11T23:54:59.2067142Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.852 s <<< FAILURE! - in io.quarkus.it.main.JaxbTestCase$SomeClass
2020-08-11T23:54:59.2074214Z [ERROR] io.quarkus.it.main.JaxbTestCase$SomeClass.testNews  Time elapsed: 0.001 s  <<< ERROR!
2020-08-11T23:54:59.2126405Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2020-08-11T23:54:59.2132968Z Caused by: java.lang.RuntimeException: Failed to start quarkus
2020-08-11T23:54:59.2133270Z Caused by: java.lang.RuntimeException: Unable to start HTTP server
2020-08-11T23:54:59.2136258Z Caused by: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
```

**Comment by stuartwdouglas** [comment]
Because the test class is the inner class there is no way of knowing that it is a native test, so it starts the JVM mode. I don't know if there is anything we can do about this.

**Comment by stuartwdouglas** [comment]
I am going to close this, I can't see a way to fix the native issue.

**Pull request closed without merging**
