### PR TITLE
Disable the M1 job as it's been failing consistently

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by Karm — APPROVED** [review]
Thx. I think we would need to connect our own runners to saturate the allocation :man_shrugging:

**Comment by gsmet** [comment]
@holly-cummins pinging you as it has been failing for weeks now. Not sure what to do about it? Either you can fix it in a stable way or we will just have to wait for GH to roll M1 runners.

**Comment by holly-cummins** [comment]
I've rebooted the mac, so it's now running jobs again.

**Comment by holly-cummins** [comment]
Adding this in here, so it's searchable. This is the error that crops up and needs a reboot (for now?) to fix it.

```
A job started hook has been configured by the self-hosted runner administrator
Run '/Users/githubactions/podman-start.sh'
Starting machine "podman-machine-default"
Error: dial unix /var/folders/mq/dx78dkw10dv2hb0fm0qvchqm0000gp/T/podman/qmp_podman-machine-default.sock: connect: no such file or directory
Error: Process completed with exit code 125.
```

Note that https://github.com/quarkusio/quarkus/actions/runs/3243362735/jobs/5318611709 isn't showing the error, because I rebooted the machine. :)

**Comment by holly-cummins** [comment]
We now have green builds on M1 again, and I have scheduled a reboot for midnight every Sunday. Clearly, that's not ideal, so I will raise a defect against podman (it seems slightly different from any existing issues): https://github.com/containers/podman/issues/16163

**Comment by holly-cummins** [comment]
I might have borked one build just now by trying to upgrade podman mid-build (because I can't quiesce them), but hopefully that was a one-off!

**Comment by geoand** [comment]
Closing this

**Pull request closed without merging**
