### PR TITLE
QuteProcessor - fix problem in param declaration validation

### LINKED ISSUE #6957: Qute Error with for
**Describe the bug**

Hi I have got the next POJO:

```
@TemplateData // <1>
public class Movie {


    public String name;
    public int year;
    public String genre;
    public String director;
    public List<String> mainCharacters = new ArrayList<>();
    public float ratings;


    public int getStars() { // <2>
        return Math.round(ratings);
    }
}
```
Then I am trying to print all the mainCharacters list to an html file template:

```
<dt>Main Characters:</dt>
{#for character in movie.mainCharacters} <!--5-->
{character} <!--6-->
{#if hasNext} <!--7-->
 -
{/if}
{/for}
```

If I remove the previous part the Quarkus app works correctly and the other attributes of Movie are printed but if I add the for then I got the next exception:

```
13:27:19,254 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
 [error]: Build step io.quarkus.qute.deployment.QuteProcessor#validateExpressions threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
 at org.jboss.jandex.Type.asParameterizedType(Type.java:228)
 at io.quarkus.qute.deployment.QuteProcessor.resolveType(QuteProcessor.java:701)
 at io.quarkus.qute.deployment.QuteProcessor.validateExpressions(QuteProcessor.java:267)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
 at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
 at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
 at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
 at java.base/java.lang.Thread.run(Thread.java:834)
 at org.jboss.threads.JBossThread.run(JBossThread.java:479)
 at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:181)
 at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
 at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
 at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
```

**Expected behavior**

For logic is executed.

**Actual behavior**

An exception is thrown.

**Environment (please complete the following information):**
 - Quarkus 1.2.0

**Additional context**

If it is not a bug and it is something that I have done wrong, I think that the error message should be improved so any user can fix the problem on his own.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #6957

### CODE REVIEW

**Review by lordofthejars — APPROVED** [review]
Thank you very much for the quick fix.

**Comment by gsmet** [comment]
@FroMage looks like you have an interest in Qute and it's all about `TypeVariable` so I bet you want to review that one?

**Comment by mkouba** [comment]
Note that it's about jandex TypeVariable and not the one from `java.lang.reflect`. Anyway, we will need more tests and more reviews - the current state of validation is still WIP.

**Review by FroMage — APPROVED** [review]
This looks sane.

**Pull request merged**
