### PR TITLE
Bump RESTEasy to 4.4.2.Final

### LINKED ISSUE #5752: Microprofile rest client - Can't inject config/beans to providers
**Describe the bug**
Any provider added to rest client via `@Provider` annotation is unable to inject config bean or any other application scoped bean.
```java
@RegisterRestClient
@RegisterProvider(RequestFilter.class)
public interface EchoService {....}
```
And example the provider impl:
```java
public class RequestFilter implements ClientRequestFilter {
  @Inject
  AppConfig config;  //is always null

  @Inject
  SomeBean bean; //is always null

  @Override
  public void filter(ClientRequestContext requestContext) throws IOException {...}
```

**Expected behavior**
Config or application scope bean injected and not null

**Actual behavior**
Any bean injected via `@Inject` is alway null (no errors in logs during argumentation nor during runtime.

**To Reproduce**
1. Use reproducer: https://github.com/marcinczeczko/quarkus-rest-providers-reproducer
2. `mvn compile quarkus:dev`
3. `curl http://localhost:8080/echo`
4. Check the logs - the injected config & app bean shows `null` reference

**Configuration**
- See reproducer

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```
 - GraalVM version (if different from Java): Didn't check on graalvm
 - Quarkus version or git rev: 1.0.0.Final

**Additional context**

I found out there is a closed issue for similar problem, but looks like the fix doesn't work, see: https://github.com/quarkusio/quarkus/issues/2773

### PR DESCRIPTION
**Pull request by geoand**
Fixes #5752, #5791

### CODE REVIEW

**Comment by geoand** [comment]
Seems like `org.jboss.resteasy.microprofile.client.header.IncomingHeadersProvider` is gone in `4.4.2.Final`. I am not sure how this should be handled @asoldano

**Comment by gsmet** [comment]
Well, I don't think we should remove a class in a micro release. It seems wrong.

**Comment by geoand** [comment]
I agree, let's wait and see what @asoldano says

**Comment by asoldano** [comment]
This went unnoticed because we were previously planning for a minor and then decided to do a micro as there were basically bug fixes only.
I'm on mobile and can't check for a couple of hours, but is this actually a problem here? I think I reme2mber the change came from a big fix from Stephane. If you prefer not upgrading to this version I can probably retag as 4.5.0 in the next few days. Generally speaking strict backward compatibility is granted on the spi modules only.

**Comment by geoand** [comment]
It's a problem for Quarkus because we have a class (`io.quarkus.restclient.runtime.IncomingHeadersProvider`) that extends it.

@FroMage do we absolutely need that class or can we get rid of it in Quarkus as well?

**Comment by FroMage** [comment]
This release includes a fix for https://github.com/quarkusio/quarkus/issues/4404 and that provider class was no longer useful, so we're good to upgrade.

**Comment by FroMage** [comment]
We can remove our subclass.

**Comment by geoand** [comment]
Thanks for the input @FroMage!

PR updated

**Review by asoldano — APPROVED** [review]
Thanks

**Comment by geoand** [comment]
There seems to be some issue with Spring Web that I'll need to sort out

**Comment by geoand** [comment]
@gsmet do you remember why we are on Jackson 2.9.10 instead of `2.10`? RESTEasy uses the latter (in both `4.4.1.Final` and `4.4.2.Final` so I am not sure why we are only encountering the problem in this PR and not `master`).

**Comment by geoand** [comment]
OK, so it fails in the PR because now RESTEasy uses this type (for example `Jackson2JsonpInterceptor` references it indirectly in `clinit` - which wasn't the case in `4.4.1.Final`).
So we'll need to update to Jackson 2.10.0 if we want to pick this up.

**Comment by gsmet** [comment]
We are waiting for the Vert.x team to give us the green light.

@cescoffier @vietj is there any plan to move to Jackson 2.10 soon?

**Comment by asoldano** [comment]
You should definitely move to jackson 2.10 series for security reasons...

**Comment by gsmet** [comment]
I force pushed a rebase of this one on top of the Jackson 2.10 upgrade.

**Review by gsmet — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
Merged thanks @asoldano

**Pull request merged**
