### PR TITLE
Use the GraalVM API  instead of flag to force build-time init

### PR DESCRIPTION
**Pull request by geoand**
Relates to: #17887

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by Sanne** [comment]
Looks good, but I wonder why we generate code when it's always going to be the same call? Couldn't we have an easy-to-edit automatic feature?

**Comment by geoand** [comment]
We could yeah, it's just what we have now that I changed.
We might want to look into what else the generated feature contains to see if we can move other stuff as well

**Comment by geoand** [comment]
@maxandersen are you also okay with this?

**Comment by maxandersen** [comment]
Looks ok to me. 

I have simalar thoughts as @Sanne that an explicit feature might be better in the long run.

**Comment by geoand** [comment]
Sure, we should check was I mentioned above in that direction

**Pull request merged**
