### PR TITLE
Change the order of the version property names in pom templates

### PR DESCRIPTION
**Pull request by geoand**
This is done because it's good practice but also because it helps
to make properties not conflict with Quarkus properties

### CODE REVIEW

**Comment by geoand** [comment]
This will also need to be followed up with an update to the quickstarts

**Comment by gsmet** [comment]
Hum. Please please please, start a discussion on the list before doing changes like that.

We need to agree on it.

As for it being good practice, my experience is that most of the industry uses `<component>.version`. We switched to `version.<component>` in the Hibernate project to be consistent with JBoss but this doesn't seem very widespread.

See Spring Boot dependencies bom for instance.

**Comment by geoand** [comment]
Sure thing, I'll send an email and see what people think.

**Comment by geoand** [comment]
Although certainly not a landslide, I think there reception was more positive than negative. Should we unblock and merge this?

**Comment by gsmet** [comment]
Closing this one. We won't apply it for now. We can still reopen it later if we decide to do so.

**Pull request closed without merging**
