### PR TITLE
Fix CNFE in native mode for Flyway + MSSQL

### LINKED ISSUE #21611: Mssql extensions fails in native mode with a `ClassNotFoundException`
### Describe the bug

Quarkus Upstream: `999-SNAPSHOT`

When I try to create/update a table through Flyway and `mssql` I am getting the following error in native mode:

```
22:18:42,150 INFO  [app] 22:18:39,195 Database: jdbc:sqlserver://localhost:49158;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=msdb;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 15.0)


22:18:42,150 INFO  [app] 22:18:39,197 Failed to start application (with profile prod): java.lang.ClassNotFoundException: org.flywaydb.core.internal.database.sqlserver.SQLServerDatabase
22:18:42,150 INFO  [app] 	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:71)
22:18:42,150 INFO  [app] 	at java.lang.Class.forName(DynamicHub.java:1319)
22:18:42,150 INFO  [app] 	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:62)
22:18:42,150 INFO  [app] 	at org.flywaydb.core.internal.FlywayTeamsObjectResolver.resolve(FlywayTeamsObjectResolver.java:48)
22:18:42,150 INFO  [app] 	at org.flywaydb.core.internal.database.sqlserver.SQLServerDatabaseType.createDatabase(SQLServerDatabaseType.java:95)
22:18:42,150 INFO  [app] 	at org.flywaydb.core.internal.database.base.BaseDatabaseType.createDatabase(BaseDatabaseType.java:139)
22:18:42,151 INFO  [app] 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:172)
22:18:42,151 INFO  [app] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
22:18:42,158 INFO  [app] 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:76)
22:18:42,159 INFO  [app] 	at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions2063183959.deploy_0(FlywayProcessor$createBeansAndStartActions2063183959.zig:120)
22:18:42,159 INFO  [app] 	at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions2063183959.deploy(FlywayProcessor$createBeansAndStartActions2063183959.zig:40)
22:18:42,159 INFO  [app] 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:578)
22:18:42,159 INFO  [app] 	at io.quarkus.runtime.Application.start(Application.java:101)
22:18:42,159 INFO  [app] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
22:18:42,159 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
22:18:42,159 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
22:18:42,159 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
22:18:42,159 INFO  [app] 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
22:18:44,534 INFO  [database] Service stopped (mcr.microsoft.com/mssql/rhel/server)
```

Reproducer: 
`git clone https://github.com/quarkus-qe/quarkus-test-suite.git`
cmd: `mvn clean verify -Dnative -pl sql-db/vertx-sql`

DailyBuildExample: https://github.com/quarkus-qe/quarkus-test-suite/runs/4280479399?check_suite_focus=true#step:10:1199

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #21611

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by gastaldi** [comment]
I think this may also going to happen with other DBs supported by Flyway Teams edition (where the `org.flywaydb.core.internal.FlywayTeamsObjectResolver` is used)

**Comment by gsmet** [comment]
Ah ah, funny, I was going to add the same comment.

**Comment by gastaldi** [comment]
@gsmet great minds think alike 😆

**Comment by gastaldi** [comment]
Looking at the sources it seems that SQLServerDatabaseType is the only one that uses it, so we're good

**Comment by gsmet** [comment]
I think this is due to the new changes made. I /think/ I registered all of them in the patch I had locally.

I had something like that to mimic what was done before (we included all the implementations before the upgrade to 8.0.5):
```diff
+    @BuildStep
+    void registerDatabaseTypes(CombinedIndexBuildItem combinedIndex,
+            BuildProducer<ReflectiveClassBuildItem> reflectiveClasses) {
+        for (ClassInfo databaseType : combinedIndex.getIndex().getAllKnownImplementors(DATABASE_TYPE)) {
+            if (ORACLE_DATABASE_TYPE.equals(databaseType.name())) {
+                try {
+                    // Only add the OracleDatabaseType if the driver exists
+                    Class.forName("oracle.jdbc.OracleConnection");
+                } catch (ClassNotFoundException e) {
+                    continue;
+                }
+            } else if (POSTGRESQL_DATABASE_TYPE.equals(databaseType.name())) {
+                try {
+                    // Only add the PostgreSQLDatabaseType if the driver exists
+                    Class.forName("org.postgresql.Driver");
+                } catch (ClassNotFoundException e) {
+                    continue;
+                }
+            }
+
+            System.out.println("Registering for reflection: " + databaseType.name().toString());
+
+            reflectiveClasses.produce(new ReflectiveClassBuildItem(true, true, databaseType.name().toString()));
+        }
+    }
```

Basically, this was a replacement for what was done before here: https://github.com/quarkusio/quarkus/blob/2.5/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/DatabaseTypeRegisterSubstitutions.java#L27 (this class was dropped from Flyway to use a ServiceLoader based approach).

**Comment by geoand** [comment]
> Looking at the sources it seems that SQLServerDatabaseType is the only one that uses it, so we're good

👍🏼

**Comment by gsmet** [comment]
Now maybe it's not needed, just saying what I did locally before @gastaldi did the work on his side for the 8.0.5 upgrade.

**Comment by gastaldi** [comment]
@gsmet I am not sure this fix needs to be backported. This change happens in 8.0.5 only, and that was not marked to be backported

**Comment by gastaldi** [comment]
Actually I think an easier solution is to create a `@Substitute` method that avoids the usage of `FlywayTeamsObjectResolver` completely, but that can be done in another PR

**Comment by gastaldi** [comment]
> Actually I think an easier solution is to create a `@Substitute` method that avoids the usage of `FlywayTeamsObjectResolver` completely, but that can be done in another PR

Done in https://github.com/quarkusio/quarkus/pull/21617

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/21617

**Pull request closed without merging**
