### PR TITLE
Allow Sort to be empty

### LINKED ISSUE #20329: Allow Sort to be empty
### Description

I am writing amazon lambdas using quarkus-amazon-lambda-rest, quarkus-resteasy-jackson and quarkus-hibernate-orm-panache
I have one rest endpoint that will return me a list of the entities. But I need to be able to sort that list based on a query param.

Right now my query param is a list of string where I receive 'columnName,(ASC or DSC)'

The Sort class from io.quarkus.panache.common has it constructor as private.
It requires the Sort object to always have some column. We should have way to be able to create a Sort object without defining a column. Pretty much to what spring does with Pageable.Sort.

For example, this isn't allowed

```java
 Sort sort = new Sort();

    for (String s : sortQuery) {
      String sortColumn = s.split(",")[0];
      String sortOrder = s.split(",")[1];

      sort.and(sortColumn,
          sortOrder.equalsIgnoreCase("ASC") ? Direction.Ascending : Direction.Descending);
    }
return personRepository.findByName(name, sort) 
```

### Implementation ideas

Either allow the constructor on Sort to be public or create an static method .empty().

### PR DESCRIPTION
**Pull request by javiertoja**
Fixes  #20329.

This is my first PR to an OS project, if you find any issues contact me please.

Thanks.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

Can you please rebase the PR onto `main` so there is only one commit in the UI?

**Comment by geoand** [comment]
There are plenty of resources on the web about rebasing a PR, but here is one for IntelliJ and Quarkus specifically: https://www.youtube.com/watch?v=ah9ENkAYDrY

**Comment by javiertoja** [comment]
> There are plenty of resources on the web about rebasing a PR, but here is one for IntelliJ and Quarkus specifically: https://www.youtube.com/watch?v=ah9ENkAYDrY

Thanks I will try that I'm not used to rebase

**Comment by javiertoja** [comment]
I think I'm going yo open again the PR from a clean copy of master, sorry for the mess

**Comment by geoand** [comment]
No problem :)

**Pull request closed without merging**
