### PR TITLE
Bump RESTEasy to 4.5.7.Final

### PR DESCRIPTION
**Pull request by asoldano**
Replaces #12231 and #12211

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
@asoldano / @ronsigal hi!

According to CI there's some more compilation errors, could you check them please?

here is one:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.269 s <<< FAILURE! - in io.quarkus.restclient.ft.AsyncRestClientFallbackTest
[ERROR] io.quarkus.restclient.ft.AsyncRestClientFallbackTest.testFallbackWasUsed  Time elapsed: 0.003 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problems: 
	The import org.jboss.resteasy.client.jaxrs.engines cannot be resolved
	The import org.jboss.resteasy.client.jaxrs.internal cannot be resolved
	LocalResteasyProviderFactory cannot be resolved to a type
	The method providerFactory(ResteasyProviderFactory) is undefined for the type MpClientBuilderImpl
	The method getConfiguration() is undefined for the type MpClientBuilderImpl
	The method register(ExceptionMapping, int) is undefined for the type MpClientBuilderImpl
	The method defaultProxy(String, int) is undefined for the type MpClientBuilderImpl
	The method defaultProxy(String, Integer, String) is undefined for the type MpClientBuilderImpl
	The method defaultProxy(String, int) is undefined for the type MpClientBuilderImpl
	Type mismatch: cannot convert from MpClientBuilderImpl to ResteasyClientBuilder
	URLConnectionClientEngineBuilder cannot be resolved to a type
```

The others seem similar, probably all related - although I didn't check them all.

**Comment by geoand** [comment]
Seems like the Java tests failed

**Comment by asoldano** [comment]
@geoand @Sanne I'm having a look soon...

**Comment by ronsigal** [comment]
Please see https://github.com/quarkusio/quarkus/pull/12211. Some changes in RESTEasy 4.5.7.Final caused some test failures. With the changes in https://github.com/quarkusio/quarkus/pull/12211 and RESTEasy upgraded to 4.5.7.Final, the Quarkus testsuite passed for me on my laptop.

Maybe the changes in https://github.com/quarkusio/quarkus/pull/12211 should be applied to this PR?

**Comment by asoldano** [comment]
@ronsigal I actually included your changes. Did you run the whole testsuite?

**Comment by asoldano** [comment]
I don't know (at least yet) how to explain this, but I was able to reproduce the problem (using RegisterClientHeadersTest), then I've re-built RESTEasy 4.5.7.Final locally and the failures are gone..

**Comment by ronsigal** [comment]
Hi @asoldano,

re: "Did you run the whole testsuite?"

I think so. I went into the main quarkus directory and just did mvn install. I think it took about an hour and a half.

**Comment by ronsigal** [comment]
Hmmm. I ran the testsuite before the release, so I was using my local RESTEasy 4.5.7.Final. I'll delete it from the repository and run the testsuite again.

**Comment by ronsigal** [comment]
Well, this is strange. I'm getting

Caused by: java.lang.Error: Unresolved compilation problems: 
	The import org.jboss.resteasy.client.jaxrs.engines cannot be resolved

in quarkus/extensions/rest-client/deployment, even though mvn dependency:tree shows

```
[INFO] io.quarkus:quarkus-rest-client-deployment:jar:999-SNAPSHOT
[INFO] +- io.quarkus:quarkus-core-deployment:jar:999-SNAPSHOT:compile
[INFO] |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
...
[INFO] +- io.quarkus:quarkus-rest-client:jar:999-SNAPSHOT:compile
[INFO] |  +- org.jboss.resteasy:resteasy-client-microprofile:jar:4.5.7.Final:compile
[INFO] |  |  +- org.jboss.resteasy:resteasy-client:jar:4.5.7.Final:compile

I'm going to start with a clean copy and try again.

**Comment by ronsigal** [comment]
I got the same result again. However, when I build RESTEasy 4.5.7.Final locally, the Quarkus testsuite has gotten past the failures I had before. 

Maybe I should re-deploy the 4.5.7.Final jars.

@asoldano, did you see the same failure ("The import org.jboss.resteasy.client.jaxrs.engines cannot be resolved")?

**Comment by asoldano** [comment]
@ronsigal , unfortunately (or luckily, depending on the circumstances) you can't re-deploy the same artifacts, so 4.5.8.Final is needed.

**Comment by ronsigal** [comment]
@asoldano, ok. I wish I knew what went wrong, but I'll try again.

**Comment by ronsigal** [comment]
@asoldano, what about a 4.5.7.1.Final?

**Comment by ronsigal** [comment]
Well, just looking at repository.jboss.org, I don't see much use of a "nano" version, so I'll do 4.5.8.Final. A question that I don't need to resolve right now is: Should 4.5.7.Final just disappear, in the sense that I move all of the 4.6.7.Final JIRAs to 4.5.8.FInal?

**Comment by ronsigal** [comment]
I started the Quarkus testsuite with RESTEasy 4.5.8.Final, and it failed. I started it again, and it got near the end, passed 1679 tests, and then failed in one of the gRPC modules. I continued from there and it passed. Strange.

I'm going to run the TCK now, even though it feels like overkill.

**Comment by ronsigal** [comment]
TCK passed.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
There a failures in `Quarkus - REST Client - Deployment`

**Comment by ronsigal** [comment]
I've deployed RESTEasy 4.5.8.Final to Nexus, but I'm having trouble testing it. Quarkus master + this PR + 4.5.8.Final keeps failing for me in unexpected ways, and I don't have permission to update this PR. 

I've submitted https://github.com/quarkusio/quarkus/pull/12270 with the same changes exception RESTEasy 4.5.8.Final.

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/12270

**Pull request closed without merging**
