### PR TITLE
VertxProducer - simplify code, get rid of synchronization

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
Is there really a good reason to backport that one? Doesn't look really needed?

**Comment by mkouba** [comment]
@gsmet Well, you're probably right. A workaround exists - just inject `io.vertx.mutiny.core.Vertx` anywhere. And even without the workaround - the `@PreDestroy` callbacks declared on bean Verticles should work. The problem should only occur if the Verticle injects some `@Singleton` beans or its `stop()` method contains some logic that calls injected client proxies.

**Comment by mkouba** [comment]
> Is there really a good reason to backport that one? Doesn't look really needed?

Hm, on the other hand, it would be nice to have this fix in 1.5...

**Comment by gsmet** [comment]
@mkouba well, it's not very clear it fixes something? It just looks like some housekeeping. A description would have helped.

**Comment by mkouba** [comment]
@gsmet I'm sorry. So the original commit was indeed a small refactoring. But it turns out that it fixes a bug described in the referenced issue: https://github.com/quarkusio/quarkus/issues/9456#issuecomment-631442544.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@mkouba OK, let's backport it then, thanks for the clarification!

**Pull request merged**
