### PR TITLE
Fix vert-x CORS Filter to allow non-CORS OPTIONS requests

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
The previous implementation assumed that all OPTIONS requests were cors requests, and terminated them early, this fixes that, by ensuring that we're actually receiving a CORS request (presence of Origin and Access-Control-Request-* headers).

Included is a full set of test cases for the existing and changed behaviour. If you revert the change to CORSFilter.java, then you can see the bug.

See: #21181 for the source issue

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks

**Comment by sberyozkin** [comment]
@ThisIsMissEm I'd like to wait till tomorrow and see if @stuartwdouglas or @ia3andy and others have some concerns.
It is a good fix IMHO.

**Comment by ThisIsMissEm** [comment]
@sberyozkin okay, sure! There's no rush from my end, it was just an interesting rabbit hole to solve and write a fix for.

As mentioned, I'm not usually a java developer, so I do really welcome PR review feedback :)

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
LGTM, thanks for the fix

**Pull request merged**
