### PR TITLE
Fix backtick/tick issue a bit cleaner

### PR DESCRIPTION
**Pull request by mejlholm**
Previous issue here:

https://github.com/quarkusio/quarkus/pull/4388

### CODE REVIEW

**Review by machi1990 — COMMENTED** [review]
I noticed that the PR has two commits, one from your previous PR I guess. Can we squash the two commits? Otherwise LGTM but I’ll let @gsmet re-review this.

**Comment by geoand** [comment]
Thanks for the improvement @mejlholm! Like @machi1990 let's a single commit please.

**Comment by gsmet** [comment]
I'm closing this one, the history is all weird and I have a couple more fixes to apply. I will open another PR.

@mejlholm I recommend you to create one branch per PR and to rebase them on master each time. It should avoid this sort of problems.

Thanks anyway :).

**Comment by mejlholm** [comment]
No worries, I’ll default to creating branches.

**Pull request closed without merging**
