### PR TITLE
Add CORS documentation for Keycloak

### PR DESCRIPTION
**Pull request by sebastienblanc**
fixes #3181

### CODE REVIEW

**Comment by machi1990** [comment]
@sebastienblanc I think this warning note is worth updating
https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/undertow-reference.adoc#L78

**Comment by sebastienblanc** [comment]
@machi1990 Well this warning is still valid.

**Comment by machi1990** [comment]
> @machi1990 Well this warning is still valid.

Yes, it is still valid. I was just proposing adding a link to this added section on how to configure cors for Keycloak.

**Comment by sebastienblanc** [comment]
Good point , will do that

**Review by gsmet — CHANGES_REQUESTED** [review]
Looks good to me. I agree having a link from the Undertow reference would be nice.

I let you add that?

**Comment by sebastienblanc** [comment]
added the link

**Review by machi1990 — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Pull request merged**
