### PR TITLE
Upgrade es-module-shims to 1.8.1

### LINKED ISSUE #36742: DevUI resource error on main
### Describe the bug
After going to `localhost:8080/q/dev`

I'm seeing 

```
2023-10-27 11:16:57,239 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /q/_static/es-module-shims/1.8.0/dist/es-module-shims.js failed, error id: 9a1f2cf7-934b-48ba-9082-f41923430066-2: java.lang.NullPointerException: Cannot invoke "java.net.URL.openConnection()" because "url" is null
	at io.quarkus.devui.runtime.MvnpmHandler.handle(MvnpmHandler.java:48)
	at io.quarkus.devui.runtime.MvnpmHandler.handle(MvnpmHandler.java:25)

```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

I've seen it in `mvn quarkus-dev` in the `security-openid-connect-quickstart` quickstart, may also be a problem for other demos.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix the error in the log when loading dev-ui
/cc @metacosm 

Fixes #36742

### CODE REVIEW

**Comment by gsmet** [comment]
@phillip-kruger could you explain how this fixes the issue? Will we be hit by the same issue later?

**Comment by sberyozkin** [comment]
I added `Fixes #36742` but the question is good. Phillip, if you think `Fixes #36742` is not good for this PR then please remove it

**Comment by phillip-kruger** [comment]
I am not sure what happened with 1.8.0, but the jar that was sync to central still had the old format (without the version). Locally it was fine but must have been synced from mvnpm. 1.8.1 is fine in central, so the issue will be gone going forward. Hope that explain this. This does not break Dev UI for most cases. `es-module-shims` is added to support older browsers that does not support modules.

**Comment by phillip-kruger** [comment]
Thanks @sberyozkin - yes this will fix that issue

**Review by gsmet — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
