### PR TITLE
CLI - reduce the startup time

### PR DESCRIPTION
**Pull request by mkouba**
- do not set CommandLine.setUsageHelpLongOptionsMaxWidth(); a side
effect of this option is that picocli attempts to detect the terminal
size which is quite expensive
- do not detect unused removed beans false posititives at runtime

### CODE REVIEW

**Comment by mkouba** [comment]
FTR this is the `qs -h` output diff. Before:
```
Usage: qs [-ehV] [--verbose] [COMMAND]
  -e, --errors    Produce execution error messages.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
      --verbose   Verbose mode.
Commands:
  build             Build your quarkus project
  clean             Clean current project
  create            Create a new quarkus project.
  create-jbang      Create a new quarkus jbang project.
  list              List installed (default) or installable extensions.
  platforms         List imported (default) or all available Quarkus platforms.
  add               Add extension(s) to current project.
  remove, rm        Remove an extension from this project.
  dev               Execute project in live coding dev mode
  create-extension  Creates the base of a Quarkus extension in different layout
                      depending of the options and environment.
```
After:
```
Usage: qs [-ehV] [--verbose] [COMMAND]
  -e, --errors    Produce execution error messages.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
      --verbose   Verbose mode.
Commands:
  build             Build your quarkus project
  clean             Clean current project
  create            Create a new quarkus project.
  create-jbang      Create a new quarkus jbang project.
  list              List installed (default) or installable extensions.
  platforms         List imported (default) or all available Quarkus platforms.
  add               Add extension(s) to current project.
  remove, rm        Remove an extension from this project.
  dev               Execute project in live coding dev mode
  create-extension  Creates the base of a Quarkus extension in different layout depending of the options and environment.
```

**Comment by gsmet** [comment]
> do not detect unused removed beans false posititives at runtime

how is it a problem for the CLI and not for your typical Quarkus applications?

**Comment by mkouba** [comment]
> > do not detect unused removed beans false posititives at runtime
> 
> how is it a problem for the CLI and not for your typical Quarkus applications?

Well, it's not such a big problem but the generated `io.quarkus.arc.ComponentsProvider` contains info about every removed bean and we want to reduce the size of the CLI uber-jar (which is currently huge) and attempt to reduce the number of loaded classes.

We could probably initialize the set of removed beans lazily but I'm not sure it's worth it.

**Comment by mkouba** [comment]
Actually, it seems that all CLI commands use `@CommandLine.Command(usageHelpAutoWidth = true)`. So this PR will only help to reduce the startup time of `qs -h` :-(.

**Review by maxandersen — APPROVED** [review]
makes sense to me - i dont spot formatting differences either.

LGTM!

**Comment by maxandersen** [comment]
@patriot1burke might remember why he put the formatting widths in place - but in any case I think we should do everything we can do avoid relying on the expensive width call.

**Review by ebullient — APPROVED** [review]

**Pull request merged**
