### PR TITLE
PostgreSQL JDBC, MariaDB JDBC upgrade

### PR DESCRIPTION
**Pull request by rsvoboda**
PostgreSQL JDBC, MariaDB JDBC upgrade

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Waiting for CI.

**Review by gsmet — CHANGES_REQUESTED** [review]
The native build failed with the following error:
```
quarkus-integration-test-main-999-SNAPSHOT-runner:20]        setup:     801.32 ms
Error: could not find target method: private static synchronized void io.quarkus.narayana.jta.runtime.graal.ConfigurationInfoSubstitution.getBuildTimeProperties()
com.oracle.svm.core.util.UserError$UserException: could not find target method: private static synchronized void io.quarkus.narayana.jta.runtime.graal.ConfigurationInfoSubstitution.getBuildTimeProperties()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:633)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:326)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:298)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:863)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:817)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:520)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by rsvoboda** [comment]
Scope of this PR limited just to JDBC drivers.

Narayana to be solved separately, issue linked.

**Review by gsmet — APPROVED** [review]

**Comment by rsvoboda** [comment]
Windows failure doesn't seem to be PR related. It's "good old timeout".
```
[INFO] Running io.quarkus.maven.it.RemoteDevMojoIT
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 297.062 s <<< FAILURE! - in io.quarkus.maven.it.RemoteDevMojoIT
[ERROR] testThatTheApplicationIsReloadedOnJavaChange  Time elapsed: 77.649 s  <<< ERROR!
java.lang.RuntimeException: org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.maven.it.RemoteDevMojoIT was not fulfilled within 1 minutes.
	at io.quarkus.maven.it.RemoteDevMojoIT.runAndCheck(RemoteDevMojoIT.java:217)
	at io.quarkus.maven.it.RemoteDevMojoIT.testThatTheApplicationIsReloadedOnJavaChange(RemoteDevMojoIT.java:51)
Caused by: org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.maven.it.RemoteDevMojoIT was not fulfilled within 1 minutes.
	at io.quarkus.maven.it.RemoteDevMojoIT.runAndCheck(RemoteDevMojoIT.java:215)
	at io.quarkus.maven.it.RemoteDevMojoIT.testThatTheApplicationIsReloadedOnJavaChange(RemoteDevMojoIT.java:51)
```

**Pull request merged**
