### PR TITLE
Remove Servlet specific auth from JAX-RS

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This is no longer needed after the changes in how challenges are handled.

Partial fix for #5419

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@gsmet FYI

**Comment by geoand** [comment]
The test failure seems related

**Review by sberyozkin — COMMENTED** [review]
LGTM

**Review by sberyozkin — APPROVED** [review]

**Comment by gsmet** [comment]
I rebased it as the first commit was included in another PR.

**Comment by gsmet** [comment]
I just rebased and force-pushed.

**Pull request merged**
