### PR TITLE
Small workflow adjustments

### PR DESCRIPTION
**Pull request by gsmet**
Disabling `cancel-previous-runs` as the bot will take care of this from now on.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by famod — APPROVED** [review]

**Comment by famod** [comment]
This needs a rebase/conflict resolution.

That one failure is a known one: #16416

**Comment by famod** [comment]
Offtopic: @gsmet could the bot also detect merge conflicts? I happened more than once to me that I didn't realize I had a conflict in one of my PRs...

**Comment by gsmet** [comment]
> Offtopic: @gsmet could the bot also detect merge conflicts? I happened more than once to me that I didn't realize I had a conflict in one of my PRs...

Yeah, I thought about it, the other day. I think it would be doable. There is a `mergeable` thing on the PR object but its behavior is a bit weird.

**Comment by gsmet** [comment]
Rebased.

**Comment by famod** [comment]
@gsmet It just occured to me that in forks people are on their own now, meaning that you have to cancel runs yourself after a push (because the bot doesn't cover forks).
I think we should bring back the action, but limit it to forks. WDYT?

**Comment by gsmet** [comment]
Yeah, why not.

**Pull request merged**
