### PR TITLE
fix: NotFoundExceptionMapperTestCase fails on some environments

### LINKED ISSUE #5424: NotFoundExceptionMapperTestCase fails on some environments
**Describe the bug**
The two tests in `io.quarkus.resteasy.test.NotFoundExceptionMapperTestCase` added by @machi1990 which replace resources and expect to see the changed resources fail in some environments and not in others.

@kenfinnigan added some sleeps to these tests which seemed to fix the problems sometimes, yet the problem is still not consistently fixed.

The problem may be due to inadequate resolution of file and/or directory time stamps.  This was a known problem in Java 8 (where the test fails for me) that was fixed in Java 11 (where the test does not fail for me).

The commit which introduced the problematic test was d81e508b6fb543724bd526c01304c28ebedc3d8f.  The commit which added the sleeps was 24876d0b7a9be4445f4ee4188f97aba4dc9cd1cb.

**To Reproduce**
1. Run this test class on Java 8, hopefully the problem reappears.  Removing the sleeps might be necessary.

### PR DESCRIPTION
**Pull request by machi1990**
Fixes #5424 

/cc @dmlloyd can you have a look? Thanks.

### CODE REVIEW

**Review by dmlloyd — COMMENTED** [review]
I'm not really sure whether or not this fixes the problem.  I don't see anything that looks like a mistake per se, but someone who is more familiar with this area should review the change.

**Comment by machi1990** [comment]
> I'm not really sure whether or not this fixes the problem. I don't see anything that looks like a mistake per se, but someone who is more familiar with this area should review the change.

Thanks David for the feedback. I should probably ping @stuartwdouglas for a review. Were you able to quick launch the scripts that ran the failing tests in question and see if the issue was fixed? Thanks

**Comment by dmlloyd** [comment]
I'm in the middle of a big ugly checkout/rebase right now so I can't verify this right away.

**Comment by gsmet** [comment]
@jaikiran any chance you could have a look at this one before the end of the week? It would be nice to have it in 1.1.0.

If not, just drop me a note and I'll see if Stuart or I can have a look.

Thanks!

**Comment by jaikiran** [comment]
Hello @gsmet, this turned out to be a test framework issue. I've opened https://github.com/quarkusio/quarkus/pull/5913 to fix this and have added @dmlloyd and @machi1990 as reviewers. @machi1990, can you please take a look at the other PR and see if it's good enough?

**Comment by machi1990** [comment]
Hey @jaikiran thanks for taking care of this one and for proposing a reliable fix. 
Let me close this one in favor of your PR.

**Pull request closed without merging**
