### PR TITLE
Bump kubernetes-client-bom from 5.11.2 to 5.12.0

### PR DESCRIPTION
**Pull request by manusa**
Kubernetes Client 5.12.0 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v5.12.0

Just speeding up the dependabot process to see if CI reports any issue.

/cc @metacosm

### CODE REVIEW

**Comment by gsmet** [comment]
@manusa @metacosm is it something we want in 2.7? Given we already released CR1, we need to make sure there is no backward incompatibility.

/cc @geoand

**Comment by geoand** [comment]
And if we want it, it needs to go in with a full CI run passing ASAP

**Comment by manusa** [comment]
AFAIK there shouldn't be any breakages. This version introduces new features (a couple of new extensions + the Kubernetes model update to 1.23).

Shall I create a PR to 2.7 branch?

**Comment by geoand** [comment]
> No need, we will backport it

**Comment by metacosm** [comment]
Getting it in 2.7 would be nice assuming it doesn't break anything 😅

**Review by geoand — APPROVED** [review]

**Pull request merged**
