### PR TITLE
Make updating a built application to k8s a no-brainer

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by iocanel — APPROVED** [review]
LGTM

**Review by maxandersen — CHANGES_REQUESTED** [review]
idea is good as from developer perspective its annoying not getting latest changes on a push.

I'm aok on the changes, but I reckon we should document how to turn this off in a prod profile ?

**Review by maxandersen — APPROVED** [review]
lets get this in and update docs as we get them more complete

**Comment by geoand** [comment]
I'll be looking at the docs tomorrow and then next week and plan to add some "how to" style additions to it, one of which would address the above comment.

**Pull request merged**
