### PR TITLE
GraphQL Field level context and error event on blocking fixes

### LINKED ISSUE #1530: EventingService.errorDataFetch not called on failed synchronous graphql operations
For synchronous graphql operations exceptions thrown does not result in invocations of `EventingService.errorDataFetch`.
Changing to `Uni<T>` gives the expected behaviour.

[Reproducer](https://github.com/computerlove/missing-error-eventingservice)

### LINKED ISSUE #27628: GraphQL fails to get current request using CDI.current().select(HttpServerRequest.class)
### Describe the bug

GraphQL fails to get current request using CDI.current().select(HttpServerRequest.class)

fails with 

    javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=io.quarkus.vertx.http.runtime.CurrentRequestProducer, id=c786212c50efeac37ecc96f8570579f64be3bb5b]
            - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
            at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:53)
            at io.vertx.core.http.CurrentRequestProducer_ProducerMethod_getCurrentRequest_05f950ea7ab91d121ba0bac525b89d62f3261b2d_ClientProxy.arc$delegate(Unknown Source)
            at io.vertx.core.http.CurrentRequestProducer_ProducerMethod_getCurrentRequest_05f950ea7ab91d121ba0bac525b89d62f3261b2d_ClientProxy.getHeader(Unknown Source)

### Expected behavior

work same as in 2.11.1

### Actual behavior

Exception is thrown

### How to Reproduce?

https://github.com/deedarb/graphql-error-reproducer-1

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.12.0 or 2.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

### Additional information

maybe related to https://github.com/quarkusio/quarkus/pull/27147

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #27628
Fix https://github.com/smallrye/smallrye-graphql/issues/1530

see https://github.com/smallrye/smallrye-graphql/releases/tag/1.7.1

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by jmartisk — APPROVED** [review]

**Comment by gsmet** [comment]
@jmartisk @phillip-kruger this update is missing the Jakarta counterpart. Could you fix it and make sure it doesn't happen again? Thanks.

Also, as reported elsewhere, I suspect this patch is triggering the context leaks again. See https://github.com/quarkusio/quarkus/pull/27742#issuecomment-1237596991 .

**Comment by gsmet** [comment]
Hmmm, the update is there but the tests are failing with a weird class error. I will report back here when I know more.

**Comment by gsmet** [comment]
Yeah, so sorry about the confusion. Apparently, it's still the `BeanManager#fireEvent` thing being an issue. Which is weird given I can see the fix in the released branches. I'm trying to understand what's going on.

**Comment by gsmet** [comment]
Oh, my, I think I will go back to bed. Doesn't look like a good day... I was looking in the history to better understand things and ended up working on an old report...

So the current issue at hand is a NPE when we try to index a GraphQL class.

This is because we have both Jandex versions in the classpath when GraphQL is around and the new Jandex is taking precedence, returning null when a class is indexed:
```
[INFO] |  |  \- io.smallrye:jandex:jar:3.0.0:compile
[INFO] |  |  \- org.jboss:jandex:jar:2.4.3.Final:test
```

@Ladicek I wonder if we should push the fix to `IndexingUtil` (`classInfo = indexer.index(stream);`) right now as a quick workaround. We could add exclusions but you would have to remove them soon so I don't think that would be ideal.

Asking because having the report full of unrelated failures makes things a bit harder for me.

**Comment by Ladicek** [comment]
Ah it's the Jakarta variant of SmallRye GraphQL that already depends on Jandex 3. Humpf...

**Comment by gsmet** [comment]
@Ladicek yeah, exactly. I don't think it's worth spending much time on this given we will merge the Jandex upgrade on Sep 14th or around that. But if the `IndexingUtil` fix makes it work, maybe it's worth pushing just that (provided it's not risky)?

**Comment by Ladicek** [comment]
In my Jandex 3 branch, I had to change `IndexingUtil` to use a Jandex 3 API, so that can't be directly ported to the Jakarta branch. However, looking at the SmallRye GraphQL changes I did to upgrade to Jandex 3, it should still be compatible at runtime with Jandex 2.4.3. So adding a dependency exclusion would likely be easiest at the moment.

**Comment by gsmet** [comment]
OK, I'll think about it. Not sure it's worth it. If I prepare a PR with an exclusion, I'll ping you there so you can adjust your Jandex 3 PR to remove it.

**Pull request merged**
