### PR TITLE
Support modules with non-empty default classifier

### LINKED ISSUE #24697: DEV mode fails when using classified dependencies
### Describe the bug

My project uses a maven dependency (jar) that has a <classifier>. The project compiles, tests, and executes just fine. But the Quarkus DEV mode fails to start because of an exception while assembling the project.

### Expected behavior

Quarkus DEV mode should work as expected even if some dependencies use a classifier to select the proper jar.

### Actual behavior

"mvn clean quarkus:dev -X" leads to the following error:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:dev (default-cli) on project classifier-test: Failed to run
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run
    at io.quarkus.maven.DevMojo.execute (DevMojo.java:432)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NullPointerException
    at io.quarkus.maven.DevMojo.addProject (DevMojo.java:703)
    at io.quarkus.maven.DevMojo.newLauncher (DevMojo.java:990)
    at io.quarkus.maven.DevMojo$DevModeRunner.<init> (DevMojo.java:820)
    at io.quarkus.maven.DevMojo.execute (DevMojo.java:386)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

### How to Reproduce?

The attached project is a maven wrapper project with two children:
- a small library which contains an injectable CDI bean. This project uses a classifier for the produced Jar.
- a Quarkus application with a greeting resource, that uses the (classified) JAR as a dependency.

1. Build the whole project with `mvn clean install`
The library and the quarkus app will build just fine. The Quarkus tests are executed successfully, injecting the bean from the qualified jar and returning the proper response.

2. Now try to start dev mode using `mvn quarkus:dev -f qualifier-test`
The application will not start. Instead an exception from the quarkus plugin in thrown.

[classifier.zip](https://github.com/quarkusio/quarkus/files/8399277/classifier.zip)

### Output of `uname -a` or `ver`

Mac OS 12.3 

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 LTS

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

Explanation, why we are using qualifiers:
In the real world, we have a support library that provides a couple of common Quarkus features to our microservices. In order to ensure full compatibility (and because our services don't all use the same Quarkus version), we compile this library multiple times using different Quarkus versions, putting the used Quarkus version as the qualifier.
So module A will use the library with qualifier <2.7.5.Final> to fetch the version of the library compiled against Quarkus 2.7.5.Final, while module B will use the version with qualifier <2.7.4.Final> because it still uses Quarkus 2.7.4

### PR DESCRIPTION
**Pull request by aloubyansky**
Fix #24697

### CODE REVIEW

**Comment by famod** [comment]
I'll try to find some time for this tomorrow.

**Review by famod — APPROVED** [review]

**Comment by famod** [comment]
@aloubyansky this seems to have an unexpected (?) side effect:
In 2.8.1 (when running tests) the following is returing a "jar:file:" URL whereas in 2.8.0 it was returning a "file" URL:
```java
final var resource = Thread.currentThread().getContextClassLoader().getResource(resourceName);
```
This is only the case if the resource is located in an upstream module (e.g. resource in module A, test is run in B and B depends on A).
If the test is run in the same module where the resource is located (e.g. all in module A), then it works as before.

WDYT?

**Comment by aloubyansky** [comment]
So it is finding the resource in the JAR instead of the directory? Do you think you can adapt one of your reproducers to show the difference between two versions?

**Comment by famod** [comment]
> So it is finding the resource in the JAR instead of the directory?

Exactly.

> Do you think you can adapt one of your reproducers to show the difference between two versions?

I've failed to do so for now. There must be more to it...

**Comment by famod** [comment]
@aloubyansky I tried a few more things whithout any luck.

So I changed the code in question to create a new `FileSystem` and get the `Path` from that (instead of directly via `Path.of(URI)`) and that works as expected, but during implementation I found an even bigger issue:
Via Eclipse, in module A I adjusted the code mentioned above in that I added a new method ot a class called `ResourceLoader` and used it in `MariaDBContainerQuarkusLifecycleManager`, instead of the now faulty method.
Then I ran the test in module B and all of a sudden I was getting `NoSuchMethodError`.

Turns out that when _no_ test was run before via `mvn`, running that test in IDE is just fine - without adjusting anything!
But as soon as I run that test via `mvn` (which fails), test execution fails in IDE as well.
That's when I remembered `test-app-model.dat`. When I delete it after `mvn`, IDE is back to normal.
Unsurprisingly, next `mvn` run (with `clean test`) fails again, also again breaking IDE.
Consequently, running `mvn test` with out `clean` is fine as well. So the problems start when `test-app-model.dat` is created via `mvn` (not via IDE).

How does the above relate to `NoSuchMethodError`? Well, deleting `test-app-model.dat` (thatw as created by `mvn`) also fixes that issue.
I suppose `test-app-model.dat` told test execution in Eclipse to load the respective class from the jar, but as Eclipse is doing workspace resolution and is not doing any `install`, things got inconsistent.
(Of course, at some pint I ran `mvn install` on module A, which also "fixed" that issue.)

**Comment by famod** [comment]
FYI @stuartwdouglas ⬆️

**Comment by aloubyansky** [comment]
Thanks @famod for all the info. Is the JAR the class is loaded from in the module's target dir or the local Maven repo?
When you run tests in module B from the command line, has the module A been built?
Do you use Maven profiles? Does dependency on module A come from a profile?

**Comment by famod** [comment]
> Is the JAR the class is loaded from in the module's target dir or the local Maven repo?

It's (simplified) `A/target/A.jar` via `mvn` and `A/target/classes` via Eclipse. (I have to say though that I checked it with the resource I mentioned initially, because `class.getProtectionDomain().getCodeSource().getLocation()` wasn't giving me anything useful).
So
> but as Eclipse is doing workspace resolution and is not doing any `install`

is misleading here, I should have said that Eclipse is not assembling a jar.

> When you run tests in module B from the command line, has the module A been built?

Usually yes, but at some point it wasn't with the latest changes. My main concern here is that IDE should not be influenced by the different/limited/absent workspace resolution of the command line execution.

> Do you use Maven profiles?

In general yes, but nothing specific in this case.

> Does dependency on module A come from a profile?

There are two dependencies on A from B: A "regular" compile one and a test-jar one. But both are _not_ in a profile.
There is a third dependency on A ("mocks" classifier) in a profile, but that profile is not active in this case.
I tried to mimic that in a reproducer but it didn't lead to what I'm seeing in my real project.

**Comment by famod** [comment]
Btw, removing `test-app-model.dat` between test runs yields a 2 seconds runtime penalty in my case. So simply dropping it (as we discussed before) might not be the best idea.

**Comment by famod** [comment]
I was also trying to wrap my head around how this PR is causing that URI change and I was suspecting the following in my root pom.xml to be related (in pluginManagement):
```xml
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${jar-plugin.version}</version>
                    <configuration>
                        <excludes>
                            <exclude>application-dev.yaml</exclude>
                        </excludes>
                    </configuration>
                </plugin>
```
But again, adding that to the small sample project didn't reproduce it either.

**Comment by famod** [comment]
Ok, so this is the root cause of the URI change for my setup:
https://github.com/quarkusio/quarkus/blob/2.8.1.Final/independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/workspace/DefaultWorkspaceModule.java#L164-L165
This is kicking in for A (when running tests via `mvn` in B), because two source sets are present: `test` and `mocks`. Thing is, `mocks` is also a test-jar result and so the check is incorrect at this point.
It is therefore not entering the following block anymore:
https://github.com/quarkusio/quarkus/blob/2.8.1.Final/independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java#L368-L371
so it's missing an "ArtifactSources".

I don't see how `DefaultWorkspaceModule.this.sourcesSets` can be used to differentiate that case, at least not without adding some info where that set is coming from (so to say).

**Comment by famod** [comment]
PS: What I don't understand at this point (might just be too late), is why the URI is unchanged in Eclipse (compared to 2.8.0), given that it's also mising that MAIN "ArtifactSources".

**Comment by aloubyansky** [comment]
Oh, ok, thanks @famod

**Comment by aloubyansky** [comment]
https://github.com/quarkusio/quarkus/pull/25086 should fix it

**Pull request merged**
