### PR TITLE
Make ValidatorFactory and Validator singleton beans

### PR DESCRIPTION
**Pull request by gsmet**
Created as draft to get CI feedback and because I will wait for https://github.com/quarkusio/quarkus/pull/26997 to get in.

### CODE REVIEW

**Comment by manovotn** [comment]
@gsmet I'll just add these changes as a separate commit into https://github.com/quarkusio/quarkus/pull/26997 :)

**Comment by gsmet** [comment]
@manovotn ah sorry, I just saw your message, I merged it as CI was green and I'm not completely sure this one will go in :). I'll adjust the small things in there.

**Comment by manovotn** [comment]
> @manovotn ah sorry, I just saw your message, I merged it as CI was green and I'm not completely sure this one will go in :). I'll adjust the small things in there.

Hehe, good timing; I was literally just pushing these changes into the PR. Doesn't matter though.

I think this change makes sense as I didn't come across any piece of code that would use `Validator` and somehow required that it should be dependent. If you have any further CDI questions, fire away :)

**Review by manovotn — APPROVED** [review]
Looks good.
I don't think it is worth a backport, but I'll leave that up to you.

**Pull request merged**
