### PR TITLE
Fix remaining case for Windows path issues on dev mode reload

### LINKED ISSUE #3592: Hot reload fails with InvalidPathException on Windows
Starting with Quarkus 0.21.0 hot reload failes with InvalidPathException (at least) on Windows.

When a Quarkus application runs in dev mode, i. e. using mvn quarkus:dev, a REST call will trigger a hot reload, if one of the source files has changed before. That worked like a charm up to version 0.20.0. With 0.21.0 the REST response contains an error message:

`<header>
    <h1 class="container">Error restarting Quarkus</h1>
    <div class="exception-message">
        <h2 class="container">java.nio.file.InvalidPathException: Illegal char &lt;:&gt; at index 2: /C:/Users/dw/.m2/repository/io/quarkus/arc/arc/0.21.0/arc-0.21.0.jar</h2>
    </div>
</header>`

As the message complains about the ':' in the file path, I guess, the problem arises on Windows only.

The bug can easily be reproduced:
- Use any of the applications from the guide, e. g getting-started
- Make sure that quarkus.version in pom.xml is 0.21.0
- Build the application and start dev mode (mvn clean package quarkus:dev)
- Make some code change
- Call a REST endpoint (curl http://localhost:8080/hello)

My environment:
- Windows 10 Pro
- AdoptOpenJDK 8 (jdk8u202-b08) and 11 (jdk-11.0.3+7)

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #3592

### CODE REVIEW

**Comment by geoand** [comment]
Looks like imports were not properly formatted

**Comment by dmlloyd** [comment]
Fixed...

**Comment by geoand** [comment]
I don't have a Windows machine to test, but this seems reasonable to me. Perhaps someone with a Windows machine could give it a quick check?

**Comment by dmlloyd** [comment]
Someone other than me I guess. :)  I did verify this on a Windows machine personally.

**Comment by geoand** [comment]
Good enough for me then :)

**Review by geoand — APPROVED** [review]

**Pull request merged**
