### PR TITLE
Support fault tolerance and load balance with vert.x pool of reactive mysql client

### LINKED ISSUE #31492: Loadbalance for reactive mysql client
### Description

There is built-in loadbalance support from MySQL Connector/J driver, so we can write `quarkus.datasource.jdbc.url=jdbc:mysql:loadbalance://192.168.32.101,192.168.32.102/dbname` in application.properties to take the advantage of load balance.

For reactive mysql client similar config not work because vert.x mysql client not support the `loadbalance` keyword within url. But vert.x do support server load balance. https://vertx.io/docs/vertx-mysql-client/java/#_advanced_pool_configuration

Do we have any plan to support config like this? `quarkus.datasource.reactive.url=mysql:loadbalance://192.168.32.101,192.168.32.102/dbname`

### Implementation ideas

update io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder, change `MySQLPool.pool(Vertx vertx, MySQLConnectOptions database, PoolOptions options)` to `MySQLPool.pool(Vertx vertx, List<MySQLConnectOptions> databases, PoolOptions options)` if keyword `loadbalance` present in the url

### PR DESCRIPTION
**Pull request by benstonezhang**
Add support to config load balance url for reactive mysql datasources in application.properties, for example

```quarkus.datasource.reactive.url=mysql:loadbalance://192.168.32.101:3306,192.168.32.102:3306/dbname```

or more simple

```quarkus.datasource.reactive.url=mysql://192.168.32.101:3306,192.168.32.102:3306/dbname```

### CODE REVIEW

**Comment by Sanne** [comment]
LGTM in principle, but I've never used this capability; better to rely on review from others about it being suitable.

Wouldn't it need some documentation changes?

It certainly needs to be squashed.

**Comment by benstonezhang** [comment]
@Sanne I expect no document change needed. The PR is try to mimic load balance url supported by  MySQL Connector/J driver. With this patch, we can use similar url for reactive datasource of mysql too.


https://github.com/quarkusio/quarkus/issues/31492

**Comment by cescoffier** [comment]
PArodn my ignorance, but it's fault tolerance, right? Is ` fatal tolerance` a thing in MySQL?

**Comment by benstonezhang** [comment]
@cescoffier Here the fault tolerance is about connection to mysql. With vert.x pool of mysql client, we can create connections to the servers in pool. In case of one server down and cause an active connection is broke, we still can use other alive connections in pool.

**Comment by cescoffier** [comment]
We need @tsegismont review - he is the expert.

**Comment by tsegismont** [comment]
I'll review it today.

**Review by tsegismont — CHANGES_REQUESTED** [review]
Thank you @benstonezhang 

I think it is a good idea to support connection load-balancing.

Nevertheless, instead of parsing the url, I would prefer we change its type in `DataSourceReactiveRuntimeConfig`:

https://github.com/quarkusio/quarkus/blob/96605e8782f7be5e314a887453784453f2012135/extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/DataSourceReactiveRuntimeConfig.java#L29

Instead of a `Optional<String>` field, we could have `Optional<List<String>>`.

Existing configurations wouldn't be broken, and users could configure it with either several values comma-separated, or [Indexed Properties](https://quarkus.io/guides/config-reference#indexed-properties).

**Comment by benstonezhang** [comment]
That's great. It would be more clear.

**Comment by benstonezhang** [comment]
@tsegismont The change of `DataSourceReactiveRuntimeConfig` would have bigger impact. What's the action I can take by now?

**Comment by benstonezhang** [comment]
OK. I will work on it and update the PR.

**Comment by benstonezhang** [comment]
@tsegismont I create a new PR [#31994](https://github.com/quarkusio/quarkus/pull/31994) name as "Support config reactive datasource with list of database urls for fault tolerance and load balance". Please review.

**Comment by benstonezhang** [comment]
PR move to [#31994](https://github.com/quarkusio/quarkus/pull/31994). Close this one.

**Pull request closed without merging**
