### PR TITLE
Excluding animal-sniffer annotations and android-annotation dependency

### PR DESCRIPTION
**Pull request by harshmadhani**

### CODE REVIEW

**Review by gsmet — COMMENTED** [review]
If you want them to be banned, please also add them to the banned dependencies here:
https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L413

Otherwise, we will have the same issue in future versions.

**Comment by harshmadhani** [comment]
> If you want them to be banned, please also add them to the banned dependencies here:
> https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L413
> 
> Otherwise, we will have the same issue in future versions.

Okay, once the GH actions pass, we will add it to the banned dependencies. Thanks for the heads-up

**Review by gsmet — DISMISSED** [review]
CI looks good. 

I let you add them to the dependencies and do a quick build without tests locally to be sure they are banned from everywhere. 

Then feel free to dismiss this review

Thanks!

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by harshmadhani** [comment]
@gsmet The CI builds have passed and we have added the dependencies to the banned dependencies list. Can you take a look and review the PR?

**Comment by gastaldi** [comment]
Thank you @harshmadhani !

**Pull request merged**
