### PR TITLE
Deprecate MetricBuildItem constructors and the unused configRootName …

### PR DESCRIPTION
**Pull request by jmartisk**
…field

Metrics equivalent of https://github.com/quarkusio/quarkus/pull/9729

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
Thanks for the followup @jmartisk

**Comment by loicmathieu** [comment]
Can you wait on the suppression of the configRoot property? This was a copy of the design made for health check and it had a reason, see my comment on the health check PR that removes it: https://github.com/quarkusio/quarkus/pull/9729#issuecomment-638163837

**Comment by jmartisk** [comment]
Hold off merging this until we settle on a decision how to proceed

**Comment by kenfinnigan** [comment]
What's the hold up on this one? Other than it needing a rebase?

**Comment by kenfinnigan** [comment]
Or maybe closed in favor of https://github.com/quarkusio/quarkus/pull/10626

**Comment by jmartisk** [comment]
If we go ahead with #10626 this PR will basically become useless. Anyway I think we can keep the `configRootParameter` parameter, as it was explained why it might be useful. I'd say let's drop this.

**Pull request closed without merging**
