### PR TITLE
Strengthen tests for @QuarkusMain

### PR DESCRIPTION
**Pull request by holly-cummins**
Our test coverage for `@QuarkusMain` is all in the `picocli-native` project. Although it covers more complex scenarios relating to picocli commands, it doesn't cover the specific scenario in https://quarkus.io/guides/command-mode-reference#mocking. Since it's documented, we want it to keep working. #28997 

I've slightly updated the wording in the docs, since I needed a bit of help to understand the intent of the example test, and I've added an integration test which exercises the scenario of using a test profile to adjust injected beans.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by holly-cummins** [comment]
My initial assumption is that the `ClasspathInGraalITCase` failure is unrelated, since I didn't touch that test, but it could be a port conflict or some other cleanup. I'll rebase to see if that changes things.

**Comment by holly-cummins** [comment]
The failure's pretty reproducible, so I assume there's some cross-talk: 

```
 Error:  io.quarkus.it.extension.ClasspathInGraalITCase.testRuntimeInitMainResourceNoDuplicate -- Time elapsed: 0.011 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '2780'. Exit code is: '0'.
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:373)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:115)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Unable to successfully launch process '2780'. Exit code is: '0'.
	at io.quarkus.test.common.LauncherUtil.ensureProcessIsAlive(LauncherUtil.java:119)
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:82)
	at io.quarkus.test.common.DefaultNativeImageLauncher.start(DefaultNativeImageLauncher.java:110)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:157)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:301)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:168)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:128)
	... 1 more
```

What's awesome is that I can reproduce it locally, and I can also reproduce it locally if I revert this changeset. Not sure how to debug that one.

**Comment by holly-cummins** [comment]
@Ladicek very kindly debugged this for me, since the problem test has always failed for me locally. He pointed out that I was mixing a `@QuarkusMain` and `@QuarkusIntegrationTest` in the same module. The `@QuarkusIntegrationTest` runs the Quarkus application, and since there's @QuarkusMain, that's what gets executed, and it terminates early, causing unhappiness for the `@QuarkusIntegrationTest`. 

One solution would be to split the tests out into their own modules but I was reluctant to go super-granular with the modules, so I've applied the second fix @Ladicek suggested, which is just to take `QuarkusMain` off the default path by adding a qualifier. 

That fixes CI, so I will squash.

**Comment by gsmet** [comment]
Thanks @holly-cummins and @Ladicek !

**Comment by holly-cummins** [comment]
Good news! This test is already failing! 

I mean, it's bad news that it's failing, but it's good news because it's failing on my classloading-rewrite branch, which means the coverage gap was real, and a regression got caught before making it to the field.

**Pull request merged**
