### PR TITLE
Bump kubernetes-client-bom from 6.7.2 to 6.8.1

### PR DESCRIPTION
**Pull request by manusa**
- Kubernetes Client 6.8.0 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.8.0
- Kubernetes Client 6.8.1 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.8.1

This will require bumping the Fabric8 Kubernetes Client version in Dekorate first.
- [x] https://github.com/dekorateio/dekorate/pull/1233
- [x] https://github.com/dekorateio/dekorate/pull/1235

The Dekorate dependency is also bumped to latest 4.0.0 which includes the 6.8.0 compatible Kubernetes Client dependency.

/cc @metacosm

### CODE REVIEW

**Comment by metacosm** [comment]
Tried this PR locally, this is definitely not a backwards compatible change: some of my code doesn't compile anymore.

**Comment by manusa** [comment]
Could you provide more details about your specific compilation failures?

Is it related to the change of syntax in builders? Or in intermediate type signatures (fluents)?

**Comment by manusa** [comment]
You'll notice how these can be fixed if you check the changes in this PR.

I'm not sure how we should document this in Quarkus to help user's migration

**Comment by metacosm** [comment]
Not that easy in my case… Then again, I can't already not read or understand the explicit type as it is. I applied the suggestion from my IDE and the type got changed to:

`NamedInstallStrategyFluent<ClusterServiceVersionSpecFluent<ClusterServiceVersionFluent<ClusterServiceVersionBuilder>.SpecNested<ClusterServiceVersionBuilder>>.InstallNested<ClusterServiceVersionFluent<ClusterServiceVersionBuilder>.SpecNested<ClusterServiceVersionBuilder>>>.SpecNested<ClusterServiceVersionSpecFluent<ClusterServiceVersionFluent<ClusterServiceVersionBuilder>.SpecNested<ClusterServiceVersionBuilder>>.InstallNested<ClusterServiceVersionFluent<ClusterServiceVersionBuilder>.SpecNested<ClusterServiceVersionBuilder>>>`

I mean, come on… that's completely not understandable (not that the original type was) but now it's significantly worse. I mean I wouldn't be able to make that change without assistance from the IDE. Not sure what we can do here but we're definitely not going in the right direction on this particular issue.

**Comment by metacosm** [comment]
I managed to get it dealt with by using `NamedInstallStrategyFluent<?>.SpecNested<?>` instead, which I guess makes sense.

**Comment by metacosm** [comment]
Where do we stand on this? /cc @manusa @iocanel

**Comment by manusa** [comment]
From my standing point the pull request is ready (it included the 4.0.0 Dekorate bump one week ago) , not sure if it's expected for something else to be added.

**Comment by geoand** [comment]
I have no objections, but I would like the PR rebased onto `main` since the last time we had a CI run was over a week ago.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
I assume this is a somewhat breaking change, right?

**Comment by metacosm** [comment]
> I assume this is a somewhat breaking change, right?

Yes, so probably for 3.5.

**Comment by metacosm** [comment]
@manusa minor nit picking but the commit message for the second commit is wrong: it should say dekorate, not kubernetes client bom.

**Comment by michalvavrik** [comment]
After this PR, when I use `io.fabric8.kubernetes.client.impl.KubernetesClientImpl#load` to load my template

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "app"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
      app.kubernetes.io/name: "app"
    type: "ClusterIP"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "app-management"
  spec:
    ports:
      - name: "management"
        port: 9000
        targetPort: 8080
    selector:
      app.kubernetes.io/name: "app"
    type: "ClusterIP"
- apiVersion: "apps.openshift.io/v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app.openshift.io/runtime: "quarkus"
      app.kubernetes.io/name: "app"
    name: "app"
  spec:
    replicas: 1
    selector:
      app.kubernetes.io/name: "app"
    template:
      metadata:
        labels:
          app.openshift.io/runtime: "quarkus"
          app.kubernetes.io/name: "app"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "my-registry"
          name: "app"
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
              ports:
            - containerPort: 8080
              name: "management"
              protocol: "TCP"
```

my deployment config spec contains empty triggers and then when I adjust stuff and serialize it as `KubernetesList`, I can see newly template contains `triggers: []`

```
- apiVersion: "apps.openshift.io/v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app.openshift.io/runtime: "quarkus"
      app.kubernetes.io/name: "app"
      scenarioId: "OpenShiftUsingContainerRegistryPingPongResourceIT-1695036746"
    name: "app"
    namespace: "mvavrik-debug"
  spec:
    replicas: 1
    selector:
      app.kubernetes.io/name: "app"
    template:
      metadata:
        labels:
          app.openshift.io/runtime: "quarkus"
          app.kubernetes.io/name: "app"
          tsLogWatch: "app"
          scenarioId: "OpenShiftUsingContainerRegistryPingPongResourceIT-1695036746"
        namespace: "mvavrik-debug"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: "quarkus.log.console.format"
            value: "%d{HH:mm:ss,SSS} %s%e%n"
          image: "my-registry"
          name: "app"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
            ports: null
          - containerPort: 8080
            name: "management"
            protocol: "TCP"
    **triggers: []**
```
which prevents my rollout with `oc: error: #1 is already in progress (Pending).`. This is new behavior, why are `triggers: []` added, please?

**Comment by michalvavrik** [comment]
nope, I got rid of triggers and still having issue (with the bump only), so it's not related to the triggers.

**Comment by manusa** [comment]
cc/ @shawkins 

There were some changes in the serialization default behavior, let me try to find some references.

**Comment by manusa** [comment]
```
Fix #5262: Built-in resources were in-consistent with respect to their serialization or empty collections. In many circumstances this was confusing behavior. In order to be consistent all built-in resources will omit empty collections by default. This is a breaking change if you are relying on an empty collection in a json merge or a strategic merge where the list has a patchStrategy of atomic. In these circumstances the empty collection will no longer be serialized. You may instead use a json patch, server side apply instead, or modify the serialized form of the patch.
```

https://github.com/fabric8io/kubernetes-client/issues/5262

AFAIR setting the triggers to `null` (when "adjusting stuff") should fix your problem

**Comment by michalvavrik** [comment]
> ```
> Fix #5262: Built-in resources were in-consistent with respect to their serialization or empty collections. In many circumstances this was confusing behavior. In order to be consistent all built-in resources will omit empty collections by default. This is a breaking change if you are relying on an empty collection in a json merge or a strategic merge where the list has a patchStrategy of atomic. In these circumstances the empty collection will no longer be serialized. You may instead use a json patch, server side apply instead, or modify the serialized form of the patch.
> ```
> 
> [fabric8io/kubernetes-client#5262](https://github.com/fabric8io/kubernetes-client/issues/5262)
> 
> AFAIR setting the triggers to `null` (when "adjusting stuff") should fix your problem

yeah, it did. and after that, diff on previously serialized and newly (after bump) serialized deployment config doesn't show changes. I have some other issue caused by this bump though, I don't know where so probably not right time to get you involved :-)

Thanks for prompt answer.

**Pull request merged**
