### PR TITLE
Revert "Introduce getSession() to PanacheEntity and PanacheRepository"

### PR DESCRIPTION
**Pull request by gastaldi**
Reverts quarkusio/quarkus#14379

### CODE REVIEW

**Comment by FroMage** [comment]
Damn, I reviewed https://github.com/quarkusio/quarkus/pull/10541 and OKed it even when @evanchooly noticed it should have been static. And the extension is stable so we can't just change an instance method into a static one to fix it.

**Comment by FroMage** [comment]
Perhaps we can make `PanacheEntityBase.getEntityManager` deprecated and introduce `static PanacheEntityBase.entityManager()` instead, on the basis that this is not actually a property so it doesn't need the `get` prefix.

It's dodgy but I can't think of anything better. Can you?

**Comment by gastaldi** [comment]
@FroMage sure, that makes sense. Let's merge this and revisit in a separate PR then

**Review by FroMage — APPROVED** [review]

**Comment by FroMage** [comment]
OK thanks.

**Pull request merged**
