### PR TITLE
Bump jboss-logmanager.version from 1.0.10 to 1.0.11

### PR DESCRIPTION
**Pull request by vsevel**
see https://github.com/dmlloyd/jboss-logmanager-embedded/pull/6
thanks @dmlloyd for the release

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Review by dmlloyd — APPROVED** [review]

**Comment by vsevel** [comment]
can't seem to be able to run all jobs successfully, even after several attempts. last issue is on
```
2022-10-25T17:40:44.7102270Z 2022-10-25 13:40:44,662 INFO  [io.quarkus] (main) quarkus-integration-test-mongodb-devservices stopped in 0.047s
2022-10-25T17:40:45.1667040Z [INFO] 
2022-10-25T17:40:45.1667450Z [INFO] Results:
2022-10-25T17:40:45.1667810Z [INFO] 
2022-10-25T17:40:45.1668150Z [ERROR] Errors: 
2022-10-25T17:40:45.1681960Z [ERROR]   BookResourceTest.health:45 » SocketTimeout Read timed out
2022-10-25T17:40:45.1683720Z [ERROR]   BookResourceTest.testBlockingClient:34 » SocketTimeout Read timed out
2022-10-25T17:40:45.1684660Z [ERROR]   BookResourceTest.testReactiveClients:39 » SocketTimeout Read timed out
2022-10-25T17:40:45.1685850Z [ERROR]   BookResourceWithParameterInjectionTest.testInjectedClient:31 » SocketTimeout Read timed out
2022-10-25T17:40:45.1687060Z [ERROR]   OtherProfileBookResourceTest.testBlockingClient:14 » SocketTimeout Read timed out
2022-10-25T17:40:45.1687690Z [INFO] 
2022-10-25T17:40:45.1688130Z [ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
```

completely unrelated to the current PR. if ok with you @gsmet and @geoand I suggest merging as is.

**Comment by gsmet** [comment]
Is this fix included in `1.1.1` that is used in the Jakarta branch?

**Comment by vsevel** [comment]
> Is this fix included in `1.1.1` that is used in the Jakarta branch?

yes @gsmet through https://github.com/quarkusio/quarkus/pull/27890
we are consistent now

**Comment by gsmet** [comment]
Perfect, thanks.

**Pull request merged**
