### PR TITLE
WIP: Add info to Contributing.md (Don't merge - for demo purposes only)

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by gastaldi** [comment]
Use the `git` commands in https://github.com/quarkusio/quarkus/pull/7859#issuecomment-599252831 if you need help :wink:

**Comment by gastaldi** [comment]
IMHO it would be nice to recommend using [Hub](https://hub.github.com) for faster turnaround

**Comment by geoand** [comment]
> Use the `git` commands in [#7859 (comment)](https://github.com/quarkusio/quarkus/pull/7859#issuecomment-599252831) if you need help

Well you know I've signed you up adding those commands to the guide :laughing:

**Comment by gastaldi** [comment]
Voluntelling is always effective :laughing:

**Comment by gastaldi** [comment]
Maybe it's easier to create a Wiki page and then move the content over to CONTRIBUTING.md?

**Comment by geoand** [comment]
PR served it purpose. Video coming shortly

**Pull request closed without merging**
