### PR TITLE
Generate debug sources for generated bytecode

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
This is a draft until Gizmo 1.0.0.Alpha4 is released.

**Comment by Sanne** [comment]
Should we still consider this only as a draft?

**Comment by dmlloyd** [comment]
Yes, until Gizmo 1.0.0.Alpha4 is released.

**Comment by dmlloyd** [comment]
This is ready for review now.

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
