### PR TITLE
Move 1.3 to Java 11 by default

### PR DESCRIPTION
**Pull request by gsmet**
I think I backported everything that's needed except for the deprecation warnings that should be only for 1.4.

/cc @gwenneg @dmlloyd @gastaldi @geoand

### CODE REVIEW

**Comment by gsmet** [comment]
Please don't merge, I will merge it myself.

**Review by gastaldi — APPROVED** [review]

**Comment by geoand** [comment]
@gsmet what about https://github.com/quarkusio/quarkus/pull/8132?

**Comment by gsmet** [comment]
@geoand It's marked for backport already, I will backport it separately when I do my mass backporting.

**Comment by geoand** [comment]
OK gotcha!

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
This looks good to go

**Pull request merged**
