### PR TITLE
Additional Endpoint

### PR DESCRIPTION
**Pull request by saumya1singh**
#14195 
#14385

### CODE REVIEW

**Comment by SaumyaSingh1** [comment]
@FroMage Here I removed `br` tag and added some CSS.

**Comment by SaumyaSingh1** [comment]
Also on the `Additional endpoints` branch I have previously done `Merge` so maybe older commits will be shown.

**Comment by FroMage** [comment]
This is fine, but you should not do this on your `master` branch: that is a risky thing to do because it's easy to mess it up.

Also, you didn't have to create a new PR, you could have pushed your updated work on the previous branch and the old PR would be updated.

**Comment by SaumyaSingh1** [comment]
> This is fine, but you should not do this on your `master` branch: that is a risky thing to do because it's easy to mess it up.
> 
> Also, you didn't have to create a new PR, you could have pushed your updated work on the previous branch and the old PR would be updated.

oh yes I should have added more commits in `Additional Endpoints` branch only , I updated my master with my new commits 🙆🏻‍♀️ Strange

**Comment by gsmet** [comment]
@SaumyaSingh1 small comment: please make sure your PR title is descriptive enough. The current one is a bit evasive and it's not really easy to know what's it's doing. Thanks!

**Comment by FroMage** [comment]
OK so I advise you fix your other branch and close this PR and update the other one, OK?

**Comment by FroMage** [comment]
Let me know if you want help fixing your other branch.

**Comment by FroMage** [comment]
Let me know if you want help fixing your other branch.

**Comment by SaumyaSingh1** [comment]
> Let me know if you want help fixing your other branch.

I followed same `rebase` instructions there, I will need to do force push as you said I think .

**Comment by SaumyaSingh1** [comment]
So here I am clicking on close PR. 
Will be adding more commits on the `AdditionalEndpoint` Branch only :)

**Pull request closed without merging**
