### PR TITLE
Remove lambdas from RestClientBase

### PR DESCRIPTION
**Pull request by geoand**
It's policy to not use lambda's in runtime code

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]
I don't know why you thought of me for the review, but looks fine :-)

**Comment by Ladicek** [comment]
> It's policy to not use lambda's in runtime code

If that's a policy, then it's a wrong policy, but this is a wrong place to discuss that :-)

**Comment by geoand** [comment]
@Ladicek it was you or Michal, your name came up first in the reviewers list :)

**Comment by geoand** [comment]
Darn, I just saw that I hadn't squashed the commits :facepalm:

**Pull request merged**
