### PR TITLE
Bump kubernetes-client-bom from 5.9.0 to 5.10.1

### PR DESCRIPTION
**Pull request by manusa**
Kubernetes Client 5.10.0 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v5.10.0

Just speeding up the dependabot process to see if CI reports any issue.

/cc @metacosm

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Seems like there is a compilation failure

**Comment by manusa** [comment]
I will check.

**Comment by manusa** [comment]
The method [KubernetesServer#getMockServer](https://github.com/fabric8io/kubernetes-client/blob/5f5c8d3f76375ffc0bccfc3c4f417beaac031024/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesServer.java#L106-L108) was [removed](url) since it was providing access to a [deprecated method](https://github.com/fabric8io/mockwebserver/blob/3714add928bbc1287c3ba4521837323c26b194c1/src/main/java/io/fabric8/mockwebserver/DefaultMockServer.java#L166) that exposed an internal class.

The following statements are now invalid:
https://github.com/quarkusio/quarkus/blob/35d76c413674bae47e10b4e6e521cb74310c0c06/integration-tests/kubernetes-client/src/test/java/io/quarkus/it/kubernetes/client/KubernetesTestServerOnProfileTest.java#L43

https://github.com/quarkusio/quarkus/blob/5df26472fc3666e2945d29ae530413af5c9dbc17/integration-tests/kubernetes-client/src/test/java/io/quarkus/it/kubernetes/client/KubernetesTestServerTest.java#L43

I don't really understand why Quarkus actually exposes the KubernetesServer class (a JUnit4 ExternalResource) which is intended to be used as:
```java
@Rule
public KubernetesServer server = new KubernetesServer();
```

I guess that what it would be useful is to expose the [KubernetesMockServer](https://github.com/fabric8io/kubernetes-client/blob/4f2d12cc5ecc72b4dfc4b02c95a3715d8dd438f5/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java) class and maybe the pre-configured KubernetesClient too, just like the JUnit 5 [extension](https://github.com/fabric8io/kubernetes-client/blob/4f2d12cc5ecc72b4dfc4b02c95a3715d8dd438f5/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtension.java) does.

For the current issue I can only think of the following alternatives:
1. Remove the assertions that are causing trouble.
2. Replace the assertions with something crazy like this:
   `Assertions.assertEquals(10001, new URL(mockServer.getClient().getConfiguration().getMasterUrl()).getPort());`
3. Don't bump the client version and add a `KubernetesServer#getPort` method to a future Fabric8 Kubernetes Client release


My main concern is still that we are making use and exposing the KubernetesServer class which is really intended to be used as a JUnit4 rule. In order to maintain future compatibility with this, we'll probably need to add some extra-methods in the upstream Fabric8 project.

**Comment by geoand** [comment]
If possible, I would prefer option 3

**Review by geoand — APPROVED** [review]

**Comment by manusa** [comment]
There is some API breakage, since we no longer have the `KubernetesServer#getMockServer()` method that exposed the internal OkHttp MockWebServer instance. There's access to the `KubernetesMockServer` instance via the `Kubernetes#getKubernetesMockServer()` method that exposes the public API for the [Fabric8 MockServer](https://github.com/fabric8io/mockwebserver/blob/482fbb1eafd5fc77f335251ab038f6830977581b/src/main/java/io/fabric8/mockwebserver/MockServer.java).

Should we document this somewhere?

**Comment by geoand** [comment]
Yeah I added the tag so we can add this change to release notes for `2.6`

**Comment by geoand** [comment]
@manusa mind wring a small blurb here about the breakage which I can then add to the `wiki`?

**Comment by manusa** [comment]
> @manusa mind wring a small blurb here about the breakage which I can then add to the `wiki`?

Hi @geoand, no problem. I'll do my best here, but bear with me, I'm not sure how you usually write this things.

```
## Kubernetes Client / OpenShift Client test framework

The [Fabric8 Kubernetes Client 5.10](https://github.com/fabric8io/kubernetes-client/releases/tag/v5.10.0)
release includes many improvements in the MockWebServer.
These improvements are based on the latest release of
[Fabric8 MockWebServer](https://github.com/fabric8io/mockwebserver/releases/tag/v0.2.2) which included
some breaking changes.

The method `io.fabric8.kubernetes.client.server.mock.KubernetesServer#getServer()` has been removed in favor of
the `io.fabric8.kubernetes.client.server.mock.KubernetesServer#getKubernetesMockServer()` method
that returns the instance of the underlying `KubernetesMockServer`.
This instance should provide access to almost every functionality that was available through the `getServer()` method.

Similarly the method `io.fabric8.openshift.client.server.mock.OpenShiftServer#getServer()` has been
removed in favor of 
the `io.fabric8.openshift.client.server.mock.OpenShiftServer#getOpenShiftMockServer()` method.
```

I hope this helps. Let me know if you need anything else :wink:.

**Comment by geoand** [comment]
Looks good, thanks

**Comment by geoand** [comment]
@gsmet can you please make sure ^ gets added to the wiki?

Thanks!

**Pull request merged**
