### PR TITLE
Asterisk and other special characters not escaped in Quarkus config docs

### LINKED ISSUE #10153: Asterisk and other special characters not escaped in Quarkus config docs
`io.quarkus.annotation.processor.generate_doc.JavaDocParser.appendHtml(StringBuilder, Node)` is passing asterisk and other special characters verbatim to AsciiDoc. As a result, when AsciiDoctor renders the docs to HTML, the asterisks are replaced by `<strong>` instead of being displayed verbatim. An example: https://camel.apache.org/camel-quarkus/latest/extensions/core.html#quarkus.camel.service.discovery.exclude-patterns

Original report: https://github.com/apache/camel-quarkus/issues/1402

A PR follows.

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #10153

### CODE REVIEW

**Comment by ppalaga** [comment]
@machi1990 any chance to review? I'd like to propose one more fix after this one.

**Comment by machi1990** [comment]
Hi @ppalaga thanks for the fix. I'd take a look at this a bit later. Any chance we could have a test or two?

**Comment by ppalaga** [comment]
> Any chance we could have a test or two?

Tests for JavaDoc -> AsciiDoc would be rather trivial and thus not so useful. 
JavaDoc -> AsciiDoc -(AsciiDoctor)-> HTML would make more sense, IMO. Let me check if it is doable.

**Comment by ppalaga** [comment]
fdaa2e0 added tests

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
Thanks for adding the tests @ppalaga. LGTM

**Pull request merged**
