### PR TITLE
Add Freemarker documentation

### PR DESCRIPTION
**Pull request by vsevel**
Documentation for https://github.com/quarkiverse/quarkiverse-freemarker
Should be part of Quarkus Guides, according to:
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkiverse.20Releases/near/212560606

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
I don't think the particular sentence you're pointing makes a decision.

I'm not exactly sure I want the Quarkiverse doc to be part of the official guides as it would somehow say that they are officially supported by us, which is not the case.

Pointing to the guides from the Guides page as long as we have a proper Quarkiverse section and something clearly stating what these extensions are would be OK for me. But hosting the guides in our UI is another thing.

We need a real discussion about this.

**Comment by vsevel** [comment]
@gsmet no problem. just let me know where I should put it. @loicmathieu 's argument seemed reasonable, since if there was no `quarkiverse` yet, the `freemarker` extension would have landed in the `quarkusio` repo (assuming we agreed there was value, and it was respecting the quality criteria of course). so until we have a unified documentation approach for `quarkiverse`, that would seem a good compromise.
I can definitely put it back into the `quarkiverse-freemarker` repo. that is where I had it initially.

**Comment by gastaldi** [comment]
We have an issue to discuss this: https://github.com/quarkusio/quarkus/issues/12526

**Comment by gastaldi** [comment]
@vsevel do you mind moving this documentation to the `quarkiverse-freemarker` repository meanwhile? It would be nice to have that in the repository's README for now

**Comment by gastaldi** [comment]
Thanks. I'll close this PR for now and reopen when we reach a consensus.

**Pull request closed without merging**
