### PR TITLE
[docker][jib] Bump baseJvmImage from JRE8 to JRE11

### PR DESCRIPTION
**Pull request by OneCricketeer**
JDK11 has been around over a year. Time to upgrade

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot!

You would also updating https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/templates/dockerfile-jvm.ftl#L19 as part of the PR?
Since this template is used to create the Dockerfile that the `container-image-docker` extension uses, it would be nice to have both extensions updated.

**Comment by cricket007** [comment]
Done 😸 

Thanks! 😷

**Review by geoand — APPROVED** [review]
Excellent, thanks!

**Comment by gsmet** [comment]
@geoand I think it should be backported, right?

**Comment by geoand** [comment]
@gsmet I don't think so.

We only start warning people against using Java 8 in `1.4`, so I don't think we need to make the change in `1.3`.

**Comment by geoand** [comment]
After discussing with @gsmet I see the merit in this, let's do it.

**Comment by cricket007** [comment]
So, this'll go in 1.4, then? 

Roadmap one can watch for release cycles?

**Comment by gsmet** [comment]
@cricket007 it will be in 1.3.1 that should be released tomorrow.

**Comment by cricket007** [comment]
So, I saw Jib things in here. Is this ticket still valid? https://github.com/GoogleContainerTools/jib/issues/1555

**Comment by geoand** [comment]
I added a comment there.

**Pull request merged**
