### PR TITLE
Google Cloud services

### PR DESCRIPTION
**Pull request by loicmathieu**
Add support for some popular Google Cloud services.

This PR provides the following integration with Google Cloud services:

- Authentication via our configuration file and allow to inject a `GoogleCredentials` CDI bean.
- Storage: allow to inject a `Storage` CDI bean.
- BigQuery: allow to inject a  `BigQuery` CDI bean.
- PubSub
- Spanner: allow to inject a `Spanner` CDI bean.
- Firestore: allow to inject a `Firestore` CDI bean.

These extensions make the libraries works in Quarkus and manage the needed dependencies.

Documentation is still missing but erything works including native.

There is already an extension proposal for Firebase here #8671 maybe we can also provide it but it seems very specific (Firebase admin server).

### CODE REVIEW

**Comment by kostacasa** [comment]
An extension for google cloud secret manager would be hugely useful as this is something that every modern cloud service will need to utilize. We rolled our own by using a combination of REST API and google's auth library but it's very clunky and requires custom native image config to make Google's auth library compile down to native.

Additionally, having an extension that demonstrates how to implement Google Cloud SDK supported services in a best practices way would be immensely useful for the community to build support for additional services using it as a template. 

In any case, I'm definitely subscribing to this one. :)

**Comment by loicmathieu** [comment]
@kostacasa 

> An extension for google cloud secret manager would be hugely useful as this is something that every modern cloud service will need to utilize. [...]

I didn't plan to create more extension at the moment, you can always create an extension proposal issue so that people will be able to +1 to it and show interest.

> Additionally, having an extension that demonstrates how to implement Google Cloud SDK supported services in a best practices way would be immensely useful for the community to build support for additional services using it as a template.

I could write something for this in the documentation, creating the proposed extension shows that there is two kind of services API: one uses REST and the other GRPC. Native support could be challenging for the one using REST. But it should be realy simple to create new extension based on the existing ones if you choose the right template ...

**Comment by kostacasa** [comment]
> I could write something for this in the documentation, creating the proposed extension shows that there is two kind of services API: one uses REST and the other GRPC. Native support could be challenging for the one using REST. But it should be realy simple to create new extension based on the existing ones if you choose the right template ...
We wrote our integrations with Cloud Secrets and Cloud KMS using a combination of Quarkus native REST client and the Google Auth library. Every gRPC service in google cloud has a REST equivalent using the gRPC transcoding syntax. 

Of course, the question becomes whether the efficiency gains of using gRPC marshaling outweigh the added weight of gRPC libraries themselves. Since the GCP APIs are gRPC native, I'd prefer to use the native integration rather than going through the REST transcoding.

I will have a look at how you approached it with gRPC and see if that could be extended for additional services. Thanks a lot for paving the path!

**Comment by kostacasa** [comment]
> I use the Java libraries provided by Google Cloud, so I didn't directly use REST or gRPC services. And some of them are based on REST and some on gRPC.

Oh cool, didn't realize you managed to get them to work, I'll have a closer look. I tried to take the entire Google Cloud API library and slim it down to the things we needed but it refused to play nice with native image.

**Comment by loicmathieu** [comment]
@kostacasa if you want to use a different service you could add `quarkus-google-cloud-common` dependency and use the needed library from Google Cloud API. Then use an existing library as a template (depending the underlying library uses REST or gRPC). Or you can open an extension proposal issue ;) 

If you want to discuss this more, you can contact me on Zulip => https://quarkusio.zulipchat.com/

**Comment by sberyozkin** [comment]
@loicmathieu Hi, this is great. 
What I'd like to suggest though is to make some work about `GoogleCredentials` such that the same `BigQuery`/etc bean can work not only with the service accounts but also with the Quarkus user authenticating against a Google Identity OIDC provider.
Specifically, when a Quarkus user authenticates with Google, Quarkus OIDC adapter will make the access token (which can be used to access whatever Google services are enabled in this user's developer console) as an injected `AccessTokenCredential` which is an instance of `quarkus-security`'s `TokenCredential` which has a `getToken` method. 

BigQuery/etc beans then could use this token to invoke a given service on behalf of a user.

So right now `GoogleCredentials` is initialized from the service account file. What do you think about providing using Quarkus `TokenCredential` as an alternative ?

**Comment by kostacasa** [comment]
> @loicmathieu Hi, this is great.
> What I'd like to suggest though is to make some work about `GoogleCredentials` such that the same `BigQuery`/etc bean can work not only with the service accounts but also with the Quarkus user authenticating against a Google Identity OIDC provider.
> Specifically, when a Quarkus user authenticates with Google, Quarkus OIDC adapter will make the access token (which can be used to access whatever Google services are enabled in this user's developer console) as an injected `AccessTokenCredential` which is an instance of `quarkus-security`'s `TokenCredential` which has a `getToken` method.
> 
> BigQuery/etc beans then could use this token to invoke a given service on behalf of a user.
> 
> So right now `GoogleCredentials` is initialized from the service account file. What do you think about using Quarkus `TokenCredential` as an alternative when making a google service call ?

Also related to this, I would suggest using Google Auth library's utility method for locating application default credentials and setting the correct scope.

```java
            googleServicesCredentials = GoogleCredentials.getApplicationDefault().createScoped(List.of("https://www.googleapis.com/auth/cloud-platform"));
            genericServicesCredentials = GoogleCredentials.getApplicationDefault();
            if (!(genericServicesCredentials instanceof IdTokenProvider)) {
                throw new IllegalStateException("Credentials are not an instance of IdTokenProvider");
            }
```

We do something along these lines for now and that works both locally and when deployed on the cloud. It does require calling `gcloud auth application-default login`. However, that will produce a service account JSON file that does not implement IdTokenProvider and will therefore not be able to generate valid access tokens.

There is a PR open to resolve that here:
https://github.com/googleapis/google-auth-library-java/pull/469

**Comment by loicmathieu** [comment]
@sberyozkin interesting, this could be done on a followup issue. Note that PubSub only support using a JSON service account file defines as an env variable so this will not works for all cases.

@kostacasa I'll have a look as I'm not familiar with how to authenticate to GCP in details and there seems to be some differencies accross services, and if the application is deployes on AppEngine/Cloud Fuctions or not.

**Comment by sberyozkin** [comment]
Hi @loicmathieu 

> interesting, this could be done on a followup issue.

Sure, this would be quite cool; I did a demo awhile back with a user authenticating via Google and then choosing which Shakespeare works to query, and BigQuery was happy to return the list to a user specific query. So I'm already looking forward to doing it with Quarkus :-).
I guess we can do it easily enough, `TokenCredential` can be injected into the `GoogleGredentials` producer, and use  `TokenCredential#getToken` when a serrvice account file is not present.

 > Note that PubSub only support using a JSON service account file defines as an env variable so this will not works for all cases.
Sure, we can use a simple priority - if `service account` file is set - it must be used - else - `TokenCredential.getToken`, and may be some extra check in the PubSub bean to verify it is the service account only...

This would bring a `quarkus-security` dependency but it is pretty light.
Thanks for starting this integration project :-)

**Comment by kostacasa** [comment]
> @kostacasa I'll have a look as I'm not familiar with how to authenticate to GCP in details and there seems to be some differencies accross services, and if the application is deployes on AppEngine/Cloud Fuctions or not.

Yes, they use access tokens, OIDC tokens and OAuth2 tokens, then they also distinguish between service accounts and user accounts and managed and unmanaged platforms. It's a big hairy mess, but you have to start somewhere.

The managed platforms (i.e. Cloud Run/Functions) will be preconfigured with service account credentials in locations where `GoogleCredentials.getApplicationDefault()` can discover them. So that's a great start. Then you can start thinking about how to scope them depending on what service is being called.

We use a method like this to obtain the Authorization header value:

```java
    private String getAuthorizationHeader(OAuth2Credentials credentials) {
        Map<String, List<String>> requestMetadata;
        try {
            requestMetadata = credentials.getRequestMetadata();
        } catch (IOException e) {
            throw new RuntimeException("Unable to refresh google credentials", e);
        }

        if(!requestMetadata.containsKey(HttpHeaders.AUTHORIZATION)) {
            throw new RuntimeException("Unable to retrieve GCP Authorization header");
        }

        return requestMetadata.get(HttpHeaders.AUTHORIZATION).get(0);
    }
```

As far as I recall, OAuth2Credentials implements an internal caching mechanism so calls to `credentials.getRequestMetadata();` should returned the cached token for as long as it's still valid. Therefore it should be safe to call this method before every request without incurring a performance penalty. 

Not sure how that will gel with the `TokenCredential` suggested by @sberyozkin though. You could extract the value and stick it into an instance of TokenCredential. Also not sure how TokenCredential gets attached to outgoing HTTP requests but would like to know more if there is an easy way to achieve that. Right now we are using a ClientRequestFilter as a @Provider on all GCP clients.

**Comment by sberyozkin** [comment]
@kostacasa

> Not sure how that will gel with the TokenCredential suggested by @sberyozkin though. You could extract the value and stick it into an instance of TokenCredential. Also not sure how TokenCredential gets attached to outgoing HTTP requests but would like to know more if there is an easy way to achieve that. Right now we are using a ClientRequestFilter as a @Provider on all GCP clients.

As far as Loic's @loicmathieu PR is concerned, if he agrees then we will just inject it into the producer creating a request scoped Google credentials and the token will be used to create them if no service account file is available.

Are you asking how to get this `TokenCredential` into your JAX-RS client filter ? If yes then I think the only way is to run the client in the MP Context Propagation scope (CC @FroMage ). Alternatively, set `Authorization` header manually. FYI, I've started prototyping the OIDC client code and as part of that effort, eventually, there will hopefully be a closer integration with MP RestClient

**Comment by loicmathieu** [comment]
This PR moved to https://github.com/quarkiverse/google-cloud-services/pull/1

**Comment by sberyozkin** [comment]
@loicmathieu Thanks, I'll fork, may be you can close this one then ?

**Comment by loicmathieu** [comment]
@sberyozkin @kostacasa can you open an issue to describe what you may expect around authentication to Google Cloud in this repo: https://github.com/quarkiverse/quarkiverse-google-cloud-services

**Comment by loicmathieu** [comment]
Closing as it will be integrated here: https://github.com/quarkiverse/quarkiverse-google-cloud-services/pull/1

**Pull request closed without merging**
