### PR TITLE
Apply tiny polish to StartupActionImpl

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@Sanne @gsmet I am seeing:

```
2021-04-06T09:13:38.4387734Z [ERROR] Failed to execute goal io.quarkus:quarkus-bootstrap-maven-plugin:999-SNAPSHOT:extension-descriptor (generate-extension-descriptor) on project quarkus-jdbc-oracle: The deployment artifact io.quarkus:quarkus-jdbc-oracle-deployment::jar depends on the following Quarkus extension deployment artifacts whose corresponding runtime artifacts were not found among the dependencies of io.quarkus:quarkus-jdbc-oracle:jar:999-SNAPSHOT: io.quarkus:quarkus-arc-deployment::jar -> [Help 1]
```

**Comment by Sanne** [comment]
hum that's a remnant from old structures I guess. The Oracle PR has been re-adapted from very old times.

How do I reproduce this?

**Comment by Sanne** [comment]
> How do I reproduce this?

ah it's an unrelated PR. Sorry I thought I was reading a new issue.. let me try a local clean build.

**Comment by geoand** [comment]
Thanks

**Review by gsmet — APPROVED** [review]

**Pull request merged**
