### PR TITLE
Handle text blocks when creating Panache find query

### LINKED ISSUE #31210: using PanacheQuery#project with multi-line string in Kotlin fails
### Describe the bug

[This line](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/panache-hibernate-common/runtime/src/main/java/io/quarkus/panache/hibernate/common/runtime/PanacheJpaUtil.java#L70) checks if the query starts with `select ` (note the trailing space), but in Kotlin you normally use (I do at least) this type of string for queries
```
val hql = """
    select myStuff
    and do more hql stuff here
""".trimIndent()
```
which doesn't have the trailing space that's checked for unless you manually add one. Instead theres a \n after `select`. This in turns messes with the generated HQL when you use `io.quarkus.hibernate.orm.panache.kotlin.PanacheQuery#project` since it will insert its own select at the beginning if it's missing (if I've understood everything correctly).

EDIT: I thought these strings were a Kotlin feature, but it seems it's a Java feature ref https://docs.oracle.com/en/java/javase/15/text-blocks/index.html

### Expected behavior

That text blocks work with .project().

### Actual behavior

Using text blocks do not work .project() when generating the HQL for .project() since Quarkus looks for `select ` with the space to see if we supplied our own select.

### How to Reproduce?

See the reproducer.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

Discovered in 2.16.0.Final, reproducer is 2.16.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information
[panache-project-reproducer.zip](https://github.com/quarkusio/quarkus/files/10818465/panache-project-reproducer.zip)

_No response_

### PR DESCRIPTION
**Pull request by bakrhaso**
I filed this issue #31210 from my work account. This PR should fix it. I'm not really sure why one test is failing. As far as I can tell it doesn't seem related to my change, but this is my first time contributing so hopefully someone else can shed some light on that.

Fixes #31210

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM thanks

**Review by gsmet — CHANGES_REQUESTED** [review]
Could we test this in the Java tests because they are our reference?

Thanks.

**Comment by bakrhaso** [comment]
I'm not sure if the formatter supports text blocks in Java, it seems to fail no matter what I do.

Shall I remove the Kotlin tests? They are pretty much identical.

**Comment by loicmathieu** [comment]
Quarkus supports Java 11.
For tests for features on more recent versions  there is a java17 integration test that can be used.

**Comment by bakrhaso** [comment]
I've added the Java tests

**Review by loicmathieu — APPROVED** [review]
lgtm, thanks

**Comment by loicmathieu** [comment]
@gsmet the CI failure seems to be non-related. Is it OK for you to merge it ?

**Review by gsmet — APPROVED** [review]
Yes, let's merge it!

Thanks for the contribution!

**Pull request merged**
