### PR TITLE
Vertx 3.8 and new sql client

### PR DESCRIPTION
**Pull request by FroMage**
This is a draft PR because I want to wait for opinions about the new mysql async client.

Right now I've just updated the `quarkus-reactive-pg-client` module to use the new `vertx-sql` module, but I wonder if it should support both pg and mysql, by discriminating on the URL string. It would make it depend on both clients, though.

An alternative would be to make a new `quarkus-reactive-mysql-client` module, but it would largely be similar.

Opinions @vietj and @tsegismont ?

This may be related to the ongoing work of @gsmet about supporting multiple datasources, but I don't know what state it is in.

### CODE REVIEW

**Comment by gsmet** [comment]
We already support multiple datasources. Are you talking about supporting multiple persistence units?

**Comment by FroMage** [comment]
> We already support multiple datasources. Are you talking about supporting multiple persistence units?

Mmmm, that's an interesting subtle difference I did not realise. So, since the reactive drivers don't need persistence units, we could already support multiple data sources at the same time with one JPA and two reactive sources (pg and mysql). We should definitely look into that.

**Comment by gsmet** [comment]
@FroMage could you rebase and squash everything?

I think we should promote this PR because, the MySQL discussion is IMHO unrelated and could be started on the mailing list.

**Comment by FroMage** [comment]
Yeah, that was my plan.

**Comment by FroMage** [comment]
OK, rebased and squashed.

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
Let's merge then, thanks!

**Pull request merged**
