### PR TITLE
Add the ability to display the k8s manifest in the DevUI

### LINKED ISSUE #26230: Expose generated k8s resources in the Dev UI
### Description

The DevUI should have a way to expose the k8s resources that would be generated by the application

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Resolves: #26230

### CODE REVIEW

**Comment by geoand** [comment]
@phillip-kruger if you have a few spare cycles to push a small commit adding styling to the `manifests` template?
Basically I would like the `content` to be formatted (it currently only ever contains YAML), that would be amazing :).

**Comment by phillip-kruger** [comment]
We already pull in codemirror for other code snippets, so we should be able to render this a little nicer. See https://codemirror.net/5/mode/yaml/

I can look at this later this week if you want

**Comment by phillip-kruger** [comment]
Stacking the filename and file contents might also make this nicer (remove the big while space on the left). I'll look at that too

**Comment by phillip-kruger** [comment]
In the config editor you can see the property file, and that use code mirror: https://github.com/quarkusio/quarkus/blob/d33d063a07fc50439e15c4fdaaecb85049db39ab/extensions/vertx-http/deployment/src/main/resources/dev-templates/io.quarkus.quarkus-vertx-http/config.html#L32

**Review by iocanel — APPROVED** [review]
Looks great!

**Comment by geoand** [comment]
@phillip-kruger should I merge this or do you want me to keep it open for you? Whatever works best :)

**Comment by phillip-kruger** [comment]
Let's merge here, I'll add on top

**Pull request merged**
