### PR TITLE
Revert "Fix usage of class not available in Java 9+", fixes #2207

### LINKED ISSUE #2207: [camel] Could not find field com.sun.beans.WeakCache.map
Building native images is broken because of the following error:

```
Error: should not reach here: Could not find field com.sun.beans.WeakCache.map on class io.quarkus.camel.core.runtime.graal.Target_com_sun_beans_WeakCache
    object com.sun.beans.WeakCache
    field java.beans.Introspector.declaredMethodCache
```

### PR DESCRIPTION
**Pull request by gnodet**
This reverts commit c1c51b8fefd26359557b214cae8e2489d6be62a9.

### CODE REVIEW

**Comment by gsmet** [comment]
I have a very similar issue with the substitution I wanted to put in place for `SSLContext`.

The issue here is that it won't build with JDK 11 anymore. And you can't add `--export` for the compiler as we are targeting JDK 8.

Not sure what we can do here unfortunately.

@dmlloyd any idea?

**Comment by dmlloyd** [comment]
What if instead of reverting this, we added an alias for the `map` field in the substitution class?

**Comment by gnodet** [comment]
@dmlloyd I think that's what your original commit was doing, but it does not seem to work on JDK 8 native anymore.

**Comment by dmlloyd** [comment]
No, my original class just added a substitution for the class that is in 8 only.  If adding an alias for the field doesn't help (the field it's actually complaining about in quarkusio/quarkus-quickstarts#166) then a better fix might be to add an `onlyWith` qualifier.

**Comment by gnodet** [comment]
I don't think the `onlyWith` approach would work, the JDK related code has not changed between jdk8 and jdk11, the only problem is that the class is not accessible anymore in jdk11.
I'll try adding an alias for the `map` field and report.

**Comment by dmlloyd** [comment]
My last comment was inaccurate.  What I should have said was - the substitution was for a class that is only *directly visible* when compiling with 8.  The class is still present in 11 - it's just not in a default module.

**Comment by gnodet** [comment]
I think my last fix will work as a work around, but could be a problem for non trivial classes.

**Comment by gnodet** [comment]
Fwiw, I've tried with an alias on `map`:
```
@TargetClass(className = "com.sun.beans.WeakCache")
final class Target_com_sun_beans_WeakCache<K, V> {

    @Alias
    private Map<K, Reference<V>> map = new WeakHashMap<>();

    @Alias
    public Target_com_sun_beans_WeakCache() {
    }

}

@TargetClass(className = "java.beans.Introspector")
final class Target_java_beans_Introspector {

    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.FromAlias)
    private static Target_com_sun_beans_WeakCache<Class<?>, Method[]> declaredMethodCache = new Target_com_sun_beans_WeakCache<>();

}
```
but this leads to the same results as before:
```
Error: should not reach here: Could not find field com.sun.beans.WeakCache.map on class io.quarkus.camel.core.runtime.graal.Target_com_sun_beans_WeakCache
	object com.sun.beans.WeakCache
	field java.beans.Introspector.declaredMethodCache
```

**Comment by dmlloyd** [comment]
This is really looking more and more like a GraalVM bug (given the whole `should not reach here` bit).

**Comment by gnodet** [comment]
Maybe, but it we could get the workaround in in the meantime, that would allow Camel to be used in native mode ;-)

**Comment by dmlloyd** [comment]
We're just choosing between two breakages, are we not?

**Comment by gnodet** [comment]
I don't think so.  The current PR may be ugly but it works on both JDK 8 and JDK 11.  That was not the case with the PR earlier today which was doing a revert, but this is not the case anymore by completely substituting the WeakCache class.

**Comment by dmlloyd** [comment]
Ah I thought you were saying that the current PR didn't work.

**Review by dmlloyd — APPROVED** [review]
If this solves the problem, let's go with it.

**Pull request merged**
