### PR TITLE
Fix codestart for kotlin serialization (Gradle, Gradle Kotlin and Maven)

### LINKED ISSUE #33622: Resteasy reactive kotlin serialization not completely configured after generating app from code.quarkus.io
### Describe the bug

Creating an app through code.quarkus.io with 

- kotlin
- resteasy reactive kotlin serialization
- maven

do not configure the kotlin-maven-plugin to use kotlinx-serialization.

Without doing this, kotlin serialization will not work, and the following error will be given when returning an object where content type is application_json

```
kotlinx.serialization.SerializationException: Serializer for class 'Result' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

        at kotlinx.serialization.internal.PlatformKt.serializerNotRegistered(Platform.kt:31)
```

### Expected behavior

When selecting the resteasy reactive kotlin serialization extension, the kotlin-maven-plugin should also be configured in pom.xml.

```xml
     <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <version>${kotlin.version}</version>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-allopen</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-serialization</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <javaParameters>true</javaParameters>
          <jvmTarget>17</jvmTarget>
          <compilerPlugins>
            <plugin>all-open</plugin>
            <plugin>kotlinx-serialization</plugin>
          </compilerPlugins>
          <pluginOptions>
            <option>all-open:annotation=jakarta.ws.rs.Path</option>
            <option>all-open:annotation=jakarta.enterprise.context.ApplicationScoped</option>
            <option>all-open:annotation=io.quarkus.test.junit.QuarkusTest</option>
          </pluginOptions>
        </configuration>
      </plugin>
```

### Actual behavior

The generated kotlin-maven-plugin in pom.xml is without the kotlinx.serialization plugin

```xml
      <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <version>${kotlin.version}</version>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-allopen</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <javaParameters>true</javaParameters>
          <jvmTarget>17</jvmTarget>
          <compilerPlugins>
            <plugin>all-open</plugin>
          </compilerPlugins>
          <pluginOptions>
            <option>all-open:annotation=jakarta.ws.rs.Path</option>
            <option>all-open:annotation=jakarta.enterprise.context.ApplicationScoped</option>
            <option>all-open:annotation=io.quarkus.test.junit.QuarkusTest</option>
          </pluginOptions>
        </configuration>
      </plugin>
```

### How to Reproduce?

1. Use code.quarkus.io, select maven as build tool and select the kotlin and the resteasy-reactive-kotlin-serialization extension
2. Change GreetingResource.kt generated starter code to

```kotlin
@Path("/hello")
class GreetingResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    fun hello() = Result("Hello from RESTEasy Reactive")
}

@Serializable
data class Result(val greeting : String)
```

Running

```bash
./mvnw test
```

results in 

```
kotlinx.serialization.SerializationException: Serializer for class 'Result' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

        at kotlinx.serialization.internal.PlatformKt.serializerNotRegistered(Platform.kt:31)
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ia3andy**
Fix #33622 

Includes tests

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
The other failures don't look related and a rebase might help but the failures in `KotlinSerializationCodestartTest` look related.

**Comment by ia3andy** [comment]
It should be fixed on the last commit

**Comment by ia3andy** [comment]
if I start always running all the Quarkus CI on my machine for all PRs, I can stop working now :)
This ran CI too many times I agree, but this is unusual.

**Comment by ia3andy** [comment]
@gsmet can we merge this?

**Review by gsmet — APPROVED** [review]
Sorry for the delay. I rebased to make sure CI still passes and then we can merge.

**Comment by gsmet** [comment]
I fixed the PR to take into account the Quarkus REST renaming. The failing tests are OK on my laptop now, I just hope I didn't break something else in passing, CI will be the judge of that :).

**Pull request merged**
