### PR TITLE
Bump vertx to 4.4.3

### PR DESCRIPTION
**Pull request by shivarm**
Bump vertx to 4.4.3

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @geoand @gsmet

**Comment by geoand** [comment]
Vertx updates are usually far more involved and are performed almost exclusively by @cescoffier

**Comment by geoand** [comment]
Vertx updates are usually far more involved and are performed almost exclusively by @cescoffier

**Comment by cescoffier** [comment]
Yes, I started, but it's long, and requires checks in 6 projects before upgrading in Quarkus.

**Comment by cescoffier** [comment]
Also, the netty version need a bump.

**Comment by shivam-sharma7** [comment]
> Also, the netty version need a bump.

do you want this in same branch?

**Comment by cescoffier** [comment]
I will do it. But as I said, there are lots of checks and sometimes release to do before updating Vert.x.

It starts in the mutiny bindings where we check that the API can be generated and do not have any changes. 
Then we check stork, and reactive messaging. 
The , we look at Quarkus http.
Finally we do the update in Quarkus.

**Comment by geoand** [comment]
@shivam-sharma7 I am going to close this because as explained the process is a lot more very involved than it seems. 

Thanks however for taking a shot at it!

**Pull request closed without merging**
