### PR TITLE
Update to smallrye-jwt-2.1.1

### LINKED ISSUE #7618: JWT groups as string causes 401
**Describe the bug**
A JWT with a string in the "groups" claim causes the authentication to fail. Es:
```
  "groups": "WEBAPP_GROUP",
```

**Expected behavior**
The authentication completes successfully (as on Quarkus v0.23.0).

**Actual behavior**
A 401 is returned because of this exception:
```
org.jose4j.jwt.MalformedClaimException: The value of the 'groups' claim is not the expected type (WEBAPP_GROUP - Cannot cast java.lang.String to java.util.List)
         at org.jose4j.jwt.JwtClaims.getClaimValue(JwtClaims.java:256)
         at org.jose4j.jwt.JwtClaims.getStringListClaimValue(JwtClaims.java:310)
         at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator.authenticate(MpJwtValidator.java:68)
         at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator.authenticate(MpJwtValidator.java:28)
         at ...
```

**To Reproduce**
1. Checkout the following reproducer: https://github.com/antoniomacri/quarkus-jwt-groups-string
2. git checkout master
3. mvn test --> test with string fails, test with array ok
4. git checkout v0.23.0
5. mvn test --> both tests ok

**Environment (please complete the following information):**
Quarkus 1.2.1.Final.
This previously worked on Quarkus 0.23.0.

### PR DESCRIPTION
**Pull request by sberyozkin**
Also Fixes #7618. 

Thanks to @cescoffier for the help with `smallrye-jwt-2.1.1` release after `2.1.0` failed.

### CODE REVIEW

**Comment by gsmet** [comment]
How critical is this?

/cc @michalszynkiewicz

**Review by gastaldi — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
Easier for me if we don't backport; not a big problem if we do.

**Comment by SchulteMarkus** [comment]
The new option ```smallrye.jwt.always-check-authorization``` is really a nice one, I am using it as part of my Quarkus application already (HowTo¹). I would highly appreciate having smallrye-jwt-2.1.1 as part of Quarkus1.3

¹ In Gradle, by forcing the version
```groovy
configurations.all {
  resolutionStrategy {
    // v2.1.x required, because of feature "smallrye.jwt.always-check-authorization"
    // TODO Can be removed, once Quarkus includes smallrye-jwt:v.2.1.x itself
    force 'io.smallrye:smallrye-jwt:2.1.1'
  }
}
```

**Comment by sberyozkin** [comment]
Hi All, note that the transition from `2.0.13` to `2.1.1` has been done because it was better for Darran to have a 2.0.x line finalized for it to be managed in the WildFly releases better, so it does not indicate some new dependencies have been added, and `2.1.0` release failed, so it is `2.1.1`.
Let me merge then, @gsmet, @michalszynkiewicz, I'll support your decision about the backmerge

**Comment by sberyozkin** [comment]
@SchulteMarkus Hi, thanks for already testing the new option :-)

**Comment by gsmet** [comment]
OK, I will backport as it sounds better to do it. Hopefully, it won't be too much work for @michalszynkiewicz .

**Comment by masini** [comment]
Thank you @gsmet, we have a blocking issue solved in this version.

**Comment by sberyozkin** [comment]
@gsmet Thanks

**Pull request merged**
