### PR TITLE
Fix JAX-RS SecurityContext authScheme problem and sync jwt-guide with the current demo source

### LINKED ISSUE #4573: Wrong behavior in Using JWT RBAC guide
Following the [Using JWT RBAC guide](https://quarkus.io/guides/jwt-guide) section "finally-secured-access-to-securedroles-allowed" the expected curl result is `hello + jdoe@quarkus.io, isSecure: false, authScheme: MP-JWT, hasJWT: true` but the outcome differs.

Also this warning is reported: `WARN: Unrecognized configuration key "quarkus.smallrye-jwt.auth-mechanism" provided`

**Expected behavior**

Expected `authScheme: MP-JWT`  and no WARN report.

**Actual behavior**

`authScheme: BASIC` in resource report and warning about unrecognized configuration key.

**To Reproduce**
1. git clone https://github.com/quarkusio/quarkus-quickstarts.git
2. run integratest unit test
3. test pass but unexpected behavior

**Configuration**
The one provided in quickstart

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux 2018-00002 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: `openjdk version "1.8.0_222" OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-linux64) (build 1.8.0_222-b10) OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-linux64) (build 25.222-b10, mixed mode)`
 - Quarkus version or git rev: `0.24.0`

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #4573

### CODE REVIEW

**Comment by sberyozkin** [comment]
Oh, that `BearerTokenAuthorizationTest` :-) ! I'm too tired now to look into it, I'll try to add some waiting code to that test tomorrow

**Comment by filippobuletto** [comment]
Love the shift towards jose4j 😃

**Comment by sberyozkin** [comment]
@filippobuletto we will do a better job later on and provide smallrye-jwt API for generating the tokens.

**Comment by geoand** [comment]
Can you please rebase onto the latest `master`? 

There is a CI fix that should take care of the error reported.

Thanks

**Comment by geoand** [comment]
Looks good to me although I'm no JWT expert :P

**Comment by sberyozkin** [comment]
Hey @geoand - This code only does a simple fix to the authentication scheme check (returns the first part of the `Authorization` header value) and sync the guide to the current quick-start demo code.

**Comment by geoand** [comment]
@sberyozkin cool, thanks! I guess there were some formatting changes that made it harder to read in the GitHub UI.

**Review by geoand — APPROVED** [review]

**Comment by sberyozkin** [comment]
@geoand Thanks

**Pull request merged**
