### PR TITLE
Do not use latest in the Dockerfile.jvm

### PR DESCRIPTION
**Pull request by cescoffier**
Avoid issues such as https://github.com/quarkusio/quarkus/issues/5848

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Of course yes for anything that doesn't use `latest`!

**Comment by gsmet** [comment]
How will we deal with security updates to the image?

**Comment by geoand** [comment]
We'll probably have to check it periodically

**Comment by cescoffier** [comment]
Yes, we will have to check periodically.

With `latest` security updates are not covered either as you get the `latest` from the initial pull, and then you need to pull again explicitly.

**Comment by jaikiran** [comment]
I was under the impression that `latest` would mean that docker, during the build process, would fetch any changes as compared to any previously locally downloaded image. Apparently not. Looks like `--pull` needs to be explicitly passed to `docker build` for that to work https://github.com/moby/moby/pull/9281, which would mean updating our docs to show the usage of this option. But then that's not enforcable in any way. So I think sticking to a specific version and then regularly updating that version in our `Dockerfile` is the better way to go about it.

**Comment by geoand** [comment]
Yes, `latest` causes way to many problems and in my experience should avoided like the plague! 
The even worse thing is that you usually have no idea what went wrong since PRs or examples failing for no apparent reason.

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
