### PR TITLE
lay some ground work for support of multiple persistence units in Panache

### PR DESCRIPTION
**Pull request by machi1990**
As proposed by Guillaume in this comment https://github.com/quarkusio/quarkus/issues/2759#issuecomment-531191748

/cc @gsmet

### CODE REVIEW

**Comment by cescoffier** [comment]
What's the status of this PR?

**Comment by machi1990** [comment]
@cescoffier it is on-ice for the moment. I am yet to discuss with @gsmet in details about the approach.

**Comment by gsmet** [comment]
@Sanne @FroMage just wanted you to be aware of that one. @machi1990 already did some preliminary work on the multiple PU support in Panache.

**Comment by FroMage** [comment]
OK cool, you want me to review, or not yet?

**Comment by gsmet** [comment]
Well, just wanted you both to be aware of that as Sanne will probably start working soon on multiple PU support. I wouldn't want us to duplicate the work.

**Comment by machi1990** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/8695 as this PR was several months old and needed a needed a rebase.

**Pull request closed without merging**
