### PR TITLE
Fix #1701: mark `isPersistent()` method transient

### LINKED ISSUE #1701: Panache: mark `isPersistent()` method transient
As seen in #1662

### PR DESCRIPTION
**Pull request by FroMage**
for isTransient():
- hibernate does not care, since it the class is not annotated
- jaxb ignores it since it has no setter
- for jsonb I generate an override in subtypes marked @JsonbTransient to avoid depending on jsonb

for mapped public fields:
- for jaxb: add the @XmlTransient annotation to the field to make it use the accessors
- for jsonb: nothing needed since it will ignore it and use the accessors

### CODE REVIEW

**Comment by FroMage** [comment]
@gsmet if it wasn't Friday and I wasn't about to leave I would say it could be a candidate for the 0.13 branch, but it's probably too risky.

**Comment by gsmet** [comment]
Hmmm, maybe it's a stupid question but couldn't you make the jsonb dependency optional and use the annotation?

Annotations that are not available at runtime should be simply ignored AFAIK.

**Comment by FroMage** [comment]
Hah, I did not think of that. @aloubyansky would that work even with the bootstrap resolving? If yes I think it's a better idea than what I did.

**Comment by aloubyansky** [comment]
The default is only the direct optional dependencies are collected.

**Comment by FroMage** [comment]
> The default is only the direct optional dependencies are collected

Direct from what source?

**Comment by aloubyansky** [comment]
User application.

**Comment by FroMage** [comment]
OK thanks, so it should work. Lemme change my PR then.

**Comment by aloubyansky** [comment]
BTW, you can `quarkus-bootstrap:build-tree` on the app to see what's used for the build.

**Comment by FroMage** [comment]
OK, rebased and use optional dep on jsonb now. Let's wait for the tests to pass.

**Comment by FroMage** [comment]
Ah great, it can't index the entity due to the optional dependency I guess?

**Comment by FroMage** [comment]
Stupid exception:

```
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: java.lang.IllegalStateException: Failed to index: io.quarkus.hibernate.orm.panache.PanacheEntityBase
	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:257)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassTestDescriptor.java:361)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllCallbacks(ClassTestDescriptor.java:361)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: java.lang.IllegalStateException: Failed to index: io.quarkus.hibernate.orm.panache.PanacheEntityBase
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:137)
	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:220)
	... 35 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: java.lang.IllegalStateException: Failed to index: io.quarkus.hibernate.orm.panache.PanacheEntityBase
	at io.quarkus.builder.Execution.run(Execution.java:124)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:137)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:108)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:102)
	... 36 more
Caused by: java.lang.IllegalStateException: Failed to index: io.quarkus.hibernate.orm.panache.PanacheEntityBase
	at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:48)
	at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:53)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:507)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:414)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.jboss.jandex.Indexer.verifyMagic(Indexer.java:1288)
	at org.jboss.jandex.Indexer.index(Indexer.java:1587)
	at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:45)
```

**Comment by FroMage** [comment]
@stuartwdouglas do you have any idea how I can solve that? I tried:

```xml
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>javax.json.bind</groupId>
                        <artifactId>javax.json.bind-api</artifactId>
                        <version>1.0</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>make-index</id>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

But no luck.

**Comment by FroMage** [comment]
Nevermind, I found it.

**Comment by FroMage** [comment]
I think I found it, but I'll need @stuartwdouglas 's review on the 77daf775d220f22af93147ea73e5d9c94af4e3a2 commit.

**Comment by FroMage** [comment]
Hum, the test failures don't seem related to this PR:

```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
Unable to find image 'quay.io/quarkus/centos-quarkus-native-image:graalvm-1.0.0-rc14' locally
docker: Error response from daemon: Get https://quay.io/v2/: EOF.
See 'docker run --help'.
```

**Comment by gsmet** [comment]
You can rerun the failing tests from the Azure UI. I'll do it.

**Comment by FroMage** [comment]
Oh thanks. it passed now.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by FroMage** [comment]
Thanks.

**Pull request merged**
