### PR TITLE
Support Spring Data JpaRepository#getReferenceById(ID)

### LINKED ISSUE #41987: Support Spring Data `JpaRepository#getReferenceById(ID)` (replacement for deprecated `getOne(ID)`)
### Description

`JpaRepository#getOne(ID)` was marked deprecated a long time ago: https://github.com/spring-projects/spring-data-jpa/issues/1697
and javadoc suggests to use `getReferenceById`: https://github.com/spring-projects/spring-data-jpa/pull/2398
In Quarkus, we are seeing this deprecation since #40344.

Now, when trying to use `getReferenceById` the following is thrown:
```
io.quarkus.spring.data.runtime.FunctionalityNotImplemented: Method getReferenceById of class foo.BarRepository_cbd379646a149ba2465a399aca3df36673c2a7c1Impl from Spring Data has not yet been implemented
```

### Implementation ideas

Support `getReferenceById` just like `getOne`

### PR DESCRIPTION
**Pull request by aureamunoz**
Fixes #41987

### CODE REVIEW

**Comment by geoand** [comment]
Won't this change remove `JpaRepository#getOne(ID)`? 
We should not remove it, but instead have the new method be an additional one

**Comment by geoand** [comment]
Furthermore, we should have tests using both the new and the deprecated method

**Comment by aureamunoz** [comment]
Initially, I thought about keeping the StockMethodsAdder#getOne method and adding a new one. However, since getOne was private and only used in one place, I decided to refactor it instead. I renamed the method and its variables to getReferenceById. As RepositorySupport#getOne is public, I didn't delete it. Instead, I marked it as @Deprecated and added a new method, RepositorySupport@getReferenceById.

Regarding the tests I'm not sure to understand, I added a [few tests](https://github.com/quarkusio/quarkus/pull/41993/files#diff-de742f6ebcba5e2d5b22618347b6f564d452b2b16d54354fa7c600e198e20f0dR157-R167) using both. What do you exactly mean?

**Comment by geoand** [comment]
> Regarding the tests I'm not sure to understand, I added a [few tests](https://github.com/quarkusio/quarkus/pull/41993/files#diff-de742f6ebcba5e2d5b22618347b6f564d452b2b16d54354fa7c600e198e20f0dR157-R167) using both. What do you exactly mean

I had missed those I guess. If these pass, we are fine

**Comment by aureamunoz** [comment]
Looking at this

**Comment by geoand** [comment]
The problem is likely what I mentione earlier: The change seems to have removed the implementation of the `getOne` method

**Comment by aureamunoz** [comment]
Yes, it seems to be a good reason to keep adding the deprecated methods implems :laughing:
I refactored and added a few more that were lacking.

Let's see what the CI says

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
Can this also be backported to 3.12? My reasoning would be that the Spring API update was also done in 3.12.

**Comment by geoand** [comment]
Sure yeah

**Pull request merged**
