### PR TITLE
Introduce `quarkus.http.filter` config

### LINKED ISSUE #25047: Allow having different http headers depending on the path
### Description

Currently it's only possible to set the header for one specific path:
```properties
quarkus.http.header.Pragma.value=no-cache
quarkus.http.header.Pragma.path=/headers/pragma
quarkus.http.header.Pragma.methods=GET,HEAD
````
It would be nice to be able to do it for multiple paths. Something like:
```properties
quarkus.http.header.path."/static/*".Cache-Control.value=max-age=31536000
quarkus.http.header.path."/index.html".Cache-Control.value=no-cache
```

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #25047

### CODE REVIEW

**Comment by ia3andy** [comment]
As there is no guarantee on properties order, maybe there should be an optional `priority` field to be able to order the filters?

**Comment by sberyozkin** [comment]
We already have `quarkus.http.root-path`, I wonder if it makes sense to have something like `quarkus.http.headers...` or similar to reflect it is primarily about the headers for specific paths

**Comment by ia3andy** [comment]
> We already have `quarkus.http.root-path`, I wonder if it makes sense to have something like `quarkus.http.headers...` or similar to reflect it is primarily about the headers for specific paths

Yes, I agree with this too, this is what I suggested in the issue: https://github.com/quarkusio/quarkus/issues/25047#issue-1209879249

**Comment by gastaldi** [comment]
> We already have `quarkus.http.root-path`, I wonder if it makes sense to have something like `quarkus.http.headers...` or similar to reflect it is primarily about the headers for specific paths

👎🏻 for two reasons:

1) there is already `quarkus.http.header.`, introducing the plural form here would lead to confusion;
2) This config doesn't have to be only about headers. Because the path is the first level, it could be extended in the future to (hypotetically) specify cookies for example:

```application
quarkus.http.path."/foo".cookie.Foo.value=Bar
```

**Comment by gastaldi** [comment]
> As there is no guarantee on properties order, maybe there should be an optional `priority` or `order` field to be able to order the filters?

👍🏻, That is a good idea, I'll add it

**Comment by gsmet** [comment]
I'm a bit torn about the name. I think it might become a problem.

**Comment by gastaldi** [comment]
> I'm a bit torn about the name. I think it might become a problem.

Can you elaborate a bit more?

**Comment by gsmet** [comment]
Sorry if it was unclear. It's extremely generic and I'm not sure it won't conflict with things we would want to do in the future.
I can't think of a better name right now though so it's not a -1 from me, just a concern.

**Comment by ia3andy** [comment]
> > We already have `quarkus.http.root-path`, I wonder if it makes sense to have something like `quarkus.http.headers...` or similar to reflect it is primarily about the headers for specific paths
> 
> 👎🏻 for two reasons:
> 
> 1. there is already `quarkus.http.header.`, introducing the plural form here would lead to confusion;
> 2. This config doesn't have to be only about headers. Because the path is the first level, it could be extended in the future to (hypotetically) specify cookies for example:
> 
> ```
> quarkus.http.path."/foo".cookie.Foo.value=Bar
> ```

ok, you nearly convinced me :) but I would argue that you could still be consistant with `quarkus.http.cookie.path."/foo".Foo.value=Bar` and it would keep them separated.

**Comment by ia3andy** [comment]
Thanks @gastaldi, I will give it a try today :)

**Review by ia3andy — APPROVED** [review]
It's pretty cool !

Tested successfully for React with:
```
quarkus.quinoa.dev-server-port=3000
quarkus.http.path."/.*".header.Cache-Control=no-cache
quarkus.http.path."/.*".methods=GET
quarkus.http.path."/.*".order=0
quarkus.http.path."/static/.+".header.Cache-Control=max-age=31536000
quarkus.http.path."/static/.+".order=1
quarkus.http.path."/static/.+".methods=GET
```

**Comment by gastaldi** [comment]
There is one thing I am not completely happy with: the case where you need to configure a different HTTP method per path to have different HTTP headers. Any suggestions?

**Comment by gastaldi** [comment]
Something like this may be an option, but I am not 100% sure if we want to open that can of worms

```properties
quarkus.http.path."/static/.+".method.GET.header.Cache-Control=max-age=31536000
```

**Comment by ia3andy** [comment]
I think it's fine, you can always play with the regex if you really need something different :)

**Comment by gastaldi** [comment]
After giving it some thought, I agree with @gsmet that the name may not be suitable. 
Maybe using the plural here might make more sense, as @ia3andy and @sberyozkin also suggested but I'd like some feedback:

How about something like: 
```properties
quarkus.http.response.headers."/.*".Cache-Control=no-cache
```

Well, the following might also work I think:
```properties
quarkus.http.headers."/.*".Cache-Control=no-cache
```

**Review by mamadaliev — APPROVED** [review]

**Review by ebullient — CHANGES_REQUESTED** [review]
quarkus.http.path is going to be confusing. I like either of these alternatives: 

> How about something like:
> 
> `quarkus.http.response.headers."/.*".header.Cache-Control=no-cache`
> 
> Well, the following might also work I think:
> 
> `quarkus.http.headers."/.*".header.Cache-Control=no-cache`

**Comment by gastaldi** [comment]
I have created a poll here: https://github.com/quarkusio/quarkus/discussions/25139

**Comment by gastaldi** [comment]
@ebullient @ia3andy I changed it to `quarkus.http.headers`, let me know if that's better

**Comment by gastaldi** [comment]
I have applied @dmlloyd's suggestion and went with: 

```properties
quarkus.http.by-path.my-app.header.Cache-control=none
quarkus.http.by-path.my-app.matches=/app/*|/other-path|/blah
```

Thoughts?

**Review by ebullient — APPROVED** [review]

**Comment by ia3andy** [comment]
> I have applied @dmlloyd's suggestion and went with:
> 
> ```ini
> quarkus.http.by-path.my-app.header.Cache-control=none
> quarkus.http.by-path.my-app.matches=/app/*|/other-path|/blah
> ```
> 
> Thoughts?

I think it's confusing to have `by-path` but then a name? which is used for what just differentiation?

**Comment by ia3andy** [comment]
Maybe this (in the end the path is not the differentiator anymore)?
`quarkus.http.group.my-app.header.Cache-control=none`

**Comment by gastaldi** [comment]
Not sure if only `group` makes the intention clear, how about:

```properties

quarkus.http.filter.my-app.add-header.Cache-control=none
quarkus.http.filter.my-app.matches=/app/*|/other-path|/blah
```

**Comment by gastaldi** [comment]
Changed to `quarkus.http.filter` now. Let's merge it if no one has any other objections 👍🏻

**Pull request merged**
