### PR TITLE
Fix Kafka kafka-version metrics tag missing in native

### LINKED ISSUE #42865: kafka_version label is unkown in native mode
### Describe the bug

Verifying backport for 3.8.6 https://github.com/quarkusio/quarkus/pull/41278 (_Add kafka-version.properties as a native image resource _ ), and attempting to do a test coverage for our Quarkus test suite.

I've noticed that the kafka_version="unknown" label still appears during native mode execution

### Expected behavior

``kafka_consumer_request_total{client_id="kafka-consumer-words-in",kafka_version="3.7.1}`"`

### Actual behavior

`kafka_consumer_request_total{client_id="kafka-consumer-words-in",kafka_version="unknown"}`

### How to Reproduce?

1. Clone my reproducer:

`    git clone -b kafkaversion-unknown-native https://github.com/jcarranzan/quarkus-reproducer.git `

2.  Execute maven command:

`mvn clean verify -Pnative`

3. See at the end of logs on the native execution:
    
   ```
 ```
    2024-08-29 15:10:17,902 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18229: Configured topics for channel 'words-in': [words]
2024-08-29 15:10:17,903 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18214: Key deserializer omitted, using String as default
2024-08-29 15:10:17,914 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-producer-thread-0) SRMSG18258: Kafka producer kafka-producer-words-out, connected to Kafka brokers 'OUTSIDE://localhost:32797', is configured to write records to 'words'
2024-08-29 15:10:17,918 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-0) SRMSG18257: Kafka consumer kafka-consumer-words-in, connected to Kafka brokers 'OUTSIDE://localhost:32797', belongs to the 'code-with-quarkus' consumer group and is configured to poll records from [words]
2024-08-29 15:10:17,919 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 3.14.1) started in 0.040s. Listening on: http://0.0.0.0:8081
2024-08-29 15:10:17,919 INFO  [io.quarkus] (main) Profile prod activated. 
2024-08-29 15:10:17,919 INFO  [io.quarkus] (main) Installed features: [cdi, kafka-client, messaging, messaging-kafka, micrometer, resteasy, smallrye-context-propagation, vertx]
RESPONEEEEEE  # TYPE kafka_consumer_fetch_manager_fetch_latency_max gauge
# HELP kafka_consumer_fetch_manager_fetch_latency_max The max time taken for any fetch request.
kafka_consumer_fetch_manager_fetch_latency_max{client_id="kafka-consumer-words-in",kafka_version="unknown"} 500.0
# TYPE kafka_consumer_coordinator_rebalance_latency_max gauge
# HELP kafka_consumer_coordinator_rebalance_latency_max The max time taken for a group to complete a successful rebalance, which may be composed of several failed re-trials until it succeeded
kafka_consumer_coordinator_rebalance_latency_max{client_id="kafka-consumer-words-in",kafka_version="unknown"} 2.0
```

### PR DESCRIPTION
**Pull request by ozangunalp**
Call registerMetrics in AppInfoParser substitution

Fixes #42865

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
@jcarranzan any chance you could check if this fixes your issue? Thanks!

**Comment by jcarranzan** [comment]
> @jcarranzan any chance you could check if this fixes your issue? Thanks!

Hi @gsmet @ozangunalp (thanks for looking at this) I've just executed my reproducer again and still see `kafka_version="unknown"` in the logs.
My reproducer--> ` git clone -b kafkaversion-unknown-native https://github.com/jcarranzan/quarkus-reproducer.git`
Execution: `$ mvn clean verify -Pnative`


PW: Next week I'll be on PTO,

**Comment by ozangunalp** [comment]
It was my bad that the issue isn't resolved in the initial PR.

But I do think this one resolves it. 
@jcarranzan did you run it with a local Quarkus build containing this fix?

**Comment by jedla97** [comment]
Hi @ozangunalp I checked @jcarranzan provided reproducer and it seems to work. Don't see any `"afka_version="unknown"` in the test logs. When tried it with 3.14.1 I see them and one test failing. From this it's safe to assume that this PR fix should fix the issue.

**Pull request merged**
