### PR TITLE
Upgrade GraalVM to 19.3.2

### PR DESCRIPTION
**Pull request by gsmet**
Note that I don't throw an error if 19.3.1 is used as I don't see a good
reason to do it.

Still, I'm recommending either 19.3.2 or 20.0.0 in the error message.

Creating as a draft while waiting for the images to be available.

### CODE REVIEW

**Comment by gsmet** [comment]
The security LDAP native tests are failing with:
```
2020-05-18T09:02:37.7824391Z 2020-05-18 09:02:37,780 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /api/requiresStandardRole failed, error id: b31b25f9-8596-47fb-a808-cd4b144ec5a0-1: com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.createOrGetClassLoaderValueMap()
2020-05-18T09:02:37.7824775Z 	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
2020-05-18T09:02:37.7828325Z 	at java.lang.ClassLoader.createOrGetClassLoaderValueMap(Target_java_lang_ClassLoader.java:184)
2020-05-18T09:02:37.7841621Z 	at java.lang.System$2.createOrGetClassLoaderValueMap(System.java:2126)
2020-05-18T09:02:37.7841842Z 	at jdk.internal.loader.AbstractClassLoaderValue.map(AbstractClassLoaderValue.java:266)
2020-05-18T09:02:37.7849727Z 	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:189)
2020-05-18T09:02:37.7857719Z 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:711)
2020-05-18T09:02:37.7864037Z 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
2020-05-18T09:02:37.7865997Z 	at javax.naming.InitialContext.init(InitialContext.java:236)
2020-05-18T09:02:37.7866235Z 	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
2020-05-18T09:02:37.7870244Z 	at io.quarkus.elytron.security.ldap.QuarkusDirContextFactory.createDirContext(QuarkusDirContextFactory.java:110)
2020-05-18T09:02:37.7870481Z 	at io.quarkus.elytron.security.ldap.QuarkusDirContextFactory.obtainDirContext(QuarkusDirContextFactory.java:50)
2020-05-18T09:02:37.7870657Z 	at io.quarkus.elytron.security.ldap.LdapRecorder.lambda$createDirContextSupplier$0(LdapRecorder.java:52)
2020-05-18T09:02:37.7874153Z 	at org.wildfly.security.auth.realm.ldap.LdapSecurityRealm.obtainContext(LdapSecurityRealm.java:202)
2020-05-18T09:02:37.8253294Z 	at org.wildfly.security.auth.realm.ldap.LdapSecurityRealm.access$600(LdapSecurityRealm.java:101)
2020-05-18T09:02:37.8256828Z 	at org.wildfly.security.auth.realm.ldap.LdapSecurityRealm$LdapRealmIdentity.verifyEvidence(LdapSecurityRealm.java:590)
2020-05-18T09:02:37.8260377Z 	at org.wildfly.security.auth.server.ServerAuthenticationContext$NameAssignedState.verifyEvidence(ServerAuthenticationContext.java:2006)
2020-05-18T09:02:37.8267026Z 	at org.wildfly.security.auth.server.ServerAuthenticationContext.verifyEvidence(ServerAuthenticationContext.java:761)
2020-05-18T09:02:37.8267281Z 	at org.wildfly.security.auth.server.SecurityDomain.authenticate(SecurityDomain.java:309)
2020-05-18T09:02:37.8267425Z 	at org.wildfly.security.auth.server.SecurityDomain.authenticate(SecurityDomain.java:285)
```

@galderz any idea where the problem could be?

We will move to 20 soon but I thought it would be nice to have 19.3.2 working anyway.

**Comment by galderz** [comment]
We already spotted this: https://github.com/oracle/graal/issues/2367. I also had a quarkus issue about this: https://github.com/quarkusio/quarkus/issues/8651. A workaround might be the easiest for 19.3.x support: https://github.com/galderz/quarkus/commit/10ae381eccc63192734d9e22254a5a84cf248766

**Comment by gsmet** [comment]
@galderz could you add this commit to my PR?

**Comment by galderz** [comment]
@gsmet Sure, let me try

**Comment by galderz** [comment]
@gsmet Couldn't push to your branch, but sent you a PR to your branch.

**Comment by gsmet** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/9486 .

**Pull request closed without merging**
