### PR TITLE
Allow delete clause in delete queries in Panache

### LINKED ISSUE #18502: PanacheEntityBase.delete(String query, Parameters params) doesn't work with SQL prefix - java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: DELETE
## Describe the bug
If I pass the SQL DELETE prefix command to the `String query` of the  `PanacheEntityBase.delete(String query, Parameters params)`, I receive the following error:
```
org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: DELETE
```

Example of `String query`:
> DELETE FROM Product P WHERE userName = :userName AND shoppingName = :shoppingName

If I omit the SQL prefix as below, everything works fine:
> userName = :userName AND shoppingName = :shoppingName

Command:
```java
delete(query, Parameters.with("userName", userName).and("shoppingName", shoppingName));
```

**I don't know if this is a bug or I misunderstood the `String query` parameter.**

The `find(String query, Parameters params)` and `update(String query, Parameters params)` methods work perfectly with or without the SQL prefix.

### Expected behavior
PanacheEntityBase.delete(String query, Parameters params) should work with or without the SQL DELETE prefix.

### Actual behavior
PanacheEntityBase.delete(String query, Parameters params) don't work with the SQL DELETE prefix.

## To Reproduce

```
$ git clone https://github.com/felipewind/panache-delete-test
$ ./mvnw quarkus:dev
```

Access `http://localhost:8080/q/swagger-ui`.

Here you can test the find(), update() and delete() methods with or without the SQL prefix:

image

Each endpoint has a Query Parameter named `useSqlPrefix` where you can choose if you will or not use the SQL prefix:

image

### Configuration
```properties
# Log
%dev.quarkus.log.category."org.acme".level=DEBUG
%dev.quarkus.log.min-level=TRACE

# Database
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.driver=org.h2.Driver
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%dev.quarkus.hibernate-orm.log.bind-parameters=true
%dev.quarkus.hibernate-orm.log.sql=true
```

### Output of `uname -a` or `ver`

inux machine 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/helesto/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-59-generic", arch: "amd64", family: "unix"

### PR DESCRIPTION
**Pull request by FroMage**
Fixes #18502

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM.

I think the same documentation that you add in the package-info.java is inside the guide. Maybe you also need to update the two corresponding guides.

**Comment by geoand** [comment]
Is this ready to go?

**Comment by FroMage** [comment]
Lemme check the guide then, good point.

**Comment by FroMage** [comment]
Well spotted: updated guides.

**Pull request merged**
