### PR TITLE
Delegate projections with a `select` clause to ORM

### LINKED ISSUE #31117: Exception in panache, when using newline before `from`
### Describe the bug

I have an application, made with Hibrnate reactive and Panache. I run `find` method for HQL query with a new-line character before `FROM` clause. The operation fails with an exception.

### Expected behavior

New lines in query should not affect the result

### Actual behavior

An exception is thrown

### How to Reproduce?

1. Clone the reporducer: `git clone git@github.com:fedinskiy/reproducer.git -b reproducer/hibernate-newline`
2. Start a DB in a separate terminal: 
```
 docker run \
-e POSTGRESQL_USER=user \
-e POSTGRESQL_PASSWORD=user \
-e POSTGRESQL_DATABASE=mydb \
-e POSTGRES_USER=user \
-e POSTGRES_PASSWORD=user \
-e POSTGRES_DB=mydb \
-p 5432:5432 \
docker.io/library/postgres:15
```
3. run the reproducer: `mvn quarkus:dev`
4. Try to access the endpoint:
```
$ curl http://localhost:8080/library/by-author/Dlugi
{"code":500,"error":"begin 7, end -1, length 101"}
```
5. edit file `src/main/java/io/quarkus/ts/hibernate/reactive/http/PanacheEndpoint.java`, add a space between `\n` and "FROM" on line 119
6.``` $ curl http://localhost:8080/library/by-author/Dlugi
[{"title":"Slovník"}] ```

### Output of `uname -a` or `ver`

6.7.3-200.fc39.x86_64

### Output of `java -version`
21.0.1, vendor: Eclipse Adoptium

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

See https://github.com/quarkusio/quarkus/issues/29838 for a similar bug

### PR DESCRIPTION
**Pull request by FroMage**
Problem is that there's a bug in ORM that disallows projections of single columns, but that will be resolved by https://github.com/hibernate/hibernate-orm/pull/7874

Fixes #31117

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM.

You added //FIXME comment that seems more like a dev comment, or a TODO.
I'm not fan of having FIXME in the code, or maybe create an issue describing what needs to be fixed and add the link int the FIXME comment.

**Comment by FroMage** [comment]
Looks like Kotlin is testing single field projections…

**Comment by FroMage** [comment]
>  You added //FIXME comment that seems more like a dev comment, or a TODO.
> I'm not fan of having FIXME in the code, or maybe create an issue describing what needs to be fixed and add the link int the FIXME comment.

Yeah, it's something that's always been there I suppose, but it stroke me as a bug, I thought I'd leave a note for the person who'd find the bug and want to fix it later.

**Comment by FroMage** [comment]
I don't know what to do with this. This fixes reported bugs, but introduces a regression around single-column projections, which is fixed in ORM 6.5.0 (not released yet). Either we wait until ORM is released to merge this, or I merge it because single-column projections are not very common, or I merge this with a workaround for single-column projections until ORM is released.

Any opinion?

**Comment by loicmathieu** [comment]
If ORM 6.5.0 is not too far away, it is better to wait for it than to introduce a regression.

**Comment by FroMage** [comment]
> If ORM 6.5.0 is not too far away, it is better to wait for it than to introduce a regression.

Fair enough.

**Comment by FroMage** [comment]
Rebased on `main` now that we have ORM with the fix.

**Comment by FroMage** [comment]
Well this is weird, it's supposed to be fixed :(

**Comment by FroMage** [comment]
Oh, HR, let's see…

**Comment by FroMage** [comment]
Ah…
```
2024-06-06 14:37:04,093 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /test/projection2 failed, error id: 65e4acde-2a86-408c-8d01-fee35ce85544-1: java.lang.RuntimeException: Cannot count on more than one column
```
I suppose I can add support for that, but it's soon going to be supported by HR…

**Comment by FroMage** [comment]
I can fix that, but then I'm left with `Select item at position 1 in select list has no alias (aliases are required in CTEs and in subqueries occurring in from clause)` which is caused by https://hibernate.atlassian.net/browse/HHH-18234 so it's like for #40962 we're blocked waitin for 6.5.3

**Comment by FroMage** [comment]
OK, last try?

**Pull request merged**
