### PR TITLE
ClassLoader leak fixes

### PR DESCRIPTION
**Pull request by stuartwdouglas**
- In tests don't hold into the initial ClassLoader via the BasicConsole
- DB_CLOSE_DELAY=-1 will hold onto the ClassLoader, as the DB will never
  be closed

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@Sanne should help out with the intermittent hibernate metaspace errors on windows

**Comment by Sanne** [comment]
Are you sure about removing 'DB_CLOSE_DELAY=-1' ?

It will wipe out the database content on connection close: I'm not sure if these tests can deal with that, and might be puzzling for future tests.

**Comment by stuartwdouglas** [comment]
Why would the connection be closed though? Argoal will pool it. As it is every test with that Param leaks the CL (and not all of them have it).

**Comment by Sanne** [comment]
I suppose we can try, but just relying on the connection pool might expose us to race conditions, especially as Agroal isn't pre-filling the pool by default.  cc/ @gsmet you added most of these, WDYT?

So we'd be relying on a side-effect of the pool; I want of course address memory leaks but I wonder if there's a better way.

BTW the business around "DB_CLOSE_DELAY" bites uses regularly as well. Perhaps we should have Agroal enforce keeping a connection open when using H2:mem ? If we make it a feature, then we wouldn't need to rely on a side-effect, and users would benefit as well.

**Comment by stuartwdouglas** [comment]
So the way DevServices handles it is to always add DB_CLOSE_DELAY=-1 to the URL, and then invokes 'SET DB_CLOSE_DELAY 0' to shut it down at the end. 

We could try and handle this automatically for the user but we don't really have any existing hooks for this, so we would need to add them, which is a fair bit of work for an in-memory database. 

What do you think about just changing these tests to use devservices instead?

**Comment by gsmet** [comment]
If the tests pass, I'm OK with removing them. I don't remember if we added them for caution or because it wasn't stable without them.

**Comment by gsmet** [comment]
Oh and just to be clear: we have a lot of users using `DB_CLOSE_DELAY=-1` as we have all sorts of problems without it. So we can remove them from our tests if they pass but you can be sure it's used out there in the wild.

**Comment by stuartwdouglas** [comment]
This issue is with QuarkusUnitTest and QuarkusDevModeTest, rather than QuarkusTest. Because we setup whole new isolated class loaders each time class loader leaks start to add up. With @QuarkusTest this is not really an issue, unless you have a lot of profiles.

**Comment by Sanne** [comment]
OK then, let's merge this. Thank you both!

> What do you think about just changing these tests to use devservices instead?

Yes that's an idea, but we shoud also think of how end users are going to shoot themselves. I guess we can recommend the same in docs, but it would be even nicer if we could handle things transparently.

In nutshell, I'm inclined we should have ad-hoc code in Agroal to handle this; and if we do it correctly we would be able to intercept|remove|warn when the property is set by users.

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
BTW anyone knows why CI hasn't completed yet? It's been more than 24h...

**Comment by gsmet** [comment]
I cancelled and restarted the workflow.

**Comment by Sanne** [comment]
Interesting, I'm essentially unable to run the ORM testsuite locally today becasue of the leaks fixed in this PR, so this fix seems really urgent now.

But I didn't have such severe issues ~ a week ago?

**Pull request merged**
