### PR TITLE
Generating Jackson serializers for concrete classes only

### LINKED ISSUE #44069: Recently added ReflectionFreeSerializationTest is very unstable
Recently added `ReflectionFreeSerializationTest` has been very unstable.

For instance see: https://github.com/quarkusio/quarkus/pull/44027 . But there were a lot of other failures lately.

Here is the output of the test:

```
2024-10-23T13:02:00.6037919Z 2024-10-23 13:02:00,591 ERROR [io.qua.res.rea.jac.run.map.NativeInvalidDefinitionExceptionMapper] (vert.x-eventloop-thread-1) com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.quarkus.mongodb.panache.reactive.ReactivePanacheMongoEntityBase and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])
2024-10-23T13:02:01.0187642Z [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.73 s <<< FAILURE! -- in io.quarkus.it.mongodb.panache.ReflectionFreeSerializationTest
2024-10-23T13:02:01.0192965Z [ERROR] io.quarkus.it.mongodb.panache.ReflectionFreeSerializationTest.testReactiveBookEntity -- Time elapsed: 1.060 s <<< ERROR!
2024-10-23T13:02:01.0194735Z java.lang.RuntimeException: 
2024-10-23T13:02:01.0196221Z com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
2024-10-23T13:02:01.0198080Z  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
2024-10-23T13:02:01.0200161Z 	at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:30)
2024-10-23T13:02:01.0202739Z 	at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
2024-10-23T13:02:01.0204786Z 	at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
2024-10-23T13:02:01.0206059Z 	at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
2024-10-23T13:02:01.0207526Z 	at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
2024-10-23T13:02:01.0208976Z 	at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
2024-10-23T13:02:01.0210334Z 	at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
2024-10-23T13:02:01.0211587Z 	at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
2024-10-23T13:02:01.0213126Z 	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:229)
2024-10-23T13:02:01.0214803Z 	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl$as$2.callCurrent(Unknown Source)
2024-10-23T13:02:01.0216630Z 	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:246)
2024-10-23T13:02:01.0218379Z 	at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:186)
2024-10-23T13:02:01.0220449Z 	at io.quarkus.it.mongodb.panache.reactive.ReactiveMongodbPanacheResourceTest.callReactiveBookEndpoint(ReactiveMongodbPanacheResourceTest.java:107)
2024-10-23T13:02:01.0222682Z 	at io.quarkus.it.mongodb.panache.ReflectionFreeSerializationTest.testReactiveBookEntity(ReflectionFreeSerializationTest.java:29)
2024-10-23T13:02:01.0224513Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-10-23T13:02:01.0225990Z 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:971)
2024-10-23T13:02:01.0227812Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:821)
2024-10-23T13:02:01.0229276Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-10-23T13:02:01.0230315Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-10-23T13:02:01.0231858Z Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
2024-10-23T13:02:01.0233349Z  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
2024-10-23T13:02:01.0234811Z 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
2024-10-23T13:02:01.0236339Z 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:5008)
2024-10-23T13:02:01.0237972Z 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4910)
2024-10-23T13:02:01.0239293Z 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3860)
2024-10-23T13:02:01.0241153Z 	at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:28)
2024-10-23T13:02:01.0242617Z 	... 18 more
```

### PR DESCRIPTION
**Pull request by mariofusco**
Fixes https://github.com/quarkusio/quarkus/issues/44069

/cc @gsmet

### CODE REVIEW

**Comment by mariofusco** [comment]
@gsmet I don't see any reason why all those tests should fail with JDK21 and I cannot reproduce any of those problems locally. Can you please simply relaunch that job?

**Comment by mariofusco** [comment]
@gsmet sorry, ignore my latest comment, for some reason I cannot reproduce the problem from maven CLI but I can when launching those tests from inside the IDE. I need a bit more time to figure out what's happening.

**Comment by gsmet** [comment]
@mariofusco out of curiosity, what was the issue?

**Comment by mariofusco** [comment]
@gsmet it should be ok now. The problem is that it was uselessly trying to generate serializers also for not concrete classes (abstract classes or interfaces) and moreover trying to register them into the Jackson ObjectMapper caused an error internally to Jackson during serialization.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
That part I understood :). I was more wondering what caused a specific Java 21 failure :)

**Comment by mariofusco** [comment]
> That part I understood :). I was more wondering what caused a specific Java 21 failure :)

Sorry I misunderstood your question :)

Actually it was a real bug in my yesterday's commit. It is true that I don't want to generate serializers for abstract classes, but with what I did yesterday it was skipping in the generated serializers for a concrete class the fields eventually inherited from its abstract parent. To be honest I have no clue why this failed only on Java 21.

**Comment by gsmet** [comment]
OK, thanks!

**Pull request merged**
