### PR TITLE
ci: activate CI for jpa-without-entity integrations native test

### LINKED ISSUE #5368: Run native-image tests for quarkus-integration-test-jpa-without-entity on CI
Follow up to #5343 : I introduced a new integration test which requires to be run in native-image, but forgot to edit the pipelines to enable this.

@machi1990 volunteered :1st_place_medal: Thanks!

### PR DESCRIPTION
**Pull request by machi1990**
This is based on https://github.com/quarkusio/quarkus/pull/5343#issuecomment-552371739

Fixes https://github.com/quarkusio/quarkus/issues/5368

/cc @Sanne @geoand @jaikiran

### CODE REVIEW

**Comment by geoand** [comment]
Thanks @machi1990 !

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Would actually be nice if Azure CI ran this :)

**Comment by machi1990** [comment]
For some reason CI did not pick it :-(

**Comment by geoand** [comment]
@machi1990 perhaps you need to also make a dummy "code" change?

**Comment by machi1990** [comment]
> @machi1990 perhaps you need to also make a dummy "code" change?

We normally have ci runs for this kind of change. Also, tricking the ci with a code change did not help. 
I remember @jmartisk encountered a similar issue where one of his PR was not picked up. Do not remember how was that solved though.

**Review by Sanne — APPROVED** [review]
great. Thanks!

**Comment by machi1990** [comment]
Also the merge of #5343 parent PR is encountering ci failures https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=11930&view=logs 
``` 
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 2ff6fc4f-b2b8-4380-9c16-2d95323a3454
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 2ff6fc4f-b2b8-4380-9c16-2d95323a3454
Information, Minimatch patterns: [**]
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A73d3f287-1d8f-4459-bc46-c7af16e679c5/_apis/dedup/nodes/0C332261DE397A27703EF8006982F80E5637942C0290FFFC5D6753C7DE5250F902 attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False
Information, Filtered 13816 files from the Minimatch filters supplied.
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 1,127.0 MB (0%).
Information, Downloaded 37.1 MB out of 1,127.0 MB (3%).
Information, Downloaded 256.8 MB out of 1,127.0 MB (23%).
Information, Downloaded 443.5 MB out of 1,127.0 MB (39%).
Information, Downloaded 590.1 MB out of 1,127.0 MB (52%).
Information, Downloaded 695.4 MB out of 1,127.0 MB (62%).
Information, Downloaded 800.5 MB out of 1,127.0 MB (71%).
Information, Downloaded 872.4 MB out of 1,127.0 MB (77%).
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A73d3f287-1d8f-4459-bc46-c7af16e679c5/_apis/dedup/urls attempt 1/6 failed with HttpRequestException: 'An error occurred while sending the request.', HttpStatusCode 
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A73d3f287-1d8f-4459-bc46-c7af16e679c5/_apis/dedup/urls attempt 1/6 throwing HttpRequestException with AttemptCount 1, LastBackoff 10000ms
Information, Downloaded 1,104.2 MB out of 1,127.0 MB (98%).
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A73d3f287-1d8f-4459-bc46-c7af16e679c5/_apis/dedup/urls attempt 1/6 failed with HttpRequestException: 'An error occurred while sending the request.', HttpStatusCode 
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A73d3f287-1d8f-4459-bc46-c7af16e679c5/_apis/dedup/urls attempt 1/6 throwing HttpRequestException with AttemptCount 1, LastBackoff 10000ms
Information, Downloaded 1,105.9 MB out of 1,127.0 MB (98%).
Information, Downloaded 1,123.0 MB out of 1,127.0 MB (100%).
Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 2ff6fc4f-b2b8-4380-9c16-2d95323a3454
##[error]One or more errors occurred. (One or more errors occurred. (An error occurred while sending the request.))
##[section]Finishing: DownloadPipelineArtifact
```
something to do with Azure maybe?

**Comment by machi1990** [comment]
Finally picked up by ci and all green. Let's merge this. Thanks @Sanne @geoand

**Pull request merged**
