### PR TITLE
Support Swagger UI in production mode

### LINKED ISSUE #2597: Support a boolean property to enable swagger-ui even not in dev/test modes
**Description**
There have been several requests to have the swagger-ui context/ui enabled even when not running in dev or test mode, primarily for demos and samples.

**Implementation ideas**

@stuartwdouglas commented on the dev list:
Adding a boolean to enable this would be pretty easy. At the moment for dev mode this is extracted into a temp directory, so this would need to change to be placed into the actual runner jar, and set up in a slightly different way.

This will conflict with https://github.com/quarkusio/quarkus/pull/2596 at the moment though, as I have changed the way the caching works.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This adds a flag to enable swagger-ui in the final output

### CODE REVIEW

**Comment by gsmet** [comment]
CI is failing with:
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ServletITCase>ServletTestCase.testWebjars:73 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   ServletITCase>ServletTestCase.testWelcomeFile:51 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "A HTML page"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/

[ERROR]   SwaggerUIITCase>SwaggerUITestCase.testSwaggerUi:32 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "#swagger-ui"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/swagger-ui/

[ERROR] Errors: 
[ERROR]   OpenApiITCase>OpenApiTestCase.testOpenAPIJSON:49 » IO Server returned HTTP res...
```

**Review by gsmet — APPROVED** [review]
Let's get this in, it's a very useful addition.

**Comment by emmanuelbernard** [comment]
This is missing the documentation change to describe the new flag and behavior.

**Comment by stuartwdouglas** [comment]
We really need auto generated config docs.

**Comment by gsmet** [comment]
@emmanuelbernard @stuartwdouglas well, I pushed https://github.com/quarkusio/quarkus/pull/2660 yesterday so I think we are good.

(obviously, generated docs would be better but in this case, the guide needed to be tweaked anyway)

**Pull request merged**
