### PR TITLE
Bump minimum GraalVM version to 22.2.0

### LINKED ISSUE #28475: Module support not available in GraalVM / Mandrel 21.3
### Describe the bug

https://github.com/quarkusio/quarkus/pull/28409 adds support for modules. However, modules are not supported in GraalVM / Mandrel 21.3.

### Expected behavior

Quarkus native integration tests should pass when using 21.3.

### Actual behavior

Quarkus integartion tests fail when using 21.3. The error is:
```
--add-modules=jdk.net
```

See https://github.com/graalvm/mandrel/actions/runs/3216808337/jobs/5259259874#step:11:693

### How to Reproduce?

Run quarkus integration tests with `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11

### GraalVM version (if different from Java)

21.3

### Quarkus version or git rev

06c4344e6b203a798eb73f01e6e1d70fe01815b3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
As discussed in https://github.com/quarkusio/quarkus/pull/28529

Supersedes #28529
Closes #28475
Relates to #28530

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Awesome cleanup. Thanks!

**Review by jerboaa — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
CI is failing with:
```
 Caused by: java.lang.RuntimeException: Failed to register resource META-INF/services/org.jboss.logmanager.MDCProvider
	at io.quarkus.runtime.ResourceHelper.lambda$registerResources$0(ResourceHelper.java:37)
	at io.quarkus.runtime.util.ClassPathUtils.lambda$consumeStream$1(ClassPathUtils.java:180)
	at io.quarkus.runtime.util.ClassPathUtils.readStream(ClassPathUtils.java:201)
	at io.quarkus.runtime.util.ClassPathUtils.consumeStream(ClassPathUtils.java:179)
	at io.quarkus.runtime.util.ClassPathUtils.consumeAsStreams(ClassPathUtils.java:71)
	at io.quarkus.runtime.ResourceHelper.registerResources(ResourceHelper.java:33)
	... 9 more
Caused by: java.lang.IllegalAccessException: class io.quarkus.runtime.ResourceHelper cannot access class com.oracle.svm.core.jdk.Resources (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk to unnamed module @3b576ee3
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at io.quarkus.runtime.ResourceHelper.lambda$registerResources$0(ResourceHelper.java:35)
	... 14 more
```

**Comment by zakkak** [comment]
> CI is failing

Sorry for that, should be OK now.

**Comment by zakkak** [comment]
@gsmet I would like to backport https://github.com/quarkusio/quarkus/pull/28574/commits/8c2c6bd111bd761e30426c147321d4e7d89dc695 to 2.13, should I move it in a different PR (which I will mark with `triage/backport?`) or let it get merged in this one and then open a separate PR against `2.13` containing only https://github.com/quarkusio/quarkus/pull/28574/commits/8c2c6bd111bd761e30426c147321d4e7d89dc695?

**Comment by zakkak** [comment]
In https://github.com/quarkusio/quarkus/blob/ca191ab119f8ea74a9148563f7f15a89740421e3/.github/workflows/ci-actions-incremental.yml#L713-L718 we have hardcoded the version of GraalVM to be used for running tests on windows. I guess we should somehow pick this up from the source code instead.

**Comment by gsmet** [comment]
@zakkak given our hope is to backport this PR entirely, let's follow the usual backport process (I added the label). And then we can adjust if we need a contingency plan.

**Comment by zakkak** [comment]
> I guess we should somehow pick this up from the source code instead.

I switched the workflow to use the `graalvm/setup-graal` action instead which supports using 'latest' as the version, meaning it will always use the latest upstream release.

**Comment by gsmet** [comment]
> I switched the workflow to use the graalvm/setup-graal action instead which supports using 'latest' as the version

Good idea.

**Pull request merged**
