### PR TITLE
open config doc's type javadocs in new tab

### PR DESCRIPTION
**Pull request by machi1990**
A minor one to open the JavaDoc link of config Type in a new tab instead of the current tab.

/cc @gsmet @FroMage

### CODE REVIEW

**Comment by FroMage** [comment]
So, ten years ago I had an argument with @hilton where he convinced me that it was the user's responsability to decide if he wanted to open in a new window or not, and that it was bad UX to decide for him, because there's no UI to let you know this in advance (will it open normally, or in a new window), and if it opens in a new window, there's no UI in browsers to force it to open in the current window (whereas there is UI to force open in new windows if it's not meant ti).

Now, ten years on, and there are a lot of very famous websites which default to "open in new window" without any UI to tell you about it (GMail and many others), so perhaps it's become acceptable.

**Comment by FroMage** [comment]
So, I'm not really sure. I could go either way, but I'd prefer if "new window" links would have at least some UI icon to set them apart.

**Comment by FroMage** [comment]
I haven't looked at the resulting links, though, do they have special UI?

**Comment by gsmet** [comment]
Yeah, I tend to lean towards letting the user decide. But I don't have any strong opinion either.

EXCEPT that I want to be sure that in modern browsers, it opens in a new tab, not in a new window. Because that is a bad behavior IMHO.

**Comment by machi1990** [comment]
> EXCEPT that I want to be sure that in modern browsers, it opens in a new tab, not in a new window. Because that is a bad behavior IMHO.

Tested this in Chrome and Safari and the link is opened in new tab.

**Comment by hilton** [comment]
> there are a lot of very famous websites which default to "open in new window" without any UI to tell you about it (GMail and many others), so perhaps it's become acceptable

Or perhaps dark UX (a.k.a. asshole design) is more common now.

**Comment by FroMage** [comment]
> Or perhaps dark UX (a.k.a. asshole design) is more common now.

Yeah, it's very russian-rouletty

**Comment by machi1990** [comment]
Closing. We can revisit when it is actually needed.

**Pull request closed without merging**
