### PR TITLE
Introduce support for canceling async types in Quarkus Rest

### LINKED ISSUE #41705: Support cancelling Kotlin coroutine handlers on connection closing
I just started testing out Quarkus with Kotlin suspend handlers and it seems to work well. However, I noticed that these handlers don't support cancellation on request connection closing. I found a workaround, but it seems very cumbersome to add this to every request and would like to find out if there's a better way.

In the sample code below, endpoint `/long/a` cancels the delay by throwing the `CancellationException` when the connection is closed, but `/long/b` does not.

```kotlin
@Path("/long")
class SampleResource(private val log: Logger) {
    @GET
    @Path("a")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun longRunning(rc: RoutingContext): String = coroutineScope {
        val requestJob = Job(coroutineContext[Job])
        // Listen for the connection close event
        rc.request().connection().closeHandler {
            requestJob.cancel(CancellationException("Client connection closed"))
        }
        // Launch a coroutine within this job
        async(requestJob) {
            delay(10000)
            log.info("/long/a responding")
            "Completed request"
        }.await()
    }

    @GET
    @Path("b")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun hello(): String = coroutineScope {
        delay(10000)
        log.info("/long/b responding")
        "Completed request"
    }
}
```

```log
2024-07-04 17:30:07,579 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /long/a failed, error id: 1e9c93da-0f36-484d-8557-240fba83db7f-3: java.util.concurrent.CancellationException: Client connection closed
	at ...

2024-07-04 17:30:22,693 INFO  [org.acm.SampleResource] (vert.x-eventloop-thread-0) /long/b responding
```

_Originally posted by @calebkiage in https://github.com/quarkusio/quarkus/discussions/41696_

[Sample project](https://github.com/calebkiage/quarkus-kotlin-cancellation-test)

### PR DESCRIPTION
**Pull request by geoand**
When the underlying connection is closed, we can now cancel the underlying pipeline when an async type is supported.

Question: Should this be configurable? I am wondering because it is not unimaginable that some people might relying on the pipeline being completed in some fire and forget scenario.
Based on the scenario I explained above, I consider this a breaking change (albeit unlikely to break many people...)

- Closes: #41705

### CODE REVIEW

**Comment by calebkiage** [comment]
Thanks for putting this together so fast :-) How do I test? Is there a maven repo I can use once the CI is done?

Also, to answer your question, I thought this could be a configurable option.
If the option's default is the old behavior, it won't be a breaking change either.

**Comment by geoand** [comment]
> If the option's default is the old behavior, it won't be a breaking change either.

Very true. If we decide to add one that preserves the old behavior, I'll remove the label. 

> How do I test?

You need to checkout https://github.com/geoand/quarkus and use the `rest-cancelable` branch.
Once that is done, you can build the project like so (other options are possible, but this is what I use):

```
mvn -T 1C -DskipDocs -DskipTests -DskipITs -Dinvoker.skip -DskipExtensionValidation -Dskip.gradle.tests -Dskip.gradle.build -Dtruststore.skip clean install -Prelocations
```

Then update your project to use version `999-SNAPSHOT` while also making sure to use  `io.quarkus` instead of `io.quarkus.platform` for the Quarkus BOM.

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
@cescoffier @gsmet what do you think of the breaking aspect of this?

Perhaps we don't have to worry about it as it's clearly a very small niche?

**Comment by cescoffier** [comment]
I would. It worry too much. The new behavior is the correct one.

**Pull request merged**
