### PR TITLE
Add support for Podman auth file in Jib

### LINKED ISSUE #35609: Quarkus build with quarkus.container-image.builder=jib does not consider podman's auth.json
### Describe the bug

I get the exception below when i try to build my quarkus app after login in using `podman login` but without the properties `quarkus.container-image.username` and `quarkus.container-image.password`
```
[ERROR] Caused by: com.google.cloud.tools.jib.api.RegistryUnauthorizedException: Unauthorized for ...
```
Not sure if i am looking at the right place but when i look at the code [here](https://github.com/quarkusio/quarkus/blob/3.3.1/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L356) it does not consider the podman authfile in `${XDG_RUNTIME_DIR}/containers/auth.json.`

as an alternative i was able to create a sym link - $HOME/.docker/config.json to the podman's auth file to get it working. 

It will be nice to add the podman's authfile if the docker config is not found.

### Expected behavior

The build should work and should produce a container image

### Actual behavior

The build throws an exception 
```
[ERROR] Caused by: com.google.cloud.tools.jib.api.RegistryUnauthorizedException: Unauthorized for ...
```

### How to Reproduce?

1. Remove `$home/.docker/config.json`
2. Before running the build, authenticate to the container registry using `podman login`
3. Run the build without the properties `quarkus.container-image.username` and `quarkus.container-image.password`

### Output of `java -version`
```
OpenJDK Runtime Environment GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15) 
OpenJDK 64-Bit Server VM GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15, mixed mode, sharing)
```
### Quarkus version or git rev

4.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #35609

### CODE REVIEW

**Comment by geoand** [comment]
cc @codequester

@gastaldi would you be able to test this one?

**Review by gastaldi — APPROVED** [review]
> cc @codequester
> 
> @gastaldi would you be able to test this one?

No, but it LGTM

**Comment by codequester** [comment]
@geoand I was able to test and it worked.  Here is what i did. Pls let me know if there is a better way to test this

1. Checked out your PR
```
gh pr checkout 35613
```
2. Followed the docs [here](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#build)
```
export MAVEN_OPTS="-Xmx4g"
./mvnw -Dquickly
./mvnw install -f extensions/container-image/container-image-jib
```
3. Replaced my local .m2 repo jar with the one that was generated above and renamed it. This is coz **I don't know how to use a specific version of an extension**
```
cp ~/.m2/repository/io/quarkus/quarkus-container-image-jib/999-SNAPSHOT/quarkus-container-image-jib-999-SNAPSHOT.jar ~/.m2/repository/io/quarkus/quarkus-container-image-jib/3.3.0/quarkus-container-image-jib-3.3.0.jar
```
5. Ran the tests successfully
```
./mvnw -f integration-tests/container-image/ clean install

```
5.  Delete the symbolic link to podman's auth
```
rm -rf ~/.docker/config.json
```
6. do the maven build and push the image to the repo
```
./mvnw quarkus:build -DskipTests -D"quarkus.container-image.push=true" -D"quarkus.container-image.builder=jib"
```

The build worked and images was successfully build and pushed to the repo.

**Comment by gastaldi** [comment]
Merged, thanks @geoand and @codequester !

**Comment by geoand** [comment]
Thanks for checking!

**Pull request merged**
