### PR TITLE
Expose Agroal feature: transaction requirement

### PR DESCRIPTION
**Pull request by barreiro**

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]

**Comment by Sanne** [comment]
This looks good in principle, but there are some exceptional cases in which we might (intentionally) need a connection out of transaction.

The main use case coming to mind is schema validations, or schema updates. Hibernate ORM isn't going to use a transaction for that, and even if we wanted some databases don't support it. 

I believe there might be other similar cases, such as some ID optimisers could need running some statements out-of-transaction (although I'm less sure in this case and we might want to restrict to the implementation not requiring this).

If we want to introduce such a check, should we go the extra mile and make sure that it applies only on "user code", while having some kind of backdoor SPI access for Hibernate ?

**Review by Sanne — CHANGES_REQUESTED** [review]
As commented, I'm not sure if we should have this flag if it prevents existing framework code to work as usual.

**Comment by Sanne** [comment]
BTW I flagged it as "change requested" so to make it clear some clarification might be needed.

But I can be persuaded that this could be a reasonable limitation as-is: that when this is enabled, e.g. for production profiles, no schema changes are expected.

**Comment by Sanne** [comment]
BTW even in a "production mode" it's highly desireable to be ableto query the JDBC metadata (which we also do w/o a transaction) so to ensure e.g. schema validation can be used. So even in strictest mode, at least selected read operatiosn should be allowed?

**Comment by barreiro** [comment]
I'm aware of the limitations for metadata and DDL operations. Because of that, this setting allow 3 possible outcomes: allow, warn and exception. The default is allow so that nothing changes. For cases that really need such operations, either a warning is acceptable for users or it will force us to think better about it.

On the upside, this setting can be an invaluable tool to troubleshoot issues by ensuring that all access to the DB are transaccional.

**Comment by barreiro** [comment]
@Sanne You know that what I would like was to have everything transactional in Hibernate, but I'm not sure that is a solution either. I'm not seeing Hibernate using a SPI to get privileged connections even if one existed, given all the abstractions it has around the DataSource. 

How do you see we can get around this stalemate?

**Comment by Sanne** [comment]
I guess you're right that providing the right SPI would take more time, and this feature is useful.

I'm OK to merge this now if you think it's important?  But I still hope we could explore further improvements around the lines of a privileged SPI later.

**Comment by barreiro** [comment]
Added some clarification about the risks of setting the option.

**Review by Sanne — APPROVED** [review]

**Comment by famod** [comment]
I currently trying out this nice feature. I suppose nobody had the time to work on a SPI?
Btw, the liquibase extensions also acquires connections without transactions. I suppose flyway is similar.
So as it stands (IMO), `strict` can hardly ever be used.

**Comment by famod** [comment]
Btw, falling back to `warn` does print helpful hints but it's a bit inconvenient that I have to set DEBUG level for `io.agr.pool` to see the trace:
https://github.com/quarkusio/quarkus/blob/e59b4664daa506513529d8dfdd93b6cd3bcb474d/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalEventLoggingListener.java#L76-L77
Two separate log statements are also not really multi-threading friendly because other log entries could get in between.

I wonder if `Connection acquired without transaction.` could be handled specifically by that listener. I'd even send a PR for that...

**Comment by barreiro** [comment]
@famod Thanks for the feedback. I will consider it for next versions.

By the way, I agree that is unfortunate that Flyway and Liquibase operate without transactions. I haven't looked into those extensions in detail, but for Hibernate I did some research and it seems possible (and relatively straight forward) to have it's schema validation with transactions. It will be certainly a step in the direction of being able to enable `STRICT`.

**Comment by Sanne** [comment]
@barreiro sometimes there are legit operations that need to happen on the DB which require to not have a transaction.

Sure we can all agree these are uncommon, but they exist and we should allow people to perform these operations; that's why I suggested providing some SPI as a reasonable compromise (the alternative being a full blown API with no such restrictions at all - I thought you'd prefer the SPI idea).

**Comment by famod** [comment]
@barreiro
> @famod Thanks for the feedback. I will consider it for next versions.

I had a very brief look and I thought maybe `AgroalDataSourceListener.onConnectionAcquire()` could be extended with some parameter that allows the (quarkus) listener implementation to say "it's alright, I know what I'm doing". 🤔

**Pull request merged**
