### PR TITLE
Update strimzi test container from 0.100.0 to 0.106.0.

### LINKED ISSUE #37685: Old `strimzi/test-container` are being used in quarkus
### Describe the bug

Old (almost 2 years) `strimzi/test-container` are being used in quarkus

https://github.com/strimzi/test-container/releases/tag/0.100.0 was created in Jan 28, 2022

Latest available version is https://github.com/strimzi/test-container/releases/tag/0.105.0 from October 2023

Please update the dependency to make sure the latest strimzi gets used in tests.

### Expected behavior

Latest strimzi/test-container to be used

### Actual behavior

~2 years old strimzi/test-container are used

### How to Reproduce?

https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L155

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

Quuarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
Add it to the dependabot

Fixes #37685

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
@ozangunalp  the failure may be related. Can you have a look?

**Comment by gsmet** [comment]
I restarted CI as something odd happened in a few PRs.

**Comment by ozangunalp** [comment]
"Kafka OAUTH with Keycloak" test is indeed broken. I am looking at it.

**Comment by ozangunalp** [comment]
Pushed the fix

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
