### PR TITLE
Ensure no content-type header is sent when no HTTP body exists

### LINKED ISSUE #31184: OIDC Challenge response has JSON content type without body
## Background

I configured my quarkus service for our SPA as described:

https://quarkus.io/guides/security-openid-connect-web-authentication#single-page-applications

When I send a request with the header " X-Requested-With: JavaScript", the response has all the expected characteristics from the article.

## Bug

The response includes a header `Content-Type` but no body. That is a conflict.

For example, the fetch API https://developer.mozilla.org/en-US/docs/Web/API/Response does not provide introspection methods to identify this case, and calling `json()` leads to the error: `JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

### Expected behavior

The `Content-Type` should not be included in the response when there is no content.

### Actual behavior

This the a typical response in the browser:

```
HTTP/1.1 499 Client Error (499)
access-control-allow-origin: http://localhost:3000
access-control-allow-credentials: true
Content-Type: application/json
WWW-Authenticate: OIDC
content-length: 0
```

### How to Reproduce?

Use reproducer: https://github.com/Adelrisk/quarkus-reproducer-31184

OR

Follow the described instructions in https://quarkus.io/guides/security-openid-connect-web-authentication#single-page-applications

1. Add the extension `quarkus-oidc`
2. Disable redirects for javascript calls
```properties
quarkus.oidc.authentication.java-script-auto-redirect=false
```
3. Declare a protected resource
4. Access the protected resource as a JavaScript client. Here using curl:

```
curl 'http://0.0.0.0:8080/api/v1/profile' -H 'Accept: application/json' -H 'x-requested-with: JavaScript' -v
*   Trying 0.0.0.0:8080...
* Connected to 0.0.0.0 (127.0.0.1) port 8080 (#0)
> GET /api/v1/profile HTTP/1.1
> Host: 0.0.0.0:8080
> User-Agent: curl/7.87.0
> Accept: application/json
> x-requested-with: JavaScript
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 499 Client Error (499)
< Content-Type: application/json
< WWW-Authenticate: OIDC
< content-length: 0
< 
* Connection #0 to host 0.0.0.0 left intact
```

### Output of `uname -a` or `ver`

Linux Rechner 6.1.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.11-1 (2023-02-09) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.2-ea" 2022-07-19

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #31184

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by geoand** [comment]
Interestingly enough, one of the TCK tests is faiing...

**Comment by geoand** [comment]
It should be much better now

**Comment by sberyozkin** [comment]
Thanks @geoand

**Comment by geoand** [comment]
Now I just need to address the failing tests :)

**Pull request merged**
