### PR TITLE
Support Surefire 3.0.0-M4

### PR DESCRIPTION
**Pull request by Tibor17**
The versions 2.x.x are EOL.
The new version 3.0.0-M4 has many bugfixes, e.g. JUnit5 improvements, wide JDK and OS support.

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks! Not entirely sure though we want to switch to a still in-development version which still has a lot of changes going on.

@stuartwdouglas @geoand WDYT?

**Comment by geoand** [comment]
I had / have the same reservations as well.

Do we know when to expect a none milestone version?

**Comment by Tibor17** [comment]
@gsmet 
@geoand 
I am the most active developer of Surefire/Failsafe. The thing that we use milestones is our bureaucracy in Maven but here we guarantee 100% guarantee in 3.0.0-M4 and 3.0.0-M5. The reason why it is milestone and 3.0.0 is the fact that we want to release only one major version instead of two or three versions breaking the users multiple times. The goal of these milestone versions is to fix some issues which cannot be normally fixed without changing the internal code in a bigger scope. We are very glad the we do not have bug reports against the current features which appears thanks to our huge number of tests. We have 2000 tests altogether and 850 integration tests. We normally receive requirements for new features or the bugs for JPMS. The other bug fixes are our agenda even if the users report them or they are in progress and then the user's Jira issue is closed as a duplicate.

The Surefire is in situation where the versions 2.22.x would not backport changes from 3.0.0-Mx and you have to wait very long time. Now we are exactly in the middle of the work, so this is for your imagination how critical it is for Quarkus to stick to the old version.

For instance now the version 3.0.0-M5 has fixed the issues where the code (e.g. OSGi and JVM and Java Agents) used std/in and `native` std/out which corrupted Surefire's command/event stream. The fix is the extension which we introduced in Surefire project and this way we have got new feature with TCP connectors and abstraction which can be implemented by the user in the POM.
The next thing is the support of JUnit5 which happens only in 3.0.0-M1 - 3.0.0-M5. The same with JPMS and TestNG, Toolchains, etc.

The plugin is still backwards compatible.
According to our [road map](http://maven.apache.org/surefire/maven-surefire-plugin/) we will break the backwards compatibility in the last version 3.0.0-M8, but not earlier, and there we will break this:

- use prefix `surefire|failsafe` in system properties for some config parameters but not all
- the filter won't be file path based (com/xyz/**/tests/*Test.java). It will be fully qualified name e.g. `com.xqz.**.*Test`
- remove deprecated code

So, one can see that we know what we are doing and we listen to the users, and the name of the milstone means that we are in a progress with with big ambitions, and thus we only split the work to many stages.

**Comment by rquinio** [comment]
I actually wanted to suggest such upgrade - I always got weird failures when executing tests of some Quarkus modules via surefire on my laptop (java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory).
I've been using 3.0.0-M4 locally to solve this issue (I believe the bug is https://issues.apache.org/jira/browse/SUREFIRE-1679 which is still pending a 2.22.3 release)

**Comment by Tibor17** [comment]
@rquinio 
We are going to proceed through the Vote of the realaese `2.22.3`. Follow our chat in @dev mailing list.
The problem is that you cannot use older JUnit5 versions in Surefire `2.22.3`.

Since the version `3.0.0-M4` the Surefire has a smart resolver and the old versions still can be used. The versions `2.x.x` do not have such resolver, the `2.22.3` either, and technically it won't be possible to add it without having Maven API 3.0 in the plugin which is possible only in the versions `3.0.0-Mx`.

**Comment by stuartwdouglas** [comment]
We also require JUnit 5.6, so this is not an issue for us.

**Comment by geoand** [comment]
@Tibor17 Thank you very much for taking the time to explain the surefire / failsafe situation.

**Comment by gsmet** [comment]
Given @Tibor17 's explanation and the whole context, I think I could be convinced to move to Surefire 3.

**Comment by geoand** [comment]
I agree. Even compatibility does break in future milestones, it seems like it will be very minor and we might not even be affected.

**Comment by gsmet** [comment]
@stuartwdouglas any objections?

**Comment by stuartwdouglas** [comment]
I am fine with it, I just wonder if some customers will be reluctant to use anything with a Milestone in the name. Even if there is no logical difference there is still a perception difference.

**Comment by Tibor17** [comment]
Hey guys,
It's good to hear from you that the discussion is in progress.
Just for you info, we have dropped the release of `2.22.3` due to the JUnit5 Platform Launcher used in the plugin with the hardcoded version `5.6.1` breaks current Spring build. So we continue with last few bug fixes in `3.0.0-M5` which i hope will be available next week or a bit later. We may then start working on `2.22.4` and backport the smart resolver from `3.0.0-M5` if the users were shouting too much. So, we continue in our development of Surefire and the Quarkus team should make decision.

**Comment by geoand** [comment]
I am +1 to merge this

**Comment by cescoffier** [comment]
No problem on my side, Surefire 2 being EOL, it's good to move away from it.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by Tibor17** [comment]
Try to restart the build because the connections to the Maven Central reached the time out.

```Could not transfer artifact org.apache.maven.plugins:maven-failsafe-plugin:pom:3.0.0-M4 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-failsafe-plugin/3.0.0-M4/maven-failsafe-plugin-3.0.0-M4.pom: Connection timed out (Read failed)```

**Comment by mkouba** [comment]
FYI 3.0.0-M4 contains a [regression](https://issues.apache.org/jira/browse/SUREFIRE-1688) that manifests itself as follows: if a `QuarkusUnitTest` fails during application bootstrap (`BeforeAllCallback`) the exception is not re-thrown and the results is `BUILD SUCCESS`.

**Comment by geoand** [comment]
Given how much we depend on `QuarkusUnitTest`, I would say that if `3.0.0-M5` isn't coming very soon, we should consider reverting this

**Comment by gsmet** [comment]
Yes, I will revert it. We can revisit if M5 is released before 1.5.

**Comment by Tibor17** [comment]
You cannot be conservative infinitely. This does not solve anything.
My advice is to follow our Apache Jiras in Maven Surefire.
It's fair to give it a try like this, and report an issue if it is a new one.
There is an alternative to check it out with 3.0.0-SNAPSHOT right now and give me a feeback.
The version is available at the Apache Nexus repository.apache.org.

We will release M5 very soon and my estimation is May 22.

**Comment by gsmet** [comment]
Sure we cannot and we will reconsider the upgrade once M5 is out.

But right now, better get back to our last working version.

**Comment by Tibor17** [comment]
When you want to cut a new release of Quarkus?

**Comment by geoand** [comment]
From @gsmet's release email:

```
- Core CR1 - Tuesday May 19th
- Core Final - Tuesday May 26th end of day
```

**Comment by Tibor17** [comment]
Pls check it out with the snapshot version of surefire on your local working copy, otherwise our development in Surefire would not satisfy your needs on the time.

**Comment by Tibor17** [comment]
The version `3.0.0-M5` was deployed to the Maven Central.

**Comment by Tibor17** [comment]
A new PR #10081 was created.

**Pull request merged**
