### PR TITLE
Reset TCCL in QuarkusLauncher when the app terminates

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@aloubyansky does it fix an issue? I.e. should I backport it or we can keep it for 1.11?

**Comment by aloubyansky** [comment]
I don't have any specific issue to associate with it yet.
I spotted this one looking into the incremental build issues from @famod 's effort. But it might not be relevant after all.

**Comment by aloubyansky** [comment]
Ah, confused it with another PR of a similar nature. This one wasn't relevant.

**Pull request merged**
