### PR TITLE
Add an option to clear service test results in DevUI for Keycloak

### PR DESCRIPTION
**Pull request by sberyozkin**
I've found out that the results are starting to overwhelm the space after testing with the same token for a while, so having an option to clear/erase them will help

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Code looks good, can you share a screenshot?

**Comment by sberyozkin** [comment]
ResultsEraser2
ResultsEraser1

**Comment by sberyozkin** [comment]
@phillip-kruger Have a look please, the eraser is in the right bottom corner, pressing it, after a few results have been added, clears the results area. 
If there is a way to look it neater then please suggest, thanks

**Comment by phillip-kruger** [comment]
I like it! Nice

**Review by phillip-kruger — APPROVED** [review]
Lgtm

**Pull request merged**
