### PR TITLE
Exclude Eclipse Sisu (CDI implementation)

### PR DESCRIPTION
**Pull request by mariofusco**
…tion processor in org.eclipse.sisu.inject

### CODE REVIEW

**Comment by gsmet** [comment]
@stuartwdouglas any idea why we have this dependency coming and why it generates this file in the Kogito case?

**Comment by mariofusco** [comment]
@gsmet @stuartwdouglas apparently the annotation processor in that dependency is explicitly made (God knows why) to generate that javax.inject.Named file, see https://www.eclipse.org/sisu/docs/api/org.eclipse.sisu.inject/reference/org/eclipse/sisu/space/SisuIndexAPT6.html

**Comment by mariofusco** [comment]
@gsmet @stuartwdouglas in reality that jar seems to be explicitly made to be used inside a maven plugin to generate that file, see http://www.eclipse.org/sisu/docs/api/org.eclipse.sisu.mojos/ I think it doesn't make sense to have it among our dependencies

**Comment by stuartwdouglas** [comment]
I have no idea what this does, I assume it is part of the internals of JUnit 5.

**Comment by emmanuelbernard** [comment]
I'm a noob but should this exclusion be in our bom instead? Otherwise +1 for the exclusiong. Sisu is a CDI impl so we don't want it in.

**Comment by gsmet** [comment]
Closing this one in favor of https://github.com/quarkusio/quarkus/pull/2986 for a more general fix.

Typically, the Kogito quickstart did generate a file too so we really need to exclude it from the JUnit artifact.

**Pull request closed without merging**
