### PR TITLE
Add encryption secret to configuration

### PR DESCRIPTION
**Pull request by Brutus5000**
Not setting an encryption-secret can cause unexpected behaviour. Each restart, even from hot reload, will pick a new encryption secret otherwise, invalidating existing logins. This is a very annoying behaviour during development.

### CODE REVIEW

**Review by sberyozkin — COMMENTED** [review]
Thanks @Brutus5000, can you clarify something,  do you have a client secret setup in your case ?
The note you added is informative but it is only relevant if no fallback to the client secret exists. 

Perhaps we should add a note instead explaining it ?

I will continue the review next week since I'm on PTO 
Thanks

**Comment by Brutus5000** [comment]
@sberyozkin No, I have not set this up, as the OAuth client I use does not require/have a secret.

**Comment by sberyozkin** [comment]
@Brutus5000 OK, thanks for the confirmation. This is why I suggest to have a dedicated note, as opposed to adding the encryption secret property to this demo's configuration which already has a client secret fallback.

Something like this, at the end of that section where the demo properties are introduced/explained:

```
[NOTE]
====
When you do not configure a client secret with `quarkus.oidc.credentials.secret`,  it is recommended to configure `quarkus.oidc.token-state-manager.encryption-secret`.

The `quarkus.oidc.token-state-manager.encryption-secret` enables the default token state manager to encrypt the user tokens in a browser cookie. If this key is not defined, and the `quarkus.oidc.credentials.secret` fallback is not configured, Quarkus uses a random key. A random key causes existing logins to be invalidated either on application restart or in environment with multiple instances of your application. Alternatively, encryption can also be disabled by setting `quarkus.oidc.token-state-manager.encryption-required` to `false`. However, you should disable secret encryption in development environments only.

The encryption secret is recommended to be 32 chars long. For example, `quarkus.oidc.token-state-manager.encryption-secret=AyM1SysPpbyDfgZld3umj1qzKObwVMk`
====
```

Does it sound reasonable to you ?

**Comment by Brutus5000** [comment]
@sberyozkin I adjusted the commit accordingly.

**Review by sberyozkin — APPROVED** [review]
Thanks @Brutus5000

**Pull request merged**
