### PR TITLE
Cache programmatic API - invalidate entries whose keys match a predicate

### PR DESCRIPTION
**Pull request by mkouba**
Currently, you would need to make use of `CaffeineCache`, then iterate over the key set and finally remove an entry if it matches a predicate/condition.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by gwenneg — APPROVED** [review]
Nice improvement, thanks! This could use a new section in the cache doc.

LGTM

**Comment by mkouba** [comment]
> This could use a new section in the cache doc.

Yes, the [Caching using the programmatic API](https://quarkus.io/guides/cache#programmatic-api) could describe all `io.quarkus.cache.Cache`  methods.

**Comment by karesti** [comment]
@mkouba @gwenneg while I understand the motivation behind this method, for caching servers such as Redis or Infinispan looks like a dangerous idea to me (all the keys need to be read, apply the predicate and then send remove operations). I would like us to consider the idea of deprecating this method from the SPI

**Comment by mkouba** [comment]
> @mkouba @gwenneg while I understand the motivation behind this method, for caching servers such as Redis or Infinispan looks like a dangerous idea to me (all the keys need to be read, apply the predicate and then send remove operations). I would like us to consider the idea of deprecating this method in the SPI

Hm, I don't think we should deprecate the method but instead throw an `UnsupportedOperationException` in Redis or Infinispan impls and add a note to the method javadoc. It's perfectly valid for inmemory impls such as `Caffeine` (which was BTW the only impl we had at the time the method was added ;-).

**Comment by karesti** [comment]
@mkouba sounds like the method was promoted because we had it in the library implementation we were using

**Comment by mkouba** [comment]
> @mkouba sounds like the method was promoted because we had it in the library implementation we were using. I believe this method does not belong in a Caching SPI, but this is not my call

Well, that depends on how the cache is used. And it's actually not part of an SPI but a part of public user-facing API.

**Comment by karesti** [comment]
@mkouba looks like if it is also part of an SPI now, since we need to implement the interface to be used by the interceptors and chose a different cache provider

**Comment by karesti** [comment]
but as I said earlier, it's not my call :)

**Pull request merged**
