### PR TITLE
Remove Github action unreconized property

### PR DESCRIPTION
**Pull request by loicmathieu**
@gastaldi the CI from a fresh extension didn't work due to this line in the Github action file

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
I don't remember why I added this, but I think this change makes sense

**Comment by gsmet** [comment]
I would like to see the error first.

**Comment by loicmathieu** [comment]
Github action refuse the fail fast attribute. It generates an error and didn't launch the workflow.

Maybe the parameter is not passed correctly?

**Comment by loicmathieu** [comment]
I can paste the exact error tomorrow

**Comment by gsmet** [comment]
Yes please with some context and a link to the workflow file.

**Comment by loicmathieu** [comment]
@gsmet you can find a failing workflow here: https://github.com/quarkiverse/quarkus-pinot/actions/runs/2421198494

The error message was `The workflow is not valid. .github/workflows/build.yml (Line: 32, Col: 5): Unexpected value 'fail-fast'`.

**Pull request merged**
