### PR TITLE
Do not rely on initialization of log manager via property in native image

### PR DESCRIPTION
**Pull request by dmlloyd**
Required for correct operation under Java 11

### CODE REVIEW

**Comment by dmlloyd** [comment]
Hang on, it's still racy.  V2 coming

**Comment by dmlloyd** [comment]
OK better version pushed!

**Comment by aloubyansky** [comment]
I'm not familiar with this, it looks like this is about not giving a choice of alternative impl, forcing our own one, is that correct?

**Comment by dmlloyd** [comment]
Correct.  We've never offered a choice of alternative implementation, but the difference is that under Java 11 with native images there's some odd class initialization race condition that causes a problem with the old approach.  This approach solves the race completely by avoiding the racy code.

**Review by aloubyansky — APPROVED** [review]
Thanks!

**Pull request merged**
