### PR TITLE
Change Liquidbase to use config injections

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Relates to: #8648

### CODE REVIEW

**Comment by geoand** [comment]
Did you test the Kafka-Streams change?

Asking because I did the same thing and it didn't work

**Comment by stuartwdouglas** [comment]
I just tested and it is broken for me as well. @mkouba it looks like the injected field is null in the OnStartup observer method invocation, which seems like an arc bug

**Comment by mkouba** [comment]
> it looks like the injected field is null in the OnStartup observer method invocation, which seems like an arc bug

Could you be more specific? What should I do to reproduce the issue?

**Comment by geoand** [comment]
@mkouba if you checkout this PR or https://github.com/quarkusio/quarkus/pull/8685 and run `io.quarkus.it.kafka.streams.KafkaStreamsTest`, you'll see it fails

**Comment by mkouba** [comment]
Ok. I'll look at it right now.

**Comment by stuartwdouglas** [comment]
I may know what is going on, just testing now

**Comment by stuartwdouglas** [comment]
The Kafka bean is being initialized at static init, so the config is null at that point.

**Comment by mkouba** [comment]
We should thow an expection when a synthetic bean for a `ConfigPhase.RUN_TIME` root is accessed during STATIC_INIT. I'll send a PR shortly.

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
@mkouba this is so cool \o/

**Pull request merged**
