### PR TITLE
Add missing Jackson dependency to internal k8s client module

### PR DESCRIPTION
**Pull request by geoand**
Relates to: https://github.com/quarkusio/quarkus/pull/14588#issuecomment-768099796

### CODE REVIEW

**Comment by geoand** [comment]
cc @rsvoboda

**Review by rsvoboda — APPROVED** [review]
+1 for these changes

**Comment by rsvoboda** [comment]
@geoand there is fail in ci
```
Caused by: org.apache.maven.plugin.MojoExecutionException: Deployment artifact io.quarkus:quarkus-container-image-s2i-deployment::jar:999-SNAPSHOT is missing the following dependencies from its configuration: io.quarkus:quarkus-jackson-deployment::jar
```

**Comment by geoand** [comment]
Yup, I'm looking into it

**Comment by geoand** [comment]
Actually, this is going to cause more issues than it will solve.

So for the time being I opened https://github.com/quarkusio/quarkus/pull/14644 to revert the problematic change and I'll look into ths more in the future

**Comment by rsvoboda** [comment]
so this PR should be closed then?

**Comment by geoand** [comment]
Yup, closing

**Pull request closed without merging**
