### PR TITLE
Quarkus OIDC tokens persistence

### LINKED ISSUE #13239: Add quarkus-oidc-db-state-manager extension
**Describe the extension**
Quarkus OIDC `CodeAuthenticationMechanism` uses a default `TokenStateManager` implementation which stores all the session content in a cookie, which, by default, will include 3 tokens: ID, access and refresh tokens. When all 3 of them are in a JWT format as is with Keycloak, the cookie value size may exceed `4096` when JWTs have a lot of claims, at which point some browsers may drop it. 

Default `TokenStateManager` can be configured to create a cookie per each of these 3 tokens, thus, avoiding the size limitation problem, likely in most cases.

However, a cookie per token solution is not ideal, and also, a general approach where JWT tokens are stored as cookies may become a weak point as far as the data privacy is concerned, since, a signed JWT token, if leaked, can be easily introspected (its payload is just a base64-url encoded JSON - hence a claim like `Address` might become visible).

So, as discussed earlier with @pedroigor and @stuartwdouglas, the proposal is to ship a simple Hibernate based extension which will only implement `DbTokenStateManager`, store 3 tokens in a DB of choice, and return a DB pointer to OIDC `CodeAuthenticationMechanism` thus allowing for a session cookie to only have a short encoded binary value:

```
import javax.enterprise.context.ApplicationScoped;

import io.quarkus.oidc.AuthorizationCodeTokens;
import io.quarkus.oidc.OidcTenantConfig;
import io.quarkus.oidc.TokenStateManager;
import io.vertx.ext.web.RoutingContext;

@ApplicationScoped
public class DbTokenStateManager implements TokenStateManager {

    @Override
    public String createTokenState(RoutingContext routingContext, OidcTenantConfig oidcConfig,
            AuthorizationCodeTokens tokens) {
        // save tokens in DB, return DB pointer
    }

    @Override
    public AuthorizationCodeTokens getTokens(RoutingContext routingContext, OidcTenantConfig oidcConfig, String tokenState) {
            //tokenState is a DB pointer - use it to get the tokens from DB
    }

    @Override
    public void deleteTokens(RoutingContext routingContext, OidcTenantConfig oidcConfig, String tokenState) {
          // delete DB table pointed to by tokenState
    }
}
```

The DB-node synchronization would be out of scope - as it is a general concern for a multi-node Quarkus DB deployment. 
 
Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

Also CC @Sanne

### PR DESCRIPTION
**Pull request by cemnura**
Fixes #13239

### CODE REVIEW

**Comment by cemnura** [comment]
@sberyozkin I worked on this extension. Would you think I have the correct idea? I still could not manage to the [TokenState](https://github.com/cemnura/quarkus/blob/4491276cda46e16e06cb44d1006f5239303573e4/extensions/oidc-code-tokens-persistence/runtime/src/main/java/io/quarkus/oidc/runtime/TokenState.java) entity to register.

**Comment by sberyozkin** [comment]
Hey @cemnura Glad to hear from you. Let me have a look next day or so, the token state manager has to be nearly empty, and it just should be the only file in the extension, may be with the config. The integration test should be significantly simpler as well. Let me comment a bit later, thanks

**Comment by sberyozkin** [comment]
I'll try to refresh this one asap

**Comment by sberyozkin** [comment]
a new PR will be needed, closing now

**Pull request closed without merging**
