### PR TITLE
Simplify stork configuration

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Review by aureamunoz — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
CI failures seem related

**Comment by michalszynkiewicz** [comment]
> CI failures seem related

yes, for some reason my search missed a few places, fixed

**Comment by michalszynkiewicz** [comment]
@geoand since you already took a look at it, and Aurea doesn't have write access, maybe you'd like to review this ? :)

**Review by geoand — APPROVED** [review]
Good idea!

**Pull request merged**
