### PR TITLE
Support OIDC Client JWT Bearer authentication

### LINKED ISSUE #38513: Introduce JWT Bearer client authentication type
### Description

See #38458 for the details.

### Implementation ideas

Introduce new authentication type `client_jwt_bearer`.

Abstract OIDC client filters will have a protected `Map<String, String> getExtraParameters()` method, a custom filter will return a JWT bearer token obtained out of band, and these extra properties will be passed when acquiring or refreshing tokens. This approach will work for cases where filters need to supply some extra properties

### LINKED ISSUE #38609: Support OIDC Client JWT Bearer authentication
### Description

https://www.rfc-editor.org/rfc/rfc7523 defines how an incoming or possibly stored JWT bearer token can be exchanged using the JWT bearer token grant (already supported by the OIDC client) or be used to authenticate the client as part of whatever grant requests that are made. 

For example, the use case in #38458 is to use the token capturing the  current client credentials which is periodically recycled in the cluster thus making it a more secure option to authenticate to the OIDC server. 

### Implementation ideas

This token is obtained out of band as far as the OIDC client is concerned whose job is to acquire tokens, therefore to support the JWT bearer client authentication at the OIDC client filter level a custom filter is required.

This issue is about making creating such custom filters very easy by only having to extend an abstract class and provide a required assertion property.

Going forward it will also benefit other cases where the OIDC client request parameters have to be provided dynamically at the filter level

### PR DESCRIPTION
**Pull request by sberyozkin**
- Fixes #38609.
See also #38458.

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]
LGTM, @sberyozkin.

**Comment by sberyozkin** [comment]
Thanks @pedroigor, that should help with picking up other dynamically generated  sensitive data the secrets you mentioned etc

**Comment by Sopka** [comment]
I've tested the current 999-SNAPSHOT version and it works, but only If I add the client id again...
I do think that the OidcClientImpl class should add 

```
body.add(OidcConstants.CLIENT_ID, oidcConfig.clientId.get());
```

at the end of new clode block for `} else if (jwtBearerAuthentication) {` after line 149

My current workaround is to override my custom filter method like so:

```
  @Override
  protected Map<String, String> additionalParameters() {
      return Map.of(OidcConstants.CLIENT_ASSERTION, getFederatedToken(),
          OidcConstants.CLIENT_ID, this.clientId);
  }
```

BTW: Without setting the client-id again in the additionalParameters Map, Azure was giving me the error `AADSTS90023: Unexpected client assertion type`. This is really misleading, because the assertion _type_ was correct all the time, but actually the client-id was missing.

**Comment by Sopka** [comment]
There is still another problem with the current snapshot implementation.

After a while, I guess when the token gets renewed after it expired, the filter passes multiple times the client_assertion_type parameter. Especially the OIDC provider at Azure only expects the parameter exactly once.

The response from the OIDC provider is than correctly:

```
{"error":"invalid_request","error_description":"AADSTS90023: Unexpected client assertion type. ...}
```

Since the actual requests to the OIDC provider cannot be logged by enablng some application.properties I've added another custom Filter to debug what actually got sent to the provider:

```
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

import io.quarkus.arc.Unremovable;
import io.quarkus.oidc.common.OidcRequestContextProperties;
import io.quarkus.oidc.common.OidcRequestFilter;
import io.vertx.mutiny.core.buffer.Buffer;
import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
@Unremovable
public class OidcRequestDumpFilter implements OidcRequestFilter {

  private static final Logger LOG = Logger.getLogger(OidcRequestDumpFilter.class);

  @ConfigProperty(name = "oidc.request.dump.enabled")
  boolean requestDumpEnabled;

  @Override
  public void filter(io.vertx.mutiny.ext.web.client.HttpRequest<Buffer> request, Buffer requestBody,
      OidcRequestContextProperties contextProperties) {
    if (requestDumpEnabled) {
      LOG.info(dumpRequest(request.headers().entries(), requestBody == null ? "" : requestBody.toString()));
    }
  }

  String dumpRequest(final List<Map.Entry<String, String>> headers, final String requestBody) {
    final StringBuilder dumpBuilder = new StringBuilder();
    dumpBuilder.append("Headers:\n");
    headers.forEach(
        header -> dumpBuilder.append("  ").append(header.getKey()).append(": ").append(header.getValue()).append("\n"));
    dumpBuilder.append("Body:\n  ").append(requestBody);
    return dumpBuilder.toString();
  }

}
```

**Pull request merged**
