### PR TITLE
Fix group overriding with machine username

### LINKED ISSUE #41968: `quarkus image build` overrides `container-image.group` with the docker username
### Describe the bug

I have the following property in `application.properties`: `quarkus.container-image.group=custom-group`

Doing `quarkus build` generates both `target/kubernetes/kubernetes.json` and `target/kubernetes/kubernetes.yml` generates the correct image group: `*/custom-group/*`. However, doing `quarkus image build` generates both files with the default image group: `*/docker-username/*`

### Expected behavior

Both `target/kubernetes/kubernetes.json` and `target/kubernetes/kubernetes.yml` are generated using the specified image group:
- `*/custom-group/*`

### Actual behavior

Both `target/kubernetes/kubernetes.json` and `target/kubernetes/kubernetes.yml` are generated using the default image group (my docker username):
- `*/docker-username/*`

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

`Linux 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`

`openjdk version "17.0.11" 2024-04-16`

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by thmasker**
- Fixes #41968

### CODE REVIEW

**Comment by geoand** [comment]
Can you please rebase onto `main`?

Thanks

**Comment by gsmet** [comment]
I did the rebase.

**Comment by gsmet** [comment]
@thmasker you don't need to rebase your PR. We are just waiting for @iocanel to have a look (but he might be on PTO).

**Comment by thmasker** [comment]
@gsmet oh, ok. Since you wanted  me to rebase previously...

**Review by iocanel — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks for the PR! I will backport it to 3.13.1 that will be released next week.

**Pull request merged**
