### PR TITLE
Remove JDK 11 only API call in Qute test

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
I somehow missed the JDK 8 build was specifically failing :/

**Review by geoand — APPROVED** [review]

**Comment by mkouba** [comment]
@gsmet Sorry about that, I missed the `@since 11` tag :-(

**Comment by famod** [comment]
IMO, all `independent-projects` should have something like `build-parent`:
```xml
        <profile>
            <id>jdk-8-classpath</id>
            <activation>
                <!-- activate this on any JDK from 9 onwards -->
                <jdk>[9,)</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <release>8</release>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
```
This way you would also detect such problems locally.

**Review by mkouba — APPROVED** [review]

**Comment by famod** [comment]
I've just realised that `<parameters>` and `<maven.compiler.parameters>` are inconsistently scattered all over the repo.
I'll clean this up first and after that I'll have a look at adding the profiles.

**Comment by gsmet** [comment]
> @gsmet Sorry about that, I missed the @since 11 tag :-(

It's easy: as soon as a method makes your life a bit less miserable, it's JDK 11 only :).

**Comment by geoand** [comment]
Kill Java 8 now!

**Comment by famod** [comment]
> Kill Java 8 now!

Go tell those poor folks still on JDK7. 😉

**Comment by geoand** [comment]
> > Kill Java 8 now!
> 
> Go tell those poor folks still on JDK7.

There were versions of Java before 8 😆 ?

**Comment by johnaohara** [comment]
Is this functionally equivalent? idk what format `ctx.getBase().toString()` can return,  JDK11 String.lines() splits on line feed `\n`, carriage return `\r` and a carriage return followed immediately by a line feed`\r\n`

**Comment by mkouba** [comment]
> Is this functionally equivalent? idk what format `ctx.getBase().toString()` can return, JDK11 String.lines() splits on line feed `\n`, carriage return `\r` and a carriage return followed immediately by a line feed`\r\n`

It's OK because we don't use any line separator in the test template.

**Comment by gsmet** [comment]
Yeah I know it's not exactly the same behavior but it looked good enough. Just waiting on the Windows build to be sure.

**Pull request merged**
