### PR TITLE
Update SmallRye Config to 2.12.0

### LINKED ISSUE #27185: quarkus.http.host property initialization exception during build time, started from Qarkus 2.10.1+
### Describe the bug

Hi guys!
I believe something is changed in the build process in Quarkus 2.10.x+ for "quarkus.http.host" property initialization process.
Right now, it's necessary to have it during container build time, which doesn't look correct because the build system host may differ from the app's host.
In our project, it works as ENV variable from a container:

`quarkus.http.host: ${HOST}`

and it worked perfectly fine up to 2.9.2 version, but today I checked all versions from 2.10.1 to 2.11.2, and the build process failed with the following exception:

```posh
2022-08-08T14:35:22.6914579Z #15 126.2 * What went wrong:
2022-08-08T14:35:22.6916064Z #15 126.2 Execution failed for task ':some-service:quarkusBuild'.
2022-08-08T14:35:22.6916697Z #15 126.2 > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2022-08-08T14:35:22.8415007Z #15 126.2   	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.util.NoSuchElementException: SRCFG00011: Could not expand value HOST in property quarkus.http.host
2022-08-08T14:35:22.8417268Z #15 126.2   	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:68)
2022-08-08T14:35:22.8418927Z #15 126.2   	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:58)
2022-08-08T14:35:22.8420391Z #15 126.2   	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
2022-08-08T14:35:22.8421680Z #15 126.2   	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
2022-08-08T14:35:22.8422955Z #15 126.2   	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
2022-08-08T14:35:22.8424310Z #15 126.2   	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:58)
2022-08-08T14:35:22.8425850Z #15 126.2   	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:38)
2022-08-08T14:35:22.8427426Z #15 126.2   	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-08-08T14:35:22.8428995Z #15 126.2   	at io.smallrye.config.FallbackConfigSourceInterceptor.getValue(FallbackConfigSourceInterceptor.java:24)
2022-08-08T14:35:22.8430624Z #15 126.2   	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-08-08T14:35:22.8432169Z #15 126.2   	at io.smallrye.config.FallbackConfigSourceInterceptor.getValue(FallbackConfigSourceInterceptor.java:24)
2022-08-08T14:35:22.8434393Z #15 126.2   	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-08-08T14:35:22.8436036Z #15 126.2   	at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
2022-08-08T14:35:22.8437654Z #15 126.2   	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-08-08T14:35:22.8439137Z #15 126.2   	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:307)
2022-08-08T14:35:22.8440428Z #15 126.2   	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:225)
2022-08-08T14:35:22.8441639Z #15 126.2   	at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:324)
2022-08-08T14:35:22.8443617Z #15 126.2   	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.getAutoServerFilter(SmallRyeOpenApiProcessor.java:455)
2022-08-08T14:35:22.8446409Z #15 126.2   	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeDocument(SmallRyeOpenApiProcessor.java:1024)
2022-08-08T14:35:22.8448037Z #15 126.2   	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeDocument(SmallRyeOpenApiProcessor.java:1004)
2022-08-08T14:35:22.8449599Z #15 126.2   	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:719)
2022-08-08T14:35:22.8451040Z #15 126.2   	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)15 actionable tasks: 15 executed
2022-08-08T14:35:22.8452000Z #15 126.2 
2022-08-08T14:35:22.8452977Z #15 126.2   	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-08-08T14:35:22.8454447Z #15 126.2   	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-08-08T14:35:22.8455732Z #15 126.2   	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-08-08T14:35:22.8456941Z #15 126.2   	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
2022-08-08T14:35:22.8458138Z #15 126.2   	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
2022-08-08T14:35:22.8459305Z #15 126.2   	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2022-08-08T14:35:22.8460522Z #15 126.2   	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-08-08T14:35:22.8461873Z #15 126.2   	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-08-08T14:35:22.8463026Z #15 126.2   	at java.base/java.lang.Thread.run(Thread.java:829)
2022-08-08T14:35:22.8463964Z #15 126.2   	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

quarkus.http.host property is initialized during runtime (on startup) as in Quarkus 2.9.2 version

### Actual behavior

A container build process fails with an exception "Could not expand value HOST in property quarkus.http.host"

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.10.1+

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #27353: Quarkus 2.12.0.CR1 - Map style config property resolution does not work in native mode
### Describe the bug

In Camel Quarkus it's possible to have some configuration like the following in `application.properties`:

```
camel.threadpool.config[customPool].id = customPool
camel.threadpool.config[customPool].pool-size = 1
camel.threadpool.config[customPool].rejectedPolicy = Abort
```

Where the `config[customPool]` part denotes a map key that Camel can resolve internally. This all works fine in JVM mode. Since ` 2.12.0.CR1`, resolution of such properties no longer seems to work in native mode. The config keys seem to be present, but their associated values are not resolvable.

### Expected behavior

The properties are resolvable as expected in native mode.

### Actual behavior

See comments in the main description. 

### How to Reproduce?

There's a reproducer project here:

https://github.com/jamesnetherton/smallrye-config-demo

See instructions in the README for how to run. Tests fail with `2.12.0.CR1`, they pass with `2.11.2.Final`.

### LINKED ISSUE #27630: quarkus.uuid is missing in 2.12.0
### Describe the bug

    ConfigProvider.getConfig().getValue("quarkus.uuid", UUID.class);

This works well in Quarkus 2.11.3. However, it throws an exception in Quarkus 2.12.0:

```
2022-08-31 17:43:28,918 [] ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.util.NoSuchElementException: SRCFG00014: The config property quarkus.uuid is required but it could not be found in any config source
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:282)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:239)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:167)
	...
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
https://github.com/smallrye/smallrye-config/releases/tag/2.12.0

- Fixes #27353
- Fixes #27185
- Fixes #27630

### CODE REVIEW

**Comment by geoand** [comment]
@radcortez I assume this is now good to go?

**Comment by radcortez** [comment]
Yes.

**Review by gsmet — CHANGES_REQUESTED** [review]
The Jakarta update is missing.

**Comment by radcortez** [comment]
> The Jakarta update is missing.

Ah, yes. I forgot that I have to update that now as well :)

I still have to release that one. I'm doing that now.

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by radcortez** [comment]
It seems that something is breaking `io.quarkus.jwt.test.PublicKeyLocationConfigTest`. I'll check.

**Comment by radcortez** [comment]
> It seems that something is breaking `io.quarkus.jwt.test.PublicKeyLocationConfigTest`. I'll check.

Ah, this is because `mp.jwt.verify.publickey.location` may contain expansion variables provided on runtime. In that case, we cannot register the native image resource (the user must do that manually). In the new version of MP Config, expressions in Optional configuration do not cause the expansion to fail (which the build step was checking).

**Pull request merged**
