### PR TITLE
Vert.x restructuring - part 2/2

### LINKED ISSUE #16797: Restructure Vert.x extensions
## Description

At the moment, we have 4 Vert.x related extensions. This is mostly because of decisions taken at the very beginning of the project, before Vert.x becomes the underlying engine (even the name of the extension is somewhat broken now).
So currently we have:

* vertx-core -> configure vert.x, produce the "bare" Vert.x instance
* vertx-http -> initialize Vert.x Web router(s) and the Vert.x HTTP server
* vertx -> produce the Mutiny Vert.x instance, add support for the `@ConsumeEvent` annotation (event bus, built-in in vert.x)
* vertx-web -> handle reactive routes (`@Route`) and provide the `@RouteFilter` annotation

With the introduction of RESTEasy Reactive, Reactive Routes use case become less relevant. 
Also, Mutiny, becoming the omniscient reactive programming library, should be supported by default (Stuart already started doing some work around that)

To ease the maintenance, and also reduce a bit the confusion, here is a structuration proposal:

* vertx-core -> configure vert.x, producer "bare" and "mutiny" instances, add support for `@ConsumeEvent`
* vertx-http ->  initialize Vert.x Web router(s) and the Vert.x HTTP server, handle reactive routes (`@Route`) and provide the `@RouteFilter` annotation

The vertx and vertx-web extensions would be _dropped_.

### PR DESCRIPTION
**Pull request by mkouba**
- rename quarkus-vertx-web to quarkus-reactive-routes
- keep the API package name io.quarkus.vertx.web
- resolves #16797

### CODE REVIEW

**Review by ebullient — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]
We would need to add a note to the migration guide.

**Comment by cescoffier** [comment]
Thanks!

**Comment by mkouba** [comment]
> We would need to add a note to the migration guide.

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.3#reactive-routes

**Comment by geoand** [comment]
This as well as https://github.com/quarkusio/quarkus/pull/19933 should also be marked as breaking changes.

**Comment by loicmathieu** [comment]
And please communicate on the mailing list for this kind of breaking changes as renaming an extension can have a broader impact.
I was not pingued on the PR even if it touch google cloud functions, and the update of the guides is missing.
I'm pretty sure the Amazon Lambda and the Asure Function guide also needs to be updated, I'll have a look.

**Comment by mkouba** [comment]
> This as well as #19933 should also be marked as breaking changes.

#19933 should not be a breaking change because the API did not change and the user-facing extension (`quarkus-vertx`) should still work.

**Comment by geoand** [comment]
Gotcha, thanks

**Comment by mkouba** [comment]
> I was not pingued on the PR even if it touch google cloud functions, and the update of the guides is missing.
> I'm pretty sure the Amazon Lambda and the Asure Function guide also needs to be updated, I'll have a look.

The reactive routes guide was updated. `amazon-lambda-http.adoc` and `azure-functions-http.adoc` were updated as well. I did not find a reference in the Google Cloud Functions guide.

**Comment by loicmathieu** [comment]
@mkouba the feature has not been renamed so it's still shows as `vertx-web` inside the starting log.
https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/Feature.java#L153

**Comment by mkouba** [comment]
> @mkouba the feature has not been renamed so it's still shows as `vertx-web` inside the starting log.
> https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/Feature.java#L153

Thanks! Would you care to add this change to [your PR](https://github.com/quarkusio/quarkus/pull/20133)?

**Comment by loicmathieu** [comment]
@mkouba too later, my PR contains only document changes so quick CI and alreay merged.

**Comment by mkouba** [comment]
> @mkouba too late, my PR contains only document changes so quick CI and alreay merged.

No problem! I'll fix it in a separate PR.

**Pull request merged**
