### PR TITLE
Rest client config - avoid warnings about unrecognized config keys

### LINKED ISSUE #21698: Quarkus throws warnings about quarkus.rest-client configuration after #21530
### Describe the bug

https://github.com/quarkusio/quarkus/pull/21530 introduced warnings when using quarkus-rest-client (both in JVM and native mode).

### Expected behavior

Quarkus shouldn't through warnings (like it did before https://github.com/quarkusio/quarkus/pull/21530)

### Actual behavior

Quarkus throws warnings like the following both in JVM and native mode:

```
04:09:13,334 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client.restClientBaseUriConfigKey.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,357 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestInterface".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,358 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.GouvFrGeoApiClient".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,360 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client.loopback.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,361 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestClientInterface".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,367 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestClientWithFaultToleranceInterface".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,368 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestInterface".scope" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,370 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client.restClientConfigKey.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### How to Reproduce?

```
./mvnw verify -f integration-tests/pom.xml -pl main
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3f0ffd4c98b672f7fbc5ab63c10d0456a213f040

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TomasHofman**
Fixes https://github.com/quarkusio/quarkus/issues/21698

### CODE REVIEW

**Comment by gsmet** [comment]
Don't worry about the Gradle failure, it has nothing to do with your PR.

**Review by radcortez — COMMENTED** [review]
Can you add a test to make sure if don't fall into this again? Take a look here: https://github.com/quarkusio/quarkus/blob/01bee6969efe374d4489d35189c65f34106cea87/core/test-extension/deployment/src/test/java/io/quarkus/extest/UnknownConfigTest.java#L22-L32

**Comment by TomasHofman** [comment]
Sure, I will add the test.

**Comment by TomasHofman** [comment]
PR updated.

**Comment by TomasHofman** [comment]
I believe this PR should be backported to the same branches as the previous PR: https://github.com/quarkusio/quarkus/pull/21530

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
Thanks @TomasHofman !

**Pull request merged**
