### PR TITLE
Ignore javax.net, javax.crypto and javax.security reflective hierarchy warnings

### LINKED ISSUE #14577: Unable to properly register the hierarchy for javax.net, javax.security and javax.crypto classes
```
2021-01-25 10:08:52,144 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-25) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - javax.crypto.Mac (source: KubernetesClientProcessor > io.fabric8.tekton.pipeline.v1beta1.PipelineRun)
        - javax.net.SocketFactory (source: KubernetesClientProcessor > io.fabric8.tekton.pipeline.v1beta1.PipelineRun)
        - javax.net.ssl.HostnameVerifier (source: KubernetesClientProcessor > io.fabric8.tekton.pipeline.v1beta1.PipelineRun)
        - javax.net.ssl.SSLSocketFactory (source: KubernetesClientProcessor > io.fabric8.tekton.pipeline.v1beta1.PipelineRun)
        - javax.net.ssl.X509TrustManager (source: KubernetesClientProcessor > io.fabric8.tekton.pipeline.v1beta1.PipelineRun)
        - javax.security.auth.x500.X500Principal (source: KubernetesClientProcessor > io.fabric8.tekton.pipeline.v1beta1.PipelineRun)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #14577

### CODE REVIEW

**Comment by geoand** [comment]
Seems reasonable to me.

@sberyozkin @gsmet any reason you can think of why we would not want to do that?

**Comment by gastaldi** [comment]
@goldmann this should fix your issue

**Comment by gastaldi** [comment]
I wonder if we shouldn't add `javax.xml.*` too. See #14576

**Comment by sberyozkin** [comment]
Hi @gastaldi @geoand I don't really know - excluding packages like `javax.crypto.*` looks a bit scary :-) ?
For example, `SecretKey` is in this package:
https://github.com/smallrye/smallrye-jwt/blob/master/implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java#L44

Or is it simply about minimizing the logging noise ?

**Comment by sberyozkin** [comment]
Can it be isolated somehow to the `kubernetes-client` extension ?

**Comment by gastaldi** [comment]
Hm, probably it needs to be added to the tekton client extension. /cc @goldmann

**Comment by goldmann** [comment]
@sberyozkin @gastaldi I'm happy to whatever is required, but here are we talking about skipping the warning, am I correct? Can I do similar thing as part of the extension?

**Comment by gastaldi** [comment]
@goldmann yes, something like https://github.com/quarkusio/quarkus/pull/14576 would be nice to have in the tekton-client extension

**Comment by goldmann** [comment]
@gastaldi Perfect, on it!

**Comment by goldmann** [comment]
Created ticket: https://github.com/quarkiverse/quarkus-tekton-client/issues/6

**Comment by goldmann** [comment]
PR opened: https://github.com/quarkiverse/quarkus-tekton-client/pull/7

**Comment by goldmann** [comment]
Version 0.2.0 of Quarkus Tekton Client released with a fix for this.

**Comment by gsmet** [comment]
I'm not exactly sure about this. I think we need to understand why they are added to the mix and if we should improve things for them to not be considered.

Typically:
- why exactly is this class marked for reflection?
- if it's for JSON serialization, where do these classes come from, are things properly annotated to ignore these fields?

With more info, we would be able to take a more educated decision.

**Comment by gastaldi** [comment]
@gsmet true, this was observed in the tekton-client extension, but since that was already resolved there, I think we can safely close this PR and issue

**Comment by gastaldi** [comment]
Closing this for now

**Pull request closed without merging**
