### PR TITLE
Fix package of hibernate-orm/deployment-spi

### PR DESCRIPTION
**Pull request by gsmet**
The package is incorrect and makes the javadoc build fail.

### CODE REVIEW

**Comment by gsmet** [comment]
I already backported it as it's blocking the release.

**Review by yrodiere — APPROVED** [review]

**Comment by Sanne** [comment]
We only spot such an issue when you attempt a release?

**Comment by gsmet** [comment]
So we actually have a build testing the release posting on status.quarkus.io but I was too busy/on PTO/at JNation to actually have a look before today.

And yes only javadoc chokes on this, the rest seems to ignore the problem. It's not the first time.

**Comment by gastaldi** [comment]
Holy crap, I didn't notice that either when renaming this class

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand it seem that all the Windows build are now timing out in AppCDS. I don't know if it's related to this module or something else but I had at least 2 builds failing there for totally different changes. See for instance https://github.com/quarkusio/quarkus/commit/590edfefbe5ec04aa255dac9dc9d47ccb9d01643/checks/6812364928/logs .

And this one was a small build of only 40 minutes for the Linux builds.

**Pull request merged**
