### PR TITLE
fix: possible infinite loop on Oauth2 Identity Manager

### LINKED ISSUE #3419: OAuth2IdentityManager.verify(String id, Credential credential) - infinite loop
OAuth2IdentityManager.verify(String id, Credential credential) has infinite loop / recursive call.

link to code: https://github.com/quarkusio/quarkus/blob/master/extensions/elytron-security-oauth2/runtime/src/main/java/io/quarkus/elytron/security/oauth2/runtime/auth/OAuth2IdentityManager.java#L31

@loicmathieu should be current `return verify(null, credential);` changed to `return verify(credential);` ?

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #3419

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]

**Review by sberyozkin — COMMENTED** [review]
Should this one throw UnsupportedOperationException ?

**Comment by loicmathieu** [comment]
@sberyozkin it could be but none of the other IndentityManager on the other security extension throws UnsupportedOperationException for unused methods, they return `null` so I can change my code to return `null` if you prefere as a safeguard to align with JwtIdentityManager and ElytronIdentityManager.

**Comment by sberyozkin** [comment]
Hi @loicmathieu - IMHO returning `null` would be better, looks like this method is never called, so even the current delegation would do - but I'm not sure this method's contact will be satisfied this way if it is ever called...

**Comment by loicmathieu** [comment]
@sberyozkin done

**Review by n1hility — APPROVED** [review]

**Comment by n1hility** [comment]
Thanks 🍺!

**Pull request merged**
