### PR TITLE
Update RuntimeUpdatesProcessor.java

### PR DESCRIPTION
**Pull request by survivant**
fix typo %ss -> %s s

### CODE REVIEW

**Comment by famod** [comment]
I'd have the same remark as here: https://github.com/quarkusio/quarkus/pull/10748#issuecomment-658734017

**Comment by jaikiran** [comment]
Interesting. @survivant, does this change work? I haven't seen this issue so far. The current code generates output like:
```
INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Hot replace total time: 0.658s 
```
which correctly shows the time as well as the `s` (which represents seconds) without any space.

**Comment by survivant** [comment]
it's for the issue : https://github.com/quarkusio/quarkus/issues/10746

**Comment by jaikiran** [comment]
> it's for the issue : #10746

Thank you for that reference. Looking at the details in that issue:

```
juill. 10, 2020 8:04:42 A.M. io.quarkus.deployment.dev.RuntimeUpdatesProcessor doScan INFO: Hot replace total time: %ss
```
Is it picking up some other logging implementation maybe? the `doScan` which is a method name (which doesn't usually get printed out) is an hint that this doesn't appear to be a typical logging configuration. Is there a simple application you can share with us which reproduces the issue?

**Comment by famod** [comment]
@jaikiran I am also puzzled by this because `String.format(...)` (which JBoss Logging should be using for this under the hood) does _not_ have a problem with `%ss` either.

**Comment by geoand** [comment]
Again, all PRs should go against `master` not `1.6`.

Thanks

**Pull request closed without merging**
