### PR TITLE
Fix mandrel-flavor in guide

### LINKED ISSUE #15667: `mandrel-flavor` appearing in https://quarkus.io/guides/building-native-image#container-runtime
**Describe the bug**
In https://quarkus.io/guides/building-native-image#container-runtime `{mandrel-flavor}` has not been replaced with the corresponding value defined in `docs/pom.xml`.

**Expected behavior**
`{mandrel-flavor}` should have been replaced with `21.0-java11`

**Actual behavior**
image

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #15667

### CODE REVIEW

**Comment by zakkak** [comment]
@gastaldi this makes sense, but I don't know how to test it locally. Could you please give me a pointer to the corresponding documentation or the commands I need to run?

Thanks for the fix!

**Comment by gastaldi** [comment]
@zakkak run `mvn clean package -pl docs` and open the `docs/target/generated-docs/building-native-image.html` file in your browser (format won't be the same as the website but it should show you it's correct)

**Review by zakkak — APPROVED** [review]
Thanks @gastaldi

**Review by geoand — APPROVED** [review]

**Comment by gastaldi** [comment]
Thanks!

**Comment by geoand** [comment]
Thank you!

**Pull request merged**
