### PR TITLE
Avoid "Failed to index" warnings produced during @SecureField annotation detection

### LINKED ISSUE #40153: Many "Failed to index" warnings since 3.9.1
### Describe the bug

Since 3.9.1 I'm getting the following warnings when building my app or running dev mode:
```
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index org.springframework.context.support.AbstractApplicationContext: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index com.sun.xml.fastinfoset.stax.StAXDocumentParser: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index com.sun.xml.fastinfoset.stax.StAXDocumentSerializer: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index org.springframework.context.ConfigurableApplicationContext: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index io.mashona.logwriting.ArrayStore: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index org.apache.activemq.artemis.core.journal.RecordInfo: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index org.apache.activemq.artemis.core.journal.Journal: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index jakarta.jms.XAConnection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index jakarta.jms.XASession: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index jakarta.jms.XAConnectionFactory: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
[WARNING] [io.quarkus.deployment.index.IndexWrapper] Failed to index jakarta.jms.Connection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for myapp-5.0.1.local-dev1@62d7d954
```
`git bisect` says #39564 is to blame. /cc @michalvavrik

### Expected behavior

No such warnings (as in 3.9.0 and before)

### Actual behavior

Warnings since 3.9.1

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17.0.11

### Quarkus version or git rev

3.9.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.6

### Additional information

The respective Maven module doesn't have any sources, but it has dependencies to almost all other modules in the repo.
Interestingly, another module in the repo (which builds a different "flavor" of the app) doesn't have this issue, but it also has fewer dependencies (but it does contain some sources).

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #40153

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks a lot!

**Review by gsmet — APPROVED** [review]

**Comment by rsvoboda** [comment]
There is QUARKUS-4431 request on product side.

@vmuzikar this fix was included in Quarkus 3.10.1 released ~1 hour ago, so this doesn't have any bake time.
Is this a must-have for 3.8.5 or would it be ok to wait till 3.8.6 to get community feedback?

**Comment by vmuzikar** [comment]
@rsvoboda If you are not comfortable with including it last minute in 3.8.5, that's fine for Keycloak. What is the estimated time frame for 3.8.6? Based on that we'll filter the messages on our end.

**Comment by rsvoboda** [comment]
Bits are out now and it's usually week or two to get feedback in case something goes wrong.

So assuming we are not under immediate pressure to get 3.8.5 out, we could include this in the last 3.8.5 backports round.

**Comment by vmuzikar** [comment]
Ok, 3.8.5 would be awesome. :)

**Pull request merged**
