### PR TITLE
Fixed typos in method names of ArcInvocationContext

### PR DESCRIPTION
**Pull request by nikolassv**
This PR fixes some typos in method names of the `ArcInvocationContext`. Moreover, it renames them to match the names of the corresponding methods of the [`jakarta.interceptor.InvocationContext`](https://github.com/jakartaee/interceptors/blob/2.2.0/api/src/main/java/jakarta/interceptor/InvocationContext.java) (v2.2.0). This will make it easier to update one day to Version 2.2.0 of the Jakarta Interceptor API.

These are breaking changes as the `ArcInvocationContext` is a public interface.

### CODE REVIEW

**Comment by Ladicek** [comment]
Thanks for the PR! Alas, I already have a branch with all the necessary updates to CDI 4.1, including Interceptors 2.2. And breaking changes like this are not acceptable -- sorry, but I need to close this.

**Comment by mkouba** [comment]
Hm, I don't see any typos there :thinking:. But I agree with Ladislav...

**Comment by gsmet** [comment]
@mkouba see `findIterceptorBinding` and a few others. There are actual typos in method names.

**Comment by mkouba** [comment]
> @mkouba see `findIterceptorBinding` and a few others. There are actual typos in method names.

Ah, I see. Missing `n`...

**Comment by Ladicek** [comment]
Ah I was totally blind to this all the time! That's hilarious :-D

All these methods with typos are actually going to be deprecated once we bump to CDI 4.1.

**Pull request closed without merging**
