### PR TITLE
[WIP] Support both GraalVM 19.2.1 and 19.3.0.2 - 19.2.1 SDK & 19.3.0.2 GraalVM image

### PR DESCRIPTION
**Pull request by gwenneg**
This PR tests one of the Graal SDK and image combinations decribed [here](https://github.com/quarkusio/quarkus/pull/6487#issuecomment-573233582).

svm version (SDK): 19.2.1
GraalVM image version : 19.3.0.2-java8

### CODE REVIEW

**Comment by gsmet** [comment]
@gwenneg this one went well so it's promising.

**Comment by gwenneg** [comment]
I've tested this branch with `ubi-quarkus-native-image:19.3.0.2-java11` locally and most of the native tests completed successfully. I'm struggling a bit with four integration test modules that won't run on my machine because of various issues that don't seem related with the SDK change:

- `quarkus-integration-test-main`: I'm running out of memory (error 137)
- `quarkus-integration-test-jsch`: I'm having a random port issue that happens with both native and non-native tests
- `quarkus-integration-test-kubernetes-client`: it looks like my computer isn't fast or powerful enough to run these native tests with JDK 11
- `quarkus-integration-test-infinispan-embedded`: the native image generation fails because of an invalid path entry for `resources-config.json`

I'll update this PR with additional comments as soon as I find a way to run these tests without any error.

**Comment by gwenneg** [comment]
https://github.com/quarkusio/quarkus/pull/6507/commits/d5c37f54086919e5d6571a153fa345d40f3bb04f fixes the `quarkus-integration-test-infinispan-embedded` issue.

**Comment by geoand** [comment]
All tests are passing? Nice!

**Comment by gwenneg** [comment]
Superseded by #6574.

**Pull request closed without merging**
