### PR TITLE
Re-enable single parsing of compiler graphs in native-image

### LINKED ISSUE #19446: InlineBeforeAnalysis enabled by default in coming GraalVM 21.3 release
### Description

In 21.0 GraalVM introduced a new compiler flag `-H:+InlineBeforeAnalysis` (see https://github.com/oracle/graal/issues/2594) and quarkus introduced a new build item for it (see https://github.com/quarkusio/quarkus/pull/16134).

In 21.3-dev (latest GraalVM master) this flag has been turned on by default (see https://github.com/oracle/graal/pull/3628/files) making the builditem introduced by https://github.com/quarkusio/quarkus/pull/16134 obsolete.

### Implementation ideas

If we are OK with not being able to disable this flag, deprecating the build item once we upgrade to 21.3 should be fine.

If we would like to be able to pass `-H:-InlineBeforeAnalysis` by setting `quarkus.native.inline-before-analysis` to false or similar then extra steps are needed.

### PR DESCRIPTION
**Pull request by zakkak**
GraalVM 21.2-dev introduced a new enhancement (enabled by default) to avoid parsing compiler graphs twice.
This enhancement however resulted in increased memory usage (https://github.com/oracle/graal/issues/3435) which then resulted in Quarkus' Integration Test failures in CI.
In GraalVM 21.2 and 21.3-dev this appears to no longer be an issue.

I have tested this branch with [GraalVM CE](https://github.com/zakkak/quarkus/runs/3371447400?check_suite_focus=true) and [Mandrel](https://github.com/graalvm/mandrel/actions/runs/1146954848) 21.2, as well as with [GraalVM CE](https://github.com/graalvm/mandrel/actions/runs/1147285998) and [Mandrel](https://github.com/graalvm/mandrel/actions/runs/1147027008) 21.3-dev.

Things look good except for `io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase` which fails when compiled with 21.3-dev with:
```
[ERROR] io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative  Time elapsed: 0.137 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Type 'javax.xml.transform.TransformerFactory' was found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20210819_173859.txt
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContainsNot(ClassInclusionReport.java:67)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContainsNot(ClassInclusionReport.java:53)
	at io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative(JPAFunctionalityInGraalITCase.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:895)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

~~Keeping this as draft for now.~~

Closes: #19446

### CODE REVIEW

**Comment by zakkak** [comment]
Testing this with a more recent Quarkus seems OK except for the following error in `io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase`:
```
org.opentest4j.AssertionFailedError: Type 'javax.xml.transform.TransformerFactory' was found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20210924_074424.txt
``` 

Passing `-Dquarkus.native.additional-build-args="-H:-InlineBeforeAnalysis"` makes the test pass.

@Sanne it looks like when ParseOnce and InlineBeforeAnalysis are both enabled (default behavior in the upcoming GraalVM 21.3) https://github.com/quarkusio/quarkus/blob/c5a2f2c3becac20222bb1ed4a611e40b0e97aacf/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/SQLXLMFeature.java#L25-L36

doesn't work as expected.

My first thought was that `setResult` might be getting inlined before analysis and thus analysis sees it as reachable, following that thought I tried the following:
```diff
diff --git a/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/PgSQLXML.java b/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/PgSQLXML.java
index b0333866f2..2dea4eaeda 100644
--- a/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/PgSQLXML.java
+++ b/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/PgSQLXML.java
@@ -41,6 +41,7 @@ import org.postgresql.xml.PGXmlFactoryFactory;
 import org.xml.sax.InputSource;
 import org.xml.sax.XMLReader;
 
+import com.oracle.svm.core.annotate.NeverInline;
 import com.oracle.svm.core.annotate.Substitute;
 import com.oracle.svm.core.annotate.TargetClass;
 
@@ -222,6 +223,7 @@ public final class PgSQLXML implements SQLXML {
         return stringWriter;
     }
 
+    @NeverInline("Prevent inlining so that io.quarkus.jdbc.postgresql.runtime.graal.SQLXLMFeature keeps working with -H:+InlineBeforeAnalysis")
     @Substitute
     @Override
     public synchronized <T extends Result> T setResult(Class<T> resultClass) throws SQLException {
 ```

But the test still fails.

@sanne any thoughts? (+ FYI)

**Comment by zakkak** [comment]
After some profiling it looks like the use of ParseOnce is no longer causing issues with the CI (like the ones mentioned in https://github.com/quarkusio/quarkus/pull/17711) both in 21.2 and 21.3-dev (averages of 3 runs)

### 21.3-dev

| | -H:+ParseOnce | -H:-ParseOnce |
| -- | -- | -- |
| compilation time | ~263s | ~274s |
| Allocated heap size | 6.5 GB | 7.3 GB |

## 21.2

| | -H:+ParseOnce | -H:-ParseOnce |
| -- | -- | -- |
| compilation time | ~282s | ~275s |
| Allocated heap size | 7.2 GB | 7.4 GB |

Especially motivated by the reduction of the allocated heap size in 21.3-dev I believe we should allow GraalVM/Mandrel to keep ParseOnce enabled moving forward.

**Comment by geoand** [comment]
I can't say I know much about the subject. so I'll leave this to others.

**Comment by Sanne** [comment]
Hi @zakkak , if `javax.xml.transform.TransformerFactory` is still being detected, it might be being included for other reasons.

I was able to identify the `PgSQLXML` case as being a reason for GraalVM to decide to include the `TransformerFactory` as non-dead code: it was the only detected path that made it reachable.

But having changed the analysis algorythms, I suppose other tricky paths might have materialized? It's very likely that it's being included via a different path now, as my patches on `PgSQLXML` make it unlikely.
We would need to do another reachability analysis to know where it's coming from; do you have any clue from the reports?

I think it's really important to keep such types out of it as they come with a significant amount of dependencies; however it might be more interesting for the long term to figure out why GraalVM isn't able to see such paths as dead code automatically.

**Comment by zakkak** [comment]
@Sanne it turns out what is happening with ParseOnce + InlineBeforeAnalysis is that GraalVM is now able to figure out the trick in
https://github.com/quarkusio/quarkus/blob/e1ea35876568ea31a2b34679f7d0750db62f0b0e/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/DomHelper.java#L51-L55

so it automatically registers it for reflection.

Fixed in https://github.com/quarkusio/quarkus/pull/19511/commits/c8187f5b31545a891452a2d9cc6f0938757c013c

Please re-review :)

**Comment by Sanne** [comment]
ah awesome :) Sorry I should have remembered of that one.

**Review by Sanne — APPROVED** [review]

**Comment by zakkak** [comment]
Updated PR following @Sanne's comment https://github.com/quarkusio/quarkus/commit/c8187f5b31545a891452a2d9cc6f0938757c013c#commitcomment-57177705

New CI runs for Mandrel 21.2: https://github.com/graalvm/mandrel/actions/runs/1282744930
and GraalVM 21.3-dev: https://github.com/graalvm/mandrel/actions/runs/1282744523

**Pull request merged**
