### PR TITLE
ArC - parallelize resource generation

### PR DESCRIPTION
**Pull request by mkouba**
I have to admit that I have no "scientifict measurements". My observations while working on this PR are that for small apps the performance is more or less identical and for large apps (such as [003-quarkus-many-extensions](https://github.com/quarkus-qe/beefy-scenarios/tree/main/003-quarkus-many-extensions)) the difference was ~15% on average.

### CODE REVIEW

**Comment by manovotn** [comment]
I'll take a look tomorrow if that's ok

**Comment by mkouba** [comment]
> I'll take a look tomorrow if that's ok

No problem at all. It's not a high priority...

**Comment by Ladicek** [comment]
The changes are pretty straightforward, but the code duplication on a few places is unfortunate.

Also, not sure why you need to precompute those names (`prefill*`) before generating the resources, but I'm sure there's a good reason.

What I find most interesting is that you can actually achieve speedup with this. That suggests that the concurrent build step execution framework can't utilize the CPU fully, probably because a lot of build steps do blocking operations?

**Comment by Sanne** [comment]
Nice idea :)
But could you avoid adding a configuration property? I'd say just enable it...

**Comment by mkouba** [comment]
> Also, not sure why you need to precompute those names (`prefill*`) before generating the resources, but I'm sure there's a good reason.

We need to generate the names first because they're used in the [ComponentsProviderGenerator](https://github.com/quarkusio/quarkus/pull/26381/files#diff-c9b2b8f7f82a42a3270b51243922c82ca8e6617e554a67788a60ac8381701391R164). If we don't pregenerate the names we would have to wait for all bean and observer generators to finish and then start the generation of the `ComponentsProvider` (i.e. no parallel execution). Note that the generated `ComponentsProvider` is one of the largest class ArC generates and so it should go first. I'll add some javadoc to the method.

> What I find most interesting is that you can actually achieve speedup with this. That suggests that the concurrent build step execution framework can't utilize the CPU fully, probably because a lot of build steps do blocking operations?

There are build steps whose dependencies/dependents prevent or limit the concurrent execution. Typical examples are `ClassTransformingBuildStep#handleClassTransformation` and `JarResultBuildStep#buildRunnerJar`. For these build steps it might help to try to parallelize the execution inside the build step. And FYI we already do this in the `ClassTransformingBuildStep#handleClassTransformation`.

**Comment by mkouba** [comment]
> But could you avoid adding a configuration property? I'd say just enable it...

It's just a safeguard so that it can be disabled in case of an oversight that would cause some concurrency issues. And it's enabled by default.

**Review by manovotn — COMMENTED** [review]
I don't have any objections to this.
The idea is solid, doesn't hurt for smaller deployments and if it helps in beefy scenarios, it's always a plus. So +1

EDIT: I'd also be fine with not using the config option and just making it default, but I understand why you wanted to keep that in. Perhaps we could have it straight up deprecated so that we can eventually get rid of it once we see this doesn't cause troubles?
The less config options, the better :-)

**Comment by manovotn** [comment]
> Having additional properties won't save the day for most people as they won't figure out a relation from the random problem to needing to set this.

I think the idea here is that if the change is to cause some problems, users will report it and we can then direct them to use this config option as a temporary workaround before we have a proper fix. So it effectively unblocks the user.
And I understand the decision, I would just like to see a way to gradually lower the amount of configs as we become more confident about the changes we made.

**Comment by Sanne** [comment]
yea I agree in principle - feel free to ignore me, but at least deprecating the new property would be nice.
FWIW I've used system properties for similar things, perhaps that's more suitable and doesn't distract in documentation.

**Comment by mkouba** [comment]
@manovotn @Sanne all your comments about the config item make a lot of sense. I'll switch to a system property. I want to keep it so that we can also easily test the difference.

**Review by manovotn — APPROVED** [review]

**Comment by mkouba** [comment]
^ Are [these](https://github.com/quarkusio/quarkus/pull/26381#issuecomment-1177594993) known flaky tests? @gsmet

**Comment by gsmet** [comment]
The failing tests above are either flaky or have been already fixed in main and are not related to this. So feel free to merge when ready.

**Pull request merged**
