### PR TITLE
Support @TestSecurity in combination with JWT

### LINKED ISSUE #11695: Support @TestSecurity in combination with JWT-Security
**Description**
If your application uses JWT for security, you could disable the security during tests with `@TestSecurity(authorizationEnabled = false)`.
But if your application requires data (like username or roles) from the JWT, the test will crash with a HTTP-500.

```
@Inject
@Claim(standard = Claims.preferred_username)
String currentUserName;

@Inject
@Claim(standard = Claims.email)
String email;
	
@Inject
@Claim(value = "realm_access")
String rolesFromRedhatSSO725;
```

**Implementation ideas**
Generate a JsonWebToken with the data from the `@TestSecurity` annotation and publish it to CDI context for later injection.

The `io.quarkus.test.security.QuarkusSecurityTestExtension#beforeEach` does this for the SecurityIdentity, but adding JWT here would add another dependency which is not required everywhere. Maybe directly a json?

Maybe a hook could be implemented where the test author could add some custom values for the JWT.
```
@Test
@TestSecurity(name = "username", roles = {"user", "admin"} )
@TestJwtData(key="field1", value="value1")
@TestJwtData(key="field2", value="value2")
void customJwtFields() {
}
```

### PR DESCRIPTION
**Pull request by geoandri**
Closes #11695

### CODE REVIEW

**Comment by sberyozkin** [comment]
@geoandri This is very good, thanks, but IMHO we need to have `JsonWebToken` created in its own `security-jwt` module as the current approach won't scale once we start introducing other extension-specific Principals, etc.

Also, `SecurityAttribute` is not the best name for setting the principal attributes (claims in case of JWT, etc) because `SecurityIdentity` has its own attributes. I propose to rename `SecurityAttribute` to `PrincipalAttribute`

Not sure what the best approach is, but one idea is as follows:

- `security` module should have a CDI bean implementing `PrincipalProducer` interface with a `producePrincipal` method accepting a user name and `PrincipalAttribute`s - and it will create a principal the way it is done by default - you'd use CDI to acquire it
- new `security-jwt` module will only have its own `Alternative` `PrincipalProducer`:
```
@ApplicationScoped
@AlternativePriority(1)
public class JwtPrincipalProducer implements PrincipalProducer {
    Principal producePrincipal(String userName, Set<PrincipalAttribute> principalAttributes) {}
}
```

That should work, maybe we can come up even with the better CDI centric approach later.

Give it a try please, thanks

**Comment by geoandri** [comment]
Will do @sberyozkin,

thanks

**Comment by sberyozkin** [comment]
@geoandri Hi, have you had some time to try and finalize it ?

**Comment by geoandri** [comment]
Hi @sberyozkin ,

Unfortunately a combination of vacation and urgent matters in my "daily" work, prevented me from putting effort on this. I do not expect to have the opportunity to give it a shot during this month.

**Comment by sberyozkin** [comment]
@geoandri Sure, thanks for the update - lets sync a bit later on

**Comment by sberyozkin** [comment]
@geoandri Hi, I'm pIanning to re-assign #11695 this PR was intending to fix. The issue has been open for a while and the users are asking about simple unit testing of the endpoints working with JWT - so we need to progress - if you do plan to resume then please let me know by tomorrow. Np at all if you are busy right now - in that case we can suggest new issues for you to look at once you become available

**Comment by geoandri** [comment]
I apologize for this @sberyozkin . Please go on and assign it to anyone willing to take over. I missed notifying you due to my limited availability.

**Comment by sberyozkin** [comment]
Hi @geoandri There is absolutely nothing to apologize for :-), you've spent your time on this issue and it is appreciated; please ping me or anyone else from Quarkus once you are available

**Comment by sberyozkin** [comment]
@geoandri I'll keep it assigned to you for a bit longer...

**Comment by geoandri** [comment]
Hi @sberyozkin . I think it would be preferable for someone else to take over at this point because I am really pressed for time for the upcoming period and this issue is already idle for quite some time.

**Comment by sberyozkin** [comment]
@geoandri Hi, sounds good, let me take care of it - please pick up a new issue whenever you will become available, thanks

**Comment by sberyozkin** [comment]
I'm about to open a new PR so going to close this one

**Pull request closed without merging**
