### PR TITLE
Update version to 3.8.999-SNAPSHOT in 3.8 branch

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by zakkak — COMMENTED** [review]
Thanks @gsmet 

Let's see if the CI is happy as well :)

**Comment by gsmet** [comment]
Hmmm, not sure what's going on but that's definitely bad news as `update-version.sh` is supposed to be safe.

**Comment by zakkak** [comment]
It looks like `quarkus-enforcer-rules` is still looking in for 999-SNAPSHOT:

```
gradle/gradle-enterprise-maven-extension/1.20.1/gradle-enterprise-maven-extension-1.20.1.pom\n[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/gradle/gradle-enterprise-maven-extension/1.20.1/gradle-enterprise-maven-extension-1.20.1.pom (1.5 kB at 8.3 kB/s)\n[INFO] Downloading from central: [https://repo.maven.apache.org/maven2/com/gradle/gradle-enterprise-maven-extension/1.20.1/gradle-enterprise-maven-extension-1.20.1.jar\n[INFO]](https://repo.maven.apache.org/maven2/com/gradle/gradle-enterprise-maven-extension/1.20.1/gradle-enterprise-maven-extension-1.20.1.jar/n[INFO]) Downloaded from central: https://repo.maven.apache.org/maven2/com/gradle/gradle-enterprise-maven-extension/1.20.1/gradle-enterprise-maven-extension-1.20.1.jar (14 MB at 39 MB/s)\n[INFO] Downloading from central: [https://repo.maven.apache.org/maven2/com/gradle/common-custom-user-data-maven-extension/1.12.5/common-custom-user-data-maven-extension-1.12.5.pom\n[INFO]](https://repo.maven.apache.org/maven2/com/gradle/common-custom-user-data-maven-extension/1.12.5/common-custom-user-data-maven-extension-1.12.5.pom/n[INFO]) Downloaded from central: https://repo.maven.apache.org/maven2/com/gradle/common-custom-user-data-maven-extension/1.12.5/common-custom-user-data-maven-extension-1.12.5.pom (6.9 kB at 1.4 MB/s)\n[INFO] Downloading from central: [https://repo.maven.apache.org/maven2/com/gradle/common-custom-user-data-maven-extension/1.12.5/common-custom-user-data-maven-extension-1.12.5.jar\n[INFO]](https://repo.maven.apache.org/maven2/com/gradle/common-custom-user-data-maven-extension/1.12.5/common-custom-user-data-maven-extension-1.12.5.jar/n[INFO]) Downloaded from central: https://repo.maven.apache.org/maven2/com/gradle/common-custom-user-data-maven-extension/1.12.5/common-custom-user-data-maven-extension-1.12.5.jar (9.6 MB at 82 MB/s)\n[INFO] Scanning for projects...\n[INFO] Downloading from local.central: file:///home/runner/.m2/repository/io/quarkus/quarkus-parent/999-SNAPSHOT/maven-metadata.xml\n[INFO] Downloading from local.central: file:///home/runner/.m2/repository/io/quarkus/quarkus-parent/999-SNAPSHOT/quarkus-parent-999-SNAPSHOT.pom\n[ERROR] [ERROR] Some problems were encountered while processing the POMs:\n[FATAL] Non-resolvable parent POM for io.quarkus:quarkus-enforcer-rules-smoketest:1.0-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-parent:pom:999-SNAPSHOT (absent): Could not find artifact io.quarkus:quarkus-parent:pom:999-SNAPSHOT in local.central (file:///home/runner/.m2/repository) and \'parent.relativePath\' points at wrong local POM @ line 5, column 13\n @ \n[INFO] Configuring extension: MavenBuildScanCaptureListener\n[INFO] 0 goals, 0 executed\n[ERROR] The build could not read 1 project -> [Help 1]\n[ERROR]   \n[ERROR]   The project io.quarkus:quarkus-enforcer-rules-smoketest:1.0-SNAPSHOT (/home/runner/work/quarkus/quarkus/independent-projects/enforcer-rules/target/it/smoketest/pom.xml) has 1 error\n[ERROR]     Non-resolvable parent POM for io.quarkus:quarkus-enforcer-rules-smoketest:1.0-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-parent:pom:999-SNAPSHOT (absent): Could not find artifact io.quarkus:quarkus-parent:pom:999-SNAPSHOT in local.central (file:///home/runner/.m2/repository) and \'parent.relativePath\' points at wrong local POM @ line 5, column 13 -> [Help 2]\n[ERROR] \n[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.\n[ERROR] Re-run Maven using the -X switch to enable full debug logging.\n[ERROR] \n[ERROR] For more information about the errors and possible solutions, please read the following articles:\n[ERROR] [Help 1] [http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException\n[ERROR]](http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException/n[ERROR]) [Help 2] [http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException\n[INFO]](http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException/n[INFO]) Configuring unpublished Build Scan capture\nRunning post-build script: /home/runner/work/quarkus/quarkus/independent-projects/enforcer-rules/target/it/smoketest/verify.groovy\n'
```

https://github.com/quarkusio/quarkus/actions/runs/8263718559/job/22606627430?pr=39396#step:16:1388

**Comment by gsmet** [comment]
@zakkak yes, I was on it too. I pushed an update to the script. But I'm not exactly sure it's a good thing to depend on quarkus-parent here.

**Pull request merged**
