### PR TITLE
Do not duplicate methods in Panache Repositories and Entities

### LINKED ISSUE #6787: Overriding Panache methods leads to duplicated method error
**Describe the bug**
I have a class implementng a PanacheRepositoryBase<T, P> 

```
@ApplicationScoped
public class JpaOwnerRepository implements PanacheRepositoryBase<Owner, Integer> {

    @Inject
    EntityManager em;

    @Override
    public Owner findById(Integer id) {
        // using 'join fetch' because a single query should load both owners and pets
        // using 'left join fetch' because it might happen that an owner does not have
        // pets yet
        Query query = this.em
                .createQuery("SELECT owner FROM Owner owner left join fetch owner.pets WHERE owner.id =:id");
        query.setParameter("id", id);
        return (Owner) query.getSingleResult();
    }

    @Audited
    public void save(Owner owner) {
        if (owner.getId() == null) {
            persist(owner);
        } else {
            this.em.merge(owner);
        }

    }
}
```

Error received 
```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.springframework.samples.petclinic.service.userService.UserServiceTests]
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to initialize Arc
Caused by: java.lang.ClassFormatError: Duplicate method name "findById" with signature "(Ljava.lang.Object;)Ljava.lang.Object;" in class file org/springframework/samples/petclinic/repository/jpa/JpaOwnerRepository
```

**Expected behavior**
The overrided method should take place, having only one method, not 2.

**Actual behavior**
Apparently 2 methods go to the compiled artifact

**To Reproduce**
1. Create a class implementing PanacheRepositoryBase<T, M>
2. Override *findById* method with the same identity type
3. Build and execute tests

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 192.168.1.134 4.20.15-200.fc29.x86_64 #1 SMP Mon Mar 11 16:01:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`:  openjdk version "1.8.0_181-ojdkbuild"

 - GraalVM version (if different from Java): 19.2.1
 - Quarkus version or git rev: master branch at today

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #6787

### CODE REVIEW

**Comment by gastaldi** [comment]
@jonathanvila can you give it a try if this PR fixes your problem? Thanks!

**Review by FroMage — CHANGES_REQUESTED** [review]
This looks fine, but I think you should move the tests to the existing orm-panache integration tests.

And also this appears to be only fixing the issue for repositories, but not for entity static methods. Pretty sure the same issue happens there.

**Comment by gastaldi** [comment]
@FroMage it seems that the Entity static methods are safe, I added a test to prove it works

**Comment by FroMage** [comment]
Nope, `findById(Object)` is the signature you should be testing.

**Comment by gsmet** [comment]
@FroMage I let you recheck that one? Thanks!

**Comment by FroMage** [comment]
Nothing changed since my last comment, this will still let in duplicate methods for entities.

**Comment by gastaldi** [comment]
> Nothing changed since my last comment, this will still let in duplicate methods for entities.

@FroMage look closely, I [added the `findById(Object)` method](https://github.com/quarkusio/quarkus/pull/6812/files#diff-472e5caaf16e13fa012c610af3d5d72fR16) as you requested but the test still pass.

**Comment by gastaldi** [comment]
@gsmet @FroMage any chance to get this merged for 1.3.0.Alpha1 and tackle the duplicate methods for entities (when reproducible) in a separate issue?

**Comment by gsmet** [comment]
@gastaldi I let you bug @FroMage to get it merged. I'm not familiar enough with this code.

If it's merged before the end of the day, it will be in Alpha1 for sure.

**Comment by FroMage** [comment]
I believe the exact signature that will cause trouble will be `public static <T extends PanacheEntityBase> T findById(Object id)` but even something simpler such as `public static int update(String query, Parameters params)` should give trouble.

**Comment by gastaldi** [comment]
@FroMage thanks for the pointer. I updated the test and managed to reproduce and fix the bug. Please review

**Review by FroMage — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
