### PR TITLE
Extensions should override codestart data for dependencies

### PR DESCRIPTION
**Pull request by ia3andy**
The extension may contain the version to use.

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by ia3andy** [comment]
Oups I forgot about that one, I need to have a look

**Comment by gsmet** [comment]
@ia3andy I don't know how critical this is?

**Comment by ia3andy** [comment]
I will have a look on monday..

**Comment by ia3andy** [comment]
Fixed

**Pull request merged**
