### PR TITLE
WP: Quarkus Unleash extension

### PR DESCRIPTION
**Pull request by andrejpetras**
Hi,

we do continue rolling out the Quarkus as a new technology stack in the projects. The next missing piece for us is the [Unleash](https://github.com/Unleash/unleash) feature toggle extension. I created a base structure for the extension which contains one producer for the `Unleash` object. It would be great if you could give feedback to this PR.

To-do:
- [x] register classes for reflection
- [x] native image
- [ ] extend unleash configuration
- [ ] unit test
- [ ] integration test
- [ ] documentation

The `Unleash` java SDK client is a rest client which call the `Unleash` service. What could I use in the unit and integration test to mock the service endpoint? (Testcontainers, Mock-server, Wiremock, ...)

My test application: https://github.com/andrejpetras/quarkus-unleash-test

BR
Andrej

### CODE REVIEW

**Comment by gastaldi** [comment]
Interesting, but IMHO this extension should live in the quarkiverse org instead. Have a look at https://github.com/quarkiverse/quarkiverse/wiki

**Comment by andrejpetras** [comment]
@gastaldi, thank you for the info. I did not know that.

How can I start the process for Unleash extension in the `quarkiverse` organization?
Do I need to [create an Extension Proposal issue](https://github.com/quarkusio/quarkus/issues/new/choose)?

**Comment by gastaldi** [comment]
@andrejpetras yes, that would kickstart the process of provisioning a new repository and give you the appropriate permissions.

I am on PTO this week, so I'd appreciate if @aloubyansky, @maxandersen or @gsmet could work on that.

**Comment by gsmet** [comment]
I can do it :).

You will probably have to fix things yourself later, though :]

**Comment by andrejpetras** [comment]
@gsmet I created https://github.com/quarkusio/quarkus/issues/13434
I believe we can close this PR.

**Comment by famod** [comment]
@andrejpetras closed as requested.

**Pull request closed without merging**
