### PR TITLE
make default banner max 80 chars wide

### PR DESCRIPTION
**Pull request by maxandersen**

### CODE REVIEW

**Comment by maxandersen** [comment]
fixes #7633 character width

**Comment by geoand** [comment]
Can you try pushing again to the PR? Something seems to have gone wrong

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@cescoffier can you check it fixes the issue you had with native image? Because it didn't look related to the width.

Thanks!

**Comment by maxandersen** [comment]
@gsmet this won't fix @cescoffier's issue - his would be fixed by #7662

**Pull request merged**
