### PR TITLE
Update to Stork 1.4.1

### LINKED ISSUE #19: smallrye-stork - New service discovery implementation based on Knative
(From https://github.com/smallrye/smallrye-stork/issues/402)
We would need a new service discovery implementation in Stork for KNative. This SD locates the KNative service (and not the pods as we do for Kubernetes). It would not be possible to use load balancing. However, if you use KNative, load balancing can be handled there.

This SD would take a (Knative) service name as parameter and search for it in the current (or configured) namespace. It will not check if there are pods, just locate the service, resolve the name and return that name. It fails if no service can be found. You will never have more than one service (this needs to be verified when using revisions).

See [Quarkus #146](https://github.com/quarkusio/quarkus-super-heroes/issues/146)

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 402
upstream-status: open
upstream-milestone: unplanned
```

### LINKED ISSUE #146: Fights service shouldn't use client side load balancing when deployed in knative
The fight service shouldn't use Stork's client-side load balancing when deployed in KNative. This breaks because if the heroes/villains services scale to 0, then the client side load balancing in the fights service won't have any downstream clients.

### PR DESCRIPTION
**Pull request by cescoffier**
* Fix https://github.com/quarkusio/quarkus-upstream-roadmap/issues/19
* Fix https://github.com/quarkusio/quarkus-super-heroes/issues/146

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by edeandrea** [comment]
@cescoffier I see this was merged but I don't see any updated documentation, either on the Quarkus stork guide nor the smallrye stork docs on how to actually use this?

**Comment by cescoffier** [comment]
@edeandrea this is weird, the documentation is there: https://github.com/smallrye/smallrye-stork/blob/main/docs/docs/service-discovery/knative.md

But, it looks like something went wrong with the web site generation during the release.

**Comment by edeandrea** [comment]
Yeah I don't see any docs for 1.4.1

**Comment by cescoffier** [comment]
@edeandrea i've found the issue. I opened the release PR from my fork so it updated the wrong remote.

I've triggered another redeploy, but, Murphy's law applied... GitHub actions are down.

**Comment by cescoffier** [comment]
@edeandrea Finally! https://smallrye.io/smallrye-stork/1.4.1/service-discovery/knative/#caching-the-service-instances

Sorry about that!

**Comment by edeandrea** [comment]
Thanks! Once 2.16 ships I'll verify that it fixes https://github.com/quarkusio/quarkus-super-heroes/issues/146

**Comment by edeandrea** [comment]
Hey @cescoffier circling back to this.

When reading https://smallrye.io/smallrye-stork/1.4.1/service-discovery/knative/#caching-the-service-instances I see this property: `quarkus.stork.my-knservice.service-discovery.knative-namespace`

Is that property required? If left blank will it assume the same namespace as the app?

If its required, then this solution doesn't solve the original problem discussed in quarkusio/quarkus-super-heroes#146

**Comment by cescoffier** [comment]
@aureamunoz ^

**Comment by edeandrea** [comment]
@cescoffier additionally, how do I tell the stork knative client what the name of the knative service is?

the docs say 

```
quarkus.stork.my-knservice.service-discovery.type=knative

Stork looks for the Knative Service with the given name (my-knservice in the previous example) in the specified namespace.
```

But in my case my jaxrs client has `@RegisterRestClient(configKey = "hero-client")`

So how do I bind `hero-client` to the knative service name of `rest-heroes`? Seems there is something missing in the configuration?

For example, with the kubernetes service discovery, I would put `quarkus.stork.hero-service.service-discovery.application: rest-heroes`

I don't think having `quarkus.stork.my-knservice` is correct? It isn't consistent with any of the other service discovery configs.

Other service discovery configs are in the format `quarkus.stork.my-service.service-discovery.....`

**Comment by aureamunoz** [comment]
> Is that property required? If left blank will it assume the same namespace as the app?
> 

The `quarkus.stork.my-knservice.service-discovery.knative-namespace` property is not required. If blank, the namespace used is the one from the kubernetes client configuration.

**Comment by edeandrea** [comment]
@aureamunoz see my other comments in https://github.com/quarkusio/quarkus/pull/30272#issuecomment-1419240057 & https://github.com/quarkusio/quarkus/pull/30272#issuecomment-1419244144

How do I bind the knative service discovery to a particular rest client within my app? Happy to chat offline if I've confused you :)

**Comment by aureamunoz** [comment]
> I would think I would want something like this:

>  quarkus.stork.hero-service.service-discovery.type: knative
>  quarkus.stork.hero-service.service-discovery.application: rest-heroes
>  quarkus.stork.villain-service.service-discovery.type: knative
>  quarkus.stork.villain-service.service-discovery.application: rest-villains

> This would say that the hero-service client used knative service discovery and was looking for the rest-heroes knative > service within the same namespace as the current app

> Similar with the villain-service binding to the rest-villains knative service within the same namespace.

> There may be situations where a single app is using multiple service discovery mechanisms per client. Say, for 
> example, with the superheroes, the hero service is a knative app, but the villain service is a regular app deployed via a > k8s Deployment. I'd want to bind the hero-service via the knative discovery type, but then bind the villain-service via > the kubernetes discovery `type.`

> 

It works exactly like described here. We have an issue displaying the documentation (I will open an issue for it). The following configuration properties are available for knative service discovery:

| Attribute           | Mandatory | Default Value | Description                                                                 |
| ------------------- | --------- | ------------- | --------------------------------------------------------------------------- |
| `knative-host`      | No        |               | The Knative API host.                                                       |
| `knative-namespace` | No        |               | The namespace of the service. Use all to discover all namespaces.           |
| `application`       | No        |               | The Knative application Id; if not defined Stork service name will be used. |
| `refresh-period`    | No        | `5M`          | Service discovery cache refresh period.                                     |
| `secure`            | No        |               | Whether the connection with the service should be encrypted with TLS.       |

**Comment by cescoffier** [comment]
Stork web site fixed....

Do not ask what went wrong. I just retriggered the publication, and voilà....

**Pull request merged**
