### PR TITLE
Also include stream information in CLI project creation

### PR DESCRIPTION
**Pull request by gsmet**
This has been done a long while ago for standard apps but I missed to update the CLI somehow.

### CODE REVIEW

**Comment by gsmet** [comment]
@MichalMaler pinging you as I'm not sure if the downstream doc overrides `create-app-group-id`. If so, it will have to override `create-cli-group-id` too after this PR is merged.

**Comment by MichalMaler** [comment]
> @MichalMaler pinging you as I'm not sure if the downstream doc overrides `create-app-group-id`. If so, it will have to override `create-cli-group-id` too after this PR is merged.

Hello. I think downstream not override anything ATM. We have this attribute specified in our `attributes.adoc`:
:create-app-group-id: org.acme

I will ask @inoxx03 for confirmation. I guess he will have more info about this too :)
Stefan, please, do we have any plan about this attribute being defined downstream with a specific value?

**Comment by inoxx03** [comment]
@gsmet I've run a search of our docs set and can confirm that a the moment we do not override the `create-app-group-id` in the downstream docs.

Form what i know, we'll need to override the platform `{quarkus-platform-groupid}` when we downstream the [automated upgrade guide](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/update-quarkus.adoc), but we have been leaving the _org.acme_ example project name in the downstream docs so far.

From a long term perspective, I wouldn't exclude the possibility that we might want to override it at some point, in which case we can do 2 things  downstream:

* override the `create-cli-group-id` attribute instead of `create-app-group-id` (Works if we are reusing the complete upstream attribute file downstream, albeit the attribute name would be slightly counterintuitive in the context of downstream docs)
* define our own value for the `create-app-group-id` attribute. (this would only work if we maintain our own set of downstream attributes in a separate `attributes.adoc` file which would only live downstream)

Either way I don't think that this change is going to break our docs. @MichalMaler please feel free to follow-up if you know that this change carries a risk of breaking anything downstream, although I don't think it does at the moment.

Why exactly was the attribute name change necessary?

**Comment by gsmet** [comment]
Thanks, I will merge it then.

**Comment by maxandersen** [comment]
just a quick comment - the whole intent on how we made quarkus have notion of platforms and streams is to avoid having to document different behaviors. it should be sufficient to just enable the product registry first and it should use the recommended defaults from that registry.

**Comment by maxandersen** [comment]
so if some productized docs had to make changes like this we would be making differences that shouldn't be necessary.

**Pull request merged**
