### PR TITLE
Fix wrong entry for spring-data-jpa in deployment bom

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
cc @michalszynkiewicz

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
I let @michalszynkiewicz check it too.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by gsmet** [comment]
Backport tag, backport tag :).

**Comment by geoand** [comment]
Ooops :P

**Pull request merged**
