### PR TITLE
Update to Vert.x 4.5.7

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
Backport note: 3.9 / 3.8 are based on Vert.x 4.5.x

**Review by geoand — APPROVED** [review]

**Comment by jponge** [comment]
I'm doing a separate 3.2 backport

**Comment by geoand** [comment]
Some GraalVM substitutions will definitely be needed to fix:

```
2024-03-28T10:04:40.0884388Z Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.netty.handler.codec.http.HttpContentCompressor$ZstdEncoderFactory.createEncoder(HttpContentCompressor.java:459) 
2024-03-28T10:04:40.0886540Z Parsing context:
2024-03-28T10:04:40.0887601Z ------------------------------------------------------------------------------------------------------------------------
2024-03-28T10:04:40.0889390Z    at io.netty.handler.codec.http.HttpContentCompressor.beginEncode(HttpContentCompressor.java:275)
2024-03-28T10:04:40.0891458Z    at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:163)
2024-03-28T10:04:40.0895891Z    at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:57)
2024-03-28T10:04:40.0940626Z    at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
2024-03-28T10:04:40.0941999Z                        15.5s (19.5% of total time) in 145 GCs | Peak RSS: 3.29GB | CPU load: 3.81
2024-03-28T10:04:40.0948157Z    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
2024-03-28T10:04:40.0950209Z    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
2024-03-28T10:04:40.0952128Z    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956)
2024-03-28T10:04:40.0954443Z    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982)
2024-03-28T10:04:40.0956098Z    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
2024-03-28T10:04:40.0957516Z    at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:183)
2024-03-28T10:04:40.0958798Z    at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:233)
2024-03-28T10:04:40.0960126Z    at io.vertx.core.net.impl.ConnectionBase.writeClose(ConnectionBase.java:204)
2024-03-28T10:04:40.0961337Z    at io.vertx.core.net.impl.ConnectionBase.close(ConnectionBase.java:283)
2024-03-28T10:04:40.0962645Z    at io.vertx.core.http.impl.Http1xConnectionBase.close(Http1xConnectionBase.java:99)
2024-03-28T10:04:40.0964107Z    at io.vertx.core.http.impl.Http1xServerConnection.close(Http1xServerConnection.java:89)
2024-03-28T10:04:40.0965463Z    at io.vertx.core.net.impl.ConnectionBase.close(ConnectionBase.java:135)
2024-03-28T10:04:40.0966622Z    at io.vertx.core.net.impl.VertxHandler.close(VertxHandler.java:158)
2024-03-28T10:04:40.0968075Z    at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:757)
2024-03-28T10:04:40.0969805Z    at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:733)
2024-03-28T10:04:40.0971586Z    at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:560)
2024-03-28T10:04:40.0973072Z    at io.vertx.core.net.impl.VertxHandler.exceptionCaught(VertxHandler.java:138)
2024-03-28T10:04:40.0974752Z    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
2024-03-28T10:04:40.0976633Z    at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:854)
2024-03-28T10:04:40.0978338Z    at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
2024-03-28T10:04:40.0979886Z    at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
2024-03-28T10:04:40.0981138Z    at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
2024-03-28T10:04:40.0982388Z    at io.netty.channel.DefaultChannelConfig.setAutoRead(DefaultChannelConfig.java:341)
2024-03-28T10:04:40.0983860Z    at io.netty.channel.socket.nio.NioDatagramChannelConfig.setAutoRead(NioDatagramChannelConfig.java:178)
2024-03-28T10:04:40.0984857Z    at io.netty.channel.socket.nio.NioDatagramChannelConfig.setAutoRead(NioDatagramChannelConfig.java:36)
2024-03-28T10:04:40.0985743Z    at io.netty.channel.DefaultChannelConfig.setOption(DefaultChannelConfig.java:183)
2024-03-28T10:04:40.0986657Z    at io.netty.channel.socket.DefaultDatagramChannelConfig.setOption(DefaultDatagramChannelConfig.java:134)
2024-03-28T10:04:40.0987655Z    at io.netty.channel.socket.nio.NioDatagramChannelConfig.setOption(NioDatagramChannelConfig.java:216)
2024-03-28T10:04:40.0988543Z    at io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:487)
2024-03-28T10:04:40.0989349Z    at io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:479)
2024-03-28T10:04:40.0990079Z    at io.netty.bootstrap.ServerBootstrap.init(ServerBootstrap.java:133)
2024-03-28T10:04:40.0990949Z    at io.quarkus.netty.runtime.graal.Target_io_netty_bootstrap_AbstractBootstrap.initAndRegister(NettySubstitutions.java:351)
2024-03-28T10:04:40.0991833Z    at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:288)
2024-03-28T10:04:40.0992758Z    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:284)
2024-03-28T10:04:40.0993578Z    at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeVirtual(VertxHttpRecorder.java:1395)
2024-03-28T10:04:40.0994715Z    at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:317)
2024-03-28T10:04:40.0995578Z    at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy_0(Unknown Source)
2024-03-28T10:04:40.0996564Z    at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy(Unknown Source)
2024-03-28T10:04:40.0997264Z    at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2024-03-28T10:04:40.0997827Z    at io.quarkus.runtime.Application.start(Application.java:101)
2024-03-28T10:04:40.0998542Z    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
2024-03-28T10:04:40.0999203Z    at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
2024-03-28T10:04:40.0999687Z    at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2024-03-28T10:04:40.1000284Z    at com.oracle.svm.core.JavaMainWrapper.runCore0(JavaMainWrapper.java:237)
2024-03-28T10:04:40.1000950Z    at com.oracle.svm.core.JavaMainWrapper.doRun(JavaMainWrapper.java:293)
2024-03-28T10:04:40.1001827Z    at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
2024-03-28T10:04:40.1002550Z    at static root method.(Unknown Source)
2024-03-28T10:04:40.1002803Z 
2024-03-28T10:04:40.1003340Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
2024-03-28T10:04:40.1004518Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:184)
2024-03-28T10:04:40.1005738Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:153)
2024-03-28T10:04:40.1007051Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:111)
2024-03-28T10:04:40.1008498Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:114)
2024-03-28T10:04:40.1009768Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:620)
2024-03-28T10:04:40.1010763Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:491)
2024-03-28T10:04:40.1011900Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
2024-03-28T10:04:40.1013151Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
2024-03-28T10:04:40.1014230Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
2024-03-28T10:04:40.1015008Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
2024-03-28T10:04:40.1015775Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
2024-03-28T10:04:40.1016539Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
2024-03-28T10:04:40.1017239Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
2024-03-28T10:04:40.1018021Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-03-28T10:04:40.1020403Z Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: com.oracle.svm.core.util.UserError$UserException: Class initialization of io.netty.handler.codec.compression.ZstdConstants failed. This error is reported at image build time because class io.netty.handler.codec.compression.ZstdConstants is registered for linking at image build time by command line and command line. Use the option 
2024-03-28T10:04:40.1022482Z 
2024-03-28T10:04:40.1022920Z     '--initialize-at-run-time=io.netty.handler.codec.compression.ZstdConstants'
```

**Comment by jponge** [comment]
I'll get back to this later today, I now need to unlock another Mutiny + Reactive Messaging PR for @ozangunalp

**Comment by jponge** [comment]
Just added a substitution to cut `ZstdConstants` ties to an optional library.

**Comment by jponge** [comment]
Note on backporting 3.2: we should move forward with a Vert.x 4.4.9 release by @vietj

**Review by geoand — APPROVED** [review]

**Comment by jponge** [comment]
@geoand I'll work on the 3.2 backport later today following the release of Vert.x 4.4.9 (thanks @vietj!)

**Pull request merged**
