### PR TITLE
Remove the old MetricBuildItem SPI

### LINKED ISSUE #39468: ChainBuildException - Cycle detected after #39352 PR
### Describe the bug

I noticed regression with recent Quarkus main using https://github.com/quarkus-qe/beefy-scenarios 002-quarkus-all-extensions module

```
[ERROR] Errors:
[ERROR]   AlmostAllQuarkusExtensionsTest.testQuarkusEndpointWithManyExtensions » Runtime java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady produced class io.quarkus.arc.deployment.BeanContainerBuildItem
		to io.quarkus.flyway.deployment.FlywayProcessor#startActions produced class io.quarkus.agroal.spi.JdbcDataSourceSchemaReadyBuildItem
		to io.quarkus.hibernate.orm.deployment.metrics.HibernateOrmMetricsProcessor#metrics produced class io.quarkus.deployment.metrics.MetricsFactoryConsumerBuildItem
		to io.quarkus.smallrye.metrics.deployment.SmallRyeMetricsProcessor#extensionMetrics produced class io.quarkus.arc.deployment.UnremovableBeanBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.ResourcesGeneratedPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#initializeContainer produced class io.quarkus.arc.deployment.ArcContainerBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#notifyBeanContainerListeners produced class io.quarkus.arc.deployment.PreBeanContainerBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady
```

I was able to pin down the PR that caused this regression and it's https://github.com/quarkusio/quarkus/pull/39352 CC @geoand 

I have prepared minimal reproducer application [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/14614002/code-with-quarkus.zip) to identify the minimal set of dependencies :
```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-flyway</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-metrics</artifactId>
    </dependency>
```

The key part is quarkus-smallrye-metrics usage, mentioned PR fixes issue for Hibernate / Micrometer combination but introduces regression for SRye Metrics. 

### Expected behavior

Build ends succesfully

### Actual behavior

Build fails

### How to Reproduce?

Run `mvn clean verify` in 002-quarkus-all-extensions module from https://github.com/quarkus-qe/beefy-scenarios 

Or run `mvn clean verify` with this minimal reproducer application [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/14614002/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus main d30f1618e3f1c6c3d1effc0180bb58db8cad49f0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jmartisk**
I don't think this is being used anywhere anyway???

The problem was in producing `UnremovableBeanBuildItem` in `SmallRyeMetricsProcessor.java#extensionMetrics`, so this sounds like a good time to get rid of that stuff

- Fixes: https://github.com/quarkusio/quarkus/issues/39468

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by rsvoboda** [comment]
@gsmet @geoand Is there anything like "migration guide for extensions"? This can be a breaking change for extensions with an old codebase.

**Comment by geoand** [comment]
Not that I am aware of. 

I wonder if instead of removing the build item, we can just deprecate it (for removal) and not consume it anywhere...

**Comment by jmartisk** [comment]
> Not that I am aware of.
> 
> I wonder if instead of removing the build item, we can just deprecate it (for removal) and simply not consume it anywhere...

Then a potential extension that uses it would still compile and its applications would compile and run, but wouldn't get the expected metrics. I think it's better to make it fail fast (so, at compile time)

**Comment by geoand** [comment]
Hold on, then I don't understand how an extension that currenly uses them should do in light of their removal, can you explain?

**Comment by gsmet** [comment]
When did it get deprecated? I don't see a `since` in the deprecated annotation.

**Comment by geoand** [comment]
It did not, @jmartisk is proposing to straigh up remove it as it's not used anywhere (something we absolutely need to check)

**Review by ebullient — APPROVED** [review]

**Comment by jmartisk** [comment]
It's been deprecated since 2020: https://github.com/quarkusio/quarkus/pull/10626

**Comment by ebullient** [comment]
> It did not, @jmartisk is proposing to straigh up remove it as it's not used anywhere (something we absolutely need to check)

I'm down with removing it aggressively, but I can understand downstream worries.

**Comment by geoand** [comment]
> It's been deprecated since 2020: #10626

Oh, that's great to know!

**Comment by gsmet** [comment]
Yeah, I think we should check if this is used by Camel Quarkus and maybe a few other Platform members.

Because I backported Georgios' PR to 3.8 so that means we would need to backport this to 3.8.

**Comment by geoand** [comment]
> Yeah, I think we should check if this is used by Camel Quarkus and maybe a few other Platform members.

@jmartisk can you check this?

**Comment by geoand** [comment]
I personally was able to find it being used anywhere but Quarkus core

**Review by gsmet — APPROVED** [review]

**Pull request merged**
