### PR TITLE
Support constructor injection into providers

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Good idea!

**Comment by famod** [comment]
@stuartwdouglas @geoand Could it be that there is a stale warning in `ResteasyCommonProcessor` after this change? In CI there is the same warning as in my current project:
```
[INFO] Running io.quarkus.resteasy.test.CustomExceptionMapperTestCase
2021-06-09 07:21:04,664 WARN  [io.qua.res.com.dep.ResteasyCommonProcessor] (build-4) Classes annotated with @Provider should have a single, no-argument constructor, otherwise dependency injection won't work properly. Offending class is io.quarkus.resteasy.test.CustomExceptionMapperTestCase$CustomExceptionMapper
```

**Comment by geoand** [comment]
Yes, that warning is longer valid.

Mind removing it?

**Comment by famod** [comment]
Your request was registered at queue position 174828. 🤪

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/18328

**Comment by stuartwdouglas** [comment]
Oops, I saw the email and decided to fix it, but did not check GH (as based on your comment I did not think you were going to work on this). 

I think my approach is better though, as you still need an @Inject constructor.

**Comment by famod** [comment]
Sure, if that's the case (and ArC auto-@Inject isn't working here) then your PR should be merged instead!

**Comment by stuartwdouglas** [comment]
ah, I forgot about auto inject. Lets just go with your PR

**Pull request merged**
