### PR TITLE
Use lazy task api in gradle plugins

### PR DESCRIPTION
**Pull request by grossws**
Minor modifications to avoid eager task creating when they aren't required for build.

### CODE REVIEW

**Comment by grossws** [comment]
@glefloch, I guess you're the best person to ping about Gradle improvements. If you have a bit of time to chat about that I sent a message to #dev on Zulip.

**Review by glefloch — APPROVED** [review]
LGTM, thanks @grossws

**Comment by grossws** [comment]
Heh, now I need to import full project in the IDE. Where do I get `maven:rewrite-maven-plugin:4.21.0-SNAPSHOT`?

**Comment by glefloch** [comment]
I would say in maven central, I haven't any custom repository configuration on my machine, and I never had issue with maven plugins. 
There is a ˋCONTRIBUTION.md` in the root directory of the project with instructions for importing the project in IDE. That may help you

**Comment by grossws** [comment]
Yeah, I read that, of course. It just takes a while for IDEA to import project and download jars/sources.
Central doesn't host snapshot versions, so you likely have it in maven local repo. I just built it from source (after rewinding to some old commit).
Unfortunately IDE doesn't see that `quarkus-gradle-model` depends gradle api so I'm running required integration tests directly with maven. I'll update PR later. I'd need to run gradle under integration tests with debug and hook there. At least I now can trace where it fails.

**Comment by grossws** [comment]
@gsmet, thanks for the info

**Comment by grossws** [comment]
@glefloch, I've updated this PR too to fix issue found by integration tests and reworded commit names according to style preferred here.

Gradle integation tests pass on my laptop. Could you respin CI for it, please.

**Comment by Sanne** [comment]
@grossws - sorry it took so long, could you rebase it and resolve the conflicts please?

**Comment by glefloch** [comment]
@grossws sorry that delay could you rebase your branch and squash your commits? Otherwise Everything looks good to me.

**Comment by grossws** [comment]
@glefloch, I'll try to update the PR later this week or on a weekend

**Comment by grossws** [comment]
@Sanne, @glefloch, I've rebased, updated a bit & squashed commits into one.

It seemed to me that you (as in Quarkus committers) aren't against plugin API changes between minor version updates. If it's the case I'd like to push some more changes to improve Gradle plugins.

**Comment by glefloch** [comment]
Thanks @grossws i will have a look. Regarding API changes, we avoid breaking backward compatibility but feel free to open new PRs. :)

**Comment by gsmet** [comment]
@glefloch could you have a look at this one before we ask for a rebase?

**Review by glefloch — APPROVED** [review]
Looks good to me. Sorry for the delay

**Comment by grossws** [comment]
@glefloch, @gsmet, rebased onto current `main`

**Review by glefloch — APPROVED** [review]

**Comment by glefloch** [comment]
Thanks @grossws

**Pull request merged**
