### PR TITLE
Improve OIDC warning when a session encryption key is generated

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
That is strange, I actually run and built it...

**Comment by sberyozkin** [comment]
@gsmet I'm struggling with fixing this formatting issue.

`mvn clean install -DskipTests` build does not fix it.

`mvn -f extensions/oidc/runtime net.revelc.code.formatter:formatter-maven-plugin:2.24.0:format`

gives
 ```
running `[WARNING] This build will only read from the build cache, since the clean lifecycle is not part of the build invocation.
```
and also does not fix it.

How can I remove the build cache ?

**Comment by Eng-Fouad** [comment]
> @gsmet I'm struggling with fixing this formatting issue.
> 
> `mvn clean install -DskipTests` build does not fix it.
> 
> `mvn -f extensions/oidc/runtime net.revelc.code.formatter:formatter-maven-plugin:2.24.0:format`
> 
> gives
> 
> ```
> running `[WARNING] This build will only read from the build cache, since the clean lifecycle is not part of the build invocation.
> ```
> 
> and also does not fix it.
> 
> How can I remove the build cache ?

See: https://github.com/quarkusio/quarkus/pull/40945

**Review by gsmet — APPROVED** [review]
@sberyozkin I fixed it.

Let's make sure CI passes and we can merge.

**Comment by sberyozkin** [comment]
Thanks @gsmet

**Pull request merged**
