### PR TITLE
Add default empty favicon.ico when using RESTEasy Reactive in Qute

### LINKED ISSUE #16548: Default favicon.ico for quarkus-resteasy
When adding an `index.html` file in `src/main/resources/META-INF/resources/` and opening it in a browser, the development console shows this error in the console:

image

_If and only if_ the user did not create a `src/main/resources/META-INF/resources/favicon.ico` file, Quarkus should automatically return a default one. If that's the Quarkus icon, it's very good for Quarkus marketing. But it might have a security impact.

### PR DESCRIPTION
**Pull request by geoand**
The reasoning behind this is that when `quarkus-resteasy-reactive-qute` is used, the application likely serves HTML, so having a favicon makes sense.

Users can override this easily by adding their own `favicon.ico` in `src/main/resources/META-INF/resources` (the standard location where Quarkus serves static resources from)

Closes: #16548

### CODE REVIEW

**Comment by mkouba** [comment]
What happens if I add my own `src/main/resources/META-INF/resources/favicon.ico` in my app? Is it used instead of the default one?

**Comment by gsmet** [comment]
I'm not sure it's such a good idea. My reasoning is that it is showing the technology that is used underneath if you're not careful and don't add your own favicon and that could be seen as a security issue by some companies (in some companies, any indication of the technology that is used is seen as a potential security problem as it gives information to potential attackers).

Also, I don't see a case where having the Quarkus favicon would be something the user would want? So you would have to override it always anyway.

**Comment by geoand** [comment]
> What happens if I add my own src/main/resources/META-INF/resources/favicon.ico in my app? Is it used instead of the default one?

Yes, I tried it

**Comment by geoand** [comment]
> I'm not sure it's such a good idea. My reasoning is that it is showing the technology that is used underneath if you're not careful and don't add your own favicon and that could be seen as a security issue by some companies (in some companies, any indication of the technology that is used is seen as a potential security problem as it gives information to potential attackers).
> 
> Also, I don't see a case where having the Quarkus favicon would be something the user would want? So you would have to override it always anyway.

Yeah, not sure, I don't have any strong feelings about this.

In any case, if we don't merge this, we should close https://github.com/quarkusio/quarkus/issues/16548 as `won't fix`

**Comment by mkouba** [comment]
> > I'm not sure it's such a good idea. My reasoning is that it is showing the technology that is used underneath if you're not careful and don't add your own favicon and that could be seen as a security issue by some companies (in some companies, any indication of the technology that is used is seen as a potential security problem as it gives information to potential attackers).
> > Also, I don't see a case where having the Quarkus favicon would be something the user would want? So you would have to override it always anyway.
> 
> Yeah, not sure, I don't have any strong feelings about this.
> 
> In any case, if we don't merge this, we should close #16548 as `won't fix`

Hm, could we add an empty icon instead?

**Comment by geoand** [comment]
PR updated to use an empty favicon

**Review by mkouba — APPROVED** [review]

**Comment by geoand** [comment]
@gsmet @maxandersen are you guys okay with the empty favicon?

**Comment by geoand** [comment]
Unless I hear a no on this one, I'm going to merge it :)

**Comment by maxandersen** [comment]
whats the win of having a blank favicon instead of no icon at all ? less 404 errors?

**Comment by maxandersen** [comment]
just to be pedantic it doesn't really matter if empty icon or quarkus icon - make a sha on the favicon.ico and you can identify its a quarkus app.

Does other fwks return default favicons to avoid the 404's ?

**Comment by geoand** [comment]
>  less 404 errors?

exactly

**Comment by geoand** [comment]
> Does other fwks return default favicons to avoid the 404's ?

Spring Boot does

**Comment by geoand** [comment]
> > Does other fwks return default favicons to avoid the 404's ?
> 
> Spring Boot does

It actually doesn't - I was tricked by browser caching. 
Let's close this then as the reasoning Spring Boot doesn't use it makes sense and we can do the same.

**Pull request closed without merging**
