### PR TITLE
Sync antlr in build with runtime

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by gsmet** [comment]
You opened the same PR a few days ago and CI was failing consistently. Did the issues get fixed by unrelated PRs?

Thanks.

**Comment by gsmet** [comment]
As I already explained it, our CI resources are limited so things need to be tested locally or in your fork before opening a PR.

See https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#continuous-integration .

**Comment by geoand** [comment]
Thanks for the contribution @tobiasstadler.

However, as @gsmet mentioned, it would be nice if you could first open your PR as a `draft` and only when CI has completed on your own fork, promote it to normal status.
The reason is as we receive a lot of PRs and CI infrastructure does not scale elastically based on load, PRs that are not tested end up slowing down others that are properly tested.

Thanks in advance for your understanding and compliance.

**Comment by gsmet** [comment]
Apparently, CI passed this time. But I'm puzzled why the previous PR triggered related CI failures and not this one.

**Comment by tobiasstadler** [comment]
The last time I targeted the microprofile branch. Because the build in the microprofile branch is broken, my pr failed.

**Comment by tobiasstadler** [comment]
Sorry for not waiting for my local ci run. I will do it next time

**Pull request closed without merging**
