### PR TITLE
Qute If section - fix evaluation of composite params with a logical complement operator

### LINKED ISSUE #21857: Qute: bug in `if` test
### Describe the bug

I have the following tag:

```html
{#if user && target.status == ContentStatus:NEW && !target.voted(user)}
    User: {user}<br/>
    Target.status: {target.status}<br/>
    Target.voted(user): {target.voted(user)}<br/>
{/if}
```

When I call it with some values, I'm getting this output:

```
User: User<2>
Target.status: ACCEPTED
Target.voted(user): false
```

This can't be right. As you see `target.status` is `ACCEPTED` (that's the correct value) but the `if` condition specifies `target.status == ContentStatus:NEW` so in theory we should never be able to get into the `if` block and display this.

I can give you instructions for reproducing but it requires you build the vixen branch and checkout the aviouf demo app. Otherwise you can perhaps point me where to look in a debugger to help you narrow it down?

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
..a logical complement operator
- resolves #21857

### CODE REVIEW

**Comment by mkouba** [comment]
@gsmet I believe that this one should go into 2.6.0.Final.

**Review by FroMage — APPROVED** [review]
I'll approve this, but I have to tell you that normally it's the parser's job to decide on priorities, by constructing the parsed tree using operator precedence.

Perhaps we should spend a bit of time together trying to use an ANTLR parser for Qute in the future?

**Comment by mkouba** [comment]
> I'll approve this, but I have to tell you that normally it's the parser's job to decide on priorities, by constructing the parsed tree using operator precedence.

Ofc, the problem here is that the sections params are not designed as proper language constructs. It would make sense for `{#if}` but not for other sections. Qute was originally designed as _logic-less_ templating but then we had to relax some of the rules to be more practical (`{#if}` is one of the example). So there is a mismatch and we need to find a reasonable compromise ;-).

> Perhaps we should spend a bit of time together trying to use an ANTLR parser for Qute in the future?

@angelozerr is working on this within the [quarkus-ls](https://github.com/redhat-developer/quarkus-ls) project. See also https://github.com/redhat-developer/quarkus-ls/issues/473.

**Comment by angelozerr** [comment]
> Perhaps we should spend a bit of time together trying to use an ANTLR parser for Qute in the future?

ANTLR is very powerfull but when you try to use it in an IDE/Editor you can have some trouble because even if it can manage fault tolerant (broken Qute template), it's hard for IDE/Editor to detect properly the error ranges that we need in an IDE/Editor.

More ANTLR parser stores a lot of infirmation for line, offset etc. In an IDE/Editor we need to take care of memory. That's why I implemented a Qute parser at hand.

Today my parser is linked with some information that I need (like QuteProject) but I'm sure that I can clean it and use it for Qute core. Having the same parser for the core and for IDE/Editor integration should b ereally nice. For instance IDE/Editor could pick  up the Qute Jar of the project (with a given maven dependency) and user will have the same error in the editor than the Qute mavendependency that it consumes.

**Pull request merged**
