### PR TITLE
Upgrade SmallRye GraphQL to 1.0.21

### PR DESCRIPTION
**Pull request by phillip-kruger**
Upgrading to 1.0.21 
See https://github.com/smallrye/smallrye-graphql/releases/tag/1.0.21

Only small bug fixes.

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by gsmet** [comment]
Hmmm, not sure this will be compatible with Quarkus 1.11 due to the move to Mutiny 0.13. Not backporting for now except if we have a very good reason to try it.

**Comment by phillip-kruger** [comment]
Ok no worries, should I revert the mutiny upgrade ? Or will 1.12.0 contain that ?

**Comment by gsmet** [comment]
1.12 will be OK.

The upgrade is probably OK for 1.11 anyway but I would say not worth taking the risk except if we have users complaining.

**Comment by gsmet** [comment]
Hmmm, let me try to push it, we'll see how the tests go. I can drop it this evening if we have CI issues.

**Comment by phillip-kruger** [comment]
OK let me know if/where I can help

**Review by gsmet — APPROVED** [review]

**Pull request merged**
