### PR TITLE
Bootstrap Maven resolver: switch to Maven Wagon transporters

### LINKED ISSUE #3318: Quarkus test fails on Jenkins
My application runs tests very well on my local system. However if I want to execute mvn test on my Jenkins pipeline I encounter problems that might be related to the proxy. I set my proxy for all mvn commands and I see that the dependencies are fetched. During the test phase it breaks with the following error. Is there any dependency loading outside the maven context? Is 

`
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running backend.FeedbackControllerTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 4.164 s <<< FAILURE! - in backend.FeedbackControllerTest
[ERROR] testEmptyProjectList  Time elapsed: 0.022 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [backend.FeedbackControllerTest]: Failed to create the boostrap class loader
Caused by: java.lang.IllegalStateException: Failed to create the boostrap class loader
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the deployment classloader for backend::jar:1.0-SNAPSHOT
Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to inject extension deployment dependencies for backend:jar:1.0-SNAPSHOT
Caused by: io.quarkus.bootstrap.resolver.maven.DeploymentInjectionException: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to collect dependencies for io.quarkus:quarkus-resteasy-deployment:jar:0.19.1
Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to collect dependencies for io.quarkus:quarkus-resteasy-deployment:jar:0.19.1
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for io.quarkus:quarkus-resteasy-deployment:jar:0.19.1
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for io.quarkus:quarkus-resteasy-deployment:jar:0.19.1
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.quarkus:quarkus-resteasy-deployment:pom:0.19.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.quarkus:quarkus-resteasy-deployment:pom:0.19.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known
Caused by: java.net.UnknownHostException: repo.maven.apache.org: Name or service not known
`

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #3318

### CODE REVIEW

**Comment by geoand** [comment]
Is there an easy way to test this @aloubyansky?
I don't see why it wouldn't work, just asking to be on the safe side 😀

**Comment by aloubyansky** [comment]
Yes. This mechanism kicks in during tests. So the way to test it would be to make it download one of the deployment deps.
I was testing it by removing `org.jboss.metadata` artifacts. And then running `mvn clean test -Dhttp.proxyHost=URL -Dhttp.proxyPort=PORT -Dhttps.proxyHost=URL -Dhttps.proxyPort=PORT`, as reported in the issue.
Currently used transporters would ignore these props and will simply download the missing artifacts.

**Comment by geoand** [comment]
Cool, thanks! I'll give it a shot in a couple hours if you don't mind

**Comment by geoand** [comment]
I wasn't able to replicate a setup like the OP mentioned, but this looks good to me.

**Review by geoand — APPROVED** [review]

**Comment by aloubyansky** [comment]
It should be easy. First you need to build the project. Then remove org/jboss/metadata from the local maven repo. And then pick any test and run `mvn clean test ...`
Thanks anyway for the review!

**Comment by geoand** [comment]
Yeah, I was able to do that and it worked great.

What I wasn't able to do is verify if the proxy setting actually had an effect because I couldn't easily replicate a locked down environment

**Pull request merged**
