### PR TITLE
Migrate the guides to RESTEasy Reactive

### LINKED ISSUE #24174: Move all the guides to use RESTEasy Reactive
- Apply the necessary changes to the extensions added (command, text, dependencies...)
- Apply the necessary changes to the quickstart code (see ongoing PR here: https://github.com/quarkusio/quarkus-quickstarts/pull/971/files)

### PR DESCRIPTION
**Pull request by gsmet**
@geoand this is the first step I had in mind.

I think, after this is in, we need:
- to have a closer look to the RESTEasy Reactive guide. I remember things being a bit weird there especially in the class names of the examples and I would prefer we make things more mainstream
- the REST JSON guide needs a check by you, especially to make sure everything I left there is valid for RESTEasy Reactive. Frankly I think the filter/interceptor part should rather be in the RESTEasy Reactive guide. I haven't found any information about the filters there.

Hopefully I haven't done too many mistakes, I'll do a review of the changes tomorrow but my eyes are too tired tonight.

Fixes #24174

### CODE REVIEW

**Comment by geoand** [comment]
>  Frankly I think the filter/interceptor part should rather be in the RESTEasy Reactive guide. I haven't found any information about the filters there.

Hm.. There is plenty of information in the reference documentation:

Filters: https://quarkus.io/guides/resteasy-reactive#request-or-response-filters
Interceptors: https://quarkus.io/guides/resteasy-reactive#reader-and-writer-interceptors

**Comment by gsmet** [comment]
> The reference guide has a lot more information than the rest-json guide, although the latter is still valid for RESTEasy Reactive.

So my idea is to make the REST JSON guide a very simple introduction/getting started. And then you have the more comprehensive reference guide.

> Hm.. There is plenty of information in the reference documentation:

Ah OK, I was looking for `ContainerRequestFilter` and didn't find it. There's just a pointer to the JAX-RS spec. I will move the paragraph.

**Comment by geoand** [comment]
> So my idea is to make the REST JSON guide a very simple introduction/getting started. And then you have the more comprehensive reference guide.

Sounds good to me!

**Comment by gsmet** [comment]
I will merge it as soon as CI is green as I need one of the changes for my other patches.

**Pull request merged**
