### PR TITLE
Prevent duplicate HTTP headers when WriterInterceptor is used

### LINKED ISSUE #27325: Resteasy Reactive duplicates headers when custom WriterInterceptor is present
### Describe the bug

After migrating my app to resteasy-reactive, I noticed that all response headers I set myself are being duplicated.
Headers set by quarkus, like content-length and content-type, are only present once in the response as expected

Essentially, whenever a custom writerinterceptor is present in the app, all custom response headers are duplicated. The interceptor does not even have to do anything.

This duplication did not happen with resteasy classic.

```
@Provider
public class CachePolicyHeaderProvider implements WriterInterceptor {

    @Override
    public void aroundWriteTo(WriterInterceptorContext context) throws IOException, WebApplicationException {
        context.proceed();
    }
}
```

```
@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response hello() {
        return Response.ok("123").lastModified(new Date()).header("etag", 0).build();
    }
}
```

### Expected behavior

No headers are getting duplicated.

### Actual behavior

image

### How to Reproduce?

Reproducer: 
[Uploading etag-duplication.zip…]()

1. mvn quarkus:dev
2. go to http://localhost:8080/hello in a browser
3. look at the servers response in the network view
4. notice the response headers being duplicated

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1889]

### Output of `java -version`

openjdk version "18.0.2" 2022-07-19 OpenJDK Runtime Environment Temurin-18.0.2+9 (build 18.0.2+9) OpenJDK 64-Bit Server VM Temurin-18.0.2+9 (build 18.0.2+9, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 18.0.2, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\18 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #27325

### CODE REVIEW

**Review by Sgitario — COMMENTED** [review]
After digging into the code, I see that what this change is doing is avoiding calling ServerSerializers.encodeResponseHeaders (https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java#L71). 

This consumer is being invoked because it has been previously registered in https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java#L194. 

Therefore, I have two questions/comments:
a. Instead of setting the listener to null, why not avoid setting it in here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java#L71
b. Or why not improving the logic of ServerSerializers.encodeResponseHeaders to remove the response header before adding it: `vertxResponse.removeResponseHeader(header)`.

Note that I tried to do the option b. without removing the listener and it worked fine.

**Comment by geoand** [comment]
> a. Instead of setting the listener to null, why not avoid setting it in here:

This code path is needed for all other cases other than the writer interceptor handling

> b. Or why not improving the logic of ServerSerializers.encodeResponseHeaders to remove the response header before adding it

We don't want to do this because it's possible for Vert.x handles that run before RESTEasy Reactive to add headers that are then written out

**Comment by Sgitario** [comment]
> Very good questions indeed!
> 
> Below are my answers on why we can't do one or the other:
> 
> > a. Instead of setting the listener to null, why not avoid setting it in here:
> 
> This code path is needed for all other cases other than the writer interceptor handling
> 
> > b. Or why not improving the logic of ServerSerializers.encodeResponseHeaders to remove the response header before adding it
> 
> We don't want to do this because it's possible for Vert.x handles that run before RESTEasy Reactive to add headers that are then written out

I don't fully understand the scenario of your last statement, but if you have already thought about these two solutions and decided to implement the current change, I trust your solution is the best approach :) Approving.

**Review by Sgitario — APPROVED** [review]

**Comment by geoand** [comment]
> I don't fully understand the scenario of your last statement

The most common use case is [this](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.header.-header-.value) feature.

**Comment by Sgitario** [comment]
> > I don't fully understand the scenario of your last statement
> 
> The most common use case is [this](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.header.-header-.value) feature.

I've added a test in `quarkus-resteasy-reactive/deployment` to try to reproduce the scenario you described (using the property `quarkus.http.header...`). The test covers the same thing as the one you added in the independent project plus using the header property too. 

The thing is that the test is behaving exactly the same either if you use the changes of this pull request or if you remove the header before setting it right before this line https://github.com/quarkusio/quarkus/blob/effe3f9a865ffd0fcc26d2f6828f5a78b2fe17d4/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java#L497. 

This is the implementation:

```java
package io.quarkus.resteasy.reactive.server.test.response;

import static io.restassured.RestAssured.when;
import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.is;

import java.io.IOException;
import java.util.Arrays;
import java.util.Date;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerResponseContext;
import javax.ws.rs.container.ContainerResponseFilter;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.ext.Provider;
import javax.ws.rs.ext.WriterInterceptor;
import javax.ws.rs.ext.WriterInterceptorContext;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import io.quarkus.test.QuarkusUnitTest;
import io.restassured.http.Headers;

public class CustomHeadersAndWriterInterceptorTest {

    @RegisterExtension
    static QuarkusUnitTest runner = new QuarkusUnitTest()
            .withApplicationRoot((jar) -> jar
                    .addClasses(DummyWriterInterceptor.class, TestResource.class))
            .overrideConfigKey("quarkus.http.header.\"propertyHeader\".value", "foo")
            .overrideConfigKey("quarkus.http.header.\"aggregateHeader\".value", "1");

    @Test
    void testResponseHeaders() {
        Headers headers = when()
                .get("/test")
                .then()
                .statusCode(200)
                .header("etag", is("0"))
                .extract().headers();
        assertThat(headers.getList("etag")).hasSize(1);
        assertThat(headers.getList("Last-Modified")).hasSize(1);
        assertThat(headers.getList("customHeader")).hasSize(1);
        assertThat(headers.getValue("customHeader")).isEqualTo("[a]");
        assertThat(headers.getValue("propertyHeader")).isEqualTo("foo");
        assertThat(headers.getList("aggregateHeader")).hasSize(2);
        assertThat(headers.getValue("aggregateHeader")).isEqualTo("[2]");
    }

    @Path("/test")
    public static class TestResource {

        @GET
        @Produces(MediaType.TEXT_PLAIN)
        public Response hello() {
            return Response.ok("123").lastModified(new Date()).header("etag", 0).build();
        }
    }

    @Provider
    public static class MyCustomHeaderFilter implements ContainerResponseFilter {

        @Override
        public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext)
                throws IOException {
            responseContext.getHeaders().add("customHeader", Arrays.asList("a"));
            responseContext.getHeaders().add("aggregateHeader", Arrays.asList("2"));
        }
    }

    @Provider
    public static class DummyWriterInterceptor implements WriterInterceptor {

        @Override
        public void aroundWriteTo(WriterInterceptorContext context) throws IOException, WebApplicationException {
            context.proceed();
        }
    }

}
```

**Comment by geoand** [comment]
I might be misremembering when that Vert.x handler runs, but you should be able to reproduce the scenario I mentioned above if you create a custom Vert.x Web handler that runs before RESTEasy Reactive anb simply sets an HTTP header.

**Pull request merged**
