### PR TITLE
fix: handling of arrays in kubernetes properties

### PR DESCRIPTION
**Pull request by iocanel**
Bump to the latest dekorate version that addresses the issue of handling arrays in kubernetes properties.

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel can you please rebase onto the latest master?

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
@iocanel the kubernetes integration tests are failing

**Comment by geoand** [comment]
@iocanel is there anymore that needs to go into this one?

**Comment by iocanel** [comment]
@geoand yeah! Need to fix the issue in dekorate and bump! Will work on that either during the weekend or on Monday!

**Comment by geoand** [comment]
Cool, thanks!

**Comment by gsmet** [comment]
@iocanel any update?

**Comment by iocanel** [comment]
> @iocanel any update?

I am afraid not!

**Comment by geoand** [comment]
@iocanel seems like the Windows CI issue still persists

**Comment by iocanel** [comment]
@geoand can we kick the CI again? There was a problem with central, which prevented half of the dekorate artifacts to sync for a day or so. It should be better now.

**Comment by geoand** [comment]
CI is budging for some reason...

**Comment by geoand** [comment]
There it goes :relieved:

**Comment by iocanel** [comment]
I give up with 0.10.6. I will re-release!

**Comment by geoand** [comment]
:crossed_fingers:

**Comment by geoand** [comment]
It seems like this PR is cursed...

```
2020-01-20T07:31:25.7621459Z [ERROR] Failed to execute goal on project quarkus-kubernetes-deployment: Could not resolve dependencies for project io.quarkus:quarkus-kubernetes-deployment:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.dekorate:dekorate-core:jar:0.10.7, io.dekorate:dekorate-dependencies:jar:0.10.7, io.dekorate:s2i-annotations:jar:0.10.7: Could not find artifact io.dekorate:dekorate-core:jar:0.10.7 in google-maven-central (https://maven-central-eu.storage-download.googleapis.com/repos/central/data/) -> [Help 1]
```

**Comment by geoand** [comment]
I did however checkout the PR locally and when trying to build it, I got:

```
[ERROR] Failed to execute goal on project quarkus-kubernetes-deployment: Could not resolve dependencies for project io.quarkus:quarkus-kubernetes-deployment:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.dekorate:dekorate-core:jar:0.10.7, io.dekorate:dekorate-dependencies:jar:0.10.7, io.dekorate:s2i-annotations:jar:0.10.7: Could not find artifact io.dekorate:dekorate-core:jar:0.10.7 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

```

**Comment by iocanel** [comment]
From what I see there are corrupt metadata and missing artifacts on central.
Can't tell if its from the dekorate side or a sonatype issues, but as we haven't willigly changed anything in our release process, I raised an issue against sonatype: https://issues.sonatype.org/browse/MVNCENTRAL-5488?filter=-2

**Comment by iocanel** [comment]
@geoand @gsmet: sonatype issues got resolved it builds now locally? can we kick CI?

**Comment by gsmet** [comment]
It's running.

**Comment by geoand** [comment]
@iocanel there is another failure:

```
2020-01-20T23:15:56.3073743Z [INFO] [INFO] ------------------------------------------------------------------------
2020-01-20T23:15:56.3537845Z [INFO] run post-build script verify.groovy
2020-01-20T23:15:56.3580936Z [INFO] Running post-build script: /home/vsts/work/1/s/integration-tests/kubernetes/target/it/kubernetes-with-application-properties/verify.groovy
2020-01-20T23:15:57.2467778Z [INFO] Finished post-build script: /home/vsts/work/1/s/integration-tests/kubernetes/target/it/kubernetes-with-application-properties/verify.groovy
2020-01-20T23:15:57.2470817Z [INFO]           kubernetes-with-application-properties/pom.xml ... SUCCESS (8.7 s)
2020-01-20T23:15:57.2479493Z [INFO] -------------------------------------------------
2020-01-20T23:15:57.2480152Z [INFO] Build Summary:
2020-01-20T23:15:57.2482942Z [INFO]   Passed: 4, Failed: 2, Errors: 0, Skipped: 0
2020-01-20T23:15:57.2483767Z [INFO] -------------------------------------------------
2020-01-20T23:15:57.2486813Z [ERROR] The following builds failed:
2020-01-20T23:15:57.2487656Z [ERROR] *  openshift-with-application-properties/pom.xml
2020-01-20T23:15:57.2488106Z [ERROR] *  openshift/pom.xml
2020-01-20T23:15:57.2488832Z [INFO] -------------------------------------------------
```

**Comment by iocanel** [comment]
@geoand: Somehow, we manage to temporary lift the curse! Merge now before its back!

**Comment by geoand** [comment]
@gsmet I am adding the `backport` label since it would be nice to have this one and it's same to have

**Pull request merged**
