### PR TITLE
Attach the extension descriptor as a JSON artifact to the runtime extension project

### PR DESCRIPTION
**Pull request by aloubyansky**
This change takes the `quarkus-extension.yaml` content, serializes it to JSON and attaches the JSON to the runtime extension project.
The JSON artifact attachment can be disabled with `excludeExtensionJsonArtifact` parameter.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM. What's the GAV for this new artifact?

**Comment by aloubyansky** [comment]
It's the same GAV as the extension's runtime artifact only the type is `json` instead of `jar`.

**Comment by maxandersen** [comment]
-1. this is making our publishing process more complex for very little gain.

**Comment by gastaldi** [comment]
@maxandersen can you please elaborate on how this is more complex?

As you're already aware, the extension info is stored inside the extension's runtime JAR and requires downloading and extracting the file somewhere to be able to parse it. The rest of the JAR is useless for  indexing.

**Comment by gastaldi** [comment]
BTW the `quarkus-extension.yaml` is no longer required to be inside the runtime JAR with this change

**Comment by maxandersen** [comment]
> As you're already aware, the extension info is stored inside the extension's runtime JAR and requires downloading and extracting the file somewhere to be able to parse it. The rest of the JAR is useless for indexing.

why is it justfiable to require everyone to publish two artifacts when one is enough just so an index has to happen *once* per release ? 

> BTW the `quarkus-extension.yaml` is no longer required to be inside the runtime JAR with this change

i'm sorry but we put that file in there very deliberately so this information is available no matter how you get this jar - it would be like removing MANFIST.MF outside the jar.

What about those wanting to make extensions writing gradle or other build system - requiring deploying using seperate classifiers just for this *ONE* usecase of an index operation that needs to happen *ONCE* I see as weird.

Mind you, nothing prevents you from actually having the user when they submit the "I've relased something" to post the matching yaml, right?

**Comment by maxandersen** [comment]
also quarkus-extensions.yaml are useful for tools outside our tools i.e. IDE's to get and gather info. it would be the fallback when the remote registry or the "quarkiverse" json isn't available or incomplete.

**Comment by gastaldi** [comment]
> What about those wanting to make extensions writing gradle or other build system - requiring deploying using seperate classifiers just for this _ONE_ usecase of an index operation that needs to happen _ONCE_ I see as weird.

I'm yet to see an extension built using Gradle or other build system at the moment but I get your point :)

> i'm sorry but we put that file in there very deliberately so this information is available no matter how you get this jar - it would be like removing MANFIST.MF outside the jar.

> also quarkus-extensions.yaml are useful for tools outside our tools i.e. IDE's to get and gather info. it would be the fallback when the remote registry or the "quarkiverse" json isn't available or incomplete.

Okay, your justification makes sense, you win! :)

I'll provide a PR reverting this commit in this case.

**Pull request merged**
