### PR TITLE
Bump JUnit to 5.11.0-M2

### PR DESCRIPTION
**Pull request by dmlloyd**
Relates to #40601, #40749, #38991. No use waiting for Dependabot. Fixes problem where an NPE can occur in some tests.

### CODE REVIEW

**Comment by geoand** [comment]
🤞 for CI to pass!

**Review by geoand — APPROVED** [review]

**Comment by holly-cummins** [comment]
Good news! I'll get going on the reproducer, too, and hopefully I'll see it go green when I rebase to this change.

**Comment by holly-cummins** [comment]
Should fix https://github.com/quarkiverse/quarkiverse/issues/94 once merged (but we'll let the ecosystem CI decide). Also cc-ing @edeandrea, who should be able to re-enable the superheroes tests onces this merges.

**Comment by holly-cummins** [comment]
Doh. Looks like JUnit made some API changes we need to deal with.

**Comment by gsmet** [comment]
Sorry to spoil the party but I’m not sure I’m comfortable merging a M2 given we don’t control JUnit lifecycle.

**Comment by geoand** [comment]
The problem is that without this change, there is a chance that David's previous important PR might fail in some circumstances.

**Comment by holly-cummins** [comment]
I’ve done some digging into when this happens. PR with reproducer tests incoming, but it’s still half-baked. :)

We didn’t have any coverage for `@TemplateTest`, so I’ve added some, and don’t see the NPE. I see [other problems](#40770), but that’s orthogonal. 

I think problems happen when the JUnit extension used in the template is provided by an extension. That combination is what triggers the classloader dance which ends in using serialisation to hop between classloaders. That’s a somewhat rare scenario; I [searched](https://github.com/search?q=org%3Aquarkiverse+%40TestTemplate&type=code) in the quarkiverse org extensions, and it’s only Pact which does this (or at least, if anyone else does it, they never bothered to test it). 

So that’s the good news, but the bad news is that Quarkus 3.11 would break anyone using a Pact provider. There isn’t really a workaround. We can see from https://quarkus.io/extensions/?sort=downloads that the Pact Provider extension is reasonably well used (it’s about a third of the way down the page, more popular than Cucumber,  say). 

So I think we have three options: 

- Accept JUnit 5.11.0-M2 (once we do the work to work around the breaking changes), with the attendant risks + ickiness of shipping a milestone release.
- Temporarily revert #60401, which means reintroducing the break covered by https://github.com/quarkusio/quarkus/pull/40749/files#diff-675df95783a89f22ff50a447a6441c60196d63f1fbe018ae5294523dfd98add4. It's `@ExtendWith(MyParameterResolver.class)`, where the parameter resolver comes from an extension. That's the one I have a reproducer for, but there's a bunch of issues relating to serialization on Java 17+ that are fixed by #40601. 
- Keep the code as it currently is, which means breaking everyone doing pact provider tests. 
- Temporarily hot-patch or shade JUnit, since David's fix for the NPE is super small and safe.

**Comment by geoand** [comment]
Thanks for doing a deep dive on this @holly-cummins!

I'm personally in favor of options `1` or  `3`.

We could also try and ask the JUnit folks again if we can get a `5.10.z` release with a David's fix in it.

**Comment by gsmet** [comment]
> We could also try and ask the JUnit folks again if we can get a 5.10.z
release with a David's fix in it.

Let's try to kindly ask for that. If they don't want to do it, then we can
reconsider.

**Comment by geoand** [comment]
> Let's try to kindly ask for that

Done, let's see what happens

**Comment by holly-cummins** [comment]
Fingers crossed for the micro release, that's a good thought, @geoand. I think I'm most against option 3. That's partly because of my own bias because it's my extension and my tests, but also because it's a regression. At the moment, we have lots of things that don't work around test classloading, but they've not worked for a long time. So we *know* no one is doing those things, because they couldn't be – they just don't work. Whereas if we broke Pact (which we know people are doing) to enable things people aren't doing, it would be an awkward conversation.

**Comment by gsmet** [comment]
> Whereas if we broke Pact

I agree it's not ideal but by using a non-final release, we are also having a non-null risk of breaking regular JUnit usage and that wouldn't be better.

We need to be a bit cautious.

Let's rediscuss this once we have JUnit's position.

**Comment by holly-cummins** [comment]
> > Whereas if we broke Pact
> 
> I agree it's not ideal but by using a non-final release, we are also having a non-null risk of breaking regular JUnit usage and that wouldn't be better.

Agreed ... I think my personal vote would be for option 2. That puts us back on the old status quo, which was far from ideal, but at least it's not a regression ... and we would have the JBoss Marshaller change good to go as soon as the JUnit fix is in a proper release.

> Let's rediscuss this once we have JUnit's position.

+1

**Comment by edeandrea** [comment]
Not that my vote matters, but I also agree with Holly. I would vote on option 2.

**Comment by geoand** [comment]
I am personally pretty strongly against `2`.

**Comment by edeandrea** [comment]
Why? As Holly explains, that fix is fixing things that have been broken for a long time, so people aren't doing it currently. It has the least chance to introduce any kind of regression until the JUnit fix is released.

**Comment by holly-cummins** [comment]
I've raised https://github.com/quarkusio/quarkus/pull/40880 with the code changes to (temporarily!) back this out, so we're ready to go if we decide to go for one of the "avoid regressing our users" paths and don't want to pick up the JUnit pre-release.

**Comment by holly-cummins** [comment]
I think we can close this as "won't do", to get it off the list of open PRs. #40906 is a superset of this, since we now also need to reintroduce the JBoss serializer (doh!) as well as bumping the JUnit version.

**Comment by holly-cummins** [comment]
(Anyone would think I've got a vendetta against @dmlloyd  .... reverting his changesets, closing his PRs ... )

**Comment by edeandrea** [comment]
> (Anyone would think I've got a vendetta against @dmlloyd .... reverting his changesets, closing his PRs ... )

A time will come at some point in the future when it'll happen to you :D

**Pull request closed without merging**
