### PR TITLE
Rest client jackson docs galder

### PR DESCRIPTION
**Pull request by galderz**
Expanded the note and added a tip to the model sections of rest client guides.

### CODE REVIEW

**Comment by geoand** [comment]
@gsmet WDYT about having such specifics? I am +0

**Comment by gsmet** [comment]
Yeah I don't know. After giving him some thoughts, even the public field note is a bit incorrect. I use private fields with public getters for Jackson and it works well.

So frankly, I'm not sure even the thing you added has any value. `To avoid adding getters, we chose to make the fields public.` would probably be more true.

**Comment by geoand** [comment]
I'll leave it up to you to decide which of the 2 PRs (if any) you want to be merged.

**Comment by maxandersen** [comment]
+1 on merging it; I can say I have to look it up everytime as with panache and other examples I got used to the pattern of not adding accessors for internal only data classes which something fetching data from rest end point often is - at least initially. Thus +1 on bringing awareness.

**Comment by gsmet** [comment]
Personally, I think the suggested wording is misleading and should be adjusted because a lot of Jackson users use private fields + public getters and it's perfectly valid (I would even dare to say more valid, even if more verbose).
Also, I'm really not sure this is the place for such considerations as it's really an implementation detail of the example and we end up entering into deep Jackson considerations.

So please make the wording less misleading, otherwise I'm -1 on this (and for both PRs).

**Comment by galderz** [comment]
> Yeah I don't know. After giving him some thoughts, even the public field note is a bit incorrect. I use private fields with public getters for Jackson and it works well.

That works as well. The note is not meant exhaustive, that's what the reference guide is for. The note is just making the point that the fact that the fields are `public` is not a coincidence. No setters are in the example shown, so I didn't feel the need to talk about something that's not there in the first place.

**Pull request closed without merging**
