### PR TITLE
Add a WebJars Locator extension that duplicates webjars locator behavior from Spring Boot

### PR DESCRIPTION
**Pull request by stuartwdouglas**
…r from Spring Boot.

This reverts commit 7c9face3cd1424387d8db0015c34ea2da095da0e.

This caused CI failures and was reverted, even though the run was green. Reopened here to get more info on the failures.

### CODE REVIEW

**Comment by gsmet** [comment]
FWIW, the issue I had in CI was 404 similar to what we had before all the fixes you made.

**Comment by stuartwdouglas** [comment]
Initial run was green, I have rebased to try capture the problem. @gsmet I don't suppose you have a link to one of the failures?

**Comment by gsmet** [comment]
No I don't. There wasn't much info, just 404s when trying to get the webjar resources.

**Comment by Christopher-Chianelli** [comment]
Here a run for an integration test that failed after the PR was merged and before it was reverted: https://github.com/quarkusio/quarkus/runs/688607249 (commit e007fe5) (also fails for Windows: https://github.com/quarkusio/quarkus/runs/688607008)

**Comment by stuartwdouglas** [comment]
well it seems to be fine now, it has passed with no failures at all 3 times in a row. Looking at the time frame between when it was merged and reverted it looks like it was when CI was completely screwed anyway as quay.io was down?

**Comment by gsmet** [comment]
The errors I had were absolutely not related to the quay.io outage. It was 404s on the resources handled by the webjar locator. That's why I reverted it, I didn't pick a PR randomly :).

We can try merging it again though and see how it goes.

**Comment by stuartwdouglas** [comment]
I am re-running CI again.

**Review by gsmet — APPROVED** [review]
Let's merge and see how it goes.

**Pull request merged**
