### PR TITLE
Introduce async exception mapping to RESTEasy Reactive

### PR DESCRIPTION
**Pull request by geoand**
This is done in order to handle async types (for example when dealing with Quarkus Security)

### CODE REVIEW

**Comment by FroMage** [comment]
I'm not sure about this, especially given that the particular use-case is using Uni, so it looks like it'd be much simpler to allow the exception mapper method to return a `Uni<Response>` and simplify this a lot.

**Comment by FroMage** [comment]
Hum, this is the API version, I guess that's harder for this one. I was thinking of the annotation-based version, I guess.

**Comment by geoand** [comment]
> Hum, this is the API version, I guess that's harder for this one. I was thinking of the annotation-based version, I guess.

Right, this isn't the annotation based one. This is one we really only need internally

**Comment by geoand** [comment]
> I'm not sure about this, especially given that the particular use-case is using Uni, so it looks like it'd be much simpler to allow the exception mapper method to return a `Uni<Response>` and simplify this a lot.

We can definitely improve the annotation to support `Uni`, but that's something different

**Comment by geoand** [comment]
@FroMage do you want me to change something regarding this?

As I am sure you saw, we can't really use `Uni` because `io.quarkus.resteasy.reactive:resteasy-reactive` does not depend on Mutiny.

**Review by FroMage — APPROVED** [review]

**Comment by geoand** [comment]
> @FroMage do you want me to change something regarding this?
> 
> As I am sure you saw, we can't really use `Uni` because `io.quarkus.resteasy.reactive:resteasy-reactive` does not depend on Mutiny.

This is wrong... I'll follow up on another PR adding support for `Uni` for the annotation based approach.

**Comment by FroMage** [comment]
So, to recap our conversation:

- The is the API version, so it makes sense to not tie it to any potential async type such as `Uni`/`CompletionStage` because those are better supported by a later annotation version
- Makes sense to have a `suspend`/`resume` context object
- Sync has a `ResteasyReactiveRequestContext` while async has `AsyncExceptionMapperContext` which are not subtypes or similar, but none of the alternatives we thought of were better:
    - Create a supertype `ExceptionMapperContext` for the sync version: has no method other than getting the `ResteasyReactiveRequestContext` we're replacing
    - Pass both the same type `ExceptionMapperContext`, but the sync version is just nicer to have if it returns the response, having to set it in the context makes this less nice for the sync common case

This is definitely good enough for now.

**Pull request merged**
