### PR TITLE
Dev UI indicate properties set by DevServices

### PR DESCRIPTION
**Pull request by phillip-kruger**
As discussed here https://github.com/quarkusio/quarkus/issues/18597#issuecomment-894255670

This PR adds a way to indicate what configuration is been automatically set by DevServices. 
It also give an easy way to copy this to `application.properties` for `%test` and `%prod`.
This also added a way to narrow the config screen to configuration of a certain extension and added a basic raw editor.

For now this is a draft to get some feedback. 

See this video for a walkthrough: 

https://user-images.githubusercontent.com/6836179/130242716-5a95a967-e3b8-4dd7-900a-da6f6a0469ca.mp4

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Small UI changes as per feedback on Zulip:

image

**Review by stuartwdouglas — APPROVED** [review]
LGTM

**Comment by maxandersen** [comment]
what happens if user have yaml configs ? does that "just work" ?

**Comment by phillip-kruger** [comment]
As I mentioned in the video, I do not think yaml is supported, even in the form editor. I have not tested it, but from the code it does not look like it. I can have a look at that in another PR ?

**Comment by maxandersen** [comment]
makes sense @phillip-kruger - the config viewer supports both so its unfortunate if edit falls apart on that. but sure - separate PR/effort for that makes sense.

**Comment by phillip-kruger** [comment]
@maxandersen - If you say config viewer do you mean the current form editor ? I might be amble to read from `application.yml` , but from the code it seems like the save will always create an `application.properties`. I did not test that to confirm though.
see https://github.com/quarkusio/quarkus/blob/7eb76b4604132302ef80eda0d6bfc310c2ea6964/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/ConfigEditorProcessor.java#L60

**Comment by gsmet** [comment]
Small nitpick: if the button are round, you need a bit of space between them (i.e. between the cross from the form, then the Dev Services button and then the third one). Other than that, nice improvement!

**Comment by phillip-kruger** [comment]
Thanks @gsmet ! I'll update with a space

**Comment by phillip-kruger** [comment]
Peek 2021-08-25 13-04

@gsmet See updated screen ^^^ - Ready for review.

**Review by stuartwdouglas — COMMENTED** [review]
I have a couple of comments:

- Can we automate the config keys in the extension descriptor somehow? This is something that is easy to miss when updating things. 
- What is the use case for copying to a new profile, given that the dev service values are transient and different on each startup?

**Review by FroMage — APPROVED** [review]
Looks like a great feature, and blog-worthy, congrats !

Agree with Stuart that it would be nice to automate, there must be a way to detect which config keys apply to which extensions, I think we do something similar during the Quarkus build to generate the all-config page?

Also agree with Philip that the use-case of knowing what properties are the minimum required by to run outside of dev mode is useful when wanting to deploy on staging/prod for the first time.

This config editor originally seemed like a gimmick but now I'm starting to think that between this and the build system that Stuart is discussing on quarkus-dev, we're on to being able to help new users do things that would just be a pain otherwise. Like, this is much simpler than writing IDE plugins for all existing IDEs for a config editor. I don't think we'll want to go all-in and also provide an integrated web IDE in Quarkus for the rest of the code, but since we can already direct from DEV UI to IDEs easily, I only regret that going from the IDE to the DEV UI isn't something we've solved. Like, instead of coding a config editor for Eclipse, it would be super nice if Eclipse would open the config editor page in the DEV UI instead, if it's running…

**Review by gastaldi — APPROVED** [review]
Works as advertised! Good job! 

One thing I'll suggest: would it be possible to move configuration properties that were specifically set to the top (or display them differently)? For example, I set `quarkus.application.version=1.0` using the application.properties Online Text Editor but I had a hard time trying to find it when it navigated back to the Config Editor screen

**Comment by gsmet** [comment]
I took the time to have a closer look and it's indeed a nice feature and I think we should merge it. One comment though (but not blocking, we can tweak things later), is it so obvious that the button allows to edit the configuration? I wonder if we should make it a bit more obvious.

**Pull request merged**
