### PR TITLE
Qute - scan the templates located in the extension runtime modules

### LINKED ISSUE #21170: Qute - scan the tempates located in the extension runtime modules
### Description

An extensions should be able to provide templates in the runtime module. These templates should be validated and accessible at runtime via injection, etc.

### Implementation ideas

It should be possible to filter out the runtime modules of extensions via `CurateOutcomeBuildItem` and `io.quarkus.maven.dependency.Dependency.isRuntimeExtensionArtifact()` and then make the templates located in the `templates` directory accessible at runtime.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #21170

### CODE REVIEW

**Comment by mkouba** [comment]
Note that this PR does not contain an automated test because I have no idea how to write it without a template in a real extension runtime artifact.

**Comment by mkouba** [comment]
@FroMage I think that you can leverage this feature ;-)

**Comment by mkouba** [comment]
FTR this PR basically follows up on https://github.com/quarkusio/quarkus/pull/21162.

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by mklueh** [comment]
Just for clarification, in my Gradle multi module project templates only work when they are located in the actual application module, but not when they are in sub modules.

Does this merge request solve this as well? Not sure because of the term "extension runtime modules" in the title.

**Comment by mkouba** [comment]
> Edit: found this issue now that is related to my problem. Thanks anyway

Yes, https://github.com/quarkusio/quarkus/pull/21162 should solve your problem. However, the submodules should be marked as application archives (`beans.xml`, jandex index, etc.).

**Comment by mklueh** [comment]
@mkouba are resources of sub modules automatically merged into the artifact when running quarkusBuild? Tried to build my project locally and none of the html files located in META-INF were available in my .jar file. Could be something different as well, but just curious

**Comment by mkouba** [comment]
> are resources of sub modules automatically merged into the artifact when running quarkusBuild?

Merged into which artifact? In general, they should not be merged but loaded fromthe original sub modules jars.

**Comment by mklueh** [comment]
@mkouba for example the .jar archive of the application module. When my mail module provides these templates, will they automatically be in the .jar file when I build my application that includes the mail module?

**Comment by mkouba** [comment]
> @mkouba for example the .jar archive of the application module. When my mail module provides these templates, will they automatically be in the .jar file when I build my application that includes the mail module?

Well, they should be present in the mail module jar but it really depends on how you make the jar and also what the package type is. When you build your quarkus application then by default (`quarkus.package.type=fast-jar`) the module jar is added as a dependency.

**Comment by mklueh** [comment]
@mkouba Got it, yes I'm running the default build, thanks for your help :)

**Comment by mklueh** [comment]
@mkouba first of all, many thanks, it works. However, I tried to override a generic template of my service module (where the mail sending logic is defined) with a concrete customized template of the actual application and I'm running into this issue:

```
Caused by: java.lang.IllegalStateException: Duplicate templates found:

	at io.quarkus.qute.deployment.QuteProcessor.analyzeTemplates(QuteProcessor.java:344)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Is this default behavior intended? Seems overriding is currently impossible.

One could argue that you can define the templates only in the application module and pass the TemplateInstance to a worker class within the submodule, but in my case the class dealing with the templates is a standalone service with it's own REST Api. So in my case, abstraction and reusability is pretty much diminished without ugly workarounds.

**Pull request merged**
