### PR TITLE
Moved `@Rollback` to its own module

### LINKED ISSUE #24500: `@Rollback` annotation is JTA-specific: should be reusable for Hibernate Reactive with Panache
### Description

In https://github.com/quarkusio/quarkus/pull/22202 I screwed up and should have anticipated that we'd need that annotation also for HR.

It's acceptable that we have own own `@ReactiveTransactional` annotation because we don't want the ORM (actually JTA) and HR to walk on each other's feet. But it's not acceptable to ask users to decorate their exceptions with both `@Rollback` (from JTA) and `@ReactiveRollback` (from HR/Panache) because that adds two dependencies "just in case" the exception user uses ORM or HR.

So I vote to move that exception to a new extension `quarkus-transactions` that only has a runtime module containing the single class `@Rollback`, and zero dependency.

Not sure about the name, should it be plural or what? Should we add the annotation some other place, perhaps in an existing module such as `quarkus-hibernate-orm` which is after all, included by `hibernate-reactive`?

@Sanne or @DavideD would that be better/acceptable do you think?

Sorry about the urgency, but I think it'd be nice to figure this one out before we release 2.8, which currently has the new annotation, before it starts being used.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by FroMage**
Fixes #24500

### CODE REVIEW

**Comment by FroMage** [comment]
@gsmet I think it's important to have this in 2.8 before a release, because it moves an annotation (new in 2.8) to a new module/package, and I'd like to move it before it's used.

As I mentioned in #24500 I'm unsure about the module name, but it seems ok to me.

**Comment by gsmet** [comment]
@FroMage I wonder if it's time to create `io.quarkus:quarkus-annotations` with a `io.quarkus.annotations.transaction` package instead.
We had several people complaining over the years that it wasn't possible to use our annotations without dragging the whole of Quarkus and we could move `@RegisterForReflection` there too (and deprecate the old one).

WDYT? /cc @geoand @aloubyansky

**Comment by geoand** [comment]
Yeah, I've heard those complaints a few times.

I'm personally +0

**Comment by aloubyansky** [comment]
I'd prefer each extension providing the relevant annotations.

**Comment by FroMage** [comment]
I'm all for it.

**Comment by gsmet** [comment]
@FroMage in this case, let's go with:
- `quarkus-transaction-annotations` for the artifactId
- `io.quarkus.transaction.annotations` for the package

This way it paves the way for other annotation artifacts.

**Comment by FroMage** [comment]
Are you sure we need to split those annotations? I would have put them all in a single module called `quarkus-annotations` or something, since there's no implementation along with it. Otherwise we'll end up with a lot of modules. OTOH if we don't split them we may give the false impression that they'll do something when they don't because their users/impl/interceptors are somewhere else…

**Comment by gsmet** [comment]
Yeah, I somehow agree and yes it was to alleviate this concern from Alexey for the very reason you mentioned:

> I'd prefer each extension providing the relevant annotations.

@aloubyansky are you entirely against having separate modules for annotations? Or your concern was to make sure we don't expose annotations that wasn't brought properly by an added extension?

By the way, I don't think we should move all of them to separate packages, just the ones that make sense from an architecture point of view.
We had people complaining that they needed to bring all Quarkus in libraries hosting just their domain model for instance.

Maybe I'm overthinking this but from my POV, we have 3 options:

1. have all kind of annotations in a `quarkus-annotations` jar
2. name this module `quarkus-transaction-spi` as I think using a name so generic could bite us later. My concern with this is the name of the package to avoid potential conflicts later (I could see how we could have a `quarkus-transactions` extension at some point).
3. name your module `quarkus-transaction-annotations` and start a proper nomenclature for them

I could go with either 1 or 3. 2 doesn't look that appealing to me.

**Comment by aloubyansky** [comment]
I am not entirely against the idea, I'll leave to you to decide. In general though I would not like to have API and classes on the classpath that aren't relevant to a given app, which also fits one of the goals of Quarkus. If there is a good enough reason to gather all the annotations in one JAR then ok, I suppose.

**Comment by gsmet** [comment]
@FroMage I think we will go with:
- `quarkus-transaction-annotations` for the artifactId
- `io.quarkus.transaction.annotations` for the package

Do you have the time to adjust this PR before Tuesday evening (that will be today for you when you read that I suppose)?

If not, I'll do it.

**Comment by FroMage** [comment]
I should be able to do it now.

**Comment by FroMage** [comment]
Done, in theory.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
