### PR TITLE
Set the Agroal ExceptionSorter to detect which JDBC exception can be recovered from

### PR DESCRIPTION
**Pull request by yrodiere**
As requested by @barreiro . Addresses [this comment](https://github.com/quarkusio/quarkus/issues/7275#issuecomment-588277895), but I think we need more in order to close that ticket.

Since it's a bit hard to artificially trigger fatal JDBC exceptions, I ended up trusting Agroal to do the right thing, and only testing that we configure Agroal correctly.

~The one thing I'm not sure of is what to do for Derby and H2. There is no built-in `ExceptionSorter` for those, so we have to rely on defaults. Currently I'm logging a warning because of that, but there is nothing users can do about it... maybe I should strip the warning?~ => I stripped the warning.

### CODE REVIEW

**Comment by gsmet** [comment]
> Currently I'm logging a warning because of that, but there is nothing users can do about it... maybe I should strip the warning?

Yes please.

**Comment by yrodiere** [comment]
> > Currently I'm logging a warning because of that, but there is nothing users can do about it... maybe I should strip the warning?
> 
> Yes please.

Done.

**Comment by yrodiere** [comment]
I'm having trouble getting tests to work correctly: I added assertions to check no warnings are issued, but it turns out there are many warnings already (JDK8, TestContainers, JDBC drivers, ...). Worse, they mostly depend on the environment, so I don't see them locally but they do happen on CI, breaking the tests.

I changed the tests to fail only if we find a warning that contains the word "Agroal". Not great, but it should work... let's find out.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Let's wait for @barreiro to comment on this.

**Review by barreiro — APPROVED** [review]

**Comment by barreiro** [comment]
Looks good. There are no exception sorters for Derby and H2 as we don't consider them to be 'production' databases. No need for a warning in that case.

**Comment by yrodiere** [comment]
Merged, thanks!

**Pull request merged**
