### PR TITLE
Fix broken Kubernetes extension

### PR DESCRIPTION
**Pull request by geoand**
The generated Kubernetes resources need to end up in the file system, not the produced jar.
Previously they were obtained via the `wiring-classes`. 
Now we explicitly make the available from the file system.

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel can you try this one out please?

**Comment by iocanel** [comment]
> @iocanel can you try this one out please?

I did and it works like a charm!

**Review by gsmet — APPROVED** [review]
Looks good to me and I see @iocanel validated it works so let's merge it :).

**Comment by geoand** [comment]
Thanks folks!

**Pull request merged**
