### PR TITLE
2.11: switch codestart testing API from io.quarkus.maven.Artifact* to io.quarkus.maven.dependency.Artifact*

### PR DESCRIPTION
**Pull request by aloubyansky**
`io.quarkus.maven.Artifact*` API was removed in the `main` (to be 2.12) branch, which may break some codestart tests in extension projects that are based on Quarkus 2.11 running CI against the Quarkus `main` branch. This PR updates the codestart testing API to enable passing those CIs.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@ia3andy can you have a look at this one today? I will probably release a new 2.11 tomorrow.

**Review by ia3andy — DISMISSED** [review]
This is also important for the future CLI 2.11 and the Maven plugin 2.11

**Review by ia3andy — CHANGES_REQUESTED** [review]
I need to check if that doesn't actually break the CLI/Maven plugin

**Review by ia3andy — APPROVED** [review]
Good to go

**Pull request merged**
