### PR TITLE
Expose the shared attribute in the reactive data source configuration

### PR DESCRIPTION
**Pull request by cescoffier**
This attribute was introduced in Vert.x 4.2.2.

### CODE REVIEW

**Comment by geoand** [comment]
This needs a formatting change

**Review by gsmet — APPROVED** [review]
I rebased and adjusted a small thing in the javadoc. Otherwise, it looks good to go!

**Comment by Sanne** [comment]
I can't say I understand how to use this... is there a better explanation in the vertx docs?

I found this one but I'm not sure how this translates to Quarkus users as it seems very specific to vert.x:
 -https://vertx.io/docs/vertx-pg-client/java/#_pool_sharing

**Comment by gsmet** [comment]
@cescoffier could you have a look at @Sanne 's question?

**Comment by cescoffier** [comment]
@Sanne it allows sharing the connection pool. It can be useful when you do not use Hibernate Reactive :-). 
Now, it's a pretty advanced use case.

**Comment by Sanne** [comment]
Sorry I might be slow (and I'm away) but I still don't understand the implications a Quarkus user should understand.

"shared" across what? What kind of usage pattern would require this to be set (or not)? The documentation I found is very specific for a Vert.x application - I'm not sure how that translates to a Quarkus application and we need to document that in a way which a typical Quarkus user can understand.

In particular I'd want to explore if we actually need a property, or if something should be enforced or inferred.

**Comment by gavinking** [comment]
@cescoffier I don't understand this concept either:

>  share the pool among datasources.

You mean, something like: connections to different databases might go into one big pool? Or something else?

**Comment by gavinking** [comment]
Whatever, the documentation should read something like:

```
/**
 * True when the database connection pool is shared among datasources.
 * 
 * If, false, the default, there is a separate connection pool for each named datasource.
 * Otherwise, if true, there is a single connection pool holding every pooled connection 
 * from any datasource, with a single FIFO eviction queue and blah blah blah blah blah.
 */
```

Where blah blah blah blah blah explains all the implications of enabling this pretty unintuitive setting.

**Pull request merged**
