### PR TITLE
Remove OpenTracing

### PR DESCRIPTION
**Pull request by radcortez**
~~Missing the jdbc tracing, that was only deprecated in https://github.com/quarkusio/quarkus/pull/43416~~

Remove remaining references of OpenTracing. See https://github.com/quarkusio/quarkus/pull/43542/

### CODE REVIEW

**Comment by geoand** [comment]
This needs a rebase

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Let's make sure we add a note in the migration guide for 3.17.

**Comment by radcortez** [comment]
> Let's make sure we add a note in the migration guide for 3.17.

Ok!

**Comment by radcortez** [comment]
Added this: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.17#opentracing

**Pull request merged**
