### PR TITLE
Upgrade of kogito to 0.6.0 and updated jandex proto generator

### PR DESCRIPTION
**Pull request by mswiderski**
…ator to allow exclusion of static and transient, support simple types for collections

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
@mswiderski is there any exciting new features in this version? Just to know if I make it a `noteworthy-feature` or not.

Thanks!

**Comment by mswiderski** [comment]
@gsmet there are quite many new features of kogito coming with this version like jobs service (built on top of quarkus as completely reactive service to track time based activities scheduled by processes). Domain specific filters via GraphQL ... again built on top of quarkus... and many many more. Shall I prepare something for the announcement or?

**Comment by gsmet** [comment]
@mswiderski yes, if you could prepare a short paragraph with a few links, that would be perfect!

**Comment by mswiderski** [comment]
@gsmet here it is

Kogito has been upgraded to 0.6.0 version - comes with features to handle time based activities that can be externalized to dedicated service (jobs service). It fully utilizes quarkus and reactive non blocking api to effectively deal with scheduled jobs (using vert.x timers). In addition, GraphQL interface of data index service has been enhanced to allow typed searches over domain information for maximum flexibility to deal with data produced by Kogito runtime services (processes). If you want to learn more about jobs service and data index service visit Kogito [wiki pages](https://github.com/kiegroup/kogito-runtimes/wiki)

**Comment by gsmet** [comment]
Thanks @mswiderski !

**Pull request merged**
