### PR TITLE
Namespace optaplanner's kogito version to avoid clash

### PR DESCRIPTION
**Pull request by ge0ffrey**
Also removes kogito removal leftovers
Also updates kogito to 0.8.1 and removes a workaround with substitution

### CODE REVIEW

**Comment by ge0ffrey** [comment]
@mariofusco @evacchi Can you review this PR too please?

**Review by evacchi — APPROVED** [review]
LGTM

**Review by mariofusco — APPROVED** [review]

**Comment by ge0ffrey** [comment]
@geoand Ready for your review (Mario and Edoardo approved)

**Comment by geoand** [comment]
Will the version mismatch situation be rectified in time for `1.4`?

**Comment by ge0ffrey** [comment]
> Will the version mismatch situation be rectified in time for `1.4`?

Unlikely for 1.4. I expect it to take longer.
OptaPlanner is facing a catch 22 situation: either uses Drools 7, or its fork Kogito-Drools 1. The former doesn't support graal. The latter is business wise unacceptable as long as Kogito-Drools 1.0 isn't released - formerly replacing Drools 7 - at which point OptaPlanner 8.0 will be branched and depend on Kogito-Drools and this issue will be resolved.
Suffice it to say... it's difficult.

**Comment by evacchi** [comment]
@ge0ffrey there is a conflict now

**Comment by gsmet** [comment]
I fixed the conflict and force pushed.

**Review by gsmet — APPROVED** [review]

**Comment by ge0ffrey** [comment]
@gsmet Good to merge I think.
Although the situation after this PR is far from perfect, it's a workable temporary situation.

**Pull request merged**
