### PR TITLE
Improve IDE detection

### LINKED ISSUE #18676: Clicking on application class in stacktrace causes 500 in dev ui
### Describe the bug

I use idea for development.

Stack traces of the application are visible in the dev ui. Application classes are clickable, and should open the file in the ide. (see #15761)

This does not work however in my testing. The http access log simply shows a 500 status code.

### Expected behavior

File is opened in idea. If no ide is found, an actionable error message should be shown.

### Actual behavior

The http access logs show a status code 500. I was not able to get an stacktrace for this.
```
2021-07-14 09:54:36,646 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-11) 127.0.0.1 - - 14/Jul/2021:09:54:36 +0200 "POST /q/dev/io.quarkus.quarkus-vertx-http/openInIDE HTTP/1.1" 500 - 
Host: localhost:8080
Connection: keep-alive
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
Accept: */*
X-Requested-With: XMLHttpRequest
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryq6xHXmAFsFB0AMhL
Origin: http://localhost:8080
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8080/q/dev/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
content-length: 495
x-quarkus-hot-deployment-done: true
```

### How to Reproduce?

Reproducer:

1. mvn quarkus:dev
2. open dev ui, and open the log
3. in a seperate tab, go to localhost:8080/hello
4. switch to the dev ui log
5. click on the SomeResource application class

### Output of `uname -a` or `ver`

MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

### Output of `java -version`

openjdk version "11.0.7" 2020-04-14 LTS OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS) OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\eclipse\tools\apache-maven\bin.. Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\java\11 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
* Test more possible cases for Windows
* Support detection for multi-module projects

Fixes: #18676

### CODE REVIEW

**Comment by Sanne** [comment]
This stuff looks really brittle. Is there any way we could think of having integration tests for such cases? Anyone from the IDE teams might be able to help @maxandersen ?

(not meant to be a blocking remark on this particular PR, just a general thought)

**Review by Sanne — APPROVED** [review]
Approved based on trust - I have no idea :)

**Comment by geoand** [comment]
Yeah, I completely agree

**Comment by Postremus** [comment]
@geoand FTR, the IdeProcessor is also not detecting idea when using fedora as os. I am investigating.

**Comment by geoand** [comment]
> @geoand FTR, the IdeProcessor is also not detecting idea when using fedora as os. I am investigating.

I'm looking forward to what you find :)

**Comment by maxandersen** [comment]
> This stuff looks really brittle. Is there any way we could think of having integration tests for such cases? Anyone from the IDE teams might be able to help @maxandersen ?

its brittle but thats the business of trying to detect this - users can always override. 

about integration tests this is probably something QE could add to their bigger setup tests - not sure IDE team can help here.

**Comment by maxandersen** [comment]
to QE: could you have tests with various IDE's on various platforms that could test these are detected ?

**Comment by rsvoboda** [comment]
Hi Max, sure we can. New automation and target environment preparation will be needed. For this effort, a new Feature Request needs to be created to define requirements (minimal set and the ideal set) and to prioritize it comparing to the other product requirements.

**Comment by Postremus** [comment]
@geoand I commited my fixes to https://github.com/Postremus/quarkus/commits/%2318676. How do we proceed from here, should I simply open a new PR?

**Comment by geoand** [comment]
Cool.

Please open a new PR (I will close this one)

**Pull request closed without merging**
