### PR TITLE
ignore newlines after parameter declaration

### LINKED ISSUE #8753: Qute: remove whitespace around type declarations
If I declare parameter types in my template:

```txt
{@java.lang.String name}
{@java.lang.String foo}

Here is my email
```

Then the output is `\n\n\nHere is my email` because whitespace isn't stripped between the type declarations and the first content. Note that this is mostly an issue for email and plaintext, but still.

Now, perhaps it's important to allow whitespace before the first content, but even in this case, we should strip whitespace before/between type declarations and the last newline after it?

### PR DESCRIPTION
**Pull request by adrianfiedler**
fixes #8753

### CODE REVIEW

**Comment by gsmet** [comment]
@mkouba could you review that one?

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/issues/8753#issuecomment-620639688

If there are no objections I'm going to close this PR for now.

**Comment by Sanne** [comment]
@mkouba just checking on the status.. did you mean to close it?

**Comment by mkouba** [comment]
@Sanne Hm, I thought I closed this one... Anyways, it's superseded by https://github.com/quarkusio/quarkus/pull/10305.

**Pull request closed without merging**
