### PR TITLE
Ensure that quarkus-kubernetes does not pollute the runtime classpath

### LINKED ISSUE #15705: quarkus-kubernetes / quarkus-openshift extension pulls in additional 10+ MB of dependencies
quarkus-kubernetes / quarkus-openshift extension pulls in additional 10+ MB of dependencies
Affected version: Quarkus master

Quarkus 1.12.2.Final
```
du -cskh target/quarkus-app/
 11M	target/quarkus-app/
 11M	total
find target/quarkus-app/ | grep jar$ | wc -l
      70
```

Quarkus master
```
du -cskh target/quarkus-app/
 23M	target/quarkus-app/
 23M	total
find target/quarkus-app/ | grep jar$ | wc -l
     102
```

Reproducer:
```
mvn io.quarkus:quarkus-maven-plugin:1.12.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello" -Dextensions="quarkus-kubernetes"
cd getting-started

mvn clean package -DskipTests
du -cskh target/quarkus-app/
find target/quarkus-app/ | grep jar$ | wc -l

mvn clean package -DskipTests -Dquarkus.platform.artifact-id=quarkus-bom \
  -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus-plugin.version=999-SNAPSHOT
du -cskh target/quarkus-app/
find target/quarkus-app/ | grep jar$ | wc -l
```

A lot of new io.fabric8 deps appear in dependency tree and `target/quarkus-app/` directory:
```
[INFO] |  |  \- io.fabric8:kubernetes-client:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-core:jar:5.1.1:compile
[INFO] |  |     |  \- io.fabric8:kubernetes-model-common:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-rbac:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-admissionregistration:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-apps:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-autoscaling:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-apiextensions:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-batch:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-certificates:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-coordination:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-discovery:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-events:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-extensions:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-networking:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-metrics:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-policy:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-scheduling:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-storageclass:jar:5.1.1:compile
[INFO] |  |     +- io.fabric8:kubernetes-model-node:jar:5.1.1:compile
[INFO] |  |     +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |     |  \- com.squareup.okio:okio:jar:1.17.2:compile
[INFO] |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.14.9:compile
[INFO] |  |     +- io.fabric8:zjsonpatch:jar:0.3.0:compile
[INFO] |  |     \- com.github.mifmif:generex:jar:1.0.2:compile
[INFO] |  |        \- dk.brics.automaton:automaton:jar:1.11-8:compile
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #15705

### CODE REVIEW

**Comment by aloubyansky** [comment]
Just to clarify, `quarkus-kubernetes-client` will be the only one providing `io.fabrik8:kubernetes-client`, the rest of the extensions depending on the `quarkus-kubernetes-client-internal` will not. Is this how it is intended to be?

**Comment by geoand** [comment]
> Just to clarify, `quarkus-kubernetes-client` will be the only one providing `io.fabrik8:kubernetes-client`, the rest of the extensions depending on the `quarkus-kubernetes-client-internal` will not. Is this how it is intended to be?

Yes, exactly

**Review by aloubyansky — APPROVED** [review]

**Comment by geoand** [comment]
Actually, I still need to try something

**Comment by geoand** [comment]
Tried what I had in mind and it works just fine

**Comment by geoand** [comment]
Some tests are failing :(

**Comment by aloubyansky** [comment]
I guess it's a compile dependency which isn't then provided at runtime. Not isolated enough.

**Comment by aloubyansky** [comment]
Because it appears as a transitive dependency. Only direct `provided` dependencies (of the app or test) are supposed to be collected. If it has to be present at build time then it should just be a build-time (compile) dependency. Build time-only dependencies should be used with caution though, to make sure they are actually not required at runtime.

**Comment by geoand** [comment]
I am sure I am missing something from what you described, but I don't really know how to solve this case TBH...

If there is some way I can include `io.fabric8:kubernetes-client` in the `quarkus-kubernetes-client-deployment-internal` (therefore build-time) module, then everything should be OK, as the client will be present at build time when it's needed. At runtime it won't be present, unless the `quarkus-kubernetes-client` extensions brings it in.

**Comment by aloubyansky** [comment]
You haven't actually added that dependency to the `quarkus-kubernetes-client-deployment-internal`. So, if i got you right, just add a direct compile dependency on `io.fabric8:kubernetes-client` in the `quarkus-kubernetes-client-deployment-internal`.

**Comment by geoand** [comment]
> You haven't actually added that dependency to the `quarkus-kubernetes-client-deployment-internal`. So, if i got you right, just add a direct compile dependency on `io.fabric8:kubernetes-client` in the `quarkus-kubernetes-client-deployment-internal`.

That is what I am trying locally and ufortunately I am seeing the same error.

**Comment by aloubyansky** [comment]
I'll have a look into this a bit later today.

**Comment by geoand** [comment]
I pushed what I am doing locally as well.

**Comment by geoand** [comment]
> I'll have a look into this a bit later today.

I'm looking as well to try and understand what is going on.

**Comment by aloubyansky** [comment]
Is farbik8 client necessary to build the internal runtime module?

**Comment by geoand** [comment]
> Is farbik8 client necessary to build the internal runtime module?

Yes, unfortunately it is

**Comment by geoand** [comment]
Looking into it a little more closely, it seems that this is caused by the fact that `io.quarkus.kubernetes.client.runtime.KubernetesClientUtils` is being loaded by the System ClassLoader.

**Comment by aloubyansky** [comment]
Doesn't it mean that the fabrik8 client is actually required at runtime? At least from the classloading perspective?

**Comment by geoand** [comment]
> Doesn't it mean that the fabrik8 client is actually required at runtime? At least from the classloading perspective?

From a classloader perspective, yes.

However the problem is this:

When I simple do `mvn package` on a project tha contains the `quarkus-kubernetes`, everything works as expected (`io.quarkus.kubernetes.client.runtime.KubernetesClientUtils` is loaded from the augmentation ClassLoader.)
The problem I mentioned above only seems to happen with the `QuarkusProdModeTest`, so I am really not sure what to make of it...

**Comment by geoand** [comment]
There is probably a horrible hack I can do  to make it work, let me check

**Comment by geoand** [comment]
> There is probably a horrible hack I can do to make it work, let me check

It didn't work.

I am really baffled by this because the only place this fails is in the `QuarkusProdModeTest`...

**Comment by geoand** [comment]
> I am really baffled by this because the only place this fails is in the `QuarkusProdModeTest`...

I think I know why this is happening..

**Comment by geoand** [comment]
It should now be OK

**Comment by geoand** [comment]
I also added a test to make sure this does not happen again

**Comment by aloubyansky** [comment]
Great @geoand, thanks!

**Comment by geoand** [comment]
👍🏼

**Pull request merged**
