### PR TITLE
Liquibase - Fix NPE with createView

### LINKED ISSUE #14740: Liquibase native compilation broken since 1.11.1.Final: NullPointerException in LiquibaseProcessor#nativeImageConfiguration
**Describe the bug**
Since the version 1.11.1.Final I cannot compile native with liquibase. It was working fine in 1.11.0.Final. I suspect the issue started with #14500 (because of the stacktrace). This only happen if I have a `<createView` because if I comment it out, the build is passing.

/cc @famod (since you're the author of #14500) maybe you have some insights

**Expected behavior**
I can compile native with liquibase with views.

**Actual behavior**
mvn native compilation exit in error.

Command: 
```
mvn clean package -Pnative
```

Stack trace:
```
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.586 s
[INFO] Finished at: 2021-02-01T12:48:24+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.1.Final:build (default) on project sdm-schema: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.liquibase.deployment.LiquibaseProcessor#nativeImageConfiguration threw an exception: java.lang.NullPointerException
[ERROR] 	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
[ERROR] 	at java.base/java.util.Optional.<init>(Optional.java:107)
[ERROR] 	at java.base/java.util.Optional.of(Optional.java:120)
[ERROR] 	at io.quarkus.liquibase.deployment.LiquibaseProcessor.extractChangeFile(LiquibaseProcessor.java:345)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[ERROR] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[ERROR] 	at io.quarkus.liquibase.deployment.LiquibaseProcessor.findAllChangeLogFiles(LiquibaseProcessor.java:316)
[ERROR] 	at io.quarkus.liquibase.deployment.LiquibaseProcessor.getChangeLogs(LiquibaseProcessor.java:276)
[ERROR] 	at io.quarkus.liquibase.deployment.LiquibaseProcessor.nativeImageConfiguration(LiquibaseProcessor.java:120)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**To Reproduce**

Have a liquibase change with a view, example:
```xml
    <changeSet id="view_last_schema" author="gc">
        <createView viewName="v_last_schema">
            SELECT s.*
            FROM (
                SELECT data_offer_state_uuid, schema_encoding, schema_source, MAX(created) as created
                FROM t_schema
                GROUP by data_offer_state_uuid, schema_encoding, schema_source
                ) as o
            INNER JOIN t_schema s USING(schema_encoding, schema_source, created);
        </createView>
    </changeSet>
```

**Configuration**
```yml
quarkus:
  liquibase:
    migrate-at-start: true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux gaetan-desktop 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`:  
 ```
 openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```
 - Quarkus version or git rev: `1.11.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
 Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: GraalVM Community, runtime: /home/gaetan/.sdkman/candidates/java/21.0.0.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-64-generic", arch: "amd64", family: "unix"
```

### PR DESCRIPTION
**Pull request by gaetancollaud**
Closes #14740

### CODE REVIEW

**Comment by gsmet** [comment]
You have your error running the tests with Maven or from the IDE?

**Comment by gaetancollaud** [comment]
> You have your error running the tests with Maven or from the IDE?

both.

Same error twice

**Comment by gaetancollaud** [comment]
Nevermind, it seems that h2:mem uses the port 8082 And I had a service running on this port, my bad...

**Review by gsmet — APPROVED** [review]
Looks good to me. I'll let you promote it once it's all good for you.

**Comment by famod** [comment]
Thanks @gaetancollaud!
The icing on the cake would be a native test which verifies that the changes from #14500 actually do what they are supposed to.
But this can of course also go into another PR.

**Comment by gsmet** [comment]
And merged! Thanks @gaetancollaud !

**Pull request merged**
