### PR TITLE
ArC - detect local, inner classes annotated with a scope annotation

### PR DESCRIPTION
**Pull request by mkouba**
- and fail the build eventually

I was bitten by this many times, esp. when writing tests...

### CODE REVIEW

**Comment by mkouba** [comment]
In theory, we could detect the bean defining annotations instead... but I think that this is a good start ;-).

**Review by Ladicek — APPROVED** [review]
LGTM

**Comment by Ladicek** [comment]
Also, are producer methods/fields on inner classes ignored as well?

**Comment by mkouba** [comment]
> Also, are producer methods/fields on inner classes ignored as well?

That's a good point. They are, they must be ;-). I think we could add detection for `@Observes` and `@Produces` because right now, if you use one these annotations the scope annotation is not required and `@Dependent` is used instead.

**Comment by Ladicek** [comment]
I figured we might do some shortcuts there :-) +1 for also detecting observer methods.

**Review by manovotn — APPROVED** [review]
LGTM

**Review by Ladicek — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

**Pull request merged**
