### PR TITLE
The smallrye reactive streams operators project is in maintenance mode.

### PR DESCRIPTION
**Pull request by cescoffier**
This PR removes the dependency from dependabot, rephrase a paragraph in context propagation, and add deprecated to the project name.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by machi1990** [comment]
Do we have a `deprecated` flag for the quarkus-extension.yaml file like, that code.quarkus.io understand? 

What I am thinking is to be able to say that a listed extension is in maintenance / deprecated mode display deprecated. 

For example, adding the said flag in https://github.com/quarkusio/quarkus/blob/master/extensions/reactive-streams-operators/smallrye-reactive-streams-operators/runtime/src/main/resources/META-INF/quarkus-extension.yaml and it will be automatically picked by code.quarkus.io. Much like https://github.com/quarkusio/quarkus/pull/10781/files#diff-4a26a0a61868afa383faaeec1557f0f2R14 but more visible to developers looking to start new projects too. (Alternative to that will be to unlist the extension)

**Comment by cescoffier** [comment]
@machi1990 I don't know if we can set the `status` to `deprecated`. @maxandersen by any chance, do you know?

**Comment by gsmet** [comment]
TBH, if it shouldn't be used, I would make it unlisted.

**Comment by gsmet** [comment]
That being said, a deprecated status would be useful. But for this particular extension, I think unlisting it would be OK.

**Comment by cescoffier** [comment]
Yes, unlisted would make a lot of sense. Can we just remove it from the list or is there anything to be done somewhere else?

**Comment by gastaldi** [comment]
@cescoffier you can add `unlisted: true` to the `metadata` in the extension's quarkus-extension.yaml or here:https://github.com/quarkusio/quarkus-platform/blob/master/bom/runtime/src/main/resources/extensions-overrides.json#L133 

I'd prefer the former 😉

**Comment by cescoffier** [comment]
Thanks @gastaldi, I just added `unlisted: true` to the descriptor.

**Review by machi1990 — APPROVED** [review]

**Comment by cescoffier** [comment]
@gsmet is this ok for you?

**Review by gsmet — APPROVED** [review]

**Pull request merged**
