### PR TITLE
Rename independent-projects to other

### PR DESCRIPTION
**Pull request by ia3andy**
If the CI passes, this might be less impacting than using `longpath`.

Moving this out of Quarkus core might also be a good option.

Try another fix for https://github.com/quarkusio/quarkus/issues/26807

cc @Sanne @gastaldi @aloubyansky @gsmet @maxandersen

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
This is a band-aid. Really, let's avoid doing this. Especially since it's going to make backporting harder for me and it will solve the issue until you have a path a bit longer.
It will also break the release scripts, the Jakarta migration...

And it's definitely not a reason good enough to move these projects out of the tree. If we do it, we must really think about the advantages and the drawbacks of doing it.

Next time let's talk about this before doing it.

**Comment by ia3andy** [comment]
> This is a band-aid. Really, let's avoid doing this. Especially since it's going to make backporting harder for me and it will solve the issue until you have a path a bit longer. It will also break the release scripts, the Jakarta migration...
> 
> And it's definitely not a reason good enough to move these projects out of the tree. If we do it, we must really think about the advantages and the drawbacks of doing it.
> 
> Next time let's talk about this before doing it.

I agree.

I made this PR as a way out to be sure people understand and agree on using `longpath` for Windows.

We can close this PR as soon as everyone agree on this.

**Review by maxandersen — CHANGES_REQUESTED** [review]
this does not solve the issue. -1.

**Review by gastaldi — CHANGES_REQUESTED** [review]
I agree with @gsmet and @maxandersen that this is a band-aid and won't fix the real problem, it could happen with any other module

**Comment by ia3andy** [comment]
> I agree with @gsmet and @maxandersen that this is a band-aid and won't fix the real problem, it could happen with any other module

So you also agree with me then 😁

**Comment by gastaldi** [comment]
Moving the independent projects out of core may be another topic that would be better discussed over the mailing list 😉

**Pull request closed without merging**
