### PR TITLE
Add redis host provider documentation

### LINKED ISSUE #23787: Document redis host provider or give an example
### Describe the bug

At the moment the redis guide is missing an example of the host provider feature

### Expected behavior

The feature should be documented

### Actual behavior

No documentation exists yet. We only have an integration test.

### Additional information

The documentation can be added based on https://github.com/quarkusio/quarkus/issues/16284#issuecomment-1042898488. The documentation can be go just before the https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/redis.adoc#creating-clients-programmatically section.

### PR DESCRIPTION
**Pull request by VanillaSpoon**
* Fix #23787

### CODE REVIEW

**Comment by VanillaSpoon** [comment]
* Fix #23787

**Review by machi1990 — CHANGES_REQUESTED** [review]
This lgtm, thanks for the quick turn around and the PR.

I've added some small suggestions.

**Comment by machi1990** [comment]
@VanillaSpoon thanks for taking a look on the feedback. Can you squash the 2 commits into one? It should be good to merge once that is done.

**Comment by VanillaSpoon** [comment]
Thanks for the feedback @machi1990. I've squashed the commits.

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
Congrats on your first PR. Let me know if you'll be interested on moving on to https://github.com/quarkusio/quarkus-quickstarts/issues/1060

**Comment by VanillaSpoon** [comment]
Thanks @machi1990.
Yea, Im happy to move to it. I'll just need a brief on where in redis-quickstart and how you would like it implemented :)

**Pull request merged**
