### PR TITLE
(docs): Update Knative Quickstart guide

### LINKED ISSUE #1698: Update Knative Quickstart guide
Update Knative Quickstart docs update for quarkusio/quarkus-quickstarts#112

### PR DESCRIPTION
**Pull request by kameshsampath**
Update dKnative Quickstart guide for  quarkusio/quarkus-quickstarts#112

Fixes:  #1698

### CODE REVIEW

**Comment by kameshsampath** [comment]
FYI: @gsmet  @cescoffier - sorry for opening the issue in other site repo. moved it here and closed the other one.

**Review by starksm64 — COMMENTED** [review]
I tried running through the guide. I went to https://kubernetes.io/docs/tasks/tools/install-minikube/ and followed the steps to install minikube and dependcies on an osx box using brew. On the first command minikube crashed:

```bash
Scotts-iMacPro:docs starksm$ eval $(minikube docker-env)

💣  Error getting host: Machine does not exist for api.Exists(minikube)

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

Scotts-iMacPro:docs starksm$ minikube version
minikube version: v1.0.0
```

**Comment by starksm64** [comment]
I guess I needed to have started minikube before the `eval $(minikube docker-env)` command.

**Comment by kameshsampath** [comment]
oh yeah ! you are right

**Comment by starksm64** [comment]
It says to run a maven command, but I don't see one in the merged getting-started-knative. If I do the step after docker-env eval, I don't have a Dockerfile so it is failing:

```bash
Scotts-iMacPro:docs starksm$ docker build -t starksm64/getting-started-knative . 
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/starksm/Dev/JBoss/Protean/starksm64-quarkus/docs/Dockerfile: no such file or directory
```
so either I'm supposed to using the solution or there is a maven command to setup a new project that is missing.

**Comment by kameshsampath** [comment]
@starksm64  - for all the commands in this to work well, you might need the PR https://github.com/quarkusio/quarkus-quickstarts/pull/117 merged as that uses the latest quarkus maven images

**Comment by starksm64** [comment]
Ok, but the getting-started-knative-guide.html seems to be missing something. Here is what I see in it:
mvn-cmd

there is a reference to a maven command, but I don't see one.

**Comment by kameshsampath** [comment]
@starksm64 you dont need the maven command explicitly, the build takes care of it. Also you cant build from macbook directly for the old get started. the new PR which I mentioned ( needs to be merged) can allow you to do the build directly from mac

**Comment by starksm64** [comment]
Ok, I did try the new quickstart PR branch and left a comment on that about not being able to get past the first `docker build -t {username}/getting-started-knative .` step as the image build failed with a 137 status code.

**Comment by rsvoboda** [comment]
Hi. This PR and knative guide are mentioning docker.io. Q is focused on quay.io.
Please update the PR and examples to use quay.io registry.

```
git grep docker.io
docs/src/main/asciidoc/getting-started-knative-guide.adoc:| https://index.docker.io/v1/
docs/src/main/asciidoc/getting-started-knative-guide.adoc:| docker.io/demo/quarkus-knative-quickstart
docs/src/main/asciidoc/getting-started-knative-guide.adoc:    -Dapp.container.image='docker.io/demo/getting-started-knative' \
extensions/kubernetes/deployment/src/main/java/io/quarkus/kubernetes/deployment/DockerConfig.java:    public String registry = "docker.io";
```

**Comment by kameshsampath** [comment]
@rsvoboda  - i would also be happy to use quay.io but then for the knative i have to use docker or gcr repos which are `v2_2` enabled. Quay is not set default `v2_2` for all the registered users. Once I see the quay release happening we can move to use quay.io

**Comment by dmlloyd** [comment]
Any updates on this?  @starksm64 ?

**Comment by starksm64** [comment]
I'll go through it again today to see the current status. Last time I tried it was failing with remote repository issues.

**Comment by cescoffier** [comment]
Any update on this? @kameshsampath @starksm64

**Comment by kameshsampath** [comment]
@cescoffier  am waiting on @starksm64  for any update on the issues he was facing.  But this gives me a chance to update it for `0.16.0` and push again. WDYT?

**Comment by cescoffier** [comment]
@kameshsampath yes, please update.

**Comment by kameshsampath** [comment]
@cescoffier  an effective close to this will be merging the PRS:

- https://github.com/quarkusio/quarkus-images/pull/6
- https://github.com/quarkusio/quarkus-quickstarts/pull/117

I have updated and rebased all the PRs for 0.16.0 and graal rc16

**Comment by emmanuelbernard** [comment]
@cescoffier @kameshsampath so 0.18 is about to land with GraalVM 19.0.2 support. Maybe a good time to refresh that PR in that occasion right after the release.

**Comment by dmlloyd** [comment]
Now that 0.18 (and 0.19) have been released, do we want to update this further?

/cc @cescoffier @kameshsampath

**Comment by cescoffier** [comment]
@kameshsampath can you have a look?

**Comment by kameshsampath** [comment]
@cescoffier  - I will mid of next week

**Comment by kameshsampath** [comment]
@cescoffier  - I have updated the doc, dont know why there is conflict I tried to rebase to the latest quickstarts.

I have also updated https://github.com/quarkusio/quarkus-quickstarts/pull/117 the sources. Please merge them together.

Let me know if some action is required.

**Comment by cescoffier** [comment]
Closing due to inactivity.

**Comment by kameshsampath** [comment]
rather than inactivity there was no response

**Pull request closed without merging**
