### PR TITLE
Use java.util.Locale to parse the languages from the Accept-Language header

### LINKED ISSUE #36227: Accept-Language header not parsed correctly for language subtags, variants, extension and private subtags
### Describe the bug

When using an Accept-Language header for HTTP requests that contains more than simple language or language-country forms, the parsed `Locale` does not correctly reflect the given language tag as defined in https://www.rfc-editor.org/rfc/rfc9110#section-12.5.4.

Other examples of complex tags can be found in https://www.w3.org/International/articles/language-tags/.

### Expected behavior

Language tags are parsed into a Locale that correctly reflects the given data;  examples (not sure if `zh-yue` being turned into `yue` or `ar-afb` being turned into `afb` are correct, but that's what `java.util.Locale` turns it into):

```
Accept-Language: en
         Parsed: en

Accept-Language: ast
         Parsed: ast

Accept-Language: zh-yue
         Parsed: yue

Accept-Language: ar-afb
         Parsed: afb

Accept-Language: zh-Hans
         Parsed: zh-Hans

Accept-Language: az-Latn
         Parsed: az-Latn

Accept-Language: en-GB
         Parsed: en-GB

Accept-Language: es-005
         Parsed: es-005

Accept-Language: zh-Hant-HK
         Parsed: zh-Hant-HK

Accept-Language: sl-nedis
         Parsed: sl-nedis

Accept-Language: sl-IT-nedis
         Parsed: sl-IT-nedis

Accept-Language: de-CH-1901
         Parsed: de-CH-1901

Accept-Language: de-DE-u-co-phonebk
         Parsed: de-DE-u-co-phonebk

Accept-Language: en-US-x-twain
         Parsed: en-US-x-twain
```

### Actual behavior

Simpler language tags are parsed correctly, but some of the more complex ones are not:

```
Accept-Language: en
         Parsed: en

Accept-Language: ast
         Parsed: ast

Accept-Language: zh-yue
         Parsed: zh

Accept-Language: ar-afb
         Parsed: ar

Accept-Language: zh-Hans
         Parsed: zh

Accept-Language: az-Latn
         Parsed: az

Accept-Language: en-GB
         Parsed: en-GB

Accept-Language: es-005
         Parsed: es-005

Accept-Language: zh-Hant-HK
         Parsed: zh-x-lvariant-HK

Accept-Language: sl-nedis
         Parsed: sl

Accept-Language: sl-IT-nedis
         Parsed: sl-IT-nedis

Accept-Language: de-CH-1901
         Parsed: de-CH-1901

Accept-Language: de-DE-u-co-phonebk
         Parsed: de-DE-x-lvariant-u

Accept-Language: en-US-x-twain
         Parsed: en-US-x-lvariant-x
```

### How to Reproduce?

[i18n-with-quarkus-reactive.zip](https://github.com/quarkusio/quarkus/files/12777404/i18n-with-quarkus-reactive.zip)

1. run the application with `./mvnw clean compile quarkus:dev`
2. either use the included `tests.sh` script to run some `curl` commands, or craft your own with an `Accept-Language` header for the URL `http://localhost:8080/hello`
3. note the response to see if the parsed Locale produces the same language tag as the given header

### Output of `uname -a` or `ver`

Linux laverne 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8.1" 2023-08-24

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nderwin**
- Fixes: https://github.com/quarkusio/quarkus/issues/36227.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

Would you like to add some new tests that verify the behavior?

**Comment by nderwin** [comment]
@geoand Sure, where would they go, in the `integration-tests` module?  Hrm, I don't see an existing `resteasy-reactive` module there (not counting the Kotlin one).

**Comment by geoand** [comment]
I would add one [here](https://github.com/quarkusio/quarkus/tree/338fe5300acfd26692e14192ae4c054cb800eb33/independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test)

**Comment by geoand** [comment]
I have launched CI, let's see what it says

**Comment by nderwin** [comment]
:crossed_fingers:

**Review by gsmet — APPROVED** [review]
This looks good, thanks.

I will let @geoand approve and merge when he's back from Devoxx.

**Comment by geoand** [comment]
Thanks. I want to have a closer looks because either the Javadoc of the method is outdated, or something more subtle is going on.

**Comment by nderwin** [comment]
@geoand Also keep an eye on https://github.com/resteasy/resteasy/pull/3808 - I made the same change for the non-reactive RESTEasy, and it tripped on the Jakarta REST TCK.  If it's rejected there, then we should probably reject this too, for consistency.

**Comment by nderwin** [comment]
My PR for RESTEasy was replaced with these two that were merged:

https://github.com/resteasy/resteasy/pull/4054
https://github.com/resteasy/resteasy/pull/4055

**Comment by gsmet** [comment]
Thanks for the follow-up. How did the TCK issue get fixed?

**Comment by nderwin** [comment]
I'm not sure.  I wasn't really clear on what the TCK issue was, unfortunately.

**Comment by nderwin** [comment]
I think it's been long enough that we can turn this back into a real PR.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
As this is doing the same as RESTEasy is now doing, it makes perfect sense to merge it

**Pull request merged**
