### PR TITLE
Qute - support addition and subtraction for integer numbers

### LINKED ISSUE #25824: Add simple arithmetic to Qute expressions
### Description

Currently simple arithmetic doesn't work in Qute templating: I have used `... {datasetOrdinal + 1 } ...` and received an exception:
```
io.quarkus.qute.TemplateException: Method "+(1)" not found on the base object "java.lang.Integer" in expression {datasetOrdinal.+(1)} in template
```
I am not sure why I assumed this would work but it would be definitely nice.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #25824

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
That is cool

**Comment by mkouba** [comment]
I originally thought that it would be nice to add support for multiplication and division as well but then I realized that with the current syntax/API we can't implement the behavior similar to "operators with priority", e.g. `1 + 2 * 3` would not return `7` but `9` because it would be translated to something like `1.plus(2).multiple(3)`. We could revisit this later...

**Comment by mkouba** [comment]
> Hi @mkouba , it seems that while `{x.y + 1}` works well `{x.y+1}` does not (mind the spaces): `Property "y+1" not found on the base object "foo.bar.X" in expression {x.y+1}`. Should I open another issue or reopen the original?

Yes, that's expected (although not very intuitive). You can do `{x.y.plus(1)}` or use the infix notation `{x.y + 1}` or `{x.y plus 1}`. However, `{x.y+1}` is parsed as an expression with two parts: `x` and `y+1`.

**Comment by rvansa** [comment]
@mkouba I guess this is related to the problem with multiplication - the parsing is not breaking expression into tokens and then building the tree (with priorities) but follows a simpler approach. Well, noone really wants to build another Touring-complete DSL and a workaround exists, so fair enough.

**Comment by mkouba** [comment]
> @mkouba I guess this is related to the problem with multiplication - the parsing is not breaking expression into tokens and then building the tree (with priorities) but follows a simpler approach. Well, noone really wants to build another Touring-complete DSL and a workaround exists, so fair enough.

Yup, it's a limitation of our current syntax rules.

**Pull request merged**
