### PR TITLE
Update `jboss-logmanager` to 3.0.4.Final

### LINKED ISSUE #22844: Gradle tests (with JBoss LogManager setup) output duplicate unformatted messages
### Describe the bug

When Gradle tests are setup to use the JBoss LogManager (as suggested in the test logging guide using `systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"`). Gradle will output unformatted raw messages to stdout during testing.

For example, this log statement in an application:
```
Log.errorf("Hello %s!", "World");
```

will produce the following output during `./gradlew (build|test)`:
```

> Task :quarkusGenerateCode
preparing quarkus application

> Task :quarkusGenerateCodeTests
preparing quarkus application
Hello %s!

BUILD SUCCESSFUL in 3s
6 actionable tasks: 6 executed
```

It should be noted that Gradle hides stdout/stderr from tests by default. So the `Hello %s` is a duplicate, if you look at the `stdout` output of the actual test you will see a proper log line with the message `Hello World!`.

### Expected behavior

Log messages should be output once (and never be unformatted) during build and/or teest.

### Actual behavior

Log messages are duplicated and unformatted during build and/or test.

### How to Reproduce?

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7857227/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

MacOS 12.1

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

_No response_

### LINKED ISSUE #36919: Quarkus 3.4.x+ forces ASCII logging out to console instead of abiding by environment/system default as it had previously
### Describe the bug

I am not sure why, but somewhere between Quarkus 3.3.3 & 3.4.x something changed in how the logging is happening.  Prior to 3.4.x I could deploy anywhere and log to the console and it would abide by the system default encoding for the logging (for instance if I deployed to z/OS the encoding would be EBCDIC and the logs could easily be viewed through checking the console).  The same happened for logging to a file...before 3.4.x it was defaulting to EBCDIC and now it is ASCII, however I have the ability to switch the encoding on the file via the quarkus.log.file.encoding setting (https://quarkus.io/guides/logging#quarkus-log-logging-log-config_quarkus.log.file.encoding) and that is working.  I do not have the option of setting the console log encoding though regardless of what I have tried.  More importantly I am curious and cannot find as to what changed that is causing this.

### Expected behavior

The encoding for console logging should not have changed between Quarkus 3.3.3 & 3.4.x or at a minimum I should be able to set something to switch the console logging back to what it was.

### Actual behavior

The encoding for console logging is now always ASCII with no way to set/change it.

### How to Reproduce?

1. Deploy Quarkus 3.3.3 HelloWorld application to z/OS and note that it logs to console in EBCDIC
2. Deploy Quarkus 3.4.x HelloWorld application to z/OS and note that it logs to console in ASCII with no way of fixing/changing it

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

java version "11.0.17" 2022-10-18 IBM Semeru Runtime Certified Edition for z/OS 11.0.17.0 (build 11.0.17+8)

### Quarkus version or git rev

3.3.3 & 3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.4

### Additional information

I am confused as they are using the same slf4j and logmanager dependencies/libraries?

Quarkus 3.3.3 (Console logging encoding in EBCDIC):

[INFO] \- io.quarkus:quarkus-arc:jar:3.3.3:compile
[INFO]    \- io.quarkus:quarkus-core:jar:3.3.3:compile
[INFO]       +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]       \- org.jboss.slf4j:slf4j-jboss-logmanager:jar:2.0.0.Final:compile

Quarkus 3.4.1 (Console logging encoding in ASCII):

[INFO] \- io.quarkus:quarkus-arc:jar:3.4.1:compile
[INFO]    \- io.quarkus:quarkus-core:jar:3.4.1:compile
[INFO]       +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]       \- org.jboss.slf4j:slf4j-jboss-logmanager:jar:2.0.0.Final:compile

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #36919. Fixes #22844.

### CODE REVIEW

**Comment by gsmet** [comment]
@dmlloyd the errors are probably related as I haven't see these failures before.

**Comment by dmlloyd** [comment]
The failures do indeed look like they may be logging-related, though I don't see a change that might cause it.

**Comment by dmlloyd** [comment]
```

**Comment by dmlloyd** [comment]
It's a regression: https://issues.redhat.com/browse/LOGMGR-344

I'll update this PR with 3.0.4.Final once the release is done (and the requisite time has elapsed).

**Comment by dmlloyd** [comment]
Should be OK now.

**Comment by dmlloyd** [comment]
I'll double check these failures.

**Comment by dmlloyd** [comment]
Some (or maybe all) of these failures are due to usage of `InMemoryHandler`, which implements the JUL `Handler` API. Because of this, and the fix for #22844, the log manager auto-formats `printf`-style messages, causing tests which rely on the structure of log records to fail.

The simple workaround which I am testing now is for these handlers to extend `ExtHandler` instead, indicating that they can process `printf`-formatted records.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
