### PR TITLE
Apply Quarkus formatting rules to ArC sources

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Looks good to me. I let it open as you specifically asked Stuart's review but feel free to merge.

**Comment by stuartwdouglas** [comment]
Is it worth merging https://github.com/quarkusio/quarkus/pull/1383 first? If not then it might be better to do this as two commits (one where you add the formatter, the other where you actually run it), just to make it a bit easier to fix up that other PR.

**Comment by mkouba** [comment]
@gsmet Thanks. I asked Stuart because he's our formatting guru ;-)
@stuartwdouglas ok, so I'll try to split the PR in two commits.

**Comment by mkouba** [comment]
Actually, it makes sense to merge the Spring DI stuff first...

**Review by stuartwdouglas — APPROVED** [review]
Looks fine once the conflicts are fixed.

**Comment by gsmet** [comment]
Needs rebase (or reformat).

**Comment by mkouba** [comment]
Yes, I know. I'd like to merge https://github.com/quarkusio/quarkus/pull/1485 first.

**Pull request merged**
