### PR TITLE
Update Boucycastle to 1.77 and Boucycastle FIPS to 1.0.2.4

### LINKED ISSUE #36735: Failure to bump BouncyCastle FIPS version to 1.0.2.4 due to a native build failure
### Describe the bug

Creating this bug so that I don't forget about the native build failure reported by @gsmet at #36679

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
PRs were created by Dependabot in the quarkus-platform so I think we should update here.

Also Fixes #36735

### CODE REVIEW

**Comment by gsmet** [comment]
The substitutions will require some adjustments:

```
[1/8] Initializing...                                                                                    (0.0s @ 0.14GB)
Error: could not find target field: private java.security.SecureRandom io.quarkus.security.runtime.graal.Target_org_bouncycastle_jcajce_provider_BouncyCastleFipsProvider.providerDefaultRandom
com.oracle.svm.core.util.UserError$UserException: could not find target field: private java.security.SecureRandom io.quarkus.security.runtime.graal.Target_org_bouncycastle_jcajce_provider_BouncyCastleFipsProvider.providerDefaultRandom
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.guarantee(UserError.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalField(AnnotationSubstitutionProcessor.java:913)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:550)
```

**Comment by sberyozkin** [comment]
Let me have a look

**Comment by gsmet** [comment]
@sberyozkin note that we need to make sure this field hasn't been moved elsewhere!

**Comment by sberyozkin** [comment]
@gsmet I've removed one of the SecureRandom fields as it has been replaced by `SecureRandomProvider` interface and it looks like it may be resolving it at runtime

**Comment by gsmet** [comment]
Thanks @sberyozkin !

**Review by sberyozkin — APPROVED** [review]

**Pull request merged**
