### PR TITLE
Update to Vert.x 4.1.1

### PR DESCRIPTION
**Pull request by cescoffier**
Also, update:

* Mutiny Vert.x Binding to 2.8.0
* SmallRye Reactive Messaging to 3.6.0

Both projects use Vert.x 4.1.1

### CODE REVIEW

**Comment by cescoffier** [comment]
According to the change I had to do around Vert.x, I doubt it will pass CI, but let's see.

**Comment by famod** [comment]
Nice, I'll try adding keystore alias password support after the merge. (https://github.com/eclipse-vertx/vert.x/issues/3970)

**Comment by famod** [comment]
It seems this MP-Health exclusion can now be removed: https://github.com/quarkusio/quarkus/blob/main/integration-tests/reactive-messaging-kafka/pom.xml#L55-L60
See also: https://github.com/quarkusio/quarkus/pull/18158#discussion_r658760020

**Review by geoand — APPROVED** [review]

**Comment by cescoffier** [comment]
Hum, we got a new random instance in io.vertx.ext.mail.impl.sasl.NTLMEngineImpl.

**Review by gsmet — APPROVED** [review]
CI looks happy, I let you merge it when you want :)

**Pull request merged**
