### PR TITLE
Document Reactive DataSource idle-timeout limitation

### PR DESCRIPTION
**Pull request by tsegismont**
Follows-up on #14737

See #14608

### CODE REVIEW

**Comment by tsegismont** [comment]
@gsmet @rsvoboda @pjgg

**Comment by gsmet** [comment]
So the doc addition is all good but I fail to see how this config property is useful in real life? Shouldn't we rather have some maximum lifetime for a connection in the pool?

**Comment by gsmet** [comment]
To be more precise: your example is all well with a select, but things will get a tad harder with an INSERT, an UPDATE or a DELETE.

**Comment by tsegismont** [comment]
@gsmet it must be somewhat useful as someone from the community asked for it and we also got feedback from another person that use it.

Yes, we should have a maximum lifetime for the connection in the pool, we've come to an agreement for addressing that in #14608. A part of the agreement was to document the limitation in the interim, hence this PR.

It's not necessarily more difficult when you have multiple interactions (including updates). You could apply the retry operator on a Uni/Multi that fails if the first interaction failed and transaction was rollbacked. The whole process would be retried in a new transaction.

Keep in mind that these failures happen rarely (as reported by the community user from production experience).

**Review by rsvoboda — APPROVED** [review]
The doc addition looks good to me. The main goal was to highlight current limitations to the users so they can get ready for this (rare) case which can bite them in production.

There is https://github.com/eclipse-vertx/vertx-sql-client/pull/881 and https://github.com/eclipse-vertx/vertx-sql-client/pull/883 work going on to address this problem

**Comment by gsmet** [comment]
My guess is that we will need to rename the existing property as part of the upcoming change and reuse the current name for the new feature. But I think that's fine given I'm pretty sure the new feature is what people want.

**Comment by tsegismont** [comment]
@gsmet agreed

**Pull request merged**
