### PR TITLE
Upgrades infinispan extension: don't create Remote Cache Manager without server list

### LINKED ISSUE #18517: Do not produce Infinispan RemoteCacheManager if no Infinispan configuration is present - part 2
Follow up to https://github.com/quarkusio/quarkus/issues/18232. See [comments](https://github.com/quarkusio/quarkus/issues/18232#issuecomment-873922973) after testing the changes made in #18363.

### PR DESCRIPTION
**Pull request by karesti**
Resolves #18517

### CODE REVIEW

**Comment by karesti** [comment]
@jamesnetherton would you mind testing this again please ?

**Comment by jamesnetherton** [comment]
@karesti This doesn't seem to be working for me. The `builderFromProperties(properties).build()` step is throwing an exception: `ISPN004030: Cannot enable authentication without specifying either a username, a token, a client Subject or a CallbackHandler`.

The [previous fix](https://github.com/karesti/quarkus/commit/4ae93de797b3f2ea98bd14e25aa71abe289393ae) works because it returns from the producer method before reaching that point.

**Comment by jamesnetherton** [comment]
BTW - I made a basic demo app to test with [here](https://github.com/jamesnetherton/camel-infinispan-demo).

**Comment by karesti** [comment]
@jamesnetherton I tested this and test passed for me

**Comment by jamesnetherton** [comment]
Thanks @karesti! I tested some other scenarios and they work as expected too :+1:

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
@karesti Should this fix be backported?

**Comment by karesti** [comment]
@gastaldi I think it should be for camel at least but I'm not sure this is necessary

**Pull request merged**
