### PR TITLE
Jackson should use HybridJacksonPool

### LINKED ISSUE #39738: Quarkus should use `HybridJacksonPool` with Loom
### Describe the bug

Using Java 21 (with ) and running the test at https://github.com/franz1981/fortune-benchmark/blob/main/fortune-virtual-thread-mariadb/src/test/java/me/escoffier/fortune/virtual/reactive/mariadb/test/FortuneApiTest.java

with the branch at https://github.com/quarkusio/quarkus/pull/39704

this is the reported stack trace:
```
<init>:289, RecyclerPool$LockFreePoolBase (com.fasterxml.jackson.core.util)
<init>:214, JsonRecyclerPools$LockFreePool (com.fasterxml.jackson.core.util)
<clinit>:209, JsonRecyclerPools$LockFreePool (com.fasterxml.jackson.core.util)
newLockFreePool:85, JsonRecyclerPools (com.fasterxml.jackson.core.util)
defaultPool:29, JsonRecyclerPools (com.fasterxml.jackson.core.util)
<init>:376, JsonFactory (com.fasterxml.jackson.core)
<init>:29, MappingJsonFactory (com.fasterxml.jackson.databind)
<init>:682, ObjectMapper (com.fasterxml.jackson.databind)
<init>:605, ObjectMapper (com.fasterxml.jackson.databind)
objectMapper:31, ObjectMapperProducer (io.quarkus.jackson.runtime)
doCreate:-1, ObjectMapperProducer_ProducerMethod_objectMapper_0pJSAzCVhvpc3iOoOyAlWRwtODI_Bean (io.quarkus.jackson.runtime)
create:-1, ObjectMapperProducer_ProducerMethod_objectMapper_0pJSAzCVhvpc3iOoOyAlWRwtODI_Bean (io.quarkus.jackson.runtime)
create:-1, ObjectMapperProducer_ProducerMethod_objectMapper_0pJSAzCVhvpc3iOoOyAlWRwtODI_Bean (io.quarkus.jackson.runtime)
createInstanceHandle:119, AbstractSharedContext (io.quarkus.arc.impl)
get:38, AbstractSharedContext$1 (io.quarkus.arc.impl)
get:35, AbstractSharedContext$1 (io.quarkus.arc.impl)
get:32, LazyValue (io.quarkus.arc.impl)
computeIfAbsent:69, ComputingCache (io.quarkus.arc.impl)
computeIfAbsent:19, ComputingCacheContextInstances (io.quarkus.arc.impl)
get:35, AbstractSharedContext (io.quarkus.arc.impl)
get:-1, ObjectMapperProducer_ProducerMethod_objectMapper_0pJSAzCVhvpc3iOoOyAlWRwtODI_Bean (io.quarkus.jackson.runtime)
get:-1, ObjectMapperProducer_ProducerMethod_objectMapper_0pJSAzCVhvpc3iOoOyAlWRwtODI_Bean (io.quarkus.jackson.runtime)
doCreate:-1, BasicServerJacksonMessageBodyWriter_Bean (io.quarkus.resteasy.reactive.jackson.runtime.serialisers)
create:-1, BasicServerJacksonMessageBodyWriter_Bean (io.quarkus.resteasy.reactive.jackson.runtime.serialisers)
get:-1, BasicServerJacksonMessageBodyWriter_Bean (io.quarkus.resteasy.reactive.jackson.runtime.serialisers)
get:-1, BasicServerJacksonMessageBodyWriter_Bean (io.quarkus.resteasy.reactive.jackson.runtime.serialisers)
beanInstanceHandle:559, ArcContainerImpl (io.quarkus.arc.impl)
beanInstanceHandle:539, ArcContainerImpl (io.quarkus.arc.impl)
beanInstanceHandle:572, ArcContainerImpl (io.quarkus.arc.impl)
get:331, ArcContainerImpl$3 (io.quarkus.arc.impl)
get:328, ArcContainerImpl$3 (io.quarkus.arc.impl)
create:58, BeanContainerImpl$1 (io.quarkus.arc.runtime)
createInstance:27, ArcBeanFactory (io.quarkus.resteasy.reactive.common.runtime)
instance:80, ResourceWriter (org.jboss.resteasy.reactive.common.model)
toMessageBodyWriters:199, Serialisers (org.jboss.resteasy.reactive.common.core)
findBuildTimeWriters:150, Serialisers (org.jboss.resteasy.reactive.common.core)
buildResourceMethod:426, RuntimeResourceDeployment (org.jboss.resteasy.reactive.server.core.startup)
deploy:136, RuntimeDeploymentManager (org.jboss.resteasy.reactive.server.core.startup)
createDeployment:150, ResteasyReactiveRecorder (io.quarkus.resteasy.reactive.server.runtime)
deploy_0:-1, ResteasyReactiveProcessor$setupDeployment713137389 (io.quarkus.deployment.steps)
deploy:-1, ResteasyReactiveProcessor$setupDeployment713137389 (io.quarkus.deployment.steps)
<clinit>:-1, ApplicationImpl (io.quarkus.runner)
forName0:-1, Class (java.lang)
forName:534, Class (java.lang)
forName:513, Class (java.lang)
run:269, StartupActionImpl (io.quarkus.runner.bootstrap)
doJavaStart:252, QuarkusTestExtension (io.quarkus.test.junit)
ensureStarted:610, QuarkusTestExtension (io.quarkus.test.junit)
beforeAll:660, QuarkusTestExtension (io.quarkus.test.junit)
lambda$invokeBeforeAllCallbacks$12:396, ClassBasedTestDescriptor (org.junit.jupiter.engine.descriptor)
execute:-1, ClassBasedTestDescriptor$$Lambda/0x00007f756c10ac68 (org.junit.jupiter.engine.descriptor)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
invokeBeforeAllCallbacks:396, ClassBasedTestDescriptor (org.junit.jupiter.engine.descriptor)
before:212, ClassBasedTestDescriptor (org.junit.jupiter.engine.descriptor)
before:85, ClassBasedTestDescriptor (org.junit.jupiter.engine.descriptor)
lambda$executeRecursively$6:148, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, NodeTestTask$$Lambda/0x00007f756c0bfcc0 (org.junit.platform.engine.support.hierarchical)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$8:141, NodeTestTask (org.junit.platform.engine.support.hierarchical)
invoke:-1, NodeTestTask$$Lambda/0x00007f756c0bfaa0 (org.junit.platform.engine.support.hierarchical)
around:137, Node (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$9:139, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, NodeTestTask$$Lambda/0x00007f756c0bf160 (org.junit.platform.engine.support.hierarchical)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
executeRecursively:138, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:95, NodeTestTask (org.junit.platform.engine.support.hierarchical)
accept:-1, SameThreadHierarchicalTestExecutorService$$Lambda/0x00007f756c0ba8d0 (org.junit.platform.engine.support.hierarchical)
forEach:1596, ArrayList (java.util)
invokeAll:41, SameThreadHierarchicalTestExecutorService (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$6:155, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, NodeTestTask$$Lambda/0x00007f756c0bfcc0 (org.junit.platform.engine.support.hierarchical)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$8:141, NodeTestTask (org.junit.platform.engine.support.hierarchical)
invoke:-1, NodeTestTask$$Lambda/0x00007f756c0bfaa0 (org.junit.platform.engine.support.hierarchical)
around:137, Node (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$9:139, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, NodeTestTask$$Lambda/0x00007f756c0bf160 (org.junit.platform.engine.support.hierarchical)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
executeRecursively:138, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:95, NodeTestTask (org.junit.platform.engine.support.hierarchical)
submit:35, SameThreadHierarchicalTestExecutorService (org.junit.platform.engine.support.hierarchical)
execute:57, HierarchicalTestExecutor (org.junit.platform.engine.support.hierarchical)
execute:54, HierarchicalTestEngine (org.junit.platform.engine.support.hierarchical)
execute:198, EngineExecutionOrchestrator (org.junit.platform.launcher.core)
execute:169, EngineExecutionOrchestrator (org.junit.platform.launcher.core)
execute:93, EngineExecutionOrchestrator (org.junit.platform.launcher.core)
lambda$execute$0:58, EngineExecutionOrchestrator (org.junit.platform.launcher.core)
accept:-1, EngineExecutionOrchestrator$$Lambda/0x00007f756c0a3cf8 (org.junit.platform.launcher.core)
withInterceptedStreams:141, EngineExecutionOrchestrator (org.junit.platform.launcher.core)
execute:57, EngineExecutionOrchestrator (org.junit.platform.launcher.core)
execute:103, DefaultLauncher (org.junit.platform.launcher.core)
execute:85, DefaultLauncher (org.junit.platform.launcher.core)
execute:47, DelegatingLauncher (org.junit.platform.launcher.core)
execute:63, SessionPerRequestLauncher (org.junit.platform.launcher.core)
startRunnerWithArgs:57, JUnit5IdeaTestRunner (com.intellij.junit5)
execute:38, IdeaTestRunner$Repeater$1 (com.intellij.rt.junit)
repeat:11, TestsRepeater (com.intellij.rt.execution.junit)
startRunnerWithArgs:35, IdeaTestRunner$Repeater (com.intellij.rt.junit)
prepareStreamsAndStart:232, JUnitStarter (com.intellij.rt.junit)
main:55, JUnitStarter (com.intellij.rt.junit)
```
which shows that https://github.com/quarkusio/quarkus/pull/38196 is not kickin-in

The same data information can be retrieved while acquiring buffers out of the pool

image

### PR DESCRIPTION
**Pull request by franz1981**
- Fixes #39738

### CODE REVIEW

**Comment by geoand** [comment]
Seems reasonable to me

**Comment by franz1981** [comment]
@geoand I have found this ->  https://github.com/FasterXML/jackson-module-scala/issues/672#issuecomment-2002358450

**Comment by franz1981** [comment]
@geoand I have found this ->  https://github.com/FasterXML/jackson-module-scala/issues/672#issuecomment-2002358450

**Review by mariofusco — APPROVED** [review]
That's ok for me as a temporary workaround, but in reality the problem should be fixed in `jackson-core` that [when returning the `defaultPool()`](https://github.com/FasterXML/jackson-core/blob/b8a132eefe3ccdcccfe4af444c1c3d237211fd1b/src/main/java/com/fasterxml/jackson/core/util/JsonRecyclerPools.java#L29) should actually return the [shared one](https://github.com/FasterXML/jackson-core/blob/b8a132eefe3ccdcccfe4af444c1c3d237211fd1b/src/main/java/com/fasterxml/jackson/core/util/JsonRecyclerPools.java#L76) instead of creating a new pool each and every time.

I will send a pull request to `jackson-core` to fix this problem, but when the change will be included in a stable release, and we will upgrade to it, I believe we should also revert this fix otherwise if jackson will decide to change the default pool with a different implementation we will break our integration again.

**Comment by franz1981** [comment]
> in reality the problem should be fixed in jackson-core that [when returning the defaultPool()](https://github.com/FasterXML/jackson-core/blob/b8a132eefe3ccdcccfe4af444c1c3d237211fd1b/src/main/java/com/fasterxml/jackson/core/util/JsonRecyclerPools.java#L29) should actually return the [shared one](https://github.com/FasterXML/jackson-core/blob/b8a132eefe3ccdcccfe4af444c1c3d237211fd1b/src/main/java/com/fasterxml/jackson/core/util/JsonRecyclerPools.java#L76) instead of creating a new pool each and every time.

Agree, although, if users set a different instance of still that specific pool I would feel safer by NOT using it, given that is dangerous even for the non virtual thread use case ie after 3 attempts to compare and set a pool, it will create a whole new one (!), which is not what we want regardless.
Related this specific point I believe jackson should not use that pool as default and/or having an infinite loop-like there, instead.

**Comment by mariofusco** [comment]
As anticipated I sent [this pull request](https://github.com/FasterXML/jackson-core/pull/1250) to jackson that should fix the problem.

**Comment by franz1981** [comment]
after speaking with @mariofusco I agree on the fact that we cannot save users which want to shoot themselves in the foot ie this PR is just a workaround, which prevent users which use the "wrong" pool type to do it, so, in theory it would be better to wait for the actual fix, and marge this in meantime, depending by the time required by jackson to keep up (and us to use it). @geoand

**Comment by geoand** [comment]
👌

**Comment by mariofusco** [comment]
@geoand it seems that Jackson's maintainers don't agree with [the change I proposed](https://github.com/FasterXML/jackson-core/pull/1250) to avoid creating a new pool at each and every incocation of the `defaultPool()` method, so we necessarily need to merge this PR asap. \cc @franz1981

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Understood, thanks

**Comment by geoand** [comment]
Mind rebasing onto `main` please?

**Pull request merged**
