### PR TITLE
SubclassGenerator - split initialization of interception metadata

### LINKED ISSUE #28864: Camel EndpointRouteBuilder throws org.objectweb.asm.MethodTooLargeException
### Describe the bug

A class that implements a Camel EndpointRouteBuilder with six methods additional methods (besides configure) throws an exception when starting quarkus.
Note that if the builder has less than six additional methods there is no error.

### Expected behavior

Quarkus starts without error.

### Actual behavior

An exception is thrown:

```
$ mvn clean quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:camel-reproducer >----------------------
[INFO] Building camel-reproducer 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ camel-reproducer ---
[INFO] Deleting /Users/miguel.pedro/workspace/quarkus-examples/camel-reproducer/target
[INFO]
[INFO] --- quarkus-maven-plugin:2.13.3.Final:dev (default-cli) @ camel-reproducer ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ camel-reproducer
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.13.3.Final:generate-code @ camel-reproducer
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile @ camel-reproducer
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/miguel.pedro/workspace/quarkus-examples/camel-reproducer/target/classes
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ camel-reproducer
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/miguel.pedro/workspace/quarkus-examples/camel-reproducer/src/test/resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.13.3.Final:generate-code-tests @ camel-reproducer
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ camel-reproducer
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
2022-10-26 17:11:53,758 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2022-10-26 17:11:53,787 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:322)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	... 6 more
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:214)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
	at io.quarkus.arc.processor.SubclassGenerator.generate(SubclassGenerator.java:127)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:289)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:286)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:322)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	... 6 more
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:214)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
	at io.quarkus.arc.processor.SubclassGenerator.generate(SubclassGenerator.java:127)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:289)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:286)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 9 more
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:322)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	... 6 more
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:214)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
	at io.quarkus.arc.processor.SubclassGenerator.generate(SubclassGenerator.java:127)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:289)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:286)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more
```

### How to Reproduce?

Reproducer: https://github.com/miguel-figueiredo/quarkus-examples/tree/master/camel-reproducer

Steps to reproduce:

1. Run `./mvnw compile quarkus:dev` 

### Output of `uname -a` or `ver`

Darwin PT-340360-MBP32M1P.lan 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 11.0.16 2022-07-19 LTS OpenJDK Runtime Environment Corretto-11.0.16.8.1 (build 11.0.16+8-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.16.8.1 (build 11.0.16+8-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec Java version: 11.0.16, vendor: Amazon.com Inc., runtime: /Users/miguel.pedro/.sdkman/candidates/java/11.0.16-amzn Default locale: en_PT, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "aarch64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #28864

### CODE REVIEW

**Comment by mkouba** [comment]
CC @manovotn

**Comment by geoand** [comment]
I wonder if there is any way to add a test that would cover the cause of https://github.com/quarkusio/quarkus/issues/28864

**Comment by mkouba** [comment]
> I wonder if there is any way to add a test that would cover the cause of #28864

Hm, the only way I'm aware of is to generate a class with 1000+ methods... so let's do this!

**Comment by mkouba** [comment]
> > I wonder if there is any way to add a test that would cover the cause of #28864
> 
> Hm, the only way I'm aware of is to generate a class with 1000+ methods... so let's do this!

Done.

**Review by manovotn — COMMENTED** [review]
Hmm, this is very much like the attempt I did but unlike my attempt, this actually works :)

LGTM, I was only thinking the `groupLimit` might be higher. You could comfortably house 100 interceptors in a single init method.

**Review by manovotn — APPROVED** [review]

**Comment by Ladicek** [comment]
I had to play with this locally to understand. Here's a simple optimization that gets rid of repeated lookups of the exact same thing in the interception metadata initialization methods: https://github.com/Ladicek/quarkus/commits/interception-metadata-split

I believe we should be able to get rid of the newly-introduced maps completely. We could separate initialization methods for each combination of interception chain + interceptor bindings, and those initialization methods would just take `List<InterceptorInvocation>` and `Set<Annotation>` as parameters. This wouldn't get rid of the need to split, just of the needless `Map` allocations / lookups. I could take a stab at that, but it would take me a bit longer than just the simple improvement above.

**Comment by mkouba** [comment]
> Here's a simple optimization that gets rid of repeated lookups of the exact same thing...

Nice! Could you just push your commit to my branch?

> We could separate initialization methods for each combination of interception chain + interceptor bindings, and those initialization methods would just take List<InterceptorInvocation> and Set<Annotation> as parameters.

Interesting idea, but in that case you would have to split the init methods per each interception chain + interceptor bindings combination. I'm not really sure it's worth the effort. I mean those "needless Map allocations/lookups" are IMO negligible. In any case, feel free to take a look and send a follow-up PR.

**Comment by Ladicek** [comment]
Pushed my simple improvement to this PR.

Here's a branch with a more thorough optimization I described above: https://github.com/Ladicek/quarkus/commits/interception-metadata-split-v2 @manovotn has a good point that this ends up emitting more init methods than would be otherwise necessary, so I'll just let you look at it and see what you think.

**Comment by mkouba** [comment]
So in theory, we don't need to generate init methods for every combination of chain + bindings but instead analyze the combinations for a particular batch of intercepted methods and pass all chains and bindings as params to each init method. We have 255 slots to use and that should be enough for a group of 30 intercepted methods ;-).

**Comment by Ladicek** [comment]
That is a good idea!

**Comment by mkouba** [comment]
> EDIT: technically we have 254 slots, because the init methods are not `static`

Very true :D

**Comment by Ladicek** [comment]
Just to be sure, I totally agree with merging this first!

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
