### PR TITLE
Bump Jackson to 2.16.0

### PR DESCRIPTION
**Pull request by geoand**
Also includes the necessary bump aws xray to 2.15.0

Replaces #37188

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
The test failures are weird, I'll have to look more

**Comment by gsmet** [comment]
The Amazon Lambda failure looks related, I haven't checked the other one:

```
2023-11-24T13:49:43.9940914Z Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class com.fasterxml.jackson.databind.PropertyNamingStrategy does not have member field 'com.fasterxml.jackson.databind.PropertyNamingStrategy CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES' [in thread "main"]
2023-11-24T13:49:43.9946911Z 	at com.amazonaws.xray.entities.EntityImpl.<clinit>(EntityImpl.java:61)
2023-11-24T13:49:43.9949717Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
2023-11-24T13:49:43.9952615Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
2023-11-24T13:49:43.9957662Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:177)
2023-11-24T13:49:43.9964443Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.AllowAllHostedUsagesClassInitializationSupport.computeInitKindAndMaybeInitializeClass(AllowAllHostedUsagesClassInitializationSupport.java:191)
2023-11-24T13:49:43.9971636Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.AllowAllHostedUsagesClassInitializationSupport.computeInitKindAndMaybeInitializeClass(AllowAllHostedUsagesClassInitializationSupport.java:160)
2023-11-24T13:49:44.0013183Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.AllowAllHostedUsagesClassInitializationSupport.computeInitKindAndMaybeInitializeClass(AllowAllHostedUsagesClassInitializationSupport.java:129)
```

**Comment by geoand** [comment]
Indeed.

I'm going to tap out of this one however as I will be traveling next week

**Comment by gsmet** [comment]
I think we will have to wait for X-Ray to adapt. The problem is caused by this commit in Jackson: https://github.com/FasterXML/jackson-databind/commit/d7a1efc7f45af4f56c0df4eccb0244418b6428bb .

**Comment by gsmet** [comment]
The MySQL one is related to a Quay issue so not concerning.

**Comment by geoand** [comment]
Ah, nice catch!

@msailes is the X-RAY something you can help push forward on your side?

Thanks 🙏

**Comment by msailes** [comment]
@wangzlei, is this a change X-Ray plans to make?

**Comment by manofthepeace** [comment]
Created this in the hope I can help a bit where I can.. https://github.com/aws/aws-xray-sdk-java/pull/391

**Comment by wangzlei** [comment]
Thanks for providing https://github.com/aws/aws-xray-sdk-java/pull/391, we would release a minor version with this fix next week.

**Comment by geoand** [comment]
Great, thanks!

**Review by gsmet — APPROVED** [review]
Woot, thanks!

**Comment by gsmet** [comment]
Oh and thanks @msailes for pinging the right person, it helped too!

**Pull request merged**
