### PR TITLE
Creates maven profiles for integration tests

### PR DESCRIPTION
**Pull request by zakkak**
Allows running groups of test in CI builds with commands like:

    mvn -e -pl integration-tests -amd -PIT-Security1 verify
    mvn -e -pl integration-tests -amd -Dnative -PIT-Security1 verify
    mvn -e -pl integration-tests -amd -Dno-format -DskipDocs -Dnative -PIT-Security1 verify

etc.

### CODE REVIEW

**Review by galderz — APPROVED** [review]
Looks good to me. It appears the build run fine too.

Needs rebasing though and verify that the build continues to work well after that.

**Comment by galderz** [comment]
Needs rebasing again :\

**Comment by zakkak** [comment]
@gsmet @n1hility could you please give me some feedback on this before I invest time on a second rebase?

**Comment by zakkak** [comment]
@gsmet @n1hility this is a kind reminder.

Change 5724c0ad80ea433c4f1f6c521ea8e586f5eb783a requires updating the workflows of mandrel and graal (again) while with this PR we would have avoided this.

**Comment by zakkak** [comment]
@gsmet @n1hility this is another kind reminder :)

**Comment by gastaldi** [comment]
@zakkak it needs another rebase :)

**Comment by gastaldi** [comment]
@zakkak I like this approach. My only concern is if once we start using GIB (https://github.com/vackosar/gitflow-incremental-builder) this won't become a burden? @famod any thoughts?

**Comment by famod** [comment]
@gastaldi 
> My only concern is if once we start using GIB (https://github.com/vackosar/gitflow-incremental-builder) this won't become a burden? @famod any thoughts?

Well, I haven't tested GIB with this setup, but theoretically there shouldn't be a problem.
I might be able to try it out later this week (Sunday at the latest).

**Comment by zakkak** [comment]
@gastaldi I know it needs another rebase, but before investing time on it I would like to get some feedback (I guess you covered that part )  and hopefully a confirmation that this will get merged after the rebase so that it won't end up needing yet another rebase :)

Now waiting for @famod 's OK as well :)

**Comment by famod** [comment]
I've tested this briefly with GIB and it works as expected!

**Comment by zakkak** [comment]
Hi @gastaldi, this should now be up to date.

**Review by gastaldi — APPROVED** [review]
LGTM. Any objections that may impact the next release @gsmet ?

**Comment by gastaldi** [comment]
Merged. Let's see how that goes. Thanks!

**Comment by zakkak** [comment]
Thanks @gastaldi

**Comment by gsmet** [comment]
The doc at the bottom of https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#frequently-asked-questions needs an update.

**Comment by zakkak** [comment]
> The doc at the bottom of https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#frequently-asked-questions needs an update.

:+1: Noted!

**Pull request merged**
