### PR TITLE
Use latest SmallRye Context Propagation

### LINKED ISSUE #40852: @CacheResult with method returning Uni makes cache exceed its maximum size
### Describe the bug

When a method retuning a `Uni` is annotated with `@CacheResult` the result of the `Uni` is cached as expected, but the cache grows infinitely even when a maximum size is set.

### Expected behavior

When the cache reaches the specified maximum size, the number of elements in the cache should stop growing, or at least not grow infinitely.

### Actual behavior

No elements are evicted and the cache grows infinitely

### How to Reproduce?

In [GreetingResource](https://github.com/jolsum/quarkus-cache-eviction/blob/master/src/main/java/org/acme/GreetingResource.java) there are two endpoints ("/hello/fast" and "/hello/delayed"). The "delayed" endpoint gets its data from a method returning a `Uni<String>` where the response is delayed, and the method is annotated with `@CacheResult`. The "fast" endpoint gets it data from method returning a `Uni` with an item without any delay.

```java
@Path("/hello")
public class GreetingResource {

  @GET
  @Produces(MediaType.TEXT_PLAIN)
  @Path("/delayed")
  public Uni<String> delayed() {
    return getHelloDelayed(System.currentTimeMillis());
  }

  @GET
  @Produces(MediaType.TEXT_PLAIN)
  @Path("/fast")
  public Uni<String> fast() {
    return getHelloFast(System.currentTimeMillis());
  }

  @CacheResult(cacheName = "delayed")
  Uni<String> getHelloDelayed(long key) {
    return Uni.createFrom().item("Hello with a delay").onItem().delayIt().by(Duration.ofMillis(10));
  }

  @CacheResult(cacheName = "fast")
  Uni<String> getHelloFast(long key) {
    return Uni.createFrom().item("Hello");
  }
}
```
The cache maximum size is defined as `quarkus.cache.caffeine.maximum-size = 10`

In the [GreetingResourceTest](https://github.com/jolsum/quarkus-cache-eviction/blob/master/src/test/java/org/acme/GreetingResourceTest.java) the endpoints are invoked 20 times and then wait for the size of the cache to become 10.

```java
@QuarkusTest
class GreetingResourceTest {

  @Inject
  @CacheName("fast")
  Cache cacheFast;

  @Inject
  @CacheName("delayed")
  Cache cacheDelayed;

  @Test
  void testFastEndpoint() {
    for (int i = 0; i < 20; i++) {
      given().when().get("/hello/fast").then().statusCode(200).body(is("Hello"));
    }
    await()
        .atMost(5, TimeUnit.SECONDS)
        .until(() -> ((CaffeineCache) cacheFast).keySet().size() == 10);
  }

  @Test
  void testDelayedEndpoint() {
    for (int i = 0; i < 20; i++) {
      given().when().get("/hello/delayed").then().statusCode(200).body(is("Hello with a delay"));
    }
    await()
        .atMost(5, TimeUnit.SECONDS)
        .until(() -> ((CaffeineCache) cacheDelayed).keySet().size() == 10);
  }
}
```
However, the size remains at 20 even after waiting for 5 seconds

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.3593]

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17

### Quarkus version or git rev

3.10.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

I have done some debugging and manage to narrow the issue down to being an issue with `CaffeineCache` and how it works with the `CompletableFuture` returned from `Uni.subscribeAsCompletionStage()`.

If I create a `Uni` with a delayed item like this
```java
    var future =
        Uni.createFrom()
            .item("item")
            .onItem()
            .delayIt()
            .by(Duration.ofMillis(100))
            .subscribeAsCompletionStage();

    future.whenComplete(
        (result, error) -> {
          System.out.println(future.isDone());
        });
```
In `whenComplete()` the `future.isDone()` returns `false`. So in Caffeine class `BoundedLocalCache.replace()` the item gets weight 0 and the cache considers it as a read rather than a write even if the item is stored, and the eviction is not run.

### PR DESCRIPTION
**Pull request by FroMage**
Fixes #40852

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by FroMage** [comment]
I suppose this may be related…
```
2024-06-07T15:26:06.5371531Z [ERROR] io.quarkus.vertx.deployment.MessageConsumerFailureTest.testFailure
2024-06-07T15:26:06.5373087Z [ERROR]   Run 1: MessageConsumerFailureTest.testFailure:49->verifyFailure:110 expected: <boom> but was: <java.io.IOException: boom>
2024-06-07T15:26:06.5374337Z [ERROR]   Run 2: MessageConsumerFailureTest.testFailure:49->verifyFailure:110 expected: <boom> but was: <java.io.IOException: boom>
2024-06-07T15:26:06.5375516Z [ERROR]   Run 3: MessageConsumerFailureTest.testFailure:49->verifyFailure:110 expected: <boom> but was: <java.io.IOException: boom>
2024-06-07T15:26:06.5376704Z [ERROR]   Run 4: MessageConsumerFailureTest.testFailure:49->verifyFailure:110 expected: <boom> but was: <java.io.IOException: boom>
```

**Comment by FroMage** [comment]
Yeah, I can reproduce locally. Pity that this behaviour is not tested in the TCK, or the SR/CP tests, or the Quarkus CP tests, and it shows up in something completely unrelated.

**Comment by FroMage** [comment]
I've looked at the problem, and I wonder if that test is actually correct. I would like to know the reasoning behind sometimes having the exception wrapped in `CompletionException` and sometimes not:

```
    @Test
    public void testFailure() throws InterruptedException {
        verifyFailure("foo", "java.lang.IllegalStateException: Foo is dead", false);
        verifyFailure("foo-message", "java.lang.NullPointerException", false);
        verifyFailure("foo-completion-stage", "java.lang.NullPointerException: Something is null", false);
        verifyFailure("foo-completion-stage-failure", "boom", true);
        verifyFailure("foo-uni", "java.lang.NullPointerException: Something is null", false);
        verifyFailure("foo-uni-failure", "boom", true);

        verifyFailure("foo-blocking", "java.lang.IllegalStateException: Red is dead", false);
        verifyFailure("foo-message-blocking", "java.lang.NullPointerException", false);
        verifyFailure("foo-completion-stage-blocking", "java.lang.NullPointerException: Something is null", false);
        verifyFailure("foo-completion-stage-failure-blocking", "boom", true);
        verifyFailure("foo-uni-blocking", "java.lang.NullPointerException: Something is null", false);
        verifyFailure("foo-uni-failure-blocking", "boom", true);
    }
```

All those with `NameOfException: ` prefixes are (I think) wrapped. Only two are not (`boom`) and I'm not sure if that test is correct. Perhaps they should all be wrapped, or nobody should care if they are.

I'll need @cescoffier or perhaps @jponge to help me figure out this test.

**Comment by FroMage** [comment]
I've updated the vertx test temporarily, and marked this PR as Draft, to see if we have other issues.

**Comment by cescoffier** [comment]
We use `CompletionException` when using CompletionStage (that's part of the contract) or Uni failing with a checked exception (we have to wrap it anyway). These are only used when "awaiting" for a result (`.get()` for CS (via completable future) or `await()....` for `Uni`)

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
The change in the test looks fine - we may have tested an implementation-specific behavior.

**Comment by FroMage** [comment]
OK, bumped to 2.1.2 which is compiled for Java 11, let's re-run CI but it should be fine.

**Comment by FroMage** [comment]
CI takes +4h to run, now?

**Comment by geoand** [comment]
It all depends on how many PRs are running in parallel (and what modules they touch)

**Pull request merged**
