### PR TITLE
ArC: deprecate ArcInitConfig.Builder.setOptimizeContexts()

### PR DESCRIPTION
**Pull request by mkouba**
- this value was actually never used

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

**Comment by mkouba** [comment]
Unfortunately, I don't think we can deprecate/rework `ArcInitConfig.Builder.setCurrentContextFactory()` easily. However, I wonder if we should try to replace the `Arc.setExecutor()` with something like `ArcInitConfig.Builder.setExecutor()`? At least, we would be able to make the `ArcContainerImpl.executorService` field `final`. WDYT?

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
> I wonder if we should try to replace the `Arc.setExecutor()` with something like `ArcInitConfig.Builder.setExecutor()`? At least, we would be able to make the `ArcContainerImpl.executorService` field `final`. WDYT?

I didn't look into details, but sounds good!

**Comment by mkouba** [comment]
> > I wonder if we should try to replace the `Arc.setExecutor()` with something like `ArcInitConfig.Builder.setExecutor()`? At least, we would be able to make the `ArcContainerImpl.executorService` field `final`. WDYT?
> 
> I didn't look into details, but sounds good!

Ok. I will try to propose a follow-up PR then...

**Comment by mkouba** [comment]
> > > I wonder if we should try to replace the `Arc.setExecutor()` with something like `ArcInitConfig.Builder.setExecutor()`? At least, we would be able to make the `ArcContainerImpl.executorService` field `final`. WDYT?
> > 
> > 
> > I didn't look into details, but sounds good!
> 
> Ok. I will try to propose a follow-up PR then...

Ah, of course we can't do that because the ArC container is initialized during `STATIC_INIT` but the executor is only available in `RUNTIME_INIT`!

**Pull request merged**
