### PR TITLE
Substitute MappedByteBuffer#force0 only in JDK 15 or earlier

### LINKED ISSUE #15903: MappedByteBufferReplacement substitutions is obsolete in JDK16
## Describe the bug
Trying to build a simple Quarkus Native Image application with a JDK16 based GraalVM results in 
```
Error: Could not find target method: private void io.quarkus.runtime.graal.MappedByteBufferReplacement.force0(java.io.FileDescriptor,long,long)
com.oracle.svm.core.util.UserError$UserException: Could not find target method: private void io.quarkus.runtime.graal.MappedByteBufferReplacement.force0(java.io.FileDescriptor,long,long)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:734)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:366)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:338)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:952)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:886)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:493)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
The target method [`MappedByteBuffer.force0`](https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/graal/MappedByteBufferReplacement.java#L13) has been removed in JDK16.

Note: A JDK16 GraalVM is not widely available yet, it must be built from source.

### PR DESCRIPTION
**Pull request by jaikiran**
Fixes https://github.com/quarkusio/quarkus/issues/15903

I haven't tested this against JDK 16, since Graal VM needs to be built from source and I need to refresh my current setup a bit to get that building.

/cc @cstancu

### CODE REVIEW

**Comment by jaikiran** [comment]
Unrelated failure in `io.quarkus.it.vault.VaultTest.test`

```
2021-03-22T04:28:40.4710627Z Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource io.quarkus.vault.test.VaultTestLifecycleManager@30490759
2021-03-22T04:28:40.4712860Z 	at io.quarkus.test.common.TestResourceManager.lambda$start$1(TestResourceManager.java:110)
2021-03-22T04:28:40.4714635Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-03-22T04:28:40.4716018Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-03-22T04:28:40.4717944Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2021-03-22T04:28:40.4720294Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2021-03-22T04:28:40.4721521Z 	at java.base/java.lang.Thread.run(Thread.java:832)
2021-03-22T04:28:40.4722391Z Caused by: io.smallrye.mutiny.TimeoutException
2021-03-22T04:28:40.4727471Z 	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:58)
2021-03-22T04:28:40.4729236Z 	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
2021-03-22T04:28:40.4730924Z 	at io.quarkus.vault.runtime.client.VertxVaultClient.exec(VertxVaultClient.java:161)
2021-03-22T04:28:40.4732953Z 	at io.quarkus.vault.runtime.client.VertxVaultClient.exec(VertxVaultClient.java:154)
2021-03-22T04:28:40.4734975Z 	at io.quarkus.vault.runtime.client.VertxVaultClient.put(VertxVaultClient.java:122)
2021-03-22T04:28:40.4737854Z 	at io.quarkus.vault.runtime.client.backend.VaultInternalSystemBackend.init(VaultInternalSystemBackend.java:43)
2021-03-22T04:28:40.4740527Z 	at io.quarkus.vault.test.VaultTestExtension.initVault(VaultTestExtension.java:256)
2021-03-22T04:28:40.4742373Z 	at io.quarkus.vault.test.VaultTestExtension.start(VaultTestExtension.java:242)
2021-03-22T04:28:40.4744419Z 	at io.quarkus.vault.test.VaultTestLifecycleManager.start(VaultTestLifecycleManager.java:33)
2021-03-22T04:28:40.4746550Z 	at io.quarkus.test.common.TestResourceManager.lambda$start$1(TestResourceManager.java:105)
2021-03-22T04:28:40.4747694Z 	... 5 more
```

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Comment by cstancu** [comment]
It looks like this didn't make it in latest release, `1.13.0`. Btw, the substitution class for `MappedByteBuffer` should not be necessary  at all, even for JDK < 15, since we have JNI support.

**Comment by jaikiran** [comment]
>Btw, the substitution class for MappedByteBuffer should not be necessary at all

I opened a new PR to handle that https://github.com/quarkusio/quarkus/pull/16380

**Pull request merged**
