### PR TITLE
Use encoded request path in rest-client-reactive

### LINKED ISSUE #25326: Reactive REST client does not encode request path properly
### Describe the bug

If I create a REST client using _quarkus-rest-client-reactive_ spaces in the request path (and other special characters) are not encoded correctly when the final HTTP request is built:

```
javax.ws.rs.client.ClientBuilder.newClient().target("http://localhost:12345/with space").request().get()
javax.ws.rs.client.ClientBuilder.newClient().target("http://localhost:12345/with%20space").request().get()
```

In both cases the HTTP request contains `GET /with space HTTP/1.1` when it should be `GET /with%20space HTTP/1.1`.
This problem does not exist in the classic RESTEasy client.

### Expected behavior

Paths for HTTP requests should be encoded correctly.

### Actual behavior

Special characters are not encoded for the HTTP request.

### How to Reproduce?

Run `quarkus.bugs.RequestUriNotEncoded` from https://github.com/sithmein/bugs-in-quarkus.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #25326

### CODE REVIEW

**Comment by geoand** [comment]
Seems reasonable to me, but let's get @michalszynkiewicz's opinion as well

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by geoand** [comment]
It appears that this did not make it into `2.9.0.Final` but it is in `2.8.3.Final`.

**Comment by lthasle** [comment]
I tried to use 2.9.0.Final and discovered that the fiks is NOT included!

**Comment by geoand** [comment]
Yes, that's an unfortunate side effect of the first release in our `2.9` series. It will be part of `2.9.1`

**Pull request merged**
