### PR TITLE
Add provided capability to OIDC extension

### PR DESCRIPTION
**Pull request by HerrDerb**
Add OIDC as capability as suggested in #30386

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Review by sberyozkin — APPROVED** [review]
Thanks @HerrDerb

**Comment by sberyozkin** [comment]
@HerrDerb Please run `mvn process-sources` or just rebuild the core module and commit the formatting fix

**Comment by geoand** [comment]
Or see the message which tell you exactly what command to run to fix the formatting issue 😉

**Comment by geoand** [comment]
Can you please squash the commits? Once that is done, we can run CI and merge when everything is green

**Pull request merged**
