### PR TITLE
Refetch dynamic credentials for Reactive Postgres Client

### PR DESCRIPTION
**Pull request by kdubb**
Implements a custom `PgConnectionFactory` that refetches dynamic credentials from the configured `CredentialsProvider` for each connection.

The custom factory is only applied when a credentials provider is configured.

### CODE REVIEW

**Comment by kdubb** [comment]
@vietj This is a PR with the changes mentioned in Zulip channel.

**Comment by kdubb** [comment]
To recap...

I have made changes to the reactive Postgres extension that uses a custom PgConnectionFactory that requests new credentials from the CredentialsProvider anytime a new connection is made. I then set the 'idleTimeout' to a factor of the credential expiration time. At first this appears to work. The pool recycles connections that have been connected longer than 'idleTimeout' and during the reconnection new Vault credentials are created.

This can be seen in the following output from `pg_stat_activity`:

Screenshot 2023-03-28 at 9 19 34 PM

This was from a session where the `idleTimeout` is set to 60s. Vault's credential lease time is 60s and the maximum credential lifetime is 3m; this means that it issues new credentials after 60s and revokes the credentials from the Postgres database after 3m.

You can see in the output from `pg_stat_activity` that it's recycling connections after 60s , with each connection getting a new username/password from Vault, except the 0th connection; which is the remaining issue.

Unfortunately there seems to be a "protected" connection in the in the pool. Somewhere in the depths of SqlConnectionPool the eviction code appears to never recycle the first (0th) connection in the pool. This is identified by the length of time connected (around ~9 minutes) and that the 'username` is blank because Vault has revoked those credentials from the database.

If we can get the `SqlConnectionPool` to recycle this first connection like the others then dynamic credentials will start to work as expected.

**Comment by kdubb** [comment]
Ultimately this would need to be reproduced for each reactive SQL client or alternatively we get a feature addition to VertX that will allow new credentials to be fetched during each connect attempt.

**Comment by kdubb** [comment]
/cc @vsevel This is the result of my research into the _many_ tickets we have about dynamic credentials support.

In summary, they don't work in reactive at all and there is no known workaround. I've even tried to getting Vault to refresh the connection (using `rotation_statements`) but Postgres specifically doesn't support anything but a "kill" of the connection; meaning it would cancel any in-flight queries.

So the only way to fix it is to add support to the Quarkus reactive SQL client extensions or tell users to use an external connection manager like `pg_bouncer` that can recycle them.

**Comment by kdubb** [comment]
@tsegismont This is essentially an attempt at simplifying the #31873 by using a `PgConnectionFactory`. It's currently for Postgres only but should be duplicatable for all supported reactive clients. 

The major difference being that this doesn't currently work do to the aforementioned issue with a single connection never being recycled. I see your PR is closing the pool entirely which essentially solves that problem.

**Comment by kdubb** [comment]
This doesn't work it's built upon a faulty assumption of how `idle-timeout` works. I've opened a PR in vertx (https://github.com/eclipse-vertx/vertx-sql-client/pull/1296) that adds proper support for dynamic credentials without any hacks.

**Comment by vsevel** [comment]
> /cc @vsevel This is the result of my research into the _many_ tickets we have about dynamic credentials support.

@kdubb what about those suggestions https://github.com/quarkiverse/quarkus-vault/issues/65#issuecomment-1224275358 or https://github.com/quarkiverse/quarkus-vault/issues/65#issuecomment-1225198358 ?

**Comment by kdubb** [comment]
For a `CredentialsProvider` implementation to "callback" when the credentials are refreshed  would require changes to the `CredentialsProvider` interface itself. I'm okay with that but that's a big surface area change.

Above I referenced a PR I made in the `vertx-sql-client` project that implements pieces to the puzzle to make it easy to implement these things. I can easily add a `flushAll` to support that idea in the future.

**Pull request closed without merging**
