### PR TITLE
Add interactive terminal

### PR DESCRIPTION
**Pull request by stuartwdouglas**
The terminal is activated by pressing ':', and at present can do the
following, all of which support tab completion:

- Open a path in your browser
- Set the log level for a category
- Set a config value

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Best get this in now so we can have it in `2.6.0.CR1`

**Comment by maxandersen** [comment]
if : activates the shell line, what will :q do ? :)

**Comment by stuartwdouglas** [comment]
`:q + return` will enter the shell then exit it immediately.

**Comment by gsmet** [comment]
Unfortunately, this needs a rebase.

**Comment by rsvoboda** [comment]
I know this is "boring" work, but could be some info about this added into the docs / guides?

**Comment by stuartwdouglas** [comment]
I am planning to do it before 2.7, rather than updating it every time something changes, as this will hopefully evolve a lot before the release. It is also somewhat self documenting as the shortcut shows up in the prompt and supports tab completion.

**Comment by rsvoboda** [comment]
OK, good to know more candies are coming :)

**Pull request merged**
