### PR TITLE
Bump Arquillian to 1.5.0.Final

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
I'd recommend holding off updating this PR until after Monday.

Also, I would suggest running a build before pushing a library update that's had API changes.

**Comment by gastaldi** [comment]
Darn, forgot to commit the changes in the class. I'll wait until the CI usage is calm again to push my changes. Thanks for the heads up!

**Review by Sanne — CHANGES_REQUESTED** [review]
not compiling

**Comment by gastaldi** [comment]
@Sanne yeah, I was holding the update to this PR until today. I force pushed the fix

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
Thanks @gastaldi !

**Pull request merged**
