### PR TITLE
Bump jquery from 3.5.1 to 3.6.0 and use maven managed versions in webjars tests

### PR DESCRIPTION
**Pull request by famod**
Follows up on #22372.

### CODE REVIEW

**Comment by gsmet** [comment]
So I'm all for this but I would prefer we use https://search.maven.org/artifact/org.webjars/jquery-ui/1.13.0/jar in the locator tests so that we are totally independent from our usage of jQuery for Quarkus itself.

**Comment by famod** [comment]
@gsmet not sure what this `setForcedDependencies()` bit is about. Would it still cover everything if moving to jquery-ui?

Feel free to take it from here.

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — DISMISSED** [review]
Please don't merge, I want to adjust things.

**Comment by gsmet** [comment]
@gastaldi @famod can you have a look at what I did?

**Review by gastaldi — APPROVED** [review]
LGTM 👍🏻

**Comment by famod** [comment]
Haha. just tried to approve my own PR. 🤦‍♂️ LGTM!

**Pull request merged**
