### PR TITLE
Escape properties in filtered pom.xml of integration-tests/maven and integration-tests/kubernetes 

### LINKED ISSUE #33630: native.image.path have absolute path in generated pom
### Describe the bug

 <native.image.path> is set to an absolute path in lots of pom.xml in  `integration-tests/maven/target/test-classes`

https://ge.quarkus.io/c/nk5vgua7gpx2u/k4ldeu42numus/goal-inputs?expanded=WyJ2YmRzbTZ5ZmYzeG55LWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwiMmI1NTRwNDJxbmV6bS1hbm5vdGF0aW9ucHJvY2Vzc29ycGF0aCIsImhsbDZsbWYydnZodjYtYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCJobGw2bG1mMnZ2aHY2LWFubm90YXRpb25Qcm9jZXNzb3JQYXRoLTAtMCIsInR5bWNvcXM1bnNoZnktYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCJ0eW1jb3FzNW5zaGZ5LWFubm90YXRpb25Qcm9jZXNzb3JQYXRoLTAtMCIsImU3dmx6b2xwbXptY28tYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCI3YmR0bmxmdm03azZrLWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwiN2JkdG5sZnZtN2s2ay1hbm5vdGF0aW9uUHJvY2Vzc29yUGF0aC0xLTAiXQ#change-7bdtnlfvm7k6k-annotationProcessorPath-1-0-0

same for `integration-tests/kubernetes/maven-invoker-way/`:

### PR DESCRIPTION
**Pull request by gsmet**
Fixes https://github.com/quarkusio/quarkus/issues/33630

### CODE REVIEW

**Comment by gsmet** [comment]
Hey @maxandersen could we merge this one to start making progress on the Gradle build scan thingy?

**Comment by jprinet** [comment]
> Hey @maxandersen could we merge this one to start making progress on the Gradle build scan thingy?

Hi @gsmet, I am just confirming that this PR fixes most of the differences found in the `pom.xml`, there is however the `integration-tests/container-image/maven-invoker-way` module which is not considered.

Could you escape the `maven.home` and `native.image.path` for [those pom.xml files](https://ge.quarkus.io/c/k4ldeu42numus/nk5vgua7gpx2u/goal-inputs?expanded=WyJ2YmRzbTZ5ZmYzeG55LWFubm90YXRpb25wcm9jZXNzaW5ncmVzb3VyY2VzIiwidmJkc202eWZmM3hueS1hbm5vdGF0aW9uUHJvY2Vzc2luZ1Jlc291cmNlcy0wLTAiLCJ2YmRzbTZ5ZmYzeG55LWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwidmJkc202eWZmM3hueS1hbm5vdGF0aW9uUHJvY2Vzc29yUGF0aC0xLTAiXQ#change-vbdsm6yff3xny-annotationProcessingResources-0-0-0) as well?

**Review by maxandersen — APPROVED** [review]

**Comment by jprinet** [comment]
> Hi @gsmet, I am just confirming that this PR fixes most of the differences found in the `pom.xml`, there is however the `integration-tests/container-image/maven-invoker-way` module which is not considered.
> 
> Could you escape the `maven.home` and `native.image.path` for [those pom.xml files](https://ge.quarkus.io/c/k4ldeu42numus/nk5vgua7gpx2u/goal-inputs?expanded=WyJ2YmRzbTZ5ZmYzeG55LWFubm90YXRpb25wcm9jZXNzaW5ncmVzb3VyY2VzIiwidmJkc202eWZmM3hueS1hbm5vdGF0aW9uUHJvY2Vzc2luZ1Jlc291cmNlcy0wLTAiLCJ2YmRzbTZ5ZmYzeG55LWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwidmJkc202eWZmM3hueS1hbm5vdGF0aW9uUHJvY2Vzc29yUGF0aC0xLTAiXQ#change-vbdsm6yff3xny-annotationProcessingResources-0-0-0) as well?

Do you want me to take care of the remaining pom.xml in another PR @gsmet @maxandersen ?

**Comment by maxandersen** [comment]
Yeah. Lets do others in separate prs.

**Pull request merged**
