### PR TITLE
Hibernate reactive - configure HBM2DDL script generation

### PR DESCRIPTION
**Pull request by mkouba**
- follows up on https://github.com/quarkusio/quarkus/pull/16483

### CODE REVIEW

**Review by DavideD — COMMENTED** [review]
LGTM and it seems consistent with HIbernate ORM. Shouldn't you add some tests, though?

**Comment by mkouba** [comment]
> LGTM and it seems consistent with HIbernate ORM. Shouldn't you add some tests, though?

Sure. I can copy the test from the ORM module ;-).

**Review by DavideD — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
CI failure looks weird, I rebased the PR.

**Review by gsmet — APPROVED** [review]
Davide approved it!

**Pull request merged**
