### PR TITLE
Merge detached entity when deleting with panache CRUD repository

### PR DESCRIPTION
**Pull request by schmittjoaopedro**
This PR regards the issue #27184 to allow merging detached entities when calling `delete` with panache CRUD repository and non-transactional control.
In my current project, we don't control database transactions as all our endpoints always run a single SQL statement. I found that the remove method from panache could be improved to be in line with the implementation from Spring. I think it makes sense as it facilitates the migration from Spring to Quarkus.

So I'm proposing to handle unattached objects when calling the `remove(entity)`.

### CODE REVIEW

**Review by yrodiere — CHANGES_REQUESTED** [review]
> /cc @yrodiere pinged you as you probably know better if it's a good idea or not to do that. Personally it makes be a big nervous to do a merge automatically.

As far as I'm concerned, merging is an anti-pattern.

The main problem has to do with concurrent updates: when you detach an entity, then the entity is modified concurrently, and then you the merge detached entity back into a new session, merging brings the risk of setting properties back to their previous state (before the concurrent modification). So, really not great. There might be workarounds (maybe `@Version` detects those concurrent updates?), but as far as I know none is enabled by default.

Besides, merging generally is used in application that serialize entities directly to JSON, which is another serious problem IMO (use DTOs, people!).

So in general, if you're ask me whether we should use `merge`, or even facilitate merging... It'll be a clear "no" from me.

Now, in the specific case of an update... I suppose merging wouldn't hurt as much, since we're deleting the entity afterwards anyway.
But:

* Merging will still potentially trigger an extra database query to retrieve the initial state of the entity. Which is not great.
* Why merge at all, if we know the entity is going to get deleted? Why on earth would the content of the detached entity matter, if the entity is going to get deleted anyway? If it matters because of associations, wouldn't it make more sense to use cascade deletes, orphan removal, or even just to perform a merge manually before the delete?

So, I get the argument of improving compatibility with Spring Data, but let's exercise restraint: if we do everything like Spring Data, including what we disagree with, there's no point in using Panache instead of Spring Data anymore. Let's try to find another solution.

For example... if the only part of the detached entity that matters is its identifier, what we really should do is simply retrieve the identifier from the detached entity, then call `entityManager.getReference(type, id)`, then call `delete` on *that*. Would that work?

There doesn't seem to be an API to retrieve the ID from a detached entity, unfortunately, but that seems like something we could add to Hibernate ORM, or just implement in Panache using low-level Hibernate ORM code.

**Comment by yrodiere** [comment]
Actually, digging a bit, there *is* a way to get the identifier of a detached entity: `PersistenceUnitUtil.getIdentifier`.

So, something like this might work?

```
        Object toRemove = entity;
        if (!em.contains(toRemove)) {
            Class<?> type = Hibernate.getClass(toRemove);
            Object id = em.getEntityManagerFactory().getPersistenceUnitUtil().getIdentifier(toRemove);
            toRemove = em.getReference(type, id);
        }
        em.remove(em.contains(entity) ? entity : .merge(entity));
```

The main problem is it won't work with entities whose identifier contains associations (hey, another thing to rant about: associations within identifiers, what the hell).

A more robust solution would be to use that code (adapted from `org.hibernate.jpa.internal.PersistenceUnitUtilImpl`) to retrieve the identifier (preferably putting that code in Hibernate ORM itself...):

```
	public Object getIdentifier(SharedSessionContractImplementor session, Object entity) {
		if ( entity == null ) {
			throw new IllegalArgumentException( "Passed entity cannot be null" );
		}

		if ( entity instanceof HibernateProxy ) {
			return ((HibernateProxy) entity).getHibernateLazyInitializer().getInternalIdentifier();
		}
		else if ( entity instanceof ManagedEntity ) {
			EntityEntry entityEntry = ((ManagedEntity) entity).$$_hibernate_getEntityEntry();
			if ( entityEntry != null ) {
				return entityEntry.getId();
			}
			else {
				return getIdentifierFromPersister( session, entity );
			}
		}
		else {
			return getIdentifierFromPersister( session, entity );
		}
	}

	private Object getIdentifierFromPersister(SharedSessionContractImplementor session, Object entity) {
		Class<?> entityClass = Hibernate.getClass( entity );
		final EntityPersister persister;
		try {
			persister = sessionFactory.getMetamodel().entityPersister( entityClass );
			if ( persister == null ) {
				throw new IllegalArgumentException( entityClass.getName() + " is not an entity" );
			}
		}
		catch (MappingException ex) {
			throw new IllegalArgumentException( entityClass.getName() + " is not an entity", ex );
		}
		return persister.getIdentifier( entity, session );
	}
```

**Comment by schmittjoaopedro** [comment]
@yrodiere I got your point, one of the reasons I proposed this PR was to put the panache library in line with spring because when migrating from one framework to another it helps to have fewer surprises during the migration.

However, from my point of view, the biggest challenge was the behavior of the library when lacking a transactional context around the database operations. In our specific case, we don't use transactions in our app in many places because the database interactions are quite straightforward and we don't need to setup them, so it was a struggle to find out that some methods from panache can work fine without transaction boundaries (`save` for example) while other couldn't (`remove` in this case). So the proposal was to improve the library in this sense, this way you can expect a more homogeneous behavior from the lib when not bound to a transaction.

As you mentioned, the merge in an updated context can be messy if you have a race condition. However, because this entity is going to be deleted maybe it's worth having it. Otherwise, the framework users have to develop the logic around opening up a transaction, finding the entity, and finally calling the delete, just for the sake of the library implementation detail.

What's your take on this point of view?

**Comment by yrodiere** [comment]
I just noticed there's an even simpler solution: using `Session#getReference(Object)`, e.g.:

```
        em.remove(em.contains(entity) ? entity : em.unwrap(Session.class).getReference(entity));
```

Problem: at the moment, this is only possible in Hibernate ORM 6.x, where that method was introduced. We'll need to backport `Session#getReference(Object)` to ORM 5.6 if we want to go down that route.

**Comment by yrodiere** [comment]
> I'm ok with your solution, I don't like the idea of backporting code. I was just wondering on changing your proposal a bit, what do you think about the following approach?
> 
> ```java
> public void delete(Object entity) {
>         EntityManager em = getEntityManager(entity.getClass());
>         if (!em.contains(entity)) {
>             Class<?> type = Hibernate.getClass(entity);
>             Object id = em.getEntityManagerFactory().getPersistenceUnitUtil().getIdentifier(entity);
>             deleteById(type, id);
>         } else {
>             em.remove(entity);
>         }
>     }
> ```

That could be a start, but:

1. `deleteById` will actually load the entity. Yes, I know, it's counter-intuitive, but that's how it's currently implemented, I didn't make that decision :shrug:. So you're not getting much improvement from calling that, and actually you *could* get a performance hit in some cases compared to calling `getReference` to retrieve an (unloaded) instance of the entity.
2. As I mentioned before, `PersistenceUnitUtil#getIdentifier` will not always work, in particular with weird identifiers that contain associations.

**Comment by schmittjoaopedro** [comment]
I really don't feel comfortable duplicating code from hibernate @yrodiere .
I'd prefer not to have this PR instead in that case.
If you agree we can revoke this PR

**Comment by yrodiere** [comment]
> I really don't feel comfortable duplicating code from hibernate @yrodiere .

It would certainly be better to backport `getReference(Object)` to Hibernate ORM 5.6 and use that here.

>  If you agree we can revoke this PR

Yep, I agree. We should open another one once `getReference(Object)` is available in Hibernate ORM, and use that. We'll probably need a test, too :)

**Comment by schmittjoaopedro** [comment]
Indeed. Thanks for all the comments :)

**Comment by gsmet** [comment]
> It would certainly be better to backport getReference(Object) to Hibernate ORM 5.6 and use that here.

@yrodiere could you check with the ORM team if it could be an option?

The upgrade to 6 is probably a couple of months away.

**Comment by yrodiere** [comment]
> > It would certainly be better to backport getReference(Object) to Hibernate ORM 5.6 and use that here.
> 
> @yrodiere could you check with the ORM team if it could be an option?

Way ahead of you: https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/Getting.20reference.20to.20a.20potentially.20detached.20entity,  https://hibernate.atlassian.net/browse/HHH-15508

**Comment by gsmet** [comment]
@schmittjoaopedro see https://github.com/quarkusio/quarkus/pull/27928 which will be part of 2.14. Thanks for raising the issue and taking the time to create a PR.

**Pull request closed without merging**
