### PR TITLE
Adding AWS Secrets Manager

### PR DESCRIPTION
**Pull request by cmaluend**
# AWS Secrets Manager Extension
## Description
The goal of this extension is to make easy then integration with AWS Secrets Manager. The extension provides an annotation to inject the secret into a variable. Also, it is possible to inject the client and use it directly.

## Tasks
- [x] AWS Secrets Manager Client
- [x] AWS Secrets Manager Async Client
- [x] AWS Secrets Manager Annotation
- [ ] AWS Secrets Manager integration with DB Config [#6896](https://github.com/quarkusio/quarkus/issues/6896)

### Sync Client
```
    @Inject
    SecretsManagerClient client;
```
### Async Client
```
    @Inject
    SecretsManagerAsyncClient asyncClient;
```
## AWS Secrets Manager Annotation
Allows injecting a secret from AWS Secrets Manager directly to a variable. It supports plaintext and binary secrets.
```
    @AWSSecretsManager("a-secret-id")
    String secretId;
```

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi @cmaluend, thanks, I think it should be tied somehow with the credentials-spi as well, https://github.com/quarkusio/quarkus/tree/master/extensions/credentials.
CC @vsevel @gsmet

**Comment by sberyozkin** [comment]
Just wonder if this PR can contribute to resolving #6896 as well ? Would be great if it were possible :-).

**Comment by cmaluend** [comment]
> Just wonder if this PR can contribute to resolving #6896 as well ? Would be great if it were possible :-).

My goal was to be able to use AWS Secrets Manager in a native image. But, I think this is a good use case. I will take a look at it. This is my first contribution, probably I will have some questions.

**Comment by gsmet** [comment]
@marcinczeczko could you have a look at that one?
@vsevel you might be interested in this one too.

**Comment by marcinczeczko** [comment]
I'm on PTO till the end of July, so can look at this on Aug.

czw., 16 lip 2020, 11:15 użytkownik Guillaume Smet <notifications@github.com>
napisał:

**Comment by sberyozkin** [comment]
@cmaluend Thanks for the great contribution so far, and also considering to expose this engine as `CredentialsProvider`, it would be great because it will  let us verify the concept of Vault being replaceable by an alternative provider.
See these docs which Vincent did:
https://quarkus.io/guides/credentials-provider

Hopefully it will be quite straightforward given that you already have the working extension, `CredentialsProvider` impl may only need to get the [suggested](https://quarkus.io/guides/credentials-provider) configuration properties and delegate to `AWS` secrets manager client...
Cheers

**Comment by provcristianmaluenda** [comment]
@sberyozkin 
I took a quick look at the credential provider yesterday and I have been thinking that a better solution would be using the secret from AWS Secrets Manager directly in the `application.properties`. This will be more generic and other extensions will be able to use it (AMQP, Artemis, etc).

```
quarkus.secretsmanager.aws.secrets.mysecrets=cristian-db-pwd (1)
quarkus.datasource.password=${mysecrets} (2)
quarkus.qpid-jms.password=${mysecrets} (3)
amqp-password=${mysecrets} (4)
```

1) `mysecrets` will have a secret from AWS Secrets Manager. Where `cristian-db-pwd` is the AWS secret id.
2) The datasource will use the password stored in the variable `mysecrets`
3) The Artemis extension will use the password stored in the variable `mysecrets`
4) The AMQP extension will use the password stored in the variable `mysecrets`

I am asking in the forum how I can do this. I know SmallRye has [expression-interceptor](https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html#expression-interceptor) that I could use. But, I would like to know how is the "Quarkus" way to achieve this.

Does it make sense?

**Comment by cmaluend** [comment]
@sberyozkin 
I took a quick look at the credential provider yesterday and I have been thinking that a better solution would be using the secret from AWS Secrets Manager directly in the `application.properties`. This will be more generic and other extensions will be able to use it (AMQP, Artemis, etc).

```
quarkus.secretsmanager.aws.secrets.mysecrets=cristian-db-pwd (1)
quarkus.datasource.password=${mysecrets} (2)
quarkus.qpid-jms.password=${mysecrets} (3)
amqp-password=${mysecrets} (4)
```

1) `mysecrets` will have a secret from AWS Secrets Manager. Where `cristian-db-pwd` is the AWS secret id.
2) The datasource will use the password stored in the variable `mysecrets`
3) The Artemis extension will use the password stored in the variable `mysecrets`
4) The AMQP extension will use the password stored in the variable `mysecrets`

**Comment by sberyozkin** [comment]
@cmaluend but Agroal gets the passwords from CredentialsProvider. Perhaps `CredentialsProvider` needs some enhancements to support your more generic idea ? 
So for example, Agroal can get the passwords from Vault via CredentialsProvider. How would your proposal fit in ? Would `CredentialsProvider` have to be dropped ?

**Comment by vsevel** [comment]
> I took a quick look at the credential provider yesterday and I have been thinking that a better solution would be using

I will take a look at your ideas in the next few days.

**Comment by vsevel** [comment]
there are different use cases to consider:

1. programmatic api, which looks like your `SecretsManagerClient`, or the `VaultKVSecretEngine` in the vault extension
2. config source, which you seem to hint at in your https://github.com/quarkusio/quarkus/pull/10663#issuecomment-660125595, and has been implemented by the `VaultConfigSource` in the vault extension => see this [guide](https://quarkus.io/guides/vault-datasource#vault-microprofile-config-source)
3. credentials provider spi implementation, such as the `VaultCredentialsProvider`, which allows implementing advanced use cases (e.g. vault dynamic db credentials), and provide a standard way for a user to develop its custom secret store

from what I see you are tackling use cases 1 and 2. for the second one the correct approach is to create a config source. but there are a few challenges at the moment such as https://github.com/quarkusio/quarkus/issues/4848 (which should be improved with https://github.com/quarkusio/quarkus/issues/9991#issuecomment-649015892). If you do not develop a config source, then an alternative is to make your extension implement the `CredentialsProvider` interface. and then it will be automatically usable from extensions that can consume credentials from a `CredentialsProvider` (i.e. the different db connection pools at the moment).

hope this makes it clearer.

**Comment by cmaluend** [comment]
I will work on the CredetialsProvider this weekend.

**Comment by sberyozkin** [comment]
Hi @cmaluend How are you, have you had a chance to look at the `CredentialsProvider` update to finalize this PR ? May be it can male sense to follow up with another PR to make it simpler ? thanks

**Comment by gsmet** [comment]
Closing this one. Please reopen if you have some updates.

**Comment by mvrk57** [comment]
@cmaluend any news? Youre extension looks very interesting. I hope the pull request gets merged :-) I would use youre changes! :)

**Pull request closed without merging**
