### PR TITLE
Rename credentials-provider-type into credentials-provider-name

### PR DESCRIPTION
**Pull request by vsevel**
Follow up to #9552 and this specific https://github.com/quarkusio/quarkus/pull/9552#discussion_r430350205
Rename credentials-provider-type into credentials-provider-name.
Discuss whether the existing `name` should be renamed into `id`.

/cc @sberyozkin @geoand

### CODE REVIEW

**Comment by geoand** [comment]
Seems reasonable to me ( obviously since I'm the one that originally brought it up :laughing: )

**Comment by vsevel** [comment]
> Seems reasonable to me ( obviously since I'm the one that originally brought it up 😆 )

sure ;)

just to challenge before we close it, I think we should rename the [credentials provider name](https://github.com/vsevel/quarkus/blob/credentials_rename_field/extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceRuntimeConfig.java#L27) to `id` or `alias`, so that we do not confuse it with the [credentials provider bean name](https://github.com/vsevel/quarkus/blob/credentials_rename_field/extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceRuntimeConfig.java#L38). I could see people getting very confused (if `type` did not speak to you, at least it was different from `name`).
what do you think @geoand ?

**Comment by geoand** [comment]
Yeah, that makes sense to me. @sberyozkin WDYT?

**Review by gsmet — APPROVED** [review]
Let's go with it. It's better than before.

**Comment by gsmet** [comment]
I will backport it.

**Comment by vsevel** [comment]
> Let's go with it. It's better than before.

the good news is that if we want to go ahead and rename the `name` field to `id`, this won't be a breaking change. let me know if you think it is worthwhile. otherwise I will keep it as is.

**Pull request merged**
