### PR TITLE
Scheduler: fix Trigger#getNextFireTime() for cron-based jobs

### LINKED ISSUE #41717: quarkus-scheduler trigger getNextFireTime does not consider cron timezone
### Describe the bug

When using the Quarkus Scheduler, cron triggering works properly with respect to the configured timezone. However, when interrogating the scheduler for the "getNextFireTime", the timezone is not factored in. This results in incorrect behaviour, most problematically, is that it can return a next fire time in the past. 

See example class which demonstrates the results coming back.

### Expected behavior

When calling getNextFireTime from the scheduler, the Instant returned should match the actual nextFireTime defined by the cron AND timezone, not simply the cron as parsed in the local timezone. 

### Actual behavior

When calling getNextFireTime from the scheduler, the Instant returned treats the cron as if it had the local timezone.

### How to Reproduce?

```
package org.example;

import java.time.Instant;

import io.quarkus.runtime.StartupEvent;
import io.quarkus.scheduler.Scheduler;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;

@ApplicationScoped
public class TestScheduler {

  @Inject
  Scheduler scheduler;

  public void init(@Observes StartupEvent startupEvent) {

    scheduler.newJob("testJob1")
             .setCron("0 30 20 ? * * *")
             .setTimeZone("Europe/Berlin")
             .setTask(execution -> System.out.println("Job has run"))
             .schedule();

    scheduler.newJob("testJob2")
             .setCron("0 30 20 ? * * *")
             .setTimeZone("Europe/London")
             .setTask(execution -> System.out.println("Job has run"))
             .schedule();

    Instant nextFireTime1 = scheduler.getScheduledJob("testJob1").getNextFireTime();
    Instant nextFireTime2 = scheduler.getScheduledJob("testJob2").getNextFireTime();

    System.out.println("=============================================================");
    System.out.println("NextFireTimes:");
    System.out.println("TestJob1(Berlin)=" + nextFireTime1);
    System.out.println("TestJob2(London)=" + nextFireTime2);
    System.out.println("compareTo result=" + nextFireTime1.compareTo(nextFireTime2) + "    <-- should be greater than 0");
    System.out.println("=============================================================");
    // These two times should be different as they are crons with same local time but diff timezone, so UTC time expressed by the Instant should be different.
  }

}
```

### Output of `uname -a` or `ver`

Linux alan-test-redis-cacher-56d9f6f6d4-ssstk 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #41717

### CODE REVIEW

**Comment by mkouba** [comment]
@alanmscott it would be great if you could test this PR!

**Comment by alanmscott** [comment]
Hi @mkouba 

I've had a test with the new SimpleScheduler. Whilst it is casting the Instant into the value correctly, it still has the problem where it can return a "nextFireTime" in the past.

E.g.
```
USING: cron = "0 35 12 ? * * *";

2024-07-09 11:58:25,719 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) NextFireTimes:
2024-07-09 11:58:25,721 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob1(UTC     )=2024-07-09T12:35:00Z / 2024-07-09T12:35:00Z[UTC]
2024-07-09 11:58:25,722 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob2(London  )=2024-07-09T11:35:00Z / 2024-07-09T12:35:00+01:00[Europe/London]
2024-07-09 11:58:25,722 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob3(Berlin  )=2024-07-09T10:35:00Z / 2024-07-09T12:35:00+02:00[Europe/Berlin]
2024-07-09 11:58:25,722 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob4(Istanbul)=2024-07-09T09:35:00Z / 2024-07-09T12:35:00+03:00[Europe/Istanbul]
2024-07-09 11:58:25,722 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) compareTo result1-2=1     <-- should be greater than 0
2024-07-09 11:58:25,723 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) compareTo result2-3=1     <-- should be greater than 0
2024-07-09 11:58:25,723 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) compareTo result3-4=1     <-- should be greater than 0
```

As you can see, the local time (London time) is 09/07/2024 11:58. 
The UTC and London `nextFireTime` is perfectly correct, but for the others, it shows an almost sensible time, but it's actually in the past. 
i.e. at 11:58 in London, the time in Berlin is 12:58, so the nextFireTime should be **10**/07/2024 12:35
Similarly, for Istanbul, the time is 13:58, so the nextFireTime should **10**/07/2024 13:35.


Is perhaps a problem with the value being returned by the underlying cronutils library?

**Comment by mkouba** [comment]
> Is perhaps a problem with the value being returned by the underlying cronutils library?

Hi @alanmscott, thanks a lot for testing this PR!

You're right and I don't think it's the problem of cronutils. It's the way we adapt the _next fire time_ because we retain the local date-time and change the timezone. Which is not correct. Let me try to fix that. Oh, timezones :facepalm:.

**Comment by mkouba** [comment]
@alanmscott Ok, another attempt. Note that I've removed the comparison of instants because it really depends on the current time.

**Comment by alanmscott** [comment]
I think the latest change looks good. It's returning what I'd expect for the test harness:

```
USING Cron = "0 06 17 ? * * *";

2024-07-09 16:05:36,103 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) NextFireTimes:
2024-07-09 16:05:36,106 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob1(UTC     )=2024-07-09T17:06:00Z / 2024-07-09T17:06:00Z[UTC]
2024-07-09 16:05:36,107 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob2(London  )=2024-07-09T16:06:00Z / 2024-07-09T17:06:00+01:00[Europe/London]
2024-07-09 16:05:36,107 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob3(Berlin  )=2024-07-09T15:06:00Z / 2024-07-09T17:06:00+02:00[Europe/Berlin]
2024-07-09 16:05:36,107 INFO  [org.exa.TestScheduler] (Quarkus Main Thread) TestJob4(Istanbul)=2024-07-10T14:06:00Z / 2024-07-10T17:06:00+03:00[Europe/Istanbul]
```

Which is right. 17:06 for London = 18:06 for Berlin, so that is still "today", but has passed for Istanbul which is now "tomorrow". 
I noted that the trigger still executed for "job3" also, demonstrating the triggering is unchanged and correct.

Fantastic, thank you!!!

**Review by manovotn — APPROVED** [review]

**Pull request merged**
