### PR TITLE
Change resteasy.gzip to ConfigGroup; Add resetasy.gzip.max-input config

### PR DESCRIPTION
**Pull request by jimma**
- Change resteasy gzip as a CongGroup
- Allow to configure resteasy gzip maxInput

### CODE REVIEW

**Review by rsvoboda — COMMENTED** [review]
https://github.com/resteasy/Resteasy/blob/master/resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java lists quite a lot of configuration parameters.

Do you plan to expose more of them?

Zulip chatroom / Google Groups are good place to discuss what the right level of exposure should be.

**Comment by jimma** [comment]
> https://github.com/resteasy/Resteasy/blob/master/resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java lists quite a lot of configuration parameters.
Do you plan to expose more of them?

Yes. This could be the future to do things. For now we provide gzip configuration, we need to provide configuration to limit the max gzip input too.

> Zulip chatroom / Google Groups are good place to discuss what the right level of exposure should be.

Thanks. I'll post there if have questions and doubts about this task.

**Comment by jimma** [comment]
@stuartwdouglas @rsvoboda  Can you please review ?

**Comment by rsvoboda** [comment]
Code change looks good to me. I'd like to see feedback from others too.

@jimma any chance you could add a test for gzip+max-input ?

By Google Groups discussion I didn't mean discussion around this PR, but more general discussion which RESTEasy configuration parameters should be exposed via Quarkus. https://github.com/resteasy/Resteasy/blob/master/resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java lists quite a lot of configuration parameters.
I don't thing it's necessary or wise to expose all of them, but we should have some discussion around it. @asoldano wdyt ?

**Comment by jimma** [comment]
> Code change looks good to me. I'd like to see feedback from others too.
   @jimma any chance you could add a test for gzip+max-input ?

This is  a small change to modify gzip to config group and add this configuration to servletContextParams . I saw there is already test for @ConfigGroup and functionality tests are in Resteasy : https://github.com/resteasy/Resteasy/blob/master/testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip.  So I don't think we need add a test.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Looks good to me, but needs a rebase.

I agree that the value of tests for this sort of thing is borderline. Presumably the actual functionality is tested in the RESTeasy test suite, and config functionality itself is tested elsewhere.  That said not having a test means that if we refactored and this code went missing it would not be obvious.

**Comment by jimma** [comment]
@stuartwdouglas  Rebased and added a test. Please review again.

**Pull request merged**
