### PR TITLE
Update importmap to 1.0.11

### PR DESCRIPTION
**Pull request by phillip-kruger**
This contains @gsmet classloading fix

### CODE REVIEW

**Comment by gsmet** [comment]
Ah let me add my work to your PR, then :).

**Comment by gsmet** [comment]
@phillip-kruger I let you have a look at the commit I added, it makes use of the new method I introduced - that was all part of a plan \o/.

**Review by gsmet — APPROVED** [review]

**Review by phillip-kruger — COMMENTED** [review]
@gsmet as long as the importmap looks the same we are good !

**Comment by phillip-kruger** [comment]
@gsmet - This breaks dev-ui namespace relocations. I am providing a fix for the new CR

**Pull request merged**
