### PR TITLE
Fix a typo in the BC CredentialsProvider test

### PR DESCRIPTION
**Pull request by sberyozkin**
@rsvoboda Spotted a typo in the test - the reason it works without a typo is because currently the default keystore password is `password` which matches the `server-keystore.jks` password. 
I've confirmed that changing either `keystore-password` or `truststore-password` keys in `SecretProvider` fails the tests.
For whatever reasons, if I try to change the `server-keystore.jks` password (just to ensure that no default keystore value is picked up), it messes up the `server-keystore.jks` and Vertx can't read it, with or without `CredentialsProvider`.
Rostislav, if you'd like, please confirm independently that changing the passwords in `SecretProvider` causes a failure

### CODE REVIEW

**Comment by sberyozkin** [comment]
@rsvoboda I copied the existing keystore from one of the vertx-http tests where the secret is `secret` so it makes sure the default `password` is not used and therefore `SecretProvider` is effective

**Comment by rsvoboda** [comment]
Good, just was about to ask why not generate new keystore and truststore with different password.

**Comment by rsvoboda** [comment]
> the default keystore password is password

Why do we have the default password at all?

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
I was able to set new password for existing `server-keystore.jks` this way:

```
keytool -list -v -keystore server-keystore.jks -storepass password

keytool -storepasswd -new my-new-password -keystore server-keystore.jks -storepass password
keytool -keypasswd -alias server -keypass password -new my-new-password -keystore server-keystore.jks -storepass my-new-password
```

Changes to the code:
```diff
diff --git a/integration-tests/bouncycastle-jsse/src/main/java/io/quarkus/it/bouncycastle/SecretProvider.java b/integration-tests/bouncycastle-jsse/src/main/java/io/quarkus/it/bouncycastle/SecretProvider.java
index 9eed67c402..ddd70260fe 100644
--- a/integration-tests/bouncycastle-jsse/src/main/java/io/quarkus/it/bouncycastle/SecretProvider.java
+++ b/integration-tests/bouncycastle-jsse/src/main/java/io/quarkus/it/bouncycastle/SecretProvider.java
@@ -15,7 +15,7 @@ public class SecretProvider implements CredentialsProvider {
     @Override
     public Map<String, String> getCredentials(String credentialsProviderName) {
         Map<String, String> creds = new HashMap<>();
-        creds.put("keystore-password", "password");
+        creds.put("keystore-password", "my-new-password");
         creds.put("truststore-password", "password");
         return creds;
     }
diff --git a/integration-tests/bouncycastle-jsse/src/main/resources/application.properties b/integration-tests/bouncycastle-jsse/src/main/resources/application.properties
index 40f0793cd8..3a28e5d458 100644
--- a/integration-tests/bouncycastle-jsse/src/main/resources/application.properties
+++ b/integration-tests/bouncycastle-jsse/src/main/resources/application.properties
@@ -1,7 +1,7 @@
 quarkus.security.security-providers=BCJSSE

 quarkus.http.ssl.certificate.key-store-file=server-keystore.jks
-quarkus.http.ssl.certificate.key-store-password-key=key-store-password
+quarkus.http.ssl.certificate.key-store-password-key=keystore-password
 quarkus.http.ssl.certificate.trust-store-file=server-truststore.jks
 quarkus.http.ssl.certificate.trust-store-password-key=truststore-password
 quarkus.http.ssl.certificate.credentials-provider=custom
```

**Comment by sberyozkin** [comment]
@rsvoboda Thanks, yeah I think I did it the same way except that I let the tool ask for the current password. I could then confirm with `keytool` the new password was in place, but Vert.x would just fail. Strange, may be I missed something

**Pull request merged**
