### PR TITLE
Fix preserve next fire time of rescheduled job in quartz 

### LINKED ISSUE #21455: Quarkus quartz should not reschedule jobs on start
### Describe the bug

Bug introduced by https://github.com/quarkusio/quarkus/issues/20538

Anytime quarkus starts it will reschedule jobs, not matter if the job config changed or not.
It's a tough decision, at best it should only detect changes and WARN, nothing else.
This can have serious collateral damages depending on what your jobs are doing.

If you are cleaning up your data once a year, you don't want that to be re initialized and triggered every time you restart the app or scale up your cluster.

### Expected behavior

Do not reschedule jobs, WARN or maybe improve the dev tools but this is too dangerous.

### Actual behavior

All jobs are rescheduled on start.

### How to Reproduce?

Pick any quartz based clustered app.
Create a job running every 5 sec for example.

Request the db for
select * from qrtz_simple_triggers and select * from qrtz_triggers

Restart the app and check the table again.
All triggers, executions are reset, ignoring past execution and, most important, the expected and persistent next_fire_time on qrtz_triggers.

### Output of `uname -a` or `ver`

no impact

### Output of `java -version`

no impact

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

since 2.3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

no impact

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ashwinair**
Fixes #21455

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

I'll let @machi1990 and @mkouba comment on the change, but we will certainly need the commits merged.

Thanks

**Comment by gsmet** [comment]
I squashed the 2 commits.

**Comment by gsmet** [comment]
@mkouba if you could have a quick look, I think it would be a good candidate for 2.6.2.Final.

**Comment by mkouba** [comment]
The solution is probably OK but I'd like @machi1990 to comment on this one as he's our "Quartz clustered jobs" expert ;-)

**Review by machi1990 — APPROVED** [review]
lgtm, thanks @ashwinair for the PR.

@apat59, this should fix the issue your reported in https://github.com/quarkusio/quarkus/issues/21455.

**Pull request merged**
