### PR TITLE
Don't run postgres tests by default

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by geoand** [comment]
Shouldn't we do this for the rest of the `reactive-mysql-client` as well?

**Comment by stuartwdouglas** [comment]
yes, that must run after the next failure I hit so I did not notice.

**Comment by stuartwdouglas** [comment]
That can be a seperate PR thought

**Comment by stuartwdouglas** [comment]
Maybe we need a basic mvn install CI test with nothing running to make sure we don't break this again

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
I approved the PR, feel free to proceed as you see fit :)

**Comment by gsmet** [comment]
I'm not sure about that one. IIRC, the reactive-pg-client tests are designed to "work" without any PostgreSQL instance.

**Comment by stuartwdouglas** [comment]
well they don't

**Comment by stuartwdouglas** [comment]
They work on CI because we already have PG running, if you run them locally they fail

**Pull request merged**
