### PR TITLE
Configure Mutiny infra to use Quarkus thread pool

### LINKED ISSUE #9550: Configure Mutiny thread pools using the Quarkus ones
**Description**

Related to https://github.com/smallrye/smallrye-mutiny/issues/144.

Right now Mutiny is starting its own minimal thread pool for operators manipulating times.
The default head pool should be the quarkus one.

### PR DESCRIPTION
**Pull request by cescoffier**
@stuartwdouglas You mentioned it last week. Here it is.

### CODE REVIEW

**Comment by cescoffier** [comment]
Something is wrong, I will have a look

**Comment by cescoffier** [comment]
A class has been renamed where it should not have been renamed. I will fix it tomorrow.

**Comment by cescoffier** [comment]
Other updates would require the update to Mutiny 0.5.2, so if we could get a review it would be great.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by geoand** [comment]
:+1:

**Pull request merged**
