### PR TITLE
CompletableFuture smart dispatch support

### LINKED ISSUE #17037: Vertx-web return Vertx Future support.
## Description

Compared to mutiny, I prefer Vertx's Promise and Future. Mutiny takes more time to learn and also affects code readability.

```java
    @Route(path = "/", methods = HttpMethod.POST,
        produces = "application/json",
        consumes = "application/json")
    public Future<String> promise(@Body JsonObject body) {
        Promise<String> promise = Promise.promise();
        //do somethings.
        return promise.future();
    }
```

The above code does not produce the expected result, it will respond:

```json
{
    "complete": true
}
```

*aomsweet*
*Best Regards*

### LINKED ISSUE #30133: CompletableFuture smart dispatch support
### Description

https://quarkus.io/blog/resteasy-reactive-smart-dispatch/ states which types are automagically detected to correctly dispatch the endpoint requests into I/O thread or the blocking thread pool: currently `CompletionStage` is handled on the I/O thread, but `CompletableFuture` not, that's a bit unexpected from a user perspective.

### Implementation ideas

Reuse most of the existing setup to perform `CompletionStage` detection and enhance tests to verify it's correctly dispatched on the I/O threads.

### PR DESCRIPTION
**Pull request by franz1981**
- resolves #30133

### CODE REVIEW

**Comment by franz1981** [comment]
@cescoffier Not sure I made it right, I see lot of duplicate codes :/ 
I will create a separate issue in case it seems a good use case

The reason why I've done it is on this [Quarkus profiling workshop snippet](https://github.com/franz1981/quarkus-profiling-workshop/blob/3c7a8d70947a8bfee75e7906649fcf852de6c932/src/main/java/profiling/workshop/time/CachedTimeResource.java#L37) where I've been forced to use `CompletionStage` in order to use the I/O threads, while failing (ie using the blocking thread pool) with the actual concrete type `CompletableFuture`.

**Comment by cescoffier** [comment]
What's the rationale? We strongly recommend Uni in this case (for plenty of reason including context handling).

**Comment by cescoffier** [comment]
So basically, do you have the same issue when using Uni instead of CS?

**Comment by franz1981** [comment]
> So basically, do you have the same issue when using Uni instead of CS?

The issue is related of how we recognize non-blocking endpoint: CS isn't CF and it's going to use a thread pool for that, that's unexpected from a user pov

**Comment by cescoffier** [comment]
Ah ok, it makes sense (even if I would prefer users to move away from CS/CF as fast as they can)

**Comment by franz1981** [comment]
> Ah ok, it makes sense (even if I would prefer users to move away from CS/CF as fast as they can)

Yep and still my changes are not correctly handling polymorphism there (if someone impl their own CompletionStage children my changes won't help fixing it), given that's not an high prio thing I'm happy to close it unless can still be useful to someone other then me and Mario for the workshop: let me know and I can happily close this ;)

**Comment by geoand** [comment]
Also, do we really want to do this when RESTEasy Reactive already has support for it?

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
CI is complaining :(

**Comment by franz1981** [comment]
> CI is complaining :(

yep, let me check what going on

**Comment by franz1981** [comment]
@geoand it seems that `ServletSimpleRestTestCase::testAsync`   is failing to run on the I/O thread even if I switch to `CompletionStage` type on the endpoint signature...is it supposed to happen? @cescoffier too

**Comment by geoand** [comment]
Servlet is always meant to run on a worker thread

**Comment by geoand** [comment]
Yeah, that makes sense

**Comment by geoand** [comment]
I fixed the formatting issue and rebased the PR onto main.

**Pull request merged**
