### PR TITLE
Add excluded artifacts for Spring

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
I think these should actually be in the relevant spring extensions. You should only exclude something if you are providing a replacement.

**Comment by geoand** [comment]
PR updated, thanks for the info!

**Review by stuartwdouglas — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
Maybe we should also add them to the banned dependencies of the enforcer?

**Comment by geoand** [comment]
@gsmet done

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Perfect, thanks! Let's wait for CI!

**Comment by geoand** [comment]
CI failure is totally unrelated

**Pull request merged**
