### PR TITLE
Registry client config (de)serialization tests and fixes

### PR DESCRIPTION
**Pull request by aloubyansky**
Adding tests and fixes for the registry (devtools) config serialization and deserialization.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Excellent!

**Comment by aloubyansky** [comment]
Line endings on Windows...

**Comment by aloubyansky** [comment]
Oh, @geoand
````
Error:  Failed to execute goal io.quarkus:quarkus-bootstrap-maven-plugin:999-SNAPSHOT:extension-descriptor (generate-extension-descriptor) on project quarkus-resteasy-reactive-kotlin: Deployment artifact io.quarkus:quarkus-resteasy-reactive-kotlin-deployment::jar:999-SNAPSHOT is missing the following dependencies from its configuration: io.quarkus:quarkus-smallrye-context-propagation-deployment::jar, io.quarkus:quarkus-vertx-core-deployment::jar, io.quarkus:quarkus-netty-deployment::jar, io.quarkus:quarkus-jsonp-deployment::jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-bootstrap-maven-plugin:999-SNAPSHOT:extension-descriptor (generate-extension-descriptor) on project quarkus-resteasy-reactive-kotlin: Deployment artifact io.quarkus:quarkus-resteasy-reactive-kotlin-deployment::jar:999-SNAPSHOT is missing the following dependencies from its configuration: io.quarkus:quarkus-smallrye-context-propagation-deployment::jar, io.quarkus:quarkus-vertx-core-deployment::jar, io.quarkus:quarkus-netty-deployment::jar, io.quarkus:quarkus-jsonp-deployment::jar
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
````

**Comment by aloubyansky** [comment]
I bet you used `-Dquickly` ;)

**Comment by aloubyansky** [comment]
Hm, it looks like it actually builds locally.

**Comment by geoand** [comment]
The thing is that CI is passing for my PR that builds onto the one in question

**Comment by aloubyansky** [comment]
Interesting. AFAICS, the error is legit.

**Comment by geoand** [comment]
How do we get around it is the question :)

**Comment by aloubyansky** [comment]
Yes, me neither. I'll look into this. But just by looking at it, it looks like the deployment module is missing a dependency on `quarkus-resteasy-reactive-common-deployment`

**Pull request merged**
