### PR TITLE
outputFile and appendOutput params for quarkus:dependency-tree

### PR DESCRIPTION
**Pull request by aloubyansky**
These two options allow redirecting the dependency tree output to a file, similar to what `dependency:tree` supports.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
CI failure is fixed in https://github.com/quarkusio/quarkus/pull/20682

**Comment by rsvoboda** [comment]
@aloubyansky is there PR with update for the docs?

**Comment by aloubyansky** [comment]
@rsvoboda i opened https://github.com/quarkusio/quarkus/pull/21622

**Comment by rsvoboda** [comment]
Thanks!

**Pull request merged**
