### PR TITLE
exclude spotbugs and findbugs

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Please add them to the banned dependencies in the build-parent pom. Thanks!

**Comment by michalszynkiewicz** [comment]
I added it and it turns out the enforcer fails on test dependencies :(
I will exclude the test ones too

**Comment by gsmet** [comment]
You can specifically allow things for test dependencies, there is an example at the bottom of the banned dependencies IIRC.

**Comment by michalszynkiewicz** [comment]
should be excluded everywhere now :)

**Comment by michalszynkiewicz** [comment]
So it seems that (unlike plain java), in some cases Quarkus requires declared annotations to be available. 
An example is `SpringDIProcessor` that assumes such annotations are in the index.
I will close this PR now. We can revisit later.

**Pull request closed without merging**
