### PR TITLE
Make mutiny version of pool use the already configured vertx pool

### LINKED ISSUE #39047: Reactive pg datasource with enabled health check opens more connections than configured
### Describe the bug

We use the reactive postgresql datasource, with configured max-size and enabled datasource health check.

### Expected behavior

The maximum number of open connections are equals the configured number.

### Actual behavior

The number of open database connections increases to twice the maximum number configured.

### How to Reproduce?

1. Create a simple app with reactive postgresql datasource and datasource health check (quarkus create app  --extension='resteasy-reactive,reactive-pg-client,resteasy-reactive-jackson,smallrye-health')
2. Configure max-size (quarkus.datasource.reactive.max-size=5)
3. Enable health check (quarkus.datasource.health.enabled=false)
4. Create an endpoint with database access
5. Call this endpoint and the health endpoint a view times (for example with apache benchmark)
6. Check the open connections in your database

Small reproducer can be found here: https://github.com/dgewiss/quarkus-reactive-health-check-test

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 21 2023-09-19 LTS

### Quarkus version or git rev

3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

This workaround works for me:

Disable the datasource health check and use a own implementation of ReactivePgDataSourcesHealthCheck.

The difference to the original implementation is that `io.vertx.mutiny.pgclient.PgPool` is used to select the connection pool instead of `io.vertx.pgclient.PgPool`. The delegate is then passed to the ReactiveDatasourceHealthCheck.

This workraound is also incuded in the reproducer.

### PR DESCRIPTION
**Pull request by geoand**
Before this, the mutiny version would recreate the delegate instead of reusing the existing bean

- Fixes: #39047

### CODE REVIEW

**Review by tsegismont — APPROVED** [review]
LGTM, thank you @geoand !

**Comment by geoand** [comment]
Thanks for checking!

**Comment by tsegismont** [comment]
@geoand @gsmet I believe this is critical enough to be fixed in all supported versions, wdyt?

**Comment by geoand** [comment]
That means basically only 3.8 (as that will be LTS) and 3.2 isn't affected

**Review by gsmet — APPROVED** [review]
It makes sense to backport it but that will be for 3.8.3. 3.8.2 is already on its way.

**Pull request merged**
