### PR TITLE
Support Flyway ignoreFutureMigrations config

### LINKED ISSUE #15242: Add support for Flyway "ignore future migrations"
**Description**
Flyway can be configured to ignore future migrations. Support for missing migrations already has been added in https://github.com/quarkusio/quarkus/issues/11421 . Ignoring future migrations is useful in rollback scenarios when you have backwards compatible database migrations (that you need anyways for zero-downtime deployments) and encounter an issue that is related to code changes. Rolling back would solve it, but flyway would fail starting because it sees migrations applied it does not know.

**Implementation ideas**
Add a new boolean-typed `quarkus.flyway.ignore-future-migrations` configuration property (defaulting to `false` as in Flyway).

### PR DESCRIPTION
**Pull request by lenalebt**
Fixes #15242

### CODE REVIEW

**Comment by lenalebt** [comment]
I did have some trouble downloading some dependencies (may be my bad internet connection; it's still loading...), so I did not yet compile locally. Will fix any CI issues that may pop up.

**Review by gsmet — APPROVED** [review]
Thanks!

**Review by gastaldi — APPROVED** [review]
Excellent! Thank you!

**Comment by lenalebt** [comment]
Thanks for your very quick response & merge/approval :).

**Pull request merged**
