### PR TITLE
Scope of java env vars for OpenShift builds

### LINKED ISSUE #12894: deployment-target=knative not working with Quarkus 1.9
`quarkus.kubernetes.deployment-target=knative` not working with Quarkus 1.9, works fine with Quarkus 1.8.2.Final / 1.7.5.Final. Running on OpenShift 4.5 with OpenShift Serverless.

The main message I see in log of the final pod is `ERROR Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 JARs found in /deployments (1 expected)`

The problem I see is that with knative `/deployments` is still looked at while the path should be `/deployments/target`

When I switch to `quarkus.kubernetes.deployment-target=openshift` application starts properly from `/deployments/target`

reproducer:
```
oc new-project rsvoboda

rm -rf getting-started
mvn io.quarkus:quarkus-maven-plugin:1.9.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello" \
    -Dextensions="openshift, smallrye-health"
cd getting-started

cat > src/main/resources/application.properties <<EOF
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.container-image.group=rsvoboda
quarkus.kubernetes.deployment-target=knative
quarkus.kubernetes-client.trust-certs=true
EOF

mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus-plugin.version=1.8.2.Final -Dquarkus.platform.version=1.8.2.Final

==> application gets available, e.g. http://getting-started-rsvoboda.apps.ocp45.dynamic.quarkus/hello in my case

mvn clean package -Dquarkus.kubernetes.deploy=true

==> application is not available, CrashLoop Error in console
```

Error from pod:
```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
[0;31mERROR Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 JARs found in /deployments (1 expected)[0m
INFO exec  java -javaagent:/opt/jboss/container/jolokia/jolokia.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar   
Error: -jar requires jar file specification
Usage: java [options] <mainclass> [args...]
           (to execute a class)
  ...
```

Tried to set `quarkus.s2i.jar-directory` and `quarkus.openshift.jar-directory` but it didn't help in my experiments.

### PR DESCRIPTION
**Pull request by iocanel**
Fixes: #12894

### CODE REVIEW

**Review by rsvoboda — CHANGES_REQUESTED** [review]
Using sample app from https://github.com/quarkusio/quarkus/issues/12894#issue-727958359 with Quarkus master patcheched with changes from this PR
command: `mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus-plugin.version=999-SNAPSHOT -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.platform.artifact-id=quarkus-bom`

I see `No Deployment found under: /Users/rsvoboda/tmp/getting-started/target/kubernetes/knative.yml` error

Shouldn't be `DeploymentConfig` searched for?

Details:
```
[INFO] [io.quarkus.container.image.openshift.deployment.OpenshiftProcessor] Push successful
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Deploying to knative server: https://api.ocp45.dynamic.quarkus:6443/ in namespace: rsvoboda.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Service getting-started.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:54 min
[INFO] Finished at: 2020-10-24T11:14:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: java.lang.IllegalStateException: No Deployment found under: /Users/rsvoboda/tmp/getting-started/target/kubernetes/knative.yml
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.lambda$deploy$6(KubernetesDeployer.java:190)
[ERROR] 	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:189)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:102)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]
```

**Comment by iocanel** [comment]
> Shouldn't be `DeploymentConfig` searched for?
No, it should be looking for a `Service` (knative serving service).

**Comment by iocanel** [comment]
@rsvoboda push a fix for the Service thing. I am not sure if there are other issues down the road. ATM I don't have access to a Knative enabled Openshift cluster making it a bit hard to test.

**Comment by rsvoboda** [comment]
I will try it. I think Max had cluster. You should have one for sure, dev team can ask for PSI capacity to run OpenShift clusters, the price is to maintain it.

**Comment by rsvoboda** [comment]
And Max and Jason were looking into a solution to provide clusters on demand, please ping them to see where it is.

**Comment by rsvoboda** [comment]
So my cluster is broken and new one can't be provisioned because of issues in OpenStack / PSI :( Will look into it once the env issues get resolved, probably tmr.

**Comment by rsvoboda** [comment]
@iocanel did you succeeded in finding the cluster?

**Comment by iocanel** [comment]
> @iocanel did you succeeded in finding the cluster?
Ended up using crc and it works ok for now. The pull request works great!

**Comment by rsvoboda** [comment]
Have bad news for you. There is side effect of your PR.
I changed the `quarkus.kubernetes.deployment-target` to `openshift` an I get an error:

```
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Service getting-started.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: ImageStream getting-started.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: ImageStream openjdk-11-rhel7.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: BuildConfig getting-started.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: DeploymentConfig getting-started.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:43 min
[INFO] Finished at: 2020-10-27T15:24:47+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: java.lang.IllegalStateException: No Deployment found under: /Users/rsvoboda/tmp/getting-started/target/kubernetes/openshift.yml
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.lambda$deploy$6(KubernetesDeployer.java:190)
[ERROR] 	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:189)
```

**Comment by iocanel** [comment]
Hmmm, it looks more like the next error down the line. Will fix it ASAP.

**Comment by iocanel** [comment]
@rsvoboda: This was a regression introduced in https://github.com/quarkusio/quarkus/pull/12655/files#diff-2f7f8b1e6f4a44f6f156a44d9a60ec9f4a233e7874e8059fb0c627771a505fc4R62. Pushed a fix for that.

**Review by rsvoboda — APPROVED** [review]
Approving, knative target works well. openshift target is handled in another PR

**Comment by rsvoboda** [comment]
Ups, misunderstood your comment, checking now

**Review by rsvoboda — APPROVED** [review]
Both knative and openshift target worked for me

**Comment by gsmet** [comment]
This one is not really backportable. Everything has changed.

**Pull request merged**
