### PR TITLE
Create RESTEasy JSON Jackson Codestart

### PR DESCRIPTION
**Pull request by jantosi**

### CODE REVIEW

**Comment by ia3andy** [comment]
@jantosi Thanks for this PR!!

I am working on making tests easier for example codestarts (but not done yet), and I didn't have time to test the generated code yet. 

Until then, to check your code, you can generate the project by creating a new test like this one:
https://github.com/quarkusio/quarkus/blob/master/integration-tests/devtools/src/test/java/io/quarkus/devtools/codestarts/QuarkusCodestartRunIT.java#L91

```java
generateProjectRunTests("maven", "java", Collections.singletonList("resteasy-jackson-example"),
                Collections.emptyMap());
```

It will be generated in `integration-tests/devtools/target/codestarts-run-test/something`, then you can flip the buildtool and language easily ;-) or create different tests.

I will come up with a better solution next week ;-)

**Review by ia3andy — COMMENTED** [review]
Nice!! @jantosi Could you rebase on master and squash it to 1 commit please :)

**Comment by jantosi** [comment]
I can't rebase my `master` easily (protected branch) - I'll submit a new PR and link it here.

**Comment by jantosi** [comment]
See PR https://github.com/quarkusio/quarkus/pull/12494 instead.

**Pull request closed without merging**
