### PR TITLE
Make the name of the configuration adoc file configurable 

### LINKED ISSUE #36189: Make the name of the configuration adoc file configurable
### Description

Currently the name of the AsciiDoc file with the docs of the individual properties is transformed from `@ConfigRoot.name()` . E.g. if the name() is `quarkus.cxf` then the generated file will be `<tree-root>/target/asciidoc/generated/config/quarkus-cxf.adoc`. This works well as long as the names are unique throughout the extensions hosted within the current source tree or as long as one wants to output the docs of the properties coming from all extensions using the same `@ConfigRoot.name()` to the same adoc file.

In Quarkus CXF this is not what we want. We have several extensions which enhance the main `quarkus.cxf` config on lower levels of the configuration tree. 

The main config in the core extension has naturally `@ConfigRoot(name = "quarkus.cxf")`. It allows basic configuration of clients and services via 

```
quarkus.cxf.client.myClient.wsdl = ...
quarkus.cxf.client.myClient.client-endpoint-url = ...
...
quarkus.cxf.endpoint."/hello".implementor = ...
```

But then there is a couple of other extensions, which also need to have `@ConfigRoot(name = "quarkus.cxf")` because they hook somewhere deeper in the config hierarchy. E.g. our logging extension allows the following:

```
quarkus.cxf.client.myClient.logging.enabled = true
quarkus.cxf.client.myClient.logging.pretty = true
...
quarkus.cxf.endpoint."/hello".logging.enabled = true
quarkus.cxf.endpoint."/hello".logging.pretty = true
```

At the same time, we want to have two separate property adoc files for the core extension and for the logging extension because we want to include them on two separate extension pages.

 This is currently not possible, because all property doc chunks land in `<tree-root>/target/asciidoc/generated/config/quarkus-cxf.adoc`

### Implementation ideas

Add a new attribute on `@ConfigRoot` specifying the name of the destination adoc file.

A PR follows.

### PR DESCRIPTION
**Pull request by ppalaga**
fix #36189

### CODE REVIEW

**Comment by ppalaga** [comment]
It looks like the JVM Tests - JDK 11 job was killed midair. Not sure it needs a restart. All other JDK jobs passed.

**Comment by ppalaga** [comment]
Any feedback on this one?

**Review by gsmet — COMMENTED** [review]
@radcortez I will let you review this one. Not sure if `@ConfigRoot` is the right place for it or if we should introduce a new annotation in the `@ConfigDoc*` namespace.

**Review by radcortez — CHANGES_REQUESTED** [review]
Please, @ppalaga add a new annotation `@ConfigDocFilename` (or something) instead. Thank you.

`@ConfigRoot` will probably go away at some point once everything is using `@ConfigMapping`.

**Comment by ppalaga** [comment]
001782e: addressed the feedback of @radcortez (thanks!)

**Comment by ppalaga** [comment]
8302f5c: reformated

**Review by radcortez — APPROVED** [review]
Thanks!

**Review by gsmet — APPROVED** [review]

**Comment by ppalaga** [comment]
Thanks for feedback and review, gentlemen!

**Pull request merged**
