### PR TITLE
Create security cors doc

### LINKED ISSUE #36509: Move HTTP CORS section to its own document
### Description

Move HTTP CORS section to its own document, link to it from HTTP and Security Overview docs

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #36509.

This PR promotes the CORS related section as an independent security concept, linked to from both HTTP reference and Security overview docs

### CODE REVIEW

**Review by rsvoboda — CHANGES_REQUESTED** [review]
References will need to be updated in more places:

```
git grep -l "#cors-filter"

docs/src/main/asciidoc/openapi-swaggerui.adoc
docs/src/main/asciidoc/resteasy-reactive.adoc
docs/src/main/asciidoc/resteasy.adoc
docs/src/main/asciidoc/security-csrf-prevention.adoc
docs/src/main/asciidoc/security-oidc-bearer-token-authentication.adoc
docs/src/main/asciidoc/security-oidc-code-flow-authentication.adoc
docs/src/main/asciidoc/security-overview.adoc
```

**Comment by sberyozkin** [comment]
Sorry, @rsvoboda, I was under impression only one doc was referring to the HTTP CORS section, thanks for reminding all docs have to be checked (those links would still work since HTTP section is still there, the only problem, users will need to click on another link from there, so yes, let me handle these links)

**Comment by sberyozkin** [comment]
@rsvoboda This is done, note `http-reference.adoc#cors-filter` will now be a more precise check if some old references are still there, all is clear now

**Comment by sberyozkin** [comment]
Not sure though why surge is failing to publish

**Comment by rsvoboda** [comment]
https://quarkus-pr-main-36541-preview.surge.sh/version/main/guides/ reports Unavailable

**Comment by gastaldi** [comment]
@rsvoboda not recently. I had some trouble in the past when the payload is bigger than the limit supported in surge.sh, which I reported in https://github.com/quarkusio/quarkus/issues/35660

**Comment by sberyozkin** [comment]
@rsvoboda 

>This CORS guide has quite long first sentence, that's why it would be good to check it.

It was immediately starting from a link to the Mozilla docs, so I removed it, may be it will help for surge to succeed

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
@sunayna15 can you have somebody from the team to look into this? We may merge it soon, docs feedback can be addressed in separate pull request.

**Comment by MichalMaler** [comment]
@rsvoboda @sberyozkin  @sunayna15 Let me have a look on this content. Will create a new PR if needed.

**Comment by sberyozkin** [comment]
Thanks @rsvoboda @MichalMaler

**Pull request merged**
