### PR TITLE
Add merge(entity) to allow for updating an entire entity in one go

### PR DESCRIPTION
**Pull request by jasondlee**
There appears to be no way to pass an entity in via Panache for updates. The only available methods require setting fields one by one. This addresses that lack.

### CODE REVIEW

**Comment by FroMage** [comment]
Thanks for your PR, but this is a duplicate of https://github.com/quarkusio/quarkus/issues/3969.

We are still trying to delay adding `merge` because it's a very dangerous operation that we do not recommend. We have better alternatives planned for the future, and meanwhile you can always get to it via `Panache.getEntityManager().merge(entity)`.

I will close this until we're ready to make a move on this topic.

**Comment by jasondlee** [comment]
No worries. Can explain (or point me somewhere that does) how merge is dangerous? I've been using JPA for years and this is the first I've heard that. :)

**Comment by FroMage** [comment]
It's super dangerous because people use it from REST controllers most of the time, on data that comes directly from the user, which may have bindings that they're not allowed to access (say, an `isAdmin` property set to `true` when the current user doesn't have the right to edit it) and JPA due to its behaviour of auto-flushing changes to the DB is especially susceptible to those attacks, because the user may forget to check for what fields got sent in the request before merging and even in some use-cases will forget to throw an exception or rollback the transaction to prevent those changes from hitting the DB.

**Comment by FroMage** [comment]
If you don't your entities as DTOs you are exempt from this type of security issue, but you also don't need `merge` anymore.

**Comment by jasondlee** [comment]
That makes sense. Thanks for explaining that. :)

**Comment by jasondlee** [comment]
One final (I think ;) thought: While I understand the logic, it seems odd to me for the framework to make that decision for the application developer. I get trying to make something that is less likely to allow developers to shoot themselves in the foot, but this is hiding a pretty major piece of functionality that developers have used (and perhaps misused) for years. If I had to guess at the response, it would "Use JPA directly, or use $WHATEVER_IS_COMING", and those are also fair responses, but I just thought I'd chime in and share that thought. :) I do anxiously await the future alternatives, and, in the meantime, I'll grab the EM and merge directly.

Thanks!

**Pull request closed without merging**
