### PR TITLE
Bump Dekorate to 3.4.1

### PR DESCRIPTION
**Pull request by Sgitario**
Changes: https://github.com/dekorateio/dekorate/releases/tag/3.4.1

Relates: https://github.com/quarkusio/quarkus/issues/31355

### CODE REVIEW

**Comment by Sgitario** [comment]
> @Sgitario I'm not sure how often `isVerbose` was called but executing the call only once will be enough to remove all the additional cost we added? I'm a bit worried that even one time could be too much compared to the situation we had before but you're the expert here, I'm just asking questions :).

The problem is that we were calling too many times to the `isVerbose` method in the Topological Sort algorithm (which is new in Dekorate 3.4.0) and every time we invoked this method we were checking this property via the configuration registry (I wasn't aware of the cost of this call :/ ). 

After these changes, the value of `isVerbose` will be evaluated just once, and taking into account we are also using the `isVerbose` method in Dekorate core, when it's used by the Topological Sort algorithm, the cost will be free.

**Comment by gsmet** [comment]
OK, thanks for the clarification.

**Review by gsmet — APPROVED** [review]

**Comment by punkratz312** [comment]
@gsmet is there a reason why dependabot is not bumping the versions. these mr´s are very important. thanks for the contribution. on github the bot in actually included i think the config file need´s an adjustment, then it should work here as well? 
image

**Comment by gsmet** [comment]
@Sgitario the failures were unrelated. (I need to understand what is going on with these tests as they are always failing now)

**Review by gsmet — APPROVED** [review]

**Pull request merged**
