### PR TITLE
Add note about default Kotlin interface methods in REST Client docs

### PR DESCRIPTION
**Pull request by geoand**
Relates to: #22231

### CODE REVIEW

**Comment by kdubb** [comment]
If this is the "fix", maybe add a blurb about the `AbstractMethodError` one would get without the option so Google can land people here easily.

It took longer than I'd like to admit to realize the issue was default methods.

**Comment by geoand** [comment]
Good idea. I'll look into it

**Comment by geoand** [comment]
> If this is the "fix", maybe add a blurb about the `AbstractMethodError` one would get without the option so Google can land people there easily.
> 

@mkouba in order to save me some time looking around, when Arc generates a `...$$CDIWrapper_ClientProxy`  class for a REST Client interface, does it know which interface it's being created for?

Asking because if so, we could check if the class is a Kotlin class, and generate code that catches `AbstractMethodError` at runtime and provides a good error message.

**Review by gsmet — APPROVED** [review]

**Comment by mkouba** [comment]
> in order to save me some time looking around, when Arc generates a `...$$CDIWrapper_ClientProxy` class for a REST Client interface, does it know which interface it's being created for?

@geoand I'm not sure what this `..$$CDIWrapper_ClientProxy` actually is? I suppose that the `$$CDIWrapper` class is generated by the rest client extension?

**Comment by geoand** [comment]
Good point, it probably is.

**Comment by geoand** [comment]
I think that we can catch this issue at build time, I'll try something out

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/22276 is what I came up with

**Pull request merged**
