### PR TITLE
Additional JSON input validation on request

### PR DESCRIPTION
**Pull request by damonsutherland**
Adding exceptions to handle JSON that is malformed, or syntactically correct with invalid constraints (i.e., required properties, unresolved forward references, etc.). Both classifications are indications of client errors.

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
Thanks! Any chance we can get some tests like the ones we have [here](https://github.com/quarkusio/quarkus/tree/58c15652827711abc2bdeda643d5006f2f911250/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test)?

**Comment by damonsutherland** [comment]
@geoand Well, I have apparently messed things up a bit. I did a merge commit, which is not allowed. I tried to undo it, but the Merge commit check still fails. Anyway, my git foo is lacking. Do you have a recommendation to fix this?

Also, I added the tests you requested.

**Comment by geoand** [comment]
@damonsutherland no problem!

I force pushed to the PR

**Review by geoand — APPROVED** [review]

**Review by gsmet — DISMISSED** [review]
Just a note that the changes need to be squashed into one commit before being merged.

**Comment by damonsutherland** [comment]
@geoand, here is the commit that should address that error: https://github.com/quarkusio/quarkus/pull/29548/commits/572e2f7a4f6d3f8bec4e1db99d85095e3e07d08b.

I believe I have everything correct now .. tests passing, etc. I will monitor the build in case I missed something. In the mean time, I appreciate your help and patience.

Let me know if you need anything more.

**Comment by geoand** [comment]
Thanks!

I squashed, rebased and force pushed

**Comment by geoand** [comment]
Closing as per https://github.com/quarkusio/quarkus/issues/29316#issuecomment-1332997906

**Pull request closed without merging**
