### PR TITLE
When minikube is being used, never push a container-image

### LINKED ISSUE #10747: Updates are not being picked up when using minkube and jib extension together
**Describe the bug**

Changes made to the app when using jib and minikube extension are not reflected in the deployed application.
It's possible that due to the nature of jib (dockerless?) that the image never reaches the minikube docker daemon.

**Steps to reproduce** 

1. create a quarkus app

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=org.acme -DprojectArtifactId=hello-world --DprojectVersion=0.1-SNAPSHOT -Dendpoint=/hello -DclassName=org.acme.Hello
```
2. add minikube extension

```
mvn quarkus:add-extension -Dextensions="io.quarkus:quarkus-minikube"
```
3. add jib extension
```
mvn quarkus:add-extension -Dextensions="io.quarkus:quarkus-container-image-jib"
```

4. deploy

```
mvn clean install -Dquarkus.kubernetes.deploy=true
```

5. Change the message in Hello.java

6. redeploy

```
mvn clean install -Dquarkus.kubernetes.deploy=true
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #10747

### CODE REVIEW

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@geoand the build failed.

**Comment by geoand** [comment]
Darm, I'll take a look

**Comment by geoand** [comment]
I can't reproduce this locally.

**Comment by geoand** [comment]
Failed again... This one is going to be fun figuring out...

**Comment by geoand** [comment]
Should be fixed now

**Comment by geoand** [comment]
At last...

**Pull request merged**
