### PR TITLE
Upgrade to Hibernate Search 6.2.0.Final

### PR DESCRIPTION
**Pull request by yrodiere**
Changes since 6.2.0.CR1: https://hibernate.atlassian.net/issues/?jql=project=10061+AND+fixVersion=32168

There weren't many changes. Just a few micro dependency upgrades.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
LGTM but I need to restart CI as all the builds failed.

**Comment by Sanne** [comment]
Rebased, not least to trigger another CI run

**Comment by Sanne** [comment]
It would seem none of the windows builds were able to complete. I can't say for sure but I haven't seen other recent PRs fail for a similar reason so it's a bit suspicious...

@marko-bekhta would you be able to have a better look?

**Comment by marko-bekhta** [comment]
Ohh windows 😈 let me check what I can do 😃

**Comment by Sanne** [comment]
@marko-bekhta thanks! But before digging deep, try to see if there were other PRs with the same issue - I don't know for sure if it's really the fault of this pr.

**Comment by marko-bekhta** [comment]
> But before digging deep

Ouch 😨😢 should've read that before installing windows 😆😆😆. 

Just joking, I had a windows env but it didn't have quarkus on it so I've tried to build there -- but for some reason, it takes ages just to even run `./mvnw -Dquickly ` 

From what I see the failed `KotlinProjectWithCompilerArgsDevModeTest` test is trying to do something with `kotlin-grpc-project`  and there's nothing related to Search so I'd assume it is not related to the upgrade 😃 

I see that a few neighbouring PRs have the timeouts on windows builds too... 

There also don't seem to be any obvious changes in this release compared to CR1 that would cause any issues.

Maybe it's worth to try and restart the build once more? 🙈

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I rebased and force pushed to fix a conflict.

**Pull request merged**
