### PR TITLE
ArC Dev UI - add bean dependency graph

### LINKED ISSUE #26065: Bean tree/graph in Quarkus Dev UI
### Description

In the Quarkus Dev UI it would be really cool to see how beans are being pulled in. Like a tree or graph showing the hierarchy of bean resolution.

I have a few beans that I think should be considered "unused", but they are still pulled in (I know because they fail with missing config properties). It would be helpful to debug these cases.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- also add DEBUG logging for unremovable beans
- resolves #26065

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
Very nice !

**Comment by phillip-kruger** [comment]
@mkouba this is very cool. I'll look into small cosmetic changes in a separate PR. This looks great ! 
image

**Comment by mkouba** [comment]
> @mkouba this is very cool. I'll look into small cosmetic changes in a separate PR. This looks great !

Thanks and +1 for further development and cosmetic improvements! I need to fix this PR first though - the CI failure is related.

**Review by phillip-kruger — APPROVED** [review]

**Review by manovotn — APPROVED** [review]
Played with it using some quickstart samples and it looks really amazing!

**Comment by gsmet** [comment]
Deserves to be in the release announcement IMHO, I added the appropriate label.

**Comment by gsmet** [comment]
@phillip-kruger in your upcoming UI improvement PR, please add a screenshot so that I can use it for the announcement :).

**Comment by phillip-kruger** [comment]
Will do.

**Comment by mkouba** [comment]
Hm, the `rest-client-reactive-jaxb` failures do not seem to be related. @gsmet does it ring a bell?

**Comment by gsmet** [comment]
Yes: https://github.com/quarkusio/quarkus/pull/26173/files .

**Pull request merged**
