### PR TITLE
Update xrefs to use .adoc consistently

### PR DESCRIPTION
**Pull request by rolfedh**
@sberyozkin

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
This is a good idea and I think we should even:

- generalize it to all the guides
- throw an error when xref is not using `.adoc`

If you're willing to do the former, I could do the latter once done so that we don't have more crawling back.

**Comment by rolfedh** [comment]
@gsmet: That's a great idea.

- I scoped the search to `quarkus/docs/src/main/asciidoc` (which doesn't include generated files).
- I used the regex `xref:[^\s.]+#.*` to identify filenames that omit `.adoc` and are followed by a `#` bookmark.
- However, I'm unsure how to differentiate xrefs to filenames missing `.adoc` from xrefs to same-page IDs. For example, the regex `xref:[^.]+\[` captures this xref to a filename missing `.adoc`, like:
  ```asciidoc
  See the xref:quarkus-reactive-architecture[Quarkus Reactive Architecture documentation] for further details.
  ```
  But it also matches this xref to a same-page section, like:
  ```asciidoc
  As mentioned in the xref:why-not[Why not run everything on virtual threads?] section...
  ```

I suspect the solution might involve a Python script that inventories all filenames in the `asciidoc` directory. What do you think?

**Comment by sberyozkin** [comment]
Thanks @rolfedh, LGTM, I'll let you and Guillaume decide when to merge 🙂

**Review by sberyozkin — APPROVED** [review]

**Comment by gsmet** [comment]
> I suspect the solution might involve a Python script that inventories all filenames in the asciidoc directory. What do you think?

Hmmm, yeah, I think I'd rather implement the checks directly in Java. That's probably the only way to detect them.

Let's merge this as it's already a good step forward. Thanks!

**Comment by rolfedh** [comment]
Thanks, Guillaume! (@gsmet)

I ran a script to identify the second case mentioned above and found only one instance: [#45288](https://github.com/quarkusio/quarkus/pull/45288).

With that, I believe all the `.adoc` files in the `/asciidoc` directory have been successfully cleaned up.

**Pull request merged**
