### PR TITLE
Update OWASP dependency check plugin version

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by jmartisk** [comment]
Do we have a way to test that this will fix the failure?

**Review by aloubyansky — APPROVED** [review]

**Comment by sberyozkin** [comment]
@jmartisk Jan, I think maybe we can manually trigger the action ? The update is long overdue in any case

**Comment by jmartisk** [comment]
We can trigger it manually, but to run it in this repo, we would have to merge it first. Could you try executing it in your repo? You'd go to https://github.com/sberyozkin/quarkus/actions/workflows/owasp-check.yml and trigger it using the "Run workflow" button that I don't see because I'm not an admin of your fork

**Comment by jmartisk** [comment]
If it turns out to be a problem, we can just merge it and wait for the next nightly run

**Comment by sberyozkin** [comment]
@jmartisk Sure, just did it, will take awhile :-)

**Comment by sberyozkin** [comment]
@jmartisk It does not want to run it in my fork: https://github.com/sberyozkin/quarkus/actions/runs/11702263054/job/32590086209

I've run it on this PR's branch, while the action references the `main` branch, but all previous scheduled runs were cancelled after just 2 secs too.

We can just merge and users can also try to run it locally

**Comment by jmartisk** [comment]
I think you'd have to change/remove this line https://github.com/sberyozkin/quarkus/blob/main/.github/workflows/owasp-check.yml#L12 to allow it to run on your fork

**Comment by sberyozkin** [comment]
Sorry @jmartisk, I merged and then decided to scroll and noticed your comment, my apologies :-), the version update itself should be fine in any case, let me trigger the action

**Comment by sberyozkin** [comment]
@jmartisk @aloubyansky It worked :-), I guess the next step is to see how to wire in sbom

**Comment by jmartisk** [comment]
@sberyozkin are you sure the plugin supports working from sbom? Or do you have a different plugin in mind?

On the other hand, I found https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html where Example 7 shows how to exclude vulnerabilities that we don't want to pollute the report, which may be useful

**Comment by sberyozkin** [comment]
Thanks @jmartisk, yeah, this one does not accept BOM AFAIK...  Yeah, I'm not seeing which OWASP plugin can take SBOM as input for the CVE checks on dependencies... We may have to do exclusions, I'll have a look

**Pull request merged**
