### PR TITLE
Check template key against transformed method name

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by alesj** [comment]
@mkouba something like this ... cannot fully test atm, as it looks like the build is broken
If this is not the way, then we at least have a reproducer test. :-)

**Comment by mkouba** [comment]
I believe that it works as [documented](https://quarkus.io/guides/qute-reference#localization): _keys in a message bundle file are mapped to method names from the corresponding message bundle interface_.

**Comment by alesj** [comment]
OK, I then fail to see the use-case / usage of `UNDERSCORED_ELEMENT_NAME` ... ?

**Comment by alesj** [comment]
> [Message bundle files](https://quarkus.io/guides/qute-reference#localization), on the other hand, always use the method name as a key.

Ah, I see.

But why not change this as well?
(at least that looked natural to me when I tried using this ...)

**Comment by mkouba** [comment]
> But why not change this as well?
> (at least that looked natural to me when I tried using this ...)

I don't remember all the details but since the message bundle interface is the central piece of the API it kind of makes sense that the method names are used as keys. Also it gives you more flexibility when changing the strategy, e.g. `HYPHENATED_ELEMENT_NAME` -> `UNDERSCORED_ELEMENT_NAME` requires no change in the localized files.

In theory, we could introduce a config property to change the default behavior. But I'm not really sure it's worth the effort :shrug:.

**Comment by alesj** [comment]
I guess it was just me who expected the interface API to be Java-like (doh!),
where template AND localized files keys would be underscored or hyphenated.
(since they are both 'text' files, and using `_` or `-` makes more sense for keys)

**Comment by FroMage** [comment]
Yeah, I would have expected the setting to also apply to the message file as well 🤷, it feels more intuitive.

Now, that doesn't mean it's very important… so not sure what to make of it :)

**Comment by mkouba** [comment]
I'm used to the fact that my "intuitive" is often not very "intuitive" for others and vice versa. Anyway, I don't think it's worth the effort. Like [I mentioned](https://github.com/quarkusio/quarkus/pull/34770#issuecomment-1661900646) - I don't remember the details why we choose this way but (A) it's documented, (B) it would be a breaking change.

I'm going to close this PR but I will create a tracking issue.

**Pull request closed without merging**
