### PR TITLE
Disable extension validation by default until it gets fixed

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by geoand** [comment]
CI seems to not like it :(

**Comment by zakkak** [comment]
The issue seems unrelated to the PR though:

```
Fail to upload '/home/runner/work/quarkus/quarkus/maven-repo.tgz' due to 'Blob is incomplete (missing block). Blob: b520c43ed1b6ea119b052818788e512b, Expected Offset: 482393059, Actual Offset: 482344960'.
GitHub.Services.Common.VssServiceException: Blob is incomplete (missing block). Blob: b520c43ed1b6ea119b052818788e512b, Expected Offset: 482393059, Actual Offset: 482344960
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState)
   at GitHub.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Boolean uploadFirstChunk, Object userState, Boolean compressStream)
   at GitHub.Runner.Plugins.Artifact.FileContainerServer.UploadAsync(RunnerActionPluginExecutionContext context, Int32 uploaderId, CancellationToken token)
File upload complete.
Uploaded '0' bytes from '/home/runner/work/quarkus/quarkus/maven-repo.tgz' to server
```

**Comment by aloubyansky** [comment]
Here is the fix for the original issue https://github.com/quarkusio/quarkus/pull/10268

**Comment by gsmet** [comment]
The idea is to merge https://github.com/quarkusio/quarkus/pull/10268 instead.

**Pull request closed without merging**
