### PR TITLE
Ensure that subsequent uberJar creations doesn't fail

### LINKED ISSUE #4858: uberjar: second build fails
**Describe the bug**
With uberjar enabled, the second time I run `mvn install` it fails with:
```
[ERROR]     [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildUberJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: META-INF/services/org.eclipse.microprofile.context.spi.ContextManagerProvider
[ERROR]     at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:949)
[ERROR]     at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
[ERROR]     at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR]     at java.lang.Thread.run(Thread.java:748)
[ERROR]     at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.nio.file.FileAlreadyExistsException: META-INF/services/org.eclipse.microprofile.context.spi.ContextManagerProvider
[ERROR]     at com.sun.nio.zipfs.ZipFileSystem.newOutputStream(ZipFileSystem.java:516)
[ERROR]     at com.sun.nio.zipfs.ZipPath.newOutputStream(ZipPath.java:790)
[ERROR]     at com.sun.nio.zipfs.ZipFileSystemProvider.newOutputStream(ZipFileSystemProvider.java:285)
[ERROR]     at java.nio.file.Files.newOutputStream(Files.java:216)
[ERROR]     at io.quarkus.deployment.pkg.steps.JarResultBuildStep.copyCommonContent(JarResultBuildStep.java:407)
[ERROR]     at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildUberJar(JarResultBuildStep.java:230)
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]     at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]     at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:940)
[ERROR]     ... 7 more
```

`mvn clean install` works as usual.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "1.8.0_222"
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 0.26.1

**Additional context**
The build also outputs a lot of warnings like:
```
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/quarkus-extension.json entry from io.quarkus:quarkus-resteasy-jackson::jar:0.26.1(compile) will be ignored. Existing file was provided by io.quarkus:quarkus-resteasy-common::jar:0.26.1(compile)
```
This should be avoided.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #4858

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Did you include the latest from master, as it was broken for about 10 minutes?

**Comment by geoand** [comment]
Thanks for pointing it out @kenfinnigan! Just rebased on to the latest master

**Comment by kenfinnigan** [comment]
No worries, saves waiting an hour to find out it's broken ;-)

**Comment by geoand** [comment]
Absolutely!

**Comment by jaikiran** [comment]
Hello @geoand, I think it's better and safer to use this same change in other places, within that same class, wherever we are writing out data using this `Files.newOutputStream` on a zipfs. For example, I expect the user will run into this same error, when we try to write out the `META-INF/MANIFEST.MF` into that jar. Searching for `wrapForJDK8232879` should show other such locations in that file.

**Comment by geoand** [comment]
@jaikiran You are correct! I mistakenly assumed (I admit I didn't even search :)) that this was the only zip we were writing to.

**Comment by geoand** [comment]
@jaikiran PR updated

**Comment by jaikiran** [comment]
This looks good to me @geoand :)

**Review by jaikiran — APPROVED** [review]

**Comment by geoand** [comment]
Thanks for the review @jaikiran!

**Comment by geoand** [comment]
@stuartwdouglas OK to merge?

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
