### PR TITLE
Fix for xray to work within aws http/rest extensions

### LINKED ISSUE #22595: Quarkus doesn’t send X-Ray traces to AWS for sub-segments in Native build while using “controller”-based approach
### Describe the bug

I an using "Controller" based approach using RESTEasy. I have added Quarkus AWS Xray dependency in my POM.xml..

And then we are instrumenting calls to AWS Services using below dependency:
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-xray-recorder-sdk-aws-sdk-v2-instrumentor</artifactId>
    <version>2.10.0</version>
</dependency>

Also, we create manual sub-segment for external API calls..

However, Quarkus send sub-segment traces to XRay in the JVM build..
But in Native build, it does not send any sub-segments... also, there is no error thrown. In cloudwatch logs, it says "TRACE_ID missing.

It works for native build in AWS Lambda "Handler" based approach but not in "Controller" based approach in RESTEasy.
Attaching the screenshots of JVM and Native Build below:

### Expected behavior

It should create and show sub-segments in the graph also.

### Actual behavior

It does not show the sub-segments in Native build.

### How to Reproduce?

[https://github.com/amitkumar7566/xray-native-image-test](url)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

java 11

### GraalVM version (if different from Java)

21.3-java11

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by patriot1burke**
Reverted code substitution as xray now looks within system properties

Fix #22595

### CODE REVIEW

**Review by radcortez — APPROVED** [review]

**Comment by paulrobinson** [comment]
Requested in https://issues.redhat.com/browse/QUARKUS-1722, so proposing a backport to 2.7.

**Comment by radcortez** [comment]
> Requested in https://issues.redhat.com/browse/QUARKUS-1722, so proposing a backport to 2.7.

We are still waiting for confirmation that this fix actually solves the problem reported in #22595. Once we get confirmation, it should be fairly straightforward to backport.

**Comment by patriot1burke** [comment]
@gsmet Needs to be backported to 2.7 branch and released with 2.7.1 (Customer issue).

**Comment by gsmet** [comment]
@patriot1burke unless I'm mistaken, the current status is that I already backported it to 2.7.0.Final.

**Comment by gsmet** [comment]
Yes, it's there: https://github.com/quarkusio/quarkus/pull/23151 .

**Pull request merged**
