### PR TITLE
Make Sub Resources unremovable beans

### LINKED ISSUE #5314: Subresouce init resource failed when using `ResourceContext.getResource`
I have created a post about the sub resource issue on StackOverflow before, https://stackoverflow.com/questions/57820428/jax-rs-subresource-issue-in-quarkus 
It seems [Quarkus issue#3919](https://github.com/quarkusio/quarkus/issues/3919) has been resolved in the latest 1.0.0.CR1. 

When I tried to remove the workaround annotations(`@Unremovable`, `@RegisterForReflection `), it failed, there are still some issues in 1.0.0.CR1. 

```java
@RequestScoped
public class CommentResource {
    private final static Logger LOGGER = Logger.getLogger(CommentResource.class.getName());
    private final CommentRepository comments;

    @Context
    UriInfo uriInfo;

    @Context
    ResourceContext resourceContext;

    @PathParam("id")
    String postId;

    @Inject
    public CommentResource(CommentRepository commentRepository) {
        this.comments = commentRepository;
    }

    @GET
    public Response getAllComments() {
        return ok(this.comments.allByPostId(this.postId)).build();
    }
```

And declares it as sub-resources of `PostResource` like this.

```java
    @Path("{id}/comments")
    public CommentResource postResource() {
        return resourceContext.getResource(CommentResource.class);
    }
```

When I ran the application and tried to access comments resources like `/posts/< post id>/ comments`, failed with NPE exception in this line `  return ok(this.comments.allByPostId(this.postId)).build();`.

`@PathParam("id") String postId` or `this.comments` injection failure caused this exception. 

But when change the subresource declaration to the following. 

```java
    @Inject CommentResource commentResource;

    @Path("{id}/comments")
    public CommentResource postResource() {
        return resourceContext.initResource(commentResource);
    }
```
It works.  A updated version is [here](https://github.com/hantsy/quarkus-sandbox/tree/master/post-service). 

But I think both approaches(`getResource` or `initResource`) should work in JAX-RS.

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #5314

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
Looks like something we should backport? Or is it risky?

**Comment by geoand** [comment]
Not risky at all, we should backport

**Comment by gsmet** [comment]
Done, thanks!

**Comment by geoand** [comment]
Thank you!

**Pull request merged**
