### PR TITLE
Qute generated value resolvers - fix varArgs methods with 1 argument

### LINKED ISSUE #31449: Qute: VarArgs processing error with 1 element
### Describe the bug

@mkouba I'm submitting this based on your suggesting to file here in Quarkus to fix https://github.com/quarkiverse/quarkus-renarde/issues/102

I have a method on my User class which is a RenardeUser, etc.

I have a method called `hasUserRole(String... roleNames)` that I'd like to pass in a list of roles to check from my Qute templates in a single method call instead of multiple calls.

This works IF I pass in a list of roles like `{#if inject:user && inject:user.hasUserRole("webadmin", "admin", "support")}` but I get an exception during RUNTIME if I try to pass in a single value, ie. `{#if inject:user && inject:user.hasUserRole("admin")}`

The project compiles and starts up just fine but dies when I access the page with the single permission check.

```
2023-02-26 17:27:11,348 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-1) Request failed: java.lang.ClassCastException: class java.lang.String cannot be cast to class [Ljava.lang.String; (java.lang.String and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
```

### Expected behavior

VarAgs with a single parameter should also work

### Actual behavior

Get the error:

```
2023-02-26 17:27:11,348 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-1) Request failed: java.lang.ClassCastException: class java.lang.String cannot be cast to class [Ljava.lang.String; (java.lang.String and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #31449

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by mkouba** [comment]
@FroMage FYI this should fix the problem discovered in https://github.com/quarkiverse/quarkus-renarde/issues/102.

**Comment by gsmet** [comment]
@mkouba should we backport it or is it only in 3?

**Comment by mkouba** [comment]
> @mkouba should we backport it or is it only in 3?

We should backport this pr if possible...

**Comment by gsmet** [comment]
Done, I just had to adjust the test with the javax packages.

**Comment by mkouba** [comment]
> Done, I just had to adjust the test with the javax packages.

Thanks! :+1:

**Pull request merged**
