### PR TITLE
Generate Jackson deserializers

### PR DESCRIPTION
**Pull request by mariofusco**
This pull request completes the work on Jackson's reflection-free serialization also implementing the deserialization part. I added a complete explanation of what this generates in the javadocs.

Once this will be merged I believe that we could have some discussion on how to extend and generalize this work making this improvement available also to other parts of Quarkus that need to perform some sort of json serialization.

/cc @geoand @franz1981 @metacosm

### CODE REVIEW

**Comment by geoand** [comment]
Nice!

Just wondering, have you seen https://github.com/quarkusio/quarkus/issues/42774?

I mention it because I would not want this to make things even worse, so maybe it makes sense to fix that bug first.

**Comment by mariofusco** [comment]
> Just wondering, have you seen #42774?

Yes, I saw it and I just started investigating it. I think that the only problem is that I missed to properly cover some (less used) primitive types like `char` and `byte` in my implementation. I need a bit more time to work on this and I will let you know if simply properly parsing those types will also fix that problem as I hope.
 
> I mention it because I would not want this to make things even worse, so maybe it makes sense to fix that bug first.

I don't think that this pull request could make the things worse in any way except for the fact that now I will have to properly support those primitive types on both serialization and deserialization. I started working on this improvement before that issue was opened and since it required a quite huge refactor I simply didn't want to mix the 2 things. 

In essence I could also try to fix that problem also in this pull request, but if it's ok for you I'd prefer to keep the 2 things separated and provide a fix only on top of this refactor. Let me know.

**Comment by mariofusco** [comment]
> Yeah, this PR could have an extra commit fixing the issue

Ok, I will work on it and keep you updated. In the meanwhile I will flag this pull request as a draft.

**Comment by gsmet** [comment]
FWIW, I'm sorry to be that guy but I somehow need a backportable fix for the bug (and so a fix that is not on top of a major refactoring).
You can create a PR targeting 3.14 at some point if the patch for `main` is very different.

**Comment by mariofusco** [comment]
> FWIW, I'm sorry to be that guy but I somehow need a backportable fix for the bug (and so a fix that is not on top of a major refactoring). You can create a PR targeting 3.14 at some point if the patch for `main` is very different.

No problem, I will work on that fix on a different pull request and I will rebase this one against it once ready and merged.

**Comment by geoand** [comment]
> FWIW, I'm sorry to be that guy but I somehow need a backportable fix for the bug (and so a fix that is not on top of a major refactoring).
> You can create a PR targeting 3.14 at some point if the patch for `main` is very different.

Ah, I'd didn't realize the previous stuff was already in what will be LTS

**Comment by geoand** [comment]
This now needs a rebase

**Comment by mariofusco** [comment]
Replaced by https://github.com/quarkusio/quarkus/pull/42954

**Pull request closed without merging**
