### PR TITLE
Update to SmallRye Fault Tolerance 5.1.0 and add Vert.x integration

### LINKED ISSUE #17080: Enable fault-tolerance tests on JDK 16+
Update to a smallrye-fault-tolerance release that incorporates https://github.com/smallrye/smallrye-fault-tolerance/pull/409 (probably 5.0.1?) and revert this commit: https://github.com/quarkusio/quarkus/pull/17053/commits/d9290492cd2a30f04e8216725d03930fa7fb9468

Relates to https://github.com/quarkusio/quarkus/issues/16195#issuecomment-832585114

- set JDK 16 (e.g. via `sdk`)
- if Kotlin 1.5 is not yet integrated: add `--add-opens java.base/java.util=ALL-UNNAMED` to `MAVEN_OPTS`
- `mvn -Dquickly -T1C`
- `mvn clean verify -f tcks/microprofile-fault-tolerance` (should not fail)
- `mvn clean verify -f tcks/microprofile-fault-tolerance -P'!jdk16-workarounds'` (should fail)
- same with `integration-tests/main` (`RestClientTestCase#testFaultTolerance`)

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #17080

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft because

- I want to let CI run in my fork;
- I need to add some tests.

**Comment by famod** [comment]
Is this also going to fix the Java 16 issues?

**Comment by Ladicek** [comment]
Indeed this will fix the Java 16 issues. I totally forgot to revert that commit -- thanks for reminder!

**Comment by Ladicek** [comment]
CI passed in my fork.

**Comment by Ladicek** [comment]
@michalszynkiewicz could you please review the `SmallRyeFaultToleranceProcessor` change? (Sorry, can't think of anyone else, I don't really know who wrote the FT extension originally :-) )

**Comment by famod** [comment]
Have you tried running the tcks tests locally with Java 16? Thing is CI runs them only with Java 11.
What I could do alternatively is to create a branch from yours here in the main repo and run the EA job for it...

**Comment by Ladicek** [comment]
I did run the TCK locally with Java 16, but only on the SmallRye Fault Tolerance repo, that is, with Weld. Let me do that again with Quarkus.

**Comment by Ladicek** [comment]
This is what I just did locally, on commit 490ca98cd2da628a8215c884766b1edb17509a94, that is, on the branch corresponding to this PR:

```bash
find . -type d -name target -print0 | xargs -0 rm -rf
mvn clean install -Dquickly
export JAVA_HOME=/usr/lib/jvm/java-16-openjdk-amd64
cd tcks/microprofile-fault-tolerance/
mvn clean verify -Dtcks
```

And the result is `Tests run: 435, Failures: 0, Errors: 0, Skipped: 0`.

In other words, the MP FT TCK passes on Java 16 just fine :-)

**Comment by cescoffier** [comment]
Should we merge this one?

@famod I believe @Ladicek did the Java 16 tests.

**Comment by Ladicek** [comment]
Merging would certainly be nice :-)

**Comment by Ladicek** [comment]
I mean, @cescoffier if you could take a look at what I did to the Vert.x extension, that would be even nicer! I couldn't think of a better place where to put the integration dependency. An unfortunate side effect is that the `quarkus-vertx` artifact now transitively brings exactly 1 new dependency, `smallrye-fault-tolerance-vertx`, but that thing only includes like 4 classes and weights 6 KBs, so should be fine.

**Comment by famod** [comment]
Thanks for checking the FT TCK on Java 16!

**Review by cescoffier — APPROVED** [review]
LGTM, the new dependency is acceptable as it rather small. We can revisit this later if need be.

**Pull request merged**
