### PR TITLE
Set target dir in QuarkusUnitTest

### PR DESCRIPTION
**Pull request by aloubyansky**
It looks the target dir is missing in QuarkusUnitTest.
This is related to https://github.com/quarkusio/quarkus/issues/23759 and https://github.com/quarkusio/quarkus/pull/23856

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
We should probably backport this, right?

**Comment by aloubyansky** [comment]
Yes

**Comment by geoand** [comment]
@phillip-kruger mind taking a look at the OpenAPI failures?

Thanks

**Comment by aloubyansky** [comment]
The CI failures are caused by this change.

**Comment by geoand** [comment]
Yeah, just wondering if the tests themselves are making some incorrect assumption

**Comment by aloubyansky** [comment]
I pushed a kind of fix to the `SmallRyeOpenApiProcessor.java`, which needs to be reviewed.

**Review by phillip-kruger — APPROVED** [review]
LGTM.

**Pull request merged**
