### PR TITLE
Make hibernate.temp.use_jdbc_metadata_defaults configurable from persistence.xml

### LINKED ISSUE #15888: hibernate.temp.use_jdbc_metadata_defaults=false setting is ignored in persistence.xml
## Describe the bug
1. Use quarkus-hibernate-orm extension
2. Use dedicated META-INF/persistence.xml for configuration
3. set hibernate.temp.use_jdbc_metadata_defaults=false in persistence.xml
4. the setting is ignored during startup

### Expected behavior
hibernate.temp.use_jdbc_metadata_defaults setting should actually take effect.

### Actual behavior
hibernate.temp.use_jdbc_metadata_defaults=false is ignored during application deployment

## To Reproduce

link to reproducer: https://github.com/tttomat19/quarkus-quickstarts

1. get https://github.com/tttomat19/quarkus-quickstarts
2. use modified hibernate-orm-quickstart (the only difference is persistence.xml)
3. run with ./mvnw quarkus:dev -Dsuspend=y 
4. see in debugger that quarkus goes through JdbcEnvirtonmentInitiator twice. The second time it ignores the setting.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
 ./mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

## Additional context

The problem is with this line in quarkus-hibernate-orm extension:
file: FastBootHibernatePersistenceProvider.java
runtimeSettingsBuilder.put("hibernate.temp.use_jdbc_metadata_defaults", "true");
it just overrides whatever is set in persistence.xml

And my actual problem is that I hit the edge case: my database has literally 10000 tables, the metadata scan is slow, and overall startup is slow. I try to disable the metadata scan. But.

### PR DESCRIPTION
**Pull request by tttomat19**
Make hibernate.temp.use_jdbc_metadata_defaults configurable from persistence.xml

* Fix #15888

### CODE REVIEW

**Review by yrodiere — COMMENTED** [review]
The fix looks good to me. As such, this patch will only affect people who set property `hibernate.temp.use_jdbc_metadata_defaults` in their `persistence.xml`; which is great.

A disclaimer to anyone else reading this PR, though: `hibernate.temp.use_jdbc_metadata_defaults` is not part of the Hibernate ORM API and may disappear completely at any moment. The name contains `temp` precisely because it's a temporary workaround and we will hopefully remove it at some point (without warning).

@Sanne I assume from [your comment](https://github.com/quarkusio/quarkus/issues/15888#issuecomment-804809942) that you're fine with merging this without a test? Considering the use case is way beyond what we support anyway, I'd say it's reasonable.

**Comment by Sanne** [comment]
> @Sanne I assume from [your comment](https://github.com/quarkusio/quarkus/issues/15888#issuecomment-804809942) that you're fine with merging this without a test? Considering the use case is way beyond what we support anyway, I'd say it's reasonable.

Yea I agree it should be reasonable.  Maybe we need a warning if this setting is explicitly defined?

**Comment by yrodiere** [comment]
> > @Sanne I assume from [your comment](https://github.com/quarkusio/quarkus/issues/15888#issuecomment-804809942) that you're fine with merging this without a test? Considering the use case is way beyond what we support anyway, I'd say it's reasonable.
> 
> Yea I agree it should be reasonable. Maybe we need a warning if this setting is explicitly defined?

That's not the only "unsupported" setting, though...

To be fair there are so many settings that are not "officially" supported that it would probably make more sense to have an allowlist for settings that don't trigger a warning, than to have a denylist for settings that do trigger a warning...

Maybe I can add that to my todo list?

**Comment by Sanne** [comment]
I think there's a difference. With most other properties being rather "not tested" than "dangerous": they should work as usual - just untested, which implies possibly to find some issues in native. Remember we don't encourage people to use the `persistence.xml` - the whole file is "unsupported".

But this one property specifically we do automatically disable, and the user setting it explicitly to `false` would break things, so we should recommend users to not set it (unless they want to set it to true like in this case).

**Comment by gavinking** [comment]
Then wouldn't that be a warning (or even an error!) only if they explicitly set it to *false*?

**Comment by gavinking** [comment]
I mean, I don't understand this issue much at all, but it sounds like s related to native vs VM. And so it sounds like you're actually able to identify the "broken" case. If so, wouldn't it be better to nail down that case and explicitly warn the user only in that case.


(I'm probably misunderstanding.)

**Comment by Sanne** [comment]
> Then wouldn't that be a warning (or even an error!) only if they explicitly set it to _false_?

yes exactly that's the primary goal. But setting it to true should also be unnecessary, so either way ..

**Comment by gavinking** [comment]
Well, I mean "unnecessary" is not the same thing as "broken".

**Comment by gavinking** [comment]
It's just: you know how I feel about warnings. They suck.

**Comment by Sanne** [comment]
sure, I have no strong opinion but we could make it more strict: the user should never need to mention this property.

**Comment by tttomat19** [comment]
To clarify I wanted to set it to `false`.

Current state:
1. Setting `use_jdbc_metadata_defaults` is fixed false during static init. (false means disabled metadata scan). `FastBootMetadataBuilder:223`
2. But then, at runtime it is fixed true (ignoring whatever is set in persistence.xml). `FastBootHibernatePersistenceProvider:192`
Both 1 and 2 are executed during startup.

The actual problem is startup performance when database has 10000 tables. Then metadata scan takes really long time.

Proposed state:
1. Setting `use_jdbc_metadata_defaults` is fixed false during static init. Unchanged.
2. Take value for `use_jdbc_metadata_defaults` from persistence.xml (defaults to true). - to be able to set it to `false`. Or maybe take it from properties, but not implemented yet.

I can't tell if setting to `false` could break things. If it does break anything, is there any other way to handle the problem with long metadata read?

**Comment by gavinking** [comment]
If that's an option, it sounds like it would be ideal.

**Review by yrodiere — APPROVED** [review]

**Comment by yrodiere** [comment]
@Sanne @gavinking Unless you still have objections, I'm going to go ahead and merge this.

**Comment by gavinking** [comment]
Well yeah, I do kind-of object, frankly: it looks like we're adding support for a users to explicitly set a "temp" property that (according to what @Sanne seems to be saying above) was never really intended to be user-visible. That's implicitly making it non-"temp" and turning it into something that we can't easily remove later.

I think we should either:

1. figure out a way to get the right behavior automatically, or
2. not fix at this time.

Otherwise we're just creating problems for the future.

Of course, I might be wrong, but it seems to me that the *right* solution to this issue is to do more thinking. And if nobody has the bandwidth to do the thinking that's required, then we should do nothing until someone does have time.

**Comment by Sanne** [comment]
right good points - however I didn't intend to _support_ people setting the option, but the fact is that apparently ORM already supported this and that ship has sailed. So trying to restore some consistency fixing past mistakes.

Currently (and I didn't even know) this has weird semantics in Quarkus as it seems the use of persistence.xml was bypassing what I had intended to enforce. I need this consistently enforced, which just happens to be what @tttomat19 also needs.

So my proposal:

- enforce it to false
- check if the user is setting it explicitly; if it's set -> log that we're ignoring it, or that we will ignore it shortly (deprecation)

It's tempting to just ignore it right away, but there are side effects; these are very unlikely to manifest as real problems but that's what makes me more cautious and think we'd need a deprecation first.

**Comment by gavinking** [comment]
Ok, Sanne, what you're proposing sounds fine, I suppose.

**Comment by juliaaano** [comment]
In my view this other PR #17509 also fixes the issue with the advantage of providing tests.

**Comment by Sanne** [comment]
@tttomat19 I suspect this is no longer necessary, as we improved several other things; see
 - https://github.com/quarkusio/quarkus/issues/16927#issuecomment-858958729

Could you please test how it's working for you?  I'd really like to close this without exposing the property. Thanks!

**Comment by tttomat19** [comment]
Thanks a lot. It just works after upgrading to quarkus 2.0+/ Startup is 8-15 seconds faster.

**Comment by gavinking** [comment]
Excellent outcome.

**Pull request closed without merging**
