### PR TITLE
Revert "Bump to Liquibase 4.4.0"

### PR DESCRIPTION
**Pull request by gastaldi**
Reverts quarkusio/quarkus#17943

### CODE REVIEW

**Comment by geoand** [comment]
Why are we reverting?

**Comment by gastaldi** [comment]
@geoand because @gsmet found that the Liquibase quickstart started failing after this: https://github.com/quarkusio/quarkus-quickstarts/runs/2871476711?check_suite_focus=true

**Comment by geoand** [comment]
I assume we can fix it, no?

**Comment by gsmet** [comment]
Probably. There's no urgency as long as we don't backport it. But I would prefer if the quickstarts CI could be fixed sooner rather than later.

**Comment by geoand** [comment]
Right, I didn't mark the `4.4` bump for backport anyway. I'll have a look

**Pull request closed without merging**
