### PR TITLE
Initial Support for Code coverage

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I have tested out the local coverage and it seems to work. Apparently Azure can auto publish the results so I am testing this out.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
@stuartwdouglas can you rebase?

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
FWIW, I tried this last week and I had a build issue. I still have to understand what's going on. Will try to get at it this week, other PRs were in the way.

**Comment by cescoffier** [comment]
@gsmet Ok, I let you investigate.

**Comment by gastaldi** [comment]
Perhaps it would be interesting to publish these analysis to [SonarQube](https://www.sonarsource.com/products/sonarqube/) (there is a maven plugin that publishes there)

**Comment by gsmet** [comment]
@stuartwdouglas @paulrobinson I just rebased that one as there were several conflicts. I'm running it on my laptop now.

**Comment by gsmet** [comment]
I was able to run it on my laptop.

The Windows build fails though with:
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool::allocate
# An error report file with more information is saved as:
# D:\a\1\s\integration-tests\kotlin\target\test-classes\projects\project-classic-run-kotlin-change-local\hs_err_pid4244.log
#
# Compiler replay data is saved as:
# D:\a\1\s\integration-tests\kotlin\target\test-classes\projects\project-classic-run-kotlin-change-local\replay_pid4244.log
```

I don't think it's related to this PR as it shouldn't change the Windows build at all. I will trigger a new run.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
