### PR TITLE
Move to dekorate 2.9.0

### LINKED ISSUE #23399: `quarkus-kubernetes` fails when using Git submodules.
### Describe the bug

Any use of Git submodules causes a build crash when using `quarkus-kubernetes`; to which there is no workaround.

The cause is a parsing bug in Dekorate. I've filed a PR to fix the issue in the Dekorate repository (https://github.com/dekorateio/dekorate/pull/852).

This issue is to document the bug and track it's fix when a fixed dekorate is released. 

### Expected behavior

Gut submodules can be used.

### Actual behavior

Using Git Submodules causes an irrecoverable build crash.

### How to Reproduce?

Use Git submodules in any project along with `quarkus-kubernetes`.

### Output of `uname -a` or `ver`

macOS 12.1

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kdubb**
Includes updates for breaking changes to dekorate API.

Fixes #23399

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
LGTM, but I'll let @iocanel have the final say.

Also, is this safe to backport to 2.7?

**Comment by kdubb** [comment]
Haha.. I was in the middle of adding him as well.

There are breaking changes in the dekorate API. Even so, I think it's safe because Quarkus users are very unlikely to use the dekorate API or its annotations directly.

**Comment by kdubb** [comment]
⚖️ Risk is integrating some rare breaking changes... the reward is fixing a showstopper for any project that uses git submodes.

**Comment by geoand** [comment]
I am just wondering if for Quarkus 2.7.x it would be better to have a Dekorate `2.8.1` that included the git submodule fix

**Review by iocanel — CHANGES_REQUESTED** [review]
Instead of passing null you can pass the name of the deployment, so that it's more accurate.

**Comment by kdubb** [comment]
@iocanel Doesn't this replicate previous behavior? Which might be better for back porting to 2.7.

Also, I'm not sure where to get the specific name of the deployment in this context.

**Comment by iocanel** [comment]
> I am just wondering if for Quarkus 2.7.x it would be better to have a Dekorate `2.8.1` that included the git submodule fix

I don't think that it really worth, going for a dekorate 2.8.1, as the only things that changed since 2.8.0 are:

- git submodule support
- fix handling of labels when existing resources are involved ( was brought up by @edeandrea last week, don't recall the issue number)
- helm support (which is irrelevant to quarkus but justified the bump to 2.9.0).

**Comment by iocanel** [comment]
> @iocanel Doesn't this replicate previous behavior? Which might be better for back porting to 2.7.
> 
> Also, I'm not sure where to get the specific name of the deployment in this context.

This is what I had in mind: 
https://github.com/ioforks/quarkus/commit/717f578b84408b9d6a95f89da2a80d3e656504b8#diff-790f32c6b9d143ce53d34d972c2354512b470b65ac34021babdef4dbb6532d71L188

**Comment by geoand** [comment]
> helm support (which is irrelevant to quarkus but justified the bump to 2.9.0).

Understood, let's go with it then and backport into `2.7.2.Final`

**Comment by edeandrea** [comment]
@iocanel The labels thing was [mentioned in this comment](https://github.com/quarkusio/quarkus/issues/23417#issuecomment-1029217931) but did not have its own issue. I can open a separate issue for it if you'd like me to.

**Comment by kdubb** [comment]
@iocanel Updated with your suggested changes

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by metacosm** [comment]
There are breaking API changes in 2.9.0, see: https://github.com/quarkiverse/quarkus-operator-sdk/runs/5195176946?check_suite_focus=true#step:6:65981 for example.

**Comment by geoand** [comment]
If that is the case, we probably shouldn't backport, but instead have a new 2.8 release and use it in Quarkus 2.7

**Comment by kdubb** [comment]
@geoand @iocanel Can we get a release of dekorate that can be back ported to 2.7 series? 

Because of the breaking changes we can't just pull in 2.9.0, we have to use a custom build of the Kubernetes plugin; which is not easily publishable for us.

**Comment by geoand** [comment]
You have my vote

**Comment by gsmet** [comment]
@iocanel I'm pushing 2.7.2.Final tomorrow morning Paris time. There will be other 2.7.x after that so I think that, even if it doesn't make 2.7.2.Final, we should get it fixed for 2.7 with a proper backport. Thanks.

**Comment by kdubb** [comment]
@iocanel I hate to be a nag but this is blocking us. 

I tried to create a PR against the tag `2.8.0` with the fix integrated to ease your work but apparently that's not allowed. In any case cherry picking my commit onto `2.8.0` is conflict free and should be all that's necessary; it was created before the other breaking changes. Also, my change looks like the only "fix" that was applied between 2.8 and 2.9.

**Comment by iocanel** [comment]
2.8.1 is on it's way to central.

**Pull request merged**
