### PR TITLE
Upgrade to JBoss Threads 3.0.0.Beta3

### LINKED ISSUE #2218: Native mode - ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread
java.lang.ClassCastException on app shutdown with websocket

Quarkus: 0.14.0
GraalVM: 1.0.0-rc-15
Application: https://github.com/burrsutter/quarkusfingerpaint ++ Quarkus version update

Error is not thrown each time, best way for me was to open 2 tabs with http://127.0.0.1:8080/ URL, do some drawing and shutdown the app. 

```
target/quarkusfingerpaint-1.0.0-runner
2019-04-25 13:49:37,655 INFO  [io.quarkus] (main) Quarkus 0.14.0 started in 0.007s. Listening on: http://[::]:8080
2019-04-25 13:49:37,658 INFO  [io.quarkus] (main) Installed features: [cdi, smallrye-health, undertow-websockets]
2019-04-25 13:49:41,349 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:42,220 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:43,652 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:45,539 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:47,636 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:50,749 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:52,635 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:53,196 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:56,252 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
^C2019-04-25 13:49:59,359 INFO  [org.acm.web.WebSocket] (main) onClose: 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:59,359 INFO  [org.acm.web.WebSocket] (main) onClose: 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:59,360 INFO  [io.quarkus] (main) Quarkus stopped in 0.001s
2019-04-25 13:49:59,360 ERROR [org.jbo.exe.uncaught] (executor-thread-1) Thread Thread[executor-thread-1,5,executor] threw an uncaught exception: java.lang.ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread
	at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:47)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
...hopefully.

**Comment by dmlloyd** [comment]
This should not be merged until @gsmet can confirm that it does in fact fix the problem for him.  If it does not, we can still merge it - it has a couple minor fixes - but I'll want to amend the commit so it doesn't claim to fix #2218.

**Comment by gsmet** [comment]
AFAICS, it doesn't fix the issue.

How to reproduce it:
- rebase your PR on top of master (the quickstart below requires latest master)
- get this PR https://github.com/quarkusio/quarkus-quickstarts/pull/151
- `cd using-opentracing`
- `mvn clean install -Pnative`
- `./target/using-opentracing-1.0-SNAPSHOT-runner`
- in another shell: `curl http://localhost:8080/chain`
- go back to previous shell, you should see:
```
2019-04-29 18:55:28,454 ERROR [org.jbo.exe.uncaught] (executor-thread-2) Thread Thread[executor-thread-2,5,executor] threw an uncaught exception: java.lang.ClassCastException
	at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:33)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```
The line number is a bit off but I checked and it's using Beta2.

**Comment by gsmet** [comment]
@dmlloyd so can you amend your commit message and description so that I can merge without closing the issue it doesn't fix? Thanks!

**Review by gsmet — DISMISSED** [review]
Marking it with `Request changes` so that it doesn't get merged by mistake before we adjust the description and commit message.

**Comment by dmlloyd** [comment]
What do you mean by "the line numbers are a bit off"?

**Comment by gsmet** [comment]
@dmlloyd `Substitutions.java:33` points to https://github.com/jbossas/jboss-threads/blob/master/src/main/java/org/jboss/threads/Substitutions.java#L33 .

**Comment by dmlloyd** [comment]
Ah I hadn't pushed upstream.  I assumed you were looking inside the source JAR, but I guess you must be looking in a git checkout instead.  Anyway I pushed the changes up and it should line up now.

**Comment by dmlloyd** [comment]
This change now brings in the view executor which will (eventually) be used/needed by #467.

**Comment by gsmet** [comment]
The artifact is not yet available on Central, that's why the CI failed.

**Comment by gsmet** [comment]
Artifact deployed, I request a CI re-run.

**Review by gsmet — APPROVED** [review]
Pending CI success.

**Pull request merged**
