### PR TITLE
Use proper case for SameSite cookie

### LINKED ISSUE #38465: RestEasy Reactive sends SameSite cookie param with wrong case
### Describe the bug

With RestEasy Reactive the `Set-Cookie` header uses the wrong case for SameSite parameter values:

```
Set-Cookie: ....; SameSite=LAX
```

RestEasy Classic on the other hand sets the correct case:

```
Set-Cookie: ....; SameSite=Lax
```

The `NewCookieHeaderDelegate` class that converts cookies into headers is not in sync between reactive and classic:

* Reactive: https://github.com/resteasy/resteasy/blob/main/resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/NewCookieHeaderDelegate.java#L144
* Classic: https://github.com/resteasy/resteasy/blob/main/resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/NewCookieHeaderDelegate.java#L144

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stianst**
- Closes #38465

### CODE REVIEW

**Comment by stianst** [comment]
I would like to have this in Quarkus 3.7, as we are trying to remove some custom code around cookie creation in Keycloak.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
@jamezp I wonder if `NewCookie` should be expanded in the spec API to provide a properly cased version of the string with an enum attribute.
Problem is that if at some point, we have something like 'NEW_VALUE' as a new value, we will have to make sure our transformation is updated while including it in the API would solve the issue once and for all.

**Comment by jamezp** [comment]
> @jamezp I wonder if `NewCookie` should be expanded in the spec API to provide a properly cased version of the string with an enum attribute. Problem is that if at some point, we have something like 'NEW_VALUE' as a new value, we will have to make sure our transformation is updated while including it in the API would solve the issue once and for all.

We could definitely make a suggestion to the spec. They may be receptive to it. It would likely just be a generic utility since the implementation is responsible for the `HeaderDelegate` implementations.

**Comment by gsmet** [comment]
I was thinking more of adding an attribute to the enum with the name. Did I miss something?

**Comment by jamezp** [comment]
> I was thinking more of adding an attribute to the enum with the name. Did I miss something?

Oh, apologies. I thought you meant a utility method to camel case an enum :)

**Comment by jonkoops** [comment]
> I wonder if `NewCookie` should be expanded in the spec API to provide a properly cased version of the string with an enum attribute.

+1 for this, this reduces the chance of a bug like this in other codebases.

**Pull request merged**
