### PR TITLE
1.7.1 backports 1

### PR DESCRIPTION
**Pull request by gsmet**
Please don't merge, I will merge it myself.

### CODE REVIEW

**Comment by geoand** [comment]
Hm... I wonder if it's a coincidence that this run passed in CI...

**Comment by gsmet** [comment]
Ah ah, I was going to write something about it :).

**Comment by geoand** [comment]
Something good I hope :)

**Comment by gsmet** [comment]
Well, nothing good or bad. I just don't remember having a backport PR failing that way so there might be something specific to how the master branch is handled somewhere.

**Pull request merged**
