### PR TITLE
Adding BC Fips and OidcClient tests to the native build, with a minor fix

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by sberyozkin** [comment]
@gastaldi @gsmet thanks, `Security2` tests failed - but on the positive side - it just failed to install JDK11, so I'll restart. Still a bit wary of the `checkLog` bit which is run by the `OidcClient` integration test - but hopefully it will be fine in CI

**Comment by sberyozkin** [comment]
MP TCK has failed - I'm not worried about it in context of this PR :-)

**Comment by sberyozkin** [comment]
OK, so all but the MP TCK tests have passed so it is good to go IMHO

**Pull request merged**
