### PR TITLE
Fix memory leak in Agroal local connection cache for Netty's FastThreadLocalThread

### PR DESCRIPTION
**Pull request by Dieken**
https://github.com/quarkusio/quarkus/blob/2.15/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L234

https://github.com/agroal/agroal/blob/2.0/agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java#L745 

https://github.com/agroal/agroal/blob/2.0/agroal-pool/src/main/java/io/agroal/pool/ConnectionHandler.java#L173

1. Quarkus uses `QuarkusNettyConnectionCache` for Agroal local connection cache if it finds class `FastThreadLocal`.
2. Agroal `ConnectionPool` calls `localCache.reset()` in its `ReapTask` periodically (5min in Quarkus), the `FastThreadLocal` instance is created again in `reset()` but actually the old thread local `ConnectionHandler` is still in array `FastThreadLocalThread.threadLocalMap.indexedVariables`.
3. `ConnectionHandler.closeConnection()` doesn't set its fields to null, so it still holds reference to JDBC connection such as `ConnectionImpl` in mysql-connector-j, the JDBC connection still holds some heavy Java objects, thus `localCache.reset()` leads to heavy memory leak after running for about a week.

The solution is to not create `FastThreadLocal` again, so the memory leak is limited by total count of Java threads that use JDBC to access database.

This bug is introduced since Quarkus-2.2.0 at https://github.com/quarkusio/quarkus/issues/17304 .

### CODE REVIEW

**Comment by Dieken** [comment]
An example of memory leak.

image

**Comment by Dieken** [comment]
@gsmet @stuartwdouglas seems you often touched agroal extension, could you review this PR? I have many services influenced by this bug, would like to get this merged soon and backported to Quarkus >= 2.2.

**Comment by geoand** [comment]
@franz1981 @barreiro can you comment on this one please?

**Comment by franz1981** [comment]
@Dieken why keeping the fast thread local as volatile at this point?

**Comment by Dieken** [comment]
> @Dieken why keeping the fast thread local as volatile at this point? I would do like this:
> 
> * making it final, but will allocate "something" even if no `FastThreadLocalThread` or `JBossThread` are going to use it
>   or
> * leave it volatile but use a atomic reference field updater or a synchronized block the very first time cache's `put` is executed, while `get` can just return `null` if  `connectionCache` itself is not initialized yet

Indeed it's unnecessary to keep the `volatile` keyword, I will push again to take option 1.

**Comment by Dieken** [comment]
```
/Volumes/actions-files/githubactions/actions-runner/_work/_temp/293eb1d0-b809-492a-9b02-8fa310006ba1.sh: line 1: devtools/gradle/gradlew: No such file or directory
```

This test failure isn’t caused by this PR.

**Comment by geoand** [comment]
Don't worry about the MacOS runner failures

**Comment by Dieken** [comment]
Sorry to disturb you,  could we accelerate this PR? I have a dozen of Quarkus services,  the more DB access threads the more frequent OOM crash,  one of them crashes every three days which is rather important core service, we didn't realize the root cause for about a year until last week.

**Comment by gsmet** [comment]
@yrodiere could you have a look at this one on Monday? Might be a good candidate for 2.15.3.Final.

**Review by yrodiere — APPROVED** [review]
Makes sense, the previous code definitely looks wrong.

**Comment by yrodiere** [comment]
Merged, thanks @Dieken!

**Comment by hajdukda** [comment]
Are there any plans to backport it to: 2.9.2.Final ?

**Comment by Dieken** [comment]
The bug is introduced in v2.2.0, the patch is backported to some old releases:

```
$ for v in (seq 1 16); git tag -l | grep 2.$v | tail -1 | while read t; echo $t; git grep 'Do our best' $t; echo; end; end
2.2.1.Final

2.2.5.Final

2.3.1.Final

2.4.2.Final

2.5.4.Final

2.6.3.Final

2.7.7.Final
2.7.7.Final:extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/QuarkusNettyConnectionCache.java:        // Do our best to release memory. In fact `io.agroal.pool.ConnectionPool` calls

2.8.3.Final

2.9.2.Final

2.10.4.Final

2.11.3.Final

2.12.3.Final

2.13.7.Final
2.13.7.Final:extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/QuarkusNettyConnectionCache.java:        // Do our best to release memory. In fact `io.agroal.pool.ConnectionPool` calls

2.14.3.Final

2.15.3.Final
2.15.3.Final:extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/QuarkusNettyConnectionCache.java:        // Do our best to release memory. In fact `io.agroal.pool.ConnectionPool` calls

2.16.0.Final
2.16.0.Final:extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/QuarkusNettyConnectionCache.java:        // Do our best to release memory. In fact `io.agroal.pool.ConnectionPool` calls
```

**Comment by hajdukda** [comment]
Uh Oh so:
- 2.7.7.Final
- 2.13.7.Final
- 2.15.3.Final
- 2.16.0.Final

k, thx for info.

**Comment by hajdukda** [comment]
@Dieken Do you think the same could be the case for VertxThread ?

image

**Comment by Dieken** [comment]
> @Dieken Do you think the same could be the case for VertxThread (extends FastThreadLocalThread)?
> 

Yes. 

* Your class path contains `FastThreadLocalThread` so `QuarkusNettyConnectionCache` is used: https://github.com/quarkusio/quarkus/blob/2.15/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L234  
* `if (thread instanceof FastThreadLocalThread` makes the connections be really cached for `VertxThread`, then the bug happens due to `QuarkusNettyConnectionCache.reset()`,  see detailed description in the first comment above. https://github.com/quarkusio/quarkus/blob/2.15.2.Final/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/QuarkusNettyConnectionCache.java#L17

**Pull request merged**
