### PR TITLE
Validate REST Data Panache request body

### LINKED ISSUE #15492: Validation for REST endpoints does not return messages about the constraints violated
**Describe the bug**
After the changes in https://github.com/quarkusio/quarkus/pull/15447, now when using REST Panache or Spring Data REST quarkus extensions, we got 400 when there are constraint violations. 

The problem now is that the response does not return the constraints that have been violated. 

**Expected behavior**
After a REST violation, It's expected to receive something like:

```json
{
    "classViolations": [],
    "parameterViolations": [
        {
            "constraintType": "PARAMETER",
            "message": "Title may not be blank",
            "path": "addBook.book.title",
            "value": ""
        }
    ],
    "propertyViolations": [],
    "returnValueViolations": []
}
```

* If we're using JSON... *

**Actual behavior**
No message is returned.

**To Reproduce**
1- git clone https://github.com/Sgitario/beefy-scenarios
2- git checkout reproducer_15409
3- cd beefy-scenarios/602-spring-data-rest
4- mvn clean verify
There are some tests failing due to this issue.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 999-SNAPSHOT

### PR DESCRIPTION
**Pull request by gytis**
Fixes https://github.com/quarkusio/quarkus/issues/15492

### CODE REVIEW

**Comment by geoand** [comment]
Might be a dump question, but does panache rest depend on validation?

**Comment by gytis** [comment]
Not directly, but it is coming transitively from somewhere. It doesn't have Hibernate Validator thought, but the annotation doesn't break it. 
Should I maybe add a capability check?

**Comment by geoand** [comment]
You could add a check, yeah.

Ideally also one of the integration tests would not have Hibernate Validator and show that the application still works.

**Comment by gytis** [comment]
The tests in the deployment don't have it and they seem fine. But I can add the check just in case.

**Comment by gytis** [comment]
@geoand added a capability check.

**Review by geoand — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
