### PR TITLE
Make OIDC Google example more complete

### LINKED ISSUE #33053: Document happy path Google auth and augmentation
### Description

Current OIDC tutorials and reference documents can be considered quite technical and some users might find it challenging to figure out how to setup OIDC.
This issue will continue with the idea of creating Getting Started Fast with Security series of tutorials, with the Basic and JPA tutorial being the first and only such a guide so far, with the plan always being to follow up with something for OIDC.
The next guide will show a Happy path Google authentication with 3 properties only

### Implementation ideas

- Show how to register Quarkus App in Google dashboard
- Show  a simple endpoint injecting ID token and using it to interact with the user
- Show a typical structure of ID token, explain how it differs from access token
- The endpoint will show how to logout using the injected OidcSession
- Security identity augmentor is introduced showing how to augment Google tokens for them to go through RBAC check
- Make it all work with 3 lines of config only

CC @maxandersen @cescoffier @stuartwdouglas @FroMage @n1hility

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #33053.

The well known providers doc already covers how to register a Google application, how to prepare and configure a REST client targeting one of its services, `Calendar`, but this PR makes it more complete, showing an example endpoint, straight from our demo.

CC @cescoffier

### CODE REVIEW

**Comment by sberyozkin** [comment]
Attempted to address a couple of Linting with Vale comments

**Comment by sberyozkin** [comment]
Sorry, need to add a couple of images

**Review by gastaldi — APPROVED** [review]

**Comment by sberyozkin** [comment]
Hi @gastaldi I've just pushed a minor update, including two images, showing what users have to do if they want to try the  Quarkus endpoint

**Comment by sberyozkin** [comment]
I'll update if you'll have some comments

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]

**Pull request merged**
