### PR TITLE
Add support for Path in GeneratedStaticResourceBuildItem

### PR DESCRIPTION
**Pull request by ia3andy**
This PR:
- adds support for `Path` in `GeneratedStaticResourceBuildItem`
- renames `path` to `endpoint` to be consistant with `NotFoundPageDisplayableEndpointBuildItem` and not be confused with the file Path
- adds normal and dev-mode tests for file based generated static resources
- `AdditionalStaticResourceBuildItem` will still be served in dev-mode to avoid breaking dev-mode on existing apps

Using `Path` instead of `byte[]` allow to achieve live-reload without restarting Quarkus.

### CODE REVIEW

**Comment by ia3andy** [comment]
cc @mcruzdev

**Comment by ia3andy** [comment]
I am currently testing it with the web-bundler

**Comment by ia3andy** [comment]
Testing on web-bundler, I will test on Quinoa on monday

**Comment by ia3andy** [comment]
It's good to merge if approved and CI is ok

**Review by FroMage — APPROVED** [review]
I didn't read the details, but the goals state look legit.

**Pull request merged**
