### PR TITLE
Register all implementation of ExtensionAdapter in k8s client extension

### LINKED ISSUE #29096: Provider io.fabric8.knative.client.KnativeExtensionAdapter not found
### Describe the bug

Native binary fails to start when using the `quarkus-kubernetes-client` with `knative-client`.

### Expected behavior

start without issues.

### Actual behavior

```
ERROR: Failed to start application (with profile prod)
java.util.ServiceConfigurationError: io.fabric8.kubernetes.client.extension.ExtensionAdapter: Provider io.fabric8.knative.client.KnativeExtensionAdapter not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:114)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.fabric8.kubernetes.client.impl.Adapters.discoverServices(Adapters.java:106)
	at io.fabric8.kubernetes.client.impl.Adapters.<init>(Adapters.java:51)
	at io.fabric8.kubernetes.client.impl.BaseClient.<init>(BaseClient.java:102)
	at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.<init>(KubernetesClientImpl.java:191)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:79)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:98)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:60)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:56)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:48)
	at org.kie.kogito.addons.quarkus.k8s.KubeDiscoveryConfigSourceInterceptor.<init>(KubeDiscoveryConfigSourceInterceptor.java:42)
	at org.kie.kogito.addons.quarkus.k8s.config.ServiceDiscoveryConfigBuilder.configBuilder(ServiceDiscoveryConfigBuilder.java:27)
	at io.quarkus.runtime.configuration.ConfigUtils.configBuilder(ConfigUtils.java:197)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### How to Reproduce?

Reproducer:

Steps:

1. create a new Quarkus app.
2. make sure that the `quarkus.platform.version` is 2.14.0.CR1
3. add the following dependencies: 
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kubernetes-client</artifactId>
    </dependency>
        <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>knative-client</artifactId>
    </dependency>
```
4. update the `GreetingResource` class with some usage of the knative client, e.g.:
```
        knativeClient = new DefaultKnativeClient();
        knativeClient.adapt(KnativeClient.class);
```
5. access the hello endpoint.

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.19.12-200.fc36.x86_64", arch: "amd64", family: "unix"

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #29096

### CODE REVIEW

**Comment by geoand** [comment]
cc @manusa

**Comment by geoand** [comment]
@iocanel can you take a look at this one?

It would be nice to get it into the next 2.14 release

**Review by iocanel — APPROVED** [review]
This is amazing!

**Comment by geoand** [comment]
Thanks for the review

**Comment by manusa** [comment]
> cc @manusa

Hi @geoand sorry for the late reply :sweat: 

This one looks OK.

However, maybe we want to do:
```java
serviceProviderProducer.produce(ServiceProviderBuildItem.allProvidersFromClassPath(ExtensionAdapter.class.getName()));
```
for the `HttpClient.Factory.class` class too.

Regarding this option `ServiceProviderBuildItem.allProvidersFromClassPath`, I learned about this on this PR. I assume this will discover any SPI provider that's available on the application's compile classpath.

If so, this will be very handy once we merge and release https://github.com/fabric8io/kubernetes-client/pull/4511

**Comment by geoand** [comment]
@manusa thanks for the info. Feel free to send a PR updating the k8s client support

**Comment by manusa** [comment]
:+1: Will do. I'll probably tackle everything once we release Kubernetes Client 6.3.0 with the mentioned improvement (hopefully next week :crossed_fingers:)

**Comment by geoand** [comment]
👌

**Comment by gsmet** [comment]
Actually, this can't be backported to 2.13 as `io.fabric8.kubernetes.client.extension.ExtensionAdapter` is a new thing in Kubernetes Client 6.x and 2.13 is still using 5.x.

**Comment by gsmet** [comment]
Ah no, actually, it's there but in a different package. I will adjust the package in the backport.

**Pull request merged**
