### PR TITLE
Dev UI - scheduler improvements

### PR DESCRIPTION
**Pull request by mkouba**
- add option to pause/resume individual jobs with identity
- add Scheduler#isPaused(identity)
- show the configured values in the schedules table; e.g. "{cron.expr} configured as */5 * * * * ?"
- fix links to config expressions in the docs

### CODE REVIEW

**Comment by machi1990** [comment]
the code lgtm.

@mkouba would you happen to have a screenshot of how it will look in the Dev UI? 
Also there are some test failing.

**Comment by mkouba** [comment]
> Also there are some test failing.

Yep, one of the Dev UI smoke tests failed - fixed.

> would you happen to have a screenshot of how it will look in the Dev UI?

Screenshot from 2021-07-23 12-30-15

Note that the pause/resume job buttons cannot be placed in the "Actions" column because they apply to a specific `@Scheduled` which is repeatable, i.e. multiple buttons may exist for a particula scheduled method.

**Comment by machi1990** [comment]
> > Also there are some test failing.
> 
> Yep, one of the Dev UI smoke tests failed - fixed.
> 

perfect, let's wait for CI to pass. 

> > would you happen to have a screenshot of how it will look in the Dev UI?
> 
> Screenshot from 2021-07-23 12-30-15
>

Really cool. Thank you for the improvement. 
 
> Note that the pause/resume job buttons cannot be placed in the "Actions" column because they apply to a specific `@Scheduled` which is repeatable, i.e. multiple buttons may exist for a particula scheduled method.

Makes sense.

**Review by machi1990 — APPROVED** [review]

**Comment by famod** [comment]
Nice! Ship has sailed for 2.1 I suppose?

**Comment by mkouba** [comment]
> Nice! Ship has sailed for 2.1 I suppose?

Yeah, this should probably target 2.2.

**Pull request merged**
