### PR TITLE
Fix JDBC test failures in Windows

### LINKED ISSUE #4433: elytron-jdbc-security tests are unstable
**Describe the bug**
Fails in this [build](https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=9286&view=logs): 
```
[ERROR] Tests run: 14, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 1.018 s <<< FAILURE! - in io.quarkus.elytron.security.jdbc.MultipleDataSourcesTest
[ERROR] testJaxrsGetRoleSuccess  Time elapsed: 0.078 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```
No further clues are available in the rest of the trace.

@danielpetisme @stuartwdouglas can you please check if you have few secs ?
On my Fedora laptop it passes:
```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.494 s - in io.quarkus.elytron.security.jdbc.MultipleDataSourcesTest
```

### PR DESCRIPTION
**Pull request by gastaldi**
@gsmet @danielpetisme please review

Fixes #4433

### CODE REVIEW

**Comment by danielpetisme** [comment]
Good for me

**Review by gsmet — APPROVED** [review]
Let's wait for CI.

**Comment by gastaldi** [comment]
@gsmet yay green build!

**Comment by gsmet** [comment]
Thanks @gastaldi !

**Pull request merged**
