### PR TITLE
Bump rest-assured to 4.1.1

### PR DESCRIPTION
**Pull request by gastaldi**
Changelog: https://github.com/rest-assured/rest-assured/blob/master/changelog.txt

### CODE REVIEW

**Comment by gsmet** [comment]
We had this issue open https://github.com/quarkusio/quarkus/issues/3607 .

We need to check it's no longer an issue.

**Comment by gastaldi** [comment]
According to the changelog, in 4.1.0 they are no longer depending on hamcrest-core or hamcrest-library, instead the hamcrest module is used directly.

**Comment by gsmet** [comment]
But doesn't that mean that you would have 2 conflicting libraries? You just don't have Maven complaining because the dependencies have a different name.

**Comment by gastaldi** [comment]
You're right, that's exactly what's going on. I think one of the solutions is to migrate all tests to JUnit 5 and deprecate the junit4 extension, otherwise the tests will be stuck forever depending on a JAR that's no longer maintained (Junit4).

image

Dependency tree of `extensions/hibernate-orm/deployment`:

```
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ quarkus-hibernate-orm-deployment ---
[INFO] io.quarkus:quarkus-hibernate-orm-deployment:jar:999-SNAPSHOT
[INFO] +- io.quarkus:quarkus-core-deployment:jar:999-SNAPSHOT:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.wildfly.common:wildfly-common:jar:1.5.0.Final-format-001:compile
[INFO] |  +- io.quarkus.gizmo:gizmo:jar:1.0.0.Alpha7:compile
[INFO] |  +- org.jboss:jandex:jar:2.1.1.Final:compile
[INFO] |  +- org.ow2.asm:asm:jar:7.1:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:999-SNAPSHOT:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  +- io.smallrye:smallrye-config:jar:1.3.9:compile
[INFO] |  |  |  \- org.eclipse.microprofile.config:microprofile-config-api:jar:1.3:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.3:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.1.0.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.0.0.Beta5:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  |  \- org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final:compile
[INFO] |  +- io.quarkus:quarkus-builder:jar:999-SNAPSHOT:compile
[INFO] |  \- org.graalvm.sdk:graal-sdk:jar:19.2.0:compile
[INFO] +- io.quarkus:quarkus-hibernate-orm:jar:999-SNAPSHOT:compile
[INFO] |  +- io.quarkus:quarkus-agroal:jar:999-SNAPSHOT:compile
[INFO] |  |  +- org.jboss.narayana.jta:narayana-jta:jar:5.9.8.Final:compile
[INFO] |  |  |  +- org.jboss:jboss-transaction-spi:jar:7.6.0.Final:compile
[INFO] |  |  |  \- org.jboss.spec.javax.resource:jboss-connector-api_1.7_spec:jar:1.0.0.Final:compile
[INFO] |  |  +- org.jboss.narayana.jts:narayana-jts-integration:jar:5.9.8.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
[INFO] |  |  +- io.agroal:agroal-api:jar:1.5:compile
[INFO] |  |  +- io.agroal:agroal-narayana:jar:1.5:compile
[INFO] |  |  \- io.agroal:agroal-pool:jar:1.5:compile
[INFO] |  +- io.quarkus:quarkus-narayana-jta:jar:999-SNAPSHOT:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-reactive-streams-operators:jar:1.0.9:compile
[INFO] |  |  |  +- org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-api:jar:1.0:compile
[INFO] |  |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  |  |  +- org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-core:jar:1.0:compile
[INFO] |  |  |  \- io.reactivex.rxjava2:rxjava:jar:2.2.9:compile
[INFO] |  |  +- io.smallrye:smallrye-context-propagation-jta:jar:1.0.11:compile
[INFO] |  |  |  \- javax.transaction:javax.transaction-api:jar:1.3:compile
[INFO] |  |  \- io.smallrye.reactive:smallrye-reactive-converter-api:jar:1.0.9:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.4.4.Final:compile
[INFO] |  |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.9.11:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  |  +- org.dom4j:dom4j:jar:2.1.1:compile
[INFO] |  |  \- org.hibernate.common:hibernate-commons-annotations:jar:5.1.0.Final:compile
[INFO] |  +- org.hibernate:quarkus-local-cache:jar:0.1.0:compile
[INFO] |  |  \- com.github.ben-manes.caffeine:caffeine:jar:2.6.2:compile
[INFO] |  \- io.quarkus:quarkus-caffeine:jar:999-SNAPSHOT:compile
[INFO] +- io.quarkus:quarkus-narayana-jta-deployment:jar:999-SNAPSHOT:compile
[INFO] +- io.quarkus:quarkus-agroal-deployment:jar:999-SNAPSHOT:compile
[INFO] +- io.quarkus:quarkus-arc-deployment:jar:999-SNAPSHOT:compile
[INFO] |  +- io.quarkus:quarkus-arc:jar:999-SNAPSHOT:compile
[INFO] |  |  +- io.quarkus.arc:arc:jar:999-SNAPSHOT:compile
[INFO] |  |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.0-RC1:compile
[INFO] |  \- io.quarkus.arc:arc-processor:jar:999-SNAPSHOT:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- io.quarkus:quarkus-junit5-internal:jar:999-SNAPSHOT:test
[INFO] |  +- org.jboss.shrinkwrap:shrinkwrap-depchain:pom:1.2.6:test
[INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:test
[INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.6:test
[INFO] |  |  \- org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.6:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.5.1:test
[INFO] |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  \- org.junit.platform:junit-platform-commons:jar:1.5.1:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.5.1:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-engine:jar:5.5.1:test
[INFO] |  |  \- org.junit.platform:junit-platform-engine:jar:1.5.1:test
[INFO] |  +- io.quarkus:quarkus-test-common:jar:999-SNAPSHOT:test
[INFO] |  |  \- io.quarkus:quarkus-jsonp-deployment:jar:999-SNAPSHOT:test
[INFO] |  |     \- io.quarkus:quarkus-jsonp:jar:999-SNAPSHOT:test
[INFO] |  |        \- org.glassfish:javax.json:jar:1.1.4:test
[INFO] |  +- javax.enterprise:cdi-api:jar:2.0.SP1:compile
[INFO] |  |  +- javax.el:javax.el-api:jar:3.0.0:compile
[INFO] |  |  \- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO] |  \- io.quarkus:quarkus-development-mode:jar:999-SNAPSHOT:test
[INFO] +- io.quarkus.gizmo:gizmo:test-jar:tests:1.0.0.Alpha7:test
[INFO] |  \- org.ow2.asm:asm-util:jar:7.1:compile
[INFO] |     +- org.ow2.asm:asm-tree:jar:7.1:compile
[INFO] |     \- org.ow2.asm:asm-analysis:jar:7.1:compile
[INFO] +- io.quarkus:quarkus-resteasy-deployment:jar:999-SNAPSHOT:test
[INFO] |  +- io.quarkus:quarkus-resteasy-server-common-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  +- io.quarkus:quarkus-resteasy-common-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  |  \- io.quarkus:quarkus-resteasy-common:jar:999-SNAPSHOT:test
[INFO] |  |  |     +- org.jboss.resteasy:resteasy-core:jar:4.3.0.Final:test
[INFO] |  |  |     |  +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:1.0.2.Final:test
[INFO] |  |  |     |  +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:1.0.1.Final:test
[INFO] |  |  |     |  \- org.jboss.resteasy:resteasy-core-spi:jar:4.3.0.Final:test
[INFO] |  |  |     +- org.jboss.resteasy:resteasy-context-propagation:jar:4.3.0.Final:test
[INFO] |  |  |     |  \- io.smallrye:smallrye-context-propagation:jar:1.0.11:test
[INFO] |  |  |     |     \- io.smallrye:smallrye-context-propagation-api:jar:1.0.11:test
[INFO] |  |  |     \- com.sun.activation:jakarta.activation:jar:1.2.1:test
[INFO] |  |  +- io.quarkus:quarkus-jaxb-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  |  \- io.quarkus:quarkus-jaxb:jar:999-SNAPSHOT:test
[INFO] |  |  \- io.quarkus:quarkus-resteasy-server-common:jar:999-SNAPSHOT:test
[INFO] |  |     \- javax.validation:validation-api:jar:2.0.1.Final:test
[INFO] |  +- io.quarkus:quarkus-undertow-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  +- io.quarkus.http:quarkus-http-servlet:jar:3.0.0.Alpha5:test
[INFO] |  |  |  +- io.quarkus.http:quarkus-http-core:jar:3.0.0.Alpha5:test
[INFO] |  |  |  |  +- io.quarkus.http:quarkus-http-http-core:jar:3.0.0.Alpha5:test
[INFO] |  |  |  |  |  \- io.netty:netty-buffer:jar:4.1.39.Final:test
[INFO] |  |  |  |  \- io.netty:netty-codec-http:jar:4.1.39.Final:test
[INFO] |  |  |  |     +- io.netty:netty-common:jar:4.1.39.Final:test
[INFO] |  |  |  |     +- io.netty:netty-transport:jar:4.1.39.Final:test
[INFO] |  |  |  |     +- io.netty:netty-codec:jar:4.1.39.Final:test
[INFO] |  |  |  |     \- io.netty:netty-handler:jar:4.1.39.Final:test
[INFO] |  |  |  \- org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:jar:1.0.0.Final:test
[INFO] |  |  +- io.quarkus:quarkus-undertow:jar:999-SNAPSHOT:test
[INFO] |  |  |  +- io.quarkus:quarkus-vertx-http:jar:999-SNAPSHOT:test
[INFO] |  |  |  |  +- io.quarkus:quarkus-vertx-core:jar:999-SNAPSHOT:test
[INFO] |  |  |  |  |  +- io.quarkus:quarkus-netty:jar:999-SNAPSHOT:test
[INFO] |  |  |  |  |  \- io.quarkus:quarkus-jackson:jar:999-SNAPSHOT:test
[INFO] |  |  |  |  |     \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9.3:test
[INFO] |  |  |  |  |        +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:test
[INFO] |  |  |  |  |        \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:test
[INFO] |  |  |  |  \- io.vertx:vertx-web:jar:3.8.1:test
[INFO] |  |  |  |     +- io.vertx:vertx-web-common:jar:3.8.1:test
[INFO] |  |  |  |     +- io.vertx:vertx-auth-common:jar:3.8.1:test
[INFO] |  |  |  |     \- io.vertx:vertx-bridge-common:jar:3.8.1:test
[INFO] |  |  |  \- io.quarkus.http:quarkus-http-vertx-backend:jar:3.0.0.Alpha5:test
[INFO] |  |  |     \- io.vertx:vertx-core:jar:3.8.1:test
[INFO] |  |  |        +- io.netty:netty-handler-proxy:jar:4.1.39.Final:test
[INFO] |  |  |        |  \- io.netty:netty-codec-socks:jar:4.1.39.Final:test
[INFO] |  |  |        +- io.netty:netty-codec-http2:jar:4.1.39.Final:test
[INFO] |  |  |        +- io.netty:netty-resolver:jar:4.1.39.Final:test
[INFO] |  |  |        \- io.netty:netty-resolver-dns:jar:4.1.39.Final:test
[INFO] |  |  |           \- io.netty:netty-codec-dns:jar:4.1.39.Final:test
[INFO] |  |  +- io.quarkus:quarkus-vertx-http-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  |  \- io.quarkus:quarkus-vertx-core-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  |     +- io.quarkus:quarkus-netty-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  |     \- io.quarkus:quarkus-jackson-deployment:jar:999-SNAPSHOT:test
[INFO] |  |  +- io.quarkus:quarkus-kubernetes-spi:jar:999-SNAPSHOT:test
[INFO] |  |  \- org.jboss.metadata:jboss-metadata-web:jar:11.0.0.Final:test
[INFO] |  |     \- org.jboss.metadata:jboss-metadata-common:jar:11.0.0.Final:test
[INFO] |  \- io.quarkus:quarkus-resteasy:jar:999-SNAPSHOT:test
[INFO] +- io.quarkus:quarkus-hibernate-validator-deployment:jar:999-SNAPSHOT:test
[INFO] |  \- io.quarkus:quarkus-hibernate-validator:jar:999-SNAPSHOT:test
[INFO] |     \- org.hibernate.validator:hibernate-validator:jar:6.1.0.Alpha6:test
[INFO] +- io.quarkus:quarkus-jdbc-h2:jar:999-SNAPSHOT:test
[INFO] |  +- com.h2database:h2:jar:1.4.197:test
[INFO] |  \- org.locationtech.jts:jts-core:jar:1.15.0:test
[INFO] +- io.rest-assured:rest-assured:jar:4.1.1:test
[INFO] |  +- org.codehaus.groovy:groovy:jar:2.5.6:test
[INFO] |  +- org.codehaus.groovy:groovy-xml:jar:2.5.6:test
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.9:test
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.11:test
[INFO] |  |  \- commons-codec:commons-codec:jar:1.11:test
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.3:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.1:test
[INFO] |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
[INFO] |  +- io.rest-assured:json-path:jar:4.1.1:test
[INFO] |  |  +- org.codehaus.groovy:groovy-json:jar:2.5.6:test
[INFO] |  |  \- io.rest-assured:rest-assured-common:jar:4.1.1:test
[INFO] |  \- io.rest-assured:xml-path:jar:4.1.1:test
[INFO] |     +- org.apache.commons:commons-lang3:jar:3.8.1:test
[INFO] |     \- org.apache.sling:org.apache.sling.javax.activation:jar:0.1.0:test
[INFO] +- org.hibernate:hibernate-envers:jar:5.4.4.Final:test
[INFO] |  \- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:test
[INFO]    +- javax.xml.bind:jaxb-api:jar:2.3.1:test
[INFO]    +- org.glassfish.jaxb:txw2:jar:2.3.1:test
[INFO]    +- com.sun.istack:istack-commons-runtime:jar:3.0.7:test
[INFO]    +- org.jvnet.staxex:stax-ex:jar:1.8:test
[INFO]    \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:test
```

**Comment by gastaldi** [comment]
I created https://github.com/quarkusio/quarkus/pull/3915 to remove the conflict in the module.

**Comment by gastaldi** [comment]
I'm closing this PR until this Hamcrest mess is resolved ;)

**Pull request closed without merging**
