### PR TITLE
update and align RX Java 2 version to 2.2.17

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by gsmet** [comment]
Does it make sense to add it to Dependabot and have it handled for us? I mean we are not forced to accept all the changes but it will update everything in a consistent way.

**Review by gsmet — APPROVED** [review]

**Comment by cescoffier** [comment]
Agreed, I was surprised actually.

**Comment by geoand** [comment]
+1 for the dependabot change

**Comment by cescoffier** [comment]
Just opened: https://github.com/quarkusio/quarkus/pull/6542/files

**Pull request merged**
