### PR TITLE
Fix issue with KnownPathResource manager in native

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by melloware** [comment]
Looks like the unit tests are failing?

**Comment by stuartwdouglas** [comment]
Yea, should be fixed now.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@stuartwdouglas this LGTM and when I test locally things seem to work but the true test is the nightly build in GitHub Actions which runs on Linux.  Is there any way we can get this merged so I can watch tonights nightly build of PrimeFaces and OmniFaces?

**Comment by melloware** [comment]
More info and test case: https://github.com/quarkusio/quarkus/pull/33018

**Review by gsmet — APPROVED** [review]

**Pull request merged**
