### PR TITLE
OpenAPI: Added support for `quarkus.resteasy-reactive.path`

### LINKED ISSUE #19434: Setting quarkus.resteasy.path not reflected in OpenAPI or Swagger
### Describe the bug

When I set the "quarkus.resteast.path" it works making API calls directly but does not get reflected in the OpenAPI or Swagger.

Using @ApplicationPath and setting eash @Path looks to work.

### Expected behavior

OpenAPI and Swagger reflect the path set in the application properties.

### Actual behavior

RESTful calls works but OpenAPI and Swagger do not reflect the path.  From Swagger invoking an endpoint gives a 404.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #19434

@geoand - I think a better fix would be that RestEasy Reactive also produce a `ResteasyJaxrsConfigBuildItem` like the RestEasy classic ? 

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by ebullient — APPROVED** [review]

**Comment by ebullient** [comment]
> @geoand - I think a better fix would be that RestEasy Reactive also produce a `ResteasyJaxrsConfigBuildItem` like the RestEasy classic ?

The problem is that the two extensions have _zero_ common classes (including build items). Part of why I moved all of the resteasy stuff into the "resteasy-classic" directory was to really emphasize that even though some of those have "common" in the name.. they aren't common between reactive and classic, only between resteasy server and client.

**Comment by ebullient** [comment]
Amendment: What would have been better, IMO, was for both extensions to use `quarkus.rest.path`, since they can't be used at the same time anyway. Making all downstream extensions understand two paths is.. meh. But that's just my opinion. ;)

**Comment by phillip-kruger** [comment]
+1 on that

**Comment by stuartwdouglas** [comment]
I am also +1 on using `quarkus.rest.path`

**Comment by phillip-kruger** [comment]
@stuartwdouglas @ebullient - At the moment we have `quarkus.resteasy.path` and `quarkus.resteasy-reactive.path` and we want both of those to also support `quarkus.rest.path` ? Is that something we want as part of this PR ? Or should I just add support for 
`quarkus.rest.path` here and once it's in RestEasy this will work (still supporting the old properties as well) ?

**Comment by stuartwdouglas** [comment]
I would just deprecate `quarkus.resteasy-reactive.path` and update RR to support `quarkus.rest.path`. I don't know if I would even bother making `quarkus.resteasy-reactive.path` work.

**Comment by phillip-kruger** [comment]
@stuartwdouglas ok cool. I am a bit concerned that the reversed has happened it seems (see this comment: https://github.com/quarkusio/quarkus/issues/19434#issuecomment-901086235) from @ebullient . So I am worried that there was a reason that `rest.path` was deprecated in favor of the other two and now we are revering it ? Also, is there as shared common module used by both classic and reactive that can host this property ?

**Comment by stuartwdouglas** [comment]
Oh ok, reading the issue I assumed that quarkus.rest.path was used by Resteasy Classic, but it appears this is not the case. I think this PR is ok as is then.

**Comment by phillip-kruger** [comment]
Thanks @stuartwdouglas :)

**Comment by gsmet** [comment]
Yes, I prefer we keep it that way rather than introducing a `quarkus.rest` prefix out of the blue.

I think this should be backported though if we want to make RESTEasy Reactive a first class citizen in 2.2. Adding the label.

**Pull request merged**
