### PR TITLE
Bump Kotlin to 1.5 for both language and coroutines

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
The failures are legitimate issues that need to be addressed,

@evanchooly was this bump on your radar?

**Comment by evanchooly** [comment]
Yeah. I'm already working it.

**Comment by geoand** [comment]
Excellent, 👍🏼

**Comment by famod** [comment]
FTR, there is also #16806

**Comment by geoand** [comment]
I was not aware of it at all.

@evanchooly feel free to close this or use it's bits if you like

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/18244

**Pull request closed without merging**
