### PR TITLE
Mutiny 0.15.0 support

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
Currently a draft PR (Mutiny 0.15.0 hasn't been released yet).

Operator logging is a new addition to the extension work.

**Comment by jponge** [comment]
Mutiny has been released

**Review by geoand — APPROVED** [review]
LGTM

**Review by cescoffier — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
The PR is incorrect. `mutiny-vertx.version` has been replaced by `smallrye-reactive-utils.version`. Will fix and force push.

**Review by gsmet — APPROVED** [review]

**Comment by jponge** [comment]
@gsmet what did you do to the commit?

**Comment by gsmet** [comment]
I just adjusted the correct variable. I think you got it wrong when you rebased (you probably had a conflict).

**Comment by gsmet** [comment]
This one: https://github.com/quarkusio/quarkus/pull/15920/files#diff-2b7d71809e1063e0d0411cbe30d606e12b984790680195567e7b8bde0d078e3fR54 .

**Comment by jponge** [comment]
Ok thanks

**Pull request merged**
