### PR TITLE
Grammar corrections for en-us

### PR DESCRIPTION
**Pull request by msscsh**
Fixing some grammar issues i found in the Qute documentation.

Duplicate of the closed PR with @gastaldi suggestion:
https://github.com/quarkusio/quarkus/pull/44563

### CODE REVIEW

**Comment by gastaldi** [comment]
Can you please squash both commits?

**Comment by msscsh** [comment]
> Can you please squash both commits?

sure

**Comment by msscsh** [comment]
commits squasheds @gastaldi

**Review by mkouba — APPROVED** [review]
Thanks!

**Pull request merged**
