### PR TITLE
Bump smallrye-open-api from 3.2.0 to 3.3.0, fix OpenAPI security issues

### LINKED ISSUE #21126: OpenAPI Auto security OIDC only works with keycloak
### Describe the bug

OpenAPI Auto security is a great feature, it generates OpenAPI/Swagger config automatically based on the security configuration. However, if OIDC is used the generated OpenAPI config contains wrong hardcoded url paths. https://github.com/quarkusio/quarkus/blob/5c3ec06e41774c9f47f09ca74bffa8512832dea3/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L331

### Expected behavior

If OIDC is used (with autodiscovery), the configured/discovered urls should be used instead of hardcoded ones, which are only valid for keycloak.

### Actual behavior

Currently only the base url of the authorization server can be configured, but the paths of the different endpoints are hardcoded.

### How to Reproduce?

1. create a project with oidc, OpenAPI and Swagger UI
2. configure `quarkus.oidc.auth-server-url` of on oidc server which is not keycloak
3. start dev mode
4. open Swagger UI
5. try to authroize in the UI
6. you are redirected to the wrong url

### Output of `uname -a` or `ver`

Linux leon-pc 5.13.0-20-generic #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-Ubuntu-0ubuntu3)
OpenJDK 64-Bit Server VM (build 11.0.12+7-Ubuntu-0ubuntu3, mixed mode, sharing)
```

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

`2.3.0.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

#19680

### LINKED ISSUE #27373: OpenAPI extension creates bad oapi export with @RolesAllowed
### Describe the bug

Adding a `@RolesAllowed` annotation to a method that is to be documented with OpenAPI results in the following verification warning:

> Security Requirement 'SecurityScheme' scopes must be an empty array because the referenced Security Definition not "oauth2" or "openIdConnect".
> Security Requirements can be specified for basic, apiKey, or oauth. When using basic or apiKey authentication, the security requirement must NOT provide a list of scopes (the list of scopes must be empty). In other words, scopes are only valid when using OAuth 2 authentication.

The generated JSON looks like

```
            security:
                -
                    SecurityScheme:
                        - HullaRole
```

This does not match the expectation from OpenAPI https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#securityRequirementObject

### Expected behavior

Create correct openapi

### Actual behavior

_No response_

### How to Reproduce?

Use the openapi-swagger-quickstart with the following class

```
@Path("/bla")
public class Main {

    @GET
    @RolesAllowed({"HullaRole"})
    public String getBla() {
        return "Hello OpenAPI";
    }
}

```

Then export the openapi.json and inspect it

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.2 Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #30248: openapi for RestResponse<Stream<T>> not automaticly documenting T
### Describe the bug

The openapi for a resteasy-reactive resource like this is incorrect:
```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public RestResponse<Stream<SomeObject>> hello() {
        return null;
    }
```

It documents the Stream class itself.

### Expected behavior

I would expect the documentation to be generated as a List of SomeObject, i.e. the inner type of Stream.
This is also what the resource returns.

As workaround, I can annotate the method as follows, which produces the expected result:
```
@GET
    @Produces(MediaType.APPLICATION_JSON)
    @APIResponse(name = "200", content = @Content(schema = @Schema(type = SchemaType.ARRAY, implementation = SomeObject.class)))
    public RestResponse<Stream<SomeObject>> hello() {
        return null;
    }
```

Which correctly produces:
image

However, always having to add type and implementation (and not forgetting them / making copy & paste mistakes) becomes a bit cumbersome.

Can Stream<T> please be automaticly detected?

### Actual behavior

image

### How to Reproduce?

Reproducer: 
[restresponse-openapi.zip](https://github.com/quarkusio/quarkus/files/10370532/restresponse-openapi.zip)

1. mvn quarkus:dev
2. Go to http://localhost:8080/q/swagger-ui
3. Look at the responses of the /hello resource - looks correct since the workaround is active
4. Now go to class GreetingResource and remove the APIResponse annotation
5. Go to http://localhost:8080/q/swagger-ui
6. Look at the responses of the /hello resource - looks wrong

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.2364]

### Output of `java -version`

openjdk 17.0.4 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\17 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### LINKED ISSUE #30997: OpenAPI does not correctly generate security schema when @RolesAllowed is used
### Describe the bug

`quarkus-smallrye-openapi` creates incorrect security schema for endpoints, which use `@RolesAllowed` annotation on both class level and method level.
E.g.:
```java
@Path("/roles-allowed-user")
@RolesAllowed("user")
public class RolesAllowedResource {

    @GET
    public void rolesAllowedUser() {
    }

    @GET
    @Path("/roles-allowed-admin")
    @RolesAllowed("admin")
    public void rolesAllowedAdmin() {
    }
}
```
Then the `/q/openapi` produces:
```yaml
---
openapi: 3.0.3
info:
  title: openapi-security-reproducer API
  version: 1.0.0-SNAPSHOT
paths:
  /roles-allowed-user:
    get:
      tags:
      - Roles Allowed Resource
      responses:
        "204":
          description: No Content
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - user
  /roles-allowed-user/roles-allowed-admin:
    get:
      tags:
      - Roles Allowed Resource
      responses:
        "204":
          description: No Content
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - user
components:
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
```
The actual behavior of the `/roles-allowed-user/roles-allowed-admin` endpoint correctly reflects the security specification and requires the `admin` role.
However, the OpenAPI schema shows the `user` role in the endpoint.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

```
git clone git@github.com:jsmrcka/openapi-security-reproducer.git
mvn -f ./openapi-security-reproducer test
```

### Output of `uname -a` or `ver`

Linux ... 6.0.15-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 21 18:33:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

999-SNAPSHOT, 2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MikeEdgar**
- Handle method-level `@RolesAllowed` that override class-level `@RolesAllowed` values, fixes #30997
- Render `BaseStream<T, S>` as array of `T` in OpenAPI document, fixes #30248 (via smallrye-open-api 3.3.0)
- Do not place scopes in OpenAPI security requirements unless the security scheme is OAuth2 or OIDC, fixes #27373
- Include only OIDC discovery URL in OpenAPI when auto-security is active, fixes #21126

### CODE REVIEW

**Comment by MikeEdgar** [comment]
@phillip-kruger , please take a look if you get a chance

**Comment by phillip-kruger** [comment]
@MikeEdgar nice ! let's get this in. I assume you will do the SR release ?

**Comment by MikeEdgar** [comment]
> let's get this in. I assume you will do the SR release ?

Yep, I'll do it now. Thanks for the reviews :smiley:

**Comment by gsmet** [comment]
@MikeEdgar the test failure is definitely related. Could you have a look? Thanks!

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Pull request merged**
