### PR TITLE
Scheduler - support static scheduled methods

### LINKED ISSUE #24234: Scheduler - support static scheduled methods
### Description

Similarly, the CDI spec supports static observer methods.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #24234

### CODE REVIEW

**Comment by mkouba** [comment]
We'll need to update the docs too.

**Review by machi1990 — APPROVED** [review]
lgtm

**Comment by mkouba** [comment]
@Ladicek a MP FT TCK failure - does it ring a bell? Or is it just a test-machine-too-slow issue?
```
2022-03-10T20:13:11.0334498Z [ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.806 s <<< FAILURE! - in org.eclipse.microprofile.fault.tolerance.tck.TimeoutUninterruptableTest
2022-03-10T20:13:11.0335534Z [ERROR] org.eclipse.microprofile.fault.tolerance.tck.TimeoutUninterruptableTest.testTimeoutAsyncBulkhead  Time elapsed: 1.114 s  <<< FAILURE!
2022-03-10T20:13:11.0336260Z java.lang.AssertionError: Unexpected exception thrown from Future
2022-03-10T20:13:11.0336610Z 	at org.testng.Assert.fail(Assert.java:85)
2022-03-10T20:13:11.0337070Z 	at org.eclipse.microprofile.fault.tolerance.tck.util.Exceptions.expect(Exceptions.java:98)
2022-03-10T20:13:11.0337894Z 	at org.eclipse.microprofile.fault.tolerance.tck.TimeoutUninterruptableTest.testTimeoutAsyncBulkhead(TimeoutUninterruptableTest.java:190)
2022-03-10T20:13:11.0338765Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-03-10T20:13:11.0339309Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-03-10T20:13:11.0339935Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-03-10T20:13:11.0340444Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-03-10T20:13:11.0340880Z 	at io.quarkus.arquillian.QuarkusProtocol$QuarkusMethodExecutor$1.invoke(QuarkusProtocol.java:87)
2022-03-10T20:13:11.0341489Z 	at ...
2022-03-10T20:13:11.0398364Z Caused by: org.eclipse.microprofile.faulttolerance.exceptions.BulkheadException: org.eclipse.microprofile.fault.tolerance.tck.timeout.clientserver.UninterruptableTimeoutClient#serviceTimeoutAsyncBulkhead rejected from bulkhead
2022-03-10T20:13:11.0399370Z 	at io.smallrye.faulttolerance.core.bulkhead.BulkheadBase.bulkheadRejected(BulkheadBase.java:17)
2022-03-10T20:13:11.0400058Z 	at io.smallrye.faulttolerance.core.bulkhead.FutureThreadPoolBulkhead.doApply(FutureThreadPoolBulkhead.java:103)
2022-03-10T20:13:11.0400909Z 	at io.smallrye.faulttolerance.core.bulkhead.FutureThreadPoolBulkhead.apply(FutureThreadPoolBulkhead.java:40)
2022-03-10T20:13:11.0401641Z 	at io.smallrye.faulttolerance.core.bulkhead.FutureThreadPoolBulkhead.apply(FutureThreadPoolBulkhead.java:24)
2022-03-10T20:13:11.0402250Z 	at io.smallrye.faulttolerance.core.timeout.Timeout.doApply(Timeout.java:55)
2022-03-10T20:13:11.0402763Z 	at io.smallrye.faulttolerance.core.timeout.Timeout.apply(Timeout.java:30)
2022-03-10T20:13:11.0403311Z 	at io.smallrye.faulttolerance.core.timeout.AsyncTimeout.lambda$doApply$0(AsyncTimeout.java:47)
2022-03-10T20:13:11.0403806Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-03-10T20:13:11.0404334Z 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
2022-03-10T20:13:11.0405459Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
2022-03-10T20:13:11.0405987Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-03-10T20:13:11.0406503Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-03-10T20:13:11.0406987Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2022-03-10T20:13:11.0407513Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2022-03-10T20:13:11.0408092Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-03-10T20:13:11.0408727Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Ladicek** [comment]
@mkouba yes, this is known flaky test: https://github.com/smallrye/smallrye-fault-tolerance/issues/233 It unfortunately happens pretty rarely, and I've never seen that failure outside of Quarkus CI runs, so it's hard to investigate :-/

**Comment by mkouba** [comment]
> @mkouba yes, this is known flaky test: [smallrye/smallrye-fault-tolerance#233](https://github.com/smallrye/smallrye-fault-tolerance/issues/233) It unfortunately happens pretty rarely, and I've never seen that failure outside of Quarkus CI runs, so it's hard to investigate :-/

Ok, thanks for info!

**Comment by mkouba** [comment]
@gastaldi @gsmet is it a known flaky test?
```
 Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 s <<< FAILURE! - in io.quarkus.platform.catalog.RegistrySnapshotCatalogCompatibilityTest
Error:  io.quarkus.platform.catalog.RegistrySnapshotCatalogCompatibilityTest.testRegistrySnapshotPlatformCatalog  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to locate the dev tools config file (.quarkus/config.yaml)
```

**Comment by gastaldi** [comment]
@aloubyansky any changes on this module lately?

**Comment by mkouba** [comment]
I don't think it's related, see also https://github.com/quarkusio/quarkus/pull/24246#issuecomment-1064464238. Merging...

**Comment by aloubyansky** [comment]
> @aloubyansky any changes on this module lately?

Nothing comes to mind so far.

**Pull request merged**
