### PR TITLE
Backport quarkusGenerateCode runtime configuration selection

### PR DESCRIPTION
**Pull request by glefloch**
This backport #24512 on branch `2.7`

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet should we consider merging this one after we backport everything that has the labels? Otherwise, I haven't checked, but it could potentially create conflicts?

**Comment by aloubyansky** [comment]
Sorry, read the comments on the original PR now.

**Comment by gsmet** [comment]
OK, it looks like it's not as obvious as it seems to be. I think we'd better not backport it then. WDYT?

**Comment by glefloch** [comment]
Yes I agree with that. I tried to understand failures but it looks a bit more obvious than I thought. Let's close this.

**Pull request closed without merging**
