### PR TITLE
Exclude osgi.annotation.versioning dependency

### PR DESCRIPTION
**Pull request by RotBolt**
Exclude the org.osgi:osgi.annotation.versioning from dependency graph

### CODE REVIEW

**Comment by KaenDagger** [comment]
CC @michalszynkiewicz

**Review by gsmet — CHANGES_REQUESTED** [review]
If you really don't want that one, could you add it here: https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L211 with a small comment explaning the why?

Thanks!

**Comment by KaenDagger** [comment]
@michalszynkiewicz had discussion to remove this dependency for the productized version. There is no productized version of this available . Also No github repository is there for this dependency. This could excluded from Metrics API

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
