### PR TITLE
Bump jboss-logmanager 1.1.1

### LINKED ISSUE #26401: log4j: java.lang.IllegalStateException: Maximum number of attachments exceeded
### Describe the bug

adding dependency `log4j-jboss-logmanager` to the application leads to the following exception when executing the integration test:

```
2022-06-28 11:00:12,440 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /foo failed, err
or id: 9985f0d2-3c6f-4b03-938f-c76130e6048b-1: java.lang.ExceptionInInitializerError
...
Caused by: java.lang.IllegalStateException: Maximum number of attachments exceeded
        at org.jboss.logmanager.LoggerNode.attachIfAbsent(LoggerNode.java:485)
        at org.jboss.logmanager.Logger.attachIfAbsent(Logger.java:196)
        at org.apache.log4j.JBossLogManagerFacade$2.run(JBossLogManagerFacade.java:102)
        at org.apache.log4j.JBossLogManagerFacade$2.run(JBossLogManagerFacade.java:85)
        at org.apache.log4j.JBossLogManagerFacade.doPrivileged(JBossLogManagerFacade.java:269)
        at org.apache.log4j.JBossLogManagerFacade.getLoggerRepository(JBossLogManagerFacade.java:85)
        at org.apache.log4j.JBossLogManagerFacade.getLoggerRepository(JBossLogManagerFacade.java:73)
        at org.apache.log4j.LogManager.getLoggerRepository(LogManager.java:49)
        at org.apache.log4j.LogManager.getLogger(LogManager.java:57)
        at org.apache.log4j.Logger.getLogger(Logger.java:39)
        at com.lodh.foo.Bar.<clinit>(Bar.java:14)
        ... 33 more
```

Surprisingly it works when I compile the application with `skipTests`, and I execute the `java -jar` command. It only fails when the application is started through the integration tests.

### Expected behavior

log4j logging working.

### Actual behavior

It fails during the tests with an exception.

### How to Reproduce?

Not sure at this point. This is happening on the integration test application that validates an extension with multiple dependencies.
I have tried to go back to `2.9.2`, and this fails also. So it is not a regression in `2.10.0`
Would you be able to suggest some things I could test in my build (beside trying to create a full reproducer)?

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vsevel**
see https://github.com/dmlloyd/jboss-logmanager-embedded/pull/5
Fixes https://github.com/quarkusio/quarkus/issues/26401

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
We cannot upgrade to 1.1 in main. 1.1 is the version targeting the Jakarta packages.

You can upgrade it here so the Jakarta version is updated: https://github.com/quarkusio/quarkus/blob/main/jakarta/rewrite.yml#L340-L342 .

And we would need a new 1.0 if you want this fix in main.

**Comment by vsevel** [comment]
> You can upgrade it here so the Jakarta version is updated:

we do not have to do both at the same time, right?
if I do the backport, when do you think you will be able to do a release @dmlloyd ?

**Review by gsmet — APPROVED** [review]
No we can merge that one already.

As long as it doesn't require any code changes on the Quarkus side, which seems to be the case.

**Comment by vsevel** [comment]
FYI here is the backport on 1.0.x: https://github.com/dmlloyd/jboss-logmanager-embedded/pull/6

**Pull request merged**
