### PR TITLE
Enable formatter & impsort for quickly, cache outside of target

### PR DESCRIPTION
**Pull request by famod**
As discussed here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Towards.20the.202.2Ex.20branch/near/231617232

### CODE REVIEW

**Comment by famod** [comment]
@gsmet @aloubyansky any objections? Can we get this in?

**Comment by aloubyansky** [comment]
I haven't yet tried it. Could you post the result of `ls .cache`? Just curious how it looks like and whether we could reuse it to cache other stuff in perspective?

**Comment by famod** [comment]
```
ls -la core/runtime/.cache/
total 56
drwxr-xr-x 2 fmo fmo  4096 Mar 26 10:55 .
drwxr-xr-x 5 fmo fmo  4096 Mar 26 10:55 ..
-rw-r--r-- 1 fmo fmo 28663 Mar 24 15:58 formatter-maven-cache.properties
-rw-r--r-- 1 fmo fmo 19696 Mar 24 15:58 impsort-maven-cache.properties
```
```
cat core/runtime/.cache/formatter-maven-cache.properties
#Wed Mar 24 15:58:53 CET 2021
/src/test/java/io/quarkus/runtime/configuration/DotEnvTestCase.java=c96f9fbcdace6b17b91df3085c2f8e0aaf2c15400a06a027f2760783b8a4b08ed45588619cdc97fcaac5a3adaf081cca42b97256e93e6146ebfecf6eeddb46d8
/src/main/java/io/quarkus/runtime/configuration/FastCachedConfigSource.java=707cb12e28c04a8d61e2677f656566899ec3e19212cd9d3eb5f1b28f0c52b230e889de00671a57f32c8a70b3768dbf07abca0e538885be702ba4ace7c6b7a23c
[...]
```
```
cat core/runtime/.cache/impsort-maven-cache.properties
#Wed Mar 24 15:58:53 CET 2021
/home/fmo/proj/quarkus/core/runtime/src/main/java/io/quarkus/runtime/graal/MappedByteBufferReplacement.java=ab803f20698a1fc313e1eefe4c499c92
/home/fmo/proj/quarkus/core/runtime/src/main/java/io/quarkus/runtime/logging/CategoryConfig.java=3024caccbc913d8e883dd019a5f9c7e6
[...]
```

**Comment by aloubyansky** [comment]
So it looks re-usable.
I guess +1. I'd like to have a simple command for the first build after cloning. But I guess it's a good enough compromise for a working branch.

**Review by aloubyansky — APPROVED** [review]

**Comment by famod** [comment]
> I'd like to have a simple command for the first build after cloning.

You mean without any formatting (like quickly is today)? Something shorter than `mvn -Dquickly -T...`?

**Comment by aloubyansky** [comment]
`mvn -Dquickly` is simple enough.

**Comment by famod** [comment]
I'll merge this since (on Zulip) everyone seemed to be annoyed by the current behavior and nobody raised any concerns.

**Pull request merged**
