### PR TITLE
Polish datasource config structure to get better generated documentation

### PR DESCRIPTION
**Pull request by yrodiere**
In particular, this gets rid of unnecessary headings such as "Datasources" (that's important when you know that section nesting is not really handled):

Screenshot from 2024-02-12 13-24-13

And it makes sure that merging of config properties for the default/named datasources (see above) is handled consistently, which is not always the case right now:

Screenshot from 2024-02-12 13-24-18

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
I'm not sure I fully understand what the problem is because these sections were supposed to make things better but it's your stuff so I will let you decide what you prefer :).

**Comment by yrodiere** [comment]
> I'm not sure I fully understand

It's just that a section titled "datasources" in configuration properties about... datasources... doesn't really help.

Regarding "additional named datasources", we won't need it after the changes because the config properties or named datasources will be next to the ones for the default datasource, like so:

image

> it's your stuff

Most definitely not :D

**Comment by yrodiere** [comment]
@gsmet adding the backport label to get this into 3.7 or 3.8 because @MichalMaler thinks it's useful

**Comment by MichalMaler** [comment]
@yrodiere @gsmet Yeah, for sure, those are the little tweaks that increase the level of user experience , and also makes QE happy :)
Thank you!

**Comment by gsmet** [comment]
Sorry but this doesn't only change the doc, it actually changes the structure of the config so I'm not comfortable backporting it this late in the 3.7/3.8 cycle.

**Comment by MichalMaler** [comment]
OK, sure thing.

**Pull request merged**
