### PR TITLE
Add configuration for WebSocket MaxFrameSize and MaxMessageSize

### LINKED ISSUE #43381: Max frame length of 65536 has been exceeded - Quarkus 3
### Describe the bug

WebSocket Server ignores Max Frame Size after upgrade from Quarkus 1.x to 3.14.4.
In application.properties I set:

`quarkus.websocket.max-frame-size=2097152`

and get the exception:
```

2024-09-18 18:45:18,450 INFO  [com.vim.ngv.wss.TunnelWSS] (executor-thread-3) WebSocket tunnel error, session: lUIS0BLIvL7sX4SNrHaQrjlQCd3ld1B5W_yJT2FQ, error: Max frame length of 65536 has been exceeded..: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:427)
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:288)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
...
```

### Expected behavior

No exception, or a message with my max frame size setting in "Max frame length of 65536 has been exceeded".

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux localhost.localdomain 6.4.4-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 19 17:06:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

I think this method miss to take the quarkus.websocket.* configuration...

https://github.com/quarkusio/quarkus/blob/1c8464b3ff87a75857bc1a8a9f0e8a72db584d58/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L1009-L1025

### PR DESCRIPTION
**Pull request by dometec**
- Fixes: #43381

### CODE REVIEW

**Review by cescoffier — COMMENTED** [review]
It makes sense to add these there, but we need to think how we can advertize them from web-socket-next.

@mkouba WDYT? 

(why it makes sense: because someone can use websockets directly from a router or reactive routes, it does not need to use Undertow websocket or websocket next).

**Comment by mkouba** [comment]
> It makes sense to add these there, but we need to think how we can advertize them from web-socket-next.

We could just a section/note in the reference guide.

> 
> (why it makes sense: because someone can use websockets directly from a router or reactive routes, it does not need to use Undertow websocket or websocket next).

Well, it's possible but IMO not very common.

**Comment by cescoffier** [comment]
> Well, it's possible but IMO not very common.

The Dev UI uses a web socket. So, these configurations will affect it. It's not common, but we do use that approach.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Pull request merged**
