### PR TITLE
Update builder images to jdk-21

### PR DESCRIPTION
**Pull request by zakkak**
- Update the GraalVM Community builder image to the tag `jdk-21`
- Update the Mandrel builder image to the tag `jdk-21`(Mandrel 23.1)
- Update GraalVM SDK version to 23.1 (yes, it does not follow the same version scheme)

Draft till the Mandrel images get [pushed to quay.io](https://github.com/quarkusio/quarkus-images/actions/runs/6498335260).

### CODE REVIEW

**Comment by Sanne** [comment]
hi @zakkak, there are some conflicts

**Review by Sanne — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@zakkak I rebased and added a few commits.

**Comment by gsmet** [comment]
FWIW, the VT thread CI is now failing in native as we use a builder that has apparently been dropped so we really need it now.

**Comment by zakkak** [comment]
CI failures are irrelevant.

@gsmet I suggest we get this backported to 3.5.

Please note that the update to Mandrel 23.1 / GraalVM for JDK 21) results in warnings like the following:

```
Warning: The option '-H:IncludeResourceBundles=yasson-messages' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ReflectionConfigurationFiles=reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
```

which should be fixed in the corresponding projects, e.g., as in https://github.com/netty/netty/pull/13596 and https://github.com/micrometer-metrics/micrometer/pull/4246

**Comment by zakkak** [comment]
> Warning: The option '-H:ReflectionConfigurationFiles=reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.

The `Warning: The option '-H:ReflectionConfigurationFiles=reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.` part is `integration-tests/main` specific and related to https://github.com/quarkusio/quarkus/pull/36491

**Comment by gsmet** [comment]
Yeah I think it makes sense. The warnings are unfortunate though, thanks for creating PRs in the upstream projects.

**Comment by jerboaa** [comment]
> Please note that the update to Mandrel 23.1 / GraalVM for JDK 21) results in warnings like the following:
> 
> ```
> Warning: The option '-H:IncludeResourceBundles=yasson-messages' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> Warning: The option '-H:ReflectionConfigurationFiles=reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
> ```
> 
> which should be fixed in the corresponding projects, e.g., as in [netty/netty#13596](https://github.com/netty/netty/pull/13596) and [micrometer-metrics/micrometer#4246](https://github.com/micrometer-metrics/micrometer/pull/4246)

@zakkak Couldn't we work-around those warnings by using `--exclude-config`?

```
Non-standard options help:

    --exclude-config      exclude configuration for a comma-separated pair of classpath/modulepath
                          pattern and resource pattern. For example:
                          '--exclude-config foo.jar,META-INF\/native-image\/.*.properties'
                          ignores all .properties files in 'META-INF/native-image' in all
                          JARs named 'foo.jar'.
```

**Pull request merged**
