### PR TITLE
Clean up IsolatedDevModeMain when closing a bit more

### PR DESCRIPTION
**Pull request by gsmet**
Also avoid keeping a reference to the IsolatedDevModeMain instance in the AugmentAction.

### CODE REVIEW

**Comment by gsmet** [comment]
It should be good to go now, CI was greenish in my fork.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@brunobat not sure if this error is fatal or not but it looks like the container was not accessible after it.

It might be due to my changes but I don't see how they could affect this specifically.

```
2024-07-02T13:28:07.6252501Z 2024-07-02 13:28:07,564 INFO  [tc.ghc.io/open-telemetry/opentelemetry-java/otel-collector:latest] (pool-17-thread-1) Pulling docker image: ghcr.io/open-telemetry/opentelemetry-java/otel-collector:latest. Please be patient; this may take some time but only needs to be done once.
2024-07-02T13:28:07.7253692Z 2024-07-02 13:28:07,672 INFO  [tc.ghc.io/open-telemetry/opentelemetry-java/otel-collector:latest] (docker-java-stream-1517473528) Starting to pull image
2024-07-02T13:28:07.7256051Z 2024-07-02 13:28:07,681 INFO  [tc.ghc.io/open-telemetry/opentelemetry-java/otel-collector:latest] (docker-java-stream-1517473528) Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2024-07-02T13:28:07.7258655Z 2024-07-02 13:28:07,682 INFO  [tc.ghc.io/open-telemetry/opentelemetry-java/otel-collector:latest] (pool-17-thread-1) Image ghcr.io/open-telemetry/opentelemetry-java/otel-collector:latest pull took PT0.117570792S
2024-07-02T13:28:07.7261206Z 2024-07-02 13:28:07,684 INFO  [tc.ghc.io/open-telemetry/opentelemetry-java/otel-collector:latest] (pool-17-thread-1) Creating container for image: ghcr.io/open-telemetry/opentelemetry-java/otel-collector:latest
2024-07-02T13:28:07.8254659Z 2024-07-02 13:28:07,729 INFO  [tc.ghc.io/open-telemetry/opentelemetry-java/otel-collector:latest] (pool-17-thread-1) Container ghcr.io/open-telemetry/opentelemetry-java/otel-collector:latest is starting: f214ba3ea49c002f17b74b67ecf6d6c5f98dbd6c6ee756003e5024207834301c
2024-07-02T13:28:08.0256127Z 2024-07-02 13:28:07,990 INFO  [org.tes.con.wai.str.HttpWaitStrategy] (pool-17-thread-1) /crazy_satoshi: Waiting for 60 seconds for URL: http://localhost:33081/ (where port 33081 maps to container port 13133)
2024-07-02T13:28:08.1258301Z 2024-07-02 13:28:08,040 INFO  [otel-collector] (docker-java-stream--1127862324) STDERR: Error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: variable substitution using $VAR has been deprecated in favor of ${VAR} and ${env:VAR} - please update $LOGGING_EXPORTER_VERBOSITY_LEVEL or temporarily disable the confmap.unifyEnvVarExpansion feature gate
2024-07-02T13:28:08.1263867Z 2024-07-02 13:28:08,041 INFO  [otel-collector] (docker-java-stream--1127862324) STDERR: 2024/07/02 13:28:08 collector server run finished with error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: variable substitution using $VAR has been deprecated in favor of ${VAR} and ${env:VAR} - please update $LOGGING_EXPORTER_VERBOSITY_LEVEL or temporarily disable the confmap.unifyEnvVarExpansion feature gate
2024-07-02T13:29:08.0323783Z 2024-07-02 13:29:07,993 ERROR [tc.ghc.io/open-telemetry/opentelemetry-java/otel-collector:latest] (pool-17-thread-1) Could not start container: java.lang.IllegalStateException: Wait strategy failed. Container exited with code 1
```

**Comment by brunobat** [comment]
It is a breaking change picked up by the latest image from OpenTelemetry Collector.
I locked it to the previous version in the Open Telemetry Metrics PR... Do you want me to create a dedicated PR?

**Comment by brunobat** [comment]
here: https://github.com/quarkusio/quarkus/pull/41637

**Pull request merged**
