### PR TITLE
Activate request context for GraphQL API methods

### LINKED ISSUE #9786: @GraphQLApi without @ActivateRequestContext gives a ContextNotActiveException
As discussed [here](https://groups.google.com/forum/#!topic/quarkus-dev/AGem0DpyE8A) the Quarkus GraphQL integration with `@GraphQLApi` itself gives a `ContextNotActiveException` when using Panache.

```
@GraphQLApi
public class MyGraphQLApi {

    private final ContinentTypeMapper continentTypeMapper;

    public MyGraphQLApi(ContinentTypeMapper continentTypeMapper) {
        this.continentTypeMapper = continentTypeMapper;
    }

    @Query("continents")
    @Description("Get a list of continents")
    public List<ContinentType> getContinents() {
        return continentTypeMapper.toContinentTypes(Continent.findAll(Continent.DEFAULT_SORT).list());
    }
}
```

leads to:

```
Data Fetching Error: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.arc$delegate(RequestScopedEntityManagerHolder_ClientProxy.zig:68)
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(RequestScopedEntityManagerHolder_ClientProxy.zig:220)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:77)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:316)
        at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:142)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:360)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:315)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:266)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:149)

```

When changing it to:

```
@GraphQLApi
@ApplicationScoped
@ActivateRequestContext
public class MyGraphQLApi {

    ..
}
```

it works.

It would be nice if the `@ActivateRequestContext` is activated automatically.

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #9786

### CODE REVIEW

**Comment by jmartisk** [comment]
There seems to be an improperly formatted `core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java`, failing the build, so I added a commit that fixes that. If this is not the way we will get this fix in, I'll remove that commit

**Comment by geoand** [comment]
Saw that too... However I can't push to master...

**Comment by jmartisk** [comment]
Perhaps I could submit a separate PR that fixes that and have it merged quickly so not many people are affected?

**Comment by geoand** [comment]
Thanks a lot of taking care of the import issue @jmartisk

**Review by geoand — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
@mkouba mind taking a quick look as well?

**Comment by mkouba** [comment]
So I think that we should rather activate/deactivate the request context in the `SmallRyeGraphQLExecutionHandler`, i.e. something like:
```java
ManagedContext requestContext = Arc.container().requestContext();
if (requestContext.isActive()) {
   // handle the request
} else {
   try {
      requestContext.activate();
        // handle the request
    } finally {
      requestContext.terminate();
    }
}
```
The current approach leverages interceptors which is a much more heavyweight solution compared to the snippet above. WDYT?

**Comment by jmartisk** [comment]
@mkouba That's a good idea. Done.

**Review by mkouba — APPROVED** [review]

**Comment by gsmet** [comment]
I marked it for backport as it looks like a useful fix.

**Pull request merged**
