### PR TITLE
Error when conflicting Deployment due to label selector version

### LINKED ISSUE #39180: Deployment of new version of application with OpenShift extension fails with `LabelSelectorRequirement(nil)}: field is immutable`
### Describe the bug

Hey @**Ioannis Canellos|226065** , I noticed something odd lately when deploying with the OpenShift extension... Opening as a bug since I'm not quite sure, but feel free to requalify.

It seems that the deployment fails because a selector includes the app version (the git SHA in this case), and selectors are immutable:

```
Error: [ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: ***/apis/apps/v1/namespaces/prod-quarkus-github-lottery/deployments/quarkus-github-lottery. Message: Deployment.apps "quarkus-github-lottery" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"quarkus-github-lottery", "app.kubernetes.io/version":"7df7e9a331fb67fdfe434ec56b49a3f52a944674"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.selector, message=Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"quarkus-github-lottery", "app.kubernetes.io/version":"7df7e9a331fb67fdfe434ec56b49a3f52a944674"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=quarkus-github-lottery, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "quarkus-github-lottery" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"quarkus-github-lottery", "app.kubernetes.io/version":"7df7e9a331fb67fdfe434ec56b49a3f52a944674"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

I don't think I personally changed anything in this area in my app, so... could it be related to the switch from DeploymentConfig to Deployment?

More importantly, should this be addressed/documented in the extension, since it's apparently the default behavior?

See https://github.com/quarkusio/quarkus-github-lottery/actions/runs/8142539385/job/22252314385

### Expected behavior

Deployment should erase the previous version of the application -- at least it used to.

### Actual behavior

Deployment fails:

```
Error: [ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: ***/apis/apps/v1/namespaces/prod-quarkus-github-lottery/deployments/quarkus-github-lottery. Message: Deployment.apps "quarkus-github-lottery" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"quarkus-github-lottery", "app.kubernetes.io/version":"7df7e9a331fb67fdfe434ec56b49a3f52a944674"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.selector, message=Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"quarkus-github-lottery", "app.kubernetes.io/version":"7df7e9a331fb67fdfe434ec56b49a3f52a944674"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=quarkus-github-lottery, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "quarkus-github-lottery" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"quarkus-github-lottery", "app.kubernetes.io/version":"7df7e9a331fb67fdfe434ec56b49a3f52a944674"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

### How to Reproduce?

Deploy a new version of an application without removing the previous version one.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #39180

What the pull request does is that it checks if an existing Deployment is already installed with conflicting Deployment version and provides detailed error message with instructions on how the situation should be handled.

Also, it does the checking before applied resources (e.g. Service etc) that could leave the application in a non-working state.

### CODE REVIEW

**Comment by iocanel** [comment]
@manusa: Do you have any insights on this?

**Comment by geoand** [comment]
This seems kinda risky, no?

**Comment by manusa** [comment]
> @manusa: Do you have any insights on this?

I do have a recent experience about a complaint from a JKube user regarding something related.

https://github.com/eclipse/jkube/issues/2697

Starting from v1.16, we switched to use standard/recommended Kubernetes labels as opposed to those that JKube (formerly Fabric8 Maven Plugin) prescribed.

When the user upgraded to the newer JKube version with the changes, their pipelines failed due to the existent Deployment selector containing different values.

We did recommend the `recreate` approach (where the previous Deployment is deleted and then reapplied), but this was not possible for them. See https://github.com/eclipse/jkube/issues/2697#issuecomment-1952562420

**Comment by maxandersen** [comment]
@iocanel if having version in label makes impossible to update deployments shouldn't this not be avoided?

**Comment by iocanel** [comment]
> @iocanel if having version in label makes impossible to update deployments shouldn't this not be avoided?

Adding the version to the selector has it's pros and cons. If we just remove it then users will only be able to correlate pods by name, which can be problematic as users won't be able to route traffic between version etc. Things like canary, a/b testing it will become trickier. 

So, we need give users the option to decide how they'll roll. 
Currently, it's enabled by default. We could possibly change that but that means that it will then bite everyone once.

**Comment by iocanel** [comment]
Something additional that worth mentioning ... This behavior (having the version being part of the label) is inherited by dekorate since 2019. Meaning that its not something that we just recently change. The main reason why this is has been just discovered is the transition from `DeploymentConfig` to  `Deployment` which is the resource affected by it.

I suggest we move forward with this pull request. And move to an optional opt-in strategy for the next major release.

**Comment by maxandersen** [comment]
@gsmet @yrodiere wdyt ? seems like good first step to inform users what to do early.

I suggest we in anohter PR make `add-version-to-label-selectors` be false by default. That will still cause exception on existing deployments that has label but with this PR its now informative/helpful, and any future quarkus versions wil allow rolling deployments by default.

**Review by yrodiere — APPROVED** [review]
> @gsmet @yrodiere wdyt ? seems like good first step to inform users what to do early.

Agreed. If it's going to fail, better fail early with an actionable message.

> I suggest we in anohter PR make `add-version-to-label-selectors` be false by default. That will still cause exception on existing deployments that has label but with this PR its now informative/helpful, and any future quarkus versions wil allow rolling deployments by default.

Great minds think alike: https://github.com/quarkusio/quarkus/issues/39180#issuecomment-1980747368

**Pull request merged**
