### PR TITLE
Add an extension for Camel-AWS SNS

### LINKED ISSUE #2681: Add an extension for Camel-AWS SNS
**Description**
Supporting camel-aws-sns

### PR DESCRIPTION
**Pull request by oscerd**
Add support for Camel SNS - Fixes #2681

### CODE REVIEW

**Comment by oscerd** [comment]
@gnodet @lburgazzoli @gsmet

**Comment by gsmet** [comment]
@oscerd @lburgazzoli @gnodet @ppalaga 

So general comment on the Camel extensions: we have 3 of them pending. I would really appreciate if you guys could cross-review them and check they are properly working and in line with what you want for Camel.

Once it's done, ping me and I can review the code itself at a Quarkus level.

Thanks!

**Comment by oscerd** [comment]
I think the first step to test again the extension is having this one merged: https://github.com/quarkusio/quarkus/pull/2562

**Comment by gsmet** [comment]
@oscerd it was on my list for this morning, done :).

**Comment by oscerd** [comment]
Ok, thank you, I'll check the pending PRs for extensions.

**Comment by oscerd** [comment]
@gsmet I can confirm this works fine with the fix from #2562

**Review by lburgazzoli — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@gsmet can you grant me the possibility to set labels ?

**Comment by cescoffier** [comment]
Now that https://github.com/quarkusio/quarkus/pull/2562, can someone recheck this PR? 
@lburgazzoli @oscerd ?

**Comment by oscerd** [comment]
@cescoffier I already verified this extension with #2562 merged and it works fine.

**Comment by oscerd** [comment]
so it can be merged, as camel-servlet extension too, I tested it too.

**Comment by lburgazzoli** [comment]
@cescoffier allt eh camel related extension have been checked, I think we can safely merge them

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
