### PR TITLE
ArC: improve validation of interceptor method signatures

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
I think we might wanna backport this to 3.7/3.8, WDYT @mkouba?

**Review by mkouba — APPROVED** [review]

**Review by manovotn — APPROVED** [review]
Looks good but shouldn't we also add a test for `@AroundInvoke` having `void` return type?

**Comment by Ladicek** [comment]
Ah I intended to do that, but forgot! Thanks, will add.

**Comment by Ladicek** [comment]
Done. Thanks for reminding me!

**Review by manovotn — APPROVED** [review]

**Comment by gsmet** [comment]
I'm not sure about backporting this one? My understanding is that apps that were somehow building without errors will fail, right? Granted, they wouldn't work well but still.
I think we are a bit late in this cycle to do that.

Unless I misunderstood something?
(I could be convinced if you have a case)

**Comment by Ladicek** [comment]
Not a huge deal if we don't backport this, we already had a mostly good (say 95%) validation in place, this just tightens it up (to 100%).

**Comment by mkouba** [comment]
@gsmet I agree with Ladislav. So let's not backport this one.

**Pull request merged**
