### PR TITLE
Exposing the reactive MongoDatabase

### PR DESCRIPTION
**Pull request by dloiacono**
Exposing the reactive MongoDatabase provides the ability to use MongoDB features not yet wrapped in quarkus like the GridFS feature.

Added the unwrap method.

### CODE REVIEW

**Comment by gsmet** [comment]
There is a formatting issue, please run `mvn process-sources` and amend your commit.

**Comment by dloiacono** [comment]
> There is a formatting issue, please run `mvn process-sources` and amend your commit.

I got this problem:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce) on project quarkus-test-extension-deployment: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve following dependencies: [io.quarkus:quarkus-test-extension:jar:999-SNAPSHOT (compile)]: Could not resolve dependencies for project io.quarkus:quarkus-test-extension-deployment:jar:999-SNAPSHOT: Could not find artifact io.quarkus:quarkus-test-extension:jar:999-SNAPSHOT in oss.sonatype.org (https://oss.sonatype.org/content/repositories/snapshots/)

**Comment by geoand** [comment]
Thanks for this! One thing we will need for certain is to merge the 2 commits

**Review by loicmathieu — APPROVED** [review]
LGTM

**Comment by dloiacono** [comment]
@cescoffier please, waiting for one more review :-)

**Review by cescoffier — APPROVED** [review]
It looks good to me, however be aware that the "reactive streams" compatibility is sometimes a bit weird (like sending `null` as item). Hopefully, you won't see that.

**Pull request merged**
