### PR TITLE
Upgrade SmallRye Config to 1.5.1

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes issue described in smallrye/smallrye-config#211

### CODE REVIEW

**Comment by dmlloyd** [comment]
Also should serve to verify whether the relocations will work as expected with respect to version upgrades.

**Comment by gsmet** [comment]
@dmlloyd is it something I should backport?

**Comment by dmlloyd** [comment]
Yes, if the relocation stuff works (we'll soon see).

**Comment by dmlloyd** [comment]
Relocation seems to work, but there is a different problem in the form of kiegroup/kogito-runtimes#256.  We'll see what they say.

**Comment by gastaldi** [comment]
Perhaps you could also add it to https://github.com/quarkusio/quarkus/blob/master/.dependabot/config.yml? Less work :)

**Comment by dmlloyd** [comment]
You mean, less work once every single upgrade doesn't blow everything up :)

**Comment by geoand** [comment]
I restarted the failed test since I'm not sure if it's related

**Comment by mswiderski** [comment]
@gsmet @dmlloyd kogito 0.6.1 is released and available in maven central. It should address the problems found when upgrading smallrye config. Maybe it would be good to test this change with upgrade of kogito in single PR to make sure it all works well, wdyt?

**Comment by gsmet** [comment]
Yes, I'm working on it. Running the tests then will push.

**Review by gsmet — APPROVED** [review]
CI is green now. Thanks to both of you.

**Comment by gsmet** [comment]
I had to revert the inclusion of this one into 1.1 for now due to this issue: https://github.com/quarkusio/quarkus/issues/6176.

**Pull request merged**
