### PR TITLE
Hibernate ORM - make synthetic beans ApplicationScoped

### PR DESCRIPTION
**Pull request by mkouba**
- to workaround a problem with debezium extension

### CODE REVIEW

**Comment by gsmet** [comment]
No need to backport, this work is only in master!

**Comment by mkouba** [comment]
> No need to backport, this work is only in master!

Ok, sorry. Didn't realize it.

> to be sure we don't expect significant performance regressions here.

I wouldn't expect a noticable drop unless we do invoke a method of the `EntityManager` bean "million" times per request...

**Comment by Sanne** [comment]
Could we know more about the reason?  You mention a _workaround_, shouldn't we rather look into a proper fix?

**Comment by mkouba** [comment]
@Sanne the proper fix needs to be implemented in DBZ: https://issues.redhat.com/browse/DBZ-2465

Anyway, there is a comment in the code that attempts to explain what's going on. 

It's also discussed on zulip: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Synthetic.20beans

**Comment by Sanne** [comment]
Why would you prefer regressing Quarkus core to address a bug in an external extension?

**Comment by mkouba** [comment]
> Why would you prefer regressing Quarkus core to address a bug in an external extension?

That's a question for @gsmet ...

**Comment by gsmet** [comment]
1. I wasn't sure it would be that much of a regression and it would only be temporary until we upgrade DBZ. Thus why I asked you and John.
2. I have no idea what the DBZ lifecycle is and if they plan to release a micro version.

For sure, the best way to fix this if making the bean `@ApplicationScoped` is a problem would be to fix things in DBZ and release a new micro.

/cc @gunnarmorling

**Comment by gunnarmorling** [comment]
> I have no idea what the DBZ lifecycle is and if they plan to release a micro version.

We're on a three weekly release cadence for preview releases, with Final releases at the end of the quarter. This fix would go into our upcoming 1.3.0.Beta2 release (next week), 1.3 Final should be out by end of September.

**Comment by gsmet** [comment]
I was more asking for a 1.2.3.Final containing the Quarkus upgrade and the config injection?

I would still need to check if it properly fixes the issue though.

**Comment by gunnarmorling** [comment]
> I was more asking for a 1.2.3.Final containing the Quarkus upgrade and the config injection?

I got to admit I'm not super-excited about this prospect. Couldn't you upgrade to DBZ 1.3.0.Beta2 instead?

**Comment by gsmet** [comment]
Not really without it becoming an issue with Camel IMHO.

**Comment by gsmet** [comment]
If making the EM `@ApplicationScoped` has a significant cost, it's basically either we can get a 1.2.3.Final or we disable DBZ IT in the platform and the DBZ outbox extension won't work for 1.8.

I will check if what you did fixed the issue.

**Comment by gsmet** [comment]
I created a PR here backporting both changes: https://github.com/debezium/debezium/pull/1772 .

I confirm it fixes the issue we have.

**Comment by gsmet** [comment]
Given @Sanne confirmed it would cause a performance regression, I went the Debezium route. PR created there with the backport and they will release a new micro in time for our 1.8 Platform release.

Closing this one. Thanks @mkouba for diagnosing the issue!

**Comment by mkouba** [comment]
> Given @Sanne confirmed it would cause a performance regression, I went the Debezium route.

Do we have some numbers? I'm just curious...

**Comment by Sanne** [comment]
@mkouba sorry I don't have the exact references anymore; surely it wasn't orders of magnitude, but yes there's a difference when specifically benchmarking ORM.

I remember seeing overhead in the resolution via flamegraphs, having discussed it with you, you suggested to switch types and that resolved the complex invocation. I'd prefer to keep it this way.

**Comment by mkouba** [comment]
@Sanne no problem, I was just curious...

**Comment by gunnarmorling** [comment]
To close the loop, we're planning to release Debezium 1.2.3.Final early next week which will include the required fix in Debezium itself.

**Pull request closed without merging**
