### PR TITLE
Store since JavaDoc tag in the configuration metadata, so that Quarkiverse projects can render it in their documentation if they like

### PR DESCRIPTION
**Pull request by ppalaga**
https://github.com/quarkiverse/antora-ui-quarkiverse/issues/64

### CODE REVIEW

**Comment by michalvavrik** [comment]
Part that I don't understand about this is that config properties are versioned and documentation is branched. So if user needs to know whether his Quarkus version supports the config property, he just needs to documentation for his Quarkus version. Also such hardcoded statement "supported since" doesn't take into consideration backports.

**Comment by michalvavrik** [comment]
Alright @ppalaga , makes sense.

> New config options are new features, that should typically not be backported. 

Agreed, but I just know it happens from time to time, this is the latest I remember: https://github.com/quarkusio/quarkus/pull/37269

> If it happens for some reason, the since tag could perhaps have a different value in the LTS branch where the new option is backported.

ok

**Comment by ppalaga** [comment]
In case there is enough agreement that we want to have the since tag rendered, I'd still be thankful for any comments from our UI experts about how to present the tag in the docs. I am not especially keen on the current working version that looks like the following 
image

**Comment by michalvavrik** [comment]
> In case there is enough agreement that we want to have the since tag rendered, I'd still be thankful for any comments from our UI experts about how to present the tag in the docs

I think @machi1990 and @gsmet are ones who wrote docs generation, maybe they can help you.

**Comment by maxandersen** [comment]
Nice improvement Peter - I think this is good info to get in.

**Comment by maxandersen** [comment]
@holly-cummins this is another example of core vs platform vs individual extensions - the "since" part all depends on your perception.

I would probably put it below the key - or even below description now thinking that version can be misleading - maybe the generation and include GAV info ?

**Comment by ppalaga** [comment]
> I would probably put it below the key - or even below description now thinking that version can be misleading 

I'd be fine with both, slightly prefering below the key. 

Note that we might want to show also `@deprecated` around there.

> - maybe the generation 

You mean just major.minor instead of major.minor.micro? I'd be for full, bc. we already had options introduced in micros to fix issues. 

> and include GAV info ?

You mean like `Since Quarkus CXF 1.2.3`?

**Comment by ppalaga** [comment]
I changed the scope from "Render in the docs" to "Store in the configuration metadata, so that
Quarkiverse projects can render it in their documentation if they like". 
There will be no observable effect on Quarkus docs and I get some freedom to experiment in Quarkus CXF.

It would be nice if this could be backported to 3.8

**Review by gsmet — APPROVED** [review]
Tested locally and it seems to not disturb our doc so let's merge.

**Comment by ppalaga** [comment]
Perfect, thanks @gsmet !

**Pull request merged**
