### PR TITLE
Fix JandexUtil#getBoxedTypeName() and move it to Qute extension

### PR DESCRIPTION
**Pull request by gsmet**
Type.toString() shouldn't be used to get the type name.

Related to https://github.com/quarkusio/quarkus/discussions/28406 .

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Review by FroMage — APPROVED** [review]

**Comment by mkouba** [comment]
I did a quick search and it seems that `io.quarkus.deployment.util.JandexUtil.getBoxedTypeName(Type)` is only used in the `QuteProcessor`. resteasy-reactive has its own [copy of `JandexUtil`](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java) (!).

So I'd recommend to deprecate the original `JandexUtil.getBoxedTypeName()` method and mark it for removal, move the logic to the `QuteProcessor` and use a more meaningful name such as `getCheckedTemplateParameterTypeName()`. BTW I don't think that we need the boxed value for primitives anymore because we do support template param declaration like `{@int myInt}`.

**Comment by Ladicek** [comment]
`Type.toString()` is just a human readable representation. We can add a human readable representation without annotations for sure. But clearly `JandexUtil.getBoxedTypeName()` is not meant to return a human-readable representation of the type, so it shouldn't use `Type.toString()`. What is it supposed to return, I don't really know, but if it's only used in Qute, I agree with @mkouba that Qute should have its own copy and this method should be deprecated for removal.

Now, `Type.name()` is not exactly consistently defined. For primitives (and `void`), it returns the corresponding Java keyword, otherwise it returns what `Class.getName()` would return (for parameterized types, it's the class of the raw type, and for wildcards and type variables, it's the class of the [first] upper bound). This is why it returns that weird string for arrays...

**Comment by FroMage** [comment]
> resteasy-reactive has its own copy of JandexUtil (!).

Well, it's supposed to be independent and move to its own repo at some point, so it can't depend on quarkus-core.

> So I'd recommend to deprecate the original JandexUtil.getBoxedTypeName() method and mark it for removal, move the logic to the QuteProcessor and use a more meaningful name such as getCheckedTemplateParameterTypeName()

Why deprecate it and move it? Are you sure it will never be useful to others?

**Comment by mkouba** [comment]
> Why deprecate it and move it? Are you sure it will never be useful to others?

Well, it's not used by any core extension and it's IMO not very clear what should be the return value.

**Comment by mkouba** [comment]
> @mkouba see what I just pushed.

Looks good but I'd rather mark the method as deprecated first becuse it could be used by an extension from quarkiverse and others...

**Comment by gsmet** [comment]
@mkouba done!

**Review by mkouba — APPROVED** [review]

**Pull request merged**
