### PR TITLE
Handle primitives in DefaultIgnorePredicate

### LINKED ISSUE #9753: Building GraphQL quickstart generates warnings that should be avoided
We shouldn't have these warnings when building a GraphQL application:

```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- java.lang.Boolean
	- java.lang.Double
	- java.lang.Enum
	- java.lang.Integer
	- java.lang.Object
	- java.lang.String
	- java.time.LocalDate
	- java.util.List
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #9753
Closes #10017

### CODE REVIEW

**Comment by gastaldi** [comment]
@cemnura can you have a look?

**Review by gsmet — APPROVED** [review]
Yes, that would have my preference if it fixes the initial issue properly.

**Review by phillip-kruger — APPROVED** [review]
Even better ! Thanks!

**Review by geoand — APPROVED** [review]

**Comment by cemnura** [comment]
> @cemnura can you have a look?

@gastaldi 
I agree, a general solution would be much more beneficial. Primitives should be registered to jandex anyway?

**Pull request merged**
