### PR TITLE
[fixes #5926] - Attempt to make code flow test more stable

### LINKED ISSUE #5926: OIDC integration-tests/oidc-code-flow is unstable
**Description**
It has failed recently with a `Too much redirect ...` error but it appears to be failing randomly. 
It is really an html unit level issue. 

**Implementation ideas**
Perhaps a newer version can be used or some alternative html-friendly test framework can be plugged in

CC Pedro @pedroigor

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Comment by gsmet** [comment]
Sorry, I had to cancel it as I need CI resources for the release.

**Comment by sberyozkin** [comment]
@gsmet sure
@pedroigor thanks for finding this Silent handler :-), I'm following with the PR to the quickstarts to minimize the noise in the native mode

**Comment by pedroigor** [comment]
Not sure though it is going to help ... But it should reduce some noise in logs. I've tried to raise timeout too which I think may be related (when testing logout).

I'll try to keep an eye on any failure in PRs so that I see the error and avoid making assumptions. If you see something, please let me know so I can look logs.

**Comment by sberyozkin** [comment]
@pedroigor it [did help with the noise reduction](https://github.com/quarkusio/quarkus-quickstarts/pull/406#issuecomment-566415389) at least :-). Yes, if I see it failing then I'll copy the error message. @gsmet Hi Guillaume, please copy it if you spot it as well :-)

**Pull request merged**
