### PR TITLE
Jakarta - Make sure all versions are proper strings in rewrite.yml

### PR DESCRIPTION
**Pull request by gsmet**
I don't think we had any funky behaviors but let's make sure we won't get bit by this at some point.

### CODE REVIEW

**Comment by gsmet** [comment]
@Sanne FYI.

**Comment by Sanne** [comment]
@gsmet nice, thanks! Bear in mind @gastaldi had suggested to me to use double quotes - I hope there's no subtle difference there :)

**Comment by gastaldi** [comment]
Single quotes should work fine too. YAML works in mysterious ways :)

**Comment by Sanne** [comment]
great, thanks for confirming @gastaldi :+1:

**Comment by gsmet** [comment]
I tested it locally before pushing (you know how I am).

**Pull request merged**
