### PR TITLE
Add a logging-gelf integration test with ELK

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by loicmathieu** [comment]
This time, I move the call to the rest endpoint that generates the log in the retry of awaitability.
I think the first issue was that the log was issued too late so lost by graylog.

I launch two times the CI on my fork and the CI was green for both (so the test ran 6 times).
I didn't add it to any native test, should I do that also?

I plan to launch the CI multiple times before merging it to be 100% sure it will not break it again

**Comment by geoand** [comment]
> I didn't add it to any native test, should I do that also?

We used to have it IIRC, so best have it now as well

**Comment by loicmathieu** [comment]
JDK 8 test fail, so this change is not enought to provides a stable IT.
Maybe it will be easier to switch to logstash/elastic as it will imply less components.

**Comment by loicmathieu** [comment]
@gsmet @geoand I rewrite the logging-gelf test with Logstash/Elasticsearch and it seems to be stable.
I launch it multiple times in my fork and the last to times it runs without any issue :)

I had to increase the wait time for logstash to start as it needs to wait for elasticsearch to prepare the index before its pipeline can be ready, maybe we will need to increase it (in the pom.xml) if things failed.

**Comment by geoand** [comment]
Sounds good! Let's see what CI says

**Comment by loicmathieu** [comment]
@geoand I run the CI twice and each time it didn't fail, I think it's safe to merge it.

**Review by geoand — APPROVED** [review]
Thanks!

**Pull request merged**
