### PR TITLE
Move JSON-related JPA tests to their own module

### LINKED ISSUE #37498: [GraalVM for JDK 22] quarkus-integration-test-jpa-postgresql test fails with latest GraalVM master
### Describe the bug

The native integration test tracking that XML factories from the JDK are not included are failing with latest GraalVM master builds and JDK `22+25` early access. The failure looks like this (and has been seen from around Nov 22 onwards):

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.835 s <<< FAILURE! -- in io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase
Error:  io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative -- Time elapsed: 0.190 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Type 'com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl' was found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20231204_161950.txt
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContainsNot(ClassInclusionReport.java:67)
	at io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative(JPAFunctionalityInGraalITCase.java:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:816)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

See:
https://github.com/graalvm/mandrel/actions/runs/7087354809/job/19288795063#step:12:521

And indeed the image size increased from `~74MB` (from a [Nov 22 ](https://github.com/graalvm/mandrel/actions/runs/6951713819/job/18914879806#step:12:376) build) to `~87MB` which is about the same size as the one including the XML factories.

We see the same failure on JDK 21-based GraalVM CE builds. See:
https://github.com/graalvm/mandrel/actions/runs/7087354812/job/19288620329#step:12:522

### PR DESCRIPTION
**Pull request by marko-bekhta**
fixes https://github.com/quarkusio/quarkus/issues/37498

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
Hmm, could we stand by a bit?

I'm not exactly a big fan of adding yet another native module (it wasn't declared as one but probably should be).

Also I'm a bit worried that just adding Jackson makes our ORM optimization go away.

Because, well, most people add Jackson so this optimization is then completely useless in a lot of cases.

**Comment by yrodiere** [comment]
> Because, well, most people add Jackson so this optimization is then completely useless in a lot of cases.

... True. Especially since it seems we don't support XML serialization with Jackson; at least I couldn't find that in the docs.

So, I guess the problem becomes that Jackson (hopefully) or Hibernate ORM (I hope not!) leads to XML parsers being detected as used by GraalVM.

I can't work on this right now, so either this will wait, or someone will have to work on [native reports](https://quarkus.io/guides/native-reference#native-reports)... fun stuff.

**Comment by gsmet** [comment]
@zakkak any chance you could help us to understand what's going on and if the Jackson extension needs some tuning?

**Comment by zakkak** [comment]
Sure, I will have a look, but it might take a while.

**Comment by galderz** [comment]
> So, I guess the problem becomes that Jackson (hopefully) or Hibernate ORM (I hope not!) leads to XML parsers being detected as used by GraalVM.

I'm not sure the issue is really related to Jackson, but more the fact that when JSON integration was added, XML integration was also included and JAXB was added as an optional dependency: https://github.com/quarkusio/quarkus/pull/35113/files#diff-af9399740cc05097b1e4d8ae864622d81b6ab8f927375a047f81bbf8e9d1477bR146-R160

Seems to me you need different modules JAXB, same as you have different integration test for postgresql with xml.

**Comment by yrodiere** [comment]
Thanks for having a look.

> Seems to me you need different modules for Hibernate and JAXB integration, separate from those that integrate Hibernate and JSON (Jackson).

I'd rather avoid that if possible... It's not very intuitive, especially since upstream bundles it all in a single module.

> I'm not sure the issue is really related to Jackson, but more the fact that when JSON integration was added, XML integration was also included and JAXB was added as an optional dependency: https://github.com/quarkusio/quarkus/pull/35113/files#diff-af9399740cc05097b1e4d8ae864622d81b6ab8f927375a047f81bbf8e9d1477bR146-R160

Alright, but it's optional; I hope an optional dependency, by itself, won't trigger code from that dependency to be added to the native image... ? The very point of an optional dependency is that it's ignored at runtime unless someone else adds a non-optional dependency to the same artifact...

Anyway, if that's not the case, I imagine that PR did add some code that might confuse GraalVM into thinking we use JAXB. This looks like a prime suspect:

https://github.com/quarkusio/quarkus/blob/47ecd0a245b26e85a2b01536f182f3292e95b2e8/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/customized/FormatMapperKind.java#L31-L34

Maybe that code, or `org.hibernate.type.format.jaxb.JaxbXmlFormatMapper`, should be eliminated when JAXB is not present in the classpath (the runtime one, ignoring optional dependencies)?

Would that make sense @galderz?

**Comment by galderz** [comment]
>Alright, but it's optional; I hope an optional dependency, by itself, won't trigger code from that dependency to be added to the native image... ? The very point of an optional dependency is that it's ignored at runtime unless someone else adds a non-optional dependency to the same artifact...

Optional dependencies are just a concept of Maven. Neither JDK nor GraalVM really has such a concept so anything you bring in through that is considered part of the universe. I wrote about the issues these have [here](https://quarkus.io/guides/writing-native-applications-tips#modularity-benefits).

> Anyway, if that's not the case, I imagine that PR did add some code that might confuse GraalVM into thinking we use JAXB. This looks like a prime suspect:
> 
> https://github.com/quarkusio/quarkus/blob/47ecd0a245b26e85a2b01536f182f3292e95b2e8/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/customized/FormatMapperKind.java#L31-L34
> 
> Maybe that code, or `org.hibernate.type.format.jaxb.JaxbXmlFormatMapper`, should be eliminated when JAXB is not present in the classpath (the runtime one, ignoring optional dependencies)?
> 
> Would that make sense @galderz?

I think it's more nuanced than that, because the last release GraalVM and/or Mandrel releases work fine with this. So this is not an immediate issue. The problem arises when you try with the very latest GraalVM code along with a newer JDK (the issue seems to appear with both latest JDK 21 and 22). Either of these two parts is causing this to break now but I don't know yet.

All my investigations so far lead up to this entry point which is a bit of a dead end:
```
├── entry com.oracle.svm.core.code.FactoryMethodHolder.DOMSerializer_constructor_ed8d8ed1c0ba7927c499a8c3ec42227bb4ec6043():com.fasterxml.jackson.databind.ext.DOMSerializer id=633 
│   └── directly calls com.fasterxml.jackson.databind.ext.DOMSerializer.<init>():void id=12495 @bci=1 
```

I'll see if I can git bisect on either the GraalVM or JDK code to try to narrow down the cause.

**Comment by galderz** [comment]
This has been fixed in GraalVM upstream so this PR is no longer needed.

**Comment by marko-bekhta** [comment]
Nice! thank you @galderz 🎉

**Pull request closed without merging**
