### PR TITLE
Update SmallRye Health to 2.2.1

### LINKED ISSUE #91: Performance cost of Json
Currently, SmallRyeHealthReporter use the `javax.json.Json` helper class to create the various Json builder/factory that it needs (JsonArrayBuilder, JsonObjectBuilder, JsonWriterFactory).

This class calls `JsonProvider.provider()` without caching it (the JavaDoc of JsonProvider say that it's safe to cache it) each time it creates a new Json builder/factory.
As `JsonProvider.provider()` uses a ServiceLoader to load the Json implementation, this is a very costly operation.

If the code is updated to cache an instance of JsonProvider and to use this instance to create the various Json object instead of using the Json helper class this performance cost should disapear.

### PR DESCRIPTION
**Pull request by jmartisk**
To include the performance fix https://github.com/smallrye/smallrye-health/issues/91

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by machi1990** [comment]
Do we have plan to add this to dependabot? @jmartisk

**Comment by jmartisk** [comment]
@machi1990 that's a good idea I think, there are some SmallRye projects there, but not all. I'll come up with a PR soon

**Comment by machi1990** [comment]
Thanks

**Pull request merged**
