### PR TITLE
Move core configuration to @ConfigMapping

### LINKED ISSUE #42114: Core module is using a mix of traditional `@ConfigRoot` and `@ConfigMapping`
@radcortez if you want to help, it would be nice if you could make sure the `quarkus-core` modules (runtime and deployment) uniformly use `@ConfigMapping` (or `@ConfigRoot`, your choice but I suspect you will choose the former).

This won't be allowed anymore with the new annotation processor.

See `PackageConfig` for `@ConfigMapping` and `ShutdownBuildTimeConfig` for traditional `@ConfigRoot`.

### LINKED ISSUE #43149: `  quarkus.configuration.build-time-mismatch-at-runtime` should be in the `quarkus.config` namespace
We have several `quarkus.config.*` properties in the tree and we have `quarkus.configuration.build-time-mismatch-at-runtime` that is in a separate config root.

It should be moved to the `quarkus.config` root.
I'm not sure it's worth deprecating it properly as it seems very technical and probably not something people would widely use?

/cc @radcortez for advice.

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #42114
- Fixes #43149

We still miss `ClassLoadingConfig`, which needs to be handled separately.

Please merge the following PRs first to address a couple of performance issues:
- https://github.com/quarkusio/quarkus/pull/44455
- https://github.com/quarkusio/quarkus/pull/44448

### CODE REVIEW

**Comment by gsmet** [comment]
@radcortez the failures look related.

BTW, maybe we could tackle https://github.com/quarkusio/quarkus/issues/43149 at the same time, while we're at it?

**Comment by radcortez** [comment]
Yes, I was already expecting something to fail, and I also wanted to implement #43149, which is why I added "not merge" in the description.

I'll complete this in the meantime.

**Comment by gsmet** [comment]
I'm not sure why only Java 21 build is failing but the failure:

```
Build failed due to errors
	[error]: Build step io.quarkus.artemis.core.deployment.DevServicesArtemisProcessor#startArtemisDevService threw an exception: java.lang.RuntimeException: java.lang.NoSuchFieldError: Class io.quarkus.deployment.dev.devservices.GlobalDevServicesConfig does not have member field 'java.util.Optional timeout'
```

looks suspicious?

**Comment by radcortez** [comment]
> I'm not sure why only Java 21 build is failing but the failure:
> 
> > Build failed due to errors
> > [error]: Build step io.quarkus.artemis.core.deployment.DevServicesArtemisProcessor#startArtemisDevService threw an exception: java.lang.RuntimeException: java.lang.NoSuchFieldError: Class io.quarkus.deployment.dev.devservices.GlobalDevServicesConfig does not have member field 'java.util.Optional timeout'
> 
> looks suspicious?

Hum, I thought it was just a docker container that randomly failed to start. The problem is that we have a Quarkiverse dependency in the test, which uses the code I just changed:

https://github.com/quarkusio/quarkus/blob/9fd098a84cf4f8ce1e717ebd9eb6551adc94732a/integration-tests/virtual-threads/jms-virtual-threads/pom.xml#L48-L52

https://github.com/quarkiverse/quarkus-artemis/blob/main/core/deployment/src/main/java/io/quarkus/artemis/core/deployment/DevServicesArtemisProcessor.java#L133

Should we be depending on Quarkiverse artifacts?

**Comment by gsmet** [comment]
> Should we be depending on Quarkiverse artifacts?

No, we shouldn't as it creates a cycle and there's no way to get around it as you won't be able to release the Artemis extension with this fix without a Quarkus core release.
So we need to break this dependency or we're going to be stuck. Maybe this test should be moved to the Artemis project or it should be rewritten to avoid the Artemis dependency but we would need another JMS implementation that is available in core? It might cause us missing some VT issues though if we move it to the Quarkiverse extension.

@cescoffier what's your take on this?

**Comment by gsmet** [comment]
FWIW, I would be in favor of disabling the test and merging this while we figure out a solution as it will be extremely prone to conflicts.

**Comment by radcortez** [comment]
Alternatively, we can hold the move of the related configuration, but I would prefer to disable the test :)

**Comment by zakkak** [comment]
@radcortez I am on the road today, but I plan to test this PR and report back any potential changes in binary size (probably tomorrow or the day after). As discussed in https://github.com/quarkusio/quarkus/pull/39748#issuecomment-2025137382, the changes are not expected to have a huge impact but it's worth having a look before moving forward. Thank you.

For reference, this should also help us with https://github.com/quarkusio/quarkus/issues/44312

**Comment by radcortez** [comment]
> @radcortez I am on the road today, but I plan to test this PR and report back any potential changes in binary size (probably tomorrow or the day after). As discussed in [#39748 (comment)](https://github.com/quarkusio/quarkus/pull/39748#issuecomment-2025137382), the changes are not expected to have a huge impact but it's worth having a look before moving forward. Thank you.
> 
> For reference, this should also help us with #44312

Sure. I'm also taking some measurements of RSS and startup time. There is a slight increase, but these are related to some additional checks that I'll address in a separate PR.

**Comment by radcortez** [comment]
Thanks!

I guess that a slight increase in the image size may occur due to the following factors:

- The old implementation uses a plain POJO, where the config logic to populate the values is a centralized piece that deals with all the details. We also generate some code for each POJO to handle a few specific cases. This code goes away when replaced with the new implementation.
- The new implementation doubles the class usages (for each interface we generate an implementation)
- Each implementation contains the logic to populate itself
- Each implementation contains an `equals` and `hashcode`

So compared to the old approach, we are adding x2 classes, and each class contains and `equals` and `hashcode` with the populate code. Apparently, the delta between both does cause a slight increase in the native binary, but it may be possible to further optimize these. I already did some improvements here:
- https://github.com/quarkusio/quarkus/pull/44455
- https://github.com/quarkusio/quarkus/pull/44448

Regarding the RSS usage, I really have no idea what would be the cause. We are now extensively using mappings in a lot of other places and we never had such problem.

**Comment by gsmet** [comment]
I think it would still be interesting to get a diff of the list of classes in the case of `picocli-native` to make sure it's expected and there's nothing we don't expect.

**Review by gsmet — APPROVED** [review]
Let's merge this as it's where we want to go.

We will need to make sure we improve things as much as possible though.

**Pull request merged**
