### PR TITLE
Bump Gradle to version 7.6

### PR DESCRIPTION
**Pull request by glefloch**
This bumps gradle to 7.6 with java 19 support !

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
It could just be flaky tests but there are a lot more than usual. Probably worth a look.

**Comment by famod** [comment]
There seem to be metaspace and heap issues.

**Comment by famod** [comment]
We should probably wait for https://github.com/gradle/gradle/issues/23215 to be fixed (currentlty assigned to 7.6.1)

**Comment by gastaldi** [comment]
Let's wait if that is fixed in 7.6.1. Closing this now

**Pull request closed without merging**
