### PR TITLE
Improve response filter documentation

### LINKED ISSUE #36955: `@ServerResponseFilter` with `Throwable` parameter is not called when REST resource is throwing an exception
### Describe the bug

https://quarkus.io/guides/resteasy-reactive#request-or-response-filters
image
implies that a `@ServerResponseFilter` method can handle exceptions, but that does not seem to be the case (see reproducer).

### Expected behavior

Filter method should be called with the exception that was thrown in a rest resource method.

### Actual behavior

Filter is not called with the exception that was thrown in a rest resource method.

### How to Reproduce?

- clone https://github.com/famod/quarkus-quickstarts/tree/server-response-filer-exc
- cd opentelemetry-quickstart
- mvn clean install
- testFailEndpoint will fail because the trace-id header is missing (because the filter is not called)
- in `TraceHeaderServerResponseFilter` activate `@ServerExceptionMapper` -> test will pass

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.5.0 (and current main respectively)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Close: #36955

### CODE REVIEW

**Comment by famod** [comment]
Ah, interesting - confirmed with small reproducer; I only need a matching `@ServerExceptionMapper` _which doesn't need to set the header though!_
The irony is that for some reason I tried it via the quickstart right away instead of in my app - and there I already have matching exception handlers. :man_facepalming: 

WDYT about making it more explicit by adding:
> Such a reponse filter will also be called for <<exception-mapping, handled>> exceptions.

just above
> Your filters may declare any of the following parameter types:

My reasoning here is that you don't need to add the `Throwable` parameter and your filter will still be called.

**Comment by geoand** [comment]
I all for making it more clear for readers, but I am not sure I understand how you would like it to look.
If you want to push a change into my branch, that's fine with me :)

**Comment by famod** [comment]
I've pushed what I had in mind.

**Review by famod — APPROVED** [review]

**Comment by geoand** [comment]
🙏🏼

**Comment by famod** [comment]
I've just realized that even a Jakarta-way `ContainerResponseFilter` is called for mapped exceptions. I'll add a note there too.

**Pull request merged**
