### PR TITLE
Qute: inject attributes in template extensions methods

### LINKED ISSUE #15718: Qute: Template attributes in template extensions
I would like to implement a template extension method to properly format a `MonetaryAmount` parameter. Here it would be great if I could use the `locale` attribute of the `TemplateInstance`, which I already use for the `MessageBundles` anyway.

It would be great if you could inject the specific value via an annotation. 

```java
@TemplateExtension
public class TemplateExtensions {

    public static String formatMoney(MonetaryAmount price, @TemplateAttribute("locale") Locale locale) {
        var formatter = MonetaryFormats.getAmountFormat(AmountFormatQuery.of(locale));
        return formatter.format(price);
    }
}
```

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #15718

### CODE REVIEW

**Comment by gsmet** [comment]
CI is failing with:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1-jboss-1:compile (default-compile) on project qute-generator: Compilation failure
Error:  /home/runner/work/quarkus/quarkus/independent-projects/qute/generator/src/main/java/io/quarkus/qute/generator/ExtensionMethodGenerator.java:[680,49] cannot find symbol
Error:    symbol:   class Param
Error:    location: class io.quarkus.qute.generator.ExtensionMethodGenerator
Error:  -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1-jboss-1:compile (default-compile) on project qute-generator: Compilation failure
/home/runner/work/quarkus/quarkus/independent-projects/qute/generator/src/main/java/io/quarkus/qute/generator/ExtensionMethodGenerator.java:[680,49] cannot find symbol
  symbol:   class Param
  location: class io.quarkus.qute.generator.ExtensionMethodGenerator
```

**Comment by gsmet** [comment]
What is weird is that the other JDK builds are not failing. @mkouba rings a bell or it's a glitch?

**Comment by mkouba** [comment]
Looks like some odd compilation problem... it should be OK now (I've verified locally with JDK8).

**Comment by mkouba** [comment]
Hm, failures look unrelated...
```
2021-03-16T23:41:37.4611272Z [ERROR] Failures: 
2021-03-16T23:41:37.4612087Z [ERROR]   BasicKubernetesTest.assertDependencies:108 
2021-03-16T23:41:37.4613106Z Expecting directory:
2021-03-16T23:41:37.4615880Z   /home/runner/work/quarkus/quarkus/integration-tests/kubernetes/quarkus-standard-way/target/quarkus-prod-mode-test16070550556064391413/build-result/quarkus-app/lib/main
2021-03-16T23:41:37.4617428Z not to contain any files matching the given filter but found some:
2021-03-16T23:41:37.4626314Z   [/home/runner/work/quarkus/quarkus/integration-tests/kubernetes/quarkus-standard-way/target/quarkus-prod-mode-test16070550556064391413/build-result/quarkus-app/lib/main/io.quarkus.quarkus-kubernetes-client-internal-999-SNAPSHOT.jar]
```

**Review by gsmet — APPROVED** [review]

**Pull request merged**
