### PR TITLE
Check whether outputDirectory is the root of the file system before using its parent

### PR DESCRIPTION
**Pull request by aloubyansky**
@phillip-kruger does it make sense to you?

It seems like this could happen in remote dev case.

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by vsevel** [comment]
I am trying quarkus core main and now I have:
```
Caused by: java.nio.file.AccessDeniedException: /target
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
at java.base/java.nio.file.Files.createDirectory(Files.java:699)
at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
at java.base/java.nio.file.Files.createDirectories(Files.java:793)
at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeGeneratedSchema(SmallRyeOpenApiProcessor.java:950)
```

I added back this to go further:
```
quarkus:
  smallrye-openapi:
    store-schema-directory: /tmp
```

**Comment by vsevel** [comment]
can't reproduce it anymore... we are good (until it comes back)

**Comment by vsevel** [comment]
I take that back: https://github.com/quarkusio/quarkus/issues/40501

**Pull request merged**
