### PR TITLE
Update SR Health to 3.0.0

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks but this update is done as part of the MicroProfile 4 branch (and same for all the MicroProfile major upgrades).

**Comment by tobiasstadler** [comment]
@gsmet yes, I know. That is why the target branch is microprofile-4

**Comment by xstefank** [comment]
there already is a PR - https://github.com/quarkusio/quarkus/pull/14358

**Comment by tobiasstadler** [comment]
Ok, I didn‘ see that.

**Pull request closed without merging**
