### PR TITLE
Expose the new dev ui under /q/dev The old dev ui is under /q/devui-v1

### PR DESCRIPTION
**Pull request by cescoffier**
The old dev ui is under /q/devui-v1.

### CODE REVIEW

**Comment by gastaldi** [comment]
How about naming it `/q/dev/v1/`? That would make it simpler to type ;)

**Comment by phillip-kruger** [comment]
Hi @cescoffier . When we started the new Dev UI we intentionally made the url `/q/dev-ui` to be the same as other UI (`swagger-ui`, `graphql-ui`, `health-ui`) and the plan was to, when we migrate, route `/q/dev` to `/q/dev-ui`. So dev will still work, but redirect to dev-ui. That will also make this change much smaller ? w.d.y.t ?

**Comment by cescoffier** [comment]
I can try to setup the redirection. The difficulty is mostly move the old one, as their is lots of substring / startWith and regexp. Finding something that does not collide is not simple (and seems that even the current one does not work). I will have another look this week (but cannot tell you when exactly)

**Comment by phillip-kruger** [comment]
Thanks @cescoffier !

**Comment by cescoffier** [comment]
Superseded by #32151.

**Pull request closed without merging**
