### PR TITLE
Support running tests from third party test-jars transformed using

### PR DESCRIPTION
**Pull request by ppalaga**
rpkgtests-maven-plugin

cc @aloubyansky

### CODE REVIEW

**Comment by aloubyansky** [comment]
I'll try one alternative approach tonight.

**Comment by aloubyansky** [comment]
> I'll try one alternative approach tonight.

I'm getting some classpath issues but it looks like it might work, so I'll continue looking into it tomorrow.

**Comment by gsmet** [comment]
@aloubyansky Max asked me to review this one. Not sure what I can do, the patch looks safe enough and not risky at all so if it helps working around some issue, I would say let's get it in?

**Comment by aloubyansky** [comment]
Ok @gsmet

**Review by gsmet — APPROVED** [review]
Let's get this in for now, we can still remove it later if this approach doesn't end up being viable.

**Pull request merged**
