### PR TITLE
Smallrye RM 3.13.0 with Kafka client version 3.0.0

### PR DESCRIPTION
**Pull request by ozangunalp**
- Added snappy as provided dependency for the kafka extension, as it is now a runtime scoped dependency for `kafka-clients:3.0.0`
- Removed workaround for openjdk 7 and Mac for snappy native library

### CODE REVIEW

**Comment by ozangunalp** [comment]
Test on Reactive Messaging RC release. Do not merge

**Review by cescoffier — APPROVED** [review]
Is there anything we should mention in the doc? 
At least, we should mention that the client uses Kafka 3.0, but is compatible with Kafka brokers 2.0.

Does the doc cover snappy?

**Comment by ozangunalp** [comment]
I'll add the portion with Kafka client 3.0. 
The doc portion about snappy is still correct.

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
Should this be merged now or are we waiting for something?

**Pull request merged**
