### PR TITLE
Move QuarkusModelBuilderTest from the plugin module to Gradle IT

### PR DESCRIPTION
**Pull request by aloubyansky**
The issue with this test is that the projects it is testing apply the Quarkus plugin which hasn't been installed yet in the local repo at the time of testing.
TBH, I am not sure how to write this kind of test the best way, atm. If I move to IT then I have to add the plugin itself as the test dependency, which isn't nice. Perhaps, we could extract the model loading classes to their own project and use that project as the dependency of the plugin and the IT.

### CODE REVIEW

**Review by glefloch — APPROVED** [review]
LGTM. 
I agree with you, we could maybe move the `QuarkusModelBuilder` class in `bootstrap/gradle-resolver` module, I think all dependencies are already there.

**Comment by aloubyansky** [comment]
That is probably a good idea @glefloch. The class does depend on `org.gradle.api`. Which means the `gradle-resolver` should probably become a Gradle project, which wouldn't be wrong. Except that it will complicate our build in one other place.

**Comment by glefloch** [comment]
You right, we only depend on `gradle-tooling-api` on that module. 
Another possibility could be to convert our existing `gradle-plugin` project into a multi-module project.

**Comment by gsmet** [comment]
So should we go ahead with this PR or not?

**Comment by aloubyansky** [comment]
I think so. Extracting the class to a different module could be a separate task. This change will allow testing the plugin as part of the release.

**Comment by glefloch** [comment]
Yes that could definitely be something we can do later.

**Review by gsmet — APPROVED** [review]
Ok, let’s merge it then, thanks!

**Pull request merged**
