### PR TITLE
Use AbstractLocationConfigSourceLoader to load application.properties and application.yaml

### LINKED ISSUE #6810: Multiple per-profile configuration files or includes
Several users have asked us to put their config in multiple files. This is not good generally, but there's no good reason to prevent people from doing it if they must.

There are several strategies possible:

Nr.|Strategy|Pros|Cons
---|---|---|---
1|`application-%profile.properties`, fall-back to `application.properties` if not found|Clear mapping with fallback|No composition (single file)
2|`application.properties` + `application-%profile.properties` if it exists|Composition possible|Users are bound to ask for reversing the order of composition, or how to unset a config value set by the previous file
3|Support `@include=application-%profile.properties` directives|We don't take sides, composable and extendable|No default guideline/convention to follow

Am I missing options, pros, cons?

### LINKED ISSUE #9869: Respect submodule application.properties config when packaging the application
**Description**

When using a shared library module between several application modules, you probably will have some library-specific properties set, like default timeouts, urls etc.

Currently you have to redefine them in the application.properties file of the application module, as the properties of the library are not carried into the application and therefore those config entries are missing.

It leads to this issue:

[**"DeploymentException: No config value of type [java.lang.String] exists for" #8999**](https://github.com/quarkusio/quarkus/issues/8999)

Redefining all library module properties in each application would create a huge mess and discrepancys over time if not handled carefully

**Implementation ideas**

I think it would be helpful to have some kind of merging, where library properties are threated as default values unless they are overwritten by a property defined in the application´s .properties file.

### LINKED ISSUE #12507: Pick a profile config properties automatically in @TestProfile
I updated myself to the latest Quarkus 1.8.1.Final, obviously the testing feature is improved.

I have tried to use `@TestProfile` to test my Repository against an embedded H2 database instead of the default Postgres database.

Now my working example is like this.

* Java 11
* Windows 10 64bit
* only test on jvm

The profile class is simple, try to create an H2 data source here.

```java
public class H2Profile implements QuarkusTestProfile {
    @Override
    public Map<String, String> getConfigOverrides() {
        return Map.of(
                "quarkus.datasource.url", "jdbc:h2:tcp://localhost/mem:test",
                "quarkus.datasource.driver", "org.h2.Driver",
                "quarkus.hibernate-orm.database.generation", "drop-and-create",
                "quarkus.hibernate-orm.log.sql", "true"
        );
    }

    @Override
    public String getConfigProfile() {
        return "h2";
    }
}
```
And the test class.

```java
@QuarkusTest
@QuarkusTestResource(H2DatabaseTestResource.class)
@TestProfile(H2Profile.class)
public class PostRepositoryTest {

    private final static Logger LOGGER = Logger.getLogger(PostRepositoryTest.class.getName());

    @Inject
    private PostRepository posts;

    @Test
    public void testPersistence() {
        this.posts.listAll().forEach(p -> System.out.println("Post:" + p));
        Assertions.assertTrue(this.posts.findAll().list().size() == 2, "result list size is 2");
    }

}
```

I would like to use an *application.properties* file to override the config at runtime when running a test. I hope there are some improvements.

1. The `H2Profile` has a unique config profile name(**h2**), by convention,  the test will scan the classpath if there is an *application-h2.properties* for this profile.
2. In the `@TestProfile` add a configFile attribute to accept a custom properties file located in the classpath. eg. "propertiesFile= test-datasources.properties".

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #6810
- Fixes #9869
- Fixes #12507

These may be a little controversial, since it changes how we are using `application.properties`. 

In essence, having `application.properties` scanning in the classpath  aligns the behaviour of `microprofile-config.properties`. Some users already complained about this difference, and that they want to load the files from sub modules. With `application.properties`, this is not possible, so they need to use `microprofile-config.properties`.

The profile aware `application-{profile}.properties` has been requested as well, and it was added in MP Config 2.0, creating one more inconsistency once we move. This will align both files again.

### CODE REVIEW

**Comment by gsmet** [comment]
I rebased this one. Let's see how CI goes.

**Comment by radcortez** [comment]
Thanks!

**Comment by gsmet** [comment]
CI failure looks related.

**Comment by radcortez** [comment]
Ok, let me check.

**Review by gsmet — APPROVED** [review]
OK, let's get this into CR1.

@radcortez could you write a blurb about the new possibilities that I could include in the announcement? Thanks!

**Pull request merged**
