### PR TITLE
Replace deprecated classAnnotation(s) with declaredAnnotation(s)

### PR DESCRIPTION
**Pull request by rsvoboda**
- Replace deprecated classAnnotation(org.jboss.jandex.DotName) with declaredAnnotation(org.jboss.jandex.DotName)
 - Replace deprecated classAnnotations() with declaredAnnotations()
 - Replace deprecated classAnnotationsWithRepeatable(name, index) with declaredAnnotationsWithRepeatable(name, index)

### CODE REVIEW

**Comment by rsvoboda** [comment]
(re-based due to conflict on ResteasyReactiveScanner.java file)

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
The test failure is weird:

```
Error: [ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception:
java.lang.IllegalStateException: Out of date version of GraalVM detected:
native-image 21.3.6.0-Final Mandrel Distribution (Java Version 17.0.7+7). Quarkus currently supports 22.3.0.
Please upgrade GraalVM to this version.
```

**Comment by rsvoboda** [comment]
re-based due to merge conflicts

**Comment by rsvoboda** [comment]
CI is green, ready for merge, cc @gsmet

**Pull request merged**
