### PR TITLE
Only record config properties coming from ConfigSources

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@radcortez can you rebase the change?

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
hmm... there's quite a lot of failures that I haven't seen before.

**Review by michalszynkiewicz — CHANGES_REQUESTED** [review]
I think the failures need to be investigated before merging

**Comment by radcortez** [comment]
> @radcortez so with https://github.com/quarkusio/quarkus/pull/20602/files the tests are passing?

Not exactly. The change that I did here uncovered an issue with GraphQL, that is related to #20494. GraphQL is also using an interceptor to relocate some properties, but only for build time (when some of the properties are runtime). Because we removed here the recording of interceptor properties, these keys are not recorded, but they are also not reread on runtime because the GraphQL configuration is set up to be build-time only.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by radcortez** [comment]
> I think it should be backported to 2.4, @radcortez is there any other related PR that has to be backported too?

Yes. It requires https://github.com/quarkusio/quarkus/issues/20494.

**Pull request merged**
