### PR TITLE
Update Timing.java

### PR DESCRIPTION
**Pull request by survivant**
fix the typo %ss -> %s s

### CODE REVIEW

**Comment by famod** [comment]
Thanks for this contribution.

I might be wrong but AFAIK everything goes into `master` and when labeled with `triage/backport?` @gsmet will decide whether or not to backport it explicitely to the release specific branch.
So I suppose the target branch should be `master` instead.

**Comment by survivant** [comment]
it's for the issue : https://github.com/quarkusio/quarkus/issues/10746

**Comment by geoand** [comment]
Thanks for this.

Like @famod said, all PRs should be made against `master`, not `1.6`. The `triage/backport` label is enough for us to know that the PR should be backported to 1.6.
So please rebase the PR against `master` instead of `1.6`

**Comment by famod** [comment]
@geoand FYI, there is an ongoing discussion whether this change is really needed or whether this problem has other reasons (different logging implementation?): #10749

**Comment by survivant** [comment]
I'll try redo the PR using master

**Comment by geoand** [comment]
> @geoand FYI, there is an ongoing discussion whether this change is really needed or whether this problem has other reasons (different logging implementation?): #10749

I purposely staying out of that discussion :). Y' all can figure it out :laughing:

**Review by gsmet — CHANGES_REQUESTED** [review]
Yeah, I don't understand the reason of this change as it works OK.

**Comment by survivant** [comment]
I created a new PR https://github.com/quarkusio/quarkus/pull/10760  if that can help.  You can close this PR

**Pull request closed without merging**
