### PR TITLE
Take 'enable' field into account for named logging handlers

### LINKED ISSUE #17913: Named logging handlers can't be disabled
## Describe the bug
When configuring a named logging handler (like `quarkus.log.handler.console."STRUCTURED_LOGGING"` or `quarkus.log.handler.console."STRUCTURED_LOGGING_FILE"`), those handlers are always used, no matter what the value of the `enable` flag is for that named handler.

### Expected behavior
The named handler's `enable` flag is taken into account and can be used to disable a named handler.

## Additional context
The problem was originally reported at https://stackoverflow.com/q/67959479/2504224

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #17913

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by jotjeeven** [comment]
This issue is still reproducible in 2.0.0.Final, Kindly check

**Comment by geoand** [comment]
Can you attach an example application?
When I tried this, it worked just fine, so if it doesn't work for you, an example application is the best way to check

**Comment by jotjeeven** [comment]
@geoand Verified the same, it is working fine, Version was not updated at my end, after updation it is working well.
Thanks !!

**Comment by geoand** [comment]
Great, thanks for letting us know!

**Pull request merged**
