### PR TITLE
Use the JUnit BOM

### PR DESCRIPTION
**Pull request by gastaldi**
So Dependabot can update all the artifacts in a single PR.
See https://github.com/quarkusio/quarkus/pull/20083#issuecomment-918174254

### CODE REVIEW

**Comment by geoand** [comment]
I thought there was a reason we didn't do that, but I can't remember...

**Comment by aloubyansky** [comment]
Are we switching from a single JAR constraint to the BOM here?

**Comment by gastaldi** [comment]
> Are we switching from a single JAR constraint to the BOM here?

IMHO it doesn't change anything in practice. In fact using the BOM here is safer in case any of the other submodules start depending on any other Jupiter module.

**Comment by aloubyansky** [comment]
I think we should consider this once there is another module that actually adds a dependency on another junit artifact.

It does have a cost. Including more constraints increases the build time of core and the platform because our tools analyze the content of the BOMs (unless some constraints are explicitly excluded).  The BOM also grows in size. We also don't really know what will come in the next version of the BOM. If we follow this principle for every constraint we include, we'll end up with a big mess and longer build times. Given that, as you said, there is no technical reason for it yet, I am -1 for now.

**Comment by gastaldi** [comment]
That's fine, we can simply merge https://github.com/quarkusio/quarkus/pull/20083 as is now.

**Pull request closed without merging**
