### PR TITLE
Updating Documentation to use QuarkusMultipartForm with rest-client-reactive

### PR DESCRIPTION
**Pull request by doogle-oss**
We are discussing on using QuarkusMultipartForm and since Quarkus 3.4.x with all reactive rest client and no support for legacy quarkus-resteasy-multipart which causes resteasy classic and resteasy reactive mixing issue adding documentation to use QuarkusMultipartForm to custom build forms if needed ideally for supporting List<File>/ List<Path> etc.

### CODE REVIEW

**Comment by debu999** [comment]
This is to support the discussion and open issue #37765
Discussion #36780

**Comment by debu999** [comment]
@gsmet @geoand @Sgitario Can you please review if the changes are inline with Quarkus standards to merge. Please advise if any other changes are needed.

**Comment by geoand** [comment]
Hi,

We're on PTO these days so not much is really going on on any front.

**Comment by geoand** [comment]
Thanks a lot for this!

Actually, I think that I am going to change the package of the multipart classes as using `impl` in the name suggests they are private.

**Comment by gsmet** [comment]
> Actually, I think that I am going to change the package of the multipart classes as using impl in the name suggests they are private.

+1

**Comment by geoand** [comment]
It's looks like untangling which parts constiture the API is going to be a little more involved.

**Comment by geoand** [comment]
I would prefer we close this and request @debu999 to add the docs commit once #38031 is in

**Comment by debu999** [comment]
> I would prefer we close this and request @debu999 to add the docs commit once #38031 is in

will wait for 38031 to be merged to main so i can test the same share a new PR with doc updates.

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
#38031 was just merged

**Comment by debu999** [comment]
Can we cancel this PR as i have raised a new one with #38075

**Pull request closed without merging**
