### PR TITLE
Bump kubernetes-client-bom from 6.13.1 to 6.13.3

### PR DESCRIPTION
**Pull request by manusa**
Kubernetes Client 6.13.3 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.13.3

~~Kubernetes Client 6.13.2 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.13.2~~

Related to #39934 

/cc @metacosm

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@metacosm I let you check this one.

**Comment by metacosm** [comment]
PR doesn't build in CI: https://github.com/quarkiverse/quarkus-operator-sdk/actions/runs/10332967104/job/28604798710#step:9:37275
Any idea what's going on?

**Comment by gsmet** [comment]
@metacosm my guess is that the version of Maven you use is too old (GitHub is known for shipping an old default version). Use `./mvnw` to build Quarkus.

**Comment by metacosm** [comment]
This is no-go for us at the moment. We're seeing issues similar to https://github.com/fabric8io/kubernetes-client/issues/6249 with the upgrade.

**Comment by metacosm** [comment]
Note that this is an example of why version checking alignment was introduced in QOSDK: a patch version discrepancy between Quarkus, JOSDK and QOSDK breaks end user apps and this is why some of our users wanted to be able to fail a build if such a situation was detected.

**Comment by gastaldi** [comment]
Ah crap, I didn't see the comments, I'm going to revert this, sorry for the trouble

**Comment by manusa** [comment]
Note that @metacosm comments are related to 6.13.2 (prior to my last commit that bumps to 6.13.3).

Supposedly 6.13.3 addresses the issue mentioned by Chris.

I'd wait for his comments before reverting because this might be already alright.

**Pull request merged**
