### PR TITLE
Add an Apache Lucene extension

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gustavonalle** [comment]
@gastaldi I was not aware of Quarkiverse, I'm fine being assigned to a repository over there

**Comment by gustavonalle** [comment]
btw @Sanne @yrodiere Are you fine having the Lucene extension outside Quarkus? Some extensions that are already in core like hibernate search or Infinispan may use it in the future, do you see any issue?

**Comment by Sanne** [comment]
@gustavonalle good question. So yes like Gastaldi suggested we're trying to move most / all non-core extensions into the Quarkiverse, not leat to keep CI and IDE-import times reasonable, so indeed this probably belongs in Quarkiverse as it's not widely depended on.

I think the way forward would be to have the Hibernate Search / Lucene backend also live in the Quarkiverse, while the Hibernate Search "core" components can stay where they are. Not sure if we should eventually move out the Elasticsearch backend as well, but we can discuss that another time.

At least, having Lucene in the Quarkiverse seems like a good start to me.  @maxandersen / @gsmet WDYT ?

**Comment by gsmet** [comment]
My opinion is that, if we decide to support Lucene for Hibernate Search, I would have the Lucene extension in Core. Hibernate Search belong to the Core as it's a companion for ORM I would like to be pushed much more often.

**Comment by Sanne** [comment]
@gsmet yes but this approach doesn't help to trim the number of extensions in core.  Could we keep it fluid? I'm thinking let this evolve in Quarkiverse, then we can pull it into core whenever we like.

Also, I'm not convinced that we should support/endorse the solution beyond specific needs (such as obviously Infinispan needing it) as the "cloud native" approach of Quarkus would have us support the remote backends only - so I wouldn't rush putting this in core.

**Comment by gsmet** [comment]
Can we have @yrodiere 's opinion on this? Because the plan for Hibernate Search would be the deciding factor IMHO.

(And note that I'm the first one pushing new extensions to the Quarkiverse - but this is a specific case)

**Comment by yrodiere** [comment]
Lucene is inherently single-node, unless significant infrastructure is added on top of it to distribute it (Elasticsearch, Solr, Infinispan). So it makes sense to move Lucene to the Quarkiverse, and also a hypothetical Hibernate Search + Lucene extension (which would be single-node too). I think that would still make sense even if Hibernate Search + Elasticsearch stayed in core, because **that** extension **is** cloud-ready.

Moving all of Hibernate Search out of the core is a bit extreme, but I agree it's damn hard to work on Quarkus with so many extensions in core. So if Hibernate Search has to go to the Quarkiverse "for the greater good", I could potentially understand it.

If extensions in the Quarkiverse can still be first-class citizens as far as Quarkus users are concerned, i.e. close to no difference in how users consume the extensions, obtain help, read documentation or report issues, then I'd say it's no big deal. If not, or if other extensions are not moved out of core in the same way, I may start making some noise ;)

**Comment by Sanne** [comment]
> Lucene is inherently single-node, unless significant infrastructure is added on top of it to distribute it (Elasticsearch, Solr, Infinispan). So it makes sense to move Lucene to the Quarkiverse, and also a hypothetical Hibernate Search + Lucene extension (which would be single-node too). I think that would still make sense even if Hibernate Search + Elasticsearch stayed in core, because **that** extension **is** cloud-ready.

Agreed.

> Moving all of Hibernate Search out of the core is a bit extreme, but I agree it's damn hard to work on Quarkus with so many extensions in core. So if Hibernate Search + Elasticsearch has to go to the Quarkiverse "for the greater good", I could potentially understand it.

I haven't suggested that, what I suggested is for the Lucene backend of Hibernate Search to be in Quarkiverse - at least initially.

> If extensions in the Quarkiverse can still be first-class citizens as far as Quarkus users are concerned, i.e. close to no difference in how users consume the extensions, obtain help, read documentation or report issues, then I'd say it's no big deal. If not, or if other extensions are not moved out of core in the same way, I may start making some noise ;)

Right, Quarkiverse will become first-class citizens in terms of usage; tooling is evolving to make sure of that (but it's work in progress). So eventually users should be able to use the Lucene backend with the same experience as the Elasticsearch one, indipendently of where this is maintained.

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-lucene

I'm closing this PR now. Thanks!

**Comment by gsmet** [comment]
As for Hibernate Search, I think it needs to be kept in Core (at least for the main parts). The main reason being the very tight integration with Hibernate ORM.

**Comment by maxandersen** [comment]
Wasn't @gunnarmorling  doing something related here?

**Comment by Sanne** [comment]
@maxandersen yes but both Gunnar and Gustavo are aware of each other's experiments. BTW Gustavo is a long time contributor to Hibernate Search as well, although he works primarily on Infinispan nowadays.

**Comment by gunnarmorling** [comment]
> Wasn't @gunnarmorling doing something related here?

Yeah, I did. As said before, I'll be happy to contribute my work; although from a quick look it seems @gustavonalle's work is very similar and a bit more complete. As it's an in PR-able here already, I suggest you go with this one, also assuming Gustavo may have more cycles to maintain this going forward.

**Comment by maxandersen** [comment]
Cool - just to be sure we got both aware and weren't creating two at the same time that could be merged :)

**Pull request closed without merging**
