### PR TITLE
TestScopeManager. tearDown() calls setup() instead of tearDown() Fixes issue #3784

### LINKED ISSUE #3784: TestScopeManager. tearDown() calls setup() instead of tearDown()
The tearDown() method of TestScopeManager calls TestScopeSetup.setup() instead of tearDown():
https://github.com/quarkusio/quarkus/blob/2a3e3c6993d0530f512457bef5cc4ee85234c36f/test-framework/common/src/main/java/io/quarkus/test/common/TestScopeManager.java#L25-L29

I did not see any bad behaviors associated with that mistake though.

### PR DESCRIPTION
**Pull request by vsevel**
I have made the change that seemed obvious. but I am not sure how to test it since I filed the issue just looking at the code, not actually experiencing a bug.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Thanks! Let's wait for CI.

**Comment by vsevel** [comment]
the fix does make the integration-tests/hibernate-orm-panache module fail with exception:
```
> ./mvnw -am clean install -pl integration-tests/hibernate-orm-panache
...
ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.287 s <<< FAILURE! - in io.quarkus.it.panache.PanacheFunctionalityTest
[ERROR] testPanacheInTest  Time elapsed: 0.021 s  <<< ERROR!
javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.arc$delegate(RequestScopedEntityManagerHolder_ClientProxy.zig:83)
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(RequestScopedEntityManagerHolder_ClientProxy.zig:191)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:77)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:292)
        at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:142)
        at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.count(JpaOperations.java:315)
        at io.quarkus.it.panache.Person.count(Person.java)
        at io.quarkus.it.panache.PanacheFunctionalityTest.testPanacheInTest(PanacheFunctionalityTest.java:45) 
```

If I revert the fix, the test succeeds again.
so may be the issue is deeper than just calling the right method?
@gsmet it would worth getting somebody to look at it

**Comment by geoand** [comment]
Maybe @FroMage has some insight?

**Comment by stuartwdouglas** [comment]
There is another bug: https://github.com/quarkusio/quarkus/blob/101c74f385688db7cdf2eaae0ddbaad7d4cff471/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L300

we tear down before the test and setup afterwards.

**Pull request merged**
