### PR TITLE
Decouple quarkus-spring-web from RESTEasy Classic

### LINKED ISSUE #19819: Allow spring-web to work on RESTEasy Reactive
### Description

The `quarkus-spring-web` module currently depends on `quarkus-resteasy`. 
With `quarkus-resteasy-reactive` likely to become the default REST extension in the future, we should port `quarkus-spring-web` to it. 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
The decoupling is achieved by using conditional
dependencies and moving RESTEasy Classic specific code
to a new (unlisted) extension.

It is now possible to use spring-web endpoints with RESTEasy Reactive as well.

This is a breaking change because users now have to include `quarkus-resteasy-jackson` or `quarkus-resteasy-reactive-jackson` on their own.

Resolves: #19819 
Superceded #21082

### CODE REVIEW

**Comment by aloubyansky** [comment]
@geoand perhaps don't rush fixing the testsuite yet. I wanted to evaluate a few ideas to avoid this kind of breaking change.

**Comment by geoand** [comment]
Sure thing

**Comment by geoand** [comment]
@aloubyansky I think I will actually push a fix for the failing tests since I really want to get this in sooner rather than later.
I can certainly point you to which tests you can use for your experiments and what needs to be done to restore the error.

**Comment by geoand** [comment]
CI is now all green

**Comment by geoand** [comment]
@aloubyansky @stuartwdouglas can we get this in for the time being? I would like to have it bake for a few days before `2.5.0.CR1` is released

**Comment by aloubyansky** [comment]
It's a great effort in general. What bothers me is that the impl of what looks like the primary dependency is now dictated by its transitive which is now required to be a direct dependency. If you are sure this is worth it - ok. But I think we should be careful about shifting the switch in this way.

**Comment by geoand** [comment]
I had initially portes Spring Web to RESTEasy Reactive - no support for for RESTEasy Classic at all.
That change was deemed to be too breaking and it was agreed that there should be support for both RESTEasy Classic and Reactive for the Spring Web extension (cc @maxandersen) and it should be up to the users to decide the underlying engine.

**Comment by aloubyansky** [comment]
Yes, I remember. I am not sure this is fixing the issue entirely. Isn't it shifting the switch to another dependency now?

**Comment by geoand** [comment]
Unless I have missed something completely, what is does is make users add `quarkus-resteasy-reactive-jackson` or `quarkus-resteasy-jackson` to their application that uses `quarkus-spring-web`. 
Those applications used to being `quarkus-resteasy-jackson` transitively, so they definitely did not work with RESTEasy Reactive anyway.

**Comment by aloubyansky** [comment]
How does it fail if there is no direct dependency on the resteasy jackson?

**Review by aloubyansky — APPROVED** [review]
I think it's acceptable in this case. Thanks @geoand

**Comment by geoand** [comment]
Thanks @aloubyansky

**Pull request merged**
