### PR TITLE
ObserverGenerator - rework the way a declaring bean instance is obtained

### LINKED ISSUE #8062: Constructor of bean with @Startup annotation is called twice
Constructor of bean with @Startup annotation is called twice, @mkouba fyi

Tried with https://quarkus.io/guides/getting-started#bootstrapping-the-project ++ FooBean

```java
package org.acme.getting.started;

import javax.enterprise.context.ApplicationScoped;
import io.quarkus.runtime.Startup;

@ApplicationScoped
@Startup
public class FooBean {
    FooBean() {
        System.out.println("Init ..");
    }
}
```

```
Init ..
Init ..
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-03-22 10:13:40,042 INFO  [io.quarkus] (main) getting-started 1.0-SNAPSHOT (powered by Quarkus 1.3.0.Final) started in 0.686s. Listening on: http://0.0.0.0:8080
2020-03-22 10:13:40,072 INFO  [io.quarkus] (main) Profile prod activated.
2020-03-22 10:13:40,072 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

### PR DESCRIPTION
**Pull request by mkouba**
- also create client proxy instances lazily
- resolves #8062

### CODE REVIEW

**Comment by gsmet** [comment]
@rsvoboda @mkouba is it something we want for 1.3?

**Comment by mkouba** [comment]
@gsmet It's a minor issue but it wouldn't hurt to backport it. However, we should wait for the review from @manovotn first.

**Review by manovotn — APPROVED** [review]

**Comment by gsmet** [comment]
OK, I will not backport it for now and we will backport it if someone complains at some point.

**Comment by rsvoboda** [comment]
> if someone complains at some point

@gsmet did you mean me :)?

I vote for backport, but don't have huge story for it. I just want to decrease the bug count in 1.3.

**Comment by gsmet** [comment]
Yeah, we would have to rewrite the whole patch and, after a discussion with @mkouba , we don't think it's a priority.

**Comment by gsmet** [comment]
Ah wrong issue: this one is different. I don't backport it because it looks minor enough and the patch is very large.

If we have someone complaining on a real use case, we will revisit.

**Pull request merged**
