### PR TITLE
Change RotationConfig default max file size in FileConfig.java

### LINKED ISSUE #24041: Documented quarkus.log.handler.file...rotation.max-file-size default value is incorrect
### Describe the bug

https://quarkus.io/guides/logging#quarkus-log-logging-log-config_quarkus.log.handler.file.-file-handlers-.rotation.max-file-size states the default size is `10`.  Based on the [MemorySize](https://quarkus.io/guides/logging#memory-size-note-anchor) definition, this would mean 10 bytes.  Actual value from observed system appears to be 640K.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by VanillaSpoon**
### Change RotationConfig default max file size in FileConfig.java
___

In FileConfig.java RotationConfig the default value for Max Size of the log file after which a rotation is executed was set incorrectly
___

```diff
-@ConfigItem(defaultValueDocumentation = "10")
+@ConfigItem(defaultValue = "10M")
```
___

Fixes #24041

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]
/lgtm

Thanks for the quick PR @VanillaSpoon :spoon:

**Comment by VanillaSpoon** [comment]
Thanks @machi1990 😊

**Comment by machi1990** [comment]
> Thanks @machi1990 blush

There are some tests failing. Can you have a look?

**Comment by VanillaSpoon** [comment]
Of course 😊 I'll get back to you @machi1990

**Comment by machi1990** [comment]
> Of course blush I'll get back to you @machi1990

Thanks, let me know if you'll need some inputs.

**Comment by gsmet** [comment]
Hmmm, so I worked on fixing the tests and AFAICS, log rotation was disabled until now or at least it was not using a size rotating appender.

I think enabling rotation by default makes sense.

@jamezp do you see any red flags with this change?

**Comment by jamezp** [comment]
@gsmet Seems fine to me. The only question I'd have is if you'd prefer to default to a `SizeRotatingFileHandler` or a `PeriodicRotatingFileHandler`. The size one has better cleanup capabilities. However, it should be noted with the `RotationConfig.fileSuffix` of a date the files will NOT be deleted. You'll end up with no files being deleted on the next rotation.

**Comment by VanillaSpoon** [comment]
Sorry for not getting this one sorted guys. Thanks for the change @gsmet

**Pull request closed without merging**
