### PR TITLE
ResteasyServerCommonProcessor - fix resource method reflective scanning

### LINKED ISSUE #10742: Jandex warning at boot time about JsonString
**Describe the bug**

At system start, the following warning is printed:

```
2020-07-15 11:54:34,465 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-32) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - javax.json.JsonString (source: com.redhat.cloud.policies.app.rest.PolicyCrudService[javax.ws.rs.core.Response validateName(@NotNull javax.json.JsonString policyName, java.util.UUID id)])
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.

```

Code looks like

```
  @POST
  @Path("/validate-name")
  public Response validateName(@NotNull JsonString policyName, @QueryParam("id") UUID id) {

```

`JsonString` is pulled into Quarkus via 

* io.quarkus:quarkus-resteasy-jsonb:1.6.0.Final
** org.jboss.resteasy:resteasy-json-binding-provider:4.5.5.Final
*** org.glassfish:jakarta.json:1.1.6

so I would expect that this is already registered in Quarkus by default. 
This warning was not printed before 1.6 

**Expected behavior**

Print no warning, as it is already registered

### PR DESCRIPTION
**Pull request by mkouba**
- do not register the ReflectiveHierarchyBuildItem twice for most
resource methods; first try the BeanArchiveIndexBuildItem and then add
methods only found in the CombinedIndexBuildItem
- resolves #10742

### CODE REVIEW

**Comment by mkouba** [comment]
CC @pilhuhn

**Comment by gsmet** [comment]
I think `JsonString` should probably be added here: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyDotNames.java#L77 .

If you can do that in a separate PR, I would be able to backport it.

**Comment by mkouba** [comment]
@gsmet hm, so this PR is valid but we don't need to register anything from `javax.json` for reflection because the API is used directly by a provider, right?

**Comment by gsmet** [comment]
Yes. At least if the `AnnotationInstance` `equals()` and `hashCode()` is usable :).

**Comment by mkouba** [comment]
I believe they are usable: https://github.com/wildfly/jandex/blob/master/src/main/java/org/jboss/jandex/AnnotationInstance.java#L324-L357

**Review by gsmet — APPROVED** [review]

**Pull request merged**
