### PR TITLE
Move Jaeger metrics to vendor instead of base

### LINKED ISSUE #3730: [Jaeger] Metrics are wrongly added to base metrics
**Describe the bug**
The Jaeger metrics are displayed as **base** metrics, but they should be **vendor** metrics as **base** metrics should only be the one listed on the [MP metrics specification](https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/required-metrics.adoc)

**Expected behavior**
Jaeger metrics are displayed under **vendor** metrics.

**Actual behavior**
Jaeger metrics are displayed under **base** metrics.

**To Reproduce**
1. Add `quarkus-smallrye-metrics` extension.
2. Add `quarkus-smallrye-opentracing` extension.
3. Navigate to the `/metrics/base` endpoint you will see Jaeger metrics.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 0.21.1

**Additional context**
This has been discuss with @jmartisk that agreed it's a bug. If I have some time this week I will works on a PR for this as it should be very simple to fix :)

### PR DESCRIPTION
**Pull request by loicmathieu**
fixes #3730

### CODE REVIEW

**Review by jmartisk — APPROVED** [review]
One might even argue that this should be in the `application` scope, because these metrics will be created based on the application code, but I believe `vendor` is the best scope here for now. In the future, MP Metrics spec could have a new scope for this kind of metrics that belong somewhere between `vendor` and `application` (but really not `base`). After all, the MP Metrics spec says
>  It is expected that a future version of this specification will also have a sub-resource for integrations with other specifications of MicroProfile.

**Comment by geoand** [comment]
I think the PR needs to be rebased onto `master` to pick up a fix for the vertx issue (I recall seeing it in other PRs as well).

**Comment by loicmathieu** [comment]
@geoand rebase done

**Comment by loicmathieu** [comment]
@geoand rebase done again as the build was still failing ...

**Comment by geoand** [comment]
@loicmathieu thanks! Let's hope everything will be OK!

**Comment by loicmathieu** [comment]
@jmartisk, @geoand this is a breaking change, can one of you add the label to the PR to be able to list it on the release note?

**Comment by geoand** [comment]
Which label @loicmathieu ? I don't see one for breaking changes

**Comment by loicmathieu** [comment]
@geoand this has been discuss on the mailing list by @gsmet to help writing the release notes ... Maybe it didn't exist

**Comment by gsmet** [comment]
I use the `noteworthy-feature` one for that.

**Comment by geoand** [comment]
Got it, I'll add it

**Review by FroMage — APPROVED** [review]

**Pull request merged**
