### PR TITLE
Remove reference to missing `red-hat-font.css.map`

### PR DESCRIPTION
**Pull request by gastaldi**
- This avoids the error displayed in the web console
- See https://github.com/quarkusio/quarkus/issues/32230#issuecomment-1492445832

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Should we not rather add the map?

**Comment by gastaldi** [comment]
Dunno, tried to find it but failed so.

**Comment by gsmet** [comment]
I'm not completely sure this choice of font is a good idea because of https://github.com/quarkusio/quarkus/issues/32230 .

Not sure exactly what's going on but my setup is very standard, no funky things.

**Comment by phillip-kruger** [comment]
Closing here. Well just remove the font

**Pull request closed without merging**
