### PR TITLE
Reset CSRF cookie to minimize a risk of failures due to its expiry

### LINKED ISSUE #36946: CSRF cookie should be refreshed on each request
### Describe the bug

ATM the CSRF filter only sets a CSRF cookie for safe methods (like `GET`) if it does not exist, but it never refreshes it.

So, for example, what can happen, since the cookie expires after 10 minutes, is the following:

- T + 0 minutes : GET, get a CSRF cookie, OK
- T + 1 minute : GET, existing CSRF cookie sent in request, no new CSRF cookie in response, OK
- T + 2 minutes : POST, existing CSRF cookie sent in request, no new CSRF cookie in response, OK
- T + 9 minute : GET, existing CSRF cookie sent in request, no new CSRF cookie in response, OK
- T + 11 minutes  : POST, expired CSRF cookie NOT sent in request, FAIL

We should refresh the CSRF cookie on every request, safe or even POST. This has been reported by several users independently.

### LINKED ISSUE #37928: CSRFFilter should have set the attribute csrf-token, but it is null after upgrade to 3.6.4
### Describe the bug

I upgraded from 3.6.3 to 3.6.4, and since then the CsrfTokenParameterProvider getToken() fails 'CSRFFilter should have set the attribute csrf-token, but it is null ' after the first load of the page, subsequent load or GET requests fails with the same error 

image

2023-12-23 19:46:30,719 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /api/table failed, error id: ace42e7c-bf2e-495b-b24f-52711085a983-2: io.quarkus.qute.TemplateException
        at io.quarkus.qute.CompletedStage.get(CompletedStage.java:65)
        at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
        at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
        at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
        at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$5(TemplateImpl.java:239)
        at io.quarkus.qute.CompletedStage.whenComplete(CompletedStage.java:285)
        at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:233)
        at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsyncNoTimeout(TemplateImpl.java:224)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniFailOnTimeout.subscribe(UniFailOnTimeout.java:36)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
        at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:19)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:290)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: CSRFFilter should have set the attribute csrf-token, but it is null
        at io.quarkus.csrf.reactive.runtime.CsrfTokenParameterProvider.getToken(CsrfTokenParameterProvider.java:42)
        at io.quarkus.csrf.reactive.runtime.CsrfTokenParameterProvider_ClientProxy.getToken(Unknown Source)
        at io.quarkus.csrf.reactive.runtime.CsrfTokenParameterProvider_ValueResolver.resolve(Unknown Source)
        at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:211)
        at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:131)
        at io.quarkus.qute.EvaluatorImpl.lambda$evaluate$0(EvaluatorImpl.java:78)
        at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:249)
        at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:77)
        at io.quarkus.qute.ResolutionContextImpl$ChildResolutionContext.evaluate(ResolutionContextImpl.java:87)
        at io.quarkus.qute.ExpressionNode.resolve(ExpressionNode.java:36)
        at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:228)
        at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:76)
        at io.quarkus.qute.LoopSectionHelper.nextElement(LoopSectionHelper.java:141)
        at io.quarkus.qute.LoopSectionHelper.lambda$resolve$0(LoopSectionHelper.java:58)
        at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:249)
        at io.quarkus.qute.LoopSectionHelper.resolve(LoopSectionHelper.java:47)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
        at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:228)
        at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:66)
        at io.quarkus.qute.Parser$1.resolve(Parser.java:1288)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
        ... 35 more

image

### Expected behavior

The CSRF token should be in context

### Actual behavior

The CSRF token is not in contett

### How to Reproduce?

clone https://github.com/yazalulloa/quarkus-csrf-signature-bug

Run quarkus project

Go to http://localhost:9898/some-page

### Output of `uname -a` or `ver`

Linux yaz-laptop 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15) OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #36946.
Fixes #37928.

@FroMage FYI, it won't guarantee the failure won't ever happen, for example, the cookie age is 10 mins and the user just sits idle for 11 min and then returns, but with a reasonably large cookie age and with this PR recycling cookies, the chance of it happening will be very low. 
If you'd like please give this PR a try with Renarde or you can try snapshots later.
Andy, @ia3andy FYI
It is not urgent to review it, thanks

### CODE REVIEW

**Review by FroMage — APPROVED** [review]
I don't have time to test this, but LGTM

**Comment by sberyozkin** [comment]
Thanks Steph @FroMage, I wonder if there has to be a property enabling this cookie refreshment by default so that users can choose not to make it last indefinitely. I think I'll just add it before merging.

**Comment by FroMage** [comment]
I don't see why anyone would want to do that. Perhaps better to wait until someone requests this with a use-case?

**Comment by sberyozkin** [comment]
Hi Steph @FroMage, I was thinking today, may be the easiest is simply set the default cookie age to a few hours which will support most cases and if a whole day has to be supported then one will just increase the age.
 I thought that this solution is not complete while also trying to make this cookie age essentially unlimited and I'm not sure I appreciate if it can have some consequences or not.

**Comment by sberyozkin** [comment]
Hey @FroMage I've decided to go ahead with this PR as after I started fixing #37928 I realized I was typing exactly the same code on the GET path as in this PR, this PR just needs a minor tweak to ensure the cookie is correctly reset when the token signature is required, so instead of resetting the token immediately in various places it will be done in the response filter, in a single place

**Comment by sberyozkin** [comment]
@FroMage I've also set a default cookie token age to 2H

**Comment by sberyozkin** [comment]
Sorry for the noise with multiple pushes, hopefully not too many people are getting them today :-)

**Comment by FroMage** [comment]
@gsmet Could we backport this one please? It's fixing a pretty serious CSRF bug (by accident) which makes it unusable in 3.6.4: https://github.com/quarkusio/quarkus/issues/37928

**Comment by FroMage** [comment]
Thanks!

**Pull request merged**
