### PR TITLE
Next stage of config fixes

### PR DESCRIPTION
**Pull request by dmlloyd**
- Make sure that build time/run time config properties are actually readable at run time
- Read run time config properties in the main method to open the door for profiles & run time config files
- Fix up extensions as needed

### CODE REVIEW

**Comment by dmlloyd** [comment]
The native failure seems to relate to things that are not otherwise tested.  I think I have an underlying cause.

**Comment by dmlloyd** [comment]
OK this is ready for review & merge

**Comment by geoand** [comment]
Is it possible that the following log messages be removed from `mvn quarkus:dev` ?

```
22:40:05,090 WARN  [io.qua.config] Unrecognized configuration key "quarkus.devMode" provided
22:40:05,090 WARN  [io.qua.config] Unrecognized configuration key "quarkus.runner.sources" provided
22:40:05,090 WARN  [io.qua.config] Unrecognized configuration key "quarkus.runner.classes" provided
22:40:05,090 WARN  [io.qua.config] Unrecognized configuration key "quarkus.runner.resources" provided
22:40:05,091 WARN  [io.qua.config] Unrecognized configuration key "quarkus.undertow.resources" provided

```

**Comment by dmlloyd** [comment]
We'd have to put in a special catcher for those.  Maybe they should have a different prefix than `quarkus` as that is reserved for configuration.  We could have `quarkus-internal` for example.

**Comment by geoand** [comment]
I think the rename you mention makes sense

**Comment by geoand** [comment]
Could we catch and ignore all properties that have a `quarkus-internal` prefix perhaps?

**Comment by dmlloyd** [comment]
We already would do so; those internal properties just have to be renamed.

**Comment by geoand** [comment]
Awesome, thanks for the info!

**Review by kenfinnigan — APPROVED** [review]
Looks reasonable, plus I trust @dmlloyd

**Pull request merged**
