### PR TITLE
Docs: Update RabbitMQ Channel Config

### PR DESCRIPTION
**Pull request by zigad**
This commit will add newly introduced and missing channel configuration:
- queue.x-queue-type
- queue.x-queue-mode
- dead-letter-queue-type
- dead-letter-queue-mode
- content-type-override
- connection-count
- queue.single-active-consumer

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks for creating a PR!

@kdubb @ozangunalp I'm not sure if you generate this documentation automatically or if we should merge this. Please have a look.

**Comment by zigad** [comment]
> Thanks for creating a PR!
> 
> @kdubb @ozangunalp I'm not sure if you generate this documentation automatically or if we should merge this. Please have a look.

I think it needs to be added manually since few of this channel configurations were introduced some time ago. For example connection-count was introduced on April 11, queue.single-active-consumer on Feb 21 and so on. But let's wait for the reviewers to check and confirm if it's OK to confirm this PR.

**Review by ozangunalp — APPROVED** [review]
@zigad Thanks for this!
Indeed rabbitmq doc was a bit outdated. We used to copy the configs doc directly from Smallrye Reactive Messaging but then moved to markdown there, I need to write a script to translate the tables to asciidoc.

**Comment by zigad** [comment]
Hey, @ozangunalp I applied wrong ' in the documentation so I opened new PR to fix this. #29302

**Pull request merged**
