### PR TITLE
Add LGTM traces test / check

### PR DESCRIPTION
**Pull request by alesj**
Poke LGTM's Tempo endpoint, to check if traces / spans were stored.
This also means that otlp traces config was used properly -- from base,
since LGTM only provides base config.

### CODE REVIEW

**Comment by alesj** [comment]
@radcortez this atm fails on purpose -- to show that OTLP base config is still not picked-up correctly

**Comment by geoand** [comment]
The test failure seems related

**Comment by alesj** [comment]
> The test failure seems related

@geoand yes, I've added this just to show that the config is still not properly applied

LgtmResource already adds all required config / properties -- base one's -- hence it should work, once OTLP failover to base works as expected

**Comment by alesj** [comment]
To reproduce locally -- on this PR's branch
* cd integration-tests/observability-lgtm
* mvn clean package -Dtest=LgtmServicesTest

**Review by geoand — APPROVED** [review]

**Pull request merged**
