### PR TITLE
Fix AppCDS generation when using podman

### LINKED ISSUE #38616: AppCDS containerized generation runs with UID 1000 which can clash with an existing user with UID 1000 on the host
### Describe the bug

In my current setup, when creating an AppCDS archive using the property `quarkus.package.create-appcds=true` and executing `mvn package -Dquarkus.container-image.build=true`, the user that is running the mvn command has a UID 1000 and GID 1000.

To create the appcds archive, the following command is run:
`podman run -v /devfolder/target:/tmp/quarkus:z --user 1000:1000 -w /tmp/quarkus/quarkus-app --rm registry.access.redhat.com/ubi8/openjdk-21-runtime:1.18 java -XX:ArchiveClassesAtExit=app-cds.jsa -Dquarkus.appcds.generate=true -jar quarkus-run.jar`

Since the /target folder has 755 permission octal and the user with UID 1000 that exists on the host does not exist in the `/etc/passwd` of the container that podman spawns, the container is unable to write the archive to the folder. The creation fails with the following error:

`[9.824s][error  ][cds] Unable to create shared archive file app-cds.jsa: (Permission denied).`

I was able to fix this by adding the argument argument `--userns=keep-id` to the `podman run` command. As you can see [here](https://docs.podman.io/en/v4.4/markdown/options/userns.container.html) this argument ensures that the current user in my host also exists in the `/etc/passwd` of the container. However, I didn't find any way to pass this command in the current AppCDS flow.

As I mentioned in #38020, albeit in a different context, I feel like the best solution here would be to allow the dev to add arguments or modify the command that gets called, since that fixes not just my issue but any other that may arise.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Darwin <computer_name> 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64 arm Darwin

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 OpenJDK Runtime Environment (build 21.0.1+12-29) OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

### Quarkus version or git rev

Quarkus 3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
We use the same trick as used in native-image
building

- Fixes: #38616

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM, but this is the third place we use this, so perhaps it's worth extracting it in a method and reusing it.

* https://github.com/quarkusio/quarkus/blob/f75790f6029cee7c7fd85c53989313d5d8fa9d8f/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/UpxCompressionBuildStep.java#L128-L136
* https://github.com/quarkusio/quarkus/blob/0af4d6a1b974f17413d7580966f197ed169f9f6d/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildLocalContainerRunner.java#L25-L37

I am also wondering whether we would need to include the WSL work around as well:

```
            if (containerRuntime.isInWindowsWSL()) {
                containerRuntimeArgs.add("--interactive");
            }
```

**Comment by geoand** [comment]
> LGTM, but this is the third place we use this, so perhaps it's worth extracting it in a method and reusing it.

Where would you put it?

**Comment by zakkak** [comment]
> > LGTM, but this is the third place we use this, so perhaps it's worth extracting it in a method and reusing it.
> 
> Where would you put it?

There is `io.quarkus.deployment.pkg.steps.LinuxIDUtil`, we could either rename and extend it or create a similar class in the same package. For the time being it looks like this is only used by build steps.

**Comment by geoand** [comment]
Seems like a reasonable follow-up task

**Pull request merged**
