### PR TITLE
Federation batch tests

### PR DESCRIPTION
**Pull request by robp94**
This adds some tests for federation batch resolvers in smallrye graphql.
https://github.com/smallrye/smallrye-graphql/pull/1908

It is based on https://github.com/quarkusio/quarkus/pull/35766

### CODE REVIEW

**Comment by geoand** [comment]
This has a conflict in the BOM, can you please rebase onto main?

Thanks

**Comment by jmartisk** [comment]
Nice!!

Could you please add a Quarkus-side equivalent of the `smallrye.graphql.federation.batchResolving.enabled` property? Probably `quarkus.smallrye-graphql.federation.batch-resolving-enabled` or so? We usually add `quarkus.*` properties into the Quarkus configuration model.

It would go into https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLConfig.java as an `Optional<Boolean>`, and then:

 in the processor (https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java): if a value was passed by the user (the Optional isn't empty) then you would simply translate that into a value of `smallrye.graphql.federation.batchResolving.enabled` by producing a `SystemPropertyBuildItem` - see for example https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java#L673 which does the same for Federation in general.

Also, this will depend on a release of SmallRye GraphQL, so I'm assuming we won't really merge this PR, but when we're happy with it, somebody will cherry-pick your commit and add it to a PR that performs the upgrade, later when the SmallRye release is out and ready.

**Comment by robp94** [comment]
@jmartisk I added the property, could you take a look?

**Comment by jmartisk** [comment]
Thanks @robp94 , I'll now have a look at both your PRs and how they work together. Very nice work!

**Comment by jmartisk** [comment]
LGTM. I've cherry picked your commits into my branch https://github.com/jmartisk/quarkus/commits/smallrye-graphql-2.5.0
which will go into Quarkus together with the upgrade to SmallRye GraphQL 2.5.0, once it's released.
So if you need to update anything, please submit against that.
Thanks a lot!!!

**Pull request closed without merging**
