### PR TITLE
(2.16) Upgrade wildfly-elytron to 1.20.3.Final

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes https://github.com/quarkusio/quarkus/issues/32211
Main isn't affected

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Thanks @jmartisk

**Comment by sberyozkin** [comment]
@gsmet Looks like the Gradle/devtools test failures are unrelated

**Comment by sberyozkin** [comment]
@jmartisk Thanks for the PR, it is ready to go I think but please wait with the merge as Guillaume would like to see the list of open PRs going to 2.16 before releasing the next 2.16.x

**Review by gsmet — CHANGES_REQUESTED** [review]
We need to have a look at what's going on with the failing tests. I'm pretty sure it's not related to this PR but we need to make sure it isn't (and fix them!).

**Comment by gsmet** [comment]
AFAICS, the errors were transient errors. Let me restart CI.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
