### PR TITLE
Add support for @ShouldNotPin/@ShouldPin on superclass

### LINKED ISSUE #41782: VirtualThreadExtension does not take super classes into account
### Describe the bug

A lot of our test classes have a single super class which contains the `@ShouldNotPin` annotation. The class VirtualThreadExtension does not take super classes into account when determing if recording is needed:
https://github.com/quarkusio/quarkus/blob/main/independent-projects/junit5-virtual-threads/src/main/java/io/quarkus/test/junit5/virtual/internal/VirtualThreadExtension.java#L65

### Expected behavior

When a super class declares the `@ShouldNotPin` annotation that the extension validates that no pinning occurs.

### Actual behavior

The `@ShouldNotPin` annotation is ignored

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdeneuter**
- Fixes https://github.com/quarkusio/quarkus/issues/41782 
Allow the usage of @ShouldPin and @ShouldNotPin on super classes

### CODE REVIEW

**Comment by bdeneuter** [comment]
Reopening the existing PR https://github.com/quarkusio/quarkus/pull/41898 to keep the history of the PR together

**Review by cescoffier — APPROVED** [review]
Thanks!

**Comment by bdeneuter** [comment]
@cescoffier one test failed on JDK17. I added `@EnabledForJreRange(min = JRE.JAVA_21)` to this test as virtual threads are not supported on JDK17

**Comment by bdeneuter** [comment]
@cescoffier Is there something else expected from me? Or will you merge this PR?

**Comment by cescoffier** [comment]
@bdeneuter nope, all good. Merging! Thanks again!

**Pull request merged**
