### PR TITLE
More robust Stream emptiness check for ServerJaxbMessageBodyReader

### LINKED ISSUE #43186: quarkus-rest-jaxb: Request body is null
### Describe the bug

When making a http request with xml as a request body, The deserialized request body is null. 
The project uses `quarkus-rest-jaxb` for xml support. The endpoint definition is similar to this:

```java
public class MyResource {

    @POST
    @Consumes({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
    @Path("my-path")
    public Response myEndpoint(MyRequest request) {
        // request is null
        return ...;
    }
}
```

### Expected behavior

When sending an xml body to the endpoint, the request body is deserialized and passed to the `myEndpoint` method.

### Actual behavior

The `request` parameter of `myEndpoint` is null.

### How to Reproduce?

Finding exact steps to reproduce the issue might prove difficult since a race condition is likely involved. The issue occurred when testing the application on a testing environment whereas everything worked as expected when running the application locally.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java 21

### Quarkus version or git rev

3.13.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I believe this issue is caused by the [ServerJaxbMessageBodyReader](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-jaxb/runtime/src/main/java/io/quarkus/resteasy/reactive/jaxb/runtime/serialisers/ServerJaxbMessageBodyReader.java) class:

```java
...

    private Object doReadFrom(Class<Object> type, Type genericType, InputStream entityStream) throws IOException {
        if (isInputStreamEmpty(entityStream)) {
            return null;
        }
    
        return unmarshal(entityStream, type);
    }
    
    private boolean isInputStreamEmpty(InputStream entityStream) throws IOException {
        return StreamUtil.isEmpty(entityStream) || entityStream.available() == 0;
    }
}
```

`entityStream.available()` is called to check whether the stream is empty. The documentation for this method states:

> Returns an estimate of the number of bytes that can be read (or skipped over) from this input stream without blocking, which may be 0, or 0 when end of stream is detected.

This might lead to a stream wrongfully being classified as empty. No bytes being available to be read _without blocking_ does not necessarily imply that there are no bytes to be read _at all_.

I have been able to test this theory by attaching a debugger to the application and creating a breakpoint on the `return null;` line. When I reevaluate `isInputStreamEmpty(entityStream)` once the
breakpoint has been reached the result is `false`. Moreover, `entityStream.available()` is now larger than 0.

This issue can likely be avoided by adjusting the `isInputStreamEmpty` method and no longer using `entityStream.available()` to check whether the stream is empty.

A possible workaround for this issue is to add a request filter like this to the project:

```java
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerRequestFilter;
import jakarta.ws.rs.ext.Provider;

import java.io.IOException;
import java.io.InputStream;
import java.io.PushbackInputStream;

@Provider
public class EntityPeekingFilter implements ContainerRequestFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        if (requestContext.hasEntity()) {
            InputStream entityStream = requestContext.getEntityStream();
            PushbackInputStream pushbackStream = new PushbackInputStream(entityStream);
            int firstByte = pushbackStream.read();
            pushbackStream.unread(firstByte);
            requestContext.setEntityStream(pushbackStream);
        }
    }
}
```

This request filter reads one byte from the stream and then resets the streams start. This ensures that there is always at least one byte available for reading in a non-blocking manner.

### PR DESCRIPTION
**Pull request by qa-andreas-stangl**
Previously, InputStream.available() was used to check the stream for emptiness. This can result in streams being mistakenly qualified as empty since available() only provides an estimate of how many bytes can be read without blocking.

Fixes https://github.com/quarkusio/quarkus/issues/43186

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this, seems reasonable to me!

@Sgitario WDYT?

Also, would it be possible to add a test that reproduces the scenario you encountered in https://github.com/quarkusio/quarkus/issues/43186?

**Comment by qa-andreas-stangl** [comment]
Adding a test that reproduces the exact issue encountered here might prove very difficult. The bug appearing depends on the `entityStream` having no bytes available to be read without blocking (yet) when `isStreamEmpty` is called. It is not entirely clear to me what causes this to happen with our project and not others. As I discovered when attaching a debugger, timing is relevant for the bug to occur. It might prove impossible to write a test that can create the necessary conditions reliably.

**Comment by geoand** [comment]
Understood, thanks

**Comment by Sgitario** [comment]
> Thanks for this, seems reasonable to me!
> 
> @Sgitario WDYT?
> 

It looks good to me as well. Thanks for taking care of this!

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
@geoand should we backport this one?

**Comment by geoand** [comment]
Probably, but I would prefer to get some testing from 3.16 first

**Comment by gsmet** [comment]
Yeah, that's what I was thinking too. Will mark it for backport once 3.15.0 is shipped.

**Comment by geoand** [comment]
🙏🏽

**Pull request merged**
