### PR TITLE
List servlet mapping in 404

### LINKED ISSUE #3852: 404 page does not list swagger-ui
call an 404 resource with openapi extension in, you won't get swagger-ui listed.

### PR DESCRIPTION
**Pull request by Dufgui**
fix #3852

### CODE REVIEW

**Comment by Dufgui** [comment]
wait  https://github.com/quarkusio/quarkus/pull/3854 and https://github.com/quarkusio/quarkus/pull/3901

before merging it.

**Comment by Dufgui** [comment]
in fact, it can be merged before the #3901
So it's ready for review

**Comment by Dufgui** [comment]
i push an edit of commit message because test fail on something which is not related to my dev:
Caused by: java.lang.NullPointerException
	at org.jboss.jandex.Indexer.decodeClassEntry(Indexer.java:1298)

**Comment by Dufgui** [comment]
comté? tome ? camembert ? Roquefort ? Brillat Savarin? ... @FroMage (try to attract the reviewer DONE ;o) )

**Comment by FroMage** [comment]
Be careful what you wish for ;)

Can I have a screenshot of the page with servlets?

**Comment by Dufgui** [comment]
image

**Comment by Dufgui** [comment]
Are you like beetlejuice : @FroMage @FroMage @FroMage

**Comment by gsmet** [comment]
What would be better is having a simple black title on grey background for "Servlet mappings" (similar to the intro of the REST resources) and then have the mappings in a white background as for the rest resources.

The main title should also be changed from "REST interface overview" to "Resources overview" that is more generic.

**Comment by Dufgui** [comment]
"Resources overview" or "Resources available" ?

**Comment by Dufgui** [comment]
image

something like this ?

**Comment by Dufgui** [comment]
@gsmet @FroMage

**Comment by gsmet** [comment]
I would keep `Resources overview`.

Maybe let's replace the intro of the resources with a title too and unify everything.

We would have:
```
REST resources

<list>

Servlet mappings (with a s at mappings and no uppercase)

<list>
```

(and same for the static resources that are in another PR, maybe it would make sense to do all this in the same PR?)

**Comment by Dufgui** [comment]
yes i will rebase it.
and push it here

**Comment by Dufgui** [comment]
image

cherry pick done.

**Comment by dmlloyd** [comment]
@FroMage, @gsmet is this ready now?

**Comment by FroMage** [comment]
I think it's good enough, we can always improve it later. That's already great progress.

**Review by FroMage — APPROVED** [review]

**Pull request merged**
