### PR TITLE
Add missing module to CI native runs

### LINKED ISSUE #4910: Azure pipelines cover only subset of modules (43/60) for native runs
Azure pipelines are missing several modules for native runs

There are 60 modules under integration-tests and 43 of them are executed in native mode

```
find integration-tests -mindepth 1 -maxdepth 1 -type d | wc -l
      60
yq r azure-pipelines.yml stages[3].jobs.*.parameters.modules | wc -l
      43

for i in `find integration-tests -mindepth 1 -maxdepth 1 -type d | xargs basename `; do
     MATCHING_TEMPLATE=`yq r azure-pipelines.yml stages[3].jobs.*.parameters.modules | sed "s/- //g" | sed "s/ //g " | grep "^$i$"`
     if [ "$i" != "$MATCHING_TEMPLATE" ]; then
         echo "$i"
     fi
done

elytron-security-jdbc
amazon-lambda-http-it
infinispan-embedded
maven
elytron-undertow
kotlin
kogito-maven
class-transformer
common-jpa-entities
scala
reactive-mysql-client
elytron-resteasy
vault-agroal
kubernetes
narayana-jta
shared-library
vault
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #4910

### CODE REVIEW

**Comment by geoand** [comment]
The infinispan embedded tests were also being added in #4887 but that also failed in CI

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
I would rather open an issue for Infinispan and not break master.

**Comment by Sanne** [comment]
> I would rather open an issue for Infinispan and not break master.

sure, Stuard didn't enable infinispan-embedded in this PR. I'll open the issue for that one and assign the Infinispan team, but that's orthogonal to this one.

**Review by Sanne — APPROVED** [review]

**Comment by geoand** [comment]
> > I would rather open an issue for Infinispan and not break master.
> 
> sure, Stuard didn't enable infinispan-embedded in this PR. I'll open the issue for that one and assign the Infinispan team, but that's orthogonal to this one.

TBF, the initial version of the PR did contain it and it was subsequently removed :)

**Pull request merged**
