### PR TITLE
Scheduled javadoc - clarify config property expressions

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by mkouba** [comment]
CC @renegrob

**Comment by mkouba** [comment]
@machi1990 pls review ;-)

**Review by machi1990 — APPROVED** [review]
lgtm

There was a report on the `disabled` / `off` not working as we'd expect for quartz. That's a separate issue though.

**Comment by machi1990** [comment]
> @machi1990 pls review ;-)

Sorry for the delay. I was away from the keyboard yesterday.

**Comment by mkouba** [comment]
> > @machi1990 pls review ;-)
> 
> Sorry for the delay. I was away from the keyboard yesterday.

No problem ;-)

**Pull request merged**
