### PR TITLE
Update SmallRye Health to 4.0.4

### LINKED ISSUE #32800: Duplicated checks in health check response
### Describe the bug

When quarkus app is deployed on environment with multiple instances checks in health check response are repeated.
There are 3 instances and one instance returns expected behavior, second instance returns doubled response and third instance returns tripled instance.

### Expected behavior

```
{
	"status": "UP",
	"checks": [
		{
			"name": "Kafka consumers health check",
			"status": "UP"
		},
		{
			"name": "Database connections health check",
			"status": "UP",
			"data": {
				"<default>": "UP"
			}
		}
	]
}
```

### Actual behavior

```
{
	"status": "UP",
	"checks": [
		{
			"name": "Kafka consumers health check",
			"status": "UP"
		},
		{
			"name": "Kafka consumers health check",
			"status": "UP"
		},
		{
			"name": "Kafka consumers health check",
			"status": "UP"
		},
		{
			"name": "Database connections health check",
			"status": "UP",
			"data": {
				"<default>": "UP"
			}
		},
		{
			"name": "Database connections health check",
			"status": "UP",
			"data": {
				"<default>": "UP"
			}
		},
		{
			"name": "Database connections health check",
			"status": "UP",
			"data": {
				"<default>": "UP"
			}
		}
	]
}
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xstefank**
https://github.com/smallrye/smallrye-health/releases/tag/4.0.3

- Fixes: https://github.com/quarkusio/quarkus/issues/32800

### CODE REVIEW

**Comment by xstefank** [comment]
cc/ @geoand

**Review by geoand — APPROVED** [review]
Thanks for the quick release!

**Comment by geoand** [comment]
The test failures seem related to the change

**Comment by xstefank** [comment]
I'll take a look, we have an integration test before we release that should have caught any potential test failures.

**Comment by xstefank** [comment]
got a fix, I'll release a follow-up.

**Pull request merged**
