### PR TITLE
Drools extension documentation

### PR DESCRIPTION
**Pull request by mariofusco**
Since Drools 10.0.0 is finally out, it's also time to merge the documentation for its Quarkus extension.

@geoand @cescoffier Please review.

### CODE REVIEW

**Comment by geoand** [comment]
🎉

**Review by geoand — COMMENTED** [review]
I added a couple of small comments.

Do you plan to add a [quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/development) as well?

**Comment by mariofusco** [comment]
> I added a couple of small comments.

Approved, thanks.

> Do you plan to add a [quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/development) as well?

I wasn't thinking to this, but yes, it's a good idea, I will.

**Comment by geoand** [comment]
🙏🏽 

When done, please squash the commits

**Comment by mariofusco** [comment]
> 🙏🏽
> 
> When done, please squash the commits

Done.

**Review by geoand — APPROVED** [review]

**Pull request merged**
