### PR TITLE
Qute "if" section - support multiple conditions

### PR DESCRIPTION
**Pull request by mkouba**
This PR makes it possible to use more complex expressions in `{#if}` sections:
`{#if !item.active || (item.sold && item.price == 100)}`
`{#if item.age > 10 && item.price > 500}`
`{#if (item.age > 10 || item.price > 500) && user.loggedIn}`

We can switch to a common reusable EL (once we have it ;-) but this should be powerful enough in the meantime.

TODO: improve validation of parameters.

### CODE REVIEW

**Comment by gsmet** [comment]
I won't have the time to review that one before 1.2. @gastaldi could you give it a shot?

**Comment by gastaldi** [comment]
Sure, I'll give it a try tomorrow morning first thing

**Comment by gastaldi** [comment]
@mkouba doesn't seem to work with me. I have a template like: 
```
{#if (name.equals("George")) || name.startsWith("C")}
Hello {name}!
{#else}
OI {name}!
{/if}
```
Having a GreetingResource like: 

```java
@Path("/hello")
public class GreetingResource {

    @Inject
    Template hello; 

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public TemplateInstance hello(@QueryParam("name") String name) {
        return hello.data("name",name);
    }
}
```
And I did a http://localhost:8080/hello?name=George but I get the `OI George!`  output

**Comment by gastaldi** [comment]
Ah my fault for not RTFM:
```
{#if name is "George" || name startsWith "C"}
Hello {name}!
{#else}
OI {name}!
{/if}
```

It seems that startsWith is not supported yet

**Comment by mkouba** [comment]
@gastaldi `equals` and `startsWith` methods are not automatically available. By default, only public properties work out of the box (public getter or field). You can use `@TemplateData(target=String.class)` or `@TemplateExtension`.

**Review by gastaldi — APPROVED** [review]
Works like a charm. Good job!

**Pull request merged**
