### PR TITLE
MP FT TCK integration

### PR DESCRIPTION
**Pull request by manovotn**
A draft of what Ken and I did so far; requires to run against SNAPSHOT of MP FT and SR FT.
We have some exclusions but otherwise I am getting following output when executed against SNAPSHOT versions: `[INFO] Tests run: 340, Failures: 0, Errors: 0, Skipped: 0`

**Before turning this into a PR we need a new version of MP FT (with TCK fixes) and of SR FT released.**

This is the last missing bit for #348

### CODE REVIEW

**Comment by kenfinnigan** [comment]
woohoo!

**Comment by manovotn** [comment]
@kenfinnigan if you find we need any further changes, feel free to push them directly in this draft so we have a commonplace for it.

**Comment by manovotn** [comment]
Bumped MP/SR FT versions and rebased onto current master.
Let's see what CI has to say.

**Comment by gsmet** [comment]
Sorry, I had to cancel the build to get some CI resources for the PRs that need to go into 0.26.0.

Can you re-run the build tomorrow?

Thanks!

**Comment by manovotn** [comment]
I am looking into the test failure.
Apparently, our beloved TestNG allows certain parameters for before/after methods. Obviously we do not have them at hand for our manual invocations. Although looking at failing test, those are only used for logging, so there is probably no harm in leaving those methods out. Commit incoming shortly...

**Comment by manovotn** [comment]
Alright, so as a bonus it turns out opentracing TCKs use `protected` before/after method, so that we also need to set them accessible.
But even with that, I am then getting following failure:
```
[ERROR] arquillianBeforeTest(org.eclipse.microprofile.opentracing.tck.OpenTracingSkipPatternTests)  Time elapsed: 3.849 s  <<< FAILURE!
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.arquillian.QuarkusBeforeAfterLifecycle.invokeCallbacks(QuarkusBeforeAfterLifecycle.java:77)
	at io.quarkus.arquillian.QuarkusBeforeAfterLifecycle.on(QuarkusBeforeAfterLifecycle.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.before(EventTestRunnerAdaptor.java:115)
	at org.jboss.arquillian.testng.Arquillian.arquillianBeforeTest(Arquillian.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.arquillian.QuarkusTestNgCallbacks.invokeTestNgBeforeMethods(QuarkusTestNgCallbacks.java:79)
	... 79 more
Caused by: java.lang.RuntimeException: java.net.MalformedURLException: no protocol: rest/tracer/clearTracer
	at org.eclipse.microprofile.opentracing.tck.application.ApplicationUtils.getWebServiceURL(ApplicationUtils.java:57)
	at org.eclipse.microprofile.opentracing.tck.OpenTracingBaseTests.getWebServiceURL(OpenTracingBaseTests.java:132)
	at org.eclipse.microprofile.opentracing.tck.OpenTracingBaseTests.getWebServiceURL(OpenTracingBaseTests.java:120)
	at org.eclipse.microprofile.opentracing.tck.OpenTracingBaseTests.clearTracer(OpenTracingBaseTests.java:194)
	at org.eclipse.microprofile.opentracing.tck.OpenTracingBaseTests.beforeEachTest(OpenTracingBaseTests.java:109)
	... 84 more
Caused by: java.net.MalformedURLException: no protocol: rest/tracer/clearTracer
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:497)
	at org.eclipse.microprofile.opentracing.tck.application.ApplicationUtils.getWebServiceURL(ApplicationUtils.java:52)
	... 88 more
```

This didn't show itself before because we simply never invoked before/after for testng.
@kenfinnigan do you know someone who would know more about opentracing?

**Comment by kenfinnigan** [comment]
@pavolloffay is Mr OpenTracing

**Comment by manovotn** [comment]
Great, @pavolloffay could you please take a look at why exactly does this fail?

**Comment by jmartisk** [comment]
I will have a look, I integrated the OpenTracing TCKs into Quarkus

**Comment by manovotn** [comment]
> I will have a look, I integrated the OpenTracing TCKs into Quarkus

I am trying to look what's going on now, I think this is happening because of ` @ArquillianResource URL deploymentURL` which in our case is `null` hence the before method fails to create a URL.

**Comment by jmartisk** [comment]
Something like this should fix it https://github.com/jmartisk/quarkus/commit/830a53a72bb57745cbe993ac0e9db1106992c267

**Comment by manovotn** [comment]
@jmartisk wow you're fast, thanks :)
Cherry picked onto this branch

**Comment by pavolloffay** [comment]
I was OOO last days. Ping me if there are still issues. If there is something we can improve in the OT TCK please create an issue in the https://github.com/eclipse/microprofile-opentracing

**Review by kenfinnigan — APPROVED** [review]

**Pull request closed without merging**
