### PR TITLE
Don't require quarkus.datasource.db-kind

### PR DESCRIPTION
**Pull request by stuartwdouglas**
If only one driver is installed then it
should not be nessesary to specify the DB
type.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@geoand @gsmet I am not sure if there is a reason why this is currently implemented the way it is? It seems really odd to me that this property becomes optional if you have the kube service binding extension installed, but not otherwise?

**Comment by geoand** [comment]
Only because I wanted to reduce the blast radius of the change.

There is no real technical reason I didn't do what you just did.

I'm +1 as long as Guillaume is too

**Comment by geoand** [comment]
The `quarkus-integration-test-vault-agroal` doesn't like the change:

```
2021-01-29T05:04:23.4473341Z [ERROR] io.quarkus.vault.AgroalVaultITCase  Time elapsed: 22.651 s  <<< ERROR!
2021-01-29T05:04:23.4474817Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
...
2021-01-29T05:04:23.4838754Z Caused by: io.quarkus.runtime.configuration.ConfigurationException: quarkus.datasource.jdbc.url has not been defined
```

**Comment by stuartwdouglas** [comment]
Yea, looks like there are a few tests that include drivers but don't define datasources, and this makes them fail.

With the containers based 'auto start, zero config' approach I proposed on the mailing list this would actually result in a TestContainers DB being started in dev and test mode.

**Comment by geoand** [comment]
👍🏼

**Comment by gsmet** [comment]
Yes there is a reason why it was done this way.

I didn't want to break applications if you add a new driver (typically for testing).

**Comment by stuartwdouglas** [comment]
If you have a test scoped driver you need different %test config anyway, so it does not really break the existing app, its just that the test config needs an extra line of config.

**Comment by stuartwdouglas** [comment]
Closing, as I want to address this as part of my automatic containers proposal.

**Pull request closed without merging**
