### PR TITLE
HTTP Authorization Refactor

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This is a subset of https://github.com/quarkusio/quarkus/pull/4956 that does not need the new quarkus-http release. If the other artifact is not published in time then ideally this one will go in as it fixes some problems (such as blocking ops on the IO thread)

### CODE REVIEW

**Comment by sberyozkin** [comment]
@stuartwdouglas It all looks good, I'd only consider making it obvious that context is meant for the blocking calls (or even move it out of the signature if it is easy enough to do), as per [this comment](https://github.com/quarkusio/quarkus/pull/4956#discussion_r340012037), unless you plan to add more operations to `AuthorizationRequestContext`, for the users be able to do more than just the blocking checks on this context instance.
What do you think ?

**Comment by stuartwdouglas** [comment]
Eventually it may contain more context info, so I would rather leave it to future proof.

**Comment by sberyozkin** [comment]
@stuartwdouglas OK, that makes sense. So may be it is worth pushing the doc about the blocking calls from the class itself to the method which does the blocking call ?

**Review by sberyozkin — APPROVED** [review]
LGTM

**Review by pedroigor — APPROVED** [review]

**Comment by gsmet** [comment]
Quarkus HTTP Beta3 has hit Central so I'm closing this one.

**Pull request closed without merging**
