### PR TITLE
OpenTelemetry: Respect provided TracingPolicy in VertxTracer implementations

### PR DESCRIPTION
**Pull request by tmihalac**
Fixed https://github.com/quarkusio/quarkus/issues/25417

Added TracingPolicy.IGNORE consideration to quarkus 

Signed-off-by: Theodor Mihalache <tmihalac@redhat.com>

### CODE REVIEW

**Review by radcortez — CHANGES_REQUESTED** [review]
@tmihalac Thank you for the PR.

Can we also add a test, please?

**Comment by tmihalac** [comment]
> @tmihalac Thank you for the PR.
> 
> Can we also add a test, please?

I am not familiar with Vert.X, can you point me to the correct module where I should put the test in and where I can see other tests

**Comment by radcortez** [comment]
Check here:
- https://vertx.io/docs/vertx-opentracing/java/
- https://github.com/quarkusio/quarkus/blob/6e095f49ee7660de87ffc9b7c6e64429027df7ae/extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/VertxClientOpenTelemetryTest.java#L58-L62

You should be able to change the `TracingPolicy` in the Vert.x Client and do not generate Span (include both scenarios, enable / disabled)

For the EventBus:
- https://github.com/quarkusio/quarkus/blob/a82137d3908c00addde3640e98f27a59bca96856/integration-tests/opentelemetry-vertx/src/main/java/io/quarkus/it/opentelemetry/vertx/HelloRouter.java#L39

For the HTTP Server, we probably need to expose the configuration because Quarkus manage the server. Have a look at the `vertx-http` extension.

Thanks!

**Comment by tmihalac** [comment]
> Check here:
> 
> * https://vertx.io/docs/vertx-opentracing/java/
> * https://github.com/quarkusio/quarkus/blob/6e095f49ee7660de87ffc9b7c6e64429027df7ae/extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/VertxClientOpenTelemetryTest.java#L58-L62
> 
> You should be able to change the `TracingPolicy` in the Vert.x Client and do not generate Span (include both scenarios, enable / disabled)
> 
> For the EventBus:
> 
> * https://github.com/quarkusio/quarkus/blob/a82137d3908c00addde3640e98f27a59bca96856/integration-tests/opentelemetry-vertx/src/main/java/io/quarkus/it/opentelemetry/vertx/HelloRouter.java#L39
> 
> For the HTTP Server, we probably need to expose the configuration because Quarkus manage the server. Have a look at the `vertx-http` extension.
> 
> Thanks!

```WebClient.create(vertx, options)``` is not fixed, only when I set the HTTP Server TracingPolicy to `IGNORE` it is actually ignored.

In addition ```eventBus.publish("bus", "hello to bus", options)``` is also not fixed since in vertx-core-4.3.2 in class `HandlerRegistration` line 130 the TracingPolicy is hard coded to `TracingPolicy.PROPAGATE`

**Comment by gsmet** [comment]
As for the event bus, when you're sending the option to the client call, I think you actually want to avoid tracing in the client call itself (the server is not in your hands really).
AFAICS, the tracing policy is considered properly here: https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/eventbus/impl/OutboundDeliveryContext.java#L99 .

As for `WebClient.create(vertx, options)`, same question: are you talking about the client calls or the server calls? Removing tracing at the client level won't affect the server itself, for which the config is at the server level.

**Comment by tmihalac** [comment]
> As for the event bus, when you're sending the option to the client call, I think you actually want to avoid tracing in the client call itself (the server is not in your hands really). AFAICS, the tracing policy is considered properly here: https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/eventbus/impl/OutboundDeliveryContext.java#L99 .
> 
> As for `WebClient.create(vertx, options)`, same question: are you talking about the client calls or the server calls? Removing tracing at the client level won't affect the server itself, for which the config is at the server level.
> 
> At least that's my understanding of it but I can't say I'm well versed in all this :).

You can have a look in the issue according to my understanding the requirement is for the tracing to be ignore in client side as well

**Comment by radcortez** [comment]
> You can have a look in the issue, according to my understanding the requirement is for the tracing to be ignore in client side as well
> 
> Can you please comment on it @radcortez ?

Yes. Setting the tracing policy at the client to ignore cannot generate client spans, but the policy is not propagated to the server. 

> For the HTTP Server, we probably need to expose the configuration because Quarkus manage the server. Have a look at the vertx-http extension.

This is why I've written the previous quote. To control the policy on the server side we would need to expose a configuration. This is available in Vert.x `HttpServerOptions`. Because this is a specific Vert.x Http configuration (and not directly related with OpenTelemetry, I think it should be fine if the configuration stays on the vertx-http extension.

**Comment by tmihalac** [comment]
> Yes. Setting the tracing policy at the client to ignore cannot generate client spans, but the policy is not propagated to the server.
> 

@radcortez Any suggestion where in the client code do I need to add such an enforcement?

**Comment by radcortez** [comment]
> > Yes. Setting the tracing policy at the client to ignore cannot generate client spans, but the policy is not propagated to the server.
> 
> @radcortez Any suggestion where in the client code do I need to add such an enforcement?

Clients need to set the TracingPolicy when creating the Vert.x Client. This is on the consuming side, so we have nothing to do there. We need to ensure that no traces are going on on the `HttpInstrumenterVertxTracer`. Thanks!

**Comment by tmihalac** [comment]
> Clients need to set the TracingPolicy when creating the Vert.x Client. This is on the consuming side, so we have nothing to do there. We need to ensure that no traces are going on on the `HttpInstrumenterVertxTracer`. Thanks!

Do I need also to set the server Vert.x `HttpServerOptions` to `TracingPolicy.Ignore` when testing the client with `TracingPolicy.Ignore` ? otherwise it looks like a SpanOperations are being created?

**Comment by radcortez** [comment]
> @radcortez Do I need also to set the server Vert.x `HttpServerOptions` to `TracingPolicy.Ignore` when testing the client with `TracingPolicy.Ignore` ? otherwise it looks like a SpanOperations are being created?

No, because one thing is Client Tracing and another thing is Server Tracing. If you have the Client set to Ignore, then you still get traces on the server side and that is fine. Only when you also set Ignore on the Server side, then you won't have traces.

**Comment by brunobat** [comment]
@tmihalac are you still planning to work on this?

**Comment by tmihalac** [comment]
No

**Pull request closed without merging**
