### PR TITLE
WebSockets Next: honor the quarkus.http.root-path correctly

### PR DESCRIPTION
**Pull request by mkouba**
- i.e. do not use HttpRootPathBuildItem together with RouteBuildItem.builder()

### CODE REVIEW

**Comment by geoand** [comment]
So we need to figure out if we want this or not :)

**Comment by mkouba** [comment]
> So we need to figure out if we want this or not :)

Well, the opening handshake goes over HTTP so I'd say we want this :shrug:

**Comment by geoand** [comment]
Clement and I were both wondering on the Zulip thread... I am still unconvinced

**Comment by cescoffier** [comment]
I agree with Martin because of the "upgrade" HTTP request. 

It could be debatable when you would use a direct, without-upgrade approach, but the initial HTTP request should honor the root path.

Also, I think it's more consistent from a user POV.

**Review by cescoffier — APPROVED** [review]
The documentation should mention this.

**Comment by geoand** [comment]
> The documentation should mention this.

Definitely

**Comment by mkouba** [comment]
> The documentation should mention this.

Done.

**Pull request merged**
