### PR TITLE
Verify project build tool before creating Gradle model

### LINKED ISSUE #13021: Quarkus should verify that build.gradle or pom.xml exists rather than defaulting to gradle
**Description**
[`isMavenProject` defaults to a Gradle project](https://github.com/quarkusio/quarkus/blob/master/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/utils/BuildToolHelper.java#L49-L61) if it can't find Maven or Gradle build files. This might make sense in some cases, but can cause issues if not logging what it's doing. For example, in multi module IntelliJ projects (not gradle/maven modules, but IntelliJ modules), the `working directory` will commonly be a different project than the one you are currently working in. I encountered this bug [when my main project was a nodejs project, while the project I was testing was Quarkus](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Gradle.20error.20in.20Maven.20project). The solution was to change the working directory, but it took debugging down into the quarkus library to figure that out. 

**Implementation ideas**

Simply log what is occurring to make debugging the issue easier, or perform a check [here](https://github.com/quarkusio/quarkus/blob/master/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/utils/BuildToolHelper.java#L98-L101) and [here](https://github.com/quarkusio/quarkus/blob/master/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/utils/BuildToolHelper.java#L108-L111) that the gradle file actually exists instead of assuming that since Maven wasn't there it's Gradle.

### PR DESCRIPTION
**Pull request by glefloch**
Make sure we are in a gradle project before generating the model. 

close #13021

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM but I think it would be nice to throw an exception if neither is found

**Comment by glefloch** [comment]
@gastaldi yes, I added a throw if no build file is found.

**Comment by aloubyansky** [comment]
Throwing an exception from `isMavenProject(path)` if the dir does not contain any project seems counter-intuitive to me. I.e. it is definitely not a Maven project dir which is what the name of the method suggest it is checking.

Here is what I'd suggest.
1) Take the code of the current `isMavenProject(Path)` and move to a method `BuildTool detectBuildTool(Path dir)`. If it find a `pom.xml` it returns BuildTool.MAVEN, if it find a Gradle script it returns BuildTool.GRADLE, if it finds nothing return null.
2) Make `isMavenProject(Path path)` call `findBuildTool(Path path)`. If it does not return BuildTool.MAVEN return false, otherwise true
3) The same for `isGradleProject(Path path)`

WDYT?

**Comment by glefloch** [comment]
@aloubyansky, Yes I updated the code, and added a `log` if no build tool is find.

**Review by aloubyansky — APPROVED** [review]
Thanks @glefloch

**Pull request merged**
