### PR TITLE
Restore port sysprop values in VertxHttpRecorder

### LINKED ISSUE #12087: quarkus.http[s].test-port system properties are lost on app restart triggered by @TestProfile
**Describe the bug**
If you set e.g. `<quarkus.http.test-port>0</quarkus.http.test-port>` in `systemPropertyVariables` of `maven-surefire-plugin` and you have at least one `@QuarkusTest` *without* `@TestProfile` and one `@QuarkusTest` *with* `@TestProfile` then the port is not picked up by that second test (if run after the test without `@TestProfile`).

The reason for this lies in [VertxHttpRecorder](https://github.com/quarkusio/quarkus/blob/1.7.2.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java):
It is (re-?)setting the port properties here: https://github.com/quarkusio/quarkus/blob/1.7.2.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L898-L902
and it is *clearing* the port properties here:
https://github.com/quarkusio/quarkus/blob/1.7.2.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L916-L930

(I saw in the debugger that the recorder is setting the actual effective port, e.g. 62138)

That clearing occurs on shutdown which is triggered by the test extension because it finds a `@TestProfile`.
The app instance that is then booted up after that cannot (obviously) see the original port properties anymore, falling back to the default (or I guess to yaml/properties in case port properties are set there).

**Expected behavior**
Port system properties must survive restarts triggered by `@TestProfile`.

**Actual behavior**
Port system properties are lost on first restart by a `@TestProfile`.

**To Reproduce**
1. clone https://github.com/famod/quarkus-quickstarts
2. switch to issue-12087-port-sysprop-lost
    diff: https://github.com/quarkusio/quarkus-quickstarts/compare/master..famod:issue-12087-port-sysprop-lost
3. cd getting-started-testing
4. mvn clean test will show that random port is only used for the first test (second one uses profile):
    ```
    [INFO] Running org.acme.getting.started.testing.GreetingResourceTest
    2020-09-14 22:30:53,552 INFO  [io.quarkus] (main) Quarkus 1.7.3.Final on JVM started in 1.743s. Listening on: http://0.0.0.0:51063
    2020-09-14 22:30:53,555 INFO  [io.quarkus] (main) Profile test activated.
    2020-09-14 22:30:53,555 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
    [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.031 s - in org.acme.getting.started.testing.GreetingResourceTest
    [INFO] Running org.acme.getting.started.testing.GreetingServiceTest
    2020-09-14 22:30:54,585 INFO  [io.quarkus] (main) Quarkus stopped in 0.021s
    2020-09-14 22:30:56,357 INFO  [io.quarkus] (main) Quarkus 1.7.3.Final on JVM started in 1.585s. Listening on: http://0.0.0.0:8081
    2020-09-14 22:30:56,357 INFO  [io.quarkus] (main) Profile test activated.
    2020-09-14 22:30:56,357 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
    [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.017 s - in org.acme.getting.started.testing.GreetingServiceTest
    [INFO] Running org.acme.getting.started.testing.StaticContentTest
    2020-09-14 22:30:56,599 INFO  [io.quarkus] (main) Quarkus stopped in 0.015s
    2020-09-14 22:30:58,120 INFO  [io.quarkus] (main) Quarkus 1.7.3.Final on JVM started in 1.389s. Listening on: http://0.0.0.0:8081
    2020-09-14 22:30:58,120 INFO  [io.quarkus] (main) Profile test activated.
    2020-09-14 22:30:58,120 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
    ```

**Configuration**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `MINGW64_NT-10.0-18363 XXX 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys`
 - Output of `java -version`: `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)`
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: `1.7.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by famod**
Fixes #12087

Not the prettiest solution. I think those `clear*Property ` flags and the map could somehow be merged into one thing but my creativity is depleted for today.

Tomorrow I can try to find a test to cover this change.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

It would be great to have a test for this

**Comment by geoand** [comment]
Also, it does seem a little weird that we need to change the recorder. Couldn't be done in the test alone?

**Comment by famod** [comment]
> Also, it does seem a little weird that we need to change the recorder. Couldn't be done in the test alone?

Depends on your POV. In my POV the recorder is manipulating system properties so it knows best what to restore.
Doing it in the test extension would mean (IMO) that the extension has some kind of "whitebox knowledge" about everything that is happening internally in the non-test code. For me this doesn't feel like the best approach.

**Comment by famod** [comment]
> It would be great to have a test for this

I'll have a look later today or tomorrow.

**Comment by famod** [comment]
@geoand What kind of test do you envision?

A "real" test setup would involve at least two test classes that are run in a specific order and for both tests we would need to set the port number system property to 0.
I don't think this will be possible with the current test framework...unless I introduce a specific surefire execution, e.g. in `integration-tests/vertx-http`.
WDYT?

**Comment by geoand** [comment]
Yeah, that sounds good

**Comment by famod** [comment]
As discussed via Zulip, setting port 0 should be avoided for now: https://github.com/quarkusio/quarkus/pull/12117/commits/b3790d6ed1b377b803b2479b9807d2dc9546e0d0
This blocks the proper test setup for this case (unless someone else comes up with a different idea).

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
