### PR TITLE
Enable the generation of documentation for extensions whose package name contains 5 specific components

### PR DESCRIPTION
**Pull request by yrodiere**
Because I'm going to introduce an extension named `quarkus-hibernate-search-orm-elasticsearch-aws`. Yes that's a mouthful, but considering it's an integration into the existing `quarkus-hibernate-search-orm-elasticsearch`, there isn't much choice in how to name it...

The change is quite similar to 5be4cffe02fe5d204a39e84302771733accf2f1c, so I expect it should be safe?

Note I also tried the pattern `^io\\.quarkus\\.(\\w+)(?:\\.(\\w+))*` as an alternative, but it doesn't work: it seems capturing groups in non-capturing groups are ignored for some reason.

### CODE REVIEW

**Comment by yrodiere** [comment]
> @yrodiere have you made a diff of the generated doc before and after this change?

Doing that right now, be back with the diff in a few minutes...

**Comment by yrodiere** [comment]
> > @yrodiere have you made a diff of the generated doc before and after this change?
> 
> Doing that right now, be back with the diff in a few minutes...

Done. I ran your aliases, `build-fast && build-docs`, both on `main` and on this branch. Absolutely no differences in the resulting `docs/target/generated-docs`.

**Review by gsmet — APPROVED** [review]
Cool, thanks!

**Comment by yrodiere** [comment]
I also diffed `target/asciidoc/generated/config`. Here is the result: https://gist.github.com/yrodiere/14406494aebcf0e6d430646b765e13fd

As far as I can tell the differences are unrelated to my changes. All the differences are related to `quarkus-amazon-common`, which is a base module reused in multiple extensions, but which is not documented by itself. 

Most likely these files have a different content for each build, because multiple extensions compete for their content.

**Comment by yrodiere** [comment]
> As far as I can tell the differences are unrelated to my changes.

Also, FWIW, `docs/target/generated-docs/` does not have any difference, and it does include the configuration docs for every documented extension, converted to HTML.

**Pull request merged**
