### PR TITLE
Move to RESTEasy 4.1.0.Final

### PR DESCRIPTION
**Pull request by asoldano**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Let's wait for CI.

**Comment by kenfinnigan** [comment]
Does this update include MP REST Client 1.3 impl?

**Comment by asoldano** [comment]
@kenfinnigan yes, another PR should likely be opened to remove the smallrye impl and pull the resteasy one (the resteasy-client-microprofile artifact http://central.maven.org/maven2/org/jboss/resteasy/resteasy-client-microprofile/4.1.0.Final/ )

**Comment by kenfinnigan** [comment]
Ok, that's what I was wondering.

Is the preference for it to be in a separate PR?

**Comment by asoldano** [comment]
@kenfinnigan , it's really that today and possibly tomorrow I don't have the bandwidth for figuring out what has to be done exactly for the MP REST Client impl switch here, so I thought to upgrade RESTEasy anyway in the meantime. If you have time for that, fine with me :-)

**Pull request merged**
