### PR TITLE
More config doc improvements

### PR DESCRIPTION
**Pull request by gsmet**
I started on it to fix the enum values in the details being all weird and I ended up deep down in the rabbit hole. Hopefully, they are all improvements over what we have :).

Commits better reviewed separately or by generating the end result.

/cc @FroMage @machi1990

### CODE REVIEW

**Comment by FroMage** [comment]
Can we have a screenshot ? :)

**Comment by gsmet** [comment]
@FroMage once thing I would like a second opinion on is should we add a dot or remove the dot at the end of the first line in the table. I think we should be consistent because it's weird in a table like that but can't decide if it's better with or without.

**Comment by gsmet** [comment]
Screenshot from 2019-09-05 15-18-13

Showing the nice title we have on the icon now.

**Comment by FroMage** [comment]
I think the dot is better.

**Review by FroMage — APPROVED** [review]
LGTM

**Comment by machi1990** [comment]
> Can we have a screenshot ? :)

I'll try to update this repo - https://github.com/machi1990/quarkus-generated-extension-config-docs with more generated docs.

**Comment by machi1990** [comment]
LLGM.

**Pull request merged**
