### PR TITLE
Update SmallRye Config to 2.9.1

### LINKED ISSUE #19970: "[WARNING] unknown enum constant org.osgi.annotation.bundle.Requirement.Resolution.OPTIONAL" when compiler warnings are enabled
### Describe the bug

`maven-compiler-plugin` issues a warning when your app is using `@ConfigProperty` and compiler warnings are enabled:
```
[INFO] Compiling 1 source file to /home/famod/proj/quarkus-quickstarts/config-quickstart/target/classes
[WARNING] unknown enum constant org.osgi.annotation.bundle.Requirement.Resolution.OPTIONAL
  reason: class file for org.osgi.annotation.bundle.Requirement$Resolution not found
```

### Expected behavior

No such warning.

### Actual behavior

Warning w.r.t OSGI annotations. Also pollutes "real" compilation errors which can lead developers astray.

### How to Reproduce?

`./mvnw clean compile -f config-quickstart/ -Dmaven.compiler.showWarnings=true` in `quarkus-quickstarts`.

### Output of `uname -a` or `ver`

Linux XXX 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.2.Final, probably since 2.0, up to current 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/OSGI.20Warnings

https://mvnrepository.com/artifact/org.eclipse.microprofile.config/microprofile-config-api/2.0 defines provided OSGI annotations.
Adding https://mvnrepository.com/artifact/org.osgi/osgi.annotation/7.0.0 works around the issue.

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes https://github.com/quarkusio/quarkus/issues/19970

### CODE REVIEW

**Comment by radcortez** [comment]
Not really required. This is only the MP API fix for the compiler warning. I think we can live with it for a little longer :)

**Comment by jorsol** [comment]
So, are we going to have a backport to 2.7.2.FInal? 😄

**Review by gastaldi — APPROVED** [review]

**Comment by jorsol** [comment]
Ohh, it didn't make it 😞

**Comment by radcortez** [comment]
You can update it manually until is available :)

**Pull request merged**
