### PR TITLE
Amazon services - cosmetics - rename variables in common processors

### PR DESCRIPTION
**Pull request by marcinczeczko**

### CODE REVIEW

**Comment by marcinczeczko** [comment]
@gsmet - these are just some cosmetics, found dynamodb variable names in the common module

**Review by gsmet — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by geoand** [comment]
Can you please rebase the PR onto master to pick up some CI fixes? 

Thanks

**Comment by marcinczeczko** [comment]
@geoand - done

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
