### PR TITLE
Qute: fix parsing of section parameters

### LINKED ISSUE #13107: Qute: fishy `#if` expressions
I tried several variations of `{#if foo.bar == 'something' || foo.bar == 'other'}` and got mixed results, but not valid results. I think the second boolean operand was ignored, or random.

For some reason, `{#if (foo.bar == 'something') || (foo.bar == 'other')}` got me an error.

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #13107
- also add more tests for IfSectionHelper

### CODE REVIEW

**Review by FroMage — CHANGES_REQUESTED** [review]
It doesn't solve the issue for me. I just tried it.

My real code is this BTW:

```java
       {#for qual in bean.qualifiers}
        {#if qual.name != 'javax.inject.Named'
          && qual.name != 'javax.enterprise.inject.Any'
          && qual.name != 'javax.enterprise.inject.Default'}
          <span class="annotation" title="{qual.name}">@{qual.localName}</span><br/>
        {/if}
       {/for}
```

**Comment by mkouba** [comment]
I see. We don't handle whitespaces (line breaks, etc.) in expressions correctly. I'll try to fix that shortly... 

BTW the real code was really helpful and it should have been in the description of the issue ;-).

**Comment by FroMage** [comment]
> BTW the real code was really helpful and it should have been in the description of the issue ;-).

Absolutely, really sorry about that :(

**Review by FroMage — APPROVED** [review]
Confirmed it fixes my issue, thanks!

**Pull request merged**
