### PR TITLE
Use proper Maven repositories to resolve deployment dependencies

### LINKED ISSUE #18125: Broken dependency when using OpenTelemetry + REST Client on main
## Describe the bug
When combining `quarkus-opentelemetry-exporter-otlp` and `rest-client` extensions, Maven is unable to resolve the `io.quarkus:quarkus-opentelemetry-rest-client-deployment` dependency unless it is locally cached.  

### Expected behavior
Build success

### Actual behavior
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:generate-code (default) on project opentelemetry-test: Quarkus code generation phase has failed: Failed to bootstrap the application: Failed to create the application model for org.acme:opentelemetry-test::jar:1.0.0-SNAPSHOT: Failed to resolve artifacts: Could not find artifact io.quarkus:quarkus-opentelemetry-rest-client-deployment:jar:999-SNAPSHOT
```

## To Reproduce
Make sure you do not have `io.quarkus:quarkus-opentelemetry-rest-client-deployment:jar:999-SNAPSHOT` in local Maven repo and a remote repo with Quarkus `999-SNAPSHOT` is available.
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DplatformArtifactId=quarkus-bom \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=opentelemetry-test \
    -Dextensions="rest-client,quarkus-opentelemetry-exporter-otlp"
cd opentelemetry-test
mvn clean compile
```

See also https://github.com/quarkusio/quarkus-quickstarts/tree/development/opentelemetry-quickstart, which fails in the same manner when using a remote repository.

## Environment:
```
Apache Maven 3.8.1
Java version: 11.0.10, vendor: AdoptOpenJDK
Quarkus main (999-SNAPSHOT)
```

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #18125

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky I wonder if the issue is related to your patch.

**Comment by aloubyansky** [comment]
most probably

**Comment by aloubyansky** [comment]
Should be good now.

**Review by gsmet — APPROVED** [review]

**Comment by ambition-consulting** [comment]
thanks, this was haunting me also

**Pull request merged**
