### PR TITLE
WIP - Show the worst possible workaround for QCL leak in tests

### PR DESCRIPTION
**Pull request by geoand**
Relates to: #12498

Even after these horrific hacks are applied, there seems to be another Netty related leak that I couldn't identity.

cc @stuartwdouglas

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I don't think either of these are the underlying problem, these objects are loaded by the QuarkusClassLoader, the statics should not prevent GC. I had a look at the reproducer and if you exclude RESTAssured the leaks go away. 

The real issue seems to be some kind of reflection cache in groovy that is doing funky things with SoftReference. I will investigate further but I think there will likely be some horrible groovy hack required.

**Comment by geoand** [comment]
That's odd, I couldn't find any trace of Groovy in the memory snapshots, but I might have missed it

**Comment by stuartwdouglas** [comment]
So I see it in yourkit as not being 'strongly reachable' (i.e. it is being held by either soft/weak references or objects pending finalization). The thing is though that non matter how much GC is run it still does no get cleaned up.

**Comment by geoand** [comment]
OK cool. I see it now as well.

I had checked `Ignore soft/weak references`

**Comment by geoand** [comment]
>  The thing is though that non matter how much GC is run it still does no get cleaned up.

Any idea what could be causing it?

**Comment by stuartwdouglas** [comment]
If you add `quarkus.class-loading.parent-first-artifacts=org.codehaus.groovy:groovy` the leak goes away. 

I think it is technically a JVM bug, where there are basically soft references going everywhere and it does not realize that the ClassLoaders are eligible for GC. Figuring out exactly what causes this will take some investigation though.

**Comment by geoand** [comment]
I don't think more investigation is warranted if we can just make Groovy parent first and be done with it

**Comment by geoand** [comment]
Closing

**Pull request closed without merging**
