### PR TITLE
Add AMQP Connector tests

### LINKED ISSUE #8023: Improve test coverage of the AMQP connector
**Description**
The Reactive Messaging AMQP connector lacks of test coverage.

**Tests to be added**

* Test plain connection to an AMQP router (activeMQ)
* Test secured connection to an AMQP router (activeMQ) - this includes credentials and TLS
* Test sending and receiving all the AMQP types as well as the JSON-B serialization / deserialization
* Test hot reload when the configuration is updated
* Test hot reload when the code is updated

### PR DESCRIPTION
**Pull request by cescoffier**
This PR includes:

* dev mode tests
* anonymous and secured access
* IT (including native) tests

It fixes #8023.

### CODE REVIEW

**Comment by cescoffier** [comment]
Related tests are failing, I will have a look.

**Comment by cescoffier** [comment]
Unfortunately, the issue is due to the CI system:
```
2020-04-01T07:21:03.1717805Z 2020-04-01 07:21:02,987 WARN  [org.apa.act.art.cor.server] (Thread-2 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@157267db)) AMQ222210: Free storage space is at 8.9GB of 89.3GB total. Usage rate is 90.0% which is beyond the configured <max-disk-usage>. System will start blocking producers.
```

**Comment by cescoffier** [comment]
Got the CI fixed.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Could you rebase?

**Comment by cescoffier** [comment]
@gsmet Rebase done.

**Pull request merged**
