### PR TITLE
azure-functions fix ClassCastException at post-requests

### LINKED ISSUE #6940: Azure Functions - BaseFunction.java triggers a ClassCastException on Azure JavaWorker
**Describe the bug**
Say you deploy a Quarkus app to Azure Functions (using mvn azure-functions:deploy or mvn azure-functions:run). Later you want to interact with any of your endpoints. You get a ClassCastException (see Actual Behavior section)

**Expected behavior**
Being able to interact with the REST endpoint

**Actual behavior**
`[2/2/2020 5:34:45 AM] Executed 'Functions.quarkus' (Failed, Id=5b062e90-b8e1-463c-bd7b-d7fa412acddd)
[2/2/2020 5:34:45 AM] System.Private.CoreLib: Exception while executing function: Functions.quarkus. System.Private.CoreLib: Result: Failure
Exception: ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@4f5c16a2to type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<byte[]>>
Stack: java.lang.ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@4f5c16a2to type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<byte[]>>
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataOperations.generalAssignment(DataOperations.java:191)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:120)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:55)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52) [2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2/2/2020 5:34:45 AM]   at java.lang.Thread.run(Thread.java:748)
[2/2/2020 5:34:45 AM] .`

**To Reproduce**
1. Build a hello world quarkus app 
2. Run locally: `mvn azure-functions:run`
3. Exercise your REST endpoint

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
image

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [Version 10.0.18363.628]`
 - Output of `java -version`: 
openjdk version "1.8.0_222"
`OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-win64) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-win64) (build 25.222-b10, mixed mode)`
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.1.Final
- Azure functions version: 1.3.0

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by moewes**
…ional<String>> to avoid class cast Errors for POST-Request with mimetype application/json

fixes #6940

### CODE REVIEW

**Comment by gsmet** [comment]
@patriot1burke any chance you could have a look at this one?

**Review by patriot1burke — CHANGES_REQUESTED** [review]
I do not approve this PR at the moment as it will not work if the payload is binary and not json.  I'm pretty sure this is configuration related, but I need to review Azure Functions as I haven't done them in a long time.

**Comment by moewes** [comment]
@patriot1burke 
Hello Bill, at first I was unsure if I break something with this change. Especially when I had to change some integration tests too that were not directly in this extension. I Looked around in google and found this in the azure functions code:
https://github.com/Azure/azure-functions-java-worker/pull/259/commits/bd78c01970e3911902fb3c12ebfbe3febfa31525#
As far as I understand this change there will be no byte[] under any circumstances. Either there will be a deserializing to a Java type if possible or the payload will be put in a string. Maybe this helps to investigate it further. I don't want to break anything but in the actual version POST with json doesn't work at all which is in my point of view a more typical use case for a serverless function. Regards Maik

**Comment by patriot1burke** [comment]
Going to have to not support binary data :...(  Poor testing on my part.

See this:

https://github.com/Azure/azure-functions-java-worker/issues/44

**Review by patriot1burke — APPROVED** [review]

**Comment by patriot1burke** [comment]
Approving as there is no workaround.

**Pull request merged**
