### PR TITLE
Make 'postgres print-command' quarkus command work with reactive datasources

### LINKED ISSUE #27622: NPE in DEV console command
### Describe the bug

I started my app with `mvn clean quarkus:dev`, opened the DEV console with `:` then typed `postgres print-command` and got an NPE:

```
You are now in Quarkus Terminal. Your app is still running. Use `help` or tab completion to explore, `quit` or `q` to return to your application.
quarkus$ postgres print-command 
java.lang.NullPointerException
quarkus$ 
```

The normal terminal has more info:

```
2022-08-31 11:46:36,602 WARNING [org.aes.rea.Process] (Thread-77) Uncaught exception when executing the command: io.quarkus.devservices.postgresql.deployment.PsqlCommand@78eb1c73: java.lang.RuntimeException: java.lang.NullPointerException
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:237)
	at org.aesh.readline.Process.run(Process.java:80)
Caused by: java.lang.NullPointerException
	at io.quarkus.devservices.postgresql.deployment.PsqlCommand.execute(PsqlCommand.java:28)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
	... 1 more
```

[quarkus-dev-console-psql.zip](https://github.com/quarkusio/quarkus/files/9460437/quarkus-dev-console-psql.zip)

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #27622

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
It's the only command of this type, right?

**Comment by geoand** [comment]
AFAIK, yes

**Comment by FroMage** [comment]
Thanks!

**Comment by geoand** [comment]
👌

**Pull request merged**
