### PR TITLE
Update KeycloakPolicyEnforcerAuthorizer to init in a PostConstruct method

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
All the NPE guards are not needed really as this http policy implementation is not registered now if the oidc and policy enforcer configs are disabled - the problem has been is that the authorizer has been registered even if the oidc is disabled but initialized only if it is enabled

**Comment by sberyozkin** [comment]
@pedroigor @gastaldi Making this PR now ready for review - it does not have to make it to `1.13.0.Final` so please take your time to review

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by sberyozkin** [comment]
@gastaldi Thanks, yeah, I recall your earlier comment where I had to check NPE at the policy check time and it just did not look right :-), so indeed, going the bean way should be safer and no NPE checks are needed

**Comment by sberyozkin** [comment]
Hey @pedroigor I'm happy to go with George's @gastaldi approval since it is a pure structural update which I'm doing in this PR based on the earlier feedback, any concern - let us know please - I'll start with merging this PR as it will cause a conflict for another pending one which I will resolve next

**Pull request merged**
