### PR TITLE
Post-process proto files one by one to reduce memory usage

### LINKED ISSUE #30817: Grpc post processing throws OOM exception with large number of proto file
### Describe the bug

Importing a large set of proto files from a dependency like `io.envoyproxy.controlplane:api`  causes OOM.

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:generate-code (default) on project grpc: Quarkus code generation phase has failed: InvocationTargetException: Java heap space -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```

### Expected behavior

Post-processing passed without tuning heap size

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

GrpcPostProcessing parsed all files in memory before post processing them. It should process files sequentially. I'll provide a MR to fix it.

### PR DESCRIPTION
**Pull request by scrocquesel**
Fixes: #30817

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Comment by scrocquesel** [comment]
Tests passed on my CI https://github.com/scrocquesel/quarkus/actions/runs/4075859630

**Comment by cescoffier** [comment]
I will relaunch then, it's a bit suspicious.

**Comment by geoand** [comment]
The failure is very suspicious indeed...

**Comment by cescoffier** [comment]
Definitely related. @scrocquesel can you have a look?

**Comment by scrocquesel** [comment]
> > Definitely related. @scrocquesel can you have a look?
> 
> Yes, I'll try to build a windows env to debug it.

Cannot reproduce localy with same JDK. Seems it introduce kind of race condition. Need to dig into the hotreload stuff.

**Comment by gsmet** [comment]
Please rebase the PR to latest main before pushing again.

**Comment by scrocquesel** [comment]
@cescoffier hard to reproduce locally but it did occur once in a while even with previous version.
It seems that codegen watcher and compilation watcher are not sync'ed and it may happen that the compilation starts while codegen has not finished yet. I guess that as the new version is doing post processing file by file, files are modified on a longer time period and it may trigger a build in between while a unit is being overwritten more often than the previous version.
Also, I don't understand why it always pass on my github CI and always fail here. Is there a way to trigger only the two failing tests ?

**Comment by cescoffier** [comment]
Weird, we never had such an issue... Why would it start failing now?

**Comment by scrocquesel** [comment]
Giving a try to first postprocessing file in temporary space and replace to the final destination in one loop.

**Comment by scrocquesel** [comment]
@cescoffier I really think there is a race condition between codegen watcher and compilation watcher. TBH, I don't really like having to create temporary files and then moving them all at once. It feels like when codegen watcher trigger a codegen, it  should retain compilation watcher from triggering a builder (or even compare files timestamps). Maybe an issue for later.

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
