### PR TITLE
Add ability to remove classes from a dependency

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This is an advanced option, but there have been a few cases
recently where this would be useful.

### CODE REVIEW

**Comment by geoand** [comment]
Maybe also add a test for running the production application?

**Comment by stuartwdouglas** [comment]
This needs a bit more work and some more tests, as I have discovered some other use cases.

**Review by geoand — APPROVED** [review]
Very interesting and very advanced option :)

**Comment by stuartwdouglas** [comment]
The primary use case I have for this is a Quarkiverse Logback extension, that needs to remove the SLF4J binding.

**Pull request merged**
