### PR TITLE
Qute - ignore expressions/tags starting with invalid identifiers 

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by mkouba** [comment]
@sdaschner FYI.

**Review by maxandersen — APPROVED** [review]
looks good! lgtm!

**Comment by sdaschner** [comment]
Thanks!

**Comment by mkouba** [comment]
I can see `java.net.BindException: Address already in use: bind` in `HibernateValidatorFunctionalityTest.testCDIBeanMethodValidation` on the windows machine again and again :-(.

**Pull request merged**
