### PR TITLE
Bump Keycloak version to 18.0.0

### PR DESCRIPTION
**Pull request by sberyozkin**
I've run all (I think) OIDC tests (in native mode), nearly all works well except for `keycloak-authorization` tests.

@pedroigor `KeycloakTestResource` fails to create a realm [here](https://github.com/quarkusio/quarkus/blob/main/extensions/keycloak-authorization/deployment/src/test/java/io/quarkus/keycloak/pep/test/KeycloakTestResource.java#L49).

I've traced it, the token is created successfully but the realm creation fails with `401`:

```
1. Get Admin Token: 
 
Request:

POST /auth/realms/master/protocol/openid-connect/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=admin&client_id=admin-cli

Response:

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 1837

{"access_token":"ey...Q", ..., "token_type":"Bearer",..."}

2. Create Realm 

Request:

POST /auth/admin/realms HTTP/1.1
Authorization: Bearer ey..Q
Content-Type: application/json
Content-Length: 11859

{realm data}

Response:

HTTP/1.1 401 Unauthorized
```

Note this is run against WildFly based distro.

Not sure what is specific here about `keycloak-authorization` since many other OIDC tests also create realms in WildFly based Keycloak. 

I suspect that the extra Keycloak authorization specific content which may be causing it. Oh, I think I know what it is about. Is it related to uploading scripts :-) ? If yes, please suggest how to replace [this method](https://github.com/quarkusio/quarkus/blob/main/extensions/keycloak-authorization/deployment/src/test/java/io/quarkus/keycloak/pep/test/KeycloakTestResource.java#L181).

Thanks

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@sberyozkin I think this is because of the removal of the `upload-scripts` feature. Without it, you can't upload scripts anymore through the Admin REST API.

Now, scripts should be deployed to the server. Wherever we are using this https://github.com/quarkusio/quarkus/blob/main/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/KeycloakTestResource.java#L231. It should fail.

I think I need to review the test suite and migrate it accordingly.

**Comment by sberyozkin** [comment]
@pedroigor Yeah, please have a look at what can still be tested.

>Now, scripts should be deployed to the server.

If it is possible to point to such script resources with the system/start-up property when launching Keycloak then we can move the scripts to the test resources

**Comment by pedroigor** [comment]
@sberyozkin I've some changes to update the authz integration tests as you can see here https://github.com/pedroigor/quarkus/tree/issue-25109.

They should be enough to use KC 18 and the implementation is pretty much based on what you did to `oidc`.

I'm going to prepare a PR but If you could try it out and see if it is aligned with what you expect, I appreciate it.

**Comment by sberyozkin** [comment]
Hey @pedroigor Thanks, good to see how the migration should be done, let me try it

**Comment by sberyozkin** [comment]
@pedroigor I've cherry-picked your commit but had no luck with getting the tests passed, here is a diff related to your commit:
```
diff --git a/integration-tests/keycloak-authorization/pom.xml b/integration-tests/keycloak-authorization/pom.xml
index e2de51ca0d..af4b68f68e 100644
--- a/integration-tests/keycloak-authorization/pom.xml
+++ b/integration-tests/keycloak-authorization/pom.xml
@@ -201,7 +201,27 @@
                 </plugins>
             </build>
         </profile>
-
+        <profile>
+            <id>jakarta-rewrite</id>
+            <activation>
+                <property>
+                    <name>jakarta-rewrite</name>
+                </property>
+            </activation>
+            <build>
+                <plugins>
+                    <plugin>
+                        <groupId>org.openrewrite.maven</groupId>
+                        <artifactId>rewrite-maven-plugin</artifactId>
+                        <configuration>
+                            <activeRecipes>
+                                <recipe>io.quarkus.keycloak-admin-client</recipe>
+                            </activeRecipes>
+                        </configuration>
+                    </plugin>
+                </plugins>
+            </build>
+        </profile>
     </profiles>
 
 </project>
diff --git a/integration-tests/keycloak-authorization/src/main/resources/application.properties b/integration-tests/keycloak-authorization/src/main/resources/application.properties
index 114282376f..dc147e146a 100644
--- a/integration-tests/keycloak-authorization/src/main/resources/application.properties
+++ b/integration-tests/keycloak-authorization/src/main/resources/application.properties
@@ -79,4 +79,4 @@ quarkus.keycloak.webapp-tenant.policy-enforcer.paths.1.name=Permission Resource
 quarkus.keycloak.webapp-tenant.policy-enforcer.paths.1.path=/api-permission-webapp
 quarkus.keycloak.webapp-tenant.policy-enforcer.paths.1.claim-information-point.claims.static-claim=static-claim
 
-admin-url=${quarkus.oidc.auth-server-url}
\ No newline at end of file
+admin-url=${keycloak.url}
diff --git a/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/KeycloakXTestResourceLifecycleManager.java b/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/KeycloakXTestResourceLifecycleManager.java
index 2fb610452b..fb0b14b265 100644
--- a/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/KeycloakXTestResourceLifecycleManager.java
+++ b/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/KeycloakXTestResourceLifecycleManager.java
@@ -1,23 +1,18 @@
 package io.quarkus.it.keycloak;
 
 import java.io.ByteArrayOutputStream;
-import java.io.FileNotFoundException;
-import java.io.FileOutputStream;
 import java.io.IOException;
 import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.Collections;
-import java.util.HashMap;
 import java.util.HashSet;
 import java.util.List;
 import java.util.Map;
+
 import org.jboss.logging.Logger;
 import org.jboss.shrinkwrap.api.ShrinkWrap;
 import org.jboss.shrinkwrap.api.exporter.ZipExporter;
-import org.jboss.shrinkwrap.api.formatter.Formatter;
-import org.jboss.shrinkwrap.api.formatter.Formatters;
 import org.jboss.shrinkwrap.api.spec.JavaArchive;
-import org.jboss.shrinkwrap.api.spec.WebArchive;
 import org.keycloak.representations.AccessTokenResponse;
 import org.keycloak.representations.idm.ClientRepresentation;
 import org.keycloak.representations.idm.CredentialRepresentation;
@@ -29,7 +24,6 @@ import org.keycloak.representations.idm.authorization.PolicyRepresentation;
 import org.keycloak.representations.idm.authorization.ResourceRepresentation;
 import org.keycloak.representations.idm.authorization.ResourceServerRepresentation;
 import org.keycloak.util.JsonSerialization;
-import org.testcontainers.containers.BindMode;
 import org.testcontainers.containers.GenericContainer;
 import org.testcontainers.containers.wait.strategy.Wait;
 import org.testcontainers.images.builder.Transferable;
@@ -47,21 +41,19 @@ public class KeycloakXTestResourceLifecycleManager implements QuarkusTestResourc
     private static final String KEYCLOAK_SERVICE_CLIENT = "quarkus-service-app";
     private static final String KEYCLOAK_VERSION = System.getProperty("keycloak.version");
 
-    private static String SERVER_KEYSTORE = "server-keystore.jks";
-    private static String SERVER_KEYSTORE_MOUNTED_PATH = "/etc/server-keystore.jks";
-
     @SuppressWarnings("resource")
     @Override
     public Map<String, String> start() {
         keycloak = new GenericContainer<>("quay.io/keycloak/keycloak:" + KEYCLOAK_VERSION)
-                .withExposedPorts(8080, 8443)
+                .withExposedPorts(8080)
                 .withEnv("KEYCLOAK_ADMIN", "admin")
                 .withEnv("KEYCLOAK_ADMIN_PASSWORD", "admin")
                 .waitingFor(Wait.forLogMessage(".*Keycloak.*started.*", 1));
 
         JavaArchive archive = ShrinkWrap.create(JavaArchive.class);
 
-        archive.addAsResource(getClass().getResource("/policies/META-INF/keycloak-scripts.json"), "META-INF/keycloak-scripts.json");
+        archive.addAsResource(getClass().getResource("/policies/META-INF/keycloak-scripts.json"),
+                "META-INF/keycloak-scripts.json");
         archive.addAsResource(getClass().getResource("/policies/admin-policy.js"), "admin-policy.js");
         archive.addAsResource(getClass().getResource("/policies/always-grant.js"), "always-grant.js");
         archive.addAsResource(getClass().getResource("/policies/body-claim-based-policy.js"), "body-claim-based-policy.js");
@@ -75,9 +67,9 @@ public class KeycloakXTestResourceLifecycleManager implements QuarkusTestResourc
         archive.as(ZipExporter.class).exportTo(outputStream);
 
         keycloak = keycloak
-                .withClasspathResourceMapping(SERVER_KEYSTORE, SERVER_KEYSTORE_MOUNTED_PATH, BindMode.READ_ONLY)
                 .withCopyToContainer(Transferable.of(outputStream.toByteArray()), "/opt/keycloak/providers/policies.jar")
-                .withCommand(String.format("-v start-dev --https-key-store-file=%s", SERVER_KEYSTORE_MOUNTED_PATH));
+                .withCommand(
+                        String.format("-v start --http-enabled=true --hostname-strict=false --hostname-strict-https=false"));
         keycloak.start();
         LOGGER.info(keycloak.getLogs());
 
@@ -87,7 +79,8 @@ public class KeycloakXTestResourceLifecycleManager implements QuarkusTestResourc
 
         postRealm(realm);
 
-        return Map.of("quarkus.oidc.auth-server-url", KEYCLOAK_SERVER_URL + "/realms/" + KEYCLOAK_REALM);
+        return Map.of("quarkus.oidc.auth-server-url", KEYCLOAK_SERVER_URL + "/realms/" + KEYCLOAK_REALM,
+                "keycloak.url", KEYCLOAK_SERVER_URL);
     }
 
     private static void postRealm(RealmRepresentation realm) {
diff --git a/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerInGraalITCase.java b/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerInGraalITCase.java
index 9d9b66fbce..5b8400ea65 100644
--- a/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerInGraalITCase.java
+++ b/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerInGraalITCase.java
@@ -1,6 +1,5 @@
 package io.quarkus.it.keycloak;
 
-import io.quarkus.test.common.QuarkusTestResource;
 import io.quarkus.test.junit.QuarkusIntegrationTest;
 
 /**
diff --git a/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerTest.java b/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerTest.java
index 419fa3c387..725e286856 100644
--- a/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerTest.java
+++ b/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/PolicyEnforcerTest.java
@@ -230,7 +230,8 @@ public class PolicyEnforcerTest {
                 .param("client_id", "quarkus-app")
                 .param("client_secret", "secret")
                 .when()
-                .post(KeycloakXTestResourceLifecycleManager.KEYCLOAK_SERVER_URL + "/realms/" + KEYCLOAK_REALM + "/protocol/openid-connect/token")
+                .post(KeycloakXTestResourceLifecycleManager.KEYCLOAK_SERVER_URL + "/realms/" + KEYCLOAK_REALM
+                        + "/protocol/openid-connect/token")
                 .as(AccessTokenResponse.class).getToken();
     }
 }
```
I thought the jakarta profile is still needed because `AdminClientTest` is also there. I also reverted back to `http` only, hoping it would help, but `PolicyEnforcerTest` keeps failing with `404` errors, not sure where they are coming from

**Comment by sberyozkin** [comment]
This must be something really minor, `404` may be reported if keycloak authorization policy is not found as far as I recall

**Pull request closed without merging**
