### PR TITLE
In Resteasy Reactive, fix line separator for "x-ndjson" and "stream+json".

### PR DESCRIPTION
**Pull request by Sgitario**
We're wrongly using `/n` instead of `\n`.
This was done in https://github.com/quarkusio/quarkus/pull/20908

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @michalszynkiewicz

**Comment by geoand** [comment]
Ouch... nice catch

**Review by geoand — APPROVED** [review]

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
> Ouch... nice catch

found it while adding support for ndjson in the client

**Comment by gsmet** [comment]
Well, I think it was high time to invent a brand new new line separator besides `\r`, \n` and `\r\n`. Are we going to innovate or not?!?

**Comment by geoand** [comment]
😆

**Pull request merged**
