### PR TITLE
Upgrade PostgreSQL used for testing to postgres:13.1

### PR DESCRIPTION
**Pull request by Sanne**
This will allow to run all integration tests via podman (rather than docker)

### CODE REVIEW

**Comment by famod** [comment]
I wonder whether the `postgres.image` property should be pulled up to `integration-tests/pom.xml`?

**Comment by Sanne** [comment]
yea that would be nice. I wondered the same... but ideally even I'd like such definitions to be shared among both Maven and the CI action definitions.

**Comment by famod** [comment]
> to be shared among both Maven and the CI action definitions

The CI could parse certain pom.xml files or could use `mvn help:evaluate -Dexpression=...`. I did that a couple of times in `Jenkinsfiles`.
But in this special case: Where is this image used in CI? AFAIKS CI also uses the Maven way to start the containers?

**Comment by Sanne** [comment]
hum right. I remember we had containers defined there, but apparently that was long ago.

**Comment by gsmet** [comment]
> hum right. I remember we had containers defined there, but apparently that was long ago.

Not that long ago but yes I removed them :).

**Comment by gsmet** [comment]
@Sanne so do you plan to adjust this PR to move this to the parent? Or should we do it later?

Considering they are also used for extension tests, the right place for them would be build-parent.

But maybe we should do that for all images at once in a follow-up PR?

**Comment by Sanne** [comment]
I'd prefer a follow-up as I need to jump on other topics. Would be nice to integrate this in the meantime.

**Comment by famod** [comment]
Since I've done quite a few Maven related consolidations lately, I can have a look at it in a separate PR.
PS: I'd love to get more feedback in my other open PRs because they depend on each other (partially) and I'm starting to loose track and have to keep syncing them.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
