### PR TITLE
Oracle DevServices: limit CPU to 2 to avoid excessive memory consumption

### LINKED ISSUE #24939: Oracle Devservice fails to launch on hosts with over 100 CPU cores
### Describe the bug

This is essentially the same issue as https://github.com/gvenzl/oci-oracle-xe/issues/64 but with _even more_ CPU cores. Since using that many cores is unreasonable anyway, and the upstream dockerfile seems to rely on an `if`-case for every CPU count, it might be better to implement a workaround along the lines of this: https://github.com/gvenzl/oci-oracle-xe/issues/64#issuecomment-1099107397

> Wouldn't docker run --cpus=2 option do the trick?
https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler
Unless you really want to use more.

### Quarkus version or git rev

2.8.0

### Additional information

see https://github.com/gvenzl/oci-oracle-xe/issues/64#issuecomment-1087261618 for the error message that is currently happening on a 128 core machine.

### PR DESCRIPTION
**Pull request by Sanne**
(removed)

### CODE REVIEW

**Comment by Sanne** [comment]
@DavideD we might want to apply similar tuning in Hibernate Reactive ?

**Review by geoand — APPROVED** [review]
Seems reasonable

**Comment by Felk** [comment]
I wanna try if this works, but I am really having trouble getting quarkus built and the snapshot pushed to our repository. Is there a way to have the CI build and publish a version of this?

**Comment by geoand** [comment]
Unfortunately, no, we don't publish snapshots of pull requests

**Comment by geoand** [comment]
Have you read the contributing guide to see how to build ?

**Comment by Felk** [comment]
Yes, and I can get it to build with the `quickly` profile, given I don't touch the version to be anything else than `999-SNAPSHOT`. I'm just struggling to `mvn deploy` it to our jfrog artifactory (it needs to be there because the fat machine with > 100 cores is our gitlab runner host, not anyone's local machine).

I changed the `distributionManagement` in several places to point to our company artifactory:
```
<distributionManagement>
	<repository>
		<id>acme-releases</id>
		<name>ACME Release</name>
		<url>https://artifactory.acme.net/artifactory/acme-releases</url>
	</repository>
	<snapshotRepository>
		<id>acme-snapshots</id>
		<name>ACME Snapshots</name>
		<url>https://artifactory.acme.net/artifactory/acme-snapshots</url>
		<uniqueVersion>false</uniqueVersion>
	</snapshotRepository>
</distributionManagement>
```
but I can't push the snapshots there:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project quarkus-ide-config: Failed to deploy artifacts: Could not transfer artifact io.quarkus:quarkus-ide-config:jar:999-20220419.135547-1 from/to acme-snapshots (https://artifactory.acme.net/artifactory/acme-snapshots): authorization failed for https://artifactory.acme.net/artifactory/acme-snapshots/io/quarkus/quarkus-ide-config/999-SNAPSHOT/quarkus-ide-config-999-20220419.135547-1.jar, status: 403 Forbidden -> [Help 1]
```
It's most certainly a wetware issue and has nothing to do with quarkus. For me in 99% of cases a 403 Forbidden error is not actually permission related (I can push to that repository fine in other cases), but instead indicated me trying to push the wrong thing to the wrong repository. I just don't see what is wrong there. Maven sometimes just breaks my head. I'll try again tomorrow if I find the time.

**Comment by Sanne** [comment]
@Felk I can try verifying that my path does indeed translate to the equivalent of running `docker run --cpus=2 `.

Perhaps you could verify on your 100 CPU machine if running oracle that way works fine?

Then we can assume this is most likely fixed and merge it since it seems otherwise harmless.  You can then more easily test it at the next release, and in worse case we can re-open the issue.

**Comment by Sanne** [comment]
So apparently I actually need to use `withNanoCPUs(2_000_000_000l)` for this to be effective. Need to update the PR.

**Comment by Sanne** [comment]
Something is off with github, it's not reflecting the changes I just pushed. Will need to open a new PR.

Replaced by #25009

**Pull request closed without merging**
