### PR TITLE
Codestart modularize pom

### PR DESCRIPTION
**Pull request by vsevel**
split pom file into multiple fragments.
introduce data variables to control what is included.
optionally not include a particular artifact dependency (in case it is already inherited from another known extension)
optionally not include a version for a particular artifact dependency (in case some common dependencies are from dependency mgmt).

in our case, we would overidde the `codestart.yml` with: 
```
    data:
      pom:
        properties: false
        dependency-management: false
        dependencies:
          ignored-artifacts:
            - quarkus-arc
            - quarkus-rest
            - quarkus-config-yaml
            - quarkus-scheduler
            - quarkus-cache
            - quarkus-rest-client-jackson
          ignored-version-artifact-prefix: mycompany-
        plugins:
          compiler: false
          surefire: false
          failsafe: false
        profiles:
          native: false
```

explanation:
- we provide a parent
- properties, dependency mgmt, native profile, and plugins (other than quarkus) come from the parent
- several common quarkus extensions are dragged from a common company extension (no need to list `quarkus-arc` in new projects)
- our extensions are in dependency mgmt in parent pom

see the [zulip discussion](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/custom.20create.20app.20scaffolding/near/462363339)

### CODE REVIEW

**Comment by ia3andy** [comment]
It looks good.

The only thing I would prefer to avoid is the ignored dependencies, it is very specific to your case and will introduce complexity. Let's find another solution to this.

**Comment by ia3andy** [comment]
What I suggest is making the dependencies also modular and use the ignore in your overridden template.
Same for plugins instead of introducing many data which are not useful for most apps, use an include and override it for your case.

**Comment by vsevel** [comment]
> dependencies also modular and use the ignore in your overridden template.

ok let me propose a new version

**Review by ia3andy — APPROVED** [review]
Very nice!

**Comment by vsevel** [comment]
I think we are complete. I am going to squash and rebase. thanks for the review. I tested it on my project, with my override and that works out nicely.
I was wondering if the `FROM` should have been `include` too. that would allow me to not override the entire `codestart.yml`. WDYT?

**Comment by vsevel** [comment]
hmmm. I rebase and now I get this error:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create (default-cli) on project standalone-pom: Failed to generate Quarkus project: ConflictStrategyHandler named 'docker-compose-includes' not found. Used with filter 'docker-compose-include-*' -> [Help 1]
```

**Comment by vsevel** [comment]
@ia3andy squashed, rebased and re-tested.

**Pull request closed without merging**
