### PR TITLE
Optimize the use of buffers in health reporting

### PR DESCRIPTION
**Pull request by geoand**
This is done by leveraging Vert.x's `Buffer` directly instead
of relying on a `ByteArrayOutputStream` which results in
of unnecessary copying of data

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Looks good. I wonder if the `BufferOutputStream` should go into a util package somewhere?

**Comment by geoand** [comment]
I thought about that, but I would say let's play it safe and keep it private for now and revise the decision if we need something similar in the future

**Comment by mkouba** [comment]
> I thought about that, but I would say let's play it safe and keep it private for now and revise the decision if we need something similar in the future

+1 expect that nobody would know about this class (and you'll probably forget about it in a few months too ;-).

**Comment by geoand** [comment]
That is entirely possible 😆

**Pull request merged**
