### PR TITLE
Add new property quarkus.transaction-manager.xa-assume-recovery-complete to allow assuming recovery has succeeded

### LINKED ISSUE #35806: Narayana JTA: expose property to set xaAssumeRecoveryComplete
### Description

There is a gap in the XA restore process. If all resources have acknowledged the transaction, narayana deletes the transaction from its transaction store. If the application dies right in this moment and restarts, narayana still thinks that the XA transaction is not finished, but the transactions on the resources were already committed, and the resources do not have any memory about those transactions. This, in return, leads the a log message similar to:
```
... ARJUNA016037: Could not find new XAResource to use for recovering non-serializable XAResource XAResourceRecord ...
```

This message will appear periodically with log-level `WARN`, until the correspoding transaction log is removed.

[This link (`access.redhat.com`)](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html/development_guide/java_transaction_api_jta#limitations_of_the_xa_recovery_process) suggests setting system-property `com.arjuna.ats.jta.xaAssumeRecoveryComplete` to `true`.

While we can start the application with `java ... -Dcom.arjuna.ats.jta.xaAssumeRecoveryComplete=true ...`, it would be convenient to have a configuration property like `quarkus.transaction-manager.xa-assume-recovery-complete` that can be set in `application.properties`/`application.yml`.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by turing85**
Resolves #35806

### CODE REVIEW

**Comment by turing85** [comment]
Closing since it should be implemented in a different way.

**Comment by turing85** [comment]
See https://github.com/quarkusio/quarkus/issues/35806#issuecomment-1714189933

**Review by mmusgrov — CHANGES_REQUESTED** [review]
This property can result in the deletion of valid transaction logs which can compromise data integrity (the C part of ACID). We realised that this was an issue back in 2011 and provided an alternative: https://issues.redhat.com/browse/JBTM-860 ("use XAResourceWrapper metadata for assume complete"). The property still exists for backwards compatibility and for deployments where it is absolutely certain that a resource can be found (message ARJUNA-16037 "Could not find new XAResource to use for recovering non-serializable XAResource" is related), to do the recovery on on the very first recovery attempt since we would otherwise delete the log. Please refer to the discussion on the issue for the varying points of view.

**Pull request closed without merging**
