### PR TITLE
Simplify wiremock config in oidc

### PR DESCRIPTION
**Pull request by alex-martel**
In wiremock 3, `ResponseTemplateTransformer` should not be created manually; see https://github.com/wiremock/wiremock/pull/2350#issuecomment-1706610158

Wiremock now creates one internally, by default local. Also made few simplifications within the same class by using static imports + bump to 3.0.3  while at it.

follows up on https://github.com/quarkusio/quarkus/pull/35649

supersedes https://github.com/quarkusio/quarkus/pull/35820
supersedes https://github.com/quarkusio/quarkus/pull/35821

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks, though now that I think about it, may be it is better to have 2 commits in this PR, one bump the version, another update the OIDC test code. Guillaume, do you have any preferences ?

**Review by sberyozkin — APPROVED** [review]

**Comment by geoand** [comment]
> Thanks, though now that I think about it, may be it is better to have 2 commits in this PR, one bump the version, another update the OIDC test code. Guillaume, do you have any preferences ?

Yeah, that's probably best

**Comment by manofthepeace** [comment]
Done

**Comment by sberyozkin** [comment]
The test failures are not related

**Pull request merged**
