### PR TITLE
Add more netty tweaks to make reactor-netty work on top of quarkus-netty

### PR DESCRIPTION
**Pull request by ppalaga**
The second version of https://github.com/quarkusio/quarkus/pull/14774 after it was merged and reverted.

This one adds two more delayed init classes: `io.netty.channel.socket.InternetProtocolFamily` and `io.netty.channel.socket.nio.ProtocolFamilyConverter$1`

### CODE REVIEW

**Comment by gsmet** [comment]
@ppalaga does it fix the issue we had with `NetUtil`?

**Comment by ppalaga** [comment]
> @ppalaga does it fix the issue we had with `NetUtil`?

https://github.com/quarkusio/quarkus/pull/14894 is merged now so if something was missing in this PR some of the native tests would have failed, wouldn't they?

**Comment by ppalaga** [comment]
I had a `NetUtil` problem also in Camel Quarkus after upgrading to Quarkus 1.12.0.CR1 and this change solved it for me. Hard to say though, whether it was the same issue as the one because of which you reverted the original PR.

The failed test in in the JVM Tests - JDK 8 job does not seem to be related.

**Comment by gsmet** [comment]
@cescoffier could you have a look as you're our Netty guardian?

**Comment by ppalaga** [comment]
Any chance to review, @cescoffier, before this ages too much?

**Comment by cescoffier** [comment]
I'm worried about the classes initialized at runtime. I have a netty update to do, and I'm afraid it would cause issue at some point. 

The substitutions look good.

**Comment by ppalaga** [comment]
> I'm worried about the classes initialized at runtime. I have a netty update to do, and I'm afraid it would cause issue at some point.
>
> The substitutions look good.

OK, let me remove the substitutions. We can keep the delayed initialization items in Camel Quarkus for now.

**Comment by ppalaga** [comment]
573ec6f: removed the delayed class initialization items, kept only the substitutions

**Review by gsmet — APPROVED** [review]
@cescoffier is OK with the substitutions!

**Pull request merged**
