### PR TITLE
Don't allow QuarkusUnitTest access to classes in the test directory that are not part of the deployment

### PR DESCRIPTION
**Pull request by stuartwdouglas**
…hat are not part of the deployment

### CODE REVIEW

**Comment by geoand** [comment]
The `Quarkus - Integration Tests - Vault` is failing with:

```
Caused by: java.lang.ClassNotFoundException: io.quarkus.vault.VaultITCase
```

**Comment by stuartwdouglas** [comment]
I did not realise they were unit tests, so I did not test them out locally.

**Comment by geoand** [comment]
Yeah they have a misleading name.

**Review by gsmet — APPROVED** [review]
Nice improvement.

**Pull request merged**
