### PR TITLE
SmallRye OpenAPI 3.7.0 and Tests to check content type between Services and OpenAPI

### LINKED ISSUE #36646: OpenAPI support to register schema for a type from 3rd party lib
### Description

Range class is from 3rd party lib and we can not add openapi schema definition for it.

So we need to add the same definition for every field using Range type.

```java
@Schema(title = "timeRange", implementation = String.class, example = "[2020-02-02T00:00:00Z,2022-02-02T00:00:00Z]")
Range<ZonedDateTime> timeRange
```

To avoid repeating myself, I would like to know if quarkus openapi provides the functionality to register schema for types of 3rd party libraries？

### Implementation ideas

something like:

```java
openapiConfig.registerSchema(
  Schema.of(new GenericType<Range<ZonedDateTime>>() {})
  .implementation(String.class).example("[,]")
  .build()
)
```

### LINKED ISSUE #36677: OpenAPI.yaml with recursion
### Describe the bug

With the current Quarkus (3.5.0.CR1) a recursion in the openapi.yaml file will occur. 
When using Enum in a Collection (in my case a Set) the following openapi.yaml is generated:

```yaml
openapi: 3.0.3
info:
  title: quarkus-openapi API
  version: 1.0.0-SNAPSHOT
paths:
  /hello:
    get:
      tags:
      - Greeting Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    MyClass:
      description: MyClass Description
      type: object
      properties:
        myEnums:
          description: My Enum Set
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/MyEnum'
    MyEnum:
      $ref: '#/components/schemas/MyEnum'
```
The Enum MyEnum has a selfreference.

### Expected behavior

The openapi.yaml should look like the following:

```yaml
openapi: 3.0.3
info:
  title: quarkus-openapi API
  version: 1.0.0-SNAPSHOT
paths:
  /hello:
    get:
      tags:
      - Greeting Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    MyClass:
      description: MyClass Description
      type: object
      properties:
        myEnums:
          description: My Enum Set
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/MyEnum'
    MyEnum:
      description: A special Enum
      enum:
      - VALUE_ONE
      - VALUE_TWO
      - VALUE_THREE
      type: string
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
```

### Actual behavior

_No response_

### How to Reproduce?

Under https://github.com/KaiSuchomel/quarkus_openapi i have created a small reproducer.

1. Run Test `org.acme.CheckOpenApiTest`

With Quarkus 3.4.3 the CheckOpenApiTest is successfully running. With 3.5.0.CR1 not.

### Output of `uname -a` or `ver`

5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

3.5.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /opt/apache/maven/apache-maven-3.9.0
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: /home/kai/.jbang/cache/jdks/17
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-87-generic", arch: "amd64", family: "unix"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
This started with this issue: #34700 and some initial fixes when into OpenAPI (some more needed) but we decided to first do a good analysis for the issue.

**As discussed with @FroMage  and @geoand :**

- Default values of content types for both Producing (return object) and Consuming (input parameters) in Services should be aligned.
- Different Services (RESTEasy, RESTEasy-Reacitve, Spring Web, ~~Reactive Routes~~) behavior needs to be consistent
- Handling of content type and content type wrapped in an holder (except Collection) should be consistent

The fixes happened in SmallRye OpenAPI and this PR is mostly tests and the upgrade of SmallRye OpenAPI to [3.7.0](https://github.com/smallrye/smallrye-open-api/releases/tag/3.7.0).

SmallRye OpenAPI 3.7.0 also 
Fix #36677 
Fix #36646

//cc @MikeEdgar 

**Extensions to analyze**

- [ ] resteasy-reactive
- [x] resteasy-reactive-jackson
- [ ] resteasy-reactive-jsonb
- [ ] resteasy-reactive-jaxb
- [ ] resteasy
- [ ] resteasy-jackson
- [ ] resteasy-jsonb
- [ ] resteasy-jaxb
- [x] spring-web
- [ ] reactive-routes

**Types to consider**

- [x] String
- [x] Integer/ int / OptionalInt
- [x] Boolean
- [x] Pojo
- [x] Byte / byte
- [x] Short / short
- [x] Long / long
- [ ] Float / float
- [ ] Double / double
- [ ] Character / char
- [x] File
- [x] InputStream
- [x] Reader
- [x] BigDecimal
- [x] BigInteger
- [x] URL
- [ ] Buffer (Vertx)
- [ ] JsonObject
- [ ] JsonArray
- [ ] JsonStructure
- [ ] JsonValue

**Wrappers**

- [x] RestResponse<?>
- [x] ResponseEntity<?>
- [x] Optional<?>
- [x] Uni<?>
- [x] CompletionStage<?>
- [x] CompletedFuture<?>
- [x] List<?>
- [x] [?]
- [x] Map<?,?>

Notes so far:

- Optional <?> and Optional? for services does not work. (Test commented out) For OpenAPI we assume the wrapper (?) type
- URL in services defaults to json, I kept OpenAPI the same. We discussed that this should be text. If we want to change this we need coordinate.
- File/InputStream/Reader/byte[] defaults to `application/octet-stream` in the service, I make OpenAPI the same
See https://docs.google.com/spreadsheets/d/1NBq31_9qsEhOWX1a1artN3HY6UNK-D7RpG283GfK1yw/edit?usp=sharing

### CODE REVIEW

**Comment by phillip-kruger** [comment]
//cc @cescoffier @FroMage @geoand @rsvoboda

**Comment by MikeEdgar** [comment]
Also closes #36646

**Comment by phillip-kruger** [comment]
@FroMage @geoand - this is now ready for review. Please have a look. 
@rsvoboda - this might break beefy scenarios, please update those tests

**Comment by geoand** [comment]
I'll try and have a look tomorrow.

The test failures do seem relevant thought, right?

**Comment by phillip-kruger** [comment]
@FroMage @geoand - I have rebased, it will be good to get this in, if you get a chance, please have a look. It's mostly just tests as discussed. Thanks :)

**Review by geoand — APPROVED** [review]
Seems reasonable to me!

**Comment by phillip-kruger** [comment]
@geoand The Ci failures looks unrelated, and I see them in other PRs too. Are you ok if we merge ?

**Comment by geoand** [comment]
I am kind of reluctant to merge any PR if there are no passing JDK jobs.

Wanna restart CI?

**Comment by phillip-kruger** [comment]
Let me rebate, as it has already restarted with no effect

**Comment by yrodiere** [comment]
> @yrodiere are these tests known to be failing lately?

Yes, see https://github.com/quarkusio/quarkus/issues/36794

Give me a minute y'all xD

**Comment by geoand** [comment]
Gotcha, sorry for asking. I've been out of the loop the past few days :)

**Comment by yrodiere** [comment]
> Gotcha, sorry for asking. I've been out of the loop the past few days :)

No problem, no need to be sorry :) Anyway, I'm on it...

**Comment by geoand** [comment]
I doubt the devtools failures are related. 

@ia3andy can you take a look and make sure please?

**Comment by ia3andy** [comment]
ok it's due to this PR https://github.com/quarkusio/quarkus/pull/33181, @gsmet didn't you fix the snapshots? I saw a comment about it.. I'll fix it now

**Comment by ia3andy** [comment]
@geoand I made the PR to fix the codestarts: https://github.com/quarkusio/quarkus/pull/36824

**Comment by yrodiere** [comment]
> ok it's due to this PR #33181, @gsmet didn't you fix the snapshots? I saw a comment about it.. I'll fix it now

@ia3andy Guillaume is currently on PTO.

**Comment by geoand** [comment]
@phillip-kruger I would say go ahead and merge this if you are happy with it

**Pull request merged**
