### PR TITLE
REST: comment out useless 10K System.out.printl() in the DrainTest

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
Honestly I would just remove the line.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Merging to free up CI

**Comment by mkouba** [comment]
BTW it seems that `mvn clean test -Dtest=DefaultJaxRsRolesAllowedImplMethodSecuredTest` produces another 6K+ lines in the log. A lot of error messages in this case... will take a look.

**Comment by mkouba** [comment]
Filed https://github.com/quarkusio/quarkus/issues/43017

**Comment by gsmet** [comment]
@mkouba thanks a lot for this!

**Pull request merged**
