### PR TITLE
Set context class loader to the system one when loading the default filesystem providers

### LINKED ISSUE #7424: Unable to inject rest client defined in a different module in a multi module project
**Describe the bug**
I have a multi-module project setup. I am able to use @RestClient based injections for interfaces that are part of the same module (and registered with the @RegisterRestClient annotation).

E.g.,
```
my-project
    |
    |- module-1
        src/main/java/mypackage
            RestAPIInterface.java
        src/test/java/
            @Inject @RestClient RestAPIInterface -- works
    |
    |- module-2
        src/main/java/myOtherPackage
            SomeBean.java
                @Inject @RestClient RestAPIInterface -- does not work
```
Do I need to enable any specific features / switches in order to get this working?

**Expected behavior**
I should be able to inject Rest clients defined in other modules within the same project.

**Actual behavior**
Test case fails stating that there is no client definition

**To Reproduce**
1.  Clone https://github.com/roguexz/quarkus-sample
2. Execute `./gradlew clean test`
3. Observe that the test fails for the `consumer` module.

**Configuration**
```
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_231 (Oracle Corporation 25.231-b11)
OS:           Mac OS X 10.14.6 x86_64
```
**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.2.1.Final

### LINKED ISSUE #9017: [Gradle] ServiceLoader issues in test cases
**Describe the bug**
If a test case pulls in a library that provides a SPI for a service used by Quarkus test configuration (e.g., `FileSystemProvider`), then the test cases fail during boot time with a `ClassCastException` due to the classloader separation introduced in 1.3

Consider the following scenario,
 * In order to setup a mock SSH server, the project declares a `test` dependency on `org.apache.sshd:sshd-sftp`
 * This library provides an implementation for a virtual file system, `SftpFileSystemProvider`
 * In the project you define a `QuarkusTestResource` for configuring the mock SSH server
 * When you run the test case, it fails with a `ClassCastException` during boot time.

**Expected behavior**
The mock SSH server should have started up properly.

**Actual behavior**
We observe a `ClassCastException` instead.

**To Reproduce**
1. Clone the [quarkus-sample](https://github.com/roguexz/quarkus-sample) repository
2. Run `./gradlew clean build`

**Configuration**
```
N/A
```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin LM-SJN-40002334 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "1.8.0_232"
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.3

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #9017 
Fixes #7424

These two issues were reported by the same user. They are different but both reproducers are affected by #9017

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
This does not seem right. FileSystemProvider is part of the JDK, there should never be multiple implementations of it (in fact you can't have multiple impls, because the JDK will stop you).

**Comment by aloubyansky** [comment]
How about https://docs.oracle.com/javase/8/docs/technotes/guides/io/fsp/filesystemprovider.html ?

**Comment by aloubyansky** [comment]
Have you checked the original issue?

**Comment by stuartwdouglas** [comment]
`
Caused by: java.lang.ClassCastException: Cannot cast org.apache.sshd.common.util.security.bouncycastle.BouncyCastleSecurityProviderRegistrar to org.apache.sshd.common.util.security.SecurityProviderRegistrar
	at java.base/java.lang.Class.cast(Class.java:3605)
`

This must be because the FS lookup is not using the TCCL, but some other provider is. 

Is there any reason why we don't pass the TCCL to the ServiceLoader here?

**Comment by aloubyansky** [comment]
It is using the TCCL but the JDK is using the system classloader to load the "installed" providers. The test deps are visible to the system classloader so this is where it picks it up.

**Comment by aloubyansky** [comment]
Well, the JDK actually allows you to provide your own classloader which we don't in this specific case. But even if we did it wouldn't affect this use-case. Because it always loads the providers from the system classloader first and then from the user provided cl.

**Comment by aloubyansky** [comment]
Looks at java.nio.file.spi.FileSystemProvider.loadInstalledProviders()

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Looks like there is not much else that can be done here. 

The global provider list is being loaded from the system CL, but then if the TCCL is set the sshd provider attempts to use the TCCL to load some classes.

**Pull request merged**
