### PR TITLE
Switch to Eclipse Temurin JDK via actions/setup-java

### PR DESCRIPTION
**Pull request by famod**
CI and EA job both passed in my fork.

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Very cool. We probably need to do it for the quickstarts and platform too.

**Comment by famod** [comment]
I can have a look at those afterwards.

**Comment by gsmet** [comment]
There's no immediate urgency. Trying to understand the CL issue you have is far more urgent :).

**Comment by famod** [comment]
This one Gradle test seems to fail on Windows all the time these days (/cc @glefloch but IIRC you're already aware).

**Comment by glefloch** [comment]
right @famod

**Pull request merged**
