### PR TITLE
Replace as many occurrences as possible of master by main

### PR DESCRIPTION
**Pull request by gsmet**
This is a consequence of the renaming of the master branch to main but I
also checked all the external URLs to see if they were changed or not. I
updated them if it was the case.

There are still a some problematic occurrences but they are mostly
related to external projects.

### CODE REVIEW

**Comment by famod** [comment]
```
Error: Unable to resolve action `DeLaGuardo/setup-graalvm@main`, unable to find version `main`
```

**Comment by gastaldi** [comment]
> ```
> Error: Unable to resolve action `DeLaGuardo/setup-graalvm@main`, unable to find version `main`
> ```

When `sed` substitutions are not so reliable... 😆

**Comment by gastaldi** [comment]
We should be using a version, really: `DeLaGuardo/setup-graalvm@3.1` as suggested in https://github.com/marketplace/actions/setup-graalvm-environment

**Comment by famod** [comment]
Or just `3` instead of `3.1` to receive updates for the 3.x line. Some other actions are also defined with just the major version. 🤷‍♂️

**Comment by gsmet** [comment]
> Error: Unable to resolve action `DeLaGuardo/setup-graalvm@main`, unable to find version `main`

Obviously I had to miss the one at the end of the file :/

> When sed substitutions are not so reliable...

Couldn't use sed. There are a lot of master occurrences that we needed to keep. So I used Eclipse with preview and reviewed each change manually. It was a lot of fun.

> We should be using a version, really: DeLaGuardo/setup-graalvm@3.1 as suggested in https://github.com/marketplace/actions/setup-graalvm-environment

As suggested by what? All their examples are using master. Not saying we shouldn't change it but we can do it in another PR.

**Comment by gsmet** [comment]
I changed the quarkiverse-docs branch and fixed the branch of the GH Action.

**Comment by gastaldi** [comment]
> As suggested by what?

Click on the big green button and you'll see it 😉

**Comment by famod** [comment]
Keeping my fingers crossed, but now there is a merge conflict.

**Comment by gsmet** [comment]
I'll wait for the full CI run, then fix the conflict and merge.

**Comment by famod** [comment]
All green! 🎉

**Pull request merged**
