### PR TITLE
Fix picocli codestart readme with gradle

### LINKED ISSUE #15758: Picocli example app readme is incorrect
## Describe the bug
Create app from code.quarkus.io with picocli selected and with Gradle: the readme instructions are incorrect and with bad error report.

### Expected behavior

Readme should show proper Gradle syntax

### Actual behavior

Gradle syntax is incorrect, it should be

```shell script
## incorrect one  (both use of -D and use of help)
./gradlew quarkusDev -Dquarkus.args=='help'

## correct one
./gradlew quarkusDev --quarkus-args='-h'
```

## To Reproduce

Create app from code.quarkus.io with picocli selected and with Gradle.

### Quarkus version or git rev

1.12.2.Final 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #15758

This PR also rename input codestart data.

### CODE REVIEW

**Comment by ia3andy** [comment]
@gsmet it would be nice to get this one in CR1 because it breaks the codestart api. If it can't make it, it's ok, I will need to change it and don't break the api.

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by ia3andy** [comment]
Thanks testing and CI 😅, just pushed a fix..

**Comment by ia3andy** [comment]
The error doesn't seem to be related, should I rebase?

**Comment by gsmet** [comment]
I don't see any errors? If any and looks unrelated  just ping me so I can check. CI is quite overloaded right now so better not push more things if we can avoid it.

**Comment by ia3andy** [comment]
Really weird, I just had CI with a kubernetes test error on JDK11 Linux & Window, then I hit refresh on the issue and its gone... I must be tired..

**Comment by ia3andy** [comment]
Ah ok @gsmet  mystery solved I was on the previous run which failed for a real reason, but also for the kubernestes reason:
https://pipelines.actions.githubusercontent.com/5Na9LjmLgXLiLuzJ0Z1qHRbIDVUXUHNrKe6jPcqGdw5t1S8TiW/_apis/pipelines/1/runs/107604/signedlogcontent/45?urlExpires=2021-03-16T18%3A51%3A03.0725404Z&urlSigningMethod=HMACV1&urlSignature=OBbvGUTdJDMd5HuHXEsxwOvHsx2ZUcsfyeC68ewd8NA%3D

**Comment by gsmet** [comment]
Yeah I confirm this is a flaky test, Georgios already disabled it in main. But JDK 8 doesn't run this test so we will have some results anyway.

**Comment by ia3andy** [comment]
@gsmet I let you merge that one

**Pull request merged**
