### PR TITLE
Extend TestSecurity to support attributes

### PR DESCRIPTION
**Pull request by jasondlee**
Add new SecurityAttribute annotation
Add attributes property to TestSecurity
Process and store new property

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hmm - another oidc code flow failure, seeing
```
 Caused by: io.fabric8.maven.docker.access.hc.http.HttpRequestException: {"message":"received unexpected HTTP status: 502 Bad Gateway"} (Internal Server Error: 500)
```

there was another failure (with `Connection was closed`) earlier

CC @gsmet, Hi Guillaume, has something changed around the way Keycloak images are started ? Also CC Clement @cescoffier

@jasondlee thanks for the PR, LGTM, can you please update some test involving `@TestSecurity` to verify these attributes are available ? For example, one test I'm aware of is in `integration-tests/oidc-code-flow` - perhaps you can update the test endpoint there to echo back the configured attributes
thanks

**Comment by sberyozkin** [comment]
@gsmet, @cescoffier, sorry for the noise, looks like another transient exception:
```
Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to pull 'quay.io/keycloak/keycloak:12.0.3' from registry 'quay.io' : {"message":"received unexpected HTTP status: 502 Bad Gateway"} (Internal Server Error: 500)
```

**Comment by jasondlee** [comment]
> @jasondlee thanks for the PR, LGTM, can you please update some test involving `@TestSecurity` to verify these attributes are available ? For example, one test I'm aware of is in `integration-tests/oidc-code-flow` - perhaps you can update the test endpoint there to echo back the configured attributes
> thanks

@sberyozkin Certainly! I looked in the module and didn't see any tests and just assumed. I guess I could and should have grepped. Or asked. I'll have that up shortly.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by jasondlee** [comment]
@sberyozkin I've pushed a test to exercise the new property as requested. Let me know if you need more.

**Comment by sberyozkin** [comment]
@jasondlee Great, thanks. Please only squash the commits

**Review by sberyozkin — APPROVED** [review]

**Comment by jasondlee** [comment]
Squashed force pushed! :)

**Comment by sberyozkin** [comment]
@jasondlee Great, thanks

**Pull request merged**
