### PR TITLE
Fix grammar error in OIDC and Bootstrap JavaDocs

### PR DESCRIPTION
**Pull request by rolfedh**
@sberyozkin This is a quality update for `main`. 
Do you approve backporting it to `3.2` as well?

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks Rolfe

**Comment by sberyozkin** [comment]
@rolfedh I'e just updated the PR title a bit to make the bot happy, please update it further if you'd like, also proposed a backport to 3.2, thanks

**Review by sberyozkin — APPROVED** [review]

**Review by michelle-purcell — APPROVED** [review]
LGTM too @rolfedh. Thanks.

**Comment by sberyozkin** [comment]
Test failures are not related, merging now

**Pull request merged**
