### PR TITLE
Introduce a version of @OidcClientFilter for the reactive client

### LINKED ISSUE #16522: Enhance RestClient Reactive to support registering providers via custom annotations
## Description

The following is possible with `quarkus-rest-client`, for example, with `OidcClientRequestFilter`

```
@Inject
@OidcClientFilter
MyMpRestClient client;
```
where the `quarkus-oidc-client-filter` extension registers `OidcClientFilter annotation and OidcClientRequestFilter.class` pair, and where `quarkus-rest-client`'s RestClientProcessor [discovers such registrations](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/deployment/src/main/java/io/quarkus/restclient/deployment/RestClientProcessor.java#L241) and [passes them to RestClientBase](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java#L60).

Note as far as `OidcClientRequestFilter` is concerned, the alternative solution (explicitly register it with MP RestClient `RegisterProvider`) is available. This issue is not about `OidcClientRequestFilter` but about a generic support for registering providers via custom annotations.
## Implementation ideas

Do something similar in the reactive rest client to what is done in `quarkus-rest-client`'s [RestClientProcessor](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/deployment/src/main/java/io/quarkus/restclient/deployment/RestClientProcessor.java#L241) and [RestClientBase](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java#L60).

### PR DESCRIPTION
**Pull request by geoand**
Closes: #16522

### CODE REVIEW

**Comment by sberyozkin** [comment]
Oh wow, just stepped outside for a late lunch and the issue is already resolved :-), thanks @geoand, that should be useful for Resteasy Reactive users for sure.

I'd only like to wait for @rsvoboda for us to discuss how to handle this `@OidcClientFilter`, I think just having a package name changed is OK, very minor migration effort, I was considering pushing it down to `quarkus-oidc-client` where it would be misplaced or creating `oidc-client-filter-common` which seems unnecessary, and it would not solve a similar problem for oidc-token-propagation-reactive, so it look fine to me, @rsvoboda are you OK with only a package name having to be changed for `@OidcClientFilter` ?

**Comment by sberyozkin** [comment]
I'll follow up next week with another PR to support a similar mechanism for `oidc-token-propagation-reactive`

**Review by sberyozkin — APPROVED** [review]

**Comment by geoand** [comment]
@sberyozkin I agree with your concern, so let's wait for the discussion before merging

**Comment by sberyozkin** [comment]
@geoand Can you please update https://quarkus.io/guides/security-openid-connect-client-reference#oidc-client-reactive-filter a bit, when you'll have a few mins, it currently says `, and it currently can only be registered with org.eclipse.microprofile.rest.client.annotation.RegisterProvider annotation:` followed by one example, but you can just copy the block from [the section below](https://quarkus.io/guides/security-openid-connect-client-reference#oidc-client-filter) which has `You can selectively register OidcClientRequestFilter by using either io.quarkus.oidc.client.filter.OidcClientFilter or org.eclipse.microprofile.rest.client.annotation.RegisterProvider annotations:` followed by two examples and change the package.

**Comment by geoand** [comment]
@sberyozkin good point. Done

**Comment by rsvoboda** [comment]
Personally I would prefer creating `oidc-client-filter-common` to have the same FQCN for `OidcClientFilter`.
This way migration would be transparent for the end users, they would just update the dependencies (or cli update command one day). The is also `oidc-token-propagation` extension  with `AccessToken` annotation.

Maybe there could be `oidc-common` or `oidc-annotations` which would include both `io.quarkus.oidc.token.propagation.AccessToken` and `io.quarkus.oidc.client.filter.OidcClientFilter`.

**Comment by sberyozkin** [comment]
@rsvoboda We already have `oidc-common` but I'm not sure yet we need to move these annotations down to it, I mean, if a user is switching to the reactive client filter, they may as well change their REST service methods to return `Uni<String>` instead of `String`, see what I mean, the migration is very likely to happen anyway...
Moving them to `oidc-common` is an option but I'm hesitating a bit...

**Comment by sberyozkin** [comment]
`oidc-token-propagation` does not depend on any of `oidc` dependencies as it just propagates the tokens - they may come from `smallrye-jwt`, so if only `@OidcClientFilter` were to be moved then I guess it would be better land in `oidc-client`, that would still leave the option of introducing some other common module but for now it is not obvious it is necessary.
Lets see early next week :-)

**Comment by geoand** [comment]
I think what @rsvoboda is proposing is to move the annotation to a new module, that will then be shared by both old and new (reactive) implementations.

I personally think that makes sense,.

**Comment by sberyozkin** [comment]
Hi @geoand Sure, I think for now I can move it to `quarkus-oidc-client` as both `quarkus-oidc-client-filter` and `quarkus-oidc-client-reactive-filter` depend on it. We also have `quarkus-oidc-common` which `quarkus-oidc-client` and `quarkus-oidc` depend upon, but I'm not sure about moving it to `quarkus-oidc-common` as another pair of extensions where such a transition will currently require the package name update is `quarkus-oidc-token-propagation` and  `quarkus-oidc-token-propagation-reactive` - but these extensions don't depend on `quarkus-oidc-common`.

So moving `@OidcClientFilter` to `quarkus-oidc-client` will address the specific concerns from Rostislav, while will keep the option open for `quarkus-oidc-client-common` if we decide to do something similar for `quarkus-oidc-token-propagation` - or may be for the `quarkus-oidc-token-propagation` to `quarkus-oidc-token-propagation-reactve` transition we can push the related annotations to the already existing `quarkus-security`.

**Comment by geoand** [comment]
@sberyozkin +1.

I propose merging this for now and then you can handle the modules as you see fit. Does that sound good?

**Comment by geoand** [comment]
🎉

**Pull request merged**
