### PR TITLE
Work around Caffeine warnings during cache computations - 1.7

### PR DESCRIPTION
**Pull request by gwenneg**
Backport of #11546 for 1.7.

I couldn't take care of it yesterday, I'm not sure if this is still needed now but here's the backport anyway.

### CODE REVIEW

**Comment by gsmet** [comment]
I had to stop CI to get the resources to test a CI fix.

Please restart tomorrow.

And I confirm we still want this backport :).

**Comment by geoand** [comment]
> I had to stop CI to get the resources to test a CI fix.
> 
> Please restart tomorrow.
> 
> And I confirm we still want this backport :).

And rebase onto master before you do :)

**Comment by gwenneg** [comment]
I can't rebase onto master, this is a PR targeting 1.7 :)

**Comment by geoand** [comment]
Ah right, sorry! I didn't see that :)

**Review by gsmet — APPROVED** [review]

**Pull request merged**
