### PR TITLE
Scheduler - make it possible to record metrics automatically

### PR DESCRIPTION
**Pull request by mkouba**
- when a metrics extension is present and
quarkus.scheduler.metrics.enabled=true a timed interceptor binding is
automatically added to a scheduled method

TODO:

* [x] Add test for MP Metrics
* [x] Add docs

### CODE REVIEW

**Review by ebullient — APPROVED** [review]

**Comment by mkouba** [comment]
Squashed, rebased and ready for review ;-)

**Comment by geoand** [comment]
CI failures seem related

**Comment by mkouba** [comment]
> CI failures seem related

Yes, some of them are related... looking into this.

**Comment by mkouba** [comment]
Hm, the `AgroalMetricsTestCase` fails because the synthetic bean instance for `io.agroal.api.AgroalDataSource` is not initialized when the metrics are registered (I need to check the relevant build steps) and `io.quarkus.scheduler.test.metrics.MicrometerTimedTest` fails for no obvious reason (and I cannot reproduce it locally :-(

**Comment by mkouba** [comment]
The CI is green so it's up to you guys :-)

**Comment by ebullient** [comment]
I've been keeping up, I'm ok

**Comment by mkouba** [comment]
CC @machi1990

**Review by jmartisk — APPROVED** [review]
LGTM

**Pull request merged**
