### PR TITLE
Provide OpenShift Serverless documentation section

### LINKED ISSUE #11442: Unable to run simple hello world application on OpenShift with quarkus.kubernetes.deployment-target=knative
I have simple https://github.com/rsvoboda/openshift-quickstart project for Knative Serving experiment. I have OpenShift 4.5 with OpenShift Serverless - Knative Serving installed.

I'm unable to run simple hello world application on OpenShift with quarkus.kubernetes.deployment-target=knative

**Steps to reproduce**
See README.md in https://github.com/rsvoboda/openshift-quickstart

**Some details:**
The application uses `quarkus-openshift` extension and sets `quarkus.kubernetes.deployment-target=knative` in https://github.com/rsvoboda/openshift-quickstart/blob/master/src/main/resources/application.properties#L3

`mvn clean package -Dquarkus.kubernetes.deploy=true` succeeds, but the service on the cluster can't start.

Service gets available when I change quarkus.kubernetes.deployment-target to openshift :/. 

https://quarkus.io/guides/kubernetes#knative doesn't mention any additional changes.

**More details:**
https://console-openshift-console.apps.ocprs.dynamic.quarkus/k8s/ns/rsvoboda/serving.knative.dev~v1~Service/openshift-quickstart says:

Revision "openshift-quickstart-b5zmr" failed with message: Unable to fetch image "rsvoboda/openshift-quickstart:1.0-SNAPSHOT": failed to resolve image to digest: failed to fetch image information: GET https://index.docker.io/v2/rsvoboda/openshift-quickstart/manifests/1.0-SNAPSHOT: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:rsvoboda/openshift-quickstart Type:repository]].

Log from terminal shows, that the image push was successful:
```
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Pushing image image-registry.openshift-image-registry.svc:5000/rsvoboda/openshift-quickstart:1.0-SNAPSHOT ...
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Getting image source signatures
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Copying blob sha256:96d330a26895c15953dadd5a7cda8801a777e3b49a21bb0f1d5e3006042399d9
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Copying blob sha256:6d7d25eb85759731f9e5726883604d83d1a9f15e2e37ca0bf7c200e638762eef
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Copying blob sha256:332a2e4ef6a26a451b89acbc5c7f57d631e64a554a62298403b5b4ea205241b0
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Copying blob sha256:25f07378c750b25e33c2e34d53f05f1f14a320217c294f43ef7835b96db2d8ae
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Copying config sha256:4fb64a5451f7fd863efafbd6424b12980f9d963c1620e8e0141753038d1ad832
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Writing manifest to image destination
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Deploying to knative server: https://api.ocprs.dynamic.quarkus:6443/ in namespace: rsvoboda.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: ServiceAccount openshift-quickstart.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Service openshift-quickstart.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 71900ms
```

@geoand or @Ladicek can you take a look?

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #11442

### CODE REVIEW

**Comment by geoand** [comment]
cc @rsvoboda @tqvarnst

**Comment by gsmet** [comment]
Should this be backported?

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
Yeah, it should be. 

There might be more fixes to Openshift + Serverless coming (pending a discussion with the various folks involved), but we do need this doc fix based on the current state of things.

**Review by rsvoboda — COMMENTED** [review]
+1 for the docs addition

**Pull request merged**
