### PR TITLE
Reproduce Regression after 576ba7c: io.vertx.core.http.HttpServerRequest.absoluteURI() does not contain port anymore

### PR DESCRIPTION
**Pull request by ppalaga**
Reproducer for #44776

### CODE REVIEW

**Comment by geoand** [comment]
Converred to draft as to not take up CI time

**Comment by sberyozkin** [comment]
@ppalaga Thanks for reporting it, it is consistent with Forwarded `host` treatment, see this [3.17.0 test](https://github.com/quarkusio/quarkus/blob/3.17.0/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/AllowOnlyForwardedHeaderTest.java#L27), the last value is an [absolute URI](https://github.com/quarkusio/quarkus/blob/3.17.0/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/ForwardedHandlerInitializer.java#L21). 

I had to reset the port when processing `X-Forwarded-Host` to get [this test](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/AllowForwardedAndXForwardedHeadersTest.java#L66), passing where both `Forwarded` and `X-Forwarded` headers are used. In this test, the Forwarded has a precedence by default, both provide a matching `host` value, which is allowed by default, but since ,before my PR, X-Forwarded host processing did not reset the local port, as opposed to `Forwarded`  host processing, it was failing the test.

I'm not sure returning the local port alongside the original host name is correct, the client which makes a call is calling `www.host.com` which is routed to `localhost:8080`...

So, right now, the forwarded `host` processing has become consistent between `Forwarded host=...` and `X-Forwarded-Host=`. 

It makes sense to me not to include the current request's port in the absolute URI in this case, my understanding that in order to have port included in the absolute URI where forwarded host is included, the forwarded host value should actually include the port too... It is all non-standardized, example, https://stackoverflow.com/questions/61429542/http-x-forwarded-host-behavior-without-port.


It is all on main, we have time to tweak it, my proposal is leave things as they are now and see if it can actually impact anyone, as I'm not certain at all that including the server port alongside the forwarded host with no port is practical.

What do you think, everyone ? Also CC @cescoffier

**Comment by sberyozkin** [comment]
@ppalaga Peter, by the way, the answer at https://stackoverflow.com/questions/61429542/http-x-forwarded-host-behavior-without-port also supports a default port case if only `X-Forwarded-Host=host`, without port is provided

**Comment by ppalaga** [comment]
> It makes sense to me not to include the current request's port in the absolute URI in this case

After some pondering, I agree keeping the local port in the absolute URI does not make much sense, if the host part reflects the value passed via `X-Forwarded-Host`. Hence the behavior before 576ba7c was awkward and 576ba7c has actually fixed it.

I hope @cescoffier agrees and we can reject this PR and close #44776 as not a bug.

**Comment by cescoffier** [comment]
Yes, I totally agree.

**Pull request closed without merging**
