### PR TITLE
Bump flapdoodle to 4.4.1

### LINKED ISSUE #30957: Mongodb native apps built with JDK20 based GraalVM / Mandrel crash
### Describe the bug

$title

cc @Karm @jerboaa 

### Expected behavior

Application should not crash.

### Actual behavior

Application crashes with:

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2707)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:111)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:45)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$3.getPid(Processes.java:242)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:80)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:61)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:177)
	at de.flapdoodle.embed.process.runtime.ProcessControl.fromCommandLine(ProcessControl.java:173)
	at de.flapdoodle.embed.process.runtime.NUMA.isNUMAOnce(NUMA.java:57)
	at de.flapdoodle.embed.process.runtime.NUMA.lambda$isNUMA$0(NUMA.java:48)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at de.flapdoodle.embed.process.runtime.NUMA.isNUMA(NUMA.java:48)
	at de.flapdoodle.embed.mongo.commands.MongodArguments.warpWithNumaSupport(MongodArguments.java:191)
	at de.flapdoodle.embed.mongo.commands.MongodArguments.asArguments(MongodArguments.java:116)
	at de.flapdoodle.embed.mongo.transitions.MongodProcessArguments.result(MongodProcessArguments.java:97)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:62)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:50)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:165)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69)
	at de.flapdoodle.embed.mongo.transitions.Mongod.start(Mongod.java:90)
	at io.quarkus.test.mongodb.MongoTestResource.start(MongoTestResource.java:71)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:481)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### How to Reproduce?

1. Build GraalVM / Mandrel using JDK 20 EA
2. Set GRAALVM_HOME to point to the build
3. `./mvnw clean verify -Dtest-containers -Dstart-containers -Dformat.skip -Dno-descriptor-tests -Dnative -Dquarkus.native.container-build=false -pl integration-tests/mongodb-client`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

23.0-dev based on JDK 20

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The issue is expected to be resolved once flapdoodle adds support for JDK 20

https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/6075c6018cfac63bf1f9b0c8a662f773dd2cce49/src/main/java/de/flapdoodle/embed/process/runtime/Processes.java#L58-L68

### PR DESCRIPTION
**Pull request by zakkak**
Fixes #30957

### CODE REVIEW

**Comment by geoand** [comment]
We've tried this in the past and it didn't usually work.

@loicmathieu do you remember specifics?

**Comment by zakkak** [comment]
> We've tried this in the past and it didn't usually work.

What's "this" in this context?

4.4.1 was released just yesterday and is a patch fix, you probably refer to some different version bump.

**Comment by geoand** [comment]
> What's "this" in this context?

Bumping flapdoodle to whatever the latest was at the time

**Review by geoand — APPROVED** [review]

**Comment by loicmathieu** [comment]
@geoand in the past, we struggle with Flapdoodle upgrades for two reasons:

- They often have breaking changes
- Our implemention was fragile

Since the good work of @michaelmosmann in https://github.com/quarkusio/quarkus/pull/30366 I think our implementation is no longuer fragile (it works now on Windows CI and without retries) so now it's safe to upgrade Flapdoodle on each release as we do for other libs.

So if CI is green, let's merge it.

**Comment by geoand** [comment]
Awesome, thanks for the update!

**Comment by michaelmosmann** [comment]
@loicmathieu @geoand I did not know until recently that quarkus is using flapdoodle mongo stuff. I nearly gave up a year ago bc i thought that everyone is using testcontainers for that.. but to my surprise there are people using this:) ..

I try to be as stable as it can be.. :) but if anything goes wrong.. i think i can fix it.

**Comment by geoand** [comment]
Thanks for your work on it!

**Comment by gsmet** [comment]
@michaelmosmann we use Flapdoodle because we cannot run containers on Windows in GitHub Actions. So if we want some level of portable testing for MongoDB on GitHub Actions, Flapdoodle is the way to go.
So thanks for your work!

**Comment by loicmathieu** [comment]
Yes, again, thanks @michaelmosmann for your work.

**Pull request merged**
