### PR TITLE
Switch Hibernate ORM/Reactive/Envers extensions to @ConfigMapping

### LINKED ISSUE #38321: Configuration ignored when using config maps and the prefix conflicts with a "static" config group
### Describe the bug

See https://stackoverflow.com/questions/77842431/quarkus-unable-to-name-a-datasource-query

Essentially:

* `quarkus.hibernate-orm.query.*` properties exist in the Hibernate ORM extension; there is a config group called `query`.
* `quarkus.hibernate-orm` is also a configuration map, so `quarkus.hibernate.orm."persistence-uni-name".*` exists to, and `quarkus.hibernate-orm.query.*` could be interpreted as "configuration for the persistence unit named `query`".
* There is, however, little to no overlap between those two possible meanings: the `*` in the patterns above will rarely, if ever, be the same.
* Nevertheless, our config seems to always assume that a property starting with `quarkus.hibernate-orm.query.*` has the first meaning, regardless of what's in `*`, leading to that configuration property being ignored, because it doesn't matched any config mapping.

### Expected behavior

I'd expect `quarkus.hibernate-orm.query.datasource` to be interpreted as "the datasource for the persistence unit named `query`" rather than "the `datasource` config property for the `query` config group, since only the former actually makes sense and has a matching config mapping.

### Actual behavior

`quarkus.hibernate-orm.query.datasource` is interpreted as "the `datasource` config property for the `query` config group, which doesn't make sense.

### How to Reproduce?

Copied from https://stackoverflow.com/questions/77842431/quarkus-unable-to-name-a-datasource-query

Checking out the quickstart from here https://github.com/quarkusio/quarkus-quickstarts.git

On hibernate-orm-panache-quickstart: Edit the application.properties with this content:

```
quarkus.datasource.query.db-kind=postgresql

quarkus.hibernate-orm.query.datasource=query
quarkus.hibernate-orm.query.packages=org.acme.hibernate.orm.panache.entity,org.acme.hibernate.orm.panache.repository
quarkus.hibernate-orm.query.database.generation=drop-and-create
quarkus.hibernate-orm.query.log.sql=true
quarkus.hibernate-orm.query.sql-load-script=import.sql
```

Run the test: FAILED

```
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
    [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#configurationDescriptorBuilding threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Model classes are defined for the default persistence unit, but no default datasource was found. The default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.
```

Edit the application.properties with this content:

```
quarkus.datasource.query-service.db-kind=postgresql

quarkus.hibernate-orm.query-service.datasource=query-service
quarkus.hibernate-orm.query-service.packages=org.acme.hibernate.orm.panache.entity,org.acme.hibernate.orm.panache.repository
quarkus.hibernate-orm.query-service.database.generation=drop-and-create
quarkus.hibernate-orm.query-service.log.sql=true
quarkus.hibernate-orm.query-service.sql-load-script=import.sql
```

Run the test: PASS

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #38321 (I checked manually)

Three reasons for this change:

1. As far as I can tell, the old `@ConfigItem` stuff is more or less deprecated. At least it's not supposed to evolve anymore.
2. Avoid bugs like #38321 in the future. Believe me, #38321 is just one among many. I have not-so-fond memories of bugs related to names containing dots, in particular; those are supposed to work much better with `@ConfigMapping`.
3. Get nicer documentation; thanks to what @radcortez did a few months ago, we no longer get duplicate entries in the config property list for the default persistence unit vs. named persistence units.

### CODE REVIEW

**Comment by yrodiere** [comment]
Hey @zakkak , looks like native image size drifted off again... is that a new problem, or one that should be solved after a rebase? I'm really not sure why this PR would trigger this, so I assume it's also affecting main...

```
org.opentest4j.AssertionFailedError: Expected analysis_results.methods.reflection to be within range [4495 +- 3%] but was 4707 ==> expected: <true> but was: <false>
```

**Comment by zakkak** [comment]
> Except if `@ConfigMapping` creates some additional reflection entries. But let's hear from @zakkak before pinging Roberto if needed.

AFAIU this is exactly what's happening in https://github.com/quarkusio/quarkus/blob/44672ebbdcccbb84bae224f506b1a550a0c9e7d0/extensions/spring-boot-properties/deployment/src/main/java/io/quarkus/spring/boot/properties/deployment/ClassConfigurationPropertiesUtil.java#L308

**Comment by yrodiere** [comment]
Still, from +200 methods with reflection enabled? We don't have that many enums in that config. Unless it also enables reflection on every single method of every single configuration interface?

Let's see if @radcortez (hey!) notices something wrong in this PR or in the reflection-enabling code, and if not I'll just raise the baseline.

**Comment by zakkak** [comment]
> Still, +200 methods with reflection enabled?

FWIW The actual difference (between this PR and `main`) is:

* **jpa-postgresql** 4707-4591= 116
* **jpa-postgresql-withxml** 4893-4776 = 117

The rest of the difference is carried over from previous changes that resulted in differences < 3%.

It still seems quite a lot.

**Comment by yrodiere** [comment]
> > Except if `@ConfigMapping` creates some additional reflection entries. But let's hear from @zakkak before pinging Roberto if needed.
> 
> AFAIU this is exactly what's happening in
> 
> https://github.com/quarkusio/quarkus/blob/44672ebbdcccbb84bae224f506b1a550a0c9e7d0/extensions/spring-boot-properties/deployment/src/main/java/io/quarkus/spring/boot/properties/deployment/ClassConfigurationPropertiesUtil.java#L308

Just noticed this code was taken from a "quarkus-spring" extension, which isn't relevant here.

I'll need to find the full list of methods enabled for reflection, before and after this PR. Then we can start asking ourselves if the new ones really are necessary.

**Comment by radcortez** [comment]
If I remember correctly, we enable reflection on every mapping method because of Bean Validation. Most extensions don't use it, so maybe we can be smarter and only register the BVal annotations methods.

Anyway, let me confirm if this is the case and adjust.

**Comment by radcortez** [comment]
Hum... BTW, we are looking into the wrong code. That code is from the old `@ConfigProperties`. The `@ConfigMapping` registration is in: 

https://github.com/quarkusio/quarkus/blob/1d6599995fe314ceedfab52f69f90598caa416c4/core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigMappingUtils.java#L87-L119

It even has a comment about BVal, which confirms my initial thoughts.

**Comment by gsmet** [comment]
FWIW, there is a build item with all the Bean Validation annotations we detected. So we could probably check if a method has a Bean Validation annotation.

**Comment by gsmet** [comment]
For me the ConfigMapping optimization problem is orthogonal to this PR. Given the size of it and the possibility of conflicts, I would prefer we raise the threshold for now (in a separate commit) and that we create an issue with a reference to this commit, that we would revert once the problem is fixed.

If by chance, we significantly improve things, we could even lower the thresholds.

**Comment by radcortez** [comment]
> I think the BV extension already registers the interfaces for reflection. And I'd expect it to register the implementations as well, it's completely its responsibility. So I think this is some sort of workaround... Maybe mapping implementation classes are not in the Jandex index and BV "forgets" to register them? Something like that? In that case perhaps a better solution would be to make BV aware of these implementation classes... somehow.

Mappings are in Jandex, and there is a build item that carries the mapping information. We even use that in BVal, to start its own validator (to avoid circular dependencies).

In the initial implementations, I've probably added the full registration preemptively, because I knew it was going to be needed and didn't think about optimizations :)

**Comment by yrodiere** [comment]
> For me the ConfigMapping optimization problem is orthogonal to this PR. Given the size of it and the possibility of conflicts, I would prefer we raise the threshold for now (in a separate commit) and that we create an issue with a reference to this commit, that we would revert once the problem is fixed.

Right. I added a commit to update the thresholds.

Let's merge if the build passes now.

**Comment by radcortez** [comment]
I've looked, and here I've changed to register the methods: https://github.com/quarkusio/quarkus/pull/12501/files#diff-26708186baae4b2358b51f3bc3c5731740eff57a0a63fb3a150d15183e817f55R214

Looking into the commit, it seems I added it to allow returning the mapping directly in a REST resource with Jackson. That is probably not required anymore. Let me remove that and see what fails and adjust.

**Comment by zakkak** [comment]
> I'll need to find the full list of methods enabled for reflection, before and after this PR. Then we can start asking ourselves if the new ones really are necessary.

FWIW to do this you can extract the `reflect-config.json` from the generated jar files that are passed to native-image and compare them (between `main` and your branch), e.g.:

```
unzip -j target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar META-INF/native-image/reflect-config.json
```

**Comment by gsmet** [comment]
If you're adding reflection solely for Bean Validation requirements, then you can drop it.
The HV extension should take care of it and if not, we need to fix the bug as it would be one.

**Review by gsmet — APPROVED** [review]

**Review by radcortez — APPROVED** [review]

**Pull request merged**
