### PR TITLE
Avoid potential NPE when collecting RESTEasy Providers on Resource classes

### PR DESCRIPTION
**Pull request by geoand**
Addresses: https://github.com/quarkusio/quarkus/issues/14418#issuecomment-1016607350

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Really, it wasn't necessary to ask another CI run.

**Comment by geoand** [comment]
Yeah, I just wanted to be sure. But we likely have a flaky test

**Comment by gsmet** [comment]
Yeah the `io.quarkus.restclient.configuration.UnknownConfigTest` has been flaky for a while. I pinged @radcortez and @michalszynkiewicz about it already.
And the Gradle stuff has also been a pain lately.

**Comment by radcortez** [comment]
> Yeah the `io.quarkus.restclient.configuration.UnknownConfigTest` has been flaky for a while. I pinged @radcortez and @michalszynkiewicz about it already.

Sorry, forgot about it. https://github.com/quarkusio/quarkus/pull/23037 should do the trick.

**Pull request merged**
