### PR TITLE
fix (#9561): Remove optional from env source and key refs

### LINKED ISSUE #9561: Environment variables from secrets are not exported on OCP 3.11
**Describe the bug**
Exporting secrets as environment variables as described by [Deploying to OpenShift guide](https://quarkus.io/guides/deploying-to-openshift#environment-variables-from-secret) does not work on OCP 3.11.

The same feature works correctly on OCP 4.x.

**Expected behavior**
Secrets should be present in environment variables specified by the property name.

**Actual behavior**
Environment variables are not available in deployment pods on OCP 3.11.

**To Reproduce**
1. Checkout https://github.com/mjurc/mock-artifacts  
2. `oc login` to OCP 3.11
3. `cd quarkus/getting-started/`
4. `oc apply -f src/main/resources/secret.yaml`
5. `mvn clean package`
6. check the deployment pod's env vars - the environment variables are not exported in environment variables as defined by the application's `application.properties` file, e. g. `DB_DATABASE=postgresql`

**Configuration**
```properties
quarkus.openshift.expose=true
quarkus.kubernetes-client.trust-certs=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7

quarkus.openshift.env-vars.DB_DATABASE.secret=postgresql
quarkus.openshift.env-vars.DB_DATABASE.value=database
quarkus.openshift.env-vars.DB_USERNAME.secret=postgresql
quarkus.openshift.env-vars.DB_USERNAME.value=username
quarkus.openshift.env-vars.DB_PASSWORD.secret=postgresql
quarkus.openshift.env-vars.DB_PASSWORD.value=password
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux tigris 5.6.13-300.fc32.x86_64 #1 SMP Thu May 14 22:51:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```
 - GraalVM version (if different from Java): `N/A` 
 - Quarkus version or git rev: 1.3.y, 1.4.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)`

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by iocanel**
Fixes #9561 for 1.3 branch

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Looks great!

**Comment by geoand** [comment]
@gsmet I'll let you merge since this is for the 1.3 branch

**Review by mjurc — APPROVED** [review]

**Comment by mjurc** [comment]
Verifying the fix on the scenario from #9561

**Comment by geoand** [comment]
Thanks a lot @mjurc

**Comment by rsvoboda** [comment]
What's the relation between this PR and https://github.com/dekorateio/dekorate/pull/518 ?

**Comment by geoand** [comment]
This PR is a workaround that will no longer be necessary when  in Quarkus we pick up the dekorate version that contains that fix. Right @iocanel ?

**Pull request merged**
