### PR TITLE
Reinitialize sun.security.pkcs11.P11Util at runtime

### PR DESCRIPTION
**Pull request by zakkak**
Fixes build error:
```
Error: Detected a java.lang.ref.Cleaner object in the image heap which uses a daemon thread that invokes cleaning actions, but threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.ref.Cleaner. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field sun.security.pkcs11.P11Util.cleaner
    at sun.security.pkcs11.wrapper.PKCS11.<init>(PKCS11.java:170)
  parsing method sun.security.pkcs11.wrapper.PKCS11.<init>(PKCS11.java:154) reachable via the parsing context
    at static root method.(Unknown Source)
```

See https://github.com/oracle/graal/actions/runs/4320092514/jobs/7540249135#step:9:154

cc @jerboaa

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@zakkak hi, thinking more about it, should it be done in the resteasy deployment processor instead or it can affect any Quarkus Security code?
Sorry I'll be offline now, going out of the hotel...

**Comment by zakkak** [comment]
> @zakkak hi, thinking more about it, should it be done in the resteasy deployment processor instead or it can affect any Quarkus Security code? Sorry I'll be offline now, going out of the hotel...

Oops, I pasted the wrong error message... (that is fixed by https://github.com/quarkusio/quarkus/pull/31452)

Updating the description with the correct one.

**Review by geoand — APPROVED** [review]

**Review by jerboaa — APPROVED** [review]
Looks good.

**Comment by gsmet** [comment]
@zakkak thanks for the PR! Is it something that we should backport to 2.16 or only affecting the new GraalVM versions?

**Comment by gsmet** [comment]
I think 2.16 will have a longer life than other versions as it's the last 2.x. I'm not sure when the new GraalVM version will be released but if they are not risky we could backport the compatibility PRs.

Probably something to discuss together with the big picture of exactly which PRs will be needed (as if one is too risky, no need to backport all the others).

**Comment by zakkak** [comment]
> I think 2.16 will have a longer life than other versions as it's the last 2.x.

That's OK, the question is whether we plan to move it to a newer GraalVM version or stick to 22.3. Till now we used to do the latter.

**Comment by zakkak** [comment]
Marking this for backport since although [the Cleaner instances were disallowed only recently](https://github.com/oracle/graal/pull/6062) the issue is actually present in older versions as well.

Not sure if it's worth backporting to 2.7 as well.

**Pull request merged**
