### PR TITLE
Updated MP Config to 1.4 and SmallRye Config to 1.6.1

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
@radcortez minor thing, but can we use `SmallRyeConfigBuilder.withSources(Collection)` in https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigUtils.java#L84?

**Comment by radcortez** [comment]
With this new version, yes. I see you added that method there :) It is included.

Do you want me to do the change, or we do it in a separate PR?

**Comment by gastaldi** [comment]
If you could do the change in this PR that would be great (it can be in a separate commit), otherwise I'll send a PR after this one is merged

**Comment by radcortez** [comment]
I'll do it. No worries.

We actually found a regression in 1.6.0, so we may need to hold this a little bit for a new minor version.

**Comment by gastaldi** [comment]
Nice, can you squash the first commit with the second one so you have only two commits in this PR?

**Comment by radcortez** [comment]
Sure. Sec.

**Comment by radcortez** [comment]
Done.

**Pull request merged**
