### PR TITLE
Ensure that the presence of OpenTelemetry does not break Jib builds

### LINKED ISSUE #22864: Using OpenTelemetry gRPC instrumentation produces NullPointerException when running quarkusBuild
### Describe the bug

Using [io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:1.9.2-alpha](https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-grpc-1.6/1.9.2-alpha) and `io.quarkus:quarkus-opentelemetry-exporter-otlp` with Quarkus 2.6.2.Final produces `NullPointerException` when packaging image by `quarkusBuild`.

### Expected behavior

It should produce an image without error.

### Actual behavior

```
$ ./gradlew quarkusBuild

> Task :quarkusGenerateCode
preparing quarkus application
Base image 'foo' does not use a specific image digest - build may not be reproducible

> Task :quarkusBuild FAILED
building quarkus jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
        at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:197)
        at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:136)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
        at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$obtainBaseImagesLayers$6(StepsRunner.java:313)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: java.lang.NullPointerException
        at io.quarkus.opentelemetry.runtime.QuarkusContextStorage.getVertxContext(QuarkusContextStorage.java:62)
        at io.quarkus.opentelemetry.runtime.QuarkusContextStorage.current(QuarkusContextStorage.java:54)
        at io.opentelemetry.context.Context.current(Context.java:86)
        at io.opentelemetry.instrumentation.grpc.v1_6.internal.ContextStorageBridge.current(ContextStorageBridge.java:75)
        at io.grpc.override.ContextStorageOverride.current(ContextStorageOverride.java:31)
        at io.grpc.Context.current(Context.java:172)
        at io.opencensus.trace.CurrentSpanUtils.getCurrentSpan(CurrentSpanUtils.java:37)
        at io.opencensus.trace.Tracer.spanBuilder(Tracer.java:308)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:865)
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:349)
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:266)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:138)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:114)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:625)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:436)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:441)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:290)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:157)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:69)
        ... 6 more
```

### How to Reproduce?

1. Create a new project

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.6.2.Final:create \
    -DprojectGroupId=my-groupId \
    -DprojectArtifactId=my-artifactId \
    -DprojectVersion=my-version \
    -DclassName="org.my.group.MyResource" \
    -Dextensions="resteasy,resteasy-jackson" \
    -DbuildTool=gradle
```

2. Add dependencies

```
    implementation 'io.quarkus:quarkus-container-image-jib'
    implementation 'io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:1.9.2-alpha'
    implementation 'io.quarkus:quarkus-opentelemetry-exporter-otlp'
```

3. Add properties to `gradle.properties` file

```
quarkus.container-image.build=true
quarkus.jib.base-jvm-image=ghcr.io/foo/bar

quarkus.container-image.group=foo
quarkus.container-image.name=bar
```

4. Run `./gradlew quarkusBuild`

### Output of `uname -a` or `ver`

21.2.0

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #22864
Supersedes:  #22865

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand could you check the CI failure? Wondering if this works with JDK 17.

**Comment by geoand** [comment]
Good question... I'll have to check

**Comment by geoand** [comment]
Fixed now!

There was a much simpler solution available after all.

**Review by cescoffier — APPROVED** [review]

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
I'm wondering if we should disable OTel completely during build time. Not sure if there is any benefit.

**Comment by geoand** [comment]
Disable how? Is there a system property?

**Comment by famod** [comment]
Can the fix be backported (if there will be a 2.6.3)? I was about to start playing around with OTel and might not be ablt to jump on 2,7 right when it's released.

**Comment by geoand** [comment]
Sure yeah, I added the label

**Comment by radcortez** [comment]
> Disable how? Is there a system property?

No. But I was thinking of a way to do it (being a system property or something else).

**Comment by geoand** [comment]
My only concern would be that it's done properly so that it doesn't affect dev-mode

**Comment by radcortez** [comment]
Sure, let me think about it.

**Comment by geoand** [comment]
👌🏼

**Comment by XSAM** [comment]
Thank you, guys. I am appreciated the fix. ❤️

BTW, I was wondering when is the release time for 2.6.3

**Comment by geoand** [comment]
We'll see, hopefully soon

**Pull request merged**
