### PR TITLE
Add tests for microprofile opentracing

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://issues.jboss.org/browse/TRACING-461

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
@pavolloffay nice contribution, thanks!

Just one thing: we do not want `@author` tags anymore in the source code (git has the history). There are a couple here and there but we try to remove them gradually.

Could you remove them please?

Thanks!

**Comment by pavolloffay** [comment]
sure I will clean it up

**Comment by pavolloffay** [comment]
@gsmet author comments have been removed

**Review by gsmet — APPROVED** [review]
Looks good to me. Let's wait for CI.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
