### PR TITLE
Update Agroal to 1.8

### PR DESCRIPTION
**Pull request by barreiro**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM. You might want to add it to the Dependabot descriptor?

**Comment by barreiro** [comment]
@gastaldi added Agroal to the dependabot descriptor. Thanks for the suggestion!

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Is this upgrade needed in 1.4.0.Final or can it wait until 1.5.0?

**Comment by barreiro** [comment]
It does **not need** to be in 1.4.0

**Pull request merged**
