### PR TITLE
Support Java 21 main launch protocol

### LINKED ISSUE #36154: Quarkus and Java 21 Instance Main Methods is not working
### Describe the bug

I tried customized QuarkusMain method as shown in https://quarkus.io/guides/lifecycle#the-main-method with Java 21 Instance Main Methods (preview feature).

Code example in https://github.com/rsvoboda/code-with-quarkus/tree/21-main

```java
@QuarkusMain
public class Main {
    void main() {
        System.out.println("==> Running main method");
        Quarkus.run();
    }
}
```

maven-compiler-plugin enabled to use preview features
```xml
    <maven.compiler.release>21</maven.compiler.release>
...
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <compilerArgs>
            <arg>--enable-preview</arg>
          </compilerArgs>
        </configuration>
      </plugin>
```

And I received:
```
Exception in thread "main" java.lang.NoSuchMethodException: org.acme.Main.main([Ljava.lang.String;)
	at java.base/java.lang.Class.getMethod(Class.java:2395)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

I checked if I will see `System.out.println("==> Running main method");` when calling the compiled jar just to ensure compilation went well. Message was printed
```
java --enable-preview -cp target/quarkus-app/app/code-with-quarkus-1.0.0-SNAPSHOT.jar org.acme.Main

==> Running main method
Exception in thread "main" java.lang.NoClassDefFoundError: io/quarkus/runtime/Quarkus
	at org.acme.Main.main(Main.java:10)
Caused by: java.lang.ClassNotFoundException: io.quarkus.runtime.Quarkus
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 1 more
```

### Expected behavior

Quarkus boots

### Actual behavior

Quarkus fails to start

### How to Reproduce?

 - Get example code from `21-main` branch - https://github.com/rsvoboda/code-with-quarkus/tree/21-main
 - Run ` mvn clean package -DskipTests && java --enable-preview -jar target/quarkus-app/quarkus-run.jar`

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This is quick and dirty support for selecting the main method according to the new Java 21 protocol, 
but we might want to consider the alternative of doing bytecode transformation of the main method 
at build time (if necessary obviously)

Closes: #36154

### CODE REVIEW

**Comment by rsvoboda** [comment]
@geoand I have checked the PR on top of Quarkus main and the troubles are gone.

This was quick!

**Comment by geoand** [comment]
Thanks for checking!

The reason I have this in draft is because I am looking into the build time solution as well.

**Comment by geoand** [comment]
#36164 is the alternative I have in mind.

**Comment by geoand** [comment]
I personally prefer https://github.com/quarkusio/quarkus/pull/36164. WDYT @Sanne ?

**Comment by cescoffier** [comment]
I also prefer https://github.com/quarkusio/quarkus/pull/36164

**Comment by geoand** [comment]
I should also thank @Ladicek and @mkouba because without their `ClassTransformer` https://github.com/quarkusio/quarkus/pull/36164 would be a lot more cumbersome :)

**Comment by geoand** [comment]
I'll go ahead and close in favor of the alternative

**Pull request closed without merging**
