### PR TITLE
Allow qute tags with ".qute" prefixed extension

### LINKED ISSUE #23285: Qute: user defined tags not working with .qute.html extension
### Describe the bug

Qute is using by convention extension .qute.html for templates

For example we have admin template ```/src/main/resources/templates/Admin/admin.qute.html``` and it works out of the box.

We can't do the same with user defined tags.

### Expected behavior

Adding template ```/src/main/resources/templates/tags/validation.qute.html``` should register tag ```validation```

### Actual behavior

Only template```/src/main/resources/templates/tags/validation.html``` is registering tag ```validation```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kucharzyk**
Fixes https://github.com/quarkusio/quarkus/issues/23285

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Looks good. Thanks!

**Comment by mkouba** [comment]
@kucharzyk You need to sort the imports in the `UserTagWithQuteExtensionIncludeTest.java`. Just do `mvn clean install` in the `extensions/qute` directory.

**Comment by gastaldi** [comment]
Does this PR fix any issue? If so make sure you mention `Fixes #xxx` in the first PR comment

**Comment by gastaldi** [comment]
> 

Also, don't forget to squash your commits after fixing it 😉

**Comment by kucharzyk** [comment]
I will fix this PR today

**Comment by kucharzyk** [comment]
@mkouba formating fixed, rebased, ready

**Pull request merged**
