### PR TITLE
Changing `userAcceptance` to show all valid inputs and small refactor on the ConfigService class

### PR DESCRIPTION
**Pull request by danielsoro**
* Changing `userAcceptance` to show the invalid input message with all valid input.
* Added test to all valid input for `userAcceptance`
* Small refactor on the `ConfigService` class.

### CODE REVIEW

**Comment by brunobat** [comment]
Thanks very much for the PR @danielsoro !
Will review the PR early next week.

**Review by brunobat — APPROVED** [review]
This looks ok to me! Thanks very much @danielsoro

**Comment by brunobat** [comment]
@maxandersen are you ok with this message:
```
[info] [Quarkus build analytics] Didn't receive a valid user's answer: yes,yy,y,n,nn,no. The question will be asked again next time.

```

**Comment by brunobat** [comment]
@danielsoro, can you please rebase?
There are quite a few changes around logging, in this area.

**Comment by danielsoro** [comment]
> @danielsoro, can you please rebase?
> There are quite a few changes around logging, in this area.

Sorry for the delay, but I was on vacation... I'll look at it and update the PR! 
Thank you for your review! :)

**Pull request closed without merging**
