### PR TITLE
ArC dev mode: introduce quarkus.arc.dev-mode.generate-dependency-graphs

### PR DESCRIPTION
**Pull request by mkouba**
- see https://github.com/quarkusio/quarkus/discussions/37552

### CODE REVIEW

**Comment by gsmet** [comment]
I wonder if we should have a threshold after which we would display an INFO/WARN suggesting to set this value to false?

**Comment by mkouba** [comment]
> I wonder if we should have a threshold after which we would display an INFO/WARN suggesting to set this value to false?

I have no idea what the threshold value should be... 3000? 4000? Also if I understand it correctly the number of beans is not always significant. It might be the complexity of dependencies (as mentioned in the referenced discussion).

**Comment by gsmet** [comment]
Yeah, I know it could be hard. Maybe we could measure the time it takes instead and suggest to set it to false if above a threshold that makes sense?

**Comment by mkouba** [comment]
> Yeah, I know it could be hard. Maybe we could measure the time it takes instead and suggest to set it to false if above a threshold that makes sense?

Hm, I wonder if we should try to measure all `@BuildStep(onlyIf = IsDevelopment.class)` steps instead? Or even log a warning for any build step with duration > threshold (this one should be straightforward to implement). WDYT?

**Comment by mkouba** [comment]
> Or even log a warning for any build step with duration > threshold (this one should be straightforward to implement).

Something like https://github.com/quarkusio/quarkus/pull/37613

**Review by gsmet — COMMENTED** [review]
I wonder if we should make a visual difference between things being empty and things being empty because we didn't generate any information?

But maybe the former can never happen as we will always have beans around?

**Comment by mkouba** [comment]
> I wonder if we should make a visual difference between things being empty and things being empty because we didn't generate any information?

I don't think we should. If the info is not available we just don't show a button to show the graph.

> But maybe the former can never happen as we will always have beans around?

Well, if I understand you correctly then it can happen if a bean has no dependencies.

**Comment by mkouba** [comment]
> We could merge it if it makes the life of the reporter better but I don't think it would be a good idea to release a new 2.16. 

@gsmet Let's merge this. And I agree that we should not do a new 2.16 release.

**Pull request closed without merging**
