### PR TITLE
Minor Resteasy Reactive Servlet fixes

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by geoand** [comment]
It seems like `ServletSimpleRestTestCase` is failing

**Comment by stuartwdouglas** [comment]
Closing for now, there is more broken here than I thought.

**Comment by stuartwdouglas** [comment]
This should be ok now, it gets down to 6 failures in the TCK when running against Servlet.

**Comment by geoand** [comment]
Awesome!

**Review by geoand — APPROVED** [review]

**Pull request merged**
