### PR TITLE
Bump to Jackson 2.11.0

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by geoand** [comment]
Maybe we should wait for a `2.11.1` or something? Just to be on the safe side?

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
Looks fine, but is there a specific reason to upgrade? I'd be cautious as so many components integrate with Jackson - but maybe that's just another reason to merge it now, as we're early in the 1.6 cycle.

**Comment by gsmet** [comment]
For Jackson upgrades, I usually ping @cescoffier to be sure it's not an issue on the Vert.x side.

**Comment by gastaldi** [comment]
@cescoffier might you give us your blessing, please? :wink:

**Comment by cescoffier** [comment]
LGTM

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
