### PR TITLE
Openapi-swaggerui guide - reference MicroProfile OpenAPI Core configuration

### LINKED ISSUE #40007: Add ability to hide rest endpoints from OpenAPI schema / Swagger
### Description

I'm unable to hide JAXRS methods in OpenAPI schema / Swagger.

For endpoints that are experimental or legacy ones I don't want them to be part of the generated schema. That schema serves as public contract in many cases.

I found `io.swagger.v3.oas.annotations.Hidden` annotation, but no equivalent of it in Quarkus OpenAPI extension.
SB has ways to hide endpoints from the generated document even without using `@Hidden` annotation.

Please add ability to hide rest endpoints from OpenAPI schema / Swagger.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by rsvoboda**
Reference MicroProfile OpenAPI Core configuration

- Fixes: https://github.com/quarkusio/quarkus/issues/40007

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Review by MikeEdgar — APPROVED** [review]
LGTM. Note to self - update spec link(s) when bumping to smallrye-open-api 4.0.

**Comment by gsmet** [comment]
I'm all for merging this but do we also have a pointer for the annotations mentioned in https://github.com/quarkusio/quarkus/issues/40007#issuecomment-2049166957 ?

**Comment by MikeEdgar** [comment]
JavaDoc for `@Operation#hidden` is : https://download.eclipse.org/microprofile/microprofile-open-api-3.1.2/apidocs/org/eclipse/microprofile/openapi/annotations/Operation.html#hidden()

**Comment by rsvoboda** [comment]
@gsmet there is no reference for that in https://download.eclipse.org/microprofile/microprofile-open-api-3.1.1/microprofile-openapi-spec-3.1.1.html#_operation

Spec html points also to https://github.com/eclipse/microprofile-open-api/wiki which and https://github.com/eclipse/microprofile-open-api/wiki/Annotation-Samples#operation-sample shows an example with `hidden = true` attribute

So it's pretty hidden :) Pointer for the annotations mentioned in https://github.com/quarkusio/quarkus/issues/40007#issuecomment-2049166957 should be ideally in MicroProfile OpenAPI Specification document.
For our guide I'm not sure where to put info about that. `@Operation` is mentioned only in https://quarkus.io/guides/openapi-swaggerui#auto-generation-of-operation-id

**Comment by gsmet** [comment]
Maybe a generic sentence saying that more information about the MicroProfile OpenAPI annotations can be found in the MicroProfile OpenAPI API Javadoc: https://download.eclipse.org/microprofile/microprofile-open-api-3.1.2/apidocs/org/eclipse/microprofile/openapi/annotations/package-summary.html .

Not perfect but still better than nothing.

And yes, I totally concur on the fact that it should be the MicroProfile OpenAPI doc containing this information.

**Comment by rsvoboda** [comment]
PR updated

**Comment by rsvoboda** [comment]
@gsmet good to go?

**Review by gsmet — APPROVED** [review]

**Pull request merged**
