### PR TITLE
Move quarkus-jaeger and quarkus-smallrye-opentracing to Quarkiverse

### LINKED ISSUE #35984: Jaeger extension end of life and move to Quarkiverse
### Description

The Jaeger extension is on end of life.
No new features will be added and it's role is now filled by `quarkus-opentelemetry'.
The extension will be removed from the Quarkus main repo and moved to Quarkiverse where it will be updated if bugs, security vulnerabilities or weaknesses are found.

This was triggered by this discussion: https://groups.google.com/g/quarkus-dev/c/C2b45e5l6l0/m/d7d-VrHpGQAJ

### LINKED ISSUE #35985: `smallrye-opentracing` end of life and move to Quarkiverse
### Description

The `smallrye-opentracing` extension is on end of life.
No new features will be added and it's role is now filled by `quarkus-opentelemetry'.
The extension will be removed from the Quarkus main repo and moved to Quarkiverse where it will be updated if bugs, security vulnerabilities or weaknesses are found.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #35984
Fixes #35985

@brunobat how do you envision the Quarkiverse extensions? Should I create two separate repositories or do we move the two extensions in one `quarkus-smallrye-opentracing` repository? Note that I don't think Jaeger had any tests on its own.

### CODE REVIEW

**Comment by brunobat** [comment]
> how do you envision the Quarkiverse extensions?

I say 2 different isolated extensions. 

> I don't think Jaeger had any tests on its own

No integration tests, just the tests in the `deployment` project

**Comment by gsmet** [comment]
OK.

@gastaldi would you be kind enough to provision `quarkus-jaeger` and `quarkus-smallrye-opentracing` repositories in the Quarkiverse with me and @brunobat as maintainers?

**Comment by gastaldi** [comment]
> @gastaldi would you be kind enough to provision `quarkus-jaeger` and `quarkus-smallrye-opentracing` repositories in the Quarkiverse with me and @brunobat as maintainers?

Sure, there you go: https://github.com/quarkiverse/quarkiverse-devops/pull/186

**Comment by gsmet** [comment]
I'm back working on this.

**Comment by brunobat** [comment]
I'm finally writing the OpenTracing to OpenTelemetry guide @gsmet.

**Comment by gsmet** [comment]
Cool, looks like the starts will be aligned :).

**Comment by gsmet** [comment]
@brunobat this is now ready, just in time for 3.6.0.CR1 if we can get it merged by tomorrow. I will release the Quarkiverse artifacts once 3.6.0 core artifacts are out so that they are only compatible with 3.6+ and don't appear in 3.5 code.quarkus.io.

**Comment by brunobat** [comment]
@gsmet The failures seem unrelated but the are failing with:
```
2023-11-13T16:32:01.4250160Z Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
2023-11-13T16:32:01.4251226Z Metaspace
2023-11-13T16:32:01.4251779Z java.lang.OutOfMemoryError: Metaspace
```

**Review by brunobat — APPROVED** [review]
It looks good to me.
There are some references on the datasource.adoc to OpenTracing but I'll take care later.
Thanks very much for the help on this @gsmet

**Review by cescoffier — APPROVED** [review]

**Comment by michalvavrik** [comment]
@gsmet this is breaking change (at least it broke QE app), would breaking label fit here?

**Comment by michalvavrik** [comment]
Hmm, I can see it in a migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6 - maybe the flow doesn't require the label, I don't know.

**Comment by brunobat** [comment]
@michalvavrik I also wrote this: https://quarkus.io/version/main/guides/telemetry-opentracing-to-otel-tutorial
I hope it helps. Will add it to the migration guide.

**Comment by michalvavrik** [comment]
> @michalvavrik I also wrote this: https://quarkus.io/version/main/guides/telemetry-opentracing-to-otel-tutorial I hope it helps. Will add it to the migration guide.

thank you

**Comment by gsmet** [comment]
@michalvavrik yeah, you're right, I added the appropriate labels. Thanks for your vigilance!

**Pull request merged**
