### PR TITLE
Allow removing version from Kubernetes label selectors

### LINKED ISSUE #11070: Kubernetes extension should not use version in labelselectors
**Describe the bug**
When using manifests generated by the quarkus kubernetes extension, issues are encountered updating versions of deployed software. This is because labelselectors in deployments and other kubernetes objects are immutable. When using software such as fluxcd, the manifest is not able to be updated without deleting the old deployment, or naming the new deployment something else, as labelSelectors cannot be updated in a deployment manifest.

**Expected behavior**
LabelSelector will not include:
`app.kubernetes.io/version`

in the manifests generated

**Actual behavior**
`app.kubernetes.io/version` is included in the manifests

**To Reproduce**
1. Generate build for a versioned release.
2. Deploy the build to kubernetes
3. Generate a build for a new version
4. Try to apply manifests with kubectl apply. Observe failure due to immutable labelSelector.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #11070

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel can you take a look please?

**Comment by gsmet** [comment]
This needs a rebase.

**Comment by geoand** [comment]
Done, @iocanel can you please review?

**Comment by gsmet** [comment]
@iocanel could you review this one tomorrow? We need it in CR1 IMHO. Thanks.

**Review by iocanel — CHANGES_REQUESTED** [review]
We don't need decorator per resource. We can just create a single decorator that will be applied everywhere. Maybe a decorator on ObjectMetaFluent is all we need. An alternative would be on HasMetadataFluent or something

**Comment by geoand** [comment]
@iocanel note that the selector is different for `Deployment` and `DeploymentConfig`. If we were to go with one Decorator, we would need to do type checks and casts to get the desired functionality. Are you sure that's what we want?

**Comment by iocanel** [comment]
Need to check.

**Comment by iocanel** [comment]
You are right! 

Deployment and DeploymentConfig resources are created with their labels set and they are not decorated.
This means that our AddLabelDecorator and RemoveLabelDecorator have logical errors and may cause issues. Also means that its likely to have mismatches when using `existing resources`.

Let's keep that for now and I'll raise an issue on decorate side.

**Comment by geoand** [comment]
Thanks for checking!

So should we put this on hold and wait for the dekorate fix or merge it as is?

**Comment by iocanel** [comment]
> Thanks for checking!
> 
> So should we put this on hold and wait for the dekorate fix or merge it as is?

Depends on how fast we need this to get in.

**Comment by geoand** [comment]
It's not super important, just a nice to have

**Comment by iocanel** [comment]
> It's not super important, just a nice to have

Then let's fix on decorate and align.

**Comment by gsmet** [comment]
Closing this one then.

**Comment by geoand** [comment]
We'll it's not invalid, it just needs to be updated when we have a new Dekorate release :).

So I'll reopen so we can address it for 1.8

**Review by iocanel — COMMENTED** [review]
Once #12160 get's in we should be able to proceed with this one.
The latest dekorate version introduces decorators for adding/removing labels from selectors `matchingLabes`.

**Comment by geoand** [comment]
@iocanel do you want to take over this PR now that dekorate has been updated?

**Review by iocanel — COMMENTED** [review]
Will do!

**Comment by geoand** [comment]
Thanks!

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
Thanks for driving it home @iocanel!

**Pull request merged**
