### PR TITLE
(3.2) MySQL connector 8.2

### PR DESCRIPTION
**Pull request by jmartisk**
https://issues.redhat.com/browse/QUARKUS-3849

### CODE REVIEW

**Comment by gsmet** [comment]
CI is failing with:
```
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.oracle.bmc.ConfigFileReader. This error is reported at image build time because class com.mysql.cj.protocol.a.authentication.AuthenticationOciClient is registered for linking at image build time by command line
```

My advice would be to go though the update PRs that went into main and build this one from them as there might have been changes to make it work.

**Comment by geoand** [comment]
This substitution seems to be the same thing we have in `main` added in a8d766d27cf15fa2e587a120b82ad14554744efc.
I would suggest cherry-picking it

**Comment by jmartisk** [comment]
Ah, right, so the substitution requirement is not due to bumping the version, but due to switching to the new coordinates of the driver. Glad that I guessed the solution correctly :) ok I'll cherry-pick it

**Comment by aloubyansky** [comment]
@jmartisk i think we should go with 8.0.33. Removing the previous G:A may break existing projections when upgrading.

**Comment by aloubyansky** [comment]
And we should have both G:A with the same 8.0.33 version.

**Comment by jmartisk** [comment]
@aloubyansky AFAIU 8.0.33 doesn't have the necessary CVE fix that we want

**Comment by aloubyansky** [comment]
Ok, i confused it with another CVE fixed in 8.0.33. LGTM

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
