### PR TITLE
WIP : Add support for timeouts config properties for MicroProfile RestClient

### PR DESCRIPTION
**Pull request by lhauspie**
Add support of connectTimeout and readTimeout as explained is the issue #4338

### CODE REVIEW

**Comment by lhauspie** [comment]
I encounter some difficulties to test my work.

This piece of (RestEasy) code in `RestClientBuilderImpl.java` :
```
        if (!SSL_ENABLED) {
            resteasyClientBuilder.httpEngine(new URLConnectionEngine());
            resteasyClientBuilder.sslContext(null);
            resteasyClientBuilder.trustStore(null);
            resteasyClientBuilder.keyStore(null, "");
        }
```

Combined with this piece of (RestEasy) code in `ResteasyClientBuilderImpl.java` :
```
      ClientHttpEngine engine = httpEngine != null ? httpEngine : new ClientHttpEngineBuilder43().resteasyClientBuilder(this).build();
```

Make the configuration not working.

The only way I found to make integration tests to work is to define the `quarkus.ssl.native` to `true` in `application.properties`.

**Comment by kenfinnigan** [comment]
@lhauspie as part of resolving skipped MP Rest Client TCK tests I was looking into this issue on Friday.

As a result, I've raised https://issues.jboss.org/browse/RESTEASY-2377 to discuss with the RESTEasy team the appropriate way to fix it

**Comment by lhauspie** [comment]
So I can maybe remove the `WIP` tag in this PR ?

**Comment by kenfinnigan** [comment]
We can compare when I push what I'd done, as I took a different approach that supports the new config key short name in the code

**Comment by lhauspie-adeo** [comment]
On which branch did you pushed your code?
I would be happy to compare our approaches ;)

**Comment by lhauspie** [comment]
> We can compare when I push what I'd done, as I took a different approach that supports the new config key short name in the code

On which branch did you push your code?
I would be happy to compare our approaches ;)

**Comment by kenfinnigan** [comment]
@lhauspie My current branch is here: https://github.com/kenfinnigan/quarkus/tree/restclient

**Comment by lhauspie** [comment]
Ok... I saw what you did.
We did almost the same thing except I think your code is more elegant and clearer.

Maybe I can refactor my work to approximatly seem like yours.

But still not working while no solution is found on https://issues.jboss.org/browse/RESTEASY-2377 :/

**Comment by kenfinnigan** [comment]
My solution to https://issues.jboss.org/browse/RESTEASY-2377 is merged and will ask for a release when I know there aren't additional changes needed for other REST Client TCK fixes

**Comment by lhauspie-adeo** [comment]
> My solution to https://issues.jboss.org/browse/RESTEASY-2377 is merged and will ask for a release when I know there aren't additional changes needed for other REST Client TCK fixes

Wow! What an efficiency!
So wait and see!

**Comment by lhauspie** [comment]
> My solution to https://issues.jboss.org/browse/RESTEASY-2377 is merged and will ask for a release when I know there aren't additional changes needed for other REST Client TCK fixes

Wow! What an efficiency!
So wait and see!

**Comment by kenfinnigan** [comment]
Going to close this as it's superseded by https://github.com/quarkusio/quarkus/pull/4954

**Pull request closed without merging**
