### PR TITLE
Copy registered services into the file system when using fast-jar

### PR DESCRIPTION
**Pull request by geoand**
This allows the RunnerClassLoader to load these resources without having
to go through the jars

Relates to: #13256

### CODE REVIEW

**Comment by geoand** [comment]
@Sanne here is a first draft of handling JDK Service files in the RunnerClassLoader. It's totally bare bones but I did seem to work in a couple examples I tried.

This is based on the services we register with the `ServiceProviderBuildItem`, however I casually saw a lot of services not being registered with those build items and thus not being included in this "fast-path".

**Comment by Sanne** [comment]
I wasn't expecting to copy the service resources on the filesystem; shouldn't we rather keep the definitions within the state of the classloader? A "known services" map?

The filesystem copy is interesting as well, but I wonder how you're going to deal with duplicate service resource definitions.  What I meant to describe in #13256 is to copy to filesystem *exclusively* the resources from `StaticResourcesBuildItem`, while having a different plan for `ServiceProviderBuildItem`.

(but I'm open to change that, just saying I'm surprised and wondering how to handle it best)

**Comment by geoand** [comment]
> I wasn't expecting to copy the service resources on the filesystem; shouldn't we rather keep the definitions within the state of the classloader? A "known services" map?
> 
> The filesystem copy is interesting as well, but I wonder how you're going to deal with duplicate service resource definitions. What I meant to describe in #13256 is to copy to filesystem _exclusively_ the resources from `StaticResourcesBuildItem`, while having a different plan for `ServiceProviderBuildItem`.
> 
> (but I'm open to change that, just saying I'm surprised and wondering how to handle it best)

The current form of the PR should deal with the duplicates just fine. That's because all the instances of a service file are found during build time and copies out to the file system. Then at runtime when a resource is requested and found in this special section, it is loaded **only** from there and not the jars.

**Comment by geoand** [comment]
> I wasn't expecting to copy the service resources on the filesystem; shouldn't we rather keep the definitions within the state of the classloader? A "known services" map?

I am probably missing something here, but even if you do that, you still have to open the required jars to get the definition, no?

**Comment by geoand** [comment]
Closing this as https://github.com/quarkusio/quarkus/pull/13383 is a better approach

**Pull request closed without merging**
