### PR TITLE
Remove okhttp leftovers

### PR DESCRIPTION
**Pull request by geoand**
With #30480 in, we no longer need any of the okhttp stuff

### CODE REVIEW

**Comment by geoand** [comment]
cc @manusa

**Comment by manusa** [comment]
Remember OkHttp is still used (server-side) in the MockServer.
That's why I added the kubernetes-httpclient-okhttp to the enforcer rules instead of just okhttp.
Removing OkHttp from the MockServer will still need some time.

**Comment by geoand** [comment]
Do we still need it in the BOM though?

**Comment by manusa** [comment]
> Do we still need it in the BOM though?

That I don't know (I'm unsure why it was added to the BOM in first place)
Sincere the Mock Server is just used for testing, and OkHttp 4 should be binary compatible with v3 loading a different version probably won't have any undesired repercussion.

**Comment by geoand** [comment]
It was added to the BOM for the k8s client.

**Comment by geoand** [comment]
I'll just remove tthe commit that changed the BOM for now, as it needs more work

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand hmmm, do we have okhttp coming from `quarkus-test-infinispan-client`? That would be a very unpleasant surprise.

**Comment by geoand** [comment]
I agree... I don't have the time to look into it now which is why I removed the connit

**Pull request merged**
