### PR TITLE
Fix handling of deployment target when using quarkus-openshift

### LINKED ISSUE #29921: Deploy an application through `quarkus-openshift` extension is using `Quarkus-kubernetes` exetension
### Describe the bug

Quarkus version: Upstream (`999-SNAPSHOT`)
Openshift 4.11

Works as expected with Quarkus 2.14.3.Final

Description:

When I deploy a Quarkus application through `quarkus-openshift` I am getting the following error

Error:
```
13:13:30,663 INFO  oc: View details with 'oc describe <resource>/<name>' or list resources with 'oc get all'.
13:13:30,666 INFO  Running command: oc get events -n ts-nlmvicjjxv
13:13:31,520 INFO  oc: LAST SEEN   TYPE      REASON              OBJECT                     MESSAGE
13:13:31,520 INFO  oc: 76s         Normal    Scheduled           pod/app-1-build            Successfully assigned ts-nlmvicjjxv/app-1-build to ocp4-11-qvqg4-worker-0-sbvxp by ocp4-11-qvqg4-master-1
13:13:31,520 INFO  oc: 74s         Normal    AddedInterface      pod/app-1-build            Add eth0 [10.129.3.122/23] from openshift-sdn
13:13:31,520 INFO  oc: 74s         Normal    Pulled              pod/app-1-build            Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2cbbf6bff06a9897b3188b6df9705879bd99ba17ea7de8090fc68f2260451c04" already present on machine
13:13:31,520 INFO  oc: 74s         Normal    Created             pod/app-1-build            Created container git-clone
13:13:31,520 INFO  oc: 74s         Normal    Started             pod/app-1-build            Started container git-clone
13:13:31,520 INFO  oc: 63s         Normal    Pulled              pod/app-1-build            Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2cbbf6bff06a9897b3188b6df9705879bd99ba17ea7de8090fc68f2260451c04" already present on machine
13:13:31,520 INFO  oc: 63s         Normal    Created             pod/app-1-build            Created container manage-dockerfile
13:13:31,520 INFO  oc: 63s         Normal    Started             pod/app-1-build            Started container manage-dockerfile
13:13:31,520 INFO  oc: 62s         Normal    Pulled              pod/app-1-build            Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2cbbf6bff06a9897b3188b6df9705879bd99ba17ea7de8090fc68f2260451c04" already present on machine
13:13:31,520 INFO  oc: 62s         Normal    Created             pod/app-1-build            Created container sti-build
13:13:31,520 INFO  oc: 62s         Normal    Started             pod/app-1-build            Started container sti-build
13:13:31,520 INFO  oc: 73s         Normal    BuildStarted        build/app-1                Build ts-nlmvicjjxv/app-1 is now running
13:13:31,520 INFO  oc: 39s         Normal    BuildCompleted      build/app-1                Build ts-nlmvicjjxv/app-1 completed successfully
13:13:31,520 INFO  oc: 34s         Normal    Scheduled           pod/app-94764cfff-77pv2    Successfully assigned ts-nlmvicjjxv/app-94764cfff-77pv2 to ocp4-11-qvqg4-worker-0-sbvxp by ocp4-11-qvqg4-master-1
13:13:31,520 INFO  oc: 32s         Normal    AddedInterface      pod/app-94764cfff-77pv2    Add eth0 [10.129.3.123/23] from openshift-sdn
13:13:31,520 INFO  oc: 16s         Normal    Pulling             pod/app-94764cfff-77pv2    Pulling image "ts-nlmvicjjxv/app:1.0.0-SNAPSHOT"
13:13:31,520 INFO  oc: 16s         Warning   Failed              pod/app-94764cfff-77pv2    Failed to pull image "ts-nlmvicjjxv/app:1.0.0-SNAPSHOT": rpc error: code = Unknown desc = reading manifest 1.0.0-SNAPSHOT in 10.0.214.155:5000/ts-nlmvicjjxv/app: manifest unknown: manifest unknown
13:13:31,520 INFO  oc: 16s         Warning   Failed              pod/app-94764cfff-77pv2    Error: ErrImagePull
13:13:31,520 INFO  oc: 2s          Normal    BackOff             pod/app-94764cfff-77pv2    Back-off pulling image "ts-nlmvicjjxv/app:1.0.0-SNAPSHOT"
13:13:31,520 INFO  oc: 2s          Warning   Failed              pod/app-94764cfff-77pv2    Error: ImagePullBackOff
13:13:31,520 INFO  oc: 36s         Warning   FailedCreate        replicaset/app-94764cfff   Error creating: pods "app-94764cfff-" is forbidden: error looking up service account ts-nlmvicjjxv/app: serviceaccount "app" not found
13:13:31,520 INFO  oc: 34s         Normal    SuccessfulCreate    replicaset/app-94764cfff   Created pod: app-94764cfff-77pv2
13:13:31,520 INFO  oc: 37s         Normal    ScalingReplicaSet   deployment/app             Scaled up replica set app-94764cfff to 1

```

Workaround: 
Set you docker registry URL into your application.properties
`quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000`

### Expected behavior

Same behavior as Quarkus 2.14.3.Final

### Actual behavior

_No response_

### How to Reproduce?

`git clone git@github.com:quarkus-qe/quarkus-test-suite.git`

`cd /quarkus-test-suite/config`

`mvn clean verify -Dit.test=OpenShiftFileSystemConfigSecretConfigIT`

### Output of `uname -a` or `ver`

Linux fedora 6.0.11-200.fc36.x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #29921

### CODE REVIEW

**Review by geoand — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
@Sgitario mind taking a look as well?

**Review by Sgitario — COMMENTED** [review]
I tested these changes by using the OpenShift extension and some combinations of `.deploy` and `.deployment-target`:
- `quarkus.kubernetes.deploy=true`. It works as expected now! The OpenShift resources are installed.
- `quarkus.openshift.deploy=true`, this still works as expected. 
- `quarkus.kubernetes.deploy=true` and `quarkus.kubernetes.deployment-target=kubernetes`. The Kubernetes resources are installed, but also the BuildConfig resource, @iocanel is this expected or something we need to address? Anyway, this is not blocker.

**Comment by geoand** [comment]
> The Kubernetes resources are installed, but also the BuildConfig resource

You mean that `BuildConfig` is also applied to the cluster when `quarkus.kubernetes.deployment-target=kubernetes` is set?
If so, that sounds wrong...

**Comment by Sgitario** [comment]
> > The Kubernetes resources are installed, but also the BuildConfig resource
> 
> You mean that `BuildConfig` is also applied to the cluster when `quarkus.kubernetes.deployment-target=kubernetes` is set? If so, that sounds wrong...

Yep

**Comment by iocanel** [comment]
> I tested these changes by using the OpenShift extension and some combinations of `.deploy` and `.deployment-target`:
> 
> * `quarkus.kubernetes.deploy=true`. It works as expected now! The OpenShift resources are installed.
> * `quarkus.openshift.deploy=true`, this still works as expected.
> * `quarkus.kubernetes.deploy=true` and `quarkus.kubernetes.deployment-target=kubernetes`. The Kubernetes resources are installed, but also the BuildConfig resource, @iocanel is this expected or something we need to address? Anyway, this is not blocker.

I am not 100% sure what do you mean by `BuildConfig` being also applied.
Is the `BuildConfig` present inside the kubernetes.yml?

**Comment by iocanel** [comment]
> * `quarkus.kubernetes.deploy=true` and `quarkus.kubernetes.deployment-target=kubernetes`. The Kubernetes resources are installed, but also the BuildConfig resource, @iocanel is this expected or something we need to address? Anyway, this is not blocker.

The reason while the `BuildConfig` is created is because it is used by the container-image build (which is `container-image-openshift`). If you need to use use soemthing else, you need to be explicit about it. This is how it always worked (it's not related neihter with the current PR nor with the recent changes the PR is trying to address).

So, I'd say let's merge this one.

**Comment by geoand** [comment]
> So, I'd say let's merge this one.

I'll merge it, please follow up with anything else needed

**Pull request merged**
