### PR TITLE
Update to the latest OpenTelemetry release

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by kenfinnigan** [comment]
I don't think the test failure is related at all to the OpenTelemetry update.

Is it a known failure?

**Comment by gsmet** [comment]
No it's a brand new one but I don't think it's related. Let me dig into the logs.

**Comment by gsmet** [comment]
@geoand stay on PTO please but when you're back, it's another occurrence:
```
2021-08-17T19:37:29.9850663Z 2021-08-17 19:37:29,957 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /simple/form-map failed, error id: e3672c38-a3f4-4013-876e-bdeec84f42f8-2: java.lang.NullPointerException
2021-08-17T19:37:29.9853878Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers.getTarget(ContextProducers.java:108)
2021-08-17T19:37:29.9857459Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers.resourceInfo(ContextProducers.java:90)
2021-08-17T19:37:29.9861602Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.create(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.zig:163)
2021-08-17T19:37:29.9866116Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.create(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.zig:194)
2021-08-17T19:37:29.9869160Z 	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:68)
2021-08-17T19:37:29.9870910Z 	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:33)
2021-08-17T19:37:29.9874045Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.arc$delegate(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.zig:60)
2021-08-17T19:37:29.9879272Z 	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.getResourceMethod(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.zig:135)
2021-08-17T19:37:29.9884187Z 	at io.quarkus.resteasy.reactive.server.test.simple.ResourceInfoInjectingFilter.filter(ResourceInfoInjectingFilter.java:19)
2021-08-17T19:37:29.9888838Z 	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:40)
2021-08-17T19:37:29.9893747Z 	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:8)
2021-08-17T19:37:29.9898151Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:133)
2021-08-17T19:37:29.9971999Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:538)
2021-08-17T19:37:29.9974080Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2021-08-17T19:37:29.9976066Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2021-08-17T19:37:29.9977965Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2021-08-17T19:37:29.9980149Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2021-08-17T19:37:29.9982705Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-08-17T19:37:29.9984394Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/issues/19471 to track it.

**Comment by geoand** [comment]
Perhaps if has time before I get back, @stuartwdouglas can have a look

**Pull request merged**
