### PR TITLE
Bump testcontainers to 1.16

### PR DESCRIPTION
**Pull request by geoand**
Supersedes: https://github.com/quarkusio/quarkus/pull/18873

_See the first commit for why this works_

### CODE REVIEW

**Comment by famod** [comment]
Good catch! Let me double-check locally in Ubuntu WSL and Windows natively...

**Review by famod — APPROVED** [review]
A lot of duplication in those processors but I guess that could be some refactoring task for later.

What I find very interesting is that with latest Docker Desktop 3.6.0, I cannot run those invoker tests **on `main`** anymore (both in WSL2 and Windows natively) because of:
```
Can not connect to Ryuk at localhost:49156: java.net.ConnectException: Connection refused: connect
```
I'm pretty sure I wasn't seeing that with 3.5.x.

**But** with this change, I can run those tests again! So I propose to backport this, ideally even to 2.1 if feasible.

**Comment by famod** [comment]
PS: I was surprised `start-containers` profile is disabled on Windows. This might have been needed in CI at some point (GH windows runner does not support Linux containers), but AFAICS Windows jobs are not even using `-Dstart-containers`. (/cc @gsmet)

When I force-enable that profile on Windows, then the surefire part runs fine, but failsafe hangs very early on.
`jstack` showed this:
```
"main" #1 prio=5 os_prio=0 cpu=6578.13ms elapsed=305.94s tid=0x000001dbf35f5000 nid=0x23e4 runnable  [0x0000009cebefd000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(java.base@11.0.10/Native Method)
        at java.io.FileInputStream.read(java.base@11.0.10/FileInputStream.java:279)
        at java.io.BufferedInputStream.read1(java.base@11.0.10/BufferedInputStream.java:290)
        at java.io.BufferedInputStream.read(java.base@11.0.10/BufferedInputStream.java:351)
        - locked <0x00000006d7c588e8> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(java.base@11.0.10/FilterInputStream.java:107)
        at java.util.Properties$LineReader.readLine(java.base@11.0.10/Properties.java:502)
        at java.util.Properties.load0(java.base@11.0.10/Properties.java:418)
        at java.util.Properties.load(java.base@11.0.10/Properties.java:407)
        - locked <0x00000006d7c5a9f0> (a java.util.Properties)
        at org.codehaus.plexus.languages.java.jpms.MainClassModuleNameExtractor.extract(MainClassModuleNameExtractor.java:102)
        at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePaths(LocationManager.java:234)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.newStartupConfigWithModularPath(AbstractSurefireMojo.java:2011)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createStartupConfiguration(AbstractSurefireMojo.java:1889)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createForkStarter(AbstractSurefireMojo.java:2374)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1310)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.10/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.10/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.10/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.10/Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by geoand** [comment]
Thanks for checking!

Yup, there is plenty of duplication, but that's the price we pay for dev services.
It is probably possible to refactor some of the common stuff and we should likely do it at some point.

As for backporting, I dunno really... The first commit should likely be backported, but the version bump I don't know ...

I'll leave it up to @gsmet to decide

**Comment by geoand** [comment]
The failures are genuine and due to the fact that I mistakenly added a
change to Redis.
I'll update the PR soon

**Comment by famod** [comment]
> What I find very interesting is that with latest Docker Desktop 3.6.0, I cannot run those invoker tests **on `main`** anymore (both in WSL2 and Windows natively) because of:
> 
> ```
> Can not connect to Ryuk at localhost:49156: java.net.ConnectException: Connection refused: connect
> ```
> 
> I'm pretty sure I wasn't seeing that with 3.5.x.
> 
> **But** with this change, I can run those tests again! So I propose to backport this, ideally even to 2.1 if feasible.

FTR, this is a general Docker Desktop issue on Windows: https://github.com/docker/for-win/issues/11584

testcontainers 1.16 does try to work around that problem via https://github.com/testcontainers/testcontainers-java/pull/4263 but it's not like nothing works anymore with <1.16, so a backport would be nice but not at all critical.

**Pull request merged**
