### PR TITLE
Fix Reactive Messaging build time wiring connector attribute types

### PR DESCRIPTION
**Pull request by ozangunalp**
Support all primitive types detecting connector attributes

### CODE REVIEW

**Comment by gsmet** [comment]
Is it something we should backport?

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
No, I don't believe we need to backport. The initial set was composed of the types that are actually used in the supported connectors.

**Comment by ozangunalp** [comment]
The issue happened with the `reactive-messaging-http` and the build fails if it is available on the classpath.

**Comment by cescoffier** [comment]
Oh! I was pretty sure to have checked that one too.
Ok, so, yes, need backport.

**Pull request merged**
