### PR TITLE
Testing reproducers

### PR DESCRIPTION
**Pull request by Ladicek**
Follows-up to #35124

Adds reproducers for the remaining issues from https://github.com/orgs/quarkusio/projects/30/:

- #8446 
- #13261 
- #34099 
- #42000 
- #42006 
- #44320

### CODE REVIEW

**Comment by Ladicek** [comment]
Probably best to review each commit in isolation, because an aggregate view shows strange changes. I renamed the `kotlin` integration tests module to `kotlin-maven-invoker` and then renamed `kotlin-serialization` to `kotlin`, because that uses the standard `@QuarkusTest` facility and so deserves the shorter name.

**Review by geoand — APPROVED** [review]
Really nice!

**Review by holly-cummins — APPROVED** [review]
Thank you!

**Comment by holly-cummins** [comment]
4 of the 6 of these are resolved by https://github.com/quarkusio/quarkus/pull/34681. It was extremely satisfying (and delightfully easy) to just remove the `@Disabled` annotation as part of the commit. :)

**Pull request merged**
