### PR TITLE
Add inject example as a comment & rm the tests in rest-client codestart

### LINKED ISSUE #24553: Sample project with rest-client-codestart has test failures
### Describe the bug

sample project with rest-client-codestart has test failures

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.049 s <<< FAILURE! - in io.quarkus.qe.MyRemoteServiceTest
[ERROR] io.quarkus.qe.MyRemoteServiceTest.testExtensionsRestClientEndpoint  Time elapsed: 0.579 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <REST Client> but was: <>
	at io.quarkus.qe.MyRemoteServiceTest.testExtensionsRestClientEndpoint(MyRemoteServiceTest.java:26)
```

Test fails on `Assertions.assertEquals("REST Client", extension.shortName);` check
https://github.com/quarkusio/quarkus/blob/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/rest-client-codestart/java/src/test/java/org/acme/MyRemoteServiceTest.java#L26

There is no `shortName` defined for quarkus-rest-client extension, see https://stage.code.quarkus.io/api/extensions?id=io.quarkus:quarkus-rest-client

To resolve this either test in the codestart needs to be adjusted or metadata for code.quarkus need to be enhanced to provide `shortName` for quarkus-rest-client extension

cc @ia3andy / @maxandersen 

### Expected behavior

sample project with rest-client-codestart has no failures

### Actual behavior

sample project with rest-client-codestart has test failures

### How to Reproduce?

 - Run `mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:create -DprojectGroupId=io.quarkus.qe -DprojectArtifactId=rest-client -DprojectVersion=1.0.0-SNAPSHOT -Dextensions=rest-client -DquarkusRegistryClient=false`
   -  `-DquarkusRegistryClient=false` is needed because of https://github.com/quarkusio/quarkus/issues/24552
 - Run `mvn clean verify -f rest-client`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ia3andy**
Follow up on https://github.com/quarkusio/quarkus/pull/24544

Fixes #24553 

Generally speaking, having a test on a remote rest endpoint is a bad practice. In this case, it is more testing the rest service and the rest-client implementation than the actual code. Mocking might be a better option but let's leave this choice open to the developer. I've added the injection code snippet as a comment directly in the service and removed the test.

### CODE REVIEW

**Comment by ia3andy** [comment]
@gsmet previous versions are also broken and the CI will fail during releases. To backport this fix, you might need to remove the revert from @aloubyansky PR (or also apply it). Feel free to ask me to split this in two commits (revert + fix).

**Comment by maxandersen** [comment]
I must have missed something - why are we even mentioning code quarkus api and especially staging in our users generated projects?

**Comment by ia3andy** [comment]
> I must have missed something - why are we even mentioning code quarkus api and especially staging in our users generated projects?

@xstefank needed an example to show off the rest client which was using restcountries.eu, better use our own apis. Then I 
 made the choice to prefer the stage for this kind of usage.

**Review by aloubyansky — APPROVED** [review]

**Comment by maxandersen** [comment]
Our own api - okey; not that relevant for users though. Using some more commonly known api would be better 

But why stage. Then that is no longer a stage. It's part of what users rely on. 

Much better to use actual api endpoints that does not increase stage to be something every example now use or even refer.

**Comment by ia3andy** [comment]
> Our own api - okey; not that relevant for users though. Using some more commonly known api would be better
> 
> But why stage. Then that is no longer a stage. It's part of what users rely on.
> 
> Much better to use actual api endpoints that does not increase stage to be something every example now use or even refer.

I am conflicted on this matter. While I would indeed prefer to have a "nice" endpoint for users, it seemed best not to charge it with non essential requests. Since @rsvoboda was right and the extension endpoint doesn't have a lot of tracking, I won't argue if we decide to use prod instead.

**Comment by ia3andy** [comment]
I believe the error is unrelated, should I merge?

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
The error is unrelated, but I restarted the failed jobs just in case 😉

**Pull request merged**
