### PR TITLE
Simplify kubernetes tests

### PR DESCRIPTION
**Pull request by geoand**
Remove the unnecessary version retrieval method that was added
and use the Version of the quarkus-builder module class that
does the same thing

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Excellent!

**Comment by geoand** [comment]
I saw someone use it, so I knew I need to copy it :)

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand I promoted it to get an earlier CI result as I would like to have that one in CR1.

**Comment by geoand** [comment]
OK thanks

**Pull request merged**
