### PR TITLE
Update to RestEasy 4.5.11

### PR DESCRIPTION
**Pull request by sberyozkin**
CC @ronsigal

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by sberyozkin** [comment]
@gsmet I'm sorry - I've realized it would be good to back it up with a test as well, pushing now

**Comment by sberyozkin** [comment]
`404` is a spec required status if the path param is wrong

**Comment by sberyozkin** [comment]
Something is failing in `quarkus-jdbc-mysql-deployment`, don't think it is related

**Comment by ronsigal** [comment]
There are test failures that look like

>2021-04-22T14:17:17.7937489Z 2021-04-22 14:17:17,443 ERROR [io.und.req.io] (executor-thread-1) Exception handling request 7528cbc8-1908-4fd6-af76-4d711371dee4-2 to /test/openapi/responses/v2: com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface javax.servlet.http.HttpServletRequest, interface javax.servlet.ServletRequest] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.

Is this a RESTEasy problem? The code that generates the proxy (ContextParameterInjector.createProxy()) has changed a bit:
```
         Class[] intfs = {rawType};
         ...
         return Proxy.newProxyInstance(clazzLoader, intfs, new GenericDelegatingProxy());
```
is now
```
         Object delegate = factory.getContextData(rawType, genericType, annotations, false);
         Class<?>[] intfs = computeInterfaces(delegate, rawType);
         ...
         return Proxy.newProxyInstance(clazzLoader, intfs, new GenericDelegatingProxy());
```
I.e., there's a difference in how the proxy is created, but the fact that a proxy is created isn't new.

**Comment by sberyozkin** [comment]
Hi Ron @ronsigal 

OK, so
```
Proxy class defined by interfaces [interface javax.servlet.http.HttpServletRequest, interface javax.servlet.ServletRequest...
```
That is the same problem which we saw with `4.5.10` though showing itself in a different way ? What I don't understand is, I run for example, `integration-tests/oidc-code-flow` before opening this PR, in a native mode, and it was fine - not sure why it fails with `integration-tests/main`

**Comment by ronsigal** [comment]
>the same problem which we saw with 4.5.10 though showing itself in a different way ?

Well, I was hoping it wasn't. The problem in 4.5.10 was that I added to ContextParameterInjector a reference to ServletOutputStream, which is now moved to another class that should get loaded only if the application code has something like
```
@GET 
public void method(@Context HttpServletResponse response) {...}
```
In this case, it looks like there's a reference to HttpServletResponse somewhere. Maybe it's this:
```
package io.quarkus.it.rest;
...
@Path("/test")
public class TestResource {

    @Context
    HttpServletRequest request;
```
But then HttpServletRequest and ServletRequest must be available.

**Comment by sberyozkin** [comment]
@ronsigal I see - yeah, it might related to the fact the proxy interfaces are calculated dynamically now... @stuartwdouglas Hi Stuart can you please check [this comment](https://github.com/quarkusio/quarkus/pull/16722#issuecomment-825033863) above from Ron ? What do you think ? thanks

**Comment by ronsigal** [comment]
But I ran 
```
mvn clean verify -pl integration-tests/main -Dnative
```
and it passed. Aarrgghh.

**Comment by sberyozkin** [comment]
@ronsigal Indeed sometimes it happens - fails in CI only, lets see if Stuarts spots something

**Comment by stuartwdouglas** [comment]
You need to create a @BuildStep that produces a io.quarkus.deployment.builditem.nativeimage.NativeImageProxyDefinitionBuildItem with the correct proxy interfaces.

**Comment by sberyozkin** [comment]
Hi Stuart, @stuartwdouglas, thanks
Hi  Ron, does `computeInterfaces(delegate, rawType);` produce the limited set of interfaces, what are they - I can update `quarkus-resteasy` to register them in a native mode

**Comment by ronsigal** [comment]
Thanks, Stuart.

re: "what are they - I can update quarkus-resteasy to register them in a native mode"

@sberyozkin, in general, the interfaces are implementation dependent. E.g., undertow could create an object that implements HttpServletRequest but other interfaces as well. The history of this is that recently, Andy McCright submitted the change because Open Liberty needs it internally. Based on the error message, though, it looks like the interfaces in this case are javax.servlet.http.HttpServletRequest and javax.servlet.ServletRequest. As long as the environment is known, the interfaces are knowable.

**Comment by sberyozkin** [comment]
@ronsigal Hi Ron, I'll create a branch on top of this PR's branch and see how CI progresses in my fork

**Comment by sberyozkin** [comment]
I've tried adding the build item [here](https://github.com/quarkusio/quarkus/compare/1.13...sberyozkin:resteasy_4.5.11_build_problem?expand=1#diff-eaddb26d3c459ba20bbc7097586a88eea8bdab6cd71028a7aeca112690481ae3) and the CI build is [here](https://github.com/sberyozkin/quarkus/actions/runs/782985099), lets see how it goes

**Comment by sberyozkin** [comment]
The [latest CI build](https://github.com/sberyozkin/quarkus/actions/runs/783440746) in my fork fails with 
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --user 1001:121 --rm -v /home/runner/work/quarkus/quarkus/integration-tests/jpa-without-entity/target/quarkus-integration-test-jpa-without-entity-999-SNAPSHOT-native-image-source-jar:/project:z quay.io/quarkus/ubi-quarkus-native-image:21.0-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-
...

java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
```

`integration-tests/main` has passed since `HttpServletRequest` is there on the classpath - but it is not in other integration tests.
So, the code I added
```
    @BuildStep
    void prepareServletApiProxy(BuildProducer<NativeImageProxyDefinitionBuildItem> proxyProducer) {

        proxyProducer.produce(new NativeImageProxyDefinitionBuildItem(
                HTTP_SERVLET_REQUEST_NAME.toString(), SERVLET_REQUEST_NAME.toString()));
    }
```
Should only be run if `HttpServletRequest`/`ServletRequest`. I don't if it is possible yet.

**Comment by sberyozkin** [comment]
I may've put that code into the wrong extension - I tried `quarkus-resteasy-server-common` but I think now it should be `quarkus-undertow`, I'll retry

**Comment by sberyozkin** [comment]
Hi @ronsigal 

Moving the native proxy build item code to `quarkus-undertow` has helped, and it passed, nearly :-). The failure has happened in `quarkus-keycloak-authorization` which is somewhat unexpected, but then it uses Resteasy Client internally:
```
Proxy class defined by interfaces [interface io.vertx.core.http.HttpServerRequest, interface io.vertx.core.streams.ReadStream] not found. Generating proxy classes at runtime is not supported.
``` 
So I've updated my branch to get `quarkus-keycloak-authorization` supporting the dynamic proxy for these interfaces. Lets see how it goes.

But I wonder, if it is really backportable - i.e - I'm not sure if the custom user code is not going to fail in a native mode. For example,  in case of `keycloak-authorization`, `io.vertx.core.http.HttpServerRequest` and  `io.vertx.core.streams.ReadStream` are certainly not related to Resteasy but yet they have been picked up by the dynamic proxy generation code - so it is quite dynamic.

So I'm thinking this kind of enhancement to do with dynamic proxies is possibly more of a Quarkus 2.0.x line material - at least there it is still all very much in the active development as opposed to 1.13.
thanks

**Comment by ronsigal** [comment]
Hey @sberyozkin,

First of all, don't think that I wasn't aware that you were hard at work over the weekend. ;-)

Now, let me preface my response by saying that I don't know what I'm talking about, with respect to Quarkus. **However**, the thing that worries me is that, if the Quarkus tests can fail because of this proxy thing, then any Quarkus application is subject to the same problem. Making everyone do this @BuildStep thing to use RESTEasy sounds pretty bad. So, yes, @asoldano, I would be in favor of backing out the proxy interface thing at least in RESTEasy 4.5.12.Final. 

My question is, what about RESTEasy 4.6.1.Final and Quarkus 2? There seem to be one or two other problems that have to be fixed in Quarkus before it will work with 4.6.1.Final in its current (unreleased) state. One of them is https://issues.redhat.com/browse/QUARKUS-973 "Remove RestClientRecorder.hackAroundExtension()". One option would be to leave the proxy change in 4.6.1.Final and expect that Quarkus will be able to deal with it. @sberyozkin, I guess my basic question is: Do you think it's likely that Quarkus will be about to have a general, convenient workaround for this proxy thing? If not, maybe the thing should just go away, although that's not ideal. A third alternative would be to back the proxy thing (I should find a better name for it) out of 4.6.1.Final to make it easier to upgrade the Quarkus main branch, and then put it back in later. WDYT?

-Ron

**Comment by ronsigal** [comment]
Ah, @sberyozkin, I just read your latest email where you point out that we've already released 4.5.11.Final with the "proxy thing" change. Hmmm. The fact is, I never added the releases of 4.5.10.Final and 4.5.11.Final to https://resteasy.github.io, so, in a sense, they aren't officially released.I think. @asoldano, WDYT?

**Comment by asoldano** [comment]
@ronsigal ... kind of ;-) Next time we might want to go with a CR release on maven repo first, have a quarkus ci run here and then release the final.

**Comment by ronsigal** [comment]
@asoldano, CR release is a great idea. Yes. In fact, that's exactly what I was looking for, since (apparently) I could run the Quarkus testsuite on my own fork on GitHub.

But for now, I infer you're not enthusiastic about backing out the change in a 4.5.12.Final?

**Comment by sberyozkin** [comment]
Hey @ronsigal, and @asoldano   
I just added a few lines of code and let my fork run the CI :-)
And just an update from my fork CI build, https://github.com/sberyozkin/quarkus/runs/2438404476?check_suite_focus=true, a few tests are failing including the problem with `HttpServletRequest/ServletRequest` and also 
```
Error:    RestClientITCase>RestClientTestCase.testMicroprofileCdiClientHeaderPassing:104 1 expectation failed.
Expected header "Content-Type" was not "application/json", was "application/json;charset=UTF-8". Headers are:
```
etc.

So I think we should close this PR.
Good question about Resteasy 4.6.x and Quarkus 2 - I haven't dealt with integrating RestEasy into Quarkus - so I don't know. I think Guillaume @gsmet would have a better idea when it will come to the actual integration of the next 4.6.x into Quarkus 2. Somehow we will sort it out :-)

By the way, if you publish snapshots then you can just update `bom/application/pom.xml` to for ex `4.5.x-SNAPSHOT` and check CI in your fork without even doing the CR releases. 

Thanks

**Comment by ronsigal** [comment]
re: "application/json;charset=UTF-8"

Hmmm, that sounds like something we should have fixed a long time ago, since, IIRC, JSON always uses UTF-8.

re: "actual integration of the next 4.6.x into Quarkus 2"

Ok, I'll contact @gsmet  before releasing 4.6.1, so we're all on the same page.

re: "if you publish snapshots"

I'm not sure what "publish" means here ...

**Comment by sberyozkin** [comment]
Hi @ronsigal sorry, just meant that if they are available in the snapshot repository - but I'm not sure if `bom/application/pom.xml` can refer to snapshots - it might need to be updated to enable them; yes please ping Guillaume - he may recommend who else knows about the integration details
thanks

**Comment by stuartwdouglas** [comment]
This should not be in the Undertow subsystem, it should be in https://github.com/quarkusio/quarkus/blob/04aa95308cc3296ec89871932cfae101daf9d46a/extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyServletProcessor.java#L97

This means it is only created if Servlet is actually present.

**Comment by sberyozkin** [comment]
Hi Stuart @stuartwdouglas, oh I see, thanks, though, please see [this comment](https://github.com/quarkusio/quarkus/pull/16722#issuecomment-826787238) - `quarkus-keycloak-authorization` test fails with 2 Vert.x interfaces being picked up hence I'm thinking it is not safe continue with backporting - but it is good where to add Servlet classes to support the dynamic proxies :-)

**Pull request closed without merging**
