### PR TITLE
Remove wildcard exclusion from `quarkus-grpc-protoc-plugin` for now to fix devmode ITs

### PR DESCRIPTION
**Pull request by famod**
Short-term alternative to #21593 (which is incomplete).

Passed on my machine:
```
mvn clean install -pl extensions/grpc/codegen -amd -pl '!integration-tests/gradle/' -pl '!integration-tests/maven/'
```

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
This will make some other tests fail, I wrote about it not long ago in a thread about CI lying

**Comment by famod** [comment]
> This will make some other tests fail, I wrote about it not long ago in a thread about CI lying

Ah, I was actually looking for that but I couldn't find it anymore. "lying" was the crucial clue! https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/.E2.9C.94.20CI.20seems.20to.20be.20lying
Checking...

**Comment by famod** [comment]
`mvn clean install -pl extensions/grpc/deployment -Dtest=GrpcDevModeTest#testProtoFileChangeReload` is fine on my machine. (on this branch) 🤷‍♂️

**Comment by famod** [comment]
Superseded by #21601

**Pull request closed without merging**
