### PR TITLE
Leverage AuthenticationException to simplify exception handling checks

### PR DESCRIPTION
**Pull request by michalvavrik**
Simplify 3 IF conditions.

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Comment by michalvavrik** [comment]
I'm pretty sure failures are unrelated as otherwise, `JVM Tests - JDK 11` would also fail.

**Comment by sberyozkin** [comment]
Strange error with security-jdbc:
```
2023-02-23T13:11:25.0803953Z 2023-02-23 13:11:24,784 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to %s failed, error id: %s [Error Occurred After Shutdown]: java.lang.RuntimeException: org.wildfly.security.auth.server.RealmUnavailableException: ELY01050: Could not execute query "SELECT u.password, roles FROM test_user u WHERE u.username=?"
2023-02-23T13:11:25.0805106Z 	at io.quarkus.elytron.security.runtime.ElytronPasswordIdentityProvider$1.get(ElytronPasswordIdentityProvider.java:62)
2023-02-23T13:11:25.0806009Z 	at io.quarkus.elytron.security.runtime.ElytronPasswordIdentityProvider$1.get(ElytronPasswordIdentityProvider.java:43)
2023-02-23T13:11:25.0872488Z 	at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl$1$1$1$1.run(QuarkusIdentityProviderManagerImpl.java:58)
2023-02-23T13:11:25.0904737Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2023-02-23T13:11:25.0905512Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
.......
2023-02-23T13:11:25.1071836Z Caused by: org.h2.jdbc.JdbcSQLDataException: Invalid value "3" for parameter "columnIndex" [90008-214]
2023-02-23T13:11:25.1072273Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
2023-02-23T13:11:25.1072694Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477
.......

```

The interesting message there is that `[Error Occurred After Shutdown]`, not sure what that means, there might be some race condition, the server is being shutdown while security jdbc is still doing something.

I also think it is not related, can you rebase though just to give it another try, as a newer wildfly-security version is available on main ?

**Comment by michalvavrik** [comment]
Done. `BuildIT` is a flaky test.

**Comment by sberyozkin** [comment]
Thanks

**Pull request merged**
