### PR TITLE
Add Minio client extension

### LINKED ISSUE #13166: Minio Extension
**Describe the extension**
[Minio](https://min.io/) is a Kubernetes Native, high performance object storage.

It has a java client library that can easily be integrated to Quarkus.

I have an extension that works both in OpenJDK and Native mode. See https://github.com/jtama-op/quarkus/commit/ef5142948ee1c5fb170fdc45fe89669fec3cc723

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
```properties
# Add your application.properties here, if applicable.
quarkus.minio.url=http://localhost:9000/
quarkus.minio.access-key=YOURACCESSKEY
quarkus.minio.secret-key=YOURSECRETKEY
```

**Additional context**

Minio being K8s native it can only be installed locally through containers. I'm not sure what kind of automtic testing I can provide. The extension is used and working on a project though I know it's not testing ;). Help or ideas would be much appreciated on this point.

### PR DESCRIPTION
**Pull request by jtama**
Additionally : 

Minio being K8s native it can only be installed locally through containers. I'm not sure what kind of automtic testing I can provide. The extension is used and working on a project though I know it's not testing ;). Help or ideas would be much appreciated on this point.

Closes #13166

### CODE REVIEW

**Comment by jtama-op** [comment]
Build fails on enforcer rule 
`Found Banned Dependency: org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final`

This dependency comes from io.quarkus:quarkus-core which is pulled by the runtime module... Don't see what I can do about it...

**Comment by gsmet** [comment]
This is something that should be in the Quarkiverse. See https://github.com/quarkiverse/quarkiverse/wiki for a nice introduction.

/cc @aloubyansky @gastaldi

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkiverse-minio. You should have push permission @jtama-op . Closing this PR now

**Comment by jtama-op** [comment]
Ok, I will push code there. Any idea on the testability issue ?

**Comment by gastaldi** [comment]
I think the best is to start a Kubernetes instance. 

See how that is done for the Kubernetes Client library:  https://github.com/fabric8io/kubernetes-client/blob/master/.github/workflows/e2e-tests.yml

**Pull request closed without merging**
