### PR TITLE
OIDC fixes

### PR DESCRIPTION
**Pull request by FroMage**
This PR fixes a few issues I've had with OIDC and JWT:

- Store the tenant ID in the generated JWT IdToken for github/facebook, so we know where it came from
- Store the `IdentityProvider` in the Vert.x Context during authentication so that JWT and OIDC don't try to participate in each-other's authentication, which happened to me and cause mayhem
- Do not authenticate disabled OIDC tenants
- Store the Vert.x context in the `tokenAuthenticationRequest` like other extensions do, otherwise JWT will create the request, not put the Vert.x context in it, and OIDC will have an NPE because it expects it there.
- Allow disabling JWT challenge (#22404)

Taken over from #22200

### CODE REVIEW

**Comment by sberyozkin** [comment]
@FroMage Steph, I don't agree with this fix, I've already said that IMHO we need to fix it at a different level, hence #22206 is open, I don't think we should be adding specific tweaks around the combination of MP-JWT and OIDC authenticators

**Review by sberyozkin — CHANGES_REQUESTED** [review]
This issue has to be resolved via a generic solution, see #22206.
Also, as already explained, encoding the tenant id in the faked token is no longer necessary - I merged PR which will make it available as a RoutingContext property - and it is already available as a SecurityIdentityAugmentor property - and it will work with or without the faked ID token.

I've been planning to look at #22206 but got delayed a bit with the Keycloak-X work

**Comment by sberyozkin** [comment]
@FroMage Steph, please trust it will all work as expected once #22206 is resolved, including the challenges when both MP JWT and OIDC web-app are active :-)

**Comment by FroMage** [comment]
> and it is already available as a SecurityIdentityAugmentor property

I just tried this and there's no such property ATM. When did you merge this?

**Comment by sberyozkin** [comment]
@FroMage, please see #22163

**Comment by FroMage** [comment]
OK, I must be thick. Where in that PR are you setting the `SecurityIdentity` attribute? I can't see it. I also can't get an `OidcSession` in my security augmenter because there's no context yet.

**Comment by sberyozkin** [comment]
@FroMage #22163 makes sure it is avail in `RoutingContext` but I've noticed now you may be asking about `SecurityIdentity` - this is set here, https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java#L187

**Comment by FroMage** [comment]
Aha, OK, my bad, I can see it, thanks. I can drop that commit then.

**Comment by sberyozkin** [comment]
@FroMage Sure, so the `tenant-id` is there; but like I said, IMHO we need to have a generic solution to this specific issue of choosing Mp JWT and OIDC web-app mechanisms, I'll have a look asap

**Comment by gsmet** [comment]
@sberyozkin I'm assigning this one to you. I'll let you determine what is the proper fix and if this PR should be merged or not (or adjusted).

**Comment by sberyozkin** [comment]
#22483 attempts to provide a generic solution to the problem Steph has tried to address here, so let me close this PR for now

**Pull request closed without merging**
