### PR TITLE
Support "INHERIT" for quarkus.jib.jvm-entrypoint and quarkus.jib.native-entrypoint

### LINKED ISSUE #28071: support quarkus.jib.jvm-entrypoint=INHERIT
### Description

https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin

Both jib-maven-plugin and jib-gradle-plugin support jib.container.entrypoint=INHERIT to inherit container entrypoint from base image, but quarkus-container-image-jib always overrides container entrypoint.

### Implementation ideas

https://github.com/quarkusio/quarkus/blob/main/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L382

When entrypoint is `["INHERIT"]`,  call `jibContainerBuilder.setEntrypoint(null).setProgramArguments(jibConfig.jvmArguments)`.

### PR DESCRIPTION
**Pull request by Dieken**
jib-maven-plugin and jib-gradle-plugin both support this option to inherit entrypoint from base image, so make Quarkus learn it.

Resolves https://github.com/quarkusio/quarkus/issues/28071

### CODE REVIEW

**Comment by geoand** [comment]
Interesting!

Can you also update one of the [integration tests](https://github.com/quarkusio/quarkus/tree/main/integration-tests/container-image/maven-invoker-way/src/it) to use this property so we can properly make test it?

**Comment by Dieken** [comment]
> Interesting!
> 
> Can you also update one of the [integration tests](https://github.com/quarkusio/quarkus/tree/main/integration-tests/container-image/maven-invoker-way/src/it) to use this property so we can properly make test it?

I added an integration test, `./mvnw -f integration-tests/container-image clean install` passed but `./mvnw -f integration-tests/container-image clean install -Dnative` failed,  I can't tell whether the former really passed and why the latter failed, the log is too few and ambiguous.

**Comment by geoand** [comment]
Did you try the tips mentioned [here](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#maven-invoker-tests)? Essentially you should use `-Dstart-containers -Dtest-containers`

**Review by geoand — APPROVED** [review]

**Comment by Dieken** [comment]
> Did you try the tips mentioned [here](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#maven-invoker-tests)? Essentially you should use `-Dstart-containers -Dtest-containers`

You are right, these properties start the real tests.

These tests all passed, I didn't run all tests because it's too slow.
```
./mvnw clean install -f integration-tests/container-image/maven-invoker-way -Dinvoker.test=container-build-jib-appcds -Dstart-containers -Dtest-containers

./mvnw clean install -f integration-tests/container-image/maven-invoker-way -Dinvoker.test=container-build-jib-appcds -Dstart-containers -Dtest-containers -Dnative

./mvnw clean install -f integration-tests/container-image/maven-invoker-way -Dinvoker.test=container-build-jib-inherit -Dstart-containers -Dtest-containers

./mvnw clean install -f integration-tests/container-image/maven-invoker-way -Dinvoker.test=container-build-jib-inherit -Dstart-containers -Dtest-containers -Dnative
```

`container-build-jib-inherit` is modified from `container-build-jib-appcds`.

So I think everything should be ok :-)

**Comment by geoand** [comment]
Looks good, thanks!

**Comment by Dieken** [comment]
https://github.com/quarkusio/quarkus/wiki/Release-Planning

2.14 will be released in Nov. , could you cherry-pick this commit into 2.13? This is a very small but useful enhancement for me :-)

@geoand

**Comment by geoand** [comment]
Yeah, I support that would be fine.

**Comment by Dieken** [comment]
Quarkus 2.13.0 is released,  could you backport this to 2.13.1? Thanks!

**Comment by geoand** [comment]
That's the point of the label :)

**Pull request merged**
