### PR TITLE
SmallRye GraphQL 1.9.3, test for Deprecated annotation

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by jmartisk** [comment]
I see that recent other PRs targeting 2.16 (like https://github.com/quarkusio/quarkus/pull/31471) have similar issues, so it probably isn't relevant to this upgrade. But yeah it sucks :/

**Comment by gsmet** [comment]
Yeah I just noticed that and I have the same issue with the backport PR I created. I have no idea what's going on, GitHub gives no clue as to what is the issue...

**Comment by gsmet** [comment]
I'm trying a backport of https://github.com/quarkusio/quarkus/pull/31274 in my backport PR. Let's see how it goes.

**Comment by gsmet** [comment]
Rebased to get the latest CI fixes.

I'll wait for this PR before releasing.

**Pull request merged**
