### PR TITLE
fix issue with openJDK11-alpine

### PR DESCRIPTION
**Pull request by survivant**
there was a issue in the regex to detect correctly JAVA_MAJOR version

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
Actually, we'll need to have the commits squashed

**Comment by gsmet** [comment]
Rebased, squashed and force pushed.

**Comment by geoand** [comment]
Thanks @gsmet

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
