### PR TITLE
Smallrye GraphQL 2.5.0

### PR DESCRIPTION
**Pull request by jmartisk**
+ test coverage for federation batch resolving

### CODE REVIEW

**Comment by jmartisk** [comment]
Also cc @robp94 , you authored some parts of this

**Comment by sberyozkin** [comment]
Hey @jmartisk Thanks very much.

I wonder if we should have 2 PRs, one - bumping the version, some tests, and then a dedicated one related to a new release noteworthy feature ?

**Comment by jmartisk** [comment]
> Hey @jmartisk Thanks very much.
> 
> I wonder if we should have 2 PRs, one - bumping the version, some tests, and then a dedicated one related to a new release noteworthy feature ?

I squashed them into one because the OIDC client integration also relies on new functionality in SR-GQL 2.5.0. Possibly we can split it, but I don't see a strong reason why. One of the PRs would depend on merging the other first.

**Comment by sberyozkin** [comment]
@jmartisk Right, the first PR, dealing with the `smallrye-graphql` version bum only would be merged, and then a new PR introducing `oidc-client-graphql` would be opened, with the label highlighting its introduction - IMHO it is worth it

**Comment by jmartisk** [comment]
Ok then; I've removed the commit with the new OIDC client extension from this PR..

**Comment by sberyozkin** [comment]
Thanks @jmartisk, your enhancement is worthy a dedicated PR and highlight in the release notes :-)

**Comment by sberyozkin** [comment]
Te

**Comment by sberyozkin** [comment]
TCK test failures seem relevant

**Comment by jmartisk** [comment]
TCKs should hopefully be fixed now...

**Review by phillip-kruger — APPROVED** [review]
Nice ! Thanks @jmartisk

**Pull request merged**
