### PR TITLE
Assorted WebJarUtil fixes

### PR DESCRIPTION
**Pull request by gsmet**
Better reviewed commit per commit as they are all small fixes.

@phillip-kruger I wanted to reuse this in my GitHub App project and ended having quite a lot of small issues. So here are a set of fixes/improvements.

Could you have a look?

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@phillip-kruger would be nice if you could check I haven't broken things for you :).

**Comment by phillip-kruger** [comment]
Hi @gsmet , coming to you from my phone. I am on PTO, I will be able to check on Thursday. Hope that is ok ?

**Comment by gsmet** [comment]
@phillip-kruger yup, no worries!

**Comment by phillip-kruger** [comment]
Starting to look at this now, seems like the custom branding is not working, I am still investigating further.

**Review by phillip-kruger — APPROVED** [review]
LGTM. I tested this PR against my example openapi application and everything looks fine.

**Comment by gsmet** [comment]
@phillip-kruger ok, so branding work in the end?

**Comment by phillip-kruger** [comment]
Yes ! It was my mistake in testing, all is working fine. Thanks :)

**Comment by gsmet** [comment]
Cool, let's merge then and I will be able to remove my custom code from my app.

**Pull request merged**
