### PR TITLE
quarkus:go-offline to download all the app dependencies for off-line use

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Comment by maxandersen** [comment]
Lgtm. Nice feature. 

What would the corresponding Gradle task be ?

**Comment by aloubyansky** [comment]
@glefloch if you like the idea, we could add an equivalent task to the Gradle plugin.

**Comment by glefloch** [comment]
Definitely, that’s cool !

**Review by gsmet — APPROVED** [review]
That's cool but shouldn't it be documented somewhere?

**Comment by dloiacono** [comment]
+1

**Comment by aloubyansky** [comment]
I'll add it to the https://quarkus.io/guides/maven-tooling in another PR

**Comment by rsvoboda** [comment]
@aloubyansky is the same functionality available in CLI?

I see only '--offline' when I hit 'quarkus build --help'

**Comment by maxandersen** [comment]
No `quarkus build --offline` is to have build fail if it ever needs to go offline.

We don't automatically expose every build command in quarkus cli; just the "commonly used ones". 

In this case I would lean towards users should use their build system specific command if they want this level of granularity.

**Comment by aloubyansky** [comment]
Given that now both maven and gradle plug-ins provide the go-offline commands, we could add it to the cli as well.

**Comment by rsvoboda** [comment]
Created https://github.com/quarkusio/quarkus/issues/21608

**Pull request merged**
