### PR TITLE
Update Jackson to 2.10.0

### PR DESCRIPTION
**Pull request by wburns**
Trivial change to just update to latest version of Jackson.

### CODE REVIEW

**Comment by geoand** [comment]
@cescoffier I believe you wanted to hold off from this upgrade because vert.x wasn't using it?

**Comment by cescoffier** [comment]
Exactly. @wburns, which API / bug has been fixed in this version?

**Comment by wburns** [comment]
Infinispan updated our dependency version to 2.10.0 so this causes a version mismatch; The two versions are not binary compatible since Jackson added some new interfaces. Fortunately we can work around it for now though as this only manifests itself in our upcoming server outside of Quarkus repo.

**Comment by machi1990** [comment]
We have a similar change here https://github.com/quarkusio/quarkus/pull/4231, maybe we can close either of the two and continue the discussion on a single PR? WDYT? @gsmet

**Comment by wburns** [comment]
Ah, yes, sorry for the duplicate. I will just close this one.

**Pull request closed without merging**
