### PR TITLE
2.7.7 backports 2

### PR DESCRIPTION
**Pull request by gsmet**
Please don't merge, I will merge it myself.

### CODE REVIEW

**Comment by gsmet** [comment]
@sanne @davided we have some native issues with the Hibernate Reactive upgrade that was marked for backport in 2.7 (upgrade to 1.1.7). I'm not sure it's worth investigating to be honest as HR was very new in 2.7 and there are probably other issues.
I will let you decide if you want to spend time on this or not. For now, I removed the commits from this PR. I have saved the commits locally so I can push them to a branch somewhere if you need them.

The report with the failures is here: https://github.com/quarkusio/quarkus/runs/10637723678 .

**Comment by gsmet** [comment]
@geoand we have a failure in the RESTEasy Reactive test suite:

`org.jboss.resteasy.reactive.server.vertx.test.resource.basic.UriInfoTest`

```
2023-01-13T16:48:45.3604649Z [ERROR] org.jboss.resteasy.reactive.server.vertx.test.resource.basic.UriInfoTest  Time elapsed: 0.044 s  <<< ERROR!
2023-01-13T16:48:45.3605799Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'org.jboss.resteasy.reactive.server.vertx.test.resource.basic.resource.UriInfoRelativizeResource#relativize'
2023-01-13T16:48:45.3793096Z 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:294)
2023-01-13T16:48:45.3793919Z 	at org.jboss.resteasy.reactive.server.processor.ResteasyReactiveDeploymentManager$ScanStep.scan(ResteasyReactiveDeploymentManager.java:226)
2023-01-13T16:48:45.3794714Z 	at org.jboss.resteasy.reactive.server.vertx.test.framework.ResteasyReactiveUnitTest.doDeployment(ResteasyReactiveUnitTest.java:318)
2023-01-13T16:48:45.3795502Z 	at org.jboss.resteasy.reactive.server.vertx.test.framework.ResteasyReactiveUnitTest.beforeAll(ResteasyReactiveUnitTest.java:278)
2023-01-13T16:48:45.3796280Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
2023-01-13T16:48:45.3796938Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-01-13T16:48:45.3797622Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
2023-01-13T16:48:45.3798293Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
2023-01-13T16:48:45.3798889Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
2023-01-13T16:48:45.3799486Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
2023-01-13T16:48:45.3800083Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-01-13T16:48:45.3800914Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2023-01-13T16:48:45.3801441Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2023-01-13T16:48:45.3801965Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2023-01-13T16:48:45.3802536Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-01-13T16:48:45.3803169Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2023-01-13T16:48:45.3803775Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2023-01-13T16:48:45.3804218Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2023-01-13T16:48:45.3804863Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2023-01-13T16:48:45.3805639Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2023-01-13T16:48:45.3806229Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-01-13T16:48:45.3806841Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2023-01-13T16:48:45.3807356Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2023-01-13T16:48:45.3807874Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2023-01-13T16:48:45.3808463Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-01-13T16:48:45.3809070Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2023-01-13T16:48:45.3809648Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2023-01-13T16:48:45.3810474Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
2023-01-13T16:48:45.3811281Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2023-01-13T16:48:45.3811948Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
2023-01-13T16:48:45.3812578Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
2023-01-13T16:48:45.3813198Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
2023-01-13T16:48:45.3814197Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
2023-01-13T16:48:45.3814886Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
2023-01-13T16:48:45.3815541Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
2023-01-13T16:48:45.3816086Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2023-01-13T16:48:45.3816575Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2023-01-13T16:48:45.3817108Z 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2023-01-13T16:48:45.3817699Z 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
2023-01-13T16:48:45.3818304Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2023-01-13T16:48:45.3818943Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2023-01-13T16:48:45.3819636Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2023-01-13T16:48:45.3820198Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2023-01-13T16:48:45.3820705Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2023-01-13T16:48:45.3821152Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2023-01-13T16:48:45.3821580Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2023-01-13T16:48:45.3822543Z Caused by: java.lang.RuntimeException: Failed to process method 'org.jboss.resteasy.reactive.server.vertx.test.resource.basic.resource.UriInfoRelativizeResource#relativize'
2023-01-13T16:48:45.3823322Z 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:666)
2023-01-13T16:48:45.3823968Z 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:382)
2023-01-13T16:48:45.3824601Z 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:265)
2023-01-13T16:48:45.3824990Z 	... 45 more
2023-01-13T16:48:45.3825752Z Caused by: java.lang.IllegalArgumentException: Path '/{path : .*}' of method 'org.jboss.resteasy.reactive.server.vertx.test.resource.basic.resource.UriInfoRelativizeResource#relativize' is not a valid expression
2023-01-13T16:48:45.3826595Z 	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.validateMethodPath(ServerEndpointIndexer.java:221)
2023-01-13T16:48:45.3827388Z 	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleAdditionalMethodProcessing(ServerEndpointIndexer.java:213)
2023-01-13T16:48:45.3828246Z 	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleAdditionalMethodProcessing(ServerEndpointIndexer.java:85)
2023-01-13T16:48:45.3828996Z 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:658)
2023-01-13T16:48:45.3829396Z 	... 47 more
2023-01-13T16:48:45.3889123Z Caused by: java.util.regex.PatternSyntaxException: named capturing group is missing trailing '>' near index 7
2023-01-13T16:48:45.3889899Z (?<path >.*)$
2023-01-13T16:48:45.3890505Z        ^
2023-01-13T16:48:45.3890853Z 	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
2023-01-13T16:48:45.3891237Z 	at java.base/java.util.regex.Pattern.groupname(Pattern.java:2952)
2023-01-13T16:48:45.3891607Z 	at java.base/java.util.regex.Pattern.group0(Pattern.java:2998)
2023-01-13T16:48:45.3891960Z 	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2124)
2023-01-13T16:48:45.3892298Z 	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
2023-01-13T16:48:45.3892645Z 	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
2023-01-13T16:48:45.3892988Z 	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1429)
2023-01-13T16:48:45.3893339Z 	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
2023-01-13T16:48:45.3893909Z 	at org.jboss.resteasy.reactive.server.mapping.URITemplate.<init>(URITemplate.java:157)
2023-01-13T16:48:45.3894539Z 	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.validateMethodPath(ServerEndpointIndexer.java:218)
2023-01-13T16:48:45.3894987Z 	... 50 more
```

Not sure what in the backports could have introduced the issue? Any chance you could have a look?

I remember we fixed something in this regard but I'm unsure how we could trigger it now?

**Comment by geoand** [comment]
Unfortunately my schedule is really backed up with workshops this week, so i doubt I will have time to look into it.
Perhaps @Sgitario can help out?

**Comment by Sgitario** [comment]
Looking into this.

**Comment by Sgitario** [comment]
We started validating the paths in https://github.com/quarkusio/quarkus/pull/20087, which probably introduces this issue. However, it was later fixed by https://github.com/quarkusio/quarkus/pull/25285. 

So you need to backport https://github.com/quarkusio/quarkus/pull/25285 too. (I tried locally and now this test passes)

**Comment by gsmet** [comment]
@Sgitario I added the commit, thanks!

**Comment by Sgitario** [comment]
The failures in io.quarkus.rest.client.reactive.queries.QueryTest is resolved by backporting first https://github.com/quarkusio/quarkus/pull/24549 and then https://github.com/quarkusio/quarkus/pull/24664. Though, I'm not sure why this test is there when it was prior not supported.

**Comment by Sgitario** [comment]
> @Sgitario could you try to understand how this test was introduced (using git blame probably?)? I'm nervous starting to backport things just to make a test that shouldn't be there in the first place work.

The test was added as part of these changes https://github.com/quarkusio/quarkus/pull/25870 which is more recent than https://github.com/quarkusio/quarkus/pull/24664. What I meant that didn't understand was that #25870 was backported and not #24664.

**Pull request merged**
