### PR TITLE
Revert "Update Agroal to 1.8"

### PR DESCRIPTION
**Pull request by gsmet**
**PLEASE DON'T MERGE AS MAYBE LUIS WILL COME WITH A QUICK RELEASE BEFORE I RELEASE FINAL**

(and I don't use WIP as I want a proper CI run)

This reverts commit bd3016c140a3dd4599455279bb64bc13af711c86.

1.8 introduces a log message at each startup:
2020-05-21 16:35:10,006 INFO [io.agr.pool] (main) Datasource '<default>': Pool interceptors: []

While not a big issue, it's definitely a usability regression
consisdering we are working hard on keeping our logs as less verbose as
possible.

I think we should demote this log message to DEBUG.

/cc @barreiro

### CODE REVIEW

**Comment by machi1990** [comment]
> 1.8 introduces a log message at each startup:
> 2020-05-21 16:35:10,006 INFO [io.agr.pool] (main) Datasource '': Pool interceptors: []
> 
> While not a big issue, it's definitely a usability regression
> consisdering we are working hard on keeping our logs as less verbose as
> possible.

Was filtering out the log instead with a build item considered?

**Comment by gsmet** [comment]
That could have been a good idea but the start of the message (before you get the database name) is not easily identifiable unfortunately. And we don't use regexps, we compare the start of the message.

That's why I passed on this option.

**Comment by machi1990** [comment]
> That could have been a good idea but the start of the message (before you get the database name) is not easily identifiable unfortunately. And we don't use regexps, we compare the start of the message.
> 
> That's why I passed on this option.

Could have been a good fix till an upstream release.  Thanks for answering / looking.

**Comment by gsmet** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/9596 .

**Pull request closed without merging**
