### PR TITLE
Improve OIDC code flow concept document

### LINKED ISSUE #37422: Docs: OpenID Connect authorization code flow mechanism
### Describe the bug

I identified several issues in `OpenID Connect authorization code flow mechanism for protecting web applications` guide[1]

1. The guide advises[2] to use property `quarkus.oidc.authentication.error-path=/error` for failures during user identification. When I use recommended solution (keycloak), I am not redirected back to the app on failure, but just get a message `Invalid username or password`.

2. An example in the token section[3] contains method `getReservationfromRemoteEndpoint`  without any description. If it is supposed to be user-defined method, then a) it should be mentioned b) an implementation example would be helpful, given that the method should retrieve data from a token, which looks like a long line of random ASCII.

3. If user info[4] is requested (via `quarkus.oidc.authentication.user-info-required=true`) this is often (even for a very small payloads[5]) leads to a very big cookies, which break some browsers (eg Firefox). I suppose, we should advise to add `quarkus.oidc.token-state-manager.split-tokens=true` for this case. That option is described in error messages in devmode and in another section[6], but we need at least to mention it.

4.  I am not sure, if this is our problem, or Keycloak's, but method ` io.quarkus.oidc.UserInfo.getFirstName()` returns `null` for user info, retireved from keycloak[5]. In the UI of Keycloak(version 22.0.1) the field is called "First Name", so that is unexpected.

5. Token state manager[6] section recommends to use value `id-refresh-token` for `quarkus.oidc.token-state-manager.strategy` property. When I put this in application.properties, I get an exception: `Cannot convert id-refresh-token to enum class io.quarkus.oidc.OidcTenantConfig$TokenStateManager$Strategy`. Options `id-token` and `keep-all-tokens` doesn't have this problem.

[1] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication
[2] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication#customizing-the-authentication-error-response
[3] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication#access_id_and_access_tokens
[4] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication#user-info
[5] `{"sub":"eb4123a3-b722-4798-9af5-8957f823657a","email_verified":true,"name":"Alice Longbottom","preferred_username":"alice","given_name":"Alice","family_name":"Longbottom","email":"alice@example.com"}`
[6] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication#token-state-manager

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #37422

Keeping in a draft state for now, @fedinskiy, please clarify how did you reproduce a too large session cookie issue with UserInfo

### CODE REVIEW

**Comment by rsvoboda** [comment]
Hi Sergey. Fedor is on Christmas PTO already, he will be back in January.

**Comment by sberyozkin** [comment]
@fedinskiy FYI, the large session cookie issue is addressed in https://github.com/quarkusio/quarkus/pull/37891, which has already been approved by @gastaldi, so it is ready to go pending some possible comments from Pedro. I plan to merge in the evening of 3rd Jan or 4th Jan morning at the latest, so then it would be possible to verify it fixed the issue in your reproducer as well 

CC @rsvoboda

**Comment by fedinskiy** [comment]
@sberyozkin do you still need clarification regarding large session cookie?

**Comment by sberyozkin** [comment]
@fedinskiy I'm certain #37891 will resolve it, so if you are OK with it, your comment about it can be considered resolved and then once #37891 is merged, you can double check it if you will have time, does it sound reasonable ?

**Review by rsvoboda — APPROVED** [review]
Approving, @fedinskiy told me he was OK with the changes.

**Comment by sberyozkin** [comment]
Thanks @fedinskiy @rsvoboda

**Pull request merged**
