### PR TITLE
Update to latest SmallRye OpenAPI

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Looks like errors are OOM.

Is this expected @gsmet?

**Comment by gsmet** [comment]
Looks weird, I triggered a new run.

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
This needs a rebase

**Comment by FroMage** [comment]
The CI failure seems related:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-main: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.OutOfMemoryError: Java heap space
[ERROR] 	at com.fasterxml.jackson.core.util.TextBuffer.carr(TextBuffer.java:864)
[ERROR] 	at com.fasterxml.jackson.core.util.TextBuffer.expand(TextBuffer.java:825)
[ERROR] 	at com.fasterxml.jackson.core.util.TextBuffer.append(TextBuffer.java:590)
[ERROR] 	at com.fasterxml.jackson.core.io.SegmentedStringWriter.write(SegmentedStringWriter.java:58)
[ERROR] 	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._flushBuffer(WriterBasedJsonGenerator.java:1946)
[ERROR] 	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeRaw(WriterBasedJsonGenerator.java:548)
[ERROR] 	at com.fasterxml.jackson.core.util.DefaultIndenter.writeIndentation(DefaultIndenter.java:91)
[ERROR] 	at com.fasterxml.jackson.core.util.DefaultPrettyPrinter.writeObjectEntrySeparator(DefaultPrettyPrinter.java:319)
[ERROR] 	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writePPFieldName(WriterBasedJsonGenerator.java:315)
[ERROR] 	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writeFieldName(WriterBasedJsonGenerator.java:156)
[ERROR] 	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeFieldName(WriterBasedJsonGenerator.java:139)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:310)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:311)
[ERROR] 	at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:39)
```

This is because we call `serialize()` during build, to generate the `OpenApiDocument`. Perhaps the latest version includes too much info or tries to serialise a graph with cycles?

**Comment by kenfinnigan** [comment]
Any thoughts @EricWittmann?

**Comment by EricWittmann** [comment]
I have no ideas off the top of my head.  I can't see how cycles are possible, but I don't guarantee it.  I would need to dig into it.  Is there some time pressure here?  I'm sort of in a bad situation right now.

**Comment by kenfinnigan** [comment]
Not a huge time crunch, but it was more about getting an updated version in as I know there were some issues fixed

**Comment by kenfinnigan** [comment]
Running locally I see:

09:43:10,527 WARN  [io.qua.arc.pro.BeanArchives] Failed to index byte: Stream closed

I thought we'd fixed that in the implementation?

**Comment by kenfinnigan** [comment]
Ok, in looking at this I discovered the fix @EricWittmann made isn't in 1.1.7, so we need a new release.

Working on that now

**Comment by EricWittmann** [comment]
Yeah I just did a full build of `master` using smallrye-open-api version `1.1.8-SNAPSHOT` and everything worked fine.  For what that's worth. :)

**Pull request merged**
