### PR TITLE
Update Netty to 4.1.67

### PR DESCRIPTION
**Pull request by cescoffier**
Update Netty version to 4.1.67.

Unlike previous Netty update, this one is motivated by https://github.com/quarkusio/quarkus/issues/18469.﻿

### CODE REVIEW

**Comment by sberyozkin** [comment]
It should also fix #18962

**Comment by ThoSap** [comment]
It should also fix https://github.com/quarkusio/quarkus/issues/14695

**Comment by stuartwdouglas** [comment]
I have pushed some new substitutions, lets see what CI says.

**Comment by gsmet** [comment]
```
io.grpc.StatusRuntimeException: INTERNAL: Connection closed after GOAWAY. HTTP/2 error code: INTERNAL_ERROR, debug data: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at examples.GreeterGrpc$GreeterBlockingStub.sayHello(GreeterGrpc.java:177)
	at io.quarkus.grpc.examples.hello.HelloWorldMutualTlsServiceTest.testHelloWorldServiceUsingBlockingStub(HelloWorldMutualTlsServiceTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1057)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:898)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
```

**Comment by cescoffier** [comment]
Not totally surprising, gRPC is a bit strict in term of netty version. I need to check if there is a compatible version.

**Comment by gsmet** [comment]
Yeah, we are way behind in terms of gRPC versions.

**Comment by cescoffier** [comment]
Does not seem to have any compatible version yet. We can try to update to a newer one and see.

**Comment by cescoffier** [comment]
No luck with the latest grpc-java version. I guess we are kind of stuck until a suitable version gets released.

**Comment by cescoffier** [comment]
The last compatible version of netty is 4.1.65.

**Comment by hamburml** [comment]
@gsmet and @cescoffier What do you say to https://github.com/grpc/grpc-java/issues/8416#issuecomment-901325461?

**Comment by stuartwdouglas** [comment]
This PR fixes the GRPC issues: https://github.com/vert-x3/vertx-grpc/pull/106

**Comment by gsmet** [comment]
Closing this as it will come with a Vert.x upgrade.

**Pull request closed without merging**
