### PR TITLE
Replace deprecated properties in JReleaser descriptor

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@yrodiere looks like `io.quarkus.cli.CliProjectGradleTest.testExtensionList` is still trying to contact the Gradle repository for Quarkus SNAPSHOT artifacts.

**Comment by gsmet** [comment]
@yrodiere  Not sure we can easily do something about it but thought I might as well have your opinion about it.

**Comment by yrodiere** [comment]
@gsmet See https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Gradle.20and.20snapshots/near/299697109:

> yrodiere: @Guillaume Smet I'm still trying to remember the specifics, but what I was involved in was gradle tests, this is CLI tests that happen to use Gradle... I'm not sure they use the same config?
> gsmet: ah maybe
> gsmet: I thought we protected all of them but that might as well have been limited to the Gradle ITs

**Comment by yrodiere** [comment]
@glefloch intended to have a look, not sure if he managed to do something. That looked difficult.

**Pull request merged**
