### PR TITLE
[3.15] 3.15.2 backports 3

### PR DESCRIPTION
**Pull request by gsmet**
Please don't merge, I will merge it myself.

This is not the final payload, I still need to work on some individual items.

### CODE REVIEW

**Comment by rsvoboda** [comment]
@michalvavrik we may need you to look into `RepeatedPermissionsAllowedTest`. https://github.com/quarkusio/quarkus/pull/44476/commits/ed536e8f60eba9316ec3bf57e27ed480f0cb4280 is backported in this branch but it may require some adder changed to backported too.

**Comment by gsmet** [comment]
The error is the following:

```
Caused by: io.vertx.core.json.DecodeException: Failed to decode:Unexpected character ('%' (code 37)): was expecting double-quote to start field name
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:128)
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromString(QuarkusJacksonJsonCodec.java:95)
	at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:1262)
	at io.vertx.core.json.JsonObject.<init>(JsonObject.java:51)
	... 21 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('%' (code 37)): was expecting double-quote to start field name
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2648)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:685)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1910)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:940)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:596)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4881)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3035)
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:125)
```

I think we should really drop the log silencing in this test as it's going to be very hard to understand what's going on when the test fails.

**Comment by michalvavrik** [comment]
> @michalvavrik we may need you to look into RepeatedPermissionsAllowedTest. https://github.com/quarkusio/quarkus/commit/ed536e8f60eba9316ec3bf57e27ed480f0cb4280 is backported in this PR but it may require some additional changed to backported too.

these failures tells you that security checks are not performed eagerly; @gsmet is this test failing on main or is it flaky on main? If not, I think I need to look into differences between 3.16 and 3.15.

> I think we should really drop the log silencing in this test as it's going to be very hard to understand what's going on when the test fails.

@gsmet this is the reason why I added the silencing https://github.com/quarkusio/quarkus/issues/43017. I don't think you will get any useful information if the test is not failing or when the test is failing and it is not flaky; anyway, you know CI possibilities better than I do, if it is fine, let's enable it

**Comment by michalvavrik** [comment]
@gsmet @rsvoboda it is wild guess, but I think I know where the issue is, In 3.16 I think I changed utils and on the current main, the change was only needed at one place. however on 3.15 it is probably needed in more than one place. it should be pretty trivial, I'll look in an hour and report back.

**Comment by michalvavrik** [comment]
If you add this commit https://github.com/quarkusio/quarkus/commit/255ffdb2b5ac93aa866491e2c452cdd245a83762 in addition to the commits you already have, the failure will be fixed.

**Comment by gsmet** [comment]
@michalvavrik I amended the commit with your additional change and the test passes locally, thanks!

> btw, the log message above didn't provide me information that I didn't already know from 500

No really, you never know. It could have been a completely different issue. I think we need something better than disabling 500 entirely as we need logging to understand what's going on. If not for you, for other people having to understand what's going on.

**Comment by michalvavrik** [comment]
> No really, you never know. It could have been a completely different issue. I think we need something better than disabling 500 entirely as we need logging to understand what's going on. If not for you, for other people having to understand what's going on.

Understood, I re-read that commit and there is `.body("{%$$#!#@") // assures checks are eager` which seemed clear to me, but now that I think about it, it's probably not that clear for whoever comes after me till they play with the test. Alright, thanks

**Comment by rsvoboda** [comment]
JPA oracle native failed with
```
Error: The heap snapshot verifier discovered a type not marked as reachable: AnalysisType<MemoryType[] -> HotSpotType<[Ljava/lang/management/MemoryType;, resolved>, allocated: false, inHeap: false, reachable: false>
com.oracle.graal.pointsto.util.AnalysisError: The heap snapshot verifier discovered a type not marked as reachable: AnalysisType<MemoryType[] -> HotSpotType<[Ljava/lang/management/MemoryType;, resolved>, allocated: false, inHeap: false, reachable: false>
```

**Pull request merged**
