### PR TITLE
Fix handling of Accept header in graphQL

### LINKED ISSUE #30806: */* in Accept header is ignored if not listed as the first item
### Describe the bug

see https://github.com/quarkusio/quarkus/discussions/30759#discussioncomment-4839300 for description of the bug

### Expected behavior

An  `*/*` type is always recognized if present in an `Accept` header of GraphQL requests, and the request be handled normally with the default response content type (which is `application/graphql+json`)

### Actual behavior

An  `*/*` type is recognized only if it's the first item in the `Accept` header, else the GraphQL endpoint returns a 406 Unacceptable response.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Bazalii**
- Closes #30806

### CODE REVIEW

**Review by jmartisk — APPROVED** [review]

**Comment by jmartisk** [comment]
@Bazalii , the CI is complaining that your source files are not formatted. Please run another Maven build to have the maven-formatter-plugin take care of it, and then amend and re-push your commit. Thanks!

**Comment by Bazalii** [comment]
@jmartisk Sorry about that. I forgot to run ./mvnw install before pushing updates. Now this problem should be solved.

**Comment by jmartisk** [comment]
Great, thanks! I'll merge it after the weekend, right now we have a merging freeze. Because the main branch will receive some significant rework over the weekend, we might have to do a rebase or so, we'll see on Monday

**Comment by Bazalii** [comment]
> Great, thanks! I'll merge it after the weekend, right now we have a merging freeze. Because the main branch will receive some significant rework over the weekend, we might have to do a rebase or so, we'll see on Monday

Okay. When will it be possible for this update to become a part of a release?

**Comment by gsmet** [comment]
If CI passes, most probably next Wednesday evening Paris time in 2.16.2.Final.

**Pull request merged**
