### PR TITLE
Fix for issue 42549 - replaces oidc auth github screenshots with generic ones

### PR DESCRIPTION
**Pull request by rghara**
Replaces oidc auth github screenshots with generic ones

### CODE REVIEW

**Comment by sberyozkin** [comment]
@rghara I'm not sure why the doc build failed, but while looking at it, I realized you did not have to introduce new image names, the existing github ones have to be replaced, sorry I did not spot it earlier. If you'd like, add a separate commit only and I can can squash them, or please do yourself, I guess there is no need to rebase right now

**Comment by rghara** [comment]
@sberyozkin 
I think I need redo this PR. This time I will make sure my copy syncs with origin.

**Comment by sberyozkin** [comment]
@rghara Np, nearly there

**Comment by rghara** [comment]
@sberyozkin 
New PR created: https://github.com/quarkusio/quarkus/pull/44029

**Pull request closed without merging**
