### PR TITLE
[fixes #4626] - CI failures for BearerTokenAuthorizationTest

### LINKED ISSUE #4626: ci failures for BearerTokenAuthorizationTest
**Describe the bug**
CI native build for the mentioned test fails
**Expected behavior**
CI to pass

**Screenshots**
```
INFO] Running io.quarkus.it.keycloak.BearerTokenAuthorizationTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.282 s <<< FAILURE! - in io.quarkus.it.keycloak.BearerTokenAuthorizationTest
[ERROR] io.quarkus.it.keycloak.BearerTokenAuthorizationTest  Time elapsed: 4.282 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <201> but was <500>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

**Additional context**
the following PRs from https://github.com/quarkusio/quarkus/pull/4609 to https://github.com/quarkusio/quarkus/pull/4623 seems to have hit this failure.

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@pedroigor Can you revert then the change done by Georgios @geoand ? If we want to use the latest tag...

**Comment by pedroigor** [comment]
@sberyozkin done

**Review by sberyozkin — COMMENTED** [review]
@pedroigor will you need a code like this one for the policy enforcer tests ?

**Comment by pedroigor** [comment]
@sberyozkin yes, but I'll handle it differently.

**Comment by sberyozkin** [comment]
@pedroigor cool, because I was thinking, 'May be I should'e asked Pedro about it first before suggesting to unpin the tag' :-)

**Comment by sberyozkin** [comment]
@pedroigor can you fix the import order please

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@gsmet @geoand OIDC test is passing, Gradle test is failing

**Comment by geoand** [comment]
Seems to have passed after all :)

**Comment by cescoffier** [comment]
I would rather pin the version, and have PRs updating the version after a KC release.

**Pull request merged**
