### PR TITLE
Don't generate certificates for tests when build is skipped

### PR DESCRIPTION
**Pull request by geoand**
This slightly speeds up the -Dquickly build

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Hmmm, the failures on Windows look suspicious.

**Comment by gsmet** [comment]
I had a quick look, I don't see anything obvious.

**Comment by geoand** [comment]
And I don't use Windows, so I probably won't be able to reproduce it....

**Comment by geoand** [comment]
I see this in the logs:

```posh
24-01-03T12:41:03.2423091Z java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for io.quarkus:quarkus-integration-test-rest-client::jar:999-SNAPSHOTnull
2024-01-03T12:41:03.2425954Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
2024-01-03T12:41:03.2427845Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:722)
2024-01-03T12:41:03.2430689Z 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2024-01-03T12:41:03.2431832Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-01-03T12:41:03.2432951Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-01-03T12:41:03.2435283Z Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for io.quarkus:quarkus-integration-test-rest-client::jar:999-SNAPSHOTnull
2024-01-03T12:41:03.2437608Z 	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:297)
2024-01-03T12:41:03.2439913Z 	at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:133)
2024-01-03T12:41:03.2441722Z 	at io.quarkus.test.junit.AbstractJvmQuarkusTestExtension.createAugmentor(AbstractJvmQuarkusTestExtension.java:189)
2024-01-03T12:41:03.2443593Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:219)
2024-01-03T12:41:03.2445215Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:605)
2024-01-03T12:41:03.2446833Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
2024-01-03T12:41:03.2447943Z 	... 1 more
2024-01-03T12:41:03.2450926Z Caused by: io.quarkus.bootstrap.resolver.maven.DeploymentInjectionException: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to collect dependencies for io.quarkus:quarkus-resteasy-deployment:jar:999-SNAPSHOT
2024-01-03T12:41:03.2454589Z 	at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.collectDependencies(ApplicationDependencyTreeResolver.java:604)
2024-01-03T12:41:03.2457381Z 	at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.injectDeploymentDependencies(ApplicationDependencyTreeResolver.java:502)
2024-01-03T12:41:03.2462321Z 	at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.resolve(ApplicationDependencyTreeResolver.java:197)
2024-01-03T12:41:03.2464673Z 	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.buildAppModel(BootstrapAppModelResolver.java:321)
2024-01-03T12:41:03.2466960Z 	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel(BootstrapAppModelResolver.java:286)
2024-01-03T12:41:03.2469692Z 	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel(BootstrapAppModelResolver.java:165)
2024-01-03T12:41:03.2471808Z 	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:283)
2024-01-03T12:41:03.2473058Z 	... 6 more
2024-01-03T12:41:03.2474862Z Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to collect dependencies for io.quarkus:quarkus-resteasy-deployment:jar:999-SNAPSHOT
2024-01-03T12:41:03.2477369Z 	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.collectManagedDependencies(MavenArtifactResolver.java:310)
2024-01-03T12:41:03.2480334Z 	at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.collectDependencies(ApplicationDependencyTreeResolver.java:600)
2024-01-03T12:41:03.2481947Z 	... 12 more
2024-01-03T12:41:03.2484700Z Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at io.quarkus:quarkus-resteasy-server-common-deployment:jar:999-SNAPSHOT -> io.quarkus:quarkus-undertow-spi:jar:999-SNAPSHOT -> io.quarkus.http:quarkus-http-servlet:jar:5.0.3.Final
2024-01-03T12:41:03.2488601Z 	at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:260)
2024-01-03T12:41:03.2507866Z 	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87)
2024-01-03T12:41:03.2511133Z 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:306)
2024-01-03T12:41:03.2513500Z 	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.collectManagedDependencies(MavenArtifactResolver.java:307)
2024-01-03T12:41:03.2515197Z 	... 13 more
2024-01-03T12:41:03.2517112Z Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for io.quarkus.http:quarkus-http-servlet:jar:5.0.3.Final
2024-01-03T12:41:03.2520308Z 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:289)
2024-01-03T12:41:03.2523091Z 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
2024-01-03T12:41:03.2525802Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382)
2024-01-03T12:41:03.2528922Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368)
2024-01-03T12:41:03.2540593Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218)
2024-01-03T12:41:03.3368918Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156)
2024-01-03T12:41:03.3554095Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138)
2024-01-03T12:41:03.3556396Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doRecurse(DfDependencyCollector.java:343)
2024-01-03T12:41:03.3558939Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:277)
2024-01-03T12:41:03.3561079Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156)
2024-01-03T12:41:03.3563027Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138)
2024-01-03T12:41:03.3564917Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doRecurse(DfDependencyCollector.java:343)
2024-01-03T12:41:03.3566851Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:277)
2024-01-03T12:41:03.3569546Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156)
2024-01-03T12:41:03.3571583Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138)
2024-01-03T12:41:03.3573589Z 	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108)
2024-01-03T12:41:03.3575833Z 	at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222)
2024-01-03T12:41:03.3577257Z 	... 16 more
2024-01-03T12:41:03.3582089Z Caused by: org.apache.maven.model.resolution.UnresolvableModelException: The following artifacts could not be resolved: org.jboss:jboss-parent:pom:28 (absent): Could not transfer artifact org.jboss:jboss-parent:pom:28 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-01-03T12:41:03.3586610Z 	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:160)
2024-01-03T12:41:03.3588910Z 	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:204)
2024-01-03T12:41:03.3590750Z 	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1009)
2024-01-03T12:41:03.3592508Z 	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:801)
2024-01-03T12:41:03.3594045Z 	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:327)
2024-01-03T12:41:03.3595543Z 	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:243)
2024-01-03T12:41:03.3597026Z 	at io.quarkus.bootstrap.resolver.maven.MavenModelBuilder.build(MavenModelBuilder.java:63)
2024-01-03T12:41:03.3599355Z 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:284)
2024-01-03T12:41:03.3600696Z 	... 32 more
2024-01-03T12:41:03.3604851Z Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.jboss:jboss-parent:pom:28 (absent): Could not transfer artifact org.jboss:jboss-parent:pom:28 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-01-03T12:41:03.3609776Z 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:473)
2024-01-03T12:41:03.3611606Z 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
2024-01-03T12:41:03.3613532Z 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
2024-01-03T12:41:03.3615388Z 	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:158)
2024-01-03T12:41:03.3616773Z 	... 39 more
2024-01-03T12:41:03.3620646Z Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss:jboss-parent:pom:28 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-01-03T12:41:03.3624471Z 	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:44)
2024-01-03T12:41:03.3626374Z 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:417)
2024-01-03T12:41:03.3628098Z 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260)
2024-01-03T12:41:03.3630601Z 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:537)
2024-01-03T12:41:03.3632358Z 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
2024-01-03T12:41:03.3633477Z 	... 42 more
2024-01-03T12:41:03.3635228Z Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-01-03T12:41:03.3637552Z 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
2024-01-03T12:41:03.3639134Z 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
2024-01-03T12:41:03.3640402Z 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
2024-01-03T12:41:03.3641611Z 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
2024-01-03T12:41:03.3643169Z 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
2024-01-03T12:41:03.3645128Z 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
2024-01-03T12:41:03.3646928Z 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
2024-01-03T12:41:03.3648813Z 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
2024-01-03T12:41:03.3650018Z 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
2024-01-03T12:41:03.3651293Z 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
2024-01-03T12:41:03.3652572Z 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
2024-01-03T12:41:03.3653756Z 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
2024-01-03T12:41:03.3654871Z 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
2024-01-03T12:41:03.3656109Z 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
2024-01-03T12:41:03.3657507Z 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
2024-01-03T12:41:03.3659186Z 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
2024-01-03T12:41:03.3660725Z 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
2024-01-03T12:41:03.3664516Z 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
2024-01-03T12:41:03.3666506Z 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
2024-01-03T12:41:03.3669115Z 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
2024-01-03T12:41:03.3670921Z 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
2024-01-03T12:41:03.3672421Z 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
2024-01-03T12:41:03.3674046Z 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
2024-01-03T12:41:03.3675316Z 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
2024-01-03T12:41:03.3676543Z 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
2024-01-03T12:41:03.3677916Z 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
2024-01-03T12:41:03.3679820Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
2024-01-03T12:41:03.3681297Z 	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:393)
2024-01-03T12:41:03.3682768Z 	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:343)
2024-01-03T12:41:03.3684566Z 	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64)
2024-01-03T12:41:03.3686460Z 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482)
2024-01-03T12:41:03.3688917Z 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414)
2024-01-03T12:41:03.3690164Z 	... 45 more
2024-01-03T12:41:03.3691915Z Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-01-03T12:41:03.3694169Z 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
2024-01-03T12:41:03.3695605Z 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
2024-01-03T12:41:03.3696957Z 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
2024-01-03T12:41:03.3698774Z 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
2024-01-03T12:41:03.3700402Z 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
2024-01-03T12:41:03.3702197Z 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
2024-01-03T12:41:03.3703421Z 	... 72 more
2024-01-03T12:41:03.3704555Z Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-01-03T12:41:03.3706320Z 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
2024-01-03T12:41:03.3708033Z 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
2024-01-03T12:41:03.3709965Z 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
2024-01-03T12:41:03.3711283Z 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
2024-01-03T12:41:03.3712202Z 	... 77 more
```

But I am not sure what to make of it...

**Comment by gsmet** [comment]
My guess is that something is wrong with the trust store config. But I don't see how what you did could change things.

I triggered a new CI run to check if it's just a flake.

**Comment by geoand** [comment]
My only guess is that the plugin does something weird that breaks some trust-store related handling in Windows, but that doesn't provide any real insight at all :)

**Comment by geoand** [comment]
Trying something else...

**Comment by geoand** [comment]
Closing as this small change is not worth any more effort

**Pull request closed without merging**
