### PR TITLE
Support outputDirectory in CreateProjectMojo

### PR DESCRIPTION
**Pull request by gastaldi**
This will allow the quarkus:create to be used on any directory and also useful in pom.xml when wanting to generate a project during the build

### CODE REVIEW

**Comment by geoand** [comment]
So I assume this is also useful in integration tests?

**Comment by gastaldi** [comment]
Yes, specially for integration tests :smiley:

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
If we are playing with that, could we make the command entirely consistent and always create the project in a new directory?

The current behavior is highly disturbing, especially when you have hidden files in the directory.

**Comment by gsmet** [comment]
Note that it doesn't have to be done in this PR. I don't want to block it.

**Comment by gastaldi** [comment]
So the default value for `outputDirectory` should be `${basedir}/${projectArtifactId}` ?

**Pull request merged**
