### PR TITLE
Fix mongo test issues

### PR DESCRIPTION
**Pull request by geoand**
The reason I started looking into [this](https://github.com/quarkusio/quarkus/pull/30648#issuecomment-1422288764) was this failure.

### CODE REVIEW

**Comment by gsmet** [comment]
We probably also need to revert https://github.com/quarkusio/quarkus/pull/30989 that I pushed as a band aid.

**Comment by geoand** [comment]
> We probably also need to revert #30989 that I pushed as a band aid.

Good idea! Let me try that

**Comment by loicmathieu** [comment]
Great, I saw there was some mix stuff in this IT with both Flapdoodle and devservices used :(
Usually, when using test resource, we specify the MongoDB connection string and it disabled devservices.

@geoand I saw you set the connection string from the test resource, I'm not against it but as it was not done at the begining I wonder if it can have some side effect. Would it override the one set manually or not ? A lot of things can be added to the MongoDB connection string (like a different default database) so I'm not very found of setting it automatically.

**Comment by geoand** [comment]
@loicmathieu if we don't set the property, then the TestResource is essentially worthless for anything other than the default port.
Returning a map of properties that contribute to configuration is how TestResources were designed and how all the other are used.
And yes, they will override anything in `application.properties` - again by design

**Review by Sgitario — APPROVED** [review]

**Comment by loicmathieu** [comment]
@geoand it didn't support automatic port mapping right ? So the port is always set manually (via test ressource args) and usually in combination with manually setting the connection string.

As I said, this change can break existing usage, I don't know if this test resource is used a lot in the wild (it exists prior to devservices) but we may need to be conservative or at least provides a way to customize the generated connection string (for ex with a test resource arg that allows passing extra properties to the generated connection string).

**Comment by geoand** [comment]
> @geoand it didn't support automatic port mapping right ? So the port is always set manually (via test ressource args) and usually in combination with manually setting the connection string.

Yes, whatever port is chosen in the annotation (if any) will be used. 
Currently this only works because Quarkus set `127.0.1.1:27017` as the default hosts value - which happens to coincide with the default used by the TestResource.

> As I said, this change can break existing usage, I don't know if this test resource is used a lot in the wild (it exists prior to devservices) but we may need to be conservative or at least provides a way to customize the generated connection string (for ex with a test resource arg that allows passing extra properties to the generated connection string).

The way things are now, the TestResource is pretty broken as is and this change is an unequivocal improvement.
If we think that some other mongo configuration property should be set (or even added to configuration and set by the TestResource), I'm all for that, but I'll let you do that in a follow up. 
The way things are now, not setting any property at all is just plain wrong.

**Review by loicmathieu — APPROVED** [review]

**Pull request merged**
