### PR TITLE
Revert "Run OIDC Challenge in the blocking mode if needed"

### PR DESCRIPTION
**Pull request by sberyozkin**
Reverts quarkusio/quarkus#12888

### CODE REVIEW

**Comment by cescoffier** [comment]
I was going to ping you. The new code blocks the event loop.

**Comment by sberyozkin** [comment]
@cescoffier Hi Clement, this is something I'm confused about. It works fine on my laptop and it is the code which has to run in the blocking mode (it is run in the blocking executor). Do you have some recommendation how to fix it ?

**Comment by sberyozkin** [comment]
@cescoffier For example, before this PR, [this call](https://github.com/quarkusio/quarkus/pull/13036/files#diff-a5d5b8d85982c834c70abde0c67251aa9b4f03394b9e1b731600ddc6d0af6a6cR67) is coming from [here](https://github.com/quarkusio/quarkus/blob/1.9.1.Final/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L55) with the blocking context implemented [here](https://github.com/quarkusio/quarkus/blob/1.9.1.Final/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java#L37).
So as you can see I just moved this blocking call from [here](https://github.com/quarkusio/quarkus/blob/1.9.1.Final/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L55) to `OidcRecorder` inside the function

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
@cescoffier @gsmet merged so to fix CI and help with #13034 - but I'm not sure how to handle labelling. Could you please amend?

**Comment by sberyozkin** [comment]
@Sanne thanks

**Pull request merged**
