### PR TITLE
Don't configure -cp with uberjar on OpenShift

### LINKED ISSUE #14844: Generated Openshift manifest contains cp argument with all dependencies when uber-jar packaging is used
**Describe the bug**
When uber-jar packaging is selected then the generated openshift manifest contains in the cp argument list of nonexisting files `/deployments/lib/*` like in the legacy-jar packaging case.

**Expected behavior**
cp argument with list of dependencies is not part of the arguments when uber-jar packaging is active.

**To Reproduce**
'mvn clean package` on a Quarkus project where uber-jar packaking is selected then check the generated Openshift Manifests in target/kubernetes/openshift.(yml|json).

**Configuration**
```properties
config_suffix=-t

quarkus.package.type=uber-jar

quarkus.application.name=application-name${config_suffix}

quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.env.configmaps=config-map${config_suffix}
quarkus.openshift.env.secrets=truststore-password,keystore-passwords
quarkus.openshift.mounts.keystore.path=/mnt/keystore
quarkus.openshift.mounts.truststore.path=/mnt/truststore
quarkus.openshift.secret-volumes.truststore.secret-name=some-truststore
quarkus.openshift.secret-volumes.keystore.secret-name=keystore
quarkus.openshift.service-account=default

quarkus.openshift.resources.requests.memory=100Mi
quarkus.openshift.resources.requests.cpu=50m
quarkus.openshift.resources.limits.memory=250Mi
quarkus.openshift.resources.limits.cpu=100m
```

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "11.0.9.1" 2020-11-04 LTS
 - Quarkus version or git rev: 1.11.1, 1.10.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #14844

### CODE REVIEW

**Comment by geoand** [comment]
What is significance of `uber-jar` here, why is it a special case?
Shouldn't we never use `-cp`?

**Comment by iocanel** [comment]
> What is significance of `uber-jar` here, why is it a special case?
> Shouldn't we never use `-cp`?

For docker, definitely not. It's the Dockerfiles responsibility to provide an entry point that makes sense.
For jib probably not, I guess its the extensions responsibility, to set a meaningful extension.
For s2i, it's the builder image that is responsible. And I think that not all builder images I tired do a great job at it and that's why we were forced to add it.

Makes sense?

**Comment by geoand** [comment]
OK, understood

**Comment by geoand** [comment]
And we want this in 1.11 too, right?

**Comment by iocanel** [comment]
Not sure, AFAIU this is a nice to have.

**Comment by geoand** [comment]
OK, let's just keep it in mind if someone asks for it for 1.11

**Review by geoand — APPROVED** [review]

**Pull request merged**
