### PR TITLE
Fix vale errors in Security Authentication mechanisms > 3.5

### PR DESCRIPTION
**Pull request by rolfedh**
Cherry picked Fix vale errors in Security Authentication mechanisms https://github.com/quarkusio/quarkus/pull/37131 from main to 3.5 using SHA https://github.com/quarkusio/quarkus/commit/82ac9e22259ea9a10f6c8d878acd618f99fe3252

### CODE REVIEW

**Comment by sberyozkin** [comment]
@rolfedh I think you need to add a label to backport to 3.5, 3.2, sometimes we create dedicated PRs to specific branches but I believe it is not necessary in this case, CC @gsmet

**Review by gsmet — CHANGES_REQUESTED** [review]
I don't think adding a new config class in a maintenance branch is what we want to do.

**Comment by gsmet** [comment]
My personal opinion is that we should refrain from backporting large chunks of changes to the doc because it just won't scale. I raised my concerns about that a few times already.

**Comment by rolfedh** [comment]
> I don't think adding a new config class in a maintenance branch is what we want to do.

I agree. I created this pull request late yesterday and missed this important point. I'll make sure to remove it.

**Pull request closed without merging**
