### PR TITLE
Ensure that Spring Controller methods can use @Valid

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Approving and backporting but as discussed, we need to clean this up.

**Comment by geoand** [comment]
Cool! I'll provide a clean up PR as discussed, hopefully on Monday

**Comment by geoand** [comment]
I need to backport this into the 0.22 branch, I forgot to do that.
I'll do it in a few hours when I'm at my machine

**Comment by gsmet** [comment]
I did it just after merging:
https://github.com/quarkusio/quarkus/commits/0.22 .

**Comment by geoand** [comment]
Nice, thanks!

**Pull request merged**
