### PR TITLE
[WIP] documentation-related script

### PR DESCRIPTION
**Pull request by rolfedh**
Goal: 
As part of a developing conversation, I created this PR to rapidly prototype and explore the feasibility of addressing Red Hat product naming requirements without burdening community contributors. 

This includes:
- Differentiate between product name instances of "Quarkus" and other types of instances.
- Replace the first instance with `{product-name-first}`
- Replace other instances with `{product-name}`
- Send modified files to an output directory
- Allow writers to define exclusions

### CODE REVIEW

**Comment by gsmet** [comment]
Could you clarify the rules that are supposed to be applied so that we can understand the rationale of the change?

**Comment by gsmet** [comment]
Given what I understood of what you want to do, I would rather have:
`{product-name}`
`{product-name-first}`

(Not sure why you used `:attribute:`, the syntax in the adoc files should be `{attribute}`)

And I would recommend to actually adjust the first occurrence manually when the doc team start working on a guide. I'm not sure a script will be clever enough and will never create awkward things.

Also we need to be careful that all the occurrences you changed should be different in the product documentation. Not sure having RHBQ always makes sense (but maybe you already did it).

**Comment by rolfedh** [comment]
Hi @gsmet ,

Thank you for your insightful feedback. I created this Work-In-Progress (WIP) prototype to facilitate an emerging conversation with Stefan. In this particular instance, the goal is to replace Quarkus in a distinct set of output files rather than in the community documentation. It's still very much a work in progress.

I appreciate your note about the attribute syntax. I'll make the necessary adjustments in my next commit.

**Comment by rolfedh** [comment]
> And I would recommend to actually adjust the first occurrence manually when the doc team start working on a guide. I'm not sure a script will be clever enough and will never create awkward things.

A script will certainly not be able to handle every case. The intention would be to have it do the majority of the work, and have writers review and finalize the changes.

**Comment by rolfedh** [comment]
> > A script will certainly not be able to handle every case. The intention would be to have it do the majority of the work, and have writers review and finalize the changes.
> 
> My point is that it would probably be easier to handle it manually when taking a guide under your umbrella rather than in bulk, given it's going to be a change for one occurrence only at the top of the file.
> 
> But I suppose YMMV.

**Comment by rolfedh** [comment]
> My point is that it would probably be easier to handle it manually when taking a guide under your umbrella rather than in bulk, given it's going to be a change for one occurrence only at the top of the file.

For the community docs, both attributes would be defined as:
```
:product-name-first: Quarkus
:product-name: Quarkus
```
In the product docs, they might be defined as:
```
:product-name-first: Red Hat Build of Quarkus (RHBQ)
:product-name: RHBQ
```
The underlying intention, which I should have articulated sooner, is to enable us to address potential Red Hat product naming requirements _without_ burdening community contributors.

**Pull request closed without merging**
