### PR TITLE
Add property required for unit testing

### LINKED ISSUE #9020: [doc] [quarkis-test-amazon-lambda] Example missing required property
**Describe the bug**
The example at https://quarkus.io/guides/amazon-lambda#integration-testing does not work when applied to an existing project.

**Expected behavior**
The test should run and complete.

**Actual behavior**
The test hangs.

**To Reproduce**
1. Create a simple Quarkus application
2. Add amazon-lambda dependencies, and add a unit test to exercise it
3. Run the test, it hangs.

I will skip ahead to the solution which is to include in the `source/test/resources/application.properties` version the following line (as found within the Quarkus own integration test):

`quarkus.lambda.enable-polling-jvm-mode=true`

### PR DESCRIPTION
**Pull request by jmkgreen**
Fix #9020

### CODE REVIEW

**Review by oztimpower — COMMENTED** [review]
Can I suggest something a little more detailed?

```
To use the integration tests in your project there is a required property, in `src/test/resources/application.properties`. If not included, the integration tests will be in a constant loop.

[source,shell]
----
quarkus.lambda.enable-polling-jvm-mode=true
----

NOTE: If you are following along with the example Maven archetype project for AWS Lambda in this guide,
it includes the required property `quarkus.lambda.enable-polling-jvm-mode=true` in the test `application.properties`.

```

**Comment by oztimpower** [comment]
Thanks for highlighting this, for anyone manually adding the tests to an existing project. Yes the property is required. The example Maven archetype includes this property, the guide was assuming someone was following along, it's important to also highlight this to not confuse. 

I've added a suggestion along these lines.

**Comment by geoand** [comment]
What's the status of this one folks?

**Comment by oztimpower** [comment]
Documentation update is needed -- however the message could be a little nicer was my view. I have documentation updates pending on this one, that actually have my suggested alternative (above) in it.  So either accept this one, and then I can submit my other documentation updates.

I'm waiting for this one to be approved or closed either way.  

@jmkgreen any chance you can make the update to the docs to a friendlier message?

**Comment by jmkgreen** [comment]
@oztimpower I have taken your suggestion and applied it.

**Comment by oztimpower** [comment]
Thanks, can you also squash the commits? (git rebase -i HEAD~2 on the branch)

**Comment by jmkgreen** [comment]
@oztimpower Can this can be done through the web interface? I didn't bother to check out the project for such a small change!

**Comment by geoand** [comment]
> @oztimpower Can this can be done through the web interface? I didn't bother to check out the project for such a small change!

Not that I know of

**Comment by oztimpower** [comment]
There is a branch created by default, jmkgreen/patch-1.  You should be able to see that?

**Comment by jmkgreen** [comment]
@oztimpower that's what I edited to provide your patch. I may need to check it all locally to flatten the commits. Sorry, working on paid-for stuff daytimes and looking after twin babies in the evenings leaves little time! I'll have a quick go when I finish in a bit.

**Comment by jmkgreen** [comment]
Right, rebased. Now I'm showing a merge from origin - does this also get seen within the PR?

**Comment by oztimpower** [comment]
Close this PR and try again?  

Once you have rebased on a branch (locally), and squashed the commits, you then need to force push the update to the remote (git push -f)

Alternatively just close this and I will submit one in it's place?  I have documentation updates to submit, which include this one (same text).

Appreciate time is sparse, congrats on the twin babies, I have two of my own young kids, and also do majority of this out of hours

**Comment by gsmet** [comment]
This one is now in conflict with what we have in master.

@patriot1burke could you check if this is still useful with the latest changes and incorporate it somewhere if so?

**Pull request closed without merging**
