### PR TITLE
Close the deployment CL in the creator when augmenting

### PR DESCRIPTION
**Pull request by gsmet**
:warning: better reviewed by ignoring whitespaces: https://github.com/quarkusio/quarkus/pull/41437/files?diff=unified&w=1

Currently, we pass the CL to something that will close it, rather than controlling the lifecycle in the creator method.

This is an issue in native ITs:

```
java.lang.RuntimeException: java.lang.IllegalStateException: This class loader has been closed
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:373)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalStateException: This class loader has been closed
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.ensureOpen(QuarkusClassLoader.java:716)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:495)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.performCustomBuild(AugmentActionImpl.java:158)
	at io.quarkus.test.junit.IntegrationTestUtil.handleDevServices(IntegrationTestUtil.java:297)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:199)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:169)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
```

Related to #41233

### CODE REVIEW

**Comment by geoand** [comment]
> rather than controlling the lifecycle in the creator method

Where is this done?

**Comment by gsmet** [comment]
It's currently closed here: https://github.com/quarkusio/quarkus/pull/41437/files#diff-92a09477a9d02a6d2dce74439457fdedbce132e0a16473b07c9a98005bdf76b8L184-L187

**Comment by geoand** [comment]
That's my question, where does it get closed with this change?

**Comment by gsmet** [comment]
Ah, OK. I use `try with resources` to close them.

**Comment by geoand** [comment]
Gotcha, thanks

**Review by geoand — APPROVED** [review]

**Pull request merged**
