### PR TITLE
Keycloak devservices multiple realms

### LINKED ISSUE #28031: Allow multiple realms to be configured with quarkus.keycloak.devservices.realm-path (multi-tenancy)
### Description

For the keycloak devservice, it is possible to define the property `quarkus.keycloak.devservices.realm-path` with a realm.json which initializes the dev service.

This works great if you only need one realm. File content -> `{ ... }`

It does not work, when more than one realm are needed.
It would be great if one could define an array of realms inside the realm.json of which all are getting initialized. File content -> ```[
{ ... }, 
{ ... }
]```
Currently, a file like this simply gets ignored.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #28031.

Summary of the changes:
- Treats `quarkus.keycloak.devservices.realm-path` as a list of realm names
- Consolidates the way the realms are uploaded for both Quarkus based and WildFly based KC distributions
- Updates `KeycloakTestClient` to support acquiring realm specific tokens, the current methods can be considered shortcuts when only one realm is available
- The changes are tested in `quarkus-quickstarts/security-openid-connect-multitenancy` as the main branch's integration-tests oidc tenancy tests are too complex by this stage, https://github.com/quarkusio/quarkus-quickstarts/pull/1185, I had to rework it a bit to use `TenantConfigResolver` instead of `TenantResolver` (dynamic resolution vs static resolution) - since Dev Services for KC can't provide tenant specific URLs - it does not know how to map specific requests to specific tenant configs - therefore using the dynamic resolution works best - custom  `TenantConfigResolver` can build tenant specific URLs based on the base KC URL set by Dev Services for KC.
- Updated `security-openid-connect-multitenancy.adoc` to align with the quickstart changes, explaining why resolving tenant configurations dynamically aligns better with using Dev Services for KC for testing, showing how to test.

- Dev UI and `provider.html`: updated it to let users select realms, client ids for all the grants, for the code one it was tricky because to complete it after KC redirects back to SPA it needs to know the realm and client id so I ended up encoding it in the state query which KC returns.
- I spent a lot of time trying to figure how how to handle multiple realms where each realm may have more than one client - ideally, selecting a realm would automatically refresh the client selection list - but I thought it would be too much of a change at this stage, so if more than one realm is used then the client id has to be entered manually, for the typical case of a single realm, the configured client id will be set
- Client secrets - working on supporting multiple realms where each client can have its own secret highlighted that it is just a bad idea to try to handle all of these secrets in SPA, ex, use local storage to preserve it during the redirect, or encode it in the state query and pass it around - as the users can use real production realm files. The only exception is to preserve the current support for clients with secrets, where `quarkus.oidc.credentials.secret` is configured in a single realm file case. For all other cases it is really expected that it is the public clients which are used from this SPA - which is what is expected in production as well. I've also tweaked `KeycloakDevServicesProcessor` not to try to generate a default secret for cases where custom realms are used - as it does not make sense - the realm will def have a different secret for this client anyway 
- Updated DevServices for KC doc, incl the images

I expect a few more PRs will follow to polish `provider.html`, specifically, making it easier to select client ids as suggested above, we can read available `RealmRepresentations` and get the client info, skipping some client definitions which are known to be KC specific admin clients etc

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hey @mkouba @phillip-kruger 

I can't get the simple `for` expression working in https://github.com/quarkusio/quarkus/pull/28327/commits/c5833b15f5e84aebd0387daa8feeb950631fd229, specifically, the problem is with this line:
https://github.com/quarkusio/quarkus/pull/28327/commits/c5833b15f5e84aebd0387daa8feeb950631fd229#diff-76d8d6a4facb0ecf128685e59c5d99a1f53e69b9702ac0e70908b9d8dd3f155cR448

where I'm getting `Entry "realms" not found in the data map in expression {realms}`.

I've tried both `var realms = info:keycloakRealms??.split(",");` and `var realms = (info:keycloakRealms??).split(",");`, not sure what am I missing ? Must be something trivial :-)

**Comment by sberyozkin** [comment]
Thanks @mkouba, will give it a go

**Comment by sberyozkin** [comment]
Using the `let` section made a difference, thanks Martin

**Comment by sberyozkin** [comment]
Forgot I temporarily commented out the code checking the realm file modification date, so re-enabled it, now it is a set of dates

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Pull request merged**
