### PR TITLE
Replace oidc auth apple screenshots with generic ones

### LINKED ISSUE #42549: Remove references to Renarde in https://quarkus.io/guides/security-openid-connect-providers
### Description

The https://quarkus.io/guides/security-openid-connect-providers doc is about showing with some sample images, the typical process for registering an application with a given provider.

Originally, I copied a few of those images from Renarde docs. It can be causing the confusion that this is indeed how Renarde applications must be registered.

So this issue is about replacing images referencing Renarde with more neutral images

CC @Sanne 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by rghara**
Replace oidc auth apple screenshots with generic ones

Related to #42549

### CODE REVIEW

**Comment by rghara** [comment]
Hi @sberyozkin,
PR request raised.

**Review by sberyozkin — APPROVED** [review]
Thanks @rghara, please follow with the X updates and then we will get the issue resolved, thanks

**Comment by rghara** [comment]
> Thanks @rghara, please follow with the X updates and then we will get the issue resolved, thanks

Sorry @sberyozkin I am not sure if I understand what you mean with the X updates. I already changed the PR to have only one commit. Was that your ask? Or is it a different thing?

**Comment by sberyozkin** [comment]
@rghara My apologies, I meant that after this PR is merged, one more will be needed to actually fix the linked issue, to update X ( formely Twitter) images. 

Why did you merge the main branch though into this PR, please don't do it, if you need to sync up the PR with the main branch, you need to rebase, we updated the Contribution guide to explain howvto do it, but you don't really need to rebase these PRs either.

Now this PR has become invalid,  please recreate it with the original single commit, I can do if you'd like

**Comment by sberyozkin** [comment]
@rghara See #45116, thanks

**Comment by rghara** [comment]
> @rghara My apologies, I meant that after this PR is merged, one more will be needed to actually fix the linked issue, to update X ( formely Twitter) images.
> 
> Why did you merge the main branch though into this PR, please don't do it, if you need to sync up the PR with the main branch, you need to rebase, we updated the Contribution guide to explain how to do it, but you don't really need to rebase these PRs either.
> 
> Now this PR has become invalid, please recreate it with the original single commit, I can do if you'd like

> @sberyozkin

I got confused. Now it is clear. I'll redo the PR.

**Pull request closed without merging**
