### PR TITLE
Fix RESTEasy ImageIO leak

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by jerboaa** [comment]
This looks good to me. I've confirmed on a local build of quarkus 1.11 with this patch, non-graphics apps no longer pull in that stack for no reason.

**Comment by gsmet** [comment]
Thanks for confirming @jerboaa !

**Review by gastaldi — APPROVED** [review]

**Comment by zakkak** [comment]
@gsmet this indeed fixes the issue for most tests but we still see issues on the following tests:
* quarkus-integration-test-main-999-SNAPSHOT-runner
* quarkus-integration-test-hibernate-orm-panache-999-SNAPSHOT-runner
* quarkus-integration-test-spring-web-999-SNAPSHOT-runner
* quarkus-integration-test-liquibase-999-SNAPSHOT-runner
* quarkus-integration-test-tika-999-SNAPSHOT-runner

IT main (which includes ImageIOTestCase) and IT tika are known to have dependencies on AWT, but what about the rest?
Can someone confirm whether their really depend on graph libraries?

**Comment by jerboaa** [comment]
When debugging `quarkus-integration-test-spring-web` ImageIO class gets loaded via AnalysisMethod `com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$10.parse`. That turns out to be coming from:
`lib/org.glassfish.jaxb.jaxb-runtime-2.3.3-b02.jar` Once you find where the source code of that actually is we arrive here:
https://github.com/eclipse-ee4j/jaxb-ri/blob/2.3.3-b01-RI-RELEASE/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/impl/RuntimeBuiltinLeafInfoImpl.java#L48

Is this expected?

**Comment by jerboaa** [comment]
I'm guessing it's a different issue, but causing a similar problem.

**Review by zakkak — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
As for the rest of the problematic tests, it looks like they all depend on JAXB explicitly and I think the behavior was probably preexisting.

Note that even for RESTEasy, that might be something we would want to reconsider now that we have proper ImageIO support. The provider detection works well IF the consumes/produces are properly defined and in this case, the provider is not included.

We didn't have any report asking for this support so far so we can keep it like that for now but that's something we might reconsider later.

**Pull request merged**
