### PR TITLE
generate get/set for public fields in order to support @JvmField annotations as well.

### PR DESCRIPTION
**Pull request by evanchooly**
An earlier change fixed a handful of bugs and expose this rather odd one.  In an earlier PR, I had changed `Address` to extend `PanacheEntityBase` to test parameterization of the id type.  I simply copied the class body from `PanacheEntity` to `Address` and ran the tests.  These all worked on the JVM but failed on the native tests due, in part, to the `@JvmField` annotation.

The presence of this annotation suppresses the generation of `get`/`set` methods.  Since these methods are not present, they can not be scanned and cataloged by the native image tool.  Generally since kotlinc generates get/set methods automatically, there is no need for quarkus to generate them as we do for Java.  However `@JvmField` changes that story and this PR adjusts quarkus to properly account for it.

in general, `@JvmField` has a limited scope where its use is warranted.  It was an oversight to leave that annotation on `PanacheEntity` and so this PR cleans that up as well.

### CODE REVIEW

**Comment by geoand** [comment]
I'll be on PTO on Monday (and won't have much time over the weekend either) so don't wait for my review 😎

**Comment by evanchooly** [comment]
no worries.  i thought you might appreciate the explanation at the least.  have a great weekend.

**Comment by geoand** [comment]
Make no mistake, I'll read up on the PR, I just don't want to hold it up pending my review.

**Comment by geoand** [comment]
And thanks for the detailed explanation!

**Review by FroMage — CHANGES_REQUESTED** [review]
LGTM. IIUC you now generate accessors if they don't already exist.

Now the question is: are you sure you substitute the user's direct field accesses with those accessors? ORM with Panache for Java does that, but I'm not sure if you've disabled this for Kotlin or not.

If you generate the accessors but don't replace field accesses, they won't ever be called.

**Comment by evanchooly** [comment]
Visual inspection seemed to indicate we were good there but I will definitely double check.

**Comment by FroMage** [comment]
We have an existing test for Java where we verify that reading/writing the field does indeed call the accessor methods. Should be easy to copy.

**Comment by evanchooly** [comment]
is it this test?  https://github.com/evanchooly/quarkus/blob/cec3afe7b06b50bd0f3b72a7d5b980568d84e83b/integration-tests/hibernate-orm-panache-kotlin/src/main/kotlin/io/quarkus/it/panache/kotlin/TestEndpoint.kt#L814

**Comment by evanchooly** [comment]
An excellent point!  hrm.  the intersection of how that entity is defined and `@JvmField` is ... all but nonexistant.  I might need to `asm` my way to a unit test to ensure this.

**Comment by evanchooly** [comment]
I added a test that accesses the id field directly and in the diff of pre-/post-quarkifying, i can see that it goes from `getfield` to `invokevirtual` in the bytecode of the class.  Now, I can write a test that uses `asm` to verify that if you'd like but it feels like overkill.  What do you think?

**Comment by FroMage** [comment]
> I added a test that accesses the id field directly and in the diff of pre-/post-quarkifying, i can see that it goes from getfield to invokevirtual in the bytecode of the class. Now, I can write a test that uses asm to verify that if you'd like but it feels like overkill. What do you think?

Why not just make the fields use `@JvmField` and the existing test will be enough, no?

**Comment by evanchooly** [comment]
because "JvmField cannot be applied to a property with a custom accessor"

**Comment by FroMage** [comment]
> because "JvmField cannot be applied to a property with a custom accessor"

So you're saying you can't write this:

```kotlin
@JvmField
public field : Integer;
public fun getField(): Integer {
 return field
}
```
Is that it?

**Comment by evanchooly** [comment]
> > because "JvmField cannot be applied to a property with a custom accessor"
> 
> So you're saying you can't write this:
> 
> ```kotlin
> @JvmField
> public field : Integer;
> public fun getField(): Integer {
>  return field
> }
> ```
> 
> Is that it?

Hrm.  I'll try that.  it's not exactly idiomatic so it hadn't occurred to me write the custom getter that way.  But we're already far afield from idiom so why not?

**Comment by FroMage** [comment]
> Hrm. I'll try that. it's not exactly idiomatic so it hadn't occurred to me write the custom getter that way. But we're already far afield from idiom so why not?

It's not idiomatic, but it's the only way by which one could start with a `@JvmField` and want to make sure that changing it to an accessor later remains bytecode-compatible for all users of the class, no?

OTOH, if Kotlin does something specific and turns field accesses into getter calls if you have a `@JvmField` and an accessor, we wouldn't be testing our transformer.

**Comment by evanchooly** [comment]
That last test should do the trick.

**Review by FroMage — APPROVED** [review]
LGTM.

**Comment by evanchooly** [comment]
Great, thanks.  once the tests wrap up (and pass) i'll merge.

**Pull request merged**
