### PR TITLE
Add `<scm>` info to Quarkiverse projects

### PR DESCRIPTION
**Pull request by gastaldi**
Also bumps the Quarkiverse parent to 15

### CODE REVIEW

**Comment by holly-cummins** [comment]
What problem are we solving with this change?

**Comment by gastaldi** [comment]
@holly-cummins it fixes the `Scm-Connection` entry in the MANIFEST.MF (as introduced in https://github.com/quarkiverse/quarkiverse-parent/pull/94/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R274) of the released JARs to the correct place. 

Using the parent's `<scm>` in Quarkiverse extensions is wrong (since it points to https://github.com/quarkiverse/quarkiverse-parent) and because each Quarkiverse extension has its own repository, I believe it makes sense to have a specific `<scm>` section for them.

**Comment by gastaldi** [comment]
I understand that https://github.com/quarkusio/quarkus/commit/b8fd4985e6a0adc306f9ae1b4f503a43a8f009fd works for cases where the SCM isn't defined, but I believe that specifying the `<scm>` is safer for publishing, as it doesn't assume any repository (eg. you can host the extension in GitLab or other Git servers of your choice)

**Comment by holly-cummins** [comment]
I remain dubious that the information quality in this will be very high. :) However, I agree that the problems you describe, @gastaldi, are real ones. 
- Any pom which inherits from a parent with `<scm>` information already has totally-wrong `scm` information in its derived maven model. Since the quarkiverse parent has an `scm` entry, this applies to many extensions in the Quarkiverse. In the Quarkus tooling, we had to work around this and not look at remote poms when reading `scm` information from the maven model.  
- Extensions using the new version of the parent will be exposing the incorrect information via the Scm-Connection entry in the MANIFEST.MF, so it matters that it's incorrect.

in an ideal world, the maven jar plugin wouldn't read remote scm information since it will obviously be wrong, but I think that's too much to hope for. :)

**Review by gsmet — APPROVED** [review]
We will need to be strict on the repository naming.

**Comment by aloubyansky** [comment]
> I remain dubious that the information quality in this will be very high. :) However, I agree that the problems you describe, @gastaldi, are real ones.
> 
> * Any pom which inherits from a parent with `<scm>` information already has totally-wrong `scm` information in its derived maven model.

Yes, if the parent is in a different code repository. Every project is meant to configure its SCM though, including general-purpose parent POMs.

> Since the quarkiverse parent has an `scm` entry, this applies to many extensions in the Quarkiverse. In the Quarkus tooling, we had to work around this and not look at remote poms when reading `scm` information from the maven model.

Right, more than that, AFAICS, we give preference to the SCM read from the environment variables over the one present in the POM, so it we should be good?

> * Extensions using the new version of the parent will be exposing the incorrect information via the Scm-Connection entry in the MANIFEST.MF, so it matters that it's incorrect.
> 
> in an ideal world, the maven jar plugin wouldn't read remote scm information since it will obviously be wrong, but I think that's too much to hope for. :)

We do cut it off though when we generate the extension descriptor.

**Comment by aloubyansky** [comment]
Agreed, Maven is annoying in many ways.

**Pull request merged**
