### PR TITLE
Nats Server Extension

### PR DESCRIPTION
**Pull request by YunaBraska**
Please help,

Is here an example where I can see and understand the concept of test extensions?
I am new to Quarkus and want to write a test extension which spins up the [NatsServer](https://nats.io). (See also my [other integrations](https://yunabraska.github.io/nats-server/)).
It will be easier to integrate also the [NatsJavaClient](https://github.com/nats-io/nats.java)
The Guide [Writing Extensions](https://quarkus.io/guides/writing-extensions) does not help much without understanding.
I have just copied things without understanding from [Beldung](https://github.com/eugenp/tutorials/tree/master/quarkus-modules/quarkus-extension/quarkus-liquibase)

How can I translate the following concept to Quarkus?:
```java
@NatsTestServer(
        port = 4680,
        keepAlive = true,
        timeoutMs = 10000,
        version = "3.0.0",
        configFile = "my.properties",
        downloadUrl = "https://example.com",
        binaryFile = "/tmp/natsserver",
        config = {"ADDR", "localhost"}
)
class NatsServerFirstTest {

    final NatsServer natsServer = getNatsServer();

    @Test
    void natsServerShouldStart() {
        assertThat(natsServer, is(notNullValue()));
    }
}
```

### CODE REVIEW

**Comment by gsmet** [comment]
Hi,

If the idea is to start a server in test and dev mode, I think a dev service would be more appropriate. That is if there exists a Docker image for the Nats server. Can you confirm if it could be an option?

In any case, this will need to be hosted as a standalone extension in the Quarkiverse though.

/cc @gastaldi

**Comment by YunaBraska** [comment]
Hi @gsmet 

I am not sure what "dev service" means in the Quarkiverse. (@YunaBraska == Quarkus noob)
What I was looking something similar as in other frameworks. Like to have a simple test annotation where you can configure and spin up the service.
It would also be nice to spin up the service in the Native Integration tests.
Docker is not needed for this service.

**Comment by gsmet** [comment]
@YunaBraska see https://quarkus.io/guides/dev-services for a nice introduction.

The nice thing about it is that it can start the server both in dev mode and for tests. You can find an example in https://github.com/quarkusio/quarkus/tree/main/extensions/elasticsearch-rest-client-common . This one is using Testcontainers but is packaged as an extension, which is probably what you want to do.

The nice thing about Dev Services is that you can also pass configuration properties and in your context, you could have configuration properties for the client and a client injectable via CDI.

We usually use Testcontainers to start a Docker container. But you can implement it without a container. Typically for H2, we start a H2 server directly: https://github.com/quarkusio/quarkus/blob/main/extensions/devservices/h2/src/main/java/io/quarkus/devservices/h2/deployment/H2DevServicesProcessor.java#L39 .

As for the discussion about the Quarkiverse, we have too many modules in the Core so we try to host most of the extensions outside of it in the Quarkiverse nowadays. There is a nice infrastructure for easy releases and documentation publishing.

See https://github.com/quarkiverse/quarkiverse/wiki#getting-an-extension-onboarded .

Not sure if all of this makes sense?

Feel free to ask questions, we will be happy to help.

**Comment by YunaBraska** [comment]
Thx @gsmet 
So you suggest me to create my extension outside this quarkus repository and create a standalone Dev-Service "extension"? I will check the Material/Links. looks promissing. But also kind of wired with the non type safety args and just "random" Classes as QuarkusTestResources. Is it possible and is there an example to provide a own Test Annotation?

**Comment by gastaldi** [comment]
I'm closing this PR. Please open an `Extension Proposal` issue if you'd like to make it a Quarkiverse extension.

Thanks!

**Pull request closed without merging**
