### PR TITLE
Runtime (re)initialize Netty's PlatformDependent classes

### LINKED ISSUE #17839: Invalid memory configuration for netty maxDirectMemory in native image
I thinks this only concerns native image builds.

Setting either 
-XX:MaxDirectMemorySize
or 
-Dio.netty.maxDirectMemory
does not work at runtime and runtime memory is incorrectly reflected in io.netty.util.internal.PlatformDependent.DIRECT_MEMORY_LIMIT
at runtime.

i think the problem is that io.netty.buffer.PooledByteBufAllocator uses  io.netty.util.internal.PlatformDependent
which is not initialized during runtime but build time.

I tested this with Quarkus 1.10.5.Final, but looking at the current code of NettyProcessor shows that PlatformDependent is still not initialized at runtime, only PooledByteBufAllocator is.

### PR DESCRIPTION
**Pull request by zakkak**
Closes https://github.com/quarkusio/quarkus/issues/17839

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
I'm surprised it is so simple. Pretty sure @gsmet and I tried that already.

Obviously, GraalVM has changed a lot in between.

**Comment by cescoffier** [comment]
Actually, I use the same trick for the array offset issue.

**Comment by zakkak** [comment]
> I'm surprised it is so simple. Pretty sure @gsmet and I tried that already.

Yes, it was not that simple before. We needed to also disable Unsafe which turned out to have performance issues (see https://github.com/quarkusio/quarkus/pull/31016 and https://github.com/quarkusio/quarkus/issues/32289). Thanks to @franz1981's work in https://github.com/netty/netty/pull/13643 we no longer need to disable Unsafe for the re-initialization making things pretty simple.

**Comment by gsmet** [comment]
The error is unrelated: `2023-11-28T09:01:15.9218680Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking status of builder image 'quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21'
2023-11-28T09:01:30.9684851Z Error response from daemon: Get "https://quay.io/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`.

**Review by gsmet — APPROVED** [review]
Nice it has become so simple \o/.

**Comment by gsmet** [comment]
@zakkak actually, I think it doesn't work.

We had these failures lately:
```
2023-11-29 09:30:46,719 INFO  [io.grp.net.Net.connections] (vert.x-eventloop-thread-0) Transport failed: java.lang.NullPointerException
	at io.netty.util.internal.PlatformDependent0.getLong(PlatformDependent0.java:650)
	at io.netty.util.internal.PlatformDependent0.directBufferAddress(PlatformDependent0.java:625)
	at io.netty.util.internal.PlatformDependent.directBufferAddress(PlatformDependent.java:525)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.initMemoryAddress(PooledUnsafeDirectByteBuf.java:64)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.init(PooledUnsafeDirectByteBuf.java:54)
	at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:615)
	at io.netty.buffer.PoolChunk.initBuf(PoolChunk.java:597)
	at io.netty.buffer.PoolChunk.allocate(PoolChunk.java:354)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:216)
	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:180)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
```
and I'm pretty sure they are related.

I will try to revert and see how it goes.

You can see the details of the failures here for instance: https://github.com/gsmet/quarkus/actions/runs/7023535365#summary-19117391342

**Comment by franz1981** [comment]
I haven't followed the discussion, but that stacktrace means that `UNSAFE` isn't populated at https://github.com/netty/netty/blob/84a13a92e1d757965438dc41a5611b19dd47ec44/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L650

enabling logging when `PlatformDependent0` static init run could be helpful

**Comment by jerboaa** [comment]
@gsmet FWIW, we see similar failures in our CI.

See: https://github.com/graalvm/mandrel/actions/runs/7026828114/job/19121127385#step:12:906

**Comment by zakkak** [comment]
It indeed seems related, but how come the CI didn't catch it?

I will try to reproduce locally to better understand what's going on.

**Comment by gsmet** [comment]
@zakkak I think it did catch it but as we had other issues related to quay being unresponsive we probably missed it.

(I contacted the people at quay to see what's going there)

**Comment by zakkak** [comment]
> @zakkak I think it did catch it but as we had other issues related to quay being unresponsive we probably missed it.

it looks like the test didn't run (although it was built), see https://github.com/quarkusio/quarkus/actions/runs/7015924713/job/19093162099#step:14:430 It doesn't look llie a quay thing to me, but I also don't understand what happened and it didn't run.

Anyhow back on the actual issue, it looks like netty sees `-Dio.netty.noUnsafe: true` at runtime which seems to be set in https://github.com/quarkusio/quarkus/blob/d7842f983f719c19785080da7179ce9c02c9e80a/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java#L208 which was added in Quarkus 0.8.0 and I can't see from the PR or commit message why so I will toy with it.

**Comment by gsmet** [comment]
Hum, I wonder if we have a problem with the build cache.

**Comment by zakkak** [comment]
```diff
diff --git a/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java b/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java
index 58201a89f0b..7e11774606f 100644
--- a/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java
+++ b/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java
@@ -205,7 +205,6 @@ InfinispanPropertiesBuildItem setup(ApplicationArchivesBuildItem applicationArch
         additionalBeans.produce(AdditionalBeanBuildItem.builder().addBeanClass(InfinispanClientName.class).build());
         additionalBeans.produce(AdditionalBeanBuildItem.builder().addBeanClass(Remote.class).build());
 
-        systemProperties.produce(new SystemPropertyBuildItem("io.netty.noUnsafe", "true"));
         hotDeployment
                 .produce(new HotDeploymentWatchedFileBuildItem(META_INF + File.separator + DEFAULT_HOTROD_CLIENT_PROPERTIES));
 
```

Seems to resolve the issue. Not sure yet if it causes any other issues though.
Being tested in https://github.com/zakkak/quarkus/actions/runs/7032713931

I will open a PR if things look good.

**Comment by gsmet** [comment]
@karesti @wburns do you remember why Infinispan is setting `-Dio.netty.noUnsafe=true` in the Quarkus extension?

If there's no good reason, we will probably drop it.

**Comment by wburns** [comment]
> @karesti @wburns do you remember why Infinispan is setting `-Dio.netty.noUnsafe=true` in the Quarkus extension?
> 
> If there's no good reason, we will probably drop it.

At the time I believe it was just because we didn't support UNSAFE in netty so we were using the property to "hint" to not initialize things related to it. As long as Netty native code is working now, there is no reason to have the property.

**Comment by gsmet** [comment]
Thanks @wburns !

**Pull request merged**
