### PR TITLE
Bump Kotlin version to 1.5.21

### PR DESCRIPTION
**Pull request by kny78**
Just bumping kotlin to 1.5.21

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
Hmmm, this PR was against the 2.1 branch, we should have been more careful. PRs need to be created for `main`.

I will push this update to `main`.

**Comment by geoand** [comment]
Oh... I never saw that...

My bad

**Comment by gsmet** [comment]
Yeah same here. Spotted it while trying to backport it.

**Comment by geoand** [comment]
Maybe we could have the bot add a warning message? Unless the user doing it is you 😆

**Comment by kny78** [comment]
So now I know that everything goes to the main branch. My thought was that it would be automatically applied to main as well as the release branch :-O

**Pull request merged**
