### PR TITLE
Fix createLiquibase mongodb connection string handling

### LINKED ISSUE #26655: LiquibaseMongodbFactory.createLiquibase() check for database name in database connection string is broken
With mongodb connection string as following:
`mongodb+srv://user:password@cluster0.1234.mongodb.net/?retryWrites=true&w=majority`
createLiquibase will fail with 
`IllegalArgumentException: Database not specified in URL`
even if database name is specified. 
Maybe 
`Pattern HAS_DB = Pattern.compile("(mongodb|mongodb\\+srv)://[^/]*/.*");` 
should support connection string with properties in it.

Also if HAS_DB will pass, createLiquibase() method will just concatenate database name to connection string
`connectionString += "/" + this.mongoClientConfig.database....`
which will lead to the same exception as database name is placed after connection properties in db url as following:
`mongodb+srv://user:password@cluster0.1234.mongodb.net/?retryWrites=true&w=majority/databaseName`

Quarkus version 2.10.2

### PR DESCRIPTION
**Pull request by paloliska**
Handling of mongodb connection string now preserves connection options in LiquibaseMongodbFactory.createLiquibase()

Fixes #26655

### CODE REVIEW

**Comment by gsmet** [comment]
I force pushed to rebase and fix the formatting issues.

**Comment by paloliska** [comment]
> I force pushed to rebase and fix the formatting issues.

@gsmet thank you

**Review by loicmathieu — APPROVED** [review]
LGTM, I'm not a regex expert but it seems to be OK.

**Comment by gastaldi** [comment]
@loicmathieu should we backport this fix?

**Comment by loicmathieu** [comment]
@gastaldi we can but it's an enhancement so maybe it's not worth it.

**Pull request merged**
