### PR TITLE
Move @StaticInitSafe annotation to the proper package

### PR DESCRIPTION
**Pull request by radcortez**
Follow up of https://github.com/quarkusio/quarkus/pull/17483. Noticed that the annotation is not in the right location.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
OK. I must admit that both worked for me :).

**Comment by radcortez** [comment]
Indeed. But I notice we have all the annotations in the other package :)

**Comment by gsmet** [comment]
AFAICS, this was introduced in 2.1 so removing the 2.0 backport label.

**Comment by radcortez** [comment]
> AFAICS, this was introduced in 2.1 so removing the 2.0 backport label.

Yes. That is why I also pushed now, so we don't have to deprecate stuff.

**Pull request merged**
