### PR TITLE
Upgrade to Mutiny 0.10.1

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by cescoffier** [comment]
Some recent security changes block the event loop. I've canceled the build until the security changes are reverted (See #13036 - @sberyozkin )

**Comment by Sanne** [comment]
thanks all, the Hibernate update is done: https://github.com/hibernate/hibernate-reactive/pull/426

@cescoffier I'll leave it in yuor hands to approve/merge when it works best for you. Thanks

**Comment by jponge** [comment]
I propose that once https://github.com/quarkusio/quarkus/pull/13036 has been merged/resolved I rebase this PR to get a clean CI run.

**Comment by Sanne** [comment]
@jponge I've approved and merged the #13036 : feel free to push a rebase here

**Comment by jponge** [comment]
@Sanne Thanks, let's see what the CI thinks of the upgrade.

**Comment by jponge** [comment]
Ok `Native Tests - IT-Data2` failed before it started 🤣

**Comment by jponge** [comment]
It worked on my machine:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:38 h
[INFO] Finished at: 2020-10-31T13:36:58+01:00
[INFO] ------------------------------------------------------------------------
```

**Review by cescoffier — APPROVED** [review]

**Comment by Sanne** [comment]
awesome, thanks all!

**Pull request merged**
