### PR TITLE
Rename quarkus-extension.yaml

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This avoids problems with the IDE overwriting changes
made by the bootstrap plugin.

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Review by ebullient — APPROVED** [review]

**Comment by gsmet** [comment]
@aloubyansky @ia3andy I think this requires further discussion. If it's a problem, shouldn't we change this to be the default when creating a new extension?

**Comment by ia3andy** [comment]
I agree with @gsmet:
- we would need to update the templates for new extensions
- keeping `.yaml` extension would be better(but maybe it's what making the IDE overwrite it?)

**Comment by Sanne** [comment]
> I think this requires further discussion

see the mailing list `[quarkus-dev] quarkus-extension.yaml vs QuarkusDevModeTest`, and follow up pr #17270

**Comment by ia3andy** [comment]
We also need to update the Quarkiverse extensions?

**Comment by ia3andy** [comment]
@Sanne I think it was a bit to rushy to merge this PR (even more with @gsmet and me saying we wanted a quick discussion to be sure there weren't better and more transparent alternatives). We come from a long WE and didn't have time to really look at the thread. Renaming all those have consequences outside of quarkus-core. 

Also, I think @aloubyansky said in the thread that he would prefer something else..

**Comment by aloubyansky** [comment]
> We also need to update the Quarkiverse extensions?

If it affects them. AFAIU, it breaks only when the QuarkusDevModeTest tests are launched from IDEA.

**Comment by ia3andy** [comment]
Ok my bad @Sanne , I missed the part were the old format was still compatible.. so with the following up PR from @aloubyansky we are alright!

**Comment by Sanne** [comment]
@ia3andy no problem at all :) but also I merely am the mindless bot who pressed the "merge" button: it was already approved and reviewed and CI flagged it as green.

**Pull request merged**
