### PR TITLE
Update to Apicurio Registry 2.1.1.Final and use Vert.x HTTP client

### PR DESCRIPTION
**Pull request by carlesarnal**
We (the Apicurio Team) released a new version of Registry recently. This PR updates the usage of Registry to the new version.

### CODE REVIEW

**Comment by carlesarnal** [comment]
cc @Ladicek

**Comment by Ladicek** [comment]
Ah does this have the new HTTP client SPI? I will dig out the commit I have to use that. That can be a separate PR I believe.

**Review by Ladicek — APPROVED** [review]

**Comment by carlesarnal** [comment]
> Ah does this have the new HTTP client SPI? I will dig out the commit I have to use that. That can be a separate PR I believe.

Yes. This also removes the need for Keycloak libraries. I can do the changes if you want, just give me the pointers to the code :).

**Comment by carlesarnal** [comment]
Ok, I've figured out what's going on with the failed build and I'm working to get it fixed. I'll ping here once is resolved.

**Comment by carlesarnal** [comment]
I've added a commit with something similar to what you did in yours but using the client on our side. Just check it when you have some time.

**Review by Ladicek — APPROVED** [review]

**Comment by carlesarnal** [comment]
@Ladicek any update on this? I would like to get this into the next release, if possible.

**Comment by Ladicek** [comment]
Ouch, I thought it's already merged. Whoops! Let me see if I can resolve the conflict real quick.

**Comment by Ladicek** [comment]
OK, done. Hopefully CI will end up green :-)

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I have no idea why these tests fail or if they're flaky :-/

**Comment by Ladicek** [comment]
Apparently these tests are flaky, so this is good to go!

**Comment by carlesarnal** [comment]
Nice, thanks for merging @Ladicek!

**Comment by Ladicek** [comment]
Thanks for your patience! :-)

**Pull request merged**
