### PR TITLE
Adds smallrye cloud events

### PR DESCRIPTION
**Pull request by kstrempel**
Adds the smallrye-reactive-messaging-cloud-events package to the quarkus-smallrye-reactive-messaging-amqp and quarkus-smallrye-reactive-messaging-kafka. 

Todo #1515

### CODE REVIEW

**Comment by cescoffier** [comment]
I believe I commented on the original issue. Even with such an extension, I don't believe it will work as the Kafka and AMQP connectors are not integrated with Cloud Events.

**Comment by kstrempel** [comment]
Hmm.. sad then I misunderstood you. I was thinking you wanted to add this to the kafka and amqp extensions.

**Comment by cescoffier** [comment]
We may add it, it's not clear how we are going to deal with cloud events in the connectors. Unfortunately, the SDK we were using has been very unstable, and each update was breaking. As cloud event is relatively simple, we may just not use the SDK.

**Pull request closed without merging**
