### PR TITLE
Expose quarkus.hibernate-orm.database.default-catalog and quarkus.hibernate-orm.database.default-schema as runtime properties

### LINKED ISSUE #19660: Expose quarkus.hibernate-orm.database.default-schema as runtime property
### Description

The property `quarkus.hibernate-orm.database.default-schema` is evaluated only at build-time only. It would be nice to configure this property during runtime.

Our engineering environments share database instances with other teams and occasionally, the same application will be deployed to the same database instance. This means that the schema names will change based on the environment.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #19660

Follow-up on  #22114, which upgrades to Hibernate ORM 5.6.2.Final.

But I confirmed locally that, when upgrading to a locally built version of ORM that includes https://github.com/hibernate/hibernate-orm/pull/4351, the test passes.

### CODE REVIEW

**Comment by yrodiere** [comment]
Rebased on `main` just now.

Now that  hibernate/hibernate-orm#4351 has been merged, I confirm that upgrading to Hibernate ORM 5.6.2-SNAPSHOT allows tests to pass. We just need a release of ORM 5.6.2.Final.

**Comment by yrodiere** [comment]
Rebased on main now that the upgrade to ORM 5.6.2.Final (#22114) was merged.

Ready for review!

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
