### PR TITLE
Make dependencies on bootstrap resolvers "provided" in quarkus-bootstrap-core

### PR DESCRIPTION
**Pull request by aloubyansky**
This change moves dependencies on the `quarkus-bootstrap-maven-resolver` and `quarkus-bootstrap-gradle-resolver` to scope `provided` in `quarkus-bootstrap-core`

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet I marked it as a potentially breaking change

**Review by gsmet — APPROVED** [review]
Awesome, thanks. This has been bugging me since forever.

**Comment by aloubyansky** [comment]
Just FYI, I'd like to get a green CI for this one before merging, just to be sure.

**Comment by gsmet** [comment]
I think the failing test could be an issue in this patch. I haven't seen it fail lately.

**Comment by gsmet** [comment]
@aloubyansky second run is green.

**Comment by aloubyansky** [comment]
I think it's good to merge then

**Pull request merged**
