### PR TITLE
Don't throw an exception when finishing a closed RESTEasy response

### PR DESCRIPTION
**Pull request by geoand**
Relates to: https://github.com/quarkusio/quarkus/issues/21762#issuecomment-985995830

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand my understanding is that this patch and the other related one should be backported to 2.5.2?

**Comment by geoand** [comment]
I believe they should

**Comment by gsmet** [comment]
Care to add the label then? Thanks! :)

**Comment by geoand** [comment]
Done :)

**Review by gastaldi — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
