### PR TITLE
Reduce required runtime dependencies for native build with Amazon services extensions

### LINKED ISSUE #11264: Amazon client requires both transport client implementations for native compilation
**Describe the bug**
The [AmazonClientTransportRecorder](https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-services/common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientTransportRecorder.java)
has both UrlConnectionHttpClient and ApacheHttpClient Code in the Runtime Recorder which seems to require both the respective dependencies during native image compilation.

**Expected behavior**
Only one of the dependencies is required during native image build time.

**Actual behavior**
Both of the dependencies are needed, which increases build time.

### PR DESCRIPTION
**Pull request by antonwiens**
Fixes #11264

### CODE REVIEW

**Comment by antonwiens** [comment]
@gsmet I had no time to create a project to try the fix out yet. Shall i already put it as ready for review or after i confirmed that it actually fixed the problem?

**Comment by gsmet** [comment]
Better check it fixes the issue, otherwise we wouldn't include this change!

**Comment by antonwiens** [comment]
I created a sample project which verifies the fix:

https://github.com/antonwiens/quarkus-test-project

submodule "success" uses locally build snapshot version of my bugfix branch and submodule "failure" includes 1.7.0.CR2.

Building the "failure" module with :failure:assemble fails due to 

> Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.

Building the "success" module with :success:assemble does not fail.

**Comment by gsmet** [comment]
Perfect, I thought that would be sufficient.

Could you get your PR out of draft?

**Comment by antonwiens** [comment]
Any idea why it failed? I don't anything meaningful in the details.

**Comment by gsmet** [comment]
We have some infra issue with the JDK 14 build.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Comment by gsmet** [comment]
And congrats for your first PR :).

**Pull request merged**
