### PR TITLE
Add dev UI for SmallRye Fault Tolerance

### PR DESCRIPTION
**Pull request by Ladicek**
This commit also updates SmallRye Fault Tolerance to version 5.4.1,
which brings some minor improvements and fixes; notably, it fixes
an issue with `@ApplyFaultTolerance` not being discovered properly.

### CODE REVIEW

**Comment by Ladicek** [comment]
Submitting as draft to let CI run in my fork first.

FTR, the resulting screen look like this:

Screenshot_20220624_115713

**Comment by gsmet** [comment]
Any chance the bugfix upgrade could be done separately? That's something I would like to backport, whereas I don't think I will backport the new Dev UI.

**Comment by gsmet** [comment]
Note: we can wait for the Dependabot PR and then rebase this one.

**Comment by Ladicek** [comment]
I can do that, sure.

**Comment by Ladicek** [comment]
I mean, the `@ApplyFaultTolerance` discovery fix includes a one-line change in the Quarkus extension too, so a simple dependabot bump isn't enough. (That fix isn't really a huge deal, but if we wanna backport it, then we should do it properly).

I'll submit a 2nd PR.

**Comment by Ladicek** [comment]
Second PR is up: #26404 I'll rebase this PR on `main` when that PR is merged.

**Comment by Ladicek** [comment]
Rebased and marking as ready for review.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
