### PR TITLE
Removal of unused appModel - minor fix

### PR DESCRIPTION
**Pull request by rsvoboda**
Removal of unused appModel - minor fix

### CODE REVIEW

**Comment by machi1990** [comment]
@rsvoboda looks like CI is not happy is not happy because of formatting issue. Can you have a look?

**Comment by rsvoboda** [comment]
@machi1990 forgot to remove unused import , fixed now

**Review by machi1990 — APPROVED** [review]
LGTM. Thanks.

**Comment by machi1990** [comment]
Merged thanks @rsvoboda

**Pull request merged**
