### PR TITLE
It should not be allowed to open a Mutiny.Session on a different thread than its users

### PR DESCRIPTION
**Pull request by Sanne**
I'm afraid this is necessary.

### CODE REVIEW

**Comment by FroMage** [comment]
Uh, OK, but then why? I thought we could just move the entire operations on the right IO thread? I mean, this works for all JUnit tests that used this, which are not using Vert.x threads.

**Comment by Sanne** [comment]
> I thought we could just move the entire operations on the right IO thread?

I need the *entire operation* running on the right IO thread; the way you did this, is to move only the opening of the Session.

By opening the `Mutiny.Session` on the IO thread you'we effectively bypassed the assertions which I had introduced in Hibernate Reactive, as we check us being on the expected thread only in the constructor of the session. So you were able to bypass my checks, but the reason to run things on the IO thread is that we need to ensure the responses from the DB are processed by the same thread as the one possibly scheduling additional IO operations which need to happen; otherwise you end up with multiple threads interleaving on the same shared mutable Session.

By *entire operation* I mean all operations on the same Session need to start and finish on the same thread; maybe I should add even stricter assertions in HR but we need to balance tradeoffs, e.g. performance costs of all these checks.

> I mean, this works for all JUnit tests that used this, which are not using Vert.x threads.

It appears to work, but it's not going to work for less trivial operations; unfortunately not easy to create a test to show you as they would fail only occasionally depending on threading and IO timings.

Also, it's still not enabling the assertions which I recommended to you earlier; I did this in https://github.com/quarkusio/quarkus/pull/18464 .

If you cherry pick say only https://github.com/quarkusio/quarkus/pull/18464/commits/7092f258e1d70b782bc1052bbf5bec72a2a5ecfd you'll see failures; and remember I want that flag to eventually be removed: it needs to be the default.

(I kept the two PRs separate as that other one is straight forward, while I expected some debate about this one. BTW I'd be happy to talk about this more later but I'm on PTO today)

**Comment by FroMage** [comment]
OK let's discuss it tomorrow, it can wait.

But I was under the impression that I could already get the session on the right IO thread, and that since the session would be obtained on an IO thread, all dependent `Uni` would get notified on it, and execute their queries on it, and be notified on it. So I guess I must be missing something.

**Comment by Sanne** [comment]
Excellent, many thanks for the explanation @FroMage !

**Pull request closed without merging**
