### PR TITLE
Kubernetes - Don't create a service account if not needed

### LINKED ISSUE #9283: control over kubernetes service account generation / kubernets-client issue
**Description**
using https://cloud.okteto.com the deployment fails as we setup service account  instead of using `default`.

Workaround is to have `quarkus.kubernetes.service-account=default` but then we still generate a service account unnecessarily.

furthermore quarkus kubernetes docs [states](https://quarkus.io/guides/kubernetes#using-the-kubernetes-client):

"some RBAC related resources are required (e.g. a ServiceAccount, a RoleBinding etc.). So, when the kubernetes-client extension is present, the kubernetes extension is going to create those resources automatically,"

i only added kubernetes extension, not kubernetes client. ... why is it then there ? 
if by implicit dependency; is there a way to avoid service-account to be defined/referenced ? 

and if i'm not using kubernets api in the deployment, isn't the kubernetes-client just making my native compilation much slower ?  

**Implementation ideas**
(If you have any implementation ideas, they can go here, however please note that all design change proposals should be posted to [the Quarkus developer mailing list](mailto:quarkus-dev@googlegroups.com) (or [the corresponding Google Group](https://groups.google.com/group/quarkus-dev); see [the decisions process document](https://github.com/quarkusio/quarkus/blob/master/DECISIONS.adoc) for more information).

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #9283 

The pull request fixes the condition under which we generate a service account.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by Ladicek** [comment]
This means we'll typically use the namespace's `default` service account, right? And we'll only create our own service account if we need some roles. Not sure if that's great.

I remember adding the TODO about the weird condition, so I assume this PR changes the behavior to what has always been intended. On the other hand, I also thought that we always generate a dedicated service account because this is a "best practice" in the Kubernetes world.

Not sure how to reconcile these 2 ideas :-)

**Comment by iocanel** [comment]
> I also thought that we always generate a dedicated service account because this is a "best practice" in the Kubernetes world.

The original intention was to generate as few resources as possible. So, the service account was meant to be optional (only generated when really needed, or if a service account is explicitly specified in `application.properties`).

Using the default service account is not considered the best idea **if you need to talk to the api server**, as it might pose a security risk. This case of course is well covered. So, I feel that in our cases minimalism is viable.

**Comment by iocanel** [comment]
I am merging, the existing code makes no sense. If @Ladicek has strong objections about not generating an SA by default, we can discuss it in another issue.

**Comment by Ladicek** [comment]
Nah, that's fine. I don't have _strong objections_, just doubts.

**Pull request merged**
