### PR TITLE
Lazily initialize (Reactive)MongoClient

### PR DESCRIPTION
**Pull request by snazy**
The (Reactive)MongoClient instances are eagerly created once the mongodb-client extension is being used.
If applications are pre-packages with multiple backend options and the user does not use MongoDB, the
eager client creation causes trouble like failing health checks and the application not terminating within
Mongo's default connect timeout (30 seconds).

[Nessie](github.com/projectnessie/nessie) for example offers multiple backend databases like Mongo, Dynamo and Rocks.

This PR does not introduce a functional change and keeps eager mongodb-client initialization. It adds
a new config-item to disable eager init so the mongodb-clients are created upon the first use (injection)
of a (Reactive)MongoClient.

PS: Would be nice to get this one backported to 2.4.

### CODE REVIEW

**Review by loicmathieu — CHANGES_REQUESTED** [review]
I'm not against it but it complexifies things a little.
Maybe we can just lazily initialize it all the time instead of having the hability to do both ?

Note that for JDBC we initialize it eagerly in all cases so this will make things not on par.

**Comment by geoand** [comment]
When done addressing the comments, please don't forget to squash the commits

**Comment by snazy** [comment]
> When done addressing the comments, please don't forget to squash the commits

GTK - squashed & rebased

**Review by dimas-b — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]
I don't see any problem with the proposal.

**Review by loicmathieu — CHANGES_REQUESTED** [review]

**Review by loicmathieu — CHANGES_REQUESTED** [review]

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks for your patience ;)

**Review by mamadaliev — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]

**Pull request merged**
