### PR TITLE
ArC - rework the way the build profile producer beans are disabled

### LINKED ISSUE #17583: ArC - rework the way the build profile/property producer beans are disabled
Currently, we add `@Alternative` and [remove `@AlternativePriority` if present](https://github.com/quarkusio/quarkus/pull/17570). However, if a user declares an `@Alternative` producer and enables it via `quarkus.arc.selected-alternatives` then `@UnlessBuildProperty` and friends would have no effect.

We could:
1. Remove `@Produces` and all scopes and known qualifiers/stereotypes (due to [Simplified Producer Method Declaration](https://quarkus.io/guides/cdi-reference#simplified-producer-method-declaration)), 
2. Remove all annotations (just in the context of `AnnotationStore`),
3. Introduce a new annotation, e.g. `@VetoedProducer` (note that `@javax.enterprise.inject.Vetoed` has `@Target({ ElementType.TYPE, ElementType.PACKAGE })`).

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #17583

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Nice and elegant!

**Review by manovotn — APPROVED** [review]
Looks good!

**Review by Ladicek — APPROVED** [review]
Looks good, but it would look even better with a test :-)

**Comment by mkouba** [comment]
> Looks good, but it would look even better with a test :-)

We have plenty of tests for `@IfBuildProfile` and friends...

**Comment by Ladicek** [comment]
Fair enough :-) I was thinking this would be a user-facing API as well, but the indirect tests are probably fine.

**Comment by mkouba** [comment]
> Fair enough :-) I was thinking this would be a user-facing API as well, but the indirect tests are probably fine.

Yeah, I forgot to mention that I did not document this annotation because I'm not sure whether it will be of any use for app developers and extension authors...

**Comment by manovotn** [comment]
> > Fair enough :-) I was thinking this would be a user-facing API as well, but the indirect tests are probably fine.
> 
> Yeah, I forgot to mention that I did not document this annotation because I'm not sure whether it will be of any use for app developers and extension authors...

That's a good point. Should we then put it under the [`impl` package](https://github.com/quarkusio/quarkus/tree/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl) which should contain the "internals" not exposed to users?

**Comment by mkouba** [comment]
> > > Fair enough :-) I was thinking this would be a user-facing API as well, but the indirect tests are probably fine.
> > 
> > 
> > Yeah, I forgot to mention that I did not document this annotation because I'm not sure whether it will be of any use for app developers and extension authors...
> 
> That's a good point. Should we then put it under the [`impl` package](https://github.com/quarkusio/quarkus/tree/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl) which should contain the "internals" not exposed to users?

So I've put the annotation intentionally in the `io.quarkus.arc` package as a "hidden" feature. I do admit that it's not very neat but I believe it's practical ;-).

**Comment by manovotn** [comment]
> So I've put the annotation intentionally in the io.quarkus.arc package as a "hidden" feature.

An untested hidden feature of Arc. How hideous of you :-D

**Comment by mkouba** [comment]
> > So I've put the annotation intentionally in the io.quarkus.arc package as a "hidden" feature.
> 
> An untested hidden feature of Arc. How hideous of you :-D

Well, it's definitely not untested ;-)

**Pull request merged**
