### PR TITLE
Disable MutinyTest#testSSE for now as it's unstable on CI

### PR DESCRIPTION
**Pull request by jaikiran**
Requesting approval to merge this one. Our other CI experiment PRs keep running into this one and we haven't been able to run those jobs to completion. This commit has been tested in @gsmet's https://github.com/quarkusio/quarkus/pull/11679 PR (which is currently open), so I don't think we have to wait for the whole 2-3 hours to merge this PR.

/cc @stuartwdouglas @geoand

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you @geoand

**Comment by geoand** [comment]
Thank you!

**Comment by cescoffier** [comment]
This test became unstable without any reason. Neither mutiny or resteasy mutiny have changed recently. 
I don't believe there is another SSE test (in native) at the moment.

**Comment by jaikiran** [comment]
Hello @cescoffier, I think at this point the CI has reached a completely unreliable state. So trying to make sense of some these failures is turning out to be almost impossible. It's very likely that this issue in this test is due to other factors and I think we should enable this back once the CI reaches some state of reliability (hopefully soon). There are some open PRs which are solely trying to resolve these CI issues. So once those reach some conclusive stage, I think we should just re-enable this test.

**Comment by jaikiran** [comment]
@cescoffier, things have now stabilized to a major extent in master branch. I will open a PR to revert this disabled test back to its previous state, either tonight or early tomorrow (just want to give a few hours for the CI to settle down and pending PRs to be processed before we start looking into this again).

**Comment by jaikiran** [comment]
I've now opened https://github.com/quarkusio/quarkus/pull/11727 to revert this change.

**Pull request merged**
