### PR TITLE
Bump Reactive Messaging version to 3.22.0 with Kafka Checkpointing support

### PR DESCRIPTION
**Pull request by ozangunalp**
Using Redis client, Hibernate Reactive and Hibernate ORM for checkpointing state stores

- [x] RM jakarta rewrite version to 4.1.0
- [x] Doc updates for Kafka, config reference updates for RabbitMQ and AMQP.

### CODE REVIEW

**Comment by ozangunalp** [comment]
I need to push a small fix to new tests where producer ordering is important for the assertion.

**Review by cescoffier — APPROVED** [review]
Awesome!

**Comment by cescoffier** [comment]
Need videos / blog post / insights!

**Comment by cescoffier** [comment]
The CI failures are unrelated.

**Pull request merged**
