### PR TITLE
Bump to Mutiny 1.3.0 and Mutiny Vert.x bindings 2.18.0

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@jponge please don't push your branches to the main repo. It makes CI run twice and it's messy.

Thanks!

**Comment by jponge** [comment]
Ah my bad!

**Comment by jponge** [comment]
The failed test is not related to the impacted code AFAIK.

**Comment by geoand** [comment]
Yeah, the gradle tests on windows are sometimes flaky

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
