### PR TITLE
Fix potential hang if exception is thrown from authenticator

### LINKED ISSUE #13559: Throwing AuthenticationFailedException from IdentityProvider.authenticate stalls connection.
**Describe the bug**
The documentation of `IdentityProvider.authenticate` is a little bit unclear on how one should throw `AuthenticationFailedException` or return the same exception wrapped in an `Uni`. I got it wrong and noticed that throwing `AuthenticationFailedException` stalls the client connection without any warning in the logs. Other exceptions (e.g. `RuntimeException`) are properly logged as an error and immediately return a 500 error to the client. This took me a while to figure out...

**Expected behavior**
Throwing `AuthenticationFailedException` from `IdentityProvider.authenticate` should either do the same as returning it wrapped in an `Uni`, or be handled as an application error (just like any other exception) resulting in a 500 error response.

**Actual behavior**
Throwing `AuthenticationFailedException` from `IdentityProvider.authenticate` does not produce an error log entry, does not trigger a 500 error response, and instead stalls the client connection until it times out.

**To Reproduce**

Implement a custom `IdentityProvider` that throws `AuthenticationFailedException`, add one of the auth annotations to a jax-rs resource, then request that resource with credentials.

```java
@ApplicationScoped
public class BasicIdentityProvider implements IdentityProvider<UsernamePasswordAuthenticationRequest> {
	@Override
	public Class<UsernamePasswordAuthenticationRequest> getRequestType() {
		return UsernamePasswordAuthenticationRequest.class;
	}

	@Override
	public Uni<SecurityIdentity> authenticate(UsernamePasswordAuthenticationRequest request,
			AuthenticationRequestContext context) {
		throw new AuthenticationFailedException("Not in the mood");
	}
}

@Path("/test")
@ApplicationScoped
public class TestResource {
	@GET
	@RolesAllowed({ "not-one" })
	public void get200() {
	}
}

// curl http://wrong:pass@localhost:8080/test  # This will block until timeout
```

**Configuration**
```properties
quarkus.http.auth.basic=true
```
**Environment (please complete the following information):**
 - Output of `java -version`: 14.0.2+12-Ubuntu-120.04
 - Quarkus version or git rev: 1.10.1.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #13559

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by defnull** [comment]
Documentation of IdentityProvider says:

> Any other failure mode will be interpreted as a failure in the underlying store (e.g. LDAP is down), rather than the credentials being invalid. If multiple providers are installed that can handle the same type of request an {@link AuthenticationFailedException} will immediately stop processing, while any other failure will allow processing to continue.

So, to put the cherry on top, you'd need to catch exceptions in `QuarkusIdentityProviderManagerImpl.handleProvider` too and continue checking more providers if the exception is not an `AuthenticationFailedException`.

How about, instead of try-catch blocks, you'd add a helper method like this:

```java
static <T> Uni<T> wrapException(Supplier<Uni<T>> sup) {
    try {
        return sup.get();
    } catch (RuntimeException e) {
        return Uni.createFrom().failure(e);
    }
}
```

and wrap calls to `IndentityProvider.authenticate()` with it? the helper could be reused for other APIs that return `Uni` but may fail with exceptions and cause problems.

**Comment by defnull** [comment]
That said, this PR is correct in that it prevents potential hang. If you want to keep the original API and do not support throwing exceptions instead of returning them, then the current patch is sufficient. But then, maybe, emit a warning to the logs from the catch block? Otherwise this common error just works most of the time and is even harder to notice.

**Comment by stuartwdouglas** [comment]
handleProvider should actually propagate the exception as-is. When an exception is thrown from a function that should supply a Uni mutiny will automatically translate that into a failed Uni with the exception type.

**Comment by defnull** [comment]
How so? `IdentityProvider.authenticate()` is called directly in line 143. If that throws, the exception is catched and wrapped by your new catch block in `QuarkusIdentityProviderManagerImpl.authenticate()`. No stalled connections, which is great. But if that exception is something different than `AuthenticationFailedException`, then the other providers should also be triggered. This does not happen currently.

**Comment by sberyozkin** [comment]
@defnull But why the code should be complicated to trigger other providers in case of the undocumented exceptions ? JavaDocs of the `IdentityProvider.authenticate` are clear about failing with `AuthenticationFailedException`

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
Actually, I see what you mean, but here we are talking about the escaped exceptions as opposed to returned properly with Uni. I reckon we can follow up with the doc update as I said earlier to clarify it as opposed to diluting the message and letting users either return it with Uni or throw randomly

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, would you like to update `IdentityProvider.authenticate` docs with a short note that the exceptions should be returned with `Uni.createFrom().failure()` ? Or I can follow up with this note alongside security docs update

**Comment by sberyozkin** [comment]
I'll add a note to the docs later on

**Pull request merged**
