### PR TITLE
Use Maven's default profile activator for profile activation

### PR DESCRIPTION
**Pull request by aloubyansky**
Fix for #2247

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet given that you've reviewed a couple of related issues, could you have a look at this one? Thanks.
This is the API Maven is using to activate profiles.

**Review by gsmet — APPROVED** [review]
@aloubyansky looks good from a quick glance.

Do we have unit tests for `MavenRepoInitializer`? If not I think we should have some if it's not too hard to add them. I think if we could override the Maven home directory, it would be easy to write some tests.

**Comment by aloubyansky** [comment]
@gsmet yes, we do. And in my other open PR there is more. There are no tests that include profiles though.

**Comment by aloubyansky** [comment]
Thanks!

**Pull request merged**
