### PR TITLE
Bump AWS SDK - to leverage netty bumped to 4.1.42

### PR DESCRIPTION
**Pull request by marcinczeczko**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
For my information, what does it change for them?

**Comment by marcinczeczko** [comment]
> For my information, what does it change for them?

@cescoffier I'm not sure what do you mean. But in general that version of sdk depends on netty 4.1.42 - so it will become aligned to netty version in quarkus. Besides it fixes/improves some SDK internal implementations, without changing the actual API.

**Comment by gsmet** [comment]
OK, this will have to wait. Please do not push anything there today and tomorrow, we need the CI resources for the PRs that we need to get in.

(sorry about that but we are struggling a bit)

**Comment by marcinczeczko** [comment]
> OK, this will have to wait. Please do not push anything there today and tomorrow, we need the CI resources for the PRs that we need to get in.
> 
> (sorry about that but we are struggling a bit)

No worries.

**Comment by gsmet** [comment]
Rebased. I will see if it passes CI and merge it tomorrow if it does.

**Comment by stuartwdouglas** [comment]
I just merged Bill's AWS PR so just to be super safe before the release I have rebased this one on top of it to test it again.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
