### PR TITLE
Fix duplicate quarkus-bootstrap-core test-jar in build-parent

### PR DESCRIPTION
**Pull request by famod**
Fixes:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.quarkus:quarkus-junit5:jar:999-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.quarkus:quarkus-bootstrap-core:test-jar -> duplicate declaration of version ${project.version} @ io.quarkus:quarkus-build-parent:999-SNAPSHOT, /home/moldowan/proj/quarkus/build-parent/pom.xml, line 277, column 25
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by aloubyansky** [comment]
Hold on, I moved it from the BOM to the build-parent. Were there two in the build-parent?

**Comment by famod** [comment]
Exactly, there already was/is one.

**Comment by aloubyansky** [comment]
Oh, sorry, didn't check. Thanks for fixing it!

**Review by aloubyansky — APPROVED** [review]

**Comment by famod** [comment]
yw!

**Comment by geoand** [comment]
CI doesn't like it :)

**Comment by famod** [comment]
I don't think we need another CI run because all those failures are happening in the devmode ITs which was a known problem until #21601.

**Comment by geoand** [comment]
I agree

**Pull request merged**
