### PR TITLE
Implemented Hibernate ORM - Multitenancy support #5681

### PR DESCRIPTION
**Pull request by michael-schnell**
Implemented Hibernate ORM - Multitenancy support #5681

### CODE REVIEW

**Comment by gsmet** [comment]
@michael-schnell thanks for this work! Any chance you could squash your commits? Thanks!

**Comment by michael-schnell** [comment]
> @michael-schnell thanks for this work! Any chance you could squash your commits? Thanks!

Hmmm... I thought this could be done in the Github UI during your merge. But, no problem.

**Comment by geoand** [comment]
> > @michael-schnell thanks for this work! Any chance you could squash your commits? Thanks!
> 
> Hmmm... I thought this could be done in the Github UI during your merge. But, no problem.

Unfortunately GitHub UI doesn't provide that ability when using the `Merge Commit` strategy (which is what we use when merging a PR)

**Comment by michael-schnell** [comment]
> > > @michael-schnell thanks for this work! Any chance you could squash your commits? Thanks!
> > 
> > 
> > Hmmm... I thought this could be done in the Github UI during your merge. But, no problem.
> 
> Unfortunately GitHub UI doesn't provide that ability when using the `Merge Commit` strategy (which is what we use when merging a PR)

OK, will check what I can do

**Comment by geoand** [comment]
Thanks a lot!

**Comment by michael-schnell** [comment]
> Thanks a lot!

Can I squash all commits into one? As I've merged several times code from this repository into my forked repo, I have  ahuge list of other commits not related to mine. Is it OK to squash also those commits from other people?

**Comment by geoand** [comment]
Yup, it's safe to squash them into a single one and then force push to your branch. 
It's probably best if you rebase onto the latest master as well (if you PR isn't already based on it).

**Comment by michael-schnell** [comment]
Something went wrong... Will start a new pull request

**Comment by michael-schnell** [comment]
Here is the new (clean) one: https://github.com/quarkusio/quarkus/pull/8545

**Pull request closed without merging**
