### PR TITLE
MP JWT 1.2 Support

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks Roberto; Kotlin test is failing in Java11, so it is not related

**Comment by radcortez** [comment]
It should be a hiccup. The previous commit with the MP Config support was all green, I don't see any reason for this to not be as well. I'll try to rerun CI again to see if we get everything to pass.

**Comment by sberyozkin** [comment]
Yes it is not related 100%

**Pull request merged**
