### PR TITLE
Remove `@Traceless` annotation

### PR DESCRIPTION
**Pull request by mcruzdev**
After this [discussion](https://github.com/quarkusio/quarkus/pull/43885/files/88f628da40b5aa1eb7ea5ed66d827c5a1affc86b#r1857472384) on https://github.com/quarkusio/quarkus/pull/43885 pull request, we decided to remove the annotation and to work only with the `quarkus.otel.traces.suppress-application-uris` property.

I created another issue for tracking the `@Traceless` annotation. https://github.com/quarkusio/quarkus/issues/44733

### CODE REVIEW

**Comment by mcruzdev** [comment]
cc: @geoand @brunobat @michalvavrik

**Review by geoand — APPROVED** [review]
Thanks!

**Review by michalvavrik — APPROVED** [review]

**Comment by mcruzdev** [comment]
this one is related, I will take a look

**Comment by gastaldi** [comment]
Test failures seem related? 🤔

**Comment by mcruzdev** [comment]
I think yes...

**Comment by traceless** [comment]
Can you close this issue, because your title include the character '@-Traceless' , i will receive a message reminder from this issue...

**Comment by geoand** [comment]
We can't close the related issues or PRs as they are part of ongoing work to improve our project.

I suggest deactivating notifications  from the repo entirely.

**Pull request merged**
