### PR TITLE
Expose Stork Registars in Quarkus extension + integration test

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Comment by aureamunoz** [comment]
cc @cescoffier

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
CI doesn't seem to like it :(

**Comment by cescoffier** [comment]
@aureamunoz the issues look related. Can you have a look?

**Review by cescoffier — CHANGES_REQUESTED** [review]
CI issues related to the changes.

**Comment by aureamunoz** [comment]
Yes, yes, I'm on it

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
