### PR TITLE
Add ability to directly inject the session

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This allows usage such as https://github.com/stuartwdouglas/quarkus-quickstarts/blob/17e47625d9e32e8d5b70a17a207b7b9f40e2888e/hibernate-reactive-quickstart/src/main/java/org/acme/hibernate/reactive/FruitMutinyResource.java#L41

Draft for now, if people like it docs/tests are needed.

### CODE REVIEW

**Comment by geoand** [comment]
I thought about this a while ago too but then forgot about it, so definitely +1

**Comment by stuartwdouglas** [comment]
We need to think about these SPI's for RR, because if we tried to combine this approach with Kotlin co-routines it would cause issues, and I think HR + Kotlin co-routines would be really interesting to support.

**Comment by geoand** [comment]
👍🏼

**Comment by Sanne** [comment]
BTW focusing on user aspect... your example:

```
public Uni<List<Fruit>> get(Mutiny.Session s) {
        return s
                .createNamedQuery("Fruits.findAll", Fruit.class)
                .getResultList();
    }
```

original code:

```
   @GET
    public Uni<List<Fruit>> get() {
        return sf.withTransaction((s,t) -> s
                .createNamedQuery("Fruits.findAll", Fruit.class)
                .getResultList()
        );
    }
```

TBH I find the original code much clearer, as it's important to me to see which block of code exactly is the transactional "block".

Are you sure this needs to be fixed? cc/ @gavinking

**Comment by stuartwdouglas** [comment]
So what should we do with this? Is this something we want?

**Comment by geoand** [comment]
I'm +1 for it

**Comment by Sanne** [comment]
If you guys love this approach go for it; personally I'm skeptical of people liking this sort of magical methods.

I wouldn't use it myself but I won't stop you :)

**Comment by Sanne** [comment]
I've pinged @gavinking again about it; would love to hear his opinion as well.

**Comment by gavinking** [comment]
Hrm, so have I understood correctly that this injected session automatically gets a tx, whose lifecycle is (implicitly) tied to the request?

Not sure how I feel about that. *Precisely* when in the lifecycle of a request does this tx get committed?

**Comment by stuartwdouglas** [comment]
Basically it's the same as if the method was wrapped in a `withTransaction`.

**Comment by Sanne** [comment]
Thinking again about this one. Personally I don't like it because when doing reactive programming my impression is that it's more natural to control scopes explicitly.

I appreciate that's just my personal preference but it keeps things simpler.

So consider myself neutral... if you both like this approach go for it, otherwise let's close this?

**Comment by Sanne** [comment]
Also, referring back again at the comparison:

```
    @GET
    public Uni<List<Fruit>> get(Mutiny.Session s) {
        return s
                .createNamedQuery("Fruits.findAll", Fruit.class)
                .getResultList();
    }
```
original code:

```
    @GET
    public Uni<List<Fruit>> get() {
        return sf.withTransaction((s,t) -> s
                .createNamedQuery("Fruits.findAll", Fruit.class)
                .getResultList()
        );
    }
```

My largest objection is that it's not explicit what the scope of this Session instance `s` is. IMO it rirks being mistakenly understood that it will get the "session from the current scope" in CDI style, as that's a common practice in such code.

Which is similar to the previous objection related to Transaction scope - both are extremely important to be well defined and understood by the developer.

And also: while it's a common case for the Transaction and the Session to having matching scopes, there's many situations in which they need to be controlled separately - there's reasons of the two APIs being separate; I fear suggesting to our users that controlling these scopes isn't important and can be left out is a bit naive - for example we don't currently support neither JTA nor XA transactions with Hibernate Reactive, and such "details" risk getting buried.

**Comment by FroMage** [comment]
Looks OK to me, but we also have `@ReactiveTransactional` so I wonder if it's not yet another way to achieve the same. Mmm, no, probably that annotation is more useful for the Panache version, which doesn't require a session injected. Without Panache you'd still have to inject a `Session` object, even with `@ReactiveTransactional`, so perhaps this is an orthogonal use-case.

**Comment by gsmet** [comment]
@Sanne @DavideD @FroMage @stuartwdouglas what's the status of this one?

**Comment by DavideD** [comment]
[I had a conversation about this](https://github.com/mkouba/quarkus/commit/579ca721d87071ef644399ce9e6405aaccbaee81#r92298533) with @mkouba  some time ago and it seems it's not doable at the moment. Not sure if this issue is different.

**Comment by mkouba** [comment]
> [I had a conversation about this](https://github.com/mkouba/quarkus/commit/579ca721d87071ef644399ce9e6405aaccbaee81#r92298533) with @mkouba some time ago and it seems it's not doable at the moment. Not sure if this issue is different.

This is something different. I was talking about CDI injection but this is JAX-RS/Resteasy Reactive parameter injection.

I think that it's OK for vanilla Hibernate Reactive; the code looks up the `SessionFactory` from the CDI context which is OK and then "wraps" the invocation within a new transaction.

For Hibernate Reactive Panache you don't need a `Mutiny.Session` instance and we have currently `@ReactiveTransactional` (will be replaced with `@WithTransaction` in https://github.com/quarkusio/quarkus/pull/29761).

**Comment by Sanne** [comment]
> I think that it's OK for vanilla Hibernate Reactive; the code looks up the `SessionFactory` from the CDI context which is OK and then "wraps" the invocation within a new transaction.

Sure it's "ok" but the lifespan of the Session is kinda "magic": at very least this should be well documented and defined properly. I do expect confusion about when the session starts and ends exactly - more importantly why it works in this method but it's not "the same" in others.

People need to be able to make a very clear model about their Session scopes - and when they're e.g. associating the entity to multiple different sessions without intending to do so.

Bottomline I'm not strictly against this - but I don't think I'd use it myself and am certainly not going to waste my upcoming years to help debugging code wich chooses to use this, you'll all have to do so yourselves ;)

**Comment by stuartwdouglas** [comment]
I am just going to close this, it seems like there was not consensus on if it was actually an improvement.

**Pull request closed without merging**
