### PR TITLE
Use the proper PU for executeUpdate on entityClass

### LINKED ISSUE #42314: JPA writes don't work when using ONLY named data sources since 3.13.0
### Describe the bug

We upgrade Quarkus from 3.12.0 -> 3.13.0. We are using 3 named data sources / Hibernate ORM configuration - no default data source is configured. This was working till 3.13.0. DB reads still work, but as soon as we do any update agains a named DB, we get the following exception:

The default datasource has not been properly configured. See https://quarkus.io/guides/datasource#jdbc-datasource for information on how to do that.

### Expected behavior

Both DB reads/writes work the same way as in the previous version, and not complaining about unconfigured default data source - we don't need such.

### Actual behavior

It is throwing an exception about the missing default data source configuration.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #42314
Introduced by #41547

### CODE REVIEW

**Comment by gsmet** [comment]
@marko-bekhta any chance you could add a test to the PR if it's not too convoluted to do it?

**Review by gastaldi — APPROVED** [review]
Good catch!

**Comment by yrodiere** [comment]
> Introduced by #41547

Sorry. That's indeed embarrassing.

**Comment by HerrDerb** [comment]
With now using an entity specific session, can this theoretically have a impact on memory and db connections for a complex transaction?

**Comment by yrodiere** [comment]
In short: no.

Because:

1. We didn't change the behavior here, we just reverted it to what it was.
2. We only use different sessions for different entities *when you explicitly tell us to*. See https://quarkus.io/guides/hibernate-orm#multiple-persistence-units

**Pull request merged**
