### PR TITLE
BOMs from the same workspace are not interpolated in dev mode

### LINKED ISSUE #6852: BOMs from the same workspace are not interpolated in dev mode
**Describe the bug**
I'm trying to automate the process to build against quarkus snapshots to spot issues compatibility issues for camel-quarkus and I'm using the following maven command:

    ./mvnw clean install -Dquarkus.version=999-SNAPSHOT -Poss-snapshots

**Expected behavior**
The project should be compiled against quarkus snapshots

**Actual behavior**

The build fails because of the following error:

```
2020-01-29T10:45:38.8184581Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.092 s <<< FAILURE! - in org.apache.camel.quarkus.component.xml.deployment.CamelDevModeTest
2020-01-29T10:45:38.8191143Z [ERROR] org.apache.camel.quarkus.component.xml.deployment.CamelDevModeTest.testRoutesDiscovery  Time elapsed: 4.037 s  <<< ERROR!
2020-01-29T10:45:38.8203762Z java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.apache.camel.quarkus:camel-quarkus-core-xml-deployment::jar:1.1.0-SNAPSHOT
2020-01-29T10:45:38.8214119Z Caused by: java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.apache.camel.quarkus:camel-quarkus-core-xml-deployment::jar:1.1.0-SNAPSHOT
2020-01-29T10:45:38.8223310Z Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.apache.camel.quarkus:camel-quarkus-core-xml-deployment::jar:1.1.0-SNAPSHOT
2020-01-29T10:45:38.8233261Z Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to resolve dependencies for org.apache.camel.quarkus:camel-quarkus-core-xml-deployment:jar:1.1.0-SNAPSHOT
2020-01-29T10:45:38.8244161Z Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.quarkus:quarkus-development-mode-spi:jar: in central (https://repo.maven.apache.org/maven2)
2020-01-29T10:45:38.8254778Z Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.quarkus:quarkus-development-mode-spi:jar: in central (https://repo.maven.apache.org/maven2)
2020-01-29T10:45:38.8265094Z Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.quarkus:quarkus-development-mode-spi:jar: in central (https://repo.maven.apache.org/maven2)`
```

So it looks like the quarkus artifact resolver does not take into accountthe maven snapshot repositorie configured through a profile

**Additional context**
full pr: https://github.com/apache/camel-quarkus/pull/669
the error happens also when executing the command locally

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #6852 

@stuartwdouglas fyi, I enabled local project discovery in QuarkusDevModTest and uncommented a condition to discover the workspace in BootstrapAppModelFactory (if it's always false you may get an NPE a few lines below).

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky the main JDK 8 failed. Could you have a look?

**Comment by aloubyansky** [comment]
Yes, looking. I see a classloading issue there apparently running gradle tests.

**Comment by aloubyansky** [comment]
Just for the record
```
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: Provider io.quarkus.test.common.http.TestHTTPConfigSourceProvider not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at java.lang.Iterable.forEach(Iterable.java:74)
        at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:78)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:169)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:191)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:133)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:92)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:204)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:95)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:45)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:96)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:191)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:219)
```

**Comment by aloubyansky** [comment]
Should be good now.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
