### PR TITLE
add initial categories into extension overrides

### PR DESCRIPTION
**Pull request by maxandersen**
For now just have one category.

@ia3andy where are your current categories defined ?
Lets share that and someone with time on their hands
can expand this or a new PR to have it defined here.

### CODE REVIEW

**Comment by maxandersen** [comment]
Another thing we should figure out is how to best share this notion of categories if that makes sense at all.

for now I put it in devtools core bom, but should actually be in platform. @aloubyansky any suggestions ?

**Comment by geoand** [comment]
Can you please rebase on master to pick up a CI fix?

**Comment by ia3andy** [comment]
@maxandersen there: https://raw.githubusercontent.com/quarkusio/quarkusio.github.io/develop/_data/extensions.yaml

**Comment by maxandersen** [comment]
> @maxandersen there: https://raw.githubusercontent.com/quarkusio/quarkusio.github.io/develop/_data/extensions.yaml

thanks @ia3andy i've updated the PR to include the json variation and using name/id.

**Comment by maxandersen** [comment]
also fixed a dumb bug introduced while merging master over weekend - so we should get this in as soon as CI test pass.

**Comment by ia3andy** [comment]
@maxandersen shouldn't we also add extension binding with categories and pinned order?

**Comment by maxandersen** [comment]
@ia3andy each extension knows what category it is in - you'll resolve that was my assumption.
I have no idea what the pinned order is so I'll need your or others help to do that as we get more info. PR's welcome :)

**Comment by maxandersen** [comment]
@ia3andy merged this for now - please open separate issue(s) for what you think is missing.

**Pull request merged**
