### PR TITLE
Make sure Transfer-Encoding set by a Resource is honored

### LINKED ISSUE #42238: Transfer-Encoding header is set twice
### Describe the bug

In our BFFs we found out that when receiving a response from the backend that has "Transfer-Encoding" header set to "chunked" and we forward this response to the FE suddenly there are two "Transfer-Encoding" headers present which are set to "chunked". The browser is ignoring this but some rest clients are throwing an error because of theses duplicate headers. 

### Expected behavior

"Transfer-Encoding" header is only present once in the response of the bff. 

### Actual behavior

"Transfer-Encoding" header is set twice. 
image
image

### How to Reproduce?

Here is a minimal project that reproduces the issue: https://github.com/FloGro3/response-header-issue-example

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java version: 19.0.2

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #42238

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Added to the backport list as it makes Istio fail.

**Comment by geoand** [comment]
Wow

**Comment by jmartisk** [comment]
@cescoffier This is already fixed in 3.20, maybe you are looking at the wrong version? Please check

**Comment by cescoffier** [comment]
Ah cool! Thanks @jmartisk

**Pull request merged**
