### PR TITLE
Upgrade to Hibernate ORM 5.4.9.Final

### LINKED ISSUE #4377: Hibernate - @ManyToOne strange behavior
**Describe the bug**
Imagine the relationship described below:
"one" User -> "many" Message
In Message class, there is @ManyToOne(fetch = FetchType.LAZY, optional = false) User user;  annotation.
When a new Message instance are created, we need to persist the object on database with related User "id".
I find the related User using EntityManager.find(clazz, id)

**Expected behavior**
Insert the new Message on database, do not make any operation with User

**Actual behavior**
After insert Message, Hibernate tries to update the User instance without any field.

**To Reproduce**
1. Create a User instance on database and persist.
2. In other transaction, create a Message and set the existent User
3. Persist the Message

**Configuration**
```properties
# We are using Postgres Database

```
Can reproduce issue only in quarkus 0.23x, on 0.22 works fine with same config.

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #4377 (Among various other fixes from upstream ORM)

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
This needs to be rebased onto the latest master for same reason that I have described in chat: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Hibernate.20validator.20IT.20issue.3F

**Comment by Sanne** [comment]
I didn't understand the reason :) but rebased and crossing fingers ...

**Comment by geoand** [comment]
CI leaks artifacts in native unfortunately... I have seen in plenty of times and it's most evident when there are a lot of PRs.

I'm willing to bet that the tests will pass with your rebase :)

**Comment by Sanne** [comment]
So there was a native test failure before my latest push?

Unfortunately I rebased before looking, didn't think the link to CI reports would be lost.

**Comment by geoand** [comment]
There was a native test failure in a module totally unrelated to your PR.
Unfortunately this has happened in the past plenty of times and as I explain the chat thread I linked it's most likely either a misuse on our part of Azure Pipeline's caching, or a bug in the CI solution itself

**Comment by Sanne** [comment]
ok got it. Thanks I was worried, I tested it all locally but stuff changes so fast here :)

**Comment by geoand** [comment]
Supersonic changes 🚀

**Pull request merged**
