### PR TITLE
Remove support for JAX-RS @AsyncResponse

### PR DESCRIPTION
**Pull request by geoand**
This API is very cumbersome to use and makes
no sense in the light of RR's complete
async support.

### CODE REVIEW

**Comment by geoand** [comment]
@cescoffier @gsmet WDYT about this one?

**Comment by gsmet** [comment]
I think we need to be a bit careful. Especially because people might want to migrate existing applications to Quarkus without having to rewrite a lot of things.
I have no idea if this API is actually used a lot in practice.

**Comment by geoand** [comment]
I personally have never seen it being used, but it's also an awful API which we probably should never have supported in the beginnign

**Comment by Ladicek** [comment]
I agree the JAX-RS async API is awkward and awful, but I think it's actually used in practice. Not terribly often, probably, but I think I've used it once or twice for something. I don't disagree with removing it, it's a tricky balance.

**Comment by Sanne** [comment]
> I personally have never seen it being used

The problem is you're not going to get feedback about stuff which works, even if it's clumsy to use. People are smart and will find ways to do what they need even it's not great - but only a small fraction will engage in the community unless you give them a gentle push.

I'd suggest find a way to get the feedback without being too disruptive; for example start by logging a warning (at most once) if you detect it's being used, warning that you plan to remove it unless you hear otherwise.

Then there's the fact that many ignore warnings; so at the next iteration you repalce the warning with an exception which also solicits feedback, and has intructions about how to re-enable the feature temporarily, e.g. a system property.

> but it's also an awful API which we probably should never have supported in the beginning

Next time, better to push back before adding things.

**Comment by geoand** [comment]
We actually use this in one of the quickstarts... 🤦🏼, so we'll have to address that too.

**Comment by Sgitario** [comment]
From my point of view, and apart from if the API is cumbersome or ugly, is this already working as part of the Resteasy Reactive extension? If so, what is the value of removing it? To gain some performance? 

My point is that if it's already there, some users can benefit from it, and perhaps we can add a comment saying that this feature is deprecated in Resteasy Reactive in favor of Mutiny. 

I'd only remove it if there is a performance pitfall or an incompatibility with some other major APIs that we can't sort out.

**Comment by geoand** [comment]
> If so, what is the value of removing it? To gain some performance?

The value the way I see it is that we can get rid of a bunch of supporting code for an API we should have never supported.

> I'd only remove it if there is a performance pitfall or an incompatibility with some other major APIs that we can't sort out.

The performance impact can be almost eliminated using the approach introduced in https://github.com/quarkusio/quarkus/pull/28204. I'll go ahead and work on it.

**Comment by geoand** [comment]
I'll go ahead and close this

**Pull request closed without merging**
