### PR TITLE
fix: container-image-s2i runtime dependencies

### PR DESCRIPTION
**Pull request by iocanel**
This pull request adds a missing required dependency to `container-image-s2i`.
This fixes tests and run-time failures.

### CODE REVIEW

**Comment by iocanel** [comment]
Possibly Fixes: #7601 
I am not 100% sure if its this particular commit or one of the previous fixes that merged earlier today. However, I can no longer reproduce #7601 .

**Comment by geoand** [comment]
Can we please have a small comment in `pom.xml` on why the dependency is needed? It's not immediately obvious

**Comment by gsmet** [comment]
Can we add the comment later once this PR is in if the PR looks good? I would like to wrap up CR1 and this one looks important.

**Comment by geoand** [comment]
OK sure

**Review by geoand — APPROVED** [review]

**Pull request merged**
