### PR TITLE
Smallrye Reactive Messaging 3.12.1

### PR DESCRIPTION
**Pull request by ozangunalp**
https://github.com/smallrye/smallrye-reactive-messaging/releases/tag/3.12.0

### CODE REVIEW

**Review by cescoffier — COMMENTED** [review]
Should we wait for the 3.12.1?

**Comment by ozangunalp** [comment]
Yes let's wait for 3.12.1 fix

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
The Ci failed because the artifacts were not yet on Maven Central. I've re-launched it.

**Comment by rsvoboda** [comment]
@ozangunalp / @cescoffier looking at the scope of changes I think this PR could have noteworthy label

And the package changes / move of some classes to `io.smallrye.reactive.messaging.providers` umbrella package should be highlighted for users in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.6

**Comment by cescoffier** [comment]
@rsvoboda Added.

**Pull request merged**
