### PR TITLE
Remove invalid imagePushSecret from BuildConfig when using internal registry

### LINKED ISSUE #35647: Knative deployment is broken using OpenShift extension in v3.3.0 and v.3.3.1
### Describe the bug

After a new project on v3.3.0 or v.3.3.1 is created with an openshift extension, the app is deployed to the OpenShift serverless. But the Quarkus serverless app never came up with the following issue:

image

Knative service has an error:
image

When I created a new project based on v3.2.4.Final, it works well.

### Expected behavior

Quarkus app should run as a knative service.

### Actual behavior

The revision status is "ContainerMissing"

image

### How to Reproduce?

1. quarkus create kube-native-java 
2. quarkus ext add openshift
3. Update the application.properties
quarkus.container-image.group={YOUR_PROJECT_NAME}
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deployment-target=knative
quarkus.kubernetes.deploy=true
quarkus.openshift.build-strategy=docker
4. quarkus build --no-test

Be sure to install OpenShift serverless in your OpenShift cluster.

### Output of `uname -a` or `ver`

Darwin doh-mac 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.3.0 and 3.3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #35647

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by danieloh30** [comment]
@geoand This fix seems to have been added to the 3.4.0 or later version. 
1) When will 3.4.0 be released (roughly)?
2) Any workaround to avoid this issue until the fix is added?

**Comment by geoand** [comment]
@danieloh30 this will be backported to the next 3.3 release as well as being part of [3.4.0.CR1](https://github.com/quarkusio/quarkus/wiki/Release-Planning#34-proposal)

**Comment by danieloh30** [comment]
sounds cool! thx for a quick answer @geoand

**Comment by geoand** [comment]
🙏🏼

**Comment by iocanel** [comment]
@danieloh30: a workaround would be to create an empty image push secret. Haven't tried it, but it should possibly work.

**Comment by iocanel** [comment]
An alternative workaround I tried is to remove the registry completely, set an empty image group (so that the image is a single segment image) and rely on the fact that the ImageStreams use local lookup policy. 

While this works ok for `Deployment` it does not seem to work for Knative `Service`. It's not clear to me why.
Feedback from Openshift or Knative people would possibly help. @maxandersen @rhuss?

**Comment by danieloh30** [comment]
That's really helpful and good to know!

**Comment by rhuss** [comment]
While not being able to fully dive into this issue, I can nevertheless that
Knative does not work well with ImageStream because a KService is not an intrinsic OpenShift object that the build controller is aware of. E.g. there can be no redeployment triggered after a new build: https://issues.redhat.com/browse/BUILD-100

Not sure if this helpful in this context though :-)

**Comment by danieloh30** [comment]
Good to know @rhuss I'd better wait for the next release for this :)

**Pull request merged**
