### PR TITLE
Upgrade Netty to version 4.1.87.Final

### PR DESCRIPTION
**Pull request by oscerd**
Signed-off-by: Andrea Cosentino <ancosen@gmail.com>

### CODE REVIEW

**Comment by cescoffier** [comment]
Anything special you need from the at release?

**Comment by oscerd** [comment]
Not really, but this minor usually keep some minor fixes, so it's always good to keep up-to-date. If there are good reason to stay on .86 I'm fine :-)

**Comment by cescoffier** [comment]
We don't have a good reason to stay on .86. However, we are waiting for the "all clear" from the Vert.x team first.

**Comment by cescoffier** [comment]
Just got the feedback from the Vert.x team. We should wait for .88 containing significant optimizations.

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
@cescoffier I suppose we can merge this in the meantime?

**Comment by cescoffier** [comment]
Yes, we can merge this one waiting for .88.

**Pull request merged**
