### PR TITLE
Don't ignore invalid config in quarkus.container-image.name

### LINKED ISSUE #33552: Jib not using image name when using variables
### Describe the bug

If I use Jib to build a container with the following property (voluntarily without value):
```
quarkus.container-image.name=hide-and-seek-${application.name}
````

It ignores the value and uses the artifactId as the default image name.

If I use:

```
quarkus.container-image.name=hide-and-seek-place-service
```

It works.

### Expected behavior

It should use the set image name, at least try to resolve it, and fails, or at least report something instead of switching silently to the default name.

### Actual behavior

It does not.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #33552

### CODE REVIEW

**Review by machi1990 — COMMENTED** [review]
The change lgtm. Can we add a unit test?

**Comment by geoand** [comment]
Sure, I'll add that tomorrow

**Review by radcortez — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]
awesome, thanks @geoand

**Comment by geoand** [comment]
🙏

**Pull request merged**
