### PR TITLE
Introduce a low level Apache HttpClient extension

### PR DESCRIPTION
**Pull request by gsmet**
This should solve the issue we have with GraalVM 21.1

@jerboaa could you check if it solves your issue?

### CODE REVIEW

**Comment by jerboaa** [comment]
@gsmet OK. I'll test it and report back.

**Comment by gsmet** [comment]
BTW, it won't solve everything I suppose but hopefully everything that's related to the Apache HttpClient.

**Comment by jerboaa** [comment]
@gsmet Yes, understood. Tested and works for me with Graal VM 21.1 dev and native.

**Comment by gsmet** [comment]
@geoand I would appreciate if you could have a look at this one.

**Review by geoand — APPROVED** [review]
LGTM

**Comment by jerboaa** [comment]
Looks like some tests are not happy:
```
Error:    CatalogProcessorTest.testExtensionsOrder:32 
Expecting:
  ["quarkus-resteasy",
    "quarkus-resteasy-jackson",
    "quarkus-resteasy-jsonb",
    "quarkus-apache-httpclient",
    "quarkus-vertx-http",
    "quarkus-vertx-graphql",
    "quarkus-hibernate-validator",
    "quarkus-rest-client-mutiny",
    "quarkus-netty",
    "quarkus-resteasy-reactive-servlet",
    "quarkus-rest-client",
    "quarkus-rest-client-jaxb",
    "quarkus-rest-client-jsonb",
    "quarkus-rest-client-jackson",
    "quarkus-hibernate-orm-rest-data-panache",
    "quarkus-mongodb-rest-data-panache",
    "quarkus-resteasy-common",
    "quarkus-resteasy-jaxb",
    "quarkus-resteasy-multipart",
    "quarkus-resteasy-mutiny",
    "quarkus-resteasy-qute",
    "quarkus-resteasy-reactive",
    "quarkus-resteasy-reactive-jsonb",
    "quarkus-resteasy-reactive-jackson",
    "quarkus-resteasy-reactive-qute",
    "quarkus-resteasy-server-common",
    "quarkus-reactive-messaging-http",
    "quarkus-vertx-web",
    "quarkus-smallrye-graphql",
    "quarkus-smallrye-jwt",
    "quarkus-smallrye-openapi",
    "quarkus-undertow",
    "quarkus-webjars-locator",
    "quarkus-websockets",
    "quarkus-grpc",
    "quarkus-grpc-common"]
to start with:
  ["quarkus-resteasy",
    "quarkus-resteasy-jackson",
    "quarkus-resteasy-jsonb",
    "quarkus-vertx-http",
    "quarkus-vertx-graphql",
    "quarkus-hibernate-validator"]
```

**Comment by gsmet** [comment]
Yuk, these tests are really fragile if they break when we add an extension :/

**Comment by gsmet** [comment]
I force pushed an update.

**Pull request merged**
