### PR TITLE
Do not build integration tests with '-Dquickly'

### PR DESCRIPTION
**Pull request by gastaldi**
This cuts the build time from 4:07 to 02:56 (in my laptop)

### CODE REVIEW

**Comment by aloubyansky** [comment]
TBH, I am not sure whether it's a good thing. People may have different expectations. Perhaps, start a poll?

**Comment by gastaldi** [comment]
Sure, but isn't `-Dquickly` meant for installing the binaries in the local repository? AFAIK integration tests are not meant to do that :slightly_smiling_face:

**Comment by loicmathieu** [comment]
I'm +1 as `quickly` already have `skipITs` but unfortunatly our integration tests didn't use the standard Maven integration test structure so they are not skipped.

We can also repurpose `skipITs` for this ...

**Comment by aloubyansky** [comment]
They'd still be compiled though. Which makes sure the repo can be compiled. But that depends on the expectations though.

**Comment by loicmathieu** [comment]
But yeah, maybe check on the mailing list first for what people think about that.

**Comment by geoand** [comment]
I am -1 for this. Compiling the ITs should happen IMHO

**Comment by gastaldi** [comment]
@loicmathieu binding to `skipITs` seems more logical, but as @geoand pointed out, this may not catch IT compilation errors, so I'll start a thread in the ML and see what to do with this PR

**Comment by gsmet** [comment]
I'm against this one. It's always good to have the compilation errors.

**Comment by aloubyansky** [comment]
Having collected the opinions on the mailing list, let's keep it the way it is.

**Pull request closed without merging**
