### PR TITLE
Update graal-sdk to 22.3.2

### LINKED ISSUE #33423: Update graal-sdk to 22.3.2 to address public known CVEs in version 22.3.0
### Describe the bug

The current version of graal-sdk 22.3.0, contains a [series of public known CVEs](https://security.snyk.io/package/maven/org.graalvm.sdk:graal-sdk/20.3.0). Even though it seems that Quarkus is not vulnerable, it would be nice to include an update in the upcoming releases to include the fixes for these vulnerabilities.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Please check https://security.snyk.io/package/maven/org.graalvm.sdk:graal-sdk/20.3.0

### PR DESCRIPTION
**Pull request by abstractj**
Closes #33423

### CODE REVIEW

**Comment by abstractj** [comment]
@sberyozkin could you please approve the workflow?

**Review by zakkak — APPROVED** [review]
LGTM, thanks

**Comment by sberyozkin** [comment]
Hey @zakkak Thanks, it is backportable to the 2.13 branch ?

**Comment by zakkak** [comment]
> Hey @zakkak Thanks, it is backportable to the 2.13 branch ?

Yes, although not necessary. Quarkus only uses the graal jars to satisfy build time dependencies, it never actually runs that code, instead it uses the implementations that are embedded in the local Graal VM installation or the builder image. Perhaps the change of `CURRENT` version is more important to make sure that people using an old version get notified to update to the latest.

**Comment by sberyozkin** [comment]
Thanks

**Pull request merged**
