### PR TITLE
Add support for LocalDate as Path-/QueryParam

### LINKED ISSUE #5860: Cannot deserialize LocalDate in @QueryParam due to missing ParamConverterProvider
**Describe the bug**
I'm using Jackson (via quarkus-resteasy-jackson) as `ObjectMapper` with the `KotlinModule` and the `JavaTimeModule` registered using an `ObjectMapperCustomizer`. When I have an endpoint with a `@QueryParam` of type `LocalDate` quarkus does not start.

**Expected behavior**
I expect resteasy to use the provided `ObjectMapper` to deserialize a String formated "YYYY-MM-DD" into an instance of `LocalDate`.

**Actual behavior**
Omitting the name and method signature for brevity I get

```
RESTEASY003875: Unable to find a constructor that takes a String param or a valueOf() or fromString() method for javax.ws.rs.QueryParam("adate") for basetype: java.time.LocalDate
```

**To Reproduce**
1. Use 
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
```
2. Register a resource like
```kotlin
@GET
@Path("path")
fun broken( @QueryParam("adate") aDate: LocalDate) {}
```
3. Run a `@QuarkusTest` to try a start up the application.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux ninja-cgd 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.5-ea" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1, mixed mode, sharing)
 - GraalVM version (if different from Java): 
not used
 - Quarkus version or git rev: 
0.25.0
**Additional context**

The problem is fixed by adding

```kotlin
@Provider
class LocalDateConverter : ParamConverterProvider {

    override fun <T: Any?> getConverter(rawType: Class<T>?, genericType: Type?, annotations: Array<out Annotation>?): ParamConverter<T>? {
        return if (rawType == LocalDate::class.java) {
            object: ParamConverter<T> {
                val mapper = ObjectMapper().also { JacksonObjectMapperCustomizer().customize(it) }
                override fun toString(value: T?): String {
                    return mapper.writeValueAsString(value)
                }
                override fun fromString(value: String?): T {
                    return mapper.readValue(value, LocalDate::class.java) as T
                }
            }
        } else null
    }
}
```

to the project. I was expecting that this kind of Provider would be added out of the box when using Jackson's `JavaTimeModule`.

### PR DESCRIPTION
**Pull request by ghost**
closes #5860

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

I just now (sorry about that...) realized that using such parameter converters causes a performance penalty, which in this case we can avoid - but it requires a deeper integration into Quarkus.
If you are up for a slightly bigger challenge, I can tell you what needs to be updated.

**Comment by belu** [comment]
@geoand 
If there is no hurry in getting this implemented you can give further instructions.

**Comment by geoand** [comment]
Sure, I'll try to write so pointers over the weekend

**Comment by geoand** [comment]
Here is what needs to be done at a high lever:

Add a similar check like is done at: 

https://github.com/quarkusio/quarkus/blob/master/independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java#L884

where you will check to see if the type is `LocalDate`. 
If it is, you do pretty much the same thing as is done for `PATH_SEGMENT`, except that you need to implement a new `org.jboss.resteasy.reactive.server.core.parameters.converters` named `LocalDataParamConverter`. The implementation should be straightforward if you see what is done for in `PathSegmentParamConverter`.

That should be enough to get the `LocalDate` handling registered in RESTEasy Reactive registered without any performance penantly

**Comment by belu** [comment]
@geoand 
Thanks for the pointers! Locally, it is working now. Could you please review the code?

Do you have a good template for the unit tests? And where should the tests be placed?

I think it makes sense to test at least two cases:
1. LocalDate is working out-of-the-box with ISO-8601 format in path
2. If there exists a user-defined ParamConverter for LocalDate (e.g. for ISO_WEEK_DATE) this one wins

**Comment by geoand** [comment]
The code seems reasonable.

As for the test, just add an something in https://github.com/quarkusio/quarkus/tree/c3458c623b30656ba435cb5dfdeda039aa09e4ec/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/simple

**Comment by geoand** [comment]
Also, when you are done, please squash the commits

**Comment by belu** [comment]
@geoand 
Added tests for LocalDate as PathParam and QueryParam. Also added a test-case with a custom ParamConverterProvider for LocalDate is present (in week-year format).

Regarding Native:
The other tests do not seem to have tests for the native-image. This can be skipped for this feature?
At least I tested the changes locally with a native runnable (Linux) and everything worked fine.

Squashed the commits locally and force-pushed. Is this okay?

Anything left?

**Review by geoand — APPROVED** [review]
Looks great, thanks a lot!

**Pull request merged**
