### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by kenfinnigan**
Including:

- Legacy Redirect for non application endpoints
- HttpRootPathBuildItem.adjustPath()
- Legacy Redirect integration testsuite

### CODE REVIEW

**Review by ebullient — APPROVED** [review]
This looks ok to me. I'd like a buddy's opinion, too.

**Review by stuartwdouglas — APPROVED** [review]
Code looks fine to me.

**Comment by gsmet** [comment]
So IIUC, you are removing the redirects from old non application endpoints to `/q/`? If so I think we need an entry in the migration guide.

**Comment by kenfinnigan** [comment]
Yes it should, and I just added https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#legacy-redirect-for-non-application-endpoints-such-as-health

**Comment by gsmet** [comment]
@kenfinnigan is there a way to still mount them at the root? If so, I think it should be added to the migration guide.

**Comment by kenfinnigan** [comment]
I think all endpoints offer that, so I've added an example of it for health

**Pull request merged**
