### PR TITLE
Fix issue with running tests in the IDE

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by geoand** [comment]
Tested and works for me.

**Review by geoand — APPROVED** [review]

**Comment by aloubyansky** [comment]
Is there a reason to explicitly define it instead of using the one from the bootstrap itself? It's not used anywhere else, is it? So why are we excluding it from bootstrap and re-adding it with a specific version instead?

**Comment by stuartwdouglas** [comment]
Bootstrap needs it to compile, we then change the scope to runtime so that it is not present on the compile classpath for the rest of Quarkus.

This code contains an annotation processor that will create extra files if it is present at compile time.

**Comment by aloubyansky** [comment]
Ah, thanks. That makes sense.

**Pull request merged**
