### PR TITLE
Bump SmallRye Reactive Messaging to 3.18.0

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by kdubb** [comment]
@gsmet Any chance of including this in 2.10.1. It basically only includes fixes for issues with RabbitMQ.

**Comment by cescoffier** [comment]
@kdubb no, this release has been done to align the vert.x version, it cannot be backported.

**Comment by kdubb** [comment]
Ahh ok

**Comment by cescoffier** [comment]
The CI issues are unrelated.

**Review by ozangunalp — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Rebased to fix a conflict.

**Pull request merged**
