### PR TITLE
Don't include version in the Swagger UI header

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Nothing good comes from exposing this information by default.

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
We might need the same for health and graphql, I'll have a look

**Comment by phillip-kruger** [comment]
Also dev ui? Even though that is just in dev, the idea is to make moving from dev ui to swagger and others look the same. Or, we need to change that we show it in dev mode, but not in other modes ?

**Comment by stuartwdouglas** [comment]
Dev UI is fine IMHO, we just don't want this for things that can be included in the production app to include the version.

**Review by geoand — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Ok, maybe I can then make a change to Dev UI to show it somewhere else ? Then the look are still the same if you do from Dev UI to Swagger UI ?

**Comment by gsmet** [comment]
I don't think it's a problem to have slightly different information for Dev UI.

**Comment by phillip-kruger** [comment]
ok cool :)

**Pull request merged**
