### PR TITLE
make ide-config shareable

### PR DESCRIPTION
**Pull request by maxandersen**
Why:

 * ide-config currently replicated at `ide-config`, `ip/arc/ide-config` and `ip/qute/ide-config`
 * quickstarts could benefit from reusing quarkus formatting

This change addreses the need by:

 * move ide-config to independent-projects and make it a real project
 * update refs to `eclipse-format.xml` to use <dependency> and resource lookup
 * update CONTRIBUTING.MD

### CODE REVIEW

**Comment by maxandersen** [comment]
this is to enforce formatting done in https://github.com/quarkusio/quarkus-quickstarts/pull/451 stays.

**Review by gsmet — APPROVED** [review]
Looks good to me. I fixed a few XML formatting issues and amended your commit.

Now that we have that, I wonder if we could apply it to the other independent projects? We would probably need to sync with Alexey so that it is not in his way.

**Comment by maxandersen** [comment]
> Now that we have that, I wonder if we could apply it to the other independent projects? We would probably need to sync with Alexey so that it is not in his way.

this PR updated independent-projects to use it so already done - since ide-config is changed to independnet project i don't see @aloubyansky or @mkouba having a problem with it (crossing fingers :)

**Comment by gsmet** [comment]
AFAIK it's not used in `tools` and `bootstrap`, thus my request and my concern about it being potentially disruptive for Alexey's work.

**Comment by aloubyansky** [comment]
That's ok, let's do it now.

**Comment by maxandersen** [comment]
> AFAIK it's not used in `tools` and `bootstrap`, thus my request and my concern about it being potentially disruptive for Alexey's work.

yes, didn't change them as they had nothing setup as fear of circular/quarkus dependency. with this change we can ;)

**Comment by maxandersen** [comment]
Pushed update of ide-config that includes enabling it for tools/bootstrap
+ a separate commit where the formatting is applied to tools/bootstrap (that’s why the file count sky rocketed here)

**Comment by gastaldi** [comment]
Looks like this PR needs to be rebased

**Comment by maxandersen** [comment]
rebased - please ack so we can get this merged ;)

**Comment by gastaldi** [comment]
Oops, you'll need to rebase this again @maxandersen, sorry about that ;)

**Comment by maxandersen** [comment]
rebased @gastaldi

**Pull request merged**
