### PR TITLE
Enable Hibernate Envers compatibility in JVM mode

### PR DESCRIPTION
**Pull request by atzoum**
Solves #3231

### CODE REVIEW

**Comment by aloubyansky** [comment]
@atzoum something's wrong with the test. Please, review. Thanks!

**Comment by ebramirez** [comment]
I am not an expert, but shouldn't this be a different quarkus extension?

If not, from now on all app depending on hibernate-orm would depend on hibernate-envers whether they use it or not.

**Comment by atzoum** [comment]
@ebramirez  Envers is brought only as a test dependeny. It is needed to verify in tests that hibernate's bootstrap in quarkus can support envers if it is in the classpath. The dependency is not leaked.

**Comment by atzoum** [comment]
@gsmet please review this PR

**Comment by gsmet** [comment]
@atzoum would you be interested in making Envers work in native too?

I don't know if it works out of the box or if it needs an extension but that would be an interesting exercise.

**Comment by atzoum** [comment]
Interesting indeed, but I fear it will require more time than I can already steal from my day job and family. If nobody has done it before I return from my vacation leave (end of August) I will consider it again.

**Comment by kenfinnigan** [comment]
@gsmet Is this ok to be approved/merged?

**Comment by gsmet** [comment]
Well, it hasn't been reviewed at all so I would say no :).

**Comment by kenfinnigan** [comment]
Fair enough.

@gsmet or @Sanne could one of you review from Hibernate perspective?

**Comment by gsmet** [comment]
Yes, that's on my TODO for 0.20.0.

**Review by gsmet — APPROVED** [review]
I just force-pushed a few minor stylistic changes.

Will merge once CI is green. Thanks!

**Pull request merged**
