### PR TITLE
ArC: remove deprecated @AlternativePriority

### LINKED ISSUE #30963: ArC: remove deprecated @AlternativePriority
### Description

The `@AlternativePriority` annotation has been deprecated since Quarkus 2.6 and it seem 3.0 is a good time to drop it. However, it is used in several core Quarkus extensions and at least one Quarkiverse extension, so I'm filing a separate issue for that and will submit a standalone PR. The migration path is simple: replace this annotation with the combination of:

- either `@jakarta.enterprise.inject.Alternative` + `@io.quarkus.arc.Priority` (this is getting deprecated),
- or `@jakarta.enterprise.inject.Alternative` + `@jakarta.annotation.Priority`.

### Implementation ideas

1. Replace with `@jakarta.enterprise.inject.Alternative` + `@jakarta.annotation.Priority` in the Quarkus core repo.
2. Submit a PR to the Quarkiverse extension affected.
3. Remember to add a note to the 3.0 migration guide.

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #30963

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Great, thanks!

**Review by manovotn — APPROVED** [review]

**Review by ebullient — APPROVED** [review]

**Comment by gastaldi** [comment]
Would it make sense to update the migration script to perform the substitution? Like it was done in https://github.com/quarkusio/quarkus/pull/31048/files#diff-25a7ff48d429b9b6bf3d3b74dc0facab416423333ed0c10d2bbb95233b35da91

**Comment by manovotn** [comment]
> Would it make sense to also update the migration script to perform the substitution? Like it was done in
> 
> * https://github.com/quarkusio/quarkus/pull/31048/files#diff-25a7ff48d429b9b6bf3d3b74dc0facab416423333ed0c10d2bbb95233b35da91

Can the rewrite actually change one annotation into two?
And can it preserve annotation value in one of them?
Genuine questions, never really tried anything else than namespace change or swapping one annotation for another without values :)

Because what we would need is `@AlternativePriority(1)` -> `@Alternative @Priority(1)`

**Comment by gastaldi** [comment]
@manovotn that's a good question, I'll investigate and write one if not available and update the migration script in a later PR then 👍🏻

**Comment by Ladicek** [comment]
It didn't occur to me that we could add a migration for this, but it's certainly worth trying! Thank you! :-)

**Pull request merged**
