### PR TITLE
Make JAX-B Marshaller / Unmarshaller classes request scoped

### PR DESCRIPTION
**Pull request by geoand**
This is done because these classes are not thread safe

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]
Thanks a lot! Let's see how the CI goes

**Comment by geoand** [comment]
@Sgitario I needed to make some pretty big changes, mind taking another look?

**Comment by geoand** [comment]
@gastaldi would also appreciate a review from you

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
This one is a bit hard to backport given:
```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
	deleted by us:   extensions/jaxb/runtime/src/main/java/io/quarkus/jaxb/runtime/JaxbContextProducer.java
```

We probably need to backport something else first. But not sure it's worth it?

**Comment by gastaldi** [comment]
> We probably need to backport something else first. But not sure it's worth it?

That would be https://github.com/quarkusio/quarkus/pull/25801, but yeah, I don't think this PR needs to be backported IMHO

**Comment by geoand** [comment]
Agreed

**Pull request merged**
