### PR TITLE
Use proper config phase for JacksonBuildTimeConfig

### PR DESCRIPTION
**Pull request by geoand**
Furthermore, eliminate the unecessary synthetic bean
as Arc automatically creates beans for Quarkus config objects

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
I think I did that at first but I had a weird error I didn't have time to deal with.

But if CI passes for you, that's definitely a tad better!

**Comment by gsmet** [comment]
Hmmm we have a test failure that looks unrelated but looks concerning:
```
 Error:  Failures: 
Error:    PackageIT.testQuarkusPackageOutputDirectory:88 
Expecting:
 <1>
to be equal to:
 <0>
but was not.
[INFO] 
Error:  Tests run: 103, Failures: 1, Errors: 0, Skipped: 2
```

**Comment by geoand** [comment]
I'll check it out in little while

**Comment by geoand** [comment]
I am not sure what happened with that test as there is nothing in the logs (we'll have to wait for the build artifact to become available) and I couldn't reproduce it locally.

**Comment by gsmet** [comment]
Weird failure:
```
[INFO] Checking for existing resources in: /home/runner/work/quarkus/quarkus/integration-tests/kubernetes/quarkus-standard-way/src/main/kubernetes.
Error: Exception in thread "main" java.lang.NoClassDefFoundError: io/quarkus/jackson/runtime/JacksonBuildTimeConfig
	at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:889)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
```

**Comment by geoand** [comment]
I pushed a fix.

I turns out that the this has to do with how the prod mode test sets up the build classpath. To get around it, I simply added quarkus-jackson as dependency to the k8s tests

**Comment by rsvoboda** [comment]
We have hit `java.lang.ClassNotFoundException: io.quarkus.jackson.runtime.JacksonBuildTimeConfig` in OpenShift TS run against Quarkus master. Adding `quarkus-jackson` into dependencies fixed the issue for us.

The same trouble can probably affect users. WDYT @geoand ?

**Comment by geoand** [comment]
Can I see the application that causes this problem?

**Comment by geoand** [comment]
For the time being, I am removing the `backport` label until we can investigate further

**Comment by rsvoboda** [comment]
It's our OpenShift testsuite which had the problem.

https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/171

This was the error we got:
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.489 s <<< FAILURE! - in io.quarkus.ts.openshift.messaging.artemis.ArtemisTest
Error:  testLastPrice  Time elapsed: 0.009 s  <<< ERROR!
java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/quarkus/jackson/runtime/JacksonBuildTimeConfig
Caused by: java.lang.NoClassDefFoundError: io/quarkus/jackson/runtime/JacksonBuildTimeConfig
Caused by: java.lang.ClassNotFoundException: io.quarkus.jackson.runtime.JacksonBuildTimeConfig
```

**Comment by rsvoboda** [comment]
Reproducer (with Quarkus master build locally), using `messaging/artemis` to demonstrate the fail:
```
git clone https://github.com/quarkus-qe/quarkus-openshift-test-suite.git
cd quarkus-openshift-test-suite
git checkout 06ddb14
mvn -Dquarkus-core-only test -pl .,app-metadata/runtime,app-metadata/deployment,common,messaging/artemis
```
No need for OpenShift cluster, this fails with "local" `@QuarkusTest`

**Comment by geoand** [comment]
@gsmet this PR turns out to be very problematic. If it was backported, then we also need to backport https://github.com/quarkusio/quarkus/pull/14644

**Comment by geoand** [comment]
I see that it is not part of the `1.11` branch, so no need to worry :)

**Pull request merged**
