### PR TITLE
test case for issue #1888

### PR DESCRIPTION
**Pull request by isikemre**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Needs a rebase, and also does not seem to pass CI at the moment.

**Comment by gsmet** [comment]
@dmlloyd yes, it's normal CI doesn't pass, it's a failing test case for the HV integration.

**Comment by isikemre** [comment]
@dmlloyd I synced my fork with the current master.

**Comment by dmlloyd** [comment]
This was synchronized with a merge commit.  For reference, the code to review is: https://github.com/quarkusio/quarkus/pull/1913/commits/73005bdd1d7e81f1a4158d2ba243173a584e31b5

**Comment by cescoffier** [comment]
I've retriggered the CI builds.

**Comment by cescoffier** [comment]
actually, can't restart the build as the build is gone.

**Comment by gsmet** [comment]
@cescoffier as mentioned, CI won't pass for this one. It's a test case for a failing configuration we don't support right now.

**Comment by cescoffier** [comment]
oh ok...

**Comment by ebullient** [comment]
I included this test in PR #5308

**Comment by cescoffier** [comment]
Closing due to inactivity.

**Pull request closed without merging**
