### PR TITLE
Update QuarkusIntegrationTestExtension.java

### PR DESCRIPTION
**Pull request by ygyg70**
Allow override of dev services props by integration test extensions

Will enable workaround for https://github.com/quarkusio/quarkus/issues/34049

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
Seems reasonable, but we would need to do the same thing in `NativeTestExtension` and `QuarkusMainIntegrationTestExtension` as well

**Comment by geoand** [comment]
We would also need the commits to be squashed

**Comment by ygyg70** [comment]
Updated `NativeTestExtension` and `QuarkusMainIntegrationTestExtension` in a similar way

**Comment by ygyg70** [comment]
Commits can be squashed when merged, right?

**Comment by geoand** [comment]
Unfortunately not from the GitHub UI when you also want to include a merge commit

**Comment by ygyg70** [comment]
Not sure the squash worked, so created also another pull request with all changes in a single commit:
https://github.com/quarkusio/quarkus/pull/34685

**Pull request closed without merging**
