### PR TITLE
Fix iteration between streams

### LINKED ISSUE #22402: quarkus create -S 2.5 fails if registry.quarkus.redhat.com is first
### Describe the bug

I have quarkus.redhat.com and quarkus.io listed:
```
quarkus registry list
Configured Quarkus extension registries:
playground.io (disabled)
registry.quarkus.redhat.com
registry.quarkus.io
(Read from /Users/max/.quarkus/config.yaml)
```

but running create using -S 2.5 (latest recommend community) fails:

```
quarkus create -S 2.5
Creating an app (default project type, see --help).
[ERROR] ❗  Unable to create project: Failed to locate stream 2.5 in platform(s): com.redhat.quarkus.platform, io.quarkus.platform
```

If I run `quarkus registry remove registry.quarkus.redhat.com` then `quarkus create -S 2.5` starts working 

### Expected behavior

should generate for stream 2.5 as found in the registry.quarkus.io registry.

Or at least state which platforms was searched so user can understand why it was rejected/not found.

### Actual behavior

just says it cannot find 2.5 even though it is there.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #22402

### CODE REVIEW

**Comment by gastaldi** [comment]
@aloubyansky not sure if you had a fix ready (as the issue was assigned to you), but I found it during my tests and this seems to work well

**Comment by aloubyansky** [comment]
Yes, this makes sense. I wouldn't like to close the issue without the test though.

**Comment by gastaldi** [comment]
> I wouldn't like to close the issue without the test though.

Sure, I tried to create a test but the amount of code required to reproduce this wasn't worth the effort (too many layers to mock). Anyway, feel free to close or add to this PR if you have something.

**Comment by aloubyansky** [comment]
@gastaldi I am closing this one in favor of https://github.com/quarkusio/quarkus/pull/22729 Could you review it please?

**Pull request closed without merging**
