### PR TITLE
Declare maven central as repository for gradle plugin resolution

### PR DESCRIPTION
**Pull request by glefloch**
By default plugin are only resolved against the gradle plugin portal. this adds maven central as an other repository

### CODE REVIEW

**Comment by gsmet** [comment]
Any idea why it started to fail suddenly? We had this setup since forever?

**Comment by glefloch** [comment]
There seems to be an issue on there side https://status.gradle.com

**Comment by glefloch** [comment]
I think we can merge this one, it will be more resilient in the feature.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
So... I'm leaning toward not merging because I want the environment to be as close as possible as when people will use the plugin (and when they use the plugin, they don't have Maven Central I think).

Maybe let's close it and if we have the issue again, we can revisit? If it's just an outage, that's life.

**Comment by glefloch** [comment]
Sure no problem, yes outage can happen.

**Pull request closed without merging**
