### PR TITLE
Remove unconfigured datasource

### LINKED ISSUE #36666: Health check on io.quarkus.agroal.runtime.UnconfiguredDataSource always reports healthy
### Describe the bug

An application using only agroal extension can start even if no datasource has been configured. 

This is because https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L147C9-L153C1

An the same application healthCheck wil lreport healthy as UnconfiguredDatasource doesn't overwrite AgroalDatasource.isHealthy which defaults to true.

That means the error is only discovered once someone tries to use the datasource, which is far too late.

### Expected behavior

I would expect the application not to start or at least report as not ready.

### Actual behavior

The application runs without any errors.

### How to Reproduce?

Simply create an application using only agroal datasource (no orm), start (not in dev mode) the application without configuring anything

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I can provide a MR but I am quite sure what the rigth way would be as even if the behaviour is expected on some cases (as per Datasources comment) it's not always the case.

### PR DESCRIPTION
**Pull request by jtama**
Fixes https://github.com/quarkusio/quarkus/issues/36666

### CODE REVIEW

**Comment by jtama** [comment]
So I manually dispatched the build but it skipped everything. Don't know why. And my laptop is dying so I can't build all quarkus  ;)

**Comment by yrodiere** [comment]
> So I manually dispatched the build but it skipped everything. Don't know why. And my laptop is dying so I can't build all quarkus ;)

The workflow ignores the `main` branch in forks, don't ask me why. You need to work in a branch that is not named `main`...

**Comment by yrodiere** [comment]
@jtama I think your build is still failing? https://github.com/jtama/remove-unconfigured-data-source/actions/runs/6649954232/job/18069255620

See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style

**Comment by jtama** [comment]
> @jtama I think your build is still failing? https://github.com/jtama/remove-unconfigured-data-source/actions/runs/6649954232/job/18069255620
> 
> See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style

Yes indeed I did spoke to quickly. Fixing all this and now correcting the real errors which are for the moment, extension that needed to explicitly handle unconfigured datasources as error cases...

**Comment by yrodiere** [comment]
> Yes indeed I did spoke to quickly. Fixing all this and now correcting the real errors which are for the moment, extension that needed to explicitly handle unconfigured datasources as error cases...

Maybe we should list those and discuss this more widely before you spend too much time on it, as we're not sure yet this is the right approach... please ping me when you get a full build listing all errors.

**Comment by jtama** [comment]
I have this https://github.com/jtama/remove-unconfigured-data-source/actions/runs/6651810790

**Comment by yrodiere** [comment]
Looking at the tests, I realized that this removal of UnconfiguredDatasource is hitting a few problems because "deactivating" datasources is sometimes necessary, but the only way we provide to do this is implicit, by not providing connection info.

I'll try to implement a way to explicitly "deactivate" a datasource through a configuration property as [discussed on quarkus-dev](https://groups.google.com/g/quarkus-dev/c/AnJLtYwgQxs/m/pYr1njhCAgAJ), and will send a PR. We'll see where this leads us.

Thanks for the initial investigation @jtama!

**Comment by yrodiere** [comment]
See also #37265

**Pull request closed without merging**
