### PR TITLE
Ensure that the manifest of the generated jar is the first entry

### LINKED ISSUE #5399: java.util.jar.JarInputStream.getManifest() returns null for quarkus-runner.jar
**Describe the bug**
JarInputStream.getManifest() returns **null** for quarkus-runner.jar

**Expected behavior**
Return non-null Manifest.class

**Actual behavior**
Returns null

**To Reproduce**
1. create quarkus-runner.jar (which includes META-INF/MANIFEST.MF)
2. execute the following code
```
InputStream file = Main.class.getResourceAsStream("/quarkus-runner.jar");
Manifest manifest = new JarInputStream(file).getManifest();
Objects.requireNonNull(manifest);
```
3. Verify NullPointerException

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux
 - Output of `java -version`: OpenJDK-8, IBM-8, Corretto-8
 - Quarkus version or git rev: 1.0.0.CR1

**Additional context**
Issue encountered when using azure-webapp-maven-plugin:1.8.0, which verifies if the deployed jar is an executable jar based on JarInputStream.class

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #5399

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
no backport?

**Comment by geoand** [comment]
We could add it for sure, but I don't think it's terribly critical. I'll let others decide if we want to backport it or not.

**Comment by geoand** [comment]
There might a windows issue with this... I restarted the tests to see if it was just a flake

**Comment by geoand** [comment]
I just ran the entire build and tests on my Linux machine and it worked. I'll restart the Windows stuff and in case it's a flake. Otherwise I might need some help from someone with a Windows machine.

**Comment by stuartwdouglas** [comment]
The windows failure looks related.

**Comment by geoand** [comment]
The Windows test does seem to fail consistently... Unfortunately there are no logs nor do I have access to a Windows machine.

@jaikiran IIRC you did look into some related Windows things in the past? Mind taking a look at this one please? 
If you like I can give you access to my fork so you can push straight to my branch.
Thanks!

**Comment by jaikiran** [comment]
Hello @geoand, sorry was away and am just catching up with the messages. 

> Mind taking a look at this one please?

Certainly, I'll take a look at this one along with the other Windows issue that I was planning to look into. I expect to get access to a Windows system tomorrow, so should be able to see what's going on.

> If you like I can give you access to my fork so you can push straight to my branch.

For now, I'll just pull in your commit locally during testing.

**Comment by geoand** [comment]
Thanks a ton @jaikiran!

**Comment by jaikiran** [comment]
Hello @geoand, I was able to look into this and figure out what's going on. It turns out an issue within the test case itself. Can you give me write permissions on this PR/branch(?) so that I can push a commit which will fix it and retrigger the CI?

**Comment by geoand** [comment]
@jaikiran thanks a lot! You should have received an invitation to collaborate on my fork

**Comment by jaikiran** [comment]
Thank you @geoand.

So the reason why this PR was failing on Windows was due to the following exception (which wasn't accessible easily in the CI infrastructure)

```
Caused by: java.nio.file.FileSystemException: C:\quarkus\integration-tests\maven\target\test-classes\projects\project-uberjar-true\target\acme-1.0-SNAPSHOT-runner.jar: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildUberJar(JarResultBuildStep.java:169)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:948)
	... 7 more
```
This was because the newly added method `ensureManifestOfJarIsReadableByJarInputStream` method wasn't closing the streams it was opening. I've updated this PR to fix that. This change passed locally on a Windows setup. So let's see how it goes now on our CI.

As for the changes in this PR itself, they look good to me.

**Review by jaikiran — APPROVED** [review]

**Comment by geoand** [comment]
@jaikiran thanks for getting to the bottom of this!
Silly mistake, I should have spotted in. Next time with the logs you added it will be much easier 😎.

Also feel free to add yourself as a co-author of the commit if you haven't done so already.

**Comment by geoand** [comment]
@stuartwdouglas does this look good to you?

**Comment by geoand** [comment]
@jaikiran seems to still be failing in Windows

**Comment by jaikiran** [comment]
Let me just rerun this whole branch against a Windows OS locally. Will get the results in a few minutes.

**Comment by jaikiran** [comment]
> @jaikiran seems to still be failing in Windows

@geoand Looks like this branch lost the change I had committed. The try-with-resources change I had added to `ensureManifestOfJarIsReadableByJarInputStream` no longer exists. Perhaps an accidental overwrite?

**Comment by geoand** [comment]
@jaikiran hm... I deleted my branch locally and then pulled your change. 
However maybe I made a mistake, let me update it.

**Comment by geoand** [comment]
Pushed the correct change. Thanks again @jaikiran

**Comment by geoand** [comment]
All tests pass and this was verified also by @jaikiran (which I thank for his Windows fix), so I'll merge it

**Pull request merged**
