### PR TITLE
Fix Dockerfile.multistage example

### PR DESCRIPTION
**Pull request by micheljung**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Good catch!

**Comment by gastaldi** [comment]
On another topic, shouldn't the line 

```docker
RUN gradle -b /code/build.gradle buildNative
```

be 

```docker
RUN gradlew -b /code/build.gradle buildNative
```

instead?

**Comment by gastaldi** [comment]
Just noticed that this is a duplicate of https://github.com/quarkusio/quarkus/pull/24850

Since that PR was opened first, I'll close this one.

Thanks!

**Comment by micheljung** [comment]
> On another topic, shouldn't the line
> 
> ```
> RUN gradle -b /code/build.gradle buildNative
> ```
> 
> be
> 
> ```
> RUN gradlew -b /code/build.gradle buildNative
> ```
> 
> instead?

I knew there was a second change I missed! :) https://github.com/quarkusio/quarkus/pull/24873

**Pull request closed without merging**
