### PR TITLE
Add ability to run unit tests

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This lets continous testing run tests
that are not annotated with @QuarkusTest

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@gsmet not sure if it is too late or not but assuming it passes it would be good to get this one into the alpha.

**Comment by gsmet** [comment]
I was starting the release process but given we are just waiting for the JDK  builds and they shouldn't be too long, I will wait.

**Comment by gsmet** [comment]
@stuartwdouglas hard to say if it's a GH Actions glitch or a more general problem but this build was very slow. We used to be able to build the whole thing in < 3 hours and here we didn't not build everything and the Windows build was cancelled and the others were also very long.

I wonder if we should check if a recent patch has introduced some significant slowness or not.

**Review by gsmet — APPROVED** [review]
Let's get this in to get early feedback.

**Comment by stuartwdouglas** [comment]
GH was super glitchy when I submitted it. I did notice that it was taking a lot longer than the other ones in have seen lately.

**Pull request merged**
