### PR TITLE
Update to Smallrye JWT 3.0.0-RC5

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by radcortez — APPROVED** [review]

**Comment by sberyozkin** [comment]
@radcortez Thanks, some Kubernetes errors this time, restarted the builds

**Comment by sberyozkin** [comment]
@radcortez Hmm, there is some instability with the CI

**Comment by gsmet** [comment]
Sergey, please see my email on quarkus-dev and my message on Zulip. Stop restarting this CI run. Thanks.

**Comment by sberyozkin** [comment]
@gsmet yeah, after a couple of attempts yesterday I spotted your messages :-). Will restart now as agreed

**Comment by gsmet** [comment]
Restarted the build but GH Actions has some issues so we will see how it goes.

**Comment by sberyozkin** [comment]
Hi Guillaume - thank you; I'm feeling guilty with my PRs and their author being a bit pesky :-).

I've just checked my own fork has it green:
https://github.com/sberyozkin/quarkus/actions/runs/548311670

So I'm happy to merge it, as long as @radcortez and yourself are OK, the messaging test failed and also smallrye-config test, and I haven't restarted yet :-)

Cheers

**Comment by radcortez** [comment]
> Hi Guillaume - thank you; I'm feeling guilty with my PRs and their author being a bit pesky :-).
> 
> I've just checked my own fork has it green:
> https://github.com/sberyozkin/quarkus/actions/runs/548311670
> 
> So I'm happy to merge it, as long as @radcortez and yourself are OK, the messaging test failed and also smallrye-config test, and I haven't restarted yet :-)
> 
> Cheers

It's fine. What is failing is some API breakage on Health I believe that I need to check.

**Pull request merged**
