### PR TITLE
Don't require ordering on GraphQL executions

### LINKED ISSUE #29141: Mailer stuck when sending a message from GraphQL endpoint
### Describe the bug

Sorry me could you explain some situation with **Mailer** and **GraphQL** that happened in Quarkus version `2.13.4.Final` (since `2.10.4.Final` like i test). Why mail send stuck, when i send e-mail from GraphQL?

Example: i create project with two endpoints REST (`io.quarkus:quarkus-resteasy-reactive-jsonb`) and GraphQL (`io.quarkus:quarkus-smallrye-graphql`), and i use Mailer for mail send (`io.quarkus:quarkus-mailer`).

REST:
```
package io.quarkus.explore.testclient.graphql;

import io.quarkus.mailer.Mail;
import io.quarkus.mailer.Mailer;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("")
public class TestMailRest {

    @Inject
    Mailer mailer;

    @GET
    @Path("/mail")
    public void send() {
        mailer.send(Mail.withText("to@acme.org", "A simple email from quarkus", "This is my body"));
    }

}

```

GraphQL:
```
package io.quarkus.explore.testclient.graphql;

import io.quarkus.mailer.Mail;
import io.quarkus.mailer.Mailer;
import javax.inject.Inject;
import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Query;

@GraphQLApi
public class TestMailGraphQL {

    @Inject
    Mailer mailer;

    @Query("checkMailSend")
    public String checkMailSend(String targetAddress) {
        mailer.send(Mail.withText("to@acme.org", "A simple email from quarkus", "This is my body"));
        return "Mail test!";
    }

}

```

**Scenario - 1:**
If i run project, and then execute REST GET to `/mail` all will be fine and message send complete, like in documentation examples.

**Scenario - 2:**
!**Restart project**!. And then, if i run it again and execute GraphQL operation:
```
query TestMail {
  checkMailSend(targetAddress: "NotMatter")
}
```
then application stuck and i have error:
```
     2022-11-09 09:23:31,247 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-0,5,main] has been blocked for 60392 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blockedce:quarkusDev
        at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
        at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
        at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
        at java.base@17.0.5/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:67)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
        at io.quarkus.mailer.runtime.BlockingMailerImpl.send(BlockingMailerImpl.java:21)
        at io.quarkus.mailer.runtime.BlockingMailerImpl_Subclass.send$$superforward1(Unknown Source)
        at io.quarkus.mailer.runtime.BlockingMailerImpl_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.mailer.runtime.BlockingMailerImpl_Subclass.send(Unknown Source)
        at io.quarkus.mailer.runtime.BlockingMailerImpl_ClientProxy.send(Unknown Source)
        at io.quarkus.explore.testclient.graphql.TestMailGraphQL.checkMailSend(TestMailGraphQL.java:17)
        at io.quarkus.explore.testclient.graphql.TestMailGraphQL_Subclass.checkMailSend$$superforward1(Unknown Source)
        at io.quarkus.explore.testclient.graphql.TestMailGraphQL_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.explore.testclient.graphql.TestMailGraphQL_Subclass.checkMailSend(Unknown Source)
        at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:92)
        at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.lambda$invokeAndTransformBlocking$0(QuarkusDefaultDataFetcher.java:62)
        at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher$$Lambda$1516/0x0000000800e2d308.call(Unknown Source)
        at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
        at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.BlockingHelper.lambda$runBlocking$0(BlockingHelper.java:27)
        at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.BlockingHelper$$Lambda$1517/0x0000000800e2d748.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.ContextImpl$$Lambda$1304/0x0000000801313a98.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.ContextImpl$$Lambda$1302/0x0000000801313440.run(Unknown Source)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at io.vertx.core.impl.TaskQueue$$Lambda$1266/0x000000080129f6a0.run(Unknown Source)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
```

**Scenario - 3:**
!**Restart project**!. And then, if i run REST GET **before GraphQL** and then i execute GraphQL query all will be fine again. GraphQL mail send work if you execute REST before it.

**Important: it is work great in 2.7.2.Final without any problem, but in new versions it is broke for me.**

### Expected behavior

**Scenario - 1:** - Work well!

**Scenario - 2:** - Mailer send my message via GraphQL.

**Scenario - 2:** - I no need execute REST before GraphQL.

### Actual behavior

**Scenario - 1:** - Work well!

**Scenario - 2:** - Mailer stuck and thread blocked error happened.

**Scenario - 2:** - Work strange, because i need execute REST before GraphQL.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

JDK 17 from Gradle Java toolchain

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.5.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes https://github.com/quarkusio/quarkus/issues/29141

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
The failure looks related.

**Review by phillip-kruger — APPROVED** [review]
Nice

**Comment by geoand** [comment]
> The failure looks related.

Indeed!

**Comment by jmartisk** [comment]
I'm going to look into the failure today

**Comment by jmartisk** [comment]
We seem to be breaking Panache tests because after this change, multiple queries in a single request are executed in parallel (which I think is ok from GraphQL point of view. Mutations are still serial) - Hibernate doesn't handle this properly because the map in `RequestScopedSessionHolder` isn't concurrent: https://github.com/quarkusio/quarkus/blob/2.14.1.Final/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/RequestScopedSessionHolder.java#L18, so when two parallel query executions both access Hibernate, it can blow up here on a `ConcurrentModificationException`.
The tests start passing after changing it to a `ConcurrentHashMap`, but I'm not sure if this is what we should do, maybe this approach is wrong for other reasons (CC @Sanne). 
It could also potentially be a breakage to applications that don't expect queries to be executed in parallel.
So I'm not completely sure about this..

**Comment by gsmet** [comment]
@yrodiere could you have a look at @jmartisk 's comment just above as I think it was you who introduced this class ^

**Comment by yrodiere** [comment]
> @yrodiere could you have a look at @jmartisk 's comment just above as I think it was you who introduced this class ^

Not really, I just renamed `RequestScopedEntityManagerHolder` to `RequestScopedSessionHolder` when I introduced support for injecting `Session`. Stuart originally introduced this class back in 2019.

> multiple queries in a single request are executed in parallel (which I think is ok from GraphQL point of view. Mutations are still serial)

That's not okay from Hibernate ORM's point of view. If you're hitting this problem, there are multiple issues in your code:

1. You're not using transactions. We only rely on request-scoped sessions if there's no transaction in progress. [You should use transactions](https://quarkus.io/guides/transaction#why-always-having-a-transaction-manager), really, even for read-only operations; that will save you a lot of trouble.
2. You are most likely going to use a single `Session` from multiple threads. `Session` is not thread-safe. You should use a separate session in each thread.

The easiest way to fix both issues would be to start a separate transaction in each thread. [`QuarkusTransaction.requiringNew()`](https://quarkus.io/guides/transaction#programmatic-approach) offers ways to do that programmatically, or you can play around with [`@Transactional`](https://quarkus.io/guides/transaction#declarative-approach). Alternatively, you can create sessions manually without dealing with transactions, but I'm not sure if that's compatible with Panache, and anyway, as I said above, [you should use transactions](https://quarkus.io/guides/transaction#why-always-having-a-transaction-manager).

The only valid reason of using a `ConcurrentHashMap` here that I can think of is if you're going to rely on the same request scope in multiple threads, but each thread uses a different persistence unit. Which, while possible, seems unlikely, and doesn't seem to be your case.

**Comment by Sanne** [comment]
I would recommend to not run queries in parallel; if you know in advance that you're going to need certain sub-graphs of data to be fetched, you should express it as a single fetch request to Hibernate so that it can optimise for the particular plan. AFAIR @beikov had offered to help to optimise the GraphQL/ORM integration.

Like @yrodiere already suggested you'd really want these operations to happen within the same transaction, but beyond safety requirements this also risks opening a pandora box in terms of introducing a much more difficult to scale architecture:
remember that each session (and transaction) is going to consume a connection to the database, and we only have a limited number available; people need to be able to cap the maximum size of those connection pools appropriately and it's much simpler to tie this to the expected load (expressed as incoming request rate to be handled) rather than having to take into account the cardinality and complexity of the data loading patterns, which are likely different on each request, and having to multiply that by the expected load.. this will result in requiring very high connection pools, and ultimately an extremely expensive bill from the DB side.
Failing to estimate this accurately there's good chances that this will deadlock, as you need to be able to proof that you can always proceed or release resources before needing to acquire new ones.

In terms of efficiency, if each incoming request needs to delegate multiple sub-jobs to various executors that's not going to perform well - I expect to see lots of cross-cpu talk in such an architecture, and CPUs wasting time waiting for each other. If we could instead express the data-loading need to the ORM, there's good chances it can fullfull the request in a reduced set of roundtrips - and within a single transaction.

Finally - I'm not a CDI expert but I don't think it's ok to use "request scope" for parallel operations - it's possible that the issues you're seeing with Hibernate are just a red flag, you might have other issues with other components binding to it.

**Comment by jmartisk** [comment]
Ok guys thanks for explanations, with the current scope of this PR it would probably be just dangerous.

**Comment by Bazalii** [comment]
@jmartisk is there another way to solve this problem with reactive calls inside graphql blocking context?

**Comment by jmartisk** [comment]
I'd say you either switch to a non-blocking context, or, until we figure it out, apply a workaround that sends some sort of dummy mail once, with the non-reactive mailer.
Something like this that runs on startup could do it:
```
public void workaround(@Observes StartupEvent evt) {
        Mail mail = Mail.withText("to@acme.org", "A simple email from quarkus", "This is my body");
        mailer.send(mail);
        System.out.println("Workaround finished");
    }
```
and then sending more mails from GraphQL blocking operations should work

**Comment by Bazalii** [comment]
@jmartisk Thank you!

**Pull request closed without merging**
