### PR TITLE
Use Mockito.RETURNS_SMART_NULLS by default

### LINKED ISSUE #32134: @InjectMock should enable RETURNS_SMART_NULLS for Mockito
### Description

Mockito returns null for unstubbed methods. This is problematic for methods that expect a non-null value and can be hard to track down.

Mockito has a solution to make locating these unstubbed calls easier using https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#RETURNS_SMART_NULLS.

I don't think there's a downside to enabling for all mocks generated by `@InjectMock`.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #32134

### CODE REVIEW

**Comment by geoand** [comment]
The test failures are related

**Comment by geoand** [comment]
The test failures should now be fixed

**Review by Sgitario — APPROVED** [review]

**Review by Sgitario — COMMENTED** [review]
To avoid the breaking change, instead of having this feature always enabled, I would add a new property in the `@InjectMock` annotation to enable this property. This is the same reasoning that Mockito seems to follow as well. 
I bet users would start complaining about something that was returning null, now it returns empty or similar.

**Comment by kdubb** [comment]
Using the returned value from a unstubbed method is an error. The only thing that would succeed in current code are reference equality comparisons. Although I understand your concern, I'd be happier with the breaking change rather than having to remember to add this to every `@InjectMock`.

**Comment by Sgitario** [comment]
> Using the returned value from a unstubbed method is an error.

This seems to be the default behavior of Mockito.

**Comment by kdubb** [comment]
Sure but Quarkus doesn't allow configuring the full range of Mockito features (e.g. default answer, calls real methods, etc.) and is creating sensible defaults for the mocks used in the Arc/CDI environment. I'd argue that this is a sensible default to add.

**Comment by geoand** [comment]
I agree it's the most sensible default

**Comment by geoand** [comment]
Seems like it still needs so love...

**Comment by geoand** [comment]
This actually causes a lot of problems with for Panache Reactive mocking code...

**Pull request closed without merging**
