### PR TITLE
Allow quarkus.application.name to be overridden for Spring Cloud Config Server

### LINKED ISSUE #41011: Allow quarkus.application.name to be overridden for Spring Cloud Config Server
### Description

The ‘Spring Cloud Configuration’ extension uses the `quarkus.application.name` property to determine the configuration files to be loaded on the remote server. This works, but can lead to problems when there are multiple files to load. The property no longer corresponds to anything.

```
quarkus.application.name=common,dc1,my-application
quarkus.application.version=2.62.3

quarkus.spring-cloud-config.enabled=true
quarkus.spring-cloud-config.fail-fast=true
quarkus.spring-cloud-config.url=https://xxxxxx/spring-config-server/
```

In this example, the `quarkus.application.name` option loses its usefulness because the extension forces you to enter information that has nothing to do with the name of the application.

### Implementation ideas

It could be nice to implement a new property `quarkus.spring-cloud-config.names` (default value is `quarkus.application.name`)

**Example**
```
quarkus.application.name=my-application
quarkus.application.version=2.62.3

quarkus.spring-cloud-config.enabled=true
quarkus.spring-cloud-config.fail-fast=true
quarkus.spring-cloud-config.names=common,dc1,my-application
quarkus.spring-cloud-config.url=https://xxxxxx/spring-config-server/
```

### PR DESCRIPTION
**Pull request by thibaultmeyer**
- Resolves: #41011

### CODE REVIEW

**Comment by thibaultmeyer** [comment]
@geoand

**Review by geoand — COMMENTED** [review]
Very nice!

Any chance we can get a test?

**Comment by thibaultmeyer** [comment]
yes, I'll try to add some unit tests

**Comment by geoand** [comment]
I was thinking of something similar to `SpringCloudConfigClientGatewayTest`

**Comment by thibaultmeyer** [comment]
I've added new unit tests, but I'm not 100% sure it's OK.

**Comment by geoand** [comment]
Please see output above for the command that needs to be run in order to properly format the code

**Comment by thibaultmeyer** [comment]
> Please see output above for the command that needs to be run in order to properly format the code

done

**Comment by thibaultmeyer** [comment]
Import are now sorted.

```
mvn -f . net.revelc.code:impsort-maven-plugin:1.10.0:sort
`
``

**Comment by thibaultmeyer** [comment]
I don't understand the rules applied to imports. On my first comit, they were sorted by IntelliJ, on the second by the impsort-maven-plugin. But it still fails.

What are the exact rules I need to follow to ensure that the imports are OK and that the validation goes through? 

When I look other file like 
https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-http/runtime/src/test/java/io/quarkus/amazon/lambda/http/LambdaHttpHandlerTest.java. I dont understand import rules.

**Review by geoand — APPROVED** [review]
Great!

**Pull request merged**
