### PR TITLE
Make Quarkus listen on all interfaces in WSL dev mode

### LINKED ISSUE #22887: Cannot access web app running on WSL from a Windows-hosted client (browser)
### Describe the bug

Open a WSL terminal on Windows.
Create a sample app using the quickstart/archetypes.
Run `mvn quarkus:dev`.
Try to access the app.

### Expected behavior

Be able to see the expected output of the quickstart.

### Actual behavior

404

### How to Reproduce?

As described.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #22887

### CODE REVIEW

**Comment by famod** [comment]
I've just tested this and it works!

_But_ I cannot force `localhost` via `application-dev.yaml`. It sill works via `-D` though.
Is this what we want? It's not something I would actually set, but I think we should obey the user's choice?

**Comment by geoand** [comment]
It should be possible to set `quarkus.http.host` via any of the supported ways. If not, then that's a different bug :)

**Review by famod — APPROVED** [review]
Sorry, my bad: wrong workspace. 🤦‍♂️

**Comment by geoand** [comment]
The failures are unrelated, but I'll restart CI just in case

**Review by rsvoboda — APPROVED** [review]
Tried on Windows machine with wsl and quarkus instance is accessible from Windows-hosted browser

**Pull request merged**
