### PR TITLE
Arc - toString() method invocation should be delegated to contextual …

### LINKED ISSUE #3722: Arc - client proxy should delegate toString() to contextual instance
According to CDI spec, methods on proxies inherited from `Object` are undefined except for `toString()`. See [this](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#client_proxy_invocation) chapter. In combination with chapter 5.4 this indirectly requires `toString()` to be delegated to contextual instances.

ATM Arc doesn't do that (in comparison, Weld does).

@mkouba @jmartisk FYI

### PR DESCRIPTION
**Pull request by manovotn**
…instance.

Fixes #3722

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Comment by manovotn** [comment]
@stuartwdouglas @dmlloyd I can see some native failures here and I have no idea what to do about that. Could you please help?

The stack from CI goes like this:
> Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.lang.Object.toString(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.

**Comment by mkouba** [comment]
Note that the problem occurs when we override `toString()` on a client proxy for a producer method that returns an interface. The method looks like:
```java
public String toString() {
   return this.arc$delegate().toString();
}
```
Where `arc$delegate()` returns an interface such as `io.vertx.ext.web.Router`.

**Comment by mkouba** [comment]
So it turns out we use `invokeinterface` to invoke the `toString()` upon an interface which seems to work in JVM but is probably not legal in SVM. I have a fix so I'll try to add a commit to this PR.

**Comment by mkouba** [comment]
Does anybody have a clue what this means?
```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v /home/vsts/work/1/s/integration-tests/hibernate-orm-panache/target:/project:z --rm --user 1001:117 quay.io/quarkus/ubi-quarkus-native-image:19.2.0 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-hibernate-orm-panache-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -J-Xmx6g -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
Unable to find image 'quay.io/quarkus/ubi-quarkus-native-image:19.2.0' locally
docker: Error response from daemon: Get https://quay.io/v2/: EOF.
See 'docker run --help'.
```

**Comment by gsmet** [comment]
@mkouba I would say it's just a transient error of Quay not responding correctly.

**Pull request merged**
