### PR TITLE
[3.8] Upgrade to opentelemetry-semconv.version 1.26.0-alpha to make CXF 4.0.5 happy

### PR DESCRIPTION
**Pull request by ppalaga**
https://github.com/quarkiverse/quarkus-cxf/issues/1465

### CODE REVIEW

**Comment by ppalaga** [comment]
cc @brunobat

**Comment by ppalaga** [comment]
The failures in MailerTruststoreTest are reproducible before this change and are therefore unrelated.

**Comment by brunobat** [comment]
will take a look soon

**Review by brunobat — APPROVED** [review]
The old classes are still present. The change is backwards compatible.
I've run the OTel tests with the PR and they seem to be ok. 
CI errors seem unrelated.
CC @gsmet

**Comment by gsmet** [comment]
@ppalaga I think we can proceed with this BUT it needs to go in `main` first and have the 3.8 label as AFAICS `main` is still 1.25 (which I just figured out...).

Given this PR conflicts now, can you close this one and open one against `main` with this update? I'll merge it and backport to 3.8.

**Comment by ppalaga** [comment]
What a pity, would taking 1.25 make things faster for 3.8? 
I can send an upgrade to main anyway.

**Comment by ppalaga** [comment]
I mean what you said sounded like it might be too late to make 1.26 pass main and catch the  3.8.6 train. If so, I'd prefer having 1.25 in 3.8.6, if that's an option for you?

**Comment by gsmet** [comment]
No, that's not what I'm saying. I'm saying it needs to be merged in `main` first as `main` is still using 1.25 (I noticed it due to a Dependabot PR).
So just create a PR for `main` and I will take care of the backports and it will be in 3.8.6, no change in plan.

Sorry if I wasn't clear enough.

**Pull request closed without merging**
