### PR TITLE
Runtime ClassLoader's buffer evictions

### LINKED ISSUE #13258: Deferred release of JarFile buffers in RunnerClassLoader
**Description**
As a follow up to #13157 : releasing the caches isn't super effective as there's much code (and resources) possibly being loaded much later after the bootstrap has completed.

**Implementation ideas**
There's a number of things we could do.

## Switch to immediate-close, with threshold

@stuartwdouglas in https://github.com/quarkusio/quarkus/pull/13219#issuecomment-725682255 suggests we could, after bootstrap, switch to a strategy of opening/closing the jars immediately - and give up of closing it again if we observe there's many opening events happening - just counting it to go over some threshold.

Personally I like the principle, but I'm afraid of the impact of having many sequential open/close requests - I can think of some scenarios in which it's not going to be nice.

I think my main problem with this is that performance of the application could possibly get severely inconsistent while it stabilizes into the right threshold, and it's hard for us to guess a reasonable number for such threshold.

## Switch to SoftReferences

This could be improved with a SoftReference? We'd open on demand, and close the Jar on GC - this should give it the opportunity to reuse the same Jar buffers, should there be sequential need. Except I'm not a fan of XReference tricks, they usually end up costing some other unpredicted soul.

## Periodic unload

We could use a timer to cleanup the JarFile caches each N seconds. And [edited following @geoand 's suggestions below], only close a Jar after some access grace period.

This is interesting, provided we can reuse an existing thread - would prefer to not need to start a dedicated new thread. Perhaps the main thread, which is sitting waiting for the app to quit could occasionally wake up and verify things? There might be other things it could do.

## Other?

TBD

To be considered that solving #13256 should also mitigage the need for this, so SoftReferences could be good enough.

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #13258 

The interesting bit is in the last commit: 266af76

### CODE REVIEW

**Comment by geoand** [comment]
Very interesting idea!

Have you measured it at all to see how it performs?

**Comment by Sanne** [comment]
I measured retained memory; from that perspective it's great as it does
what I intended: jar files in excess of the 4 allowed references are closed
even if I trigger a "post boot burst".

In terms of efficiency I think the algorithm is very low overhead, however
I entirely made it up on the spot ;)

The model is similar to a stack as the most recent opened jar is closed
first, but only if it was accessed only once. This takes into account "
hotness" and doesn't get the cache wiped by one off probes. Works very well
combined with your resource indexing PR.

I didn't measure post- boot classloader throughout .. I believe we're ok
for that to take some minimal hit? It's not a pattern we encourage, so at
that point we trade efficiency of jar opening to save memory on these
buffers.

**Comment by geoand** [comment]
I am wondering if the use `synchronized` could cause any performance issues. 
Did you see any slowdown when comparing this to what we already have?

**Comment by Sanne** [comment]
> I am wondering if the use `synchronized` could cause any performance issues.
> Did you see any slowdown when comparing this to what we already have?

I didn't notice any slowdown - but didn't run benchmarks either.  I'm maybe missing somthing, why would you expect this synchronized block to get in the way of runtime performance? It's extremely short and it's on a path which will do some I/O to load resources/classes.

I can reduce the synchronization scope just in case, let me push one more change..

**Comment by geoand** [comment]
> > I am wondering if the use `synchronized` could cause any performance issues.
> > Did you see any slowdown when comparing this to what we already have?
> 
> I didn't notice any slowdown - but didn't run benchmarks either. I'm maybe missing somthing, why would you expect this synchronized block to get in the way of runtime performance? It's extremely short and it's on a path which will do some I/O to load resources/classes.
> 

Just because it's `synchronized` :) and because at the boot of the application this will be called a lot. 
I don't expect there to be any noticeable slowdown, just want to be on the safe side.

**Comment by Sanne** [comment]
Ok yes I agree on being cuatious. Testing a minor improvements.. but the `synchornized` will stay, just reducing the scope.

N.B. that during boot all the synchronized block needs to do is to read a boolean ;)

Even after boot, at most we'll be scanning for reference equality on a array of 4 elements. I'm now moving the `resetInternalCaches` operations out of the critical section.

**Comment by Sanne** [comment]
@geoand pushed.. It also includes a rebase, but the last changes are in the last commit only.

**Comment by geoand** [comment]
Seems like CI choked... Mind force pushing again?

**Comment by Sanne** [comment]
had to re-push this one as well, as consequence of addressing concerns on #13503

**Comment by geoand** [comment]
I like the idea this brings to the table but would also like to hear what @stuartwdouglas has to say

**Comment by gsmet** [comment]
> I didn't notice any slowdown - but didn't run benchmarks either.

This concerns me a bit. If we're doing optimization work, we need to benchmark it to be extra sure. I can't count the times I thought an optimization was a good idea and it ended making things worse when benchmarking.

**Comment by Sanne** [comment]
@gsmet I don't think that applies here as we're not aiming for top throughput.

The goal of this patch is to mitigate _memory costs_ associated with post-boot resource loading activities that some applications might exhibit - at a tradeoff (by design) of a minimal peformance impact that only applies to either one-off operations (delayed class initialization), or suboptimal extensions (recurring resource loading). It is meant to mitigate problems caused by suboptimal code - and it's part of a larger plan such as fully extracting resources which are actually needed (Vertx already does so).

On the other hand, I did thest both:
 - the memory benefits are working (and are significant)
 - the alleged performance costs is not noticeable

Considering a "benchmark" is about collecting metrics and match some goal, I'm satisfied we did that. How else would you test this?

N.B. the reason I'm doing such things is precisely to make it all integration-testable, with upcoming changes, so to be able to ensure we actually cast such improvements in stone. Please see the design proposals on the issue, including related #13256

**Comment by Sanne** [comment]
Rebased - Although CI was green

**Comment by stuartwdouglas** [comment]
There is the possibility to affect the runtime performance of serving static resources here, especially if there are multiple jars with META-INF/resources entries.

In general serving from zip files is not great, but we do it because it is convenient, and in theory static resources should be served via a CDN anyway, so I am not sure how much it matters, but it would be good to get some measurements on how much this is affected.

**Comment by Sanne** [comment]
Rebased to dodge conflicts.

@stuartwdouglas ok I'll try to have a look at the performance of static resources tomorrow. I had the impression Vertx would cache them on filesystem, but need to verify this again after other changes.

**Comment by Sanne** [comment]
BTW I guess you all want me to test specifically for static resources which are stored across many jars? (with "many" >4)

Because clearly if they are only loaded from a couple of "resource jars" then they won't be evicted at all, and would get loaded as before the patch. That's why I assume there was no need to benchmark this, as I don't expect applications to spread-out static resources across many jars - but I guess I can test what the impact could be in such case.

**Comment by gsmet** [comment]
This is not an uncommon scenario nowadays. Think webjars.

**Comment by Sanne** [comment]
Ok, I verified this again and it's still true: static resources are being cached on filesystem by Vertx

See io.vertx.core.file.impl.FileResolver#resolveFile

Each resource loading event needed to serve static content is hitting this method, and triggers a classloader load at most once.

There's some things we could do better there - for example, avoid the synchronized block that the vertx method hits - but the present PR is unrelated.

**Comment by geoand** [comment]
+1 for this PR from me

**Comment by Sanne** [comment]
I'll need some approval please :) Anyone? Any unresolved concerns?

**Comment by geoand** [comment]
Stuart is on PTO for a few days, so it might be a while until we get his approval :)

**Comment by Sanne** [comment]
@geoand you could approve? We're going to need this patch, would be nice to have it in earlier for baking.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
I approved. We can always revert or improve if we see this approach causes issues in some cases.

**Comment by Sanne** [comment]
Sure :) Thanks.

I might be wrong, but actually think the approach is very sound; if there's some problem it's more likely to be in the details of my cache implementation - I'm always nervous when dealing with array indices but traced this one carefully :)

**Comment by geoand** [comment]
> Sure :) Thanks.
> 
> I might be wrong, but actually think the approach is very sound;

I do to!

**Pull request merged**
