### PR TITLE
Provide a way to push container properties to database dev services

### LINKED ISSUE #20654: can't create mysql trigger in dev container
### Describe the bug

If I put  `CREATE TRIGGER ...` in my Flyway migration sql,  `quarkus dev` will complain:

```
2021-10-10 21:22:19,770 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.sql.SQLException: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
```

According to https://www.testcontainers.org/modules/databases/mysql/,  I set these properties but they don't work:

```
%dev.quarkus.datasource.devservices.properties.TC_MY_CNF=testcontainers/mysql_conf
%test.quarkus.datasource.devservices.properties.TC_MY_CNF=testcontainers/mysql_conf
```

```
$ cat src/main/java/testcontainers/mysql_conf/extra.cnf 
[mysqld]
log_bin_trust_function_creators=ON
```

### Expected behavior

The `extra.cnf` should be mounted into mysql container.

### Actual behavior

The `extra.cnf` isn't mounted into mysql container.

### How to Reproduce?

Put some `CREATE TRIGGER ...` in src/main/resources/db/migration/V1.0.0__init.sql,  run  `quarkus dev` to make it create mysql container automatically.

### Output of `uname -a` or `ver`

Darwin XXX.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

Client Version 2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

quarkus dev

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #20654

### CODE REVIEW

**Comment by gsmet** [comment]
I asked the OP here https://github.com/quarkusio/quarkus/issues/20654 to confirm it's working OK.

**Review by geoand — APPROVED** [review]
👍🏼

**Comment by Dieken** [comment]
> I asked the OP here #20654 to confirm it's working OK.

confirmed, it works, nice! 👍🏻

**Comment by ekoptybenko-aligntech** [comment]
Hello. Can you please provide the final configuration?
Right now I cannot start the dev services mysql image due to:

2024-05-17 16:19:21 2024-05-17 20:19:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.37-1.el9 started.
2024-05-17 16:19:21 2024-05-17 20:19:21+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
2024-05-17 16:19:21     command was: mysqld --verbose --help --log-bin-index=/tmp/tmp.tgIihWbWwc
2024-05-17 16:19:21     mysqld: Can't read dir of '/etc/mysql/conf.d/' (OS errno 20 - Not a directory)
2024-05-17 16:19:21 mysqld: [ERROR] Stopped processing the 'includedir' directive in file /etc/my.cnf at line 36.
2024-05-17 16:19:21 mysqld: [ERROR] Fatal error in defaults handling. Program aborted!


My configuration is:
quarkus:
  devservices:
    enabled=true:
  datasource:
    db-kind: mysql
    devservices:
      container-properties:
        TC_MY_CNF: testcontainers/mysql-conf

And mysql-conf file contains the following:
log_bin_trust_function_creators = 1

**Comment by Dieken** [comment]
FYI:

```
$ grep devservices src/main/resources/application.properties
quarkus.datasource.devservices.image-name=mysql:8.0.31
quarkus.datasource.devservices.container-properties.TC_MY_CNF=testcontainers/mysql-conf

$ find testcontainers/
testcontainers/
testcontainers//mysql-conf
testcontainers//mysql-conf/extra.cnf

$ cat testcontainers/mysql-conf/extra.cnf 
[mysqld]
log_bin_trust_function_creators=ON
```

**Pull request merged**
