### PR TITLE
Fix consumes in rest score template;add consumes in endpoints template

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this fix!

@SaumyaSingh1 mind reviewing it?

**Review by saumya1singh — APPROVED** [review]

**Comment by SaumyaSingh1** [comment]
Looks good :)

Thanks, @jimma!

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
@geoand is it really something I can backport? This page was modified a lot AFAIK.

**Comment by geoand** [comment]
Wasn't the modification also marked for backport? If not, then it probably can be.

If we want to skip backporting these sort of UI changes, I'm fine with that too.

**Comment by gsmet** [comment]
Yeah, the thing is that they are not tested at all, except manually. So... I'd rather avoid backporting structural changes. I can try backporting this one and see if there are conflicts or if it applies cleanly.

**Comment by geoand** [comment]
OK, no problem at all

**Pull request merged**
