### PR TITLE
Restore compatibility with Mandrel 20.3

### LINKED ISSUE #18513: Serialization support breaks backwwards compatibility with GraalVM/Mandrel 20.3
## Describe the bug
After merging https://github.com/quarkusio/quarkus/pull/15380 we observe failures when using GraalVM/Mandrel 20.3.

### Expected behavior
Tests should pass.

### Actual behavior
Tests fail. See https://github.com/graalvm/mandrel/actions/runs/1006524072 for logs

## To Reproduce

1. clone and build latest Quarkus
2. 
```
./mvnw verify -B --settings .github/mvn-settings.xml --fail-at-end -Dtest-containers -Dstart-containers -DfailIfNoTests=false -Dnative-image.xmx=5g -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.3-java11 -Dnative.surefire.skip -f integration-tests -pl jpa-h2
```

## Environment (please complete the following information):

| Key                          | Value                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| ---------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| uname -a                     | Linux 5.12.13-300.fc34.x86_64 #1 SMP Wed Jun 23 16:18:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux<br>                                                                                                                                                                                                                                                                                                                                    |
| java -version                | openjdk version "11.0.11" 2021-04-20<br>OpenJDK Runtime Environment 18.9 (build 11.0.11+9)<br>OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)<br>                                                                                                                                                                                                                                                                          |
| mvnw --version               | Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)<br>Maven home: /home/zakkak/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1<br>Java version: 11.0.11, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-4.fc34.x86_64<br>Default locale: en_IE, platform encoding: UTF-8<br>OS name: "linux", version: "5.12.13-300.fc34.x86_64", arch: "amd64", family: "unix"<br> |
| Quarkus version | 86536349bd14ff4a402d6de82943499e65741f47 |
| Mandrel image | quay.io/quarkus/ubi-quarkus-mandrel:20.3-java11 |

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

## Additional context
Reverting #15380 (see branch https://github.com/zakkak/quarkus/tree/revert-serialization) makes the tests pass https://github.com/graalvm/mandrel/actions/runs/1008436919

### PR DESCRIPTION
**Pull request by gsmet**
Fix #18513

@zakkak I let you push this PR to your CI? Thanks!

### CODE REVIEW

**Comment by zakkak** [comment]
Closes https://github.com/quarkusio/quarkus/issues/18513

**Review by zakkak — APPROVED** [review]
LGTM. Thanks Guillaume!

Could we also add some comments tight above the changes that are for 20.3 compatibility so that we can easily grep them (and ultimately remove them) in the future?

Waiting for the CI to finish.... https://github.com/graalvm/mandrel/actions/runs/1011083032

**Comment by gsmet** [comment]
@zakkak I think we'd better just revert the commit rather than track individual changes. So let's just make sure we can find the PRs we need to revert.

**Comment by zakkak** [comment]
@gsmet OK 

The tests in [my CI run](https://github.com/graalvm/mandrel/actions/runs/1011083032) look good. Please merge once the Quarkus CI is happy as well :)

**Comment by gsmet** [comment]
I will split some of the work into a separate PR as some fixes need to stay after reverting this.

**Comment by gsmet** [comment]
Note for future selves: when dropping Mandrel 20.3 support, please only revert the last commit!

**Pull request merged**
