### PR TITLE
Have the Mongo Clients initialized eagerly

### LINKED ISSUE #7895: Mongo clients should be initialized eagerly
**Describe the bug**
Currently the mongo clients are flagged as @ApplicaitonScoped, which means they are wrapped by a proxy making them initialized on first use.

This is annoying as

* we don't respect the configuration of pre-filling the pool on boot
* we can't validate the connection properties, deferring any failure
* it's an overhead

relates to #4507

### PR DESCRIPTION
**Pull request by Postremus**
We propably also should add a heads up in the migration guide.

/cc @dufoli 
closes #7895

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM but a review by @cescoffier is needed on this one

**Review by loicmathieu — APPROVED** [review]

**Review by mkouba — APPROVED** [review]
Looks good but I'm no Mongo expert ;-).

**Comment by cescoffier** [comment]
@mkouba yes, but this change is mostly about ApplicationScoped to Singleton. The mongo part is not impacted.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Before merging,  I would prefer having a go from the metrics guy.

**Comment by mkouba** [comment]
> The mongo part is not impacted.

It's ok to change the scope and expect `@Singleton` beans to be initialized eagerly (when injected) but it could impact some other parts of the mongo extension (bootstrap logic, etc.) about which I have no idea...

**Comment by jmartisk** [comment]
IIUC this is semi-eager, because the client will still only initialize once a bean that injects it is being initialized, so it does not necessarily mean initializing right after start, right?

**Comment by mkouba** [comment]
> IIUC this is semi-eager, because the client will still only initialize once a bean that injects it is being initialized, so it does not necessarily mean initializing right after start, right?

Yes, as I said in my previous comment - eagerly, when injected. One could use `@io.quarkus.runtime.Startup` or add `void onStart(@Observes StartupEvent event)` to initialize the bean at startup.

**Review by jmartisk — APPROVED** [review]
LGTM

**Pull request merged**
