### PR TITLE
Update to smallrye-jwt-2.4.3

### LINKED ISSUE #14450: Quarkus JWT producing 401 errors using @RolesAllowed
**Describe the bug**

I´m running into an issue with Quarkus JWT and I cannot get past the 401 error as none of my requests is getting authorized.

To create my ssh key pair I´m using the following code from the documentation https://quarkus.io/guides/security-jwt#generating-a-jwt :

```
openssl genrsa -out src/main/resources/privateKey_tmp.pem 2048
openssl rsa -pubout -in src/main/resources/privateKey.pem -out src/main/resources/META-INF/resources/publicKey.pem
openssl pkcs8 -topk8 -nocrypt -inform pem -in src/main/resources/privateKey_tmp.pem -outform pem -out src/main/resources/privateKey.pem
```

And I´m creating my token with

```
Jwt
                .issuer("some-id")
                .groups("user")
                .expiresAt(System.currentTimeMillis() + 1000000000L)
                .sign()
```

While providing the necessary properties in **application.properties**

I´ve created a small producer where you just need to run the **tests**.

https://github.com/mklueh/quarkus-jwt-401-reproducer

Am I missing something or do I issue invalid tokens for whatever reason?

Thanks for any help

### PR DESCRIPTION
**Pull request by sberyozkin**
Also fixes #14450.

### CODE REVIEW

**Comment by gsmet** [comment]
@sberyozkin is it something that should be backported?

**Review by gastaldi — APPROVED** [review]

**Comment by sberyozkin** [comment]
Hi @gsmet it improves on a few things in the build API (better control of the claim object types), aligns the key location property names with the verification key locations, and also supports the key rotation for the HTTP-only based key sets - but here it uses a new mechanism compared to 2.4.2 - so there might be a low risk here. So I guess it is OK to keep it for 1.12.0 only.

**Comment by sberyozkin** [comment]
@gastaldi thanks; I forgot to update the docs as 2 build api props have been deprecated and new ones aligning with the existing smallrye-jwt naming pattern for the verification keys (as also requested by the Quarkus user) have been added. I'll update you ince I force-push

**Comment by sberyozkin** [comment]
@gastaldi @gsmet did a doc update as well

**Review by gsmet — APPROVED** [review]

**Comment by sberyozkin** [comment]
MP context-propagation tests have had some problem, so I've restarted

**Pull request merged**
