### PR TITLE
Use idiomatic RESTEasy Reactive filter declaration for OpenTelemetry

### LINKED ISSUE #31245: [Regression in 2.16.3] `NullPointerException: Cannot invoke "org.jboss.resteasy.reactive.server.SimpleResourceInfo.getResourceClass()" because "this.resourceInfo" is null`
### Describe the bug

There seems to be a regression in 2.16.3: RestAssured tests that were running fine with 2.16.2 now fail with error code 500.

I can see the following in the logs:
```
2023-02-17 10:10:11,260 WARN  (f1cedf409aa3d4426067cc1700745ce6,86399571e387844a) [de.tsy.mms.nrw.reg.api.exc.ApiExceptionMapper] (executor-thread-0) internal exception: java.lang.NullPointerException: Cannot invoke "org.jboss.resteasy.reactive.server.SimpleResourceInfo.getResourceClass()" because "this.resourceInfo" is null
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.resteasy.OpenTelemetryReactiveServerFilter.filter(OpenTelemetryReactiveServerFilter.java:29)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:48)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:104)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
So it looks related to OTEL...?

### Expected behavior

No error

### Actual behavior

REST endpoints fail

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #31245

### CODE REVIEW

**Comment by famod** [comment]
So I cherry-picked this on top of branch `2.16` and **it does fix the problem!**

Thanks a lot @geoand!

**Comment by geoand** [comment]
Very interesting, thanks for checking!

I wish I knew why the previous version failed, but I can live with not knowing 😂

**Comment by famod** [comment]
Yeah sorry, it's a bit unsatisfying. I just couldn't put together a reproducer in the the little time I had thus far. :-/

**Comment by geoand** [comment]
No worries :)

**Review by Sgitario — APPROVED** [review]

**Pull request merged**
