### PR TITLE
Inject DevServicesContext in QuarkusTest via default TestResource

### PR DESCRIPTION
**Pull request by ozangunalp**
`DevServicesContext` is already injectable using a TestResource implementing `DevServicesContext.ContextAware`. 
It is automatically injected into `@QuarkusIntegrationTest` but not `@QuarkusTest`. 
However, the doc states that both injection should work OOTB : https://quarkus.io/guides/getting-started-testing#testing-dev-services

Having both `@QuarkusIntegrationTest` but not `@QuarkusTest` is useful for ITs directly extending the regular test.

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]
Looks nice, thanks. +1 if tests pass :)

**Comment by geoand** [comment]
Test failures do seem related :)

**Comment by ozangunalp** [comment]
Indeed, I'll check

**Comment by ozangunalp** [comment]
Ok `DevUIGrpcSmokeTest.testTestService` is not related, it is flaky or already always failing.

For `TestChangeTrackingWhenStartFailsTestCase`, it seems like the fact that I've added a global test resource changes the way tests are skipped or not. @geoand do you have an idea why?

I'll handle the injection without the test resource.

**Comment by geoand** [comment]
> For TestChangeTrackingWhenStartFailsTestCase, it seems like the fact that I've added a global test resource changes the way tests are skipped or not. @geoand do you have an idea why?

Really weird. Can't think of anything off hand

**Review by geoand — APPROVED** [review]
Thanks!

**Pull request merged**
