### PR TITLE
Application classes classloader

### PR DESCRIPTION
**Pull request by geoand**
Add DeploymentClassLoaderBuildItem

This is a 'transformer safe' class loader that can be used
to load application classes

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by gastaldi** [comment]
No tests?

**Comment by geoand** [comment]
The current testsuite should suffice I think unless @kenfinnigan can think of a test that needs to be added to the OpenAPI integration test

**Comment by cescoffier** [comment]
@gastaldi Quickstarts covers that.

**Comment by geoand** [comment]
The test failure is totally unrelated and is known

**Pull request merged**
