### PR TITLE
Document @RegisterForReflection(targets=)

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by geoand** [comment]
Thanks!

There is also a similar section at https://github.com/quarkusio/quarkus/blob/b22b0c0bfb9a087b2f259590effa5e0ebbbdce3c/docs/src/main/asciidoc/writing-native-applications-tips.adoc#alternative-with-registerforreflection.

Maybe that should be removed?

**Review by geoand — APPROVED** [review]

**Comment by loicmathieu** [comment]
> Maybe that should be removed?

It's a good question, I think so as the section is clearly about extension.
I also can just add a link to the corresponding section, but having two times the same thing in a guide is not a good idea.

**Comment by loicmathieu** [comment]
I removed the duplicated section.

**Comment by geoand** [comment]
LGTM

**Pull request merged**
