### PR TITLE
Do not include the default values when serializing mutable extension catalog objects

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Comment by aloubyansky** [comment]
Adding the backport label since I would like to upgrade the platform generator to 2.7.x (not wait for 2.8).

**Review by gastaldi — DISMISSED** [review]
LGTM

**Review by ebullient — COMMENTED** [review]
How often are mutable variants serialized? In most cases, I would expect the post-build (immutable) artifact to be written (and those are already set to avoid writing defaults, IIRC)

**Review by ebullient — CHANGES_REQUESTED** [review]
I'd like to understand the use case (why builders are being serialized, instead of using the built result), because it doesn't match some expectations I had, which means we may be missing something else.

**Comment by aloubyansky** [comment]
I was able to avoid the need for this change after all. So it can be closed. Thanks @ebullient

**Pull request closed without merging**
