### PR TITLE
Fix build issue when client and server RESTEasy Reactive jackson deps are used together

### PR DESCRIPTION
**Pull request by geoand**
The issue was originally reported [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/reactive.20server.20.26.20client/near/233703482).

### CODE REVIEW

**Comment by geoand** [comment]
@famod is there a way we have can have an enforcer rule that enforces that all classes that  extend `MultiBuildItem`, `SimpleBuildItem` and `EmptyBuildItem` are `final`?

**Comment by famod** [comment]
ArchUnit would be way more suitable for such things.

**Comment by geoand** [comment]
But I don't see I way that such rules could apply to all modules, no?

**Comment by famod** [comment]
It's not totally trivial, but via surefire you can run tests from jars so you could define those rules in a central module and add executions to all modules that need to be checked (ideally only add it to a parent to cover as much as possible).

**Comment by geoand** [comment]
Understood, thanks 👍

**Comment by geoand** [comment]
I don't have any immediate plans, no.

But it's certainly something I'll keep in mind if no one else comes up with something in the meantime

**Comment by famod** [comment]
@geoand let's track that via https://github.com/quarkusio/quarkus/issues/16370 and whoever finds the time to do that can take that issue.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
thanks @geoand !

**Pull request merged**
