### PR TITLE
Qute - loop section - introduce the {#else} block

### PR DESCRIPTION
**Pull request by mkouba**
- this block is executed if there are no items to iterate

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Good idea

**Comment by gastaldi** [comment]
@mkouba looks like it conflicts now with your other PR

**Comment by mkouba** [comment]
> @mkouba looks like it conflicts now with your other PR

Yep, I'll fix it...

**Comment by mkouba** [comment]
It seems that the CI is currently somewhat unstable. Let's try for the last time...

**Comment by gsmet** [comment]
This is a very good idea, can't wait to have it available as I was too lazy to cover the corner cases and with this, cost is ~0!

**Pull request merged**
