### PR TITLE
Fix various IT modules and add them to the CI matrices

### PR DESCRIPTION
**Pull request by cescoffier**
- Fix the gRPC Test Random Port IT (cannot use injection)
- Fix the virtual thread webauthn IT (cannot use injection)
- Fix the opentelemetry redis instrumentation IT (still unable to retrieve the exception)

### CODE REVIEW

**Comment by cescoffier** [comment]
@brunobat would be great to understand why we cannot retrieve the "exception" in native.

**Comment by jponge** [comment]
This makes me think that the mutiny native IT tests are not in the CI

**Comment by brunobat** [comment]
I'm taking a look at it... 
The event actually shows up, but not the message:
```
 "events": [
    {
      "name": "exception",
      "attributes": {
        "empty": false
      },
      "totalAttributeCount": 3,
      "epochNanos": 1712845473066243041,
      "droppedAttributesCount": 0
    }
```

**Comment by brunobat** [comment]
> ```
>  "events": [
>     {
>       "name": "exception",
>       "attributes": {
>         "empty": false
>       },
>       "totalAttributeCount": 3,
>       "epochNanos": 1712845473066243041,
>       "droppedAttributesCount": 0
>     }
> ```

It says the attribute count is 3 but only 1 shows up... I wonder if this is a JSON parsing problem.

**Comment by gsmet** [comment]
Is it normal you dropped `hibernate-reactive-mssql` entirely?

**Comment by gsmet** [comment]
@brunobat could it be that we need to register something for reflection?

**Comment by cescoffier** [comment]
@gsmet I'm puzzled about `hibernate-reactive-mssql`, it does not seem to be in the reactor at all. So I was wondering. It is something we added and removed? or something we added but we forgot to add it to the CI? 

@Sanne do you know? ^

**Comment by cescoffier** [comment]
>  This makes me think that the mutiny native IT tests are not in the CI

Let me add that. You are right! (but because the passed, I forgot about them)

**Comment by cescoffier** [comment]
@jponge I added mutiny-native-jctools.

**Comment by gsmet** [comment]
> hibernate-reactive-mssql

That's a question for @DavideD . My guess is that we need it fixed and added but let's clarify with @DavideD .

If it's confirmed, I would keep the file and keep it disabled for now and ask @DavideD to have a closer look async.

**Comment by brunobat** [comment]
> @brunobat could it be that we need to register something for reflection?

It almost certainly due to this class: https://github.com/quarkusio/quarkus/blob/7e14b560f512652de682d2812df617829e70a090/integration-tests/opentelemetry-redis-instrumentation/src/main/java/io/quarkus/io/opentelemetry/jackson/RegisterCustomModuleCustomizer.java#L12

I know know the problem is on the out serialisation from Quarkus, not the inbound one, from restasured.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
