### PR TITLE
Export package from different module name in 23.1-dev

### PR DESCRIPTION
**Pull request by zakkak**
Module names changed in https://github.com/oracle/graal/pull/7171

### CODE REVIEW

**Comment by gsmet** [comment]
Cancelling CI for now as it is saturated. I will restart this later.

**Review by jerboaa — CHANGES_REQUESTED** [review]
Please add a comment that prior `23.1` the class got provided by `org.graalvm.sdk` module and with `23.1` onwards, it's provided by the `org.graalvm.nativimage` module.

This will have implications on the GraalVM maven dependencies as well once we upgrade to `23.1`.

**Comment by jerboaa** [comment]
> Update: I opened [oracle/graal#7224](https://github.com/oracle/graal/discussions/7224) to ask about it.

Thanks! Once that's come to a conclusion we need to jot down the actual dependency (maven coordinates) which are now considered API and move to that for the 23.1 GraalVM upgrade.

**Review by jerboaa — APPROVED** [review]
Code change seems fine as it makes Quarkus work with current dev tree of 23.1. So looks good! Thanks.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
