### PR TITLE
fix: remove un-used config properties

### PR DESCRIPTION
**Pull request by loicmathieu**
Remove two un-used properties.

They are not passed to MongoDB, and not supported anymore on the MongoDB client.

They should be vestigials of MongoDB 3 client ...

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]
LGTM, Good catch.

I only have one question: removing the property all together will generate a warning "if they are used somehow by users without them knowing that they are not actually supported anymore", so should we document this in the migration guide? 
/cc @geoand @gsmet

**Comment by gastaldi** [comment]
Yeah, I believe this definitely needs to go to the migration guide.

**Comment by machi1990** [comment]
> Yeah, I believe this definitely needs to go to the migration guide.

@loicmathieu mind preparing a word or two that will go in the migration guide. Thanks!

**Comment by loicmathieu** [comment]
I'm OK to add it to the migration guide, but I didn't thougth it's worth it as they are not used since multiple month and there is no migration path to other properties ...

**Comment by gastaldi** [comment]
@loicmathieu that's fine, it's just so users can be aware of that change. Probably won't have much impact but it would be nice to mention that

**Comment by loicmathieu** [comment]
@gastaldi too late, you already merged it ;)

**Comment by machi1990** [comment]
> I'm OK to add it to the migration guide, but I didn't thougth it's worth it as they are not used since multiple month and there is no migration path to other properties ...

To be clear, I was talking about preparing a note that would have ended up here https://github.com/quarkusio/quarkus/wiki/Migration-Guides.

**Comment by gastaldi** [comment]
@machi1990 exactly :) 

@loicmathieu see above :point_up:

**Comment by loicmathieu** [comment]
Ah I forget it's on a separate repo.
Will do tomorrow

**Pull request merged**
