### PR TITLE
Updating to slf4j 1.7.32

### LINKED ISSUE #22569: Inconsistent versions of slf4j-api
### Describe the bug

Getting this enforcer failure when pulling in 2.6.1.Final:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (default) @ jfrunit-core ---
[WARN] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.slf4j:slf4j-api:1.7.30 paths to dependency are:
+-org.moditect.jfrunit:jfrunit-core:1.0.0-SNAPSHOT
  +-io.quarkus:quarkus-junit5:2.6.1.Final
    +-io.quarkus:quarkus-core:2.6.1.Final
      +-org.slf4j:slf4j-api:1.7.30
and
+-org.moditect.jfrunit:jfrunit-core:1.0.0-SNAPSHOT
  +-io.quarkus:quarkus-junit5:2.6.1.Final
    +-io.quarkus:quarkus-bootstrap-core:2.6.1.Final
      +-io.quarkus:quarkus-bootstrap-maven-resolver:2.6.1.Final
        +-org.slf4j:slf4j-api:1.7.30 (managed) <-- org.slf4j:slf4j-api:1.7.32
```

### Expected behavior

One version of the slf4j-api artifact should be used consistently.

### Actual behavior

_No response_

### How to Reproduce?

```
quarkus$ ag -Q "1.7.32"
independent-projects/bootstrap/pom.xml
53:        <slf4j-api.version>1.7.32</slf4j-api.version>
quarkus$ ag -Q "1.7.30"
bom/application/pom.xml
105:        <slf4j.version>1.7.30</slf4j.version>
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gunnarmorling**
Fixes https://github.com/quarkusio/quarkus/issues/22569

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks but let's not merge it. I want to figure out why Dependabot didn't update this occurrence and get it fixed.

**Comment by famod** [comment]
@gsmet this looks strange:
- `updater | INFO <job_250542162> Pull request already exists for org.slf4j:jcl-over-slf4j@1.7.32, org.slf4j:slf4j-api@1.7.32`
  https://github.com/quarkusio/quarkus/network/updates/250542162
- `Looks like these dependencies are updatable in another way, so this is no longer needed.` #22363

**Comment by gsmet** [comment]
This is because of https://github.com/quarkusio/quarkus/pull/22571 .

**Comment by gsmet** [comment]
Hmmm. Looks like this PR https://github.com/quarkusio/quarkus/pull/22363 got us in some sort of mess. I have no idea what's going on.

Let's get this in and we will see how it goes for the next upgrade.

**Review by gsmet — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Thx for merging, @gsmet! Already was concerned I would miss the opportunity for a Quarkus 3.0 shirt ;)

**Pull request merged**
