### PR TITLE
Make class clickable in Log stream (to open in IDE)

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR make the classes in the log file clickable, to open the file, at the correct line number, in the user's IDE (if we could detect it)
It also makes some lines in a stacktrace clickable.

clickable_log

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by geoand** [comment]
WOW! This is great 💯 !

**Review by geoand — APPROVED** [review]

**Comment by phillip-kruger** [comment]
@geoand - getting failures in Kubernetes - Standard for Windows. I am sure it's not related to this PR :)

**Comment by geoand** [comment]
@phillip-kruger can you do me a favor and rebase the PR onto the latest master?

My guess is that the failure will go away

**Comment by geoand** [comment]
> @phillip-kruger can you do me a favor and rebase the PR onto the latest master?
> 
> My guess is that the failure will go away

I'd to CI to verify what I have in mind - that is why I ask :)

**Comment by phillip-kruger** [comment]
Re-based. Let's see !

**Review by gsmet — APPROVED** [review]
Interesting!

**Comment by phillip-kruger** [comment]
@geoand same issue after rebase. I am checking local to see if I can recreate it

**Comment by phillip-kruger** [comment]
@geoand - that specific integration tests builds successful on my Linux box. Any advice how to proceed ?

**Comment by geoand** [comment]
I'll merge the PR as the test is flakey and had since been disabled on main

**Pull request merged**
