### PR TITLE
Update SmallRye Config to 2.11.0

### LINKED ISSUE #24944: Config mapping to a Map with a List value type fails
### Describe the bug

Having a config mapping to a `Map<String, List<Double>>` fails with the `java.lang.ClassCastException`. 

Seems that the [ConfigMappingProvider#processLazyMap](https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/ConfigMappingProvider.java#L416-L488) does not have a correct switch for the `CollectionProperty` and fails with class cast exception.

I can also confirm that the config mapping to `Map<String, Map<Double, Boolean>>` works for example. Again most likely because that `ConfigMappingProvider` does handle the case when value is a map.

### Expected behavior

* the map value resolves correctly in case of a `List` or `Set`

### Actual behavior

* class cast exception

### How to Reproduce?

Simple to reproduce:

```
@ConfigMapping(prefix = "some")
public interface Config {

  Map<String, List<Double>> prop();
  
}  
```

and config:

```
some:
  prop:
    value:    
      - 0.9
      - 0.99
```

leads to:

```
Caused by: java.lang.ClassCastException
	at io.smallrye.config.ConfigMappingInterface$Property.asGroup(ConfigMappingInterface.java:225)
	at io.smallrye.config.ConfigMappingProvider.processLazyMap(ConfigMappingProvider.java:481)
	at io.smallrye.config.ConfigMappingProvider.processLazyMapInGroup(ConfigMappingProvider.java:411)
	at io.smallrye.config.ConfigMappingProvider.processProperty(ConfigMappingProvider.java:215)
	at io.smallrye.config.ConfigMappingProvider.processEagerGroup(ConfigMappingProvider.java:151)
	at io.smallrye.config.ConfigMappingProvider.<init>(ConfigMappingProvider.java:80)
	at io.smallrye.config.ConfigMappingProvider$Builder.build(ConfigMappingProvider.java:955)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:444)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 13 more
```

### Output of `uname -a` or `ver`

Linux ise-Precision-5550 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-39-generic", arch: "amd64", family: "unix"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
https://github.com/smallrye/smallrye-config/releases/tag/2.11.0

- Fixes https://github.com/quarkusio/quarkus/issues/24944

### CODE REVIEW

**Comment by radcortez** [comment]
@gsmet I'll leave this to your consideration if you want to backport it to 2.11. There are a lot of code changes on SR Config, but they should not impact Quarkus.

**Comment by radcortez** [comment]
Sure.

**Comment by edeandrea** [comment]
Thanks @radcortez ! Does this also pull in smallrye/smallrye-config#767?

**Comment by radcortez** [comment]
> Thanks @radcortez ! Does this also pull in [smallrye/smallrye-config#767](https://github.com/smallrye/smallrye-config/issues/767)?

Yes.

**Comment by edeandrea** [comment]
Thank you for keeping me in the loop!

**Review by gsmet — APPROVED** [review]

**Comment by edeandrea** [comment]
Hey @radcortez this doesn't seem to work?

When I try this out using

```
%knative.quarkus.config.profile.parent=prod
%knative.quarkus.kubernetes.deployment-target=knative
%knative-openshift.quarkus.config.profile.parent=knative
%knative-openshift.quarkus.container-image.builder=openshift
%knative-openshift-17.quarkus.config.profile.parent=knative-openshift
```

and then I run

```
 ./mvnw clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.profile=knative-openshift-17 -Dquarkus.kubernetes-client.trust-certs=true -DskipTests -Dquarkus.container-image.group=eric-deandrea-dev -Dquarkus.container-image.registry=
```

I would expect it to pick up `quarkus.kubernetes.deployment-target=knative`, but it doesn't. It does, however, pick up `quarkus.container-image.builder=openshift`.

Does the parent/child hierarchy only traverse 1 level?

**Comment by radcortez** [comment]
No, it is probably related to the relocations of the `smallrye` to the `quarkus` namespace. If you use `smallrye.config` instead it works as expected.

I'll have a look.

**Comment by edeandrea** [comment]
Hi @radcortez I just wanted to circle back and see if you've had a chance to take a look at this?

**Comment by radcortez** [comment]
I believe this should have taken care of it: https://github.com/quarkusio/quarkus/pull/28960

**Comment by edeandrea** [comment]
Thanks @radcortez I'll give it a go!

**Comment by edeandrea** [comment]
Thanks @radcortez - I've verified all is good! See quarkusio/quarkus-super-heroes#232

**Comment by radcortez** [comment]
Great!

**Pull request merged**
