### PR TITLE
Qute: add support to iterate long numbers

### PR DESCRIPTION
**Pull request by DaHoC**
Add support to not only iterate Integer, but also Long in Qute

### CODE REVIEW

**Review by mkouba — CHANGES_REQUESTED** [review]
We should update the docs as well: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/qute-reference.adoc?plain=1#L671-L672

**Comment by mkouba** [comment]
@DaHoC could you pls squash the commits; and do not include merge commits pls ;-).

**Comment by geoand** [comment]
Please squash and rebase the commits. 

Thanks!

**Review by mkouba — APPROVED** [review]

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
@DaHoC your PR description should have `- Fixes #6963` in the title.

**Pull request merged**
