### PR TITLE
Add explicit version boring-ssl

### LINKED ISSUE #9921: Add Specific version for io.netty:netty-tcnative-boringssl-static
`io.netty:netty-tcnative-boringssl-static` is missing specific version 

cc @michalszynkiewicz

### PR DESCRIPTION
**Pull request by RotBolt**
fixes #9921

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this, but I am pretty sure that if this is only meant to be a test dependency, it belongs in https://github.com/quarkusio/quarkus/blob/801dd53c57f5e5df98b5192d3b56d80b777c6a1a/bom/test/pom.xml

**Review by gsmet — CHANGES_REQUESTED** [review]
@RotBolt @michalszynkiewicz could you give some context about what you're trying to solve here?

In any case, we don't define the scope in the bom and the version should be a property. But we need to decide if it should be in the bom or in the test bom, depending on what you're trying to fix.

**Comment by michalszynkiewicz** [comment]
@gsmet it's a test dependency only, isn't it worth making it visible in the bom?

Currently we seem to inherit it from vertx-dependencies, indirectly through vertx dep chain. At the moment it only causes us problems for the product but we want to eliminate the dependency on vertx-dependencies anyway.

**Comment by gsmet** [comment]
The BOM shouldn't contain scopes. But yeah, ideally, it would be nice to get rid of it altogether.

Also, if it's just an issue with the Quarkus build, you can just define it in the `build-parent` pom and avoid putting it in the BOM.

**Comment by gsmet** [comment]
Of course my last sentence is only valid if we are sure it won't be a problem for Quarkus users.

**Comment by gsmet** [comment]
@michalszynkiewicz what's the status of this one? See my comments above.

**Comment by michalszynkiewicz** [comment]
@RotBolt ? Did we work around it in the product build?

**Comment by RotBolt** [comment]
yes it was solved by custom pme param

**Comment by michalszynkiewicz** [comment]
@RotBolt could you change the PR to put the dependency in the build-parent?

**Comment by RotBolt** [comment]
sure.

**Comment by RotBolt** [comment]
@gsmet It would be good if this could be added to 1.7.0

**Comment by michalszynkiewicz** [comment]
@gsmet can you take another look at it?

**Review by gsmet — APPROVED** [review]

**Pull request merged**
