### PR TITLE
Remove obsolete `build-include-jdk-misc` from `core/runtime`

### PR DESCRIPTION
**Pull request by famod**
This avoids the usage of `maven-compiler-plugin` 3.8.1-jboss-2, which seems obsolete at least as far CI in my fork is concerned.

More context:
- https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/maven-compiler-plugin.203.2E9.2E0
- https://github.com/quarkusio/quarkus/commit/bbbe03b051c8f600f1d8c55946502636a7a1019e
- https://github.com/jboss/jboss-parent-pom/blob/main/pom.xml#L924-L977

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@famod I'm not sure how removing this file changes anything the the version of the maven compiler plugin we use? The maven compiler plugin we need, yes, but the one we use?

**Comment by famod** [comment]
Check out the third link, there is a file-activated profile in jboss-parent.

**Comment by gsmet** [comment]
I can see that but I don't see it setting a version of the plugin?

**Comment by famod** [comment]
Right, there is some other magic involved. Need to check later.

**Comment by famod** [comment]
@gsmet that's why: https://github.com/jboss/jboss-parent-pom/pull/112
In that recent PR, @dmlloyd made the switch to the official plugin version.

But in latest released version 39 it's still there: https://github.com/jboss/jboss-parent-pom/blob/jboss-parent-39/pom.xml#L923

**Comment by famod** [comment]
That Gradle issue looks unrelated, it passed in my fork: https://github.com/famod/quarkus/runs/4804350800?check_suite_focus=true#step:7:904

**Comment by gsmet** [comment]
Ah ok cool, that's nice we switch to a standard version.

**Comment by Sanne** [comment]
Nice! that's one less problem when trying to import the project in IDEA.

**Comment by famod** [comment]
Yeah, or fighting overly "secure" artifactory caches.

**Comment by famod** [comment]
JDK 17 failure is not related:
```
Caused by: io.fabric8.maven.docker.access.hc.http.HttpRequestException: {"message":"Get \"https://docker.elastic.co/v2/\": dial tcp 34.68.230.202:443: connect: connection refused"} (Internal Server Error: 500)
```
(and it passed in my fork)

**Pull request merged**
