### PR TITLE
Sync with optaplanner-quickstart PR 506

### PR DESCRIPTION
**Pull request by ge0ffrey**
To keep it in sync with the changes in https://github.com/quarkusio/quarkus-quickstarts/pull/506
Specifically, to make life better for students, there must be soft constraints for students too, which is implemented in the optaplanner-quickstart.

### CODE REVIEW

**Comment by geoand** [comment]
@ge0ffrey what is the proper merging sequence for this and the linked PR?

**Comment by ge0ffrey** [comment]
@geoand The quarkus-quickstart PR ( https://github.com/quarkusio/quarkus-quickstarts/pull/506 ) first.

**Comment by geoand** [comment]
@ia3andy please review and merge this once the quickstart PR is in.

Thanks

**Review by ia3andy — APPROVED** [review]
LGTM

**Pull request merged**
