### PR TITLE
Bump Smallrye Reactive Messaging from 4.16.2 to 4.17.0

### PR DESCRIPTION
**Pull request by ozangunalp**
Resolves split package on health package issue #38711

### CODE REVIEW

**Comment by cescoffier** [comment]
I'm a bit concerned by the Kafka related CI failures.

**Review by cescoffier — APPROVED** [review]

**Comment by ozangunalp** [comment]
My last "fix" apparently didn't fix the KafkaDevServicesDevModeTestCase.sseStream

**Comment by ozangunalp** [comment]
Even without that test, that's awful a lot of test failures.

**Comment by ozangunalp** [comment]
VT test failures are container image fetch failures, so they are not related.

**Pull request merged**
