### PR TITLE
Document the option to install CLI using Scoop

### PR DESCRIPTION
**Pull request by goostleek**
Now we can install the CLI using `scoop install quarkus-cli`. See ScoopInstaller/Main#3573

The [Scoop installation manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/quarkus-cli.json) will be automatically updated each time a new CLI version is [released](https://github.com/quarkusio/quarkus/releases).

@maxandersen Since the Quarkus CLI is now added to the [Scoop main bucket](https://github.com/ScoopInstaller/Main/blob/master/bucket/quarkus-cli.json) and is automatically updated there's no need for keeping the https://github.com/quarkusio/scoop-bucket repository. It can be safely archived/deleted as it looks no longer maintained anyway.

### CODE REVIEW

**Comment by maxandersen** [comment]
interesting! looks like scoop-bucket was missed in the latest config update and that explains why not updated.

Can you outline where/how that installation manifest is updated automatically ? We probably don't want that updated when core is released; we would have that happen when platform is released so would be good to know how that is done.

also I would like the same for jbang which has simpler release gates :)

**Comment by maxandersen** [comment]
ah the update is done using autoupdate at https://github.com/ScoopInstaller/Main/pull/3573/files#diff-62f4cbf713cb8031f3f9a76baecf2aae8ddee88b4eb5a605ce85d1bb62eecee1R17 ?

**Comment by maxandersen** [comment]
I get that. The issue is afaik we don't want the update to the various cli distributions to happen before the platform is released. 

@gsmet when are you releasing the cli'a today - would auto release from GitHub quarkus core release work or we need find options?

**Comment by gsmet** [comment]
If it's only updated when the GitHub release is done, it won't be a problem as we create the Quarkus GitHub release after the Platform is released.

**Comment by gsmet** [comment]
I have one questions though: what about maintenance branch micros? Is this thing smart enough to not switch to 2.7.6.Final when I release it after 2.9.0.Final has been released?

If so, I think we are good.

**Comment by goostleek** [comment]
> Is this thing smart enough to not switch to 2.7.6.Final when I release it after 2.9.0.Final has been released?

Good catch. Unfortunately, it's not as smart. Currently, the manifest [`checkver`](https://github.com/ScoopInstaller/Main/blob/master/bucket/quarkus-cli.json#L13-L16) section will always pick the last released version. That's why it picked up [`2.8.3.FINAL`](https://github.com/ScoopInstaller/Main/blob/4a202ded6c7a27ecd287a30d3f5e22c303bde58d/bucket/quarkus-cli.json#L2) yesterday instead of `2.9.0.Final`.

But if I only knew where I can reliably look for the latest version then I can update the [`checkver`](https://github.com/ScoopInstaller/Main/blob/master/bucket/quarkus-cli.json#L13-L16) section of the manifest to pick the right version. Initially I thought to look for it simply on https://quarkus.io/ (it mentions Quarkus 2.9.0) but I'm not sure if it's a valid approach. Do you think it's ok to look at the main page or maybe we can look somewhere else? I will adjust the manifest accordingly if I get the confirmation from you @gsmet.

**Comment by gsmet** [comment]
@gastaldi @aloubyansky do we have an endpoint somewhere where we can get the latest Quarkus Final release?

**Comment by gastaldi** [comment]
@gsmet https://registry.quarkus.io/client/platforms should have this information (latest stable is the first and may be followed by CRs and another stable) .

**Comment by gsmet** [comment]
@gastaldi we are sure the latest stable is always first? If so, yes, that would work if the `checkver` is flexible enough to talk JSON.

/cc @goostleek

**Comment by aloubyansky** [comment]
Yes, the first one is the currently recommended release.

**Comment by gsmet** [comment]
Cool! @goostleek would it work for you?

**Comment by goostleek** [comment]
Cool 👌  That will do the thing. It's even better for `checkver` to operate on JSON rather than digging through HTML using regexes. I will prepare a PR for [ScoopInstaller/Main](https://github.com/ScoopInstaller/Main) bucket with appropriate changes to the manifest. Stay tuned...

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gastaldi** [comment]
I think https://github.com/quarkusio/scoop-bucket can be safely deleted, since it's not used anywhere it doesn't make sense to be archived, WDYT @maxandersen ?

**Comment by gsmet** [comment]
Yes, I think we can delete it but better wait for @maxandersen 's blessing.

**Comment by maxandersen** [comment]
Yeah. +1 on deleting that repo as we in scoop main and seems never used that quarkus-scoop repo outside my initial dry run. 

Nuke it :)

**Pull request merged**
