### PR TITLE
Adds integration tests for postgresql devservices

### PR DESCRIPTION
**Pull request by netodevel**
Goal: 
Ensure that the devservices feature for postgresql is working correctly;

### CODE REVIEW

**Review by gsmet — COMMENTED** [review]
@stuartwdouglas I would be interested in your take on this. I think if we go this way, we need to be consistent but I'm not sure if we should just create a big module with all of them or having separate modules.

Let's try to decide how we want things before making further progress.

**Comment by netodevel** [comment]
@gsmet 
Thanks for the answer.
To help with your decision, I had already contributed an integrated test for redis devservices. (https://github.com/quarkusio/quarkus/pull/17133)
as soon as you make the decision I adjust the code review points.

note:
if we decide to have multiple modules, we'll need somewhere for the SocketKit class to have no duplication;

**Comment by netodevel** [comment]
@gsmet, @stuartwdouglas,
Hi guys, 
Any feedback about this PR?

**Comment by gsmet** [comment]
Sorry, we haven't have the time to have a proper look at this. @stuartwdouglas is on PTO and I'd like to discuss this with him when he's back. Assigning it to me so that I can keep track of this thing.

**Pull request closed without merging**
