### PR TITLE
Update SmallRye Config to 3.8.1

### PR DESCRIPTION
**Pull request by radcortez**
<summary>SmallRye Config Release notes:</summary>
<br>
<blockquote>
    <h2>3.8.0</h2>
    <ul>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1153">#1153</a> Release 3.8.0</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1150">#1150</a> Update SR Commons to 2.4.0</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1149">#1149</a> Consistent collection type for profiles</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1148">#1148</a> Always include super properties of mappings</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1147">#1147</a> PropertyName do not match star with empty</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1146">#1146</a> Generate mapping names</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1145">#1145</a> Bump org.eclipse.parsson:parsson from 1.1.5 to 1.1.6</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1144">#1144</a> Bump io.smallrye:smallrye-parent from 42 to 43</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1143">#1143</a> Support expression expansion with secret keys configuration values</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1142">#1142</a> Bump org.ow2.asm:asm from 9.6 to 9.7</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1101">#1101</a> Bug! Spring bootJar: NoSuchFileException: /path/application.jar!/BOOT-INF/classes, /path/application.jar!/BOOT-INF/lib/somelib.jar</li>
    </ul>
</blockquote>
<blockquote>
    <h2>3.8.1</h2>
    <ul>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1159">#1159</a> Release 3.8.1</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1158">#1158</a> Keep all mapping names</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1157">#1157</a> Check invalid mapped properties</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1156">#1156</a> Override super members defaults</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1155">#1155</a> Bump org.apache.maven.plugins:maven-shade-plugin from 3.5.2 to 3.5.3</li>
        <li><a href="https://redirect.github.com/smallrye/smallrye-config/issues/1154">#1154</a> Change getSuperTypes to public</li>
    </ul>
</blockquote>

<summary>Quarkus:</summary>

- Adjusted API integration to not require `@ConfigMapping` method reflection registration

### CODE REVIEW

**Comment by gsmet** [comment]
@zakkak @galderz @yrodiere @maxandersen some good news on the reflection front:

> org.opentest4j.AssertionFailedError: Expected analysis_results.methods.reflection to be within range [4893 +- 3%] but was 4551 ==> expected: <true> but was: <false>

It fails because we are below the threshold :).

Now, this is just the methods metrics but it was the one growing significantly every time we migrated a config class to `@ConfigMapping`.
As we don't use Hibernate Validator constraints in the core config, it should avoid registering the methods for reflection for all the core config move to `@ConfigMapping`.

@radcortez needs to adjust the testing a bit on his side of the PR but we should be good for 3.11.

**Comment by zakkak** [comment]
That's great, well done!

**Comment by yrodiere** [comment]
Great!

Just a heads-up: updates to the expected metrics will likely conflict with #40102, so you might want to wait until that's merged before doing all that work.

**Comment by gsmet** [comment]
@zakkak just to be clear, it's only improving the methods (I think), so https://github.com/quarkusio/quarkus/pull/40102/files#diff-f740c865e615865a3cf3a4018a7115b9e528d6ad48595ec8e264bb4fc5b2ea83R4 is probably still problematic.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks for collaborating with me on this, @radcortez !
It's definitely something we needed to improve before considering more candidates for `@ConfigMapping`.

**Comment by radcortez** [comment]
Env variable matching is a bit smarter. Before it was blindly trying to match the expected dotted name. Now, it uses the actual container types to generate the expected name.

**Pull request merged**
