### PR TITLE
Added orm panache hot reload test

### PR DESCRIPTION
**Pull request by FroMage**

### CODE REVIEW

**Review by geoand — APPROVED** [review]
LGTM, although I would personally use RESTAssured's capability of extracting pieces from json and asserting them instead of the whole body

**Review by Sanne — APPROVED** [review]
great, thanks!

**Comment by FroMage** [comment]
> LGTM, although I would personally use RESTAssured's capability of extracting pieces from json and asserting them instead of the whole body

Bah, I felt like I wanted to test that the output reflected the changes and not necessarily test JSON parsing.

**Comment by geoand** [comment]
Yeah, I understand :)

**Comment by geoand** [comment]
Tests seem to have failed

**Comment by FroMage** [comment]
Yeah, damnit. The test fails sometimes, apparently due to ORM sometimes not executing the `import.sql` script :(

**Comment by geoand** [comment]
If it caught an error, the test has already proven it's worth, although it may have been more that you bargained for :P

**Comment by FroMage** [comment]
```
[INFO] Running io.quarkus.hibernate.orm.panache.test.PanacheHotReloadTestCase
2020-03-31 15:25:27,458 WARN  [io.qua.dep.QuarkusAugmentor] (main) Using Java versions older than 11 to build Quarkus applications is deprecated and will be disallowed in a future release!
Hibernate: 
    
    drop table if exists MyEntity CASCADE 
Hibernate: 
    
    drop sequence if exists hibernate_sequence
Hibernate: create sequence hibernate_sequence start with 1 increment by 1
Hibernate: 
    
    create table MyEntity (
       id bigint not null,
        name varchar(255),
        primary key (id)
    )
Hibernate: 
    INSERT INTO MyEntity(id, name) VALUES(1, 'my name')
2020-03-31 15:25:30,190 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 2.826s. Listening on: http://0.0.0.0:8080
2020-03-31 15:25:30,190 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-03-31 15:25:30,190 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, narayana-jta, resteasy, resteasy-jsonb]
Hibernate: 
    select
        myentity0_.id as id1_0_0_,
        myentity0_.name as name2_0_0_ 
    from
        MyEntity myentity0_ 
    where
        myentity0_.id=?
2020-03-31 15:25:31,593 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002010: Failed to execute: javax.ws.rs.WebApplicationException: HTTP 404 Not Found
	at io.quarkus.hibernate.orm.panache.test.MyTestResource.get(MyTestResource.java:21)
```

@Sanne these logs show that I'm creating the DB fine, and `import.sql` is actually called and creates my entity, but on the first request when I query it, I don't see the import yet, _sometimes_.

Can the `import.sql` stuff be running in a transaction not yet committed by the time I execute my first request? Sounds far-fetched, but that's the most logical explanation, no?

**Comment by FroMage** [comment]
@Sanne forget it, it's not that at all.

**Comment by FroMage** [comment]
> that's the most logical explanation, no?

Famous Last Words™

**Comment by FroMage** [comment]
Should pass now.

**Comment by Sanne** [comment]
What was it?

**Comment by FroMage** [comment]
Don't ask.

**Comment by FroMage** [comment]
PBKAC.

**Pull request merged**
