### PR TITLE
Elasticsearch guide fixes

### PR DESCRIPTION
**Pull request by loicmathieu**
- Add missing imports
- Remove the link to the quickstart as it didn't exist
- Replace the frontend by curl examples as the HTML example didn't exist

### CODE REVIEW

**Comment by loicmathieu** [comment]
I openned an issue to create the quickstarts, see #23755, when done the guide could be restored to link the quickstarts

**Review by gastaldi — APPROVED** [review]

**Comment by geoand** [comment]
Is this is meant to be backported?

**Comment by loicmathieu** [comment]
@geoand backporting it would be a great idea as the issue is on the current guide. I added the backport label

**Comment by geoand** [comment]
Cool, thanks

**Pull request merged**
