### PR TITLE
[3.15] (do not merge) docs tooltips

### PR DESCRIPTION
**Pull request by jmartisk**
Turns out we can only properly test the downstream ingestion pipeline against a PR that is open against 3.15 (we can't use https://github.com/quarkusio/quarkus/pull/44070 for the test).
So this is just for testing purposes, and I will close it afterwards.

### CODE REVIEW

**Comment by MichalMaler** [comment]
Test downstreaming pipeline runs here:
https://gitlab.cee.redhat.com/quarkus-documentation/quarkus/-/jobs/28280200

**Comment by MichalMaler** [comment]
Jobs done, pipeline succeded, results look clean!
https://gitlab.cee.redhat.com/quarkus-documentation/quarkus/-/merge_requests/1944
Neat!

**Comment by MichalMaler** [comment]
The table and its content is generated here:
`include::{generated-dir}/config/quarkus-agroal.adoc[opts=optional, leveloffset=+1]`
while that attribute translates to this: `:generated-dir: ../../../target/quarkus-generated-doc`
If I could get to the file, maybe there is a way to add some table configuration so that the resulting text does not wrap after each word.

**Comment by MichalMaler** [comment]
@jmartisk Look, I think it doesn't look bad at all!
image

**Comment by gsmet** [comment]
Another option could be to move the details to a note and have a link to it, similar to what we did with the Duration note.

I don't think it would be that hard to do with the theming support that I added in the plugin recently (and some additional helpers to extract the list of enum with tooltips - we have a visitor pattern for this sort of things). Again it would require a specific execution of the plugin to generate the downstream config doc but it might be a more viable option.

@jmartisk I let you have a look if you want to play with it, I'm available on Zulip if you have any question.

**Comment by MichalMaler** [comment]
@gsmet : Jan will be back at this issue on Thuesday. In the meanwhile, I am for merging https://github.com/quarkusio/quarkus/pull/44070 and backporting it to 3.15, because it provides some raw improvement on our side and QEs are kinda ok with that for the time You and Jan can work on the final solution.
Thank you both for your cooperation and ideas.
Cheers.

**Comment by jmartisk** [comment]
Given that it looks better actually rendered with Pantheon than in the Jenkins job, we decided to keep it for now as is, I've just removed the descriptions from the third column (for the default value of config properties)

**Comment by MichalMaler** [comment]
Testing it here:
https://gitlab.cee.redhat.com/quarkus-documentation/quarkus/-/jobs/28400680

**Comment by MichalMaler** [comment]
@jmartisk Results in Pantheon:
https://content-preview.docs.redhat.com/en/documentation/red_hat_build_of_quarkus/3.15/html-single/configure_data_sources/index#jdbc-configuration
image

Looks good in my books.

**Comment by jmartisk** [comment]
@gsmet should we merge this, or do you prefer adding it to  https://github.com/quarkusio/quarkus/pull/43985 by yourself?

**Comment by rsvoboda** [comment]
I think this could be closed as the change is backported in https://github.com/quarkusio/quarkus/pull/44186

**Comment by jmartisk** [comment]
Cool, thanks @rsvoboda

**Pull request closed without merging**
