### PR TITLE
Add datasource label to DB DevServices

### LINKED ISSUE #28857: Container labels for dev services
### Description

I have a multi tenant setup with multiple databases. Therefor, running quarkusDev or quarkusTest will launch multiple devservices. 
This will result in 2 identical containers with randomly generated names and I am not able to tell which is for which tenant, making debugging difficult.

### Implementation ideas
It would be great if I could either configure a container name of a dev service or attach labels to a dev service, so I can recognize which is which. 

Or even better, the container automatically gets the datasource name as label. The last approach would not clutter up the configs and would not bother anyone.

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes #28857

### CODE REVIEW

**Review by yrodiere — COMMENTED** [review]
I just checked, this works great:

```
$ docker container ls --format 'table {{.ID}}\t{{.Image}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Labels}}'
CONTAINER ID   IMAGE                       CREATED AT                      STATUS          LABELS
51b359b258ea   postgres:14                 2022-10-31 14:59:24 +0100 CET   Up 18 minutes   datasource=db2,org.testcontainers=true,org.testcontainers.sessionId=fe761b0d-1309-49f3-8511-6c1e476aac72
95964b863195   postgres:14                 2022-10-31 14:59:23 +0100 CET   Up 18 minutes   datasource=db1,org.testcontainers=true,org.testcontainers.sessionId=fe761b0d-1309-49f3-8511-6c1e476aac72
86dee578eaa6   testcontainers/ryuk:0.3.4   2022-10-31 14:59:22 +0100 CET   Up 18 minutes   org.testcontainers=true
```

What about documentation, though? Maybe we should document the fact we add datasource labels to launched containers somewhere?

And maybe we could also document the command to list containers and their labels... It may be obvious to some, but I had to google for quite some time, especially since the available fields for templates passed to `--format` are not documented... I struggled for the container ID: I tried `{{.Id}}`, `{{.ContainerId}}`, `{{.Identifier}}`, but it turns out it was `{{.ID}}` (all caps) -_-
Note to anyone as lost as I was: you can get a view of all available fields by running `docker container ls --format 'table {{json .}}'`.

Also... I noticed these log when starting the app:

```
2022-10-31 14:59:24,849 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-28) Dev Services for  datasource 'db1' (postgresql) started.
2022-10-31 14:59:26,517 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-28) Dev Services for  datasource 'db2' (postgresql) started.
```

What do you think of including the container ID there?

**Comment by geoand** [comment]
Great points!

I'll have a look tomorrow and address them

**Comment by geoand** [comment]
@yrodiere the two new commits should address the points you raised.

**Review by yrodiere — APPROVED** [review]
Looks great, thanks!

**Comment by geoand** [comment]
👌🏼

**Pull request merged**
