### PR TITLE
Improvements in native.surefire.skip usage to skip unit tests with -Dnative

### PR DESCRIPTION
**Pull request by zakkak**
Fixes the issue described in https://github.com/quarkusio/quarkus/pull/10791#issuecomment-661939373

### CODE REVIEW

**Comment by zakkak** [comment]
I moved:
```
<native.surefire.skip>${skipTests}</native.surefire.skip>
```
in each integration test's `pom.xml` to be consistent with future integration tests generated using the `create-extension` mojo.

**Comment by zakkak** [comment]
This however does not seem to work because in:
```
                         <configuration>
                             <native.surefire.skip>${skipTests}</native.surefire.skip>
                             <skipTests>${native.surefire.skip}</skipTests>
                         </configuration>
```
`native.surefire.skip` will (at least the way I understand it)  be assigned the value of `skipTests`, but in the next line `skipTests` will not be assigned the freshly assigned value of `native.surefire.skip`.

As a result I think that 
```
<native.surefire.skip>${skipTests}</native.surefire.skip>
```
must be in a parent pom file of the pom that includes:
```
<skipTests>${native.surefire.skip}</skipTests>
```
so that it can get prioritized.

**Comment by zakkak** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
Yes, this change alone doesn't look right. I know there was a create-extension issue but keep in mind that that integration-test-pom.xml template is a Quarkus-specific part. create-extension however is something that can be used outside of the quarkus repo.

**Comment by gsmet** [comment]
The commit message shouldn't have the `fixup!` prefix.

**Comment by zakkak** [comment]
@aloubyansky In that case, if `integration-test-pom.xml` template is a Quarkus-specific part then I think that #10791 is OK and we don't need any further patching, since in Quarkus (#10791) `<native.surefire.skip>${skipTests}</native.surefire.skip>` is included in `integration-tests/pom.xml`.

**Comment by aloubyansky** [comment]
Yes, i think you can leave it for now. BTW, couldn't we move 
```
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skipTests>${native.surefire.skip}</skipTests>
                        </configuration>
                    </plugin>
```
to the `pluginManagement` of the parent pom (in the profile)?

**Comment by zakkak** [comment]
@aloubyansky I am not sure we can. We want this to be enabled only for the native-image profile.

**Comment by aloubyansky** [comment]
I thought we could add pluginManagement to the native profile. Or even configure the plugin in the native profile and customize the configs where necessary in specific test projects. But perhaps that won't work, i'm not sure. I thought i'd ask whether you know.

**Comment by zakkak** [comment]
I am not that familiar with maven so I will have to give it a try and come back :)

**Comment by aloubyansky** [comment]
Great, please do :)

**Review by gsmet — CHANGES_REQUESTED** [review]
Just a note that the commit message and the PR title need some love. We don't want any `fixup!` in there.

**Comment by gsmet** [comment]
I hate to say that and I'm sorry about it but my opinion on this patch (and given the discussion that took place in the other thread) is that it's not really worth the added complexity and the time spent on it.

I think your time would be more valuable on other more pressing issues.

Just my 2 cents though, others may have different opinion.

**Comment by zakkak** [comment]
@gsmet the way I see it this is not "spent time" for the following reasons:
* It reduces the run time of native-image CI jobs by 2% to 8% as shown in https://github.com/quarkusio/quarkus/pull/10791#issuecomment-659725829 (note that Mandrel runs only native-image tests, so the benefits there are more obvious)
* It reduces the time spent to run native-image integration tests locally 
* it's an exercise that helps me better understand how maven works, which I need to in order to achieve my end goal of making quarkus testing more "portable" as discussed in https://groups.google.com/forum/#!searchin/quarkus-dev/github$20ci%7Csort:date/quarkus-dev/_KZe1ydg4C0/tzazd4b0CAAJ.

> Just a note that the commit message and the PR title need some love. We don't want any `fixup!` in there.

Noted. Once we conclude our discussions/experiments this PR will either get out of Draft mode and those will get fixed, or just get closed.

**Comment by famod** [comment]
@zakkak 
Just to clearly state this (but maybe I am just too confused by this change): This has no effect whatsoever.
The custom `configuration` element (= plugin parameter) `native.surefire.skip` is nothing that `maven-surefire-plugin` is aware of and therefore it is simply ignored.

See `test` goal parameter reference: https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html

@aloubyansky is on the right track:
> I thought we could add pluginManagement to the native profile. Or even configure the plugin in the native profile and customize the configs where necessary in specific test projects. But perhaps that won't work, i'm not sure.

As long as _all_ `jar`submodules under `integration-tests` shall execute native tests when the profile is active, the most DRY solution would be to add the profile to the parent (`integration-tests`), but _not_ with `pluginManagement` (see paragraph at the bottom).
This way we could drop most of the native-profile definitions in the submodules.
The ones that need special config would need to either define the profile (with `activation`!) and add their parts to the plugin (and inherit the other defaults) _or_ a few custom properties at parent level would need to be addded so that the submodules in question could override those properties.

It becomes more complicated if some jar-submodules should _not_ execute/native any native stuff.
You cannot "un-inherit" a profile from a parent. You could only add "skip" properties for all plugins in that profile.
Or you could a "negative" file activation to the profile in the parent so that a submodule can place a marker file so that the profile is disabled for it.
No very pretty, but that is how the (limited) profile mechanism works.

Downside of `pluginManagement`:
- you need to redefine the version
- you still need to define the profile in each submodule

**Comment by zakkak** [comment]
@famod Thanks for the detailed explanation, I'll try that then.

> @zakkak
> Just to clearly state this (but maybe I am just too confused by this change): This has no effect whatsoever.
> The custom `configuration` element (= plugin parameter) `native.surefire.skip` is nothing that `maven-surefire-plugin` is aware of and therefore it is simply ignored.
> 
> See `test` goal parameter reference: https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html
> 

Note that surefire is already (by #10791) made aware of this in the integration-tests/*/pom.xml files, e.g. https://github.com/quarkusio/quarkus/blob/05a0ec5580dc26bf96b680db004a79dc94b211a2/integration-tests/amazon-lambda-http/pom.xml#L90-L92

**Comment by gsmet** [comment]
@zakkak the problem is that it also requires other people attention such as Alexey's and again I don't think it's worth it.

As we mentioned it with Georgios, locally, we want to run the Java tests before the native ones because it's a safe check that avoids waiting for 5 minutes if there's an obvious issue.

That lets us with CI and IMHO the benefit is not really worth it.

**Comment by zakkak** [comment]
> As we mentioned it with Georgios, locally, we want to run the Java tests before the native ones because it's a safe check that avoids waiting for 5 minutes if there's an obvious issue.

FWIW this is still the case since this is an opt-in "feature" where one needs to use `-Dnative.surefire.skip` to skip the tests.

**Comment by zakkak** [comment]
Following @aloubyansky 's [comment](https://github.com/quarkusio/quarkus/pull/10932#issuecomment-662970045) I have moved the corresponding `<plugin>` segment to the parent pom and it works as expected.

If we want to follow the same approach for other parts of the native-image profile (like @famod [suggests](https://github.com/quarkusio/quarkus/pull/10932#issuecomment-663093106)) please let me know and I will open another PR, since it's unrelated to `native.surefire.skip`.

**Comment by zakkak** [comment]
Regarding `<pluginManagement>`, if I understand correctly [it's not possible to define it in a profile](https://maven.apache.org/guides/introduction/introduction-to-profiles.html#profiles-in-poms) so I used `<plugins>` which did the trick.
Please let me know if this is wrong in any way.

**Comment by aloubyansky** [comment]
> Regarding `<pluginManagement>`, if I understand correctly [it's not possible to define it in a profile](https://maven.apache.org/guides/introduction/introduction-to-profiles.html#profiles-in-poms) so I used `<plugins>` which did the trick.
> Please let me know if this is wrong in any way.

Would you mind trying it nevertheless?

This is definitely looking cleaner. Potential issue with this config is that there are projects that are not supposed to contain the native profile, which could lead issues running all the ITs with -Dnative (which I believe we don't do). In that case we could:
1. merge the change anyway;
2. not merge and require config per native test
3. break the integration-tests into (submodules) those that should be tested in native and others.

3 could make sense. Originally this module contained only extension IT for which native profile makes sense. But slowly we realized needed IT for non-extensions and ended up moving Maven, Gradle, devmode, etc in there.

**Comment by zakkak** [comment]
> Would you mind trying it nevertheless?

I tried it and it works, I force pushed the change including it.

> This is definitely looking cleaner. Potential issue with this config is that there are projects that are not supposed to contain the native profile, which could lead issues running all the ITs with -Dnative (which I believe we don't do).

At the moment this would only affect the `native.surefire.skip` property which I think is OK.

> In that case we could:
> 
>     1. merge the change anyway;
> 
>     2. not merge and require config per native test
> 
>     3. break the integration-tests into (submodules) those that should be tested in native and others.
> 
> 
> 3 could make sense. Originally this module contained only extension IT for which native profile makes sense. But slowly we realized needed IT for non-extensions and ended up moving Maven, Gradle, devmode, etc in there.

3 makes sense indeed and might be handy in combination with https://github.com/quarkusio/quarkus/pull/10763 to better group tests in CI.

**Comment by quarkus-lab** [comment]
> > Would you mind trying it nevertheless?
> 
> I tried it and it works, I force pushed the change including it.

Yes, I think I tried it at some point and it did work which is why I asked you to confirm.

> > This is definitely looking cleaner. Potential issue with this config is that there are projects that are not supposed to contain the native profile, which could lead issues running all the ITs with -Dnative (which I believe we don't do).
> 
> At the moment this would only affect the `native.surefire.skip` property which I think is OK.

Agreed.

> > In that case we could:
> > ```
> > 1. merge the change anyway;
> > 
> > 2. not merge and require config per native test
> > 
> > 3. break the integration-tests into (submodules) those that should be tested in native and others.
> > ```
> > 
> > 3 could make sense. Originally this module contained only extension IT for which native profile makes sense. But slowly we realized needed IT for non-extensions and ended up moving Maven, Gradle, devmode, etc in there.
> 
> 3 makes sense indeed and might be handy in combination with #10763 to better group tests in CI.

Feel free to propose a new module structure.

**Review by ghost — APPROVED** [review]

**Comment by quarkus-lab** [comment]
I approved it, assuming it works :)

**Comment by aloubyansky** [comment]
Sorry, quarkus-lab was me :) Forgot to sign out of that one.

**Review by aloubyansky — APPROVED** [review]

**Comment by zakkak** [comment]
Thanks for all the help @aloubyansky !

> Feel free to propose a new module structure.

I am afraid I am not qualified for this, I don't know what each test does and what parts of quarkus it tests to make meaningful groups. Instead I will start a discussion on quarkus-dev to see if it's more obvious for someone else :).

**Comment by aloubyansky** [comment]
@zakkak could you please rebase it. Let's merge it.

**Comment by zakkak** [comment]
@aloubyansky done (there were some conflicts, so please make sure to review once more)

**Comment by aloubyansky** [comment]
@gsmet it's in your hands

**Comment by zakkak** [comment]
@gsmet are there any standing issues with this PR?

**Comment by zakkak** [comment]
@gsmet this one got away, should I rebase it to get it merged?

**Comment by aloubyansky** [comment]
@gsmet is on PTO this week. Good question though.

**Comment by zakkak** [comment]
@gsmet this is a kind reminder

**Comment by gastaldi** [comment]
@zakkak go ahead and rebase it so we can merge it

**Comment by zakkak** [comment]
@gastaldi this is now rebased :)

**Comment by gastaldi** [comment]
@zakkak weird, I still see conflicts in the PR. Are you sure you have rebased on the latest master?

**Comment by zakkak** [comment]
> @zakkak weird, I still see conflicts in the PR. Are you sure you have rebased on the latest master?

Sorry for that, it looks like I only fetched and never pulled `master` :/

Should be OK now

**Comment by zakkak** [comment]
@gastaldi this is a kind reminder

**Review by gastaldi — APPROVED** [review]
@zakkak sorry, that fell through the cracks. It looks good to me

**Comment by gastaldi** [comment]
@gsmet I'll let you push the Merge button once your concerns are addressed

**Comment by zakkak** [comment]
Hello, should I proceed with rebasing?

**Comment by famod** [comment]
I must have forgotten about this! I'm in the process of unifying the `native` profile #14501 which definitely clashes with this one...

**Comment by zakkak** [comment]
> I must have forgotten about this! I'm in the process of unifying the `native` profile in #14501 which definitely clashes with this one...

Nice, I am closing this one in favour of #14501 then :)

**Pull request closed without merging**
