### PR TITLE
Update filename of security policy content

### PR DESCRIPTION
**Pull request by rolfedh**
References issue: https://github.com/quarkusio/quarkusio.github.io/issues/1664

Also see pull-request: https://github.com/quarkusio/quarkusio.github.io/pull/1665

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @rolfedh I wonder though should we also change the title of that document from `Security` to `Security Policy` and the link from `/security` to `security-policy` ?
@gsmet Guillaume, would you agree ?

**Comment by rolfedh** [comment]
I've made an omission. 
The canonical file for this content is in a different repo: https://github.com/quarkusio/quarkusio.github.io/blob/develop/security.adoc
I'll create a separate PR to make a parallel set of changes there, too.

**Comment by sberyozkin** [comment]
@gsmet Right now, if I search for `Quarkus Security` the 1st and 5th hits will offer what looks like the same information, while in fact the 5th hit points to Quarkus Security Policy which is why I've asked the Doc team to help with making it clearer

**Comment by rolfedh** [comment]
> the title of that document from `Security` to `Security Policy`

In this PR (`quarkusio`), the title was already "Security policy" before I renamed the file. 
In [the other PR](https://github.com/quarkusio/quarkusio.github.io/pull/1663/files) for `quarkusio.github.io`, I updated the title to "Security policy".

**Comment by rolfedh** [comment]
> @gsmet Right now, if I search for `Quarkus Security` the 1st and 5th hits will offer what looks like the same information, while in fact the 5th hit points to Quarkus Security Policy which is why I've asked the Doc team to help with making it clearer

After these two PRs are merged and Google re-indexes the site, I believe search results will change as follows:
- The  "Quarkus Security overview" link (#1) will remain unchanged.
- The "Security - Quarkus"  link (#5) will change to "Security policy - Quarkus" (Google appends "Quarkus" when it is omitted from the title.)

**Comment by sberyozkin** [comment]
@rolfedh 

>The "Security - Quarkus" link (SERP 5) will change to "Security policy - Quarkus" (Google appends "- Quarkus" when it is omitted from the title.)

Sounds good, it will become clearer IMHO, let me approve, but I'd like Guillaume to double check

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@rolfedh So, just to confirm, does the link which can be found in https://github.com/quarkusio/quarkus/issues/new/choose will work after the file is renamed ?

**Comment by sberyozkin** [comment]
@rolfedh Thanks, Guillaume, @gsmet, can you help with finalizing this PR please, are you OK with the proposed flow - we merge this PR and then delete `security.md` once the link from the issue template to the sec policy is updated ? Or it can be done right now ? I can't find where is it controlled

**Comment by rolfedh** [comment]
> I can't find where is it controlled

I'm guessing it might be a description field in GitHub the issue templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by rolfedh** [comment]
> Or it can be done right now ?
@sberyozkin @gsmet 
In any case, this PR must be merged before you can update the link to point to `SECURITY-POLICY.md`

**Review by gsmet — CHANGES_REQUESTED** [review]
That's not something we can tweak. See https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository .

The `SECURITY.md` file needs to stay and let's not duplicate it.

**Comment by rolfedh** [comment]
> Thanks @gsmet, @rolfedh What do you think though about updating not the file name itself but the title of the page, from `Security` to `Security Policy` or is [quarkusio/quarkusio.github.io#1665](https://github.com/quarkusio/quarkusio.github.io/pull/1665) enough ?

The `SECURITY.md` in this repo has is "Security policy" as its title.
 [quarkusio/quarkusio.github.io#1665](https://github.com/quarkusio/quarkusio.github.io/pull/1665) makes the following improvements:
- Updates the filename and URL path from `security.adoc` (`/security`) to `security-policy.adoc` (`/security-policy`).
- Updates the title of that content from "Security" to "Security policy".
- Updates a link to point to the new URL.

**Pull request closed without merging**
