### PR TITLE
Removed Old Dev UI: Arc

### PR DESCRIPTION
**Pull request by phillip-kruger**
Removing the old Dev UI from Arc extension

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Seems like this needs to be the last extension being removed. I'll keep it draft for now, until I can rebase on a branch where all other extensions has been cleaned

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
CI is not happy :)

**Comment by phillip-kruger** [comment]
Yeah this one needs more work

**Comment by geoand** [comment]
👌🏼

**Comment by cescoffier** [comment]
I'm a bit worried about the CI failures.

**Comment by phillip-kruger** [comment]
@cescoffier I know what is going on, will fix soon

**Comment by mkouba** [comment]
Shouldn't we add a replacement of the `DevConsoleArcSmokeTest` for the new dev UI? Or we do we have some other tests somewhere else?

**Comment by phillip-kruger** [comment]
@mkouba the tests is already copied to new set of tests. For Arc see https://github.com/quarkusio/quarkus/blob/main/integration-tests/devmode/src/test/java/io/quarkus/test/devui/DevUIArcJsonRPCTest.java and https://github.com/quarkusio/quarkus/blob/main/integration-tests/devmode/src/test/java/io/quarkus/test/devui/DevUIArcBuildTimeDataTest.java

I'll fix this PR soon. I need to remove some other things in vertx-http before I can finalize this PR

**Pull request merged**
