### PR TITLE
Ignore oracle test

### PR DESCRIPTION
**Pull request by brunobat**

### CODE REVIEW

**Review by yrodiere — COMMENTED** [review]
Makes sense but you might want to add a link to relevant information + create an issue to eventually revert this.

**Comment by michalvavrik** [comment]
Hey, did you report this here https://github.com/gvenzl/oci-oracle-xe/issues, can you link exact upstream issue or provide any context on what "buggy" means? I read but this PR and https://github.com/quarkusio/quarkus/issues/36141 and thre is really no context on what it means. Maybe the issue you opened could provide error message etc. I am also experiencing issues with Oracle and I'd expect this is much larger problem than failing OpenTelemetry JDBC instrumentation tests. Are you planning to open upstream issue, please?

**Comment by michalvavrik** [comment]
@brunobat I just read the issue you opened, we have same problem, "good". Thanks for opening it.

**Review by geoand — APPROVED** [review]

**Comment by brunobat** [comment]
Moving to a real computer with linux.

**Comment by brunobat** [comment]
Removed the tests, will bring them back once the image is fixed

**Pull request merged**
