### PR TITLE
Fix generateJniConfig step

### PR DESCRIPTION
**Pull request by scrocquesel**
Follow up https://github.com/quarkusio/quarkus/pull/32432

When defining both methods and ctors, ctors are discarded. This will merge both.

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM!

We need the same change applied to https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java as well.

@scrocquesel could you please include the change in this PR? If not I will prepare a follow up.

**Comment by jerboaa** [comment]
This is probably one for @Karm to review. I'm not super familiar with this json generation logic.

**Comment by Karm** [comment]
Re-running the check.

And I'll compare the produced json files...

**Comment by Karm** [comment]
```
2023-04-24T14:47:03.7662261Z   JAVA_HOME: C:\hostedtoolcache\windows\mandrel-java17-windows\22.3.2-0-Final\x64\mandrel-java17-22.3.2.0-Final
```
Looks right now. But the flow doesn't do anything when manually restarted as I did...

**Comment by scrocquesel** [comment]
> LGTM!
> 
> We need the same change applied to https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java as well.
> 
> @scrocquesel could you please include the change in this PR? If not I will prepare a follow up.

Done

**Review by zakkak — APPROVED** [review]
LGTM, thanks @scrocquesel !

**Comment by zakkak** [comment]
@Karm the version-related failure was due to [21.3.6.0.Final](https://github.com/graalvm/mandrel/releases/tag/mandrel-21.3.6.0-Final) appearing as `latest` in https://github.com/graalvm/mandrel/releases/latest, before the release of 22.3.2.0.Final, which is what https://github.com/graalvm/setup-graalvm/ uses to get the latest mandrel version when invoked in:

https://github.com/quarkusio/quarkus/blob/585ebb263534251f2985580d5d7ed8299bbd63f3/.github/workflows/ci-actions-incremental.yml#L696-L704

I think this is good to merge if you have no objection.

**Review by Karm — APPROVED** [review]
I unzipped the jars and compared the json files with/without the change for an AWT app and it seems good. THX :pray:

**Pull request merged**
