### PR TITLE
reenable test.  see if #12557 is still an issue.

### LINKED ISSUE #12557: Fix disabled KotlinGRPCProjectBuildTest
**Describe the bug**
The `KotlinGRPCProjectBuildTest` fails in snapshot-ci job. The test has been disabled.

**Expected behavior**
The test should pass. 

**Actual behavior**
The tests failed only on this job (https://scans.gradle.com/s/4oz72djgqmjoc/tests/:test/io.quarkus.gradle.KotlinGRPCProjectBuildTest/testBasicMultiModuleBuild()#1)

### PR DESCRIPTION
**Pull request by evanchooly**
Closes #12557

### CODE REVIEW

**Comment by machi1990** [comment]
CI issue cause of formatting
```
Caused by: org.apache.maven.plugin.MojoFailureException: Imports are not sorted in /home/runner/work/quarkus/quarkus/integration-tests/gradle/src/test/java/io/quarkus/gradle/KotlinGRPCProjectBuildTest.java
```

**Comment by glefloch** [comment]
This test used to only fail on the snapshot-ci job while being ok on master

**Review by gsmet — CHANGES_REQUESTED** [review]
Yes, please do not merge this until it's properly checked.

**Comment by evanchooly** [comment]
seems to be running ok.  merge it back in?

**Comment by gastaldi** [comment]
Already re-enabled. Closing this PR

**Pull request closed without merging**
