### PR TITLE
Bump OpenTelemetry version from 1.11.0 to 1.12.0

### PR DESCRIPTION
**Pull request by knutwannheden**

### CODE REVIEW

**Comment by knutwannheden** [comment]
Background: I created an OpenTelemetry PR to get the Trace Context serialized as part of the Trace Data in the OTLP Exporter. This was integrated as part of the 1.12.0 release.

**Comment by gsmet** [comment]
There is already a PR here: https://github.com/quarkusio/quarkus/pull/24112 .

See Roberto's comment there about why the PR is pending.

**Comment by gsmet** [comment]
Ah wait, I see you also upgraded the other component. Let me reopen this one.

**Comment by knutwannheden** [comment]
> There is already a PR here: #24112 .
> 
> See Roberto's comment there about why the PR is pending.

I see. I had completely missed that. The `opentelemetry-bom-alpha` was released, but apparently `opentelemetry-instrumentation-bom-alpha` not yet.

**Comment by gastaldi** [comment]
I closed the dependabot PR as this is the correct fix. Now we wait until the missing artifact is published to kick the CI build again 👍🏻

**Comment by radcortez** [comment]
> I see. I had completely missed that. The `opentelemetry-bom-alpha` was released, but apparently `opentelemetry-instrumentation-bom-alpha` not yet.

Yes, they are released independently. The instrumentation one, a few days (or a couple of weeks) after.

**Comment by knutwannheden** [comment]
> Yes, they are released independently. The instrumentation one, a few days (or a couple of weeks) after.

Thanks. That's a shame. FWIW, I tried to use the new 1.12.0 version anyway. It works for some use cases but compatibility issues show up in others. Some changes will most likely be required in Quarkus to support 1.12.0.

**Comment by knutwannheden** [comment]
The OpenTelemetry instrumentation 1.12.0 library has now been released.

**Review by radcortez — APPROVED** [review]

**Pull request merged**
