### PR TITLE
Trim OIDC claim role path

### PR DESCRIPTION
**Pull request by sberyozkin**
Follows #26185.

@gastaldi Sorry, I commented in #26185 that I was also adding a role path trim, but I've found today I forgot to commit

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by sberyozkin** [comment]
Thanks George

**Comment by gsmet** [comment]
I wonder if it wouldn't be better to handle that at the `@ConfigItem` level with `@ConvertWith(TrimmedStringConverter.class)`?

**Comment by gastaldi** [comment]
> I wonder if it wouldn't be better to handle that at the `@ConfigItem` level with `@ConvertWith(TrimmedStringConverter.class)`?

That would be much better, +1

**Comment by sberyozkin** [comment]
Sure

**Comment by sberyozkin** [comment]
@gastaldi @gsmet Hey, it does not work with a List property, after adding `@ConvertWith(TrimmedStringConverter.class)` to
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java#L441 and removing `trim()` from the code I've got the test failing.

I guess it should only be applied to Strings, I can follow up at some point with reviewing the OIDC docs and adding it where possible

**Comment by gastaldi** [comment]
> 

That is weird, maybe that's a bug in the converter? WDYT @radcortez?

**Review by gsmet — APPROVED** [review]
OK, let's get this in as is for now, then. We can revisit later.

**Comment by sberyozkin** [comment]
Sure

**Pull request merged**
