### PR TITLE
Scheduler - fix Trigger#isOverdue() for simple cron trigger

### PR DESCRIPTION
**Pull request by mkouba**
- add cron trigger tests

### CODE REVIEW

**Comment by mkouba** [comment]
@rmanibus pls review ;-)

**Comment by mkouba** [comment]
Actually, I'm not so sure about the _"This method returns false if the last execution has been skipped."_ sentence from the `Trigger.isOverdue()` javadoc...

**Comment by mkouba** [comment]
> Actually, I'm not so sure about the _"This method returns false if the last execution has been skipped."_ sentence from the `Trigger.isOverdue()` javadoc...

@rmanibus I mean that I don't see how a skipped execution affects the result of `Trigger#isOverdue()` (at least for simple scheduler). But maybe I'm missing something...

**Comment by rmanibus** [comment]
> @rmanibus pls review ;-)

What was the issue there ?

**Comment by mkouba** [comment]
> > @rmanibus pls review ;-)
> 
> What was the issue there ?

https://github.com/quarkusio/quarkus/pull/25195/files#diff-4ac093a76f90f16863570dcf8bfcc0b9c1bbff82cf754b718a78c9fcfa9d40a9L484

When I copied the `OverdueExecutionTest` test for cron it did not pass because obviously this never returns `true` (unless no next execution is returned).

**Comment by rmanibus** [comment]
> > > @rmanibus pls review ;-)
> > 
> > 
> > What was the issue there ?
> 
> https://github.com/quarkusio/quarkus/pull/25195/files#diff-4ac093a76f90f16863570dcf8bfcc0b9c1bbff82cf754b718a78c9fcfa9d40a9L484
> 
> When I copied the `OverdueExecutionTest` test for cron it did not pass because obviously this never returns `true` (unless no next execution is returned).

How yes nextFireTime is always after now. in fact, I used a part of the method getNextFireTime().
It make me think about something: in case the trigger is overdue, shouldn't the getNextFireTime() return something in the past ?

**Comment by mkouba** [comment]
> It make me think about something: in case the trigger has not been fired (and is overdue), shouldn't the getNextFireTime() return something in the past ?
> Also getPreviousFireTime assume that the last execution has fired. Both methods return theoretical values deducted from the cron timeline, not from the real last execution !

Yes, the `getPreviousFireTime()` method should probably return `lastFireTime` instead. And the `getNextFireTime()` should return `executionTime.nextExecution(lastFireTime)`...

**Comment by rmanibus** [comment]
@mkouba I met your french colleagues at DevoxxFr, now I have enough tshirt for the rest of my life.
I was hopping to see you there too !

**Comment by mkouba** [comment]
> @mkouba for your question about skipped execution, the trigger is evaluated before being skipped so the concurrent skip has no effect on the isOverdue method result. By skipped I was meaning not being fired on time in the documentation.

Hm, I was more thinking about the `Scheduled#skipExecutionIf()` and `SkippedExecution`. In any case, the sentence _"This method returns `false` if the last execution has been skipped."_ does not make any sense to me.

**Comment by rmanibus** [comment]
> > @mkouba for your question about skipped execution, the trigger is evaluated before being skipped so the concurrent skip has no effect on the isOverdue method result. By skipped I was meaning not being fired on time in the documentation.
> 
> Hm, I was more thinking about the `Scheduled#skipExecutionIf()` and `SkippedExecution`. In any case, the sentence _"This method returns `false` if the last execution has been skipped."_ does not make any sense to me.

do you want me to rephrase it ? in an independent PR ?

**Comment by mkouba** [comment]
> do you want me to rephrase it ? in an independent PR ?

Yes pls, that would be great..

**Comment by rmanibus** [comment]
> > do you want me to rephrase it ? in an independent PR ?
> 
> Yes pls, that would be great..

Alright, I will do this this afternoon !

**Comment by rmanibus** [comment]
@mkouba I'm had another thought about the is overdue method. Seeing your modification, I think that what we have for the quartz schedule
```
        @Override
        public boolean isOverdue() {
            Instant nextFireTime = getNextFireTime();
            if (nextFireTime == null) {
                return false;
            }
            return LocalDateTime.ofInstant(nextFireTime, ZoneId.systemDefault()).plus(gracePeriod)
                    .isBefore(LocalDateTime.now());
        }

```
can be the default implementation. 

It is basically what we are doing in every other place but without calling getNextFireTime to avoid the instant conversion.

**Review by machi1990 — APPROVED** [review]

**Comment by mkouba** [comment]
> @mkouba I had another thought about the is overdue method. Seeing your modification, I think that what we have for the quartz schedule
> 
> ```java
>         @Override
>         public boolean isOverdue() {
>             Instant nextFireTime = getNextFireTime();
>             if (nextFireTime == null) {
>                 return false;
>             }
>             return LocalDateTime.ofInstant(nextFireTime, ZoneId.systemDefault()).plus(gracePeriod)
>                     .isBefore(LocalDateTime.now());
>         }
> ```
> 
> can be the default implementation.
> 
> It is basically what we are doing in every other place but without calling getNextFireTime to avoid the instant conversion. I can make I PR for that too

I don't think we can use the `getNextFireTime()` for `SimpleScheduler.CronTrigger`...

**Comment by rmanibus** [comment]
> > > do you want me to rephrase it ? in an independent PR ?
> > 
> > 
> > Yes pls, that would be great..
> 
> Alright, I will do it this afternoon !

this is done in #25223

**Pull request merged**
