### PR TITLE
Record config properties in multiple phases

### PR DESCRIPTION
**Pull request by turing85**
(cherry picked from commit b1ecd0b065bdc0f783b55581ea872aee38152db3)

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Please don't push backports like this. They need to be handled very carefully, that's why we use the backport labels.

From what I can see of the original issue it used to work with 2.x so I don't see why we would backport this?

**Comment by turing85** [comment]
@gsmet Sorry for that, didn't mean to cause trouble.

To the topic at hand:
I was able to reproduce the bug on `2.13.8.Final` and `2.16.7.Final`
Reproducer `2.13`: https://github.com/turing85/quarkus-camel-jms/tree/bug-2.13
reproducer `2.16`: https://github.com/turing85/quarkus-camel-jms/tree/bug-2.16

To reproduce:
- clone the repository
- build and deploy natively, look at logs:
```bash
./mvnw --define native clean package \
&& docker-compose --file local-deployment/docker-compose.yml up --build --detach\
&& sleep 5 \
&& docker-compose --file local-deployment/docker-compose.yml --profile native-services up --build --detach \
&& sleep 5 \
&& docker logs sender
```
- observe the error:
```
2023-07-03T21:49:57+02:00 ERROR: Failed to start application (with profile prod)
2023-07-03T21:49:57+02:00 java.lang.IllegalStateException: Configuration <default>: url is not set and devservices is activated. This is a bug. Please report it.
2023-07-03T21:49:57+02:00 	at io.quarkus.artemis.core.runtime.ArtemisUtil.validateIntegrity(ArtemisUtil.java:30)
2023-07-03T21:49:57+02:00 	at io.quarkus.artemis.jms.runtime.ArtemisJmsRecorder.getConnectionFactoryProducer(ArtemisJmsRecorder.java:33)
2023-07-03T21:49:57+02:00 	at io.quarkus.deployment.steps.ArtemisJmsProcessor$configure1492597324.deploy_0(Unknown Source)
2023-07-03T21:49:57+02:00 	at io.quarkus.deployment.steps.ArtemisJmsProcessor$configure1492597324.deploy(Unknown Source)
2023-07-03T21:49:57+02:00 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-07-03T21:49:57+02:00 	at io.quarkus.runtime.Application.start(Application.java:101)
2023-07-03T21:49:57+02:00 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
2023-07-03T21:49:57+02:00 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
2023-07-03T21:49:57+02:00 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
2023-07-03T21:49:57+02:00 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:123)
2023-07-03T21:49:57+02:00 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```
- stop deployment:
```bash
  docker-compose --file local-deployment/docker-compose.yml --profile native-services down
```
- un-comment the commented-out `%prod` configurations in both `application.yml`s
- repeat the above steps
- observe that no error occurs

I was not able to reproduce the issue with `3.1.3.Final`. This all suggests that the same issue also exists on `2.13` and `2.16`.

@radcortez do you see any issues in downstreaming this change to ` 2.13` and `2.16`?

**Comment by radcortez** [comment]
Yes, the original PR https://github.com/quarkusio/quarkus/pull/30620 was merged for 3.0.0.Alpha4. There was never a request to backport it to 2.x.

From a code perspective, I believe it should be fine to backport it, but the final word is from @gsmet, since there is no point in backporting without a release :)

**Comment by turing85** [comment]
Given the fact that some people might be stuck on `2.x` for a while (e.g. because there is no camel-4 release yet), I think a backport + release would be great :slightly_smiling_face:

**Comment by geoand** [comment]
Closing this as we don't handle backports with dedicated PRs (except for a few exceptions)

**Comment by gsmet** [comment]
@radcortez are you sure this particular change didn't cause any regressions? We can backport it but the change is sufficiently cryptic that we need to make sure it didn't introduce regressions that were fixed later.

**Comment by radcortez** [comment]
Right, we had to push this one after: https://github.com/quarkusio/quarkus/pull/30709, so it would require both. I believe that should be enough after looking into the entire history, but I understand there is a bit of a risk involved.

To be totally fair, this fix is not a bug fix, but an enhancement. This is caused by a shadowing build time and runtime configuration (which we always recommended not to do), and the use of a second level of indirection with property expressions.

@turing85 can't you use the real property names as environment variables as a workaround?

**Comment by turing85** [comment]
@radcortez This is the old discussion :slightly_smiling_face: We don't have properties that **must** be set at compile-time. So from a usability-standpoint, the current solution is the most user-friendly approach. We could work around this by making some `enabled`-flag required, but I'd like to avoid this if possible.

**Comment by radcortez** [comment]
I understand. The issue here is that we need to weigh the risk of backport vs using another way to accomplish the same thing.

In theory, the 2 PRs I've mentioned should be enough, but if they break something else, due to the big diverge between 2 and 3, it can become troublesome to resolve.

**Comment by radcortez** [comment]
Backports are marked with a label:

https://github.com/quarkusio/quarkus/issues?q=is%3Apr+label%3Atriage%2Fbackport-2.13%3F
https://github.com/quarkusio/quarkus/issues?q=is%3Apr+label%3Atriage%2Fbackport-2.16%3F

I don't believe this has been backported.

**Comment by turing85** [comment]
Okay. Gonna keep the ticket open a little while longer. Please notify me if it should be marked for backport.

**Pull request closed without merging**
