### PR TITLE
Updated gRPC and protobuf-java versions

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
Tested on gRPC integration tests and quickstarts, in both, JVM and native, modes.

**Comment by gsmet** [comment]
There is a dependency convergence issue unfortunately:
```
Warning:  
Dependency convergence error for com.google.auth:google-auth-library-oauth2-http:0.20.0 paths to dependency are:
+-io.quarkus:quarkus-micrometer:999-SNAPSHOT
  +-io.micrometer:micrometer-registry-stackdriver:1.6.1
    +-com.google.cloud:google-cloud-monitoring:1.100.1
      +-com.google.api:gax:1.56.0
        +-com.google.auth:google-auth-library-oauth2-http:0.20.0
and
+-io.quarkus:quarkus-micrometer:999-SNAPSHOT
  +-io.micrometer:micrometer-registry-stackdriver:1.6.1
    +-com.google.cloud:google-cloud-monitoring:1.100.1
      +-com.google.api:gax-grpc:1.56.0
        +-com.google.auth:google-auth-library-oauth2-http:0.20.0
and
+-io.quarkus:quarkus-micrometer:999-SNAPSHOT
  +-io.micrometer:micrometer-registry-stackdriver:1.6.1
    +-com.google.cloud:google-cloud-monitoring:1.100.1
      +-com.google.api:gax-grpc:1.56.0
        +-io.grpc:grpc-alts:1.34.0
          +-com.google.auth:google-auth-library-oauth2-http:0.22.0

Warning:  
Dependency convergence error for com.google.auth:google-auth-library-credentials:0.20.0 paths to dependency are:
+-io.quarkus:quarkus-micrometer:999-SNAPSHOT
  +-io.micrometer:micrometer-registry-stackdriver:1.6.1
    +-com.google.cloud:google-cloud-monitoring:1.100.1
      +-com.google.api:gax:1.56.0
        +-com.google.auth:google-auth-library-oauth2-http:0.20.0
          +-com.google.auth:google-auth-library-credentials:0.20.0
and
+-io.quarkus:quarkus-micrometer:999-SNAPSHOT
  +-io.micrometer:micrometer-registry-stackdriver:1.6.1
    +-com.google.cloud:google-cloud-monitoring:1.100.1
      +-com.google.api:gax-grpc:1.56.0
        +-io.grpc:grpc-auth:1.34.0
          +-com.google.auth:google-auth-library-credentials:0.22.0
and
+-io.quarkus:quarkus-micrometer:999-SNAPSHOT
  +-io.micrometer:micrometer-registry-stackdriver:1.6.1
    +-com.google.cloud:google-cloud-monitoring:1.100.1
      +-com.google.api:gax-grpc:1.56.0
        +-com.google.auth:google-auth-library-credentials:0.20.0

Warning:  Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

That is a bit unfortunate because we will have to enforce the version of a very low level library because of an optional dependency (the stackdriver one). I don't see any other option though :/

/cc @ebullient

**Comment by ebullient** [comment]
Yea -- this is one of the things I've been thinking about how to tackle (as I have to go through this again re: native libs).  I can try ignoring more (beyond what is required for the cloud monitoring library.. ). Will pull this up and see what's what.

**Review by ebullient — APPROVED** [review]
LGTM

**Comment by michalszynkiewicz** [comment]
@gsmet the Windows JVM tests failed, looks like they're stuck on mongodb. Should I retrigger the checks?

**Pull request merged**
