### PR TITLE
Upgrade to Hibernate ORM 6.5.1 and configure Hibernate ORM/Reactive with database product names instead of dialect names for core dialects

### LINKED ISSUE #37575: Warning during build: [org.hib.orm.deprecation] HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect'
### Describe the bug

I got this during a native build, but I guess this might also happen for JVM builds.

Quarkus does set the dialect explicitly, but it seems Hibernate ORM doesn't like that anymore for some reason.
We should investigate.

Note I remember that back when we migrated to Hibernate ORM 6.0, we had tried to set ["jakarta.persistence.database-product-name"](https://docs.jboss.org/hibernate/orm/6.4/javadocs/org/hibernate/cfg/JdbcSettings.html#JAKARTA_HBM2DDL_DB_NAME) for this purpose (and I guess that's what Hibernate ORM would like us to do), but I had to roll that back and set the dialect explicitly instead. I don't remember why exactly.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Mainly to avoid Hibernate ORM logging warnings on startup.

Fixes #37575 

~~Opening as draft, because this won't work until https://hibernate.atlassian.net/browse/HHH-18079 gets fixed.~~ => Done

... and actually we'll need https://hibernate.atlassian.net/browse/HHH-18112 to get rid of some more warnings on PostgreSQL.

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Comment by yrodiere** [comment]
The remaining failures are not (exactly) related; we'll need #40652 to get merged first.

**Comment by yrodiere** [comment]
> The remaining failures are not (exactly) related; we'll need #40652 to get merged first.

Done. I rebased on `main`. Let's wait for CI :crossed_fingers:

**Comment by Sanne** [comment]
It appears that the failing test in ` integration-tests/reactive-messaging-kafka ` is new or at least not flaky.. however that module doesn't seem to depend on Hibernate ORM.

What do we do? I'll try it locally, but later as I can't work now.

In the meantime, I'll have it run again :/

**Comment by yrodiere** [comment]
> It appears that the failing test in `integration-tests/reactive-messaging-kafka` is new or at least not flaky.. however that module doesn't seem to depend on Hibernate ORM.
> 
> What do we do? I'll try it locally, but later as I can't work now.
> 
> In the meantime, I'll have it run again :/

Thanks @Sanne , this did the trick: tests pass, so this was probably just a flake. Which seems confirmed by the fact it was [a timeout](https://ge.quarkus.io/s/oq6lqgfvwy3x4/tests/goal/io.quarkus:quarkus-integration-test-reactive-messaging-kafka:surefire:test@default-test/details/io.quarkus.it.kafka.KafkaConnectorTest/testRequestReply?expanded-stacktrace=WyIwIl0&top-execution=1).

I have approvals and passing tests, so I'll merge! Thank you all.

I'll reignite the discussion on Zulip to see if we should backport this (+ the impending upgrade to ORM 6.5.2) to branch 3.11.

**Comment by Sanne** [comment]
Awesome! great job

**Comment by gsmet** [comment]
@ozangunalp could you have a look at the flaky test `ConnectorChangeTest.testUpdatingConnector` above?

**Comment by Sanne** [comment]
I confirm `ConnectorChangeTest.testUpdatingConnector` fails locally as well - not consistently but very often

**Pull request merged**
