### PR TITLE
Fix local proxy handling in REST Client module

### PR DESCRIPTION
**Pull request by geoand**
With the previous implementation, Cloudfare was
blocking requests coming from the local proxy

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by fedinskiy** [comment]
@geoand from the practical standpoint, this change means, that from now on there is `x-forwarded-host` header in the requests, which were sent by client through the proxy, is that correct?

**Comment by geoand** [comment]
@fedinskiy not exactly. It calls `setAuthority` on Vert.x `io.vertx.httpproxy.ProxyRequest` which does the folloing:

```
  /**
   * Set the request authority
   *
   * <ul>
   *   <li>for HTTP/1 the {@literal Host} header</li>
   *   <li>for HTTP/2 the {@literal :authority} pseudo header</li>
   * </ul>
   */
```

**Comment by fedinskiy** [comment]
@geoand how does this affect the requests? Are there new headers (which ones), or old headers are changed (how)?

**Comment by geoand** [comment]
The request that is sent to the proxy now has the proper `Host` header set.

**Comment by fedinskiy** [comment]
@geoand could you elaborate? The only difference I see now in headers is in added ` x-forwarded-host`. Should there be something else?

Headers:
```
3.19.2 with proxy:
[clientFilter: [clientFilterInvoked], x-forwarded-host: [localhost:46207], host: [localhost:1101], REQUEST_ID: [0], Accept: [application/json], User-Agent: [Quarkus REST Client]]
3.19.2 No proxy
[Connection: [Keep-Alive], Accept-Encoding: [gzip,deflate], Accept: [*/*], User-Agent: [Apache-HttpClient/4.5.14 (Java/21.0.5)], Host: [localhost:1101]]

3.17.4 with proxy
[User-Agent: [Quarkus REST Client], Accept: [application/json], REQUEST_ID: [0], host: [localhost:40609], clientFilter: [clientFilterInvoked]]
3.17.4 No proxy
[Accept: [*/*], Accept-Encoding: [gzip,deflate], Host: [localhost:1101], Connection: [Keep-Alive], User-Agent: [Apache-HttpClient/4.5.14 (Java/21.0.5)]]
```

**Comment by geoand** [comment]
If that's what you seem that's the difference :)

**Pull request merged**
