### PR TITLE
Improve test coverage for container-image group handling

### PR DESCRIPTION
**Pull request by rsvoboda**
container-image tests to ensure spaces removal from EffectiveGroup and resolved image name for various inputs

Test development initially intended for https://github.com/quarkusio/quarkus/pull/13651

Additional coverage introduced in ContainerImageInfoTest to test build time procedure related to image name resolution, most of the work done by @Sgitario (kudos!), I did the finalization work + ported it to Quarkus repo as Jose is on PTO.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Really nice, thanks!

Let's just improve the title a little - it's a little too long :)

**Comment by rsvoboda** [comment]
@geoand any tips for shorter title?

**Comment by geoand** [comment]
I would just go with: `Improve test coverage for container-image group handling`.

Then the description can have all the details you like.

**Comment by geoand** [comment]
The new tests seems to be failing:

```
2021-01-06T12:18:20.4569033Z [INFO] Running io.quarkus.container.image.deployment.ContainerImageConfigEffectiveGroupTest
2021-01-06T12:18:20.4578867Z [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in io.quarkus.container.image.deployment.ContainerImageConfigEffectiveGroupTest
2021-01-06T12:18:20.4583331Z [INFO] 
2021-01-06T12:18:20.4584855Z [INFO] Results:
2021-01-06T12:18:20.4585225Z [INFO] 
2021-01-06T12:18:20.4586716Z [ERROR] Failures: 
2021-01-06T12:18:20.4593527Z [ERROR]   ContainerImageInfoTest.shouldFailWhenSpacesInGroupProperty:83 Expected java.lang.IllegalArgumentException to be thrown from ContainerImageProcessor.publishImageInfo ==> Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <java.lang.NoClassDefFoundError>
2021-01-06T12:18:20.4601183Z [ERROR] Errors: 
2021-01-06T12:18:20.4613029Z [ERROR]   ContainerImageInfoTest.shouldReplaceSpacesInUserName:75->whenPublishImageInfo:110 » ExceptionInInitializer
2021-01-06T12:18:20.4621556Z [ERROR]   ContainerImageInfoTest.shouldUseAppNameAndVersionWhenNoUserName:61->whenPublishImageInfo:110 » NoClassDefFound
2021-01-06T12:18:20.4629729Z [ERROR]   ContainerImageInfoTest.shouldUseUserAppNameAndVersionWhenUserName:68->whenPublishImageInfo:110 » NoClassDefFound
2021-01-06T12:18:20.4633908Z [INFO] 
2021-01-06T12:18:20.4635096Z [ERROR] Tests run: 8, Failures: 1, Errors: 3, Skipped: 0
```

on the Java 8 job

**Comment by rsvoboda** [comment]
I have seen that, waiting for the rest of jobs to finish, `java.lang.NoClassDefFoundError` is really weird error, I was running these tests locally without issues.

**Comment by rsvoboda** [comment]
OK, so I installed JDK 8 on my machine and I can see the error too, not present with JDK11. 

We should really ditch JDK8 :-D

**Comment by geoand** [comment]
That should be our New Year's resolution :)

**Comment by rsvoboda** [comment]
JDK8 didn't like `System.getProperties().clear();`, replaced by removing 2 properties.

Tried on JDK 8 / 11 / 15.

**Comment by geoand** [comment]
> JDK8 didn't like `System.getProperties().clear();`, replaced by removing 2 properties.

Interesting to know!

**Pull request merged**
