### PR TITLE
Set analytics filter logs to debug

### LINKED ISSUE #34703: Ignored projects also ask about build analytics
When playing with an app that is ignored by build analytics for the first time, typically playing with a quickstart, we are asking the user if they want to enable build analytics. 

If they say yes, we display a message saying build analytics will be ignored. 

So first I thing we shouldn’t ask the user about build analytics when they’re playing with an ignored project: we don’t want to bother a user exploring Quarkus for the first time with this. Especially when we are not actually collecting data. 

Secondly, I think we shouldn’t log anything when build analytics is ignored for a project. The user really doesn’t care about it. And when I say that, I mean in all cases: even if he has enabled build analytics, telling the user this particular project won’t send any build time analytics has very little value and can be confusing. 

/cc @brunobat @maxandersen

### PR DESCRIPTION
**Pull request by brunobat**
fixes #34703

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by cescoffier** [comment]
@gsmet That's for @ozangunalp

**Comment by brunobat** [comment]
Yes @gsmet, I created this one in the morning: https://github.com/quarkusio/quarkus/pull/35077
Please let me know if it continues to happen.

**Comment by ozangunalp** [comment]
I figure that io.quarkus.it.vthreads.jms.VirtualThreadTest is flaky, I'll disable it.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@brunobat perfect, thanks!

**Pull request merged**
