### PR TITLE
Register missing Jaeger classes for reflection

### LINKED ISSUE #10402: RemoteControlledSampler fails with "No strategy present in response. Not updating sampler." in native mode
**Describe the bug**

When using Jaeger tracing by adding: `io.quarkus:quarkus-jaeger`, tracing seems to work, but a periodic error message is in the log, when using native mode.

I assume that updating the strategy is broken as well.

**Expected behavior**

Same as JVM mode: No error message. Update works.

**Actual behavior**

~~~
2020-07-01T11:31:05.711Z ERROR [RemoteControlledSampler] No strategy present in response. Not updating sampler.
~~~

**To Reproduce**
1. Enable tracing
2. Check the logs
3. 

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

### PR DESCRIPTION
**Pull request by sophokles73**
Fixes: #10402

Signed-off-by: Kai Hudalla <sophokles.kh@gmail.com>

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by sophokles73** [comment]
would be nice if this would find its way into 2.7.x :-)

**Comment by geoand** [comment]
That's the point of the `triage/backport` label 😉

**Comment by sophokles73** [comment]
got it, thanks for the explanation :+1:

**Comment by geoand** [comment]
NP!

**Pull request merged**
