### PR TITLE
Introduce BOM and build-parent poms

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #275

`build-parent` pom - this one is needed because otherwise our BOM pom could not inherit from `shamrock-parent`. A similar strategy is used in [Thorntail](https://github.com/thorntail/thorntail/tree/master/build-parent).

Usage:
```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>shamrock-bom</artifactId>
        <version>${shamrock.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  
  <dependencies>
    <dependency>
      <groupId>org.jboss.shamrock</groupId>
      <artifactId>shamrock-jaxrs-deployment</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jboss.shamrock</groupId>
      <artifactId>shamrock-arc-deployment</artifactId>
    </dependency>   
   </dependencies>  
```

### CODE REVIEW

**Review by gsmet — COMMENTED** [review]
Looks mostly good to me.

Added a couple of minor comments/questions inline.

**Review by gsmet — APPROVED** [review]
Looks good to me, now.

**Review by dmlloyd — APPROVED** [review]
Other than my one comment I generally agree with the change.

**Review by cescoffier — APPROVED** [review]
@mkouba I'm ok with the BOM, but we may have to revisit the scope of the `-deployment`. Typically, I'm pretty sure for Vert.x you want the `compile` scope (or you don't get Vert.x on the classpath). 

It's something we can change once we have more experience.

**Pull request merged**
