### PR TITLE
[3.9] Allow to inject JAX-RS ResourceInfo into custom HTTP Security Policy

### PR DESCRIPTION
**Pull request by michalvavrik**
backports #39920

### CODE REVIEW

**Comment by michalvavrik** [comment]
Windows tests are failing over unrelated:
```
2024-04-06T02:11:25.2513545Z 2024-04-06 02:11:23,800 ERROR [org.apa.act.art.cor.server] (main) AMQ224104: Error starting the Acceptor artemis {scheme=tcp, tcpReceiveBufferSize=1048576, port=61616, host=0.0.0.0, protocols=CORE,AMQP, tcpSendBufferSize=1048576} [Error Occurred After Shutdown]
2024-04-06T02:11:25.2517398Z 2024-04-06 02:11:23,800 ERROR [org.apa.act.art.cor.server] (main) AMQ224000: Failure in initialisation [Error Occurred After Shutdown]: java.lang.IllegalStateException: AMQ229230: Failed to bind acceptor artemis to 0.0.0.0:61616
```

**Review by sberyozkin — APPROVED** [review]
LGTM but this PR requires a @gsmet's approval too because it is going into the 3.9 branch

**Comment by gsmet** [comment]
Why do you want to backport this? It seems a bit more than a bugfix to me. And it's security related so not sure I feel comfortable pushing it to 3.9.

**Comment by michalvavrik** [comment]
I think your comments / requests are completely reasonable. I simply thought this is a good for security where JAX-RS policies are applied in general. I will leave this PR open for now as it is discussed in other thread. Thanks

**Pull request closed without merging**
