### PR TITLE
#1844: Update to smallrye-jwt 1.1.3

### PR DESCRIPTION
**Pull request by sberyozkin**
I'm creating this PR early, before smallrye-jwt 1.1.3 is out, for the team to have a look how the Quarkus smallrye-jwt code will be affected. @starksm64 FYI

thanks

### CODE REVIEW

**Comment by sberyozkin** [comment]
FYI, the test update is caused by the fact that the TCK test is currently enforcing a different conversion strategy for the unknown claims (it is a TCK fault and it has been challenged) ). I'll revert this test update with a small override to keep Quarkus smallrye-jwt spec compliant

**Comment by sberyozkin** [comment]
@starksm64 This is now ready for the review

**Comment by kenfinnigan** [comment]
@sberyozkin does https://github.com/quarkusio/quarkus-quickstarts/tree/master/using-jwt-rbac work with this change?

**Comment by sberyozkin** [comment]
@kenfinnigan thanks for reminding me about this quickstart project, just built it, 6 tests are green. (may be it would make sense to do a quick starts PR builds as well, a a single Java8 one after all the quarkus builds are finished ?)

**Comment by sberyozkin** [comment]
@kenfinnigan, @starksm64 I'd like to start another round of refactorings on top of smalrye-jwt 1.1.4-SNAPSHOT, so would be good to have this PR merged once all the checks are good :-)

**Comment by starksm64** [comment]
I'm waiting for the CI

**Review by starksm64 — APPROVED** [review]

**Pull request merged**
