### PR TITLE
Bump mssql-jdbc to 12.2.0

### LINKED ISSUE #31261: Bump Microsoft SQL Server JDBC driver to 12.2.0
### Description

MS has created a major release of the MS SQL JDBC driver: https://github.com/microsoft/mssql-jdbc/releases/tag/v12.2.0

This should be included in the Quarkus main.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by sschu**
Fixes #31261

### CODE REVIEW

**Comment by gsmet** [comment]
There are some issues in native:
```
Error: Substitution target for io.quarkus.jdbc.mssql.runtime.graal.com.microsoft.sqlserver.jdbc.QuarkusSqlFedAuthToken is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for io.quarkus.jdbc.mssql.runtime.graal.com.microsoft.sqlserver.jdbc.QuarkusSqlFedAuthToken is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1031)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:364)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:342)
------------------------------------------------------------------------------------------------------------------------
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:966)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

**Comment by gsmet** [comment]
I fixed the problem but I don't have the permission to push to your branch so I will create another PR (keeping your commit).

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/pull/31280

**Comment by sschu** [comment]
@gsmet Thanks a lot! Sorry for missing this, I forgot to run the integration test locally...

**Pull request closed without merging**
