### PR TITLE
Ensure that configured http port is reflected in open browser options

### LINKED ISSUE #21844: Changing http.port breaks pressing 'd' or 'w' in dev mode
### Describe the bug

If an application has changed `quarkus.http.port` to some other value than `8080`, pressing `w` or `d` in dev mode still uses port `8080` in the browser window it opens.

### Expected behavior

If I have `quarkus.http.port=8085` in my `application.properties` I would expect that while in dev mode, pressing `d`would open http://localhost:8085/q/dev/ and pressing `w` would open http://localhost:8085/.

### Actual behavior

If I have `quarkus.http.port=8085` in my `application.properties` while in dev mode, pressing `d` opens http://localhost:8080/q/dev/ and pressing `w` opens http://localhost:8080/.

### How to Reproduce?

1. Create a new app from code.quarkus.io
2. In `application.properties`, set `quarkus.http.port=8085`
3. Run dev mode
4. Press `w` or `d`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #21844

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I prefer the approach here: https://github.com/quarkusio/quarkus/pull/21902 

I don't really like the idea of creating new config.

**Comment by geoand** [comment]
Hm, I must be missing something because when I tried it, there was no Config object until it was created at that point.
Moreover, the created Config did not use the `application.properties` ConfigSource, so I don't see how #21902 addresses the issue

**Comment by stuartwdouglas** [comment]
The config is captured during the build step (which does have config). Currently the config is closed after the build so attempting to read it from an input command handler fails.

**Comment by geoand** [comment]
OK, thanks

**Comment by geoand** [comment]
Superceded by https://github.com/quarkusio/quarkus/pull/21902

**Pull request closed without merging**
