### PR TITLE
Simplify dockerfile declaration in codestart

### LINKED ISSUE #12706: Dockerfile codestart could be factorized to ease maintenance
**Description**
https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/dockerfiles/base/src/main/docker/Dockerfile.tpl.qute.fast-jar,
https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/dockerfiles/base/src/main/docker/Dockerfile.tpl.qute.jvm
and https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/dockerfiles/base/src/main/docker/Dockerfile.tpl.qute.native

have a lot of duplicated content.

**Implementation ideas**

You can use the qute include mechanism like we do for gradle: `https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/buildtool/gradle/base/build-layout.include.qute`

https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/buildtool/gradle/java/build.tpl.qute.gradle

Also, you can use buildtool data to provide the commands..

### PR DESCRIPTION
**Pull request by glefloch**
This branch aims to introduce a base `Dockerfile` in `codestart` to reduce the configuration

@ia3andy WDYT? I'm not really happy with those conditions in the `base/Dockerfil-layout.include.qute`, if you have a better solution, I will take it :)

close #12706

### CODE REVIEW

**Comment by gastaldi** [comment]
Maybe put in separate template files?

**Comment by glefloch** [comment]
Yes that's a good idea, we could keep the `native` Dockerfile out of the scope of the template. This would avoid conditions.

**Review by ia3andy — APPROVED** [review]
This looks good :)

Maybe we could improve a bit the generation test to make sure the output is alright?
https://github.com/quarkusio/quarkus/blob/master/integration-tests/devtools/src/test/java/io/quarkus/devtools/codestarts/QuarkusCodestartGenerationTest.java#L520

**Comment by glefloch** [comment]
Yes for sure.

**Comment by glefloch** [comment]
@ia3andy, I added some checks on the generated dockerfile. WDYT? I don't know if we could to build/run some of them in CI?

**Review by ia3andy — APPROVED** [review]
LGTM

**Pull request merged**
