### PR TITLE
Qute - default locale and charset

### LINKED ISSUE #21405: Support setting locale and charset for "default" Qute `Variant`
### Description

If I do _not_ want to set the `Variant` [for each `TemplateInstance`](https://quarkus.io/guides/qute-reference#template-variants) then the only way I could find to set it seems to be via `TemplateLocator`.
But usually I'm fine with how and from where templates are loaded, so implementing a `TemplateLocator` for this seems like overkill.

So it would be nice to have some way to configure which locale (and charset) is used.

### Implementation ideas

Maybe extend (and rename?) `quarkus.qute.content-types` so that you can also specify locale and encoding?

Or just introduce `quarkus.qute.locale` and `.encoding`?

### PR DESCRIPTION
**Pull request by mkouba**
- honor quarkus.default-locale and introduce
quarkus.qute.default-charset
- resolves #21405

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — DISMISSED** [review]
Let's clarify something before merging (marking as request changes to make sure it's not merged accidentally but it's a question really): I wonder if we should be symmetrical and also have the default charset in the global config. And if you want a more local Qute config, you could have overrides for both and default to global ones if not set and to the environment if global ones are not set.

My rationale is that this might be a useful config for other extensions too.

**Comment by mkouba** [comment]
> I wonder if we should be symmetrical and also have the default charset in the global config.

I'm not sure to be honest. My original idea was that while the locale is an abstraction that can be shared by many extensions the charset is only useful for extensions that read files... @gsmet do you have some specific extensions in mind?

> And if you want a more local Qute config, you could have overrides for both and default to global ones if not set and to the environment if global ones are not set.

That looks like an overkill...

**Comment by gsmet** [comment]
OK, as you wish. I just think this looks very weird as it is to have a global locale and a specific charset. Time will tell.

**Comment by mkouba** [comment]
> OK, as you wish. I just think this looks very weird as it is to have a global locale and a specific charset. Time will tell.

Hm, like I said I'm not quite sure ;-). Anyway, I'll update the docs as well.

**Comment by gsmet** [comment]
@rsvoboda this is the native test you added for web jar locator that failed ^. Could  you have a look?

**Comment by mkouba** [comment]
Shall we merge this PR? @gsmet

**Comment by rsvoboda** [comment]
@gsmet strange this happens from time to time. I checked few PRs and some are green, some have this test failed. In my local experiments I had green pass, will double check.

**Comment by rsvoboda** [comment]
I did 15 runs in a row and the tests always pass :/

I don't think there is something wrong with the test, failure of webjars-locator native test feels like a bug, but I can't really reproduce it and investigate it.

I plan to create GH issue for the case and ignore the native test so Quarkus CI is not polluted by it. This will need somebody with better native image experience. @gsmet wdyt?

**Comment by gsmet** [comment]
@mkouba sure, feel free to merge :).

**Comment by gsmet** [comment]
@rsvoboda  yes, let's comment out the testing for now. Thanks.

**Comment by rsvoboda** [comment]
Done - https://github.com/quarkusio/quarkus/issues/22718 ++ https://github.com/quarkusio/quarkus/pull/22719

**Pull request merged**
