### PR TITLE
Reorder Grpc server interceptors to apply exception handler correctly

### LINKED ISSUE #39602: Clients do not receive error response in case of an exception when using default gRPC API with `@Blocking` or `@RunOnVirtualThread`
### Describe the bug

Clients do not receive error response (they just hang waiting for a response that never arrives) in case of an exception when using default gRPC API with `@Blocking` or `@RunOnVirtualThread`.

Please note this bug is not seen with Mutiny gRPC API. Also, this works as expected with default gRPC API when `@Blocking` or `@RunOnVirtualThread` is not used.

|                                              | Mutiny gRPC API                      | Default gRPC API                     |
| -------------------------------------------- | ------------------------------------ | ------------------------------------ |
| Without `@Blocking` or `@RunOnVirtualThread` | *(expected)* client receives error   | *(expected)* client receives error   |
| `@Blocking`                                  | *(expected)* client receives error   | *(unexpected)* client hangs          |
| `@RunOnVirtualThread`                        | *(expected)* client receives error   | *(unexpected)* client hangs          |

### Expected behavior

Client should receive an error response

### Actual behavior

Client hangs

### How to Reproduce?

1. Clone repo - https://github.com/ranjanashish/quarkus-grpc-unhandled-exception-bug
2. Run unit tests using `./gradlew test`
3. Test will hang
4. Kill test and remove `@Blocking` from the RPC method
5. Re-run unit tests
6. Test will pass

The same behaviour applies when using `@RunOnVirtualThread`.

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.4.0

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
Fixes #39602 

To squash once reviewed

### CODE REVIEW

**Comment by ozangunalp** [comment]
@alesj I am not sure if this breaks anything. Please take a look

**Comment by alesj** [comment]
@ozangunalp so this looks like we had the interceptors order wrong all along?
@cescoffier ^^ ?!

**Comment by alesj** [comment]
The tests seem to pass locally
* https://gist.github.com/alesj/425fce74784e50f638794fb86c5b1730

**Review by alesj — APPROVED** [review]

**Comment by ozangunalp** [comment]
> @ozangunalp so this looks like we had the interceptors order wrong all along? @cescoffier ^^ ?!

Yes, the blocking interceptor schedules server listener calls on other threads so there wasn't any other way to apply the exception handling. The solution is to apply the blocking interceptor before the exception handling, so when an exception is thrown by the server method it gets handled by the handler and we close the server call by setting the status.

Where we need to pay attention in this change is all the other places I moved the list of interceptors. Sure tests pass but I am not sure whether we need to test something else.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Yes, it may break users interceptor, but I think this change makes a lot of sense.

**Comment by ozangunalp** [comment]
I am squashing it and it's good to go then

**Comment by alesj** [comment]
> Yes, it may break users interceptor, but I think this change makes a lot of sense.

Break them in what way?

**Comment by ozangunalp** [comment]
> > Yes, it may break users interceptor, but I think this change makes a lot of sense.
> 
> Break them in what way?

Expecting to get called in event loop but getting called on worker thread. But at least the context will be preserved.

**Comment by alesj** [comment]
> Expecting to get called in event loop but getting called on worker thread. But at least the context will be preserved.

Don't we / you control this with the @Blocking / @RunOnVirtualThread ... ?

Or this has changed now by default, and if someone is depending on this impl-details, it will break the current interceptors?

**Comment by ozangunalp** [comment]
> > Expecting to get called in event loop but getting called on worker thread. But at least the context will be preserved.
> 
> Don't we / you control this with the @Blocking / @RunOnVirtualThread ... ?
> 

It depends on the order in which interceptors are applied.

> Or this has changed now by default, and if someone is depending on this impl-details, it will break the current interceptors?

I don't think it is a big deal as interceptors are still applied by priority.

**Pull request merged**
