### PR TITLE
Validate formatting before build

### PR DESCRIPTION
**Pull request by gsmet**
This is a draft for now, I'll push a badly formatted file soon after to see how it behaves.

### CODE REVIEW

**Comment by gsmet** [comment]
It doesn't work as apparently it tries to download the `quarkus-bootstrap-core` artifact from Central:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce) on project quarkus-bootstrap-maven-plugin: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve following dependencies: [io.quarkus:quarkus-bootstrap-core:jar:999-SNAPSHOT (compile), io.quarkus:quarkus-bootstrap-core:jar:tests:999-SNAPSHOT (test)]: Could not resolve dependencies for project io.quarkus:quarkus-bootstrap-maven-plugin:maven-plugin:999-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-bootstrap-core:jar:999-SNAPSHOT, io.quarkus:quarkus-bootstrap-core:jar:tests:999-SNAPSHOT: Could not find artifact io.quarkus:quarkus-bootstrap-core:jar:999-SNAPSHOT in google-maven-central (https://maven-central-eu.storage-download.googleapis.com/repos/central/data/) -> [Help 1]

@aloubyansky do you have any idea why it doesn't see it as provided by the current build?

Note that I'm not yet sure this PR is a good idea, at least not until we have some cache for the artifacts because we download all the artifacts one more time.

**Comment by aloubyansky** [comment]
Not sure.

**Comment by stuartwdouglas** [comment]
You will need to make it run `mvn package -DskipTests` so it actually builds the artefacts that are required.

**Comment by stuartwdouglas** [comment]
I am going to close this, as it will conflict with the work I am doing to make the native tests run in parallel and use maven caching. My PR actually handles this anyway, as the initial build that resolves the maven artifacts from central will fail on any formatting errors.

**Pull request closed without merging**
