### PR TITLE
Bump kafka to 2.4.0

### PR DESCRIPTION
**Pull request by RotBolt**

### CODE REVIEW

**Comment by KaenDagger** [comment]
cc @michalszynkiewicz @gsmet

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
FWIW, I had the issue of Kafka ITs failing on Windows numerous times today. It doesn't look related to the upgrade.

**Comment by michalszynkiewicz** [comment]
thanks for info @gsmet

**Comment by KaenDagger** [comment]
I can check for windows as well @gsmet. Have a windows machine as well. But as far as I have  experienced trying to build Quarkus applications on windows. I faced many issues creating normal applications in the previous releases

**Pull request merged**
