### PR TITLE
Drop java < 11 support in native substitutions

### PR DESCRIPTION
**Pull request by zakkak**
[GraalVM head](https://github.com/oracle/graal/commit/488d0b55238e3eaeb93c4e3f1a5abfdf9f532b0a) no longer provides `JDK8OrEarlier` and `JSK11OrLater`.

Since Quarkus doesn't support Java 8 9 and 10, it should be safe to remove the usages of those classes (along with some deprecated substitutions).

### CODE REVIEW

**Comment by gastaldi** [comment]
@zakkak you need to run `mvn process-sources`  to have your imports sorted accordingly

**Review by gsmet — APPROVED** [review]
Thanks for the cleanup, I fixed the formatting issue and force pushed.

**Comment by gsmet** [comment]
Error is unrelated: Unable to find image 'quay.io/quarkus/ubi-quarkus-native-image:21.3-java11' locally
docker: Error response from daemon: Head "https://quay.io/v2/quarkus/ubi-quarkus-native-image/manifests/21.3-java11": received unexpected HTTP status: 502 Bad Gateway.

**Comment by zakkak** [comment]
> @zakkak you need to run `mvn process-sources` to have your imports sorted accordingly

Weird given that I only removed imports...

> Thanks for the cleanup, I fixed the formatting issue and force pushed.

Thanks for taking care of it @gsmet!

**Comment by gsmet** [comment]
> Weird given that I only removed imports...

You had an unused import (Function).

**Pull request merged**
