### PR TITLE
MP Config TCK - fix a regression caused by #2629

### PR DESCRIPTION
**Pull request by mkouba**
Could we also enable the `tcks` profile for CI?

### CODE REVIEW

**Comment by geoand** [comment]
Let me check this out locally and run it with the tck enabled.

**Review by geoand — APPROVED** [review]
LGTM and worked like a charm!

**Comment by geoand** [comment]
I would say we should add the TCK tests to CI, but that's just me :)

**Comment by mkouba** [comment]
@kenfinnigan @stuartwdouglas @cescoffier @gsmet Hey guys, who can modify the CI config? We just need to add `-Dtcks`.

**Comment by gsmet** [comment]
@mkouba apparently, you found your answer :)

**Comment by cescoffier** [comment]
Waiting for CI, we would need to check the output to verify the `-Dtcks`

**Comment by mkouba** [comment]
@gsmet well, it was @geoand who told me where to look ;-)

**Comment by geoand** [comment]
@mkouba Looks like the ` -Dtcks` was added to the wrong task. It should be added at https://github.com/quarkusio/quarkus/blob/master/azure-pipelines.yml#L75 instead of https://github.com/quarkusio/quarkus/blob/master/azure-pipelines.yml#L43

**Comment by mkouba** [comment]
@geoand I don't think so. We don't want to run the tcks for Build_JDK11_Linux. Well, we could run it for this job too. But primarily for Build_Native_Linux.

**Comment by mkouba** [comment]
The error is:
```
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.quarkus:quarkus-tck-microprofile-config:jar:999-SNAPSHOT
```

**Comment by geoand** [comment]
Why would we add it to the native job? I suppose it couldn't hurt, but that job is very slow as it is, so I would assume it would be best not to add it there.

Also in light of the error you mentioned what if we do the following:

Add a new job that first does `mvn  install -DskipTests -Dtcks` (to install everything needed), then changes to the tck directory and executes them like `mvn test -Dtcks`. 
That way we would know when a test failure is a TCK failure immediately

**Comment by mkouba** [comment]
Build_Native_Linux is basically all-in-one **JDK8** job. +1 for a new TCK-only job. But I'm not sure if that's acceptable. Would you care to communicate this?

**Comment by geoand** [comment]
Sure thing.

**Comment by geoand** [comment]
@cescoffier do you think we could add a new job as in CI as part of this? Do you see any reason why not to do it?

**Comment by cescoffier** [comment]
@geoand sure, we can add more CI jobs. 
That should be doable in the yaml file (in the project root).

**Comment by geoand** [comment]
Great! @mkouba would you like to try that approach and see how it goes?

**Comment by mkouba** [comment]
@geoand This PR should be open for changes. It would be great if you could take this over ;-).

**Comment by geoand** [comment]
@mkouba sure thing, I will take care of it later on today :)

**Comment by geoand** [comment]
TCKs are working, I'll merge as soon as the rest of the jobs go green

**Comment by mkouba** [comment]
@geoand Looks good! Thanks.

**Comment by geoand** [comment]
No problem!

**Pull request merged**
