### PR TITLE
fix (#9178): Use File.separator in S2iProcessor

### LINKED ISSUE #9178: OpenShift deployment (quarkus-openshift extension) fails on Windows
**Describe the bug**
OpenShift deployment using the quarkus-openshift extension fails on Windows.
The same project works fine on Linux.

**Expected behavior**
Deployment works on Windows too.

**Actual behavior**
```
[WARNING] [io.quarkus.container.image.s2i.deployment.S2iProcessor] No Openshift manifests were generated (most likely due to the fact that the service is not an HTTP service) so no s2i process will be taking place
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**To Reproduce**
1. Clone repo https://github.com/haraldatbmw/quarkus-openshift-deployment
2. Login to your OpenShift cluster `oc login ...`
3. Start deployment `mvn clean package -Dquarkus.kubernetes.deploy=true`

**Configuration**
```properties
quarkus.kubernetes-client.trust-certs=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7
quarkus.openshift.expose=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17134.1425]
 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
- oc tool: 
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

### PR DESCRIPTION
**Pull request by iocanel**
Fixes #9178

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand this should be backported to 1.3, right?

/cc @rsvoboda @tqvarnst

**Comment by geoand** [comment]
Yes, it should. We just need to see if/how we can add tests

**Comment by geoand** [comment]
@maxandersen @iocanel are we going to do anything about adding a test for this case?

I know it's not easy, but we really should at least look into it

**Comment by gsmet** [comment]
OK, I'm merging this as I want it for 1.3. Setting up a test infrastructure can be done as a follow-up in another issue/PR.

**Comment by gsmet** [comment]
@iocanel @geoand I don't think this fix is complete: https://github.com/quarkusio/quarkus/blob/master/extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java#L224

I have changed the 2nd occurrence too in my backport to 1.3.

**Comment by iocanel** [comment]
@gsmet: Do you need me to do something additional regarding the second occurrence you found?

**Pull request merged**
