### PR TITLE
Add support for Qute's createMulti in RESTEasy Reactive

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@Sanne @franz1981  do you have guys any time to test if this brings any benefit for Techempower?

**Comment by gsmet** [comment]
@geoand not sure what to do with this one? Does it make sense to revisit it with the various benchmarks going on?

**Comment by geoand** [comment]
Yeah, we should run some bechmarks on it

**Comment by geoand** [comment]
> @Sanne @franz1981 do you have guys any time to test if this brings any benefit for Techempower?

bump :)

**Comment by franz1981** [comment]
@geoand we do have to move to Qute as template processor there, while we are not using it now...maybe it's time!

**Comment by geoand** [comment]
Ah, I didn't remember it wasn't being used...

**Comment by geoand** [comment]
Let's close as it's really niche

**Pull request closed without merging**
