### PR TITLE
Unwrap tooltips in the downstream configuration reference docs

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes https://issues.redhat.com/browse/QDOCS-978

The downstream docs engine is unable to render `tooltip`-s, so we need to unwrap the tooltips in the configuration reference into regular text within the table

Example for the `quarkus.datasource."datasource-name".jdbc.transactions` config property:

Before this PR:
```
tooltip:enabled[Integrate the JDBC Datasource with the JTA TransactionManager of Quarkus. This is the default.], tooltip:xa[Similarly to `enabled`, also enables integration with the JTA TransactionManager of Quarkus, but enabling XA transactions as well. Requires a JDBC driver implementing `javax.sql.XADataSource`], tooltip:disabled[Disables the Agroal integration with the Narayana TransactionManager. This is typically a bad idea, and is only useful in special cases\: make sure to not use this without having a deep understanding of the implications.]
```

After this PR:
```
*enabled*: Integrate the JDBC Datasource with the JTA TransactionManager of Quarkus. This is the default.

*xa*: Similarly to `enabled`, also enables integration with the JTA TransactionManager of Quarkus, but enabling XA transactions as well. Requires a JDBC driver implementing `javax.sql.XADataSource`

*disabled*: Disables the Agroal integration with the Narayana TransactionManager. This is typically a bad idea, and is only useful in special cases: make sure to not use this without having a deep understanding of the implications.
```

@MichalMaler please check

### CODE REVIEW

**Review by MichalMaler — APPROVED** [review]

**Comment by MichalMaler** [comment]
@jmartisk Hey, Jan, that's a great and smart way to solve our problem with tooltip rendering while keeping Quarkus docs unchanged. Thanks a ton. It looks good; approved.

**Comment by jmartisk** [comment]
Note: don't merge this yet, we're still testing this with the downstreaming pipeline

**Comment by MichalMaler** [comment]
Upstream test and build works fine; downstream pipeline was finished successfully and provided the desired effect in the downstream repo:
https://gitlab.cee.redhat.com/quarkus-documentation/quarkus/-/jobs/28274480
However, Jenkis' build for the Datasource guide failed. I am returning the pipeline just to confirm that this was a casual Jenkins fail that happens from time to time.

Currently running pipeline:
* https://gitlab.cee.redhat.com/quarkus-documentation/quarkus/-/jobs/28277557 (this runs over this PR and puts the changes made here against our main, which currently mirrors Quarkus `3.15`)
* https://gitlab.cee.redhat.com/quarkus-documentation/quarkus/-/jobs/28277134 (our standard downstreaming pipeline that should produce no errors)

Lets see.

**Comment by gsmet** [comment]
Another option would be to adjust the Config Doc Maven plugin and have a specific run for the downstream doc with specific options. There is already an option to disable the tooltips (but it doesn't include the Javadoc in this case - for now).

That might be a bit more solid.

I don't remember the specifics of how we package this thing but just throwing out an idea.

In any case, this can be merged.

**Comment by MichalMaler** [comment]
@jmartisk 's last commits provide a working solution. QEs agree with this.

**Review by rsvoboda — APPROVED** [review]
It looks a bit fragile on the first sight, but with comments describing the expectations and flow of the change. Thus approving.

**Pull request merged**
