### PR TITLE
Add support of signature algorithms (PSxxx, EdDSA) in quarkus-oidc

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Related #33444

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @Eng-Fouad Can you please add `EdDSA` to that list ? As far as `PS*` is concerned, I was thinking of adding a test. But I'm not sure yet where

**Comment by Eng-Fouad** [comment]
> Thanks @Eng-Fouad Can you please add `EdDSA` to that list ? As far as `PS*` is concerned, I was thinking of adding a test. But I'm not sure yet where

EdDSA is added to the list.

**Comment by sberyozkin** [comment]
@Eng-Fouad I had to add an option to enforce a signature algorithm, something I've been planning for a long while and finally with your PR it became essential - as it is impossible to assert 100% that it is indeed for example `PS256` as opposed to `RS256` which was used to sign - given that the same `RSA` type JWK can verify both `PS256` and `RS256` if it has no `alg` set. After that testing was easy - we check the tenant expecting `PS256`  rejects `RS256` tokens but accepts `PS256` tokens,
We can't test `EdDSA` here - well, not yet, otherwise some native issues with Java 11 might show up, but once Java 17 becomes a minimum supported version in Quarkus - we can test them too - same way it is done in smallrye-jwt.

**Comment by sberyozkin** [comment]
Let me approve this one, as I only added a test to assert the main enhancement

**Review by sberyozkin — APPROVED** [review]

**Pull request merged**
