### PR TITLE
Second batch of modifications for #2299

### PR DESCRIPTION
**Pull request by FroMage**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
I fixed a minor typo and force pushed.

CI complained but I don't know why, I'm running a local build to check everything is OK.

**Comment by FroMage** [comment]
Huh, does it check javadoc?

**Comment by gsmet** [comment]
Yeah there was a formatting issue in the Javadoc. I force pushed a fix.

**Comment by FroMage** [comment]
Ah sorry I forgot about the formatter :(

**Comment by gsmet** [comment]
I'll merge and backport as soon as CI is green.

**Pull request merged**
