### PR TITLE
Avoid race condition in determining if SSL is used in integration tests

### PR DESCRIPTION
**Pull request by geoand**
The idea is to now always capture the output of the launched process in
order to determine whether it listens on SSL or not.
The previous mechanism trying the http could fail if the application didn't
start fast enough (which can easily happen when starting containers).

Furthermore, a nice side effect of having so much shared code is that if CI passes for `@NativeImageTest`, then the room for error for the others is really smally.

### CODE REVIEW

**Comment by geoand** [comment]
@gsmet this is meant to fix the flaky test we were seeing yesterdat

**Comment by geoand** [comment]
This needs more work - I'm going to look into it today

**Comment by geoand** [comment]
This is hopefully good now.

**Comment by geoand** [comment]
@sberyozkin `io.quarkus.it.keycloak.CodeFlowTest#testAuthenticationCompletionFailedNoStateCookie` is failing consistently with this PR, although I see no reason why it would... This PR changes some internal testing things, but the native image is started in the same way as with `master`.
Can you think of a reason why this test would fail? It seems to me that the application has frozen and is no longer responding... Do you know if there is some problem with the test that perhaps just now showed up?
Asking because every other test in the codebase passed just fine so this looks really suspicious...

**Comment by geoand** [comment]
Actually there might be in handling the process's output that could affect the tests - I'm looking into it

**Comment by geoand** [comment]
It should now be fine 🤞🏼

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
