### PR TITLE
Simplify extensions update info and allow extensions to contribute recipes

### LINKED ISSUE #34391: Fetch recipes from quarkus-updates for the non-core extensions updates
### Description

Recipes for the non-core extensions should be fetched from quarkus-updates when generating project update.

Part of #32392 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes https://github.com/quarkusio/quarkus/issues/34391

This allows any extension to contribute recipes of their own in the https://github.com/quarkusio/quarkus-updates/tree/main/recipes/src/main/resources/quarkus-updates repo

### CODE REVIEW

**Comment by geoand** [comment]
CI failures seem related

**Comment by ia3andy** [comment]
@geoand yes I'll fix it now, thanks!

**Comment by geoand** [comment]
👌

**Comment by ia3andy** [comment]
Superseded by #35910

**Pull request closed without merging**
