### PR TITLE
Upgrade to Oracle JDBC driver 23.5

### PR DESCRIPTION
**Pull request by Felk**
Trying my luck again, hoping no metadata has changed this time and CI passes without any modifications. For reference, previous upgrade was https://github.com/quarkusio/quarkus/pull/41998

### CODE REVIEW

**Comment by gsmet** [comment]
Please monitor CI on your fork, I'll start CI here if things are all good on your side. Thanks!

**Comment by Felk** [comment]
Here are the results: https://github.com/Felk/quarkus/actions/runs/10267101277

**Comment by gsmet** [comment]
Perfect, thanks!

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
And merged!

**Pull request merged**
