### PR TITLE
Remove BOM check when adding extensions in tooling

### LINKED ISSUE #10826: Maven Add Extension command fails with error about BOM
**Describe the bug**
Running the Add Extension command fails with the following message:

```
The Quarkus BOM is required to add a Quarkus extension
```

**Expected behavior**
The extension is added correctly.

**Actual behavior**
The extension isn't added as the command fails.

**To Reproduce**
1. Use the [Amazon Lambda HTTP guide](https://quarkus.io/guides/amazon-lambda-http) to generate a project using the artefact `quarkus-amazon-lambda-http-archetype` version `1.6.0.Final`.
2. Use Maven to add an extension to this new project:

```
mvn -X quarkus:add-extension -Dextensions="smallrye-jwt"
```

The command will fail with the following stacktrace:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.6.0.Final:add-extension (default-cli) on project artifactid1: Unable to update the pom.xml file: The Quarkus BOM is required to add a Quarkus extension -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:1.6.0.Final:add-extension (default-cli) on project artifactid1: Unable to update the pom.xml file
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to update the pom.xml file
    at io.quarkus.maven.AddExtensionMojo.doExecute (AddExtensionMojo.java:67)
    at io.quarkus.maven.QuarkusProjectMojoBase.execute (QuarkusProjectMojoBase.java:67)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.IllegalStateException: The Quarkus BOM is required to add a Quarkus extension
    at io.quarkus.devtools.project.buildfile.BuildFile.install (BuildFile.java:43)
    at io.quarkus.devtools.commands.handlers.AddExtensionsCommandHandler.execute (AddExtensionsCommandHandler.java:37)
    at io.quarkus.devtools.commands.AddExtensions.execute (AddExtensions.java:43)
    at io.quarkus.maven.AddExtensionMojo.doExecute (AddExtensionMojo.java:62)
    at io.quarkus.maven.QuarkusProjectMojoBase.execute (QuarkusProjectMojoBase.java:67)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux DESKTOP-GJJ95MV 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: NA
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: `1.6.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/rich/.sdkman/candidates/maven/current
Java version: 14.0.1, vendor: AdoptOpenJDK, runtime: /home/rich/.sdkman/candidates/java/14.0.1.hs-adpt
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.104-microsoft-standard", arch: "amd64", family: "unix"
```

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by ia3andy**
Related to #10836, Fixes #10826

As soon as the descriptor is resolved, we should be ok in 99.9% of the case..

### CODE REVIEW

**Comment by ia3andy** [comment]
@aloubyansky from my understanding:
- we were wrongly checking that the pom.xml was containing the same bom as the used plugin (1.6.0 and quarkus-universe-bom)
- with this fix, we check that a valid Quarkus bom is present (if it's not in the pom.xml, the descriptor version will contain the latest quarkus-universe-bom for the check, which will fail as we want)

**Comment by gsmet** [comment]
AFAICS, I'm able to build a project created by the archetype with this fix.

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
@gsmet then i'd say that's all we need for 1.6.1.Final.

**Comment by aloubyansky** [comment]
@ia3andy there are test failures
```
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.addExtensionWithGroupIdAndArtifactId:73->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.addMissingExtension:93->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.addSomeValidExtensions:25->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.doNotAddExtensionWhenMultipleMatch:173->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.testPartialMatchConflict:142->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.testPartialMatches:38->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.testRegexpMatches:49->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.testVertx:197->createProject:15->createProject:26 » IllegalState
[ERROR]   AddMavenExtensionsTest>AbstractAddExtensionsTest.testVertxWithDot:207->createProject:15->createProject:26 » IllegalState
[ERROR]   CreateProjectTest.create:39->createProject:129->createProject:140 » IllegalState
[ERROR]   CreateProjectTest.createMultipleTimes » Timeout createMultipleTimes() timed ou...
[ERROR]   ListExtensionsTest.listWithBom:34->createNewProject:194 » IllegalState The Qua...
[ERROR]   ListExtensionsTest.listWithBomExtensionWithSpaces:52->createNewProject:194 » IllegalState
[ERROR]   ListExtensionsTest.listWithoutBom:66->createNewProject:194 » IllegalState The ...
[ERROR]   ListExtensionsTest.searchRest:154->createNewProject:194 » IllegalState The Qua...
[ERROR]   ListExtensionsTest.searchUnexpected:132->createNewProject:194 » IllegalState T...
[ERROR]   RemoveMavenExtensionsTest>AbstractRemoveExtensionsTest.removeSomeValidExtensions:24->createProject:14->createProject:24 » IllegalState
[ERROR]   RemoveMavenExtensionsTest>AbstractRemoveExtensionsTest.testPartialMatches:46->createProject:14->createProject:24 » IllegalState
[ERROR]   RemoveMavenExtensionsTest>AbstractRemoveExtensionsTest.testRegexpMatches:64->createProject:14->createProject:24 » IllegalState
[ERROR]   QuarkusProjectCompressTest.createZip:35->createProject:87 » IllegalState The Q...
[ERROR]   QuarkusProjectCompressTest.createZipWithParentFolder:56->createProject:87 » IllegalState
[INFO] 
[ERROR] Tests run: 73, Failures: 0, Errors: 26, Skipped: 0
```

**Comment by gsmet** [comment]
FYI, this is high priority as I consider it blocking for the 1.6.1 release.

**Comment by ia3andy** [comment]
I am on it in a few minutes..

**Comment by ia3andy** [comment]
Ok we discussed it with @aloubyansky and thought it would be better to just remove that check.

Checking that the bom is defined is not enforcing that adding the extension won't break the project.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks guys! I'll wait for CI and merge. I already backported it in my 1.6.1 backports PR.

**Comment by famod** [comment]
Very interesting how this whole thing developed. From me saying "I don't question the check" until this removal. 😄

**Comment by gsmet** [comment]
Yup, that one was worth a discussion :).

**Pull request merged**
