### PR TITLE
Use Stork registrars in standalone way

### PR DESCRIPTION
**Pull request by aureamunoz**
This requires a new Stork release. Will made it after holidays, from 19th August.

### CODE REVIEW

**Comment by aureamunoz** [comment]
cc @cescoffier

**Comment by melloware** [comment]
@cescoffier i think this is what I need.  Will this allow me to programatically add a Consult client.  Right now I have a customer converting from Spring Boot and they don't like that they have to do this...

```java
 /**
     * Register our two services in Consul.
     *
     * Note: this method is called on a worker thread, and so it is allowed to block.
     * @throws UnknownHostException 
     */
    public void init(@Observes StartupEvent ev, Vertx vertx) throws UnknownHostException {
        String consulHost = ConfigProvider.getConfig().getValue("quarkus.stork.my-service.service-discovery.consul-host", String.class);
        int consulPort = ConfigProvider.getConfig().getValue("quarkus.stork.my-service.service-discovery.consul-port", Integer.class);
        ConsulClient client = ConsulClient.create(vertx, new ConsulClientOptions().setHost(consulHost).setPort(consulPort));

        int port = ConfigProvider.getConfig().getValue("quarkus.stork.my-service.service-discovery.consul-port", Integer.class);
        String address = InetAddress.getLocalHost().getHostAddress();
        String name = ConfigProvider.getConfig().getValue("quarkus.application.name", String.class);
        client.registerService(
                new ServiceOptions().setPort(port).setAddress(address).setName(name).setId("greeting-service"));
    }
```


They don't want to write Java code in every service they just want to use configs to register their services?

**Comment by aureamunoz** [comment]
Yes, this is what you need @melloware . With this feature you don't event need to instantiate the ConsulClient, stork will do it for you. You just will need to configure in properties the host and port of the Consul.
This will be only available in Quarkus 3.16 though.

Let me try to provide a quickstart.

**Comment by melloware** [comment]
Darn not until 3.16?  Also as part of this PR don't the docs need to be updated?

**Comment by aureamunoz** [comment]
This PR uses Stork 2.7.0 which contains the [documentation](http://smallrye.io/smallrye-stork/latest/service-registration/consul/). I will also add a quickstart with it in the [quickstarts repository](https://github.com/quarkusio/quarkus-quickstarts). As an example, for now you can check [the integration tests](https://github.com/aureamunoz/quarkus/blob/e5b86799e68f86f09937d117399d907a42004f9a/integration-tests/smallrye-stork-registration/src/main/java/org/acme/services/Registration.java#L22).

**Comment by melloware** [comment]
@aureamunoz thanks but the IT still does this.

```java
 Stork.getInstance().getService("my-service").getServiceRegistrar().registerServiceInstance("my-service", "localhost",
                red);
```

My client is looking for a ZERO code option so they can just do this.

```
quarkus.stork.my-service.service-registrar.type=consul
```

And it automatically registers the service by `quarkus.application.name`, `quarkus.http.port` etc so they don't have to code anything. Are you saying the above will be possible in Quarkus 3.16?

**Comment by aureamunoz** [comment]
> @aureamunoz thanks but the IT still does this.
> 
> ```java
>  Stork.getInstance().getService("my-service").getServiceRegistrar().registerServiceInstance("my-service", "localhost",
>                 red);
> ```
> 
> My client is looking for a ZERO code option so they can just do this.
> 
> ```
> quarkus.stork.my-service.service-registrar.type=consul
> ```
> 
> And it automatically registers the service by `quarkus.application.name`, `quarkus.http.port` etc so they don't have to code anything. Are you saying the above will be possible in Quarkus 3.16?

Ah, I didn't get that. No, that is not possible at the moment. Still need to pass the host and port of the application to register. We had mention something like this [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Stork.20service.20registrar/near/448872275). I could do it but not sure to be able to work on that inmediately.

**Comment by melloware** [comment]
OK they are coming from Spring Boot and Spring Boot does this: https://cloud.spring.io/spring-cloud-consul/reference/html/

> The default service name, instance id and port, taken from the Environment, are ${spring.application.name}, the Spring Context ID and ${server.port} respectively.

I think Quarkus should definitely do something similar.

**Comment by aureamunoz** [comment]
Ready for review @cescoffier

**Comment by cescoffier** [comment]
@melloware this is heavily dependent on the environment. These days it's rare an application knows it's public IP and public port (typically, as soon as you run in a container you do not have this info anymore). So I would be very cautious about providing such a feature which may end up registering unreachable services.

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
