### PR TITLE
Bump Keycloak version to 19.0.3

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier I have seen `DuplicatedContextTest.testThatBlockingEventConsumersAreCalledOnDuplicatedContext` being flaky several times lately.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@sberyozkin should this one be backported?

**Comment by sberyozkin** [comment]
@gsmet Thanks, I'd say so, hopefully it will make things more stable, let me add the label

**Comment by sberyozkin** [comment]
@gsmet I'm removing the backport label for now, due to https://github.com/keycloak/keycloak/issues/14962

**Pull request merged**
