### PR TITLE
KOGITO-5560 remove 'preview'label from community website

### PR DESCRIPTION
**Pull request by tarilabs**
Draft as pending Kogito upstream PR first: https://github.com/kiegroup/kogito-runtimes/pull/1462

https://issues.redhat.com/browse/KOGITO-5560

### CODE REVIEW

**Comment by gsmet** [comment]
I don't think it makes sense to backport it past 2.0 as the older versions are using older versions of Kogito, so I suppose versions that should be considered preview still.

**Comment by tarilabs** [comment]
We have Kogito runtime components from RHDM/RHPAM v7.11, which translates afaik to RHBQ equivalent of Quarkus-1.11, so I believe backport to Quarkus 1.11 inclusive, is indeed meaningful.

(
that's would have been the ~equivalent of 
```
1.11 https://github.com/quarkusio/quarkus/pull/18905
1.12 https://github.com/quarkusio/quarkus/pull/18906
1.13 https://github.com/quarkusio/quarkus/pull/18907
2.0 https://github.com/quarkusio/quarkus/pull/18909
2.1 https://github.com/quarkusio/quarkus/pull/18910
```
)

**Comment by gsmet** [comment]
Well, you will need a Quarkus Platform release to push the latest Kogito bits. I have no idea what's planned for this. I can mark it for backport but I have no idea if a new 1.11 will be released.

What's for sure is that we won't release any new 1.12 or 1.13.

**Comment by tarilabs** [comment]
https://github.com/quarkusio/quarkus/pull/18904#issuecomment-884320619 this is a bit beyond my radar, the intent here was actually to reflect the website guide, not code. I will follow-up in due time with the Kogito leads.

**Comment by danielezonca** [comment]
@tarilabs 
Thanks for the PR, I agree with @gsmet that `main` should be enough

@gsmet 
Thanks for tracking it as possible backport for 1.11 but it should not be a big deal even if it will not be backported 👍

**Comment by tarilabs** [comment]
This PR marked as ready following merge event on https://github.com/kiegroup/kogito-runtimes/pull/1462#event-5085007428

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@tarilabs just a note that the preview status has been added to the other guides you all created. Not sure if it should be dropped or not?

**Comment by tarilabs** [comment]
@gsmet you right, `prediction` and `rule` was missing to remove the Preview label, but AFAIK `decision` did not have Preview.

**Comment by tarilabs** [comment]
I have included comment in the related PR with your spotting, thanks @gsmet

**Pull request merged**
