### PR TITLE
Make all build time properties visible at run time

### LINKED ISSUE #6255: quarkus.application.version config property is unavailable
**Describe the bug**
The following config property injection doesn't work: 
```java
@Path("/hello")
public class GreetingResource {

    @ConfigProperty(name = "quarkus.application.version", defaultValue = "not-set")
    String version;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello " + version;
    }
}
```
**Expected behavior**

When running `http localhost:8080/hello`, to return `hello 1.0.0-SNAPSHOT`

**Actual behavior**
When running `http localhost:8080/hello`, it returns `hello not-set`

**To Reproduce**
1. Create a sample project and add the endpoint above

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #6255

### CODE REVIEW

**Comment by geoand** [comment]
I just tried this and it doesn't seem to fix the original issue

**Comment by dmlloyd** [comment]
This makes sense in retrospect.  But this stil might be a legitimate issue.  I'll come back to it later.

**Comment by gsmet** [comment]
@dmlloyd is this PR still a thing or should we close it?

**Comment by dmlloyd** [comment]
It's probably still legitimate.  I'll update it and see what happens.

**Comment by dmlloyd** [comment]
Never mind, looks like it can't be merged anymore.

**Pull request closed without merging**
