### PR TITLE
Bump kubernetes-client-bom from 5.7.0 to 5.7.1

### PR DESCRIPTION
**Pull request by manusa**
Kubernetes Client 5.7.1 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v5.7.1

Just speeding up the dependabot process to see if CI reports any issue.

/cc @metacosm

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by manusa** [comment]
These might be causing trouble:
- https://github.com/fabric8io/kubernetes-client/pull/3427
- https://github.com/fabric8io/kubernetes-client/pull/3422

**Comment by gastaldi** [comment]
> These might be causing trouble:
> 
> * [chore(deps): bump jandex from 2.3.1.Final to 2.4.0.Final fabric8io/kubernetes-client#3427](https://github.com/fabric8io/kubernetes-client/pull/3427)
> * [chore(deps): bump jandex-maven-plugin from 1.1.0 to 1.1.1 fabric8io/kubernetes-client#3422](https://github.com/fabric8io/kubernetes-client/pull/3422)

@manusa I think jandex-maven-plugin needs to be updated to 1.2.0. @Ladicek do you know why the tests failed with this error?

**Comment by gastaldi** [comment]
I rebased the branch, let's see how it behaves now that the main branch is also updated. I am not 100% sure if we can backport this PR without backporting the Jandex bump too

**Comment by manusa** [comment]
https://github.com/quarkusio/quarkus/pull/14586

**Comment by Ladicek** [comment]
Here's the interesting part: https://github.com/fabric8io/kubernetes-client/blob/v5.7.1/pom.xml#L612-L632. Fabric8 Kubernetes Client's POM explicitly says that the Jandex Maven plugin is _not_ supposed to use the Jandex version it was built with, but the Jandex version the POM includes. So even though the Jandex Maven plugin is version 1.1.1, it used Jandex 2.4.0.Final.

Jandex 2.4 writes indices of version 10, which Jandex 2.3 can't read.

**Comment by manusa** [comment]
Is #14586 going to be backported?
If not, can we release a 5.7.2 version of the client that generated index files in an earlier Quarkus 2.2 compatible version (which version? how to configure?)?

**Comment by Ladicek** [comment]
I don't think we should backport #14586. My personal opinion is that we also shouldn't backport the Jandex 2.4.0.Final upgrade, but I could be convinced otherwise, I guess :-)

I'd recommend Fabric8 Kubernetes Client to downgrade Jandex back to 2.3.1.Final and re-release.

I'm also writing down a Jandex compatibility promise, which unfortunately hasn't been done before.

**Comment by Ladicek** [comment]
FYI, I'm trying to add an explicit compatibility promise to Jandex in this PR: https://github.com/wildfly/jandex/pull/136 Comments welcome :-)

**Comment by gastaldi** [comment]
Let's upgrade to 5.7.2, which uses Jandex 2.3.1 (meaning it's backportable). Closing this now

**Pull request closed without merging**
