### PR TITLE
Reactive routes - improve @Route method invocation performance

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by mkouba** [comment]
@johnaohara FYI this could improve the performance of `@Route` method invocations a little bit. Although I'm not quite sure it would make any significat difference in your use case.

**Comment by johnaohara** [comment]
@mkouba i'll try it out, thanks

**Comment by mkouba** [comment]
@johnaohara Did you get a chance to test this branch? 

Anyway, I think that it wouldn't hurt to merge this even though we have no perf numbers yet.

**Review by cescoffier — APPROVED** [review]

**Comment by johnaohara** [comment]
Approx 3.3% improvement in throughput for simple plain text test

```
2020-04-14 12:12:06,470 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT (powered by Quarkus 1.3.1.Final) started in 0.583s. Listening on: http://0.0.0.0:8080


$ wrk -c 100 -t 4 -d 30s http://benchserver4G1:8080/hello/John
Running 30s test @ http://benchserver4G1:8080/hello/John
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.82ms   13.21ms  54.63ms   82.37%
    Req/Sec    30.45k     2.16k   46.01k    72.09%
  3646069 requests in 30.10s, 170.38MB read
Requests/sec: 121132.29
Transfer/sec:      5.66MB




2020-04-14 12:14:46,529 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT (powered by Quarkus 999-SNAPSHOT) started in 0.595s. Listening on: http://0.0.0.0:8080


$ wrk -c 100 -t 4 -d 30s http://benchserver4G1:8080/hello/John
Running 30s test @ http://benchserver4G1:8080/hello/John
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.69ms   13.06ms  53.55ms   82.44%
    Req/Sec    31.49k     1.93k   43.40k    71.49%
  3767409 requests in 30.10s, 176.05MB read
Requests/sec: 125163.16
Transfer/sec:      5.85MB
```

**Comment by mkouba** [comment]
@johnaohara thanks!

**Comment by mkouba** [comment]
@gsmet Unfortunately, there is a bug in this PR. Thanks @michalszynkiewicz for spotting the problem. I'm going to send a fix shortly.

**Comment by gsmet** [comment]
Looks like we need more tests :).

**Comment by mkouba** [comment]
Well, I don't think that regular tests would cover this. It's a race condition... caused by my inattention.

**Pull request merged**
