### PR TITLE
Add artifact coords and enable resource filtering for quarkus-extension.yaml

### PR DESCRIPTION
**Pull request by aloubyansky**
This PR adds artifact coords in the form of `${project.groupId}:${project.artifactId}:${project.version}` and enables resources filtering for extension modules, so the relevant tests launched from IDEA actually work.

### CODE REVIEW

**Comment by aloubyansky** [comment]
What do you mean by "take time" though? It looks like we need to do something about it now. I.e. current options include:
1) exclude the template file from the jar;
2) revert Stuart's PR but that'll break the dev mode tests launched from IEDA;
3) merge this PR.

> One other option could be to generate an augmented version of this file rather than overwriting it that would be consumed by the tools if existing?

Isn't it what Stuart's change is about? That's ok, but then we need to exclude the template file from the jar. And we now support two ways to provide the template: the original yaml and yaml.template. Plus, DevUI tests (in perspective) may be affected because the extension G:A won't be available.

**Comment by ia3andy** [comment]
This PR seems good.

I think @gsmet meant we shouldn't merge a PR that's break the contract without further thinking about it.

**Comment by aloubyansky** [comment]
It didn't look like it broke a contract. The original yaml was still supported.

**Comment by ia3andy** [comment]
> It didn't look like it broke a contract. The original yaml was still supported.

Ok then, it makes more sense, maybe we missed that part :)

**Review by stuartwdouglas — APPROVED** [review]

**Comment by aloubyansky** [comment]
@gsmet are you ok with this for the upcoming Alpha3? Otherwise, we need to look into excluding the template file from the jar.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@aloubyansky I merged it but I'm still unsure it's such a good idea to augment the file in place.

**Pull request merged**
