### PR TITLE
Fix quarkus.knative.image-pull-policy property

### LINKED ISSUE #23832: Knative: Property `quarkus.knative.revision-auto-scaling.container-concurrency` is ignored
### Describe the bug

When using the property `quarkus.knative.revision-auto-scaling.container-concurrency` with a value `5` for example and we generate the Knative manifests, the generated Knative service ignores this value and it always uses `0`:

```yaml
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-02-21 - 11:09:14 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: knative-demo
  name: knative-demo
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: knative-demo
      name: my-revision
    spec:
      containerConcurrency: 0
      containers:
        - image: jcarvaja/knative-demo:1.0.0-SNAPSHOT
          name: knative-demo
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
```

I did check that the decorator `ApplyLocalContainerConcurrencyDecorator` is executed with the right value (`5`), but for some reason, this is overwritten later. 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Plus, this pull request also verifies that https://github.com/quarkusio/quarkus/issues/23832 is fixed. 
Fix https://github.com/quarkusio/quarkus/issues/23832

### CODE REVIEW

**Comment by Sgitario** [comment]
@iocanel the new test is based on what you did in this commit: https://github.com/quarkusio/quarkus/commit/327520db72e38a1bb892aa1608be69f6470c6c34

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@Sgitario should we backport to 2.15?

**Comment by Sgitario** [comment]
Yes, I think we can safely backport it.

**Pull request merged**
