### PR TITLE
Remove private field injection from within our own extensions.

### PR DESCRIPTION
**Pull request by manovotn**
These can lead to debug log warning about unrecommended usage of private fields.

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
@manovotn can you also change `QuarkusObjectMapperContextResolver` please?

**Comment by manovotn** [comment]
> `QuarkusObjectMapperContextResolver`

Sure thing, done!

**Review by geoand — APPROVED** [review]
LGTM, thanks!

**Comment by loicmathieu** [comment]
@manovotn there is also one in quarkus Vert.x

```
2019-10-31 10:36:30,600 INFO  [io.qua.arc.pro.BeanProcessor] (build-22) Found unrecommended usage of private members (use package-private instead) in application beans:
	- Bean constructor void <init>() on io.quarkus.vertx.CodecRegistrationTest$EventBusConsumers
```

**Comment by manovotn** [comment]
@loicmathieu I'll add it here as well, but that's just a test class.
I know there are even some tests that have this deliberately (mostly in arc) but I don't think we care about this much in tests.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
