### PR TITLE
Upgrade Hibernate Reactive to 1.1.7.Final

### PR DESCRIPTION
**Pull request by DavideD**
Latest Hibernate Reactive release

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@DavideD is it something we should backport to 2.10?

**Comment by DavideD** [comment]
I think so. We fixed a pretty nasty bug: https://github.com/hibernate/hibernate-reactive/issues/975

**Comment by gsmet** [comment]
OK thanks. Label added.

**Comment by geoand** [comment]
The failing test has nothing to do with this PR, it's being addressed in https://github.com/quarkusio/quarkus/pull/26492

**Comment by Sanne** [comment]
We'll need this backported to 2.7 as well

**Comment by fedinskiy** [comment]
@gsmet it looks like this change was not backported to 2.7: https://github.com/quarkusio/quarkus/blob/2.7/bom/application/pom.xml#L95

**Comment by gsmet** [comment]
Hmmm. I think we tried to upgrade it and then we stumbled upon some issues with either Mutiny or Vert.x and had to back off.

It should be removed from the 2.7 version. I will adjust the PR.

**Comment by gsmet** [comment]
I had a recollection of having written something about it and it's here: https://github.com/quarkusio/quarkus/pull/30367#issuecomment-1386781586 .

But we forgot to unmark the pull requests.

**Pull request merged**
