### PR TITLE
Rest-client-reactive: support ClientRequestContext.[get|set]EntityStream()

### PR DESCRIPTION
**Pull request by Erfankam**
Please review and accept the changes.

### CODE REVIEW

**Comment by Erfankam** [comment]
Would you please to check PR?

**Comment by Erfankam** [comment]
I will recheck PR and request for pull again.

**Comment by maxandersen** [comment]
@Erfankam can you reach out to me on either twitter(@maxandersen) or e-mail: manderse@redhat.com on this PR? Thanks

**Comment by Erfankam** [comment]
> 

Yes of course. I will be in contact.

> @Erfankam can you reach out to me on either twitter(@maxandersen) or e-mail: [manderse@redhat.com](mailto:manderse@redhat.com) on this PR? Thanks

Yes of course. I will be in contact.

**Pull request closed without merging**
