### PR TITLE
Respect max message size property fo Quarkus GRPC client (44853)

### LINKED ISSUE #44853: Quarkus Vertx GRPC Client should respect "max-inbound-message-size" property
### Describe the bug

Quarkus Vertx GRPC client should respect `quarkus.grpc.clients."client-name".max-inbound-message-size` property. Now it only affects java-grpc client.

### Expected behavior

The property is respected

### Actual behavior

Quarkus Vertx GRPC client uses default restriction.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The solution could give us a workaround for this issue: https://github.com/quarkusio/quarkus/issues/44852

### PR DESCRIPTION
**Pull request by alex-pumpkin**
Fixes https://github.com/quarkusio/quarkus/issues/44853 and gives a workaround for https://github.com/quarkusio/quarkus/issues/44852

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
Thanks!

**Comment by cescoffier** [comment]
Can you check the formatting?

**Comment by alex-pumpkin** [comment]
Sure. The imports are sorted now.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Can you squash your commits?

**Comment by alex-pumpkin** [comment]
Done

**Comment by alex-pumpkin** [comment]
Sorry, I have synchronized it with the main branch wrong. Should I reopen with clean branch and commits?

**Comment by geoand** [comment]
You can just rebase your branch onto `main` and then force push

**Comment by alex-pumpkin** [comment]
Great, thanks. Never used force push before :)

**Comment by geoand** [comment]
It's perfectly fine to do that on your own branches (that are not being worked by others)

**Comment by cescoffier** [comment]
If it backports cleanly yes.

**Comment by gsmet** [comment]
I tried to backport it to 3.17 and I have the following test failure:

Screenshot from 2024-12-03 18-30-27

The issue can be seen in this (now probably hidden) issue: https://github.com/quarkusio/quarkus/pull/44897#issuecomment-2515109970 .

@cescoffier any clue?

**Comment by cescoffier** [comment]
@gsmet Nope, I don't why this PR could change this test. (@alesj any idea).

BTW, due to the last comment on https://github.com/quarkusio/quarkus/issues/44852, I don't believe we should backport. We need to understand the behavior difference between gRPC java and the Vert.x gRPC first. (removing the label, sorry about that).

**Comment by alesj** [comment]
> (@alesj any idea).

Uh, no idea, since this change looks trivial / simple.

**Pull request merged**
