### PR TITLE
Dev UI: Move dependencies from bom to build-parent

### PR DESCRIPTION
**Pull request by phillip-kruger**
@gsmet as discussed before, I am moving the Dev UI dependencies out of the BOM to the Dev UI module. 
There is no real reason that it needs to be in the BOM, as this is (from a Dev UI perspective) only used in deployment module.
This is so that we can change the scope when using it from web-bundler (especially transitively). At the moment the BOM makes this difficult.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
I am not too sure why the CI Build fails. Any tips @gsmet ?

**Comment by cescoffier** [comment]
I understand the idea. The PR looks good, but I guess the enforcer is preventing us to do that.

**Review by cescoffier — COMMENTED** [review]
The enforcer is most probably not very willing to let us do this.

**Comment by phillip-kruger** [comment]
@cescoffier do you know if I can add an exception to this for mvnpm ?

**Comment by gsmet** [comment]
@phillip-kruger I think the problem is that your dependencies are not consistent. You probably need to enforce the version by moving the version to a `dependencyManagement` of the module.

**Comment by phillip-kruger** [comment]
@gsmet Having it in the dependency management of the dev-ui module still failed. I have now moved it to the build-parent, let's see if that does the trick

**Comment by phillip-kruger** [comment]
@gsmet @cescoffier CI passing, please review :)

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Let's keep this for 3.5 as it's going to be a bit annoying to backport (versions are not the same so there is a conflict and a risk of introducing unwanted changes) and I don't think it's urgent.

Let me know if it's more urgent than it looks.

**Pull request merged**
