### PR TITLE
Disable probes production if health extensions are disabled

### LINKED ISSUE #38613: RabbitMQ Health Checks cannot be disabled from 3.7+
### Describe the bug

mp.messaging.incoming.XXX.health-enabled=false removes the channel from the health check data, but even if there is only one channel and its health is turned off, it will fail the health checks if rabbit cannot be connected

e.g.
{
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "application-com.ukheshe.services.banknodescantopay.BanknodeScanToPayBankReplyListener#consume": "[KO] - Connection refused"
            }
        }

Also,
quarkus.health.extensions.enabled=false
Used to completely disable reactive messaging health checks on <=3.6 but from 3.7 onwards it does not disable the health checks.

### Expected behavior

If all channels have health disabled then completely disable health checks for reactive messaging

if quarkus.health.extensions.enabled=false then completely disable health checks for reactive messaging

### Actual behavior

As per bug description

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by metacosm**
Partially fixes #38613, at least for probes generation in kubernetes manifests.

### CODE REVIEW

**Review by xstefank — CHANGES_REQUESTED** [review]
@metacosm sorry but I don't think this is a correct fix. The probes should be created in the manifest. The issue with Reactive messaging not respecting health disable properties will be somewhere else.

**Comment by metacosm** [comment]
> @metacosm sorry but I don't think this is a correct fix. The probes should be created in the manifest. The issue with Reactive messaging not respecting health disable properties will be somewhere else.

Not sure I follow what you're saying… If the health extensions are disabled, I don't think that the probes should be created in the manifests because they won't be anything available at these endpoints. 

Anyway, that was my attempt at fixing it but I have only a small point of view on the issue so I'm more than happy to close this PR in favor of something that would address the issue better / more completely.

**Comment by ozangunalp** [comment]
If the health check extensions is not enabled does that mean that application-provided health check are not enabled as well ? 

Because the issue with reactive messaging is https://github.com/quarkusio/quarkus/issues/38613#issuecomment-1931655312

**Comment by metacosm** [comment]
Actually, I think there might be some confusion here on my part, at least: is it possible to disable health check support completely even if the extension is present? Or is the only way to do so is to remove the extension?

**Comment by xstefank** [comment]
@metacosm users can still define their health checks, for instance, even when disabling Quarkus ones.

Also, smallrye-health presence should generate K8s probes.

**Comment by metacosm** [comment]
> @metacosm users can still define their health checks, for instance, even when disabling Quarkus ones.
> 
> Also, smallrye-health presence should generate K8s probes. 

OK, so that's where we disagree. Imo, there should be a way to disable the extension even when it's present as there might be cases where you don't want its support but still don't want to remove the extension from your build just for the sake of not having health check for a particular use case. As a consequence, whenever support is disabled via this property, nothing health related should be generated (including k8s probes). So maybe this isn't so much a bug as much as a feature request? 😉

**Comment by xstefank** [comment]
@metacosm if that would be a requirement than we need a new property. `healthBuildTimeConfig.extensionsEnabled` means only extension provided checks. Other checks should still be present.

**Comment by cescoffier** [comment]
@metacosm @xstefank Where are we on this one?

**Comment by xstefank** [comment]
If @metacosm agrees, I would close this and we will open new issue if https://github.com/quarkiverse/quarkus-operator-sdk/issues/818 is reopened.

**Comment by metacosm** [comment]
Agreed.

**Pull request closed without merging**
