### PR TITLE
Remove Secret handling from kubernetes-config extension

### PR DESCRIPTION
**Pull request by geoand**
This is done because we don't (yet) have a good way to create the proper
ClusterRole (see: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrole-example)
so in any cluster that has RBAC enabled, an application that uses secrets
with this extension will fail unless the user performs additional actions

Came about after a long discussion and debugging session with @lordofthejars.

### CODE REVIEW

**Comment by geoand** [comment]
@gsmet this is a breaking change - but breaking from `1.4.0.CR1`, not from `1.3.x` where the `kubernetes-extension` didn't exist.

**Comment by Ladicek** [comment]
1. You don't need to create a `ClusterRole`, you can just create a `Role`. (And a corresponding `RoleBinding`, of course.)
2. Per https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles, it seems the `edit` cluster role should have access to secrets, so if we detect that users want to access secrets (can we do that at build time?), we can just create a `RoleBinding` that doesn't reference the `view` role, but the `edit` role.

**Comment by geoand** [comment]
>     2. Per https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles, it seems the `edit` cluster role should have access to secrets, so if we detect that users want to access secrets (can we do that at build time?), we can just create a `RoleBinding` that doesn't reference the `view` role, but the `edit` role.

We could, but there is no guarantee it will be the same as runtime. Furthermore, `edit` seems a little too big of a hammer, no?

**Comment by Ladicek** [comment]
> We could, but there is no guarantee it will be the same as runtime.

Not quite sure what that means. Do you mean that we can't reliably detect at build-time that access to secrets will be required?

> edit seems a little too big of a hammer, no?

Perhaps so. In that case, we could generate a custom `Role` that would only allow access to secrets.

**Comment by geoand** [comment]
> > We could, but there is no guarantee it will be the same as runtime.
> 
> Not quite sure what that means. Do you mean that we can't reliably detect at build-time that access to secrets will be required?
> 
> > edit seems a little too big of a hammer, no?
> 
> Perhaps so. In that case, we could generate a custom `Role` that would only allow access to secrets.

Exactly, that is what I want to do. But we currently don't have a good way of doing that, which is why I am proposing to remove `Secret` handling until we do.
I really want the experience to be hassle free :)

**Comment by Ladicek** [comment]
Ah, you mean that implementation-wise, we don't have a way to ask the `kubernetes` extension to generate an extra resource, and it would take too much time to implement a good one? Fair enough.

Just wanted to highlight that there's no conceptual problem, we're generating a dozen resources and one more `Role` doesn't make a difference.

**Review by Ladicek — APPROVED** [review]

**Comment by geoand** [comment]
Yes that is exactly what I mean

**Comment by geoand** [comment]
I'll wait for a review from @iocanel as well, since he might have some trick up his sleeve we could apply instead of this heavy handed PR.

**Comment by geoand** [comment]
@iocanel do you have anything better to propose? If not, we should really have this in for `1.4`

**Comment by iocanel** [comment]
Not atm

**Comment by geoand** [comment]
Thanks.

Let's merge this then and come back to secret handling when we come up with a more configurable way of generating roles

**Pull request merged**
