### PR TITLE
Adapt the Maven project creation logic to always create a sub-directory

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by cescoffier** [comment]
Once merged, the guides must be updated to explicitly indicate to "cd" in the created directory.

**Comment by maxandersen** [comment]
> Once merged, the guides must be updated to explicitly indicate to "cd" in the created directory.

If we don't merge, the guides must updated to explicitly indicate to "mkdir" + "cd" into the directory before running  the commands ;)

j/k - change looks good - makes the behavior consistent for everyone.

**Review by maxandersen — APPROVED** [review]
LGTM - now we can update the guides to follow one deterministic approach.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
OK, it mostly passed the first build except for the documentation which is unrelated. I don't see why it would fail elsewhere. Let's merge and be done with it.

**Pull request merged**
