### PR TITLE
Enable kubernetes authentication path configuration in Vault extension

### LINKED ISSUE #9871: Enhance quarkus vault integration - allow users to specify k8s auth method mount path
**Description**
Kubernetes auth method mount path can be customized by users, e.g. using below command
```bash
vault auth enable -path mycluster kubernetes
```
In this case if we want to do vault k8s login, we need to login against "auth/mycluster/login".

But currently, the [OkHttpVaultClient ](https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/client/OkHttpVaultClient.java#L93)hard coded the mount path to "auth/kubernetes/login", which won't work if users specify different mount paths.

New application configuration property should be introduced to allow users to specify customized k8s auth mount path.

### PR DESCRIPTION
**Pull request by ejba**
* Allows kubernetes authentication path configuration through the "kubernetes.auth-endpoint-path" config property

Closes #9871

### CODE REVIEW

**Comment by vsevel** [comment]
@ejba only `auth/kubernetes` should be made configurable. not `/login`, which comes from the [api](https://www.vaultproject.io/api-docs/auth/kubernetes#login)

**Comment by ejba** [comment]
@vsevel Do you want that config property to be parsed? For example, strip slashes or something?

**Comment by vsevel** [comment]
> @vsevel Do you want that config property to be parsed? For example, strip slashes or something?

hello @ejba . I do not think it is necessary.
can you update also `VaultConfigSource.loadRuntimeConfig()` with the additional property? it needs to be kept in synch until we move property loading in the boostrap phase.
I see also that the build on jdk 14 is failing. is this associated with your change? can you check?
thanks

**Comment by ejba** [comment]
Hi @vsevel, really sorry I didn't see `VaultKubernetesAuthenticationConfig`. I moved the created property there. What do you think?
About the build failures, I can't tell why it's happening. I will trigger the build again.

**Comment by vsevel** [comment]
> really sorry I didn't see VaultKubernetesAuthenticationConfig. I moved the created property there. What do you think?

sounds good. I suggest naming the field `kubernetesAuthMountPath` for consistency reason with `kvSecretEngineMountPath`

can please also update `VaultConfigSource.loadRuntimeConfig()` as discussed before.
thanks

**Comment by ejba** [comment]
@vsevel Sorry, I forgot that part. Already done!

**Comment by ejba** [comment]
@vsevel finally a green light! sorry for keep you waiting!

**Review by vsevel — APPROVED** [review]
@sberyozkin LGTM do you want to have a look?

**Review by gsmet — APPROVED** [review]
Thanks to both of you for this!

**Pull request merged**
