### PR TITLE
Enable the Panache annotation processor in Gradle if it's found on the classpath

### LINKED ISSUE #16596: Quarkus Gradle plugin breaks Gradle incremental compilation
## Describe the bug
After upgrading to Quarkus 1.13.x I've noticed that all modules that use Quarkus plugin are fully rebuilt everytime. That increases our build times. The issue seems to be related to these fixes: https://github.com/quarkusio/quarkus/pull/16214 and https://github.com/quarkusio/quarkus/pull/15365. 

From Gradle logs I get:
```
Task ':server:compileJava' is not up-to-date because:
  Input property 'options.annotationProcessorPath' file /Users/anzes/Downloads/code-with-quarkus/library/build/libs/library-1.0.0-SNAPSHOT.jar has changed.
The input changes require a full rebuild for incremental task ':server:compileJava'.
```

I think that putting whole compile classpath to annotation classpath is in general not a good idea with Gradle, but I might be wrong.

### Expected behavior
Projects are built incrementally.

### Actual behavior
Projects are not built incrementally.

## To Reproduce
Check attached reproducer.
[code-with-quarkus-example.zip](https://github.com/quarkusio/quarkus/files/6327901/code-with-quarkus-example.zip)

1. run ./gradlew compileJava --info -> everything is rebuilt, since it's first compilation
2. run ./gradlew compileJava --info -> nothing is compiled since nothing changed
3. Change String "hello" to "hello1" in LibraryClass.java
4. run ./gradlew compileJava --info -> :library:compileJava is run, :server:compileJava is up-to-date
5. uncomment `id 'io.quarkus'` in server/build.gradle and run ./gradlew compileJava --info two time so compile task are up-to-date
6. Change String "hello1" in LibraryClass.java to  "hello2"
7. run ./gradlew compileJava --info -> :library:compileJava is run and also :server:compileJava with message `The input changes require a full rebuild `
8. Repeat

### Output of `uname -a` or `ver`
MacOS

### Output of `java -version`
Openjdk 11.0.7 2020-04-14

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

Also I noticed that `quarkusGenerateCode` task is not incremental and it's run every time since it does not declare inputs and outputs. But that is unrelated issue :).

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #16596

This PR reverts the compileTask's annotation processor path manipulation and enables the Panache annotation processor if it's found on the classpath instead.

### CODE REVIEW

**Comment by aloubyansky** [comment]
I think it's a lesser evil @glefloch It appears to work. But if you could also verify it, it'd be great.

**Review by glefloch — COMMENTED** [review]
That’s definitely better. I will test it on the reproducer. Shouldn’t we add all quarkus artifacts to avoid missing a new annotation processor?

**Comment by aloubyansky** [comment]
You mean add all quarkus artifacts as annotationProcessors?

**Comment by glefloch** [comment]
Yes but not sure it totally make sense. Do we have a lot of use case that could require annotation processor?

**Comment by aloubyansky** [comment]
No, this is an exception. The convention, afaiu, is to configure them in scripts with `annotationProcessor`. If one day we come up with a better way to enable them implicitly - great, until then it should be the conventional Gradle way.

**Comment by glefloch** [comment]
I just tested it on the repoducer of #15104 but the issue is still present. I think the `compileClasspath` is resolved to late regarding to the `annotationProcessor` configuration.

**Comment by aloubyansky** [comment]
Isn't it a different error now? Not the one reported in the issue but a missing config property?

**Comment by glefloch** [comment]
No I still have the issue about accessing a protected field: 

````
Sep 13, 2021 8:53:41 PM io.quarkus.vertx.http.runtime.QuarkusErrorHandler handle
    ERROR: HTTP Request to /hello failed, error id: 383f2d90-6135-4371-9664-99761a6bb032-1
    org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalAccessError: class org.acme.ExampleResource tried to access protected field org.acme.db.TestEntity.name (org.acme.ExampleResource and org.acme.db.TestEntity are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4803aa2b)
````

Looking at the reproducer, I added this in the `application.properties`:

````
uarkus.mongodb.database=test
````

**Comment by aloubyansky** [comment]
Interesting. It does work on my machine. If I completely remove that code (w/o reverting to the previous fix), the project will fail to build. If I add the change back, it builds.

**Review by glefloch — APPROVED** [review]

**Pull request merged**
