### PR TITLE
Infinispan Service Binding

### LINKED ISSUE #29740: Infinispan client should support Kubernetes Service Binding
### Description

At the moment, Infinispan connection can't be configured with the Kubernetes Service Bindig. 
Support it as other Data Services extensions do right now.

https://quarkus.io/guides/deploying-to-kubernetes#service_binding

### PR DESCRIPTION
**Pull request by karesti**
Implements the Service Binding capability 

Closes #29740

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand is it you who is the most aware about service binding?

**Comment by geoand** [comment]
Indeed!

**Review by geoand — APPROVED** [review]
I can't say much about the Infinispan specific stuff, but the integration looks good

**Comment by wburns** [comment]
Looks fine to me as well from the Infinispan side.

**Pull request merged**
