### PR TITLE
Add a more informative error message when Dockerfile is unavailable during s2i

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@rsvoboda mind giving a try please?

**Comment by rsvoboda** [comment]
Building master with your changes now

**Comment by rsvoboda** [comment]
Now I'm getting:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.081 s
[INFO] Finished at: 2021-03-23T18:08:00+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftPrepareJvmDockerBuild threw an exception: java.lang.IllegalArgumentException: Specified Dockerfile: '/Users/rsvoboda/tmp/getting-started/foo' does not exist.
[ERROR] 	at io.quarkus.container.image.openshift.deployment.ApplyDockerfileToBuildConfigDecorator.<init>(ApplyDockerfileToBuildConfigDecorator.java:22)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftPrepareJvmDockerBuild(OpenshiftProcessor.java:99)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Before I was getting:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.565 s
[INFO] Finished at: 2021-03-23T18:09:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.6.Final:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.RuntimeException: java.io.FileNotFoundException: /Users/rsvoboda/tmp/getting-started/foo (No such file or directory)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.ApplyDockerfileToBuildConfigDecorator.andThenVisit(ApplyDockerfileToBuildConfigDecorator.java:34)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.ApplyDockerfileToBuildConfigDecorator.andThenVisit(ApplyDockerfileToBuildConfigDecorator.java:14)
[ERROR] 	at io.dekorate.kubernetes.decorator.NamedResourceDecorator.andThenVisit(NamedResourceDecorator.java:90)
[ERROR] 	at io.dekorate.kubernetes.decorator.NamedResourceDecorator$ResourceVisitor.visit(NamedResourceDecorator.java:105)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:118)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
[ERROR] 	at io.dekorate.kubernetes.decorator.NamedResourceDecorator.visit(NamedResourceDecorator.java:63)
[ERROR] 	at io.dekorate.kubernetes.decorator.NamedResourceDecorator.visit(NamedResourceDecorator.java:29)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:118)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
[ERROR] 	at io.dekorate.deps.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
[ERROR] 	at io.dekorate.Resources.lambda$generate$3(Resources.java:168)
[ERROR] 	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
[ERROR] 	at io.dekorate.Resources.generate(Resources.java:162)
[ERROR] 	at io.dekorate.Session.generate(Session.java:216)
[ERROR] 	at io.dekorate.Session.close(Session.java:191)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$4(KubernetesProcessor.java:164)
[ERROR] 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:122)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.io.FileNotFoundException: /Users/rsvoboda/tmp/getting-started/foo (No such file or directory)
[ERROR] 	at java.base/java.io.FileInputStream.open0(Native Method)
[ERROR] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[ERROR] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.ApplyDockerfileToBuildConfigDecorator.andThenVisit(ApplyDockerfileToBuildConfigDecorator.java:25)
[ERROR] 	... 34 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Used commands:
```
mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.jvm-dockerfile=foo -Dquarkus-plugin.version=999-SNAPSHOT -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.platform.artifact-id=quarkus-bom

mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.jvm-dockerfile=foo
```

**Review by rsvoboda — APPROVED** [review]

**Comment by geoand** [comment]
Great, thanks 👍

**Pull request merged**
