### PR TITLE
Make fast-jar the default packaging

### PR DESCRIPTION
**Pull request by gsmet**
@geoand here is the PR we talked about.

The commit https://github.com/quarkusio/quarkus/commit/5fc05749fc7d12555c207eb5f43e8a10caa13da3 should go away once `QuarkusProdModeTest` is fixed.

@stuartwdouglas do you remember what the test disabled in f72c880 is supposed to do? It wasn't exactly obvious so I wasn't sure how to tweak it.

Also, once all the issues are fixed, I need to have another look to probably add a couple of non-regression `legacy-jar` tests if needed.

Finally, I decided to have `Dockerfile.jvm` be the fast-jar one, drop the existing one and rename the old jvm to `legacy-jar`. It might be a bit too disruptive so it's open for discussion but I wasn't sure it was a good idea to maintain several identical Dockerfiles to smooth a migration that is disruptive by nature.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@gsmet looks like that was added by @aloubyansky, it appears to test that packaging still works in the presence of a custom maven extension that changes how the maven lifecycle is defined?

**Comment by geoand** [comment]
@aloubyansky it seems like `QuarkusProdModeTest` doesn't work with `fast-jar` because at https://github.com/quarkusio/quarkus/blob/fe0879cfdf0e041ad08458adca94a1970cfa5321/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java#L544 the path to the artifact of `io.quarkus:quarkus-bootstrap-runner` is the `target` directory instead of the jar itself.
I am not sure what the proper fix is for this case, could you please take a look?

**Comment by aloubyansky** [comment]
> @gsmet looks like that was added by @aloubyansky, it appears to test that packaging still works in the presence of a custom maven extension that changes how the maven lifecycle is defined?

It is supposed to test custom packaging type. The artifact's extension is still jar but the artifact packaging type is something else. There was an actual issue about that.

**Comment by aloubyansky** [comment]
BTW, why not simply rename `fast-jar` to `jar` (keeping the `legacy-jar`)?

**Comment by aloubyansky** [comment]
Or is this basically what this is but also keeping `fast-jar` being equivalent to `jar`?

**Comment by geoand** [comment]
> Or is this basically what this is but also keeping `fast-jar` being equivalent to `jar`?

I thought we were going to do that

**Comment by gsmet** [comment]
> Or is this basically what this is but also keeping fast-jar being equivalent to jar?

That's exactly what it does. `jar` is now an alias for `fast-jar`.

**Comment by aloubyansky** [comment]
https://github.com/gsmet/quarkus/pull/40 fixes the QuarkusProdModeTest but @stuartwdouglas should have a look. There is a comment saying the parent-first deps should not appear as classes dirs.
For that not to happen the QuarkusProdModeTest should not enable the workspace discovery (which it does explicitly), that will affect usability though. Since the resolver will be looking for the JARs in the repo and will ignore local changes in the dependencies.

**Comment by stuartwdouglas** [comment]
The fix LGTM, I don't remember the reason for the comment, it may have just been that at the time there were no artifacts that would be affected by this and it only really affects builds in our repo, so I just did not implement it.

**Review by geoand — APPROVED** [review]
Great work!!!

**Pull request merged**
