### PR TITLE
Dev UI: Remove link to prev dev ui

### PR DESCRIPTION
**Pull request by phillip-kruger**
After this we will start remove the prev dev ui

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
`VertxBlockingMutinyTest` seems to be pretty unstable

**Comment by gsmet** [comment]
@cescoffier @DavideD @alesj not sure who is taking care of `com.example.grpc.hibernate.VertxBlockingMutinyTest.shouldAddItems ` but it has been failing for several days pretty often.

**Comment by phillip-kruger** [comment]
This PR is a very small UI only change. @gsmet is it ok to merge with the current CI failures ? Else I can rebase and see if CI pass ?

**Comment by gsmet** [comment]
I think I will disable these failing gRPC tests are they are getting very annoying.

**Comment by phillip-kruger** [comment]
Thanks @gsmet !

**Comment by cescoffier** [comment]
@gsmet yes... it became flaky a few days ago. We need to have a look.

**Pull request merged**
