### PR TITLE
Add JWT and POST body tests

### PR DESCRIPTION
**Pull request by sberyozkin**
Relates to #21571

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi @stuartwdouglas @michalszynkiewicz @gsmet @gastaldi Are you aware of any related updates which may have gone to the `main` branch ?

FYI, I can reproduce the problem reported at #21571 with both `2.4.2.Final` and `2.5.0.Final` - butall works with `999-SNAPSHOT`

**Comment by gastaldi** [comment]
@sberyozkin no idea here.

**Review by gastaldi — APPROVED** [review]

**Comment by sberyozkin** [comment]
Sorry, please ignore - it still fails in a user project even with the snapshot, I tried something else.

So I've no ideas now what is going on - as this PR passes, locally, I've just retried, but fails here
with
```
Caused by: java.lang.NoClassDefFoundError: io/quarkus/jwt/test/User
```
even though it is added as a test class.

What can I do, it is Friday evening :-)

**Comment by sberyozkin** [comment]
I see, `RolesAllowedEndpoint` is used by some other test as well, fixing it now

**Pull request merged**
