### PR TITLE
Workaround Vault IT issue in Java8

### PR DESCRIPTION
**Pull request by cescoffier**
This PR changes the build matrix to run on tests on:

* Java 11 and Java 14
* Java 8 - 252+ without the Vault ITs
* Java 8 - 242 - with the Vault ITs

### CODE REVIEW

**Review by geoand — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
I don't think the test failure has anything to do with the PR, but maybe we should restart the tests just to be on the safe side?

**Comment by cescoffier** [comment]
@geoand I got the tests green on my branch, but let's be safe and restart them.

**Comment by gsmet** [comment]
Thanks for taking care of that one!

**Pull request merged**
