### PR TITLE
Updated Mockito version

### PR DESCRIPTION
**Pull request by marceloverdijk**
Mockito version defined in bom was quite old already, consider using latest Mockito version.

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]
Thanks!

But AFAICS, the latest version on Central seems to be 3.2.4, not 3.2.7.

**Comment by marceloverdijk** [comment]
😳 don't know where I got the `.7` from, updated the PR.

**Comment by gastaldi** [comment]
Thanks! Mind adding it to the dependabot config too? https://github.com/quarkusio/quarkus/blob/master/.dependabot/config.yml

**Comment by marceloverdijk** [comment]
@gastaldi sure, Mockito is now added to the dependabot config as well.

**Review by gastaldi — APPROVED** [review]
Great job!

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks for this!

**Pull request merged**
