### PR TITLE
Fix select distinct projection with Panache

### LINKED ISSUE #29089: Panache project() is not working if used with distinct + case-sensitive HQL query
### Describe the bug

For an entity that has getter defined with camelCase attribute name ie: `myId` executing query:
```java
Data.find("SELECT DISTINCT d.myId FROM Data d", Sort.by("myId"))
        .project(Long.class)
        .list();
```
will result in:
```
Caused by: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: myid of: de.turing85.panache.projection.entity.Data [select distinct new java.lang.Long(d.myid) FROM de.turing85.panache.projection.entity.Data d ORDER BY myId]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:757)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:114)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:349)
        at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:547)
```
The issue is probably here: https://github.com/quarkusio/quarkus/blob/8e4ee686b538e8cb7cbb402ef084ef0925fb83cf/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java#L104

### Expected behavior

Distinct query should work with HQL compliant query.

### Actual behavior

It does not work, an exception is raised.

```
Caused by: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: myid of: de.turing85.panache.projection.entity.Data [select distinct new java.lang.Long(d.myid) FROM de.turing85.panache.projection.entity.Data d ORDER BY myId]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:757)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:114)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:349)
        at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:547)
```

### How to Reproduce?

https://github.com/turing85/quarkus-panache-projection/tree/reanme-id-to-myId

Check this line: https://github.com/turing85/quarkus-panache-projection/blob/reanme-id-to-myId/src/main/java/de/turing85/panache/projection/DataResource.java#L36

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000

### Output of `java -version`

openjdk version "19" 2022-09-20 OpenJDK Runtime Environment Homebrew (build 19) OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/jasminsuljic/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 19, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/19/libexec/openjdk.jdk/Contents/Home Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DavideD**
Fix #29089

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks

**Comment by geoand** [comment]
Does this need to be backported to `2.14` and perhaps `2.13`?

**Comment by loicmathieu** [comment]
@geoand as it's a bug I vote for backporting it

**Comment by geoand** [comment]
CI doesn't seem to like it as `quarkus-integration-test-hibernate-orm-panache` is failing

**Comment by DavideD** [comment]
It should be fixed now. Let's wait until CI agrees.

It's annoying that panache allows stuff like this:
```
find("select ... ", Parameters.with("param1", value), Sort.by("field"))
```

even if it's wrong.

**Comment by loicmathieu** [comment]
@DavideD 

> It's annoying that panache allows stuff like this:
> 
> find("select ... ", Parameters.with("param1", value), Sort.by("field"))
> even if it's wrong.

We can compute the list of entity fields at build time, inject it somewhere and check this list in all calls to Sort and Parameters. This will have a slight memory impact for storing the cache, not a lot, but adding the check in all possible place would be some work.

But is it really worth it ? Such error will pop up at developement time with a clear error message right ?

**Comment by DavideD** [comment]
To clarify, I don't mean that we have to change Panache right now (that's why I haven't created a separate issue for it). 
But we already have classes to specify `Parameters` and `Sort`, so it should be possible to make the API more robust.

**Comment by loicmathieu** [comment]
@DavideD if the error message is not explicit, then I agree we should investiguate to make the API more robust (if the cost is not too high).
Can you open an issue with a reproducer so we can discuss it ?

**Pull request merged**
