### PR TITLE
SmallRye GraphQL - fix minor glitch around EventingService

### PR DESCRIPTION
**Pull request by mkouba**
- add some API dependencies to get rid of a useless warning log message

### CODE REVIEW

**Comment by mkouba** [comment]
Out of curiosity - would the SM GQL bean validation integration work if we enable the relevant `EventingService`?

**Review by phillip-kruger — COMMENTED** [review]
Those are all opt-in. So the user might not want them ? Will Quarkus be clever enough not to include the deps if not used ?

**Comment by phillip-kruger** [comment]
> Out of curiosity - would the SM GQL bean validation integration work if we enable the relevant `EventingService`?

How do you mean ?

**Comment by gsmet** [comment]
I think we should avoid including them and get to the bottom of why we have the warnings.

**Comment by phillip-kruger** [comment]
Possibly the warning is from a test that test some extension that needs the dep but does not have it ?

**Comment by mkouba** [comment]
> I think we should avoid including them and get to the bottom of why we have the warnings.

@gsmet We get the warning because:
1. `smallrye-graphql-cdi` declares several service providers of `io.smallrye.graphql.spi.EventingService`
2. `io.smallrye.graphql.execution.event.EventEmitter` attempts to instantiate all service providers and those that are enabled (via MP config) are used
3. The providers from `smallrye-graphql-cdi` use these APIs but the dependencies have the scope `provided` => we get a `ClassNotFoundException` when the service loader attempts to instantiate the provider.

**Comment by mkouba** [comment]
> Out of curiosity - would the SM GQL bean validation integration work if we enable the relevant EventingService?

> How do you mean ?

@phillip-kruger There is the `io.smallrye.graphql.cdi.validation.ValidationService` provider. If I set `smallrye.graphql.validation.enabled=true` would the BV integration work in quarkus?

**Comment by phillip-kruger** [comment]
> @phillip-kruger There is the `io.smallrye.graphql.cdi.validation.ValidationService` provider. If I set `smallrye.graphql.validation.enabled=true` would the BV integration work in quarkus?

As far as I know yes. BV deps also needs to be present, else you will get the message

**Comment by mkouba** [comment]
> Possibly the warning is from a test that test some extension that needs the dep but does not have it ?

Nope, you'll get a warning whenever you don't include the opentracing API dependency, e.g. when running the quickstart.

**Comment by phillip-kruger** [comment]
Maybe the warning should move to a better place. So we handle the ClassNotFound silent, but if you try and enable opentracing (or any other) we warn if opentracing not available ? Not sure if this is possible ?

**Comment by phillip-kruger** [comment]
> Maybe the warning should move to a better place. So we handle the ClassNotFound silent, but if you try and enable opentracing (or any other) we warn if opentracing not available ? Not sure if this is possible ?

This is not possible at the moment. I guess the right way to fix this is to move the config key up. At the moment the implementation "owns" the config key. So we first have to load the service to see if this is enables. I think I should change to have a key that use convention. Then we can check enable before we load the service. using the service name ? W.d.y.t ? This would be a change in SmallRye.

**Comment by mkouba** [comment]
> Then we can check enable before we load the service. using the service name ?

You would not be able to use the `ServiceLoader` then. You could have a service provider class -> config key mapping but `java.util.ServiceLoader.Provider<S>` which allows to inspect the service provider type is JDK9+.

**Comment by phillip-kruger** [comment]
@mkouba - please see #12783 that supersede this PR.

**Pull request closed without merging**
