### PR TITLE
Always instantiate Hibernate ORM collections in the default fetch group

### LINKED ISSUE #4644: ObjectMapperCustomizer with Hibernate5Module for lazyloading
**Describe the bug**
Jackson ObjectMapperCustomizer not working as expected. 

**Expected behavior**
If the  Hibernate5Module would be set with the Hibernate5Module.Feature.SERIALIZE_IDENTIFIER_FOR_LAZY_NOT_LOADED_OBJECTS feature, i would expect that on every jax-rs endpoint with the jackson module would use the given Objectmapper feature. 
So that lazy loaded relations would shown only as id lists.

**Actual behavior**
Getting Lazyloading execptions.

**To Reproduce**
1. Clone https://github.com/cerias/quarkus-debug-jackson-objectmapper
2. setup database with one entity of TestA and TestB
3. Open /swagger-ui and trigger GET

**Configuration**
```properties
also in the example repo.
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux huffelpuff 5.1.1-050101-generic #201905110631 SMP Sat May 11 06:33:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

 - GraalVM version (if different from Java): 19.0.2
 - Quarkus version or git rev: 0.25

It is also possible im not using the hibernate feature wrong. ;)

### PR DESCRIPTION
**Pull request by yrodiere**
... be it for Hibernate Reactive (as before) or for Hibernate ORM.

Fixes #27657
Fixes #4644 (according to https://github.com/quarkusio/quarkus/discussions/27657#discussioncomment-3580743)

Fixes problems such as https://github.com/quarkusio/quarkus/discussions/27657, where calling a getter to retrieve a collection on an initialized entity would throw a `LazyInitializationException`, whereas one would expect the exception to be thrown later, when accessing the collection itself (`.size()`, `.iterator()`, ...).

This sets defaults as suggested by @gavinking and @Sanne when the option was introduced some time ago: https://github.com/hibernate/hibernate-orm/pull/3558#issuecomment-695003875, https://github.com/hibernate/hibernate-orm/pull/3558#issuecomment-701440788

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Comment by plevart** [comment]
Cool. Is this going to make it into Quarkus 2.12.1 ?

**Comment by yrodiere** [comment]
> Cool. Is this going to make it into Quarkus 2.12.1 ?

I'm not sure that would be wise... It's a rather significant change, and could have a (small) performance impact. @Sanne, any opinion on that?

**Comment by Sanne** [comment]
I'd prefer it to be limited to the next minor but I have no strong opinion.

**Comment by yrodiere** [comment]
FWIW I submitted a PR to make this the default in Hibernate ORM 6.2. I hade to change a few tests though; and that won't become the default in 5.x (which Quarkus currently uses, and will use until we migrate to Jakarta EE).

This is a rather complex situation, so I'll discuss with @gsmet when/where he thinks it would be best to merge this.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
