### PR TITLE
Update to Jandex 2.4.3 and avoid deprecated methods

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
CI passed in my fork, barring one test in "Maven Tests - JDK 11 Windows" which I've seen failing elsewhere and is probably flaky. Rebased and marking as ready for review.

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Thanks for taking the time to adjust the whole codebase. And nice strategy to have a transition version.

**Comment by Ladicek** [comment]
Yea I think/hope/believe this will make the move to 3.0 much smoother and require less coordination. Time will tell though :laughing:

**Comment by gsmet** [comment]
Let's get this in before we end up with a ton of conflicts!

Thanks!

**Comment by gsmet** [comment]
Changing my backport decision for 2.7 as I think it's a bit too late for that, now that RHBQ 2.13 is already out.

**Pull request merged**
