### PR TITLE
VertxRequestHandler cleanup code changes

### PR DESCRIPTION
**Pull request by rsvoboda**
knative.events.VertxRequestHandler
 - Removal of unused local variables
 - Removal of unnecessary casts 

OptaPlannerProcessor changes dropped

### CODE REVIEW

**Comment by geoand** [comment]
cc @ge0ffrey @patriot1burke

**Comment by gsmet** [comment]
`OptaPlannerProcessor` is gone and there is a conflict with the other one.

**Comment by rsvoboda** [comment]
Rebased, updating PR description now

**Comment by rsvoboda** [comment]
Native Tests - Data2 was aborted, timeout - `##[error]The operation was canceled.`

Windows JDK 11 was aborted, timeout - `##[error]The operation was canceled.`

**Comment by ge0ffrey** [comment]
FYI Working with @rsvoboda to apply the cleanups originally in this PR downstream into the optaplanner-quarkus extension: https://github.com/kiegroup/optaplanner/blob/master/optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java#L62

**Comment by gsmet** [comment]
Rebased, let's merge as soon as CI is green.

**Review by machi1990 — APPROVED** [review]

**Pull request merged**
