### PR TITLE
Do not generate Dockerfile.legacy-jar for new projects

### LINKED ISSUE #32948: Drop Dockerfile.legacy-jar from generated applications
### Description

`Dockerfile.legacy-jar` is delivered since Quarkus 1.12 when the default switched to fast-jar in PR https://github.com/quarkusio/quarkus/pull/14753 more than 2 years ago.

I'm not sure we need Dockerfile.legacy-jar in generated applications anymore.

I think it should be OK to remove that artifact from generated applications.

CC @gsmet @geoand @maxandersen @ia3andy 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by nderwin**
* updated the documentation that mentions the file
* removed the code that generates the file
* removed the test code that looks for the generated file
* Fixes #32948

Signed-off-by:Nathan Erwin <nathan.d.erwin@gmail.com>

### CODE REVIEW

**Comment by geoand** [comment]
I personally can't think of a reason to keep it around

**Comment by cescoffier** [comment]
Yea, we can probably drop it on 3.5. 

Should we send an email, and see if someone strongly disagrees.

**Comment by maxandersen** [comment]
Given comments on https://groups.google.com/g/quarkus-dev/c/YaQRSjjkQio/m/2yQVrZKpBgAJ?utm_medium=email&utm_source=footer that legacy jar is needed for certain functions - I reckon we ned to keep it?

**Comment by nderwin** [comment]
@maxandersen I'll go ahead and close this;  https://github.com/quarkusio/quarkus/issues/32948 should probably be updated saying why it won't be done and then closed as well.

**Pull request closed without merging**
