### PR TITLE
[3.8] Update content for support of quarkus-oidc-token-propagation-(reactive) extensions

### PR DESCRIPTION
**Pull request by rolfedh**
Cherry Picked from https://github.com/quarkusio/quarkus/commit/d14c8beb0b0d820a45e439a0f6de61555f573f99
xref: https://github.com/quarkusio/quarkus/pull/41938

### CODE REVIEW

**Comment by sberyozkin** [comment]
@rolfedh Are you going to manage these exclusions at the products docs level ?

**Comment by rolfedh** [comment]
> @rolfedh Are you going to manage these exclusions at the products docs level ?

From what I understand, [@rsvoboda mentioned that these extensions are now Tech Preview in both 3.8 and 3.14](https://github.com/quarkusio/quarkus/pull/41914#issuecomment-2232565681). They also appear as Tech Preview here: https://code.quarkus.redhat.com/?S=com.redhat.quarkus.platform%3A3.8&extension-search=origin:platform%20quarkus-oidc-token-propagation.
Based on our previous team discussions, Tech Preview extensions **are supported**: [3-13-SJ-MA-RS-Copy of QDOCS-660: Supported/unsupported extensions in the upstream>downstream documentation](https://docs.google.com/spreadsheets/d/1T1o4SwZhLG7-KKOxz5KMcEB_2Mwl6hoxcrahC0FWWLY/edit?usp=sharing).
So, it seems like exclusions are no longer necessary on the 3.8 branch. Right?
Best,
Rolfe

**Review by rsvoboda — APPROVED** [review]

**Comment by sberyozkin** [comment]
Thanks for the clarification @rolfedh. LGTM.

**Review by sberyozkin — APPROVED** [review]
LGTM.

@gsmet, please check and merge if it looks good to you

**Comment by rsvoboda** [comment]
Sorry, I merged already ...

**Comment by sberyozkin** [comment]
@rsvoboda OK, thanks for merging, I was not sure I could merge to 3.8

**Comment by rsvoboda** [comment]
I'm on triage call, I can discuss it with Guillaume if he is not happy that I merged this.

**Comment by sberyozkin** [comment]
Sure, I think Guillaume prefers to manage all the backports in general, but as long as he is aware, it should be fine I hope

**Comment by rsvoboda** [comment]
Well, the ideal case is to add `triage/backport-3.8` label on the original PR and it will be cherry-picked during the backports/triage session. NO need to do these individual PRs if the change is applicable to 3.8 stream.

@rolfedh can you set labels on PRs?

**Comment by rolfedh** [comment]
> Well, the ideal case is to add `triage/backport-3.8` label on the original PR and it will be cherry-picked during the backports/triage session. No need to do these individual PRs if the change is applicable to 3.8 stream.
> 
> @rolfedh can you set labels on PRs?

Sure, I can set the labels without any problem. However, I prefer doing the manual cherry-picks because I sometimes encounter merge conflicts or other issues that need inspection. How often does the backports/triage session happen?

**Comment by rolfedh** [comment]
Thank you both for the reviews and merges, @sberyozkin and @rsvoboda!

**Comment by rsvoboda** [comment]
> How often does the backports/triage session happen?

There is no regular cadence, they are usually initiated when RHBQ discussions about the new version appear. With some plans about regular cadence, this shouldn't be an issue going forward. No promises though ;)

**Pull request merged**
