### PR TITLE
Improve how nested MDC scopes are handled in the Jaeger extension

### PR DESCRIPTION
**Pull request by Ladicek**
This is a follow-up to #8746.

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft to let CI run in my fork.

@pavolloffay could you please take a look? Thanks!

**Review by pavolloffay — APPROVED** [review]

**Comment by Ladicek** [comment]
Un-WIP-ing, CI passed in my fork.

**Comment by gsmet** [comment]
Rebased and force pushed, CI went berserk.

**Review by gsmet — APPROVED** [review]
Approved by @pavolloffay

**Pull request merged**
