### PR TITLE
Fix 6754 - Give preference to application's resources during uber jar creation

### LINKED ISSUE #6754: Incorrect resources included in UberJar with multiple dependencies
**Describe the bug**
If you have a pom which pulls in multiple jars (each has some rest services) as well as the Quarkus features, and each individual jar has a src/main/resources/application.properties, then the application.properties from the first dependency is put in the uberjar instead of one on the uberjar project itself

**Expected behavior**
The uberjar projects src/main/resources/application.properties should take precedence and be put in the jar file

**Actual behavior**
The src/main/resources/application.properties from the first dependency is put in the uberjar

**To Reproduce**
git clone https://github.com/bcluap/quarkus.git
cd quarkus/uberjar
mvn install
look in the jar getting-started-uberjar/target/uberjar-runner.jar and see that application.properties is the one from getting-started1 but should be from uberjar

**Configuration**
```properties
maven 3.6.1
Latest Quarkus master

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux PCBLaptop 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
master

**Additional context**

### PR DESCRIPTION
**Pull request by jaikiran**
Fixes https://github.com/quarkusio/quarkus/issues/6754

The commit here fixes the issue reported in https://github.com/quarkusio/quarkus/issues/6754, by introducing a deterministic behaviour of always including the application's resources instead of any duplicated resources from the application's dependencies, during uber jar creation.
The commit also includes a test case to reproduce the issue and verify the fix.

### CODE REVIEW

**Comment by jaikiran** [comment]
Looks like an unrelated failure:

```
2020-01-26T11:47:26.7579453Z [ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 334.111 s <<< FAILURE! - in io.quarkus.maven.it.DevMojoIT
2020-01-26T11:47:26.7579988Z [ERROR] testThatExternalConfigOverridesConfigInJar  Time elapsed: 64.42 s  <<< ERROR!
2020-01-26T11:47:26.7580123Z org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.maven.it.DevMojoIT that uses java.lang.String was not fulfilled within 1 minutes.
2020-01-26T11:47:26.7580483Z 	at io.quarkus.maven.it.DevMojoIT.testThatExternalConfigOverridesConfigInJar(DevMojoIT.java:393)
2020-01-26T11:47:26.7580720Z Caused by: java.util.concurrent.TimeoutException
2020-01-26T11:47:26.7580877Z 	at io.quarkus.maven.it.DevMojoIT.testThatExternalConfigOverridesConfigInJar(DevMojoIT.java:393)
```
Can't reproduce this locally.

**Comment by gsmet** [comment]
@jaikiran could we also check that the jars are fully ordered so that we have a reproducible build?

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
I think this is now overwriting our generated manifest which is why everything is failing.

**Comment by jaikiran** [comment]
@stuartwdouglas, you are right - looking at the code this will need a bit more involved work. I'll reopen this once I have that.

**Pull request closed without merging**
