### PR TITLE
Upgrade GraalVM to 20.1.0

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@galderz the upgrade looks mostly good except for:
```
 [quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]     analysis: 133,881.86 ms,  2.48 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor): 
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:101)
	at sun.security.ssl.TransportContext$NotifyHandshake.run(TransportContext.java:663)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```
in the Kafka native tests.

Did you already fix that one?

**Comment by gsmet** [comment]
@galderz ping?

**Comment by galderz** [comment]
@gsmet Looking, this rings a bell...

**Comment by galderz** [comment]
@gsmet I've not seen this in kafka tests before, but I'll have a look.

**Comment by galderz** [comment]
Kafka issue https://github.com/quarkusio/quarkus/issues/9633.

**Comment by gsmet** [comment]
@galderz your fix works like a charm, thanks!

**Review by Sanne — APPROVED** [review]

**Comment by galderz** [comment]
Camel will directly benefit from the fix, and hopefully others too :)

**Pull request merged**
