### PR TITLE
Prevent usage of @Inject with QuarkusProdModeTest

### PR DESCRIPTION
**Pull request by geoand**
This is done in order to make it explicit to users that such
a construct does not work, instread of having them guess whether
it's their application or the test that is problematic.

An example error looks like this:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in io.quarkus.it.kubernetes.client.AbsentConfigMapPropertiesPMT
[ERROR] io.quarkus.it.kubernetes.client.AbsentConfigMapPropertiesPMT  Time elapsed: 0.006 s  <<< ERROR!
org.junit.platform.commons.JUnitException: @Inject is not supported in QuarkusProdModeTest tests. Offending field is io.quarkus.it.kubernetes.client.AbsentConfigMapPropertiesPMT.kubernetesClient
        at io.quarkus.test.QuarkusProdModeTest.ensureNoInjectAnnotationIsUsed(QuarkusProdModeTest.java:437)

```

### CODE REVIEW

**Comment by geoand** [comment]
cc @metacosm who first encountered this

**Review by metacosm — APPROVED** [review]
LGTM apart from maybe accumulating all offending fields and report them at once (though I guess we can assume that users might be smart enough to fix all instances themselves the first time they encounter this issue)?

**Comment by geoand** [comment]
> LGTM apart from maybe accumulating all offending fields and report them at once (though I guess we can assume that users might be smart enough to fix all instances themselves the first time they encounter this issue)?

Yeah, I think users will get the point with the first error :)

**Review by gastaldi — APPROVED** [review]
Nice!

**Pull request merged**
