### PR TITLE
OpenAPI auto security for OAuth2 opaque token

### LINKED ISSUE #25883: OpenAPI auto security didn't work with OAuth2 opaque token
### Description

Currently, OpenAPI automatically setup security for HTTP basic auth and JWT based authentication.
It should also work with OAuth2 opaque token which support is provided by the  elytron-security-oauth2 extension.

### Implementation ideas

Looking at the JWT support, it may not be hard to tweak it so also support opaque token as there is not a lot of things specific to JWT.

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #25883

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Thanks @loicmathieu . This looks good to me, but I also agree with your suggestion above, so happy if you want to do that. Thanks

**Comment by loicmathieu** [comment]
@phillip-kruger great I'll refactor the code tomorrow

**Comment by loicmathieu** [comment]
@phillip-kruger I refactor the code to share the same security filter can you check again ?

I also notice that there is no documentation about all that, maybe we need to add some that explain how the automatic handling works and what need to be set if we want to customize it ?

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@sberyozkin I would prefer if you could approve this one before merging. Thanks!

**Comment by gsmet** [comment]
@sberyozkin friendly ping ^

**Comment by sberyozkin** [comment]
Oops, sorry everyone :-)

**Review by sberyozkin — APPROVED** [review]
LGTM as well, sorry again for a delay, did not realize I was blocking the merge

**Pull request merged**
