### PR TITLE
K8s Service redeployment

### PR DESCRIPTION
**Pull request by manusa**
Fixes #19701 

Deploy step checks if resource needs to be deleted before creation. In case deletion is needed (KNATIVE or Service, others should be opted-in in the new `shouldDeleteExisting` method), client deletes any existing resource matching Group+Version+Kind+Namespace+Name and waits for its deletion (10 seconds ---> Maybe should add a constant somewhere?)

I'd like to add some tests for this, but I'm not sure where.

/cc @geoand

### CODE REVIEW

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
> I'd like to add some tests for this, but I'm not sure where.
> 

For the time being, we don't have a cluster are part of our upstream CI.

@Sgitario it would be great if you could test this at some point

**Comment by Sgitario** [comment]
> > I'd like to add some tests for this, but I'm not sure where.
> 
> For the time being, we don't have a cluster are part of our upstream CI.
> 
> @Sgitario it would be great if you could test this at some point


> > I'd like to add some tests for this, but I'm not sure where.
> 
> For the time being, we don't have a cluster are part of our upstream CI.
> 
> @Sgitario it would be great if you could test this at some point

This is a good one!  I will add an automated test into our repo https://github.com/quarkus-qe/quarkus-test-suite to reproduce this issue using https://github.com/quarkus-qe/quarkus-test-framework#kubernetes

**Comment by geoand** [comment]
Thanks!

**Comment by gsmet** [comment]
@Sgitario any chance you can validate this one before next Monday? It would be nice to have it in 2.2.2.Final.

**Comment by Sgitario** [comment]
> @Sgitario any chance you can validate this one before next Monday? It would be nice to have it in 2.2.2.Final.

@geoand @gsmet I could not verify the issue at first place: https://github.com/quarkusio/quarkus/issues/19701#issuecomment-910011077

**Comment by geoand** [comment]
So you were able to redeploy the application without problems?

**Comment by Sgitario** [comment]
> So you were able to redeploy the application without problems?

Yes, without the changes from this PR.

**Comment by geoand** [comment]
Weird... I think I was able to reproduce the problem in Minikube

**Comment by manusa** [comment]
> So you were able to redeploy the application without problems?

I did reproduce the issue too (and _obviously_ I verified the fix) in Minikube. It's a common problem that you can easily reproduce even using kubectl with the generated YAMLs (since there is an already allocated node port/IP, the service cannot start).

What I'm not sure if the issue is reproducible in the [1.x LTS version](https://github.com/quarkusio/quarkus/issues/19701#issuecomment-908920075), since in some versions of the client a specific Service handler **might** have taken care of this.

**Comment by Sgitario** [comment]
> Weird... I think I was able to reproduce the problem in Minikube

We use kind and OCP, but not minikube. 
As @manusa said, if he could reproduce it in minikube, then I guess it should be fine.

**Comment by geoand** [comment]
Let's merge this as it clearly fixes a problem and doesn't seem to cause any new ones.

Thanks forlks

**Pull request merged**
