### PR TITLE
Use Stork 2.2.1 fixing an issue about k8s SD refreshing cache

### PR DESCRIPTION
**Pull request by aureamunoz**
cc @cescoffier

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
The test failures seems suspicious

**Comment by aureamunoz** [comment]
> The test failures seems suspicious

looking at it

**Comment by geoand** [comment]
There are a lot of failures, but if you think they are not related, rebase onto main so we can get a new fresh CI run

**Comment by aureamunoz** [comment]
> 

rebase onto main? or 3.2 branch?

**Comment by aureamunoz** [comment]
> Hm... Why the PR done against `3.2` in the first place?

Because it is a bug fix and @gsmet suggested do it this way

**Comment by geoand** [comment]
Is this change already in `main`?

**Comment by aureamunoz** [comment]
> Is this change already in `main`?

Yes

**Comment by geoand** [comment]
Understood, thanks. I'll rerun the tests in that case.

**Pull request merged**
