### PR TITLE
Process @Consumes for ContextResolvers in RESTEasy

### LINKED ISSUE #6974: NullPointerException with mixed media types
When there are different `@Produces`/`@Consumes` media types a `NullPointerException` is returned inside the body of a `400 Bad Request` response. No error/stacktrace in the log.

**Steps to reproduce the behavior:**
1. Use the code from rest-json-quickstart (https://github.com/quarkusio/quarkus-quickstarts/tree/master/rest-json-quickstart) 
2. Add `quarkus-resteasy-jaxb` dependency to the pom
3. Change `FruitResource` to
```java
@Consumes(MediaType.APPLICATION_XML)
@Produces(MediaType.APPLICATION_JSON)
```
4. Add `@XmlRootElement` to `Fruit` 
3. Change `FruitResourceTest.testAdd()` test to send proper XML:
```java
given()
   .body("<fruit><name>Pear</name><description>Winter fruit<description></fruit>")
   .header("Content-Type", MediaType.APPLICATION_XML)
```

**Expected result**: test passes

**Actual result**: test fails with `Expected status code <200> but was <400>`

The actual response is:
```
HTTP/1.1 400 Bad Request
Content-Length: 30
Content-Type: text/html;charset=UTF-8

<html>
  <body>java.lang.NullPointerException</body>
</html>
```

Quarkus version: 1.2.0.Final

### PR DESCRIPTION
**Pull request by ia3andy**
Includes failing reproducer test now succeeding.

Fixes #6974

### CODE REVIEW

**Comment by ia3andy** [comment]
Note that as soon as a `@Produces(MediaType.APPLICATION_XML)` was declared somewhere (even on another method) there were no bug.

**Review by gsmet — APPROVED** [review]
Exactly what I had in mind, thanks for fighting the test case battle :).

**Comment by ia3andy** [comment]
For the sake of quality, I created an upstream issue regarding the NPE:
https://issues.redhat.com/browse/RESTEASY-2489

**Comment by ia3andy** [comment]
and a PR: https://github.com/resteasy/Resteasy/pull/2282

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
