### PR TITLE
Add some useful debugging information to ReflectiveHierarchyBuildItem

### PR DESCRIPTION
**Pull request by gsmet**
@geoand could you have a look to that one?

I spent considerable amount of time debugging the warnings and having the source is definitely very useful.

### CODE REVIEW

**Comment by geoand** [comment]
Sure thing, I'll take a look tomorrow morning

**Review by geoand — APPROVED** [review]
This make a ton of sense!!!

**Comment by geoand** [comment]
CI is failing:

```
2020-06-15T18:17:21.6022032Z [INFO] Running io.quarkus.it.resteasy.jackson.BigKeysResourceTest
2020-06-15T18:17:26.3693093Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.763 s <<< FAILURE! - in io.quarkus.it.resteasy.jackson.BigKeysResourceTest
2020-06-15T18:17:26.3696306Z [ERROR] test  Time elapsed: 0.016 s  <<< ERROR!
2020-06-15T18:17:26.3701890Z java.lang.RuntimeException: 
2020-06-15T18:17:26.3706177Z java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2020-06-15T18:17:26.3706463Z 	[error]: Build step io.quarkus.deployment.steps.ReflectiveHierarchyStep#build threw an exception: java.util.ConcurrentModificationException
2020-06-15T18:17:26.3706652Z 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
```

**Comment by gsmet** [comment]
Ah ah nice... I specifically worked around that when coding but in the end removed the items from the copy... Will fix.

**Comment by gsmet** [comment]
I'm closing this one, I will include the commit here: https://github.com/quarkusio/quarkus/pull/10052 .

**Comment by geoand** [comment]
:+1:

**Pull request closed without merging**
