### PR TITLE
Support mocking PanacheEntityBase.persist static methods

### PR DESCRIPTION
**Pull request by FroMage**
This is the 1.13 version of #16313

### CODE REVIEW

**Comment by FroMage** [comment]
Bogus CI fail:

```
2021-04-28T09:26:24.3177555Z Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.confluent:kafka-avro-serializer:jar:5.5.0 from/to confluent (https://packages.confluent.io/maven/): Transfer failed for https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/5.5.0/kafka-avro-serializer-5.5.0.jar
```

**Comment by FroMage** [comment]
```
2021-04-28T09:47:27.3728901Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1-jboss-1:testCompile (default-testCompile) on project quarkus-integration-test-mongodb-panache: Compilation failure: Compilation failure: 
2021-04-28T09:47:27.3745587Z [ERROR] /home/runner/work/quarkus/quarkus/integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/reactive/ReactiveMongodbPanacheMockingTest.java:[14,37] cannot find symbol
2021-04-28T09:47:27.3752193Z [ERROR]   symbol:   class MongoReplicaSetTestResource
2021-04-28T09:47:27.3758098Z [ERROR]   location: package io.quarkus.it.mongodb.panache
2021-04-28T09:47:27.3773274Z [ERROR] /home/runner/work/quarkus/quarkus/integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/reactive/ReactiveMongodbPanacheMockingTest.java:[24,22] cannot find symbol
2021-04-28T09:47:27.3779656Z [ERROR]   symbol: class MongoReplicaSetTestResource

```

OK this one is real. Lemme see.

**Comment by FroMage** [comment]
Meh, should compile now :)

**Comment by FroMage** [comment]
What's the policy WRT merging on the 1.13 branch @gsmet @geoand? CI passes

**Comment by geoand** [comment]
I dunno TBH, @gsmet ?

I would assume we just merge

**Comment by FroMage** [comment]
I'd be fine, but I noticed you asking @gsmet on at least one other PR so :shrug:

**Comment by edeandrea** [comment]
I certainly appreciate all the help @geoand and @FroMage !

**Comment by edeandrea** [comment]
@gsmet / @FroMage / @geoand any word about merging this into 1.13?

**Comment by geoand** [comment]
Let's merge this in the 1.13 branch.

We can always revert if necessary

**Comment by FroMage** [comment]
Thanks.

**Comment by edeandrea** [comment]
@geoand / @FroMage I noticed that #16182 still shows its on the `2.0.0.Alpha1` milestone. Does that need to be fixed?

I saw that this did not get into the 1.13.4 release. I assume there will be a 1.13.5?

**Comment by geoand** [comment]
Are you sure it's not in 1.13.4?

**Comment by edeandrea** [comment]
Positive. I verified against the list of PRs in the release. Also I upgraded my projects and the tests still fail with the same error.

**Comment by geoand** [comment]
The code does seem to be in the `1.13` branch, so maybe some additional code needed to be backported @FroMage >

**Comment by edeandrea** [comment]
Any updates on this?

**Comment by edeandrea** [comment]
I can verify this now works in `1.13.4`. Was user error - I had to update my mock config & verification

**Pull request merged**
