### PR TITLE
Added effective host and mapped port prop to amqp dev services

### PR DESCRIPTION
**Pull request by garethahealy**
The AMQP dev services currently always resolve's the host to be `localhost`. Thats fine when using `quarkus:dev` or in `@QuarkusTest` but when running a `@QuarkusIntegrationTest` in a container, the app wont be able to connect to the artemis container.

This change attempts to follow what other dev service extensions have done (I.e.: postgres/kafka) via the "sharedNetwork" flag. It also adds another prop so the app within the container resolves the correct port, but the test outside of the container can resolve the mapped port via `DevServicesContext`

I've tested this via my sample project:
- https://github.com/garethahealy/cats-and-dogs/blob/advicewith/src/test/java/com/acme/dogsandcats/main/PetRoutesIT.java#L55

gahealy@rh

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
LGTM - I've pinged @ozangunalp

**Comment by cescoffier** [comment]
We would need to clean up the PR - the update failed.

**Comment by garethahealy** [comment]
rebased which should fix the CI complaint.

**Review by ozangunalp — APPROVED** [review]
LGTM!

**Comment by cescoffier** [comment]
Thanks!

**Pull request merged**
