### PR TITLE
Add OpenTelemetry tracing spans for RESTEasy Reactive clients

### LINKED ISSUE #17800: Distributed tracing for RestEasy Reactive
With RestEasy Classic we can trace the calls with Jaeger, we need the same functionality for RestEasy Reactive, both for server and client (client needs to propagate appropriate headers)

### PR DESCRIPTION
**Pull request by kenfinnigan**
- Fixes #17800
- Remove "hidden" opentelemetry-rest-client extension as it's no longer needed
- Prevent the VertxTracingAdaptor from creating a CLIENT span when REST Client has done it. Check for "traceparent" header in request already
- Fix RESTEasy Reactive client url template path by removing double slash

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@kenfinnigan I'm really happy to see this :)

Could you add some test for Rest Client Reactive?

**Comment by kenfinnigan** [comment]
In the integration tests for RR?

**Comment by michalszynkiewicz** [comment]
I was thinking somewhere in the integration tests in the Quarkus project.

**Comment by kenfinnigan** [comment]
Sorry, that's what I meant. The integration tests for RR in Q

**Comment by kenfinnigan** [comment]
@michalszynkiewicz test added

**Comment by michalszynkiewicz** [comment]
that was fast. I don't know much about opentelemetry but the parts I understand look good to me.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by gsmet** [comment]
@ebullient could you have a look at this one before we wrap 2.1 CR1? It looks like an interesting addition. Thanks!

**Review by ebullient — APPROVED** [review]

**Pull request merged**
