### PR TITLE
[3.2] 3.2.12.final backports 1

### PR DESCRIPTION
**Pull request by aloubyansky**
FYI @rsvoboda @gastaldi @gsmet

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by rsvoboda** [comment]
GAVs of mime4j changed @aloubyansky 
But I think we want that because we want the update version

**Comment by rsvoboda** [comment]
there is also https://mvnrepository.com/artifact/org.apache.james/apache-mime4j/0.8.11

What's exactly motivation for https://github.com/quarkusio/quarkus/pull/40021/commits/0ecb7d09d17372045098183d88294dfa3277e795? I'd rather keep the same GAV for 3.2 LTS not to break any application.

**Comment by aloubyansky** [comment]
Yes, the one that was there before isn't even a JAR.

**Comment by rsvoboda** [comment]
https://repo1.maven.org/maven2/org/apache/james/apache-mime4j/0.8.11/ yup, it's binary distribution, thanks

**Comment by aloubyansky** [comment]
Those that are added are actually dependencies of our extensions, so it's good to align them.

**Review by rsvoboda — APPROVED** [review]
LGTM!

**Pull request merged**
