### PR TITLE
Add MicroProfile LRA TCK

### PR DESCRIPTION
**Pull request by xstefank**

### CODE REVIEW

**Comment by gsmet** [comment]
Also, yes, please make the upgrade a separate commit.

**Comment by xstefank** [comment]
@gsmet no worries, happens. I don't think test failures are related. Can I also ask who is the main quarkus-arquillian master to discuss some improvements of this TCK runs?

**Comment by xstefank** [comment]
@gsmet just resolved conflict, no need to upgrade narayana anymore here. So only adding the LRA TCK run.

**Review by gsmet — APPROVED** [review]
Thanks! My guess is that it will require some efforts to make it work with the Jakarta effort but I will have a look tomorrow.

**Comment by xstefank** [comment]
@gsmet let me know if I can help on that front too.

**Pull request merged**
