### PR TITLE
Fix mutabillity in Stork gRPC channel when fetching Stork services

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
Does this fix a known issue?

**Review by geoand — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
@alesj can you update the title to be a bit more descriptive?

**Comment by alesj** [comment]
@cescoffier title fixed

**Comment by alesj** [comment]
> Does this fix a known issue?

@geoand I stumbled upon it when testing some other stuff ...

**Comment by geoand** [comment]
👍

**Pull request merged**
