### PR TITLE
Don't load remote build analytics config if user has not accepted

### LINKED ISSUE #34626: Quarkus 3.2.0.Final fetching build analytics remote config when disabled
### Describe the bug

Quarkus 3.2.0.Final seems to try to fetch a remote configuration for build analytics, even though build analytics are not enabled and are supposed to be opt-in. 

In addition, the warning is also using the wrong Maven logger or logger level, because we are using the Maven helper plugin in our CI/CD with options "-q –DforceStdout" to fetch project information, and this log line still appears and breaks our job in our internal CI/CD: 

`[warn] [Quarkus build analytics] Analytics remote config not received. java.util.concurrent.TimeoutException: (no message)`

(logging issue is perhaps related to #34166 ?)

In addition, I tried to force disabling the build analytics using the 2 solutions mentioned in the doc:

- JSON File in home/.redhat/io.quarkus.analytics.localconfig
- Maven param -Dquarkus.analytics.disabled=true

but I still have the same problem, so it seems like it is still trying to get a remote config. 

We didn't have this for previous versions of Quarkus, only for 3.2.0.Final

### Expected behavior

Quarkus not fetching anything for build analytics when they are disabled (which should be the default)

### Actual behavior

Quarkus tries to fetch build analytics remote configuration

### How to Reproduce?

Steps to reproduce: 

1. generate quarkus app from https://code.quarkus.io/ using Maven and Quarkus 3.2.0.Final
2. remove file io.quarkus.analytics.remoteconfig from ~home/.redhat
3. disconnect internet connection
4. run `mvn package` , or even `mvn package -q`

-> The log contains this line: 

`[warn] [Quarkus build analytics] Analytics remote config not received. java.util.concurrent.ExecutionException: java.net.ConnectException`

### Output of `uname -a` or `ver`

5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (but also happens in other environments)

### Output of `java -version`

openjdk 17.0.7 2023-04-18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

### Additional information

Note: this may not seem blocking, but the logging issue is blocking our CI/CD completely, because we are using the helper plugin to fetch project identification info, and get a log line instead.

### PR DESCRIPTION
**Pull request by brunobat**
fixes #34626

### CODE REVIEW

**Review by maxandersen — APPROVED** [review]
looks good - I think we still log too much in places (i.e. if segment is not reachable behind firewall) but that can be done in separate PR.

**Comment by brunobat** [comment]
Please merge this as well to fix their build issue: https://github.com/quarkusio/quarkus/pull/34606

**Comment by geoand** [comment]
The CI failures are suspicious

**Comment by brunobat** [comment]
@geoand, I've improved the test resilience with awaitility.

**Comment by brunobat** [comment]
The Windows JDK 17 CI build keeps failing but now for unrelated reasons...
Did another try to make sure.

**Pull request merged**
