### PR TITLE
Fix a few typos in newly added REST Client doc

### PR DESCRIPTION
**Pull request by gsmet**
Plus adjust the key name for better config doc.

### CODE REVIEW

**Comment by gsmet** [comment]
Noticed while preparing the release yesterday.

**Comment by gsmet** [comment]
@geoand BTW, this proxy feature is great, I wonder if it deserves more than just being mentioned in the config doc? Maybe a short paragraph in the doc would help?

**Comment by geoand** [comment]
Yeah, I definitely need to write something!

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
> @geoand BTW, this proxy feature is great, I wonder if it deserves more than just being mentioned in the config doc? Maybe a short paragraph in the doc would help?

[Here](https://github.com/quarkusio/quarkus/pull/42268) it is. Thanks for reminding me of this!

**Pull request merged**
