### PR TITLE
Ignore bridge methods and improve error message in @Embeddable annotation checks

### LINKED ISSUE #36421: Quarkus 3.4.x - Build failure: java.lang.Object is used as an embeddable but does not have an @Embeddable annotation
### Discussed in https://github.com/quarkusio/quarkus/discussions/36368

<div type='discussions-op-text'>

<sup>Originally posted by **jimbogithub** October 10, 2023</sup>
I'm seeing this new build error with Quarkus 3.4.2 (was fine for 3.3.3 and prior):
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: java.lang.IllegalStateException: io.quarkus.builder.BuildException: Build failure: java.lang.Object is used as an embeddable but does not have an @Embeddable annotation.
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:867)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: io.quarkus.builder.BuildException: Build failure: java.lang.Object is used as an embeddable but does not have an @Embeddable annotation.
	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectEmbeddedType(JpaJandexScavenger.java:513)
	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.enlistEmbeddedsAndElementCollections(JpaJandexScavenger.java:323)
	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.discoverModelAndRegisterForReflection(JpaJandexScavenger.java:95)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.defineJpaEntities(HibernateOrmProcessor.java:409)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
```
I can't find any explicit use of `Object` as an embedded type in our JPA models.
Is it possible that https://github.com/quarkusio/quarkus/issues/35598 / https://github.com/quarkusio/quarkus/pull/35822 has caused this?</div>

Looks like the new `@Embeddable` checks are being polluted by abstract super-structure and causing false positives.

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #36421
Addresses https://github.com/quarkusio/quarkus/issues/36421#issuecomment-1780699293

Best reviewed commit by commit.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Looks good, thanks!

And thanks for taking the time to improve the error message, I'm sure users will appreciate.

**Comment by gastaldi** [comment]
Should we backport this to 3.2.x?

**Comment by gsmet** [comment]
I don't remember if I backported this check to 3.2. IIRC I was a bit skeptical.

**Comment by yrodiere** [comment]
> I don't remember if I backported this check to 3.2. IIRC I was a bit skeptical.

Looks like you didn't, it's only in 3.4.0: https://github.com/quarkusio/quarkus/releases?q=35822&expanded=true

**Comment by gsmet** [comment]
Let's backport it for the next 3.5 anyway.

**Comment by yrodiere** [comment]
The test failure seems caused by I/O errors when contacting docker.io. Merging, thanks!

**Pull request merged**
