### PR TITLE
Update extensions file with Kubernetes extension

### LINKED ISSUE #2033: Register kubernetes extension
When running `./mvnw quarkus:list-extensions` you see a lot of extensions but one that is set in guides but not registered is the one about Kubernetes.

`io.quarkus:quarkus-kubernetes`

I am using Quarkus 0.13.1

### PR DESCRIPTION
**Pull request by lordofthejars**
Fixes #2033

### CODE REVIEW

**Review by geoand — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
Merged, thanks!

**Comment by geoand** [comment]
YW!

**Comment by geoand** [comment]
Lol, wrong PR and it's toooo late 😂

**Pull request merged**
