### PR TITLE
CORS content review

### PR DESCRIPTION
**Pull request by MichalMaler**
Creating this PR to separate pure CORS content from the already opened [PR](https://github.com/quarkusio/quarkus/pull/36661/files) that mix the same changes as this PR with some other fixes that got into my cross hair.

This is the docs team follow-up of the @sberyozkin 's PR https://github.com/quarkusio/quarkus/pull/36541/files

This PR already contains SME review of @sberyozkin and @jmartisk .

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Thanks @MichalMaler, @jmartisk, sorry for the hassle with having it opened in a dedicated PR, but hope you'll find it easier to deal with various backport requirements later

**Comment by MichalMaler** [comment]
> Thanks @MichalMaler, @jmartisk, sorry for the hassle with having it opened in a dedicated PR, but hope you'll find it easier to deal with various backport requirements later

Cool. No worries. Please attach the needed labels and feel free to merge :)

**Comment by MichalMaler** [comment]
@rsvoboda Hello Rostislav! Do we want this PR to be backported to 3.2?
Cheers.

**Review by jmartisk — APPROVED** [review]

**Comment by rsvoboda** [comment]
PR look good to me, thanks @MichalMaler 

@sberyozkin there are quite a few changes going on around security guides, they should be probably marked for backport to 3.2 because security guides are planned for downstream. WDYT?

**Pull request merged**
