### PR TITLE
JAX-RS ApplicationPath and Provider are bean defining annotations

### LINKED ISSUE #1880: Make javax.ws.rs.ApplicationPath a bean defining annotation
I'm not quite sure wheter it will be of any use but it would comply with JAX-RS spec requirements.
The corresponding `BeanDefiningAnnotationBuildItem` should be unremovable (default) and have the default scope: `@Singleton` or `@ApplicationScoped`.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #1880

### CODE REVIEW

**Comment by geoand** [comment]
Seems like it needs some import sorting :)

**Review by geoand — APPROVED** [review]
Approved pending the imports being sorted out

**Comment by gastaldi** [comment]
I can confirm that this PR fixes #1927 too

**Comment by gsmet** [comment]
@mkouba I have doubts about this PR but maybe I don't understand everything.

My doubts are about the `@Provider` annotations. If all the providers are made unremovable singleton beans, then our logic to determine which providers are indeed useful and should be included in the native image will be totally useless. Or am I missing something?

**Comment by kenfinnigan** [comment]
I'm wondering if there's confusion between ArC removal of Beans, and native image DCE?

Is this fix purely to stop ArC from removing Beans, or does it impact native image size too?

**Comment by gsmet** [comment]
@kenfinnigan my understanding is that if all the providers are made unremovable CDI beans, they will be included in the native image. Or am I wrong on this?

**Comment by kenfinnigan** [comment]
That's why I was asking, as I'm not sure.

Is there a correlation?

Is it possible that ArC bean removal is separate and distinct from native image DCE?

@mkouba?

**Comment by geoand** [comment]
Good question! My guess is that they are not the same thing but it's a great opportunity for @mkouba to clarify

**Comment by mkouba** [comment]
@kenfinnigan So ArC **bean removal** is a **"framework level DCE"**. Normal DCE does not apply here, because we need hold references of all beans so that we're able to do programmatic lookup (for example `CDI.current().select(Foo.class).get()`).

> my understanding is that if all the providers are made unremovable CDI beans, they will be included in the native image. Or am I wrong on this?

@gsmet Yes, you're right. So in general, any `Provider` that is part of the index will be included in the native image.

**Comment by kenfinnigan** [comment]
Ok, so that's definitely bad then. As we don't want to retain all `Provider` instances.

Is there a way to register the provider classes once RESTEasy Common has found which ones we need? Instead of adding bean definition for everything with `@Provider`?

**Comment by mkouba** [comment]
So is the `ResteasyCommonProcessor` also doing some kind of framework-level DCE? BTW we only make unremovable beans from **indexed** providers that doesn't mean all the providers on the class path.

**Comment by kenfinnigan** [comment]
Yes, as it doesn't include for reflection to substrate any provider classes that aren't used by `@Consumes` or `@Produces` annotations

**Comment by mkouba** [comment]
In that case, the `ResteasyCommonProcessor` should also register additional beans for the providers found. I'll try to update the PR tomorrow.

**Comment by mkouba** [comment]
@gsmet I've updated the PR. @gastaldi Could you pls try it again?

**Comment by gastaldi** [comment]
@mkouba yes, this PR (still) fixes #1927 :smiley:

**Review by gsmet — APPROVED** [review]
Looks good to me.

Let's wait for CI and merge.

**Pull request merged**
