### PR TITLE
refactor: minor cleanups to remove unused imports

### PR DESCRIPTION
**Pull request by machi1990**
When going through the codebase I noticed some unused imports. 
This PR propose a minor cleanups to remove them.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Nice cleanup, let's wait for CI.

**Comment by gsmet** [comment]
The compilation of the Gradle plugin tests fail AFAICS:
```
> Task :compileTestJava FAILED
/home/vsts/work/1/s/devtools/gradle/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java:17: error: cannot find symbol
        assertTrue(project.getPluginManager().hasPlugin("io.quarkus"));
        ^
  symbol:   method assertTrue(boolean)
  location: class QuarkusPluginTest
/home/vsts/work/1/s/devtools/gradle/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java:35: error: cannot find symbol
        assertTrue(tasks.getByName("assemble").getDependsOn().contains(tasks.getByName("quarkusBuild")));
```

**Comment by machi1990** [comment]
> The compilation of the Gradle plugin tests fail AFAICS:
> 
> ```
> > Task :compileTestJava FAILED
> /home/vsts/work/1/s/devtools/gradle/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java:17: error: cannot find symbol
>         assertTrue(project.getPluginManager().hasPlugin("io.quarkus"));
>         ^
>   symbol:   method assertTrue(boolean)
>   location: class QuarkusPluginTest
> /home/vsts/work/1/s/devtools/gradle/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java:35: error: cannot find symbol
>         assertTrue(tasks.getByName("assemble").getDependsOn().contains(tasks.getByName("quarkusBuild")));
> ```

I wonder how IntelliJ could have missed that one up. I'll push a correction soon.

**Comment by dmlloyd** [comment]
That kind of problem can happen on patches like this when an import which was previously unused becomes used by a later commit, but the cleanup is based on an older commit when it was unused.  Both patches merge without (text) conflict, but then when a rebase or merge happens, it becomes a syntax error.

**Comment by machi1990** [comment]
@dmlloyd I think automating it is the way. I could not find the right configuration option to add on `eclipse-format.xml` that's why I went file par file. @mkouba found an interesting config option (thanks :-) ) which I have tried on [remove-unused-imports](https://github.com/machi1990/quarkus/tree/chore-configure-remove-unused-imports). Will open a PR soon.

**Pull request merged**
