### PR TITLE
Make sure GraalVM js artifact is consistent with the SDK version

### PR DESCRIPTION
**Pull request by gsmet**
Related to https://github.com/quarkusio/quarkus-platform/pull/707

### CODE REVIEW

**Comment by ppalaga** [comment]
@gsmet thanks, this makes the life of Camel Quarkus easier in the community, but IIRC, org.graalvm.js:js is not available on Mandrel (cc @zakkak @galderz ). If that's really the case this will make the life of the prod team harder. Note that the js-dsl extension is not supported in CEQ product currently and will hardly be in the future because of the above. @lburgazzoli may want to add his/Camel K perspective.

**Comment by gsmet** [comment]
Pinging @zakkak too.

**Comment by lburgazzoli** [comment]
> Note that the js-dsl extension is not supported in CEQ product currently and will hardly be in the future because of the above. @lburgazzoli may want to add his/Camel K perspective.

I don't think that we will have the js-dsl in the produce any time soon so I'm fine with everything that reduces the maintenance

**Review by geoand — APPROVED** [review]

**Review by zakkak — APPROVED** [review]

**Comment by aloubyansky** [comment]
AFAICS, it's not a problem for prod.

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
@ozangunalp I don't know what's happening with this test lately but it has been extremely unstable. Either we fix it quickly or we need to disable it.

**Comment by ozangunalp** [comment]
@gsmet Thanks for the heads up! I was preparing the fix: #29433

**Pull request merged**
