### PR TITLE
Fixed NPE when a param converter is used

### LINKED ISSUE #40287: Using a custom ParamConverter fails when not sending that parameter with the request
### Describe the bug

When using a custom ParamConverter, the call fails when we do not sending  any value for that parameter in the request.

### Expected behavior

The request would be executed

### Actual behavior

A 404 error happens due to a NPE.

### How to Reproduce?

Take this example code:

```
@GET
    @Path("/greet")
    public Response greet(@QueryParam("number") @Parameter(allowEmptyValue = true) Optional<Integer> numberOpt) {
        if (numberOpt.isPresent()) {
            Integer number= numberOpt.get();
            if (number == null) {
                return Response.ok("Hello! You provided an empty number.").build();
            } else {
                return Response.ok("Hello, " + number+ "!").build();
            }
        } else {
            return Response.ok("Hello, world! No number was provided.").build();
        }
    }
```
    
This is the converter:

```
public class OptionalIntegerParamConverter implements ParamConverter<Optional<Integer>> {

	@Override
    public Optional<Integer> fromString(String value) {
		if (value == null) {
			return null;
		}
		
        if (value.trim().isEmpty()) {
        	return Optional.empty();
        }
        
        try {
        	int parsedInt = Integer.parseInt(value);
        	return Optional.of(parsedInt);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Invalid integer value");
        }
    }
    @Override
    public String toString(Optional<Integer> value) {
    	if (!value.isPresent()) {
    		return null;
    	}
    	
    	Integer intValue = value.get();
        if (intValue == null) {
            return null;
        } else {
            return intValue.toString();
        }
    }

}

}
```
And this is its provider:
```
@Provider
public class OptionalIntegerParamConverterProvider implements ParamConverterProvider {
    @SuppressWarnings("unchecked")
	@Override
    public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType, Annotation[] annotations) {
    	if (rawType.equals(Optional.class)) {
            if (genericType instanceof ParameterizedType) {
                ParameterizedType parameterizedType = (ParameterizedType) genericType;
                Type[] typeArguments = parameterizedType.getActualTypeArguments();
                if (typeArguments.length == 1 && typeArguments[0].equals(Integer.class)) {
                    return (ParamConverter<T>) new OptionalIntegerParamConverter();
                }
            }
        }
        
        return null; // return null if no converter is needed for the type
    }
}
```

If that is setup, then trying to call the service without providing any value to the number parameter will fail within `RuntimeResolvedConverter` 

```
public Object convert(Object parameter) {
        if (runtimeConverter != null)
            return runtimeConverter.fromString(parameter.toString());
        return quarkusConverter.convert(parameter);
    }
```
it fails because parameter is null.

If I provide no conversion, then it fails only when checking the `Send empty value`, since "" cannot be converted to an Optional<Integer>

Thus, a simple change in `RuntimeResolvedConverter` would fix this:
```
public Object convert(Object parameter) {
        if (runtimeConverter != null)
            return runtimeConverter.fromString(parameter != null ? parameter.toString() : null);
        return quarkusConverter.convert(parameter);
    }
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michelcouto**
Occurs when param is not sent in the request.

- Fixes: #40287

### CODE REVIEW

**Review by FroMage — CHANGES_REQUESTED** [review]
I have doubts about this:

- I'm not sure it's useful to make a distinction between not setting a parameter and setting it to an empty value
- I find the possibility of `Optional` being `null` especially confusing, I don't think this is how it's supposed to work. It's not meant to be used as a tri-state value.
- I'm not sure why we have support for `Optional<Integer>` but not the other types. Ideally, we'd support `Optional` parameters for _every_ existing type of registered `ParamConverter`, much like we do for `List`, arrays and other sequence types, no?

I'll defer decitions to @geoand but at least he knows my doubts.

**Comment by michelcouto** [comment]
> I have doubts about this:
> 
> * I'm not sure it's useful to make a distinction between not setting a parameter and setting it to an empty value
> * I find the possibility of `Optional` being `null` especially confusing, I don't think this is how it's supposed to work. It's not meant to be used as a tri-state value.
> * I'm not sure why we have support for `Optional<Integer>` but not the other types. Ideally, we'd support `Optional` parameters for _every_ existing type of registered `ParamConverter`, much like we do for `List`, arrays and other sequence types, no?
> 
> I'll defer decitions to @geoand but at least he knows my doubts.

What is being asked here is not that a distinction between not setting a parameter and setting it to an empty value is useful or not. That is up to someone using the library to decide.
What is being asked here is that when we use a param converter, then sending that parameter in the call is currently mandatory! This shouldn't be the case, as marking it as mandatory is something else.
The use of Optional<Integer> was a TEST only, not related to the actual fix. It could have been any other converter there. I simply used my use case, which is that, but any other converter will have the same issue.

**Review by FroMage — APPROVED** [review]
Oh, sorry, I did not realise this converter ended up in tests, I was pretty sure I checked that.

I apologise, then I have no reservations and indeed this is a good fix.

**Comment by geoand** [comment]
@michelcouto do you plan to update the PR?

**Comment by michelcouto** [comment]
> @michelcouto do you plan to update the PR?

I am sorry but I don't exactly know how to fix the tests...
The actual fix is very straightforward... but the tests I am afraid I don't know how to properly fix them...

So, we either:
1) Remove the tests from the PR
2) Someone fix the tests

**Comment by geoand** [comment]
For starters you'll need to remove the commons logging stuff

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/42434

**Pull request closed without merging**
