### PR TITLE
Support using tars and docker daemon as base image for Jib

### LINKED ISSUE #38320: Support image from local docker daemon for jib build base image
### Description

Jib supports the usage of a local docker base image already since a while: https://github.com/GoogleContainerTools/jib/issues/1468#issuecomment-531373394

It seems that the same does not work when using the quarkus property to point to a local docker image `quarkus.jib.base-native-image=docker://my-customquarkus-native-image:latest`

It would be neat if quarkus would also support this, as we build the base image within the git workflow and would like to omit the push

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Resolves: #38320

### CODE REVIEW

**Comment by geoand** [comment]
Thanks!

**Review by HerrDerb — APPROVED** [review]

**Review by HerrDerb — APPROVED** [review]

**Comment by HerrDerb** [comment]
Sorry, this approvals were unwanted.

**Comment by geoand** [comment]
No problem :)

**Comment by geoand** [comment]
Ah, I was not aware of that. I'll check it out later today.

**Comment by geoand** [comment]
PR updated!

**Review by gastaldi — APPROVED** [review]

**Comment by HerrDerb** [comment]
I guess this also would need to be applied on L789 `createContainerBuilderFromNative` for native builds?

**Comment by geoand** [comment]
The commit already fixes that, no?

**Comment by HerrDerb** [comment]
Yes I've missed the recent push 🙈

**Comment by geoand** [comment]
💪🏼 

Do you want to give it a try on your example use case?

**Comment by HerrDerb** [comment]
Looking good 👍 Thank you very much

**Comment by geoand** [comment]
Thanks for checking!

**Comment by HerrDerb** [comment]
Is it possible to include this in 3.7?

**Comment by gastaldi** [comment]
Yes, it is already marked to be backported to 3.7

**Pull request merged**
