### PR TITLE
Move the Camel extensions outside Quarkus

### LINKED ISSUE #3095: Remove Camel extensions and integration tests
Camel extensions have their new home in https://github.com/apache/camel-quarkus and they can be removed from here once this blocker is fixed: https://github.com/quarkusio/quarkus/issues/3094 

We hope both #3094 and the current issue can be resolved in Quarkus 0.19.0.

cc @lburgazzoli @aloubyansky

### PR DESCRIPTION
**Pull request by ppalaga**
Please merge this only after https://github.com/quarkusio/quarkus/pull/3117

### CODE REVIEW

**Comment by gsmet** [comment]
And please do it after Wednesday's release :).

We need to do that at the start of a development cycle.

BTW, it's a bit unfortunate because this PR will conflict with https://github.com/quarkusio/quarkus/pull/3141 .

Thanks!

**Comment by ppalaga** [comment]
> this PR will conflict with #3141 

Thanks for the headsup, I have no problem to update this PR.

**Comment by gsmet** [comment]
Well, you will have to update this PR and probably the externalized Camel code, unfortunately.

It's not mandatory as the old constructs are still supported but it would be better.

**Comment by kenfinnigan** [comment]
@ppalaga can you rebase the PR?

**Comment by ppalaga** [comment]
Rebased

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
