### PR TITLE
Allow skipping of persistence.xml parsing

### LINKED ISSUE #6805: Support ignoring an existing persistence.xml file
**Description**
It should be possible to skip an existing persistence.xml file, that is contained in a JAR file dependency.

My use case for this is, that I need to import a legacy jar, that unfortunately contains a persistence.xml with unsupported entries. Fortunately I only need the classes from this jar, not the persistence configuration, so ignoring it would help me.

**Implementation ideas**
I see the following possibilities for this:
* add an option to ignore all persistence.xml files, not in the currently build jar.
* add an option to ignore all persistence.xml files contained in specific jars
* add an option to ignore specific persistence units by name
  * The persistence XML files would need to be parsed, and if the unit name matches would be ignored

### PR DESCRIPTION
**Pull request by tisoft**
Fixes #6805

### CODE REVIEW

**Comment by tisoft** [comment]
@Sanne  This is the alternative to the closed PR #10047 

Do you have a suggestion what the system property should be? Currently it is `SKIP_PARSE_PERSISTENCE_XML` and I don't really like that. :smile:

**Comment by tisoft** [comment]
CI failure seems unrelated, the test runs locally.

Would you consider adding this to the 1.5 branch, or is the main branch better suited?

**Comment by geoand** [comment]
> CI failure seems unrelated, the test runs locally.
> 

There seem to be one or two unstable tests lately.

> Would you consider adding this to the 1.5 branch, or is the main branch better suited?

I doubt we will be doing another `1.5.x` release now that `1.5.2` has been released, so `master` is certainly the proper target.

**Review by Sanne — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
