### PR TITLE
Improve ignore rules in reflection hierarchy registration

### PR DESCRIPTION
**Pull request by gsmet**
@geoand this is my proposal for https://github.com/quarkusio/quarkus/pull/4832 

Let's see if native tests pass.

### CODE REVIEW

**Comment by geoand** [comment]
Looks like a nice improvement. Maybe we should let it bake a couple days though before releasing?

**Comment by gsmet** [comment]
Sure I didn't want to merge it right away.

**Comment by geoand** [comment]
:+1: 

This is way more flexible than we already have. I'll close my open PR.

**Comment by gsmet** [comment]
@geoand if you're still in with this approach, could you approve it so that I can merge it? I branched this morning so we are safe.

**Review by geoand — APPROVED** [review]

**Pull request merged**
