### PR TITLE
Fix Quarkus plugin syncing

### LINKED ISSUE #43036: quarkus plug sync no longer removes plugins provided by extensions
### Describe the bug

A CLI plugin that is added because via Quarkus extensions is not removed, even when the extension that added it was removed.

### Expected behavior

The plugin should be removed as soon as the extension is removed.

### Actual behavior

The plugin is not removed.

### How to Reproduce?

In a blank project add an extension that provides a cli plugin (e.g. `helm`), verify that cli plugin is added, then remove the extension and call `quarkus plug sync`.

```sh
quarkus ext add helm
quarkus plug list
quarkus ext remove helm
quarkus plug sync
quarkus plug list
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #43191: quarkus plugin sync is broken
### Describe the bug

The command is broken due to the fact that sync is run indirectly before the actual command runs.
This happens due to regressions in `QuarkusCli` that may trigger sync when `quarkus plug xxx` is run.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
- Resolves: #43036 
- Resolves: #43191

### CODE REVIEW

**Comment by gsmet** [comment]
@iocanel there are early test failures

**Comment by geoand** [comment]
@maxandersen see https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.20TLS.20CLI/near/470963674

**Comment by iocanel** [comment]
@maxandersen: gentle reminder

**Review by gsmet — APPROVED** [review]
Tested and it seems to work as advertised.

**Pull request merged**
