### PR TITLE
Adjusted config for removed resources in the ExtensionDescriptorMojo to have valid XML

### PR DESCRIPTION
**Pull request by aloubyansky**
Follow up to https://github.com/quarkusio/quarkus/pull/26025

Now it looks like
````
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-extension-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>extension-descriptor</goal>
            </goals>
            <configuration>
              <deployment>${project.groupId}:${project.artifactId}-deployment:${project.version}</deployment>
              <removedResources>
                <artifact>
                  <key>org.acme:acme-resources</key>
                  <resources>META-INF/a</resources>
                </artifact>
              </removedResources>
            </configuration>
````

### CODE REVIEW

**Comment by aloubyansky** [comment]
fyi @xstefank

**Comment by aloubyansky** [comment]
@gsmet I marked it for backport, since @xstefank needed it in 1.10.

**Comment by xstefank** [comment]
I don't have a particular use case for backport. However, LRA wouldn't work by default from the release when resteasy-reactive (and thus required reactive REST client) was made default.

**Comment by aloubyansky** [comment]
@xstefank I thought you wanted this feature before June 20. If we are not backporting this PR it's going to end up in 1.11 for which we don't have a schedule yet.

**Comment by gsmet** [comment]
You're talking about 2.10 and 2.11, right? I think we can backport it as it doesn't work very well right now.

**Review by gsmet — APPROVED** [review]

**Comment by aloubyansky** [comment]
Are our Gradle tests unstable lately?

**Comment by aloubyansky** [comment]
I rebased just to see the effect on the CI.

**Comment by xstefank** [comment]
@aloubyansky @gsmet I have an LRA talk next week at DevoxxPL so if we can backport and have a release where I don't need to explain resteasy vs resteasy reactive in the talk that would be great. But if it's too much effort then nothing serious.

**Comment by aloubyansky** [comment]
Here we go :)

**Pull request merged**
