### PR TITLE
Register user configuration sources

### LINKED ISSUE #1871: User configuration sources are not registered
They should be registered along with the system configuration sources for run time.

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #1871

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by geoand** [comment]
Should this be documented perhaps in the configuration guide?

**Comment by dmlloyd** [comment]
Sure, I can add a blurb.

**Comment by dmlloyd** [comment]
Pushed.  @geoand WDYT?

**Comment by geoand** [comment]
@dmlloyd LGTM!

**Comment by cescoffier** [comment]
I know it's annoying, but what about a test?

**Comment by dmlloyd** [comment]
Added tests, found & squashed some other bugs as a result.

**Comment by dmlloyd** [comment]
I'll have to have someone with a Windows system give me a hand with troubleshooting this, next week.

**Comment by starksm64** [comment]
I'll take a look at the failure on windows failure when I get back home.

**Comment by dmlloyd** [comment]
Thanks Scott.

**Comment by dmlloyd** [comment]
I wonder if maybe one of the `relativePath` entries is using `\` separators instead of `/`.

**Comment by dmlloyd** [comment]
Trying one more thing.  Since `Path` instances can exist on any file system with any file separator, just use `toUri().getPath()` instead.

**Comment by dmlloyd** [comment]
Never mind, that was wrong: it seems that `toUri()` always makes the path absolute, unfortunately.

**Comment by dmlloyd** [comment]
Hey looks like that fixed the Windows build!  Cool.

**Pull request merged**
