### PR TITLE
[3.8] Do not record local sources in runtime config defaults

### PR DESCRIPTION
**Pull request by gsmet**
Please don't merge, I will merge it myself.

### CODE REVIEW

**Comment by gsmet** [comment]
Also /cc @jmartisk

**Review by aloubyansky — APPROVED** [review]

**Review by radcortez — APPROVED** [review]

**Review by rsvoboda — COMMENTED** [review]
LGTM!

**Comment by gsmet** [comment]
@rsvoboda they look odd, I pinged @radcortez . I'm going to push the dev service change to this PR and see what CI says.

**Pull request merged**
