### PR TITLE
Fix vale errors and warnings in the OpenID Connect (OIDC) and OAuth2 Client and Filters Reference Guide

### PR DESCRIPTION
**Pull request by rolfedh**
@sberyozkin This is a quality update for `main`.
Do you approve backporting it to `3.2` as well?

Note: Here, I've made minimal changes to fix Vale errors and some warnings.
Related to [QDOCS-536](https://issues.redhat.com/browse/QDOCS-536).

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Thanks @rolfedh.

FYI, to avoid PR titles be stripped of some trailing words and the bot be unhappy the titles should be quite short, and indeed, the description can expand it, so I tried to shorten the title a bit, thanks :+1:

**Comment by rolfedh** [comment]
> the titles should be quite short

Thanks. I didn't realize this was an issue for our tooling. In the future, I'll use short titles and rely on the description to provide fuller information.

**Comment by gsmet** [comment]
Not backporting to 3.5 as doesn't apply cleanly. I will let @aloubyansky judge if he wants to backport that to 3.2 (I removed the label and then readded as it's not my call).

**Comment by michelle-purcell** [comment]
@rolfedh - Removing backport label as this guide is not being published for the 3.2 product doc release. Thanks.

**Pull request merged**
