### PR TITLE
In io.quarkus.jackson.ObjectMapperCustomizer, use JsonMapper.Builder instead of ObjectMapper

### LINKED ISSUE #24019: In io.quarkus.jackson.ObjectMapperCustomizer, use JsonMapper instead of ObjectMapper
### Description

As of 2.10, JsonMapper appears to be the preferred system.

This will require changing the default ObjectMapper producer and change the interface of ObjectMapperCustomizer.

What backward compatibility is required? 

### Implementation ideas

```java
package io.quarkus.jackson;

import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.databind.json.JsonMapper;
import io.quarkus.jackson.runtime.ObjectMapperProducer;
import org.jboss.logging.Logger;

/**
 * Meant to be implemented by a CDI bean that provides arbitrary customization for the default {@link ObjectMapper}.
 * <p>
 * All implementations (that are registered as CDI beans) are taken into account when producing the default
 * {@link ObjectMapper}.
 * <p>
 * See also {@link ObjectMapperProducer#objectMapper}.
 */
public interface ObjectMapperCustomizer extends Comparable<ObjectMapperCustomizer> {

    Logger log = Logger.getLogger(ObjectMapperCustomizer.class);

    int MINIMUM_PRIORITY = Integer.MIN_VALUE;
    // we use this priority to give a chance to other customizers to override serializers / deserializers
    // that might have been added by the modules that Quarkus registers automatically
    // (Jackson will keep the last registered serializer / deserializer for a given type
    // if multiple are registered)
    int QUARKUS_CUSTOMIZER_PRIORITY = MINIMUM_PRIORITY + 100;
    int DEFAULT_PRIORITY = 0;

    /**
     * Customize the ObjectMapper.  By default, does nothing
     * @param objectMapper The ObjectMapper to customize.
     * @deprecated Use {@link #customize(JsonMapper)}
     */
    @Deprecated(since = "")
    default void customize(ObjectMapper objectMapper) {
    }

    /**
     * Customize the JsonMapper
     * @param jsonMapper The JsonMapper to customize.
     */
    default void customize(JsonMapper jsonMapper) {
        log.info("Implement customize(JsonMapper), as customize(ObjectMapper) is deprecated");
    }

    /**
     * Defines the priority that the customizers are applied.
     * A lower integer value means that the customizer will be applied after a customizer with a higher priority
     */
    default int priority() {
        return DEFAULT_PRIORITY;
    }

    default int compareTo(ObjectMapperCustomizer o) {
        return Integer.compare(o.priority(), priority());
    }
}
```

### PR DESCRIPTION
**Pull request by chonton**
Closes #24019

### CODE REVIEW

**Comment by chonton** [comment]
Probably merge conflicts with #23995.  (Are you ready to merge that?)

**Review by gastaldi — CHANGES_REQUESTED** [review]
We can't break compatibility because injecting ObjectMapper is used a lot.

I suggest maintaining the same behavior by deprecating it and introduce the new enhancement

**Comment by gastaldi** [comment]
Also how would that work for non-json content?

**Comment by gsmet** [comment]
Yeah, this is a good start but we need to think about the proper strategy to make that change as we don't want to break all the applications around.

**Comment by chonton** [comment]
These changes should be backwards compatible.  JsonMapper is an ObjectMapper.  There is backwards compatibility for invoking the deprecated ObjectMapperCustomizer(s) provided by non-quarkus managed code.

@gastaldi, what do you mean by non-json content?  Is there current or future support for any other [text mappers](https://github.com/FasterXML/jackson-dataformats-text) such as YamlMapper?  Support for any [binary mappers](https://github.com/FasterXML/jackson-dataformats-binary) such as AvroMapper?

**Comment by gastaldi** [comment]
@chonton I don't think we do that now, but an `ObjectMapperCustomizer` instance could work on any `ObjectMapper` implementation (eg. `YAMLMapper`).

**Comment by chonton** [comment]
When XxxMapper is introduced, is it better to use a single Customizer interface, or specific XxxCustomizer per XxxMapper?

**Comment by gastaldi** [comment]
> When XxxMapper is introduced, is it better to use a single Customizer interface, or specific XxxCustomizer per XxxMapper?

IMHO a single Customizer interface would be easier, as it does not require any code changes when a new ObjectMapper implementation is introduced

**Pull request closed without merging**
