### PR TITLE
Update JWT guide with a list of smallrye-jwt properties

### LINKED ISSUE #2383: Document how to use JWT default groups, custom headers, custom group and sub path/defaults, kid, whitelists, jwk rotation

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #2383.

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi Guillaume @gsmet, it might require some rewording, please suggest if yes :-)

**Comment by gsmet** [comment]
@gastaldi do you have a few cycles to review that one? My hands are more than full.

**Review by gastaldi — APPROVED** [review]
Looks good to me. I haven't verified if the properties really exist in the code base but this documentation looks great. ;)

**Comment by gastaldi** [comment]
@sberyozkin is there a link to the smallrye docs (or website) with more information about these properties?

**Comment by sberyozkin** [comment]
Hi @gastaldi thanks, they are doc-ed starting from [here](https://github.com/smallrye/smallrye-jwt/blob/2.0.12/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L125) and ending https://github.com/smallrye/smallrye-jwt/blob/2.0.12/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L239.

Double check please, I can merge later or please merge once all looks good to you.

Note the only property in that list of properties which is not documented is a [whitelistAlgorithms](https://github.com/smallrye/smallrye-jwt/blob/2.0.12/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L224) becase it will be deprecated as part of the pending PR to do with the support for non RSA keys.

**Comment by gastaldi** [comment]
@sberyozkin thanks, I think this PR is good as is. Let's merge it and see how that goes

**Comment by sberyozkin** [comment]
@gastaldi thanks

**Pull request merged**
