### PR TITLE
Update to Vert.x 3.9.3

### PR DESCRIPTION
**Pull request by cescoffier**
Update Vert.x version to 3.9.3.

Mutiny clients are going to be updated in another PR, as it depends on #11614.

### CODE REVIEW

**Comment by cescoffier** [comment]
@stuartwdouglas there is a tiny change in the error handling. Please have a look.

**Review by mkouba — APPROVED** [review]
Looks good.

**Comment by Sanne** [comment]
Great. FYI @gavinking @DavideD ^

**Comment by gavinking** [comment]
@Sanne we already updated HR

**Comment by Sanne** [comment]
@gavinking ok, so now I can actually update HR in Quarkus ;)  I guess we'll do another release soon.

**Comment by gavinking** [comment]
@Sanne that would be great, but I would sorta like to know what to do with this one first:

https://github.com/hibernate/hibernate-reactive/pull/375

**Pull request merged**
