### PR TITLE
Move Elytron substitutions to specific extension

### LINKED ISSUE #6107: Infinispan has an Elytron security dependency but the WildFly security substitutions are not included
**Describe the bug**
Building sample services that use following quarkus extensions
- quarkus-smallrye-reactive-messaging-kafka
- quarkus-infinispan-client
- quarkus-vertx-web
- quarkus-kogito
- quarkus-resteasy

 in native mode fails with following exceptions

````
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: char[].clone(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing org.wildfly.security.password.interfaces.ClearPassword.createRaw(ClearPassword.java:62)
Call path from entry point to org.wildfly.security.password.interfaces.ClearPassword.createRaw(String, char[]):
	at org.wildfly.security.password.interfaces.ClearPassword.createRaw(ClearPassword.java:60)
	at org.wildfly.security.sasl.plain.PlainSaslServer.evaluateResponse(PlainSaslServer.java:133)
	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.handleSaslToken(SaslServerAuthenticator.java:415)
	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:290)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:173)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:487)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:535)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:298)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:248)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.json.Json. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace:
	at parsing org.wildfly.security.mechanism.oauth2.OAuth2Server.createErrorMessage(OAuth2Server.java:156)
Call path from entry point to org.wildfly.security.mechanism.oauth2.OAuth2Server.createErrorMessage():
	at org.wildfly.security.mechanism.oauth2.OAuth2Server.createErrorMessage(OAuth2Server.java:156)
	at org.wildfly.security.mechanism.oauth2.OAuth2Server.evaluateInitialResponse(OAuth2Server.java:149)
	at org.wildfly.security.sasl.oauth2.OAuth2SaslServer.evaluateMessage(OAuth2SaslServer.java:65)
	at org.wildfly.security.sasl.util.AbstractSaslParticipant.evaluateMessage(AbstractSaslParticipant.java:219)
	at org.wildfly.security.sasl.digest.DigestSaslClient.evaluateChallenge(DigestSaslClient.java:323)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.lambda$evaluateChallenge$3(AuthHandler.java:96)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler$$Lambda$932/1444813663.run(Unknown Source)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:143)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
````

**Expected behavior**
build should finish without errors and produce native executable

**Actual behavior**
native image build fails

**To Reproduce**
1. clone repository https://github.com/mswiderski/kogito-travel-agency-tutorial
2. go into 06-kogito-travel-agency
3. run `man clean package -Pnative`

**Configuration**
everything is in the 06-kogito-travel-agency sample service

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin mswiders-mac 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - GraalVM version (if different from Java): 19.3.0
 - Quarkus version or git rev: 1.1.0.CR1

**Additional context**
maven dependency tree

````
[INFO] ---------------< org.acme.travels:kogito-travel-agency >----------------
[INFO] Building kogito-travel-agency 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ kogito-travel-agency ---
[INFO] org.acme.travels:kogito-travel-agency:jar:1.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-kogito:jar:1.1.0.CR1:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:1.1.0.CR1:compile
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile
[INFO] |  |  +- io.smallrye.config:smallrye-config:jar:1.5.0:compile
[INFO] |  |  |  \- io.smallrye.config:smallrye-config-common:jar:1.5.0:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.4:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.1.0.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.0.0.Final:compile
[INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final:compile
[INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:19.3.0:compile
[INFO] |  |  \- org.wildfly.common:wildfly-common:jar:1.5.0.Final-format-001:compile
[INFO] |  +- io.quarkus:quarkus-resteasy:jar:1.1.0.CR1:compile
[INFO] |  |  \- io.quarkus:quarkus-resteasy-server-common:jar:1.1.0.CR1:compile
[INFO] |  |     +- io.quarkus:quarkus-resteasy-common:jar:1.1.0.CR1:compile
[INFO] |  |     |  +- org.jboss.resteasy:resteasy-core:jar:4.4.1.Final:compile
[INFO] |  |     |  |  +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile
[INFO] |  |     |  |  \- org.jboss.resteasy:resteasy-core-spi:jar:4.4.1.Final:compile
[INFO] |  |     |  \- com.sun.activation:jakarta.activation:jar:1.2.1:compile
[INFO] |  |     \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  +- io.quarkus:quarkus-resteasy-jackson:jar:1.1.0.CR1:compile
[INFO] |  |  +- org.jboss.resteasy:resteasy-jackson2-provider:jar:4.4.1.Final:compile
[INFO] |  |  |  +- org.jboss.resteasy:resteasy-jaxb-provider:jar:4.4.1.Final:compile
[INFO] |  |  |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b01:compile
[INFO] |  |  |  |     +- org.glassfish.jaxb:txw2:jar:2.3.3-b01:compile
[INFO] |  |  |  |     \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.10:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.10:compile
[INFO] |  |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.10:compile
[INFO] |  |  |  \- com.github.fge:json-patch:jar:1.9:compile
[INFO] |  |  |     \- com.github.fge:jackson-coreutils:jar:1.6:compile
[INFO] |  |  |        \- com.github.fge:msg-simple:jar:1.1:compile
[INFO] |  |  |           \- com.github.fge:btf:jar:1.2:compile
[INFO] |  |  \- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
[INFO] |  +- io.quarkus:quarkus-arc:jar:1.1.0.CR1:compile
[INFO] |  |  +- io.quarkus.arc:arc:jar:1.1.0.CR1:compile
[INFO] |  |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.0.1:compile
[INFO] |  +- org.kie.kogito:kogito-api:jar:0.6.0:compile
[INFO] |  |  \- org.kie:kie-dmn-api:jar:7.29.0.Final:compile
[INFO] |  |     \- org.kie:kie-dmn-model:jar:7.29.0.Final:compile
[INFO] |  +- org.kie.kogito:drools-core:jar:0.6.0:compile
[INFO] |  |  +- org.kie.kogito:kogito-internal:jar:0.6.0:compile
[INFO] |  |  +- org.kie.kogito:kogito-services:jar:0.6.0:compile
[INFO] |  |  +- org.kie.kogito:drools-core-reflective:jar:0.6.0:compile
[INFO] |  |  +- org.mvel:mvel2:jar:2.4.4.Final:compile
[INFO] |  |  +- com.thoughtworks.xstream:xstream:jar:1.4.11.1:compile
[INFO] |  |  |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  |  \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java:jar:3.6.1:compile
[INFO] |  +- org.kie.kogito:drools-model-compiler:jar:0.6.0:compile
[INFO] |  |  +- org.kie.kogito:drools-canonical-model:jar:0.6.0:compile
[INFO] |  |  +- org.kie.kogito:drools-compiler:jar:0.6.0:compile
[INFO] |  |  |  +- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO] |  |  |  \- org.eclipse.jdt.core.compiler:ecj:jar:4.6.1:compile
[INFO] |  |  +- com.github.javaparser:javaparser-core:jar:3.13.10:compile
[INFO] |  |  +- org.kie.kogito:drools-mvel-parser:jar:0.6.0:compile
[INFO] |  |  \- org.kie.kogito:drools-mvel-compiler:jar:0.6.0:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  +- org.kie.kogito:drools-core-static:jar:0.6.0:compile
[INFO] |  +- org.kie.kogito:jbpm-flow:jar:0.6.0:compile
[INFO] |  \- org.kie.kogito:kogito-dmn:jar:0.6.0:compile
[INFO] |     \- org.kie:kie-dmn-core:jar:7.29.0.Final:compile
[INFO] |        +- org.kie:kie-dmn-backend:jar:7.29.0.Final:compile
[INFO] |        |  \- org.kie.soup:kie-soup-commons:jar:7.29.0.Final:compile
[INFO] |        +- org.kie:kie-dmn-feel:jar:7.29.0.Final:compile
[INFO] |        |  \- ch.obermuhlner:big-math:jar:2.0.1:compile
[INFO] |        +- org.antlr:antlr4-runtime:jar:4.7.2:compile
[INFO] |        \- org.jpmml:pmml-model:jar:1.4.11:compile
[INFO] |           \- org.jpmml:pmml-agent:jar:1.4.11:compile
[INFO] +- io.quarkus:quarkus-vertx-web:jar:1.1.0.CR1:compile
[INFO] |  +- io.quarkus:quarkus-vertx:jar:1.1.0.CR1:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-core:jar:1.1.0.CR1:compile
[INFO] |  |  +- io.quarkus:quarkus-smallrye-reactive-streams-operators:jar:1.1.0.CR1:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-reactive-streams-operators:jar:1.0.10:compile
[INFO] |  |  |  +- io.smallrye:smallrye-context-propagation-propagators-rxjava2:jar:1.0.11:compile
[INFO] |  |  |  \- io.quarkus:quarkus-smallrye-context-propagation:jar:1.1.0.CR1:compile
[INFO] |  |  |     +- io.smallrye:smallrye-context-propagation:jar:1.0.11:compile
[INFO] |  |  |     |  \- io.smallrye:smallrye-context-propagation-api:jar:1.0.11:compile
[INFO] |  |  |     \- org.jboss.resteasy:resteasy-context-propagation:jar:4.4.1.Final:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-axle-generator:jar:0.0.10:compile
[INFO] |  |  |  +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  |  \- io.vertx:vertx-codegen:jar:3.8.4:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-axle-core:jar:0.0.10:compile
[INFO] |  |  \- io.vertx:vertx-rx-java2:jar:3.8.4:compile
[INFO] |  |     \- io.vertx:vertx-rx-gen:jar:3.8.4:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:1.1.0.CR1:compile
[INFO] |  |  \- io.vertx:vertx-web:jar:3.8.4:compile
[INFO] |  |     +- io.vertx:vertx-web-common:jar:3.8.4:compile
[INFO] |  |     +- io.vertx:vertx-auth-common:jar:3.8.4:compile
[INFO] |  |     \- io.vertx:vertx-bridge-common:jar:3.8.4:compile
[INFO] |  +- io.quarkus.security:quarkus-security:jar:1.0.1.Final:compile
[INFO] |  \- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile
[INFO] |     +- jakarta.el:jakarta.el-api:jar:3.0.3:compile
[INFO] |     \- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile
[INFO] +- org.kie.kogito:monitoring-prometheus-addon:jar:0.6.0:compile
[INFO] |  +- io.prometheus:simpleclient:jar:0.5.0:compile
[INFO] |  \- io.prometheus:simpleclient_common:jar:0.5.0:compile
[INFO] +- io.quarkus:quarkus-infinispan-client:jar:1.1.0.CR1:compile
[INFO] |  +- io.quarkus:quarkus-caffeine:jar:1.1.0.CR1:compile
[INFO] |  |  \- com.github.ben-manes.caffeine:caffeine:jar:2.6.2:compile
[INFO] |  +- io.quarkus:quarkus-netty:jar:1.1.0.CR1:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.1.42.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.42.Final:compile
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.42.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport:jar:4.1.42.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.42.Final:compile
[INFO] |  +- org.wildfly.security:wildfly-elytron-sasl-plain:jar:2.0.0.Alpha4:compile
[INFO] |  |  +- org.wildfly.security:wildfly-elytron-auth-server:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-auth:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-base:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-permission:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-x500:jar:2.0.0.Alpha4:compile
[INFO] |  |  +- org.wildfly.security:wildfly-elytron-credential:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-asn1:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-keystore:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-provider-util:jar:2.0.0.Alpha4:compile
[INFO] |  |  +- org.wildfly.security:wildfly-elytron-sasl:jar:2.0.0.Alpha4:compile
[INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-ssl:jar:2.0.0.Alpha4:compile
[INFO] |  |  \- org.wildfly.security:wildfly-elytron-mechanism:jar:2.0.0.Alpha4:compile
[INFO] |  |     \- org.wildfly.security:wildfly-elytron-http:jar:2.0.0.Alpha4:compile
[INFO] |  +- org.wildfly.security:wildfly-elytron-sasl-digest:jar:2.0.0.Alpha4:compile
[INFO] |  |  +- org.wildfly.security:wildfly-elytron-mechanism-digest:jar:2.0.0.Alpha4:compile
[INFO] |  |  \- org.wildfly.security:wildfly-elytron-util:jar:2.0.0.Alpha4:compile
[INFO] |  +- org.wildfly.security:wildfly-elytron-sasl-external:jar:2.0.0.Alpha4:compile
[INFO] |  +- org.wildfly.security:wildfly-elytron-sasl-oauth2:jar:2.0.0.Alpha4:compile
[INFO] |  |  \- org.wildfly.security:wildfly-elytron-mechanism-oauth2:jar:2.0.0.Alpha4:compile
[INFO] |  +- org.wildfly.security:wildfly-elytron-sasl-scram:jar:2.0.0.Alpha4:compile
[INFO] |  |  \- org.wildfly.security:wildfly-elytron-mechanism-scram:jar:2.0.0.Alpha4:compile
[INFO] |  +- org.infinispan:infinispan-client-hotrod:jar:10.0.0.Final:compile
[INFO] |  |  +- org.infinispan:infinispan-commons:jar:10.0.0.Final:compile
[INFO] |  |  +- io.reactivex.rxjava2:rxjava:jar:2.2.15:compile
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.42.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.42.Final:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- org.infinispan:infinispan-remote-query-client:jar:10.0.0.Final:compile
[INFO] |  +- org.infinispan:infinispan-query-dsl:jar:10.0.0.Final:compile
[INFO] |  \- org.infinispan.protostream:protostream-processor:jar:4.3.0.Final:compile
[INFO] +- org.kie.kogito:infinispan-persistence-addon:jar:0.6.0:compile
[INFO] |  \- org.infinispan.protostream:protostream:jar:4.3.0.Final:compile
[INFO] +- org.kie.kogito:kogito-events-reactive-messaging-addon:jar:0.6.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.10.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile
[INFO] |  +- io.smallrye.reactive:smallrye-reactive-messaging-provider:jar:1.0.8:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.1.2.Final:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  +- org.eclipse.microprofile.reactive.messaging:microprofile-reactive-messaging-api:jar:1.0:compile
[INFO] |  |  +- org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-api:jar:1.0:compile
[INFO] |  |  +- org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-core:jar:1.0:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-reactive-converter-api:jar:1.0.10:compile
[INFO] |  |  +- org.eclipse.microprofile.config:microprofile-config-api:jar:1.3:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.29:compile
[INFO] +- org.drools:drools-decisiontables:jar:7.22.0.Final:compile
[INFO] |  +- org.drools:drools-templates:jar:7.22.0.Final:compile
[INFO] |  +- org.kie:kie-api:jar:7.22.0.Final:compile
[INFO] |  |  \- org.kie.soup:kie-soup-maven-support:jar:7.22.0.Final:compile
[INFO] |  +- org.kie:kie-internal:jar:7.22.0.Final:compile
[INFO] |  +- org.apache.poi:poi-ooxml:jar:3.17:compile
[INFO] |  |  +- org.apache.poi:poi-ooxml-schemas:jar:3.17:compile
[INFO] |  |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] |  |  \- com.github.virtuald:curvesapi:jar:1.04:compile
[INFO] |  +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  \- org.apache.poi:poi:jar:3.17:compile
[INFO] |     +- commons-codec:commons-codec:jar:1.13:compile
[INFO] |     \- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO] +- io.quarkus:quarkus-smallrye-reactive-messaging-kafka:jar:1.1.0.CR1:compile
[INFO] |  +- io.quarkus:quarkus-kafka-client:jar:1.1.0.CR1:compile
[INFO] |  +- io.smallrye.reactive:smallrye-reactive-messaging-kafka:jar:1.0.8:compile
[INFO] |  +- io.quarkus:quarkus-jackson:jar:1.1.0.CR1:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.10:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.10:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.10:compile
[INFO] |  +- org.apache.kafka:kafka-clients:jar:2.2.1:compile
[INFO] |  |  +- com.github.luben:zstd-jni:jar:1.3.8-1:compile
[INFO] |  |  +- org.lz4:lz4-java:jar:1.5.0:compile
[INFO] |  |  \- org.xerial.snappy:snappy-java:jar:1.1.7.2:compile
[INFO] |  +- io.vertx:vertx-kafka-client:jar:3.8.4:compile
[INFO] |  |  +- io.vertx:vertx-core:jar:3.8.4:compile
[INFO] |  |  |  +- io.netty:netty-handler-proxy:jar:4.1.42.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec-socks:jar:4.1.42.Final:compile
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.42.Final:compile
[INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.42.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.42.Final:compile
[INFO] |  |  |  \- io.netty:netty-resolver-dns:jar:4.1.42.Final:compile
[INFO] |  |  |     \- io.netty:netty-codec-dns:jar:4.1.42.Final:compile
[INFO] |  |  \- org.apache.kafka:kafka_2.12:jar:2.2.1:compile
[INFO] |  |     +- net.sf.jopt-simple:jopt-simple:jar:5.0.4:compile
[INFO] |  |     +- com.yammer.metrics:metrics-core:jar:2.2.0:compile
[INFO] |  |     +- com.typesafe.scala-logging:scala-logging_2.12:jar:3.9.0:compile
[INFO] |  |     \- org.apache.zookeeper:zookeeper:jar:3.4.14:compile
[INFO] |  |        +- com.github.spotbugs:spotbugs-annotations:jar:3.1.9:compile
[INFO] |  |        \- org.apache.yetus:audience-annotations:jar:0.5.0:compile
[INFO] |  \- io.quarkus:quarkus-smallrye-reactive-messaging:jar:1.1.0.CR1:compile
[INFO] +- io.quarkus:quarkus-junit5:jar:1.1.0.CR1:test
[INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:1.1.0.CR1:test
[INFO] |  |  +- com.google.guava:guava:jar:27.0.1-jre:compile
[INFO] |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  |  +- org.checkerframework:checker-qual:jar:2.5.2:compile
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO] |  |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] |  |  +- org.apache.maven:maven-embedder:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven:maven-settings:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven:maven-core:jar:3.5.4:test
[INFO] |  |  |  |  \- org.apache.maven:maven-artifact:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven:maven-model:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven:maven-model-builder:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven:maven-builder-support:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.1.1:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.1.1:test
[INFO] |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.2.1:test
[INFO] |  |  |  |  \- commons-io:commons-io:jar:2.6:test
[INFO] |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.0:test
[INFO] |  |  |  |  \- aopalliance:aopalliance:jar:1.0:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-utils:jar:3.0.24:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:test
[INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:test
[INFO] |  |  |  \- commons-cli:commons-cli:jar:1.4:test
[INFO] |  |  +- org.apache.maven:maven-settings-builder:jar:3.5.4:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.24:test
[INFO] |  |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:test
[INFO] |  |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:test
[INFO] |  |  +- org.apache.maven:maven-resolver-provider:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.5.4:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.1.1:test
[INFO] |  |  |  \- org.apache.maven.resolver:maven-resolver-impl:jar:1.1.1:test
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.1.1:test
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.1.1:test
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.0.0:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-http:jar:3.0.0:test
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-http-shared:jar:3.0.0:test
[INFO] |  |  |     \- org.jsoup:jsoup:jar:1.7.2:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-file:jar:3.0.0:test
[INFO] |  |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:test
[INFO] |  +- io.quarkus:quarkus-test-common:jar:1.1.0.CR1:test
[INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:1.1.0.CR1:test
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo:jar:1.0.0.Final:test
[INFO] |  |  |  |  \- org.ow2.asm:asm-util:jar:7.1:test
[INFO] |  |  |  |     +- org.ow2.asm:asm-tree:jar:7.1:test
[INFO] |  |  |  |     \- org.ow2.asm:asm-analysis:jar:7.1:test
[INFO] |  |  |  +- org.ow2.asm:asm:jar:7.1:test
[INFO] |  |  |  \- io.quarkus:quarkus-builder:jar:1.1.0.CR1:test
[INFO] |  |  \- io.quarkus:quarkus-jsonp-deployment:jar:1.1.0.CR1:test
[INFO] |  |     \- io.quarkus:quarkus-jsonp:jar:1.1.0.CR1:test
[INFO] |  |        \- org.glassfish:jakarta.json:jar:1.1.6:test
[INFO] |  \- org.junit.jupiter:junit-jupiter:jar:5.5.2:test
[INFO] |     +- org.junit.jupiter:junit-jupiter-api:jar:5.5.2:test
[INFO] |     |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |     |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |     |  \- org.junit.platform:junit-platform-commons:jar:1.5.2:test
[INFO] |     +- org.junit.jupiter:junit-jupiter-params:jar:5.5.2:test
[INFO] |     \- org.junit.jupiter:junit-jupiter-engine:jar:5.5.2:test
[INFO] |        \- org.junit.platform:junit-platform-engine:jar:1.5.2:test
[INFO] +- io.rest-assured:rest-assured:jar:4.1.2:test
[INFO] |  +- org.codehaus.groovy:groovy:jar:2.5.8:test
[INFO] |  +- org.codehaus.groovy:groovy-xml:jar:2.5.8:test
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.10:test
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.12:test
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.3:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.1:test
[INFO] |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
[INFO] |  +- io.rest-assured:json-path:jar:4.1.2:test
[INFO] |  |  +- org.codehaus.groovy:groovy-json:jar:2.5.8:test
[INFO] |  |  \- io.rest-assured:rest-assured-common:jar:4.1.2:test
[INFO] |  \- io.rest-assured:xml-path:jar:4.1.2:test
[INFO] |     +- javax.xml.bind:jaxb-api:jar:2.3.1:test
[INFO] |     \- org.apache.sling:org.apache.sling.javax.activation:jar:0.1.0:test
[INFO] \- io.quarkus:quarkus-smallrye-openapi:jar:1.1.0.CR1:compile
[INFO]    +- io.smallrye:smallrye-open-api:jar:1.1.20:compile
[INFO]    |  +- org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:1.1.2:compile
[INFO]    |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.10:compile
[INFO]    |  |  \- org.yaml:snakeyaml:jar:1.23:compile
[INFO]    |  \- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:compile
[INFO]    \- io.quarkus:quarkus-swagger-ui:jar:1.1.0.CR1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.010 s
[INFO] Finished at: 2019-12-11T15:28:57+01:00
[INFO] ------------------------------------------------------------------------
````

### PR DESCRIPTION
**Pull request by gsmet**
I also added a missing dependency to Infinispan Client.

With this, I think we should be covered.

I went the full extension route, because I thought we might have to add deployment tweaks later.

/cc @stuartwdouglas - this is what we discussed the other day.

Fixes #6107

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Does this actually need to be an extension, I think it is just substitutions so it could just be a normal maven module?

**Comment by gsmet** [comment]
I made it an extension because I suspect we might need to add some more stuff in the future that would require some build steps.

**Comment by gsmet** [comment]
@stuartwdouglas should I adjust or does my answer convince you somehow? I'd like to get that one into 1.1 so I need to know if I have to adjust it.

**Review by geoand — APPROVED** [review]
I agree with having this as an extension in order to be more flexible if need be

**Comment by gsmet** [comment]
Merging, we can tweak it in master if Stuart really wants a simple dependency.

**Comment by stuartwdouglas** [comment]
The extension makes sense.

**Pull request merged**
