### PR TITLE
Fix restore happening in the same thread

### PR DESCRIPTION
**Pull request by rvansa**
When the restore is performed from the same thread, creating Vert.x HttpServer results in it being registered under the same `io.vertx.core.Context` (cached in a thread-local). That way the Netty eventloop is also the same and the requests are not balanced across threads - causing performance regression as request handling becomes effectively single-threaded.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this.

I'd also like @franz1981's opinion

**Review by franz1981 — CHANGES_REQUESTED** [review]
LGTM, just comment it so it won't be lost; this is not the Vertx core codebase and we need any reader to grasp it at first look.
Ideally a test or an assert check is welcome 😁


For myself of the future as well: https://github.com/eclipse-vertx/vert.x/blob/4.4.6/src/main/java/io/vertx/core/net/impl/TCPServerBase.java#L162

The thread which bind the server is the one which can inject its cached context

**Review by cescoffier — APPROVED** [review]

**Review by franz1981 — APPROVED** [review]
Thanks @rvansa !

**Review by geoand — APPROVED** [review]

**Comment by rvansa** [comment]
Thanks @franz1981, I've added the comment and one assertion. A full test executing this code would require a bit more code to setup some sort of CRaC mock.

**Comment by franz1981** [comment]
np @rvansa even a simple `assert` right after listen would work, but is not necessary per-se, given that I don't expect this impl detail of vertx to change in the future

**Comment by rvansa** [comment]
I think that the CI test failure has nothing to do with this PR.

**Comment by geoand** [comment]
Can you rebase on main please?

**Comment by geoand** [comment]
Can you rebase on main please?

**Comment by rvansa** [comment]
@geoand Rebased, and checks are green.

**Pull request merged**
