### PR TITLE
JUnit 5 version should match in ArC too

### PR DESCRIPTION
**Pull request by gastaldi**
Follow-up to https://github.com/quarkusio/quarkus/pull/12096

Using the BOM is necessary so Dependabot can update properly

### CODE REVIEW

**Comment by mkouba** [comment]
Shouldn't we also upgrade the JUnit version to 5.7.0?

**Comment by geoand** [comment]
It's a little to new I would say :P

Maybe we wait a couple weeks?

**Comment by mkouba** [comment]
@geoand But https://github.com/quarkusio/quarkus/pull/12096 was already merged ;-)

**Comment by geoand** [comment]
:(

**Comment by gastaldi** [comment]
> Shouldn't we also upgrade the JUnit version to 5.7.0?

Doh, I made the PR before merging the JUnit bump. It should be OK now. Sorry for the noise :)

**Review by manovotn — APPROVED** [review]

**Review by mkouba — APPROVED** [review]

**Pull request merged**
