### PR TITLE
Reinitialize com.sun.management.internal.PlatformMBeanProviderImpl

### LINKED ISSUE #25501: Ecosystem CI for Google Cloud Services fails with Quarkus main
### Describe the bug

The Quarkiverse extension Google Cloud Services fails to runs the ecosystem CI due to an issue to build a native image with the current Quarkus main.

See the failing build: https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/2304956797

### Expected behavior

Eciosystem CI build is OK

### Actual behavior

It fails with

```
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a PlatformManagedObject (a MXBean defined by the virtual machine) in the image heap. This bean is introspecting the VM that runs the image builder, i.e., a VM instance that is no longer available at image runtime. Class of disallowed object: com.sun.management.internal.HotSpotDiagnostic  Object has been initialized by the com.oracle.svm.hosted.jfr.JfrFeature class initializer with a trace: 
 	at com.sun.management.internal.HotSpotDiagnostic.<init>(HotSpotDiagnostic.java:42)
	at com.sun.management.internal.PlatformMBeanProviderImpl.getDiagnosticMXBean(PlatformMBeanProviderImpl.java:274)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.oracle.svm.hosted.jfr.JfrFeature.getDiagnosticBean(JfrFeature.java:154)
	at com.oracle.svm.hosted.jfr.JfrFeature.<clinit>(JfrFeature.java:125)
. Try to avoid initializing the class that stores the object in a static field The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
	at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a PlatformManagedObject (a MXBean defined by the virtual machine) in the image heap. This bean is introspecting the VM that runs the image builder, i.e., a VM instance that is no longer available at image runtime. Class of disallowed object: com.sun.management.internal.HotSpotDiagnostic  Object has been initialized by the com.oracle.svm.hosted.jfr.JfrFeature class initializer with a trace: 
 	at com.sun.management.internal.HotSpotDiagnostic.<init>(HotSpotDiagnostic.java:42)
	at com.sun.management.internal.PlatformMBeanProviderImpl.getDiagnosticMXBean(PlatformMBeanProviderImpl.java:274)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.oracle.svm.hosted.jfr.JfrFeature.getDiagnosticBean(JfrFeature.java:154)
	at com.oracle.svm.hosted.jfr.JfrFeature.<clinit>(JfrFeature.java:125)
. Try to avoid initializing the class that stores the object in a static field The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
	at com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.error(DisallowedImageHeapObjectFeature.java:173)
	at com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.checkDisallowedMBeanObjects(DisallowedImageHeapObjectFeature.java:162)
	at com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.replacer(DisallowedImageHeapObjectFeature.java:119)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:582)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
	at com.oracle.svm.hosted.heap.SVMImageHeapScanner.transformFieldValue(SVMImageHeapScanner.java:126)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.onFieldValueReachable(ImageHeapScanner.java:331)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.onFieldValueReachable(ImageHeapScanner.java:310)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$computeTypeData$1(ImageHeapScanner.java:153)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 10 more
```

### How to Reproduce?

This can be reproduced using the integration test of the extension pack.

Fork the repository: https://github.com/quarkiverse/quarkus-google-cloud-services
Update the pom.xml to use Quarkus version 999-SNAPSHOT
Build everything: `mvn clean install -DskipTests`
Build the native executable the main integration test : 
```
cd integration-test/main
mvn clean package -DskipTests -Pnative
```

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

11

### GraalVM version (if different from Java)

22.1

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8

### Additional information

The repo uses a Google provided native image support library: https://github.com/GoogleCloudPlatform/native-image-support-java

### PR DESCRIPTION
**Pull request by zakkak**
Work around https://github.com/quarkusio/quarkus/issues/25501 until
https://github.com/oracle/graal/issues/4543 gets resolved

Fixes #25501

### CODE REVIEW

**Comment by zakkak** [comment]
@jiekang can you please have a look at this PR and verify that this reinitialization won't cause any JFR breakage? Thanks

**Review by loicmathieu — APPROVED** [review]
Thanks.
Are you sure the issue is only for gRPC based application ? Shouldn't this be on core-deployment instead ?
I can try this branch tomorrow afternoon to confirm it on GCP services if you didn't already did it.

**Comment by jiekang** [comment]
> @jiekang can you please have a look at this PR and verify that this reinitialization won't cause any JFR breakage? Thanks

@zhengyu123 ^ any chance you have cycles for this?

**Comment by zakkak** [comment]
> Are you sure the issue is only for gRPC based application ? 

It's certainly not, but I don't really understand why it only pops up with gRPC.

> Shouldn't this be on core-deployment instead ?

Not sure, I 'll leave that to the Quarkus team :)

> I can try this branch tomorrow afternoon to confirm it on GCP services if you didn't already did it.

:+1: I only tried it with the reproducer from https://github.com/quarkusio/quarkus/issues/25501

**Comment by geoand** [comment]
> >  Shouldn't this be on core-deployment instead ?

> Not sure, I 'll leave that to the Quarkus team :)

I think it should be part of the core

**Comment by zakkak** [comment]
> I think it should be part of the core

Done

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by loicmathieu** [comment]
They fix it at Google library side, see https://github.com/GoogleCloudPlatform/native-image-support-java/pull/395
If the issue occurs on other gRPC base extension it will not fix it for them as the Google native-image-support library is not integrated inside our gRPC support but inside the Google Services extension pack.

I hope they will do a release soon.

**Comment by zhengyu123** [comment]
> > @jiekang can you please have a look at this PR and verify that this reinitialization won't cause any JFR breakage? Thanks
> 
> @zhengyu123 ^ any chance you have cycles for this?

I don't see any problems.

-Zhengyu

**Comment by zakkak** [comment]
> If the issue occurs on other gRPC base extension it will not fix it for them as the Google native-image-support library is not integrated inside our gRPC support but inside the Google Services extension pack.

To my understanding the issue itself is caused by the Google native-image-support library. If you look at [the patch](https://github.com/GoogleCloudPlatform/native-image-support-java/pull/395/files) what it does is to remove some registrations for reflection, as a result if other extensions don't do similar registrations things should be fine.

**Comment by geoand** [comment]
Yeah, that makes sense to me

**Pull request closed without merging**
