### PR TITLE
Remove synthetic flag for created acessor methods in Panache

### LINKED ISSUE #6641: Panache entites are not marked as dirty after deserialization with Jackson
**Describe the bug**
Using Jackson for JSON-Deserializiation Panache entities (w/out explicit setters) is problematic because generated getters & setters are marked "synthetic" by Quarkus and Jackson skips synthetic methods, i.e. it uses just the public fields. But that means that Hibernate's dirty tracking is bypassed and the (changed) entities are not persisted.

**Expected behavior**
Panache entity is persistable (aka. dirty) after deserialization with Jackson.

**Actual behavior**
Panache entity is not marked as dirty after deserialization with Jackson.

**To Reproduce**
1. Use Jackson for JSON handling
2. Deserialize a Panache entity w/out explicit getters & setters
3. Try to persist this entity

**Solution**
As discussed with @FroMage on the chat, the synthetic flag should be removed to make this work as it is not relevant for any (known) use case right now (see getter & setter generation in PanacheEntityEnhancer).

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #6641

### CODE REVIEW

**Comment by geoand** [comment]
I think an integration test failing without this PR would also be nice :)

**Review by FroMage — CHANGES_REQUESTED** [review]
I think only accessors should have the synthetic bit removed, not the other methods.

**Comment by FroMage** [comment]
Well, I think you deleted the change for mongodb-panache accessors too, and even though they don't have a hibernate bug to workaround, so their accessors are not as significant, I support they should drop the synthetic bit as well just to be consistent. WDYT @loicmathieu ?

**Comment by loicmathieu** [comment]
@FroMage yes, better keep consistent both Panache implementations

**Comment by gastaldi** [comment]
Ah crap, I reverted too much. Let me add it back

**Comment by gastaldi** [comment]
Hm, actually I reverted the RepositoryEnhancer changes, I don't think we need those, right?

**Comment by FroMage** [comment]
Oh, my bad, this is used by both variants.

**Review by FroMage — APPROVED** [review]

**Pull request merged**
