### PR TITLE
Enable monitoring flag is only available from GraalVM 22.3 onwards

### LINKED ISSUE #37825: Add heap dump monitoring only when using a GraalVM version that supports it
### Describe the bug

Currently the minimum GraalVM version needed for Quarkus is 22.2.0, but this version didn't include heap dump monitoring. In #35729 we added this option by default, but native builds fail when using a GraalVM version before 23.1.0. E.g.

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GRAALVM 22.2.0 JDK 17.0.4+8-jvmci-22.2-b06
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=GB -J-Dfile.encoding=UTF-8 --features=io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature,io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature,org.hibernate.graalvm.internal.GraalVMStaticFeature,io.quarkus.runner.Feature,io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https --enable-monitoring=heapdump -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json code-with-quarkus-1.0.0-SNAPSHOT-runner -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
Error: Unrecognized option: --enable-monitoring=heapdump
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by galderz**
Fixes #37825

### CODE REVIEW

**Comment by gsmet** [comment]
@zakkak do we still support 22.2 in recent versions? I thought we moved away from it but it might be me misremembering.

**Comment by galderz** [comment]
@gsmet If we don't support 22.2 any more, we should up the minimum version. Right now there's nothing stopping people using it.

**Review by zakkak — APPROVED** [review]
LGTM, but is probably not worth merging. 22.2 is not supported since Oct 2022, we should better up the minimum supported version as discussed in the comments.

**Comment by gsmet** [comment]
@galderz where did you see we still support 22.2?

**Comment by zakkak** [comment]
> @galderz where did you see we still support 22.2?

@gsmet see

https://github.com/quarkusio/quarkus/blob/519b3ea3f3d9992d1356ddbc9329fb97cd881007/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java#L159

This is used to let users know if they are using an unsupported version or not. Right now using 22.2 doesn't show any warnings/errors.

**Comment by galderz** [comment]
> LGTM, but is probably not worth merging. 22.2 is not supported till Oct 2022, we should better up the minimum supported version as discussed in the comments.

Fair enough. Feel free to close this and send a new PR updating minimum GraalVM version when agreed.

**Pull request closed without merging**
