### PR TITLE
Add Caffeine cache implementations required by users

### LINKED ISSUE #10420: Caffeine error at runtime when using native build
**Describe the bug**
```
"causedBy": {
--
  | "exception": {
  | "refId": 5,
  | "exceptionType": "java.lang.ClassNotFoundException",
  | "message": "com.github.benmanes.caffeine.cache.SSMSW",
  | "frames": [
  | {
  | "class": "com.oracle.svm.core.hub.ClassForNameSupport",
  | "method": "forName",
  | "line": 60
  | },
  | {
  | "class": "java.lang.ClassLoader",
  | "method": "loadClass",
  | "line": 160
  | },
  | {
  | "class": "com.github.benmanes.caffeine.cache.LocalCacheFactory",
  | "method": "newBoundedLocalCache",
  | "line": 95
  | },
```

**Expected behavior**
Should be working in Native build

**Actual behavior**
Only works on JVM build and local dev.
Build native is successful, but at runtime it triggers an error

**To Reproduce**
1. Error when a code is hit with caffeine implementation at runtime
2. No problem with JVM build and local dev runtime

**Environment (please complete the following information):**
Quarkus 1.5.2.Final
GraalVM 20.1.0

### PR DESCRIPTION
**Pull request by gsmet**
Conservatively fixes #10420

Reverts https://github.com/quarkusio/quarkus/issues/12961

See https://github.com/quarkusio/quarkus/issues/12961

### CODE REVIEW

**Comment by Sanne** [comment]
wow that's a lot of space. Wondering if someone would want to explore the reason? cc/ @galderz @n1hility

**Review by Sanne — APPROVED** [review]

**Comment by gsmet** [comment]
Well, it's just because it includes A TON of classes and then you have all the counterpart classes used to register reflection for each class.

FTR, that's 522 more classes just for Caffeine and then you must have approximately the same number of classes for reflection registration.

**Comment by Sanne** [comment]
yes I understand but they are all rather simple simple / very similar. Ok I probably overreacted as I guess it might be reasonable and not too interesting - it just sounds a bit much for the code it is.

**Pull request merged**
