### PR TITLE
Add ability to produce overridable build items

### LINKED ISSUE #4270: Enhanced conditional BuildStep
The `BuildStep` annotation supports simple conditions `onlyIn/onlyIfNot` that one can implement using a `BooleanSupplier` but in some cases it would be nice to have support for more enhanced construct.

In my specific case I have a core extension with a `BuildStep` that should provide the default instance for a given interface and a number of extensions that can provide specialized implementations for that.

I've actually solved the issue by using an `MultiBuildItem` and depending on number of instances found, I do instantiate the default implementation, get the first one that is found or throw an exception in case of multiple instances being found.

This solution works fine but as it seems to me a common pattern it would be nice if it could be expressed through annotations, i.e. spring has a `ConditionalOnMissingBean` that I've used extensively to implement the same logic at runtime. 

Maybe related to: https://github.com/quarkusio/quarkus/issues/4114

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #4270

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@lburgazzoli Can you verify that this works for your use case?

**Comment by lburgazzoli** [comment]
I will, not very sure if I can do it today as I'm in the middle of a huge refactor but I definitively will

**Comment by lburgazzoli** [comment]
will test tomorrow

**Comment by lburgazzoli** [comment]
LGTM

**Review by lburgazzoli — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
