### PR TITLE
Azure guide for Quarkus Native applications in Docker containers

### PR DESCRIPTION
**Pull request by brunoborges**
Hey @emmanuelbernard, here is a first version.

### CODE REVIEW

**Comment by n1hility** [comment]
Nice! Thanks @brunoborges

**Review by n1hility — CHANGES_REQUESTED** [review]
@brunoborges would you mind squashing these commits? Otherwise we can do so. We don’t mind intermediate commits in general, but prefer to collapse WIP changes. 

Thanks!

**Comment by brunoborges** [comment]
I tried... I failed :-/ Damn git.

Mind to squash on your end?

**Comment by n1hility** [comment]
Sure no problem

**Review by n1hility — APPROVED** [review]

**Pull request merged**
