### PR TITLE
Allow injection of a reactive session not wrapped in a Mutiny/CompletionStage

### LINKED ISSUE #10432: Allow injection of Mutiny.Session and Stage.Session when using Hibernate Reactive
**Description**
At the moment, Quarlus Hibernate Reactive allows the following:

    @Inject
    CompletionStage<Stage.Session> stageSession;

    @Inject
    Uni<Mutiny.Session> mutinySession;

We  also want to be able to do this:

    @Inject
    Stage.Session stageSession;

    @Inject
    Mutiny.Session mutinySession;

This would make it easier to use it because it reduces the amount of code to write considerably. 

**Implementation ideas**

it quite easy, we just need to add the Producer here: https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #10432

### CODE REVIEW

**Comment by Sanne** [comment]
Looks fine, but some CI tests failed on DB2.  It seems similar to that same problem I had when testing DB2 locally; I never had time to investigate that but I'd say that a DB2 driver issue shouldn't get in the way to fix the missing CDI factories...

@aguibert could you have a look at the DB2 failure?

@DavideD perhaps change this PR to not run ITs on DB2 ?  I think the PR is fine, but we can't have CI broken for all other devs.

**Comment by aguibert** [comment]
@Sanne I looked into the CI failures and the stuff that's failing is the new tests being added in this PR, both for JVM and native image mode (see log snippets below). Also, the new tests are failing for MySQL and DB2, so it's not a problem specific to DB2. I think we should review these changes more before merging. 

My current thought is that we have an intermittent timing issue of the tests running too early and perhaps not waiting for the test app to be ready. If something was going wrong with the DB drivers or hibernate reactive, we'd get some useful output from Quarkus, but currently we're just getting a 404.

### JVM mode
```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.188 s <<< FAILURE! - in io.quarkus.it.hibernate.reactive.db2.HibernateReactiveDB2AlternativeTest
[ERROR] io.quarkus.it.hibernate.reactive.db2.HibernateReactiveDB2AlternativeTest.reactiveFind  Time elapsed: 1.425 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "{\"id\":5,\"name\":\"Aloi\"}"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/alternative-test/reactiveFind
```

### Native mode (DB2 and MySQL are failing)
```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.113 s <<< FAILURE! - in io.quarkus.it.hibernate.reactive.db2.HibernateReactiveDB2AlternativeTest
[ERROR] io.quarkus.it.hibernate.reactive.db2.HibernateReactiveDB2AlternativeTest.reactiveFind  Time elapsed: 1.668 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "{\"id\":5,\"name\":\"Aloi\"}"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/alternative-test/reactiveFind

...

[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.665 s <<< FAILURE! - in io.quarkus.it.hibernate.reactive.mysql.HibernateReactiveMySQLAlternativeTest
[ERROR] io.quarkus.it.hibernate.reactive.mysql.HibernateReactiveMySQLAlternativeTest.reactiveFind  Time elapsed: 1.592 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "{\"id\":5,\"name\":\"Aloi\"}"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/alternative-test/reactiveFind
```

**Comment by aguibert** [comment]
Also, ignore the red herring NPE's you see from ` io.vertx.db2client.impl.drda.DRDAQueryResponse.parseEXCSQLSTTreply(DRDAQueryResponse.java:551)`. That is a bug that has been fixed in Vertx 3.9 and will be resolved next time we upgrade Vertx, but it's only related to DDL gen and the test will still pass with that NPE.

**Comment by Sanne** [comment]
@gsmet there's no strong need to backport this, I suspect this is just the first of many polishing PRs. But I'll leave that to you.

**Comment by gsmet** [comment]
Well, it doesn't hurt if we can make it work. TBH, the main reason why I marked it is because I would like to integrate the quickstart PR ASAP :).

**Comment by DavideD** [comment]
GOt it. It's a silly error in the tests. I'm going to fix it

**Comment by Sanne** [comment]
@gsmet ok yes that would be great. The changed syntax looks *much* better.

@aguibert many thanks, you guessed right: that NPE confused me.

**Comment by DavideD** [comment]
OK, I think I've now fixed the issues. Let's wait for CI to confirm

**Review by Sanne — APPROVED** [review]

**Comment by DavideD** [comment]
There is an error on the Windows machine but it doesn't seem related to the PR, any idea?

**Comment by Sanne** [comment]
It's definitely not related, I'll merge this.

**Pull request merged**
