### PR TITLE
Remove deprecated reactive datasource config properties

### PR DESCRIPTION
**Pull request by tsegismont**
- thread local pool
- prepared statement caching at Pg and MySQL level

### CODE REVIEW

**Comment by tsegismont** [comment]
@geoand this would be for Quarkus 3 only. Shall I create the PR against the `3.0` branch instead?

**Comment by geoand** [comment]
I don't think so. @gsmet ?

**Comment by gsmet** [comment]
Hmmm. Let's wait before merging it. Not yet sure if main will be 3 or not.

**Comment by gsmet** [comment]
This needs a rebase to be compatible with the Jakarta-transformed `main`.

**Comment by tsegismont** [comment]
> This needs a rebase to be compatible with the Jakarta-transformed `main`.

@gsmet done

**Review by gsmet — APPROVED** [review]
Thanks!

**Pull request merged**
