### PR TITLE
Allow AuthorizationControllers to access request for their decision

### PR DESCRIPTION
**Pull request by ambition-consulting**
Explained in https://github.com/quarkusio/quarkus/issues/26724 - this will allow authorization controllers to use request information for their decision making.

### CODE REVIEW

**Comment by sberyozkin** [comment]
Unfortunately is not going  to work as `RoutingContext` is not available at the security SPI module level, and the other problem is that `AuthorizationController` no-arg method is used everywhere else except `HttpAuthorizer` where such a new method  makes sense.

Can adding `@ActivateRequestContext` to a custom controller and having `RoutingContext` work instead ?

**Comment by ambition-consulting** [comment]
> Unfortunately it is not going to work as `RoutingContext` is not available at the security SPI module level, and the other problem is that `AuthorizationController` no-arg method is used everywhere else except `HttpAuthorizer` where such a new method makes sense.
> 
> Can adding `@ActivateRequestContext` to a custom controller and having `RoutingContext` injected instead work ?

Still doesn't work:

image

**Comment by michalvavrik** [comment]
Here are steps that I tested with your reproducer and it works.

Step one, define handler and save yourself `RoutingContext`:
```
package org.acme;

import io.quarkus.runtime.StartupEvent;
import io.vertx.core.Handler;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;

import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.inject.Singleton;

@Singleton
public class FridayRoutingContext {

    private volatile RoutingContext routingContext;

    @Inject
    Router router;

    public void init(@Observes StartupEvent startupEvent) {
        final FridayRoutingContext fridayRoutingContext = this;
        router.route().order(-150).handler(new Handler<RoutingContext>() {
            @Override
            public void handle(RoutingContext routingContext) {
                fridayRoutingContext.routingContext = routingContext;
                routingContext.next();
            }
        });
    }

    public RoutingContext getRoutingContext() {
        return routingContext;
    }
}
```

Step two, inject it to your `CustomAuthorizationController`:

```
	@Inject
	FridayRoutingContext fridayRoutingContext;
...

	@Override
	@ActivateRequestContext
	public boolean isAuthorizationEnabled() {
            fridayRoutingContext.getRoutingContext(); // IS NEVER NULL
      }
```

**Comment by sberyozkin** [comment]
This is very useful to know, this technique can help in cases where RequestContext can not be activated, thanks @michalvavrik.

**Comment by ambition-consulting** [comment]
Thanks @michalvavrik - this is an adequate solution for my fairly unusual requirement. We basically don't want our test environments to care about sso, since it would only slow down development. In prod (via profile) and our integration (via request header) environments however it's mandatory.

Thanks a lot - finally I can use Quarkus without Undertow - reactive non-blocking, here we go again! ;)

**Pull request closed without merging**
