### PR TITLE
Bump BouncyCastle version to 1.78.1

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by sberyozkin** [comment]
Let me merge

**Comment by vil2be** [comment]
@sberyozkin , will this PR be backported to 3.8.x?

**Comment by vil2be** [comment]
@aloubyansky @gsmet will this PR also be backported to 3.8.x?

**Comment by vmuzikar** [comment]
@sberyozkin Keycloak is also interested in a backport to 3.8 and 3.2.

**Comment by aloubyansky** [comment]
@vil2be @vmuzikar Sergey has already added the backport labels for those branches, so yes, the change will be included in the review for those branches.

**Pull request merged**
