### PR TITLE
Upgrade to Hibernate ORM 5.6.0.Beta2

### LINKED ISSUE #19867: JPA-Annotation @AttributeOverride is not evaluated properly
### Describe the bug

I have an application with Quarkus using JPA, which has the following problem since I migrated from Quarkus 1.x to 2.x.

There exists a MappedSuperclass named BaseClass, with the following field, which is mapped by default to the database-column 'name':
`
private String name;
`
Now I have another class named DerivedClass, where I want to map the field to another db-column 'custom_name'.
`@Entity
@AttributeOverride(name = "name", column = @Column(name = "custom_name"))  
public class DerivedClass extends BaseClass`

But apperently the AttributeOverride-Annotation is ignored at runtime, as the application tries to read the (not existing) db-column 'name' - and not the column 'custom_name', as required by the annotation.

I managed to fix the problem via the following entry in the orm.xml-file, but I wonder why the AttributeOverride-Annotation is broken since Quarkus 2.x

`
    <entity class="DerivedClass">  
        <attribute-override name="name">  
            <column name="custom_name"/>  
        </attribute-override>  
    </entity>
`

### Expected behavior

Expected behaviour is that the database column custom_name is read.

### Actual behavior

2021-09-02 14:51:52,332 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-0) SQL Error: 0, SQLState: 42703
2021-09-02 14:51:52,333 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-0) ERROR: column derivedclass2_.name does not exist

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 LTS

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

_No response_

### LINKED ISSUE #20186: Hibernate bytecode enhancement applied by quarkus generates invalid bytecode for embeddedId value objects
### Describe the bug

Given the following JPA Entity class with an EmbeddedId class modeled as a value Object, the Hibernate bytecode enhancement that is triggered by Quarkus generates invalid bytecode (shown below). This leads to `java.lang.IllegalAccessError: Update to non-static final field com.example.Drink$DrinkId.id attempted from a different method ($$_hibernate_write_id) than the initializer method <init>` errors.

```
package com.example;

import org.hibernate.annotations.Immutable;

import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import java.io.Serializable;
import java.util.Objects;
import java.util.UUID;

@Entity
public class Drink {

    @EmbeddedId
    private DrinkId id;

    private String name;

    public Drink() {
        this.id = DrinkId.of(UUID.randomUUID().toString());
    }

    public DrinkId getId() {
        return id;
    }

    public void setId(DrinkId id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Immutable
    @Embeddable
    public static class DrinkId implements Serializable {

        private final String id;

        public DrinkId() {
            this.id = null;
        }

        private DrinkId(String id) {
            this.id = id;
        }

        public static DrinkId of(String string) {
            return new DrinkId(string);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof DrinkId)) return false;
            DrinkId drinkId = (DrinkId) o;
            return Objects.equals(id, drinkId.id);
        }

        @Override
        public int hashCode() {
            return Objects.hash(id);
        }
    }
}
```

Stacktrace:
```
java.lang.IllegalAccessError: Update to non-static final field com.example.Drink$DrinkId.id attempted from a different method ($$_hibernate_write_id) than the initializer method <init> 
	at com.example.Drink$DrinkId.$$_hibernate_write_id(Drink.java)
	at com.example.Drink$DrinkId.<init>(Drink.java:50)
	at com.example.Drink$DrinkId.of(Drink.java:54)
	at com.example.Drink.<init>(Drink.java:20)
	at com.example.ExampleResource.hello(ExampleResource.java:25)
	at com.example.ExampleResource_Subclass.hello$$superforward1(ExampleResource_Subclass.zig:157)
	at com.example.ExampleResource_Subclass$$function$$1.apply(ExampleResource_Subclass$$function$$1.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
....
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Resulted in: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalAccessError: Update to non-static final field com.example.Drink$DrinkId.id attempted from a different method ($$_hibernate_write_id) than the initializer method <init> 
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	... 15 more
```

The decompiled generated bytecode for the class `DrinkId` looks like this:
```
 @Immutable
  @Embeddable
  public static final class DrinkIdentifier implements Identifier, Serializable, ManagedComposite, PersistentAttributeInterceptable, CompositeTracker {

    private final String id;
    
    @Transient
    private transient PersistentAttributeInterceptor $$_hibernate_attributeInterceptor;
    
    @Transient
    private transient CompositeOwnerTracker $$_hibernate_compositeOwners;
    
    private DrinkIdentifier(String id) {
      $$_hibernate_write_id(id); // This triggers the IllegalAccessError 
    }
...

    public void $$_hibernate_write_id(String param1String) {
      if (this.$$_hibernate_compositeOwners != null)
        this.$$_hibernate_compositeOwners.callOwner(""); 
      if ($$_hibernate_getInterceptor() != null) {
        this.id = (String)$$_hibernate_getInterceptor().writeObject(this, "id", this.id, param1String);
        return;
      } 
      this.id = param1String; // This triggers the IllegalAccessError
    }
```

### Expected behavior

The hibernate bytecode enhancement applied by quarkus should not emit unnecessary / invalid change tracking bytecode.

### Actual behavior

The hibernate bytecode enhancement applied by quarkus emits invalid bytecode which leads to errors at runtime.

### How to Reproduce?

1) Download and build the example https://github.com/thomasdarimont/quarkus-bugs-invalid-hibernate-bytecode
2) Open http://localhost:8080/hello
3) Observe the stacktrace

### Output of `uname -a` or `ver`

Linux neumann 5.13.14-200.fc34.x86_64 #1 SMP Fri Sep 3 15:33:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

### Additional information

I'm not 100% sure if this is a quarkus issue or a plain hibernate issue. 

The original example comes from a Spring Boot application (https://github.com/odrotbohm/spring-restbucks/blob/main/server/src/main/java/org/springsource/restbucks/drinks/Drink.java#L53) which uses Hibernate 5.5.6. In the spring app the bytecode of the `DrinkIdentifier` class is not enhanced.

The quarkus version 2.2.2.Final seems to use Hibernate 5.5.7. Perhaps this is an hibernate issue that is 
triggered by quarkus due to the explicit bytecode enhancement...

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #19867
Fixes #20186

### CODE REVIEW

**Comment by gastaldi** [comment]
Rebased to get Stuart's fixes to the build

**Comment by geoand** [comment]
Can you please rebase? The Spring test was fixed in https://github.com/quarkusio/quarkus/pull/20271

**Comment by yrodiere** [comment]
@geoand @Sanne I'll do the rebase; I need to add a test for #20186 anyway (because the fix might interact with Panache bytecode enhancement)

**Comment by geoand** [comment]
Thanks!

**Comment by yrodiere** [comment]
Done. I confirmed the tests fail before the upgrade, and succeed after the upgrade.

Let's wait for CI.

**Review by yrodiere — APPROVED** [review]

**Comment by Sanne** [comment]
Thanks for the tests!

**Comment by Sanne** [comment]
ah the `HibernateOrmAnnotationsTest.testNoMissingHibernateAnnotation` is being useful. I'll need to add a commit.

**Comment by knutwannheden** [comment]
> If yes, I could prepare a PR.

Looks like it is part of that release. Here is the PR: #20309

**Pull request merged**
