### PR TITLE
Add support for @NameBinding meta-annotations for @ServerRequestFilter

### PR DESCRIPTION
**Pull request by geoand**
Related to: https://github.com/quarkusio/quarkus/issues/14747#issuecomment-780382773

### CODE REVIEW

**Review by FroMage — APPROVED** [review]
\m/

**Comment by geoand** [comment]
The gradle test failure is totally unrelated

```
2021-02-17T09:48:17.5512688Z     Caused by: io.quarkus.bootstrap.prebuild.CodeGenException: Failed to generate Java classes from proto files: [D:\a\quarkus\quarkus\integration-tests\gradle\build\resources\test\grpc-multi-module-project\application\src\main\proto\devmodetest.proto, D:\a\quarkus\quarkus\integration-tests\gradle\build\resources\test\grpc-multi-module-project\application\src\main\proto\invalid.proto] to D:\a\quarkus\quarkus\integration-tests\gradle\build\resources\test\grpc-multi-module-project\application\build\classes\java\quarkus-generated-sources\grpc
```

cc @michalszynkiewicz

**Comment by michalszynkiewicz** [comment]
@geoand have you seen this failure in other builds?
CC @glefloch

**Comment by geoand** [comment]
I think I have seen it sporadically in the past

**Comment by glefloch** [comment]
@geoand @michalszynkiewicz yes this test has been flaky lately.

**Pull request merged**
