### PR TITLE
Go back to Liquibase 4.3.5

### PR DESCRIPTION
**Pull request by gsmet**
Since the upgrade to Liquibase 4.4, we have some errors with their license stuff. Given we don't have the sources and things are obfuscated, it's not exactly easy to know what's going on so for now, let's go back to 4.3.5.

For the record:
```
Caused by: java.lang.NullPointerException
	at liquibase.license.pro.DaticalTrueLicenseService.licenseIsInstalled(Unknown Source)
	at liquibase.license.pro.DaticalTrueLicenseService.licenseIsValid(Unknown Source)
	at liquibase.configuration.pro.EnvironmentValueProvider.getProvidedValue(Unknown Source)
	at liquibase.configuration.LiquibaseConfiguration.getCurrentConfiguredValue(LiquibaseConfiguration.java:123)
	at liquibase.configuration.ConfigurationDefinition.getCurrentConfiguredValue(ConfigurationDefinition.java:93)
	at liquibase.configuration.ConfigurationDefinition.getCurrentValue(ConfigurationDefinition.java:61)
	at liquibase.logging.core.DefaultLogMessageFilter.filterMessage(DefaultLogMessageFilter.java:12)
	at liquibase.logging.core.AbstractLogger.filterMessage(AbstractLogger.java:92)
	at liquibase.logging.core.JavaLogger.log(JavaLogger.java:26)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:50)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:45)
	at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:28)
	at liquibase.plugin.AbstractPluginFactory.findAllInstances(AbstractPluginFactory.java:92)
	at liquibase.plugin.AbstractPluginFactory.getPlugin(AbstractPluginFactory.java:62)
	at liquibase.logging.core.LogServiceFactory.getDefaultLogService(LogServiceFactory.java:22)
	at liquibase.Scope.getCurrentScope(Scope.java:79)
	at liquibase.configuration.ConfigurationDefinition$Building.build(ConfigurationDefinition.java:323)
	at com.datical.liquibase.ext.config.LiquibaseProConfiguration.<clinit>(Unknown Source)
```

Note that GraalVM recommends to make `com.datical.liquibase.ext.config.LiquibaseProConfiguration` runtime initialized but it's not as easy as it seems as this class is used in a ton of clinits across the codebase.

And for now, I must admit I don't want to waste my time on this given I have absolutely no idea what's going wrong. I'll open an issue in the Liquibase tracker to see if they are willing to help.

### CODE REVIEW

**Comment by famod** [comment]
> I'll open an issue in the Liquibase tracker to see if they are willing to help.

👍 

Btw, https://github.com/quarkusio/quarkus/issues/16292#issuecomment-818808595 is another case of GraalVM "incompatibility" in Liquibase.

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
@gsmet Should we backport this PR too?

**Comment by gsmet** [comment]
AFAIK, we kept 4.3 in 2.0.x.

**Comment by famod** [comment]
@gsmet have you ever reported that issue upstream?

**Pull request merged**
