### PR TITLE
Avoid using Class.getName() in Build steps

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by gsmet** [comment]
Is it supposed to fix something? I miss the context.

**Comment by gastaldi** [comment]
I remember @Sanne saying something that using Class.getName() in our Build items a bad practice, since you're initializing the class early

**Comment by sberyozkin** [comment]
@gastaldi Oh, this is affecting `keycloak-authorization`, sorry, missed it - LGTM - it is a minor optimization as far as I understand

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
I wonder if all of those classes are required to be reflected - but it would be off-topic for this PR I guess, CC @pedroigor

**Review by gsmet — CHANGES_REQUESTED** [review]
Frankly, I don't think we should do that except if we have a good reason to do it. Sanne did it for a particular reason in the Hibernate ORM extension.

If there's a good chance these classes will be initialized anyway and the initialization is not slow, I would keep it the way it is as it's a lot less fragile.

If we had a proper test coverage of all the potential cases, we could consider it but I very doubt it's the case.

**Comment by gastaldi** [comment]
Ok, let´s close this for now then and revisit if needed. Thanks!

**Pull request closed without merging**
