### PR TITLE
Fix OIDC Mastodon image name typo

### PR DESCRIPTION
**Pull request by sberyozkin**
I'm sorry @gastaldi, a typo fix follow up

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Oops, missed that too, good catch!

**Comment by sberyozkin** [comment]
@gastaldi totally my fault, sorry for the hassle, image will def show now though :-)

**Comment by gastaldi** [comment]
No worries 👍🏻

**Comment by gastaldi** [comment]
Follow-up from https://github.com/quarkusio/quarkus/pull/36268

**Pull request merged**
