### PR TITLE
Fix issues in the Quarkus code style

### PR DESCRIPTION
**Pull request by rsynek**
The current Quarkus code style limits maximum line length to 128 characters. Some rules, however, force programmers to exceed this limit by disallowing wrapping in certain situations.

Examples:
```
Class<? extends BiConsumer<CuratedApplication, Map<String, Object>>> clazz = (Class<? extends BiConsumer<CuratedApplication, Map<String, Object>>>) cl
        .loadClass(consumerName); // the previous line exceeds the line length limit by 34 characters
```
[assignment operator example](https://github.com/quarkusio/quarkus/blob/master/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java#L128)

```
@TargetClass(className = "com.sun.xml.internal.bind.v2.model.annotation.LocatableAnnotation", onlyWith = Target_com_sun_xml_internal_bind_v2_model_annotation_LocatableAnnotation.Selector.class) // cannot wrap between the two parameters
```
[annotation example](https://github.com/quarkusio/quarkus/blob/master/extensions/jaxb/runtime/src/main/java/io/quarkus/jaxb/runtime/graal/JAXBSubstitutions.java#L74)

I am proposing the following fix to the Quarkus code style:
- allow line wrapping after the assignment operator
- allow line wrapping between annotation parameters
- allow line wrapping in method declarations

Motivation:
- These fixes give people more freedom on wrapping lines to fit the line length limit and thus, arguably, lead to an increase in the readability of the code.
- OptaPlanner project has recently adopted the Quarkus code style to join a consensus of a wider group of engineers rather than creating yet another one. Unfortunately, the issues described above manifest very often in the OptaPlanner codebase.

### CODE REVIEW

**Comment by gsmet** [comment]
I suppose we could live with it if it helps other projects. @stuartwdouglas WDYT?

**Comment by stuartwdouglas** [comment]
I am +0, I don't really have strong opinions about code style as long as it is consistent and enforced automatically (well mostly, unless you start putting opening braces on their own line, then I will care :-)). I figure most people have large monitors these days so wrapping is less important than it was.

Does it really matter if OptaPlanner style does not exactly match Quarkus?

**Comment by gsmet** [comment]
Well, I suppose they are using what we publish?

But yeah, they could use their own style.

**Comment by stuartwdouglas** [comment]
I am happy to merge it anyway, I am not worried either way.

**Comment by rsynek** [comment]
The idea was to find some widely-used code style. In the past, there was a code style by Sun, then by Oracle. If Quarkus is the next runtime platform, then for projects that integrate with it, e.g. by providing a Quarkus extension, it could make sense to follow some of its conventions.

**Comment by ge0ffrey** [comment]
@gsmet We've already applied these changes in OptaPlanner, but we think it's a readability improvement for Quarkus too, good to upstream. They are pretty minor changes for **more sensible newline points in wrapping**, specifically this code:

BEFORE
```
Class<? extends BiConsumer<CuratedApplication, Map<String, Object>>> clazz = (Class<? extends BiConsumer<CuratedApplication, Map<String, Object>>>) cl
        .loadClass(consumerName);
```

AFTER
```
Class<? extends BiConsumer<CuratedApplication, Map<String, Object>>> clazz =
        (Class<? extends BiConsumer<CuratedApplication, Map<String, Object>>>) cl.loadClass(consumerName);
```

**Comment by rsynek** [comment]
In some places, this change adds line wrappings, in others, it just moves them to a more suitable place, e.g. here:
https://github.com/quarkusio/quarkus/pull/9277/files#diff-d6316ea064df5e821489000ae7f13f8cL128-R129

**Comment by rsynek** [comment]
@gsmet please let me know if you are ok with merging this and I will rebase the PR on the latest master branch.

**Comment by rsynek** [comment]
@gsmet I don't want to be bothersome, but any update/decision here? Thanks!

**Comment by patriot1burke** [comment]
Style guides are the devil!

**Comment by gastaldi** [comment]
LGTM, can you please rebase this PR?

**Comment by gsmet** [comment]
I agree the rules you suggest are better but I think it's going to be too much noise and a pain when dealing with backports. I'm closing.

**Pull request closed without merging**
