### PR TITLE
Flush after REST Data Panache POST

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by FroMage** [comment]
But… why, though? And why don't we have a test?

**Comment by gytis** [comment]
Based on the comments here https://github.com/quarkusio/quarkus/issues/15961, the POST behaviour has changed.

**Comment by gytis** [comment]
Before the `persist` would propagate the @ManyToMany relations, but now I was only able to do it with `persistAndFlush`

**Comment by FroMage** [comment]
I understood that, but I don't see why a flush is needed: it's not like you do another operation after the operation and it should be auto-flushed. That's a sign something is weird.
Also, this should have a test, because we're not seeing the failure ATM, which means it's not tested.

**Comment by gytis** [comment]
The test that @mrizzi provided has a `@ManyToMany` relation. With it the Hibernate does multiple inserts under the covers (in his specific scenario I see three inserts in the log). I assume that's why the flush is needed.
But I think Sane gave a good point on the same issue. Maybe we shouldn't promote such cascading operations to begin with. Then this `flush` would not be needed.

**Comment by Sanne** [comment]
The need for this is confusing me, because I think we made transactions mandatory - and the end of operations should be followed by a commit, at which point Hibernate ORM will automatically flush any pending changes.

**Comment by FroMage** [comment]
Precisely why I found this suspicious too.

**Comment by gastaldi** [comment]
Is this PR still valid? Should we merge or close it?

**Comment by geoand** [comment]
Probably close

**Pull request closed without merging**
