### PR TITLE
Support KubernetesServer test resource for CRUD operations

### LINKED ISSUE #14744: Add a crud capable Kubernetes server test resource
**Description**
Similar to KubernetesMockServerTestResource it would be great to have KubernetesServerTestResource supporting the crud feature of the fabric8 KubernetesServer.

**Implementation ideas**
A new test resource class.  Locally my implementation is just https://github.com/shawkins/mk-agent/blob/39d2606d59a228845d7fa643d277dfe495b64c04/agent-sync/src/test/java/org/bf2/sync/KubernetesServerTestResource.java - at least for my usage there's no need for something like MockServer annotation support.

### LINKED ISSUE #14823: QuarkusTestResourceLifecycleManager should be executed only when a class is annotated by @QuarkusTestResource
I have junit tests and I have integration tests (named xxxIT).  I want to launch the IT test only when the maven profile "integration-test" is active.  (took that my quarkus example)

I have this in my pom.xml
````
<profile>
            <id>integration-test</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <includes>
                                        <include>**/*IT.java</include>
                                    </includes>
                                    <excludes>
                                        <exclude>**/*Native*IT.java</exclude>
                                    </excludes>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
````

in my IT test, I have to create a Kind cluster and also launch a DockerCompose with TestContainer.

I created 2 classes that implements **QuarkusTestResourceLifecycleManager**

and I added them into my IT test like this

````
@QuarkusTest
@QuarkusTestResource(TwinApiServiceDockerCompose.class)
@QuarkusTestResource(KindClusterForQuarkusTest.class)
public class MachineMainCodecControllerTestIT {
...
````

That works fine for IT tests, but I found out that the juni test will start the cluster and dockercompose also even if I didn't put 
````
@QuarkusTestResource(TwinApiServiceDockerCompose.class)
@QuarkusTestResource(KindClusterForQuarkusTest.class)
````  
in my junit tests.

my junit test look like this

````
@QuarkusTest
class MachineHelperTest {
    ````

so.  My point is when a **@QuarkusTest** should use only the @QuarkusTestResource when they are specify in the class.

### PR DESCRIPTION
**Pull request by FroMage**
Can you check @shawkins if this would work for you?

It's a bit over-engineered, but I didn't want for future fixes on one class to miss the other.
I'm also unsure about the annotation for injecting the crud server, but the target server type doesn't have a good name including `mock` like the other… I don't you don't need it ATM but it's more regular to support injection anyway.

@geoand could you double-check if this is binary-compatible? I think it should be. Do you know if we have tests/docs?

Fixes #14744.

Late edit: Also fixes #14823.

### CODE REVIEW

**Comment by geoand** [comment]
Sure thing, I'll check it later on today

**Comment by geoand** [comment]
Looks great to me!

I assume we also want to wait for feedback from @shawkins

**Comment by shawkins** [comment]
This looks good to me as well.  I should add there is an implicit assumption that the KubernetesServer will always be in crud mode because if you didn't want that you would just use the non-crud test resource.  However there is case to be made for something like the Junit EnableKubernetesMockClient where you can toggle the crud mode and use this new test resource either way.

**Review by geoand — APPROVED** [review]

**Comment by FroMage** [comment]
OK hold on don't merge, let me investigate what @shawkins said and another version of this feature I've spotted in the wild.

**Comment by geoand** [comment]
I'll let you merge it when you like

**Comment by FroMage** [comment]
OK I have added a test locally, but I have questions.

@geoand ATM SSL usage is defined by:

```java
    protected boolean useHttps() {
        return Boolean.getBoolean("quarkus.kubernetes-client.test.https");
    }
```

Which is a Java system property. Shouldn't we obtain the quarkus config for `quarkus.kubernetes-client.master-url` instead? As in, would it be better for test users? And is it possible to use quarkus config at this lifecycle stage?

@kornys @shawkins I see in `UseKubeMockServer` that you want to configure ssl, crud and port.

I'm thinking of making those configurable using the quarkus config (see above), would it be OK for you or you prefer annotation attributes?

As for configuring `crud`, I can add an annotation attribute, but if it's `false` then why not just use the `KubernetesMockServer`?

I guess hard-coding it to `crud=true` would allow me to rename this `KubernetesCrudServer`. WDYT?

**Comment by geoand** [comment]
> Which is a Java system property. Shouldn't we obtain the quarkus config for `quarkus.kubernetes-client.master-url` instead? 

Yeah, that makes more sense.

As in, would it be better for test users? And is it possible to use quarkus config at this lifecycle stage?
> 

Unfortunately that won't work because this method is run before any Quarkus bootstrapping has taken place (since one of the points of `start` is to affect the environment the application will run in)

**Comment by shawkins** [comment]
> As for configuring crud, I can add an annotation attribute, but if it's false then why not just use the KubernetesMockServer?

I am saying the same thing above, that it's an implicit assumption of hardcoding crud = true.

> I guess hard-coding it to crud=true would allow me to rename this KubernetesCrudServer. WDYT?

You definitely could, but doesn't the functionality of KubernetesServer dominate that of the KubernetesMockServer?  Should the old test resource be deprecated in favor of one based upon KubernetesServer where it's easy to toggle the crud flag?

**Comment by FroMage** [comment]
> You definitely could, but doesn't the functionality of KubernetesServer dominate that of the KubernetesMockServer? Should the old test resource be deprecated in favor of one based upon KubernetesServer where it's easy to toggle the crud flag?

That's an option as well.

**Comment by FroMage** [comment]
OK, pushed another version for review.

I've added support for meta-annotations to configure the test resources:

```java
@TestProfile(KubernetesTestServerTest.MyProfile.class)
@WithKubernetesTestServer(https = false, crud = true, port = 10001)
@QuarkusTest
public class KubernetesTestServerTest {

    @KubernetesTestServer
    private KubernetesServer mockServer;
```

They're defined by creating an annotation with `@TestResource` on it:

```java
/**
 * Use on your test resource to get a mock {@link KubernetesServer} spawn up, and injectable with {@link KubernetesTestServer}.
 * This annotation is only active when used on a test class, and only for this test class.
 */
@QuarkusTestResource(value = KubernetesServerTestResource.class, restrictToAnnotatedTest = true)
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface WithKubernetesTestServer {

    /**
     * Start it with HTTPS
     */
    boolean https() default false;

    /**
     * Start it in CRUD mode
     */
    boolean crud() default true;

    /**
     * Port to use, defaults to any available port
     */
    int port() default 0;
}
```

And they tie into a new subtype of `QuarkusTestResourceLifecycleManager`:

```java
public interface QuarkusTestResourceConfigurableLifecycleManager<ConfigAnnotation extends Annotation>
        extends QuarkusTestResourceLifecycleManager {
    default void init(ConfigAnnotation annotation) {
    }
}
```

Allowing easy config:

```java
public class KubernetesServerTestResource extends AbstractKubernetesTestResource<KubernetesServer>
        implements QuarkusTestResourceConfigurableLifecycleManager<WithKubernetesTestServer> {

    private boolean https = false;
    private boolean crud = true;
    private int port = 0;

    @Override
    public void init(WithKubernetesTestServer annotation) {
        this.https = annotation.https();
        this.crud = annotation.crud();
        this.port = annotation.port();
    }
```

WDYT?

**Comment by FroMage** [comment]
@geoand I've made it so meta-annotations are always per-test-class but that's OK because they're new. And for existing test resources that people want to make per-test-class I've added:

```java
public @interface QuarkusTestResource {

    /**
     * Whether this annotation should only be enabled if it is placed on the currently running test class.
     * Note that this defaults to true for meta-annotations since meta-annotations are only considered
     * for the current test class.
     */
    boolean restrictToAnnotatedTest() default false;
}
```

This should allow for users to work around the current behaviour without affecting existing users.

WDYT?

**Comment by FroMage** [comment]
@geoand @stuartwdouglas if you're fine with these changes I'll add docs.

**Comment by geoand** [comment]
I like the idea.

But I have a question: what happens if I write something like:

```
@WithKubernetesTestServer(https = false, crud = true, port = 10001)
@QuarkusTest
public class KubernetesTestServerTest {

}
```

Notice that I have removed the test profile.

**Comment by FroMage** [comment]
Not sure what you're trying to discover? I only use that test profile to set some config, so in terms of this PR, nothing would happen, I think.

**Comment by geoand** [comment]
What I am getting at is: "What happens when someone uses such meta-annotations on a test that does not use a profile? Does the resource get started? If, does it still stay up when the test completes?"

**Comment by FroMage** [comment]
It would get started just the same, yes, and it would get stopped as well I assume. The code I modified did not look at profiles at all, so this would be the same behaviour as if the class were annotated with `@TestResource` directly.

Or, are you saying this is going to be tricky if we run multiple tests at once?

**Comment by geoand** [comment]
> It would get started just the same, yes, and it would get stopped as well I assume. The code I modified did not look at profiles at all, so this would be the same behaviour as if the class were annotated with `@TestResource` directly.
> 

OK, that's what I wanted to know. I wanted to understand what **you** expect will happen.

> Or, are you saying this is going to be tricky if we run multiple tests at once?

Nah, that's not really supported anyway

**Review by geoand — APPROVED** [review]
LGTM!

**Comment by FroMage** [comment]
Some reflection foiled my CI, force-pushed a fix

**Comment by FroMage** [comment]
I just verified this works for our operators.

**Comment by geoand** [comment]
Great, a win-win then!

**Comment by FroMage** [comment]
Added docs.

But I'm not entirely satisfied, because the user code had custom code to be executed to set up the kafka mock in their `TestResource`:

```java
    public void configureServer(KubernetesServer mockServer) throws FileNotFoundException {
        // initialize with the crd
        server.getClient().load(new FileInputStream(Paths.get(Environment.ROOT_PATH, "kas-fleetshard-api", "target", "classes", "META-INF", "dekorate", "kubernetes.yml").toString())).get().forEach(crd ->
                server.getClient().apiextensions().v1beta1().customResourceDefinitions().createOrReplace((CustomResourceDefinition) crd));

    }
```

And now with this annotation, usage looks cooler, but they have to remember to put this in every test in a `@BeforeEach`.

**Comment by geoand** [comment]
What's the alternative?

**Comment by FroMage** [comment]
> What's the alternative?

Well, that was your clue to give me a great idea ;)

**Comment by geoand** [comment]
> > What's the alternative?
> 
> Well, that was your clue to give me a great idea ;)

My brain is pretty fried with other stuff, so any ideas from me will have to wait until later on today or tomorrow morning :)

**Comment by gsmet** [comment]
CI is not happy about it:
```
Quarkus - Integration Tests - Kubernetes Client .... FAILURE

2021-02-09T17:14:56.8022729Z Caused by: java.lang.RuntimeException: Unable to obtain configuration for ConfigMap objects from Kubernetes API Server at: http://localhost:54855/
2021-02-09T17:14:56.8026481Z 	at io.quarkus.kubernetes.client.runtime.KubernetesConfigSourceProvider.getConfigMapConfigSources(KubernetesConfigSourceProvider.java:85)
2021-02-09T17:14:56.8031031Z 	at io.quarkus.kubernetes.client.runtime.KubernetesConfigSourceProvider.getConfigSources(KubernetesConfigSourceProvider.java:45)
2021-02-09T17:14:56.8034278Z 	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProvider(ConfigUtils.java:107)
2021-02-09T17:14:56.8036581Z 	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProviders(ConfigUtils.java:121)
2021-02-09T17:14:56.8038464Z 	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1450)
2021-02-09T17:14:56.8040168Z 	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:60)
2021-02-09T17:14:56.8041867Z 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:367)
2021-02-09T17:14:56.8042755Z 	... 49 more
2021-02-09T17:14:56.8044269Z Caused by: java.lang.RuntimeException: ConfigMap 'cmap3' not found in namespace 'demo'
2021-02-09T17:14:56.8047181Z 	at io.quarkus.kubernetes.client.runtime.KubernetesConfigSourceProvider.logMissingOrFail(KubernetesConfigSourceProvider.java:133)
2021-02-09T17:14:56.8053402Z 	at io.quarkus.kubernetes.client.runtime.KubernetesConfigSourceProvider.getConfigMapConfigSources(KubernetesConfigSourceProvider.java:72)
2021-02-09T17:14:56.8055916Z 	... 55 more
```

**Comment by geoand** [comment]
> > What's the alternative?
> 
> Well, that was your clue to give me a great idea ;)

Sounds like a case for `QuarkusTestBeforeEachCallback`, no?

**Comment by FroMage** [comment]
> Sounds like a case for QuarkusTestBeforeEachCallback, no?

Huh, I didn't know it existed. But this is too global for our case.

**Comment by geoand** [comment]
> > Sounds like a case for QuarkusTestBeforeEachCallback, no?
> 
> Huh, I didn't know it existed. But this is too global for our case.

Yeah... There is a ticket to make it per test class, I just haven't got around to doing it...

**Comment by FroMage** [comment]
So… CI failed because the test resources were on tests, but global, had to use the new `restrictToAnnotatedClass` setting :) Should pass now.

**Comment by FroMage** [comment]
So, between the current:

```java
@WithKubernetesTestServer(https = false, crud = true, port = 10001)
@QuarkusTest
public class KubernetesTestServerTest {
    @KubernetesTestServer
    private KubernetesServer mockServer;

 @BeforeEach
 void setup(){
  Infra.setup(mockServer);
 }
}

class Infra {
 public static void setup(KubernetesServer mockServer){
  // ...
 }
}
```

And per-test `QuarkusTestBeforeEachCallback`:

```java
@WithKubernetesTestServer(https = false, crud = true, port = 10001)
@QuarkusTest(beforeEach = Infra.class)
public class KubernetesTestServerTest {
    @KubernetesTestServer
    private KubernetesServer mockServer;
}

class Infra implements QuarkusTestBeforeEachCallback {
 public void beforeEach(QuarkusTestMethodContext context){
   // how do I get to KubernetesServer?
 }
}
```

It is somewhat better I guess, but not sure how to get to what I want here. I'm actually looking for a replacement for:

```
public class CustomKubernetesTestServerTestResource extends KubernetesServerTestResource {

    // setup the ConfigMap objects that the application expects to lookup configuration from
    @Override
    protected void configureServer() {
        // server is a protected field here
    }
}
```

Perhaps it's specific to `@WithKubernetesTestServer` in fact, and not a global test-framework lack of offering?

```java
@WithKubernetesTestServer(https = false, crud = true, port = 10001, setup = Infra.class)
@QuarkusTest
public class KubernetesTestServerTest {
    @KubernetesTestServer
    private KubernetesServer mockServer;
}

class Infra implements Consumer<KubernetesServer> {
 public void accept(KubernetesServer server){
   // setup
 }
}
```

Frankly, that sounds like a decent solution, no?

**Comment by geoand** [comment]
Yeah, the consumer approach does sounds good

**Comment by geoand** [comment]
@FroMage should we get this in now for CR1 and then you follow up later with the consumer API?

**Comment by FroMage** [comment]
Well those test failures are puzzling, I can't reproduce them locally.

**Comment by FroMage** [comment]
> @FroMage should we get this in now for CR1 and then you follow up later with the consumer API?

The consumer API was trivial. The CI failures, no clue.

**Comment by FroMage** [comment]
So, turns out this is because `TestResourceManager`'s lifecycle extends past the current test resource. For `@QuarkusTest` we only reinitialise it when the test profile changes, so it can be random, and so it can't really use the test class for enabling per-test test resource. Just plain out of luck on this one.

**Comment by FroMage** [comment]
OK, so I could have gone with the route of having two sets of test resources: per-test and global, but since test resources can set system properties that affect other parts of the application (I think that's the idea), it would just be broken if we didn't restart the app when we have per-test test resources.

IMO it's similar to changing profile, and we do restart when changing profile, so now I've made it similar: if the test class changes, and we used to have or will have per-test test resources, I force a restart.

This fixes those tests. Let's see what else I broke.

**Comment by FroMage** [comment]
Damnit, now it's native tests failing

**Comment by FroMage** [comment]
OK, native tests now work locally, let's see what CI throws my way.

**Comment by FroMage** [comment]
I think failure on Windows is unrelated, but let's wait for the other runs:

```
2021-02-15T14:39:28.0595731Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.98 s - in io.quarkus.scheduler.test.SimpleScheduledMethodTest
2021-02-15T14:39:28.0608094Z [INFO] Running SimpleScheduledMethodDefaultPackageTest
2021-02-15T14:39:29.3299911Z 2021-02-15 14:39:28,774 WARN  [io.qua.sch.dep.SchedulerProcessor] (build-42) @Scheduled(cron = "0/1 * * * * ?",every = "2m") declared on SimpleJobsDefaultPackage#checkEverySecondCron() defines both cron() and every() - the cron expression takes precedence
2021-02-15T14:39:29.3302897Z 2021-02-15 14:39:29,321 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT on JVM started in 0.453s. Listening on: http://localhost:8081
2021-02-15T14:39:29.3304036Z 2021-02-15 14:39:29,322 INFO  [io.quarkus] (main) Profile test activated. 
2021-02-15T14:39:29.3304845Z 2021-02-15 14:39:29,322 INFO  [io.quarkus] (main) Installed features: [cdi, scheduler]
2021-02-15T14:39:31.0345491Z 2021-02-15 14:39:31,025 INFO  [io.quarkus] (main) Quarkus stopped in 0.020s
2021-02-15T14:39:31.0351197Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.002 s - in SimpleScheduledMethodDefaultPackageTest
2021-02-15T14:39:31.1378829Z [INFO] 
2021-02-15T14:39:31.1389156Z [INFO] Results:
2021-02-15T14:39:31.1390089Z [INFO] 
2021-02-15T14:39:31.1392804Z [ERROR] Failures: 
2021-02-15T14:39:31.1394226Z [ERROR]   DevConsoleRunScheduledTaskBodyHandlerTest.testInvokeScheduledTask:35 1 expectation failed.
2021-02-15T14:39:31.1395664Z Response body doesn't match expectation.
2021-02-15T14:39:31.1396146Z Expected: "true"
2021-02-15T14:39:31.1396716Z   Actual: false
```

**Comment by FroMage** [comment]
Only Windows failed, re-running.

**Comment by FroMage** [comment]
A comment by @mkouba https://github.com/quarkusio/quarkus/issues/15083#issuecomment-779687496 made me wonder if per-test test resources should not belong on custom test profiles rather than on tests. After all, in both cases we need to restart the app if the settings changed between tests, so it's pretty similar.

WDYT?

**Comment by geoand** [comment]
Yeah, sounds reasonable

**Comment by FroMage** [comment]
Damnit, just when CI passed…

**Comment by geoand** [comment]
Well, if you are good to go for your work, feel free to merge this as is

**Comment by FroMage** [comment]
Well, so for now we have global test resources, and we now have per-test test resources with this PR.

I'm thinking of adding per-profile test resources, but perhaps they're just an additional use-case and would not replace per-test test resources?

If that's the case, then we can merge as-is and add per-profile test resources later.

If on the other hand, we think that per-profile test resources are better than per-test test resources, I should make the change before merging anything. Opinion?

**Comment by geoand** [comment]
I personally think that per-profile test resources are better (`QuarkusTestProfile#testResources` allows you to set them), but I know that you need to move forward with other work, so I'll leave it up to you

**Comment by FroMage** [comment]
I guess yes, on the one hand it's probably more common to have per-profile test resources, since they can be shared by more than one test.

On the other hand, I'd still prefer to support meta-annotations, because they're just better, consider:

```
    @WithKubernetesTestServer(https = false, crud = true, port = 10001, setup = KubernetesTestServerTest.Setup.class)
    public static class MyProfile implements QuarkusTestProfile {

        @Override
        public List<TestResourceEntry> testResources() {
            Map<String,String> args = new HashMap<>();
            args.put("https", "false");
            args.put("crud", "true");
            args.put("port", "10001");
//            args.put("setup", ??);
            return Arrays.asList(new TestResourceEntry(KubernetesServerTestResource.class, args));
        }
}
```

So I'm tempted to allow both per-test and per-profile test resources with meta-annotations. If this is not too complex to support. Famous Last Words™.

**Comment by FroMage** [comment]
Interestingly `NativeImageTest` doesn't support per-profile test extensions, apparently?

**Comment by geoand** [comment]
I haven't tried it, but (from my recollection of the code) I think it should

**Comment by FroMage** [comment]
I don't think it can, not the way it looks ATM.

**Comment by FroMage** [comment]
Failing test is unrelated and flaky. Let's merge this.

**Comment by gsmet** [comment]
I don't remember why I added the `triage/backport-1.11?` label but... this doesn't apply cleanly at all so I think we shouldn't backport it to 1.11.

@geoand @FroMage what's your take on this?

**Comment by geoand** [comment]
This is one that @FroMage wanted, but I can't remember if he wanted it backported or not

**Comment by gsmet** [comment]
It's going to be in 1.12.1.Final that I will release in a few days. But backporting to 1.11 will require to create another PR and carefully review things. Not sure it's worth the risk.

**Comment by geoand** [comment]
We'll need Stephane to clarify that point

**Comment by gsmet** [comment]
We won't have time to do a proper backport now. Unmarking it.

**Pull request merged**
