### PR TITLE
Remove security guides we are no longer publishing for 3.2 product docs

### PR DESCRIPTION
**Pull request by rolfedh**
On Wednesday, we agreed to publish only a smaller set of security docs to maximize the effort on `main`. 

This PR updates the 3.2 version of the downstream doc import list yaml file in the upstream community to remove the unrequired content so that our downstream import script does not automatically add the content downstream and so that the xrefs get turned into external community links.

FYI @gsmet / @gastaldi / @aloubyansky / @maxandersen 

Please note, I deliberately targeted the 3.2 branch instead of main because the version of this file on main has diverged significantly. Several files have been renamed/restructured requiring a massive backport, most of which seems to be currently outside the scope of the 3.2 docs both upstream and downstream. Thanks.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by michelle-purcell** [comment]
:eyes: - @rsvoboda

**Review by ebullient — APPROVED** [review]

**Comment by rsvoboda** [comment]
@michelle-purcell the plan was to keep 7 security guides, not 8. What changed? security-authentication-mechanisms wasn't in the set we discussed together

**Comment by michelle-purcell** [comment]
@rsvoboda - My apologies if there's a mixup here... but this topic was on the list I proposed in Gchat. I added the proposed label in JIRA but a shorter version of it for RHBQ without some of the in-depth content. Most of the overview guides refer to it, so sending the reader back up to the community docs might not be the best experience. WDYT?  
Proactive Authentication was the one on the list but under question that we might not include. However, we want to rebuild the smaller subset and view on PV2 before confirming. Thanks.

**Comment by michelle-purcell** [comment]
@rostislav - security-authentication-mechanisms was a potential that we discussed in the writers sync. Now that this PR is merged and we can see what the initial reduction proposal looks like on PV2 this morning, it makes sense to remove this one altogether and just link to it in product docs. Thanks for flagging!

**Pull request merged**
