### PR TITLE
Do not assume that option values are always String[]

### PR DESCRIPTION
**Pull request by gastaldi**
From @michalszynkiewicz feedback in https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/ClassCastException.20on.20master

### CODE REVIEW

**Comment by aloubyansky** [comment]
Actually, it should be fixed here https://github.com/quarkusio/quarkus/blob/96067aeeffe3abdf4fc9984036d354c15c31e699/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/options/BootstrapMavenOptionsParser.java#L23

Instead of calling getOptionValue(..) for the active profiles, it should be calling getOptionValues(..).

**Comment by gastaldi** [comment]
Anyway putting everything in a Map with Object as value seems to be a bit creepy. Maybe change the generic parameter to the map value to `String[]` would be better

**Comment by gastaldi** [comment]
Or a Multimap data structure

**Comment by aloubyansky** [comment]
I hope that class is gonna go away with the refactoring I'm working on right now. So don't go too creative there.

**Comment by gastaldi** [comment]
Awesome, so I'll close it and wait for your changes then ;)

**Pull request closed without merging**
