### PR TITLE
Support for platform streams in the registry client

### PR DESCRIPTION
**Pull request by aloubyansky**
This PR introduces the notion of platform streams to the registry client API.

### CODE REVIEW

**Comment by gsmet** [comment]
@gastaldi can you have a look?

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by aloubyansky** [comment]
@gastaldi if this will need changes in the registry. If we merge it now, the registry won't be usable with the devtools.

**Comment by gastaldi** [comment]
@aloubyansky fair enough, can we get this in the CR1 release and have a PR for the registry?

**Comment by aloubyansky** [comment]
AFAIK,it's too late for cr1.

**Comment by gastaldi** [comment]
> AFAIK,it's too late for cr1.

That's fine, we just need to make sure the registry works in 2.0.0.Final, since it doesn't seem to be used ATM.

@phillip-kruger might be interested in these changes too, as AFAIK he was working with @ia3andy on adapting code.quarkus.io to read from the registry

**Comment by aloubyansky** [comment]
Sure, @phillip-kruger let me know if you need my help with that.

**Comment by phillip-kruger** [comment]
Thanks :) At this point I am not sure if I know enough to know what I don't know and where I need help :)

I am still trying to figure out how to get a catalog of all extensions for a certain version and platform...

**Comment by aloubyansky** [comment]
Let's take it to zulip.

**Pull request merged**
