### PR TITLE
Move OidcTenantConfig out of the runtime package

### LINKED ISSUE #8347: Move OidcTenantConfig out of the runtime package
**Description**
Right now `OidcTenantConfig` is in the runtime package: `io.quarkus.oidc.runtime` but since it is now visible to `io.quarkus.oidc.TenantConfigResolver` it could be a bit better to move `OidcTenantConfig` out of `runtime` as it is really part of the API now, and we'll offer a builder support around it too.

**Implementation ideas**
Move `OidcTenantConfig` to `io.quarkus.oidc`

The only concern is that I know at least a single user who was looking at it. It is still the relatively early days though for the multi-tenancy and `TenantConfigResolver` in particular, so I reckon we should do it for `1.4.0` before it will become used a lot

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #8347

I can update 1.4.0.Final release notes and also sent the note to the forum once this PR is merged. CC @gsmet

### CODE REVIEW

**Comment by sberyozkin** [comment]
`AmazonLambdaSimpleTestCase` fails in one of the CIs.
I'll give it another rebase

**Review by pedroigor — APPROVED** [review]
We should probably have a specific object to build this configuration when multi-tenancy is being used. It would help to improve encapsulation and remove those getters/setters that are kind of redundant now.

I'm approving because I think you mentioned we are going to handle this in the future. But the way it is now users can set config properties in different ways when using multi-tenancy.

**Comment by sberyozkin** [comment]
@pedroigor Hi, you had an idea awhile back that we can introduce a builder API, I might give it a go later.

**Comment by sberyozkin** [comment]
@pedroigor @gsmet I keep getting a resteasy deployment test failure, Security2 tests pass:
https://github.com/quarkusio/quarkus/pull/8596/checks?check_run_id=592986982

I'll rebase again just to try to get a total green, but will merge, unless there will be more review comments if the same reasteasy test fails, as it has to make it into 1.4.0.Final if it to make it at all :-)

**Comment by sberyozkin** [comment]
The same resteasy deployment failure, so I'll just go ahead or else it won't make it at all.

**Comment by sberyozkin** [comment]
@gsmet Can you explaing why it is not backported ?

**Comment by sberyozkin** [comment]
@gsmet OK, got it. Sorry I missed that the backport was already done, could've checked

**Pull request merged**
