### PR TITLE
Fix typo in name of `AdditionalSecuredClassesBuildIem` class

### PR DESCRIPTION
**Pull request by knutwannheden**

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@ppalaga @evacchi I was leaning towards backporting this one to 2.0 but I was wondering if it could be an issue for you?

**Comment by knutwannheden** [comment]
Please also note that this typo is the reason that the build item is not documented here: https://quarkus.io/guides/all-builditems

See https://github.com/quarkusio/quarkus/blob/main/.github/quarkusbuilditemdoc.java#L96

**Comment by evacchi** [comment]
I don't think we are using this @danielezonca @mariofusco ?

**Comment by ppalaga** [comment]
Thanks for the heads up, @gsmet! I found zero occurrences of `AdditionalSecuredClassesBuildIem` in Camel Quarkus, so you are good to go.

**Pull request merged**
