### PR TITLE
Provide an option to set Form based auth encrypted cookie as HttpOnly

### LINKED ISSUE #27609: Extend form auth cookie configuration
### Description

**Suggested configurations**:

- Make cookie [`HttpOnly`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security) / add configuration option to force this.
	- **Why?** Current cookie is not `HttpOnly` which is [not a safe way](https://owasp.org/www-community/HttpOnly) of using session cookie.
	- **Workaround?** Can you advice any? Is it possible intercept **single** endpoint response and modify it's cookies?

- or Add ability to modify session cookie after it was created by injecting some mapper function and calling it on the cookie instance (e.g. I would love to use `Secure` as my application server is running behind the reverse proxy (Caddy <---http--> Quarkus)).

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #27609

Provide convenient way to make the cookie that is used to store the persistent session `HttpOnly`.

### CODE REVIEW

**Comment by michalvavrik** [comment]
cc @sberyozkin

**Comment by sberyozkin** [comment]
Hi @michalvavrik Thanks for the PR, looks fine, but I wonder, should we even introduce a property and instead just set `HttpOnly` by default ? We do it in `quarkus-oidc` too, there's no reason to allow the client side scripts access this cookie, so just adding this attribute by default works IMHO

**Comment by michalvavrik** [comment]
@sberyozkin doesn't client need to access this cookie in order to make it expired (aka "delete it") as advised here for logout https://github.com/quarkusio/quarkus/issues/27389#issuecomment-1223675576 ? I can prepare reproduce to find out, but if you know this already, you can tell me :-)

**Comment by sberyozkin** [comment]
@michalvavrik I forgot about, good point. Right, so ideally the logout would be handled at the server, by deleting the same cookie, but with form based authentication I suppose we should support the client side removal of this cookie too

**Review by sberyozkin — APPROVED** [review]

**Pull request merged**
