### PR TITLE
MP Metrics 3.0

### PR DESCRIPTION
**Pull request by jmartisk**
fixes https://github.com/quarkusio/quarkus/issues/10514

### CODE REVIEW

**Comment by jmartisk** [comment]
At minimum, this will break fault tolerance and graphql, so it will need to be followed by upgrades of these components
cc @Ladicek @phillip-kruger

**Comment by Ladicek** [comment]
Sounds fine to me, I have a Quarkus branch locally that updates to SRye FT 5.0, I can undust it and submit a PR too.

**Comment by jmartisk** [comment]
I took a look at the failures in CI tests and all seem expected to me (mostly `IncompatibleClassChangeError` in GraphQL and Fault Tolerance tests due to mismatch in MP Metrics versions)
I'd suggest merging as-is and these things will be fixed by subsequent PRs

**Comment by radcortez** [comment]
Are we able to get a green build? Or are we blocked with some other dependency?

**Comment by jmartisk** [comment]
No green build right now, we need an update of GraphQL and Fault Tolerance. 
I looked at the failing tests and didn't notice anything unexpected, so I would suggest merging it like this.
Other option would be to get all the dependencies into this PR as well, but that would make it quite big, and would kinda defeat the purpose why we created a separate branch for MP 4, so that everyone can do their own part separately.

**Comment by radcortez** [comment]
Do we need them to be done at the same time? Or could we update FT first or Graph QL and do Metrics? I don't completely oppose to merge like this, I'm just concerned that when we move with other integrations, we cannot be sure if it is ok or not because the build is broken.

**Comment by radcortez** [comment]
Or in alternative, could we disable the tests that we know that are failing due to Metrics? I've done the same for the OpenTracking TCK, since it requires the new version, but we don't have one available.

**Comment by jmartisk** [comment]
Disabling tests makes it looks like the problem does not exist. And you have to re-enable them later, so that's also a lot of work. 
I think that once we add GraphQL and Fault Tolerance PRs, which will be very soon, the problem will be gone.

**Comment by phillip-kruger** [comment]
GraphQL is on it way ....

**Comment by Ladicek** [comment]
Here's my branch for integrating MP FT 3.0 and SRye FT 5.0.0 to Quarkus: https://github.com/Ladicek/quarkus/commits/mp-ft-3.0 It only has RCs, because MP FT 3.0 isn't out yet, but otherwise should be good.

**Comment by jmartisk** [comment]
incorporated into https://github.com/quarkusio/quarkus/pull/13867

**Pull request closed without merging**
