### PR TITLE
Remove workaround for testing knative environment

### PR DESCRIPTION
**Pull request by geoand**
This can now be done because
https://github.com/fabric8io/kubernetes-client/issues/4447 is included in version 6.3 of the k8s client

### CODE REVIEW

**Comment by geoand** [comment]
cc @manusa

**Comment by manusa** [comment]
:+1: I'll rebase #30480 once you merge this since I might include changes that affect this class and the KubernetesBuildItem in general.

**Comment by geoand** [comment]
Cool

**Review by gsmet — APPROVED** [review]

**Comment by manusa** [comment]
Note that this method will need refactoring when bumping the client to 6.5 or at most 6.6 

https://github.com/fabric8io/kubernetes-client/pull/4869

**Pull request merged**
