### PR TITLE
Camel JDBC extension

### PR DESCRIPTION
**Pull request by ppalaga**
@gnodet could you please review? This was an introductory exercise for me. I am not 100% sure the test makes sense in this standalone form. We could move the route to `camel-core` itest but the necessary dependencies would not be that explicit there (would that matter?).

### CODE REVIEW

**Comment by ppalaga** [comment]
@gnodet it is finally passing. Could you please share your opinion whether the test makes sense in this standalone form (or if I should move it to the camel-code tests module)?

**Comment by gsmet** [comment]
@gnodet any chance you could review this one?

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
LGTM.

**Comment by ppalaga** [comment]
In b57f739 I added `camel-csv` and `camel-jdbc` to `quarkus-bom`.

**Comment by ppalaga** [comment]
Resolved merge conflict in acb1573

**Comment by kenfinnigan** [comment]
Are these tests being added solely to verify `quarkus-camel-core` works as expected with Camel components?

If so, I think that's unnecessary given adding Camel into Quarkus is a temporary solution

**Comment by gnodet** [comment]
Btw, if the goal is to split Camel support out of quarkus, it would be nice to have that sooner rather than later. Is there anything missing beyond supporting extensions in a more dynamic way ? I.e. without having them statically listed in the FeatureBuildItem...

**Comment by kenfinnigan** [comment]
My understanding of `FeatureBuildItem` is that it can be set with any String value.

The statics are purely a convenience and possibly to prevent overlap, but I don't think it's necessary.

**Comment by ppalaga** [comment]
I was just taught by @gnodet and @lburgazzoli that I should add a camel-jdbc-extension (in spite of the fact that the component would work without it) so that it is easier for the users to discover it and get the right set of dependencies. So let me add such a trivial extension.

**Comment by ppalaga** [comment]
787fa0f adds the Camel JDBC extension and the integration test does not depend on camel-csv anymore. @lburgazzoli @gnodet could you please re-review?

**Comment by oscerd** [comment]
This one looks good too @gsmet

**Review by oscerd — APPROVED** [review]

**Review by lburgazzoli — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
