### PR TITLE
Support test resources with restrict to annotatedClass in @Nested class

### LINKED ISSUE #26639: `QuarkusTestResource` with `restrictToAnnotatedClass` restarts for `@Nested` classes
### Describe the bug

When `QuarkusTestResource` is configured to be `restrictToAnnotatedClass`, it restarts for nested classes annotated with `@Nested`. This is also the case for `QuarkusTestResourceConfigurableLifecycleManager`, which apply `restrictToAnnotatedClass` automatically.

```java
@QuarkusTest
@QuarkusTestResource(value = DummyTestResource.class, restrictToAnnotatedClass = true)
public class DummyNestedTest {

    @InjectDummyString
    String bar;

    @Test
    public void testBar() {
        Assertions.assertEquals("bar", bar); // this assertion works
    }

    @Nested
    class NestedTestClass {

        @Test
        public void testBar() {
            Assertions.assertEquals("bar", bar); // this assertions fails
        }
    }
}
```

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD})
public @interface InjectDummyString {
}
```

```java
public class DummyTestResource implements QuarkusTestResourceLifecycleManager {

    @Override
    public Map<String, String> start() {
        return null;
    }

    @Override
    public void stop() {

    }

    @Override
    public void inject(TestInjector testInjector) {
        testInjector.injectIntoFields("bar", new AnnotatedAndMatchesType(InjectDummyString.class, String.class));
    }
}
```

### Expected behavior

`QuarkusTestResource` configured with `restrictToAnnotatedClass=true` should not restart for nested classes annotated with `@Nested`.  
Or, should be capable of injecting fields into the parent class.

### Actual behavior

`QuarkusTestResource` configured with `restrictToAnnotatedClass=true` restarts for nested classes and can not inject fields located in the parent class.

### How to Reproduce?

Reproducer: [reproducer.zip](https://github.com/quarkusio/quarkus/files/9079579/reproducer.zip)

How to reproduce: Execute the tests.

The reproducer introduces a `QuarkusTestResourceLifecycleManager` which injects the string "bar" using the `@InjectDummyString` annotation.  
The `DummyNestedTest` shows, that the string is actually `null` in a nested class annotated with `@Nested`. Also you can see, that Quarkus is restarting for the nested class.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.10.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/26639

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @stephan-strate @geoand

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
@Sgitario can you resolve those conflicts?

**Comment by Sgitario** [comment]
> @Sgitario can you resolve those conflicts?

Done

**Comment by famod** [comment]
With tis change, Quarkus is still restarted for nested classes, right? This is what I'm seeing locally.

We should probably fix that too, eventually (via a separate issue/pr).

**Comment by stephan-strate** [comment]
> With this change, Quarkus is still restarted for nested classes, right? This is what I'm seeing locally.
> 
> We should probably fix that too, eventually (via a separate issue/pr).

Did you open an issue for it already?

**Comment by famod** [comment]
> > With this change, Quarkus is still restarted for nested classes, right? This is what I'm seeing locally.
> > We should probably fix that too, eventually (via a separate issue/pr).
> 
> Did you open an issue for it already?

No, I didn't. Please feel free to do so.

**Pull request merged**
