### PR TITLE
Append label instead of replacing whole Spring Cloud config URI

### LINKED ISSUE #38445: Wrong logging of SpringCloudConfig server URL when using labels
### Describe the bug

The log statement that is supposed to print the final URL being called logs only the last segment only.

`DEBUG [io.qu.sp.cl.co.cl.ru.VertxSpringCloudConfigGateway] (main) Attempting to read configuration from '/myLabel'.`

instead of
`DEBUG [io.qu.sp.cl.co.cl.ru.VertxSpringCloudConfigGateway] (main) Attempting to read configuration from 'http://myserver:8888/application-name/dev/myLabel'.`

### Expected behavior

log statement prints the whole URL

### Actual behavior

only label is printed

### How to Reproduce?

use spring cloud config with a label

### Quarkus version or git rev

latest

### Additional information

@radcortez The issue is here: https://github.com/quarkusio/quarkus/blob/391ca5afd58679af55962601373961fa9845b4d8/extensions/spring-cloud-config-client/runtime/src/main/java/io/quarkus/spring/cloud/config/client/runtime/VertxSpringCloudConfigGateway.java#L236

instead of appending to `finalURI`, it is replacing the value.

### PR DESCRIPTION
**Pull request by troosan**
- Fixes #38445

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Great catch, thanks!

**Comment by troosan** [comment]
I was actually trying to understand why my properties did not get loaded.
It seems that instead of doing a single call to the SCC specifying all profiles, it is looping over the profiles and loading them one by one.
All properties could be loaded in one go with 
`http://myserver:8888/application-name/dev,other-dev/myLabel`

instead of calling
`http://myserver:8888/application-name/dev/myLabel`
`http://myserver:8888/application-name/other-dev/myLabel`

Then I saw that it is creating the properties with %dev and %other-dev quarkus profiles
it meant that I had to enable 2 quarkus profiles (one which is useless, as it is already specified in quarkus.spring-cloud-config.profiles).
But I guess changing this to be added without profile would be quiet a contract breaker ...

Anyway to find out what what was wrong I had to check the quarkus code, I guess a bit more DEBUG logs would have helped to find out what the issue was.

**Comment by geoand** [comment]
> Anyway to find out what what was wrong I had to check the quarkus code, I guess a bit more DEBUG logs would have helped to find out what the issue was.

What did the current output look like?

**Comment by troosan** [comment]
not much, just
`DEBUG [io.qu.sp.cl.co.cl.ru.VertxSpringCloudConfigGateway] (main) Attempting to read configuration from '/myLabel'.`

and then my app failed to load because it did not load the properties because I was not passing the SCC profiles as Quarkus profiles

**Comment by geoand** [comment]
Gotcha, I'll add some more

**Pull request merged**
