### PR TITLE
Bump Keycloak version to 19.0.1

### PR DESCRIPTION
**Pull request by sberyozkin**
I've spent nearly all day on this PR today as the new storage (Map based by default AFAIK) seems to have some clean up issues at the host and Dev Services based tests have been failing randomly (I've captured the same tests passing and then failing), and also the start time has increased, but then I've remembered that Pedro has advised to try `--storage=chm` - it stabilized it and the startup time is at least no worse compared to `18.0.2` on my old laptop but will likely be even better on newer laptops.
Also `integration-tests/oidc-client-reactive` which starts Dev Services for KC has a redundant profile.
I'm still seeing side-effects with 2 quickstarts but it looks like they are more related to the fact they use the realms created by very old Keycloak - I'll try to finalize it - but this PR itself should be ready for review.

### CODE REVIEW

**Comment by sberyozkin** [comment]
https://github.com/quarkusio/quarkus-quickstarts/pull/1159 fixes the quickstart issues, but this PR needs to be merged first

**Review by pedroigor — APPROVED** [review]
@sberyozkin FYI, sessions do not expire after server restart if you are using `storage=chm`. That is because they are stored in the filesystem.

Not sure if it might impact tests that expect otherwise.

**Comment by sberyozkin** [comment]
Hi @pedroigor I thought I left a comment here but looks like I lost it, yeah, I just said I'd check it out with devservices - it has no side-effects, as even if we restart, it is a new container start, so for example, I logged in as `admin:admin` and then stopped Quarkus without logging out, and then returned to Dev UI and got a new authentication challenge. I guess it is more related to the case where `Keycloak` is started from the cmd with `kc.sh` which is not the case with the devservices.

So I'll go ahead and merge, thanks

**Comment by rsvoboda** [comment]
There are new failures in security related QS, see https://github.com/quarkusio/quarkus-quickstarts/actions/workflows/native-build-development.yml 
These failures are related to this change, when I used quarkus main `52379a5ce2e7d61447d96f7cb9f9c133822788b6` (the one before the merge) QS was passing

**Pull request merged**
