### PR TITLE
Use the correct URL for creating realms in DevServices for KC with shared network

### LINKED ISSUE #22471: DevServices for Keycloak can not create realms in shared network
### Describe the bug

Dev Services for Keycloak (current using on a WildFly based distribution container by default) can import the realm file by setting an env property but if a default realm has to be created which requires an HTTP call to Keycloak then it will not work if the shared network is enabled.

@geoand I have a PR ready to follow on your fix earlier - as the test you added (with the realm imported) does not cover the code path where a realm has to be created, I spotted it while fixing the #22420 build failure - since with Keycloak-X the realm can only imported at the moment by sending a create realm request over HTTP. The same fix is in #22420 but I'd not like to backport #22420 so I'd like to fix this specific issue independently and backport and then sync it to #22420

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #22471

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by sberyozkin** [comment]
Oops, sorry @geoand Just need to tweak the new test :-) - it still imports the realm, I'll update very soon

**Comment by geoand** [comment]
No problem :)

**Comment by sberyozkin** [comment]
@geoand It is already correct as here the realm resource does not exist, so Dev Services for KC will default to creating a simple realm, but I've removed `application.properties` completely to make it clearer. Note this time the users differ, in the test you added the existing realm is imported where the `admin` user has an `admin` role, but `alice` has only a `user` role. This time, when the default realm is created, `alice` has an `admin` role but `bob` - only a `user` role :-)

**Comment by geoand** [comment]
Cool 💪🏼

**Pull request merged**
