### PR TITLE
Bump Stork version to 2.0.1

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Comment by aureamunoz** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
The failure are not surprising, we need to change the extension to register the service discovery and load balancer providers as bean.

**Comment by aureamunoz** [comment]
> The failure are not surprising, we need to change the extension to register the service discovery and load balancer providers as bean.

Yeah, will do it next week.

**Comment by gsmet** [comment]
Rebased to get the latest CI fixes.

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
