### PR TITLE
Introduce a way for users to customize Flyway configuration

### LINKED ISSUE #28502: Flyway transactional lock property
### Description

Please consider adding new Flyway [property](https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock#usage) to Quarkus configuration with default value set to "false"
A discussion about this property and issue with its current default (true) value can be found [here](https://github.com/flyway/flyway/issues/3508)

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This is useful for users who need to update Flyway's configuration after it has been populated by Quarkus but before it has been handed off to Flyway

Closes: #28502

### CODE REVIEW

**Comment by geoand** [comment]
P.S. We should probably follow up with a similar approach for Liquibae

**Review by gastaldi — APPROVED** [review]
Good idea!

**Comment by pedrolopix** [comment]
I have this issue and it's preventing to bumping quarkus, it will be available in version 2.x?

**Comment by geoand** [comment]
It is unlikely we will backport this

**Pull request merged**
