### PR TITLE
Manage Quartz Jobs through ArC

### LINKED ISSUE #11496: Provide a cdi aware QuartzFactory
Please provide a cdi aware QuartzFactory that allows to create QuartzJobs that make use of cdi injection.

As a hack, I am currently using: Arc.container().instance(MyService.class).get(); in the Quartz Job class, as recommended by @radcortez, but it doesn't work reliably when the bean is not available and I am sure this could be done in a more transparent way :)

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #11496

### CODE REVIEW

**Review by manovotn — APPROVED** [review]
Looks good!

**Review by machi1990 — CHANGES_REQUESTED** [review]
Can we add a line or two in the Quartz documentation? 

Other than that it LGTM too. 

Thank you!

**Review by machi1990 — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]
Thanks for the followup fixes!

**Comment by mkouba** [comment]
@gastaldi @machi1990 I think that a better and more correct solution would be to inject `Instance<Job>` into `QuartzScheduler` and use it in `InvokerJobFactory`. That way all beans implementing `Job` would be _unremovable_ automatically and no `AdditionalBeanBuildItem` would be needed (note that `AdditionalBeanBuildItem` should be only used to add a bean class that is not in any bean archive).

**Comment by machi1990** [comment]
> @gastaldi @machi1990 I think that a better and more correct solution would be to inject `Instance<Job>` into `QuartzScheduler` and use it in `InvokerJobFactory`. That way all beans implementing `Job` would be _unremovable_ automatically and no `AdditionalBeanBuildItem` would be needed (note that `AdditionalBeanBuildItem` should be only used to add a bean class that is not in any bean archive).

Welcome back and thanks for the input / note @mkouba.  

Happy to review any followup PR if @gastaldi or anyone will be up for it :-)

**Comment by mkouba** [comment]
I can try to prepare a followup PR today...

**Comment by machi1990** [comment]
Thanks @mkouba

**Pull request merged**
