### PR TITLE
Test for #7102

### PR DESCRIPTION
**Pull request by FroMage**
Test passes, we must have fixed this already.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by mkouba — APPROVED** [review]
LGTM.

**Comment by FroMage** [comment]
Thanks.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
These all need @DisabledOnNativeImage

**Comment by FroMage** [comment]
Good point, done.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by geoand** [comment]
The Vault failure have nothing to do with this PR (I opened https://github.com/quarkusio/quarkus/pull/9600 to address it)

**Comment by FroMage** [comment]
OK, let's merge then.

**Pull request merged**
