### PR TITLE
Initial commit adding shutdown hooks

### LINKED ISSUE #15742: Application shutdown hooks
## Description

I would like have the ability to register shutdown hooks to have the Quarkus shutdown tasks wait until all registered hooks have terminated or timed out. This creates the possibility to implement graceful shutdown for end-user tasks to properly shutdown before Quarkus starts shutting down e.g. entity managers, executors and other services that could still be needed while properly shutting down the end-user tasks .

Of course there is @PreDestroy, but that doesn't seem to block the Quarkus shutdown process in my experience. It can be done now listening to the `ShutdownEvent`, but it seems a bit cumbersome and I am not sure it would work in all circumstances.

```java
@ApplicationScoped
public class ServiceLifeCycle {

    @Inject
    SampleService service;

    void onStop(@Observes ShutdownEvent ev) {
        service.shutdown()
                .completeOnTimeout(null, 10, TimeUnit.SECONDS)
                .join();
    }
}

```

Quarkus would need to guarantee all user defined shutdownhooks are called in the order they are registered and finished or timed out before starting the Quarkus shutdown tasks.

## Implementation ideas
One idea could be to do this using an extension and have it register `ShutdownBuildItems`, but I think it deserves a more prominent position. I would rather see something like the following options:

* `Quarkus.addShutdownHook( Runnable r )`
* `Quarkus.addShutdownHook( Runnable r, long timeout, TimeUnit unit )`
* `Quarkus.addShutdownHook( CompletableFuture<Void> cf )`
* `Quarkus.addShutdownHook( CompletableFuture<Void> cf, long timeout, TimeUnit unit )`

### PR DESCRIPTION
**Pull request by bpasson**
Preliminary PR which fixes #15742 to create a discussion on the specific implementation.

@geoand The current implementation hooks into the `Application#stop(Runnable r)` method. All other functionality is basically static. My gut tells me it should be part of `Application` or `ApplicationLifecyleManager` or ultimately `ShutdownContext`, but I need some pointers to make that happen.

Furthermore, I'd like to have some testcases for this functionality, but don't see where to put them. The runtime module seems to have none which test the shutdown procedure currently. Any hints on where to put some testcases.

Documentation is other than Javadoc has not been created yet.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for starting this.

I actually have a fundamental question about the whole feature:

What is the problem with using `@Observes ShutdownEvent ev` and how would this solution be better?

**Comment by bpasson** [comment]
@geoand that is a very good question and I thought about it before opening the original issue. In itself `@Observes ShutdownEvent ev` works great. The proposed solution differs in two ways.

1. The shutdown hooks are run in a blocking fashion, which removes the need to implement the blocking parts yourself in the `ShutdownEvent` listener.
2. The order in which shutdown hooks are run is known up front, in reverse order of registration, like ShutdownContext does. Achieving this requires a bit of juggling with `@Priority` annotation on the `ShutdownEvent` listeners.

I'm not saying this solution is better. In my opinion it adds an extra option to add user code to the shutdown sequence which executes in a predictable order. It might be the extra option is unwanted. If that is the case or not is up to you.

The concerns I have with current implementation of this option still stand and would need to be resolved if it is decided to continue with this PR.

What do you think?

**Comment by geoand** [comment]
> The concerns I have with current implementation of this option still stand and would need to be resolved if it is decided to continue with this PR.

Totally understood! I just want to establish that this new API is actually something want.

> The shutdown hooks are run in a blocking fashion, which removes the need to implement the blocking parts yourself in the ShutdownEvent listener.

Are you saying that methods that `@Observe ShutdownEvent` do not block the shutdown? @mkouba is this true?

> The order in which shutdown hooks are run is known up front, in reverse order of registration, like ShutdownContext does. Achieving this requires a bit of juggling with @Priority annotation on the ShutdownEvent listeners.

To be honest, I think I prefer the `@Priority` way of ordering things, because you pretty much know throughout the entire code base what the ordering is, whereas with the programmatic API you really don't have a clue.

**Comment by mkouba** [comment]
> > The shutdown hooks are run in a blocking fashion, which removes the need to implement the blocking parts yourself in the ShutdownEvent listener.
> 
> Are you saying that methods that `@Observe ShutdownEvent` do not block the shutdown? @mkouba is this true?

I'm not sure if I understand the question but the `ShutdownEvent` is fired synchronously in a runnable registered via `io.quarkus.runtime.ShutdownContext.addShutdownTask(Runnable)`, i.e. it should block until all notified observer methods complete.

**Comment by geoand** [comment]
That is what I thought as well...

**Comment by bpasson** [comment]
Ok it is becoming more clear to me. It seems this PR might be pointless. I do have some questions though as it is not completely clear to me what runs in which order.

1. Is the shutdown task for running `ShutdownEvent` observers always registered last with the shutdown context to be sure it always runs at first once shutdown is requested?
2. How is `ShutdownEvent` related to `PreDestroy` from CDI, does it run before or after?
3. Extension can also add shutdown tasks to the shutdown context, the order in which they are added is the order in which they are dependent on each other?

**Comment by geoand** [comment]
@mkouba maybe the documentation needs to be enhanced with the various points touched in this thread?

**Comment by mkouba** [comment]
> @mkouba maybe the documentation needs to be enhanced with the various points touched in this thread?

Yep, that would make sense. Unfortunately, I'm not quite sure if I will know the answers ;-).

>   1. Is the shutdown task for running ShutdownEvent observers always registered last with the shutdown context to be sure it always runs at first once shutdown is requested?

Two points. 1. [Tasks are executed in the reverse order that they are added](https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/ShutdownContext.java#L11). 2. This task is registered after a shutdown task that shuts down the CDI container, i.e. is executed before this task (which makes sense because we can't deliver CDI events if the CDI container is down).

> 2. How is ShutdownEvent related to PreDestroy from CDI, does it run before or after?

It's not related. A `@PreDestroy` callback is always bound to the lifecycle on a bean. So you can't really say when it's invoked without more information about the bean it is bound to.

> 3. Extension can also add shutdown tasks to the shutdown context, the order in which they are added is the order in which they are dependent on each other?

It depends on the [build items produced and consumed by the build steps](https://quarkus.io/guides/writing-extensions#build-steps) that register the shutdown tasks.

**Comment by geoand** [comment]
> Yep, that would make sense. Unfortunately, I'm not quite sure if I will know the answers ;-).

Which answers do you think you don't know? It seems like you answered all the questions :)

**Comment by bpasson** [comment]
@mkouba @geoand Thanks for clarifying. With this information I suppose ShutdownEvent kan be used for specific user shutdown tasks. I think we can safely close this PR and the linked issue #15742. Do you agree?

> > 3. Extension can also add shutdown tasks to the shutdown context, the order in which they are added is the order in which they are dependent on each other?
> 
> It depends on the [build items produced and consumed by the build steps](https://quarkus.io/guides/writing-extensions#build-steps) that register the shutdown tasks.

This puzzles me a bit. Say you have an extension A with a shutdown task that depends on the `ManagedExecutor` for context propagation, how can you make sure it is not shutdown before extension A's shutdown task is finished?

**Comment by mkouba** [comment]
> This puzzles me a bit. Say you have an extension A with a shutdown task that depends on the `ManagedExecutor` for context propagation, how can you make sure it is not shutdown before extension A's shutdown task is finished?

You'd need to make sure that your shutdown task is registered AFTER the shutdown task registered by the CP extension, i.e. after [this build step](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-context-propagation/deployment/src/main/java/io/quarkus/smallrye/context/deployment/SmallRyeContextPropagationProcessor.java#L88-L108). Unfortunately, it seems that this build step does not produce a build item you can consume/depend on.

Feel free to file an issue to create a [marker build item](https://quarkus.io/guides/writing-extensions#empty-build-items) produced by the CP extension when the runtime init finished.

**Pull request closed without merging**
