### PR TITLE
Bump wildfly-common version to 1.7.0.Final

### LINKED ISSUE #36686: Quarkus native tests fail with latest GraalVM CE for JDK 22, 24.0.0-dev builds due to wildfly substitution
### Describe the bug

Quarkus native tests fail with latest GraalVM CE for JDK 22, 24.0.0-dev builds due to wildfly substitution.

The error is:

```
Error: Substitution target for org.wildfly.common.Substitutions$Target_GraalDirectives is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for org.wildfly.common.Substitutions$Target_GraalDirectives is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1098)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1047)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1043)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:375)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:353)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1058)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:924)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:595)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:555)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:540)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
```

### Expected behavior

Tests should build and pass.

### Actual behavior

Tests fail to build.

### How to Reproduce?

1. Grab a dev build of GraalVM CE with https://github.com/oracle/graal/pull/7650 and https://github.com/oracle/graal/pull/7621 (none available yet) or build it from source:
  ```
git clone https://github.com/graalvm/mx
git clone https://github.com/oracle/graal
cd graal
../mx/mx fetch-jdk --java-distribution labsjdk-ce-latest
export JAVA_HOME=/path/to/downloaded/labsjdk
../mx/mx --primary-suite-path substratevm --components="Native Image,LibGraal,Truffle SVM Macro" --native-images=native-image,lib:jvmcicompiler build
export GRAALVM_HOME=$(pwd)/sdk/latest_graalvm_home
```

2. `export GRAALVM_HOME=/path/to/the/deb-build`
3. `./mvnw -Dnative -pl integration-tests/jpa -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package -Dquarkus.native.container-build=false`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

24.0.0-dev

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The issue is caused because wildfly tries to [substitute a GraalVM internal class](https://github.com/wildfly/wildfly-common/blob/44dc271fa0893788f51842a8b34313e1cb6c1519/src/main/java/org/wildfly/common/Substitutions.java#L62) that is no longer available due to the package renaming in https://github.com/oracle/graal/pull/7650 and https://github.com/oracle/graal/pull/7621

### PR DESCRIPTION
**Pull request by zakkak**
Closes https://github.com/quarkusio/quarkus/issues/36686

### CODE REVIEW

**Comment by jerboaa** [comment]
> Good point.
> 
> Please see https://github.com/graalvm/mandrel/actions/runs/6798911351

Heh, `22+22` doesn't work. Could you try with `22+21` and/or with a local patch for latest JDK 22 support? Failing that, a local test is sufficient for me too :)

**Comment by zakkak** [comment]
Unfortunately there is no way to instruct our CI to use a specific JDK 22 release so I will run with GraalVM CE instead of Mandrel. Running locally is also an option but will take too long to run all the tests.

https://github.com/graalvm/mandrel/actions/runs/6799010528

**Comment by jerboaa** [comment]
> Unfortunately there is no way to instruct our CI to use a specific JDK 22 release so I will run with GraalVM CE instead of Mandrel. Running locally is also an option but will take too long to run all the tests.
> 
> https://github.com/graalvm/mandrel/actions/runs/6799010528

Thanks! GraalVM CE is fine.

**Comment by jerboaa** [comment]
> Unfortunately there is no way to instruct our CI to use a specific JDK 22 release so I will run with GraalVM CE instead of Mandrel. Running locally is also an option but will take too long to run all the tests.
> 
> https://github.com/graalvm/mandrel/actions/runs/6799010528

Are you sure this was building the correct quarkus version? Looks to me it build revision `ff9047485f3169931f2def3e609f5d2cc14a2b76`. Shouldn't it build `4000072d054317495d514f165d94c82b32df9983`? Either way, the test failures are still the same in the above test run.

**Comment by zakkak** [comment]
@jerboaa good catch, I was working on another issue and used the wrong branch...

I hope _third time's the charm_
https://github.com/graalvm/mandrel/actions/runs/6803742613

**Comment by geoand** [comment]
I have no idea what this library does, I'll leave reviewing to someone else

**Review by gsmet — APPROVED** [review]

**Pull request merged**
