### PR TITLE
Revert "Improve the OIDC/OAuth2 documentation"

### PR DESCRIPTION
**Pull request by gastaldi**
This reverts commit dfdcad9218485cbbed28fb741c41eb2ffb88b274.

I had to revert it because of https://github.com/quarkusio/quarkus/pull/10653#issuecomment-657671432

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by sberyozkin** [comment]
@gastaldi @geoand thanks, what is the correct sequence to fix it now, I think I deleted the local branch ?

**Comment by sberyozkin** [comment]
May be we have reverted it too fast :-) ?

**Comment by sberyozkin** [comment]
Never mind, just ignore me, obviously it was causing the PR build failures, sorry for a mess

**Comment by sberyozkin** [comment]
@gastaldi So what do I do now, create a branch, revert this revert PR and add another commit which fixes the issue ? It will probably be a messy commit sequence...I think it would be simpler just to create a new PR completely...

**Comment by gastaldi** [comment]
@sberyozkin Yeah, I think the best is to create a new commit based on the reverted commit. You can use `git revert --no-commit` to not commit the reversion

**Comment by sberyozkin** [comment]
@gastaldi @geoand sorry for being a bit edgy about the revert, I was so happy during my walk that I could continue with the next doc updates round tomorrow :-). But I think I'll create an issue, the PR was green as far as I recall... thanks

**Comment by sberyozkin** [comment]
Yeah, `docs` is clean which is what I was checking, but `documentation` is broken

**Comment by gastaldi** [comment]
There is something wrong with CI. The Documentation build shouldn't have passed

**Comment by geoand** [comment]
No worries @sberyozkin!

**Pull request merged**
