### PR TITLE
Allow extensions to exclude classes to be found in the JAXB context

### LINKED ISSUE #31646: Allow third party extensions to avoid validating the default JAXB context
### Describe the bug

The change 46f348c85934b914f8d986f4f4535134e4ffba03 by @Sgitario has brought hard times to Quarkus CXF and Camel Quarkus. Basically all our CXF related tests fail, because duplicate JAXB classes seem to a normal situation in CXF. 

Here an example of the stack trace see when running [quarkus-cxf-integration-test-client](https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security-client): 

```
Caused by: java.lang.IllegalStateException: Failed to configure JAXB context
        at io.quarkus.jaxb.deployment.JaxbProcessor.validateContext(JaxbProcessor.java:395)
        at io.quarkus.jaxb.deployment.JaxbProcessor.setupJaxbContextConfig(JaxbProcessor.java:318)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "{http://www.w3.org/2005/08/addressing}EndpointReferenceType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
        this problem is related to the following location:
                at org.apache.cxf.ws.addressing.EndpointReferenceType
                at public org.apache.cxf.ws.addressing.EndpointReferenceType org.apache.cxf.ws.addressing.ObjectFactory.createEndpointReferenceType()
                at org.apache.cxf.ws.addressing.ObjectFactory
                at protected java.util.List org.apache.cxf.ws.addressing.ReferenceParametersType.any
                at org.apache.cxf.ws.addressing.ReferenceParametersType
        this problem is related to the following location:
                at jakarta.xml.ws.wsaddressing.W3CEndpointReference

        at org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:83)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:421)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:255)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1115)
        at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:144)
        at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:44)
        at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:368)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:605)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:546)
        at io.quarkus.jaxb.deployment.JaxbProcessor.validateContext(JaxbProcessor.java:393)
        ... 10 more
```

In this particular case, both conflicting classes come through transitive dependencies of CXF:

* `jakarta.xml.ws.wsaddressing.W3CEndpointReference` comes via

```
io.quarkiverse.cxf:quarkus-cxf-integration-test-client:2.0.0-SNAPSHOT:jar:
        -> io.quarkiverse.cxf:quarkus-cxf:2.0.0-SNAPSHOT:jar:
        -> org.apache.cxf:cxf-rt-frontend-jaxws:4.0.0:jar:
        -> org.apache.cxf:cxf-rt-bindings-soap:4.0.0:jar:
        -> jakarta.jws:jakarta.jws-api:3.0.0:jar
```

* `org.apache.cxf.ws.addressing.EndpointReferenceType` comes via

```
io.quarkiverse.cxf:quarkus-cxf-integration-test-client:2.0.0-SNAPSHOT:jar:
        -> io.quarkiverse.cxf:quarkus-cxf:2.0.0-SNAPSHOT:jar:
        -> org.apache.cxf:cxf-rt-frontend-jaxws:4.0.0:jar:
        -> org.apache.cxf:cxf-core:4.0.0:jar
```

I doubt we can exclude the artifacts and I doubt we can exclude the classes via `quarkus.jaxb.exclude-classes`.

Advising all users of `camel-quarkus-cxf` and `quarkus-cxf` to always have `quarkus.jaxb.validate-jaxb-context=false` in their `application.properties` does not seem to be a good UX.

I think the best way forward would be to find a programmatic way of disabling the JAXB context validation. 

I see three options:

### B. Split quarkus-jaxb into quarkus-jaxb-core and quarkus-jaxb

quarkus-jaxb would contain the config, the properties, the validation and the default context bean

quarkus-jaxb-core would keep all the rest. 

quarkus-cxf would depend only on quarkus-jaxb-core. If quarkus-cxf users need to inject the default JAXB context, they are on their own to add quarkus-jaxb dependency and resolve the conflicts.

## Assessment:

I see C as rather problematic. I think it would be hard to find the right semantics (esp. how it would combine with `quarkus.jaxb.validate-jaxb-context=false/true`), keep it transparent enough for end users and even document comprehensibly.

If A is technically possible, we should go with A. What do others think?

This blocks 
* https://github.com/apache/camel-quarkus/issues/4603
* https://github.com/quarkiverse/quarkus-cxf/issues/730

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/31646

### CODE REVIEW

**Comment by gsmet** [comment]
Hmmm, sorry but I will have to ask candid questions: I don't understand why we are trying to push all the classes to a unique JAXBContext.

Can't we imagine that an extension is creating a JAXBContext with the classes that are actually needed and this subset wouldn't contain any collisions?

I wasn't entirely sure about this collision thing when the original PR was created and I have even more doubts now.

Note that I'm seeing that from very far as it has been a long time since I played with this extension but I would appreciate if we could discuss this and if you could explain me why I'm all wrong :). Thanks!

**Comment by Sgitario** [comment]
The idea was to ease the usage of JAXB to be similar to Jackson, where you can use the same ObjectMapper instance to serialize/deserialize objects into JSON. 

Having said that, I'm not even sure if I was who introduced this :/, but to me, it makes sense how it works.

**Comment by gsmet** [comment]
I don't know. I'm not convinced it is a good idea given how many problems it causes.

Maybe it should be done the other way and have the extensions actually register the classes, instead of excluding them? But even so, I'm not sure if it's a good idea to have a unique JAXBContext with everything.

**Comment by Sgitario** [comment]
> I don't know. I'm not convinced it is a good idea given how many problems it causes.
> 
> Maybe it should be done the other way and have the extensions actually register the classes, instead of excluding them? But even so, I'm not sure if it's a good idea to have a unique JAXBContext with everything.

I'm not aware of how many problems this change is causing (but the issue with the BuildIT and the camel extensions, though these two issues were due to transitive dependencies that ran into conflicts in JAXB). 

Maybe, instead of trying to see if this is done for good or the opposite, we should analyze or clarify why this extension is being used and its expectations. As far as I see, this extension is doing two things:
1. Adapt JAXB types to be compatible with native
2. Discover all the JAXB types and bind the discovered JAXB types to a generated JAXBContext

At the moment and as far as I know, the generated JAXBContext is used by the Resteasy Reactive and the Resteasy Reactive REST Client extensions. 

Therefore, maybe and as @ppalaga suggested, it makes sense to split this extension into one for point 1. and keep the jaxb extension for point 2.

In the future, we could also refine the logic that includes all the discovered JAXB types to the JAXBContext to be less intrusive (I'm not sure how we could do this, since we don't know if one class is coming from a direct dependency or a transitive dependency, maybe does the Index help with this?).

**Comment by Sgitario** [comment]
Closing as the linked issue has been fixed by https://github.com/quarkusio/quarkus/pull/31666.
If needed, we can always include this in the future.

**Pull request closed without merging**
