### PR TITLE
Take entity class transformations into account during Hibernate proxy pre-generation

### LINKED ISSUE #8932: Access to public field returns null for Hibernate entity lazy-loaded from polymorphic toOne association
**Describe the bug**
Since release 1.3.2.Final, I noticed hibernate lazy load is no long working properly in my project.  here is the hierarchy of the entities:

```
@MappedSuperclass
public abstract class EntityBase extends PanacheEntityBase {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;
}

@Entity
public class EntityA extends EntityBase  {
   @Column(nullable = false)
    public String name;
}

@Entity
**@Inheritance(strategy = InheritanceType.JOINED)**
public class EntityB extends EntityBase  {
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	public EntityA a;
}

@Entity
public class EntityC  extends EntityBase  {
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	public EntityB b;
        @Column(nullable = false)
        public String uuid;
}

and I'm getting NPE when accessing the entities this way:

EntityC  c= EntityC .find("uuid=?1", id).firstResult();

if (c.b.a.name.equals("") { ... 
}
```

c.b.a is null, because c.b is a hibernate proxy and it is not getting lazy loaded.   everything worked fine before 1.3.2.Final.

**Expected behavior**
Hibernate lazy load works for all entities.

**Actual behavior**
Hibernate lazy load not working for entities annotated with Inheritance

**To Reproduce**
see description above. 

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.url = jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
quarkus.datasource.driver = com.mysql.cj.jdbc.Driver
quarkus.datasource.username = usr
quarkus.datasource.password = pwd

quarkus.hibernate-orm.database.generation = none
quarkus.hibernate-orm.log.sql = true
quarkus.hibernate-orm.dialect = org.hibernate.dialect.MySQLDialect
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux orchid 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`:   java 11.0.1 2018-10-16 LTS
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.3.2.Final and 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #8932 

~Creating as draft, because this fix will only work after https://github.com/hibernate/hibernate-orm/pull/4845 is merged, released, and we upgrade to the corresponding Hibernate ORM version.~ => Done

The core of this PR is simple enough to understand: the Hibernate ORM bytecode enhancer works on class definitions, and will only enhance those methods it can see in those class definitions. So any methods added by Panache (such as getters/setters) must be added before the Hibernate ORM bytecode enhancer starts to work, and thus we need to pass already-transformed classes to the Hibernate ORM bytecode enhancer, not the original bytecode.

This requires a bit of reorganization of build steps to pass the transformed bytecode to the build step that performs Hibernate ORM proxy generation. This also requires tuning the input to the proxy generation (again, to pass transformed bytecode).

One challenge was that the reorganization of build steps led to a circular dependency in some edge cases involving resteasy reactive. That circular dependency was artificial, however: one of the dependencies between build steps was only there to pass information that would only be passed to bytecode recorders and used during static init... so nothing that prevents build steps from running out of order.

To solve the circular dependency, I had to add a feature to bytecode recorders: the ability to define constants in recorders to break circular dependencies between build steps. See the second commit "Ability to define constants in recorders to break circular dependencies between build steps".
Compared to simply passing the value to a recorder proxy, defining a constant allows a build step A to push information to code recorded by another build step B, without introducing a dependency from build step B to build step A.

I know this new bytecode recorder feature would deserve a separate PR, but I thought it would be better to see a practical use of that feature in the same PR. And you can see a practical use in the third commit: "Pass pre-generated proxies to HibernateOrmRecorder as a constant".

### CODE REVIEW

**Comment by luca-bassoricci** [comment]
Does this ticket also affect PanacheEntity `@Inject`-ed as `@RequestScoped`?

**Comment by yrodiere** [comment]
#24362 was merged, upgrading to ORM 5.6.7.Final, so tests added in this PR should now pass. Marking as ready for review, let's see what CI thinks of that...

**Comment by yrodiere** [comment]
I'm investigating the test failures.

**Comment by yrodiere** [comment]
Looks like the problem was simply a missing build item after my changes, to make sure phase 6 happens after phase 5 in `ArcProcessor`. Marking as ready for review to have CI run all tests, let's see how it goes.

**Comment by yrodiere** [comment]
One build step of resteasy reactive seems to be depending on `BeanContainerBuildItem` but also producing a `BytecodeTransformerBuildItem`, which is causing cyclic dependency problems. I'll try to solve that...

**Comment by yrodiere** [comment]
Alright, I think I finally managed to solve the circular dependency problem in a clean way. I had to add a feature to bytecode recorders, though: the ability to define constants.

I updated the PR description to explain the full reasoning behind all changes in this PR.

@gsmet This ended up touching areas I'm not very familiar with... would you mind having a look? Or should I ask Stuart? As I understand he's a bit busy these days.

**Review by gsmet — APPROVED** [review]
Thanks for this work. Let's get it in once CI is green.

**Comment by yrodiere** [comment]
Thanks @gsmet!

**Comment by Sanne** [comment]
awesome :) thank you both

**Pull request merged**
