### PR TITLE
Added link of cache quickstart in cache.adoc

### PR DESCRIPTION
**Pull request by saumya1singh**
Hey @loicmathieu !
PR for #12521
I have added the cache quickstart link in the guide.

### CODE REVIEW

**Comment by loicmathieu** [comment]
Thanks @SaumyaSingh1 if there is multiple guides with the same issue, maybe you can open a single PR with all the modification to avoid too much PR.

**Comment by loicmathieu** [comment]
OK, I'll approve this one then.

**Review by loicmathieu — APPROVED** [review]
LGTM

**Comment by SaumyaSingh1** [comment]
@loicmathieu So as of now I have added missing quickstarts in the guides. 
I think the PR is ready to be merged .

**Comment by gastaldi** [comment]
Thanks!

**Comment by loicmathieu** [comment]
Thanks, and congrats for your first PR (I think) ;)

**Comment by SaumyaSingh1** [comment]
Thank you so much @loicmathieu for the help 💙
Yes it was my first PR here :)

**Pull request merged**
