### PR TITLE
Ensure that a non-indexed entry doesn't break generic type resolution

### PR DESCRIPTION
**Pull request by geoand**
This can happen if say some interface extends a JDK interface and there
is no reason the type resolution should fail because of it

### CODE REVIEW

**Comment by geoand** [comment]
cc @lburgazzoli who initially brought this to me

**Review by FroMage — COMMENTED** [review]
Sorry, I don't understand the change.

What I think this is doing is that for external callers to `findParametersRecursively` this will still throw if not found, but if it recurses inside, it will return `null` instead.

So… I assume `fetchFromIndex` is the one doing the throwing, and then it will only throw for the first-level call, not for any recursion?

**Comment by geoand** [comment]
> What I think this is doing is that for external callers to `findParametersRecursively` this will still throw if not found, but if it recurses inside, it will return `null` instead.
> 

What external callers?

> So… I assume `fetchFromIndex` is the one doing the throwing, and then it will only throw for the first-level call, not for any recursion?

Yes, `fetchFromIndex` is the method that throws.

My whole point is that I don't want th exception to terminal when looking up superclasses or interfaces

**Comment by FroMage** [comment]
> What external callers?

The function that calls it the first time. It's not going to just call itself ;)

> My whole point is that I don't want th exception to terminal when looking up superclasses or interfaces

OK. Got it.

My only worry is that this is changing the behaviour for all users of that method, and so it may be hiding the cause of a further error.

I think there are two cases where we can fail to find the parameter recursively:

- It's in a super class that is missing from the index, we won't find it anywhere else and the user must know that we failed to find it because the super class should be indexed.
- It's not in a super class, which is missing anyway, and we can go on and find it later from another super class that is indexed.

I think you've treated the second case. I worry about the first case, because the result is that we'll tell the user we could not find the parameter (it will be `null`) but we won't be able to tell him why (the class `Foo` was not indexed).

OTOH, if the contract of the external caller to `findParametersRecursively` is that it can return `null` and that's not an error, then perhaps we never want any exception. But I don't think that's the case. I think the `null` return value is only valid for recursion calls, to allow further lookup.

So perhaps the safer thing to do is to record which types are not indexed during recursion, and keep going. If at the end of the external call we have a result, then ignore all those not-indexed errors. If we don't, then raise an error explaining which types were not indexed that could be the cause of this error?

WDYT?

**Comment by geoand** [comment]
> > What external callers?
> 
> The function that calls it the first time. It's not going to just call itself ;)
> 
> > My whole point is that I don't want th exception to terminal when looking up superclasses or interfaces
> 
> OK. Got it.
> 
> My only worry is that this is changing the behaviour for all users of that method, and so it may be hiding the cause of a further error.
> 
> I think there are two cases where we can fail to find the parameter recursively:
> 
> * It's in a super class that is missing from the index, we won't find it anywhere else and the user must know that we failed to find it because the super class should be indexed.
> * It's not in a super class, which is missing anyway, and we can go on and find it later from another super class that is indexed.
> 
> I think you've treated the second case. I worry about the first case, because the result is that we'll tell the user we could not find the parameter (it will be `null`) but we won't be able to tell him why (the class `Foo` was not indexed).
> 
> OTOH, if the contract of the external caller to `findParametersRecursively` is that it can return `null` and that's not an error, then perhaps we never want any exception. But I don't think that's the case. I think the `null` return value is only valid for recursion calls, to allow further lookup.
> 

Yes, I completely agree

> So perhaps the safer thing to do is to record which types are not indexed during recursion, and keep going. If at the end of the external call we have a result, then ignore all those not-indexed errors. If we don't, then raise an error explaining which types were not indexed that could be the cause of this error?
> 
> WDYT?

 Sure yeah, that makes sense. I'll update the PR on Monday

**Comment by FroMage** [comment]
OK great, no rush :)

**Comment by geoand** [comment]
PR updated as per your suggestion and tests added

**Review by FroMage — APPROVED** [review]
Great!

**Comment by geoand** [comment]
It seems like the failure in `JAXRSClient0021` is actually caused by this...

**Comment by geoand** [comment]
Fixed

**Pull request merged**
