### PR TITLE
Add support KubernetesHealthStartupPathBuildItem parse to generated in kubernetes yaml.

### LINKED ISSUE #29482: Kubernetes extension support startupProbe
### Description

`startupProbe` hadn't generated in kubernetes yaml.

this is my dependencies:
```xml
        <dependency>
            <!--https://quarkus.io/guides/deploying-to-kubernetes-->
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes</artifactId>
        </dependency>
        <dependency>
            <!--health-->
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>

```

### Implementation ideas

1. add startupProbe in `KubernetesConfig`
2. add code in `KubernetesCommonHelper#createDecorators and KubernetesCommonHelper#createProbeDecorators`
3. add code in ` KubernetesCommonHelper#createStartupProbe`

### PR DESCRIPTION
**Pull request by naah69**
Closes https://github.com/quarkusio/quarkus/issues/29482

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
The changes look good to me. However, some tests need to be added in `integration-tests/kubernetes/quarkus-standard-way`  to cover these changes.

**Comment by naah69** [comment]
> The changes look good to me. However, some tests need to be added in `integration-tests/kubernetes/quarkus-standard-way` to cover these changes.

OK，i will replenish it.

**Review by iocanel — CHANGES_REQUESTED** [review]
I'd like to see some tests too.

**Comment by gsmet** [comment]
@naah69 are you still willing to finalize this? (it will need a rebase)

Thanks.

**Comment by Sgitario** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/30246

**Pull request closed without merging**
