### PR TITLE
Add ApplicationArchive.getResolvedDependency()

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
CC @vsevel

**Review by aloubyansky — APPROVED** [review]
Thanks @Ladicek

**Comment by mkouba** [comment]
> Some changes in `independent-projects/boostrap` are technically breaking, but I take it this is in fact not a public API?

I would not replace those methods but introduce new ones and deprecate the old ones.

It's public API in the sense that any extension can use it and there's no clear contract defined...

**Comment by Ladicek** [comment]
So there's actually exactly one change that breaks "public" API, this constructor:

```diff
-public PathTreeClassPathElement(PathTree pathTree, boolean runtime, ArtifactKey dependencyKey) {
+public PathTreeClassPathElement(PathTree pathTree, boolean runtime, ResolvedDependency resolvedDependency) {
```

All other changes are in fact compatible due to `default` methods.

It is unfortunately not straightforward to preserve the old constructor. While it's trivial to obtain an `ArtifactKey` from `ResolvedDependency`, it is not possible to do the opposite.

**Review by mkouba — APPROVED** [review]

**Comment by Ladicek** [comment]
To be absolutely precise, there's also one other "breaking" change:

```diff
-public ApplicationArchiveImpl(IndexView indexView, OpenPathTree openTree, ArtifactKey artifactKey) {
+public ApplicationArchiveImpl(IndexView indexView, OpenPathTree openTree, ResolvedDependency resolvedDependency) {
```

But I'm sure everyone agrees that this is _not_ a public API.

**Pull request merged**
