### PR TITLE
Recreate all metric registries during reload

### LINKED ISSUE #7018: Recreate all metric registries on startup?
Currently, the behavior of dev mode is that `application` metric registry will be discarded and re-created on reload. This however does not include the `vendor` and `base` registries, so extensions must take care of removing their metrics properly in case that they have to be re-registered on reloading. 
While this could theoretically allow some specific metrics, in cases where appropriate, to just 'survive' a reload and continue without change, we're not doing this for any metrics at the moment, and there's actually not many cases where this would work. I can only think of some JVM metrics in the `base` scope. Most other metrics can't do this, especially if they need any sort of reference to application code, because application will be loaded by a different class loader.

That said, my opinion is that allowing this optimization might be not worth it, because it forces extensions to include cleanup code (only those extensions that are registering metrics directly rather than using `MetricBuildItem`, which takes care of the cleanup automatically).
If we changed the behavior such that all registries will get re-created and all metrics will have to be re-registered, we can do a code cleanup and remove all code (shutdown tasks or other) that takes care of removing a metric before it can be re-created.

Note: the cleanup actually happens here in SmallRye code https://github.com/smallrye/smallrye-metrics/blob/2.3.3/implementation/src/main/java/io/smallrye/metrics/MetricRegistries.java#L64

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes https://github.com/quarkusio/quarkus/issues/7018

### CODE REVIEW

**Comment by geoand** [comment]
I like it @jmartisk!
Any chance we can get a dev mode test for this? I am not really concerned about it working - I'm sure it does, I just want to make sure some other change irrelevant doesn't brake it in the future

**Comment by jmartisk** [comment]
Hey @geoand,  `DevModeMetricsTest` basically already verifies this for application metrics, this PR just extends the behavior to other metric scopes.
Given that this is meant for `base` and `vendor` metrics, which are managed by Quarkus extensions, it would make sense to have a test where an extension registers a metric, but I'm not sure how to do that because `QuarkusDevModeTest` does not seem to support adding build chain customizers (unlike `QuarkusUnitTest`), so I think we can't right now create a dev mode test that adds a dynamically added "extension" :(
So the test would have to register a `base`/`vendor` metric within application code, which is not really correct usage, so adding such test sounds awkward.

**Comment by geoand** [comment]
@jmartisk in that case you would probably have to add one of ugly test like this: https://github.com/quarkusio/quarkus/blob/master/integration-tests/maven/src/test/java/io/quarkus/maven/it/DevMojoIT.java

**Comment by jmartisk** [comment]
That looks quite awful for something that would only verify that `base` and `vendor` scopes get cleaned up too :)

**Comment by geoand** [comment]
I'll leave it up to you to decide, but I personally for having something that we'll keep potentialy erroneous future refactorings in check :)

**Comment by jmartisk** [comment]
I added a tiny test that creates base/vendor metrics in application code, it's not how it's supposed to be done in reality, but the test will still verify what it needs to verify, so I suppose it's a valid test

**Comment by geoand** [comment]
Cool, thanks

**Review by geoand — APPROVED** [review]

**Comment by jmartisk** [comment]
There were some unrelated CI failures, I rebased it and let's try again

**Pull request merged**
