### PR TITLE
ArC: EventMetadata - implement the getInjectionPoint() method

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Review by manovotn — COMMENTED** [review]
Nice, I actually tried something similar yesterday but ran into a Gizmo wall and didn't finish it :)

@mkouba I took your code and ran it against the [TCK test that asserts just this](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/event/metadata/injectionpoint/EventMetadataInjectionPointTest.java) and found one failure.
It's not directly related to this, but we seem to be too generous adding `@Any` to events where TCK doesn't expect it. Following [test fails (both qualifier set assertions)](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/event/metadata/injectionpoint/EventMetadataInjectionPointTest.java#L138-L146) because we will always add `@Any` to the mix. Want to fix it here or should we do a separate PR?

**Comment by mkouba** [comment]
> It's not directly related to this, but we seem to be too generous adding `@Any` to events where TCK doesn't expect it. Following [test fails (both qualifier set assertions)](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/event/metadata/injectionpoint/EventMetadataInjectionPointTest.java#L138-L146) because we will always add `@Any` to the mix.

Hm, so the `EventMetadata.getQualifiers()` should include `@Any` (because _"Every event has the qualifier @javax.enterprise.inject.Any, even if it does not explicitly declare this qualifier._" and it seems to be tested [here](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/event/metadata/EventMetadataTest.java#L68)) but `EventMetadata.getInjectionPoint().getQualifiers()` should only contain `@Default`?

> Want to fix it here or should we do a separate PR?

Let's fix it here.

**Comment by mkouba** [comment]
@manovotn it should be fixed now.

**Comment by manovotn** [comment]
> Hm, so the EventMetadata.getQualifiers() should include @Any (because "Every event has the qualifier @javax.enterprise.inject.Any, even if it does not explicitly declare this qualifier." and it seems to be tested [here](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/event/metadata/EventMetadataTest.java#L68))

Yes, this basically says you should add the `@Any` qualifier once you fire the event in case it's not already present.

> EventMetadata.getInjectionPoint().getQualifiers() should only contain @Default?

Seems like it although I agree it seems somewhat weird. CDI spec isn't exactly clear in this (meaning the definition of the built-in `Event` bean), it doesn't rule out `@Any` being added.

**Review by manovotn — APPROVED** [review]
Thanks!

**Comment by manovotn** [comment]
For future reference, related to https://github.com/quarkusio/quarkus/issues/28558

**Pull request merged**
