### PR TITLE
Use relocation for changing config properties

### PR DESCRIPTION
**Pull request by dmlloyd**
Follows up on #37445

### CODE REVIEW

**Comment by dmlloyd** [comment]
To check whether the redirection is working, run `integration-tests/hibernate-orm-panache` and check log for `2023-12-21 10:59:08,537 WARN  [io.qua.config] (build-38) Unrecognized configuration key "quarkus.package.vineflower.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo` or similar in second set of tests (`prod-mode` execution).

**Comment by radcortez** [comment]
I pushed a commit to improve the recording of system properties and env variables, which filter properties, and then apply the interceptors, which should work better with the relocate interceptor. Let me know if that works.

**Comment by dmlloyd** [comment]
Looks good, thanks @radcortez!

**Comment by dmlloyd** [comment]
This is out of date; replaced by #39295.

**Pull request closed without merging**
