### PR TITLE
Update to smallrye-jwt-1.1-1.0.0

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@starksm64 FYI, work in progress

**Review by starksm64 — APPROVED** [review]
These look fine once the CI is passing with a valid smallrye-jwt release

**Comment by gsmet** [comment]
@sberyozkin can you squash the 2 commits? I don't think we want an intermediary commit introducing a SNAPSHOT version. Thanks!

**Comment by sberyozkin** [comment]
@starksm64 thanks, waiting for the CI results with the valid release

**Comment by sberyozkin** [comment]
@gsmet I did it manually, or do you mean use 'Squash and Merge' option from the UI ? I always use it

**Comment by gsmet** [comment]
@sberyozkin I don't think you can squash and merge when using a merge commit workflow, unfortunately. That's why I asked. So thanks for doing it!

**Comment by sberyozkin** [comment]
@gsmet np, thanks. Hope I did it right as I've always been relying in Squash and Merge button....

**Comment by sberyozkin** [comment]
I guess you meant the use of 'fixup' vs 'squash' - the latter keeps all the log messages (which is what the button uses). Though there is also Rebase and Merge...

**Pull request merged**
