### PR TITLE
Update repository declaration order

### PR DESCRIPTION
**Pull request by glefloch**
This fix change the order of repository declaration in sample test projects.

It should fix release test ci job and tests that fail in PRs.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Review by gsmet — CHANGES_REQUESTED** [review]
Could you explain the rationale here? Do I misunderstand or we will always try to download things instead of using the local cache?

**Comment by glefloch** [comment]
Well not exactly. Errors come from the fact that some artifacts are only partially resolved in the local repository (only the pom is present and not the jar). In that case, gradle don't fallback to the next repository to resolve the `jar`. I opened an issue on gradle for that.

Regarding the resolution, gradle also have a cache for dependencies, dependencies will only download once if they are not already in that cache.

I agree that this is not a durable solution but this avoid to disable those tests.

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@famod looks like there's an issue with the build: `Error when evaluating 'strategy' for job 'native-tests'. (Line: 698, Col: 15): Error reading JToken from JsonReader. Path '', line 0, position 0.,(Line: 69`

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
@gsmet The script is not yet covering this case which was introduced recently: https://github.com/quarkusio/quarkus/commit/9bd76cad3fd96e7dd8ace827bc8cb452575b9636#diff-307c72aded80fc768e1f20cfa0bed2320c3fe4bb815a6996db89d986c972d845
Will send a fix ASAP, it's rather easy.

**Comment by famod** [comment]
@geoand Thing is that in your PR GIB decided to do a full build due to:
```
[INFO] gitflow-incremental-builder execution skipped: Changed path matches regex defined by skipIfPathMatches: .github/native-tests.json
```
and because of that the respective part of the script wasn't run at all (no use filtering any native jobs for a full build).

Nice corner case you hit there! I'll think about make this more fine grained: https://github.com/quarkusio/quarkus/blob/main/pom.xml#L290

**Pull request merged**
