### PR TITLE
Add supported JVM versions badge

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by famod** [comment]
Cool! I "stole" this idea for https://github.com/vackosar/gitflow-incremental-builder 😉

**Comment by geoand** [comment]
I was "inspired" by this: https://github.com/burningwave/core

**Comment by gsmet** [comment]
I'm a bit torn on that one because we don't support 9 or 10 for instance.

**Comment by gsmet** [comment]
Maybe "8 - 11 - 14" would be less misleading.

**Comment by geoand** [comment]
That's fine with me

**Pull request merged**
