### PR TITLE
Dev UI tests updates

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR Migrate tests for the old Dev UI in  `integration tests` to the new `DevUIJsonRPCTest`
Tests needs to stay in integration tests to not create a cyclic dependency 

OIDC Tests are currently disabled in their pom.xml. I'll leave that up to @sberyozkin to complete those tests.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Still need to migrate OIDC

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Do not merge! This PR introduced a cyclic dependency in Maven.

@phillip-kruger you will need to break the cycle somehow.

**Review by cescoffier — CHANGES_REQUESTED** [review]
There is a maven dependency cycle to fix first.

**Comment by phillip-kruger** [comment]
@cescoffier yes I am looking at it

**Comment by phillip-kruger** [comment]
@cescoffier I now changed to use verx client directly (vs using Jakarta ws) for the JsonRPC Test client. Let's see how CI goes now.

**Comment by cescoffier** [comment]
Can you squash and fix the last commit message?

**Review by cescoffier — APPROVED** [review]

**Comment by phillip-kruger** [comment]
@cescoffier squash all in one ?

**Comment by cescoffier** [comment]
Yes

**Comment by phillip-kruger** [comment]
@cescoffier  Done !

**Pull request merged**
