### PR TITLE
Add test for case where @ResponseStatus is used along with @ExceptionHandler

### PR DESCRIPTION
**Pull request by geoand**
Relates to: #16321

### CODE REVIEW

**Comment by geoand** [comment]
Opened as a draft as this requires a new RESTEasy release with includes https://github.com/resteasy/Resteasy/pull/2722

**Comment by gastaldi** [comment]
Is this now ready to be reviewed?

**Comment by geoand** [comment]
I'll check soon

**Comment by geoand** [comment]
RESTEasy `4.6.1` contains the fix necessary for this test to pass, so I am making the PR ready for review.

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
