### PR TITLE
Remove now obsolete ContainerImageResultBuildItem

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
This class is part of the SPI so theoretically this is breaking change for extension authors, but given the fact that the only extensions using this are inside the repo, it's best to refactor now and get rid of it soon.

**Comment by Ladicek** [comment]
Exactly what I wanted to point out.

If the Kubernetes extension SPI is not in a state where stability could be guaranteed, it would probably be best to not have a dedicated `spi` artifact.

**Comment by geoand** [comment]
Actually this was part of the Container Image SPI, which is indeed is unstable. The Kubernetes SPI module is pretty stable - I don't recall us having to make breaking changes to it.

**Comment by Ladicek** [comment]
Oh and one thing: you _don't_ really know that "the only extensions using this are inside the repo". I have already been affected by a breaking change in the Kubernetes SPI once (or was it Container Image SPI?), because I use it in the OpenShift test suite.

**Comment by Ladicek** [comment]
Ah, correct, sorry, indeed I meant Container Image SPI.

**Comment by geoand** [comment]
Fair point.

However I think it's best to break SPI in these extension now, that it's pretty certain that other folks (not directly affiliated with Quarkus) are not using them in their extensions.
Otherwise we will end up with a lot of junk down the road when people start doing more complex stuff in their own extensions.

**Comment by Ladicek** [comment]
I don't disagree. I'm saying we shouldn't mark unstable SPI as stable SPI; in other words, if we're not sure the `BuildItem`s are stable, perhaps they should stay in the `deployment` artifact. I guess it's too late here, but let's keep that in mind for the future.

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
Windows failure is not related to the PR.

**Pull request merged**
