### PR TITLE
Fix null query parameter handling in generated RestEasy Reactive clients

### PR DESCRIPTION
**Pull request by kdubb**
Also adds missing query handling tests.

~The tests for using a `Map<>` as a query param via the `RestQuery` annotation are commented out. This is because I cannot figure out how to get these to work. If I uncomment them then the Quarkus refuses to build the client with an error of `Failed to find converter for java.util.Map`; I am not sure if this is itself a bug or user error.~

### CODE REVIEW

**Comment by kdubb** [comment]
@geoand This is a fix for #23876 that I commented on today. Note that my comments were wrong lol.

**Comment by geoand** [comment]
`Map` is currently not supported for `@RestQuery` (or any of the other types actually). I do think it would be useful to have (and not that difficult to add), but let's please remove the commented part of the code for now.

**Comment by kdubb** [comment]
Ok. I'm confused by #24783 and its associated issue #24764 that seem to say & implement exactly that.

**Comment by geoand** [comment]
That is for the client, not the server

**Comment by kdubb** [comment]
Yes. This PR is for the client and the PR/Issue I referenced are about using a Map in the client.

I must be completely missing something here lol.

**Comment by geoand** [comment]
> I must be completely missing something here lol.

The failure you are getting is from the Server where you are trying to use `Map` to read all query params - that's what's not supported.

**Comment by kdubb** [comment]
I knew I was missing something obvious...

I reinstated the tests for map but I'm using `UriInfo` on the server to extract all the query parameters. This way we're still testing the client's map (or null map) support.

**Comment by geoand** [comment]
Great, thanks!

**Review by geoand — APPROVED** [review]

**Pull request merged**
