### PR TITLE
Make it possible to test Google OIDC from DevUI

### PR DESCRIPTION
**Pull request by sberyozkin**
This PR does a few minor updates which will allow testing Google OIDC provider directly from the OIDC DevUI:
* Google authorization code (probably always) includes a `/` character which is returned to DevUi as `%2F`, and currently it is not decoded and the authorization code flow fails so the `code` in now decoded in `provider.html`
* Google access token (as opposed to ID token) is binary, and OIDC DevUI passes the ID token to SwaggerUI if it thinks that the binary token can not be introspected - but now Quarkus OIDC can also verify the binary tokens indirectly via the `UserInfo` acquisition, so `OidcDevConsoleProcessor` now also checks if the discovered metadata contains a user info endpoint to give a hint to DevUI that the binary token can be verified, and thus DevUI should pass the access token to Swagger UI (instead of ID token)
* DevUI only passes `openid` scope when requesting an authorization code, which with Google, is not enough to get the user name, so `OidcConfigPropertySupplier` which is used by DevUI to fetch runtime-init configuration values has been updated to return an encoded list of scopes if they are configured

Additionally, I updated `provider.html` to recognize `hybrid` OIDC applications, which is convenient for testing for example Google directly against Quarkus web-app but also from DevUI where Quarkus can accept bearer tokens.

With these updates and some related configuration (both in Quarkus and Google Cloud Console) one will be able to login to Google, use both ID and access tokens it returns from DevUI. It is already possible to do it with Auth0/Okta as well

### CODE REVIEW

**Comment by sberyozkin** [comment]
@phillip-kruger, are you OK with these changes ? Michal is looking at the migration, these changes should not affect it

**Comment by sberyozkin** [comment]
Also CC @stuartwdouglas

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by sberyozkin** [comment]
Thanks @phillip-kruger, it would be necessary for the demo we are planning, cheers

**Pull request merged**
