### PR TITLE
Load the Servlet API parent first

### LINKED ISSUE #7407: quarkus-logging-sentry and quarkus-undertow -  java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
When using quarkus-logging-sentry and quarkus-undertow an app user gets `java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer`

```
[INFO] Running io.quarkus.qe.MyResourceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.998 s <<< FAILURE! - in io.quarkus.qe.MyResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.013 s  <<< ERROR!
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
Caused by: java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
```

Reproducer:
```
rm -rf fooBar
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=io.quarkus.qe \
    -DprojectArtifactId=fooBar \
    -DprojectVersion=1.0.0-SNAPSHOT \
    -DplatformArtifactId=quarkus-bom \
    -DclassName="io.quarkus.qe.MyResource" \
    -Dextensions="quarkus-logging-sentry,quarkus-undertow"
mvn -f fooBar/pom.xml clean verify
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #7407

### CODE REVIEW

**Comment by ia3andy** [comment]
@stuartwdouglas It solves the issue #7407 , but now I have another issue on code.quarkus.io:
```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'org.apache.maven.model.Model io.quarkus.bootstrap.resolver.maven.workspace.ModelUtils.readModel(java.nio.file.Path)' the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1de5cc88 of the current class, io/quarkus/platform/descriptor/resolver/json/QuarkusJsonPlatformDescriptorResolver$2, and the class loader 'app' for the method's defining class, io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils, have different Class objects for the type org/apache/maven/model/Model used in the signature (io.quarkus.platform.descriptor.resolver.json.QuarkusJsonPlatformDescriptorResolver$2 is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1de5cc88, parent loader 'bootstrap'; io.quarkus.bootstrap.resolver.maven.workspace.ModelUtils is in unnamed module of loader 'app')
```


cc @aloubyansky

**Comment by stuartwdouglas** [comment]
Should work now

**Comment by ia3andy** [comment]
@stuartwdouglas great, it works now!

I am testing in native now to be sure :-)

**Review by ia3andy — APPROVED** [review]
Good good!

@gsmet at the same time it confirms that code.quarkus.io is working with master :-)

**Pull request merged**
