### PR TITLE
K8S service binding support for Reactive SQL Clients

### PR DESCRIPTION
**Pull request by tsegismont**
This commit introduces support for K8S service binding when using Reactive SQL Clients.

### CODE REVIEW

**Comment by tsegismont** [comment]
@geoand in addition to the feature implementation, we could reduce code duplication with a small refactoring. Instead of [`JdbcDatasourceUtil`](https://github.com/quarkusio/quarkus/blob/766974486f540098ffe7cef17dd1f2b76afeb05b/extensions/kubernetes-service-binding/runtime/src/main/java/io/quarkus/kubernetes/service/binding/runtime/JdbcDatasourceUtil.java) static methods, we could extend [`ReactiveDatasourceServiceBindingConfigSourceFactory`](https://github.com/quarkusio/quarkus/blob/0d08b98024f5b3c848c15edfce4233b4201003d4/extensions/kubernetes-service-binding/runtime/src/main/java/io/quarkus/kubernetes/service/binding/runtime/ReactiveDatasourceServiceBindingConfigSourceFactory.java) (sorry for the name!) and override only specific methods like `urlPropertyName` and `formatUrl`.

Then the same code base would handle both jdbc and reactive config sources when using k8s service bindings.

Wdyt?

**Comment by geoand** [comment]
Sounds like a good idea to me 🙂

**Comment by geoand** [comment]
Also, please rebase the PR onto a `main` in order to pick up a CI fix

**Comment by tsegismont** [comment]
@geoand done

**Comment by geoand** [comment]
Great! I'll have a look tomorrow morning

**Review by cescoffier — APPROVED** [review]
LGTM, but my knowledge about SBO is quite superficial.

**Review by geoand — COMMENTED** [review]
Thanks for this, LGTM!

I only have one comment: Can you squash the first and second commits please?
We try to avoid having commits that would break the build.
That way this PR would only have two commits: The first one that adds the Service Binding support for the reactive clients and the other one performing the refactoring.

**Review by geoand — APPROVED** [review]

**Comment by tsegismont** [comment]
I've added the `release/noteworthy` label

**Pull request merged**
