### PR TITLE
SmallRye Metrics 3.0.5

### PR DESCRIPTION
**Pull request by jmartisk**
Contains a fix required by Keycloak (https://github.com/keycloak/keycloak/issues/12177)

### CODE REVIEW

**Comment by gsmet** [comment]
@rsvoboda we need to add this one for 2.7 as Keycloak is going to use 2.7 AFAIK.

**Comment by rsvoboda** [comment]
@jmartisk / @jmartisk which product needs that? RH-SSO is based on WildFly / EAP.

**Comment by jmartisk** [comment]
@rsvoboda Actually, it's not a RH product asking for this, it's https://vector.dev/ that has a problem scraping metrics from Keycloak. And they seem to have a workaround, so nothing critical.

**Comment by gsmet** [comment]
@rsvoboda I wasn't talking product (at least not for the immediate future) but I was told Keycloak would use 2.7 for a while (not sure if it's still the case).

**Comment by gsmet** [comment]
Doesn't look very critical but AFAICS https://github.com/smallrye/smallrye-metrics/commit/be478e8e35142ad958811721ed45081fdf08d99e is the only change except for small Dependabot bumps so if it can help, it looks reasonable.

**Review by gsmet — APPROVED** [review]

**Comment by rsvoboda** [comment]
I see it's included in https://github.com/quarkusio/quarkus/pull/25839 now. The size / complexity of the fix if fine with me, I was just concerned about the productization price as it is a component upgrade.

**Pull request merged**
