### PR TITLE
Fix jackson integration test

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
Weird that CI hasn't even picked this up...

**Comment by gsmet** [comment]
CI wasn't triggered for now so let's wait if Azure gets triggered or I'll force push this week-end.

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by gwenneg** [comment]
Sorry, I didn't pay enough attention to the number of passed checks. This shouldn't have been merged. I'll keep an eye on CI to make sure everything's OK.

**Comment by gwenneg** [comment]
CI is broken on master, I submitted #6000 to fix it. I'll never ever merge something that late and without checking twice the CI checks list! Again, sorry about all this :(

**Comment by geoand** [comment]
No worries!

It was a bit of a special case with CI completely failing to start...

Thanks for fixing in the follow up PR

**Pull request merged**
