### PR TITLE
Optimize Accepts header validation in the common case

### PR DESCRIPTION
**Pull request by geoand**
The common case of having multiple Accepts headers validate
against a single @Produces media type shows up often
(as both browsers and benchmarks send 5 values in the Accepts
header)

### CODE REVIEW

**Comment by geoand** [comment]
In my simple hello world style tests with `application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7` as the value of the `Accepts` header, this have an improvement of from 1 to 2 percent

**Comment by gsmet** [comment]
Nice:
```
Exception during JVMCI compiler initialization
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (./src/hotspot/share/jvmci/jvmciRuntime.cpp:1120), pid=4756, tid=68
#  fatal error: Fatal exception in JVMCI: Exception during JVMCI compiler initialization
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 21.0.0 (11.0.10+8) (build 11.0.10+8-jvmci-21.0-b06)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (11.0.10+8-jvmci-21.0-b06, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, parallel gc, windows-amd64)
# Core dump will be written. Default location: D:\a\quarkus\quarkus\integration-tests\hibernate-validator\target\quarkus-integration-test-hibernate-validator-999-SNAPSHOT-native-image-source-jar\hs_err_pid4756.mdmp
```
hopefully, it won't happen very often :)

**Comment by gsmet** [comment]
BTW, I'm unhappy with the error management of this thing. It should report the build error of the native image process not the fact that the file does not exist. I wonder if it's a regression because I have a vague recollection it used to report the build error.

@zakkak @jonathan-meier could this behavior be related to your recent changes?

**Comment by jonathan-meier** [comment]
@gsmet I looked into it and it is unlikely to be a regression from our recent changes, but rather a pre-existing issue, though only on Windows (I guess that's why no one noticed until now). On Linux we should correctly report the build error.

The exception is thrown on line 185 (and then caught on line 209:
https://github.com/quarkusio/quarkus/blob/2405149e6b41026ee901fc6dbc9223383168348a/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L179-L215
This means we successfully passed the exit code check on line 180.

It turns out that since `native-image.cmd` does not explicitly exit with a proper exit code, we'll always receive `0` as an exit code from invoking `native-image.cmd` no matter what the actual invocation of `native-image.exe` inside `native-image.cmd` returned.

For reference, this is the content of `native-image.cmd`:
```
@echo off

call :getScriptLocation location
"%location%..\lib\svm\bin\native-image.exe" %*
:goto eof

:: If this script is in `%PATH%` and called quoted without a full path (e.g., `"js"`), `%~dp0` is expanded to `cwd`
:: rather than the path to the script.
:: This does not happen if `%~dp0` is accessed in a subroutine.
:getScriptLocation variableName
    set "%~1=%~dp0"
    exit /b 0
```
replacing `:goto eof` with `exit %errorlevel%` would solve the issue. Other than that, I don't know what other options we'd to catch the exit code of `native-image.exe` except invoking directly instead of going through the wrapper script.

**Comment by zakkak** [comment]
> replacing `:goto eof` with `exit %errorlevel%` would solve the issue.

FYI: This is fixed by https://github.com/oracle/graal/commit/5cbc36f336e53a1b959b9e0e040e16eccca42af3 in GraalVM master.

**Comment by gsmet** [comment]
Perfect, thanks guys!

**Review by gsmet — APPROVED** [review]
Makes perfect sense. We have tests covering that?

**Comment by geoand** [comment]
Yes, the TCK covers this stuff

**Pull request merged**
