### PR TITLE
Upgrade Maven Wrapper to 3.1.0

### PR DESCRIPTION
**Pull request by jorsol**
This upgrade the `maven-wrapper` to the latest official version that was previously maintained by the community at https://github.com/takari/maven-wrapper and was kindly donated to the Maven team: https://maven.apache.org/wrapper/

Most of the changes are just formating, but to preserve the scripts intact I leave them as the original ones.

### CODE REVIEW

**Comment by famod** [comment]
Thanks! I suggested using this now official wrapper two days ago when the quickstarts were updated to Maven 3.8.4.
@gsmet's take on this was that it needs discussion first: https://github.com/quarkusio/quarkus-quickstarts/pull/1017#issuecomment-995253514

/cc @aloubyansky

**Comment by gsmet** [comment]
We can discuss it here. I didn't want to have a discussion in the quickstarts repo as it has less visibility.

I have nothing against it as long as we consistently upgrade all artifacts. Also it would be nice to document the command line used as we will have to do it for a lot of projects.

**Comment by aloubyansky** [comment]
Good move. Thanks @jorsol

**Comment by gastaldi** [comment]
Isn't Maven 4 required to run the new Maven Wrapper plugin?

**Comment by jorsol** [comment]
> Isn't Maven 4 required to run the new Maven Wrapper plugin?

I think that was the plan, but it looks like with this first release they changed their minds.

**Comment by gsmet** [comment]
Could someone try to generate a project with this in and try to use the Maven wrapper? I'm not sure our test suite covers it.

**Comment by gastaldi** [comment]
I just tested and I can confirm it works as advertised

**Comment by gsmet** [comment]
Thanks @gastaldi . The CI failures were due to a Quay outage, I restarted a build.

**Review by gsmet — APPROVED** [review]
@gastaldi tested it and it works as advertised. Let's merge when CI is green.

**Comment by gsmet** [comment]
@jorsol could you also prepare a PR for https://github.com/quarkusio/quarkus-platform ? Thanks!

**Pull request merged**
