### PR TITLE
Fix erroneous JSON related warning message when returning Qute types

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by mkouba** [comment]
This will fix the case when a resource method returns `TemplateInstance` but not `Uni<RestResponse<Object>>`.

**Comment by geoand** [comment]
I tried it and this also fixes the case of `Uni<RestResponse<Object>>`.

**Comment by mkouba** [comment]
I can still see the warning for `Uni<RestResponse<String>>` but the case of `Uni<RestResponse<Object>>` is fixed indeed ;-).

**Comment by geoand** [comment]
Hm... I don't see the warning in the case of `Uni<RestResponse<String>>` either.

**Comment by mkouba** [comment]
> Hm... I don't see the warning in the case of `Uni<RestResponse<String>>` either.

It does log the warning if the resource method also declares `@Produces(MediaType.APPLICATION_JSON)` but builds the json manually, e.g. via `io.vertx.core.json.JsonObject`. And that's probably not a common use case so not a big deal.

**Comment by geoand** [comment]
Yeah, I think we can ignore that case for now :)

**Review by mkouba — APPROVED** [review]

**Pull request merged**
