### PR TITLE
Replace jackson-databind dependencies with quarkus-jackson

### LINKED ISSUE #3638: Add quarkus-jackson dependency to all the extensions using Jackson
We have several extensions using Jackson (Amazon Lambda, Vert.x) that do not depend on `quarkus-jackson`. We should fix that.

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #3638

### CODE REVIEW

**Comment by gwenneg** [comment]
I expected the Windows build to fail (classic websocket test failure) but not the Linux one (it was successful locally). I'll investigate this ASAP.

**Comment by machi1990** [comment]
> I expected the Windows build to fail (classic websocket test failure) but not the Linux one (it was successful locally). I'll investigate this ASAP.

It is a known issue - https://github.com/quarkusio/quarkus/issues/3558, related to the new http layer.

**Comment by gwenneg** [comment]
> > I expected the Windows build to fail (classic websocket test failure) but not the Linux one (it was successful locally). I'll investigate this ASAP.
> 
> It is a known issue - #3558, related to the new http layer.

Yes, I know this one as I’ve seen it a lot lately. It’s the other one that surprised me :)

**Comment by gwenneg** [comment]
So it turns out that CI could not contact JCenter to retrieve `maven-model-3.0.4.pom` during the `quarkus-gradle-plugin` build. It doesn't seem related to this PR changes.

**Comment by cescoffier** [comment]
@evanchooly  @patriot1burke can you look at the Lambda part?

**Comment by evanchooly** [comment]
It looks ok to me.  Simple enough.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
