### PR TITLE
Use `MapBackedConfigSource`-based implementation for platform properties

### PR DESCRIPTION
**Pull request by knutwannheden**
Changes `ExtensionLoader#loadStepsFrom()` to use a `MapBackedConfigSource`-based implementation for the platform properties rather than a `KeyMapBackedConfigSource`-based implementation. This is simpler and has the advantage that the config source's properties can be enumerated using `ConfigSource#getProperties()` and `ConfigSource#getPropertyNames()`.

Related to #18063

### CODE REVIEW

**Comment by radcortez** [comment]
@aloubyansky do you remember if there was any specific reason why you used the `KeyMapBackedConfigSource` here?

**Comment by aloubyansky** [comment]
Yes, https://github.com/quarkusio/quarkus/pull/12785#discussion_r516232819

**Comment by knutwannheden** [comment]
I see. I never got around looking into the test failures. I was a bit surprised that a seemingly innocuous change like this would cause failures. In that case we should probably just close this PR.

**Comment by aloubyansky** [comment]
@knutwannheden this change doesn't look related to the test failure though. You could rebase the branch to re-run.

**Comment by radcortez** [comment]
Anyway, because of the comment in https://github.com/quarkusio/quarkus/pull/12785#discussion_r516232819 I believe we shouldn't replace the `ConfigSource` type.

**Pull request closed without merging**
