### PR TITLE
Add a check to ensure values are not produced or consumed outside of their step

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
This exposes the problem described in #2954.

**Comment by gsmet** [comment]
There are test failures in the Arc deployment module:
```
https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=3574&view=logs&jobId=40f2f079-c615-51da-ef6d-c921ab62f03a&taskId=3a479b05-c898-55dd-4261-55631ea103ce&lineStart=4288&lineEnd=4303&colStart=1&colEnd=8
```

**Comment by dmlloyd** [comment]
Yeah it's expected.  See #2954 for discussion.

**Comment by dmlloyd** [comment]
I'm not sure why it says the branch is out of date with the base branch.  It is one commit ahead of `master`.

**Comment by gsmet** [comment]
@dmlloyd what's the status of this one? Do you wait for @mkouba to check the ArC-related failures?

**Comment by dmlloyd** [comment]
Martin and I have a call scheduled for tomorrow to brainstorm some ideas.

**Comment by mkouba** [comment]
This PR is superseded by https://github.com/quarkusio/quarkus/pull/3175.

**Pull request closed without merging**
