### PR TITLE
Apply various fixes to Kotlin Serialization modules

### LINKED ISSUE #22712: Adding both `quarkus-resteasy-reactive-kotlin-serialization` and `quarkus-rest-client-reactive-kotlin-serialization` throws `arc.deployment.SyntheticBeansProcessor#initStatic threw an exception: A synthetic bean ... is already registered`
### Describe the bug

Built Quarkus from source, set `gradle.properties` tag to `999-SNAPSHOT`
Error message is:
`	[error]: Build step io.quarkus.arc.deployment.SyntheticBeansProcessor#initStatic threw an exception: java.lang.IllegalStateException: A synthetic bean with identifier 9e2487eb0d6c3e033af916549aa4ab5873e78bf9 is already registered: SYNTHETIC bean [types=[kotlinx.serialization.json.Json], qualifiers=[@Default, @Any], target=n/a]
`
```java
Jan 06, 2022 11:33:59 PM io.quarkus.arc.processor.Injection getAllInjectionPoints
WARN: An injection field must be non-static and non-final - ignoring: io.quarkus.rest.client.reactive.kotlin.runtime.serializers.ClientKotlinMessageBodyWriter#json

Jan 06, 2022 11:33:59 PM io.quarkus.arc.processor.Injection getAllInjectionPoints
WARN: An injection field must be non-static and non-final - ignoring: io.quarkus.rest.client.reactive.kotlin.runtime.serializers.ClientKotlinMessageBodyReader#json

java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.SyntheticBeansProcessor#initStatic threw an exception: java.lang.IllegalStateException: A synthetic bean with identifier 9e2487eb0d6c3e033af916549aa4ab5873e78bf9 is already registered: SYNTHETIC bean [types=[kotlinx.serialization.json.Json], qualifiers=[@Default, @Any], target=n/a]
	at io.quarkus.arc.processor.BeanDeployment.addSyntheticBean(BeanDeployment.java:1174)
	at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.lambda$configure$0(BeanDeployment.java:1363)
	at io.quarkus.arc.processor.BeanConfigurator.done(BeanConfigurator.java:51)
	at io.quarkus.arc.deployment.SyntheticBeansProcessor.configureSyntheticBean(SyntheticBeansProcessor.java:88)
	at io.quarkus.arc.deployment.SyntheticBeansProcessor.initStatic(SyntheticBeansProcessor.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

It werks

### Actual behavior

It don't werk

### How to Reproduce?

With the following `build.gradle.kts`, the project won't run:

```kt
plugins {
    kotlin("jvm") version "1.6.10"
    kotlin("plugin.allopen") version "1.6.10"
    id("io.quarkus")
}

repositories {
    mavenCentral()
    mavenLocal()
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-vertx")
    implementation("io.quarkus:quarkus-resteasy-reactive")
    implementation("io.quarkus:quarkus-rest-client-reactive")

    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-resteasy-reactive-kotlin-serialization")
    implementation("io.quarkus:quarkus-rest-client-reactive-kotlin-serialization")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.rest-assured:rest-assured")
    testImplementation("io.rest-assured:kotlin-extensions")
}

group = "com.github.gavinray97"
version = "1.0.0-SNAPSHOT"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11.toString()
    kotlinOptions.javaParameters = true
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.376]

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 22.0.0-dev (build 17.0.2+5-jvmci-22.0-b02)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

Master

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #22712

### CODE REVIEW

**Comment by mkouba** [comment]
The fix for #22712 looks good.

**Comment by geoand** [comment]
@mkouba mind reviewing please? The other fixes are totally trivial, but very necessary to make the extensions work properly

**Review by mkouba — APPROVED** [review]
Looks good.

**Comment by mkouba** [comment]
Shall we squash the commits?

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I think it makes sense to keep them given they are all semantic and tell a story.

**Comment by geoand** [comment]
> I think it makes sense to keep them given they are all semantic and tell a story.

My thoughts exactly :)

**Comment by mkouba** [comment]
> I think it makes sense to keep them given they are all semantic and tell a story.

Hm, that's a nice idea - you can write a short story in a series of commit comments :D

**Comment by gsmet** [comment]
Kotlin serialization is in main only so not backporting.

**Pull request merged**
