### PR TITLE
Fix for resolving entity fields based on collections and generics

### LINKED ISSUE #34395: Spring Data API Extension Property Expressions with List not working
### Describe the bug

The method  `long countParentsByChildren_Name(String name)` throws `java.lang.IllegalStateException: Entity class java.util.List referenced by at.atc.database.entities.Parent.children was not part of the Quarkus index. Offending method is 'countParentsByChildren_Name' of repository 'at.atc.database.repository.ParentBaseRepository'.`

Same method works fine with Spring.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

[reproducerJPAQueryMethod.zip](https://github.com/quarkusio/quarkus/files/11898682/reproducerJPAQueryMethod.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aureamunoz**
Fixes #34395

The problem  was that the resolveNestedFields method  didn't resolver correctly collection fields. For example if Person had a `List<Address> addresses`, or `List<T>` in case where wildcard is used. When dealing with a single field, Address address, there is no problem. 
What happens with the list is that it takes the wrong type, List instead of T/Address, and checks and checks that the field preceded by '_' (e.g. _isoCode) is a Person field. Also it tries to get `List`from the index and it is not indexed at this point.  

cc @geoand , @Michael-AT-Corporation

### CODE REVIEW

**Comment by geoand** [comment]
Can you please fix the formatting issue?

Thanks

**Comment by aureamunoz** [comment]
> Can you please fix the formatting issue?
> 
> Thanks

Yes, I saw it just this morning. Done!

**Comment by geoand** [comment]
It's still not happy :)

**Comment by aureamunoz** [comment]
I fixed! I had broken it with the new code :grimacing: Thank goodness for the tests! Let's see what the CI says

**Review by geoand — APPROVED** [review]
Thanks!

**Pull request merged**
