### PR TITLE
Update all known UIs to look more like the Dev Console

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR contains changes to make the current known UIs look more like the new Dev Console.
Changes include:

- Allow quarkus branding to override per module (as user override can do currently)
- Allow replacement for applicationName, applicationVersion and quarkusVersion in css
- Added css for swagger-ui, graphql-ui and health-ui to look more like Dev Console.
- Replaced logo+name with just logo.

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by phillip-kruger** [comment]
devconsole
swaggerui
graphqlui
healthui

**Comment by gsmet** [comment]
There is a bit more space between the border and the text for "Health UI". Very minor. Did I say I was picky? :)

Then I think I would get Quarkus application name + version at the far right for all of them and:
- move the URL bar just after the title for Swagger UI
- Move the docs button after the menu for GraphQL
- move the status for Health either just after Health UI (before the cog)

Does it make sense? That's very cool to have everything aligned :).

**Comment by phillip-kruger** [comment]
Hi @gsmet - I like picky :) 

Ok:

> move the URL bar just after the title for Swagger UI
Should be possible. Let me try
 
> Move the docs button after the menu for GraphQL
This might be weird from a Feel (from L&F) as this is a pull out panel from the right (see image below). But let me do it, then we decide.

> move the status for Health either just after Health UI (before the cog)
Should be possible. Let me try

image

**Comment by gsmet** [comment]
> This might be weird from a Feel (from L&F) as this is a pull out panel from the right (see image below). But let me do it, then we decide.

Ah OK, having the Docs there makes perfect sense then. Keep it this way.

**Comment by phillip-kruger** [comment]
devconsole
swaggerui
swaggerui2

**Comment by phillip-kruger** [comment]
healthui
graphqlui

**Comment by phillip-kruger** [comment]
@gsmet - I could not get the status button before the cog, (I can do that in the HTML, but that would be a new SmallRye Health version).  But the swagger-ui is done.

**Review by gsmet — APPROVED** [review]
Woot! Looks very good, thanks!

**Comment by FroMage** [comment]
Looks GREAT, big +1

**Pull request merged**
