### PR TITLE
REST Data Panache dev mode

### LINKED ISSUE #9510: Error with HTTP POST using "REST Data with Panache" extension
**Describe the bug**
HTTP POST with results in an error, but GET, PUT, and DELETE work.

**Expected behavior**
HTTP POST should add entity to H2 database.

**Actual behavior**
Error on HTTP POST:
```
RESTEASY012020: Discovery failed for method org.acme.rest.PersonControllerImpl_772bba7f3925f61a49c0d93159012a40b2de28d6.delete: RESTEASY012005: Cannot guess resource type for service discovery
```

**To Reproduce**
Reproducer [here](https://github.com/jclingan/quarkus-panache-rest).
* mvn quarkus:dev
* Run example commands in reproducer README.md

**Environment (please complete the following information):**
java -version output:
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
```
**Additional context**
I'm a really nice guy.

### PR DESCRIPTION
**Pull request by gytis**
Fixes https://github.com/quarkusio/quarkus/issues/9510.

### CODE REVIEW

**Comment by gsmet** [comment]
@gytis I upgraded RESTEasy to 4.5.6.Final, is it enough for this to work?

**Comment by geoand** [comment]
@asoldano when is RESTEasy 4.6.0.Final due? If it's not out before we release Quarkus `1.7.0.CR1`, I think it would be good to have a `4.5.7.Final` with https://github.com/resteasy/Resteasy/commit/2bb4bc0522b1ee01772667d72be1787bc94d60cb included (although I don't know how safe it is)

**Comment by gytis** [comment]
@geoand this should be good to go now since the RESTEasy upgrade has been merged.

**Comment by geoand** [comment]
One question: You mention `potential` fix in the description, but if I recall correctly, this is the actual fix, right?

Asking because I want to know if we should properly link the issue so GH can close it when we merge the PR

**Comment by geoand** [comment]
Also, have you rebased the PR to the latest master? Best we have it up to date

**Comment by gytis** [comment]
My bad, I left the description unchanged. I've created this PR months ago to have it ready once the RESTEasy is upgraded.

**Comment by gytis** [comment]
I've updated maybe an couple of hours ago. Should I do it again?

**Comment by geoand** [comment]
No, just wanted to make sure it wasn't weeks old 😎

**Review by geoand — APPROVED** [review]

**Pull request merged**
