### PR TITLE
Fix incorrect JUnit dependency

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Good catch!

**Comment by famod** [comment]
This could be prevented via `bannedDependencies` enforcer rule. I think a separate execution is required because some modules bring in Junit4 transitively (`quarkus-test-arquillian` & `quarkus-test-kubernetes-client`).

**Comment by gsmet** [comment]
I think we should move those two to use Junit 5 too.

**Comment by geoand** [comment]
Yeah, I don't see why they are on JUnit 4

**Comment by famod** [comment]
Well, AFAIK Arquillian Junit5 support is still in alpha stage.
The Kubernetes test client is using `mockwebserver` and from what I can tell, that project is still in the process of migrating to Junit5.

**Comment by stuartwdouglas** [comment]
Arquillian needs JUnit 4 support because that is what the TCK's are written with, even if there was a JUnit 5 Arquillian we can't move until the TCK move.

**Pull request merged**
