### PR TITLE
Apply micro-optimizations to RESTEasy Reactive startup

### PR DESCRIPTION
**Pull request by geoand**
The main idea is to get rid of the fairly expensive `Map#entrySet` calls and replace them with `forEach` which is optimized in `HashMap` and `TreeMap`.

### CODE REVIEW

**Comment by geoand** [comment]
This shouldn't have much of an impact most of the time, but it could with larger deployments

**Comment by geoand** [comment]
This also does not conflict with https://github.com/quarkusio/quarkus/pull/21138

**Comment by stuartwdouglas** [comment]
Just how much difference does this actually make? And does the forEach end up allocating a bit more metaspace anyway which we then pay for for the life of the application?

**Comment by geoand** [comment]
I used your large project generated and saw that it saved around 30ms of startup time. Not much obviously, but not terrible either :).

As for the metaspace, shouldn't that not be an issue with method references?

**Comment by geoand** [comment]
So should I close this?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
30ms with 100 classes is not nothing, might as well include it

**Comment by geoand** [comment]
Okay, cool

**Pull request merged**
