### PR TITLE
Updates of rest-assured, assertj

### PR DESCRIPTION
**Pull request by rsvoboda**
Updates of rest-assured, assertj and jetty

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Why do we even have Jetty? I think it may be a leftover from when Camel was part of the main code base.

**Comment by rsvoboda** [comment]
I think I saw that in TCK modules, let me check

**Comment by rsvoboda** [comment]
got confused, tck module is not using it, it is excluding it
https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-rest-client/pom.xml#L98-L110

I will update the pr to skip jetty for now, will prepare dedicated pr for jetty removal

**Comment by stuartwdouglas** [comment]
Thanks

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
