### PR TITLE
Use proper type for Kubernetes probes

### PR DESCRIPTION
**Pull request by geoand**
Relates to: #11431

https://github.com/quarkusio/quarkus/pull/10824 incorrectly changed the type to String

### CODE REVIEW

**Comment by geoand** [comment]
This PR doesn't completely fix #11431 - for that to happen we need https://github.com/dekorateio/dekorate/pull/607 to be merged, a new Dekorate release cut and have Quarkus pick up that release

**Comment by gsmet** [comment]
Is this something that should be backported?

**Comment by geoand** [comment]
Ah sorry :). I just added the label

**Comment by gsmet** [comment]
All the JDK runs failed :/. I rebased on top of master where I reenabled JDK 14 so that we have one more chance...

**Comment by geoand** [comment]
Thanks!

**Review by iocanel — DISMISSED** [review]
I think that this will cause NPE when using knative + probes.
Why?

Because in that cause we *need to* remove the port number from the probe definition and this is only possible when setting it to null. However, the `IntOrString` type is internally using `int` resulting in NPE.

This is something that needs to be adressed on `kubernetes-client` level, then dekorate and finally on quarkus side.

So, till then I suggest we explore other ways of dealing with this.

**Comment by iocanel** [comment]
Maybe we should revert back to Int and also use `Include.NON_DEFAULT` in order to skip this property. However, this is a cross cutting change and we need to be cautious.

**Comment by iocanel** [comment]
An other solution could be to manage the creation of the `IntOrString` ourselves and pass it via the `withPort` method. Let me have a look.

**Comment by geoand** [comment]
I just added a test and it does fail with a NPE like you predicted. Let me look into solutions

**Comment by geoand** [comment]
I have a workaround (I think). Will run the tests and commit the change

**Comment by geoand** [comment]
Fixed

**Comment by geoand** [comment]
@iocanel can you please re-review?

**Review by iocanel — APPROVED** [review]
lgtm

**Pull request merged**
