### PR TITLE
Fallback to a docker build on linux

### PR DESCRIPTION
**Pull request by stuartwdouglas**
If native image is not installed attempt to use docker instead.

This just makes things a bit more user friendly. This is only for linux though as mac and windows users would not be able to run the resulting executable. 

We could also do this if the local image is out of date, but I thought I would see what people thought of this first.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
I like it!

**Comment by gsmet** [comment]
I have no opinion about this. I usually prefer consistent behavior rather than this sort of things but I'm usually in minority :).

**Comment by stuartwdouglas** [comment]
Personally since I moved to linux I always do -Dquarkus.native.container-build=true unless I actually needed to debug graal (which has not happened yet). An order of magnitude more developers have docker installed than Graal, so this just makes things work out of the box. You could argue that it is more deterministic, as you always get the version that we tested against.

**Comment by geoand** [comment]
I am +1 for this

**Comment by gsmet** [comment]
Force pushed a rebase.

**Pull request merged**
