### PR TITLE
Add support for CredentialsProvider in Mongo connections

### LINKED ISSUE #20277: Add support for CredentialsProvider in the MongoDB client
### Description

We use a custom credential provider to manage login credentials for all Argoal data sources, we need the same for MongoDB.  Currently MongoDB only supports plain text passwords in the application.properties/yml file which is not an acceptable solution.

Please add support for same credential provider in MongoDB.

Custom Credential Provider: https://quarkus.io/guides/credentials-provider#custom-credentials-provider

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #20277

I did not add a test because: 
* I did not see how we can do that (none of our other tests do it)
* Even if I did, I would not be able to verify on my machine as our existing tests fail for me with `[mongod error]/home/gandrian/.embedmongo/fileSets/de0c2b8f50ba7d3bc96e039e3d158b6c0e6f88d66dfc78533601ff522286a91b/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hey @geoand, one of the oidc tests should be using a custom credentials provider, quarkiverse file vault or even better file vault shoul have it too. So if in Quarkus repo we already have a mongo test where a user name and password is configured,  then you can reuse for ex the one  from the oidc test. It is just a simple bean, return from it the same username and password. I can show an example next week FYI, even if this PR is merged before that, thanks

**Comment by geoand** [comment]
Hi @sberyozkin 

My problem is how to start mongo to configure it to use specific credentials. Using vault isn't really an issue :)

**Comment by sberyozkin** [comment]
Hi @geoand sure, I'm not really familiar with MongoDB, @loicmathieu Loic, can you please look at this PR as well ?

**Comment by loicmathieu** [comment]
Hi,
This looks good but having no test is an issue, maybe you can add a test and use CI to validate it, I can help to make it work to avoid too many round trip with the CI.
@geoand you can also open an issue with the error you have with flapdoodle embedded MongoDB, we can ping the people that made the upgrade for help.

**Comment by loicmathieu** [comment]
@geoand Well, you do mention that you cannot start Mongo due to an error, that was I was referencing.

I can try the following PR with a Vault provider locally using MongoDB Atlas which is user/pass protected, I just need some time to do it so this will not be "now".

If tests are missing for user/password we definitely need to add some, I'll create an housekeeping issue for that.

**Comment by geoand** [comment]
> Well, you do mention that you cannot start Mongo due to an error, that was I was referencing.

Ah, sorry! I forgot about that... The error is: `[mongod error]/home/gandrian/.embedmongo/fileSets/de0c2b8f50ba7d3bc96e039e3d158b6c0e6f88d66dfc78533601ff522286a91b/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

**Comment by geoand** [comment]
> If tests are missing for user/password we definitely need to add some, I'll create an housekeeping issue for that.

+1

**Comment by geoand** [comment]
What do you think about this one folks?

I think it's important to get this one into one of the upcoming Alphas

**Review by loicmathieu — APPROVED** [review]
LGTM, you wan merge it I already created an housekeeping issue to create a test with username/password to cover part of the authenticated code.

Or you can wait for me to have the time to test it locally, as you want.

**Comment by geoand** [comment]
> Or you can wait for me to have the time to test it locally, as you want.

Sure yeah, that works for me :)

**Comment by loicmathieu** [comment]
@geoand I cannot run embedded Mongo anymore, when I'll find more time I'll add test for user/name auth and credential providers. Meanwhile I merge this one.

**Pull request merged**
