### PR TITLE
Update to OpenAPI 1.2.3 and fixes #8811

### LINKED ISSUE #8811: Uni and Multi should not be represented in OpenAPI schema
When using 

```
@GET
@Path("/{name}")
public Uni<Fruit> getOne(@PathParam(value = "name") String name) {
}
```

The schema is

```
UniFruit:
  type: object
```

Which is wrong. Uni and Multi should not be in the open api contract. 

See https://stackoverflow.com/questions/61394139/openapi-spec-for-reactive-rest-service-using-quarkus

@cescoffier @kenfinnigan

### PR DESCRIPTION
**Pull request by kenfinnigan**
- OpenAPI 1.2.3 adds support for Mutiny types
- Added Mutiny type tests into OpenAPI output verification

### CODE REVIEW

**Comment by gsmet** [comment]
@kenfinnigan cool! Please add the backport label instead of the version. I change the version when I do the backport. Otherwise it's hard to keep track of what has been backported or not.

Thanks!

**Comment by kenfinnigan** [comment]
Sorry

**Comment by kenfinnigan** [comment]
Hmm, not sure why scala tests timed out, can't see it being related to my change.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
It happens from time to time, no worries, I'll merge.

**Pull request merged**
