### PR TITLE
correct signature for singleResult

### LINKED ISSUE #11287: Misleading/Erroneous signatures in Panache Hibernate Kotlin
**Describe the bug**
Several signatures in the `PanacheCompanion` indicate that the result of function call may be `null`, e.g. `PanacheCompanion<Id, Entity>.findById(id: Id): Entity?` or `PanacheQuery<Entity>.singleResult(): Entity?`.

**Expected behavior**
Invoking a function with a nullable result type returns `null` instead of throwing an exception; like e.g. `PanacheQuery<Entity>.firstResult(): Entity?`.

**Actual behavior**
```
javax.persistence.NoResultException: No entity found for query
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1583)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.singleResult(CommonPanacheQueryImpl.java:299)
	at io.quarkus.hibernate.orm.panache.kotlin.runtime.PanacheQueryImpl.singleResult(PanacheQueryImpl.java:171)
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: any version with Panache Kotlin support
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

### PR DESCRIPTION
**Pull request by evanchooly**
add tests to confirm

fixes #11287

### CODE REVIEW

**Review by FroMage — APPROVED** [review]
LGTM but this doesn't seem to be about documentation but the return type.

**Review by loicmathieu — APPROVED** [review]
LGTM

**Comment by evanchooly** [comment]
ah, yes.  i suppose that's the better way to put that.  👍

**Comment by evanchooly** [comment]
It's probably an easy backport but if it doesn't make it in 1.8 is just around the corner

**Comment by gsmet** [comment]
@evanchooly Yeah it's just a cherry-pick, just wanted to be sure this fix was valid for 1.7. Can you confirm?

**Comment by evanchooly** [comment]
It is.

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
