### PR TITLE
H2 embedded: disable support for compiling javascript/groovy triggers

### PR DESCRIPTION
**Pull request by Sanne**
Not including aa test as I'm not sure how to trigger it - but this should fix a problem in the ecosystem CI:
 - https://github.com/quarkusio/quarkus/issues/9142

### CODE REVIEW

**Comment by Sanne** [comment]
cc/ @beikov

**Review by geoand — APPROVED** [review]

**Comment by Sanne** [comment]
Thanks @geoand !

I'll wait to merge for @beikov 's opinion as there might be more to it.

**Comment by geoand** [comment]
Sure thing, makes sense

**Comment by beikov** [comment]
Ok, my local tests showed that this fixes the problem

**Pull request merged**
