### PR TITLE
Stop disabling unsafe in netty at native-executable runtime

### PR DESCRIPTION
**Pull request by zakkak**
Resolves issues unveiled with https://github.com/quarkusio/quarkus/pull/37347

~Draft till tests in https://github.com/zakkak/quarkus/actions/runs/7032713931 complete~

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
I think I will merge this to get CI green and if @karesti and @wburns have concerns, we can discuss it further and find another solution.

**Comment by karesti** [comment]
if CI passes well, should be fine @gsmet

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
@gsmet I'm going to ping @wburns directly too

**Comment by gsmet** [comment]
I'm merging to get our CI green but we can reconsider if you have concerns. Ping me and @zakkak in this case. Thanks!

**Comment by wburns** [comment]
Yeah, I see nothing wrong as long as CI is passing with the native executable.

**Pull request merged**
