### PR TITLE
Updated the version of keycloak version in bom from 9.0.2 to 9.0.3

### PR DESCRIPTION
**Pull request by harshmadhani**
The version of keycloak dependency is upgraded from 9.0.2 to 9.0.3

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
the failure doesn't seem to be related to the change...

**Comment by gsmet** [comment]
I force pushed an update to remove the second commit. Let's see what CI has to say about it now.

**Comment by gsmet** [comment]
I tweaked the CI and also updated the images. Let's see how it goes.

**Comment by gsmet** [comment]
@sberyozkin can you have a look at this PR? The Vault issue for JDK 8 looks unrelated but I'm not entirely sure about the `security2` failure.

**Comment by gsmet** [comment]
@sberyozkin ping. We need to move fast on this and be done with it before the end of this week.

**Comment by geoand** [comment]
@sberyozkin ping :)

**Comment by sberyozkin** [comment]
Sorry everyone

**Review by sberyozkin — APPROVED** [review]
@harshmadhani Nice work sorry for a delay. 
Sorry all, I've missed it badly.
Guillaume may be commits can be squashed :-)

**Comment by sberyozkin** [comment]
Vault failure is definitely not related

**Pull request merged**
