### PR TITLE
Issue 5440 - Link to Infinispan Query DSL is broken on the documentation

### PR DESCRIPTION
**Pull request by tiagodolphine**
Fix for the issue https://github.com/quarkusio/quarkus/issues/5440.

Please check if I inserted the right link, at least this is the one I'm using now checked on the Infinispan website.

Thanks.

### CODE REVIEW

**Review by wburns — APPROVED** [review]
Looks good to me. Unfortunately, some other people keep moving docs around :)

**Comment by Sanne** [comment]
> Looks good to me. Unfortunately, some other people keep moving docs around :)

Please consider adding a requirement to have proper redirects in place. That will make sure people think twice about moving them next time ;)

**Comment by Sanne** [comment]
@tristantarrant ^

**Comment by Sanne** [comment]
Fixes ##5440

**Comment by tristantarrant** [comment]
or the link should have been updated according to the documentation changes

**Comment by Sanne** [comment]
Sure we fix it. But @tristantarrant you're damaging your SEO, for a long lived project you really should consider having redirects.

**Comment by tristantarrant** [comment]
If I search infinispan query dsl on google, the first link I get is fine (and is updated wrt the latest layout). Our docs are also hosted on GH pages which doesn't really have redirects... unless you count having a placeholder html with a meta http equiv with a refresh.

**Comment by Sanne** [comment]
that's not how you test for SEO scores, but feel free to ignore my suggestions.

**Pull request merged**
