### PR TITLE
Kubernetes resource name and version no longer depend on container image configuration

### LINKED ISSUE #33554: Kubernetes name influenced by the `quarkus.container-image.name`
### Describe the bug

I have an application. It sets the image name to quarkus.container-image.name=hide-and-seek-${quarkus.application.name}. I didn't expect this to change the name in my kubernetes descriptor:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-05-23 - 11:46:15 +0000
    app.quarkus.io/commit-id: 8ebd4faa57246c018ed32642bdc6be234b0e8bfc
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: hide-and-seek-place-service
    app.kubernetes.io/managed-by: quarkus
  name: hide-and-seek-place-service
---
```

According to @iocanel it's not intended and it's a bug

### Expected behavior

Setting `quarkus.container-image.name` should not change the kubernetes names.

### Actual behavior

Setting `quarkus.container-image.name` is used in my kubernetes descriptor (for the names)

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #33554

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
The changes in ApplyOpenshiftRouteConfigurator.java is a change of behavior that needs to be justified (from my point of view, if the route is exposed, why should we edit a provided one by the user?).

 
I think we should first fully understand why the failing test is not working well after the changes in the first commit.

**Comment by iocanel** [comment]
>  The changes in ApplyOpenshiftRouteConfigurator.java is a change of behavior that needs to be justified (from my point of view, if the route is exposed, why should we edit a provided one by the user?).

Generally speaking, the whole idea of using `user provided` resources is to further enhance / dekorate them using the info gathered during the build.
 
This is also the behavior that is tested by the `OpenshiftWithCustomRouteResource` test: User provides a `Route` without a port and the test expects to find one.

>  I think we should first fully understand why the failing test is not working well after the changes in the first commit.

 By removing the defaults we end up with 0 `openshift` properties and therefore we  trigger: [dekorateio/dekorate#1215](https://github.com/dekorateio/dekorate/issues/1215). The side effect is that dekorate generates a RouteConfig without a target port.
 
 Regardless, of what dekorate does internally, quarkus does have a `targetPort` with a default value `http` and this should be respected. Currently, it is not because we only apply that when `expose == true`. As explained above this is not the expected behavior something that is also reinforced by the logic of `OpenshiftWithCustomRouteResource`

**Comment by Sgitario** [comment]
> > The changes in ApplyOpenshiftRouteConfigurator.java is a change of behavior that needs to be justified (from my point of view, if the route is exposed, why should we edit a provided one by the user?).
> 
> Generally speaking, the whole idea of using `user provided` resources is to further enhance / dekorate them using the info gathered during the build.
> 
> This is also the behavior that is tested by the `OpenshiftWithCustomRouteResource` test: User provides a `Route` without a port and the test expects to find one.
> 
> > I think we should first fully understand why the failing test is not working well after the changes in the first commit.
> 
> By removing the defaults we end up with 0 `openshift` properties and therefore we trigger: [dekorateio/dekorate#1215](https://github.com/dekorateio/dekorate/issues/1215). The side effect is that dekorate generates a RouteConfig without a target port.
> 
> Regardless, of what dekorate does internally, quarkus does have a `targetPort` with a default value `http` and this should be respected. Currently, it is not because we only apply that when `expose == true`. As explained above this is not the expected behavior something that is also reinforced by the logic of `OpenshiftWithCustomRouteResource`

So, before your changes, the targetPort was set to `http` by Dekorate, not by Quarkus. 
Now, because of [this issue](https://github.com/dekorateio/dekorate/issues/1215) in Dekorate, Dekorate does not play anymore. Since Quarkus was doing nothing already, the target port remained untouched. 

With your changes about the `expose == true`, now Quarkus does set the target port (regardless if Dekorate does something or not).

Did I understand what is going well now?

**Review by Sgitario — APPROVED** [review]
lgtm!

**Comment by rsvoboda** [comment]
So what's the right way to customize the names in kubernetes yaml? Is it `quarkus.application.name`?

I mean these names:
```bash
yq '.spec.template.spec.containers[].name' target/kubernetes/kubernetes.yml
yq '.metadata.name' target/kubernetes/kubernetes.yml
```

**Comment by rsvoboda** [comment]
@iocanel @Sgitario @cescoffier ^^^

**Comment by iocanel** [comment]
@rsvoboda: `quarkus.kubernetes.name` is still the way to go. The PR does not change that.

**Pull request merged**
