### PR TITLE
refactor(LogConfig): Remove optional @DefaultConverter

### PR DESCRIPTION
**Pull request by aoudiamoncef**
Hi @dmlloyd, 
According to [writing extensions guide](https://quarkus.io/guides/writing-extensions) we should use `@DefaultConverter` if we have one, i thought that this is the case of `Level.class` && `InetSocketAddress`. 

Thanks

### CODE REVIEW

**Comment by dmlloyd** [comment]
No, that annotation is only necessary when we have a non-default converter for a given type, which we do not in these cases.  Right now the default converter is used in most cases already, so this change is not needed.

**Comment by aoudiamoncef** [comment]
According to the current code in `FileConfig` && `ConsoleConfig`: 
```java
    /**
     * The level of logs to be written into the file.
     */
    @DefaultConverter
    @ConfigItem(defaultValue = "ALL")
    Level level;
```
So it could be removed ?

**Comment by dmlloyd** [comment]
Correct, it should be removed.

**Comment by aoudiamoncef** [comment]
@dmlloyd, 
Please, could you tell me why did this code is using unboxing ?

```java
log.warnf("Thread pool shutdown failed: %d threads still running",
                                            Integer.valueOf(executor.getActiveCount()));
```

**Comment by dmlloyd** [comment]
I'm sure it was a mistake.

**Comment by aoudiamoncef** [comment]
I removed it in my last commit.

**Comment by aoudiamoncef** [comment]
Hi @dmlloyd, 
I think that i finished all the  modifications on this PR.

**Review by dmlloyd — APPROVED** [review]

**Comment by dmlloyd** [comment]
Just have to wait for CI testing to finish.

**Comment by machi1990** [comment]
Merged, thanks @aoudiamoncef

**Pull request merged**
