### PR TITLE
Qute: improve bracket notation support, add docs

### LINKED ISSUE #11216: Qute: support bracket notation properly
The current impl is broken and more or less useless. 

~Ideally, the bracket content should be treated as an expression, i.e. `{foo["bar.baz"]}` -> "foo", "bar.baz"; or `{foo[bar.baz]}` where `bar.baz` is evaluated first and the result is the second token.~ 

This would be probably very powerful but also unnecessarily complicated. Therefore, I think it would be ok to only support literal values for `property_name` in the `object[property_name]` syntax.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #11216

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gastaldi** [comment]
@mkouba I went ahead and added the backport tag to 1.7.0.Final, any objections?

**Comment by gsmet** [comment]
I must admit that I'm not very enthusiastic at the idea of backporting this one. I will trust your judgement and we will see.

**Comment by mkouba** [comment]
> I must admit that I'm not very enthusiastic at the idea of backporting this one.

@gsmet It's not necessary. Qute is still an experimental and fast evolving component anyway...

**Pull request merged**
