### PR TITLE
Make TransactionSynchronizationRegistry producer @Unremovable once again

### PR DESCRIPTION
**Pull request by manovotn**
This should fix the CI failures introduced by https://github.com/quarkusio/quarkus/pull/19873

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
@manovotn "Imports are not sorted..." ;-)

**Comment by manovotn** [comment]
@mkouba already fixed ;-)

**Comment by gsmet** [comment]
I fixed the fact that the error was not included in the build report here: https://github.com/quarkusio/quarkus/pull/19936 .

**Review by gsmet — APPROVED** [review]
I'm fast tracking this as it's in the way of everything.

I checked locally that the issues initially introduced are gone.

**Pull request merged**
