### PR TITLE
Add more detail to test result page

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
LGTM !

**Comment by phillip-kruger** [comment]
Did you find out why the button did not work in main ?

**Comment by stuartwdouglas** [comment]
No idea, it worked when I tried it out today

**Comment by phillip-kruger** [comment]
mmm, ok, could be when used in a certain combination.... We need to keep our eye on it... Thanks

**Pull request merged**
