### PR TITLE
Provides a way to configure the maximumMessageSize

### LINKED ISSUE #9196: Gelf handler chunking messages
**Describe the bug**
The gelf handler chunking the messages exceeding 8192 bytes, any meaning full java stack trace exceed this limits. Once messages are chunked Fluentd gelf input plugin rejects the chunked message because of unknown format and log statement never reach elasticsearch

**Expected behavior**
Allow users to configure the maximumMessageSize

```quarkus.log.handler.gelf.maximumMessageSize=2000000```

**Actual behavior**
Message chunking and loss of log statements

**To Reproduce**
1. Configure Gelf logging in quarkus
2. Create a log message size greater than 8192 bytes
3. Notice the log statement chunking and underlying log aggregation rejecting the chunked messages (In this case EFK)

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=${GELF_HOST:localhost}
quarkus.log.handler.gelf.port=${GELF_PORT:12201}
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: amazon linux 2
 - Output of `java -version`:  11.0.6" 2020-01-14
 - GraalVM version (if different from Java): GraalVM CE 19.3.1
 - Quarkus version or git rev: 1.4.2-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn

**Additional context**
JBOSS logmanager JSON logging is outstanding, please support socket appender in addition to existing console, file. So that we can push the logs directly to fluentd tcp source.

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #9196

### CODE REVIEW

**Comment by loicmathieu** [comment]
/cc @missourian55 @geoand 

Keep in mind that this will not disabled chuncking but only allow bigger messages.
Messages will always be sent in chuck if big (this is very important for UDP), so if the receiver didn't support chuncks it will still be possible to have issues.

**Review by missourian55 — APPROVED** [review]

**Review by geoand — APPROVED** [review]
Nice one @loicmathieu.

One question, what value was being used when  `setMaximumMessageSize` was not called? 
I hope `8192` :)

**Comment by loicmathieu** [comment]
@geoand yes, I use as default value the default value from the library.

**Review by gsmet — APPROVED** [review]
Makes sense!

**Pull request merged**
