### PR TITLE
Container JIB: Update base ubi openjdk to tag version to 1.16

### PR DESCRIPTION
**Pull request by davidvoit**

### CODE REVIEW

**Comment by geoand** [comment]
Seems reasonable. @cescoffier WDYT?

**Review by cescoffier — APPROVED** [review]
Sure, looks good.

Note that I will have to update these this week or next...

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks for that but could we do it globally?

See https://github.com/quarkusio/quarkus/pull/32753/files for the full set of changes needed.

**Review by gsmet — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
I squashed the commits and force pushed.

**Comment by davidvoit** [comment]
These CI-erros don't look releated or am I overlooking something

**Pull request merged**
