### PR TITLE
Make it possible to dump transformed classes in the dev/test mode

### PR DESCRIPTION
**Pull request by mkouba**
Simply use the `quarkus.debug.transformed-classes-dir` system property when running the test or `quarkus:dev`.

### CODE REVIEW

**Comment by geoand** [comment]
I'm not sure what the deal is what the deal is with the test failures...

**Comment by mkouba** [comment]
For JDK 14 I can some odd error in `KafkaConsumerTest`:
```
0-05-28T11:40:23.4481716Z Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=apicurio/apicurio-registry-mem:1.1.0.Final, imagePullPolicy=DefaultPullPolicy())
2020-05-28T11:40:23.4481880Z 	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1279)
2020-05-28T11:40:23.4482011Z 	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:613)
2020-05-28T11:40:23.4482122Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
2020-05-28T11:40:23.4482235Z 	... 47 more
2020-05-28T11:40:23.4482618Z Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3: received unexpected HTTP status: 500 Internal Server Error"}
```

**Comment by geoand** [comment]
Lets just restart them when everything completes and see what happens

**Comment by mkouba** [comment]
@geoand @stuartwdouglas PR ready...

**Review by geoand — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
