### PR TITLE
Don't use JSON formatted logs for main integration tests

### LINKED ISSUE #11774: Test failures not clear on root causes
While testing Mandrel 20.2, we discovered the following test failure:

```
2020-08-20T14:15:21.5852034Z [ERROR] Failures: 
2020-08-20T14:15:21.5852333Z [ERROR]   ServletITCase>ServletTestCase.testStaticResource:32 1 expectation failed.
2020-08-20T14:15:21.5853201Z Response body doesn't match expectation.
2020-08-20T14:15:21.5856642Z Expected: a string containing "A HTML page"
2020-08-20T14:15:21.5859431Z   Actual: 
2020-08-20T14:15:21.5859984Z 
2020-08-20T14:15:21.5860194Z [ERROR]   ServletITCase>ServletTestCase.testStaticResourceSubdir:38 1 expectation failed.
2020-08-20T14:15:21.5863287Z Response body doesn't match expectation.
2020-08-20T14:15:21.5863521Z Expected: a string containing "A HTML page"
2020-08-20T14:15:21.5863684Z   Actual: 
2020-08-20T14:15:21.5863752Z 
2020-08-20T14:15:21.5866046Z [ERROR]   ServletITCase>ServletTestCase.testWebjars:66 1 expectation failed.
2020-08-20T14:15:21.5866290Z Expected status code <200> but was <500>.
2020-08-20T14:15:21.5868913Z 
2020-08-20T14:15:21.5869068Z [ERROR]   ServletITCase>ServletTestCase.testWelcomeFile:44 1 expectation failed.
2020-08-20T14:15:21.5869828Z Response body doesn't match expectation.
2020-08-20T14:15:21.5873368Z Expected: a string containing "A HTML page"
2020-08-20T14:15:21.5873568Z   Actual: 
2020-08-20T14:15:21.5873684Z 
2020-08-20T14:15:21.5873797Z [INFO] 
2020-08-20T14:15:21.5877460Z [ERROR] Tests run: 141, Failures: 4, Errors: 0, Skipped: 2
```

Looking closely we discovered that the issue was this error message printed in json format (??):

```
2020-08-20T14:15:16.6258004Z {"timestamp":"2020-08-20T14:15:16.293Z","sequence":1474,"loggerClassName":"io.undertow.UndertowLogger_$logger","loggerName":"io.undertow.request","level":"ERROR","message":"UT005071: Undertow request failed HttpServerExchange{ GET /index.html delegate io.undertow.vertx.VertxHttpExchange@7fa8ee239958}","threadName":"executor-thread-2","threadId":21,"mdc":{},"ndc":"","hostName":"fv-az71","processName":"NativeImageGeneratorRunner$JDK9Plus","processId":3286,"exception":{"refId":1,"exceptionType":"java.util.MissingResourceException","message":"Resource bundle not found sun.util.resources.TimeZoneNames. Register the resource bundle using the option -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames.","frames":[{"class":"com.oracle.svm.core.jdk.LocalizationSupport","method":"getCached","line":66},{"class":"sun.util.resources.Bundles","method":"loadBundleOf","line":52},{"class":"sun.util.resources.Bundles","method":"of","line":106},{"class":"sun.util.resources.LocaleData$1","method":"run","line":185},{"class":"sun.util.resources.LocaleData$1","method":"run","line":182},{"class":"java.security.AccessController","method":"doPrivileged","line":83},{"class":"sun.util.resources.LocaleData","method":"getBundle","line":182},{"class":"sun.util.resources.LocaleData","method":"getTimeZoneNames","line":114},{"class":"sun.util.locale.provider.LocaleResources","method":"getTimeZoneNames","line":270},{"class":"sun.util.cldr.CLDRTimeZoneNameProviderImpl","method":"deriveFallbackName","line":170},{"class":"sun.util.cldr.CLDRTimeZoneNameProviderImpl","method":"getDisplayNameArray","line":93},{"class":"sun.util.locale.provider.TimeZoneNameProviderImpl","method":"getDisplayName","line":99},{"class":"sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter","method":"getName","line":271},{"class":"sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter","method":"getObject","line":229},{"class":"sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter","method":"getObject","line":215},{"class":"sun.util.locale.provider.LocaleServiceProviderPool","method":"getLocalizedObjectImpl","line":150},{"class":"sun.util.locale.provider.LocaleServiceProviderPool","method":"getLocalizedObject","line":242},{"class":"sun.util.locale.provider.TimeZoneNameUtility","method":"retrieveDisplayNamesImpl","line":197},{"class":"sun.util.locale.provider.TimeZoneNameUtility","method":"retrieveDisplayName","line":150},{"class":"java.util.TimeZone","method":"getDisplayName","line":401},{"class":"java.text.SimpleDateFormat","method":"subFormat","line":1302},{"class":"java.text.SimpleDateFormat","method":"format","line":997},{"class":"java.text.SimpleDateFormat","method":"format","line":967},{"class":"java.text.DateFormat","method":"format","line":374},{"class":"io.undertow.util.DateUtils","method":"toDateString","line":109},{"class":"io.undertow.server.handlers.resource.CachedResource","method":"<init>","line":64},{"class":"io.undertow.server.handlers.resource.CachingResourceManager","method":"getResource","line":103},{"class":"io.undertow.server.handlers.resource.CachingResourceManager","method":"getResource","line":30},{"class":"io.undertow.servlet.handlers.ServletPathMatches","method":"getServletHandlerByPath","line":97},{"class":"io.undertow.servlet.handlers.ServletInitialHandler","method":"handleRequest","line":124},{"class":"io.undertow.server.handlers.HttpContinueReadHandler","method":"handleRequest","line":43},{"class":"io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1","method":"handleRequest","line":114},{"class":"io.undertow.server.Connectors","method":"executeRootHandler","line":290},{"class":"io.undertow.server.DefaultExchangeHandler","method":"handle","line":18},{"class":"io.quarkus.undertow.runtime.UndertowDeploymentRecorder$6$1","method":"run","line":398},{"class":"java.util.concurrent.Executors$RunnableAdapter","method":"call","line":515},{"class":"java.util.concurrent.FutureTask","method":"run","line":264},{"class":"org.jboss.threads.ContextClassLoaderSavingRunnable","method":"run","line":35},{"class":"org.jboss.threads.EnhancedQueueExecutor","method":"safeRun","line":2046},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"doRunTask","line":1578},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1452},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"java.lang.Thread","method":"run","line":834},{"class":"org.jboss.threads.JBossThread","method":"run","line":479},{"class":"com.oracle.svm.core.thread.JavaThreads","method":"threadStartRoutine","line":517},{"class":"com.oracle.svm.core.posix.thread.PosixJavaThreads","method":"pthreadStartRoutine","line":192}]}}
```

[Full logs](https://gist.github.com/galderz/4dcb80c340358e35910d13fee85bd2df).

The issue is caused by https://github.com/graalvm/mandrel/issues/106, but the Quarkus test should log such errors better: the exception should be printed as is (no json) and the message sent back to the client should be appropiate (iow, not empty but say there's a server error and provide info?).

### PR DESCRIPTION
**Pull request by jaikiran**
In https://github.com/quarkusio/quarkus/pull/8857 we introduced the `quarkus-logging-json` dependency in the `integration-tests/main` to help us catch issues with JSON formatted logging in native mode. However, recent CI issue investigations and this issue https://github.com/quarkusio/quarkus/issues/11774 have shown that it makes it difficult to debug/read the logs when something goes wrong.

@gsmet, I remember you had mentioned in some old PR that we should perhaps remove this from this `main` integration-tests. So here's the PR. 
I think additionally, we need a new module perhaps to test the JSON formatted logging in integration tests? I know that's a bit of a pain to create and maintain, but I don't see any other way.

Fixes https://github.com/quarkusio/quarkus/issues/11774

### CODE REVIEW

**Comment by gsmet** [comment]
Yeah, I think we need a specific IT, since we will have to test native anyway.

**Comment by machi1990** [comment]
> Yeah, I think we need a specific IT, since we will have to test native anyway.

+1

**Review by gsmet — CHANGES_REQUESTED** [review]
So I'm all for it but I think we need a small isolated native IT for it (unfortunately).

**Comment by jaikiran** [comment]
Agreed. I'll most likely get to it this weekend or later tonight.

**Comment by machi1990** [comment]
> Agreed. I'll most likely get to it this weekend or later tonight.

Cool, thanks.

**Comment by jaikiran** [comment]
I've just now updated this PR to include a new module under `integration-tests` for testing this `logging-json` extension. However, right now, all it does is include that extension in the application and then makes sure the application can log a message and the test can invoke on an endpoint which logs that message.

I actually wanted to even verify (via the automated test) that the logs written out are indeed in expected JSON format. But it looks like this extension is only capable of logging these JSON formatted message to the console? That's my understanding based on what I see in the code and what I noticed in my tests. Is that intentional? I couldn't get this extension to log JSON messages to a file. For now I decided not to try and read content off `System.out` to verify the log messages. I however manually verified that these messages being logged are indeed in JSON format.

**Comment by machi1990** [comment]
> I've just now updated this PR to include a new module under `integration-tests` for testing this `logging-json` extension. However, right now, all it does is include that extension in the application and then makes sure the application can log a message and the test can invoke on an endpoint which logs that message.
> 
> I actually wanted to even verify (via the automated test) that the logs written out are indeed in expected JSON format. But it looks like this extension is only capable of logging these JSON formatted message to the console? That's my understanding based on what I see in the code and what I noticed in my tests. Is that intentional? I couldn't get this extension to log JSON messages to a file. For now I decided not to try and read content off `System.out` to verify the log messages. I however manually verified that these messages being logged are indeed in JSON format.

Thanks @jaikiran for adding the test module. I think having the module is fine and an endpoint that's called from the test is fine. 

When reviewing I noticed that (application.properties)[https://github.com/quarkusio/quarkus/blob/9417cf0a0bc91e5af5c7d079e07aff98264d2e4c/integration-tests/logging-json/src/main/resources/application.properties]  is empty. Maybe we can delete it?

**Comment by jaikiran** [comment]
Hello @machi1990, thank you for the review.

> When reviewing I noticed that application.properties is empty. Maybe we can delete it?

That's a leftover from my experiments of getting the JSON logging to work in files. I've removed it and updated the PR.

**Review by machi1990 — APPROVED** [review]
LGTM, thanks @jaikiran

**Comment by jaikiran** [comment]
Hello @gsmet, this is ready for a review and merge.

**Comment by gsmet** [comment]
I pushed an additional commit to trigger native testing on CI.

**Review by gsmet — APPROVED** [review]

**Comment by jaikiran** [comment]
> I pushed an additional commit to trigger native testing on CI.

Thank you for doing that. I was under the wrong impression that the CI workflow picks up all integration test modules (from the parent `pom.xml`'s `modules`) by default to run the native tests. So never bothered adding this there.

**Pull request merged**
