### PR TITLE
Trigger restart when deleting previously existing watched file

### LINKED ISSUE #25331: Deleting a watched file in dev mode doesn't trigger a restart
### Describe the bug

When a build step registers a file to be watched and trigger a restart (using `HotDeploymentWatchedFileBuildItem`), deleting the file doesn't trigger a restart of the application, as it should.

Debugging shows that the call to `RuntimeUpdatesProcessor#checkForFileChange()` in `RuntimeUpdatesProcessor#doScan()` returns the empty set when a watched file is deleted.

### Expected behavior

A watched file registered to trigger a restart should trigger a restart when the file is deleted by the user.

### Actual behavior

The file deletion appears to go undetected and thus doesn't cause a restart. It may however cause other failures, since there is application state which expects the files to still exist. One such case is the Flyway extension, which will fail when triggering a _Migrate_ action from the Dev UI.

### How to Reproduce?

Steps to reproduce:
1. Create a new application
2. Make sure there is an `application.properties` file in it
3. Start the application in dev mode
4. Delete the `application.properties` file
5. Trigger some action in the Dev UI (which should trigger a restart when required)
6. Check if the application was actually restarted

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Postremus**
Also fixes naming of the processor responsible for the initial watched files scan

Fixes #25331

### CODE REVIEW

**Comment by Postremus** [comment]
Will have to take a closer look why the maven tests failed, looks related.

**Comment by Postremus** [comment]
Setting to draft, I want to do a full CI run in my fork first. I also need to possible do another cleanup pass before this is ready.

I found the reason why the tests where failing.
It is related to them having multiple resource directories, and me introducing deletion of single files in target/classes when they got deleted in the resource directory.

Basicly, it went like this.
resource-dir-a: contained application.properties
resource-dir-b: no application.properties

First, resource-dir-a was checked. application.properties was found - no need to delete anything.
resource-dir-b got checked for application.properties. which was not found. Now, the file got deleted from the outputdir, even though it existed in the another resource root.

**Comment by Postremus** [comment]
CI passes in my fork, this is now ready for review.

**Review by aloubyansky — APPROVED** [review]
Looks good, @Postremus, thanks! Would be good to have a test for it though. Will you have time to add one? Just in case it helps, we already have some test projects that include extensions, e.g. https://github.com/quarkusio/quarkus/tree/main/integration-tests/maven/src/test/resources-filtered/projects/project-with-extension.

**Comment by Postremus** [comment]
@aloubyansky I added one in DevMojoIT.

**Comment by aloubyansky** [comment]
Excellent. Thanks @Postremus !

**Pull request merged**
