### PR TITLE
Add wellness health handling

### LINKED ISSUE #12071: /health/well is not exposed
**Describe the bug**
In SR Health 2.2.2 we've introduced the experimental Wellness feature - https://github.com/smallrye/smallrye-health/releases/tag/2.2.2 that also introduced a new health endpoint -- `/health/well` which is not currently exposed by Quarkus. Please note that `@Wellness` annotated checks are still collected in the `/health` endpoint.

**Expected behavior**
`/health/well` is exposed.

**Actual behavior**
`/health/well` is returning 404.

**To Reproduce**
1. Add simple `@Wellness` health check
2. access `/health`
3. access `/health/well`

reproducer - https://github.com/xstefank/quarkus-well-endpoint

### PR DESCRIPTION
**Pull request by xstefank**
resolves #12071

### CODE REVIEW

**Comment by mkouba** [comment]
Is the Wellness feature documented somewhere?

**Comment by xstefank** [comment]
@mkouba not yet, we are working on full documentation on the smallrye side.

**Review by mkouba — APPROVED** [review]
Looks good.

**Comment by gsmet** [comment]
@jmartisk we let you check and merge this one?

**Review by jmartisk — APPROVED** [review]
LGTM

**Pull request merged**
