### PR TITLE
mongodb-client: Make it possible to override default providers

### PR DESCRIPTION
**Pull request by jayee**
Make it possible to override the default codec providers by changing the order in the codec registry created during initalization.

In my case I wanted to a use different UuidCoded instead of the default.

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier can you have a look to that one?

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
LGTM, thanks!

**Comment by geoand** [comment]
Hi,

Can you please rebase onto master to pick up a fix for CI?

Thanks

**Comment by gsmet** [comment]
Let's take the risk to merge it, the failures are really unrelated.

**Pull request merged**
