### PR TITLE
Jakarta migration: Agroal, Hibernate ORM, Hibernate Search...

### PR DESCRIPTION
**Pull request by gsmet**
For now, I build a fork of Agroal locally while waiting for the release.

### CODE REVIEW

**Comment by gsmet** [comment]
@glefloch any chance you could have a look at the Gradle failure? I have no idea how what I did could have triggered the issue and the setup of the test is a bit complex.

**Comment by gsmet** [comment]
BTW, I can reproduce it locally so there's a real issue. But no idea why the dependency is now popping up.

From what I can see this particular build brings `implementation("io.quarkus:quarkus-agroal-deployment")` from ext-a so its not surprising that Agroal is around in the deployment dir but maybe I'm missing something.

**Comment by glefloch** [comment]
@gsmet yes I can have a look this afternoon.

**Comment by gsmet** [comment]
@glefloch cool, thanks!

**Comment by glefloch** [comment]
Looking at `git blame` it seems that `narayana-deployment` and `agraoal-deployment` dependencies where added by mistake when testing the  validation task of `io.quarkus.extension` Gradle plugin. 

In that test we check that agroal is not transitively imported when depending on `panache-reactive` (we add an issue on hat), however, I don't understand why it only starts failing now ... I pushed a fix that remove those dependencies.

**Comment by gsmet** [comment]
thanks @glefloch

**Pull request merged**
