### PR TITLE
Add copy button for configuration properties in config tables

### PR DESCRIPTION
**Pull request by michalvavrik**
Addresses: https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/Doc.20-.20Copy.20property.20name/near/452271216

two-buttons
single-button

This won't work until https://github.com/quarkusio/quarkusio.github.io/pull/2157 is merged and CI is rerun with that change.

### CODE REVIEW

**Comment by michalvavrik** [comment]
That docs CI failure didn't fail when I build docs and server it. I'll check command used by CI and try to fix it.

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks! I think we will need to implement something similar to what was done for env vars:

https://raw.githubusercontent.com/quarkusio/quarkus/ecef520cb35eb493a22f68804eb0f153d2b684aa/devtools/config-doc-maven-plugin/src/main/resources/templates/asciidoc/default/tags/envVar.qute.adoc

This is needed for the downstream doc.
But happy to discuss if you had something else in mind.

I think we could have only one common property for that as it's all about having the ability to handle the feature.

**Comment by michalvavrik** [comment]
> Thanks! I think we will need to implement something similar to what was done for env vars:

The difference is that this is inline (like this is inside table row that is inline) so you cannot use ifdef etc. Before I went this implementation, I tried to make this conditional for hours. I am no Asciidoc expert though, if you think it can be done, I'll dig again. (also I found some links to Asciidoc about that https://discuss.asciidoctor.org/Inline-Conditional-Inclusion-Macros-td3007.html that suggested the same)

> This is needed for the downstream doc. But happy to discuss if you had something else in mind.

I'll come for solution for downstream, but I'll need pointers. I added that "inline macro process" that I thought is enough for any scenario that is not supported. If you tell me how downstream docs is build, I'll prepare NOOP macro.

> I think we could have only one common property for that as it's all about having the ability to handle the feature.

I'd like that, but again, I don't know how to make this conditional.

**Comment by gsmet** [comment]
But is it a problem if it's on another line? My understanding is that it would end up on the same line in the end? But maybe it wouldn't work?

**Comment by gsmet** [comment]
And the envVar a few lines below is not in the same situation? If adding a block solves the issue, maybe we could do the same as for `.description` and have a block with no styling? Would it change the output?

**Comment by michalvavrik** [comment]
> And the envVar a few lines below is not in the same situation? 
> If adding a block solves the issue, maybe we could do the same as for `.description` and have a block with no styling? Would it change the output?

Fair point, from DOM POV they are all div paragraphs inside one div paragraph so there shouldn't be a problem. I'll figure why it works for the env var. Thanks

**Comment by michalvavrik** [comment]
@gsmet the issues I experienced were due to the fact that qute template didn't end with an empty line, it messed things. works now. I tested it and works when copy button is enabled with https://github.com/quarkusio/quarkusio.github.io/pull/2164

image

I'll need to re-check tomorrow forenoon because I made one cosmetic change that I won't wait till docs rebuild now. Unless I report back tomorrow, please consider this ready for review. Thanks

**Comment by michalvavrik** [comment]
I have tested it with and without `add-copy-button-to-config-props: true` and works as expected. I think this is ready for review.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks a lot!

**Pull request merged**
