### PR TITLE
fix: build warning

### PR DESCRIPTION
**Pull request by machi1990**
Follows up https://github.com/quarkusio/quarkus/pull/4089

/cc @gsmet @geoand for a quick review.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks @machi1990

**Comment by gsmet** [comment]
Hmmm, it looks a lot like this PR of mine? https://github.com/quarkusio/quarkus/pull/4089/files

It has been merged so I'm surprised it's not fixed.

**Comment by machi1990** [comment]
> Hmmm, it looks a lot like this PR of mine? https://github.com/quarkusio/quarkus/pull/4089/files
> 
> It has been merged so I'm surprised it's not fixed.

Yes, I was surprised to find these leftovers - the profiles part was not modified.

**Comment by gsmet** [comment]
Aaaaah, OK, I missed the changes were in the native profiles :).

Good catch, thanks!

**Review by gsmet — APPROVED** [review]

**Pull request merged**
