### PR TITLE
Testcase to verify that the StaticHandler can handle requests with If-Modified-Since header without running into thread safety issues

### PR DESCRIPTION
**Pull request by jaikiran**
The commit here adds a testcase to reproduce the issue reported in https://github.com/quarkusio/quarkus/issues/4627.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for the PR @jaikiran, it seems however that the JVM tests are failing

**Comment by geoand** [comment]
Just out of curiosity @jaikiran , does the new test pass with the fix proposed in https://github.com/vert-x3/vertx-web/pull/1432?

**Comment by jaikiran** [comment]
Hello @geoand, I haven't yet had a chance to build the snapshot version of vertx-web and test this out. Will do some time soon.

**Comment by jaikiran** [comment]
Having said that, once https://github.com/quarkusio/quarkus/pull/4689 gets merged here, this testcase should start passing and this PR can be merged, since 3.8.3 has a fix which works around the root cause of this issue.

**Comment by jaikiran** [comment]
@geoand  @gsmet  This is now ready to be reviewed and merged. The latest failures don't seem related to this.

**Comment by geoand** [comment]
Yeah CI is misbehaving at the time being, we are looking into it. So most likely we will ask you to rebase at some point.

Thanks

**Comment by geoand** [comment]
@jaikiran can you please rebase onto the latest master?

Thanks

**Comment by jaikiran** [comment]
Done - rebased against latest master

**Comment by geoand** [comment]
@vietj mind taking a look please?

**Comment by geoand** [comment]
@cescoffier WDYT will you have time to do a quick check for this one?

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
It's a test, let's get it in and make progress. Thanks @jaikiran !

**Pull request merged**
