### PR TITLE
Panache optional predicate

### PR DESCRIPTION
**Pull request by loicmathieu**
I prototype optional predicates as discussed here: #2303
This is a draft PR to discuss the implementation.

For the sake of simplicity, as MongoDB already use the parse I implement it for MongoDB only.

This PR enable this for MongoDB with Panache:

```
Person.find("name? = ?1 and status = ?2", "Loïc", Status.ALIVE)
=> generates the following query : {'name' : 'Loïc', 'status' : 'ALIVE'}
Person.find("name? = ?1 and status = ?2", null, Status.ALIVE)
=> generates the following query : { 'status' : 'ALIVE'}
Person.find("name? = ?1", null)
=> generates the following query : { }
```

### CODE REVIEW

**Comment by loicmathieu** [comment]
@emmanuelbernard @FroMage WDYT ?

The main caveat is that you can no longuer express query like `{'name' : null}` when using optional prediate. Or we will need to use a null placeholder like `Person.find("name? = ?1", PanacheQuery.NULL)` but this is not very convenient for a user ...

The second caveat is that you must pass null parameters, so when using the `Parameters` API you will need to write something like this that can seems boilerplate :
```
Person.find("name? = :name", Parameters.with("name", null))
```

**Comment by emmanuelbernard** [comment]
hey @loicmathieu thanks for that work.
Just looking at your PR description: yes that's the expected query.

I don't understand your remark around the caveats. If you want to ignore null, then `name?` is your friend. If you want to handle null, then `name` is your friend. How is that a loss of feature? 

About your second caveat, it's true but that's not the usage. The usage is

```
class Person ... {
    findAllOrByName(String name) {
        return find("name? = :name", Parameters.with("name", name));
    }
}
```

Note that Gavin and I discussed that a while back and I owe him a formal description of the behavior when OR / AND are thrown into the mix. I could not find time to do it yet. We need that before we push that feature,

**Comment by emmanuelbernard** [comment]
> @emmanuelbernard I will try to stetup the parser for Hibernate next week and we will see how it works.
> I wonder if I should put this feature behind a property to be able to disabled (this can solve issue where a user have a query that works without the parser and didn't work with it).

That would be un Quarkusy

**Comment by emmanuelbernard** [comment]
But to be honest unless we have the OR / AND semantic figured out, we won't be able to release (or only as preview)

**Comment by gsmet** [comment]
Closing as out of date. Please reopen with an update if you still want this in.

**Pull request closed without merging**
