### PR TITLE
Add apicurio protobuf support

### PR DESCRIPTION
**Pull request by carlesarnal**
This introduces support for serialization using protobuf as #37722 introduced for JSON Schema. The caveat here is that Protobuf serialization does not work for now in native mode. I will investigate more.

### CODE REVIEW

**Comment by carlesarnal** [comment]
The problem with the native integration test is that when the test is executed in that mode, the runtime used for generating the class and the one used for running the test is different, causing protobuf to fail validating the message. The flow and test works fine in JVM mode, and that might be all that can be done here.

**Comment by cescoffier** [comment]
@alesj can you have a look?

**Comment by alesj** [comment]
@cescoffier yeah, already on my todo list for this week -- all coordinated with @carlesarnal

**Comment by carlesarnal** [comment]
@alesj now the error must be reproducible. Note that I had to revert the banned dependency, so I'm going to close the PR for now so it does not get merged by mistake.

**Pull request closed without merging**
