### PR TITLE
Upgrade to Hibernate ORM 6.2.0.CR3

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]

**Comment by yrodiere** [comment]
The failure in `integration-tests/opentelemetry-jdbc-instrumentation` *may* be related, since that module uses Hibernate ORM...

We'll need more investigation, but since it happens only in native mode, it might be related to the reflection metadata you removed?

https://github.com/quarkusio/quarkus/pull/31526/files#diff-583c184a7bb985fc15d72cd11861e77f12dbd3332307065f3122b8d6390c1602L1617-L1639

I.e. maybe some things are missing in the metadata shipped with ORM?

**Comment by geoand** [comment]
> The failure in integration-tests/opentelemetry-jdbc-instrumentation may be related, since that module uses Hibernate ORM...

I've seen it fail in a lot of PRs lately. Just wanted to mention it, I don't know if this PR makes things better or worse WRT the failing IT

**Comment by yrodiere** [comment]
> I've seen it fail in a lot of PRs lately. Just wanted to mention it, I don't know if this PR makes things better or worse WRT the failing IT

Ah, thanks. Then I'll let people more versed into OTEL have a look :)

**Comment by Sanne** [comment]
@yrodiere I *think* I have the same metadata upstream, but a fresh pair of eyes wouldn't hurt:

https://github.com/quarkusio/quarkus/pull/31526/files#diff-583c184a7bb985fc15d72cd11861e77f12dbd3332307065f3122b8d6390c1602L1617-L1639

https://github.com/hibernate/hibernate-orm/blob/3f24a0064fdc7581582eca5806256d76249a0d42/hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/StaticClassLists.java#L98-L116

It did pass all other tests ..

**Comment by yrodiere** [comment]
> @yrodiere I _think_ I have the same metadata upstream, but a fresh pair of eyes wouldn't hurt:
> 
> https://github.com/quarkusio/quarkus/pull/31526/files#diff-583c184a7bb985fc15d72cd11861e77f12dbd3332307065f3122b8d6390c1602L1617-L1639
> 
> https://github.com/hibernate/hibernate-orm/blob/3f24a0064fdc7581582eca5806256d76249a0d42/hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/StaticClassLists.java#L98-L116

Yes, looks identical to me.

**Pull request merged**
