### PR TITLE
QuarkusTestExtension enum lookup via name() not toString().

### PR DESCRIPTION
**Pull request by jimbogithub**
Enum::toString can be overridden and may not match the Enum constant.  Enum::name is used for that purpose.

### CODE REVIEW

**Comment by gastaldi** [comment]
Can you squash your commits?

**Comment by jimbogithub** [comment]
Nope.  Wouldn't have a clue.

**Comment by geoand** [comment]
https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by jimbogithub** [comment]
No list of picks.  Are you sure you want to spend your time giving me a tutorial on this?  Might just be easier to close this and apply the patch yourself.

**Comment by geoand** [comment]
We certainly could, but don't you want to have your name in the Quarkus contributors list :wink: ?

**Comment by geoand** [comment]
In any case, this has been superseded by #9340

**Pull request closed without merging**
