### PR TITLE
ArC - fix CreationalContext handling when used directly with BeanManager

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
For historical reference, this PR fixes `@PreDestroy` interceptors/callbacks being invoked twice for `@Dependent` beans, when the dependent bean was created through `BeanManager.getReference()` and is destroyed through `Bean.destroy()`.

**Comment by manovotn** [comment]
> ... when the dependent bean was created through BeanManager.getReference() and is destroyed through Bean.destroy().

Just my favourite way of creating and destroying beans :)

I am a bite late but LGTM and thanks for fixing this!

**Comment by gsmet** [comment]
@mkouba is this something that we want backported to 3.0.2.Final?

**Comment by mkouba** [comment]
> @mkouba is this something that we want backported to 3.0.2.Final?

I don't think it's necessary because the problem was only spotted in the TCK runner. @Ladicek @manovotn WDYT?

**Comment by manovotn** [comment]
+1, no need to port this.

**Pull request merged**
