### PR TITLE
Rename Dev Console to Dev UI

### LINKED ISSUE #14296: dev console -> dev mode
**Description**
Quarkus Developer Console has some unfortunate connotations of it might be for management features or cause confusion between OpenShift Developer Console. 

Suggestion that came up during conversations was to simply just call the page "Dev Mode" or "Quarkus Dev Mode" in full.

This would:

a) avoid using the already overloaded console term
b) makes it clear this feature set is for development mode; not a management tool of any sorts
c) does not introduce new vocabulary besides "dev mode"  page.

Too late for 1.11 but I suggest we do it in 1.11.1

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #14296

FWIW, we have the `Q` logo on the right so I don't think it's worth having `Quarkus` too.

I'll let you bikeshed on this :).

### CODE REVIEW

**Comment by maxandersen** [comment]
Wasn't there a build item named DevConsole ? On phone so can't check.

**Comment by maxandersen** [comment]
But I guess we'll have to live with that as release built :)

**Review by phillip-kruger — APPROVED** [review]
We can also consider allowing users to name this themselves, using config, with the default being 'Dev UI'. This might give them the opportunity to give more context to the screen. Same goes for the other UIs.

**Comment by gsmet** [comment]
There are a ton of things named DevConsole. I don't know if we want to change everything or just the name given some extensions started to use it and we released 1.11.0.Final already?

Not sure it's really a problem. In any case, we need an easy backport for 1.11, even if we decide to make things consistent for 1.12 (and the latter will make backporting a lot harder).

@FroMage WDYT?

**Comment by stuartwdouglas** [comment]
I think its fine to leave the backend stuff as-is. The time to rename them would have been before the release.

**Comment by FroMage** [comment]
Yeah, let's just rename what it's called. Though docs may have to be updated too, no?

**Review by FroMage — CHANGES_REQUESTED** [review]
The docs have to be updated too :)

**Comment by gsmet** [comment]
@FroMage I updated the documentation and fixed a few things (some typos and errors in the links, also switched to US English as most of our doc are US English). Nothing big.

I also updated part of the screenshots. Didn't have any RESTEasy Reactive app around and the clear cache feature was failing.

**Review by FroMage — APPROVED** [review]

**Pull request merged**
