### PR TITLE
fix: use unique key name when generating config section anchor

### PR DESCRIPTION
**Pull request by machi1990**
The issue was reported here - https://github.com/quarkusio/quarkus/pull/4529#issuecomment-551883480

@geoand @dufoli this should fix the doc building issue for https://github.com/quarkusio/quarkus/pull/4529. Can you please confirm? Thanks

### CODE REVIEW

**Comment by geoand** [comment]
I don't really know anything about the docs generation process so best this be reviewed by someone who does

**Comment by machi1990** [comment]
Thanks @geoand I think anyone can review it. But  I was hoping @dufoli could try first with his PR and see if it fixes the issue he encountered there.

**Comment by dufoli** [comment]
@machi1990 it fix PR   #4529. So for me good fix to merge ;-)

**Comment by machi1990** [comment]
@dufoli Good to hear that the fix unblocked your PR. We'll try to get this fix in so that you can a proper rebase. 
/cc @geoand 

/cc @FroMage if you could have a look.

**Comment by geoand** [comment]
It seems simple enough to me but I am reluctant just because I haven't the faintest idea of how docs are generated.
I'd rather if @FroMage took a look

**Comment by machi1990** [comment]
Yes, let's wait for @FroMage. I pinged you earlier as in France we had a long weekend (yesterday was holiday) and Stéphane was sure not around :-)

**Review by FroMage — APPROVED** [review]
So we're using the artifact id as prefix instead of the module name. That looks OK to me.

**Comment by machi1990** [comment]
Thanks @FroMage :-)

**Pull request merged**
