### PR TITLE
Migrate off ancient Plexus components

### PR DESCRIPTION
**Pull request by cstamas**
To JSR330, and drop use of archived plexus-component-metadata plugin and replace it with sisu-maven-index.

### CODE REVIEW

**Comment by cstamas** [comment]
@aloubyansky  ping

**Review by aloubyansky — APPROVED** [review]
Thanks @cstamas!

**Comment by cstamas** [comment]
Aside of these component changes, there are two "critical" classes, both relying on ancient Plexus Container internals:
* `independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapWagonConfigurator.java`
* `independent-projects/enforcer-rules/src/main/java/io/quarkus/enforcer/DeploymentDependencyRuleSupport.java`

Just FTR

**Comment by aloubyansky** [comment]
In the `beanbag` branch and PR `BootstrapWagonConfigurator` is not actually used anymore. Thanks for point out.

**Comment by famod** [comment]
Interesting, will do the same in https://github.com/gitflow-incremental-builder/gitflow-incremental-builder

@cstamas 

>     * `independent-projects/enforcer-rules/src/main/java/io/quarkus/enforcer/DeploymentDependencyRuleSupport.java`

Do you mean the handling of `org.codehaus.plexus.component.configurator.expression.ExpressionEvaluationException`?
Can you suggest a replacement? Thanks!

**Review by dmlloyd — APPROVED** [review]

**Pull request merged**
