### PR TITLE
Narayana update to 7.0.1.Final

### PR DESCRIPTION
**Pull request by marcosgopen**
The component upgrade brings some major updates, most notable are the TransactionReaper related issues: https://issues.redhat.com/browse/JBTM-3830 and https://issues.redhat.com/browse/JBTM-3837. Then there other minor updates such as the issue related to https://github.com/quarkusio/quarkus/issues/30491 which was resolved by https://issues.redhat.com/browse/JBTM-3821.

Tag: [https://github.com/jbosstm/narayana/releases/tag/7.0.1.Final](https://github.com/jbosstm/narayana/releases/tag/7.0.0.Final)
Diff: https://github.com/jbosstm/narayana/compare/7.0.0.Final...7.0.1.Final
Release Notes: https://issues.redhat.com/secure/ReleaseNote.jspa?version=12423360&styleName=Html&projectId=12310200

### CODE REVIEW

**Comment by mmusgrov** [comment]
@marcosgopen @yrodiere The LRA test failures are because there is no external LRA coordinator running and I don't know what job config is needed to deploy such a coordinator.

**Comment by yrodiere** [comment]
> @marcosgopen @yrodiere The LRA test failures are because there is no external LRA coordinator running and I don't know what job config is needed to deploy such a coordinator.

Since the tests are pre-existing I'd expect that config to already be there... or have these tests been failing for a long time?

**Comment by mmusgrov** [comment]
I do see the following in the log:

```
2024-02-27 08:29:55,847 INFO  [tc.qua.io/jbosstm/lra-coordinator:latest] (main) Container quay.io/jbosstm/lra-coordinator:latest started in PT1.157615776S
2024-02-27 08:29:56,481 WARN  [io.qua.boo.BootstrapAppModelFactory] (main) Expected project directory /home/runner/work/quarkus/quarkus/tcks/microprofile-lra/target/quarkus-arquillian-test3075692299612060282/app does not match current project directory /home/runner/work/quarkus/quarkus/tcks/microprofile-lra
```
Is that related?

**Comment by yrodiere** [comment]
> I do see the following in the log:
> 
> ```
> 2024-02-27 08:29:55,847 INFO  [tc.qua.io/jbosstm/lra-coordinator:latest] (main) Container quay.io/jbosstm/lra-coordinator:latest started in PT1.157615776S
> 2024-02-27 08:29:56,481 WARN  [io.qua.boo.BootstrapAppModelFactory] (main) Expected project directory /home/runner/work/quarkus/quarkus/tcks/microprofile-lra/target/quarkus-arquillian-test3075692299612060282/app does not match current project directory /home/runner/work/quarkus/quarkus/tcks/microprofile-lra
> ```
> 
> Is that related?

It does look like it. I'm not familiar with Narayana tests.

Try running the tests locally with `./mvnw -f <path to pom> -Dstart-containers -Dtest-containers`; provided you have docker locally, it should start containers just as it does on CI.

**Comment by mmusgrov** [comment]
@marcosgopen Do you know if we updated "quay.io/jbosstm/lra-coordinator:latest" during the release?

**Comment by marcosgopen** [comment]
> @marcosgopen Do you know if we updated "quay.io/jbosstm/lra-coordinator:latest" during the release?

We did not @mmusgrov

**Comment by mmusgrov** [comment]
In that case the follow up question is: can we find out what version of narayana is used by  "quay.io/jbosstm/lra-coordinator:latest" and analyse why it might have broken tcks/microprofile-lra?

**Comment by marcosgopen** [comment]
> @marcosgopen Do you know if we updated "quay.io/jbosstm/lra-coordinator:latest" during the release?

Actually the quay.io/jbosstm/lra-coordinator:latest was updated 2 days ago.

**Comment by marcosgopen** [comment]
I could reproduce the error locally with latest (7.0.0.Final-3.8.0) version of lra-coordinator-quarkus. 7.0.0.Final-3.6.6 seems to work though.

**Comment by xstefank** [comment]
Just note that I can't reproduce this locally so I believe this is CI as mentioned by @gsmet. But I'll work on rewriting this to DevService soon nevertheless.

**Comment by xstefank** [comment]
There is really an issue with the produced coordinator JAR but we will be pushing fixed tag soon.

**Comment by xstefank** [comment]
@mmusgrov pushed the new image to quay.io, can you force push to retrigger the tests?

**Comment by marcosgopen** [comment]
> @marcosgopen pushed the new image to quay.io, can you force push to retrigger the tests?

Thanks @xstefank , I have just force pushed.

**Comment by mmusgrov** [comment]
To facilitate debugging this kind of issue with the container we need to capture the coordinator output using the testcontainers GenericContainer#getLogs() call unless the container output is already available to the CI job, @gsmet do you know if it is accessible?

**Comment by gsmet** [comment]
I don't think the container logs are accessible. Well, the startup logs are in the log output we have on GH Actions. Not sure if you need more?

**Comment by xstefank** [comment]
@mmusgrov we will be testing the image also on the narayana side from now on where we will be able to catch this issues before the image release.

**Comment by marcosgopen** [comment]
I rebased this PR.

**Review by gastaldi — APPROVED** [review]

**Review by yrodiere — COMMENTED** [review]
My review is not necessary at all here, I don't have any relevant knowledge. Since @mmusgrov doesn't seem opposed to the upgrade and @gastaldi approved, let's merge it.

**Pull request merged**
