### PR TITLE
Hot reload tests for Reactive SQL Clients

### LINKED ISSUE #6917: Add hot reload tests for Reactive SQL Clients
Nothing fancy, but make sure the databases can be queried again when after code changes

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #6917

### CODE REVIEW

**Comment by tsegismont** [comment]
@cescoffier can you please review?

I chose to use callback-based pools instead of Axle version because the API is soon to be deprecated.

**Comment by gsmet** [comment]
@tsegismont CI failed with:
```
io.vertx.pgclient.PgException: password authentication failed for user "user"
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:29)
	at io.vertx.pgclient.impl.codec.InitCommandCodec.handleErrorResponse(InitCommandCodec.java:76)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:235)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:123)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:103)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tsegismont** [comment]
I had not anticipated that a Postgres server might be running at this stage
of the build. I will update the test

**Comment by tsegismont** [comment]
@gsmet test updated

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
