### PR TITLE
Bump Keycloak version to 17.0.1

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by sberyozkin** [comment]
`io.quarkus.resteasy.reactive.jackson.deployment.test.SimpleJsonTest` in JDK11

**Comment by gsmet** [comment]
@sberyozkin I reverted this commit as there's definitely something wrong. Could you have a look soon, it's definitely our top priority if we want the admin client situation to be sorted out.

**Comment by sberyozkin** [comment]
@gsmet I'll have a look, missed checking these 2 tests

**Comment by sberyozkin** [comment]
@gsmet @geoand I've rerun these tests locally, all works fine, I think it is a test issue (timing probably), I recall now seeing exactly the same container tests failing in native in CI with the upgrade to 17.0.0 - these tests depend on Dev Services for Keycloak which from 17.0.0 use a Quarkus powered image by default. Then I also tested locally, and just rebased the failing PR and it all worked.

Not sure what can be done to avoid these specific intermittent test failures

**Comment by sberyozkin** [comment]
@gsmet @geoand It might be a race condition - with Quarkus based distro the only way at the moment to import a realm into Keycloak is to use Admin API to HTTP POST it to Keycloak as JSON (with WildFly distro it is imported at the startup). So one theory Keycloak might still be finalizing the realm creation by the time the test starts running.

**Comment by geoand** [comment]
If that is the case, is there a way to wait for that to complete?

**Comment by sberyozkin** [comment]
Sure, trying to add something

**Comment by sberyozkin** [comment]
@geoand Do you know how to capture the Quarkus log output in these container tests ? I've been chasing the source of 401 without luck so far

**Comment by geoand** [comment]
You mean the keycloak container?

**Comment by sberyozkin** [comment]
@geoand No, from Quarkus. The log messages are not reported, I thought Quarkus was also running in a container...

**Comment by sberyozkin** [comment]
I'll try file based logging

**Comment by geoand** [comment]
We override the logs to be output in a file when `@QuarkusIntegrationTest` is used. That file is in the target directory, but I am not sure you can access it in CI...

You might have to define a named logger just for the purposes of debugging

**Comment by sberyozkin** [comment]
I can see them all locally in `target` but because I'm slow I can't get Quarkus logs shown there, even with the file logging enabled, so I've come with the worst idea ever, I'm modifying the OIDC code to report some data back to the test, and finally I've had some progress, an issuer mismatch, will look at it next

**Comment by sberyozkin** [comment]
```
Issuer (iss) claim value (http://localhost:41035/realms/quarkus) doesn't match expected value of http://localhost:8080/realms/quarkus]
```

port mismatch, just have to step outside but will look a bit later; DevServices setup issue

**Pull request merged**
