### PR TITLE
Lift restriction of HTTP application for Kubernetes manifest generation

### LINKED ISSUE #19442: Cannot deploy "pure" messaging application to Kubernetes
### Describe the bug

If you have an application that does not run an HTTP server, the OpenShift/Kubernetes metadata generation fails with:
```
No Openshift manifests were generated (most likely due to the fact that the service is not an HTTP service) so no openshift process will be taking place
```

It does not fail the build, just do not generate the descriptors and skip the deployment. 

Not having an HTTP server is very likely for pure messaging applications that do not expose an HTTP endpoint.

### Expected behavior

It should still generate the descriptor and proceed with the deployment.

### Actual behavior

It skips the descriptor and deployment.

### How to Reproduce?

Use the kafka-quickstart, go to the `processor` sub-module.
Then run:

```
> mvn quarkus:add-extension -Dextensions="openshift"
> mvn clean package -Dquarkus.container-image.build=true -DskipTests -Dquarkus.container-image.push=true
```

### Output of `uname -a` or `ver`

Darwin bespin.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

no native involved in this issue

### Quarkus version or git rev

main branch (999-SNAPSHOT)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Resolves: #19442

### CODE REVIEW

**Comment by geoand** [comment]
@cescoffier mind giving this a try as a resolution for https://github.com/quarkusio/quarkus/pull/19616 ?

**Review by cescoffier — APPROVED** [review]
LGTM!

Thanks!

**Comment by geoand** [comment]
This basically leaves the Deployment or DeploymentConfig as it is, but removes the ports part .

It also doesn't generate a Service because the application isn't accessible over the wire

**Comment by geoand** [comment]
I'll merge this as it will be nice to have for 2.2.0.Final

**Pull request merged**
