### PR TITLE
Gradle: include test sources in the ApplicationModel for dev mode

### LINKED ISSUE #23735: Gradle Unit Tests Don't Work Since 2.7.1
### Describe the bug

After moving to Quarkus 2.7.1 from 2.7.0 unit tests in Gradle no longer run. 

Quarkus says "No tests found" even though there tests.

### Expected behavior

Unit tests run and fail because my code is trash

### Actual behavior

Unit tests pass saying "No tests found" so I push it to prod and my boss gets angri :fearful: 

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

OpenJDK Runtime Environment 18.9 (build 11.0.14+9)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fix #23735

### CODE REVIEW

**Comment by gsmet** [comment]
@glefloch it would be nice if you could have a look at this one today as I'm releasing 2.7.2.Final tomorrow morning and it looks like a serious regression.

**Review by glefloch — APPROVED** [review]
LGTM

**Comment by glefloch** [comment]
I amended the commit with formatting.

**Comment by aloubyansky** [comment]
Thanks @glefloch!

**Comment by glefloch** [comment]
The failure doesn't seem to be related.

**Pull request merged**
