### PR TITLE
Google Cloud Functions documentation improvements

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by loicmathieu** [comment]
Test failures seems un-related (micrometer and opentelemetry assertion failures).

**Comment by loicmathieu** [comment]
Can someone review this one please ? @gsmet or @geoand maybe ?
I have another PR which may be in conflict so I cannot finish it untill this one is merged.

**Comment by geoand** [comment]
Although this looks correct, I don't know the details of how the docs are built, so I'll leave it to Guillaume.

**Comment by loicmathieu** [comment]
I checked the generated docs for the correct replacement of attributes, but OK, let's wait for Guillaume

**Comment by loicmathieu** [comment]
@gsmet can you validate this PR ? I check the generated doc for the variable replacement this should be OK.

**Review by gastaldi — APPROVED** [review]
LGTM

**Pull request merged**
