### PR TITLE
Fix MongoDB Panache projection

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by FroMage** [comment]
Looks OK, but I don't understand why the existing tests didn't show this, and why we don't need a new test to show we've fixed it?

**Comment by loicmathieu** [comment]
@FroMage I agree with you and I'm a little disturbed by the fact the our integration test worked as it is the same as the example that didn't works on the mailing list.

I verify it with the example on the mailing list and it passes.

Now, two options, dig inside the issue and try to understand it better ... or admit that computer science is part of the chaos theory and that we didn't understand everything and merge it ;)

Anyway, this PR is the right implementation, it's just fustrating because it shouldn't have worked in the first place ...

**Comment by FroMage** [comment]
Are you sure the tests are run?

**Comment by loicmathieu** [comment]
@FroMage yes, I double checked via a good old sysout and it's called inside 
```
    @GET
    @Path("/search/{name}")
    public List<PersonName> searchPersons(@PathParam("name") String name) {
        return personRepository.find("lastname", name).project(PersonName.class).list();
    }
```
Which is more or less the same thing as what is reported as an issue ...

**Comment by FroMage** [comment]
Watch out that this code doesn't check the return type at all. Try:

```java
  @GET
    @Path("/search/{name}")
    public List<PersonName> searchPersons(@PathParam("name") String name) {
        List<PersonName> ret = personRepository.find("lastname", name).project(PersonName.class).list();
        PersonName p = ret.get(0); // this will throw if it's not the right type
        return ret;
    }
```

**Comment by loicmathieu** [comment]
@FroMage good catch! Generic type erasure is tricky!
If I add this line in the current test I have the exception so I can reproduce it:
```
Caused by: java.lang.ClassCastException: class io.quarkus.it.mongodb.panache.person.Person cannot be cast to class io.quarkus.it.mongodb.panache.person.PersonName (io.quarkus.it.mongodb.panache.person.Person and io.quarkus.it.mongodb.panache.person.PersonName are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @15e8f9b2)
```

I'll add something in the test.

**Comment by loicmathieu** [comment]
I added a bunch of test code to be sure that the type is the correct one.
The new test failed in master and works with this PR

**Review by FroMage — APPROVED** [review]

**Pull request merged**
