### PR TITLE
Update UBI images to 1.20/8.10

### LINKED ISSUE #41322: Upgrade `ubi8/openjdk-VERSION:1:19` -> `ubi8/openjdk-VERSION:1:20`
### Description

[ubi8/openjdk-VERSION:1:20](https://catalog.redhat.com/software/containers/ubi8/openjdk-21/653fb7e21b2ec10f7dfc10d0?architecture=amd64&image=6661ff8e8d86ed30a8ce90ae) is available.

Please upgrade e.g. https://github.com/quarkusio/quarkus/blob/3.11.3/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by Felk**
Fixes https://github.com/quarkusio/quarkus/issues/41322, I used full-text search and compared against https://github.com/quarkusio/quarkus/pull/40537

Also Updates the ubi9 version that was used in tests.

Also updates the ubi-minimal image to latest.

An open question would be: Would it also be okay to try and update to ubi9 by default? I'm not sure if there is a reason why quarkus is on ubi8 by default. Would probably be nice to update to ubi9 for the upcoming LTS

### CODE REVIEW

**Comment by cescoffier** [comment]
We do not want to update to Ubi 9 by default as it's not yet FIPS certified.

**Review by gsmet — COMMENTED** [review]
Thanks for this PR! Looks like some tests need an update!

**Comment by Felk** [comment]
Yeah, the `RedHatOpenJDKRuntimeBaseProviderTest` and `UbiMinimalBaseProviderTest` did not work the way I expected it to work. I reverted my "extension" of it, so it's a plain update now. Do you want me to rebase the commit history, or is it okay as-is? Maybe just rebase-merge

**Comment by gsmet** [comment]
Yes please squash the commits as we can’t do it easily when using merge commits. 

Thanks!

**Comment by Felk** [comment]
Done!

**Review by gsmet — APPROVED** [review]
Thanks!

**Pull request merged**
