### PR TITLE
SmallRye GraphQL 1.9.0

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Given I now build Jakarta releases based on our releases, I would need a Jakarta release even if there are no API changes so that the Jakarta releases I build are equivalent to the corresponding non-Jakarta release.

**Comment by jmartisk** [comment]
Ok that sounds like a good time to release a 2.0.0.Final, after all those RC builds. I'll do that.

**Comment by jmartisk** [comment]
Updated the jakarta version now.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Comment by phillip-kruger** [comment]
@jmartisk so federation support is in ? Maybe we can update the documentation ? Maybe do a blog ?

**Comment by jmartisk** [comment]
Yeah we should have a real-world example, perhaps it could live in its own github repo, or be added into quarkus-quickstarts

**Comment by gsmet** [comment]
Could you add a comment with a release note? I will include it in the 2.15 announcement.

**Comment by jmartisk** [comment]
Right, we don't have much content yet, so I assume something like this will have to be enough?!

> The SmallRye GraphQL extension now supports enhancing your GraphQL API with metadata needed to be able to expose it via a Apollo Federation gateway. This is achieved via annotations in the `io.smallrye.graphql.api.federation` package. See https://www.apollographql.com/docs/federation/ for general information about Federation or https://smallrye.io/smallrye-graphql/2.0.0/federation/ for an example.

**Pull request merged**
