### PR TITLE
First round of tabs in the documentation

### PR DESCRIPTION
**Pull request by gsmet**
I just started letter O but I thought we might as well get this first part in as I doubt I'll be able to add them everywhere before tomorrow evening.

### CODE REVIEW

**Comment by gsmet** [comment]
By the way, I don't really expect a review, I'll say it's probably best to push it and get some community feedback.

**Review by gastaldi — APPROVED** [review]
Merge it and let's see how it behaves :)

**Comment by gsmet** [comment]
FWIW, I implemented the tabs in the preview we have here. I haven't adjusted the Asciidoctor CSS so it's not ideal but at least you can see them in action.

**Review by geoand — APPROVED** [review]
Lovely!

**Pull request merged**
