### PR TITLE
Introduce ability to deprioritize artifacts of deployment dependencies

### LINKED ISSUE #8405: new project created with gradle, kubernetes, jib fails  for task quarkusBuild
```
mvn io.quarkus:quarkus-maven-plugin:1.3.1.Final:create \
    -DprojectGroupId=micro.apps \
    -DprojectArtifactId=greeting-quarkus \
    -DprojectVersion=0.1.0 \
    -DclassName="micro.apps.greeting.GreetingResource" \
    -Dpath="/greeting" \
    -Dextensions="kotlin, resteasy-jsonb, kubernetes, jib" \
    -DbuildTool=gradle
```

```
cd greeting-quarkus
gradle quarkusBuild
```

```
Task :quarkusBuild FAILED
building quarkus runner

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.UnsupportedOperationException
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.toFile(ZipPath.java:674)
        at io.quarkus.kubernetes.deployment.KubernetesProcessor.createProject(KubernetesProcessor.java:539)
        at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:166)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:938)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:273)
        at io.quarkus.builder.BuildContext$$Lambda$163/0000000000000000.run(Unknown Source)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #8405

### CODE REVIEW

**Comment by geoand** [comment]
@stuartwdouglas this is draft I came up with according to our discussion on #8405.

It's just a draft for now since I wanted to get your early feedback and to make sure CI passes.

**Comment by geoand** [comment]
CI passed on my Github actions

**Comment by stuartwdouglas** [comment]
I am ok with the approach. I don't massively like it but I can't really see a better approach that does not involve moving the augmentation phase to being modularised with one CL per jar.

Another option would potentially be to blacklist resources from artifacts, and add an explicit dependency on the google code.

**Comment by geoand** [comment]
> Another option would potentially be to blacklist resources from artifacts, and add an explicit dependency on the google code.

That's interesting! 
Which approach do you prefer?

**Comment by stuartwdouglas** [comment]
Maybe just stick with this one for now, we can always revisit later.

**Comment by geoand** [comment]
PR taken out of draft and proper comments added

**Comment by geoand** [comment]
PR rebased onto master

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
