### PR TITLE
Adjust for Graal 19.3.0 - with java 11

### PR DESCRIPTION
**Pull request by bobmcwhirter**

### CODE REVIEW

**Comment by gwenneg** [comment]
Hi @bobmcwhirter. I've been working on the same subject with #5358 and our PRs share a lot of identical changes (there are also some differences). How should we handle this?

**Comment by bobmcwhirter** [comment]
I’m mostly looking at jdk11. Sanne mentioned you were looking at jdk8?

I’m happy to collaborate on a branch somewhere if you like.

**Comment by gwenneg** [comment]
Yes, I'm currently focusing on JDK8 with #5358 but I was planning on making the JDK11 changes as well after that (@Sanne created #5682 for that purpose today).

**Comment by gwenneg** [comment]
It would be great if you could commit your changes to https://github.com/gwenneg/quarkus/tree/issue-4218-upgrade-graalvm-to-19.3.0

I'm not sure you have the `push` right on my fork by default though.

**Comment by gsmet** [comment]
@gwenneg AFAICS, all the changes here are in your PR, right?

We can probably close this one, then.

**Comment by gwenneg** [comment]
@gsmet Not exactly, @bobmcwhirter started working on a JDK 11 specific issue that is not part of my JDK 8 PR.

**Comment by bobmcwhirter** [comment]
I think we should indeed close this for @gwenneg's PR. You can cherry-pick (or copy/pasta) whatever you need out of this one.

**Comment by gwenneg** [comment]
The `RuntimeClassInitializationSupport` issue has been fixed in #5854 and everything else is already in #5358 so I'm closing this PR.

**Comment by gwenneg** [comment]
@gsmet I'm not sure if this PR should be marked with a specific label.

**Pull request closed without merging**
