### PR TITLE
Properly pass JVM Target options to kotlin dev-mode

### LINKED ISSUE #6817: JVM target version  miss match when kotlin DevMode
**Describe the bug**
Kotlin extension doesn't pass jvm-target when re-compile.

Example case is below.
```kotlin
interface SomeInterface {
    companion object {
        @JvmStatic
        fun staticMethod() = "static"
    }
}

@Path("/hello")
class ExampleResource {
    @GET
    fun hello() = SomeInterface.staticMethod()
}
```

**Expected behavior**
Kotlin codes are compiled specified version.
Can use new features depends specified version.

**Actual behavior**
Kotlin codes are compiled JVM 1.6.
Compiler rises RuntimeException.

**To Reproduce**
1. create java 1.8 project and define example classes.
2. mvn compile quarkus:dev
3. curl localhost:8080/hello
4. change string.
5. curl localhost:8080/hello

**Configuration**
nothing

**Screenshots**
nothing

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin PC-XXX.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "12.0.2" 2019-07-16 Java(TM) SE Runtime Environment (build 12.0.2+10) Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
 - GraalVM version (if different from Java): openjdk version "11.0.6" 2020-01-14 OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07) OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
 - Quarkus version or git rev: 1.2.0.CR1

**Additional context**
To solve it, add `compilerArguments.setJvmTarget(context.getTargetJvmVersion());` here I think.
https://github.com/quarkusio/quarkus/blob/8e06dad026794c31e49040950b9cf63947ebd284/extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinCompilationProvider.java#L39

### PR DESCRIPTION
**Pull request by kuzuha**
Fixes: #6817

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Makes sense to me. @geoand WDYT?

**Comment by geoand** [comment]
Thanks for the contribution!

I want to give this a spin first as I am not absolutely sure that the value has been set. I'll most likely do that later on today

**Review by geoand — APPROVED** [review]
Looks good, thanks!

**Comment by geoand** [comment]
Can you please rebase the PR onto master?

**Comment by kuzuha** [comment]
@geoand Sure, I did.

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
