### PR TITLE
[3.8] Bump kafka3.version from 3.6.1 to 3.7.0

### PR DESCRIPTION
**Pull request by ozangunalp**
Kafka Streams register DslStoreSuppliers for reflective access in native

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
This is for the next LTS (3.8.x) releases.

**Comment by cescoffier** [comment]
@ozangunalp the messaging CI failure looks related

**Review by cescoffier — COMMENTED** [review]
Waiting for CI

**Review by cescoffier — APPROVED** [review]

**Comment by rsvoboda** [comment]
Is this related to the bump of Kafka on AMQ Streams side? 
(https://access.redhat.com/announcements/7051859 - Streams for Apache Kafka 2.7 uses Kafka 3.7.0.)

**Comment by cescoffier** [comment]
@gsmet @rsvoboda Yes, please include this one (Kafka 3.7.0) in Quarkus 3.8.x. 

Do not update to Kafka 3.8.0.

**Pull request merged**
