### PR TITLE
Remove runtime dependency on ASM

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by gsmet** [comment]
Unfortunately, it fails in native:
```
Error: can not find io.smallrye.config.ConfigMappingInterface.getConfigurationInterface, io.smallrye.config.ConfigMappingInterface can not be loaded, due to org/objectweb/asm/ClassVisitor not being available in the classpath. Are you missing a dependency in your classpath?
com.oracle.svm.core.util.UserError$UserException: can not find io.smallrye.config.ConfigMappingInterface.getConfigurationInterface, io.smallrye.config.ConfigMappingInterface can not be loaded, due to org/objectweb/asm/ClassVisitor not being available in the classpath. Are you missing a dependency in your classpath?
```

**Comment by radcortez** [comment]
I'll have a look.

**Comment by stuartwdouglas** [comment]
We probably need some substitutions to clean out this code path in native. ASM is definitely not useful in native, we don't want to include it.

**Comment by radcortez** [comment]
In https://github.com/quarkusio/quarkus/issues/12960 we did remove the ASM classes from the final native.

I guess the native build tries to load the original `io.smallrye.config.ConfigMappingInterface` class in https://github.com/quarkusio/quarkus/blob/6f97b00a75e12ace7e3e21363c14bee917ea5b69/core/runtime/src/main/java/io/quarkus/runtime/configuration/Substitutions.java#L75-L96. I'll probably need to extract the asm generation piece from there. 

@stuartwdouglas is this impacting something right now? Can it wait for SR Config 2.0 and the MP 4.0 work?

**Comment by stuartwdouglas** [comment]
It was discovered because this broke JBang integration, as JBang ended up resolving the old version of ASM used by smallrye-config. I have worked around that but this still should not be in the runtime part of Quarkus core.

**Comment by radcortez** [comment]
Ok, let me change this on SR Config side.

**Comment by radcortez** [comment]
https://github.com/smallrye/smallrye-config/pull/452 should prevent GraalVM to load the ASM classes in the substitution, so we should be able to remove the dependency.

In my box seems to work. Trying a full build in my fork: https://github.com/radcortez/quarkus/actions/runs/391622287.

Anyway, we need a SR Config release. I've also updated the ASM version there to align with Quarkus.

**Comment by radcortez** [comment]
Ok, this one looks promising: https://github.com/radcortez/quarkus/actions/runs/391887929. Do you want me to push a SR Config release and update Quarkus?

**Comment by stuartwdouglas** [comment]
Sounds good to me.

**Comment by radcortez** [comment]
@gsmet to target Quarkus 1.11? Is it ok if I do a major release of SR Config with some extra things?

**Comment by gsmet** [comment]
@radcortez sure.

**Pull request closed without merging**
