### PR TITLE
Deprecated PR - Feature/OTEL JAX-RS Span Code function

### PR DESCRIPTION
**Pull request by arik-dig**
Add the [standard attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#source-code-attributes) `code.function` and `code.namespace` to [Local Root Span](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/LocalRootSpan.java) based  on JAX-RS endpoint annotations (GET, POST, etc).

this PR is proposed based on [this extension discussion](https://github.com/quarkusio/quarkus/issues/29864#issuecomment-1352608138)

### CODE REVIEW

**Comment by arik-dig** [comment]
@radcortez , @brunobat can you please review it?

**Comment by geoand** [comment]
Thanks for this.

One thing to keep in mind is that we'll need the commits squashed and the PR _rebased_ onto main.

**Review by gsmet — CHANGES_REQUESTED** [review]
Just a note that this PR will require a cleanup/squash before merging.

**Comment by arik-dig** [comment]
> Just a note that this PR will require a cleanup/squash before merging.

@gsmet what kind of cleanup?

**Review by radcortez — CHANGES_REQUESTED** [review]
The issue with the interceptor approach is that it does not work when the annotations are on a parent class. Look into https://github.com/quarkusio/quarkus/issues/22530.

My recommendation is to use `javax.ws.rs.container.ResourceInfo`, which already provides the class and method of the invoked REST endpoint. Also, have a look into `io.opentelemetry.instrumentation.api.instrumenter.code.CodeAttributesExtractor`.

**Comment by arik-dig** [comment]
@radcortez regarding CodeAttributesExtractor I would have used it, but the method `getServerInstrumenter` in class `HttpInstrumenterVertxTracer` returns `Instrumenter<HttpRequest, HttpResponse>` meaning that `HttpRequest` does not contain reference to method and/or class. any ideas about it?

**Comment by arik-dig** [comment]
@radcortez reg using annotations with inheritance, the proposed JAX-RS interceptor is on Method level (of GET, POST), and not on class.
I added tests and I see no problems with it.

**Comment by arik-dig** [comment]
@radcortez when you mention `javax.ws.rs.container.ResourceInfo` how do you suggest to use it?
can you please explain?
thanks

**Comment by arik-dig** [comment]
@radcortez BTW, there's already existing JAX-RS interceptor which traps the same method annotations as I proposed in this PR.
```
List<DotName> JAXRS_METHOD_ANNOTATIONS = List.of(GET, POST, HEAD, DELETE, PUT, PATCH, OPTIONS);
```
see classes `io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor`, `io.quarkus.resteasy.deployment.RestPathAnnotationProcessor`

**Comment by radcortez** [comment]
You can @Inject the `ResourceInfo` in a Filter and retrieve the className and methodName from the API. You can then store these values in the Vert.x context or the HTTP request context and use them in the `HttpInstrumenterVertxTracer`.

**Comment by arik-dig** [comment]
> You can @Inject the `ResourceInfo` in a Filter and retrieve the className and methodName from the API. You can then store these values in the Vert.x context or the HTTP request context and use them in the `HttpInstrumenterVertxTracer`.

@radcortez I will try do it in a clean new PR

**Pull request closed without merging**
