### PR TITLE
Enable proxy configuration for OpenTelemetry exporters

### LINKED ISSUE #39519: OpenTelemetry - respect proxy settings in VertxGrpcExporter and VertxHttpExporter
### Description

Starting from quarkus version `3.3.x` the spans are exported using Vert.x based exporters. It is not possible to set Proxy on the Vert.x Http client used by these exporters (analog to `quarkus.rest-client.my-client.proxy-address`). 

Expected: Via `quarkus.otel.exporter.otlp.traces.proxy-address` it should be possible to configure a proxy server to be used to communicate with external server.

### Implementation ideas

1. Extend `OtlpExporterTracesConfig` with `proxyAddress` property.
2. Extend `io.quarkus.opentelemetry.runtime.exporter.otlp.OTelExporterRecorder.HttpClientOptionsConsumer#HttpClientOptionsConsumer` with `proxyAddress` and add private method `configureProxy`

With the above proposed small changes, it will be possible to use these exporters behind a proxy

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #39519

### CODE REVIEW

**Comment by geoand** [comment]
Although this is technically a new feature, due to the following:

* there is a high chance it's needed in enterprise systems
* there is a very very low probability it will break something

I propose backporting it to 3.8 as well.

**Review by brunobat — CHANGES_REQUESTED** [review]
Please hold any merge until OTel Metrics is done.

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
Actually, waiting could be a problem for backporting...

**Comment by gsmet** [comment]
One option could be to push this to 3.9 and 3.8 and wait for @brunobat to finish his stuff before merging in main.

**Comment by geoand** [comment]
Yeah, I'll wait yo see what Bruno thinks

**Review by brunobat — APPROVED** [review]
Let's merge this because the backport is important. 
I'll deal with the code changes on my branch.

**Comment by geoand** [comment]
Thanks 🙏

**Pull request merged**
