### PR TITLE
vert.x and reactive messaging hot reload test

### PR DESCRIPTION
**Pull request by cescoffier**
Add hot-reload tests to the Vert.x HTTP extension and Reactive Messaging extension.

### CODE REVIEW

**Comment by geoand** [comment]
@cescoffier I'm confused, how come these now work? I don't see any fixes :)

**Comment by cescoffier** [comment]
@geoand that's the beauty of reactive, it works... asynchronously :-D

**Comment by geoand** [comment]
So it was just a matter of adding the dependencies?

**Review by geoand — APPROVED** [review]
:+1:

**Comment by gsmet** [comment]
@cescoffier looks like a good candidate for 1.1.0 but CI looks broken. Could you rebase and push?

**Comment by cescoffier** [comment]
Just rebased it.

**Comment by gsmet** [comment]
@cescoffier the CI reports an issue in Vert.x tests now so I wonder if it's a legit one?

**Comment by gsmet** [comment]
@cescoffier what should we do with this PR?

**Comment by cescoffier** [comment]
Good question! Forgot that one. I will have a look.

**Comment by cescoffier** [comment]
@gsmet I've rebased and checked. The tests still make sense.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
