### PR TITLE
Dev UI: Add strictRendering=false to Qute engine

### LINKED ISSUE #18413: Accessing DevConsole fails with InternalServerError in the current snapshot
## Describe the bug
Starting the quickstarts (I've tried `security-openid-connect-quickstart` followed by `getting-started`) with `mvn quarkus:dev` and then accessing the console from the browser at `localhost:8080/q/dev` fails with:

```
io.quarkus.qute.TemplateException: Property "currentExtensionName" not found in expression {currentExtensionName} in template main on line 25
	at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:207)
        ...
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:90)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.renderTemplate(DevConsole.java:134)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.sendMainPage(DevConsole.java:178)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:97)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:34)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:12)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
	...
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:195)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:192)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:49)
	at io.vertx.core.impl.EventLoopContext.lambda$emit$1(EventLoopContext.java:56)
```

CC @stuartwdouglas @phillip-kruger

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #18413

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
@phillip-kruger Thanks for a quick fix :-), LGTM, though indeed lets wait for more approvals before merging

**Comment by gastaldi** [comment]
I think that's okay for the DevConsole, but I'll let @mkouba have the final say here 😉

**Review by gsmet — DISMISSED** [review]
I'm not sure it's the right fix. Why is the property not defined? I would rather fix the issue with this property rather than changing this globally (and thus miss potential errors).

**Comment by phillip-kruger** [comment]
The default has changed (see https://github.com/quarkusio/quarkus/pull/18227) but I can investigate some more.

**Comment by sberyozkin** [comment]
@gsmet This fix only affects the dev console templates, it is not doing it globally - the user templates are not affected

**Comment by stuartwdouglas** [comment]
@mkouba was the intention of this to completely ban null values? We do:

```
                TemplateInstance devTemplateInstance = devTemplate
                        .data("currentExtensionName", extName)
                        .data("flash", FlashScopeUtil.getFlash(ctx))
                        .data("currentRequest", ctx.request());
```

where extName may be null, but there is now no way to check for a null value in the template.

**Comment by phillip-kruger** [comment]
Some more info: I am not sure if what case that var is null. In my basic tests there is always a value. 
We use it when we build the page to create the title and the heading. In the template we check it like this:

`{#if currentExtensionName}`

So if it would be null, the title will be a default value.

**Comment by geoand** [comment]
If `null` can't be used, then what should be used and can be checked for in the templates?

**Comment by stuartwdouglas** [comment]
I think we should merge this for now, as it is better than the current state of affairs, however I do have reservations about making strict rendering the default, as it makes working with null values almost impossible.

I have pushed a smoke test to this PR so we don't accidentally break the main page again, when it passes we should merge it.

**Comment by mkouba** [comment]
> @mkouba was the intention of this to completely ban null values?

Not at all. `null` is a valid value that should be treated as `falsy` in the `{#if}` section. Strict rendering is about throwing an exception if _no value is found_, i.e. if the engine was not able to evaluate the expression correctly. Previously, we did throw an exception for "standalone" expressions, e.g. `{foo.bar}`. strictRendering=false means that we extend this behavior to any expression used, including section params such as `{#if foo.bar}`.

I need to check the original error though. It might be that we have some bug in there. In general, if a map has a `key=null` pair then `{#if map.key}nok{#else}null{/if}` should render `null`.

**Comment by mkouba** [comment]
> I'm not sure it's the right fix. Why is the property not defined? I would rather fix the issue with this property rather than changing this globally (and thus miss potential errors).

@gsmet I'm going to create a separate issue to verify all DEV UI templates and switch to strict rendering eventually. For now it's probably safer to disable it globally.

**Comment by gsmet** [comment]
OK yeah, let's fix the issues first and reconsider later.

But what I would like is to enable it at some point and ALSO to have simple tests for Dev UI just checking that the pages of every extension don't return a 500. That should be relatively easy and allow to catch at least some errors with a small investment.

**Comment by sberyozkin** [comment]
@gsmet, So can your change request be dismissed at this stage ?

**Review by gsmet — APPROVED** [review]

**Pull request merged**
