### PR TITLE
Use GizmoAdaptor where possible

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Review by geoand — APPROVED** [review]
Wasn't aware of this one, nice!

There are definitely more occurences of this in the code that I guess we'll track down little by little

**Comment by stuartwdouglas** [comment]
I don't think so, I just looked at all implementers in my IDE and removed the duplicated classes.

**Comment by geoand** [comment]
One occurence is this: https://github.com/quarkusio/quarkus/blob/master/extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/SpringWebProcessor.java#L340

I guess all the other occurences use `GeneratedBeanBuildItem` like this: https://github.com/quarkusio/quarkus/blob/master/extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/SpringDataJPAProcessor.java#L101

**Comment by stuartwdouglas** [comment]
For some reason I don't understand Intellij has been randomly marking maven modules as ignored for me, which is why I did not pick this one up. 

We should also create a version of this for GeneratedBeanBuildItem.

**Comment by geoand** [comment]
> For some reason I don't understand Intellij has been randomly marking maven modules as ignored for me, which is why I did not pick this one up.
> 

I have seen the same exact problem every now and then. 

> We should also create a version of this for GeneratedBeanBuildItem.

Makes sense. I'll do that later if no one beats me to it.

**Pull request merged**
