### PR TITLE
Handle duplicated Vert.x context in CaffeineCacheImpl

### LINKED ISSUE #39515: Programmatic Cache API does not preserve Vertx Duplicate Context
### Describe the bug

We noticed that using the programmatic cache API via `cache.getAsync()` leads to the Vertx duplicate context being lost. This can lead to undesired behavior, especially when relying on Hibernate Reactive which stores its session in the context. In our application, we frequently saw the exception `java.lang.IllegalStateException: Illegal pop() with non-matching JdbcValuesSourceProcessingState`, but of course this will depend on the specific application.

### Expected behavior

The context should be preserved.

### Actual behavior

The context is lost, leading to problems for applications or modules that rely on the context, e.g. Hibernate Reactive.

### How to Reproduce?

https://github.com/markusdlugi/cache-context-reproducer/tree/master

1. Run the `ReproducerTest` and observe that the test fails
2. Remove comment in line 68 in `GreetingResource` and observe that the test now passes

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS

### Quarkus version or git rev

3.8.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

A similar bug has already been reported and fixed for the annotation-based cache (#37078), so most likely the same treatment is necessary for the programmatic API.

### LINKED ISSUE #41081: `ContextNotActiveException` in `SecurityIdentityAugmentor` since Quarkus 3.10
### Describe the bug

Since Quarkus 3.10 we get a `ContextNotActiveException` in our own `SecurityIdentityAugmentor`.

```
2024-06-01 15:59:51,328 ERROR [com.example.fre.ser.ExceptionMappers] (vert.x-eventloop-thread-3) Es ist ein unbehandelter Fehler aufgetreten.: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.vertx.http.runtime.CurrentVertxRequest, id=0_6n6EmChCiiDdd8HelptG_A0AE]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
	at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:30)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.setCurrent(Unknown Source)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusCurrentRequest.set(QuarkusCurrentRequest.java:33)
	at org.jboss.resteasy.reactive.server.core.CurrentRequestManager.set(CurrentRequestManager.java:12)
	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.handleRequestScopeActivation(ResteasyReactiveRequestContext.java:654)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.handleRequestScopeActivation(QuarkusResteasyReactiveRequestContext.java:39)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.requireCDIRequestScope(AbstractResteasyReactiveContext.java:264)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:27)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:78)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:75)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

We have not yet been able to create a reproducer, but we hope that a Quarkus expert can help with the following sample code. We were able to narrow down the problem, the exception always occurs when the cache is updated. 

```kotlin
import com.github.benmanes.caffeine.cache.Caffeine
import com.github.benmanes.caffeine.cache.LoadingCache
import io.quarkus.oidc.client.filter.OidcClientFilter
import io.quarkus.security.identity.AuthenticationRequestContext
import io.quarkus.security.identity.SecurityIdentity
import io.quarkus.security.identity.SecurityIdentityAugmentor
import io.quarkus.security.runtime.QuarkusSecurityIdentity
import io.smallrye.jwt.auth.principal.JWTCallerPrincipal
import io.smallrye.mutiny.Uni
import jakarta.enterprise.context.ApplicationScoped
import jakarta.inject.Inject
import jakarta.ws.rs.GET
import jakarta.ws.rs.Path
import jakarta.ws.rs.PathParam
import jakarta.ws.rs.Produces
import jakarta.ws.rs.core.MediaType
import org.eclipse.microprofile.jwt.Claims
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient
import org.eclipse.microprofile.rest.client.inject.RestClient
import java.time.Duration

data class ExampleRolesResponse(val roles: List<String>)

@RegisterRestClient
@OidcClientFilter
@ApplicationScoped
interface ExampleRestClient {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("auth/{email}")
    fun getRoles(@PathParam("email") email: String): Uni<ExampleRolesResponse>
}

@ApplicationScoped
class ExampleAuthorizationProvider @Inject constructor(
    @RestClient private val client: ExampleRestClient,
) {

    private val cache: LoadingCache<String, Uni<ExampleRolesResponse>> = Caffeine.newBuilder()
        .expireAfterWrite(Duration.ofMinutes(1L))
        .build { email -> client.getRoles(email).memoize().indefinitely() } // the exception is thrown here

    fun getRoles(email: String): Uni<ExampleRolesResponse> {
        return cache.get(email)
    }
}

@ApplicationScoped
class ExampleSecurityIdentityAugmentor @Inject constructor(
    private val authProvider: ExampleAuthorizationProvider,
) : SecurityIdentityAugmentor {

    override fun augment(identity: SecurityIdentity, context: AuthenticationRequestContext): Uni<SecurityIdentity> {
        val email = identity.email()
        if (identity.isAnonymous || email == null) {
            return Uni.createFrom().item(identity)
        }

        return authProvider.getRoles(email)
            .map { response -> identity.createFrom(response) }
    }

    private fun SecurityIdentity.email(): String? {
        return (principal as? JWTCallerPrincipal)
            ?.getClaim<String>(Claims.email)
            ?.lowercase()
    }

    private fun SecurityIdentity.createFrom(response: ExampleRolesResponse): SecurityIdentity {
        val newAttributes = this.attributes + ("example.response" to response)
        
        return QuarkusSecurityIdentity.builder()
            .addAttributes(newAttributes)
            .addCredentials(this.credentials)
            .addRoles(response.roles.toSet())
            .addPermissionChecker { permission -> this.checkPermission(permission) } // sustain previous permission checks
            .setPrincipal(this.principal)
            .setAnonymous(this.isAnonymous)
            .build()
    }

    override fun priority(): Int = 1000
}
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gwenneg**
- Fixes #39515.
- Fixes #41081.

### CODE REVIEW

**Comment by gwenneg** [comment]
I was able to reproduce locally the issues from #39515 and #41081 with the reproducers provided by the Quarkus users. Then, I confirmed that this PR fixes both issues.

The Vert.x context is untested in quarkus-cache though. I'm trying to determine if that can be tested somehow.

**Review by geoand — APPROVED** [review]

**Comment by gwenneg** [comment]
@geoand I'm out of time for today but I'll try to add the test later with a separate PR. Until then, I think this PR can be merged. WDYT?

**Comment by geoand** [comment]
Yeah, I agree. 

Let's also get a +1 from @cescoffier

**Comment by geoand** [comment]
Hm... I'm wondering if this change would affect Infinispan and Redis cache implementations...

**Comment by gwenneg** [comment]
The Infinispan impl depends on a separate [https://github.com/quarkusio/quarkus/blob/main/extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/runtime/cache/CacheResultInterceptor.java](CacheResultInterceptor) and does not depend on `CaffeineCacheImpl` so I think we're safe here.

I'm not sure about the Redis impl.

**Comment by geoand** [comment]
> The Infinispan impl depends on a separate [CacheResultInterceptor](https://github.com/quarkusio/quarkus/blob/main/extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/runtime/cache/CacheResultInterceptor.java) and does not depend on `CaffeineCacheImpl` so I think we're safe here. I'm still checking why the test failed...
> 

I think this is only the case for ` io.quarkus.infinispan.client.CacheResult`

> I'm not sure about the Redis impl.

cc @cescoffier

**Comment by gwenneg** [comment]
The test from `quarkus-infinispan-cache` that failed depends on the annotation and interceptor from `quarkus-cache` while both a variation of the annotation and interceptor exist in `quarkus-infinispan-client`. I'm a bit confused about how things are organized in the Infinispan impl today. I've been away from too long 😅

**Comment by karesti** [comment]
> The test from `quarkus-infinispan-cache` that failed depends on the annotation and interceptor from `quarkus-cache` while a variation of both the annotation and the interceptor exist in `quarkus-infinispan-client`. I'm a bit confused about how things are organized in the Infinispan impl today. I've been away from too long 😅

Custom annotations are deprecated in the infinispan client extension, they were introduced before the SPI existed. The infinispan cache extension is now fully providing the replacement of caffeine by infinispan with the new extension

**Comment by karesti** [comment]
@geoand @gwenneg @cescoffier I don't know if we need a fix on the deprecated annotations, since the new extension provides the fix

**Comment by karesti** [comment]
> The test from `quarkus-infinispan-cache` that failed depends on the annotation and interceptor from `quarkus-cache` while a variation of both the annotation and the interceptor exist in `quarkus-infinispan-client`. I'm a bit confused about how things are organized in the Infinispan impl today. I've been away from too long 😅

https://quarkus.io/guides/cache-infinispan-reference

**Comment by geoand** [comment]
I don't think the old annotations need a fix, but we do need to make sure that @gwenneg fix doesn't break Infinispan with the regular cache annotations (my guess is that it might, as I don't see the context juggling that was moved to Caffeine)

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
It needs a proper tests but I think the Redis cache is going to propagate the requester duplicated context, and the callback from Redis is going to preserve the duplicated context.

**Comment by karesti** [comment]
@geoand how should I be testing this to make sure, beyond the already existing tests

**Comment by geoand** [comment]
Take a look at the issues this PR closes.
You would likely be able to reproduce the same problems with the infinispan cache backend.
My assumption is that this PR will not make things any better for Infinispan, if anything it should make it worse

**Comment by karesti** [comment]
@geoand do you think I should move the change to the cache impl ? I can have a closer look tomorrow

**Comment by geoand** [comment]
I think the infinispan cache implementation will need a similar change to this one

**Comment by karesti** [comment]
@gwenneg I opened a PR here https://github.com/gwenneg/quarkus/pull/298/files

**Comment by geoand** [comment]
@gwenneg could you please merge Katia's PR into your branch so this PR can be updated?

Thanks

**Comment by gwenneg** [comment]
Sure, done!

**Comment by geoand** [comment]
Thanks a lot!

**Review by geoand — APPROVED** [review]

**Comment by rsvoboda** [comment]
Hi @gwenneg. Did you have chance to look adding the test later with a separate PR as noted in https://github.com/quarkusio/quarkus/pull/41647#issuecomment-2205412894?

**Comment by gwenneg** [comment]
Hey @rsvoboda. No, not yet. I'm currently on PTO so that will have to wait a bit.

**Pull request merged**
