### PR TITLE
Allow accessing build time config POJOs from a CodeGenProvider

### LINKED ISSUE #35962: Allow accessing build time config POJOs from a CodeGenProvider
### Description

Currently `CodeGenProvider.trigger()` gives an access to a org.eclipse.microprofile.config.Config instance, but there is no (correct me if I am wrong) way to get my config POJO with all defaults set.

### Implementation ideas

I think I found a way how to do this. A PR will follow.

### PR DESCRIPTION
**Pull request by ppalaga**
fix #35962

### CODE REVIEW

**Comment by ppalaga** [comment]
The failures in the Gradle tests are related to this change. When looking into first failure in `QuarkusCodestartBuildIT#testGradle` I see the following in the output of the Gradle build (for `java`):

```
...
Caused by: org.gradle.api.GradleException: Failed to generate sources in the QuarkusPrepare task for org.test:test-codestart:1.0.0-codestart due to java.lang.reflect.InvocationTargetException
        at io.quarkus.gradle.tasks.worker.CodeGenWorker.execute(CodeGenWorker.java:89)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:54)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:48)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:48)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:96)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:65)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.lambda$run$0(WorkerAction.java:135)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:127)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.quarkus.gradle.tasks.worker.CodeGenWorker.execute(CodeGenWorker.java:66)
        ... 24 more
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.Converter: io.quarkus.runtime.configuration.InetSocketAddressConverter not a subtype
        at io.smallrye.config.SmallRyeConfigBuilder.discoverConverters(SmallRyeConfigBuilder.java:136)
        at io.smallrye.config.SmallRyeConfig.buildConverters(SmallRyeConfig.java:77)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:69)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:646)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConfigForRuntimeDefaults(BuildTimeConfigurationReader.java:1067)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:514)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:415)
        at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:415)
        at io.quarkus.deployment.CodeGenerator.lambda$getConfig$5(CodeGenerator.java:281)
        at io.quarkus.deployment.CodeGenerator.readConfig(CodeGenerator.java:345)
        at io.quarkus.deployment.CodeGenerator.getConfig(CodeGenerator.java:277)
        at io.quarkus.deployment.CodeGenerator.initAndRun(CodeGenerator.java:78)
        ... 28 more
```

Apparently it is triggered by my change in `io.quarkus.deployment.CodeGenerator.getConfig(ApplicationModel, LaunchMode, Properties, QuarkusClassLoader)`. The message `java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.Converter: io.quarkus.runtime.configuration.InetSocketAddressConverter not a subtype` sounds after some classloading issue. `InetSocketAddressConverter` is perhaps loaded using wrong class loader? 

@aloubyansky could you please help or at least point me where to look?

**Comment by ppalaga** [comment]
63118fe716be4d52d296965222a6bc2b7eaf97ec : rebased

**Comment by ppalaga** [comment]
@aloubyansky could you please help or at least point me where to look for fixing the Gradle failures?

**Comment by aloubyansky** [comment]
It looks like the caller isn't setting the deployment classloader as TCCL. You can try adding
```
        Thread.currentThread().setContextClassLoader(deploymentClassLoader);
```
right before the function is applied.

**Comment by ppalaga** [comment]
> ```
> config.unwrap(SmallRyeConfig.class).getConfigMapping(ConfigTrackingConfig.class)
> ```

Thanks for the tip! Let me try.

**Comment by gsmet** [comment]
What's the status of this one? Is this still needed?

**Comment by ppalaga** [comment]
Ups, sorry for not closing earlier. @aloubyansky's hits have helped to solve the issue on QCXF side.

**Comment by camproto** [comment]
We solved it manually without a secret handler. Thanks for your support!

**Pull request closed without merging**
