### PR TITLE
Fix syntax highlighting for all code examples in guides

### LINKED ISSUE #12733: Some documentation examples are not correctly highlighted
Some code examples (like for example the Java code starting here: https://github.com/quarkusio/quarkus/blame/master/docs/src/main/asciidoc/security-jwt.adoc#L670) either lack the property declaring source type. As a result the rendered HTML guide doesn't have proper syntax highlighting, which is unfortunate.

### PR DESCRIPTION
**Pull request by knutwannheden**
Fixes #12733

### CODE REVIEW

**Comment by sberyozkin** [comment]
LGTM, Guillaume, @gsmet please review

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
LGTM but it needs to be rebased and squashed into a single commit

**Comment by knutwannheden** [comment]
> LGTM but it needs to be rebased and squashed into a single commit

Done. Sorry about the big commit!

**Comment by gastaldi** [comment]
Thank you!

**Comment by gsmet** [comment]
Too impractical to backport.

**Pull request merged**
