### PR TITLE
Include classes touched by parent for testing

### LINKED ISSUE #27821: Parameterized test contexts do not see transformed test classes (classloader/ordering issues in tests)
### Describe the bug

I think something is not right in classloading for test classes. If an extension transforms a test class, what gets executed is the transformed class (as you'd expect) - *except* that if the test is parameterised or uses a TestTemplate, the template gets passed a context which has the *untransformed* class. 

For example, in this test, `MyContextProvider` gets handed a context which has the test class in it, loaded by the `QuarkusClassLoader`, but un-transformed. 

```
    @TestTemplate
    @ExtendWith(MyContextProvider.class)
    void verificationTestTemplate(ExtensionContext context) {
        ClassLoader loader = this.getClass().getClassLoader();
        Annotation[] contextAnnotations = context.getRequiredTestClass().getAnnotations();
        Annotation[] myAnnotations = this.getClass().getAnnotations();

        Assertions.assertEquals(myAnnotations.length, contextAnnotations.length, "The test template sees a different version of the class than the test execution" + Arrays.toString(myAnnotations) + " vs " + Arrays.toString(contextAnnotations));
    }
```

### Expected behavior

I would expect the view of the test class would be consistent across the whole test execution, including in the `ExtensionContext`. 

### Actual behavior

The test above fails; the ExtensionContext has a version of the class which does not have transformations on it. 

### How to Reproduce?

Reproducer: https://github.com/holly-cummins/parameterized-test-reproducer/blob/main/README.md

What’s the reproducer doing? An extension defines some byte code transformations which apply to a test class.

The test uses a Junit 5 @TestTemplate for tests. At runtime, the version of the test that runs is the version which was transformed by the extension. However, the ContextProvider for the test template is initialised with the non-transformed version of the test class (this is the problem).

Note that QuarkusDevModeTest may not seem to be enough to show this issue, it may need a proper integration testing running in dev mode. (I had another issue which definitely did not show up in the QuarkusDevModeTest but did with mvn Quarkus:dev.)

```
2022-09-08 21:59:10,425 INFO  [io.qua.test] (Test runner thread) Running 1/0. Running: sample.house.ParameterizedTest#verificationTestTemplate(ExtensionContext)
Test class is class sample.house.ParameterizedTest
Test class annotations is [@io.quarkus.test.junit.QuarkusTest()]
Test class classloader is QuarkusClassLoader:Deployment Class Loader: TEST@7881b3d8
2022-09-08 21:59:10,428 INFO  [io.qua.test] (Test runner thread) Running 1/0. Running: sample.house.ParameterizedTest#[@io.quarkus.test.junit.QuarkusTest()]
This tests's loader is QuarkusClassLoader:Quarkus Runtime ClassLoader: TEST restart no:1@576a1438
This tests's annotations is [@quarkus.io.pact.runtime.AnnotationAddedByExtension(), @io.quarkus.test.junit.QuarkusTest()]
```

To see the failure,
```
rm -rf integration-tests/src/test/resources-filtered/projects/bff/target && mvn clean  install verify  -DskipTests=false -DskipITs=false
```
To play with the failing test in more detail,
```
cd integration-tests/src/test/resources-filtered/projects/bff
mvn quarkus:dev
```

`mvn verify` also fails.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

    <quarkus.version>2.12.0.Final</quarkus.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stuartwdouglas**
When deciding if a test should be re-run we should also re-run the test if class level methods touched the changed class.

### CODE REVIEW

**Comment by holly-cummins** [comment]
I'm excited about this fix, but from the description, I'm not sure if it fixes https://github.com/quarkusio/quarkus/issues/27821. I feel like #27821 might need deeper changes to how we tell JUnit about our test's classloader; however, I think this change should fix an issue where changing a test template class doesn't trigger a test re-run, which would be great.

**Comment by stuartwdouglas** [comment]
@holly-cummins I changed the description, should be good to go.

**Comment by stuartwdouglas** [comment]
@holly-cummins any chance you could give this one a review?

**Review by holly-cummins — APPROVED** [review]

**Comment by holly-cummins** [comment]
Thanks for the nudge, @stuartwdouglas - LGTM!

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merging as @holly-cummins approved it.

**Pull request merged**
