### PR TITLE
Use URLConnection to read jar content

### PR DESCRIPTION
**Pull request by Postremus**
According to the comment, originally this method was introduced since the inputstream created by openConnection() was not closed.
Closing the IS was not working, because caching prevents the close. The check for caching is done in sun.net.www.protocol.jar.JarURLConnection.JarURLInputStream.

Saves about 60ms of devmode startup time, by again reducing the number of opened FileSystems.

Related to #21552

Draft, because:
* Waiting for https://github.com/quarkusio/quarkus-fs-util/pull/5

### CODE REVIEW

**Comment by aloubyansky** [comment]
It was locking JARs on Windows. Do you have access to a Windows machine to verify it's not locking them any more? If not, I'll try to get a hold of one and test it one of these days.

**Comment by Postremus** [comment]
My main machine right now is windows. :)

I tested this change in 3 ways:
* mvn quarkus:dev - devmode still starts
* debugged sun.net.www.protocol.jar.JarURLConnection.JarURLInputStream and verified that the stream is still closed
* This CI run. Only the gradle tests fail, because of https://github.com/quarkusio/quarkus-fs-util/pull/5
https://github.com/Postremus/quarkus/actions/runs/1579925042

**Comment by Postremus** [comment]
Anything more that I should check?

**Comment by aloubyansky** [comment]
Great. Could you check that the JARs aren't locked after you terminate dev mode and/or after packaging? e.g. you can move the jars.

**Comment by Postremus** [comment]
@aloubyansky 
Moving the jar works.

I tested it with following program:
```
    public static void main(String[] args) throws IOException {
        URL url = new URL("jar:file:/C:/Users/Martin/.m2/repository/io/quarkus/quarkus-resteasy-reactive/999-SNAPSHOT/quarkus-resteasy-reactive-999-SNAPSHOT.jar!/META-INF/quarkus-config-roots.list");
        URLConnection urlConnection = url.openConnection();
        urlConnection.setUseCaches(false);
        try (InputStream is = urlConnection.getInputStream()) {
            System.out.println(new String(is.readAllBytes(), StandardCharsets.UTF_8));
        }
        System.out.println("Finish");
    }
```

I set my breakpoint at the last sysout, and launched a debugger.
With `setUseCaches(false)`, I can move the jar.
With `setUseCaches(true)`, I can't.

**Comment by aloubyansky** [comment]
Very good @Postremus Thanks for checking!

**Comment by gsmet** [comment]
Hmmm. The Gradle tests both failed. It looks a bit suspicious.

**Comment by Postremus** [comment]
@gsmet yep, the quarkus-fs-util changes need to be merged and released first.

**Comment by gsmet** [comment]
@Postremus released (you'll have to wait for the sync). Can you adjust your PR to include the upgrade of quarkus-fs-util, ideally as the first commit of the PR? Thanks!

**Comment by Postremus** [comment]
@gsmet Thank you for the release!

I bumped quarkus-fs-util to 0.0.4. Lets see what CI says.

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
