### PR TITLE
Provided ManagedExecutor and ThreadContext beans should be default so that users can override them easily

### LINKED ISSUE #6148: Creation of custom MP Context Propagation objects fails
**Describe the bug**
When defining a producer for an own `ManagedExecutor`, or `ThreadContext`, the creation fails with a deployment exception:

The following describes the error for `ManagedExecutor`, the same is true for other MicroProfile Context Propagation types.

```
[1] Ambiguous dependencies for type org.eclipse.microprofile.context.ManagedExecutor and qualifiers [@Default]
	- java member: com.sebastian_daschner.coffee.mp_cp.BulkheadExampleResource#readExecutor
	- declared on CLASS bean [types=[com.sebastian_daschner.coffee.mp_cp.BulkheadExampleResource], qualifiers=[@Default, @Any], target=com.sebastian_daschner.coffee.mp_cp.BulkheadExampleResource]
	- available beans:
		- PRODUCER METHOD bean [types=[java.util.concurrent.Executor, org.eclipse.microprofile.context.ManagedExecutor, java.util.concurrent.ExecutorService, java.lang.Object], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.context.ManagedExecutor managedExecutor(), declaringBean=com.sebastian_daschner.coffee.mp_cp.ManagedExecutorProducer]
		- PRODUCER METHOD bean [types=[org.eclipse.microprofile.context.ManagedExecutor], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.context.ManagedExecutor getAllManagedExecutor(), declaringBean=io.quarkus.smallrye.context.runtime.SmallRyeContextPropagationProvider]
```

The SmallRye implementation seems to define their own, which then collides.

**Expected behavior**
I expect the following examples to work, as described in the spec:

**To Reproduce**

```java
public class ManagedExecutorProducer {

    @Produces
    ManagedExecutor managedExecutor() {
        System.out.println("creating managed executor");

        return ManagedExecutor.builder()
                .propagated(ThreadContext.CDI, ThreadContext.APPLICATION)
                .maxAsync(4)
                .maxQueued(4)
                .build();
    }

    public void disposeManagedExecutor(@Disposes ManagedExecutor managedExecutor) {
        System.out.println("disposing managed executor");
        managedExecutor.shutdownNow();
    }
}
```

Also see [here](https://github.com/sdaschner/quarkus-playground/tree/mp-cp/src/main/java/com/sebastian_daschner/coffee/mp_cp)

Also see my [blog post](https://blog.sebastian-daschner.com/entries/context-asynchronous-execution-bulkheads-microprofile)

Tested with Quarkus version `1.0.1.Final`

**Suggestion**

To resolve it, maybe it helps to annotate `SmallRyeContextPropagationProvider#getAllManagedExecutor` (and others) with `@DefaultBean`?

### PR DESCRIPTION
**Pull request by manovotn**
… that users can override them easily.

Fixes #6148

### CODE REVIEW

**Comment by manovotn** [comment]
@sdaschner FYI

**Comment by manovotn** [comment]
That Kogito test failure looks rather unrelated, I did try to rerun that one but it keeps failing. Not sure why...

**Comment by geoand** [comment]
CI failed I think because a PR was merged in the meantime. Probably best to rebase onto the master

**Comment by geoand** [comment]
CI failed I think because a PR was merged in the meantime. Probably best to rebase onto the master

**Comment by manovotn** [comment]
Yea, will do that on Mon (not near my work laptop now).

**Review by FroMage — APPROVED** [review]

**Comment by manovotn** [comment]
Rebased onto master.

**Pull request merged**
