### PR TITLE
Allow transformation of private injected field to allow reflection-free injection

### LINKED ISSUE #12597: ArC - get rid of reflection fallback for private injection points
Currently, we have a reflection fallback for private injection points. This is not ideal. In theory, we could get rid of the reflection fallback if we transform the original class and add a package-private synthetic "setter" method that could be used from the bean metadata class.

```java
public class Foo {
   
   @Inject
   private Bar bar;

   // Generated package-private method - will be called from the bean metadata class
   static set$$bar(Foo foo, Bar bar) {
      foo.bar = bar;
   }
}
```

The downside of this approach is the cost of transformation.

NOTE: This approach is similar to what the compiler does for nested classes that need to access a private member.

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #12597

This PR adds a configuration (by default enabled) for transformation of private fields that are injection points into package private.
The change allows Arc to operate on them without the need for reflection.

If this option is turned on, there is a DEBUG level logging for each changed injection point (just like with other transformations):
> [io.qua.arc.pro.Beans] (build-5) Changed visibility of an injected private field to package-private. Field name: head in class: io.quarkus.arc.test.transform.injectionPoint.PrivateFieldInjectionTest$CombineHarvester

If you turn the option off, we are still using reflection fallback and the user keeps getting the same INFO logging as before:
> [io.qua.arc.pro.BeanProcessor] (build-6) Found unrecommended usage of private members (use package-private instead) in application beans:
	- @Inject field io.quarkus.arc.test.transform.injectionPoint.PrivateFieldInjectionTest$CombineHarvester#head

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Looks good. Thanks!

**Comment by manovotn** [comment]
I've fixed the issue and also added a more thorough test for private injection point of a bean with superclass in different package.
Hopefully, there aren't any more variations I've forgotten :)

**Review by mkouba — APPROVED** [review]

**Comment by manovotn** [comment]
The kotlin failures I have honestly no clue about.
The LRA I think I might know, I'll dig into it more tomorrow.

**Comment by Ladicek** [comment]
This should also allow to shed some reflection registration I guess?

**Comment by manovotn** [comment]
> This should also allow to shed some reflection registrations I guess?

@Ladicek sadly, this PR currently has several problems that we cannot really fully remedy.
I.e. there are issues with bean superclasses declaring private injection points while not being beans themselves (meaning not eligible for transformation). In such cases we'd still need reflection workaround meaning the whole effort will only really affect a fraction of actual private injection.

**Comment by Ladicek** [comment]
I would hope that would be a pretty significant fraction, but I also saw we need reflection for non-{public,protected} fields in superclasses in different packages, so I understand it's not that simple...

**Comment by manovotn** [comment]
@Ladicek @mkouba I've updated the PR according to the issues I mentioned in https://github.com/quarkusio/quarkus/issues/12597#issuecomment-1381932627
We can basically only temper with private fields declared by given bean, superclasses and other cases might potentially require reflection anyway. There are tests that should show the case we can transform as well as parts that we cannot.

I'm not sure it's worth incorporating which is where I'd like your input. IMO it shouldn't hurt, it's just that the gain might not be great based on user app.

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I'd like to note that my comment above about reflection registrations is wrong -- I previously didn't see that reflection registrations already happen only when necessary. So this PR doesn't have to do anything extra and we should already shed some reflection registrations, so that's nice :-)

**Comment by manovotn** [comment]
The FT TCK failure is a case with (private field) injection into interceptor class; I assume this to be reproduceable outside of FT as well and decorators to be equally affected. I'm not quite sure how my changes influence these parts but I obviously missed something there; can take yet another look on Mon.

**Comment by manovotn** [comment]
FTR, the second commit I added enables transformation of private injection points for interceptors and decorators and adds tests for them. I've added this into the validation section of bean deployment (where we do similar things for standard beans) so that we can keep transformations in one place and also because I assume we might need some actual interceptor/decorator validation in the near future if we want to try and pass CDI Lite TCKs with Quarkus 3.

**Pull request merged**
