### PR TITLE
Qute - replace the map-based html escaper with simplified impl

### PR DESCRIPTION
**Pull request by mkouba**
- this result mapper is used to replace some characters for HTML/XML
templates

### CODE REVIEW

**Comment by johnaohara** [comment]
I'll try and take a look today

**Comment by mkouba** [comment]
@johnaohara thanks! I don't expect a big difference though...

**Review by gastaldi — APPROVED** [review]

**Comment by mkouba** [comment]
I'm going to merge this one now. @johnaohara it's a low priority but if you get a chance to look at it, that would be awesome ;-)

**Comment by johnaohara** [comment]
@mkouba np, I keep running out of time :( I will test, but as you say I am also not expecting huge differences. iirc the previous impl was using 1-2% cpu time under heavy load

**Comment by mkouba** [comment]
In that case, I'd say "just skip it". There are other tasks that deserve your attention ;-)

**Pull request merged**
