### PR TITLE
Bump Wiremock to 3.0.0

### LINKED ISSUE #35648: Bump Wiremock to 3.0.0
### Description

New major version of Wiremock ([v3.0.0](https://github.com/wiremock/wiremock/releases/tag/3.0.0)) has been released.

The group ID and artifact ID are changed from:

> com.github.tomakehurst:wiremock-jre8
> com.github.tomakehurst:wiremock-jre8-standalone

to:

> org.wiremock:wiremock
> org.wiremock:wiremock-standalone

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Resolves #35648

### CODE REVIEW

**Comment by geoand** [comment]
Let's see what CI says

**Comment by Eng-Fouad** [comment]
> Let's see what CI says 

It seems one of the tests hit 6h limit and failed. Is it possible to re-run this specific test again?

**Comment by geoand** [comment]
Nah, it's fine

**Review by geoand — APPROVED** [review]
Great stuff, thanks!

**Comment by famod** [comment]
Little too fast for 3.0.1 ;-)
https://github.com/wiremock/wiremock/releases/tag/3.0.1

**Comment by geoand** [comment]
Sounds like an opportunity for a follow up PR 😉

**Pull request merged**
