### PR TITLE
Add environmentVariables to gradle task quarkusDev

### LINKED ISSUE #32661: Support setting environment variables in Gradle quarkusDev
### Description

This enables setting environment variables in dev mode. Something like:

#### build.gradle.kts:

```
tasks {
    quarkusDev {
        environmentVariables.put("FOO_VALUE", "1")
        environmentVariables.put("BAR_VALUE", "2")
    }
}
```

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Closes #32661

### CODE REVIEW

**Comment by aloubyansky** [comment]
Thanks @Eng-Fouad, do you think you could add a little test in https://github.com/quarkusio/quarkus/tree/main/integration-tests/gradle for this feature?

**Comment by Eng-Fouad** [comment]
> Thanks @Eng-Fouad, do you think you could add a little test in https://github.com/quarkusio/quarkus/tree/main/integration-tests/gradle for this feature?

Yes sure, I will do.

**Comment by Eng-Fouad** [comment]
@aloubyansky I just added a simple test. However, I could not run the Quarkus project on my machine, so I wrote the test without compilation. Could you please verify the test from your side? Thanks.

**Comment by aloubyansky** [comment]
Thanks @Eng-Fouad, let's see what the CI says.

**Comment by aloubyansky** [comment]
Looks like it's passing @Eng-Fouad, thanks! Would you mind also adding a note about it in https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/gradle-tooling.adoc? It'll end up in https://quarkus.io/guides/gradle-tooling#dev-mode. You could do that in a separate PR, if you like.

**Comment by Eng-Fouad** [comment]
> Looks like it's passing @Eng-Fouad, thanks! Would you mind also adding a note about it in https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/gradle-tooling.adoc? It'll end up in https://quarkus.io/guides/gradle-tooling#dev-mode. You could do that in a separate PR, if you like.

OK, I will add it to docs 👍

**Comment by Eng-Fouad** [comment]
@aloubyansky using Kotlin DSL, which one is correct?

```
tasks.quarkusDev {
    environmentVariables = mapOf("FOO_VALUE" to "abc", "BAR_VALUE" to "def")
}
```

or

```
tasks.quarkusDev {
    environmentVariables.set(mapOf("FOO_VALUE" to "abc", "BAR_VALUE" to "def"))
}
```

**Comment by Eng-Fouad** [comment]
I chose: `environmentVariables.set()`

**Review by gastaldi — APPROVED** [review]
Nice!

**Review by aloubyansky — APPROVED** [review]

**Comment by maxandersen** [comment]
does this not overwrite users actual environment meaning users can no longer do:

```
FOO=whatever gradle quarkusDev
```

as gradle build will override the environment?

That is not good IMO as it changes the order of priority/locality.

**Pull request merged**
