### PR TITLE
Add build item for extensions to contribute ClusterRoleBindings

### PR DESCRIPTION
**Pull request by metacosm**
Signed-off-by: Chris Laprun <claprun@redhat.com>

### CODE REVIEW

**Comment by metacosm** [comment]
This would also be a candidate for backport if possible.

**Review by xstefank — APPROVED** [review]

**Comment by gsmet** [comment]
Is there an overall goal behind the backport requests?

Because from what I can see, this one (and some of the others) qualify more as new features than as fixes. So except if we have a very pressing business requirements, I'm not so excited about backporting them.

**Comment by metacosm** [comment]
> Is there an overall goal behind the backport requests?
> 
> Because from what I can see, this one (and some of the others) qualify more as new features than as fixes. So except if we have a very pressing business requirements, I'm not so excited about backporting them.

Understandable. However, https://github.com/quarkiverse/quarkus-operator-sdk/issues/932 cannot be fixed without these particular features (or changes that would similarly expose information that isn't currently available to extensions). I wouldn't say that this is a pressing need, however it would be detrimental for this not to be in the next LTS, in my opinion. I realize it's pretty late in the cycle but we don't get to choose when issues appear or when we finally have time to work on them. This being available in some .x version of the next LTS would be fine with me, it doesn't need to be in the very first one as long as it's eventually there and doesn't have to wait for LTS + 1.

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
