### PR TITLE
Mark quarkus-core extensions as hidden in the descriptor

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Comment by gsmet** [comment]
Is it always present then?

**Comment by aloubyansky** [comment]
It is of course always present. But there is a difference between Maven and Gradle extension listing. Currently when the installed extensions are requested Gradle lists all the installed extensions including the transitive ones (which, imo, is a good thing). Maven however lists only the direct dependencies (also not taking into account the parent poms). So it's unlikely you'll see it Maven but it does appear among the Gradle project deps.

**Comment by aloubyansky** [comment]
Marking core as unlisted can't be wrong either way :)

**Comment by aloubyansky** [comment]
Especially, given that quarkus-arc is unlisted.

**Comment by gsmet** [comment]
It's just that I remember some discussions about how it was possible to create a broken Quarkus app as core dependencies were missing. I think we also discussed making ArC always there.

Best is to ask @ia3andy .

**Comment by ia3andy** [comment]
On code.quarkus.io it's (already) not listed because there is no category.
On the maven plugin, it is going to hide it which I think is good to makes things consistent..

Regarding having quarkus-arc by default, people argued that some may not want to use arc..

**Review by ia3andy — APPROVED** [review]

**Pull request merged**
