### PR TITLE
Avoid potential NPE in Metrics filter

### LINKED ISSUE #16620: Resteasy Reactive - NPE when a filter throws exceptions
## Describe the bug

My application throws an exception inside a `ContainerRequestFilter`. This exception is then catched an converted to a 400 status code inside an `ExceptionMapper`.

This setup works fine in Resteasy Classic - status code 400 ist returned, and no exception.
In Resteasy Reactive, I get the exception from below and an 500 status code.

When I remove the `ExceptionMapper`, the RuntimeException is logged as expected, but no NPE is thrown.

### Expected behavior
No exceptions. Correct response that was set in the ExceptionMapper.

### Actual behavior
```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-04-19 11:30:50,075 INFO  [io.quarkus] (Quarkus Main Thread) rr-rest-metrics 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.13.2.Final) started in 3.215s. Listening on: http://localhost:8080
2021-04-19 11:30:50,077 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-04-19 11:30:50,077 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, mutiny, resteasy-reactive, smallrye-context-propagation, smallrye-metrics]
2021-04-19 11:31:11,471 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /hello-resteasy-reactive failed, error id: 6347e5ea-b5a9-4ec4-94f6-e06d7ec92ebd-1: java.lang.NullPointerException
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter.filter(QuarkusRestMetricsFilter.java:15)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter.filter(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter.zig:68)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.filter$$superaccessor1(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.zig:213)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass$$function$$1.apply(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass$$function$$1.zig:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.filter(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.zig:168)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:24)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:9)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:122)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:47)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder.lambda$start$1(StaticResourcesRecorder.java:65)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:101)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:206)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

2021-04-19 11:31:11,480 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-2) Request failed: java.lang.NullPointerException
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter.filter(QuarkusRestMetricsFilter.java:15)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter.filter(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter.zig:68)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.filter$$superaccessor1(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.zig:213)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass$$function$$1.apply(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass$$function$$1.zig:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.smallrye.metrics.runtime.QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.filter(QuarkusRestMetricsFilter$GeneratedServerResponseFilter$filter_Subclass.zig:168)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:24)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:9)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:122)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:47)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder.lambda$start$1(StaticResourcesRecorder.java:65)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:101)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:206)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Download the reproducer: [rr-rest-metrics.zip](https://github.com/quarkusio/quarkus/files/6334905/rr-rest-metrics.zip)
2. mvn quarkus:dev
3. Visit http://localhost:8080/hello-resteasy-reactive
4. The exception happens

### Configuration
```properties
quarkus.smallrye-metrics.jaxrs.enabled=true

```

### Output of `uname -a` or `ver`
MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\eclipse\tools\apache-maven\bin\..
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\zulu11.39.15-ca-jdk11.0.7-win_x64
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### PR DESCRIPTION
**Pull request by geoand**
The NPE could happen if an exception was thrown
in a ContainerRequestFilter

Fixes: #16620

### CODE REVIEW

**Review by FroMage — COMMENTED** [review]
I'm a bit torn about this: it's hard for filter authors to know which (allowed) parameter may be `null`, and why. 

Perhaps it would be better to always have a `ResourceInfo` even if its methods then throw an exception explaining that there's no resource because we had an exception before we found it.

But this would not make it easier for this particular filter which wants to ignore calls when that happens.

OTOH, is it really normal to invoke response filters when an exception happens that prevents us from finding the target resource?

**Comment by FroMage** [comment]
Well, the spec says "A response mapped from an exception MUST be processed using the  filter chain and the  interceptor chain (if an entity is present in the mapped response). "

So yeah, we apparently need to invoke them no matter how broken everything else is.

**Comment by geoand** [comment]
> So yeah, we apparently need to invoke them no matter how broken everything else is.

Unfortunately yes...

**Comment by geoand** [comment]
> Perhaps it would be better to always have a `ResourceInfo` even if its methods then throw an exception explaining that there's no resource because we had an exception before we found it.

I actually think this would make it even more confusing

**Comment by FroMage** [comment]
OK hold on, the javadoc of `ResourceInfo` says:

> Methods in this class MAY return null if a resource class and method have not been matched, e.g. in a standalone, pre-matching ContainerRequestFilter that was not provided by a post-matching PreMatching.

So that's our answer that is spec-compliant.

**Review by ebullient — APPROVED** [review]

**Review by FroMage — CHANGES_REQUESTED** [review]
According to javadoc, the right thing to do is to have a non-null `ResourceInfo` and a `null` return value from its methods. Given that both options are equally confusing IMO, we should implement the one that is documented and has a better interop chance.

**Comment by geoand** [comment]
OK lemme do that

**Review by FroMage — APPROVED** [review]
Great, thanks!

**Comment by geoand** [comment]
👍🏼

**Comment by gsmet** [comment]
@geoand this one conflicts (due to the MP 4 changes). Not sure it's worth rewriting the patch? I'll let you judge of that.

**Comment by geoand** [comment]
I think it's not terribly important, but I'd be up for it if someone complains :)

**Pull request merged**
