### PR TITLE
Add keycloak-authorization container image test

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
I looked at this test for a couple of hours today, `KeycloakPolicyEnforcerRecorder` sees the properties set by `DevServices for Keycloak` but looks like Keycloak container is not available yet, I may have to update the recorder to keep retrying to connect...

**Comment by sberyozkin** [comment]
@geoand I looked for a long time at this one yesterday, and while I had some progress at trying to narrow down the problem, it is still not quite clear to me what is going on. 
I believe what I've confirmed is that Keycloak Authz Client, being an external client, needs to use a `client.quarkus.auth-server-url`, `quarkus.auth-server-url` gives a connection exception. This is the problem number one (though I don't understand yet how `quarkus-oidc` itself is capable of using this internal `quarkus.auth-server-url` address).
The other strange problem is that if I try to use  Keycloak Authz Client with `client.quarkus.auth-server-url` directly inside `KeycloakDevServicesProcessor` (in `oidc/deployment`) then it can connect, but once the same code runs in `keycloak-authorization/runtime/KeycloakPolicyEnforcerRecorder` it fails...
It will require more investigation

**Comment by sberyozkin** [comment]
Np, with some temp local modification, where `KeycloakPolicyEnforcerAuthorizer` tries both `quarkus.oidc.auth-server-url` and `client.quarkus.oidc.auth-server-url`, I see both attempts failing but these properties set by `KeycloakDevServicesProcessor` are visible, so no ordering issues exist.
My best bet at this stage is that there is a race condition, when `KeycloakDevServicesProcessor` creates a realm it checks the status, all is good, but Keycloak may not have finished yet initializing it, and in native mode, a request to this realm happens too fast.
I'll look into it after PTO...
The exceptions I'm seeing (with the temp update, `http://keycloak-hU5Ko:8080/auth/realms/quarkus` is `quarkus.oidc.auth-server-url`, `http://localhost:40549/auth/realms/quarkus` is `client.quarkus.oidc.auth-server-url`):

```
May 27, 2022 4:39:01 PM org.keycloak.adapters.authorization.PolicyEnforcer
INFO: No path provided in configuration.
May 27, 2022 4:39:01 PM org.keycloak.adapters.authorization.PolicyEnforcer
INFO: Querying the server for all resources associated with this application.
May 27, 2022 4:39:02 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
java.lang.RuntimeException: PolicyEnforcer first exception: "Could not find resource, address:http://keycloak-hU5Ko:8080/auth/realms/quarkus. stacktrace:java.lang.RuntimeException: Could not find resource
	at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:45)
	at org.keycloak.authorization.client.resource.ProtectedResource.findAll(ProtectedResource.java:248)
	at org.keycloak.adapters.authorization.PolicyEnforcer.configureAllPathsForResourceServer(PolicyEnforcer.java:225)
	at org.keycloak.adapters.authorization.PolicyEnforcer.configurePaths(PolicyEnforcer.java:153)
	at org.keycloak.adapters.authorization.PolicyEnforcer.<init>(PolicyEnforcer.java:76)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerRecorder.createPolicyEnforcer(KeycloakPolicyEnforcerRecorder.java:130)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerRecorder.setup(KeycloakPolicyEnforcerRecorder.java:42)
	at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: java.lang.RuntimeException: Could not find resource
	at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:91)
	at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:181)
	at org.keycloak.authorization.client.resource.ProtectedResource.findAll(ProtectedResource.java:246)
	... 20 more
Caused by: java.lang.RuntimeException: Error executing http method [GET]. Response : null
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:106)
	at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
	at org.keycloak.authorization.client.resource.ProtectedResource$4.call(ProtectedResource.java:175)
	at org.keycloak.authorization.client.resource.ProtectedResource$4.call(ProtectedResource.java:172)
	at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:179)
	... 21 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:84)
	... 25 more
", second exception: "Could not obtain configuration from server [http://localhost:40549/auth/realms/quarkus/.well-known/uma2-configuration]., address:http://localhost:40549/auth/realms/quarkus. stacktrace:java.lang.RuntimeException: Could not obtain configuration from server [http://localhost:40549/auth/realms/quarkus/.well-known/uma2-configuration].
	at org.keycloak.authorization.client.AuthzClient.<init>(AuthzClient.java:266)
	at org.keycloak.authorization.client.AuthzClient.create(AuthzClient.java:105)
	at org.keycloak.adapters.authorization.PolicyEnforcer.<init>(PolicyEnforcer.java:65)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerRecorder.createPolicyEnforcer(KeycloakPolicyEnforcerRecorder.java:130)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerRecorder.setup(KeycloakPolicyEnforcerRecorder.java:48)
	at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: java.lang.RuntimeException: Error executing http method [GET]. Response : null
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:106)
	at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
	at org.keycloak.authorization.client.AuthzClient.<init>(AuthzClient.java:264)
	... 19 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:84)
	... 21 more
"
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerRecorder.setup(KeycloakPolicyEnforcerRecorder.java:53)
	at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)

```

**Comment by sberyozkin** [comment]
@geoand Can you please have a brief look at this draft PR when you get a chance ?

here is a summary of what is going on: [this code](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L247) which you may recall, creates KC client and internal URLs, publishes both as config properties - which can only happen once Keycloak is up and running, and the realm is created (you can see in that code, it makes sure the realm is actually accessible) and only after that code advertising the URLs as the config properties is done, next, [this code](https://github.com/quarkusio/quarkus/blob/main/extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerRecorder.java#L65) runs and it fails to connect to Keycloak. I've tried both the internal and client URLs there (I've temporarily updated the Keycloak recorder to try both URLs as you can see in this PR), they are visible, and are equal to those set by KeycloakDevServicesProcessor.

This test passes in a JVM mode. I'm short of ideas why it fails in a native mode. 
Thanks

**Comment by geoand** [comment]
@sberyozkin I looked at this and here is a description of why the unit test pass and the integration tests do not:

The unit tests simply launch the application in the same JVM as the tests run and also launch Keycloak as a docker container that both the test and application (which again are running on the same JVM) can access via `locahost:xxxxx`.
However, when launching the integration tests, now the application and the Keycloak are both launched as containers inside the same docker network. This means that the application can now only talk to keycloak via the Keycloak container's hostname  (which is something like `keycloak-96znz` and port `8080`) while the test can only talk to Keycloak via `locahost:yyyyy` (where `yyyyy` is the port that has been mapped to `8080` on the host machine).
The error we are seeing that is the root of the problem is:

```
Could not obtain configuration from server [http://localhost:45223/realms/quarkus/.well-known/uma2-configuration]., address:http://localhost:45223/realms/quarkus. stacktrace:java.lang.RuntimeException: Could not obtain configuration from server [http://localhost:45223/realms/quarkus/.well-known/uma2-configuration].
```

when the Keycloak Authorization Client is used in the application.

This means that the wrong URL is being used internally (`http://keycloak-96znz:8080/realms/quarkus/.well-known/uma2-configuration` should have been used).

Does this information help you track down the problem?

**Comment by sberyozkin** [comment]
@geoand Apologies, I was doing some fixes and missed your comment, I've no idea why but I'm not always notified which is why I keep missing the pings.

Thanks for a nice summary of the technical aspect of how the networking works,

Right, so have a look please at the stacktrace, and the updated recorder where I first try `quarkus.oidc.auth-server-url` and then I try `client.quarkus.oidc.auth-server-url`, and there you can see both 
```
ERROR: Failed to start application (with profile prod)
java.lang.RuntimeException: PolicyEnforcer first exception: "Could not find resource, address:http://keycloak-hU5Ko:8080/auth/realms/quarkus.
...
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```
and
```
second exception: "Could not obtain configuration from server [http://localhost:40549/auth/realms/quarkus/.well-known/uma2-configuration]., address:http://localhost:40549/auth/realms/quarkus. stacktrace:java.lang.RuntimeException: Could not obtain configuration from server [http://localhost:40549/auth/realms/quarkus/.well-known/uma2-configuration].
	at org.keycloak.authorization.client.AuthzClient.<init>(AuthzClient.java:266)
	at ...
	... 19 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```  

In both cases the underlying cause is the same, `ConnectException`. with the DNS resolution it looks like it progresses further but in both cases the keycloak container can not be reached...

**Comment by geoand** [comment]
Using `keycloak-hU5Ko` should work - I was actually able to do a `docker exec` into the application container and then perform curl on `http://keycloak-hU5Ko:8080/auth/realms/quarkus` and it worked as expected.

Can you try rebasing the PR onto main and trying again?

**Comment by sberyozkin** [comment]
@geoand Sure, will check it, thanks

**Comment by geoand** [comment]
Let me know if you want me to take another look

**Comment by sberyozkin** [comment]
Sure, thanks

**Comment by sberyozkin** [comment]
@geoand Unfortunately the code running in `KeycloakPolicyEnforcerRecorder` still fails to connect to the Keycloak container, this time it was `http://keycloak-fp8mb:8080/realms/quarkus`.
The container is ready, because [this code](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L266) which makes this internal URL available as a `quarkus.oidc.auth-server-url` property runs after the code (immediately above it) which successfully posts a realm creation request to Keycloak.

What is interesting is that [this test](https://github.com/quarkusio/quarkus/tree/main/integration-tests/container-image/maven-invoker-way/src/it/container-build-with-keycloak) passes. In that test, [OidcRecorder](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java) will record the code which will use the same type of url, `http://keycloak-fp8mb:8080/realms/quarkus` and it works.

The only difference between `KeycloakPolicyEnforcerRecorder` and `OidcRecorder` is that they reside in two different extensions. 
It feels like some context allowing for such a connection to succeed is not available to  the code created with `KeycloakPolicyEnforcerRecorder`. As I said above the Keycloak container must be ready by the time the `KeycloakPolicyEnforcerRecorder` code is executed...

**Comment by sberyozkin** [comment]
@geoand The other thing is that the test added in this PR is nearly identical to the one passing in https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-keycloak-authorization-quickstart/src/test/java/org/acme/security/keycloak/authorization/NativePolicyEnforcerTest.java which also relies on `DevServices for Keycloak` to prepare the container, the only difference is in the quickstart this Keycloak container is reachable via the `localhost`

**Comment by sberyozkin** [comment]
@geoand That is what I could not figure out how to do, how to debug it when the Native Test was running, thanks for showing how to do it, that should make it easier, thanks for your help

**Comment by geoand** [comment]
You are welcome!

Just one correction, it's not a native test, it's an integration test that launches the application that has been built as a container - a JVM container not a native binary container :)

**Comment by sberyozkin** [comment]
@geoand Debugging it did help me to progress a bit, but not too far.
The problem you were seeing where a `keycloak:` URL was set but then suddenly `localhost` was produced is caused by [this code](
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L410).

if you recall, that was done to avoid the issuer problem - the test would use `client.oidc.auth.server.url` to acquire a token so the issuer would be `localhost:` based, while `quarkus-oidc`, while discovering the KC metadata, would get `http://keycloak:` based `issuer` so there was a mismatch. So `org.keycloak.adapters.authorization.PolicyEnforcer` initializes `AuthzClient` which gets `ServerConfiguration` which gets a mix of `localhost:` and `keycloak:` based URLs and it picks somewhere `localhost:` based URL and fails to connect. (The fact that `ServerConfiguration` return a mix of URL hostnames is a likely bug in KC I think, but we can workaround it). Locally I temp disabled [this code](
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L410) since in this PR the application is configured to support any issuer (wildcard). For DevServices I can also add a property to disable adding such env properties.
So, after this update, I'm debugging again, `PolicyEnforcer`->`AuthzClient`->`ServerConfiguration` returns only `keycloak:` based URLs but in `org.keycloak.authorization.client.resource.ProtectedResource#find`, when trying to use a `keycloak:` based url to get a token, it fails with the same `ConnectException`.

Can you please give me a favor and just confirm the same in case I've missed something (tomorrow or Mon), with the temp disabled [this code](
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L410) ?
Thanks

**Comment by sberyozkin** [comment]
@geoand I think I've found something, will update

**Comment by sberyozkin** [comment]
@geoand @pedroigor So I've spent few more hours today trying a few different options but I could not resolve the following.

@pedroigor Hey Pedro, so in this test, as @geoand has explained above, we have a test running outside of the Docker network and uses a URL like `http://localhost:12345` where `12345` is a mapped port. While both Keycloak and Quarkus containers are running inside this Docker network so Quarkus needs to use a URL like `http://keycloak-abcd:8080`.

DevServices command for starting KC in one concrete instance looks like this:
```
"start --http-enabled=true --hostname-strict=false --hostname-strict-https=false --hostname=localhost --hostname-port=42459"
```
(recall we discussed it on Zulip, `start-dev` is simpler but `start` is faster)

With keycloak-authorization we have `AuthzClient` returning `ServerConfiguration` which looks like this:

ServerConfiguration

So as you can see some URLs which are considered public start with `localhost:42459`, for example a token endpoint, so the test can get the tokens successfully outside of the docker network.

The problem is with the `resourceRegistrationEndpoint` as it starts with: `localhost:42459`. It is used in a few places in `keycloak-authorization` and it fails to connect.

I'm really not sure if it is even resolvable. My understanding is that `resourceRegistrationEndpoint` is considered public ? In this case then `quarkus-keycloak-authorization` won't be able to connect to it in this test, it really needs something like `http://keycloak-rfk123:8080`.

I have tried to start Keycloak with
```
```
"start --http-enabled=true --hostname-strict=false --hostname-strict-https=false"
```
only, without `--hostname=localhost --hostname-port=42459` - this does resolve the connection problem, however, the token acquired by the test can not be used, first it forces to use `any` issuer during the token verification in `quarkus-oidc` but also `keycloak-authorization` fails to use it to check the authorization - this is because the test used `localhost:42459` to acquire a token which affects the issuer value while `keycloak-authorization` uses `http://keycloak-rfk123:8080`...

So my current thinking it just does not work whichever way you try it. 
@pedroigor do you have ideas which might be tweaked at the Keycloak end to report the `resourceRegistrationEndpoint` as the internal URL ?
@geoand Can there be some Docker networking hacks for the public URL be reachable from withing the Docket network, so that 
`Quarkus in Docker Network -> client.oidc.server-url -> Keycloak in Docker Network` ?

Thanks

**Comment by geoand** [comment]
Thanks for the analysis @sberyozkin !

**Comment by sberyozkin** [comment]
Hey @geoand thanks for showing how debug it all.

**Comment by geoand** [comment]
No problem! Is it working now?

**Comment by sberyozkin** [comment]
Sorry @geoand, did not see your last question, no, sadly no, as some changes will need to be done on the Keycloak side I guess, we'll discuss with Pedro.
I was thinking, may be a networking related workaround can be created but then it would still be just a workaround which may not work for all the users.

**Comment by gsmet** [comment]
What is the status of this?

**Pull request closed without merging**
