### PR TITLE
Don't fire the startup event until the vert.x producer has been initialized

### LINKED ISSUE #6612: Sometimes getting an NPE when using Startup event and vertx
**Describe the bug**
Here is the exception I am getting:
```
Andy Damevin:
2020-01-17 15:47:03,534 ERROR [io.sma.rea.mes.ext.MediatorManager] (main) Unable to initialize mediator: demo.gos.hero.Hero#game: java.lang.RuntimeException: Error injecting io.vertx.core.Vertx demo.gos.hero.Hero.vertx
        at demo.gos.hero.Hero_Bean.create(Hero_Bean.zig:380)
        at demo.gos.hero.Hero_Bean.create(Hero_Bean.zig:1228)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at demo.gos.hero.Hero_Bean.get(Hero_Bean.zig:1212)
        at demo.gos.hero.Hero_Bean.get(Hero_Bean.zig:56)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:355)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:367)
        at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:60)
        at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$initializeAndRun$4(MediatorManager.java:143)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:136)
        at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent40.deploy_0(LifecycleEventsBuildStep$startupEvent40.zig:58)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent40.deploy(LifecycleEventsBuildStep$startupEvent40.zig:77)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:124)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runtime.Application.run(Application.java:210)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.NullPointerException
        at io.quarkus.vertx.core.runtime.VertxCoreProducer.vertx(VertxCoreProducer.java:26)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:258)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:69)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        at demo.gos.hero.Hero_Bean.create(Hero_Bean.zig:363)
        ... 27 more
```

@cescoffier has made a reproducer.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #6612

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Hm, I remember we fixed this once but then there was the split of the vertx extension and the error appeared again. Maybe we should spend some more time reviewing the current state of Vertx integration and document it somehow as it became quite complex.

**Review by cescoffier — APPROVED** [review]
Should we add the reproducer (as a test) I attached to the issue?

**Comment by mkouba** [comment]
@cescoffier well, I wonder if running a test 1000x in a row is a good idea?

**Comment by cescoffier** [comment]
No, actually it didn't need that, a simple `@Test` is enough. 
I use repeated tests when hunting a concurrency issue.

**Comment by mkouba** [comment]
If so then +1 and feel free to add your test to this PR ;-).

**Comment by cescoffier** [comment]
I will in a few minutes.

**Comment by mkouba** [comment]
>  cescoffier commented 3 hours ago
> I will in a few minutes.

@cescoffier ^ ;-) ?

**Comment by cescoffier** [comment]
ok, that's long minutes, but I will do it this afternoon. Started writing test for reactive messaging.

**Comment by cescoffier** [comment]
@mkouba https://github.com/quarkusio/quarkus/pull/6657

**Comment by gsmet** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/6657/commits .

**Pull request closed without merging**
