### PR TITLE
Use Mandrel by default for container build

### PR DESCRIPTION
**Pull request by gsmet**
Due to a bug in GraalVM, let's default to using Mandrel containers for now.

See:
- https://github.com/quarkusio/quarkus/issues/29124
- https://github.com/oracle/graal/issues/5303

@cescoffier @galderz @zakkak I think that's all that's needed to switch to Mandrel container builds.

@galderz I will wait for your green light before merging this.

### CODE REVIEW

**Comment by zakkak** [comment]
> I think that's all that's needed to switch to Mandrel container builds.

That's true as far as it concerns the code, but I am afraid we need to go through the documentation and make sure things are consistent there as well.

> Due to a bug in GraalVM, let's default to using Mandrel containers **for now**.

So is this a temporary change expected to be reverted once the mentioned issue is resolved? 
FWIW the Mandrel team seems to be in favor of making this a permanent change instead (cc @galderz @jerboaa @Karm in case I got this wrong :) )

**Review by zakkak — CHANGES_REQUESTED** [review]
We will need to change

https://github.com/quarkusio/quarkus/blob/9108cfadd09657297d2fc8cd3c8ea59019888d99/.github/workflows/ci-actions-incremental.yml#L718

to `mandrel-latest` as well.

**Comment by gsmet** [comment]
> but I am afraid we need to go through the documentation and make sure things are consistent there as well.

Yeah so for me it was supposed to be temporary so I was somehow thinking that we could be light on the doc changes and mention it in the migration guide/announcement.

If we decide to make this change permanent, we definitely need to update the documentation but I will let you do it as you're far more aware of what needs to be changed :).

I don't have any objections on my side but that's probably something we need to post on `quarkus-dev` to gather feedback.

**Comment by gsmet** [comment]
@zakkak I pushed the CI change you requested.

**Review by zakkak — APPROVED** [review]
LGTM as a temporary change. For making the change permanent we also need to go through the documentation.

I will prepare an email for quarkus-dev suggesting a permanent transition to Mandrel by default and wait for 1-2 weeks to see if there will be any objections before going through the docs.

Thanks @gsmet

**Comment by gsmet** [comment]
@zakkak perfect, thanks!

**Comment by zakkak** [comment]
@gsmet apparently we need https://github.com/quarkusio/quarkus/pull/29182/commits/1de3eacf1142da9ad89df48e23ffaa4bdf3cf343 as well. I pushed this as a separate commit so that in case of a revert of this PR we can keep it as `gu install` is no longer needed either in Mandrel or GraalVM.

**Review by cescoffier — APPROVED** [review]

**Comment by maxandersen** [comment]
@zakkak what are the documentation changes you think are needed for this? it should just be a dropin replacement so am I right in assuming doc changes are just that its at least mentioned the container build is done via mandrel?

**Comment by zakkak** [comment]
> @zakkak what are the documentation changes you think are needed for this?

It looks like you are right. I recalled more explicit mentions to GraalVM, that would imply it's the default, but it looks that's not the case.

>  it should just be a dropin replacement so am I right in assuming doc changes are just that its at least mentioned the container build is done via mandrel?

If we switch (permanently) to Mandrel by default I would also like to update the non-container related parts to promote Mandrel as well for consistency.

**Pull request merged**
