### PR TITLE
Dev mode - list reactive routes in 404 document

### LINKED ISSUE #10853: Dev mode - list reactive routes in the "404 - Resource Not Found" document
Currently, only JAX-RS resources, static resources and additional endpoints are listed.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #10853

### CODE REVIEW

**Comment by geoand** [comment]
I'll check this on Monday

**Comment by machi1990** [comment]
I think this also fixes issues reported in https://github.com/quarkusio/quarkus/issues/5236, right? @mkouba

**Comment by mkouba** [comment]
@machi1990 Not really. #5236 requires a more complex solution. This PR merely adds routes to the `NotFoundExceptionMapper` and if `quarkus-resteasy` is not present, adds an error handler to report reactive routes and endpoints registered by `NotFoundPageDisplayableEndpointBuildItem`. 

The problem is that `NotFoundExceptionMapper` leverages RESTEasy API at runtime (to obtain the resources methods). Which kind of makes sense because the discovery is perfomed by RESTEasy (unlike for reactive routes where the discovery is performed in a build step).

I agree that it would be nice to unify the logic but it's a little bit more challenging. E.g. we would have to introduce a general representation of an endpoint. That said, I belive that it's doable. We could try to fix #5236 for 1.9. WDYT?

**Comment by machi1990** [comment]
> @machi1990 Not really. #5236 requires a more complex solution. This PR merely adds routes to the `NotFoundExceptionMapper` and if `quarkus-resteasy` is not present, adds an error handler to report reactive routes and endpoints registered by `NotFoundPageDisplayableEndpointBuildItem`.
> 
> The problem is that `NotFoundExceptionMapper` leverages RESTEasy API at runtime (to obtain the resources methods). Which kind of makes sense because the discovery is perfomed by RESTEasy (unlike for reactive routes where the discovery is performed in a build step).
> 

@mkouba thanks for the detailed response. I was curious whether the PR would fix the issue too thus I wanted to link it for automatic closure upon merge but seems like not. 

> I agree that it would be nice to unify the logic but it's a little bit more challenging. E.g. we would have to introduce a general representation of an endpoint. That said, I belive that it's doable. We could try to fix #5236 for 1.9. WDYT?

Sure, #5236 can be done on separate PR / release. 

I'll have a look at your PR over the weekend.

**Review by geoand — APPROVED** [review]
Excellent!

**Review by cescoffier — APPROVED** [review]

**Review by machi1990 — APPROVED** [review]

**Pull request merged**
