### PR TITLE
Fixes Google cloud functions HTTP query params and status code bypass

### LINKED ISSUE #15501: Quarkus + Resteasy + Google Cloud Functions: no query parameters bypass
**Describe the bug**
I'm trying to implement a simple service using Google Cloud Functions and Quarkus. But if I'm trying to use `@QueryParam` annotation I'm getting nulls in any param. E.G.:
```java
	@GET
	@Path("echo1")
	@Produces(MediaType.TEXT_PLAIN)
	public Response echo1(@QueryParam("test") String test) {
		return Response.status(Response.Status.OK)
				.encoding("UTF-8")
				.entity("test: " + test).build();
	}
```

**Expected behavior**
```none
test: test string
```

**Actual behavior**
```none
test: null
```

**To Reproduce**
I've implemented a very small test service to reproduce the issue:
https://github.com/HardNorth/quarkus-google-functions-test/blob/main/src/main/java/net/hardnorth/test/quarkus/QuarkusTestService.java

You need to deploy it into Google Cloud. Because it works locally.

**Configuration**
Doesn't matter at all

**Additional context**
Based on what I see from code there is a missing part in `QuarkusHttpFunction.java`. E.G. for Amazon lambdas you have a whole loop which appends query parameters to `path` variable:
https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java#L154

But there is no such logic for Google Functions:
https://github.com/quarkusio/quarkus/blob/master/extensions/google-cloud-functions-http/runtime/src/main/java/io/quarkus/gcp/functions/http/QuarkusHttpFunction.java#L94

### LINKED ISSUE #15510: Quarkus + Resteasy + Google Cloud Functions: status code alway 200 no matter what
**Describe the bug**
I'm trying to implement a simple service using Google Cloud Functions and Quarkus. But if I'm trying to return any status except 200, I will always get 200. E.G.:
```java
	@GET
	@Path("error")
	@Produces(MediaType.TEXT_PLAIN)
	public Response error(@Context UriInfo uriInfo) {
		String uriStr = uriInfo.getBaseUri().toString() + uriInfo.getPath(true) + uriInfo.getQueryParameters();
		return Response.status(Response.Status.BAD_REQUEST)
				.encoding("UTF-8")
				.entity(uriStr + "\nmy error").build();
	}
```

**Expected behavior**
Status code 400

**Actual behavior**
Status code 200

**To Reproduce**
I've implemented a very small test service to reproduce the issue:
https://github.com/HardNorth/quarkus-google-functions-test/blob/main/src/main/java/net/hardnorth/test/quarkus/QuarkusTestService.java

You need to deploy it into Google Cloud. Because it works locally.

**Configuration**
Doesn't matter at all

**Additional context**
Based on what I see from code there is a missing part in `QuarkusHttpFunction.java`. E.G. for Amazon lambdas you bypass status and reason phrase explicitly:
https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java#L91

But there is no such logic for Google Functions (you convert only headers):
https://github.com/quarkusio/quarkus/blob/master/extensions/google-cloud-functions-http/runtime/src/main/java/io/quarkus/gcp/functions/http/QuarkusHttpFunction.java#L145

### PR DESCRIPTION
**Pull request by HardNorth**
Fixes #15501 and fixes #15510, adds unit-tests for Amazon Lambda, Azure Function, Google Function to ensure this will never be broken again. Amazon Lambda query handling slightly improved

### CODE REVIEW

**Comment by loicmathieu** [comment]
Thanks, I'll have a look at the Google Cloud Functions side.

@patriot1burke can you have a look at the lambda and azure functions side ?

**Review by loicmathieu — APPROVED** [review]
LGTM, great job!

I wanted to particularly thank you for the tests you added, these are great piece of tests and are very valuable additions.

We'll need @patriot1burke review for the lambda and azure functions part.

**Comment by loicmathieu** [comment]
Can you update the comment so the two reated issues would be fixed automatically when merging this one ?
See https://docs.github.com/en/enterprise/2.13/user/articles/closing-issues-using-keywords

**Comment by HardNorth** [comment]
@loicmathieu done

**Comment by gsmet** [comment]
@patriot1burke could you have a look at this one? I'd like to have it in 1.13.

or @matejvasek ?

**Comment by gsmet** [comment]
@patriot1burke @matejvasek ping? If you don't give a sign of life, I will merge it today given @loicmathieu approved it.

**Comment by patriot1burke** [comment]
LGTM.  Apologies, I've been out for a few weeks.

**Comment by gsmet** [comment]
@patriot1burke cool, thanks! Will merge then.

**Comment by gsmet** [comment]
Merged, thanks @HardNorth !

**Pull request merged**
