### PR TITLE
3.8.4 backports 1

### PR DESCRIPTION
**Pull request by gsmet**
@aloubyansky @rsvoboda this is the first round of backports for 3.8.4.

@aloubyansky I also added a commit to make SmallRye Common version consistent across all projects as I think it was the issue (my guess is that the bootstrap BOM was the culprit).

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
@franz1981 we tried to backport https://github.com/quarkusio/quarkus/pull/39739 and the test is failing. I wonder if it's because we need a newer version of Jackson for it to work? Could you have a look.

`io.quarkus.jackson.deployment.JacksonDefaultPoolTest.validateDefaultJacksonPool` is failing with:

```
java.lang.AssertionError: 

Expecting actual:
  com.fasterxml.jackson.core.util.JsonRecyclerPools$ThreadLocalPool@729cb7b
to be an instance of:
  com.fasterxml.jackson.core.util.JsonRecyclerPools.LockFreePool
but was instance of:
  com.fasterxml.jackson.core.util.JsonRecyclerPools.ThreadLocalPool
```

I don't think we want to upgrade Jackson in 3.8 for now, so maybe we should either adjust the test or drop the backport.

Let me know what you think.

**Comment by franz1981** [comment]
Yep, the new version of Jackson brought the required changes to the pool to make it work in a better way with Virtual Threads; meaning that older versions of Quarkus which are using prior versions of Jackson didn't use such and they won't have the benefit of being more virtual thread friendly nor the downside of hitting the issue I have fixed here

**Comment by rsvoboda** [comment]
This PR bumps vert.x to 4.5.7 (the same as in main) So I would vote for backporting https://github.com/quarkusio/quarkus/pull/39455 to get benefits for virtual threads.

Java 21 is supported for 3.8.

**Comment by gsmet** [comment]
@rsvoboda this hasn't been in any release so I'm not exactly excited about it. We could decide to backport it later but I think we at least need some bake time in 3.9 before doing so.
This will have to wait for 3.9.3 though.

**Comment by rsvoboda** [comment]
Sounds good, didn't realize it has 3.10 milestone on the PR. We could use you on QE side @gsmet  ;)

**Comment by rsvoboda** [comment]
#39739 has also 3.10 milestone, no bake time for it too.

**Comment by gsmet** [comment]
@rsvoboda yes, you're right (we refrained to backport  a few other things due to that but this one shouldn't have been either). I'll make both part of 3.9.3 and we will go from there.

**Comment by gsmet** [comment]
@aloubyansky @rsvoboda I think we are good now and things should be in line with what we discussed earlier today, could you have a look?

**Comment by aloubyansky** [comment]
Looks good @gsmet, thanks

**Review by rsvoboda — APPROVED** [review]
LGTM!

**Pull request merged**
