### PR TITLE
Document that ContextConfigurator#done() is invoked automatically

### PR DESCRIPTION
**Pull request by manovotn**
Note that this doesn't change or fix any behavior since there is a safety latch that already did this invocation in `ArcProcessor`, see [this code](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java#L436C30-L439).
Purpose of this PR is just to add clarity in how to properly operate with context configurators.

### CODE REVIEW

**Review by Ladicek — DISMISSED** [review]
I'd prefer to keep it all as a single statement, as that's how builders are typically used, but that's just a personal preference. @mkouba WDYT?

**Comment by mkouba** [comment]
I wonder if we should just add a note to the `ContextConfiguratorBuildItem` that `done()` is called automatically. That was probably one of the reasons why we introduced the `ContextConfiguratorBuildItem` anyway...

> I'd prefer to keep it all as a single statement, as that's how builders are typically used, but that's just a personal preference. @mkouba WDYT?

:+1:

**Comment by manovotn** [comment]
> I'd prefer to keep it all as a single statement, as that's how builders are typically used, but that's just a personal preference. 

WDYM? The `done()` method returns `void` which prevents you from doing something like:
```
 return new ContextConfiguratorBuildItem(contextRegistrationPhase.getContext()
                .configure(TransactionScoped.class).normal().contextClass(TransactionContext.class).done());
```

**Comment by manovotn** [comment]
> I wonder if we should just add a note to the ContextConfiguratorBuildItem that done() is called automatically. 

Right, we could do that instead but I found it sort of weird since all other Arc related configurators have `done()` method and require you to invoke it :shrug: 
I don't mind either way as long as it clarifies what is happening/should happen.

> That was probably one of the reasons why we introduced the ContextConfiguratorBuildItem anyway...

I don't recall this but it's very well possible :)

**Comment by mkouba** [comment]
> Right, we could do that instead but I found it sort of weird since all other Arc related configurators have `done()` method and require you to invoke it shrug
> I don't mind either way as long as it clarifies what is happening/should happen.

There are other places where we already call `done()` automatically: https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationsTransformer.java#L372-L380 ;-)

**Comment by Ladicek** [comment]
> The `done()` method returns `void`

Ouch, totally forgot about that. Well, that might be another reason why we call `done()` automatically :-)

**Comment by manovotn** [comment]
> There are other places where we already call done() automatically: https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationsTransformer.java#L372-L380 ;-)

That's good pointer, I didn't realize we're already doing it. In that case, I'll scratch this and instead mention it's done automatically.

**Comment by manovotn** [comment]
@mkouba @Ladicek I've changed the PR so that it now instead documents that `ContextConfigurator#done()` is invoked automatically.

**Review by mkouba — APPROVED** [review]

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
