### PR TITLE
Update the spring to 5.1.9.RELEASE

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by gsmet** [comment]
There is a dependency convergence issue: https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=7749&view=logs&jobId=8d8a3a4a-b6e2-5ba1-8653-fed54bf06386&taskId=14ce4d30-2ef4-5d65-2621-59ec40dc8509&lineStart=13995&lineEnd=13996&colStart=1&colEnd=1 .

@geoand can you check how we can deal with that long term (i.e. it will happen again)?

**Comment by geoand** [comment]
So, [this](https://github.com/quarkusio/quarkus/issues/3436) issue should take care of this in the future.

There isn't much point in updating the Spring version since any of the new capabilities in there won't really show up in the Quarkus work.

**Comment by zhfeng** [comment]
@geoand So we will not have the dependency of the spring in the future ?

**Comment by geoand** [comment]
@zhfeng The idea is in the future for us to provide our own jars which only what we is used by the Quarkus extension and nothing more.

**Comment by zhfeng** [comment]
Thanks @geoand and I think we can close this PR and wait for the https://github.com/quarkusio/quarkus/issues/3436 to be resolved ?

**Comment by geoand** [comment]
That sounds like a good idea.

Thanks for your interest @zhfeng !

**Pull request closed without merging**
