### PR TITLE
Look fo existing UncaughtExceptionHandler when producing KafkaStreams Instance

### LINKED ISSUE #18018: KafkaStreams UncaughtExceptionHandler can only be set before starting the stream
## Describe the bug
It is not possible to use KafkaStreams#setUncaughtExceptionHandler on the injected `KafkaStreams` instance because it is already started by the `KafkaStreamsProducer` managed by kafka-streams Quarkus extension.

### Expected behavior
The kafka-streams extension calls setUncaughtExceptionHandler with an instance of `StreamsUncaughtExceptionHandler` discovered in the application the before the start, much like StateListener and StateRestoreListener

Reported by @andrerigon

### PR DESCRIPTION
**Pull request by andrerigon**
KafkaStreams UncaughtExceptionHandler can only be set before starting the stream. This change allows an user to define a bean that implmements UncaughtExceptionHandler and use that bean, if available,
as the stream's UncaughtExceptionHandler.

Fixes https://github.com/quarkusio/quarkus/issues/18018.

### CODE REVIEW

**Comment by geoand** [comment]
cc @cescoffier @ozangunalp

**Comment by ozangunalp** [comment]
@geoand Thanks for approving it for CI :)

@andrerigon I think changes will work as expected. There is a formatting issue though. If you run a build of `extensions/kafka-streams` module formatter plugin should sort things out.

**Comment by andrerigon** [comment]
Thank you @ozangunalp  and @geoand. I pushed the formatting fix.

**Comment by ozangunalp** [comment]
LGTM. I don't see an easy way of validating that an exception handler is set on `KafkaStreams`.

**Review by cescoffier — APPROVED** [review]

**Comment by andrerigon** [comment]
Thank you all for looking at this.

**Pull request merged**
