### PR TITLE
Rename SmallRye Reactive Messaging extensions to Messaging

### LINKED ISSUE #39279: Renaming reactive messaging to Quarkus messaging
Following the _big rename_ and avoiding user confusion around the "reactive" word, we want to rename "reactive messaging" into "quarkus-messaging". The implementation would not change; it would just be the user-facing name. 

- `quarkus-smallrye-reactive-messaging` =>  `quarkus-messaging`
- `quarkus-smallrye-reactive-messaging-kafka` =>  `quarkus-messaging-kafka`
- `quarkus-smallrye-reactive-messaging-amqp` =>  `quarkus-messaging-amqp`
- `quarkus-smallrye-reactive-messaging-mqtt` =>  `quarkus-messaging-mqtt`
- `quarkus-smallrye-reactive-messaging-pulsar` =>  `quarkus-messaging-pulsar`
- `quarkus-smallrye-reactive-messaging-rabbitmq` =>  `quarkus-messaging-rabbitmq`

Relocations will be configured to prevent user disruption. Thus, applications using the previous artifactIds will still work.

## Tasks

- [ ] Renaming `quarkus-smallrye-reactive-messaging` to  `quarkus-messaging` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-kafka` to  `quarkus-messaging-kafka` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-amqp` to  `quarkus-messaging-amqp` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-mqtt` to  `quarkus-messaging-mqtt` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-pulsar` to  `quarkus-messaging-pulsar` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-rabbitmq` to  `quarkus-messaging-rabbitmq` and setting up relocation
- [ ] Update all documentation (getting started, and reference guides)
- [ ] Updating reactive and virtual thread documentation (the extensions are likely mentioned) 
- [ ] Relocating configuration using `quarkus.reactive-messaging` or `quarkus.reactive.messaging` to `quarkus.messaging`

### PR DESCRIPTION
**Pull request by gsmet**
This one is on top of https://github.com/quarkusio/quarkus/pull/39159 so I will rebase once the previous one is merged.

It renames SmallRye Reactive Messaging to Quarkus Messaging (where it makes sense).

Only the last commit is of interest here, @cescoffier I would appreciate if you could have a look at it.

An overview of the changes is available in the migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#smallrye-reactive-messaging-extensions-renamed-to-quarkus-messaging

Relocations have been put in place, together with fallbacks for the configuration.

I think this is ready if we except this issue that I mentioned in the other PR:

> There are a ton of warnings due to the fallback layer. @radcortez is working on it and hopefully we will have something for the CR1.

Same than for the other PR, I would like us to move quickly on it if it looks generally OK, I can fix the small details later.

Note that for this one, I haven't run the full CI yet so I might adjust a few things later on.

Fixes #39279

/cc @cescoffier @maxandersen @geoand

### CODE REVIEW

**Comment by gsmet** [comment]
CI is green in my fork so it will just need a rebase once the other PR has been merged.

**Review by cescoffier — APPROVED** [review]
Impressive!

**Comment by gsmet** [comment]
This is now ready, let's see how CI behaves.

**Comment by ozangunalp** [comment]
Looks good with my local tests both with new artifacts and relocations. We may want to rename also entries in Feature enum and Capability.

**Comment by gsmet** [comment]
Ah, yes, you are entirely right, this should have been done.

As for capabilities, we need to add a new one as people might have to rely on the old one being present.

**Comment by gsmet** [comment]
I force pushed an update!

**Review by ozangunalp — APPROVED** [review]
I've also checked existing Reactive messaging extensions in Quarkiverse. They seem ok.

**Pull request merged**
