### PR TITLE
Add support for config based SameSite cookies

### LINKED ISSUE #9286: Add support for the SameSite cookie attribute
In undertow sources i saw that there is implemented SameSiteCookieHandler. Please add this same functionality to quarkus

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #9286

### CODE REVIEW

**Comment by geoand** [comment]
The JVM runs seems to be failing with:

```
2020-05-14T05:16:54.7680382Z [ERROR] Errors: 
2020-05-14T05:16:54.7681436Z [ERROR]   DevMojoIT.testThatApplicationRecoversStartupIssue:539->RunAndCheckMojoTestBase.runAndExpectError:86 Â» ConditionTimeout
```

**Review by sberyozkin — APPROVED** [review]
It will also work for `quarkus-oidc` cookies, nice. @pedroigor FYI, I recall you were talking about SameSite in scope of the logout work

**Comment by melloware** [comment]
This does not seem to work for JSESSIONID cookies?

**Comment by melloware** [comment]
I tried every variation...
```
quarkus.http.same-site-cookie.session.value=Strict
quarkus.http.same-site-cookie.jsessionid.value=Strict
quarkus.http.same-site-cookie.JSESSIONID.value=Strict
```

None of them is forcing Undertow to create a SameSite Strict JSESSIONID cookie.

**Pull request merged**
