### PR TITLE
Have the Agroal datasources initialized eagerly

### LINKED ISSUE #4507: Agroal datasource should be initialized eagerly
**Describe the bug**
Currently the datasources are flagged as `@ApplicaitonScoped`, which means they are wrapped by a proxy making them initialized on first use.

This is annoying as
 - we don't respect the configuration of pre-filling the pool on boot
 - we can't validate the connection properties, deferring any failure (however also affected by #4503)
 - it's an overhead

### PR DESCRIPTION
**Pull request by Postremus**
Originally, this was done by @Sanne in https://github.com/quarkusio/quarkus/pull/4504/commits/5209e40b9b40d1bc8a740e9f2d2247c4cc5b7396
But I have no Idea how to cherry pick from a deleted branch..
Created a new commit with the same changes because of this.

Main difference is, that this time around all ITs are passing.

closes #4507

### CODE REVIEW

**Review by Sanne — APPROVED** [review]
that's great to know! Thanks @Postremus

**Comment by dufoli** [comment]
@Sanne @Postremus maybe the same patch must be applied to mongo codebase which is close to agroal now.

**Comment by Sanne** [comment]
what do you mean @dufoli ? I've not followed what is happening with the MongoDB extension, how it that related to Agroal?

cc/ @loicmathieu

**Comment by dufoli** [comment]
Multi tenancy support of Mongo client have introduce a mongo processor very close to agroal processor.

**Comment by Postremus** [comment]
@dufoli ah, I see what you mean. I will test if this change is also possible for the mongo processor.

**Comment by geoand** [comment]
I believe this should be marked as a breaking change, WDYT @Sanne @gsmet ?

**Comment by Sanne** [comment]
Technically I see it as a bugfix, and there was a tracking issue open that
people could watch, but +1 to highlight the change somehow

**Comment by geoand** [comment]
I agree it's the right thing to do, but from a user's perpective it is also breaking (some users could possibly be relying on the fact that the application could start even if the connection to the database wasn't available at startup time).

**Pull request merged**
