### PR TITLE
Upgrade to GraalVM rc15

### PR DESCRIPTION
**Pull request by Sanne**
This is ready now, thanks @mkouba for taking care of the needed changes in the fault tolerance module!

### CODE REVIEW

**Comment by mkouba** [comment]
Hm, we do register all FT annotations for reflection: https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java#L101-L103

**Comment by mkouba** [comment]
I'll try to download rc15 and debug it locally.

**Comment by mkouba** [comment]
I confirm that I get `java.lang.NoSuchMethodException: org.eclipse.microprofile.faulttolerance.Retry$$ProxyImpl.maxRetries()` locally and the generated `io.quarkus.runner.AutoFeature` contains the code to register the declared methods. @Sanne any tips where to look now?

**Comment by Sanne** [comment]
I think the problem is that reflection is registered on the annotation class, while it's invoked on `Retry$$ProxyImpl` ? Just a suspicion, sorry I couldn't look in detail :)

**Comment by mkouba** [comment]
I think that `Retry$$ProxyImpl` is the underlying impl of the annotation instance, provided by JDK so I would expect it to work just fine.

**Comment by geoand** [comment]
I briefly took a look at this and came to same conclusion as @mkouba did (the `NoSuchMethodException`). Could this be a new bug in Substrate perhaps where reflection does not work on annotations (even if they have been registered for reflection)?

**Comment by mkouba** [comment]
I'll try to put together a simple reproducer.

**Comment by mkouba** [comment]
So I found out that we get `NoSuchMethodException` if we try to lookup and invoke a method of an annotation proxy:
```java
// TestAnnotation instance is proxy
TestAnnotation annotation = Some.class.getAnnotation(TestAnnotation.class);
annotation.getClass().getDeclaredMethod("maxRetries").invoke(annotation);
```
(this is what SmallRye FT does BTW)

Whereas this works fine:
```java
TestAnnotation annotation = Some.class.getAnnotation(TestAnnotation.class);
TestAnnotation.class.getDeclaredMethod("maxRetries").invoke(annotation);
```
However, this fails with RC14 too. See my reproducer: https://github.com/mkouba/substrate-annotation-reflection. So I wonder why only RC15 triggers the problem?

**Comment by mkouba** [comment]
So it seems that the way the classes are initialized is alittle bit more conservative now: 
[ Conservative class initializaiton for native image ](https://github.com/oracle/graal/commit/24a4e620fb5291846048b10f240df29a5832aa8d).

I'm not sure whether this could be the cause of our issue but it looks suspicious. There's another related commit in the master: [ Initialize safe classes automatically](https://github.com/oracle/graal/commit/6ac150c842f62dbfe217fb0e610c39c16e68b237). It would be nice if somehow who knows how to build the graalvm could try the latest master.

Also note that there are some new options: `-H:+PrintClassInitialization`, `-H:-EagerlyInitializeClasses`, ...

I've also created https://github.com/oracle/graal/issues/1167.

**Comment by mkouba** [comment]
@Sanne CI is all green ;-).

**Comment by Sanne** [comment]
@mkouba awesome! thanks.

I see it's a major upgrade for fault-tolerance. Maybe you should send that PR independently first, then we rebase this one? That would get both changes mentioned in the changelog and release notes, up to you of that's worth it.

**Comment by mkouba** [comment]
> That would get both changes mentioned in the changelog and release notes, up to you of that's worth it.

MP FT integration is more or less untested. So I'd prefer not mention it in the changelog. @kenfinnigan WDYT?

**Comment by kenfinnigan** [comment]
I'm fine with it not being mentioned specifically in release note.

**Comment by Sanne** [comment]
Cool. rebased it to test fresh tests as it was aging a bit.

This is read to me merged now, I'll change the labels. Anyone could approve?

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
