### PR TITLE
Update Netty to 4.1.72

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by cescoffier** [comment]
The update fixes one moderate CVE.

**Comment by sberyozkin** [comment]
@cescoffier Hi, can it be backported to 2.2 ?

**Comment by cescoffier** [comment]
No, at least not without some nasty cherry-picking.

**Comment by sberyozkin** [comment]
@cescoffier Thanks for the clarification

**Pull request merged**
