### PR TITLE
Fix combination of remote-dev and Jib created containers

### LINKED ISSUE #26113: Remote-dev mode not supported with container images created with Jib extension
### Describe the bug

[Remote-dev ](https://quarkus.io/guides/maven-tooling#remote-development-mode) works perfectly using the docker file generated by the a Quarkus project. But when trying the same thing with the `containers-jib` extension, once deployed inside a pod we get this error : 

```
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2022-06-14 11:52:06,160 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:50)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:45)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: java.nio.file.AccessDeniedException: /home/jboss/dev
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
	at io.quarkus.deployment.mutability.DevModeTask.extractDevModeClasses(DevModeTask.java:104)
	at io.quarkus.deployment.mutability.DevModeTask.createDevModeContext(DevModeTask.java:78)
	at io.quarkus.deployment.mutability.DevModeTask.main(DevModeTask.java:53)
	... 8 more

```

### Expected behavior

remote-dev should work and the local project should be able to connect to the remote pod/container

### Actual behavior

Pod can not be started due to file.io exception

### How to Reproduce?

container image you can use to reproduce the bug : quay.io/sebastienblanc0/remote-dev-test:1.0.0-SNAPSHOT

Don't forget to set the env var : `QUARKUS_LAUNCH_DEVMODE=true`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #26113

### CODE REVIEW

**Comment by geoand** [comment]
I'm adding the backport label, but only the second commit should be backported.

**Comment by gsmet** [comment]
> I'm adding the backport label, but only the second commit should be backported.

This is not ideal as I don't really check the comments when backporting so I might miss it. If this goes in today and I backport it tonight, I will probably think about it but let's not make it a habit as I'm pretty sure I will backport things that shouldn't be :).

**Comment by geoand** [comment]
Completely understood.

**Comment by geoand** [comment]
Can I get a review of this please?

Thanks!

**Review by gastaldi — APPROVED** [review]
LGTM, I wonder if there is an easy way to add a test for this

**Comment by geoand** [comment]
I will have a look at that at some point as we could definitely use such a test

**Comment by gsmet** [comment]
As requested, only the second commit has been backported to 2.10.2.Final.

**Comment by geoand** [comment]
Thanks 🙏

**Pull request merged**
