### PR TITLE
X will open editor on current working directory as a fallback

### LINKED ISSUE #33060: add open-editor ('e') to devmode
### Description

with `quarkus dev` I constantly end up doing: `git clone myproject; cd myproject; quarkus dev`

from here I can use 'w' to open webui and 'd' for devui.

Would be awesome to have 'e' that would open identifiable IDE just like we have 'x' to open stacktrace in IDE.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by maxandersen**
fixes #33060 

realized we already have the mechanics to open IDE's thus why not have it open on default project if no exceptions found/recorded yet?

@geoand @stuartwdouglas wdyt?

### CODE REVIEW

**Comment by geoand** [comment]
Would it not be more clean to have it as a separate option?

**Comment by maxandersen** [comment]
so grap 'e' to open editor on current project?  or maybe shift+X ?  to not grab more letters than necessary?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I like it. There are a limited number of shortcuts we can provide, so I am fine with overriding them like this.

**Comment by geoand** [comment]
🆗

**Comment by geoand** [comment]
This needs a formatting fix (the exact command to run is in the error message)

**Comment by gsmet** [comment]
I force pushed a fix for the formatting issue.

**Pull request merged**
