### PR TITLE
Integrate Keycloak Admin Client with TLS registry

### LINKED ISSUE #37243: Enhance keycloak-admin-client extension to support TLS trust and key stores
### Description

When connecting to a keycloak instance that has TLS encryption enabled, for example when running in Openshift with a certificate provided by the Service CA, the certificate cannot be provided to the extension and the only option is to set it system-wide which requires elevated privileges to do.

After #37206 is possible to disable TLS verification altogether, but that may not be desired for other extensions. 

In addition to that mutual TLS is not possible at all because we cannot set client certificate.

### Implementation ideas

Should be something similar to what has been done for oidc client extension in #18012 .

### PR DESCRIPTION
**Pull request by michalvavrik**
- Closes: https://github.com/quarkusio/quarkus/issues/37243

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]

**Comment by michalvavrik** [comment]
Thanks @sberyozkin; cc @geoand in case you wanna check, I configure REST client with TLS registry just as you did in https://github.com/quarkusio/quarkus/pull/41153/ so I expect it's alright

**Comment by michalvavrik** [comment]
sorry @sberyozkin , I didn't know there are native tests so I didn't run them. it seems that Keycloak's `org.keycloak.admin.client.ClientBuilderWrapper#create` must be initialized it at runtime, so I'll stop using it and request your review again.

**Comment by michalvavrik** [comment]
Changes inside Keycloak Admin Resteasy Client are due to the fact that I changed time when we set Keycloak Rest client provider (from static to runtime). This meant that during static init when native image is build this was executed: https://github.com/keycloak/keycloak/blob/75973157aa10bdbcb04d82af490a495dbb0b35a7/integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java#L46
Which meant that static initialization block here was executed https://github.com/keycloak/keycloak/blob/75973157aa10bdbcb04d82af490a495dbb0b35a7/integration/admin-client/src/main/java/org/keycloak/admin/client/ClientBuilderWrapper.java#L11 which for failed (I didn't spend time looking why, it's not important as we don't need that class at all). So I just made sure that we don't call https://github.com/keycloak/keycloak/blob/75973157aa10bdbcb04d82af490a495dbb0b35a7/integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java#L48 considering we don't use it anyway.

**Review by geoand — APPROVED** [review]
Nice!

**Review by sberyozkin — APPROVED** [review]
Thanks @michalvavrik

**Pull request merged**
