### PR TITLE
Introduce support for Spring Web

### PR DESCRIPTION
**Pull request by geoand**
Spring Web REST annotations can now be used instead of JAX-RS ones for defining REST endpoints

### CODE REVIEW

**Comment by geoand** [comment]
Some dependency issue, will fix ASAP

**Comment by geoand** [comment]
@gsmet could you take a look when you have the time?

**Comment by patriot1burke** [comment]
Great work!  I don't have any suggestions for improvement.

**Comment by geoand** [comment]
Thanks a lot @patriot1burke!

**Review by n1hility — APPROVED** [review]
This looks great. I only have two comments that are really future tasks

1. We should probably change the project creation generation to be influenceable so that when the user picks spring they get a spring greeting 
2. We should probably think about whether its worth creating a spring API only dependency, that way we don't end up with issues caused by spring implementation classes conflicting with our code or inadvertently getting picked up by the native-image generation process. It also would help establish what APIs we do and don't support.

**Comment by n1hility** [comment]
https://github.com/quarkusio/quarkus/issues/3436

**Comment by geoand** [comment]
@n1hility added #3437 for your other point. I'll probably have someone from my team have a look since I think it's a good first issue

**Pull request merged**
