### PR TITLE
Update to Apache Http Client 4.5.13

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Maybe add to Dependabot? Or is there a reason to not be in there?

**Comment by sberyozkin** [comment]
Hi @gastaldi sorry, sure I'll update the dependabout config, this build has failed (likely for unrelated reason), but I'll update the PR anyway

**Comment by gsmet** [comment]
This issue is that you have `${httpclient.version}` used for other artifacts that are not in the Dependabot config. That's why it's not updated.

Now I'm not entirely sure how to update this given `httpcore` probably needs to be synced.

**Comment by sberyozkin** [comment]
@gsmet, @gastaldi  interesting, `httpcore` has a different version, may be adding `httpclient-cache` and ``httpclient-mime` can make dependabot happy ? Pity it is not possible to use a wildcard :-), `dependency-name: org.apache.httpcomponents:http*`

**Comment by gsmet** [comment]
Wildcards are supposed to be supported now.

And yes, that would make Dependabot happy. What I was mentioning is that there's a good chance you need to update httpcore when upgrading the httpclient artifacts.

Anyway, let's do it in another PR, I would like to get this one CI-tested and backported.

**Comment by sberyozkin** [comment]
@gsmet I see what you meant about `http-core` :-). Tricky, I was not sure about the wildcard as it is the same group id but indeed, it can be reviewed later. thanks

**Comment by gsmet** [comment]
Rebased to get a CI fix.

**Comment by gastaldi** [comment]
Dumb question: In https://hc.apache.org/downloads.cgi it says that the latest is 5.0.3 - why we aren't using that?

**Comment by sberyozkin** [comment]
Hey @gastaldi I haven't thought about 5.0.3, and indeed I'm not sure about the implications

**Comment by rsvoboda** [comment]
@gsmet What is this upgrade fixing for 1.7 branch?

**Comment by gsmet** [comment]
See https://issues.redhat.com/browse/QUARKUS-490

**Pull request merged**
