### PR TITLE
Fix various issues when accessing context objects

### LINKED ISSUE #28863: Reactive REST client with multiple content-type providers fails with untyped response
### Describe the bug

When using a REST client with multiple content-type providers (e.g. JSON & CBOR), responses without a `Content-Type` header fail with `No RESTEasy Reactive request in progress`.

This happens even when the client interface is annotated with `@Produces("application/json")`.

[Zulip discussion](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/RestClient.20without.20a.20.40Producer)

### Expected behavior

The response is decoded according to the value provided in `@Produces`.

If multiple types are provided in the `@Produces` annotation then an appropriate error should be thrown.

We are using the built client to interact with external services so we will not control the responses and need proper handling and when it fails we need a proper error message.

### Actual behavior

The call fails with the error quoted above.

### How to Reproduce?

1. Execute the tests (e.g. `mvn install`) to see the failure.

If you uncomment `GreetingResourceTest.kt:32`, providing an explicit content-type, the issue goes away.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/9871068/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

macOS 12.6

### Output of `java -version`

OpenJDK 17.0.1

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #28863

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
I tried these changes by running the reproducer to confirm the issue is fixed, but unfortunately, the reproducer is still not working, though the exception is now:

```
-250159f55578-1: javax.ws.rs.ProcessingException: com.fasterxml.jackson.core.JsonParseException: Illegal length for VALUE_STRING: 2480750516282419045
 at [Source: (ByteArrayInputStream); byte offset: #9]
        (Coroutine boundary)
        at org.acme.GreetingResource.hello$suspendImpl(GreetingResource.kt:24)
        at org.jboss.resteasy.reactive.server.runtime.kotlin.CoroutineInvocationHandler$handle$1.invokeSuspend(CoroutineInvocationHandler.kt:41)
Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.core.JsonParseException: Illegal length for VALUE_STRING: 2480750516282419045
 at [Source: (ByteArrayInputStream); byte offset: #9]
        at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:70)
        at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:160)
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:185)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:104)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:35)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:31)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:229)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:279)
```

If we uncomment the line 23 in `GreetingResourceTest.kt` (`.withHeader("Content-Type", "application/json")`, the test passes regardless if we apply the changes of this pull request or not. 

Perhaps, the reproducer is wrong and it should always provide the header `Content-Type: application/json`, but why the reproducer fails with the above exception with these changes and no content type is set? :/

Also, why the request context is lost when running a coroutine in Kotlin? Sorry if this is a dumb question, I don't know about Kotlin very much... I tried to inject a request context instance in the hello resource:

```kotlin
@GET
@Produces(MediaType.TEXT_PLAIN)
suspend fun hello(@Context request:Request): String {
```

And the request is correctly injected, so the request context is active when running the method.

**Comment by geoand** [comment]
I know the reproducer continues to fail, but that is a reproducer issue.

**Comment by geoand** [comment]
> Also, why the request context is lost when running a coroutine in Kotlin

This is a very good question. It should not be lost - we have tests that do ensure this, so there is probably something more deep going on that requires even more investigation.

But in any case, this change does make sense.

**Comment by Sgitario** [comment]
> I know the reproducer continues to fail, but that is a reproducer issue.

My point is that when using the content type `application/json`, everything works fine, but when there is no content type and applying these changes, it fails with a JSON parser exception. 

The content type resolution should deduct that the body is a JSON (because NestedAPI is annotated with `@Consumes(MediaType.APPLICATION_JSON)`) and hence both scenarios should behave the same, right? :/

**Comment by geoand** [comment]
I'll have to take another look

**Comment by geoand** [comment]
> My point is that when using the content type application/json, everything works fine, but when there is no content type and applying these changes, it fails with a JSON parser exception.

> The content type resolution should deduct that the body is a JSON (because NestedAPI is annotated with @Consumes(MediaType.APPLICATION_JSON)) and hence both scenarios should behave the same, right? :/

That's not how the spec works for better or worse. When no content type is specified, then all the  providers are checked. 
There is 0️⃣ chance I am going to look into changing this as it is guaranteed to break everything.

**Comment by geoand** [comment]
The Kotlin issue how now been addressed

**Review by Sgitario — APPROVED** [review]
I see now what it fails after these changes: Resteasy Reactive is correctly selecting the user COBRProvider provider because it's defined as:

```java
@Provider
@Consumes({"*/*"})
@Produces({"*/*"})
public class JacksonCBORProvider
```

So, this is a user issue and there is nothing we can do to amend that.

Many thanks @geoand !

**Comment by geoand** [comment]
Thank you for scrutinizing the PR!

**Pull request merged**
