### PR TITLE
Update wildfly-elytron version to 2.0.0.Alpha6

### PR DESCRIPTION
**Pull request by sberyozkin**
@rsvoboda FYI, thanks for letting me know about this version. Will update accordingly should the next/final version become available in time for 1.3.0

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
Rebased to trigger CI.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@sberyozkin at least the native image failure looks related.

**Comment by sberyozkin** [comment]
@gsmet I see 
```
2020-01-23T12:24:56.0041196Z java.io.IOException: Cannot run program "/home/vsts/work/1/s/extensions/mongodb-client/runtime/target/extract-00b9d603-2bca-4ca0-b70b-afcb36788367extractmongod": error=26, Text file busy
2020-01-23T12:24:56.0041929Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
2020-01-23T12:24:56.0042398Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
2020-01-23T12:24:56.0044258Z 	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:213)
2020-01-23T12:24:56.0051892Z 	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
2020-01-23T12:24:56.0052499Z 	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
2020-01-23T12:24:56.0052952Z 	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
2020-01-23T12:24:56.0063275Z 	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
2020-01-23T12:24:56.0064075Z 	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
2020-01-23T12:24:56.0064562Z 	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
2020-01-23T12:24:56.0065013Z 	at io.quarkus.mongodb.MongoTestBase.startMongoDatabase(MongoTestBase.java:62)
```

May be I've missed something...

**Comment by gsmet** [comment]
I was talking about the native failure:
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: char[].clone(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.wildfly.security.password.interfaces.MaskedPassword.createRaw(MaskedPassword.java:224)
	... 7 more
```

I pushed a fix to your branch. Let's wait for what CI has to say.

**Comment by sberyozkin** [comment]
Some strange Windows build issue, possibly unrelated

**Pull request merged**
