### PR TITLE
Prevent QuarkusErrorServlet from returning a 405 status instead of 500

### LINKED ISSUE #3017: RestEasy returns 405 instead of 500 for POST
**Describe the bug**
405 is returned for POST requests on internal server errors.
It works fine with GET

**Expected behavior**
500 should be returned

**To Reproduce**
- clone it and start it:
```
git clone https://github.com/michalszynkiewicz/quarkus-resteasy-invalid-status-code reproducer && cd reproducer
mvn clean package
java -jar target/foo-1.0-SNAPSHOT-runner.jar
```
- query:
```
curl -v localhost:8080/foos -X POST -H "Content-Type: text/plain" -H "Accept: text/plain"
```

**Environment (please complete the following information):**
Quarkus 0.18.0, java 8

### PR DESCRIPTION
**Pull request by gwenneg**
Resolves #3017

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I think this should be changed to just implement Servlet rather than HttpServlet, so it will work for all methods. Even though this change would fix it for POST other methods such as PUT and DELETE would still be a problem.

**Comment by gwenneg** [comment]
Ok I'll update the PR, thanks!

**Comment by michalszynkiewicz** [comment]
@gwenneg could you also create a test for it?

**Comment by gwenneg** [comment]
@michalszynkiewicz Ok, I'll do that.

**Review by n1hility — CHANGES_REQUESTED** [review]
As @stuartwdouglas mentioned above this will only fix POST methods, and really it should cover all of them. Instead of doXXX you could probably just extend service() and handle all methods.

**Comment by gwenneg** [comment]
I just pushed some PR changes before seeing your comment @n1hility and I was about to ask about how to replace `HttpServlet` with `Servlet`, but you just gave me an interesting idea. I'll work on this again and update the PR soon.

**Comment by gwenneg** [comment]
@n1hility This last version should be closer to what you asked for.

**Comment by gsmet** [comment]
It looks good to me but it seems it's still extending `HttpServlet` and I see @stuartwdouglas mentioned `Servlet`.

@stuartwdouglas @n1hility could you check the latest version?

I would like to have this one in 0.19.0.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
