### PR TITLE
Test framework: Use JBoss Marshalling cloner

### LINKED ISSUE #15892: A @QuarkusTest with a ParameterResolver that return a java record, throws an exception
## Describe the bug

During a QuarkuTest, when using a junit "ParameterResolver" that return a java record with at least one field, xstream return this error:

```
com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : java.lang.UnsupportedOperationException
cause-message       : can't get field offset on a record class: private final java.lang.String com.example.TestRecord.test
class               : com.example.TestRecord
required-type       : com.example.TestRecord
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /com.example.TestRecord/test
line number         : 2
version             : 1.4.15
-------------------------------
```

The problem in quarkus is at 
`io.quarkus.test.junit.internal.XStreamDeepClone.doClone(XStreamDeepClone.java:49)`

As far as I understand, this class use xstream to just create a copy of the object (the java record) in the Quarkus ClassLoader.
If it's the only usage, i think we can use another library that support records (and maybe use json instead of XML).

what do you think?

The cause is:
```
java.lang.UnsupportedOperationException: can't get field offset on a record class: private final java.lang.String com.example.TestRecord.test
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:648)
	at com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider.getFieldOffset(SunUnsafeReflectionProvider.java:105)
```

## To Reproduce

It's very simple.

1- Create a Java record, with at least one field `record TestRecord(String test)`

2- Create a ParameterResolver that return the record `new TestRecord("my test")`

3- Create a quarkus test that use that ParameterResolver
eg:
```
@QuarkusTest
@ExtendWith(TestRecordResolver.class)
public class QuarkusRecordTest {
  @Test
  public void test(TestRecord record) {
    assert record != null;
  }

}
```

### Output of `uname -a` or `ver`
Darwin MacBookPro.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

### Output of `java -version`
openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)

### Quarkus version or git rev
Quarkus 1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven 3.6.3 

## Additional context
I reproduced it in a new empty project.
I can post it, if need, but it's super simple.

This occurs from java 15, for this reason
[https://mail.openjdk.java.net/pipermail/amber-dev/2020-June/006241.html](https://mail.openjdk.java.net/pipermail/amber-dev/2020-June/006241.html)
[https://medium.com/@atdsqdjyfkyziqkezu/java-15-breaks-deserialization-of-records-902fcc81253d](https://medium.com/@atdsqdjyfkyziqkezu/java-15-breaks-deserialization-of-records-902fcc81253d)

Complete [stacktrace.txt](https://github.com/quarkusio/quarkus/files/6172338/stacktrace.txt)

### PR DESCRIPTION
**Pull request by dmlloyd**
Remove usage of xstream or serialization for cloning, and use the JBoss Marshalling cloner instead.

Fixes #15892.

### CODE REVIEW

**Review by gsmet — COMMENTED** [review]
Oh, that's some nice cleanup!

**Review by geoand — APPROVED** [review]
Love it!

I wish I had thought of JBoss Marshaling when we added this

**Comment by geoand** [comment]
Also, I'm pretty sure this will close more outstanding issues

**Comment by gsmet** [comment]
@dmlloyd I was able to reproduce the problem locally with `mvn clean install -Dstart-containers -Dtest-containers` in the IT submodule.

In:

```java
@QuarkusTest
public class TransactionalUniAsserterTest {

    private static final AtomicBoolean ASSERTER_USED = new AtomicBoolean();

    @RunOnVertxContext
    @Test
    public void testTransactionalUniAsserter(TransactionalUniAsserter asserter) {
        assertNotNull(asserter);
        asserter.assertThat(Panache::currentTransaction, transaction -> {
            ASSERTER_USED.set(true);
            assertNotNull(transaction);
            assertFalse(transaction.isMarkedForRollback());
            asserter.putData("tx", transaction);
        });
        asserter.assertThat(Panache::currentTransaction, transaction -> {
            assertNotNull(transaction);
            assertFalse(transaction.isMarkedForRollback());
            assertNotEquals(transaction, asserter.getData("tx"));
        });
    }

    @AfterAll
    static void afterAll() {
        assertTrue(ASSERTER_USED.get());
    }

}
```

we end up with `ASSERTER_USED` being false.

**Comment by dmlloyd** [comment]
It looks like it's having a problem because the `TransactionalUniAsserter` is getting cloned, and the clone, well, just doesn't work right. I'm digging into the how/why now but it might be a tricky one to solve.

**Review by geoand — APPROVED** [review]

**Comment by holly-cummins** [comment]
Ohhhh, nice. The xstream serialization was becoming increasingly non-viable, since it doesn't work on Java 17+, and that's our minimum Java level. This possibly means I don't need to pursue my epic test classloading rewrite. (https://github.com/quarkusio/quarkus/pull/34681) I was going to pick it up tomorrow, too (although in fairness, it's been Real Soon Now for like a year). 

Here's my (partial) list of issues that I think this might resolve: 
- https://github.com/quarkusio/quarkus/issues/40148
- https://github.com/quarkusio/quarkus/issues/36812

Thinking about it more, I think "load the tests with the classloader we intend to use to run them" is probably still a nice aspiration, and trying to avoid serialization could have some broader benefits. I think the following issues probably are *not* fixed by this change, and would need the epic test classloading rewrite (ETCR):

- https://github.com/quarkusio/quarkus/issues/27821
- https://github.com/quarkusio/quarkus/issues/22611
- https://github.com/quarkiverse/quarkus-pact/issues/73

**Comment by maxandersen** [comment]
Xstream goes poof? That's excellent news.

**Comment by dmlloyd** [comment]
I think that cleaning up the class loader situation is still a worthy goal.

**Comment by holly-cummins** [comment]
I'm planning to add a test which reproduces the failure @edeandrea and I saw, so we can assess how common it is. If it's a common one, we should maybe consider temporarily reverting this while we wait for the JUnit upgrade. But in the meantime, some tests which *were* failing because of the broken xstream serialization are now passing (yay!). So I've raised a PR to un-disable them: https://github.com/quarkusio/quarkus/pull/40749

**Pull request merged**
