### PR TITLE
Allow injecting the authorization client

### LINKED ISSUE #16972: Allow direct access to the keycloak PolicyEnforcer or the AuthzClient
## Description

When using quarkus-keycloak-authorization, it would be nice when the AuthzClient or the PolicyEnforcer could be injected, or at least be retreived from the KeycloakPolicyEnforcerAuthorizer.

This way, it's not necessary to create a second AuthzClient for configuring the authorization from within the application. Sometimes its also necessary to get the user entitlements for collection-rest-endpoints that deliver all items a user has access to.

## Implementation ideas

First Idea: Create the PolicyEnforcer as a bean and also inject it in the KeycloakPolicyEnforcerAuthorizer.
Second Idea: Just keep the PolicyEnforcer as a field on the KeycloakPolicyEnforcerAuthorizer with a public getter.

Regards, Adrian

### PR DESCRIPTION
**Pull request by pedroigor**
Fixes #16972.

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi @pedroigor 
It looks good, I did not realize it was wrapped internally by policy enforcer - I'm just wondering though, since we also have `quarkus-keycloak-admin-client` - which may also get this injection supported - not yet - but may be it will, would it make sense to inject `PolicyEnforcer` instead - the users can then get the client out of it or do something else with the enforcer - that would be more `keycloak-authorization` specific and would avoid possible future conflicts with `quarkus-keycloak-admin-client` ?

**Comment by sberyozkin** [comment]
Or is that a different client ?

**Comment by sberyozkin** [comment]
Yeah it must be :-)

**Comment by pedroigor** [comment]
Yes, it is a different client. We could expose the `PolicyEnforcer` but I'm not sure if it is a good thing to do. The reason being that it is really internal stuff and people should rely on what the extension providers on top of it.

But who knows, we can re-evaluate this if we get strong requirements for doing that.

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@pedroigor Makes sense, I just got confused :-), you are right, I looked at `PolicyEnforcer` it is quite internal :-)

**Comment by pedroigor** [comment]
@sberyozkin Why tests did not run?

**Comment by sberyozkin** [comment]
@pedroigor yeah - it is amazing how fast the incremental builds are :-)
thanks to @famod and @gsmet efforts

**Pull request merged**
