### PR TITLE
Add Vertx JsonObject and JsonArray support to RESTEasy Reactive

### LINKED ISSUE #14668: Vert.x JsonObject in RESTEasy Reactive response has extra nesting level
**Describe the bug**
When RESTEasy Reactive plugin should convert Vert.x JsonObject into application/json response, it produces extra nesting level with key "map". 
This occurs either with quarkus-resteasy-reactive-jackson or with quarkus-resteasy-reactive-jsonb extention.
But with simple RESTEasy as well as Reactive routes approach response is {"key":"value"} as expected.

**Expected behavior**
It is expected that response is just 
```
{"key":"value"}
```

**Actual behavior**
Response body is 
```
{"empty":false,"map":{"key":"value"}}
```

**To Reproduce**

[Simple reproducer]( https://github.com/sashamc/quarkus-resteasy-reactive-jsonobject-issue.git)

1. Include quarkus-resteasy-reactive-jackson or quarkus-resteasy-reactive-jsonb extention dependency into pom.xml (or create project template at code.quarkus.io with extentions: RESTEasy Reactive, RESTEasy Reactive JSON-B, RESTEasy Reactive Jackson),
2. Create an JAX-RS resource class (@Path("/hello"), with method annotated @GET @Path("{ami}") @Produces(MediaType.APPLICATION_JSON) ,
3. Method signature: public JsonObject helloAmi(@RestPath String ami) ,
4. And body: return new JsonObject().put("ami", ami);
5. In terminal run command: curl "http://localhost:8080/hello/john" -w "\n".

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: "mac os x", version: "10.15.7"; Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64
 - Output of `java -version`: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
 - GraalVM version (if different from Java): 
 - Quarkus versions: 1.11.1.Final, 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #14668

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Comment by FroMage** [comment]
Why is this tied to jackson and jsonb and not just in quarkus-resteasy-reactive which already depends on vertx?

**Comment by geoand** [comment]
Because these providers can't work without Jackson databind on the classpath - which we purposely don't include with the internal vertx dependencies

**Comment by FroMage** [comment]
Oh OK, I didn't know that.

**Comment by geoand** [comment]
Yeah, it's a non obvious detail 😎

**Pull request merged**
