### PR TITLE
Change order for hal extension

### PR DESCRIPTION
**Pull request by Sgitario**
Fix failure for the CI job: https://github.com/quarkusio/quarkus/actions/runs/2317143363

### CODE REVIEW

**Comment by Sgitario** [comment]
@geoand I haven't been able to reproduce the CI error in my local machine, do you have any tips to confirm that this pull request will fix the CI failures?

**Comment by Sgitario** [comment]
@geoand I haven't been able to reproduce the CI error in my local machine, do you have any tips to confirm that this pull request will fix the CI failures?

**Comment by geoand** [comment]
I would wipe out my local.m2/repository directory and try.

There is likely some leftover that causes the build to pass on your machine

**Comment by Sgitario** [comment]
> 

But it also passes in the CI for pull requests :/

**Comment by geoand** [comment]
> But it also passes in the CI for pull requests :/

Yeah... Not sure what's going on there

**Comment by Sgitario** [comment]
> > But it also passes in the CI for pull requests :/
> 
> Yeah... Not sure what's going on there

I still could not reproduce the error even after having removed my maven repository.
Anyway, I think this PR should fix it.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
There's very little chance this is the right fix. The build should be constrained by dependencies, not by the order in the pom file. It will especially go wrong with any sort of parallel build.

**Pull request merged**
