### PR TITLE
Smallrye RM 3.14.0 with Kafka Companion test resource

### PR DESCRIPTION
**Pull request by ozangunalp**
- Bump Smallrye Reactive Messaging to [3.14.0](https://github.com/smallrye/smallrye-reactive-messaging/releases/tag/3.14.0)
- Added kafka-companion to quarkus-test-framework
- Fix for Apicurio dev service url

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by edeandrea** [comment]
I see this is targeted for 2.8 (the fix for the Apicurio registry).

That has been broken on main for almost a week now. Does that mean the break will make it into a subsequent 2.7.x release while the fix will have to wait until 2.8?

**Comment by ozangunalp** [comment]
@edeandrea 2.7.x releases don't have the apicurio registry dev service regression, which is introduced in #23048.

**Comment by edeandrea** [comment]
Thanks for confirming!

**Comment by gsmet** [comment]
I backported the commit [Fix apicurio dev service registry url](https://github.com/quarkusio/quarkus/pull/23733/commits/6d5abfdd92a0dea1e59503133d1ed3256e31296f)

**Comment by gsmet** [comment]
Hum, in the end, no, it doesn't help fixing the issue I have with the backport.

**Pull request merged**
