### PR TITLE
Add Freemarker extension

### PR DESCRIPTION
**Pull request by vsevel**
This adds an extension providing support for _Freemarker_, including native support.
It brings 2 CDI beans: _Freemarker_ `Configuration` and `Template`, expose common configuration options plus support for custom directives.
This work has been largely inspired by (including copying some snippets of code) from @carlosthe19916 's work in the context of https://github.com/apache/camel-quarkus/issues/223.
The PR is complete with integration testing and a new documentation guide.
see also https://groups.google.com/g/quarkus-dev/c/M8EcFBFkj-o/m/Sv6RW_ZeBgAJ

/cc @ppalaga

### CODE REVIEW

**Comment by aloubyansky** [comment]
@vsevel we've created https://github.com/quarkiverse/quarkiverse/wiki in the meantime. Would you mind contributing the extension there instead? Let me know if you want me to create a repo for it. And thanks for another great contribution!

**Comment by sberyozkin** [comment]
@vsevel HI Vincent, how are you, how does it relate to `Qute` ? Can Qute be used to work with `Freemarker` ? CC @mkouba

**Comment by vsevel** [comment]
hello @sberyozkin. great thanks :)

> how does it relate to `Qute`

it does not, apart from being also a templating engine.

> Can Qute work with Freemarker

they are independent. the freemarker extension is for people that have invested in freemarker (with some code or knowledge) and want to stay with it. for instance people that want to migrate a freemarker app to quarkus, without changing the templating engine.

for greenfield applications, qute is probably a great choice in the quarkus universe.

**Comment by vsevel** [comment]
@aloubyansky 

> Let me know if you want me to create a repo for it. 

I would rather not. should I move the extension to the https://github.com/quarkiverse/quarkiverse/ repo? is it ready to host extensions (with ci and everything)?

**Comment by aloubyansky** [comment]
Ah, no, we create separate repos for extension projects under the quarkiverse org. Which is what I proposed. We will also provide release and publishing automation.

**Comment by vsevel** [comment]
@aloubyansky 

> Let me know if you want me to create a repo for it.

I misread what you said. sorry for the confusion. yes if it is the new way of doing, please create the repo, and instruct me on how to get started. thanks.

**Comment by aloubyansky** [comment]
Sure, no problem, we just started that org and haven't properly presented it yet, so no wonder it sounds confusing at times.
Basically you can pick a name that you like that starts with the `quarkiverse-` prefix, e.g. quarkiverse-freemarker. I'll create the repo and send you an invite to become the admin. We've gathered some basic info here https://github.com/quarkiverse/quarkiverse/wiki feel free to ping me on zulip if you have further questions. Thanks.

**Comment by vsevel** [comment]
@aloubyansky `quarkiverse-freemarker` sounds perfect. great idea by the way.

**Comment by aloubyansky** [comment]
@vsevel done! You should have received an invite. One thing we are about to add is a common parent POM https://github.com/quarkiverse/quarkiverse-parent @gastaldi should be able to release it early next week.

**Comment by mkouba** [comment]
If I understand it correctly this PR will be moved under quarkiverse. Feel free to reopen if I'm wrong...

**Pull request closed without merging**
