### PR TITLE
Update to Vert.x 3.8.2 and friends

### PR DESCRIPTION
**Pull request by cescoffier**
Update to Vert.x 3.8.2, Axle 0.0.10, Rx Java 2.2.13, SmallRye Reactive Streams Ops 1.0.10 and SmallRye Reactive Messaging  1.0.8

Also, update Reactive Streams to 1.0.3

### CODE REVIEW

**Review by geoand — APPROVED** [review]
The dependency trees look good to me

**Comment by geoand** [comment]
@cescoffier I think my substitutions need to go in with this. The native tests are failing with some jackson related errors

**Comment by cescoffier** [comment]
@geoand we may need your PR to be included:
```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field io.vertx.core.json.Json.mapper is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing io.vertx.core.json.jackson.JacksonCodec.createParser(JacksonCodec.java:85)
```

**Comment by cescoffier** [comment]
> Would you like to cherry pick my commit into this PR?

Yes, that would be great

**Comment by cescoffier** [comment]
I will give you push access.

**Comment by cescoffier** [comment]
@geoand You should receive an invite soon.

**Comment by geoand** [comment]
Cool, will push as soon the build is done locally

**Comment by geoand** [comment]
@cescoffier PR updated. Let's see what CI has to say about it.

**Comment by cescoffier** [comment]
@geoand Party time!

**Comment by geoand** [comment]
:tada: :birthday:

**Comment by gsmet** [comment]
Nice! Thanks @vietj @cescoffier @geoand !

**Pull request merged**
