### PR TITLE
Upgrade Narayana to 5.12.7.Final

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by NitishKumar06** [comment]
Hey @gsmet , May I know how were you able to find the exact location of the file?

**Comment by mmusgrov** [comment]
@gsmet I published artifacts for Narayana 5.13.0 over the weekend so I will most likely want to follow up with that after I've completed all of my sanity checks. Version 5.13.0 removes support for Java 8 and JacORB and adds support for Java 17.

**Comment by Sanne** [comment]
@mmusgrov that's nice, but we could already merge this one too, no?

**Review by Sanne — APPROVED** [review]

**Comment by mmusgrov** [comment]
Yes Sanne, I just wanted to let you know that a new version is imminent.

**Pull request merged**
