### PR TITLE
Add a resteasy-jaxb extension

### PR DESCRIPTION
**Pull request by gsmet**
This should solve the problems of Apache Camel: they have JAXB
annotations in their model and it triggers JAXB inclusion even if they
don't want to use it.

@gnodet this should solve your issues with JAXB being included even if you don't want it. You now have to depend on `quarkus-resteasy-jaxb` if you want to have JAXB support for RESTEasy.

/cc @geoand 

Supersedes https://github.com/quarkusio/quarkus/pull/3866

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Makes sense!

**Comment by geoand** [comment]
Something is wrong with CI... It's not running PRs

**Comment by gsmet** [comment]
Yeah, CI apparently trusts me more than I do :).

**Comment by gsmet** [comment]
I force pushed and still no CI.

**Comment by geoand** [comment]
@gsmet CI is green. Should we merge or do you want extra confirmation?

**Comment by gsmet** [comment]
I think we want that anyway so let's merge it.

/cc @lburgazzoli

**Comment by geoand** [comment]
Done

**Pull request merged**
