### PR TITLE
Fix not-found links when management enabled

### LINKED ISSUE #44639: When using the management interface, URLs for management pages in Dev UI are incorrect
### Describe the bug

When using the management interface, the URLs on the 404 page for any management page are incorrectly prefixed with `/`.

### Expected behavior

I expect the URLs to point to http://0.0.0.0:9000/q/health-ui.

Not sure exactly what we're doing with the URLs but we are supposed to have a framework to safely resolve them so let's try to understand exactly why they are prefixed with `/`.

### Actual behavior

The URLs point to `/http://0.0.0.0:9000/q/health-ui` which will direct you to http://localhost:8080/http://0.0.0.0:9000/q/health-ui.

### How to Reproduce?

Unzip this app (it's just a default app with SmallRye Health):

[management-url-issue.zip](https://github.com/user-attachments/files/17868258/management-url-issue.zip)

Start dev mode.

Go to http://0.0.0.0:9000

Image

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #44639

Peek 2024-11-25 11-06

### CODE REVIEW

**Comment by gsmet** [comment]
Isn't it a bit confusing that we don't display the whole host:port when it's not the same as the current URL?

**Comment by phillip-kruger** [comment]
@gsmet ok I have changed it to show the full path. This is also more in line with the Endpoints page in Dev UI:

image

**Comment by gsmet** [comment]
@phillip-kruger last question: how are they sorted? It looks very random with Health stuff being mixed with other stuff?

**Comment by phillip-kruger** [comment]
@gsmet It is ordered based on the distance from root (or in other words, the number of / in the url). I have change this to be alphabetic by default, and added a button to toggle between alphabetic and distance from root.

Peek 2024-11-25 11-06

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
OK, not entirely sure about the necessity of being able to sort by distance but I suppose it won't hurt :).

Nice improvements!

Also now, by default, standard and management interfaces will be on the same host so order will make more sense (we won't have management first).

**Pull request merged**
