### PR TITLE
Panache EntityBase should flush on the right entity manager

### LINKED ISSUE #24394: Panache: give a flush() method that pinpoints the right PU
### Description

I'm using multiple named PUs.

There are two ways to `flush()` from a Panache repository

- `persistAndFlush()` which is fine IF I want to store an entity itself... But If I run several `update()` and then I want to flush, persistAndFlush is not the correct answer.
- then there is `flush()`: it works only on the default PU, which is not my case since the repo's entity is configured within a named PU

Any advice?

### Implementation ideas

Maybe the `flush()` method could get an argument that pinpoints the right PU (an entity Class instance?)

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #24394

### CODE REVIEW

**Comment by gsmet** [comment]
You saw me coming but no tests? We should at least have a test that calls the method to make sure it doesn't fail altogether.

**Comment by loicmathieu** [comment]
@gsmet there is already test on this method, I'm not sure we can easily check that we flush the right entity manager. The current test call the method but made no assertion. 

This is also a breaking change but I don't think there is a hight risk that someone rely on the wrong behaviour of the current situation.

**Comment by gsmet** [comment]
> there is already test on this method

OK, good, then.

**Comment by loicmathieu** [comment]
Well, hum, I'm a little ashame as tests didn't pass and I didn't notice it because I use `mvn clean install` instead of `mvn clean test` ont the tests :(.
I prepare a fix, sorry for that.

**Comment by loicmathieu** [comment]
@gsmet it can work with this hacky code (I need to add safeguard to it to cover possible corner cases): 

```
     */
    default void flush() {
        Class<?> entityClass = findEntityClass(this.getClass());
        INSTANCE.getEntityManager(entityClass).flush();
    }

    default Class<?> findEntityClass(Class<?> theClass) {
        if (theClass.getGenericInterfaces().length > 0) {
            return ((Class<?>) ((ParameterizedType) theClass.getGenericInterfaces()[0]).getActualTypeArguments()[0]);
        }

        // if the type is not generic we climb up the hierarchy of classes
        return findEntityClass(theClass.getSuperclass());
    }
```

This issue is that I need to find the entity class wich is the parameterized type of the PanacheRepository/PanacheRepositoryBase interface or any custom interface or abstract type that a user may define on top of them ...

Even if it's less practicle to use, I wonder if we should deprecate `flush()` and introduce flush(Class<? extends PanacheEntityBase>)` instead as finding the right entity class may be tricky ?

**Comment by gsmet** [comment]
Don't we already have code that could take care of that when generating the classes? I mean it's not a good idea to resolve that at execution time given we know what it will be at build time.
How do we do it for the other methods?

And no, we don't want a `flush(Class)`, especially in Panache when things should be simple.

**Comment by loicmathieu** [comment]
@gsmet yes but it didn't work for flush, I'll dig a little more, I don't want a `flush(class)` neither.

**Comment by loicmathieu** [comment]
@gsmet the current PR should fix the issue, the flush method on the Java Panache repository was not correct (the Kotlin one was) as it didn't use the bytecode enhancement `getEntityManager` method.

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
