### PR TITLE
Qute template scanning - fix case-insensitivity problem on Windows

### LINKED ISSUE #18736: Mailer Template Error:  the return value of  TemplateProducer.template() is null
### Describe the bug

I use the following checked templates with quarkus mailer:
```
@CheckedTemplate
public class Templates {
  public static native MailTemplate.MailTemplateInstance success(String name);

  public static native MailTemplate.MailTemplateInstance error(String name);
}
```
I'm able to use those template in dev mode and in test. but when the jar is built, It's throwing an NPE.

### Expected behavior

The mail is templated correctly

### Actual behavior

```
java.lang.NullPointerException: Cannot invoke "io.quarkus.qute.Template.instance()" because the return value of "io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.template()" is null
        at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.templateInstance(TemplateProducer.java:174)
        at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.renderAsync(TemplateProducer.java:155)
        at io.quarkus.mailer.runtime.MailTemplateInstanceImpl$1.get(MailTemplateInstanceImpl.java:122)
        at io.quarkus.mailer.runtime.MailTemplateInstanceImpl$1.get(MailTemplateInstanceImpl.java:117)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$UniHandler.subscribe(UniAndCombination.java:203)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.run(UniAndCombination.java:71)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.access$000(UniAndCombination.java:53)
        at io.smallrye.mutiny.operators.uni.UniAndCombination.subscribe(UniAndCombination.java:50)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:54)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
        at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:42)
        at org.acme.services.MailerService.send(MailerService.java:26)
        at org.acme.services.MailerService_ClientProxy.send(MailerService_ClientProxy.zig:157)
        at org.acme.GreetingResource.hello(GreetingResource.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

### How to Reproduce?

Reproducer: https://github.com/rmanibus/quarkus_18736

1) mvn install
2) mvn quarkus:dev 
3) curl localhost:8080/hello -> template is working
4) mvn install && java -jar target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
5) curl localhost:8080/hello -> an exception is thrown

### Output of `uname -a` or `ver`

windows

### Output of `java -version`

15.0.1

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #18736

### CODE REVIEW

**Comment by mkouba** [comment]
Hm, the fix obviously did not help..

**Comment by mkouba** [comment]
So it seems that [`archive.addAsResource(new StringAsset("Hello!"), "Templates/bing.html")`](https://github.com/quarkusio/quarkus/pull/18744/files#diff-0fa3a3177757c25303eab92599c630e77ce280b124034312f89c85a6a71bed09R22) results in `D:\a\quarkus\quarkus\extensions\qute\deployment\target\quarkus-unit-test5923005184557091681\templates\bing.html` on Windows and I have no idea why...

@gsmet @stuartwdouglas @geoand @FroMage ^ any idea?

**Comment by geoand** [comment]
> @gsmet @stuartwdouglas @geoand @FroMage ^ any idea?

I don't unfortunately

**Comment by mkouba** [comment]
It seems that on Windows if you attempt to resolve the path `templates` against the root directory via `Path.resolve()` then it returns the path of value `templates` even if the existing dir is `Templates` and `Files.exists()` returns also true which is probably OK in a case-insensitive environment. We'll have to obtain the real names from the root dir and compare them instead.

**Comment by mkouba** [comment]
Guys, if you think that the current solution is OK I'll need an approval ;-)

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Given it's done at build time, I suppose we can live with this. Thanks!

**Pull request merged**
