### PR TITLE
Make VertxHttpExporter more robust

### PR DESCRIPTION
**Pull request by geoand**
- Relates to: #35686
- Similar to: #38895

### CODE REVIEW

**Comment by famod** [comment]
Thanks! I've deployed this change to my test env and I'll be monitoring it for at least an hour.

**Comment by geoand** [comment]
🙏🏼

**Review by famod — APPROVED** [review]
Test successful! (on top of 3.8.0)

Code LGTM, but I only scanned it briefly. So better wait for @brunobat.

PS: I think both exporters should log something in DEBUG on retry, but that can be added later on.

**Comment by geoand** [comment]
That's awesome, thanks a lot @famod!

**Review by brunobat — APPROVED** [review]
Thanks @geoand The code now seems clearer to me and looks more reusable... Seems it will be simpler to send logs and metrics in the future. 
@famod thanks very much for testing the code in a real environment.

**Comment by geoand** [comment]
👌

**Pull request merged**
