### PR TITLE
Remove now obsolete guide

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand my understanding is that somehow the `kubernetes.adoc` is now replacing this one? If true maybe we should rename it to the name we had here to be consistent with the other deploying- guides.

Maybe better to have a quick chat on Zulip.

**Comment by geoand** [comment]
I'm out for an hour or so, so if you need to do something now, go ahead 😎

**Comment by gsmet** [comment]
No it can wait.

**Comment by geoand** [comment]
@gsmet pretty much yeah - `kubernetes.adoc` now does it all :)

**Pull request merged**
