### PR TITLE
Implement Apicurio Registry Dev Service sharing

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
@Ladicek the CI complains about a format issue.

**Comment by Ladicek** [comment]
Ouch! :-) Should be fixed now.

**Comment by Ladicek** [comment]
Gotta look into this.

**Comment by Ladicek** [comment]
Nah, can't make it fail locally :-/

**Comment by Ladicek** [comment]
I'm inclined to say that the failing test, which verifies continuous testing, can't be affected by this PR and must be flaky. Also, the only reason why `quarkus-smallrye-reactive-messaging-kafka-deployment` has a test-scoped dependency on `quarkus-apicurio-registry-avro-deployment` is because of `DefaultSerdeConfigTest`.

**Pull request merged**
