### PR TITLE
Include removed dependencies in the ApplicationModel

### PR DESCRIPTION
**Pull request by ia3andy**
DependencyFlags.REMOVED was added to represent dependencies removed from the classloaders.
And ApplicationModel now allows to get dependencies with a specific flag.

### CODE REVIEW

**Review by ia3andy — COMMENTED** [review]
Tested with Maven and Gradle thanks

**Comment by ia3andy** [comment]
@aloubyansky I can't approve as I created the PR :-)

**Comment by aloubyansky** [comment]
Well, I can't approve it either :D

**Comment by ia3andy** [comment]
@aloubyansky I approve it (you can approve it)

**Comment by aloubyansky** [comment]
No, I really can't :) Either I need to open a new PR or somebody else should approve.

**Comment by ia3andy** [comment]
Lol I've asked @maxandersen to approve 😅

**Comment by ia3andy** [comment]
deadlock

**Review by aloubyansky — APPROVED** [review]
Ah, i can approve it, sorry.

**Pull request merged**
