### PR TITLE
Housekeeping: Remove all @author tags in javadoc

### PR DESCRIPTION
**Pull request by tamaro-skaljic**
Because they don't adhere to the [coding guidelines](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#coding-guidelines).

### CODE REVIEW

**Comment by yrodiere** [comment]
Well that's certainly bold. Policy or not, some people may take offense. 
I'll let @gsmet/@maxandersen/@geoand comment on whether they want to do it.

Whether this happens or not, it would probably be a good idea to add build-time checks to forbid adding new `@author` tags, to conform with the policy that is supposed to "disallow" it. Checkstyle will allow something like that, probably other tools as well.

**Comment by geoand** [comment]
I think we don't need to remove the existing ones, just prevent new ones being added like @yrodiere says

**Comment by maxandersen** [comment]
Only time I would consider this move would be if tooling wouldn't be able to deal with it easily. 

If turns out tooling needs it we should ask the identified authors if ok to remove otherwise yeah it could be considered offensive.

**Comment by Sanne** [comment]
This was proposed already in the past and the authors had objections so we decided to leave the original ones.

**Pull request closed without merging**
