### PR TITLE
Use the project object as the source of dependencies instead of 'connecting' to the project

### PR DESCRIPTION
**Pull request by aloubyansky**
This makes listExtensions, addExtension and removeExtension ~10 times faster.

### CODE REVIEW

**Comment by maxandersen** [comment]
two questions:

1) why removal of tests ? 
2) does this knowingly change anything with respect to depednency chains maybe differ or was the connecting part just completely irrelevant to ever do ?

**Comment by aloubyansky** [comment]
1. Unless there is another kind of CLI (or some other kind of tool) that needs to connect to the project to list, add and remove extensions then the original implementations of those "connector" "BuildFile"s could be kept and the related tests testing those classes directly.
Otherwise, all of them can be removed.

2. I don't see any reason to connect to the project from the "outside" when we are already "inside" the initialized project.

**Review by ia3andy — APPROVED** [review]
Awesome @aloubyansky this will make the CLI (which call the gradle plugin) way faster!

**Comment by maxandersen** [comment]
looks good yeah, and based on @aloubyansky explanation that we already are "inside" the project and my limited understanding of the code I'm +1 on this.

**Review by glefloch — APPROVED** [review]

**Pull request merged**
