### PR TITLE
Make rest-client aware of deployment profiles

### LINKED ISSUE #4983: rest-client doesn't take deployment profile when reading config
_From the mailing list:_

I have the following configuration (Quarkus 0.26.1) in application.properties:

```
%dev.de.wwu.ulb.registry.RegistrationClient/mp-rest/url=http://wwurdm.uni-muenster.de/registration/api/v1
%dev.de.wwu.ulb.registry.RegistrationClient/mp-rest/scope=javax.inject.Singleton
%prod.de.wwu.ulb.registry.RegistrationClient/mp-rest/url=http://registration-service:8080/registration/api/v1
%prod.de.wwu.ulb.registry.RegistrationClient/mp-rest/scope=javax.inject.Singleton
```

to distinguish dev and prod profile. However, the rest client won't get injected when starting in prod profile while

```
de.wwu.ulb.registry.RegistrationClient/mp-rest/url=http://registration-service:8080/registration/api/v1

de.wwu.ulb.registry.RegistrationClient/mp-rest/scope=javax.inject.Singleton
```

works. Shouldn't the first version work as well?

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #4983

### CODE REVIEW

**Comment by geoand** [comment]
@cescoffier @kenfinnigan given that the only proper way to test this is to add a test that includes `%test....` and `%prod....` and the fact that those tests are slow hard to maintain, would you like me to add it or not?

**Comment by gsmet** [comment]
Stupid question: we don't have other areas doing the same mistake? It looks like an honest one.

**Comment by geoand** [comment]
That's a great question, let me check

**Comment by geoand** [comment]
We have a lot of them unfortunately... I am not sure what we should do so close to a release...

**Comment by kenfinnigan** [comment]
Instead of tests, is there a maven plugin we can use that looks for the bad way to retrieve config and fails the build if it's present?

**Comment by kenfinnigan** [comment]
I can fix this one as part of my REST TCK work, as it needs to be rebased anyway

**Comment by geoand** [comment]
@kenfinnigan not sure, but that would fail master unfortunately because there are places where the other way of doing things is valid and is being used and some where I'm not sure. This close to release I am very hesitant to make such across the board changes

**Comment by kenfinnigan** [comment]
Wasn't suggesting now, just trying to think of a way to prevent them from being added in the future

**Comment by geoand** [comment]
@kenfinnigan yes, we will need to address that for sure

**Comment by geoand** [comment]
CI failure seems to be due to Azure infra. I'll restart the failing tests once the others finish

**Comment by kenfinnigan** [comment]
I've included this fix in the REST TCK fixes, so we could close

**Comment by geoand** [comment]
OK, closing as #4954 includes the fix this PR proposed

**Pull request closed without merging**
