### PR TITLE
SmallRye FT integration - make use of transitive interceptor bindings

### LINKED ISSUE #2560: MP rest client interfaces do not support MP FT annotations
SmallRye FT implementation is using an additional interceptor binding `@HystrixCommandBinding` to bind `HystrixCommandInterceptor` to all bean clasess that declare an MP FT annotation (such as `@Fallback`). In order to make it work SM FT portable extension adds `@HystrixCommandBinding` to [all FT annotations](https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/src/main/java/io/smallrye/faulttolerance/HystrixExtension.java#L66-L71) and since interceptor bindings are transitive it works as expected.

However, quarkus does not support transitive interceptor bindings yet and so the `HystrixCommandInterceptor` is not bound to the following rest client interface:
```java
@RegisterRestClient
interface MyClient {

        @Fallback(MyFallback.class)
        @GET
        @Path("/data")
        JsonArray get();
    }
```
WORKAROUND: annotate the rest client with `@HystrixCommandBinding` (this annotation comes from SM FT).

I think we should support transitive interceptor bindings.

### PR DESCRIPTION
**Pull request by mkouba**
- MP rest client interfaces do support MP FT annotations now
- resolves #2560

### CODE REVIEW

**Comment by gsmet** [comment]
CI is failing with:
```
[INFO] Running io.quarkus.smallrye.restclient.ft.RestClientFallbackTest
Found ext: class io.smallrye.context.propagators.rxjava1.RxJava1ContextPropagator
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.193 s <<< FAILURE! - in io.quarkus.smallrye.restclient.ft.RestClientFallbackTest
[ERROR] io.quarkus.smallrye.restclient.ft.RestClientFallbackTest  Time elapsed: 1.193 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor#setupProviders threw an exception: java.lang.NoClassDefFoundError: javax/activation/DataSource
	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:283)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassTestDescriptor.java:361)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllCallbacks(ClassTestDescriptor.java:361)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor#setupProviders threw an exception: java.lang.NoClassDefFoundError: javax/activation/DataSource
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:248)
	... 35 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor#setupProviders threw an exception: java.lang.NoClassDefFoundError: javax/activation/DataSource
	at io.quarkus.builder.Execution.run(Execution.java:124)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:137)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:113)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:108)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor.categorizeProviders(ResteasyCommonProcessor.java:134)
	at io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor.setupProviders(ResteasyCommonProcessor.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:507)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:414)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1429)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 16 more

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor#setupProviders threw an exception: java.lang.NoClassDefFoundError: javax/activation/DataSource
[INFO] 
```

**Comment by mkouba** [comment]
@gsmet it does not seem to be related. Let's wait for the results of `Build_Native_Linux`...

**Review by manovotn — APPROVED** [review]
Looks pretty good!
The CI failures seem misplaced, I tried restarting them.

**Comment by manovotn** [comment]
@mkouba Actually, the CI failures are related, you can reproduce that locally using JDK 11

**Comment by mkouba** [comment]
I don't understand why `javax.activation` is needed? Hm, it probably comes from `org.jboss.resteasy.plugins.providers.DataSourceProvider`...

**Comment by mkouba** [comment]
Also `javax.activation.DataSource` is part of JDK8 (rt.jar).

**Comment by manovotn** [comment]
>I don't understand why javax.activation is needed? Hm, it probably comes from org.jboss.resteasy.plugins.providers.DataSourceProvider...

That was my guess as well but I didn't go deeper.

> Also `javax.activation.DataSource` is part of JDK8 (rt.jar).

Yea, but you don't have rt.jar in JDK 9+, do you?

**Comment by mkouba** [comment]
> Yea, but you don't have rt.jar in JDK 9+, do you?

No, but it explains why it works on JDK8.

**Comment by mkouba** [comment]
@gsmet Do you have an idea what's going on?

**Comment by mkouba** [comment]
So I think the problem is that `jakarta.activation` is a dependency of `resteasy-server-common/runtime/pom.xml` but it should be a dependency of `resteasy-common/runtime/pom.xml` instead, because an app does not need to depend on the server bits (in our case it's only using the rest client API). I'll try to move this dependency.

**Pull request merged**
