### PR TITLE
Allow @OIDCClientFilter at field level

### LINKED ISSUE #39460: Allow @OIDCClientFilter at field level
### Description

Hi

I'm using quarkus-oidc-client-reactive-filter extension to invoke remote REST calls with a specific JWT.
It's working pretty well, but I've only found the ability to decorate the Service Java Interface with (@RegisterRestClient).
I'd like to do that directly on the injection point. 

now:
```java
@OidcClientFilter("myapp")
public interface ApiController {
```

wished :
```java
@Inject
@RestClient
@OidcClientFilter("myapp")
private ApiController api;
```

Ludovic

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by neoludo**
- Closes: #39460

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot for the contribution, however I am against this for reasons explained in my [comment](https://github.com/quarkusio/quarkus/issues/39460#issuecomment-1999061314) on the issue.

Furthermore, even if we did decide to implement #39460, the change proposed here would not be enough, there would be a lot more work involved to make it work.

**Comment by neoludo** [comment]
Hi Georgios,

I was guessing that just adding this would not be enough....
I can go a bit further and propose the full implementation, but as I understand, I have to convince you before :)

In our company, we are pushing api-first programmation with open API specifications.
Those specifications are processed by CI to generate API/models for any technology (Quarkus, Spring boot, legacy JavaEE, C++, ...). So we getting interfaces from dependencies and don't want to duplicate them to add the @OIDCClientFilter annotation.

Another point is that most of the time the same service is deployed for multiple contexts, so on runtime have to be able to call the same API with different OIDC configurations. @OIDCClientFilter can be named, but at Class Level it seems to be a quite useless.

Please let me know if I should continue the work or not.

Thanks in advance
Ludo

**Comment by geoand** [comment]
Thanks for the explanation!

I do understand the rationale behind this, but my problem is that the proposal runs counter to how CDI injection works - i.e. you are trying to configure a bean with metadata (othen than a CDI qualifier) provided at the injection site, rather than that metadata being specified on the bean (in this case rest client) itself.

In my opinion, if you really need this kind of flexibility, you should be using the programmatic API of the REST Client (`QuarkusRestClientBuilder`)

**Comment by vsevel** [comment]
it reminds me of the issue we where having with rest client interfaces requiring `@RegisterRestClient`, as interfaces that are either generated by a sdk, or provided through a jar from the vendor will unlikely contain this annotation. we ended up having to extend the provided interfaces from what I remember.
putting a constraint on annotations being present in the rest client interface gives us a few challenges.

**Comment by geoand** [comment]
But that challenge would also be solved by the use of the programmatic API, would it not?

**Comment by vsevel** [comment]
we can probably do everything programmatically but we would not achieve developer joy on this topic. this would be a hard sell to developers. 
beside we are undertaking a major shift from a proprietary sso solution to oidc. asking developers to replace injected services with a programmatic approach would add some work.
we thought about systematically adding the oidc client filter annotation on the openapi generated interfaces, but this breaks down as soon as we want to negotiate a different token when calling different services. then we would have to customize the sdk generation process for each customer. 
if we want to stay interface centric, rather than injection point centric, then the only thing we see would be to be able to provide build time configuration to specify the filter associated with a given interface.

**Comment by geoand** [comment]
> we can probably do everything programmatically but we would not achieve developer joy on this topic. this would be a hard sell to developers.

I'm all for developer joy, but I don't think having to do:

```java
            Client client = QuarkusRestClientBuilder.newBuilder()
                    .baseUri(URI.create(uri))
                    .register(OidcClientRequestFilter.class)
                    .build(Client.class);
```

is a much of step down :)

> if we want to stay interface centric, rather than injection point centric, then the only thing we see would be to be able to provide build time configuration to specify the filter associated with a given interface.

Interesting, does:

```properties
quarkus.rest-client.test-client.providers=io.quarkus.oidc.client.reactive.filter.OidcClientRequestReactiveFilter
```

not cover your needs?

**Comment by sberyozkin** [comment]
I've commented at #39460.

I'd only recommend coding the client programmatically if it is absolutely necessary, we don't really promote this idea in general. 

But in any case, unfortunately, neither the programmatic approach nor  `quarkus.rest-client.test-client.providers=io.quarkus.oidc.client.reactive.filter.OidcClientRequestReactiveFilter` works in this case as @neoludo was looking at binding filters which use named OIDC clients. For example:

Given `quarkus.oidc-client.client-1.someproperties...` and `quarkus.oidc-client.client-2.someproperties...`, `RestClient1` wants to use a filter which will use OIDC Client `client1` and `RestClient2` wants to use a filter which will use OIDC Client `client2`

So I'm not sure what do to here if the binding at the injection point is rejected - I don't want to ignore a strong concern (thanks Georgios for expressing it), so we need to figure how to do it right

**Comment by sberyozkin** [comment]
I can add a constructor to the filter for it to accept `OidcClient` so that the programmatic approach works - but it will become more complex, as `OidcClient` will have to be created programmatically too. Or another approach is to use custom filter extending the core one and supplying the client id. But both approaches don't scale at all with a lot of REST Client interfaces...

**Comment by geoand** [comment]
> I'd only recommend coding the client programmatically if it is absolutely necessary, we don't really promote this idea in general.

This is not true, we have in our documentation we use it extensively ourselves.


My general point is that you need binding at injection point, you need a different client. Doing it the other way around (although handy for this use case) is totally against everything we have done so far and would also make  complicate the implementation as @Ladicek has mentioned

**Comment by vsevel** [comment]
> This is not true, we have in our documentation we use it extensively ourselves.

if a team asked me, I would have said to use the programmatic approach only if the injected approach did not work. I always favor injection over programmatic by default for ease of use, readability, testing flexibility, ...
it is good (and necessary) that most of what can be done declaratively can be done programmatically for the corner cases, and I am happy that quarkus has good support for it, but to me that is a second choice.

**Comment by geoand** [comment]
Second choice yes, agreed.

But not every use case can be covered by the declarative approach and in my mind, this one is a prime example.

**Comment by Ladicek** [comment]
It should be possible to centralize the usage of programmatic API in a single class that defines a bunch of producers. Everywhere else, you can just continue using injection. That should work for everyone I guess?

**Comment by sberyozkin** [comment]
@geoand 

>My general point is that you need binding at injection point, you need a different client. Doing it the other way around (although handy for this use case) 

This is an important point. I don't want to judge this case in general terms, if this use case is convincing we should address it.

> is totally against everything we have done so far

I don't think we should be constrained by general CDI or other consideration, it is not going against Quarkus prnciples or whatever

> and would also make complicate the implementation as @Ladicek has mentioned

It may, the question is, if the use case is convincing.

Like I said, I don't think either the programmatic or the proposed configuration level solution works.
Can you think about something else ?

**Comment by geoand** [comment]
> if this use case is convincing we should address it.

The use case can already be addressed in one of the few ways thay myself and @Ladicek have already mentioned

> I don't think we should be constrained by general CDI or other considerations, it is not going against Quarkus principles or whatever

It's not being against CDI per-se, it's simply about introducing an inverse way of configuring things for a very very specific use case - that's what I don't agree with.

> Like I said, I don't think either the programmatic or the proposed configuration level solution works. 

I still don't understand why this is the case

**Comment by sberyozkin** [comment]
@Ladicek 

>It should be possible to centralize the usage of programmatic API in a single class that defines a bunch of producers. Everywhere else, you can just continue using injection. That should work for everyone I guess?

It probably can

```
Client client = QuarkusRestClientBuilder.newBuilder()
                    .baseUri(URI.create(uri))
                    // OidcClient specific filter
                    .register(new OidcClientRequestFilter() { String client() {return "client1";} })
                    .build(Client.class);
```

and then have these RestClients injected ?

**Comment by sberyozkin** [comment]
@geoand, because each filter  needs to use a specific OIDC client, one can't just register the same filter will all the clients. But then I realized

`register(new OidcClientRequestFilter() { String client() {return "client1";} })`

can do... 

@neoludo @vsevel Can the approach suggested by @Ladicek above work ?

**Comment by Ladicek** [comment]
Yeah, something like

```java
class RestClientProducers {
    @Inject
    @ConfigProperty("foo.uri")
    String fooUri;

    @Produces
    @Singleton // I don't know what's the best scope for the particular use case here
    @Identifier("foo") // or some other qualifier, your choice
    MyRestClient produceFooRestClient() {
        return QuarkusRestClientBuilder.newBuilder()
                .baseUri(URI.create(fooUri))
                .register(new OidcClientRequestFilter() { String client() { return "foo";} })
                .build(MyRestClient.class);
    }
}
```

Then you can simply

```java
@Inject
@Identifier("foo")
MyRestClient fooClient;
```

**Comment by neoludo** [comment]
Of course it will work 😊
But don't want to ask the dev teams to code that in every component.

Maybe we'll code this in one of our extensions, to detect injection points
and create producers automatically...
(as we had made previously in EAP6 as CDI extensions)

Thanks guys for that interesting discussion.

Ludo

Le ven. 15 mars 2024 à 12:36, Ladislav Thon ***@***.***> a
écrit :

**Comment by sberyozkin** [comment]
@neoludo, sure, let us know how it works out for you, thanks

**Comment by gsmet** [comment]
I will close this PR, thanks for raising the issue though and don't hesitate to challenge us on usability issues. Thanks!

**Pull request closed without merging**
