### PR TITLE
Update SmallRye Config to 2.9.2

### PR DESCRIPTION
**Pull request by radcortez**
https://github.com/smallrye/smallrye-config/releases/tag/2.9.2

- Updated the Quarkus config properties Relocator to add the properties in the active profile to support reading the profile parent property from the active profile (this requires SmallRye Config 2.9.2).

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Is this something we want to backport?

**Comment by radcortez** [comment]
I think it can wait until `2.8.0`.

**Comment by edeandrea** [comment]
I think backporting this would be very worthwhile, since RHBQ 2.7 will be based on upstream 2.7, and the "profile being able to set a parent profile" feature would be good to have.

**Comment by radcortez** [comment]
@gsmet can you please backport this one?

Quarkus `2.7.5` is using Smallrye Config `2.9.1. This requires SmallRye Config `2.9.2` with only a couple of fixes, so I believe it won't break anything. 

Thanks!

**Comment by yrodiere** [comment]
Hey @radcortez I see this in [the docs](https://quarkus.io/guides/config-reference#parent-profile):

> Do not use Profile aware files to set quarkus.config.profile.parent. This will not work because the profile is required in advance to load the profile aware files.

Is it still true even after this PR?

**Comment by radcortez** [comment]
Yes. This PR only adds the ability to read the profile parent from a profile-aware property in one of the main sources, not from a profile file.

**Pull request merged**
