### PR TITLE
Upgrade Infinispan to 12.0.1.final

### PR DESCRIPTION
**Pull request by karesti**
Minor latest release upgrade

### CODE REVIEW

**Comment by karesti** [comment]
@gsmet weird failure, launching all my tests locally again just in case (i pushed something wrong juste before)

**Comment by karesti** [comment]
@geoand for a reason I did not run into this dependency build issue before but now I did get it locally: Dependency convergence error for org.wildfly.security:wildfly-elytron-asn1:1.14.2.Final paths to dependency are ...
for all the security dependencies i the hotrod client.
any clue on why is this happening and how to fix it?

**Comment by geoand** [comment]
It seems like that  `io.quarkus:quarkus-infinispan-client` depends on `1.14.2.Final` version of Elytron while hotrod client depends on version `1.13.2.Final`.

You'll need to align to those versions to `1.14.2.Final` which is the elytron version used in Quarkus

**Comment by karesti** [comment]
@geoand ok I was confused since I did not experience any problem with 12.0.0.Final. We will upgrade in infinispan

**Comment by gsmet** [comment]
I force pushed an update that adds some missing WildFly Elytron artifacts to the BOM.

@karesti please at least run locally the basic tests of the extension you change. Thanks! No need to run the full test suite but at least the changed bits.

**Comment by karesti** [comment]
@gsmet yes, I believed I did it, sorry about that, I was doing parallel stuff with quarkus as well

**Review by gsmet — APPROVED** [review]

**Pull request merged**
