### PR TITLE
Reintroduce lost tests in mongodb-client

### LINKED ISSUE #20139: Inconsistency in mongodb-client integration tests
### Description

While checking for Mongo test coverage, we noticed an inconsistency introduced by https://github.com/quarkusio/quarkus/pull/12902.

Originally, there were two tests in `integration-tests/mongodb-client/src/test/java/io/quarkus/it/mongodb/BookResourceTest.java` which were removed:
- `testVehicleEndpoint` (https://github.com/quarkusio/quarkus/pull/12902/files#diff-adad68742f7dc851850e5b594177697da7a5313144b74da9ca4dccfe19e5aeeaL135)
- `testPojoEndpoint` (https://github.com/quarkusio/quarkus/pull/12902/files#diff-adad68742f7dc851850e5b594177697da7a5313144b74da9ca4dccfe19e5aeeaL155)

Their respective endpoints, however, were kept intact:
- `integration-tests/mongodb-client/src/main/java/io/quarkus/it/mongodb/discriminator/VehicleResource.java`
- `integration-tests/mongodb-client/src/main/java/io/quarkus/it/mongodb/pojo/PojoResource.java`

What was the reason for the removal?
Would it be possible to either add the tests back, or remove the related enpoints?

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by jsmrcka**
Fixes https://github.com/quarkusio/quarkus/issues/20139.

### CODE REVIEW

**Comment by jsmrcka** [comment]
@loicmathieu

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks.

I'll merge as soon as CI is OK

**Comment by jsmrcka** [comment]
Great, thanks. I'm working on backport to 2.2 as well.

**Comment by loicmathieu** [comment]
> I'm working on backport to 2.2 as well.

I don't think such changes deserves a backport, it's housekeeping. For backporting, it's usually asked by a label and done by the release manager.

**Pull request merged**
