### PR TITLE
Add caffeine integration tests

### PR DESCRIPTION
**Pull request by lburgazzoli**
Reproducer for https://github.com/quarkusio/quarkus/issues/3300

### CODE REVIEW

**Comment by Sanne** [comment]
hi @lburgazzoli could you try again and maybe rebase the PR?

**Comment by cescoffier** [comment]
Closing due to inactivity.

**Comment by Sanne** [comment]
hum, ok but there's valuable stuff in here.

@lburgazzoli : not urgent but would be great if you could make a note about this so to ressurrect this work whenever you have a moment?

**Comment by lburgazzoli** [comment]
@Sanne @cescoffier sorry, I've missed your mentions. 
I've re-create the PR, see https://github.com/quarkusio/quarkus/pull/5426

**Pull request closed without merging**
