### PR TITLE
JVM args should be aware of quotes

### LINKED ISSUE #10166: -Dquarkus.args cannot handle more than one argument in command line
**Describe the bug**
When running applications in Maven with more than one command line argument for `-Dquarkus.args`, Quarkus is not capable of handling those arguments and passing them to the application

**Expected behavior**
In the example code linked below in reproduction steps, the expected behaviour is for the program to take 2 arguments (`--name` and `--day`) which should produce a message of `Hello {name}! Today is {day}`

**Actual behavior**
The console outputs help text for either Java or Maven

**To Reproduce**
1. Clone example [repo](https://github.com/rt-chang/quarkus-command-line-demo)
2. Enter the command `./mvnw quarkus:dev -Dquarkus.args="--name=Bob --day=Monday"` (or any other values for the arguments)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [Version 10.0.17763.1282]`
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - GraalVM version (if different from Java): `20.1.0`
 - Quarkus version or git rev: `Quarkus 1.5.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
Also tried the following:
- Attempted to escape the quotes as suggested by @geoand in the Zulip chat (ie. ` ./mvnw quarkus:dev -Dquarkus.args=\"--name=Bob --day=Monday\"`
- Attempted to use commas as delimiters between arguments

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #10166

### CODE REVIEW

**Comment by gastaldi** [comment]
@rt-chang can you build this locally and see if it works for you? Build with `mvn clean install -DskipTests -DskipITs` 

Here is what you need to change in your pom.xml to use this version 

```diff
diff --git a/pom.xml b/pom.xml
index c067781..95e7bc5 100644
--- a/pom.xml
+++ b/pom.xml
@@ -12,10 +12,10 @@
     <maven.compiler.target>11</maven.compiler.target>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
-    <quarkus-plugin.version>1.5.2.Final</quarkus-plugin.version>
-    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
+    <quarkus-plugin.version>999-SNAPSHOT</quarkus-plugin.version>
+    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
     <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
-    <quarkus.platform.version>1.5.2.Final</quarkus.platform.version>
+    <quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>
     <surefire-plugin.version>2.22.1</surefire-plugin.version>
   </properties>
   <dependencyManagement>
```

**Comment by gastaldi** [comment]
BTW this is how I tested it:

`./mvnw -Dquarkus.args="--name=Bob --day=Monday" quarkus:dev`

**Comment by rt-chang** [comment]
@gastaldi I attempted to make those pom changes you highlighted, but get the following error:

image

**Comment by gastaldi** [comment]
@rt-chang you need to build my PR locally first

**Comment by rt-chang** [comment]
I was able to pull your branch, build locally, and verify that my pom was pulling the snapshot version. On my machine, when I run the app to test, I still got the same output.

Unsure if it is a local issue on my end or if it is a Windows issue. Unfortunately don't have another machine to test this on

**Comment by gastaldi** [comment]
@rt-chang no problem, I'll try it on a Windows 10 machine and see how that goes. Thank you!

**Review by geoand — APPROVED** [review]
Seems reasonable to me but let's wait and see if it solved OPs issue

**Comment by gsmet** [comment]
@gastaldi I think we should promote that one. It seems like the right thing to do.

**Comment by gastaldi** [comment]
I tested on Windows and it didn't fix the problem, that's why I haven't
promoted yet. But it fixes in Fedora, so I'll promote it :)

Em Qui, 25 de jun de 2020 12:02, Guillaume Smet <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment]
Ah you already did, thanks

**Comment by gsmet** [comment]
Yeah, even if it's not enough, it's still better than what we did before.

**Pull request merged**
