### PR TITLE
Added detailed for deploying to OpenShift and how to test the app

### PR DESCRIPTION
**Pull request by jackhu008**
Relating to issue #11730  and complement PR https://github.com/quarkusio/quarkus/pull/12356

Hi @geoand, further to the completion of PR 12356 which improves "Deploying to OpenShift" document, I raise this PR to improve the OpenShift deployment section of the "Deploying to Kubernetes" document  and also link it to the "Deploying to OpenShift" document.  I hope this would help other developers to avoid the difficulties that I encountered when I first tried to following the instructions in the "Deploying to Kubernetes" document.  Jack

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
Thanks for this, but to be completely honest, I don't see it bringing much to the table for new users.

@gastaldi WDYT?

**Comment by gastaldi** [comment]
@geoand I'm afraid I personally don't have any opinion on this, so I'll let you to decide :wink:

**Comment by geoand** [comment]
:+1:

**Comment by jackhu008** [comment]
Hi @geoand thanks for reaching out to @gastaldi for a second opinion.  The instructions in this documents did not work for me for trying to deploy the sample application to OpenShift.  It would be useful to find another person to try them out to see if he or she could follow the document and deploy the application to OpenShift.

I only worked out how to use the openshift.json as suggested here to deploy the application to OpenShift after I had learnt how to deploy to OpenShift from the "Deploying to OpenShift" document and did a fair amount of trial and error.  From my experience, I found that the following key details are missing from this document:

- remove kubernetes and jib dependencies from the pom.xml -  by running the command `./mvnw quarkus:remove-extension -Dextensions="kubernetes, jib"`

- add openshift as depdency `./mvnw quarkus:add-extension -Dextensions="openshift"`

- add the build extension in the "./mvnw clean package" command, i.e. `./mvnw clean package -Dquarkus.container-image.build=true`

With those changes, the deployment command `oc apply -f target/kubernetes/openshift.json` would work.  

-

**Comment by geoand** [comment]
@iocanel what's your take on this?

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
@iocanel I'll let you merge if you like this since I am +0 on this one.

**Comment by iocanel** [comment]
@geoand: why are you reluctant? Anything I may have missed?

**Comment by geoand** [comment]
It's just that I don't see it adding much value, but I might be to used to the whole process.

**Pull request merged**
