### PR TITLE
Fix Deadlocks using CreateProject with multiple threads

### LINKED ISSUE #3388: Having Deadlocks using CreateProject with multiple threads
**Describe the bug**
I need to use `CreateProject` in a rest api, therefore, it needs to be threadsafe.
I run into Deadlock when calling it will multiple threads.

**Expected behavior**
CreateProjects in a multithreading env without problem

**Actual behavior**
Deadlock

**To Reproduce**
- Create a unit test calling CreateProject in multiple threads

### PR DESCRIPTION
**Pull request by ia3andy**
- Renamed `QuarkusTemplate` to `ProjectGenerator` for clarity.
- Renamed `TemplateRegistry` to `ProjectGeneratorRegistry` for consistency.
- Renamed `ProjectGeneratorRegistry.createTemplateWith()` to `TemplateRegistry.get()` for consistency, it does not create it.
- Renamed `BasicRest` to `BasicRestProjectGenerator` for consistency.
- Add concurrency test for `CreateProject` that is not passing because of dead lock.
- Add tests for `ProjectGenerator` that are not passing because of path inconsistency and dead lock.
- Add mockito dependency to mock `ProjectWriter` and verify calls.
- Remove state in `BasicRestProjectGenerator` to make it threadsafe, the multithreads tests now passes.
- Make paths more consistent with `ProjectWriter`: never add the trailing slash in dirs, but only when using it, the test now passes.

Closes #3388

### CODE REVIEW

**Comment by ia3andy** [comment]
I am currently splitting it into two commits (rename then changes) to make it easier to review

**Comment by gsmet** [comment]
There is a formatting issue: please run `mvn process-sources` then amend your commits.

**Comment by ia3andy** [comment]
@gsmet ok I've run it ;-)

I also splitted the commits to have each different actual parts separated

**Comment by gsmet** [comment]
Note: we need this for the launcher to be thread safe.

**Comment by mkouba** [comment]
@gsmet are all comments addressed now?

**Comment by gsmet** [comment]
@mkouba I haven't reviewed it yet. It's on my list before going on PTO. Hopefully, I'll get to it!

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
