### PR TITLE
Do not initialize Jaeger context if span is null

### LINKED ISSUE #13440: Getting NullPointerException for open tracing with jaeger
**Getting NullPointerException for open tracing with jaeger**

**There should not be any exception.**

**Actual behavior**
Exception in thread "pool-8-thread-1" java.lang.NullPointerException
	at io.quarkus.jaeger.runtime.MDCScope.<init>(MDCScope.java:31)
	at io.quarkus.jaeger.runtime.MDCScopeManager.activate(MDCScopeManager.java:17)
	at io.smallrye.opentracing.OpenTracingAsyncInterceptor.applyContext(OpenTracingAsyncInterceptor.java:37)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.jboss.resteasy.microprofile.client.impl.MpClientInvocation$Decorator.lambda$decorate$0(MpClientInvocation.java:90)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Configurations that I used**

quarkus.log.console.format=%p, %d{yyyy-MM-dd HH:mm:ss.SSSZ}, traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled}, [%c{3.}], %s%e%n
# configurations for jaeger
quarkus.jaeger.service-name=load-auth-service
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.jaeger.endpoint=http://localhost:14268/api/traces

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
 - Quarkus version or git rev: 1.7.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
Dependency used for open tracing:
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-opentracing</artifactId>
</dependency>

### PR DESCRIPTION
**Pull request by gsmet**
Might fix #13440 but I have absolutely no idea what I'm doing :).

See my comment here: https://github.com/quarkusio/quarkus/issues/13440#issuecomment-777589753 .

### CODE REVIEW

**Comment by gsmet** [comment]
@Ladicek could you have a look at this one? I see you contributed to `MDCScope` somehow.

**Comment by Ladicek** [comment]
That looks strange, I _believe_ that a non-`null` scope should always have a non-`null` span...

**Comment by gsmet** [comment]
Yeah, that was somehow what I expected but it's not the case in the example provided by the OP.

There is a test case here: https://github.com/quarkusio/quarkus/issues/13440#issuecomment-775278149 (with a README.md explaining how to reproduce).

**Comment by Ladicek** [comment]
Yea I'm playing with that locally. During the entire test, noone starts any tracing anywhere. So when `OpenTracingAsyncInterceptor` (which is a SmallRye OpenTracing thing that propagates OpenTracing spans between RestClient threads) captures a span on the original thread (that invoked the RestClient method), it gets `null`. And when it activates a span on the RestClient "async" thread, it passes down that same `null`. That's where the NPE comes from.

This obviously doesn't happen in case of a synchronous RestClient invocations, because in such case, no span propagation is necessary/attempted.

If I start a span in `@BeforeEach`, then no NPE occurs and the span is correctly propagated.

To me, that looks like a bug in the context propagation thingy. If there's no active span, either one should be started, or tracing should be skipped. I'm leaning towards the latter, because this is merely context propagation -- if there's no span active on the original thread, none should be active on the async thread either.

**Comment by Ladicek** [comment]
I submitted https://github.com/smallrye/smallrye-opentracing/pull/173 with what I think is a proper fix.

The PR is for SmallRye OpenTracing 2.x. For current Quarkus, we'd have to do a release in the SmallRye OpenTracing 1.3.x line, but that should be possible too (cc @radcortez).

**Comment by gsmet** [comment]
OK, I'm closing this PR. Was pretty sure it wasn't the right fix :).

**Pull request closed without merging**
