### PR TITLE
Migrate from config classes to `@ConfigMapping` OIDC token propagation, OIDC GraphQL client and OIDC client filters

### PR DESCRIPTION
**Pull request by michalvavrik**
Small part of https://github.com/quarkusio/quarkus/issues/39185 effort. I'll follow with other small PRs.

According to Maven central, there are no known usages (like in Quarkiverse):

- https://mvnrepository.com/artifact/io.quarkus/quarkus-oidc-token-propagation/usages
- https://mvnrepository.com/artifact/io.quarkus/quarkus-oidc-token-propagation-reactive/usages
- https://mvnrepository.com/artifact/io.quarkus/quarkus-oidc-client-graphql/usages
- Https://Mvnrepository.Com/Artifact/Io.Quarkus/Quarkus-Oidc-Client-Reactive-Filter/Usages

Quarkus OIDC Client Filter is used by https://mvnrepository.com/artifact/io.quarkus/quarkus-oidc-client-filter/usages:
- https://github.com/quarkiverse/quarkus-openapi-generator (cloned, checked, no config class usage)
- FoundationDB API Client (I've looked for this project for 20 minutes, I have no idea whether project exists or where are it's source codes, can't find anything about it)
- https://github.com/kiegroup/kogito-runtimes/tree/main/quarkus/integration-tests/integration-tests-quarkus-openapi-client (cloned, checked, no config class usage)
- https://github.com/kiegroup/kogito-runtimes/tree/main/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test  (cloned, checked, no config class usage)

Please feel free to squashing commits during merging, I wasn't sure whether it's good idea to have them as one commit, but they are tiny changes.

### CODE REVIEW

**Review by gsmet — DISMISSED** [review]
These modules are part of the big REST rename PR that I'm working on for 3.9 so I would prefer if we don't merge these changes yet and solve the conflicts in this small PR rather than in the very large one.

**Comment by michalvavrik** [comment]
> These modules are part of the big REST rename PR that I'm working on for 3.9 so I would prefer if we don't merge these changes yet and solve the conflicts in this small PR rather than in the very large one.

sure, can you link the PR?

**Comment by michalvavrik** [comment]
I'll make it draft as it depends on Guillaume PR, but @sberyozkin please consider it ready for your feedback if you have one and time for it. Thanks

**Comment by michalvavrik** [comment]
Found it https://github.com/quarkusio/quarkus/pull/39159.

**Comment by gsmet** [comment]
@michalvavrik yeah sorry, it wasn't ready and I was still actively working on it. It should be in a better shape now :).

**Review by sberyozkin — APPROVED** [review]
LGTM, waiting for  @gsmet to give a go ahead

**Comment by michalvavrik** [comment]
Yeah, I need to rebase on the current main as the #39159 is merged.

**Comment by sberyozkin** [comment]
@michalvavrik Yes, indeed, I see @gsmet merged his PR. Let me merge this one

**Pull request merged**
