### PR TITLE
Fix for issue 42549 - replaces oidc auth github screenshots with more generic ones

### PR DESCRIPTION
**Pull request by rghara**
Fix replaces oidc auth github screenshots with more generic ones

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @rghara , LGTM, I'd like to ask you to do a few minor updates, please name the application as `Quarkus Github`, it is actually an Oauth2 aware application, but it wiul still be a bit technical.
And if you don't mind have a callback URL like `http://localhost:8080/github`, since `userinfo` can cause some confusion due to the association with `UserInfo`

**Comment by sberyozkin** [comment]
Hi @rghara It is ready to go now but  the rebasing did not work out, I guess it is simplest at this stage to close this PR and open a new one, and I'll merge. Would you like to go ahead and replace this PR ? Note it does not fix the linked issue as a few other Renarde references remain in some other application setups there, but fixing Github instructions is important

**Comment by rghara** [comment]
> Hi @rghara It is ready to go now but the rebasing did not work out, I guess it is simplest at this stage to close this PR and open a new one, and I'll merge. Would you like to go ahead and replace this PR ? Note it does not fix the linked issue as a few other Renarde references remain in some other application setups there, but fixing Github instructions is important

@sberyozkin 
I think I need to create a new branch all together

**Comment by rghara** [comment]
@sberyozkin
Create a new pull request. It seems it is passing the checks.
https://github.com/quarkusio/quarkus/pull/44023

**Pull request closed without merging**
