### PR TITLE
Minor style edits to security architecture doc

### PR DESCRIPTION
**Pull request by michelle-purcell**
To enhance and apply style as per the [Quarkus docs contributor style guide](https://quarkus.io/guides/doc-reference).

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
Thanks Michelle

**Comment by michelle-purcell** [comment]
Thanks @sberyozkin :superhero:

**Comment by rsvoboda** [comment]
This is minor change, imho doesn't need qe prioritization for the input. Removing qe label.
If you think our presence is needed, please put the label back and elaborate on the reasoning. Thank you.

**Comment by michelle-purcell** [comment]
Thanks for clarifying, @rsvoboda :+1:

**Pull request merged**
