### PR TITLE
Java inter-op for Kotlin Maven template

### PR DESCRIPTION
**Pull request by oztimpower**
Enhance Maven Kotlin template pom to permit Kotlin to co-exist, **optionally**, with Java.  It is inevitable that Java code needs to be integrated into a Kotlin project.

Implemented and tested as per Kotlin Maven guide:
https://kotlinlang.org/docs/reference/using-maven.html

### CODE REVIEW

**Comment by geoand** [comment]
@oztimpower could you please ping me in the beginning of next week so I can test this if I haven't done in by then? Time is kind of tight now, sorry :)

**Comment by oztimpower** [comment]
Reminder to test this one, #5046  and #5032 - Kotlin template enhancements for Maven and Gradle, now that 0.28 is released.

**Comment by geoand** [comment]
Thanks @oztimpower! I'm at a conference this week so this will probably slip until next week.

Thanks for your time on this 👌

**Comment by geoand** [comment]
@oztimpower Thanks for this!

Can I ask you to rebase onto the master? I tried restarting CI but without much luck.
Once that's done, we can get this one in.

**Comment by geoand** [comment]
@oztimpower was this closed by accident perhaps?

**Comment by oztimpower** [comment]
Yes…

Trying to recover it.  I forced pushed and lost my changes.

**Comment by geoand** [comment]
Oh darn...

In similar cases in the past git reflog has saved me :)

**Comment by oztimpower** [comment]
Thanks, got it back it now.

**Review by geoand — APPROVED** [review]
Excellent, thanks again @oztimpower!

**Comment by oztimpower** [comment]
@geoand any chance the Azure pipeline could be restarted for those that did not complete successfully?  Errors are unrelated to the change.

**Comment by geoand** [comment]
@oztimpower I pushed the button, let's see what happens :)

**Comment by machi1990** [comment]
I re-run CI yesternight without success. @oztimpower can you rebase on top of master to pick up latest modifications? I hope that will fix the CI issue. Thanks.

**Comment by geoand** [comment]
Thanks for bringing this one back to my attention @machi1990.

I'll check it out tomorrow so we can most likely get it in.

**Comment by geoand** [comment]
@oztimpower I just tried this and it seems like the dev mode no longer works after the change is applied.
Have you encountered that?

Also, the test project (specified [here](https://github.com/quarkusio/quarkus/tree/2787aeb7b59ebb47414f68c2e6565ec71b4b2162/integration-tests/kotlin/src/test/resources/projects/classic-kotlin) and used [here](https://github.com/quarkusio/quarkus/blob/2787aeb7b59ebb47414f68c2e6565ec71b4b2162/integration-tests/kotlin/src/test/java/io/quarkus/kotlin/maven/it/KotlinDevModeIT.java#L21)) would need to be updated to reflect this and test dev mode

**Comment by oztimpower** [comment]
Got it, I must confess I hadn't tried Dev mode.  Let spend some more time on it.

**Comment by geoand** [comment]
Thanks @oztimpower!

**Comment by gsmet** [comment]
Any progress on that one?

**Comment by oztimpower** [comment]
Apologies a bit busy with re:Invent. Will have more time afterwards to wrap it up.

**Pull request closed without merging**
