### PR TITLE
Document DevServices container's database name and credentials

### PR DESCRIPTION
**Pull request by Mahaswami**

### CODE REVIEW

**Review by Sanne — APPROVED** [review]
Nice! thanks

**Review by gsmet — CHANGES_REQUESTED** [review]
Please don't merge right away, I will do some minor tweaks to the wording.

**Review by gsmet — CHANGES_REQUESTED** [review]
After giving it more thoughts, I don't think we can accept this PR as is. It only talks about PostgreSQL and things can be different for the various databases we support.

We would need to clearly state the various configurations for the supported databases.

Also I don't understand the thing about the container IP? And it would be nice to talk about the `port` option because if you want to access the started container, there's a good chance you will want to use this option to use a fixed port.

Are you willing to work more on this?

**Comment by Mahaswami** [comment]
@gsmet Currently there is no way to know how to access any database from tools like psql or IDE database tools. It took me more than a couple of hours before I realised that the only way to find this is to deep dive to get the connection object in the runtime to inspect. I doubt other people have the time or skills to know how to do this. The purpose of DevServices is to make development start quickly so not having tools to view db data makes the DevServices thing much less valuable to me as user.

I shared this PR because I don't want other people to waste time like this. At the moment, I do not have time to do this for every database. If someone knowing the exact source code location can put in the MySQL it would be great. I am happy to edit the PR if you can point to the github repo file to find this.

My suggestion is to add a TODO tag for other databases and put this in the documentation so as to avoid at least other Postgresql people from getting stuck now (It has already been more than two weeks since I submitted the PR beginning from putting it in the other repo). 

I am interested in to creating a separate PR to configure the port number at docker level to avoid random ports. It is indeed quite a waste of time to dig into port each time I need to use IntelliJ to run a Liquibase db migration.

**Comment by gsmet** [comment]
Closing this one. I will work on a more comprehensive one.

Thanks for raising your concerns about this and providing a PR.

**Pull request closed without merging**
