### PR TITLE
convert Javadoc of configuration properties to Asciidoc

### LINKED ISSUE #3433: Convert Javadoc of configuration properties to Asciidoc
Replace the Javadoc for `@ConfigItem` and friends to Javadoc format.

Make sure the documentation is useful for people and complete. It will be what the guide will show.

From 

```
        /**
         * Schema genration config
         * The default is {@code none}.
         * <p>
         * Same as JPA's javax.persistence.schema-generation.database.action.
         */
        @ConfigItem
        public Optional<String> generation;
```

Go for 

```
        /**
         * Select whether the database schema is generated or not.
         * Options are `none`, `create`, `drop-and-create`, `drop`, `update`}.
         * The default is `none`.
         *
         * `drop-and-create` is particularly useful in Quarkus Lice Coding mode
         * 
         * Same as JPA's javax.persistence.schema-generation.database.action.
         */
        @ConfigItem
        public Optional<String> generation;
```

All extensions should use that model.

### PR DESCRIPTION
**Pull request by machi1990**
Fixes #3433

/cc @emmanuelbernard @gsmet

### CODE REVIEW

**Comment by n1hility** [comment]
@machi1990 sorry for the delay on this one. Not sure if @emmanuelbernard mentioned this, but we were thinking about using AsciiDoclet for processing the configuration classes, and then coming up with a summarization strategy for the configuration file. What do you think about this approach?

**Comment by machi1990** [comment]
> @machi1990 sorry for the delay on this one. Not sure if @emmanuelbernard mentioned this, but we were thinking about using AsciiDoclet for processing the configuration classes, and then coming up with a summarization strategy for the configuration file. What do you think about this approach?

@n1hility thanks for the feedback, I saw that in the mailing list. We can add AsciiDoclet, also if there is a summarization strategy defined (was it reading only the first paragraph when generating an `example.properties` file?) I can work on it this weekend to make this PR ready for review. Once this PR lands, it will be a huge step for the doc generation part.

**Comment by dmlloyd** [comment]
This seems ill-advised to me: all existing tooling (IDEs) will not know what to do with asciidoc in javadoc blocks and expect doc tags, taglets, and HTML.  Why again do we not parse javadoc correctly and then emit the needed result on the back end?  Seems very, very unclear to me and also does not really match the config design either to do it this way.  Augmentation could probably produce these docs much more simply since all the inputs are there, just like for example config file generation.  Is it just because nobody is able to correctly parse the doc inputs?

**Comment by n1hility** [comment]
@dmlloyd so the idea was to allow for rich docs under a config value instead of just a basic summary and parameter description, by just using asciidoclet on those config based java files (we'd need to figure out the selection mechanism).  The drawbacks are pretty small in the case of just config java files since it's not common (at least for users) to directly refer to them from java and see the IDE popups.  The advantage though is its much easier to write docs for content like this, since the javadoc grammar is quite cumbersome and forces you into raw html.

**Comment by gsmet** [comment]
FWIW, it's not possible right now to have only part of the doc using Asciidoclet. We created https://github.com/asciidoctor/asciidoclet/pull/91 a while ago with Steve for Hibernate ORM 6. Looks like it's time to get this one in, independently from the decision we take for Quarkus. Will do.

**Pull request closed without merging**
