### PR TITLE
Introduce the convenient Qute.fmt() methods

### PR DESCRIPTION
**Pull request by mkouba**
- these static methods can be used anywhere
- the engine used is the one produced by Quarkus

### CODE REVIEW

**Comment by mkouba** [comment]
This basically allows for simple messages powered by qute like `Qute.fmt("Hello {}!", "Martin")`. I think that it could be useful. The API is not polished and docs are missing.

**Comment by mkouba** [comment]
@gastaldi @FroMage @gsmet WDYT?

**Review by gastaldi — APPROVED** [review]
That looks good and useful! 👍🏻

**Comment by famod** [comment]
So if you had code using this tested by a plain and simple unit test, you'd need to setup the engine yourself, right?

**Comment by mkouba** [comment]
> So if you had code using this tested by a plain and simple unit test, you'd need to setup the engine yourself, right?

Not really. If you don't setup the engine the default instance is created lazily. Basically `Engine.builder().addDefaults()` + `ReflectionValueResolver` + special parser hook to turn all empty expressions into index-based expressions.

**Comment by mkouba** [comment]
> Which reminds me that the engine produced by quarkus does not replace the empty expressions...

Fixed.

Moreover, it's also possible to use it together with message bundle interfaces, e.g.  something like `Qute.fmt("{msg:hello}").attribute("locale", Locale.GERMAN).noData()`.

**Comment by famod** [comment]
> > So if you had code using this tested by a plain and simple unit test, you'd need to setup the engine yourself, right?
> 
> Not really. If you don't setup the engine the default instance is created lazily. Basically `Engine.builder().addDefaults()` + `ReflectionValueResolver` + special parser hook to turn all empty expressions into index-based expressions.

That's nice!
Ideally, the docs should mention that there will be a difference if the engine wasn't setup in the "regular" way.
E.g. in my current project we first had a custom engine setup (in production code!) and then we hit an html escaping problem...which is when I realized that `HtmlEscaper` is not part of the defaults.

**Comment by mkouba** [comment]
> Ideally, the docs should mention that there will be a difference if the engine wasn't set up in the "regular" way.

Yes, I'd like to mention this in the javadoc as well..

**Comment by FroMage** [comment]
Yeah, +1

**Pull request merged**
