### PR TITLE
Remove NativeImageMojo

### LINKED ISSUE #14645: Remove NativeImageMojo in 1.13
**Description**
As discussed [here](https://groups.google.com/g/quarkus-dev/c/fZH519p86hM), `NativeImageMojo` was deprecated a long time ago and shall therefore be removed.
`quarkus.package.type=native` is the way to go, see https://quarkus.io/guides/building-native-image

**Implementation ideas**

- [x] log a warning in the mojo (#14634)
- [x] remove remaining usages<sup><a href=#note-1>[1]</a></sup><span id=return-1></span> (#14649)
- [x] remove usages in quickstarts (https://github.com/quarkusio/quarkus-quickstarts/pull/765)
- [ ] remove the class in 1.13 (#14982)

<sub><sup id=note-1>[1]</sup> Remaining usages:<a href=#return-1></a></sub>
```
$ grep -Rl --exclude-dir=.git --exclude-dir=target '<goal>native-image</goal>'
devtools/maven/src/main/resources/create-extension-templates/integration-test-pom.xml
docs/src/main/asciidoc/tika.adoc
extensions/amazon-lambda/maven-archetype/src/main/resources/archetype-resources/pom.xml
extensions/amazon-lambda-http/maven-archetype/src/main/resources/archetype-resources/pom.xml
extensions/funqy/funqy-amazon-lambda/maven-archetype/src/main/resources/archetype-resources/pom.xml
integration-tests/container-image/maven-invoker-way/src/it/container-build-docker/pom.xml
integration-tests/container-image/maven-invoker-way/src/it/container-build-jib/pom.xml
integration-tests/container-image/maven-invoker-way/src/it/container-build-multiple-tags-docker/pom.xml
integration-tests/container-image/maven-invoker-way/src/it/container-build-multiple-tags-jib/pom.xml
integration-tests/container-image/maven-invoker-way/src/it/container-image-push/pom.xml
integration-tests/kotlin/src/test/resources/projects/classic-kotlin/pom.xml
integration-tests/kubernetes/maven-invoker-way/src/it/kubernetes-docker-build-and-deploy/pom.xml
integration-tests/kubernetes/maven-invoker-way/src/it/kubernetes-jib-build-and-deploy/pom.xml
integration-tests/kubernetes/maven-invoker-way/src/it/kubernetes-with-existing-manifest/pom.xml
integration-tests/kubernetes/maven-invoker-way/src/it/openshift-docker-build-and-deploy/pom.xml
integration-tests/kubernetes/maven-invoker-way/src/it/openshift-s2i-build-and-deploy/pom.xml
integration-tests/kubernetes/src/it/openshift-s2i-build-and-deploy/pom.xml
integration-tests/maven/src/test/resources/expected/create-extension-pom-itest/integration-tests/itest/pom.xml
integration-tests/maven/src/test/resources/projects/arc-exclude-dependencies/runner/pom.xml
integration-tests/maven/src/test/resources/projects/classic/pom.xml
integration-tests/maven/src/test/resources/projects/classic-no-build/pom.xml
integration-tests/maven/src/test/resources/projects/classic-no-generate/pom.xml
integration-tests/maven/src/test/resources/projects/classic-no-undertow/pom.xml
integration-tests/maven/src/test/resources/projects/classic-noconfig/pom.xml
integration-tests/maven/src/test/resources/projects/classic-remote-dev/pom.xml
integration-tests/maven/src/test/resources/projects/classic-resource-filtering/pom.xml
integration-tests/maven/src/test/resources/projects/dependency-on-pom/pom.xml
integration-tests/maven/src/test/resources/projects/multimodule/runner/pom.xml
integration-tests/maven/src/test/resources/projects/multimodule-classpath/runner/pom.xml
integration-tests/maven/src/test/resources/projects/multimodule-revision-prop/runner/pom.xml
integration-tests/maven/src/test/resources/projects/multimodule-root-no-src/runner/pom.xml
integration-tests/maven/src/test/resources/projects/native-image-app/pom.xml
integration-tests/maven/src/test/resources/projects/project-with-extension/runner/pom.xml
integration-tests/maven/src/test/resources/projects/property-overrides/runner/pom.xml
integration-tests/maven/src/test/resources/projects/quarkus-index-dependencies/runner/pom.xml
integration-tests/maven/src/test/resources/projects/quarkus.package.output-directory/pom.xml
integration-tests/maven/src/test/resources/projects/rr-with-json-logging/pom.xml
integration-tests/maven/src/test/resources/projects/uberjar-check/pom.xml
integration-tests/maven/src/test/resources/projects/uberjar-maven-plugin-config/pom.xml
integration-tests/neo4j/README.md
integration-tests/scala/src/test/resources/projects/classic-scala/pom.xml
```

### PR DESCRIPTION
**Pull request by famod**
Resolves #14645

PS: A few more usages were introduced since #14649 (might have also missed one back then). This PR removes those again.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@famod could you add a paragraph for this change and the uberJar one there: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13 ?

Thanks!

**Comment by gsmet** [comment]
@famod also we need to check the quickstarts if it has not already been done.

**Comment by famod** [comment]
> @famod also we need to check the quickstarts if it has not already been done.

Did that already two weeks ago: https://github.com/quarkusio/quarkus-quickstarts/pull/765
But I'll re-check. Sometimes in the Quarkus world things change faster than you can type. 😉 

I'll also add something to the Migration Guide.

**Comment by famod** [comment]
@gsmet I've extended the Migration-Guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13
I wouldn't mind some proofreading. 😉

**Pull request merged**
