### PR TITLE
Sys prop configuration to leverage SSL heap buffer pooling

### PR DESCRIPTION
**Pull request by franz1981**
This fix the weird performance problem observed at https://github.com/quarkusio/quarkus/issues/41880#issuecomment-2227334797  

if the users run the quarkus application with 
`-Dquarkus.http.server.ssl.jdk.bufferPooling=true -Dvertx.reuseNettyAllocators=true` (latter, see https://github.com/eclipse-vertx/vert.x/pull/5292)

It is still missing:

- [ ]  Reactive SQL Client SSL 
- [ ]  gRPC SSL
- [ ]  vertx http client-side (if we expose it)

I'm not aware in which other Quarkus extensions (.e.g OTel?) we are using SSL/TLS from Vertx: if we do, we should provide a similar fix there.

### CODE REVIEW

**Comment by franz1981** [comment]
@geoand I'm opened to suggestions on how to better let users to consume it.

To be fair `-Dvertx.reuseNettyAllocators=true` should *always* be set, it's low risk and good impact.
Whilst for `quarkus.http.server.ssl.jdk.bufferPooling` I have tried to make it "hidden" enough, since, with Vertx 5 it will be the default behaviour (both, actually) - and I don't think we want to deprecate or else....

IDK if it's ok the way I've implemented it because `HttpServerOptionsUtils` is consumed by `VertxHttpRecorder`

**Comment by geoand** [comment]
This is more for @cescoffier to decide

**Review by cescoffier — APPROVED** [review]

**Comment by franz1981** [comment]
@mabartos can you please check the checklist in description if TLS/SSL is used in any of the missing changes?

**Comment by geoand** [comment]
> I'm not aware in which other Quarkus extensions (.e.g OTel?) we are using SSL/TLS from Vertx: if we do, we should provide a similar fix there.

Correct

**Comment by franz1981** [comment]
I've quickly verified, by running a debug session vs getting-started (dev branch) - that the 2 args work as intended.
@mabartos need to add them in order to benefit of these changes, but please check if you need to have the gRPC fix and the reactive SQL one

**Comment by mabartos** [comment]
@franz1981 Thanks for these changes! We will probably some more comprehensive analysis after Xmas.

For Keycloak purposes, we don't use gRPC SSL, or reactive SQL SSL. AFAIK, not even Vert.x HTTP client.

**Comment by vsevel** [comment]
I am making a note of it. how should this be tested? where can I expect the improvements?

**Comment by franz1981** [comment]
Thanks @vsevel for the quick response: it should benefit when http (1.1 and 2) TLS/SSL is involved.
If you have other "secured" cases which include gRPC, Reactive SQL, http client side...let me know so I can provide a fix for these too 🙏 

The benefits are both CPU usage and heap allocation pressure, since, without these fixes, on SSL/TLS every decoding/encoding of data just allocate a giant unpooled heap buffer.
These changes uses heap pooled buffers, instead, which despite increases the application idle memory footprint (in terms of heap old gen occupancy) it should reduce the demand under load.

**Comment by franz1981** [comment]
@vsevel any chances you tried `-Dvertx.reuseNettyAllocators=true -Dquarkus.http.server.ssl.jdk.bufferPooling=true`?

**Comment by vsevel** [comment]
unfortunately no @franz1981 
we are finishing up our move to `3.18`. I will do a test in our integration env.

**Comment by vsevel** [comment]
hello @franz1981 we have a simple service with a `/hello` endpoint deployed on our openshift cluster.
I ran this script:
```
name: my-benchmark
http:
  host: https://...:443
  sharedConnections: 20
duration: 60s
usersPerSec: 20
scenario:
  - fetchIndex:
      - httpRequest:
          GET: /hello
```

the backend is running with quarkus `3.18.3` . here are the results with and without the options:
```
native (powered by Quarkus 3.18.3)

without options
PHASE  METRIC      THROUGHPUT   REQUESTS  MEAN      p50      p90       p99        p99.9    p99.99   TIMEOUTS  ERRORS  BLOCKED  2xx   3xx  4xx  5xx  CACHE
main   fetchIndex  19.75 req/s      1185  16.04 ms  7.27 ms  11.40 ms  105.91 ms  1.31 s   1.60 s          0       0     0 ns  1185    0    0    0      0

with '-Dvertx.reuseNettyAllocators=true' '-Dquarkus.http.server.ssl.jdk.bufferPooling=true' on backend
PHASE  METRIC      THROUGHPUT   REQUESTS  MEAN     p50      p90      p99       p99.9      p99.99   TIMEOUTS  ERRORS  BLOCKED  2xx   3xx  4xx  5xx  CACHE
main   fetchIndex  19.88 req/s      1193  9.10 ms  6.68 ms  8.59 ms  52.95 ms  137.36 ms  1.38 s          0       0     0 ns  1193    0    0    0      0
```

we can see that with the options, there are some improvements in all categories. the `mean` especially goes from `16ms` to just `9ms`.
is this what you were expecting?

**Comment by franz1981** [comment]
Lovely and thanks @vsevel and...wow, you are using Hyperfoil - which make me happy twice :)

**Pull request merged**
