### PR TITLE
REST client encoding test

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Test for #10245

This needs to be fixed in RESTEasy, so the test can be merged: https://github.com/resteasy/Resteasy/pull/2456

### CODE REVIEW

**Comment by gastaldi** [comment]
RESTEasy was updated and the test passed locally. Time to mark this PR ready to review

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
Let's not backport the test, I don't think it's worth it.

**Comment by gsmet** [comment]
Hum.

The test is not working on Windows unfortunately:

```
Error:  Failures: 
Error:    RestClientTestCase.testEmojis:51 1 expectation failed.
Response body doesn't match expectation.
Expected: is "????????"
  Actual: 😀😀😀😀😀😀😀😀
```

**Comment by gsmet** [comment]
I somehow missed it when merging.

**Comment by gastaldi** [comment]
It looks like the server part works fine but the test doesn't?

**Pull request merged**
