### PR TITLE
Properly segregate Json MessageBodyReader/Writer classes for server and client

### PR DESCRIPTION
**Pull request by geoand**
Relates to: #30089

### CODE REVIEW

**Comment by sberyozkin** [comment]
Great stuff, thanks @geoand.

**Comment by geoand** [comment]
> Great stuff, thanks @geoand.

You are welcome!

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Does it really fix the original issue? I.e. won't the original issue fail if the client JSON-B part is included? I would somehow expect us to have the Keycloak Admin Client working even in this case.

**Comment by geoand** [comment]
> i.e. won't the original issue fail if the client JSON-B part is included?

I don't really know, I didn't follow the whole discussion. 

> I would somehow expect us to have the Keycloak Admin Client working even in this case.

I agree that the admin client should just work, so if we need to do more work on this (@sberyozkin can comment), then I'll gladly do it

**Comment by sberyozkin** [comment]
I think this hopefully should fix the original problem, since Keycloak Admin Client is using Jackson in the client scope, and a user has confirmed JSONB is used in the server scope. I'll ask to confirm

>I agree that the admin client should just work, so if we need to do more work on this

I was thinking that may be reactive Jackson and JSONB runtime config would have a property like scope=`all/client/server` to support mixing such providers, but not sure it is necessary yet, let me ask the reporter to check the PR

**Comment by gsmet** [comment]
> since Keycloak Admin Client is using Jackson in the client scope, and the user has confirmed JSONB is used in the server scope. I'll ask to confirm

Well, sure. My problem is that IIUC it won't fix the issue if someone is using the client JSON-B part. Or am I mistaken?

The Keycloak Admin Client should work with all combinations of extensions.

**Comment by sberyozkin** [comment]
>My problem is that IIUC it won't fix the issue if someone is using the client JSON-B part. Or am I mistaken?

I think you are right, but I'm not sure it is possible to mix multiple JSON providers in the client or server, as the resteasy reactive providers supported out of the box like Jackson and JSONB are available to all clients if both providers are registered in the client scope.

**Comment by sberyozkin** [comment]
Let me merge, propose to discuss having an option to have in Resteasy Reactive to allow webinding reactive jsonb and jackson providers to specific clients only to address Guillaume's concern, it is already possible I believe with custom providers so ideally it should be optionally possible with these 2 json providers as well

**Pull request merged**
