### PR TITLE
Update to Netty 4.1.70

### PR DESCRIPTION
**Pull request by cescoffier**
See https://netty.io/news/2021/10/11/4-1-70-Final.html.

### CODE REVIEW

**Comment by cescoffier** [comment]
Let's see how it goes. 
also waiting for the insights from the Vert.x team.

**Comment by cescoffier** [comment]
@gsmet This would be for 2.6.

**Review by gsmet — APPROVED** [review]
LGTM.

@cescoffier should we wait for the Vert.x team as you said or should we merge?

**Comment by cescoffier** [comment]
@gsmet it's all good,
We can merge.

**Pull request merged**
